### ISSUE TITLE
is there any configuration for spacing after class and function? 

### ISSUE THREAD

**Issue by mhamri** [prettier/prettier#10012]
I can't see any configuration that adds one line before/after a class/function definition, to prevent this 

![image](https://user-images.githubusercontent.com/8991783/103785904-b6e8b880-5076-11eb-85c9-d4aaae2b7e8a.png)

it is quite unclear where the class finish, where the properties finish, where the constructor begins

if I want to exaggerate the situation, something like this won't get formatted which is wiered

![image](https://user-images.githubusercontent.com/8991783/103786089-f7e0cd00-5076-11eb-8604-bcdd68f5449b.png)

if I remove the coloring it's totally unclear what is what which it's against the purpose of formatting

![image](https://user-images.githubusercontent.com/8991783/103786365-51e19280-5077-11eb-9dfd-9f7b395b9932.png)

**Comment by kachkaev** [comment]
1. Please use the issue template
2. Please see https://prettier.io/docs/en/option-philosophy.html

**Comment by mhamri** [comment]
@kachkaev  I understand the philosophy, but if you don't want to expose a configuration for that at least should consider changing how the formatting is being done atm, it's quite wired and unreadable. since the main philosophy every formatter is the readability of code hence I reopen it again and as you suggested I use the template, but seriously we need to consider these cases.

**Comment by mhamri** [comment]
reopened #10018
