### ISSUE TITLE
typescript condensed formatting of class items

### ISSUE THREAD

**Issue by mhamri** [prettier/prettier#10018]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwGEItoEYAafASSkwFdr8B5Ke1AgX3wDMcZfAHIAAgEMoAc0YAbcTgD0kHHGEBuADpQM2PIXwAlAB4BlGOPj5eAoWJzGAtJJnylAZwvwN23bgJEqLBwOABu4rI0powARgBWcGA8-ILoIg5x7j465PpEFpjWKXYZ7ooQmCGWuFlaOXoB+AAyqJ6mIaGoYHBFtmnCAHSKsq0wA+4dXWp1fnkkZNhQlOaWPTapIkMAshAAJnCyZaTkS7Ar8ONe09racMYN+GDy7u74puJYsnAAjMeLlNp8Pg7vAoLtXiZznAADx-ChnK4APkB+F0X3QlFe7E4ARRqgEcHcAAt6PAwhFojF3GAcKhMDBUNAkPhJABPOpAu6YSS7YhElyE-AAXnwSwA7m9YgkkgAKACUHPwqgmMEMcAJxNJHQi8sIKKBMCJrQGXJ5fIF7gGmDpcHlioNRst+OVJOC5NklOptPpjKgwtRbvCshlhuNUjgMBlwmdhNdZKDwjlcv1QPwVptIfEmBlMuMcuFiPwoctIzak26AzVfAjYCJ8qTKaB41iXtQMVtCpR3BT6D2BwAJP7i+MDolI52-fgAPpBLioClXZlw04wKH+4Ap0swZkAbQAulRN6MAKL3HlwXbMvgRCaHydAmOawMRZkAVgADHegdxFaJ6Exx3wFUlXVF0tXdGVHzjbVZHzDd71RPh8Eg0DY3AoN8ELb533fODGyLR0R0jIgoPQiJrAnVNU2HZUIyrMDn2DSjU27SdWKo00wXNaRCQAJn9cVJXiMc7RRSAoE8HBGCSXAZUwWlwisLd2jCKZmRaMtVO6PCEPcRhKhwUSEOHFUQ0ImcdAZBdVmYh1jXEpZZWELdT25MEL2EGhhxcs8uP5Hj3GY9jRSkbFLPlZlQggVBdkIVjWJAKgQAqBloHcZBQAUQQxQABQUBB0pQCIxXEVl0qSmIcHEMAAGsI1MbkwCCKRkBgKS4CSuB0HbXZ9l2JoXEYcRwwAMVwdBLAZaRkBAcRmAgRKQCJGB0FkAB1I14HcRq4HaCS506GBWRmsAXkWoIJjwHKqqkCbkGvQ4OpATJjAAISq2r6o+OAWiWe6byel7TGar4AEVGAgeB-sepLuRwS6ZqOypW3pRb5KCGA1piw1kAADk-EB5IgCY1qqzAZvkwkOjgRaAEcIfga6KkK2b3EcJYLwvRbVHp1BVGu4a7qQB7bxACZ0FQVr2qS9wQbgcHIZp4WAaSiwYix3YcaQXjVaq1ARmkY4hZAQlX0WxgJgAFXEKlodF0JGDgeh9jOGk6RgABBMFzFZL47bgbhuCAA)
```sh
--parser typescript
```

**Input:**
```tsx
import { Component, Input, OnInit } from '@angular/core';
import { RxState } from '@rx-angular/state';
import { interval, Subject } from 'rxjs';
import { tap } from 'rxjs/operators';
import { ListService } from './list.service';
import { ComponentState } from './Models/ComponentState.state';

export class Sample1Component
  extends RxState<ComponentState>
  implements OnInit {
  refreshIntervalSubscription: any;
  expandChanges = new Subject();
  resetRefreshInterval() {
    this.expandChanges.pipe();
    this.refreshIntervalSubscription = interval(this.get('refreshInterval'))
      .pipe(tap((x) => this.listService.Refetch()))
      .subscribe();
  }
    model$ = this.select();
  _initialState: ComponentState = {
    list: [],
    listExpanded: false,
    refreshInterval: 50,
  };
  @Input() set refreshInterval(refreshInterval) {
    if (refreshInterval > 100) {
      this.set({ refreshInterval });
      this.resetRefreshInterval();
    }
  }
    expandChanges2 = new Subject();
  constructor(private listService: ListService) {
    super();
    this.set(this._initialState);
    this.connect('listExpanded', this.listExpandChanges);
  }
  ngOnInit(): void {}
}

```

**Output:**
```tsx
import { Component, Input, OnInit } from "@angular/core";
import { RxState } from "@rx-angular/state";
import { interval, Subject } from "rxjs";
import { tap } from "rxjs/operators";
import { ListService } from "./list.service";
import { ComponentState } from "./Models/ComponentState.state";

export class Sample1Component
  extends RxState<ComponentState>
  implements OnInit {
  refreshIntervalSubscription: any;
  expandChanges = new Subject();
  resetRefreshInterval() {
    this.expandChanges.pipe();
    this.refreshIntervalSubscription = interval(this.get("refreshInterval"))
      .pipe(tap((x) => this.listService.Refetch()))
      .subscribe();
  }
  model$ = this.select();
  _initialState: ComponentState = {
    list: [],
    listExpanded: false,
    refreshInterval: 50,
  };
  @Input() set refreshInterval(refreshInterval) {
    if (refreshInterval > 100) {
      this.set({ refreshInterval });
      this.resetRefreshInterval();
    }
  }
  expandChanges2 = new Subject();
  constructor(private listService: ListService) {
    super();
    this.set(this._initialState);
    this.connect("listExpanded", this.listExpandChanges);
  }
  ngOnInit(): void {}
}

```

**Expected behavior:**

in an es6 or typescript class, there should be 
* one empty line before each function
* one empty line after functions if the next item isn't a function 
* and one line after the class definition so this case doesn't happen
![image](https://user-images.githubusercontent.com/8991783/103894665-34213580-512a-11eb-80aa-c1cd15024771.png)

```tsx
import { Component, Input, OnInit } from "@angular/core";
import { RxState } from "@rx-angular/state";
import { interval, Subject } from "rxjs";
import { tap } from "rxjs/operators";
import { ListService } from "./list.service";
import { ComponentState } from "./Models/ComponentState.state";

export class Sample1Component
  extends RxState<ComponentState>
  implements OnInit {

  refreshIntervalSubscription: any;
  expandChanges = new Subject();

  resetRefreshInterval() {
    this.expandChanges.pipe();
    this.refreshIntervalSubscription = interval(this.get("refreshInterval"))
      .pipe(tap((x) => this.listService.Refetch()))
      .subscribe();
  }

  model$ = this.select();
  _initialState: ComponentState = {
    list: [],
    listExpanded: false,
    refreshInterval: 50,
  };

  @Input() set refreshInterval(refreshInterval) {
    if (refreshInterval > 100) {
      this.set({ refreshInterval });
      this.resetRefreshInterval();
    }
  }

  expandChanges2 = new Subject();

  constructor(private listService: ListService) {
    super();
    this.set(this._initialState);
    this.connect("listExpanded", this.listExpandChanges);
  }

  ngOnInit(): void {}
}
```

**Comment by kachkaev** [comment]
Can you solve this with eslint? Empty lines before `return` is similar to what you are describing. For that to happen, I personally use [newline-before-return](https://eslint.org/docs/rules/newline-before-return) and that works well alongside prettier. I'm not aware of a specific eslint rule that would add empty lines in your case, but it can be searched or implemented.

**Comment by kachkaev** [comment]
Prettier’s approach to empty lines: https://prettier.io/docs/en/rationale.html#empty-lines

**Comment by mhamri** [comment]
@kachkaev my problem isn't inside a function, but the main problem is inside a class. properties are sticking to functions and class definition. 

referring back to the rational about the empty lines, this item is causing one of the mentioned problems

> Empty lines at the start and end of blocks (and whole files) are removed. (Files always end with a single newline, though.)

there should be at least one empty line at the start of the class so the content of the class doesn't stick to the class definition. 

you are right, I can add those empty line by myself and prettier keep them as it is, but still, it's removing the first empty line after the class definition that as you can see it is causing this strange formatting. 

so if I want to change the rule i would change it to this 

> Empty lines at the ~~start and~~ end of blocks (and whole files) are removed. (Files always end with a single newline, though.)

**Comment by sosukesuzuki** [comment]
What do you think about just adding a empty line to the beginning of such a class members instead of preserving it?

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAlRAwo44qAcwB0occ4APeKAE13xPdMupwEsBbAA6o4fBDFYdJhcjmBUaAgE4QBcRTACeARiQ5MMRT3IBueTiUq1mgEy79hk2Yur1GgMx2DRsqe7OrGgAsng4+VAC+VGAY2HhSUuRm9IwscfHsidz8QiJiEukZZLJOyi6aOnpejn6lAbaVob4Kta4eDd5N5i2awe3VkVAgADQgKjA80JjIoOiKygDuAAqzCFMo6Kjz6BpTIwBGiuhgANZwMADKAkfeyAYArnAjIntwTEyvADLo5HfoZHAAMQgij46Bg43IyBA6DuMAgwxAAAsYHxUAB1RE8eCYK5gODnVZYngANyxGihYGwCKMmCsi0OZFByAAZhtaSMAFaYOgAIUOJzO53Qog+RjgLLZjxAXLo528wgAincIPAJah2SAropaYooZpVJgwIYBDAEUojDA0TwmDBEcgABwABhGFlpaMOAihSjgOuJ4pGAEdlfB6So1tDMABaKBwV6vBGKOBBniJ+l-JlIVnqqW0vg8W6KB4jTDyuBKlXizOSkYwdB7K02u1Iaw1w48VDeADCED4GZAPoArAi7rSACp1tZZjXEh4ASWYYnORp4JoAgsxzpphGraeFwkA)
```sh
--parser typescript
```

**Input:**
```tsx
class loooooooooooooooooooong
  extends looooooooooooooooooong
  implements loooooooooooooooooooong {
  property1: string;
  property2: string;
  property3: string;
  property4: string;
}
class loooooooooooooooooooong
  extends looooooooooooooooooong
  implements loooooooooooooooooooong {

  property1: string;
  property2: string;
  property3: string;
  property4: string;
}

```

**Output:**
```tsx
class loooooooooooooooooooong
  extends looooooooooooooooooong
  implements loooooooooooooooooooong {
  property1: string;
  property2: string;
  property3: string;
  property4: string;
}
class loooooooooooooooooooong
  extends looooooooooooooooooong
  implements loooooooooooooooooooong {
  property1: string;
  property2: string;
  property3: string;
  property4: string;
}

```

**Expected:**

```ts
class loooooooooooooooooooong
  extends looooooooooooooooooong
  implements loooooooooooooooooooong {

  property1: string;
  property2: string;
  property3: string;
  property4: string;
}
class loooooooooooooooooooong
  extends looooooooooooooooooong
  implements loooooooooooooooooooong {

  property1: string;
  property2: string;
  property3: string;
  property4: string;
}


```

**Comment by thorn0** [comment]
There are only two solutions, both inconsistent with how Prettier formats everything else. One of the two has to be chosen nonetheless. The question is which one.
```js
// 1
class loooooooooooooooooooong
  extends looooooooooooooooooong
  implements loooooooooooooooooooong {

  property1: string;
  property2: string;
  property3: string;
  property4: string;
}

// 2
class loooooooooooooooooooong
  extends looooooooooooooooooong
  implements loooooooooooooooooooong
{
  property1: string;
  property2: string;
  property3: string;
  property4: string;
}

**Comment by sosukesuzuki** [comment]
I prefer solution 1. So I created draft PR (#10080).

**Comment by alexander-akait** [comment]
I think related https://github.com/prettier/prettier/issues/5156, we have `2` in plugin-php (because it is popular)

**Comment by sosukesuzuki** [comment]
I didn't know because I don't write much code like that, thanks.

**Comment by alexander-akait** [comment]
And look at here https://github.com/prettier/prettier/issues/8340

**Comment by sosukesuzuki** [comment]
Oh I forgot that I commented to the issue

**Comment by brodybits** [comment]
I would actually favor applying "solution 2" (opening brace on its own line) for all ES classes, regardless of extends/implements/etc., which should improve readability in some other cases. I think it would be better than the request in #4870 to respect or enforce a blank line after the class declaration.

**Comment by samuelsweet** [comment]
It is situational depending on the signature. I agree that newline braces help readability for multiline signatures most of the time, but can also create a lot of noise

Possibly consider rule to apply new line brace if the signature was multi-line, otherwise an empty line?

**Comment by mhamri** [comment]
I prefer to have the `{` always next to some real code to avoid these kinds of problem 

![image](https://user-images.githubusercontent.com/8991783/105037226-a255e880-5a98-11eb-9628-4842db29c289.png)


so my vote is for the number 1 as the other option is just a preference, but this one actually solve a problem

**Comment by thorn0** [comment]
@mhamri Prettier doesn't generate such lone opening braces in any other case, so diff generators won't have anything to confuse them with.

**Comment by mhamri** [comment]
@thorn0 no, there are many cases that `{` will be lone in a line, this is one of them

![image](https://user-images.githubusercontent.com/8991783/105047045-d0d9c080-5aa4-11eb-9bff-f6a175fff3ad.png)
