### ISSUE TITLE
Unnecessary line break in method type declaration returning a multiline type

### ISSUE THREAD

**Issue by nicolo-ribaudo** [prettier/prettier#10013]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACASnAGzgEMBnOAFQggIGFoAzASwHNsBebYAHSm2xZwYACgDWcNEmzdwAC2JRBBCCxkBKKQANe-bVAC+AbhAAaEBAwwm0UslDEATg4gB3AAqOEtlMQIviaLZmAEYOxGDiMADKGOFMisgwDgCucGZwALbBcAAmObkAMgosycSCAGIQDhnEMFYJPskwEKYgsjAZBADqskzwpLFgcFFefUwAbn1oyOCkQSDx5A4wbmEsNcgMvuRmAFakAB4AQmERQlHEGXAF8XCb22kg+wdR8SxEAIrJEPD3BDsgWIOJYzYLEbIEAC0MHmGAc8RgXSYORgsmQAA4AAxmOEQchdMIYGZwuBLcZ3MwAR2+8FWFm8IDIkKgcFyuVaDjg1KYnNWZQ2SC2-0e5AyTESKRFb0+NLugoeZhg4KRKLRSAATIqwkwCG96BkBSBSQBWVrJcgUcHeIUA8apACSUHysCiYHhlgAgk6ougiH9yPp9EA)
```sh
--parser babel-ts
```

**Input:**
```tsx
type ReleaseToolConfig = {
  get(key: "changelog"): `
  `
};
```

**Output:**
```tsx
type ReleaseToolConfig = {
  get(
    key: "changelog"
  ): `
  `;
};

```

**Expected behavior:**
```ts
type ReleaseToolConfig = {
  get(key: "changelog"): `
  `;
};
```

I don't understand why Prettier breaks `get(key: "changelog")` into multiple lines, but it can also be reproduced if instead of the template literal you return a multiline object type.

**Comment by brodybits** [comment]
@nicolo-ribaudo your playground link was made with the multiline template literal while your description shows an object type annotation. I would highly recommend that you update the description to show the issue with the multiline template literal for the sake of a more minimal reproduction. Thanks and thanks for reporting this!
