### ISSUE TITLE
Prettier breaks code functionality on nested ternary

### ISSUE THREAD

**Issue by juppsy** [prettier/prettier#10019]
As the title says, Prettier removes my parenthesis and add ones how it thinks that sould be but this breaks my code after I save the file.

**How I want the code to be:**

```jsx
{route === 'home' ? 
	<div>
		<Logo />
		<Rank
			name={this.state.user.name}
			entries={this.state.user.entries}
		/>
		<ImageLinkForm
			onInputChange={this.onInputChange}
			onButtonSubmit={this.onButtonSubmit}
		/>
		<FaceRecognition box={box} imageUrl={imageUrl} />
	</div>
  : (
	route === 'signin'
	? <Signin loadUser={this.loadUser} onRouteChange={this.onRouteChange}/>
	: <Register loadUser={this.loadUser} onRouteChange={this.onRouteChange}/>
   )
}
```

**How it modifies the parenthesis:**

```jsx
{route === 'home' ? (
	<div>
		<Logo />
		<Rank
			name={this.state.user.name}
			entries={this.state.user.entries}
		/>
		<ImageLinkForm
			onInputChange={this.onInputChange}
			onButtonSubmit={this.onButtonSubmit}
		/>
		<FaceRecognition box={box} imageUrl={imageUrl} />
	</div>
) : route === 'signin' ? (
	<Signin loadUser={this.loadUser} onRouteChange={this.onRouteChange} />
) : (
	<Register
		loadUser={this.loadUser}
		onRouteChange={this.onRouteChange}
	/>
)}
```

**Comment by kachkaev** [comment]
Please use the issue template

**Comment by kachkaev** [comment]
Related: #2724 (closed as wontfix)

**Comment by thorn0** [comment]
@juppsy 

> this breaks my code

What do you mean by that? Does the code change its behavior because of the added parens?

> How I want the code to be

"Prettier is not a kitchen-sink code formatter that attempts to print your code in any way you wish." 
Source: https://prettier.io/docs/en/option-philosophy.html

As for parens in JSX, please see this explanation: https://prettier.io/docs/en/rationale.html#jsx
