### ISSUE TITLE
--jsx-bracket-same-line for self-closing JSX element

### ISSUE THREAD

**Issue by cdroulers** [prettier/prettier#1001]
When declaring a self-closing element and using `jsxBracketSameLine: true`, I would expect the closing mark to be on the same line (like it does for a non-self-closing element).

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Cn%5Cnconst%20wot%20%3D%20%3Cdiv%20one%3D%5C%22twoasdfasdfs%5C%22%20three%3D%5C%22four%5C%22%20five%3D%7Btrue%7D%20test%3D%5C%22lolque%5C%22%20wat%3D%5C%22lskfjslkfj%5C%22%20%2F%3E%5Cn%20%20%5Cn%20%20const%20wot%20%3D%20%3Cdiv%20one%3D%5C%22twoasdfasdfs%5C%22%20three%3D%5C%22four%5C%22%20five%3D%7Btrue%7D%20test%3D%5C%22lolque%5C%22%20wat%3D%5C%22lskfjslkfj%5C%22%3E%5Cn%20%20%20%20content%5Cn%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by rattrayalex** [comment]
eg; 

```jsx
<div 
  attr="val" />
```
instead of 
```jsx
<div 
  attr="val" 
/>
```
correct?

@vjeux what is the style at FB for this?

**Comment by vjeux** [comment]
@rattrayalex fb style is to put `/>` on the next line like prettier currently does with the flag enabled. This visually helps seeing the where the jsx element ends.

**Comment by cdroulers** [comment]
@rattrayalex Yes, I would expect the former.

I can see why it's more "visible" where it ends in the case of self-closing, but considering that it's also more visible for a non-self-closing, I think it would make sense to do the same for both?

**Comment by rattrayalex** [comment]
Thanks for the datapoint @vjeux ! 

@cdroulers I see where you're coming from in terms of expectations. My impression is that it'd reduce clarity, however. 

In code like this: 
```jsx
<div 
  attr="val" >
  <div>child content</div>
</div>
<div>sibling content</div>
```
You have dedented code to clearly differentiate between the child and sibling. 

Meanwhile, with code like this: 
```jsx
<div 
  attr="val" />
<div>sibling that looks kind of like child content</div>
```
there isn't the dedented code, so it looks a little more confusing. 

Clearly closing an opening element isn't such a big deal; closing the whole element is. Does that make sense?

**Comment by cdroulers** [comment]
Sure does. I'm already used to this way after a day! Thanks.

**Comment by rattrayalex** [comment]
Awesome! Thanks @cdroulers !
