### ISSUE TITLE
CLI argument to disable plugins

### ISSUE THREAD

**Issue by cncolder** [prettier/prettier#10036]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI
- Runtime: Node.js v14
- Operating System: macOS

**Steps to reproduce:**

`prettier .`

**Expected behavior:**

Missing a cli argument to disable plugins: `--no-plugin` or `--ignore-plugins`.

In a large codebase, I want to format code with prettier plugins via an editor or git hook, but skip plugins on CI. (for performance reason)

**Actual behavior:**

For now, I can skip plugins like this:

`prettier --plugin-search-dir /tmp .`

**Comment by thorn0** [comment]
Duplicate of #9719
