### ISSUE TITLE
request: support for syntax comments, to avoid template tag functions

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#10044]
** feature request **

I like to avoid using template tag functions if I don't need them. For example, if I want to make a syntax string without the overhead of calling a function (and to avoid using a template tag merely as an identity function), I write:

```js
const css = /*css*/ `
  div { color: skyblue; }
`
```

and my editor (VS Code) knows how to highlight and handle the syntax (with a plugin). It works for any language. For example I use `/* glsl */`, `/* html */`, etc.

At the moment, it seems Prettier will only format code with template tags:

```js
const css = css`
  div { color: skyblue; }
`
```

But this means I need to define an identity template tag function even if I don't need any special behavior. It'd be super sweet to have syntax comments.

**Comment by thorn0** [comment]
Let's close in favor of #5588.
