### ISSUE TITLE
Plugin discovery doesn't work on Yarn 2

### ISSUE THREAD

**Issue by RDIL** [prettier/prettier#10052]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI
- Runtime: Node 14 Nightly
- Operating System: Windows

**Steps to reproduce:**

Any repository that uses Yarn 2 and has at least one prettier plugin installed can see the issue.

**Expected behavior:**

Prettier should properly discover plugins.

**Actual behavior:**

Because Yarn 2 **uses a virtual filesystem**, discovery doesn't work.

The hard-coding around `node_modules` isn't flexible enough to cover this currently.

cc @arcanis

**Comment by thorn0** [comment]
closing in favor of #8474
