### ISSUE TITLE
how about no parentheses in one line stateless components

### ISSUE THREAD

**Issue by faceyspacey** [prettier/prettier#1005]
in addition to `prettier --no-semi`, e.g:

```js
const MyComponent = () => 
  <div>
     <h1>HURRAY!</h1>
  </div>
```

`prettier --no-unnecessary-parentheses-around-react-components` :)

**Comment by vjeux** [comment]
That would be nice indeed but would change a ton of existing code. I want to do it at some point but it's likely going to need to be a major version upgrade. I'll close this as it's tracked somewhere else (don't remember where)
