### ISSUE TITLE
Issue with comments & nested ternaries

### ISSUE THREAD

**Issue by brodybits** [prettier/prettier#10051]
I think this is some kind of a "corner case":

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMIAcDC0AmBLGPaAHSgH4ACAeiooDM8AnAZxgqjlbhwsin0IkoFek1YA5TvBylKARgWkkFAExql1Wszh8eHLj10EiUUtt2SDsigGY7GgCxOQAGhAZBUZslABDRowQAO4ACv4I3ii+ADZBvgCe3m4ARoy+YADWcDAAyujpeFAA5sgwjACucG5wALbJ3DjcADK+xeW+RXAAYhCMNb4whMXIIL7laK4gABYwNdEA6lMEnPlgcDkRxgBuBPEjYMxJIIXajDAhaUX9yHQx2m4AVswAHgBCaZnZOb41cE2FcBudyqICezxyhSK0TgAEVyhB4EDovcQPkWHBGCNkr56tFJuhGIUYPM8DgYFNkAAOAAMbgJEG08zS6BGBM4GK2gLcAEd4fALhhIqNmABaDjcbiTRhwXlMOAXDrXJC3ZEg7Q1PClCpqyHQuEIwHK4FuGA4klkilIFQmtJ4aKQ7A1JUgTgAVkm5W0ABUcZEVSitpUAJL8BC5MCE9AwACC-ByMHi0KR2gAvimgA)
```sh
--parser babel
```

**Input:**
```jsx
topCondition
? // first nested condition
  firstNested
? 111
: 222
: // second nested condition
secondNested
? 333
: 444
```

**Output:**
```jsx
topCondition
  ? // first nested condition
    firstNested
    ? 111
    : 222
  : // second nested condition
  secondNested
  ? 333
  : 444;

```

**Expected behavior:**

`secondNested` should be indented by 2 more spaces, like this:

```js
topCondition
  ? // first nested condition
    firstNested
    ? 111
    : 222
  : // second nested condition
    secondNested
  ? 333
  : 444;
```

I actually discovered this while working on my `prettierx` fork.

**Comment by thorn0** [comment]
I'd rather expect these comments to be moved to own lines above `?` and `:`:
```js
topCondition
  // first nested condition
  ? firstNested
    ? 111
    : 222
  // second nested condition
  : secondNested
  ? 333
  : 444;
```
Looks cleaner IMHO. Related: #2076

**Comment by hwalinga** [comment]
#8554 still pending

**Comment by thorn0** [comment]
closing in favor of #2076
