### ISSUE TITLE
Stop stripping whitespace from before trailing single line comments

### ISSUE THREAD

**Issue by jfriend00** [prettier/prettier#10068]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBLKATOAD0wF5MAGAbkxtrroHoHNIBXWOAJ0wCtWBnLALh5MAMwjcCAI1YBzObjmYIrGAAc1AHSjosuAGKpscgBYwAwrG5kq9Gk0ymIAd0wBbAIZQAnpk5wAI6scIL8LKycAbCofrjixmYwOnqYeNBwVjA2FNT2jMzObl6+-kEhYU6eAG5w4rjY-KYiKRgs3mBwqKTinqj8cHn5jqY1dS51ghDq6iLikTDN3OqcEJ38-EqtWJye8AAq2O5cPVCsqKhDBZgunthYMEcn8dNce9jQOpBQgpionuwwKZDsdwmQANoAXSumEcLmaUBudX+gOaojgniBZWCoWSUBAABoQNNHtB+MhQJ4oq4AApUhDklB9W4+clE6S7MAAawwAGV1JilMhsiEiXB3NIRAQ8AAZbxyVieORwAySLwwR5QOTIEAAmAQQkgczuVAAdVM91CAs6vIZ92w1XuPh1YA2htwA04MBpuzkXmQYj6AyJPH4hAAQpyeTBeZ5jjLcHAA0G4CGw7ylOgAIqsCDwZP9VMgAWcT066SeSWoQ0rXAwU3YPCLZAADnIRJWEAGpt26h1K1CXFqhuCebgPumjN1-AAtFA4CIRIaAsFsAEfUr-UhA4WiQN3NhhZxRSBNlrs7n89uU0SYJWG03TMgAEy33bYYxaiwQdxbkChABWQ1hH2StGR3YMQGqEIAEl8AQGMwE4bB1BgABBfBeRgHx0ALAYAF98KAA)
```sh
--parser babel
```

**Input:**
```js
let index = 0;              // counter just used for debugging output
let inFlightCntr = 0;       // how many requests currently in flight
let doneCntr = 0;           // how many requests have finished
let cancel = false;         // have we stopped further processing
let rateTimer = null;       // wait timer in operation
const launchTimes = [];     // when we launched each request

```

**Output:**
```js
let index = 0; // counter just used for debugging output
let inFlightCntr = 0; // how many requests currently in flight
let doneCntr = 0; // how many requests have finished
let cancel = false; // have we stopped further processing
let rateTimer = null; // wait timer in operation
const launchTimes = []; // when we launched each request

```

**Expected behavior:**

Prettier should preserve trailing comments that line up and not strip whitespace before them.  It should not mess up the existing formatting by stripping the whitespace before the comments and make it less readable than it was.  

```js
let index = 0;              // counter just used for debugging output
let inFlightCntr = 0;       // how many requests currently in flight
let doneCntr = 0;           // how many requests have finished
let cancel = false;         // have we stopped further processing
let rateTimer = null;       // wait timer in operation
const launchTimes = [];     // when we launched each request
```

In the ideal case, prettier would recognize that a series of comments are purposely lined up line this and, even if it modified the code before the comment, it would keep the comments lined up.  But, I will settle for just not destroying the indentation put there by the programmer.

**Comment by thorn0** [comment]
Sorry, but proposals to preserve existing formatting are out of scope for Prettier. The idea of Prettier is to free developers from formatting-related decisions.

**Comment by jfriend00** [comment]
So, the prettier design is to just whack all spaces from before same line comments and make unreadable?  OK, I guess I will go look for a different product because that's ridiculous.  I wouldn't mind prettier asserting a style, but that style should be usable and easy to read, not hard to read.  Bye.

**Comment by thorn0** [comment]
> The idea of Prettier is to free developers from formatting-related decisions.

Consequently, if you don't want to be free from that, Prettier is a "product" not for you, indeed.

**Comment by jfriend00** [comment]
The idea is to free developers from formatting-related decisions while formatting the code in a decent, readable and standard way.  In this case, it is failing the "decent" and "readable" parts of that mission as it leaves the code in a not particularly readable way that nobody would say is a particularly good way to leave it if they were objectively evaluating the output.  

You could take this particular issue on as part of what the product does without breaking any of your rules or philosophy if you so chose.  It appears to me that you are just ignoring this issue because it is not easy to handle given the way your product works so you do what's easy, even though it not very readable.

Are you arguing that the result here is desirable and good and the best result possible from a code formatter?

**Comment by thorn0** [comment]
There are multiple problems with your proposal. The main one is that it's based on some initial manual formatting whereas leaving this kind of manual things up to the developer is directly against Prettier's philosophy of fully automatic formatting.

A comment alignment algorithm not based on whitespace from original formatting would be a different proposal, still problematic though. For one, the diff-unfriendliness of such a solution is a complete show-stopper.

**Comment by jfriend00** [comment]
I don't mean to be proposing a specific solution - other than to say it should be as readable as my manually formatted version since a formatter shouldn't be in the job of making things less readable.  I've already said multiple times I'm willing to accept re-formatting of the comments if they look clean and readable.  I want trailing comments not to be cranked up against the code and look unreadable and ugly.  You're the expert here.  Come up with a good solution.  Your current product produces ugly trailing comments.  You could do better if you wanted to.  Multiple lines of code with trailing comments are ugly and not very readable.  That's my point here.  Right now you seem to first be hiding behind some principle of reformatting, then you seem to be hiding behind not liking my suggestions.  That's fine.  Come up with something that actually works in the spirit of what your product is trying to do.  You're the expert here.  I rather doubt ugly trailing comments is in line with any core principle prettier has.

I don't understand what you're arguing about diff-unfriendly.  All your reformatting creates diffs if a previous version that wasn't auto-formatted was already checked in.  I already know that as all sorts of diffs occurred when I started using prettier on one of my repositories.
