### ISSUE TITLE
Comments inside flow object definition are printed on wrong lines

### ISSUE THREAD

**Issue by jonathanewerner** [prettier/prettier#1007]
Haven't been able to find an existing issue for that, sorry if it's a duplicate. 

```js
export default (
  {
    foo,
    bar
  }: {
    // comment
    foo?: Object,
    // comment 2
    bar?: Object,
  },
) => {}
```

outputs

```js
export default (
  {
    foo,
    bar
    // comment
    // comment 2
  }: {
    foo?: Object,
    bar?: Object
  }
) => {};
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20default%20(%5Cn%20%20%7B%5Cn%20%20%20%20foo%2C%5Cn%20%20%20%20bar%5Cn%20%20%7D%3A%20%7B%5Cn%5Ct%2F%2F%20comment%5Cn%20%20%20%20foo%3F%3A%20Object%2C%5Cn%20%20%20%20%2F%2F%20comment%202%5Cn%20%20%20%20bar%3F%3A%20Object%2C%5Cn%20%20%7D%2C%5Cn)%20%3D%3E%20%7B%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Good catch! This is a bug indeed.

**Comment by bvaughn** [comment]
Noticed a related issue for Flow types when running prettier on some changes made to the React repo.

```js
type Foo = {
  bar(
    baz: number, // I belong with baz
    qux: string /* I belong with qux */
  ) : void
}
```
...gets converted to...
```js
type Foo = {
  bar /* I belong with qux */(baz: number, qux: string): void // I belong with baz
};
```

Online repro [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Foo%20%3D%20%7B%5Cn%20%20bar(%5Cn%20%20%20%20baz%3A%20number%2C%20%2F%2F%20I%20belong%20with%20baz%5Cn%20%20%20%20qux%3A%20string%20%2F*%20I%20belong%20with%20qux%20*%2F%5Cn%20%20)%20%3A%20void%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D).

**Comment by vjeux** [comment]
@bvaughn thanks for the repro! Sorry about it!

To get you unblocked, you can do two things:

- Add // prettier-ignore before the function declaration
- Use the arrow function version of the type which apparently works

```js
type Foo = {
  bar: (
    baz: number, // I belong with baz
    qux: string /* I belong with qux */
  ) => void
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Foo%20%3D%20%7B%5Cn%20%20bar%3A%20(%5Cn%20%20%20%20baz%3A%20number%2C%20%2F%2F%20I%20belong%20with%20baz%5Cn%20%20%20%20qux%3A%20string%20%2F*%20I%20belong%20with%20qux%20*%2F%5Cn%20%20)%20%3D%3E%20void%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by bvaughn** [comment]
Oh cool. Thought I tried that in the repl. Thanks! 😄

**Comment by vjeux** [comment]
Looks like the two are not the same bug. I created https://github.com/prettier/prettier/issues/1037 for the bug you reported @bvaughn.

**Comment by bvaughn** [comment]
Nice! Thanks for the update!

**Comment by vjeux** [comment]
Okay, the issue with this bug is that `typeAnnotation` is not in the type definition and therefore ignored during the comment location search, it therefore puts it in the closest node which is the `ObjectPattern`.

I sent a PR to https://github.com/benjamn/ast-types/pull/211 that fixes the bug. It needs to be merged and released there and we need to update prettier before I can close this issue.

**Comment by vjeux** [comment]
@jonathanewerner https://github.com/prettier/prettier/pull/1045 fixes it :)

**Comment by jonathanewerner** [comment]
Awesome. 👍🏻 So nice to be using a tool that is maintained this responsively. 👏🏻

**Comment by vjeux** [comment]
@jonathanewerner you're welcome, please keep sending issues on weird things you see with prettier!
