### ISSUE TITLE
functions in callbacks seem to break prettier

### ISSUE THREAD

**Issue by davidascher** [prettier/prettier#1008]
Using version 0.22.0, 

The following code:
```js
import "React";

class X {
  onDrop(files) {
    function previewFile() {
      reader.addEventListener(
        function(reader) {
          preview.src = reader.result;
        }, false)
    }
  }
}
```

gets changed by prettier to:

```js
import 'React';

class X {
  onDrop(files) {
    function previewFile() {
      reader.addEventListener(
        function(reader) {
          preview.src = reader.result;
        },
        false,
      );
    }
  }
}
```

which is weird in four ways:

- changes the quotes to be single quotes.
- it adds a comma to the `false`
- adds a semicolon to the `)`
- thereby making the code not parseable as far as `eslint` is concerned.

Just removing the assignment in the callback:

```js
import "React";

class X {
  onDrop(files) {
    function previewFile() {
      reader.addEventListener(
        function(reader) {
        },
        false,
      );
    }
  }
}
```

results in a good `prettier` output:

```js
import "React";

class X {
  onDrop(files) {
    function previewFile() {
      reader.addEventListener(function(reader) {}, false);
    }
  }
}
```

**Comment by yamafaktory** [comment]
Prettier doesn't add commas and doesn't switch to single quotes by default, please see it here https://prettier.github.io/prettier/#%7B%22content%22%3A%22import%20%5C%22React%5C%22%3B%5Cn%5Cnclass%20X%20%7B%5Cn%20%20onDrop(files)%20%7B%5Cn%20%20%20%20function%20previewFile()%20%7B%5Cn%20%20%20%20%20%20reader.addEventListener(%5Cn%20%20%20%20%20%20%20%20function(reader)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20preview.src%20%3D%20reader.result%3B%5Cn%20%20%20%20%20%20%20%20%7D%2C%20false)%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D.

I guess you are using additional flags `--single-quote --trailing-comma all`, please refer to https://github.com/prettier/prettier#api.

**Comment by vjeux** [comment]
Thanks for the report! As mentioned by @yamafaktory this is the intended output when you have `--single-quote --trailing-comma all`. If you don't want it, then feel free to use a different set of options.
