### ISSUE TITLE
Prettier is not formatting optional Chaining properly

### ISSUE THREAD

**Issue by shubhamtulsyan** [prettier/prettier#10089]
Hi Team, I am using prettier in VS code. when I am writing a syntax for optional chaining, it is not able to understand which is causing bug
e.g.
I have written:
const test = game[el]?.game[el]??'Team not found';

prettier changed it to:

const test = game[el] ? .game[el] ? ? 'Team not found';

**Comment by brodybits** [comment]
You are more likely to get help if you use the Prettier playground: https://prettier.io/playground/

It has buttons to copy the Markdown and even raise a new issue if you like.

Here is what I got based on your input:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8OYLyYDmAhgLZwDacANgLoD8AdCeVXffQOQAqcZmUCFgBmEAK5QAJpwDcIADQgIABxgBLdMlDEATjogB3AAq6EaZCGLUDxAJ7nFAIx3EwAazgwAystdqohMgwOmJwinCkjnCSktEAMsQBYsSEcABiEDqkxDDqARbEYjAQCiAAFjCk1ADqZWo4vmBwXmb1agBu9bYWYGgOIP5ocDowRi6E2cjCVkOKAFZoAB4AQi7unl5kcHH+cFMzYSALi17+hNRwAIpiQntI09SzIL46QzoWjsRR1KXKOv4wapqSQwMrIAAcAAZFH8IENqi5lBY-nA3u09ooAI43eBjFTmFDENAAWigcGi0VKOjg2LU1LGKUm9wOiiGpDUQRChzQZwu11u+0ehxgXyBILBSAATIpgsQ1NQzgBhCCkJkgVEAVlKYiG3C+BIeT3aoQAklIEN4wP9VABBKReGC2C6CoYAX1dQA)
```sh
--parser babel
```

**Input:**
```jsx
const test = game[el]?.game[el]??'Team not found';
```

**Output:**
```jsx
const test = game[el]?.game[el] ?? "Team not found";

```

**Comment by akozdev** [comment]
I've seen this problem a couple of times occurring for different people. Unfortunately, I couldn't reproduce it myself.
Can it be related to the [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) in VS Code extension?
