### ISSUE TITLE
Blank line at the end of file

### ISSUE THREAD

**Issue by awslabspl** [prettier/prettier#10088]
Whats the rationale behind this?

**Comment by thorn0** [comment]
It's much more widespread than the lack of it.

**Comment by awslabspl** [comment]
But, to be honest, its misleading (at least)

**Comment by kachkaev** [comment]
Please use online search before opening an issue:

- https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795
- https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

When creating issues, it is necessary to follow an issue template:  
https://github.com/prettier/prettier/tree/master/.github/ISSUE_TEMPLATE

**Comment by awslabspl** [comment]
@kachkaev  Maybe I didnt stick to your guidelines, OK, I can agree on this. But, its not changing the fact that @thorn0 could have been nicer to me/everyone else. This can hardly be named welcoming attitude.

**Comment by thorn0** [comment]
@awslabspl Maybe I'm missing something, but why keep the issue open if the question has been answered?
See also: https://www.google.com/search?q=github+etiquette ;)

**Comment by awslabspl** [comment]
@thorn0 maybe because someone may want to add something?

**Comment by thorn0** [comment]
It's not a forum. We use the issue tracker only for tracking bug reports and feature requests. When I have time, I answer questions about Prettier on StackOverflow though.

**Comment by awslabspl** [comment]
> It's not a forum. We use the issue tracker only for tracking bug reports and feature requests. When I have time, I answer questions about Prettier on StackOverflow though.

SO isnt either.........
