### ISSUE TITLE
--debug-print-doc leads to "Out of memory" error

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#10095]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI, browser
- Runtime: Node v12.19.0
- Operating System: WSL

**Steps to reproduce:**

In the browser: [playground](https://prettier-doc.netlify.app/playground/#N4Igxg9gdgLgprEAuEBtAOlABF9IDuATgIYAOpcAJgOKEQCupeANJjgOZ2MAUG2OuENxZsBASyiUEMXqIFYAzhABmMADYS4rfvLwSpsEToGcGpWcd1Cj8+fukXbtpao1Qtcp4MhQwxGDZeOD6UYjBi0MRqtGaOQQJ88bZ4wiDaSfKmPIkZVhhpnrn2sHG58i7qmullmVzmqADkeABGYsoQhFAAwoQS7HCEALIQCgAWVAAKA6RqcAAeAMrE+FKEeA0AugCU1TU4IgWWZW4eR7lZ9XgneNu7ewd3NSePZRe8TSDECgDWACp0ADcEMQAEJwYEAETgFEkCgAShB8MQoAp1rdChl0Wd4m0QYQ4MRvqlWCAdhikhVnuT4jdArksTU8Fs6fENi8nDlcikWUkiGQKDQ6qVXkLOfc0DyysUZGK9ooVJV3OyRbFGi02h1ur0oP0hiNxpQpoQZvMlisBmiydiuQVDnL5FTrRk3vlriAGfb9rblblHZ6OKKPl8-oDgWDIdCEJR4YjkaiQJsrZ6PXLcfjCcSmT74pSqtSkrS7XsU5ik2UmZKnGz8wI+eQqDFsjWrJmnXZJA5ZRk-XsXc2vHh8tmgtLhXLc0r+0EXR9Wu1Oj0+gNhmNJtNZotlqtLcOad6p14e56+yA3SW5Q8D04j-aZ3hg-8IECoKDwS+oTDowikSid1eBOeUrKHiBJEgcZbjgqN6Mu6lashBpa7jg0F7syRZJIB8iYVg2FpqBqRZtSE6nEEFboQBCElnhGZ4IRxjEXcZHVB6eAANyBKMxCEJQjobOxUBpCAECkOE0AKMgoBcXQ+ATFxCDiSgURIgAnuJzAgM0JBgN8cAwAspDEGAfTIDAhD0FoIBwAAts0VBSJQAAyyLsPQxD9AAYh0Vn+OEOrIJ89AwBAgmjDAVlqAA6qMYRwAoBlgHACzyWEYgAmEyn+WAChqSAEgKAMMATCQ7DecgyhRPl6kAFYKHMeKGTpenEFZcAOZoZUVRZNWLH0swAIr0BA8AdWolUgAZhD5YQ-nNMQtlqAAtDAOWkNqMARWIlAwKMyAAKwAOzqatIxwBFJCkP5q2xQMQKCQAjoN8BFcJCmfAoC3uFQVCCfiD1iPiRVuaVSDlaNFn5VZYgmWZ4O9XAA1DXAI1jTAc0bVtO1IAATOppnEGIbjsF0EBWcDlkKLtgn0PlvxzQpoNjQC5kAJIdrACxgL0IkAIKSAsMDKbMyNwAAviLQA) (the browser tab crashes)

Node

1. Save this code to a file:
<details>

```
[
  "wrappedGroup",
  group([
    "(",
    indent([
      softline,
      "indent",
      group([
        "(",
        indent([
          softline,
          "concat",
          conditionalGroup([
            [
              "(",
              group([
                "[",
                indent([
                  softline,
                  group(['"bifornCringerMoshedPerplexSawder"']),
                  ",",
                  line,
                  group(["line"]),
                  ",",
                  line,
                  group(['"askTrovenaBeenaDependsRowans"']),
                ]),
                ifBreak(","),
                softline,
                "]",
              ]),
              ")",
            ],
            [
              "(",
              wrappedGroup([
                group([
                  "[",
                  indent([
                    softline,
                    group(['"bifornCringerMoshedPerplexSawder"']),
                    ",",
                    line,
                    group(["line"]),
                    ",",
                    line,
                    group(['"askTrovenaBeenaDependsRowans"']),
                  ]),
                  ifBreak(","),
                  softline,
                  "]",
                ]),
              ]),
              ")",
            ],
            wrappedGroup([
              "(",
              indent([
                line,
                group([
                  "[",
                  indent([
                    softline,
                    group(['"bifornCringerMoshedPerplexSawder"']),
                    ",",
                    line,
                    group(["line"]),
                    ",",
                    line,
                    group(['"askTrovenaBeenaDependsRowans"']),
                  ]),
                  ifBreak(","),
                  softline,
                  "]",
                ]),
              ]),
              line,
              ")",
            ]),
          ]),
        ]),
        ifBreak(""),
        softline,
        ")",
      ]),
    ]),
    ifBreak(""),
    softline,
    ")",
  ]),
  ";",
  hardline,
]; 
```

</details>

2. Run `prettier your-file.js --debug-print-doc`

**Expected behavior:**

No error

**Actual behavior:**

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**Comment by fisker** [comment]
I took a quick look, it's only because the doc is huge, compare docs for these two case

```js
a(
  b(),
);
```

```js
a([
  b(),
]);
```

**Comment by thorn0** [comment]
Okay, closing then. But if OOM happens this easily in `flattenDoc`, then it might happen in other doc traversing functions we have in doc-utils. Just something to keep in mind.
