### ISSUE TITLE
jsx-wrap-multilines

### ISSUE THREAD

**Issue by zorzysty** [prettier/prettier#1009]
In it's current version prettier is conflicting with [jsx-wrap-multilines rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md) that is used by some of the most popular react style guides including [Airbnb's](https://github.com/airbnb/javascript/tree/master/react#parentheses). 

```js
const header = this.props.header
  ? (
	<HeaderElement
	  className="myclass myclass2"
	  isExpanded={this.state.isExpanded}
	>
	  {this.props.header}
	</HeaderElement>
  )
  : null;
```

outputs

```js
const header = this.props.header
  ? <HeaderElement
      className="myclass myclass2"
      isExpanded={this.state.isExpanded}
    >
      {this.props.header}
    </HeaderElement>
  : null;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20header%20%3D%20this.props.header%5Cn%20%20%3F%20(%5Cn%5Ct%3CHeaderElement%5Cn%5Ct%20%20className%3D%5C%22myclass%20myclass2%5C%22%5Cn%5Ct%20%20isExpanded%3D%7Bthis.state.isExpanded%7D%5Cn%5Ct%3E%5Cn%5Ct%20%20%7Bthis.props.header%7D%5Cn%5Ct%3C%2FHeaderElement%3E%5Cn%20%20)%5Cn%20%20%3A%20null%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
The reason why () are added is to prevent 

```js
return
  <div />;
```

from the semi-colon automatic insertion feature of js where it adds a `;` after `return`. Then, because people see parenthesis added for return, they are thinking it's actually useful/needed for other places, but it's not the case.

It seems like adding parenthesis around ternaries is just adding noise and not actually useful.

**Comment by zorzysty** [comment]
@vjeux I agree with you. Those parentheses aren't useful in ternaries and prettier shouldn't be adding them by default. 

The option would be nice to have since this rule is so popular, and its default settings are requiring parentheses for both returns and ternaries like in the example. 

As a workaround, for those who are using Airbnb style guide and want to integrate prettier, I'd recommend adding this line to the rules:
`"react/jsx-wrap-multilines": ["error", {"declaration": false}],`

**Comment by vjeux** [comment]
I'm going to close this one in order to concentrate all the ternary discussions in https://github.com/prettier/prettier/issues/737

**Comment by charlike** [comment]
@vjeux it's not only about ternaries..

following

```js
const foo = ({ bar }) => <h1>Hello {bar}</h1>
```
is converted to

```js
const foo = ({ bar }) =>
  (<h1>
    Hello {bar}
  </h1>)
```

current config of that rule

```js
module.exports = {
  rules: {
    'react/jsx-wrap-multilines': [
      'error',
      { arrow: true, return: true, declaration: true }
    ]
  }
}
```

**Comment by vjeux** [comment]
@charlike prettier has never outputted that, it must be an eslint rule with autofix

**Comment by charlike** [comment]
Hm, probably, after couple of more tests it feels like that, because in some cases it work. Sorry :hand:

**Comment by zhenyulin** [comment]
got some further errors with nested multiline-jsx

```
const renderBarGroup = (className, input, xScale, yScale, height, barWidth) =>
  <g
    className={`bargroup-${className}`}
    transform={`translate(${-barWidth / 2},0)`}
  >
    {input.map(d =>
      (<rect
        key={d.x}
        x={xScale(d.x)}
        y={d.y < 0 ? height : yScale(d.y)}
        width={barWidth}
        height={Math.abs(height - yScale(d.y))}
      />),
    )}
  </g>;
```

```
  10:3  error  Missing parentheses around multilines JSX  react/jsx-wrap-multilines
  15:7  error  Delete `(`                                 prettier/prettier
  21:9  error  Delete `)`                                 prettier/prettier
```
