### ISSUE TITLE
Make leading semicolon rule consistent with typescript-eslint

### ISSUE THREAD

**Issue by brandon-leapyear** [prettier/prettier#10101]
Prettier will say the following code is formatted correctly:
```ts
function asdf1(x: any) {
  ;(x as number).toString()
}

function asdf2(x: any) {
  console.log(x)
  ;(x as number).toString()
}
```

But `typescript-eslint` fails:
```
  2:3  error  Unnecessary semicolon  @typescript-eslint/no-extra-semi
```
Removing the semicolon will then cause prettier to fail:
```
  2:3  error  Insert `;`  prettier/prettier
```
It seems like `typescript-eslint@4` only considers a leading semicolon necessary if it's ambiguous (as it is in the second function), so prettier should do the same

**Comment by thorn0** [comment]
When you use ESLint with Prettier, you should use [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier#installation) to disable formatting-related ESLint rules. With `@typescript-eslint`, the `extends` section of your ESLint config might look like this (note `prettier/@typescript-eslint`):

```
	extends: [
		'eslint:recommended',
		'plugin:@typescript-eslint/recommended',
		'plugin:@typescript-eslint/recommended-requiring-type-checking',
		'prettier',
		'prettier/@typescript-eslint',
	]
```

Docs about this: https://prettier.io/docs/en/integrating-with-linters.html
