### ISSUE TITLE
Comments move outside named import block and appear after 'from' when comments are at end of block

### ISSUE THREAD

**Issue by dburrows** [prettier/prettier#1011]
```js
import {
    FN1,
    FN2,
    // FN3,
    FN4,
    // FN4,
    // FN5
} from './module';
```

becomes 

```js
import {
    FN1,
    FN2,
    // FN3,
    FN4
} from // FN4,
// FN5
"./module";

```

Example: https://prettier.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%5Cn%20%20%20%20FN1%2C%5Cn%20%20%20%20FN2%2C%5Cn%20%20%20%20%2F%2F%20FN3%2C%5Cn%20%20%20%20FN4%2C%5Cn%20%20%20%20%2F%2F%20FN4%2C%5Cn%20%20%20%20%2F%2F%20FN5%5Cn%7D%20from%20'.%2Fmodule'%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Good catch!
