### ISSUE TITLE
Bug: Comments ignored for fat-arrow function body

### ISSUE THREAD

**Issue by Undistraction** [prettier/prettier#1012]
Prettier collapses fat-arrow function even if comment exists.

```js
export const hasAnyRoutes = app => {
  // eslint-disable-next-line no-underscore-dangle
  return app._router.stack.filter(layer => layerHasRoute(layer)).length > 0;
};
```

Is turned into:

```js
export const hasAnyRoutes = app => // eslint-disable-next-line no-underscore-dangle
  app._router.stack.filter(layer => layerHasRoute(layer)).length > 0;
```

I think this is a lot less readable so I'm assuming this is a bug rather than a 'feature'.

**Comment by vjeux** [comment]
prettier doesn't change the AST so it's never going to remove `{}` from arrow functions. Something else in your toolchain must be doing that.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20const%20hasAnyRoutes%20%3D%20app%20%3D%3E%20%7B%5Cn%20%20%2F%2F%20eslint-disable-next-line%20no-underscore-dangle%5Cn%20%20return%20app._router.stack.filter(layer%20%3D%3E%20layerHasRoute(layer)).length%20%3E%200%3B%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by Undistraction** [comment]
Apologies. Must be eslint's autofixing.
