### ISSUE TITLE
Number properties can't be unquoted in TypeScript

### ISSUE THREAD

**Issue by remcohaszing** [prettier/prettier#10123]
Prettier usually removes unnecessary quotes from properties in TypeScript and JavaScript. However, when a numeric property is used in TypeScript, they keep their original quoting.

I tried to see if the quotes make TypeScript behave differently using TypeScript 4.1.3, but it does not.

In the linked playground, the diffence can be observed when toggling the parser between babel and typescript.

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgDEIJDgAdKQwgcgBYAmOpQgZxk3QHMBuagF9q1SFE6FsZQgF4K1WoxZs6dIQKggANCAgAHGKmjtkoXJkwQA7gAVzCEylwAbK7gCeJnQCNM+ANZwMADKevi8yFwArnA6cAC23nAAJskpADK4UDxRuDxwpJjxuDCG2cgguFEwENogABYw8c4A6vWo8OxhBMEOHagAbh3uFWDsXmjiWDA2fjzFyHjO7LEgAFbsAB4AQn5ggSG48XDp6HCLLis6G5vBvM5wAIpREPAXy6thmCuYFTDuejg7DA3AMdT03FgLVQyRg9WQAA4AAw6CEQFYtPx6CoQoFYAbnHQARxe8Fm+kclXYAFooHAUik6pg4CTUMzZnkFkgllcQCt4qhIpgYjp2PcnqTztzLqsYLhvNDYfCkEwdFxcKhnLwAMIQeJckBAgCsdSiKwAKvLHDzVgMYgBJKBpWDBEGoAwAQSdwX+D3eK0EgiAA)
```sh
--parser typescript
```

**Input:**
```tsx
interface Foo {
  '42': string;
}

const foo = {
  '42': ''
};

```

**Output:**
```tsx
interface Foo {
  "42": string;
}

const foo = {
  "42": "",
};

```

**Expected behavior:**
```tsx
interface Foo {
  42: string;
}

const foo = {
  42: "",
};

```

**Comment by brodybits** [comment]
See this comment: https://github.com/prettier/prettier/pull/8508#issuecomment-701683685

I think this should be documented in the help text, at least.

**Comment by thorn0** [comment]
TS differentiates between string and numeric keys: https://www.typescriptlang.org/play?#code/DYUwLgBAhhC8EG8IEYBcKA0EBM7sQF8AoUSAIzkQgHJlr1ktrt6dCiiATEAY2CgBOICKWhR0AaxABPAPYAzCGGkAHEAugBuLr35CR4CGTKSZG5Wo1ltRKDHjHtQA

> I think this should be documented in the help text, at least.

Okay, let's mark this issue as "docs".

**Comment by remcohaszing** [comment]
> TS differentiates between string and numeric keys: https://www.typescriptlang.org/play?#code/DYUwLgBAhhC8EG8IEYBcKA0EBM7sQF8AoUSAIzkQgHJlr1ktrt6dCiiATEAY2CgBOICKWhR0AaxABPAPYAzCGGkAHEAugBuLr35CR4CGTKSZG5Wo1ltRKDHjHtQA

That’s weird, but it makes sense from the perspective of Prettier.
