### ISSUE TITLE
HTML: Change formatting for new lines

### ISSUE THREAD

**Issue by DerekRTP** [prettier/prettier#10134]
I have been using prettier for just over a year now and have enjoyed its usefulness. This is one thing that has always stood out to me as an issue and now i'm taking the time to report it. It seems with HTML that prettier decides to break long lines in a way that I feel looks disjointed and difficult to read. Please see the desired formatting behaviour below.

**Input:**

```html
<v2-body-text color="dark-grey" id="resend-text-1">Verification code sent</v2-body-text>
```

**Output:**

```html
<v2-body-text color="dark-grey" id="resend-text-1"
  >Verification code sent</v2-body-text
>
```

**Expected behavior:**
```html
<v2-body-text color="dark-grey" id="resend-text-1">
  Verification code sent
</v2-body-text>
````

**Comment by thorn0** [comment]
This works as expected. Please read about [whitespace-sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting). You can control it using the [`htmlWhitespaceSensitivity`](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option.
