### ISSUE TITLE
Another issue to test #10140

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#10144]

**Comment by fisker** [comment]
Duplicate of #10143

**Comment by fisker** [comment]
Takes 13s.

**Comment by fisker** [comment]
And run CI on any comments. https://github.com/prettier/prettier/actions/runs/512836800

**Comment by fisker** [comment]
Duplicate of #10143

**Comment by fisker** [comment]
Keep this closed, and post "Duplicate of #10143"

**Comment by fisker** [comment]
Duplicate of #10143

**Comment by fisker** [comment]
Reopen to test #10220

**Comment by fisker** [comment]
Duplicate of #10143

**Comment by fisker** [comment]
@xrkffgg Everything working as expected, thanks!

**Comment by xrkffgg** [comment]
My pleasure
