### ISSUE TITLE
if line starts with "it" (unit tests) line breaks are not added for long lines

### ISSUE THREAD

**Issue by valera33** [prettier/prettier#10141]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLGAKA5AJzjAVxygGcACGACzjIRhwE8zUowAbAgExYHMLqyeEgTYwyEAGa0AbnEZlIUWTng4yAOk3qyEiBCwAaHQVYxU0DFVQkkAMT0BKMsAA6UMgugkxAQwC8WD5YbgC+DgDcIAYgEAAOZl7IoD44OBAA7gAKKQgkyCA+bOk+DHnRAEY4PmAA1vgAyrHVvMj0BHDRcAC25XCcnH0AMj5QPAQ+PHD2OF0+MGaj+T4EMBBRIJQwXWwA6pTocCRNYHD1ueio0ugM+WAkZWikcjCZVTyzyBKFJB0gAFYkAAeACEqrUGj4unBBiw4J9vr8AYD6rw2HAAIoECDweFsH7RJo4H44fLlHy9NjrWI4FgwHaoThUZAADgADAS0j8dlVYvlqYc5LJ1gBHLHwV5xPIoHwkAC0UDgfT66zwotQeFeEw+SC+eN+Py6qFaOHa0RIqIxYrhOoR0Rg5PpjMoyAATHaqqg2LwAMIQLrakCHACs6wIPwAKuSpbr8SBpO0AJJQAawepgGnxACCyfqMAYaNxPxCISAA)
```sh
--parser babel
```

**Input:**
```jsx
it('returns the entry including the result of every converter .... foo', function(this:Foo) {
  const a='a'
});
```

**Output:**
```jsx
it("returns the entry including the result of every converter .... foo", function (this: Foo) {
  const a = "a";
});

```

**Expected behavior:**

however if we replace "it" with anything esle, for example "fo" then formatting works as expected:

***Outupt***
```jsx
fo(
  "returns the entry including the result of every converter .... foo",
  function (this: Foo) {
    const a = "a";
  }
);
```

**Comment by thorn0** [comment]
Works as intended. See: https://prettier.io/docs/en/rationale.html#testing-functions
