### ISSUE TITLE
Support parallel mode in CLI

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#10151]
https://github.com/microsoft/parallel-prettier seems much faster, we should consider support it in our CLI too.

Ref https://github.com/prettier/prettier/issues/10147#issuecomment-767997181

**Comment by sosukesuzuki** [comment]
related: https://github.com/prettier/prettier/issues/4980

**Comment by sosukesuzuki** [comment]
We may be able to use libraries such as [workerpool](https://github.com/josdejong/workerpool)(used in mocha) and [jest-worker](https://www.npmjs.com/package/jest-worker)

**Comment by fisker** [comment]
Duplicate of #4980
