### ISSUE TITLE
Remove 2nd argument pass to `Plugin.parse` function

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#10156]
https://github.com/prettier/prettier/blob/9786ce2fb628ac4ad3ed5088fd8f7c66a93d9c17/src/language-js/parser-babel.js#L110

The 2nd parameter, seems not very useful, but I'm not sure if plugins uses it, but plugin can always load other plugin by themself. 

I think we can remove it.

---
This is breaking change.

**Comment by fisker** [comment]
Any thought on this?

**Comment by fisker** [comment]
If we still want keep it, we should proberly change it to a Proxy?

https://github.com/prettier/prettier/blob/e096ea7552c2aaec1883c7fdde4bd9f5283301bd/src/main/parser.js#L61-L74

**Comment by fisker** [comment]
@thorn0 @sosukesuzuki In case you missed.

**Comment by thorn0** [comment]
Why make it a proxy?

**Comment by fisker** [comment]
Cheaper? We don't need map all keys.

**Comment by sosukesuzuki** [comment]
I think we can remove it if it isn't used by real-world plugins.

**Comment by fisker** [comment]
>  if it isn't used by real-world plugins.

Maybe it doesn't matter if plugin uses it or not, if plugin uses `options`, it will have to change, the paramter will be moved from 3rd to 2nd.

**Comment by thorn0** [comment]
> Maybe it doesn't matter if plugin uses it or not, if plugin uses `options`, it will have to change, the `options` paramter will be moved from 3rd to 2nd.

Some trickery with `parse.length` might help with this.

**Comment by fisker** [comment]
This is when it's added https://github.com/prettier/prettier/pull/1783/files#diff-54c345dc104dc19440f9c2482b7883df820e8b9b699fdd8fa07e2773e7197a29L22

**Comment by fisker** [comment]
Let's pass an empty object in v3  (deprecate those getters), and  remove the paramter in v4?

**Comment by fisker** [comment]
Or pass `option` as both 2nd  and 3rd argument, and remove the 3rd one in v4.

**Comment by fisker** [comment]
Fixed by #13268
