### ISSUE TITLE
Drop support for Node.js 10, switch to ES Module

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#10157]
Node.js 10 will go end of life in April 2021, Node.js 12 has full native modules support.

**Comment by alexander-akait** [comment]
> switch to ES Module

Not sure it will be good idea, because many tools and extensions for IDE, linter plugins/boilerplates and etc/etc/etc, whice have wide support Node.js (they have EOL which do not match with EOL of Node.js), don't forget we very popular, maybe we should do dual publish (cjs and esm), I am not against esm, but I think will be great to keep cjs version possibly until the end of the life of Node.js v12. We must not forget about our users, even if they are in legacy world

**Comment by fisker** [comment]
We can convert codebase to esm, this will stop "direct-install-from-codebase" support for Node.js 10, and we can ship both bundled `cjs` and `esm`.

**Comment by thorn0** [comment]
What about publishing separate packages for cjs and esm? Would it make sense? Or is it considered a bad practice?
Some users complain the package size has become too big.

**Comment by fisker** [comment]
I'm not sure about cjs and esm, but we can at least publish seperate package for `standalone`.

**Comment by thorn0** [comment]
Standalone is only 514 kB whereas esm has doubled the size of the package.

**Comment by fisker** [comment]
I was  thinking `standalone` package with all umd/esm files, Node.js package have different cjs/esm file.  But I guess this won't solve package size problem. Sorry, my bad.

**Comment by alexander-akait** [comment]
@fisker 

> We can convert codebase to esm, this will stop "direct-install-from-codebase" support for Node.js 10, and we can ship both bundled cjs and esm for a while.

Yep, sounds good :+1: 

> What about publishing separate packages for cjs and esm? Would it make sense? Or is it considered a bad practice?
> Some users complain the package size has become too big.

hm, can you provide link? Don't think it is real problem...

**Comment by thorn0** [comment]
@alexander-akait Can't find it now. Hopefully it is indeed a non-issue

**Comment by fisker** [comment]
Maybe we can publish pre language? Also prevent unexpected embed format 😄

**Comment by alexander-akait** [comment]
> Maybe we can publish pre language? Also prevent unexpected embed format smile

Sounds good and bad :smile: Good for developers which known what they want, bad for new developers and DX

To be honestly I don't think size is real big issue for dev dependencies, I know many developers say I am wrong, but here two things:
1. good DX and big bundle - just install and all works
2. bad DX, a lot of packages - experience to understand what you need and extra setup

But if I'm not mistaken our philosophy is 0CJS, so I prefer big size over bad DX

**Comment by jaydenseric** [comment]
I just started work on a new Prettier plugin (to eventually be published), and immediately ran into Prettier crashing when attempting to test it, because internally Prettier incorrectly uses `require` to load the plugin, which is pure ESM in `.mjs` files. Prettier shouldn't assume plugins are CJS modules; it should use `import` to load plugins as that can import both CJS and ESM modules.

Over time, it will be impossible to ship certain plugins as CJS as most of the packages on npm you might need as plugin dependencies will be pure ESM.

Running into friction like this so soon kind of puts me off working on a Prettier plugin. Confusingly, the docs under ["Developing Plugins"](https://prettier.io/docs/en/plugins.html#developing-plugins) says:

> Prettier plugins are regular JavaScript modules with five exports

"Regular JavaScript modules" can only be interpreted as ESM. Additionally, the plugin code examples show ESM named exports:

<img width="911" alt="Screen Shot 2021-11-07 at 1 41 16 pm" src="https://user-images.githubusercontent.com/1754873/140630398-50335d1d-1cf2-491d-b91b-6222b1346424.png">

**Comment by jaydenseric** [comment]
I want to use [`estree-walker`](https://www.npmjs.com/package/estree-walker) in a Prettier plugin, but can't as it's a pure ESM package and Prettier doesn't support ESM plugins. This issue should be one of the top priorities for Prettier.

**Comment by fisker** [comment]
We are blocking by jest. Some how we can't get ESM module pass the test. See #11235

**Comment by jaydenseric** [comment]
Why use Jest at all? It's incredibly bloated ([25.6 MB install size](https://packagephobia.com/result?p=jest@27.3.1)), slow, and buggy with significant issues that don't get fixed for years. Not being able to test stock standard modules in Node.js is a huge red flag the tool is not fit-for-purpose.

All of this is being overcomplicated; Prettier could be unblocked by switching out Jest for simpler and more reliable tools that work more as libraries than heavy monolithic frameworks. Node.js has [a built in assertions library](https://nodejs.org/api/assert.html) and you can use [`snapshot-assertion`](https://github.com/jaydenseric/snapshot-assertion) or some other standalone dependency for snapshot test assertions. You can use [`coverage-node`](https://github.com/jaydenseric/coverage-node) to run your tests with code coverage using the build in Node.js coverage API. To harness your tests and get nice CLI reporting you can use [`test-director`](https://github.com/jaydenseric/test-director) or any one of a number of alternative lightweight tools.

**Comment by fisker** [comment]
#11891 makes this possible, we'll start the migration.

**Comment by fisker** [comment]
> I want to use [`estree-walker`](https://www.npmjs.com/package/estree-walker) in a Prettier plugin, but can't as it's a pure ESM package and Prettier doesn't support ESM plugins. This issue should be one of the top priorities for Prettier.

Your issue is not really blocking by this one, but #4459

**Comment by ancyrweb** [comment]
@fisker any plans for a release date ?

**Comment by fisker** [comment]
We are blocked by Jest again...

**Comment by TimvdLippe** [comment]
Over in #12144 we are working on reducing the bundle sizes of various packages. Some of the fixes (for example #12204) appear to be related to how tree-shaking interacts with CommonJS. If I am not mistaken, tree-shaking of CommonJS is (near) impossible, hence does it make sense to split up these utils to reduce the overall bundle.

That said, I think if Prettier were to move to ESM, you would get this "for free", where most modern tooling can determine which ES exports are used and which aren't, and drop those that are unused. Therefore, by switching to ESM, you might be able to avoid changes like #12204 as it becomes automatic for you.

**Comment by fisker** [comment]
Just want to give an update here, the migration is going smoothly.

**Comment by kachkaev** [comment]
Node 12 reached end of life in Spring 2022. How about supporting Node 14+ only?

**Comment by fisker** [comment]
So we can use TLA, private fields!

**Comment by fisker** [comment]
The source code has migrated to ESM, Node.js 10 & 12 support has been dropped.

Let's consider this done.


---

Some other questions related to ESM, but not included in this issue.

ESM bundle support tracking in #8772 .
ESM config file support should be easy to add.
ESM plugin support also planned in v3.

**Comment by strager** [comment]
The [release notes for version 3.0](https://prettier.io/blog/2023/07/05/3.0.0.html) mention Prettier switching to ES Modules:

> We have made the migration to using ECMAScript Modules for all our source code. This change has significantly improved the development experience for the Prettier team. Please rest assured that when using Prettier as a library, you can still use it as CommonJS as well.

What are some of the developer experience improvements? I don't see any mentioned in this thread related to ES Modules.
