### ISSUE TITLE
VSCode prettier printWidth not working for imports

### ISSUE THREAD

**Issue by alexdev888** [prettier/prettier#10162]
The problem is that VSCode ignores prettier printWith for imports. This causes problems with ng lint:

This line has a length of 147. Maximum allowed is 140 max-len

**Comment by thorn0** [comment]
This works as intended. Stylistic rules like `max-len` should be disabled if Prettier is used. Please see.

1. https://prettier.io/docs/en/rationale.html#imports
2. https://prettier.io/docs/en/integrating-with-linters.html
3. https://prettier.io/docs/en/options.html#print-width
