### ISSUE TITLE
Markdown: code with vertical bar (pipe) character nested in table interpreted as column delimiter

### ISSUE THREAD

**Issue by jasonroyle** [prettier/prettier#10164]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABAMQhdGBCAhgE54A6UGAtDXujVeZegAYBmOS6AzjMQJZQA5nV4DhAbQC6LOiwBGJWahAAaEBAAOMftG7JQJYhADuABRIJ9KQgBsThAJ77184oTABrODADKmj0EhZD4AVzh1OABbeTgAEzj4gBlCYVDCIThsYijCGB1hZBBCUJgINRAACxgo2wB1Sv54bgCwOF8rJv4ANybHIrBuFxBBbjhiGDN3IVzkNjsx9QArbgAPfHcvH19CKLgkwTg5hYiQFdXfINs4AEVQiHhj20WQAOIx4iLc4k840ygKppxDA6vw4jBKsgABwABnUQIgYzq7k0RSBcA+3SO6gAjvd4FMtNZitwqFA4PF4hViHA8fwaVMMrMkPNnqcxlF+CFiOF1Nwrrd8UcWSd1DBCPJQeDIUgAExi9z8WxBADCECizJAGIArBVQmMACoS6ysl7dcIASSgiVgvjAAm0AEFrb4YI5rk8xgBfL1AA)
```sh
--parser markdown
```

**Input:**
```markdown
| Foo | Bar |
| --- | --- |
| `foo: string | string[]` | `bar` |
```

**Output:**
```markdown
| Foo          | Bar       |
| ------------ | --------- | ----- |
| `foo: string | string[]` | `bar` |
```

**Expected behavior:**

The vertical bar character in the code to be ignored as it is not a part of the table construct.

**Comment by thorn0** [comment]
Not a bug. See #9146
