### ISSUE TITLE
[Question] plugin to take intellij inlay-type-hinting into consideration

### ISSUE THREAD

**Issue by gioragutt** [prettier/prettier#10180]
It's a general question related to the possibility of implementing a certain prettier plugin.

Intellij (and Webstorm) provides a ["Type Hinting"](https://www.jetbrains.com/help/webstorm/inlay-hints.html) feature, which, in-code, adds hints regarding types of variables.

It does it by inlaying those hints next to the variables themselves.

When writing code with typing, the width of the hints can get quite long, however, tools like prettier and other formatters don't (and shouldn't by default) take that into consideration.

Here's an example from a react code-base:
![image](https://user-images.githubusercontent.com/13711224/106358061-895bfb80-6312-11eb-8c36-8a7a30d7f6b5.png)

The fact that it makes the line so wide, makes the code-writer prefer to not destruct the code in-place but instead have a `prop` param and destructure it in a code-block:

```tsx
const MyComponent: FC<Props> = (props) => {
    const {prop1, prop2, propN} = props;
};

// over

const MyComponent: FC<Props> = ({prop1, prop2, propN}) => {
};
```

Question is - can a prettier plugin be made, such that:
* it would integrate with typescript,
* be able to read the types of variables, 
* compensate such that it would break the code into several lines when the width of the line *including the inlay hints* passes the max-width, and not only the width of the actual code?

So if I put it into an example, consider the `/* */` blocks as the inlay hints:

```tsx
// without inlay hints, code fits nicely into line-width
const PostCodeBlock: React.FC<PostCodeBlockProps> = ({ domNode, options, fallback }) => { ...

// with inlay hints, it's practically longer than max line-width, but won't break.
const PostCodeBlock: React.FC<PostCodeBlockProps> = ({ domNode /*: Element*/, options /*: HTMLReactParserOptions*/, fallback /*: FallbackElement*/ }) => { ...
```

Would become: 

```tsx
const PostCodeBlock: React.FC<PostCodeBlockProps> = ({ 
  domNode /*: Element*/,
  options /*: HTMLReactParserOptions*/,
  fallback /*: FallbackElement*/,
}) => { ...
```

**Comment by thorn0** [comment]
Hi. We use the issue tracker only for tracking bug reports and feature requests. For questions like this, please use StackOverflow.

> Question is - can a prettier plugin be made,

Yes, it can. To do this your plugin can monkeypatch Pretier's builtin TypeScript plugin and transform the input (add the comments) before Prettier's parser gets to it. But that looks like a lot of work for a not really useful result. Changing types in one file would affect the formatting of other files. Who would like such diffs?

**Comment by gioragutt** [comment]
> Hi. We use the issue tracker only for tracking bug reports and feature requests. For questions like this, please use StackOverflow.
> 
> > Question is - can a prettier plugin be made,
> 
> Yes, it can. To do this your plugin can monkeypatch Pretier's builtin JS/TS plugin and transform the input (add the comments) before Prettier's parser gets to it. But that looks like a lot of work for a not really useful result. Changing types in one file would affect the formatting of other files. Who would like such diffs?

@thorn0 the change I want is not to add the comments. The point is that the comment isn't really part of the code, but is something added in the IDE.

The way I see it, it would be to kinda trick prettier and increase the actual width of the variables, so it would break lines earlier.

I'm not using intellij/webstorm so this change is not for me, but for people/organizations that DO use these tools, it might be a good thing, since it would make formatting take into consideration something that exists in the IDE, but not in the code.

**Comment by thorn0** [comment]
If your plugin prints spaces instead of those comments, it'll do the trick. Prettier removes trailing spaces.
