### ISSUE TITLE
Extra newlines in function with destructured object argument

### ISSUE THREAD

**Issue by lelandrichardson** [prettier/prettier#1019]
I couldn't find if this had been discussed before or not.

We tried this on our code base and a lot of stateless functional components showed up with this diff and it feels like we could optimize for this case:

I expect the following:
```jsx
export default function StatelessFunctionalComponent({
    isActive,
    onFiltersUpdated,
    onSelect,
    onSubmitAndDeselect,
    onCancel,
    searchFilters,
    title,
    items,
}) {
  return <div />
}
```

but instead we get:
```jsx
export default function StatelessFunctionalComponent(
  {
    isActive,
    onFiltersUpdated,
    onSelect,
    onSubmitAndDeselect,
    onCancel,
    searchFilters,
    title,
    items
  }
) {
  return <div />;
}
```

It seems like as long as the destructured param was the last param, and the param list wasn't already multi line, you could do it this way

[repl](https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20default%20function%20StatelessFunctionalComponent(%7B%5Cn%20%20%20%20isActive%2C%5Cn%20%20%20%20onFiltersUpdated%2C%5Cn%20%20%20%20onSelect%2C%5Cn%20%20%20%20onSubmitAndDeselect%2C%5Cn%20%20%20%20onCancel%2C%5Cn%20%20%20%20searchFilters%2C%5Cn%20%20%20%20title%2C%5Cn%20%20%20%20items%2C%5Cn%7D)%20%7B%5Cn%20%20return%20%3Cdiv%20%2F%3E%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

**Comment by sebmarkbage** [comment]
This came up in the React repo with some explanations and alternatives:
https://github.com/facebook/react/pull/9101#discussion_r104100215
https://github.com/facebook/react/pull/9101#discussion_r104101084

**Comment by vjeux** [comment]
This has come up in the past but the use case seemed very "edge-casey". SFC are a good use case. I'll see how hard it is to implement.
