### ISSUE TITLE
Glimmer parser destructively re-orders component modifiers and comments

### ISSUE THREAD

**Issue by lougreenwood** [prettier/prettier#10203]
When mixing comments in with the args of an Ember "angle brackets" component, the comments will be destructively sorted to the end of the arguments list.

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAsgTwMIQLYAO0CMAOlAAQXDACEFMAFgJYDOFbFAhhZHniQoAzCACduogOYUAjAF855KgAEuUmQF5SIRnAA2eiNqUVVUgExad+w8crU6DFu048+A2MLETpAZgUmZpK+VroGRiCBapIALKE2ESY09Eycrrz4HjBe4tEUAKwB9kH58eF2APQAfCAANCAQBDDM0KzIoGqiEADuAApqCG0oXHrdXJht9QBGolxgANZwMADKBHPMUJLIMKIArnD1cHhTcAAmp2cAMlybu1yScABiYnhcMM2byCBcuzAQdToYHg9AB1FjwVhrMBwZaDZjNABu8MwXzArEmIA2rDgohgvVmkleyCEI2x9QAVqwAB4AIVmCyWyy4AkuGzgxNJBxAlKpyw2kj0cAAirsIPAOXoySA1qJsaIvgLmPwcQCCKINjAQcxTkxkAAOAAM9TVEGxINmBC+argcoR7PqAEdRfB8Y0ht9WABaKBwM5nAGiOBO5iB-H3IlIEmSrnYvDMbZ7GP8wUisXsyOc+owLhTLU6xjIcxZ2bMPT83D8LhfG35AG7bEAFRzQyjUoR+wAklALrBlmB1U0AILd5YwTCCiXYhRAA)

```sh
# Options (if any):
--parser glimmer
```

**Input:**

```hbs
<MyComponent
  {{! this is a comment for arg 1}}
  @arg1="hello"
  @arg2="hello"
  {{! this is a comment for arg 3}}
  @arg3="hello"
  @arg4="hello"
  {{! this is a comment for arg 5}}
  @arg5="hello"
/>
```

**Output:**

```hbs
<MyComponent
  @arg1="hello"
  @arg2="hello"
  @arg3="hello"
  @arg4="hello"
  @arg5="hello"
  {{! this is a comment for arg 1}}
  {{! this is a comment for arg 3}}
  {{! this is a comment for arg 5}}
/>
```

**Expected behavior:**

```hbs
<MyComponent
  {{! this is a comment for arg 1}}
  @arg1="hello"
  @arg2="hello"
  {{! this is a comment for arg 3}}
  @arg3="hello"
  @arg4="hello"
  {{! this is a comment for arg 5}}
  @arg5="hello"
/>
```

**Comment by NullVoxPopuli** [comment]
I just noticed this here: https://github.com/prettier/prettier/issues/10588

**Comment by lougreenwood** [comment]
I think that this also manifests as a similar bug where `...attributes` gets re-ordered.

**Before:**
```hbs
<input
  {{on "click" this.someThing}}
  name="hello"
  ...attributes
/>
```

**After:**
```hbs
<input name="hello" ...attributes {{on "click" this.someThing}} />
```

**Expected:**
```hbs
<input {{on "click" this.someThing}} name="hello" ...attributes/>
```

Although I'm not sure just how much of a bug this is, since I'm not sure if the order of "element modifiers" matters (in terms of whether the modifiers passed in via `...attributes` being applied before the defined ones matters).

**Comment by jelhan** [comment]
> Although I'm not sure just how much of a bug this is, since I'm not sure if the order of "element modifiers" matters (in terms of whether the modifiers passed in via `...attributes` being applied before the defined ones matters).

I think that makes a functional difference. The order in which modifiers are run is guaranteed. From [RFC 373](https://github.com/emberjs/rfcs/blob/master/text/0373-Element-Modifier-Managers.md), which added Modifiers:

> ## Modifier Lifecycle
>
> [...]
>
> ### createModifier
>
> [...]
>
> Always
>
> - called as discovered during DOM construction
> - called in defintion order in template

Depending on the modifier it may or make not a difference. One example for would it make a difference is [ember-style-modifier](https://github.com/jelhan/ember-style-modifier).

Let's take this component as an example:

```hbs
// app/components/square.md

<div {{style backgroundColor="green" height="100px" "width="100px"}} ...attribute></div>
```

If called as `<Square />` it would have a green background but if called as `<Square {{style "backgroundColor" "red"}} />` it would have a red background.

If being changed like this by Prettier it would always have a green background:

```patch
- <div {{style backgroundColor="green" height="100px" "width="100px"}} ...attribute></div>
+ <div ...attribute {{style backgroundColor="green" height="100px" "width="100px"}}></div>
```

**Comment by NullVoxPopuli** [comment]
how would you then override the height/width with attributes?
should attributes _always_ come last?

**Comment by jelhan** [comment]
> how would you then override the height/width with attributes?
> should attributes _always_ come last?

It is valid choice of component's author to _not_ allow customizing some HTML attributes. Same should apply for enforcing some modifiers to run at the very end. I think Prettier should not change the order of modifiers and `...attributes`.

**Comment by lougreenwood** [comment]
> > how would you then override the height/width with attributes?
> 
> > should attributes _always_ come last?
> 
> 
> 
> It is valid choice of component's author to _not_ allow customizing some HTML attributes. Same should apply for enforcing some modifiers to run at the very end. I think Prettier should not change the order of modifiers and `...attributes`.

Completely agree - hopefully fixing this bug means that comments and modifiers stay where they were authored, which means attributes won't start jumping around. 🤞
