### ISSUE TITLE
Parser bundles for HTML, Markdown, CSS include unexpected parts

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#10206]
I noticed that `parser-html.js` includes the content of `doc-builders.js` and `doc-printer.js`. Turns out the same is true for `parser-markdown.js` and `parser-postcss.js`. Looks like a bug.

**Comment by fisker** [comment]
Because of frontMatter print?

**Comment by thorn0** [comment]
Probably. I'd thought it should have been tree-shaken, but apparently it isn't.
