### ISSUE TITLE
Weird JSX mixed node contents formatting

### ISSUE THREAD

**Issue by n1k0** [prettier/prettier#1021]
Couldn't find an existing issue about this, but sometimes prettier makes strange decisions wrt JSX content formatting:

```jsx
function DiffOverview(props) {
  const { source, target, since } = props;
  return (
    <div>
      <div className="alert alert-info">
        <p>
          This diff overview is computed against the current list of records in
          this collection and the list it contained on <b>{humanDate(since)}</b>.
        </p>
        <p>
          <b>Note:</b> <code>last_modified</code> and <code>schema</code> record metadata 
          are omitted for easier review.
        </p>
      </div>
      <Diff source={source} target={target} />
    </div>
  );
}
```

Is formatted like this:

```jsx
function DiffOverview(props) {
  const { source, target, since } = props;
  return (
    <div>
      <div className="alert alert-info">
        <p>
          This diff overview is computed against the current list of records in
          this collection and the list it contained on
          {" "}
          <b>{humanDate(since)}</b>
          .
        </p>
        <p>
          <b>Note:</b>
          {" "}
          <code>last_modified</code>
          {" "}
          and
          {" "}
          <code>schema</code>
          {" "}
          record metadata
          {" "}
          are omitted for easier review.
        </p>
      </div>
      <Diff source={source} target={target} />
    </div>
  );
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20DiffOverview(props)%20%7B%5Cn%20%20const%20%7B%20source%2C%20target%2C%20since%20%7D%20%3D%20props%3B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%3Cdiv%20className%3D%5C%22alert%20alert-info%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%3Cp%3E%5Cn%20%20%20%20%20%20%20%20%20%20This%20diff%20overview%20is%20computed%20against%20the%20current%20list%20of%20records%20in%5Cn%20%20%20%20%20%20%20%20%20%20this%20collection%20and%20the%20list%20it%20contained%20on%20%3Cb%3E%7BhumanDate(since)%7D%3C%2Fb%3E.%5Cn%20%20%20%20%20%20%20%20%3C%2Fp%3E%5Cn%20%20%20%20%20%20%20%20%3Cp%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3Cb%3ENote%3A%3C%2Fb%3E%20%3Ccode%3Elast_modified%3C%2Fcode%3E%20and%20%3Ccode%3Eschema%3C%2Fcode%3E%20record%20metadata%20%5Cn%5Ct%5Ct%20%20are%20omitted%20for%20easier%20review.%5Cn%20%20%20%20%20%20%20%20%3C%2Fp%3E%5Cn%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%3CDiff%20source%3D%7Bsource%7D%20target%3D%7Btarget%7D%20%2F%3E%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

This makes the code harder to read imho.

**Comment by vjeux** [comment]
Related issue on https://github.com/prettier/prettier/issues/963 cc @rattrayalex

**Comment by rattrayalex** [comment]
Yeah, we should probably merge these two issues. Maybe merge that one into this one, since the other had two reports? If so, I can change the title to clarify

**Comment by rattrayalex** [comment]
To summarize the discussion in #963, it is indeed unfortunate, but will probably require the addition of a fairly fundamental primitive to the prettier internals (that allows breaking a single `line` without breaking the entire group). I don't personally feel motivated to tackle this in the near term, but would like to see it happen, and might take it on later.

**Comment by rattrayalex** [comment]
I'm actually not sure it needs the `Needs Discussion` label so much as `help wanted`, or just `difficult` ?

**Comment by jlongster** [comment]
Let's merge into #963 as there's more discussion, if that's ok.
