### ISSUE TITLE
Valid syntax in prettierignore doesn't ignore folder, still throws an error as if it's included

### ISSUE THREAD

**Issue by MindTooth** [prettier/prettier#10236]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI
- Runtime: Node.js v15.7.0
- Operating System: macOS

**Steps to reproduce:**

The  folder  `ui/app/__pycache__`, ignored via `.prettierignore`, doesn't get ignored.

Have the file `.prettierignore` with the following content:
```gitignore
__pycache__/
node_modules/
ui/app/static/
```

_(I've tried all possible combination of ignoring syntax for catching the folder.)_

Run the following command:
```
$ prettier **/* --list-different --ignore-unknown
```

Get the follow output:
```
[error] No supported files were found in the directory: "ui/app/__pycache__/".
```

Receive unsuccessful shell exit code which in turn breaks the workflow.

---

Tested using the small script below, and it reports back `true`:
```js
const ignore = require("ignore");
console.log(ignore().add(["__pycache__/"]).ignores("ui/app/__pycache__/"));
```

As I've newer touched JS/Node.js before, I don't know if this is the correct way of testing my issue.

However, if I have the ignore file inside `ui/app` and run `prettier` inside there, it works as expected.

**Expected behavior:**

The folder `ui/app/__pycache__` is ignored and don't throw an error because `prettier` doesn't find supported files inside.

**Actual behavior:**

`prettier` throws an error because it can't locate supported files inside the folder `ui/app/__pycache__`.

**Comment by thorn0** [comment]
Looks like you forgot to put quotes around the glob pattern.

> Don’t forget the quotes around the globs! The quotes make sure that Prettier CLI expands the globs rather than your shell,

https://prettier.io/docs/en/cli.html

Am I right?

**Comment by MindTooth** [comment]
> Am I right?

Yes. 😔 

Thank you so much!  Really appreciate the quick reply.
