### ISSUE TITLE
The arrays format should behave like objects.

### ISSUE THREAD

**Issue by infacto** [prettier/prettier#10246]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA8gIwFZxgwDOGA7hAE4DWpZcANgwHQYBCArjBgIKWUBDAJ6liACwgcGAEwxiBANzgYYY5cQEBbZTjjyFASypIAOlHQYAInHhEMOSnAHUVEDADMqmgd3FVuABQAPBgADpQGsOQG0qoAlGZmkFDE3BD4AIwYALwYwBjQcEgYGQA0KhTFAEzlqo5FGADMGAC+ANxJ0KkF+FU5eRhmGAVQDWUVENW1YvXFze2dKWn4zbn5QyNj5RswlRg1g1DDdXANjWYLUMnd6XgALP35hcXju5P707NN5Z4clMV3H4GJTFACs5WIBgAHsUAGwQuBKKDFADs5TgBgA5mIYMUABytDpQRbdAT8LK5ADaAHIsKNqeVqQAVCgMjDMmanakAXSJ124ZMofSpG1p9MZLIgbI59R5fK6Av4qwwlNFdLgbNFks1R3ZTM5GrMvJJisoDypYo1EtZEoN0oAYpJKA7gVb2QBlaHS92IhDSgCiWJx0oAcpENcbieZMAAlODEKS4jCCvoCKCyQXNPxSWS6DxeHzwWQMAzUZS3VPpnp4RqsALSGyEbgOJzUBJRiyWAyUGBCcgCBjUMmSdOmKP85NK-qq3WWtkWLU2w7DGVco1EswWLCUDDSAwaHAMZThGwwAxwHeeHeqfcYEujVicAUMYhuKAQAUYTEQCCyGJOZgzBAUoQAgUIzy6ZBQEFCAyAABTJBBiGQEABzIYRkJAhwBDAMsYHdUIcMiTFkBgSgODgEC4E0XRpAbaQABk00xDgBExOBHUobwYDPKASJQAQuAgYCQBxTQGAAdTEAx4GIQiwDgH0Uhk4EZKEFCwGITCQEiYgLxgODBExbxkHcAc9JAvBiChNhBFwmx3S0OAGPDUzzMokArKhT0+KPABFDgPzgNyXw8wjKD0ygUJwARdAYETwkiGAJJiVRkDxAAGEDwggPSJMEUIUJPSKlBEgBHQL4EMsDkIE4gAFpRjgeiRMcCruzgQy2JMpAzNCkC9M0AxSPIjzIV8uAAqCkKLJAGBYpS2IxGQGo5sEAx70xABhCBNB6kB41BESOD0plYtqvrZoUCiAEl0wQfCwAicCeHTd1eyPGa4BaFogA)

<details><summary><strong>Screenshot</strong> (if playground not work) - click to expand.</summary><p>

---

![image](https://user-images.githubusercontent.com/60390085/106910496-9194ac00-6701-11eb-91fb-ceb29af8276a.png)

---
</p></details>

See playground to view used options. Locally, I use the default settings.

**Input:**

```jsx
// ... (see playground)
const arr1 = ["One", "Two", "Three"];
const arr2 = [
  'One', 'Two', 'Three'];
const arr3 = [
  'One', 
  'Two', 
  'Three'
];
// ... (see playground)
```

**Output:**

```jsx
// ... (see playground)
const arr1 = ["One", "Two", "Three"];
const arr2 = ["One", "Two", "Three"];
const arr3 = ["One", "Two", "Three"];
// ... (see playground)
```

**Expected behavior:**

```jsx
const arr1 = ["One", "Two", "Three"];
const arr2 = [
  'One', 
  'Two', 
  'Three'
];
const arr3 = [
  'One', 
  'Two', 
  'Three'
];
```

It should behave like objects. Which is a great solution without options. Just detect if a break (multiline format) is wanted for short arrays (objects; < print width).

The objects are formatted like (see playground):

**Input:**

```jsx
const obj1 = { one: 1, two: 2, three: 3 };
const obj2 = { 
  one: 1, two: 2, three: 3 };
const obj3 = { 
  one: 1, 
  two: 2, 
  three: 3
};
```

**Output**

```jsx
const obj1 = { one: 1, two: 2, three: 3 };
const obj2 = {
  one: 1,
  two: 2,
  three: 3,
};
const obj3 = {
  one: 1,
  two: 2,
  three: 3,
};
```

🙏

**Comment by thorn0** [comment]
Please see the option philosophy https://prettier.io/docs/en/option-philosophy.html

> Please note that as option requests are out of scope for Prettier, they will be closed without discussion. The same applies to requests to preserve elements of input formatting (e.g. line breaks) since that’s nothing else but an option in disguise with all the downsides of “real” options.

Also see the "note on formatting reversibility" here:

https://prettier.io/docs/en/rationale.html#multi-line-objects

**Comment by infacto** [comment]
@thorn0 I know the Prettier philosophy of few options as possible. And that's great. But in some cases we should provide options for different behaviors. In cases where opinions differ. 50/50. Like the "semi-manual formatting" of this kinds of line break detection. In some case we want keep multiline objects / arrays with a few items which would fit the print width. It's really annoying to so that objects collapsing. 

Here are other options of matter of taste:
- [Bracket Spacing](https://prettier.io/docs/en/options.html#bracket-spacing)
- [Arrow Function Parentheses](https://prettier.io/docs/en/options.html#arrow-function-parentheses)
- etc.
- With this issue: **Keep Multiline Objects / Array**

Why is the community ignored? Here is another related issue: #352 With many upvotes. Certainly not the only one.
There are so many request for this "feature".

The alternative is e.g.

```ts
const arr = [
  'One', // < this
  'Two',
  'Three'
];
```

or

```ts
// prettier-ignore
const arr = [
  'One',
  'Two',
  'Three'
];
```

But this is not "prettier". There should be no annotation or hacks for the formatter in the code.

... It's a pity.

**Comment by scscgit** [comment]
If the array doesn't follow object's behavior, would it be possible to at least make the object follow array's behavior for sake of consistency (of formatting reversibility)? For example I'm in a situation where I'm replacing a JSON by an almost identical JSON, but with the objects collapsed; causing countless diffs that the `prettier --write` ignores, and there's no setting to allow making this deterministic 🤔 Not only can't we use a code formatting rule in a project, but there isn't even any command to manually reformat a file.
