### ISSUE TITLE
How to prevent formating / wrapping objects in javascript 

### ISSUE THREAD

**Issue by hermify** [prettier/prettier#10258]
Hi there,
tried everything in settings.json.

I have an Array with objects inside and dont wan't it. to being formatted to new line. 

tried with 
    "html.format.wrapAttributes": "preserve-aligned",
	"editor.wordWrapColumn": 10000,
	"html.format.preserveNewLines": true,
    "prettier.printWidth": 2100,

with no success.

**Comment by thorn0** [comment]
Hi. This issue tracker is only for tracking bug reports and feature requests. For questions like this, please use StackOverflow.

It's not really clear what you're asking, but probably what you're looking for is this: https://prettier.io/docs/en/ignore.html#javascript
