### ISSUE TITLE
why the if comment is line breaked?

### ISSUE THREAD

**Issue by tawon2137** [prettier/prettier#10250]
Is there any way to prevent line break?

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEMCGaDWAgpgLyYAUAlKQHybAC+AOlJFBtnvgEKkXUk6jFmw64CAYT5Va9ZlBYB6AFTKWmTMswABAA44ATjgC29AEYQIAGzg4oDTAEs0mALTY4HfUePrNilgAzAFdWGEdoDwxyZ2pgP0dAmLRqcSIZRUUnFxJczAAVA2C4WXyuQj84KzQSxPIAQljOAm4MrOdSPIAxHGqSwQKubkq+5vwJNuzOslCAEzhAxyg4WdKuCRZ5EAAaEAhdcPRkUEMDCAB3AAVDBDRkEF7znABPO92zIzB8OBgAZX0wEsAObIGBFOC7ODGMwreazAAydiBwRwQLgXQgBmMOBg4SgIJQOGCMAgOxAAAsYMYrAB1cmOeBoAFwX63BmOABuDOe90cQKgmLgZKWNQMMEuRiB2OQgV6NV2ACs0AAPbifb5-ExweFLIVIWV9RUq37AmwARWCEHgMrlEJA3lF9zMOBhVjJugMSxgNMcsxg5OQAA4AAy7D0QGo0oy6e6PF5vEAAR0t8Al+zuKA9njgBg5Qt2BjgycchYlqOl+ttuxqxkcNsNIDQprgFqterBxV2uDMPr9AaQACYu0ZHFZgRIIMYKyBPABWMnBGplMwZg3ykAc4oASSg81gvzAnoOhF3vxgzxs9ZqDAYQA)
```sh
--html-whitespace-sensitivity ignore
--parser babel
--prose-wrap always
--quote-props preserve
--no-semi
--single-quote
```

**Input:**
```jsx
const taskA = () => {}
const taskB = () => {}
const taskC = () => {}

/**
  * @param {boolean} is - test param
  */
function test(is) {
  if(is) taskA() // is === True => TaskA
  else if(!is) taskB() // is === False => TaskB
  else taskC() // is === undefined => TaskC
}

```

**Output:**
```jsx
const taskA = () => {}
const taskB = () => {}
const taskC = () => {}

/**
 * @param {boolean} is - test param
 */
function test(is) {
  if (is) taskA()
  // is === True => TaskA
  else if (!is) taskB()
  // is === False => TaskB
  else taskC() // is === undefined => TaskC
}

```

**Expected behavior:**
```jsx
const taskA = () => {}
const taskB = () => {}
const taskC = () => {}

/**
 * @param {boolean} is - test param
 */
function test(is) {
  if (is) taskA() // is === True => TaskA
  else if (!is) taskB() // is === False => TaskB
  else taskC() // is === undefined => TaskC
}

```

**Comment by thorn0** [comment]
The intention was to support these often-requested cases:
```js
function test(is) {
  if (is) {
    taskA()
  }
  // is === True => TaskA
  else if (!is) {
    taskB()
  } // is === False => TaskB
  else taskC()
}
```
This issue might be an unintended side-effect of fixing that.
