### ISSUE TITLE
Possible to use to use multiple community plugins with the same parser?

### ISSUE THREAD

**Issue by hrougier** [prettier/prettier#10261]
Hi,

It seems like multiple community plugins can't work together as soon as they override a specific prettier parser.
For example, [prettier-plugin-jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc) and [prettier-plugin-organize-imports](https://github.com/simonhaenisch/prettier-plugin-organize-imports).

It is most likely due to the fact that both plugins are defining their own typescript parser ([here](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/54bdbc54614d2919f426a926b0612de47d5e5fdd/src/index.ts#L90) and [here](https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/120c88b58e0d751958a2e5bb3f0dac1a31221d4a/index.js#L92)), both importing `prettier/parser-typescript` to inherit from it.

`prettier-plugin-jsdoc` uses the `parse` property of the typescript parser while `prettier-plugin-organize-imports` uses the `preprocess` property, but the last plugin loaded (alphabetical sort) completely overrides what is defined by the previous one.

I managed to have them both working by doing something like this

`.prettierrc.js`

```js
const { merge } = require('lodash')

module.exports = {
  // ... prettier config
  plugins: [merge(organizeImports, jsDoc)],
}
```

But it is not an ideal solution as it kind of loses the plugin autoloading feature by having to manually merge them (the original plugins are still autoloaded but the merged one overrides them).
Moreover, if another plugin like `prettier-plugin-tailwind` is used, which also [inherits](https://github.com/Acidic9/prettier-plugin-tailwind/blob/master/src/parsers/typescript.ts) and uses the `parse` property of the typescript parser, this makes it quite difficult to handle.

Is there a better way to handle this use case or would it be possible for prettier to manage it by automatically composing the properties defined by custom plugins ?

Thank you for your time ✌️

**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI
- Runtime: Node.js v14
- Operating System: macOS

**Steps to reproduce:**

```
yarn add prettier-plugin-jsdoc
yarn add prettier-plugin-organize-imports
yarn add prettier-plugin-tailwind
```

**Expected behavior:**

All plugins working together.

**Actual behavior:**

Only the last plugin loaded by prettier works.

**Comment by thorn0** [comment]
What these plugins do isn't really an officially supported use case. However, they could be modified to take other such plugins into account. See https://github.com/prettier/prettier/issues/10259#issuecomment-774013489

Closing in favor of #4424 (an issue where a non-monkeypatching API for extending Prettier's built-in plugins/languages is discussed).
