### ISSUE TITLE
User should be able to enable experimental parsers via configuration

### ISSUE THREAD

**Issue by jelhan** [prettier/prettier#10263]
Prettier includes some experimental parsers that are not officially released yet. One example is Glimmer parser for Handlebars templates.

Experimental languages are not returned by [`prettier.getSupportInfo()`](https://prettier.io/docs/en/api.html#prettiergetsupportinfo). Many tools build on top of Prettier rely on that method to detect support languages. One example is the official Prettier plugin for VSCode.

Prettier does not allow an user to enable a language for a project even though it has not been officially released yet. This breaks established tools from the ecosystem and requires hacky work-a-rounds. This situation has lead to two unofficial VSCode plugins to use Prettier for Handlebars: [Prettier for Handlebars](https://marketplace.visualstudio.com/items?itemName=EmberTooling.prettier-for-handlebars-vscode) and [vsc-prettier-glimmer](https://marketplace.visualstudio.com/items?itemName=AdamBaker.vsc-prettier-glimmer). Both extension try to replicate the functionality of the official Prettier for VSCode extension. Additionally they enable Glimmer parser for Handlebars language.

It seems as if this limitation could be overcome if a parser for a language could be enabled in project configuration. E.g. an `enableExperimentalParsers` option could be added to [Prettier configuration](https://prettier.io/docs/en/options.html). If would take a list of parsers, which should be returned by `prettier.getSupportInfo()` even if they are not officially released yet. Following the Glimmer parser example a project could enable it like this:

```json
{
  "enableExperimentalParsers": ["glimmer"]
}
```

Not yet released parsers are explicitly filtered out by `getSupportInfo()`: https://github.com/prettier/prettier/blob/ce26805e84756953875f30a0c165bd6b09c94ea0/src/main/support.js#L40 The filter is implemented here: https://github.com/prettier/prettier/blob/ce26805e84756953875f30a0c165bd6b09c94ea0/src/main/support.js#L83-L89 The `showUnreleasedFlag` is not exposed as public API. Public method `prettier.getSupportInfo()` does not except any argument. So a tool can not even request to include unreleased parsers.

I'm not an expert in Prettier code base for sure. But implementation may be as simple as adding another check to `filterSince` utility function to _not_ exclude a parser if is included in `enableExperimentalParsers` option of project configuration.

Alternatively to adding the configuration option to Prettier itself it could be added to each tool. There is an open issue for Prettier for VSCode to do so: https://github.com/prettier/prettier-vscode/issues/1747 But adding it to each tool is not an optimal solution in my opinion. Implementing and maintaining at several places would require way more work. And it may lead to fragmentation in the ecosystem of some tools providing support for experimental parsers and some not.

I'm not sure if the Handlebars situation maybe special. The glimmer parser has known issues for some cases. I fully understand that it is not officially released yet. But for most projects it is stable enough. It has been developed and tested over years. Some projects decided to use it even it is not officially released. [ember-template-lint-plugin-prettier](https://www.npmjs.com/package/ember-template-lint-plugin-prettier) has 4000 weekly downloads accordingly to NPM.

I see the risk of making it easier to use a non yet released parser. The project may get more duplicated bug reports and loose reputation. But I think this risk can be mitigated by requiring an opt-in and explicitly calling out the experimental status in the option.

On the other making it easier for early adopters to opt-in into experimental parsers may help with Prettier development itself. Early adopters are known to provide good bug reports and even fixes themselves.

**Comment by thorn0** [comment]
Probably other editor integrations don't rely on the `languages` property of the return value of `getSupportInfo`. Only VS Code users complained about this so far. That's why let's consider this issue VS Code specific for now.

Prettier doesn't associate files with unreleased parsers by default. [Configuration overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides) should be used to tell Prettier that certain files should be handled by such parsers. Example:
```
  "overrides": [
    {
      "files": "*.hbs",
      "options": {
        "parser": "glimmer"
      }
    }
  ]
```
Then the VS Code extension can be told to be active for this files by using its [`documentSelectors` setting](https://github.com/prettier/prettier-vscode#prettierdocumentselectors).

This should be enough to solve the problem for VS Code. Please confirm.

As for the issue overall, `glimmer` - the only unreleased parser - seems to be pretty close to being out of experimental. After that it's highly unlikely Prettier will have experimental parsers ever again, since it has the plugin API now, and a plugin is a much better place for experiments than the core. That's why I'm not sure this issue needs any action.

**Comment by jelhan** [comment]
Thanks a lot for your quick response. It's working like a charm. I agree that this work-a-round should be good for now until glimmer parser is officially released.

I needed to do some more configuration to tell VSCode to format Glimmer templates with Prettier on save. Will document this step as reference for others from Ember community as I think it's a very common configuration.

I run Prettier as ESLint plugin for JavaScript and TypeScript files. Therefore I have not configured VSCode to format all files on safe but use `editor.codeActionsOnSave` to run ESLint, which also fixes Prettier:

```json
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": true
}
```

As ESLint does not run for Glimmer Templates I needed to configured VSCode to format on save for Glimmer Templates:

```json
"[handlebars]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
}
```

After adding this configuration as well Glimmer templates are formatted by VSCode when I save them as I'm used to from other files. :tada:

**Comment by jelhan** [comment]
I have written a blog post documenting the required steps to lint Glimmer templates in Ember.js: [ Format Glimmer templates with Prettier ](https://dev.to/jelhan/format-glimmer-templates-with-prettier-ipa) Hope it helps people to get up and running with Prettier for Glimmer templates quickly.
