### ISSUE TITLE
Plugin: How can i get functions params list

### ISSUE THREAD

**Issue by hosseinmd** [prettier/prettier#10264]
How can I get params of functions(function/arrow function/object or class methods) as an array of strings

**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: 
- Runtime: 
- Operating System: 

**Steps to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by thorn0** [comment]
Please fill the issue template. It's there for a reason as it's not clear what you're asking.

**Comment by hosseinmd** [comment]
> Please fill the issue template. It's there for a reason as it's not clear what you're asking.

This is a question

**Comment by hosseinmd** [comment]
Parser give me an AST obj I want to get params of functions, to sort jsdoc params, I did it, but I want to know, is a better way to do that? Or has a utility for that?

**Comment by thorn0** [comment]
No, Prettier does not and will not provide any API for that.
