### ISSUE TITLE
Vue template - Whitespace in inline elements are not handled correctly

### ISSUE THREAD

**Issue by lyle45** [prettier/prettier#10279]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDOWeUhAFnDjhGVRBnALQBOceFgE9urKAHNuVGLwCWE9px79BOEWMnS5Cjlz4Dho6JpnzxivSsMappiagD0NOiXKVn9MkxZtdyg2pGErba5n76qurGIWYW-pFBJqFxEdbRWrGOHq7EMKSOmLgEcDlQ1GByWDCuOHAwZAAK-DAwsnC8ZAC8ZABmELwYBF2EZMBkQhAArrwAdABWVAAUAOQwDFPiDMsAlGQAvvlOFbJVpdQwQrWuM3QAJqNkYFRUSGQwEGwAhLLY-TB09QOZScFyuIAANCAIFVZNAqMhQHheLwIAB3BpIhDwlCCVF4ITwyEAI14eDAAGs6gBlWhgMzIGSTOCQuAYIlwW63DkAGTo4kmeHEcAAYv1Bi16TjJu8ISAGDAMDgAOoMWTwZxgOBUrFq2QANzVQmQ4GesvkVHaMCagsGyB6ggtkIWAA8AEKkinUvBcbnyOB2h3MkAuqlmWoARUmEHgAZwjpAtF4Ft4xr1TNlWG0MCVslua2QAA4AAyQzMQC1K0lYY2ZuDJvX+yEARyj8Ca0OxIDwVG4UDgHI5sv4Ldk-Gt4ltSHtcaDFowsgZvCZkKoYbgkej-qngch-yJObzDGQACZd6TZDgzABhTiTkB1gCsssmFoAKngidjp-G03AAJJQFysBUscVQAIKAVSoJbt+cB7HsQA)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <span>hello some-really-long-string some-really-long-string some-really-long-string some-really-long-string</span>
  <span> hello some-really-long-string some-really-long-string some-really-long-string some-really-long-string </span>
	
</template>
```

**Output:**
```vue
<template>
  <span
    >hello some-really-long-string some-really-long-string
    some-really-long-string some-really-long-string</span
  >
  <span>
    hello some-really-long-string some-really-long-string
    some-really-long-string some-really-long-string
  </span>
</template>
```

**Expected behavior:**

In vue, when formatting inline elements, whitespace sensitivity happens exactly opposite of expected behavior. inline elements that start or end with a meaningful whitespace are treated as blocks, while no whitespace are treated as inline

I searched the issues and could not find relevant bug report for this behavior

**Comment by thorn0** [comment]
This works as expected. You didn't write what the expected behavior is in your opinion, so I don't understand why exactly you think there is a problem.

**Comment by lyle45** [comment]
@thorn Thank you for the quick reply. Maybe I'm misunderstanding about meaningful whitespaces, but from what I see,
the formatting would change html view

```
<span>bar </span>
<span>baz</span>
```

would output `bar baz` while the formatting output

```
<span>
  bar
</span>
<span
  >baz<
/span>
```

will output `barbaz`

Am I missing something?

**Comment by thorn0** [comment]
Both output `bar baz`.

See one of this:
* [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace#how_does_css_process_whitespace)
* [CSS spec](https://www.w3.org/TR/css-text-3/#white-space-processing)
* use your browser and a text editor to check how things are rendered

**Comment by lyle45** [comment]
@thorn0 Damnit, my apologies I only figured it would change output if another inline element comes after it, but than prettier formats differently... Thank you man
