### ISSUE TITLE
Prettier crashes VS code extension host

### ISSUE THREAD

**Issue by AbdulAhadArain** [prettier/prettier#10292]
After VS code update **January 2021 (version 1.53)** extension host is crashing and formatting is not working on windows 10.

**Comment by thorn0** [comment]
This repository is only concerned with the core formatting tool and not the editor integrations. Unfortunately, there's not much we can do to help you in this case, especially given that you haven't provided very little details. I suggest you submit a more detailed report (e.g. check what the extension prints in its console, it's here: <kbd>ctrl-shift-u</kbd> → "Prettier") on the extension's issue tracker: https://github.com/prettier/prettier-vscode
