### ISSUE TITLE
Redundant parens around ternary in arrow function

### ISSUE THREAD

**Issue by jackgeek** [prettier/prettier#10305]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgBAARgTwAc4tgBxAJwENCALANQEs4B3ASVjmrBkegAkqFKHADOogL5Z0qADoiAHoQgUYWACZwAZlQCuAGzUAKAJRYAvAD5S8rFgpwYu4Tah27Ac0cARRqML6VPhw6gBijIZcIQCCFBQQLKLRUOoAchCaokhYphbWwLbudpBQompaEfAO6pQ0tBakEgDchUUVkdW1dAB0+oxQANaiDR7UPX2Doq1FWN0AtjRGRsBYjOpYEgA0qylwCmZWWF4wbElxCeEdIUb9mvtYAPyr69lQBvom00Xd7VVLawdrGssABCczmLBvfQfFpuGa-KI1Ma0bpQDJiEbI1HoqZwmazBaEJYrYFbHZ3QE5Y6ndKaS5Va63PZmJ7A17vEyfPEzH6VLj-dSU4FgiFQmFfeyOZxuBGdZGwooSQrNeTNECbEAQQi8aCiZCgITxFgABSECD1KCoADcIGt1SAAEbcAaOADKhCoYH6HmQMAoujgGtoMDm+gA6rRGPB-J64K7zVHGFao-hkOBxPb+qIuDBjdQPAtkDp9NmNQArUQKABCzrdVDmcAAMv04EWqCXAyAKwpXd79HAAIq6CDwNsdjUeijZihph1UB1wfT2wgUfowMNrGC0ZAADgADBP4tmw2M0yuxFwra2NQBHYfwPNai0gKiiAC0IhCIXtDjvjAceZUAWVBjqWIDZnMjC+v6naiH2g73q2SDFmBMDzhu6hbsgABMGp+lQETegAwhAcyFigaIiPaujZgAKvOFooZ2VoBhwmiwK6YCrtqyTqK6BD9qBcASBIQA)
```sh
--parser babel
```

**Input:**
```jsx
export default () => {
  return {
    getDisplayedFilteredArrowsAndNodes: () => {
      const filteredGraph = {};
      filteredGraph.links = graph.links
        .map(({ id }, index) => getIsArrowFiltered(index) ? id : null)
        .filter((id) => id !== null);
      filteredGraph.nodes = graph.nodes
        .map(({ id }, index) => (getIsNodeFiltered(index) ? id : null))
        .filter((id) => id !== null);
      return filteredGraph;
    }
  };
};
```

**Output:**
```jsx
export default () => {
  return {
    getDisplayedFilteredArrowsAndNodes: () => {
      const filteredGraph = {};
      filteredGraph.links = graph.links
        .map(({ id }, index) => (getIsArrowFiltered(index) ? id : null))
        .filter(id => id !== null);
      filteredGraph.nodes = graph.nodes
        .map(({ id }, index) => ((getIsNodeFiltered(index) ? id : null)))
        .filter(id => id !== null);
      return filteredGraph;
    }
  };
};

```

Notice the redundant parens put around the .map arrow function.  On the first pass it adds one set, on the second it adds another.  The second set is obviously redundant, but both are redundant in my opinion.

**Expected behavior:**

It should never put parens around existing parens.

**Comment by thorn0** [comment]
> Prettier 1.19.1

Does the Playground really has v1.19.1 for you? 😮 Please hard-refresh it (ctrl-shift-r) in this case. It might be cache. 1.19.1 was released in 2019.

Anyway, I've tested your input with 1.19.1, and with other versions. Neither produces the output that you show. How exactly did you get this output?

As for the redundancy of the parens, it's intended see #1379.
