### ISSUE TITLE
Prettier removes '\' in string literals

### ISSUE THREAD

**Issue by JaegerJens** [prettier/prettier#10303]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzTBeTAHREMIApiBuEAGhAgAcYBLdZUAQwCcuIB3AArcEaZCA4AbPhwCeougCMuHMAGs4MAMoMVzKAHNkMLgFc4dOAFsFcACa27AGQ4GTHfXABiELpY4wWAzEOExgIWhAACxhLCQB1SOZ4NB0wOE0RJOYANySZMTA0eRA9NDguGAFlfT9kbEkyugArNAAPACFlNQ1NDks4Rz04OobzEBbWzT19CTgARRMIeBGJRpAdLjKuMQUOGwkIhi49GDjmWxhI5AAOAAY6I4gyuOUGMSO4LezhugBHRfgVUYohQHDQAFooHA7HYIlw4P9mPCqu5akh6qsxmVLMwjKYsdNZgslsN0aM6DA9mcLlckAAmCnKZgSaYAYQgljRIE+AFYIiYygAVPYgjFrbJmACSUAcsE0YGOTAAgjLNDAZLMVmUAL7aoA)
```sh
--parser babel
```

**Input:**
```jsx
const f = "\(";
```

**Output:**
```jsx
const f = "(";

```

**Expected behavior:**
do not modify content of string literals

**Comment by thorn0** [comment]
`'\('` is equivalent to `'('` in JS. If you want a literal \ in your code, you have to use `\\`. Is this change causing issues somehow?

**Comment by JaegerJens** [comment]
Thanks for the feedback.

My problem was before running prettier, because something replaced `\\` with `\` and then prettier removed the last `\`.
