### ISSUE TITLE
Markdown code-block with wrong language yields garbage

### ISSUE THREAD

**Issue by Izhaki** [prettier/prettier#10333]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAztAOlABwEMwBrIgczi11xgAs4BaegVwCNawBPAgJ2o1cAMwCWADxisBQin1EATAMLQxFaURijoAOmx4o6VPhAAaEBAJboWZKCJ8+EAO4AFBwlsoiAG2dFuW3N2PhJSOBgAZWIwUSgKZBg+VjhzOABbdjgFBWyAGSJ41ko4ADEIPnTNLXjkECJWGAgzEHoYdJ8AdXpReCwYuEjPXtEAN17uOrAsIJA4rDg+GFdQiirkYV8F82xxACFQsgjIonS4PLi4Da3UkF3IuIofOABFVgh4a59tkGI+Bb4dSqfFIChcUBa-DiME6igYyAAHAAGcz8CALTqhAh1fjURajK7mACO73gK0sXnqWCYUDg2WyLQEJNEAhWlHWSE231uC3SokSyR5j2ebw+V05N3MMCI7FhCnhSAATFLQqIfI8VOkOSBqABWFqsBYAFRlXi5P1GKQAklBcrBImB5FYAIK2yIwbjPL4LAC+PqAA)

**Input:**

Markdown document with:
<pre>
```json
packages\the-hub\cypress\fixtures\gridConfiguration.json
```
</pre>

**Output:**

<pre>
```json
packagespackages\the -
  hubhub\cypresshub\cypress\fixtureshub\cypress\fixtures\gridConfiguration.json
```
</pre>

**Expected behavior:**

If the content cannot be parsed as the requested language, throw.

**Comment by thorn0** [comment]
> If the content cannot be parsed as the requested language, throw.

I'd caution against relying on such expectations. Prettier guarantees (well, strives to guarantee) only that correct code stays correct. It makes no promises about invalid code. That's why handling this case better would be an enhancement, not a fix.

**Comment by Izhaki** [comment]
Awesome! Thanks @fisker !
