### ISSUE TITLE
Wrong formatting when arguments of function are string and callback function

### ISSUE THREAD

**Issue by yurakis** [prettier/prettier#10331]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMAUByAMhAJzgFsACASwAc0BXMgEwgBtDS1yZSBDYuGAGlKQoaOGHgwaBbvSrl2YclADmpOEw4A6UgEEwYGmi6xydQQEcaENIIBucAhy4x5AQlIBROmvtRyfUgALcjBSGAgYHk1sQUwASlIAXgA+UmAAXziAbgAdKBB+EAhKF2g0ZFAuAgIIAHcABSqEcpQuJlquAE9ywoAjAi4wAGs+AGVKQaVlZBgCGjhCkl64enoV3GNlGi5lOAAxQmJnFxVkEC4acIKQQJhiJgB1YPQJsDhR5o5yWw5Os7A0D0QEpRAQYPUBsojsgAGZtUSFABWaAAHgAhAbDMY8OC4JRwWHwhYgZEo0ZTJhwACKVnghKYCJAEwIoLOvS4yyY10ojlgD3I9BggWQAA4AAyFHnWOAPAaUM48uCg+zXSwROAQ4otc5oAC0UDgKxW1yIlnIRAhO2hSDhDOJomI5Bmc3tFOptIJSFm80KkV6-MFwqQACZfQNyBoVABhCDEa3nJhcwqGOAAFQ5LVtjNs8wAklA1rBRmBHCUdAXRjBOpT6aJ0ukgA)
```sh
--parser babel
--single-quote
--trailing-comma all
```

**Input:**
```jsx
test('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, quos, veritatis! Eum eveniet hic totam.', () => {});

```

**Output:**
```jsx
test('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, quos, veritatis! Eum eveniet hic totam.', () => {});

```

**Expected behavior:**
```jsx
test(
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, quos, veritatis! Eum eveniet hic totam.',
  () => {},
);
```

It seems it happens only when arguments are string + callback. I tried different combinations and it behaves as expected in other cases.

**Comment by alexander-akait** [comment]
@prettier/core Every week we get the same about `test`, maybe we should put some popular cases in the issues template?

**Comment by thorn0** [comment]
This is intended. See https://prettier.io/docs/en/rationale.html#testing-functions

@alexander-akait Yes, we definitely need to do something with the issue submission process. There were some discussions and good examples from other projects in https://github.com/prettier/prettier/pull/7974

**Comment by yurakis** [comment]
It works not only for `describe`, `it` and `test`. It happens in any function, but if we have lets say a number same length, arguments will be in a separate lines

**Comment by thorn0** [comment]
> It happens in any function

For the record, it doesn't. `describe`, `it`, etc. are hardcoded names that trigger this formatting.

**Comment by yurakis** [comment]
Yes, indeed. I just checked, it does not work with function with different name.
Are there any options to format such functions like any other ones?

**Comment by thorn0** [comment]
No. Why do you ask? Do you really not know that Prettier is opinionated?

**Comment by yurakis** [comment]
No. Why do you ask? Do you really think everybody should know that?
But anyway thanks for an explanation, because I am quite new to prettier.

**Comment by thorn0** [comment]
They definitely should if they use it. It's mentioned literally everywhere where Prettier is mentioned.
