### ISSUE TITLE
Comments in typescript type unions move to incorrect place

### ISSUE THREAD

**Issue by Naddiseo** [prettier/prettier#10344]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYhCbAXmwB0QBGc7AHzJACZqB6AKmxgHdDXnb6AzOQDcpKGMhQAzjDwFi9KiH7kmytlwi8VIISGEgANCAgYYAS2hTkoAIYAnexE4AFBwmspbAG06201sYARva2YADWcDAAyhhh5lAA5sgw9gCucMZwALZBcAAm+QUAMrZJabaJcPj22bYwFknIILZpMBBGIAAWMNneAOpd5vBScWBw0R7D5gBuw2jNYFKBIAlScPYwLqGJdcgAZj7rxgBWUgAeAEKhEVHRttlwxQlwB0eZIGfn0QmJ3nAARTSEHgb28xxAcXs63szXQWCkYHs5jMnQwyNg-XM+RgXWQAA4AAzGdEQdb9UIYZrouAwmavYwAR2B8G2pk8LSkAFooHACgVOvY4MzzELtpU9khDuCPutsuYUulZb9-kCQa8pe9jDBbEEsTi8UgGNrQuZvL8AMIQbKSlrebydNLrAAqus80ohMwyAEkoEVYNEkSiYABBP3RdD-MHrAC+MaAA)
```sh
--parser typescript
--trailing-comma all
```

**Input:**
```tsx
type Foo = "1" | "2" /* two */ | "3";

const Foo = "1" | "2" /*two*/ | "3";
```

**Output:**
```tsx
type Foo = "1" | "2" | /* two */ "3";

const Foo = "1" | "2" /*two*/ | "3";

```

**Expected behavior:**
The comment should stay on the correct side of the `|` (like it does with `const`):
```tsx
type Foo = "1" | "2" /* two */ | "3";

const Foo = "1" | "2" /*two*/ | "3";

```

**Comment by prabhuHalodoc** [comment]
@thorn0 I am working on this issue.

**Comment by thorn0** [comment]
@prabhuHalodoc Sorry, this has been fixed by the Babel team. Now that we updated the Babel parser, we can remove workarounds that caused this bug. See #10457 for more details.

**Comment by prabhuHalodoc** [comment]
Thank you @thorn0 for the update.
