### ISSUE TITLE
suboptimal formatting with nested async function calls and type assertions

### ISSUE THREAD

**Issue by dcermak** [prettier/prettier#10340]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBzOMCCYkArrAMISlYC8mAhmgJ5RiYAUAlJtQHwA6UTOzoB3OgEssAoULZtRErG2kyhCyZgBmEMMTQB5KAGU4YGOOhsAQvv0BpALL4ASnYCiAEQD6ABWf6AKTcyABUjLyNgkIBJfQA5Lzj8BzcOFSEOADpNcSgAE2j4AFtlEAdGTAAjCAgAayK6ACdatD4QDi4GTBDGuDhCuCKVLNwYMgALcQAbPN6oTmHMqYRsGHGBEAAaEAgAB3N0ZFAmxogRHyaENGQQOimxRmvtysa6MFq8I1233OxkGEaxDg20GlTgeTy4IAMnQoNhiHRcAAxCCNBowcxwm50YgwCBbEDjGBFKYAdUm8DQ3zAcBMUDQknEADdJIwbmA0E8QLk0HBGjAfK9sA1kJo7rztgArNAADysr3enzoRTgUNycFF4uBIGlMqMv2WAEViBB4JqphKQN9GrzGjcYIxdnA0GBGuJ9gTdm7YKTxHk1sgABwABm2XogvNJr12Ny9zr5TI12wAjib4IK9tcUAwALRQPqQvIE3qp8S9QWIkVIMUW7W8orif6AusGuDG00a6ta7YwOiVX3+8bIABMPde01+FCKVZAzoArAS9HAQn2szXLUygdF8ggYEZXe6CPkjA7lubeQBfC9AA)
```sh
--parser typescript
```

**Input:**
```tsx
const getAccountCount = async () =>
  (await 
    ((await (
      await focusOnSection(BOOKMARKED_PROJECTS_SECTION_NAME)
    ).findItem("My bookmarks")) as TreeItem
  ).getChildren()
  ).length

```

**Output:**
```tsx
const getAccountCount = async () =>
  (
    await ((await (
      await focusOnSection(BOOKMARKED_PROJECTS_SECTION_NAME)
    ).findItem("My bookmarks")) as TreeItem).getChildren()
  ).length;

```

**Expected behavior:**

I would expect something more akin to the input, albeit I don't really like that one either. However, I find the output of prettier a bit worse, because it puts two awaits on a single line and that makes it harder to read imho.

**Comment by thorn0** [comment]
I guess this output would be good enough:
```ts
const getAccountCount = async () =>
  ( 
    await (
      (await (
        await focusOnSection(BOOKMARKED_PROJECTS_SECTION_NAME)
      ).findItem("My bookmarks")) as TreeItem
    ).getChildren()
  ).length
```
Prettier is already almost there. Here's what I got when I removed `as TreeItem`:
```js
const getAccountCount = async () =>
  (
    await (
      await (
        await focusOnSection(BOOKMARKED_PROJECTS_SECTION_NAME)
      ).findItem("My bookmarks")
    ).getChildren()
  ).length;
```
Looks like `as` is the culprit.

**Comment by dcermak** [comment]
Georgii Dolzhykov <notifications@github.com> writes:

> I guess this output would be good enough:
> ```ts
> const getAccountCount = async () =>
>   ( 
>     await (
>       (await (
>         await focusOnSection(BOOKMARKED_PROJECTS_SECTION_NAME)
>       ).findItem("My bookmarks")) as TreeItem
>     ).getChildren()
>   ).length
> ```
> Prettier is already almost there. Here's what I got when I removed `as TreeItem`:
> ```js
> const getAccountCount = async () =>
>   (
>     await (
>       await (
>         await focusOnSection(BOOKMARKED_PROJECTS_SECTION_NAME)
>       ).findItem("My bookmarks")
>     ).getChildren()
>   ).length;
> ```
> Looks like `as` is the culprit.

Indeed, that is much better!

**Comment by thorn0** [comment]
The output for the code without `as` looked that good because I decreased `printWidth` to 77. With 80, it looks worse:
```js
const getAccountCount = async () =>
  (
    await (
      await (await focusOnSection(BOOKMARKED_PROJECTS_SECTION_NAME)).findItem(
        "My bookmarks"
      )
    ).getChildren()
  ).length;
```
Turns out `as` isn't the only problem.
