### ISSUE TITLE
Regression: Comma incorrectly added to last generic type parameter in TypeScript

### ISSUE THREAD

**Issue by bwbuchanan** [prettier/prettier#10351]
**Prettier f858f5519fb07806ad60c8e8a29763c003c9588c **

This is a regression of #1820.

```sh
# Options (if any):
--print-width 40 --trailing-comma all
```

**Input:**

```typescript
type GenericType<A, B, C, D, E> = number;

export function abc(arg: GenericType<number, number, number, number, number>) {}
```

**Output:**

```typescript
type GenericType<A, B, C, D, E> =
  number;

export function abc(
  arg: GenericType<
    number,
    number,
    number,
    number,
    number,
  >,
) {}
```

**Expected behavior:**

The final type parameter should not have a trailing comma. Otherwise, the TypeScript compiler (4.1.3) reports error `ts(1009)`.

**Comment by thorn0** [comment]
Related issue in the TS repo: https://github.com/microsoft/TypeScript/issues/21984
