### ISSUE TITLE
Separate character limit for JSX and other code

### ISSUE THREAD

**Issue by sarimarton** [prettier/prettier#10350]
Hi,

This is a feature request to make JSX code have different (higher) print width setting than regular code.

This request comes on top of a simple realization that JSX (XML) ultimately differs in nature of horizontal scaling and by experience one can soon tell that the same 80 character limit which works great for code, is not optimal for JSX, especially for, but not limited to, the world of CSS utility classes.

My proposal is tentative in regards of whether this feature is represented by an extra option applied to JSX only, like `print-width-jsx`, or is applied with an opinionated, automatic multiplier on the regular print-width setting. For example, if print-width is set to 80, JSX lines could automatically extend to 80 + 80/4 = 100 characters on a line.

I think there is a clear benefit in this trade-off of contextually deviating from the set character limit in case of JSX.

**Comment by thorn0** [comment]
> I think there is a clear benefit

Please show some code examples to demonstrate that benefit. It's unclear what you hope to achieve.
