### ISSUE TITLE
Formatting of Reduce, Other FP Functions.

### ISSUE THREAD

**Issue by jacobp100** [prettier/prettier#1035]
When formatting longer functions within arguments, prettier tends to put each argument on a new line.

```js
array.reduce((accum, value) => {
  accum[value] = value;
  return accum;
}, {});

// to
array.reduce(
  (accum, value) => {
    accum[value] = value;
    return accum;
  },
  {}
);
```

I'm not sure if this is intended, but at least [AirBnb's JavaScript guide gives special formatting in these cases](https://github.com/airbnb/javascript#arrows--one-arg-parens).

```js
array.reduce((accum, value) => accum + value, 0);

array.reduce((accum, value) => (
  reallyLongFunctionNameThatMeansItWontAllFitOnOneLine(accum, value)
), {});

array.reduce((accum, value) => {
  accum[value] = value;
  return accum;
}, {});
```

Also worth noting that sometimes the function isn't the first parameter, but would still have this formatting.

```js
_.reduce(array, (accum, value) => (
  reallyLongFunctionNameThatMeansItWontAllFitOnOneLine(accum, value)
), {});
```

I tried hard to find existing issues for this, and didn't find any. Sorry if there was already one!

Is this something we'd want in prettier?

**Comment by vjeux** [comment]
@Royce is fixing the first use case in https://github.com/prettier/prettier/pull/947 (can you make sure empty objects as second argument is not consider to expand)

For the second one, I don't think that we should support it. Because prettier works on the ast level, we don't know if you are using reduce or not and I don't think that we should automatically expand functions in the middle, it would be really weird in a lot of cases.

**Comment by jacobp100** [comment]
> I don't think that we should automatically expand functions in the middle, it would be really weird in a lot of cases.

Really? I think I would expect this in almost all cases. What's an example where you wouldn't?

**Comment by Royce** [comment]
@jacobp100  #947 (merged) allows:

```js
array.reduce((accum, value) => {
  accum[value] = value;
  return accum;
}, {});
```

So that's part way there!

**Comment by jacobp100** [comment]
Would be interesting to see how people format these things! For the last example, I would normally,

```js
func(() => {
  thing();
}, {
  yes: true,
  cats: 5
});
```

**Comment by vjeux** [comment]
The initial suggestion has now been implemented and we're not going to implement the others, so I'm going to close this issue.
