### ISSUE TITLE
[Q] How to ignore certain file types in CLI file patterns?

### ISSUE THREAD

**Issue by wenfangdu** [prettier/prettier#10366]
I want to exclude only `js`, `jsx`, and `vue` files, I imagine something like:
```bash
prettier --check --write --ignore-unknown "**/*.{!js,jsx,vue}"
```

**Comment by lydell** [comment]
It doesn’t answer your question, but I would suggest using a [.prettierignore](https://prettier.io/docs/en/ignore.html#ignoring-files-prettierignore) file instead.

**Comment by wenfangdu** [comment]
@lydell Hello, unfortunately, that's not a viable option, I'm using prettier like:
```bash
vue-cli-service lint . && prettier --check --write --ignore-unknown "**/*"
``` 
By which, `vue-cli-service lint` will auto prettify `js`, `jsx, and `vue` files, and I don't want prettier to prettify them again.

By adding a `.prettierignore`, I will lose the prettier formatting when writing.

So, I guess achieving this in the file pattern is impossible?

**Comment by wenfangdu** [comment]
Thanks to @thorn0, the answer is `prettier --check --write --ignore-unknown "**/*.!(js|jsx|vue)"`
