### ISSUE TITLE
Flow function declaration being inlined

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1037]
From https://github.com/prettier/prettier/issues/1007#issuecomment-287221945 by @bvaughn

"Noticed a related issue for Flow types when running prettier on some changes made to the React repo.

```js
type Foo = {
  bar(
    baz: number, // I belong with baz
    qux: string /* I belong with qux */
  ) : void
}
```
...gets converted to...
```js
type Foo = {
  bar /* I belong with qux */(baz: number, qux: string): void // I belong with baz
};
```

Online repro [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Foo%20%3D%20%7B%5Cn%20%20bar(%5Cn%20%20%20%20baz%3A%20number%2C%20%2F%2F%20I%20belong%20with%20baz%5Cn%20%20%20%20qux%3A%20string%20%2F*%20I%20belong%20with%20qux%20*%2F%5Cn%20%20)%20%3A%20void%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)."

**Comment by vjeux** [comment]
Here's the fix. You found a super subtle bug! Great catch.  https://github.com/prettier/prettier/pull/1038

**Comment by bvaughn** [comment]
Yay! Lucky me 😆
Thanks! ❤️
