### ISSUE TITLE
please help to maintain `stylelint-prettier`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#10409]
No really an issue of `prettier` core itself, sorry.

I've been suffered from https://github.com/prettier/stylelint-prettier/issues/25, and raised a PR https://github.com/prettier/stylelint-prettier/pull/156 to fix it, but the current maintainer @BPScott haven't reviewed and released it.

So I'm here to ask for help from the core maintainers.

**Comment by BPScott** [comment]
It's been a week. I've got a day job. I'll try and get to looking at it this weekend.
