### ISSUE TITLE
prettier-ignore comment doesn't apply if on end of line

### ISSUE THREAD

**Issue by pushkine** [prettier/prettier#10408]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzuuAnGAKAQgLAFdtsEYAVOdGAGgAIADAHRAGIBRADwAc4YeABN2jAEYAbCGADW6RgFsSdCXEZ8KYOHGG6JAT0YwAFnACW2Ruah8SMZgEoA3IwD0bzXBgxzOALTmAOZQEBSsUBhYuHik5JQAylDmfAIwjAQAvJmMcRSwNHQAdBD2dgwsMADuEIzs3PyCImJSMvKMemCSqBTC1lCMqIzYEFVOziD0IBB8vtDoyKA9I1UACj0ICyioklWoBgtT4tioct4JfKc2Qcgw2CRwU3CK4rp6wgAyqFBBJKhBcAAYmFFKgfNdkGh7BBJiATDBFJIAOomczwdCXbQJTZo8wANzRBkhYEwsJs0RgqxOQVByAAZjssFMAFboHgAIROZxgCVQijgHxscHpjMeIFZPAS10kcAAiiQIPARZImSBLthopDxKhXpJYZobDAkeZhKZkAAOAAMU00ECwSJOfEhXmieOFUwAjgr4FSZls0Oh-FAdO9YRQvZY4FT-rSkAyVWKsIpzLd7onpXLvcK46KpjAdcbTSZkAAmPMncySa4AYQgiljIFoAFZYSo4FQdVt46q8Q8AJJQPSwBJgbApGAAQUHCRgBhlyqwAF9F0A)
```sh
--parser babel
```

**Input:**
```jsx
assert(!!currentTest, `"#Expected" blocks must be preceeded by their input`); //prettier-ignore
assert(currentSnippet !== currentTest.output, `two "#Expected" blocks declared in a row`);
```

**Output:**
```jsx
assert(!!currentTest, `"#Expected" blocks must be preceeded by their input`); //prettier-ignore
assert(
  currentSnippet !== currentTest.output,
  `two "#Expected" blocks declared in a row`
);

```

**Expected behavior:**

```jsx
assert(!!currentTest, `"#Expected" blocks must be preceeded by their input`); //prettier-ignore
assert(currentSnippet !== currentTest.output, `two "#Expected" blocks declared in a row`);
```

Expected behavior comes from `// @ts-ignore` which in this case would ignore the next line

**Comment by thorn0** [comment]
Works as intended. It's applied on the AST node level. In this case it's a trailing comment of the first statement, so Prettier prints that statement with the original formatting.

This approach is more flexible and less fragile than the behavior of `ts-*` comments, which operate on the line level. If Prettier's ignore comments worked that way, it wouldn't be possible to use them like this (the example from the docs):
```
// prettier-ignore
matrix(
  1, 0, 0,
  0, 1, 0,
  0, 0, 1
)
```

See also https://prettier.io/docs/en/rationale.html#comments
