### ISSUE TITLE
Glimmer: Double quotes removed even if single quotes inside

### ISSUE THREAD

**Issue by bmaehr** [prettier/prettier#10419]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIaYwA2cAvADojDAy4DkREA5plAHQCuAznAE5QBDALZw26OFzC9MABwLQ6AX0WVcAiiEoB6AHwgANCAhzM0LslADevCAHcAClYTmUAorYEBPc4YBGvATAAazgYAGUZQNYmZBheDjhDOCFfOHRxdAAZASgmDgEmOAAxCF4hARgCXOQQAQ4YCAMQAAsYISIAdWbCCUiwODDnQhxCTxqwLh8QVh5eGHsApnLkADM3HkMAKy4ADwAhAODQsOE4TNY4VfXEkG2dsOiSAEUOCHgrog2QSN5ZmqYiJghCJeE0ZNJYB1MOgYM1kAAOAAMhnBEB4HQCMhq4IkfGwl0MAEdXvAFsYXLUuABaKBwNJpJq8ODEzBMhYFZZINafG48ISYWLxXmPOAvN6XJBxBKGGACXxQmFwpAAJhlAUwgNyAGEIMCBDUJABWJrcOAAFTlLm5X2wCQAklBxLAwlJZDAAIKOsIwTwkD48ZRAA)

```sh
# Options (if any):
--single-quote
--parser=glimmer
```

**Input:**

```jsx
<div title="{{t 'login.username.description'}}" />
```

**Output:**

```jsx
<div title='{{t 'login.username.description'}}'></div>
```

**Expected behavior:**

Behavior like parser=html

```jsx
<div title="{{t 'login.username.description'}}" />
```

Even if the output can be parsed by glimmer it is not readable with only the single quotes.

**Comment by nraju99** [comment]
Hi! I would like to make this contribution!

**Comment by dcyriller** [comment]
@nraju99 you have test cases already [in this file](https://github.com/prettier/prettier/blob/2.3.0/tests/format/handlebars/single-quote-option/attributes.hbs#L9-L12)

The code to adjust to get this issue fixed is probably here:
https://github.com/prettier/prettier/blob/2afc3b9ae674ede93489b55ab3f90ba2bcdd27c5/src/language-handlebars/printer-glimmer.js#L156-L166

**Comment by Alonski** [comment]
@nraju99 Want to try fixing this please? :)

**Comment by bmaehr** [comment]
@dcyriller is right, this statement is the problem. 

More exact: The problem is that 
```
node.value.parts 
         .filter((part) => part.type === "TextNode") 
         .map((part) => part.chars) 
         .join("") 
```
is not containing any text from inside the `{{}}`. For the example above this is returning an empty string.

Has anybody an idea how to get the whole text including text inside `{{}}`?

**Comment by bmaehr** [comment]
https://github.com/prettier/prettier/pull/11524
