### ISSUE TITLE
Babel turn invalid code to valid code

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#10412]
Found in #10410, `espree` also not handle this code well https://github.com/eslint/espree/issues/470

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAhgAgLyYEYCUOmAjCADQgQAOMAltAM7KjoBObEA7gArsLMU6ADZd0AT2aU8bdGADWcGAGVqculADmyGGwCucSnAC2eOABNzFgDLote9JrgAxCG2PoY9LchDo9MBAUIAAWMMbCAOohdPCMamBwygKxdABuseK+YIxSIBqMcGwwPLKaHsgAZiKFlABWjAAeAEKyCkrK6MZw1hpwVTWGIA2NyhqawnAAinoQ8APCtSBqbIVsvnjoZsLB1GwaMJF05jAhyAAcAAyUexCFkbLUvntwa2n9lACOs-ClNIJ+RgAWigcAsFmCbDg3zoUNKjgqSGqiyGhWMdB0+lR40mMzm-SRg0oMC2RxOZyQACZibI6MJxgBhCDGREgV4AVmCekKABUtoJkUs0gYAJJQKywZRgfa0ACC4uUMHEkwWhQAvmqgA)

```sh
--parser babel
```

**Input:**

```jsx
(a = b) = 1
```

**Output:**

```jsx
a = b = 1;

```

**Expected behavior:**

Should throw SyntaxError.

**Comment by fisker** [comment]
Sorry, fixed code still invalid.

**Comment by thorn0** [comment]
What about `(a = b) =1` then?

**Comment by fisker** [comment]
Nice catch, we should throw an error on this.
