### ISSUE TITLE
Glimmer: New line at end of file is removed

### ISSUE THREAD

**Issue by bmaehr** [prettier/prettier#10420]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeARgJwAQHoB8AOlCADQgQAOMAltAM7KgCGmmEA7gAqsKMrMANh2YBPRuSzMwAazgwAypWk0oAc2QxMAVzjk4AW3RwAJidMAZZuu3M1cAGIRMB5jFrrkIZtpgQyIAAWMAaCAOqBNPD0ymBwCnxRNABuUaJeYPQSIKr0cJgwXJh2rpo6eiAAVvQAHgBCxbLyCswGcBaqcGW65NU1CqpqgnAAitoQ8N0Vyph5mF5DNAZt8+SUmKowYTQmMIHIAEwADEdr7HlhxZReUHDJ+QEAjuPwRVT84Aw09PCI5JhwZ40AFFErMKbkPIGGgQkD0QbDMYTLpILQ9EAwZjoba7fZIA7kLTMGiCQYAYQgy3BAkEggC2jyABUsfwAGZCPLkZK6ACSUHMsAUYA21AAgvyFDBRMNkOzBHkAL4KoA)

```sh
# Options (if any):
--parser=glimmer
```

**Input:**

```jsx
<br />(\n)

```

**Output:**

```jsx
<br />
```

**Expected behavior:**

Behavior like parser=html

```jsx
<br />(\n)
```

**Comment by thorn0** [comment]
I agree that this is confusing but this is intended. See https://github.com/prettier/prettier/pull/6243

If the Glimmer team changes their mind on this, Prettier will change this too.
