### ISSUE TITLE
printers not invoked for json/json-stringify

### ISSUE THREAD

**Issue by unional** [prettier/prettier#10423]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: API, during developing plugin
- Runtime: NodeJS v14.9.0
- Operating System: Windows

**Steps to reproduce:**

I have the repro in this branch:
https://github.com/unional/prettier-plugin-tidy-json/tree/printer-not-invoked

run `yarn watch` and you will see the `console.log()` in the printers is not being invoked

In short, I have:

```js
export const printers = {
  json: {
    print() { console.log('called') }
  }
}
```
but it is not being called when used.

**Expected behavior:**

Calling the `print()` function in the plugin's printers export for `json` and/or `json-stringify`

**Actual behavior:**

not being called

btw, I tried to find out what's the difference between `json` and `json-stringify` parsing but can't find information about that.
If you know, can you also describe what's the difference between the two?
Thanks. 🌷

**Comment by thorn0** [comment]
Re `json-stringify`: see https://prettier.io/blog/2018/05/27/1.13.0.html#added-json-stringify-parser-for-jsonstringify-style-formatting-4450-by-ikatyang
Re plugin API: see https://prettier.io/docs/en/plugins.html#printers In particular this part: "The key must match the `astFormat` that the parser produces."

**Comment by unional** [comment]
I see. thanks. I just tried that but still doesn't work for some reason.

I have changed it to:
```js
export const parsers = {
  "json" : {
    ...parser, // astFormat: "estree-json"
  }
}

export const printers = {
  "estree-json": {
    print() { console.log('called') }
  }
}
```

But it is still not called.

**Comment by thorn0** [comment]
The plugin API is for adding parsers/printers, not for patching existing ones. There are hacky ways to do that, but that is not officially supported and can break in any release. See https://github.com/prettier/prettier/issues/10259

**Comment by unional** [comment]
Thanks. Yeah, I'm not look for monkey patching existing parser/printer.
I'm planning to provide a different one so that the consumer can specify it in their prettier config.
Seems like that's is not a use-case that prettier supports?

**Comment by thorn0** [comment]
> Thanks. Yeah, I'm not look for monkey patching existing parser/printer.

Your posts kind of show the opposite. You use the names of the built-in parsers and printers.

> I'm planning to provide a different one so that the consumer can specify it in their prettier config.
> Seems like that's is not a use-case that prettier supports?

What exactly do you think isn't supported? Example: you create a plugin with a parser called `"my-lang-parser"` with the `astFormat`  property set to `"my-lang-ast"`, so the printer in this plugin should be named `"my-lang-ast"`. Then the user of the plugin can use `parser: "my-lang-parser"` in [configuration overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides) to associate the new parser with files. Or the plugin can define "languages" to make the association automatic. That's how the Plugin API should be used. This is described in the docs I linked to above.

**Comment by unional** [comment]
> Your posts kind of show the opposite. You use the names of the built-in parsers and printers.

I was trying out to see how the system works, and also I thought doing `printers = { "estree-json": { ... } }` I'm replacing the printer handling of the process, not monkey patching.

By monkey patching I mean something like this:

```js
const existingPrinter = require('...')
export const printers = {
  "estree-json": {
    ...existingPrinter,
    print() { /* do something else */ }
  }
}
```

i.e. changing part of the printer instead of replacing it entirely.

> What exactly do you think isn't supported?
Sorry, I missed out some explanation.
I assume that is not a use-case because `prettier` is opinionated and also form this comment: https://github.com/prettier/prettier/issues/4424#issuecomment-408489742

So I assume since a particular language (`json` in this case) is already supported, plugin should not be created for that language thus diverging the community. 🌷 

Thanks for your example. It makes clear that it is possible and supported.

**Comment by thorn0** [comment]
> plugin should not be created

It's not really the case, and I didn't write that. Prettier itself bundles multiple alternative parsers for the same languages (e.g. `typescript` and `babel-ts`) and alternative printers for the same languages (the parsers `json` and `json-stringify` use the same underlying parser, but have different values in the `astFormat` property, which corresponds to different printers).
