### ISSUE TITLE
feature-request: reading Git's Config for changing CRLF to LF on windows

### ISSUE THREAD

**Issue by naveen521kk** [prettier/prettier#10421]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI
- Runtime: Node v12.18.4
- Operating System: Windows

**Steps to reproduce:**
- Save a file in CRLF format.
- Then initialise a git repository, `git init`
- Commit that file. `git add . && git commit`
- Run
  ```sh
  prettier --write .
  ```
- Run `git status`, you will see that there are no changes in there but git showing the file is changed because of line ending.

**Expected behaviour:**
Prettier could read git config to check whether to convert to CRLF to LF or not. That can be done by 
```sh
$ git config core.autocrlf
true
```
if it is true, regardless of line ending it will change it to CRLF while committing and this causes unintended things in `git status`.

**Actual behavior:**
Doesn't look for git config.

**Comment by thorn0** [comment]
Thanks for the proposal. Isn't `autocrlf` a legacy feature of Git from the time when text editors on Windows didn't support LF-only line breaks? In general, Prettier [recommends](https://prettier.io/docs/en/options.html#end-of-line) using its default setting - LF-only line endings - on all platforms. Today all the major editors, IDEs, tools work with LF without any problem on Windows, so why use `autocrlf`? Why put efforts into support of outdated workflows?

Besides, Git configuration isn't that simple. There are also `gitattributes` files that allow overriding the settings using globs, so should Prettier understand them too? Looks too complex for little gain.

**Comment by naveen521kk** [comment]
I would simply say looking for repo config for the autocrlf should be fine.
All of this happened or annoyed me when I run prettier on a project and `git status` showed me that all the files have been changed. So, for me just checking the local autocrlf setting should be fine and ignore the `gitattributes`(people who set that should be knowing that it is gonna happen.).

> Today all the major editors, IDEs, tools work with LF without any problem on Windows, so why use autocrlf?

I think it is enabled by default on Windows no?

**Comment by thorn0** [comment]
> I think it is enabled by default on Windows no?

Not really, but kind of. Git itself has always had `false` as the default value. But the installer on Windows makes the user choose the value and, unfortunately, has `true` preselected in the dropdown. Also note that the installer configures this in the system-level config. Repo level configs don't have this setting set on `git init` (as far as I know, maybe I'm mistaken and this happens is some conditions).

**Comment by naveen521kk** [comment]
> Repo level configs don't have this setting set on git init (as far as I know, maybe I'm mistaken and this happens is some conditions).

I just tried `git init` and then `git config core.autocrlf` which gave `true` to me
```sh
$ git init
Initialized empty Git repository in H:/pretchk/.git/
$ git config core.autocrlf
true
```

**Comment by thorn0** [comment]
It's an inherited value from your system-level config, isn't it?

**Comment by naveen521kk** [comment]
Yeah I think it is
tried 
```sh
$ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
```

**Comment by thorn0** [comment]
Are there examples of other tools taking this Git setting into account? I think I've never seen any.

**Comment by naveen521kk** [comment]
No, I haven't seen any. I mostly use [black](https://black.readthedocs.io)(I mostly use python), but it just follows whatever is the previous line encoding, doesn't convert it.

**Comment by thorn0** [comment]
Closing as wontfix. Motivation:

* Other tools don't do this, so this behavior would be unconventional and surprising. Also this means that it's an untested approach. Who knows what pitfalls it might have? Let's better not learn the hard way.
* This goes against Prettier's recommended way ([docs]) of handling line endings, which is:
  * don't use `autocrlf`
  * always use only LFs
  * enforce that in `.gitattributes`

>  black ... follows whatever is the previous line encoding, doesn't convert it

This corresponds to `"endOfLine": "auto"` in Prettier. If for some reason, it's required that the contributors of a project should rely on `autocrlf`, that's how Prettier should be configured in that project.

[docs]: https://prettier.io/docs/en/options.html#end-of-line
