### ISSUE TITLE
Formatting issue when using a function called 'define' (no AMD/RequireJS)

### ISSUE THREAD

**Issue by mcjazzyfunky** [prettier/prettier#10422]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwBM4AzVKOfAX3zJwnXwB0QBnJuAWgBtUARjgCGOAJ5sA3CygzIUdgU7o4ANVGphA3tQC8JcpTgAKGflYcu+RTkoBzfP3gjebADRn8wqBBgALOBx1Wy0dDyhzMTgYAEEff0DgzW04GQBKSRA3EAhMGFRodmRQUUYAdwAFUQQilGFeMuExIuyhYTAAa2iAZUx2+2QYHABXOGy4dAE4YlJiABlvO2HhOzgAMVx0YRh8qDtkEGFhmAgskD8YdF4AdT9UeHY+sDhumvvUADd7sQOwdha0ApAjAKiI7FtkGR6uwxiAAFbsAAeACERJ0esIVHMjJDobCEYjuvYdABFYa+OC43gw7J9HAwnAHARaOC8M6YWywa6oYj+ZAADgADLTGDDriJMAcOXAGR9KdkAI7k+Cg3K1Q7sbhUabTM44OBK1D60ErCFIKHU2Ew9CoQYjK3EuBkilUmkgGBabm8vzIABM2SGwlQ-D2AGEmGaQDKAKxnYYwgAqWlqFrdH1GAEkoKRYN0wLY8nFiN0YGIdK64DQaEA)

```sh
--parser babel
```
[EDIT: Same issue with TypeScript]

**Input:**

```jsx
import { define } from "some-library";

const someVariable = define(
  "some string literal",
  anotherVariable,
  yetAnotherVariable
);
```

**Output:**

```jsx
import { define } from "some-library";

const someVariable = define("some string literal", anotherVariable, yetAnotherVariable);

```

**Expected behavior:**
Should format like in the input snippet above (while width in "Output" is more than 80 chars, which seems to be a bug).

**Remarks**
I know that Prettier treats functions that are called `define` in a special way (because of the AMD/RequireJS `define` function) and I also know that I could use `// prettier-ignore` (which would be quite sad if this was the only solution).

**Comment by thorn0** [comment]
We need to improve the detection of AMD `define`.
