### ISSUE TITLE
Markdown secondary list line-wrapping behavior is confusing

### ISSUE THREAD

**Issue by kkocdko** [prettier/prettier#10463]
This:

```markdown
Test

- List
  - Secondary
```

Is compliant and not be changed. But if I **add some content, the line-wrapping behavior comes different:**

**Input:**

```markdown
Test

- List
  - Secondary

- List
  - Secondary
```

**Output:**

```markdown
Test

- List

  - Secondary

- List
  - Secondary
```

A newline inserted to first secondary list.

I don't know why this behavior, is this a feature or bug?

Test with `v2.2.1`.

**Comment by thorn0** [comment]
I don't have the full picture of this behavior of Prettier, and investigation is needed, but this issue is a duplicate.

**Comment by thorn0** [comment]
Duplicate of #8004

**Comment by kkocdko** [comment]
Sorry to disturb you, I just search "markdown line" but found nothing.
