### ISSUE TITLE
Husky v5 is not MIT

### ISSUE THREAD

**Issue by hg-pyun** [prettier/prettier#10461]
Hello. Starting with husky v5 version, they use an early access license, not an MIT license. Therefore, it is not commercially available, but caution is needed when using the Pretier Pre-Commit Hook. Wouldn't it be better to add a reminder on the https://prettier.io/docs/en/precommit.html page?

## Reference
https://dev.to/typicode/what-s-new-in-husky-5-32g5

**Comment by thorn0** [comment]
`npx mrm lint-staged`, the command recommended in Prettier's docs, installs Husky 4.x. See https://github.com/sapegin/mrm/pull/146

**Comment by hg-pyun** [comment]
@thorn0 Got it. Good.
