### ISSUE TITLE
Add option for double lines below imports

### ISSUE THREAD

**Issue by dspacejs** [prettier/prettier#10460]
I prefer having two lines below imports. Such as this:

```js
import module from "some-module";
import foo from "bar";

import baz from "./baz;


const func = () => "output";

// ...
```

But Prettier automatically removes the second line. I haven't found a way to configure this, or any related issues requesting this configuration option.

**Comment by thorn0** [comment]
https://prettier.io/docs/en/option-philosophy.html

**Comment by dspacejs** [comment]
@thorn0 at the very least, Prettier should have some plugin available that enables you to configure it as you wish. It's a very good code formatter, and I don't think developers should have to opt for something subpar just to change a few things.
