### ISSUE TITLE
Only one error is printed at a time

### ISSUE THREAD

**Issue by llimllib** [prettier/prettier#1046]
I'm working on a vim plugin for prettier, and it would be great if prettier would list all errors in an invalid file, rather than just the first.

Example:

```
$ cat test.js
funciton bananas() {};
funciton cream() {};

$ prettier test.js
test.js: SyntaxError: Unexpected token, expected ; (1:9)
> 1 | funciton bananas() {};
    |          ^
  2 | funciton cream() {};
  3 |
```

If there were a flag to give all errors, then I could give vim users a list of each error where they can quickly scan through and fix the syntax errors. As it is, I'll just display the first.

**Comment by vjeux** [comment]
I don't know if Babylon even attempts to keep parsing the file after the first error. I know that flow does but everything after the first error is basically useless. I don't think that it's a really good idea to show errors that may not be errors anymore after you fix the first one.

**Comment by llimllib** [comment]
Fair enough; I'll close this and if somebody else feels strongly they can restart discusstion :+1:
