### ISSUE TITLE
idea: more exit codes.

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#10467]
It'd be great if there were more exit codes. For example, there could be a specific exit code for errors like `No files matching the pattern were found:`.

In the case of that error, for example, one may wish to not fail the calling process, but fail only on other errors.

We can currently scan the stderr output, but it would be easier to work with certain exit codes (f.e. when using streams, the stderr may arrive in chunks, which is more difficult to handle).

**Comment by thorn0** [comment]
"more exit codes" sounds too general. The upcoming release will have `--no-error-on-unmatched-pattern` (#10058). Won't this be enough for your use case?
