### ISSUE TITLE
Prettier converts ISO-8859 file to UFT-8 corrupting accented characters

### ISSUE THREAD

**Issue by lpanebr** [prettier/prettier#10480]
**Prettier 2.2.1**

**How to reproduce the problem:**

1. Create a file `test.html` with the following content in UFT8 encoding:
```html
<html>
  <body>
    <p>        // Este arquivo teste
 é ISO-8859, mas após passar pelo Prettier é convertido em UFT-8
    e os caracteres acentuados são corrompidos: áéíóúäü çÇ ãÃ etc.
</p>  </body>
         </html>
```
2. Check the file encoding:
```sh
file test.html
test.html: HTML document, UTF-8 Unicode text
```
3. Convert it to a file named `test-iso8859.html` in ISO-8859 and test the encoding:
```sh
iconv -f utf8 -t iso8859-1 test.html > test-iso8859.html

file test-iso8859.html
test-iso8859.html: HTML document, ISO-8859 text
```
4. Confirm in your editor that the content is correct:
![image](https://user-images.githubusercontent.com/129185/110245930-28909600-7f44-11eb-838d-d0f68d2b8a84.png)

5. Run Prettier and test file encoding:
```sh
npx prettier --write test-iso8859.html
test-iso8859.html 22ms

file test-iso8859.html
test-iso8859.html: HTML document, UTF-8 Unicode text
```
6. Confirm in your editor that the characters are corrupted:
![image](https://user-images.githubusercontent.com/129185/110245996-8624e280-7f44-11eb-87e8-2dfccc49d8ff.png)

**Expected behavior:**
Prettier should not change the file's encoding thus preserving special characters.

**Comment by thorn0** [comment]
Like many other JS-based tools, Prettier CLI supports only UTF-8, which is pretty much de facto standard and expected these days. It's the first issue about supporting other encodings in the history of the project. This fact says a lot. I'm going to close this as wontfix.
