### ISSUE TITLE
Write formatted output to a file using the Node.js API

### ISSUE THREAD

**Issue by ranisalt** [prettier/prettier#10498]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: Node.js API
- Runtime: v15.11.0
- Operating System: Arch Linux

**Steps to reproduce:**

```js
const filepath = path.join(__dirname, 'packages/shared/translations.json');
const data = prettier.format(JSON.stringify(sortByKey(translation)), prettier.resolveConfig.sync(filepath));
fs.writeFileSync(filepath, data);
```

**Expected behavior:**
`data` should contain the formatted contents of `JSON.stringify(sortByKey(translation))`, and `packages/shared/translations.json` should too.

**Actual behavior:**
Prettier just spills everything in the standard output, I don't know what's in `data` and the file is not even created.

I just need and equivalent of `--write` for the API. The return type of `prettier.format` is `string`, but it's not the output. [The docs for `format` are virtually nonexistent](https://prettier.io/docs/en/api.html) :disappointed:

**Comment by thorn0** [comment]
> Actual behavior:
> Prettier just spills everything in the standard output

This definitely shouldn't happen. Could you create a repository with a minimal reproduction of this behavior?

> The return type of prettier.format is string, but it's not the output

You're doing something wrong or facing a bug in that case.

> The docs for format are virtually nonexistent 😞

`(string, options) => string` What can be added to that?

**Comment by thorn0** [comment]
> Not all command line options are available as options, it would be nice to document how to trigger them (if possible)

No, it's not possible. The CLI is a separate program from the core library and is documented separately. The core options are documented on their own page.

> However, what is the point of accepting content as the first parameter and then the file name as an option? Isn't it redundant?

It's not. How should Prettier know what language your content is in and what parser should be used for it? The docs contain this sentence:

>> Set options.parser according to the language you are formatting (see the list of available parsers).

In your case, Prettier is now inferring the parser from the file extension.

What is indeed wrong in the docs is that the `options` parameter shouldn't be shown as optional. When the `parser` (or `filepath`) option isn't specified, the input is treated as JS, but this is deprecated and will change in the next major release.
