### ISSUE TITLE
Computed properties that use template literals

### ISSUE THREAD

**Issue by shaunwallace** [prettier/prettier#1049]
This is most likely a very edge case scenario but I thought it worth mentioning. The following code:

```js
  const user = {name: {[`foo
bar`]: 56}}
}
```

where the above uses a computed property on the object with the key `foo\nbar` will be rendered as follows:

```js
const user = {
  name: {
    [`foo
bar`]: 56
  }
};
```

It is definitely something that I wouldn't consider a but something to discuss how this might be handled differently. I understand that the formatting of **bar** being on a newline is due to the fact that a template literal was used but it seems as though if one wanted to access this object at that key one could do by calling `user.name["foo\nbar"]` which would return the value of 56. Would it be worthwhile to print it like:

```js
const user = { name: { [`foo\nbar`]: 56 } };
```

**Comment by vjeux** [comment]
prettier doesn't change the way you actually write a string literal. If you want the last version, you can write it directly and prettier will leave it as is:

```js
const user = { name: { [`foo\nbar`]: 56 } };
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20const%20user%20%3D%20%7Bname%3A%20%7B%5B%60foo%5Cnbar%60%5D%3A%2056%7D%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by shaunwallace** [comment]
Makes perfect sense and totally agree that you could write it with \n rather than what is shown in the example. To be honest I don't know why someone would do something like that, don't personally have a use case atm but thought I'd post to get feedback 😀
