### ISSUE TITLE
YAML: Node Anchor followed by a blank line: "Nested mappings are not allowed in compact mappings"

### ISSUE THREAD

**Issue by jdufresne** [prettier/prettier#10510]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBrOBPAjEgBAMgBM4AzAQwFcAbGAHSnt1wGcKAjdbPANzKorhZ69TgCYkjXAB4peAFTFy1OlBAAaEBAAOMAJbRmyUGQBOJiAHcACqYSGUfC2QyGNbE2TDoYAZS2fdKABzZBgTAQ04AFs2OEJiQgAZMmCKMiC4ADEIEyiyGD1g5BBKGAh1EAALGCiqAHVK3XhmfzA4Hzsm3W4mjGKwZlcQQOY4ExgrDyC85HIqUY0AK2YADwAhDy84XzIouETAuFm+BZBllZ9AoKo4AEUKCHhj+bgNfxNRk2KMXaoKrRMgRgdV0hBglWQAA4AAxvcyjOoeLTFAFwT7cI4aACOD3gk209hKzAAtFA4HE4hUTHAcbpqZN0jMkHNTqMorpQuFXiBmFcbvdHkdmSduTAyGwQWCIUhRBowmRdFQrgBhCBRJkgNEAVgqFFGABVxfYWdzuAIAJJQYiwHxgQE6ACCVp8MAwN2eowAvp6gA)

**Input:**

```yml
key1: &default

  subkey1: value1

key2:
  <<: *default
```

**Output:**

```
test.yml[error] test.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:7)
[error] > 1 | key1: &default
[error]     |       ^^^^^^^^
[error] > 2 | 
[error]     | ^
[error] > 3 |   subkey1: value1
[error]     | ^
[error] > 4 | 
[error]     | ^
[error]   5 | key2:
[error]   6 |   <<: *default
[error]   7 | 
```

**Expected behavior:**

No error. The file should be formatted.

Both Python and Ruby YAML libraries load this file with the expected results.

In my production code, the blank line exists there to separate a comment.

```yml
key1: &default

  # This key ...
  subkey1: value1

key2:
  <<: *default
```

Which actually results in a different error:

```
test.yml[error] test.yml: SyntaxError: All collection items must start at the same column (1:1)
[error] > 1 | key1: &default
[error]     | ^^^^^^^^^^^^^^
[error] > 2 | 
[error]     | ^
[error] > 3 |   # This key ...
[error]     | ^
[error] > 4 |   subkey1: value1
[error]     | ^
[error] > 5 | 
[error]     | ^
[error] > 6 | key2:
[error]     | ^
[error] > 7 |   <<: *default
[error]     | ^
[error] > 8 | 
[error]     | ^
```

**Comment by thorn0** [comment]
To confirm that this is valid YAML and the parsing errors are incorrect, please you use the [spec], not 3rd party implementations. I'm really sure about the robustness of Prettier's underlying parser: [yaml-unist-parser], which in turn uses [eemeli/yaml], but if you can prove this is indeed an error on their part, we'll open an issue in the corresponding repo.

[spec]: https://yaml.org/spec/1.2/spec.html
[yaml-unist-parser]: https://github.com/ikatyang/yaml-unist-parser
[eemeli/yaml]: https://github.com/eemeli/yaml

**Comment by jdufresne** [comment]
Yes, this is valid YAML. There is nothing in the spec suggesting blank lines between keys are invalid, even when a node anchor is involved.

I only presented other tools as example of compliant tools, not as a authority. Sorry for the confusion.

**Comment by thorn0** [comment]
Okay, thanks for the report. I'll try to find time to look into it. Meanwhile, to make things faster, you can open an issue in https://github.com/eemeli/yaml yourself.

**Comment by jdufresne** [comment]
:+1: I'll go ahead with that. Thanks for the response.

**Comment by thorn0** [comment]
Great. Let's keep the issue open though.

**Comment by jdufresne** [comment]
Upstream issue #242

**Comment by eemeli** [comment]
Yeah, this is a bug in `yaml`. There it's already fixed in its master branch, via the new lexer + parser that's a major reason for the library's ongoing v2 overhaul.

So this poses a bit of a problem, as I've got my hands full in that work, and I'd been hoping to avoid needing to do more v1 patch releases. For most users, v2 should work perfectly fine without any changes, but underneath, the CST changes completely. And as I recall, that's what @ikatyang's yaml-unist-parser uses.

Posting about this here to make sure that you have visibility into this; not sure yet about how to resolve this.

**Comment by eemeli** [comment]
I resolved the issue by releasing a patch update [`yaml@1.10.1`](https://github.com/eemeli/yaml/releases/tag/v1.10.1).

**Comment by thorn0** [comment]
Thanks @eemeli. This way we can fix it without touching yaml-unist-parser.

However, I noticed something. Is this expected?

**Prettier pr-10516**
[Playground link](https://deploy-preview-10516--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBrOBPAjEgBAMgBM4AzAQwFcAbGAHSgGJcAVACwEsBnXdDe3XJwoAjXjlwA3MlQpws9erwBMSfrgA86vACpi5ajBAAaEBAAOMdtE7JQZAE72IAdwAKDhDZTTnZDDZNhezIwdBgAZTMQ9igAc2QYe1kTOABbYThCYkIAGTI4ijJYuAAxCHtUshhLOOQQShgIYxBWGFSqAHUOeE4osDhwz3ZLCWGMOrBOAJAYzjh7GFdg2Mrkcio5kwArTgAPACFg0LgIslS4HJi4NelNkB3d8JjYqjgARQoIeBuNuBMo+xzex1DBnKjNMz2GIwDrsQgwVjIAAcAAZ-k45h1gmY6pC4ECJNcTABHT7wJbmLz1TgAWigcEymWa9jgpPYLKWRVWSHWdzmqXYCSSfxAnGerw+X2uPNuIpgZGEsPhiKQShMiTI7CozwAwhBUtyQPiAKzNChzZgKry8kUSWQASSgxFg4TAUIsAEEneEYBhXj85gBfQNAA)

**Input:**

```yaml
key1: &default
# This key
  subkey1: value1

key2:
  <<: *default
```

**Output:**

```yaml
SyntaxError: All collection items must start at the same column (1:1)
> 1 | key1: &default
    | ^^^^^^^^^^^^^^
> 2 | # This key
    | ^^^^^^^^^^
> 3 |   subkey1: value1
    | ^^^^^^^^^^
> 4 |
    | ^^^^^^^^^^
> 5 | key2:
    | ^^^^^^^^^^
> 6 |   <<: *default
    | ^^^^^^^^^^^^^^^
```

**Comment by eemeli** [comment]
No, that's not expected. Bother. But I'm pretty sure I can fix this pretty easily. You may expect a `yaml@1.10.2` shortly.

**Comment by eemeli** [comment]
Yah, it was what I thought. `yaml@1.10.2` is out with this fixed.

**Comment by jdufresne** [comment]
Thank you @eemeli  and @thorn0 for the very prompt responses and fixes! :tada: :rocket:

**Comment by thorn0** [comment]
@jdufresne You aren't going to like the resulting formatting though. As can be seen in the snapshots in the PR, the comment after the anchor doesn't stay on its own line. That'll be a separate issue.
