### ISSUE TITLE
Add man page

### ISSUE THREAD

**Issue by Yash-Singh1** [prettier/prettier#10514]
**Environments:**

- Prettier Version: n/a
- Running Prettier via: CLI
- Runtime: NodeJS
- Operating System: n/a

**Steps to reproduce:**

```text
$ man prettier
No manual entry for prettier
```

**Expected behavior:**

Some man page to appear

**Actual behavior:**

No man page

**Links:**

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#man

**Comment by thorn0** [comment]
Prettier is supposed to be installed locally in a project. See https://prettier.io/docs/en/install.html
Sure, it's possible to install it globally, but don't expect first-class support for a secondary use case.
