### ISSUE TITLE
Comments inside jsx result in invalid code

### ISSUE THREAD

**Issue by RShergold** [prettier/prettier#1052]
[See this example ](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20foo%20%3D%20(%5Cn%20%20%20%20%3Col%3E%5Cn%20%20%20%20%5Ct%3Cli%3Eone%3C%2Fli%3E%5Cn%20%20%20%20%5Ct%7B%5Ct%5Cn%20%20%20%20%5Ct%5Ct%2F%2F%20comment%5Cn%20%20%20%20%5Ct%5Ct%2F%2F%20here%5Cn%20%20%20%20%5Ct%7D%5Cn%20%20%20%20%5Ct%3Cli%3Etwo%3C%2Fli%3E%5Cn%20%20%20%20%3C%2Fol%3E%5Cn%20%20)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

Original code:

```
 foo = (
    <ol>
    	<li>one</li>
    	{	
    		// comment
    		// here
    	}
    	<li>two</li>
    </ol>
  );
```

Expected
```
 foo = (
    <ol>
    	<li>one</li>
    	{	
    		// comment
    		// here
    	}
    	<li>two</li>
    </ol>
  );
```

actual
```
 foo = (
    <ol>
    	<li>one</li>
    	{// comment
    	 // here}
    	<li>two</li>
    </ol>
  );

```

**Comment by vjeux** [comment]
Thanks for the report and so sorry about it! This is fixed in master, we'll do a new release in the next couple of days.
