### ISSUE TITLE
Function definition not being wrapped

### ISSUE THREAD

**Issue by josephsavona** [prettier/prettier#1053]
I have prettier configured to wrap at 80 characters, but the following isn't being wrapped correctly:

```js
export function genMockSubscriber<T>(partialSubscriber?: PartialSubscriber<T>): Subscriber<T> {
  ...
}
```

I would expect something like

```js
export function genMockSubscriber<T>(
  partialSubscriber?: PartialSubscriber<T>
): Subscriber<T> {
  ...
}
```

**Comment by vjeux** [comment]
It seems like it is. Can you try to figure out a repro case using the web thingy?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20function%20genMockSubscriber%3CT%3E(partialSubscriber%3F%3A%20PartialSubscriber%3CT%3E)%3A%20Subscriber%3CT%3E%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Closing since no update. @josephsavona let me know if you can repro and we can reopen
