### ISSUE TITLE
I have many formatter to select when I use vscode-extension prettier v6.2.0 with vscode 1.54 

### ISSUE THREAD

**Issue by B2D1** [prettier/prettier#10536]
**Environments:**

- Prettier Version: 2.2.1
- Operating System: macOS

**Steps to reproduce:**

**Expected behavior:**

**Actual behavior:**
![image](https://user-images.githubusercontent.com/36991862/111078044-a8af9080-852e-11eb-80c4-d927a1685b6e.png)

**Comment by thorn0** [comment]
Hi, this repository is only concerned with the core formatting tool and not the editor integrations. Unfortunately, there's not much we can do to help you in this case. I suggest you [ask this question on StackOverflow](https://stackoverflow.com/questions/ask?tags=vscode-prettier). Or if that doesn't help and you're sure you're facing a bug, submit a report on the extension's issue tracker: https://github.com/prettier/prettier-vscode
