### ISSUE TITLE
FR: I want to escape formatting SVG in html files

### ISSUE THREAD

**Issue by marwan-nwh** [prettier/prettier#10535]
I don't see any benefits from formatting SVG tags the same way other tags are formatted. So I just want SVGs to be in one line.

**Comment by thorn0** [comment]
>> Prettier is not a kitchen-sink code formatter that attempts to print your code in any way you wish.

-- from https://prettier.io/docs/en/option-philosophy.html

Please read that page to understand why fine-grained configurability is a non-goal for this project.
