### ISSUE TITLE
More configuration information

### ISSUE THREAD

**Issue by Zyst** [prettier/prettier#1054]
Heya guys, awesome tool! I'm having a bit of a problem in the sense that I haven't the slightest clue as to how to configure it, though.

Like, say I have a new project, how do I make prettier actions (I'm running through vim) grab their settings from some file?

Is there a way to plug it to use the same settings as ESLint? I saw there's quite a few extensions, including [eslint-plugin-prettier](https://github.com/not-an-aardvark/eslint-plugin-prettier) which lets prettier throw errors through eslint, but that's not really what I want. 

**To finally get around to making my point:** I would love to see README extended to cover these questions to some degree.

Is it like Babel and Eslint where if there's no local file it can go to root (`~`) and look for a file there with 'sane' default basics? 

~~I'm really sorry if this has been answered before~~ It totally (Sort of) has been, from what I've seen in:

#644 #98 #154 and #40, there's even work arounds there, so most of the problems I had above are "solved". I still would still love you guys forever if some of these questions could be answered in the README, it was quite a wild goose chase.

**Comment by vjeux** [comment]
Thanks for the issue! You can see here the proposal for configuration: https://github.com/prettier/prettier/issues/918

The idea is to put project configuration in package.json and for prettier to read it. We haven't had the time to actually implement it yet. I'm going to close this issue. If you can chime in the proposal if you have any suggestions that would be awesome!
