### ISSUE TITLE
0️⃣ Line-breaking on all JSX text

### ISSUE THREAD

**Issue by Sawtaytoes** [prettier/prettier#10552]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAJOAbPCAdQgCc8ATTAXkwAoBKGgPnoB0pMvMAeCgSwBuzDt0xsYuUnADkaTAFsAnpgGDMAd34wAFpgCGmQlggAzTPAAeWflDT8KcAHSYiOlf3nbM0RQFc8bQAHPDgjWzg0AH5MABU4a0xPKBksNDh9UjAdfQAjUJ9OBQCYfhCwwKhIp1FuHgB6NREoBg4OBKCyLEdTfRKcfEIScgoOEAAaEAgg0vRkUEzSCA0ABUyENGQQfTwNfSVNydzSfTAAazgYAGUg09sAc2QYUj84SbgFXLgKRwoAGX0UHufn09zgADEyAp9DBSkCtn0YBAJiAdDAFHg3NpIrcwHArhttEJtEotmA0IcQLZ0qQYCsTvdochenh0pMAFZoSwAIRO50uV30CjgfwizJ2bJAnMsVweoQAin4IPBxay3iBbqQaVtcnl8CigqRbDAiA5dMgAAyTQ0QdJEE5BLaGyJwUiCOAogCOSvg9OmmxQ+jQAFoqt9vijpN7+NJ6aCmUgWZL0gp+E8Xur7ECFT6PYmJeqYHlTRRzUgAEyTZ76fiVe4AYQgCgTIEiAFYUX50rE8gGk+rBK8AJJQRywK5gI0zACCo6uMCUoVV6QAviugA)

```sh
# Options (if any):
--print-width 0
```

**Input:**

```jsx
const HelloWorld = () => (
    <div>
    	Here's my div with a lot of text inside. Why is it on multiple lines? Text isn't searchable on multiple lines.
    </div>
)

export default HelloWorld
```

**Output:**

```jsx
const HelloWorld = () => (
  <div>
    Here's
    my
    div
    with
    a
    lot
    of
    text
    inside.
    Why
    is
    it
    on
    multiple
    lines?
    Text
    isn't
    searchable
    on
    multiple
    lines.
  </div>
);

export default HelloWorld;
```

**Expected behavior:**
```jsx
const HelloWorld = () => (
    <div>
    	Here's my div with a lot of text inside. Why is it on multiple lines? Text isn't searchable on multiple lines.
    </div>
)

export default HelloWorld
```

I believe text in JSX shouldn't be line-wrapped arbitrarily. It could potentially cause formatting issues if your CSS is looking for newlines and makes it nearly impossible to search. Even at `printWidth: 0`, I still expect to have my text untouched.

Another way to think about this, if I put text in here and want to export it somewhere else, I first have to re-assemble all the lines to do so.

**Comment by thorn0** [comment]
> I believe text in JSX shouldn't be line-wrapped arbitrarily. 

I should say upfront that too many users rely on the current behavior and find it convenient, so it isn't going to change. You're the first one who expressed such a request, which means something given the size of Prettier's user base.

> It could potentially cause formatting issues if your CSS is looking for newlines

That's not how whitespace works in JSX. These newlines don't survive the compilation. E.g. see this [example](https://codesandbox.io/s/zealous-heyrovsky-4vlvy?file=/src/App.js:123-171). Or could you probably use CodeSandbox to provide a reproducible example of what you mean?

> Another way to think about this, if I put text in here and want to export it somewhere else, I first have to re-assemble all the lines to do so.

JSX isn't a great format for long text content anyway. You should consider something like MDX instead.

**Comment by Sawtaytoes** [comment]
There are a few reasons I'd be the first one to submit such a request:
1. I don't hold the opinions of others.
2. I'm willing to speak up in an environment where my opinion will seen as deviant.
3. I'm somehow smart enough to discover things on my own that literally no one's ever figured out.

I'm going to assume number 2.

In your CSS example, it works if I do `{'foo\nbar'}`. This means React is changing how it works. If I do it in the `index.html`, it works as expected: https://codesandbox.io/s/serene-stonebraker-86i9c

But then, does Prettier's line-wrapping take place? I can't tell. It keeps reformatting my HTML to look like:
```html
    <pre>
    foo
    bar
  </pre
    >
```

**Comment by thorn0** [comment]
JSX and HTML are two different languages with different, albeit similar, syntax. In particular, whitespace doesn't work the same way in the two. Closing this as bug reports require steps to reproduce.
