### ISSUE TITLE
0️⃣ Line-break not occurring consistently in object properties

### ISSUE THREAD

**Issue by Sawtaytoes** [prettier/prettier#10554]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAxCAnAW0wF5MAKYAHSk0zjz3wFk400BDAc1ZPOttoBLKIJiD2AGwAKjAA5p+AgHT1GeFmy6tFASgA0i6AGEAFuyjdeZRbTQQCcAEpwAZjcxKwAVwYIY7pWMzCzhdAxpMaABlLwAjAlErd2FRcWk5BQjaQKgY+NEwxQA3SS8eUmsszBSxSRkIeQCSiTLM2n1qAF8dEgA+PgiAHhd8Al73YDATQQkAEzwETsVBgHoRwnGoHWpqOAAPWXwsWdd2LwksXEJqED0QBrF0ZFB2BggAdylXhDRkEEl3uwAJ6-O6xPDsMAAazgMCiskhwk4yBgeDKdzgBFicFmJ1mABlzJwvForgR2DAxBY-mcYBBbiATDACBIAOrTeBoBFgOBRH6pIqiIF-MBsBnCND0GAyLjk5AuSSSu4AKzQewAQhDobCouwHPjhHB5Yq4Cq1VEkRI4ABFLwQeDGiRKkAIvCSvB-WLsbESBmyPDCGCswSzGAmZAABju-ogktZENkf39rHoRSNdwAjnb4PV5DS0ABaKBwHE4hkLLOCBYyzhypAKp2mkCShIotFNtCWm3Zo31k13GDe4Oh8NIABMA4hMyRRnsdZArAArAyvJKACre359xt3IplACSUBOsCiYADshgAEEj1EYECrY7JZ1OkA)

```sh
# Options (if any):
--print-width 0
```

**Input:**

```jsx
const Form = ({
  errorMessages = (
    initialProps
    .errorMessages
  ),
  onChange = (
    initialProps
    .onChange
  ),
  onSubmit = (
    initialProps
    .onSubmit
  ),
  values = (
    initialProps
    .values
  ),
}) => (
  <form>
    {children}
  </form>
)

export default Form
```

**Output:**

```jsx
const Form = ({
  errorMessages = initialProps.errorMessages,
  onChange = initialProps.onChange,
  onSubmit = initialProps.onSubmit,
  values = initialProps.values,
}) => (
  <form>
    {
      children
    }
  </form>
);

export default Form;
```

**Expected behavior:**
```jsx
const Form = ({
  errorMessages = (
    initialProps
    .errorMessages
  ),
  onChange = (
    initialProps
    .onChange
  ),
  onSubmit = (
    initialProps
    .onSubmit
  ),
  values = (
    initialProps
    .values
  ),
}) => (
  <form>
    {children}
  </form>
)

export default Form
```

With `printWidth: 0`, I'd expect nothing to change from the code I wrote to the Prettier-formatted code. I get that Prettier removes parens, but it didn't even do that here; it just left those objects on a single line. I think this is because Prettier internally has a minimum of 2 before it line-breaks props.

This is inconsistent behavior.

Say I had one of these with more than one property like:
```jsx
  errorMessages = initialProps.errorMessages,
  onChange = somethingRef
    .current
    .onChange,
```

Suddenly, there's inconsistent formatting making it more difficult form e to skim the code and understand what's going on.

It's also strange that in some cases, as shown [here](https://github.com/prettier/prettier/issues/10553), Prettier line-breaks the entire value down onto another line but here, because we're using `=` and not `:`, it only line-breaks the properties.

Lastly, by not adding parenthesis around these groupings, the comma moves to different lines making it harder to edit code and also means random changes will show up in the commit history.

**Comment by thorn0** [comment]
Sorry about that, but Prettier is not intended to be used with `printWidth: 0`.
