### ISSUE TITLE
0️⃣ Line-break occurs after a single child of `{ }` in JSX

### ISSUE THREAD

**Issue by Sawtaytoes** [prettier/prettier#10555]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBhArhiAWwBEBLAN0wF5MAKASmoD46AdKTTAHgBMKn2nTsDAALUgBseAJwQBfQdwD0fcgKj12IADQgIABxil0yUAENp0iAHcAChYRpkIMxOtmAnk90AjaWbAAazgYAGV9ANIoAHNkGGlcOF04Qh84Hh50gBkzGNwzaLgAMQhpQjMYIxjnM1wYCB0QURhCCQB1cXg0CLA4UMdSI3JBj2cwNG8QKLQ4aRhbf2jy5AAzVxndACs0AA8AIX8gkNCzQjgsqLhV9aSQbZ3QqOiJOABFXAh4a4kNkAjpGbSZw+MxpCSNfTSKIwNqkHgwUTIAAMukhEBmbX8+mckLggPIV10AEcPvAFgYnCgzGgALRQODpdKNWQk0iyBYFZZINY-W4zQikOIJPlPF7vT5Xbk3XQwUGw+GIpAAJhl-kkT2wRC5IDxAFZGvg4AAVUGUnm-ciJACSUEysFCYChhgAgrbQjAPC9vjM5HIgA)

```sh
# Options (if any):
--print-width 0
```

**Input:**

```jsx
const CustomDiv = () => (
  <div>
    {children}
  </div>
)
```

**Output:**

```jsx
const CustomDiv = () => (
  <div>
    {
      children
    }
  </div>
);
```

**Expected behavior:**
```jsx
const CustomDiv = () => (
  <div>
    This is my text: {children}. And I think it's okay.
  </div>
)
```

Related to, but different from https://github.com/prettier/prettier/issues/10552.

Another example:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBhArhiAWwBEBLAN0wF5MAKASmoD46AdKTTAHgBMKn2nTgBUAFqTSYJmQgE9M8AB4wkmYGHEAbHgCcEAXwB0mAIJQemAJILxUANZSYAckkQ7AQ1mHB3APR9yASh6dhAAGhAIAAcYUnRkUHcdHQgAdwAFJIQ0ZBB3TVTPHIiAIx13MDs4GABlKIrSKABzZBgdXDgIuEISuB4ePoAZd2bcdya4ADEIHUJ3GFjm3PdcGAhwkFEYQk0AdXF4NHqwOBrs0ljyC9lcsDRikEa0OB0YdPKmueQAM3zniIAVmhFAAhcqVao1dyEOCDRpwH5-TogIGKGqNJqaOAARVwEHgiM0-xA9R0zx0uRK7l6mg2UR0jRgu1IPBgomQAAYIvSIM9duUorl6XByeQEREAI54+DvaI5FDuNAAWigcD6fQ2eilpD073GXyQvyJyOehFIrXaJoxWNx+IRhqRERg1OZrPZSAATE7yqRNBjsEQDSARQBWDb4ODCanyo3E8gdSzmBC1MAMmJmHg1GCyLGE576fRAA)

```jsx
const CustomDiv = () => (
  <div>
    This is my text: {children}. And I think it's okay.
  </div>
)
```

**Output:**

```jsx
const CustomDiv = () => (
  <div>
    This
    is
    my
    text:{" "}
    {
      children
    }
    .
    And
    I
    think
    it's
    okay.
  </div>
);
```

This one isn't a huge issue by itself, but when you put text around mustache tags like this, you lose the ability to keep this in one line, and it becomes unreadable.

The official React recommended ESLint rules auto-fix to:
```jsx
const CustomDiv = () => (
  <div>
    This is my text:
    {" "}
    {children}
    {" "}
    . And I think it's okay.
  </div>
)
```

That's most-likely because of my StackOverflow response on the topic: https://stackoverflow.com/a/41142436/1624862. While it doesn't keep the text in one line, it still has consistent behavior.

Even if Prettier still dropped the singular items in mustache tags onto their own lines, I'd at least expect this behavior:
```jsx
const CustomDiv = () => (
  <div>
    This is my text:
    {
      " "
    }
    {
      children
    }
    {
      " "
    }
    . And I think it's okay.
  </div>
)
```

And ideally, this one as a compromise:
```jsx
const CustomDiv = () => (
  <div>
    This is my text:
    {" "}
    {
      children
    }
    {" "}
    . And I think it's okay.
  </div>
)
```

**Comment by thorn0** [comment]
`--print-width 0` isn't a supported use case and won't be fixed.

**Comment by Sawtaytoes** [comment]
Why wouldn't `--print-width 0` be a supported use case? What about `--print-width 20?` Is there a point at which Prettier won't go lower?

**Comment by thorn0** [comment]
Prettier is supposed to be used with `printWidth` values from the range 80...100.

**Comment by Sawtaytoes** [comment]
So I understand this, does that mean Prettier is not meant to be used with mobile-safe code? Like, code meant to display in a portrait orientation in a narrow viewport?

**Comment by thorn0** [comment]
You're right. That's something that is out of scope for Prettier.

**Comment by Sawtaytoes** [comment]
I appreciate you responding and going through all the issues I put up.

I've been going through Prettier's source and reading the docs and noticed no one's written or made a video about how amazing the code is behind the scenes. The kinds of things you had to work around like unit tests strings, importing single items, etc. These are all important topics. Everyone's videos are like "here's how you integrate Prettier into your app".

While I completely disagree with the direction of the code styling, the library itself is very well-made. I like the goal of not-breaking-code. For a long time, I thought nothing was documented about how the library worked (since nothing shows up in a web search), but after reading the `docs/` folder, I have a much better grasp.

Maybe the Document idea came from Recast, but it's brilliant. I was expecting complicated ESLint rules and complex AST parsing but instead found an interim Document format--something that's completely language-independent--printed by calling functions. And seeing how Prettier determines how to line wrap based on the `group` function; impressive stuff!

---

As a side note, the reason I care about something like `--print-width 0` is because I code in vertical columns and spend a lot of my day reading code reviews. But I think the bigger issue is actually reading code articles on my phone (including documentation on sites like GitHub). With Prettier formatting, I have to constantly scroll left and right making it nearly impossible to read.

Since Prettier has taken off, I see its formatting everywhere and this is a problem when wider code is, in general, harder to read.

Prettier can run in the browser and be used to reformat code on-the-fly for mobile devices; although, if it's not meant to go under 80, that poses an issue.

I'm in agreement that Prettier shouldn't change as it is. I get why you've made the decisions you have and agree, adding options to change it is exponentially harder when your goal is "it doesn't break your code".

Now that I know Prettier isn't going to accomplish my vision, I've gone ahead and forked it, so I can achieve my goals of auto-formatting vertically-oriented code without ESLint. 🥂
