### ISSUE TITLE
Babylon is enabled by default, but tests aren't run using babylon

### ISSUE THREAD

**Issue by ChristianHersevoort** [prettier/prettier#1057]
By default the tests are run using the [flow](https://github.com/prettier/prettier/blob/master/tests_config/run_spec.js#L85) parser but the prettier is using [babylon](https://github.com/prettier/prettier/blob/master/bin/prettier.js#L79) by default. 

This causes some inconsistenties and it also breaks 51 tests. 

Some suggestions:

- Run all tests against flow, typescript and babylon
- Make flow the default formatter in https://github.com/prettier/prettier/blob/master/bin/prettier.js#L79) (As flow seems to be the most stable at formatting code right now)

**Comment by vjeux** [comment]
Hey, yeah this is unfortunate. We started with flow parser and then added babylon. If you want to help out fixing the 51 tests that are not passing in both that would be awesome.

**Comment by ChristianHersevoort** [comment]
I created https://github.com/prettier/prettier/pull/1068 to able to fix this problem, but actually prettier should test every parser implementation against the **same** snapshot. Jest unfortunately doesn't support this, every call to toMatchSnapshot() tests against a **different** snapshot. (which is fine in normal tests). 

1. Create a single snapshot for each test using flow (ignoring babylon and typescript) (call this this "base" snapshot*)
2. Verify output of babylon and typescript against "base snapshot" (write a jest plugin?)
3. Add to ability to opt-out (ignore) a test on a specific (instead of breaking the test?) 
4. (separate issue) Have a way to visualize the result per parser

* Maybe allow the change of the 'base-snapshot'

Once we get concensus; I will try to write a prototype this week

**Comment by existentialism** [comment]
A number of the failures will be fixed once [declare export](https://github.com/babel/babylon/pull/224) support lands (soonish!).

Some, as discussed before, will require us to pass options to the babylon, like toggling strict mode for things like [octal numbers](https://github.com/prettier/prettier/issues/228).

**Comment by vjeux** [comment]
We could allow multiple arguments to run_spec

```js
run_spec(__dirname, { parser: 'babylon' }, { parser: 'flow' })
```

And ensure that the result is the same for all the options and matches the snapshot.

This way it'll let us on a per test basis chose what we want

**Comment by vjeux** [comment]
We can use toBeEqual() between the various options so we don't need to invent anything in jest

**Comment by vjeux** [comment]
I just reverted https://github.com/prettier/prettier/pull/1070 as it conflicted with all the existing pull requests and if you follow through my suggestion then we don't actually need to put the parser name in the test

**Comment by ChristianHersevoort** [comment]
@vjeux I don't think we can use toBeEqual because prettier relies on Jest generated snapshots, if ship our own implementation we would also lose the Jest snapshot update feature.I agree that we should modifiy the run_spec call and allow multiple parsers in a single call.

I want create something like:

1. use toMatchSnapshot on first parser from run_spec, or default to jest if none provided
2. Verify jest snapshot against every additional parser provided to run_spec (using toBeEqual)
3. Run Test.skip on each parser not provided to run_spec

**Comment by vjeux** [comment]
Yeah we should use both toBeEqual and toMatchSnapshot.

Why would you do test.skip? It's only going to add noise. Also, there are many tests that have flow nodes that won't work with the typescript parser and vis-versa.

**Comment by ChristianHersevoort** [comment]
Jest doesn't have a method (AFAIK) to to test against the *same* snapshot. Jest internal doesn't expose any internal interface to access the snapshot data either :(. This is especially hard since the Jest snapshot-subsystem is a state-machine with (some) magic.

In order to fix this I can either:

1. Re-implement some of the Jest snapshot reading logic -> This is more work, but is probably more safe in the long run
2. Access the jest global state and touch it's private vars -> This is easier, but might break if Jest internals change. 

Thoughts?

**Comment by vjeux** [comment]
You don't need to change jest.

If you have 3 parsers, compute the result of the three and then

```js
expect(one).toEqual(two)
expect(one).toEqual(three)
expect(one).toMatchSnapshot()
```

**Comment by ChristianHersevoort** [comment]
You are probably right, but it might give incorrect test results if the first(one) parser has a bug. 

If you test against the same snapshot you can also find bugs in the first parser.

**Comment by vjeux** [comment]
In this mode, all the options need to be outputting the same thing, so if the first one or the last one is different then you are going to have a failing test and need to fix it. I'm not sure what isn't working? Do you have an example?

**Comment by vjeux** [comment]
We're in a much better shape now, I'm going to close this issue.
