### ISSUE TITLE
[HTML] Add an option to choose void tags over self-closing tags.

### ISSUE THREAD

**Issue by nerfipro174** [prettier/prettier#10577]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
```

**Input:**

```jsx
<img src="" alt="Example">
```

**Output:**

```jsx
<img src="" alt="Example" />
```

**Expected behavior:**
I'd really love to have a possibility to choose void tags over self-closing tags. I know that many people choose them because it's compatible with XHTML but I really don't need them and at this moment this is the reason why I am not using this extension. This is great in every other thing and I'd really like to start using it but I can't know because of this self-closing tags.

**Comment by thorn0** [comment]
Options are added only in the case of strict technical necessity. See here https://prettier.io/docs/en/option-philosophy.html
