### ISSUE TITLE
how to test prettier in jest?

### ISSUE THREAD

**Issue by southorange1228** [prettier/prettier#10597]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: 
- Runtime: 
- Operating System: 

**Steps to reproduce:**
1.
```ts
export const formatCode = async (content: string, configPath: string) => {
  const configOptions = await prettier.resolveConfig(configPath);
  const formatted = prettier.format(content, { parser: 'typescript', ...(configOptions as any) });
  return formatted;
};
```
2.
```ts
it('formatedCode test', async () => {
    const result = await formatCode(' var a = 123', join(__dirname, '../config/prettier.js'));
    expect(result).toBe('var a = 123;\n');
  });
```

**Expected behavior:**

this case should not fail.
**Actual behavior:**

i think it's ok,but i got some error
![image](https://user-images.githubusercontent.com/32590310/112406706-9d8b0a80-8d4f-11eb-8ff4-691e6dfe608f.png)

**Comment by thorn0** [comment]
I can't reproduce this. Could you create a sample repo with a minimal reproduction?

**Comment by southorange1228** [comment]
i create a mini program and can't repreduce too. 
i think i get some error config. maybe? 0.0

**Comment by thorn0** [comment]
Unfortunately, without a reproduce, it's impossible to tell what's going on.
