### ISSUE TITLE
MDX: code block comments are stripped out when tagged as tsx

### ISSUE THREAD

**Issue by mattdarveniza** [prettier/prettier#10591]
__NOTE__: filled out manually because prettier playgrounds don't support mdx as far as I can tell
**Prettier 2.2.1**

```sh
# Options (if any):
N/A
```

**Input:**

````mdx
# hello

this is an mdx file, here's some jsx

<Meta title="page title" />

Here's a codeblock using standard markdown

```tsx
// I'm a code comment
const someCode = 'foo'
```
````

**Output:**

````mdx
# hello

this is an mdx file, here's some jsx

<Meta title="page title" />

Here's a codeblock using standard markdown

```tsx
const someCode = 'foo'
```
````

**Expected behavior:**

Prettier should leave code comments inline in code blocks. Sometimes it is useful to leave comments in code blocks, even when writing mdx, in order to point to specific lines and document those without breaking the code block into unreadable chunks.

Notably this only seems to be an issue with `tsx`, when tagging a code block as `jsx` it leaves the comment unharmed.

**Comment by fisker** [comment]
What do you mean 

>  prettier playgrounds don't support mdx

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABACzgGxxAHSiJkwEsBndS9AQynQFsATAD3QDMyc4AaLOACc4AcioUIjOOgBWFVkSIAeALJwYtdDDIweAXgIgADrQDm07briH0AegB8iqAAkhoqpsjM4AI3xgAa3QAVwoyKFN0Cg0oZlpBZiZ4gOYIAHdiTIADHJh5IltbdABJEUY6dC9pSEYpWCJIKGioyTgAYQhvdD10EQ4ICBEiHKyQXhAII21oCmRQeMF0gAV4hFmUWhw02gBPWfGfQVpA9QBlEzBw02QYQWC+EDhGHzhmb2YAGXpTYLM4ADEIIJGLQYNoIsgQLRgjAIGMQJgYIwcAB1cjwCgXOCnNY6MgANx0O0hYAo+xA4QoQhgSyOphByA4myp4zkrAAQkcTjBTrQpB9wnBGcyHmzTlceABFYIQeDCnAs4zxKmCSEsVjwoyCcIwFFkZikZAADgADOMtRAqSijkZIVq4Cr8ULxgBHGXwWmTdZQigAWigcFer3hwjdZGEtLMDKQTIVDypjDINzu8YlcGlsqFMZF4w0Pj1BswyAATLmjtwrh1arRIQ6AKzw0JwAAqtB861jivx92KsQQPLA2qmAEFYqcYDsePKqQBfGdAA)

```sh
--parser mdx
```

**Input:**

````mdx
# hello

this is an mdx file, here's some jsx

<Meta title="page title" />

Here's a codeblock using standard markdown

```tsx
// I'm a code comment
const someCode = 'foo'
```
````

**Output:**

````mdx
# hello

this is an mdx file, here's some jsx

<Meta title="page title" />

Here's a codeblock using standard markdown

```tsx
// I'm a code comment
const someCode = "foo";
```

````

I can't reproduce in playground.

**Comment by mattdarveniza** [comment]
Sorry I completely missed that you can set the `--parser` flag to mdx in playgrounds. Yeah interestingly it doesn't seem to happen in the playground, _or_ when running the CLI. Seems to be a thing only in vscode. I'll close this issue and try to figure out what's going on with the vscode plugin.

Thanks for the reply and sorry for the hassle!
