### ISSUE TITLE
When will dart files be supported

### ISSUE THREAD

**Issue by mulieli** [prettier/prettier#10590]
When will dart files be supported

**Comment by alexander-akait** [comment]
Dart has `dartfmt` tool to format dart files, you can create plugin to run it inside prettier

**Comment by kachkaev** [comment]
When creating a plugin, you can use [prettier-plugin-elm](https://github.com/gicentre/prettier-plugin-elm) as inspiration. It is a pretty thin wrapper around [elm-format](https://github.com/avh4/elm-format).
