### ISSUE TITLE
 Comment "x" was not printed. Please report this error!

### ISSUE THREAD

**Issue by tomardern** [prettier/prettier#10592]
**Environments:**

- Prettier Version: 2.2.1 (This does not seem to be an issue in 2.0.5)
- Running Prettier via: VSCode/CLI
- Runtime: Typescript / Angular
- Operating System: Mac OS

**Steps to reproduce:**

Adding a comment such as `/* something here */` or `// something here` above a class, such as:

```
/* something here */
@Component({
  selector: 'something-here',
  templateUrl: './something-here.html'
})
export class SomethingHere {
```
or

```
// something here
@Component({
  selector: 'something-here',
  templateUrl: './something-here.html'
})
export class SomethingHere {
```

**Expected behavior:**

**Actual behavior:**

I get the following error message:

```
["ERROR" - 11:44:04 AM] Comment "something here" was not printed. Please report this error!
Error: Comment "something here" was not printed. Please report this error!
	at /<project>/node_modules/prettier/index.js:13827:13
	at Array.forEach (<anonymous>)
	at ensureAllCommentsPrinted (/<project>/node_modules/prettier/index.js:13825:15)
	at coreFormat (/<project>/node_modules/prettier/index.js:13874:3)
	at format (/<project>/node_modules/prettier/index.js:14115:73)
	at formatWithCursor (/<project>/node_modules/prettier/index.js:14131:12)
	at /<project>/node_modules/prettier/index.js:42399:15
	at Object.format (/<project>/node_modules/prettier/index.js:42418:12)
	at t.default.<anonymous> (/<user>/.vscode/extensions/esbenp.prettier-vscode-6.3.1/dist/extension.js:1:16946)
	at Generator.next (<anonymous>)
	at s (/<user>/.vscode/extensions/esbenp.prettier-vscode-6.3.1/dist/extension.js:1:9119)
["INFO" - 11:44:04 AM] Formatting completed in 134.263562ms.
```

Thanks,

**Comment by sosukesuzuki** [comment]
Can you reproduce it in https://prettier.io/playground?

**Comment by tomardern** [comment]
@sosukesuzuki I've just tried now, I can't no, how very odd... sorry!

**Comment by thorn0** [comment]
@tomardern Are you still able to reproduce this locally? Did you copy the exact code you had a problem with to the playground? Did you select the same parser (and other options) that you use locally?

**Comment by trumbitta** [comment]
I have the same error locally, with comments above imports

**Comment by thorn0** [comment]
@trumbitta https://mobile.twitter.com/bradzacher/status/1169731712751812608

**Comment by trumbitta** [comment]
@tomardern I can't reproduce it on the playground either. Are you having the error via the VSCode extension like I have?

@thorn0 I was looking into it but the kid came back crying and I forgot to submit the comment with the line above.

Aaand, I just confirmed prettier ran directly from node_modules works like a charm so it must be the extension and I'm heading on its repo to continue looking for a fix

**Comment by trumbitta** [comment]
@thorn0 but then again https://github.com/prettier/prettier-vscode/issues/1552 ... now I'm confused

**Comment by thorn0** [comment]
@trumbitta please provide a repository with a minimal reproduction

**Comment by tomardern** [comment]
> @tomardern I can't reproduce it on the playground either. Are you having the error via the VSCode extension like I have?
> 
> @thorn0 I was looking into it but the kid came back crying and I forgot to submit the comment with the line above.
> 
> Aaand, I just confirmed prettier launched directly from node_modules works like a charm so it must be the extension and I'm heading on its repo to continue looking for a fix

Yes, this was via the VSCode extension, I can't replicate using the playground sadly... :(

**Comment by Kevinchenshujian** [comment]
I also face the same issue. As long as the code has comments, the prettier cannot work.

**Comment by thorn0** [comment]
@trumbitta 

> it only happens via the vscode extension

In that case, provide a repository where we could see a minimal reproduction in the VS Code extension. There isn't much we can do without a reproduction.

Do you happen to use any Prettier plugins?

**Comment by thorn0** [comment]
@tomardern Do you use Prettier plugins? How did you configure the extension? Did you tweak any formatting-related settings in VS Code (e.g., `editor.formatOnSaveMode`)?

@Kevinchenshujian Could you make a proper bug report? Please include as much actionable information as possible: input, error, configuration, environment, logs, repo with a minimal reproduction (or a reproduction on the playground), etc.

**Comment by trumbitta** [comment]
FYI https://github.com/prettier/prettier-vscode/issues/1872#issuecomment-808237184

**Comment by johnnyasantoss** [comment]
Not sure how this happened to you all, but to me, it started after changing branch (and with that changing a lot of prettier config files).
After restarting VSCode it was fine. Probably some issues with caching the config and ignore files.

(Still not sure why the error would be related to comments, but hey, just trying to help here)

**Comment by ackmanx** [comment]
I get this exact error within Intellij after I upgraded from prettier v1 to latest, and then upgraded eslint prettier as well. I haven't narrowed it down, but I'm not using VSCode and get the same error.

Like @johnnyasantoss mentioned with restarting, after restarting Intellij the problem went away.

**Comment by Nnadozie** [comment]
> Not sure how this happened to you all, but to me, it started after changing branch (and with that changing a lot of prettier config files).
> After restarting VSCode it was fine. Probably some issues with caching the config and ignore files.
> 
> (Still not sure why the error would be related to comments, but hey, just trying to help here)

@johnnyasantoss this worked for me, thanks for sharing!

**Comment by VincentPuget** [comment]
> Not sure how this happened to you all, but to me, it started after changing branch (and with that changing a lot of prettier config files).
> After restarting VSCode it was fine. Probably some issues with caching the config and ignore files.
> 
> (Still not sure why the error would be related to comments, but hey, just trying to help here)

Restart VSCode works for me too. Thx @johnnyasantoss
