### ISSUE TITLE
backslash double

### ISSUE THREAD

**Issue by Ramsteven** [prettier/prettier#10593]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAFAcgDwEsoAOArjAAQwCeBcAvADoMMgAWuAJmwoyKVAIYBbWoyYE+FIbADaMCAGsEAXRF0eAegB8mAJQA6AG58ANulkKo2ulBAAaEBAIxc0AM7JQfAE6eIAdwAKXghuKMa+4m52AEaefGAKMADKYmD4AObIMJ5EcHZwAlFwHEUAMnxQaUR8aXAAYhCeAnwwThXIIHwkELYsMAJGAOqs8C4pcInBuE76UxTtYC6RIPgucJ4w-rFpTcgAZsardgBWLgAeAEKx8XBJgnAl+HB7B7kgJ6eJ6UZwAIpEEPBnkZDiAxJ5Vp52lE+IUjD0CJ58DABuwYMxkAAOAAMdgREFWA1iBHaCLgEP0TzsAEd-vBNg4Qh0XABaKBwIpFHqeOA03DczbVHZIfbA16rAS4TLZMVfX60p7Cl52GAwlFsNHIABMytiuCM6QAwhABEKQGSAKw9IirAAqMJCIpB+hyAEkoJxYIkwIjHABBd2JSjfIGrAC+oaAA)

```sh
--parser babel
```

**Input:**

```jsx
$('<input type=\\"hidden\\" name=\\"payment[token]\\" />').val(token)

```

**Output:**

```jsx
$('<input type=\\"hidden\\" name=\\"payment[token]\\" />').val(token);

```

**Expected behavior:**

```jsx
$('<input type=\"hidden\" name=\"payment[token]\" />').val(token);

```
Hello i have this problem, i reading thread about use  two backslash for obtain one but in this case dint works, and i need send this string exactly to stripe, i am using vim how editor.

**Comment by alexander-akait** [comment]
`\\"hidden\"` is not same `\"hidden"` and can be changed, you should not use `\\` in your case

**Comment by Ramsteven** [comment]
> `\\"hidden\"` is not same `\"hidden"` and can be changed, you should not use `\\` in your case
how would you do it?
