### ISSUE TITLE
JSX inserts blank space when bad indented

### ISSUE THREAD

**Issue by lpalmes** [prettier/prettier#1061]
When running prettier through this code, notice that there is a space between `<h2>` and `Dog`, It insert blanks space before the child of h2, i'm not sure if this is intended, i was expecting to wrap it all in one line, but the blank space might be interpreted as intentional white space.
Thanks and great project! 😄 
```js
const App = (
  <div>
    <h2> Dog
    </h2>
  </div>
);
```
```js
const App = (
  <div>
    <h2>
      {" "}Dog
    </h2>
  </div>
);
```

**Comment by vjeux** [comment]
This is actually intended, prettier doesn't change the behavior of your application, so it cannot drop this space and has to recreate it. At least, it's going to teach you how JSX actually works!

**Comment by lpalmes** [comment]
Ohh, makes sense, thanks!

**Comment by rattrayalex** [comment]
@lpalmes FYI you could also write:
```jsx
const App = (
  <div>
    <h2> Dog</h2>
  </div>
);
```
and prettier will leave as-is.

**Comment by lpalmes** [comment]
Thanks @rattrayalex, it was just me formatting code when i found this, it wasn't a real use case.
Thanks anyway!
