### ISSUE TITLE
special chars in strings

### ISSUE THREAD

**Issue by rmetzler** [prettier/prettier#1062]
Prettier replaces special chars like "äöüß" in Strings with another representation.

```js
var test = "äöüß";
```
becomes
```js
var test = "\xE4\xF6\xFC\xDF";
```

Is there a way to deactivate this behavior?

**Comment by lydell** [comment]
You seem to be running an old version of prettier – that escaping behavior has been gone for a while :) https://prettier.github.io/prettier/#%7B%22content%22%3A%22var%20test%20%3D%20%5C%22%C3%A4%C3%B6%C3%BC%C3%9F%5C%22%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by rmetzler** [comment]
:man_facepalming: Thank you.
