### ISSUE TITLE
`as` in array destructuring is printed wrong (babel-ts only)

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#10635]
This is valid TypeScript, but Prettier corrupts it. AST isn't aligned with typescript-estree.

**Prettier pr-10416**
[Playground link](https://deploy-preview-10416--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBtAhgAnQZ21ATwF1MBeTADwG4QAaECABxgEtodlR0AnbiAdwAKPBBxToANv3QEO9AEbd0YANZwYAZUbKWUAObIY3AK5x6cALby4AExu2AMun3H0euADEI3C+hit9ZBB0YxgIOhAACxgLCQB1SJZ4HG0wOA1RJJYANySCILAcORBdHDhuGEElPV9kADNJMvoAKxwKACElVXUNdAs4B104esazEFaKDV09CTgARWMIeBGJJpBtbjLuIPl0awkAWhhixm5dGDiWGxhI5AAOAAZ6U4gyuKVGINO4Lezh+gAjot4FUmGJgjgDlA4LZbBFuHAgSwEVU3LUkA1VmMyhYWIYTNjprMFkthhjRvQYHtLtdbkgAEyUpQsCTTADCEAs6JAPwArBFjGUACp7MSYtbZUwASSg9lgGjAZ2YAEFZRoYARZisygBfHVAA)

```sh
--parser babel-ts
```

**Input:**

```tsx
[a as any] = x;
```

**Output:**

```tsx
[a: any] = x;

```

_Originally posted by @thorn0 in https://github.com/prettier/prettier/issues/10416#issuecomment-809418766_

**Comment by Swastik2000** [comment]
I'd like to work on this as my first contribution to Prettier. I'll create a PR within the upcoming days.
