### ISSUE TITLE
GraphQL anonymous operations have incorrect spacing after keyword

### ISSUE THREAD

**Issue by leebyron** [prettier/prettier#10655]
Formatting of GraphQL operations (eg a query) are formatted to incorrectly remove the space between the operation keyword and the variable body.

See this [Prettier GraphQL playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAUQB4Ac5gzoDOuAhmHOmQGbwBO6AjgK5z0Ce6A1nBwO4R6AEwA06AEYsiUCEVoNmbTugByZALZwAOlFbsu6rcIAUAEgBuZeknQBlGPQCWUAOYBKdMHS706J8I+UAC+uroYOPiEJOSU1HTsSgY8fIIi-lDUslAcGhAsxEmcuvoq5ixQUJpwwrYOzm6e3r7+gbqhUOFYeAREpBRUComlXLwCQoEuWdC5+YWyALRWjCMlylzALQHtuiCiIBC4ME7QxMig1vQQ-AAK1ghnKGQANvxkHGf7EvQUvDB2sRcrmQjjY+zgGgkNWENQAMmQ3CwyK44AAxIQaMgwY5uZAgMjSCB7EAACxgGmeAHUSU54P1KHYHrSnBZaRw8WBiJ8QC5iOwYDcfq5McgaC8+fsAFbEbAAIR+YD+dmqsJccFF4rgUpldiBzzgAEUWHJ1Ugxc8JSByPQ+fQ8a4frgSUxnsTcA0YJSAjAScgABwABn27ogfMpjrx7rgtos6v2rBNgsOj3xxAWUDgNRqxPocFYTlzguRIrNmv2fI0ThB9DBIGIesNxvgGotWpAMDIEi9wh9yAATPtHGQnM8gQBhCAaEsgaMAVmJBTgABVO49zZaLGwAJJQGGwOxgZxHACCu4cHH1Lb5wWCQA) for repro as of prettier@2.2.1:

**Expect formatting:**

```graphql
# Expect space after query keyword in anonymous query
query ($unnamed: String) { 
  id 
}
```

**Actual formatting:**

```graphql
# Expect space after query keyword in anonymous query
query($unnamed: String) {
  id
}
```

This grammar for named and unnamed queries is designed similarly to named and unnamed functions in programming languages, and should be formatted similarly. For a point of comparison, see this [Javascript Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAogDwA5xgwYDOeAhmHBuQGbwBOGtArlEQJbQYDWcAngHcIDACYAaDACMWxKBGJ1GzNp24A5cgFs4AHSit2MLlAyadogBTkGAcwCUGYAF99+9NnyFiZStSVwTIZqpnxCIqIYHKbk8lD8WhAsJCpGJvqQUCTEbFDacJEAvKkhGNZ2ji76IOIgEHjG0CTIoDYMEIIACjYIzSjkADaC5PzNtVIMlHwwAMoUYNG2yDAMLHC1cFpSBaIFADKxtizktnAAYiJa5DDGUEv9shA1IAAWMFoDAOovHPC+VDNer8OAA3X78ZDgEhjEDREiBGCdSa2K7IWiDeG1ABWJBwACFJmBpjN8ntonA0Rj1iAcTgZosBnAAIosBQUpDogaYkAUBjwhiQqTkbYDZ54BjRGCfDiiGAvZAADgADLVxRB4Z9JnhIeK4PyQRTagBHVnwJH1PogcgkAC0UDgBQKzwYcBNHBdSJOqI5VNq8K0HGWq2pJAZzNN7M53JgwulsvlSAATLUVuQOANFgBhCBab0gPUAVmeyTgABVhX0o9SQWsAJJQXawGZgCUNACCDZmMH4jMpXLgzmcQA) which shows consistent spacing after the `function` keyword.

**Comment by patriscus** [comment]
I'd like to work on this as my first contribution to Prettier. I'll create a PR within the upcoming days, most likely until next Wednesday latest (but probably earlier).
