### ISSUE TITLE
Comment is duplicated when prettier-ignore is used

### ISSUE THREAD

**Issue by Daniel15** [prettier/prettier#10661]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAdAIwDpQAR4D0heADgE5wwwCWc5AtDQOZQSW4HF4DKEAtnDwQYAC3p5I-QbDziO+POjAgANCAila0AM7JQqcuQgB3AAqGEelKgA2J1AE896zOVRgA1lR6kPNKGZkGHIAVzh1OH5MOAATWLiAGVRA0NRmOAAxdn5UagCgm1CYCDUQURh+WwB1URp4HT8wOB4repoAN3rHZHAdFxAAnXoYM3dmXOQAMzth9QArHQAPACF3Lx9UQUSAuGnZiJBFpZ4C2zgARVCRPaQZ2zmQP3Jh8l7MVBjbMooAmGqaLExMgABwABnUFAgw2q7lIvQocFeHT26gAjtd4GNNNY0DoGFA4HE4mVKBiaJQxulJncDuphvwaMEwocdGdLpjbvdHjBPgCgaJkAAmdQhVA0WwFADCAhpICRAFYyqFhgAVT7WbmHDrhACSUASsB4YHINC0AEEDTwYI5zvsHnAAL6OoA)

```sh
--parser babel
```

**Input:**

```jsx
verylongidentifierthatwillwrap123123123123123(
  a.b
    // prettier-ignore
    // Some other comment here
    .c
);
```

**Output:**

```jsx
verylongidentifierthatwillwrap123123123123123(
  // prettier-ignore
  // Some other comment here
  a.b
    // prettier-ignore
    // Some other comment here
    .c
);
```

If you feed the output into Prettier again, it duplicates the comment again:

**Input:**

```jsx
verylongidentifierthatwillwrap123123123123123(
  // prettier-ignore
  // Some other comment here
  a.b
    // prettier-ignore
    // Some other comment here
    .c
);
```

**Output:**

```jsx
verylongidentifierthatwillwrap123123123123123(
  // prettier-ignore
  // Some other comment here
  // prettier-ignore
  // Some other comment here
  a.b
    // prettier-ignore
    // Some other comment here
    .c
);
```

This means that every time I save the file, the comment gets duplicated again above the node 😄

**Expected behavior:**
Comment should not be duplicated

**Comment by bobbyoz** [comment]
Thank you

**Comment by bobbyoz** [comment]
I'm going in seek higher twin loc
