### ISSUE TITLE
Can I customise my code specifically to the way I like using this extension?

### ISSUE THREAD

**Issue by Joe23232** [prettier/prettier#10668]
Hi I wanted to use [Prettier](https://prettier.io/) but I was wondering if I could really customise at a low level and make my code look like this in Rust:

```rust
struct Color
{
    red             : u32,
    blue            : u32,
    greenasds       : u32,
}
impl Color
{
    fn init() -> Self
    {
        Self
        {
            red             : 255,
            blue            : 255,
            greenasds       : 255,
        }
    }
}
```

If this is possible, then can somebody please point me in the right direction as to how I do get this extension to make my code like this?

**Comment by thorn0** [comment]
No, you can't. See here https://prettier.io/docs/en/option-philosophy.html

**Comment by Joe23232** [comment]
I see thanks
