### ISSUE TITLE
Formatting not working properly for typescript new sintax "abstract new () =>"

### ISSUE THREAD

**Issue by Farenheith** [prettier/prettier#10670]
There's a new syntax option released in the latest version of TypeScript which prettier does not recognize properly: **abstract new () -> ...**:
TypeScript release notes: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAsmgQQCMBnGAJwEMwYBhaCgVxonOwF5tLSLqZsocAO7YAFADpJlcgHMSSLlDQBtALoBKDgD5FaANwgANCAgYYAS2glkoaeQhCACtITWUlADZDKaa8aJUYADWcDAAyhjU5lAyyExwxnAAtkRwACZp6QAylDGMlDJwAGKsSZQwFjHIIJSMMBBGIAAWMEkeAOpN5vAkkWBwYa7d5gBu3WjVYCR+INEkcOQwjlQyZcgAZp7zxgBWJAAeAEKBIeGUSXBZ0XAbWwkge-th0TIecACKjBDwtx7bIJFyPNyNV0FgSGByOYzI0MFDYO1zGkYE1kAAOAAMxjhEHm7SoGGqcLgwJGN2MAEcvvBlqY3DUSABaQTpdKNchwKnmDnLAprJCbP73eZJcxxciMYUvN6fb43AV3YwwbiI5GopAAJiVVHMHhe9CS-JAJIArI1GPMACrcNyC-4jSUASSgmVgYUh0JgBBdYXQb1+8wAvoGgA)

```sh
{
  "singleQuote": true,
  "trailingComma": "all",
  "useTabs": true
}
```

**Input:**

```ts
type MyAbstractContructor = abstract new (...args: any[]) => any;
```

**Output:**

```
SyntaxError: ';' expected. (1:38)
> 1 | type MyAbstractContructor = abstract new (...args: any[]) => any;
    |                                      ^
```

**Expected behavior:**

No error

**Comment by thorn0** [comment]
This hasn't been released yet. Please use the search before making new issues.
