### ISSUE TITLE
please help to maintain `eslint-plugin-prettier`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#10699]
Sorry but I have to raise an issue like #10409 again.

---

No really an issue of `prettier` core itself, sorry.

I've been suffered from https://github.com/prettier/eslint-plugin-prettier/issues/393, and raised a PR https://github.com/prettier/eslint-plugin-prettier/pull/401 to fix it, but the current maintainer @BPScott @lydell haven't reviewed and released it.

So I'm here to ask for help from the core maintainers.

It's been **21 days** since I opened that PR.

**Comment by BPScott** [comment]
Hello again. I'm aware of that issue however have been too busy with other work and personal things recently but I haven't forgotten about it. I have a few holiday days over the next week, i might be able to find some time to review it then.
