### ISSUE TITLE
Look for known config file types in package when resolving shared config 

### ISSUE THREAD

**Issue by NoNameProvided** [prettier/prettier#10692]
**Description / Rationales behind the request**

I would like to create a package for my org where all commonly used tooling is authored in a single place. This would allow us to install a single package (eg: `@my-org/shared-tooling`) instead of managing multiple packages and their configurations. 

As far as I understand to share a Prettier configuration the installed package must export the config via the `main` entry in `package.json`. This takeover of the entry point by Prettier is not an ideal behavior for us as we would like to use it for something else. 

So my question/feature request is about whether Prettier can/will support a resolve methodology where it looks for the known configuration file names in the resolved package instead of importing the package entry-point?

**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI
- Runtime: Node LTS
- Operating System: Windows, MacOS
- Prettier plugins (if any): none

**Steps to reproduce:**

- attempt to share config without using `main` export in the shared config package
- notice that sharing config is only available via entry-point  of a package

**Expected behavior:**

- I add `'@my-org/shared-tooling'` to the `prettierrc.yml` in my project as I do now
- Prettier checks if the module exists
- if the module exists, then Prettier looks for all known configuration file names
- if found one, it parses and returns 

**Actual behavior:**

Sharing configuration only works when the entry-point of the shared config package exports a JS(ON) object.

**Comment by thorn0** [comment]
When Prettier finds a string instead of a configuration object, it passes this string to `require`. E.g., if the string is `"@my-org/shared-tooling/.prettierrc.json"`, it'll load `.prettierrc.json` from the package `@my-org/shared-tooling`. Note that `require` doesn't support YAML (at least out of the box), so use JSON or JavaScript instead.
