### ISSUE TITLE
(Feature request) `resolveConfigFile`, `resolveConfig` and `format` as all-in-one function.

### ISSUE THREAD

**Issue by cobraz** [prettier/prettier#10698]
Hello 👋

Thank you for this project! I love it and frankly; I am addicted. Recently, I've dipped my toe in more code generation, and I find myself using Prettier to handle all formatting.

More often than not, I pack Prettier with my code generation utility/package. This way I don't have to care much about the code style, just the actual generation. Less complexity, fewer things to go wrong 🤷 

Anyway, what I find lacking with the current Prettier API is a way to resolve the config file path, config and format in one function. I tend to write this function all the time:

```typescript
import * as prettier from 'prettier';

async function formatWithPrettier(source: string): Promise<string> {
	const configPath = await prettier.resolveConfigFile();
	const config = await prettier.resolveConfig(configPath);
	return prettier.format(source, { parser: 'typescript', ...config });
}
```

Maybe this is something we can bring into the Prettier API?

Maybe something like this?

```typescript
async function formatWithConfig(source: string, parser: BuiltInParserName): Promise<string> {
	const configPath = await resolveConfigFile();
	const config = await resolveConfig(configPath);
	return format(source, { parser: 'typescript', ...config });
}
```

**Comment by thorn0** [comment]
> resolveConfig can be used to resolve configuration for a *given source file*, passing *its path* as the first argument

-- https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options

There is no need to call `resolveConfigFile` to use `resolveConfig`.

**Comment by cobraz** [comment]
> > resolveConfig can be used to resolve configuration for a _given source file_, passing _its path_ as the first argument
> 
> -- [prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options)
> 
> There is no need to call `resolveConfigFile` to use `resolveConfig`.

Gotcha! In that case, you'll do something like this?

```typescript
async function formatWithConfig(source: string, parser: BuiltInParserName): Promise<string> {
	const config = await resolveConfig(process.cwd());
	return format(source, { parser: 'typescript', ...config });
}
```

I can change #10700 if it's something you'd like to see in the Prettier API. :-)

**Comment by thorn0** [comment]
I'd avoid adding something like that to the API. I'm afraid increasing the number of methods will make the API rather more complex and confusing than simpler.

Besides, the argument of `resolveConfig` is supposed to be the name of a file to be formatted. If a directory name is passed instead, [configuration overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides) might get applied incorrectly. And what if the configuration file is right in the current directory? `resolveConfig(process.cwd())` will skip it. A file name is needed, even if such a file doesn't exist. Alternatively, you can use `resolveConfigFile` and pass the result as the `config` option to `resolveConfig`, but in that case the overrides will be ignored.

**Comment by fisker** [comment]
Let's remove `resolveConfigFile` in v3? It's never useful.

**Comment by duailibe** [comment]
To remove `resolveConfigFile` we would need to remove `--find-config-path` first.

**Comment by fisker** [comment]
We can keep it, but only use internally?  Like these https://github.com/prettier/prettier/blob/d09545952ef6cc37b1f0ad985ef0c1e3887b7e56/src/index.js#L69

**Comment by duailibe** [comment]
We're not interested in changing the `resolveConfig()` + `format()` API right now.

A convenient function that calls both steps can be implemented in user-land (and published as another package if someone thinks it's convenient). That would be something like:

```js
async function format(filepath) {
  const config = await prettier.resolveConfig(filepath);
  return prettier.format(await fs.readFile(filepath, "utf-8"), config);
}
```
