### ISSUE TITLE
Showing semicon but semicon option off

### ISSUE THREAD

**Issue by yansaan** [prettier/prettier#10697]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhujBACJwA2c8AFGABZQAqOYA1jQJT7AA6UPjCG1CAZwCeWfLR4BeAHy8BQ1TEhQxEagDpKEAOaiA7oRwx8jFm04wuK4Y4D0Tq6w40dqCACcAooSMopLSAMIMhFBQVPiKyoKOQi6W0GIWlOIwrAC2cLFEpub44ZHRlDq5YmKEBnBiDmrJQl40QfwJjU74apQ42eZI+ACMADQNzl1CAL72HRPdMDowDAjBUmD4lbFKhIUWlXqZsjpgPnCE8AAmOXUwhNkADrNqSV0aWrr6RhlpN8+JMGS1AsUAgxnyZAucB0oOMsnGr3wOFQMh+WT6eQA1PgAGwABnwACpcQTiUM8RT8AAefCwnjtF6AybqVLaaFfWgAA2YDBwYnwABJgCUolQYfc4FN8JcqDQ4JciKh4D5hvgGBB0CrQfgzmIHtBLpz-p0FiKyjoZcC4PC5oihLszBYxNQ4A9aAAOInDCl443zKYIpkzcYzG3TAQgEYgCAPXCpZCgQg+HxggAKSYQYmQIEIlFMEizUYARj5ArYAMoPQI4KAGZAwHzoOBRuDZIvymWXAAykQM6BqcAAYr5shdcLXs8RSJGQAwYNlKAB1XnwPWBODlzPmHAAN3MEmzYCqM5rYjgPhgqdLBlHyFQubPUYAVmIAB4AIVLHhg5YlXZrcB3g+zYgC+r7ljWBjUAAiugEDwEBlCPiAVY+GePjZkWhDtpQM4PD4NYwIuOCXMsyDuniUb4RAZ6LqWDzZvhdTnjugFRgAjnB8BXjGWYoOIAC00TyvKM5nJxOBnFeNS3kg95ISBZ79IhyFiJBMFcYBcnAVGdxFsRpEMMgABMumljgvS1qEEDZLJIB1AArDO6Bnsw2F8fJyE7k2ACSUAyrA5anDgsYAIL+eWMASNQKmSlMQA)

```sh
# Options (if any):
--semi=false
```

**Input:**

```jsx
function autoDelete(chnTicket) {
		(async () => {
			console.log(await chnTicket)
                })()
}
```

**Output:**

```jsx
function autoDelete(chnTicket) {
  ;(async () => {
    console.log(await chnTicket)
  })()
}

```

**Expected behavior:**

**Comment by thorn0** [comment]
This works as intended. See https://prettier.io/docs/en/rationale.html#semicolons
