### ISSUE TITLE
Incorrect formatting with comment in empty object pattern

### ISSUE THREAD

**Issue by frederickfogerty** [prettier/prettier#10708]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCqA6VMwHQAmEAMgBSnAAEAhgDSWpKXDa64D07lkAtjwjFYwAvsICUlALwA+SgGcI-GAAsAllADmQ3HjgAbOXGyUTpnfsMVxYkLRAQADjFXQ5yUNQBOniAHcACl4IbijUer7UAJ5udqie1GAA1nAwAMoOCeoayDCeAK5wdnA8qHAEBGXE1Jp51BpwAGIQnjzUMM6ayCDUeTAQtiDKMDx6AOpq8HIZYHCpwarOAG4LkV1gcjEg6oaeMP7xGq3IAGZhhnYAVnIAHgBC8UkpqdT8xOpwJ2eFIFfXqVl6OAARTyEHgnwM3wynh2XVQ1FKegGDk86hgo1UBBUyAAHAAGOwoiCGUbxBxdFFwHaLD52ACOoPg+0cIW6cgAtFA4GUygNPHAGap+fs6kckKdIXZDDxVDl8t85ADgYyPuKvnYYAiMVjlMgAEwa+KqPRZADCijFICpAFYBnlDAAVBEhCXnECLAoASSgFVgqTAqKcAEEfakYJFARDDKIgA)

```sh
--parser babel
```

**Input:**

```jsx
bob
	.doL(({ a, b: {
		// comment
	}}) => something
		.else
      	.else({}))
```

**Output:**

```jsx
bob.doL(({ a, b: {
    // comment} }) => something.else.else({}));

```

**Expected behavior:**
Unsure what the "correct" behaviour is here, but definitely the comment needs to be on its own line, so something like this could work

```jsx
bob.doL(({ a, b: {
    // comment
    }}) => something.else.else({}));

```

**Comment by thorn0** [comment]
Closely related: https://github.com/prettier/prettier/issues/7518

**Comment by frederickfogerty** [comment]
Thanks @thorn0!
