### ISSUE TITLE
Disabling atom plugin in specific projects

### ISSUE THREAD

**Issue by IljaDaderko** [prettier/prettier#1071]
Hi,

I've started using prettier in my personal projects and it is really helping out with code formatting. I am using atom package and have following problem.

As it is my main editor I also use it for my work where we haven't currently introduced prettier, as I have it configured to format on save it causes lint errors in work project, hence I need to enable and disable the package when switching between personal and work projects.

I wanted to check if there is a way to disable prettier's atom package automatically in specific projects somehow?

**Comment by yamafaktory** [comment]
Hi @IljaDaderko, can you directly ask that question in the related project https://github.com/jlongster/prettier-atom. Please refer to https://github.com/prettier/prettier/issues/1063#issuecomment-288113555. Thanks a lot!

**Comment by IljaDaderko** [comment]
Related issue in `prettier-atom` project: [#98 (issue)](https://github.com/jlongster/prettier-atom/issues/98)
