### ISSUE TITLE
Deletes space when Emoji is used on markdown

### ISSUE THREAD

**Issue by thanpolas** [prettier/prettier#10713]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOBDAJnATgHSgF4TTDCA+AAgCobBOQkHg-qqgOQnjqSoBUALOFQAyEAOYBhaPAAeMKhABmVGAKpg+ASwA2WKhqgBnGBihg4AGioB3bVqqiIyvrggBXUXyoYtdlYIC2GlhYWnBWGLiCJrpgrkYQ-vKuMAAOyVQKrqYwGtAGVDgK+nC6+k6CKREIcvpGJmYAdCDmIBApOXnIoBEuVgAKVYbIIN7hAJ4GzSAARrgYYADWcDAAypVg+qLIMLiuFiBw-tMlOFhCJqKuGKJwAGIQuP4YMDlQWygYyRBTfDD+WgB1TTwAzrOArBAGDQ5ABu0LGwzABkmLVqeBgfTmoieyAU3gM+wAVgZpAAhOaLZYrDD+OBCYq4-FEkkrTahACKrg4cEZWgJLUquAJuGGT1wCywECsUCmKVw+hgAKCKmQAA4AAwClwEgFzFLDOVwYUwnktACOXPgmLakw+BgAtFA4CUSlNIhaNJFMdccUg8Xz9gTAttdoG2XBOdzefyQMZpkqsCqkAAmFo7DDaTaSfy+g4GACsUzicB4GGmtv9MZhewAklAcLAVmB5e0AIL1lYwMahaNwAC+faAA)

```sh
# Options (if any):
    "singleQuote": true,
    "trailingComma": "all"
```

**Input:**

```markdown
> **ℹ️  Note**: The LogContext
```

**Output:**

> **ℹ️ Note**: The LogContext

![prettier-emoji-bug](https://user-images.githubusercontent.com/458813/115016229-78586a80-9ebd-11eb-838f-39226ada3986.gif)

**Expected behavior:**

Should leave the space between the emoji and the next work as is, and not remove it.

**Comment by thorn0** [comment]
There is still one space left. Replacing multiple spaces with one is okay in Markdown. It doesn't have any effect on the rendered result.

**Comment by thanpolas** [comment]
yea, you are right... VSC rendering confused me, sorry.
