### ISSUE TITLE
Spurious {" "} introduced

### ISSUE THREAD

**Issue by houshuang** [prettier/prettier#1072]
Currently, this line (which compiles fine, and does what it's supposed to)

```
<font size={-3}><i>Starting at minute {graphActivity.startTime}, running for {graphActivity.length} to minute {graphActivity.startTime + graphActivity.length}</i></font>
```

gets transformed into this:

```
<font size={-3}>
  <i>
    Starting at minute
    {" "}
    {graphActivity.startTime}
    , running for
    {" "}
    {graphActivity.length}
    {" "}
    to minute
    {" "}
    {graphActivity.startTime + graphActivity.length}
  </i>
</font>;
```

...which is not what I had expected. 

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cfont%20size%3D%7B-3%7D%3E%3Ci%3EStarting%20at%20minute%20%7BgraphActivity.startTime%7D%2C%20running%20for%20%7BgraphActivity.length%7D%20to%20minute%20%7BgraphActivity.startTime%20%2B%20graphActivity.length%7D%3C%2Fi%3E%3C%2Ffont%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by houshuang** [comment]
For some reason, this gets left alone:

```
                  <i>
                    Starting at minute {graphActivity.startTime}, running for
                    {graphActivity.length} to minute
                    {graphActivity.startTime + graphActivity.length}
                  </i>
```

**Comment by yamafaktory** [comment]
Hi @houshuang, I guess this is related to this closed issue https://github.com/prettier/prettier/issues/1061.

**Comment by houshuang** [comment]
Yeah, I realize it makes sense... And why the second example gets "left alone" :) However, it looks horrible, and is definitively not what I expected... Not sure how to fix it. Would prefer to just leave the line alone, but understand that Prettier wants to enforce line-length...

**Comment by jlongster** [comment]
I've actually noticed this too. @rattrayalex Do you have any strong opinions about this? Is there any way we could be a little more lenient on this? I don't know what we could do without actually changing semantics, but it's worth talking about.

**Comment by rattrayalex** [comment]
Yeah, this has been discussed in a couple other threads... mostly https://github.com/prettier/prettier/issues/1021 and https://github.com/prettier/prettier/issues/963 (#1061 is actually different). 

It'd be nice to merge the conversation before further discussion – @jlongster would you be willing to pick a thread to merge into so we can close the other two issues?

**Comment by rattrayalex** [comment]
(tl;dr, I hope we fix this, but we'll probably need to introduce a new primitive)

**Comment by jlongster** [comment]
Let's merge on #963 as it seems to have the most discussion. Thanks!
