### ISSUE TITLE
prettier breaks typescript

### ISSUE THREAD

**Issue by aprilmintacpineda** [prettier/prettier#10735]
**Prettier 2.2.1**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtNcA2cY8AJgDSZ4wDKBRpAupgLyYBKcAhsQHQCueajE7wAPBABGAK3qYAPpih98+AHwAKADpRMi5fm0BKANwgyICAAcYAS3TJQnAE5OIAdwAKzhGmQhO+G6cAJ6+5hJO3ADWcDSW3DZQAObIME58cOZwALYScCQk+QAynMl8nElwAGIQTtkitsl+nHwwEGYgABYw2fgA6p028GjxYHC0UGhDNgBuQ8F+YGhhIIl4TjAekUn1yABmAXjmUmgAHgBCkWAxNJzZcEWJcPuHmSAnp9SJSYQAinwQeAvfBHEDxJzrPwSTh5fAdSxORIwPo2EgwTrIAAcAAZzAiIHg+pFLH4EXB1jNnuYAI4A+BbKy+FCcNAAWigcHy+Q6TjgtJsvK2FV2SAOILeeGyNlS6Ql3z+dOeote5mEEhRaIxSAATKrIjZ8N8AMIQbIikDkgCsHQEcAAKjCmWLQTMMgBJKCFWDUMCI6wAQU9QmChGBeAAvuGgA

```sh
# Options (if any):
--single-quote
```

**Input:**

```tsx
const [selected, setSelected] = React.useState<object | null>(
  null
);
```

**Output:**

```tsx
const [selected, setSelected] = (React.useState < object) | (null > null);
```

**Expected behavior:**

**Comment by thorn0** [comment]
You forgot to specify a [parser](https://prettier.io/docs/en/options.html#parser).
