### ISSUE TITLE
Invalid nested tags

### ISSUE THREAD

**Issue by leoseccia** [prettier/prettier#10734]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeA-ADwLYBsAEAbnAE4DOAltALwA6IAjAHQAM9+CkAJhVAOZ0QAVQAqAMQC0ADnroAfKjAwYJJGAowAhjAgl8OXFDKCAFsoAOSAPRX42cwFcSFKwbJgTcbJrJXIsBBgrMhNNEjguKwAjHzgrBit2AyM1XB9KADMAT1MLa1svR2dXPHdPb19-eFhg0PDIsDSyTIowbSooeMSQfTwUpRVBJygkTAl8OyKKNWhqmDUNbV0kELCIslJCVrgyJAYkvt2uMFyYSxsi3CZdPitjqzhcL0DfZgSDwyOIE-ozM-zJk4XG4PF4fH5ZoFamtIlxvg5sIEJE9iLgJIitFxtJouvQFHCwEgMZosVp8d8kATeBkIPgCRIqkjIA5YCQcvQhABlPGKJqZLKpdIUDKtdrQCR8EjmfCNdJlZ6CQxMXhcOCYXh8CTwEjYMg82XNYUCg2UOwKYnmuBaDRefBQTSIwSaczmXAUCJRLLsQiaXAOOCmBGaKDsKyW612O0OgP0XgwDRPb2+-2CDK+jahhRWC2oHTmVpIPOtABKcAypE4cHwfAcFC4SBrdaGJBGRcJAEEAEIAYUzqD8fKNgsNZv7JqH45FbXj4sl5izBMp32pEAXFOJpM0WYGqnUWh0JDkIAANCAIOYZ0ZkKAwiQIAB3AAKayvKF9980WTIJ5AURImjAABrK1OXMACNWQFR-VPLwogiVUuAAGWDGtND4OAxF0bxlAgt8HB0H8zDwAB1EwbTIMCwDgTkEFNCgthgLJkHAZof14DYSBgR9-z4bxkDTXANlPAArMhME7f8gJA6NEN4OB+PTOARLEzkNSeABFBwIHgBTBKUkAwPIUhmKI3Af3MZxYGIusYBMZApBYU8LIgDZiP-cxmIsnZNnk08AEctPgbjz2-N8yAkKA4AiCIf3CAKKHCbi0L4pABKEkANmwChIJIaCMrUuBNO0+TUsU08tCiayuFs5AACZyv-Cg3X4bsIGwFKQB2ABWH8HA2ERNCiUK0v0wh-QASSgVVYE5MBnAvdsps5Rinl0jYAF91qAA)

```sh
--parser html
```

**Input:**

```html
<?xml version="1.0" encoding="UTF-8"?><cttr:citator xmlns="http://tempuri/xmlschemas/content/shared/base/1/" xmlns:classify="http://tempuri/xmlschemas/content/shared/classification/1/" xmlns:cttr="urn:x- tempuri:content:citator:sharedservices:1" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:doc="http://tempuri/xmlschemas/content/shared/document-level-metadata/1/"><doc:metadata><doc:docinfo doc-content-country="US"><classify:classification-grp classscheme="ln.indexing-terms"><classify:classitem><meta><metaitem name="appliedby" value="human" /><metaitem name="intitle" value="false" /></meta><topic:topicReference guid:guid="urn:topic:ABC" /></classify:classitem></classify:classification-grp></doc:docinfo></doc:metadata></cttr:citator>
```

**Output:**

```html
<?xml version="1.0" encoding="UTF-8"?><cttr:citator
  xmlns="http://tempuri/xmlschemas/content/shared/base/1/"
  xmlns:classify="http://tempuri/xmlschemas/content/shared/classification/1/"
  xmlns:cttr="urn:x- tempuri:content:citator:sharedservices:1"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:doc="http://tempuri/xmlschemas/content/shared/document-level-metadata/1/"
  ><doc:metadata
    ><doc:docinfo doc-content-country="US"
      ><classify:classification-grp classscheme="ln.indexing-terms"
        ><classify:classitem
          ><meta
            <metaitem name="appliedby" value="human" />
            <metaitem name="intitle" value="false" />/><topic:topicReference
            guid:guid="urn:topic:ABC" /></classify:classitem></classify:classification-grp></doc:docinfo></doc:metadata
></cttr:citator>

```

**Expected behavior:**

**Comment by thorn0** [comment]
Prettier core doesn't support XML. There is a plugin for this: https://github.com/prettier/plugin-xml
