### ISSUE TITLE
JSDoc typedef parentheses removed around functions

### ISSUE THREAD

**Issue by wooorm** [prettier/prettier#10733]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgBAARgTwAc4tgBDAXy3VQB0oA3MgJyzKwF4sAKerLDNjxESwAEZUafLADMArlDAwAltCxjuASlIV6mkABoQEQiugBnZKBbMIAdwAKLBJZRkANnbL5LRsczIwAGs4GABlQkDlKABzZBhmOTgjOABbMTgAE0ysgBkyWLkyGLgAMQhmVLIYFVjkEDI5GAhDEAALGFT3AHU25XhzSLA4MJd+5QZ+-Hqwc18QaPM4ZhgHAJiq5BkPJaMAK3MADwAhAODQsLJUuFzouC2d5JADw7DomPc4AEU5CHgH9y7ECRZhLZj1MRkDLuVqEZjRGDdZSZGBtZAADgADEY4RAlt0AoR6nC4GCGPcjABHX7wNYmVwNcwAWigcCyWVazDg1OUXLWxU2SG2gKeS1SyniiVF70+Pz+9yFjyMMChSJRaKQACZlQFlO53gBhCCpQUgUkAVlaciWABUoa5hUCGEkAJJQHKwMJgeGmACC7rCBE+AKWFAoQA)

```sh
--parser babel
```

**Input:**

```jsx
/** @type {a} */
var a = (
  /** @type {b} */
  function b() {}
)
```

**Output:**

```jsx
/** @type {a} */
var a =
  /** @type {b} */
  function b() {};
```

**Expected behavior:**

```jsx
/** @type {a} */
var a = (
  /** @type {b} */
  function b() {};
)
```

---

Somewhat similar to: https://github.com/prettier/prettier/issues/6120.

A practical example of why this is needed is for overloading functions:

```js
/**
 * @jsdoc stuff
 */
// prettier-ignore
export var u = (
  /**
   * @jsdoc stuff
   */
  function (type, props, value) {
  // …
```

^-- I’d prefer not to have to resort to the prettier-ignore comment!

**Comment by thorn0** [comment]
> `var u = /* @type {function(): undefined} */ (function () {})`

It's not a JSDoc comment if it doesn't start with `/**`. ;)

**Comment by wooorm** [comment]
wait...

**Comment by wooorm** [comment]
OK, fixed the issue with a working reproduction of my problem.  😅 Nice catch, thanks!

**Comment by thorn0** [comment]
See https://github.com/prettier/prettier/issues/8096#issuecomment-616516093

**Comment by wooorm** [comment]
Hmm. Pinging @ChristianMurphy and @remcohaszing because I’m out of my depth here.

**Comment by thorn0** [comment]
The correct syntax for what you're after (nested type assertions) is:
```js
var a = /** @type {a} */ (
  /** @type {b} */
  function b() {}
)
```
It corresponds to the following TypeScript syntax:
```ts
var a = function b() {} as b as a;
```
Whereas the original input corresponds to a different thing:
```ts
var a: a = function b() {} as b;
```
At least, it's supposed to be like this. But because of the bug, TS treats the original input as nested type assertions.

**Comment by wooorm** [comment]
Not the prettiest formatting, but it works!

```js
export var u = /**
 * @jsdoc stuff
 */ (
  /**
   * @jsdoc stuff
   */
  function (type, props, value) {
    …
```

Awesome, thanks!

**Comment by thorn0** [comment]
The upcoming release handles this better. Meanwhile you can move each opening parens to a new line to improve the formatting:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACANwENs8BXPAXjwHoAqOgHSjzrwAEYBPDOPYAM4wyAMxEBfZqxpS8cgBSz6TFnLacefQcLGTV0vLLzyRZKGBgBLaMe68ANHgzYIGAY+IAbMnACU-cV9mXwBuEHsQVytoAWRQEhcAdwAFEgRYlCJPRKIuWIiAI2wiMABrOBgAZQwSyygAc2QYbB8IuABbArgAE26egBkiBrIiergAMRx2ohgrBuQQIjIYCHCQAAsYds8AdXXLeAEasDhK9IPLAgOuBbABfJA6gThcZOL66eQRLOeIgCsBGgAELFMoVSpEdpwfp1OBfH5wf6Ayp1eqeOAARTIEHg8M8vxANWwz2wCwKRC6njWzjqMB2lm6MHWyAAHAAGCLOCDPHbFDALZxwEkEOERACO2Pgb1cGUWAgAtFA4D0emtsHAJZZ1W9Rp8kN98YiQM92pYmi0jQJUeisTi4fqEREYBT6YzmUgAExO4qWTyogDCEHaetQAgArGsyM8ACoUjIGgkEHwASSgfVglTA2EsGBgAEE05VuOi8c9xOIgA)

```sh
--parser babel
```

**Input:**

```jsx
export var u = /**
 * @type {stuff}
 */
    (
  /**
   * @type {stuff}
   */ 
   (function (type, props, value) {})
);
```

**Output:**

```jsx
export var u =
  /**
   * @type {stuff}
   */
  (
    /**
     * @type {stuff}
     */
    (function (type, props, value) {})
  );

```

**Comment by wooorm** [comment]
oh that’s perfect! ✨
