### ISSUE TITLE
Experimental feature request: reverse colon and space order for types in typescript

### ISSUE THREAD

**Issue by Norfeldt** [prettier/prettier#10760]
I really really enjoy prettier - it has truly made a difference for my productivity. Thank you for that ❤️❤️

This is a far reach feature request and I do not have high expectations for it. But please hear me out and consider it.

**Input:**

```tsx
const isPrettierAwesome: Boolean = true
```

**My Dream ❤️ Output:**

```jsx

const isPrettierAwesome :Boolean = true

```

Having the type written like a Ruby :symbol makes it like sticking in a one-word label and avoid the confusion that this is not a renamed destruct or some sort of fancy object writing.

The syntax is valid..

**Comment by thorn0** [comment]
Please see here: https://prettier.io/docs/en/option-philosophy.html

> as option requests are out of scope for Prettier, they will be closed without discussion
