### ISSUE TITLE
Reserved words as object keys have quotes removed

### ISSUE THREAD

**Issue by livgust** [prettier/prettier#10762]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8MHkBGAVnGFgLybAA6UmmAJnAGYCGArgDYxKasdpwANJgD0IzAHc4mNAAsInepgCObCPGyyAlmhp0YAJzZwefAcLGTpchRyUAHAxHwt8HAJ4q1GmNrTYICD1MFh4qEHxwmgBfGhpIKAwQqHVZOAMAFTg8IhJySmDwxlZOGHDTFn4hUXFfHRl5RRkYFk9VdTh6QpBDY3LeSvMa5KU6-2g4YJYU33SAaTh3MJBp1PSANUq+kBiQQRAIexgtdGRQFgMnCQAFC4Q0ZBWOCVaH-fwDFjAAazgYAGV7F8tFAAObIXpCEBwAC2+E6jHoABlpqC2CxQXAAGIQAwwlgwY5gx7sGAQPYgWQwGEcADq2hwQLAcH+9y0xwAbuz3I8wGg3iAQQIDDBrp9QfjkGYoYQ0AAPABCnx+f3+LBhcCRILgUsGMvl-xBoI4cAAit4dUhpfsgQZhY8XPCOBTHCCYLStPRfMgABwABhtTgEtM+9kejmy6Q5Ov27XgYsODxQLDQAFooHBOp0KQY4KotLmxRjJVa9fsBDCtBCjFC0EaTeaOrqqvsWvgPV7ZMgAEytz5aDhGgDCEBhJehaAArBS2AIMq4k9aQBzjABJKCMWD-MAGLRHACCG-+MHcJubAmi0SAA)

```sh
--parser babel
```

**Input:**

```jsx
const testObject = {
  default: false, // we should quote this
  true: false, // we should probably quote this too
  a: "b"
}

const anotherTestObject = {
  "default": false, // this should stay quoted
  "true": false, // and this one
  anotherKey: "anotherValue"
}
```

**Output:**

```jsx
const testObject = {
  default: false, // we should quote this
  true: false, // we should probably quote this too
  a: "b",
};

const anotherTestObject = {
  default: false, // this should stay quoted
  true: false, // and this one
  anotherKey: "anotherValue",
};

```
My exact use case is that I have a project using [`convict`](https://www.npmjs.com/package/convict) that uses objects as a configuration with a _required_ `default` key. When I have it unquoted, `eslint` gets mad because it's a reserved word, and when I quote it, `prettier` removes the quotes.

**Expected behavior:**
Reserved words in javascript should not be unquoted when they are used as object keys. I'm happy to make a PR to fix this - would it be OK to just have a list of [all the reserved words](https://www.w3schools.com/js/js_reserved.asp) and quote them if they're being used as keys in a JS object?

**Comment by thorn0** [comment]
See https://stackoverflow.com/questions/7022397/using-reserved-words-as-property-names-revisited
This works as expected. If you happen to use ECMAScript older than ES5 and need to keep the quotes, set the option `quoteProps` to `"preserve"`.

**Comment by thorn0** [comment]
As for ESLint, use https://github.com/prettier/eslint-config-prettier to disable all its rules conflicting with Prettier.
