### ISSUE TITLE
Missing parentheses `for ((async) of []);`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#10777]
This is valid even in [main branch](https://deploy-preview-10775--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAzCAnABAChwQwGcBPKMASiwlSwG0BdcgbhABoQIAHGAS2kOSh8GDBADuABWEIBKfABsx+YgPYAjDPjABrODADKnLTygBzZDAwBXOOzgBbNXAAmzlwBl8Zq-lNwAYpj2+DC8Zsgg+FYwEGwgABYw9vIA6vE88IRGYHD6Mhk8AG4ZxBFghKogJoRwGDASmqbByKgKNewAVoQAHgBCmjp6+vj2cO4mcC1ttiBd3fompvJwAIpWEPBT8u0gRhg1GBFq+E7ycZwYJjApPM4w8cgAHAAM7BcQNSmanBEXcAeFSbsACO63gDS4skihAAtFA4C4XHEMHBQTwUQ1fM0kK1tjMavYeBZrPjFss1htJjjpuwYCcbncHkgAEy0zQ8eSLADCEHs2JA-wArHErDUAConWS4naFGwASSgblg+jAl24AEFFfoYMRllsagBfA1AA), [related babel pr](https://github.com/babel/babel/pull/13208)

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABAChwQwGcBPKMASiwlSwG0BdcgbhABoQIAHGAS2kOSh8GDBADuABWEIBKfABsx+YgPYAjDPjABrODADKnLTygBzZDAwBXOOzgBbNXAAmzlwBl8Zq-lNwAYpj2+DC8Zsgg+FYwEGwgABYw9vIA6vE88IRGYHD6Mhk8AG4ZxBFghKogJoRwGDASmqbByKgKNewAVoQAHgBCmjp6+vj2cO4mcC1ttiBd3fompvJwAIpWEPBT8u0gRhg1GBFq+E7ycZwYJjApPM4w8cgAHAAM7BcQNSmanBEXcAeFSbsACO63gDS4skihAAtFA4C4XHEMHBQTwUQ1fM0kK1tjMavYeBZrPjFss1htJjjpuwYCcbncHkgAEy0zQ8eSLADCEHs2JA-wArHErDUAConWS4naFGwASSgblg+jAl24AEFFfoYMRllsagBfA1AA)

```sh
--parser babel
```

**Input:**

```jsx
for ((async) of []);
```

**Output:**

```jsx
for (async of []);

```

**Second Output:**

```jsx
SyntaxError: Unexpected token, expected "=>" (1:15)
> 1 | for (async of []);
    |               ^
  2 | 
```

**Expected behavior:**

**Comment by Blakelist7** [comment]
Hey! new to Open-Source as well as prettier.

**Comment by thorn0** [comment]
The parens are also needed in `for ((let) of []);` and `for ((let.foo.bar) of []);`.

See https://tc39.es/ecma262/#sec-for-in-and-for-of-statements
