### ISSUE TITLE
A literal JS regex as a function param in a line over the printWidth limit with trailingComma set to "all" will have a comma erroneously inserted at the end

### ISSUE THREAD

**Issue by theblang** [prettier/prettier#10779]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEOUOMAFAJT7AA6U+9+AJAG44AmcEAzgHTSkByMABscYANYCANPgxZcBClVoNV+SFC4x8rDhACqAJQAy+ALxNSMABY4u5HgEMYMAE6C2zxwFpdnb+iuwgLkANwqavQaWjrsnACSACLmsXpGxjwAts5g1qQA9KQA-EjWLgAOXCXU1PnAAEwAvuRFxUgA7sAAzI01PC0AnhDoMOhtAEZwLX1tkJkAPpPkbTX57TnWNUXMZvOrywDaAHo1XABkALoA1OT5YRH0zeFQvVAgUiAQ5QqayKCOrlcEHaAAUAQguMgQI5mBB2O8QONXI4JHAYABlcooogAc2QbnQcA+cEykzYHDYxkcUBx6EcOLgADEIK5si5cVDHCMIAiyplhAB1WzwLhYsBwdEQkg4VgwAZQsBcSEfIhcOCuGAg5E47LIVCOYRqj4AKy4AA8AELI1EYxyZODGIhwPUGo0gU1m9G44RwACK6Ag8BdhqJICxrjVrih40ck2ECPKriIMAF7BsyAAjPUAAwfRPcOAC5HlKGJuCR5jOj4ARwD8C1X0hKEcXG8UDgcApCNccFrOB7WvpuqQ+pDHzVmRw+NchPH3r9dedI9doZgsdTbHTSAALB83I4cKIaQBhCCZYfQ4Txj7oNUAFVjTdHbuYhPiUA4sHRYCT3wAgh+6Jyj6wZqo0jRAA)

```sh
--parser babel
--print-width 120
--tab-width 4
--arrow-parens avoid
--trailing-comma all
```

**Input:**

```jsx
function init() {
    $videos.on('click', function () {
        const videoURL = $(this).attr('data-video-url');
        const videoID = videoURL.match(/(?:https?:\/{2})?(?:w{3}\.)?youtu(?:be)?\.(?:com|be)(?:\/watch\?v=|\/)([^\s&]+)/);
    });
}

```

**Output:**

```jsx
function init() {
    $videos.on("click", function () {
        const videoURL = $(this).attr("data-video-url");
        const videoID = videoURL.match(
            /(?:https?:\/{2})?(?:w{3}\.)?youtu(?:be)?\.(?:com|be)(?:\/watch\?v=|\/)([^\s&]+)/,
        );
    });
}

```

**Expected behavior:**

There should be no trailing comma in this case, because the comma seems to break the literal regex. It doesn't break the JS parser, but the regex doesn't work right (that in of itself is interesting to me, but I'm not going to postulate further as to why).

I can see how the behavior is happening, because something like the following is valid:

```
videoUrl.match(
    areallylongparamnameareallylongparamnameareallylongparamnameareallylongparamname,
);
```

But I'm guessing there should be an exception for a literal regex param?

**Comment by thorn0** [comment]
> because the comma seems to break the literal regex

It's not the case.

**Comment by theblang** [comment]
@thorn0 My apologies, it seems we had an unrelated red herring that caused us to believe this regex literal was causing an issue.
