### ISSUE TITLE
how to vscode prettier force line wrap

### ISSUE THREAD

**Issue by wjx0912** [prettier/prettier#10778]
my vscode settings:

    "prettier.printWidth": 100,
    "prettier.tabWidth": 4,

my source code:

    if (200 != response.status)
        return '';

the prettier format it to(it seems ugly):

    if (200 != response.status) return '';

how to force line wrap (force format two line)?

**Comment by Sarbjitgrewaltws** [comment]
Open VSC and go to settings then Extensions and click on "prettier" there's a check box ticked under Prettier: 'Require Config'. If that's unchecked it will break your lines automatically.
