### ISSUE TITLE
Odd object multi-lining

### ISSUE THREAD

**Issue by chrisui** [prettier/prettier#1077]
One of the formatting choices which has popped up in our first play with prettier as slightly odd is the automatic multi-lining of multi-keyed objects. Note this has occured in flow type objects.

For example we believe the following

```
  queries: {
    invoices:
      | {
          ready: true,
          pageInfo: {total: number},
        }
      | {ready: false},
  },
```

would be better as

```
  queries: {
    invoices:
      | {ready: true, pageInfo: {total: number}}
      | {ready: false},
  },
```

**Comment by chrisui** [comment]
Actually just had a quick play around with this and it seems we get different output based on the original formatting. This seems super odd!

https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Queries%20%3D%20%7B%5Cn%20%20%20%20invoices%3A%5Cn%20%20%20%20%20%20%7C%20%7Bready%3A%20true%2C%20pageInfo%3A%20%7Btotal%3A%20number%7D%7D%5Cn%20%20%20%20%20%20%7C%20%7Bready%3A%20false%7D%2C%5Cn%20%20%7D%3B%5Cn%5Cntype%20Queries%20%3D%20%7B%5Cn%20%20invoices%3A%5Cn%20%20%20%20%7C%20%7B%5Cn%20%20%20%20%20%20%20%20ready%3A%20true%2C%5Cn%20%20%20%20%20%20%20%20pageInfo%3A%20%7Btotal%3A%20number%7D%2C%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7C%20%7Bready%3A%20false%7D%2C%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Yes, for objects, if there is a \n inside, we keep it expanded. This wasn't intended for flow types but the ast node for those in flow types is used by sooo many different contexts and changes a ton of snapshots so we need to manually go through and figure out for each case what we want to do with them.

This behavior should also be properly documented which it isn't right now!

**Comment by tomekwi** [comment]
@chrisui Deciding between variants is something I know and love from elm-format as well. An extra bit of whitespace inside a record makes elm-format conclude that you _want_ it  more fleshed out rather than concise.

**Comment by 0x24a537r9** [comment]
For a non-Flow example, I would also hope that the project object be collapse into one line with:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22descriptionLineFocused%20%3D%20foo(%5Cn%20%20'Add%20to%20party'%2C%5Cn%20%20'Text%20shown%20on%20hovering%20Friendlist%20item'%2C%5Cn%20%20%7B%5Cn%20%20%20%20project%3A%20'my-cool-project'%2C%5Cn%20%20%7D%2C%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by jlongster** [comment]
It's a tough call but this is one place where we allowed user input because objects are used for so many different things in JS. I actually agree with you and I wish we collapsed it, but we've decided to allow that flexibility and it's helped a lot of people adopt prettier. I don't think we're going to go back on that decision unfortunately.

**Comment by chrisui** [comment]
Super interesting and I can see the value of allowing this flexibility especially after @vjeux's talk at react london the other day as well.

Is it possible that another place which you would to have somewhat similar behaviour is union types across multiple lines?

"If the type annotation starts with a newline and pipe then the developer wants each type on a new line"

https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Person%20%3D%20%5Cn%20%20%7C%20%7Bsome%3A%20Object%7D%5Cn%20%20%7C%20%7Bsome%3A%20Object%7D%5Cn%20%20%7C%20%7Bsome%3A%20Object%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
We are not going to change the implementation for this and explained why it's there in the issue, so I'm going to go ahead and close it.
