### ISSUE TITLE
Prettier refuses to format TSX code which contains namespace with TypeScript parser.

### ISSUE THREAD

**Issue by mhevery** [prettier/prettier#10786]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAKgTwA5wDKYATgJZ4wZ4A2AhjgOYkQCuUAJkhgBYwx4AzknQB3cQDoY+OINIUY9KIwkQSjVLQYB+AMSQOcVAFkAmnFEdGALzIBBAEwBhALYAhAAweAigAljdgCqdnB2AFKMhKIA4gAs4aJ2rKZ0AEamdnSiAGLx9gCSogCiAVDRjAAKUH4QHBwA6m4A0vl2ADpQ6Ng8ZIIYvRgAbnQ0ZBzYMsTklBiCcHAYo1AA1hhpEINwEh2QUIIQNFs0EIwAFKcAPBxkgxiGYDRIAGYQEBgAvBjAbSCpdCQ-AC+AD4LqhroNgQBKKEAbg6HS65ioMB6fSedDIND6qIWeH+cxI2ygHRAABoQBBKGRoIJkKB-ixRBV-gg6SgRqIGHSKakSHQwMs4DBCPiwGRlMgYCRWHAKXAXKk4HVlQAZOjKVh0RhwbJqFx0fgSxjIEB0VgwCDkkB8Fw0eo9eCCMVENlkGA3d04U1gQQ8kASwkwCr8xgG5AY7FykAAK0EAA83PzBcLCHQXHBVRK4BGRnMKXH44RjYdvKwIPBc1GKfiSITTdICHJpjBrXhyLB6mNUcgABweGssOb1fl4U3t2RwEiba0AR3L8BDVPZZsEAFooPNDBxrSQ4POyHuQ9rw8889G5i4yFKZReS3AyxWc2fqyAYGkuxwe0gHBTpZilkYJwIBcU8QFkABWa1WDmLA0nZSN8xAQZZXyTgEBFeRKDsThCGkQ4qzmQFASAA)

```sh
--parser typescript
```

**Input:**

```tsx
// TypeScript playground: https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUAeAJgSwG4AJwAuYabYAawF4AiAIwEMAnGgPnQHoddWBKIA
// This is valid TypeScript see link above.
console.log((<div decl:foo = {"bar"}></div>));

// Yet this fails the parser.


```

**Output:**

```tsx
SyntaxError: '>' expected. (3:19)
  1 | // TypeScript playground: https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUAeAJgSwG4AJwAuYabYAawF4AiAIwEMAnGgPnQHoddWBKIA
  2 | // This is valid TypeScript see link above.
> 3 | console.log((<div decl:foo = {"bar"}></div>));
    |                   ^
  4 | 
  5 | // Yet this fails the parser.
  6 | 
```

**Expected behavior:**

**Comment by sosukesuzuki** [comment]
Workaround: you can use `babel-ts` parser
