### ISSUE TITLE
bug on export from

### ISSUE THREAD

**Issue by sibelius** [prettier/prettier#1078]
prettier version: ^0.22.0

Prettier command
`prettier --write --single-quote true --trailing-comma all --print-width 120`

input
```jsx
export User, { USER_ROLE } from './models/User';
```

output
```jsx
export { User, USER_ROLE } from './models/User';
```

expected output
```jsx
export User, { USER_ROLE } from './models/User';
```

.babelrc

```jsx
{
  "plugins": [
    ["transform-flow-strip-types"]
  ],
  "presets": ["es2015", "stage-0"]
}
```
mac os x sierra
node 6.10.0

**Comment by existentialism** [comment]
@sibelius you see https://github.com/prettier/prettier/issues/995 (and the fix: https://github.com/prettier/prettier/pull/998)?

**Comment by sibelius** [comment]
Tks, I'll close and wait the next release
