### ISSUE TITLE
trailingComma option is not applied after spread in object

### ISSUE THREAD

**Issue by jonathanewerner** [prettier/prettier#1079]
```diff
- const {
-   foo,
-   baz,
-   ...bar
- } = this.props
+ const {
+   foo,
+   baz,
+   ...bar
+ } = this.props;
```

I'd expect a comma after `...bar` when `trailingComma` flag is set, no?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20%7B%5Cn%20%20foo%2C%5Cn%20%20baz%2C%5Cn%20%20...bar%5Cn%7D%20%3D%20this.props%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by danharper** [comment]
A trailing comma isn't allowed after the rest operator.

> The rationale for this is that the use case for trailing comma is that you can add something at the end without affecting the line above. E.g. for version control software. However, that is never the case here.
> https://github.com/babel/babylon/pull/149#issuecomment-250601695

(It's currently parsed by Babel v6, but only for back-compat reasons. Babel v7 will be spec compliant and disallow it)

**Comment by jonathanewerner** [comment]
Nice, thanks for the info!

**Comment by thgreasi** [comment]
How about typescript? tslint reports it as an error and I have to use a line ignore comment

https://prettier.io/playground/#%7B%22content%22%3A%22%5Cnexport%20const%20foo%20%3D%20(%5Cn%5Cta%3A%20any%2C%5Cn%5Ct...rest%3A%20any%5B%5D%2C%20%2F%2F%20tslint%3Adisable-line%20trailing-comma%5Cn)%20%3D%3E%20%7B%7D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
@thgreasi can you open an issue on tslint so that they can fix it?

**Comment by thgreasi** [comment]
Opened https://github.com/palantir/tslint/issues/3147 for this.
