### ISSUE TITLE
TypeScript union types declaratios starting with `|` (pipe)

### ISSUE THREAD

**Issue by mcjazzyfunky** [prettier/prettier#10806]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAGtgXmwE0AeAHSm2wB9tyQBDBy6uhgIxatvpAGFuAPgDcrerEw58RMuPZMG2APTL5fLiHUMwwsVEros2AIKFsAIQo8FzLVFGVDU0+avbFIFWof7KkKABnGGwAgDMASwBzc2BxRiRsMKhrajY+O3F0zm403h1c7CEACgBKSgBfPygA4NDoSJiiOJ4EpJSs-M9vToVNXr5de2oS8qgqkAAaEAgMGAjoQORQRgAnVYgAdwAFNYQllEYAG03GNCXpjlXGMABrOBgAZQwbiKgo5BhVgFc4abgALYcOAAExBoIAMox3t9GFE4AAxCCrAGMGDzd7IJjfGAQKYgAAWMABRwA6gSIvBAi8wHBHvtKREAG6UtBYsCBC4gN6BOCrGDba5RVHIMLHXnTABWgQAHhZrncHo9GAC4BC3nBReK-iBpTLHm8okc4ABFb4QeBao4SkAvVa81ZYoxwQJgVYROb4jDu2CkiIgmAE5AADgADNNvRBeaTrhgsd6XXymZrpgBHc3wQWzA5MQIAWigcFBoPxqzg6YiZcFcJFSDF1p1vIBEU+P0bhuNZotmrr2umMEYHD9AaDSAATP3rhEjob+BAAbWQFBoCmQN9eQAVQcHes2pm-ACSUHBsEebo9MBMx8e6GNVt5FQqQA)

```sh
--parser typescript
--trailing-comma none
```

**Input:**

```tsx
type X = Y<
  | "a"
  | "b"
  | "C"
>;
  
type X = Y<
  | "a" //
  | "b"
  | "c"
>;

type A = B<
  | "a"
>;

type A = B<
  | "a" //
>;

const config = {
  a: fn<
    | "a"
    | "b"
    | "c"
  >()
};

const config = {
  a: fn<
    | "a" //
    | "b"
    | "c"
  >()
};
```

**Output:**

```tsx
type X = Y<"a" | "b" | "C">;

type X = Y<
  | "a" //
  | "b"
  | "c"
>;

type A = B<"a">;

type A = B<"a">; //

const config = {
  a: fn<"a" | "b" | "c">()
};

const config = {
  a: fn<
    | "a" //
    | "b"
    | "c"
  >()
};

```

**Expected behavior:**
I think it would make much more sense if all of the above example independent of that `//` workaround started a new line for each `|` as the first part of the union type expression is starting already with a `|`. If the first part of the union type expression is not starting with an `|` then everything should behave as before.Why should I add an unnecessary pipe in front of the union type expression if not for the case that I want the expression splitted on different lines.

Remark: I only mention union types here and not intersection types as prettier formats (for whatever reasons) union types differently than union types in certain cases and the issue mentioned above is far more important for union types, I guess.

**Comment by thorn0** [comment]
See https://prettier.io/docs/en/option-philosophy.html

> Please note that as option requests are out of scope for Prettier, they will be closed without discussion. **The same applies to requests to preserve elements of input formatting** (e.g. line breaks) since that’s nothing else but an option in disguise with all the downsides of “real” options. 

Also please read "A note on formatting reversibility" on this page: https://prettier.io/docs/en/rationale.html
