### ISSUE TITLE
Multiline strings leaves closing quote in wrong place

### ISSUE THREAD

**Issue by trotzig** [prettier/prettier#1081]
I have this bit of jsx code: 

```jsx
<Foo 
  someMultilineString={`
   Foo bar baz. Foo bar baz. Foo bar baz. Foo bar baz. Foo bar baz. 
   Foo bar baz. Foo bar baz. Foo bar baz. Foo bar baz.  
  `}
>
  body
</Foo>
```

When I run it through prettier, it ends up like this: 

```jsx
<Foo
  someMultilineString={
    `
   Foo bar baz. Foo bar baz. Foo bar baz. Foo bar baz. Foo bar baz.
   Foo bar baz. Foo bar baz. Foo bar baz. Foo bar baz.
  `
  }
>
  body
</Foo>
```

Notice how the closing backtick is indented one step less than the opening backtick. 

I think the way I would prefer it to be formatted is to keep the opening backtick on the same line as the attribute, and the closing backtick could be together with the closing curly  (as in the before-block).

**Comment by trotzig** [comment]
I changed the title to not mention jsx specifically, because I found this in [another one of my projects](https://github.com/Galooshi/import-js) (in a regular js file): 

```js
it('finds exports from json', () => {
  expect(
    findExports(`
{
  "foo": {
    "foobar": 1
  },
  "bar": "Brown's bar"
}
    `, '/path/to/file.json'),
  ).toEqual({
    named: ['foo', 'bar'],
    hasDefault: true,
  });
});
```

gets transformed to 

```js
it('finds exports from json', () => {
  expect(
    findExports(
      `
{
  "foo": {
    "foobar": 1
  },
  "bar": "Brown's bar"
}
    `,
      '/path/to/file.json'
    )
  ).toEqual({
    named: ['foo', 'bar'],
    hasDefault: true,
  });
});
```

It's a little hard to see formatting in this example because the string contains json, sorry about that.

**Comment by vjeux** [comment]
@jlongster looks like a lot of people are running into it. Maybe it's worth reviving https://github.com/prettier/prettier/pull/873

**Comment by jlongster** [comment]
That is leaving them in the right place; the output is expected. It's not going to change your string templates, like adding indentation or something within the block. We can't do that without changing your string. Honestly, the output doesn't seem any more or less readable than the input.

#873 would not fix this as there is a second argument to the call.

We will not be able to automatically make sure string templates look "right" all the time. I think the only solution is going to be for you to tweak them as needed. If we tried to keep the original formatting, it would produce a lot of other inconsistencies with syntax around it. I think this is just a limitation of combining something like string templates with prettier, and it's a rare case where you'll have to manually fix its formatting.

**Comment by trotzig** [comment]
Fair, although just to be clear - I wasn't expecting prettier to do anything to the text between the backticks. I just want the backticks to have the same indentation. Can you explain why we expect the closing backtick to be indented differently than the opening one? 

Oh wait, I see it. We can indent the opening backtick however we want, since the string starts with a newline. Changing the closing backtick would change the ending whitespace of the string. I get how that's a tricky issue to solve.

**Comment by jlongster** [comment]
@trotzig Yeah :/ However, see https://github.com/prettier/prettier/issues/1014#issuecomment-289595971. I just commented there. That would actually fix both of your examples. It's likely we'll explore this path. On paper, it's worse and makes the printer incorrect, but would actually probably work better for 95% of the real-world usages of string templates.

**Comment by mo** [comment]
I ran into this issue as well, my diff was:
https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20a()%20%7B%5Cn%20%20function%20b()%20%7B%5Cn%20%20%20%20function%20c()%20%7B%20%20%5Cn%20%20%20%20%20%20self.element.append(%60%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%5C%22section-title-row%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3Cspan%20class%3D%5C%22my-card-header%5C%22%3EThis%20Is%20Sparta%3C%2Fspan%3E%5Cn%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%60)%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

...not sure I understand why prettier wants to move the opening backtick to a new line?
