### ISSUE TITLE
An option to break before else and elseif

### ISSUE THREAD

**Issue by khalilpierre** [prettier/prettier#10823]
Before anybody screams about duplication, wanna say that the other threads have been shushed and locked by the Prettier team. But I think and option to break before else and elseif should be created. I mean, just look at this foolishness!

if (item.type == "song") {
      return item.data.song.song_title;
    } else if (item.type == "bible") {
      return item.data.title;
    } else if (item.type == "prayer") {
      return item.data.title;
    } else if (item.type == "instrumental") {
      return item.data.song.song_title;
    } else if (item.type == "reference") {
      return item.data.reference.title;
    }

And this is only going to get bigger and adding a "//" before each line is just (not a solution!) I know that the Prettier mods said that adding this option is just going to make the tool more complicated(i don't agree), but that was 2020.
Hopefully now in 2021, maybe they're going to reconsider. :|

**Comment by khalilpierre** [comment]
BTW, this is the code format i want:
if (item.type == "song") {
return item.data.song.song_title;
}
else if (item.type == "bible") {
return item.data.title;
}
else if (item.type == "prayer") {
return item.data.title;
}
else if (item.type == "instrumental") {
return item.data.song.song_title;
}
else if (item.type == "reference") {
return item.data.reference.title;
}

**Comment by thorn0** [comment]
> as option requests are out of scope for Prettier, they will be closed without discussion

https://prettier.io/docs/en/option-philosophy.html
