### ISSUE TITLE
Empty space

### ISSUE THREAD

**Issue by babakfp** [prettier/prettier#10832]
Empty space:

https://user-images.githubusercontent.com/44144724/117556540-e9072880-b01e-11eb-9baa-2eaa291dfc8e.mp4

Pressing:
1. enter
2. ctrl + s (format on same)

**Comment by thorn0** [comment]
Please fill in the issue template (input code, input options, actual output, expected output, explanation). For that:
- reproduce your on the [Playground](https://prettier.io/playground/)
- use the <kbd>Copy Markdown</kbd> button to get a report and paste it here
- provide the expected output and a short explanation for why you expect it to be that way

**Comment by babakfp** [comment]
Thank you for your quick response🌸.

### input code
```HTML
<p>
	Hello</p>
```

### input options
Do you mean the `.prettierrc` file?
[.prettierrc.zip](https://github.com/prettier/prettier/files/6447250/default.prettierrc.zip)

### actual output
```HTML
<p> Hello</p>
```

### expected output
```HTML
<p>Hello</p>
```

### explanation
I don't expect that white space because I don't need it and in some places it probably causes problems🤔.

### playground
This the the `Copy markdown` button data:
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpWzACTgBtiJUB6LEAGhAnRgEtoBnZUAQwCduIB3AAo8E7FJ2L9OAT3Z0ARt05gA1nBgBldMqZQA5shjcArnDpwAtvLgATG7YAynfcc564AMQjcLnGM31kEE5jGAhaEAALGAtiAHVIpnhWbTA4DVEkpgA3JOkgsFY5EF1WOG4YQSU9X2QAMwkyugArVgAPACElVXUNTgs4B104esazEFa2jV09YjgARWMIeFHiJpBtbjLuIOjYiPRuXRg4phsYSOQADgAGOkOIMrildCDDuG3skboARyX4KoMMTBVgAWigcFstgi3DgfyYsKqblqSAaa3GZQsTEMJgxMzmi2WI1RYzoME48lO50uSAATGSlExiDMAMIQCwokAfACsEWMZQAKhSxGj1tlTABJKD2WAaMBHRgAQWlGhg0jmqzKAF8tUA)

```sh
--parser html
```

**Input:**

```html
<p>
	Hello</p>
```

**Output:**

```html
<p>Hello</p>

```

### This is another report
It works as expected. It isn't the same content but there is no empty space like the previous example.
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpWzAZwgAJSziBbXfG+Y+amfADybylQHotcQAaEBHQwAltALJQAQwBOMiAHcACrIQSUUgDYKpATwkCARjKlgA1nBgBldKZFQA5shgyArnAFwKhuABNffgAyUo6uUg5wAGIQMhRSMKKOyCBSrjAQ-CAAFjAUmgDqWSLwBLZgcFZqxSIAbsW6yWAEBiD2BHAyMEomDnHIAGZa7QIAVgTMAEIm5pZWUhRwgfZwA0MeIGPMVvYOmnAAiq4Q8KuawyC2Mu0yyYZSPpqZ6DL2MPkivjBZyAAcAAwCZ4Qdr5EzoZLPODXGorAQARyO8G6QnUKQIAFooHA-H5MjI4AiRPjuuE+khBmd1u0KCJnG4qTs9odjityWsBDB7u9Pt8kAAmDkmESaHYAYQgFDJIChAFZMq52gAVe7qCnnGruACSUACsCsYBewgAgjqrDBdHtTu0AL7WoA)

```sh
--parser babel
```

**Input:**

```jsx
<p>
	so       m
			e te
		xt

</p>

```

**Output:**

```jsx
<p>so m e te xt</p>;

```

**Comment by thorn0** [comment]
See [Whitespace-sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting)
