### ISSUE TITLE
Timing of next release?

### ISSUE THREAD

**Issue by gkz** [prettier/prettier#10830]
Hi, thank you for being such active maintainers of Prettier! :)

I was just wondering if there is a timeline for the next point release. The last release was in November 2020. I've landed support for some new features in Flow (indexed access and optional indexed access) and we need Prettier to be released before we can launch the features. Additionally, you recently updated Babel so that's also probably a good reason for a new version. 

Thanks!

**Comment by thorn0** [comment]
Hi. I was going to release 2.3 two weeks ago. But it didn't happen because of a bug in a Rollup plugin we use. Now that it's been fixed, I'm going to try again today or tomorrow.

**Comment by thorn0** [comment]
https://prettier.io/blog/2021/05/09/2.3.0.html
