### ISSUE TITLE
Inconsistent formatting of small objects

### ISSUE THREAD

**Issue by brc-dd** [prettier/prettier#10849]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTYTAI0yUwHIwLMBfAHSkcig0wBN9DHNM4zKAMwqNaIADQgIABxgBLdMlDYATiogB3AAqqEaZCGwAbDdgCe+ycRXYwAazgwAytNtyoAc2QwVAVziScAC2xHDs7GEAMtievtgecABiECpB2DDyngbYvjAQEiAAFjBBRgDqhXLwaK5gcE56VXIAblVmBmBoliDuaHAqMFo2HmnIgsZ9kgBWaAAeAEI29o5O2EFwke5wYxMBIDOzTu4eRnAAir4Q8DtGkyCuKn0qBsTYoUYF0iruMGVy7DBCsgABwABkkXwgfTKNmkBi+cCezW2kgAjpd4EMZPoUNg0ABaKBwMJhAoqODouTkobxUZIca3PZ9IJybx+JnHU4XK7bem7SQwN5-AFApAAJgFNjkRmOAGEIEE6SBEQBWAq+PoAFTeOIZd2a-gAklAIrAnGBvrIAIImpwwMynG59Wi0IA)

```sh
--parser babel
```

**Input:**

```jsx
const a = { b : 'c' }

const d = {
  e : 'f'
}
```

**Output:**

```jsx
const a = { b: "c" };

const d = {
  e: "f",
};

```

**Expected behavior:**

I was expecting **_either_** the expanded one (`const d`) or the condensed one (`const a`) in **_both_** the declarations, i.e. any **_one_** of the following outputs:

```jsx
const a = {
  b: "c",
};

const d = {
  e: "f",
};

```

or 

```jsx
const a = { b: "c" };

const d = { e: "f" };

```

I am not able to find any API option which allows me to modify this behavior. I believe this is bug as people use Prettier to apply consistent styling across the codebase, and this doesn't seem like consistent.

**Comment by fisker** [comment]
https://prettier.io/docs/en/rationale.html#multi-line-objects
