### ISSUE TITLE
getFileInfo() doesn't consider .prettierignore

### ISSUE THREAD

**Issue by diegovilar** [prettier/prettier#10844]
`.prettierignore` is not considered by the API. This produces diverging results between CLI and API calls for the same file in the same working dir.

**Environments:**

- Prettier Version: 2.3.1
- Running Prettier via: API
- Runtime: Node.js v14
- Operating System: Linux and Windows
- Prettier plugins (if any): none

**Steps to reproduce:**

.prettierignore contents:
````
subdir
````

Test script (api-getfileinfo.js) contents:
````javascript
const prettier = require('prettier');
const file = process.argv[2];
const info = prettier.getFileInfo.sync(file);
console.log(info);
````

Run API test script:
```
/test$ node api-getfileinfo.js subdir/somefile.ts
````
Output: `{ ignored: false, inferredParser: 'typescript' }`

Run CLI:
```
/test$ prettier --file-info subdir/somefile.ts
````
Output: `{ "ignored": true, "inferredParser": null }`

**Expected behavior:**

`subdir/somefile.ts` **should** be ignored when using the API.

**Actual behavior:**

`subdir/somefile.ts` is **not** ignored when using the API.

**Comment by thorn0** [comment]
`getFileInfo` has the `ignorePath` option. See the docs https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath--options
