### ISSUE TITLE
The offset for React component body depends on component name length in v2.3

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#10848]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgFkBPAYQgFsAHaBGABUwhoGdDgAdKQwgDySEoAVyoAjLDwC+PHpChsYJCtTpQGQgEpx8MAHQA1CKgAmAMRFQwMVNEq16sADxkH6hs1ZsAfIQC8hAAUwAKE0gCUAX7cvIQKSoS4AYQibHAAgkERPHyYcDAimLzOpqgAbj78KcD80gDcSTW40s4A9GWVMnJQ6PA4+ERuak4wAExe7Jy5AkKiElJxpHNikpjdUPLQicOOGrBj2ro2RiYWVjZ2UO6jrqp7DBMs7H6BIQIANISk4VH+MTMEspkoE0plsjN8oVioRShUqjU6o0foFgKQGk1US12p0fBseH0sHgCCobvsYAB1VAwAAWABloABzAByuCocEmHFifEEwlWiz4yz5C3WUFkm2s22Uuw8sCptIZUBZbLgRz0pzMlmstnsI3JdzJDHl9KZrPZnNewVC-C+P0i0WmcSBmNS6SyOTiUKKJVx1VRSO+NXRjRBnGxHXhMhAHxArB1imQoFwmBYAHdGMmEGxkCBcAAbVO4UjZmPiTD4ADWBQAyjR8OhGcgYJgRHAY3AFqZTHBTHTcEqRLhGXBzBBMFRcDBbEqc7gRDAINGQDSYFQ8xSadS4Gw6wRq1nqRVqaQc2A2CW0IosExy4yJ8g8Hn0jGAFZsfgAIXLYCrMGrKrpdA4AffNnxAN9+GrBs8zgABFEQIHgECnzbEA60wdJMBzGBSBobcwEwVAaBgJcaEIuUzFpZAAA4AAYYzIiB0gpcsaBzMjtywcpgJjABHBD4E5Wc2AAWg0HseyXfJ+NQfJmCHe8kEfMD0ioVAmxbVC2GguCBOApTQNQmBcHEKlTCopAxhjZtcFQPMGwcRSQG3ABWJcwQAFRM7MDJQmNylbABJKBu1gasCKImAMhC6scJg5D0mkaQgA)

```sh
--parser typescript
```

After switching from Prettier 2.2.1 to 2.3.0 in a large React + TS codebase, I've noticed an unexpectedly large diff. The offset for many React components has shifted.

It turns out that the length of the component name now affects the location of `({`. If these opening brackets are moved to the new line, the whole component body is shifted. This makes git diffs quite fragile.

Imagine renaming some component during a refactor. In Prettier 2.2.1, the diff would be just one line but in Prettier 2.3.0, `git blame` for the whole file would end up broken.

**Input:**

```tsx
interface MyComponentProps {
  x: number
}

const MyComponent: React.VoidFunctionComponent<MyComponentProps> = ({ x }) => {
  const a = useA()
  return <div>x = {x}; a = {a}</div>
}

interface MyComponent2Props {
  x: number
  y: number
}

const MyComponent2: React.VoidFunctionComponent<MyComponent2Props> = ({ x, y }) => {
  const a = useA()
  return <div>x = {x}; y = {y}; a = {a}</div>
}

interface MyComponentWithLongNameProps {
  x: number
  y: number
}

const MyComponentWithLongName: React.VoidFunctionComponent<MyComponentWithLongNameProps> = ({ x, y }) => {
  const a = useA()
  return <div>x = {x}; y = {y}; a = {a}</div>
}
```

**Output:**

```tsx
interface MyComponentProps {
  x: number;
}

const MyComponent: React.VoidFunctionComponent<MyComponentProps> = ({ x }) => {
  const a = useA();
  return (
    <div>
      x = {x}; a = {a}
    </div>
  );
};

interface MyComponent2Props {
  x: number;
  y: number;
}

const MyComponent2: React.VoidFunctionComponent<MyComponent2Props> = ({
  x,
  y,
}) => {
  const a = useA();
  return (
    <div>
      x = {x}; y = {y}; a = {a}
    </div>
  );
};

interface MyComponentWithLongNameProps {
  x: number;
  y: number;
}

const MyComponentWithLongName: React.VoidFunctionComponent<MyComponentWithLongNameProps> =
  ({ x, y }) => {
    const a = useA();
    return (
      <div>
        x = {x}; y = {y}; a = {a}
      </div>
    );
  };

```

**Expected behavior:**

All three `useA()` and `return` statements have only two leading spaces, i.e. the offset does not depend on the component name length.

Our team will be staying on Prettier 2.2.1 in the meantime. Happy to help with a PR if we come up with some solution!

**Comment by kachkaev** [comment]
Just checked if the issue is present in pure JavaScript and could reproduce it too: [Playgound](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBZAngYQgFsAHaBLAXkwAphMAPTAXwEpNKA+TYAHSkyZIUDJgCGHTAFc0cAII1W-QQCc4MKSoEAeACYBLAG6cm1YA2YBucZOBjm2gPQHj-Zv37DReQqXKwAdX0YAAsANTgVXAAZaABzADkxInk5NPSMzKzsnMzJOkYAGkxcFnYuHmUhdCwJahl5RSq1DS1MPSMTWwtrUrNcKxszeycXTjcPKC8sH2IyKAog0Iio2KhE5NTc7Z2d-PoGYtK2Dm4+AWqRWskGhSULls0dMdMeHpLbAes6nhHnTrcIEKIAgJBg+nQyFAYhUKggAHcAAowhBoZAgMQAG3hYlwaOBACMVGIwABrdQAZRIJP062QMBUUjgwLgRAJcF0ug50TE6ykYjicAAYhAVEQxDBwXSUGIpDAIECQCEYERMQEQsE4GhqWA4BTUcEjMFcOiwGh8SBabIVDBEcS4uLkAAzLGyYEAKzQDAAQsSyZTNtFaXBna7mSBPQwKbS4pi4ABFKQQeChzFukDUlTW9EEsTszGKkgqWkwIK6ULIAAcAAZgUWILIAsSSOii1rIoYQ8CAI5J+B20FomVoAC0Cw5HMVal7+jUdoFjqQLrT4dkRH09MZq5jccTyZDS7DwJgebLFaQACZj8T9JiY75FyAtQBWRUNAAqeaHy-ThiZAEkoC5WAKTAYswTkICKRgXA41TWRmGYIA).

Of course, the name of the component should be quite long to shift the fn body 😅

**Comment by thorn0** [comment]
Is `git blame` the main concern here? It has the `-w` mode, in which it ignores whitespace changes. Also it has the [`--ignore-revs-file` feature](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt). Don't these Git features solve this problem completely?

**Comment by thorn0** [comment]
Said that, I agree that it's better to minimize indentation when possible. For type-annotated variables, the following formatting seems to be an interesting idea:

```ts
const MyComponentWithLongName: (
  React.VoidFunctonComponent<MyComponentWithLongNameProps>
) = ({ x, y }) => {
  const a = useA();
  return (
    <div>
      x = {x}; y = {y}; a = {a}
    </div>
  );
};
```

But for variables without type annotations, I'm afraid the current (2.3) formatting is going to stay since it's difficult to think of an alternative.

**Comment by kachkaev** [comment]
Git blame is one of the two concerns I have. Just checked what [VSCode git lens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) shows for the updated lines and saw the commit with an offset shift rather than the original one. This makes code introspection more challenging than it used to. Even if it’s technically possible to look ‘through’ the whitespace-only diffs, it's not a default setting, so requires an extra action from the whole team.

Another concern is the ‘broken rhythm’. I’d say that it’s even bigger than `git blame`.

Human brain unconsciously gets used to the standard offsets in the React files, which helps certain cognitive tasks. Determining if a given line is inside a hook or in the plain 'render phase' is a typical example. If there's no ‘rule of thumb‘ for the whole component body offset, this mini-task eats up an extra split second hundreds of times a day.

**Comment by thorn0** [comment]
> `gitlens.blame.ignoreWhitespace` Specifies whether to ignore whitespace when comparing revisions during blame operations

-- https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens#gutter-blame-settings-

**Comment by thorn0** [comment]
If we're talking specifically about React, I might be missing something. Why are these type annotations needed? In my React projects, I annotate only the props parameter and let TS infer the type of the variable. (Also I use function declarations instead of `const`s because I think hoisting is convenient.) Anyway, I guess you have your reasons for doing it that way, so if you feel like implementing https://github.com/prettier/prettier/issues/10848#issuecomment-836828099, please go ahead. I think it'd have good chances of getting merged.

**Comment by kachkaev** [comment]
Thanks @thorn0 – I might give that PR a shot soon.

I think I understand what you mean by using `function` keyword and by typing props only. In that case we get something like:

```tsx
interface MyComponentWithLongNameProps {
  x: number;
  y: number;
}

function MyComponentWithLongName({ x, y }: MyComponentWithLongNameProps) {
  const a = useA();
  return (
    <div>
      x = {x}; y = {y}; a = {a}
    </div>
  );
}
```

We don’t do so for two reasons:

- `const myVar = ...` is universal. By using [`"func-style": "error"` in ESLint](https://eslint.org/docs/rules/func-style), we enforce the expression fn style and this saves the team from a number of pitfalls and avoidable discussions. The difference between the two styles include traps for newcomers, so it's best to not have to pick between one style and the other. Not having `hoisting` is a good thing. It helps the devs follow a coherent ‘rhythm’ and not write code that is then hard hard to read.

- [`React.VoidFunctonComponent`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46643) checks the return types, not just the args. So it's harder to return `undefined` or `void` by accident. When using `function` + `props: MyProps`, the return type will be also checked, but only when the component is mentioned in some Jsx. This works too, but makes things a bit more confusing for the devs.

**Comment by kachkaev** [comment]
@thorn0 WDYT of 

```ts
const MyComponentWithLongName: React.VoidFunctonComponent<MyComponentWithLongNameProps> = ({
  x,
  y,
}) => {
```

instead of 

```ts
const MyComponentWithLongName: (
  React.VoidFunctonComponent<MyComponentWithLongNameProps>
) = ({ x, y }) => {
```

?

So my third example would work as the second one. The benefit I see here is that `const MyComponent = React.VoidFunctonComponent<MyComponentProps>` will always be on one line. This will make it easier for the brain to pattern-match.  Sticking with one line despite its length is what Prettier 2.2.1 does already.

**Comment by thorn0** [comment]
This line is too long. The fact that Prettier doesn't break it is kind of a bug. Also Prettier's general strategy with regard to arrow functions is "prefer to keep the signature on one line if possible".

**Comment by kachkaev** [comment]
Sorry for the lack of updates @thorn0. I’m still planning to look into [your suggestion](https://github.com/prettier/prettier/issues/10848#issuecomment-836828099) – just haven’t found time yet. When 2.3.1 is on the horizon, please let me know and I’ll prioritise the work!

**Comment by thorn0** [comment]
Now that TS 4.3 got released, we need to release support for it, so Prettier 2.3.1 is near.

**Comment by kachkaev** [comment]
Thanks for the headsup @thorn0! I'm planning to look into the fix now. If you have any hints / suggestions, it'd be great if you could share them!

**Comment by thorn0** [comment]
First of all, you'll need to detect this situation in the code that prints assignments (`print/assignment.js`) and switch the _layout_ to `break-lhs`. Then modify the code that prints type annotations in assignments.
