### ISSUE TITLE
Extend markdown parser & printer

### ISSUE THREAD

**Issue by Gregoor** [prettier/prettier#10858]
Hi there,

thanks for the amazing work on prettier, it has made programming so much better and focused on what's important!

I do appreciate prettier's end-of-bikeshedding approach of minimizing configurability. Now I am wondering whether that philosophy also extends to extensibility:
Over at MDN [we are considering extend micromark to add kramdown-style definition lists](https://github.com/mdn/content/issues/4367). Simultaneously we are wondering whether to use Prettier for our content, which fortunately also uses micromark. Now we are wondering, if we were to go down the road of writing a syntax extension, would the people of Prettier also be open to creating an (or reviewing a PR adding an) extension point for that?

All the best ✨

**Comment by fisker** [comment]
Not speaking on behave of the team.

I think we can accept new syntax, if it conflict with other spec, we can add a new parser value, js have many parsers, what can't markdown?

**Comment by Gregoor** [comment]
Thank you for the information, that is good to read! I did not realize prettier was not yet using micromark. We are considering not extending syntax for now, but wait for prettier (and possibly GFM) to move on this, before we adopt new syntax.

**Comment by thorn0** [comment]
Okay, closing in favor of https://github.com/prettier/prettier/issues/10701 then.
