### ISSUE TITLE
Support for shell script 

### ISSUE THREAD

**Issue by komondor** [prettier/prettier#10871]
Hi, 

- I currently use [shell-format](https://github.com/foxundermoon/vs-shell-format) to format shell script. 
- Google recently open source [zx](https://github.com/google/zx) 

Automatic embedded language template literals is not yet available for shell script. Would it be possible to integrate the shell-format plugin to format embedded shell script in javascript template literals ? 

Thanks

**Comment by kachkaev** [comment]
There is a plugin for that :)

https://prettier.io/docs/en/plugins.html → [`prettier-plugin-sh`](https://www.npmjs.com/package/prettier-plugin-sh)

Note that issues in this repo are for reporting bugs. One of the [issue templates](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE) must be followed.

**Comment by komondor** [comment]
Does it format shell embedded in a javascript template literal ? For what I understand, it will format shell script (script.sh), but not embedded script within a javascript file.

Thanks

**Comment by kachkaev** [comment]
Yes, it will format ` ```sh ` blocks in markdowns. For questions, please use StackOverflow.
