### ISSUE TITLE
Ugly formatting for assignment function call with complex type parameters

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#10878]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mYAhgDZkA8wAOlJpgA4BOEjAjEphswJZQBzANx0GLNgCYuPfsNFNWjAMzSYfQSKgBfAHwAKAJSaQAGhBsYvdMlAlmrAO4AFOwjTIQ5ByQCe7swBGzCRgANZwMADKjCGyyGoArnBmcAC2AXAAJplZADIkggkkAnAAYhDMqSQwloIeJAkwEKYgABYwqWQA6q288GgxYHCRbn28AG59Ph5gaP4g-GhwzDBOwQJVyNjkS2YAVmgAHgBCwWERkSSpcLn8cFs7ySAHh5GyZHAAigkQ8A9kuxAMWYS2YHhgPkYcDQYD4jBgLRY-BgXV4mRgrWQAA4AAxmcRLLrBRgeFjQ5bje5mACOP3gazY7hQJDQAFooHAslkWsw4LTeLy1sVNkhtgCnktUrx4swkmY0O8vnT7qLHmYYCQAqj0ZikBJ1cFeGRZABhCCpEUgaEAVhaCSWABVNUyxYDxkkAJJQHKwSKw3jwgCC3siEI+-yWWi0QA)

```sh
--parser typescript
```

**Input:**

```tsx
const foo = call<{
  prop1: string;
  prop2: string;
  prop3: string;
}>();

```

**Output:**

```tsx
const foo =
  call<{
    prop1: string;
    prop2: string;
    prop3: string;
  }>();

```

**Expected behavior:**

No change

```tsx
const foo = call<{
  prop1: string;
  prop2: string;
  prop3: string;
}>();

```

**Comment by alexander-akait** [comment]
I found output is better :smile:

**Comment by ArnaudBarre** [comment]
Also reported here: https://github.com/prettier/prettier/issues/10846

**Comment by thorn0** [comment]
No, it's not the same issue.
