### ISSUE TITLE
Incorrect line break in the middle of a closing </i> tag if immediately followed with another tag

### ISSUE THREAD

**Issue by julienma** [prettier/prettier#10872]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UABEQOqYwAWEArjEQIZEDOADg2HEQEZwwDucBEUyMo6EQFsA5oRKpRYADYNmzALz4QDALTY4AJwCeOpdGk7lq5jqgNJcHQCsazGDpgQd0vjoj6DD0pHVgNMWB1+THQqHWYvKgZ3KkclcMdmaholdB1eSIMGVlY4dC1cVAB6TArMGSJKgigqrDxCQgwcJpJyKkYWdk4ePkFhUQZxKVliIgUiKzVNbT1DEzMoCwWbOwdnV2SvH3d-QyCQsIiomMo4hMoks9N0uKycvMd+QuLS8qqa2bq0gaTRaXRAABoQBBWDBMNBmMhQAwDAYIPwAArIhAIlAMJT8BhGBGQ7iFMAAaz4AGVBuFpMgYAYaHBIXBJLx0OhSgAZCbSGgMHwAMQgBkkSVhG2Q2joEAhIEoMEkSlIlAocDYHDgVOxFBwFCM0rAanl4WYhhg6MK0nFyAAZnjzZCnMwAB4AITJlJgVPscG56XtjpZIBdrqpdKUcAAijQIPAg0onSB2AZzQZpYrlfLQuEYORrsgABwABkhoQg5tIX2loQ1hn08oAjnH4FboTjtNshFz0PKDHAW5gB1bBbakA6kyHzZJMAymdPIzHW3BE8mYAxuAWqMgAEyQxkMTBpDYAYQgknHIA1AFZ5a44AAVTc4yfJ7DMgCS4gQPrAYRhABBcQqRgIwozXOAAF8oKAA)

```sh
--parser html
```

When a `</i>` tag is immediately followed with another tag (without any space), then prettier cuts the closing `</i>` in the middle.

(Original issue is https://github.com/adamzapasnik/prettier-plugin-erb/issues/36#issuecomment-839910141)

**Input:**

```html
<div>
  Without a space between i and img
  <i class="a-very-long-class-name-just-to-get-over-the-print-width-so-that-the-line-should-be-wrapped"></i><img />
</div>

<div>
  With a space between i and img
  <i class="a-very-long-class-name-just-to-get-over-the-print-width-so-that-the-line-should-be-wrapped"></i> <img />
</div>
```

**Output:**

```html
<div>
  Without a space between i and img
  <i
    class="
      a-very-long-class-name-just-to-get-over-the-print-width-so-that-the-line-should-be-wrapped
    "
  ></i
  ><img />
</div>

<div>
  With a space between i and img
  <i
    class="
      a-very-long-class-name-just-to-get-over-the-print-width-so-that-the-line-should-be-wrapped
    "
  ></i>
  <img />
</div>

```

**Expected behavior:**

```html
<div>
  Without a space between i and img
  <i
    class="
      a-very-long-class-name-just-to-get-over-the-print-width-so-that-the-line-should-be-wrapped
    "
  ></i><img />
</div>
```

**Comment by thorn0** [comment]
This is intended. Prettier tries to keep one element per line. `i` and `img` are on the same level of the tree and Prettier makes it explicit. The benefits aren't immediately seen in simple cases like yours, but in more complex cases, this approach shines:

```html
<span class="word"
  ><span class="syllable"
    ><span class="letter vowel">i</span
    ><span class="letter consonant">p</span></span
  ><span class="syllable"
    ><span class="letter consonant onset">s</span
    ><span class="letter vowel">u</span
    ><span class="letter consonant">m</span></span
  ></span
>
```
