### ISSUE TITLE
Inconsistent curried arrow functions in TS + 2.3.0

### ISSUE THREAD

**Issue by mpajunen** [prettier/prettier#10877]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mmAFAEYCGATkphlQJZQDmAlIQHymUBet9TNp0yUqmANQiKPADpQ5kKBhx4ATIWLlq-GIxbsCXLXzq7BrHXubDREqbPlRFy3BADMGgDwAVDlpqmVgZGvJbmNtR2vHIgADQgEAAOMAzoyKDUVBAA7gAK1AhoyCAUADbZFACeRfFkVBRgANZwMADKiQ2CyLoArnDxcAC2ZHAAJqNjADIULD0UzHAAYhBUgxQwKSzFFD0wEHEgABYwg6UA6ocM8GgdYHCthVcMAG5XlcVgaDUgTGhwVDBcvVmGtkNgyn94gArNAADwAQvUmi1WhRBnBJkw4GCIf0QDDYa1BKU4ABFHoQeA40qQkAdKh-KjFSgjUoHRJ6GBnBijGCHZAADgADPEORA-md6olihy4Izntj4gBHCnwIFJIooChoAC0UDgYzGByocBVDBNQPmoKQ4JpeL+gwY3SofXiaGJZNV2JtuPiMAoZG5vP5SFUfvqDFKggAwhBBtaQHKAKwHHp-bwBzW22nPPoASSgE1grTAjGSAEFC60YJUSdS-gBfBtAA)

```sh
--parser babel
```

**Input:**

```jsx
const foo =  (bar: string) => (baz: string) => bar + baz

const foo2 =  (bar: string) => (baz: string): string => bar + baz

const foo3 = <T>(bar: string) => (baz: string) => bar + baz

```

**Output:**

```jsx
const foo = (bar: string) => (baz: string) => bar + baz;

const foo2 =
  (bar: string) =>
  (baz: string): string =>
    bar + baz;

const foo3 =
  <T>(bar: string) =>
  (baz: string) =>
    bar + baz;

```

**Expected behavior:**

No changes to the input.

The changes from #9992 are nice when wrapping is needed. However, using TypeScript, shorter lines are also formatted when there's a type parameter or a return type.

**Comment by thorn0** [comment]
This is intended. Sometimes Prettier splits the line even if the line length limit isn't reached. This happens if it looks like too much is going on a single line. An arrow chain with type annotations is one of such cases. This logic might look unneeded in simple cases like your made-up examples, but it's helpful in real-world code.

**Comment by mpajunen** [comment]
> This is intended. Sometimes Prettier splits the line even if the line length limit isn't reached. This happens if it looks like too much is going on a single line. An arrow chain with type annotations is one of such cases.

But it's not type annotations that causes the split: It's type parameter or return type annotations. Especially splitting based on a return type annotations, but not parameter type annotations seems inconsistent.

**Comment by thorn0** [comment]
Being outside the parens, return type annotations make arrow functions more difficult to read than parameter annotations. E.g., sometimes it's not clear whether `=>` is part of the annotation. Do you have any specific real code that looks bad because of this logic, or is this issue hypothetical?

**Comment by TwireonEnix** [comment]
Is there any way to opt out of this behaviour @thorn0 ? If i'm currying only two arguments I don't like nor need one argument per line if the print width is not exceeded. This recent change is messing all my codebase.

**Comment by thorn0** [comment]
@TwireonEnix without an example, it's difficult to understand what you mean

**Comment by mpajunen** [comment]
> Being outside the parens, return type annotations make arrow functions more difficult to read than parameter annotations. E.g., sometimes it's not clear whether `=>` is part of the annotation. Do you have any specific real code that looks bad because of this logic, or is this issue hypothetical?

So far ran into the issues in a private repository. [Here are some paraphrased examples from real code.](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEYBOcCG8mAvJgBT5gwCW0SmAglbVADwCuUA1lBAO5QAfAEp6ACXxQAJgBs4OEoMz40ATyhhyeAI4AaTHjTDFmYAB0ombOiwyIAcxLK++arYf35ZHcItXIUBimmFKE+PoYhOxoAMIQUnCYAL5O+C5uyszQ3nB6mHb2vlB+BnBoAHSRMNFkVdFxCcLlAFZo2aEw+EVJFhYBQbgE8ADicFikrAAimHAAHvDSaJiTYYJkYAAWcGBc9DFbO1Mi9KMwRyYq6ppccKom5pbWgVhucAC2qelYnjAAkvBvMg3VRFEp4ao4SybbZcMivN7lABu+Bk7DgxgA-Jh4Zh6PIcBAcGRur0NDZsBtXJYJgAVNblBkAM04YDQ9AAaijqB1Caw6QBtAC6okwnJk3MIvLpJmRqMSxEEJWZGgqeCk7DAcDIZAADnhEfQMDhqFBHAAfTCcBKMk1wKT6ZVgYwKzB6uCIzAYrGOsiytHCfRWuA2qB20HFKAAekjmAAsgQoHwNtQ5Jg0DrxTAlvg8KU3hBEXbMIyCR82m8xsnTflqDdMDBk2y+uSdew-gCnDAIAAlMrsGQwMglS4aTBTGbzBBSJYrTprbmGmDG036Dr4egAeTebim+gA5Ny98dMAAFUvUNBwViIiDcpQuh5WKxpVxYKQAI3KrcHj6fVm5uglH+DLlGugGPFYSRFJB4FFCAuggBAOo0OgyCgDmBJ8CeOYIGgyAgPgN7cvBIDvjglA3DAADKOqUCa9jIEuaIIe8752gkUgADKSPY7D4J4ABihJvIQNCmvh+BthAJEbDAbwyAA6sm8DppQcBUbhbjUIibiqPhrJ4QhJqXjgMBnvxInIIyKKXghrSzAAQuROxjFR+AVpxtpWTZcB2WgsxUfRcgAIrsBA8DeTItkgLROAmfhMCqDqZS4NQyEkXqJowAp3INsgACMAAMhUIXqECXgp5E6vhbomYWJHaGF8BnkheEoCoAC0oZ2naJE6Ow1B4OZ9iWUg1lRb5ICXtukXRWgQVwKF4VwIxODMSAnTvjlUh5UgABMCFLq44qmnEbyjSAZQAKwkdEcA0vg75teN0WImivzSAg1GpchDDSFRiVyLNcBJEkQA)

I'm not sure the reformatted code necessarily looks bad, though I'm used to the single line forms. Mostly the change just seems unnecessary.

Originally I thought the TS formatting change was accidental, since the example in release notes has long lines. Looking at the formatter code, clearly the changes were considered. And starting from scratch, I could see the argument for either style.
