### ISSUE TITLE
Same JSON content is formatted differently dependent on file name

### ISSUE THREAD

**Issue by KonradHoeffner** [prettier/prettier#10876]
Unfortunately I cannot use the playground as it doesn't seem to accept JSON. My problem is that prettier 2.3.0 formats a very short array in my package.json  incorrectly as a multi-line array but *only* if the file is named exactly package.json. If the file has a different filename it works correctly.

The simplified package.json file:

```json
{
        "keywords": ["mtg"]
}
```

```
$ npx prettier package.json
{
	"keywords": [
		"mtg"
	]
}

$ cp package.json test2.json
$ npx prettier test2.json
{
	"keywords": ["mtg"]
}
```

As you can see, the files are exactly the same but the output is different.

## Configuration

```
{
        "useTabs": true,
        "singleQuote": false,
        "trailingComma": "es5",
        "printWidth": 120
}
```

**Comment by fisker** [comment]
`package.json` use a different parser 

https://github.com/prettier/prettier/blob/2eb2df6ed29efd8e6dce7aabc8d23771aac308ca/src/language-js/index.js#L80

**Comment by KonradHoeffner** [comment]
Is this documented anywhere? It really tripped me up and I want to prevent other users wasting time on this same problem.
