### ISSUE TITLE
Empty exact object flow type is changed as non-exact

### ISSUE THREAD

**Issue by valscion** [prettier/prettier#1089]
Prettier turns this:

```js
type Props = {||};
```

into this:

```js
type Props = {};
```

...which changes the type. This feels like a bug.

This means different things in Flow: https://flowtype.org/try/#0C4TwDgpgBAogHgQwMbAPICMBWUC8UDeAPoQL4DcAUKJFAJIB2EiKG2e+5FFAZgK70oAlgHt6UJsmAAKYQC5YzNFgCUBEj35DRUQY0Uz5DCSxVqux6fijdhcqAHJ0CAE72oJZZV0WpVm3ccXNw9KIA

Here's the prettier run: https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Props%20%3D%20%7B%7C%7C%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by jlongster** [comment]
Interesting, thanks!
