### ISSUE TITLE
Formatting Vue lang="ts" doesn't work at all

### ISSUE THREAD

**Issue by Shinigami92** [prettier/prettier#10905]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdQHyVQDEeWWLhhAsngEsoAYWgwAThBzdCrDIKgBaAG4C4Adxk85CxTAhSARnnFaehAHQw8hgM5meFvGBgDo9qOa+E8ACmWKAGYQ4uQA5MDEEGAEblAANIQAJoQAvoQQgYTyQgAqBjjG4gCCLnG2YYlIANZwAJ7hONGx0JWEAAJgOAJg1eFQeKqkBHD5vk0xrtAAlGHTDt4WPdAL3oS2yqS+6gJJMAAW4QBMACxt+3ACpPswx2eJqhoAQhAAHuEADIRfp4Snc6s1oQsAR9r5AgIcDhwqxAnC2kgkuEkgDPOYdEJFJBYAo4KY0V5JLR4OIVGpNFBUAB6TC4EbMKAsVC2MDiARYGDEPBkKggGD2EAMgTYEKc-hCUSwSQ4QiBSQYQhhdpUyAiqAIflU8UiMTSizKWhwMIAbhYwqwosIkSScAh6tEao1iQASrbEuJbWlZfLFQajaaoObLZFnRBiXAADLNKZQZ14dQusMkxK0WxwUPh8ReuUQBVhP2KIkkk0sFhwV4W8Scm2BPC0HDV21COAOi3q2C+YAyVVtjW2JBW7WSiRSVLxGRpmC0LC+aZWszY2ycot4gcZkmEciEVPppN42cBryLzk5KD5IwmUox-uEV2BVDFcTiPB1VCRCYtKADpdssjG5LfhIQikGkjCMJuhAeoEvgANoLF2BLeB+MYDmEkA2pUgJUlShBwLY3SwIoSQCLYNg4HAijqq8MCKARcDZHgry0QggJJKhvAABzxAAzMIABsFgAJw8YQfE8UJonxAArAAaoJ-HxAAjB8FiKYQUmqUpaknFpAAS3EyYp3G6ScwgaYpSncZJRkSWJimyYp8liUcKlqQJwlHGpXGebpymGYJukcYZplcYpRwSQA7JpYXWUcwhRRZMWhYpqmEKFHwyVJvkZdxvCKWJvGKQlImKVx3ESaV0lycIlXKalpVCVpfwfHpnmGcZLk1RxjVGYQtXlYJfWhQ58mVS59XFZ5fXOYpvknP5vl8cFNV2eFg35T1RxDUpcUbcJMX5Vp9V2RlWWKfNxn5QAWmECxjvBgLIXEqGqAAXphiFeNhuH4UINHEaRhjkZR5Y0XRDFMeRjKfeYbGKnlKVSX1gmqTVKVWeNW11YNU11VtnkWFJwgo0jRxbd1fF-OFalRaTKXyQlfwpRxokWBjKURaJTOExGAmkx8-EWCz400xYJzNWzhBRZz428d1wsqUjKPiy5hAo5TDUcRGMUabt4VbeLYUWJz5VY+VKsWHxNUnKl1N9eZfUVQJ+OoxtlP631UUW1ZpV-Jb2u04QplFZLA3TZbhDlSzG1WeVEU1Uj5VI+dks22p53qf7imI8jqk3Xd44wwhQJRJMz2KngS4fSXcNhHlLVtaV+kRqFxlSdrLUcbpEXa0cPEB-EXfndr+2XXxEaeUpQ-zT5yn5zDqRmAAutMAYLu4nIDEMIz5AO4zRuX66Rgf0Bxuoc7kOBygQLsEH72XMybuBK7iBYdC2GCT0zGviEelO4ieEiKec8hRLxlHcIkLeVwd4QDSIeNILBUiryZFSFkbIOQMiZEuOo5EuQ8moCyWwAoGQABJTxYl1FIRQOw9j7AHCcDiWBXgBhIbYXYCBBjMUCDRGhBwBzcQ+B8JhLDyH6AvKSC4Vwbj8KksI0sUBDAQCSHUecaJ5DiFIEIAcHx4HBEImw16cABxGTkWiPRNFawYEhHUAcigOC4AorYOoS44AYESE8Ai1R+BgAAMrOMwAAMTEIkMIPi4CkAgPRAAqgASTaKGRR+hEgAHlXh1FIAgRIUTDC0FgLQRIwhuTWA9FCEJySsAIEID47kFRC5eDCLpOAOBlBwFcDEQgAA5OAho2ikSgLYRQaY2SBADIvaG7BOCqJ4ADOkNjZTkWYd2KQIQBwaMML4MmEVEibO2UcCKyC0TGF6KQIkUAkgUKaOIVZpB1ncS2ZHe53EOIHLGSwDEShHjqCmYQSR1wYDGMEcofY8DeF0MIDEHAYBfDKQ+MoL5ihZDADIbobEI4cDUN2AcdICLWBIrYTaLeXCeGYv2Eg+BEAWniECE0dQig5l1n0KM+R7y9AFCKN8350jCDIsxGI0BEjLh-PgUc6oJywxnIuSsyCNzfAnHuVJPuoluIHJkE4cB-TvnTJIrMgc1LyzwJ4AAK1TK4QIdQKGwA1LqhZigEBJANT8wVXKhAXDZDAH+XgljYk1bDbV+A5l6sWTDPA3RSBKFRVa8FGo8QOp4CCJIxEyD0NMV4MZPAxmvLYOQ1FuIszF0dVI-54KQ1QphUCwgOKkWiLZSYRQnKYBkpkBSvE1KIC0vpcSCATLKSoJgDguADIQDxBABADk5RkCgBMJIdQAAFEwCBbDIBACG9QL5F3DsMM+XorSfEgjAMBZAEhDTDtcYYOACbz0Rm5KQWgeAMlBPEPIGArgyBLoZRAIdIAbgYBwAAdX2AIeAtg91wDCf0wDAhVB9qXWAIhn6hBDJgDO58pB5DIFrDgNMw7DW2FeE8LdtQYDVIwJGZs6GQ1YZADh14PjgLkQAIq0AgPAcjmG4DDpBOIIZS6-SfqwL+GAv6SXIDCi1Ggkg0y-ufFgJd-G8J4haZ+gAjkx+AyHR2LpQJXEG57z2fo9CpgQHpkN3rQ0gDDlG0xWMPeIY9IA2FkAY6puANm7PWEMEJ2hyA+58mfJCYCDozMgCgNAFzw6dy5BsJpiz7GQB+hiWcjUPjWTshgMUM5Pi+3kVY2mVIqQgA)

```json
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "printWidth": 120,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "none",
  "useTabs": false
}
```

**Input:**

```vue
<template lang="pug">
#app
  MainControl
  #main-view
    #main-toolbar
      .tabs
      .actions
        a(v-for='{ location, d } of mainToolbarActions', :key='location', @click='navigateTo(location)')
          .icon
            svg(width='24', height='24', viewBox='0 0 24 24')
              path(fill='#fff', :d='d')
    #main-container
      router-view
</template>

<script lang="ts">
import MainControl from '@/components/MainControl.vue';
import { defineComponent, Ref, ref } from 'vue';
import { RouteLocationRaw, Router, useRouter } from 'vue-router';

export default defineComponent({
  components: {MainControl},
  setup() {
    const router: Router = useRouter();
    const mainToolbarActions: Ref<Array<{ location: string; d: string }>> = ref([
      {
        location: 'code',
        // eslint-disable-next-line max-len
        d: 'M8,3C6.9,3 6,3.9 6,5V9C6,10.1 5.1,11 4,11H3V13H4C5.1,13 6,13.9 6,15V19C6,20.1 6.9,21 8,21H10V19H8V14C8,12.9 7.1,12 6,12C7.1,12 8,11.1 8,10V5H10V3M16,3C17.1,3 18,3.9 18,5V9C18,10.1 18.9,11 20,11H21V13H20C18.9,13 18,13.9 18,15V19C18,20.1 17.1,21 16,21H14V19H16V14C16,12.9 16.9,12 18,12C16.9,12 16,11.1 16,10V5H14V3H16Z'
      },
      {
        location: 'viz',
        // eslint-disable-next-line max-len
        d: 'M11.5 19.1C11.3 20.2 10.9 21 10.2 21.5C9.5 22 8.6 22.1 7.5 21.9C7.1 21.8 6.3 21.7 6 21.5L6.5 20C6.8 20.1 7.4 20.3 7.7 20.3C8.8 20.5 9.4 20 9.6 18.8L12 5.2C12.2 4 12.7 3.2 13.4 2.6C14.1 2.1 15.1 1.9 16.2 2.1C16.6 2.2 17.4 2.3 18 2.6L17.5 4C17.3 3.9 16.6 3.8 16.3 3.7C15 3.5 14.3 4.1 14 5.6L11.5 19.1Z'
      },
      {
        location: 'ast',
        d: 'M10,21V18H3L8,13H5L10,8H7L12,3L17,8H14L19,13H16L21,18H14V21H10Z'
      }
    ]);

    const navigateTo: (location: RouteLocationRaw) => void = (location) => router.push(location);

    return { mainToolbarActions, navigateTo };
  }
});
</script>

<style lang="scss">
$main-control-width: 48px;
$sidenav-left-width: 300px;
$main-toolbar-height: 35px;

body {
  margin: 0;
  font-size: 13px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans',
    'Helvetica Neue', sans-serif;
}

#app {
  display: flex;
  color: rgb(227, 227, 227);
  background-color: rgb(37, 37, 38);
}

#main-view {
  height: 100vh;
  width: calc(100vw - #{$main-control-width} - #{$sidenav-left-width});
  overflow-y: auto;
}

#main-toolbar {
  height: $main-toolbar-height;
  background-color: rgb(47, 52, 63);

  .actions {
    display: flex;
    justify-content: flex-end;
    height: inherit;

    .icon {
      display: flex;
      align-content: center;
      padding: 4px;
    }
  }
}

#main-container {
  height: calc(100vh - #{$main-toolbar-height});
  overflow-y: auto;
}
</style>

```

**Output:**

```vue
<template lang="pug">
#app
  MainControl
  #main-view
    #main-toolbar
      .tabs
      .actions
        a(v-for='{ location, d } of mainToolbarActions', :key='location', @click='navigateTo(location)')
          .icon
            svg(width='24', height='24', viewBox='0 0 24 24')
              path(fill='#fff', :d='d')
    #main-container
      router-view
</template>

<script lang="ts">
import MainControl from '@/components/MainControl.vue';
import { defineComponent, Ref, ref } from 'vue';
import { RouteLocationRaw, Router, useRouter } from 'vue-router';

export default defineComponent({
  components: {MainControl},
  setup() {
    const router: Router = useRouter();
    const mainToolbarActions: Ref<Array<{ location: string; d: string }>> = ref([
      {
        location: 'code',
        // eslint-disable-next-line max-len
        d: 'M8,3C6.9,3 6,3.9 6,5V9C6,10.1 5.1,11 4,11H3V13H4C5.1,13 6,13.9 6,15V19C6,20.1 6.9,21 8,21H10V19H8V14C8,12.9 7.1,12 6,12C7.1,12 8,11.1 8,10V5H10V3M16,3C17.1,3 18,3.9 18,5V9C18,10.1 18.9,11 20,11H21V13H20C18.9,13 18,13.9 18,15V19C18,20.1 17.1,21 16,21H14V19H16V14C16,12.9 16.9,12 18,12C16.9,12 16,11.1 16,10V5H14V3H16Z'
      },
      {
        location: 'viz',
        // eslint-disable-next-line max-len
        d: 'M11.5 19.1C11.3 20.2 10.9 21 10.2 21.5C9.5 22 8.6 22.1 7.5 21.9C7.1 21.8 6.3 21.7 6 21.5L6.5 20C6.8 20.1 7.4 20.3 7.7 20.3C8.8 20.5 9.4 20 9.6 18.8L12 5.2C12.2 4 12.7 3.2 13.4 2.6C14.1 2.1 15.1 1.9 16.2 2.1C16.6 2.2 17.4 2.3 18 2.6L17.5 4C17.3 3.9 16.6 3.8 16.3 3.7C15 3.5 14.3 4.1 14 5.6L11.5 19.1Z'
      },
      {
        location: 'ast',
        d: 'M10,21V18H3L8,13H5L10,8H7L12,3L17,8H14L19,13H16L21,18H14V21H10Z'
      }
    ]);

    const navigateTo: (location: RouteLocationRaw) => void = (location) => router.push(location);

    return { mainToolbarActions, navigateTo };
  }
});
</script>

<style lang="scss">
$main-control-width: 48px;
$sidenav-left-width: 300px;
$main-toolbar-height: 35px;

body {
  margin: 0;
  font-size: 13px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans',
    'Helvetica Neue', sans-serif;
}

#app {
  display: flex;
  color: rgb(227, 227, 227);
  background-color: rgb(37, 37, 38);
}

#main-view {
  height: 100vh;
  width: calc(100vw - #{$main-control-width} - #{$sidenav-left-width});
  overflow-y: auto;
}

#main-toolbar {
  height: $main-toolbar-height;
  background-color: rgb(47, 52, 63);

  .actions {
    display: flex;
    justify-content: flex-end;
    height: inherit;

    .icon {
      display: flex;
      align-content: center;
      padding: 4px;
    }
  }
}

#main-container {
  height: calc(100vh - #{$main-toolbar-height});
  overflow-y: auto;
}
</style>
```

**Expected behavior:**

Content between `<script lang="ts">` and `</script>` should also be formatted

E.g. `{MainControl}` should become `{ MainControl }`

---

I don't know why it's working in the playground but not in my project https://github.com/Shinigami92/vizscript

I checked my configs and everything multiple times and prettier is working for pug, scss and typescript files on their own
But not the part between `<script lang="ts">` and `</script>` :thinking: 

Please check out the repo and try

```node
yarn install
yarn format
```

Change some content between `<script lang="ts">` and `</script>` and try to format it

**Comment by fisker** [comment]
Why I got the right result?

**Comment by thorn0** [comment]
@Shinigami92  Please try to isolate the issue. We need a [minimal reproduction](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff#how-to-create-a-minimal-reproduction), not a repo with a lot of unrelated stuff.

**Comment by Shinigami92** [comment]
https://github.com/Shinigami92/prettier-repro-10905

**Comment by Shinigami92** [comment]
Added also a non-ts example that also doesn't work
And a style css that works!

**Comment by thorn0** [comment]
Try removing `prettier-plugin-organize-imports`

**Comment by Shinigami92** [comment]
Okay I will open an issue at https://github.com/simonhaenisch/prettier-plugin-organize-imports

**Comment by simonhaenisch** [comment]
@thorn0 I'm the author of `prettier-plugin-organize-imports`. Figured out that the plugin was throwing an error during preprocessing, after which Prettier would silently pretend that it had formatted the file, without making any changes to it. I think there could be better error handling around this with plugins? Like it could log a warning that the file couldn't be formatted because of a plugin error, and the name of the plugin?

**Comment by thorn0** [comment]
See https://github.com/prettier/prettier/issues/10602#issuecomment-808602535
