### ISSUE TITLE
Concatenate strings when changing from multi to single line

### ISSUE THREAD

**Issue by bogdan-zaharia-hs** [prettier/prettier#1091]
If I have an old code that used a smaller line-width, and I have a long string split along two lines:
```js
const someLongString = "This was formatted for a line width of 80 characters, "
  + "but I want 100";
```
If I run this through `prettier --print-width=100`, I get: 
```js
const someLongString = "This was formatted for a line width of 80 characters, " + "but I want 100";
```

Ideally, it should be: 
```js
const someLongString = "This was formatted for a line width of 80 characters, but I want 100";
```

Not sure if this is something that prettier should do, but I think it is useful, since the code would not look strange.

**Comment by lydell** [comment]
(Related: ESLint's [no-useless-concat](http://eslint.org/docs/rules/no-useless-concat) rule.)

**Comment by bogdan-zaharia-hs** [comment]
@lydell thanks, I didn't know about this rule. So maybe this could be done by running `eslint --fix` afterwards? Or using [prettier-eslint](https://github.com/prettier/prettier-eslint).

**Comment by bogdan-zaharia-hs** [comment]
> So maybe this could be done by running eslint --fix

Never mind, I just saw that this rule is not auto-fixable.

**Comment by bakkot** [comment]
This would involve changing the AST, which is usually out of scope for Prettier.

**Comment by jlongster** [comment]
Yeah, unfortunately we're not going to get into rewriting the AST, sorry! That eslint looks good and should tell you where to need to cleanup.

**Comment by bogdan-zaharia-hs** [comment]
> That eslint looks good and should tell you where to need to cleanup.

👍  Fair enough, thanks.
