### ISSUE TITLE
Trailing comma setting "none" ignored

### ISSUE THREAD

**Issue by RadoslavMarinov** [prettier/prettier#10957]
Prettier Version: v6.4.0
VSCode version: 1.56.2

Even though I added [this](https://prettier.io/docs/en/options.html#trailing-commas) option into several places:
1) package.json `{"prettier.trailingComma": "none"}`
2) .prettierrc.json `{"trailingComma" : "none"}`
3) ~/.config/Code/User/settings.json : `{"prettier.trailingComma": "none",}`
the coma still keeps being added the end of the returned array.

Here is the code:
        
        function validateRequest() {
          return [
            body("status", "status is mandatory field").exists(),
            body(
              "echnicalInspectionReservationId",
              "echnicalInspectionReservationId is mandatory field"
            ).exists(), // <<<--- This comma keeps being added upon formatting
          ];
        }

Restarted VSCode every time setting is changed.

I made a [video ](https://www.youtube.com/watch?v=c9I99EN6_Qo)where you can see the behavior:

**Comment by thorn0** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff).

**Comment by RadoslavMarinov** [comment]
You could have pointed out what more do you need ? More information is too generic. In my prospective you have all you need.
Please point out what is missing !

**Comment by thorn0** [comment]
@RadoslavMarinov You haven't provided a [minimal reproduction](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff). We can't help you without it.
