### ISSUE TITLE
I encountered a format error caused by a space

### ISSUE THREAD

**Issue by crown3** [prettier/prettier#10953]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEYATnAIbwCiANnALYIwAUMAngA5wA0+bREbAZ24A6UWAAWOKgBMSUAJT5gAHSj58JGOiJqVa9flYdOqgzz6CkS02fyjhvfkJtmJU2QituZc4bVJsjN7S+AC8AHwutkZwEKiEkjJhoaH4yiAQAEYAVnDY6VG2+AD8Ce6Ftl4k5HAAKnAAHjDUdAxBidLyFfIm+uoAvjaDUMOqGFi4BMRk8PVNLfSwzI0winrqmtq6UTFW6bUUABq1APoUADIUALIUAHK16b1mjpbWfQZQENJwAGqkVOg4FZ4E0nrZgnIrABtAC6YIGYOGoyg42weDUcm+REYcBoixg3EgsFIOCgcCIaxsRIEMHw0ggtDCUVxrVgwhiyVS+yOpwu1zuDxAFVK9LA6HxwmmNTmMFuXzgjAKIC673UVlF4oYkuqlDxbRZEpiKqp0Bp+BwAgAChZyawwvgANZwFhhcKO534ACEKTS4A6cgKUCiAHkcnkYMInSwBDi9WyXgIVUVhKgpPBsRbrfxbSwk7YUxAiBRSBJGFBSPRXW8iup6bQoeX6DD7QatQmGxW4DCKv1jfpW-GLAJJf6EAWiyXxO13K6opjydOZNw63m++oiTASWSiMIAhwoNIAMIdRgr1TI6m0gAiOGkJdpqXWhB1cAWDDB86I59UgGgCVQAen-QhTVpAcH3wG872wbUZlfOMmAAoD1HSaQcAAN0eRCDGAc1pD2NAIAgdJ8H6XpAIMSD7xgmo3yWdJSEefAoHQKgqG4dJMlIL9lTIpCINvKipV1VkEJATJ0hVcjJIAKmk-AAAFsgEBp+KgiMhLgkT8Gk-9VEvfAwPtRV9AAHlQtDcNCdJUEI9JIneEzSHCTiiBM-8nKiEzMnwf97PUNzzPslV9I3LdyXtDUJQAczgZp4IAIRYABJaRFRAPgIBgCSsIAJTIbAr2DK5hE-WMRMJaBN1JckVUo6DSrAiriWqilVBATgMjYSYoAEZBQC4vgAHdLS4hBepQf5BtIaN2rEogSydGAAGU2BLUkouQGAiEBDq6EyOBpG+aRzlIKAovQUgYoAMULfwYFwM7kBAUh0BgCBZvEGBaCoAB1SR4AEVawDgJaxpwXA0PBlgnrAAReo60kBFta1Lv8ZBUH+JGOqUhp4vmsBFqWztzmq9HMa4EAcaW9aaAARXQTK4DJqgsZAVaiCRogns4-aqFm3hSRgH7bxgcRkAADgABg6xwkZ++a2Ce3g4E5tCmY6gBHBn4CzQQntIAQAFoyQOg7ZpILWcBIFGorRpAMZZimkdoHBNu2p2abgenGeZ1nN0yYXpFF5AACYOq2kkqHWw8GTtkAVYAVlm9AkdqUhMnGh3WbQwEkoPBgluIHAuoAQQPJbWBoX24H6fogA)

```sh
--parser babel
```

**Input:**

```jsx
function createElement(type, props, ...children) {
  return {
    type,
    props: {
      ...props,
      children: children.map(child =>
        typeof child === "object"
          ? child
          : createTextElement(child)
      ),
    }
  }
}

function createTextElement(text) {
  return {
    type: "TEXT_ELEMENT",
    props: {
      nodeValue: text,
      children: [],
    },
  }
}

function render(element, container) {
  const dom =
    element.type === "TEXT_ELEMENT"
      ? document.createTextNode("")
      : document.createElement(element.type)

  const isProperty = key => key !== "children"

    Object.keys(element.props)
      .filter(isProperty)
      .forEach(name => {
        dom[name] = element.props[name]
      })

  element.props.children.forEach(child =>
    render(child, dom)
  )

  container.appendChild(dom)
}

const Didact = {
  createElement,
  render
}
​
// const element = Didact.createElement(
//   "div",
//   { id: "foo" },
//   Didact.createElement("a", null, "bar"),
//   Didact.createElement("b")
// )
/** @jsx Didact.createElement */
const element = (
  <div id="foo">
    <a>bar</a>
    <b />
  </div>
)
const container = document.getElementById("root")
// ReactDOM.render(element, container)
Didact.render(element, container)

```

**Output:**

```jsx
SyntaxError: Unexpected character '​'. (50:1)
  48 |   render
  49 | }
> 50 | ​
     | ^
  51 | // const element = Didact.createElement(
  52 | //   "div",
  53 | //   { id: "foo" },
```

**Expected behavior:**
Maybe should auto remove the space which has problem

**Comment by thorn0** [comment]
U+200B (Zero Width Space) isn't valid whitespace in JavaScript, so this works as it should.
