### ISSUE TITLE
Using compound expression with comma operator as return value of curried function

### ISSUE THREAD

**Issue by LeMisterV** [prettier/prettier#10955]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzArlMTAXkwAoBDAJwHMBGAGkyuoCYBKYgPjI6O4poMmNdgB0oIeiAgAHGAEt0yUFUoQA7gAUqCNMhDkANuvIBPPVIBGlcmADWcGAGUZt+VGrIYlXHClwAW0s4ABMQ0IAZcg9ccmo4ADEISgDyGAUPfXJcGAhJEAALGADDAHUC+Xg0VzA4J11K+QA3StN9MDQLEHc0OEoYTRtqVORsI16pACs0AA8AIRt7RydyALgI9zhR8b8QaZmnd2pDOABFXAh4bcMJkFdKXsp9S3Jgw3yZSncYUvkQmAKyAAHAAGKSfCC9Uo2GT6T5wR5NLZSACOF3gg1kehQ5DQAFooHBQqF8pQ4Gj5GTBnERkgxjddr0AvIvD5GUcTudLls6TspDBXr9-oCkCx+TZ5IYjgBhCABWkgBEAVnyuF6ABVXtj6bcmr4AJJQcKwJxgL5yACCRqcMFMJ2uvQAvo6gA)

```sh
--parser babel
```

**Input:**

```js
const func = (arg1, arg2) => () => (arg1, arg2)

```

**Output:**

```js
const func = (arg1, arg2) => () => arg1, arg2;

```

**Expected behavior:**
Using compound expression with comma operator is not usual, but is valid syntax (and can be really useful).
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

It should be handled correctly by prettier in all cases, including this currying case.

Given input should result with no changes at all.
The current output is not valid JS syntax as the `arg2` variable is not declared, and this gives an error when executed.

**Comment by LeMisterV** [comment]
In the input I didn't write the ending semi-colon, and I didn't configure prettier about this, so a semi-colon was added.
This does not change anything on the issue. With or without semi-colon, the issue is the same.

**Comment by LeMisterV** [comment]
I tested the same code with prettier 2.2.1, and there was no problem with this previous version.

**Comment by fisker** [comment]
I wonder which PR breaks it.

**Comment by fisker** [comment]
Must break during function print.

Here says:

https://github.com/prettier/prettier/blob/81a1c463116f9dc8ec5e8059d70a9254675847e6/src/language-js/needs-parens.js#L351-L352

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/9992 Seems the one, but I don't know how.

**Comment by brodybits** [comment]
With updated playground (with help from its "second output" option under debug):

**Prettier 2.3.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzArlMTAXkwAoBDAJwHMBGAGkyuoCYBKYgPjI6O4poMmNdiHogIABxgBLdMlBVKEAO4AFKgjTIQ5ADYryAT23iARpXJgA1nBgBlSVZlRqyGJVxxxcALZm4ABNAoIAZcldccmo4ADEISl9yGFlXHXJcGAgxEAALGF89AHVcmXg0JzA4ey0ymQA3MqMdMDRTEBc0OEoYNUtqJORsfS7xACs0AA8AIUsbO3tyXzhQlzghke8QCcn7F2o9OABFXAh4Db1RkCdKLsodM3IAvRzJShcYIplAmFzkAA4AAziN4QLpFSySHRvOB3errcQAR1O8D6Um0KHIaAAtFA4EEgjlKHBkTJiX1ooMkMNLlsur4ZO5PHT9ocTmd1tTNuIYE8vj8-kgWDzLDI9PsAMIQXxUkCwgCsOVwXQAKk8MTSrvUvABJKAhWD2MDvaQAQX19hgRkOFy6AF87UA)

```sh
--parser babel
```

**Input:**

```jsx
const func = (arg1, arg2) => () => (arg1, arg2)
```

**Output:**

```jsx
const func = (arg1, arg2) => () => arg1, arg2;

```

**Second Output:**

```jsx
SyntaxError: 'Const declarations' require an initialization value. (1:46)
> 1 | const func = (arg1, arg2) => () => arg1, arg2;
    |                                              ^
  2 |
```

---

with TypeScript:

**Prettier 2.3.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzArlMTAXkwAoBDAJwHMBGAGkyuoCYBKYgPjI6O4poMmNdiHogIABxgBLdMlBVKEAO4AFKgjTIQ5ADYryAT23iARpXJgA1nBgBlSVZlRqyGJVxxxcALZm4ABNAoIAZcldccmo4ADEISl9yGFlXHXJcGAgxEAALGF89AHVcmXg0JzA4ey0ymQA3MqMdMDRTEBc0OEoYNUtqJORsfS7xACs0AA8AIUsbO3tyXzhQlzghke8QCcn7F2o9OABFXAh4Db1RkCdKLsodGCNJODQwShlpHMl32CKZQJguWQAA4AAzib4QLpFSySHTfF7derrcQAR1O8D6Um0KHIaAAtFA4EEgjlKHB0TJyX1ooMkMNLlsur4ZO5PEz9ocTmd1vTNuIYOQzH8AUCkCwBZYZHp9gBhCC+OkgF4AVhyuC6ABUhTiGVd6l4AJJQEKwexvD4wACCJvsj0OFy6AF8nUA)

```sh
--parser typescript
```

**Input:**

```tsx
const func = (arg1, arg2) => () => (arg1, arg2)
```

**Output:**

```tsx
const func = (arg1, arg2) => () => arg1, arg2;

```

**Second Output:**

```tsx
const func = (arg1, arg2) => () => arg1,
  arg2;

```

---

With Flow, the second output would be an error as well.
