### ISSUE TITLE
There is a problem when semi option is false in Typescript.

### ISSUE THREAD

**Issue by sakito21** [prettier/prettier#10951]
There is a problem when using Typescript and prettier and setting semi option false.

versions

```sh
"prettier": "^2.3.0",
"typescript": "^4.2.4",
```

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjOAzCAnOBRAQzAAsAKUgSgAIBeAPiuAB0oqrSBzAGwlQK6oEAzoKgBPCgDoeYAjACW0WlQBWcITEkYolSQFsIYANYBJPQAcucPQhhzFOyrQalmrNoKFD5HKEnbU9KrqmtqUADQsbAC+FBQssSDhIBDmCtBCyKAE2NgQAO4ACjkImSj8+QRimcmo2ERGcDAAyuZE8lAcyDDYAK5wydboACbDcMMAMgSdvQQccABiOHpyCp3IIAS9MBBJIMQwelwA6sTy8EJtYHDNpefyAG7nYhtgXnsdQnDYMIX1HCtkBh+F9kiohAAPABC9WMTWaBBsEw6cCBIIGIHBEOaHW4cAAir0IPA0VxQSA2tgvtgNjAxOZ1GBsPI0ntzMzYMd5MMYMRkAAOAAMyXZEC+x3q5g27PU3weqOSAEcifA-qkypshABaKBwcbjPa4ZXyXB-OaApDAskYr56eSk8neTpWQnE1FIHr9ZJ2VBcnl8pAAJm99XkXFxAGEIHoLSB1ABWPa9L4AFQIqDKVvJD36JigY1gzSZLJgAEF8806VYHXBotEgA)

```sh
# Options (if any):
semi: false,
```

**Input:**

```
beforeEach(() => {
  (global as any).location = jest.fn().mockImplementation(() => ({
    assign: () => jest.fn(),
  }))
})
```

In this case, you don't need a semi at the lead `;(global as any)`.

**Output:**

```jsx
beforeEach(() => {
  ;(global as any).location = jest.fn().mockImplementation(() => ({
    assign: () => jest.fn(),
  }))
})
```

**Expected behavior:**

```jsx
beforeEach(() => {
  (global as any).location = jest.fn().mockImplementation(() => ({
    assign: () => jest.fn(),
  }))
})
```

**Comment by thorn0** [comment]
This intended. Please see https://prettier.io/docs/en/rationale.html#semicolons
