### ISSUE TITLE
'default' modifier removed for unnamed classes

### ISSUE THREAD

**Issue by jeengbe** [prettier/prettier#10960]
**Prettier 2.3.0**
[Prettier Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAgDMBXKMGAS2gPUl2xglwB4BhAPgApIoBnGLhIVmSAmwCUYtgG4AOlAUABOs0bMF6IthKYYBLNj58CwAL4KQAGhAQADlWh9koPLggB3AAp4EzlNiYHtgAns42AEYMYADWcDAAynbYYJRQAObIgiRwNnAAthFwqOioADLYGSTY6XAAYsz5jFQZyCA6TNYgABYw+ZgA6t2U8HzJYHAJfiOUAG4jIW1gxl1pfHC4MF4M6U3I2pjrNgBWfAAeAELRcYnY+XBlaXD7gUcgp2cJaemYcACKJAg8Beh1yIGSuHWuDaMBCdjgfDAuEoDi6dmRsAGlFQMG6yAAHAAGGzoiDrAYMOxtdEIjazZ42ACOgPg23s-nafAAtFA4MVil18MzKPhtjU9kgDm91vlKFkhGC+N9fgCgc9Ja8wTBsBEsTi8UgAEw2QTYSiYb5sCD5CUgBEAVi6JHWABUdf4pWDZjkAJJQdCwBJIlEwACC-oSsN+IPWZjMQA) yields the following invalid code: [TypeScript Playground link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX1DBxig2IB4BhAPgAojUBnDGZTYgLnkoEovKA3ACghAAULFSxIZCiNG8AN4BfIUA).
The decorator is required for this example to work.

**Input:**

```typescript
declare function decorator<C>(constructor: C): C;

@decorator
default class {}
```

**Output:**

```typescript
declare function decorator<C>(constructor: C): C;

@decorator
class {}
```

**Expected behavior:**
The 'default' modifier should not be removed for unnamed classes.

**Comment by thorn0** [comment]
What does this modifier do?

**Comment by alexander-akait** [comment]
Seems like bug in parser, `default` without export :confused:

**Comment by jeengbe** [comment]
> What does this modifier do?

I'm not 100 sure what it actually does, but it is required for unnamed classes with decorators (see ts playground link). I think it might be a way to tell unnamed classes.

**Comment by jeengbe** [comment]
> Seems like bug in parser, `default` without export :confused: 

That's valid with a class decorator. I believe decorators are just a missing edge case since Prettier keeps the default modifier for exports.

**Comment by thorn0** [comment]
> That's valid with a class decorator

Could you please provide a reference to TypeScript docs (or at least an issue in the TypeScript repo) that would confirm your words? I'm sure you've discovered a bug in TypeScript.

**Comment by jeengbe** [comment]
I can't, I just assumed it was correct as it made sense to me and there were no errors. I don't really get why this would be a bug in TypeScript.

**Comment by thorn0** [comment]
> I can't

Prettier doesn't have to support it then. Reported the bug here https://github.com/microsoft/TypeScript/issues/44319

**Comment by jeengbe** [comment]
This might be related: [Prettier Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAgDMBXKMGAS2gPUl2xglwApIoBnGXEi5pAtigBPAJQChwgNwAdKHIACdZo2ZyA9OoIAHfDCpxcAWkoBzKMzhz0RbCUwwCWbBw4FgAXzkgANCAjaVNAcyKB4uBAA7gAKeAghKNiYkdjCIX4ARgxgANZwMADK2thglFCmyNwkcH5wALYZcKjoqAAyQqYk2KZwAGLMdYxU5cggdky+IAAWMHWYAOpTlPAcxWBwBfHLlABuy8KjYK6TZRyGMNEMpoPItphnfgBWHAAeAELZeYXYdXCtZXBbkkHiBni8CmVTJg4ABFEgQeBA+41EDFXBnXCjGDCbRwDhgXCUQKTXRlGDzSioGBTZAADgADH5dBAzvMGNpRro8YYdoC-ABHeHwS4BBJjDhGKBwJpNSb4QWUfCXbo3JB3EFnOqUSo8FEcSHQuEIwFq4EomDYDIUqk0pAAJj83GwlEwkIAwhA6qqQHiAKyTEhnAAqloS6pRO2qAEkoOhYAUCUSYABBWMFbHQpFnDweIA).
`// prettier-ignore` still removes the 'default' modifier despite the comment.
