### ISSUE TITLE
JSX Bracket Spacing

### ISSUE THREAD

**Issue by okwolf** [prettier/prettier#1097]
Should the `bracketSpacing` option apply to JSX expressions, including the spread operator? It seems to me that this would be more consistent with regard to spacing. Another option would be to add another option to control this spacing just for usage within JSX. The React plugin for ESLint already has a rule that works well for this: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md. In prettier, the lack of spacing around the curly braces appears to be hardcoded, based on the snippet I found in the printer below.

https://github.com/prettier/prettier/blob/master/src/printer.js#L1227:
```js
    case "JSXSpreadAttribute":
      return concat(["{...", path.call(print, "argument"), "}"]);
    case "JSXExpressionContainer": {
      const parent = path.getParentNode(0);

      const shouldInline = n.expression.type === "ArrayExpression" ||
        n.expression.type === "ObjectExpression" ||
        n.expression.type === "ArrowFunctionExpression" ||
        n.expression.type === "CallExpression" ||
        n.expression.type === "FunctionExpression" ||
        n.expression.type === "JSXEmptyExpression" ||
        (parent.type === "JSXElement" &&
          (n.expression.type === "ConditionalExpression" ||
            isBinaryish(n.expression)));

      if (shouldInline) {
        return group(
          concat(["{", path.call(print, "expression"), lineSuffixBoundary, "}"])
        );
      }

      return group(
        concat([
          "{",
          indent(
            options.tabWidth,
            concat([softline, path.call(print, "expression")])
          ),
          softline,
          lineSuffixBoundary,
          "}"
        ])
      );
    }
```

**Comment by yamafaktory** [comment]
Hi @okwolf, please refer to @vramana's comment in https://github.com/prettier/prettier/issues/989:
>{expression} in JSX is similar to (expresson) in JS. Along this line of argument, there shouldn't be spaces around expression surrounded by {}.

**Comment by okwolf** [comment]
@yamafaktory thanks for the reference. I'm aware that JSX expressions do not currently have spaces around them in prettier, but I don't believe they have the same use case as `(expression)` since their use is not for operator precedence. To me the usage is closer to `{}` for object literals since the purpose is to separate a value from non-values. I know the actual syntax for an object literal is `{{ }}` which is already controlled by `bracketSpacing`. So should values inside JSX expressions other than objects be allowed to have the same spacing?

I really want to migrate away from other ESLint formatting rules to using prettier, but jsx-curly-spacing seems to be the last formatting rule holding me back.

**Comment by vjeux** [comment]
We are now past 1.0 and not going to do any major formatting changes anymore. If you really want this feature, I would recommend forking prettier.

**Comment by ercpereda** [comment]
I think this could be discussed for future versions and added like an option.
