### ISSUE TITLE
Optionally enable comma first.

### ISSUE THREAD

**Issue by JAForbes** [prettier/prettier#1098]
I'd like to propose adding an option to support comma first.

Comma last has exceptions, comma first works in all cases.  

Great for diffs, works for function args, array literals, object literals and errors stick out like a sore thumb!  In my opinion it's a better editing experience too, because we tend to add items to the end of lists more often than we prepend, we don't have to juggle commas as often.

It's also great in editors for swapping lines, in a composition pipeline, in virtual dom, in a list literal.  It's effortless because the comma doesn't need to change.  With comma last, there's a greater likelihood you'll need to juggle that common final case.

I know its not the standard way to write in JS, but it is used and enjoyed by many in the community.  I think its worthy of being a configurable option in prettier.

Here's a great walkthrough / justification of comma first here https://gist.github.com/isaacs/357981, (understandably considering the author) it's also part of the [npm coding style](https://docs.npmjs.com/misc/coding-style)

I've got lots of "weird" things I do in my code, but I'd give them all up for comma first.  Since I've switched to it, I've had less bugs in my virtual dom code, less git conflicts, and overall more fun coding (particularly point free).

Even though comma last isn't popular in the JS community, I do think it fits perfectly into Crockford's "The better parts" reasoning for e.g. the switch statement.  If there's 2 options, 1 sometimes fails, and the other never fails, the choice is obvious.

**Comment by lydell** [comment]
Sounds like you want `--trailing-comma all` and [trailing-function-commas](http://babeljs.io/docs/plugins/syntax-trailing-function-commas/) rather than comma-first.

**Comment by JAForbes** [comment]
Great suggestion.  If it was in the language *today* sure.  But I don't use babel, and what about node?

I also really *like* comma first 😄 , it works today, and it looks great!  If I had to go back to comma last 

Putting aside how foreign it seems, it really is aesthetically pleasing.  Look at the alignment of symbols.

```js
[ 1
, 2
, 3
  [ 4
  , 5
  , 6
  ]
]
```

But the proposal is interesting, thank you for pointing it out. @lydell

**Comment by lydell** [comment]
Yes, it looks kinda neat. But your main argument was to make diffs, merges as well as moving and adding lines easier, wasn’t it? If so you miss out by using comma-first instead of trailing-comma. When you use trailing comma, those things work on _all_ lines. With comma-first, it works on all _but the first_ line. ¯\\\_(ツ)\_/¯

**Comment by JAForbes** [comment]
@lydell that's true.  If we had comma last in the language I'd switch to that because I just want whatever is the least error prone and requires the least tooling. 

But in all those cases I've found its always a latter line that changes the most (I can't think of one time I've had a conflict on the first line).

At the moment, for my rationale at least (least errors, least tooling) comma first still wins .  Perhaps later, comma last may be officially a part of the language, and I'd change my position there.

With that said, is it likely this would be added to prettier?

**Comment by lydell** [comment]
(Just noting here that trailing commas in functions is part of ES2017 (http://2ality.com/2016/02/ecmascript-2017.html#the-features-of-ecmascript-2017) and supported in the latest versions of Firefox, Safari and Edge (and the next Chrome version) (http://kangax.github.io/compat-table/es2016plus/#test-trailing_commas_in_function_syntax). Not Node.js yet though :( )

**Comment by JAForbes** [comment]
@lydell ah that's awesome!  In that case no worries!  I'm sure node will add it soon.  I'll start using comma last as soon as it lands there.  No point adding it to prettier if this is a sure thing.

**Comment by wellcaffeinated** [comment]
+1
I'd like to suggest reopening this feature request. Regardless of the trailing comma support, I still love comma-first formatting. It's basically the only thing keeping me from using any kind of JS prettifier... nobody supports comma-first

**Comment by scurker** [comment]
👍 

I'd love to see this implemented as well. You can technically achieve this with `eslint --fix` and `comma-style: ['warn', 'first']` but I'd rather not see warnings in eslint for something that can be cleaned up with prettier.

**Comment by lydell** [comment]
@scurker Seems like you're looking for [prettier-eslint](https://github.com/kentcdodds/prettier-eslint).
