### ISSUE TITLE
I am sorry, who the fuck thought this was a good idea?

### ISSUE THREAD

**Issue by VottusCode** [prettier/prettier#10998]
Hello,

recently Prettier started formatting my code in the following way:
```vue
  <router-link
    v-for="item in userNavigation"
    :key="item.name"
    :to="item.href"
    class="
      block
      px-4
      py-2
      text-base
      font-medium
      text-gray-500
      hover:text-gray-800
      hover:bg-gray-100
    "
  >
    {{ item.name }}
  </router-link>
```

What in the hell? The class formatting is absolutely disgusting, I fail to believe that there is someone out there who seriously likes this.

My question is, how in the living hell can I disable this disgusting nastiness.

**Comment by kachkaev** [comment]
![61915826-33EE-4D75-981C-09B54BF4FBD9](https://user-images.githubusercontent.com/608862/120230647-b4664580-c247-11eb-9767-dc0d113a5c72.jpeg)

✅

**Comment by VottusCode** [comment]
> 
> 
> ![61915826-33EE-4D75-981C-09B54BF4FBD9](https://user-images.githubusercontent.com/608862/120230647-b4664580-c247-11eb-9767-dc0d113a5c72.jpeg)
> 
> ✅

Oh right, comment a totally useless thing instead of something useful.

**Comment by fisker** [comment]
I think you are right, we shouldn't make this change before you agree. Currently, you can uninstall Prettier to disable, and this will be the only way. Sorry again.
