### ISSUE TITLE
computed-property-even-spacing: do not break on property access

### ISSUE THREAD

**Issue by jmagrippis** [prettier/prettier#1100]
It seems prettier will happily line-break on the bracket when you try to access an array key or object property:

```js
weNeedToReachTheEightyCharacterLimitXXXXXXXXXXXXXXXX.someNode.childrenInAnArray[
  0
]
```

I noticed this when it triggered the standard/computed-property-even-spacing eslint rule. I don't know if there is a convention there, but I have never seen anyone break at that point. I'd guess most people would break before the array itself?

```js
weNeedToReachTheEightyCharacterLimitXXXXXXXXXXXXXXXX.someNode
  .childrenInAnArray[0]
```

This also happens when you try to access an object key using bracket notation:

```js
weNeedToReachTheEightyCharacterLimitXXXXXXXXXXXXXXXX.someNode.childrenInAnObject[
  dynamicKey
]
```

So is this "intended behaviour", or something worth taking into account?

---

edit: [sample code](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20weNeedToReachTheEightyCharacterLimitXXXXXXXXXXXXXXXX%20%3D%20%7B%5Cn%20%20someNode%3A%20%7B%5Cn%20%20%20%20childrenInAnArray%3A%20%5B'I%20am%20a%20child'%2C%20'me%20too!'%5D%2C%5Cn%20%20%20%20childrenInAnObject%3A%20%7B%5Cn%20%20%20%20%20%20one%3A%20'I%20am%20another%20child'%2C%5Cn%20%20%20%20%20%20two%3A%20'me%202!'%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%3B%5Cn%5Cnconst%20theKey%20%3D%20'one'%3B%5Cnconsole.log(%5Cn%20%20weNeedToReachTheEightyCharacterLimitXXXXXXXXXXXXXXXX.someNode.childrenInAnArray%5B0%5D%2C%5Cn%20%20weNeedToReachTheEightyCharacterLimitXXXXXXXXXXXXXXXX.someNode.childrenInAnObject%5BtheKey%5D%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D).

**Comment by SimenB** [comment]
Just pointing out that you can add your sample here, and copy the URL: https://prettier.github.io/prettier/

**Comment by vjeux** [comment]
Thanks! Right now prettier doesn't a way for multiple .properties to break without a call at the end. So the only place where it can break is the [] which isn't usually what you expect.

**Comment by vjeux** [comment]
@jmagrippis hey, sorry it's been so long. It would be very helpful to get some real piece of code that triggered this if you still have it. We're trying to figure out what's the best thing to do here and it's hard without seeing some real code. Feel free to rename variables if there's anything sensitive, what's most important is the shape of the code than the precise names. Thanks!

**Comment by jmagrippis** [comment]
@vjeux 
We were running it through some old code that was kinda migrated to a newer project, and it's [this test file][] that triggered it, at line 54. Disappointing, I know, as we are using `findDOMNode` instead of enzyme's `find` and `childAt` chains, which is what most people would have done and wouldn't have triggered this in the first place!

[this test file]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22import%20React%20from%20'react'%3B%5Cnimport%20%7B%20findDOMNode%20%7D%20from%20'react-dom'%3B%5Cnimport%20%7B%20shallow%2C%20mount%20%7D%20from%20'enzyme'%3B%5Cn%5Cnimport%20Scroll%20from%20'.%2FScroll'%3B%5Cnimport%20styles%20from%20'.%2FScroll.css'%3B%5Cn%5Cn%2F%2F%20https%3A%2F%2Fgithub.com%2Fairbnb%2Fenzyme%2Fblob%2Fmaster%2Fdocs%2Fguides%2Fjsdom.md%5Cnconst%20jsdom%20%3D%20require('jsdom').jsdom%3B%5Cnglobal.document%20%3D%20jsdom('')%3B%5Cnglobal.window%20%3D%20document.defaultView%3B%5CnObject.keys(document.defaultView).forEach(property%20%3D%3E%20%7B%5Cn%20%20if%20(typeof%20global%5Bproperty%5D%20%3D%3D%3D%20'undefined')%20%7B%5Cn%20%20%20%20global%5Bproperty%5D%20%3D%20document.defaultView%5Bproperty%5D%3B%5Cn%20%20%7D%5Cn%7D)%3B%5Cnglobal.navigator%20%3D%20%7B%5Cn%20%20userAgent%3A%20'node.js'%5Cn%7D%3B%5Cn%5Cndescribe('Scroll'%2C%20()%20%3D%3E%20%7B%5Cn%20%20let%20component%3B%5Cn%20%20beforeEach(()%20%3D%3E%20%7B%5Cn%20%20%20%20component%20%3D%20shallow(%5Cn%20%20%20%20%20%20%3CScroll%3E%5Cn%20%20%20%20%20%20%20%20Children!%5Cn%20%20%20%20%20%20%3C%2FScroll%3E%5Cn%20%20%20%20)%3B%5Cn%20%20%7D)%3B%5Cn%5Cn%20%20it('hides%20the%20scrollbars%20when%20mounted'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20let%20spy%20%3D%20jest.fn(Scroll.prototype.hideScrollbars)%3B%5Cn%20%20%20%20Scroll.prototype.hideScrollbars%20%3D%20spy%3B%5Cn%20%20%20%20component%20%3D%20mount(%3CScroll%20hideScrollbars%20%2F%3E)%3B%5Cn%20%20%20%20expect(spy).toBeCalled()%3B%5Cn%20%20%7D)%3B%5Cn%5Cn%20%20it('optionally%20shows%20the%20scrollbars%20when%20mounted'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20let%20spy%20%3D%20jest.fn(Scroll.prototype.hideScrollbars)%3B%5Cn%20%20%20%20Scroll.prototype.hideScrollbars%20%3D%20spy%3B%5Cn%20%20%20%20component%20%3D%20mount(%3CScroll%20%2F%3E)%3B%5Cn%20%20%20%20expect(spy).not.toBeCalled()%3B%5Cn%20%20%7D)%3B%5Cn%5Cn%20%20it('adds%20padding%20to%20inner%20element%20to%20hide%20scrollbar'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20Scroll.prototype.getScrollbarWidth%20%3D%20()%20%3D%3E%201000%3B%5Cn%20%20%20%20component%20%3D%20mount(%5Cn%20%20%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%3CScroll%20hideScrollbars%20%2F%3E%5Cn%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20)%3B%5Cn%20%20%20%20%2F%2F%20TODO%3A%20refactor%20to%20not%20use%20findDOMNode%5Cn%20%20%20%20expect(%5Cn%20%20%20%20%20%20findDOMNode(component.instance()).getElementsByClassName(styles.inner)%5B0%5D.style.paddingRight%5Cn%20%20%20%20).toBe('1000px')%3B%5Cn%20%20%7D)%3B%5Cn%5Cn%20%20describe('its%20public%20API'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20let%20mock%3B%5Cn%20%20%20%20let%20scrollToSpy%3B%5Cn%20%20%20%20let%20getScrollElMock%3B%5Cn%20%20%20%20let%20getWrapperElMock%3B%5Cn%20%20%20%20beforeEach(()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20scrollToSpy%20%3D%20jest.fn()%3B%5Cn%20%20%20%20%20%20getScrollElMock%20%3D%20%7B%5Cn%20%20%20%20%20%20%20%20scrollTop%3A%200%2C%5Cn%20%20%20%20%20%20%20%20scrollHeight%3A%2044%2C%5Cn%20%20%20%20%20%20%20%20clientHeight%3A%2045%5Cn%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20getWrapperElMock%20%3D%20%7B%5Cn%20%20%20%20%20%20%20%20clientHeight%3A%2044%5Cn%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20mock%20%3D%20%7B%5Cn%20%20%20%20%20%20%20%20scrollTo%3A%20scrollToSpy%2C%5Cn%20%20%20%20%20%20%20%20getScrollEl%3A%20()%20%3D%3E%20getScrollElMock%2C%5Cn%20%20%20%20%20%20%20%20getWrapperEl%3A%20()%20%3D%3E%20getWrapperElMock%5Cn%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%7D)%3B%5Cn%5Cn%20%20%20%20it('exposes%20a%20scrollTo%20method'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20expect(mock.getScrollEl().scrollTop).toBe(0)%3B%5Cn%20%20%20%20%20%20Scroll.prototype.scrollTo.call(mock%2C%2022)%3B%5Cn%20%20%20%20%20%20expect(mock.getScrollEl().scrollTop).toBe(22)%3B%5Cn%20%20%20%20%7D)%3B%5Cn%5Cn%20%20%20%20it('exposes%20a%20scrollToBottom%20method%20which%20uses%20the%20scrollheight'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20Scroll.prototype.scrollToBottom.call(mock)%3B%5Cn%20%20%20%20%20%20expect(scrollToSpy).toBeCalledWith(44)%3B%5Cn%20%20%20%20%7D)%3B%5Cn%5Cn%20%20%20%20it('exposes%20a%20scrollToTop%20method%20which%20scrolls%20to%200'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20Scroll.prototype.scrollToTop.call(mock)%3B%5Cn%20%20%20%20%20%20expect(scrollToSpy).toBeCalledWith(0)%3B%5Cn%20%20%20%20%7D)%3B%5Cn%5Cn%20%20%20%20it('exposes%20a%20isScrollable%20method%20which%20tell%20us%20if%20the%20scroll%20area%20has%20become%20scrollable'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20expect(Scroll.prototype.isScrollable.call(mock)).toBe(false)%3B%5Cn%20%20%20%20%20%20getWrapperElMock%20%3D%20%7B%5Cn%20%20%20%20%20%20%20%20clientHeight%3A%2046%5Cn%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20mock%20%3D%20%7B%5Cn%20%20%20%20%20%20%20%20scrollTo%3A%20scrollToSpy%2C%5Cn%20%20%20%20%20%20%20%20getScrollEl%3A%20()%20%3D%3E%20getScrollElMock%2C%5Cn%20%20%20%20%20%20%20%20getWrapperEl%3A%20()%20%3D%3E%20getWrapperElMock%5Cn%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%20%20expect(Scroll.prototype.isScrollable.call(mock)).toBe(true)%3B%5Cn%20%20%20%20%7D)%3B%5Cn%20%20%7D)%3B%5Cn%5Cn%20%20it('renders%20children'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20expect(component.text()).toBe('Children!')%3B%5Cn%20%20%7D)%3B%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks, that's great. It's going to look like this after #1036:

```js
expect(
  findDOMNode(component.instance()).getElementsByClassName(styles.inner)[0]
    .style.paddingRight
).toBe("1000px");
```

**Comment by jmagrippis** [comment]
Great, quick survey and other devs here agree: that'd be perfect.

**Comment by lili21** [comment]
Still got the issue. I am using prettier@1.4.4

**Comment by prewk** [comment]
See #1327
