### ISSUE TITLE
#region comments should be ignored in vs-code

### ISSUE THREAD

**Issue by farqis** [prettier/prettier#11005]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbl9-VHwGQ14+AEYPL3i-DKyAI1z8ACZC7wB6OvwAB2jcJwBaHGYoGjh6uoBiNmY8eIAhdoBhQ1NNdJL8BvxJ-DAZuHw6OE0wahwm3Gh5koCssB4eAs9jhbB5Kpv8F0elgBFV9c3t3f3Dn2KFqcGHQLgBmWoAhabeQAFkezygSxaHDa1E63V6-QGCDow1G+Ama1mxwRfgRLhA4hAEAOo00yFAhmo1AgAHcAApMhD0lDGVmGACe9KpZWohjAAGsOABlJri8LMZAwajoMwgOAAWzKcDoWzoABlDFx0IZmHAAGI0DWGGCcRW89AwCCU4QwDUkChCHDwTRysBwaXc704ezegXIcCaYUgcKmagwdli5jW5BGExqgBWmgAHmMxZKZYYNXB9eE4KnjKYqVns9KFboAIroCDwCvpqly6hxiNlQzakgulrhGAUHB0GBCZAADgADB2WaYKGKmhHkXHHC6AI7N+CJmk8kAzdpQdh6l1sbc4NiJ00ppBpqsgUwanBKlVq7RcRs78v3ytqmA+1HcdJyQKoqWVQwdAVSYIA1O91U0ABWF0bDgAAVPseQfNV7FVABJKAtlgaUfgOABBIjpRgAVdDbUwXBcIA)

```sh
--parser babel
```

**Input:**

```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};
  if (a == 1) {
    if (b == 2) {
// prettier-ignore
//#region B-Cases
      // C case description
      if (c==1) {
        c = 2
      }
      // D case description
      if (d==3) {
        d = 4
      }
// prettier-ignore
//#endregion B-cases
    }
  }
}
```

**Output:**

```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver,
}) {
  if (!greeting) {
    return null;
  }
  if (a == 1) {
    if (b == 2) {
      // prettier-ignore
      //#region B-Cases
      // C case description
      if (c==1) {
        c = 2
      }
      // D case description
      if (d==3) {
        d = 4
      }
      // prettier-ignore
      //#endregion B-cases
    }
  }
}

```

**Expected behavior:**

//#region comments in VS Code should be ignored by Prettier either by default, or it should be possible to do so via Config file entry, e.g. "ignoreRegion": true.

Usually developers keep //#region comments left aligned so that they are easy to spot and use. Prettier indents the //#region comments making them impossible to spot in large files, especially those with heaving commenting. Large files are exactly where regions are really needed and useful.

It's also noteworthy that the existing // prettier-ignore construct does not work for the case either and would be an ugly solution anyways forcing developers to write extra code with every region. Since the behavior is almost always required globally, hence config file entry is the most advisable solution.

**Comment by thorn0** [comment]
@farqis Do you have any references confirming that formatting regions like this is a common practice?
