### ISSUE TITLE
Add support for flow type spread operator

### ISSUE THREAD

**Issue by NameFILIP** [prettier/prettier#1101]
An object type spread was added to the newest version of Flow: https://github.com/facebook/flow/blob/master/Changelog.md#v0420

See https://github.com/facebook/flow/issues/2626

Looks like prettier-atom plugin doesn't support it yet

**Comment by existentialism** [comment]
Support for this should be landing in Babylon soon: https://github.com/babel/babylon/pull/418

**Comment by vjeux** [comment]
There's a PR open for the flow parser https://github.com/prettier/prettier/pull/1064
