### ISSUE TITLE
support an option to skip indentation for top level functions in JS

### ISSUE THREAD

**Issue by asurkov** [prettier/prettier#11012]
It is a typical for the web to put JS into anonymous function block to avoid global context pollution, for example
```
(function() {
let a = 3;
}){};
```
will avoid leaking `a` variable into `window` object.

Running this example through prettifier indents the body of the anonymous function this way:
```
(function() {
  let a = 3;
}){};
```

This top anonymous function has nothing with the code logic, so it'd be nice to not indent the function body pretending as the function didn't exist at all.

Unfortunately it seems there's no way to skip indention in this case,  perhaps expect rangeStart/rangeEnd option, which is not handy in this case, because you have to recompute offsets for each change.

So, it'd be nice to support something similar to eslint indent outerIIFEBody rule (https://eslint.org/docs/rules/indent#enforce-consistent-indentation-indent) or allow using start-range/end-range inline, for example,

(function() {
// prettier-start-range
let a = 3;
// prettier-end-range
}){};

**Comment by alexander-akait** [comment]
Sorry, out of scope prettier

**Comment by thorn0** [comment]
This might have made sense in 2012, but not in 2021. Sorry!

**Comment by asurkov** [comment]
> This might have made sense in 2012, but not in 2021. Sorry!

Could you elaborate please? It might be out of scope but what is the best practice to avoid using top level functions if it is what you meant?

**Comment by thorn0** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

**Comment by fisker** [comment]
Actually, there is still one need for IIFE, 😄 

```js
// TODO: Use top-level await when we target Node.js 14
(async () => {
	await foo;
	// ...
})();
```

But we should still indent code inside for this case.

**Comment by asurkov** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

this question is totally out of box but just in case, how do people bundle and minify those and build sourcemaps?

**Comment by alexander-akait** [comment]
@asurkov babel + webpack/rollup/esbuild, some developers drop old browsers supports and do not use babel
