### ISSUE TITLE
JSX Brackets alignments

### ISSUE THREAD

**Issue by tleunen** [prettier/prettier#1102]
Why are [these 2 different](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%7BshowThis%20%26%26%20(%5Cn%20%20%5Ct%3Cdiv%3E%5Ct%5Ct%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%5Ct%3CYolo%20%2F%3E%5Ct%5Ct%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%5Ct%3C%2Fdiv%3E%5Cn)%7D%5Cn%5Cn%2F%2F%20And...%5Cn%5Cn%5Cn%3Cdiv%3E%5Cn%5Ct%7BshowThis%20%26%26%20(%5Cn%20%20%20%20%5Ct%3Cdiv%3E%5Ct%5Ct%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%5Ct%3CYolo%20%2F%3E%5Ct%5Ct%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%5Ct%3C%2Fdiv%3E%5Cn%5Ct)%7D%5Cn%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)?

```js
 {showThis && (
    <div>		                        
      <Yolo />		                    
    </div>
)}
```
gives this following, which is fine, although I don't know why the colon is needed.
```js
{
  showThis &&
    <div>
      <Yolo />
    </div>;
}
```

But then this code:
```js
<div>
  {showThis && (
    <div>		                        
      <Yolo />		                    
    </div>
)}
</div>
```

gives this, and the brackets are not aligned the same. (I'd expect them to be on the same column)
```js
<div>
  {showThis &&
    <div>
      <Yolo />
    </div>}
</div>;
```

**Comment by vjeux** [comment]
The first one is a block statement, no-one ever writes them directly like that but instead after a `if ()` or `for ()`...

For the second one, it is indeed not optimal that it doesn't put a \n but the implementation for it is actually not straightforward. So we may want to fix it at some point but it's going to take some work and is lower pri than other things we need to work on.

**Comment by vjeux** [comment]
This is also tracked by https://github.com/prettier/prettier/issues/765
