### ISSUE TITLE
Allow Object Literal to be Explicit with String Names

### ISSUE THREAD

**Issue by sebmarkbage** [prettier/prettier#1103]
```js
var foo = {
  'bar': 123
};
window.bar = function() {
  console.log(foo['bar']);
}
```

Turns into:

```js
var foo = {
  bar: 123
};
window.bar = function() {
  console.log(foo['bar']);
}
```

Note that the object literal lost its explicit string encoding. This breaks Google Closure Compiler's advanced mode heuristic/convention around property name mangling. Uglify has this mode too.

Maybe an explicit mode would be good for this? Or should it be default?

**Comment by bakkot** [comment]
Uuuugh. I really dislike the idea of making formatting decisions based on tools which treat formatting information as semantic. Do those tools not have a way of providing that information out-of-band from the AST, say with a comment?

**Comment by sebmarkbage** [comment]
Anyone using those tools (like React is planning on doing) wouldn't really like that noise since it's all over the place.

**Comment by yamafaktory** [comment]
@sebmarkbage this should be fixed with #1108. @bakkot I don't see keeping object keys as strings (when they originaly were) as a formatting decision, IMHO those should be kept.

**Comment by bakkot** [comment]
> I don't see keeping object keys as strings (when they originaly were) as a formatting decision

This statement confuses me.

`({a:0})` and `({'a':0})` are semantically identical. Engines parse them to the same internal representation. The presence or absence of quotes is no more significant than whitespace. How could it be anything other than a formatting decision?

**Comment by yamafaktory** [comment]
@bakkot Agree, but if we change `'a'` to be `a` then this is a formatting decision and I don't think Prettier should modify it.

**Comment by bakkot** [comment]
@yamafaktory Isn't the point of prettier to make your formatting decisions for you? It's a formatter. That's what it does.

**Comment by yamafaktory** [comment]
@bakkot I partially agree. Prettier is opinionated but in this case, I think this is somehow different than just indenting a piece of code in a different way or removing unnecessary parenthesis. Keeping the original quotes can also help if as a team you want to be consistent in the way you declare an object (let's say in big config file), e.g. https://prettier.github.io/prettier/#%7B%22content%22%3A%22var%20a%20%3D%20%7B%5Cn%20%20%5C%22prop%20as%20string%5C%22%3A%201%2C%5Cn%20%20%5C%22propA%5C%22%3A%202%2C%5Cn%20%20%5C%22propB%5C%22%3A%203%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

I will let @vjeux / @jlongster decide on that.

**Comment by bakkot** [comment]
Also, context: #90, #838

**Comment by SimenB** [comment]
I know there's an aversion to options, but I'd like to see a subset of the options eslint provides: `always`, `as-needed`, and `consistent-as-needed`. Meaning it either always puts it in, it just puts it in where it's syntactically needed, or or quotes all properties if any is needed. There are more options. Missing is `consistent`, but I don't think that's needed as an option.

The advantage is that if you always want to quote it (like this issue) it's possible, but if you want to be quote-less, that's also a possibility. I threw in `consistent-as-needed` as well (which is what I use (used I suppose since prettier)) as I find it more readable to not mix quoted and unquoted props, but I can see the argument that it's not needed.

Source: http://eslint.org/docs/rules/quote-props

**Comment by vjeux** [comment]
@SimenB in this case none of those options would work, Google Closure Advanced mode gives a meaning to the presence or absence of quotes, so we cannot change them without changing the meaning of the program.

**Comment by SimenB** [comment]
Oh, didn't know that. A 4th. option, "don't touch" then 😁

**Comment by jlongster** [comment]
The google closure use case is a pretty strong one. I think we should respect the original style of object keys. I can't imagine many people fight over whether or not keys should be as strings or not, so I don't think we're solving much of a pain point by being opinionated about it, and only make it harder for tools like closure.

While you can *infer* that `{ 'foo': bar }` is the same as `{ foo: bar }`, I don't think it's too far to think of the string as more of an expression like `{ ['foo']: bar }`. Basically I don't think closure is in the wrong to work the way it does. For it's advanced mode, it already is very restrictive about what's allowed and you can't do a lot that you normally could.

**Comment by bakkot** [comment]
@jlongster, re:

> I can't imagine many people fight over whether or not keys should be as strings or not

This is exactly the sort of formatting issue which I want a tool like prettier to handle. (That's why I implemented the current behavior [in the first place](https://github.com/prettier/prettier/pull/90)!) It would be easy enough to add yet another `eslint --fix` to get around prettier not doing this, but it would make me sad.

**Comment by jlongster** [comment]
I agree that this is the sort of stuff I'd like prettier to normalize, but when it comes at the cost of something powerful like Closure's advanced mode (which is really amazing), I think we should back off on it. When there are places that we can make these decisions without affecting anything else very much, I'm all for it, but we have to also recognize the existence of other tools and how they work to some extent.

**Comment by SimenB** [comment]
Prettier should work to make code readable and consistent for humans, not tools. Can't people needing the quotes just add `// prettier-ignore`? Or at least behind an option, I don't want to re-add eslint rules I removed when I started using prettier

**Comment by bakkot** [comment]
Hm. Does the Closure compiler compile `({ ['foo']: bar })` to `({ 'foo': bar })`? I believe it does, in which case people who want to signal that information to Closure could use `['foo']` instead of `'foo'` without too much noise, and prettier would leave it alone. It's more explicit anyway.

@sebmarkbage thoughts? Would that work for your team?

**Comment by stringham** [comment]
Changing all of our Closure annotated JavaScript to use `{['foo']: bar}` would be very prohibitive. There wouldn't be an easy way to apply a change like that throughout our large code base.

It looks like the closure compiler doesn't treat them the same:

`console.log({['foo']:4})` outputs `var a={};console.log((a.foo=4,a));` ([link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconsole.log(%257B%255B'foo'%255D%253A4%257D)%253B%250A%250A))

where `console.log({'foo':4})` outputs `console.log({foo:4});` ([link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconsole.log(%257B'foo'%253A4%257D)%253B%250A%250A))

and `console.log({foo:4})` outputs `console.log({a:4});` ([link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconsole.log(%257Bfoo%253A4%257D)%253B%250A%250A))

adding a `// prettier-ignore` comment to all of the places we need to work with data from the server would also not be feasible.

I appreciate @jlongster's insight on recognizing the existence of other tools and how they work to some extent.

**Comment by bakkot** [comment]
It looks like this has the effect you want - property names don't get mangled - but it's a shame it doesn't treat them exactly the same. Maybe file a bug with them?

---

> There wouldn't be an easy way to apply a change like that throughout our large code base.

Sure there is; just write a codemod. It's super short:

```js
module.exports = function () {
  return {
    visitor: {
      ObjectProperty(path, state) {
        let node = path.node;
        if (node.key.type !== 'StringLiteral' || node.computed) return;
        node.computed = true;
      }
    }
  };
}
```

Save that as `fix-keys.js`, then just `codemod --plugin ./fix-keys.js src/`, where `codemod` is [babel-codemod](https://github.com/square/babel-codemod). I'm sure it's also straightforward with jscodeshift, if you already have your tooling set up for it instead.

**Comment by vjeux** [comment]
In practice, I haven't seen people successfully adopting the closure compiler with advanced mode outside of Google internal codebase and only a single person using it raised an issue about it. So, given this lack of usage, I'm going to close this issue for now. If React actually manages to do it, I may reconsider.

**Comment by emirotin** [comment]
Let me bump this one with another use-case. It's a matter of visual style for me, but the changes prettier makes make the code harder to read.

For context I'm working on some utility that tests the text for the specific patterns.
Here's a screenshot of my tests file:
![Alt text](https://monosnap.com/file/cutjRUvJghqZW0ZwlMI9ZjRTcfilVv.png)

Now if you look at the hashes defining the tests and the expected results, you can see that `PT`, `y` and `x7` keys they're unquoted and thus are not highlighted as strings.  Which makes it harder to scan the text.

**Comment by kentor** [comment]
same thing with classnames in jsx:
```jsx
<Something
  className={cx({
    'disabled': true,
    'btn-primary': true,
  })}
/>
```

would not want the `disabled` to lose its quotes

**Comment by IslamWahid** [comment]
there must be an option and let me choose whether to remove or keep the quotes
