### ISSUE TITLE
Generate pretty printed code from babel typescript AST

### ISSUE THREAD

**Issue by bali182** [prettier/prettier#11039]
**Environments:**

- Prettier Version: 2.3.1
- Running Prettier via: Node.js API
- Runtime Node.js v14.16
- Operating System: Windows
- Prettier plugins (if any): typescript parser (possibly?)

**Steps to reproduce:**

I'm generating typescript code using babel ast (`@babel/types`). I'd like to use prettier (if this is possible) to stringify the ast directly instead of using babels printer first then re-parsing it with prettier, then stringifying again.

I'm trying to do it like this:

```ts
import { program, Statement, file } from '@babel/types'
import prettier, { Options } from 'prettier'

function createFile(): File {
  const content: Statement[] = ... // Create a list of statements
  return file(program(content, [], 'module')) // Wrap it into a file
}

// Options are prettier options
export function prettierStringify(file: File, options: Options = {}) {
  // Giving it a faux string, since it doesn't seem to do anything on empty input
  return prettier.format('type X = any', {
    ...options,
    // Instead of parsing returning the generated AST
    parser: () => {
      return file
    },
  })
}
```

**Expected behavior:**
Should pretty print the AST

**Actual behavior:**
I get an error. Now this might be because I'm using the API wrong, in this case could you advise?

> TypeError: Cannot read property 'raw' of undefined
>    at printLiteral$1 (node_modules/prettier/index.js:48834:39)
>       at printPathNoParens (node_modules/prettier/index.js:49087:21)
>       at Object.genericPrint$6 [as print] (node_modules/prettier/index.js:49035:19)
>       at callPluginPrintFunction (node_modules/prettier/index.js:16169:21)
>       at mainPrintInternal (node_modules/prettier/index.js:16107:17)
>       at node_modules/prettier/index.js:16096:28
>       at AstPath.call (node_modules/prettier/index.js:15831:20)
>       at mainPrint (node_modules/prettier/index.js:16096:17)
>       at printTypescript$1 (node_modules/prettier/index.js:48618:27)
>       at printPathNoParens (node_modules/prettier/index.js:49087:21)
>       at Object.genericPrint$6 [as print] (node_modules/prettier/index.js:49035:19)
>       at callPluginPrintFunction (node_modules/prettier/index.js:16169:21)
>       at mainPrintInternal (node_modules/prettier/index.js:16107:17)
>       at mainPrint (node_modules/prettier/index.js:16089:14)
>       at node_modules/prettier/index.js:44669:50
>       at AstPath.each (node_modules/prettier/index.js:15864:7)
>       at printArrayItems$3 (node_modules/prettier/index.js:44668:8)
>       at printTypescript$1 (node_modules/prettier/index.js:48607:56)
>       at printPathNoParens (node_modules/prettier/index.js:49087:21)
>       at Object.genericPrint$6 [as print] (node_modules/prettier/index.js:49035:19)
>       at callPluginPrintFunction (node_modules/prettier/index.js:16169:21)
>       at mainPrintInternal (node_modules/prettier/index.js:16107:17)
>       at node_modules/prettier/index.js:16096:28
>       at AstPath.call (node_modules/prettier/index.js:15831:20)
>       at mainPrint (node_modules/prettier/index.js:16096:17)
>       at printExportDeclaration$2 (node_modules/prettier/index.js:47133:21)
>       at printPathNoParens (node_modules/prettier/index.js:49252:14)
>       at Object.genericPrint$6 [as print] (node_modules/prettier/index.js:49035:19)
>       at callPluginPrintFunction (node_modules/prettier/index.js:16169:21)
>       at mainPrintInternal (node_modules/prettier/index.js:16107:17)
>       at mainPrint (node_modules/prettier/index.js:16089:14)
>       at node_modules/prettier/index.js:47895:21
>       at AstPath.each (node_modules/prettier/index.js:15864:7)
>       at printStatementSequence (node_modules/prettier/index.js:47887:8)
>       at printBody$1 (node_modules/prettier/index.js:48021:10)
>       at printBlockBody$1 (node_modules/prettier/index.js:48187:16)
>       at printPathNoParens (node_modules/prettier/index.js:49116:14)
>       at Object.genericPrint$6 [as print] (node_modules/prettier/index.js:49035:19)
>       at callPluginPrintFunction (node_modules/prettier/index.js:16169:21)
>       at mainPrintInternal (node_modules/prettier/index.js:16107:17)
>       at node_modules/prettier/index.js:16096:28
>       at AstPath.call (node_modules/prettier/index.js:15831:20)
>       at mainPrint (node_modules/prettier/index.js:16096:17)
>       at printPathNoParens (node_modules/prettier/index.js:49112:18)
>       at Object.genericPrint$6 [as print] (node_modules/prettier/index.js:49035:19)
>       at callPluginPrintFunction (node_modules/prettier/index.js:16169:21)
>       at mainPrintInternal (node_modules/prettier/index.js:16107:17)
>       at mainPrint (node_modules/prettier/index.js:16089:14)
>       at printAstToDoc (node_modules/prettier/index.js:16076:13)
>       at coreFormat (node_modules/prettier/index.js:16436:15)
>       at formatWithCursor$1 (node_modules/prettier/index.js:16665:14)
>       at node_modules/prettier/index.js:60922:12
>       at Object.format (node_modules/prettier/index.js:60942:12)

**Comment by thorn0** [comment]
Does [this](https://github.com/prettier/prettier/issues/3150#issuecomment-394150810) help?

**Comment by bali182** [comment]
@thorn0 Hey thanks for the response! I went through the issue, it seems like the person there trying to use a custom parser. What I'm trying to do is bypass prettier's parsing step, and use an already created ast. The ast is built using the factory methods in `@babel/types`, not parsed from a source file, which might be the problem.

**Comment by lydell** [comment]
Your stack trace mentions `printLiteral$1`. There’s a `printLiteral` function here: https://github.com/prettier/prettier/blob/c8133f8afabbfa0b6a8f88da8a37c8e79d9f5671/src/language-js/print/literal.js

For `StringLiteral`, `NumericLiteral` and `BigIntLiteral` it tries to access `node.extra.raw`. If `node.extra` is missing, a `Cannot read property 'raw' of undefined` error would be thrown, just like in your case.

I played around a little with `@babel/types` and `@babel/parser`:

```
> require("@babel/parser").parseExpression('"a"')
Node {
  type: 'StringLiteral',
  start: 0,
  end: 3,
  loc: SourceLocation {
    start: Position { line: 1, column: 0 },
    end: Position { line: 1, column: 3 },
    filename: undefined,
    identifierName: undefined
  },
  range: undefined,
  leadingComments: undefined,
  trailingComments: undefined,
  innerComments: undefined,
  extra: { rawValue: 'a', raw: '"a"' },
  value: 'a',
  comments: [],
  errors: []
}
> require("@babel/types").stringLiteral("a")
{ type: 'StringLiteral', value: 'a' }
```

As you can see, `@babel/types` generates much fewer properties than parsing, and most notably – `.extra` is missing.

I’m not super familiar with Babel’s APIs, but it sounds like you can’t just use `@babel/types` out of the box together with Prettier, since Prettier expects more properties (at least `.extra`).

Previous issues (with no satisfying conclusion):

- https://github.com/prettier/prettier/issues/465
- https://github.com/prettier/prettier/issues/1274

Unfortunately I think it’s going to be really hard to print an AST that isn’t parsed from text.
