### ISSUE TITLE
Support for not ignoring specified misses in ignored folders

### ISSUE THREAD

**Issue by engvucen** [prettier/prettier#11036]
This configuration is available in .eslintignore.
![image](https://user-images.githubusercontent.com/31369318/121022796-42f13e80-c7d5-11eb-8fe7-a7c910a2654a.png)

But the same configuration is in prettierignore doesn’t work.
![image](https://user-images.githubusercontent.com/31369318/121023132-91064200-c7d5-11eb-8a46-d8903af4b246.png)

All files in the web folder are ignored.
https://prettier.io/docs/en/ignore.html#range-ignore

I can’t find a use case in the documentation. Doesn’t prettier support it?

**Comment by thorn0** [comment]
Are you sure it works in ESLint? Prettier and ESLint use the same [module](https://www.npmjs.com/package/ignore) to work with ignore files.

**Comment by thorn0** [comment]
> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is **not possible to re-include a file if a parent directory of that file is excluded**.

-- https://git-scm.com/docs/gitignore

**Comment by thorn0** [comment]
Use `web/**/*` instead of `web/`.
