### ISSUE TITLE
Prettier - Error: Syntax error : Unexpected token { (Running on figma plugin with webpack)

### ISSUE THREAD

**Issue by softmarshmallow** [prettier/prettier#11046]
- Prettier Version: 2.3.1
- Running Prettier via: Node.js / Browser
- Runtime: Node.js v14, Figma plugin

**Steps to reproduce:**

Run the snapshot - https://github.com/bridgedxyz/assistant/tree/snapshot/prettier-wont-work-with-webpack-on-figma-plugin

**Expected behavior:**

**Actual behavior:**

First, webpack throws this warning
```
Critical dependency: the request of a dependency is an expression
```

Secondly, While runtime, throws `Error: Syntax error on line 19506: Unexpected token {`
![image](https://user-images.githubusercontent.com/16307013/121640281-af678880-cac8-11eb-9598-8d8f9ec497a9.png)

It's hard to specify which is causing this error since running same code on browser works fine, but running it on figma plugin with different webpack config throws the error.

webpack.config.js for figma plugin
```js
const HtmlWebpackInlineSourcePlugin = require("html-webpack-inline-source-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const path = require("path");
const Dotenv = require("dotenv-webpack");
const TerserPlugin = require("terser-webpack-plugin");

module.exports = (env, argv) => ({
  mode: argv.mode === "production" ? "production" : "development",

  // https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285598881
  node: {
    fs: "empty",
  },
  // This is necessary because Figma's 'eval' works differently than normal eval
  devtool: argv.mode === "production" ? false : "inline-source-map",

  entry: {
    ui: "./src/ui.tsx", // The entry point for your UI code
    code: "./src/code.ts", // The entry point for your plugin code
  },

  module: {
    rules: [
      // Converts TypeScript code to JavaScript
      { test: /\.tsx?$/, use: "ts-loader", exclude: /node_modules/ },

      // Enables including CSS by doing "import './file.css'" in your TypeScript code
      {
        test: /\.css$/,
        loader: [{ loader: "style-loader" }, { loader: "css-loader" }],
      },

      // Allows you to use "<%= require('./file.svg') %>" in your HTML code to get a data URI
      {
        test: /\.(png|jpg|gif|webp|svg|zip)$/,
        loader: [{ loader: "url-loader" }],
      },
    ],
  },

  // Webpack tries these extensions for you if you omit the extension like "import './file'"
  resolve: { extensions: [".tsx", ".ts", ".jsx", ".js"] },

  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "dist"), // Compile into a folder called "dist"
  },

  // minimize
  optimization: {
    minimize: false,
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          sourceMap: true,
          compress: {
            keep_classnames: true, // keep class name cause, flutter-builder uses class name reflection.
            keep_fnames: true,
            drop_console: true,
            conditionals: true,
            unused: true,
            comparisons: true,
            dead_code: true,
            if_return: true,
            join_vars: true,
            warnings: false,
          },
          output: {
            comments: false,
          },
        },
      }),
    ],
  },

  // Tells Webpack to generate "ui.html" and to inline "ui.ts" into it
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/ui.html",
      filename: "ui.html",
      inlineSource: ".(js)$",
      chunks: ["ui"],
    }),
    new HtmlWebpackInlineSourcePlugin(),
    new Dotenv(),
  ],
});

```

**Things I've tried**
I tried copying both raw esm/standalone and standalone from node_modules directly in project code, but throws the same error.

**Comment by fisker** [comment]
I don't think this is related to Prettier, my guess is you are running Prettier on a compressed file, because I saw `.js.br` file extension.

**Comment by softmarshmallow** [comment]
No that is unrelated. That is the figma platform throwing the message.
And also my question is. why won't it work on this platform then.

**Comment by fisker** [comment]
I don't really know what `figma` is, my guess is it's a different runtime? Then, I have to say, we don't support it.

And my best guess is that your runtime doesn't support optional catch binding, may be you can try replace `catch {` with `catch (_) {` to see if it helps. If this is the problem, you have to transform our file yourself.

**Comment by softmarshmallow** [comment]
![image](https://user-images.githubusercontent.com/16307013/121647355-48020680-cad1-11eb-92e7-f4bf2685d997.png)

I tried copying all the sources and installing dependencies that only required by standalone. throws above error instead.



> I don't really know what `figma` is, my guess is it's a different runtime? Then, I have to say, we don't support it.
> 
> And my best guess is that your runtime doesn't support optional catch binding, maybe you can try replace `catch {` with `catch (_) {` to see if it helps. If this is the problem, you have to transform our file yourself.

Are you saying "we don't support it." behalf of prettier? (I must know)

If this case is and won't be supported then i'll have to make remote api server that only performs formatting.

**Comment by fisker** [comment]
> Are you saying "we don't support it." behalf of prettier? (I must know)

Yes, in behalf of Prettier team, we support `Node.js>10.13.0` and latest browsers. In other runtime, you need to transform yourself (with babel for example).

**Comment by softmarshmallow** [comment]
Ok I'm first going to go with remote api approach, but when i do make it work somehow with custom transformation, I'll share again on this thread.

Thanks for helping out.

**Comment by fisker** [comment]
Isn't it easier to run `babel` when webpacking?
