### ISSUE TITLE
Rationale for default double quotes

### ISSUE THREAD

**Issue by svenanders** [prettier/prettier#1105]
What is the rationale for enforcing double quotes as standard (when it seems most other use single quotes)?

I *support and encourage* using double quotes, so I'm **not** asking for this to change. I'm asking because I'd like to know how you arrived at this position.

**Comment by vjeux** [comment]
@jlongster used double quotes on his projects so he started the project with it. But it turns out that most of the js world use single quote so we want to switch the default. We need to find a good transition path though to avoid a big breaking change.

**Comment by svenanders** [comment]
All right! Raised this issue internally at my company and apparently no-one is in favor of double quotes. I still like it, but I'll bend to the majority view.

**Comment by focusaurus** [comment]
FYI I prefer double quotes because JSON requires them and I often have to move snippets of object literals between JSON documents and javascript code. There's a lot more tooling around switching things around these days, but that's the main reason I prefer double quotes in my javascript.

**Comment by vjeux** [comment]
I'm going to close this since it's not very actionable.

**Comment by johnunclesam** [comment]
How to change the default behaviour to single quote?

**Comment by suchipi** [comment]
The default behavior (that is, what happens when you use prettier with no options set) is to use double quotes. If you want to override the default behavior to use single quotes in your project, use the `--single-quote` option. https://prettier.io/docs/en/options.html
