### ISSUE TITLE
Unexpected indentation in chains with implicit returns

### ISSUE THREAD

**Issue by matthewwithanm** [prettier/prettier#1106]
This formatting makes it seem like the chained calls are on the Pomise, when they're actually on the Observable:

```js
Observable.defer(() =>
  Promise.all([
    aFunctionThatsLongEnoughToCauseAWrap(),
    anotherFunctionThatsLongEnoughToCauseAWrap()
  ]))
  .map(x => {
    return b();
  })
  .filter(x => {
    return true;
  });
```

It's not great without the second chained method either:

```js
Observable.defer(() =>
  Promise.all([
    aFunctionThatsLongEnoughToCauseAWrap(),
    anotherFunctionThatsLongEnoughToCauseAWrap()
  ])).map(x => {
  return b();
});
```

Switching to an explicit return gives more desirable results:

```js
Observable.defer(() => {
  return Promise.all([
    aFunctionThatsLongEnoughToCauseAWrap(),
    anotherFunctionThatsLongEnoughToCauseAWrap()
  ]);
})
  .map(x => {
    return b();
  })
  .filter(x => {
    return true;
  });

Observable.defer(() => {
  return Promise.all([
    aFunctionThatsLongEnoughToCauseAWrap(),
    anotherFunctionThatsLongEnoughToCauseAWrap()
  ]);
}).map(x => {
  return b();
});
```

cc @vjeux @stepanhruda

**Comment by vjeux** [comment]
Sorry about this!

https://github.com/prettier/prettier/pull/927 is a fix for it but is missing some edge cases. As soon as I have some time to work on prettier I'm going to push it through and it's going to fix your issue. Thanks the report

**Comment by matthewwithanm** [comment]
woot! thanks @vjeux 😊

**Comment by vjeux** [comment]
Going to close this as it's being tracked by #974
