### ISSUE TITLE
Prettier removes necessary parens (changing the AST) when using prettier-ignore

### ISSUE THREAD

**Issue by evanyeung** [prettier/prettier#11077]
**Prettier 2.3.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAHgJT7AA6UX++DPvfAHoh+AA7U4MXHGoBaHAHMoNOAN4j8cAM4kcsOXRzaAhgCMScOVDhMYcvTfX4mAOhP4APs7dmBLVzATMgYodDIWLi4AXxAAGhAIMVxobWRQE2pqCAB3AAVMhDSUYJyTAE80hLNqEzAAaykAZTE6-UVkGGp0OAS4AFszODo6YYAZEyhFdBNFOAAxGn6TaXbkEBN0GAh4kAALGH6SCj2ceG1WsDgmorOcADcz8vWwbSqQfW1ZGDzaxWXkKhgl8EgArbRMABCtQazRM-TgY30cEBwN6IHBTCa7UsAEV0BB4KiSCCQK1qF9qOszOZSLsJPoYBQcHQYHtkAAOAAMCQkEC+FFqYnWEh0snuKISAEcCfBfklihttNY4MNhrtJDKcJJfrMAUggST0V9+jhOt1jTi4PjCSiDWiEjBzMzWeykAAmR21HCORQAYQg-X1IB0AFZdugvgAVczFQ2k+49ACSUFGsCaYGoOGSAEFU00YOVLMSvtFokA)

```sh
--parser babel
```

**Input:**

```jsx
function HelloWorld(x) {

  (
    // prettier-ignore
    // eslint-disable-next-line
    x.a |
    x.b
  ).call(null)

}
```

**Output:**

```jsx
function HelloWorld(x) {
  // prettier-ignore
  // eslint-disable-next-line
  x.a |
    x.b.call(null);
}

```

**Expected behavior:**
```jsx
function HelloWorld(x) {

  (
    // prettier-ignore
    // eslint-disable-next-line
    x.a |
    x.b
  ).call(null)

}
```
(or something similar which does not remove the wrapping parens)

This issue is related to issues such as #10814 and #10851  where "disable" magic comments are being moved. In order to prevent the comment moving, I added a `prettier-ignore` comment. However, this causes the wrapping parens to be removed which changes the AST of the program.

A workaround is to move the `prettier-ignore comment one line up:
```
function HelloWorld(x) {
  // prettier-ignore
  (
    // eslint-disable-next-line
    x.a |
    x.b
  ).call(null)

}
```
However, I only tried this workaround after realizing that the runtime of the program had been changed by prettier.

**Comment by fisker** [comment]
Fixed by #14406
