### ISSUE TITLE
When prettier defaults change in a new release, it should not affect exsiting projects, only new projects.

### ISSUE THREAD

**Issue by craigphicks-public** [prettier/prettier#11082]
Clients of prettier depend upon the consistency of prettier to ensure only real code changes are visible when comparing versions.

Recently an April change to prettier hit hard.  There is no way benefits of the cosmetic changes outweigh the destruction of the ability to compare with older versions.  

Other than that, thanks for a great tool.

**Comment by fisker** [comment]
```diff
{
  "devDependencies": {
-    "prettier": "^2.2.0"
+   "prettier": "^2.2.0"
}
```

**Comment by craigphicks-public** [comment]
Awesome!  Thank you very much.
