### ISSUE TITLE
Prettier breaking css if it does not fit print width

### ISSUE THREAD

**Issue by rfoel** [prettier/prettier#11083]
**Prettier 2.3.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcYBPAGzgBMAafYfMQw-AX3wDMcJ18ByY8lQC0kLNAQxCvADpRZkKMXwBlUhUoAZVEoC8RNVQB0AVzIAKWfnxn6MABZx0cJHXwAjXJTg5Vg2h5wvHAB1VEp7WkgyXEJaQkwAQzBUKABzVlYASnwdAD4GJgADSyt8MlQ6EtL3T28hDxgYbhcAEmAAoNDwu0N0BJS2No7vXwpDQghyykHgKJjDCHZ2YLtUeENy1LsYFgBuKtLEykoU1NbgeKTTswBmTLYABn2oapYSwupZTJBqEAhMGCoaCEZCgBI4LgAdwACuCECCUAkyJCEiQQb83DgkgBrOAwZSJZJpZAwHDGOC-RxuKheTQJNLGBKpOAAMVwfUap2QIASxiaPxA23QZBWazglzAcGU8LWqAAbmsSNzGOi0IpvDBoVjUn1kOwkYQKSAAFaEAAeACEsWBcfiEk4tFA4HqDUbTWblKcKABFYwQeAusiG36JHCGnDctwJalkAWYHApGBdezIAAcDxDXENwSxmG58fF3jlzt+AEc-fAtf8ETzCEInVQqAKcHBy6gW1qmbqkPqg0bDehUCSyf2vXBff7nT3Xb8YNHk3ZkAAmWdY1DlNIAYW43ZA4oArALjIaACrRhG94MgOXkgCSUC8sGUYATAIAgg-RlPL3AWCwgA)

```sh
--parser babel
```

**Input:**

```jsx
import styled, { css } from 'styled-components'

const StyledList = styled.ul(
  ({ theme: { borderStyle, borderWidth, colors, spacing } }) => css`
    li {
      border-bottom: ${borderWidth.main} ${borderStyle.solid} ${colors.offWhite.light};
      padding: ${spacing(3)} 0;
    }
  `,
)
```

**Output:**

```jsx
import styled, { css } from "styled-components";

const StyledList = styled.ul(
  ({ theme: { borderStyle, borderWidth, colors, spacing } }) => css`
    li {
      border-bottom: ${borderWidth.main} ${borderStyle.solid}
        ${colors.offWhite.light};
      padding: ${spacing(3)} 0;
    }
  `
);

```

**Expected behavior:**
```jsx
import styled, { css } from "styled-components";

const StyledList = styled.ul(
  ({ theme: { borderStyle, borderWidth, colors, spacing } }) => css`
    li {
      border-bottom: ${borderWidth.main} ${borderStyle.solid} ${colors.offWhite.light};
      padding: ${spacing(3)} 0;
    }
  `
);

```

**Comment by alexander-akait** [comment]
CSS is not broken in this

**Comment by rfoel** [comment]
It should not break the line for `border-bottom`, should it?

**Comment by rfoel** [comment]
Anyway, my problem is with `ts-styled-plugin` itself and no prettier. Cheers.
