### ISSUE TITLE
`prettier-ignore` is ignored if there is a comment before

### ISSUE THREAD

**Issue by frantic** [prettier/prettier#1109]
This works as expected (the `module.exports` thing stays untouched by prettier):
```javascript
console.log('hi');

// prettier-ignore
module.exports = {
  "foo": "bar",
};
```

But the following doesn't work (`module.exports` is reformatted):
```javascript
// Some comment stuff

// prettier-ignore
module.exports = {
  "foo": "bar",
};

```

**Comment by hawkrives** [comment]
Here's a [live reproduction](https://prettier.github.io/prettier/#%7B%22content%22%3A%22console.log('hi')%3B%5Cn%5Cn%2F%2F%20prettier-ignore%5Cnmodule.exports%20%3D%20%7B%5Cn%20%20%5C%22foo%5C%22%3A%5Cn%20%20%5Cn%20%20%5C%22bar%5C%22%2C%5Cn%7D%3B%5Cn%5Cn%2F%2F%20Some%20comment%20stuff%5Cn%5Cn%2F%2F%20prettier-ignore%5Cnmodule.exports%20%3D%20%7B%5Cn%20%20%5C%22foo%5C%22%3A%20%5Cn%20%20%5Cn%20%20%5C%22bar%5C%22%2C%5Cn%7D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D). Thanks for reporting!

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/blob/60816af4ce6df274b10f3f9cd264a78f1106c48b/src/printer.js#L68

Looks like I only check for the first comment attached to a node. /facepalm

**Comment by ericclemmons** [comment]
@vjeux Good thing you added "easy" :) #1125 is ready for review, since I had 10 minutes and didn't want to do _real_ work stuff.
