### ISSUE TITLE
Comment gets wrongly placed after readonly keyword in mapped type

### ISSUE THREAD

**Issue by MichaelDeBoey** [prettier/prettier#11098]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKpnAXm2AB0ptsB6K7SAW3oRnMoCc4BDAE2gBs02ANq5sASwpQArvQBGcNgF0k2APIwAFgvxYRigNzkAvvpAAaEBAwwx0AM7JQnNmwgB3AArOEDlJz5unGgOFrJsnGAA1nAwAMoYERIA5sgwbFJwFnBycNzcuQAynFBJUpxJcABiEGz0nDA2JcggnFIwEOYgGjD0fADqGmLwdglgcLE+Q2IAbkNozWB2ISASdgowHuFJdcgAZv5rFgBWdgAeAELhUTGxnEwFEnB7B5kgJ6exyXxwAIpSEPBnnxDiAEmw1mxmugsHYwGwxNZOhh4bA+mJuJpkAAOAAMFmREDWfXCGGayLgEOmTwsAEd-vBNlZfC07ABaKBwXK5TocOliDibco7JD7YGvNb0MSpdLir6-elPEUvCwwTiyNEYjTIABMKvCYj4yQAwhBGJxmhSAKydKRrXBq3yikHTDIASSg+VgsThCJgAEEPbF0N8gWsjEYgA)

```sh
--parser typescript
```

**Input:**

```tsx
type Type = {
  // comment
  readonly [T in number]: OtherType[T];
};
```

**Output:**

```tsx
type Type = {
  readonly // comment
  [T in number]: OtherType[T];
};

```

**Expected behavior:**
```tsx
type Type = {
  // comment
  readonly [T in number]: OtherType[T];
};
```

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/issues/11098
