### ISSUE TITLE
`.prettierignore` is not used without `--write`?

### ISSUE THREAD

**Issue by AustinScola** [prettier/prettier#11105]
**Environments:**

- Prettier Version: 2.3.1
- Running Prettier via: CLI
- Runtime: Node v14.17.1
- Operating System: Ubuntu 18.04

**Steps to reproduce:**

Here is a bash script to reproduce the issue.
```bash
#!/bin/bash

# Make a javascript file foo.js.
echo "let foo = 1" > foo.js

# Make a prettier ignore file that ignores foo.
echo "/foo.js" > .prettierignore

# Running prettier prints the formatted version of foo but it should ignore foo.js?
prettier .

```

**Expected behavior:**
Prettier shouldn't do anything.

**Actual behavior:**
Prettier prints the formatted version of the file. Note that the file does seem to be ignored if `--write` is passed to `prettier`.

**Comment by sosukesuzuki** [comment]
Does Prettier output **formatted** version of foo? In my machine, Prettier outputs **not formatted** version.

**.prettierignore**

```
foo.js
```

**foo.js**

```js
function foo     (     ) {
console.log("HI");
}
```

**CLI:**

```
$  npx prettier *.js
foo.jsfunction foo     (     ) {
console.log("HI");
}
```

**Comment by sosukesuzuki** [comment]
I've never heard of it before, but it seems to be the intended behavior. See #3618, #3590.

However, if you are having trouble in real world with this problem, I think we need to implement some kind of workaround. Did you have any real problems with Prettier outputs ignored file as is?

**Comment by AustinScola** [comment]
> Does Prettier output **formatted** version of foo? In my machine, Prettier outputs **not formatted** version.

It outputs the _not formatted_ version.

> I've never heard of it before, but it seems to be the intended behavior. See #3618, #3590.
> 
> However, if you are having trouble in real world with this problem, I think we need to implement some kind of workaround. Did you have any real problems with Prettier outputs ignored file as is?

That is interesting. It wasn't really a problem. I was actually just trying to list the files that prettier would format so that I could double check my `.prettierignore` file and stumbled upon this behavior. If there is a legitimate reason for the behavoir as those links suggest then this probably doesn't need to be changed. I would however say that it seems to violate the principle of least surprise.

**Comment by thorn0** [comment]
see https://github.com/prettier/prettier/issues/3590

**Comment by thorn0** [comment]
See also https://github.com/prettier/prettier/issues/7473#issuecomment-602930711
This works as intended. Changing this will break existing workflows for editor integrations.

**Comment by gulliver-madrid** [comment]
I would suggest that these differences in the treatment of `.prettierignore` be explicitly documented. Apparently, prettier ignores certain patterns (the files included in `node_modules`, and the version control files), and `.prettierignore` would allow the user to add extra patterns to ignore. However, calling `prettier` without options ignores the default patterns but no those indicated in `.prettierignore`, which can be a bit confusing.
I understand that this behavior may be perfectly reasonable (and that changing it would mean breaking existing workflows), but it's not at all obvious, and it could be useful to document it in the `Ignoring Files: .prettierignore` section of the documentation.
