### ISSUE TITLE
prettier cannot format XXX

### ISSUE THREAD

**Issue by itxtoledo** [prettier/prettier#11102]
from yesterday to today after an update from prettier I come across this message when I try to format my .ts and .tsx files, other extensions this also happens

![image](https://user-images.githubusercontent.com/21026675/123008906-2ab31f00-d392-11eb-845f-a69cae7705a9.png)

**Comment by sosukesuzuki** [comment]
This is caused by https://github.com/prettier/prettier-vscode/issues/2029
