### ISSUE TITLE
`{{ $attributes }}` get formatted in seperate lines

### ISSUE THREAD

**Issue by jeroenvanrensen** [prettier/prettier#11104]
### Summary

I want the `{{ $attributes }}` in Laravel blade to be formatted into one line, but it separates it into three.

### Github Repository to Reproduce Issue

I don't think it's useful, because I don't have any config files in the repo. I configured everything in my code editor.

### Steps To Reproduce:

1. Install Prettier to VS code
2. Add this in the config: `"files.associations": { "*.blade.php": "html"}`
3. Configure these Prettier settings:

```json
"prettier.printWidth": 120,
"prettier.htmlWhitespaceSensitivity": "strict",
"prettier.tabWidth": 4,
"editor.defaultFormatter": "esbenp.prettier-vscode",
"prettier.useEditorConfig": false,
"prettier.singleQuote": true
```

4. Create a `home.blade.php` file
5. Add this to the file and then format using Prettier:

```html
<li>
    <a {{ $attributes }} class="px-5 py-2 font-semibold text-white border border-green-200 shadow-md shadow-green-md rounded-3xl">
        {{ $slot }}
    </a>
</li>
```

### Expected result

The code snippet from above should be formatted to this:

```html
<li>
    <a
        {{ $attributes }}
        class="px-5 py-2 font-semibold text-white border border-green-200 shadow-md shadow-green-md rounded-3xl"
    >
        {{ $slot }}
    </a>
</li>
```

### Actual result

But instead, it was formatted to this:

```html
<li>
    <a
        {{
        $attributes
        }}
        class="px-5 py-2 font-semibold text-white border border-green-200 shadow-md shadow-green-md rounded-3xl"
    >
        {{ $slot }}
    </a>
</li>
```

### Additional information

**VS Code Version**: v1.56.2

**Prettier Extension Version**: v6.4.0

**OS and version**: Windows 10

**Comment by sosukesuzuki** [comment]
Sorry we don't support Laravel blade template.
