### ISSUE TITLE
HTML tag with long list of styles

### ISSUE THREAD

**Issue by refaelsh** [prettier/prettier#11112]
Here is a simple html file:
```
$ cat test.html
<div style="display: flex;align-items: center;padding: 6px;height: 60px;box-sizing: border-box;">
    <a href="https://mail.google.com/mail/?authuser=0&amp;ogbl" target="_top">Gmail</a>
</div>
```

Here is what I get when using `prettier`:
```
$ prettier test.html
<div
  style="
    display: flex;
    align-items: center;
    padding: 6px;
    height: 60px;
    box-sizing: border-box;
  "
>
  <a href="https://mail.google.com/mail/?authuser=0&amp;ogbl" target="_top"
    >Gmail</a
  >
</div>
```
I expected anything, but no that. It looks really not good. Is that a bug?
Please advise me on what am I missing here?

P.S.
The version of Prettier that is currently available on Arch Linux is this:
```
$ prettier -v
2.3.1
```

**Comment by fisker** [comment]
It's intentionally, https://prettier.io/blog/2020/03/21/2.0.0.html#format-value-of-html-style-attribute-7556httpsgithubcomprettierprettierpull7556-by-fiskerhttpsgithubcomfisker

**Comment by refaelsh** [comment]
understood. Thank you for the answer and sorry for the bother :-)
