### ISSUE TITLE
Understanding the destructuring params heuristics

### ISSUE THREAD

**Issue by real34** [prettier/prettier#1111]
Hi,

After runnier prettier (0.22.0) on a codebase I still have a few questions regarding the formatting of React components with props destructuring. Like @kenny_dee pointed out in #975 it is not really clear to me.

It would be great to add a few lines in the Rationale about the choices and the reasons leading to it. I could understand that choices made for imports or other objects destructuring could impact the final formatting.

For instance, what feels counter-intuitive to me (for now) is adding a new line in the function:

```js
const NumberField = ({
  min = '0',
  step = '1',
  ...props
}) => (
  <span>FOO</span>
)
```

becomes

```js
const NumberField = (
  {
    min = "0",
    step = "1",
    ...props
  }
) => <span>FOO</span>;
```

[Here is a web demo of a few cases a rationale could help to understand](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Cnconst%20CallToAction%20%3D%20(%7Blabel%2C%20onClick%2C%20pending%20%3D%20false%2C%20disabled%20%3D%20false%7D)%20%3D%3E%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D%5Cn%5Cnconst%20SecondaryButton%20%3D%20(%7Blabel%2C%20onClick%2C%20type%7D)%20%3D%3E%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D%5Cn%5Cnconst%20InputBase%20%3D%20(%7B%5Cn%20%20inputAttributes%20%3D%20%7B%7D%2C%5Cn%20%20...props%5Cn%7D)%20%3D%3E%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D%5Cn%5Cnconst%20NumberField%20%3D%20(%7B%5Cn%20%20min%20%3D%20'0'%2C%5Cn%20%20step%20%3D%20'1'%2C%5Cn%20%20...props%5Cn%7D)%20%3D%3E%20(%5Cn%20%20%3Cspan%3EFOO%3C%2Fspan%3E%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

Are there any resources out there that have already been made available?

**Comment by SimenB** [comment]
#1022

**Comment by vjeux** [comment]
Thanks for the report, as mentioned by @SimenB, this is now fixed in master and will be available in the next release. We've been a bit busy with our own lives but next week is likely.

**Comment by real34** [comment]
Thank you for the link, I had not seen the issue. Perfect!
