### ISSUE TITLE
Prettier should not add leading and trailing whitespace to HTML Button element text

### ISSUE THREAD

**Issue by amayer42** [prettier/prettier#11110]
**Prettier 2.3.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAy5u3AQQDKQgLxMQUCAFoAVgGdyNQtNx0B8oROZRy5dqQGYdevak6l8AvmwEAlIZfEgArjABm0gBzaWp-fgAkvjcpAycAJ7kMMF0pKgA9EEhYX6m5pbWAHICFs4AJnDyYABOAJYADjBl0BLkkLAIMM6RfBBZMKRQ+L66+glshsZpqABGEPkRJumjbjDQ5PkAhjBL0iswJQCMiytrGyUATLur6zCbAMzhUQBCc9CJs+fQ02byFUu6y6cHO9-75yOJwBl2u5Duz1YCXen2mjwmUxYiQ4PAYIAANCAIFUalB5MhQEsSiUIAB3YhEhD4lBLOikpYRfGY0YlJZgADWcBgQg+YDKUAA5shNi44Ji4DRRnB8oV8txPgKXEsBXAAGIQEo0Db8oU0twQDEgaj0ADqlDK8BhYDgQipFrKADcLRFkOB5EyQPz5HASjBiKyBVrkO5ad7MQoAB43VkcrlCJY0ODcflwYOhsUgSNCHV0OAARRcEHgaboYZAHxK3pKruNdENFXKsBNZXyMEoyAALAAGTENiDek2siquhtFH0O1OYgCOhfg-ux1JAS3k0igcGl0sNJTgM7K2-9yqDSBDpYz3poZWFJVFmPkOfzs9Tx-TmNWo2brfbSEOr9ZZToOq4BANBHiARQAKyGi43r4EsozUieZYOqKgRQIUsBCKUlQwAIaFCDAES5iW3oAL4kUAA)

```sh
--parser html
--print-width 40
```

**Input:**

```html
<!DOCTYPE html>
<HTML CLASS="no-js mY-ClAsS">
  <HEAD>
    <META CHARSET="utf-8">
    <TITLE>My tITlE</TITLE>
    <META NAME="description" content="My CoNtEnT">
  </HEAD>
  <body>
    <button data-attr1 data-attr2 data-attr3>My Button</button>
    <span data-attr1 data-attr2 data-attr3>My Button</span>
  </body>
</HTML>
```

**Output:**

```html
<!DOCTYPE html>
<html class="no-js mY-ClAsS">
  <head>
    <meta charset="utf-8" />
    <title>My tITlE</title>
    <meta
      name="description"
      content="My CoNtEnT"
    />
  </head>
  <body>
    <button
      data-attr1
      data-attr2
      data-attr3
    >
      My Button
    </button>
    <span
      data-attr1
      data-attr2
      data-attr3
      >My Button</span
    >
  </body>
</html>

```

**Expected behavior:**
Based upon the documentation for [HTML Whitespace Sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity), `<button>` elements should be formatted similar to `<span>` elements by default. Currently, buttons will have newlines added by the formatter and the `textContent` of the button will contain the additional leading and trailing space. It's really minor, but a bit annoying.

**Comment by vaish567** [comment]
Howdy! @sosukesuzuki  I would like to look up to this issue :) it would be great if you assign me.

**Comment by thorn0** [comment]
> Based upon the documentation for [HTML Whitespace Sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity), `<button>` elements should be formatted similar to `<span>`

They should not. `button`'s default value of the `display` property is `inline-block`, which means the whitespace added by Prettier don't affect how the element is rendered in the browser.

As for `textContent`, you can say that about any element. Modifying whitespace is an inherently unsafe transformation in HTML, even with `--html-whitespace-sensitivity strict`. Nothing can be done about that.

**Comment by amayer42** [comment]
Alright, thanks for the info and taking a look @thorn0
