### ISSUE TITLE
Comment after key isn't printed

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1112]
While looking at #1103, I found this one

```js
a = {
   "a" /* prettier-ignore */: () => 1
}
```

```
Error: Comment "prettier-ignore" was not printed. Please report this error!
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22a%20%3D%20%7B%5Cn%20%20%20%5C%22a%5C%22%20%2F*%20prettier-ignore%20*%2F%3A%20()%20%3D%3E%201%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by 2c2c** [comment]
In `printer.js` function `printPropertyKey` has a special case for stringliterals that bypasses a `fastpath.call`

This makes the node representing the stringliteral never be on the top of the path stack. Since it carries the comment via trailingComment it never gets an opportunity to print

That's the best I can understand what's going on anyways. Out of my depth to fix :---)

**Comment by vjeux** [comment]
@2c2c great investigation! The solution for this is to manually print the comments:

```js
comments.printComments(
  path,
  p => key.value,
  options
)
```

feel free to send a pull request to fix it :)

**Comment by ericclemmons** [comment]
Should this be marked _easy_ since you provided the fix?

**Comment by duailibe** [comment]
If #1108 is merged, this bug should be fixed, right?

**Comment by vjeux** [comment]
@duailibe we're unlikely going to merge #1108 as is fyi.

@ericclemmons good call!

**Comment by yamafaktory** [comment]
@vjeux if #1108 is not going in the right direction, should I close it?

**Comment by vjeux** [comment]
@yamafaktory I want to take the time to respond to it properly!

**Comment by yamafaktory** [comment]
@vjeux oh sorry, my intention was not to urge you to look at it. I thought it was simply out of scope.
