### ISSUE TITLE
Prettier is not respecting my indentation settings

### ISSUE THREAD

**Issue by justingolden21** [prettier/prettier#11133]
I recently installed Prettier for VS code

![image](https://user-images.githubusercontent.com/30274440/123882249-16b37400-d8e2-11eb-8868-ba3da9fb23f8.png)

But when I save any of my js files it automatically converts indentation to spaces, not tabs.

I don't have a .editorconfig or .prettierrc file anywhere. I've already searched github issues and stackoverflow posts to no success. Prettier is not indenting as specified. I have absolutely no clue why it's forcing me to use spaces. I've checked the settings are saved, restarted VS Code and even restarted my laptop.

**Comment by justingolden21** [comment]
I should mention, on the bottom of my editor, I've selected (numerous times) "indent using tabs" "tab size 4" and "convert indentation to tabs" and it constantly converts it to spaces.

**Comment by justingolden21** [comment]
Also, I'd have to say Prettier made it **impossible** to figure out how to auto-indent HTML (which is supposedly a feature that comes out-of-the-box). I searched for almost half an hour before figuring it out. Nowhere in the extension settings does it have *anything* on which files are formatted. It was formatting my CSS and JS but not my HTML.

I had tried adding html as an item here:
![image](https://user-images.githubusercontent.com/30274440/124051639-901d9600-d9b8-11eb-81f2-4e02c5651305.png)

And searching github, stackoverflow, prettier's website, and articles and videos with no help.

I finally found that the settings json had a setting that wasn't in prettier:
```json
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
```

I tried adding "css, html, json" to "javascript" but it didn't work. I tried without commas, I tried semicolons, I tried googling this string in hopes that *anyone* has *ever* tried to change this from "javascript" but only found "html" by itself. I finally found the marketplace: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode and decided to cut it out entirely and paste it as `"editor.defaultFormatter": "esbenp.prettier-vscode"` and it worked.

You really need to make this clear on the docs. I searched the docs for 15-20min and found absolutely nothing on this anywhere.

Also, is it a bug or a feature that this formats CSS automatically even though my settings only said javascript?

For an extension designed to make my life easier, I've spent several hours struggling with this now; I highly recommend UX testing this further.

I've just given up entirely on the tabs / spaces problem, after searching for literal days, opening a github issue and [stackoverflow post](https://stackoverflow.com/questions/68175780/prettier-is-not-respecting-my-indentation-settings). I'll have to deal with whatever inconsistent spacing it gives me, since it's not worth any more of my time after three days of struggling and not a single person with an answer.

**Comment by sosukesuzuki** [comment]
> I don't have a .editorconfig or .prettierrc file anywhere. I've already searched github issues and stackoverflow posts to no success. Prettier is not indenting as specified. I have absolutely no clue why it's forcing me to use spaces. I've checked the settings are saved, restarted VS Code and even restarted my laptop.

Sorry I don't know why it was happened. But maybe you can avoid this by creating `.prettierrc`.

> You really need to make this clear on the docs. I searched the docs for 15-20min and found absolutely nothing on this anywhere.

Thank you for pointing this out. But we mention about prettier-vscode in our docs and prettier-vscode's docs mention about it. So I don't think the importance is that high.

Overall, your problem seems to be related to the vscode extension, not the prettier core. You might get a better answer by asking your question at https://github.com/prettier/prettier-vscode than here.
