### ISSUE TITLE
Misplaced parameter comment in abstract method

### ISSUE THREAD

**Issue by emmettnicholas** [prettier/prettier#11145]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDARgZxgJ1WGAAjABtVNNCAxCCQ4AHSkMI2zwMPVRwAomWLAPQAqEcQgBbSQiJwAHgAcyASyhqA5oQCumODgCSAE0KKeqSYRFCBg3fuMAaWwEomAXxCOQERTBXQmMigPDgQAO4ACjwIQSioJOGoAJ5B3ugcANZwMADKZmCayLjacN5wkuhwRkbVADKoUBraqBpwNDiSqDD+Tcho2jAQXiAAFjCSJADqoyrwmAVwubFzKgBuc8n9YBQjano4MJF4Gl3IAGYJet4AVpjyAEJZObkWcHVqcBdXZSB38rlNCQ4ABFbQQeDfEjXEBmHAHfrcKokAC0MDSsJwahgUxURhgo2QAA4AAzeRRhPRTPCKfoUuAHNZfbwAR3B8GOvjiaEwKKgcGq1RGODgbJUIuOrTOSEu0N+ekkKmKOFK3kwQNB7K+Mp+3hgGFx+MJSAATHq8CoSJoAMJSaUgBkAVhG9gAKmwoTC1qUDFBarBcmAsX4AIJ+3IwZLAz1wdzuIA)

```sh
--parser babel-ts
```

**Input:**

```tsx
abstract class Foo {
  abstract bar(
    /** comment explaining userId param */
    userId,
  )
}
```

**Output:**

```tsx
abstract class Foo {
  abstract bar(userId);
  /** comment explaining userId param */
}

```

**Expected behavior:**

```tsx
abstract class Foo {
  abstract bar(
    /** comment explaining userId param */
    userId
  )
}
```

I expect the comment to remain directly above the `userId` argument. It only seems to repro when the method is abstract and has exactly one argument.

**Comment by sosukesuzuki** [comment]
Also it happens for a method that has no body.

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOARugE4AUZFFA9AFSs6QC2XCMOcAB4AHDAEsoEgOY4Arpjg0AkgBMcw2ui45WzRk3mLVAGn0BKMgF8QxkBGEwx0TMlC0aEAO4AFWghco6Kie6ACeLraUNOhgANZwMADKGmDSyDA0snC2cFyUcCoqBQAy6FBSsuhScAQ0XOgwjuXIIOiyMBA2IAAWMFyoAOrdYvCYKXCJ-iNiAG4joS1g2F0SCjQw3tFS9cgAZkEKtgBWmIIAQtFxCYlacMUScHsH2SAngonSqHAAirIQ8E9UIcQBoaGsWtR8qgALQwCIgmgSGADMQqGDdZAADgADLZhB4FANosIWvi4GsZo9bABHP7wTb2AKtTDQqBwAoFLo0OC0sTczZVHZIfZAl4KLhidKZMWfH50x7C562GDoSgotEYpAAJmV0TEqGkAGEIDx0C1yQBWLqGAAqqoCIuBMyySigRVgiTAiIcAEE3YkYKEvoCFJZLEA)

```sh
--parser babel-ts
```

**Input:**

```tsx
class Foo {
  bar(
    /** comment explaining userId param */
    userId,
  )
}
```

**Output:**

```tsx
class Foo {
  bar(userId);
  /** comment explaining userId param */
}

```

**Comment by MarcCelani-at** [comment]
This is blocking us from adopting prettier 2.3. Would love to see some traction on this diff.

**Comment by t-mangoe** [comment]
I investigated this issue a little.

```typescript
abstract class Foo {
  abstract bar(
    /** comment explaining userId param */
    userId,
  )
}
```

In the `babel-ts` parser, the above comment has become the trailing comment for `bar`.
This might be the reason why the comment is misplaced.

**Comment by MarcCelani-at** [comment]
Thanks @t-mangoe . If you can get us unblocked we'd be extremely grateful. I've never worked on a tool like prettier before, so I've procrastinated biting the bullet and diving in. This one is really blocking us and we can't leverage new features like support for the override keyword.

**Comment by MarcCelani-at** [comment]
After bisecting, I found that this issue was introduced in #9872

**Comment by MarcCelani-at** [comment]
@fisker is this something you can take a look at?

**Comment by MarcCelani-at** [comment]
Looks like the change in canAttachComment is to blame, but the fix may be more complicated.

**Comment by fisker** [comment]
May be we can fix this in attachComment?

**Comment by MarcCelani-at** [comment]
Forgive me, but I've never contributed to this project before. I don't see an attachComment API. Is it maybe referring to this PR? https://github.com/prettier/prettier/pull/11525

**Comment by MarcCelani-at** [comment]
So excited that this issue has been resolved, thank you so much!

Is there a place where I can read about the release schedule for prettier? We are going to start upgrading once this is available.

**Comment by duailibe** [comment]
@MarcCelani-at we haven't started planning for a new release yet but it might happen during this month.
