### ISSUE TITLE
What about "space before function paren" option?

### ISSUE THREAD

**Issue by devm4n** [prettier/prettier#11148]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEq+AFAJT7AC+IANCBAA67QDOyoAhgE5cQDuABW4I2KDgBs+HAJ5s6AIy4cwAazgwAyg2U4oAc2Qwu6OHTgBbeXAAm1mwBkO+9Bz1wAYhC7mOMXPuQQDnQYCFoQAAsYc3EAdQiceBZtMDgNEUScADdE6UCwFjkQXRY4LhgBJT0fZFQJUroAKxYADwAhJVV1DQ5zOHtdOFr60xBmlo1dPXE4AEV0CHhh8QaQbS5SrkD5DitxcIYuXRhYnGsYCOQADgAGOkOIUtilBkDDuE2soboARwX4SqMURBFgAWigcBsNnCXDgfxwsMqrhqSDqK1GpXMOEMxgxUxm80WQ1RIzoMF2p3OlyQACYyUocOIpgBhCDmFEgD4AVnC6FKABVdqI0assiYAJJQOywDRgI5MACCUo0MGkM2WpUolCAA)

```sh
--parser babel
```

**Input:**

```jsx
function f () {}
```

**Output:**

```jsx
function f() {}

```

**Expected behavior:**

```jsx
function f () {}
```
I use Standard JS style which requires space before function paren. But Prettier removes this after formatting and doesn't have the option to keep the space. As a result ESLint gives an error. So what about "space before function paren" option?

**Comment by sosukesuzuki** [comment]
Prettier prefers the current style and will not add any options for it. Please see https://prettier.io/docs/en/option-philosophy.html.
