### ISSUE TITLE
Prefer single line objects as arguments resulting in single line functions

### ISSUE THREAD

**Issue by mfbx9da4** [prettier/prettier#11168]
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAFMABHATkrARgF8AaLbAQwICZiBKEUkCABxgEtoBnZUS3LggB3AAoCEvFJQA2wygE9ezAEa5KYANZwYAZVYaOUAObIYuAK5xmcALYq4AE0dOAMpRMXKxuADEIuLaUMJwmyCCUFjAQTCAAFjC2MgDqcRzw3AZgcLqS6RwAbukK4WDcyiBG3HgwourGQciostXMAFbcAB4AQupaOrqUtnCuRnBNLdYgHZ26RsYycACKFhDwEzKtIAa41bjhKpQOMrGsuEYwyRyOMHHIABwADMxnENXJ6qzhZ3B7BePMACOq3gdTYUgi3AAtFA4E4nLFcHBgRwkXVvI0kM1NlNqrYOGZLLj5osVmtxljJswYEcrjc7kgaNT1BwZPMAMIQWyYkC-ACssQs1QAKkcpNitgUrABJKAuWC6MDndgAQTluhgCkWG2qxGIQA)

Input

```
f({
  er: 1}, {
  a: 2})
```

Actual Output

```
f(
  {
    er: 1,
  },
  {
    a: 2,
  }
);
```

Expected output

```
f({ er: 1}, { a: 2})
``` 

Note, the one liner code is not exceeding the line length limit. 

Anyway to tune prettier to format as expected?

**Comment by sosukesuzuki** [comment]
Please open your playground link. Prettier outputs as is. Also see https://prettier.io/docs/en/rationale.html#multi-line-objects for more details.

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAFMABHATkrARgF8AaLbAQwICYtiBKAbgB0oRSQIAHGAS2gBnZKEq5cEAO4AFMQmEpKAG0mUAnsM4AjXJTABrODADK3PXygBzZDFwBXOJzgBbLXAAm7jwBlKVu5SWcABiELjOlDD8VsgglHYwEBwgABYwzkoA6il88IJmYHDG8rl8AG65arFggpogFoJ4MNK6lhHIqMqNnABWggAeAEK6BkbGlM5w3hZwHV2OIH39xhaWSnAAinYQ8HNK3SBmuI24sVqUbkrJ3LgWMJl87jApyAAcAAycNxCNmbrcsRucBOZVmnAAjtt4C0eAo4oIALRQOAeDzJXBwSF8DEtQLtJCdfYLRrOPg2ezE1brLY7WYE+acGAXB5PF5IGiM3R8JSrADCEGc+JAwIArMk7I0ACoXBSEg5lBwASSgXlgxjAt14AEEVcYYGp1ntGsRiEA)

```sh
--parser babel
```

**Input:**

```jsx
f({ er: 1}, { a: 2 });

```

**Output:**

```jsx
f({ er: 1 }, { a: 2 });

```

**Comment by mfbx9da4** [comment]
Sorry there was a bug in my original issue and original playground link please check again @sosukesuzuki

**Comment by mfbx9da4** [comment]
Also thanks for the link, I can confirm that I have read it @sosukesuzuki

**Comment by sosukesuzuki** [comment]
Thanks, I've checked current playground link. It is expected behaviour. Because Prettier respects line breaks in object literal expressions.
