### ISSUE TITLE
HOC function composing

### ISSUE THREAD

**Issue by Alex-Mann** [prettier/prettier#1116]
This occurs in my react workflow. It would be really helpful when composing or exporting a higher-order-component (HOC) to _always_ show the style as such:
```js
export default compose(
  withRouter,
  withSomeOtherHOC,
  graphql(CurrentUserQuery)
)(ComponentToBeDecorated);
```

Prettier automatically reformats to this style when the print-width of the line is exceeded, but when it is not it is kept on a single line.

I find it much easier to read when it is in this style regardless of print-width being exceeded and am wondering if a feature like this is something that you guys would be open to as a setting/toggle. Thoughts?

**Comment by patrickhulce** [comment]
Also applies to list items that are fairly complicated but fall just under a line limit such as 
```js
return Promise.all([
  sql.executeQuery(myQuery),
  redis.fetch(),
  other.go(),
])
```

**Comment by vjeux** [comment]
We are past 1.0 and are not going to do any major formatting changes to prettier anymore. If you are interested in getting this, I would encourage you to fork prettier.
