### ISSUE TITLE
[CLI] range-start/range-end not working for ruby parser

### ISSUE THREAD

**Issue by zhengpd** [prettier/prettier#11175]
Similar problem to https://github.com/prettier/prettier/issues/6428 but for ruby parser: range-start/range-end cli args not working 

**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: CLI 
- Runtime: Node.js v16.3.0 
- Operating System: macOS
- Prettier plugins (if any): @prettier/plugin-ruby

**Steps to reproduce:**

```sh
echo '"aaa";\n"bbb"' | prettier --parser ruby --range-start 0 --range-end 1 --single-quote=true
```
**Expected behavior:**

`aaa` should be single-quoted while `bbb` should remain double-quoted:
```
'aaa';
"bbb"
```

**Actual behavior:**

Both `aaa` and `bbb` remain double-quoted:
```
"aaa";
"bbb"
```

**Possible Workaround**
<https://github.com/prettier/prettier/blob/main/src/main/range-util.js#L161>
Edit `function isSourceElement` and add ruby case:

```
function isSourceElement(opts, node, parentNode) {
  ...
  switch (opts.parser) {
    case "ruby":
      return true
  ...
```

**Comment by sosukesuzuki** [comment]
This is a problem for all plugins, not just Ruby. See https://github.com/prettier/prettier/issues/7639.
