### ISSUE TITLE
List items with several chained functions receive strange indentation

### ISSUE THREAD

**Issue by patrickhulce** [prettier/prettier#1117]
[Live example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20promises%20%3D%20%5B%5Cn%20%20Promise.resolve().then(console.log).catch(err%20%3D%3E%20%7B%5Cn%20%20%20%20console.log(err)%5Cn%20%20%20%20return%20null%5Cn%20%20%7D)%2C%5Cn%20%20redis.fetch()%2C%5Cn%20%20other.fetch()%2C%5Cn%5D%5Cn%5CnPromise.all(promises)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

```js
const promises = [
  Promise.resolve().then(console.log).catch(err => {
    console.log(err)
    return null
  }),
  redis.fetch(),
  other.fetch(),
]

Promise.all(promises)
```

becomes 

```js
const promises = [Promise.resolve().then(console.log).catch(err => {
    console.log(err);
    return null;
  }), redis.fetch(), other.fetch()];

Promise.all(promises);
```

instead of staying like it is or becoming
```js
const promises = [
  Promise.resolve()
    .then(console.log)
    .catch(err => {
      console.log(err);
      return null;
    }),
  redis.fetch(),
  other.fetch(),
];

Promise.all(promises);
```

Dropping `.then(console.log)` from the chain preserves the original style.

**Comment by vjeux** [comment]
Thanks, this looks like a bug!
