### ISSUE TITLE
create-react-app@4.0.3 使用 prettier@2.3.2一直报错乱码

### ISSUE THREAD

**Issue by Selfimpryx** [prettier/prettier#11172]
![image](https://user-images.githubusercontent.com/49122459/124691777-fcdfe580-df0e-11eb-92df-adef37e81b2a.png)

**Comment by fisker** [comment]
Save it as `utf8`

**Comment by fisker** [comment]
Duplicate of #8815

**Comment by Selfimpryx** [comment]
可以了  太感谢了
