### ISSUE TITLE
`createGlobalStyle` and `keyframes` are not getting formatted - styled-components

### ISSUE THREAD

**Issue by erfanasbari** [prettier/prettier#11196]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHzBzgEN4BxAGwgCMzqBlGAT2rnwF98AzHCOnwAdEAGc2HACYBaSFmgIYY0QG5hUDZCgT8NeoxbtOAXnwTjUgHQlyVWg2aS4AAw358dCFNaF3H-HQyHABzVCgkfAAGdSgA+IDMMikpcJDImP8ErwAPGTFUAC80yK8cKTgcGVzYjy4NF1itaF19RyMOfDNbCjg2w2c3OM9vX2AswOCwiOjahMTk1Kh02YmA3PyikpHyyuqIHLn6qEaNDTgc7Dx8Ct4yAFdqAn6nY1UQABoQCEwYVBbkKBggIAO4ABWCCDEyBAjBBZFY0K+dBwZDAAGs4DAmEkwGlkDAcPc4F84Og6HAUpSADJkZb3MghOAAMVwQRgf2WMIeMAgnxAAAsYOhqAB1AWoeBiXFwJhQyWoABuktYMLAYiRaB0lRgYNRISCyDu1DEJJAACsxDkAEKojFYphkdBwanhOBGximr6WnJMNIcACK9wg8A9JrNSRwppwMIYFOo-MwOHCMFFqCkMAFyAAHFEvkmIKbRajMDCk3Bo4r3V8AI7B+B6n7QlBkMQyKBwSmU-mkOuoUh6xmGpDGr3iMmoAlEs0FZaB+vukees0wMh0NMZrNIABMX0JZFQ1DSAGFBMOQBWAKz8+6mgAqa+bo7NiuJAEkoBVYEwSKhfgBBT8OkXZ8uC4IA)

```sh
--parser babel
```

**Input:**

```jsx
import { createGlobalStyle } from "styled-components";

const GlobalStyle = styled.createGlobalStyle`
  body {
    margin: 0;
          padding: 0;
       box-sizing: border-box;
  }
`;

const GlobalStyle = createGlobalStyle`
  body {
    margin: 0;
         padding: 0;
       box-sizing: border-box;
  }
`;

export default GlobalStyle;

```

**Output:**

```jsx
import { createGlobalStyle } from "styled-components";

const GlobalStyle = styled.createGlobalStyle`
  body {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
`;

const GlobalStyle = createGlobalStyle`
  body {
    margin: 0;
         padding: 0;
       box-sizing: border-box;
  }
`;

export default GlobalStyle;

```

**Expected behavior:**

Prettier does not format the css styles passed to `createGlobalStyle` and `keyframes` functions from styled-components.

This issue exist for a long time but is not yet fixed.

There are some workarounds but fixing this should not be a big deal because Prettier already supports formatting for styled-components functions line `css`.

**Comment by sosukesuzuki** [comment]
We cannot support such a format, at least not currently. It may be supported in the future using `--embedded-language-formatting`. See #9025 and #5588.

**Comment by HanSeokSeo** [comment]
> As a workaround, I would like to propose something like this
> 
> ```js
> import { createGlobalStyle } from 'styled-components'
> 
> const styled = { createGlobalStyle }
> 
> const GlobalStyle = styled.createGlobalStyle`
>   body {
>     margin: 0;
>     padding: 0;
>     box-sizing: border-box;
>   }
>   ...
> `
> 
> export default GlobalStyle
> ```
> 
> I have previously mentioned it here, [styled-components/vscode-styled-components#175](https://github.com/styled-components/vscode-styled-components/issues/175)

you genius!

**Comment by kachkaev** [comment]
@HanSeokSeo you can also do this, which is a bit less hacky: https://github.com/prettier/prettier/pull/9025#issuecomment-678655928
