### ISSUE TITLE
HTML Formatter: Liquid parsing error with conditions withing attribute space.

### ISSUE THREAD

**Issue by thet** [prettier/prettier#11199]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgHSgAh8AUhwEsAzHSWOADxgF47MQBnCAWzhgAtioBzJjgIBfbHjxcATnFKMQAehjpJfTgEYmY-ETgAbZnCGjc4qTLmLlqmACZNJwjgQATMka0A+LQBleAaxwAFRoYbFR5dA8QABoQCAAHGGJoZmRQZUkIAHcABWUEVJR0XSz0AE9U2IAjSXQwP04AZXi63j5kGEkAVzhYuDYquGdnIe90fi70VQAxCEk2dBgk-mQQdC6YCBiQLhg2XQB1HnhmFrA4RoLiJIA3a7LVsGZKkF4DSRgc2r4F5FJigyxABWzGoACFavUmugOL4oHA-gDeiAQdRGm1dHAAIpdCDwRH6ZEtSTvVa7fbbeKSXgwA7EZzcZAADgADLEqRADAdavFVlS4O8bgjYgBHXHwL4JQprZgAWnhQyG22kYuI0i+U1+SH+hNiBjYxA63WRzAx2PFCO1SNiSiqdIZXGQNhttWIujaAGF2FqQAKAKzbLoGQLoKqFHWAkA3HoASSgI1gjTA1MSAEF440YGVMQSDMJhEA)

```sh
--parser html
```

**Input:**

```html
<a
  {% if context=="something" %}
    href="/target1"
  {% else %}
    href="/target2"
  {% endif %}
  >
  Link Text
</a>
```

**Output:**

```html
SyntaxError: Unexpected closing tag "a". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (9:1)
  7 |   >
  8 |   Link Text
> 9 | </a>
    | ^^^^
```

**Expected behavior:**

Liquid conditions within the attribute space of an tag should not result into parser errors.
The output should rather be like:

```
<a {% if context=="something" %} href="/target1" {% else %} href="/target2" {% endif %}>
  Link Text
</a>
```

**There is a workaround though**
```
{% assign test_1 = context == "something" %}
<a
  {%- if test_1 -%}
    href="/target1"
  {%- else -%}
    href="/target2"
  {%- endif -%}
  >
  Link Text
</a>
```

Does result in:
```
{% assign test_1 = context == "something" %}
<a {%- if test_1 -%} href="/target1" {%- else -%} href="/target2" {%- endif -%}>
  Link Text
</a>
```

**Comment by alexander-akait** [comment]
Please use search, https://github.com/prettier/prettier/issues/3695

**Comment by thet** [comment]
@alexander-akait apparently this issue is not solved. I do get this error with prettier 2.3.2 as well as in the playground.

**Comment by alexander-akait** [comment]
we don't support `Liquid` and you can create custom plugin for this
