### ISSUE TITLE
HTML Formatter: attribute values with Liquid conditions break ugly.

### ISSUE THREAD

**Issue by thet** [prettier/prettier#11200]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiMAKS6YBm+xZA+jAJ4AOcu55XAHIwpOAEYhuWgF9CpEuLq4EWZrNzKmLBRx58Bw0STgAmKbPllTy1do1bmVknt79BIsQGYLc1iS9bKDVpGWoAPkooXFwACzgCAggAOijUAHosbHCQABoQCG4YTGgSZFAiACdKiAB3AAUqhDKUIgJaok4y-IAjSqIwAGs4GABlbgHMKABzZBhKgFc4fLgAWx64dHRNgBkiGYWiabgAMQhK1aIYYpnkECIFmAg8kFiYVYIAdVjMeBIJsBwUbNX44X6cO5gMgvKYmSower9aaXZCMNomfIAKxIAA8AEL9IYjUZEVZwHZTOCo9HLEDYnGjKbTAhwACKCwg8GpBAxIAmlThdzeHxe3EqUxgn0w6BgsWQAA4AAz5MUQEyffrcO5iuBw7BU-IARw58ERhRa9xIAFooHBNpsXpU4MbME7EUcUUg0TzaSZVpg5otfUyWezOVSvTT8jAiD0pTK5UhTNH+pgCEyAMIQVaekC6gCsLwWJgAKrGWt7edglgBJYIIMZgcVFACCwVGXBZ3JMMhkQA)

```sh
--parser html
```

**Input:**

```html
<div class="{% if class_type == 'case1' %}class1{% endif %} {% if class_type == 'case2' %}class2{% endif %} {% if class_type == 'case3' %}class3{% endif %}">
  hello.
</div>
```

**Output:**

```html
<div
  class="
    {%
    if
    class_type
    ==
    'case1'
    %}class1{%
    endif
    %}
    {%
    if
    class_type
    ==
    'case2'
    %}class2{%
    endif
    %}
    {%
    if
    class_type
    ==
    'case3'
    %}class3{%
    endif
    %}
  "
>
  hello.
</div>

```

**Expected behavior:**

Liquid condition syntax should not be broken into newlines.
I'd exect something like:

```html
<div
  class="
    {% if class_type == 'case1' %}
      class1
    {% endif %}
    {% if class_type == 'case2' %}
      class2
    {% endif %}
    {% if class_type == 'case3' %}
      class3
    {% endif %}
  "
>
  hello.
</div>

```

**Comment by sosukesuzuki** [comment]
We don't support Liquid, so we don't format the contents of the class. But you can set `--embedded-language-formatting` to `off` to preserve contents of class.
