### ISSUE TITLE
Curve formatting

### ISSUE THREAD

**Issue by Jebati** [prettier/prettier#11209]
Before formatting:
![image](https://user-images.githubusercontent.com/24898536/126052262-f6fc8753-c2dc-4ff3-8c69-8f16462c6978.png)

After formatting:
![image](https://user-images.githubusercontent.com/24898536/126052264-78d749f9-017a-404b-946d-d0a7257806e6.png)
![image](https://user-images.githubusercontent.com/24898536/126052266-5515ca67-a8c0-4da1-9c0a-757dbc60047b.png)

I meet this quite often.
Are there any options how to fix this?

**Comment by sosukesuzuki** [comment]
It is intended for correct rendering in browsers. You can use `--html-whitespace-sensitivity` option to control this behaviour. Please see https://prettier.io/docs/en/options.html#html-whitespace-sensitivity for more details.
