### ISSUE TITLE
Support for jsonnet

### ISSUE THREAD

**Issue by jcpunk** [prettier/prettier#11207]
**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: CLI
- Runtime: 
- Operating System:Linux
- Prettier plugins (if any): None

**Steps to reproduce:**

Attempt to run prettier against a jsonnet file (https://jsonnet.org/ref/spec.html).  Jsonnet is similar, but not identical to `JSON`

**Expected behavior:**

Able to parse and make pretty

**Actual behavior:**

File is not made pretty due to unsupported language/syntax/extension.

**Comment by alexander-akait** [comment]
You can create plugin for this, it is not popular, so we don't want to put it in core, please read https://prettier.io/docs/en/plugins.html
