### ISSUE TITLE
Feature request: expand on label builder

### ISSUE THREAD

**Issue by Janther** [prettier/prettier#11205]
With version 2.3.0 the builder [label](https://github.com/prettier/prettier/blob/main/commands.md#label) was introduced.
This has helped a lot for `doc` analysis and making printing choices in our plugin. But the signature says that label should be a `string` and we are using `JSON.stringify()` and `JSON.parse()` to pass additional data.

It would be great if the `label` specification could also expand to support metadata or have a dedicated `metadata` builder that behaves the same as label but receives an object.

**Expected behavior:**

I could call `label` like

```JavaScript
label({ label: 'foo', ...additionalData }, doc);
// or
metadata(additionalData, doc);
```

**Actual behavior:**

I'm only capable to call

```JavaScript
label('foo', doc);
```

**Comment by thorn0** [comment]
@Janther We're going to change the signature of `label` in v3.
See https://github.com/prettier/prettier/pull/13532/files#diff-36a23b056c0b88915240fda511cce74477567f8b3891b96d0764f3232098c0fd

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/13532
