### ISSUE TITLE
React shorthand Fragment (<> </>) doesn't work with prettier

### ISSUE THREAD

**Issue by 1xiscool** [prettier/prettier#11203]
With React Fragments if you use the short hand <>(open)</>(close) when prettier runs on commit it stopes it from committing and throws an error. If this is a styling issue then change it it  Fragment <Fragment> </Fragment>but if this is not a code formatting style choice then Prettier should handle either king of Fragment

**Comment by sosukesuzuki** [comment]
Prettier formats syntax sugar of `React.Fragment` correctly. Review the settings of your environment other than Prettier. Also please use issue template.

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBhCBbAB2gSwF5MAKASk1ID5MAeOxgejoG4AdKEAGhAQCMAJbpkoAIYAnaRADuABRkI0yEJIA28yQE81AgEbTJYANZwYAZQKmRUAObIY0gK5wBcPIbgATX34AMpKOrpIOcABiENJ4kjCijuqSrjAQ-CAAFjB4mgDqmSLwaLZgcFaqRSIAbkW66mBoBiD2aHDSMIomDnHIAGZabQIAVmgAHgBCJuaWVpJ4cIH2cP2DHiCjY1b2DppwAIquEPCrmkMgttJt0uqGkj6aGQTS9jB5Ir4wmcgAHAAMAmeEDaeRMBHUzzg12qKwEAEcjvAukI1ChJGgALRQOB+PwZaRwBEiAldcK9JADM7rNp4ETONzUnZ7Q7HFYUtYCGD3d6fb5IABMnJMIk0O1weHJIChAFYMq42gAVe6oynnaruACSUACsCsYBewgAgtqrDBdHtTm0AL5WoA)

```sh
--parser babel
```

**Input:**

```jsx
const Component = () => <></>;

```

**Output:**

```jsx
const Component = () => <></>;

```
