### ISSUE TITLE
import, export, destructuring, component declaration always to one line unless printWidth exceeds

### ISSUE THREAD

**Issue by hieunm22** [prettier/prettier#11201]
hi all
I'm using prettier to format my code
my expectation for import, export, destructuring, component declaration is always wrap all items in one seperate line

```javascript
// expect
import {
  componentA,
  componentB,
  componentC,
  componentD,
  // .....
} from 'some/path/to/component'
```

```javascript
// actual
import { componentA, componentB, componentC, componentD } from 'some/path/to/component'
```
in some cases which import line has printWidth exceeds the number defined in .prettierrc config then it wraps as expect. But I want it always to wrap all items in one seperate line
the same expectation also applies to export, destructuring, component declaration
component declaration is 
```javascript
// expect
<ComponentA
  props1={props1}
  props2={props2}
  props3={props3}
  props4={props4}
/>
// actual
<ComponentA props1={props1} props2={props2} props3={props3} props4={props4} />
```

so is my expectation above possible?

**Comment by sosukesuzuki** [comment]
Sorry probably it isn't possible. We follows `printWidth` for those formattings.
