### ISSUE TITLE
Dotfile / package.json configuration

### ISSUE THREAD

**Issue by DanielMSchmidt** [prettier/prettier#1121]
Hi there,

I am working in a team of 10 people using like 20 editors and we would benefit heavily if every plugin and our format command would rely on a single source of truth regarding the configuration. If you are interested I would go forward and add a PR to include that.

I am sorry if I overlooked any issue related to that.
Keep on with the great work 👍

**Comment by hawkrives** [comment]
There's a PR and some discussion in https://github.com/prettier/prettier/pull/1086

**Comment by DanielMSchmidt** [comment]
Thanks for linkning @hawkrives!
