### ISSUE TITLE
Removes parentheses around binary + (add / concat)

### ISSUE THREAD

**Issue by lightmare** [prettier/prettier#11225]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAllAJnAHgAgGp8BGASiPwB0RcaBuKqJjbPS8ygZwFcAzPulyMoIADQgIABxjpoXZKACGAJxUQA7gAVVCBSiUAbDUoCeCiQCMVSsAGs4MAMpTbmAObIYKnnAlwAW0s4LBwsABklKHceJXc4ADEIFQClGFlo5BAlHhgIcRAACxgAwwB1QvR4LlcwOCc9KvQANyrTLLAuCxBMLjgVGC0bd1TkPiM+iQArLlwAIRt7RyclALhwzDgxib8QGdwnD0M4AEUeCHhtw0mQVxU+lSzLJWDDAqkVTBgy9CwYQuQAA4AAwSD4QPplGxSLIfOAPZpbCQAR3O8CG0n02S4AFooHAQiECio4Kj0CShnFRkhxtddn0AugvD56UdTmitjSdhIYC8fn8AUgAEw8mzoQweADCEAC1JA8IArAUeH0ACovfS0m7NXwASTYsCcYE+MgAgtgnDBTMcrn0AL52oA)

```sh
--parser babel
```

**Input:**

```jsx
(index + 1) + "x";

(index + 1) + suffix;

```

**Output:**

```jsx
index + 1 + "x";

index + 1 + suffix;

```

**Expected behavior:**
Leave the code as is. The parentheses clarify intent to concatenate a number `(index + 1)` with a string `suffix`.

Removing the parentheses also makes the expression more prone to refactoring errors. If someone later decides to prepend a prefix to the string, it's very easy to make this mistake: `prefix + index + 1 + suffix`.

**Comment by sosukesuzuki** [comment]
We discussed about the issue a few times(Sorry I forgot links). Then, Prettier probably will never support the formatting you expect. But there is a workaround that is to use `// prettier-ignore` comment.

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSgApCoATOADwwGoMBGASm4ZaIdiIDc9ek1YchAoQGcArgDNVhdpKggANCAhYi0RclABDHDggB3AAqWEplOYA2N8wE9T+gEY5zMABrfABlLEDmCmQYHGU4fTgAW184FjYWABlzKAplcwo4ADEaJPMCKOQQc2UYCD0QAAsYJNcAdUbCeEUIsDhQpy7CADcuzyqwRR8QZkUSGDsAijLkVTc5-QArRXYAIQDgsPMkuEzmOFX1hJBt9lCo1zgARWUIeEvXDZAInDmcKt85lSrgauGYMDahBYMEayAAHAAGfS4CBzNoBLBVXBwP7DC76ACOr3gi0MzmqilIUDgaTSDTwRMIeEWBRWSDWn2ucyShBicS5D2exIu7Ku+hgQMh0NhSAATOKAoRXFEAMIQJJskA4gCsDWUcwAKkDnByvsN4gBJWSwUJgHCEIwAQVYoRgnkeHzmAF8vUA)

```sh
--parser babel
```

**Input:**

```jsx
// prettier-ignore
(index + 1) + "x";

(index + 1) + suffix;

```

**Output:**

```jsx
// prettier-ignore
(index + 1) + "x";

index + 1 + suffix;

```

**Comment by lightmare** [comment]
Thanks for the quick response. I did search existing issues, found a few relating to parentheses, but only two somewhat similar were about different operators' precedence.

The workaround you suggest is kinda ham-fisted. Such an expression won't stand by itself, it could be a function argument or an arrow function expression (which is how I encountered it). Ignoring the whole line is far from ideal.

**Comment by alexander-akait** [comment]
You don't need parentheses in this case, due add/content go left to right

**Comment by lightmare** [comment]
> You don't need parentheses in this case, due add/content go left to right

That's irrelevant. I don't need parentheses in `1 ** (2 ** 3)` or `(3 << 2) << 1`, so why does prettier keep/insert those?

**Comment by alexander-akait** [comment]
Due to the historical reasons of parsers and bugs in browsers
