### ISSUE TITLE
If a file only contains JSX <tags>, a semicolon will be placed at the start of the file if no-semis is true...

### ISSUE THREAD

**Issue by RickGove** [prettier/prettier#11231]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAsgQwJZQHwA6UABMagBYCMeAEnADb0SoD0VhUrWueIANCAgAHGNmgBnZKEwAnGRADuABVkJJKTPQWYAnpIEAjGZjABrODADKQk7gDmyGDICucAXAC2BuABMfvgBlMKDtnTDs4ADEIGQ9MGFEQ5BBMZxgIfhByGA96AHVybHhxGzA4SzUi7AA3Ip1ksHF9EFxxOBkYJWM7OOQAM002gQArcQAPACFjMwtLTA84ANw4fsG3EFGxy3t6OABFZwh4VfohkBsZNplkg0xvekyhGVwYPOwfGHJkAA4ABgEnhA2nljEJkk84FdqisBABHQ7wLrCdQpcQAWigcF8vkyMjg8OweK64V6SAGp3WbQ82BOZ3EO32CJWZLWAhgdzeHy+SAATGzjNh6PYAMIQDykkCQgCsmWcbQAKnd1OSztVXABJKD+WCWMDPEQAQS1lhgOl2tLgAF9LUA)

```sh
--parser babel
--no-semi
```

**Input:**

```jsx
<Main>
  <h1>Hello</h1>
</Main>
```

**Output:**

```jsx
;<Main>
  <h1>Hello</h1>
</Main>

```

**Expected behavior:**
No semicolons anywhere...

this is important for a project I am working on...Thank you

**Comment by sosukesuzuki** [comment]
Why did you format HTML tags with `babel` parser?

**Comment by fisker** [comment]
I think we should fobid use `parser` in prettierrc root

**Comment by RickGove** [comment]
> Why did you format HTML tags with `babel` parser?

It's not Html. It's JSX with nothing surrounding it. I don't want <Main /> changed to <main />

**Comment by fisker** [comment]
How are you going to use this file with only one statement?

**Comment by RickGove** [comment]
> How are you going to use this file with only one statement?

It's for a React IDE we are developing.

The more I think about it, the more I understand that it's a probably a very niche situation.

![image](https://user-images.githubusercontent.com/63856101/126450642-86104dde-abb2-4bc6-a9a3-6daee26780b8.png)

**Comment by fisker** [comment]
It's expect behavior, it's the same if you only put an  array `[]` in this file.

**Comment by fisker** [comment]
I think you'll need to write your own plugin for this https://prettier.io/docs/en/plugins.html#developing-plugins

**Comment by sosukesuzuki** [comment]
Sorry we probably won't fix anything for this.

**Comment by sosukesuzuki** [comment]
Actually, it may be enough to remove the first character of the formatting result.

**Comment by RickGove** [comment]
> Actually, it may be enough to remove the first character of the formatting result.

You're right, that might be all it takes
