### ISSUE TITLE
Support /** @type {InlineType} */ (templateFn)``

### ISSUE THREAD

**Issue by wmertens** [prettier/prettier#11239]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAkjDBLAcyggCc4BnDACgEoAdKSKc3AeQDc4SAbAQwAcA6iQH8uGALwM6MVACo5GAAIwAnmIzA8AW36kYVAOQtV3OABMAtJF3QEMcoZoA6ACoALONosBlNWfMAMQBXRhg8aAAeQ3M8dkMAGihg7m4E4AhOHgEkDAAjCAgzXigAXwA+Uow5VGkDEwDnWPYaAAMGPXI8cOgkMj5wzgBuOplyzTrO7oioXN488iLg+BGoGQKYGAhtXIASYH5Jcf5nTK4+Q4krjEN+MnYI4McMADIXjAAGUtWZX82Ifh7A5HDAnM7ZS7XQxQOAADxghle7y+PxgMlKdXaayg6AwAGFSGQwDAkAwmCwMBxzgJhKJxFI1g5-BYmnEsVMerN+rxBnBUWMJoyOTM5gslis6hstjsMPtLsdTlkLpIoXc4A8IE9EW9Pt9Rmj-oDZcCJArwcqrhIbjD4drkXrGejMdIoCAEiAAZzyMhQLwSCQIAB3AAKfoQ3pQvG4gd4qm97ryIjAAGs4DAfPxeGA8FACMgYCRgnB3V48hZzBYADIlAjBXgEOCBUjaHnhXPIEC8ZYQN0gdwwbTcQTuboUTNgOA+cPTB5qDtgcjxkA58hcGDBkQEFvIABmUdX7oAVuRYQAhJOp9O8byVnNwXf74sgY+wnw5ghmACKwQg8Af3APEBMxIVcSA7PJ5jgbhezuHMYEEPBzBgdxkAADg+d07ggVdaX4Ds1VAzhewARx-eANwBCNO3ISwYQsCxezIUi8DIDd623JA9wAp9V20PB80LHj3y-Mj704x93RgeYEKQlCkAAJkkkQ8G4d8CW0DiQAoABWXsnjgVx5gjLjAPYIssCgCtYB8MASDwfgYAAQUsvxTDEky4FKUogA)

**Input:**

```jsx
const OverlapWrapper = /** @type {import('styled-components').ThemedStyledFunction<'div',null,{overlap: boolean}>} */
(styled.div)`
position:relative;
		> {
	position: absolute;
	bottom: ${p => p.overlap === 'previous' && 0};
			top: ${p => p.overlap === 'next' && 0};
		}
	`
```

**Output:**

```jsx
const OverlapWrapper =
  /** @type {import('styled-components').ThemedStyledFunction<'div',null,{overlap: boolean}>} */
  (styled.div)`
position:relative;
		> {
	position: absolute;
	bottom: ${(p) => p.overlap === "previous" && 0};
			top: ${(p) => p.overlap === "next" && 0};
		}
	`;
```

**Expected behavior:**

it should detect that `/** @type ... */ (styled.div)` is the same as `styled.div` and format accordingly

**Comment by fisker** [comment]
I don't think we should support reassigned tags, but the `ParenthesizedExpression` should be supported, it's a bug in babel parser.
