### ISSUE TITLE
Using inline comments (/* */) before an element attribute's value in JSX causes document to not be formatted

### ISSUE THREAD

**Issue by edazpotato** [prettier/prettier#11242]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAsgJ4Bim2eUAwhALYAO0CMAFAJT7AA6U3MAHgBG6GDAIAbAIZC4EgLwB6AFRxli7iDiaAfCLHQBi-eKg7eAXxAAaEBAa5oAZ2SgpAJ3cQA7gAUPCC4oUhLeUsQutkLuUmAA1nAwAMoMsThQAObIMO7ocLZwdLIAJsVwxQAyUpnoUhlwpBDudFJi6VnBohA2IAAWMHQSAOq9OPBOqWBwSYFjOABuY8TI4E6RIOlOcO4wvjEZLcioIVu2AFZOAB4AQjHxiUlSdHAV6XBHJ-kgF5dJ7RJwACK6Ag8A+ElOIFS7i27hWQhkch6DHc6RgQxwxRgvWQAA4AAy2FEQLZDGIMFYouCw+bvWwARxB8D29iCICkTgAtFA4OVyj13HBGThBXs6ockMcIV8tnQcNlcjL-kCme9JZ9bDAZBisTikAAmTUxHASdq0OgSrROACsPXQWwAKjIglLIfM8gBJKBlWBJMCohwAQW9SRgxAB4K2FgsQA)

```sh
--parser babel
```

**Input:**

```jsx
function MyFunctionComponent() {
	<button label=/*old*/"new">button</button>
}
```

**Output:**

```jsx
Error: Comment "old" was not printed. Please report this error!
    at Object.ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:36:119166)
    at Sd (https://prettier.io/lib/standalone.js:36:125590)
    at Nd (https://prettier.io/lib/standalone.js:36:128103)
    at Object.formatWithCursor (https://prettier.io/lib/standalone.js:76:38121)
    at formatCode (https://prettier.io/worker.js:141:21)
    at handleMessage (https://prettier.io/worker.js:78:26)
    at self.onmessage (https://prettier.io/worker.js:36:14)
```

**Expected behaviour:**
The document should be formatted as usual

**Comment by sosukesuzuki** [comment]
Workaround
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAsgJ4Bim2eUAwhALYAO0CMAFAJT7AA6U3MAHgBG6GDAIAbAIZC4EgLwB6AFRxliniDjcQAXwB8IsdAGKj4qPt66QAGhAQGuaAGdkoKQCdPEAO4AFLwQ3FCkJXyliN3shTykwAGs4GABlBnicKABzZBhPdDh7ODpZABNSuFKAGSls9CksuFIITzopMUyc0NEIOxAACxg6CQB1fpx4F3SwOBTgiZwANwniZHAXaJBMlzhPGH84rLbkVDCd+wArFwAPACE4xOSUqTo4Ksy4E7PCkCvrlM6EjgAEV0BB4F8JOcQOlPDtPGshDI5H0GJ5MjARjhSjB+sgABwABnsaIgOxGcQYazRcHhi0+9gAjmD4AdHCEQFIXABaKBwSqVPqeODMnDCg4NY5IU5Qn47Og4XL5OWAkEsz7S772GAyLE4vFIABM2riOAknVodClWhcAFY+ugdgAVGQhGXQxYFACSUAqsBSYHRTgAgr6UjBiEDITtdLogA)

```sh
--parser babel
```

**Input:**

```jsx
function MyFunctionComponent() {
	<button label=/*e*/{"e"}>button</button>
}
```

**Output:**

```jsx
function MyFunctionComponent() {
  <button label=/*e*/ {"e"}>button</button>;
}

```
