### ISSUE TITLE
Empty line is not formatted

### ISSUE THREAD

**Issue by vvscode** [prettier/prettier#11274]
One empty line makes huge difference

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAzgVwLYYBmOUYMAltERAE4ZT4BGcNWAOlHAB4AOtMREmUpRs+AIwAKDhgwBDADQzZyjIw4BKDMGU04MHDVFyMAajUBuDgF8Odzr36DSFKrjwAmaaPlKfazW1dfUNjM0sbEAUQCB5XKCxkUDkaGggAdwAFFIRElDkAG3S5AE9E6MYaOTAAa30AZR5q8igAc2QYGhw4aLg8ZgATAbgBgBk5Npw5VrgAMVo8ORgKNuQQORwYCCiQAAsYPAKAdV3yeCwmsDh63LPyADczkrWwLHKQFqwWGEyq1sXkIRCl9ogArLBcABCVVqDTkeDgoxacEBwJ6IHBXHqLVaBTgAEUcBB4KiCiCQE1WCw1ow5MwCjseDQWjAjuQBjBdsgABwABmiTIgXyOVR4ayZcC+NHuKOiAEcifBfrE8ussABaTgjEY7PQK8h6X7TAFIIFk9FfPDkDpdC04vGE4ko01o6IwOlsjlcpAeN1VcgFHEAYQgeBNIElAFYdjgvgAVOl5M3k+7dACSUGGsHqYGZcQAgpn6jASnjSV9rNYgA)

```sh
# Options (if any):
```

**Input:**

```jsx
// sum function for numbers
export function sum1(
  a,
   
   b
) {
  return a + b;
}


export function sum2(
  a,
   b
) {
  return a + b;
}
```

**Output:**

```jsx
// sum function for numbers
export function sum1(
  a,

  b
) {
  return a + b;
}

export function sum2(a, b) {
  return a + b;
}

```

**Expected behavior:**

```jsx
// sum function for numbers
export function sum1(a, b) {
  return a + b;
}

export function sum2(a, b) {
  return a + b;
}
```

**Comment by vvscode** [comment]
I guess it's connected to https://prettier.io/docs/en/rationale.html#empty-lines so is not an issue

**Comment by sosukesuzuki** [comment]
Yes, this is intended
