### ISSUE TITLE
hex format

### ISSUE THREAD

**Issue by 5alidshammout** [prettier/prettier#11275]
HEX format is a setting where you can choose whether uppercase and lowercase, uppercase makes all the hex codes like `#3DBBFF` and lowercase makes them `#3dbbff`, I think this will be a nice setting

**Comment by sosukesuzuki** [comment]
Can you use the issue template?

**Comment by 5alidshammout** [comment]
wdym?

**Comment by kachkaev** [comment]
When creating a new issue, please use one of these files as a template:
https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE

Deleting the template makes it much harder for repo maintainers to triage new issues. As a result, this delays their response.
