### ISSUE TITLE
WebStorm 2021.2: Prettier on Save seems to be broken

### ISSUE THREAD

**Issue by derwaldgeist** [prettier/prettier#11278]
I just updated WebStorm to 2021.2 and noticed that prettier won't run anymore if I save a file, although the option is still checked. Seems as if it is broken?

**Comment by mchrostowski** [comment]
I noticed the IntelliJ 2021.2 update prompt stated that the Prettier plugin is "... incompatible with the new build..."

**Comment by derwaldgeist** [comment]
This is interesting, because prettier is a default plugin in WebStorm now.

**Comment by mordgard** [comment]
The same for me, not working on save. 2021.2

**Comment by sosukesuzuki** [comment]
Sorry, I don't use JetBrains IDE and I'm not sure why this is happened. It may be better to report this bug to JetBrains side.

**Comment by thorn0** [comment]
This is not an issue with Prettier core.
