### ISSUE TITLE
Prettier formatting "breaks" typescript jsdoc types

### ISSUE THREAD

**Issue by daKmoR** [prettier/prettier#11279]
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgBAARgTwAc4tgBLAW0IgCcYAKAchojAGs4ZUwAbMxgJQA6AEqsOMAMJ9J0AGZkA5gF8s6VAB0ocAB7U6WACZw5AQwCuPGFnrAtWLCx49zhJFkhQFirAF4AfDZ2UA4OQuGe3gA0Whow8ADOMO6MFHCM9ljKAjFQ2QDcIFEgEIQwZNAJyKCmNCwA7gAKtQhVKKYAbhBkhkUgAEY0puycAMqEw2RQisgwNOZwxXAU-XCGxoYAMqbT5qaKcABitBSm8VMz7eYwEH0AFjAUPADqd2SJE2Bwo63vZB3vfDIcAJKrFKYJOB0RpDRSnZBmHiQ4oAKwSOgAQkMRjBRqY0pspnAEaYkYsQGidKMLjw4ABFcwQeAksnFCY0SE0YH9UyrHh9Qg0KYwZ49GB3ZAADgADGyWJDnkNCMDBXBOR1icUAI6M+Aw0ptECmBIAWm0azWfRocB1ZGtMP28KQiORIEhFDIs3m5ISNPpuuJztJrpgvNFhnFyAATMU5qYyHxprIKE6QGqAKx9cyQgAqvLaLvJHQWAEkoMZYKMwEKygBBcujAi0lmQ5TKIA)

```sh
--parser babel
--arrow-parens avoid
```

**Input:**

```jsx
/** @type {import('rocket/cli').RocketCliConfig} */
export default ({
  rollup: config => ({
    ...config,
	test: 'me'
  }),
});
```

**Output:**

```jsx
/** @type {import('rocket/cli').RocketCliConfig} */
export default {
  rollup: config => ({
    ...config,
    test: "me",
  }),
};

```

**Expected behavior:**

```jsx
/** @type {import('rocket/cli').RocketCliConfig} */
export default ({
  rollup: config => ({
    ...config,
	 test: "me",
  }),
});
```

Typescript will "assign" the type to the object only if it's wrapped in a `()`

```js
/** @type{string} */
(x)
is equivalent to
x as string
```

which results in 
```js
/** @type {import('rocket/cli').RocketCliConfig} */
export default {
  // type any
} 

/** @type {import('rocket/cli').RocketCliConfig} */
export default ({
  // type RocketCliConfig
});
```

Would there be a way to keep the `()` around `export default`?

**Comment by thorn0** [comment]
It's a bug in TS. You shouldn't rely on this behavior because eventually it'll be fixed (i.e. will stop working). The correct syntax for JSDoc type assertions is a `@type` JSDoc comment _directly_ followed by a parenthesized expression. In this case it'd be:
```ts
export default /** @type {import('rocket/cli').RocketCliConfig} */ ({
  // type RocketCliConfig
});
```
Anything else isn't the correct syntax and shouldn't be relied upon.

See https://github.com/prettier/prettier/issues/8096#issuecomment-616516093
