### ISSUE TITLE
Hexadecimals are replaced with decimals

### ISSUE THREAD

**Issue by josephsavona** [prettier/prettier#1128]
It appears that numbers written in hexadecimal where the value is below some threshold are replaced with decimals, while others are left as hexadecimal. For example I had `const FOO = 0x01;` and it was replaced with `const FOO = 1;`. While the conversion in this example is straightforward, ideally numbers would *always* be left in their original form. In this case I'm implementing a protocol and it's helpful to be able to copy-paste hex values and grep for them in the protocol specification.

**Comment by vjeux** [comment]
Can you make sure you that this is from prettier or that you are using a recent version?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20FOO%20%3D%200x01%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

We're not doing this normalization anymore.

**Comment by josephsavona** [comment]
@vjeux I just ran `yarn upgrade prettier` and tried again; this is still broken.

**Comment by josephsavona** [comment]
Here's a repro: https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Frame%20%3D%20%7B%5Cn%20%20type%3A%200x01%2C%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Looks like this is a bug in `NumberLiteralTypeAnnotation`, good catch!
