### ISSUE TITLE
Template literals incorrectly formatted (mismatched indentation)

### ISSUE THREAD

**Issue by KieranP** [prettier/prettier#11284]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wBsIBzASygFUi5s8BePACgDcBDbKrgI1JwiSPBH4ArOGBgAaPBWxcMACwCOpUSV5QKAShYA+ADpQ8eALYBXGFxhVobAAanz567fuOAJHAtcqTTwAZRgdCgBCeW8MLiIiAHccABNRUPCovG8IGAwAYQhkuDSwmn08YFc3c3JqOgZsNhoMG1FKs2q3PwCg339A2SrOvFj4pOxUrNHElMGO4Zz8wuKsxYKiobcAXwN24fNvYEVldVItzfNz+bwr8yd5bl4BISI9EFkQCAwvYmRQHmwEASAAUeAgiMgQFwOBAqMl3iB+EowABrOAwYKxMBlZBhKxwD5+fhwZJFZIAGS4uisXAocAAYjh-DB7LpIVwbBAESoYBZSAB1FRUeBELFwYLg4VUDjCgCekLA8QRNAaMGBSgo-mQADMuKQGB8JEQ0AAhZFojFcCxwck0OA6vUGkBGtDBMpCACKVhy9qQuv1BJAsWwDUhMFlGGEYF43wRGB0MH5cJgKmQAA4AAwfeMQBj8pQYSHx4SMDj2j5qb3wdVfCEoOIAWigcBJJIR2DglaoHfVtK1fsdgYYFioDoDHyI7rgXp9Y6dtn4SeSKeQACYPmEemUChZ+yAoNByyArAwACoCOv+p0cfEASSgRVgwWjVG+AEEH6FZUI53AtlsgA)

```sh
--parser typescript
--no-semi
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx
export const loginUser = (variables: object, graphql: string) =>
  mutation(`
    mutation($email: String!, $password: String!, $otpCode: String) {
      loginUser(input: {
        email: $email,
        password: $password,
        otpCode: $otpCode
      }) {
        ${graphql}
      }
    }
  `, variables)
```

**Output:**

```tsx
export const loginUser = (variables: object, graphql: string) =>
  mutation(
    `
    mutation($email: String!, $password: String!, $otpCode: String) {
      loginUser(input: {
        email: $email,
        password: $password,
        otpCode: $otpCode
      }) {
        ${graphql}
      }
    }
  `,
    variables
  )

```

**Expected behavior:**

```tsx
export const loginUser = (variables: object, graphql: string) =>
  mutation(
    `
    mutation($email: String!, $password: String!, $otpCode: String) {
      loginUser(input: {
        email: $email,
        password: $password,
        otpCode: $otpCode
      }) {
        ${graphql}
      }
    }
    `,
    variables
  )

```

**Comment by sosukesuzuki** [comment]
This is intended. Because the template literal in actual output and expected output are different. Prettier should keep contents.
<img width="499" alt="スクリーンショット 2021-08-02 2 45 56" src="https://user-images.githubusercontent.com/14838850/127780544-0ec9ba28-0627-4703-9c86-f41d8fc61c1d.png">
