### ISSUE TITLE
Wrong formatting caused by using Strong.prototype.length

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#11298]
叱 and 𠮟 are similar, but different characters on Unicode.
The former is 16 bit, while the latter is 32 bit. Therefore, the result of String.prototype.length is different, and the format result is also different.

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCECMAKA9IIQ3B8-aKNwEoA6dCAJmwCMBDAJ0uoGYHGAvMgbgA6UIdRy5Aj8qTyVDHSasZETk16CoIADQgIABxgBLaAGdkoFswgB3AAosEJlIwA2lxgE8TW+s0ZgA1nAwAMo6vvpQAObIMMwArnBacAC29HAAJmnpADKMkbGMEXAAYhDMSYwwBpHIIIyxMBCaIAAWMElOAOrN+vBGoWBwQfY9+gBuPW41YEaeIOFGcMww1j4R5ciozgtaAFZGAB4AQj7+gUGMSXBZ4XAbWwkge-tB4RFOcACKsRDwd07bIFCzAWzBqTFSTiaOmY4RgHX0aRgzWQAA4AAxaaEQBYdHw6GrQuAg0a3LQAR2+8BWugctSMAFooHB0ukmsw4BT9OyVgV1khNv8HgskvponEha93l8frd+fctDBGPR4YjkUgaAqfPonK8AMIQJJ8kBEgCsTViCwAKkqHAKAaN4gBJKCZWBBMAwvQAQRdQRgbnefwWAF9g0A)

```sh
--parser babel
```

**Input:**

```jsx
foo1(/𠮟𠮟𠮟/).foo2(bar).foo3(baz);

foo1(/叱叱叱/).foo2(bar).foo3(baz);

```

**Output:**

```jsx
foo1(/𠮟𠮟𠮟/)
  .foo2(bar)
  .foo3(baz);

foo1(/叱叱叱/).foo2(bar).foo3(baz);

```

**Expected behavior:**
```jsx
foo1(/𠮟𠮟𠮟/)
  .foo2(bar)
  .foo3(baz);

foo1(/叱叱叱/)
  .foo2(bar)
  .foo3(baz);

```

**Comment by tomoki3** [comment]
あああああああああああああ
