### ISSUE TITLE
CLI: add a --silent flag?

### ISSUE THREAD

**Issue by Pomax** [prettier/prettier#11302]
**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: CLI
- Runtime: Node 16 I guess? This is a feature request for the CLI invocation, so the actual version probably doesn't really matter =)
- Operating System: Win10 x64 Pro
- Prettier plugins (if any): no

**Steps to reproduce:**

Run `prettier --write` on a dir, and watch it log each file it updates to the console. This can be super useful! However, it can also be super scroll-buffer-polluting so it would be fantastic if there was an explicit `--silent` flag that didn't make prettier log to stdout at all and just run until completion. Errors should still be logged, of course, but when everything's fine, that isn't always welcome log information.

**Comment by sosukesuzuki** [comment]
You can use `--loglevel=silent` for the purpose. See https://prettier.io/docs/en/cli.html#--loglevel for more detail.
