### ISSUE TITLE
`prettier .` suddently not working

### ISSUE THREAD

**Issue by Mister-Hope** [prettier/prettier#11311]
**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: Cli
- Runtime: node14
- Operating System: win10
- Prettier plugins (if any): no

**Steps to reproduce:**

```
PS F:\project\vuepress-theme-hope> yarn prettier --check ./
yarn run v1.22.10
$ F:\project\vuepress-theme-hope\node_modules\.bin\prettier --check ./
Checking formatting...
[error] No matching files. Patterns tried: ./ !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**All matched files use Prettier code style!
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is happening when I  run  `yarn upgrade` in my project today, seems to be an upstream issue

**Expected behavior:**

No error, I have tons of js, md, json, ts files in my project. And it used to work well for months. And I am already on prettier@2.3.2 before this issue happens

**Actual behavior:**

If fails with just `yarn upgrade`

Addtional info:

At least it should format `readme.md` (just ignore my proejct files)

![image](https://user-images.githubusercontent.com/33315834/128328291-a4ec0e24-ba64-4143-8fa8-6447e9f62018.png)

Content of `.prettierignore`:

```
# Node modules
node_modules/

# Dist files
lib/

# VuePress Output
dist/

# VuePress public
**/.vuepress/public/**

# VS Code Config file
.vscode/

# Theme Output Files
packages/theme/**/*.js
packages/theme/**/*d.ts
!packages/theme/types/**/*.d.ts

# Coverage Files
coverage/
```

**Comment by fisker** [comment]
I thought this was fixed https://github.com/prettier/prettier/blob/main/CHANGELOG.md#fix-failure-on-dir-with-trailing-slash-11000-by-fisker, Does `prettier .` (no trailing slash) work?

**Comment by Mister-Hope** [comment]
Nope

**Comment by Mister-Hope** [comment]
@fisker I just found another issue, prettier started failing on my typescript files, but it's working fine before upgrade on deps:

```
× prettier --write:
[error] packages\sitemap\src\node\sitemap.ts: SyntaxError: '=' expected. (6:13)
[error]   4 | import { SitemapStream } from "sitemap";
[error]   5 | 
[error] > 6 | import type { Context, PageComputed, SiteData } from "@mr-hope/vuepress-types";
[error]     |             ^
[error]   7 | import type {
[error]   8 |   SitemapFrontmatterOption,
[error]   9 |   SitemapLinkOption,
[error] packages\sitemap\src\types\index.d.ts: SyntaxError: '=' expected. (2:13)
[error]   1 | /* eslint-disable @typescript-eslint/naming-convention */
[error] > 2 | import type { PageComputed } from "@mr-hope/vuepress-types";
[error]     |             ^
[error]   3 | 
[error]   4 | interface SitemapImageOption {
[error]   5 |   /** The URL of the image. */
```

**Comment by fisker** [comment]
What `npx prettier --file-info packages/sitemap/src/node/sitemap.ts` prints

**Comment by Mister-Hope** [comment]
Update: I will delete my `node_modules` and make a clean install to make sure it's not my problem first. I will update this when I am done.

**Comment by Mister-Hope** [comment]
> What `npx prettier --file-info packages/sitemap/src/node/sitemap.ts` prints

PS F:\project\vuepress-theme-hope> yarn prettier --file-info packages/sitemap/src/node/sitemap.ts
yarn run v1.22.10
$ F:\project\vuepress-theme-hope\node_modules\.bin\prettier --file-info packages/sitemap/src/node/sitemap.ts
{ "ignored": false, "inferredParser": "typescript" }

Done in 0.33s.

**Comment by Mister-Hope** [comment]
Edited: this issue is resolved.

1. I tried on another win 10 pc and it's working
2. I tried deleting node_modules and install, not working
3. I deleted yarn cache and `yarn.lock` then with a slow clean install, and it works. `yarn.lock` is not changed, so I guess there is something wrong in my yarn cache.

**Comment by fisker** [comment]
I wonder what possibly go wrong.
