### ISSUE TITLE
lees formatting problem

### ISSUE THREAD

**Issue by kailong321200875** [prettier/prettier#11339]
Prettier 2.3.2

![QQ图片20210812192938](https://user-images.githubusercontent.com/32283845/129285919-fec25784-2192-4dca-9980-caaca16a591d.png)

![QQ图片20210812193030](https://user-images.githubusercontent.com/32283845/129285922-7189a680-7368-416d-95de-baf951e07bb5.png)

How can I make it work

**Comment by fisker** [comment]
重开一个，仔细看看模板，打开 https://prettier.io/playground/ 填好代码 选项， 右下角 "Report issue"
