### ISSUE TITLE
less format problem

### ISSUE THREAD

**Issue by kailong321200875** [prettier/prettier#11340]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6MBDANmACgDwFkBLfYqACgEoACYAHShpoAEAzAVyjBmOgGckNAH4ADCp269o1Oo2bNIUfjBoATOP2IBzKAHViamAAsaAXhoBmABwAWAAzyFSlTQw8O2A0dMWArADsAGyOTAomxPzo2Hj45jSSPHyUAPq0DGEKNABOcDAc2UwpNABUbh5ehiY0APTqmjr6VaYA1DQA5AAO+O1OzAC+Tv1U1KKM-SAANCAQndLKyKAY2dkQAO64ywj8yCDYaxgAnjvTAEbZ7gDWeQDKne7k2sgw2Rxw03AAtqdwahpqABkMFBtJ5tHAAGIQbKfDAwXgg3YYDgwCBTEDGGCfLB6YzEeD8e5gOA3bb44gAN3xh12YH4JxA5H4cGyMFwF20sOQbGwzOmACt+PgAEIXMDXGA3DCfOAA8hwbm894gQX4G6PLBwACKHAg8EVWD5IHu2WZ2V2mvp6M62XIMG8JmQ1ns0xtEGZegunV2Ns0LIpCumAEddfB2bMdigMPwALRQOC-X7o3Ih4i5dkYTkYA1G5mfYjPV7KrQgzU6vUKpA8w3KmAYU4O4zIABM0xeGGIWEeAGEIJ8uShNH50RxmQAVeuR6tGilvACSUA0sBuYFtcwAgoubjBDpqc3B+v0gA)

```sh
--parser less
```

**Input:**

```less
.calcPxMixin() {
  @functions: ~`(function() {
    const designWidth = 3840
    const actualWidth = 5760
    this.calcPx = function(_) {
      return _ * actualWidth / designWidth + 'px'
    }
  })()`
}
```

**Output:**

```less
SyntaxError: CssSyntaxError: Unknown word (6:7)
  4 |     const actualWidth = 5760
  5 |     this.calcPx = function(_) {
> 6 |       return _ * actualWidth / designWidth + 'px'
    |       ^
  7 |     }
  8 |   })()`
  9 | }
```

**Expected behavior:**

**Comment by fisker** [comment]
The next branch seems fixed the parse error, but not formatting as JavaScript code.

**Prettier pr-9583**
[Playground link](https://deploy-preview-9583--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEA6MBDANmACgDwFkBLfYqACgEoACYAHShpoAEAzAVyjBmOgGckNAH4ADCp269o1Oo2bNIUfjBoATOP2IBzKAHViamAAsaAXhoBmABwAWAAzyFSlTQw8O2A0dMWArADsAGyOTAomxPzo2Hj45jSSPHyUAPq0DGEKNABOcDAc2UwpNABUbh5ehiY0APTqmjr6VaYA1DQA5AAO+O1OzAC+Tv1U1KKM-SAANCAQndLKyKAY2dkQAO64ywj8yCDYaxgAnjvTAEbZ7gDWeQDKne7k2sgw2Rxw03AAtqdwahpqABkMFBtJ5tHAAGIQbKfDAwXgg3YYDgwCBTEDGGCfLB6YzEeD8e5gOA3bb44gAN3xh12YH4JxA5H4cGyMFwF20sOQbGwzOmACt+PgAEIXMDXGA3DCfOAA8hwbm894gQX4G6PLBwACKHAg8EVWD5IHu2WZ2V2mvp6M62XIMG8JmQ1ns0xtEGZegunV2Ns0LIpCumAEddfB2bMdigMPwALRQOC-X7o3Ih4i5dkYTkYA1G5mfYjPV7KrQgzU6vUKpA8w3KmAYU4O4zIABM0xeGGIWEeAGEIJ8uShNH50RxmQAVeuR6tGilvACSUA0sBuYFtcwAgoubjBDpqc3B+v0gA)

```sh
--parser less
```

**Input:**

```less
.calcPxMixin() {
  @functions: ~`(function() {
    const designWidth = 3840
    const actualWidth = 5760
    this.calcPx = function(_) {
      return _ * actualWidth / designWidth + 'px'
    }
  })()`
}
```

**Output:**

```less
.calcPxMixin() {
  @functions: ~`(
      function() {const designWidth = 3840 const actualWidth = 5760 this.calcPx =
        function(_) {return _ * actualWidth / designWidth + "px"}}
    )
    () `;
}

```

**Comment by alexander-akait** [comment]
Maybe we should apply js printer for this case

**Comment by fisker** [comment]
Fixed  by https://github.com/prettier/prettier/pull/14109
