### ISSUE TITLE
Support formatting code from other languages inside RMarkdown code blocks?

### ISSUE THREAD

**Issue by benwhalley** [prettier/prettier#11364]
(Apologies if this should be posted to the markdown parser repo and not here)

In RMarkdown, three backticks indicates a code block, which can be in various languages (e.g. R, python).
Is it possible to get prettier to defer parsing/formatting within these blocks to secondary parsers?

Example inputs (as graphics because of formatting issues with backticks here):

<img width="577" alt="Screenshot 2021-08-18 at 12 42 52" src="https://user-images.githubusercontent.com/524696/129892452-8c68718a-29d3-4544-a1ca-491800fff579.png">

Expected output:

<img width="566" alt="Screenshot 2021-08-18 at 12 43 22" src="https://user-images.githubusercontent.com/524696/129892459-8bd5df1f-5d1a-42bd-897f-c8e0541c21ee.png">

(syntax highlighting also broken in atom at the moment for python blocks!)

**Comment by sosukesuzuki** [comment]
Prettier does not support RMarkdown, Python and R. Also sorry, I think we won't support it never. However you can create plugins that support it (See https://prettier.io/docs/en/plugins.html about plugins).
