### ISSUE TITLE
Please help to maintain `eslint-plugin-prettier`, again.

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#11361]
Sorry, but I have to raise an issue same as #10699 again.

---

No really an issue of prettier core itself, sorry.

I've been suffered from prettier/eslint-plugin-prettier#411 and prettier/eslint-plugin-prettier#414. And I've raised two PRs prettier/eslint-plugin-prettier/pull/413 and prettier/eslint-plugin-prettier#415 to fix them, and the current maintainer @BPScott did review 3 months ago, but disappeared again later...

So I'm here to ask for help from the core maintainers.

It's been **4 months** since I opened those PRs.

Is there any more active maintainer can offer help?

**Comment by JounQin** [comment]
It becomes a bit ridiculous since the PR has been raised for more than one year!

cc @sosukesuzuki @fisker @j-f1 @thorn0 

I'll have to publish a fork instead...

**Comment by JounQin** [comment]
> Just released `@rxts/eslint-plugin-prettier@4.1.0`, source codes at https://github.com/JounQin/eslint-plugin-prettier/tree/fork-release, you can use
> 
> ```sh
> # yarn
> yarn add -D eslint-plugin-prettier@npm:@rxts/eslint-plugin-prettier@^4.1.0
> 
> # pnpm
> pnpm add -D eslint-plugin-prettier@npm:@rxts/eslint-plugin-prettier@^4.1.0
> 
> # npm
> npm i -D eslint-plugin-prettier@npm:@rxts/eslint-plugin-prettier@^4.1.0
> ```
> 
> Then it will just work the same as before with this feature enabled.

**Comment by sosukesuzuki** [comment]
@JounQin I am not going to actively develop eslint-plugin-prettier, but I will at least do a PR merge and release. I do not have the permission to release eslint-plugin-prettier right now, so I need to contact @BPScott

**Comment by JounQin** [comment]
If @BPScott is not actively maintain `eslint-plugin-prettier`, maybe the project should be given to a more active maintainer. 🤷🏻‍♂️

**Comment by sosukesuzuki** [comment]
@JounQin I see. Btw, You are a contributor to various Open Source and have made many contributions to eslint-plugin-prettier. If we give you GitHub and npm permissions, can you maintain it? (I am not familiar with eslint-plugin-prettier, so I thought you would be better suited than I)

**Comment by JounQin** [comment]
@sosukesuzuki I'd be happy and pleasure to help to maintain that project.

**Comment by sosukesuzuki** [comment]
@JounQin We can close this?

**Comment by JounQin** [comment]
> @JounQin We can close this?

After a npm release, I'll close this one.
