### ISSUE TITLE
Intersection of types with IndexSignatures aren't formated nicely

### ISSUE THREAD

**Issue by RebeccaStevens** [prettier/prettier#11371]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYhCAHgBUBGAGm2ICYA+bAXmwCEBDAJ0IB0pttgefPgG0A0tgCWvANZw0EAGZVSAXSTYAzjHZSA5gG5B2AL7YAZPyMjxU7LPlKaa7FACuAWwBGcdod4meWn0QchAIDBgJaA1kUA52CAB3AAUOBBiUVgAbRNY0GNDPdlYwWRgAZQwSvWRtVzhQuC84ABMW1oAZVihdV1ZdOHx2d1YYSJ7kEFZXGAgQkAALGHcsgHUFiXgNKrA4cvTNiQA3TbRJsA0CkCkNHxhk4t0R5AVs29CAKw0AD2Zi0rgFVY7jgHSkcBebwaIC+33KeiycAAiq4IPBIVl3iAquxbuxJugsBowDoIvMMDpYKsJC0YAtkAAOAAMoQpEFuq2KGEmFLgeKOENCAEdUfAHuEMlMNABaKBwVqtebsOAiiTKh79Z5IV6Y6G3dwSWrseqhDQI5GiiHaqGhGCsTzU2n0pDUW3FCRZPQAYQg7i1ID5AFZ5q5bsR7RkdVijvUAJJQdqwcokiQRACCCfK6ERGNuxmMQA)

**Input:**

```ts
type Foo<T1, T2> = Bar<
  {
    [K in keyof T1]: string;
  } & {
    [K in keyof T2]: number;
  }
>;
```

**Output:**

```ts
type Foo<T1, T2> = Bar<
  {
    [K in keyof T1]: string;
  } &
    {
      [K in keyof T2]: number;
    }
>;

```

**Expected behavior:**

The input text should be the correct format. [This would be consistent with types that don't have IndexSignatures](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYhCAHgBUBGAGm2ICYA+bAXmwCEBDAJ0IB0pttgefPqyTYAzjHYBLKAHMA3IOwBfbADJ+SvgCNRUAK4BbbXHaLeKnrXkhyICBhhToY5KA7sIAdwAKHBK4orAA2Xqxornba7KxgANZwMADKGLEyssiS+nB2cMZwACYFhQAyrHL6rLJw+OyGrDBOcsggrPowELYgABYwhsEA6t1S8GKpYHBJASNSAG4jaC1gYpEgMmKmMD4xsvXIAGYhG3YAVmIAHswx8YlJrIZwJTJwB0c5IGfnSenBcACK+gg8FewWOIFS7A27Ba6CwYjA0kcXQw0lgAykBRg3WQAA4AAx2FEQDYDGIYFoouBQ2YvOwAR0B8G2DkCrTEAFooHBCoUuuw4AypPztlU9khDqD3htDFJMuxsnYxD9-oyXuK3nYYKxtOjMdikNRNTEpMF0gBhCCGMUgKkAVi6+g2xG1gQlYNm2QAklBirAkgipI4AII+pLoX4gjbKZRAA).

**Comment by sosukesuzuki** [comment]
Thank you for reporting. It'a a not IndexSignature, It's a MappedType. Also, your issue is duplicated with #11181 and already fixed by #11247
