### ISSUE TITLE
Single Line Comments

### ISSUE THREAD

**Issue by Stamimail** [prettier/prettier#11370]
Issue forwarded from: https://github.com/prettier/prettier-vscode/issues/2146#issue-974912414
> 
> 
> https://www.w3schools.com/js/js_comments.asp
> I want to use single line comments at the end of each line to explain the code,
> but sometimes after saving, prettier change the location of the comment from the end of the line and move it down to a new line.
> It's unwanted behaviour.
> 
> Is there an option to fix this behaviour?

**Comment by alexander-akait** [comment]
Please use the issue template

**Comment by Stamimail** [comment]
I won't waste my time on that. Do whatever you want. Have a good life.

**Comment by alexander-akait** [comment]
I do not understand what the problem is to show understanding and respect time of other developers

**Comment by Stamimail** [comment]
You got my respect. Sorry if I can not respond to your request for lack of time.
