### ISSUE TITLE
running prettier with --list-different flag never errors out

### ISSUE THREAD

**Issue by vaziliybober** [prettier/prettier#11389]
Quote from the docs: "Another useful flag is --list-different (or -l) which prints the filenames of files that are different from Prettier formatting. If there are differences the script errors out, which is useful in a CI scenario".

But in fact the script does not error out when there are differences. If that behavior is intended, it should probably be reflected in the docs. If that is a bug, it should be fixed. Or maybe i'm doing it wrong? And thank you for building and maintaining prettier! It is such an amazing formatting tool :)

**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: Node.js
- Runtime: Node.js v16.4.2
- Operating System: Linux 
- Prettier plugins (if any): None

**Steps to reproduce:**
Create a src folder in your root directory with a js file inside (prettier should be installed, of course)
Inside that js file write any js code that breaks your prettier rules (for example it might use the wrong quotes)
From your root directory run "npx prettier --list-different src"

**Expected behavior:**
We get an error because some prettier rules inside src directory are broken
**Actual behavior:**
We only get the list of the files in which some rules are broken, but no error occurs

**Comment by thorn0** [comment]
This works as intended. "The script errors out" means that it completes with a non-zero exit code:
```console
$ npx prettier --list-different .
foo.ts
$ echo $?
1
```
