### ISSUE TITLE
[HTML Templating] Prettier close previous <tr> on save, even with in-line ignore

### ISSUE THREAD

**Issue by sharky98** [prettier/prettier#11393]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeGBDARgGzgAjBwwGcSBeAHRE1wNrwFoSYAnASwAc4ATfBuIwAWEAG5xW+DDnYBzKIwC27HjzzV8LAJ54qIAO4qYQpPgCMABgsBSagD5KUfM-zohcDDwdOXvt3YBhCBwAQVQAemNvXz8ooJwAIQioxz9I909ol3QsCB4tLJj8YGt8ADMISXZ4RXx2J2q4RRJ8awBfVKLXNkKu53QvYGA6moA6SFD8Nrbkr06+yhhUAEJGRnxOVjgYGHYJRjkoSoI13r6S8srNAFcsRtr6kaaSUZJb+5b2+a7FlbWNrY7PasA7yY74U7fc6ldhlfBHGCXVg4CAQTijMrsVgsVodHx9fqrdabba7faHcGQ-EE9CsM5dP7EwFkkEUrYQxj0ooXBA8WG4qEMmCDYZvO5jCYJKYzSJzanQ-C8iqSL7y7KROmC5w8qA8ZUC6nJXL5bzJbB4OwgAA0IDRu2gJGQoAwrFYEH0AAUXQhHShpPoMFpHTasKwMGAANbbADKnHD9VkyDY1zgNqaWF4PF4ABkMFBZNcMLI4AAxSqKDBA-PIEAYa4wCDWkBCGCKHAAdSEjRIcbAcGjPuq7FE1S0NbAZCb9RIEhgHrDsgryDK0hnNoAViQAB4JMORmMYRRwbP1ODL1epkCbrfRhN4ACK1wg8HPODXIDj2IkNZbbabm3qGB2yMIRkAADgsG1NggGd2zDTgaxJGdWHEJsAEcn3gec0V9WsSEYKA4F4Xgmy2DCsTgeciyXJAVzfS8Z2UJNWBTG0SDvOBH2fM9aIvG02AwdgZHzIJFBokA4BIABWJtrhnAAVbBfWTS9RBTABJXUEBgaMwA4TgYBCXVoxgHQeLo99aGAnhjGQAAWaYgA)

```sh
--parser html
--tab-width 4
--use-tabs
```

I am trying to do a conditionnal opening of a table row (`<tr>`) base on my template (Django) values. This is a edge case for formatting, but somewhat regular things in templating (at least, for my projects).

The HTML code below is incomplete (still missing the rowspan and colspan that will be used), but the issue I ran into is about the fact that Prettier will auto-close the *previous* `<tr>` tag even though I `prettier-ignore` it everywhere.

Even though having a fully supported HTML Templating support would be nice, I am able to workaround most of the issue with `<!-- prettier-ignore -->`. Except this one my workaround is to ignore the whole file altogether.

**Input:**

```html
<table class="table table-striped table-hover align-middle" style="width: 100%">
    <thead>
        <th>ColA</th>
        <th>ColB</th>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.colA }}</td>
          	<!-- prettier-ignore -->
            {% for subitem in items.subitems %}
          	<!-- prettier-ignore -->
            {% if not forloop.first %}
            <!-- prettier-ignore -->
            <tr>
            <!-- prettier-ignore -->
            {% endif %}
            <td>{{ subitem.colB }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
```

**Output:**

```html
<table class="table table-striped table-hover align-middle" style="width: 100%">
	<thead>
		<th>ColA</th>
		<th>ColB</th>
	</thead>
	<tbody>
		{% for item in items %}
		<tr>
			<td>{{ item.colA }}</td>
			<!-- prettier-ignore -->
			{% for subitem in items.subitems %}
			<!-- prettier-ignore -->
			{% if not forloop.first %}
			<!-- prettier-ignore -->
		</tr>

		<tr>
			<!-- prettier-ignore -->
			{% endif %}
			<td>{{ subitem.colB }}</td>
			{% endfor %}
		</tr>
		{% endfor %}
	</tbody>
</table>

```

**Expected behavior:**
Prettier should not auto-close previous `<tr>` tag when a `<!-- prettier-ignore -->` is found.

**Comment by alexander-akait** [comment]
We don't support Django templates

**Comment by sharky98** [comment]
Maybe I wasn't clear, but I don't expect you supporting Django Template, but I would expect the `<!-- prettier-ignore -->` tag to be reconized to not close a previous tag when opening a new one. A bit like this `<!-- prettier-ignore -->` works like a charm for the more complexe Django templates tags; ignoring them and leaving the template alone.

**Comment by fisker** [comment]
We don't support Django templates
