### ISSUE TITLE
Formatter add double space at the end of the class declaration (before bracket)

### ISSUE THREAD

**Issue by root-10** [prettier/prettier#11405]
When use the prettier works very well, it's my favorite, no doubt, but I found that the double space between declaration and bracket is annoying because the style doesn't apply.

**Before :**
.my-style { margin: auto };
p { font-size: 2rem };

(*** Formatting ***)

**After:**

_The output_
.my-style  { // Here double space between ".my-style" and "{"
   margin: auto
};
p  { // Here double space between "p" and "{"
   font-size: 2rem
};

_What I expect_
.my-style { // Only one space between ".my-style" and "{"
   margin: auto
};
p { // Only one space between "p" and "{"
   font-size: 2rem
};

Note: I expect one space between ".my-style" or "p" and bracket "{" because the example in the output sometimes does'nt apply the style and that's what happening actually.
PS: I'm not sure how the double space adds, not sure about the rule because sometimes when use the formatter this adds one space and sometimes double space.

Thank you!

**Comment by thorn0** [comment]
Please use [the playground](https://prettier.io/playground/) to reproduce your issue.
