### ISSUE TITLE
No possibility for plugins to support range formatting

### ISSUE THREAD

**Issue by dummdidumm** [prettier/prettier#11404]
I'm maintaining `prettier-plugin-svelte` and want to add support for formatting ranges. After digging into the source code of Prettier, I came to the conclusion that this is impossible right now. `calculateRange` uses [findNodeAtOffset](https://github.com/prettier/prettier/blob/main/src/main/range-util.js#L75) to find the node at the starting/ending position. The function ultimately ends up calling the passed in function [predicate](https://github.com/prettier/prettier/blob/main/src/main/range-util.js#L79), which is handed in [here](https://github.com/prettier/prettier/blob/main/src/main/range-util.js#L208) and calls the function [isSourceElement](https://github.com/prettier/prettier/blob/main/src/main/range-util.js#L161) which I have no possibility to hook into. This means that `isSourceElement` will always return false in the end, making the search for the node at offset fail.

I'd like to have a possibility to hook into this, either by enhancing `isSourceElement` with something like 
```javascript
// ... switch case
if (opts.isSourceElement) {
  return opts.isSourceElement(node);
}
return false
```

Or rethink the plugin architecture at this code position, because it's a little weird that I have to implement `canAttachComment` because `findNodeAtOffset` uses `comments.getSortedChildNodes` .

**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: CLI
- Runtime: Node.js v14
- Operating System: Windows
- Prettier plugins (if any): prettier-plugin-svelte

**Comment by sosukesuzuki** [comment]
Thank you for reporting this issue. I'll close this because this is duplicated to #7639.
