### ISSUE TITLE
Conditional bracket formatting causes runtime errors

### ISSUE THREAD

**Issue by Forbidden-Duck** [prettier/prettier#11407]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUEARgFYDy1AyjNQDT4cAZ3ZsAlPmAAdKPkGp8DBsNGt8AMnX4YATwAOcCApYduvfAEIAvFfxSQJuNnv4APq+37Dxtpx7UAOgA3AEMSdDhLGzsQIV4cKABzewl3SxM-XglpWTltAAtqCAB3fAAVLwBRaiLqBnsAOQh8UPDIhPwMs2oUgG4ZOQBfAfxIKCEIEjgA8kTlETZ8AH5O327gsIj8JFXTfzEZQZA+Bz1caCFkUBCakoAFG4RLlDDikJ1Lk+ZqELAAazgMC4el+CUSyF4EROcAAtsw4HQ6AiADIhJLoEKJOAAMRoMJCMFwSWQIBC6BgEGOIHyMBhJAo+Rw8CEILAcC4TyZOCCTJ0JLAQk+IASQjg1Bgdx+iXxyFQYVFJ1YQgAHgAhH7-QFcEIwuDIhJwWXyuCKlVcMFTACK6Ag8CNJAVIBB1FF1BJzBC8JIVL01ASMAoODoMHyyAAHAAGE6+iCiig-PQk31wV1BQ0nACONvgkogemepKEAFooHAEQiqdQ4FmcFXJZiZUg5Q6TbFYTgIdQobELXBrbbDU3jScYJ7A8HQ0gAEwjn44EhggDCEBhjZAKYArFT0KKyp7ns3HUEIgBJKBI2BcMB+s4AQXPPB0U3tosGgyAA)

```sh
--parser babel
```

**Input:**

```jsx
function HelloWorld(objOrStr, isObj) {
  if ((isObj && typeof objOrStr !== "object" || typeof objOrStr.value !== "string") || !objOrStr) {
    throw TypeError("No value in objOrStr");
  }
  console.log(isObj ? objOrStr.value : objOrStr)
}
```

**Output:**

```jsx
function HelloWorld(objOrStr, isObj) {
  if (
    (isObj && typeof objOrStr !== "object") ||
    typeof objOrStr.value !== "string" ||
    !objOrStr
  ) {
    throw TypeError("No value in objOrStr");
  }
  console.log(isObj ? objOrStr.value : objOrStr);
}

```

**Expected behavior:**
I expected it to leave the bracket wrapped around `isObj` instead, moving the bracket will cause a runtime error if objOrStr is a string because of `objOrStr.value`

**Comment by sosukesuzuki** [comment]
Sorry I'm not sure what you expect behavior. Can you show code example your expect?

**Comment by Forbidden-Duck** [comment]
```js
function HelloWorld(objOrStr, isObj) {
  if (
    (isObj && typeof objOrStr !== "object" ||
    typeof objOrStr.value !== "string") || // <-- End of bracket to be where I originally put it
    !objOrStr
  ) {
    throw TypeError("No value in objOrStr");
  }
  console.log(isObj ? objOrStr.value : objOrStr);
}
```

**Comment by Forbidden-Duck** [comment]
Also to my knowledge, there isn't a way to disable prettier formatting brackets in conditional statements

**Comment by thorn0** [comment]
> The statement is supposed to be
> 
> > If `isObj` is true then check that `objOrStr` is not `typeof object` or `objOrStr.value` is not `typeof string`
> > Or check if `objOrStr` is not a truthy value

That's not how JS works. Your expression doesn't do what you've described here.
`(a && b || c) || d` and `(a && b) || c || d` are equivalent expressions. Prettier hasn't changed what the code does.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
