### ISSUE TITLE
Extra spaces in html tagged templates

### ISSUE THREAD

**Issue by zizifn** [prettier/prettier#11402]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAbAhgIzm0wF5MALGAW2wAMAefAVxhmkzDzTRIB0QAZrgBuEAE4BLeJjQATeQsVLZMAJ7Y4s-ryiY9+vWoAOcPiGato-AHw6DAQXmY2mIaMnw0O+gHoLbKGtaAG4dEAAaEAgjGAl0ZFBcMTEIAHcABSSENGQQEQgJWQjzMVwwAGs4GABlIzKJKABzZBgxJjhIuCpCeU0AGVwmplxGuAAxcSpcVgbmlFwWCGLKGgB1cik4NDqwOGrsqQlhKVVcsG5ihrQ4MRh00sap5CFsa8iAKzQADwAhUoqqtVcFQ4H0GnBnrhXh0QJ8vtVZhoAIpMCDwSHQyJ1MTXMS5fAEIjFIySWCrQowcjIAAcAAYsSlrqtSkZciStjdhBDIgBHVHwe7RHLzNAAWigcE0mmKYjgfIksvuIyeSBebxA1yoEhabRhaERcBRaIhqqh6pgBHJKipSAATJFWrgJNhZgBhCBUFUgKDQbkgJjXAAqBGFaphwnaAEkoLIEDUwJIYvYY9U1BoMdcAL6ZoA)

```sh
--parser babel
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```jsx
const label = html`<button class="favorite sddddddddddddddddtyled"
        type="button">
    Add to favorites
</button>`;

```

**Output:**

```jsx
const label = html`<button
  class="favorite sddddddddddddddddtyled"
  type="button"
>
  Add to favorites
</button>`;

```

**Expected behavior:**

```jsx
const label = html`<button
  class="favorite sddddddddddddddddtyled"
  type="button">
  Add to favorites
</button>`;

**Comment by sosukesuzuki** [comment]
What is your expected behavior?

**Comment by zizifn** [comment]
@sosukesuzuki sorry, forgot attach the expected behavior, please check the update.

**Comment by sosukesuzuki** [comment]
Tagged Template Literal HTML is formatted just like normal HTML. And normal HTML is formatted as follows. So this behavior is not a bug.

```html
// Input
<button
  class="favorite sddddddddddddddddtyled"
  type="button"
>
  Add to favorites
</button>

// Output
<button
  class="favorite sddddddddddddddddtyled"
  type="button"
>
  Add to favorites
</button>
```

However, you will can control this behavior since 2.4 by new `--bracket-same-line` option(Added in #11006). Please wait new minor release.
