### ISSUE TITLE
array access then assignment

### ISSUE THREAD

**Issue by brigand** [prettier/prettier#1141]
In (with no config):

```js
elements[0].innerHTML = '<div></div><div></div><div></div><div></div><div></div><div></div>';
```

Out:

```js
elements[
  0
].innerHTML = "<div></div><div></div><div></div><div></div><div></div><div></div>";
```

Expected:

```js
elements[0]
  .innerHTML = "<div></div><div></div><div></div><div></div><div></div><div></div>"
```

**Comment by vjeux** [comment]
I'm curious, what do you think of

```js
elements[0].innerHTML =
  '<div></div><div></div><div></div><div></div><div></div><div></div>';
```

**Comment by brigand** [comment]
That's also fine, as long as it doesn't spread the 3 characters across three lines :-)

Might be more consistent with method calls to move the `.` to a new line.

**Comment by vjeux** [comment]
Just sent #1142 for it. Thanks!

**Comment by bakkot** [comment]
#1142 is definitely an improvement, but I think the issue is more general than that:

```js
elements[0].aReallyLongLine012345678901234567890123456789012345678901234567890123456789
```

becomes

```js
elements[
  0
].aReallyLongLine012345678901234567890123456789012345678901234567890123456789;
```

whereas I'd want it to become

```js
elements[0]
  .aReallyLongLine012345678901234567890123456789012345678901234567890123456789;
```

**Comment by vjeux** [comment]
@bakkot #1142 also fixes your example by the way.

It generates

```
group(
  group(
    elements[
    group(
      0
    )
    ]
  )
  .aReallyLongLine012345678901234567890123456789012345678901234567890123456789
)
```

so it first breaks before `.` and then if it still doesn't fit inside of `[]`

**Comment by vjeux** [comment]
Oh I'm sorry, I got mixed up in the issues. https://github.com/prettier/prettier/pull/1036 fixes the problem you mention.
