### ISSUE TITLE
Online playground not loading

### ISSUE THREAD

**Issue by mikjakrych** [prettier/prettier#11428]
Hi team,

What a wonderful product! Just a heads up that in one of the latest pull requests (possibly #11006) the online playground at [prettier.io](https://prettier.io/playground/) no longer loads at all.

![image](https://user-images.githubusercontent.com/32045115/131519471-793022f4-7463-4c50-8754-029a29e2c3ee.png)

**Comment by kachkaev** [comment]
Interestingly, the playground still works for the most recently merged PR (`main` branch):
https://deploy-preview-11044--prettier.netlify.app/playground/

**Comment by nakulnagariy** [comment]
same for me.

![image](https://user-images.githubusercontent.com/26174424/131798561-f0fa85f3-0e3d-4ce2-a3de-89bcd2e643dd.png)

**Comment by sosukesuzuki** [comment]
Oh sorry I'll try to fix it.

**Comment by sosukesuzuki** [comment]
Now, https://prettier.io/playground is working fine. Please check.

**Comment by kachkaev** [comment]
Thanks @sosukesuzuki – it works! I had to deep-refresh the page for it to load though – looks like some assets are aggressively cached, but their URLs don’t change based on content.
