### ISSUE TITLE
json accuracy problem

### ISSUE THREAD

**Issue by wchbrad** [prettier/prettier#11430]
I'm sorry to ask a question here, because https://prettier.io/playground is currently not available.
   I am using json formatting in chrome, but found a loss of precision problem. The configuration is as follows.
   Prettier 2.3.2
   chrome: 92.0.4515.159
   Code used:
`import prettier from "prettier/standalone";
import parserBabel from "prettier/parser-babel";

prettier.format(
  `{
    "a":122222222222222222222222,
    "b":2.000000000000
    }`,
  {
    parser: "json",
    plugins: [parserBabel],
  }
)`
Expected result:
{
  "a": 122222222222222222222222,
  "b": 2.000000000000
}
Actual results:
{
  "a": 122222222222222222222222,
  "b": 2.0
}
The accuracy of b is lost. Could this be a bug?

**Comment by kachkaev** [comment]
Yeah the playground is currently down, the issue is tracked in #11428. You should be able to find a temporary link there (from a recent PR).

What do you mean by ‘accuracy of b is lost’? `2.000000000000 === 2.0` in JavaScript.

**Comment by wchbrad** [comment]
Yes, I thought that prettier's json parser would only adjust the json format without modifying the content. I expect to retain the complete number `2.000000000000`. Maybe I should first convert `2.000000000000` into a string to display? Many thanks.

**Comment by kachkaev** [comment]
From the data point of view numbers like `2.000000000000`, `2.0` and [even `2.0E0`](https://en.wikipedia.org/wiki/Scientific_notation#E_notation) are identical. When you read the JSON, the details of the notation you’ve picked will be lost. If you do want to distinguish between `2.0` and `2.000`, you need to store your data points as strings instead.

**Comment by wchbrad** [comment]
It seems I can only do this, thanks for your answers
