### ISSUE TITLE
Babel-TS can't format JSON

### ISSUE THREAD

**Issue by Xenfo** [prettier/prettier#11432]
**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: CLI
- Runtime: Node.JS v16.8.0
- Operating System: Linux
- Prettier plugins (if any): `@trivago/prettier-plugin-sort-imports` (happens with and without)

**Steps to reproduce:**

Options:
```js
module.exports = {
  parser: 'babel-ts',
  semi: true,
  singleQuote: true,
  bracketSpacing: true,
  trailingComma: 'none',
  importOrder: ['^[./]'],
  importOrderSeparation: true,
  experimentalBabelParserPluginsList: ['typescript'],
  plugins: [require.resolve('@trivago/prettier-plugin-sort-imports')]
};
```
JSON File:
```json
{
  "version": "0.0.1",
  "license": "MIT"
}
```
Command:
```sh
prettier --write package.json
```

**Expected behavior:**
Prettier to complete successfully.

**Actual behavior:**
I get an error. This seems to be a problem with `babel-ts` as when I remove it, I can format JSON.
```
package.json
[error] package.json: SyntaxError: Unexpected token, expected ";" (2:12)
[error]   1 | {
[error] > 2 |   "version": "0.0.1",
[error]     |            ^
[error]   3 |   "license": "MIT"
[error]   4 | }
```

**Comment by sosukesuzuki** [comment]
This is not a bug. `babel-ts` cannot parse JSON text. Please use `json` parser for parsing JSON.

**Comment by Xenfo** [comment]
Thanks that worked!
