### ISSUE TITLE
proposal: enhanced no-semi

### ISSUE THREAD

**Issue by rattrayalex** [prettier/prettier#1143]
It's a bit of a bummer to insert `;` at the start of every potentially-problematic line, rather than only when it's actually needed. This is important, though, because if a user introduces an ASI failure, prettier will highlight that error in an ugly (albeit helpful) way. 

eg; 

```js
foo
[1, 2, 3].forEach(bar)
```
will be transformed into
```js
foo[(1, 2, 3)].forEach(bar)
```

even once https://github.com/prettier/prettier/pull/1129 goes through. 

I have a somewhat radical proposal to fix this, so that prettier does "what you want, not what you say" when it comes to ASI:

1) use a forked parser that incorporates the ASI fixes in the [LightScript](http://lightscript.org) parser (or similar). 
2) only insert the prepended `;` when preceded by an ExpressionStatement. 

Obviously, this would be an option – "super-no-semi" – or a fork (if someone decides to take this up). 

The example above would instead be transformed to:
```js
foo
;[1, 2, 3].forEach(bar)
```
since it would be parsed as two separate statements rather than a MemberExpression.

This proposal would help coders using the "no-semi" option really *never* have to think about semicolons, and prevent frustration.

**Comment by vjeux** [comment]
I'm very anxious around using a non standard JavaScript parser in prettier. I'm afraid that people are going to feed it code that will change meaning this different ASI implementation.

**Comment by rattrayalex** [comment]
I definitely agree with your anxiety – I don't think I would recommend this proposal be adopted, though somebody might want to make a fork with this functionality.

I'm not sure what you mean by 

> that will change meaning this different ASI implementation

?

**Comment by lydell** [comment]
> It's a bit of a bummer to insert `;` at the start of every potentially-problematic line

Why? In semi-colon free code I've worked on, semicolon-at-start-of-line has been _extremely_ rare. And in many cases where I've typed them, I ended up with not needing them after all before comitting. For example:

```js
;['mouseenter', 'mousemove', 'mouseleave'].forEach(eventName => {...})
```

→

```js
const MOUSE_EVENTS = ['mouseenter', 'mousemove', 'mouseleave']

MOUSE_EVENTS.forEach(eventName => {...})
```

I don't see this as a problem.

But that's just me.

**Comment by rattrayalex** [comment]
It's definitely theoretical, not something I've encountered – so maybe it'll be fine. But... 

> I ended up with not needing them after all before committing

The problem that I'm worried about is that, when using `prettier`, it reformats your code as you type (assuming you save frequently, and have it wired to format on save). So it may distort code before you "save yourself" from it, for example by rewriting 

```js
blah
['mouseenter', 'mousemove', 'mouseleave'].forEach(eventName => {...})
```

to 
```js
blah[('mouseenter', 'mousemove', 'mouseleave')]
  .forEach(eventName => {...})
```
or whatever, before you get the chance to rewrite it to `const MOUSE_EVENTS = ['mouseenter', 'mousemove', 'mouseleave']`. 

That said, I'm similarly hopeful that this won't come up that often, so I'll just close for now. Wanted to get the idea out there.
