### ISSUE TITLE
How to import Prettier's html tag for template literals in TypeScript?

### ISSUE THREAD

**Issue by archfisv** [prettier/prettier#11431]
**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: Node.js/TypeScript
- Runtime: Node.js v16.5.0, TypeScript v4.2.4
- Operating System: Windows
- Prettier plugins (if any): prettier-tslint

**Steps to reproduce:**

I have a .ts file with tagged template literal (`html` tag as described here: https://prettier.io/blog/2020/08/24/2.1.0.html#api ), like this:

```typescript
const myFunction = (arg) => {
  return html`<p>
    hello ${arg}!
  </p>`;
}
```

**Expected behavior:**

Correct formatting without any errors.

**Actual behavior:**

Prettier formats the code correctly, but unfortunately after compilation it complains: `ReferenceError: html is not defined`.

Should I import anything or my configuration is missing something?

**Comment by alexander-akait** [comment]
Bug on your application side, there is not `html` templated tag in your env

**Comment by archfisv** [comment]
Does prettier provide such function?

**Comment by alexander-akait** [comment]
No, we are formatter, not library

**Comment by archfisv** [comment]
Thanks
