### ISSUE TITLE
Adds trailing comma after last argument to a function call

### ISSUE THREAD

**Issue by juanmaia** [prettier/prettier#1145]
```
"eslint": "^3.19.0",
"eslint-config-airbnb": "^14.1.0",
"eslint-plugin-import": "^2.2.0",
"eslint-plugin-jsx-a11y": "^4.0.0",
"eslint-plugin-react": "^6.10.3",
"prettier": "^0.22.0",
```

If I have this:
```
someFunction(arg1, 'Large Error message that will add a trailing comma when breaking the line a lil');
```
And hit save, it becomes:
```
someFunction(
  arg1,
  'Large Error message that will add a trailing comma when breaking the line a lil',
);
```

The trailing comma is causing an `SyntaxError: Unexpected token )` error.

**Comment by juanmaia** [comment]
I would love to help fix this btw.

**Comment by vjeux** [comment]
You want to use the option `--trailing-comma es5`. If you do `--trailing-comma all` then it's going to add `,` for function calls which is now part of the spec but not implemented widely yet.

**Comment by juanmaia** [comment]
Thanks for clarification @vjeux

**Comment by ffxsam** [comment]
@vjeux Question on this:

If I use `--trailing-comma es5`, what does that mean exactly? Because trailing commas are then _not_ being used in ES5. But my ES6 code doesn't get trailing commas either.. so it looks like trailing commas are effectively disabled.

**Comment by k15a** [comment]
@ffxsam Objects and Arrays should get trailing commas with the es5 option.

```js
const array = [
  1,
  2,
  3,
]

const object = {
  foo: 'foo',
  bar: 'bar',
}
```

**Comment by ffxsam** [comment]
Ah, I must've done something wrong. I see it working now. Thanks!
