### ISSUE TITLE
Change the default value for `trailingComma` to `"all"` in v3

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#11465]
Trailing commas in function syntax was introduced in ES2017, it's supported since Node.js 8.2.1, modern browsers supports it too.

I think it's time to change `trailingComma` to `"all"`.

**Comment by sosukesuzuki** [comment]
:+1:

**Comment by alexander-akait** [comment]
Agree

**Comment by kachkaev** [comment]
`"trailingComma": "all"` is the only option in [my shared prettier config](https://github.com/kachkaev/routine-npm-packages/blob/02d91fa00501a3d0bc9a9c8ee5390e220a1b18e3/packages/prettier-config/index.js#L2), so a big 👍 from me too 😁

**Comment by nickmccurdy** [comment]
Support for Internet Explorer, the only browser lacking an update for modern trailing comma support, is ending next week.

**Comment by fisker** [comment]
Fixed in #11479
