### ISSUE TITLE
example glob pattern uses symbols not explained in node-glob

### ISSUE THREAD

**Issue by Pomax** [prettier/prettier#1147]
The example CLI prettier command is:
```
prettier --single-quote --trailing-comma es5 --write "{app,__{tests,mocks}__}/**/*.js"
```
but this uses curly braces in the glob pattern, which are not mentioned in https://github.com/isaacs/node-glob#glob-primer so... what do they do, and where is that described? =)

**Comment by SimenB** [comment]
It's standard glob pattern. You can read about it i.e. here: http://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm

**Comment by lydell** [comment]
The curly braces _are_ documented in the "glob primer" you linked to :)

> Before parsing the path part patterns, braced sections are expanded into a set. Braced sections start with `{` and end with `}`, with any number of comma-delimited sections within. Braced sections may contain slash characters, so `a{/b/c,bcd}` would expand into `a/b/c` and `abcd`.

**Comment by Pomax** [comment]
As a windows user, I have no idea where to look for standard linux documentation ^_^;

@lydell hah, clearly I am completely blind!
