### ISSUE TITLE
[scss] Wildcard syntax in `@forward` broken

### ISSUE THREAD

**Issue by Michsior14** [prettier/prettier#11482]
Using the latest prettier wildcard syntax is broken when using `@forward` pattern.
It worked as desired in v2.3.2.

**Prettier 2.4.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZhATgdwIZYAmABAOQB0A9AA54wAWpxeAzsbQwLQBUA3ADpQM2fETJVIAG2xNWxKdh4ChmXARIVKcSXAC2CGLLba9BpYJAAaEBGowAltBbJQBLBBwAFAgmco8kvgAns7WAEZYeGAA1nAwAMp4+gAy9lBwyOgBLHDhkTFx8bRgaQDmyDBYAK65IHphcISEjcl4UKVVeKVwAGLYunQO7cggeFUwEFYg9DC6kgDq9PbwLMVw8b7L9gBuy0EjYCyhIGk5WDCekaUDmdm1AFYsAB7xZToAilUQ8LeSOda0LBnEYsQ7HahYNIweb2QgMZAADgADAD3Dl5pFqCMIXAztsMtYAI5feCXWx+UYsTjpRqNKZYODE+wMy5dG5ILJ-Wo5XT2CrVblvOCfb4ZDl3awwPBhGFw+jIABMksi9kkZQAwhBdOy6iwAKxTKo5AAq0r8nP+IG2NQAklBmrB4mBIXYAIL2+IwII6X45AC+fqAA)

```sh
--parser scss
```

**Input:**

```scss
@forward './path' as path-*;
@forward './color' as color-*;
@forward './element' as element-*;

```

**Output:**

```scss
@forward "./path" as path- *;
@forward "./color" as color- *;
@forward "./element" as element- *;

```

**Expected behavior:**

Wildcard syntax should be preserved.

```scss
@forward "./path" as path-*;
@forward "./color" as color-*;
@forward "./element" as element-*;

```

**Comment by alexander-akait** [comment]
Regression, thanks

**Comment by alexander-akait** [comment]
Due https://github.com/prettier/prettier/pull/11461

/cc @ niksy

**Comment by niksy** [comment]
@Michsior14 oh wow, sorry, I didn’t see that single whitespace in snapshot :(

@alexander-akait [PR](https://github.com/prettier/prettier/pull/11487) created!
