### ISSUE TITLE
Prettier infinitely suggests additional " ;" to the end of less detached rulesets

### ISSUE THREAD

**Issue by noahsal** [prettier/prettier#11483]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAbgQwE4EtMBGANnEgATAA6UZZAZrnEQCbkDOEAtnDABa5QA5tQC+AbhAAaEBAAOMXNDbJQObBADuABRwJlKTEQ2YAnsukFsmMAGseAZUzcAMgLjI6htnAtXbD2WsBQWQYbABXHxA4TgI4ZmZ450whcMxBOAAxCGxOTBgFIWQQTHCYCCkQXhhOIgB1fng2QLA4ez1cBXROk2KwNnMQAW9sGC0rQTyPLyiAKzYAD3tgkgBFcIh4aaJvaUDsEeKSAcrZPFg63GY+ZAAOAAY99W86q1lis7gR9HdpAEcNvBxnJ9CU2ABaKBweLxSrYOAA3Dw8bpKZITw7KLeTi4UIRLErODrTbudEzaQwQiXa68ZAAJgpVlwRGCAGEuGjomwAKyVcLeAAqhH0GN2IHQkQAklBErB7GA8PIAIIy+wwEwkbZi+YLABCfjsMEcLjcWrgIhEQA)

```sh
--parser less
```

**Input:**

```less
@variable: {
  field: something;
};
```

**Output:**

```less
@variable: {
  field: something;
}; ;

```

(If you test it out in the playground, another space + semicolon are always added, no matter how many are in the "input")

**Expected behavior:**
I would expect `prettier` to be satisfied with zero or one semicolon, not always suggest another. See [detached rulesets docs](https://lesscss.org/features/#detached-rulesets-feature).

**Comment by mvorisek** [comment]
It seems the problem is in the `postcss` parser - https://github.com/postcss/postcss/issues/1806
