### ISSUE TITLE
Unable to indent by 4 spaces instead of 2

### ISSUE THREAD

**Issue by brianarpie** [prettier/prettier#1150]
Hi, I'm using vanilla vim implementation and prettify on save while saving cursor location is working great. However, my project uses 4 spaces per indentation level rather than 2.

Is there a way I can configure this with the current options ? Thanks

**Comment by lydell** [comment]
` --tab-width 4` should do the trick.

**Comment by brianarpie** [comment]
@lydell thanks! I was passing in --tabWidth (camel cased) hence the confusion.

**Comment by vjeux** [comment]
You probably didn't see it because of the integration but we print a warning on stdout:

![image](https://cloud.githubusercontent.com/assets/197597/24806098/9d27b00a-1b68-11e7-8da8-c7080bc90231.png)
