### ISSUE TITLE
Changing string literals!! (breaking styled) 

### ISSUE THREAD

**Issue by cancerberoSgx** [prettier/prettier#11518]
Before: 
```tsx
import styled from 'styled-components/native';
export const Container = styled.View`
  flexDirection: row;
`;
```

After: 

```tsx
import styled from 'styled-components/native';
export const Container = styled.View`
  flexdirection: row;
`;
```

Notice the change from `flexDirection` to `flexdirection` which actually broke our react-native app. 

It's sounds very wrong to me that a formatter is changing actual string literals ! I hope this is only a "magic feature" for styled since changing literals sounds very very buggy for a formatting tool like this. 

**Expected behavior: Prettier shouldn't change string literals in my code, NEVER.**

**Comment by sosukesuzuki** [comment]
workaround: you can set [embedddedLanguageFormatting](https://prettier.io/docs/en/options.html#embedded-language-formatting) `off`.

**Comment by thorn0** [comment]
@cancerberoSgx  Does styled-components actually allow camelcased property names?

**Comment by cancerberoSgx** [comment]
@thorn0 Thanks, and yes, I know that, although incorrect, in our case (react-native+styled-components) it allows camel case CSS properties so prettier actually broke my app. Thanks for the answer, you may close this issue if you don't think this is an issue. On my side the only suggestion perhaps is to set `"embeddedLanguageFormatting": "off"` by default.

**Comment by alexander-akait** [comment]
@cancerberoSgx Yes, we want to do it for prettier v3

**Comment by alexander-akait** [comment]
Formatting tagged literals were never safe

**Comment by thorn0** [comment]
related https://github.com/prettier/prettier/issues/2897
