### ISSUE TITLE
Incorrect reformatting of types that changes the code

### ISSUE THREAD

**Issue by jfmengels** [prettier/prettier#1151]
In the following example, `foo` has been annotated to be a function that takes a string, and returns a function that takes a string and returns a string, which it is.
```js
// @flow
const foo = (bar: string): (string => string) => {
  return () => bar;
};
```
After reformatting, I get
```js
// @flow
const foo = (bar: string): string =>
  string => {
    return () => bar;
  };
```

The parens around `(string => string)` have been removed, which changes the type annotations and the JS code. Now the function takes a string, then another one before returning a function that takes a string and returns a string (so it added one extra argument to the function).

Another example:
```js
// @flow
const foo = (bar: string): (Array<string> => Array<string>) => {
  return () => bar;
};
// -->
// @flow
const foo = (bar: string): (Array<string>) => Array<string> => {
  return () => bar;
};
```

(Then there is the odd reformatting of chained arrow functions, but that should have been fixed with https://github.com/prettier/prettier/issues/1065 already)

Again, :heart: the project, thanks for all your hard work!

**Comment by vjeux** [comment]
Great catch! Thanks, we need to fix this asap :)

**Comment by vjeux** [comment]
I can't find any other broken cases than just an arrow function being returned.

```js
const f = (): (a | string => string) => {};
const f = (): (a & string => string) => {};
```

outputs

```js
const f = (): a | ((string) => string) => {};
const f = (): a & ((string) => string) => {};
```

so we're already adding the correct parenthesis if the function is nested.

```js
function f(): string => string {}
```

doesn't conflict, so we don't need to fix it.

**Comment by vjeux** [comment]
In the meantime, to get you unblocked, you can add `// prettier-ignore` on the line before or put the return type in a variable.
