### ISSUE TITLE
.stylelintrc fails to pass format check, but no changes suggested

### ISSUE THREAD

**Issue by Th3S4mur41** [prettier/prettier#11520]
**Environments:**

- Prettier Version: 2.4.0
- Running Prettier via: CLI
- Runtime: Node.js v14 & v16
- Operating System: Windows, Linux

**Steps to reproduce:**
Using the following .prettierrc: 
```
{
	"bracketSpacing": true,
	"printWidth": 120,
	"semi": true,
	"singleQuote": true,
	"tabWidth": 2,
	"trailingComma": "none",
	"useTabs": true
}
```

Running `prettier --check --ignore-unknown .`  will return a warning about [.stylelintrc](https://gist.github.com/Th3S4mur41/3cf1ba266c841a29f707f9eeb90b2993) not being properly formatted.
Running `prettier --write --ignore-unknown .` will however not change anything in [.stylelintrc](https://gist.github.com/Th3S4mur41/3cf1ba266c841a29f707f9eeb90b2993)

**Expected behavior:**
Either prettier check should pass or prettier write should fix the style error

**Actual behavior:**
Prettier check and prettier write are not consitent

**Comment by thorn0** [comment]
Can't reproduce using your steps. Yes, `--check` printed a warning, but then `--write` formatted the file, so now `--check` doesn't report anything. Please re-check your steps.

**Comment by Th3S4mur41** [comment]
@thorn0 you're right... 
Seemed to have been a weird glitch on two different repositories.
The problem was fixed after a fresh npm install

**Comment by Methuselah96** [comment]
Had the same thing. Turned out to be a line-ending issue in case anyone else runs into this.
