### ISSUE TITLE
Incorrect report and fix of `export type T = null!`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#11552]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwBU8BePKAVwBt6BCEAGhAgxgEtoBnZKACG2bBADuABREIBKIfXFDCA9gCNsQsAGs4MAMpCAtnAAy3KHGQAzBXzjrNOvfoxaLAc2QxstB6iM1OAATYJDTISgPWiEPOAAxHCMhGB4o5BAhWhgINhAACxgjegB1fO54PjcwOH1ZCu4ANwrCDLA+VRALe1xJTQ9kmzt-ACs+NH1PejgARVoIeCH6e3Y3bB6MohI+MGxuLjyMPdgS7mCYfOQADgAGVbF7Es0MDKO4HsardgBHefg+zhyTJ8AC0lhCITy2Dgv240L6sUGSFsy389iM3G8vjRU1mfysyOG7BgQjUp3OlyQACZiZpuPRPABhCBGJGoPgAVjytHsZFJchRKxAjT8AEkoGFYPpdvsYABBCX6IjTJb2AC+aqAA)

**Input:**

```ts
export type T = null!
```

**Output:**

```ts
export type T = !null
```

**Expected behavior:**

No report

**Comment by sosukesuzuki** [comment]
What does "report" mean?

**Comment by JounQin** [comment]
> What does "report" mean?

Oh, sorry, it's `eslint-plugin-prettier`.

**Comment by sosukesuzuki** [comment]
Thanks, I see. But I don't think current Prettier output is wrong. `null!` and `!null` are both `TSJSDocNonNullableType`. They mean the same thing. Prettier simply puts the `TSJSDocNonNullableType` exclamation-token in front of the term.

**Comment by JounQin** [comment]
@sosukesuzuki See [TS playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCCcC8cCEA7AVwBsiAoIA)

**Comment by sosukesuzuki** [comment]
[TS Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCCcC8cCEA7AVwBsiBuAKFElgWVQCEs5CScKg). line-1 and line-2 has same error `export type A = !null;
export type B = null!;
`.
```ts
export type A = !null;
export type B = null!;

```

**Comment by JounQin** [comment]
Hah, thank you. I think I just misused `export const A = null!` vs `export type A = null!`, and `prettier` reformatted the incorrect again, that made me thought it is caused by formatting.

So `export type T = null!` is an incorrect syntax, I still don't understand why `prettier` try to format the incorrect syntax?

**Comment by sosukesuzuki** [comment]
You are right. `export type T = null!` is incorrect syntax but TypeScript compiler can parse it. it has so loose parser. It can parse a variety of incorrect syntaxes. Prettier uses `@typescript-eslint/typescript-estree` that depends on TypeScript Compiler API for parsing TypeScript code. So Prettier can format incorrect code.

**Comment by sosukesuzuki** [comment]
This issue is not actually a bug and will be closed.
