### ISSUE TITLE
Prettier variables prettier and prettierPlugins undefined in web view

### ISSUE THREAD

**Issue by amruta-jv** [prettier/prettier#11555]
We have a product which is an IDE, this IDE uses ace editor which runs in web view and to beautify these files, we would like to use prettier. After integrating with prettier, it's variables are going undefined in web view of editor. However, in browser same code works. Could you please let me know why this is happening or is there any other way of integrating to make it work in web view. 

**Environments:**

- Prettier Version: 2.4.1
- Running Prettier via:  Browser
- Runtime:  Chrome v83
- Operating System: Linux
- Prettier plugins (if any): 

**Steps to reproduce:**

Intergrate Prettier in a web view. 

**Expected behavior:** Variables prettier and prettierPlugins to be defined.

**Actual behavior:** They are going undefined.

**Comment by sosukesuzuki** [comment]
Can you share the minimal repository to reproduce?

**Comment by amruta-jv** [comment]
@sosukesuzuki It's difficult to share a repository, IDE is in Java and in web view of it, Ace editor is integrated and we want to use  Prettier for formatting.

**Comment by alexander-akait** [comment]
What is error stack trace?

**Comment by amruta-jv** [comment]
@alexander-akait `TypeError: undefined is not an object (evaluating 'prettier.format')
`

**Comment by thorn0** [comment]
> IDE is in Java and in web view of it

So it's not really a browser. Could you tell us more about this environment? Does it happen to support CommonJS or AMD? Prettier's standalone bundle is UMD. If an environment supports CommonJS or AMD, the global variable isn't created. You need to import it as a CommonJS/AMD module in that case.

**Comment by amruta-jv** [comment]
@thorn0 We are using CommonJS way as below: 

`require(['js/standlone'], function(prettier){
			window.prettier = prettier;
		});`

**Comment by thorn0** [comment]
@amruta-jv Were you able to solve this? I'm closing this issue for now as there is no way for us to reproduce it.
