### ISSUE TITLE
nested ternaries not consistent in indentation

### ISSUE THREAD

**Issue by MarkKahn** [prettier/prettier#11576]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjAljNTAXgB0pNMA3AQwBtMAeTABwCc5KyKKB+TAbQAMAXS7ckVOpgB8Ldp3LdemXGgDCEALZs4aNHAAmYpcv4BGUYpOYJ5gDSYRx8SvVadew86V9+l6xS2Zg4WANwgdiAQzDC46Mig1KysEADuAApJCGjIIHSp1ACeOZHYrNRgANZwMADK1JpwADK4UHDIAGZ0+qXlVTW1zBWtAObIMKwArnCRcJrYhgaGTdRQI5PUI3AAYhCsmtQwsWu51JMwEBEgABYwmrQA6tf4ukNgcLXZ+LiU+IW5YD0V1a+lYMHS5RGB063RmIAAVmgAB61Ua0OAARUmEHgMNoPRAQ1YoNy2GoC1oVzYrRgD1wBhg12QAA5BJE2BB9A9ysxch44KxKO1IgBHbHwCHRHIoahoAC0bUMhiu7DFuHYEM20KQXXxcP0mlw4ym+rRmPF7R1sMiMHJdIZTKQACYbeVcLRRhpNNqQLoAKxXSb6AAq5OluoJlGmAEkoEtYLUwKxcDEAIJx2owQrovH6AC+eaAA)

```sh
--parser babel
```

**Input:**

```jsx
const bits =
  val < prev
    ? [0]
    : val > prev
      ? isCompressed
        ? [1]
        : [1, 0]
      : isCompressed
        ? []
        : [1, 1];
```

**Output:**

```jsx
const bits =
  val < prev
    ? [0]
    : val > prev
    ? isCompressed
      ? [1]
      : [1, 0]
    : isCompressed
    ? []
    : [1, 1];

```

**Expected behavior:**

Anything consistent.  My personal preference is the input formatting.

**Comment by sosukesuzuki** [comment]
New formatting for nested ternaries is discussed in #9561. Please see it.
