### ISSUE TITLE
proseWrap: never does not format tables with rows > 80chars

### ISSUE THREAD

**Issue by stefanprobst** [prettier/prettier#11571]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABPAzjdHu6oA6UGAtBXuhWXifnDlTABYCWW6kANgK4C2UdCwCGnAI6828dCPQAjaeggAzTHAAeMAHQLeuJaM7dGnViKEAOAAxdRAJyy7iUeuqYMPbmlR8vPhJjsnDwCQkboktJwsgpKqupauvL66IZisYq4-BD2MeZWtmAOTnggADQgEAAOMGzQWMigIvb2EADuAAotCI0oItztIgCejZXy9iJgANZwMADKIvxwADJsUHDIKgNYcOOTM3Pz1VPrAObIMPa8eyBw-PJwACZPzysWZ7wiZ3AAYrn8EQwOpQC79fQQCogFgwfjcADq7GwJzAcHmvWkbAAbtJhshwFgxiB1rt7DBOpMzoCtjtbgArLAaebnEwARV4EHgNO4u0qJ0ccHs+MB9mmTw6UCh1Xs6xg8LYT1YyBsfLau3hk2q+I2WMFUMknLgFJqfRAYjIG2ezyheSieQp32pSG2PNuu34bEu1zdLLg7MN3N5IBgInk8sVLGQACZKlcRGxuOcAMIQfhOu5YACsUN4uwAKqG+i6g1ibgBJKCvWDzMAy2oAQUr8xgwxMgbgAF8O0A)

```sh
--parser markdown
--prose-wrap never
```

**Input:**

```markdown
| test | test |
| --- | --- |
| test | this column has quite a bit of text. but it has less than 80 chars. |

| test | test |
| --- | --- |
| test | this column has quite a bit of text. but it has a bit more than 80 chars. |
```

**Output:**

```markdown
| test | test                                                                |
| ---- | ------------------------------------------------------------------- |
| test | this column has quite a bit of text. but it has less than 80 chars. |

| test | test |
| --- | --- |
| test | this column has quite a bit of text. but it has a bit more than 80 chars. |

```

**Expected behavior:**

markdown tables with rows longer than 80characters should be formatted correctly when `proseWrap: never` is set.

**Comment by benface** [comment]
Unfortunately, this appears to be by design. Original PR is #5701. You can see the code [here](https://github.com/prettier/prettier/blob/main/src/language-markdown/printer-markdown.js#L585) and the tests [here](https://github.com/prettier/prettier/blob/main/tests/format/markdown/long-table/__snapshots__/jsfmt.spec.js.snap).
