### ISSUE TITLE
Unable to use prettier with autosave over network drive

### ISSUE THREAD

**Issue by caldwelljt2** [prettier/prettier#11596]
- VS Code Version:  1.60.2
- OS Version: Windows 10 (latest updates)

Steps to Reproduce:

1. Disabled all extensions except prettier
2. Set Auto-save on with 1 second timeout
3. open code on a network drive
4. make changes
5. undo changes
6. wait for timeout - or - click another window
7. unable to redo

I have tried every combination of settings for:
1. "formatonsave": true/false
2.  "prettier.enable": true/false,
3.   "files.restoreUndoStack": true/false

With the below settings redo works as expected on C: drive but not on mapped T: drive:

{
  "workbench.iconTheme": "material-icon-theme",
  "tabnine.experimentalAutoImports": true,
  "[javascript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "editor.fontFamily": "'Cascadia Code', Consolas, 'Courier New', monospace",
  "editor.fontSize": 10,
  "window.zoomLevel": 1,
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "liveServer.settings.donotShowInfoMsg": true,
  "liveServer.settings.CustomBrowser": "chrome",
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "wrap_attributes": "force-expand-multiline"
    },
    "prettyhtml": {
      "printWidth": 100,
      "singleQuote": false,
      "wrapAttributes": false,
      "sortAttributes": false
    }
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "eslint.format.enable": true,
  "vetur.validation.template": false,
  "vetur.validation.script": false,
  "vetur.validation.style": false,
  "vscode-edge-devtools.mirrorEdits": true,
  "files.autoSave": "afterDelay",
  "files.restoreUndoStack": true,
  "editor.codeActionsOnSave": null,
  "prettier.enableDebugLogs": true,
  "prettier.enable": false,
  "editor.formatOnSave": false
}

**Comment by caldwelljt2** [comment]
just want to reiterate that i've confirmed this is an issue only with prettier, not with the native formatter and only when i use vscode on folders located on a network share.

My temporary solution is to copy data to a local drive, edit there, and then both copy it back to the network drive as well as checking it in to github.

**Comment by thorn0** [comment]
Hi, thanks for the report!

This repository is only concerned with the core formatting tool and not the editor integrations. Unfortunately, there's not much we can do to help you in this case. I suggest you open a report on the extension's issue tracker: https://github.com/prettier/prettier-vscode
