### ISSUE TITLE
Unstable chained call with object

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1162]
```js
Wg.select("body").append("svg").style({position:"absolute",top:0,left:0,margin:0,padding:0,border:"none"},"important");
```

```js
Wg.select("body")
  .append("svg")
  .style(
    {
      position: "absolute",
      top: 0,
      left: 0,
      margin: 0,
      padding: 0,
      border: "none"
    },
    "important"
  );
```

```js
Wg.select("body").append("svg").style(
  {
    position: "absolute",
    top: 0,
    left: 0,
    margin: 0,
    padding: 0,
    border: "none"
  },
  "important"
);
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22Wg.select(%5C%22body%5C%22).append(%5C%22svg%5C%22).style(%7Bposition%3A%5C%22absolute%5C%22%2Ctop%3A0%2Cleft%3A0%2Cmargin%3A0%2Cpadding%3A0%2Cborder%3A%5C%22none%5C%22%7D%2C%5C%22important%5C%22)%3B%5Cn%5CnWg.select(%5C%22body%5C%22)%5Cn%20%20.append(%5C%22svg%5C%22)%5Cn%20%20.style(%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20position%3A%20%5C%22absolute%5C%22%2C%5Cn%20%20%20%20%20%20top%3A%200%2C%5Cn%20%20%20%20%20%20left%3A%200%2C%5Cn%20%20%20%20%20%20margin%3A%200%2C%5Cn%20%20%20%20%20%20padding%3A%200%2C%5Cn%20%20%20%20%20%20border%3A%20%5C%22none%5C%22%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%5C%22important%5C%22%5Cn%20%20)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by frontsideair** [comment]
This doesn't look broken in the latest [playground](https://prettier.io/playground/#%7B%22content%22%3A%22Wg.select(%5C%22body%5C%22).append(%5C%22svg%5C%22).style(%7Bposition%3A%5C%22absolute%5C%22%2Ctop%3A0%2Cleft%3A0%2Cmargin%3A0%2Cpadding%3A0%2Cborder%3A%5C%22none%5C%22%7D%2C%5C%22important%5C%22)%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Atrue%2C%22parser%22%3A%22%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22%22%2C%22useTabs%22%3Afalse%7D%7D).
