### ISSUE TITLE
Weird wrapping for SCSS @use rules

### ISSUE THREAD

**Issue by GrimLink** [prettier/prettier#11635]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABArgZzgAgDpoBmAngDYDmAVgIYD0ARtdgTgO4CWMAFjgBR5QcQnABJC1ALbtSxALQTq7KEj4Dh6nACV09dgGsANGo1DNEehBgQjgkzkzFM8CbPTsbd+9SiZZ2AE7shB7CAJQhQmLQMLKscOzkXDAqAMwArAAMEaJcAIyyhNGx8YnJOJlZxpFcAEwFRXEJSSoV2SJcKfWwxU1lFQKhANwgBiAQAA4w7NCYyKDU-v4QrAAKCwizKNSkrNSOIyD0-tRgenAwAMqScAAySnDI4qTYo0cnZ5fjJ0rkyDD+6DgozgEnocAAJuCITdvOR0NRyHAAGIQfwKGBTKC-LboKwHJISUgAdS4nDgmC+YDgFw2nHYADdOMRkOBMLNRkoAjAVsdyApHtsXiBKJgAB4XH6kOAARXQlgeSCeQq+-gCLMwYDZB3GgVgRPY4O4yAAHFkQDqINgicdxiydeS4P56Q9RgBHOXwHkTTYgJiyKBwCEQg7+ODu9ihnkI-mKwVAkDYKR-AHxzCSmUehVK+Mwaj0fWGrjIGqjf6KUg-ADCEAkMZA5LSBywcAAKnnNtnRvTAQBJKBQ2AXMCBSYAQX7FxgZCzcYAvrOgA)

Not sure which version this was introduced.
Previously this did not happen.

But the current SCSS syntax using `@use` gets wrapped in a weird way.
The opening parentheses is wrapped with a indent, and also all of  the code inside it.

**Input:**

```scss
@use "@fylgja/base" with (
    $family-main: (
        Rubik,
        Roboto,
        system-ui,
        sans-serif,
    ),
    $font-weight: 350,
    $h1-font-weight: 500,
    $h2-font-weight: 500,
    $h3-font-weight: 500
);
```

**Output:**

```scss
@use "@fylgja/base" with
  (
    $family-main: (
      Rubik,
      Roboto,
      system-ui,
      sans-serif,
    ),
    $font-weight: 350,
    $h1-font-weight: 500,
    $h2-font-weight: 500,
    $h3-font-weight: 500
  );
```

**Expected behavior:**

```scss
@use "@fylgja/base" with (
    $family-main: (
        Rubik,
        Roboto,
        system-ui,
        sans-serif,
    ),
    $font-weight: 350,
    $h1-font-weight: 500,
    $h2-font-weight: 500,
    $h3-font-weight: 500
);
```

**Comment by alexander-akait** [comment]
hm, both looks good...

**Comment by GrimLink** [comment]
I think the indent should not be there @alexander-akait 
But it is also inconsistent with the SCSS map wrapping which does not wrap the opening parentheses to the next line
