### ISSUE TITLE
Prettier incorrectly formats html in Vue templates

### ISSUE THREAD

**Issue by Mikilll94** [prettier/prettier#11631]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQVmoYCeAtJNtAjGQG50CWAZgLzEgAhDgh4AJpygBzAWUgiATvxAAjHAFc4ssPgDOu5RgV0ALAMK6IGOGXgAPGKgD0tBlazNYJKM8y4CcN6kqLpgCpxYMN44cKwACgqxMJxwCmS8ZNwQChgE6YRkwGQ0EOoKAHQAVroAFADkMAAWpVKNdQCUZAC+wU6h4ZFBProwNDHe5XhQYoVy+ki2EBBkgpxMCjBTrD0+faPjIAA0IBCRnNC6yKB4CgoQAO5xNwiXKHg493g0l8cqCnhgADWsQAynhrAAZSRwZDcd66OC-f5A0FYAGSKTIGAKTTHOAYFRwMRiIkQqZSdR4KRwABi2VyMGS0mQIDw6hgECOIEaMAwOAA6o1OPBdGiwHAQS9hZw2MKaCywPouZIERsElTcrD4YiQNU7CCMTEAIrqCDwLU4BHHNEKVUstiaLlYcKwfmcMRNZAADgADNa7gj+f8sCznXBVWwYccAI6m+AJU6vVm6OhQOBEolcxKxziJdVSTVIOGWnUIjCcLE40uGuAms0wova46bFRuj2NZAAJmb-04OAxAGErIWQOGAKxc9QIgAqeBUr2LVpADrgAElpiwQWEIjAAILTEH7BuLuBdLpAA)

```sh
--parser vue
```

**Input:**

```vue
<template>
    <my-component v-if="!loading" color="blue" class="mr-4">some text</my-component>
</template>

<script>
let Prettier = format => { your.js('though') }
</script>

<style>
.and { css: too !important }
</style>
```

**Output:**

```vue
<template>
  <my-component v-if="!loading" color="blue" class="mr-4"
    >some text</my-component
  >
</template>

<script>
let Prettier = (format) => {
  your.js("though");
};
</script>

<style>
.and {
  css: too !important;
}
</style>
```

**Expected behavior:**
Prettier incorrectly formats html in Vue templates. The endings of the tags are messed up.

The desired output should be:
```vue
<template>
  <my-component v-if="!loading" color="blue" class="mr-4">
    some text
  </my-component>
</template>

<script>
let Prettier = (format) => {
  your.js("though");
};
</script>

<style>
.and {
  css: too !important;
}
</style>
```

**Comment by sosukesuzuki** [comment]
Thanks for the report! Probably it is intended. Why Prettier format

```html
<my-component v-if="!loading" color="blue" class="mr-4">some text</my-component>
```

to

```html
<my-component v-if="!loading" color="blue" class="mr-4"
    >some text</my-component
  >
```

is consistent whitespaces rendering. You can use [HTML Whitespace Sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option to control this. Please see [the blog post](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) for details.

Also you can get expected format result from the below input:

**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQVmoYCeAtJNtAjGQG50CWAZgLzEgAhDgh4AJpygBzAWUgiATvxAAjHAFc4ssPgDOu5RgV0ALAJLlKFXRAxwy8AB4xSV1AHpaDW1mawLHpi4BHAWpKi6YAqcWDAWOHCsAAoKiTCccApkvGTcEAoYBNmEZMBkNBDqCgB0AFa6ABQA5DAAFpVSrU0AlGQAvuHukdGxYVARMDQJFtV4UGKlcvpIDhAQZIKcTAowc6wD40OT0yAANCAQsZzQusigeAoKEADuSQ8Ityh4OM94NLfnFQKPBgADWiQAyng7AAZSRwZDcb66OCA4FgyFYEGSKTIGAKTTnOAYFRwMRiMkwuZSdR4KRwABi+UKMHS0mQIDw6hgEDOIFaMAwOAA6q1OPBdFiwHAIR9xZw2OKaBywPo+ZIUTsUnTCojkaiQPVHBCcQkAIrqCDwPU4FHnLEKTUctiaPlYaKwYWcMRtZAADgADPanijhcCsBz3XBNWwEecAI6W+ApS6fTm6OhQOBksl81KJzipbVSXVIJG2g0ojCcPEEyumuAWq0Isv6867FRen2tZAAJnbwM4OBxAGFbKWQNGAKx89QogAqeBUn3LdpALrgAEl5iwIVEYjAAILzCHHFuruB9PpAA)

```sh
--parser vue
```

**Input:**

```vue
<template>
    <my-component v-if="!loading" color="blue" class="mr-4">
      some text
    </my-component>
</template>

<script>
let Prettier = format => { your.js('though') }
</script>

<style>
.and { css: too !important }
</style>
```

**Output:**

```vue
<template>
  <my-component v-if="!loading" color="blue" class="mr-4">
    some text
  </my-component>
</template>

<script>
let Prettier = (format) => {
  your.js("though");
};
</script>

<style>
.and {
  css: too !important;
}
</style>

```
