### ISSUE TITLE
[Flow] Don't indent single function param with multiline type annotation

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#1164]
Using [0.22.0](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20X%20%3D%20(props%3A%20%7B%5Cn%20%20a%3A%20boolean%2C%5Cn%7D)%20%3D%3E%5Cn%20%20%3CA%20%2F%3E%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D)
```es6
const X = (props: {
  a: boolean,
}) =>
  <A />;

// is formatted to

const X = (
  props: {
    a: boolean,
  },
) => <A />;
```
It would be great if we kept the param inline, the same way we do for single param destructing.

**Comment by vjeux** [comment]
Sounds like a good idea!

**Comment by vjeux** [comment]
I just sent https://github.com/prettier/prettier/pull/1173 for it. But I'm not convinced that this is always an improvement.
