### ISSUE TITLE
Keep blank line between imports.

### ISSUE THREAD

**Issue by SohelIslamImran** [prettier/prettier#11640]
I'm using prettier with eslint.
**Is there any way to keep blank or empty line between imports?**
Like this :

```
import React from "react";
import { ThemeProvider } from "styled-components";

// provider
import { Provider as ProfileProvider } from "./src/context/ProfileContext";

// component
import AppSplash from "./src/components/ui/AppSplash";

// navigation
import Navigation from "./src/navigation";

// styles
import { theme } from "./src/theme";
```

Currently, prettier formatting it to : 

```
import React from "react";
import { ThemeProvider } from "styled-components";
// provider
import { Provider as ProfileProvider } from "./src/context/ProfileContext";
// component
import AppSplash from "./src/components/ui/AppSplash";
// navigation
import Navigation from "./src/navigation";
// styles
import { theme } from "./src/theme";
```

**Comment by alexander-akait** [comment]
Something wrong with eslint setup, prettier keep newlinew between [imports](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwB0QdTyGBuOqDbPfYfAFQAWcdHAAK1AG6oAJnBz4Avvio16IAM4wAngBs4MgLSQs0BDA1sOHAPQ38mKbPkcuuAnwkRpchSQ34XhSo+l4+8koq1LQMAHQ2GjhgNpCwcAAeMDZBIXAAwtDwmVZQtvYm2FDmrqY8AIKYmADKmLr+glFqcQlJKTSV5ho2AK6oNg3Nre0lZfhQJNIA5iQwqNA13AQAcguoy6vQnTEg8YnJ80sra6Ug7KVQdvhaenCWnLUe+DDCopGqx6det8RHA2CAADQgCCYA5QDTIUAkHDUADuYiRCHhKBIuhRJG08MhACMcGQANZwGBNEiiAAyqCqyAoOI0cGJpLAFKpmDIDMWyBgOGGbJAIiJBjkMlpJCgi2GJEWcAAYrh0CtVrLkCASMMYBAISBBDB0LoAOqCVDwDQ8sBwJqYy2oaQ6LVgDSEtBw+QwCQKtVMlkigBWGnSTT5+gAisMIPAA7pWZCeThWTgtUSSOLdAbHAyYKbZN9kAAOAAMSeorNNpMwWscr3kkjgBoAjjH4F5MFjtRpDFUDAYDUw26gmL7Fv6kMyEyLWehUAKhbOI3Bo7Hm1PA5CYJmCzIi0gAEzb0khPkFdCT0UaACsBuGrP4max08TIEkwoAklA5LAmmAcFQGE6h-JodH0eNWUURQgA)
