### ISSUE TITLE
placement of function return type comments with flow

### ISSUE THREAD

**Issue by montemishkin** [prettier/prettier#1166]
Hey all, 
Thanks for working on this awesome project!
I'm noticing some unexpected behavior with regards to comment placement in multi-line function declarations when using flow type annotations.  Check out the link below.

See here: https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20f(%5Cn%20%20a%3A%20number%2C%5Cn%2F%2F%20some%20comment%20here%5Cn)%3A%20number%20%7B%5Cn%20%20return%20a%20%2B%201%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D

### Input
```js
function f(
  a: number,
// some comment here
): number {
  return a + 1;
}
```

### Actual Output
```js
function f(
  a: number
)// some comment here
: number {
  return a + 1;
}
```

### Expected Output
Of course this could just be my personal preference, but I'd expect the output to look closer to this:
```js
function f(
  a: number
// some comment here
): number {
  return a + 1;
}
```
It's not the end of the world to me if the comment must be put where prettier is currently placing it, but it does feel out of place.

### Why am I even putting a comment there?
Well, in my case I'm putting a `$FlowFixMe`, but in general I could see making a comment about the return type or something of that nature.  Also, just for context, the reason that the `): number {` is on its own line in the input code is because in my real use case, the arguments list is longer and the return type is long as well.

#### Side note
While we are on the topic of how comments get moved, I'm wondering what kind of guarantees `prettier` can (and cant) make to the user about comments staying next to the code it was initially intended to refer to.  This is of course important for keeping the comments relevant, but I'm also now thinking about comments that have "meaning" to third party libraries like flow or eslint (`$FlowFixMe`,  `eslint-disable`, etc.)  I couldn't find a section in the README about this.  Is there any mention of it that I accidentally overlooked?

**Comment by vjeux** [comment]
Thanks for the report, this is indeed not great and needs to be fixed.

For the guarantees prettier makes around comments, this is a complicated subject. There are two big constraints:

1) Comments can be added anywhere between two tokens. In prettier, we chose to attach every comment to an AST node, either before or after. So there are times where we have to make a choice and cannot print it exactly where it was before.

2) Prettier doesn't have the notion of on which line things will be printed up-front. Based on a line-width, it can break into multiple lines.

In most cases, we're able to do a good job at maintaining correctness as people write comments in sensible places, but we can't guarantee that we're going to maintain it all the time.

**Comment by vjeux** [comment]
Here's the fix for your particular issue: https://github.com/prettier/prettier/pull/1176

Please don't hesitate to report other issues you see with comments!

**Comment by montemishkin** [comment]
Thanks for the quick fix and explanation @vjeux, you rock!
