### ISSUE TITLE
Prettier removes trailing comma of generic arrow function in Markdown tsx codeblock

### ISSUE THREAD

**Issue by rothsandro** [prettier/prettier#11684]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdACGBnAHgHSkimxizlIwF4MAeAFQBoA+ACgDcBDAGwFc4kGegEpqzDMAC+AbkLpUhEIxAQADjACW0bMlCcATvogB3AAoGEOlD2OcAnjuUAjfZzABrODADKnALZwADIaUHDIAGY82HDOrh5e3qpuIQDmyDD6-Mpwfk5wACb5BYGcUCm8nClwAGIQ+n6cMJplyCCcvDAQSiAAFjB+3ADqPRrw2ElgcN6Woxrso3atYNiOICHR+jCmrikNEVExIABWeN6p3HAAirwQ8Pvc0cpJ+hutDfru+SZQ3ar6ITBBhp8jAesgABwABieRmig1cqlafwocH07DCygAjjd4Ns1FY2tgALShAoFbr6ODYjSU7aVPZISIPQ7RPwadKZFnnK44sKMg7KGCcJxAkFgpAAJkFrg03FSAGEIH4GSAKABWbq8aL0YVWJmPEDsfgASSgRVg3jA-3UAEEzd4YHYLvdopJJEA)

```sh
--parser markdown
```

**Input:**

````markdown
``` tsx
const test = <T,>(value: T) => {};
```

````

**Output:**

````markdown
```tsx
const test = <T>(value: T) => {};
```

````

**Expected behavior:**
Prettier should not remove the trailing comma because this results in invalid code. Expected output is:

````markdown
```tsx
const test = <T,>(value: T) => {};
```

````

Prettier handles trailing commas correctly in `.tsx` files. It does it by checking if the file name ends with `.tsx`. As this is false in markdown files (`.md` instead) it removes the comma. See https://github.com/prettier/prettier/blob/main/src/language-js/print/type-parameters.js#L54-L64

**Comment by m93a** [comment]
This is still an issue inside Svelte components. Not sure if its a problem with Prettier or Svelte though.

**Comment by kachkaev** [comment]
@m93a please open a new issue if you think it’s a bug 🙂
