### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by TarunavBA** [prettier/prettier#11698]
Would like support for python code.

**Comment by kachkaev** [comment]
There exists https://github.com/prettier/plugin-python, but the repo is archived and it’s maintainers recommend using [Black](https://github.com/psf/black) instead.

Please use one of the [issue templates](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE) when creating Prettier issues.

**Comment by TarunavBA** [comment]
> There exists https://github.com/prettier/plugin-python, but the repo is archived and it’s maintainers recommend using [Black](https://github.com/psf/black) instead.
> 
> Please use one of the [issue templates](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE) when creating Prettier issues. General questions are answered [on StackOverflow](https://stackoverflow.com/questions/ask?tags=prettier).

But still would like if `prettier` would support python. 😢

**Comment by sosukesuzuki** [comment]
We won't implement Python support as the core of Prettier. But, as @kachkaev said, you can implement it as a plugin. See https://prettier.io/docs/en/plugins.html for details.
