### ISSUE TITLE
Feature request: disable/customize empty lines rule.

### ISSUE THREAD

**Issue by JosepAlacid** [prettier/prettier#11715]
No sample here.

Even someone despotically posted **_"we're not going to allow this"_** or **_"no, no options"_** as an answer to another like feature request on the past, and even prettier is a **very strong opinionated** formatter, it would be a good option to allow the user customize or when or not use rules on empty lines.

For this kind of tool "opinionated" should deal on how to apply rules, but never force all users to an "all or nothing" decision. It will be as useful as it is for those delighted with strict rules so keeping them enabled is always an option. Maybe another formatter will appear as much "opinionated" but no so "interventionist " and all us, freedom lovers, will stop posting this request. 😉

**Comment by JosepAlacid** [comment]
> Prettier is not a kitchen-sink code formatter that attempts to print your code in any way you wish.
Exceptional answer.

**Comment by alexander-akait** [comment]
I think we can close it
