### ISSUE TITLE
How to preserve forward-slashes?

### ISSUE THREAD

**Issue by gogo9th** [prettier/prettier#11739]
Hi,

I have the following code (test.js):

`("<\/script>");`

And I run the following command:

`$ node_modules/prettier/bin-prettier.js test.js`

Then, the output is as follows:

`("</script>");`

However, I need the following output:

`("<\/script>");`

. . . because I will use the formatted code inside a <script> tag of a webpage. If I have the "</script>" string inside a script tag's body, the HTML parser recognizes it as the end of the script tag and raises an error. Therefore, I need to preserve the forward slash. Is there a way to do this?

**Comment by alexander-akait** [comment]
We don't support your templates you can write own plugin for this

**Comment by fisker** [comment]
We can preserve it if it's in html

**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wB8AOlAARmRToQA2cAdLRAOYAUxaxxA9JrgRIgAlAG5SFVH2z4iIADQgIBHNHTJQAQyxYIAdwAK2hOpSbaezQE91igEZZNYANZwYAZU0BbOABkcUHDIAGbm6HD2ji5u7nhOASzIMFgArhEgcF52cAAmObm+mlAsKZoscABiEFhemjAwCcggmikwEAogABYwXrQA6p048OhxYHDuJkM4AG5DVk1g6LYgAeFYMAaOLLUhYekAVugAHu4J9ACKKRDwu7ThinFYa03dvR14uLB9ODkwncgADgADA9dOE+o48E0PnA1tMgooAI5XeCbZSmZroAC0gVyuQ6WDgyJwhM2ZR2SFCd3S4S8OCSqRpZzgl2uQUpe0UME0dm+v3+SAATFzHDhaAkAMIQLwUjLoACsHRS4QAKjzTFT7iBpmkAJJQfKwdwyAgAQQN7hgVnot3CAF87UA)

```sh
--parser html
```

**Input:**

```html
<script>
  console.log("<\/script>");
  </script>
```

**Output:**

```html
<script>
  console.log("<\/script>");
</script>

```


As a workaround, you can use `unescape('%3C/script%3E')` or `'<' + '/script>'` instead.

**Comment by gogo9th** [comment]
Thanks very much for your suggestions!

**Comment by fisker** [comment]
Or maybe you can update your script to replace `</script>` when you build your html.
