### ISSUE TITLE
Unnecessary semicolon

### ISSUE THREAD

**Issue by liweiook** [prettier/prettier#11738]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**
![image](https://user-images.githubusercontent.com/42706756/139645333-09fa99a4-6e83-421b-82aa-31052def0827.png)

```jsx

```

**Output:**
![image](https://user-images.githubusercontent.com/42706756/139645574-974223a7-cfd6-4993-b334-e19b547559f8.png)

```jsx

```

**Expected behavior:**

**Comment by fisker** [comment]
This works as intended. See prettier.io/docs/en/rationale.html#semicolons
