### ISSUE TITLE
Formatting bug on `+=`,`-=`,`*=`,`/=` and `%=`

### ISSUE THREAD

**Issue by bolan9999** [prettier/prettier#11746]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAKgLzoBQBGA1AIwCUA3CADQgQAOMAltAM7KioBOXEA7gAVuCdilQAbPqgCe7WgS6owAazgwAyqgC2cADJMocZADMJrOPMUq16+koMBzZDC4BXCyDhaCcACa+-XVQoB1dUBzgAMQguLVQYZhDkNFcYCBoQAAsYLXEAdUymeFY7MDh1ESKmADci6WSwVjkQA3MuGAFFBziTMw8AK1YAD3VHcTgARVcIeF7xc1o7LjbkglQfcQz6LgMYPKZfGEzkAA4ABkXeczzFemTtuDbqo1oAR2n4ToZRNFYAWkMfj8GS4cHeTFBnXCPSQpnmHnMWiYzjcCLGkw+RlhfVoMHW+0OxyQACZcYomOJHABhCBaGGeVgAVgyrnMABV1qI4QsQNV3ABJKABWDqMA7RgAQSF6hg0nGc3MAF9FUA)

```sh
--parser babel
```

**Input:**

```jsx
a *= (b+1);
```

**Output:**

```jsx
a *= b + 1;

```

**Expected behavior:**

```
a *= (b + 1);
```

**Comment by alexander-akait** [comment]
Expected, we don't want to change output

**Comment by bolan9999** [comment]
？？？？

**Comment by bolan9999** [comment]
A u kidding me?

**Comment by sosukesuzuki** [comment]
@bolan9999 Thanks for your issue. I agree with @alexander-akait. Can you tell me why you expect to keep parentheses?

**Comment by bolan9999** [comment]
@sosukesuzuki  @alexander-akait  Sorry, my default.  [React-native-reanimated](https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/api/useSharedValue) caused my issue. 
I tried to do like this:
```
const a=useSharedValue(1);
const b=useSharedValue(2);
a.value *= (b.value + 1);
```
I can not get my result for a long time before I notice that prettier remove the parentheses.

Actually SharedValue updates asynchronously on two different thread, sometimes I can get my result but sometimes not. 

I thought it's prettier's bug.
