### ISSUE TITLE
Prettier `--check` doesn't fail when a file includes lines with trailing whitespace

### ISSUE THREAD

**Issue by glen-84** [prettier/prettier#11748]
**Environments:**

- Prettier Version: 2.4.1
- Running Prettier via: CLI
- Runtime: Node.js v14
- Operating System: Windows
- Prettier plugins (if any): n/a

**Steps to reproduce:**

1. Add a TypeScript file that includes lines with trailing whitespace.
2. Run `npx prettier --check src/**/*.ts`

**Expected behavior:**

A file including lines with trailing whitespace should fail the check, as Prettier will remove trailing whitespace when writing the file, so the file is not correctly formatted.

**Actual behavior:**

```
Checking formatting...
All matched files use Prettier code style!
```

**Comment by alexander-akait** [comment]
Please provide reproducible example

**Comment by glen-84** [comment]
Apologies, I just realised that this was happening because the trailing whitespace was inside a template literal.
