### ISSUE TITLE
SyntaxError: Deleting local variable in strict mode.

### ISSUE THREAD

**Issue by JasonBarnabe** [prettier/prettier#11749]
**Environments:**

- Prettier Version: 2.4.1
- Running Prettier via: CLI
- Runtime: node 12.22.7
- Operating System: Linux
- Prettier plugins (if any): None

**Steps to reproduce:**

```
 echo "function foo() { var bar = 1; delete bar; }" | yarn -s prettier --stdin-filepath script.js
```

**Expected behavior:**

A nicely formatted output of my function.

**Actual behavior:**

```
[error] script.js: SyntaxError: Deleting local variable in strict mode. (1:31)
[error] > 1 | function foo() { var bar = 1; delete bar; }
[error]     |                               ^
[error]   2 |
```

Not sure if there's an option to disable reading my script as one with strict mode enabled? The scripts I'm prettifying are user-supplied and are not guaranteed to use strict mode.

**Comment by fisker** [comment]
Seems like a bug in the defaut parser, you can use other parsers as workaround for now.

```bash
echo "function foo() { var bar = 1; delete bar; }" | prettier --stdin-filepath script.js --parser=espree
```

```bash
echo "function foo() { var bar = 1; delete bar; }" | prettier --stdin-filepath script.js --parser=meriyah
```
