### ISSUE TITLE
Method invocation on a parenthesized expression [bug?]

### ISSUE THREAD

**Issue by guy-kdm** [prettier/prettier#1175]
[By design?](https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20seeHere()%7B%20%20%20%20%5Cn%5Ctvar%20confirmationMessage%20%3D%20T(%5C%22unsaved%20draft%20alert%5C%22)%20%20%20%20%5Cn%5Ct(e%20%7C%7C%20window.event).returnValue%20%3D%20confirmationMessage%3B%20%5Cn%5Ctreturn%20confirmationMessage%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D)

**Comment by lydell** [comment]
Looks like you forgot a semicolon on line 2 and prettier just helped you find that mistake :)
