### ISSUE TITLE
Update postcss-scss

### ISSUE THREAD

**Issue by nex3** [prettier/prettier#11796]
Filing a tracking issue at @vjeux's request for updating `postcss-scss`. It's currently pinned to 2.1.1 when the most recent version at time of writing is 4.0.2. This updated version contains bug fixes that would be useful to have in Prettier, such as https://github.com/postcss/postcss-scss/pull/133.

**Comment by fisker** [comment]
It's already updated in next branch #9583

**Comment by nex3** [comment]
Oh rad!
