### ISSUE TITLE
Exporting default async function get wraps in parens

### ISSUE THREAD

**Issue by thejameskyle** [prettier/prettier#1181]
```js
export default async function foo() {}
```

```js
export default (async function foo() {});
```

**Comment by thejameskyle** [comment]
https://github.com/babel/babel/issues/5622

**Comment by existentialism** [comment]
Should be fixed via https://github.com/prettier/prettier/pull/1047 (ref: https://github.com/prettier/prettier/issues/700)

**Comment by thejameskyle** [comment]
lol, I guess I was re-following the same path: https://github.com/babel/babel/issues/5622#issuecomment-293083028
