### ISSUE TITLE
Prettier can't know if placeholder content is safe to switch from single/double quotes in styled-components CSS

### ISSUE THREAD

**Issue by dinofx** [prettier/prettier#11814]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcYBPAGzgBN8AzHCdfAcmPKoFpItoEZCmA3AB0oIyFGL5IAV1g4SAOQCG6OPgC8+ISADCAF-j5KTAJIA3CKhxxtw0VHGSAYmSUBzAIJRKOiLJjyGkSkFJQAdJSoZgAGIvj4YTiohADWJABKcDS46EowSEhKNPA4+MBx8VLQ8LBIWiAAJMAycooqcAC+thVdUPFhUBCZ2Ti5+YXFcKXlfZXiNfn1+obG5pbW3bO9-YRFcMM5eQVFJWUV8fO8ddo6SlBKlEqb8b0iItF2InAAHth4RlklNIyAQXO4vD4-K07CAADQgCCYGCoaCEZCgJQ4egAdwACpiEGiUEoyNilCQ0fCAEY4JRgFJwGAAZXaABlUFA4MgaCTCHBqbT6YymZg6Ry3MgAtJ+SA4OgqVRKFRWXc3NJ3HAnIcYMioBLidIYBA4SAABYwdBkADqptQ8EIorAcCZhLtUTtJGQ4EIlLQEimMFxtLcuW5vJlACtCN8meKKABFaQQeBhsh8+GinB8nBeqlKBVkE2YJKwK2oSgwU3IAAcAAYM-Q+VbaZgvcW4NmzFz4QBHJPwIOIokgJSEdicqhUE3WPtWOBB9yhpA8tMyvnoVCSnDS+GEONwRPJrlIKUymD5ssVqtIABM8ICSlQZHFvnQS9lhAArCbpHyACr5kSK7piAZjSiY3i8EyYBJEiEJMiEx7AZ0HRAA)

```sh
--parser babel
--single-quote
```

**Input:**

```jsx
import styled from 'styled-components';

const countryName = "Côte d'Ivoire";

const FlagAndCountry = styled.div`
  .riskyReformat::after {
    content: "${countryName}";
  }
  .noReformat::after {
    content: "Côte d'Ivoire";
  }
  .safeReformat::after {
    content: "Canada";
  }


`;

export default FlagAndCountry;

```

**Output:**

```jsx
import styled from 'styled-components';

const countryName = "Côte d'Ivoire";

const FlagAndCountry = styled.div`
  .riskyReformat::after {
    content: '${countryName}';
  }
  .noReformat::after {
    content: "Côte d'Ivoire";
  }
  .safeReformat::after {
    content: 'Canada';
  }
`;

export default FlagAndCountry;

```

**Expected behavior:**

When there is a placeholder expression between a pair of single/double quotes, Prettier does not know if it is safe to switch the type of quotes being used.  In the example above, the "riskyReformat" example results in invalid CSS at runtime (content with single quotes surrounded by single quotes).

**Comment by alexander-akait** [comment]
When you work with string in CSS you should use `CSS.escape(...)` (you potential can create XSS), or avoid using quotes between values.

**Comment by alexander-akait** [comment]
I want to say, it is not bug, it is hint for you

**Comment by alexander-akait** [comment]
No matter how you use CSS - using vanilla JS, `<style>` created in JS, `styled-components` or something else, you should escape input.
