### ISSUE TITLE
HTML with Unicode - SyntaxError: Unexpected character """

### ISSUE THREAD

**Issue by prx-lmo** [prettier/prettier#11822]
**Environments:**

- Prettier Version: 2.4.1
- Running Prettier via: CLI
- Runtime: Node.js
- Operating System: Windows

**Steps to reproduce:**

`<input placeholder="&#8203">`

Playground with my case: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAyzU55VACMIAEwCefAdMEBLKAAcArjHIK6AQzBxKEOqLgAnALxMQAMgDEADgBMABgDMZqYID0IiX1RuOPBiAANCAQCjCy0ADOyKAahoYQAO7EcQjRKBp0iRri0cFChloA1nAwAMoaNHDc8nDIAGaZkXD5hWAl5Qpa8gDmyDCGSi0gcDRCcKIGotwaUD1KGj1wAGIQhjQaMOFzyCAaKhBBINT0AOqUsvCRXdplaZeyAG6X4rtgkXkg8s2GMMSFPQ2DSawwAVpEAB5lXp0OAARSUEHgwLozWCXUMP12JzoRwUhnkMFOslEMEoyGs9nRCWap0KCl2+LgP0edWCAEdEfB-qF0ntIgBaKBwCYTI6GOCc2QS-6LIFIRqo4bNGiyfqDZUw+FcuoKkHBGAaITE0nkpC2A2FWR0Xq4CA0eUjSIAViOSma+CN6UVaJAjyGAEkoAZYGUwASwgBBYNlGDiWEo5oAXyTQA

it also happens this way: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAyzU55VACMIAEwCefAdMEBLKAAcArjHIK6AQzBxKEOqLgAnALxMQAMgDEZqYID0IiX1R2OPBiAA0ICApizoAGdkUA1DQwgAd2IwhGCUDTpIjXFg7yFDLQBrOBgAZQ0aOG55OGQAM0TAuHTMsBz8hS15AHNkGEMlGpA4GiE4UQNRbg0oFqUNFrgAMQhDGg0YfzHkEA0VCC8QanoAdUpZeECm7Ty4w9kAN0PxVbBAtJB5asMYYkyWhYqq7oArQIAHnlWnQ4ABFJQQeDfOjVbxNQwvVY7OhbBSGeQwXayUQwSjIAAcAAZ4RFqrtMgpVui4C9LmVvABHSHwd6+eJrQIAWigcAGAy2hjgzNkQveky+SEqsO61RosnanVlIPBLLKUp+3hgGiE2Nx+KQACYtZlZHRWrgIDRJT1AgBWLZKar4HXxaVwkCXLoASSgBlgeTAGL8AEE-XkYOJQTDqgBfWNAA

**Expected behavior:**
the code gets prettified and no error is thrown
the example line should be printed as-is

**Actual behavior:**
SyntaxError: Unexpected character """
at the last " of _placeholder="&#8203"_

**Comment by fisker** [comment]
Can you report this to [`angular-html-parser`](https://github.com/ikatyang/angular-html-parser)?

You can use `<input placeholder="&#8203;">` as workaround for now.

**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAllADgVxgAiwBsBDMOACwiIBM4AnAXgB0QAyAYgA4AmABgDMAblYA+EABoQELDHTQAzslAl69CAHcACqoRKUJIhpIBPJVIBG9MgGs4MAMokAtnAAymOMgBmhhXEtrMDtHLDJMAHNkGHocAJA4Zws4GjoaNxIoCJwSCLgAMQh6ZxIYOSzkEBI8CEkQChhnIgB1CnR4BTDyBz129AA3dpNKsAVzEEx-ehgtawiSnz94gCsFAA8HSKI4AEUcCHhFon8pMPopyoamuqx6TBhm9BoYCmQuPlP1f2brLErbuBTfpeKQAR328FmMn0VQUAFooHAUik6vQ4OD0GjZrkFkhfMd4v5nOhorFCVtdhCvHillIYCQLI9nq8kDw6dZ0ERIgBhCDOXEJBQAVjqOH8ABUGfp8ScQP04gBJKB0WAOMB3WQAQWVDhgJm2R38AF8jUA)

```sh
--parser html
```

**Input:**

```html
<input placeholder="&#8203;">
```

**Output:**

```html
<input placeholder="&#8203;" />

```

**Comment by prx-lmo** [comment]
i have opened at angular-html-parser an issue see: https://github.com/ikatyang/angular-html-parser/issues/24

**Comment by thorn0** [comment]
Is `&#8203` without `;` valid syntax?

**Comment by fisker** [comment]
Yes, the `;` can be omitted when the following character is not `0-9`（`0-9a-f` for `&#x
...`entries).

**Comment by thorn0** [comment]
Browsers try parsing anything and never complain about syntax. That doesn't mean that anything is valid syntax.
See https://html.spec.whatwg.org/#character-references
"The digits must then be followed by a U+003B SEMICOLON character (;)."

**Comment by fisker** [comment]
I didn't know that, we can close this then.
