### ISSUE TITLE
Support for file lines, e.g. `app/models/user.rb:34`

### ISSUE THREAD

**Issue by dorianmariefr** [prettier/prettier#11832]
**Environments:**

- Prettier Version: 2.4.1
- Running Prettier via: CLI
- Runtime: node v17.0.1
- Operating System: macOS Monterey
- Prettier plugins (if any): `@prettier/plugin-ruby` and `@prettier/plugin-xml`

**Steps to reproduce:**

Have a `spec/support/helpers/login.rb` file for instance:

```
prettier spec/support/helpers/login.rb:29
[error] No files matching the pattern were found: "spec/support/helpers/login.rb:29".
```

**Expected behavior:** Ignores the line number and formats the file

**Actual behavior:** Throws an error

**Comment by alexander-akait** [comment]
Why?

**Comment by dorianmariefr** [comment]
I often do `vim something.rb:34" and then `pw something:34` when I need it formatted (`pw` being `prettier --write`).

I edit file with the line number often because it's in the stacktrace of errors and in the line of rspec errors

I guess I could change `pw` to remove the line numbers

**Comment by alexander-akait** [comment]
I think it is out of scope prettier.... vim on 32 line make sense when you have a error, but what is sense run prettier on only one line?

**Comment by dorianmariefr** [comment]
It would ignore the line number and run on the whole file

**Comment by alexander-akait** [comment]
Just do not write line

**Comment by dorianmariefr** [comment]
Just do not run prettier :D it's just easier, I will just make a `pw`
script that removes the line number

**Comment by fisker** [comment]
I think this is easy to implement, we already have range support. But currently, maybe only work for core plugins? Not sure.

**Comment by dorianmariefr** [comment]
I did a script for this https://github.com/dorianmariefr/pw
