### ISSUE TITLE
Tried it out and it seems to be making my code worse...almost minified

### ISSUE THREAD

**Issue by deltaskelta** [prettier/prettier#1184]
I am not sure if I have done something horribly wrong or not...

before...
![screen shot 2017-04-11 at 5 29 47 pm 2](https://cloud.githubusercontent.com/assets/9424192/24900890/4ab08a10-1ee0-11e7-9ac7-6a09a5138cde.png)

after...
![screen shot 2017-04-11 at 5 30 04 pm 2](https://cloud.githubusercontent.com/assets/9424192/24900902/506c93ea-1ee0-11e7-8146-9449f79406fd.png)

I did `npm install -g prettier` and then I changed my vimrc to have these lines...(with a few of my javascript settings included...

```
let g:jsx_ext_required = 0
au FileType javascript set tabstop=2 shiftwidth=2 expandtab
autocmd FileType javascript.vim,javascript setlocal 
            \formatprg=prettier\ --stdin\ --parser\ flow\ --single-quote\
            \ --trailing-comma\ es5"
```
after it was installed, I ran the command `gggqG`

Is this what the output should look like at this point?

**Comment by hawkrives** [comment]
If you run it in the online Prettier demo, can you replicate it? It's at https://prettier.github.io/prettier. Trying to replicate it with that demo would help us figure out if it's a Prettier issue or a vim integration problem.

**Comment by deltaskelta** [comment]
thanks for taking the time to answer. It works. IDK what happened, but it just started working on every file....weird, thanks

**Comment by hawkrives** [comment]
well, I'm glad it started working for you! good luck.
