### ISSUE TITLE
mdx v2: Should preserve newlines inside jsx

### ISSUE THREAD

**Issue by ferdinandant** [prettier/prettier#11857]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPAWTgGc6BDAczgAoNsIM6BKPYAB0oePNjgwi2EZ250AdGAAW5ADYATcVGEBfYcIA8tBizgA+YaMbXLeW9ca37NqAYD0xpqzMgANCG4KaDpkUEZsLgB3AAVwhBCURlVIxgBPEP8AI2xGMABrCQBlRgBbOAAZcig4ZAIkujgsnPyijFyq5mQYbCJG1BLMuHV1IfLGKGYiUwAxHBLGGAoJ5BBGIhgIPxAlGBLVAHUVeDo2sDhC+PIKADcr1JWwBi2qhtxonOZ52vq+gCs6NCFDqqOAARSIEHg31UDX8bWwrxWJXUaC2nCqMH25HUMCUyAAHAAGOFcBr7HIYFacehwbDXGr+ACOEPg7zkK0YdAAtNUhkMtuJmeRxO8WF8kHUYX0GiVyF0etLgWCWTUJT9-DBGJksTi8UgAEwanJqDoAYQgJXFqDoAFYtkQGgAVLUJSWwkDXXoASSgI1ghTA2HIGBgAEFfYUYKkQdCGjodEA)

```sh
--parser mdx
```

**Input:**

```mdx
export function Message(props) {
  return props.children
}

<Message>
  aaa
  
  aaa
  
  aaa
</Message>
```

**Output:**

```mdx
export function Message(props) {
  return props.children;
}

<Message>aaa aaa aaa</Message>

```

**Expected behavior:**
Newlines inside `<Message>` should be preserved because mdx (as of version 2) now treats them as separate paragraph
blocks. Try it here: https://mdxjs.com/playground/

```mdx
export function Message(props) {
  return props.children
}

<Message>
  aaa
  
  aaa
  
  aaa
</Message>

**Comment by kachkaev** [comment]
I created https://github.com/prettier/prettier/issues/11857 to track MDX 2 support. I am going to close this issue in favour of a more generic one. Hope it’s fine 🤞
