### ISSUE TITLE
mdx files: Using with a plugin, comments are printed with a single slash

### ISSUE THREAD

**Issue by lukeapage** [prettier/prettier#11859]
**Prettier 2.4.1**
Playground link - N/A it does not reproduce in the playground as a plugin is needed

 * **node version** [12.x.x, 14.x.x]: 16.13.0
 * **package manager**: yarn@1
 * **IDE**: Webstorm

**Input:**

```
import Heading from './heading';

export const Text = ({ className, children }) => (
    // use <section> instead of <div> so storybook doesn't style it automatically
    <section className={className}>{children}</section>
);

<Meta title='Heading' component={Heading} />

<Story
    name='Heading'
    parameters={{
        docs: { disable: true },
    }}
    args={{
        type: 'primary',
        size: 'medium',
        isCenter: false,
        children: 'Heading',
    }}
>
    {(args) => <Heading {...args} />}
</Story>

# Heading

Headings...
```

**Output:**

```
import Heading from './heading';

export const Text = ({ className, children }) => (
    / use <section> instead of <div> so storybook doesn't style it automatically
    <section className={className}>{children}</section>
);
...
...
```

**To Reproduce**

```
git clone https://github.com/lukeapage/mdx-prettier-bug.git
cd mdx-prettier-bug
yarn
yarn prettier --write test.mdx
git diff
```

**Expected behavior**

For the slashes in comments not to be removed.

If I remove this plugin, no slashes are removed.

**Investigation**

Originally I raised this on the plugin, but when I add debug console logs after the plugin pre-processes the file, it seems to come out correct with two slashes on comments.

Inside `textToDoc`

![image](https://user-images.githubusercontent.com/309321/143306256-4f9ad493-c95a-4527-86c1-19cd9644e5a8.png)

I see the following console output:

```
textToDoc import Heading from './heading';

export const Text = ({ className, children }) => (
    // use <section> instead of <div> so storybook doesn't style it automatically
    <section className={className}>{children}</section>
);
[
  {
    type: 'CommentLine',
    value: " use <section> instead of <div> so storybook doesn't style it automatically",
    start: 90,
    end: 167,
    loc: Vn {
      start: [Hn],
      end: [Hn],
      filename: undefined,
      identifierName: undefined
    }
  }
]
```
So, the input after pre-processing is ok, and the astComments is correct, but after printing:

```
                            "type": "indent",
                            "contents": [
                              {
                                "type": "line",
                                "soft": true
                              },
                              [
                                [
                                  [
                                    "/ use <section> instead of <div> so storybook doesn't style it automatically",
                                    {
                                      "type": "concat",
                                      "parts": [
                                        {
                                          "type": "line",
                                          "hard": true
                                        },
                                        {
                                          "type": "break-parent"
                                        }
                                      ]
                                    }
                                  ]
                                ],
```

I am not familiar with the prettier codebase and I am struggling to track this down further, but am happy to try fixing if someone can help point me in the right direction...

**Comment by sosukesuzuki** [comment]
Could you use our issue template?

**Comment by lukeapage** [comment]
@sosukesuzuki the template didn’t make a huge amount of sense since this bug is quite specific- I’ve added a lot of information to this bug to make it easy to investigate- a lot more than your template asks for.. you want me to delete info???

**Comment by sosukesuzuki** [comment]
No, however if your info includes the result of [Playground](https://prettier.io/playground), it helps my debugging.

**Comment by lukeapage** [comment]
@sosukesuzuki unfortunately it only happens when you add a plug-in, so the playground example does not work.

I did provide a repo to reproduce instead and I did investigate thinking it was caused by the plug-in, but I believe it is caused because there is a plug-in rather than by the plug-in.

**Comment by sosukesuzuki** [comment]
Okay, thank you.

**Comment by lukeapage** [comment]
Updated to follow template.

I'd love to help but I got stuck in where it is going wrong.

**Comment by lukeapage** [comment]
good news - I tested with prettier 2.5.0 and it is fixed!
