### ISSUE TITLE
GraphQL directives with lists of objects have commas removed, no matter the setting

### ISSUE THREAD

**Issue by TheRobotCarlson** [prettier/prettier#11875]
**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgmSAV1gEkoAzCAJwFsBDGAS2mwAEaIATOAGzbsIwAFgAoqhHnADOSbAG1gdHjwgB3WRkIAjHozAAabBioQAbo25VZdDIwDScNIYhYqDZlBnywVOAziGvnSchoQYnP6G3JLwALoAvoaKymqyAOYmYVKGGRBZsnIAOiDBNIxQxYbFUmFwVFomANZ1xbHOru7QXnI+fvCBfiHYYRH92NFwcfGxAJTYwIVQ2NhqUHUFAMowVOVpsYvLdAR5sAByhDRa69hbO1BpAIRsxoz0VGgOaAfYR0RndDQ4LJbrtFvFFiB9CAXEwushQHQqCZVAAFREIKTIEo8VR0NCYqENI7NGAbAFwAAy5TgyHISikARARLAJI2GCOu2Q20IjLglzgnG4nApdHuhDoaTgADFqPQYEx7liBDAIJCQEIYDQeAB1ISMeBSdlgOAbDH6xjmdBYsBSAkgcoMqgwFFuNL0Wn0xkAKykAA8NrtJABFQgQeAengMqHsqiOrEZGxCACOPDVL1g2oswmQAA4AAzRkwM7VuDBY4zSOqmGlQpOh+AulyYlB0KQAWjWAoFat8dcYvhdEvdSDpkcZDLKXPE48DcBDYZpI89UJgdC0mc42aQACYV25GLp7gBhCA0YcgaQAVjVhAZABU183R1GQKYeWRuLANj5GBgYLgoE4LY0EkCMGXieIgA)

```sh
--parser graphql
```

**Input:**

```graphql
type AccountInformation @model @auth(rules: [{allow: public, provider: apiKey, operations: [create, read, update, delete]}, {allow: groups, groups: ["admin", "superbroker"], operations: [create, read, update, delete]}]) {
  owner: [String]
  accountNumber: String! @primaryKey
  accountName: String
}

```

**Output:**

```graphql
type AccountInformation
  @model
  @auth(
    rules: [
      {
        allow: public
        provider: apiKey
        operations: [create, read, update, delete]
      }
      {
        allow: groups
        groups: ["admin", "superbroker"]
        operations: [create, read, update, delete]
      }
    ]
  ) {
  owner: [String]
  accountNumber: String! @primaryKey
  accountName: String
}

```

**Expected behavior:**
```graphql
type AccountInformation
  @model
  @auth(
    rules: [
      {
        allow: public,
        provider: apiKey,
        operations: [create, read, update, delete]
      },
      {
        allow: groups,
        groups: ["admin", "superbroker"],
        operations: [create, read, update, delete]
      },
    ]
  ) {
  owner: [String]
  accountNumber: String! @primaryKey
  accountName: String
}

```
GraphQL directives with lists of objects have commas removed, no matter the setting. For reference, these directives are from AWS Amplify's graphql [auth directives](https://docs.amplify.aws/cli/graphql/authorization-rules/). Changing comma settings seems to not affect this behavior.

**Comment by sosukesuzuki** [comment]
> Changing comma settings seems to not affect this behavior.

Then why do you expect commas? (I don't use GraphQl, so I don't know what style the community prefers.)
Personally, I prefer no commas version.
