### ISSUE TITLE
Import type modifiers on names break prettier

### ISSUE THREAD

**Issue by lkrugertogetr** [prettier/prettier#11877]
[Typescript 4.5 introduced type modifiers on names](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names). Using these, however, breaks prettier.

**Environments:**

- Prettier Version: 2.5.0
- Running Prettier via: VSCode plugin 
- Runtime: Node 14.x/16.x
- Operating System: Windows, Linux

**Steps to reproduce:**

```typescript
import { type BuildOptions, build } from 'esbuild';
```

Command palette: format document with prettier.

**Expected behavior:**
Formats document
**Actual behavior:**
```
["ERROR" - 11:34:20 AM] Error formatting document.
["ERROR" - 11:34:20 AM] ',' expected. (1:15)
> 1 | import { type BuildOptions } from 'esbuild';
    |               ^
```

**Comment by sosukesuzuki** [comment]
Prettier 2.5 supports type modifiers on name syntax. I think your Prettier version maybe incorrect. Can you reproduce the bug on https://prettier.io/playground?

**Comment by dan-lee** [comment]
I am experiencing the same with WebStorm:

```
$ yarn why prettier
=> Found "prettier@2.5.0"
info Has been hoisted to "prettier"
info Reasons this module exists
   - "workspace-aggregator-d5caa601-b887-43ef-bc44-9e9b61550f6d" depends on it
   - Specified in "devDependencies"
   - Hoisted from "_project_#prettier"
[…]
info Number of shared dependencies: 0
```

It definitely works on the playground, I don't understand how this is happening.

<details>
  <summary>Extended stacktracke from WebStorm</summary>

```
SyntaxError: ',' expected. (2:17)
�[0m �[90m 1 | �[39m�[36mimport�[39m { envelop�[33m,�[39m useSchema } from �[32m'@envelop/core'�[39m�[0m
�[0m�[31m�[1m>�[22m�[39m�[90m 2 | �[39m�[36mimport�[39m {   type �[33mGraphQLSchema�[39m } from �[32m'graphql'�[39m�[0m
�[0m �[90m   | �[39m                �[31m�[1m^�[22m�[39m�[0m
    at e (/…/node_modules/prettier/parser-typescript.js:1:322)
    at Object.parse (/…/node_modules/prettier/parser-typescript.js:1:3072720)
    at Object.parse (/…/node_modules/prettier/index.js:13625:19)
    at coreFormat (/…/node_modules/prettier/index.js:14899:14)
    at format (/…/node_modules/prettier/index.js:15131:14)
    at /…/node_modules/prettier/index.js:57542:12
    at Object.format (/…/node_modules/prettier/index.js:57562:12)
    at performFormat (/…/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/213.5744.206/PhpStorm 2021.3 EAP.app.plugins/prettierJS/prettierLanguageService/prettier-plugin.js:72:29)
    at PrettierPlugin.handleReformatCommand (/…/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/213.5744.206/PhpStorm 2021.3 EAP.app.plugins/prettierJS/prettierLanguageService/prettier-plugin.js:39:16)
    at PrettierPlugin.onMessage (/…/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/213.5744.206/PhpStorm 2021.3 EAP.app.plugins/prettierJS/prettierLanguageService/prettier-plugin.js:13:33)
Process finished with exit code -1
```
<details>

**Comment by sosukesuzuki** [comment]
Thank you for detailed report! Maybe your problem is caused by IDE side. So it will be good to ask to IDE forum.

**Comment by dan-lee** [comment]
Thanks, @sosukesuzuki, while creating an issue I might've found a related one: https://youtrack.jetbrains.com/issue/WEB-53053

**Comment by kachkaev** [comment]
By looking at your stacktrace, it seems that IDE is calling a built-in prettier, i.e. not the one from your project.

**Comment by dan-lee** [comment]
@kachkaev That's really odd but definitely true. I can select the prettier package in the plugins' settings but I guess it's probably wrapped by the IDE. Maybe the same happens for the VSCode plugin.

**Comment by kachkaev** [comment]
This happened to me in VSCode a few times in the past, yes. A common trigger is a change in project dependencies (i.e. node_modules). It can cause the IDE plugin to break and thus fallback to the built-in Prettier instance. Restarting the editor usually helps in this case.

In VSCode, you can view Output → Prettier and see why a local project-specific version does not apply:

<img width="857" alt="Screenshot 2021-11-29 at 21 07 23" src="https://user-images.githubusercontent.com/608862/143943315-1f42f465-f845-4775-9536-dba08225ef95.png">

Hope that something like that exists in JetBeans too. Shall we close this issue at it seems to be unrelated to Prettier core?

**Comment by lkrugertogetr** [comment]
> Thank you for detailed report! Maybe your problem is caused by IDE side. So it will be good to ask to IDE forum.

Correct! I did not add prettier as a dependency in my project, so it loaded whichever version came with the VSCode plugin. Sorry for the hassle.
