### ISSUE TITLE
Disable Trailing zeros removal

### ISSUE THREAD

**Issue by saar120** [prettier/prettier#11882]
**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAzCFMC8mALAHQAM5A3CADQgQAOMAltAM7KgCGATrxADuABT4JOKbqkHcAnp3oAjXtzABrDAGVuAWzgAZFlDjJsU9nCUr1WxqqMBzZDF4BXSyDg7FcACa+-fW4oB1duBzgAMQheHW4YVhDkEG5XGAg6EAALGB1UAHUslnh2OzA4TXFilgA3YtlksHYFECMLXhhhFQc403MPACt2AA9NR3QARVcIeD7UC3o7XnbkxW4fVEzGXiMYfJZfGCzkAA5yRYELfJVGZO24dpqTegBHafgupgkU9gBaYz8fkyvDgbxYIK64V6SDM8w8Fh0LGcbnh4zgUxmJhh-XoMHW+0OxyQACZcSoWKhHABhCA6aGedgAVkyrgsABV1hJYQsQDV3ABJKABWCaMA7ZgAQSFmhgsnQcwsAF9FUA)

```sh
--parser babel
```

**Input:**

```jsx
let foo = 4.00;
```

**Output:**

```jsx
let foo = 4.0;

```

**Expected behavior:**
let foo = 4.00;

**Comment by alexander-akait** [comment]
Sorry, we don't want to change our output

**Comment by fisker** [comment]
Strange, why we don't print `4` instead? Because the number can be in `4.00.toString()`?

**Comment by alexander-akait** [comment]
We have discussion about it before, somewhere...

**Comment by fisker** [comment]
Found #1653

**Comment by fisker** [comment]
Anyway, `4.0` -> `4` can be done in an eslint rule.

**Comment by saar120** [comment]
I think you missed understood.
The output I'm looking for is "4.00" but after prettier format it is becoming "4"
If I disable prettier extension it's stays 4.00

**Comment by JacksonKearl** [comment]
@alexander-akait I understand you want to keep config slim but this is pretty annoying when working in scientific computing, in which `2.000` represents a value you know to be `2.000±0.0005`, whereas `2.0` (which that gets converted to) just means `2.0±0.05`. This isn't something that matters to the runtime of course, but it's nice to be able to look through the code and understand the margins on each value.

A config option for this would be nice.
