### ISSUE TITLE
"TypeError: Cannot set property 'originalText' of undefined" from TypeScript Jest inline snapshot

### ISSUE THREAD

**Issue by joshkel** [prettier/prettier#11888]
After upgrading from Prettier 2.4.x to 2.5.0, a Jest inline snapshot test in a TypeScript file throws the following error when Jest tries to update the snapshot:

```
    TypeError: Cannot set property 'originalText' of undefined

      at Object.<anonymous> (node_modules/prettier/parser-typescript.js:13:3304772)
      at Object.parse$d [as parse] (node_modules/prettier/index.js:12975:19)
      at coreFormat (node_modules/prettier/index.js:14525:16)
      at formatWithCursor$1 (node_modules/prettier/index.js:14765:14)
      at node_modules/prettier/index.js:60955:12
      at Object.format (node_modules/prettier/index.js:60975:12)
```

I'm not sure if this is a bug within Prettier or within how Jest is using Prettier; if I should file this with the Jest project, please let me know.

**Environments:**

- Prettier Version: 2.5.0
- Running Prettier via: CLI (via Jest)
- Runtime: Node.js 14.17.1
- Operating System: Windows and Linux
- Prettier plugins (if any): None

**Steps to reproduce:**

Clone https://github.com/joshkel/prettier-test-case and run `npm i; npm test`

**Expected behavior:**

The snapshot is correctly written and Prettier formats the file.

**Actual behavior:**

Abort with a stack trace.

**Comment by duailibe** [comment]
Hi @joshkel, thanks for the bug report! Looks like it's a combination of two things.

First one is the fact that Jest calls our parsers directly, but after https://github.com/facebook/jest/pull/7792 it started using it with an incorrect API.

The other thing is that https://github.com/prettier/prettier/pull/11602 didn't account for uses outside of Prettier (which is the case for Jest, which used to pass both `parsers` and `opts` as `undefined`)
