### ISSUE TITLE
CSS formatting

### ISSUE THREAD

**Issue by svipben** [prettier/prettier#1189]
Hello,

I know it is JS formatter, but maybe you have future plans to make it also for CSS? I'm working with `.css` files which can't be formatted and I need to have 2 different formatters... :cry:

**Comment by lydell** [comment]
@svipben Which CSS formatter do you currently use? I've been looking for one for a while.

**Comment by svipben** [comment]
@lydell This one -> http://jsbeautifier.org/, but you need to disable all other formatters and enable only CSS, because it also formats JS, etc., but for me prettier is perfect, just need CSS formatting and it will be godlike tool :smile:.

**Comment by lydell** [comment]
You could very easily create a little wrapper around prettier and any other formatters you'd like that chooses formatter based on file extension or something, though :)

**Comment by mrmartineau** [comment]
@svipben there is already a project called [`stylefmt`](https://github.com/morishitter/stylefmt) that does exactly what you need. It even integrates with `stylelint`.

**Comment by svipben** [comment]
@mrmartineau Thank you very much! This is WOW!

**Comment by SimenB** [comment]
While `stylefmt` is amazing, it is an addon to stylelint, kinda like eslint and its autofixing in 2 separate projects.
One thing I really like about prettier is that it's very opinionated. Sharable configs works great in eslint as well (look at the ridiculous popularity of airbnb's config (over 50k stars...)), but prettier still improved vastly over it by enforcing consistency all over.

Not saying prettier should do css stuff, but I'd prefer if current `stylefmt` was just `stylelint --fix`, and `stylefmt` itself became more like prettier 😄

**Comment by vjeux** [comment]
Working on it! https://github.com/prettier/prettier/pull/1636 I'm going to close this issue.
