### ISSUE TITLE
Different indentation for "continuation indents/wrapped lines"

### ISSUE THREAD

**Issue by dvlato** [prettier/prettier#11898]
Many style guides set a different indentation (2* tabWidth) for wrapped lines/ continuation indents; since Prettier does not want any new configurable option;  Could we please add a default for continuation indents which is 2* normal tabWidth?

See the prettier example, where I would like "this.line.is.very.long()" and "bodyOfBlock()" to have different indentation: 

**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwBaoDOAdADapRzFHEBucATgJ5nQDm2AlADpSaYAyAZgC2EBlUgATKnkZxsDAK5QoFNpgDUmCEpgAaHegCSMgIaFDAdwZmADgEFSEs1KadOmYL34AjCG4A8ugAQqQQYADWXADcvAC+vJBQhDCYhKgiqKRmDNlMDoSESllQbAAy7ABquahmvqRwAHJmInCEmAC8PukQbTWkSnAxIPogEHYwqNCEyKC5DBBWAAq5CLMoZrQQqFKjIL62UXAwAMp2ZmDqyDDKcGN4MCKkAOoE8IQXYHCn66hTtH+TGQ4CK+wohEYMGWtjYIjMyHQZlIkLGACtCAAPEJHSInU6tODlChwRHI1EgDGY07qRoARSUEHgZJR9xAFwYkIYIN89SY4Sg+zseVgL12+GQAA4AAxjYUQSEvWx2EHC9qMej7CQARyUqAkMLMcIRSCRrLGkKyNzuFtpcAZTNJpvJbJg9TFUglSAATGNbmZsuoAMJ9eEgqDQUljJSQgAq9Q2Zsh8XiQA)

```sh
--parser babel
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```jsx
if (this.line.is.very.long()
  && more.code.here(running + out, ofIdeas, wrapAlready)) {
  bodyOfBlock();
}
const similarilyAssumingLongVariableNames =
  someValue;
```

**Output:**

```jsx
if (
  this.line.is.very.long() &&
  more.code.here(running + out, ofIdeas, wrapAlready)
) {
  bodyOfBlock();
}
const similarilyAssumingLongVariableNames = someValue;

```

**Expected behavior:**
```jsx
if (
    this.line.is.very.long() &&
    more.code.here(running + out, ofIdeas, wrapAlready)
) {
  bodyOfBlock();
}
```

Elements inside the IF block have a 4 character indentation instead of the 2 for "bodyOfBlock()"

**Comment by alexander-akait** [comment]
Answered, please do not duplicate https://github.com/prettier/prettier/issues/11897
