### ISSUE TITLE
HTML: error when `div` in `p`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#11907]
**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPlQEwJYBu2A9PkasVgDpQgA0IE6Me0AzsqAIYBOPEAdwAKvBBxRcANgK4BPDgwBGPLmADWcGAGUuAWzgAZPFDjIAZlLZwlK9Zq3pVxgObIYPAK7WQcXYrg4OAEGXFDOHlzOcABiEDy6XDAsYcggXB4wEPQgABYwupIA6jl48GyOYHBaYqWEpbKpYGwKIMZWPDBCKs4J5pbeAFZsAB5aLpJwAIoeEPB9klYMjjztqXkF2eg8xjCFeDgwOcgAHAAMS-xWhSroqVtw7QSmDACOM-BdTOJpbAC0JgEAtkeHA3ngQV1Ir0kBYFt4rLo8G5PPDxlN3qYYf0GDAuIo9gcjkgAEw4lR4SQuADCEF00J8bAArNkPFYACp48SwxYgAheACSUCCsC0YG2zAAgkKtDBZBN5lYAL6KoA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```html
<p><div></div></p>
```

**Output:**

```log
SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:15)
> 1 | <p><div></div></p>
    |               ^^^^
  2 |
```

**Expected behavior:**

No error

**Comment by fisker** [comment]
That's against the spec.

**Comment by fisker** [comment]
See `A start tag whose tag name is one of: "address", "article", "aside", "blockquote", "center", "details", "dialog", "dir", "div", "dl", "fieldset", "figcaption", "figure", "footer", "header", "hgroup", "main", "menu", "nav", "ol", "p", "section", "summary", "ul"` section

**Comment by JounQin** [comment]
> That's against the spec.

But it should not error on formatting.

The html codes comes from other API.

**Comment by alexander-akait** [comment]
@JounQin I don't think, we can't format broken JS (whole file), like we can't format broken HTML (whole file)

**Comment by alexander-akait** [comment]
Even more you faced with bug in your code, maybe better to fix it?

**Comment by fisker** [comment]
It's a parser error. You can open an issue in [`angular-html-parser`](https://github.com/ikatyang/angular-html-parser) or  [`angular`](https://github.com/angular/angular), if you like, but I recommend not to do that.

**Comment by duailibe** [comment]
@JounQin I understand where you're coming from that Prettier could format this as it looks like regular HTML code, but Prettier doesn't work with invalid syntax files (it can be done, but it's out of the scope for Prettier).

**Comment by appukuttan-shailesh** [comment]
@JounQin, @alexander-akait  : if you are just concerned with having the code formatted and are ok to switch parsers, then change to another parser, such as "mdx" or "babel" parsers, and you will find it formatted as you desire:

```
<p><div></div></p>
```
formatted to:

```
<p>
  <div></div>
</p>
```
