### ISSUE TITLE
Last indented list item inline comment is being moved to outer comment and combined with existing comment

### ISSUE THREAD

**Issue by pbelbin** [prettier/prettier#11910]
**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/?source=post_page---------------------------#N4Igxg9gdgLgprEAuEB6VACAKgTwA5wDKYATgJZ4wZmxwkBmAhmHADpQ3wPNzYAWNAOYBGDMHasYjaUgwAKCTEkAfDAHIYAqCLUZ0GAMIQAtsYQxhiles1CATLv1HT5u4oCUAbQC6Abj2YAGI0jAA2GJAusOwAviAANCAQlGTQAM7IoIwkJBAA7gAK2QgZKGF5jDgZiQBGJMwA1nAwhIxmADI0cMhMoWlwtfVgTS14zELIMCQArgMgcMY1cAAmyyvtjNrTjIJwgRAkxowwMBNl0zAQCSB8MMahAOoC8GljLIQlZKcAbl84yOA0tUQDR+iQYAV6oIjj0wv1EgArNIAD0IQlCcAAitMIPBYX05mMSGCATVGEtQtc8ORYA8yMtNMgABwABkS1Ig-Qe9TwAOpcDB326iQAjjj4JDkqUQIw0gBaKBwFYra4kOBishqyE7GFIXrwkD9YxkSYzOZpdFY8XdPVwuZSGp0hl8ZB2RJTRhkUJCZy6+ZpACs12m-Sw5NK+rm31mAEkoGtYMRyJQAILxwgwHAY-H9GIxIA)

```sh
--parser babel
```

**Input:**

```ts
// TypeScript interface
interface Thing1 {
	aaa: (
		| 'thing1' // Comment1
		| 'thing2' // Comment2
	)[]; // Final comment
}
```

**Output:**

```ts
// TypeScript interface
interface Thing1 {
  aaa: (
    | "thing1" // Comment1
    | "thing2"
  )[]; // Comment2 // Final comment
}

```

**Expected behavior:**
```ts
// TypeScript interface
interface Thing1 {
  aaa: (
    | "thing1" // Comment1
    | "thing2" // Comment2
  )[]; // Final comment
}
```

The placement of `Comment2` in the sample output is the point of concern.

Curiously, using 'flow', 'babel', 'babel-flow' and 'typescript' parsers, the same incorrect output is obtained.

But: when using `babel-ts` as the parser, it seems to generate the expected output.

So, I'm thinking this is a bug in Prettier rather than in the parsers?

**Comment by corymharper** [comment]
This is still happening in the latest version of Prettier, has anyone started looking into this?

**Comment by Peter-Sparksuite** [comment]
Another half year later, and it appears that this issue is *still* happening!!!

**Comment by pbelbin** [comment]
@sosukesuzuki and @fisker : Thank you very much for fixing this!  I'm looking forward to when it will be available in a release.

Will it be available in both the 3.x and 2.x releases, or just the 3.x?

Again: thank you!

**Comment by sosukesuzuki** [comment]
3.x only!
