### ISSUE TITLE
when following the suggested instructions vim sometimes deletes the whole buffer

### ISSUE THREAD

**Issue by deltaskelta** [prettier/prettier#1191]
The current set of instructions with...

- MacVim Version 8.0.525 (130) 
- OSSierra 10.12.4

had the following behavior for me...

~/.vimrc
```
autocmd BufWritePre *.js exe "normal! gggqG\<C-o>\<C-o>"
autocmd FileType javascript.jsx,javascript setlocal 
            \formatprg=prettier\ --stdin\ --parser\ flow\ --print-width=90\
            \ --trailing-comma\ es5 
```

produces the following unexpected behavior for me sometimes on a save...

stdin: SyntaxError: Unexpected identifier (1:31)
> 1 | stdin: SyntaxError: Unexpected identifier (1:31)
    |                                ^
  2 | > 1 | stdin: SyntaxError: Unexpected identifier (1:29)
  3 |     |                                ^
  4 |   2 | > 1 | stdin: SyntaxError: Expected corresponding JSX closing tag for BS.Button (157:41)

if there is a syntax error somewhere then it produces an error which is ok, but then it gets written to the buffer, and since the suggested instructions had the setting set to run before writing the buffer, in essence my whole file gets erased and replaced with an error.

I am "somewhat" inexperienced in vim so I am sure there may be a way around writing the stderr of prettier to the buffer, but nonetheless I think that the instructions should be changed so that unsuspecting users don't accidentally erase their files...

I will research how to fix this, in the meantime if anyone has any ideas or input, I would appreciate it.

**Comment by josephfrazier** [comment]
Hi @deltaskelta, I'm another Vim user who's encountered the same problem, and I recommend using the [Neoformat approach](https://github.com/prettier/prettier/tree/c56a685e5d9fce9299cabdbadd3e7edc3c190de2#neoformat-approach) instead.
