### ISSUE TITLE
Typescript 4.5: type Modifiers on Import Names fails when combined with export statement

### ISSUE THREAD

**Issue by PupoSDC** [prettier/prettier#11921]
[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACYPAEzgDMBDAVwBt9yBnPAQQwwCFzsAaPGATwxxmrDtgAK2CBkYBfPKUkBbPAB0QAAUWUAlgHpF5eNm3lqulu05qA3CqgguIKTG3R6yUJ0kB3MZwTuKKbe5HzujgBG2ORgANZwMADKGDHaUADmyDDYlHCOABYwitQA6vna8PQpYHCJARXaAG4VfMjg9OEgafRwuBLk6QbIFNQ9jgBW9Ghs0XEJieSKcAAyaXDDpmMgk2iJaenUcACKlBDwG6N5ICnYPdhtEeQRcNQO18awJdpEMPnIABwABkcGEkPRK0QwbVBcDujXWjgAjqd4BIpIEQAwALRQOBwEhEN7YODI7TE-qDcgXLY9RTaLI5K70faHE5ndZIEZbGBPL4-P5IABMjmy5G01H2AGEIIohihYQBWN6UHoAFSegS5V0auQAklASLBEmBjBgYEwDYl+IdqXAZDIgA)

**Input**

```ts
export { default as AppBar, type AppBarProps } from "@mui/material/AppBar";
```
**Output:**

```
SyntaxError: Unexpected token, expected "," (1:34)
> 1 | export { default as AppBar, type AppBarProps } from "@mui/material/AppBar";
    |                                  ^
  2 | 
```

**Expected behavior:**

No error

**Comment by fisker** [comment]
**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACYPAEzgDMBDAVwBt9yBnPAQQwwCFzsAaPGATwxxmrDtgAK2CBkYBfPKUkBbPAB0QAAUWUAlgHpF5eNm3lqulu05qA3CqgguIKTG3R6yUJ0kB3MZwTuKKbe5HzujgBG2ORgANZwMADK5IpwADLaUHDIFNT0cJHRcQmJGDGZAObIMNiUBaiKEXBEJERp5FAVlOQVcABiOAYwLp3IIFQwEA4gABYwitQA6jPa8PRlYHCJAavaAG6rfGNg9OEgmfm4Ej0GOab5jgBW9GiJldRwAIqUEPB3efUythLmN+IJ6GBjBgYNMMMZYIttEQYDNkAAOAAMjjhEHyi2iGDGcLglz22UcAEcfvAJFJAuN6ABaLLNZrTbBwKnaDnXCq3JC5B4gfKKbTVWr1ejvL7U7IC+71GDkCKI5GopAAJkcNXI2molQAwhBFPzUPQAKzTSj5AAqysCgvqezqAEkoCRYIlIdpoUx3Yl+B9-kLnmg2EV4kkUulMnLHTIZEA)

```sh
--parser typescript
```

**Input:**

```tsx
export { default as AppBar, type AppBarProps } from "@mui/material/AppBar";

```

**Output:**

```tsx
export { default as AppBar, type AppBarProps } from "@mui/material/AppBar";

```

**Comment by PupoSDC** [comment]
:facepalm: 

Thanks a lot for your help.. This must be some problem with my tooling then, i'm getting this error in my project:

![image](https://user-images.githubusercontent.com/9625304/144677618-4f74f71f-b226-4ee3-8441-5f57447654c8.png)

and i can't figure out why :(

**Comment by kachkaev** [comment]
Try `yarn prettier --version`. It might be out of date.

**Comment by duailibe** [comment]
@PupoSDC that error could also happen if you have a config somewhere forcing `parser: "babel"`

**Comment by PupoSDC** [comment]
Took me a while, since I didnt really have explicitly anywhere "partser: babel". But in the end specifying `"parser": "babel-ts"` in prettier config did the trick.

Thank you both for your help!! <3
