### ISSUE TITLE
JetBrains IntelliJ - Relative path won't work

### ISSUE THREAD

**Issue by n1try** [prettier/prettier#1192]
The `$FilePathRelativeToProjectRoot$` [mentioned for Jetbrains editors](https://github.com/prettier/prettier/blob/master/editors/jetbrains/README.md) doesn't work. It points to the wrong directory. Instead I had to use the `$FileRelativePath$` macro.

**Comment by umidbekkarimov** [comment]
Both options works for me. Can you provide your config with console output?

**Comment by vjeux** [comment]
I'm going to close this issue since no answer was given.
