### ISSUE TITLE
Invalid shorthand for ExportSpecifier

### ISSUE THREAD

**Issue by lachrist** [prettier/prettier#11939]
Sorry for not following the usual issue formatting but this issue is only available via the API:

```js
// Actual:   export {specifier1};
// Expected: export {specifier1 as specifier2};
console.log(require("prettier").format(".", {
  parser: () => ({
    type: "Program",
    body: [
      {
        type: "ExportNamedDeclaration",
        declaration: null,
        specifiers: [
          {
            type: "ExportSpecifier",
            local: {
              // start: 0, end: 0,
              type: "Identifier",
              name: "specifier1",
            },
            exported: {
              // start: 1, end: 1,
              type: "Identifier",
              name: "specifier2",
            },
          },
        ],
        source: null,
      },
    ],
    sourceType: "module",
  }),
}));
```

Uncommenting the `start` and `end` properties solves the issue. I understand that `prettier` looks into the `start` and `end` properties to inspect the original formatting of the code. But I submit to you that these properties should only affect the formatting of the generated code and not its correctness. This can be motivated by the fact that the `start` and `end` properties are not part of the [estree specification](https://github.com/estree/estree).

**Comment by fisker** [comment]
But we can check specifier name first

**Comment by fisker** [comment]
I'm going improve this check in #11941, but still, the range info is required.

**Comment by lachrist** [comment]
Thanks for your answer. I understand that `prettier` requires code locations. However from my experience with prettier, it seems that code locations only affect the format of the generated program and not its semantics. The issue I raised here with specifier shorthands is the only example I could find where code location affect the semantic of the generated program.

**Comment by fisker** [comment]
#11941 should fix it then,

**Comment by lachrist** [comment]
Thanks man, wish you all the best!
