### ISSUE TITLE
Prettier should either provide whitespace sensitivity option for JSX/TSX or respect that of html

### ISSUE THREAD

**Issue by ippeiukai** [prettier/prettier#11932]
Prettier should provide a way to specify whitespace sensitivity for JSX/TSX.
Those languages are typically used to generate HTML, but htmlWhitespaceSensitivity does not currently seem to apply.

Without this feature, it is very hard to mark up texts in languages that do not insert whitespaces between words.

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlADgQykwF5MAKYMACwEsAbAEwCcEBfAShID5yAeNAlC6VajFlFa8A9AMJd2AbgA6UFby4rMmXnjmAhBh2CuB3UL3mLlq9YvTTxu0fOO5aqVxAAaEBFwwa6Mig+ExMEADuAAohCGjIIPgAbhA0DF4gAEZM+GAA1nAw2PgAtnAAMjRQcMgAZvh0aHDeWTn5hQRglQDmyDBMAK5NIHDFGXAMDONlhF39+F1wAGIQTMX4MP5QPSj4-TAQ6VQwxXQA6rTwsmBw2LE0-on3AJ7xGEw0YDDplY1MMJHZLprWr1RreABWaAAHthunQ4ABFfoQeAghpDAhMX7xDL4MZ0dK4d6wU6pGBUZAADgADN4iRBGqdsrh4kS4L9EtVvABHZHwAG+OI7NAAWiq43G6RYvJoLAB82BSDq6O8jWKNF6AyGaDhiL51SVoKGMDxpIY5OQACZvH18PRugBhCDFRUgKDQLkgfqNAAqeKFyrBIESgwAklBJrBsGB3n4AIIR7AwJ7wtFByFQgBC2TyBSKpQqVTTcFYrCAA)

```sh
--parser babel
--arrow-parens avoid
--trailing-comma none
--html-whitespace-sensitivity strict
```

**Input:**

```jsx
const Span = ({children}) => (<span>{children}</span>);

<>
  <Span>あ<Span>あ<Span>ああああああああああああああああああああああああ</Span>あ</Span>ああ</Span>
</>
```

**Output:**

```jsx
const Span = ({ children }) => <span>{children}</span>;

<>
  <Span>
    あ
    <Span>
      あ<Span>ああああああああああああああああああああああああ</Span>あ
    </Span>
    ああ
  </Span>
</>;

```

**Expected behavior:**

Somethink akin to:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAygBwIZQHyBCDBjvkVroQVdTbXVagPTmlMuVsl4gA0IEmGAEtoAZ2ShsAJykQA7gAVpCcSmwA3CEIAmvEACMp2MAGs4MdNgC2cADJCocZADNsAG1Fw+h42Ys4wBwBzZBgpAFcvEDgrfThtbXjbXCDw7CC4ADEIKStsGGEoELVwmAg9AAsYKzcAdQqheFEAuHQVRqF1RoBPZBBRMKEwGD0HTykYBSMgvJd3Tz4AK1EAD3RgtzgARXCIeDmPKJwpcb6qmr1MKQcYWp0YCuQADgAGPiuIT1qjTD6ruHG6icfAAjrt4FMBKoQNhRABaRzxeJ6KRwMFCVFTdKzJCuQ58TxWIShCJRUQbbbgpy4+ZRGDYfR3bQPZAAJj4YWwQjcwQAwhArDiQFBoMCQOFPAAVBmqPELEDqSIASSgiVg6DA10EAEFVegYN1Ngd5csVgAhIymcyWGz2RzGuAAX0dQA
```jsx
const Span = ({children}) => (<span>{children}</span>);

<>
  <Span
    >あ<Span>あ<Span>ああああああああああああああああああああああああ</Span>あ</Span>ああ</Span
  >
</>
```

**Comment by Josh-Cena** [comment]
JSX never treats line breaks as spaces, but ignores them:

![image](https://user-images.githubusercontent.com/55398995/145002410-44c55c3a-7ba3-424d-8e16-21bc9c9bd8e8.png)

So it's never subject to HTML whitespace sensitivity rules.

> mark up texts in languages

Are you trying to directly use JSX as markup for HTML instead of compiling it with a JSX runtime?

**Comment by ippeiukai** [comment]
> JSX never treats line breaks as spaces, but ignores them

Oh. It seems a bad misunderstanding of JSX on my side now. Terribly embarrassing.
Thank you for your reply!
