### ISSUE TITLE
Add an option to disable adding parentheses around spread + ternary operator

### ISSUE THREAD

**Issue by Zajozor** [prettier/prettier#11933]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEkoBNMC8mMATgK5wDcAOlLThplHAO4DyARgFaGbC2ZMADyTFycADQDMAehmYAkphYQyAG3xqAlgGs4xABZa0xCJhJwAtgEMtUZVpgHVWAA7WLsA3DQ+p92XkOMjcLGBgtOBJMa1xcEycrADppOUwAZTNHZVUNTA59KC0wfRgzA2sAN31rbGgAMy0Ac0wIVwjoTHqIaMdpJIGcXGlBAH4+EcEp61FqEA45-ynl7FmQYZAllYBfSdFgbf9tmihNkDaOqDRkUA8SCBYABQ8Ea5RrNRZrAE9riXmSNYwHoYOlrJY4AAZOxwZD1D6+f4cQHAuCg9xgOxNZCkCj-KwFOJwXCQ6xQJpkaxNOAAMR6NnCWOQIGsIQgZwMMEsagA6kZ4GgMXB0q9HFpKo5vsywGg-iA7L4SDBHoCmjY4QjJCAuGghOksWo4ABFMgQeAatSIkDuEiK5kcawFNRnVwkOwwHlaXBOZAADgADP9XRBfDzAa5ma6fFFqmcAI6m+AqtpvFloAC0zGJxLOFgTWgsKqp6qQ8MtWt8li0OPE-zQBuNidhpc1-xgjs93oMyAATG3AVptOSAMIQSwlkA+ACsZzIvgAKo63mWrZUKAo8AhQWA3e0AIJ4dIwb6Gi2+bbbIA)

```sh
--parser babel
```

**Input:**

```jsx
const cond = true;

const newObj = {
  x: true,
  // I would like this to remain without parentheses,
  // but prettier adds them.
  // So it would be nice to have a config option for it
  ...cond
    ? {
        a: "b",
        c: "d",
      }
    : {},
};

```

**Output:**

```jsx
const cond = true;

const newObj = {
  x: true,
  // I would like this to remain without parentheses,
  // but prettier adds them.
  // So it would be nice to have a config option for it
  ...(cond
    ? {
        a: "b",
        c: "d",
      }
    : {}),
};
```
**Expected behavior:**

```jsx
const cond = true;

const newObj = {
  x: true,
  // I would like this to remain without parentheses,
  // but prettier adds them.
  // So it would be nice to have a config option for it
  ...cond
    ? {
        a: "b",
        c: "d",
      }
    : {},
};
```

This "ternary spread" pattern is something we use fairly often. But we don't want the parentheses around it. Partially because of consistency with other things, and our TS+ESLint+Prettier setup.

It would be amazing if we could have a config option in prettier to disable these parentheses from being added near spread + ternary.

I am open to contributing this feature if I receive a bit of guidance about where to look :)
Would it be possible?

Keywords: spread, ternary, parens, no-extra-parens, config, eslint-typescript

**Comment by kachkaev** [comment]
👋 @Zajozor!

Prettier is built on the principle of being opinionated about code formatting. This means we add options only in the case of strict technical necessity. Find out more: https://prettier.io/docs/en/option-philosophy.html

**Comment by Zajozor** [comment]
@kachkaev Thanks for the quick reply!

Do you by any chance have some guidance as to how to set up our codebase in a way that this behaviour does not conflict with no-extra-parens? (eg. https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-extra-parens.md ) (if we disable no-extra-parens it leads to problems in other places, which neither prettier nor eslint then help with).

Even if it is not of interest for the upstream, could you give a small bit of advice where to look for this in the code?
We might look into using a custom fork.

I appreciate your time.

**Comment by alexander-akait** [comment]
You should disable `no-extra-parens` rule to use prettier, it is stylistic problem, prettier solve your problem without additional options/settings

**Comment by Zajozor** [comment]
@alexander-akait actually, now that I retried it, you're right! I'm not sure what I was doing before 🧠 💩 😅 .  Prettier solves those extra parens problems pretty nicely. We'll just disable that eslint rule as suggested.

Thanks you guys for the help, sorry for the bother.

Keep up the good work!

**Comment by kachkaev** [comment]
@Zajozor if you want to disable all ESLint rules that conflict with Prettier, take a look at [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier).
