### ISSUE TITLE
Prettier ugly formatting in react

### ISSUE THREAD

**Issue by ivanjeremic** [prettier/prettier#11943]
This is how prettier is formatting my react code.
```
const dateSelect = useCallback(
    (val: string) => {
      setDate(val);
    },
    [date]
  );
```

```
const dateSelect = useCallback((val: string) => {
      setDate(val);
},[date]);
```

There needs to be something horrible wrong, behause there is no way the prettier way is cleaner, sometimes long one liners are just cleaner this should be discussed.

**Comment by sosukesuzuki** [comment]
Duplicated with #11881 ?

**Comment by ivanjeremic** [comment]
> Duplicated with #11881 ?

Yes looks like a duplicate is there some solution to this? Because it make looking at the code very hard.

**Comment by sosukesuzuki** [comment]
No, not at the moment. I'm trying to figure out how to improve it now. I'll implement it when I have time.

BTW, I close this because duplicated.
