### ISSUE TITLE
[Typescript, Type casting] Prettier adds semi colons at the beginning of the line when --semi = false

### ISSUE THREAD

**Issue by Dynacord** [prettier/prettier#11962]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACMBDAznDARgB0phTiYAKXCAWzhgAsBLKAcwzwwEEAVAJ4AHOAEoMAXgzEQ2AMowATm3YzSAXwpR0WPAQBMpclEpUAPP2FwAfLQbMVAUQA2+cVIAshqJqgZ-Af5GpP46OPgYAMxY9ABGbCq6+LgYinC4AK7OMBhsGLjYDBjObHAhGDT0jKwcXCmWIu7SsgrKHGp+FRaCIrZVDhwubpIYXhrlgcGdYXqjFZB0DLBwACYYsXA4GRFbyVz5ArDYAB4YcIqKEIoYouU63VZ99jXsQwSe3uogADQgEEIwFjQXDIUDYC4QADuAAVwQgQShsM5IdgBCDfrFFNgwABrRhyQpwAAypWQADMkfgMVjcfihNiVMglBk4L84HQNisVqsidgOBlsOw4AAxK50bAwQEcZB-Mlkn4gJgwOjOADqrHguHpYDgcnhLEBADcDQIZWBcOiQGx8IoYNCsexxeTKayQAArXDHOQqZxwACKGQg8Gdrld9MUNplMCsuDAygBCqEbRgqpYK2YyAAHAAGX5JiD4VVYoQypPpc6GuAKgCOgfg9v+CNkuAAtFA4KtVgq0rWWGl7YKnUgKaHfvg6CwQ1SQLgff661Xhy7fjBsLFU+mmMh9CusSwShwAML0IcgdIAVgV2zgfDXCJH08NLIAklBubA5HGWACeG+FAJfSnOB1HUIA)

```sh
--parser typescript
--no-semi
--embedded-language-formatting off
```

**Input:**

```tsx
// case 1
{
	(something as AType) = "aString"
}

// case 2
{
	(<AType>somethingElse) = 42
}
        
{
  // case 3 combining cases result in same line
  (something as AType) = "aString"
  (<AType>somethingElse) = 42
}
      
{
  // case 4 (commented because causes a syntax error )
  // <AType>somethingElse = 42
}
```

**Output:**

```tsx
// case 1
{
  ;(something as AType) = "aString"
}

// case 2
{
  ;(<AType>somethingElse) = 42
}

{
  // case 3 combining cases result in same line
  ;(something as AType) = "aString"(<AType>somethingElse) = 42
}

{
  // case 4 (commented because causes a syntax error )
  // <AType>somethingElse = 42
}

```

**Expected behavior:**
Prettier shouldn't add semi-colons at the beginning of the strings (case 1 and 2)
Prettier shouldn't combine two variable assignments on the same line (case 3)
Prettier shouldn't consider "unwrapped" type casting as a syntax error (case 4). **This also happens with --semi = true**

```tsx
// case 1
{
  (something as AType) = "aString"
}

// case 2
{
  (<AType>somethingElse) = 42
}

{
  // case 3 combining cases result in same line
  (something as AType) = "aString"
  (<AType>somethingElse) = 42
}

{
  // case 4 (shouldn't be a syntax error)
  <AType>somethingElse = 42
}

```

Workaround is simply to add // prettier-ignore over the problem line

**Comment by alppe461** [comment]
42

**Comment by fisker** [comment]
This works as intended. See https://prettier.io/docs/en/rationale.html#semicolons
