### ISSUE TITLE
JSX allow multiple tags on the same line (ie. format JSX the same as HTML)

### ISSUE THREAD

**Issue by adamerose** [prettier/prettier#11983]
**Prettier 2.5.1**

[HTML Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAeArgGwHwA6U66GOAlnhgIaoAWATnAGYC8BIAxB6jOTDjjsQACQgBbOBzxjJGAPTUq8ioWIkylGvSZsO3NHwFCOAQQBGELDGkWrMBUoWqiJTKu2MWwg736DhAGVyAHNiAFUAB2lgsNQox2UXdVIPWi89Lh4jAI4AYWgYajAbEDwC2GKHRSTKVw00nW99bP8TEDzqJjgGAGdpTu6+xOc69QVcNSJ67Hx61LG3UnTdH1bjYVkpMvmlrd3SGt3RtTdNU6XPVZbDNuE7a2kDkgebFI0j95Pj5KXMFeaWVuGw4sQi0R27zcYPi0ShmE+ZxUiwaKLOAMyvhy7QqRRKT3h6FxVWeiWOyIuC0pGgxa2BuQ6XTgPX6kL+RKZLNJiI+vwRkxAABoQBBInxoL1kKAugwIAB3AAKTKgkpQ1BwcuoAE9JcLzAxigBrOAwQLUSQAGXIUDgyGY6t6cD1BrAxtNkWK1pCyBgDCwTpAcHE5jgABNQ2GLdQoCEsNQQnAAGIQBjiagwPgx5AgajWCBCkB0GDiHAAdTo-DgvQ9YDggQQvX45AAbvwtdmwL1dSBrY6GDAFQaQmm7Q6AwArXoAD2CMcEAEUsBB4KOcI7hR6+j1s0WSwXIgxrTBS+RQzA6MgABwABg3ssdpYNkWzB6rPWbtuFAEcl-BB6LVRzXoAFobTDMMCyYH9yCYQd4xHJB7TXANHXEcgfT9FCvQXX9bUQsdhSKcwTzPC8kAAJkIg1yAoGMCnEBDA16ABWAssEdAAVahzFVJD1xAZt-QASSgCNYECMBDzFUxRMCGAtUEVdHQAX2UoA)

[JSX Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEcAeBGTAXk0wAoAdKEgHgFcAbAPkpJvoEtHqBDTACwBOcAGaFyIAMTjMMdjHpwxIABIQAtnHGNVG6gHpuXPR2ZVW1Ez35DR4qSBlyFSgIIAjCLRhb3nmPsN9ExZzS15BESV7R3lFcQBldgBzKgBVAActRJTMDICjYLM2TisI20lpWVilAGFoGG4wbxBGOthG-wMCzhDirnCbKMqnOJAa7iE4ATQtccnp-KCes30GUwBKAG5KSkgoDGwcACYiMhC6Jl7MC2XWcwHIu2Hq8R1NFqu7t8-rrqul0x3G6Au7XB7laJVZziXxeLQ-Eiw7xFcx-FEA-6FUFg6yPCoOKGjbJpTIfFF3Ym5TLk36Gf7GW6hRlA8FDAkjWr1DrwmkkNoNJo-fL0rFMkEs3EQ57QsYTOBTGZk7F8uUKoVooEMkGrS5QLaUEAAGhAEHSsnQyFAEwEEAA7gAFOX7ZAgbj0W3cACeaCNIDcAkaAGs4DB4twNAAZdhQODIYRutBwY3+oMh+LpRrRpLIGACWhJkBwNRuOAAE1LZYj3CgSVo3CScAAYhABGpuDBZDWXdwvBBfXwYGp6AB1PhyOBoDNgODxBBoOTsABuck9LrAaB9xujiYEMHtAaSbbjCYLACs0DhEjWFABFWgQeDH+iJ40Z6ZTF1ubgl+i+9ICaMYGHdhSxgPhkAADgABlfG1E2HAN0hdf8JymRdY2NABHe94H3U0fRQbg0AAWhjMsy19IRsPYIR93rI8kHjZ8C0TNR2BzPMWKzW8cNjRiT2NBo3GA0DwKQI5BIDdgOBrOo1AYws0AAVl9WhEwAFW-AimJfEBF3zABJKAK1geIwAAs0XGM+IYE9BQn0TABfRygA)

**Input:**

```jsx
const example = () => (
  <ul>
    <li><a href="#" title="Home">Home</a></li>
    <li><a href="#" title="About">About</a></li>
    <li><a href="#" title="Sign Up">Sign Up</a></li>
    <li><a href="#" title="Contact">Contact</a></li>
    <li><a href="#" title="Careers">Careers</a></li>
  </ul>
);

```

**Output:**

```jsx
const example = () => (
  <ul>
    <li>
      <a href="#" title="Home">
        Home
      </a>
    </li>
    <li>
      <a href="#" title="About">
        About
      </a>
    </li>
    <li>
      <a href="#" title="Sign Up">
        Sign Up
      </a>
    </li>
    <li>
      <a href="#" title="Contact">
        Contact
      </a>
    </li>
    <li>
      <a href="#" title="Careers">
        Careers
      </a>
    </li>
  </ul>
);

```

**Expected behavior:**

I would like to be able to keep each `<li>` element (and nested `<a>`) on a single line. When I apply Prettier, it automatically puts each tag and text on a separate line for JSX, but for HTML it keeps the original style. I think the JSX formatting here should have the same behavior as the HTML

**Comment by kachkaev** [comment]
Hi @adamerose! 👋 Which practical problem are you trying to solve?

**Comment by adamerose** [comment]
> Hi @adamerose! 👋 Which practical problem are you trying to solve?

After more reading I realize this inconsistency is just due to the fact that HTML formatting is whitespace sensitive while JSX isn't so I think my initial problem was expected behavior.

**Comment by kachkaev** [comment]
Yep, that’s right! Unlike in HTML, spaces and newlines in JSX are ignored – they do not affect the result of rendering. Seeing multiple lines in the source may look confusing at start, but they are easy to get used to. What’s good about them is that `git diff` for the changes ends up smaller and thus `git blame` becomes more useful for the team 🙂
