### ISSUE TITLE
Prettier fails to detect opening html tag when it has liquid markup inside it

### ISSUE THREAD

**Issue by datapolitical** [prettier/prettier#12007]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UGAtGwNoCWAZuQCUAggCERASXwBdZlGABScgAcAThABWcMDAD6ANzgqAzt2jlINGtxjkjlCCpvyAvi3LuP5APRMmn9wA+vm7+Ae6+nl7kQVD+0R4R8d4h-ok6AV460Sn+Uam+sXHpcdE6Oe5RXgAUYYEAlBHBhRUtHlkJfuRNHnm13h0etd39HTplTGM6mVOeQQVJJYuDXfN9S4u1MeGd2+sVednNayvkk+1jXgeHy3s9kSHTZwDuL0-ur2+nUywYnAgAJnwpBxZKhqPRyHQAIZQADmAF4mCBgMBlFDYXAAHTQuHxf5wXhQgCudBgSFs1ixONheIJxNJ5KRCCR5GcrhAoPQHHICmUak02n0hhMZhc5BBP0ocCh-1k7lQRhgAE86HA5TzFGAoUoYESVHBbFCjEYdGAVNZuFq6OQXCFedwoGA6ET8aaoWApf9zOaYJaoXRMUYwMaba5CryAVqdXqDbbw6ijEaTWaLVb4kHjXwlayw-KvIqVWq7Yo+GiMZi9db4fCuiAvPqwNwlHAjD4QOQHGWsZXyNXa-WtE2W5jwXQWXH5XQHQBrcj6uiIkAF1V2OBwGAsyj63iLlH9pPr1vB1swKEAIyMmOPLLC86hvoMOh7bKR6vtjud+PINHXULY3BodEsVHUNi3IOA6BMfglCAisVGtSBYChB0jFrBshyMcdcw1cgk24WFYhoJV0ObXsKXgTF-nvKFMRIlt4l4B1-iQJEoChH8kQAGi7TFfRgVVQMKVAf1PPkIGbRwlUXCBYSQACgJZRD4FgXcE0pODrTZLwDxgVsUSIujMXkjEn3gl92y8N9FABUsJ3IYTf3INif0XGCMUrRToGUmBVLc7szPZdUHNEj0oWMddVPIrEEEgQFcXMoKRKhJz2LgRc9G4OAniUBwN3bJSEB8pEnm4f4YEoeF8QysA4DYEqysobiHQtf02CDf00oARkxAAGV8QmC5LnLSpFyrgH82EgOgHE82BCsXABiTrcE6zAACY1qRSyBqSlKXKRYlypm-KvPmpE9z8zFDvsFRaUJEkySiq6iSO26whbKMDQSnbHOGxcMSgQx72O8xTpUpEACk4GnFVrT0PdNBhugAwMYxTFib6hKnKBZ3nRctSgaA-THdstwJSLLp7MJzyMCBnXgUzNMCgbsdxiDF2XFspXXTdt0iradKPY0vCYuAAA8r2NG85wg+9uEfZ9maxmcZYXJFAKgPgWzyqg+fO4ATAoystI1rXFUxdRaagfrlZx1XF21JRVTYGAICJD1-0Q3nyf1w3-LoLTHed133coT3oExJQ4RtsCjDgCBBNQLwpRlUEzwgf4lVkSVpXxW6nSTRcU7zm35TYvRzGhY1F2G19UGSsmd31-tpbvB84EZnNFKroxFz41VXz3P3eOsAT3va0i2STqEGCT8urPIB0nRdDutQ9OAvR-KAiTYTPnMtEdaGtLeiXhYfy-wuXRTDJPi8MbO5FRArYC763WCDc0dXIKjT0mwkjCVI6RchJIJwBZEYFQYBVLD2Ns4bSxpDxeEtl4JQTw-zdR6piKwUALaYQ5EnD+TYYCyHfMvV0a9PS4TYnQJUvpgyHwhHGJO6dM6gmTkfWQIBOIgHEr6aARhkCgDCmoJ4xAwoIAESgf0aClQCO4WeFQ7ppzrgAMqpQADIOjgMgEBcd5GKLAMomAKiYKNjhMgGAKgiRwG4eNM8G98T-HUTCWERIgIADEHCARgL6cxUiXoQC4SAUcAB1SglIjCmLgCoiRFoMrKmQOAY0QSUKGBgMQRRsJAI6P9HokAlsxYqIdLCVUABFIkEB4A5NAdwmC4UVCJNHEE1QDoYAhNKuVZAAAOHqtS1BxxCYopQiTVAtkMAYIJABHCp8AMniUkSAI0bBAYbw3kE-U0zuD6gyeibJSBdE2KXONbgFirGHJMHCMpMztH7NyYc08Z52kNWQGtbhljkLY1hLgCAlgoSJJbAAViCUSOO+AabVLyXoax4goD4lgColMOohCwpUcqVUEK4BsiAA)

```sh
--parser html
```

**Input:**

```html
<!DOCTYPE html>
<!--[if RABBIT]>
{% project_version commit short %}
       /\      |\
      |  \    / |
      |   \  |  /
       \  _|/_ |
        /      \
       _|       |_
      / /(|   |)\ \
    /  /    _    \  \
   /  |   /   \   |  \
  /    \__\___/__/    |\
 |                    | \
 |                    |  |
  \    \            //   |
   |     \ ____  __//    |
   |               /    /
  /______wwww  wwww  __/
<![endif]-->
<html lang="{{ page.lang | default: site.lang | default: "en" }}">
<!-- {% project_version %} -->
<head>
  <style>
  {% capture sass_critical %}
  {% include_cached critical.scss %}
  {% endcapture %}
  {{ sass_critical | scssify }}
  </style>
  {% if page.url == "/recipes/" or page.url == "/recipes.html" %}
  <link rel="stylesheet" href="{{ "/assets/css/tabs.css" | relative_url }}">
  {% include meta-image.html %}
  {% elsif page.url contains "recipes" %}
  {% assign myrecipe = site.data.recipes | find:"name", page.title %}
  <meta property="og:image" content="{{ site.url }}/assets/{{myrecipe.image_url}}" />
  {% endif %}
  <meta name="pageurl" content="{{page.url}}">
  <meta charset="{{ site.encoding }}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="theme-color" content="#1C1D22"/>
  <meta name="author" content="{{ page.author | default: site.author | escape }}">
  <meta name="generator" content="Jekyll v{{ jekyll.version }}">
  <link rel="canonical" href="{{ page.url | absolute_url }}">
  <link rel="stylesheet" href="{{ "/assets/css/index.css" | relative_url }}">
  <link rel="manifest" href="{{site.url}}/manifest.json">
  <link rel="apple-touch-icon" href="{{site.url}}/apple-touch-icon.png">

  {% seo %}
</head>
<body>

<header class="header">
  <nav class="name"><a href="{{ "/" | relative_url }}" class="title">{{ site.title | escape }}</a></nav>
  {% include_cached menu-dynamic.html menu=site.navigation %}
</header>

{{ content }}

<script data-cfasync="false" src="{{site.url}}/assets/js/pwa-1.0.min.js"></script>
{% include_cached analytics.html %}
</body>
</html>

```

**Output:**

```html
SyntaxError: Unexpected closing tag "a". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (53:95)
  51 |
  52 | <header class="header">
> 53 |   <nav class="name"><a href="{{ "/" | relative_url }}" class="title">{{ site.title | escape }}</a></nav>
     |                                                                                               ^^^^
  54 |   {% include_cached menu-dynamic.html menu=site.navigation %}
  55 | </header>
  56 |
```

**Expected behavior:**

There should be no error as the opening <a> tag is present and the closing tag is present.

**Comment by fisker** [comment]
Sorry, we don't support this syntanx.

**Comment by datapolitical** [comment]
No you don't support the syntax, you *ignore* the syntax, which is what should be happening. And what does 99% of the time, except when the liquid is inside of an html tag.

**Comment by datapolitical** [comment]
And you do support HTML

**Comment by fisker** [comment]
Avoid using quotes and slashes in the attribute then.

**Comment by datapolitical** [comment]
Quotes and slashes are perfectly fine in HTML attributes, they're used for links all the time. 

I just don't understand how you guys could support ignoring half of liquid but not filter tags inside of elements.

**Comment by datapolitical** [comment]
This is a development question.

**Comment by fisker** [comment]
```html
<!-- Valid -->
<video>
  <source src="movie.mp4" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
</video>

<!-- Valid -->
<video>
  <source src="movie.mp4" type="video/mp4; codecs=&quot;avc1.42E01E, mp4a.40.2&quot;" />
</video>

<!-- Invalid -->
<video>
  <source src="movie.mp4" type="video/mp4; codecs="avc1.42E01E, mp4a.40.2"" />
</video>
```

**Comment by datapolitical** [comment]
OK, how does that apply to what I am talking about?

**Comment by datapolitical** [comment]
And I should say, I appreciate you taking the time to engage with me on this question, I'd really like to use the product I just wanna understand why this isn't a bug considering that you mostly support ignoring liquid.
