### ISSUE TITLE
Search icon in search bar on prettier website is not positioned correctly

### ISSUE THREAD

**Issue by technophile-04** [prettier/prettier#12003]
The search icon in the search bar on the website is not positioned correctly.

[https://prettier.io/](https://prettier.io/)

**Current**
<img width="525" alt="Screenshot 2021-12-28 at 11 14 51 AM" src="https://user-images.githubusercontent.com/80153681/147532824-ea8bac30-c751-445b-83c2-b6a012efd1b9.png">
**Expected**
<img width="540" alt="Screenshot 2021-12-28 at 11 14 35 AM" src="https://user-images.githubusercontent.com/80153681/147532836-ec0cd6d0-1778-4e79-9664-48132db215c6.png">

**Comment by technophile-04** [comment]
Can I work on this issue, please?

**Comment by fisker** [comment]
Which browser are you using, it's centered in mine (Edge v99).

**Comment by technophile-04** [comment]
I am using chrome

**Comment by fisker** [comment]
There must be some plugin breaks it?

**Comment by sosukesuzuki** [comment]
It's centered in Chrome 96 on MacOS

**Comment by technophile-04** [comment]
yes it was because of plugins
