### ISSUE TITLE
Simplify clean-cspell

### ISSUE THREAD

**Issue by Jason3S** [prettier/prettier#12014]
@fisker,

An issue on CSpell: https://github.com/streetsidesoftware/cspell/issues/808 referenced your `clean-cspell.mjs` script.

After reading through the script, it made me realize that CSpell has some options that might be useful.

The following code that parses the output:

https://github.com/prettier/prettier/blob/c9c6d3364f8cf5140c3c16b44b92943464be7873/scripts/clean-cspell.mjs#L21

might be simplified if you use the `--words-only` option in combination with `--unique`.

**Comment by fisker** [comment]
That's great! Thank you!

**Comment by fisker** [comment]
Nice to meet you here. A off topic question: are you interested in build a ESLint plugin? https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1442 :smile:
