### ISSUE TITLE
Automatic paren changes semantics and broke code

### ISSUE THREAD

**Issue by wyuenho** [prettier/prettier#1201]
We recently upgraded from prettier 0.19 to 0.22. Prettier now starts to strip parens in expressions like this:

```javascript
// before
var fooInstance = new (classFactory('Foo'))(...);

// after
var fooInstance = new classFactory('Foo')(...);
```

This stripping is not safe because the invocation operator `()` has higher precedence than new, so the interpreter will try to invoke the returned class like a function first then attempt to `new` the result of the function invocation.

**Comment by vjeux** [comment]
Sorry about this! This is fixed in master https://github.com/prettier/prettier/pull/1169.  We're going to do a release this week. In the meantime, you can add `// prettier-ignore` in the line before to workaround it.
