### ISSUE TITLE
Windows and Ubuntu Check Results Are Different

### ISSUE THREAD

**Issue by tuhanayim** [prettier/prettier#12010]
**Environments:**

- Prettier Version: 2.5.1
- Running Prettier via: Node.js
- Runtime: Node.js v17.3.0
- Operating System: GitHub CI Windows and Ubuntu Latest
- Prettier plugins (if any): None

**Steps to reproduce:**

1. Create GitHub workflow for both Windows and Ubuntu latest versions
2. Add prettier, check script, config and etc.
3. Push to GitHub for workflow run
4. See the results

My workflow runs:
- https://github.com/tuhanayim/simpleicons-cli/runs/4659122978
- https://github.com/tuhanayim/simpleicons-cli/runs/4659404136

Repo (`refactor` branch): https://github.com/tuhanayim/simpleicons-cli/tree/refactor

**Expected behavior:**
On Windows, it should behave like Ubuntu. No errors and check is successful.

**Actual behavior:**
On Windows it says the files are not formatted, but they are formatted actually and checks on Ubuntu (and on my personal Arch Linux) are perfectly fine.

**Comment by fisker** [comment]
Try copy this file to your repo to see if it result differently https://github.com/prettier/prettier/blob/main/.gitattributes

**Comment by tuhanayim** [comment]
> Try copy this file to your repo to see if it result differently https://github.com/prettier/prettier/blob/main/.gitattributes

This file fixed the issue but is there no solution without `.gitattributes` file? Since there's no problem with ESLint's checker i think the problem is related to Prettier.

**Comment by brodybits** [comment]
I use `--end-of-line=auto` to solve this on Ubuntu & Windows.

**Comment by tuhanayim** [comment]
> I use `--end-of-line=auto` to solve this on Ubuntu & Windows.

Looks `git clone` on Windows replaces `lf` endings with `crlf` and because of this Prettier says files are not formatted. I'm going to change EOL option to `auto`.

**Comment by tuhanayim** [comment]
Yes, changing EOL option to `auto` fixed the problem. Issue solved, thanks.

**Comment by kachkaev** [comment]
`lf` + [`.gitattributes`](https://github.com/prettier/prettier/blob/main/.gitattributes) is generally safer. I had colleagues on Windows who used both WSL and CMD.exe interchangeably. This essentially meant that they had two independent git binaries processing the same repo folder. As result, if a repo was cloned in a Windows shell but a commit was done in WSL, the remote repo ended up with `crlf`. I guess it’s just a matter of time for a repo without enforced `lf`.
