### ISSUE TITLE
I can`t use prettier in vue3 and pug.

### ISSUE THREAD

**Issue by willx12123** [prettier/prettier#12045]
In vue3 and vite project, pug code in template can not have initial indent, like:

```vue
// Good way
<template lang="pug">
div
  p.text-xl.text-red-500 123123123
</template>

// Bad way
<template lang="pug">
  div
    p.text-xl.text-red-500 123123123
</template>
```

For script and style tag, prettier can keep no indent at inital place. But it force me to indent in template tag.😭

That means I cannot run `prettier --write` for my all vue file. If I do that, it will add indent for every pug code line, and then vue3 and vite will not working......

Could prettier fix this?

**Comment by willx12123** [comment]
I think I fix it by using @prettier/plugin-pug.

**Comment by fisker** [comment]
It's also not broken without plugin

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdQHyVQAmAlgG4uGFYB08AB4wAtEJyC4I0QCc4rUQFYADCsIBGAEwBmbXt0tUAeky4CcRiAA0ICFhjtoAZ2Sg8s2RADuABQ8Irih4ON54AJ6utgBGsnhgANZwMADKeBhwADLsUHDIAGYhznAxcYnJKVjxOaTIMLK0JSBwGNEKrAqZeGS0eKRwAGIQshgEjmTIIHi0MBA2IAAWMBg4AOoL7PDOVWBwKYGbXJvhk2DOUSA5xbIwvnGkowVFTQBWzkIpNThwAIq0EPAnjhirYqrJrpNOI15lhZDkYKt2KwYAtkAAOFSgrzFVZxLCTWFwa6cPK2ACO-3gd3sQSmzlEuQUCnm8gp7Hkdz6jyQhWBTWKGHYdQa-K+v0peR5z1sMDw0URyNRSC0Mri7BwNQAwhAMNzms4lPNaMUACpyoK8kEgKFwACSbAQqTAcIcAEE2CkYOFvkDigBfP1AA)

```sh
--parser vue
```

**Input:**

```vue
<template lang="pug">
div
  p.text-xl.text-red-500 123123123
</template>
```

**Output:**

```vue
<template lang="pug">
div
  p.text-xl.text-red-500 123123123
</template>

```

**Comment by willx12123** [comment]
> It's also not broken without plugin
> 
> **Prettier 2.5.1** [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdQHyVQAmAlgG4uGFYB08AB4wAtEJyC4I0QCc4rUQFYADCsIBGAEwBmbXt0tUAeky4CcRiAA0ICFhjtoAZ2Sg8s2RADuABQ8Irih4ON54AJ6utgBGsnhgANZwMADKeBhwADLsUHDIAGYhznAxcYnJKVjxOaTIMLK0JSBwGNEKrAqZeGS0eKRwAGIQshgEjmTIIHi0MBA2IAAWMBg4AOoL7PDOVWBwKYGbXJvhk2DOUSA5xbIwvnGkowVFTQBWzkIpNThwAIq0EPAnjhirYqrJrpNOI15lhZDkYKt2KwYAtkAAOFSgrzFVZxLCTWFwa6cPK2ACO-3gd3sQSmzlEuQUCnm8gp7Hkdz6jyQhWBTWKGHYdQa-K+v0peR5z1sMDw0URyNRSC0Mri7BwNQAwhAMNzms4lPNaMUACpyoK8kEgKFwACSbAQqTAcIcAEE2CkYOFvkDigBfP1AA)
> 
> ```shell
> --parser vue
> ```
> 
> **Input:**
> 
> ```
> <template lang="pug">
> div
>   p.text-xl.text-red-500 123123123
> </template>
> ```
> 
> **Output:**
> 
> ```
> <template lang="pug">
> div
>   p.text-xl.text-red-500 123123123
> </template>
> ```

I think it is just not execute format program for template content.

See [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdQHyVSUwAmAlgG4uGFs2WAHTwAHjAC0YnKLgTJAJzjtJAVgAMG-jt26AjACYAzC1QB6TLgJxmrKKgDOMAJ45bfYWHyPHhYCx8hAC+-Gbmzm4eUCAANCAQWDCc0I7IoHiKihAA7gAKmQhpKHg4OXguafEARop4YADWcDAAyngYcAAynFBwyABmpY5wNXWNzS1Y9T2kyDCKtCMgcBjVKuwqnXhktHikcABiEIoYBMlkyCB4tDAQcSAAFjAYOADqD5zwjlNgcC1Fnx4nxclzAvnuPWGihgeTqpFOAyGSwAVo4xC0Zu4AIq0CDwRE4YbxKaKKGXbiLe5YRQ9GCvTjsGAPZAADg0xOyw1edSwl2pcCh3D68QAjrj4LDEsUro5JL0VCp7soxZxlLC9gikINCUthhhOHMFrrMXAcXi+lqkfEYHhqvTGcykIZrXVODgZgBhCAYTXLRxqe60YYAFVtxW1RJAFLgAEkoBtYC0wDSkgBBeMtVzuAnDYLBIA)

I add a lot of space between 123123123 and class name, but they are still in the right panel.

**Comment by fisker** [comment]
Because Prettier consider it's unknown language without plugin, we can't format it.

**Comment by willx12123** [comment]
> Because Prettier consider it's unknown language without plugin, we can't format it.

I see...

My situation is caused by WebStorm, prettier actually cannot format pug without plugin.
