### ISSUE TITLE
JSX markup is incorrectly breaks lines on punctuation

### ISSUE THREAD

**Issue by rschristian** [prettier/prettier#12047]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9jyowYBLaPACQgFs4AKASj2AAdKHlF5scGOWwjuwsQrwAeAHzzFGpQGc4DZlDUiNx0UoAWARhXsuSgPSXDJk0oxPnHgKJpSHDJTg8eDQYIRA8QRAAX3UPF1JYuI8zCWIAXkizGBgMLSQ7O3RffzgAWkpGKABrcogwUiZoO0jEpJMYUmwAc0kMkAB9ACNKUmqWozbnCUo+qBwSOGwJbHHJjXc14wqxic3lO1IVABo8UYIgs0YtPCvTvAxsCGG4DgbGMDxtwMGJUiqAOlacXsbiBmjsOj00A2insMN4AG5hFEQEcQBAMI0oFpkKBOo8AO4ABU6CBxKFIlAJpAAnji0T9SGAqpIAMq+OAAGUqcGQZEoOgZ2CZLJgrIwTMqXWQMGw5DgaJegzgBCIBE5oy65FIPQAYjhXtkpcgQBQYBBUSAshxKAB1S7wLQSsBwVlkxhMABuHppJrAWnpIEqOlwROFXVefMpgpAACstGhWVKAgBFcgQeBRgUKkAS7Ahk2DUjKyiWh6VGC2xgEGBmZAADgADGiHhAdLbhRgTQ84CHPby0QBHdPwMMY8mmrSlKBwFUqy0SYeMCRhnWRpD8mM6DiMGVynNaZNwNMZ3kb6M5jqDKs1utIABMaNlpEY2y6AGFOOvUFoAKyW8gdAAFWLclNxzT15QASSgIhYFZMBsEYTEAEFYNZGAaQCLMdCiKIgA)

```sh
--parser babel
```

**Input:**

```jsx
export default function Home() {
    return (
        <>
            <section>
                <h1>Home</h1>
                <p>
                    Example text{" "}
                    <a
                        href="https://example-link-location/"
                        target="_blank"
                        rel="noreferrer"
                    >
                        link
                    </a>, and this is a problematic line break.
                </p>
            </section>
        </>
    );
}
```

**Output:**

```jsx
export default function Home() {
  return (
    <>
      <section>
        <h1>Home</h1>
        <p>
          Example text{" "}
          <a
            href="https://example-link-location/"
            target="_blank"
            rel="noreferrer"
          >
            link
          </a>
          , and this is a problematic line break.
        </p>
      </section>
    </>
  );
}
```

**Expected behavior:**

Maybe this?

```jsx
export default function Home() {
  return (
    <>
      <section>
        <h1>Home</h1>
        <p>
          Example text{" "}
          <a
            href="https://example-link-location/"
            target="_blank"
            rel="noreferrer"
          >
            link
          </a>,
          and this is a problematic line break.
        </p>
      </section>
    </>
  );
}
```

The issue is that a new line will result in white space in the HTML (after the anchor tag, before the comma), where there was none. Punctuation needs to remain where it is.

**Comment by Josh-Cena** [comment]
JSX is whitespace insensitive. Line breaks between tags and text nodes don't become whitespaces.

**Comment by rschristian** [comment]
> JSX is whitespace insensitive.

That's incorrect.

There is no JSX spec. How different tools use the syntax is entirely up to them, and many do follow the correct HTML semantics which say that line breaks become whitespace.

**Comment by Josh-Cena** [comment]
Well, _JSX_ may not have a well-defined behavior regarding whitespaces (although you didn't give an example and I can assert that Babel and tsc, two of the major implementers, both ignore line breaks for JS interoperability), but the _parser_ certainly does. You specified Babel as parser, and if Babel can't see the whitespace, you should expect it to work at runtime yeah?

Just curious, is there a JSX implementation that actually makes it whitespace sensitive? There have been _constantly_ bug reports about whitespace formatting in JSX, but none of them were actually valid

**Comment by rschristian** [comment]
Well, I didn't intend to specify Babel as a parser by any means. I just opened the playground link and used whatever was the default. I have no earthly idea what the differences between the parsers are or what prettier uses normally.

Just taking a look now, some combinations of Acorn and [HTM](https://github.com/developit/htm) make whitespace relevant, yes. In my example, moving the comma to the previous line would correct it.

In retrospect, an implementation that's used less commonly isn't worth supporting. I can just tell prettier to ignore the line and move on.
