### ISSUE TITLE
Prettier makes code harder to read by removing line breaks.

### ISSUE THREAD

**Issue by FractalHQ** [prettier/prettier#12053]
Large files become harder to read when sections of code can't be separated by more than 1 empty line.  Empty lines can be used to group related code, improving the organization and readablility of large codebases.

<details>
<summary>Even 1 empty line is removed sometimes, further degrading readability.</summary>
This is harder to read:

```scss
$colours: (
    /* Text */
    "text": $light-100,
    /* Background Colours */
    "background-primary": $dark-300,
    "background-secondary": $dark-200,
    "background-tertiary": $dark-100,
    /* Primary Colours */
    "primary": $blue-300,
    "primary-hover": $blue-400,
    /* Secondary Colours */
    "secondary": $blue-200,
    "secondary-hover": $blue-100,
    /* Misc */
    "green": $green,
    "red": $red
);
```
Than this:

```scss
$colours: (
    /* Text */
    "text": $light-100,

    /* Background Colours */
    "background-primary": $dark-300,
    "background-secondary": $dark-200,
    "background-tertiary": $dark-100,

    /* Primary Colours */
    "primary": $blue-300,
    "primary-hover": $blue-400,

    /* Secondary Colours */
    "secondary": $blue-200,
    "secondary-hover": $blue-100,
    
    /* Misc */
    "green": $green,
    "red": $red
);
```
</details>

If I can't stop prettier from removing empty lines, how can I write a plugin or hook to prevent Prettier from making my code harder to read?

**Comment by ghostdevv** [comment]
+1

**Comment by sosukesuzuki** [comment]
This is a bug according to the [empty lines rationale](https://prettier.io/docs/en/rationale.html#empty-lines).

**Comment by sosukesuzuki** [comment]
Also, if you ever create an issue in Prettier again, please follow the Issue Template.

**Comment by FractalHQ** [comment]
Will do!  Perhaps the SCSS example should get it's own (properly named) issue?

My issue, however, applies to all languages.  Specifically, my inability to improve the organization and readability of large files by separating related groups of code using 2 (or more in rare cases) empty lines.

My question specifically was:
> If I can't stop prettier from removing empty lines, how can I write a plugin or hook to prevent Prettier from making my code harder to read?

Any insight would be much appreciated!

**Comment by sosukesuzuki** [comment]
On JavaScript formatting, we can get the below output that is keeping line breaking.

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mwAOlJpgPQBU1mADgE4T0CMAtAMya2VkVMWrJJk4Aafg2b0ATCPGTB9TvInlMkmnSUAWdgFYe1Put2rF0-efWbaUlgDZ2ADiMmB0h9Y8sA7N-t6Z2sAXwBuMhAxEBYYAEt0ZFAAQ0ZmAHcABVSENGQQZIAbdOSATzzogCNGZLAAazgYAGVkgFs4ABk4qDhkbCK0OCqa+sam+lrugHNkGEYAVyGQOFbKuAATdY2O5Kgp+eSpuAAxCEZW5Jh4vfzk+ZgIKJAACxhWwoB1Z7j4NAmwOBNXI-OIANx+pXyYDQFRA3UGjBgmRqUwufQGSwAVmgAB5NaaFOAARXmEHg6MKg2iE0YCPylWSa0KTyY3RgHzi6xgz2QzgADNTmIMPjV6PkmHAEaDetEAI6k+DIlh5FDJNDsHobDZPRhweVxXXIw5opD9SlLQatOKzBYWgnEhW9U0Y6IwRkcrk8pAyV01OKFaYAYQgrRNyzQ+ie80GABVGSqzVSQKDFgBJKBbWBNMCMOL0GAAQQzTRgpUJFMGIRCQA)

```sh
--parser babel
```

**Input:**

```jsx
const foo = {
  /** prop1-3 **/
  prop1: 3,
  prop2: 3,
  prop3: 3,
  
  /** prop4-5 **/
  prop4: 3,
  prop5: 3,
  
  /** prop6-8 **/
  prop6: 3,
  prop7: 3,
  prop8: 3,
};

```

**Output:**

```jsx
const foo = {
  /** prop1-3 **/
  prop1: 3,
  prop2: 3,
  prop3: 3,

  /** prop4-5 **/
  prop4: 3,
  prop5: 3,

  /** prop6-8 **/
  prop6: 3,
  prop7: 3,
  prop8: 3,
};

```

**Comment by sosukesuzuki** [comment]
> If I can't stop prettier from removing empty lines, how can I write a plugin or hook to prevent Prettier from making my code harder to read?

The answer is we should not create any plugins to fix this bug. We should fix it on Prettier side.

**Comment by FractalHQ** [comment]
Ah yes, thanks!   I don't believe that addresses the issue though.  Here are the important parts in bold:

> Specifically, my inability to improve the organization and readability of **large files** by separating related groups of code using **2 (or more in rare cases) empty lines**

Related:
- https://github.com/prettier/prettier-eslint/issues/176
- https://github.com/prettier/prettier/issues/554
- https://github.com/prettier/prettier/issues/4439
- https://github.com/prettier/prettier/issues/1610
- https://github.com/prettier/prettier/issues/3501
- https://github.com/prettier/prettier/issues/1613
- https://stackoverflow.com/questions/54413716/how-to-add-multiple-lines-between-code-blocks-with-prettier
- https://stackoverflow.com/questions/68708569/vscode-prettier-no-need-to-remove-blank-lines
- https://www.digitalocean.com/community/questions/prettier-custom-rules-formatter
- https://stackoverflow.com/questions/59309733/prettier-rule-no-multiple-empty-lines-not-working-in-react-js-project

I've been resisting the urge to make this issue for years in hopes that I was missing something, but at this point I am certain that I'm not.  The _1-empty-line only_ rule significantly decreases code readability (depending on the context), inhibiting the speed of navigating large files with modular, related sections of code.

A config option to specify the `max-empty-lines` would obviously solve this problem that so many people have, but since the maintainers of this project refuse to add it, I would like to know how I can fix the problem without it.

**Comment by zhangenming** [comment]
![image](https://user-images.githubusercontent.com/21235555/148647932-47658a26-0df2-4d4e-b389-5e1d2c9c2764.png)
Same question

**Comment by brodybits** [comment]
I think it would be awesome if someone could update both the title and description with some more info.

Title could read something like this:

    Prettier removes blank lines from CSS

And add markdown from a playground, this for example:

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASSAbCBXATgZyQAIAKAHSiKqIHoAqIgFTgA8Yi6aLqiyR42fYqgwBLAOYALGAFoAjAAYFAGgrdq9IgCEAhmADW43DigATIgGEIWPPg5dK1PgCM9h49jMyADrlEBbHVwATyEiVFMg-RkAZiVVRyoXNyMTUxl8OEgzINDkcMjcaIAmePUkkFcDVM90+FwYUVywiKj5Mqhy2gYABT9AkMtrHAJ7Lr5fAOb81GcMbDhYjp4J-tyZSQgANzhcFrmFmQAWDq7NAGUs6ELgoZtRznGQTOyb-fnF0pUnl+v1zZ2exmB0Wim+iV4EM0AFlRPgwGMIXwjHAEC0UQgEisQLg4KYWrj8VAAJQAbhAyhAEG8jWg+GQoCCxgA7j0ggh6SgdBhmTpgvTKc5cG44DBzjp-HAADKiKBwZAAM25mUFwoMovO3j0svEyBguAWlLg-mceNMeKlOig4mwOnEcAAYhBcIEYI1rcgQDpsDAIBSQNJ-BgAOqSUTwfBasBwS5QfDh0RbcPBT1gfACkCyzINPp2wKK5VwSkAK3wLHOOowcAAitgIPACxgVSAtQRdqn0-7JrBg6JTDBJMgABwqFvGTLB4XeT2+ODZnb+gCOdfgfWpnK9+BkcrxeP9uOXolxufE+aQSqbReextEeoNV-j1qrtfr8vPhcpMB0zl7-cHSGKT9hVEMRrSsfwzxAOcAFZ-WwTJGG-TkL2bLYFgASTMBAxTAPwaQAQTMc4YGCKtG0yABfCigA)

```sh
--parser css
```

**Input:**

```css
$colours: (
    /* Text */
    "text": $light-100,

    /* Background Colours */
    "background-primary": $dark-300,
    "background-secondary": $dark-200,
    "background-tertiary": $dark-100,

    /* Primary Colours */
    "primary": $blue-300,
    "primary-hover": $blue-400,

    /* Secondary Colours */
    "secondary": $blue-200,
    "secondary-hover": $blue-100,
    
    /* Misc */
    "green": $green,
    "red": $red
);
```

**Output:**

```css
$colours: (
  /* Text */ "text": $light-100,
  /* Background Colours */ "background-primary": $dark-300,
  "background-secondary": $dark-200,
  "background-tertiary": $dark-100,
  /* Primary Colours */ "primary": $blue-300,
  "primary-hover": $blue-400,
  /* Secondary Colours */ "secondary": $blue-200,
  "secondary-hover": $blue-100,
  /* Misc */ "green": $green,
  "red": $red
);

```

**Expected:**

same as input (??)

**Comment by wesleyboar** [comment]
Wow. [Prettier does not know how to solve this problem, and that is their rationale for merging blank lines.](https://prettier.io/docs/en/rationale.html#empty-lines)

> **Empty lines**
> It turns out that empty lines are very hard to automatically generate. The approach that Prettier takes is to preserve empty lines the way they were in the original source code. There are two additional rules:
> 
> Prettier collapses multiple blank lines into a single blank line.
Empty lines at the start and end of blocks (and whole files) are removed. (Files always end with a single newline, though.)

**Comment by FractalHQ** [comment]
@brodybits While this issue happened to mention the CSS bug, that is not the primary subject of this issue.

This issue is about the lack of a configuration option for allowing **_more than 1 empty line in a file_**, as clarified in my [previous comment](https://github.com/prettier/prettier/issues/12053#issuecomment-1007773411):

> > Specifically, my inability to improve the organization and readability of **large files** by separating related groups of code using **2 (or more in rare cases) empty lines**
> 
> Related:
> 
> * [Prettier does not respect the "no-multiple-empty-lines" rule of eslint prettier-eslint#176](https://github.com/prettier/prettier-eslint/issues/176)
> * [Suggestion: add option to retain blank lines #554](https://github.com/prettier/prettier/issues/554)
> * [Option Request: configurable empty multiple lines #4439](https://github.com/prettier/prettier/issues/4439)
> * [2 new lines after import #1610](https://github.com/prettier/prettier/issues/1610)
> * [Keep the empty line at the beginning of a function, if present. #3501](https://github.com/prettier/prettier/issues/3501)
> * [Readability: Preserve existence of two or less blank lines between code chunks. #1613](https://github.com/prettier/prettier/issues/1613)
> * https://stackoverflow.com/questions/54413716/how-to-add-multiple-lines-between-code-blocks-with-prettier
> * https://stackoverflow.com/questions/68708569/vscode-prettier-no-need-to-remove-blank-lines
> * https://www.digitalocean.com/community/questions/prettier-custom-rules-formatter
> * https://stackoverflow.com/questions/59309733/prettier-rule-no-multiple-empty-lines-not-working-in-react-js-project

**Comment by Frikki** [comment]
The problem is even deeper. For example, you might want to collapse multiple empty lines into a single empty line for JavaScript files; on the other hand, you might want to preserve consecutive empty lines in CSS files.

**Comment by pedro-santos21** [comment]
Agreed

_Before prettier:_
```js
export const startMongo = async () => {
    const dbConnection = <string>process.env.STAGE === 'PROD' ? <string>process.env.MONGODB_KEY_PROD : <string>process.env.MONGODB_KEY_DEV;
    try {
        await mongoose.connect(String(dbConnection), {useNewUrlParser: true, useUnifiedTopology: true});
        console.log("+ Connecting to MongoDB...");
        mongoose.connection.on('connected', () => {
            console.log('+ You are connected to MongoDB!');
        });
    } catch (error) {
        console.error('Error connecting to MongoDB:', error);
        throw error;
    }
}
```

_After:_
```js
export const startMongo = async () => {
  const dbConnection =
    <string>process.env.STAGE === "PROD"
      ? <string>process.env.MONGODB_KEY_PROD
      : <string>process.env.MONGODB_KEY_DEV;
  try {
    await mongoose.connect(String(dbConnection), {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("+ Connecting to MongoDB...");
    mongoose.connection.on("connected", () => {
      console.log("+ You are connected to MongoDB!");
    });
  } catch (error) {
    console.error("Error connecting to MongoDB:", error);
    throw error;
  }
};
```

Which one do you guys think is more readable? Maybe I'm in the wrong here...

**Comment by kachkaev** [comment]
@pedro-santos21 I pasted your example into Playgound and it preserved new lines for me:

**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3xIENcBZaAcwjwF48yiBPKMPACgEpGA+PMAA6UPOILQSeACYAjAMLQocMDACW0RngA8JbOqg1+GbBDBwiRAHQIAbtYDKAFQCCAcQCijBkwDkAAoASgDyACJ+eAD8uvqGxqbmljb21pQhAHLu4QBCAPoA0p4AmnnB4XhIsTAGRiZmFla2UA7pWbmFJXlhngBqANyiEng1rEJDwxJkAO5k6vgAtrQQEERw1oQqalyONfFc8kpQWxrQPAA0QgCuaxlw0wCq2AA2ARRr2FU1V3CXN3APKDqABm6jgMmcECwzwgNFYX2wPwAvjxBlAJpNJMQIM91jCaFxhCAANR4I4neIjejUIwQMI5ayMomo0QYyZLWmrdabVSnKDWaBcPw8tTgvyXXgCcZiTGTQhEHF42FC0nFCBXZjYOBYk7gql4Gl0ekAQj8LJlmJRaOGSIIZBgYAAFtw4NgzNg+CILXKpIrbG6cELPAHsDreZSYNTlvSkOK8K73ebZSNHWZpvGQ9aJEjREiQOcQFC+URkKAKGm3lriMgQGRnrNWCWC3JsGQwABrOAwRxkBZwAAyhjgyGBdbWzdbHa7jgwbfiyG+vxAawW6gXiKXRHiuIAilcIPAR2OlwArIhoRzbuB7g-DpCj57jkAAR338ACZgwJZQLAAtCpwXBfMQBqOZnniJQFgWMgazrZ5gK3IxcVcGA9jkK531dQcVCPR8l0dGAFmeAB1R15ksWcLEcBAtw0Ox5lYGswCsYC7B+ABJKAZAQbswAMDAYFcLjdlYXFcKfRI1mI1sMBrUxLFdOxhwLQwPhgD8yBoaDxKXWdsA+GsYFYDBLD49QBOA0xDBgYj1BkGBHWQAAOAAGAstVfdQtQ0rSYPvY8CxgMg5Fs+zHKQAAmAt-mcYLvwfJ84AWORwW4mR+zIIwrk0uAADEcGg1D5x-DCIBAJEkSAA)

```sh
--parser typescript
```

**Input:**

```tsx
export const startMongo = async () => {
    const dbConnection = <string>process.env.STAGE === 'PROD' ? <string>process.env.MONGODB_KEY_PROD : <string>process.env.MONGODB_KEY_DEV;
    try {
        await mongoose.connect(String(dbConnection), {useNewUrlParser: true, useUnifiedTopology: true});

        console.log("+ Connecting to MongoDB...");

        mongoose.connection.on('connected', () => {
            console.log('+ You are connected to MongoDB!');
        });
    } catch (error) {
        console.error('Error connecting to MongoDB:', error);
        throw error;
    }
}
```

**Output:**

```tsx
export const startMongo = async () => {
  const dbConnection =
    <string>process.env.STAGE === "PROD"
      ? <string>process.env.MONGODB_KEY_PROD
      : <string>process.env.MONGODB_KEY_DEV;
  try {
    await mongoose.connect(String(dbConnection), {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log("+ Connecting to MongoDB...");

    mongoose.connection.on("connected", () => {
      console.log("+ You are connected to MongoDB!");
    });
  } catch (error) {
    console.error("Error connecting to MongoDB:", error);
    throw error;
  }
};
```

**Comment by FractalHQ** [comment]
I'd like to request that you please restore the original title and close this issue as wont-fix instead of changing it into something it was never intended to be.  We can make a new issue for the CSS bug.

The community support for this option has been widespread for years now.  It's a legitimate complaint, and for historical reasons, the support shown for this option would be best preserved with the original title.

As an aside, if anyone has advice towards a reasonable solution -- whether it's adding this option with a plugin or a fork -- that would be greatly appreciated.  I'm forced to use prettier (like many in this thread) due to it's industry dominance and it would be a massive QOL improvement if I was able to preserve code readability in large codebases using empty lines without being forced to remove them against my will by a tool like prettier 😅

**Comment by sirhaffy** [comment]
Is there a fix for this? Or what options do we have?

**Comment by sosukesuzuki** [comment]
We'll never add any options for this. But it is possible that it will be fixed.
