### ISSUE TITLE
Prettier [error] -> Comment "' + comment.value.trim() + '" was not printed..."

### ISSUE THREAD

**Issue by garrettmorse** [prettier/prettier#12073]
[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuABAWwgEwK4A2cAdHAB4AOEATjAM7F0AWcBBAomXGOgLzoAzPFDAwAltHTNWHLmAAUkTJgCGUHAEoAOlHTpg6AG4rq6AmKhw6fKSzak5iiMrU4ANMDpiisJDGp4cAC+GsQQeDAUEYwU5jDyAPRaOgnauugYBBAA5vIARhAEOE4u6hppehgCNOjyxqZi6BZmFlYVevotlnQA2mIAusT+Ypg6HRlNArUAhObdff0a6JCwFoHoCQlSANZiFOh5BGrbXVZjHZk58nNWC+16QeePUCBuIBAU4tB0yKAm1BAAO4ABRMCB+KBUBEBKgAnj83nlqCowNs4DAAMoqTBwAAyrWQAihdDgiORqPRGIoKIs2WQ-kCbzgmDycBwODZuLU2TwKmycAAYjRVDBxFA6ZCIhBXiAmDBMAQAOpMMTwOjUsBwDHg1ViQyq2HIcB0BEgCwk2jA5HZVSE4mkkAAKzoZAxtKIAEU8BB4HaCCS3tTqBajXkVKyCDKKNQLDBFWIcDAmMgABwABkDAJJiuRFCN0ascGohjgMoAjt74FaPhCQCo6ABaSxstky6hwCtidtWvm2pBE-0OkmYMT0gJD91wL0+0v9+1vGDh+OJ5NIABMC+R3lpAGFnH2QFYAKwyvAkgAq4YhA4DIEMgQAkuoEJiwDHPgBBdQYmCwoh+kkgiCIA)

**Input**
```
$ prettier someScript.js --check
```
`someScript.js`
```
; module.exports.shellExec = function shellExec(command)
  { var lines = shell.exec(command,{silent:true}).output.split(/\n/)
  ; log(bold(command))
  ; for (var i in lines)
    { lines[i].trim
    ; if (!lines[i]) continue // skip blank lines
    ; log(lines[i])
    }
  }
```

**Output**

```
Checking formatting...
someScript.js [error] someScript.js: Error: Comment "skip blank lines" was not printed. Please report this error!
[error]     at Object.ensureAllCommentsPrinted (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/index.js:13824:13)
[error]     at coreFormat (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/index.js:14538:14)
[error]     at formatWithCursor$1 (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/index.js:14765:14)
[error]     at Object.formatWithCursor (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/index.js:60959:12)
[error]     at format$1 (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/bin-prettier.js:18001:21)
[error]     at Object.formatFiles$1 [as formatFiles] (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/bin-prettier.js:18115:16)
[error]     at async main (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/bin-prettier.js:20216:5)
[error]     at async Object.run (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/bin-prettier.js:20159:5)
All matched files use Prettier code style!
```

**Expected Behavior**

```
[warn] someScript.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

On prettier version 2.5.1.

This is my first issue in this repo, so please let me know if there's something missing from this bug report.

**Comment by kachkaev** [comment]
Please follow the issue template, i.e. include a reproduction in the Prettier Playground. Here it is: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuABAWwgEwK4A2cAdHAB4AOEATjAM7F0AWcBBAomXGOgLzoAzPFDAwAltHTNWHLmAAUkTJgCGUHAEoAOlHTpg6AG4rq6AmKhw6fKSzak5iiMrU4ANMDpiisJDGp4cAC+GsQQeDAUEYwU5jDyAPRaOgnauugYBBAA5vIARhAEOE4u6hppehgCNOjyxqZi6BZmFlYVevotlnQA2mIAusT+Ypg6HRlNArUAhObdff0a6JCwFoHoCQlSANZiFOh5BGrbXVZjHZk58nNWC+16QeePUCBuIBAU4tB0yKAm1BAAO4ABRMCB+KBUBEBKgAnj83nlqCowNs4DAAMoqTBwAAyrWQAihdDgiORqPRGIoKIs2WQ-kCbzgmDycBwODZuLU2TwKmycAAYjRVDBxFA6ZCIhBXiAmDBMAQAOpMMTwOjUsBwDHg1ViQyq2HIcB0BEgCwk2jA5HZVSE4mkkAAKzoZAxtKIAEU8BB4HaCCS3tTqBajXkVKyCDKKNQLDBFWIcDAmMgABwABkDAJJiuRFCN0ascGohjgMoAjt74FaPhCQCo6ABaSxstky6hwCtidtWvm2pBE-0OkmYMT0gJD91wL0+0v9+1vGDh+OJ5NIABMC+R3lpAGFnH2QFYAKwyvAkgAq4YhA4DIEMgQAkuoEJiwDHPgBBdQYmCwoh+kkgiCIA).

Replacing 

```diff
- ; if (!lines[i]) continue // skip blank lines
+ ; if (!lines[i]) continue; // skip blank lines
```

fixes the error. [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuABAWwgEwK4A2cAdHAB4AOEATjAM7F0AWcBBAomXGOgLzoAzPFDAwAltHTNWHLmAAUkTJgCGUHAEoAOlHTpg6AG4rq6AmKhw6fKSzak5iiMrU4ANMDpiisJDGp4cAC+GsQQeDAUEYwU5jDyAPRaOgnauugYBBAA5vIARhAEOE4u6hppehgCNOjyxqZi6BZmFlYVevotlnQA2mIAusT+Ypg6HRlNArUAhObdff0a6JCwFoHoCQlSANZiFOh5BGrbXVZjHZk58nNWC+16QeePUCBuIBAU4tB0yKAm1BAAO4ABRMCB+KBUBEBKgAnj83nlqCowNs4DAAMoqTBwAAyrWQAihdDgiORqPRGIoKIs2WQ-kCbzgmDycBwODZuLU2TwKmycAAYjRVDBxFA6ZCIhBXiAmDBMAQAOpMMTwOjUsBwDHg1ViQyq2HIcB0BEgCwk2jA5HZVSE4mkkAAKzoZAxtKIAEU8BB4HaCCS3tTqBajXkVKyCDKKNQLDBFWIcDAmMgABwABkDAJJiuRFCN0ascGohjgMoAjt74FaPhCQCo6ABaSxstky6hwCtidtWvm2pBE-0OkmYMT0gJD91wL0+0v9+1vGDh+OJ5NIABMC+R3lpAGFnH2QFYAKwyvAkgAq4YhA4DIEMgQAkuoEJiwDHPgBBdQYmCwoh+kkgiCIA).

**Comment by garrettmorse** [comment]
Thank you for the information. I was able to resolve the issue but just wanted to make sure the error was reported!

**Comment by kachkaev** [comment]
Thanks! Minimal repro ([Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgG4CG2AllhKlsfALYDOAlFpLMVAK5xYD0XTE11BDAA6UANwgANCAgAHGMWi1koIhggB3AApEEylAQA2GggE9l0gEYYCYANZwYAZQKCAMqzjJUR2nCs29o5OsrasAObIMBgc0nDUlnAAJknJbgRQ4WwE4XAAYpjUBDAKmcggBGwwEFIgABYw1IYA6nVUcLShYHBOelTEeFSm5WC0FiCsfhgwWjbhRd6+-iAAVrQAHk4RhnAAimwQ8IuGftKhGFPllgSJhrWyGKwwzcRJMHXIABwADGfqfs0bLJyg8OnAMHgvNIAI4HeCzOT6Cq0AC0UDgyWStQwcFhxBxsxyCyQPhOyz81GIURi5O2ezhXhJS2kMBuLzeHyQACYWTZiIYIgBhfjEkAdACstTYfgAKjd9KTTiA8BwAJJQVKwJxgR7yACCGqcMFMO2OfgAvuagA)):

```js
for (var i of items) continue // comment
;
```

Parser = flow, babel*, typescript
