### ISSUE TITLE
Missing trailing comma in TSX arrow single type param

### ISSUE THREAD

**Issue by nicolo-ribaudo** [prettier/prettier#12076]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDATrzAXkwB4AVAGgD4AKASiKtIBMBLANypIHo3OBuEBRAQADjFbQAzslB5cEAO4AFPAhkpsqRdgCeM4QCNc2MAGsMAZWwBbOABlWUOMgBmWqXCMnzV0aacAc2QYXABXLxA4G0M4ZmY4+2woQLDsQLgAMQhcG2wYCRTkEGwwmAghEAALGBtUAHUq1ngpfzA4S3VmjmbdYrApAxAnT1wYZRNAvLcPSIArKQAPSyD0AEUwiHgZ1E9hf1xR4sNsWNQAWhgh0VwnGHrWZhgq5AAOAAZ9hU96k1Fim5wUbsFzCACOm3gEzEGhKUnOzjicUquDgENYqIm6WmSHcu0inhsrBC4QJqzgGy2Llxs2EMFODyeLyQACY6SZWKgggBhCA2HFRKQAVkqYU8ZFOGjxexA7AiAEkoAlYJYwLdxABBJWWGC6dA7TwAX0NQA)

```sh
--parser babel-ts
```

**Input:**

```tsx
let arr = <T,>() => <div></div>;
```

**Output:**

```tsx
let arr = <T>() => <div></div>;

```

**Expected behavior:**

It should print the trailing comma.

```tsx
let arr = <T,>() => <div></div>;
```

When using TSX, arrow functions with a single type argument must have a trailing comma to disambiguate it from JSX. Babel currently has a bug and parses `<T>() => <div></div>`, but TS [doesn't](https://www.typescriptlang.org/play?#code/DYUwLgBAhgTjEF4IB4AqA+AFASkelAJgJYBu6yA9MWQNxA). We are fixing the Babel bug at https://github.com/babel/babel/pull/14135.

**Comment by kachkaev** [comment]
Looks like a duplicate of https://github.com/prettier/prettier/issues/6302. You can try writing `let arr = <T,>() => <div></div>;` in `Example.tsx` and the comma will preserve.

**Comment by nicolo-ribaudo** [comment]
In the playground link it's not preserved :thinking:

**Comment by nicolo-ribaudo** [comment]
Oh I see, even if the playground parses TSX it doesn't not print as if the output file was `.tsx`.

**Comment by tianyingchun** [comment]
it seems that this issue also can be reproduce.  https://github.com/prettier/prettier/issues/12479#issuecomment-1069874705
