### ISSUE TITLE
Whitespace before function parentheses inconsistency?!

### ISSUE THREAD

**Issue by Weissrolf** [prettier/prettier#12085]
Prettier removes a whitespace here:
`async function setElevation(value) {`

and here:
`setElevation(`

But inserts a whitespace here (anonymous function, not converted to arrow function):
`function (token, hovered) {`

and here (another anonymous function):
`function () {`

Is this correct?

**Comment by Josh-Cena** [comment]
Prettier puts a space between `function` and `()` because `function` is not the name of the function, but a keyword. It's the same as `for ()` and `if ()`.

**Comment by Weissrolf** [comment]
Thank you for the explanation.
