### ISSUE TITLE
What is the rationale for throwing away semantic information by collapsing blank lines?

### ISSUE THREAD

**Issue by fenomas** [prettier/prettier#12086]
**Prettier 2.5.1**

Consider code like the following:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMLow7AA6UOOA9AFQ4B0DO1lZAvmWWBtjgCIQBzYmQo16jZmw5RpnbrgAKASwBeK9MPJVaDOkxZR2MqFyy4AEugC2AIwCuAJwFwHm0TokGjIADQgIAA4wStCYyKDoDg4QAO4KkQhhKOioMegAnmF+Ng7oYADWcDAAytZwADJKUHDIAGYpmHDZuQVFxQF5VQLIMA52TSBwtnAAJiOj5ehQAnbozgBiEA5WhMHTyCDodjAQviAAFjBWqADq+0rwmB1gcMWJF0oAbhfpG2DYe1WNDjAKuQIrOoNAYAK0wAA9il1UHAAIp2CDwIGoRp+DoOb4bGzoGxwVB7AIOKowE5KEYwfbIAAcAAY0dFGidcgENoS4N9HjU-ABHBHwP6BJKbTAAWmqo1GewccF5SmlfzmgKQ9RRA0aViUPT6auhcL5NWVwL8MBxpPJlKQACZjbklKgungIFYlYNMABWPZ2RoAFRxSRVqJAj36AEkoONYMUwESggBBcPFGDpGHIxqsVhAA)

```sh
--parser babel
```

**Input:**

```jsx
class Cat {
  /* ... */
}

class Dog {
  /* ... */
}




class Pizza {
  /* ... */
}

class Hamburger {
  /* ... */
}

```

In code like that the consecutive blank lines clearly aren't just a style preference, they're a *semantic cue* to the reader about which classes are closely related, and which aren't. 

After Prettier collapses the blank lines, the semantic meaning is lost and all classes appear equally related:

**Output:**

```jsx
class Cat {
  /* ... */
}

class Dog {
  /* ... */
}

class Pizza {
  /* ... */
}

class Hamburger {
  /* ... */
}

```

The difference is obviously trivial in a short empty snippet like this, but in large files containing lots of classes, vertical space becomes a very important, common semantic tool for the developer to convey how the file's contents are separated. (This is especially obvious if you use the "minimap" feature of modern editors - code minimaps can be great for navigating large files, but after prettier strips out all the semantic whitespace the minimap becomes largely useless.)

----

Even worse, consider the use case of Single File Components for front-end frameworks. A typical SFC file might look like this:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWW0MDKEGcZ8AHjGUiwEMVAHpWjUsxb1CHLjzj9B0eLHGTS05tTkLufAUPWiJcnZotRxmXAThSo2mwGcwAJxpYYjGtggPAWAeAAsaKABzMgBfMgAzD04yAHIAOjSxV044AHdQuA84FJd4gFcoMBgaaASICAAKAEoyYB0xMTIMtNIY0oqqmvIAIzwPZtb2zu7el2UsQIEqOHi8MpxgnVcYMvj4pFaYgBpZmyzPb18XF1RtgE8cR1IAAX8FoLIyjxwG9Mzh-ChNJgVyuFJNADcLjSHnWcAAjJMmAtXDRqtADkV8NU6HAoVA+s4oDC4QAmJEUFFooYHPDDbI4MrwfGE0gkx4AZgpZFornsdwOERwETgAFoARAwABrFmkcT3R6MEBHEAQHxDVzIUBjJK5AAKYwQmpQeBwuTwd01KuGHjw0rgMDYeC4ABkRchVjhXHBrbb7Y6sHaIpFkDBYT6QHAMMM4FRllQXXgomU8JE4AAxQIYAjVKLIEBrGAQZUgUIwDA4ADq4XgfLtcDYRupdDRd3zIKtIAi3qCettkWzHtN3pVACtXLw2MHHgBFMoQeBDr0RwMeHv5uhlOAlrBeWCVmhUGChZAADgADCrdxBvZXbVh87u4D3cSWAI7z+B9tXGguuUVQHAsaxiWRQfjQRR9qmg5IJ6I4gN6GA0KG4YqqiUSzp+26wcOEYwHSB5HieSCkiqYZ4DQwpRAAwpwMGRq4ACsJZlN6AAqdLGnBEabnAACSUDLLAbAXD4ACCglsDADzYdxMQxEAA)

```sh
--parser vue
```

**Input:**

```vue
<template>
  <div>
    <div>Some text content</div>

    <div>Some text content</div>

    <div>Some text content</div>
  </div>
</template>



<script>
import { thing } from '../somewhere'

function foo() {
  // ...
}

function bar() {
  // ...
}

export default {
  stuff: {},
}
</script>



<style>
@import url('../blah.css');

.rule1 {
  position: relative;
}

.rule2 {
  position: absolute;
}

.rule3 {
  display: inline-block;
}
</style>

```

Again, the blank lines are being used semantically - to visually separate source code in unrelated formats.

After prettier is used, the result is much harder to read - the vertical space between, say, JS and CSS is now exactly the same as the separation between two JS functions or two CSS rules. Even though the file is *semantically* divided into three clearly separate parts, prettier makes it impossible for that separation to be visually apparent.

**Output:**

```vue
<template>
  <div>
    <div>Some text content</div>

    <div>Some text content</div>

    <div>Some text content</div>
  </div>
</template>

<script>
import { thing } from "../somewhere";

function foo() {
  // ...
}

function bar() {
  // ...
}

export default {
  stuff: {},
};
</script>

<style>
@import url("../blah.css");

.rule1 {
  position: relative;
}

.rule2 {
  position: absolute;
}

.rule3 {
  display: inline-block;
}
</style>

```

**Expected behavior:**

Shouldn't prettier simply stop collapsing blank lines? 

If not, what's the rationale for stripping out semantic information this way?

**Comment by sosukesuzuki** [comment]
We have the page on website to describe rational of empty lines formatting. See https://prettier.io/docs/en/rationale.html#empty-lines. Is it an enough answer for your question?

**Comment by fenomas** [comment]
@sosukesuzuki Hi, that page is actually the source of my question. It says that prettier takes the approach of *preserving* blank lines, but then turns around and says that it *doesn't* preserve multiple consecutive blank lines. 

My question here is why the latter rule exists - why not preserve consecutive blank lines, and keep the developer's semantic intent?

**Comment by sosukesuzuki** [comment]
Thanks. I was not involved of this rationale, so I don't know the reasoning behind it. But that's probably because they simply couldn't find a rule that would satisfy more users than the current one. it is heuristics.

**Comment by fenomas** [comment]
Hmmm. I went looking through old issues, and the only discussion I could find was [this one](https://github.com/prettier/prettier/issues/1613). There seemed to be more commenters against the rule than for it.

As I read it, I guess prettier's rationale here was simply that throwing away a little bit of semantic information is okay if it keeps the style consistent? This seems like an very strange policy for a *style* formatter... 😦

**Comment by alexandernanberg** [comment]
Part of the reason why I'm using prettier is that it forces consistent spacing, I feel like if you need to separate things more you can use comments

**Comment by fenomas** [comment]
@alexandernanberg Per the linked docs, prettier specifically *doesn't* force consistent spacing with newlines. It preserves them as written, with the addition of this rule where it throws away semantic information. It would be better to just preserve them as written.
