### ISSUE TITLE
Declare and initialize multiple variables at the same line.

### ISSUE THREAD

**Issue by hyrious** [prettier/prettier#12105]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDANJgI3zAB0p0sATfOTAXkwEZ8AzEXECABxgEtoAzslDYATqIgB3AApiEQlNlSTsATyEcCo7GADWGAMrYAtnAAyvKHGQslAuJu17DXHZYDmyGKICuDkHDGBHCUlCFm2FDuPtjucABiEKLG2DB8Ucgg2D4wEOwgABYwxqgA6gW88AKuYHAG8pW8AG6VqplgAhoglvaiMNLa7ik2dv4AVgIAHgYe6ACKPhDwI6j2HK6ivZkE2MGo+VyiljClvJQwBcgAHAAM6xL2pdpcmYdwvU3WHACOi-AD3AUWQEAForCEQvlRHBfrxoQNYsMkLZVv57MZeF5fGjZnAFktrMjRhwYLtTudLkgAEwk7S8VAeADCEGMSICAgArPkfPYACq7BQotYgJp+ACSUDCsAMYCOPAAgpKDDBVOgVvYAL4aoA)

```sh
--parser babel
```

**Input:**

```jsx
let a, b, c
let d, e = 1, f
```

**Output:**

```jsx
let a, b, c;
let d,
  e = 1,
  f;

```

**Expected behavior:**

Same as input.

I know this is desired to someones' eyes. But it is verbose and annoying to force me split a short `let`-statement into 3 lines. The wrapping does not occur if there's no `=`, or in `for`-loop's initialization part. Can you also allow this kind of usage in short statements?

**Comment by Momo1631** [comment]
Hello, I would like to contribute to this issue, can you briefly explain it ?

**Comment by fisker** [comment]
I don't think we want change the output.

**Comment by Momo1631** [comment]
@fisker then can you please explain what is the issue here ?
