### ISSUE TITLE
Unstable comment in binary expression

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1210]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBZAhjAFgOgLYCWUAFADpQAEFZlVFA9AFQUAkAYgDYQDubBAHqjjEAfAF4ADDgDMADhwSKAZwLwx3DQEoKAWgqceFOACdjEYxQAmceGHiWrAV2NEA5hWxxydKs2sAHLgBPPAQYCggAMwoANyk5BRwKABUIZTg4DyxMkzNjABoKYzg8CBjM7AIlCkg8UNgKdChLbx9mY0dKSK5uCkZ6VqpLCDBHepgcACMISyCcJTAzDg4ACTgCVyxwnUHqbiJh7nnFiGWATQoAagp95p4cIigTNY2tzVbtPWsYlXgAfUiEAg8GMf2yrxg+VaEihUHeUBA+RAEH8MAI0CUyFA6FMPAACjiEJiUOgYhACJZESB0EoYMhIugOEo4EjJsZ0GAANY2ADK-g5bmQMA6LJAwzA9MZzKRRGZxhgePZrjw6ElTNFACslPwAELsrm89ChAAyRDgaulyMcMH81oATEKRUj+cY5cgQJN0JMglwEc6XLAAOoU7DIWQwkD+MzMwPs-zuqNwOXlKnFACOjgIxUV6GVqqQDPVSOZhEdjlFKigrg4cAAio5geaC1LRTAvcHLKGkHakcL0AQOG4AMIQOr5kBQaDmpGOZnJL3EwvMgC+y6AA)

**Input:**
```jsx
Math.min(
  (
    /* $FlowFixMe(>=0.38.0 site=www) - Flow error detected during the
     * deployment of v0.38.0. To see the error, remove this comment and
     * run flow */
    document.body.scrollHeight -
    (window.scrollY + window.innerHeight)
  ) - devsite_footer_height,
  0,
)

```

**Output:**
```jsx
Math.min(
  /* $FlowFixMe(>=0.38.0 site=www) - Flow error detected during the
     * deployment of v0.38.0. To see the error, remove this comment and
     * run flow */
  document.body.scrollHeight -
  (window.scrollY + window.innerHeight) -
    devsite_footer_height,
  0
);

```

**Second Output:**
```jsx
Math.min(
  /* $FlowFixMe(>=0.38.0 site=www) - Flow error detected during the
     * deployment of v0.38.0. To see the error, remove this comment and
     * run flow */
  document.body.scrollHeight -
    (window.scrollY + window.innerHeight) -
    devsite_footer_height,
  0
);

```

**Comment by evilebottnawi** [comment]
Other problem example:
```js
const topOfDescriptionBox =
      Layout.window.width +          // Images are 1:1 aspect ratio, full screen width
      Layout.headerHeight;
```
