### ISSUE TITLE
Vue components matching native tags names, won't keep sensitivity

### ISSUE THREAD

**Issue by iamandrewluca** [prettier/prettier#12116]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAagVzhyAWwAdoEYBnAHSkigpgwBEBLAQwBsIBzDAXgzAAvjToMMAIRwwY0foJG1o4gCoALOK0495w0csYSYUXYv31GamIQ7yAyjABOLKNwB0jtgHca58QFkATwBBYmJdXxgiUihyCiRBZnYubgAaSWlZKHT1TWSedKMTIVTI+BIONngEqxsAAxoMJuaAHgATFgA3AD5G5v6WrRTek37mqhgWqRlobpU4BhbUaayRsdbUIZ419YwW3K3uHfWJqeM5hcnl8771pYP8o9uNjp7IhqghEFSQCGIYFjKZCgNiORwQLwABVBCAoyBAnC8bECcJ+ACNPGAANZwGB2NiEOAAGRccGQADNOBQ4OjMTi8cQ2GAXNxkE48D84IQ0XA2m1eUS2K4cGxuHAAGIQRyEKoA1zwtjSCDfEC1DgAdTULHgFEZYDgdlh2q62sC8LAFFRIBc1McMEhnm4MopVJpIAAVhQAB52FkcOAARRwEHgLo41J+jMctvhaLYPI4KuIzlg6pYbRgamQAA4AAyR8HU9WeYjw5MLOCOTpkn4AR2D8AdfzhKDYFAAtLFebyVY44PWWH2HaLnUhKeG3dTCCw2Y4OSAKH7Aw2yWPXT8YPG0xms0gAEwbzwsDgsgDCEEIo5ACwArCqcNSVPGW+OIyBOngAJJQfmwOxgZx-mCH8HECf0w2pIQhCAA)

```sh
--parser babel
```

**Input:**

```jsx
// Vue components
const Dialog = {}
const Button = {}
const TheDialog = {}
const Btn = {}

const html = String.raw

const MyApp = {
	components: { Dialog, Button, TheDialog, Btn },
	template: html`
      <div>
        <Dialog>
        	<Button>Test</Button>
        </Dialog>
        <TheDialog>
        	<Btn>Test</Btn>
        </TheDialog>
      </div>
	`
}
```

**Output:**

```jsx
// Vue components
const Dialog = {};
const Button = {};
const TheDialog = {};
const Btn = {};

const html = String.raw;

const MyApp = {
  components: { Dialog, Button, TheDialog, Btn },
  template: html`
    <div>
      <dialog>
        <button>Test</button>
      </dialog>
      <TheDialog>
        <Btn>Test</Btn>
      </TheDialog>
    </div>
  `,
};

```

**Expected behaviour:**

Keep `Dialog` and `Button` components case sensitivity.

From what I see, prettier will format all tags that are native tags. Because it does not have the `components` context

Is there any way to override this?

https://github.com/prettier/prettier/pull/5101/files#diff-1fd8eef290c732d92e96da3d62e43667b283f1d6a41b040736c9a62ec043c452R37

**Comment by fisker** [comment]
I don't think this is going to be easy to fix, actually I don't think this is bug, you used html tag , in html <dialog> is same as <Dialog>, why don't you rename you component to avoid confusion?

**Comment by fisker** [comment]
One word component name is considered anti-pattern anyway.

**Comment by fisker** [comment]
https://eslint.vuejs.org/rules/multi-word-component-names.html#vue-multi-word-component-names

**Comment by iamandrewluca** [comment]
> I don't think this is going to be easy to fix, actually I don't think this is bug, you used html tag , in html is same as , why don't you rename you component to avoid confusion?

Yes, I think we will rename the components using two words. e.g. `App*`

> One word component name is considered anti-pattern anyway.

Good point!

Thanks!

**Comment by fisker** [comment]
I always prefix my components with a short project code.

```js
import Dialog from "./dialog.vue"

// ...
components: {
'foo-dialog': Dialog,
// ...
}

```
