### ISSUE TITLE
Default Markdown list formatting is not spec-compliant

### ISSUE THREAD

**Issue by oliversalzburg** [prettier/prettier#12110]
This issue possibly duplicates #3679 and #5019.

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAS3QG0wazl0wGcYAdKddDAd0xgAtLqMSBXAIxZq3gFsSlSgEYAdFmKFiZHunHp6TOQo7cq1BQziDKIADQgIABxiZoJZKACGAJ1sRaABTsJLKazlrWAnpcOcttZghDAAytb8cAAymFBwyABmniRwAUEhcOHGwXEA5sgwtuxpIDqccAAmlVXR1lB57NZ5cABiELb81jBmDcgg1uwwEAYgjDD8OADqjNokOWBwYW4MmABuDD79YCT+IHGptjBOQXldSSmlAFYkAB5h+ThwAIrsEPAXOKmGObaH-V1bPhKo4oKNjLY4jApphKkxkAAOAAMPwcqSmQWM-QhcEOawShgAjm94CcTO4BiRUPEqlVRrY4MTMAyTs1zkhkl9Sql+JhCsVuY8XiSEhzLoYYNZODC4YxkAAmCVBTB4BoAYQg-HZZRIAFZRuxUgAVKXuTnfEBrEoASSgNVgYTAkNMAEE7WEYD4np8LTdbgAhDKhCJRWLxH1wAC+kaAA)

```sh
--parser markdown
```

**Input:**

```markdown
- i like list
  - with
  - sub
  - items

1. i like list
   1. with
   1. sub
   1. items

```

**Output:**

```markdown
- i like list
  - with
  - sub
  - items

1. i like list
   1. with
   1. sub
   1. items

```

**Expected behavior:**

```markdown
- i like list
    - with
    - sub
    - items

1. i like list
    1. with
    1. sub
    1. items

```

I'm working on some documentation, which is built with MkDocs, which uses the python-markdown library, which [requires list item bodies to be indented by 4 spaces, per the spec](https://python-markdown.github.io/#differences). They point to this [part of the spec](https://daringfireball.net/projects/markdown/syntax#list):

> List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab

Prettiers default auto-formatting in this scenario breaks nested lists, as they are only indented with 2 spaces. I would argue, that the configured tab width in Prettier should not have an impact here, as the 4 space (or 1 tab) indentation is explicit in the spec.

To correct this behavior, I first tried to just use [`--tab-width=4`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAS3QG0wazl0wGcYAdKddDAd0xgAtLqMSBXAIxZq3gFsSlSgEYAdFmKFiZHunHp6TOQo7cq1BQziDKIADQgIABxiZoJZKACGAJ1sRaABTsJLKazlrWAnpcOcttZghDAAytb8cAAymFBwyABmniRwAUEhcOHGwXEA5sgwtuxpIDqccAAmlVXR1lB57NZ5cABiELb81jBmDcgg1uwwEAYgjDD8OADqjNokOWBwYW4MmABuDD79YCT+IHGptjBOQXldSSmlAFYkAB5h+ThwAIrsEPAXOKmGObaH-V1bPhKo4oKNjLY4jApphKkxkAAOAAMPwcqSmQWM-QhcEOawShgAjm94CcTO4BiRUPEqlVRrY4MTMAyTs1zkhkl9Sql+JhCsVuY8XiSEhzLoYYNZODC4YxkAAWCVBTB4BoAYQg-HZZRIAFZRuxUgAVKXuTnfEBrEoASSgNVgYTAkNMAEE7WEYD4np8LTdbgAhDKhCJRWLxH1wAC+kaAA), which fixes the MkDocs rendering of the list.

But now the output is very confusing to me. Why is there indentation added to the list item itself, but only for the unordered list? (Likely discussed in #5019) Is this a bug? Is this even the right way to resolve this?

**Comment by kachkaev** [comment]
👋 @oliversalzburg could you please include a code snippet to the _Expected behavior_ section?

**Comment by oliversalzburg** [comment]
@kachkaev Apologies. I lost that bit during editing.

**Comment by duailibe** [comment]
Hi @oliversalzburg 

I think it's important to clear out that Prettier tries to follow the CommonMark spec as much as possible. And that spec does not enforce the 4-space rule (and it's explained in the [section 5.2.1 - Motivation](https://spec.commonmark.org/0.30/#motivation)). So that is why Prettier has a different behavior than Gruber's spec.

As for your other question, it's pretty much what's discussed in #4114

**Comment by oliversalzburg** [comment]
Thanks a lot for the clarification and pointing out the other ticket. I guess that solves everything.
