### ISSUE TITLE
Incorrectly strips brackets around new objects, produces invalid code

### ISSUE THREAD

**Issue by mangelozzi** [prettier/prettier#12117]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAHAhjACylwFs5MBeTACijgHdMBVAJQBlqBXAJwBsBKfgDo8hYmQDcIADQgI2GAEt0yULm7cI9AArqEaZCFy96uAJ4HZAI264wAazgwAyqThtFdZADNjaONa2Dk7OeGCeAObIMNycASBwJFZwACYpqWy4UBGcuBFwAGIQ3CT4StmGuJwwEDIgBDAkvADqBIrwaGFwzvrtigBu7WaGYGiWIJ7+3DDathGlPn7xAFZoAB7OkbxwAIqcEPCLvP6yeNxThla4ybx12NyeMM2KKYTIABwADKea-s222EM9zgU36cDqAEd9vBZvIDChcGgALR0VKpOrcOBQxSY2Z5BZIXzHeL+EiKaKxElbXbQ8GEpayGDXZ6vAjIABMjNsil4kQAwhASASEmgAKx1Tj+AAq13hRJOIH6cQAklB0rBnGAHgoAIJq5wwMzbI7+AC+pqAA)

```sh
--parser babel
```

**Input:**

```jsx
const pathname = (new URL(url)).pathname;
```

**Output:**

```jsx
const pathname = new URL(url).pathname;

```

**Expected behavior:**
Not to strip the brackets. Without the brackets its invalid:

> VM1420:1 Uncaught TypeError: Failed to construct 'URL': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
>    at <anonymous>:1:18

**Comment by kachkaev** [comment]
What is your dev environment?

I just opened `node` REPL and typed both variants – they worked. Same in Chrome / FF console.


<img width="594" alt="Screenshot 2022-01-21 at 19 00 01" src="https://user-images.githubusercontent.com/608862/150584920-023d5851-5d5f-4c78-8757-904d8b5c093e.png">
<img width="556" alt="Screenshot 2022-01-21 at 19 00 25" src="https://user-images.githubusercontent.com/608862/150584930-d75a83f0-f16f-4dfb-aa03-a6e7b6295f17.png">
<img width="490" alt="Screenshot 2022-01-21 at 19 00 59" src="https://user-images.githubusercontent.com/608862/150584938-2613dcdd-7c0d-4ca2-86b5-da815ee7385f.png">
