### ISSUE TITLE
Angle bracket of opening HTML tag incorrectly placed on next line

### ISSUE THREAD

**Issue by nwalters512** [prettier/prettier#12115]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeMBXAzjCBbAWjgBs48EYACSAJxrjBgF4AdEAMwENis42A+AOoALBJWhxKAIwgATAJ6U4ADzg0YWSp0rsINMJOhbKvSFFnS58llFQB6TDnxFS5WPxs3UsgJYA3LRgYGh8pDHhWEGCMPhBxGFEaSIBGARExCUsFJVV1TW1dfUMoY1NoCxkFLztfP34QABoQCAAHGB9oLGRQTjoIAHcABV6ELpRufs55LqapGk4wAGs4GABlTnIAGR8oOGQuHjhZ+aWV1ZaFnYBzZGijkDIpOFlZZ83OKCuMTiu4ADE9HhOEFrsgQJxwhBGiBhDA8MQRD54FgLgZVqMkf4kfIwWAsDMQDteOpBvMrkD9txeE0AFZYZSra6kACKGAg8EphyaFxoxLBsPh0JaIVggh8sgSyAAHAAGbk0CC8QTzFpg4VwYl+PZNACObPgpNaY3BWAIu2ez2h9D1PnopJ+FKQB2pIF4eB8txoMSaWCZcFZ7L2Tqp9xgnCkYolwmQACYmsFOD5iNcAML4R0PLAAVmh2DgABVw2Nnfc-DEAJLmCirMAhNoAQXMqxg8lInN4AF8O0A)

```sh
# Options (if any):
--parser html
```

**Input:**

```html
<custom-element correct="false">When one body exerts a force on a second body
</custom-element>

<div attribute="true" other="1">When one body exerts a force on a second body
</div>
```

**Output:**

```html
<custom-element correct="false"
  >When one body exerts a force on a second body
</custom-element>

<div attribute="true" other="1">
  When one body exerts a force on a second body
</div>

```

**Expected behavior:**

I would expect the closing angle bracket on the `<custom-element>` tag to be on the same line as the opening `<custom-element`:

```html
<custom-element correct="false">
  When one body exerts a force on a second body
</custom-element>

<div attribute="true" other="1">
  When one body exerts a force on a second body
</div>

```

**Comment by duailibe** [comment]
Hi @nwalters512. This is the correct behavior as `>When` and `>\nWhen` is not the same thing in HTML, so we can't make this transformation automatically. You can read more about this [here](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting).

If this transformation is safe in your environment, you can set [`htmlSpaceSensitivity`](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) to `"ignore"`:

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeMBXAzjCBbAWjgBs48EYACSAJxrjBgF4AdEAMwENis42A+AOoALBJWhxKAIwgATAJ6U4ADzg0YWSp0rsINMJOhbKvSFFnS58llFQB6TDnxFS5WPxs3UsgJYA3LRgYGh8pDHhWEGCMPhBxGFEaSIBGARExCUsFJVV1TW1dfUMoY1NoCxkFLztfP34QABoQCAAHGB9oLGRQTjoIAHcABV6ELpRufs55LqapGk4wAGs4GABlTnIAGR8oOGQuHjhZ+aWV1ZaFnYBzZGijkDIpOFlZZ83OKCuMTiu4ADE9HhOEFrsgQJxwhBGiBhDA8MQRD54FgLgZVqMkf4kfIwT4rlA9HsmjteOpBvMrkD9txeE0AFZYZSra6kACKGAg8GphyaFxopLBsPh0JaIVggh8sgSyAAHAAGXk0CC8QTzFpg0VwUl+IkgACOHPg5NaY3BWAIu2ez2h9ANPno5J+VKQB1pIF4eB8txoMSaWBZcHZnL2Lpp9xgnCkEqlwmQACYmsFOD5iNcAML4Z0PLAAVmh2DgABVI2NXfc-DEAJLmCirMAhNoAQXMqxg8lI3N4AF8u0A)

```sh
--parser html
--html-whitespace-sensitivity ignore
```

**Input:**

```html
<custom-element correct="false">When one body exerts a force on a second body
</custom-element>

<div attribute="true" other="1">When one body exerts a force on a second body
</div>
```

**Output:**

```html
<custom-element correct="false">
  When one body exerts a force on a second body
</custom-element>

<div attribute="true" other="1">
  When one body exerts a force on a second body
</div>

```
