### ISSUE TITLE
incorrectly inserted semi when `semi: false`

### ISSUE THREAD

**Issue by aladdin-add** [prettier/prettier#12137]
**Prettier 2.3.2** (update:  I run into it when using prettier v2.5.1, 2.3.2 was the from the demo page.)

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgCnRCBKYAHSgAISB6ckgZwgFs4TI6HZiyBtAXQDoAHAK7UAFjwCGfPgBsAnpgBGYgE54A3MQC+IADQgIfGKmjVkoZUogB3AArKEJlGKmWxMk7vlKxYANZwYAMp83qhQAObIMEoCcLpwdPJwACZJyQAyYuECYmFwAGIQSnRiMIbhyCBiAjAQOiDCMHRSAOrCqPDUwWBwAfbtqABu7TIVYNTuaFDUcEow1l5hxcjoTtO6AFbUAB4AQl6+-gFiDGmhcMursSCbWwGhYVJwAIoCEPAXUmsgwUrTShWKRJSOp8JShGDNVBJGDCZAADgADLpQRBps0vHwKqC4H8BuddABHV7web6ByVagAWigcGSyTqSjgRNQjPmOSWSBWnyu0zoqA+X2o90eLze505l10MDE8kh0NhSAATFKvKgpPcAML0DkgHEAVjqQjgABUZQ4uV8BjEAJJQVKwAJgMEGACCdoCMBkjwFcA0GiAA)

```sh
--parser babel
--no-semi
```

**Input:**

```jsx
if(foo){
  // some comment
  [].push.apply(bar);
}
```

**Output:**

```jsx
if (foo) {
  // some comment
  ;[].push.apply(bar)
}

```

**Expected behavior:**
no semi inserted. 

I was assuming the semi was inserted as an ASI issue, but in this case it's not.

**Comment by fisker** [comment]
This works as intended. See https://prettier.io/docs/en/rationale.html#semicolons

**Comment by aladdin-add** [comment]
missed it somehow, thanks! However, it's conflicted with the eslint rule [no-extra-semi](https://eslint.org/docs/rules/no-extra-semi) (enabled in `eslint:recommended`), a workaround is to disable the rule.

**Comment by fisker** [comment]
Yes, you should disable that rule.

**Comment by kachkaev** [comment]
@aladdin-add you can add [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier) to your ESLint config, which will disable all conflicting rules.
