### ISSUE TITLE
Unnecessary `this` is added to shorthand properties in Angular templates

### ISSUE THREAD

**Issue by th0r** [prettier/prettier#12138]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeKBzAtJWBDASyjgCcACAKkwBU4BbABwBs94B5AVxibhgF4AOiADOEOnGqMmAbjK54ADxhIywPAwYBfIQD5UAekw5oMQsRI6QAGhAQGMAtGHJQeEiQgB3AApuEzlDwmTzwAT2cbACMSPDAAa14AZTxxABkiOGQAMyDhOCiY+KSGWKIMZBgSDnyQeki4ABMGxtS8TA48DDgAMQgSOlYHTGQQPC4IaxAACxg6JgB1KYJ4YRKwOET-ZYIAN2XQkbBhCJAiPJIYbxiMAezcmoArYQVEsp4ARQ4IeDumPJsSiRziM2hgOCwSJMGCQiDB5gQGjApsgABwABgBHjy8xiDBG0Lg5x2mRsAEcvvArnYAqNhFhiI1GpMSHByQQWVdOrckDk-jU8nQCBUqvy3nBPt9Mjz7jZTJF4YjkUgAEyymIEJhlADCYm5tWEAFZJhw8tQ8JEArz-iAdtUAJJQZqwRJgGH2ACCjsSMFCPF+1qeCgAQoUEjBkmkMv64JpNEA)

```sh
--parser angular
```

**Input:**

```html
<ng-container *ngTemplateOutlet="someTmpl; context: {app}"></ng-container>
```

**Output:**

```html
<ng-container
  *ngTemplateOutlet="someTmpl; context: { app: this.app }"
></ng-container>

```

**Expected behavior:**
```html
<ng-container *ngTemplateOutlet="someTmpl; context: {app}"></ng-container>
```

**Comment by fisker** [comment]
https://github.com/ikatyang/angular-estree-parser/pull/222

**Comment by fisker** [comment]
I'm moving this to 2.7 milestone, the upstream PR hasn't reviewed.
