### ISSUE TITLE
Ugly formatting for Angular unit tests (waitForAsync)

### ISSUE THREAD

**Issue by yurakhomitsky** [prettier/prettier#12142]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAjOAzCAnOAUQEMwALACgHdiBLGAMXwEEBnATyjAooEpUAvAD5UwADpR06ALZxWrYgHM5AZTh4AbrTBwVMAK4ZBoiVKnEAJhaSoAVsVbTaUOADowBYvBUAHdhQBySwsA3lMpAF8Abglw9AAVORgAITgLd2hsWkV9AkTWGGdFAFkIC30AGzgKcUkzVAs4MAriPC9aaFYbAG0AXQAaOKlaaR98GC7UbqGzACUIfXg8fMKoErLKtyp6MnnFuQo+3kG6+tRirwBJSChS8qqTs-QLmAARWmIKiHX7uEengASMBgPgAwhVaAgYCsindNjNUAMET48BAtI08JNpqd6sBUCi0bRGjZinIFMo1JptH9UPpWHAAGqffRwGyyeRKVTqLQ6PSGVARBFInHoVjkODSBw9AByAHkAPqEWazWWzFTylSggGEYrMfqoUEAVRU8VlxUVABkdYRpfF1ZrtbrekMImEca40eo8ES4HCqhQXtdoH6abUzgRpJ6bGGno1mq12p0eoGbsKnqg4AAPMZ4CbJq6phERf5mYLRhHoOMtNqFJNTUpgADWKegoIgo2gULTTyzObz9YgTZbUDbHZcsGdIoFLrdZgyo1oVVHY3HEz4MTqrokvCiIH6IAgPlrUFYyFArVRVAACq0EKeUJ8aOxT-uMG0m3AYCpiLILc44Mg2CfPSr7vo2n6+KQRTIDAeAsvuEpYFYaQWsQaz6JyTB4JKwLQQ+iwQHuIBkDA0gVAA6mQ9ByD4pC6He9C0FoMDsMg4DyERzj0rmV5tIokqAcBfwgLYrCZioRRVAAivoEDwIJFQgSAtGYuobEsT4cgeLQR5ESizgwORRIwGQyAAIwACwAAz7gS9LkW0PhsSicjcgB+4AI6yfAvGHveIAOAAtC4aRpERBBebQBC8UoAlIEBinCfSTgwXBSWSXAMlyQBSCwfBIAwMQGBGRYJnIAATPusF0BCayjnFIBQJ2RF0nA8RFfeCVKRoLKXFAjSwCo2lHsw-V6OwVQKfSEQREAA)

```sh
# Options (if any):
{
  "singleQuote": true,
  "printWidth": 140,
  "tabWidth": 2,
  "useTabs": false,
  "trailingComma": "none",
  "bracketSpacing": true,
  "semi": true,
  "endOfLine": "auto",
  "arrowParens": "always"
}

```

**Input:**

```jsx
  beforeEach(waitForAsync(() => {
    messagesServiceStub = {
      add: jasmine.createSpy('add')
    };

    TestBed.configureTestingModule({
      declarations: [],
      imports: [
        RouterTestingModule.withRoutes([]),
        MatIconModule,
        MatDialogModule,
        HttpClientTestingModule
      ],
      providers: [
        { provide: MessageService, useValue: messagesServiceStub }
      ],
      schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA]
    })
    .overrideModule(MatIconModule, {
      remove: {
        declarations: [MatIcon],
        exports: [MatIcon]
      },
      add: {
        declarations: [MockMatIconComponent],
        exports: [MockMatIconComponent]
      }
    })
    .compileComponents();
  })
);
```

**Output:**

```jsx
beforeEach(
  waitForAsync(() => {
    messagesServiceStub = {
      add: jasmine.createSpy('add')
    };

    TestBed.configureTestingModule({
      declarations: [],
      imports: [RouterTestingModule.withRoutes([]), MatIconModule, MatDialogModule, HttpClientTestingModule],
      providers: [{ provide: MessageService, useValue: messagesServiceStub }],
      schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA]
    })
      .overrideModule(MatIconModule, {
        remove: {
          declarations: [MatIcon],
          exports: [MatIcon]
        },
        add: {
          declarations: [MockMatIconComponent],
          exports: [MockMatIconComponent]
        }
      })
      .compileComponents();
  })
);

```

**Expected behavior:**
I would expect waitForAsync not to be wrapped on the next line

In this case, waitForAsync should be as in input

**Comment by fisker** [comment]
Logic should be here https://github.com/prettier/prettier/blob/6ccc462409f7cea4df7fcbe8cf9ef92cfbd5a7c9/src/language-js/utils.js#L515

**Comment by fisker** [comment]
This is strange, [tests](https://github.com/prettier/prettier/blob/4dd195099e533cfa3ac372119eb796c8114b3246/tests/format/js/test-declarations/__snapshots__/jsfmt.spec.js.snap#L312) doesn't format as the playground. Need investigation.

**Comment by duailibe** [comment]
This was fixed in https://github.com/prettier/prettier/commit/846069b6c7692bd7ee34ed0eece393fd72e8f804, but it's not released it yet.

Will be fixed in the next release

**Comment by yurakhomitsky** [comment]
@duailibe Do you happen to know what is the date for the next release?

**Comment by duailibe** [comment]
@yurakhomitsky We don't have a date yet, but should be in a few weeks.

**Comment by karanodedra20** [comment]
@duailibe is it released? Because I am facing this issue in VS Code.

**Comment by duailibe** [comment]
@karanodedra20 yes, since 2.6.0. Check which version is being used in VSCode

**Comment by karanodedra20** [comment]
@duailibe  it is v9.9.0, facing issues in VS Code but works fine in Intellij, not sure if there are any other settings that I need to change in VSC.

**Comment by duailibe** [comment]
@karanodedra20 v9.9.0 is probably the version of the VSCode plugin, not which version of Prettier the plugin is using.
