### ISSUE TITLE
Is prettier a JSON formatter?

### ISSUE THREAD

**Issue by btoueg** [prettier/prettier#12141]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEaQEMeZLYgACuAzuQJYDmUuARgDZwD65kADnOUmmgHocGAL4gANCAicYVaOWShcAJ2UQA7gAUVCBSlxN1uAJ4LJDZbjABrODADKuALZwAMlShxkAMwPk45pY2dvacVh40yDDKAK4BIHBODHAAJimprrhQNDG4NHAAYhDKTrgwstnIeDEwEBIgABYwTkwA6g1U8ORhYHD2up1UAG6dxlVglPUe-sowmpY0pT5+8QBW5AAe9hEsAIoxEPDLTP6SYcozVevQ9ZzKHjCtVCkwDcgAHAAMZ2r+rZacKp3HhwZRDLySACOB3g82kejw5AAtJ5Uql6so4NCqJj5nklkhfCd4v4nFQorESTs4PtDl5CStJDBGE8Xm8kAAmJmWKhMCIAYQgTgJCXIAFZ6jF-AAVRh6ImnEBDOIASSg6Vg9jA9xkAEF1fYYMYWMd-CIREA)

```sh
--parser json
```

**Input:**

```jsonc
{
 "a" : "@assignable_scopes:\/"
}
```

**Output:**

```jsonc
{
  "a": "@assignable_scopes:/"
}

```

**Expected behavior:**

Prettier is breaking my JSON, I would expect it to return

**Output:**

```jsonc
{
  "a": "@assignable_scopes:\/"
}

**Comment by fisker** [comment]
Can  you explain how it breaks your case?

**Comment by btoueg** [comment]
Prettier drops a `\` in the output

**Comment by btoueg** [comment]
I just tested, and apparently both JSON output are interpreted the same way

![image](https://user-images.githubusercontent.com/498190/150958399-633371d0-0495-4986-b945-a4c8bf58f8fe.png)

**Comment by fisker** [comment]
Actually, your first JSON.parser should use `\\`, you are parsing the same string. But yes, they are the same.

**Comment by fisker** [comment]
```test
JSON.parse(`"/"`)
'/'
JSON.parse(`"\/"`)
'/'
JSON.parse(`"\\/"`)
'/'
JSON.parse(`"\\\/"`)
'/'
```
