### ISSUE TITLE
formatting: params are not dense 

### ISSUE THREAD

**Issue by ayroblu** [prettier/prettier#12148]
Hey! Feel free to mark as a duplicate if there's a similar issue, I wasn't sure how to search for it. I was just feeling like this is suboptimal, and could be improved! Thanks for all the hard work on Prettier!

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdH0G0C6A6AWwEMAHACgB0pMbUysrbawAbASwRgEkATAGkZNMwQUMwBXAM5wATklTBUkFhHEy+qKEQJxUAXwHUx6A6KY4AlKgC8APjqLWHWLw1adG5RDlKIKtfoWZphBUCB8IBAkMGzQksigRDIyEADuAApJCPEoRCypRACe8REARjJEYADWcDAAytpwADJsUHDIAGZ50mUV1bV1JJWtAObIMDLicBFwBKVwPDwLTURQI+JEI3AAYt7EMDFryCBE4jAQ4SAAFjAELADqV2zwkkNgcHXZz2wAbs+FxzAkhKIFa0hkMHSFRGxE63WmIAAVpIAB51UYsOAARXEEHgcJYPRAQxk4OOpSI8xYlxIMlaMHubB4MCuyAAHAAGCK0iDSe4VEjHWlwcE-doRACOuPgUKiOROkgAtG0FgtLjI4FK2BqoZtYUguoSEdICGxxpNjRjsdL2gb4REYJTGczWUgAEwOipsdhrADCEAI+pAIoArJcpHAACqUnKGok-KZcKBLWB1MB06IAQWTdRghUxBOkej0QA)

```sh
--parser babel
```

**Input:**

```jsx
        [].map(
          ([
            clientId,
            {
              user: { colour, name },
            },
          ]) => ({ clientId, name, color: colour })
        )

```

**Output:**

```jsx
[].map(
  ([
    clientId,
    {
      user: { colour, name },
    },
  ]) => ({ clientId, name, color: colour })
);

```

**Expected behavior:**
```jsx
[].map(
  ([clientId, { user: { colour, name } }]) =>
    ({ clientId, name, color: colour })
);

```

**Comment by pushkine** [comment]
duplicate #5939
