### ISSUE TITLE
// eslint-disable-line should not be moved

### ISSUE THREAD

**Issue by vertti** [prettier/prettier#12170]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB3AFgSwDZwAQAUMATgK5wCUeweA9LXnAM7aawC0AJpkwIYBGudqyj4oEdpChMYvDlO4xM0ADpQ8eXql6YYeMLxhh0AVQAOBKvUYs2MLjwFCRYiVp322wiBDNqAvmogADQgvkrQTMigvMTEEKgACrEIUSi82NoAnlGh-MS8YADWcDAAyrwAtnAAMmxwyABmGUxweQXFpWVmhWwA5sgk5KFwlfxwnJwTNXJ9pLx9cABiEMSVhkpQA+mkMBAhIOgwldgA6ljwTD1gcGWpupgAbrpZyOBMuSBsrcQwiQV9dZNFptEAAKyYAA8yv1cABFUgQeDA7CtUI9Yg-N78ARwbAHMzEOynTCcGDoZAADgADOj4q1TgUzG9Ccw4MRHg1QgBHRHwf6+NIgXhMdiiCYTA7EOC8zDS-4LIFIZqo0GtSqYQZkNWwuAIpENZUg0KyfgkskUpAAJhNBRw-QAwhBKkqQMwAKwHUitAAqAjSKrRIEe5AAklAprAymAiWYYABBCNlGBZXAo1r+fxAA)

```sh
--parser babel
```

**Input:**

```jsx
while (true) { // eslint-disable-line no-constant-condition
  await catchUp()
}

```

**Output:**

```jsx
while (true) {
  // eslint-disable-line no-constant-condition
  await catchUp();
}

```

**Expected behavior:**
`// eslint-disable-line` is always targeted to the line it is on, so moving it while formatting will often cause on issue where the code that causes the eslint warning moves to a different line than the comment that disables that warning.

**Comment by duailibe** [comment]
It's recommended to use `// eslint-disable-next-line` instead:

```js
// eslint-disable-next-line no-constant-condition
while (true) {
  await catchUp()
}
```

See https://prettier.io/docs/en/rationale.html#comments because it's difficult to keep those kinds of comments at the original line.
