### ISSUE TITLE
Remove color support in `standalone` build?

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#12181]
After I merge #12162, there is still an old version of `chalk` used by `@babel/code-frame` -> `@babel/highlight`, in theory it should be possible to add colors in the error message, because it can also run in Node.js.

Since it's not very easy to remove, I want to discuss with the team first.

Do we agree to remove color support in `stanalone` build? I'm 👍 to remove it.

**Comment by duailibe** [comment]
I'm 👍 for removing as well

**Comment by fisker** [comment]
@sosukesuzuki Agree?

**Comment by fisker** [comment]
Update there is another copy used by `vnopts`, see #12182

**Comment by sosukesuzuki** [comment]
I'm :+1:
