### ISSUE TITLE
Wrap absurdly long type unions

### ISSUE THREAD

**Issue by pushkine** [prettier/prettier#12207]
Typescript type unions with over a dozen members are never meant to be readable, it's counter productive for prettier to add line breaks between each member.

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwDkIATUgXjwB88BBAIwEsHmoBzAGzgBC2AIZgA1nHiUA4gjjY2YJtm4BXALYIYAZ07L1emDAUtV8TgOHY4AMSjLuFtlErPHjAbwjiLEVS4AZNgAzSTZNXUYAYWhtGAAFK2EDaNjjYWd8RgARYRhhAFEoDU5c-IBlY1UwLLwy4QBVKDZoUvk2ADc4AEkoDDNOAsxsZRFCQeGmbW02bigJjBHp2agAeQwFpcIoME2mAHcM2qHFgWcrccYT7E9vMU2BCDQH62F7q+Go4V5eTa+4v5ebSqax-aAwZyqUgfRY2NhwXiUTY2HABCAQDYw7DSbB+TF4a7dYKbXrUZ5YgKSTZBY7DNEYzYAWVEuKZeTAAAsmZIOVQvj9NolrPMsYkYFysQAlYQ8aEE4aSuChYVgOXXRUkPKbRUwEEi+WLSrYaq0xYAFWwlwN2AthFuPixZtUGH4mzNxDVwyaF02TW0wlCmwA6hy2K6sQBNeGIzhwhFIxhxxFi2PRygANW+UNT8e0ZGScATeCTlG0TSgBaLcPDxZwcBW3Xg6jssbrDabzLArMTbbmjbg6kqeUUres7YH7pInFkUHaYEieG66hd-fUMSgAMYS5XHZZEE4294q8ZPKoB+XR6bk7lpPQB6b683i6bRRKW5faHg2CgURE5nfA4tgBza9lAjJnsBh73gOnbds+MF7gATNB6jgUWq5DhCuzAUaJooRaRz4SIbAwEwvBsMIC6rteKFNC0+qrg02hygEwgsAinBBKEEKaJxIRhJo2RKnxMCPBAvyMDSAiEP+eBSTJcBGiJUQclYIk2F4WqSSRvS1DSSmSd43ycLB+6MCe+RBE+FnCPmmiZrw2bmaelBOtgLAQMEbDaBKeBCloHJwDMABehYznODgaFoC5io85J+Xk3TULAnBijSqV5KZGUwKs2DZWKvlitKsrZYqyoIKqpVBbUYrlORlWMLVVQ1NlTounKYptfwuEtY1eQ0X1MBBmGRYFdlHLlHA3CaCljXWK4YB5HABQAI6pfNihLVxAkdRti3wANeAAIqTbwxKMIqqqdPInDlCseQgnKBEkY8-hFs9MCro+tQfcee6cL9HYuQDxGfVeHoAx6ozCFa16WNYQF4NeOJ4pDJCHh9aM9FAypY1ljDXmQcBdHlBMekKyRY-5+rXmNZMkPExhY2V8gVU9Hp1Yo7MkB9qwsAAVnAvVIx6XVykxcDSF4LCcBLKPOrLzF2eLzF03gEuKhWvGMJmCjCAtnC6xRs14Om3m-kthvefEqgsPVVvaIqcQKDUhacCGrNRLwwiqMxADcAA6UAgAANCAGIQrEyCgFYuL7NT2jICA3yHIQidhywIjiJI5QFkEs7IME3zMRnWcSDA5QYKIbjIFUcBhwO7GUNQlCsTwqjCNwtg4OoeQQjwSc+zAEChyAHIwOovAhiRQVV6qk0biRnQkYQSfzunIDOMxuDxCI03CIXxf1yA-PaGgd08PwR2qBA8CH7wJcgFX2Db0nLBsQio+LJkw2UOKyAAA4AAMYdFgQGYkGEQGAk6LCCvILoo8Vo33gLvDEicUCUQALSzkLIWUe1gkFsGsLvTuvd76P2YuoNgtdjTHxmJfOA19b5wHIcffILBf7-yQIhMO6QwxuBiOoMhKAgoAFZR6+zgGaNi6Ci4P2Ph0KEt5YDlC7GwDApEXCVEIPwVhABfPRQA)
**Input:**

```jsx
export type Node = | Abi | AngleBracketedGenericArguments | Arm | Attribute | BareFnArg | Binding | Block | BoundLifetimes | ConstParam | Constraint | DataEnum | DataStruct | DataUnion | DeriveInput | ExprArray | ExprAssign | ExprAssignOp | ExprAsync | ExprAwait | ExprBinary | ExprBlock | ExprBox | ExprBreak | ExprCall | ExprCast | ExprClosure | ExprContinue | ExprField | ExprForLoop | ExprGroup | ExprIf | ExprIndex | ExprLet | ExprLit | ExprLoop | ExprMacro | ExprMatch | ExprMethodCall | ExprParen | ExprPath | ExprRange | ExprReference | ExprRepeat | ExprReturn | ExprStruct | ExprTry | ExprTryBlock | ExprTuple | ExprType | ExprUnary | ExprUnsafe | ExprWhile | ExprYield | Field | FieldPat | FieldValue | FieldsNamed | FieldsUnnamed | File | ForeignItemFn | ForeignItemMacro | ForeignItemStatic | ForeignItemType | Generics | ImplItemConst | ImplItemMacro | ImplItemMethod | ImplItemType | Index | ItemConst | ItemEnum | ItemExternCrate | ItemFn | ItemForeignMod | ItemImpl | ItemMacro | ItemMacro2 | ItemMod | ItemStatic | ItemStruct | ItemTrait | ItemTraitAlias | ItemType | ItemUnion | ItemUse | Label | Lifetime | LifetimeDef | LitBool | LitByte | LitByteStr | LitChar | LitFloat | LitInt | LitStr | Local | Macro | MetaList | MetaNameValue | MethodTurbofish | ParenthesizedGenericArguments | PatBox | PatIdent | PatLit | PatMacro | PatOr | PatPath | PatRange | PatReference | PatRest | PatSlice | PatStruct | PatTuple | PatTupleStruct | PatType | PatWild | Path | PathSegment | PredicateEq | PredicateLifetime | PredicateType | QSelf | Receiver | Signature | TraitBound | TraitItemConst | TraitItemMacro | TraitItemMethod | TraitItemType | TypeArray | TypeBareFn | TypeGroup | TypeImplTrait | TypeInfer | TypeMacro | TypeNever | TypeParam | TypeParen | TypePath | TypePtr | TypeReference | TypeSlice | TypeTraitObject | TypeTuple | UseGlob | UseGroup | UseName | UsePath | UseRename | Variadic | Variant | VisCrate | VisPublic | VisRestricted | WhereClause;

```

**Output:**

```jsx
export type Node =
  | Abi
  | AngleBracketedGenericArguments
  | Arm
  | Attribute
  | BareFnArg
  | Binding
  | Block
  | BoundLifetimes
  | ConstParam
  | Constraint
  | DataEnum
  | DataStruct
  | DataUnion
  | DeriveInput
  | ExprArray
  | ExprAssign
  | ExprAssignOp
  | ExprAsync
  | ExprAwait
  | ExprBinary
  | ExprBlock
  | ExprBox
  | ExprBreak
  | ExprCall
  | ExprCast
  | ExprClosure
  | ExprContinue
  | ExprField
  | ExprForLoop
  | ExprGroup
  | ExprIf
  | ExprIndex
  | ExprLet
  | ExprLit
  | ExprLoop
  | ExprMacro
  | ExprMatch
  | ExprMethodCall
  | ExprParen
  | ExprPath
  | ExprRange
  | ExprReference
  | ExprRepeat
  | ExprReturn
  | ExprStruct
  | ExprTry
  | ExprTryBlock
  | ExprTuple
  | ExprType
  | ExprUnary
  | ExprUnsafe
  | ExprWhile
  | ExprYield
  | Field
  | FieldPat
  | FieldValue
  | FieldsNamed
  | FieldsUnnamed
  | File
  | ForeignItemFn
  | ForeignItemMacro
  | ForeignItemStatic
  | ForeignItemType
  | Generics
  | ImplItemConst
  | ImplItemMacro
  | ImplItemMethod
  | ImplItemType
  | Index
  | ItemConst
  | ItemEnum
  | ItemExternCrate
  | ItemFn
  | ItemForeignMod
  | ItemImpl
  | ItemMacro
  | ItemMacro2
  | ItemMod
  | ItemStatic
  | ItemStruct
  | ItemTrait
  | ItemTraitAlias
  | ItemType
  | ItemUnion
  | ItemUse
  | Label
  | Lifetime
  | LifetimeDef
  | LitBool
  | LitByte
  | LitByteStr
  | LitChar
  | LitFloat
  | LitInt
  | LitStr
  | Local
  | Macro
  | MetaList
  | MetaNameValue
  | MethodTurbofish
  | ParenthesizedGenericArguments
  | PatBox
  | PatIdent
  | PatLit
  | PatMacro
  | PatOr
  | PatPath
  | PatRange
  | PatReference
  | PatRest
  | PatSlice
  | PatStruct
  | PatTuple
  | PatTupleStruct
  | PatType
  | PatWild
  | Path
  | PathSegment
  | PredicateEq
  | PredicateLifetime
  | PredicateType
  | QSelf
  | Receiver
  | Signature
  | TraitBound
  | TraitItemConst
  | TraitItemMacro
  | TraitItemMethod
  | TraitItemType
  | TypeArray
  | TypeBareFn
  | TypeGroup
  | TypeImplTrait
  | TypeInfer
  | TypeMacro
  | TypeNever
  | TypeParam
  | TypeParen
  | TypePath
  | TypePtr
  | TypeReference
  | TypeSlice
  | TypeTraitObject
  | TypeTuple
  | UseGlob
  | UseGroup
  | UseName
  | UsePath
  | UseRename
  | Variadic
  | Variant
  | VisCrate
  | VisPublic
  | VisRestricted
  | WhereClause;

```

**Expected behavior:**
<img width="1260" alt="Code_2022-02-01_09-07-31" src="https://user-images.githubusercontent.com/30108880/151933367-2862b730-cf96-46d5-9a49-3bc28e795eda.png">

```ts
export function join_wrap(sep: string, data: string[]) {
	if (data.length === 1) return data[0];
	let res = "";
	let line = `${data[0]}`;
	const target_length = get_print_width() - 8;
	for (var i = 1; i < data.length; i++) {
		var item = data[i];
		if (line.length + item.length > target_length) {
			res += `${line}${sep.trimEnd()}`;
			line = `\n\t${item}`;
		} else {
			line += `${sep}${item}`;
		}
	}
	return res + line;
}
```

**Comment by kachkaev** [comment]
Not sure if Prettier can (or should) support this. I don’t think it’s easy to define ‘absurdly long’ with ease and [we can’t add an option](https://prettier.io/docs/en/option-philosophy.html).

I actually like this output in your example:

```ts
export type Node =
  | Abi
  | AngleBracketedGenericArguments
  | Arm
  | Attribute
  | BareFnArg
  | Binding
  | Block
  | BoundLifetimes
  
  // ...
  
  | Variant
  | VisCrate
  | VisPublic
  | VisRestricted
  | WhereClause;
```

- It is easy to sort values alphabetically and check against duplicates
- If anything changes, `git blame` will look nice and clear

If this code is autogenerated, you can add the file to `.prettierignor`e. If your long union type is manually defined and you don’t want to mix it with other statements, you can put the type into a separate file.

**Comment by alexander-akait** [comment]
Agree, it is not readable

**Comment by duailibe** [comment]
If you don't like having this long list of names in your code, I'd suggest extracting those to a separate file

I don't think Prettier should change anything here.
