### ISSUE TITLE
Prettier creates invalid mdx

### ISSUE THREAD

**Issue by AlexanderZeilmann** [prettier/prettier#12205]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFgRgHwBU4AeMqA9FtgDpQAKATnAM4MAEqA1gEYAm273eAQw6lOPEfwA0zAVC5U+Y0dgCisOLXFiSSgHQgJICAAcYAS2gNkoAbVoQA7tRsJLKAQBt7AgJ6WDHWgEwNjgYAGUBAFs4ABlTKDhkADMPBjh-QODQsKMg+IBzZBhaAFd0kDhIjjguLhqYmXySgXy4ADEIWkiBGDMoQrcSmAh9EHQYSPcAdXRTeAZcsDgwlznTADc572RwJlH4tNoYOhbu5NTygCsGAjCC9zgARRKIeHP3NINc2kOdyK4CKMjLR4jApqYuDB0MgABwABi+djSU0CRh2wMY6nWiQMAEcXvA6MZXCABAwALQJGo1Ub0fGmegnfJnJApD7lNKRUxFUoc+5PAmJVkXAwwITgyHQpAAJlFgVM7gKAGEIJEWRUGABWUYlNK4ISuNmfEDrMoASVkCHCYBBJgAgrIwjBvA93mkAL7uoA)

```sh
--parser mdx
```

**Input:**

```mdx
<h1>Text</h1>
Press <kbd><kbd>Tab</kbd></kbd>, and
<kbd><kbd>Enter</kbd></kbd>.
```

**Output:**

```mdx
<h1>Text</h1>
Press <kbd>
  <kbd>Tab</kbd>
</kbd>
, and
<kbd>
  <kbd>Enter</kbd>
</kbd>.

```

**Expected behavior:**
According to the [mdx playground](https://mdxjs.com/playground/), the input is valid `mdx` and the output is invalid `mdx`.
Prettier should not convert valid mdx to invalid mdx.

**Comment by AlexanderZeilmann** [comment]
Yes, I'm using MDX 2. Closing in favor of #12209 (not #11857, probably a typo).

**Comment by kachkaev** [comment]
Oh yeah I meant #12209. Thanks!
