### ISSUE TITLE
Hiya! I want to integrate prettier into my editor.

### ISSUE THREAD

**Issue by nothingButSyntaxError** [prettier/prettier#12202]
Hey! I didnt use the format for an integration issue since I dont have an issue integrating prettier into vscode or vim or any famous editor but instead I want to integrate prettier into my own editor. I checked the api docs 1but wasnt sure if those are the way to start because of which I thought it would be best to ask here. Thanks! Ill be waiting for the answer!

**Comment by fisker** [comment]
I didn't see a question to answer.

**Comment by nothingButSyntaxError** [comment]
Umm.. Well, the question is, whats the way to integrate prettier into your own editor. Like, an editor i made.

**Comment by kachkaev** [comment]
You will find a few open-source editor integrations here:
https://prettier.io/docs/en/editors.html

Feel free to close this issue if this answers your question 🙂
