### ISSUE TITLE
SCSS syntax highlighting is broken in Vue SFC

### ISSUE THREAD

**Issue by TomsMengots** [prettier/prettier#12216]
**2.6.0-dev**

The `scss` syntax highlighting is broken when `singleAttributePerLine: true` and multiple attributes for the style section in Vue SFC. As the `lang="scss"` and `scoped` attributes are split into new lines, syntax is treated as `css` 

**Input:**
<img width="311" alt="Screenshot 2022-02-03 at 15 57 18" src="https://user-images.githubusercontent.com/53424390/152357306-4bbf6a9c-b85e-496b-abdd-213cee0f1e19.png">

**Output:**
<img width="319" alt="Screenshot 2022-02-03 at 15 57 31" src="https://user-images.githubusercontent.com/53424390/152357379-f14883e0-a026-4609-981f-f0ac65a6c7f7.png">

**Expected behavior:**
Same as input? Possibly should avoid `singleAttributePerLine` option for `style` section?

**Comment by duailibe** [comment]
This looks like a bug in VSCode, it should parse correctly if `style` is in a different line.

I don't think we should special case it in Prettier

**Comment by TomsMengots** [comment]
@duailibe Thanks for clarifying! The same issue is on all the devices we tried, will open an issue for VSCode then.

**Comment by duailibe** [comment]
@TomsMengots closing for now, but let us know if there's any legitimate reason we should fix this in Prettier
