### ISSUE TITLE
JSDoc super class type override becomes broken

### ISSUE THREAD

**Issue by wmertens** [prettier/prettier#12220]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCo5wAe8UAJrgPQBU1OAAjAJ4AOcOwAYhBADwBC6AE4A+AL45qlHAApuEAJQcxIADQgILGAEtomZKGFCIAdwAKwhPpTpUJ9E33qARkPRgA1nBgBlFu+0oAHNkGCEAVzh1OABbZzgyMgSAGXRg8PQguG4hGPQYHWDkEHRwmAg1EAALGBjUAHUq7XhMfzA4Hytm7QA3ZqZisGxKwMw4IRgzNyC85AAzWzH1ACtMIn43T28fdBi4ZMC4ecWokFWiH0Cg1DgARXCIeGPUJZB-ITGhYud0eNRKlhCQIweraMgwKrIAAcAAZ1ICIGN6m4WMVAXBPj0juoAI4PeBTTTWEqYAC0UDgCQSlSEcDx2lpU0ysyQCxepzGMW0oQiHKuN3ujyOrJO6hgv1B4MhSAATGK3NpUFcAMIQGIskAYgCslXCYzwv2sbNePUiAElyAhfGAgVoAILkHzMG7PMZiMRAA)

```sh
--parser babel
```

**Input:**

```jsx
class T extends /** @type {Foo<Bar>} */ (Foo) {}
```

**Output:**

```jsx
class T /** @type {Foo<Bar>} */ extends ((Foo)) {}

```

**Expected behavior:**
```jsx
class T extends /** @type {Foo<Bar>} */ (Foo) {}
```

The type override is needed to specify the generic type and should not be moved.

**Comment by duailibe** [comment]
@wmertens Yeah, Prettier shouldn't move this comment, it's a bug.

But unrelated to the bug, shouldn't the syntax be something like this?

```js
/** @extends {Foo<Bar>} */
class T extends Foo {}
```

**Comment by wmertens** [comment]
I wish, it looks like the extends keyword can't use generics. i can't get it to work in any case

**Comment by duailibe** [comment]
Is that using tsc? [This](https://www.typescriptlang.org/play?filetype=js#code/PQKhAIAEBcFMFsAOAbAhncAVcJgCgBjNAZ2PADEB7S8Abz3HFAkgCdZoBXVgOzNswBfHPkYBzDuABm1ABQBKOg0bh2XXkxbQAnolh0hI8D07JkAbmWC81vMyiwAHnB4ATMlUoAeYtFYBLHjEAPhFCEjIAQXAnF3cKajpbexhdfV8AoLCCSj5ocEdwAF5jWAB3cEiFADoZSks7MAdnWDcPai8TeAAjWFZQ3HDUUnAAIRiWtoSaWmSm1L1jTh6+7NzfcG1i0orRmrrzIA) works for me and in the playground

**Comment by wmertens** [comment]
Thanks for the fix! Yeah I'm still struggling with it. I'm trying to type https://github.com/StratoKit/strato-db and when I use `interface` I can't seem to  extend it but when I use `declare class` I can't use types that refer to it as base classes

**Comment by fisker** [comment]
This fix havn't released yet.

**Comment by wmertens** [comment]
OK, I figured out my unrelated problem: I didn't properly export my library module (unknowingly used shorthand declaration) and this made the types somewhat work for class extending but not when subclassing. Argh.
Properly exporting the types showed that I had to use classes instead and now everything works with the JSDoc syntax.

So it was indeed a bug but not a very important one :sweat_smile:
