### ISSUE TITLE
Prettier rewraps trailing closure

### ISSUE THREAD

**Issue by spicyj** [prettier/prettier#1225]
Prettier did this to me and it seems worse IMO:

```diff
diff --git a/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js b/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js
index 749a928..cf0bb9c 100644
--- a/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js
+++ b/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js
@@ -83,11 +83,8 @@ var ReactDOMInput = {
   mountWrapper: function(inst, props) {
     if (__DEV__) {
       var owner = inst._currentElement._owner;
-      ReactControlledValuePropTypes.checkPropTypes(
-        'input',
-        props,
-        () => getStackAddendumByID(inst._debugID),
-      );
+      ReactControlledValuePropTypes.checkPropTypes('input', props, () =>
+        getStackAddendumByID(inst._debugID));

       if (
         props.checked !== undefined &&
```

**Comment by spicyj** [comment]
If the lambda's body was a BlockStatement then I would agree with the reformatting.

**Comment by vjeux** [comment]
```js
ReactControlledValuePropTypes.checkPropTypes('input', props, () =>
  getStackAddendumByID(inst._debugID),
);
```

In master, the last parenthesis will be on its own line. This is the most reported issue we had so far on prettier.

Now, regarding if we should apply the last argument expansion, this is tricky. If there's a single argument, that's a clear yes.

If there are other arguments before, this is less a clear cut. I've seen places where it made sense and places like this one where it does less.

My intuition is to keep the same rules as normal functions and arrow functions with {}. This way it's more consistent for the user and the downside is the code looking a bit weird but it's not that bad.

The heuristic I have in mind for when people expand is: is the last function the continuation of the work. Another way to say it is: would it make sense to replace it with async await.

In this case, it's not. The arrow function serves a different purpose, it is there to provide a configuration and happened to be the last argument but could have been another one.

Unfortunately, I'm not sure how to differentiate the two by looking at the ast.

**Comment by vjeux** [comment]
We're past 1.0 and are looking into avoiding making big formatting changes, so I'm going to go ahead and close this issue. Sorry!
