### ISSUE TITLE
TODOs for `@babel/parser@7.17.0`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#12255]
TODOs:

- [x] Add test for https://github.com/babel/babel/pull/14145
- [x] Support  `v` flag https://github.com/babel/babel/pull/14086
- [x] Support `decoratorsAutoAccessors` ? https://github.com/babel/babel/pull/13681
- [x] Support `destructuring private fields` https://github.com/babel/babel/pull/13931
- [ ] ~~Add more `topics` to pipeline operator? https://github.com/babel/babel/pull/13973~~

Some new syntax support should be added in separate PRs.

_Originally posted by @fisker in https://github.com/prettier/prettier/pull/12241#issuecomment-1031071366_

**Comment by sosukesuzuki** [comment]
@fisker Are there any tasks you're already working on?

**Comment by fisker** [comment]
I'm not working on any of them.

**Comment by sosukesuzuki** [comment]
I don't think we should add support for new `topicToken`. It is still an experimental feature, and it seems a hard to prepare so many tests for it. We should fix it when the pipeline proposal progresses and the topicToken is decided.
