### ISSUE TITLE
Performance of release builds more than 2x slower since 2.4.0

### ISSUE THREAD

**Issue by stephank** [prettier/prettier#12261]
**Environments:**

- Prettier Version: 2.5.1
- Running Prettier via: CLI
- Runtime: Node.js v16.13.2
- Operating System: macOS
- Prettier plugins (if any): None

**Steps to reproduce:**

```
mkdir good bad current
(cd good && npm init -y && npm add prettier@2.3.2)
(cd bad && npm init -y && npm add prettier@2.4.0)
(cd current && npm init -y && npm add prettier@2.5.1)
hyperfine -w 3 \
  './good/node_modules/.bin/prettier ./current/package.json' \
  './bad/node_modules/.bin/prettier ./current/package.json' \
  './current/node_modules/.bin/prettier ./current/package.json'
```

**Expected behavior:**

Same performance as 2.3.2.

**Actual behavior:**

```
Benchmark 1: ./good/node_modules/.bin/prettier ./current/package.json
  Time (mean ± σ):     230.2 ms ±   2.4 ms    [User: 208.7 ms, System: 24.1 ms]
  Range (min … max):   226.1 ms … 235.7 ms    12 runs

Benchmark 2: ./bad/node_modules/.bin/prettier ./current/package.json
  Time (mean ± σ):     543.1 ms ±   6.9 ms    [User: 524.5 ms, System: 50.2 ms]
  Range (min … max):   537.0 ms … 560.9 ms    10 runs

Benchmark 3: ./current/node_modules/.bin/prettier ./current/package.json
  Time (mean ± σ):     541.7 ms ±   2.3 ms    [User: 525.9 ms, System: 48.1 ms]
  Range (min … max):   535.9 ms … 543.9 ms    10 runs

Summary
  './good/node_modules/.bin/prettier ./current/package.json' ran
    2.35 ± 0.03 times faster than './current/node_modules/.bin/prettier ./current/package.json'
    2.36 ± 0.04 times faster than './bad/node_modules/.bin/prettier ./current/package.json'
```

I wanted to do a git bisect on Prettier itself, but then noticed I can't reproduce it in a checkout of the 2.4.0 tag, for example. Nor can I reproduce it using `./dist/bin-prettier.js` after a `yarn build`. Is that not the same as what ends up in the actual npm packages?

**Comment by fisker** [comment]
> Is that not the same as what ends up in the actual npm packages?

No, we publish `./dist/` directly.

**Comment by stephank** [comment]
> No, we publish `./dist/` directly.

Sorry, I'm confused, this reads a bit like 'no but yes' to me. 😅 Am I correct in that the release process is roughly `yarn build && cd dist && npm publish`?

I'm not sure what went wrong yesterday, but it appears I'm now able to reproduce it in my checkout. It still only affects builds (running from `./dist/bin-prettier.js`) and not running from source (`./bin/prettier.js`). Bisect says first bad commit is 14a952aafbe26c43d0d3855f492debf99c1abe20.

**Comment by fisker** [comment]
Sorry for the confusion.

I remember https://github.com/prettier/prettier/commit/14a952aafbe26c43d0d3855f492debf99c1abe20 did change dynamic `require` to static `require`, but I fixed it later, I'll find that commit.

**Comment by fisker** [comment]
> I remember https://github.com/prettier/prettier/commit/14a952aafbe26c43d0d3855f492debf99c1abe20 did change dynamic require to static require, but I fixed it later, I'll find that commit.

Sorry, not this one, it happened in  `v2.1.0` release https://github.com/prettier/prettier/issues/8882#issuecomment-678979437.

I'll check https://github.com/prettier/prettier/commit/14a952aafbe26c43d0d3855f492debf99c1abe20 again.

**Comment by stephank** [comment]
Alright, thanks for looking into this!

At first glance, I'm a bit mystified how that change can have such a big impact. Not sure if you can repro yourself, but if you want me to investigate further, I may be able to do so later today.

I did a quick check, and even just `--version` is noticeably impacted, so it almost has to be a bundling / module loading thing, I think:

```
Benchmark 1: ./good/node_modules/.bin/prettier --version
  Time (mean ± σ):     191.3 ms ±   2.1 ms    [User: 171.1 ms, System: 20.1 ms]
  Range (min … max):   188.3 ms … 195.3 ms    14 runs

Benchmark 2: ./bad/node_modules/.bin/prettier --version
  Time (mean ± σ):     525.9 ms ±   2.3 ms    [User: 507.6 ms, System: 49.7 ms]
  Range (min … max):   521.3 ms … 529.9 ms    10 runs

Summary
  './good/node_modules/.bin/prettier --version' ran
    2.75 ± 0.03 times faster than './bad/node_modules/.bin/prettier --version'
```

**Comment by fisker** [comment]
Thanks for the investigation, really appreciate. I'm a little busy now, if you find anything, please let me know.

**Comment by fisker** [comment]
I guess I found the reason, `require("./parser-babel.js")` was an inline `require()` in v2.3.0, somehow it was changed to a top level `require()`, this still the same in `v2.5.1`, you can see this in `index.js`. I think this is the reason.

**Comment by fisker** [comment]
If this is the reason, it's already fixed in `main` branch.

**Comment by stephank** [comment]
Oh, darn, you're right. It looks like the `main` branch is fine. Should've tested that sooner, sorry. Thanks for your time. 👍

**Comment by fisker** [comment]
I'm going to add a test for that, to make sure this won't happen again.
