### ISSUE TITLE
Incorrect Indentation For Member Access On Ternary Expression

### ISSUE THREAD

**Issue by PythooonUser** [prettier/prettier#12266]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEBqcBOBPbfQg3PAGWgHMA5AQwFs4B+AI1p2M9K-wqhoZwkbAF48SRbqT4DGAOgAmWKZNUT148TLqMAFAEo5AZwiMYACwCW-TSo12tVHXAMBuADpQQAGhAQADjCW0EbIoOw4EADuAArsCKEotAA2UbR4ob4sOLRgANZwMADKgmTWcMioKUZwWTn5hUX+udaUyDA4AK61IHD0LHAKCoNktPydtJRwAGIQOPS0MEH8yCC0nTAQPiDmMPTJAOpW8EbNYHBFCZZBAG7XeKtgRpkg1jU4MDE5lAuV1T0AKyMAA8iq1knAAIqdCDwP7JGq+Zo4d6rNgDZLbfyRGoHHL+VbYuDvG4VXwARxh8C+AUSayMAFooHBBoNtjg4JTLByvpNfkgqgiejV6JZ2l1heCoVSKgL-r4YLQWAdLAoLMgAEwKnKWZKtADCpn5vSMAFZtp0agAVJWJQWIkA3boASSgw1gRTAOEsgQAgm6ijA8BD4Q7sdYYCq1eZkAAOAAMAF9E0A)

```sh
# No options
```

**Input:**

```jsx
fooVeryVeryVeryVeryLongName?barVeryVeryVeryVeryVeryLongName:bazVeryVeryVeryVeryVeryLongName.doVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName().somethingVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName();
```

**Output:**

```jsx
fooVeryVeryVeryVeryLongName
  ? barVeryVeryVeryVeryVeryLongName
  : bazVeryVeryVeryVeryVeryLongName
      .doVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName()
      .somethingVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName();
```

**Expected behavior:**
When the lines for the method calls of `do...` and `something...` exceed the given `printWidth`, then they get indented. Unfortunately, the indentation uses **two** levels, instead of **one**.

Also, `eslint` is complaining with something like:
```
Expected indentation of 8 spaces but found 10. eslint[@typescript-eslint/indent](https://typescript-eslint.io/rules/indent)
```

**Comment by fisker** [comment]
You can add [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier) to your ESLint config, which will disable all conflicting rules.

**Comment by PythooonUser** [comment]
Hey @fisker ,

thanks for answering, but maybe I created a bit of confusion when mentioning the `tslint` issue.

My main concern is about the **doubled indentation**. I don't think that is correct.

When I do not use the ternary expression and just enforce the wrapping of the member access, I do get a single indentation, which is fine.

[Playgroud link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjAhgLwGpwE4CeuhxR+ZhAMtAOYBy6AtnAHQAmEpX53JP-fQQWpR6TOAAoAlCwDOEZjAAWAS1G8KmjdvIixzaQG4AOlBAAaEBAAOMFdFnJQ6PHggB3AAouEjlOgAbd3QCR0tUPHQwAGs4GABlcUo1OGQAM0DZOHDImLj46yi1GmQYPABXbJA4RlQ4NjZ6ynRRcvQaOAAxCDxGdBg7UWQQdHKYCAsQJRhGAIB1VXhZQrA4eN8VOwA3TYJhsFkwkDUsvBhPSJo+9MyqgCtZAA944oC4AEVyiHgbgKzLQp4U7DDB1AKTax4NQwOYqNjKZAADgADAC3Fk5pFrMNIXBTltUpYAI5feAXGx+EayAC0UDg9XqkzwcBJKmZF3a1yQGT+VSyjBUpQqfNeH1JqW5t0sMHQqFh8KUyAATNLIioAsUAMIKLnVWQAVkm5SyABVZX4ef8QFtKgBJKCNWDxMBQ2wAQQd8RgBDevyyAF9-UA)

Input:
```
bazVeryVeryVeryVeryVeryLongName.doVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName().somethingVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName();
```

Output:
```
bazVeryVeryVeryVeryVeryLongName
  .doVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName()
  .somethingVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName();
```

**Comment by fisker** [comment]
Sorry, we won't change the output.

**Comment by PythooonUser** [comment]
Sure, no problem.

I just have never seen this output before and wondered why it would use doubled indentation. It's not directly apparent.

But I seem to have found an edge case I never noticed before.

Thanks!

**Comment by Josh-Cena** [comment]
@PythooonUser Just want to mention that it's not "doubled indentation". Prettier formats every branch in a ternary as a separate block with its own indentation offsets. For example, you can also have the following Prettier output:

```js
f
  ? aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  : {
      aaaaaaaaaaaaaaaaaaa,
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
    };
```
