### ISSUE TITLE
Probable formatting issue?

### ISSUE THREAD

**Issue by matthaias** [prettier/prettier#1226]
Hi, if i write a function call with params in two different styles the result of prettier is not the same. I expected to get the same result, but maybe i am wrong and this is a special case? Thanks!

An example is [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20const%20classNames%20%3D%20cx(%5Cn%20%20%20%20%20%20%27top-navigation-container%27%2C%20%5Cn%20%20%20%20%20%20%7B%20collapsed%20%7D%5Cn%20%20%20%20)%3B%5Cn%5Cn%20%20%20%20const%20classNames%20%3D%20cx(%27top-navigation-container%27%2C%20%7B%20%5Cn%20%20%20%20%20%20collapsed%20%5Cn%20%20%20%20%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D).

**Comment by bakkot** [comment]
Prettier will expand any object literal which had newlines in it originally, since people often want to keep those.

**Comment by matthaias** [comment]
Thanks for the information. I totally forgot to answer, sorry!
