### ISSUE TITLE
diffArrays deep require breaks Prettier 2.6 in Node.js 17.5.0

### ISSUE THREAD

**Issue by gabrielmaldi** [prettier/prettier#12275]
**Environments:**

- Prettier Version: 2.6.0-dev
- Running Prettier via: CLI
- Runtime: Node.js v17.5.0, npm 8.4.1
- Operating System: macOS 12.2

**Steps to reproduce:**

1. Install Node.js v17.5.0 and npm 8.4.1
2. Install Prettier 2.6.0-dev
3. Run prettier: `npx prettier --write .`

**Expected behavior:**

Prettier works.

**Actual behavior:**

Prettier breaks:

```sh
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/diff/array.js' is not defined by "exports" in /repo/node_modules/diff/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/repo/node_modules/prettier/src/main/core.js:4:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v17.5.0
```

I tracked the problem to this line:

https://github.com/prettier/prettier/blob/92e6f44bbad9b6ee70dff0827f17448d50c72ca7/src/main/core.js#L4

If I change it to:

```js
const { diffArrays } = require("diff");
```

Prettier works.

Alternatively, If I change this line in https://github.com/kpdecker/jsdiff:

https://github.com/kpdecker/jsdiff/blob/d358a573dc38fb89dd5ee296805e29f75c932a58/package.json#L40

To:

```json
"./*": "./*"
```

Prettier works too.

Thanks!

**Comment by fisker** [comment]
Thanks for the information, do you think we can ask `diff` to fix?

**Comment by gabrielmaldi** [comment]
I thought about it, but the `diff` repo hasn't been active; the last commit is from 2020 and I don't see issues or PRs being answered. So I think that if we file a ticket there, it will probably take a long time for it to get released to npm (if it ever does). Perhaps there's something we can do in Prettier to fix this before 2.6 is released?

**Comment by fisker** [comment]
We can bundle it into vendors https://github.com/prettier/prettier/blob/92e6f44bbad9b6ee70dff0827f17448d50c72ca7/package.json#L164

**Comment by fisker** [comment]
I've sent a PR to the upstream, let's see if it will get merged. https://github.com/kpdecker/jsdiff/pull/351
