### ISSUE TITLE
Unstable formatting: variable assignment, expression in parentheses, method call

### ISSUE THREAD

**Issue by mvolfik** [prettier/prettier#12270]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwE4CucAlADpSaYY75FkWVVa6EnmOPUt3sefO02DPowA20AOYA1AIZ5UMgEai4AORkBbOAEZMAXkwB6Q5gACMAM4BaVBKgQ8cXiMrYAbnIXK4ABl0BqTDc4PABPABlJWXklFXUtVQINRRCAJmIAOi0YAAsIABNsYgBuchAAGhAIAAcYVGgLZFA5PAgAdwAFOQRGlBlRNplQxsrFPBkwAGs4GABlTThw1Cg4ZHR+izhR8amZ2eqJ5YlkQUq4ZLh8-MvwmSgJAhkJOAAxBw0ZGDr75BAZAhgEAqIByMA0ogA6jlUPALAcwHBZj0Yag3DDQr8wBYRmgoJs8DAOuMJB81hstiAAFYWAAesyOKgAigQIPAyaJNpUDnh8b8YKFqnALGB5LVgdV5LAIah8rlkAAOHxc1qbCHjaq-CVCkLBYEARxZ8CJNV6f2sK0ul2BjgNqEcRKepKQ6w5FM2GlQJ1YlQsDLgzNZq2d5MqMCU0tlOWQqVD41QoiOAGEIBonSAhQBWYEETYAFSUvRdnJAbiIAEkoNdYLMRahagBBSuzfkqdmbAC+7aAA)

```sh
--parser typescript
```

**Input:**

```tsx
if (true)
  if (true)
    if (true)
      if (true)
        if (true)
          longVariableName1 = // @ts-ignore
          (variable01 + veryLongVariableNameNumber2).method();

```

**Output:**

```tsx
if (true)
  if (true)
    if (true)
      if (true)
        if (true)
          longVariableName1 = ( // @ts-ignore
            variable01 + veryLongVariableNameNumber2
          ).method();

```

**Second Output:**

```tsx
if (true)
  if (true)
    if (true)
      if (true)
        if (true)
          longVariableName1 = // @ts-ignore
          (variable01 + veryLongVariableNameNumber2).method();

```

**Expected behavior:**
The formatter output should be stable, not loop between two different formats.

**Comment by thorn0** [comment]
Another manifestation:

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBrCYAWAhgEYDCEEAlnAOKEC2cA8lE8RADZwCqUA7nEIA3OJgC8mAPSTMAfnkAdKJhWqATvgCuxQmuIAlLTr0AKQlCiaOu8hDhwAJgGUADh0pg4aAOqEO2H0IAT18ggEoAbiUlEAAaEAgXGEp0ZFBdNQg+AAVdBDRkED8+YIL44jVCMGw4GCcGOAAZSig4ZAAzPzQ4csrq2tcqloBzZBg1TR6QOHpiRwdHRvNhzUJhuAAxCDV6QhhkqFGUQk0YCDiQfBh6Dm98Sng0Fyq4J3yHyiEHoMKwNDKQC1umoYNlKsNdh0ulMAFZoAAeThGXAAipoIPAoRxuvFnmpgYUdHMOBcXGoWjBvJQHDB8MgABwABlxmW63kqLkKZK8cDUIguAEd0fAwYkCsc0ABaVqORwXNRwIWUBVgtaQpCdbFTbr0ShjCba5FwNEYtoa6HxGAkKk0ulIABMlsqlHch3I9HV0zQAFYLppugAVEjizU4kBCSYASSgC1gTjA5KSAEEY04YEEuFjugBfbNAA)

```sh
--parser babel
```

**Input:**

```jsx
const kochabCooieGameOnOboleUnweave = // ???
      rhubarbRhubarb(annularCooeedSplicesWalksWayWay);


```

**Output:**

```jsx
const kochabCooieGameOnOboleUnweave = rhubarbRhubarb( // ???
  annularCooeedSplicesWalksWayWay
);

```

**Second Output:**

```jsx
const kochabCooieGameOnOboleUnweave = rhubarbRhubarb(
  // ???
  annularCooeedSplicesWalksWayWay
);

```

**Comment by mvolfik** [comment]
though note that your output is stable after second pass. though ideally it shouldn't need that
