### ISSUE TITLE
Add support for luau

### ISSUE THREAD

**Issue by MorganDilling** [prettier/prettier#12279]
Unless I am mistaken, there doesn't seem to be formatting support for the "luau" language. (Note I do not mean lua, but instead, roblox's language "luau" which you can find more about [here](https://luau-lang.org/). 

I am asking for support as quite a few other vsc formatting plugins for lua do not support the luau fork.

**Comment by kachkaev** [comment]
You can consider creating a plugin for luau — see [Plugins page](https://prettier.io/docs/en/plugins.html) for details and example.

I will close this issue because this repo focuses on Prettier core.
