### ISSUE TITLE
Prettier throws `SyntaxError: Unexpected token` in css

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#12282]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnOAbOYYAJgA6UuuA9AFS4BmEATrgGICWtcNAHruaUSQLQBbCAC8+AQwAOEuGNpioYOElxRocANy8ylGvQDCAC1oQBcLj2K4+AdzgAjANZMY4qTLkKlKtZqgBfIiIKRjpcAEkAUQBGAAZzInQsHCQkQVQ+OHYJeQATfC0cplQJDDEAT2VVKA0iPxAAGhAICRgmaFRkUFljawAFWQQOlDEMa3KOxrs5MAc4GABlMVMAGSZq5CoR9Enp2YXssDWAc2QYWgBXOEa4ATs4HJz75fkj87EjuAY6ATEYVqgTsNzjAIA0QAYYAIMAB1AzOODFMSKeaDZxMABuzjKyHAqAmIDW6FoMF6ciOPw2WyuIAAVqh2PNjlgAIrnCDwSkYbYgbK0Ik4uxiO4YMESWhrGDQpg5GAGZAADhijTFEHQ0LkEhxYoRcFo6LgYIAjmz4KTmkMQGJ0tV7vcwaxjSw4KT3hSkJsudT0AImKcLl6mXBWeyDe6qY0YEKpTK5UgAEwRuRMDDHPQmN0gBEAVjB53QABUhUMPdz0ZcwlBHrB5mBxS0AIKV+YwMpYTnoPx+IA)

```sh
--parser babel
```

**Input:**

```jsx
select {
  /* for Firefox */
  -moz-appearance: none;
  /* for Chrome */
  -webkit-appearance: none;
}

/* For IE10 */
select::-ms-expand {
  display: none;
}
```

**Output:**

```jsx
SyntaxError: Unexpected token (3:18)
  1 | select {
  2 |   /* for Firefox */
> 3 |   -moz-appearance: none;
    |                  ^
  4 |   /* for Chrome */
  5 |   -webkit-appearance: none;
  6 | }
```

**Expected behavior:**

**Comment by kachkaev** [comment]
Works as expected after changing `--parser` to `css` – see [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnOAbOYYAJgA6UuuA9AFS4BmEATrgGICWtcNAHruaUSQLQBbCAC8+AQwAOEuGNpioYOElxRocANy8ylGvQDCAC1oQBcLj2K4+AdzgAjANZMY4qTLkKlKtZqgBfIiIKRjpcAEkAUQBGAAZzInQsHCQkQVQ+OHYJeQATfC0cplQJDDEAT2VVKA0iPxAAGhAICRgmaFRkUFljawAFWQQOlDEMa3KOxrs5MAc4GABlMVMAGSZq5CoR9Enp2YXssDWAc2QYWgBXOEa4ATs4HJz75fkj87EjuAY6ATEYVqgTsNzjAIA0QAYYAIMAB1AzOODFMSKeaDZxMABuzjKyHAqAmIDW6FoMF6ciOPw2WyuIAAVqh2PNjlgAIrnCDwSkYbYgbK0Ik4sB4sESWhrGDQpg5GAGZAADhijRFEHQ0LkEhxIoRcFo6LgYIAjmz4KTmkMQGJ0tV7vcwaxDSw4KT3hSkJsudT0AImKcLh6mXBWey9a6qY0YGI7BKpTKkAAmMNyJgYY56EwukAIgCsYPO6AAKhGhm7uejLmEoI9YPMwKKWgBBCvzGBlLCc9B+PxAA). Where do you encounter this error?

**Comment by B2o5T** [comment]
Sorry, closed as it's was caused by my editor
