### ISSUE TITLE
Prettier not formatting when filename include [] [main].tsx

### ISSUE THREAD

**Issue by ivanjeremic** [prettier/prettier#12281]
In some frameworks like Nextjs we need to name dynamic routes using `[]` like `[main].tsx` however this files can for some reason not be formatted by prettier. (ONLY WHEN USING .tsx extension)

**Comment by fisker** [comment]
This case mentioned in https://github.com/prettier/prettier/pull/12225, maybe fixed? If so, we need add test for it.
