### ISSUE TITLE
EOF new-line (CLI bug)

### ISSUE THREAD

**Issue by Otard95** [prettier/prettier#12319]
I have looked around trying to find an existing issue. If I missed it, I do apologize.

**Environments:**

- Prettier Version: 2.5.1
- Running Prettier via: CLI (locally and github action)
- Runtime: NodeJS v16.13.2
- Operating System: Linux \<host\> 5.10.0-11-amd64 # 1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux (My local system)
- Prettier plugins (if any): None

**Steps to reproduce:**

```console
git clone https://github.com/Otard95/prettier-test
cd prettier-test
npm i
npm run prettier -- -c index-lf.js
npm run prettier -- -c index-no-lf.js
```
You can also see the [GH Workflow](https://github.com/Otard95/prettier-test/runs/5213373259?check_suite_focus=true)

**Expected behavior:**

```console
$ cat ./index-lf.js | sed 's/^/"/;s/$/"/'
"const test = () => {"
"  console.log('test')"
"}"
""
$ npm run prettier -- -c index-lf.js

> test@1.0.0 prettier
> prettier "-c" "index-lf.js"

Checking formatting...
All matched files use Prettier code style!
```
```console
$ cat ./index-no-lf.js | sed 's/^/"/;s/$/"/'
"const test = () => {"
"  console.log('test')"
"}"
$ npm run prettier -- -c index-no-lf.js

> test@1.0.0 prettier
> prettier "-c" "index-no-lf.js"

Checking formatting...
[warn] index-lf.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

**Actual behavior:**

```console
$ cat ./index-lf.js | sed 's/^/"/;s/$/"/'
"const test = () => {"
"  console.log('test')"
"}"
""
$ npm run prettier -- -c index-lf.js

> test@1.0.0 prettier
> prettier "-c" "index-lf.js"

Checking formatting...
[warn] index-lf.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```
```console
$ cat ./index-no-lf.js | sed 's/^/"/;s/$/"/'
"const test = () => {"
"  console.log('test')"
"}"
$ npm run prettier -- -c index-no-lf.js

> test@1.0.0 prettier
> prettier "-c" "index-no-lf.js"

Checking formatting...
All matched files use Prettier code style!
```

## My investigation

When I first noticed the issue I was using `nvim` with `coc` and `coc-eslint`, so taking a hint from #6090 I started testing directly in `bash`. See my [test repo](https://github.com/Otard95/prettier-test) for reference.

I also found #12010, I tried adding the [`.gitattributes`](https://github.com/prettier/prettier/blob/main/.gitattributes), as evidenced by the commits in my [test repo](https://github.com/Otard95/prettier-test/commits/master), but this changes nothing.

Now I started to think that maybe you changed this up and maybe now it was supposed to not be a EOF new-line. I found #10420 but no follow up, but i also found #10088, which if we ignore the drama, was very clear in that EOF new-lines are the standard. This [comment](https://github.com/prettier/prettier/issues/10088#issuecomment-763082323) was very clear.

Hopefully I haven't missed anything. But if I did, I again apologize for wasting your time.

**Comment by fisker** [comment]
I don't quite understand the problem here, you want prettier pass `index-lf.js` and fail `index-no-lf.js` right?

**Comment by fisker** [comment]
`index-lf.js` contains two new lines at the end, Prettier only allow one.

**Comment by Otard95** [comment]
Now this is interesting, I see now on GitHub that [index-lf.js](https://raw.githubusercontent.com/Otard95/prettier-test/master/index-lf.js) contains no new-line. But in my local version it contains one 
![image](https://user-images.githubusercontent.com/7838337/154241083-28719482-3762-4b66-966c-f228101ad4b2.png)
Which I can confirm with
```console
$ cat ./index-lf.js | sed 's/^/"/;s/$/"/'
"const test = () => {"
"  console.log('test')"
"}"
""
```

I'm unsure why GH doesn't have the new-line

**Comment by fisker** [comment]
```console
node -p "require('fs').readFileSync('./index-lf.js', 'utf8').split('\n')"
```

**Comment by Otard95** [comment]
Now that is indeed interesting. Perhaps this is something NodeJS related. All other tools seems to think there is 1 new-line.
```console
 cat -n index-lf.js 
     1	const test = () => {
     2	 console.log('test')
     3	}
     4
```
In any case, that is not your problem. Thanks for the help and sorry for taking your time.

If I find anything further on this, is it ok if I add it here? That way perhaps it can help someone else.

**Comment by fisker** [comment]
Open this file in your editor, you should see two empty lines.

**Comment by fisker** [comment]
paste `view-source:https://raw.githubusercontent.com/Otard95/prettier-test/master/index-lf.js` in you chrome.

**Comment by Otard95** [comment]
Huh. You are most likely correct. I'm not going to argue that. I only asked because someone else might find this and be as confused as I am, considering that there are conflicting information, like my editor tells me there are 4 not 5 lines, so does `cat` and GH.
![image](https://user-images.githubusercontent.com/7838337/154246178-4bd41c46-35be-4bb0-a3b1-f926c8e261d6.png)
![image](https://user-images.githubusercontent.com/7838337/154246822-200ec70d-9493-402b-812b-ffe81ab0a101.png)

I don't expect you to spend any more time on this. And if this is not the place to document this further, you can just say so. I'll just document it another place

**Comment by fisker** [comment]
https://github.com/prettier/prettier/issues/8715#issuecomment-654599853

**Comment by Otard95** [comment]
Ok now that is interesting. *Today I learned!*
I guess GH also uses this logic then. Thanks a lot for sticking with me! I really do appreciate that!
