### ISSUE TITLE
Prettier@1 depends on npm

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#1233]
No idea how this happened (package.json in this repo doesn't have it), but upgrading to 1.0 added TONS of deps, including npm (which I reckon is why there are so many).

```sh-session
$ npm show prettier@1 dependencies

{ 'ast-types': '0.9.8',
  'babel-code-frame': '6.22.0',
  babylon: '7.0.0-beta.8',
  chalk: '1.1.3',
  esutils: '2.0.2',
  'flow-parser': '0.43.0',
  'get-stdin': '5.0.1',
  glob: '7.1.1',
  global: '^4.3.1',
  'jest-validate': '19.0.0',
  minimist: '1.2.0',
  npm: '^4.5.0' }
```

```sh-session
$ yarn info prettier dependencies
yarn info v0.22.0
{ 'ast-types': '0.9.8',
  'babel-code-frame': '6.22.0',
  babylon: '7.0.0-beta.8',
  chalk: '1.1.3',
  esutils: '2.0.2',
  'flow-parser': '0.43.0',
  'get-stdin': '5.0.1',
  glob: '7.1.1',
  global: '^4.3.1',
  'jest-validate': '19.0.0',
  minimist: '1.2.0',
  npm: '^4.5.0' }
✨  Done in 0.79s.
```

Look at the bottom...

**Comment by SimenB** [comment]
`global: '^4.3.1'` is also missing from the package.json in this repo... @vjeux any idea how this happened?

**Comment by vjeux** [comment]
Oops, just pushed 1.0.1 without those :(

**Comment by vjeux** [comment]
So, the reason behind this is that I didn't have npm on my brand new fb laptop but only yarn. So I did `yarn add global npm`. But instead of adding `npm` as global, it added both global and npm to package.json.

Then, I installed npm globally and it didn't warn me that my package.json was dirty and happily pushed those two changes :x

cc @bestander for yarn, maybe we can add a warning.

**Comment by SimenB** [comment]
Auch. Fixed now though, thanks for the quick fix!

npm yells at you if you try to publish with a dirty git (or maybe just running `version`, one of them). Yarn should probably do the same thing 😄

**Comment by vjeux** [comment]
npm doesn't yell at you, it happily published it.

![image](https://cloud.githubusercontent.com/assets/197597/25015692/c2292bc2-2031-11e7-9188-424a4ea85638.png)

**Comment by vjeux** [comment]
npm doesn't yell at you, it happily published it with dirty changes

![image](https://cloud.githubusercontent.com/assets/197597/25015725/e4ba03a0-2031-11e7-9868-c1fb914fdd38.png)

**Comment by SimenB** [comment]
Npm yells during `version`

```sh-session
$ npm version major
npm ERR! Git working directory not clean.
npm ERR! M package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simen/.npm/_logs/2017-04-13T17_13_56_497Z-debug.log
```

**Comment by vjeux** [comment]
oh, I just modified package.json manually!

**Comment by SimenB** [comment]
Living on the edge 😁

**Comment by SimenB** [comment]
FWIW `yarn version` does not complain about dirty working tree
