### ISSUE TITLE
Regression TypeScript parser: "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by ayroblu** [prettier/prettier#12338]
Looks like a regression of #11269 and #11076

**Environments:**

- Prettier Version: 2.5.1
- Running Prettier via: webpack browser
- Runtime: webpack v5
- Operating System: macOS
- Prettier plugins (if any): parser-typescript

**Steps to reproduce:**

Add this line of code to repo that has webpack:

```ts
return () => import("prettier/parser-typescript");
```

**Expected behavior:**
No warnings

**Actual behavior:**
Big webpack warning about "Critical dependency: the request of a dependency is an expression"

**Comment by brabeji** [comment]
I confirm this seems to be broken since `2.3.1`.

**Comment by fisker** [comment]
I'm not sure how to reproduce this.

**Comment by fisker** [comment]
I've moved this to 2.7 milestone, to unblock v2.6 release, but we can release a patch release if necessary.

**Comment by liuzhaowei55** [comment]
I got this error on 2.6.0 , fallback 2.5.1to  is OK

**Comment by fisker** [comment]
I can't help without a reproduction.

**Comment by ayroblu** [comment]
What's the issue I explain how to reproduce in the issue + linked to a bunch of other tickets which have further reproductions. Would you like me to create a repo for the reproduction?

**Comment by fisker** [comment]
Yes, please.

**Comment by ayroblu** [comment]
With create react app:
https://github.com/ayroblu/prettier-bug

```sh
yarn create react-app prettier-bug
cd prettier-bug
yarn add prettier
vi src/App.js
yarn start
```

Main change looks like:

```diff
diff --git a/package.json b/package.json
index 4fcd053..2b6e0c5 100644
--- a/package.json
+++ b/package.json
@@ -6,6 +6,7 @@
     "@testing-library/jest-dom": "^5.14.1",
     "@testing-library/react": "^12.0.0",
     "@testing-library/user-event": "^13.2.1",
+    "prettier": "^2.6.0",
     "react": "^17.0.2",
     "react-dom": "^17.0.2",
     "react-scripts": "5.0.0",
diff --git a/src/App.js b/src/App.js
index 3784575..6b6dbe2 100644
--- a/src/App.js
+++ b/src/App.js
@@ -1,7 +1,8 @@
-import logo from './logo.svg';
-import './App.css';
+import logo from "./logo.svg";
+import "./App.css";
 
 function App() {
+  console.log(import("prettier/parser-typescript"));
   return (
     <div className="App">
       <header className="App-header">
diff --git a/yarn.lock b/yarn.lock
index 3cd6d5d..c898d48 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -6852,6 +6852,11 @@ prelude-ls@~1.1.2:
   resolved "https://registry.yarnpkg.com/prelude-ls/-/prelude-ls-1.1.2.tgz#21932a549f5e52ffd9a827f570e04be62a97da54"
   integrity sha1-IZMqVJ9eUv/ZqCf1cOBL5iqX2lQ=
 
+prettier@^2.6.0:
+  version "2.6.0"
+  resolved "https://registry.yarnpkg.com/prettier/-/prettier-2.6.0.tgz#12f8f504c4d8ddb76475f441337542fa799207d4"
+  integrity sha512-m2FgJibYrBGGgQXNzfd0PuDGShJgRavjUoRCw1mZERIWVSXF0iLzLm+aOqTAbLnC3n6JzUhAA8uZnFVghHJ86A==
+
 pretty-bytes@^5.3.0, pretty-bytes@^5.4.1:
   version "5.6.0"
   resolved "https://registry.yarnpkg.com/pretty-bytes/-/pretty-bytes-5.6.0.tgz#356256f643804773c82f64723fe78c92c62beaeb"
```

Output looks like:

![image](https://user-images.githubusercontent.com/4915682/158908230-bc2d3e4b-87f5-48f4-b50a-53fdae34579a.png)

I see that the error is different that what I originally posted, but I'm sure create react app is doing some more fancier things. By default raw webpack will spit out the error that I have shown in my original post.

**Comment by fisker** [comment]
Thank you, I'll take a look.

**Comment by fisker** [comment]
I was able to reproduce on CI now, https://github.com/prettier/prettier/runs/5595666668?check_suite_focus=true#step:6:6, I'll look into it.
