### ISSUE TITLE
Upgrading to Prettier 1 strips all semis

### ISSUE THREAD

**Issue by ekosz** [prettier/prettier#1234]
Just upgraded to prettier 1.0 and it stripped out all of our semi-colons. But looking at the help doc it seems it shouldn't do that by default?

Here's the command we use:

```
prettier --write --print-width 100 --single-quote --trailing-comma all
```

**Comment by vjeux** [comment]
/fail. Just pushed 1.0.2, sorry about this!

**Comment by ekosz** [comment]
Perfect. Just upgraded and we're fixed. Thanks for the super fast turnover!
