### ISSUE TITLE
Prettier incorrect format comments for graphql operations

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#12358]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBHArnATgTwATB4DEeAzhALZx6QVWwA6UeeAZhBEwL4gA0IEAA4wAltFLJQAQyxYIAdwAKMhBJRSANvKk4J-AEZYpYANZwYAZSlUAMiKhxkrTaTgGjp8xcHH7Ac2QYLEx+OAp9OAATSKibKSg-dCk-OAAxCCwKKRhRBOQQKXQYCD4QAAsYCg0AdTKReFIfMDgLVXqRADd6nHywUj0Qe1csGEUjPyynFzcQACtSAA8Lfw04AEV0CHgpjVd+Hyxh-L8jQTLUDVLBLHsYapFImDLkAA4ABn25V2rT-Ou4YYdRz8DBbOBjIRqAqkAC0DiiUVKWDgGBEyLGyUmSGcuxmrgoIkCwTxK3Wm222Om-BgUn090ezyQACZqUYRBp-ABhShYkAAgCspXQrgAKrS1Di9iAOpgAJJQGKwCxgG7CACCCosMBwqx2ri4XCAA)

```sh
--parser graphql
```

**Input:**

```graphql
query { # some comment
  foo
}
```

**Output:**

```graphql
query {
  # some comment
  foo
}

```

**Expected behavior:**

same as input

Saw this bug while maintaining `graphql-eslint`, for example, real-life case if a comment is ESLint directive - like `# eslint-disable-line` prettier will break graphql linting

**Comment by Harry-Hopkinson** [comment]
I have fixed this issue - just uploading a PR now.

**Comment by Harry-Hopkinson** [comment]
Moving into draft to just cleanup the code.

**Comment by Harry-Hopkinson** [comment]
@B2o5T I have fixed the issue sorry it took a while

**Comment by fisker** [comment]
I don't think we want to change the output. We format similar JS code like this https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAXncdB6PAZwgFs51ISzYAdKddAMwgjoF8QAaECABxgCW0QslCoATuIgB3AAoSEIlKgA201AE8R3AEbjUYANZwYAZVRkAMgKhxkjVYTi79Rk6d4GbAc2QxxAK7OIHAkOnAAJhGRlqhQ3gGo3nAAYhDiJKgwgvHIaAEwEFwgABYwJCoA6iUC8ISeYHCmirUCAG61GnlghNogNk7iMLL63pn2jsEAVoQAHqY+KnAAigEQ8BMqTtye4oN5OqjhKsW84jYwlQIRMCXIABwADDtSTpX6vHlncINtdtwARzW8BGfCUaEIAFpbJFIsVxHAgQIESMkuMkA4tsEnCQBH5AtjFitgXYMZNuDAjlcbnckAAmCn6AQqHwAYVI6JChAArMUAk4ACpHJSY7YgNpBACSUGisFMYHO-AAgjLTDANEtNk42GwgA

**Comment by fisker** [comment]
That's known issue.

Can use `eslint-disable-next-line` instead?

**Comment by B2o5T** [comment]
Yeah it works, but it’s like a workaround to fix actual problem, it will be nice to fix the actual problem for all languages even it’s tricky because of dealing with comments

**Comment by thorn0** [comment]
@B2o5T That's how Prettier works (see the [docs](https://prettier.io/docs/en/rationale.html#comments)). It might move comments, it also might break lines, so line-scoped magic comments get broken. This problem is fundamentally unsolvable unless we want to treat these comments like `// prettier-ignore`. It's just something to keep in mind if you use Prettier. 🤷‍♂️
