### ISSUE TITLE
Unnecessary line breaks caused by `ifBreak` with group id nested in `group` with the same id

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#12352]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEmBmEBOmAFJFAM4yZn5gAKAhjABaYQ6YDaAjAEwDMAGky8+AfRHj+QiTP7jpYiXyVdRAFj48AugEpM6LJgC+GIyAEgIABxgBLaGWSh6+fBADuDfAkcp6AG3d6AE9HCwAjfHowAGs4GABlegBbOAAZWyg4ZBwAsjgIqNj4hKtozIBzZBh8AFcCkDhk8LgAE1a2tPooCtr6CrgAMQJkxjse5BB6WpgIcxAmGGT-AHUmW3gyMrA4BJ8N2wA3DeDJsDIwkEz8-BhaKIrRnLyGgCsyAA8Eyv84AEVahB4M9-PkLGV8DdJuF6C1-PMrPhMjAVrZWsxkAAOAAM4Lc+RWUSsk0RcBuh2yFgAjoD4PdrL4pmQALRZNptebeGm2bz3fpPJC5UENfLJWzVOoin7-WnZQUvCwwWGo9FMZA8RVRWz+SoAYQgyQFjTIAFZ5rV8gAVWG+IVgkCHeoASSgHVgCTASJsAEFXQkYMFfiD8kYjEA)

```sh
--parser babel
```

**Input:**

```jsx
{
  for (const srcPath of [123, 123_123_123, 123_123_123_1, 13_123_3123_31_432]) {
  }
}
```

**Output:**

```jsx
{
  for (const srcPath of [
    123, 123_123_123, 123_123_123_1, 13_123_3123_31_432,
  ]) {
  }
}

```

**Expected behavior:**

Should format as input.

Found this when playing with the "doc", in this case, the input is exactly 80 width. I think there should be bug in the doc print.

The test code from https://github.com/prettier/prettier/blob/2cde2dbf9d280260f8c499039d89419b21fa4dc0/tests/format/js/arrays/issue-10159.js#L3

@thorn0 You may interest.

**Comment by thorn0** [comment]
It's known: #10159
I'll close that issue in favor of this one because you have a better description here.

**Comment by fisker** [comment]
Sorry, totally forgot about that.

**Comment by fisker** [comment]
After debugging with your doc [here](https://github.com/prettier/prettier/pull/10160#issuecomment-768668404), I think the bug is in `fits()`, maybe also related to how [`line` works in `fits()`](https://github.com/prettier/prettier/blob/896970a18518bc31f1f15233b5ec612394453624/src/document/doc-printer.js#L246)
