### ISSUE TITLE
Flow comment in return value of class method moved to params

### ISSUE THREAD

**Issue by tmcw** [prettier/prettier#1235]
Playground: https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Foo%20%7B%5Cn%5Ctbar()%20%2F*%3AFoo%20*%2F%20%7B%5Cn%20%20%20%20%20%20return%201%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Input:

```js
class Foo {
	bar() /*:Foo */ {
      return 1;
    }
}
```

Output:

```js
class Foo {
  bar(/*:Foo */) {
    return 1;
  }
}
```

This breaks Flow's type inference because the comment is no longer treated as a return type.

**Comment by vjeux** [comment]
Unfortunately, the way prettier handles comments, it's very hard to put them back exactly where they were inputted. We have another issue tracking this https://github.com/prettier/prettier/issues/719

Right now, prettier won't work for this use case I'm afraid. This is something we want to get to at some point though.

**Comment by vjeux** [comment]
This has been fixed :)
