### ISSUE TITLE
Destructuring from object with property moves object to new line

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#1236]
Bad title, what I mean is this sort of code:

```js
const {
  somehting,
} = someObject.deep;
```

See https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20%7B%5Cn%20%20updated%2C%5Cn%20%20author%3A%20%7B%20identifier%3A%20ownerId%20%7D%2C%5Cn%20%20location%2C%5Cn%20%20category%3A%20categories%2C%5Cn%7D%20%3D%20rawAd.entry%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

I'd expect it to not move to a new line unless it would have to break.

Compare to https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20%7B%5Cn%20%20updated%2C%5Cn%20%20author%3A%20%7B%20identifier%3A%20ownerId%20%7D%2C%5Cn%20%20location%2C%5Cn%20%20category%3A%20categories%2C%5Cn%7D%20%3D%20rawAd%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by SimenB** [comment]
This worked as I wanted it to in 0.22, btw.

**Comment by statianzo** [comment]
Also, the newline behavior doesn't happen if the right side of the = starts with `this`.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20%7B%5Cn%20%20updated%2C%5Cn%20%20author%3A%20%7B%20identifier%3A%20ownerId%20%7D%2C%5Cn%20%20location%2C%5Cn%20%20category%3A%20categories%2C%5Cn%7D%20%3D%20this.rawAd.entry%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by SimenB** [comment]
Huh, interesting that `this` seems to short-circuit whatever messes it up in the first place. Nice spot!
