### ISSUE TITLE
Prettier removes trailing comma from multiline type with `trailingComma: all`

### ISSUE THREAD

**Issue by KirillGalimov** [prettier/prettier#12389]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYgSwCcBnGAFUzgHV8YALANTkLQBloBzAOQEMBbHAF5swADpRs2HkmxQArnwBGzANziAvuPHos2AMpxIUACYUsNekxbso3fkJHjJimfKWqNW2JTz4oPABszalpGZjZOXgFsYQBtJ18SckoLMOtI+wAaBIA6PIMjUxTQqwjbKLhYgF1sqCqVEEyQCAwYfGhiZFAeQkIIAHcABR6ETpRA-p40TqbFQh4wAGs4GD17Vj84ZAAzQOI4Wfmllb0MBb8OZBhCOQOQOHdjYzhjVh5bOR4OOFwIQj4eDA2rZkCAeHIYBBGiA6DA+AEqHRaHBiGcwHADFBiLR8AA3WhoUFgYgzEB+faEGCDeYcAE7PZ3ABWxAAHnoLgE4ABFOQQeD0gL7JpnEjMUE6FFgQj4VrQjDS2A0Yz0ZAADgADMK+vsqPMMKD5SjmLitk0AI68+DUlpjMHEAC0UDgLxe0MIcAtRDg1K+dKQu0Fd32fHwVxuQY53MtW39DKaMB4iiVKqQACZ4-N8AELgBhCB8P1ggIBaFyfZkRNjANCkC424ASRMCFWUplMAAgiY9OhOQL9up1EA)

```sh
# Options:
--parser typescript
--trailingComma all
```

**Input:**

```jsx
type FirstTypeWithVeryLongName = {
  a: number;
}

type SecondTypeWithVeryLongName = {
  b: number;
}

type FinalTypeWithVeryLongName = [
  FirstTypeWithVeryLongName,
  ...SecondTypeWithVeryLongName[],
];
```

**Output:**

```jsx
type FirstTypeWithVeryLongName = {
  a: number;
};

type SecondTypeWithVeryLongName = {
  b: number;
};

type FinalTypeWithVeryLongName = [
  FirstTypeWithVeryLongName,
  ...SecondTypeWithVeryLongName[]
];
```

**Expected behavior:**
Prettier doesn't remove trailing comma from `FinalTypeWithVeryLongName` after `...SecondTypeWithVeryLongName[]` and thus doesn't conflict with `@typescript-eslint/comma-dangle` rule.

**Comment by taejs** [comment]
https://github.com/prettier/prettier/issues/11684
It's also reproduced

**Comment by sosukesuzuki** [comment]
This is a remnant of the old TS spec of placing rest elements only at the end of a tuple. I think we can fix this.

**Comment by sosukesuzuki** [comment]
We can put leading/middle rest type in tuples types since TypeScript 4.2 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html#leadingmiddle-rest-elements-in-tuple-types
