### ISSUE TITLE
Prettier is not respecting ignoring a markdown file

### ISSUE THREAD

**Issue by basickarl** [prettier/prettier#12387]
Prettier is not respecting ignoring a markdown file according to the documentation: https://prettier.io/docs/en/ignore.html#markdown

[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRE7YB8AOlADKkDOMSbuAMVIEeOGAAtSUavxwBlOJCgATMZOkgANCAh4y0LslABDAgQgB3AAqmEhlMYA2F4wE9D2gEYFjYANbEcsYAtnCcUHDIAGZOXHBePv6BeL5S1MgwBACu8SBwwZ5wyspF7MbSWcbUcAL0wcYkacggxlkwEFog4jDBjgDqkvBcKWBwClBcpGQAblOuzWBcHiBScQQwVj7U9dGxuQBWXAAecmmOcACKWRDwu45x2ikiFM31BH7KllCdhFIwfaRlBJkAAOAAMj3McT6PjwzUIcDW00i2gAjtd4JtdPYWlxMBEikVOkR0cI4JsqjskDF7rk4sFSBlsnSzpcMZFqXttDBjJ4AUDxMgAEzcnykRxpADCEGCVLyXAArJ0snEACq8+w0h4gaY5ACSKgQMDkYAIpD0AEEVHIYK5znc4gBfR1AA)

Input:
```
<!-- prettier-ignore -->
List:
- First thing
- Second thing
```
Output:
```
<!-- prettier-ignore -->
List:

- First thing
- Second thing
```
Terminal:
```
["INFO" - 5:24:18 PM] Formatting file:///Users/karl/Development/hello/.vscode/.ignore/TERMS
["INFO" - 5:24:18 PM] Using config file at '/Users/karl/Development/hello/.vscode/.prettierrc'
["INFO" - 5:24:18 PM] Using ignore file (if present) at /Users/karl/Development/hello/.prettierignore
["INFO" - 5:24:18 PM] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 5:24:18 PM] Parser not inferred, trying VS Code language.
["INFO" - 5:24:18 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:24:18 PM] Prettier Options:
{
  "filepath": "/Users/karl/Development/hello/.vscode/.ignore/TERMS",
  "parser": "markdown",
  "bracketSpacing": true,
  "singleQuote": true,
  "tabWidth": 2,
  "printWidth": 100,
  "semi": true,
  "trailingComma": "es5",
  "jsxBracketSameLine": false,
  "arrowParens": "avoid",
  "jsxSingleQuote": false
}
["INFO" - 5:24:18 PM] Formatting completed in 0.01ms.

```

**Comment by TimJ0212** [comment]
It seems as if line breaks, and only line breaks, in Markdown are generally not affected by the prettier-ignore.
The example of the documentary works for the spacing, but not the line breaks.
[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRE7YB8AOlGwCIQ490w88AZvQC2AQ348YAC1IBnEABoQEPGWgKkoMQQIQA7gAUdCTSDEAbfWICeC5QCMCYsAGtiAZTEi4AGVJQcMiClnJwjs5unnguAdTIMAQAruEgcCIOcAAmWdm+YlDUSWLUcABiohJkhcjmSTAQSiDSMCIWAOqy8HIxYHAepqRkAG5DNrVgcvYgAWEEMIbO1OLBoakAVnIAHh5xFnAAikkQ8KsWYcoxBHO14gSuWQZQTYQBMO2kWTLIABwADJc9GF2s48LVCHA5sMgsoAI7HeCLVRmMRyTCBbLZJpEeGkIiLEorJAhc6pMIiUgJZJkvaHBFBYlrZQwMQOD5faTIABMzOcpAscQAwhARES0nIAKxNJJhAAqrM0JIuIGGKQAklBcrAPGACKQ1ABBTUeGA2fZnMIAX0tQA)

**Comment by kachkaev** [comment]
I guess you need `<!-- prettier-ignore-start -->` / `<!-- prettier-ignore-end -->` for multi-line chunks with ignored formatting.

```makrdown
<!-- prettier-ignore-start -->

List:
- First thing
- Second thing

<!-- prettier-ignore-end -->
```

[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRGYDOMAhgTDtgHwA6UfAGVLMkfXADFSBZjhgALUlGpicAZTiQoAE1kKlfPhmz4iJcpRp0GCHdxAAaEBDxlojZKDYEIAdwAKbAjuKCwANj4sAJ7ujgBGBCxgANbEqiwAtnBCUHDIAGZhjHBxCcmpeImK1MgwBACuxSBw6bFwWlptAixKdSzUcOL06SxmSsggLHUwEA4gcjDpoQDqCvCMFWBw6lCMpGQAbnuR42CMMSCKRex+CdTD+YWNAFaMAB6qVaFwAIp1EPAPUJFRwVaQUcbDAhJLS+KCzQiKGBLUhaeTIAAcAAYQd4iksEnhxoQ4Fd9rlHABHP7wG7OYITRiYHJtNqzIhUqRwG59e5IApAxpFdKkGr1QWfH7U3J8x6OVixZGouTIABMcoSpFCVQAwhB0rymowAKyzOpFAAqLFiwX5wJA+waAEltAgYKowARSC4AILaVQwSJfQFFAC+IaAA)

If you use `<!-- prettier-ignore -->`, only one line is ignored.
