### ISSUE TITLE
number calculation expressions in jsx get clobbered

### ISSUE THREAD

**Issue by thurt** [prettier/prettier#1238]
before:
```javascript
<MyComponent
   myProp={2 * (125 + (2 * value))}
/>
```

after `prettier --single-quote --list-different --write`:
```javascript
<MyComponent
   myProp={
     2 *
       (125 +
         2 * value)
  }
/>
```

**Comment by thurt** [comment]
just a side-note: prettier is removing the inner parentheses also, which causes an eslint "no-mixed-operators" error on my setup.

**Comment by vjeux** [comment]
Could you check which version of prettier you are using, it now looks like

```js
<MyComponent myProp={2 * (125 + 2 * value)} />;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3CMyComponent%5Cn%20%20%20myProp%3D%7B2%20*%20(125%20%2B%20(2%20*%20value))%7D%5Cn%2F%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by thurt** [comment]
thanks! after looking at your example, i realized it was just a printWidth issue. my `value` was actually nested in an object, so the name to retrieve it was quite long, going over the 80 char printWidth.

here's a reproduction for clarity sake

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3CMyComponent%5Cn%20%20myProp%3D%7B2%20*%20(125%20%2B%20(2%20*%20valueaetnshuastehusn.aeueaou%5Baetnhuoesnhtu%5D.notehusnetoahushroe%20))%7D%5Cn%2F%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Oh okay. Yeah, this is the way we print binary operations. We haven't found a perfect way to print them but the current way usually looks good. You may want to put it in some smaller nesting to get it more readable.
