### ISSUE TITLE
Extraneous newline between = and destructuring source

### ISSUE THREAD

**Issue by hawkrives** [prettier/prettier#1240]
[[online demo](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20%7B%5Cn%20%20type%2C%5Cn%20%20revision%2C%5Cn%20%20slug%2C%5Cn%20%20isCustom%2C%5Cn%20%20name%2C%5Cn%20%20_area%2C%5Cn%20%20_progress%2C%5Cn%20%20_error%2C%5Cn%20%20_checked%2C%5Cn%7D%20%3D%20props.area%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)]

Prettier@1.0.2 is adding an extra newline between the = and the source in a large object destructuring expression.

```js
const {
  type,
  revision,
  slug,
  isCustom,
  name,
  _area,
  _progress,
  _error,
  _checked,
} = props.area

// becomes

const {
  type,
  revision,
  slug,
  isCustom,
  name,
  _area,
  _progress,
  _error,
  _checked,
} = 
  props.area
```

I would expect `props.area` to remain on the same line as the `=`.

Congrats on v1!

**Comment by SimenB** [comment]
Dupe of #1236, right?

**Comment by hawkrives** [comment]
Yup, exactly the same problem. Thanks!
