### ISSUE TITLE
Opinion: destructuring breaks on property access instead of inside the destructuring expression

### ISSUE THREAD

**Issue by hawkrives** [prettier/prettier#1241]
[[online demo](https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20x%20%7B%5Cn%5Ctrender()%20%7B%5Cn%5Ct%5Ctconst%20%7B%5Cn%20%20%5Ct%5Ct%5Ctcourse%2C%5Cn%20%20%5Ct%5Ct%5Ctconflicts%20%3D%20%5B%5D%2C%5Cn%20%20%5Ct%5Ct%5Ctindex%2C%5Cn%20%20%5Ct%5Ct%5CtscheduleId%2C%5Cn%20%20%5Ct%5Ct%5CtstudentId%2C%5Cn%5Ct%5Ct%7D%20%3D%20this.props%5Cn%5Ct%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)]

With `--tab-width=4` to ensure this demo goes over 80 columns:

```js
// prettier v0.22
class x {
	render() {
		const {
  			course,
  			conflicts = [],
  			index,
  			scheduleId,
  			studentId,
		} = this.props
	}
}

// becomes (v1.0.2)
class x {
    render() {
        const { course, conflicts = [], index, scheduleId, studentId } = this
            .props;
    }
}
```

I would expect Prettier to do it used to do, and break inside the destructuring expression rather than breaking on the property access.

**Comment by vjeux** [comment]
Thanks for the concrete example. We can add more cases to https://github.com/prettier/prettier/pull/1036!
