### ISSUE TITLE
"as" TypeScript keyword yields error within Vue template

### ISSUE THREAD

**Issue by serhez** [prettier/prettier#12414]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlKlgAQBuAtAJYBmAvMSHQM4BiEOAJnACcAFAzo44ASlaFgwCiLFwKedhQwBPDBF4BXcQDpufQRP388vHHShKAvrdQB6LIQpv3pJ5lwE4JKJ7sYAJ0WDAU+FAA5iwgMOzSno5BIWH+gcGh4exwMDqUkTGs8YlkyZlppIEw6uIUQRBYcLwReNGxQewJIP5O7DXihCAANCCNMHTQ7MigeAICEADuAApzCNMoeDiLeOrTowBGAnhgANa5AMp4GHAAMtZwyAxbOYfHZ5dYJ9ZRyDACOjgozgGAOzX4vFubSiOjwUTg3AEGAIE2iyBAeB0MAgIxAAAsYBgcAB1PF0eDsL5gOAXdbkuhUcnqdFgLq46w5AQwZbHKLIp4vIEgABW7AAHhcfuIAIo6CDwAU4V4gL4CTnoqiA3FYEKwYl0XgwPHIACMACYAAyjHUQHLE45YdE6uCcqiPUYARzl8B5jQ2GPYNBszWauIEcC9dHDPLh-KQzyVQpyGDofwBSalcFl8seSH+gNGMDwB31huNSAALIXjmIfgBhCAYOMgF0AVlxOhyABVixsE8rNXAAJJQfiwC4VGAAQVHFwGuf7cHsQA)

```sh
# Options:
--parser vue
--embedded-language-formatting auto
--single-quote
--tab-width 4
--print-width 120
```

**Input:**

```vue
<template>
<p v-if="isFolder(file)">{{ (file as mymodule.Folder).deadline }}</p>      
</template>

<script lang="ts">
</script>

<script setup lang="ts">
</script>

<style scoped lang="scss">
</style>
```

**Output:**

```vue
SyntaxError: Unexpected token, expected "," (1:8)
> 1 |  (file as mymodule.Folder).deadline 
    |        ^
```

**Expected behavior:**
`prettier` should recognise TypeScript patterns such as the `as` keyword within Vue templates. I believe this issue has to do with the `--embedded-language-formatting` system not being able to parse the keyword, as when this option is set off the error is not given; however, setting this option off is not a suitable solution as it is quite useful.

**Comment by fisker** [comment]
Any reference that this is allowed in Vue SFC?

**Comment by serhez** [comment]
@fisker I don't know about any Vue doc covering this specific use case, so official support on this is unknown to me. However, AFAIK Vue 3 fully supports TypeScript and the `as` keyword is part of the language. Furthermore, my app runs just fine with a bunch of `as` keywords in the templates, including an identical example to the given above (which is not the same as Vue officially supporting it, which is what you are asking, but still).

For more context, prettier not only throws an error with the `{{ }}` syntax, but also with things like:

```vue
<p v-if="isFolder(file as mymodule.Folder)">test</p>
```

**Comment by serhez** [comment]
@fisker never mind, it is officially supported. [Here](https://vuejs.org/guide/typescript/overview.html#typescript-in-templates) you have an example in the official docs.

**Comment by fisker** [comment]
Thank you.

**Comment by serhez** [comment]
To add a bit more context: using the `as` keyword within the `<script>` section does work fine, so the bug is only happening with embedded TS within templates.

**Comment by fisker** [comment]
> We need to update the vue expression parser to allow typescript syntax, luckily we have babel-ts, so we don't need use typescript parser.

Original posted https://github.com/prettier/plugin-pug/issues/365#issuecomment-1085622997

That's a related issue.
