### ISSUE TITLE
[Feature Request] Add an option for arrowParens: 'off'

### ISSUE THREAD

**Issue by adamma1024** [prettier/prettier#12420]
Since I was responsible for eslint and prettier rules, I was almost crazed for being involved in the rules war. In the end, we decided to close all the rules unnecessary. I have no idea to close the `arrowParens`

- `arrowParens`
- `singleAttributePerLine` (I find it'll be resolved in v2.6, looking forward to it)

**Input:**

```jsx
const A = e => {
    // do something
}
const B = (e) => {
    // do something
}
```

**Output:**
 `arrowParens: 'avoid'`
```jsx
const A = e => {
    // do something
}
const B = e => {
    // do something
}
```
 `arrowParens: 'always'`
```jsx
const A = (e) => {
    // do something
}
const B = (e) => {
    // do something
}
```

**Expected behavior:**
 `arrowParens: 'off'`
```jsx
const A = e => {
    // do something
}
const B = (e) => {
    // do something
}
```

prettier: 2.5.1
eslint-config-prettier: 8.5.0

**Comment by adamma1024** [comment]
And this rule `no-mixed-operators` didn't work.

**Comment by fisker** [comment]
we won't accept this.

**Comment by adamma1024** [comment]
> We won't accept this.

Ok, thank you for your response
