### ISSUE TITLE
The Playground page is not working

### ISSUE THREAD

**Issue by ines15ayari** [prettier/prettier#12432]
Hello everyone, 
Although I cloned the project properly and downloaded all the packages and dependencies needed to run the project, the 'Playground Page' in the navigation bar of the Prettier home page is not working, and it keeps loading for a long time.
And these are some screenshots of the errors found in the console when inspecting:
![Capture d’écran 2022-03-10 231347](https://user-images.githubusercontent.com/67631604/157767693-a7e10851-e5ce-4edd-839b-19157f17663d.png)
![Capture d’écran 2022-03-10 234434](https://user-images.githubusercontent.com/67631604/157767699-f4cfe539-4ba4-4725-bd29-246efc8cecb1.png)

Any help?
Thanks

**Comment by fisker** [comment]
Did you follow the steps https://github.com/prettier/prettier/tree/main/website#getting-started ?
