### ISSUE TITLE
Not all the community plugins tools are mentioned in the site

### ISSUE THREAD

**Issue by MohamedLiratni** [prettier/prettier#12431]
The Steps are as follow:
1. Go to https://prettier.io/
2. Scroll down to "Works with the tools you use"

In here we can see that *Community Plugins* doesn't mention all the examples that you see when you search "community plugins" in the search bar. An easy way to fix this is to redirect *Community plugins* to this link https://prettier.io/docs/en/plugins.html#community-plugins which mentions all the plugins used

(just like Yaml and GraphQL are redirected to their websites by clicking on them)

**Comment by kachkaev** [comment]
👍 Or we can keep the header as is and append something a new list item saying something like `and more`.

**Comment by Harry-Hopkinson** [comment]
I can have a look into this.
