### ISSUE TITLE
Extraneous prefix semicolon inside if-statement

### ISSUE THREAD

**Issue by hawkrives** [prettier/prettier#1244]
[[online demo](https://prettier.github.io/prettier/#%7B%22content%22%3A%22if%20(expr%20%3D%3D%3D%20'boolean')%20%7B%5Cn%20%20(%7B%20x%20%7D%20%3D%20compute())%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)]

```js
if (expr === 'boolean') {
  ({ x } = compute())
}

// becomes

if (expr === "boolean") {
  ;({ x } = compute())
}
```

I'd prefer it if the semicolon wasn't there? But I can probably get used to it and/or refactor this part of my code.

**Comment by bakkot** [comment]
This is [on purpose](https://github.com/prettier/prettier/issues/736#issuecomment-291934981).

**Comment by lourd** [comment]
I have an issue related to this, but it's additionally in the context of do expressions.

[Reproduction](https://prettier.github.io/prettier/#%7B%22content%22%3A%22render%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%7B%20do%20%7B%5Cn%20%20%20%20if%20(isDashboardRoute(this.props.location))%20%7B%5Cn%20%20%20%20%20%20if%20(!this.props.loggedIn)%20%7B%5Cn%20%20%20%20%20%20%20%20%3CRedirect%20to%3D%7B%7B%20pathname%3A%20'%2Flogin'%2C%20state%3A%20%7B%20from%3A%20this.props.location%20%7D%20%7D%7D%20%2F%3E%5Cn%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20%20%3CDashboard%20key%3D%5C%22d%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%20else%20if%20(isAccountsRoute(this.props.location))%20%7B%5Cn%20%20%20%20%20%20%3CAccounts%20key%3D%5C%22a%5C%22%20%2F%3E%5Cn%20%20%20%20%7D%20else%20if%20(this.props.location.pathname%20%3D%3D%3D%20'%2Fconsole')%20%7B%5Cn%20%20%20%20%20%20%3CRoute%5Cn%20%20%20%20%20%20%20%20key%3D%5C%22c%5C%22%5Cn%20%20%20%20%20%20%20%20path%3D%5C%22%2Fconsole%5C%22%5Cn%20%20%20%20%20%20%20%20component%3D%7BConsole%7D%5Cn%20%20%20%20%20%20%20%20restrictTo%3D%7BPermissions.LoggedIn%7D%5Cn%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%3CRedirect%20to%3D%5C%22%2Flogin%5C%22%20%2F%3E%5Cn%20%20%20%20%7D%5Cn%20%20%7D%7D%5Cn%3C%2Fdiv%3E%5Cn%20%20)%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

_Before_
```js
<div>
  { do {
    if (isDashboardRoute(this.props.location)) {
      if (!this.props.loggedIn) {
        <Redirect to={{ pathname: '/login', state: { from: this.props.location } }} />
      } else {
        <Dashboard key="d" />
      }
    } else if (isAccountsRoute(this.props.location)) {
      <Accounts key="a" />
    } else if (this.props.location.pathname === '/console') {
      <Route
        key="c"
        path="/console"
        component={Console}
        restrictTo={Permissions.LoggedIn}
      />
    } else {
      <Redirect to="/login" />
    }
  }}
</div>
```

_After_
```
<div>
  {
    do {
      if (isDashboardRoute(this.props.location)) {
        if (!this.props.loggedIn) {
          ;<Redirect
            to={{ pathname: "/login", state: { from: this.props.location } }}
          />
        } else {
          ;<Dashboard key="d" />
        }
      } else if (isAccountsRoute(this.props.location)) {
        ;<Accounts key="a" />
      } else if (this.props.location.pathname === "/console") {
        ;<Route
          key="c"
          path="/console"
          component={Console}
          restrictTo={Permissions.LoggedIn}
        />
      } else {
        ;<Redirect to="/login" />
      }
    }
  }
</div>
```

I think the leading semicolon definitely isn't wanted here. The prettified code still works as before, after transpiled with the `transform-do-expressions` Babel plugin, but there is a slightly different output.

For reference, [here's the Babel transform before](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=react%2Cstage-0&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code=render%20%3D%20()%20%3D%3E%20%7B%0A%20%20return%20(%0A%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%7B%20do%20%7B%0A%20%20%20%20%20%20%20%20if%20(isDashboardRoute(this.props.location))%20%7B%0A%20%20%20%20%20%20%20%20%20%20if%20(!this.props.loggedIn)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CRedirect%20to%3D%7B%7B%20pathname%3A%20'%2Flogin'%2C%20state%3A%20%7B%20from%3A%20this.props.location%20%7D%20%7D%7D%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CDashboard%20key%3D%22d%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%20else%20if%20(isAccountsRoute(this.props.location))%20%7B%0A%20%20%20%20%20%20%20%20%20%20%3CAccounts%20key%3D%22a%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%7D%20else%20if%20(this.props.location.pathname%20%3D%3D%3D%20'%2Fconsole')%20%7B%0A%20%20%20%20%20%20%20%20%20%20%3CRoute%0A%20%20%20%20%20%20%20%20%20%20%20%20key%3D%22c%22%0A%20%20%20%20%20%20%20%20%20%20%20%20path%3D%22%2Fconsole%22%0A%20%20%20%20%20%20%20%20%20%20%20%20component%3D%7BConsole%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20restrictTo%3D%7BPermissions.LoggedIn%7D%0A%20%20%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%3CRedirect%20to%3D%22%2Flogin%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20)%0A%7D%0A&playground=true), and [here's the Babel transform after](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=react%2Cstage-0&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code=render%20%3D%20()%20%3D%3E%20%7B%0A%20%20return%20(%0A%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20do%20%7B%0A%20%20%20%20%20%20%20%20%20%20if%20(isDashboardRoute(this.props.location))%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(!this.props.loggedIn)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3B%3CRedirect%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20to%3D%7B%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pathname%3A%20%22%2Flogin%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20state%3A%20%7B%20from%3A%20this.props.location%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3B%3CDashboard%20key%3D%22d%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%20else%20if%20(isAccountsRoute(this.props.location))%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3B%3CAccounts%20key%3D%22a%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%7D%20else%20if%20(this.props.location.pathname%20%3D%3D%3D%20%22%2Fconsole%22)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3B%3CRoute%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20key%3D%22c%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20path%3D%22%2Fconsole%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20component%3D%7BConsole%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20restrictTo%3D%7BPermissions.LoggedIn%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3B%3CRedirect%20to%3D%22%2Flogin%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20)%0A%7D%0A&playground=true).

**Comment by bakkot** [comment]
@lourd, that's on purpose for the same reason as the parentheses case. In particular, if the previous line is an expression, it won't parse without the semicolon:

```js
if (!this.props.loggedIn) {
  console.log('debug')
  <Redirect // SyntaxError
    to={{ pathname: "/login", state: { from: this.props.location } }}
  />
}
```

I don't think it makes sense to put it there for the `(` and not the `<`, and I think a majority of the no-semi people want in there for `(` for the reason linked above.

This is the price you pay for the no-semi style.

**Comment by lourd** [comment]
Hey @bakkot, thanks for your quick response. I've played around with some more expressions and understand do statements a little better now. I agree, looks like I'll just have to deal if I want semi-colon free style.

I am confused about the difference in [these two cases](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=react%2Cstage-0&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code=const%20React%20%3D%20%7B%20createElement()%20%7B%7D%20%7D%0A%0Alet%20a%20%3D%202%0Alet%20b%20%3D%20do%20%7B%0A%20%20if%20(a)%20%7B%0A%20%20%20%20console.log('a%20is'%2C%20a)%0A%20%20%20%204%0A%20%20%20%20console.log('funny%20joke%20here')%0A%20%20%20%206%0A%20%20%7D%0A%20%20else%205%0A%7D%0Aconsole.log('b%20is'%2C%20b)%0A%0Alet%20c%20%3D%20%0A%20%20%3Cdiv%3E%0A%20%20%7B%0A%20%20%20%20do%20%7B%0A%20%20%20%20%20%20if%20(true)%20%7B%0A%20%20%20%20%20%20%20%20console.log('hmm%3F')%0A%20%20%20%20%20%20%20%20%2F%2F%20This%20fails%0A%20%20%20%20%20%20%20%20%2F%2F%20%3Cspan%3EHmm%3C%2Fspan%3E%0A%20%20%20%20%20%20%20%20%2F%2F%20This%20works%0A%20%20%20%20%20%20%20%20%3B%3Cspan%3EHmm%3C%2Fspan%3E%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20console.log('whaaa')%0A%20%20%20%20%20%20%20%20%2F%2F%20Fails%0A%20%20%20%20%20%20%20%20%2F%2F%20%3Cspan%3EWhaaa%3C%2Fspan%3E%0A%20%20%20%20%20%20%20%20%2F%2F%20Works%0A%20%20%20%20%20%20%20%20%3B%3Cspan%3EWhaaa%3C%2Fspan%3E%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%3C%2Fdiv%3E&playground=true) — a do expression within JSX, versus plain variable assignment. The variable assignment case runs without semi colons, either after the log expressions or before the numbers, but the JSX case does not.

```js
let a = 2
let b = do {
  if (a) {
    console.log('a is', a)
    4
    console.log('funny joke here')
    6
  }
  else 5
}
console.log('b is', b)

let c = 
  <div>
  {
    do {
      if (true) {
        console.log('hmm?')
        // This fails
        // <span>Hmm</span>
        // This works
        ;<span>Hmm</span>
      } else {
        console.log('whaaa')
        // Fails
        // <span>Whaaa</span>
        // Works
        ;<span>Whaaa</span>
      }
    }
  }
  </div>

// console output
/*
"a is" 2
"funny joke here"
"b is" 6
"hmm?"
*/
```

**Comment by bakkot** [comment]
@lourd:

So, a bit about the JavaScript grammar. It technically requires semicolons at the end of most statements. You can get away without them in *some* cases through what's called Automatic Semicolon Insertion, or ASI, which basically amounts to "if a line ends without a semicolon, but there's no way to parse the start of the next line as a continuation of the current one, the parser is to pretend there was a semicolon there".

```js
console.log('a is', a)
4
```

parses because there's no way to consider the `4` as a continuation of the `console.log('a is', a)`: `console.log('a is', a)4` is not the start of any valid JavaScript statement. So the parser performs ASI before the 4. (But if instead you had `(4)`, it could be: `console.log('a is', a)(4)` is syntactically valid, even if it doesn't work at runtime because `console.log` doesn't return a function, so you'd need to write a semicolon there.)

Same deal when followed by a variable assignment: `console.log('a is', a)let a` isn't valid syntax, so the parser inserts a semicolon before the `let`.

Conversely, `f()<bar` _is_ valid syntax, so the parser does not perform ASI in

```js
console.log('debug')
<Redirect
```

and it doesn't parse as you intended (and then later chokes on the `{{`).

**Comment by lourd** [comment]
Thank you for your articulate answer @bakkot.

I am confused about your second example. `f()<bar` is really `f()React.createElement('bar', ...`, which is not valid syntax, so would be a case where the semicolon is inserted. 

```js
let b = do {
  if (true) {
    console.log('hmm')
    <span>Haaa</span>
    // Works
    // ;<span>Haa</span>
  }
}

let c = do {
  if (true) {
    console.log('haa')
    React.createElement('span', null, 'haa')
  }
}
```

[Playing around with this in Babel](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=react%2Cstage-0&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code=let%20b%20%3D%20do%20%7B%0A%20%20if%20(true)%20%7B%0A%20%20%20%20console.log('hmm')%0A%20%20%20%20%3Cspan%3EHaaa%3C%2Fspan%3E%0A%20%20%7D%0A%7D%0A%0Alet%20c%20%3D%20do%20%7B%0A%20%20if%20(true)%20%7B%0A%20%20%20%20console.log('haa')%0A%20%20%20%20React.createElement('span'%2C%20null%2C%20'haa')%0A%20%20%7D%0A%7D&playground=true) confirms your reasoning — the former example fails unless there's a semicolon. But, they both convert to the same thing.

Is a JSX node considered an expression, where the converted code is not?

**Comment by bakkot** [comment]
@lourd, it has to be parsed before it can be translated to `React.createElement`. That translation happens way down the line; at this stage it's just reading the raw characters you wrote and trying to make sense of them.

**Comment by rattrayalex** [comment]
Closing in favor of #1433 , which specifically addresses the JSX case.

As mentioned above, this is is otherwise behaving as intended.
