### ISSUE TITLE
Semicolon is inserted in front of a comment, instead of the expression

### ISSUE THREAD

**Issue by hawkrives** [prettier/prettier#1245]
[[online demo](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20error%20%3D%20new%20Error(response.statusText)%3B%5Cn%2F%2F%20a%20comment%5Cn(error%3A%20any).response%20%3D%20response%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)]

```js
let error = new Error(response.statusText);
// a comment
(error: any).response = response

// becomes

let error = new Error(response.statusText)
;// a comment
(error: any).response = response
```

I would expect the semicolon to be inserted at the beginning of the `(error: any)`, rather than in front of the comment.

**Comment by hawkrives** [comment]
This is an unstable comment: [online demo](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20initial%5Cnlet%20error%20%3D%20new%20Error(response.statusText)%3B%5Cn%2F%2F%20a%20comment%5Cn(error%3A%20any).response%20%3D%20response%5Cn%5Cn%2F%2F%20round%201%5Cnlet%20error%20%3D%20new%20Error(response.statusText)%5Cn%3B%2F%2F%20a%20comment%5Cn(error%3A%20any).response%20%3D%20response%5Cn%5Cn%2F%2F%20round%202%3A%20stable%5Cnlet%20error%20%3D%20new%20Error(response.statusText)%20%2F%2F%20a%20comment%5Cn%3B(error%3A%20any).response%20%3D%20response%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

```js
// initial
let error = new Error(response.statusText);
// a comment
(error: any).response = response

// round 1
let error = new Error(response.statusText)
;// a comment
(error: any).response = response

// round 2: stable
let error = new Error(response.statusText) // a comment
;(error: any).response = response
```

**Comment by vjeux** [comment]
@rattrayalex looks like we need some special handling for comments!

**Comment by rattrayalex** [comment]
Yeah, I noticed that in the original... couldn't find a quick & easy solution. I'll take another look.

**Comment by rattrayalex** [comment]
Yeah, this looks really hard. 

```js
    const stmtPrinted = print(stmtPath);
    const text = options.originalText;
    const parts = [];

    // in no-semi mode, prepend statement with semicolon if it might break ASI
    if (!options.semi && !isClass && stmtNeedsASIProtection(stmtPath)) {
      parts.push(";");
    }

    parts.push(stmtPrinted);
```

Possible routes I can think of: 

1) traverse `stmtPrinted`, mutating to add a semicolon after parts that look like comments with a regex (sounds awful). 
2) traverse `stmt`, looking for nodes with leadingComments, and if one is found... traverse `stmtPrinted`, mutating to add a semicolon... somewhere
3) modify the `print` function itself (`comments.printComments`) to accept an option, `insertLeadingSemi`, and insert the semicolon at `var trailingParts = [printed];`

I think the third might actually work, though it could get messy...

**Comment by vjeux** [comment]
@rattrayalex I think that the 3rd option is the best one. I can't see any time where it would break.

**Comment by vjeux** [comment]
@rattrayalex I have to go but I was working on your 3) option: https://github.com/prettier/prettier/pull/1257 it's not yet working (not sure why) but I think it should.

**Comment by vjeux** [comment]
Okay, https://github.com/prettier/prettier/pull/1257 is working like a charm :)
