### ISSUE TITLE
No error if file doesn't exist.

### ISSUE THREAD

**Issue by atombender** [prettier/prettier#1246]
```
$ npm i prettier@1.0.2
$ stat non-existent-file.js
stat: cannot stat 'non-existent-file.js': No such file or directory
$ prettier non-existent-file.js; echo $?
0
```

**Comment by vjeux** [comment]
This is weird. May be an issue with glob? https://github.com/prettier/prettier/blob/master/bin/prettier.js#L291-L293

**Comment by lydell** [comment]
I don't think there's any issue with glob. The CLI arguments are basically just passed as patterns to the glob package. It then looks for files matching those patterns, and returns an array of all file names that matched. In this case, no files match so it simply returns an empty array. Then we loop over that empty array. I guess we could throw an error if no files match – that is, if the glob package returns an empty array.

**Comment by atombender** [comment]
Globbing is a shell mechanism. Unix tools like `cat` don't glob at all — the shell does. There shouldn't be any reason to use `glob` on command-line arguments.

In fact, it's counterproductive, because the shell will expand globs first, which could cause problems if a file name contains wildcards, which will then be processed again by `glob`, so you get double globbing.

Globbing in a program is of course perfectly fine in other places, like if the wildcards come from a config file or the program itself.

**Comment by lydell** [comment]
@atombender In the Node.js world, the convention is to use a glob package rather than relying on the shell, since it is insanely difficult to write cross-platform globs. Double globbing is not a problem in practice (it can only cause problems if you have weirdly named files, but it can still be worked around).

**Comment by atombender** [comment]
If you're writing something that's to be invoked by a Unix shell, don't glob. It's that simple. It's a solved problem. The Node.js world isn't some unique thing; this applies to Ruby, C, Lau, Python, what have you.

Cross-platform compatibility is easily achieved by having separate wrapper scripts for Unix and Windows. Because we're really talking about Windows here, aren't we?

Shell semantics are important to get right. For example, I don't expect programs to expand `$FOO` either, or unquote arguments. And don't forget, exec on Unix _doesn't_ use a shell. There are plenty of use cases (e.g. Dockerfiles) where you don't get shell semantics without wrapping in `sh -c`. Not a problem here, just clarifying. In a non-shell invocation situation, I expect the command to be interpreted literally,  _not_ being subject to globbing, envvar expansion, etc.

**Comment by lydell** [comment]
Sorry, this is not a discussion about shells, conventions and how stuff should ideally work. I was just pointing out why the code works the way it does. Let's please keep this issue about solving the immediate problem. I suggest you open a new issue if prettier's "built-in globbing" gives you problems (but keep in mind that it is always difficult to go against the conventions of a programming community). :)

Here are the relevant earlier issues:

- https://github.com/prettier/prettier/issues/362#issuecomment-274250544
- #362 
- #451 
- #363 
- #145

**Comment by vjeux** [comment]
For this issue, I can see two things:

1) Use fs.readFileSync instead of going through glob is there is no special patterns. If you give the actual name of a file, we should throw if it's not there.
2) Throw if glob didn't return anything.

The first one seems to be the best to me. Let me know if you are interested in sending a pull request to fix it. Thanks!
