### ISSUE TITLE
`pluginSearchDirs: false` in .prettierrc not working as expected

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#12475]
**Environments:**

- Prettier Version: 2.6.0
- Running Prettier via: 
- Runtime: 
- Operating System: 
- Prettier plugins (if any): 

**Steps to reproduce:**

Add `pluginSearchDirs: false` to `.prettierrc`, run `prettier * -c`

**Expected behavior:**

Not do any plugin search

**Actual behavior:**

Still searching plugins before the config is resolved.

**Workaround**

Run Prettier with `--no-plugin-search` instead.

**Comment by RoyRao2333** [comment]
Is this fixed? I got a warning from WebStorm [when configuring Svelte](https://github.com/sveltejs/prettier-plugin-svelte#usage-with-tailwind-prettier-plugin):

<img width="476" alt="image" src="https://github.com/prettier/prettier/assets/31413093/5138248e-e53f-46d3-afb8-dbdba2cc56bd">

Don't know if this option is working (not tested yet), but I'm concerned about this warning and wondering if it would cause any problems.

Any help would be appreciated. :)

**Comment by fisker** [comment]
[`pluginSearchDirs` hasbeen removed.](https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker)
