### ISSUE TITLE
Dangling comma before a line with a comment

### ISSUE THREAD

**Issue by vsviridov** [prettier/prettier#1247]
Let's say I have an object that looks like this:
```js
const options = {
  optionA: true,
  optionB: true,
  optionC: false
};
```
I'm playing around with settings and I comment out `optionC`.
```js
const options = {
  optionA: true,
  optionB: true,
  // optionC: false
};
```
My editor runs the formatter and it removes the dangling comma after `optionB`.
```js
const options = {
  optionA: true,
  optionB: true
  // optionC: false
};
```
I see that I still need the `optionC`, and I uncomment the line using my editor shortcut.
```js
const options = {
  optionA: true,
  optionB: true
  optionC: false
};
```
I save the file and formatter fails, because it is no longer valid syntax.

Leave the dangling comma before commented line alone (in objects and arrays, i guess).

**Comment by vjeux** [comment]
Thanks for reporting this! You should try the `--trailing-comma=es5` option which always puts trailing commas so that you wouldn't have this issue in the first place.
