### ISSUE TITLE
Format function error

### ISSUE THREAD

**Issue by showmethecode9527** [prettier/prettier#12482]
**Prettier 2.6.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AUAlAATAA6UxxkUAzhADZwB0DEA5vgIwkC+IAGhAQADrmi1koAIYAnWRADuABTkJJKaQ0XSAnpKEAjWdLABrODADK0gLZwAMjihxkqLbThGT5y1ZGmzuzIMLLoXiBwtoZwACaxcQ7SUOzo0uxwAGIQsrbSMLgpyCDS6DAQgiAAFjC2DADqVTjwtAFgcFbqzTgAbs26xWC0BiDOnrIwyibseW4eEQBWtAAeVkFMAIroEPBzDJ5CAbLjxYbSMQyVIrLOMPU4sTBVyAAcAAyHCp71JiLF13Bxj1XEIAI7beBTUQaEq0AC0LjicUqsjg4JwqKm6VmSHc+winlsOBCYQJ6zgWx2rlx8yEMHO90ezyQACY6SYcAwggBhCC2HGRWgAVkq6E8ABVzho8QcQD1wgBJKAJWBWMA3MQAQWVVhguiYe08vF4QA)

**Input:**

```js
function() {
  console.log(1) }
```

**Output:**
```
SyntaxError: Unexpected token (1:9)
> 1 | function() {
    |         ^
  2 |   console.log(1) }
```

**Expected behavior:**
```js
function () {
  console.log(1)
}
```

**Comment by Josh-Cena** [comment]
Anonymous functions are not allowed as declarations, only as expressions. Because otherwise you can't call it whatsoever.

```js
const foo = function () {
  console.log(1);
};
```

**Comment by sosukesuzuki** [comment]
Or, you can wrap function expression with parens

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAZgVymGBLaVASgAJgAdKEkyKAZwgBs4A6RiAc1QEYjKBfIiAA0ICAAd80OslABDAE4KIAdwAKihDJRzGKuQE8ZogEYK5YANZwYAZTkBbOABk8UOMnS66cU+as2tuIWbhzIMAqYviBwDiZwACYJic5yUByYchxwAGIQCg5yMPjpyCBymDAQIiAAFjAOjADqtXjwdMFgcLZabXgAbm0GZWB0xiBuPgowauYchZ7e0QBWdAAetqHMAIqYEPCLjD6iwQpTZSZy8Yw14gpuME14CTC1yAAcAAwnyj5N5uIync4FN+h5RABHPbwWYSbTlOgAWnciUSNQUcCheAxsyyCyQXiO0R8Djw4UixK2cF2+w8BKWohgVyeLzeSAATIzzHhGKEAMIQBz4mJ0ACsNUwPgAKldtITjiB+lEAJJQZKwWxge6SACCatsMAMzEOPn4-CAA)

```sh
--parser babel
```

**Input:**

```jsx
(function() {
  console.log(1)
})
```

**Output:**

```jsx
(function () {
  console.log(1);
});

```
