### ISSUE TITLE
Flow types are difficult to prettier-ignore

### ISSUE THREAD

**Issue by jasonLaster** [prettier/prettier#1248]
It seems like ignore comments inside of a type object cause two strange behaviors. Either they cut off the last character or they add a second comma. The workaround is to add the comment above the type definition.

```js
type flowType = {
   // prettier-ignore
   func: (Function) => Promise<*>,
   foo: number,
};
```

Here is a test case: 

```diff
diff --git a/tests/ignore/__snapshots__/jsfmt.spec.js.snap b/tests/ignore/__snapshots__/jsfmt.spec.js.snap
index b84c893..002377c 100644
--- a/tests/ignore/__snapshots__/jsfmt.spec.js.snap
+++ b/tests/ignore/__snapshots__/jsfmt.spec.js.snap
@@ -20,6 +20,13 @@ function a() {

   // Let's make sure that this comment doesn't interfere

+
+  type flowType = {
+    // prettier-ignore
+    func: (Function) => Promise<*>,
+    overloaded: (number | Object) => any
+  };
+
   // prettier-ignore
   const commentsWithPrettierIgnore =   {
     "ewww":
@@ -84,6 +91,12 @@ function a() {

   // Let's make sure that this comment doesn't interfere

+  type flowType = {
+    // prettier-ignore
+    func: (Function) => Promise<*,
+    overloaded: number | Object => any
+  };
+
   // prettier-ignore
   const commentsWithPrettierIgnore =   {
     "ewww":
diff --git a/tests/ignore/ignore.js b/tests/ignore/ignore.js
index 63fc1e4..5b03ed2 100644
--- a/tests/ignore/ignore.js
+++ b/tests/ignore/ignore.js
@@ -17,6 +17,13 @@ function a() {

   // Let's make sure that this comment doesn't interfere

+
+  type flowType = {
+    // prettier-ignore
+    func: (Function) => Promise<*>,
+    foo: number
+  };
+
```

**Comment by vjeux** [comment]
Wow, this is crazy. This is the first time I've seen such an issue where characters were removed/added.

```js
// flow
type flowType = {
  // prettier-ignore
  func: (Function) => Promise<*,
  foo: number
}
```
https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20flowType%20%3D%20%7B%5Cn%20%20%20%2F%2F%20prettier-ignore%5Cn%20%20%20func%3A%20(Function)%20%3D%3E%20Promise%3C*%3E%2C%5Cn%20%20%20foo%3A%20number%2C%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

```js
// babylon
type flowType = {
  // prettier-ignore
  func: (Function) => Promise<*>,,
  foo: number
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20flowType%20%3D%20%7B%5Cn%20%20%20%2F%2F%20prettier-ignore%5Cn%20%20%20func%3A%20(Function)%20%3D%3E%20Promise%3C*%3E%2C%5Cn%20%20%20foo%3A%20number%2C%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Looks like both flow AND babylon are reporting incorrect location! I'm going to make a bug report on both projects.

**Comment by vjeux** [comment]
We have some crazy code that attempts to "fix" a faulty location around ObjectTypeProperty left from recast days and messes up with this: https://github.com/prettier/prettier/blob/master/src/util.js#L45-L54

**Comment by vjeux** [comment]
#1252 fixes it for the flow parser, but it's still adding another `,` for babylon. I'm investigating.

**Comment by vjeux** [comment]
Just created an issue on babylon side: https://github.com/babel/babylon/issues/470

If you are interested in helping out, that should be an easy fix on their side, whenever they merge it and do a new release, it'll fix it for prettier as well :)

**Comment by jlongster** [comment]
The real question: why are you using prettier-ignore? :)

**Comment by vjeux** [comment]
@jlongster because prettier outputted incorrect code ( #1249 ) and he sent a fix for it ( #1251 )

**Comment by jlongster** [comment]
Ooooh right, the original example didn't have that kind of union I think. cool!

**Comment by existentialism** [comment]
Fixed upstream in Babylon via https://github.com/babel/babylon/pull/472, will update when we push a new release!

**Comment by vjeux** [comment]
Yay, thanks @existentialism!

**Comment by vjeux** [comment]
This has been fixed :)
