### ISSUE TITLE
Comment in default block of switch is moving unexpectedly

### ISSUE THREAD

**Issue by stefcameron** [prettier/prettier#12481]
Discovered this after attempting to upgrade from 2.5.1 to 2.6.0.

**Prettier 2.6.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlPvkQO44xgAW+pJAhvJTXXr4w3InHyoccADYATAMoxecIgDoASgFEAggBEA8gDkAMgE0ktIUIBOK9NJj4AvBKlzFytZsPaAQsc1dAG5LK3wAI1tuAGsQwXoRMVcZBSViVW0AYQAVAEkANU0AfS09IzMLeJs7B2dk9zSVDJyCzTiwiKjY0ITRcUkUj3TNdXV9dRKdAxNzHuqie0cXAYbPVRGx9XawyLgY7d6kldS1jfGirLzCybKZyo7bBdrltxPh0fPL1oOhXf252RwVDcRb3MKPRZ1HjwIL4AD0cPwUAgwjY3CgAHM4HN6H9uoIAL60AkgAA0IAgAAdcNAiMhQNxrNYIIwAAqMhB0lDcaSMbgATzp5Mi3DA0TgMHk3AAtnBjDgoHBkMDpGJhdZReLJZTRQqMcgYNZ0HByXBpeE4LJAbJjOiMehuFiAGIQazS3i4THIEAgmAQMkgNgwaXSADqbBYKh1YDg8k5LBwADcWPzvSRrDhsAGFWJrDBWRqMe7lTy1SAAFZEAAe8j10jgAEV0BB4CXVSaQDrrLnveFuBbpAHKRnYKGcLIYGxkAAOAAM5OHEDEoY1lO9isTcGsAYAjs34AWqVyfUQALSKy2WgO2Pc4WwFx3FpAqstiaU4A1GjtEOuN-dKpBDWNcklHCMcJynJAACYQI1HBpD1TIIGlJ8QBUABWAN0DEbJ+y5F8O0TY1cigQFYHkMAM2pbRSMUfl6zbMQCQJIA)

```json
{
  "arrowParens": "always",
  "bracketSameLine": false,
  "bracketSpacing": true,
  "embeddedLanguageFormatting": "auto",
  "htmlWhitespaceSensitivity": "strict",
  "insertPragma": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "never",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false
}
```

**Input:**

```jsx
function test() {
  switch (state) {
    case fieldStates.READONLY:
      result = fieldStates.ENABLED;
      break;
    case fieldStates.ACTIVE_READONLY:
      result = fieldStates.ACTIVE;
      break;
    case fieldStates.ERROR_READONLY:
      result = fieldStates.ERROR;
      break;
    case fieldStates.ERROR_ACTIVE_READONLY:
      result = fieldStates.ERROR_ACTIVE;
      break;
    default:
      result = state; // no change
      break;
  }
}
```

**Output:**

```jsx
function test() {
  switch (state) {
    case fieldStates.READONLY:
      result = fieldStates.ENABLED;
      break;
    case fieldStates.ACTIVE_READONLY:
      result = fieldStates.ACTIVE;
      break;
    case fieldStates.ERROR_READONLY:
      result = fieldStates.ERROR;
      break;
    case fieldStates.ERROR_ACTIVE_READONLY:
      result = fieldStates.ERROR_ACTIVE;
      break;
    default: // no change
      result = state;
      break;
  }
}
```

**Expected behavior:**

The `// no change` comment shouldn't move. It should stay next to the line where I put it.

**Comment by fisker** [comment]
//cc @duailibe #12177?

**Comment by stefcameron** [comment]
This is still a problem in 2.6.1...

**Comment by stefcameron** [comment]
I was able to get around this by changing:

```javascript
    default:
      result = state; // no change
      break;
```

to this:

```javascript
    default:
      // no change
      result = state;
      break;
```

But what Prettier is doing here is not acceptable, IMO. It already relocates comments in awkward places that move them out of context under other circumstances. This is yet another example, but worse because there's really no reason to relocate this comment. The line is far from close to the max 80 length, and Prettier traditionally does not format a line when it exceeds the line length only because of a comment.

(I'm talking about the line length limit, but really, I have no idea what is causing this comment to be relocated; I'm just saying there's no apparent reason for it to be moved, whereas other cases where comments are moved out of context, it's because the code they're commenting ends-up getting formatted and then I guess Prettier has to pick the spot to put the comment, and it usually gets it wrong.)

**Comment by nelsonsbrian** [comment]
A workaround would be:
`    default: {
      result = state; // no change
      break;
}`

But I agree, would be nice to note move the comments around without the block

**Comment by alfaproject** [comment]
I've just stumbled upon this issue and got a minimum reproduction in the playground: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnA7gSxmAFgAgAoYAnAVzgEp9gAdKffAEzgDMBDMgGxiXscasIEfAF58AI3YkA3PgD08-AGEIAWzUIY-ARJJx2Aaxn0AvvRAAaEBAAOMTNFTJQ0khHQAFaQmcp2XOjsAJ7O1nrsYIZwMADK7JoAMphQcMgcXKhw4SSR0XG2kSkA5sikFNZwahJwTCxMiexQxWTsxXAAYhAkauwwDs3IIJwwEFYguDBqXADquNhwqIVgcLG+2JgAbtjBQ2CoYSApWSQwnrnFvekBWdYAVqgAHrElXHAAimQQ8NeZ2SCFEgnIYwYK2RZgEiYezjWxQ2AzTBMGC4ZAADgADNY4RAsjNcrYhnDFnASJs0tYAI5feDnOx+YaoAC0qVqtXG+mpmH05zaVyQGVuaCqmDK5H+qFeHxpaQFN3+MHYEkRyNRSAATNZSOxMFwSqoNOwhosAKzjMhZAAqSr8gv+mwoAEkoCxYLFIdCYABBF2xUFvX5ZUymIA

This is a pretty annoying breaking change because I got a comment moved out of nowhere after a simple refactoring lol
