### ISSUE TITLE
Wrong cursorOffset with Identifier.typeAnnotation

### ISSUE THREAD

**Issue by Gregoor** [prettier/prettier#12491]
Since the playground does not have the `cursorOffset` option (from what I could see), I've put it into RunKit: https://runkit.com/gregoor/prettier-cursor-offset-bug

Here is the code:
```ts
const prettier = require("prettier");
prettier.formatWithCursor("let i: T;", { cursorOffset: 5, parser: "typescript" });
```

which erroneously returns a `cursorOffset` of `7`, where I'd expect it to stay `5`.

I might look into a fix myself this weekend, unless someone tells me that my expectation are wrong and this is actually expected behavior.

**Comment by fisker** [comment]
Fixed by #14171
