### ISSUE TITLE
Markdownlint violation: MD038 - Spaces inside code span elements

### ISSUE THREAD

**Issue by felipecrs** [prettier/prettier#12503]
**Prettier 2.6.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADeBnGACX3UgA0IEADjAJbQbKgCGATgxAO4AKjCNKdANi3QCeNYgCMGdMAGs4MAMp0AtnAAyFKHGQAzPhjhiJ02XNKT1Ac2QwGAV30g4i0XAAmL1yrpRzNuubgAYhAMinQwlN7IIHQ2MBBEIAAWMIq8AOqJFJimYHByXFkUAG5ZglFgGCIg6noMMGwS5qHauvYAVhgAHnIWvHAAijYQ8C28esSmDLVRoQxSLqxQCaQM6jBpFC4wicgAHAAME8x6aRKkUStwtUWaxACOQ-ANZNzRGAC0Gq6uCQxwDxQ-g0-M0kDoxvY9IoKFZbJDegNHpowa1iDA6KINlsdkgAExoiQUXgWADCEEUoIcGAArAkbHoACoY7jg8YgIp2ACSUHcsDkYFW5AAgjy5DBBH1RnoAL7SoA)

```sh
--parser markdown
```

**Input:**

```markdown
`test    `
```

**Output:**

```markdown
`test `

```

**Expected behavior:**

```markdown
`test`

```

https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md038

**Comment by felipecrs** [comment]
Question? What makes you think this is a question?

**Comment by fisker** [comment]
This is not a bug, we won't change the output. Try to ask/think why we don't remove it. So this is a question.

**Comment by felipecrs** [comment]
Well, I thought it was a bug. Is there a reason to keep it like that?

**Comment by fisker** [comment]
Inspect these two `<code>` blocks in your browser, `foo  `(`` `foo  ` ``) and `foo`(`` `foo` ``)

**Comment by felipecrs** [comment]
Okay... I did not understand still, but that's okay. If this is a feature rather than a bug that won't be changed it is worthless to discuss anyway.

Thank you!
