### ISSUE TITLE
Github action windows issue

### ISSUE THREAD

**Issue by The-Code-Monkey** [prettier/prettier#12525]
**Environments:**

- Prettier Version: 2.6.0
- Running Prettier via: Github action windows-latest
- Runtime: node 16 Github action windows-latest
- Operating System: Github action windows-latest
- Prettier plugins (if any): none

https://github.com/The-Code-Monkey/react-cms/runs/5674536281?check_suite_focus=true

**Expected behavior:**

I'm not sure what the actual issue is as there is no output log, is there a way to get it to tell me what the issue is.

**Actual behavior:**

just saying theres an issue runs fine on my mac and on the linux stuff.

**Comment by fisker** [comment]
Can you try put this file in your repo? https://github.com/prettier/prettier/blob/main/.gitattributes

**Comment by kachkaev** [comment]
See also: https://prettier.io/docs/en/options.html#end-of-line
