### ISSUE TITLE
Remove test step from release script?

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#12532]
I just played with the release script, it run tests during release, and the tests may take long time.

Testing source doesn't make sense, we already tested on CI.
Testing bundles maybe make sense, because the build script may have bug.

If we run build script on different platforms on CI to make sure the bundled code are the same, then maybe we can remove that step too.

//cc @sosukesuzuki

**Comment by sosukesuzuki** [comment]
I agree with to remove testing source.

> If we run build script on different platforms on CI to make sure the bundled code are the same, then maybe we can remove that step too.

Sounds good.But ideally, it would be great that we can build and release from GitHub Actions(ref: #9954)
