### ISSUE TITLE
Inconsistent formatting with Javascript and brackets

### ISSUE THREAD

**Issue by EricG-Personal** [prettier/prettier#12541]
**Prettier 2.6.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDTBeTAbWGyUwHJdVoBzOAJ0wGcZ6BLKG8gGkwCMylKJjgA3BJmqcGzVhy4BfALoBuADpQN6LLgLFSFKrRkt2nHpg2ZrN2wMPCxEqXUan55ZeuG3fWjDj4RMBWNgaUksZucua8odb2QiLiwi4mMVwaXvF+UNqBejkhPr44gkbS0WZccSW+idiOKZGVstXkOQoaqpgg3CAQAA4wbNBMyKDY9PQQAO4AClMI4yjYqLPYAJ7j-Xz02GAA1hgAytgAtnAAMhxwyABma0xwu-tHp4MH8g9PLyBw5z4cAAJsCQVdGjQAK7YOgAMQg9HO2BgI04yBA2ChMAgfRAAAsYOdUAB1fFseBMT5gOAnZYUtiiCmbDFgJg7EAcZ70GDzfY0ZE-VDPfoAKyYAA8TvJ0ABFKEQeBCkUgT70bkYvjYIGoPGDGbPEn7QYY-VwbniPEARwV8D5QxWmKYAFooHAQSC8fQ4Da2N6+bDBUhHsK-s9zmxkKwoWGZXB5Yq7kho38YNqSWxgTB8cgACz9VjYNioeQAYQg5yDICg0Du-ShzwAKtqVin+qIYwBJKBg2AnMDsYYAQR7Jxgm3Qyr++o4MAzWZzSAAjAAmAAMCgUQA)

```sh
--parser babel
--print-width 120
--tab-width 4
--use-tabs
--single-quote
--no-bracket-spacing
--trailing-comma none
```

**Input:**

```jsx
let a = [{a: 'a longer string', b: 'an even longer string'}];

let a = [{a: 'a longer string', 
          b: 'an even longer string'}];
          
let a = [{
    a: 'a longer string', 
    b: 'an even longer string'
}];
        
let a = [
    {
        a: 'a longer string', 
        b: 'an even longer string'
    }
]; 
```

**Output:**

```jsx
let a = [{a: 'a longer string', b: 'an even longer string'}];

let a = [{a: 'a longer string', b: 'an even longer string'}];

let a = [
	{
		a: 'a longer string',
		b: 'an even longer string'
	}
];

let a = [
	{
		a: 'a longer string',
		b: 'an even longer string'
	}
];

```

**Expected behavior:**

I would expect Prettier's opinion on how this object to look to be consistent regardless of how the user initially typed it. At the moment, there are (at least) two possible answers for how Prettier will format the same code.

**Comment by kachkaev** [comment]
👋 @EricG-Personal! Please see https://github.com/prettier/prettier/issues/2068 and https://github.com/prettier/prettier/issues/11856. This behaviour has been a long-standing trade-off between the deterministic behaviour and output ugliness. Thoughts are welcome in #2068!
