### ISSUE TITLE
usless parentesis for multiplications preceding divisions`(a * b) / c`

### ISSUE THREAD

**Issue by yukulele** [prettier/prettier#12554]
**Prettier 2.6.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAenQIy+sAbgB0oMAqXfI0jbPSms9SvbMF9AExKhABoQEAA4wAltADOyUKgBOciAHcACvITSUqADZLUAT2mCcc1GADWcGAGVUAWzgAZMVDjIAZjslxjpi1ethMxcAc2QYOQBXHxA4Oxw4Li5Ex1QoEMjUELgAMQg5O1QYcXTkNEiYCAEQAAsYO20AdRqxeEkgsDhrDVaxADdW-TKwSSMQF285GBVTEMKPLxiAK0kAD2tQ7TgARUiIeAXtb0EguUmynFQE7WrhORcYRrEuGBrkAA4ABhPFb0bTYRlO5wSZ9NyCACOe3gMxEmjQkgAtK5EolqnI4FCxBiZll5khPEcYt47GJwlFiZsdtC3ATFoIYFcni83kgAEwM0xibShADCEDs+NikgArNVIt4ACpXTSE44gPrRACSUGSsGsYHuogAgqrrDB9FtDt4AL4moA)

```sh
--parser babel
```
on an expression of the type:
```js
a1 * a2 * … * aN / b1 / b2 / … / bM
```
where multiplications precede divisions, parentheses appear superfluous.

**Input:**

```jsx
a / b / c;
a * b / c;
a / b * c;
a * b / c * d;

```

**Output:**

```jsx
a / b / c;
(a * b) / c;
(a / b) * c;
((a * b) / c) * d;

```

**Expected behavior:**
```jsx
a / b / c;
a * b / c;
(a / b) * c;
(a * b / c) * d;

```

**Comment by yukulele** [comment]
> I agree that it might feel redundant here, but in some languages other than JavaScript 

here it is only xxx that is involved?

> ...it could be important to be taught if a * c / b is interpreted as (a * c) / b or a * (c / b) since those could have different results based on types and if they overflow.

* this is not really a problem since `(a * c) / b === a * (c / b)`
* The same could be said for `a + b - c`: is it intrpreted as `(a + b) - c` or `a + (b - c)`?

**Comment by lydell** [comment]
Prettier used to print as few parentheses as possible, then it switched to print some extra ones for readability. See the very long https://github.com/prettier/prettier/issues/187 for the full story.

**Comment by mvlabat** [comment]
@lydell can we make the behaviour configurable? I find redundant parenthesis a bit annoying, it would be great if there was a config option for those. (I haven't found one in the docs.)

**Comment by mvlabat** [comment]
I see, thanks for the link. I guess I'll try `dprint`, which is less opinionated
