### ISSUE TITLE
Throw `Uncaught Error: Mismatched anonymous define() module` when using `esm/standalone.mjs` with RequireJS

### ISSUE THREAD

**Issue by zjffun** [prettier/prettier#12560]
**Environments:**

- Prettier Version: 2.6.1
- Running Prettier via: Browser API
- Runtime: Chrome
- Operating System: macOS
- Prettier plugins (if any): parser-html

**Steps to reproduce:**

1. Add requirejs;
2. Import prettier `esm/standalone.mjs`;
3. Use prettier.

**Expected behavior:**

Don't throw error.

**Actual behavior:**

Throw `Uncaught Error: Mismatched anonymous define() module`.

---

Reproduction: [prettier-with-requirejs](https://codepen.io/1010543618/pen/PoEKWQw?editors=1000)

I make a simple fix: [fix-prettier-with-requirejs](https://codepen.io/1010543618/pen/jOYLypB?editors=1000)

This fix adds ESModule exports of parse-srcset https://github.com/zjffun/parse-srcset/commit/a5e0f86997057ac6aa8bb065e79bc505a53273b2. Because prettier using `require` to load modules,  so I also changed the `require` of `parse-srcset` in  prettier https://github.com/zjffun/prettier/commit/944b6868bb6271ed0bb08ec70ed4e5d812f85565. 

This fix only provides an idea and **can't be used as a final solution**, because there may be problems in the node environment.

**Comment by fisker** [comment]
Fixed by #13536
