### ISSUE TITLE
Include `test.describe` in the test declarations that don't wrap, or ideally make the list of functions configurable

### ISSUE THREAD

**Issue by dossy** [prettier/prettier#12575]
`prettier` cleverly doesn't wrap long lines if it happens to be a "test" call, thanks to:

* https://github.com/prettier/prettier/blob/main/tests/format/js/test-declarations/test_declarations.js
* https://github.com/prettier/prettier/blob/b0962780c1ed828651c2ea4a79baada7e8420fac/src/language-js/utils/index.js#L472

This is wonderful, because it makes test suites nicely readable when code-folded.

However, the convention with [Playwright](https://playwright.dev/) is to use `test.describe()` instead of `describe()`, and so `prettier` will wrap the function args when the line gets long, which makes folded code ugly, rendering the test suite name no longer visible in the fold summary.

It would be great if this was a more general-purpose configurable behavior, "don't wrap long lines that match this regexp" that could default to what's currently being used, but overridden from the `prettier` config somehow.

**Comment by fisker** [comment]
Send a PR add `test.describe()`

**Comment by F3n67u** [comment]
except for `test.describe`, playwright also support:

[test.describe.only(title, callback)](https://playwright.dev/docs/api/class-test#test-describe-only)
[test.describe.parallel(title, callback)](https://playwright.dev/docs/api/class-test#test-describe-parallel)
[test.describe.parallel.only(title, callback)](https://playwright.dev/docs/api/class-test#test-describe-parallel-only)
[test.describe.serial(title, callback)](https://playwright.dev/docs/api/class-test#test-describe-serial)
[test.describe.serial.only(title, callback)](https://playwright.dev/docs/api/class-test#test-describe-serial-only)
[test.step(title, body)](https://playwright.dev/docs/api/class-test#test-step)

only adding `test.describe` doesn't seem enough for full playwright support.
