### ISSUE TITLE
Prettier not formatting custom and input tags (in angular html template)

### ISSUE THREAD

**Issue by Adam-Szitas** [prettier/prettier#12595]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#.....)

```sh
# .prettierrc
{
    "tabWidth": 4,
    "singleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true,
    "printWidth": 140,
    "endOfLine": "auto",
    "overrides": [{
        "files": "*.html",
        "options": {
            "printWidth": 100,
            "parser": "angular",
            "htmlWhitespaceSensitivity": "css"
        }
    }]
}

```

**Input:**

```jsx
    <input formControlName="input" type="text" [name]="inputName" [id]="inputId" class="input" [disabled]="isDisabled" [placeholder]="placeholder" [innerText]="inputText" />

```

**
It should break the line and in block write every single [Input] attribute instead of having everything in one single line. But it is not behaving like that instead puts everything in one single line. When saving first it makes everything look fine and then puts back every attribute inline.
``` <div> ``` 
and other elements (haven't tried everything yet) are getting formated correctly. I'm attaching a picture of the issues themselves as well. 
Issued elements are: custom elements (<app-custom-element></app-custom-element>) and input elements (<input />).
**
![image](https://user-images.githubusercontent.com/86225047/161588908-1f464cea-59ae-415c-9759-bcb940cdd186.png)

**Comment by fisker** [comment]
Please follow the issue template.
