### ISSUE TITLE
prettier ignore doesn't ignore .env file

### ISSUE THREAD

**Issue by goldylucks** [prettier/prettier#12590]
**Prettier 2.6.2**
N/A

```sh
# .prettierignore
.env
```

**Input:**

```sh
FOO=a;sdlfjasld;kfjl;aksdfjl;aksdfjals;dkfjasdl;kfjas;dlkfjasd;lkfjsd;alfkjasd;lfkjasd;flkajsd;flkasjdf;lkajsf;lkasjf;lkj
```

**Output:**

```sh
FOO=a
sdlfjasld
kfjl
aksdfjl
aksdfjals
dkfjasdl
kfjas
dlkfjasd
lkfjsd
alfkjasd
lfkjasd
flkajsd
flkasjdf
lkajsf
lkasjf
lkj

```

**Expected behavior:**
should ignore file

**Comment by Harry-Hopkinson** [comment]
I could not reproduce this issue, are you creating a .prettierignore and adding a .env to that?

**Comment by goldylucks** [comment]
yes, here's a repro repo
https://github.com/goldylucks/prettier-ignore-fail-env-file

**Comment by fisker** [comment]
How did you run prettier? `npx prettier .env`?

**Comment by goldylucks** [comment]
oh sry... now I see it's a vscode bug, unrelated to prettier.

**Comment by Harry-Hopkinson** [comment]
No problem
