### ISSUE TITLE
Formatting could be better for fallthrough switch cases

### ISSUE THREAD

**Issue by janicduplessis** [prettier/prettier#1262]
``` js
let a = 0;
switch (a) {
  case 0:

  case 1:
    a = 2;
    break;

  case 2:
    break;
}
```
would be better as
``` js
let a = 0;
switch (a) {
  case 0:
  case 1:
    a = 2;
    break;

  case 2:
    break;
}
```

Noticed that because it triggers a no-fallthrough eslint error because of the extra new line (witch is kind of a bug in eslint too)

**Comment by janicduplessis** [comment]
There is also a bug where the output isn't consistent

```js
switch (a) {
  case 0: case 1:
    a = 2;
    break;
}
```
will get formatted to
```js
switch (a) {
  case 0:
  case 1:
    a = 2;
    break;
}
```
then
```js
switch (a) {
  case 0:

  case 1:
    a = 2;
    break;
}
```

**Comment by vjeux** [comment]
Can you make sure you are using prettier 1.1.0, I can't repro any of your issues.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(a)%20%7B%5Cn%20%20case%200%3A%20case%201%3A%5Cn%20%20%20%20a%20%3D%202%3B%5Cn%20%20%20%20break%3B%5Cn%7D%5Cn%5Cnswitch%20(a)%20%7B%5Cn%20%20case%200%3A%5Cn%20%20case%201%3A%5Cn%20%20%20%20a%20%3D%202%3B%5Cn%20%20%20%20break%3B%5Cn%7D%5Cn%5Cnswitch%20(a)%20%7B%5Cn%20%20case%200%3A%5Cn%5Cn%20%20case%201%3A%5Cn%20%20%20%20a%20%3D%202%3B%5Cn%20%20%20%20break%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
