### ISSUE TITLE
The "final new line" is missing in handlebars

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#12627]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgEIA6UAEAqHAYQgAcBPAJwEsBzACxhwAowBKHAMQEMw4AjCBADWAGhwBJKGAB0OLlAAmOKjADOcgGYaqAGypd4q2QEEdOnACVaDdRbiq4FAG5wF07Pg8EAKnSrrVCABXCl4cSAU4ZXU9XigHJSDFRxwYOiiAWXFvHFiEBxwNYMVlXDS4LxwAGXFCAFEAOQBlOsLdKKoy9JwKQUYFKgo4MBgICjIcCA1UvwDg0KiYIbh3KABfNewAHhIAPgBxQQUPHDQAYipprgBbDZOcHGuxqE6aE7Q4HQc73AecOBcLygb1+aAA9Jcfg80FAbnANugtmC9tgQCIQKQYFRoKpkKAuBRegB3AAKBPyyBAXB0RK4ZFx6L4FB4QjgMCacKqnTgyA01IcjOZYFZ7JIPFeyCWQTg6Lg1z4rkiCiq8hoQS4NDgHDG1wMWOBlK4QVGaJADGuOgA6n5DGLeE18ioqE4VGRKWBVAyQJ0HBQYCTmTRdbz+TKQAArVQADyarx0cAAikEIPAQ18w2KKL7KTQ9Ndro5TSRqLBLVQFGlkAAOAAM6OLEAcluZJEpxfsjhcpoAjsn4AHSLiUFxVABaKBwVyuU1DXuDOABjXBpB89PohzXKiSijS9dxxN9nkr0PomBcPhlit0ZAAJlPzN0r2I+a4lPsAFZTUEHN5z0PVwKIBONKkiRLATRgNQJAwMYihNDAZDxmm3xrEAA)

```sh
--parser glimmer
```

**Input:**

```hbs
{{!
 * Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
}}
<p>Good
  {{#if am}}
    morning
  {{else}}
    evening
  {{/if}}
  {{name}}!</p>

```

**Output:**

```hbs
{{!
 * Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
}}
<p>Good
  {{#if am}}
    morning
  {{else}}
    evening
  {{/if}}
  {{name}}!</p>
```

**Expected behavior:**

Keep the blank line.

https://github.com/facebook/jest/pull/12653#discussion_r846087106

**Comment by fisker** [comment]
@dcyriller Is it a bug? Or any reason we are not inserting it.

**Comment by dcyriller** [comment]
A while ago I started a PR to read the `insertFinalNewline` option from `.editorconfig`. The reason why it is not inserted is explained in this PR description: https://github.com/prettier/prettier/pull/10759#issue-864956777

**Comment by fisker** [comment]
Sorry, forgot about it. Thank you!
