### ISSUE TITLE
print-width: wrapping behavior shows different between languages

### ISSUE THREAD

**Issue by Rickion** [prettier/prettier#12624]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoGYCGA1nAGJSoC8qAFAJRUB8qwAOheqgE5wwCuXCvSYt2ndGM49+g0R3QByAB4rVKhUlQKEAFQAWcAI58AlmCIAjBQBpJigJ6OnjjVsC0coHDTQJvxgbbVAVHKA6to2qHZaUOER4a4KgLIggEIggBwggOIggKwgcYDSIIACICmAgiCA3CDBoQoQJaUl0YAu44AkjYAXTYAto7U1NuysMAoAXp1dndGAygyAMQyAkQyAdgyAJgzDzRytAL4A2gCMALoh8qjTktMg1iAQAA4wJtBYyKAEXFwQAO4ACmcIxygEADaXBPbH2xZcBOa8AMoEAC2cAAMiYoHBkIQnlg4J9vr8YH9dj9wQBzZAwLh8OEgOCAixwAAmROJIIIUDRfAIaLIEC4gIIMAOlOQIAIfBgEC2ID0MEBTwA6noTPAsCiwHA-vdRSYAG6i+xssBYD4gcGwrgwa7fNGMqHPWHbABWWCUf3RTzgAEU+BB4AaYbiUVxNWyLARCU8ebsuOCYIKTESYHpkABmAAM219EFhgu+uzZvrgmrlkO2xntcB1ewe7KwAFoIcTiTyeMYTDwdTT9UhoUaQLDASZMdjcVhLTa7Q664bcTBPYHg6GkAAmbZYggmJ7ogDCEEBtbxWAArDy+LCdJ6HvXcXKcQBJKCk2B-MB+-YAQWPfxg9itjth02mQA)

```sh
--parser babel
--print-width 30
```

**Input:**

```jsx
  const fakeFn = () => {
    return () => {
     
    return {
    'xxxxxxxx': 'enThequickb',
    'yyyyyyyy': '中文这四个字', 
    'nnnnnnnn': 'этичетыресл', 
    'oooooooo': '이네단어네단단',
    'zzzzzzzz': 'これらのつの',
  	}[1] 
    }
  }
```

**Output:**

```jsx
const fakeFn = () => {
  return () => {
    return {
      xxxxxxxx: "enThequickb",
      yyyyyyyy:
        "中文这四个字",
      nnnnnnnn: "этичетыресл",
      oooooooo:
        "이네단어네단단",
      zzzzzzzz:
        "これらのつの",
    }[1];
  };
};

```

**Expected behavior:**

On output panel, line 6 should stays in line 5.

![image](https://user-images.githubusercontent.com/13317720/162354097-ca214862-7a33-4e3c-9b84-27f632ba3d20.png)

1. The characters 'seems' has a same length.(red arrow on screenshot)
1. The characters range from AST: `en-us: 13`, `zh-cn: 8`.(blue arrow on screenshot)
1. Warpping for `zh-cn`, but `en-us` is OK. (yellow arrow on screenshot)

### Question 
1.  `print-width` depends on what?
2.  Is this a correct behavior?
3. Is there any special config to let these lines not warpping?

**Comment by fisker** [comment]
> print-width depends on what?

https://github.com/prettier/prettier/blob/main/src/utils/get-string-width.js

>  Is this a correct behavior?

Yes, expected #10335

> Is there any special config to let these lines not warpping?

No.

**Comment by Rickion** [comment]
All right. 
Closing since this is `expected`. @fisker 
But I still disagree about this, end-user only cares about the `display-width` rather than `full-width` .
