### ISSUE TITLE
Option "singleAttributePerLine" and hbs-files

### ISSUE THREAD

**Issue by Timbuktu1982** [prettier/prettier#12625]
Hi there, 
the Option "singleAttributePerLine" is very useful to make code more clear, but it works not for hbs-files (e.g. like in emberjs used). Can we get the support for this option for hbs-files?

> Could you please update the description by using the [issue template](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE)?

Hi kachkaev,

# Options:
--single-attribute-per-line

FileType: *.hbs

Input:
`<div class="target-class" id="test-field" name="test-field-1" .... other params></div>`

Output: 
`<div class="target-class" id="test-field" name="test-field-1" .... other params></div>`

Expected Output:
```
<div 
    class="target-class" 
    id="test-field" 
    name="test-field-1" 
    .... other params
>
</div>
```

THX

**Comment by kachkaev** [comment]
Could you please update the description by using the [issue template](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE)?

**Comment by Timbuktu1982** [comment]
> Could you please update the description by using the [issue template](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE)?

Hi kachkaev,

# Options:
--single-attribute-per-line

FileType: *.hbs

Input:
`<div class="target-class" id="test-field" name="test-field-1" .... other params></div>`

Output: 
`<div class="target-class" id="test-field" name="test-field-1" .... other params></div>`

Expected Output:
`
<div 
    class="target-class" 
    id="test-field" 
    name="test-field-1" 
    .... other params
>
</div>`

**Comment by kachkaev** [comment]
Please use the [template](https://raw.githubusercontent.com/prettier/prettier/main/.github/ISSUE_TEMPLATE/formatting.md) in the [first issue comment](https://github.com/prettier/prettier/issues/12625#issue-1196893208). Issue templates includes the link to the Playground.

**Comment by Timbuktu1982** [comment]
> Please use the [template](https://raw.githubusercontent.com/prettier/prettier/main/.github/ISSUE_TEMPLATE/formatting.md) in the [first issue comment](https://github.com/prettier/prettier/issues/12625#issue-1196893208). Issue templates includes the link to the Playground.

Now i have done this...

**Comment by kachkaev** [comment]
Hi @Timbuktu1982! I am afraid that we are still not there with the issue template. I am going to close this issue but feel free to open a new one. You can find issue examples by browsing this repo (e.g. [open issues tagged as bug](https://github.com/prettier/prettier/issues?q=is%3Aissue+is%3Aopen+label%3Atype%3Abug)).

I understand that it might be confusing to use the [Markdown template](https://raw.githubusercontent.com/prettier/prettier/main/.github/ISSUE_TEMPLATE/formatting.md), so you can open the [Playground](https://prettier.io/playground/), craft your example and then press _Report issue_ in the bottom-right corner of the UI. This will fill in most of the template for you.

Good luck and sorry for being bureaucratic! It is necessary to start with a clear problem definition to make sure that everyone is on the same page and the bug is real.

**Comment by Timbuktu1982** [comment]
> Hi @Timbuktu1982! I am afraid that we are still not there with the issue template. I am going to close this issue but feel free to open a new one. You can find issue examples by browsing this repo (e.g. [open issues tagged as bug](https://github.com/prettier/prettier/issues?q=is%3Aissue+is%3Aopen+label%3Atype%3Abug)).
> 
> I understand that it might be confusing to use the [Markdown template](https://raw.githubusercontent.com/prettier/prettier/main/.github/ISSUE_TEMPLATE/formatting.md), so you can open the [Playground](https://prettier.io/playground/), craft your example and then press _Report issue_ in the bottom-right corner of the UI. This will fill in most of the template for you.
> 
> Good luck and sorry for being bureaucratic! It is necessary to start with a clear problem definition to make sure that everyone is on the same page and the bug is real.

Hi Kachkaev,

thank you for the info.

But i cannot find the option "single-attribute-per-line" in the options list on left side of issue template window, so i cannot use the issue template. Also i cannot select "hbs"-files as script source, so i cannot simulate the real life of my problem...
