### ISSUE TITLE
Whitespace is incorrectly inserted between inline elements, even if html-whitespace-sensitivity is set to strict

### ISSUE THREAD

**Issue by distinctdan** [prettier/prettier#12629]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT77VwzrWcAPHRwA3AHwcuXQQCNxAZQCGAWzj4SOKHAA0+AM4AHJWDhJBAenlTpwsfjAkl+-QF42IHPBUfJnaTJGSlDiqBAQlkEh+IJR4rJK1JHGITYyFiISHGmsFgBU+AAqABY4+vjw+jAOzuplFcXqsugA5npeNVAA5NX6SqikAJ74hujVHgnUHvgESvjaAO4aWup5FgC+OXKKquqa2npQEAbGppbW-jKZDk4u7p7evjmBKaHhycHisa+TH6mXMQyYj8W3kABEcKgBjxYMttPpzn4AnZRDdnG4PF44D4QEiAjE4mEIhY4s8CT9En88elMnjLLSANwcdYgHQgCCGXDQfTIUCJagQBYABUSCB5KCUJAWSkGPLZsmoJgA1rxlGoADIrZCoSX6XQgBXK1WnLQtZAwajofXY2RwOh0O3q4ItdBKFpwABiNBUShguCgZolYwgrJAxRgKhIFFKlVOcAUYq8Yi8g2QICq1Bw2FDWj11BgQsVLR92t1+oAVvoAB4KU0kOAARXQEHgpZIerZxmoebTCVtJFDhkzsAoODoMGKyAAHAAGTsCvUURWGNNDuB50RwUMAR2b8ELHPFIGcAFptHa7aGeLucDxC26S0gde39XqVDhzZbX3XG3ut0+yzZGAlFkUdx0nJAACYgMVHB9haABhCAVEfEB1wAVlDdA9UKEDxWfDsQFEK0AEkoAdWAFDATNOQAQXIhQYEGes2z1dZ1iAA)

```sh
--parser babel
--html-whitespace-sensitivity strict
```

**Input:**

```jsx
function HelloWorld() {
  return <div>
    <b>Same line, space:</b>
    <div class="item">
      <span>foo</span> <span>bar</span>
    </div>

    {/* This test case is the bug, it can't safely put "bar" on a new line */}
    <b>Same line, no space</b>
    <div class="item">
      <span>foo</span><span>bar</span>
    </div>

    <b>Different lines</b>
    <div class="item">
      <span>foo</span>
      <span>bar</span>
    </div>
  </div>;
}
```

**Output:**

```jsx
function HelloWorld() {
  return (
    <div>
      <b>Same line, space:</b>
      <div class="item">
        <span>foo</span> <span>bar</span>
      </div>

      {/* This test case is the bug, it can't safely put "bar" on a new line */}
      <b>Same line, no space</b>
      <div class="item">
        <span>foo</span>
        <span>bar</span>
      </div>

      <b>Different lines</b>
      <div class="item">
        <span>foo</span>
        <span>bar</span>
      </div>
    </div>
  );
}

```

**Expected behavior:**
Prettier shouldn't be breaking the middle test case onto separate lines. If you look at this jsfiddle, you can see the difference that a newline makes in this case: https://jsfiddle.net/pr6ob0su/3/

However, could this be a problem with the playground config? If I set the parser to html, it works correctly, but I thought it was supposed to autodetect the language.

**Comment by Josh-Cena** [comment]
Using Babel means you are parsing this code as JSX, not HTML. And JSX is whitespace-insensitive and that line break won't be turned into a space.

**Comment by distinctdan** [comment]
Ah, thanks for the information, that explains it. Sorry, I had been copying the playground output into a js fiddle to test it, and I was just testing as html instead of jsx.
