### ISSUE TITLE
crash on variance annotations in typescript 4.7

### ISSUE THREAD

**Issue by DetachHead** [prettier/prettier#12630]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#optional-variance-annotations-for-type-parameters

**Environments:**

- Prettier Version: 2.6.2
- Running Prettier via: cli
- Runtime: node 16.11.1
- Operating System: windows 10
- Prettier plugins (if any): 

**Steps to reproduce:**
```ts
interface Foo<in T> {}
```

**Expected behavior:**
no crash
**Actual behavior:**
```
src\utilityTypes\misc.ts[error] src\utilityTypes\misc.ts: SyntaxError: Type parameter declaration expected. (24:15)
[error]   22 |     : false
[error]   23 |
[error] > 24 | interface Foo<in T> {}
[error]      |               ^
[error]   25 |
[error]   26 | /**
[error]   27 |  * Checks if two types are equal at the type level.
```

**Comment by fisker** [comment]
Please follow the issue template, otherwise this issue    will be  closed.

**Comment by DetachHead** [comment]
@fisker um i did?

**Comment by sosukesuzuki** [comment]
We track the status of TS 4.7 support in #12640
