### ISSUE TITLE
Upgrading to v1 breaks husky / lint-staged

### ISSUE THREAD

**Issue by VP42** [prettier/prettier#1264]
Hello!

Thank you so much for releasing the v1 of Prettier! It's a great tool that we recently add on our project and improved it significantly.

We encounter a problem while trying to update to the latest version. The npm install prettier@1.1.0 succeed but then, when we try to do a git add / commit, husky no longer works. I don't know if it may be linked but the path of the updated file seems duplicated.

```
> husky - npm run -s precommit

 ❯ Running tasks for cube-square/app/**/*.js
   → /Users/Valentin/DKT/workspace/cube-square/app/core/containers/HomePage.js/Users/Valentin/DKT/workspace/cube-square/app/core/containers/HomePage.js
   ✖ prettier --list-different --print-width 240 --single-quote true --jsx-bracket-same-line true --trailing-comma es5 --write
     → /Users/Valentin/DKT/workspace/cube-square/app/core/containers/HomePage.js/Users/Valentin/DKT/workspace/cube-square/app/core/containers/HomePage.js
     git add
🚫 prettier --list-different --print-width 240 --single-quote true --jsx-bracket-same-line true --trailing-comma es5 --write found some errors. Please fix them and try committing again.

/Users/Valentin/DKT/workspace/cube-square/app/core/containers/HomePage.js/Users/Valentin/DKT/workspace/cube-square/app/core/containers/HomePage.js
```

Any idea about this one?
Thanks again!

**Comment by hawkrives** [comment]
If you just run your prettier command on the changed files, does it succeed? There aren't many cases where Prettier exits with a non-zero status, but there are some.

**Comment by jlongster** [comment]
One thing that stands out to me is `--jsx-bracket-same-line true`. It should just be `--jsx-bracket-same-line`. But I don't *think* that should make a difference.

We can't help without actually seeing the error. We don't provide support for debugging husky or line-staged problems, so if you can give us a clear error that prettier is throwing, we can help. Otherwise you might want to ask lint-staged.

**Comment by VP42** [comment]
Clearly the bug it on husky or lint-staged, I'll dig it! Thanks again for your time and the great work!

**Comment by VP42** [comment]
I can't explain it but removing `--list-different` param did the trick!
