### ISSUE TITLE
Comment in array destructuring are moved inappropriately

### ISSUE THREAD

**Issue by epmatsw** [prettier/prettier#12645]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtA9AKkwFcoi04ATTfXAGkwCMBdTAXkwogBUALASygBzABQBKANwhaICAAcYfdMlABDAE5qIAdwAK6hGmQgVAGy0qAnoekM1KsAGs4MAMoqAtnAAyAuMgBmpuQ2do7OLrL2AoLIMGpEcNJw7gyUFJReKkJEKoJwAGIQau4qMApCRipEMBBSIDww7iYA6vzwaJFgcC4GfAoAbn0WRmBo1iAC5GowOnaCJQFBiSAAVmgAHi7RJnAAikQQ8IsmwSCRalNGDCqpJnWyagIwzXwUMDzIABwADNIPEORmnZZEYHnApv0-NIAI4HeCzOSGFAqNAAWigcEolDqajgsL4uNmuQWSECJ2W5HcfFi8Qp2z2cL8pKW0hgNxebw+SAATKy7HwTNEAMIQdwkkDggCsdTIcC4NyRZNO-QSAEkoOlYC4wI95ABBDUuGAWHbHcgAX3NQA)

```sh
--parser babel
```

**Input:**

```jsx
const [/* unused */, b] = doThing();
```

**Output:**

```jsx
const [, /* unused */ b] = doThing();

```

**Expected behavior:** It should leave the comment in the intended place in the destructured list.

**Comment by B2o5T** [comment]
Related https://github.com/prettier/prettier/issues/1013

**Comment by kachkaev** [comment]
Thanks for the link @B2o5T! @epmatsw, let’s track this issue in #1013!
