### ISSUE TITLE
Comment between a constructor call and the parens gets duplicated

### ISSUE THREAD

**Issue by Josh-Cena** [prettier/prettier#12646]
I was inspecting the possibility of formatting a JS file with type-comments in Prettier after reading https://github.com/microsoft/TypeScript/issues/48650. It turned out to be mostly working, except for this edge case.

**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEU4HcAEAFCBLWAegCoklMAeAIzwHMCYA+TYwgCgBYoAaTAVigBKADpQQ3EBAAOMPNADOyUAEMATqojpsahIpTKANumUBPRRKqrlYANZwYAZWUBbOABkCcZADND8uBZWtvYOUtYEtMgwqgCuASBwzlRwACYpqW7KULQxyrRwAGIQqs7KMLLZyCDKMTAQ4iAAFjDOBgDqjXjw8mFgcA66XXgAbl0mVWDy5iAE-qow2Fa0pT5+8QBW8gAeDhEGcACKMRDwqwb+EmGqc1VUyskGDVKqDG14KTCNyAAcAAyXGn8bSsUiqzzgc2GXgkAEdjvBFtI9NV5ABaNCpVINVRwOF4HGLPIrJC+c7xfzOPBRWLkvaHeFeElrCQwe5vD5fJAAJhZVjwBgiAGEIM5iQl5HwGjF-AAVe56UkXEDDOIASSg6VgDjALxkAEENQ4YCZ9md-ABfc1AA)

```sh
--parser babel
```

**Input:**

```jsx
new Point/*:: <bigint> */(4n, 5n)

```

**Output:**

```jsx
new Point/*:: <bigint> */(/*:: <bigint> */ 4n, 5n);

```

**Expected behavior:**

The comment should not be duplicated.

**Comment by kachkaev** [comment]
Interesting! This somehow depends on `::`:

```js
new Point/*:: <bigint> */(4n, 5n)
// ↓
new Point/*:: <bigint> */(/*:: <bigint> */ 4n, 5n);


new Point/* <bigint> */(4n, 5n)
// ↓
new Point(/* <bigint> */ 4n, 5n);


new Point/*::: <bigint> */(4n, 5n)
// ↓
new Point/*:: : <bigint> */(/*::: <bigint> */ 4n, 5n);


new Point/* :: <bigint> */(4n, 5n)
// ↓
new Point(/* :: <bigint> */ 4n, 5n);
```

**Comment by Josh-Cena** [comment]
Could be an attempt to format Flow comments? Not very familiar with that though, so I have little idea what's going on

**Comment by Josh-Cena** [comment]
Interesting, there's even an idempotency hazard.

```js
new Point/*::: <bigint> */(4n, 5n)

new Point/*:: : <bigint> */(/*::: <bigint> */ 4n, 5n);

new Point/*:: : <bigint> */(/*:: : <bigint> */ /*::: <bigint> */ 4n, 5n);

new Point/*:: : <bigint> */(
  /*:: : <bigint> */ /*:: : <bigint> */ /*::: <bigint> */ 4n,
  5n
);

new Point /*:: : <bigint> *//*:: : <bigint> */(
  /*:: : <bigint> */ /*:: : <bigint> */ /*::: <bigint> */ 4n,
  5n
);

// Keeps growing between "new Point" and "("
```

**Comment by fisker** [comment]
That's known issue.
