### ISSUE TITLE
Integrating to Typescript.

### ISSUE THREAD

**Issue by Harry-Hopkinson** [prettier/prettier#12650]
Does Prettier have any intentions to integrate to a Typescript code base. I feel that it would be beneficial to have typings and better code intellisense.

**Comment by kachkaev** [comment]
I think TSC is already used for linting Prettier codebase. You can follow [the history of `tsconfig.json`](https://github.com/prettier/prettier/commits/main/tsconfig.json) to find links to relevant discussions and PRs. Shall we close this issue?

**Comment by Harry-Hopkinson** [comment]
Thanks!
