### ISSUE TITLE
Nestled JSDoc comments are still broken after #9672

### ISSUE THREAD

**Issue by thw0rted** [prettier/prettier#12653]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAOiAEICGATqQNzFQMD0AVCw5i5gALwC2ABwA2FeJgAqHLtwHUKfTMHEBPAXAC+mGKrhSesqvMXjNANwpCArrqiceVODEtVbwAGoXr6qU1btb0gZGSjqa2mp63A5OLooeVho+DNiWUGAwAJbQmOYJABThcAA0OZ5wAJSKHJgZ2Jh51ADmlnwIMGgAdEIIjTAAFoQERABMlcDVmJjRzrZQcADumADC0GDRcPHWBToludbl9LaYmnBCaHBVR5PTsXOLm3DbagfV3lBvIEUgEAKZ6MigahUCDzAAK1AQaGQIAs8woyihXwARoYwABrRwAZXkcAAMhk5shsBZzsjURiYJjZGACY1kDAqNYvnA+Ei4AATdkc3EUKDNCiNOAAMQgVD4okyfOhFEsMAgnxAfRgfCEAHU+hl4GhqXBMZDNRlTJrlNCwGhESACecqDBQYZGuKiSTiiAAFZoAAemNp3QAipYIPAnWcXQZrdCkRQ2UIFQIqASYKqMuz+sgABwABi+cYg51VhgE0LjcGtpjgCoAjgH4HaflCUBQ0ABaOYcjkKhxVjIOO0Cx1IYkhr7nPgZemMl1oH1wf2B8sD51fGBRpMpvrIYZLwwZIS0lZ8fsgEsAVgVlnO4ij9cHpJApmsAEkoFzYJi1hlfgBBZ+Y7TdYPnOo6hAA)

```sh
--parser babel
```

**Input:**

```jsx
const foo = "Bar";

/**
 * @template T
 * @param {Type} type
 * @param {T} value
 * @return {Value}
 *//**
 * @param {Type} type
 * @return {Value}
 */
function value(type, value) {
  if (arguments.length === 2) {
    return new ConcreteValue(type, value);
  } else {
    return new Value(type);
  }
}

```

**Output:**

```jsx
const foo = "Bar";

/**
 * @template T
 * @param {Type} type
 * @param {T} value
 * @return {Value}
 */ /**
 * @param {Type} type
 * @return {Value}
 */
function value(type, value) {
  if (arguments.length === 2) {
    return new ConcreteValue(type, value);
  } else {
    return new Value(type);
  }
}

```

**Expected behavior:**

As reported in #7724, JSDoc function overloads require two comment blocks "nestled" together.  When that issue was reported, "nestled" comments would have a blank line inserted between them, breaking the JSDoc parser.  That issue was closed via #9672.  Now, instead of inserting a blank line, Prettier inserts a single space, turning `*//**` into `*/ /**`.  This still breaks the JSDoc parser.  The sequence must be exactly `*//**`, and it must not be modified by Prettier at all.

/cc @fisker, who wrote the linked PR, and @grassator who reported the previous issue.

**Comment by thorn0** [comment]
fixed by #13445
