### ISSUE TITLE
`break;` and `continue;` statements without braces followed by inline comment followed by `else` breaks prettier

### ISSUE THREAD

**Issue by aeharding** [prettier/prettier#12655]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKACLGBmEBOGAFANwkCUGw622AljsTPgK5yUBG+cAhgNYkMAeiEYYACzoBnDJAC2chDADkMuAA9p8KGDgYA7nQA2RjF158MdGDVoY4RqXrwQi5ErawBfdCAA0IBAADjB00FLIoDz4+BD6AArRCBEoPEb6PACeEQFcPGB8cDAAyjyKADJ0UHDIOGlOufj5hSVB+VUA5sjMbAFwchxwACZDw+U8UB0sPB1wAGIEcjwwoZPIIDwsMBD+IOIwckYA6pLwUm26xcnWdABu1pnrYFI5IFVO+DDxTR1LtfVwAIAKyk6mKnSMcAAiiwIPB-o5ASA2vgPusODxBkZdkF8FUYEc6EMJMgABwABgCuIgTiOTSC61xcA+txqAQAjrD4N9gikNlIALTVYbDXbcTl0bjfGZ-JB1REBJxyOjdVhIqQQ6FcmpygEBGCYwnE8TIABM+qaxk6AGEIAoeOtmQBWXYsJwAFUxKXlDRAtzYAEkoKNYMUwHiQgBBYPFGCZSEIpxeLxAA)

```sh
--parser babel
```

**Input:**

```jsx

for (;;) {
  if (true) break; // this comment's existence will break it
  else foo();
}


```

**Output:**

```jsx
_@https://prettier.io/lib/standalone.js:41:7587
b@https://prettier.io/lib/standalone.js:41:15205
D@https://prettier.io/lib/standalone.js:45:576
St/<@https://prettier.io/lib/standalone.js:115:7299
formatCode@https://prettier.io/worker.js:141:21
handleMessage@https://prettier.io/worker.js:78:36
self.onmessage@https://prettier.io/worker.js:36:14

```

**Expected behavior:**

Prettier should not break.

**Comment by Harry-Hopkinson** [comment]
The comment is get printed but an error occurs, just looking into this now.
