### ISSUE TITLE
generator format

### ISSUE THREAD

**Issue by nihgwu** [prettier/prettier#1266]
prettier@1.1.0
* original:
![image](https://cloud.githubusercontent.com/assets/2595058/25034830/073f14f2-211c-11e7-8487-4dda4049d3a5.png)

* after prettier:
![image](https://cloud.githubusercontent.com/assets/2595058/25034678/ca74a61e-211a-11e7-8113-ef1fabb92267.png)

which raises an eslint error 
> [eslint] Missing space after *. (generator-star-spacing)

BTW, the normal generator function is OK
![image](https://cloud.githubusercontent.com/assets/2595058/25034863/3fad4a84-211c-11e7-9e38-a23a843316c8.png)

**Comment by vjeux** [comment]
This eslint rule ( http://eslint.org/docs/rules/generator-star-spacing ) looks super weird to me. I've never seen anyone put a space between the `*` and function name in the shorthand version. And `function*` looks like a keyword to me.

I would love to get some more feedback on this one before we make a decision. I'm pretty happy with the current way prettier outputs generators.

**Comment by jlongster** [comment]
It looks strange to me too, like it's floating and not clear what it's attached to. You shouldn't be using any eslint formatting rules with prettier. eslint formatting failures don't really have any bearing on our decisions. We do try to look at popular styles like airbnb to inform our decisions, but that's it.

Closing as we're not going to change it unless there is a lot of noise from the community to do so.

**Comment by monkindey** [comment]
Maybe you can use the [prettier-eslint](https://github.com/prettier/prettier-eslint) to achieve the auto-formatting when what the prettier format didn't match your ESLint rules.

**Comment by SergeyKhval** [comment]
Maybe at least make it configurable?

**Comment by j-f1** [comment]
@sergeykhval see https://prettier.io/docs/en/option-philosophy.html
