### ISSUE TITLE
Please add a space between CJK characters and $...$ in markdown

### ISSUE THREAD

**Issue by ZhuangQu** [prettier/prettier#12678]
In markdown, `您abc123好` is converted to `您 abc123 好` after formatting, which is reasonable. However, `您$1+1=2$好` is not converted to `您 $1+1=2$ 好` after formatting, which is a pity. A space is also required between CJK characters and math area, just like CJK and Latin.

**Comment by ZhuangQu** [comment]
Please forgive me for not writing issue according to the template, because I can't open [the playground](https://prettier.io/playground).

**Comment by fisker** [comment]
We are planning to STOP inserting space, so we won't fix this. #6385

**Comment by fisker** [comment]
> I can't open [the playground](https://prettier.io/playground).

什么地方屏蔽了? 我江苏电信能访问.

**Comment by ZhuangQu** [comment]
> 什么地方屏蔽了? 我江苏电信能访问.
我在广州无法访问

**Comment by ZhuangQu** [comment]
> We are planning to STOP inserting space, so we won't fix this. #6385

When do you plan to stop adding spaces?

**Comment by fisker** [comment]
In v3.

**Comment by ZhuangQu** [comment]
> In v3.

Please remain a setting option to maintain the status quo. As a Chinese, I need to add a space between Chinese and English. QAQ

**Comment by fisker** [comment]
I'm going to close this since we are not going to fix your issue.
