### ISSUE TITLE
eslint-disable-line comments shouldn't be put on new line

### ISSUE THREAD

**Issue by ipanasenko** [prettier/prettier#1267]
Hi, guys

I think `// eslint-disable-line` comments shouldn't be placed on new line. What do you think?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22if%20(confirm('Are%20you%20sure%3F'))%20%7B%20%2F%2F%20eslint-disable-line%20no-alert%5Cn%20%20doAwesomeStuff()%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by SimenB** [comment]
You can do this as a workaround: https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20eslint-disable-next-line%20no-alert%5Cnif%20(confirm('Are%20you%20sure%3F'))%20%7B%5Cn%20%20doAwesomeStuff()%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by ipanasenko** [comment]
Yes I can, thanks.
Anyway, is this something that should be considered fixing?

**Comment by SimenB** [comment]
I agree it's a bug, unsure if Prettier should special-case comments like that (linter ignore comments) though. One of the maintainers will probably chime in 😄

**Comment by jlongster** [comment]
`eslint-disable-line` does not work well with prettier. We are inherently going to move around your code. Where should we put it if we end up breaking that expression across multiple lines?

`eslint-disable-next-line` usually works pretty well, so you should use that instead.

**Comment by zachlysobey** [comment]
pretty obvious I guess,... but this same issue exists with `tslint-disable-line` comments
