### ISSUE TITLE
Parsing error with generic function

### ISSUE THREAD

**Issue by tibdex** [prettier/prettier#1268]
Hi and thanks for this amazing project !

I've tried the _1.1.0_ release but quickly stumbled on this [parsing error](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20identity%20%3D%20%3CT%3E(t%3A%20T)%3A%20T%20%3D%3E%20t%3B%5Cnconst%20a%20%3D%201%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D):

```javascript
SyntaxError: Unexpected token (2:0)
  1 | const identity = <T>(t: T): T => t;
> 2 | const a = 1;
    | ^
```

It's a [valid Flow syntax](https://flow.org/try/#0MYewdgzgLgBAlgEwKZinKBPGBeGAeAFQD4AKKALhgIEpKCciYoBuAKFElgEMcYBGZkA) and was working fine with previous versions of `prettier`.

The problem comes from `babylon` 7.0.0-beta.8 so I created an issue there too: https://github.com/babel/babylon/issues/471.

**Comment by jlongster** [comment]
Thanks for notifying us! If a lot of people bump into this we'll try to figure something out.

**Comment by vjeux** [comment]
It seems to be parsing fine with the flow parser. So to get you unblocked you can do `--parser flow` or `{parser: 'flow'}` in the options.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20identity%20%3D%20%3CT%3E(t%3A%20T)%3A%20T%20%3D%3E%20t%3B%5Cnconst%20a%20%3D%201%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Once it gets fixed in babylon project and they do a release, we'll update it inside of prettier and do a release. If you want to help, it's likely relatively easy to fix and I'm sure the folks working on babylon would love a PR :)

**Comment by existentialism** [comment]
Definitely welcome a PR :)

I'll try to get to this and the comma/location end issue on flow types over the weekend as well.

**Comment by existentialism** [comment]
Fixed in babel/babylon#475, will update prettier as soon as we tag a new version!

**Comment by tibdex** [comment]
Thanks for the fix @existentialism ! Do you have an idea of when we could expect `Babylon` _7.0.0-beta.9_ ?

**Comment by existentialism** [comment]
@tibdex sorry I missed this message! Just merged :)
