### ISSUE TITLE
SyntaxError: Unexpected character '`' [./~/jest-validate/build/utils.js:15,0]

### ISSUE THREAD

**Issue by go1t** [prettier/prettier#1269]
Hi I'm trying to use prettier in create-react-app to format code snippet. It works fine until I tried to build it using `npm run build`. I got this error:
```
static/js/main.8cb118c9.js from UglifyJs
SyntaxError: Unexpected character '`' [./~/jest-validate/build/utils.js:15,0]
```

Is there a recommended way to work around this? thank you very much!

**Comment by jlongster** [comment]
This doesn't give is much info to go on. From those 2 lines I would expect that this isn't related to prettier at all. Please provide a lot more output & context!

**Comment by go1t** [comment]
Thank you for the reply! I realized that I made the issue at the wrong place haha. I guess if I want to use prettier I will have to eject from create-react-app after all since prettier uses `jest-validate` and it's not uglifyJS compatible haha.

Please feel free to close this.

**Comment by chilloutman** [comment]
What is the target environment for `prettier`? I seems to be ES5, but the `jest-validate` dependency uses ES6 template literals.

It would be great to have a `prettier-standalone`, similar to `babel-standalone` (all compiled down to ES5, no dependencies). But if the browser is not an intended target, that might not make sense.

(`create-react-app` is increasingly a PITA with its insistence on requiring everything to be ES5. These are just the waves from that core issue.)

**Comment by vjeux** [comment]
@cpojer: can you fix jest-validate so that it doesn't break when included inside of create-react-app? :)

**Comment by cpojer** [comment]
No but you can send a PR to fix it.

**Comment by vjeux** [comment]
@chilloutman would you be interested in fixing it inside of jest?

**Comment by cpojer** [comment]
Actually, we make Jest compatible with Node 4+ and we will not be transforming that code to ES5. Sorry about that. However, you can process the jest-validate package from what we ship to ES5 afterwards.

**Comment by vjeux** [comment]
prettier is also compatible with node 4+ fwiw.

**Comment by chilloutman** [comment]
Fair enough. Effectively, both `jest-validate` and `prettier` are incompatible with `create-react-app` until that starts supporting ES6 dependencies, which will happen eventually (babili).

I'll keep using my cobbled together [`prettier-standalone`](https://www.npmjs.com/package/prettier-standalone) for now.

I think this issue can be closed.

**Comment by go1t** [comment]
I think it would be really nice if prettier includes a bundled version like what @chilloutman did with his `prettier-standalone`, probably at `prettier/min` or `prettier/dist` so people who want to use it on the web can install this separately. Though the cost would be upgrading the bundle file along with prettier haha.

**Comment by vjeux** [comment]
I'm going to close this issue as we're not looking into changing this right now.
