### ISSUE TITLE
Wrong JSDoc comments indentation

### ISSUE THREAD

**Issue by FezVrasta** [prettier/prettier#1270]
I'm trying to run Prettier on my [Popper.js](https://github.com/FezVrasta/popper.js) repository but in some files I get a wrong indentation in the JSDoc comments:

```js
// default options
const DEFAULTS = {
  // placement of the popper
  placement: 'bottom',

  // whether events (resize, scroll) are initially enabled
  eventsEnabled: true,

  /**
     * Callback called when the popper is created.
     * By default, is set to no-op.
     * Access Popper.js instance with `data.instance`.
     * @callback createCallback
     * @static
     * @param {dataObject} data
     */
  onCreate: () => {},
```

I'm using the latest version of Prettier with this command:

```
$(npm bin)/prettier --single-quote --trailing-comma es5 --write "{src,scripts,tests}/**/*.js"
```

**Comment by FezVrasta** [comment]
I noticed that if I fix the indentation manually after I ran Prettier, and then I run it again, the indentation is kept correctly.

**Comment by darahak** [comment]
It's a dup of https://github.com/prettier/prettier/issues/648
