### ISSUE TITLE
Don't unquote reserved words used as object keys

### ISSUE THREAD

**Issue by drdla** [prettier/prettier#1272]
Prettier removes unnecessary quotes from object keys.
Unfortunately, it also removes quotes that eslint deems necessary.

A typical example is this:
```
<div
  style={{
    float: 'left',
  }}
/>
```

I have not witnessed this to actually break anything, but I think it would at least be good practise to preserve / add quotes around reserved words used as object keys.

**Comment by SimenB** [comment]
That's only an issue in es3 envs (ie8 and older). You should adjust you linting, and if you really need it to be quoted, make babel add the quotes

**Comment by jlongster** [comment]
This is a duplicate of https://github.com/prettier/prettier/issues/1103
