### ISSUE TITLE
Investigate async parse support in embed format

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#12751]
We can't simply make `parse` return a Promise, embed parser have to be sync.

Options:

1. Don't support async parser in embed format.
2. Support async `printer.print()` (maybe jest  `printer.embed()` function is enough ), I was not planning to support async printer, there are some known issues in doc

~Personally I prefer `1`.~ I changed my mind, if we don't support it, we can't use `import()` in bultin parser.

@kachkaev @sosukesuzuki  WDYT?

_Originally posted by @fisker in https://github.com/prettier/prettier/issues/12748#issuecomment-1113000323_

**Comment by kachkaev** [comment]
> embed parser have to be sync

Just to make sure I understand the limitation: do you mean the parser for ` ```lang ` blocks in Markdown? Why does this parser have to be sync?

When proposing https://github.com/prettier/prettier/issues/4459, I was thinking of the embedded code blocks in the first place. If they can be parsed and printed asynchroniously, we can spawn multiple sub-processes with tools like `elm-format` and thus speed-up plugins like [prettier-plugin-elm](https://github.com/gicentre/prettier-plugin-elm).

**Comment by fisker** [comment]
> Just to make sure I understand the limitation: do you mean the parser for ```lang blocks in Markdown? 

Correct.

> Why does this parser have to be sync?

In #12748, only the parse function is awaited, and I wasn't going to make `print` accepts asnyc function, and embed format is part of print, so it has to be sync unless we allow a async print function.

**Comment by kachkaev** [comment]
I see. Assuming that we’ve already made `parse` async, what are the practical downsides of making `print` async too? I understand that this is another breaking change to make, but I guess that it’s like 1.1× the effort for end users, not 2×.

I just checked [`prettier-plugin-elm`](https://www.npmjs.com/package/prettier-plugin-elm) which dedicates formatting to `elm-format`. I initially thought that child process was called in the [printer](https://github.com/gicentre/prettier-plugin-elm/blob/main/src/printer.ts), but it was [in the parser](https://github.com/gicentre/prettier-plugin-elm/blob/aedde007e895370896629194a2a7bd198fe09c11/src/parser.ts#L4) instead.

Although `prettier-plugin-elm` does not require an async printer, I wonder if can be still a requirement for someone else. It’ll be a shame if we have to introduce another breaking change later, but on the other hand, sync `printer` may be a good guard against misuse  🤔

**Comment by fisker** [comment]
I tried to add support for async parse support in embed format, turns out 

- plugin's `print()` and it's `print` argument
- plugins's `embed()` function and it's `textToDoc` argument

All have to (not optional) be async.

**Comment by fisker** [comment]
Call `embed` before print? This will require two steps to print, but require only `embed()` to be async.

**Comment by fisker** [comment]
I can't come up an idea to do this right, maybe revert #12748?

**Comment by fisker** [comment]
Working on making the printer async https://github.com/fisker/prettier/pull/1746

**Comment by fisker** [comment]
Fixed in #13104
