### ISSUE TITLE
Refactoring of string with special char

### ISSUE THREAD

**Issue by mtrezza** [prettier/prettier#12752]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
const x = 'https://example.com/ \.path';
```

**Output:**

```jsx
const x = 'https://example.com/ .path';
```

**Expected behavior:**
The string should not be changed; in certain scenarios the string is needed exactly as is.

**Comment by fisker** [comment]
> in certain scenarios the string is needed exactly as is.

When?

```js
'https://example.com/ \.path' ===  'https://example.com/ .path'
```

> The solution is using backticks instead of single quotation marks.

Sounds like bug in template literals.

**Comment by mtrezza** [comment]
> When?

When doing low-level string operations. Both strings are simply not the same. The second string contains 1 char more than the first one.
