### ISSUE TITLE
Restore original input

### ISSUE THREAD

**Issue by tunnckoCore** [prettier/prettier#1277]
i believe it would be good feature and easy to implement, because u parse the incoming input. so we can save it and if we dont like the formatted output we can `prettier --restore` it to get the original

**Comment by vjeux** [comment]
The goal of prettier is to be used for everything. If you are in a position where you don't like the output, this means that you are in the evaluation phase. I would strongly recommend you to use some kind of version control system like git where you can just revert all the changes easily.

**Comment by jlongster** [comment]
Almost all editor integrations just let you undo the formatting. In Emacs I just press the common undo operation (`M-/`). This is an editor integration issue, not one with prettier. Or if you are writing files on disk with `--write`, you can compare the differences with git and just revert there. I don't think prettier should be concerned with this (it would be complex to keep the original text around. could you imagine the confusion if we restored it but accidentally restored it to the wrong text?)
