### ISSUE TITLE
This doesn't look so good

### ISSUE THREAD

**Issue by jbrodriguez** [prettier/prettier#1278]
![screen shot 2017-04-14 at 10 19 37](https://cloud.githubusercontent.com/assets/1305422/25047362/e5377482-20fb-11e7-84b0-177e3f5e2eee.png)

Shouldn't "Core Docs" be on its own line ?
And then "a" and "li" ?

In any case, awesome work with 1.x !

**Comment by vjeux** [comment]
I'm sorry to disappoint but prettier doesn't know how to handle html with templates, so whatever is formatting your code is not prettier!
