### ISSUE TITLE
Avoid tags for the singleAttributePerLine rule

### ISSUE THREAD

**Issue by sergiomartindev** [prettier/prettier#12787]
Is it possible to specify a list of tags to avoid for this rule? I'm working with Vue 3 and I would LOVE to keep both of this tags in one line:

```
<script
  setup
  lang="ts"
>
  ...
</script>
```

```
<style
  scoped
  lang="scss"
>
  ...
</style>
```

**Comment by jd-solanki** [comment]
We can disable this just like we did with indentation (`vueIndentScriptAndStyle`).

**Comment by dshvv** [comment]
me too,how resolve it

**Comment by dshvv** [comment]
> We can disable this just like we did with indentation (`vueIndentScriptAndStyle`).

answer error

**Comment by alokVishu** [comment]
me too,how resolve it

**Comment by dshvv** [comment]
> me too,how resolve it

i dont know. I've given up using prettier
