### ISSUE TITLE
The string is automatically bracketed.

### ISSUE THREAD

**Issue by islandryu** [prettier/prettier#12796]
Seldom is such a declaration made, but I was curious so I made issue.
If one string is enclosed in parentheses, subsequent strings are also enclosed in parentheses.

**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdEAFAhgJwTACzgGcSACXOMqCGMvARwFcBLPAE3QG5UpeAKdAAdKsIqWL04zNnE4gAlDz59MowiXKVqtKTI7devAGZMoYGC2hkheGJbg5+CssF5ky6bHjGbJ2mjpGVgMQZQ9BEBEfDQk9ELl0JXdPNRjxLTwdIOkE+XCyFmNI2zh7FkcktygPDy91DP8swPjZfJSAX14OkAAaEAghS2hiZFBcHAgAd28EUZQsABsprABPUf6AIxwsMABrMoBlLABbOAAZFig4ZGMl0i2d-aORMCuAc2QYHCY4frgTps5Ow5OcsFB3kwsO84AAxCA4E5YcoQ5AgLBMGAQPogAgwE6LADqBBY8GIrzghzmpJYADdSas0WBiBsQFdSDgYBgdu8kbd7n8QAArYgAD0OH0WcAAikxaDckHdFg8orgOWjNlggYscbYrjBCSx2IRkAAOAAM-VsEFIhJ2QjRSxW6xxzHl3MG83RxAAtNc5HIccFZNzoXzFQL+qQTiwvj9BcRJTK5fA479+jAtYbjQRkAAmDM7FiLD4AYQgJ3DIBIAFYcUxSAAVLXzJUq2m-ACSUBBsEOYBwLCGAEEe4cYKspfzlXAOh0gA)

**Input:**

```jsx
"Parentheses are not required";

("parentheses required");

"Parentheses are not required";

function prettier() {
  "Parentheses are not required";
  ("parentheses required");
  "Parentheses are not required";
  if("prettier"){
    "Parentheses are not required";
  }
}
```

**Output:**

```jsx
'Parentheses are not required';

('parentheses required');

('Parentheses are not required');

function prettier() {
  'Parentheses are not required';
  ('parentheses required');
  ('Parentheses are not required');
  if ('prettier') {
    ('Parentheses are not required');
  }
}
```

**Expected behavior:**
Same as before formatting or remove all parentheses.

**Comment by fisker** [comment]
This is format like this on purpose. The first one is a directive, the rest are not.

**Comment by islandryu** [comment]
I understand.
Thank you!
