### ISSUE TITLE
Blank lines between arrow-function class properties not preserved with flow parser

### ISSUE THREAD

**Issue by jkk** [prettier/prettier#1279]
With flow parser (blank line not preserved between `baz` and `quux`):

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Foo%20%7B%5Cn%20%20foo()%20%7B%5Cn%20%20%20%20%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20bar()%20%7B%5Cn%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20baz%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20quux%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

And babylon parser (blank line preserved):

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Foo%20%7B%5Cn%20%20foo()%20%7B%5Cn%20%20%20%20%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20bar()%20%7B%5Cn%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20baz%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20quux%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Thank you for your hard work!

EDIT: it's worth noting that blank lines between non-arrow-function class properties _are_ preserved:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Foo%20%7B%5Cn%20%20foo()%20%7B%5Cn%20%20%20%20%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20bar()%20%7B%5Cn%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20baz%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20quux%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20blah%20%3D%201%3B%5Cn%5Cn%20%20whatever%20%3D%202%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
If you have a ; they are correctly preserved as well.

**Comment by vjeux** [comment]
This has been fixed.
