### ISSUE TITLE
Nice domain name for site

### ISSUE THREAD

**Issue by Daniel15** [prettier/prettier#1284]
Now that prettier has hit 1.0, it's a good time to get a custom domain for the site rather than using the tacky `.github.io` subdomain. What do you think? I'm happy to help out 😃

**Comment by vjeux** [comment]
Would be awesome to make a proper website instead of a badly maintained readme!

**Comment by thiamsantos** [comment]
What about use a [js.org](https://dns.js.org/) domain?

**Comment by luftywiranda13** [comment]
prettier.io?

**Comment by Daniel15** [comment]
Yeah, something like prettier.js.org would be good. prettier.io or prettify.me or something like that would be good too. I'll leave it up to the Prettier team to decide on which domain they like best 😛

**Comment by alexburner** [comment]
I'm with @thiamsantos. FWIW:
- webpack 1.x https://webpack.github.io/
- webpack 2.x https://webpack.js.org/

**Comment by vjeux** [comment]
More than a domain, we need a website :P If someone is willing to help on that front that would be awesome

**Comment by vjeux** [comment]
Done, we have prettier.io now :)
