### ISSUE TITLE
fileType .vue template indent

### ISSUE THREAD

**Issue by wxh250360** [prettier/prettier#12853]
**Environments:**

- Prettier Version: 2.6.2
- Running Prettier via: 
- Runtime: 
- Operating System: 
- Prettier plugins (if any): 

**Steps to reproduce:**
```js
// .prettierrc
{
	"semi": false,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
	"tabWidth": 4,
	"useTabs": true
}

// .eslintrc
module.exports = {
	env: {
		browser: true,
		es2021: true
	},
	extends: ['plugin:vue/essential', 'prettier'],
	parserOptions: {
		ecmaVersion: 13,
		sourceType: 'module'
	},
	plugins: ['prettier'],
	rules: {
		'prettier/prettier': 'error'
	}
}

```

**Expected behavior:**
should not error
**Actual behavior:**
![image](https://user-images.githubusercontent.com/50900333/167379405-014b4241-bbd7-4592-9af0-c73279665319.png)

**Comment by fisker** [comment]
You are still not following the template. https://github.com/prettier/prettier/issues/12852#issuecomment-1120841678

**Comment by wxh250360** [comment]
following template now?
