### ISSUE TITLE
.vue template nodeew IssueIssuReplace `⏎↹↹↹↹ width `·`

### ISSUE THREAD

**Issue by wxh250360** [prettier/prettier#12852]
![image](https://user-images.githubusercontent.com/50900333/167371077-aa87f257-c7e5-49b0-b8c3-c8115a01c632.png)

I configured the printWidth to be 100
```js
{
	"semi": false,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
	"tabWidth": 4,
	"useTabs": true
}
```
Property after a line break，tips must use space

**Comment by kachkaev** [comment]
Hi @wxh250360! Please use the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md) and make sure there is a link to the Playground.
