### ISSUE TITLE
[feat] prefer shorthand properties

### ISSUE THREAD

**Issue by loynoir** [prettier/prettier#12864]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
```

**Input:**

```jsx
import { xyz as xyz } from 'xyz'
var o = { a: a, b: b, c: c };
export { foo as foo }
```

**Output:**

```jsx
import { xyz as xyz } from 'xyz'
var o = { a: a, b: b, c: c };
export { foo as foo }
```

**Expected behavior:**
```jsx
import { xyz } from 'xyz'
var o = { a, b, c };
export { foo }
```

### Situation
Given
- `{ X }`

When 
- `<F2>` twice to rename reference

Becomes 
- `{ Y: Y }` or `{ Y as Y }`.

### Why
Would be nice if `prettier` can make them shorthand again, as `short-handify` after `rename-reference` is not part of language server protocol.

### Related Doc
https://babeljs.io/docs/en/babel-plugin-transform-shorthand-properties

**Comment by thorn0** [comment]
Prettier generally doesn't do things like this. See https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about
I'd recommend using ESLint. See https://eslint.org/docs/latest/rules/object-shorthand
