### ISSUE TITLE
Prettier does not seem to be using airbnb rules

### ISSUE THREAD

**Issue by philmetzger** [prettier/prettier#12862]
I am using the AirBnb StyleGuide with prettier, now when I save, the code is formatted but doesnt seem to use any airbnb rules.

Here is my `package.json` (devDependencies):

    "eslint": "^7.21.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "prettier": "^2.6.2",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-tailwindcss": "^3.4.3",

Then in `.eslintrc.json` I have this configured:

    "extends": [
      "eslint:recommended",
      "plugin:react/recommended",
      "plugin:tailwindcss/recommended",
      "plugin:@next/next/recommended",
      "airbnb",
      "prettier"
    ],
    "plugins": [
      "react",
      "react-hooks",
      "tailwindcss",
      "node",
      "prettier"
    ],

And finally my `.prettierrc` file:

    {
      "tabWidth": 4
    }

When I save, the tabWidth is set, but I also expect quotes to be replaced by single quotes as it mentions here: https://github.com/airbnb/javascript#strings

In a `test.js` file I have this:  `const test = "bla";` and on save it remains as double quotes. If I add `"singleQuote": true` to `.prettierrc` then it works. But I should not need to do that right as I use airbnb?

Any ideas?

**Comment by kachkaev** [comment]
👋 @philmetzger! Please [use StackOverflow for support questions](https://stackoverflow.com/questions/ask?tags=prettier). Issues are dedicated to development purposes.
