### ISSUE TITLE
bracket-same-line is ignored for JSON formatting

### ISSUE THREAD

**Issue by BergenSoft** [prettier/prettier#12884]
When bracket-same-line is disable I would expect, that brackets should go to the next line also for JSON.

**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6ICGAbbB5KDJAAgwGUBLKAc2zgwBpSQAZK+5ZuAD0wFsADnUZpCIKBDIDMYDkhgAnAK5wGo4swCOSiPCLF0UDRoDkAZyq04ARR3wTJEz35C4JtUeNfv3jFQAmCPD++ooqHhoAvhHG6swCABbQcABySnwARnAKZvrEANpxGuggMACeAnLMSXwcMV4YUOlZCvoYAEwAjO3EAKz9ALTdAMwALBjRRQYY5ZVtIBAAZosUsiKeDaUKmBTYlvOQfHyYZsQZZcQyYBSBsBMxALoekSAMCwIwFNBmyKCYCgoIAB3AAK-wQPxQOCBmDKPzeGW2YAA1nAYGR+HA2FA4MhFjgzKoQIiZKj0dJrjRkGEiXBMnB-IF-CxMDQlJhqHAAGIQBTHGCfKlQpQwCCvEAJGB8bAAdQSFHgZgpcDIEIVFAAbgqyshwGZ4SAqISFDAQdtqMc8QSiQArMzcSg0Oi2XS4pD47CEt7SHLZXV26DigQKKgwGU3GAJZAADgADN7AYSZdsBLrg3BjRrcW9tK6zRABJCsGYBjiGQzxQo4NoKFWzRzLe7rW9CXwKNTlESLE6bHY3R6vaVMBlw-5I8h2m9FDs9jQAMIQI6YXUZ3ripSEgAqw8hA6JGpUAEkoLd0WAQx8AIInsjlOhWz1wSKRIA)

```sh
--parser json
```

**Input:**

```jsonc
{"allOn": "Single", "Line": "example",
"noSpace":true,
  "quote": {
    'singleQuote': 'example',
                  "indented": true,
  },
    
  "phoneNumbers":  [
    {"type": "home",
      "number": "212 555-1234"},
    {"type": "office",
      "trailing": "commas by accident"},
  ],
}
```

**Output:**

```jsonc
{
    "allOn": "Single",
    "Line": "example",
    "noSpace": true,
    "quote": {
        "singleQuote": "example",
        "indented": true
    },

    "phoneNumbers": [
        { "type": "home", "number": "212 555-1234" },
        { "type": "office", "trailing": "commas by accident" }
    ]
}

```

**Expected behavior:**
```jsonc
{
    "allOn": "Single",
    "Line": "example",
    "noSpace": true,
    "quote":
    {
        "singleQuote": "example",
        "indented": true
    },

    "phoneNumbers":
    [
        { "type": "home", "number": "212 555-1234" },
        { "type": "office", "trailing": "commas by accident" }
    ]
}

```

**Comment by Josh-Cena** [comment]
That's not really what the [`bracketSameLine`](https://prettier.io/docs/en/options.html#bracket-line) option does. 

> Put the `>` of a multi-line HTML (HTML, JSX, Vue, Angular) element at the end of the last line instead of being alone on the next line (does not apply to self closing elements).

The "bracket" means "angle bracket"

**Comment by BergenSoft** [comment]
Understand, than this issue should be read as feature request. Is it possible to add this in future releases?

**Comment by Josh-Cena** [comment]
Per [options philosophy](https://prettier.io/docs/en/option-philosophy.html), no, I don't think this would be accepted.
