### ISSUE TITLE
How to infer HTML content in other languages as `angular` or other parser?

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#12881]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAyjCAnAngPgB0oACE4YYss+AWwAcAbAQ3iRIHoAqEgCQBUAsgBkSXDiQAGFACatmAHwBWAZ2gBfdZIA0VEpuKoOmHAQDcxENpAR6MAJbQVyUM2zYIAdwAKbhM5RmRk9mXGdrACNsZjAAazgYdGZaOGF7KDhkADMglThI6LiE9HoY9IBzZBhsAFd8kDhaCLgZGRbhZihymuZyuAAxHFpWBy7kEGYarCsQAAsYWkYAdVn7eBVSsDh0fzX7ADc13HGwFXCQdLzsGG9o8uHs3PrVAA90CsY4AEUaiHhHxh5aylbBXcYRZjNRgzejYdIwJb2GQwWbIAAcAAZgR48ktovRxrC4Fd9plrABHX7wW62AITFQAWgyLRaM2wcEp9nZt16DyQOUB9TytHsVVqQo+3ypmX5T2sMEhiORqKQACZ5dF7IwKgBhCC0PkNFQAVhmNTy-EhAQFQJA+zqAEkoG1YOgwHC7ABBZ2YXCfAF5TRAA)

**Input:**

```jsx
<Story>
  {{
    template: /* HTML */ `{{data|json}}`,
  }}
</Story>;
```

**Output:**

```jsx
<Story>
  {{
    template: /* HTML */ `{{data|json}}`,
  }}
</Story>;
```

**Expected behavior:**

```jsx
<Story>
  {{
    template: /* HTML */ `{{ data | json }}`,
  }}
</Story>;
```

**Comment by fisker** [comment]
There is no way, unless you print javascript yourself, and we don't have plan to support it, at least not in near future. PRs from team member also has been  rejected https://github.com/prettier/prettier/pull/5993#issuecomment-478573220 https://github.com/prettier/prettier/pull/12430

**Comment by fisker** [comment]
I'm going to close this, since we won't fix it.
