### ISSUE TITLE
fix confusing formatting of fractions

### ISSUE THREAD

**Issue by ianstormtaylor** [prettier/prettier#12927]
When you want to use fractions in a calculation, Prettier's formatting is very annoying. 

**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAE6oHMYAWmAvJgKwAMA3ADpTpZgCGqYJ2C+RAVJgEwB6AMwgANCAgAHGAEtoAZ2SgmAJxUQA7gAVVCRShYamAT0XiARiqZgA1hgDKTALZwAMjKhxkAMxby4Fla2DpLWHrjIMCoArgEgcE7mcAAmySmuTHjRTLhwAGIQKk5MMLJ4yCBM0TAQYiAEME6oAOoEMvDyoWBw9nrtMgBu7cYVYPJmIB7+KjBaVrjFPn5xAFbyAB724egAitEQ8Euo-uKhKtMV5kxJqHWSKh4wzTLJhMgAHBSn6v7NVpIVe5waYDLziACO+3gcyk+kq8gAtJ4Uik6io4JCZOi5jlFkhfMc4v4nDIjicQPJtnA9gcvEgorFxDBrs9XgRkHwmVYZKhwgBhCBOPHxeRkOrRfwAFWu+gJ5IGsQAklA0rB7GAHtIAIIq+wwYzoMlwAC+xqAA)

```sh
# Options (if any):
--single-quote
--no-semi
```

**Input:**

```jsx
let length = 50
let calc = length * 2/3
```

**Output:**

```jsx
let length = 50
let calc = (length * 2) / 3
```

This formatting change makes it much harder to understand the intention!

---

**Expected behavior:**

Ideally: let fractions be tightly formatted, like the input:

```jsx
let length = 50
let calc = length * 2/3
```

Second best: don't add unnecessary parentheses (so the fraction is still semi-readable), like so:

```jsx
let length = 50
let calc = length * 2 / 3
```

I think Prettier should handle this common case more gracefully—it would make dealing with math in Prettier a lot less tedious. Using fractions makes things much more readable, and it can be spotted whenever you have division between integers (not variables or floats).

**Comment by alexander-akait** [comment]
You should use prettier ignore in this case

**Comment by alexander-akait** [comment]
Sorry, we don't want to change our basic output and we don't want to add new options, so there are no solution without `prettier-ignore`

**Comment by jkillian** [comment]
@ianstormtaylor would it be possible just to change your input code to this? I'm not sure it's quite semantically identical in floating-point math, but it's probably perfectly fine for most code:

**Input:**
```
let length = 50
let calc = length * (2/3)
```

**Output:**
```
let length = 50
let calc = length * (2 / 3)
```

Prettier preserves the parens in this case and it makes things much cleaer imo.

**Comment by Josh-Cena** [comment]
`length * (2 / 3)` risks less loss of precision than `(length * 2) / 3` because `2` and `3` are comparable in magnitude (just consider the extreme case of `1e308 * 2 / 3`).

I think a good heuristic would be "prioritize adding parentheses between constants"? i.e. given `a OP b OP c` where the two operators are equal in precedence, Prettier would enclose `b, c` in brackets if they are both constants, or `a, b` otherwise.

**Comment by thorn0** [comment]
`length * 2 / 3` and `length * (2/3)` aren't the same expression in JS and may evaluate to different values:
```js
4503599627370495.5 * 2 / 3
3002399751580330.5
4503599627370495.5 * (2 / 3)
3002399751580330
```
So it's unsafe for a formatter to change the parentheses in the proposed way. If you need the parentheses around `2 / 3`, you should add them manually.
