### ISSUE TITLE
Typescript parser doesn't support `type A = typeof B<C>;`

### ISSUE THREAD

**Issue by Tiedye** [prettier/prettier#12928]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgHEEtUwAeAFQD5DgAdKQwgB0wjaUOoG5mAX2bMYATzZFchALytC4yRGzzSUclTqs+IADQguMVNADOyULkycA7gAVLCMylwAba7jFn9AI0z4A1nAwAMq4ALZwADLocMh4LiZwPn5ggSFs+OgA5sgwmACuSSBwYd5wACblFZG4UFn5uFlwAGIQmGG4MEZ1yCC4+TAQeiAAFjBhLgDqI6jwJhkEwY6zqABus2K9YCZeaFCJmDC2flkdca6J+gBWJgAewdkucACK+RDw5wlFGZgHvYpwExgTCoNgwYYcdAwSaocowEbIAAcAAZ9BwIIlJn42L0OICsKtYvoAI5veDHLhOPomAC06gqFWGmDgpNQzOOjTOSHilxAiTCqFyBSKJkeLzJsW5FyKMFw3hhcIRSAATPo8rhUC5sgBhCBhLnFEwAVmG+US1DlTh5RVWhQAklAqrBgsDQTAAIKO4LiJ6fRKCQRAA)

```sh
--parser typescript
```

**Input:**

```tsx
interface Generic<T> {
  prop: T;
}

type a =   typeof   Generic<T>  ;
```

**Output:**

```tsx
SyntaxError: ';' expected. (5:28)
  3 | }
  4 |
> 5 | type a =   typeof   Generic<T>  ;
    |                            ^
```

**Expected behavior:**
To not error, this is valid ts in 4.7.2 at least

**Comment by alexander-akait** [comment]
Fixed in master, but not release yet

**Comment by sosukesuzuki** [comment]
duplicated to https://github.com/prettier/prettier/issues/12640
