### ISSUE TITLE
Inconsistent handling of missing lines in a JSON file

### ISSUE THREAD

**Issue by MarrickLip** [prettier/prettier#12935]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEmPbSGACwEsBnfJTdLbHGvEMizARgBpda96cQBDZgCYOPTg3ikYzAMxjanAL6cMCkGxAQADjGLRSyUHwBORiAHcACsYT6UfADZm+AT33qARkb5gA1nBgAynwAtnAAMsRQcMgAZg6kcB5evv4Bmt6RAObIMEYArokgcMHucAAmZeVhfFCZeXyZcABiEEbBfDA6tcj8eTAQaiCEMMH2AOokEulgcAE2xDoAbgvOPWCkboxQCUYwFl6Z7bHxhQBWpAAeAVn2cACKeRDwx-YJ6ulGOz3n0IOaRpEYGNiGUiMgABwABnepgSYy8mh6-zgO0W0XUAEdHvB9lpbPxSABaKLlcqDIxwLHECn7BpHJBxV6FBLBYg5fLMm73bHRBkndQwPjuYGgwjIYQELzEexZADCEGC9KKpAArIM8gkACpC2yMt4gRYFACSUEqsACYAB2gAgqaAjBnLcXgkFAogA)

```sh
--parser json
```

**Input:**

```jsonc
{
  
  "this": {
    
    "is": 1,
      
    "a": 2,
    
    "test": 3
      
  }
  
}
```

**Output:**

```jsonc
{
  "this": {
    "is": 1,

    "a": 2,

    "test": 3
  }
}

```

**Expected behavior:**
Presumably all blank lines in a JSON file should be removed? To me this output feels inconsistent i.e. I'd expect either all blank lines to be removed or no blank lines to be removed, not only the ones between brackets.

**Comment by alexander-akait** [comment]
Please read https://prettier.io/docs/en/rationale.html#empty-lines, thank you
