### ISSUE TITLE
Breaks on create<A extends typeof Base<T>>(this: A) : InstanceType<A>

### ISSUE THREAD

**Issue by cpakken** [prettier/prettier#12953]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgEJZwA8AKgHw7AC+AOlHQJaxwBOAZumHDgMoQC2cAKIAPeFEwNoAYQzZSFYHRw4wLOOnhEAgjjhiEAE1wwAngAc4ENvkIKyAChgALBpiQ5tAShweAkhIw6FBcJBbE2mR0VCAANCAQ5jBSEsig6CwsEADuAAoZCJjIIOio2eimRfEARiycANZwMDzoggAyTHDIHKiYcDV1YI3N5pxMAObIMCwArv0gcPzVcIaGK23B4zPo43AAYhAs-JrJUJMo6DMwEHEgzjD8qADqrvCYo1w8hQzJAG4-pmKYGwtyYfRYMFydXGx26pT68QAVpgRDwJqg4ABFGYQeBw3rzUYscHFaroZaoW7mFhMGBPBiGFzIAAcAAZ4tSIH0nnVzMVqXBwb8uvEAI44+BQxJFC6YAC0UDgKxWt3U4oY6ihO1hSB6CJAfX4DCms3mkjOGOxuK6uvh8yC1XpjOcyAATPFpugGKgJtIBDqFpgAKy3GZ9EjkmV6+a-OYBNawHhqBhJbRQQw8MwY-F9KhUIA)

```sh
--parser babel
```

**Input:**

```jsx
class Base<T> {}

interface SomeExtensionClass<T> {
  create<A extends typeof Base<T>>(this: A) : InstanceType<A>
}
```

**Output:**

```jsx
SyntaxError: Unexpected token, expected "," (4:12)
  2 |
  3 | interface SomeExtensionClass<T> {
> 4 |   create<A extends typeof Base<T>>(this: A) : InstanceType<A>
    |            ^
  5 | }
```

**Expected behavior:**
This is valid typescript should be able to format

**Comment by Josh-Cena** [comment]
Instantiation expressions are parsed correctly in the next version, not published yet

**Comment by sosukesuzuki** [comment]
Duplicates to #12640
