### ISSUE TITLE
prettier does not format string literals with a language comment

### ISSUE THREAD

**Issue by jaxramus** [prettier/prettier#12957]
I am using https://github.com/0x00000001A/es6-string-html for syntax highlighting string literals of other languages

For example, let's say I have this:

    render() {
        return html`<div><h1>Hello</h1><p>I love coding.</p></div>`
    }

Prettier correctly formats it to this:

    render() {
        return html`<div>
            <h1>Hello</h1>
            <p>I love coding.</p>
        </div>`;
    }

Now let's say I have this:

    render() {
        return /*html*/`<div><h1>Hello</h1><p>I love coding.</p></div>`
    }

Prettier does not format it whatsoever. Notice how instead of `html` I am using `/*html*/` because I am not using `lit-html`, but I still want to have syntax highlighting and formatting for html string literals.

How can I get prettier to format it correctly?

**Comment by fisker** [comment]
Uppercase the comment.

https://github.com/prettier/prettier/blob/feb6b519ee0e23eeb272227825ad84ecf1af05ab/src/language-js/embed.js#L289
