### ISSUE TITLE
Prettier parses `({ methodName() })` incorrectly

### ISSUE THREAD

**Issue by zsakowitz** [prettier/prettier#12963]
**Prettier 2.6.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYACAtnGALCAEwDkBDHVASgwF9KQAaECABxgEtoBnZUUgJ34QA7gAUBCHilIAbYaQCePJgCN+pMAGtcAZXJwAMuyhxkAM1lc4q9Vt0sNxgObIY-AK7WQcLCriFCfwNSKCd3Uic4ADEIfixSGA5Q5BBSdxgIRhA8GCwZAHU8dnguBzA4HUli9gA3YoUUsC5lEGMrfhhRdSd480svACsuAA8dZxk4AEV3CHg+mSsmB352lJgFFjguMH52NiyWXdh89kJ8ZAAOAAYloSt89RYUw624fhrTJgBHGfgu1ikqS4AFoTP5-Fl+HAfuwoV0Ir0kBYFl4rFh2K4PKjxlNfqYkf0mDBSCoTmc8MgAExE9TsGTOADCECwiO8XAArFl3FYACokqTIxYgGqeACSUECsB0Oz2MAAghKdOsJvMrDQaEA)

```sh
--parser typescript
```

**Input:**

```tsx
({ methodName() })
```

**Output:**

```tsx
({ methodName(); });

```

**Expected behavior:**
The code inputted is invalid and shouldn't be parsed. Prettier recognizes this as an object because it can be turned into a multiline object and Prettier still has invalid output.

**Prettier 2.6.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYAdKACbBbOGACwgBMA5AQwNQEosBfWkAGhAgAcYBLaAZ2ShKAJ2EQA7gAURCASkoAbcZQCeAtgCNhlMAGtCAZWpwAMtyhxkAM0V84m7XsMcd5gObIYwgK72QcPA04UlJgk0ooN29KNzgAMQhhPEoYHkjkEEpvGAhWECIYPAUAdSJueD4XMDgDWXLuADdylQywPnUQczthGEltN2TrWz8AKz4ADwN3BTgARW8IeCGFOzYXYW6MmBUOOD4wYW4uPI5D2GLuUmJkAA4ABjWxO2LtDgzTvbhhBss2AEcFvA+pw5Jk+ABaCzBYJ5YRwAHcOF9GKDJA2FZ+Ox4bieHyY6ZzQGWNHDNgwSgaC5XIjIABMZO03AU7gAwhA8Kj-HwAKx5bx2AAqFLk6NWIAavgAklBQrADAcjjAAIIygzbGbLOwMBhAA)

```sh
--parser typescript
```

**Input:**

```tsx
({
  methodName()
})
```

**Output:**

```tsx
({
  methodName();,
});

```

**Comment by zsakowitz** [comment]
By the way, testing shows that this doesn't happen with the `babel`, `babel-ts`, `babel-flow`, `acorn`, `espree`, or `meriyah` parsers, so it could be an upstream bug with TypeScript's parser. This might be because of TypeScript's function overloading not working properly in object literals, but I'm not sure.

**Comment by rotu** [comment]
I think that the typescript parser properly rejects this as malformed, but the typescript-eslint parser emits a `TSEmptyBodyFunctionExpression` AST node.

Related issue: https://github.com/prettier/prettier/issues/8416
