### ISSUE TITLE
Colon/declaration groups alignment is not preserved

### ISSUE THREAD

**Issue by Lippiece** [prettier/prettier#12961]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdGkoGcYAIoCGAtnADIEBGcANrnfQ-QLy4AmEYAribAHRgAnOAXgBRanB4wAFKhDVKNOQEoA3KijpG+YmUXVe8AB4wAwtHixcLOQCEIEANa4YASxgSkc9ZozQcOiQAklAADpx42tos7FxS-EIicOKSCDJyrmERKj5ajITBWTC8BXBR1rhypd4aeQylIeHFoQpgcAAWENSscAIVcgDK7b3UHM4AEl0kWDW+2g1FvEIAjpyuQqwMLDACnHA+IAA0IBChbv7IoAQCAhAA7gAK1whYyCAEAG4QrqxHIBQCAhgRxwGADXSkTJwZAAMwI1CwcGOAKBILBoSBmQA5sgdntjpIqKweqxyFAsZwCFi4AAxCACIgiNzkt4QGEwv7tGBEagAdXa7jgWAxbQGL3crg+7gAnm8cAJXGAYH9MoiBDAHoCsYzYfDEccAFZYIwDbESACKnAg8F1CKRIAxAjVbwo+j+oQVsF5Pxg7WQAA4AAzHD0QRG8wGhN7wu4EaWvY6ra1wTWnV4oD1C3ofaHHFZrISaqk6pBwu3HRFEVy43b2rBmuCW5O2-UgGCUb2sX3IABMxx2BFc1Gx5iIJfe1Gof04iIAKpR03j7R89iEerABoJXGcAIJQVgDGDSiQtuAAXzPQA)

```sh
--parser babel
--use-tabs
--quote-props preserve
--arrow-parens avoid
--trailing-comma all
--prose-wrap always
--html-whitespace-sensitivity strict
--embedded-language-formatting off
```

**Input:**

```jsx
	const nameLabel             = document.createElement("label");
	      nameLabel.textContent = "Book title:";
	const nameInput             = document.createElement("input");
	      nameInput.name        = "name";
	      nameInput.placeholder = "Sherlock Holmes";
	      nameInput.required    = true;

```

**Output:**

```jsx
const nameLabel = document.createElement("label");
nameLabel.textContent = "Book title:";
const nameInput = document.createElement("input");
nameInput.name = "name";
nameInput.placeholder = "Sherlock Holmes";
nameInput.required = true;

```

**Expected behavior:**
To the alignment to be preserved.

Thank you.

**Comment by alexander-akait** [comment]
Sorry, we don't support aligiment as you expected, and don't want to support them

**Comment by kachkaev** [comment]
👋 @Lippiece! Please see https://github.com/prettier/prettier/issues/5770#issuecomment-455774699 for context
