### ISSUE TITLE
JSX block spacing suggestion

### ISSUE THREAD

**Issue by sean-shirazi** [prettier/prettier#1297]
Not sure if this is intentional but the alignment and spacing seem a bit odd here:

```jsx
return (
  <div className="app">
    {!cookieConsent.accepted &&
      !cookieConsent.optedOut &&
      location.pathname !== '/cookie-law' &&
      <CookieConsent i18n={i18n} onAccept={this.props.acceptCookies} />}
  </div>
);
```

Wouldn't this be better:
```jsx
return (
  <div className="app">
    {
      !cookieConsent.accepted &&
      !cookieConsent.optedOut &&
      location.pathname !== '/cookie-law' &&
      <CookieConsent i18n={i18n} onAccept={this.props.acceptCookies} />
    }
  </div>
);
```

**Comment by tsemerad** [comment]
Yeah I came here to post the same issue. Was the current behavior intentional, or just overlooked? I haven't seen JSX formatted quite like that. I'm also fine with the following:

```javascript
return (
  <div className="app">
    {!cookieConsent.accepted &&
      !cookieConsent.optedOut &&
      location.pathname !== '/cookie-law' &&
      <CookieConsent i18n={i18n} onAccept={this.props.acceptCookies} />
    }
  </div>
);
```

**Comment by milesj** [comment]
This is even better.

```js
return (
  <div className="app">
    {(
      !cookieConsent.accepted &&
      !cookieConsent.optedOut &&
      location.pathname !== '/cookie-law'
    ) && (
      <CookieConsent i18n={i18n} onAccept={this.props.acceptCookies} />
    )}
  </div>
);
```

**Comment by sean-shirazi** [comment]
@milesj I like that. But what about this one:

```js
return (
  <div className="app">
    {
      aaaaaaaaaaaaa &&
      bbbbbbbbbbbb &&
      <div>x</div> ||
      ccccccccccccc &&
      dddddddddddd &&
      <div>y</div>
    }
  </div>
);
```

it would get a little bit dirty:
```js
return (
  <div className="app">
    {(
      aaaaaaaaaaaaa &&
      bbbbbbbbbbbb
    ) && (
      <div>x</div>
    ) || (
      ccccccccccccc &&
      dddddddddddd
    ) && (
      <div>y</div>
    )}
  </div>
);
```

**Comment by milesj** [comment]
@sean-shirazi Agreed. In those use cases, I set the components to a variable using standard if conditions outside of JSX. A bit cleaner in my opinion.

**Comment by sean-shirazi** [comment]
Absolutely. Extracting that into a variable outside the jsx block would be the most reasonable option. But if the programmer didn't do that (perhaps because they're as lazy as I am) then prettier could help and produce the cleanest version of that code.

**Comment by vjeux** [comment]
Hey, thanks for raising this issue, the output is not ideal ideal since there's a weird 1 space indent effect but I'd rather not add an entire new line as it's a very common pattern.

For the `}` being on the same line, I want to fix it but it's not easy given the way the printer works. See https://github.com/prettier/prettier/issues/765 for some context.

I'm going to close that issue since we're not going to change it.
