### ISSUE TITLE
Any expressions above `use strict` wraps it in parens

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#1298]
https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20something%20%3D%20true%3B%5Cn%5Cn'use%20strict'%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

It probably makes `'use strict'` not work, it means that when I remove the expression above, I also have to manually fix the parens prettier adds.

EDIT: This only happens with the babylon parser, the flow parser leaves it alone.

**Comment by bakkot** [comment]
> It probably makes 'use strict' not work

`"use strict"` won't work in that position regardless of the parentheses; it has to be the first thing in a script or function body.

I'm guessing it's parentheses specifically so it *doesn't* work, which is unnecessary. OTOH, maybe it's a good idea to keep them, so it's more obvious that it's not doing anything in that position.

**Comment by SimenB** [comment]
I know it doesn't work, but in parens at the top it doesn't work either. Using flow parser leaves it alone, while babylon breaks it

**Comment by bakkot** [comment]
There's definitely an inconsistency here, yes. I'm just suggesting that it's maybe a good idea to have the Babylon behavior instead of the Flow behavior, so that it's more obvious to readers that it isn't doing anything.

**Comment by SimenB** [comment]
Fair point! My vote goes to "don't touch literal expressions without good reason", but I can get behind encouraging correct usage (as in highlighting wrong usage) as well 😄

**Comment by existentialism** [comment]
Some history: https://github.com/prettier/prettier/pull/602, should be able to enable Flow now?

**Comment by vjeux** [comment]
I think that we should just add parenthesis when it's the first statement and was parenthesis-ed in the first place. So two action items here:

- Make sure we only do this parenthesis detection for the first element.
- Use the new `directive` flag from Flow to enable this behavior for flow as well.

**Comment by vjeux** [comment]
If you are interested in fixing this, please send a PR. I'm going to close this as I'm going through the list of issues and trying to clean them up. This one seems like something that people are not going to hit in practice, so while it would be nice to get it fixed, it's okay if it isn't.
