### ISSUE TITLE
prettier-ignore on sequence items creates invalid YAML

### ISSUE THREAD

**Issue by perlpunk** [prettier/prettier#12983]
I'm not sure if I should report this here or at https://github.com/eemeli/yaml
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEkB0oGIAEADgE5wwwCWcxAtBQOZQSk435YgCGHr7IARjyhsOYDiAA0ICIUrQAzslCdixCAHcACioSKUnADbrOAT0VT+xTmADWZAMqcAtnAAyFKHGSpD8uBatbB0JrD3pkGGIAV38QOCd+OAATJOTXTih6KM56OAAxZidOcjDkLiiYCEkQAAsYJwMAdRqKeHkQsDh7XVaKADdWkzKweXMQDz9iGE0reiLvX1iAK3kAD3swgzgARSiIeAWDPykQ4kmyk2cDapIPGEaKJJga5AAOAAYTtT9Gq0IywzGMzVACOe3gMxkei48honmSyWqpDBFFIMxy8yQPiOsT8TgoEWiuM2O3BXiQkRiUhgnH4DyeLyQACZqVYKAYwgBhCBOTFxeQAVmqUT8ABVaXpsccQH0YgBJKCpWD2MDECiyACCivsMBMW0O0pWqwAQoE7DBHC53J4DXAAL52oA)

```sh
--parser yaml
--single-quote
--prose-wrap always
```

**Input:**

```yaml
foo:
# prettier-ignore
- "a"
- "b"
- "c"
```

**Output:**

```yaml
foo:
  # prettier-ignore
  - "a"
- "b"
- "c"

```
which is invalid YAML.

**Expected behavior:**
```yaml
foo:
# prettier-ignore
- "a"
- "b"
- "c"

```

**Comment by alexander-akait** [comment]
Duplicate of https://github.com/prettier/prettier/issues/9327

**Comment by alexander-akait** [comment]
The root of the problem is the same, we don't respect `# prettier-ignore` in sequence items
