### ISSUE TITLE
prettier is throwing error `SyntaxError: '(' expected.` in valid ts code.

### ISSUE THREAD

**Issue by imranbarbhuiya** [prettier/prettier#13009]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFsBDAazgGEJSsoEYi8BePACkgemaKR4AgmBgBLaACUIAdwA8AWThEi5AOZwR4qbLq8msAHwBtALoBKdoYA6UazB6N+AOgoZO3S20PDREqNIyAEIArmIANgAmcNiKyqoaWv6Bek6woRHR2IbOAGbY9J7mANwgADQgEBjaxMig5NgFMgAKDQhEyCDk4TLkAJ4dFQBG2ORg1DAAyuSkcAAyYkzIud1EcMOj43BTGGOLasgw2CHrqKRDcJHRkXPkUGoh6nAAYjgUMOL3neQhMBDlIAAFjBSOEAOqAsTwIi7MBwSbtKFiABuUL6nTAKgBizWuGaozUFGWq1OACsiGhJvtwnAAIohCDwYnhNYVXbYXGdGB9DDKMDYMTVAEYAWwMFiSIwQHIAAcAAY2QU1mDRhhOiLlDFkXAAQBHBnwfFVDoochEAC0TEulwB2Dg+rEdvx6iJSBWLNOa1IYkOx091LpBp1bpJFRg5CG4sl0qQACYw6MIvs9K7UEQAKwAkJrAAqEZN7tZIGRJwAklBorBJvzBTAhBXJtyacy1gBfVtAA)

```sh
--parser typescript
```

**Input:**

```tsx
export const makeComponents = (components: ActionRow<MessageActionRowComponent>[]) =>
	components.map((c) => ActionRowBuilder<MessageActionRowComponentBuilder>.from(c));
```

**Output:**

```tsx
SyntaxError: '(' expected. (2:74)
  1 | export const makeComponents = (components: ActionRow<MessageActionRowComponent>[]) =>
> 2 | 	components.map((c) => ActionRowBuilder<MessageActionRowComponentBuilder>.from(c));
    | 	                                                                        ^
```

**Expected behavior:**
It shouldn't throw as it's a valid code.

**Comment by rotu** [comment]
I think the behavior is correct here and the code is actually not valid. The *type* differs with the generic parameter, but the *class* is independent of the type parameter. I think this actually should just be `ActionRowBuilder.from(c)`.

[The docs put it thusly](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-classes):

> As we cover in [our section on classes](https://www.typescriptlang.org/docs/handbook/2/classes.html), a class has two sides to its type: the static side and the instance side. Generic classes are only generic over their instance side rather than their static side, so when working with classes, static members can not use the class’s type parameter.

[and here too](https://www.typescriptlang.org/docs/handbook/2/classes.html#type-parameters-in-static-members):

> Remember that types are always fully erased! At runtime, there’s only one Box.defaultValue property slot. This means that setting Box<string>.defaultValue (if that were possible) would also change Box<number>.defaultValue - not good. The static members of a generic class can never refer to the class’s type parameters.

**Comment by sosukesuzuki** [comment]
Prettier 2.7 resolved this problem

**Prettier 2.7.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFsBDAazgGEJSsoEYi8BePACkgemaKR4AgmBgBLaACUIAdwA8AWThEi5AOZwR4qbLq8msAHwBtALoBKdoYA6UazB6N+AOgoZO3S20PDREqNIyAEIArmIANgAmcNiKyqoaWv6Bek6woRHR2IbOAGbY9J7mANwgADQgEBjaxMig5NgFMgAKDQhEyCDk4TLkAJ4dFQBG2ORg1DAAyuSkcAAyYkzIud1EcMOj43BTGGOLasgw2CHrqKRDcJHRkXPkUGoh6nAAYjgUMOL3neQhMBDlIAAFjBSOEAOqAsTwIi7MBwSbtKFiABuUL6nTAKgBizWuGaozUFGWq1OACsiGhJvtwnAAIohCDwYnhNYVXbYXGdGB9DDKMDYMTVAEYAWwMFiSIwQHIAAcAAY2QU1mDRhhOiLlDFkXAAQBHBnwfFVDoochEAC0TEulwB2Dg+rEdvx6iJSBWLNOa1IYkOx091LpBp1bpJFRg5CG4sl0qQACYw6MIvs9K7UEQAKwAkJrAAqEZN7tZIGRJwAklBorBJvzBTAhBXJtyacy1gBfVtAA)

```sh
--parser typescript
```

**Input:**

```tsx
export const makeComponents = (components: ActionRow<MessageActionRowComponent>[]) =>
	components.map((c) => ActionRowBuilder<MessageActionRowComponentBuilder>.from(c));
```

**Output:**

```tsx
export const makeComponents = (
  components: ActionRow<MessageActionRowComponent>[]
) =>
  components.map((c) =>
    ActionRowBuilder<MessageActionRowComponentBuilder>.from(c)
  );

```
