### ISSUE TITLE
Flow generic has weird break

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#1301]
https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20default%20class%20AddAssetHtmlPlugin%20%7B%5Cn%20%20apply(compiler%3A%20WebpackCompilerType)%20%7B%5Cn%20%20%20%20compiler.plugin('compilation'%2C%20(compilation%3A%20WebpackCompilationType)%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20compilation.plugin('html-webpack-plugin-before-html-generation'%2C%20(htmlPluginData%3A%20Object%2C%20callback%3A%20Callback%3Cany%3E)%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20addAllAssetsToCompilation(this.assets%2C%20compilation%2C%20htmlPluginData%2C%20callback)%3B%5Cn%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

I'd expect it to move the whole callback to a new line, not break on the generic:

```js
(bah: Func<
any
>) =>
```

**Comment by vjeux** [comment]
Thanks! It's been an issue since the early days and we now have the proper infrastructure to fix it :) https://github.com/prettier/prettier/pull/1305
