### ISSUE TITLE
API function to auto-fix files directly

### ISSUE THREAD

**Issue by bombillazo** [prettier/prettier#13012]
**Environments:**

- Prettier Version: 2.6.2
- Running Prettier via: API
- Runtime:  Node.js v16
- Operating System: all

**Steps to reproduce:**

N/A

**Expected behavior:**

Have some API function like `prettier.formatFile()` or overloading `prettier.format()` to which you can pass a file path or pattern and prettier can check/format directly.

**Actual behavior:**

No API function exists regarding format checking or fixing files directly.

**Comment by kachkaev** [comment]
AFAIU, this is not supported to keep Prettier core independent from `fs`. What difficulties do you face while reading and writing files outside Prettier?

**Comment by bombillazo** [comment]
Hey @kachkaev ! It is more a matter of utility and dev speed. I was using the ESLint API to programmatically lint files and wanted to do the same with Prettier without having to scaffold logic around Prettier to do something the Prettier CLI does already out of the box.
