### ISSUE TITLE
Opening bracket wrap to next line conflicts with tslint rule

### ISSUE THREAD

**Issue by mohit61** [prettier/prettier#13039]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wENzyAjamsOugEyYYGsAbAKzZY4DNuuLIrw4QAlg0FEGA0tIHc2vOQ2XDpeALx5gAHSh48UUgFs4SPLpDwSV-QF8QAGhAQMMMdCLJQpbNggAdwAFPwRvFFI2QNIAT28XSmxSMBY4GABlUzgAGTEoOGRlNiI4ROTU9IyMFPyAc2QYbABXMtQTSjgmLpzSKDrm0jq4ADEcE1IYD37kEFJmmAhnEAALGBM2AHUVsRsasDgM8N2xADdd2NmwIgSQfNLcYOS6iaKo0pcOIjQM+rY4ACKzQg8DeJTaNWwD1mlFInTYyww2HyME2EhgK2QAA4AAwuJEQUqbZIYWZIuAPU6FFwAR2B8CebgicyIAFoCl0ustsHA6WIeU8hq8kMUPiBSiYxI0Wm0iH9AfTCiL3m0YHC0QwMcgAEwuJqkMRseoAYQgJmFqCIAFZls1SgAVOERUVtU6tACSUAYCEyYGR7gAgl6MjBYv8waV7PYgA)

```sh
--parser babel
```

**Input:**

```jsx
export const aaaaabbbbbbcccccddddkljlkjflkjlksfjoidjlksdlkjasdlkjlklfasdfasfsd = {
  name: "test"
}
```

**Output:**

```jsx
export const aaaaabbbbbbcccccddddkljlkjflkjlksfjoidjlksdlkjasdlkjlklfasdfasfsd =
  {
    name: "test",
  };

```

**Expected behavior:**
I don't prettier to wrap the opening bracket to next line, I have a tslint rule that which conflicts with this behaviour, is there any config of prettier that I can use to avoid wrapping?

```
export const aaaaabbbbbbcccccddddkljlkjflkjlksfjoidjlksdlkjasdlkjlklfasdfasfsd = {
  name: "test"
}
```

**Comment by bakkot** [comment]
> I have a tslint rule that which conflicts with this behaviour, is there any config of prettier that I can use to avoid wrapping?

No, there isn't. You should generally disable formatting rules from other linters when using prettier; see [the docs](https://prettier.io/docs/en/integrating-with-linters.html).
