### ISSUE TITLE
Semicolon [ASI?] being added and short circuiting code

### ISSUE THREAD

**Issue by ian-weir** [prettier/prettier#13038]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB9AZgVymAcgQwFs4kACACgCc4BHAGlOoGcGo4APGASlIF4A+UsAA6UUozgxMlMWwDupAAqUIhAJZM45ANxU4TCABsAbnACChww2oArOGBgXDPAUNHjxAEwgBlVZIALNSgAc3Iud1IAXwioKJA6EAgABxg1aCZkUHxKFTlFHIRMlHxjCDVPBJAAI0p8MABrSR8iOAAZYLhkdHxDTUTa+qaYH2T64JDkGEpMOES4Qmq4T09ltvxQzHwQuAAxCEpCfBg00OQQfEwYCCqAmEJDAHUg+CYxsDgfIrU04x+AT3OYCYmUSwU0lBgym2R26vX6IBsTHYPgmhjgAEVMBB4HC+nMQGNKBDztV8EtDFVkipNI86slztT9HBKKYqjRsfBlClihcmABaNjLZZVagctTUaEhWFIHr4xKadR4hFMNGYzldJDTWaJGDkx4VGABZAAFl1dTUhgmAGFVDKQFBoF1EphNAAVcnFOUI4yzACSUFWsB8YEoalSZkDPhg-3RyoJ1OCMANniNyAAjAAGTNRKJAA)

```sh
--parser babel
--print-width 100
--tab-width 4
--no-semi
--single-quote
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```jsx
_funcName: (req, res, next) => {
  return new Promise(;(resolveAll, rejectAll) => {
    doSomething()
  })
}
```

**Output:**

```jsx
SyntaxError: Unexpected token (2:22)
  1 | _funcName: (req, res, next) => {
> 2 |   return new Promise(;(resolveAll, rejectAll) => {
    |                      ^
  3 |     doSomething()
  4 |   })
  5 | }
```

This is a little misleading as I can't reproduce it in the playground. Essentially there's a part of my code that looks like the block but without a semicolon. If you add a leading semicolon like the example, save (using editor.formatOnSave:true and editor.formatOnSaveMode:modifications in vscode), remove the semicolon and save again the semicolon gets added back in forcing broken code. One of my teammates said he edited an unrelated line and the semi-colon was added but I cannot replicate the behaviour that way.

Not sure if this is related to https://prettier.io/docs/en/rationale.html#semicolons but it feels like it shouldn't introduce breaking code.

**Comment by sosukesuzuki** [comment]
We can investigate your issue if you provide a repository to reproduce the problem.

**Comment by randallmeeker** [comment]
related? https://github.com/prettier/prettier/issues/12964

**Comment by fisker** [comment]
Not sure if this the same as #12964, can't reproduce, don't know what the range is

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYB9AZgVymAOQEMBbOJAAlQCc4BHAGgtoGcmo4APGASgoF4AfBWAAdKBWZwYOahI4B3CgAVqEEgEsWcVDTgsIAGwBucAIKHDTWgCs4YGBcN8hI8ZMkATCAGV10gAsNKABzVB53CgBfCKgomJAGEAgABxgNaBZkUCJqNQVlXIQslCJDBSIATyykgCNqIjAAa2kfUjgAGWC4ZCwy7TqG5taUxuCQ5BhqHDgkuBJauE9PJY6iUJwiELgAMQhqEiIYdNDkECIcGAhEkACYEkMAdSD4FlGwOB9ijXTjH8qzmAWDUQMFtNQYKotodev1ZiAbCxOD5xoY4ABFHAQeCwwwDECjajgs61IiLQw3FLUYIwR4aTwwALIAAcAAYklSINpHg0Umcqfo4NRTDc6Fj4KpUiVziwALQcJZLG60MUaWhQkIwpB9PHw7SaXH4liojHinrauFJGBkukMplIABMVoaGkM4wAwuotSB9ABWG44bQAFTJJR1+OMMwAklAVrAfGBqWkzLGfDBKmjDfCGqFPtaISyAJxJHPbACiseQAEZWaz4kA)

```sh
--parser babel
--no-semi
--range-start 89
--range-end 100
```

**Input:**

```jsx
({_funcName: (req, res, next) => {
  return new Promise((resolveAll, rejectAll) => {
    doSomething()
  })
}})
```

**Output:**

```jsx
({_funcName: (req, res, next) => {
  return new Promise((resolveAll, rejectAll) => {
    doSomething()
  })
}})
```

**Comment by ian-weir** [comment]
Could be the same? Certainly feels similar. I still haven't been able to reproduce it in the playground unfortunately

**Comment by fisker** [comment]
Closed since we can't reproduce.
