### ISSUE TITLE
So Sorry if it hurts someone, but...

### ISSUE THREAD

**Issue by Shadaab1611383** [prettier/prettier#13034]
Well I know how to create prettier config file. I don't know which option will disable this type of formatting. whenever the line of querySelector is too long then prettier formats it in 3 lines. Please somebody help me (Virtual Cop 2)
![image](https://user-images.githubusercontent.com/48765917/174833211-ac13481c-adde-400f-85c1-8ae984a90b12.png)

**Comment by lucasmendonca16** [comment]
You could add your `qbox` element in a variable for better readability:
```
const qbox = document.querySelector(`.qbox`);

qbox.style.cssText = `background-color: #227f6b; color #d8d8d8; padding 0 45px`;
```

**Comment by Shadaab1611383** [comment]
> You could add your `qbox` element in a variable for better readability:
> 
> ```
> const qbox = document.querySelector(`.qbox`);
> 
> qbox.style.cssText = `background-color: #227f6b; color #d8d8d8; padding 0 45px`;
> ```

Thanks for your comment Lucas
