### ISSUE TITLE
Removal of "unnecessary" parentheses causes difficulty understanding code.

### ISSUE THREAD

**Issue by gburtini** [prettier/prettier#1304]
As a preface, I recognize that style/format are a matter of heavy debate and Github Issues is probably not an appropriate place to air grievances with respect to these opinions. I believe this particular issue is relatively objective.

Under the current Prettier rules, code written as: 

```js
const padLength = length - (message.length % length);
```

Becomes
```js
const padLength = length - message.length % length;
```

The reason this is problematic is simple: by removing the semantically unnecessary parentheses, **we've forced a programmer reading this LOC to know the precedence order for all operations to understand it.**  This is fine for obvious operators such as `%` and `*`, but do you know the precedence of say, the bitwise operators? I believe this to be a significant harm to readability.

A solution would be that unnecessary parentheses are retained (or, actually, ideally _added_) when precedence rules effect the result. I believe the logic is relatively simple -- add parentheses around any infix operators on lines which have more than one distinct infix operator.

The [Rationale.md](../blob/master/Rationale.md) file, has this quote in it, which leads me to believe this has already been discussed, but I dug and cannot find a related issue:

> Prettier outputs the minimum number of parentheses required to ensure that the behavior of the formatted code stays unchanged. This may lead to code that feels ambiguous. If that's the case, you are encouraged to extract the ambiguous parts into variables.

For what it is worth, I am personally not particularly convinced by this 'minimum number of parentheses all the time' rule.

**Comment by vjeux** [comment]
> but do you know the precedence of say, the bitwise operators?

Note that we now always put parenthesis for bitwise operators.

**Comment by vjeux** [comment]
The Rationale document was written at the beginning of the project. We've changed our mind on this particular issue. By default we are removing all the parenthesis but are adding special cases where they make sense for understandability. See the "Parenthesis" section from the 1.0 blog post ( http://jlongster.com/prettier-1.0 )

![image](https://cloud.githubusercontent.com/assets/197597/25073258/ade7950a-2297-11e7-9665-26a1a185c83a.png)

For the example you just wrote, it may make sense to add parenthesis around %. I'm not really sure.

**Comment by vjeux** [comment]
@dodekeract has a good example in https://github.com/prettier/prettier/issues/1291#issuecomment-294325944 where we should keep parenthesis:

```js
(a === b) !== c
```

it is unclear without parenthesis how those are evaluated.

**Comment by gburtini** [comment]
I agree the nontransitivity of equality and inequality is a great demonstration of the issue... meaning my solution where we check precedence isn't good enough as those share the same precedence according to the spec.

**Comment by kirkstrobeck** [comment]
Using airbnb standard eslint settings `a => (a ? 'foo')` is valid, but `a => a ? 'foo'` triggers the [no-confusing-arrow](http://eslint.org/docs/rules/no-confusing-arrow) rule. In this case the two continuously fight each other, even with the [eslint](https://github.com/prettier/prettier-atom#usage) respect enabled.

**Comment by lydell** [comment]
@kirkstrobeck `a => (a ? 'foo')` is not valid JavaScript.

**Comment by kirkstrobeck** [comment]
Sure, i meant `a => (a ? 'foo' : 'bar')` and `a => a ? 'foo' : 'bar'`

**Comment by vjeux** [comment]
@kirkstrobeck I made an update where

```js
a => (a ? 'foo' : 'bar')
```

keeps its parenthesis but when it is expanded

```js
a =>
  a
    ?  'foo'
    : 'bar'
```

doesn't have them. The indentation makes it clear that it is an arrow function and not a comparison, but the eslint rule triggers anyway, erroneously in my opinion.

**Comment by kirkstrobeck** [comment]
Good to know. Unfortunately, I’m just a state-appointed mediator and would like to get you and eslint to the table to hash things out 👮

**Comment by vjeux** [comment]
I'm concentrating all the parenthesis related issues into https://github.com/prettier/prettier/issues/187. Going to close this one.
