### ISSUE TITLE
Change `semi` to `false` by default

### ISSUE THREAD

**Issue by rayfoss** [prettier/prettier#13059]
I used semicolons most of my life, but https://slides.com/evanyou/semicolons converted me. I now look at them as useless extra clutter. It's only really a problem in self executing functions, which are trivial to avoid.

They also make the code less i18n, as many layouts don't prioritize them specially on mobile. I code on my phone for fun, but lots of folk in India/Africa/Apac only have a good phone as their main computer, not only due to the cost, but also blackouts, lack of sim cards and the cost of powering them.

It's easy to change them, if you know how, but it slows down the people who have the hardest time programming, the ones Using StackBlitz on a big cheap Android phone. I make about a 100 sandboxes a month, I have a macro for creating the file, only for the friction #4102 and semis cause. Vite got it right, the most highly rated Dev tool in the State of Js 2022 survey.

## Related

https://github.com/vitejs/vite/blob/main/.prettierrc.json

**Comment by alexander-akait** [comment]
Sorry, we don't want to change it, it was discussed a lot before

**Comment by rayfoss** [comment]
I should have clarified that the default should only apply to JavaScript/Typescript. You discussed it before when there was no consensus. I searched thoroughly for the record of that discussion and found nothing... Care to link it?

State of Js 2022 S tier libraries:
![Screenshot_20220701-115156](https://user-images.githubusercontent.com/876076/176817153-e749bc4c-d304-47a7-9ee9-0ffdb6ccc3fe.png)


- Vite, no semis
- esbuild, no semis
- Testing Library (React), no semis
- Typescript, no semis
- Jest, semi
- Cypress, no semis
- Next.js, no semis

Typescript is strongly influenced by Rust, Go and other low level strongly typed languages.
Jest's preference for semis is not consistent with Facebook's own React.

The choice should be made by the people who use the language, not by the preferences of unrelated languages. Otherwise, **Prettier risks irrelevance** when all Js libraries choose a fork with per language defaults that match their users preferences...

**Comment by alexander-akait** [comment]
It doesn't mean anything at all, it's preference of developers these tools, not more.

> Otherwise, Prettier risks irrelevance when all Js libraries choose a fork with per language defaults that match their users preferences and what makes the most sense in that language.

I don't mean to be rude, but I've heard this many times already. 

ASI is not simple for new developers and often decrease readable, so we don't want to change it.

In your list, you select tools that do not use semi, If you make a more honest selection, you will see a different picture.

Also: typescript with semi - https://github.com/microsoft/TypeScript/blob/main/src/tsc/tsc.ts

**Comment by rayfoss** [comment]
Typescript might have changed their mind 14 days ago and that file hasn't been updated... New commits with semis are set to cause an error: https://github.com/microsoft/TypeScript/blob/f8aa570b23bd094798a98cef307038b1da9101a7/.eslintrc.json#L58

Look at the slides... In practice AST is only an issue with self executing functions, which is not a trick new developers use, and are easy and more intuitive avoid by just calling it normally.

The list of libraries I mentioned wasn't picked by me... But by the most popular JavaScript survey, that's was taken by 16,000 JavaScript/Typescript developers.

Would you at least open it for discussion if I found that 90%+ of active JavaScript only GitHub repos with a linting configuration file use single quotes with no semis?

**Comment by alexander-akait** [comment]
> Typescript might have changed their mind 14 days ago and that file hasn't been updated... New commits with semis are set to cause an error: https://github.com/microsoft/TypeScript/blob/f8aa570b23bd094798a98cef307038b1da9101a7/.eslintrc.json#L58

They disabled semi rule because adopted prettier and prettier insert semi.

> Look at the slides... In practice AST is only an issue with anonymous self-executing functions, which is not a trick new developers use, and are easy and more intuitive to avoid by just calling functions normally.

not only, example

```js
let array = [1, 2, 3]

[1, 2 ,3].map((x) => call(x))
```

And more, and more

> The list of libraries I mentioned wasn't picked by me... But by the most popular JavaScript survey, that was taken by 16,000 JavaScript/Typescript developers.

As I said before, it is a personal choice

Sorry, I don't see reasons to open it and I respect your option, but we don't change it, we have the option to change it, please use if you don't want to have semi
