### ISSUE TITLE
Additional spaces in pipe when use angular parser

### ISSUE THREAD

**Issue by splincode** [prettier/prettier#13058]
**Prettier 2.7.2**
[[Playground link](https://prettier.io/playground/#.....)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeGBXAlgWgDZZRw5gAWAhgE4wA6UABI-QFRQDmAYhJQLw0h44MemSrCIAM3oATcgE8AzvzpMRecgoV9wFasoZMA2qThY2pGAF1tAJgAMd-asMB3LNJilr-NkIDq7p4AFJTk7HAAlE5GAG7keBhw3jpi9AA+9JhYHFh48JT0SPQSufmF9KHh6ZnYALLkAA4NcAVFMBAAchgAtgBGLQrllb76AHyoAPRZ+ITEotSjdCAANCAQDTBY0ArIoFSUEC4AClQIOyjxLvI7q72hYADWQgDK5N1wADKzyBLxCnC3e5PGDPBrkMCENjIGCURKrOB9ODSaRIj5hNgYci+LiUbrkGCbdjIEDkDDtFYgCzdPB+UhYeAKMFgODPM70rAxelyYlgTQUwj-ahHUJsPE-P4AkAAKwUAA9npDBABFDAQeDivD-VZgyiC4nojDqSgUhqUQgwAIeUjIACM9m1B3+flCDWJprggpicApAEdVfBhetziSFDgiEikRTKHA-Vho8KsWKkL9NZL-t0sNDYWnFXAVWrvcmJasYORepbPMgbCXQrlIQBhCDdJMgD0AVgpGH+ABUy+cU1qQDFEgBJKAo2DPMBmjYAQXHzxgckEGv+AF810A)

```sh
# Options (if any):
--parser angular
```

**Input:**

```html
<tui-line-chart
    *ngFor="let chart of days"
    class="chart"
    [height]="200"
    [width]="getWidth(range)"
    [value]="chart | tuiFilter : filter : range | tuiMapper : toNumbers : range"
></tui-line-chart>
```

**Output:**

```html
<tui-line-chart
  *ngFor="let chart of days"
  class="chart"
  [height]="200"
  [width]="getWidth(range)"
  [value]="chart | tuiFilter: filter:range | tuiMapper: toNumbers:range"
></tui-line-chart>
```

**Expected behavior:**

I feel it's much better to read with spaces.

```
    [value]="chart | tuiFilter : filter : range | tuiMapper : toNumbers : range"
```

**Comment by sosukesuzuki** [comment]
Hmm, I don't use Angular. @fisker What do you think about this?

**Comment by splincode** [comment]
@waterplea fyi

**Comment by sosukesuzuki** [comment]
I asked a friend of mine, GDE for Angular, for his opinion. He said, "I haven't seen much discussion about the format of this syntax, and it's hard to decide". Sorry we are going to close this issue for now. But it does not mean that we as Prettier will never accept your proposal. If several similar issues are opened in the future, we can consider them again.

**Comment by waterplea** [comment]
> I asked a friend of mine, GDE for Angular, for his opinion. He said, "I haven't seen much discussion about the format of this syntax, and it's hard to decide". Sorry we are going to close this issue for now. But it does not mean that we as Prettier will never accept your proposal. If several similar issues are opened in the future, we can consider them again.

I'm a GDE for Angular too 🙂 I've asked @splincode to raise this issue when he enabled Angular as template parser for prettier in our huge open source library [Taiga UI](https://github.com/tinkoff/taiga-ui) and we all were confused by how weird it looks without spaces 🙂

**Comment by sosukesuzuki** [comment]
@waterplea Thank you. I just did not know if it was necessary. From the number of `:+1:` 's on this issue and your comment, I could see that it is at least a format that could be supported by Angular community.

**Comment by sosukesuzuki** [comment]
@waterplea Just a question:

[The official Angular documentation](https://angular.io/guide/pipes#transforming-data-with-parameters-and-chained-pipes) seems to use a style that does not insert a space between the colon and the value. (e.g. `{ amount | currency:'EUR':'Euros '}}`)

Here, Prettier would have to choose between:

1. no spaces at all (`{ amount | currency:'EUR':'Euros '}}`)
2. spaces on both the left and right side of the colon. (`{ amount | currency : 'EUR' : 'Euros '}}`)

Which is more acceptable to the Angular community?

**Comment by waterplea** [comment]
I asked my twitter followers to vote with 👍 or 👎 on this issue and it seems like spaces are winning. Overall, I think it's easier to read with spaces since these are separate entries and it makes sense for spaces to be around them.

**Comment by nseni** [comment]
@sosukesuzuki It's a shame this issue was not discussed more thoroughly. Opinions of a few Taiga UI users should not overweight all the examples in the official Angular documentation, where pipes are separated with spaces, and pipe arguments stand close to pipe names:
```
{{ (user$ | async).credit | currency:'CAD':'symbol-narrow':'4.2-2' }}
```
not
```
{{ (user$ | async).credit | currency : 'CAD' : 'symbol-narrow' : '4.2-2' }}
```

**Comment by splincode** [comment]
@nseni 

@waterplea is GDE for Angular, I think he discussed something similar and coordinated with the Google team

**Comment by waterplea** [comment]
> @nseni 
> 
> @waterplea is GDE for Angular, I think he discussed something similar and coordinated with the Google team

I did not coordinate with Google team, I asked people to vote with like/dislike on this issue on Twitter. Angular team does not use prettier as far as I know.

**Comment by pedroestabruxelles** [comment]
At the very least this should be optional since it's not even on Angular documentation. @sosukesuzuki

**Comment by sosukesuzuki** [comment]
There is a possibility to revert or improve this behavior, but we probably will not add an option for this. Please see https://prettier.io/docs/en/option-philosophy.html.

**Comment by waterplea** [comment]
It's better to continue discussion over here:
https://github.com/prettier/prettier/issues/13887
