### ISSUE TITLE
Add --suggest-parser command line flag

### ISSUE THREAD

**Issue by lassik** [prettier/prettier#13052]
The `--parser` flag tells prettier which parser to use, overriding the auto-detection mechanism.

Could you add a similar `--suggest-parser` flag? This flag would tell prettier which parser to use if auto-detection fails.

I believe we need this for editor integration. The [format-all](https://github.com/lassik/emacs-format-all-the-code) plug-in for Emacs lets people format code in unsaved temporary buffers that have no filename. But in this case the plug-in knows which programming language mode is being used in Emacs for the temporary buffer, and can pass the information to prettier.

Related issue/PR:

* https://github.com/lassik/emacs-format-all-the-code/issues/175#issuecomment-1153433796
* https://github.com/lassik/emacs-format-all-the-code/pull/190#issuecomment-1167745655

**Comment by lassik** [comment]
cc @liuyinz @venikx

**Comment by APIPLM** [comment]
Can this help a little bit https://www.emacswiki.org/emacs/magic-fallback-mode-alist?

**Comment by fisker** [comment]
```console
$ npx prettier --file-info foo.jsx
{ "ignored": false, "inferredParser": "babel" }
```

Is this what you are looking for?

(Seems we missed this flag in docs)

**Comment by lassik** [comment]
@APIPLM That won't work since it infers the mode on the Emacs side. We need to know what is inferred on the Prettier side.

@fisker Great - that solves the problem. If you're willing to add a `--suggest-parser` (feel free to use another name) that would be simpler for us, but the existing `--file-info` will also work properly.

**Comment by fisker** [comment]
I think `--file-info` is more useful for your case, it also includes `ignored` info, you may want to skip formatting if file is ignored.

**Comment by lassik** [comment]
Fair enough. Let's go with `--file-info`.
