### ISSUE TITLE
Is there a way to preserve the newlines

### ISSUE THREAD

**Issue by WorldToCode** [prettier/prettier#13050]
**Input:**

```jsx
.a {

  .b {

    .c {
      width: 100;
    }
  }
}

```

**Output:**

```jsx
.a {
  .b {
    .c {
      width: 100;
    }
  }
}

```

**Expected behavior:**

```jsx
.a {

  .b {

    .c {
      width: 100;
    }
  }
}

```
Is there a way to keep the newline, I searched all the properties, it seems that this is not set. Unless there is no way, I would turn off the rules in stylelint or ignore the formatting css file, but I want to keep the line breaks.

**Comment by alexander-akait** [comment]
Sorry, no, please read https://prettier.io/docs/en/rationale.html#empty-lines
