### ISSUE TITLE
[YAML] SyntaxError: Insufficient indentation in flow collection

### ISSUE THREAD

**Issue by splincode** [prettier/prettier#13061]
**Prettier 2.7.1**

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEUCGBbOSAEBRAJjx3gGcZSAdKa6JanHABwFcAbNgfQCc4BHFnHL0ojRkzQwAFqQC0ASwDmUCLxFixsnAHIm3CACs4YCgHoAVGRjyoii+e0MNOLbv1GTpU-MhQv5hydGACNuNCgwKSEFZVVsIM0dXjY4NFI4AMdRZhZSKXUxUPDIoQKNVwBCDDQbLOcXHQrk1PTMhMZKxSlZCUUhNuzyxtIwXgQ8iBhZYMnZclU0PoHqBAA3AoBhAEENgAk8TgARAEkAZQAVTgBpPABNXAATeXJZABJgYBxFeWkWYIA6KJoB48OAAMxwAF9IW8Pl8flI-v9eBDobDPt9fgC8mgoZCnAA5AAanAAQgAlLYEva4d4YhFIuCrBAwf5QFgYYJwbh4pwABS2512nAJeCJlxOF0ezxgpi6PUWQn5guFABkAPLbVVHM7naXkUwPOAYCCEgDinFOeHJADVrZw+eryXqcABmd2upw7c7HdUE06W854PlHPCkgCqZtwMG4gmo1AMEGCpAKwRY8jYD1kRpNZRw8jBtLhFV8MBqfgAFJjEQCgSCUQAaJJwFJpOCmbQASl5gxw6CwuFJ6czOBzEBwAGIcGDVDheLk4PnRHACIvE8mErG-LI6Dg-ixYCxZGxJEIYAlyHAmCn2g0FymcGgTPJoF4SmAANYQFgwAACqwIW9GAAdwRPN6jBOAYEibMr2kXAAEYAAZ417Do+0wbAcHObgAE85zgYI2xwNgIDANAOHwmceXfD9HzBSCTDgB4cBXOAgL3dIH3+Ux-mrP5TCfaxX1MXgiPSVD6i0fssNOKCWCYHACQgI1-gMUhHygFiNifKIOPvXAeL4hlgkE58RJUI11Mk5xpMw3AAFk0G4Oix1kNAmEUp5eBMVQqNnJhuVIGUlxwciSn0rjcCEl8-FMcKon-T00LEUD4I48RJHyUcZUNY1TRSjQPzgXCi0+NZ-m2PYDklS4bluHtbzsgccCHDMWKKCIpFHfL3M8jit1wKAmAwOcDxwNN2qQMcbLAXC9CEG9ewLMqcBLaAyxsUgqxMwFUnrcEm20Zo2w7btoQSKA4GYh8AG1JszWCTQAXU3A85F3fdD2PU9yAvblVh8Upb1IVQ8NkOaFtIORvOMGBVHAsR5GqPposUCBM2eUxQe4cHId4aHs3kHz4e4JACH+BCOKYVQKERoYEIIV0ABYkEZlmLxjU9FFK28wRqNhZH54RpwoiSUuqGN5AAD3pnBSECsAADEMaNMmMpwW6NcYYEHmgbMyIbagp3qZxdf1yJnIoI2oBN02xHNqAIYgDAsG4MA4Btu37cfB49ad5iflUL2fYdv39Z8V8Q9D33-dkE1ggzT3jZj2P9YWwG4GA6PQ8d2Qy2CFIc59vOC5SIjuFIYv7cgXhq9No0r3r+ox2b5wPx+G3Q9e3sZNWyXuBl-4FeMFXM25HsNEva9Ea0AzH3MuLaO-P8AKajCWrkmAFKUlS4DUjTwm03T2MKzjShwIz+NMmKLL36yaBS5rZPkxSNnmgnD60nBTjB-D36hlQM+88r4mTMsJJeH9FocTSvkDW+NFp9XkLIFg3A2C4CkDAGATAkCmFMKRcibApAQGEOzZmpgNakHQNeYhUwJDwUvqYPQhg4ZeDcjYeAigwgQLfFA6G2NqETAoDZIYfccCHAgMBKApFgQ9RNH1RSYJ9CjQSqfe289b5LxPklGBYENb0Oyk8A0M0z6MGKqVHAdJWJQFWJVHY+wdQXGuHcRqT8N4v24MySxcIKoCiFJwDUWpHHnDxKYUIkj0g8hsBNJ8H4uHfi0gNA8uAAA+GthrSz7JkyJzIkCQAwEwJOLFZBaBKQY7x5UbH-D8WqTUWxtS1VCeE4CkScCUHaaYsQAAyPsTBMnARqFMaAOBMHYNwfgsiFFiHCCsRVAkForS2ntI6Z0ripLuNwOScaIwxh+FoSQM8GlhmzKqTUgJdSGm6iafoFp3IklQFSekkaY1RC+DAKg3gsA2D4XadrMQlBUDPK3GFXCBAkCDQIVMkhMAXClLmIrHQARTBWIHkPEeytVYT2hPYCww9Fb-AoI4EAbSOmp0YAC0gKQrw4AIEhHAXSenDVGsCuaYKIWTKIdC2FsL0WIvMMiuEqLpZ4tHpink2KkXmBFWAAlpAiUiMSGIjYrZRA7wJt+d2Soz6DV6ZkjuHAei01hTTbgMKTm2PmZaa0dpyQOidCEi6j91lKogEwfC8pehCAIqDVBHsNLw3lgDRcAADTaig0AoPkP8I0qxTBXWljAYNJEOXfPuY8zpmIwqkSurCo0TBpA4AQrCzqkQvjdE9RpUZM88HX3+Pk0w5wbBfgYqYMNEb0zGTNT405KoRRiglFcx168xFKxsCxI+BEmAng9jE9IuwUTTlnPGmFVCPJCMihfAwT4kzwwwGwLa0A5RSAjWCMdsheBTqfHAf8gEz6wLlowU9WlcDaAADziUXFIFEABeAFca4AJooSAAAfHUH2F7p1YTfR+kZP6-0AtAxrGwYA2AsCNC+811Te2inFME0Jy7vBaQA4CGAe6wP214H0WWos2Di3Xjq8iXbKm2LOThgdFx8MAdlGO4jmC90KvQmIuSnjFyYdY-2vD2Ll2hSIp+eJB4HhppwGkzpGSsmBpE3kl2hSUjFLheUsT2GJONKk1xklfzGV9JwAMn4O5RBVvGZCzlMzu0WoWda5Z9q1m2Q2TgLZogdnXT2ZMA55AjmiEM-4tjknIT-oTRxUsNhBB2dkNyfQZMSCxjUabNYD7Jx9kmFhK6zESDjkgBwOGj4OAaynE8Bi04k4aWoiRDkXJuBbs-BNSYGsNi3D5OSPApwAz8wzOqKApxBG0MOAWQsOAULauScpp5zLxpvI+Syb55nOkaABUyl5IK2XJLHEgaTJSeUIu0EilFkhB7CvRWPNWoTJXStlUSrbZK2kgEpddRStL6WWZW680F4Kjv5RO2Zs7JTeWXf5ddqWd3FYPaxbF576LXsAoEw0JVKq9yKXVb6rVFHFtqf1YLE1MKylGsw5axZNq7WrKHW4pVUROsFhygxHcP5WAwoAzKIB9t5APGlBz2idyFsPKW504wxDPtICQOkIZXOfzuO-XVsEnBefCCQK8CsT6WKYdOASLYfJTi7HVOcAMNS8QuEowBnQ-xzDtOjTNp3TBbCvG0Mp6zYAXBsC9+kYpi5tBeAAHq3VuvLiQHskDPWevys6GOnU+ZHRRP3sDNKsVxrONnavOfYOV5r4RZ8VoVPlvAa8zuRcs+Ktwf4K9uekEr+rwva1v06CQp7x1ROJcqdDnr0vFVDfG9N+by3KprfnrgFR+3jvKBN9d+7z3qXpbGFYpEccALgD4mJe0gA3BrXnMKqZJ9EfZHA4Yp0QFkVbAsQkN0Pk0V4BSMisw3-5iYHRxfZsjdQ7wCsnZdF0pVMz9AtxhaE5A4dbtpUkdxV8ROkDFVpB8jcTczcLcHRx8u8fYCxZAVAhZGshYEkhd8xYheANZeB4BYBYpsw0BcIHwABWVCNbXGBAOaAoeTHBORCABQWAKfbhWKCAuEWtOsUEVEOAxgciCIFsbgnofQLhRaaMLLagEABsEAV1HhZAUAZyG5PkZycYZAEACiAZWg5QkAIoT8KCU4TCVUGwOAZAfmWjT2UwsIcwmAU4KPGwRQZAGMQQFQ40LkP2ZiVUcIRQFgRUFWbgSWawWwfQtAH8CAEwvjNgAAdSkB+CECjzgDkj8B+HkEBhgFwn0LAGhhMK2m5BgD5DCEUGqDsLFkcPUmllOA8JSAAEUWBCsaiHCVCJBK5uR9DcJMA2ATC9AOEkjBdpBkBGYkIuj9B0gkiwgmB9CoYg0TCBBCsKjXVSAYi5BisjQHgTDeABBiY4AKjFhqikB7D0gVD0gMB5AvCssrimi4BWj2jzjaiVCC5RiHhxjyZ3iwgMwPCNgXYziQAhA6CTCFxzg0BkwOjLiQBVhBBjgiNYBThRh5B80tgtJTh8iUgYS4BoQgA

```sh
# Options (if any):
--parser yml
```

**Input:**

```jsx

jobs:
  build-demo:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Build demo # for reuse in e2e jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Try rebase locally for check affected e2e
        uses: ./.github/actions/rebase

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Mark demo-app directory for persist in cache
        uses: actions/cache@v3
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Build branch demo-app
        run: npm run build:demo

  cypress:
    if: ${{ !contains(github.head_ref, 'release/') }}
    needs: [build-demo]
    runs-on: ubuntu-latest
    services:
      sorry-cypress-director:
        image: agoldis/sorry-cypress-director:2.1
        ports:
          - 1234:1234
    strategy:
      fail-fast: false
      matrix:
        specFolder:
          [
            addon-doc,
#            addon-charts,
#            addon-commerce,
#            addon-editor,
#            addon-icons,
#            addon-mobile,
#            addon-preview,
#            addon-table,
#            addon-tablebars,
#            core,
#            deep,
#            demo,
#            kit,
          ]
    name: ${{ matrix.specFolder }}
```

**Output:**

```
SyntaxError: Insufficient indentation in flow collection (63:11)
  61 |       matrix:
  62 |         specFolder:
> 63 |           [
     |           ^
> 64 |             addon-doc,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 65 | #            addon-charts,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 66 | #            addon-commerce,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 67 | #            addon-editor,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 68 | #            addon-icons,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 69 | #            addon-mobile,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 70 | #            addon-preview,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 71 | #            addon-table,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 72 | #            addon-tablebars,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 73 | #            core,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 74 | #            deep,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 75 | #            demo,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 76 | #            kit,
     | ^^^^^^^^^^^^^^^^^^^^^^
> 77 |           ]
     | ^^^^^^^^^^^^
  78 |     name: ${{ matrix.specFolder }}
  79 |     steps:
  80 |       - uses: actions/checkout@v2
```

**Expected behavior:**

github validates a job with this yml correctly

```jsx

jobs:
  build-demo:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Build demo # for reuse in e2e jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Try rebase locally for check affected e2e
        uses: ./.github/actions/rebase

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Mark demo-app directory for persist in cache
        uses: actions/cache@v3
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Build branch demo-app
        run: npm run build:demo

  cypress:
    if: ${{ !contains(github.head_ref, 'release/') }}
    needs: [build-demo]
    runs-on: ubuntu-latest
    services:
      sorry-cypress-director:
        image: agoldis/sorry-cypress-director:2.1
        ports:
          - 1234:1234
    strategy:
      fail-fast: false
      matrix:
        specFolder:
          [
            addon-doc,
#            addon-charts,
#            addon-commerce,
#            addon-editor,
#            addon-icons,
#            addon-mobile,
#            addon-preview,
#            addon-table,
#            addon-tablebars,
#            core,
#            deep,
#            demo,
#            kit,
          ]
    name: ${{ matrix.specFolder }}
```

**Comment by kachkaev** [comment]
👋 @splincode! Could you please replace the playground example with something more concise? Having minimal reproduction helps triage and fix issues.
