### ISSUE TITLE
Prettier throws `SyntaxError: Unexpected token` in valid MDX function

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#13077]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHM4YBlGAQxgEswAFbCDIvAXjxqIE8oYPAAoAlFwB8eYAB0oeAtBJ4MAGwCupesQAidGlx4B3GvTIUmNMAGsa5IntrDgKq7fIAZeiSR4mAQQBhAGl-AHEAUUo8AF9RAG45OQVCZQATfUMaEzM-VgBbbzgAOhpVVWFkhRUNLV19YvyaDGFeASE1TW1JaSrqxWJ8AG00uCIwbHoMBmgAGgH4WABdLJz8ACN1elU0gFl1VQY1OF2dAA0xRKg+6uwKdWx5WXl+6uL3zrrZm-7R8cnpvQ5j9qoRFjBvi9+jErtDRFUEkkXncYA8njcMKx2L5nq88EQiKQcXgMrRYpDoRTbnAAG5leikuC+ABsAAY8AAqPBsqkwuQwkCzEBsGbEZCgGjYVhGSx3MUoMomPhEQUgdbYNwUSg0fJwLxQODIABmZSIcCF6s1VAwVm0pGQMGw6nNqHy6zgaVGaQ8NCgpHUdjgADEcE0YAw-cgQDR1DAIKqABYwfKqADqCbMYxtYDglAQRDM9BpZj4UbABNV2jNuBYdiaxtNLoAVkQ0JQ7ao4ABFdQQeAN1RmoU27DVqP5NJoVWY7QwVMMmAJ5AADlZw9YZtTGowUcxYzg2BphqFAEde-AWGwVQqiABaA0ej2qu5n+h3WuketIE2Dl1mwoOk6f4dt256Gt+jZCrQ6zzmki7IAATFBGrbHagQQPkX6oEQACsqrqGaAAqNDrNeP5DiANLOgAklAoywJQExTDA-h0dQfCdgOZoxDEQA)

```sh
--parser mdx
```

**Input:**

```mdx
export const getStaticProps = async () => {
  const pluginsData = await getPackagesData({ packageList: PACKAGES });

  const data = await Promise.all(
    pluginsData.map(async plugin => {
      const [description, content] = await buildMultipleMDX();

      return {
        ...plugin,
        description,
        content,
      };
    })
  );

  return {
    props: {
      ssg: { data },
    },
    revalidate: 60 * 60,
  };
};
```

**Output:**

```mdx
SyntaxError: Unexpected token (2:72)
  1 | export const getStaticProps = async () => {
> 2 |   const pluginsData = await getPackagesData({ packageList: PACKAGES });
    |                                                                        ^
```

**Expected behavior:**

**Comment by kachkaev** [comment]
👋 @B2o5T! I see `--parser mdx` used for JS code in your playground example. Was this your intent or do you have `*.mdx` code that is not working?

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHM4YBlGAQxgEswAFbCDIvAXjxqIE8oYPAAoAlFwB8eYAB0oeAtBJ4MAGwCupesQAidGlx4B3GvTIUmNMAGsa5IntrDgKq7fIAZeiSR4mAQQBhAGl-AHEAUUo8AF9RAG45OQVCZQATfUMaEzM-VgBbbzgAOhpVVWFkhRUNLV19YvyaDGFeASE1TW1JaSrqxWJ8AG00uCIwbHoMBmgAGgH4WABdLJz8ACN1elU0gFl1VQY1OF2dAA0xRKg+6uwKdWx5WXl+6uL3zrrZm-7R8cnpvQ5j9qoRFjBvi9+jErtDRFUEkkXncYA8njcMKx2L5nq88EQiKQcXgMrRYpDoRTbnAAG5leikuC+ABsAAY8AAqPBsqkwuQwkCzEBsGbEZCgGjYVhGSx3MUoMomPhEQUgdbYNwUSg0fJwLxQODIABmZSIcCF6s1VAwVm0pGQMGw6nNqHy6zgaVGaQ8NCgpHUdjgADEcE0YAw-cgQDR1DAIKqABYwfKqADqCbMYxtYDglAQRDM9BpZj4UbABNV2jNuBYdiaxtNLoAVkQ0JQ7ao4ABFdQQeAN1RmoU27DVqPrGju1SqzHaGCphkwBPIAAcrOHrDNqY1GCjmLGcGwNMNQoAjr34Cw2CqFUQALQGj0e1V3c-0O610j1pAmwcus2FA6Tr-h23YXoaP6NkKtDrAuaRLsgABM0EatsdqBBA+TfqgRAAKyquoZoACqTjev5DiANLOgAklAoywJQExTDA-h0dQfCdgOZoxDEQA)

```sh
--parser babel
```

**Input:**

```jsx
export const getStaticProps = async () => {
  const pluginsData = await getPackagesData({ packageList: PACKAGES });

  const data = await Promise.all(
    pluginsData.map(async plugin => {
      const [description, content] = await buildMultipleMDX();

      return {
        ...plugin,
        description,
        content,
      };
    })
  );

  return {
    props: {
      ssg: { data },
    },
    revalidate: 60 * 60,
  };
};
```

**Output:**

```jsx
export const getStaticProps = async () => {
  const pluginsData = await getPackagesData({ packageList: PACKAGES });

  const data = await Promise.all(
    pluginsData.map(async (plugin) => {
      const [description, content] = await buildMultipleMDX();

      return {
        ...plugin,
        description,
        content,
      };
    })
  );

  return {
    props: {
      ssg: { data },
    },
    revalidate: 60 * 60,
  };
};

```

**Comment by B2o5T** [comment]
@kachkaev yes I use this code in `.mdx` file, it's a totally valid code, but prettier breaks my code.

`prettier-ignore-start`/`prettier-ignore-end` also doesn't work in mdx2, so I can't ignore this block of code, but there is already PR that fixes the issue https://github.com/prettier/prettier/pull/12208 on 1 FEBRUARY! Please give attention to MDX community 😵‍💫

**Comment by kachkaev** [comment]
My brain’s pattern matching failed me because the example has only `export const ...` 🤦 You are right – this should be a valid MDX!

Prettier does not support MDX2 yet – see umbrella issue: #12209. In the meantime, for the code to parse, it is necessary to remove newlines from your JS blocks. I know it’s annoying because the workaround is not trivial, but at least it works:

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHM4YBlGAQxgEswAFbCDIvAXjxqIE8oYPAAoAlFwB8eYAB0oeAtBJ4MAGwCupesQAidGlx4B3GvTIUmNMAGsa5IntrDgKq7fIAZeiSR4mAQQBhAGl-AHEAUUo8AF9RAG45BUJlABN9QxoTMz9WAFtvOAA6GlVVYSSFFQ0tXX0ivJoMYV4BITVNbUlpSqrFYnwAbVS4IjBsegwGaAAafvhYAF1M7PwAI3V6VVSAWXVVBjU4HZ0ADTFE+T68bAp1bHlZK+u8IreO2pne65Gxian6LNvn1CAsYF9nlUYpc+nFKglKrcYPdHt8MKx2L4ni8iERSFi8OlaLEIbDSVVbgA3Ur0IlwXwANgADHgAFR4Znk6FybkwEAzEBsabEZCgGjYVhGSy3EUoUomPhEfkgNbYNwUSg0PJwLxQODIABmpSIcAFqvVVAwVm0pGQMGw6lNqDyazgqRGqQ8NCgpHUdjgADEcI0YAwfcgQDR1DAIMqABYwPKqADqcbMoytYDglAQRDM9EpZj4EbAuOV2hNuBYdkahuNToAVkQ0JQbao4ABFdQQeB11QmgVW7CViN5VJoZXo7QwZO0mBx5AADiZg9YJuTaowEfRozg2Ep+oFAEdu-AWGwlXKiABaPVut3K24n+i3aukWtII39p0mgp2h0-m2nanvqn71gKtBrLOqTzsgABMEFqlsNqBBAeQfqgRAAKzKuoJoACo0Gsl5fgOICUo6ACSUAjLAlDjJMMD+DR1B8O2fYmjEMRAA)

```sh
--parser mdx
```

**Input:**

```mdx
export const getStaticProps = async () => {
  const pluginsData = await getPackagesData({ packageList: PACKAGES });
  const data = await Promise.all(
    pluginsData.map(async plugin => {
      const [description, content] = await buildMultipleMDX();
      return {
        ...plugin,
        description,
        content,
      };
    })
  );
  return {
    props: {
      ssg: { data },
    },
    revalidate: 60 * 60,
  };
};	
```

**Output:**

```mdx
export const getStaticProps = async () => {
  const pluginsData = await getPackagesData({ packageList: PACKAGES });
  const data = await Promise.all(
    pluginsData.map(async (plugin) => {
      const [description, content] = await buildMultipleMDX();
      return {
        ...plugin,
        description,
        content,
      };
    })
  );
  return {
    props: {
      ssg: { data },
    },
    revalidate: 60 * 60,
  };
};

```
