### ISSUE TITLE
Playground: support 'None' value

### ISSUE THREAD

**Issue by mbelsky** [prettier/prettier#13078]
Hi folks,

The `parser` default value is `None` since v1.13.0 ([docs](https://prettier.io/docs/en/options.html#parser)). If you go to https://prettier.io/playground and open `--parser` option list there is no `None` option. That means there is no way to test `prettier`'s default behavior. 

Would you like to support `None` as a valid option in this list? If yes please let me know. I'd like to work on it.

**Comment by sosukesuzuki** [comment]
I don't think we need to support it in playground.Do you have a specific use case?

**Comment by mbelsky** [comment]
Not really, I don't have a specific use case. I just want to be able to set the same values which I use in CLI.

**Comment by sosukesuzuki** [comment]
I don't think that feature is needed for Prettier Playground, so I'm closing this issue. If you find a specific use case we can revisit.
