### ISSUE TITLE
Comment after braces

### ISSUE THREAD

**Issue by MaxenceEpitech** [prettier/prettier#13083]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEA3AhgGwFc5MBeTGAJ2IG4AdKASwDNMAKPIuASk2EwD0AKiGYAyhAC2JSJOmxMuAEYRCWGAAsSLTBAAOMRtAobcWRmkxQIWANZw4euABNdUExcz5GUEkIEMmJgMAL6CIpgAKhqesvLmlvaOLm4elt6+mP6YcPhoJPzCohLSmHEIWMqq6lo5eST6hsaaZpie1nYOTq7NMek+fgHuZegQ+HAAdPgQAOZsAORa+NPz3DThotGxUvFtiV0pvZ4Zg6EgADQgjUZQaMiguJSUEADuAAqPCHcoBC+4AJ53S5KSi4MD2GBiXDSAAyA2QzAI+WBoPBcEhejBPhmyCoxEucEkShczhcMNwUBmhFwMzgADEIJRJGZDJTkCBcGoIBcQBoYJJ8AB1GLwNCYsBwMRfRiGbAy-7ssBoIEgHz5SgwN6gmbMhFIuCXABWaAAHmJseMAIqEGxwPX1S6Yyjq9lKZS5Hl6Z75QWgvTsr1wdXYO2XACONvgWv03w5aAAtL4XC4eZQ4BHGGmtTTdUhEQ6QPlJIxcdQDYWLXBrbb7ciQFRcIwMjMAMI7XDsoMAVh5hHykWU33zdewxAAklBSbAxGBKIwDABBSdiGD-ca18swZSCxjOTTIAAsjrnsB3e40yAATAAGW8hEJAA)

```sh
--parser babel
--print-width 2000
--tab-width 4
```

**Input:**

```jsx
const value = true;
if (value) { /** Some comment about the if option that is not keeped on this line */
  
} /** This comment is keeped on this line */ else { /** Some comment about the else option that is not keeped on this line */
  console.log('hello'); /** This comment is keeped on this line */
}
```

**Output:**

```jsx
const value = true;
if (value) {
    /** Some comment about the if option that is not keeped on this line */
} /** This comment is keeped on this line */ else {
    /** Some comment about the else option that is not keeped on this line */
    console.log("hello"); /** This comment is keeped on this line */
}

```

**Expected behavior:**

```jsx
const value = true;
if (value) { /** Some comment about the if option that is not keeped on this line */
} /** This comment is keeped on this line */ else { /** Some comment about the else option that is not keeped on this line */
    console.log("hello"); /** This comment is keeped on this line */
}

```

**Comment by kachkaev** [comment]
👋 @MaxenceEpitech! Why is it necessary to keep those comments on the same line as `}`?

**Comment by kachkaev** [comment]
Sorry I meant `{` in my comment – fixed. Prettier aims to format code in a consistent manner and just ‘get out of the way’. See https://prettier.io/docs/en/why-prettier.html

What objective value do you see in keeping `/**` after `{`?

**Comment by MaxenceEpitech** [comment]
The objective of keeping a comment after `{` is to describe what's done inside the else part of an 'if / else'.

```jsx
} else { // This comment tells what is done bellow inside the else
    // A comment here would explain the bellow console.log('hello2') (not the else block)
    console.log('hello2');
}
```

**Comment by kachkaev** [comment]
This works too, does not it? Importantly, there is more horizontal space for this comment, especially in the case of a [long `if`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQDc4BOAngDLQDmAwtACaoyrQAqAFgIYwByccNAzgEEyMAPLoAygAc2YOAKg0A6hACuAGxqsVfAAraWrONQC2xhDABKqcixgBKTMAA6UTG8wB6D5lao+mSFNzTHg1NX8Ad3YYTD9MGmg4TAAjODCICNioPlQaJJgWJIwXd0wS9y9MAQCIINhMQoIkiNUNTDgAD0k1NlRXAqTU9MzIbIg1OAA6NQhybAByQvT5h2woCBiB2KxkmbAAaztyt1G+camZucW0mZWAbhcAX3bwpOdXCu9ff0CzetDwpgohxYv4ElBBjcMlkcnkQoUXnw4C5jp5vNVfsFGs1WjR2l0en14ZDhjUxhNprMFksZgAmFY4dabBFpJEpPaHVGnc6Uq40iD0uwPKCPEAAGhAEEkDGgfGQoDYBAIGR0ioQcpQbDUETYRDlEuSBBk+zgMHEbDMJD6cGQ6C1SINRoOpqkMj65GQMAIKjgErgxlSNDyNBIbCg5BUbHIcAAYhACMYOAxw8gQGwVDAIOKQLZjGpFCx6HA+NJZOJ1fRULh6ERU2A+Pq0NlCDAdEbyInbfbfSAAFZ8Drid0TACKKg2NqQdteEukBCRBFTyTYQ2zkgIfRgilyBWQAA4AAyz5VIxRGySp9fFwj4bMAR3H8DbUo1ab4AFoIbxeNmmg-UE0bZRp2U7dhKSLGKgnrej2OThqOj6TtODogDAK7bjQu5ILSEper0ajuiYIEgMWACs2baHATArhqyE9rgPoAJIKOY4hgBu0ryDQ4gwEQExdq8jyPEAA):

```js
if (veryLongConditionThatNeedsALotOfSpaceAndWouldThusPushTheCommentRight) {
    // This comment tells what is done bellow inside the if
    
    // A comment here would explain the bellow console.log('hello') (not the if block)
    console.log('hello');
} else {
    // This comment tells what is done bellow inside the else

    // A comment here would explain the bellow console.log('hello2') (not the else block)
    console.log('hello2');
}
```
