### ISSUE TITLE
How to configure with JetBrains File Watcher

### ISSUE THREAD

**Issue by mikeerickson** [prettier/prettier#1308]
Hey Gang

I am trying to get Prettier to work within WebStorm as File Watcher (so it pretties when saved) but I cant seem to get it working.   I have it working fine as External Tool (invoked manually) but cant figure out configuration as file watcher.

**Comment by SimenB** [comment]
This works for me:
![image](https://cloud.githubusercontent.com/assets/1404810/25084778/af63f9a6-235e-11e7-846f-2c4074deff9e.png)

**Comment by mikeerickson** [comment]
@SimenB Thanks for supplying the tip, but unfortunately it doesn't work for me (still throws an exception).   For the time being, I am cleaning manual with keymap associated to the external tool version.

**Comment by SimenB** [comment]
What error are you getting?

**Comment by mikeerickson** [comment]
@SimenB Actually, I cleared the error log (something left over from before) and now I dont get the same error, but it doesn't actually do anything.

![image](https://cloud.githubusercontent.com/assets/183153/25093918/787a3884-2349-11e7-9254-8749266f71e7.png)

![image](https://cloud.githubusercontent.com/assets/183153/25093904/6750c578-2349-11e7-8d08-d930410a486f.png)

If I apply the external tool manually, the above code is fixed.

**Comment by SimenB** [comment]
Not `$File$Path`, use `$FilePath$`. You can click `insert macro...` to see a list of all macros

**Comment by mikeerickson** [comment]
@SimenB I just got it working...  I am sure your above "tweak" would have fixed it as well :-)

![image](https://cloud.githubusercontent.com/assets/183153/25093976/cf259b7e-2349-11e7-9106-b1f3baecb746.png)

**Comment by mikeerickson** [comment]
@SimenB Thanks for your time and effort, greatly appreciated.

**Comment by vonovak** [comment]
is prettier with file watchers also incredibly slow for you? eg. 600ms before you see the result of the formatted file?

**Comment by SimenB** [comment]
You should probably use prettier_d to avoid the startup cost of node

**Comment by vonovak** [comment]
@SimenB while prettier_d is probably somewhat better, it's still painfully slow. The problem is not with prettier but with the IDE.

**Comment by ButuzGOL** [comment]
same slow for me
