### ISSUE TITLE
Configure ignore files, from the prettier config file

### ISSUE THREAD

**Issue by sean-au** [prettier/prettier#13088]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: node.js
- Runtime: 
- Operating System: node.js
- Prettier plugins (if any): 

**Steps to reproduce:**

**Expected behavior:**

.prettierrc.json

{
  "ignoreFiles" : [ "/build/**"}
}

**Actual behavior:**

Its not possible add an ignore config to prettiers config file (based on the docs). 
The only ways seems to be to have to use a .prettierignore file.
While this is easy, its one more config file to deal with. EsLint and Sylelint both allow setting ignores in the config file.

**Comment by sosukesuzuki** [comment]
Do you have a use case you would like to write in `.prettierrc` instead of `.prettierignore`? At least for me, `.prettierignore` is enough.

**Comment by sean-pwd** [comment]
The main use case for me is when I have stylelint, eslint and markdownlint
set upalong with prettier. I can copy and paste out of their json config
files (all use a an array to set ignores).  Whereas prettier I can't reuse
the ignore config, unless I create 4x separate ignore files.

**Comment by mtqperson** [comment]
I was also looking for this after discovering ESLint's `ignorePatterns` in the config file instead of .eslintignore. It can reduce the number of configuration files, and potentially make it easier to reuse ignore patterns between ESLint and Prettier.

**Comment by sean-au** [comment]
I believe this is required to bring prettier's configuration behavior in line with ESLint and StyleLint.

**Comment by kachkaev** [comment]
I like this suggestion by @ivodolenc: https://github.com/prettier/prettier/pull/12672#issuecomment-1256947760  (`ignorePatterns` like [in ESLint](https://eslint.org/docs/latest/user-guide/configuring/ignoring-code#ignorepatterns-in-config-files))

**Comment by kevinwolfcr** [comment]
This would be super easy for sharing configuration and ignored files. @fisker any plans to implement this? It's not a breaking change and an opt-in feature.

**Comment by kachkaev** [comment]
@kevinwolfcr there exists a work-in-progress PR that aims to do something similar: https://github.com/prettier/prettier/pull/12672. https://github.com/prettier/prettier/issues/3460 is the main discussion thread for this feature request. That other issue is named a bit differently, but comments suggest to use the same approach as here. Let's close this one as duplicate to avoid repetition.
