### ISSUE TITLE
Ignore Specific Elements

### ISSUE THREAD

**Issue by benny779** [prettier/prettier#13096]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAy5u3AQQDKQgLxMQUCAFoAVgGdyNQtNx0B8oROZRy5dqQGYdevak6l8AvmwEAlIZfEgArjABm0gBzaWp-fgAkvjcpAycAJ7kMMF0pKgA9EEhYX6m5pbWAHICFs4AJnDyYABOAJYADjBl0BLkkLAIMM6RfBBZMKRQ+L66+glshsZpqABGEPkRJunEDGxwdHQQ5ADuECV0+eioAEJ2DOT4lGWKJ+QcPACs5DsQZXRwJRV0AIbwAHSJs2n+qPIAbgBzcgAD3oUHkzmoMAqSASCRWiPeKwAzO91oCEgAmAAMeISAMBdRWZXyMEozgAjAA2OqUOBlQHUKm0kDkdz3OjOMAuEolJq4CBLEp1MCveSQiSjMrkaXSGAlF7ySh1f5lOArW4g5w48i6mnkGm9MwVN6Ucj5FqXd7Xa2XAQ2m1652U8jUt3-akvR3XXX66SunEANS9Pud+vINukNoAXjQsU6cd67eHDZG7Z7k4mXQG9SGs76Xeno5c4yj0wXUzjczjM2G-UXg9SYxIEtNUKbyezOdISi4Hs44P8EBN8nVLRJOJSACxOlEvV2BnOLtiUlH-ACcLyx5B3Dcp0h3WLYl23u9TB6xh6D08oJYXaf3AYDQaxD6XEYPlLYXsXF8NAaUG+f77mmlKUGip4gUWi7-JSMacLOlKUl45DTmhaHvDilwbkGa7vlWYGUL+j4Xi+s7YRu3DIe8XheDu05sEhKEIQm1woq+lDIXBd7IS2IBtiwiSEtMZhCLgdiBMQ+CiaYJJQPkEArO8gIvOQojsi4UBgNU0DkAAFAAlOQwDkKp7wAI7vBULjKvpLwlICLg0E08jGQAvgA3GZ3oWep5AANoALreeZdD+QA1FAGrkJgbxwJ5PymKp+kAOSlHA8WpQANOQqUAKoCNIAAapWldIhA5XlLxuBAqWGaFLxpfICD5FVqWmoCQ7qis9VJYk4mSdJsmoINUn4OQ8glGAUIwDC8hwgiSKAhAECAg80gvFALx0BE1RgPI7yQDQCRbTte1lAd7wKHUwiEFkuCxaQABipD7ANEnje2CTjJMOiJBc3AMCA2UgBAVQ1BCyCgA5JRKcQDkIPIyAgDtKwvBEyOg6MipgAA1nAMBCC8LncGU0XIO4O0tdjuME0TppgOTgLIAqLhwKDcA0KMcD5IU+TcFtTkvF1z3rDQbzVFALMoDVMAQCDIDUPQADqxzwPIjNwEISNlNUaowBEKMHVjIDky1JQwMQiqAhLlPUxzIAKCCQjMw8ACKLgQPA9t0DTICmiUFso8rdCKxU5SwCrpLksgXg4qDEcQC1KuKhUKMR0UjzDorFle-A1vg8jsvyNI0W87ziv8nnZT8tbIt20gVN+47LU0GUrN9q3btwJ73twL7-swC8ozR2SlDIFioMKi89zM4KNCNyARSXIrtlwPgI-F83-v-OzgQKU0QilJUMACApQiGw8g9wO57lAA)

```sh
--parser html
```

**Input:**

```html
<!DOCTYPE html>
<HTML CLASS="no-js mY-ClAsS">
  <HEAD>
    <META CHARSET="utf-8">
    <TITLE>My tITlE</TITLE>
    <META NAME="description" content="My CoNtEnT">
  </HEAD>
  <body>
    <P>Hello world!<BR> This is HTML5 Boilerplate.</P>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg>
    <SCRIPT>
      window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
      ga('create', 'UA-XXXXX-Y', 'auto'); ga('send', 'pageview')
    </SCRIPT>
    <SCRIPT src="https://www.google-analytics.com/analytics.js" ASYNC DEFER></SCRIPT>
  </body>
</HTML>
```

**Output:**

```html
<!DOCTYPE html>
<html class="no-js mY-ClAsS">
  <head>
    <meta charset="utf-8" />
    <title>My tITlE</title>
    <meta name="description" content="My CoNtEnT" />
  </head>
  <body>
    <p>
      Hello world!<br />
      This is HTML5 Boilerplate.
    </p>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      fill="currentColor"
      class="bi bi-trash"
      viewBox="0 0 16 16"
    >
      <path
        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
      />
      <path
        fill-rule="evenodd"
        d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
      />
    </svg>
    <script>
      window.ga = function () {
        ga.q.push(arguments);
      };
      ga.q = [];
      ga.l = +new Date();
      ga("create", "UA-XXXXX-Y", "auto");
      ga("send", "pageview");
    </script>
    <script
      src="https://www.google-analytics.com/analytics.js"
      async
      defer
    ></script>
  </body>
</html>

```

**Expected behavior:**
I would be happy if there is an option to choose elements to ignore formatting.
In my case what bothers me is the element "svg".

something like: 
```json
"prettier.config": {
    "html": {
        "unformat": [ "svg" ]
    }
}
```

Source: [Beautify](https://tonylea.com/ignoring-specific-elements-in-vs-code-beautify)

**Comment by kachkaev** [comment]
👋 @benny779! Please see [Prettier Option Philosophy](https://prettier.io/docs/en/option-philosophy.html).

**Comment by benny779** [comment]
Yes, I know about this option.
But I was looking for a general definition by element types.

Thanks!

**Comment by ariStridely** [comment]
Yeah me too! How is that not possible?
