### ISSUE TITLE
TypeError exception on empty blocks inside JSX

### ISSUE THREAD

**Issue by lourd** [prettier/prettier#1309]
[Reproduction](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3CFoo%3E%5Cn%20%20%7B'hey'%7D%5Cn%20%20%7B%7D%5Cn%3C%2FFoo%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)
```
<Foo>
  {'hey'}
  {}
</Foo>
```

`TypeError: Cannot read property 'some' of undefined`

For reference, [Babel ditches the block](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=react&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code=%3CFoo%3E%0A%20%20%7B'hey'%7D%0A%20%20%7B%7D%0A%3C%2FFoo%3E&playground=true). I assume Prettier should do the same.

**Comment by vjeux** [comment]
Thanks! I had no idea this was even valid. We'll fix it :)

**Comment by lourd** [comment]
You're welcome. Yeah me neither; I removed it from our source anyway, it definitely was intentionally left. Thank you for your quick response, and really great job on the project so far!

**Comment by vjeux** [comment]
It looks like it's working on master and in the reproduction link you have. I believe it was an issue in 1.0.0 but was fixed in 1.1.0. Could you update and confirm? Thanks!

**Comment by lourd** [comment]
Yes, I believe the online playground was on 1.0.0 when I made the issue. Looks good now, cheers!
