### ISSUE TITLE
Incorrect color output when redirecting

### ISSUE THREAD

**Issue by dspinellis** [prettier/prettier#13097]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: CLI
- Runtime: Node.js v18.5.0
- Operating System: Reproduced on Windows, Linux

**Steps to reproduce:**
Case 1: Color appearing when it shouldn't
```
bin/prettier.js --check xyzzy.js 2>errors
sed -n l errors
```

**Expected behavior:**
```
[error] No files matching the pattern were found: "xyzzy.js".$
```

**Actual behavior:**
```
[\033[31merror\033[39m] No files matching the pattern were found: "xy\
zzy.js".$
```
(The file contains color-changing escape codes.)

Case 2: Color not appearing when it should
```
bin/prettier.js --check xyzzy.js >/dev/null
```

**Expected behavior:**
The word `error` in red.

**Actual behavior:**
The word `error` without color.

I am uploading a fixing PR.

**Comment by fisker** [comment]
Fixed by  #13098
