### ISSUE TITLE
Why must a blank line be generated in the last line after formatting？

### ISSUE THREAD

**Issue by wangrongding** [prettier/prettier#13106]
Why must a blank line be generated in the last line after formatting？
Are there any current options to turn it off?
playground：
https://prettier.io/playground/

![image](https://user-images.githubusercontent.com/42437658/178913358-fdf4435d-c6f0-4480-9e5e-db6debe388e6.png)

**Comment by kachkaev** [comment]
👋 @wangrongding! Please see https://github.com/prettier/prettier/issues/6360 and https://github.com/prettier/prettier/issues/13036.
