### ISSUE TITLE
Introduce `arrow-body-style` option to work-around eslint bug

### ISSUE THREAD

**Issue by devinrhode2** [prettier/prettier#13102]
Unsurprisingly, this has been asked about a few times already.

#5195
#4928
#3949
#3425

I believe this is unrelated, but mentions arrow-body-style: #165

Oddly, github.com/prettier/prettier uses both of these problematic eslint rules:
https://github.com/prettier/eslint-plugin-prettier#arrow-body-style-and-prefer-arrow-callback-issue
GH issue link: https://github.com/prettier/eslint-plugin-prettier/issues/65

I think, because of these very long-standing eslint issue, it would be nice if prettier supported some config options equivalent to these two eslint rules:
- https://eslint.org/docs/rules/arrow-body-style
- https://eslint.org/docs/rules/prefer-arrow-callback

Please don't feel bad about just closing this, it's really A-ok :)

**Comment by fisker** [comment]
This is not possible for us to fix, it should either fix on `eslint-plugin-prettier` or `eslint` side.

https://github.com/prettier/eslint-plugin-prettier/pull/379 should fix these issues, but it it will be slower.
