### ISSUE TITLE
Inconsistencies in formatting HTML

### ISSUE THREAD

**Issue by justingolden21** [prettier/prettier#13116]
My `app.html` file has `<html>` and `<head>` at the same indentation level, and when I run prettier it complains but when I format it with Prettier it reverts it.

I tried to auto generate the output at prettier.io/playground as suggested in issue template comment, but when I add HTML I get:

```
SyntaxError: Unexpected token (1:1)
> 1 | <!DOCTYPE html>
    | ^
```

And I see no area anywhere to change the language to HTML.

### dev dependencies

```json
"devDependencies": {
		"@sveltejs/adapter-netlify": "1.0.0-next.49",
		"@sveltejs/kit": "1.0.0-next.291",
		"autoprefixer": "^10.4.2",
		"eslint": "^7.22.0",
		"eslint-config-airbnb-base": "^14.2.1",
		"eslint-config-prettier": "^8.1.0",
		"eslint-plugin-import": "^2.23.4",
		"eslint-plugin-prettier": "^4.0.0",
		"eslint-plugin-svelte3": "^3.2.0",
		"postcss": "^8.4.5",
		"postcss-load-config": "^3.1.0",
		"prettier": "^2.5.1",
		"prettier-plugin-svelte": "^2.5.1",
		"pwa-asset-generator": "^4.1.1",
		"svelte": "^3.43.1",
		"svelte-preprocess": "^4.9.8"
	},
```

### .prettierrc
```json
{
	"bracketSameLine": true,
	"printWidth": 100,
	"quoteProps": "consistent",
	"singleQuote": true,
	"trailingComma": "none",
	"useTabs": true,
	"endOfLine": "crlf"
}
```

### .eslintrc.json
```json
{
	"env": {
		"browser": true,
		"es2021": true,
		"node": true
	},
	"extends": ["airbnb-base", "prettier"],
	"parserOptions": {
		"ecmaVersion": "latest",
		"sourceType": "module"
	},
	"plugins": ["prettier", "svelte3"],
	"overrides": [
		{
			"files": ["*.svelte"],
			"processor": "svelte3/svelte3"
		}
	],
	"rules": {
		"prettier/prettier": "error",
		"indent": ["warn", "tab"],
		"quotes": ["warn", "single", { "avoidEscape": true }],
		"no-unused-vars": "warn",
		"no-console": "off",
		"no-tabs": "off",
		"no-restricted-syntax": "off",
		"func-names": "off",
		"quote-props": ["error", "consistent-as-needed"],
		"guard-for-in": "off",
		"import/extensions": "off",
		"new-cap": "off",
		"import/no-extraneous-dependencies": "off",
		"no-param-reassign": "off",
		// until sveltekit gets everything figured out for $lib imports:
		"import/no-unresolved": "off",
		"radix": "off"
	}
}
```

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input / Output when formatting alt/shift+F or on save with Prettier**

```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="robots" content="index, follow" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="shortcut icon" href="/img/icons/manifest-icon-192.png" />

	<link rel="icon" type="image/png" sizes="196x196" href="/img/icons/favicon-196.png" />

	<meta name="msapplication-config" content="/browserconfig.xml" />
	<meta name="msapplication-square70x70logo" content="/img/icons/mstile-icon-128.png" />
	<meta name="msapplication-square150x150logo" content="/img/icons/mstile-icon-270.png" />
	<meta name="msapplication-square310x310logo" content="/img/icons/mstile-icon-558.png" />
	<meta name="msapplication-wide310x150logo" content="/img/icons/mstile-icon-558-270.png" />

	<link rel="apple-touch-icon" href="/img/icons/apple-icon-180.png" />

	<link rel="manifest" href="/manifest.webmanifest" />
	<link rel="stylesheet"
		href="https://fonts.googleapis.com/css2?family=Aldrich&family=Arsenal:wght@400;700&family=Bai+Jamjuree:wght@300;500;700&family=Bitter:wght@300;500;700&family=Josefin+Sans:wght@300;500;700&family=Julius+Sans+One&family=Jura:wght@300;500;700&family=K2D:wght@300;500;700&family=KoHo:wght@300;500;700&family=Libre+Baskerville:wght@400;700&family=Limelight:wght@400&family=Major+Mono+Display&family=Montserrat+Alternates:wght@300;600;900&family=Orbitron:wght@400;600;800&family=Yatra+One&family=Comfortaa:wght@300;400;500;600;700&display=swap" />
	<meta name="apple-mobile-web-app-capable" content="yes" />

	%svelte.head%

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-ABC"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());
		gtag('config', 'G-CM722NVXJ9');
	</script>
</head>

<body>
	%svelte.body%
</body>

</html>
```

**Output when running format fix**
Format fix command: `"formatfix": "prettier --ignore-path .gitignore --write ."`

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="robots" content="index, follow" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="shortcut icon" href="/img/icons/manifest-icon-192.png" />

		<link rel="icon" type="image/png" sizes="196x196" href="/img/icons/favicon-196.png" />

		<meta name="msapplication-config" content="/browserconfig.xml" />
		<meta name="msapplication-square70x70logo" content="/img/icons/mstile-icon-128.png" />
		<meta name="msapplication-square150x150logo" content="/img/icons/mstile-icon-270.png" />
		<meta name="msapplication-square310x310logo" content="/img/icons/mstile-icon-558.png" />
		<meta name="msapplication-wide310x150logo" content="/img/icons/mstile-icon-558-270.png" />

		<link rel="apple-touch-icon" href="/img/icons/apple-icon-180.png" />

		<link rel="manifest" href="/manifest.webmanifest" />
		<link
			rel="stylesheet"
			href="https://fonts.googleapis.com/css2?family=Aldrich&family=Arsenal:wght@400;700&family=Bai+Jamjuree:wght@300;500;700&family=Bitter:wght@300;500;700&family=Josefin+Sans:wght@300;500;700&family=Julius+Sans+One&family=Jura:wght@300;500;700&family=K2D:wght@300;500;700&family=KoHo:wght@300;500;700&family=Libre+Baskerville:wght@400;700&family=Limelight:wght@400&family=Major+Mono+Display&family=Montserrat+Alternates:wght@300;600;900&family=Orbitron:wght@400;600;800&family=Yatra+One&family=Comfortaa:wght@300;400;500;600;700&display=swap" />
		<meta name="apple-mobile-web-app-capable" content="yes" />

		%svelte.head%

		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-ABC"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag() {
				dataLayer.push(arguments);
			}
			gtag('js', new Date());
			gtag('config', 'G-CM722NVXJ9');
		</script>
	</head>

	<body>
		%svelte.body%
	</body>
</html>

```

**Expected behavior:**
Anything as long as it's consistent. Any time I format the code it yells at me and any time I go to fix it, it changes the indentation, but any time I format it, it changes it back. Seems like an inconsistency in Prettier. I also had one other inconsistency, but it involves ESLint so I commented there instead.

**Comment by fisker** [comment]
[Can't reproduce](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAiHMoLNnC4ATMUxioacGF3JhKXAE4BnZYJABXGADMAtAA4h5APRyFSleShcl+zRABGEGNquRYCDD6AJZQ0nAAHgA05MYQdHQQAO5Wtizyisqqzq5CAG7BcEkADhCaMH7Q8LD6ScHSMJT84QVgcKZ1DZQxocEwwVx0ptpgg3D8AIypdqh0oQDW5JpwdPralGUwYEbkwf5WlMvG+tbBNLyn-trWNDzBxnDaMKZ70KYTAJwATAB0xXzTdLiBRzKCLZarISvcQgcgwACexXGUNuvDg1n+vCs2mCAC9HvpPgA2CLEg5HE5nC7Q67GLitN7Ev4A2FpcTAzKOHLIkA0bRcYrFOajfpvfzGYJY2H+apBITWDzuJK6TTiyU-CL0QEchzZFw8vkCoV7LiiqDDACOBi0cAA7AAGCIOxK8CCVAI1eVUy7Qa58-p0drQ95fczMqU2Ga6pz6-SGwXC03BN7aK02iYAVkdmftLrd0qqgUp5x9UD9T2CgZe-lMXwd4e1GWj3Lj-ITJrNlutywAzBNHX3cxBXe7ZcXqVcbhWq8GMxmw5jG-YsjHcry28aRcnzZ04IPSVm86Oi16SzSpwGgzW5+Za-XF6y5BzQeCVvojVWYBADOpq9ByXAxynhOvrWB+V6MuY9oNo+QIZC+SxvkItxQPcjwVLChyAScKFoU8PxJHAHi4Q8TxLrMCyIZCIBPPCgbrHAyhCOkFSNBSQjUDAxTaEg1jWHEsDaD8rrDoGArBEJkA0NYYDaNoXwAPx0jQlbwvwACCdDSJoeyUAAZMpqkaToCCDEgSS8NQAACAAs9r2gA3A69oGS4RkAEJcMEADUABSLgAFYGMscDmZZMBWT29kOVmjnOa5Kl0Gp7l9PAmhhdZUWObFTn2QlRm+RAugSlA3kAMo8DxFmZdFOXxYZSX8L5BhzAY2jlZV3nYFAcD5Y1zWaFwGURVlMXRfVbmNQA0l8mDDZFtXjXlDVqVNEAABIQPNo11ctk1qQAMsEipwN5nnaPMcCaAUCShdVEV2XFe2JYdZwrJK1DzY9fVqQAslwAVlN5v3QBA3mYBJQpcPCP38CDglXYNMDeZpaXOPAVXhQtjlEtFHzPUZ2CaB4fTuFAX3RbjjlQS5K38IQpqDV1PWw7gEA0HE5RcEN93Yw5j1jTjS0udIkPcGp2hJAK5HNrGQjgaYNCeJW7SER4phGqYozFFwHiBsenogPCjyNsCACk2h5Cs8A-JQUjSGbcEKOgpimOQADiiQeIM5A4vAcJcLw5AABS8CovA-AF2gAJTkG77sQKJcDkOpzhJf0slx6YMwjDpxQwOQXDaPCUBgL7qr6Jx3G8dYSR18Jie8IG4coYHV0-FJ1hh4H1hRwp9T8O7pjqe5uCiKg1i58E+c52AecwHY8h1GEyQ-NIppcAd0NXeQ-DkMv0ir+vKhb8bmjkAAPhf5AANoALoOSx8jGAYpdmuQ3e8MHsfAE-rHH5vbemg-htUoMHLQvADBKEEtHR+wJ5AAF8-6f2DgAcijqgmIPUkjkEwKaOA39YHIPDmgtUvBMHkFQUPXAv1bRfC+AAOQAGoAA1fIfFQUQjkk857TwXhIawdsZBPlQF4aQ8I7AWytnQG2Yj4SO1YAqCA4iRGCNoIwEAUQQAQHztubQyBQBaCVMQG0ZZkAgEGFLeE+itGKi4GAS6MAKpKCOj1ZAdI6C6FsYNBxygyo6zAKEXgyAYCaAMHALRcAaAeDgNIcI0gt58GtGiAAYmUW4MB+h8HMVwIwEBNEgHYHQAA6pQPojwAlwDKggP2wQCgInMbJGxIBQgqhgMQQavBbjuMGF4kAUcIhlSCYGAAigYbwcAemeIiSAHWJlNDmKKQU4oOlYDFPqI0ZAUEtErKKnAYpg1ijmJWY8K6VsClWgmR0nR+iUBF1MD1WJsSCnLCtMEZYHTA7dKQB4vpugVIhLCTMnEfBRnjPgFMvpKgPDrK6MgL4WjQleVBLwNmNBvnCG0BmApbU4D4F1rc35My8jhIAJJhECGVXh+dU7SDKgiQMkK4AIIQUAA), please check your editor settings/plugins.

**Comment by justingolden21** [comment]
This is a development issue, not a question
