### ISSUE TITLE
prettier fails to parse flow arrow function + generics 

### ISSUE THREAD

**Issue by vicapow** [prettier/prettier#1311]
````js
// @flow

const foo = <o: Object>(store: o) => {};
const b = '2';
````

````
SyntaxError: Unexpected token (4:0)
  2 | 
  3 | const foo = <o: Object>(store: o) => {};
> 4 | const b = '2';
    | ^
````
see: [prettier playground](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20%40flow%5Cn%5Cnconst%20foo%20%3D%20%3Co%3A%20Object%3E(store%3A%20o)%20%3D%3E%20%7B%7D%3B%5Cnconst%20b%20%3D%20'2'%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

Also see that [flowtype.org/try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqStZQBeUAHlgC5QB5AIwCsBTFbAPgAodYAnRq2AJTFWoAN4BfANyoMOULWKgA5ACYlkoA) has no issues:

**Comment by darahak** [comment]
It works with Flow parser.
Not the same issue, but similar: https://github.com/babel/babylon/issues/392

**Comment by vjeux** [comment]
This is a bug in babylon, can you please report an issue in their project. Once it is fixed upstream, we'll update babylon and it'll work in prettier. Those are also usually pretty simple to fix, if you are interested in helping out.

In the meantime, you can use `--parser flow` to get you unblocked.

**Comment by existentialism** [comment]
Fixed in https://github.com/babel/babylon/pull/475, will update prettier as soon as we tag a new version!
