### ISSUE TITLE
[Feature Request]: New options "Preserve New Line" and "Max Preserve New Lines"

### ISSUE THREAD

**Issue by Citywatt-SJ** [prettier/prettier#13111]
It would be nice to have options like "Preserve New Lines" (bool) and a "Max Preserve New Lines" (number).
So adding linebreaks for readable reasons should not be deleted. 

For the example we assume to set "Preserve New Lines" to TRUE and "Max Preserve New Lines" to 2.

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgCbEDKEAtnACI4BuAzgOo4wAWAVgIrpwBOATwAUASnzAAOlGn58s+VDkASYQHIAdJFgIYa0RsIAHIwmLCFK9QB5iDAHz6N8AB4x1NAJIA1fAHkAOQBRfQAaRTkrNVsHfQVRAG4FaRSoAF8QUJAII1xoRmRQQn5+CAB3AAVihAKUQgAbMsJBAqyAI35CMABrOBgyQmoAGRwoOGRUBsY4ds6evrIjLtGAc2QYfj4suEo2uFJ9ocIoFfRCFbgAMQh+SkIYXBPkEEJ0GAhMkHYYSnrmdjYcEYSzAcDINTYDDYgmeYEYrRAo2m-BgFU6KzuEymMxAnEYLjIq3qcF4EHgWPq0yyS34yOebUIe3qnyM-FGMFYxA4yAAHAAGamlabMTpGZ6soECejjLIAR3QZLgaJytRejAAtGN9vtPvw4PKcHq0edMUhJpScdNKDh1ptLUSSQryWbsVkYIzOdykAAmN2dHD1VYAYSoppAQIArJ90NMACqM2rmqkgeh8TxQYi6MhgNm5ACCGbIMEExIp0zSaSAA)

**Input:**

```jsx
function addSomeDivsWithjQuery() {

  
  
  $('.content').append(
    $('<div>').text('DIV ONE'), 
    $('<div>')
  );
  


}
```

**Output:**

```jsx
function addSomeDivsWithjQuery() {
  $(".content").append($("<div>").text("DIV ONE"), $("<div>"));
}

```

**Expected behavior:**
```jsx
function addSomeDivsWithjQuery() {

  $(".content").append(
    $("<div>").text("DIV ONE"), 
    $("<div>")
  );

}

```

**Comment by mniemann-citywatt** [comment]
+1

**Comment by kachkaev** [comment]
👋 @Citywatt-SJ! Please see [Prettier Option Philosophy](https://prettier.io/docs/en/option-philosophy.html).

Chaining functions are extremely hard to format. Implementing your suggestion will likely break code style for a lot of folks and create a counter-issue.

If you want to force multiple lines in your case, can:

## Use `// prettier-ignore` before the statement

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgCbEDKEAtnACI4BuAzgOo4wAWAVgIrpwBOATwAUASnzAAOlGn58s-AHpF+AA784MXAIC0OAOZQIGhQBJhAcgB0kWAhgXRVwqtUJiwhXPMWAPMQYAPkcreAAPGEsaAEkANXwAeQA5AFFHABp5KDlvS38gxwVRAG4FaXKoAF8QdJAIVVxoRmRQQn5+CAB3AAU2hGaUQgAbTsJBZtqAI35CMABrTTJCagAZHCg4ZFRhxjgpmfnF1Vn1-WQYfj5auEpJuFJ7lcIofXRCfTgAMWNKQi1T5AgQjoGAQGogdgwShDZjsNhwRjHMBwMj9NgMNiCQFgRgTEDrXb8GDdGb6X5bHZ7ECcRhhMinIZwXgQeAUoa7WrHfiEwGTQh3Ibg9TrGCsYgcZAADgADJyOrtmDNVID1AiBPRNrUAI7oFlwEn1AZAxg6Db3e7gjQ6nAaEnvclIbbsqm7Sg4c6XF0Mpm61mOym1GD8sUSpAAJkDMxwQ1OAGEqA6QAiAKzg9C7AAq-IGTo5IHofGiUGI9jIYH4OAaAEFi2QYIJGWzdpVKkA)

```sh
--parser babel
```

**Input:**

```jsx
function addSomeDivsWithjQuery() {

  
  // prettier-ignore
  $('.content').append(
    $('<div>').text('DIV ONE'), 
    $('<div>')
  );
  


}
```

**Output:**

```jsx
function addSomeDivsWithjQuery() {
  // prettier-ignore
  $('.content').append(
    $('<div>').text('DIV ONE'), 
    $('<div>')
  );
}

```

## Add an empty comment within the statement

```diff
-   $('<div>')
+   $('<div>') //
```

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgCbEDKEAtnACI4BuAzgOo4wAWAVgIrpwBOATwAUASnzAAOlGn58s+VDkASYQHIAdJFgIYa0RsIAHIwmLCFK9QB5iDAHz6N8AB4x1NAJIA1fAHkAOQBRfQAaRTkrNVsHfXwAeniFUQBuBWkMqABfEFCQCCNcaEZkUEJ+fggAdwAFcoQSlEIAGyrCQRK8gCN+QjAAazgYMkJqABkcKDhkVBbGOG7egaGyIz7JgHNkGH4+PLhKLrhSY7HCKA30Qg24ADEIfkpCGFwL5BBCdBgIXJB2GEozWY7DYcEYazAcDIDTYDDYgneYEYnRAk3m-BgNV6GyeMzmCxAnEYLjIm2acF4EHgeOa8zya346PeXUIR2avyM-EmMFYxA4yAAHAAGemVebMXpGd6csECejTPIAR3QVLgWIKjQ+jAAtFNjsdfvw4MqcEasddcUhZrSCfNKDhtrtbWSKSrqVb8XkYKzefykAAmL29HDNTYAYSolpAYIArL90PMACqsxrWukgeh8TxQYi6MhgLmFACCObIMEE5Jp8yyWSAA)

```sh
--parser babel
```

**Input:**

```jsx
function addSomeDivsWithjQuery() {

  
  
  $('.content').append(
    $('<div>').text('DIV ONE'), 
    $('<div>') //
  );
  


}
```

**Output:**

```jsx
function addSomeDivsWithjQuery() {
  $(".content").append(
    $("<div>").text("DIV ONE"),
    $("<div>") //
  );
}

```
