### ISSUE TITLE
Prettier fails to parse some TypeScript generics syntax

### ISSUE THREAD

**Issue by rossng** [prettier/prettier#13147]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAkgMwEEo0AeAFQBpsBNagOQD5sBebABmzgA94oATAM7YAFAEZsAMmzkAlNgD8tbEmz0A3NgA6sTDlyCAqlADWUCAHcoFZmwCup81a68EQmYrxESFalDgAbnAATtQwwXZwzKr+QcHqOuhY2MZmllAASnAYADYAhmAhvtgA0ralLnzuANoAllD4IdgA6rUwABbk7bWC1AB0A-WNwS1t7VmCMAC6nuSVbsJ1DU1ZuQVwXT39g8sjq-mFE9OeBqlO1vvrm4LMPFXCsU1K1ZeF19t9Z+mvRT9H1GUZqpqq0Ou9sANPo5vtkDr9Yet-qMOkdGEDsNUpqpyDodAB6PHYAAytRMOAAwtBJhEwDAIMEAAp5YJ5AC2cHgwV62A6PR5eTJwjy2EgUGpdlp9J5emweWEHRw+FqXJgsuCAHM7OzYH18YSAEJ2VVy2XYQRwUX8NWa7UwahtfmC00wOy5HAQfDSrDCAC0Puw0BwSUVUrgBXa2HVCBCtTA2AsOAseVgPIg2GCCMKOh4GHpquD2AA4tHgrHKWLwhK6YzmWyOSFBBR5gIhQAjakFVX+CyiSHM9WCVTJtDyFjMYcA8pfKw-YKkcviyU1lnszmN8iMScgSggCAYGC1KnIUDM4KWJkZsXIEB5HJJtCCbcgVsssBkmAAZTrJP8yHwt-NHcXwKd8PwwAp6nVZBKzgHc4FZVs4H4fgkKJZNNTyKMADF6VZPIYAPKAoJQPIjQgJ92hgVkcmabp4EEcDCg-BBBDaWoAjaNBrzAQRHx3epzWCGAGRZdU8L-ADYJAAArQRuA-SCcjgABFOwIHgCSckAkBwK5EJr1bPJEJyJ8MFLWBWn4DpkAADnYHczIgc1mhZDBrzMuBBKCJ8AEc1PgES90fEjBB9fwkKQp8Mz85U4BEzDxKQf8tKk81WVqaCIlSxSVP8uBNO0mAjMs6ykAAJh3cI8lqHJIMpVlEpATyAFYnzsc1yCM4Lku0gJIlwAQEE-MBS33Yh+A-dAlIKuAAF9ZqAA)

```sh
--parser babel
```

**Input:**

```jsx
type IfAny<T, Y, N> = 0 extends (1 & T) ? Y : N; 
type IsUnknown<T> = unknown extends T ? IfAny<T, never, true> : never;
type UnknownReplacer<T, K> = K extends [infer WithThis, ...infer WithRest] ? T extends [infer ReplaceThis, ...infer ReplaceRest] ? IsUnknown<ReplaceThis> extends never ? [ReplaceThis, ...UnknownReplacer<ReplaceRest, K>] : [WithThis, ...UnknownReplacer<ReplaceRest, WithRest>] : []: T

// Like ConstructorParameters, this takes a constructor type as the first argument.
// But as a second argument, it takes a tuple of types -- one type for each generic we want to replace
export type GenericConstructorParameters<T extends abstract new (...args: any) => any, K> = UnknownReplacer<ConstructorParameters<T>, K>
```

**Output:**

```jsx
SyntaxError: Unexpected token (1:25)
> 1 | type IfAny<T, Y, N> = 0 extends (1 & T) ? Y : N; 
    |                         ^
  2 | type IsUnknown<T> = unknown extends T ? IfAny<T, never, true> : never;
  3 | type UnknownReplacer<T, K> = K extends [infer WithThis, ...infer WithRest] ? T extends [infer ReplaceThis, ...infer ReplaceRest] ? IsUnknown<ReplaceThis> extends never ? [ReplaceThis, ...UnknownReplacer<ReplaceRest, K>] : [WithThis, ...UnknownReplacer<ReplaceRest, WithRest>] : []: T
  4 |
```

Prettier also has a further parsing issue at 7:44:

```jsx
SyntaxError: Unexpected token, expected "," (7:44)
  5 | // Like ConstructorParameters, this takes a constructor type as the first argument.
  6 | // But as a second argument, it takes a tuple of types -- one type for each generic we want to replace
> 7 | export type GenericConstructorParameters<T extends abstract new (...args: any) => any, K> = UnknownReplacer<ConstructorParameters<T>, K>
    |                                            ^
```

**Expected behavior:**

Prettier should accept this as valid syntax, since the TypeScript compiler does ([see playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgZgQQHYgDwBUA0UCa2ByAfFALxQAMUEAHsBEgCYDOUAFAIxQBkU6AlFAD8uKAC4o+ANxQAUKEiwmAVSQBrJAHsA7kgzEyAVzWadVWvWa8hsRCgzYkEAG4QATtmCuDEYuMcvXSTlwaBV1bSQAJQgwABsAQwBjN3soAGl9dLM6RhYAbQBLJDg3KAB1AuAAC3QqgqZsADpmopLXcsqq6KZgAF1rdGyLfNbS6LikiFr6ppbisZiE5O6+6xhlYwjUcaWpuqZiGhzLf1LhPJ3J6YaoZsawkyjFyddt5+WIHuwM-vE8iuq11m902OkuyVe4IgK2wAK6n2AhF+UDyvXE6BkMgA9FioAAZAqqaAAYQ0SB6XkSwA0rgACvFXPEALYQOiuG7VepQYDxIkseJQRJkikGKk07khKDxFjVaBwArs4BS1wAcwMLKQwEa2NxACEDErpVKoEwIELGMq1RrgNhKtzeZ9jcADHFoBo4BLICwALTeqBk6DyOXiiBJKpQFX0NwFRJQLTQLTxTXcjRQVzvCAyGhgGlKoNQADiUdcMdJ5M8oupdIZzNZbiYGCGuSlACMKUklY4tGw7gyVUxxEmQAISMQh99Mg8IlDXmWRWLq4yWWyG+hCBOgA)).

**Comment by fisker** [comment]
Please use `typescript` or `babel-ts` parser.

**Comment by rossng** [comment]
This worked in the playground but not locally. Which was confusing, until I realised that I had an outdated version of Prettier (2.2.1) locally where the `typescript` parser was still giving an error for some reason. Not sure if this was due to it supporting an older version of TypeScript or if the parser was failing to switch correctly for `.ts` files.

In any case, upgrading to the latest Prettier fixed things.

**Comment by rvk220** [comment]
> This worked in the playground but not locally. Which was confusing, until I realised that I had an outdated version of Prettier (2.2.1) locally where the `typescript` parser was still giving an error for some reason. Not sure if this was due to it supporting an older version of TypeScript or if the parser was failing to switch correctly for `.ts` files.
> 
> In any case, upgrading to the latest Prettier fixed things. Thanks for your help!

Thank you very much for help! In my case, updating prettier also helped.

**Comment by nedredmond** [comment]
I have the most up-to-date typescript, prettier, and @types/prettier. I am getting this error currently.

**Comment by nedredmond** [comment]
@kachkaev Resolved! There was a sibling package in the repo with an outdated typescript version (but did not have prettier installed)-- not sure exactly how the conflict occurred but updating that one fixed it.
