### ISSUE TITLE
trailing commas with inline comments

### ISSUE THREAD

**Issue by montemishkin** [prettier/prettier#1315]
See here:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22f(so%2C%20many%2C%20args%2C%20and%2C%20that%2C%20the%2C%20line%2C%20breaks%2C%20and%2C%20the%2C%20lastOne%20%2F*%20has%20an%20inlineComment%20*%2F)%3B%5Cn%5Cnf(%5Cn%20%20so%2C%20%5Cn%20%20many%2C%20%5Cn%20%20args%2C%20%5Cn%20%20and%2C%20%5Cn%20%20that%2C%20%5Cn%20%20the%2C%20%5Cn%20%20line%2C%20%5Cn%20%20breaks%2C%20%5Cn%20%20and%2C%20%5Cn%20%20the%2C%20%5Cn%20%20lastOne%2C%20%2F*%20has%20an%20inlineComment%20*%2F%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

I think its a bit strange to be putting the trailing comma after the comment.  I would expect the output to have `lastOne, /* has an inlineComment */` rather than `lastOne /* has an inlineComment */,`.  Especially in the second case where that is the way I originally styled it and then prettier moves the comma.

This one is certainly a matter of personal preference, and I personally **don't feel super strongly about it**, but I figured I'd bring it to light and y'all can choose to act on it or not. 

:)

**Comment by montemishkin** [comment]
might be related / similar to: https://github.com/prettier/prettier/issues/1013

**Comment by darahak** [comment]
And https://github.com/prettier/prettier/issues/929

**Comment by vjeux** [comment]
This is the same issue as #929. Feel free to keep the discussion on that other one, I'm going to close this as it's a duplicate. Thanks for reporting it!
