### ISSUE TITLE
Problems with a fallthrough switch cases

### ISSUE THREAD

**Issue by RIP21** [prettier/prettier#1316]
I have a problem with fallthrough case. It's probably related to #1262 
 
Once I check out branch and go the code which was previously formatted with Prettier I have got an error from the ESLint with prettier preset like that. Okay, let it be.
![1](https://cloud.githubusercontent.com/assets/3940079/25106471/e74527da-23c9-11e7-926f-055670f91051.PNG)

But the problem is if I run Prettier against it, it change it this way, so it adds a space between cases. Which cause `no-fallthrough` warning. 
Since I run prettier against all files every time I run the app in the dev mode. It causes a change in files with this case all time after I checkout new branch, which at the end a cause of those linting warning/errors.
![2](https://cloud.githubusercontent.com/assets/3940079/25106470/e743219c-23c9-11e7-9b60-a040a4a4eaba.PNG)

I hope you get it. I have a Windows OS if it will help in any case.

**Comment by RIP21** [comment]
I partially fix this problem with [this fix](http://stackoverflow.com/a/33424884/3917988) so it's checked out LF now if the repo is LF formatted which is accidentally fix this problem, but anyway it seems like a weird behavior. Also, we have .editorconfig which is forces LF EOL. So it's EOL style dependent.

**Comment by vjeux** [comment]
Thanks for reporting this. It should be fixed by https://github.com/prettier/prettier/pull/1263. I'm going to do another release today for it. Sorry about it!
