### ISSUE TITLE
Strange line breaking before `extends`

### ISSUE THREAD

**Issue by arv** [prettier/prettier#1317]
The following does not linebreak before extends:

```js
class X extends Y {
  method() {}
}
```

but when I do:

```js
class X extends Record({
  a: 1,
}) {
  method() {}
}
```

a linebreak is inserted before extends.

```js
class X
  extends Record({
    a: 1
  }) {
  method() {}
}
```

 It is not clear if this is a bug or by design?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20X%20extends%20Record(%7B%5Cn%20%20a%3A%201%2C%5Cn%7D)%20%7B%5Cn%20%20method()%20%7B%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks for the report. This was added to fix https://github.com/prettier/prettier/issues/147. It indeed looks a bit weird in this case. I'm not 100% sure how to fix for both use cases though.

**Comment by vjeux** [comment]
Closing to consolidate with #1317
