### ISSUE TITLE
How to config yaml-formatter behavior to quote with double quote

### ISSUE THREAD

**Issue by icefery** [prettier/prettier#13178]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: CLI
- Runtime: Node.js v16
- Operating System: Windows
- Prettier plugins (if any): YAML

**Steps to reproduce:**

1. Prettier `.prettierrc`

   ```jsonc
   {
     "singleQuote": true,
     "jsxSingleQuote": false
     // ...
   }
   ```

2. VSCode `settings.json`

   ```jsonc
   {
     "prettier.singleQuote": true,
     "prettier.jsxSingleQuote": false,
     "[yaml]": { "editor.defaultFormatter": "esbenp.prettier-vscode" }
     // ... 
   }
   ```

3. Test `test.yaml`

   ```yaml
   title: "This should be formatted to double quote(remain unchanged)"
   ```

**Expected behavior:**

```yaml
title: "This should be formatted to double quote(remain unchanged)"
```

**Actual behavior:**

```yaml
title: 'This should be formatted to double quote(remain unchanged)'
```

**Comment by thorn0** [comment]
Not sure why you expect double quotes after setting "**single**Quote" to true. Let's reopen the issue if you're able to reproduce a bug on the playground https://prettier.io/playground/

**Comment by icefery** [comment]
> Not sure why you expect double quotes after setting "**single**Quote" to true. Let's reopen the issue if you're able to reproduce a bug on the playground https://prettier.io/playground/

You may have misunderstood my meaning. I mean that I expect single-quote with JS and double-quote with YAML.

Now i am using VSCode `settings.json` as follow:

```json
{
  "[javascript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
  "[yaml]": { "editor.defaultFormatter": "redhat.vscode-yaml" }
}
```

Should I open a new issue in another repo https://github.com/prettier/prettier-vscode ?

Thanks please!

**Comment by thorn0** [comment]
Use glob-based config overrides: https://prettier.io/docs/en/configuration.html#configuration-overrides

**Comment by icefery** [comment]
> Use glob-based config overrides: https://prettier.io/docs/en/configuration.html#configuration-overrides

OK. It's just what I want~ Thanks a lot!
