### ISSUE TITLE
Strange output when formatting an <a> tag with an internal <span>

### ISSUE THREAD

**Issue by eric-g-97477** [prettier/prettier#13182]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAyzU55VACMIAEwCefAQNQBDcmDqyAzsoC8TEJTh06EcvNlHjRgyfMmzl81aOaGqZQAdZUBtt0RUAemeuH3rJSgt4iEnw+HDwMIAA0IBBOMACW0MrIoLIATlkQAO7E2QjpKLJ0ebLi6fFCWbJgANZwMADKsjRw3MlQcMgwWQCucDV1jc0tLmDdAOZ9g8MgcDRCcKKiq9yu0wOy03AAYhBZNLIwKVCzpQMwEHFatHQA6pTJ8H5gcC3Fr8kAbq-iZDgVR3brKOBZGDEOrTE7IABmZXB8QAVsoAB4tGZ0OAARQGEHgCKRCxcWXBWSB1HodycuXBjzqTiBdLgFN+vXiAEcCfBoYkSiAVABaHqrVZ3LJwHnJKXQ3ZwpCIujIkDgmjJOZDeLKbF43m9JUk+IwWRCR7JUQwSjIABMJrqyToM1wEBoisWygArHcBuD8GaSsrVb8hgBJKDrWAtMBZZJJACCkZaMHEOOJKtJcdgFqtNqQAA4AAwAXxLQA)

```sh
--parser html
--bracket-same-line
```

**Input:**

```html
<!DOCTYPE html>
<HTML>
  <body>
    <a class="hello a aaaaaaaa aaaaaaaaaaaaaa aaaaaa aaaaa aaaaa"><span>hello</span></a>
  </body>
</HTML>
```

**Output:**

```html
<!DOCTYPE html>
<html>
  <body>
    <a class="hello a aaaaaaaa aaaaaaaaaaaaaa aaaaaa aaaaa aaaaa"
      ><span>hello</span></a
    >
  </body>
</html>

```

**Expected behavior:**

Because bracketSameLine is true, I would have expected something closer to:

```
<a class="hello a aaaaaaaa aaaaaaaaaaaaaa aaaaaa aaaaa aaaaa">
    <span>hello</span>
</a>

**Comment by thorn0** [comment]
You're looking for https://prettier.io/docs/en/options.html#html-whitespace-sensitivity
