### ISSUE TITLE
Dangling/widowed operands

### ISSUE THREAD

**Issue by exogen** [prettier/prettier#1319]
Thank you so much for Prettier, it's amazing!

I was looking through my formatted code and this particular expression jumped out at me as a rather non-human way to format this ([link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20maxIndex%20%3D%5Cn%20%20searchArray.length%20*%5Cn%20%20searchArray%5B0%5D%5B1%5D.length%20*%5Cn%20%20searchArray%5B0%5D%5B1%5D%5B0%5D%5B1%5D.length%20-%201%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)):

Input:
```js
const maxIndex =
  searchArray.length *
  searchArray[0][1].length *
  searchArray[0][1][0][1].length - 1
```

Output:
```js
const maxIndex =
  searchArray.length *
    searchArray[0][1].length *
    searchArray[0][1][0][1].length -
  1;
```

Prettier seems to be using indentation to shine some light on the operator precedence here, but IMO the result is harder to follow (and visually jarring).

**Comment by azz** [comment]
This isn't ideal, but's a fairly minor edge case that's probably not worth adding extra complexity to the code for, so lets close this one.
