### ISSUE TITLE
`--ignore-unknown` does not work for explicitly specified directories

### ISSUE THREAD

**Issue by alefbragin** [prettier/prettier#13198]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: CLI
- Runtime: Node.js v16.14
- Operating System: Linux

**Steps to reproduce:**
Make dir with e.g. `font.otf` file(s).
Make `.prettierignore` with `*.otf` (e.g.) pattern.
Run `npx prettier --ignore-unknown --write frontend/src/assets/fonts`

**Expected behavior:**
Do nothing and return exit code 0.

**Actual behavior:**
Prints `[error] No supported files were found in the directory: "frontend/src/assets/fonts".` and returns exit code 2.

**Use case**
I intend to use it in the same scenario as described in #8136. But it's not possible currently because of this case.

**Comment by thorn0** [comment]
You're looking for https://prettier.io/docs/en/cli.html#--no-error-on-unmatched-pattern
