### ISSUE TITLE
Put parens around assignment in implicit return of arrow function

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#1320]
```js
(function() { return foo = bar + 2 });
() => foo = bar + 2;
```
→
```js
(function() {
  return (foo = bar + 2);
});
() => foo = bar + 2;
```

I think it would be nice if the arrow function got parens around the assignment as well:

```js
() => (foo = bar + 2);
```

Found in prettier/eslint-config-prettier#14.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22(function()%20%7B%20return%20foo%20%3D%20bar%20%2B%202%20%7D)%3B%5Cn(()%20%3D%3E%20foo%20%3D%20bar%20%2B%202)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Sounds good to me, feel free to send a PR for it!
