### ISSUE TITLE
[CSS] Prettier removes trailing comma inside `var` function 

### ISSUE THREAD

**Issue by pocka** [prettier/prettier#13202]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAWmICMBDAJyWwDdqAKUygLwBoBKAbgIF8Q7EBAAOMAJbQAzslDUqEAO4AFaghkoKAG0UUAnjKFkqFMAGs4MAMoUAtnAAy4qHGTptUuEZPnLVkabOAObIMFQArl4gcLZkcAAm8QkOFFBB4RRBcABiEFS2FDASacggFOEwEIIgABYwtloA6jXi8FIBYHBW6q3idK16pWBShiDOnlQwyiZBBW4eUQBWUgAeVsFacACK4RDw81qeQgFUE0Mj1SJUzjCN4vEwNcgAHAAMxwqejSYipVdwEzoriEAEddvBpqINGUpMQXAkEtUqHAweJkdNMnMkO5DlFPLZxKEIniNttwa5sQshDAKGQ7g8nkgAEzUkziLTBADCEFsWOiUgArNVwp4ACq0jQ4o4gOiRACSUCSsCsYGuYgAgoqrDA9JsDp4+HwgA)

```sh
--parser css
```

**Input:**

```css
.foo {
  --bar: var(--baz,);
}
```

**Output:**

```css
.foo {
  --bar: var(--baz);
}

```

**Expected behavior:**

The bare comma, which indicates "fallback to nothing," remains.

```css
.foo {
  --bar: var(--baz,);
}
```

## Spec

https://www.w3.org/TR/css-variables-1/#using-variables

> In an exception to the usual [comma elision rules](https://www.w3.org/TR/css-values-4/#comb-comma), which require commas to be omitted when they’re not separating values, a bare comma, with nothing following it, must be treated as valid in [var()](https://www.w3.org/TR/css-variables-1/#funcdef-var), indicating an empty fallback value.
> Tests
> 
> Note: That is, var(--a,) is a valid function, specifying that if the --a custom property is invalid or missing, the [var()](https://www.w3.org/TR/css-variables-1/#funcdef-var) should be replaced with nothing.

**Comment by barroudjo** [comment]
The problem still exists in 2.8.1, is this expected ?

**Comment by fisker** [comment]
Can you open an new issue with your code?

**Comment by barroudjo** [comment]
The playground link in the first post still reproduces the problem.
Just in case, [here it is](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAWmICMBDAJyWwDdqAKUygLwBoBKAbgIF8Q7EBAAOMAJbQAzslDUqEAO4AFaghkoKAG0UUAnjKFkqFMAGs4MAMoUAtnAAy4qHGTptUuEZPnLVkabOAObIMFQArl4gcLZkcAAm8QkOFFBB4RRBcABiEFS2FDASacggFOEwEIIgABYwtloA6jXi8FIBYHBW6q3idK16pWBShiDOnlQwyiZBBW4eUQBWUgAeVsFacACK4RDw81qeQgFUE0Mj1SJUzjCN4vEwNcgAHAAMxwqejSYipVdwEzoriEAEddvBpqINGUpMQXAkEtUqHAweJkdNMnMkO5DlFPLZxKEIniNttwa5sQshDAKGQ7g8nkgAEzUkziLTBADCEFsWOiUgArNVwp4ACq0jQ4o4gOiRACSUCSsCsYGuYgAgoqrDA9JsDp4+HwgA):.

**Comment by fisker** [comment]
This fix is not released yet. https://github.com/prettier/prettier/pull/9583
