### ISSUE TITLE
VS Code / TextMate Grammars: Multi-line Generic Type Arguments

### ISSUE THREAD

**Issue by karlhorky** [prettier/prettier#13212]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: VS Code Extension
- Runtime: Node.js v16.11.0
- Operating System: macOS 12.5 (21G72)
- Prettier plugins (if any): None

**Steps to reproduce:**

Format the following code:

```ts
type A = SomeLongerTypeName<AnotherFairlyLongTypeName, AndFinallyAReallyLongTypeName>;
```

It will become this:

```ts
type A = SomeLongerTypeName<
  AnotherFairlyLongTypeName,
  AndFinallyAReallyLongTypeName,
>;
```

[Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXmwGUIBbOAGWgHM4AnAFUzgDkBDCgHlyghgAWDAGLsAlvQA2aalBrMsHCgBo8UACbCxUdpOm4ASnF3TZ8lkrgA+ANwhlICBhhjoAZ2Sh29ehADuAAreCB4oun7saB4OAEb07GAA1nAwxJxU2nDIAGa6bnCx8UkpxBgJ2jTIMPQArgUgcGQxcOrqLZTscjXsdMIQ9GTsMC5yyCDsNTAQ9iACMGSSAOoCYvBuZWBwxCGrYgBuq2hjYG7RINr59DAB8TSDOXn1AFZuAB7EFZJwAIo1-FlIXKSfIOMr0S5jGLsZqSAC0MDOGHo2hgizE6kEyAAHAAGUG+fKLeIYMZIuCXPZZBwARz+8BuTlC4zcsKgcBaLRm9DgtIkcBuPXugMeDnyZDEVVq9Tcnx+dIBQJBqGhaIxAmQACYHNVxJIKgBhchChpuACsMxq+UY0NCivqezqAEkNAhUmBkc5eOpiOgvg9gXAAL6BoA)

This will unfortunately cause [the official VS Code TypeScript TextMate grammar](https://github.com/microsoft/TypeScript-TmLanguage) to no longer report `punctuation.definition.typeparameters.begin.ts` (the correct sccope). It will now report `keyword.operator.relational.ts`:

![111757788-febc6500-889b-11eb-8f92-fe6102fba050](https://user-images.githubusercontent.com/1935696/182412431-809efd8f-68d1-4473-8dc8-134216f11697.png)

I showed this overlay by using [the `Developer: Inspect Editor Tokens and Scopes` command (aka the Scope Inspector)](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector)

This is because of a limitation in TextMate Grammars: https://github.com/microsoft/TypeScript-TmLanguage/issues/761

**Expected behavior:**

Allow the option of formatting generic type arguments on a single line, without using `prettier-ignore` comments, which will disable other formatting:

```ts
type A = SomeLongerTypeName<AnotherFairlyLongTypeName, AndFinallyAReallyLongTypeName>;
```

This sounds like a TypeScript-specific option to me (only for Prettier parsers which parse TypeScript), which may go against the philosophy of Prettier.

**Actual behavior:**

No option for formatting type arguments on a single line.

**Terms for search:**

Generics, parameters, type parameters

**Comment by thorn0** [comment]
> which may go against the philosophy of Prettier

Right, we can't add options for each small problem like this.

Also, I believe this can be fixed on the TypeScript-TmLanguage side: https://github.com/microsoft/TypeScript-TmLanguage/issues/761#issuecomment-1230342817
