### ISSUE TITLE
SyntaxError: Unexpected closing tag "div".

### ISSUE THREAD

**Issue by JusticHentai** [prettier/prettier#13218]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: 
- Runtime: 
- Operating System: 

**Steps to reproduce:**

monorepo pnpm vue@2.6.14

add  local workspaces prettier preset
```json
"@my-name/prettier-config": "workspace:*",
```

run `prettier --write .`

**Expected behavior:**

no error

**Actual behavior:**
```
packages\code-mode\src\Home.vue
[error] packages\code-mode\Home.vue: SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (4:5)
[error]   2 |
[error]   3 |       <div class="img"></div>
[error] > 4 |     </div>
[error]     |     ^^^^^^
[error]   5 |   </div>
[error]   6 | </template>
[error]   7 |
```

without monorepo it can work
but in monorepo it throw that error

**Comment by fisker** [comment]
Please double check you html  markup, or paste full code of your file, can't help without it.

**Comment by JusticHentai** [comment]
code:
```vue
<template>
  <div class="douza-app">
    <Home />
  </div>
</template>

<script lang="ts">
import Home from '@pages/h5/views/Home.vue'
import { Component, Vue } from 'vue-property-decorator'

@Component({
  name: 'app',
  components: {
    Home,
  },
})
export default class app extends Vue {
  created() {
       console.log('test')
  }

  mounted() {}
}
</script>

<style lang="scss">
@include h5-config;
</style>
```
run 
`prettier --write .`

error
```
packages\templates\code-mode\src\pages\h5\App.vue
[error] packages\templates\code-mode\src\pages\h5\App.vue: SyntaxError: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (20:1)
[error]   18 |   mounted() {}
[error]   19 | }
[error] > 20 | </script>
[error]      | ^^^^^^^^^
[error]   21 |
[error]   22 | <style lang="scss">
[error]   23 | @include h5-config;
```

Only at monorepo will it be reproduced

**Comment by fisker** [comment]
[Can't reproduce on playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG5lj4DOzAvMSFRAK4BeeALR4sWTiXIVKACQgY4ZAPQSKqRbToS1mXATgTSqZmABONLDDL4oAcw4gYzcaRrYIJy7PlkAZiblkAOQAAlh4NnDMigAWAKyKdDRwAO5RXnAAdHQ8cIEubh5kwGQAwnJY0AgwADRkAGo5ZAC+vv4YQdlwglj+WHAeAJ6CVHCQJgTueVCkwWVuUFUAFMCkFFB48khBIliB1auM5ZWwzFsrkhTp+5JN100AlKRwAB4VhSM+eDw4lkx4rGQdmQXvAoFRmPVGucKKY4HoqIt7kUDlIYdBmBAcJkcBAbItAvBmDBAo8bqQDhheLA4AikcAmqQGVA1MYzBYDMyiQMsVY8LZ7MZWM4oMEaFAmDwRmQ4oJIFAfDQbABuQyKLlYwggaogCAWGjo5CgPAmfzJAAKxoQzGQIDwOGSeAG1u1ACNxmAANZwGAAZQ2cAAMmK4MhPjhmHBXe6vb6wmAxTZkDATDltXAMC6aSMqAG+TYeOE4AAxdwYAgwBM2r4wCBakDRGAYHAAdWiNEJcbgPqt7fo7YGNrArDrYojHjN4xsZdDdoj2oAVsxnj6E1iAIo8CDwGfhyMgMImMc2zp1npimDNmhUGDRZAADgADNqehAI83xlgbT1Iv06CHtQAjpu8ATrq1ooP8ggLDSNJ1iYcBATQ8ETuE05IGGc4gBGGA0EmKZ7swq5wBuW4huhs57jAeAupe163kgABM2rJngNA4AmcxoSAkSxHWPARgAKtR4EYXunQAJJglUPqmOYMAAIJgj6MDcmRolNE0QA).

Sorry, can't help.

**Comment by JusticHentai** [comment]
Thanks for your assistance and i found that the error came form the plugin `@volar/vue-typescript@0.39.4` and `prettier-plugin-organize-imports@3.0.1`
