### ISSUE TITLE
Regression in parenthesis wrapping.

### ISSUE THREAD

**Issue by rafayepes** [prettier/prettier#1321]
After upgrading from v0.22.0 to v1.1.0, one version of parenthesis wrapping for assignment doesn't work as before anymore.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Cn%2F%2F%20Still%20works%20as%20before.%20Right%20assigment%20wrapper%20in%20parenthesis%5Cnlet%20c%20%3D%20d%20%3D%200%3B%5Cn%5Cnlet%20a%20%3D%200%3B%5Cnlet%20b%20%3D%201%3B%5Cn%5Cn%2F%2F%20Regression%20after%20upgrading%20from%20v0.22.0%20to%20v1.1.0%5Cn%2F%2F%20In%20this%20ocassion%2C%20right%20assigment%20is%20not%20wrapped%20in%20parenthesis.%5Cna%20%3D%20b%20%3D%200%3B%5Cn%5Cn%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by edufelipe** [comment]
@rafayepes I'm pretty sure this is intentional, as it was fixed in https://github.com/prettier/prettier/issues/962

**Comment by vjeux** [comment]
As @edufelipe, this is indeed intentional. We shouldn't add parenthesis when the user is doing a chain of `=`. Maybe your real use case would have benefited parenthesis? I'm going to close this but feel free to continue the conversation.

**Comment by rafayepes** [comment]
Fair enough. Didn't know it was intentional. TBH, I don't mind, but should the first example be consistent? Why keeping the parenthesis in the following assigment?
```js
let c = (d = 0)
```
