### ISSUE TITLE
Prettier ignore isn't working on an import in javascript

### ISSUE THREAD

**Issue by arnmishra** [prettier/prettier#13228]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgDFd0ARAQxnPwDMcJ18ByGkgWgBNLymAdKAPQD8mHHBgxUcHG1QBzKLjj98q-Bmx58AfVr1GTADYQuAZwAWfKBtwFg+AKoAlADL4AvnobMArjkNWIAA0IBCYktCmyKDkOPQA7gAKsQhRKOSG8eQAnlEhAEY45GAA1uIAyuTocC6oUHDINBmmcAVFpRWYxXVyyDA4Pq0gcOj5cBwc4y7kUHI+5HJwxDjolJKzyCDkPjAQwSDmMOiGAOrmqPCmXWBw5akXqABuF9mbYKZ5aFAteIlFcqtGs0hgArUwAD3KPUMcAAij4IPAgYYWiEujgfpt8uQxoZ9qI6jATqgODBzMgABwABjR9BaJyKmE2ojgP0eDRCAEcEfA-mE0ltTGx6uNxvsxNzUGI-gtAUgmiihi10Kg+gMldC4TyGvLgSEqPliaTyUgAEz6oqoQw9ADCDDlw1MAFZ9j4WgAVHFpBWokCPQYASSgk1g5TAOFQ4QAgsHyjBsjDkS13O4gA)

Prettier does not consider `prettier-ignore` on imports in javascript (specifically I use typescript). I.e. in the playground, it removes the leading spaces even with the prettier-ignore set. 

The exact case I'm dealing with is that it's removing the import for `import FormData from 'form-data'` presumably because it thinks it already exists globally but it doesn't. Using `prettier-ignore` doesn't work on that line, but adding the entire file to the `.prettierignore` does work.

**Comment by thorn0** [comment]
Prettier itself never removes any imports, so you're in the wrong place. You must be using some plugin for that or your IDE is set up to organize imports on save.

**Comment by fisker** [comment]
Maybe [`unicorn/prefer-export-from`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/prefer-export-from.md) did?
