### ISSUE TITLE
Remove custom parser API

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#13232]
We've supported ESM config, ESM plugins, there is one more ESM related thing left.

We support [file path as `parser`](https://github.com/prettier/prettier/blob/2c77149e6a3f6d5a74745a23c38e13f2ffebe28d/src/main/parser.js#L53), but we always treat it as [estree parser](https://github.com/prettier/prettier/blob/21b4045dfa0e20aa99888b43bc5daacfc5492875/src/main/load-parser.js#L11-L23), I really don't think this feature is useful.

Q: Should we remove support for it or load if via `import()`?

**Comment by thorn0** [comment]
How about fully removing this custom parser API and writing a short guide on how to convert a custom parser into a plugin?

**Comment by thorn0** [comment]
An example of how people use it: https://github.com/observablehq/prettier-react-tachyons

**Comment by fisker** [comment]
> How about fully removing this custom parser API and writing a short guide on how to convert a custom parser into a plugin?

Sounds good to me, can you work on it? I'm bad at docs.

**Comment by thorn0** [comment]
okay

**Comment by thorn0** [comment]
> can you work on it?

You meant only the docs, right? :)
They're here https://github.com/prettier/prettier/pull/13249
I don't want to work on the rest :)

**Comment by fisker** [comment]
Sure, I can continue.

**Comment by fisker** [comment]
Fixed by #13250
