### ISSUE TITLE
Plugin loading is incorrectly memoized

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#13235]
**Environments:**

- Prettier Version: next
- Running Prettier via: API
- Runtime: Node 18
- Operating System: WSL
- Prettier plugins (if any): custom

**Steps to reproduce:**

```js
import * as prettier from "prettier";

console.log(
  await prettier.format(".", {
    plugins: [
      { parsers: { baz: { parse: () => ({}), astFormat: "baz-ast" } } },
      { printers: { "baz-ast": { print: () => "1" } } },
    ],
    parser: "baz",
  }),
  await prettier.format(".", {
    plugins: [
      { parsers: { baz: { parse: () => ({}), astFormat: "baz-ast" } } },
      { printers: { "baz-ast": { print: () => "2" } } },
    ],
    parser: "baz",
  })
);
```

The problem is here:

https://github.com/prettier/prettier/blob/2c77149e6a3f6d5a74745a23c38e13f2ffebe28d/src/common/load-plugins.js#L13

Both plugins are serialized to the same string by `JSON.stringify`.

**Expected output:** `1 2`

**Actual output:** `1 1`

**Comment by fisker** [comment]
Fixed by  #14576
