### ISSUE TITLE
A way to keep initial indentation when formatting a "snippet" - or part of a file

### ISSUE THREAD

**Issue by pmorch** [prettier/prettier#1324]
Use case: I'm using [Neoformat for vim](https://github.com/sbdchd/neoformat), where I select a snippet (e.g. the insides of an if-statement), and run it through `prettier`. I'd like to keep the indentation of the first line and reformat the snippet accordingly. Assume this code:

```
    ....
    if (true) {
      doSomething(); doSomethingElse();
    }
    ....
```

Assume the `doSomething(); doSomethingElse();` line starts on column 7 (First column is column 1).

Expected result: `doSomething()` starts on column 7 after being run through `prettier` and `doSomethingElse()` also starts on column 7 on the next line.

Actual result: Both lines start on column 1, not column 7.

## Workaround

I can create a wrapper script that checks the amount of indentation of the first line. Subtract this number from 80 and give that to `--print-width`. Run prettier, and subsequently re-indent the entire prettier output that amount of spaces.

But it would be handy if `prettier` would do that for me - perhaps behind an option.

**Comment by vjeux** [comment]
Yeah, this is something we should implement at some point. I honestly thought that it would have been needed for adoption but it turns out that people are going all in and not only converting entire files but also entire projects using it. This is a better outcome as it makes prettier a lot more valuable. But we still should support reformatting a range.

**Comment by pmorch** [comment]
I've created a [gist with an implementation of the workaround](https://gist.github.com/pmorch/39d1bab04090216628cadb3e39f01177)

**Comment by vjeux** [comment]
This was implemented by https://github.com/prettier/prettier/pull/1609
