### ISSUE TITLE
Parentheses shouldn't be removed from inferred function return types with extends constraints

### ISSUE THREAD

**Issue by rossipedia** [prettier/prettier#13275]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYhCAHgBUA+bAXm2OzgA94oATAZ2wAoA6bgQyWx5Q0AbQC6ASkrl2ASygAzOACdsAJVoMErbCxhK5Ac0kB+Ndn5Q4AN2UBuEABoQEDDBnQWyUDyVKIAdwAFHwRPFB4AG38eNE8nACMlHjAAazgYAGUeAFs4ABk5OGR5SJY4BKTU9IyMZMNkPQBXcpA4bPi4JiZOvMEDRp4DOHwlbJ4YNygDZBAeRpgIRxAACxhsiIB1ZZl4FlqwOAzQnZkrHbQZsBY4kDkypRhApIMx4tKWgCsWOgzDCLgAIqNCDwN4RMpOWpKe4zeI8DoRAC0MBuGH0sA2MiYMGWyAAHAAGSF+MobJIYGZouD3GxLACOwPgTxcYVmLERlk6nSWSjgDJkvKeg1eSBK4JaZWyMgaSmaThYf0BjKKoveThg8Mx2NxSAATOqkjIIoYAMIQbIi1osACsS0aZWI8LCYohICszQAkswEJkwPpXABBZgZdD-MFlAC+EaAA)

```sh
--parser babel-ts
```

**Input:**

```tsx
type Foo<T> = T extends (...a: any[]) => (infer R extends string) ? R : never;
```

**Output:**

```tsx
type Foo<T> = T extends (...a: any[]) => infer R extends string ? R : never;

```

**Expected behavior:**

The parentheses around `(infer R extends string)` should be preserved. Removing them results in an error with TypeScript, as shown in the TS Playground ([link](https://www.typescriptlang.org/play?ssl=3&ssc=1&pln=3&pc=79#code/C4TwDgpgBAYg9nAPAFQHxQLxWVCAPYCAOwBMBnKACgDpaBDALijqJAG0BdASk3QEsiAMwgAnKACVcBYuShlgIgQHMoAfglQmRCADdRAbgBQAemPYAFnwoB3OCIDWZBodCQoAIToiU6LDnyEpBQ09Ews7Ny8VALCYpIBMhTyikRKPOqSWroGQA)):

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/96213/184290978-acbda5f0-ece1-4637-8bc0-726452228c4b.png">

**Comment by GlebDolzhikov** [comment]
https://github.com/prettier/prettier/pull/13289

**Comment by thorn0** [comment]
I think it'll be slightly better if Prettier prints the parens this way:
```ts
type Foo<T> = T extends ((...a: any[]) => infer R extends string) ? R : never;
```
