### ISSUE TITLE
Computed property even spacing standard

### ISSUE THREAD

**Issue by celso-henrique** [prettier/prettier#1327]
Expected "[" and "]" to be on the same line **(standard/computed-property-even-spacing)**

Ex:
`fooBarfooByStudentId[studentId] = barFoobarByStudentId[studentId] || [];`

Becomes:
```
fooBarfooByStudentId[studentId] = barFoobarByStudentId[
  studentId
] || [];
```

In this case maybe it should be on the same line.

**Comment by vjeux** [comment]
Thanks, this looks like a bug that we should fix.

**Comment by vjeux** [comment]
There are a handful of issues about breaking on [] which leads to unfortunate looking code but unfortunately I don't know how to solve it. I'm going to close this issue since it's not actionable. If someone has an idea on how to fix it, please let me know!

**Comment by zevdg** [comment]
FYI, for now, the best solution to this problem is outlined at https://github.com/prettier/eslint-config-prettier/issues/29#issuecomment-368641895

namely, extend "prettier/standard" in your eslintrc

**Comment by 302wanger** [comment]
write // eslint-disable-next-line
before your wrong line
like 
``//` eslint-disable-next-line
      this.$refs.cdWrapper.style[
        transform
      ] = `translate3d(${x}px,${y}px,0) scale(${scale})``
