### ISSUE TITLE
error when formatting html class names containing tailwind arbitrary variants

### ISSUE THREAD

**Issue by zanona** [prettier/prettier#13279]
The issue happens when using tailwind [arbitrary variants](https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants) as class names, but only when the `&` is expanded into `&amp;` via client side rendering, i.e: `element.outerHTML`.

The selector in question `[:hover>&amp;]:opacity-50` works as `[:hover>&]:opacity-50`, but not with the `&amp;`
I should mention this works on the playground as expected, but fails on the CLI under @2.7.1

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEBYANgIYDOFAvLiANpIAWE2cATgHwBkZAtgAcA3AF0kEAWTCYYATwC0AVgAMdfEU5M4JEhFQB6LNk74QAGhASYmaBWSgy7dhADuABUcI7KMiRdlZOwsAI3YpAGs4GABlfjgAGUwoOGQAM18KOBCwsEiYyWkoAHNkGHYAVyyQOD5guHR0eviyYvKyIrgAMQh2PjIYa2LkEDJymAhzECYYPhIAdSYZOAoCuGivGRwZWWGwKkmkzPYYNzCivrSMqoArCgAPaKSikjgARXKIeEuSTItJdiOw2ms0mAnYSRgc0w6BgTGQAA5lH9nJk5mEBMMwcsOGxJgBHD7wU4SbwjCjyZL1eqTdhwAmYWmndoXJDpH5VTJ8TClCocp4vd6fFKsq4WGBkYJQmFwpAAJjFYUwJCeAGEIHwWdUKIpJuVMgAVCXeNm-EDYSoASSgjVg0TA4IEMAAgtbonIXt9MgBfL1AA)

* Works on the playground but not on the CLI

```sh
# Options (if any):
```

**Input:**

```html
<div
  class="[:hover>&amp;]:opacity-50"
  >hello</div>

```

**Output:**

```
[error] file.html: Error: Expected a backslash preceding the semicolon.
```

**Expected behavior:**
Output should be the same as the playground
```html
<div class="[:hover>&amp;]:opacity-50">hello</div>

```

**Comment by thorn0** [comment]
Sounds like a plugin issue. Wrong repo?
