### ISSUE TITLE
Yarn add fails due to incompatible module error

### ISSUE THREAD

**Issue by timbuckley** [prettier/prettier#1329]
This is a React Native app.

`babylon@7.0.0-beta.8: The engine "node" is incompatible with this module. Expected version ">=4.2.0".`

```bash
my-app feature/prettier 🚀  yarn add --dev prettier
yarn add v0.18.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error babylon@7.0.0-beta.8: The engine "node" is incompatible with this module. Expected version ">=4.2.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by SimenB** [comment]
You can use npm to install, which just prints a warning instead of failing.

Should probably be reported to babylon, though 😄

**Comment by timbuckley** [comment]
@SimenB You're right, it seems to be a global `yarn` issue for some reason, rather than `prettier`'s problem. Thanks for pointing it out!

**Comment by despairblue** [comment]
@timbuckley you can also use `yarn add prettier --ignore-engines`

**Comment by timbuckley** [comment]
Thanks @despairblue!
