### ISSUE TITLE
Can't format TypeScript files with decorators in a non-babel project.

### ISSUE THREAD

**Issue by jlachniet** [prettier/prettier#13302]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: Visual Studio Code Plugin (same issue with CLI)
- Runtime: Node.js v16.15.1
- Operating System: Windows 11
- Prettier plugins (if any): @trivago/prettier-plugin-sort-imports

When trying to format a TypeScript file with decorators using the Prettier Visual Studio Code plugin nothing happens. Removing the decorator causes it to format. When I try to format via the CLI I get this error:

```bash
src\test.ts[error] src\test.ts: SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "decorators-legacy", "decorators". (7:0)
[error]   1 | import { exampleFunction } from 'example-library';
[error]   2 |
[error]   3 | function MyDecorator() {
[error]   4 |   return (target: any) => foo(target);
[error]   5 | }
[error]   6 |
[error]   7 | @MyDecorator('Test')
[error]   8 | export class Test {}
[error]   9 |
```

I am using the latest version of Next.js which uses SWC, not Babel. If I add a Babel config to my project then Next.js will use it instead of SWC. I tried switching "parser" to "typescript" in my Prettier config, but I get the same result. Is there a way to get prettier to format this code without using Babel?

**Comment by kachkaev** [comment]
I’m unable to reproduce this in the Playground:
- [typescript parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHzgA8BDLAGzgDEBXKMGVafAX3wDMcJ18ByUhUzUAtJVQAjHGRwBPfgG4AOlFWcGTFlHwBZOQBE4kGTFwAKAJSF8OODDo4d5mLIDm9pPjJQ51gLwAfFwQEC7u9tZsqvj4qgAC+kYmZGY45vwAKnAAzjD8lqqk2Hj4YJRkOTn42XmEbCAANCAQmMzQOcigsjwA7gAKsgidKGSUvWRync3SZGAA1vYAyhRwADKoUHDInGM5cDMyC8uYc5tuyDA4dAcgcOiScAAmT89rPm50ZB40uOipzCgF1GdDMTRAAAsYOhKAB1CGoeA5U5gOBLYaI1AAN0RcmQ4Cq4M2+zw-Rkbn+Oz2twAVjkSEtztQAIp0CDwKmUfbNU44En4mByTC5MA4VBtcGYMWwWGoJ4wCHIAAcAAYeTx9rCZJh8VLcnAcFjts0AI5s+Bk1ojECVURbZ7PcF2M2oOxk76UpC7Lm3fboVCXa6+plwVns7Ze6nNVySWXyxVIABM0ZkqAkQIAwrxPXccgBWcF0faZMiSEbe7kgLE3ACSUFesCWovFMAAgvWloLqJz9mw2EA)
- [babel parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHzgA8BDLAGzgDEBXKMGVafAX3wDMcJ18ByUhUzUAtJVQAjHGRwBPfgG4AOlFWcGTFlHwBZOQBE4kGTFwAKAJSF8OODDo4d5mLIDm9pPjJQ51gLwAfFwQEC7u9tZsqvj4qgAC+kYmZGY45vwAKnAAzjD8lqqk2Hj4YJRkOTn42XmEbCAANCAQmMzQOcigsjwA7gAKsgidKGSUvWRync3SZGAA1vYAyhRwADKoUHDInGM5cDMyC8uYc5tuyDA4dAcgcOiScAAmT89rPm50ZB40uOipzCgF1GdDMTRAAAsYOhKAB1CGoeA5U5gOBLYaI1AAN0RcmQ4Cq4M2+zw-Rkbn+Oz2twAVjkSEtztQAIp0CDwKmUfbNU44En4yRkR6UcGYHCbGCw1BPGAQ5AADgADDyePtYTJMPixbk4DgsdtmgBHNnwMmtEYgSqiLbPZ7guzG1B2MnfSlIXZc277dCoS7XL1MuCs9nbd3U5quSRSmVypAAJgjMlQEiBAGFeG67jkAKzguj7TJCkYe7kgLE3ACSUFesCWYHFbQAgtWljA5NROfs2GwgA)

Please share reproduction steps if you think this is a bug in Prettier core.
