### ISSUE TITLE
Ignore semicolons when reordering lines

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier#13317]
I often reorder lines in my editor (`alt-up/down` in VSCode) to refactor JS code while keeping it formatted with Prettier. Unfortunately this only works on multi-line chained calls if semicolons are disabled, because semicolons break parsing the AST between lines. This is one of the main reasons I disable semicolons (the only option [my config](https://github.com/nickmccurdy/prettier-config) changes from the Prettier 3 defaults). However, I'd still like to be able to conveniently reorder lines in projects that use semicolons with Prettier.

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAugHSgAhwOgDMBLAG3gCcAKASgG5s98BbAQwAdbsQAaECdjGLQAzslCsKFCAHcACpIRiUrUjNYBPMXwBGFVmADWcGAGVWzOABliUOMkKqRcXfqMnT7A7YDmyGBQAri4gcMw6cAAmkVFWrFA+gaw+cABiEBRsMEIJyCCsgTAQvCAAFjDMpADqpcTwIl5gcKZKdcQAbnUaeWAi2iC2zhQwcvo+bA5OIQBWIgAepr6kcACKgRDwk6TOfF4UQ3k6rBGkJewUtjBVxJEwpcgAjADsu9LOVfrseedwQ+32fAAjut4KMBMp8iIALR2KJREoUODA4iI0bJCZIRzbELOZjEfxBHFLVYg+yYqZ8GDHa63e5IABMlP0ZF8AGEIMwMaERABWEqBZwAFWOyixOxA7WCAEkoDFYKYwBdBABBWWmGAaZZbZwAXx1QA)

```sh
--parser babel
--print-width 17
```

**Input:**

```jsx
[]
  .filter();
  .map()

```

**Output:**

```jsx
SyntaxError: Unexpected token (3:3)
  1 | []
  2 |   .filter();
> 3 |   .map()
    |   ^
  4 |
```

**Expected behavior:**

```jsx
[]
  .filter()
  .map();

```

**Suggested implementation:**
Ignore or remove semicolons when parsing, offset line length by 1 where appropriate, and continue formatting with semicolons.

**Workaround:**
Use [my config](https://github.com/nickmccurdy/prettier-config) or use `--no-semi` or `semi: false`

**Comment by thorn0** [comment]
Prettier's contract is "valid code is transformed to valid code". Formatting or fixing invalid code is out of scope.
