### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by NostalgicGareth** [prettier/prettier#13322]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: 
- Runtime: 
- Operating System: 
- Prettier plugins (if any): 

**Steps to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by kachkaev** [comment]
👋 @NostalgicGareth! You must have pressed ‘Submit new issue’ before filling in the template. No worries – this happens! Please submit a new issue with a reproducible example if you have found a bug in Prettier.
