### ISSUE TITLE
Prettier fails on windows-latest but works on mac and ubuntu

### ISSUE THREAD

**Issue by vsvipul** [prettier/prettier#13345]
**Environments:**

- Prettier Version: 2.5.2
- Running Prettier via: CLI
- Runtime: Node v16
- Operating System: Windows
- Prettier plugins (if any): 

**Steps to reproduce:**
See the checks on this PR - https://github.com/actions/cache/pull/903
Prettier format check works for ubuntu and mac, but fails for windows-latest - 
https://github.com/actions/cache/runs/7951958627?check_suite_focus=true

Also checked for line endings -
- `* text=auto eol=lf` already present in .gitattributes.
- Also tried adding `endOfLine: auto` to prettierrc but that also didn't work. https://prettier.io/docs/en/options.html#end-of-line

**Expected behavior:**
Prettier format check should pass on windows as well, as the format is correct.

**Actual behavior:**
Prettier format check fails on windows only.

**Comment by fisker** [comment]
That's strange, but seems https://github.com/actions/cache/pull/903/commits/0ae681867531e1dfbccfa23b9be8c84e4c2ec7b2 fixed it?

**Comment by vsvipul** [comment]
It didn't. It failed again.

**Comment by vsvipul** [comment]
Looks like `!` was unnecessarily escaped. Removing that fixed it. Weird that this error was not thrown locally. Closing this issue for now. Thanks.
