### ISSUE TITLE
inconsistent () formatting

### ISSUE THREAD

**Issue by mjemiracle** [prettier/prettier#13352]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2AF8BuAHSlzwDoBDIzAbQF0qoAKWxgSjoAHAK5oAFl0oh4GKX3KYA9IsxwAHgEZq1XiPHN2nXaLFCTk6XFkh51HvjPiBeiVJkw5C5arUAmbVCQUBiYTMQanEEhOMwR1FFYACbMTABUmDEqGgAM2V4q6gDM1CAANCAQgjAAlujIoAwATo0QAO4ACk0IaMggDAA2rQwAnj3lOI0MYADWcDAAygwAtnAAMtVQcMgAZgNocOOTM3PzglMbAObIMI3CByBwSzhwiYkvqwxQF8IMF3AAYhBGksGDAal9egxhDAIGUQGIYEt+gB1MTVGRnMBwebddHVABu6OGvTAaDGIA2+0aMHakwuIJ2e3ueDQanml36cAAisIIPBGf19uUzo0qb0cAxnv04YJGhsYMjqokYGJkAAObLClr7ZGTQS9WVWOCNfFbcoAR158FplR6KAYaAAtJsXi84Y04Jbqh7ab8GUhdoL7vsltVrrdgxzuVatgGmeUYJLFcrVUhfAnJtV+pcAMIQJb+h5oACscNEcAAKpK7YGhSB8XcAJJQN6weZgOVVACCLfmMGGnIF+1IpCAA)

```sh
--parser babel
```

**Input:**

```jsx
const obj = {};
obj.a = [];
(obj.a).push("test"); // ex1

obj.push = [];
obj.push.push("test");
(obj.push).push("test"); // ex2

const a = 1;
const b = 1;
const d = a * b / 100; // ex3

```

**Output:**

```jsx
const obj = {};
obj.a = [];
obj.a.push("test"); // ex1

obj.push = [];
obj.push.push("test");
obj.push.push("test"); // ex2

const a = 1;
const b = 1;
const d = (a * b) / 100; // ex3

```

**Expected behavior:**

There is an inconsistency in how Prettier formats the parentesis.

* In Ex1 it removes the ().
* In Ex2 it removes the ().
* In Ex3 it adds ().

Case 1: defending adding ()
* It makes the code easier to read.

Case 2: defending removing ()
* They are not needed, and only adds clutter.

**Comment by thorn0** [comment]
Prettier used to print as few parentheses as possible, then it switched to print some extra ones for readability. See the very long https://github.com/prettier/prettier/issues/187 for the full story.
