### ISSUE TITLE
Prettier doesn't format table correctly which has Chinese in markdown

### ISSUE THREAD

**Issue by claviering** [prettier/prettier#13362]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABITtNASFujgMeUE6HPdQLn9jUAdKDAWhNvrr2owEYA6dQf3lAKV0FklQPdegH+1AX4roAHgBsAzhJKAA70CqyoBh-wL6agPO1ADc4ZAeRqACpUCeGYDu3QMryge88qNdACYugd+jAQjaA4FUGBS40DHyiteB8VwzL1bQxAAHTAQMjXQHpTQEBjKwwAZi5AQitAf3NAcNNAN7lAPlN+DExAfvlAaDlAX3jAa-0VbWUSQHnrQCo5FNDAT+1AFL1AADkayVl5DNj0ABYuQCijDrl0FMAbePQAIwBDGTgANl6AGhJAHgTAHgtADaySbUBuvMAzh0AwuRbCFUBCm0Bng0AGJSnZhd70QDR-QEAPQBXrQHx3DQzADfjAck0WKCsdAwACWMCkcBIAEESAAhAHMOhMdBMIGcdDTTHTEiTEhgBG2LjYjCTUlkvEEhIYnF4gAm9IZ9IJ-WpGDA7I5+LZeBASxAEAADqDoDJkKBpgAnCUQADuAAVJQhRShplIZdMAJ6ivmTCXTMAAazgMAAytMALZwAAyIKgcGQADNVXMdXrDcaTQL9baAObIGASgCucD5cHNkzg9MjVumUB9gemPrgADEIBLzdMYKC48gQNNAzAILyQAALGDmqQAdRLYLgMi9YDgJqVYJBADcwRrc2AZNqQLa5hKYHK9T6M47nSGQAArOQm30QgCKgYg8AnsinXolg9zGYlBtpsqgxYFEttMErINpMBLyAAHAAGPmniBzSt6gW5091uAStv2vkAEcV3gEdBWVPMZFoO1I0jYsJTgYCQQQkdE3HJAnQ3Pk5nNEF-SDKcZAXOBl1Xe0MMnPkYGmSZL2vW8kBsKi9RBKRfQAYQgc10JAOsAFZi0DOYABUaOVTCXRANtgwASSgWkEFNMAzyFKF5JNGANQhdc5gAX10oA)

```sh
--parser markdown
```

**Input:**

```markdown
| 方案 | 优点 | 缺点 |
| - | -- | - |
| 1. 使用前端导出 xlsx | 简单，好实现| 增加项目体积|
| 2. 请求后端接口，后端生| 简单，好实现| 需要后端支持|
| 3. 模板文件放前| 方便下载快，实现简单 | 每个模板要对应一个 xlsx 文件|
| 4. 把 xlsx 模板转 base64, | 逼格高 | 实现麻烦了一点，没想到 base64 编码比真实文件还大 |

| title | A | B |
| - | -- | - |
| 1. aaaa | b | c |
| 2. a | bbbbbb | c |
| 3. a | b | cdddddddd |
| 4. a | ccccccc | c |
```

**Output:**

```markdown
| 方案                      | 优点                 | 缺点                                             |
| ------------------------- | -------------------- | ------------------------------------------------ |
| 1. 使用前端导出 xlsx      | 简单，好实现         | 增加项目体积                                     |
| 2. 请求后端接口，后端生   | 简单，好实现         | 需要后端支持                                     |
| 3. 模板文件放前           | 方便下载快，实现简单 | 每个模板要对应一个 xlsx 文件                     |
| 4. 把 xlsx 模板转 base64, | 逼格高               | 实现麻烦了一点，没想到 base64 编码比真实文件还大 |

| title   | A       | B         |
| ------- | ------- | --------- |
| 1. aaaa | b       | c         |
| 2. a    | bbbbbb  | c         |
| 3. a    | b       | cdddddddd |
| 4. a    | ccccccc | c         |

```

**Expected behavior:**
table one should be formated

**Comment by thorn0** [comment]
Prettier tries its best, but what the output looks like depends on the font. If in a font, a CJK character doesn't take exactly the space two Latin letters take, then the result will look bad, and nothing can be done about it, unfortunately.
