### ISSUE TITLE
Specifying a range for Vue files removes the new line at end of file even if that character is out of the specified range

### ISSUE THREAD

**Issue by younesaassila** [prettier/prettier#13399]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmpaEAqc2+8AzmXgE5xkBmEbGB8ACasWAdzg4cAOhmkKFVAHpqpJZlwE4JKKqZg2ASywxtOODDIAFDjBgG4bMgF5uvfhaeEywMgE8IAK5sUgBWTAAUAOQwABaBAOYxkQCUZAC+qop6hsbaujC+ZtpSeFDCPmBMTEhkMBAQZACEBti8MKUWGVBKTAVFpCAANCAQxgbQTMig7GwQopbsCJMoeDiieL6TwwBGbHhgANbmAMp4GHAAMgZQcMhcq0xwO3uHJ1j71-HIMGwBTyD0bZwQSCYEXUrxAJ4eJwABibgEn2QIDwATqQxAMRgGBwAHUYgZmO8wHBjktCQYAG6E3zIypbEDXR5sGDWaH8O4Pf5hAAex0+ZgAigEIPBOThHsN3mxmcjKX8MVhDLBcQZBLFkAAOAAMUtmj1xeywyKVcGZlNuwwAjiL4NZRssUUwALQ3YHAjEcG0GDhs+IcpD3CX-R4YAzfX4hgVwYWi26BrnDdrbVXqmLIABMSb2BhwnwAwhAMAGAUwAKwYgKPGh4bbLIOSkDyuAASTKCBgx30RhgAEEysc+vGG-89lAYYP2DBkAB2ADMwzHMIAomVkABGAAsZbSaSAA)

```sh
--parser vue
--range-start 73
--range-end 145
```

**Input:**

```vue
<template>
  <p>Templates are formatted as well...
    </p>
</template>

<script>
let Prettier = format => { your.js('though') }
</script>

<style>
.and { css: too !important }
</style>\n
```

**Output:**

```vue
<template>
  <p>Templates are formatted as well...</p>
</template>

<script>
let Prettier = (format) => {
  your.js("though");
};
</script>

<style>
.and {
  css: too !important;
}
</style>
```

**Expected behavior:**
New line at end of file should not be removed when formatting Vue file.

**Detailed explanation:**
Range is not yet supported for Vue files (see [#12576](https://github.com/prettier/prettier/issues/12576)). Thus, formatting with or without range **should be consistent**.

The issue is, formatting without range does keep the new line at end of file (_expected_), but formatting with any range removes the new line at end of file (**bug**).

This bug makes it impossible to use VS Code's `Format on Save Mode` = `modifications` without getting a linter error due to the missing new line at end of file.

**Comment by thorn0** [comment]
This should be fixed on the extension side for now. It thinks Prettier supports range formatting for Vue because of this line:

https://github.com/prettier/prettier-vscode/blob/b3565a783233bcb9d025091c5a89a333569eaada/src/PrettierEditService.ts#L68

Ideally, this shouldn't be hardcoded in extensions. Prettier should report this data via [`prettier.getSupportInfo()`](https://prettier.io/docs/en/api.html#prettiergetsupportinfo). But for now that's how the things are.
