### ISSUE TITLE
bracketSameLine not working on angular and html parsers

### ISSUE THREAD

**Issue by Sergiobop** [prettier/prettier#13407]
**Prettier 2.7.1**
[Playground link - angular parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeArgGwHwB0oAERBqAFpgJb7HHYAyEATnALYEUAOAzumwCYRMTAlwowCAQxZwYAGgKQoXOGHgx0jSX04UuYClADmBOJRgA6AgEcNumBSsTRMYRqgSCQ5mwBuYiXAEfOgUqAD05FSEtOFY2CCyIBAc9tBcyKASjIwQAO4AClkI6SgSmLkSAJ7piQBGjBJgANYyAMpScHQGcMgwjOhwdQ3NbRyNBoa9-YMgrLVwfHwLdBJG6BKGcABiTCwSMPZGyCAS6C4JIKQwLJgA6qRicFxjYHCtxWIUfjCVx2BcNRABmUjBg+Qahj2yAAZmVlIkAFZcAAerQmmDgAEV0BB4DC4TMxowQcdVoYsFkLhxGAYYLcKHwYKRkAAOAAMiWpEGUtwaHGO1KecEYPh6iRsuLg4OSJROXAAtFA4AsFhdmDYKMxwRsoUhYZh4SBlCwKFMBolREYMdjJfiDTMYBJavTGcykAAmRJ9CQUShGADCEBYutmXAArBd0MoACpOkr6w0+AYASSgS1grTANJSAEE060fhi7coAL4loA)
[Playground link - html parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeArgGwHwB0oAERBqAFpgJb7HHYAyEATnALYEUAOAzumwCYRMTAlwowCAQxZwYAGgKQoXOGHgx0jSX04UuYClADmBOJRgA6AgEcNumBSsTRMYRqgSCQ5mwBuYiXAEfOgUqAD05FSEtOFY2CCyIBAc9tBcyKASjIwQAO4AClkI6SgSmLkSAJ7piQBGjBJgANYyAMpScHQGcMgwjOhwdQ3NbRyNBoa9-YMgrLVwfHwLdBJG6BKGcABiTCwSMPZGyCAS6C4JIKQwLJgA6qRicFxjYHCtxWIUfjCVx2BcNRABmUjBg+Qahj2yAAZmVlIkAFZcAAerQmmDgAEV0BB4DC4TMxowQccrjcLhxGAYYLcKHwYKRkAAOAAMiUpEGUtwaHGOlKecEYPh6iRsuLg4OSJROXAAtFA4AsFhdmDYKMxwRsoUhYZh4SBlCwKFMBolREYMdjxfi9TMYBJarT6YykAAmRJ9CQUShGADCEBY2tmXAArBd0MoACoOkq6-U+AYASSgS1grTAVJSAEEU60fhibcoAL5FoA)

```sh
# Options (if any):
--bracket-same-line
```

**Input:**

```jsx
<ul>
    <hli
      >Lorem ipsum dolor sit amet, consectetur adipiscing elit. quristiqasitor urna lorem vitae dui</hli
    ></ul>
```

**Output:**

```jsx
<ul>
  <hli
    >Lorem ipsum dolor sit amet, consectetur adipiscing elit. quristiqasitor
    urna lorem vitae dui</hli
  >
</ul>
```

**Expected behavior:**
```jsx
<ul>
  <hli>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. quristiqasitor urna
    lorem vitae dui
  </hli>
</ul>
```

The output is not the expected using the angular or the html parser.

**Comment by thorn0** [comment]
Adding whitespace like that is unsafe. Please read about the `htmlWhitespaceSensitivity` option: https://prettier.io/docs/en/options.html#html-whitespace-sensitivity
