### ISSUE TITLE
Ignore PHP from formatting in .html files

### ISSUE THREAD

**Issue by xApep** [prettier/prettier#13412]
As far as I have googled it is not possible to have PHP in .html files and that formatting is also working for PHP code blocks.

So my question is; Is it possible to set somewhere in settings to skip from <?php to ?> or to set <prettier-ignore-start--> <prettier-ignore-end-->

**Comment by thorn0** [comment]
That's how Prettier already works. `<? ... ?>` blocks (processing instructions) are output as is:

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAyzU55VACMIAEwCefAQNTEGbOHToRyAdwgAnOqPSoAQgCUG5fJQCWAZ3KXyHHgFZyeiGbpwNABzoBDeADpUAHo5FmlBAH4PSg8WULCwmHMrOPiBJhh09MsU1LMAcyhNOFFY-mlwqUFAkQk+ILteEAAaEAgPGDNoC2RQbw0NCFViPoRulG86VW9xbpahDW8wAGs4GABlbxo4bjMoOGQAMwmLODmF5dW1j0XdvOQYDQBXU5A4GiFi0WLubyg8x+8eTgADFNDRfB0-sgQN5HjAIM0QNR6AB1czwCzXMBwNajMwdABu+PE0LAFlmIF2Jw0MGICzy4MOxxeACsLAAPNa3NwARUeEHgTLoJxa1w01OhyLoiI8Gl2MBRZlEiWQAA4AAyigYnFELDzQ2VwakE-YtACO-PgdLaYxhFgAtHtisVERo4BazG66YDGUgjsKXicaGZ7k9A9y4HyBfs-cyWjBvEJFcrKMgAEzxhauW64CA0X2vCz2RGPE74RNjf0ikAE54ASSgX1gazAcvaAEFG2sYOI3EKTgBfAdAA)

```sh
--parser html
```

**Input:**

```html
<!DOCTYPE html>
<HTML>
  <body>
    <P>Hello world!<BR> This is HTML5 Boilerplate.</P>
    <?php

         this 
         			is
         ignored

    ?>
  </body>
</HTML>
```

**Output:**

```html
<!DOCTYPE html>
<html>
  <body>
    <p>
      Hello world!<br />
      This is HTML5 Boilerplate.
    </p>
    <?php

         this 
         			is
         ignored

    ?>
  </body>
</html>

```
