### ISSUE TITLE
Boolean || followed by an object formats unusually

### ISSUE THREAD

**Issue by karl** [prettier/prettier#1342]
Input:

```js
const x = firstItemWithAVeryLongNameThatKeepsGoing || secondItemWithALongNameAsWell || {};
```

Output:

```js
const x = firstItemWithAVeryLongNameThatKeepsGoing ||
secondItemWithALongNameAsWell || {};
```

It seemed strange to me that the boolean is split without any indendation.

Expected Output:

I would have expected something like this:

```js
const x = 
  firstItemWithAVeryLongNameThatKeepsGoing ||
  secondItemWithALongNameAsWell || 
  {};
```

---

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20x%20%3D%20firstItemWithAVeryLongNameThatKeepsGoing%20%7C%7C%20secondItemWithALongNameAsWell%20%7C%7C%20%7B%7D%3B%5Cnconst%20y%20%3D%20firstItemWithAVeryLongNameThatKeepsGoing%20%7C%7C%20secondItemWithALongNameAsWell%20%7C%7C%20A%3B%5Cnconst%20z%20%3D%20firstItemWithAVeryLongNameThatKeepsGoing%20%7C%7C%20secondItemWithALongNameAsWell%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
I added some special cases for arrays and objects to be on the same line as it looks prettier when they expand. But it looks like it shouldn't be applied for empty ones!

**Comment by vjeux** [comment]
Empty objects no longer break :)
