### ISSUE TITLE
Standard Styleguide

### ISSUE THREAD

**Issue by sharat** [prettier/prettier#1343]
Prettier is a very useful tool. I am using [Standard](https://github.com/feross/standard) as JavaScript style guide and linter. Is it possible to include Standard as well when you format the syntax?

**Comment by despairblue** [comment]
@sharat have a look at the [related-projects](https://github.com/prettier/prettier#related-projects) for some ready solutions for that, otherwise `prettier --write **/*.js && eslint --fix **/*.js` will also do the job.

**Comment by AlecRust** [comment]
@vjeux has a discussion been had? Wondering what the best approach is here.

**Comment by vjeux** [comment]
@AlecRust sorry for closing without giving any response. @despairblue explained ways you can get it working and links to related projects. We can probably do a more streamlined setup with standard but right now it's not the priority. If someone is willing to jump on it, that would be very welcomed though.

**Comment by josephfrazier** [comment]
If you use [prettier-miscellaneous](https://github.com/arijs/prettier-miscellaneous), it's possible to get very close to standardjs formatting with `prettier --no-semi --single-quote --jsx-single-quote --space-before-function-paren`.

See https://github.com/feross/standard/issues/811#issuecomment-309860797 for details/caveat.
