### ISSUE TITLE
Prettier breaks typescript doc comment

### ISSUE THREAD

**Issue by ilyub** [prettier/prettier#13453]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDMk9gAdKPPbOAQwBNoAbATzzgFsMYOFGnQD0AKjHC6YvABE4RMNgCW-ZdAB0UvGJFSAFAEo8AXgB8eAG4RlzANw0AvnZAAaEBDXQiyUI2zYEADuAAr+CD4ojGxBjBw+7gBG2IxgANZwMADKjDxwADLKUHDIpNFEcEkp6ZlZGKlFAObIMNgArpWoPIlwzMy9+YxQjW2MjXAAYjg8jDAwTcggjG0wEG4gABYwPGwA6hvK8ET1YHBZEYfKlocci2BECSBFFbghKY0zpeWdAFZEaFkmmw4ABFNoQeBfNgVdz1bAvRYCDAKJSqGDrDAqWC7WwwDbIAAcAAZYYEKrsUhhFpiFHBsJYSu4AI7g+BvTyRJZEAC0xV6vXWDBZygYbzGnyQZWhnQqPGULXaMqBoNZJUl33cMEYiRxzDxyAATJqUso2E0AMIQHgS1BEACs6zaFQAKtrIlKYSBLB0AJJQfqwLKo-gAQX9WQEwKhFUcjiAA)

```sh
--parser typescript
```

**Input:**

```tsx
export const f: {
  readonly empty: 
  /**
   * Description.
   */
  () => void;
};
```

**Output:**

```tsx
export const f: {
  readonly empty: /**
   * Description.
   */
  () => void;
};

```

**Expected behavior:**

After prettier formatting doc comment is not recoginzed by typescript.

**Comment by thorn0** [comment]
> comment is not recoginzed by typescript

What do you mean?
