### ISSUE TITLE
do while doesn't break

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1346]
```js
do {
  
} while (somethingVeryVeryVeryLong && somethingVeryVeryVeryLong && somethingVeryVeryVeryLong);
```

outputs

```js
do {
} while (somethingVeryVeryVeryLong &&
  somethingVeryVeryVeryLong &&
  somethingVeryVeryVeryLong);
```

instead of

```js
do {
} while (
  somethingVeryVeryVeryLong &&
  somethingVeryVeryVeryLong &&
  somethingVeryVeryVeryLong
);
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22do%20%7B%5Cn%20%20%5Cn%7D%20while%20(somethingVeryVeryVeryLong%20%26%26%20somethingVeryVeryVeryLong%20%26%26%20somethingVeryVeryVeryLong)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by lemon79** [comment]
The current test spec requires the while conditions to be in one line. Even if it is a joint statement. Should there be a max line length limit? Besides can anyone help me with more instructions in setting up tests, currently all test suites fail, like this, sorry I am a college kid on academic probation

FAIL  tests\flow\locals\jsfmt.spec.js
  ● Test suite failed to run

    Cannot find module 'babel-code-frame' from 'index.js'

      at Resolver.resolveModule (node_modules\jest-resolve\build\index.js:169:17)
      at Object.<anonymous> (index.js:3:19)

**Comment by lemon79** [comment]
thank you i updated the modules by npm. it took a few hours but it works

**Comment by vjeux** [comment]
Thanks a lot! I merged the pull request :)
