### ISSUE TITLE
Error: Invalid name: "@components"

### ISSUE THREAD

**Issue by Fenwil** [prettier/prettier#1347]
Here's a screenshot about the error:
![screen shot 2017-04-19 at 3 27 55 pm](https://cloud.githubusercontent.com/assets/2475912/25195944/7da323ca-2515-11e7-9334-716cd9dda93d.png)

These are the imports:
![screen shot 2017-04-19 at 3 28 01 pm](https://cloud.githubusercontent.com/assets/2475912/25195773/0c2b7cc4-2515-11e7-9324-e9c66745e6f1.png)

And in the `components` folder I have this `package.json` so I don't have to use relative paths
![screen shot 2017-04-19 at 3 28 41 pm](https://cloud.githubusercontent.com/assets/2475912/25195793/1b1ea31e-2515-11e7-9115-0662c210b91c.png)

In don't know if is the Plugin itself or Prettier but I have this error from a week ago.

Prettier version: 1.2.0
Prettier-vscode version: 0.14.0

**Comment by vjeux** [comment]
Hey @Fenwil, I'm sorry but prettier is not able to trigger such errors, so it must be something else triggering it :( I'm going to close this issue as it's not actionable inside of prettier.

**Comment by Fenwil** [comment]
Get it. Thanks @vjeux !
