### ISSUE TITLE
Unknown TypeScript node type: "TSParenthesizedType"

### ISSUE THREAD

**Issue by Gregoor** [prettier/prettier#13478]
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: Standalone API
- Runtime: Node v16
- Operating System: macOS
- Prettier plugins (if any): see code

**Steps to reproduce:**

```ts
import * as babelParser from "@babel/parser";
import prettier from "prettier/standalone";

const source = "type T = (a.T | never);";

try {
  const result = prettier.format(source, {
    parser: () =>
      babelParser.parse(source, {
        plugins: ["typescript"],
      }),
  });
  console.log(result);
} catch (error) {
  console.error(error.stack);
}
```

**Expected behavior:**

It should log `type T = a.T | never;`

**Actual behavior:**

It errors out with `Error: Unknown TypeScript node type: "TSParenthesizedType".`

**Comment by fisker** [comment]
[We removed `TSParenthesizedType` after parse](https://github.com/prettier/prettier/blob/main/src/language-js/parse/postprocess/index.js#L83), so the printer don't accept it.

If you want use a custom parser, you should run this `postprocess` yourself.

FYI: We don't support [`ChainExpression`](https://github.com/prettier/prettier/issues/10244) either.

**Comment by Gregoor** [comment]
Great, thanks for the info! Then I'll do some postprocessing myself.

**Comment by Gregoor** [comment]
Looking at the code more closely again it looks like only some `TSParenthesizedType`s are removed (the ones that are type-annotated with `this` or a keyword). Thus I still get unexpected `TSParenthesizedType`s in my code. I'm not sure yet what I'm missing.
