### ISSUE TITLE
Detect JS code templates in JS and format them accordingly.

### ISSUE THREAD

**Issue by nicksrandall** [prettier/prettier#13502]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEArNmC8mAyjAE4CWUA5gHSkCGA7gNwA6U7kUGm8AtgAcANvXgEcaAAbsAZgFcoYGOWiYA4qThwYACij0+cAJSZg7TTDmkomViAAScIUIgAaWyEwBqTPsNsoAF92SWYQVxAIAWV0ZFB6UlIIRgAFBIQ0ZBB6IUZ6AE9MiIAjBjAAa20iAzgAGUo4ZBkctDgSssqYIgF6MEoqZDI5NpA4PmK4ABNJqdr6ajl6KjgAMQhSPlFlaiz6ORgIcJAACxg+IQB1Y-J4NB6wOCIMm-IANxv8rLA0IpBKVtIMBSDComyaLRGuAAHkR+kI4ABFOQQeDgoStCI9UgArLFegTIRHAQUWAXciTGDHZAADgADJikq0LgwBFliXAAa9GhEAI7I+DAqKZFD0NAAWigWhmkyOmj55E0wKWYKQzXRI1afHIg1IwwiaDhiP5jVVEIiMHxZIpVKQACZzQxyEJ+gBhCB8FWjNAAViOclaABV8cK1RiQK9hgBJKAzWBEMAUaIAQRjJHy8LRrUCgSAA)

```sh
--parser babel
```

**Input:**

```jsx
const js = String.raw;

const template = js`
function Greet(name) {
return "Hello, " + name;
}
`;
```

**Output:**

```jsx
const js = String.raw;

const template = js`
function Greet(name) {
return "Hello, " + name;
}
`;

```

Similar to how prettier can detect HTML and CSS tagged templates in JS, I have a use case (I'm writing a JS compiler) where I would like to embed JS code templates in my JS code and it would be awesome if prettier would automatically format them for me.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/12430
https://github.com/prettier/prettier/pull/5993

https://github.com/prettier/prettier/pull/5993#issuecomment-478573220

Closing
