### ISSUE TITLE
Option to keep new lines

### ISSUE THREAD

**Issue by saminton** [prettier/prettier#13503]
I would like to revive this feature request that has been requested multiple time but are now all closed and can no longer be commented upon.

I have been reluctant to use prettier pretty much since its release date but have recently started using it because some of my coworkers really don't care about how tidy their code is. Prettier does help keep things in order. While I have gotten used to some of the quirks that are frequently discussed on here, there is one thing that just drive me nuts. Why O' why does prettier insist on removing all my line breaks.

I read somewhere that the aim of prettier isn't to "force the author preferences on the rest of the world" but without this option it really does seem like it to me.

Having multiple line breaks really helps me visually separate sections of my code, and have prettier remove them can make it really hard for me to navigate the code I have written. Take the following example with Vue where I have multiple languages stuffed into one file.

![Screenshot 2022-09-21 at 20 39 13](https://user-images.githubusercontent.com/15970757/191584579-a0f6a885-fdf3-4581-9bbf-3191f9e1f97f.png)

I don't feel that removing the additional line breaks makes the code more readable and on the contrary makes it worse. Even just looking at the minimap I could see where my 3 languages are.

While I understand some people may not care for this for this feature, considering it has been proposed a few times already I can't be the only one with this problem and it would be great to see this feature reconsidered.

**Comment by thorn0** [comment]
Sorry, we aren't going to do this. See https://github.com/prettier/prettier/issues/13301

**Comment by saminton** [comment]
Oh sorry I missed that one. Shame to hear.
