### ISSUE TITLE
Add option to enable "smart formatting" of HTML class attributes

### ISSUE THREAD

**Issue by ajp2455** [prettier/prettier#13508]
This ticket had the result of reverting the class wrapping feature: https://github.com/prettier/prettier/issues/10918 that was introduced in https://github.com/prettier/prettier/pull/7865. Is there any way we could have an option to re-enable this feature? When using something like TailwindCSS, this leads to lines that are way longer than something like 80-100 characters, making the HTML difficult to read. As a workaround, I can use an older version of Prettier, but would like to update if possible.

**Comment by thorn0** [comment]
Sorry, option requests aren't accepted. Please see https://prettier.io/docs/en/option-philosophy.html
We need an algorithmic/heuristic solution that doesn't involve adding options and also doesn't violate the [reversibility principle](https://prettier.io/docs/en/rationale.html#%EF%B8%8F-a-note-on-formatting-reversibility).
Closing in favor of the original issue https://github.com/prettier/prettier/issues/7863

**Comment by ajp2455** [comment]
Okay, I understand not wanting to add options. Does the current behavior violate the reversibility principle? I believe it does, since prettier will collapse a block of classes that are newline delimited.

**Comment by ajp2455** [comment]
I guess not, since prettier will never split a list of classes to separate lines.

**Comment by ajp2455** [comment]
@thorn0 do you happen to know what PR/commit that reverted the behavior? I'm having trouble finding it, and would like to try my hand at porting it to the latest prettier version.

**Comment by thorn0** [comment]
https://github.com/prettier/prettier/pull/11827

**Comment by thorn0** [comment]
I like this proposal: https://github.com/prettier/prettier/issues/10918#issuecomment-971055862
That solution relies on the input formatting, which is something Prettier generally avoids doing, but at least it's reversible, so I think it'd make sense to do an exception from the "don't rely on the input formatting" rule (it's less important than reversibility and "no options").

**Comment by ajp2455** [comment]
I do too, that seems to give everyone what they want. Is the reason for no motion on that just due to lack of implementation?

I’m surprised that most of the people who do not want the wrapping are Tailwind users, they must have very wide monitors 😄.

**Comment by thorn0** [comment]
Prettier preserves new lines in other attributes. So it seems to be okay to do that in `class`. Only re-indent and replace multiple consequent spaces.

> Is the reason for no motion on that just due to lack of implementation?

Lack of consensus too I think. @alexander-akait are you still against doing this?
