### ISSUE TITLE
Cannot pretty-print complex flow type definition

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#1354]
I have:
```
const transformCache: WeakMap<ProjectConfig, Map<Path, ?Transformer>> = new WeakMap();
```

prettier will be unable to print break this up so it fits within 80 columns.

**Comment by vjeux** [comment]
You should try 1.0 (well 1.2.2), it now allow to break on flow generics.

**Comment by cpojer** [comment]
I take it you are telling me the atom prettier plugin ships with its own copy of prettier instead of using the one in my project, right? Because I'm on 1.2.0 and it didn't work through atom.

**Comment by kjbekkelund** [comment]
@cpojer Looks like it's breaking in 1.2.2 at least: https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20transformCache%3A%20WeakMap%3CProjectConfig%2C%20Map%3CPath%2C%20%3FTransformer%3E%3E%20%3D%20new%20WeakMap()%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by cpojer** [comment]
All good then, sorry about that.

**Comment by vjeux** [comment]
Yes, atom-prettier ships with its own version and doesn't respect the one in your package.json. This is something I want fixed but it needs some work. I've been mostly focused on getting the core formatter to be good.
