### ISSUE TITLE
No file found when formatting in Nextjs project

### ISSUE THREAD

**Issue by doliG** [prettier/prettier#13554]
### Config

`.prettierrc`
```json
{
  "parser": "typescript",
  "printWidth": 80,
  "semi": false,
  "trailingComma": "es5"
}

```

`.prettierignore`
```
// Same as .gitignore plus few addition like `public/`
```

### File structure (project folder)
```
.next/
components/
context/
machines/
pages/
public/
styles/
node_modules/
.env
.eslintrc.json
.gitignore
.lintstagedrc.json
.prettierignore
.prettierrc
README.md
next-env.d.ts
next.config.js
package.json
tsconfig.json
```

### Problem

Hey,

I'm using prettier on a very classic nextjs project. But after following the [doc > install](https://prettier.io/docs/en/install.html), when I run `yarn prettier --check .`, it does not find anything to format. I got the following:
```
$ yarn prettier .
yarn run v1.22.19
warning package.json: No license field
$ /Users/.../crossfuji/node_modules/.bin/prettier .
[error] No matching files. Patterns tried: . !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```

Then I tried `yarn prettier **`, but in that case it format every fucking thing in my codebase without taking into account what I have in `prettierignore`, including node_modules binaries (lol) and make my terminal crash.

Finally I find this workaround, but I'm not very satisfied with it
```bash
yarn prettier ./components/** ./pages/** ./store/** # and so on for every src code folders in my directory
```

It could have been easier if every source code was packed into an `src/` folder, but that's not how nextJS works...

My expectation: when I run `yarn prettier .`, it format everything using the config in `.prettierrc` except for files/folders in `.prettierignore`

What am I doing wrong ?

**Comment by thorn0** [comment]
Sounds like you're using an old (pre-v2) version of Prettier. What's the output of `.../crossfuji/node_modules/.bin/prettier -v`?

(BTW, setting the `parser` option in the configuration file is almost never a good idea. See [docs]("parser": "typescript").)

**Comment by doliG** [comment]
Hey @thorn0 , here's my version of prettier

```
$ ./node_modules/.bin/prettier -v
1.19.1
```

I updated it to `2.7.1` and it's working 🎉 Thank you very much !!

Also I removed `parser` from my configuration.
