### ISSUE TITLE
wrong print-width calculation when non-latin character exists.

### ISSUE THREAD

**Issue by joonseokhu** [prettier/prettier#13552]
code is broken into new line when there's non-latin character included, even if the number of characters is smaller than 80.

I think that it's because that non-latin chars have more Bytes per char than the latins.

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDARmAE0wF4cB3bASyxgAtK0A6PQuAMwB0pNNn8D2AcwAULAgEouPRnQTDhbCBHEkAfJgCEiiI1zYATpO69ZUYXX0QyASTYAxbABs0AT2FQ4ZTAFF9l-cIA5IA6q4AAdZiAHN2ACeOAL6OAAuOYgCjLgLdDmKFRgD6dmIASo5iAGI2ALaOAI82YgCCTgCg9gBP1gC7jmICULYATTYAnTYyB4u1SJrRyFla2Ds5uHl6+-kFiOPyThNNEE-NTC23tANxcXCAANCAQAA4wlOjIoAaWZAAKBghoyCBOFC4327j62GAA1nAwAMrYALZwAAylA8yDYTjQcGerw+X2+uzeIMEyBg+gArlCQHA-rg4AQBARAdgoII0dhBHA7BB9H9sDADiTbtg0TAIFsQLQYH9HAB1ejwNAIsBwb7XaiUABu1BctzAaCeIBBkP0MHOr0EtLBEMxACs0AAPb5IxxwACKaIg8C1zkxCP0ytuelxjnZu30IJgPMoBDoyAAHAAGbZuiCQnmvXa3N1wZUSuDsgCOFvgar2NxQ2DQAFoPHi8ez9HAk5RC2ryZqkOCbdtIX9KCj0Zi0Mazcn45XtdsYHgvT7aMgAExd16URxIgDCED+FaxaAArOy0ZCACp4dNVyHbCUY6xQASwb5gd37ACCe++MBcJutkIAvregA)

```sh
--parser babel
```

**Input:**

```jsx
const abcd = await this.abcdef
  .abcdefg(abcd)
  .then((foo) => !foo.bar)
  .then(throwIfFalsy(new Error('한글 문자열은 팔십 글자를 안 넘어도 줄바꿈이 됩니다.')))
  .then(throwIfFalsy(new Error('abcd abcd abcd abcd abcd abcd abcd abcd ab')));


```

**Output:**

```jsx
const abcd = await this.abcdef
  .abcdefg(abcd)
  .then((foo) => !foo.bar)
  .then(
    throwIfFalsy(
      new Error("한글 문자열은 팔십 글자를 안 넘어도 줄바꿈이 됩니다.")
    )
  )
  .then(throwIfFalsy(new Error("abcd abcd abcd abcd abcd abcd abcd abcd ab")));

```

**Expected behavior:**

```jsx
const abcd = await this.abcdef
  .abcdefg(abcd)
  .then((foo) => !foo.bar)
  .then(throwIfFalsy(new Error("한글 문자열은 팔십 글자를 안 넘어도 줄바꿈이 됩니다.")))
  .then(throwIfFalsy(new Error("abcd abcd abcd abcd abcd abcd abcd abcd ab")));

```

**Comment by thorn0** [comment]
This is intended. These characters take more space (double width) than Latin.
