### ISSUE TITLE
Always add semicolon to the end of CSS code

### ISSUE THREAD

**Issue by xfl12345** [prettier/prettier#13551]
**Prettier 2.7.1**

```sh
--semi true --css-semi true # css-semi is suggest to be supported
```

**Input:**

```jsx
<div style="width: 100px; height: 200px;"></div>
```

**Output:**

```jsx
<div style="width: 100px; height: 200px"></div>
```

**Expected behavior:**

**Input:**

```jsx
<div style="width: 100px; height: 200px"></div>
```

**Output:**

```jsx
<div style="width: 100px; height: 200px;"></div>
```
Formatting CSS in HTML should always add semicolon when option "semi" is true.
Or please add new option "css-semi" to support it. 
The options of "css-semi" can be same as "semi".
Thanks.😘

**Comment by fisker** [comment]
See discussion in https://github.com/prettier/prettier/issues/7907
