### ISSUE TITLE
TS Instantiation Expressions Throw Errors For Multiple Arguments

### ISSUE THREAD

**Issue by RonnyLark** [prettier/prettier#13550]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAYhBADwBqANPgCoB8AFAJT7AA6U++ATnDOt05R0AGxEBuDgF8OHSFADOMfACEAht3wBeIiVJLuOKAHNqBo8briQlEBAAOuaAuSgN3CAHcAChoQuUNRFPNQBPF1sAI241MABrPgBlNQBbOAAZIzhkVCCFOCiY+KT7WItkGG50ApA4FMi4ABNGpvS1E3Q1YzhibhS1GFwTZBA1dBgIGxAACxgUkQB1aZx4BVKwOET-FZwANxXQkbAFCJAjfO4Ybxjjfpy8moArBQAPRIsROABFdAh4e5E+VspW4FxGkTUDREU3shlgCxwjRg02QAA4AAzAjz5BYxewjWFwC67bK2ACOv3g1wcAVGCgAtFA4E0mlNeBScLxrl07khcoCavkUjgKlVBR9vpTsnyHrYYJCEUiUUgAExymI4EQWADCEBSvNqCgArFN0PkaJCAvygSBdtUAJJQFqwRJgQyOACCTsSMFCnwB+SkUiAA)

```sh
--parser babel
```

**Input:**

```jsx
function Foo<V, T>() {
  return null;
}

const Bar = Foo<string, string>;
```

**Output:**

```jsx
SyntaxError: Unexpected token (5:31)
  3 | }
  4 |
> 5 | const Bar = Foo<string, string>;
    |                               ^
```

**Expected behavior:**
To not have an error.
Instantiation expressions have been supported in TS since 2.7.
Prettier seems to allow instantiation expressions with 1 argument but not more than that.
Instantiation expressions should be supported for any number of arguments.

**Comment by thorn0** [comment]
Set the `parser` option to `typescript` or `babel-ts` if you need to format TS code. It's set automatically for ts and tsx files.

**Comment by RonnyLark** [comment]
Why was this closed?
I set my parser to `typescript` and it still throws the error.
Not that it would matter, given that you said yourself it's automatically set for `ts` and `tsx` files.
Prettier seems to hate instantiation expressions with more than one argument regardless of anything.
![image](https://user-images.githubusercontent.com/106962298/193442568-40b2617c-8022-45c6-8450-65b0082f3c98.png)
```
SyntaxError: ',' expected. (11:34)
   9 | }
  10 |
> 11 | const Second = Foo<string, number>
     |                                  ^
```

**Comment by thorn0** [comment]
Please provide a reproduce if you think there is a bug

**Comment by RonnyLark** [comment]
I'm really struggling with creating a reproducible example in the Playground, seemingly everyrthing works fine there.
But I use Prettier in Vscode, extension version 9.9.0 with TS 4.9.0. My config is:
```
{
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "lf",
  "semi": true,
  "trailingComma": "all",
  "singleQuote": true,
  "printWidth": 120
}
```
And like I'm trying to describe, TS Instantiation Expressions fail with anything over one argument.
This works well:
```js
function Foo<T>() {
    return null;
}

const Bar = Foo<string>;
```

This fails with an error:
```js
function Foo<T, V>() {
    return null;
}

const Bar = Foo<string, string>;
```
```
SyntaxError: '(' expected. (28:32)
  26 | }
  27 |
> 28 | const Bar = Foo<string, string>;
     |                                ^
```

Please let me know if I'm missing something to recreate this in the Playground.

**Comment by thorn0** [comment]
The versions of the extension and TS don't matter? What's the version of Prettier?

**Comment by RonnyLark** [comment]
Prettier version 2.7.1.

**Comment by thorn0** [comment]
Without an exact reproduce scenario, nothing can be done to help you, sorry. My best guess is that you somehow have an older version of Prettier in your `node_modules`.

**Comment by RonnyLark** [comment]
I see.
I'll have a look in our dependencies.
Thank you anyway.
