### ISSUE TITLE
Empty loop curly braces

### ISSUE THREAD

**Issue by HeavenVolkoff** [prettier/prettier#1356]
>OS: Mac OS Sierra 10.12.4
Prettier version: 1.2.2

Prettier always breaks lines between the `while` and `for` curly braces, even when there is no code in between.

Before:
```javascript
while (true) {}
for (;true;) {}
```
After:
```javascript
while (true) {
}
for (; true; ) {
}
```

Considering this doesn't happen when Prettier reformats empty functions, I assume this isn't working as intended.

**Comment by vjeux** [comment]
I'm curious, why do you have while loops or for loops without body in your code?

**Comment by HeavenVolkoff** [comment]
Because I needed a simple counter like this:
```javascript
while(++i < length && arr[i] !== value) {} 
```

**Comment by josephfrazier** [comment]
I agree @HeavenVolkoff, these should be formatted the same way as empty function bodies. I submitted a patch at https://github.com/prettier/prettier/pull/1815
