### ISSUE TITLE
Incorrect comments format

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#13579]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3yLAAs4BbAQzwF48o4B3PAcWxo3IEUAZAMoVqNABQAdKAHppeAGYQISPACMa2KQEoQAGhAQMMAJbQiyUBuwQWABQ0JzKGgBsWNAJ7n9qrmADWcDCCNFRw-MbMyPKuRHA+foHBGDRgkQDmyDDYAK7xqFSqcAAmxSX8NFDpOTTpcABiOLQwJlXIIDQ5MBB6IOQwVC4A6uTG8EQpYHCCjmPGAG5jHu1gRN4gkXG4tlzptNGx+QBWRGiCGS5wvDkQ8Acucfop2Fvt6kUuvRjYkTBDxsUYORkAAOAAMT2scSGXAw7W+cC28zgvQAjjd4DtDE4OkQALTMEolXrYODo4ykna1fZIGIPfJxKjGLK5BkXK4YlG0w76GA0VT-QHApAAJl5XGMLgyAGEIFQaagiABWXo5OIAFX5TjpjxA8zyAEkoGVYMIfkYAILGwQwDyXe5xAC+jqAA)

```sh
--parser babel
```

**Input:**

```jsx
export const schema = new GraphQLSchema(
// foo: bar
)
```

**Output:**

```jsx
export const schema = new GraphQLSchema();
// foo: bar

```

**Expected behavior:**

```js
export const schema = new GraphQLSchema(
  // foo: bar
)
```

**Comment by kachkaev** [comment]
Thanks for reporting this case @B2o5T! Let’s track it in https://github.com/prettier/prettier/issues/8804 which is very similar.
