### ISSUE TITLE
Failed to resolve a parser when there should be one

### ISSUE THREAD

**Issue by softorangetech1122** [prettier/prettier#13589]
**This issue doesn't use pre-created issue templates since there is none corresponding to my issue. If there is one, I apologize.**

The logs say: "Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.". However, I don't have a custom file extension, I'm using the Markdown file extension (`.md`) and it's not custom.

Also, what do you mean by "resolving a parser"?

### Full log

```
["INFO" - 9:16:35 PM] Extension Name: dev.prettier-vscode.
["INFO" - 9:16:35 PM] Extension Version: 0.0.0.
["INFO" - 9:16:35 PM] Using standalone prettier
["INFO" - 9:16:35 PM] Using standalone prettier
["INFO" - 9:16:46 PM] Formatting vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/markdowndocs/docs/unpublished/text-blocks.md
["INFO" - 9:16:46 PM] Using standalone prettier
["INFO" - 9:16:46 PM] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 9:16:46 PM] Parser not inferred, trying VS Code language.
["ERROR" - 9:16:46 PM] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

Using the [playground](https://prettier.io/playground/) is completely fine.

**Comment by thorn0** [comment]
Hi, thanks for the report!

This repository is only concerned with the core formatting tool and not the editor integrations. Unfortunately, there's not much we can do to help you in this case. I suggest you open a report on the extension's issue tracker: https://github.com/prettier/prettier-vscode
