### ISSUE TITLE
add a glob example for how to ignore node_modules

### ISSUE THREAD

**Issue by Haroenv** [prettier/prettier#1358]
I tried some globs, but none work, so adding this as an example somewhere will make my day!

```
**/*.js // matches node_modules too
!**/node_modules/*.js // matches non-.js files too
!(**/node_modules|**)/*.js // matches everything
```

<http://globtester.com> was useful, but not enough 😄 

Thanks a lot!

**Comment by lydell** [comment]
What about `prettier "{,!(node_modules)/**/}*.js"`?

**Comment by Haroenv** [comment]
That works to ignore when `node_modules` only exists in one folder, which is useful already, but I'd like to find a solution without xargs preprocessing for the case when the `node_modules` folder can be in a subfolder.

```sh
find . -name "*.js" | grep -v node-modules | xargs prettier --write --single-quote --trailing-comma es5
```

is what I found now

**Comment by eliaslfox** [comment]
I find `find . -name "*js" ! -name "*node_modules*" | xargs prettier` to be a little cleaner

**Comment by Haroenv** [comment]
Maybe some way that prettier would ignore node_modules by default

**Comment by eliaslfox** [comment]
That seems like it could cause some unexpected behavior, plus it doesn't really align with the unix philosophy.

**Comment by gwing33** [comment]
For `lint-staged` setup, using `"{,!(node_modules)/}**/*.{js,jsx}"` is what is seeming to work for me.

**Comment by SEAPUNK** [comment]
I'm trying to lint all files ending in `.js` in my current directory, but I can't seem to create a single glob pattern that matches ALL files in the current directory, excluding multiple directories (`node_modules`, `dist`), and manually including some dot directories (`storybook/.storybook/`).

There has to be a way that's both performant and not limiting.

**Comment by sondr3** [comment]
Sort of related, but I wish there was a way to configure Prettier to ignore specific directories. I've previously used XO, but like Prettier more but I use it with a Yeoman generator and each directory has a template subdirectory that is templated with EJS and Prettier hangs itself up on these files each time. Being able to configure which directories to ignore would be nice, otherwise I end up doing `prettier 'generators/app/!(templates)'` for each subgenerator. Would be nice to just set this in `package.json` so I can just run `prettier --write` instead of having the long string of ignored directories.

**Comment by obartra** [comment]
Building on @Haroenv's answer, I found the following useful to exclude all `.gitignore`'d paths:

```bash
find . -name \"*.js\" | grep -v -f .gitignore | xargs prettier [opts]
```

**Comment by vvo** [comment]
Give the complexity of those globs and the fact that in 99% of situations you will never want to go though node_modules, could we ignore them by default?

Like proposed by @jlongster here: https://github.com/prettier/prettier/pull/1048#issuecomment-287823726

**Comment by ryanpcmcquen** [comment]
@SEAPUNK:
```
prettier --config .prettierrc --write "{,!(excluded|directories)/**/}*.{js,json,jsx,md}"
```
