### ISSUE TITLE
Comment in empty array type breaks code

### ISSUE THREAD

**Issue by aczekajski** [prettier/prettier#13588]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgA1DgAdKQwgDyUIG1LrqB6V25wgXQG5KAviAA0ICAAcYqaAGdkoXJkwQA7gAVFCOSlwAbFbgCec0QCNM+ANZwYAZVwBbOABl0cZHl0y4Zi2Gt24vjoAObIMJgArj4gcA6mcAAmiUnOuFAhkbghcABiEJgOuDBSGcgguJEwECIgABYwDroA6nWo8DJBBLZa7agAbu2G5WAyJmhQ3pgwahYhRR563qIAVjI0tqG6cACKkRDwi14xQZhT5TCG4nAyYJiokrXi97DNqIkwdcgAHAAMos8IN5mhZxOVnjcsP13KIAI77eCzCTaCoyAC0UDgSSStUwcHhqDxs2yCyQnmWIG8DlQ4SiMRkW12CPcZKWMRguFMbw+XyQACZRBFcKhdKEAMIQByk2IyACstUi3gAKpztOSYv1ogBJKApWC2O4PGAAQV1tku2yO3gEAiAA)

```sh
--parser typescript
```

**Input:**

```tsx
interface X {
  x: [
    // x
  ];
}
```

**Output:**

```tsx
interface X {
  x: [// x];
}

```
The code is broken and no longer parsable as correct typescript. This happens both with "typescript" and "babel-ts" parsers.

**Expected behavior:**
Output should stay the same as input.

This is similar to https://github.com/prettier/prettier/issues/9299 but there it breaks only if there's a colon before the comment but with typescript it breaks any empty array type.

**Comment by thorn0** [comment]
Related comment about refactoring of dangling comments: https://github.com/prettier/prettier/pull/13445#issuecomment-1240723341

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/13608
