### ISSUE TITLE
Unstable comment after `static`

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#1360]
```js
class A {
  static
  // comment
  a() {}
}
```
```js
class A {
  static // comment
  a() {}
}
```
```js
class A {
  static a() {} // comment
}
```
https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20A%20%7B%5Cn%20%20static%5Cn%20%20%2F%2F%E2%80%81comment%5Cn%20%20a()%20%7B%7D%5Cn%7D%5Cn%5Cnclass%20A%20%7B%5Cn%20%20static%20%2F%2F%E2%80%81comment%5Cn%20%20a()%20%7B%7D%5Cn%7D%5Cn%5Cnclass%20A%20%7B%5Cn%20%20static%20a()%20%7B%7D%20%2F%2F%E2%80%81comment%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by ikatyang** [comment]
This one is unreproducible now.

---

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOmM6MAlmCWQPQOCABJALZsIz07oAUASkIBfEqKgkwGbPkI8KVWjiasIHLj35Dg48ZOm4CxUuUo0wvQSOUt2nWGJAAaEBAAONaJmSh0AJz8IAHcABX8EbxR0ADcIagATZxAsGGQAM3RUTDgXACM-dDAAazgYAGU3QuooAHNkGD8AVxyQeIgwdMzsl2rsvxgQgpq2dE6sloArTAAPACEC4tKy9E4AGWq4Me7XRpg3XYAmeqaWyr8+5BBc9FyAT1RoJLc-apgAdQSYAAtkAA4ABhczwg2TeBTcl2ecD60U2Lj8cAAjo1qAjBuhhqMkBlxi5smxqMdmnjqjVUHAAIqNCDwLYtSi5D7xb7IA4uBroaioUkAYTUI0uUGgcJAjWyABUbpEcdlhMIgA)

**Input:**
```jsx
class A {
  static
  // comment
  a() {}
}

class A {
  static // comment
  a() {}
}

class A {
  static a() {} // comment
}
```

**Output:**
```jsx
class A {
  static // comment
  a() {}
}

class A {
  static // comment
  a() {}
}

class A {
  static a() {} // comment
}

```

**Second Output:**
```jsx
✓ Second format is unchanged.
```
