### ISSUE TITLE
vscode format on modifications is not working with sass files with prettier

### ISSUE THREAD

**Issue by chungadesnehal1** [prettier/prettier#13618]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#.....)

https://github.com/microsoft/vscode/issues/161383

Steps to Reproduce:

Go to vscode settings
click on formatting in user
select modifications option in Format on Save mode
Goto .scss file and make changes
sass files are not getting formatted

**Output:**
SCSS file is not formatted
**Expected behavior:**
SCSS file should get formatted

**Comment by thorn0** [comment]
Hi, thanks for the report!

This repository is only concerned with the core formatting tool and not the editor integrations. Unfortunately, there's not much we can do to help you in this case. I suggest you open a report on the extension's issue tracker: https://github.com/prettier/prettier-vscode
