### ISSUE TITLE
String underscore "_" object key is replaced with _

### ISSUE THREAD

**Issue by Voyager-Two** [prettier/prettier#13613]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
{
    "trailingComma": "none",
    "tabWidth": 4,
    "semi": true,
    "singleQuote": false,
    "bracketSameLine": false,
}
```

**Input:**

```jsx
            myObject: {
                "_": "-"
            }
```

**Output:**

```jsx
            myObject: {
                _: "-"
            }
```

**Expected behavior:**

Not sure why it does this, but it **doesn't actually break anything**. Just seems like buggy behavior.

**Comment by alexander-akait** [comment]
> doesn't actually break anything

What is broken?

**Comment by Voyager-Two** [comment]
Doesn't break anything for my use case. Seemed like a bug so I created this.

**Comment by fisker** [comment]
Expected, see https://prettier.io/docs/en/options.html#quote-props
