### ISSUE TITLE
space and slash for single tags

### ISSUE THREAD

**Issue by Prodnik** [prettier/prettier#13633]
![image](https://user-images.githubusercontent.com/36890055/195686852-9d3f96cc-be7a-46b4-a38f-d8daf4947a6f.png)
There is a problem, it adds a space and a slash for single tags. How can this be fixed?

**Comment by thorn0** [comment]
Why is this a problem?

**Comment by ExE-Boss** [comment]
Duplicate of <https://github.com/prettier/prettier/issues/5246>

**Comment by fisker** [comment]
Duplicate of #5246
