### ISSUE TITLE
Prettier in VS code not formatting on save for Solidity and Python but works for Javascript and Json?!? I have all set to default formatter as prettier.

### ISSUE THREAD

**Issue by terryrossi** [prettier/prettier#13635]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

**Comment by thorn0** [comment]
Hi, thanks for the report!

This repository is only concerned with the core formatting tool and not the editor integrations. Unfortunately, there's not much we can do to help you in this case. I suggest you open a report on the extension's issue tracker: https://github.com/prettier/prettier-vscode

Please include more details about your setup and a way to reproduce the behavior you report if you open an issue there.
