### ISSUE TITLE
Major conflict with .editorconfig

### ISSUE THREAD

**Issue by veekhere** [prettier/prettier#13630]
Hello there. I notice some critical compatibility issue. Prettier looks into .editorconfig file and breaks his other formatting rules. Please take a look on this below to understand what I mean by that.

I have an **.editorconfig** file that looks like this:
```properties
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.ts]
quote_type = single

[*.md]
max_line_length = off
trim_trailing_whitespace = false
```

Also, I have my prettier config in VSCode settings:
```json
"prettier.useTabs": false,
"prettier.singleQuote": true,
"prettier.jsxSingleQuote": true,
"prettier.printWidth": 140,
"prettier.semi": true,
"prettier.trailingComma": "all",
"prettier.singleAttributePerLine": true,
"settingsSync.ignoredSettings": ["prettier.configPath"],
```

### Notice, that print width is 140!

Take a look on this HTML part:
```html
<ng-container *ngSwitchCase="BreachSortTypeEnum.ForFund">
  <app-fund-list-selector
    class="w-491"
    [control]="getControl(CONTROL_NAMES.FUND, TABS.OBJECT)"
    [displayControl]="getControl(CONTROL_NAMES.FUND_DISPLAY, TABS.OBJECT)"
  ></app-fund-list-selector>
</ng-container>
```

The max length in this case is 83 (including spaces on the left side)

After formatting this code with prettier (and .editorconfig file) I got this:
```html
<ng-container *ngSwitchCase="BreachSortTypeEnum.ForFund">
  <app-fund-list-selector
    class="w-491"
    [control]="getControl(CONTROL_NAMES.FUND, TABS.OBJECT)"
    [displayControl]="
      getControl(CONTROL_NAMES.FUND_DISPLAY, TABS.OBJECT)
    "
  ></app-fund-list-selector>
</ng-container>
```

Look at ```[displayControl]``` attribute. What is happened to this? Why there is extra lines for quotes?

Let's comment everything in global scope of .editorconfig:
```properties
root = true

[*]
# charset = utf-8
# indent_style = space
# indent_size = 2
# insert_final_newline = true
# trim_trailing_whitespace = true

[*.ts]
quote_type = single

[*.md]
max_line_length = off
trim_trailing_whitespace = false
```

Then let's try to format code again. We got this:
```html
<ng-container *ngSwitchCase="BreachSortTypeEnum.ForFund">
  <app-fund-list-selector
    class="w-491"
    [control]="getControl(CONTROL_NAMES.FUND, TABS.OBJECT)"
    [displayControl]="getControl(CONTROL_NAMES.FUND_DISPLAY, TABS.OBJECT)"
  ></app-fund-list-selector>
</ng-container>
```

This is exactly what I wanted. **_This is expected result_**

Rules inside of .editorconfig have nothing general with prettier format config. So what is this then?

**Comment by thorn0** [comment]
Don't use VS Code settings to configure Prettier. It's a legacy/fallback/non-recommended way. Whenever any other config is found, those settings are ignored. See https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#configuration
