### ISSUE TITLE
Unexpected auto add semicolon at vue-template when use non-ascii

### ISSUE THREAD

**Issue by Eriice** [prettier/prettier#13647]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG5kACYONYA1gLzEiCIRj2QD0JcpVoNmrDtxAY4A4aVSDMuAnEIgANCAhYYNaAGdkoPACdzEAO4AFCwhMo8Oa3gCeJnQCNzeDnAwAMp4cgAyNFBwyABmLkZwPn4BwVj+kQDmyDDmAK6JIHAY3nBUVKVheFAZuXgZcABiEOYYBAbVyCB4uTAQ2iAAFjAYOADqAzTwRmlgcEGOk-ST7p1gRl4gkQnmMLZ+Ga2x8QUAVkYAHkGZOHAAirkQ8Ec4CTpp5tuddPn9WOaRMFGNCoMAGyAAHAAGN5WBKjPxYTp-ODbOjRHQARwe8D2eicXSMAFooqVSv1zHAsTQKXs6ockHEXgUEhgaNk8szrndsdEGccdDA8N4gSCwUgAEwCvw0VjVADCEAw9MKRgArP1cgkACpCpyM14gb5wACSUHKsCCYH++gAgmagjB3DdngkAL6uoA)

```sh
--parser vue
```

**Input:**

```vue
<template>
  <div @click="我" />
  <div @click="me" />
</template>
```

**Output:**

```vue
<template>
  <div @click="我;" />
  <div @click="me" />
</template>

```

**Expected behavior:**

```vue
<template>
  <div @click="我" />
  <div @click="me" />
</template>
```

## May help

In Prettier, `isVueEventBindingExpression` depend on [vuejs v2.5 Reg](https://github.com/prettier/prettier/blob/main/src/language-html/syntax-vue.js)

``` js
function isVueEventBindingExpression(eventBindingValue) {
  // https://github.com/vuejs/vue/blob/v2.5.17/src/compiler/codegen/events.js#L3-L4
  // arrow function or anonymous function
  const fnExpRE = /^(?:[\w$]+|\([^)]*\))\s*=>|^function\s*\(/;
  // simple member expression chain (a, a.b, a['b'], a["b"], a[0], a[b])
  const simplePathRE =
    /^[$A-Z_a-z][\w$]*(?:\.[$A-Z_a-z][\w$]*|\['[^']*']|\["[^"]*"]|\[\d+]|\[[$A-Z_a-z][\w$]*])*$/;
  ...
}

```

But it seems to have changed in vue3.

[vue v3 vOn](https://github.com/vuejs/core/blob/f9d43b99f83af7fc140938a1d8d2db89666fb4e1/packages/compiler-core/src/transforms/vOn.ts)

[vue v3 isMemberExpression](https://github.com/vuejs/core/blob/f9d43b99f83af7fc140938a1d8d2db89666fb4e1/packages/compiler-core/src/utils.ts)

**Comment by fisker** [comment]
PR welcome.

**Comment by onishi-kohei** [comment]
I found the fnExpRE for vue3.
https://github.com/vuejs/core/blob/f9d43b99f83af7fc140938a1d8d2db89666fb4e1/packages/compiler-core/src/transforms/vOn.ts#L19-L21

**Comment by yangyile1990** [comment]
same problem.
https://github.com/prettier/prettier/issues/16707
waiting for someone can fix this. 
thank you.
