### ISSUE TITLE
Adding whitespace causes incorrect comment relocation and copying within function args

### ISSUE THREAD

**Issue by dikaiosune** [prettier/prettier#1366]
EDIT: I forgot my manners! Prettier is fantastic and has saved me huge amounts of time, thanks so much! Hopefully this is an easy fix that I might be able to help with.

It looks like for certain inputs, prettier 1.2.2 will incorrectly relocate block comments that trail a function argument. More fun, adding `// prettier-ignore` will cause the comments to be copied, instead of moved.

Here are a number of repros:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20NO%20WHITESPACE%2C%20COMMENT%20IS%20PRESERVED%5Cn%5Cnclass%20Foo%20%7B%5Cn%20%20constructor(lol%20%2F*%3Astring*%2F)%20%7B%7D%5Cn%7D%5Cn%5Cn%2F%2F%20FIRST%20CASE%2C%20TRAILING%20COMMENT%20MOVED%20BY%20ADDING%20A%20SINGLE%20LINEBREAK%5Cn%5Cnclass%20Foo%20%7B%5Cn%20%20constructor(lol%20%2F*%3Astring*%2F%5Cn%20%20)%20%7B%7D%5Cn%7D%5Cn%5Cn%2F%2F%20SECOND%20CASE%2C%20ADDING%20PRETTIER-IGNORE%20MAKES%20TRAILING%20COMMENT%20**COPIED**%5Cn%5Cnclass%20Foo%20%7B%5Cn%20%20%2F%2F%20prettier-ignore%5Cn%20%20constructor(lol%20%2F*%3Astring*%2F%5Cn%20%20)%20%7B%7D%5Cn%7D%5Cn%5Cn%2F%2F%20THIRD%20CASE%2C%20DEMO'ING%20WHY%20YOU'D%20EVER%20HAVE%20THIS%20INPUT%20IN%20PRACTICE%5Cn%5Cnclass%20Foo%20%7B%5Cn%20%20%2F%2F%20prettier-ignore%5Cn%20%20constructor(%5Cn%20%20%20%20lol%20%2F*%3Astring*%2F%2C%5Cn%20%20%20%20lol2%20%2F*%3Astring*%2F%2C%5Cn%20%20%20%20lol3%20%2F*%3Astring*%2F%2C%5Cn%20%20%20%20lol4%20%2F*%3Astring*%2F%5Cn%20%20)%20%7B%7D%5Cn%7D%5Cn%5Cn%2F%2F%20FOURTH%20CASE%2C%20DEMO'ING%20THE%20EFFECT%20OF%20SUBSEQUENT%20SAVES%5Cn%5Cnclass%20Foo%20%7B%5Cn%20%20%2F%2F%20prettier-ignore%5Cn%20%20constructor(%5Cn%20%20%20%20lol%20%2F*%3Astring*%2F%2C%5Cn%20%20%20%20lol2%20%2F*%3Astring*%2F%2C%5Cn%20%20%20%20lol3%20%2F*%3Astring*%2F%2C%5Cn%20%20%20%20lol4%20%2F*%3Astring*%2F%5Cn%20%20)%20%7B%7D%20%2F*%3Astring*%2F%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

This unfortunately means that flow's comment syntax is not compatible with the current version of prettier :(

Here's a fun example of what adding `prettier-ignore` does with repeated saves in my editor:

https://www.dropbox.com/s/5p06b77r16pukqn/Screenshot%202017-04-20%2014.30.44.png?dl=0

If anyone could point to some code for a quick PR, I'd definitely be interested in contributing a fix for this (although I appreciate that might take more time for y'all than fixing it).

**Comment by vjeux** [comment]
This has been fixed. Thanks for the report!
