### ISSUE TITLE
Cannot set properties of null (setting 'spaceBefore') YAML ISSUE

### ISSUE THREAD

**Issue by stephenasuncionDEV** [prettier/prettier#13671]
**Environments:**

- Prettier Version: 2.7.1
- Operating System: Windows
- Prettier plugins: @typescript-eslint, @typescript-eslint/parser

**Steps to reproduce:**

Prettier config:
```json
{
  "singleQuote": false,
  "tabWidth": 2,
  "printWidth": 80,
  "semi": true,
  "trailingComma": "all",
  "arrowParens": "always"
}
```

Create a default bug_report.yml file from github.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/73958774/196066452-fc1648df-5a7b-4b1b-8940-80d1823abff6.png)

**Comment by fisker** [comment]
Can you post content of your `bug_report.yml` file?

**Comment by stephenasuncionDEV** [comment]
> 
**bug_report.yml**
```yml
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

**Comment by fisker** [comment]
[Can't reproduce](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKWoEMC2cSABAEICuA5sQE5wAOENMWWuARhOTCQMJ254xXLQZMYxGBGIALOABt6xcgGdiAS3z0aEAG5xWsdTHlFiAcnOH5HBSpKXDuFSvWUocOPYtXsUdKiGAFRBACJeYDTq7HCScsTsVCGGAILEYKa4NMJQACbp0GDqKrG5EVH0MOrQxBAAZsQA7jKCcbGJ1MUAdMFBACrSAEoMOrnkYHDJfgDK8PRqUqLaEGMTbQlwLbrVNEiGAIxdxADi0ovmXZe+WABMR7zy6mAA1rVQFpdXhgDMR9OREHk8mIuQgjXe50+XWuUAALH9PMQ4DQdDRegBRAAe9DgYHg+RiWx2UywaQycCyOXykCgRRKIPK6kq1Xe9SaLQkAE8uEjsbj8ZJpC16DioD0-CF-nQECoZBAYCoSVAAJINXAix5gDimAA0wly+RUkU8UFl8oWQoUSjg2Js6ne3PI2WW7FM+HFWBC4RUzykSgAFPRMvTIFpTEIYPE6oD5GD7Z0oNGaPhBCyAJRIJXEVDEADy0xIAG04F1KEd1PmALqGbNkHSNErZYulo5gGQ6Qh6lS4OpZdTVvy1gBqyNcNWbZeINxuA89QWmKeY9DlHmIgeDsVDQbgEajMbjUATSZTVWgGazOfC2wmRZLk-UAAUV3AAGyz945-O3lsafMADi6fZ31rUh60bYgJyOFQpBeBIwORLsez7YCcxHGgx3eSCpxnXoUgNYwWVwYEaXgTEYCVPD8lwKBOVqSNkQKWAbQkDguAkejiBdN1ZGREsQB1EAIGZaAVGQUAsnrB8shlZAQCIxpcE5USBPYGhcBeHdpgIOAABl7TgZBe3kEoVLUjSYGmeh1PjZAYBocg4AEuB8BiA04FyHTqMochcEoOAADEmBPKpD1k3BuAgfiQBkGB8HkAB1GRjC8KyJmmGUCO2GBOVksAXCi+1GxgB81MoFNDKIkyQAAKxUTFpnjUwAEVyHlAykCMqqrPQ5FZMXZ5QXBKLtHtGB4vUXJI2QP8AAYBOWEp4rU+hZO0LxkX0KKAEdWvgEqhNElBnFQDx3PcqK6B29Q6BK3zyo6yrHJAEp8HUWz7Ke1xD2a3b2s6p6YA4cbJpkZAbgEuzcHUR5D14CB8HukAvAAVii1Q4D6DhDv+gTdAc5U8gQCzIiZGAUjyWZOVMCrjLgABfOmgA)

**Comment by stephenasuncionDEV** [comment]
There must be something wrong with yaml's parser. I remove the all the asterisk symbol and the error went away.

The command I run to check was `prettier --check .` and it gave me the error above.

**Comment by fisker** [comment]
Ah, understand the problem. It's your file a markdown? It's NOT yaml.

**Comment by stephenasuncionDEV** [comment]
> Ah, understand the problem. It's your file a markdown? It's NOT yaml.

Ah yes! Turns out it github templates should be a markdown file not .yml.
I just needed to rename `.yml` to `.md`.

**Comment by fisker** [comment]
Can we close?

**Comment by stephenasuncionDEV** [comment]
> Can we close?

Yep! Thanks
