### ISSUE TITLE
Formatting produces incorrect case statements

### ISSUE THREAD

**Issue by buffet-time** [prettier/prettier#13694]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdG6DOB3AljMACwAIAKGAJwFc4BKY4VKdFggQ0zjIom02IC8Q4gHJKNEcQBkU4lGgBZKplxhBwsdTgjaSJq1YU4ABwA2ATwB0nKABNSbbG3zEA5nBgA5KgFsARnAUAPIAZgBKvJikuLYANMQUbFDu8eJ0tPoYWeh+RmwA1pmsYBxcpDx86gKiaTp6zNlZRmZWNvaOzjBuHt7+gaERfNFxCUnutBkNBjC5cAVFWSWcZLh2cAAexAB81QAMuguGJhbWCO1OLu4wg1Ex8YnJcPGrthsTh1mz81NZryFsVFMMHq03QzRObQcFy6Vxuw3uY3SHxyeUKPwAviBYiAIMYYLhoJhkKA2BQKgAFUkIIkoNimJzmInY3JsMD5DwAZTYPjgABlVnBkP9TJxmYk2ZzjKzVq5kGlsXA+rZXrZeWMqGx3AAxCAUHxsGD45LIEAAmAQLEgQgwHymADqhHwcEwUrAcA51PwuAAbvhzCawJgmSBVpwKDByYlXPqhXTRSAAFaYdYcmWmOAARSoEHgsZFTxAUooYZNfjYAVMluMFFWMDtMRghGQAA5dtjqxBOHbEsYTdXnYFvYLsQBHbPwSO4mmmzAAWigcDgKstRjHuCMkc1MaQwvjnB8uDlWmxKmS6azOcFO7jBZg5frtkbyAATNjKM5TDKAMIQHzbkDOgArJayhwAAKuWNK7gW3o0AAkmssAcmANZ4gAgnYHIwOY6Z5pw6LokAA)

```sh
--parser babel
```

**Input:**

```jsx
		switch (true) {
			case (rows === 'true' && nonMusic === 'true'):
				reply.send(await getNumberOfRows(id, range, true))
				break
			case (rows === 'true'):
				reply.send(await getNumberOfRows(id, range))
				break
			case (index >= 0):
				reply.send(await getRows(id, range, index))
				break
			default:
				reply.send(await getRows(id, range))
				break
		}
```

**Output:**

```jsx
switch (true) {
  case rows === "true" && nonMusic === "true":
    reply.send(await getNumberOfRows(id, range, true));
    break;
  case rows === "true":
    reply.send(await getNumberOfRows(id, range));
    break;
  case index >= 0:
    reply.send(await getRows(id, range, index));
    break;
  default:
    reply.send(await getRows(id, range));
    break;
}

```

**Expected behavior:**
The parentheses in this case are needed or this does not work properly.

This comes from here: https://github.com/buffet-time/APIs/blob/main/src/danielTurcichComApi/main.ts#L36

I currently solved this producing unexpected behavior by adding prettier ignores

**Comment by thorn0** [comment]
> The parentheses in this case are needed or this does not work properly.

It's not the case. These parentheses don't change the behavior of the problem.
