### ISSUE TITLE
Max printWidth not working consistently

### ISSUE THREAD

**Issue by bryceosterhaus** [prettier/prettier#1369]
I have some tests that look like this

```js
  it('this should auto fix the print width, but for some reason it doesnt', done => {
    return;
  })
```

This breaks the 80 column limit, but format doesnt seem to fix it.

[live example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20it('this%20should%20auto%20fix%20the%20print%20width%2C%20but%20for%20some%20reason%20it%20doesnt'%2C%20done%20%3D%3E%20%7B%5Cn%20%20%20%20return%3B%5Cn%20%20%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

Might be related to https://github.com/prettier/prettier/issues/1110

**Comment by vjeux** [comment]
This is actually intentional. Apparently a lot of people allow `it` to expand past 80 columns.

See https://github.com/prettier/prettier/issues/159

**Comment by bryceosterhaus** [comment]
Ah I see, makes sense. Some how didn't see that issue when searching. Thanks!
