### ISSUE TITLE
Markdown: Single-backtick strings over linebreaks

### ISSUE THREAD

**Issue by dbrgn** [prettier/prettier#13723]
**Prettier 2.7.1**

No CLI arguments.

**Input:**

hello.md:

```md
Afterwards clone the repository as usual. (Alternatively, clone with `git clone
-c core.symlinks=true --recursive ...` if you don't want to enable this option
globally.)
```

**Output:**

```markdown
Afterwards clone the repository as usual. (Alternatively, clone with `git clone -c core.symlinks=true --recursive ...` if you don't want to enable this option
globally.)
```

**Expected behavior:**

The linebreaks are horrible.

Variant A: In a text block, single backticks don't necessarily _need_ to be on the same line. It wouldn't be necessary to merge the lines.

```markdown
Afterwards clone the repository as usual. (Alternatively, clone with `git clone
-c core.symlinks=true --recursive ...` if you don't want to enable this option
globally.)
```

Variant B: *If* prettier wants to put the backtick-text on the same line, that would be acceptable, if it would use the shortest possible snippet.

```markdown
Afterwards clone the repository as usual. (Alternatively, clone with `git clone -c core.symlinks=true --recursive ...`
if you don't want to enable this option globally.)
```

Variant C (preferrable to B): Alternatively, a linebreak could be inserted early (before the first backtick), instead of late (after the second backtick).

```markdown
Afterwards clone the repository as usual. (Alternatively, clone with
`git clone -c core.symlinks=true --recursive ...` if you don't want to enable
this option globally.)
```

**Comment by thorn0** [comment]
This has been fixed by #11373, but not yet released.

**Comment by thorn0** [comment]
Duplicate of #11372

**Comment by dbrgn** [comment]
@thorn0 thanks, I searched for backtick-related issues, and didn't spot that one 🙂 Then I guess this issue can be closed.
