### ISSUE TITLE
Don't split nested classes over multiple lines

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#1374]
```
Immutable.Seq
  .Keyed(segments.map(segment => [segment.id, segment]))
  .toOrderedMap(),
```
I would like `Immutable.Seq.Keyed` to be kept together.
![screenshot 2017-04-21 09 37 10](https://cloud.githubusercontent.com/assets/1473433/25269880/71eb8d76-2676-11e7-8ea9-79d941303712.png)

**Comment by vjeux** [comment]
If the first element is capitalized, we may want to inline everything until the first `(` instead of just the first two arguments. Not sure what edge cases we're going to run into.

**Comment by j-f1** [comment]
Actually, I can’t reproduce this anymore:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBJAtugrjAhgIwBs4A6AZTgEcAdKAAjpIGk4BPOAEwAoBnOAc3QIYPEulwAHXgKGw6AXgB8dANp9BwkgEsOAGjrrZMALoBKU7QYkYEAPIAnDnHucAspK6mQukBAkwtaB5kUFx7ewgAdwAFMIRglFwANwgdbxBcHhhkADNcQj4ffHtcMABrOBgyCVKtKH5kGHssOB8OCDBc-MKQOr57GGiSwVwugtaQACseAA8AIRLyyrJcIQAZOrgxnogcCRwAJm2Jmvt+5BB8AlZCaHSJezqYAHUdGAALZAAOAAYfB4gfGeJQkFwecH6SS2PhclCwWhcQ1wI2OPj46C0jWaEx4dX4xAAilgIPBUSA8PhXhwPsgDj4mrgtIQ8QBhCCYUYoKDQaEgLB8AAqBASeXGAF8xUA)

**Input:**
```jsx
Immutable.Seq
  .Keyed(segments.map(segment => [segment.id, segment]))
  .toOrderedMap()
```

**Output:**
```jsx
Immutable.Seq.Keyed(
  segments.map(segment => [segment.id, segment])
).toOrderedMap();

```

Feel free to comment if I’ve missed something.
