### ISSUE TITLE
< symbol  in the Vue's template tag, it can't format the code

### ISSUE THREAD

**Issue by lourain** [prettier/prettier#13741]
![image](https://user-images.githubusercontent.com/26606163/198271622-d6f1416d-741c-4d6d-8d84-20f59ebbc6b5.png)
v2.7.1
In Vue3, if I code like above pic, it can not format the code.  and the  `</div>` show the error  like below pic. I think it has `<` symbol in the `template` tag.
![image](https://user-images.githubusercontent.com/26606163/198273081-76aa450a-cf92-4474-aa6c-c624b9635850.png)

**Comment by fisker** [comment]
Please follow the issue template, otherwise your issue will be closed.
