### ISSUE TITLE
Unnecessarily splitting closing tag when parse vue template

### ISSUE THREAD

**Issue by chengfengfengwang** [prettier/prettier#13743]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWV15QC0MeARgM5m8YATxxwAvMRAY8AJwDmNDtwgwYEDEjIBWAAxYAHpIEwaYANZCyddhghU4OJHjAm64yc9dxJjZs1SsHFzcZCYwohIggOAWgH7eAIw+pH5+AWzsYA447HIyEACuWGSKvHAwvsl+AI4A7t5MFagA9IHpmdm5BYRNLcHlFN1pwbzlTbQMpE2YuARwjCAANCAQWCbQvMigsrnVAAqyCOsoeDjVeELri9wyzmalAMp4GHAAMopwyABmxyWX1+b3WGcijkyBgMjycEWcAw3DgVHsVGebDkeTwcjgADEIDJpKpgcgQHg8moFiAABYwDA4ADqZJo8F4gIydwO9Po9KEBLAvAuIGKcBkMB21zk0k+30hIAAVrx9HdgaIAIp5FTvJBfHA-ECAmQlGQEugQ0lYGSKGDUmhUGBk5AADh0ixNEBK1OuWAJJrgercpMqKvgwuWh0JvHYUDgcLhpJkcD9NBjwrRYvVEsWJQwNFB4MlvAVcGVqvFmslwQtVptSAATIswXgaDhgQBhdTJkBerSkvIlAAqPEOGq1hrgAEkoPZYHcwKaVgBBMd3YSiIslAC+K6AA)

```sh
--parser vue
```

**Input:**

```vue
<template>
  <div>
    <van-tabs style="margin-bottom: 50px" sticky v-model:active="active">
      <van-tab title="标签1">
        <van-cell-group inset>
          qwe
        </van-cell-group></van-tab>
    </van-tabs>
  </div>
</template>

```

**Output:**

```vue
<template>
  <div>
    <van-tabs style="margin-bottom: 50px" sticky v-model:active="active">
      <van-tab title="标签1">
        <van-cell-group inset> qwe </van-cell-group></van-tab
      >
    </van-tabs>
  </div>
</template>

```

**Expected behavior:**
```
<template>
  <div>
    <van-tabs style="margin-bottom: 50px" sticky v-model:active="active">
      <van-tab title="标签1">
        <van-cell-group inset> qwe </van-cell-group>
      </van-tab>
    </van-tabs>
  </div>
</template>
```

**Comment by fisker** [comment]
This happens for a reason and can be controlled with the option `--html-whitespace-sensitivity`. Please read more [here](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting).
