### ISSUE TITLE
Typescript instantiated expressions break with --no-semi option

### ISSUE THREAD

**Issue by alex12058** [prettier/prettier#13785]
Typescript 4.7 added the ability to [instantiate expressions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#instantiation-expressions) with generics. This notation requires a semicolon be placed at the end of the instantiated expression. Currently prettier removes the semicolon which prevents the code from compiling as it is not valid without the semicolon.

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEA5gnAE45gD6qEEAPACoB8AFAM4QC2clAhqYST4GASnzAAOlHwz8pODHSlpHbnwEBuKQF8pkKGxj4YATwAOcACbVa+ALxES5KjXpR0nAEZkmGkABoQCDNcaDZkUH5SCAB3AAV+BHCUXgAbGN4TcMDPUl4wAGsFAGVebgAZHCg4ZFQ0tjgcvMKSs3yqwmQYUnRGkDgvK0srct4oQnReYgAxCFJOXhhcceQQXnQYCACQAAsYTlSAdR2ceDY2sDhipNOcADdTk1WwNmyQKobSGDi8wgXa+p9ABWbAAHsUOqk4ABFdAQeAA1INQJtUifVamCxsMDkELbMzkWCHHCWGA7ZAADgADCjog1DnkzKsCXBPncaoEAI5w+A-YLJNZsAC01SsVm28m5OHkPym-yQdSRfQanBwiORIDYkJhPJqCsBgRgvE8xNJ5KQACZDXkcKkOgBhLjy-psACs23QDQYxuSio1d16AEkoMNYMUcTgQgBBEPFUxQ9VwbTaIA)

```sh
--parser typescript
--no-semi
```

**Input:**

```ts
function generic_foo<T>(some_arg: T) {
    return some_arg;
}
const typed_foo = generic_foo<number>;
```

**Output:**

```ts
function generic_foo<T>(some_arg: T) {
  return some_arg
}
const typed_foo = generic_foo<number>

```

**Expected behavior:**
```ts
function generic_foo<T>(some_arg: T) {
    return some_arg;
}
const typed_foo = generic_foo<number>;
```

**Comment by fisker** [comment]
Can't see the difference https://www.typescriptlang.org/play?ts=4.7.4#code/GYVwdgxgLglg9mABAcwKZlQJxhA+sOOAHgBUA+ACgGc4BbVXAQ02QC5ESBKRAbwFgAUImGJMqKCExIa9Ji0EBfQRARUoiKAE8ADqgAm+QgEZEAXhTosOQ8TAhaAIyxlBy1eq26DBOACYzFhjYeD5Edo7OANyCQA

**Comment by alex12058** [comment]
@fisker Seems to be a problem if it is followed by a namespace or class declaration
https://www.typescriptlang.org/play?ts=4.7.4#code/GYVwdgxgLglg9mABAcwKZlQJxhA+sOOAHgBUA+ACgGc4BbVXAQ02QC5ESBKRAbwFgAUImGJMqKCExIa9Ji0EBfQRARUoiKAE8ADqgAm+QgEZEAXhTosOQ8TAhaAIyxllAG0ZUqiAMLvPAQR4lARUwNQ0dfRsAJjMLDGw8Alt7J0wyAG43Dy9fHIAhIMEgA

**Comment by fisker** [comment]
It seems to be a bug in typescript, maybe already fixed https://www.typescriptlang.org/play?ts=4.8.4#code/GYVwdgxgLglg9mABAcwKZlQJxhA+sOOAHgBUA+ACgGc4BbVXAQ02QC5ESBKRAbwFgAUImGJMqKCExIa9Ji0EBfQRARUoiKAE8ADqgAm+QgEZEAXhTosOQ8TAhaAIyxllAG0ZUqiAMLvPAQR4lARUwNQ0dfRsAJjMLDGw8Alt7J0wyAG43Dy9fHIAhIMEgA

Note: playground version is different than the link above.

**Comment by alex12058** [comment]
Thanks @fisker, closing this issue.
