### ISSUE TITLE
Prettier don't wrap html classes with specific PrintWidth

### ISSUE THREAD

**Issue by 50l3r** [prettier/prettier#13789]
Hi guys,

I have a problem with PrintWidth with prettier cli directly. It applies some rules for my code but i cant wrap my classes when exceds 80 chars.

Can anybody help me? Much thanks 😁

**Prettier 2.7.1**

**.prettierrc:**

```jsx
{
    "printWidth": 80,
    "tabWidth": 4,
    "useTabs": false,
    "semi": false,
    "quoteProps": "consistent",
    "singleQuote": true,
    "bracketSpacing": true,
    "arrowParens": "always",
    "vueIndentScriptAndStyle": true,
    "singleAttributePerLine": false,
    "endOfLine": "lf",
    "trailingComma": "none"
}
```

**Input:**

```sh
npx prettier .\src\components\user-actions\v-button\v-button.vue --config .\.prettierrc
```

**Expected behavior:**
```vue
<template>
    <button
        class="rounded-full 
            bg-primary 
            bg-gradient-to-r 
            py-3 
            px-8 
            font-semibold 
            text-white 
            duration-100 
            ease-in 
            hover:scale-105"
        :class="buttonClasses"
    >
        LOREM IPSUM
    </button>
</template>

<script lang="ts">
    import { computed, defineComponent } from 'vue'

    export default defineComponent({
        name: 'VButton',
        props: {
            inverse: {
                type: Boolean,
                default: false
            }
        },
        setup(props) {
            ...
        }
    })
</script>

<style scoped lang="scss"></style>
```

**Output:**
```vue
<template>
    <button
        class="rounded-full bg-primary bg-gradient-to-r py-3 px-8 font-semibold text-white duration-100 ease-in hover:scale-105"
        :class="buttonClasses"
    >
        LOREM IPSUM
    </button>
</template>

<script lang="ts">
    import { computed, defineComponent } from 'vue'

    export default defineComponent({
        name: 'VButton',
        props: {
            inverse: {
                type: Boolean,
                default: false
            }
        },
        setup(props) {
            ...
        }
    })
</script>
```

**Comment by barthony** [comment]
Hello,
same issue for me since yesterday for no apparent reason
I'm using vscode with the prettier extension
printWidth set to 200 but prettier is formating ts code like it was set to 80

**Comment by kachkaev** [comment]
👋 @50l3r! This is expected behavior, see:
- https://prettier.io/blog/2021/11/25/2.5.0.html#collapse-html-class-attributes-onto-one-line-11827httpsgithubcomprettierprettierpull11827-by-jlongsterhttpsgithubcomjlongster

- https://github.com/prettier/prettier/issues/10918

- https://github.com/prettier/prettier/issues/7863

**Comment by kachkaev** [comment]
If you need to open another issue in the future, please follow [the issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1). This helps triage and reproduce potential bugs.

**Comment by 50l3r** [comment]
> If you need to open another issue in the future, please follow [the issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1). This helps triage and reproduce potential bugs.

I follow the issue template.

Thanks. I'l revert to 2.4 to improve my tailwind classes.
