### ISSUE TITLE
运行npx mrm@2 lint-staged命令之后在我的目录创建了一个6.md文件啥问题

### ISSUE THREAD

**Issue by happy-sw** [prettier/prettier#13780]
安装prettier,然后要解决eslint和prettier的冲突，就安装了 npx mrm@2 lint-staged，结果莫名其妙的在我的根目录下面出现了个6.md
文件，简直离了个大谱。这个文件里面的内容是，
added 44 packages, and audited 1502 packages in 17s

243 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
太奇怪了，不知道能不能删掉啊

**Comment by fisker** [comment]
Not related to Prettier.
