### ISSUE TITLE
Prettier clashing with eslint unicorn

### ISSUE THREAD

**Issue by DaSchTour** [prettier/prettier#13791]
Following up on this issue #5158 I have conflicting rules from prettier and eslint which both have auto-formatting which leads to formatting in the one and the other direction with each format.

The eslint rule in question is this one https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/number-literal-case.md and there are good reasons to use it. But together with prettier it is not possible to use this rule.

So I hope there could be either an option in prettier or prettier could ignore numeric literals.

**Comment by kachkaev** [comment]
These clashes are resolve the other way around. If there is a conflicting ESLint rule, [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier) is added. Doing so will address your issue:
https://github.com/prettier/eslint-config-prettier/blob/7c0eea65da47e24e101930b37ac3b36f10ccb54f/index.js#L145

**Comment by DaSchTour** [comment]
@kachkaev what the hell!? That's crazy shit. I didn't think that prettier is interfering that deep into other tools. That's scary.
