### ISSUE TITLE
Ternary as return value of arrow function is being wrapped in parens

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#1379]
```js
const x = (x) => asoudhsaoduhsaoudasdsiaudhsaduhs ? asdaosuhdosauhdu : asdsahdousahdousahduosa
```
gets formatted as
```js
const x = x =>
  (asoudhsaoduhsaoudasdsiaudhsaduhs
    ? asdaosuhdosauhdu
    : asdsahdousahdousahduosa);
```
But there is no need for these parens.
I'd be happy with either of:
```js
const x = x => asoudhsaoduhsaoudasdsiaudhsaduhs
  ? asdaosuhdosauhdu
  : asdsahdousahdousahduosa;
```
or
```js
const x = x =>
  asoudhsaoduhsaoudasdsiaudhsaduhs
    ? asdaosuhdosauhdu
    : asdsahdousahdousahduosa;
```
as output

**Comment by lydell** [comment]
For reference, this was added in #1182.

**Comment by xixixao** [comment]
@vjeux We discussed this internally before and the ESLint rule was disabled.

I just realized this is consistent with the JSX wrapping (which itself is consistent with variable assignment, both of which I think are unnecessary but there wasn't consensus on that).

**Comment by vjeux** [comment]
We should probably only add parenthesis if it doesn't break and could be confusing. If it breaks, it's clear that it's not confusing.
