### ISSUE TITLE
comment before jsx closing tag with jsxBracketSameLine enabled

### ISSUE THREAD

**Issue by montemishkin** [prettier/prettier#1380]
I stumbled across this one yesterday.  Only an issue when jsxBracketSameLine is enabled:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20x%20%3D%20(%5Cn%20%20%3Cdiv%5Cn%20%20%5Ctattr1%3D%7B1%7D%5Cn%20%20%5Ctattr2%3D%7B2%7D%5Cn%20%20%5Ct%2F%2F%20attr3%3D%7B3%7D%5Cn%20%20%3E%5Cn%20%20%5Ct%7Bchildren%7D%5Cn%20%20%3C%2Fdiv%3E%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Note that it changes the placement of the comment to be a child of the jsx element, so (depending on what component is being rendered) it might actually render the comment into the DOM.

This one crops up when I comment out attributes while testing some code, but I can't really think of any situation where I would format my final solution this way.

Not super high priority (to me personally) to have this fixed btw.

**Comment by vjeux** [comment]
Good catch!
