### ISSUE TITLE
Please add support for Mermaid syntax

### ISSUE THREAD

**Issue by difosfor** [prettier/prettier#13821]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAWTgJwLYCGAlgCboAqcAzjADpT0AGzeuhp9VcAjgK4Jg4AESIEA5jgJ566WegAOBHDCJgii2OgCCAG1VwZcxctXqCmgEIQARodm796ALQA+F1etJ0ACSLoPdv42ri7aeoJevmH6TMz0IAA0IBDyKtBUyKBKOBAA7gAKSggZKAQ6uQQAnhlJ1pJgANZwMADKUnAAMkRQcMgAZmVctfVNrYpqUGLIMDj8SXB41nAkJMsd5mK84nAAYhD4BDAqk8ggBLwwEIkgABYweDoA6jdE8FTjcC3Fr0QAbq+VU5gKg1EDdLjKfKSMSEfqDOBJABWVAAHi1umIdHAAIq8CDwOE6IYgYwQ06EHANEh5KDXeQ4bowR6kGA3ZAADgADEl6RAuI9JPJTvTqLhfr0knx8XAoSkSmcqE4estltccDxeER1VDxLCkAMiQiQFw8ERprMjVQMVjcdLCcSYARrMySKzkAAmJIzYh6SYAYQgeD1IGoAFZrrwuOQnSUDcTfvwAJJQVawFpgBmpLQplowSpY+1wAC+RaAA)

```sh
--parser markdown
```

**Input:**

````markdown
# Mermaid Test

```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice ->>Bob: Hi Bob
    Bob->> Alice: Hi Alice
```
````

**Output:**

````markdown
# Mermaid Test

```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice ->>Bob: Hi Bob
    Bob->> Alice: Hi Alice
```
````

**Expected behavior:**

[Mermaid](https://mermaid-js.github.io/mermaid/) syntax formatting support, e.g: making the spacing around the activation arrows consistent. For example, like so with the above Mermaid snippet in Markdown:

````markdown
# Mermaid Test

```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice ->> Bob: Hi Bob
    Bob ->> Alice: Hi Alice
```
````

I've just started using this and miss the comfort of Prettier taking care of formatting for me. Mermaid seems to be a widely supported syntax with GitHub for example supporting it out of the box in Markdown file previews, so I guess it's pretty widely used as well.

**Comment by kachkaev** [comment]
This can be implemented as a [Prettier plugin](https://prettier.io/docs/en/plugins.html#official-plugins). You can ask someone from Mermaid community to implement one.

**Comment by difosfor** [comment]
Ah, right, thanks for the pointers and the great work in general! 😊
