### ISSUE TITLE
arrow function multi-line switch whitespace does not accumulate

### ISSUE THREAD

**Issue by ArtoriaSAMA** [prettier/prettier#13823]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKcAeAHCAnGAAkigGciw84BDeAETkj1v0IF51DCAzKdgPk5dCACgB0E6ngDmpAIwBKAUOGiYU6XBhJC1KAE8ANIQDWcfTvJ4AllGmEAPoVL6AtgCMIAG2MATOKSU1tgw+DoACngQ2HAE+gyBNiH4Smz8hMAqhFlcAL4A3OgghiDRMNbQpMigUlEA7uFSCFUo1ABuENa+xSDuzGBmMADK1K5wADK2cMjc1F6kcCV91ANaQ9grttLIMHgArosgcB5wvv6+43rSe9SaAGL4rrTldsgg1HuhPQAWMK5eAHVvtZ4KQNmA4ENmiDrG0Qfo3mBSFUSrYFgRIrcnjM5gsSgArUiYIZbLxwACKewg8Bx80OGzw6LeMH0MUSwRgPWwNlgAK6MG+yDkACYAAwlbkQBYA5jYN7cgKxNrTEoARyp8Ei0Ra71IAFoMKdTj0qOrrFRMdJsUhZnSSgtXNYdvtDqRSRSNdMbbjDrtqNYvFsAMIQVzWkBQaAqkB7BYAFWo7hatrxIDaBwAklB-LAhkEQgBBbNDFlk2mpwmYABC-UGIzGkww5d9ib5vgFyGFuVyQA)

```sh
--parser typescript
--print-width 120
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx

export const createDecorator =
  fn =>
    (...args1) =>
      (target: any, key: string | symbol, descriptor: PropertyDescriptor) => {
    
      };

```

**Output:**

```tsx
export const createDecorator =
  fn =>
  (...args1) =>
  (target: any, key: string | symbol, descriptor: PropertyDescriptor) => {};

```

**Expected behavior:**
```typescript
export const createDecorator =
  fn =>
    (...args1) =>
      (target: any, key: string | symbol, descriptor: PropertyDescriptor) => { };
```

**Comment by thorn0** [comment]
This is intended. Binary expressions are formatted the same way. Adding an extra indentation for each nested arrow function doesn't add any value.
