### ISSUE TITLE
Single quote turns to double-quotes when another single-quote is in the middle

### ISSUE THREAD

**Issue by noamlin** [prettier/prettier#13850]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT5f6RQDOMfPAAeggLz4A5DAAWOPvj4yI6emzaTY+AEZx8Ad2oBDAA4m4dAzln46K7ST0BHdBHh9JAbg7ce0AUJwogBM+BKS1uqSCqg4whb40CQAngYyCPhG+Gwg+PKZJHwQ+CbUcHwIMF4cAL4gADQgECa4-sigRtTUEPoACp0IfMggRiT6RslDjdrGYADWcDAAykYAtnAAMjhQcMiooxXTswvLJkZg2wDmyDDU6HCNcKu6dHQWG0ZQl+hGl3AAYjRVkYYLgvsMjOgYBAGiAZDBViQKHJ3GcwHAloNrDgAG7WZLDMB8KYgbYVagwXrGS7AvYHB4gABWfGESyujgAiq54HTCgyztRycNtEZdCRYaVtjAKDg6LJkAAOAAMjVKEAqFGMJmGpXKcGoON2jRcbjgVOaQxQRj4AFodhYLLCyi4cGUqb9aUh9nzGhVVjgbncGXx2XAuabA-dGjBRTK5TJkMFo8YcCQrgBhCCrT0gcoAVlh6AqABVRZbvYcQDj7gBJKBvWBLMDUHAtACC9aWMGSjl5FRqNSAA)

```sh
--parser babel
--single-quote
```

**Input:**

```jsx
function HelloWorld() {
    const text = 'this should\'nt be wrapped with double quotes';
    const text2 = 'it\'s fixed only when a " is also present';
}
```

**Output:**

```jsx
function HelloWorld() {
  const text = "this should'nt be wrapped with double quotes";
  const text2 = 'it\'s fixed only when a " is also present';
}

```

**Expected behavior:**
When we set the --single-quote option, it should always use single quotes or else it conflicts with other tools, like eslint.

**Comment by kachkaev** [comment]
Hi @noamlin! This is expected behavior:
https://prettier.io/docs/en/options.html#quotes

> If the number of quotes outweighs the other quote, the quote which is less used will be used to format the string - Example: `"I'm double quoted"` results in `"I'm double quoted"` and `"This \"example\" is single quoted"` results in `'This "example" is single quoted'`.
