### ISSUE TITLE
any plan about  upgrading the TS parser  "@typescript-eslint/typescript-estree"  ?    there an error when prettier  parsering  " satisfies" which is a new ts  feature  mentioned by ts 4.9RC

### ISSUE THREAD

**Issue by JokerDr** [prettier/prettier#13857]
"typescript-estree" already supported the  feature "satisfies" ，so, any upgrading plan here ？ 
  
![image](https://user-images.githubusercontent.com/19502359/202683488-ba3f1aa9-d81d-4046-9171-75b32c6324fe.png)

  
![image](https://user-images.githubusercontent.com/19502359/202681651-c83409fa-b7a7-4943-ae44-279a1eaa0bb3.png)

**Comment by fisker** [comment]
https://github.com/prettier/prettier/issues/13516
