### ISSUE TITLE
Bug: Separate comments are put onto one line for type "Number | void"

### ISSUE THREAD

**Issue by jameshfisher** [prettier/prettier#13858]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAQgVQOJIZwBucATgJ4wAWAllAOYYNwwDOGb1EpAJhtBgQBUOBgA29OABoM9MOICuvek0gBbdQnYAdWBQAOYgGIQIWAIZkMAXgx6MGAD4YAcovUAjchnQYatBy8EGAe2hw0YgBmtGRsMAIGMLTQDs4YxBC0-H4BQSFhsBHUYmxwkFD8EEkpUGkA3Hp6fgDqEGQA1hwWHHAAHkZg8Lx6MIYmZpbWdmku8WSqvph5GMGhWkX+JRgxcQnVyalQji6Z2UtbgasFG+xbpeXQVTVHjo11UK3tXRg9RAPlYajcYYUzmKy2ezHdLzRa5Oj5dbhe47WLxRKHD4nDBQDzeazwq5rQp3SKcR6VDG1BogaQgA61NjIUBWMgQADuAAUrAgmSgLOJ2RYKEy6Z4yBYwB1WABlCxaAAyUmQUQFZTFEqlsoMktUyBgZEUMhAcC8cF4vHNCosjEUFhYpjI6gsMGSjGQIAsiiEtJA1Bg6nELTo8DYOrAcBlvNoyWIMYoHrAbFFIHoZTIME5EoYzpVauNACs2H0ZapxHAAIqKCDwPPidUgHVxcgesZGNhgBZJX0GBawFrZGjIAAcAAY6b2IGUWhKDB7e3B06RfQBHavwLPVPmetgAWlE5vNvrIcDXsTgWftuaQqvrxrK6lo+sN97LlfXcDrDZgFk8A94Q5IAATHSBoWLQkiMAAwhAmgWB6i4AKy+ooZQACq-nyt4NsQRoAJKVNoMqdrQSQAIKVDKYzll+cAAL50UAA)

```sh
--parser typescript
```

**Input:**

```tsx
// BUG: everything gets shoved onto one line, including comments
type FooBar = 
  | Number // this documents the first option
  | void // this documents the second option
  ;

// Works as expected
type FooBar = 
  | string // this documents the first option
  | void // this documents the second option
  ;

// Works as expected
type FooBar = 
  | string // this documents the first option
  | number // this documents the second option
  ;
```

**Output:**

```tsx
// BUG: everything gets shoved onto one line, including comments
type FooBar = Number | void; // this documents the first option // this documents the second option

// Works as expected
type FooBar =
  | string // this documents the first option
  | void; // this documents the second option

// Works as expected
type FooBar =
  | string // this documents the first option
  | number; // this documents the second option

```

**Expected behavior:**

```tsx
type FooBar = 
  | Number // this documents the first option
  | void // this documents the second option
  ;
```

**Comment by thorn0** [comment]
closed by https://github.com/prettier/prettier/pull/13860
