### ISSUE TITLE
Expression expected error on logical operator after checking if instanceof GenericClass<T>

### ISSUE THREAD

**Issue by lucasrabiec** [prettier/prettier#13856]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAMQggB4AVAPj2AB0oBfd9gMwFcoYGAEtoeUsQC2GQnAAUcbNhxI8AgNZQIAdygBKFuzx5hPPHICECpThNRSMYoLgQz1OgHJSESXAC0MACeGHAezAA+4XiKyth2Dk5gLmYAojbYBpF4FjE4AHS+5MQA5nAGbFDGxthwMHzYlV4+tQAWwlDFHgDcRnhcnCAANCAQGCLQpMigxDbaAAozCJMoxITaxIGTwwBG2MRg6rUAylJwADLtcMg8q6RwO3sHxxj77cXIMNh896iS23AAEwBgLOTmKfBKcGo2EkxBgIg6yBAxD4MAgQxALRgkkIAHU2vBSC8kkclsIRAA3cmBJFgcgY9p3XBzPbFWHXW4-ABWpDQRzesgAinwIPAOYQ7sMXtgmUigiFSGBsMIxhiMMrYLjhACYC1kAAOAAMUuUd1xewwSPVcCZFKuwwAjiL4CzRstkaQ-FA4IDARiak7hDUWSV2UgbhKfndJMIPl8owK4MLRVdw5zho5tlqdXqkAAmDN7YSEN4AYR8YdQpAArBi+Hd6MRtssI5KQBTvgBJKDA2BHJUqmAAQR7RyCsnFdw4HCAA)

```sh
--parser typescript
```

**Input:**

```tsx
export class Foo<T> {
}

function sample(error: unknown) {
  if (!(error instanceof Foo<'some-type'> || error instanceof Error) || !error.message) {
    return 'something';
  }
}
```

**Output:**

```tsx
SyntaxError: Expression expected. (5:43)
  3 |
  4 | function sample(error: unknown) {
> 5 |   if (!(error instanceof Foo<'some-type'> || error instanceof Error) || !error.message) {
    |                                           ^
  6 |     return 'something';
  7 |   }
  8 | }
```

**Expected behavior:**

```ts
  3 |
  4 | function sample(error: unknown) {
  5 |   if (
  6 |     !(error instanceof Foo<'some-type'> || error instanceof Error) ||
  7 |     !error.message
  8 |   ) {
  6 |     return 'something'
  7 |   }
  8 | }
```
~It works if I wrap Foo<'some-type'> with parentheses and then prettier formats it like expected behavior (also removes `( )`) but I think it should work without wrapping.~ edit: problem occured again on reformat (obviously)

It works if I split that logical OR into separate statements (I know this is not logically the same as above, just for an example)
```ts
!(error instanceof Foo<'some-type'>) ||
!(error instanceof Error) ||
!error.message
```

**Comment by fisker** [comment]
Not sure when it's fixed, but [works in main branch](https://deploy-preview-13854--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAMQggB4AVAPj2AB0oBfd9gMwFcoYGAEtoeUsQC2GQnAAUcbNhxI8AgNZQIAdygBKFuzx5hPPHICECpThNRSMYoLgQz1OgHJSESXAC0MACeGHAezAA+4XiKyth2Dk5gLmYAojbYBpF4FjE4AHS+5MQA5nAGbFDGxthwMHzYlV4+tQAWwlDFHgDcRnhcnCAANCAQGCLQpMigxDbaAAozCJMoxITaxIGTwwBG2MRg6rUAylJwADLtcMg8q6RwO3sHxxj77cXIMNh896iS23AAEwBgLOTmKfBKcGo2EkxBgIg6yBAxD4MAgQxALRgkkIAHU2vBSC8kkclsIRAA3cmBJFgcgY9p3XBzPbFWHXW4-ABWpDQRzesgAinwIPAOYQ7sMXtgmUigiFSGBsMIxhiMMrYLjhACYC1kAAOAAMUuUd1xewwSPVcCZFKuwwAjiL4CzRstkaQ-FA4IDARiak7hDUWSV2UgbhKfndJMIPl8owK4MLRVdw5zho5tlqdXqkAAmDN7YSEN4AYR8YdQpAArBi+Hd6MRtssI5KQBTvgBJKDA2BHJUqmAAQR7RyCsnFdw4HCAA).

**Comment by lucasrabiec** [comment]
@fisker, great! Do you know when it will be released?

**Comment by fisker** [comment]
Very soon, https://github.com/prettier/prettier/issues/13792

**Comment by fisker** [comment]
Would like to add a test for it?

**Comment by lucasrabiec** [comment]
Yes, I can give it a try. Is `tests/format/typescript/generic` the correct place for that test?

**Comment by fisker** [comment]
Maybe `tests/format/typescript/logical-expression` is a better place.

**Comment by thorn0** [comment]
Expressions like `Foo<'some-type'>` are called instantiation expressions, so the place for the test is `tests\format\typescript\instantiation-expression`

**Comment by fisker** [comment]
Reopen to track test.

**Comment by lucasrabiec** [comment]
@fisker I added test: https://github.com/prettier/prettier/pull/13897
