### ISSUE TITLE
Wrong semicolon on semi = false mode

### ISSUE THREAD

**Issue by vinhlh** [prettier/prettier#1388]
From
```js
  it('should blah blah', () => {
    [
      'vinh',
    ].forEach(t => {
      expect(convertRawToIds(t)).toEqual([
        'vinh'
      ])
    })
  })
```
To
```js
it('should blah blah', () => {
  ;['vinh'].forEach(t => {
    expect(convertRawToIds(t)).toEqual(['vinh'])
  })
})
```
https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20it('should%20blah%20blah'%2C%20()%20%3D%3E%20%7B%5Cn%20%20%20%20%5B%5Cn%20%20%20%20%20%20'vinh'%2C%5Cn%20%20%20%20%5D.forEach(t%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20expect(convertRawToIds(t)).toEqual(%5B%5Cn%20%20%20%20%20%20%20%20'vinh'%5Cn%20%20%20%20%20%20%5D)%5Cn%20%20%20%20%7D)%5Cn%20%20%7D)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by lydell** [comment]
This is on purpose. Here’s a comment that sparked the idea: https://github.com/prettier/prettier/issues/736#issuecomment-291934981

**Comment by viankakrisna** [comment]
is it necessary to have semicolon right after opening brace?

**Comment by lydell** [comment]
The semicolon in your example is technically not needed **– right now.** But when you add a new line it is:

```diff
 it('should blah blah', () => {
+  console.log('is this test even running??')
   ['vinh'].forEach(t => {
     expect(convertRawToIds(t)).toEqual(['vinh'])
   })
 })
```

When you now run the tests you will be greeted by `TypeError: Cannot read property 'vinh' of undefined`. Or, if you’re lucky, you notice what prettier did to your code before running the tests:

```js
it('should blah blah', () => {
  console.log('is this test even running??')['vinh'].forEach(t => {
    expect(convertRawToIds(t)).toEqual(['vinh'])
  })
})
```

Luckily, Prettier prints that “unnecessary” semicolon so you don’t have to think about them and won’t fall into frustrating traps. :)

**Comment by vinhlh** [comment]
Could you explain more about how the compiler works in this case? @lydell 
http://astexplorer.net/#/gist/d6561f6a60b5ae5a0d53a4f9731a9c5b/76d8a6bd0bb48a46e9982b36a0532e5f479d3820
Without semicolon, `console.log('is this test even running??')` can not be understood as a `CallExpression`.

**Comment by lydell** [comment]
Sorry, I don’t understand what you mean.

**Comment by vinhlh** [comment]
@lydell the problem was that I misunderstood how semicolon is inserted automatically:
http://www.ecma-international.org/ecma-262/7.0/index.html#sec-rules-of-automatic-semicolon-insertion
