### ISSUE TITLE
Revert adding spaces in Angular Pipes

### ISSUE THREAD

**Issue by ghost** [prettier/prettier#13887]
**Prettier 2.8.0**
Prettier 2.8.0 "fixes" issue https://github.com/prettier/prettier/issues/13058
But it was not thoroughly discussed. I think it was not discussed at all in the Angular Repository. Opinions of a few Taiga UI users should not overweight all the examples in the official Angular documentation, where pipes are separated with spaces, and pipe arguments stand close to pipe names.

Reference:
https://angular.io/guide/pipes-transform-data
https://angular.io/api/common/CurrencyPipe#usage-notes

**Input:**
```html
{{ (user$ | async).credit | currency:'CAD':'symbol-narrow':'4.2-2' }}
{{ (user$ | async).items | slice:1:5 }}
```

**Output:**
```html
{{ (user$ | async).credit | currency : 'CAD' : 'symbol-narrow' : '4.2-2' }}
{{ (user$ | async).items | slice : 1 : 5 }}
```

**Expected behavior:**
```html
{{ (user$ | async).credit | currency:'CAD':'symbol-narrow':'4.2-2' }}
{{ (user$ | async).items | slice:1:5 }}
```

Also, Webstorm displays names of arguments, and it does not look as good with additional spaces:
![image](https://user-images.githubusercontent.com/47851128/203520853-d4efe2e3-fdde-401d-b7ee-1b62550e7b65.png)

As a compromise, I suggest not adding spaces if a pipe argument is a string or a number, but add spaces in all other cases.
Expected behavior:
```html
{{ (user$ | async).credit | currency:'CAD':'symbol-narrow':'4.2-2' }}
{{ (user$ | async).items | slice:1:5 }}
{{ chart | tuiFilter : filter : range | tuiMapper : toNumbers : range }}
```

**Comment by waterplea** [comment]
Previous Prettier version formatted it with a space after first `:` which is also inconsistent with Angular docs. How do you propose to have a discussion? [Angular style guide](https://angular.io/guide/styleguide) has nothing on the matter, [angular.io](https://angular.io) has plenty of examples that go against prettier formatting, so does angular source code:
```html
{{ model | json }}
<div class="form-group">
  <label for="name">Name</label>
  <input type="text" class="form-control" id="name"
         required
         [(ngModel)]="model.name" name="name">
</div>

<div class="form-group">
  <label for="alterEgo">Alter Ego</label>
  <input type="text"  class="form-control" id="alterEgo"
         [(ngModel)]="model.alterEgo" name="alterEgo">
</div>

<div class="form-group">
  <label for="power">Hero Power</label>
  <select class="form-control"  id="power"
          required
          [(ngModel)]="model.power" name="power">
    <option *ngFor="let pow of powers" [value]="pow">{{pow}}</option>
  </select>
</div>
```
There are a couple of cases with spaces in the docs, but majority indeed use no spaces at all. I have never heard of the standard or official code style regarding this though.

**Comment by waterplea** [comment]
So I've managed to get a little over 500 votes on the matter, with help of other Angular devs retweets. The distribution pretty much settled around 60/40 in favor of current formatting rather early on and fluctuated around 1%, so I believe it should be fair to extrapolate the result as indicative of general public opinion.

**Comment by nedecoTHo** [comment]
Just updated to latest prettier version and was shocked. 
I instantly thought it looks like the result part of a conditional ternary operator. And not a key - value pair anymore.

Wouldn't it be a possibility to be able to turn this off via config?
Would be the easiest fix IMO for this minor version.


What I would add to the discussion featurewise:

Our preferred approach looks like this: 

```
{{ (user$ | async).credit | currency: 'CAD' : 'symbol-narrow' : '4.2-2' }}
{{ (user$ | async).items | slice: 1 : 5 }}
```

So basically, the first value after the pipe (pipe name) does NOT have a space between itself and the colon at all times, but after that, there are spaces between the arguments.

**Comment by waterplea** [comment]
Previously mentioned survey was comparing new format with Angular documentation format. We can probably try running one more, comparing different proposed formats. So far 4 formats were proposed:

1. Angular docs one: `value | pipe:arg1:arg2`
2. Old prettier: `value | pipe: arg1:arg2`
3. New prettier: `value | pipe : arg1 : arg2`
4. Alternative: `value | pipe: arg1 : arg2`

@nseni @sosukesuzuki @nedecoTHo @pedroestabruxelles @fisker would that be a way forward you agree upon? Anything else to add, any other idea?

**Comment by ilyakonrad** [comment]
If you take `translate` or `date` pipe as an example, it looks much better the old way:

`'translation.key' | translate: { group: organization.name }`
`lastYearDate | date: DateFormat.shortDate`


So I would vote for option 2.

**Comment by HyperLife1119** [comment]
I can accept options two and four but not options one and three.

**Comment by nedecoTHo** [comment]
Same here, as @HyperLife1119 said I like options two and four. Thanks for asking!

**Comment by pedroestabruxelles** [comment]
I prefer 2 as default, 4 as optional.

**Comment by Splaktar** [comment]
I prefer 1 or 2. I vote for reverting this change which has caused confusion across multiple projects for my teams.

**Comment by waterplea** [comment]
I have created another poll with all proposed options, sorted by the amount of spaces they use. If this question is important to you, please cast you vote and help with reach:
https://twitter.com/Waterplea/status/1615568765747597313

**Comment by nseni** [comment]
The poll has ended. 421 people voted.
![image](https://user-images.githubusercontent.com/47851128/214026996-e686b8ad-efa4-4af7-9125-66b754051359.png)

It's interesting that the "Old prettier" formatting has the least votes, so a change to formatting is indeed needed.
Note that majority (68,9%) voted not in favor of the new formatting. But option "Angular docs" has won only by a small margin. So it's not not conclusive. I don't know, could the "Alternative" formatting become a compromise? Or simply accept the poll results and implement the option with the most votes.

**Comment by Splaktar** [comment]
> I wouldn't say a vote on twitter is more representative

I'd agree with this, especially after a significant exodus or at least the deactivation of many people's Twitter accounts due to Elon.

Either way, there's significant feedback that the recently implemented formatting is not desirable.

**Comment by nedecoTHo** [comment]
If I understood correctly, no one in this thread really prefers this:
`value | pipeName:'string_value':1.2:value`
over this:
`value | pipeName : 'string_value' : 1.2 : value`

This twitter poll got that back into discussion, but I upvoted @ilyakonrad in this regard because IMO he is right.

After getting a bit more used to the new "all spaces in pipes" approach, I would still prefer the 4th option, but am also fine with the 3rd (from your post above, quoted below).

If easily possible, I would prefer the 3rd format as a new standard and the 4th one as an easily configurable alternative.

> Previously mentioned survey was comparing new format with Angular documentation format. We can probably try running one more, comparing different proposed formats. So far 4 formats were proposed:
> 
> 1. Angular docs one: `value | pipe:arg1:arg2`
> 2. Old prettier: `value | pipe: arg1:arg2`
> 3. New prettier: `value | pipe : arg1 : arg2`
> 4. Alternative: `value | pipe: arg1 : arg2`
> 
> @nseni @sosukesuzuki @nedecoTHo @pedroestabruxelles @fisker would that be a way forward you agree upon? Anything else to add, any other idea?

**Comment by waterplea** [comment]
Yeah, 4th option is a fine one too, because it highlights that pipe name differs from the arguments and it's kind of semantic use of `:` as in `feed these arguments to the pipe in use`. If that change satisfies people who are unhappy with added spaces, I'm all for it.

**Comment by EchelonFour** [comment]
Just updated prettier and this came up as a big change. I would prefer any of the options that doesn't have a space after the pipe name for the same reason you don't want to see json look like `{ key : value }`. More spaces doesn't make more readable.
The twitter poll agrees because 68.9% of people picked an option without that.

**Comment by waterplea** [comment]
@fisker @sosukesuzuki looks like `value | pipeName: arg1 : arg2` is the most welcomed format, i.e. we only need to remove space after pipe name.

**Comment by EchelonFour** [comment]
I started working on the code change for this and the issue becomes a lot more complex with a short print width (or long pipe arguments)
```typescript
//option 1A
{{
  birthdate
    | date:
      "longDate"
}}
```
or 
```typescript
//option 1B
{{
  .birthdate
    | date
      : "longDate"
}}
```
?

Then theres
```typescript
//option 2A
{{
  price
    | currency:
      "USD"
      : true
}}
```
vs
```typescript
//option 2B
{{
  price
    | currency
      : "USD"
      : true
}}
```

I think the second one looks nicer, but it breaks the consensus here about "no space after pipe name".

Also, we probably also want an exception for multiline objects or arrays so:
```typescript
//option 3A
{{
  value
    | pipeA: {
        keyA: reallySuperLongValue,
        keyB: shortValue
      } : {
        keyA: reallySuperLongValue,
        keyB: shortValue
      }
}}
```
instead of 
```typescript
//option 3B
{{
  value
    | pipeA:
        {
          keyA: reallySuperLongValue,
          keyB: shortValue
        }
      : {
          keyA: reallySuperLongValue,
          keyB: shortValue
        }
}}
```

Personally I think we go option A across the board here. even though in the second one it is less aesthetic.

**Comment by ilyakonrad** [comment]
Are there any actions taking place? It's been open for 5 months and Prettier keeps introducing unnecessary changes to the code.

**Comment by Devp00l** [comment]
I would love to see this change to be changed or opinionated in order to use pipes like seen in the angular docs and code.

I also assumed that you would do more research on your changes, not just a twitter poll in your own bubble, as in the end, if your research wasn't good, it's up to the developer to explain why we still should keep prettier for now ,even if the chosen path isn't what the team wants to see right now. It went down to a may be we change next year to something more predicable, but I hope this will change.

**Comment by waterplea** [comment]
Per prettier policy this is not something that will get a configurable option. As agreed upon during this discussion, I have opened a PR removing space after pipe name, keeping the spaces around semicolon separating arguments:
https://github.com/prettier/prettier/pull/14961
