### ISSUE TITLE
typescript[satisfies] bugs in complex ternary conditions

### ISSUE THREAD

**Issue by renatoaraujoc** [prettier/prettier#13964]
```
package.json {
    "@typescript-eslint/eslint-plugin": "5.46.0",
    "@typescript-eslint/parser": "5.46.0",
    "prettier": "2.8.1",
    "typescript": "4.9.3"
}
```

Bug:
![Screenshot 2022-12-10 at 17 30 03](https://user-images.githubusercontent.com/358128/206874148-b78e3e2c-bf30-453b-9da2-d8097cf2acaf.png)

What happens:
The formatter, somehow, stops working on the file and sometimes I have to restart Intellij IDEA Ultimate for the formatter to start working across all the project again.

Expected behavior: not to bug because this is valid typescript code.

**Comment by kachkaev** [comment]
Hi @renatoaraujoc! Could you please follow [the issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1)?

**Comment by renatoaraujoc** [comment]
Hello @kachkaev, I'm deeply sorry not to follow the issue template, this was my mistake, I've been working 12h/day for the past 3 months and I'm tired af. I'm currently going to the airport, will do a trip to Europe and won't be in touch with my PC for some days.

The issue is as follows, the screenshot is clear of the errors.

If the only way to go on with the issue is to follow the issue template, you can close this issue unless you can wait some days for me to edit this issue.

Thank you!

**Comment by cmolina** [comment]
Hello, I have a very similar issue with a simpler use of `satisfies`. However [I wasn't able to reproduce it in the playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwB0QdTyGBuOqDbPfYD-fABESMEgHEcqACYAFJulQBXdABp++CdJkkocADZqoAxQGc4mqQEFMqYhUMBffFRr0QAAXSLUAegAeALRSIiQBAOaSUgGY8krobBwccH7clIpQ5KjQGpEAFACUvOpMMIo4RrnqAgA8wqIWcnAKylUC+JBY0AgwJgC8wHxGbcPaunpIOVo6+obDwwAqEBB6AEYkOBMAwqYwNBaLy2s4s3MODq0CHdi6sCZyEJh9AxdtmNPjRUNzr3pkTd0TBgrCAwXboAIIKQME7fJwmESoEwUVBwEyTWTve6PGFzXaHdYTQbfYYACx0Uj0cAAyiSIAB3QSoEh6CBhHHfMyUzLQACyECkMxew3Q-Lg7LmZhgfIF4oEcIRSJRaO2JjB+yWq3WWJM4rOrR8AD51Pl2FBzlAQCoQA8YFkoCZkKB1tQ6domPbkCBmXSSABPB1WlY4MgAazgMCpJHQcAAMqhdMgKMyzIHg2AwxG3mB42FkDAcIoxSAmis4FIBVIYzowooSGE4AAxXDoES2qC5lAkRS7S0gEkwdB6ADqJNQ8BMWepCBMY9QADcx77PWATAG0Pa4Hg5HWW4nk0WAFYmPxUnOUgCKihBcD3ehTIDeODMOE9MF9mFRYEkmBgvZi8ZgIdpBgElkAADgABitGIIDMIdg0wT0YlRTc5xvK0AEcr3gbVPRIEwAl0Msy17JgsNQJhtzCXckCTO8izMBQ8wLBizzgSxQUkFZuzgGRNzjBNaP3K0Z3bC9sJvIT6KtUQViAqQQOQAAmGTg1QPQc02GgaOLEwAFZe1MOB5hIFYHSk+850LABJKABVgKkv1QH9LDsqk30pW8zDOIA), everything works there.

But if I pass the file to the CLI (or I use vscode + `plugin:prettier/recommended`), `prettier` fails to parse the file:

```
yarn prettier --check index.tsx
yarn run v1.22.19
$ /Users/me/app/node_modules/.bin/prettier --check index.tsx
Checking formatting...
index.tsx[error] index.tsx: SyntaxError: Unexpected token, expected "," (20:10)
[error]    1 | import React from "react";
[error]    2 | import {
[error]    3 |   DataGridPremium,
[error]    4 |   GridPanel,
[error]    5 |   GridPanelProps,
[error]    6 |   useGridApiRef,
[error]    7 | } from "@mui/x-data-grid-premium";
[error]    8 | import { CustomGridToolbar, CustomGridToolbarProps } from "components/project/docs/CustomGridToolbar";
[error]    9 |
[error]   10 | export function Grid() {
[error]   11 |   return (
[error]   12 |     <DataGridPremium
[error]   13 |       components={{
[error]   14 |         Panel: GridPanel,
[error]   15 |         Toolbar: CustomGridToolbar,
[error]   16 |       }}
[error]   17 |       componentsProps={{
[error]   18 |         panel: {
[error]   19 |           placement: "bottom-end",
[error]   20 |         } satisfies GridPanelProps,
[error]   21 |         toolbar: {
[error]   22 |           handleShowDialog,
[error]   23 |           selectionModel,
[error]   24 |           mode,
[error]   25 |           setMode,
[error]   26 |         } satisfies CustomGridToolbarProps,
[error]   27 |       }}
[error]   28 |     />
[error]   29 |   );
[error]   30 | }
[error]   31 |
All matched files use Prettier code style!
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried using the same config of the playground, but I always get the same result.

Does anyone have any guidance on how to proceed from here?

**Comment by cmolina** [comment]
I just discovered that it works if I set `"parser": "babel-ts"`. I don't know why it doesn't work with `typescript` though since it should be supported by @typescript-eslint/typescript-estree.
