### ISSUE TITLE
Nuxt Content: MDC Syntax

### ISSUE THREAD

**Issue by piet-maier** [prettier/prettier#13963]
Currently, Prettier does not support the MDC syntax used by Nuxt Content. See this link for the relevant part of the documentation of said module: https://content.nuxtjs.org/guide/writing/mdc

**Prettier 2.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFgSwM4AIe7YQC2cu8AHjADS4BmEANoxAO5wAmuARgJ64BDXJGIAHaAhgA6ADpQ5SJGAEAnDnIC0WuaJURRSXAHIAbgMYBXOEc3aoAZRYxcAYWjxYCpHLkYCBIlJcYggVMkppEGoQfRhMaGxkUFU9VgAFVQRElHNWAV5E6O4VATAAazgYewFSABlMKDhkOnNsOCKS8sr7UVKGgHNkGBUraLhibk4OTlqBKH6LAX64ADFQ4gEYOPnkEAELGAgokHQYYkYAdSx4bF6wOHsszDiTZ95dsGxCkAa2lRg0iV+htmq12iAAFbYCj2AaMOAARQsEHgoMYbWivRUf12GxUZQ4bCgx10DRgF0wHBg6GQAA4AAyYvRtC4lUS7XRwP4mJrRACOyPggP02T22A0jU4nGOYQFmDCgKWIKQLXR4LaxEwQxG6rhcAAglsVJhuAc4Gk4Cp6o00RiQNg9UiUU0VWDojABNwKVSaUgAEzukqYRgDNzEZUgLkAVmOFjaqE92VVdpMVgAklBprB7GBjaIYPrM-YYLx4ba4ABfCtAA)

```sh
--parser markdown
```

**Input:**

```markdown
This is some text, followed by a component.

::card
---
prop: 'value'
---
Slot Content
::

This is some more text.
```

**Output:**

```markdown
This is some text, followed by a component.

## ::card

## prop: 'value'

Slot Content
::

This is some more text.

```

**Expected behavior:**
MDC Components should be formatted as shown in the Nuxt documentation. In this case, the input is already properly formatted and should not be changed.

**Comment by kachkaev** [comment]
Let’s track this feature request in https://github.com/prettier/prettier/issues/13512, closing this as a duplicate. Thanks for crafting a Playground example!
