### ISSUE TITLE
Disable scheduled pipelines in forks

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#13978]
I have a [fork of Prettier](https://github.com/kachkaev/prettier) which I haven’t touched for a few weeks now. GitHub sent me these three emails:

<img width="1029" alt="Screenshot 2022-12-11 at 17 40 29" src="https://user-images.githubusercontent.com/608862/206919659-361d4b0f-c036-476c-88c7-52926899fced.png">

<div align=center><img width="558" alt="Screenshot 2022-12-11 at 17 42 47" src="https://user-images.githubusercontent.com/608862/206919696-cdd1beb0-1fdc-4921-a40e-4daab0a30893.png"></div>

It’d be nice if we can avoid this for everyone who creates forks. I _guess_ we can add `if: github.repository == 'prettier/prettier'` in yamls somewhere but I haven’t researched this yet. I’m creating this issue to raise awareness. I can look into it later unless someone knows the solution right away.

**Steps to reproduce:**

Fork `prettier/prettier`

**Expected behavior:**

Scheduled workflows run: https://github.com/kachkaev/prettier/actions

**Actual behavior:**

Scheduled workflows don't run.

**Comment by fisker** [comment]
There is no top-level `if`, so we can only add `if` to `jobs.<job_id>.if`, I guess you'll still get the email notification.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/13981
