### ISSUE TITLE
Array.from using trailingComma=all outputs SyntaxError.

### ISSUE THREAD

**Issue by marcelmokos** [prettier/prettier#1398]
When Array.from() contains function prettier will add trailing comma which will the cause "Uncaught SyntaxError: Unexpected token )"  as result.

Output:
```javascript
Array.from(
  [1, 2, 3].filter(num => {
    return num % 2 === 0;
  }), // this added comma will cause -> Uncaught SyntaxError: Unexpected token )
);
```

[Simplified cases of Array.from() causing SyntaxError](https://goo.gl/eFHKKs)

**Comment by RoM4iK** [comment]
Trailing commas in function currently unsupported in a lot of environments.
http://kangax.github.io/compat-table/es2016plus/
Copypasted your code into https://repl.it/HWON and everything was ok.

**Comment by vjeux** [comment]
You need to use `trailingComma=es5` instead. The `all` option is when you use babel to transform it. Node and browsers don't yet implement this part of the spec widely.
