### ISSUE TITLE
Unary minus must not be followed by a space in LESS

### ISSUE THREAD

**Issue by mvorisek** [prettier/prettier#13998]
Current version of Prettier is adding a space after unary minus operator in LESS.

Config:
```
module.exports = {
    tabWidth: 4,
    overrides: [
        {
            files: ['*.less'],
            options: {
                parser: 'less',
            },
        },
    ],
};
```

Wrong autoformat:
```diff
 .xxx {
-    margin: 0 -(@arrowBorderWidth / 2) 0 0;
+    margin: 0 - (@arrowBorderWidth / 2) 0 0;
 }
```

I would expect no fix/added space.

**Comment by mvorisek** [comment]
minimal playground repro link: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAdAD264AdKVI1AWwEMAnAcwEsolUAGVAWgAoABSiiAdwCEIFACZwKAdRrCYAC1QB6VACYAlEyYBuAqgC+IADQgIABxg1oAZ2ShufAAqUEVlGQA2vMgE8rhgEYUyMABrOBgAZTISOAAZOjhkADM3Czg-AODQsONAuipkGAoAV1SQOBJfOGFRYWiyKCpCsio4ADEhchgzeuQQMkKYCAMQGRgSV3EZGngLbLA4MKcpmgA3Kc8esAsfEDoUihg7AKpyROSSgCsLTDDc1zgARUKIeFPXFMNsij2eu62h4wodBgkmkMmQAA5GB8eClxAFjD0AXA9st4oYAI5PeCHEzOXoWFhQOCVSpDChwTE0cmHJonJBJN4lFIkGj5IpM25wACCnUBvn6cDsYliRNe7xAFk5j2e8XpZ0MMDIvhBsmQSgVARorlyAGEICQ6aULABWIaFFIAFSVzgZ4uWxQAklBRLAwmBAaYuc6wjBPHcxXAdDogA

**Comment by kachkaev** [comment]
Please follow the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1) in your first comment. Related to https://github.com/prettier/prettier/issues/12613.
