### ISSUE TITLE
Copy button for commands on click

### ISSUE THREAD

**Issue by mishrasur7** [prettier/prettier#14006]
Hey, is it possible to implement a copy button to copy prettier commands? it provides good user experience. 

**Environments:**

- Prettier Version: 2.8.1
- Running Prettier via: 
- Runtime: 
- Operating System: 
- Prettier plugins (if any): 

**Steps to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by kachkaev** [comment]
Hi @mishrasur7! Could you please elaborate? Not sure I understand what you mean.

**Comment by mishrasur7** [comment]
Hi @kachkaev! 
I mean to say, can we implement a functionality to copy commands into clipboard so its easy for users to just click and it gets copied to clipboard and can be pasted in command line?

**Comment by mishrasur7** [comment]
For example; we can copy this command to install redux toolkit easily from their docs. 

<img width="829" alt="Screenshot 2022-12-17 at 19 33 17" src="https://user-images.githubusercontent.com/75450225/208254204-8c44d3d4-ed89-4294-8600-9c7550268bd4.png">

**Comment by kachkaev** [comment]
Do you mean Prettier docs, e.g. https://prettier.io/docs/en/install.html? I.e. copy buttons here:

<img width="1128" alt="Screenshot 2022-12-17 at 19 28 28" src="https://user-images.githubusercontent.com/608862/208263172-c07347f1-a7aa-44d3-9e62-cee338a13343.png">

**Comment by mishrasur7** [comment]
Exactly!

**Comment by kachkaev** [comment]
Got you, thanks! Feel free to create a PR if you want!

**Comment by thorn0** [comment]
Fixed by #14153
