### ISSUE TITLE
Extra semicolon is required/added after every every prettier run

### ISSUE THREAD

**Issue by mvorisek** [prettier/prettier#14005]
Steps to reproduce:

1. checkout https://github.com/mvorisek/Fomantic-UI/commit/19a07d17df713013f39711b6d9e8a359fd0fa50c
2. run `npm install`
3. run `npm run lint-fix` (which runs `... && prettier --loglevel warn "!dist" "!test/coverage" "**/*.{css,less,overrides,variables}" --write`)
4. in the last line of `src/themes/twitter/elements/emoji.variables` file notice the following change:

![image](https://user-images.githubusercontent.com/2228672/208122103-b4d8c1e6-4e26-42ad-8c38-6756fee85b4c.png)

The added semicolon is wrong as already present.

This issue should be fixed with high priority, as the semicolon is added every `prettier ... --write` run, making the file unstable and we had to turn prettier off completely.

**Comment by kachkaev** [comment]
Can you please follow the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1)? If the bug is not unproduceable in the [Playground](https://prettier.io/playground/), it can be related to third-party code (plugins, other linters etc.)

**Comment by kachkaev** [comment]
This but is tracked in https://github.com/prettier/prettier/issues/11483. Feel free to submit a PR!
