### ISSUE TITLE
RFC: Deprecates `@types/prettier` and maintains type definitions in `prettier/prettier` repository

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#14033]
## Background

- Prettier has JavaScript API.
- Type definitions for the API is maintained in [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped).
  - https://www.npmjs.com/package/@types/prettier
  - https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prettier

## Proposal

1. Moves `@types/prettier` to https://github.com/prettier/prettier.
2. Deprecates `@types/prettier`.

## Pros

- Definitely Typed is a huge repository, so it is slightly hard to fix for us.
- Easy to synchronize type definitions with Prettier's API implementation.
- API users do not need to install `@types/prettier`, need only `prettier`.
- Some plugins are implemented in TypeScript, so improving their development experience makes a lot of sense.
  - https://github.com/sveltejs/prettier-plugin-svelte/issues/317#issuecomment-1336552532

## Cons

- Increase the maintenance cost.
- Increase the npm package size.

## References

- https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by carmanchris31** [comment]
Thank you very much for opening this!

**Comment by fisker** [comment]
Fixed by  #14212
