### ISSUE TITLE
Utility functions requests

### ISSUE THREAD

**Issue by Janther** [prettier/prettier#14035]
Is there any reason why `getNextNonSpaceNonCommentCharacterIndex` is in the public API but `getNextNonSpaceNonCommentCharacter` isn't? it's a one liner we could do without in [prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity).

Also, `hasNodeIgnoreComment` feels like something that every plugin could benefit if they decide to support comments containing `prettier-ignore`.

**Comment by fisker** [comment]
`hasNodeIgnoreComment` is only works for JS, I don't think we should expose that.

**Comment by fisker** [comment]
Fixed by #14317
