### ISSUE TITLE
Is it possible to globally skip formatting of console message

### ISSUE THREAD

**Issue by mikeerickson** [prettier/prettier#1404]
I would like to omit this time of cleaning globally

```js
console.log(chalk.cyan(_.padEnd('Start Date:', PAD_LENGTH)) + moment(startDateTime).format('MMMM Do YYYY, h:mm:ss a'));
```

to this

```js
console.log(
  chalk.cyan(_.padEnd('Start Date:', PAD_LENGTH)) +
    moment(startDateTime).format('MMMM Do YYYY, h:mm:ss a')
);
```

**Comment by vjeux** [comment]
I'm curious, the output of prettier seems reasonable, why do you want it different?

You can add `// prettier-ignore` on the line before to leave it untouched.

```js
// prettier-ignore
console.log(chalk.cyan(_.padEnd('Start Date:', PAD_LENGTH)) + moment(startDateTime).format('MMMM Do YYYY, h:mm:ss a'));
```

**Comment by vjeux** [comment]
I'm sorry about this one but we're not going to add an override for this. I would suggest to try and convince your team that this is okay to give up control on this given all the advantages of prettier. If they don't want to, then maybe using prettier is not the right thing to do at this point :(

**Comment by saimonmoore** [comment]
I have the same usecase as @mikeerickson . Since, in general, `console.log` is used for debugging purposes and is generally in the code on a temporary basis. I don't think it's unreasonable to provide a global override for these statements. 

My 2c.

**Comment by duailibe** [comment]
If it's temporary, why is it important how it's formatted?

**Comment by saimonmoore** [comment]
Well because you generally want to format the rest of the code while you still have logging statements in them. This was a pain the other day because it made removing the console.log statements a pain (e.g. using sed/vim).

I think it would be handy to have but not a biggie.

**Comment by doplumi** [comment]
I would love this too. Or better, an option that leaves (lines that start with) certain code unchanged: `ignore: ['console.log', 'log.*']`.

**Comment by kaushik-rishi** [comment]
@mikeerickson did you find a fix ?

**Comment by chadwtaylor** [comment]
+1

**Comment by FlxEd** [comment]
+1 !

**Comment by FlxEd** [comment]
@vjeux in my team we are using a lot of lines like this:

`if (LOG_MODE === 'VERBOSE') console.log('[DBG_MODE] - [Class.name] - [MethodName]:  Verbose action description that takes space:', FormatHelper.deepCloneObj({longKeyNameA: deeply.nested.object.property, longKeyNameB: deeply.nested.object.property}))`

Doing this lets us keep console.logs in the code in case we want to change `LOG_MODE` in the future for a more or less verbose logging behavior (future debugging purposes for example).

Having these long lines wrapped like the rest of the code takes enormous amount of space and makes the code harder to read (which is the contrary of what I would expect from prettier...).
And having to place a `// prettier-ignore` on top of every debug line is also annoying as it adds uneccessary comments everywhere and makes the code less pretty as well.

Personally I am very interested by something similar to what @doplumi proposed.

I love prettier and it saved us a lot of hassle on our code base.
This is why I would love to be able to use the proposed feature, to keep my code pretty ... er 🙂
