### ISSUE TITLE
define a single rule for operators line break

### ISSUE THREAD

**Issue by tinchoz49** [prettier/prettier#1405]
Hi everyone, how are you?

Playing with prettier (v1.2.2) I noticed that the formatter uses two different rules for the operators' line break and I think it's better if we keep only a single rule for it.

example src file
```javascript
const test1 = typeof URL === "function" && typeof history === "object" && typeof history.replaceState === "function"
  
const test2 = typeof URL === "function" ? "Lorem Ipsum is simply dummy text" : "printing and typesetting industry.";
```

current formatter
```javascript
const test1 =
  typeof URL === "function" &&
  typeof history === "object" &&
  typeof history.replaceState === "function";

const test2 = typeof URL === "function"
  ? "Lorem Ipsum is simply dummy text"
  : "printing and typesetting industry.";
```

using a single style (in my example: `after` style)
```javascript
const test1 =
  typeof URL === "function" &&
  typeof history === "object" &&
  typeof history.replaceState === "function";

const test2 = typeof URL === "function" ?
  "Lorem Ipsum is simply dummy text" :
  "printing and typesetting industry.";
```

I take the idea of this rule from: http://eslint.org/docs/rules/operator-linebreak

What do you think?

**Comment by rattrayalex** [comment]
Hi @tinchoz49 , 

Thanks for sharing the idea! 

The decision to print ternaries as they are is very much intentional and not likely to change. The same is true of logical operators. 

I hope this formatting is acceptable to you and your team!
