### ISSUE TITLE
"in" operator in Angular code is mis-formatted

### ISSUE THREAD

**Issue by sathishvj** [prettier/prettier#14102]
**Prettier 2.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIBUUA5gJIBmAvADogwAWmAzgHSbq6ZS4DaA5AAy8ANLl4BGXgF0aAPlQB6LNhkghICAAcYmaI2SgAhgCcjEAO4AFYwj0oDAGzMGAnnrUAjIwbABrODABlAwBbOAAZTjhkMgdGOA8vX38AjW9OImQYIwBXeJA4YPc4dHRisINibIMiOAAxCCNggxhtYmQQA2yYCFUQOhhg+wB1BnhGVLA4AJtMbWxZ53awRjcQTjijGAsvIibo2LyAK0YADwD0+zgARWyIeH37OLVUow32iqJs+2NejSNOGBDNj0ZAADn4z1McSGXg07T+cA22CiagAjrd4NtNLYOowALRQODFYq9IxwdGYMnbap7JAxR55OLBTCZHKMi5wACCLX+7i6cAscCMEUJDyeIEYHJudyidIOahgBncQPQIKQACYFV5MPZ0gBhCDBWn5RgAVl62TiABUlbZ6eLsLkSFBSrAAmB-lpOS6AjBnJcxXAAL5BoA)

```sh
--parser angular
```

**Input:**

```html
<div *ngIf="this.id in ['0', '1']"></div>
```

**Output:**

```html
<div *ngIf="this.id; in: ['0', '1']"></div>

```

**Expected behavior:**
Existing code should be as is and there should not be any formatting.
```jsx
<div *ngIf="this.id in ['0', '1']">
```

**Comment by fisker** [comment]
It seems `in` not supported https://github.com/angular/angular/issues/7751

**Comment by sathishvj** [comment]
ok. closing this one.

Also, just in case someone is curious about this later, using "in" here in this particular case is not correct.  I made a mistake.  We have to use includes() instead:  ['0', '1'].includes(this.id)
