### ISSUE TITLE
Prettier format failing for angular inject function

### ISSUE THREAD

**Issue by sheikalthaf** [prettier/prettier#14100]
**Prettier 2.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMIQC2ADtAjDsADpQ44Am6M6OAvDgJZQBWcYMACgDKROHgzYAPMEbMkOTDABOXAOYBfAHwBKANw11IADQgIxGB2iZkodEqUQA7gAU7CaynSpH6AJ7WTACMldDAAazgYIXRCOAAZLjhkADMvTDggkPDIoWJQtWRlAFcMkDhCQLh6eiq49ChVIvRVOAAxCCVCJgsG5BB0IpgIYxAACxhCVAB1UY54TDywOCF3OY4ANznfPrBsEa50pRhnENUulLTS7kwADyE1VDgARSKIeAvUdJM8pUO+wPQlVQI2IKlgUw49Bgo2QAA4AAzfBzpKYhYh9UFwQ7rJImACOr3gJzMHn6mAAtFA4FUqiMlHACRx6SdmuckKlPqV0oQOIUlCUTJgHnAAIIwZQcQKDODOOBKBJUj5fEBChqPF5vJLsy4mZiBCFQmFIABMupCHFQagIhDZZUwAFYRkV0gAVQEeDnK9YlACSUBqsCEYBU5hF-qEMF8jyVcHU6iAA)

```sh
--parser babel
```

**Input:**

```jsx
class Component {
  data = inject(SomeClass<{data: string}>);
}
```

**Output:**

```jsx
SyntaxError: Unexpected token (2:42)
  1 | class Component {
> 2 |   data = inject(SomeClass<{data: string}>);
    |                                          ^
  3 | }
```

**Expected behavior:**

**Comment by fisker** [comment]
It's not valid JavaScript code. You can use `typescript` parser.

**Comment by sheikalthaf** [comment]
Yes it is working fine in typescript, thanks
