### ISSUE TITLE
Ignore files that are not tracked by git (by default)

### ISSUE THREAD

**Issue by Divlo** [prettier/prettier#14115]
## The current behavior

Prettier is often used in a git repository, and we often have a `.gitignore` or `.prettierignore` file.
As a result, we often end up with a setup like that (in `package.json`):

```json
{
  "scripts": {
    "lint:prettier": "prettier \".\" --check --ignore-path \".gitignore\""
  }
}
```

However, only files/globs specified in the root `.gitignore` file are ignored. If we have `.gitignore` files in subdirectories they will not be taken into account.

In a monolith project or in a project with only one `package.json` it should be uncommon to use `.gitgnore` in subdirectories (not really needed in most Node.js/JavaScript applications).
However, in monorepo and with projects with not only languages supported by Prettier (JavaScript, HTML, CSS, etc.), it doesn't make sense to put everything in the one single `.gitignore`.
By using Prettier, we don't want to lose the convenience we have with `git`. Also even if [ignore npm package](https://www.npmjs.com/package/ignore) can be 100% spec compliant, it will never mirror with perfection what git really ignores or not.

Also, there are already enough dotfiles in our project, if we can avoid them when we can, it's better to do so, hence it's often better to specify  `--ignore-path \".gitignore\"` instead to rely on the `.prettierignore` file.

*Note:* This issue could be applied to many linters in the ecosystem, and by opening this issue on Prettier, I hope that others tools will follow (e.g: ESLint).

## The expected behavior

We want to use Prettier like this (in `package.json`):
```json
{
  "scripts": {
    "lint:prettier": "prettier \".\" --check"
  }
}
```
**By default** Prettier, will ignore all the files ignored by git (if the code is in a git repository of course) without any configuration and with exactly the same behavior as git.
One could argue that it could be a **BREAKING CHANGE** as we're changing *default-behavior* but, it should very uncommon to willing to lint ignored files by git with Prettier.

## Potential solution

Instead to rely on the `ignore` npm package, and doing manually the same algorithm as git to take into account `.gitignore` in subdirectories, we want to use git CLI.
Doing the exact same algorithm as git manually with the `ignore` npm package can get quite complicated to reimplement from scratch.

Similarly to how it used for https://github.com/editorconfig-checker/editorconfig-checker.

Related links:
- https://github.com/editorconfig-checker/editorconfig-checker/issues/99
- https://github.com/editorconfig-checker/editorconfig-checker/pull/135

**Comment by Divlo** [comment]
Any thoughts? Opinions? @fisker @sosukesuzuki @thorn0

**Comment by fisker** [comment]
I'm going to make CLI accept multiple `--ignore-path` first. https://github.com/prettier/prettier/pull/14332

Once it landed, if we decide accept, we'll just need to change the default value from

`[".prettierignore"]` to `[".prettierignore", ".gitignore"]`.

**Comment by Divlo** [comment]
Very good, already a improvement, but it's still missing `.gitignore` in nested folders.

**Comment by kachkaev** [comment]
Personally, I would benefit from `.gitignore` + `.prettierignore` being the default. Having said that, I don’t know if there are any risks that I don’t see, which would ruin the party. So I am on the fence here and if there are voices against changing the default (yet), I’d be easy with that.

**Comment by kraktus** [comment]
This is potentially a distinct feature request, but what about also taking into account the global `gitignore` of the user? I don't know If prettier can access it though.

**Comment by fisker** [comment]
> Interestingly, if `.gitignore` is included by default, we might no longer need `--with-node-modules` option. It could be removed in v4.

Why do you think we can remove  `--with-node-modules`?

**Comment by fisker** [comment]
Include `.gitignore` will be fixed by #14731.

Anyway, we'll still need `.gitignore` at CWD. We'll track the behavior of ignore files in #4081.

**Comment by kachkaev** [comment]
> Why do you think we can remove `--with-node-modules`?

If we include `.gitignore` by default, there are high chances of `node_modules` being there already. But maybe I am missing some use case which makes that option still valuable to some. I just saw an opportunity to reduce the API surface and remove a slightly odd ‘special case’. `node_modules` are ‘special’ but not significantly more special than, say `.yarn`. Anyways, ignore me 😅

**Comment by fisker** [comment]
`prettier --with-node-modules` means format files in `node_modules`, not ignore. We always ignore it without this flag, no matter what `--ignore-path` is.

**Comment by rotu** [comment]
I don't know that simply using `.gitignore` as a second `.eslintignore` is a good idea. It only happens to work if:

* you have a single `.gitignore`, not multiple files in the source tree.
* you happen to run prettier from the same directory containing this file (e.g. not a subfolder).
* your `.gitignore` doesn't contain special syntax (e.g. I think character ranges `[a-z]` are supported in gitignore but not globby)
* You don't use `$GIT_DIR/info/exclude` nor `core.excludesFile` https://git-scm.com/docs/gitignore

Perhaps it would be better to filter files with [`git check-ignore`](https://git-scm.com/docs/git-check-ignore) or [`git ls-files`](https://git-scm.com/docs/git-ls-files), which will reflect git's *actual* behavior.

**Comment by fisker** [comment]
@totu See https://github.com/prettier/prettier/issues/14115#issuecomment-1517641375

**Comment by totu** [comment]
> @totu See [#14115 (comment)](https://github.com/prettier/prettier/issues/14115#issuecomment-1517641375)

Think you meant to tag @rotu

**Comment by fisker** [comment]
Sorry about that...

**Comment by rotu** [comment]
@fisker Oops! You closed this issue though #14732 does not resolve the issue! Files that are not tracked by git are still mauled by prettier if e.g. you run prettier from any folder other than the repo root. or e.g. if there are multiple .gitignore files.

**Comment by sscotth** [comment]
@rotu Tracking via #4081

https://github.com/prettier/prettier/issues/14115#issuecomment-1517641375

**Comment by moiri-gamboni** [comment]
I'm not sure if this is the right place for this comment, but the docs should be updated. I found [Install](https://prettier.io/docs/en/install.html) and [Ignoring code](https://prettier.io/docs/en/ignore.html) which didn't mention this new behavior.

**Comment by mathiasrw** [comment]
> Personally, I would benefit from .gitignore + .prettierignore being the default. Having said that, I don’t know if there are any risks that I don’t see, which could ruin the party. So I am on the fence here and if there are voices against changing the default (yet), I’d be easy with that.

It is unclear to me from https://prettier.io/blog/2023/07/05/3.0.0.html, this page and the documentation if we ended up with defaulting to `.gitignore + .prettierignore` or just '.gitignore`
