### ISSUE TITLE
Reopen #5641 : The formatting of self-closing tags in HTML5

### ISSUE THREAD

**Issue by tomkeays** [prettier/prettier#14113]
I know Prettier is opinionated, but I hope you might be willing to revisit something where common usage has changed. HTML5 was initially ambiguous regarding the use of trailing slashes on void (self-closing) elements, probably because some designers were coming from using XHTML and they wanted to reduce friction for them to make the transition. Adding the trailing slash was always optional.

However, the need to ease the transition from XHTML is no longer the case and most people have moved on. In fact, the [W3C Validator](https://validator.w3.org/) throws this warning:

"Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values)."

[HTML5 Bolierplate](https://github.com/h5bp/html5-boilerplate/blob/main/src/index.html), which informs the VS Code HTML formatting style guidelines and is referenced by many designers and educators, doesn't use trailing slashes on void elements. 

Please consider rethinking this or at least provide a way to override it in VS Code.

**Comment by rickbeerendonk** [comment]
I teach HTML and use Prettier, but it am reconsider using it because of this functionality. It makes learning HTML harder, not easier.

**Comment by fisker** [comment]
Personally, I'm 👍  for this. But seems other team members prefer it compatible with XHTML.

**Comment by fisker** [comment]
Let's track this in #5246
