### ISSUE TITLE
Relay fragment passing variables in nested getFragment call

### ISSUE THREAD

**Issue by jonathansewell** [prettier/prettier#1411]
```javascript
export default Relay.createContainer(DashboardAccountList, {
  initialVariables: {
    from: '',
    to: '',
    previousFrom: '',
    previousTo: '',
    tags: null,
    usernames: null,
    orderBy: 'NAME',
    first: 100,
    last: null
  },
  fragments: {
    viewer: (variables) =>  Relay.QL`
      fragment on viewer {
        accounts(first: $first, last: $last, from: $from, to: $to, tags: $tags, usernames: $usernames, orderBy: $orderBy) {
          total

          edges {
            node {
              id
              ${Item.getFragment('account', {
                from: variables.from,
                to: variables.to,
                previousFrom: variables.previousFrom,
                previousTo: variables.previousTo
              })}
            }
          }
        }
      }
    `
  }
});
```

is turned into

```javascript
export default Relay.createContainer(DashboardAccountList, {
  initialVariables: {
    from: '',
    to: '',
    previousFrom: '',
    previousTo: '',
    tags: null,
    usernames: null,
    orderBy: 'NAME',
    first: 100,
    last: null
  },
  fragments: {
    viewer: variables => Relay.QL`
      fragment on viewer {
        accounts(first: $first, last: $last, from: $from, to: $to, tags: $tags, usernames: $usernames, orderBy: $orderBy) {
          total

          edges {
            node {
              id
              ${Item.getFragment('account', {
      from: variables.from,
      to: variables.to,
      previousFrom: variables.previousFrom,
      previousTo: variables.previousTo
    })}
            }
          }
        }
      }
    `
  }
});
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20default%20Relay.createContainer(DashboardAccountList%2C%20%7B%5Cn%20%20initialVariables%3A%20%7B%5Cn%20%20%20%20from%3A%20''%2C%5Cn%20%20%20%20to%3A%20''%2C%5Cn%20%20%20%20previousFrom%3A%20''%2C%5Cn%20%20%20%20previousTo%3A%20''%2C%5Cn%20%20%20%20tags%3A%20null%2C%5Cn%20%20%20%20usernames%3A%20null%2C%5Cn%20%20%20%20orderBy%3A%20'NAME'%2C%5Cn%20%20%20%20first%3A%20100%2C%5Cn%20%20%20%20last%3A%20null%5Cn%20%20%7D%2C%5Cn%20%20fragments%3A%20%7B%5Cn%20%20%20%20viewer%3A%20(variables)%20%3D%3E%20%20Relay.QL%60%5Cn%20%20%20%20%20%20fragment%20on%20viewer%20%7B%5Cn%20%20%20%20%20%20%20%20accounts(first%3A%20%24first%2C%20last%3A%20%24last%2C%20from%3A%20%24from%2C%20to%3A%20%24to%2C%20tags%3A%20%24tags%2C%20usernames%3A%20%24usernames%2C%20orderBy%3A%20%24orderBy)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20total%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20edges%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%24%7BItem.getFragment('account'%2C%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20from%3A%20variables.from%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20to%3A%20variables.to%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20previousFrom%3A%20variables.previousFrom%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20previousTo%3A%20variables.previousTo%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%60%5Cn%20%20%7D%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks for the report, https://github.com/prettier/prettier/pull/1385 is going to fix this issue

**Comment by vjeux** [comment]
This is now fixed :)
