### ISSUE TITLE
Soft hyphen HTML entity is converted

### ISSUE THREAD

**Issue by oscar-b** [prettier/prettier#1412]
Soft hyphen: `&shy;` is transformed to an invisible character (at least in vscode) when using Baylon parser: 

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20Terms%20%3D%20()%20%3D%3E%20(%5Cn%5Ct%3CPage%3E%5Cn%5Ct%5Ct%3Cheader%3E%5Cn%5Ct%5Ct%5Ct%3Ch1%3E%5Cn%5Ct%5Ct%5Ct%5CtDeltagar%26shy%3Bvillkor%5Cn%5Ct%5Ct%5Ct%3C%2Fh1%3E%5Cn%5Ct%5Ct%3C%2Fheader%3E%5Cn%20%20%5Ct%3C%2FPage%3E%5Cn%20%20)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

https://github.com/prettier/prettier/issues/678#issuecomment-296845823

**Comment by yamafaktory** [comment]
This will be solved by #1165.

**Comment by vjeux** [comment]
This is fixed in master
