### ISSUE TITLE
Javascript code causes prettier to error exit and request report 

### ISSUE THREAD

**Issue by rayellis4** [prettier/prettier#14142]
This line of Javascript

const maybeGenerators = N.subtract(H.members).intersection(((zGenerators /*: any */) /*: BitSet */))

either in its original context or as a single line in a file, causes prettier@2.8.1 to exit with the following message (file names are edited):

tmp.js[error] tmp.js: Error: Comment ": BitSet" was not printed. Please report this error!
[error]     at Object.ensureAllCommentsPrinted (<PROJECT_ROOT>/node_modules/prettier/index.js:8106:17)
[error]     at coreFormat (<PROJECT_ROOT>/node_modules/prettier/index.js:8655:16)
[error]     at formatWithCursor2 (<PROJECT_ROOT>/node_modules/prettier/index.js:8837:18)
[error]     at Object.formatWithCursor (<PROJECT_ROOT>/node_modules/prettier/index.js:37836:12)
[error]     at format (<PROJECT_ROOT>/node_modules/prettier/cli.js:14789:24)
[error]     at formatFiles2 (<PROJECT_ROOT>/node_modules/prettier/cli.js:14903:22)
[error]     at async main (<PROJECT_ROOT>/node_modules/prettier/cli.js:15128:5)
[error]     at async Object.run (<PROJECT_ROOT>/node_modules/prettier/cli.js:15075:5)

running in  VMware workstation pro 15.5.7 build 17171714
Linux kernel 5.15.0-57-generic #63, Lubuntu 22.04
Node v18.8.0, npm v9.2.0
eslint@8.31.0
flow-bin@0.193.0

eslint and flow both run clean on the original file, and the code executes as I had expect.

Great tool, BTW -- thank you for sharing!

**Comment by thorn0** [comment]
This has been fixed in the `next` branch, will be released in 3.0
