### ISSUE TITLE
Format issue when using Function.prototype.bind

### ISSUE THREAD

**Issue by edufelipe** [prettier/prettier#1414]
When using a locally bound function `function() {}.bind()` prettier fails to "inline" it as the first parameter, causing a disparity in formatting.

For example, when binding this function we got two very different results:

```js
setTimeout(function() { alert("good"); }, 50);

setTimeout(function() { alert("bad"); }.bind(window), 50);
```

Prettier 1.2.2 produces the following output:

```js
setTimeout(function() {
  alert("good");
}, 50);

setTimeout(
  function() {
    alert("bad");
  }.bind(window),
  50
);
```

Wouldn't it look better like this?

```js
setTimeout(function() {
  alert("good");
}.bind(window), 50);
```
What do you guys think?

**Comment by vjeux** [comment]
Yeah, this is unfortunate. However, we don't want to start supporting every single use case on earth. I'm curious, are you binding the function to window in setTimeout or is this just a random example?

**Comment by edufelipe** [comment]
@vjeux It's just a random example. I tried to do it the shortest way possible.

Unfortunately this usage pattern is really all over the codebase of the company I work for. I've introduced prettier here and folks loved it, but every single dev complained about this particular case, so that is why I considered opening an issue.

**Comment by vjeux** [comment]
Could you collect a list of examples where this happens? It's very hard to come up with good rules with some reduced examples like this one.

**Comment by vjeux** [comment]
I'm sorry but we're not going to do more changes around this. I'm going to close this issue.
