### ISSUE TITLE
Add parentheses for TSTypeOperator

### ISSUE THREAD

**Issue by onishi-kohei** [prettier/prettier#14140]
**Prettier 2.8.2**
[Playground link](https://prettier.io/playground/#.....)

```sh
--parser typescript
```

**Input:**

```jsx
a as (typeof node.children)!
```

**Output:**

```jsx
a as typeof node.children!;

```

**Expected behavior:**
```jsx
a as (typeof node.children)!
```

**Comment by fisker** [comment]
@spennine Your issue not related to this one, you must have different version of Prettier installed.

**Comment by spennine** [comment]
ty @fisker , we are seeing this using 2.8.2;  2.8.1 didn't exhibit this issue.

**Comment by fisker** [comment]
Your editor is running old version.

**Comment by spennine** [comment]
> Your editor is running old version.

ahhh... ty for pointing that out my friend :)

**Comment by thorn0** [comment]
I never saw code like this (`as` + `!`), but if the goal of the parens is to make the precedence of operators more visible, then it makes more sense to place them this way: `(a as typeof node.children)!`

**Comment by onishi-kohei** [comment]
I ran it and got the following.
Looks good as is.
**Input:**

```jsx
(a as typeof node.children)!
```

**Output:**

```jsx
(a as typeof node.children)! ;

```

**Comment by fisker** [comment]
This was proposed base on my comment https://github.com/prettier/prettier/pull/14042#issuecomment-1367750690, I'm not familiar with the TS syntax. Let's close this since it doesn't make sense.
