### ISSUE TITLE
Slow startup time of CLI tool

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [prettier/prettier#14167]
**Environments:**

- Prettier Version: 2.8.2
- Running Prettier via: CLI
- Runtime: `node --version`: v16.19.0
- Operating System: `prettier` package in Archlinux
- Prettier plugins (if any): none, I think

**Steps to reproduce:**

`time /usr/bin/prettier --version`

**Expected behavior:**
Takes at most `0.1` second

**Actual behavior:**
Takes `0.8` seconds

Should I look into [prettierd](https://github.com/fsouza/prettierd) instead? I would have expected the CLI tool to be faster and don't feel like reconfiguring my editor.

There have been some previous issues regarding this (#3386) but they seem quite old or already fixed (#12261).

**Comment by RagnarGrootKoerkamp** [comment]
Hmm this is weird,

- If I do `time /usr/lib/prettier/bin-prettier.js --version` it takes `0.786s`.
- If I do `cp -r /usr/lib/prettier ~/prettier && time ~/prettier/bin-prettier.js --version` it takes `0.240s`.

Could this have something to do with outdated caches or permissions?

**Comment by thorn0** [comment]
Looks like this is not a problem with Prettier itself. You might like to try bringing this up with the maintainers of the prettier package in Archlinux.

**Comment by RagnarGrootKoerkamp** [comment]
Ok, found the issue:
I had a very old version of the `prettier-plugin-php` AUR package installed in `/usr/lib/node_module/@prettier/plugin-php`. Updating the package made the time go from `0.760` to `0.375`. And after uninstalling it's down to `0.226s` :tada:.
