### ISSUE TITLE
prettier 2.8.2 adds superfluous parentheses to TSTypeOperator 

### ISSUE THREAD

**Issue by powercover** [prettier/prettier#14162]
**Environments:**

- Prettier Version: 2.8.2
- Running Prettier via: CLI
- Runtime: Node.js v19.2.0
- Operating System: any

**Input:**
//    prettier adds superfluous parentheses
//    adding brackets around `typeof something`
type SomeType = typeof something[number];

**Expected output:**
type SomeType = typeof something[number];

**Actual output:**
type SomeType = (typeof something)[number];

**Comment by kachkaev** [comment]
👋 @powercover! This change is intended, see https://github.com/prettier/prettier/issues/13546 and https://github.com/prettier/prettier/pull/14042

**Comment by viktomas** [comment]
I'm not sure if my opinion will be the majority opinion or not, but this change should IMO warrant a major version bump, not just a patch version. Upgrading prettier to 2.8.2 breaks builds that were green before.

**Comment by zomars** [comment]
We're having this same issue. It introduces unexpected behavior. Also creates a massive war between prettier and eslint-config-prettier. The IDE displays an error while the CLI doesn't. At least an option to disable this would be nice.

**Comment by angelod1as** [comment]
Any way to disable this rule? I want to update the package in my project but this is resulting in wrong output. 

```
const testObject = {
  first: 'a',
  second: ['first', 'second', 3]
}

typeof testObject.second[0]
// "string"

typeof testObject.second[2]
// "number"

(typeof testObject.second)[0]
// "o"

(typeof testObject.second)[2]
// "j" 
```
