### ISSUE TITLE
Angular templates self closing tags

### ISSUE THREAD

**Issue by SebastianPodgajny** [prettier/prettier#14168]
**Prettier 2.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgB0wWngZxgHoA+AHShABoQJMYBLafZUdAJ3YgHcAFDhCxToANt3QBPFjQBG7dGADWcGAGV0AWzgAZBlDjIAZqPxxZ8pStWYFegObIY7AK5mQcDTLgATbz+3oUHbO6HZwAGIQ7BroMIxByCDozjAQ1CAAFjAaIgDqGQwENmBwqoKFDABuhRKJYPjSIHqm7DC88nYxRiZuAFb4AB6q9iJwAIrOEPDdIqY0NuwtiYHBIhzpmOx6MLkM3jAZyAAcAAzzXKa58piJm3AtlQY0AI6T8O10Qkn4OPo+Pul2HBXgwge1Ql0kMZZm5TBoGI4XLCRuM3gYoT0aDB0DJdvtDkgAExY+QMET2ADCEA0kPc+AArOlnKYACo4oTQuYgSquACSUD8sFUYC29AAggLVDAJKMZqYAL7yoA)

**Input:**

```jsx
<app-test/>
```

**Output:**

```jsx
SyntaxError: Only void and foreign elements can be self closed "app-test" (1:1)
> 1 | <app-test/>
    | ^^^^^^^^^
  2 |
```

**Expected behavior:**
In [Angular 15.1.0](https://github.com/angular/angular/releases/tag/15.1.0) developers are allowed to use self closed tags for custom elements https://github.com/angular/angular/pull/48535
Prettier should support this feature

**Comment by fisker** [comment]
Will make a release today.

**Comment by fisker** [comment]
Done https://github.com/prettier/prettier/releases/tag/2.8.3
