### ISSUE TITLE
prettier can break inline linting directives.

### ISSUE THREAD

**Issue by james-lawrence** [prettier/prettier#14166]
prettier's formatting can break code that uses linting directives in comments. particularly eslint-disable-line;

personally EOL comments should be left alone ignoring print width width due to the nature of linting (and other pragmas) directives.. while one can work around it by move to the prior line and using eslint-disable-next-line the directive is now detached from the code its applying to.

that being said; primarily just bringing this up in case it was an oversight.

[related](https://github.com/prettier/prettier/issues/3714)

```typescript
export function toggle(c: JSX.Element | undefined): any { // eslint-disable-line @typescript-eslint/no-explicit-any
```

output:
```typescript
export function toggle(c: JSX.Element | undefined): any {
	// eslint-disable-line @typescript-eslint/no-explicit-any
	const dispatch = storage.get()?.dispatch
	if (!dispatch) return
	const action = actions.modals.toggle(c)
	dispatch(action)
	return action
}
```
options:
```json
{
  "semi": false,
  "trailingComma": "all",
  "singleQuote": false,
  "useTabs": true,
  "proseWrap": "never",
  "printWidth": 120
}
```

**Comment by thorn0** [comment]
This is a [well-known problem](https://prettier.io/docs/en/rationale.html#comments). It can't really be fixed as these comments operate on the line level whereas Prettier doesn't and splits and joins lines all the time. See also #5411
