### ISSUE TITLE
Number array, Variable mixed

### ISSUE THREAD

**Issue by karikera** [prettier/prettier#14161]
**Prettier 2.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKA3AhgJwAQZ4C8eAjANzrqRQDOMeUArgLYBGcOtxeA2unjwAGAB5ChAGmFjJ08RIF4A9EryQWLBDEWj5BKbsmKVaiBq3oAupSjVo9Rqw5cATD35RBhgzJ-zjquqasDq+ZH5GnsqBZsHaUNboIBIgEAAOMACW9siguDgQAO4ACrgItMggWAA2hVgAnhUpbDhYYADWcDAAyliaADKZUHDIAGY1tHDNrR1d3WltQwDmyDA4TFMgcOxwACa7e-1YUEtMWEtwAGIQOCxYMFknlVhMMBDJIAAWMCzVAOqfTLwWgLMBwbrlIGZDBA+qVMC0JogIaTHAwYqtJZ3MYTTYAK1oIm6y2qcAAikwIPAcdVJikFlxOJU2FgONUPmkcEMYH9MrsYJ9kAAOSQgTkQSZ-VppSqcuCojAjFIAR0p8Ax6QqKCwtAAtMM9nsPjg4KrMiaMedsUhxrTNpMWJlVut7SS4ABBB5ctivODFTiDYY0ukgWhuilUkY23EpGCs3n8wVIFyx1qZarLADCsSwlXlAFYPkxJgAVVla20hjAbACSUAOsG6YC5GXd9e6MHqpODcAAvr2gA)

```sh
--parser babel
```

**Input:**

```jsx

var v = 1;

const numbers = [
  0x00, 0x00, 0x00,
  // comment
  0x00, v, 0x00,
  // comment
];

const numbers2 = [
  0x00, 0x00, 0x00,
  // comment
  0x00, 1, 0x00,
  // comment
];

```

**Output:**

```jsx
var v = 1;

const numbers = [
  0x00,
  0x00,
  0x00,
  // comment
  0x00,
  v,
  0x00,
  // comment
];

const numbers2 = [
  0x00, 0x00, 0x00,
  // comment
  0x00, 1, 0x00,
  // comment
];

```

**Expected behavior:**
I wish the number array allows a few variables.

**Comment by thorn0** [comment]
This request looks okay in this specific case, but Prettier has to solve the problem in the general case. So what exactly is your proposal? I don't think it'd be okay if Prettier started to alternate between different formattings when a number is added/removed in an array of identifiers.
