### ISSUE TITLE
SyntaxError when js comment in vue file contains `<script>` tags

### ISSUE THREAD

**Issue by ydcjeff** [prettier/prettier#14173]
**Prettier 2.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wB8AOlAPQBUFpABBTQAZO30bb4w3pwwCueJKHRqoymXAUHCmDFmVJwAHnghZOAEzgAzAIa8ANp2ABfANylR4joJAAaEBAI5o6ZKB1YsEAO4AFDwiuKDr63joAnq72AEZYOmAA1jwAyjoAtnAAMjhQcMi6+twxcYkpePE5AObIMFi8cPZwadFw6prqmTpQlbw6lXAAYqppOjAwVcggejAQdiAAFjBp+gDq8zjw6OVgcMmBGzgAbhvhk2DoUSA53Gq+cZUj+SFFIABW6IrJVfpwAIq8EHgT0KDRA5SwN0mh3qczwuFgKxw6hg82QAA4AAz2OEQbgrOJ4SZwuA3Q55ewARwB8DujiCU3QAFpcq1WnMsHAqTgOXc+o8kAUXtw0jganVQehvnAAIJjXDRXg0uBYbK5YFCqX-QF5AXPUEwHTRRHI1FIABM9lqOhw+iqAGEIGl+SASQBWOa8bgAFUNQUFoOhcAAklBNLBkuwCNLQ8kYOEfuq4MZjEA)

```sh
--parser vue
```

**Input:**

````vue
<script>
/**
 * ```
 * <script setup>
 * </script>
 * ```
 */
export default {};
</script>

````

**Output:**

```vue
SyntaxError: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (9:1)
   7 |  */
   8 | export default {};
>  9 | </script>
     | ^^^^^^^^^
  10 |
```

**Expected behavior:**

**Comment by fisker** [comment]
Try put this code in a html file and run in browser.
