### ISSUE TITLE
Odd place for line breaks in object literal with long prop name

### ISSUE THREAD

**Issue by altano** [prettier/prettier#1417]
https://fburl.com/iajgnnpx

I would consider this already pretty:

```js
const o = {
  somethingThatsAReallyLongPropName:
    this.props.cardType === AwesomizerCardEnum.SEEFIRST,
};
```

outputs

```js
const o = {
  somethingThatsAReallyLongPropName: this.props.cardType ===
    AwesomizerCardEnum.SEEFIRST
};
```

**Comment by vinhlh** [comment]
@vjeux @altano How about this case
```js
     const g = classnames({
    -  "some-prop": longLongLongLongLongLongLongLongLongLongLongLongLongTooLongVar ||
    -    1337
    +  "some-prop":
    +    longLongLongLongLongLongLongLongLongLongLongLongLongTooLongVar || 1337
     });
```

Should work in the same way with [AssignmentExpression](https://prettier.github.io/prettier/#%7B%22content%22%3A%22someProp%20%3D%20longLongLongLongLongLongLongLongLongLongLongLongLongTooLongVar%20%7C%7C%201234%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D), right?
