### ISSUE TITLE
Angular expression parentheses removed with nullish coalescing operator

### ISSUE THREAD

**Issue by pbechliv** [prettier/prettier#14196]
**Prettier 2.8.3**
[Playground link] https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAy5u3AQQDKQgLxMQUCAFoAVgGdyNQtNx0B8oROZRy5dqQGYdevak6l8AvmwEAlIZfEgArjABm0gBzaWp-fgAkvjcpAycAJ7kMMF0pKgA9EEhYX6m5pbWAHICFs4AJnDyYABOAJYADjBl0BLkkLAIMM6RfBBZMKRQ+L66+glshsZpqABGEPkRJunE5ADa8iVgALrOABQAHuQAZNvkEQCU5AD8x+QAXtpscHR0EOQA7hAldPnoqABCdgzk+JRligB5A4PAArOQPhAynQ4CUKnQAIbwAB0iWI0zMQlwdkCxHwGNMDzKUHyEAeyIA5gjyKJyO4XFAwNVoOQ1kdgOQqciAI7IioueSUNYIkoUlw0JryI4AXwA3JyETyafNlvKuXRlQBqKBwB7kTBIuCytL+KlrADkpTghvNABpyOaAKoCaQADXd7ukhDtDoRbgg5oOaoRFvkCHyPvNFQRFLgADcyrrAyb+licXiCag07j8ORFmBnNQYBV5EgEgkHpXKRAIBSYdIEVAEXQItUwPJkZAaAlG83W2V28iFHVhIQsrh9aQAGKkb6JbMZkYJcaTHSJEHcBggW0gCBVGpQeTIUAikpk4gihBHlDNh4IiJHnejEoIsAAazgMCECIl3GJcGQdxmzDJ8X3fT8hGjMBiQpZAYBKFw4B3OAaFGOB8kKfJuEbMUYzgKdnhoJFqigWCb39bcQGoegAHV-ngeQoLgIQrzKaoExgCJkHAeRHxAYkwxKGBiBfCkiMA4CkJABQNiEGCYQARRcCB4AkugQJAaMSkE7icJcRESkoipylgGiynyGBKGQLwAAYd2MiAwxol8Km44yilhOMAJ3bllPgES92vEAEXkaQdXQ9DKJKOBfLKaKRJjcSkCA9SpLDGgyjghC0vkuABBgeCylGNw4GIWE-x1NSNPkXKlJUgDkskncYARUYzIsqykAAJmal9oRg3AIBoJKQCKUFKIFOB8Fa68Uo0uNEMCEkmiEUpKhgAQSSETiYSquBpWlIA

**Input:**

```jsx
"(x && y) ?? z"
```

**Output:**

```jsx
"x && y ?? z"
```

**Expected behavior:**
Expecting the parentheses to stay there as otherwise the nullish coalescing operator won't be evaluated if the first variable is null.
It is working as expected with the typescript parser.
Also if we replace ?? with || the parentheses stay there in angular parser.

**Comment by thorn0** [comment]
The `??` type node has the wrong type: `BinaryExpression` instead of `LogicalExpression`.

**Comment by fisker** [comment]
Fixed  by #14216
