### ISSUE TITLE
--loglevel=error and --check have incompatible interop

### ISSUE THREAD

**Issue by runspired** [prettier/prettier#14197]
The default prettier `loglevel` is `log`. When running `prettier . --check` the name of every file checked is printed which adds a large overhead to the time it takes to run prettier. Attempting to use `prettier . --check --loglevel=error` to only print check failures instead of all log output results in no output at all.

**Environments:**

- Prettier Version: 2.8.2
- Running Prettier via: CLI
- Runtime: Node v18.12.1
- Operating System: macOS
- Prettier plugins (if any): none

**Steps to reproduce:**

Run prettier with `--check --loglevel=error` on files

**Expected behavior:**

prettier lint failures are printed to stdout

**Actual behavior:**

only the overall process exit status is printed

**Comment by thorn0** [comment]
Doesn't `--loglevel=warn` do what you need?
