### ISSUE TITLE
Sub-optimal newlines around property lookup

### ISSUE THREAD

**Issue by altano** [prettier/prettier#1419]
Don't know if this can be fixed in a generic way but:

Code that is already pretty:
```js
someReallyLongThingStoredInAMapWithAReallyBigName[pageletID] =
  _someVariableThatWeAreCheckingForFalsiness
    ? Date.now() - _someVariableThatWeAreCheckingForFalsiness
    : 0;
```

Prettier output:
```js
someReallyLongThingStoredInAMapWithAReallyBigName[
  pageletID
] = _someVariableThatWeAreCheckingForFalsiness
  ? Date.now() - _someVariableThatWeAreCheckingForFalsiness
  : 0;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22someReallyLongThingStoredInAMapWithAReallyBigName%5BpageletID%5D%20%3D%5Cn%20%20_someVariableThatWeAreCheckingForFalsiness%5Cn%20%20%20%20%3F%20Date.now()%20-%20_someVariableThatWeAreCheckingForFalsiness%5Cn%20%20%20%20%3A%200%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by azz** [comment]
Merging this into #2482
