### ISSUE TITLE
Syntax error for import type

### ISSUE THREAD

**Issue by AHHusam** [prettier/prettier#14200]
**Environments:**

- Prettier Version: 2.8.3
- Running Prettier via: CLI `prettier --write ...`
- Runtime: Node.js v18.12
- Operating System: macOS
- Prettier plugins (if any): eslint-config-prettier
- Typescript version: 4.7.4

**Steps to reproduce:**

In a Typescript project, create 2 files
* Price.tsx
* index.ts (index.tsx is ok too)

From Price.tsx, export the following:
```tsx
export interface PriceProps { }
export const Price = (props: PriceProps) => (<></>);
```

And from index.ts export the following:
```ts
export { Price, type PriceProps } from './price';
```

Then format these files by running prettier from the CLI, for me, that's `yarn format`
Which runs: `"format": "prettier --write \"**/*.{ts,tsx,js,md,css,json}\"",`

**Expected behavior:**
Shouldn't complain about the export type syntax

**Actual behavior:**
> SyntaxError: ',' expected.

![Screenshot 2023-01-18 at 10 04 17](https://user-images.githubusercontent.com/117280525/213133290-3909f618-b531-4c73-8f7a-bfcb5c8e1291.png)

**Comment by fisker** [comment]
Can't reproduce, make sure you are using current parser

**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACYPABWwEsw4AaPGATwzmLIpIgwGc8BfPAM2wgBbPAHIAdAHoMzOCIDcISiDYxS0dslABDbAIDuRHQg0otAGz1baGpQCNsWsAGs4MAMpbBcADKkocZF5zdioQe0cXdwxHPwBzZBhsAFdQuEFbOAATTKzvLShYpK1YuAAxHEEtGFUC5BAtJJgIRRAACxhBMwB1VtJ4dmiKN2M+0gA3Pto6sHYbED8Q3BJiysDg0IArdjQ3OLM4AEUkiHg1sxClaOxFuroGdjAyDBgW6T8YLtJMmFbkAA4AAyXAQhLoODB1aRwRZjAJKACOx3grA4dS07AAtP4slkWtg4IjSPjlrFVkggudQiFBKQEskqXs4ABBapkWyNOBEODYXz+M4XEDsRlHE4BcnrJQwLS2T7fX5IABMkocpDMcQAwkIyah2ABWFpJEIAFWlJgpArGKQAklAcrA3I9SM8mba3HR9vy4FwuEA)

```sh
--parser typescript
```

**Input:**

```tsx
export { Price, type PriceProps } from './price';
```

**Output:**

```tsx
export { Price, type PriceProps } from "./price";

```

**Comment by AHHusam** [comment]
You're right @fisker, I created a fresh project and prettier is working as intended without any syntax errors.
