### ISSUE TITLE
feat: add ability for `trailingComma` to add a comma to single-line comma-separated syntactic structures.

### ISSUE THREAD

**Issue by damonholden** [prettier/prettier#14205]
While I can understand the reason for the multi-line-only functionality of the `trailingComma` option, it would be really nice to be able to add the formatting to single-line comma-separated syntactic structures as well. This practice can address errors in code such as `const coolWords = ['radical', 'mathematical', varThatStoresCoolWord];`, a change such as `const coolWords = ['radical', 'mathematical', varThatStoresCoolWord ('legen' + 'dary')];` would turn `varThatStoresCoolWord` into a function invocation, and display no syntax errors. In addition, its just better logic to say trailing commas **all the time**, rather than trailing commas **sometimes**.

So, for example, with the following line of JavaScript:

```
const fruits = ['banana', 'watermelon', 'mango'];
```

…a Prettier format including the the following option:

```
//…
trailingComma: "<es5|all>"
//…
```

…should result in:

```
const fruits = ['banana', 'watermelon', 'mango',];
```

## Playground Demo

**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzATgVwEsY1MBeTAbQHIAjAQykfuoBpNqB3e+XAWzgAbaGw59GAcwhsAugG4QrEBAAOMQumSh6uXBE4AFHQjTIQ9QdwCeppbVz0wAazgwAyvQEAZQlDjJsCzQ4OwdnVzcVR18JZBgCEJA4Plo4ABM09K9JfHoJOAAxCH4edShYlHp8GAhFEAALGD5BAHV64jg0KLA4NxNiQgA3YiszMDRbEF9g3BgDBwlxAKDEgCs0AA83GME4AEV8CHhlwWClKNwZswZUwTqVXF8YFsI0mHrkAA4ABnO9YJaDhUZgenTguEG-iUAEdDvB5qpTJU0ABaPzpdJ1XBwWGEbHzPJLJCBU6JYJ8QhxBJKNA7OAAQRg8UItGqcAM4J8fhOZxAtPKuwOR38xJWShg9FoLzeHyQACZxQ5CIIYgBhCB8InmQR3JT4YIAFUlSJJvMG+DgAEkoJlYG4wI81PSbW4YFZdjy4ABfL1AA)

```sh
--parser babel
--trailing-comma all
```

**Input:**

```jsx
const fruits = ['banana', 'watermelon', 'mango',];
```

**Output:**

```jsx
const fruits = ["banana", "watermelon", "mango"];

```

**Expected behavior:**
```jsx
const fruits = ["banana", "watermelon", "mango",];

```

**Comment by Nysosis** [comment]
> In addition, its just better logic to say trailing commas all the time, rather than trailing commas sometimes.

Agreed.

I was trialing switching from eslint/stylelint to prettier on a fairly small private project, and this is tripping me up as I work with trailing commas everywhere.

**Comment by alexander-akait** [comment]
Sorry, we don't want to do this and it won't be implemented
