### ISSUE TITLE
Handlebars / Glimmer: Square brackets removed from array index - causes SyntaxError

### ISSUE THREAD

**Issue by davidtaylorhq** [prettier/prettier#14207]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgAc4XQGzgOgG0BGAXXygEMBbOAXzoB0o1Ns8iyGQAaEbGAEtoAZ2ShKAJ0kQA7gAUpCMSko5ZlAJ5i+AI0mUwAazgwAyjTgAZQVDjIAZmpFw9B46bPpDtgObIYSQBXVxA4al04ABMo6KtKKF8gyl84ADEISWpKGCFE5BBKIJgIXhAACxhqHAB1csF4EW8wODNlBsEANwbNArARHRBbF0kYeQNfbMdnUIArEQAPMz88AEUgiHhpnBc+b0kRgt8cQWpaSTL0SVsYGsEomHLkAA4ABj2ZFxqDdAKruBGnXsfAAjht4ONsCpCiIALR2aLRMqSOBgwQo8YpKZIJw7UIuaiCALBfErOAAQVy110xTg8jgkhsdm2uxAIjJ6029hxMz4MEoujuDyeSAATHyDIITokAMIQM6UAoAgCsZSCLgAKgKVLjWZ0QgBJKCxWBmMDXdAwcnGswwTR4Fn0OhAA)

```sh
--parser glimmer
```

**Input:**

```hbs
{{people.[1].name}}
{{people.[1]}}
```

**Output:**

```hbs
{{people.1.name}}
{{people.1}}
```

When parsed, this output produces a syntax error on the second line

```
SyntaxError: Parse error on line 2:
...e.1.name}}{{people.1}}
----------------------^
Expecting 'ID', got 'NUMBER' (2:10)
  1 | {{people.1.name}}
> 2 | {{people.1}}
```

**Expected behavior:**

Prettier should only remove square brackets when the array index is followed by another property.

The correct output for the given input would be:

```hbs
{{people.1.name}}
{{people.[1]}}
```

**Comment by shogohida** [comment]
Hi guys! Can I work on this?

I assume we need to change this file (Not sure which function yet)
https://github.com/prettier/prettier/blob/main/src/language-handlebars/printer-glimmer.js

**Comment by fisker** [comment]
@shogohida Still interested? Related code should be here https://github.com/prettier/prettier/blob/ddf3b43c33e2e98f6413b5232ad623876d96738e/src/language-handlebars/printer-glimmer.js#L396-L398

According to [this](https://handlebarsjs.com/guide/expressions.html#literal-segments), there are other cases except numbers, need put in `[]`.

**Comment by shogohida** [comment]
@fisker 
Yeah, thanks for your comment!

I checked the link you provided. Is this the case for this issue?
![スクリーンショット 2023-03-25 22 10 31](https://user-images.githubusercontent.com/10365357/227719181-7f8fcae7-b074-41ad-9cfc-b50335f011de.png)

I'm not sure how I should change the code yet... Can you give me more advice?

**Comment by kennyhngo** [comment]
Hi, I haven't seen any updates on this so I was hoping I could start working on it. I've gotten a bit of progress with it.
