### ISSUE TITLE
Allow parentheses when JSDoc to allow intellisense

### ISSUE THREAD

**Issue by EloB** [prettier/prettier#14227]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhoHoAqZmgASoEMYBLKgGa84tYACU4kchgA8VGOV5QA5gBoa8xSoB8AXxrNGNABTAAOlBo0AFnBw4ISGgEYAzK4Dsqi7oCUAbhBVEAgSPmgqZFAucnIIAHcABRiESJQuHHiuAE9I4IAjci4wAGs4GABlLlQ4ABklOGQBDKo4AqLS8oqSYqVlZAUsNpA4VHy4DAwJ2q4VLC5lOAAxClQePhVkEC4sGAggkGsYVBwAdWteeCoesDgK1MveADdL7K2wKjyQJVbKRKLlGsmi1hgArKhECp9PAARSwEHgwJwrWCPXIvy2+S44xwBxIWhgp14GBg1mQAA4AAyouKtU5FEhbfEiODkJ6NYIAR3h8H+oTS2yoAFooHAJhMDuQ4NzeFL-gsgUhmsjhq1ULwBuQhsEqNC4ABBGAKXj5XZwRKs+qipEokC6lSwnmNJUg4IwbFEklkpAAJjdRV4OD6AGEIKhFSMqABWA5YVoAFWxaWVtqeQwAklAprAKmBFGF9VmKjBsngbXBdLogA)

```sh
--parser babel
```

**Input:**

```jsx
module.exports = /** @satisfies {Record<string, string>} */ ({
  hello: 1337,
});
```

**Output:**

```jsx
module.exports = /** @satisfies {Record<string, string>} */ {
  hello: 1337,
};

```

**Expected behavior:**
Keep those parentheses to not break intellisense.

```jsx
module.exports = /** @satisfies {Record<string, string>} */ ({
  hello: 1337,
});
```

Here is an example of using `@satisfies` jsdoc. https://github.com/microsoft/TypeScript/pull/51753

![prettier](https://user-images.githubusercontent.com/476567/214179620-3f27356b-9ce1-4dc3-96a8-db30a4441391.gif)

**Comment by EloB** [comment]
It becomes more and more popular to include JSDoc for configs etc.

Here is for instance Next.js official documentation.
https://nextjs.org/docs/api-reference/next.config.js/introduction
```js
/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  /* config options here */
}

module.exports = nextConfig
```

At the moment I have to disable prettier because it removes those parentheses so I wasn't able to use `@satisfies` JSDoc when I had prettier running.

**Comment by EloB** [comment]
How do we start a discussion or get some traction on this? What alternatives do we have?

I really want to continue use Prettier it's amazing! I also want to use best practices with JSDoc. Especially when it improves intellisense.

I have no experience with the Prettier team or this codebase. I only have love for what you guys created.

Is there something that I can help with? I don't know how your process work... :)

**Comment by fisker** [comment]
Is `@overload` possible to use in such places?

**Comment by fisker** [comment]
#14262

**Comment by EloB** [comment]
@fisker haven’t tried it yet but you are amazing!
