### ISSUE TITLE
List of AST issues blocking TypeScript support

### ISSUE THREAD

**Issue by azz** [prettier/prettier#1422]
Here's a list of issues encountered when implementing some TypeScript syntax features in #1410.

 * [x] `ClassDeclaration`, `ClassDeclaration`, `TSAbstractClassDeclaration`: `superTypeParameters` is missing in the AST:
    ```ts
    class X extends Y<T> { }
    ````
    _PR: eslint/typescript-eslint-parser#243_

 * [x] `ClassProperty`: abstract properties. Either need new AST type (`TSAbstractClassProperty`), or an `isAbstract` prop.
    ```ts
    class X{ 
        abstract y: any; 
    } 
    ```
    _PR: eslint/typescript-eslint-parser#238_

 * [x] Type constraints for generic types:
    ```ts
    type X <T extends string> = T;
    ```

    _Note: work in progress: eslint/typescript-eslint-parser#189_

 * [ ] `*Declaration`: `declare` modifier.
    ```ts
    declare function foo() {}
    declare var x: string;
    declare class X {}
    ```
   _Note: #1436 solves this by looking at the source code rather than the AST._

 * [x] `TSAbstractMethodDefinition`: The parser detects this constructor as type `"MethodDefinition"`, kind `"constructor"`.
    ```ts
    class X {
      abstract constructor();
    }
    ```
    _PR: eslint/typescript-eslint-parser#229_

See #1306 for the nodes that are missing or lacking printer definitions. Notably: namespaces (`namespace`/`module` keyword), `interface`, and `enum`.

**Comment by vjeux** [comment]
Thanks for building that list. cc @JamesHenry

**Comment by despairblue** [comment]
@vjeux what do you think about adding a definition file for the missing ts nodes to prettier (like the one @Pajn [works on](https://github.com/Pajn/ast-types/blob/2e2a468e4283e69e1d11c71c25e2e61c4b4ee1cf/def/ts.js)) and initializing `ast-types` with [their forking method](https://github.com/Pajn/ast-types/commit/2e2a468e4283e69e1d11c71c25e2e61c4b4ee1cf#commitcomment-21443200) to include those types. I just tried that for `TSNamespaceExportDeclaration` and it seems to work:

```js
  def("TSNamespaceExportDeclaration")
    .bases("Declaration")
    // needs more like `modefiers` and `decorators`
    .build("name")
```

**Comment by vjeux** [comment]
@despairblue that sounds like a good idea :)

**Comment by JamesHenry** [comment]
`superTypeParameters` and `TSAbstractClassProperty` have now been added to the AST

**Comment by despairblue** [comment]
@JamesHenry I have a problem parsing things in a module declaration:

```ts
module A {
    export class A {
    }
}
```

The module body yields a `TSNamespaceExportDeclaration`:

```ts
{
  type: "TSModuleDeclaration",
  range: [46, 98],
  loc: { start: { line: 6, column: 0 }, end: { line: 9, column: 1 } },
  transformFlags: undefined,
  decorators: undefined,
  modifiers: [
    {
      type: "TSDeclareKeyword",
      range: [46, 53],
      loc: { start: { line: 6, column: 0 }, end: { line: 6, column: 7 } }
    }
  ],
  name: {
    type: "Literal",
    range: [61, 64],
    loc: { start: { line: 6, column: 15 }, end: { line: 6, column: 18 } },
    value: "B",
    raw: '"B"'
  },
  body: {
    type: "TSModuleBlock",
    range: [65, 98],
    loc: { start: { line: 6, column: 19 }, end: { line: 9, column: 1 } },
    transformFlags: undefined,
    statements: [
      {
        type: "TSNamespaceExportDeclaration",
        declaration: {
          type: "ClassDeclaration",
          range: [79, 95],
          loc: { start: { line: 7, column: 11 }, end: { line: 8, column: 5 } },
          id: {
            type: "Identifier",
            range: [85, 86],
            loc: {
              start: { line: 7, column: 17 },
              end: { line: 7, column: 18 }
            },
            name: "B"
          },
          body: {
            type: "ClassBody",
            body: [],
            range: [87, 95],
            loc: { start: { line: 7, column: 19 }, end: { line: 8, column: 5 } }
          },
          superClass: null,
          implements: [],
          decorators: []
        },
        range: [72, 95],
        loc: { start: { line: 7, column: 4 }, end: { line: 8, column: 5 } },
        specifiers: [],
        source: null
      }
    ]
  }
}
```

The actual [typescript AST does not have this intermediate node.](https://astexplorer.net/#/gist/b86511c12dad757a4c3d0a30bee61b20/64994bd39857d63155329a0277ddc67a82630f41)

Is this intended or should the `ClassDeclaration` have a modifiers array with a `TSExportKeyword`?

**Comment by JamesHenry** [comment]
@despairblue The goal is not to match the structure of the TypeScript AST - quite the opposite in fact. We are looking to match existing precedents and conventions in the ESTree AST format wherever possible.

Please could you clarify what you mean by:
> I have a problem parsing things in a module declaration

It would seem everything is being parsed just fine.

**Comment by despairblue** [comment]
@JamesHenry 
> Please could you clarify what you mean by:
>> I have a problem parsing things in a module declaration

Sure. I was expecting the `ClassDeclaration` to either have a `modifiers` array containing keywords like the `TSModuleDeclaration` has or (since `ClassDeclaration` is an ESTree node so changing it is out of question) that the `TSNamespaceExportDeclaration` is just called `TSExportDeclaration` since it contains a class not a namespace (although the differences between `module`, `namespace` and `class` are arguably subtle).

I wasn't trying to propose changing `typescript-eslint-parser` to conform to the typescript AST. Sorry if that came across this way.

Maybe a class creates a `namespace` and thus the naming, it just confused me a little and I wanted to get the input of someone having a little bit more knowledge about the estree and typescript AST.

**Comment by JamesHenry** [comment]
I believe the key thing here is that namespace and module in interchangeable in this specific context.

```ts
module A {
    export class A {
    }
}

// produces the same TypeScript AST as 

namespace A {
    export class A {
    }
}
```

The TypeScript team actually say that `module` is a legacy term in this context, and that `namespace` should be preferred - that is why we went for "namespace" within our TSNode name in the final AST produced by `typescript-eslint-parser`.

Reference: http://www.typescriptlang.org/docs/handbook/namespaces.html

> A note about terminology: It’s important to note that in TypeScript 1.5, the nomenclature has changed. “Internal modules” are now “namespaces”. “External modules” are now simply “modules”, as to align with ECMAScript 2015’s terminology, (namely that module X { is equivalent to the now-preferred namespace X {).

In terms of the usage in prettier... I would think that the wrapping of the `ClassDeclaration` within the `TSNamespaceExportDeclaration` would actually be key to ensuring the correct level of indentation formatting here?

**Comment by despairblue** [comment]
Thanks, just to be sure:

```ts
declare module "A" {
    export class A {}
}
```
=>
* `TSModuleDeclaration`
  * `TSModuleBlock`
    * `TSNamespaceExportDeclaration`
      * `ClassDeclaration`
      
whereas

```ts
declare module "A" {
    class A {} // no export
}
```
=> 
* `TSModuleDeclaration`
  * `TSModuleBlock`
    * `ClassDeclaration`
    
If `TSNamespaceExportDeclaration` is necessary for the indentation, then for the last part the indentation is probably going to be off?

**Comment by despairblue** [comment]
Or maybe just this which will probably solve my confusion:

I assume that whenever there is an `export` keyword, the following node will be wrapped in a `TSNamespaceExportDeclaration`, right?

**Comment by JamesHenry** [comment]
This is exactly the same as with `class A {} vs export class A {}` is it not?

See: http://astexplorer.net/#/gist/b295a7c3740763eeaf0514fa8e5f52cb/7d5306c273be9f075200a753a72b2a865231b84a

**Comment by JamesHenry** [comment]
> I assume that whenever there is an export keyword, the following node will be wrapped in a TSNamespaceExportDeclaration, right?

In the context of a TypeScript namespace/module

**Comment by despairblue** [comment]
Ah, ok got it. Thanks for the effort :)

**Comment by JamesHenry** [comment]
No worries, we're all trying to figure this out as we go 😄
