### ISSUE TITLE
Empty line after class property gets removed when using flow parser

### ISSUE THREAD

**Issue by jozan** [prettier/prettier#1423]
[Example code](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20%40flow%5Cnimport%20React%2C%20%7B%20Component%20%7D%20from%20'react'%5Cn%5Cnclass%20TestClass%20extends%20Component%20%7B%5Cn%20%20state%20%3D%20%7B%7D%5Cn%5Cn%5Cn%5Cn%5Cn%20%20render()%20%7B%5Cn%20%20%20%20return%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

Toggle parser to babylon/flow to see the difference.

![prettier-vscode-tussi](https://cloud.githubusercontent.com/assets/388265/25420884/06ff464c-2a63-11e7-9671-36e82c2512c1.gif)

**Comment by vjeux** [comment]
Great find, this looks like a bug in the flow parser where location is off.

![image](https://cloud.githubusercontent.com/assets/197597/25449785/b9262d5a-2a71-11e7-8c1a-cd7312530700.png)

**Comment by vjeux** [comment]
I created https://github.com/facebook/flow/issues/3812 on the flow side to get it fixed.

**Comment by vjeux** [comment]
This got fixed upstream. In two weeks when they release the next version, it'll be fixed in prettier.

**Comment by jozan** [comment]
Hooray to get this fixed! Thanks! 🎉 👍

**Comment by vjeux** [comment]
It's fixed :)
