### ISSUE TITLE
Block comment starting with double colon becomes duplicated

### ISSUE THREAD

**Issue by wchargin** [prettier/prettier#14231]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mUcA7pgLICGADpgPQBUSSmAPBgE4CWUA5gBpiAVwC2AIzicAfJkb0AFAEoA3CAEgINGN3TJQVTpwikACoYRpkIKgBtSVAJ5WN4zlTABrODADKVUTgAGV44ZGw7NDhXdy8fXxoPXj5kGE5haJA4CTgAE1y8oKp+YSo+OAAxCE5RKhgdfmsqYRgIdRAACxhRWwB1Du54NESwOF9LQe4AN0HHazA0FxBeKM4YU3c+WvDIzIArNAAPX2TbOABFYQh4HdsojUTOVetxKklbdpoeWF7uXJgOsgABwABgexiivXcNGsXzgqymYQ0AEcrvANlorCgqGgALQkPJ5dqcOCo7gkjZlbZICJ3TJRUTcVLpemnC5osI03YaGBvX7-QFIABMPPc3FsyQAwhBRNSsmgAKztYRRAAqbyxtPuICmGQAklACrBfGAeNoAIKG3wwRxnW5RAC+DqAA)

```sh
--parser babel
```

**Input:**

```jsx
const foo = new Map /*:: <string, number> */();
```

**Output:**

```jsx
const foo = new Map /*:: <string, number> *//*:: <string, number> */();

```

**Expected behavior:**
The comment shouldn't be duplicated! (In this example, the output should
be the same as the input.)

If the original comment is `/*:::: foo*/`, then the extra comment in the
output is `/*:: :: foo */`: i.e., two extra spaces are inserted. Maybe
this has something to do with Flow comment syntax?

This bug seems to occur under the `babel` and `babel-flow` parsers, but
not under the `flow` or `babel-ts` parsers.

I discovered this bug after writing some code in a new file, and, after a while, noticing that it contained the lines

```javascript
  const lastEventById =
    new Map /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> */ /*:: <string, Event> *//*:: <string, Event> */();
```

because my Prettier-on-save hook had been progressively adding a new
comment each time I saved. :upside_down_face: 

(Search keywords: double colon duplicate comment block flow t_paamayim_nekudotayim)

**Comment by cagils** [comment]
To provide additional information, I think this is triggered by the 'new' expression. Here are the correct typescript AST vs incorrect babel AST:

input:
```ts
new d /*::xxxxxxxxx*/()
```

typescript AST:
```json
{
  "type": "Program",
  "body": [
    {
      "type": "ExpressionStatement",
      "expression": {
        "type": "NewExpression",
        "callee": {
          "type": "Identifier",
          "name": "d",
        },
      },
    }
  ],
  "sourceType": "script",
  "tokens": [
    {
      "type": "Keyword",
      "value": "new",
    },
    {
      "type": "Identifier",
      "value": "d",
    },
    {
      "type": "Punctuator",
      "value": "(",
    },
    {
      "type": "Punctuator",
      "value": ")",
    }
  ],
  "comments": [
    {
      "type": "Block",
      "value": "::xxxxxxxxx",
    }
  ]
}
```

babel AST:
```json
{
  "type": "File",
  "program": {
    "type": "Program",
    "sourceType": "module",
    "interpreter": null,
    "body": [
      {
        "type": "ExpressionStatement",
        "expression": {
          "type": "NewExpression",
          "callee": {
            "type": "Identifier",
            "name": "d",
            "trailingComments": [
              {
                "type": "CommentBlock",
                "value": "::xxxxxxxxx",
              }
            ]
          },
          "typeArguments": null,
          "arguments": []
        }
      }
    ],
  },
  "comments": [
    {
      "type": "CommentBlock",
      "value": "::xxxxxxxxx",
    }
  ],
  "tokens": [
    {
      "type": {
        "label": "new",
        "keyword": "new",
      },
      "value": "new",
    },
    {
      "type": {
        "label": "name",
      },
      "value": "d",
    },
    {
      "type": "CommentBlock",
      "value": "::xxxxxxxxx",
    },
    {
      "type": {
        "label": "(",
      },
    },
    {
      "type": {
        "label": ")",
    },
    {
      "type": {
        "label": "eof",
      },
    }
  ]
}
```
As you can see, with babel the

**Comment by fisker** [comment]
This already fixed in next branch [playground](https://deploy-preview-9583--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mUcA7pgLICGADpgPQBUSSmAPBgE4CWUA5gBpiAVwC2AIzicAfJkb0AFAEoA3CAEgINGN3TJQVTpwikACoYRpkIKgBtSVAJ5WN4zlTABrODADKVUTgAGV44ZGw7NDhXdy8fXxoPXj5kGE5haJA4CTgAE1y8oKp+YSo+OAAxCE5RKhgdfmsqYRgIdRAACxhRWwB1Du54NESwOF9LQe4AN0HHazA0FxBeKM4YU3c+WvDIzIArNAAPX2TbOABFYQh4HdsojUTOVetxKklbdpoeWF7uXJgOsgABwABgexiivXcNGsXzgqymYQ0AEcrvANlorCgqGgALQkPJ5dqcOCo7gkjZlbZICJ3TJRUTcVLpemnOAAQXqPHELTgpikIRIt3uIDQbMu1zCNN2Ghgb1+-0BSAATLL3NxbMkAMIQUTUmy2D4aYRRAAqbyxtJFUwyAEkoAVYL4wDxtOyHb4YI4zsK4ABfP1AA), will release as v3.
