### ISSUE TITLE
incorrectly removes parentheses in typescript when //prettier-ignore is inside them

### ISSUE THREAD

**Issue by MichaelBelousov** [prettier/prettier#14238]
**Prettier 2.8.3**
[repro link](https://github.com/MichaelBelousov/prettier-bad-typescript-format-repro)
clone and run `npm test` to see the prettier-ification of index.ts

```sh
# Options (none)
```

**Input:**

```tsx
export const foo = (
  // prettier-ignore
  bar as Baz
).qux;
```

**Output:**

```jsx
export const foo = // prettier-ignore
bar as Baz.qux;
```

**Expected behavior:**

doesn't remove parentheses around a typescript `as` cast:

```jsx
export const foo = // prettier-ignore
  (bar as Baz).qux;
```

**Comment by fisker** [comment]
Fixed by #14406
