### ISSUE TITLE
Improve GraphQL union types formatting

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#14234]
I think we can make consistency for printing union types (`|`) between TS and Gql. What do you think?

**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBXKBLaACAynAQwCcwALAJTgGdUAbGbAXgB0oAfbAYWgDM4iEYOBwBi1GBgBuBWtg7coQogw4A1BKjhyuvfoOHYxVCdNnzoSldnVRNrEABoQEAA4ToVZKGJEIAdwAFYgRPFBk-AgBPTycAIyICMABrOBhcAgBbOAAZDCg4ZB4ZKjg4hOTU3BdEvIBzZBgiTSc4DNi4ABMOzuyCKFrUAlq4EQgiDIIYCX7kEAJUGAhHEFIYDNoAdVIMeCpqoXwoKh2pHcjZsCoYkDyS5QCE2onC4tKQACsqAA9cOto4ACKqAg8BetBKTmqRDus1qCRcpAAjrRli4iHkYBsMB0YKRkAAOAAMkN8JQ28NmaOo-EkBSciOB8AerlCcyoAFp8p1OssBAyMAIHkNnkgiuC3iUMhgGk0JX84ABBKbo2ILOABfi5fJgiEgY79f5AkEFUWvJwwAixLE4vFIABM5oSGFodW4GRFIGoAFZlqgSgAVS2hMW6ySaACSUG6sFwYHRbgVUdwMEi-x1cAAvhmgA)

```sh
--parser graphql
```

**Input:**

```graphql
union SearchResult = Conference| Festival | Concert | Venue | Conference| Festival | Concert | Venue

```

**Output:**

```graphql
union SearchResult =
    Conference
  | Festival
  | Concert
  | Venue
  | Conference
  | Festival
  | Concert
  | Venue

```

**Expected behavior:**

```graphql
union SearchResult =
  | Conference
  | Festival
  | Concert
  | Venue
  | Conference
  | Festival
  | Concert
  | Venue

```

**Comment by ArchitGajjar** [comment]
HI @sosukesuzuki - can you please assigned this to me ? this will be my first contribution to prettier library :)

**Comment by sosukesuzuki** [comment]
@ArchitGajjar Go ahead!

**Comment by ArchitGajjar** [comment]
@sosukesuzuki - I made some changes and execute below commands.

> yarn build:website

> cd website/playground

> npm run start

Here, I'm seeing my changes are not reflected in playground when I test. 

How do you verify your changes are reflected while testing into local ?

**Comment by sosukesuzuki** [comment]
```
$ touch test.js
$ yarn debug test.js
```

**Comment by fisker** [comment]
```
$ touch test.gql
$ yarn debug test.gql
```

**Comment by ArchitGajjar** [comment]
Thank you both, I have raised the PR and added changes. Can you please help in reviewing ?
PR - https://github.com/prettier/prettier/pull/15870

Thank you, in advanced!

**Comment by fisker** [comment]
This seems not supported when we add support for it https://github.com/prettier/prettier/pull/2014#discussion_r120681737

**Comment by fisker** [comment]
Supported since 2017 https://github.com/graphql/graphql-spec/pull/323 https://github.com/graphql/graphql-js/pull/907
