### ISSUE TITLE
JSX with ternary not capped to line limit

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#1425]
Prettier output:
```es6
const AddCardLink = (props: {isFirst: boolean, onAdd: () => void}) => (
  <SUIButton
    label={
      isFirst
        ? <fbt desc="label for button to add first country group for some targets">
            Set a target
          </fbt>
        : <fbt desc="label for button to add more country groups for some targets">
            Set another target
          </fbt>
    }
    use="default"
  />
);
```
goes over 80 character limit. But indenting the `desc` argument would make it fit. Ideally we should also be able to break up the long string too though. [improvement]

**Comment by vjeux** [comment]
We added a special case: if you've got a jsx element with a single prop that is a string literal, then we inline it, no matter how long it is. We found that people in this case usually decide to ignore the 80 columns and just put it in one line.
