### ISSUE TITLE
Having emoji in a fail makes blank lines be trimmed in flow parser

### ISSUE THREAD

**Issue by natenorberg** [prettier/prettier#1427]
Once there is an emoji in a file, prettier trims all the blank lines after the emoji:
https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20a%20%3D%201%3B%5Cn%5Cnconst%20b%20%3D%20'two'%3B%5Cn%5Cnconst%20c%20%3D%20'%F0%9F%92%A9'%3B%5Cn%5Cnconst%20d%20%3D%20%5B%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

They are preserved in the babylon parser.

**Comment by vjeux** [comment]
This is a known issue, the flow parser messes up all the locations after any utf8 characters. Good news is, it's fixed in the master branch of flow and a new version of flow will be released today :)

**Comment by natenorberg** [comment]
Awesome sauce! Thanks
