### ISSUE TITLE
Asterisk in Markdown list sometimes isn't replaced by a dash

### ISSUE THREAD

**Issue by pvginkel** [prettier/prettier#14277]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABADwDpXejHKXAKi130NxABoQIAHGAS2gGdlQBDAJx4gDuABV4IOKLgBsBXAJ4c6AIx5cwAazgwAylwC2cADLMocZADMpbOEpXrNWhquMBzZDB4BXayDi7FcABMAwIMuKGcPLmc4ADEIHl0uGBZw5BAuDxgIWhAACxhdSQB1XOZ4NkcwOC0xMuYANzLZNLA2BRBjKx4YIRVnRPNLbwArNkwtF0k4AEUPCHhBySs6Rx4utMSeNQDBKByGHmMYIuYAmFzkAA4ABhX+KyKVBjSDuC760zoARzn4XsZxOk2KgTIFAjkeHAfsxIb0ogMkBYlt4rLpmG5PCjJnAAILJQ6KTJwIRwHhGEyLZYgNjY2bzUyIoZ0GBcRQnM4XJAAJmZKmYkhcAGEILoET42ABWHIeKwAFVZ4iRVPqXgAklBgrAtGBDkwcRqtDBZFNKXAAL5moA)

```sh
--parser markdown
```

**Input:**

```markdown
- x
  - x

* x
  - x

```

**Output:**

```markdown
- x
  - x

* x
  - x

```

**Expected behavior:**
I expect the asterisk to be replaced with a dash. I see some other weird behavior also. If I change the asterisk to a dash but leave the line endings as is, a newline appears before the first nested bullet. In the AST I see some options named "spread" and "loose" that seem to influence this. See [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABADwDpXejHKXQ3fUqEAGhAgAcYBLaAZ2VAEMAnLiAdwAK3BGxQcANnw4BPNjQBGXDmADWcGAGUOAWzgAZRlDjIAZhJZwFS1eo11lhgObIYXAK6WQcbfLgATP389DihHNw5HOAAxCC5tDhgmUOQQDjcYCGoQAAsYbXEAdWzGeBZ7MDgNERLGADcS6RSwFjkQQwsuGAElR3jTc08AKxZMDSdxOABFNwh4fvELGnsuDpT4rhU-fkolrkMYAsY-GGzkAA4ABl2ICwKlOhS6LjgO2uMaAEcZ+G76UVSWKgjP5-Flnl9GM9uhE+kgzAtPBZtIwXO5EeM4ABBRJ7eTpOACOBcAxGeaLEAsDHTWbGOEDGgwDjyQ7HU5IABMDKUjHETgAwhBtLCvCwAKxZNwWAAqTNE8PJtQ8AEkoIFYBowHsGJjVRoYNIJmS4ABfY1AA).

This makes it very difficult in a WYSIWYG editor to get the formatting right (Typora in my case). If there's an option to just force the behavior to e.g. remove all newlines within lists, that would maybe be easier.

**Comment by hks2002** [comment]
I expect the replace action could be config, not auto replace. 
It replaced all my asterisk with a dash, I want to use asterisk not the dash.

**Comment by kachkaev** [comment]
I believe that it is not a bug. A change of the marker denotes a start of a new list.

```markdown
- a

- b

- c
```

↓

```html
<ul>
<li>a</li>
<li>b</li>
<li>c</li>
</ul>
```

```markdown
- a

- b

* c
```

↓

```html
<ul>
<li>a</li>
<li>b</li>
</ul>
<ul>
<li>c</li>
</ul>
```

So replacing the marker in your example would break syntax.

Prettier defaults to `-` and falls back to `*` if there is no other way to denote the start of a new list (i.e. when there is nothing in between two lists). If you use `*` followed by `-` or try `+` (another valid marker), they will be replaced to `-` and `*` (in that sequence).

Closing as intended behavior.

**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABADwDpXejHKXAKi130N11VuqjKMvOKirwJZrtYGoXmRGgM5EQAGhAQADjACW0AM7JQAQwBO6iAHcAChoTKUqgDbbVAT2WSARutVgA1nBgBlVQFs4AGTlQ4yABmpopwtvZOLq7SDn4A5sgw6gCuYSBwHjZwACbZOd6qUHHJqnFwAGIQ6h6qMPJFyCCqyTAQEiAAFjAeJgDqHXLwijFgcK6Gg3IAboMWjWCK1iB+oeowuvZxNUEhaQBWipiu8SZwAIrJEPA7JqGSMeqrjTXqjtk6UO3S6n4wvXLZGAdZAADgADPctKFevZpI1vnBVlMApIAI6XeAbGRGJqKVD+HI5drqODouQkjalbZIYK3NKhDxyRIpeknOAAQTqPxsLTgujg6l8-hudxAijZFyuARpu0kMFUNn+gOBSAATHL7HITPEAMIQDzU9KKACs7WSoQAKgqjLTRVNUgBJKB5WCuMA-WTs52uGAWU4iuAAX0DQA)

```sh
--parser markdown
```

**Input:**

```markdown
- x
  - x

* x
  - x

---

* x
  - x

- x
  - x

---

+ x
  - x

- x
  - x

```

**Output:**

```markdown
- x
  - x

* x
  - x

---

- x
  - x

* x
  - x

---

- x
  - x

* x
  - x

```

**Comment by pvginkel** [comment]
Thank you for looking into this. Do you know whether there's a way to disable this behaviour? I'm considering creating a preprocessor that forces all list markers do dashes, but I prefer a native solution in prettier, if one exists.

**Comment by kachkaev** [comment]
Hmm I’m not sure if that’s achievable via Prettier because Prettier is just a _printer_ of the code you have. You might want to look into Markdonwlint’s [Unordered list style rule](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md004---unordered-list-style). Example (opinionated) setup for Markdowlint + Prettier can be found in [njt](https://github.com/kachkaev/njt/blob/9d040e284381ef37e76b8c325a534938b1fc050c/package.json#L13-L19). That’s a side project of mine, which is completely unrelated to Prettier.
