### ISSUE TITLE
[Typescript]: Prettier removes the necessary parentheses in union and causes a syntax error

### ISSUE THREAD

**Issue by auvred** [prettier/prettier#14271]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKtgXmwB0ptsAfbAClPPKuDvpYDcBDAGwFc4lso3ALYAjOACdmLAL5TK2JmRb0OPPtgDOMcQEsoAcznlZSgJSkQAGhAQMMHdA3JQ7ceIgB3AAquETlFwe7GhO1iLi7GAA1nAwAMrsQnAAMnpwyABmXBpwYRHRsXEYkXr6yNq81nCicAAmtXXJ7Abc7PpwAGIQ4kLsMPYGyCDs3DAQViAAFjBCnADqkzrwGsVgcHF+SzqsS2hDYBqhIHo54jBeEfq9mdm5IABWGgAecaWccACK3BDwN5w51mK4lOQ3QWA0YF0dgmGF0sDmOlqMEmyAAHAAGQHuHJzCIYIawuCnVjpawAR2+8Autn8ww0AFooHA6nUJuI4BSdOyLm1rkgsv87jkhDpyuJKiANG84ABBfq6ESjOBeCSpJl-AGS6VfH7pfm3awwdgiBFIlFIABMhoiOk4pQAwhAhHyQESAKwTbg5XDG-wCzWsXgASSgDVgcUhOjsMtDcXQ7w1cGk0iAA)

```sh
--parser typescript
```

**Input:**

```tsx
type T = 
  | (
    | {
        value: number
      }
    | {
        value: string
      }
  )

```

**Output:**

```tsx
type T =
  |
      | {
          value: number;
        }
      | {
          value: string;
        };

```

**Expected behavior:**
Expecting the parentheses to stay on their initial place or to remove them along with top-level union to get something like this:
```tsx
type T =
  | {
      value: number;
    }
  | {
      value: string;
    };

```

----
Btw, if union contains only one object the prettier is working as intended
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKtgXmwB0ptsAfbAClPPKuDvpYDcBDAGwFc4lso3ALYAjOACdmLAL7MAlKRAAaEBAwwAltADOyUO3HiIAdwAKBhLpRdj7NLpUjx7MAGs4MAMrshcADIaUHDIAGZc2nCOzm4enhgugQDmyDDivCpwonAAJtk5fuxQidzsiXAAYhDiQuwwmkXIIOzcMBDKIAAWMEKcAOodGvDa8WBwnpaDGqyDaI1g2g4ggRHiMKbOiTWh4ZEgAFbaAB6eSZxwAIrcEPDbnBEq8eIrjehY2mDiGurtGJ+wvRpsjAOsgABwABgeRgivWcGEavzgK1YwRUAEcrvB1morE1tABaII5HLtcRwDEaMnrUpbJBhO67CJCDQpNKM05wACCdU+IhacFMEgCQVu9xA2g5l2uwTpOxUMHYIgBQJBSAATPLnBpOEkAMIQIS0kBIgCs7W4EVwiqs9LFrF4AEkoHlYJ4Pl8YJznZ50GdRXBpNIgA)

**Comment by auvred** [comment]
As I understand how it works, it seems that prettier adds top-level union [here](https://github.com/prettier/prettier/blob/37fb53acf33a20379a93bfecea8242c03ce0a4fc/src/language-js/print/type-annotation.js#L181), but since this top-level union has only one child, then [this condition](https://github.com/prettier/prettier/blob/37fb53acf33a20379a93bfecea8242c03ce0a4fc/src/language-js/print/type-annotation.js#L186) returns `false` and union child lost its parentheses.

If [`pathNeedsParens(path, options)`](https://github.com/prettier/prettier/blob/37fb53acf33a20379a93bfecea8242c03ce0a4fc/src/language-js/print/type-annotation.js#L186) will return `true` (e.g if I add one more element to top-level union - [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKtgXmwB0ptsAfbAClPPKuDvpYDcBDAGwFc4lso3ALYAjOACdmLAL5TK2JmRb0OPPtgDOMcQEsoAcznlZSgJTMqg0RNIgANCAgYYO6BuSh248RADuABS8EdxQuX3Y0dwcRcXYwAGs4GABldiE4ABk9OGQAMy4NOGjYhKTkjDi9fWRtXgc4awATRrhGjPYDbnZ9OAAxCHEhdhgXA2QQdm4YCHsQAAsYIU4AdTmdeA0KsDhk4PWdVnW0cbANKJA9QvEYf1j9IbyCopAAKw0AD2SqzjgARW4IPBHpxCg4KuIruN0FgNGBdM5ZhhdLBljpGjA5sgABwABjBPkKy1iGHGSLgV1YOQcAEcAfBbk4QhMNABaKBwVqtWbiOC0nQ827dB5IfIg56FIQ6GriOogDTfOAAQRGuhEUzg-gkWXZwNBcoV-0BORFTwcMHYIlR6MxSAATGbYjpOFUAMIQITCkDkgCss24hVwFpCor1rF4AEkoC1YMk4TpnIqo8l0D9dXBpNIgA)) everything works fine

**Comment by fisker** [comment]
Thanks for the investigation, would you like to fix it?

**Comment by auvred** [comment]
Sure, I'll try to fix it tomorrow

**Comment by fisker** [comment]
Great! Thank you!
