### ISSUE TITLE
Typescript typeof invalid formatting

### ISSUE THREAD

**Issue by dfadev** [prettier/prettier#14283]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgBQCU+wAOlPvpFAM4xFQ4C2hANg-gLz4BtarUoxg+BgAc4YHHAZJ8AcjCEYSgDT4ohNnEVKAYp3SpUATyX4AvhuH5R4qTLkLlAEwgBzTdt37lQxxPK1t7RwlpWXkDNgh0BjhfHT0DABUAJzgANwgM0PsAXSIeeiZwmnwYc2l8AEFWDk4+Kpq4CFQWdi4GASh0NgAjOAzCgSVnaIYlQvsAejnW2obu5v5KcDUN-AAfBxBPL229jbiEuG2HKGsQDRAISVxoBmRQQgyMiAB3AAV3hBeKC4X0I5hed0GGUIYAA1nAYABlfwAGRwUDgyFQPTgEKhsPhCMk0LRXmQMAy6BxIDgQzg7ncdORhCgXnQhC8cEMeQ4MFwLOQIEI6BgEFuIAAFjA2JwAOrinDwKTQuAIgEKnDZBXmAVgBjgkBoxIZGA-KFeDiY7F3ABWDAAHgiSZw4ABFdAQeBkilUokZI0C6rSBhgDI4R5iySh2Ay4IwcXIAAcAAY7pGIIkZVDJALI-IRtkMXcAI7u+Cmh6AwUMAC06LpdLFWRLOCypvZFqQWO4VMSbBwlu7dwYTrgdV5ocGwrgPxGqPRA8SQ5Hbo9GKQ5MpdxghEGMfcceQACYt1CcJwSQBhCBsDvUhgAVjF5zSO8BXcXIGylIAklAGbAERDMMYAadwEWqZ0FzgaxrCAA)

```sh
--parser typescript
--no-semi
--single-quote
--jsx-single-quote
```

**Input:**

```tsx
function a() {
  const animals = [
  	{ species: 'cat', name: 'Fluffy' },
  	{ species: 'dog', name: 'Fido' },
  	{ species: 'mouse', name: 'Trevor' }
  ] as const
  
  type Animal = typeof animals[number]['species']
  // type Animal = "cat" | "dog" | "mouse"  
}
```

**Output:**

```tsx
function a() {
  const animals = [
    { species: 'cat', name: 'Fluffy' },
    { species: 'dog', name: 'Fido' },
    { species: 'mouse', name: 'Trevor' },
  ] as const

  type Animal = (typeof animals)[number]['species']
  // type Animal = "cat" | "dog" | "mouse"
}

```

**Expected behavior:**

```tsx
function a() {
  const animals = [
    { species: 'cat', name: 'Fluffy' },
    { species: 'dog', name: 'Fido' },
    { species: 'mouse', name: 'Trevor' },
  ] as const

  type Animal = (typeof animals[number]['species'])
  // type Animal = "cat" | "dog" | "mouse"
}

```

see also [https://steveholgado.com/typescript-types-from-arrays/](https://steveholgado.com/typescript-types-from-arrays/)

**Comment by fisker** [comment]
This change is intended, see #13546 and #14042

**Comment by EladBezalel** [comment]
@fisker it will be much appreciated if we could have a config to disable this rule,
ATM lints are failing on unchanged files since this change was introduced

**Comment by EladBezalel** [comment]
The code has `typeof·HANDLED_KEYS` and now after upgrading deps we get these kind of errors
```
error  Replace `typeof·HANDLED_KEYS` with `(typeof·HANDLED_KEYS)`  prettier/prettier
```

on files that weren't changed

**Comment by EladBezalel** [comment]
i understand this is expected, i suggest a config to disable it

**Comment by graup** [comment]
As far as I can tell, #13546 doesn't provide any reasoning what's bad about `typeof foo[number]`, could someone help me? There's [this comment](https://github.com/prettier/prettier/issues/13546#issuecomment-1265543962) but it doesn't give a reason against the no-braces version.

I'm not against this, just curious why it is needed.

**Comment by fisker** [comment]
```
type  a = typeof a[a];
const a = typeof a[a];
```

This is confusing for ts beginner.

**Comment by graup** [comment]
I guess I can see how there is a small difference.

```typescript
// Before
const a = [1];
const B = typeof a[0];  // B = 'number'
type A = typeof a[number];  // type A = number

// After
const a = [1];
const B = typeof a[0];
type A = (typeof a)[number];
```

But was there any data suggesting people found it confusing? Seems a bit arbitrary to just change this based on a hunch.

**Comment by fisker** [comment]
I'm the beginner, https://github.com/prettier/yaml-unist-parser/pull/281#discussion_r982267295

**Comment by graup** [comment]
Thanks, appreciate the history!
