### ISSUE TITLE
Is it possible to format a specific piece of Apex code using Prettier in VS code?

### ISSUE THREAD

**Issue by materasawa** [prettier/prettier#14284]
In visual studio code, I can specify a specific range and press Ctrl + K & Ctrl + F to format the selected range, but it does not work well in Apex code. We use Prettier as our formatting tool and it is compatible with APEX.
Is this correct behavior? If it is the correct behavior, are there any plans to implement partial formatting in Apex?

**Comment by sosukesuzuki** [comment]
Prettier Plugins don't support range formatting. In the future, it may be supported. Please see https://github.com/prettier/prettier/issues/11175
