### ISSUE TITLE
mdx v2 multiple lines comments wrong formatting

### ISSUE THREAD

**Issue by gabriele-ct** [prettier/prettier#14287]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwD0AqABACzgG3wixhwEsBnLSrAQywrKgHN84t8n3IBbHhGFgxoAvgB0oE9NlI0aErHSw8ArvhhkOXKgqy9+sIaIkgANCAgAHDdArJQtAE6OIAdwAKThHZS18r2gBPO3MAI0daMABrOBgAZVp+ABkuZAAzPwo4MIjo2LjLSKZmZBhHFWyQOB5QuAATOvqk2hYVWmY4ADEIRx5aGA0WZBBaFRgIMxAcGB58AHVyeApCsDg47zINADdNwOGwChCQJizHGHcI5j70zMqAKwoADzjitgBFFQh4G-ws80LHKdhjw6o9JpZHEwYHMyHVSMgABwABn+LiycwilmGELgpy2cEmAEdPvALlYfCMKABaKBwer1SaOODEshMi7ta5IDK-SpZHhkUrlXmvOAAQQGkNCYzg7jgjhStJ+fxAjBY7xJBK5t3MMFooRhcJwyAATDqImROCwAMIQPi0Ya4gCskxUWQAKnqfNzlVsKgBJKCNWBxMCQ6yiwNxGCBNhKuAiERAA)

```sh
--parser mdx
```

**Input:**

```mdx
{/* hello this is a single line comment */}

{/* this is 
  a multi lines 
  comment */}

```

**Output:**

```mdx
{/* hello this is a single line comment */}

{/_ this is
a multi lines
comment _/}

```

**Expected behavior:**

```mdx
{/* hello this is a single line comment */}

{/* this is
a multi lines
comment */}
```

This can be also verified using the mdx playground: https://mdxjs.com/playground/

**Comment by fisker** [comment]
#12209
