### ISSUE TITLE
Template strings with array chaining variables

### ISSUE THREAD

**Issue by tleunen** [prettier/prettier#1429]
The output doesn't seem right when using a template string with a long "variable" using chaining.

Here's an example:
https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20condition%20%3D%20stripIndent%60%5Cn%5CtAND%20(%5Cn%5Ct%5Ct%24%7BuserIds.map(uId%20%3D%3E%20%60jsondata%23%3E'%7Busers%7D'%40%3E'%5B%7B%5C%22userId%5C%22%3A%20%24%7BuId%7D%7D%5D%60).join('%20OR%20')%7D%5Cn%20%20%20%20)%5Cn%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
This is going to be fixed by https://github.com/prettier/prettier/pull/1385
