### ISSUE TITLE
Brackets around ternary as twice-curried arrow function body are removed

### ISSUE THREAD

**Issue by Josh-Cena** [prettier/prettier#14290]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBNAFOglAAgLwB8OAhjgPw4BGOSOYWA3ADpQbb5HuEnlU12MWIADQgIABxgBLaAGdkoYgCclEAO4AFZQnkpiAGzXEAnvNGUlxMAGs4MAMrEAtnAAyUqHGQAzA7LjmljZ29uJWHgDmyDBKAK4BIHBOlHAAJqlprsRQEbHEEXAAYhBKTsQw0jnIIMSxMBAiIAAWME76AOpNUvCyYWBw9jrdUgBu3cbVYLJmIB7+SjAalhFlPn4JAFayAB72kfpwAIqxEPBr+v6iYUrz1ZTEKfqN4koeMO1SqTBNyAAcAAxXVT+dqWcTVF5weYjLyiACOJ3gSwkuhqsgAtJ40mlGko4AipHilvlVkhfBcEv4nFJonFKfs4ABBCqvSh1OAaOBKdyec6XECyBnHU5eMnrUQwB4fL4-JAAJgllik+kiAGEIE5SYlZABWRqxfwAFQeunJ-JG8QAklAMrB7GBXpJGTb7DBjAc+XAAL5eoA)

```sh
--parser babel
```

**Input:**

```jsx
Y(() => a ? b : c);
Y(() => () => a ? b : c);
```

**Output:**

```jsx
Y(() => (a ? b : c));
Y(() => () => a ? b : c);

```

**Expected behavior:**

For consistency:

```jsx
Y(() => (a ? b : c));
Y(() => () => (a ? b : c));
```

**Comment by fisker** [comment]
Same problem as #11593, they use different logic.
