### ISSUE TITLE
Sort Imported Names

### ISSUE THREAD

**Issue by novalmurtado** [prettier/prettier#14307]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#.....)

**Input:**

```jsx
import { useState, useRef, useCallback, FC, ReactNode, useMemo, useEffect } from "react"
```

**Output:**

```jsx
import {
  useState,
  useRef,
  useCallback,
  FC,
  ReactNode,
  useMemo,
  useEffect,
} from "react";
```

**Expected behavior:**
```jsx
import {
  FC,
  ReactNode,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
```

as you can see the imported names are all sorted so that it is easier when you want to see if a name has been imported or not and looks prettier.

**Comment by fisker** [comment]
It's out scope of Prettier.
This can be implemented as an ESLint rule, why don't you make a proposal  in ESLint or other ESLint plugins?

**Comment by novalmurtado** [comment]
thank you for your suggestion about ESLint rule. i didn't think about that. i think it can be done by prettier. thanks again.

**Comment by novalmurtado** [comment]
> It's out scope of Prettier. This can be implemented as an ESLint rule, why don't you make a proposal in ESLint or other ESLint plugins?

thank you for your suggestion about ESLint rule. i didn't think about that. i think it can be done by prettier. thanks again.

**Comment by kachkaev** [comment]
@novalmurtado you can use ESLint for that. I can recommend [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort), but that’s not the only possible way forward. If you run ESLint before Prettier and don’t forget to add [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier), you’ll get best of the two tools.

**Comment by fisker** [comment]
I don't think eslint-plugin-simple-import-sort sort specifers.

**Comment by kachkaev** [comment]
If you mean 

```ts
import { truncate, formatNumber } from "../../utils";
```
↓
```ts
import { formatNumber, truncate } from "../../utils";
```

, it does (according to README and own experience)

**Comment by fisker** [comment]
Good to know.

**Comment by novalmurtado** [comment]
> @novalmurtado you can use ESLint for that. I can recommend [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort), but that’s not the only possible way forward. If you run ESLint before Prettier and don’t forget to add [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier), you’ll get a good synergy between the two tools.

I didn't realize that the thing I was thinking about already had a solution haha. Thanks guys

**Comment by dansteren** [comment]
Was just re-reading through, [Prettier vs Linters](https://prettier.io/docs/en/comparison). It just got me thinking... sorting of imports doesn't seem like a code-quality issue at all. I think it's strictly formatting. I understand that there's already a working solution in ESLint, but Prettier's whole thing is to take care of these sorts of formatting issues and to have linters only handle code-quality.

With that understanding, I think there's a case for having this implemented in Prettier at some point. It's likely a very low priority, given that there is a workaround, but it'd be nice to have Prettier take care of this as a formatting concern.
