### ISSUE TITLE
Extra lines inserted

### ISSUE THREAD

**Issue by nordsoyv** [prettier/prettier#1432]
If you have a file with a multiline template string, using windows line endings (CRLF) and the flow parser , extra empty lines are inserted in the output.

Example:
Input file with CRLF line endings
```javascript
const aLongString = `
Line 1
Line 2
Line 3
Line 4
Line 5
`;
```

run `prettier test.js --write --parser flow`

Output
```javascript
const aLongString = `

Line 1

Line 2

Line 3

Line 4

Line 5

`;

```

**Comment by demoneaux** [comment]
Seem to remember that this is an old issue. Could you try updating your version of prettier?

**Comment by nordsoyv** [comment]
I'm on version 1.2.2 of prettier , 6.9.2 of node. Windows 10

**Comment by vjeux** [comment]
Thanks, I can now reproduce! Working on a fix.

**Comment by vjeux** [comment]
Was an easy fix :) https://github.com/prettier/prettier/pull/1439

**Comment by nordsoyv** [comment]
Awesome :)
