### ISSUE TITLE
TypeScript 5 support

### ISSUE THREAD

**Issue by GabrielGorta** [prettier/prettier#14322]
**Environments:**

- Prettier Version: 2.8.4
- Running Prettier via: NPM/cli `prettier --ignore-path .gitignore --write --plugin-search-dir=. .`
- Runtime: Node 18.x
- Operating System: Windows 11
- Prettier plugins (if any):

```
		"eslint-config-prettier": "^8.6.0",
		"eslint-plugin-prettier": "^4.2.1",
```

**Steps to reproduce:**

1. Instal TypeScript 5
2. use new feature
3. format.

(see: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wBU4S8BePAHkMtID4AKCAIwCsk9SBKak14BuEABoQEDDACW0IslABDbNggB3AAoqEClEoA26pQE8FE9tiVgA1nBgBlJQFs4AGRlQ4yAGaGicBZWtvYOGNaeAObIMNgAroGozuxwACapaW5KUJFxSpFwAGI4zkowsjnIIEpxMBDiIAAWMM4GAOqNMvBE4WBwDrpdMgBuXSZVYETmIJ4BuJpWkaW+-omcRGgOUQZwAIpxEPArBgES4dhzVTAmGBRg2DLSDRgPsG0yqTCNyAAcAAxnNQBNpWDBVF4UODYYbeCQARwO8AWUj01SIAFovGk0g1sHAETI8Qt8sskH4TokAs4ZDF4pTtnAAILlB7sWpwTRQjxeY6nEBEBn7Q7eMmrCQwJTsd6fb5IABM4qsMgMUQAwhBnKTUEQAKwNOIBUiSvTkvnDBIASSgGVgDnujxgjOtDmuO15cAAvh6gA )

**Expected behavior:**

Format will correctly format script.

**Actual behavior:**

```
SyntaxError: Type parameter declaration expected. (518:21)
[error] > 518 | export const Test: <const T>(obj: T) => T;
```

**Comment by fisker** [comment]
#14240
