### ISSUE TITLE
Leading | and whitespace when formatting long Flow unions

### ISSUE THREAD

**Issue by freiksenet** [prettier/prettier#1434]
```js
type Foo = Promise<
  { ok: true, bar: string, baz: SomeOtherLongType } | 
  { ok: false, bar: SomeOtherLongType }
>;
```

Formatted as:

```js
type Foo = Promise<

    | { ok: true, bar: string, baz: SomeOtherLongType }
    | { ok: false, bar: SomeOtherLongType }
>;
```

Prettier version 1.2.2

**Comment by azz** [comment]
The leading `|` [is valid](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwBiccYAvGAAoBOcAtgJYDOuAPKmB2AD5gDeYcANYAuMOioBXXABowAIwCGVUY3H0AdgHMwAX3ace-IaKgKYzXagB8AbiA) in flow.

The blank line looks like a bug.

**Comment by vjeux** [comment]
The leading `|` is indeed valid and intended. The empty line is not and needs to be fixed.

**Comment by dantman** [comment]
It's worth noting that the leading `|` wasn't necessarily always valid. I encountered this in a project that was using flow 0.40.0 and the `|` prettier was inserting was causing a syntax error.

**Comment by vjeux** [comment]
Something else must have been going on @dantman. Leading `|` was introduced in flow 0.22.0 ( https://github.com/facebook/flow/releases/tag/v0.22.0 ), February 19 of last year.

To make sure, I just checked and flow parser 0.21.0 doesn't support leading `|`. 0.23.1 is the first version that does (0.22.0 wasn't published for flow-parser).
