### ISSUE TITLE
"Failed to parse buffer" error for styles in Markdown file

### ISSUE THREAD

**Issue by JESii** [prettier/prettier#14359]
**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFnAhgEwHwA6UqMAljADZx4BS0A5AM4AEAsggK6oD0Zl1RVBVJQA1swBOcCgF4CIUpCjzmMAJ4AHOHIUBbLAHM43AB4BaRdBXopAMx22sAN0tQAdJZXdCxRuqo+brZU5kowWCJwEszARMzMOKSMGhRYakjMwXAmANxxmSFmAO4SWBoZUBAlZXlQAL5EQYXScLoIMDFE8CYwZljCBlAZYO1RtbbQvYykAF5wSACMUrq1De5Z5i1tsG6M+hQUnVATsGbTcxluAKzLq40bZlvtTdlncBpYpTAQ0bFQ8QAjLBgUQGCQQDhQHBmSAUH4ZMFwBC1eL6CQGEQZAAMzGutyIa3QACYADTMdAAZjJGjJHEOf1RnwxUDMALhILO4QkMEuV1aKOYaOZrPZokeUMuFL5KwJgm4fjUATlmFwPkEiSczDAqUYjAchTCESgUXkPlQGq1Or18geT1gpsEpF0BmYjAkYB0bm42w4AEklG4NFADCoiqQcDB0DoAGwAFmscFIBnQMBj8ZA3jlGrNAEIzGZmABlGClYNwZgAuDoZykeH5ABUzF9tibWogOHLkfLEwOVRELotWBY5tImrc4+Y3lUmGY7VIUlU2Q6tlIVGYSQK2TgOBzDabLd9bY7646Q+YI7H47wqAAwgAla-cbOzpxRNSR-vMIo-UQsM-ZLQwHgHAiDzMwzQtbUh2tEBbSobZl0KRh3k+LBvgkB1iCfUcINHS1oP1V47RgTD4gwBY8DYThmAgFsnE+WsOBYYQxEYMkcAgMA2NnGAwFQAFokzf5zwtBUqAcSYzlmeZmCxa5+QSJIUjSDIRBYuARU40Q8hAPAADUommaBZLcIkiWYfNmAAGSHDoAFUNBwNDtwyIksSJCkzCxBYzApLEeGzfIeHQCiguwpwzXCnwQBJEAIA0MhoEYZBQE+cEigABU+BBkpQfoijSZLYoE4FRDgGBCywNorMiZBHAoZDitKEFysLD4wH7ZASw4OBYtaSscA7HAbODDhDDgAAxH59BgMhg2QEAsA4b4YpAFNdAoAB1dByDgZJgTgQscvIUdyDUBauKKhQoGQ7kMtKAx9Dq-pGpAAArRgTELfsqAARQ4CB4GehrepAD4JFuhagUrChVo0CQRBgTbw0jZAAA4sVi+GIGQzbSg0Bb4b2qJX1WgBHAH4Hu+LcsWxgzGNbdt1WqQKfnOB7sMJ6kHq17kN0UguokHrYumYMqAAQVmhGAWWjmohq41gb5n64H+wG4GV0HwgBZGI3QZBSRAEsIhYgwbwgXRuZAParlWpi4AAFSwAFct50GnB630oXaQswARhKJahYtFU1nmXrgOo6iAA)

```sh
--parser babel
```

**Input:**

```jsx
<head>
<title>Jon's Menu</title>
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<style>
.flex-container {
  display: flex;
  flex-wrap: nowrap;
}
.flex-element {
text-align: center;
font-size:1rem;
}
.flex-element.small {
font-size: .5rem;
}
.flex-element.flex-separator {
  background-color: green;
  margin: 0 .5rem;
}
h2, h3, p, ul {
  margin-block-start: .5em;
  margin-block-end: .35em;
}
</style>
</head>

<div class="flex-container">
<div class="flex-element">
<img src="./menuIcon.png" width="64" height="64"/>
</div>
<!-- Strange behavior:
  * If I code the following div as <div ... /> the entire text file is flexed!
  * If I code it as <div ...><CR></div> everything works as expected
!-->
<div class="flex-element flex-separator">
</div>
<div class="flex-element">
  <h1> Menu of various links, docs, etc<br />
  <div style="font-size: 0.5em; display: inline-block;">Version 0.22 -- Last Updated: 2023-01-30</div>
  </h1>
  </div>
</div>

```

**Output:**

```jsx
SyntaxError: Unexpected token, expected "}" (6:10)
  4 | <style>
  5 | .flex-container {
> 6 |   display: flex;
    |          ^
  7 |   flex-wrap: nowrap;
  8 | }
  9 | .flex-element {
```

**Expected behavior:**

**Comment by fisker** [comment]
Isn't it html? Please use correct "parser".

**Comment by JESii** [comment]
Nope -- this is the first few lines of a markdown file -- properly set as markdown. there's private stuff in the md portion, but here's more of the file
```
<!--- NOTES & TODOs ---
  1. Reported prettier issue (styles) at https://github.com/prettier/prettier/issues/14359
  2. Consider using Lissy93's Dashy: https://github.com/Lissy93/dashy
  3. Another prettier error: https://github.com/prettier/prettier/issues/14360
  4. md-toc-generator: https://github.com/Lissy93/md-toc-generator
  --->
<title>Jon's Menu</title>
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<style>
.flex-container {
  display: flex;
  flex-wrap: nowrap;
}
.flex-element {
text-align: center;
font-size:1rem;
}
.flex-element.small {
font-size: .5rem;
}
.flex-element.flex-separator {
  background-color: green;
  margin: 0 .5rem;
}
h2, h3, p, ul {
  margin-block-start: .5em;
  margin-block-end: .35em;
}
</style>
</head>

<div class="flex-container">
<div class="flex-element">
<img src="./menuIcon.png" width="64" height="64"/>
</div>
<!-- Strange behavior:
  * If I code the following div as <div ... /> the entire text file is flexed!
  * If I code it as <div ...><CR></div> everything works as expected
!-->
<div class="flex-element flex-separator">
</div>
<div class="flex-element">
  <h1> Menu of various links, docs, etc<br />
  <div style="font-size: 0.5em; display: inline-block;">Version 0.22 -- Last Updated: 2023-01-30</div>
  </h1>
  </div>
</div>
## Reminders
* Use the 'fd' command rather than 'find'; fast & excludes files based on .gitignore
```
<img width="215" alt="CleanShot 2023-02-14 at 05 21 22@2x" src="https://user-images.githubusercontent.com/486/218750922-97e5672f-37f1-4d24-ae80-9343dbe4be76.png">

**Comment by fisker** [comment]
[Markdown parser doesn't throw either](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFnAhgEwHwA6UqMAljADZx4BS0A5AM4AEAsggK6oD0Zl1RVBVJQA1swBOcCgF4CIUpCjzmMAJ4AHOHIUBbLAHM43AB4BaRdBXopAMx22sAN0tQAdJZXdCxRuqo+brZU5kowWCJwEszARMzMOKSMGhRYakjMwXAmANxxmSFmAO4SWBoZUBAlZXlQAL5EQYXScLoIMDFE8CYwZljCBlAZYO1RtbbQvYykAF5wSACMUrq1De5Z5i1tsG6M+hQUnVATsGbTcxluAKzLq40bZlvtTdlncBpYpTAQ0bFQ8QAjLBgUQGCQQDhQHBmSAUH4ZMFwBC1eL6CQGEQZAAMzGutyIa3QACYADTMdAAZjJGjJHEOf1RnwxUDMALhILO4QkMEuV1aKOYaOZrPZokeUMuFL5KwJgm4fjUATlmFwPkEiSczDAqUYjAchTCESgUXkPlQGq1Or18geT1gpsEpF0BmYjAkYB0bm42w4AEklG4NFADCoiqQcDB0DoAGwAFmscFIBnQMBj8ZA3jlGrNAEIzGZmABlGClYNwZgAuDoZykeH5ABUzF9tibWogOHLkfLEwOVRELotWBY5tImrc4+Y3lUmGY7VIUlU2Q6tlIVGYSQK2TgOBzDabLd9bY7646Q+YI7H47wqAAwgAla-cbOzpxRNSR-vMIo-UQsM-ZLQwHgHAiDzMwzQtbUh2tEBbSobZl0KRh3k+LBvgkB1iCfUcINHS1oP1V47RgTD4gwBY8DYThmAgFsnE+WsOBYYQxEYMkcAgMA2NnGAwFQAFokzf5zwtBUqAcSYzlmeZmCxa5+QSJIUjSDIRBYuARU40Q8hAPAADUommaBZLcIkiWYfNmAAGSHDoAFUNBwNDtwyIksSJCkzCxBYzApLEeGzfIeHQCiguwpwzXCnwQBJEAIA0MhoEYZBQE+cEigABU+BBkpQfoijSZLYoE4FRDgGBCywNorMiZBHAoZDitKEFysLD4wH7ZASw4OBYtaSscA7HAbODDhDDgAAxH59BgMhg2QEAsA4b4YpAFNdAoAB1dByDgZJgTgQscvIUdyDUBauKKhQoGQ7kMtKAx9Dq-pGpAAArRgTELfsqAARQ4CB4GehrepAD4JFuha0VEDiiigVaNAkEQYE28NI2QAAOLFYsRiBkM20oNAWxG9qiV9VoARwB+B7vi3LFsYMxjW3bdVqkKn5zge7DCepB6te5DdFILqJB62LpmDKgAEFZqRgFlq5qIauNYGBZ+uB-sBuBVdB8IAVRiN0GQUkQBLCIWIMG8IF0XmQD2q5VqYuAABUsABXL+dBpwet9KF2kLMAkYSqWoWLRVtb5l64DqOogA).
