### ISSUE TITLE
"SyntaxError: Unexpected token" when adding comments to markdown code

### ISSUE THREAD

**Issue by JESii** [prettier/prettier#14360]
**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFnAhgEwHwA6UqAhALQUAEAcgPIAqAogMqUBkl9tAIrQM6UKZIpUoBGAHSUASnAAOEAE7wclOYrgwYASziLK2vnwCucSgAo+MAJ4AbOHwCUlLDEojKAJikBhaH20cPUpjAKgAc0oAGUM+awBOAGYAcgFuLD50ayR3KFEhQmIdGHs8ACloVMoAWQRjVAB6YtKiVFttKABrSg1bAF4CEG1IKEHKGzk4AaGAWyxwuAaADzJh6DH0DQAzaa2sADc1qAk1sYbC1Cs7OEKJLfsVkZgsDuDgDxxDOVssbMp7uBLADcHgBKwA7oosHIclAIJDoSCoABfIh3B5kOD2GYINzvWCAmBkLDtcJQHJgXF6JFbaBEgIALzgSDEGhmSNRxzBmOxuIkfDmtlslHxtNgZEZzMoEgArGyOWjuVi4DjYOjARL5FgoTAlCKPAAjLBgTrhRQQYxQHBkSC2JQ5M1wBBI0RzRThDo5AAM0rlKoVUHQngANJR0IlQ3JQ8ZhfjXdqPVAyAa7SaJc9lDlZf6PG7E8nU51MVas4kZTmUa0GlcWsQGphcHgQMGQBA5Dp-MhQNrzeCAArahB8ZAgEng37DlsGqEmzTMLA4mJQODIPa2PhwKczzpzuTGjrhZAwRSmFsqg1wHBBHBRLARYzzOAAMSUcy0B5HWGMuubIHQMBmWwAHV0G0eA+D3SlmCHMDtEOGwRzAIxfw6DdlD7KFwjmVcSQ3FsACs+CWZgD3sABFYwIHgHD103EA90UNCRyNC9bF-dQOhgIDAhgdBkAADi9Ft1AgDcgKhOQR3UBw9H2FcWwAR0o+AMLbYcUAyMhl0vS9fw0JTtA0DD5mwpA1zwkANxmbQjxPOiwnCewAEEtEUbQDW-OA+z0JcVzM3D7NIuAKKovzzLo54DW4nBeOQEMQGPF52giPwZlMkAHBlX9QjgegsANdTwpbfZTAASStXFmDANz2ycq1mBsewaI3ZFkSAA)

```sh
--parser babel
```

**Input:**

```jsx
<head>
<!--- NOTES & TODOs ---
  1. Reported prettier issue (styles) at 
  2. Consider using Lissy93's Dashy: 
  --->
<title>Jon's Menu</title>
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<style>
.flex-container {
  display: flex;
  flex-wrap: nowrap;
}
.flex-element {
text-align: center;
font-size:1rem;
}
.flex-element.small {
font-size: .5rem;
}
.flex-element.flex-separator {
  background-color: green;
  margin: 0 .5rem;
}
h2, h3, p, ul {
  margin-block-start: .5em;
  margin-block-end: .35em;
}
</style>
</head>
```

**Output:**
ADDED COMMENTS
1. The error is actually flagging the "!"
2. Why does prettier believe this is jsx code?

```jsx
SyntaxError: Unexpected token (2:2)
  1 | <head>
> 2 | <!--- NOTES & TODOs ---
    |  ^
  3 |   1. Reported prettier issue (styles) at 
  4 |   2. Consider using Lissy93's Dashy: 
  5 |   --->
```

**Expected behavior:**
To clarify, even though the first lines of the file are html, the file is markdown
<img width="215" alt="CleanShot 2023-02-14 at 05 21 22@2x" src="https://user-images.githubusercontent.com/486/218751436-47adbf58-8997-4c2b-9c59-469a5478ae46.png">

**Comment by sosukesuzuki** [comment]
Using `--parser=markdown` solves your problem?

**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFnAhgEwHwA6UqAhALQUAEAcgPIAqAogMqUBkl9tAIrQM6UKZIpUoBGAHSUASnAAOEAE7wclOYrgwYASziLK2vnwCucSgAo+MAJ4AbOHwCUlLDEojKAJikBhaH20cPUpjAKgAc0oAGUM+awBOAGYAcgFuLD50ayR3KFEhQmIdGHs8ACloVMoAWQRjVAB6YtKiVFttKABrSg1bAF4CEG1IKEHKGzk4AaGAWyxwuAaADzJh6DH0DQAzaa2sADc1qAk1sYbC1Cs7OEKJLfsVkZgsDuDgDxxDOVssbMp7uBLADcHgBKwA7oosHIclAIJDoSCoABfIh3B5kOD2GYINzvWCAmBkLDtcJQHJgXF6JFbaBEgIALzgSDEGhmSNRxzBmOxuIkfDmtlslHxtNgZEZzMoEgArGyOWjuVi4DjYOjARL5FgoTAlCKPAAjLBgTrhRQQYxQHBkSC2JQ5M1wBBI0RzRThDo5AAM0rlKoVUHQngANJR0IlQ3JQ8ZhfjXdqPVAyAa7SaJc9lDlZf6PG7E8nU51MVas4kZTmUa0GlcWsQGphcHgQMGQBA5Dp-MhQNrzeCAArahB8ZAgEng37DlsGqEmzTMLA4mJQODIPa2PhwKczzpzuTGjrhZAwRSmFsqg1wHBBHBRLARYzzOAAMSUcy0B5HWGMuubIHQMBmWwAHV0G0eA+D3SlmCHMDtEOGwRzAIxfw6DdlD7KFwjmVcSQ3FsACs+CWZgD3sABFYwIHgHD103EA90UNCRzdTocHhKBf3UDoYCAwIYHQZAAA4vRbdQIA3ICoTkEd1AcPR9hXFsAEdKPgDC22HFAMjIZdL0vX8NBU7QNAw+ZsKQNc8JADcZm0I8TzosJwnsABBLRFG0A1vzgPs9CXFcLNwxzSLgCiqICyy6OeA1eJwfjkBDEBjxedoIj8GZzJABwZV-UI4HoLADU0yKW32UwAEkrVxZgwA89sXKtZgbHsGiN2RZEgA)

```sh
--parser markdown
```

**Input:**

```markdown
<head>
<!--- NOTES & TODOs ---
  1. Reported prettier issue (styles) at 
  2. Consider using Lissy93's Dashy: 
  --->
<title>Jon's Menu</title>
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<style>
.flex-container {
  display: flex;
  flex-wrap: nowrap;
}
.flex-element {
text-align: center;
font-size:1rem;
}
.flex-element.small {
font-size: .5rem;
}
.flex-element.flex-separator {
  background-color: green;
  margin: 0 .5rem;
}
h2, h3, p, ul {
  margin-block-start: .5em;
  margin-block-end: .35em;
}
</style>
</head>
```

**Output:**

```markdown
<head>
<!--- NOTES & TODOs ---
  1. Reported prettier issue (styles) at 
  2. Consider using Lissy93's Dashy: 
  --->
<title>Jon's Menu</title>
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<style>
.flex-container {
  display: flex;
  flex-wrap: nowrap;
}
.flex-element {
text-align: center;
font-size:1rem;
}
.flex-element.small {
font-size: .5rem;
}
.flex-element.flex-separator {
  background-color: green;
  margin: 0 .5rem;
}
h2, h3, p, ul {
  margin-block-start: .5em;
  margin-block-end: .35em;
}
</style>
</head>

```
