### ISSUE TITLE
JSX variable or statement injection: close brace placement.

### ISSUE THREAD

**Issue by Strate** [prettier/prettier#1438]
Consider the code snippet:
```jsx
{condition &&
  <Element
    withMultiLine
    properties={[]}
  />}
```
and please note close `}` character position. I suggest to place it on new line:

```jsx
{condition &&
  <Element
    withMultiLine
    properties={[]}
  />
}
```

**Comment by lydell** [comment]
I think this might be a duplicate of #1297.

**Comment by vjeux** [comment]
Yup, indeed a duplicate. Also there's likely a few other related issues.

**Comment by Strate** [comment]
Sorry for dup.

**Comment by vjeux** [comment]
@Strate please don't be! Feel free to report all the weird things you are seeing. It really helps to figure out how to prioritize them :)
