### ISSUE TITLE
Add option to specify desired MD list numbering

### ISSUE THREAD

**Issue by karlismelderis-mckinsey** [prettier/prettier#14394]
Can you please add option to specify desired MD numbered list format?

Currently prettier accepts both - `1. 2. 3. 4.` and `1. 1. 1. 1.` - and we're looking for option to make Prettier to enforce one way only (`1. 1. 1. 1.`)

I'm aware of `markdownlint` and `eslint-plugin-markdownlint`

While these packages can catch the case these are still extra dependencies to be added and `eslint-plugin-markdownlint` doesn't have `--fix` support for the case while prettier is producing properly formatted result.

And we already have prettier to format our Markdown file.

**Comment by sosukesuzuki** [comment]
Sorry, we will not add an option for this. Please use a linter.
