### ISSUE TITLE
Babel 7.21.0 features

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#14390]
- [ ] [Inline RegExp modifiers](https://babeljs.io/blog/2023/02/20/7.21.0#inline-regexp-modifiers) (Only tests?)
- [ ] [Decorators updates](https://babeljs.io/blog/2023/02/20/7.21.0#decorators-updates)
- [ ] TS 5.0 [`const` modifiers for type parameters](https://babeljs.io/blog/2023/02/20/7.21.0#typescript-50)
- [ ] TS 5.0 [`export type *`](https://babeljs.io/blog/2023/02/20/7.21.0#typescript-50)

**Comment by fisker** [comment]
Fixed by #14391
