### ISSUE TITLE
Introduce option to keep lines with trailing comma as is

### ISSUE THREAD

**Issue by mtvx** [prettier/prettier#14395]
**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mA2gDpSaakjYCWAThtQDRUVUhpyRQAmL5ALrlyPDDjyES5SgHpZmAMIQAtioRYEuemDi9MAG1pQ42OHrQyOdRjBZtK1Lj34hmQ8m5AQADjFroyKAAhvT0EADuAAqhCGjIIMEGEcEAnvHMIABG9MFgANZwMADKweoAMsZwyNhJXJk5eYUlPnnGAObIMPQArnCZcCpZerx65cFQ7T3B7XAAYhD0KsEw-pMJwT0wEF4AFjAqBgDqu7TwaK26xXFntABuZ6kJYGgZIMZc9DBRue3LNXV+iAAFZoAAexQ6BjgAEUehB4ACDPUQK1GHB6AkssFhgYvD56MYYEdaLwYLtkAAOAAMmQJEC4R1yPgSBLgnzu1UyAEd4fAfr54ihgmgALQmPR6Lz0OC8hhwH4zf5IWrIoFcFS0Lq9dVQuAAQVWhKyWwVGMqJiRKLQerhCOqKsBmRgOJJZIpSAATM7crQjJNlGpggl2QBWLw9LgAFRxQtVKLufQAknwNMUwIS-Pq+MUYKloVa4ABfItAA)

```sh
--parser babel
```

**Input:**

```jsx
const foo = [
  "first", 
  "second",
]

const foo = [
  // Workaround: having a comment enforces linefeeds
  "first", 
  "second",
]

```

**Output:**

```jsx
const foo = ["first", "second"];

const foo = [
  // Workaround: having a comment enforces linefeeds
  "first",
  "second",
];

```

**Expected behavior:**

```jsx
const foo = [
  "first",
  "second",
];

const foo = [
  // Workaround: having a comment enforces linefeeds
  "first",
  "second",
];

```

At least Python's Black has the ["magic trailing comma" option](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma) to keep lines with a trailing comma as is, instead of merging those together to one line if there's space.

Sometimes, it's more readable to keep entries in separate lines, even when the line width would allow them to be all in one line. Prettier's philosophy seems to be that nothing is left to the user, the same as what Black started with... however, this one's just so practical.

(Also, formatting all the options to the same line loses nice Git blame view on each option, etc.)

This could be behind a toggle and not on by default.

**Comment by sosukesuzuki** [comment]
We will not add an option for this. Please see https://prettier.io/docs/en/option-philosophy.html.
