### ISSUE TITLE
wrong indentation in template literal with more than 1 expression

### ISSUE THREAD

**Issue by gregsadetsky** [prettier/prettier#14403]
**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACSBbADgQwCc4MYALASwGcMBaDAd0rDI2rakkOLBgyoqcSFPmXw0ATBjgAPXMSoDoVADpRiMAK6EoGAAZqMWZXwAkwGQF8MAXgzmAZgApghoxgDWcAJ4BGJBgA5ABu+AA2mnCBADRuRl7eEgEh4ZExbpYAlJYA3Gp6eVBq6Bj4UAAmpJQ09EwULBhiNL7ScgpKumWV7Fw8MGoa2roGusZQVHwytvbAzq6j8T7+QaERUbELnj5JK6nrGdmFBWog0SAQuDAUysigRIQQDAAKRAhUyCDhDPje72cARoR8GAvDAAMr4bBwAAygjgyAc4SocABQJBcHBBDAggA5sgYIRImc4Nh-nByuVydCyjjNPgcXAAGIQQjYfAwK5QPEofCaGAQU4gMgwbBhADqlHgVCxcDBbxEFGCIm8HzAikFgmRhBgTyBOLZCKRKJAACsqDIwbiwnAAIqaCDwQ1hZFnAiELUff74MlhQXyQQwMUUcrkZAADgADK6HsixUDcB95HAtcF4WcAI72+C6i7vHlUWhQODk8mC4iZijEXX0g1IRHO43I7AUfGExtWuAAQQ5hAo-z5cCecEIsKLTpdIAEXOtdod8LrRrOMG9QZDZGQEiXQIoYVxAGEINhayBkwBWQWaZEAFW9efrE+CkQAkhUEOCwL3Lp2KmCYN5reOcCWJYQA)

```sh
--parser babel
```

**Input:**

```jsx
// compare this - which is incorrect since it has 2 expressions
return `
  const ${x} = ${f({
    key1: 'value',
    key2: 'value',
  })};
`;

// and this - which has 1 expression and is correct
return `
  const x = ${f({
    key1: 'value',
    key2: 'value',
  })};
`;

```

**Output:**

```jsx
// compare this - which is incorrect since it has 2 expressions
return `
  const ${x} = ${f({
  key1: "value",
  key2: "value",
})};
`;

// and this - which has 1 expression and is correct
return `
  const x = ${f({
    key1: "value",
    key2: "value",
  })};
`;

```

**Expected behavior:**

the expected output (for the first example) is

```javascript
return `
  const ${x} = ${f({
    key1: "value",
    key2: "value",
  })};
`;
```

**Comment by fisker** [comment]
This should already fixed in `next` branch which will be include in v3. https://github.com/prettier/prettier/pull/9583

**Comment by fisker** [comment]
Confirmed [playground](https://deploy-preview-9583--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEB6VACSBbADgQwCc4MYALASwGcMBaDAd0rDI2rakkOLBgyoqcSFPmXw0ATBjgAPXMSoDoVADpRiMAK6EoGAAZqMWZXwAkwGQF8MAXgzmAZgApghoxgDWcAJ4BGJBgA5ABu+AA2mnCBADRuRl7eEgEh4ZExbpYAlJYA3Gp6eVBq6Bj4UAAmpJQ09EwULBhiNL7ScgpKumWV7Fw8MGoa2roGusZQVHwytvbAzq6j8T7+QaERUbELnj5JK6nrGdmFBSDRIBC4MBTKyKBEhBAMAApECFTIIOEM+N5vpwBGhHwYC8MAAyvhsHAADKCODIBzhKhwf6A4FwMEEMCCADmyBghEipzg2D+cHK5TJULK2M0+GxcAAYhBCNh8DBLlBcSh8JoYBATiAyDBsGEAOqUeBUTFwUGvEQUYIibzvMCKAWCJGEGCPQHY1nwxHIkAAKyoMlBOLCcAAipoIPADWEkacCIRNe8-vhSWEBfJBDBRRRyuRkAAOAAMLvuSNFgNw73kcE1wThpwAjnb4Drzm9uVRaFA4GSyQLiBmKMQdXT9UgEU6jUjsBQ8QSG5a4ABBdmECh-XlwR5wQgwwuO50gAScq22+1w2uG04wL2B4NkZASReAihhHEAYQg2BrHzCPtOmiRABUvbm6+PgpEAJIVBBgsA9i4diqgmDeK1juCWJYQA)
