### ISSUE TITLE
prettier-ignore before comment before await with parens produces valid but incorrect code

### ISSUE THREAD

**Issue by epmatsw** [prettier/prettier#14404]
**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAOlABF9MD0+WADgE5wwwCWcpAtFQOZQTmY56FYBGmeAhgHd+VGFhgALKlEaoAlJjkA6bgBt+EkABoQEYtWgBnZKH6lSEQQAUzCYyn6rhAT2M7upfmADWFAMr8ALZwADLScMgAZo6GcO6ePv7EXtKMyDCkAK5xIHCB3HAAJoVFIfwymfyMcABirIH8lKnIIPyZMBDaIBIwgaoA6lLwhslgcH52olQAbqLOLWCGbiDSsaQwVp6MDVExOQBWhgAefqmqcACKmRDwu6qxOsmkay3c-AWqXWTSMP1UhZJkAAOAAMjwssX6nmILTIcDW0wiOgAjtd4Js9PZWoY6FA4EUil1yKiqORNlUdkhovccrFAlR0llaWc4ABBSikKjcdpwKy0MJ4u4PECGFlXG4RKl7HQwd5-AGaJAAJhlnioqlSAGEIIFKblDABWLqZWIAFXe9mpwum2QAklASrA-GBOfpWQ6-DBnOchXAAL5+oA)

```sh
--parser babel
```

**Input:**

```jsx
(
  	// prettier-ignore
  	// b
	await thing()
).blah
```

**Output:**

```jsx
// prettier-ignore
// b
await thing().blah;

```

**Expected behavior:**

```jsx
// prettier-ignore
// b
(await thing()).blah;
```

Previously, the parens caused it to await-then-access. Now, the removal of the parentheses causes it to access-then-await, which is a different (and probably incorrect) bit of code.

**Comment by fisker** [comment]
Fixed by #14406
