### ISSUE TITLE
Error when formatting with handlebarsjs syntax in html element

### ISSUE THREAD

**Issue by devcaco** [prettier/prettier#14425]
So prettier is giving me an error and won't format the document when I include handlebars syntax inside an html element. For example

`<li class="nav-item {{#if this.active}} active {{/if}}" style="flex-basis:0;">`

The following error shows up

```
(error occurred in 'an unknown module' @ line 41 : column 95) (41:95)
  39 |             {{#each navmenu}}
  40 |               <ul class="nav flex-column justify-content-center">
> 41 |                 <li class="nav-item d-flex flex-row justify-content-between align-items-center {{#if this.active}} active {{/if}}" style="flex-basis:0;">
     |                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I have try all ignore syntax to ignore that particular line but I keep getting the error and it won't format the rest of the document.

How can I make it to ignore those cases and format everything else?

**Comment by kachkaev** [comment]
@devcaco please follow the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1) 🙏
