### ISSUE TITLE
.prettierignore negation not working

### ISSUE THREAD

**Issue by nurse-the-code** [prettier/prettier#14427]
On `.eslintignore` the follow text works:
```
# Ignore all files and directories
/*

# Allow specific file types
!**/*.(html|css|js|jsx|ts|tsx|json|md)
```

On `.prettierignore` it results in all files being ignored by Prettier.

**Comment by svoop** [comment]
I can confirm this behaviour, just ate an hour off my day.

**Comment by brachkow** [comment]
Same problem. I have:
```
/*
!/some/dir/
```

and everything in /some/dir/ is ignored too when i run `prettier --write .`

**Comment by kachkaev** [comment]
This works for me in a side project:
https://github.com/kachkaev/njt/blob/c08f60f0024bf9a3a6e087dd732538eb94b6c1da/.prettierignore

```
## ignore all files (but still allow sub-folder scanning)
*
!*/

## allow certain file types
!*.cjs
!*.js
!*.json
!*.md
!*.mjs
!*.ts
!*.tsx
!*.yml
```

Please use StackOverflow for questions 🙏

**Comment by svoop** [comment]
@kachkaev Are you sure this is no bug? [The docs](https://prettier.io/docs/en/ignore.html) claim `.prettierignore` to use `.gitignore` syntax. If so, then the reporter's example should work. In other words, there's something wrong – either in the docs or in the code. (Nonetheless, thanks for the workaround!)

**Comment by kachkaev** [comment]
👋 @svoop! AFAIU, prettier uses [`ignore`](https://www.npmjs.com/package/ignore) package which claims to be “implemented in pure JavaScript according to the [.gitignore spec 2.22.1](http://git-scm.com/docs/gitignore).“

Wrapper code around `ignore` is quite minimal, you can find it in [`src/common/create-ignorer.js`](https://github.com/prettier/prettier/blob/bc098779c4e457b1454895973196cffb3b1cdedf/src/common/create-ignorer.js).

If you want to dig into this problem a bit more, feel free to share the results of your investigation below. Happy to reopen this issue if it’s a bug.
