### ISSUE TITLE
Formatting JSON5 in the browser throws when comments are present

### ISSUE THREAD

**Issue by giacomorebonato** [prettier/prettier#14431]
**Environments:**

- Prettier Version: 2.8.4
- Running Prettier via: Browser API
- Runtime: Node v19.0.1
- Operating System: macOS
- Prettier plugins (if any): custom plugin for parsing JSON5 (if there is a more appropriate option, I couldn't find it)

```js
const json5Plugin: Prettier.Plugin = {
  parsers: {
    "json5-parser": {
      parse(text: string) {
        return parserBabel.parsers.json5.parse(text);
      },
      astFormat: "estree",
    },
  },
};
```

**Steps to reproduce:**

* clone [this repository](https://github.com/giacomorebonato/mino-prettier)
* install dependencies `pnpm install` or `npm install`
* start it `pnpm dev` or `npm run dev`

**Expected behavior:**

It'll start an app with a button "Prettify" that formats JSON5 text when clicked.
When adding comments, they are formatted too.
Try for example to format `package.json5` with VSCode Prettier extension and comments are persisted.

**Actual behavior:**

When comments are added it throws an exception.

**Comment by fisker** [comment]
There are other props required like `locStart`/`locEnd`.

Why don't you use it directly? Are you planning to change `parse`?

https://github.com/giacomorebonato/mino-prettier/pull/1

**Comment by giacomorebonato** [comment]
Thanks, that fixes it.

> Why don't you use it directly? 

I really wanted to just use it in the way:

```js
  Prettier.format(text, {
    parser: "json5",
    trailingComma: "all",
    tabWidth: 4,
  })
```
[as described here](https://prettier.io/docs/en/browser.html), but I don't understand how to import JSON5 parser.

**Comment by fisker** [comment]
```js
import * as pluginBabel from "prettier/parser-babel";

  prettier.format(text, {
    plugins: [pluginBabel ],
    parser: "json5",
    trailingComma: "all",
    tabWidth: 4,
  })
```

That entry is not a parser, but a plugin. That example is confusing.

**Comment by giacomorebonato** [comment]
Thank you!
