### ISSUE TITLE
.prettierignore doesn't work as expected when unignoring directories 

### ISSUE THREAD

**Issue by brachkow** [prettier/prettier#14434]
I need to make prettier format code only in one directory, omitting the rest. I set up my .prettierignore like this:

```
/*
!/some/dir/
```
but everything in `/some/dir/` is ignored too when i run `prettier --write .`

**Environments:**

- Prettier Version: 2.8.4
- Running Prettier via: CLI
- Runtime: v16.19.1
- Operating System: macOS

**Comment by kachkaev** [comment]
👋 @brachkow! Please use [StackOverflow](https://stackoverflow.com/questions/ask?tags=prettier) for questions. You might also want to take a look at https://github.com/prettier/prettier/issues/14427 with a similar discussion.

**Comment by brachkow** [comment]
For those who facing this issue — adding dots to paths somehow works

```
./*
!./some/dir/
```

**Comment by brachkow** [comment]
Ok, after hours of research I found out that .gitignore syntax for negating is much more unobvious that it looks https://stackoverflow.com/a/5534865/12277907
