### ISSUE TITLE
Semicolon added to class arrow functions

### ISSUE THREAD

**Issue by ndresx** [prettier/prettier#1444]
With `semi `set to `true`, the following input
```js
class Semi {
  constructor() {
    this.semi = true  
  }
  
  onClick = (e) => {
    doIt();
  }
}
```
returns this as output:
```js
class Semi {
  constructor() {
    this.semi = true;
  }

  onClick = e => {
    doIt();
  };
}
```

**Issue:**
I personally would not expect prettier to actually place a semicolon after in a class context defined arrow function. The same goes for removing the parentheses around the argument (e) of this particular function, although I know that there are more things involved around this specific rule.

**Link:**
https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Semi%20%7B%5Cn%20%20constructor()%20%7B%5Cn%20%20%5Ctthis.semi%20%3D%20true%20%20%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20onClick%20%3D%20(e)%20%3D%3E%20%7B%5Cn%20%20%20%20doIt()%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by bakkot** [comment]
It's not adding it to the arrow; it's adding it to the *property*.

Class property declarations are followed by semicolons, just like statements. (You can get away with omitting them through ASI, sometimes, but that's what the no-semi style is for.) The semicolon is there for the same reason it's there in

```js
let x = e => {
  doIt();
};
```

**Comment by ndresx** [comment]
@bakkot Thanks for the correction on this.

It could theoretically also get applied to the constructor, functions as well as the class definition, but I wouldn't like that either.

**Comment by bakkot** [comment]
@ndresx Those don't have semicolons after them in the grammar, though. You can put one there, but it's like adding a semicolon after a function declaration in normal code.

It's the same as how you'd put a semicolon in

```js
let a = function(){
  // empty
};
```

but not

```js
function a() {
  // empty
}
```

**Comment by ndresx** [comment]
@bakkot Exactly, it would feel unnatural, and that's my point! I have never seen an example which is using ; after these arrow function declarations. E.g.: React docs https://facebook.github.io/react/docs/handling-events.html.

**Comment by bakkot** [comment]
@ndresx But class properties - unlike method declarations in classes - *do* have semicolons after them. *Leaving it out* feels unnatural to me, and is moreover inconsistent with the rest of prettier.

Would you leave the semicolon out of 
```js
class A {
  p = 0;
}
```
?

What about

```js
let a = function(){
  // empty
};
```
or
```js
let a = () => {
 // empty
};
```
or
```js
class A {
  p = () => 0;
}
```
?

I think the unnaturalness is just that you're not used to it. But it's definitely more consistent.

**Comment by ndresx** [comment]
1: Semi: Yes
2: Semi: Yes
3: Semi: Yes
4: Semi: No

Other question, where would you put this class property. Usually - and if you really want to treat them like that - those would be grouped at top of the class body, or not?
```
class A {
  p = () => 0;

  constructor() {}
}
```
or
```
class A {
  constructor() {}

  p = () => 0;
}
```

**Comment by bakkot** [comment]
I think the visual inconsistency in

```js
class A {
  a = 0 + 1;
  b = () => 2
}
```
would bother me a great deal.

> where would you put this class property. Usually - and if you really want to treat them like that - those would be grouped at top of the class body, or not?

People vary, here. And since prettier can't rearrange them (because of evaluation order issues), it has to support all possibilities.

Also, sometimes the semicolon is *required*, e.g. in

```js
class A {
  p = () => 0;
  [Symbol.iterator]() {}
}
```

The no-semi style handles this by putting a semicolon at the end of that first line iff it's required, and just not worrying about the inconsistency. I think people who prefer to use semicolons will generally prefer the semicolon be there unconditionally. Certainly I would.

**Comment by ndresx** [comment]
I see that there are advantages/disadvantages as well as cases where they are apparently required. In the end this was just a proposal, also based on all the examples I have seen so far as mentioned before.

**Comment by vjeux** [comment]
Since this is intended, I'm going to go ahead and close this issue.
