### ISSUE TITLE
Allow keeping parenthesis for closure compiler type casting

### ISSUE THREAD

**Issue by stringham** [prettier/prettier#1445]
When writing javascript for use with the Closure compiler, parenthesis directly following a type annotation comment have meaning.

[Type cast](https://github.com/google/closure-compiler/wiki/Annotating-Types#type-casts) precede a parenthesized expression.

```javascript
var x = /** @type {string} */ (fruit);
```

prettier outputs:

```javascript
var x /** @type {string} */ = fruit;
```

**Comment by vjeux** [comment]
We're not doing a good job at respecting all those comments. We also have a bunch of issues with flow comments.

**Comment by bakkot** [comment]
@vjeux It's not just that the comment is moved; Closure is treating the *parentheses* as semantic, and will give a warning if they're dropped. (Ugh.)

**Comment by DrRataplan** [comment]
Thanks a bunch for addressing this, I found one oversight though.
When using an inline type cast, like this:

```
const charCode = /** @type {string} */ (fruit).charCodeAt(0);
```

prettier outputs 

```
const charCode = /** @type {string} */ (fruit.charCodeAt(0));
```

The workaround is easy though: just move the cast to a different statement, like this:

```
const strFruit = /** @type {string} */ (fruit);
const charCode = strFruit.charCodeAt(0);
```

or add additional parentheses:

```
const charCode = (/** @type {string} */ (fruit)).charCodeAt(0);
```

**Comment by roelkok** [comment]
This doesn't seem to work for me. It should work without setting a specific option, right?

a.) `/** @type {MeshBasicMaterial} */(this.plane.material).map.needsUpdate = true;`

Gets rewritten to

b.) `/** @type {MeshBasicMaterial} */ this.plane.material.map.needsUpdate = true;`

And if I do this

c.) `(/** @type {MeshBasicMaterial} */ (this.plane.material)).map.needsUpdate = true;`

It gets rewritten to **a.** on the first save and eventually to **b.** on the second save.

I'm using the 'Prettier - Code formatter' extension for VS Code.

**Comment by j-f1** [comment]
@roelkok That sounds like a bug. Can you open a new issue and fill out the template please?

**Comment by roelkok** [comment]
Opened an new issue here https://github.com/prettier/prettier/issues/4124
