### ISSUE TITLE
Strange format result.

### ISSUE THREAD

**Issue by zhangenming** [prettier/prettier#14454]
**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKACL2BmAKPASgwF4A+DYAXwBp1tsBnMAJwgBt24WA6ARwGChwkaLHiJgwiBogIABxgBLaI2SgAhizYB3AApaEalBvY6NATzWyARiw1gA1nBgBlDQFs4AGSVQ4yDimjHC29k4urvIOfgDmyDAsAK6hIHAeNnAAJlnZ3hpQsUkasXAAYhAsHhowyoXIIBpJMBAyIAAWMB7sAOrtSvCM0WBwrkYDSgBuAxYNYIzWIH4hLDB69rHVgcGpAFaMAB6ucVwAikkQ8NvsIbLRLCsNNhqZ7G3yLH4wPUpZMO3IAAcAAY7mwQj17PIGh84CtJgFZHwLvB1gpjI1GABafzZbJtFhwZFKQnrEpbJBBG6pEIeJQJZI0k5wACCtU+NmacD03F8-mutxAjGZ50uAUpO1kMBePz+AKQACYpfYlOw4gBhCAeClpRgAVjaSRCABUXsYqYLJikAJJQXKwVysJSKFl21wwCxcAVwKhUIA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet


      f(() => {}, scroller.qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq)
```

**Output:**

```jsx
// code snippet

      f(() => {},
      scroller.qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq)
```

**Expected behavior:**
```js

f(
  () => {}, 
  scroller.qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
)
```

**Comment by fisker** [comment]
This can't reproduce in next branch, not sure when it's fixed.

**Comment by Thenitesh143** [comment]
I would like to work on it

**Comment by fisker** [comment]
It's already fixed, only need add tests.

**Comment by fisker** [comment]
Found PR, #13341 fixed it.
