### ISSUE TITLE
Flow indexer properties are moved to the top of the type

### ISSUE THREAD

**Issue by ianobermiller** [prettier/prettier#1448]
Not sure if this is intentional or not, but prettier usually doesn't reorder things.

Before (and expected to stay this way):

```js
type Foo = {
  alpha: 'hello',
  [key: string]: void,
}
```

After:
```js
type Foo = {
  [key: string]: void,
  alpha: 'hello'
};
```

**Comment by vjeux** [comment]
Wow this is crazy, it does it for both flow and babylon

**Comment by vjeux** [comment]
Okay, the AST is really not helping there :(

![image](https://cloud.githubusercontent.com/assets/197597/25507961/f0e65d62-2b63-11e7-9fda-23e13940a965.png)
