### ISSUE TITLE
Performance issue while dealing with huge files

### ISSUE THREAD

**Issue by s-ashwin** [prettier/prettier#14481]
**Environments:**

- Prettier Version: 2.8.4
- Running Prettier via: Browser API
- Runtime:  Chrome v83
- Operating System:  macOS
- Prettier plugins (if any): prettier/parser-babel

**Steps to reproduce:**

Pass [a large file](https://github.com/json-iterator/test-data/blob/master/large-file.json) to `prettier.format(text, extension)`

**Expected behavior:**

This shouldn't block the event loop

**Actual behavior:**

This takes around 15 seconds to complete and blocks all other actions

**Comment by sosukesuzuki** [comment]
If you are calling from a browser, I recommend using in Web Workers. https://prettier.io/playground/ uses Prettier API in Web Workers.

**Comment by sosukesuzuki** [comment]
I close this issue, if you have still problem please re-open this.
