### ISSUE TITLE
Inconsistency with Prettier on dev vs Prod on the same Browser

### ISSUE THREAD

**Issue by roshaans** [prettier/prettier#14507]
**Environments:**

- Prettier Version: 2.8.4
- Running Prettier via:  Javascript package:  `"prettier": "^2.7.1"`,-->
- Runtime Chrome browser
- Operating System: macOS
- Prettier plugins: prettier/parserBabel 

**Steps to reproduce:**

**Expected behavior:**
Formatting works as expected on javascript code in my local environment while developing the application. And I expect it to work in the production environment without any hiccups and for the most part it does, expect it does not like the "in" keyword. 

**Actual behavior:**
**production env**
![image](https://user-images.githubusercontent.com/25015977/225049295-4531cd30-5743-48b0-ae75-52d8cdfe176a.png)

You may try it yourself. 

`let isFunctionCall = (object) => {
  return "FunctionCall" in object;
};`

Copy paste the following code in the code editor [here](https://query-api-react.vercel.app/create-new-indexer?accountId=roshaan.near) and then click the **Format** button. It should throw an error. Now, clone and start [my repo](https://github.com/roshaans/query-api-react) on your local setup and head to `http://localhost:3000/create-new-indexer?accountId=Roshaan.near` and input the same code and it should work without any problems. I have made sure the production env is running the latest code. 

What can be the issue here?

**Comment by kachkaev** [comment]
Hi @roshaans! This seems to be an issue with your app setup rather than with Prettier core. Please use StackOverflow for this kind of stuff. When you want to report a problem with the latest version of Prettier, please use an [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1).
