### ISSUE TITLE
ignore pnpm-lock.yaml by default

### ISSUE THREAD

**Issue by stefanprobst** [prettier/prettier#14517]
**Environments:**

- Prettier Version: 2.8.4
- Running Prettier via: CLI
- Runtime: Node.js v18.15
- Operating System: Linux
- Prettier plugins (if any): 

**Steps to reproduce:**

- pnpm init
- pnpm add prettier
- pnpm dlx prettier . --check

**Expected behavior:**

ignore `pnpm-lock.yaml` when running `prettier`

**Actual behavior:**

prettier by default tries to format `pnpm-lock.yaml`

**Comment by kachkaev** [comment]
[Current implementation of Prettier’s ignore logic](https://github.com/prettier/prettier/blob/e7b383b570db0f5b792887aa87e7b090f43125cb/src/common/create-ignorer.js) does not contain any any special ignore rules except for `node_modules`. Ignoring common file patterns like `pnpm-lock.yaml`, `.yarn/*`, etc., may feel like a simple and good solution, but I’m not sure about that. Once we’ve ignored these ‘obvious’ patterns, what should we do, say, with a feature request to ignore `.next/*` too (Next.js output)? This app framework is very popular.

The issue has already been discussed in https://github.com/prettier/prettier/issues/4547, so I am going to close this one as a duplicate.

I my opinion, What we should probably do instead is introduce composable ignore patterns, similar to what’s possible [in ESLint with `ignorePatterns`](https://eslint.org/docs/latest/use/configure/ignore#ignorepatterns-in-config-files). See https://github.com/prettier/prettier/issues/4708 and https://github.com/prettier/prettier/issues/7073 (there could be other related issues, but I could not find them today).

**Comment by SevenOutman** [comment]
> [Current implementation of Prettier’s ignore logic](https://github.com/prettier/prettier/blob/e7b383b570db0f5b792887aa87e7b090f43125cb/src/common/create-ignorer.js) does not contain any any special ignore rules except for `node_modules`. Ignoring common file patterns like `pnpm-lock.yaml`, `.yarn/*`, etc., may feel like a simple and good solution, but I’m not sure about that. Once we’ve ignored these ‘obvious’ patterns, what should we do, say, with a feature request to ignore `.next/*` too (Next.js output)? This app framework is very popular.


If `pnpm-lock.yaml` should be considered a "popular framework" thing rather than an "npm basic convention" (like `node_modules`) because its third-party after all, then what about `package-lock.json`? It's not ignored by default either. How's that less npm-native than `node_modules`?
