### ISSUE TITLE
Fix types for `embed`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#14553]
I didn't notice that types for `embed` is totally wrong.

https://github.com/prettier/prettier/blob/1c80e0104f0d81bfec03c652aabf491a7a229914/src/index.d.ts#L478-L485

Correct signature (changed in v3)

https://github.com/prettier/prettier/blob/1c80e0104f0d81bfec03c652aabf491a7a229914/docs/plugins.md?plain=1#L255-L281

/cc @sosukesuzuki

**Comment by fisker** [comment]
https://github.com/prettier/prettier/blob/1c80e0104f0d81bfec03c652aabf491a7a229914/src/index.d.ts#L533-L540

Does this mean `cursorOffset` can't use together with `rangeStart`?

It's incorrect, they can be used together.

**Comment by fisker** [comment]
@Shinigami92 Want help?

**Comment by Shinigami92** [comment]
> @Shinigami92 Want help?

I can try, but not sure if I find the time because I have some other real life plans and in around two weeks I'm in vacation 
On the other side maybe I find some dedicated time in that vacation 😅

But if there is someone else faster, please do so 🙂
