### ISSUE TITLE
Weird formatting for an Angular HTML template

### ISSUE THREAD

**Issue by manu2504** [prettier/prettier#14552]
**Prettier 2.8.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UABCaSaptALSbwC2BxZzLF1ANgIYBGc7RABwgBnWpSgBefCGExOYANZx003ADk4AdyIAnOGEwDMCGEToRumdnEEALaHFQB6cVS692jfDG-PXtOAZCZyw8EAAaEAgBGHFhZFBOHR0ITQAFJIR4lE52TU4AT3jI7h15JRgAZU46OAAZTCg4ZAAzXOE4ErLFOCqBeUaAc2QYHQBXTpBA3nR0ZTrOKEGxzkG4ADEIHTpOGFil5BBOMZgICJBbGDp2AHVbAOF+sDhKrLFsWgLDsGFikEaOjoYGkyoMdq12pMAFbCAAelSG1gAimMIPAIewOpF+jpAYdFssuDpzgIdI0YDdMOgYLZkAAOAAM2JSHRuZQEh1JcEB2GakQAjqj4CDotkjsIqE1lMpznpBZg9CDVuCkG1MZMOnRMCNxhrEXAAIJ7MncE5wNJwHQNJoYrEyfUotHNVWQyJybiU6m0pB0t1lKxDADCEDoKqmwgArOcxh0ACo8bJqu3YCYASSgc1glTAZJiBozlRgBWstrgAF8y0A)

```sh
--parser angular
--tab-width 8
```

**Input:**

```html
<div>
        <ion-item>
                <ion-label position="stacked">New recipient mobile phone</ion-label>
		</ion-item>
</div>
```

**Output:**

```html
<div>
        <ion-item>
                <ion-label position="stacked"
                        >New recipient mobile phone</ion-label
                >
        </ion-item>
</div>

```

**Expected behavior:**

```html
<div>
        <ion-item>
                <ion-label position="stacked">
                        New recipient mobile phone
                </ion-label>
        </ion-item>
</div>
```

**Comment by ilyakonrad** [comment]
Seems like something similar to https://github.com/prettier/prettier/issues/12929.

**Comment by ilyakonrad** [comment]
Also [this](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) might help.

**Comment by sosukesuzuki** [comment]
`--html-whitespace-sensitivity` might help you. So I close this issue temporary, please re-open if your problem still happens.
