### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by rikisamurai** [prettier/prettier#14556]
**Environments:**

- Prettier Version: 2.8.6
- Running Prettier via:  CLI
- Runtime: Node.js v14
- Operating System: Linux
- Prettier plugins (if any): pretty-quick@3.1.3

**Steps to reproduce:**
```bash
pretty-quick --since HEAD~1
```

**Expected behavior:**

**Actual behavior:**
errorr:
```
SyntaxError: Unexpected token, expected "{" (11:8)
   9 |  * smaller git diff.
  10 |  */
> 11 | export declare function main(argv?: string[], entrypointArgs?: Record<string, any>): void;
     |        ^
  12 |
    at p (/home/code/node_modules/.pnpm/prettier@2.8.6/node_modules/prettier/parser-babel.js:22:1054)
    at d (/home/code/node_modules/.pnpm/prettier@2.8.6/node_modules/prettier/parser-babel.js:22:1287)
    at Object.parse (/home/code/node_modules/.pnpm/prettier@2.8.6/node_modules/prettier/parser-babel.js:29:54501)
    at Object.parse (/home/code/node_modules/.pnpm/prettier@2.8.6/node_modules/prettier/index.js:7515:23)
    at coreFormat (/home/code/node_modules/.pnpm/prettier@2.8.6/node_modules/prettier/index.js:8829:18)
    at formatWithCursor2 (/home/code/node_modules/.pnpm/prettier@2.8.6/node_modules/prettier/index.js:9021:18)
    at /home/code/node_modules/.pnpm/prettier@2.8.6/node_modules/prettier/index.js:38183:12
    at Object.format (/home/code/node_modules/.pnpm/prettier@2.8.6/node_modules/prettier/index.js:38197:12)
    at _default (/home/code/node_modules/.pnpm/pretty-quick@3.1.3_prettier@2.8.6/node_modules/pretty-quick/dist/processFiles.js:42:29)
    at _default (/home/code/node_modules/.pnpm/pretty-quick@3.1.3_prettier@2.8.6/node_modules/pretty-quick/dist/index.js:60:29) {
  loc: { start: { line: 11, column: 8 } },
  codeFrame: '\x1B[0m \x1B[90m  9 |\x1B[39m \x1B[90m * smaller git diff.\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 10 |\x1B[39m \x1B[90m */\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 11 |\x1B[39m \x1B[36mexport\x1B[39m declare \x1B[36mfunction\x1B[39m main(argv\x1B[33m?\x1B[39m\x1B[33m:\x1B[39m string[]\x1B[33m,\x1B[39m entrypointArgs\x1B[33m?\x1B[39m\x1B[33m:\x1B[39m \x1B[33mRecord\x1B[39m\x1B[33m<\x1B[39m\x1B[33mstring\x1B[39m\x1B[33m,\x1B[39m any\x1B[33m>\x1B[39m)\x1B[33m:\x1B[39m \x1B[36mvoid\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m    |\x1B[39m        \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 12 |\x1B[39m\x1B[0m'
}
```

**Comment by fisker** [comment]
You must use the wrong parser.

**Comment by rikisamurai** [comment]
But i do not specify the parser.
.prettierrc
```json
{
  "singleQuote": true,
  "trailingComma": "all",
  "arrowParens": "avoid"
}
```

**Comment by rikisamurai** [comment]
> You must use the wrong parser. [typescript](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzjABsBDbOPAMwFcowYBLaPAWzKagAoKBzAG4B+JHgDOMbFz4BtALoAaPAkkBPLFxgBBbHzEi8AJWI4CAHglSofJWSiqAfAEpRAiEwIBuEApAQMzNBiyKAU2BAA7gAKFAjBKGQkEWSqwb4ARthkYADWcDAAymRscAAyXHDI1IlicBlZufkFGNnSyJK0dahs6XAERASldny0ZHxwAGI4HDDM1sggZLQwED4gABYwbCQA6utM8GItYHAFcQdMAgeqC2BiaSBctbhRWXwcVTVdAFZiaAXSEhwACKtAg8E+JFqvha2GeCxg6jgYjAUgCawwVhgOw8MHWyAAHAAGGHhWo7LIYBaY5FwbACSq+ACOYPgr388UWYgAtFA4H0+mtKCymJRXmMPkhqlCurU2Ex2thOr4xIC4FpZlJ0ss4FE6eU+ZDoSBVdYgaDwZUpV9fDAyOkcQQ8cgAEy2rJMEjSADCEDYktQYgArGtaLUACr2+LS40CToASSgRFgBVRTACWiTBURQKNcAAvvmgA) [babel-ts](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzjABsBDbOPAMwFcowYBLaPAWzKagAoKBzAG4B+JHgDOMbFz4BtALoAaPAkkBPLFxgBBbHzEi8AJWI4CAHglSofJWSiqAfAEpRAiEwIBuEApAQMzNBiyKAU2BAA7gAKFAjBKGQkEWSqwb4ARthkYADWcDAAymRscAAyXHDI1IlicBlZufkFGNnSyJK0dahs6XAERASldny0ZHxwAGI4HDDM1sggZLQwED4gABYwbCQA6utM8GItYHAFcQdMAgeqC2BiaSBctbhRWXwcVTVdAFZiaAXSEhwACKtAg8E+JFqvha2GeC3SZF6JAAtDAHhgrDAdh4YOtkAAOAAMMPCtR2WQwC0xcGeAkqvgAjmD4K9-PFFmIUVA4H0+mtKMymJRXmMPkhqlCurU2Ex2thOr4xIC4FpZlJ0ss4FE4NhyjzIdCQMrrEDQeDKhKvr4YEicQQ8cgAEw2rJMEjSADCEDY4tQYgArGtaLUACpI+KSo0CToASSgRFgBTAUgCWgTBRgqiBhrgAF880A)

But i do not specify the parser.
.prettierrc

{
  "singleQuote": true,
  "trailingComma": "all",
  "arrowParens": "avoid"
}

**Comment by rikisamurai** [comment]
After i set prettier-quick@3.0.0, it works!🎉
