### ISSUE TITLE
Don't indent inner HTML tags

### ISSUE THREAD

**Issue by ElHyperion** [prettier/prettier#14565]
**Prettier 2.8.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAgC0ASQByQ5q0pwuAExlMYqGnBhdyYSlwBOAZw2CQAVXwAxEQA4h5APTLV6zeShd1JgG4BLOAHcABwg9GDtIWAQYE38fBRhKfgU4XzA4EVj4ygAach8oHxgfLjoRAzASuH4ARjtHFhVUIpg6OAZcCBpAngBPVHtm1pl+uUVhgCMIBR6nNnlkvXbO7qg++1GF2ZoufKdGymqGAAl5-N4Rw4bVe23dq9QAMwgIeEWASvIOrt7+p5e4RYsfqTabDda0RgsEDZEAQQJFaAGZCgfR6CD+Yj6BBIlAlfxcHpImHjPRcMAAaw0AGUPHAADL5ODIB4lIzE0kU6ndMBnZAwPQAVzgMLgNHGcAUyQUdJ4vAFXF4cAsIW2MCKfGQIC4ApgEGhIHYdAA6pRCnADNy4FTsYUfL4YD1NWADESQPkjKFiKTeNtmazhSAAFYGAAeVLOrQAigL-n66GyQN1DADNYb9YE9PkYEa4glkNYAAwwjMQIxG0mBTUZ80ArxMmEARxj8C9cJxWoMIigcAlEv1ejgTZ8A69Ct9SBZ8YDRhoPj5gunEbg0djE-9MM04xzWWQACYN6SfHQzl9x8IDABWfUCoz4LjjHH8oUwrxCsRQZKwKlgTPwgCCH5Ug6rRxkYAC+YFAA)

**Input:**

```jsx
<!DOCTYPE html>
<html lang="en-IN">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Company</title>
</head>
<body>
	<header>Company</header>
	<main>
		<h1>Heading</h1>
	</main>
	<footer>© Company</footer>
</body>
</html>

```

**Output:**

```jsx
<!DOCTYPE html>
<html lang="en-IN">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Company</title>
	</head>
	<body>
		<header>Company</header>
		<main>
			<h1>Heading</h1>
		</main>
		<footer>© Company</footer>
	</body>
</html>
```

**Expected behavior:**
Indenting <head> and <head> should be optional. Prettier currently unnecessarily indents the whole HTML file which restricts a lot of horizontal space for body and head tag contents, with no option to control this behaviour 

For example, a Prettier option "indent_inner_html" could be added.

Issue where this has been already discussed previously, with no response but positive feedback from the community: [https://github.com/prettier/prettier/issues/12348](https://github.com/prettier/prettier/issues/12348)

**Comment by sosukesuzuki** [comment]
We cannot add option for this issue. Please see https://prettier.io/docs/en/option-philosophy.html
Also I don't think we will never add support for this format. Our apologies.
