### ISSUE TITLE
Parens incorrectly added to array destructring when using Flow parser

### ISSUE THREAD

**Issue by fortes** [prettier/prettier#1457]
Input:

```js
const [one, two = null, three = null] = arr;
```

[Result w/ flow parser](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20%20const%20%5Bone%2C%20two%20%3D%20null%2C%20three%20%3D%20null%5D%20%3D%20arr%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)  (note parens around `two` and `three`):

```js
const [one, two = (null, (three = null))] = arr;
```

Expected (and what happens w/ babylon parser): 

```js
const [one, two = null, three = null] = arr;
```

As you can see, this isn't just a cosmetic issue since it breaks the value of `three` completely. Note that `const [one, two = null] = arr;` works as expected.

**Comment by vjeux** [comment]
Oh wow, looks like the flow parser is getting it terribly wrong. Could you open an issue in the flow repo, they should fix this as they parse an entirely incorrect AST.

**Comment by fortes** [comment]
@vjeux what's the best way to report this to the flow folks? I'm not quite sure what the repro would be other than prettier.

**Comment by fortes** [comment]
Looks like this issue has been in Flow for almost a year: https://github.com/facebook/flow/issues/1985

**Comment by vjeux** [comment]
I pinged the flow team about it, hopefully they can fix it. In the meantime, you can add

```js
// prettier-ignore
```

in front of the line to "fix" it.
