### ISSUE TITLE
No linebreak after comment with special character when using flow parser

### ISSUE THREAD

**Issue by fortes** [prettier/prettier#1458]
Not sure if this is another issue in just the flow parser, but here's the repro:

Input:

```js
const foo = {
  /* ⌘
   */
  bar() {},
};
```

[Output w/ flow parser](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20foo%20%3D%20%7B%5Cn%20%20%2F*%20%E2%8C%98%5Cn%20%20%20*%2F%5Cn%20%20bar()%20%7B%7D%2C%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) (note lack of linebreak after `*/`):

```js
const foo = {
  /* ⌘
   */ bar() {}
};
```

Expected (and with babylon parser):

```js
const foo = {
  /* ⌘
   */
  bar() {}
};
```

If you replace the `⌘` with a normal character, the line break is restored: https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20foo%20%3D%20%7B%5Cn%20%20%2F*%20a%5Cn%20%20%20*%2F%5Cn%20%20bar()%20%7B%7D%2C%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Yeah, so the flow parser used to report invalid locations when unicode characters were printed. Fortunately, they fixed it and released a fix yesterday and I merged the update to master. So next time I do a release it's going to be fixed. In the meantime you can use the babylon parser.
