### ISSUE TITLE
Playground is broken

### ISSUE THREAD

**Issue by sijad** [prettier/prettier#14607]
- Prettier Version: 2.8.7
- Running Prettier via: Browser API
- Runtime: Version 111.0.5563.110 (Official Build) (arm64)
- Operating System: macOS
- Prettier plugins (if any): 

**Steps to reproduce:**

open https://prettier.io/playground/

**Expected behavior:** a working playground

**Actual behavior:** there's an error

```
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://prettier.io/lib/plugins/estree.js' failed to load. at https://prettier.io/worker.js:12:1
```

**Comment by fisker** [comment]
Users can you https://deploy-preview-14584--prettier.netlify.app/playground/ temporarily.

**Comment by fisker** [comment]
It's up again. FYI: You may notice it's slower than before, we'll improve it in future.

**Comment by joemaller** [comment]
Seems broken again?

**Comment by kachkaev** [comment]
@joemaller which browser are you using? Just tried opening https://prettier.io/playground/ – it did load.

**Comment by joemaller** [comment]
@kachkaev Apologies for lack of detail. This was in macOS Safari 16.3, the playground was throwing with `SyntaxError: Invalid regular expression: invalid group specifier name`. 

Playground is working correctly after the latest macOS update which bumped Safari to 16.4 and [finally supports RegExp lookbehind](https://caniuse.com/mdn-javascript_regular_expressions_lookbehind_assertion).
