### ISSUE TITLE
Parentheses of IIFE "hanging out"

### ISSUE THREAD

**Issue by sladiri** [prettier/prettier#1461]
I find Douglas Crockford's opinion about IIFE bracket placement more appealing than the current setting:
```javascript
(function() {}())
// instead of current format:
(function() {})()
```
Anyway, this is a great project.

**Comment by ndresx** [comment]
I _personally_ tend to variant 2, simply because I can immediately see that some sort of invocation is happening, no matter what's going on in the preceding expression.

**Comment by sladiri** [comment]
@ndresx I can see your point too, yes, the invocation is an important hint.

**Comment by bakkot** [comment]
While I like the first style from a sort of idealogical purity perspective, I think the second and current style is overwhelmingly more common in JS written today.

**Comment by sladiri** [comment]
@bakkot Hm, ESLint's default is to put them inside, but I guess many put them outside, that is why Mr. Crockford mentioned them in on of his talks.

And actually ideologically I cannot decide now. :)
- If you see functions as first class as they are, their invocations should be visible, so outside.
- A pure function should be the equivalent of a value, that is where I would put them inside.
But we cannot know automatically if a function is really pure.

So I am not so sure anymore and I can live with the current setting. :)

**Comment by vjeux** [comment]
If you are interested in changing the behavior, feel free to send a PR and I'll merge it, I don't care either way and no thoughts have been put in the current behavior. In the meantime, I'm going to close this issue as it's not something that I'm going to spend anytime on.
