### ISSUE TITLE
Installing via pnpm will not load plugins

### ISSUE THREAD

**Issue by Eldair** [prettier/prettier#14616]
**Environments:**

- Prettier Version: 2.8.7
- Running Prettier via: vscode
- Runtime: vscode, nodejs 19.8.1
- Operating System: wsl2 - ubuntu
- Prettier plugins (if any): @prettier/plugin-php

**Steps to reproduce:**

Project with prettier and @prettier/plugin-php installed via pnpm

**Expected behavior:**

Can format php files with prettier

**Actual behavior:**

Prettier cannot format php files - plugin not detected

Using pnpm to install deps breaks prettier plugins. Adding php-plugin to prettierrc doesn't fix the issue.

**Comment by fisker** [comment]
Duplicate of #8056
