### ISSUE TITLE
eslint-disable comments inside JSX brackets

### ISSUE THREAD

**Issue by vinhlh** [prettier/prettier#1463]
```js
const render = items => (
  <div>
    {
      	/* eslint-disable rule-1 */
    	items.map(item => null)
    	/* eslint-disable rule-2 */
    }
  </div>
)
```
[to](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20render%20%3D%20items%20%3D%3E%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5Ct%2F*%20eslint-disable%20rule-1%20*%2F%5Cn%20%20%20%20%5Ctitems.map(item%20%3D%3E%20null)%5Cn%20%20%20%20%5Ct%2F*%20eslint-disable%20rule-2%20*%2F%5Cn%20%20%20%20%7D%5Cn%20%20%3C%2Fdiv%3E%5Cn)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)
```js
const render = items => (
  <div>
    {/* eslint-disable rule-1 */
    items.map(item => null)
    /* eslint-disable rule-2 */
    }
  </div>
);
```

But
```js
const render = items => (
  <div>
    {/* eslint-disable rule-1 */
    items.map(item => null)
    /* eslint-disable rule-2 */}
  </div>
)
```
is better, right?

**Comment by vjeux** [comment]
Yeah, your example looks better. I'm not sure how hard it is to do in practice though. JSX `{}` comments are notoriously hard to get right and this is very much an edge case.
