### ISSUE TITLE
No parser could be inferred for png image files

### ISSUE THREAD

**Issue by o-t-w** [prettier/prettier#14645]
**Environments:**

- Prettier Version: 2.8.7
- Running Prettier via: CLI
- Runtime: 
- Operating System: macOS
- Prettier plugins (if any): 

**Steps to reproduce:**

I have the following script in my package.json in an [Astro project](https://github.com/o-t-w/blog) that is using a popular Astro theme: 
```
"format": "prettier --plugin-search-dir=. --write .",
```
It is using Prettier upon commit using Husky. 

**Expected behavior:**
No errors

**Actual behavior:**
I am getting the following error: 
```
[error] No parser could be inferred for file: public/assets/caniemailstats.png
[error] No parser could be inferred for file: public/assets/email.png
[error] No parser could be inferred for file: public/assets/emailstats.png
```

**Comment by kachkaev** [comment]
👋 @o-t-w! Does [`--ignore-unknown`](https://prettier.io/docs/en/cli.html#--ignore-unknown) help you achieve your goal? Feel free to close this issue if it does.

**Comment by kachkaev** [comment]
Alternatively, you can ignore all files and then un-ignore certain file extensions in your `.prettierignore`. This will allow you to use `**/*` or `.` for file paths everywhere, while having a single source of truth for the ignore rules. Here is an example of this trick in a personal project of mine: [🐸 `njt` / `.prettierignore`](https://github.com/kachkaev/njt/blob/20987460c58047bb21bf8fee061f27f7d19ad784/.prettierignore#L5-L17).
