### ISSUE TITLE
Starts template string return value on next line for arrow functions

### ISSUE THREAD

**Issue by ismay** [prettier/prettier#1465]
When formatting the following:

```javascript
const inlineStore = preloadedState => `
  <script>
    window.preloadedState = ${JSON.stringify(preloadedState).replace(/</g, '\\u003c')}
  </script>
`
```

Prettier changes it so that the template string return value starts on the next line:

```javascript
const inlineStore = preloadedState =>
  `
  <script>
    window.preloadedState = ${JSON.stringify(preloadedState).replace(/</g, '\\u003c')}
  </script>
`
```
[Live example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20inlineStore%20%3D%20preloadedState%20%3D%3E%20%60%5Cn%20%20%3Cscript%3E%5Cn%20%20%20%20window.preloadedState%20%3D%20%24%7BJSON.stringify(preloadedState).replace(%2F%3C%2Fg%2C%20'%5C%5C%5C%5Cu003c')%7D%5Cn%20%20%3C%2Fscript%3E%5Cn%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

It doesn't do this when using a normal function, so this stays the same:

```javascript
const inlineStore = function(preloadedState) {
  return `
    <script>
      window.preloadedState = ${JSON.stringify(preloadedState).replace(/</g, '\\u003c')}
    </script>
  `
}
```

[Live example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20inlineStore%20%3D%20function(preloadedState)%20%7B%5Cn%20%20return%20%60%5Cn%20%20%20%20%3Cscript%3E%5Cn%20%20%20%20%20%20window.preloadedState%20%3D%20%24%7BJSON.stringify(preloadedState).replace(%2F%3C%2Fg%2C%20'%5C%5C%5C%5Cu003c')%7D%5Cn%20%20%20%20%3C%2Fscript%3E%5Cn%20%20%60%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

To me it looks weird to start the template string on the next line (even though it is valid). Could this be considered a bug, or is this intended behaviour?

**Comment by vjeux** [comment]
Looks like we handle the case where we have a TaggedTemplateLiteral but not the one with just a TemplateLiteral. I'll send a fix.

```js
() => a`
	a
`
() => `
	a
`
```

outputs

```js
() => a`
	a
`;
() =>
  `
	a
`;
```

Thanks for the report!

**Comment by ismay** [comment]
Awesome, thanks!
