### ISSUE TITLE
Add warning on vim usage when doing format on save

### ISSUE THREAD

**Issue by Arch-Mage** [prettier/prettier#1466]
I use vim and use vanilla approach from [README.md][readme]. And add this line:

```vim
autocmd BufWritePre *.js :normal gggqG
```

to my `.vimrc`.

Today, I'm working on some codes from morning until evening. I've wrote almost a thousand lines of
code. I didn't do git commit yet, just save (`:w`). Then I'm tired, and plan to continue tomorrow, so I
save and close the file (`:wq`). For less than a second, there is a red message right before vim closed.
I felt something wrong and check the file right away and I got this:

    stdin: SyntaxError: Unexpected token (345:2)
      343 |   return moves.filter(move => {
      344 |     const
    > 345 |   })
          |   ^
      346 | }
      347 | 

written in my work today.

Then I'm playing chess and smile.

<hr/>

I think there's should be a warning on [vim vanilla approach][readme], so user know the risk and doesn't
playing chess like me :rofl:.

[readme]: https://github.com/prettier/prettier/blob/768a81c5d55bf1908cab26c30cb5939413c05886/README.md#vanilla-approach

**Comment by vjeux** [comment]
Omg, this is horrible! So sorry about that. I have never used vim myself so I have no idea how to actually fix this, but we absolutely should stop recommending this is you can lose your work like this.
