### ISSUE TITLE
Prettier fails to parse TypeScript function with "assert condition" phrase

### ISSUE THREAD

**Issue by JESii** [prettier/prettier#14667]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgM7FwBOMAksQMozk5QDmAFAG6EA2SRUAngEpeJMpWL5OXfDgnEGTZvmAAdKPhmp8rGPwAOcCFqn4AhAF5z+FSHmMWNwcrUaNMABbkIAd3xQ4vgCCpBS40ACi5F7krDYAchAwRPh2iqaOANwu+AC+ajkgADQgEHphUMTIoIRRPgAKNQiVKNzehPyVxQBG5IRgANZwMLSEALZwADJMcMio3GTdvQNDtHp9isgM6HDFcKNdcAAmh0cThCzohMxwAGIQ5KOEMLgsyCCE6DAQRSDuMKNcADq7hw8GIazAcFoTVBOHYoP4bzApB+TDEMDqvWYj1m8x2IAAVsQAB60RRcOAARXQiRmSDmXAWIDW5DEby6hAOXB+ensMEBOEOHmQAA4AAzFXkQMiA3p6N68uBidgzYoARxp8ExpWa72IAFp-Ecjj9yHANTgzZirjj6XjimRRjhNuRtg7yXBAs9GF1PnA6hQpv5cYz8cQPdTaSGmTBOQKhe5kAAmYoMQg4LiKADCEFGtpASoArD90GQACqc5oMpnsbZUKAnWC0MCMMqBBv0fgU6NwHI5IA)

```sh
--parser babel
```

**Input:**

```jsx
function assertIsString(val: any): asserts val is string {
  if (typeof val !== "string") {
    throw new AssertionError("Not a string!");
  }
}
```

**Output:**

```jsx
SyntaxError: Unexpected token, expected "{" (1:44)
> 1 | function assertIsString(val: any): asserts val is string {
    |                                            ^
  2 |   if (typeof val !== "string") {
  3 |     throw new AssertionError("Not a string!");
  4 |   }
```

**Expected behavior:**
This is valid code from the TypeScript Handbook: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

**Comment by sosukesuzuki** [comment]
Please use `typescript` parser

**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgM7FwBOMAksQMozk5QDmAFAG6EA2SRUAngEpeJMpWL5OXfDgnEGTZvmAAdKPhmp8rGPwAOcCFqn4AhAF5z+FSHmMWNwcrUaNMABbkIAd3xQ4vgCCpBS40ACi5F7krDYAchAwRPh2iqaOANwu+AC+ajkgADQgEHphUMTIoIRRPgAKNQiVKNzehPyVxQBG5IRgANZwMLSEALZwADJMcMio3GTdvQNDtHp9isgM6HDFcKNdcAAmh0cThCzohMxwAGIQ5KOEMLgsyCCE6DAQRSDuMKNcADq7hw8GIazAcFoTVBOHYoP4bzApB+TDEMDqvWYj1m8x2IAAVsQAB60RRcOAARXQiRmSDmXAWIDW5DEb10BmIYEYZR+ensMEBOEOHmQAA4AAzFfkQMiA3p6N78uBidgzYoARxp8ExpWa72IAFp-Ecjj9yHAtTgLZirjj6XjimRRjhNuRtk7yXBAs9GF1PnA6hQpv5cYz8cQvdTaWGmTBCF0hSL3MgAEzFBiEHBcRQAYQgo3tIBVAFYfugyAAVBPNBlM9jbKhQE6wWjcnBlQLN+j8CmxuA5HJAA)

```sh
--parser typescript
```

**Input:**

```tsx
function assertIsString(val: any): asserts val is string {
  if (typeof val !== "string") {
    throw new AssertionError("Not a string!");
  }
}
```

**Output:**

```tsx
function assertIsString(val: any): asserts val is string {
  if (typeof val !== "string") {
    throw new AssertionError("Not a string!");
  }
}

```
