### ISSUE TITLE
Nested TypeScript generics are not well line-wrapped (even if input is)

### ISSUE THREAD

**Issue by jamesgpearce** [prettier/prettier#14666]
Found a bug. Thank you for your consideration!

**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwHkBXebAFWLgB4AdKPPAGWgHM5tOoefbr36CAklCi86JPOnhQAJgGcOwoQJHrRvMjAAW0+s1ZtyUgLI44MuCzYA+Fg7wBePMACGSPAEYAvgDcLAD0IXgACthwMDAAlrx4EFQYVHhxqgA26gT6nqwAHAAMeGB52J5g1MogADQgEBjx0DVIoJ7Y2BAA7hEdCK0gnpndnoQ19QBGFWAA1jEAyp4AtnDscVLIAGbDynBTM-MwCxiVG1zIMNgU+6jLk3CKio-s+VwUnjwAYjjLnrHnZBDKgQOogfQwZaZADq+ji8GUpzAcAWA3hcQAbvDCECwMoJiANntcFFPn9trtbgArZRoBbnTJwACKFAg8ApmT29VO2GJQKIJGUYGwcSaYIwItg0LiigMyGK3K6e2hFQwQIlcGJGLgYIAjqz4FFGoNPMoALRSR6PMHRfVxaKkrjkpA7Tm3PbLOKXa7uhlwACCsRFkyocAiIg2OpdlPqyj9LLZUddXJAME8k2lsv0yAATPUrp44plzgBhCDLZ2oZQAVjBFD2NHTrWTtwxNwkz1gC2Fopg-qUCyIjI5e38-iAA)

```sh
--parser typescript
```

**Input:**

```tsx
export type OuterType<
  LongerLongerLongerLongerInnerType extends LongerLongerLongerLongerOtherType<
    OneMoreType
  >
> = {a: 1};
// Prettier output is longer than 80 characters
```

**Output:**

```tsx
export type OuterType<
  LongerLongerLongerLongerInnerType extends LongerLongerLongerLongerOtherType<OneMoreType>
> = { a: 1 };
// Prettier output is longer than 80 characters
```

**Expected behavior:**
I expect the Prettier output to fit within the 80 character line length (especially since the input does)

**Comment by jamesgpearce** [comment]
(I tried commenting things like #11923 but that didn't work. Having to resort to `// prettier-ignore` for now)

**Comment by sosukesuzuki** [comment]
I prefer breaking line after `extends` for this case:

```ts
export type OuterType<
  LongerLongerLongerLongerInnerType extends
  　　LongerLongerLongerLongerOtherType<OneMoreType>
> = {a: 1};
```

**Comment by jamesgpearce** [comment]
woohoo, thanks @sosukesuzuki!
