### ISSUE TITLE
prettier typeof will add brackets, how should I configure it to ignore typeof syntax 

### ISSUE THREAD

**Issue by holiy930561** [prettier/prettier#14660]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```
![image](https://user-images.githubusercontent.com/63273780/229491766-11ab1efb-be63-40a0-be45-cfd45ce77670.png)
![image](https://user-images.githubusercontent.com/63273780/229491808-5b6dd966-6510-44b7-bb51-ca322ad69b72.png)

**Expected behavior:**

**Comment by fisker** [comment]
This change is intended and can't be disabled, see #13546 and #14042.
