### ISSUE TITLE
`<generic>type` assertions `unexpected token`

### ISSUE THREAD

**Issue by ekwoka** [prettier/prettier#14670]
Closest issue I could find was on an older version but in their case it was working (and doing something else), while I'm having it not work at all

**Environments:**

- Prettier Version: 2.8.7
- Running Prettier via: CLI
- Runtime: Node Latest
- Operating System: MacOS
- Prettier plugins (if any): `@trivago/prettier-plugin-sort-imports`

**Steps to reproduce:**

any ts file do `<string>foo`

**Expected behavior:**

Understands this.

**Actual behavior:**

`unexpected token`

**Comment by sosukesuzuki** [comment]
Does this also happen if you disable the plugin? If your answer is no, it could be a problem with @trivago/prettier-plugin-sort-imports. If your answer is yes, please create and share a reproduction repository.

**Comment by ekwoka** [comment]
You are right. Didn't seem like it would be related, but it is :)
