### ISSUE TITLE
Any plans to cut a new release?

### ISSUE THREAD

**Issue by pbomb** [prettier/prettier#1468]
I would love to see a new release cut with the recent merge for #1447 which understands the new `import()` syntax. I'm trying to bring that into my project (along with [react-loadable](https://github.com/thejameskyle/react-loadable)), but I can't because prettier complains with a SyntaxError.

Any chance of releasing what's already in master soon?

**Comment by vjeux** [comment]
Yeah, I'm planning to do a release on Monday! Sorry for the wait.

**Comment by pbomb** [comment]
Great, thanks! No need to apologize.

**Comment by vjeux** [comment]
I merged all the fixes I wanted and ran the release through Facebook codebase and everything looks good. I'm going to write the changelog and do the release tomorrow. Sorry for the wait!
