### ISSUE TITLE
`import` syntax error

### ISSUE THREAD

**Issue by anmonteiro** [prettier/prettier#1469]
With current master, this works:

```js
const x = import('some-module').then(x => {
  // ...
});
```

but this does not:

```js
import('some-module').then(x => {
  // ...
 });
```

the above snippet fails with:

```
prettier errors:
react-ssr-middleware.js: SyntaxError: Unexpected token import (14:2)
  12 |   const importPath = componentPath.replace(/\.([^\/]+)$/, '.js');
  13 | 
> 14 |   import('some-module').then(x => {
     |   ^
  15 |     // ...
  16 |   });
  17 | }
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22import('some-module').then(x%20%3D%3E%20%7B%5Cn%20%20%2F%2F%20...%5Cn%20%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by anmonteiro** [comment]
Note: this only happens with `--parser=flow`

**Comment by anmonteiro** [comment]
Just saw this is open in Flow https://github.com/facebook/flow/issues/3841

**Comment by vjeux** [comment]
Cool, so as soon as flow supports it, we should too :)

**Comment by SimenB** [comment]
Isn't facebook/flow#3841 the exact opposite? There it says it fails if assigned, while in this issue it fails if _not_ assigned

**Comment by anmonteiro** [comment]
Fails "unless it's assigned"
