### ISSUE TITLE
Don't indent <head> & <body>

### ISSUE THREAD

**Issue by soredake** [prettier/prettier#14698]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAgC0ASQByQ5q0pwuAExnlyqGnBhdyYSlwBOAZw2CQAVXwAxEQA4h5APTLV6zeShd1JgG4BLOAHcABwg9GDtIWAQYE38fBRhKfgU4XzA4EVj4ygAach8oHxgfLjoRAzASuH4ARjtHFhVUIpg6OAZcCBpAngBPVHtm1pl+uUVhgCMIBR6nNnlkvXbO7qg++1GF2ZoufJkmGDZqhgAJefzeEaOG1Xtt3evUADMICHhFgEryDq7e-ufXuCLFj9SbTYbrWiMFggbIgCCBIrQAzIUD6PQQfzEfQIZEoEr+Lg9ZGw8Z6LhgADWGgAyh44AAZfJwZCPEpGElkyk07pgc7IGB6ACucFhcBo4zgCmSCnpPF4gq4vDgFhC2xgRT4yBAXEFMAgMJA7DoAHVKIU4AYeXBqTjCj5fDAelqwAZiSB8kZQsQybxtiy2SKQAArAwAD2p51aAEVBQD-XR2SBuoZAVqjQbAnp8jBjXEEshrAAGWGZiBGY1kwJazMWwFeZmwgCOsfg3vhuO1BhEUDgkslBr0cGbPkH3sVfqQrITgaMNB8-KFM8jcAAguqs+NdXBiIDGT344mDMuY3HJwHYZpxrmssgAEwXsk+Ojnb4T4QGACsBsFRnwXHGuJTomXjCmIUDJLA1JgFmCIruB1KOq0B5wAAvihQA)

```sh
--parser html
```

**Input:**

```html
<!DOCTYPE html>
<html lang="en-IN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Company</title>
</head>
<body>
  <header>Company</header>
  <main>
	<h1>Heading</h1>
  </main>
  <footer>© Company</footer>
</body>
</html>

```

**Output:**

```html
<!DOCTYPE html>
<html lang="en-IN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Company</title>
  </head>
  <body>
    <header>Company</header>
    <main>
      <h1>Heading</h1>
    </main>
    <footer>© Company</footer>
  </body>
</html>

```

**Expected behavior:**
On smaller viewport width indenting `<head>` & `<body>` only create unnecessary overflow.

That extra whitespace might be *OKAY* if you have wider viewport width.
**BUT not for majority of others**
 
A Prettier option "indent_inner_html" with default value true would be nice have.

Originally reported here: https://github.com/prettier/prettier/issues/12348

**Comment by sosukesuzuki** [comment]
We will not add an option for this. Please see https://prettier.io/docs/en/option-philosophy.html.

Also, since `head` and `body` are definitely contents of `html`, it would make sense to indent them.

**Comment by kachkaev** [comment]
Duplicate of https://github.com/prettier/prettier/issues/12348 and https://github.com/prettier/prettier/issues/14565
