### ISSUE TITLE
Unstable comment before long JSX expression

### ISSUE THREAD

**Issue by smably** [prettier/prettier#1472]
```jsx
renderClickableDiv = callback => (
  // eslint-disable-next-line jsx-a11y/no-static-element-interactions
  <div className="clickable" onClick={callback} data-long-attribute="something">
    click me
  </div>
);
```

```jsx
renderClickableDiv = callback => // eslint-disable-next-line jsx-a11y/no-static-element-interactions
(
  <div className="clickable" onClick={callback} data-long-attribute="something">
    click me
  </div>
);
```

```jsx
renderClickableDiv = (
  callback // eslint-disable-next-line jsx-a11y/no-static-element-interactions
) => (
  <div className="clickable" onClick={callback} data-long-attribute="something">
    click me
  </div>
);
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22renderClickableDiv%20%3D%20callback%20%3D%3E%20(%5Cn%20%20%2F%2F%20eslint-disable-next-line%20jsx-a11y%2Fno-static-element-interactions%5Cn%20%20%3Cdiv%20className%3D%5C%22clickable%5C%22%20onClick%3D%7Bcallback%7D%20data-long-attribute%3D%5C%22something%5C%22%3E%5Cn%20%20%20%20click%20me%5Cn%20%20%3C%2Fdiv%3E%5Cn)%3B%5Cn%5CnrenderClickableDiv%20%3D%20callback%20%3D%3E%20%2F%2F%20eslint-disable-next-line%20jsx-a11y%2Fno-static-element-interactions%5Cn(%5Cn%20%20%3Cdiv%20className%3D%5C%22clickable%5C%22%20onClick%3D%7Bcallback%7D%20data-long-attribute%3D%5C%22something%5C%22%3E%5Cn%20%20%20%20click%20me%5Cn%20%20%3C%2Fdiv%3E%5Cn)%3B%5Cn%5Cn%5CnrenderClickableDiv%20%3D%20(%5Cn%20%20callback%20%2F%2F%20eslint-disable-next-line%20jsx-a11y%2Fno-static-element-interactions%5Cn)%20%3D%3E%20(%5Cn%20%20%3Cdiv%20className%3D%5C%22clickable%5C%22%20onClick%3D%7Bcallback%7D%20data-long-attribute%3D%5C%22something%5C%22%3E%5Cn%20%20%20%20click%20me%5Cn%20%20%3C%2Fdiv%3E%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Oh wow, this one is bad :( Thanks for the report!

**Comment by jdeniau** [comment]
Same if you use `// eslint-disable-line`

[example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20foo()%20%7B%5Cn%20%20return%20(%3Cdiv%3E%5Cn%20%20%20%20%7B%5B'a'%2C%20'b'%2C%20'c'%5D.map((value%2C%20key)%20%3D%3E%20(%5Cn%20%20%20%20%20%20%3Cdiv%20key%3D%7Bkey%7D%3E%7B%2F*%20eslint-disable-line%20react%2Fno-array-index-key%20*%2F%7D%5Cn%20%20%20%20%20%20%20%20%7Bvalue%7D%5Cn%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20))%7D%5Cn%20%20%3C%2Fdiv%3E)%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
This was fixed by https://github.com/prettier/prettier/pull/1712
