### ISSUE TITLE
Ruby Linter

### ISSUE THREAD

**Issue by nice-edox** [prettier/prettier#14720]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCWMA2cAEAdEAFTgGd0oBzHKOGAdwgCcBrHSAWwAcISNd2IAEwCu2HADMmONLDgVGAQ3TQc8MgTxRNFMJwD6nRhABWcMDD1pBOALzSonYTAAUBHfsMmzFqwQCUmgBunGB6NPRMrDjRdjKOLgTBoeEMLP6amgDEOACiUCTCjLgA4gDCAAo4nqbmOHAAHmhkJJqQsEaY+CDuALTV3gQ4ghCa0dFoXAq1AIwAdAAMo2PoWLgEeQVFVUY1MHWNzRpaUGNDpGCMaABGuBQQEBTYBjvezv3mSDjuz17mloJ+IYjE5jDA4YA4EgACwgomsDSaewAvktotlxi5MGhxGYAJ5gJ5kJRwQHAAgAQVKhAAkgA1HIEFEg6IIQSaVkZKDZDaFXAcbi8eA9AQiMRNNhFYlsqBtGAdLopSI9fk8PjCoSiOCDYanXV6-XRVHSSYzBYG80W05GlZiAjEMiqKG4ABytFSrAAshrsIMLUsjYJzpcbl97o84D9dm8Xh8vrpI95-oDhkawRDobDMPCDsjUzASM4AOTvHyCQukyEwuFsLhxjwx0s4JmnDk0KDWTnc-K8us9JI9RUsaQkCVwKWtaByiCdNy6PshdWirUgIGpk17OaLZmqDC2oikPbY3v9wesBHqECc06BkgXa63MNPJJhN2RaO-GCfZ+n5PA04YAsCHPGB-HwbcAKLIkYGEEhy3BStM3hABHHBCwAVXKQsmyNVsAyDe9QweJ5Tz0JJ312T4CHENAijoBRMEwHpGE1FoQF-PNAJAYDQJw9t2T444u02XBqNo+jOmY7ARwULYSFoMDZXlQtelEuA6IYkgenEnoAGYsJTbcbVwQseS2KAIBwABlSyAAkcCkGzCEISpxIgOg4GsGQJBotTxJwSTSELI07iIiN+ScCNVPUzACxLT5lLnEty1mKLxLCBR2FIWYxzAKEgRwAAfVKGPSzKCt46U8NvYMH1CvRwvgPRiswcjvE+XoSwAGmoDK4E+ZrSpJVdwL2dMqyzfZEWwkaC0LVz3MEPQSGhAB+OD4IzasQ3Eei5Om-98yLeaPL0KEYBgTg1sBDbxusbbdtwZsxlw7cbzvEMQvDeqIC4CKmp86LYobSjwCdcQehkEhODMHp3FAgyDs4gaAssSgimW0DgE2rMwggQ8ZUwYRAy6QMdtEGAtIYtyemWqFGQqq8xjemrCK+hrIoB8SgY-EHcrgcHIehsBYd0fxZjoJ0imcAbBB88w0GgEGcmdYoACUcms+G-1BfMxsQ3G9mA-bnoEqr3tqr6SLIuKuj5gX8iFkXOC1jjXC4nMeO3F7r3wj7HwjK2Qla2MCDtiGHZhuG2OGxG3e46OGeOH3qoIz7iNfFhSKDm3Q7B8Oocj0Xo4RnXOPjwFE5eoSewJWFrCMCLGGHUdxxlSd5VnTgmNheBGG1bWJk4KYNwWJYjK6Uy+R++JcAb3ucBuBAW-gNlLyTs4U79ur2b0Oe4EYbmKLrBM-isbqigoBWoBBuBCggaGencsgACYXZBCCCCgXrWIrbHPIJomawQBQgUPOKA3dG7TEGE9VsVdcjdi2AAEWdJZHA5JyjUmbggBQVxsDSkUtOLoHUGw033oENAYBSD9zXEPU0W5Tjj3WAg3AJZIRkIoaQHAMlcDYNwR5I4ZsWZpwjCWJa7DKHB0-MfURZ8eqZRBoIfIsxhEKE4E0WYHA36Iz1tWI2T0MScSgsuX+t0aycAns6ckAAhAAMjkRB0DK4CRAJ1EA99lD5GQKAGSRg6DlG4Z4lA9E6K4hIC4kAVxFBgGYLQSyvUbEyDgMgHaMU4CuMiVMGJMBLK0JkBQZAcphBpK4uwG4ghAyCBsQoSgwgFAUDgAAMSYOwJQ5B8lBKcBAcJZ12CYAAOpQj4FDKYcBLIIEFGgchMBcTIHAMtcJkN94wHKIoCgLTkkPVccYEg9RLJ5OwAARWEHjJJSAUlyVcUPA++9ZlXBwXATA4TDAyBgH0qwMAoTIAABzzEuUYOSfTFCcFmYYUgZCkmuKQsc+AKz75hKCZpGgHkPLhKKFCnyKy6nrLOZskAcl2BoAKcxYpvBKDYHJOdYMEVyj7wSTQDZqTXGkvDEck5DKLmoBwW8wQHzkDP1cXKBQaAsSUFKD9bFXESAAFZwkwTgIQHB8LznFMCEU6k7YEDZLvJwGA5J2yWWmdgdlcAkRIiAA)

```sh
--parser babel
```

**Input:**

```jsx
title "Testing network composite module for integration test"

gcp_project_id = input("gcp_project_id")
vpc_network    = input("vpc_network")

# Ensure GCP project exists
control "gcp-project" do
    impact 1.0
    title "Ensure project exists"

    describe google_project(project: gcp_project_id) do
    it { should exist }
    #   it(lifecycle_state) {"ACTIVE"}
    end
end

# Ensure composite-module is created
control "network-composite-module" do                        
    impact 1.0                               
    title "Test the Network Module"           
  
    describe google_project(project: gcp_project_id) do
    it { should exist }
    its('project_id') { should cmp gcp_project_id }
    end
end 

# Ensure gcp-vpc-network is created
control "gcp-vpc-module" do
    impact 1.0
    title "Test if gcp-vpc-network exist"

    describe google_vpc_network(project: vpc_network) do
    its("exist") 
    its('status') { should eq 'UP' }
    end

    describe google_network_vpc(project: "firewall-rules") do
    its("exist") 
    end
end

# Ensure firewall rules are set 
control 'gcp-firewalls-all-3' do
    title 'Ensure no SSH or HTTP allowed in firewall rules'
    google_compute_firewalls(project: 'gcp-project').firewall_names.each do |firewall_name|
    end

    describe google_compute_firewall(project: gcp-project, name: firewall_name) do
    it { should exist }
    its('allowed_ssh?')  { should be false }
    its('allowed_http?')  { should be false }
    end

    describe google_compute_firewalls(project: "chef-inspec-gcp") do
    its("firewall_rule_ingress") {should_not include "default-allow-ssh"}
    end

    describe google_compute_firewalls(project: "chef-inspec-gcp").where(firewall_direction: "ENGRESS") do
    its{ should_not exist }
    end

    describe google_network_vpc(project: "chef-inspec-gcp") do
    its("exist") 
    end

    describe google_network_vpc(project: "chef-inspec-gcp") do
    its("exist") 
    end

    describe google_network_vpc(project: "chef-inspec-gcp") do
    its("exist") 
    end
end

# Ensure cloud router is created
control "gcp-router" do
  impact 1.0
  title "Ensure compute router been created"

  describe google_compute_routers(project: gcp_project_id, region: "europe-west2") do
  its("names") { should include "ha-vpn-router1" }
  end
end

# Ensure DNS API is enabled
control "gcp-project-services" do
    impact 1.0
    title "Ensure project services are enabled"

    describe google_project_service(project: gcp_project_id, name: "dns.googleapis.com") do
    its{ should exist }
    its("state") { should cmp "ENABLED" }
    end
end

```

**Output:**

```jsx
SyntaxError: Unexpected token (6:1)
  4 | vpc_network    = input("vpc_network")
  5 |
> 6 | # Ensure GCP project exists
    | ^
  7 | control "gcp-project" do
  8 |     impact 1.0
  9 |     title "Ensure project exists"
```

**Expected behavior:**

**Comment by kachkaev** [comment]
👋 @nice-edox!

You can use [@prettier/plugin-ruby](https://github.com/prettier/plugin-ruby) to format Ruby code 🙂
