### ISSUE TITLE
Commented out code is moved to wrong place

### ISSUE THREAD

**Issue by simhnna** [prettier/prettier#14723]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAJhAMoQC2cMAFjlAOYAUqOATgM4wA0+7ckUQgEp8wADpR8+MTEjkARnTgAZAIbxOjANoSpe-XpYcYAOgDu6sNQCSMRkJMAHHI7iMDHg7s8+pAej98GFVHRgAPfABeAD58AXYIABs4E0SIJjChIW9fAyEuHN8+AUJzSxs7B2dXRkLc4NDwkRi46ATk1PSm7Mlc-Hy6vQBdHoBfEC4QCEdcNuRQVVZWCDMABUWEdmQQVUSLAE8tyflWVTAAayoSVUplJWRUXb5j04urxzO6emQYVnQ4SZwBRwQiEEFqBjoVT0OAAMQgrHI6lwDG2qnQMAgExA1Bg5ESAHVaBoPmA4CRNjhcAA3Kn7bZgdhHEB0PisGCrU70JEPJ4AkAAK3YYRIX2SAEV0BB4LzEs8QB8OHBWNt5Kp5HBEtjHKw6DACThCDRkAAOAAMkx1ED4BNOjm2OrgbOpcGxAEcpfBOdMtihVOwALRQOAgkHY1hwD1sOCc6E8pCPOX8vjkHA-P7JsVwACCMF+OHkGJjyruwdl8vYWcl0tdCb5k2C8gNRuoyAATA3TjhEl8AMIUeMgJ0AVmx6D4ABV1b7E-Lqf9rIIEDASGBdTNs4ISDB9sly3BRqMgA)

```sh
--parser babel
```

**Input:**

```jsx
function doSomething(first, second) {
  	combineLatest([
            first.watchIt().pipe(                
                  // tap(x => console.log(x))
                ),
            second.watchIt().pipe(
              tap((x) => console.log(x))
            ),
        ])
}
```

**Output:**

```jsx
function doSomething(first, second) {
  combineLatest([
    first
      .watchIt()
      .pipe
      // tap(x => console.log(x))
      (),
    second.watchIt().pipe(tap((x) => console.log(x))),
  ]);
}

```

**Expected behavior:**
Not to move the commented code out of the `pipe()` call.

```jsx
function doSomething(first, second) {
  combineLatest([
    first
      .watchIt()
      .pipe(
        // tap(x => console.log(x))
      ),
    second.watchIt().pipe(tap((x) => console.log(x))),
  ]);
}

```

**Comment by simhnna** [comment]
I guess it's not a priority issue, but it's a nuisance that you can't comment and uncomment to get valid code back

**Comment by kachkaev** [comment]
👋 @simhnna! Could you please scan through issues marked as [`area:comments`](https://github.com/prettier/prettier/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%3Acomments)? It is likely that your exact case is discussed in one of them. If you find a good match, feel free to close this issue as duplicate.

**Comment by simhnna** [comment]
* https://github.com/prettier/prettier/issues/10113 is simmilar, but the proposed fix, doesn't work in this case
* https://github.com/prettier/prettier/issues/11639 seems to be related not sure it's the same issue
* https://github.com/prettier/prettier/issues/9678 and https://github.com/prettier/prettier/issues/9192 seem to be this issue
