### ISSUE TITLE
Not letting keep multiple conditions on single line 

### ISSUE THREAD

**Issue by San1ay** [prettier/prettier#14730]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqCWAzVAKAHSgwzBgCcBPVAXjtQJEdQB8XUyrUA+VATgGsWREugAmmAG616jZmwbFRE6b0FsRogIZgwMmgyZoFOsADoANggDmMABaoAhPQDsQzSQAO5CGP2H5dm9fSxt7HgMARgAmD1QASlRgOPQcfE5qOgM5Y3YMnn4BRIkAZ08tGDA7PCqtKGs4ADEIcgBbABE4GC1MCzxgDjhyciRUCgBXOFQAX3j4gG50aZAAGhAITxhMaBLkUC1hiAB3AAUDhF2ULQsjrUpdtYAjch0Aay6AZS1WuAAZTCgcGQ2GuJTgTxeYHeMA+5TAAOsyAm4JAcFajzgYjEmN+dWs4y0DWabQqW3qyBAWnGMAgqxAdhgrQsAHU7Jh4GUdHAPhd2VJ2ZQKWASg8QACweQYCcXtZWlpgaCUQArEoADw+CKsAEVxhB4AqLGC1uVyBKKY8tBiLHTvACYMzMGJ7MgABwABmNPjBzJengp3jgEskQLWAEddfBpRtLpSSgBaQGYzF08hwcOYVPSwlyg1GkBg1qYJHkSZrEqauAAQRgFEwj2pcBOQ3+gNzKPL9W1EaBSBBhpR3UeDqddmQ0TWFB6FgRAGEIK0cyhAwBWOnjMEAFUtlz7eckkwAklBsbAPmByJhNpXjx8YJQrG3ptMgA)

```sh
--parser babel
```

**Input:**

```jsx
    if (
      ctry === "" || ctry > 999 ||
      div === "" || 
      div > 99 ||
      acc === "" || acc.length !== 7 ||
      prod === "" || prod.length >= 12
    ) {
      if (ctry === "" || ctry > 999) dispatch(changeFormDetail({ cerr: true }));  }
```

**Output:**

```jsx
if (
  ctry === "" ||
  ctry > 999 ||
  div === "" ||
  div > 99 ||
  acc === "" ||
  acc.length !== 7 ||
  prod === "" ||
  prod.length >= 12
) {
  if (ctry === "" || ctry > 999) dispatch(changeFormDetail({ cerr: true }));
}

```

**Expected behavior:**
**Output:**

```jsx
if (
  ctry === "" || ctry > 999 ||
  div === "" || div > 99 ||
  acc === "" ||  acc.length !== 7 ||
  prod === "" || prod.length >= 12
) {
  if (ctry === "" || ctry > 999) dispatch(changeFormDetail({ cerr: true }));
}

```

**Trying to keep multiple conditions on single line spanning specified width or desired no of conditions per line like two instead of single one**

**Comment by sosukesuzuki** [comment]
related: https://github.com/prettier/prettier/issues/187
