### ISSUE TITLE
Use `;` as separators in flow `ObjectTypeAnnotation`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#14734]
For the same code

```jsx
type Foo = {
  bar: boolean
}
```

with `parser: flow`, we format it as

```jsx
type Foo = {
  bar: boolean,
};
```

with `parser: typescript`, we format it as

```jsx
type Foo = {
  bar: boolean;
};
```

How about we change the separators to `;` in v3?

Interface separators discussion https://github.com/prettier/prettier/issues/2593

//cc @vjeux @mroch @gkz

**Comment by gkz** [comment]
In Flow the comma is definitely the preferred style for object types. It should mirror the syntax for object literals.

**Comment by fisker** [comment]
Okay, thank you.
