### ISSUE TITLE
Extend not formatting when under <pre> to other elements with a rule

### ISSUE THREAD

**Issue by VividLemon** [prettier/prettier#14738]
I am using Vue and building out some documentation. It came to the point where I needed to use `<code>` & `<pre>` to format this code correctly. 

As expected, prettier ignores it's formatting rules when under a `<pre>` tag. 

![image](https://user-images.githubusercontent.com/31498096/233793834-89f0b63b-2e89-4723-8947-63d67c9c13af.png)

![image](https://user-images.githubusercontent.com/31498096/233793842-1870493a-c327-48a6-b7e8-083d93a56300.png)

So far so good.

Since Vue, and other frameworks rely on "component" design, it would be beneficial for me to create a wrapper component to abstract out the details, and add props and things.

// CodeBlock.vue
```vue
<template>
  <code>
    <pre>
      <slot />
    </pre>
  </code>
</template>
```
So, we replace the above instances with:

![image](https://user-images.githubusercontent.com/31498096/233793915-da72e3da-ccab-4aa6-812e-95af06aec965.png)

And now you see the issue that I am seeking to prevent.

So, my proposal, create an option to extend the behavior in `<pre>` to other components. You can define other components which will ignore the formatting rules. This may already be implemented, but I am not seeing anything about it in the documentation, in addition, I see nothing about how a `<pre>` tag ignores formatting rules outright. I am not exactly sure how this could be applied to all frameworks. However, I believe if prettier automatically parses html, that it could parse any custom component that you apply. 

Lmk opinions

**Comment by sosukesuzuki** [comment]
Can you follow the issue template?
