### ISSUE TITLE
How can the format of the chain call be consistent?

### ISSUE THREAD

**Issue by seekcx** [prettier/prettier#14733]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAHSgHwLQGFHEmlnkWVnY4AEAShAK7wDONVnX3PRNNtACoALAJataAM1EAbOLXG0AJnCWiwAQ3hKpEAE7K40qKKgBzWgAlBggAq09zNgDpaAQVqtTZuVNnzFBGYzYQFJfVoAWw0AK31RGABPWghJWgAHRxi4MBhWABpaYQgAdzgANzgDROZaTShDY3lHFjgJU2VRSUkqhBgw-wkNKB0YplYYKI0Aa3lWJj15GAgFSPT9SZhhOEiFKC8VWi3FaTlXADEIuAAPDTW5fih0VGxsUTWNhid5SUddgHIAAKiCBgJBuJTQcSoADC+jgqEYrX+rygSPg2FoWNoznSLAAFP9UOMqqgZKCtCCoHgNAAjMD-Qr-ACqrCqcNgjhkcj0ziY6SUWjgABkKTAqf8AJSY7HOSKiJRKOQlDSLQkaFjCKUyrHOKB3OCEtgwbUNWjYdFwXEEokkvRksVUmn0xkstn22yOU5wDkwLk8vkCoWizTi6Cm7E4+WK5Wqw3-DVbCPmtHfHU4vEwQnE90O0NOukMpms9nQP0QblVQOC+Ahynh6Vm3XRpVwFVqhOaqUgfIgCDpMP7ZCgVWOEq2ONDlAacoQBU9kC0vQaMCzGAAZQNwtMcGQkg0MjZvaXK7X6-SK+8yD9TDgvZ2tNUKiUwuGZiYGjMcEuemiMHF5jICAiYQAuwgwJEMgAOpiGwF5gHA64IF44rlAkiRAWArCsAupjujAnqftEe4HkeIAxKw1zrt4cgAIpMBA8AkYed4gBeejukBtJ0nAMgLpkpgwFBCpbMgAAcAAMvaZBAbJQcu6RAZkbRVJUC4AI4MfAnr9jh06sHgUBwKoqgLosmmiIshFmMRSD7ixvZsvK156Lejk0XAbj-nooi0q0thVNuRnMWRXjmHRWm7kgN6sTAdLCUoolIAATL2foaLI3hwpEtkgG0ACsC4koIdJ6fZZHlLeACSIx9OuYA+QObgjOuSRyCFcAAL6dUAA)

**Input:**

```jsx
Route
    .put('/user/location-abc', 'UserController.updateLocation')
    .middleware('auth')
    .name('test')
  
Route.put('/user/location-abc','User/ProfileController.updateLocation')
    .middleware('auth')
  
Route
    .put('/user/location-abc', 'UserController.updateLocation')
    .middleware('auth')
```

**Output:**

```jsx
Route.put('/user/location-abc', 'UserController.updateLocation')
  .middleware('auth')
  .name('test');

Route.put(
  '/user/location-abc',
  'User/ProfileController.updateLocation'
).middleware('auth');

Route.put('/user/location-abc', 'UserController.updateLocation').middleware(
  'auth'
);
```

**Expected behavior:**

```jsx
Route
  .put('/user/location-abc', 'UserController.updateLocation')
  .middleware('auth')
  .name('test')
  
Route
  .put('/user/location-abc', 'User/ProfileController.updateLocation')
  .middleware('auth')
  
Route
  .put('/user/location-abc', 'UserController.updateLocation')
  .middleware('auth')
```

OR

```jsx
Route.put('/user/location-abc', 'UserController.updateLocation')
  .middleware('auth')
  .name('test')
  
Route.put('/user/location-abc', 'User/ProfileController.updateLocation')
  .middleware('auth')
  
Route.put('/user/location-abc', 'UserController.updateLocation')
  .middleware('auth')
```

**Comment by seiyab** [comment]
Answering "how", using a comment might help you as a workaround:
```js
Route
  // Hey prettier, would you break here, please?
  .put('/user/location-abc','User/ProfileController.updateLocation')
  .middleware('auth')
```

But probably, you want prettier to format as you suggested without workaround.
I agree that outputs you expect look better and want prettier to get better heuristic.

(Though I'm interested in it, I don't intend to work on it as of now. Go ahead if someone want to work on it.)

**Comment by seiyab** [comment]
Oops, probably duplicated? https://github.com/prettier/prettier/issues/14628

**Comment by seekcx** [comment]
Showing the method in several lines is ugly and I don't understand why the expected behavior is this way. And for different situations, it seems that there are different formatting strategies. If they can be consistent, it will seem easier to understand.

**Comment by seekcx** [comment]
> Oops, probably duplicated? #14628

Yes, I confirmed the duplicate, close this first.
