### ISSUE TITLE
Comment moved to end of previous line when non-ASCII character appears earlier in the file

### ISSUE THREAD

**Issue by keithkml** [prettier/prettier#1474]
This is a weird one!

Code:
```js
function good() {
  this.property = true;
  // This comment stays put on its own line
  return 0;
}
v = '•';
function bad() {
  this.property = true;
  // This comment gets placed on previous line
  return 0;
}
```

Delete that "v =" line, or just change the dot to the letter "a" and you'll see what I mean. The Prettier output is:

```js
function good() {
  this.property = true;
  // This comment stays put on its own line
  return 0;
}
v = '•';
function bad() {
  this.property = true; // This comment gets placed on previous line
  return 0;
}
```

**Comment by vjeux** [comment]
This is a known issue and has been fixed in master. It's going to be fixed during the next release (hopefully today or tomorrow). Sorry about that.

In the meantime, you can use `babylon` parser which doesn't have this issue.
