### ISSUE TITLE
Separate configuration options for scripts and templates for Vue SFC

### ISSUE THREAD

**Issue by Kobzol** [prettier/prettier#14755]
Is it possible to use different styling options for `<script>` and `<template>` tags in Vue SFC components? I would like to have `tabWidth: 2` for Vue templates, but `tabWidth: 4` for Vue scripts. Basically I would like to use an override based not on the file extension, but on the custom blocks within the (Vue SFC) file.

**Comment by sosukesuzuki** [comment]
Sorry, we will not support it.
