### ISSUE TITLE
`Error: astFormat is required` in 3.0.0-alpha.10 when using a plugin

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#14753]
**Environments:**

- Prettier Version: 3.0.0-alpha.10
- Running Prettier via: CLI
- Runtime: Node 18
- Operating System: macOS
- Prettier plugins (if any): [prettier-plugin-packagejson](https://github.com/matzkoh/prettier-plugin-packagejson)

**Steps to reproduce:**

https://github.com/kachkaev/njt/pull/314

This project uses Yarn PnP, but I've been able to reproduce the error in another closed-source project with `pnpm`

**Expected behavior:**

Formatting as in `3.0.0-alpha.6` (does not crash when processing `package.json` files which are covered by the plugin)

**Actual behavior:**

```
Error:  package.json: Error: astFormat is required.
Error:      at getPrinterPluginByAstFormat (file:///home/runner/.yarn/berry/cache/prettier-npm-3.0.0-alpha.10-e157831324-9.zip/node_modules/prettier/index.mjs:16923:11)
Error:      at normalizeFormatOptions (file:///home/runner/.yarn/berry/cache/prettier-npm-3.0.0-alpha.10-e157831324-9.zip/node_modules/prettier/index.mjs:16994:113)
Error:      at async formatWithCursor (file:///home/runner/.yarn/berry/cache/prettier-npm-3.0.0-alpha.10-e157831324-9.zip/node_modules/prettier/index.mjs:18591:46)
```

**Comment by fisker** [comment]
https://github.com/matzkoh/prettier-plugin-packagejson/blob/f7f6bb594829506f886f1e8225882dd444831527/lib/index.js#L9

`pluginBabel["json-stringify"]` no longer a object, it's a function need to be called to lazy evaluate parser.

I'll think about it to see if we can make it simpler for such use case.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/blob/9cd2b62314f1199a0366d211fba84b4d7816b685/src/main/parser-and-printer.js#L64-L69


Mentioned in changelog, but outdated https://github.com/prettier/prettier/blob/main/changelog_unreleased/api/13268.md

**Comment by kachkaev** [comment]
I see! I created https://github.com/matzkoh/prettier-plugin-packagejson/issues/80 in case if you don’t want to 'fix' this on the Prettier's end. We can close this issue and remove the milestone if you think that this is the way to go. Otherwise, we can close https://github.com/matzkoh/prettier-plugin-packagejson/issues/80.
