### ISSUE TITLE
My prettier extensions takes 10 minute of time only for formating one line code, LOL

### ISSUE THREAD

**Issue by Sisableng** [prettier/prettier#14762]
prettier from now takes a long time to format code even its update only one line, why? how to fix this?
also i try to disable another extensions, but it still to slow,

here is my extensions list :

- Auto rename tag
- dracula official
- es7+, react/redux/react-native snippet
- html css support
- laravel blade formater
- laravel blade snippet
- laravel goto view
- laravel snippet
- live preview
- livewire language support
- php debug
- php intelephense
- php intellisense
- postcss language support
- postgresql
- prettier code formatter
- sftp
- simple react snippet
- tailwind css intellisense
- thunder client
- vscode-icons

**Comment by kachkaev** [comment]
Please follow the issue template and share reproduction steps
