### ISSUE TITLE
Format error if has '/ ', 

### ISSUE THREAD

**Issue by beiying36** [prettier/prettier#14760]
I set rule is singlequote 
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEc1gIYAOcAsoZgLybAA6Um9DA5AGSNKYt4C2BA3IwBpaDJgB42HZgBsY-IXREcAfBJYBzWYOGLG1ao1XMAxAGYAnHO0jdIQwEcArhE1XMAX160vC+pCgZsXEISMkoaHyZmbj5DLQj6Fhl+dkZxeUVJDWTlOIyWUwtVPQN0nWZHZ2ybXIY3EAEQCAIYAEt0ZFA8ACcuiAB3AAVuhDRkEDwpPrwAT1GGgCMuvDAAazgYAGVuOAAZFqg4ZAAzCbQ4BaXV9Y2CZf21ZBguh3OQOC55uAATL++dvCgagceDUcAAYhAulw8DBWoCxngHDAIPUQAALGBcKQAdTRLXgaFuYDgGxG+JaADd8dMxmA0HMQPszl0YAMlmpocdTq8AFZoAAeG3uUjgAEUnPAuVIzg1bl1mWN5nhPlJUQQuvsYNiWl8YGjkAAOAAMst6Z2xSwIY3VODgXQphwaFXgbKaoxQeDQAFoDt9vqiunBHC1A2yQZykCdpa8zlwWo9njHhXAAIKwjXzJFwAZ2vYHKUykBoZPi5yHJBPF4NGDK7W6-VIABM1aWLSk9wAwhAuBG3mgAKyohxnAAqyvdUcLFJeAEkoL9YBswBrmin5xsYNMRQW4G43EA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```js
const escapeMap = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '\'': '&#39;',
      '"': '&quot;'
    };


    const escapeMap = {
      '&amp;': '&',
      '&lt;': '<',
      '&gt;': '>',
      '&#39;': '\'',
      '&quot;': '"',
    }
```

**Output:**

```js
const escapeMap = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  "'": '&#39;',
  '"': '&quot;',
};

const escapeMap = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&#39;': "'",
  '&quot;': '"',
};

```

**Expected behavior:**

```js
const escapeMap = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '\'': '&#39;',
  '"': '&quot;',
};

const escapeMap = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&#39;': '\'',
  '&quot;': '"',
};

```

**Comment by fisker** [comment]
This is expected, `'\'' === "'"`.

**Comment by so1ve** [comment]
Is there a way to keep quotes consistent? I know prettier will convert escaped-quotes by changing the outer quotes, so just a question.

Like `'\''` is changed to `"'"`. Can we keep it? Does it violate prettier's philosophy?

**Comment by fisker** [comment]
> Is there a way to keep quotes consistent? 

No.

> Does it violate prettier's philosophy?

The ASTs are the same, if you mean this.
