### ISSUE TITLE
Standalone version isn't loaded with ESM and Webpack

### ISSUE THREAD

**Issue by berekuk** [prettier/prettier#14765]
**Environments:**

- Prettier Version: 3.0 alpha
- Running Prettier via: Browser API
- Prettier plugins (if any): 

**Steps to reproduce:**

- import `prettier` in ESM-only React code (`"type": "module"`, and Typescript in my case, but I'm not sure that's relevant)
- try to bundle it with webpack 5

**Expected behavior:**

Bundle is built.

**Actual behavior:**

Multiple errors of this type:

```
ERROR in ../../node_modules/prettier/index.mjs 1:0-66
Module not found: Error: Can't resolve 'module' in '/Users/berekuk/coding/quri/squiggle/node_modules/prettier'
 @ ./src/components/CodeEditor.tsx 11:0-37 41:50-75
 @ ./src/components/SquiggleEditor.tsx 5:0-45 20:32-42
 @ ./src/index.ts 4:0-64 4:0-64
```

This could be solved with `prettier: "prettier/standalone"` in webpack's `resolve.alias` field, but that's a solution only for the current package; I have multiple apps that use the same components package, and I don't want to impose this requirement on all consumers of my package.

Importing `prettier/standalone` directly in the React code doesn't help either because I depend on the custom prettier plugin that imports `prettier` instead of `prettier/standalone`.

I think that adding `"browser": "./standalone.mjs"` to `exports["."]` field in `package.json` will fix this. I'm less sure if it would cause any problems for CJS builds.

**Comment by fisker** [comment]
My suggestion is use

> This could be solved with prettier: "prettier/standalone" in webpack's resolve.alias field

I don't think there are much we can do.

> adding "browser": "./standalone.mjs" to exports["."] field

Are you sure about this? We already have it pointing to the UMD version, if webpack uses this field, why error from `index.mjs`?

**Comment by alexander-akait** [comment]
Due to this https://github.com/prettier/prettier/blob/main/package.json#L15, when a package has `exports` bundler should load files only from `exports`

**Comment by berekuk** [comment]
> Are you sure about this? We already have it pointing to the UMD version, if webpack uses this field, why error from index.mjs?

I'm not sure, but changing it manually helped the build of the components package, at least. Then it broke when I tried to use it in docusaurus, but docusaurus is big and complicated and I don't know what exactly happened there.

Alternatively: is it safe to depend on `prettier/standalone` in the plugin's implementation? Would it cause problems?

One problem with that is that `prettier/standalone` doesn't expose type definitions that are necessary to implement the plugin, but I think that's `standalone.d.ts` fault, the actual exports are there.

**Comment by alexander-akait** [comment]
@fisker It is not safe to use "default" platform dependent code. It will not work for example for deno (and not only), if we have `module` module, we need to use the `"node"` key. 

> I think that adding "browser": "./standalone.mjs" to exports["."] field in package.json will fix this. I'm less sure if it would cause any problems for CJS builds.

It is a good solution

**Comment by fisker** [comment]
> is it safe to depend on prettier/standalone in the plugin's implementation?

I'd suggest plugin to have separate standard entry and use `"my-plugin/standalone"`.

What feature the plugin need from prettier? If `prettier.doc`, plugin can also use `prettier/doc` entry.

> One problem with that is that prettier/standalone doesn't expose type definitions 

That should work, if it's not, we should fix it.

**Comment by berekuk** [comment]
> I'd suggest plugin to have separate standard entry and use "my-plugin/standalone".

Nice, thanks! That should help.

Still, it'd be better it things worked out of the box, so I submitted #14766.

> What feature the plugin need from prettier? If prettier.doc, plugin can also use prettier/doc entry.

`doc` and `util`.

**Comment by fisker** [comment]
> @fisker It is not safe to use "default" platform dependent code. It will not work for example for deno (and not only), if we have `module` module, we need to use the `"node"` key.

What do you suggest to change?

**Comment by alexander-akait** [comment]
@fisker Which of our files does not contain platform dependent code? It should be in `default`, `default` should work everthing, except of course things we don't officially support.

Also pseudo exports is good too https://github.com/prettier/prettier/pull/14766#discussion_r1178532190 

i.e.

we can support specific platform using (just pseudo example):
```
import prettier from "prettier/browser";
import pretter from "prettier/deno";
import prettier from "prettier/webworker":
```

But to be honest I think bundling non platform dependent code and using ESM is the best solution.
