### ISSUE TITLE
Bug report: using `// prettier-ignore` on a call signature line leads to broken code on format

### ISSUE THREAD

**Issue by nvie** [prettier/prettier#14786]
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYhCbAXm2AB0ptsAKASiWwDcIBLAEwG5sB6b7DAE5wYMFnAEBaFgHMoEIRSoBnOJChsGSmAJZRpHCgF8DUEABoQEDKOhLkoAIYCBEAO4AFJwjsoHAG1cHNDsLACMBBzAAa2EAZQcAWzgAGV04ZAAzfxUwiOi4jEjdaWRtAFc4CzgE0Lg2Njrkhz0yh2k4fAEEhxFi5BAHMpgIcxAACxgEvwB1MZZ4JUKwOFjveZZGebR+sCUQkF0VARh3COluzOzKkAArJQAPWOK-OABFMoh4S78ckEKBI79dBYJRgHTWUaCXQwabsGBjZAADgADBZBBAVNMIhh+oI4EdGOkLABHD7wU5WHwDJQSKBwOp1UZCUksISnNoXJBZH7XFQJFilAQVCxKZ5wACCIh0oSGcHc4lSdO+v1Fehe70+6S5VwsMAcoVhbHhyAATLqIiw-MUAMIQBKckD4gCsozKKgAKvqfNzfowKgBJdQIGCxMEsazi9SxdAvZVwQyGIA)

```sh
--parser typescript
```

**Input:**

```tsx
type Foo = {
  (): void; // prettier-ignore
  second: string;
};
```

This is for the `typescript` parser only, the `babel` parser seems unaffected.

Key parts to reproduce:

1. Create a type definition (or an interface type, it has the same bug);
2. Add a call signature property (e.g. the `(): void` part in the linked playground), and `prettier-ignore` that line;
3. Add another property below it. The bug does not occur if the call signature is the last property in the type.

**Output:**

```tsx
type Foo = {
  (): void;; // prettier-ignore
  second: string;
};
```

Due to the `;;` part, the code actually breaks and becomes invalid TypeScript on save.

**Expected behavior:**

The output contains no double semicolon, i.e. the `;;` part.

**Comment by ot07** [comment]
Hello, I don't have prior experience contributing to this project, but I would like to work on this issue as a good first issue.

If I find a solution, I plan to submit a pull request.
