### ISSUE TITLE
Time increases with the nesting level

### ISSUE THREAD

**Issue by martinschayna** [prettier/prettier#1478]
Prettifying of the following example with 13 nesting levels takes about two seconds. Adding more levels doubles this time, for more than 16 levels is prettier unusable. :cry: 

```
function test(obj) {
  return read(1, obj).chain(a =>
    read(2, a).chain(b =>
    read(3, b).chain(c =>
    read(4, c).chain(d =>
    read(5, d).chain(e =>
    read(6, e).chain(f =>
    read(7, f).chain(g =>
    read(8, g).chain(h =>
    read(9, h).chain(i =>
    read(10, i).chain(j =>
    read(11, j).chain(k =>
    read(12, k).chain(l =>
    read(13, l).chain(m =>
    read(14, m).chain(n =>
    create(n)
  ))))))))))))));
}
```

This is a regression, version 0.22.0 works well.

**Comment by martinschayna** [comment]
prettier 1.2.2 for 14 levels lasts for 4 seconds, for 15 levels 8 seconds etc.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20test(obj)%20%7B%5Cn%20%20return%20read(1%2C%20obj).chain(a%20%3D%3E%5Cn%20%20%20%20read(2%2C%20a).chain(b%20%3D%3E%5Cn%20%20%20%20read(3%2C%20b).chain(c%20%3D%3E%5Cn%20%20%20%20read(4%2C%20c).chain(d%20%3D%3E%5Cn%20%20%20%20read(5%2C%20d).chain(e%20%3D%3E%5Cn%20%20%20%20read(6%2C%20e).chain(f%20%3D%3E%5Cn%20%20%20%20read(7%2C%20f).chain(g%20%3D%3E%5Cn%20%20%20%20read(8%2C%20g).chain(h%20%3D%3E%5Cn%20%20%20%20read(9%2C%20h).chain(i%20%3D%3E%5Cn%20%20%20%20read(10%2C%20i).chain(j%20%3D%3E%5Cn%20%20%20%20read(11%2C%20j).chain(k%20%3D%3E%5Cn%20%20%20%20read(12%2C%20k).chain(l%20%3D%3E%5Cn%20%20%20%20read(13%2C%20l).chain(m%20%3D%3E%5Cn%20%20%20%20read(14%2C%20m).chain(n%20%3D%3E%5Cn%20%20%20%20create(n)%5Cn%20%20))))))))))))))%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Sorry about this, it's a known regression ( https://github.com/prettier/prettier/issues/1250#issuecomment-294297600 ) but I don't know of an easy way to fix it.

In the meantime, you can add `// prettier-ignore` at the beginning of that big expression. It's not going to pretty-print it, but at least it's going to be fast.

**Comment by martinschayna** [comment]
Thanks, that helps. You can close this issue due to duplicity. Good luck with #1250 :four_leaf_clover:

**Comment by vjeux** [comment]
Going to close it in order to consolidate with https://github.com/prettier/prettier/issues/1250
