### ISSUE TITLE
Feature Request: Add `spaceAfterFuncName` in .prettierrc

### ISSUE THREAD

**Issue by hvlxh** [prettier/prettier#14790]
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAllSAnPOMGAHSgDMBXXGLaDKAQwFs4AKASg2DIw0JiU8UDAHIAchFFkAvmTLoM+QsTJUadEU1YZO3XvziDhYydKgyQAGhAQADrWgBnZKEYEIAdwAK7hC5RGABtPRgBPFxsAIzxGMABrIwBlFjgAGRw4ZHJgpzho2ITkuzicAHNkGDxKfJA4Zii4ABMm5rTGKDLKRjK4ADEIPGZGGFpO5BBGShgIaxAACxhmIIB1eax4JxKwOCT-DawANw2wibAnSJAcPLwYb1iy4ezc2oArJwAPJPKguABFSgQeDPIJ5GwlPA3CYwMJ2OBOMB4LAOOZ2JGwFZYJowebIAAcAAZwXgIHkVrE7BM0fC4HhDlkbABHQHwe72AKTJwAWigcGazTmhGZWEI9x6TyQOVBtTyzCwlWqMp+cAAgqMkVFpnBvLSMryQWCQE5lQCgVlJS8bDBGFFMdjcUgAExW2JYILlADCEGYErqTgArHNKHkACo2gJSw2HGoASSgrVgSURyJgKvjSRhvwNcBkMiAA)
![image](https://user-images.githubusercontent.com/91016099/235978215-4b0bfffe-c083-47ac-a801-b889dbeebb78.png)

By using standard codestyle, there should be an space after an function name. Look at the playground i sent at up. I am requesting an option in .pretterrc called `spaceAfterFuncName` or other aliases that fix that issue

**Comment by kachkaev** [comment]
👋 @hvlxh! Please see

- https://prettier.io/docs/en/option-philosophy.html
- https://prettier.io/docs/en/comparison.html
- https://prettier.io/docs/en/related-projects.html

If you want to disable ESLint rules that conflict with Prettier, you can add [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) as a dependency and mention it in you ESLint config.
