### ISSUE TITLE
Regression in v3 (2)

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#14809]
**Prettier pr-14803**
[Playground link](https://deploy-preview-14803--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEACAhqgvK4AdKVIgB3QCcBnOAMQFcowYBLaAIQgBMBPAQSg+pMoTCgAsAPASJEAKqjgAPePwpTp6gD6oAcgDo6DZtDXqiWvTIDKAEThgANuTgBZODFGcTp87qu2HTgaMLFBemjq6AMKOFBQACmRMAG7o8K7unAA0agB8ABQAlLhqAL5SJSCZIBDERlAUyKDkZBAA7nFO9cgg6Pat6FwNVQBGZOhgANZulugAtnAAMkJwyABmvVQjY5PTpGBCAObIMGS0cFVUs0zHp+cgFIf2cACKtBDwaxt3AFYUCpaPF5vD5Idb2TYgACOwLgCRqDRQ6AoAFooHA4BwMZUQCd0Ex7IdIhBZrN0N1evZsQ8oAcnjwYCcmMNaPA4nAyEs0Z9wXdRDBZvYAOqiJjwCh7OCWBAPZhJUVcbpgWLYpJnACS-AQMEsYEStT4HEsMC4T25EOILSogrGxG6FrgVDISRWVSEjpgCXQB1JZrupEo7O6xuIDt1TFq2ItQhggqYHHcyAAHAAGKpkODQpjpz3esmgr5VGDoYax+OiZAAJiqtCoMmLCLBELgs2GGMxHAW6BptC9NAgZFJDMO5JZEBAJRKQA)

```sh
--parser typescript
```

**Input:**

```tsx
 a = {
   parseFunctionBodyAndFinish<
    T extends
        | N.Function
        | N.TSDeclareMethod
        | N.TSDeclareFunction
        | N.ClassPrivateMethod,
  >() {
  }
 }
```

**Output:** (extra new line added after `extends`)

```tsx
a = {
  parseFunctionBodyAndFinish<
    T extends

        | N.Function
        | N.TSDeclareMethod
        | N.TSDeclareFunction
        | N.ClassPrivateMethod,
  >() {},
};

```

**Expected behavior:**

(V2 output should be preferred)

```tsx
a = {
  parseFunctionBodyAndFinish<
    T extends
      | N.Function
      | N.TSDeclareMethod
      | N.TSDeclareFunction
      | N.ClassPrivateMethod
  >() {},
};
```

Maybe the same problem as #14808

https://github.com/babel/babel/pull/15617/files#r1187671748

**Comment by fisker** [comment]
@sosukesuzuki Should caused by #14672, can you take a look?

**Comment by sosukesuzuki** [comment]
Yes
