### ISSUE TITLE
Wrong cursorOffset with multi-line comment

### ISSUE THREAD

**Issue by hyrious** [prettier/prettier#14811]
**Environments:**

- Prettier Version: 2.8.8
- Running Prettier via: Node.js API
- Runtime: Node.js 18.16.0
- Operating System: macOS
- Prettier plugins (if any): 

**Steps to reproduce:**

Save this script and run it:

```js
import prettier from "prettier";

const code = `
// All messages are represented in JSON.
// So, the prettierd.py controls a subprocess which spawns "node {this_file}".
import {  } from "fs"
`; //   ^ cursor here

console.log(
  prettier.formatWithCursor(code, {
    cursorOffset: 129,
    parser: "babel",
  })
); // => { cursorOffset: 65 }
```

**Expected behavior:**

Expect the returned `cursorOffset` to be around 129, right in the `{}`.

**Actual behavior:**

It returns 65, which is in the comments.

Frankly, I don't even find a minimal case to reproduce this issue (the code above is all I could make, changing any line of the comment may make the result correct).

**Comment by kachkaev** [comment]
Please use the [issue template](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE). Prettier Playground supports ranges if this is what you are trying to show:

<img width="215" alt="Screenshot 2023-05-10 at 08 43 51" src="https://github.com/prettier/prettier/assets/608862/bdff3abf-652d-41ff-af00-784a22c55217">

**Comment by fisker** [comment]
@hyrious 

The cursor tracking does not always return the expected position, I feel lots of problems in this part. 
#14812 may fix your case.

Do you have more test cases?

**Comment by fisker** [comment]
> the code above is all I could make, changing any line of the comment may make the result correct

Your right about this, this is strange. I can't change the code either.

<details>
<summary>My script to test</summary>

```js
import * as mainPrettier from "./index.js";
import stablePrettier from "./node_modules/prettier/index.js";

const code = `
// All messages are represented in JSON.
// So, the prettierd.py controls a subprocess which spawns "node {this_file}".
import {<|>  } from "fs"
`;

const cursorOffset = code.indexOf("<|>");
const codeToFormat = code.replace("<|>", "");

console.table([
  {
    prettier: mainPrettier.version,
    originalCursorOffset: cursorOffset,
    cursorOffset: (
      await mainPrettier.formatWithCursor(codeToFormat, {
        cursorOffset,
        parser: "babel",
      })
    ).cursorOffset,
  },
  {
    prettier: stablePrettier.version,
    originalCursorOffset: cursorOffset,
    cursorOffset: (
      await stablePrettier.formatWithCursor(codeToFormat, {
        cursorOffset,
        parser: "babel",
      })
    ).cursorOffset,
  },
]);

```

</details>

**Comment by fisker** [comment]
Smaller reproduction

```
// All m are represented in JSON.
// So, the prettierd.py controls a subprocess which spawns "node {this_file}".
import {<|>  } from "fs"
```

Change the first `m` letter in first line to `a`, generates different result.

**Comment by fisker** [comment]
Raised an issue https://github.com/kpdecker/jsdiff/issues/400

**Comment by fisker** [comment]
Shortest string I can find

```js
import { diffArrays } from "diff";

const code = `
// m represent o, 1 represent 1 1 {}
import {} from "fs";
`.trim();

function diff(string) {
  return diffArrays([...'import {  } from "fs";'], [...string]);
}

console.log([
  diff(code),
  diff(code.replace("o", "a")),
  diff(code.replace("m", "a")),
]);
```

**Comment by so1ve** [comment]
jsdiff is almost... dead? I think the project has been abandoned by its author and this bug may not be fixed in a while.

**Comment by fisker** [comment]
I know that. My PR has been there for over a year https://github.com/kpdecker/jsdiff/pull/351

Anyway, https://github.com/prettier/prettier/pull/14812 will fix your issue, so not that important.
