### ISSUE TITLE
Syntax error for flow code

### ISSUE THREAD

**Issue by philipp-spiess** [prettier/prettier#1481]
The following code: 

```js
class Foo {
  constructor: () => this;
}
```

will throw a SyntaxError in the `babylon` parser but will work fine in the `flow` parser:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Foo%20%7B%5Cn%20%20constructor%3A%20()%20%3D%3E%20this%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
I actually have no idea which parser is right! I'm asking around. Thanks for the report!

**Comment by philipp-spiess** [comment]
@vjeux We use this as a hacky way to overwrite and "fix" the wrong flow types for Immutable.Record classes. Not pretty but it works w/ flow :)

**Comment by vjeux** [comment]
That's great context, could you open up an issue on the babylon repository? Once it is fixed there, we can update our dependency and it's going to work for prettier :)

**Comment by philipp-spiess** [comment]
Thank you @vjeux. I've filed an issue [here](https://github.com/babel/babylon/issues/508). I'll update the issue here if something changes. 👌

**Comment by existentialism** [comment]
Just FYI, landed a [fix for this](https://github.com/babel/babylon/pull/510) in Babylon!
