### ISSUE TITLE
Regression in v3 (3)

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#14810]
**Prettier pr-14803**
[Playground link](https://deploy-preview-14803--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEACdH0HMA2EBGAhjgCoQCCAzpQJZZSoC8qAtnC-nAE6UB0lOGmDgAKAIwBKXlzgATAK7CRIwmDDyWAGlTquXCUwB8qYAB0GmSzJjyuDGLzYduAUQAeABxnUa0FWo1tBxpZBBgaADMabhFdfQkAbnNLDABfIMd2Ti53LzgfP2DQ2EjorhFTEFwCYkqJDJCw0pinbMoAbQAGAF0JPoSQTRAID3DoSmRQQj0IAHcABWmECZRiWcIATwmh-C5VAGs4GABlQjYAGRooOGQI4ko4Hb2wQ5OPVSusZBgueUeQB4sGjfX7-WhQXBwACK8gg8Fu93+ACtKG5jp8cNDYfCkHccA8hgBHbFweZcEYrECESgAWmucjkgxAP0INEEEIAwhAWCxCMgqTgcEzwZDyDAfjR8PJ4PNuJdrgj8f8ABYwFg4ADqypo8Eo72Ex2WOpoADcdRt+WBqEyTX8AJJQYonMBcGijciO44wDaYxUEkBeCAPDV7Dz8vIPLgmm5DK6RmBkwhYXl+-7vHjcfnejz5F1umBMrxXGAakIwZXIAAcnSGMmJNBkieTfNxiKGMEI+FLsnLyAATEN5A8SJ2Vnj-Vk5KFZOdCBD5Em4AAxCBcXniz78wjSiAgVKpIA)

```sh
--parser typescript
```

**Input:**

```tsx
        globalToAssign = members.slice(1).reduce((accum, curr) => {
          return t.memberExpression(accum, t.identifier(curr));
        }, t.memberExpression(t.identifier("global"), t.identifier(members[0])));
```

**Output:**

```tsx
globalToAssign = members.slice(1).reduce(
  (accum, curr) => {
    return t.memberExpression(accum, t.identifier(curr));
  },
  t.memberExpression(t.identifier("global"), t.identifier(members[0])),
);

```

**Expected behavior:**

Found in babel codebase. Not sure which PR changed it, need investigation.
https://github.com/babel/babel/pull/15617#discussion_r1188040925

**Comment by fisker** [comment]
Possible changed by #13341, maybe expected?

**Comment by fisker** [comment]
Yes, #13341 is the one https://github.com/prettier/prettier-regression-testing/issues/41#issuecomment-1228638631

**Comment by so1ve** [comment]
Isn't the output much clearer?

**Comment by fisker** [comment]
Yes, agree. But we forgot which one changed it, so I opened an issue.

**Comment by fisker** [comment]
Closing.
