### ISSUE TITLE
Flow parser fails to preserve whitespace in `--debug-check` for no-semi conversion

### ISSUE THREAD

**Issue by philipp-spiess** [prettier/prettier#1482]
Given the following example:

```jsx
export default class Test {
  foo: 'foo';

  render() {
    return null
  }
}
```

And the following command:

```
prettier --no-semi --debug-check test.js
```

The result will work as expected. However, when you change the parser to `flow`:

```
prettier --no-semi --parser flow --debug-check test.js
```

The whitespace can no longer be preserved:

```diff
test.jsIndex:
===================================================================
---
+++
@@ -1,7 +1,6 @@
 export default class Test {
   foo: "foo"
-
   render() {
     return null
   }
 }

```

**Comment by vjeux** [comment]
Thanks for the report! This actually got fixed by upgrading flow to the latest version ( https://github.com/prettier/prettier/pull/1447 ). I'll do a release today with the fix.
