### ISSUE TITLE
GraphQL template tags whitespace no longer respected.

### ISSUE THREAD

**Issue by pieterv** [prettier/prettier#14837]
When testing prettier v3 on the Meta codebases this behavior change is by far the most common, the graphql tag will always be "inlined" into the call expression if its the only argument. In prettier v2 it would not be "inlined" if a user had added a newline. I personally prefer the consistency of the new v3 behavior and happy if that's the intended state but i wanted to check as i couldn't find a changelog entry for it and it will make our prettier v3 rollout harder (but still not a problem).

**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U++ATnDOvbegM5wCy6MAhrmgkadOgHN6fAA4ALAI4AbAAYjRAW14C8tPuwAm5SgF9VK2vjIBuGiag0MWQbSKkK1c42at8HbpqckEtLyyqp0GvxO+LoGbrZ0ZnRWNjQgADQgEFJO7MigfPT0EADuAAoFCLkofArFfACeuRkARpJgANZMAMp8anAAMjhQcMioNZwtbZ0wXVJ8YENiyDD06HAZcGrNcHp6O-18UGLofGJwAGIQ9GoCuEfIIHy8EOkgMjBqCgDqMjjw7HMwHAupU-jgAG5-eoPMDsJogIacegwUqSMQ3UbjdYgABW7AAHl1Fgo4ABFdAQeCYhQTEBzehIh6oBQlV5SehDGBfHB6GAyZAADgADBl2RBOF9JFIHuy4EjwSMMnIKfBUVkqo92ABaYY7HavRjKnCMVGnDFIMY07GcNQ4Zara3EuAAQRgKxwzV4cFKcHog2G1Np7Cd5MpIwtWIy-Ga3N5-KQACYo5IcApFgBhCBqc0gOUAVlevgAKnxmlVLbTwWsAJJQPawLpgDnZZ11roweokwNwIxGIA)

**Input:**

```jsx
function foo() {
  useMutation(
    graphql`
      mutation FooMutation {
        foo
      }
    `
  );
}

```

**Output: Stable**

```jsx
function foo() {
  useMutation(
    graphql`
      mutation FooMutation {
        foo
      }
    `
  );
}

```

**Output: Main**

```jsx
function foo() {
  useMutation(graphql`
    mutation FooMutation {
      foo
    }
  `);
}
```

**Comment by sosukesuzuki** [comment]
This feedback is greatly appreciated. 

When I formatted this code with the current main branch code, I could not reproduce it.

```console
$ cat test.js
function foo() {
  return useMutation(
    graphql`
      mutation asd() {}
    `
  );
}

$ ./bin/prettier.js  test.js --ignore-path=.prettierignore 
function foo() {
  return useMutation(
    graphql`
      mutation asd() {}
    `,
  );
}
```

Which Prettier did you run?

**Comment by pieterv** [comment]
Oh weird, I used the latest alpha, 11 I think. We have a custom parser setup so maybe we could be messing up the location position. Ill have another look into it tomorrow to make sure I can repro with all parsers.

**Comment by pieterv** [comment]
@sosukesuzuki So i looked into this more, looks like i was a little overzealous in trying to simplify the repro, i have updated the original issue description with a working repo (i tested it on main via the flow parser). The inner `foo` property was needed to trigger this.

**Comment by pieterv** [comment]
Oh looking around some more, looks like this was intended behavior which was added with #13532?

**Comment by pieterv** [comment]
Closing since i believe this is intended behavior.
