### ISSUE TITLE
TypeScript interface issues

### ISSUE THREAD

**Issue by azz** [prettier/prettier#1484]
Ran into a couple of issues with interfaces:

The colon here should be a semi-colon:
```
$ echo "interface X { x }" | ./bin/prettier.js --parser typescript
interface X { x:  }
```

The prefix is not displayed if the body is empty:
```
$ echo "interface X {  }" | ./bin/prettier.js --parser typescript
{}
```

cc. @despairblue

**Comment by despairblue** [comment]
Good catch! I'll refactor that :)
