### ISSUE TITLE
Flow type generic syntax breaks awkwardly on long lines with destructured function args (ESLint error)

### ISSUE THREAD

**Issue by mmcgahan** [prettier/prettier#1486]
Not a high priority because there are workarounds, but

this:

```js
export const thisIsMyFunc = ({ foobar, bar, baz, qux }: Object): Promise<Object> => Promise.resolve({});

```

turns into this:

```js
export const thisIsMyFunc = ({ foobar, bar, baz, qux }: Object): Promise<
  Object
> => Promise.resolve({});
```

The line break inside the `< >` type parameter then throws an ESLint error (which seems reasonable).

Preferred formatting (which is eventually what you get if the destructured keys are long enough):

```js
export const thisIsMyFunc = ({
  foobar,
  bar,
  baz,
  qux
}: Object): Promise<Object> => Promise.resolve({});
```

Interestingly, it looks like it's hard to get the same line break position if you _don't_ destructure the function argument.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20const%20thisIsMyFunc%20%3D%20(%7B%20foobar%2C%20bar%2C%20baz%2C%20qux%20%7D%3A%20Object)%3A%20Promise%3CObject%3E%20%3D%3E%20Promise.resolve(%7B%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
I just pushed 1.3.0 which fixes this this issue! https://github.com/prettier/prettier/releases/tag/1.3.0

It now looks

```js
export const thisIsMyFunc = ({
  foobar,
  bar,
  baz,
  qux
}: Object): Promise<Object> => Promise.resolve({});
```
