### ISSUE TITLE
Prettier breaks when wrapping text in curly braces [WebStorm 2023.1.2 + sveltekit]

### ISSUE THREAD

**Issue by laszlo1337** [prettier/prettier#14882]
**Prettier 2.8.8**

In WebStorm, when editing .svelte files, when trying to wrap text in {} by selecting the text and pressing shift + {
prettier breaks completely. Steps:

1. Create example component
![image](https://github.com/prettier/prettier/assets/24696743/bd974fdc-3985-4f8f-9be7-f0ed9bfecce8)

2. Select text that needs to be wrapped in {}
![image](https://github.com/prettier/prettier/assets/24696743/2c24d2b0-4d14-4d76-b4f0-21e79510079e)

3. Press `Shift + {`
![image](https://github.com/prettier/prettier/assets/24696743/9d0770de-0ba8-40b0-9b8e-6e355b2b1a6c)

This does not happen in .js files, and wrapping in square brackets works as intended (`Shift + [`)

`prettierrc` file 
```
{
  "useTabs": true,
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 180,
  "semi": false,
  "plugins": [
    "prettier-plugin-svelte"
  ],
  "pluginSearchDirs": [
    "."
  ],
  "overrides": [
    {
      "files": "*.svelte",
      "options": {
        "parser": "svelte"
      }
    }
  ]
}

```
I don't think it has something to do with svelte plugin, because removing `plugins` and `overrides` did not change anything

**Expected behavior:**
Should format the component without breaking

**Comment by laszlo1337** [comment]
Now this happened also when commiting with "Reformat code" checkbox checked. The code was commited in broken state. 
In an older sveltekit project where prettier version was 2.2.0 nothing like this ever happened

**Comment by sjunepark** [comment]
+1

**Comment by sosukesuzuki** [comment]
Can you report this to https://github.com/sveltejs/prettier-plugin-svelte ?
