### ISSUE TITLE
This plugin is not automatically used by prettier when packages installed by pnpm

### ISSUE THREAD

**Issue by zoltan-nz** [prettier/prettier#14905]
If the package manager is `pnpm`, prettier cannot use this plugin.

Every ruby file is failing with the following error:

```
[error] No parser could be inferred for file: ...
```

Is there any suggested solution?

**Comment by kachkaev** [comment]
Plugin autoloading in pnpm and yarn PnP has been an issue for quite some time: https://github.com/prettier/prettier/issues/8474

We have removed plugin search feature completely (https://github.com/prettier/prettier/pull/14759), so please define your plugin [in the config file](https://prettier.io/docs/en/configuration.html) (e.g. `prettier.config.cjs`):

```js
{
  // ... rest of config
  plugins: [require("@prettier/plugin-ruby")]
}
```

**Comment by zoltan-nz** [comment]
@kachkaev Oh, thanks for your help and suggestion. I haven't found that solution before or seen it in the README or doc. Make sense. Thank you! :)
