### ISSUE TITLE
Ternary operators in JS/TS are very unreadable

### ISSUE THREAD

**Issue by coolCucumber-cat** [prettier/prettier#14907]
Look at my code before prettier:
```javascript
value = unit == 0 ?	(value <= 31 	? value : 31	)
: unit == 1 ?		(value <= 12 	? value : 12	)
: 			(value <= 2999? value : 2999	)
```
Writing code in GitHub is terrible so it probably looks off but it's very readable. Now look at this:
```javascript
value =
	unit == 0
		? value <= 31
			? value
			: 31
		: unit == 1
		? value <= 12
			? value
			: 12
		: value <= 2999
		? value
		: 2999
```
The last two lines aren't indented, everything after the unit == 0 is indented 1 too far, and even if that was fixed it's still pretty bad. I doesn't even have brackets to show what belongs to what.

On an unrelated note, this semicolon is stupid. I know why it's there and I don't use semicolons, but just put it on the previous line. In this case, it's the first line so it's not even neccessary:
```typescript
if (input != null) {
	;(input as HTMLElement).focus()
	return true
}
return false
```

In this case, I know there's a max length, but that join on a new line is the last place I would consider targeting for code readability. Everywhere else would benefit from some formatting, but this is less readable. The ternary operator could be indented, there are even already brackets there that would help:
```javascript
model.value = (type == 'date' ? formatDateArray(modelValue) : modelValue).join(
	'.'
)
```

On an even more unrelated note, I hate that there are spaces after if and for statements, but not functions. I get this is an opinionated code formatter, but there aren't any unopinionated code formatters really even.

**Comment by coolCucumber-cat** [comment]
Or maybe this would be good too:
```javascript
value =
	unit == 0
		? value <= 31
			? value
			: 31
		: unit == 1
			? value <= 12
				? value
				: 12
			: value <= 2999
				? value
				: 2999
```

**Comment by kachkaev** [comment]
👋 @coolCucumber-cat! There are [a few open issues](https://github.com/prettier/prettier/issues/9561) on ternary operators, e.g. https://github.com/prettier/prettier/issues/9561. I suggest to continue the discussion there to avoid duplicates.

**Comment by coolCucumber-cat** [comment]
@kachkaev I just clicked on this issue again and realised you closed it as `not planned`? Is there simply not a better option for a close reason or... ? There was a vote 2 or 3 years ago about this and nothing is being done. Why?

**Comment by jxn-30** [comment]
> @kachkaev I just clicked on this issue again and realised you closed it as `not planned`? Is there simply not a better option for a close reason or... ? There was a vote 2 or 3 years ago about this and nothing is being done. Why?

There are only two options to close an issue:
* "Close as not planned"
* "Close as completed"

As there already are other issues to this topic (as already mentioned), the "not planned" is the better choice from a maintainers point of view.
More Options by GitHub would be cool but they are not available at the moment, thus one of the two must be chosen 😉

**Comment by coolCucumber-cat** [comment]
I assume 😉 means it's being worked on? 😃
