### ISSUE TITLE
Prettier have an issue with VS Code version 1.79 on WSL

### ISSUE THREAD

**Issue by yazid113** [prettier/prettier#14915]
**Environments:**

- Prettier Version: 2.8.8
- Running Prettier via: Api
- Runtime: Node.js v16, Chrome v83
- Operating System: Windows subsystem for Linux
- Prettier plugins (if any): none

**Steps to reproduce:**

When I start up a project I been working have this error with the prettier extension

![image](https://github.com/prettier/prettier/assets/92461753/3bb3d04a-3ac2-4f8a-99aa-fdcfb62314e4)

the error comes out as soon as the extension starts up and wont let me use the formatting functionality,
this issue was not happening on VS Code version 1.78 it start as soon at VS Code got upgrade.

**Comment by leandrorodrigues00** [comment]
I have the identical problem.
I copied my project to windows+powershell and in it prettier works normally, the problem occurs only in wsl.

**Comment by sosukesuzuki** [comment]
Thank you for reporting this. Can you report this to https://github.com/prettier/prettier-vscode report? Maybe this is VSCode ext side problem.
