### ISSUE TITLE
Line exceeds max length when calling function with single line template literal

### ISSUE THREAD

**Issue by simonkberg** [prettier/prettier#1492]
Input: (with 80 width column indicator)
```js
const test = () => {
  try {
    spinner.succeed(`Detected as running on a ${bold(distro.name)}-based distro.`)
  } catch (e) {}
}
-------------------------------------------------------------------------------^
```

Output:
```js
const test = () => {
  try {
    spinner.succeed(`Detected as running on a ${bold(distro.name)}-based distro.`)
  } catch (e) {}
}
```

Expected:
```js
const test = () => {
  try {
    spinner.succeed(
      `Detected as running on a ${bold(distro.name)}-based distro.`
    )
  } catch (e) {}
}
```

IMO, single line template literals as arguments should be on it's own line if it doesn't fit inside the specified width. [Live test case](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20test%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20try%20%7B%5Cn%20%20%20%20spinner.succeed(%60Detected%20as%20running%20on%20a%20%24%7Bbold(distro.name)%7D-based%20distro.%60)%5Cn%20%20%7D%20catch%20(e)%20%7B%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D).

**Comment by vjeux** [comment]
I just pushed 1.3.1 as a hotfix for this. Sorry about it!
