### ISSUE TITLE
prettier cli run `prettier --write` very slow on wsl2

### ISSUE THREAD

**Issue by gyhyfj** [prettier/prettier#14937]
It's fast on win10, but very slow on wsl2 of the same pc, almost 10 times time taked.
This problem is for prettier cli, the prettier plugin for vscode works well.

**Comment by kachkaev** [comment]
👋 @gyhyfj! Please provide more details (reproduction repo, steps and benchmarks) – it is very hard to help with this issue otherwise.

**Comment by gyhyfj** [comment]
Sorry, it's most likely an issue with lint-staged. I'll close this issue now
