### ISSUE TITLE
[For v3+ / breaking change] Table formatting with partially extremely wide cells

### ISSUE THREAD

**Issue by tats-u** [prettier/prettier#14935]
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfAZhCqBGBDAJ1QB0pUBaCksvXa1AbTAF0AKACxhgAcBnJAPQCA7qIB0cAB54AttwA2cMZBkCYBODIQATCAFde8gJ4CAjnoCW8AfOgBzAWDjz5A3hDVYBMvFBO9uPCdeAUI4UO1tOG0ASlRtehkLSMUAAkUoOxh2VDhUEAAaEAhuGAtoXmRQQgIIYQAFMKhKlDx5YTwjSqKcAiCAazgYAGVZOAAZCyg4ZHQ23jgevrBBkcCwKbtkdT1FkE0caKjtcd87PTw7OAAxCAIfLk3kEDw9GAhCkE4ZeQB1discACQTgwwQvCsFgAblYjM8wLxuiApgsCDB6n07D5ZvM9gArXiSYabRQART0EHgOPkCyKgQIqOePgI-V0wign24BCmMF+yWyyAAHAAGOm1Ba-PrcZ5coFwAhQmZFcyUuAYkotF68cjTaLRT4acwWDQYy7YpBzGl7BZJbYEXZFCGZRQAQS43JwbzV8sm02ptJATrsZIpVItuKKMDwOD52gFSAATJG+hZ5JsAMIQGTm-a8ACsnwMcAAKtGWpaA1DdgBJKBRWDDMDc0ouuvDGBGRT+uAAXx7QA

```sh
# Options (if any):
```

**Input:**

```markdown
|foo|bar|
|-|-|
|a|b|
|[c](https://www.example.com/tremendously/quite/long/cell/so/too/many/spaces/are/added)|d|
|middle length|e|
```

Note:

- A few cells are much wider than others (e.g. because of links, HTML tags, or JSX components)
- I assume there can be more rows below this table.

**Output:**

```markdown
| foo                                                                                    | bar |
| -------------------------------------------------------------------------------------- | --- |
| a                                                                                      | b   |
| [c](https://www.example.com/tremendously/quite/long/cell/so/too/many/spaces/are/added) | d   |
| middle length                                                                          | e   |

```

**Expected behavior:**

Do you, Prettier maintainers, think which is better, the above current output or the following one?

```markdown
| foo           | bar |
| ------------- | --- |
| a             | b   |
| [c](https://www.example.com/tremendously/quite/long/cell/so/too/many/spaces/are/added) | d |
| middle length | e   |

```

I think the current output is more difficult to re-edit after format especially when the window of the editor is narrow (half, not full-width), the word-wrapping feature is enabled, or there are too may columns.

**Comment by fisker** [comment]
I prefer current output.

**Comment by tats-u** [comment]
I found a more important problem; ambiguous width characters are always treated as half.
Also, In Source Han Mono, CJK : alnum = 3 : 2, not 2 : 1.
It may be no use trying to align widths of cells in a single way.
