### ISSUE TITLE
Very hard to coordinate for beginnerss

### ISSUE THREAD

**Issue by Nicitaa** [prettier/prettier#14938]
**Environments:**

- Prettier Version: 2.8.8
- Running Prettier via: 
- Runtime: 
- Operating System: 
- Prettier plugins (if any): 

**Steps to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Very hard to coordinate and set up prettier for my self **

Contact me icpcsenondaryemail@gmail.com I help you rewrite your docs if you interested in

**Comment by sosukesuzuki** [comment]
Feel free to create an issue or PR for improving docs.

**Comment by Nicitaa** [comment]
> Feel free to create an issue or PR for improving docs.

Where I can do it attach link please

Like do it [here](google.com)

Thanks
