### ISSUE TITLE
Prettier failed to parse when using babel-ts

### ISSUE THREAD

**Issue by so1ve** [prettier/prettier#14934]
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAFAI1QJwAQA8eAjADR4BMeAfALx5a4CUTIpIEADjAJbQDOyULhwQA7gAVcCQSlQAbMagCeg9phyowAazgwAyqgC2cADI8ocZADMF-OOs069+zlosBzZDBwBXByBwRphwACahYaaoUB6+qB5wAGIQOEaoMLwxyGi+MBBsIAAWMEbyAOqFPPD8bmBw+jJVPABuVcrZYPxqIBb2ODASmh5pNnYBAFb8AB76nvJwAIq+EPCj8vbsbjh92dgh8gC0MN2cOBYwZTyhMIXIABwADJui9mWanNmncH3NVuwAjst4IMuLI0PwDpYwmECjg4ICeHDBvERkhbOsAvYjDxvH5MXM4ABBDJnTC5OASOA4cyWNYbED8AlLFZWNFjdgwVCYS7XW5ICgczQ8eSeADCECMqMC-AArAVfPYACpc2To+nNfwASSgEVg+jAZ24hJ1+hgynmdLgAF8rUA)

```sh
# Options (if any):
--parser babel-ts
```

**Input:**

```ts
a(bar < 1, 2 >= (bar))
```

**Output:**

```ts
SyntaxError: Invalid left-hand side in assignment expression. (1:3)
> 1 | a(bar < 1, 2 >= (bar))
    |   ^
```

**Expected behavior:**

It should parse.

However, it seemed to be fixed in babel: https://github.com/babel/babel/issues/15628

Shall we create a new release?

**Comment by sosukesuzuki** [comment]
This has been already fixed in `main` branch.

**Comment by so1ve** [comment]
Yes I mean you can draft a new release now
