### ISSUE TITLE
Output ugly when chain is called on a single char object (like $ from jQuery)

### ISSUE THREAD

**Issue by stormpat** [prettier/prettier#1495]
https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20this%20looks%20good%5CnmyPromise.then(()%20%3D%3E%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D).then(()%20%3D%3E%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D).catch(()%20%3D%3E%20%7B%5Cn%20%20%2F%2F%20..%5Cn%7D)%3B%5Cn%5Cn%2F%2F%20this%20looks%20good%5CnjQuery.ajax(%7B%5Cn%20%20url%3A%20'www.url.com'%5Cn%7D).done(function(response)%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D).fail(function()%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D)%3B%5Cn%5Cn%2F%2F%20this%20looks%20good%5Cn%24dollars.ajax(%7B%5Cn%20%20url%3A%20'www.url.com'%5Cn%7D).done(function(response)%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D).fail(function()%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D)%3B%5Cn%5Cn%2F%2F%20this%20looks%20good%5Cn%24_o.ajax(%7B%5Cn%20%20url%3A%20'www.url.com'%5Cn%7D).done(function(response)%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D).fail(function()%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D)%3B%5Cn%5Cn%2F%2F%20this%20looks%20bad%5Cn%24.ajax(%7B%5Cn%20%20url%3A%20'www.url.com'%5Cn%7D).done(function(response)%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D).fail(function()%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D)%3B%5Cn%5Cn%2F%2F%20this%20looks%20bad%5Cn_.ajax(%7B%5Cn%20%20url%3A%20'www.url.com'%5Cn%7D).done(function(response)%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D).fail(function()%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D)%3B%5Cn%5Cn%2F%2F%20this%20looks%20bad%5CnCaps.ajax(%7B%5Cn%20%20url%3A%20'www.url.com'%5Cn%7D).done(function(response)%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D).fail(function()%20%7B%5Cn%20%20%2F%2F%20...%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Hi, and thanks for a great tool!

The formatting looks weird in the last jQuery version. I tested the parser out some more, and it looks like when there is only a single char prettier formatting is broken.

[edit] Seems to be broken only when using a special char, like ```$```, ```_ ```
[edit2] It seems to also break when using uppercase as a first letter. I updated the example.

**Comment by azz** [comment]
There is special handing of identifiers starting with an uppercase character as they generally work as factories (e.g. `Promise.resolve()`).

Personally, I would inline the object literal if it fits and only has one property.

```js
$.ajax({ url: 'www.url.com' })
  .done(function(response) {
    // ...
  })
  .fail(function() {
    // ...
  });
```

Thoughts on that?

**Comment by vjeux** [comment]
I'm sorry about this but it is actually intended. The heuristics for printing member chains are pretty complex and I haven't found a way to make everything look good. The example that you show, while not ideal, is not crazy bad. At this point, we've reached a local maxima where any small change to make something better end up making a lot of other things worse.

I'm going to close this issue as I don't know how to solve your specific problem :(
