### ISSUE TITLE
prettier v3 graphql issue - SyntaxError: Syntax Error: Unexpected Name "GitObject".

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#14964]
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAQgGwgCNsBLAWw3znIRgGdsA5CAEzgBoAdKHgcVIwA8kQBWcMDGzAe2bAEMiRAE5wAbqXnxWQ0qyTYAyjGWkoAcwCEPWdiJp4h0gC84BgJKxrvKHMjlyQQAlOHoIAFdlMDgABS0ACwMAVSD3b1t-QJgk5Xxk1O85PQ8AEXTfMnpcM3llNANcCAhqeShyovoAFWVwqDAtOH08Jpa2mwqIYuwBYTEJGHcy8blVDAh6QQg6gxC1jZgttHbseAAPGANjUwseAF8QDhAIDBhSaHpkUFrlCAB3ONUUA+KHk+F+8jQH0eKnkYAA1nAYIZ5LQADJmODIABmoPonBAMPhiMMGFhZnMyBM4XxNCIg3YrFRrXM4Xk5jgADEtuQtK8LMgQPJwgcHiB4jByPgAOrxQShUnRQwIfakDToAVgehQkBmPHKGAxZRsnnY3H40T0U5OCzUACK4Qg8FN+Dxj1Jyj1AvMRow8QAjvhRRhrjApXoYPFkAAOAAMbp+eKlPoFwdCcGUakxjz9DvghuewMF9AAtFA4INBqLVDnSKpDcb5M7XSA8YFKT18RsbXAAIIwEykIjC2Lp9Flpud8l23OYpA4l34mCKMOsCPIABMjxM8lI+HJAGEIAFGyhQgBWUXhPGdRTA+fNtTUzzsWCGMCmF49qCsYxoagT25biAA)

```sh
--parser graphql
```

**Input:**

```graphql
type Blob implements Node,

GitObject {
  abbreviatedOid: String!

  byteSize: Int!

  commitResourcePath: URI!

  commitUrl: URI!
  id: ID!

  isBinary: Boolean!

  isTruncated: Boolean!

  oid: GitObjectID!

  repository: Repository!

  text: String
}
```

**Output:**

```graphql
type Blob implements Node, GitObject {
  abbreviatedOid: String!

  byteSize: Int!

  commitResourcePath: URI!

  commitUrl: URI!
  id: ID!

  isBinary: Boolean!

  isTruncated: Boolean!

  oid: GitObjectID!

  repository: Repository!

  text: String
}

```

**Expected behavior:**

follow code works fine in v2 but not in v3

original error message
```sh
packages/graphql-language-service/benchmark/fixtures/github.graphql[error] packages/graphql-language-service/benchmark/fixtures/github.graphql: SyntaxError: Syntax Error: Unexpected Name "GitObject". (1:28)
[error] > 1 | type Blob implements Node, GitObject {
[error]     |                            ^
[error]   2 |   abbreviatedOid: String!
[error]   3 |
[error]   4 |   byteSize: Int!
```

**Comment by fisker** [comment]
https://github.com/prettier/prettier/blob/main/changelog_unreleased/graphql/12835.md

**Comment by fisker** [comment]
Not familiar with graphql. Seems `&` should be used?
