### ISSUE TITLE
Files whose names starting with '$' (dollar sign) cannot be checked via the prettier cli in linux

### ISSUE THREAD

**Issue by amayer42** [prettier/prettier#14987]
Files that have a name starting with '$' (i.e. `$test.js`) seem to cause issues when attempting to check them via the prettier cli in linux environments. I cannot replicate the same behavior in Windows.

**Environments:**

- Prettier Version: 2.8.8
- Running Prettier via: CLI
- Runtime: Node.js v16.20.1
- Operating System: Ubuntu-22.04 via WSL2, works fine in Windows 10 Enterprise (10.0.19045)
- Prettier plugins (if any): none

**Steps to reproduce:**

1. Clone this repo: https://github.com/amayer42/prettier-dollar-sign-bug
2. run `npx prettier -c test.js`
3. Receive expected warning: 
![image](https://github.com/prettier/prettier/assets/5626443/a7494243-4d1e-4791-81e4-7ab45921eec6)
4. run `npx prettier -c $test.js`
5. Receive unexpected error: 
![image](https://github.com/prettier/prettier/assets/5626443/06dffa0b-63f8-4fad-aab9-679e2273046f)

**Expected behavior:**

Step 5 above should produce the same warning as in step 3.

**Actual behavior:**

prettier seems to try searching for a file that I did not specify and then cannot find the file.

**Comment by Skalman** [comment]
This is not a bug.

Your shell interprets `$test` as a variable, but you haven't defined that variable, so the empty string is used instead. Empty string + `.js` is the reason why Prettier complains about not finding files with the pattern `".js"`.

You need to escape commands. In this case, you can use `npx prettier -c '$test.js'` or `npx prettier -c \$test.js`. Just beware that there are more special characters that require escaping when used in a command: `$`, `\`, `'`, `"` and space.
(There could be other chars that also need escaping, but I can't think of any more.)

**Comment by amayer42** [comment]
> You need to escape commands. In this case, you can use `npx prettier -c '$test.js'` or `npx prettier -c \$test.js`.

I can confirm that this does work. I tested `npx prettier -c "$test.js"` locally and that failed just like `npx prettier -c $test.js`. I never would have imagined that there would be a difference between wrapping in single rather than double quotes. Sorry, I probably should have mentioned that I had also tried surrounding the name in double quotes in my original write up.

The reason that I noticed this is actually because we are using nrwl/nx and their `nx format:check` CLI command actually runs the prettier CLI command `npx prettier -c "$test.js"`. If the prettier team does not think that this is an issue in prettier, I can submit a bug to nx to to them to try and escape special characters.

**Comment by Skalman** [comment]
I'm not part of the Prettier team, but I am very, very sure that this is not a bug in Prettier. You should probably file a bug with nrwl/nx (I don't know what they are/do).

Shell escaping and variable interpolation is different from most other programming languages.

```sh
TEST='a b c'

# Not within quotes - whitespace within the variable is split into separate arguments
some-command $TEST
some-command 'a' 'b' 'c'

# Within double quotes - the variable is kept as one parameter
some-command "$TEST"
some-command 'a b c'

# Within single quotes - not interpreted as a variable
some-command '$TEST'
some-command "\$TEST"
```

The single/double quote distinction is similar to PHP.

**Comment by amayer42** [comment]
@Skalman , thanks for the explanation. I appreciate you pointing out the differences amongst those various commands. I will close this issue and report this over to the folks at nx.

Thanks a bunch for your time!

**Comment by amayer42** [comment]
I went to repro this issue in the latest version of nx and found that they have actually fixed this by properly escaping the `$` character. I just wanted anyone that finds this in the future to know that I didn't file a bug with them because of that.
