### ISSUE TITLE
Prettier is trying to access "node-modules", should be accessing "node_modules"

### ISSUE THREAD

**Issue by anxpara** [prettier/prettier#14988]
Running the VS Code Prettier plugin on Windows.

Versions 9.15.0 and 9.16.0 are broken. 9.14.0 is the last working version for me.

I don't use format on save, i just use ctrl+shift+f. When I hit my shortcut, nothing happens. If i use ctrl+shift+p and then type "format document with" and then select prettier, I get an actual error dialog. "Error loading node module 'c:\Users........\node-modules\prettier"

node_modules has an underscore, not a hyphen

**Comment by anxpara** [comment]
@kachkaev this isn't a question, this is a development issue, prettier is crashing.

**Comment by kachkaev** [comment]
Please provide reproduction steps if you think that this is an issue in Prettier core. If your setup involves VS Code, it has https://github.com/prettier/prettier/labels/scope%3Aexternal

**Comment by anxpara** [comment]
I'm not sure if it's a core problem, i don't know which part of prettier is attempting to load "node-modules"

Where do i go to file an issue with the vs code plugin?

**Comment by anxpara** [comment]
Are either of these lines of code from this repo related?

https://github.com/prettier/prettier/blob/2bd131fbd29e94e989e64904f1a628877d38ae3d/tests/config/install-prettier.js#L68

https://github.com/prettier/prettier/blob/2bd131fbd29e94e989e64904f1a628877d38ae3d/.yarnrc.yml#L4

**Comment by anxpara** [comment]
> Please provide reproduction steps if you think that this is an issue in Prettier core. If your setup involves VS Code, it has [ scope:external](https://github.com/prettier/prettier/labels/scope%3Aexternal) This is not an issue with Prettier, it’s an issue with external software, like an editor integration

I did a search for "node-modules" in the vscode repo and only found this:

[‎.github/workflows/main.yml](https://github.com/prettier/prettier-vscode/blob/9d40aecd5b71186848098af19f945473eabb58db/.github/workflows/main.yml#L33)
```
        with:
          cache-name: cache-node-modules
        env:
        with:
          cache-name: cache-node-modules
        env:
```

Unclear if the bug is in the extension or the core repo, but I think you should consider the possibility that it's in this repo, given that the use of the hyphen originated in this repo.

**Comment by anxpara** [comment]
@kachkaev
