### ISSUE TITLE
Wrong parenthesis around typeof

### ISSUE THREAD

**Issue by angelod1as** [prettier/prettier#14985]
**Prettier 2.8.8**

**Input:**

```jsx
const testObject = {
  first: 'a',
  second: ['first', 'second', 3]
}

type A = typeof testObject.second[0]
// "string"

type B = typeof testObject.second[2]
// "number"
```

**Output:**

```jsx
const testObject = {
  first: 'a',
  second: ['first', 'second', 3]
}

type A = (typeof testObject.second)[0]
// "o"

type B = (typeof testObject.second)[2]
// "j" 
```

**Expected behavior:**

The parenthesis should not have been added.

## Details

I read through #14162 and #14283 and #13546 and #14042 and couldn't find a solution for this problem. How to disable this rule or fix it? There's a lot of discussion but no solution.

**Comment by fisker** [comment]
Can't reproduce with any js parser

**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8MHkBGAVnGFgLybAA6UmmAZgJYBOGSmA5AIYcA0NdNCWgATdgG0OTVjD6chkKCLkBmALo0AvjRowAngAc4Eetjh4iJGADoFo8QAYNUAPQvMVEBmaMoAc08dWENjUxwYAmJSW2ElcQAmZzcPECgAVwBbfDhmTxBeEAgDGEZ0ZFAuZmYIAHcABUqENGQQLgAbGq49ZoL8Zi4wAGs4GABlLgy4ABlfOGR6dqFe-qGR0YMB3z9kGGY0uAK4LLgREROprn80rj84ADEIZgyuGBL-Fq40mAh8kAALGAZNoAdT+jBwGzAcFGTXBjAAbuC9C0wGgeiBfEJmDA6v0-M95osDiBCGgAB6jLZtOAARTSEHghLaSxAG1YORa+iMaDAPmKvwMPlgwMYIhgf2QAA4HAVBRAhMD+gYWoLzDl4XMCgBHenwXFFZooLhoAC0UDgJxOv2YcB1LDguJuBKQC2ZxKEGUYOz27qpcAAgq8fPgvg6cjNzUyWWg-XSGXMXUSCjAuPgRWKJUh4sn+ow2lsAMIQDLOkDmACsvzSQgAKqnDa6WfD9gBJJQIMa8xjFf1KUb6alRuCaTRAA)

```sh
--parser typescript
```

**Input:**

```tsx
const testObject = {
  first: 'a',
  second: ['first', 'second', 3]
}

typeof testObject.second[0]
// "string"

typeof testObject.second[2]
// "number"
```

**Output:**

```tsx
const testObject = {
  first: "a",
  second: ["first", "second", 3],
};

typeof testObject.second[0];
// "string"

typeof testObject.second[2];
// "number"

```

**Comment by fisker** [comment]
We add parens to type query, not unary `typeof`.


**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXm3SwgDNi4BnGAeQCMArOMGAOipegBMBtABgC6AHSiiSccpRoNmrDlyh8hIADQgIGGAEtoVZKACGAJ2MQA7gAUTCfSkMAbc4bT719Y4bABrODADKhgC2cAAy2lBwyGSOnO6ePn7+GF4RAObIMMYArnDqcEH0cNzcxaGGUGnZhmlwAGIQxkGGMDqVyCCG2TAQaiAAFjBBDgDq-drwVClgcP62E9oAbhNoHWBUbiARnMYwlp5pzdGxeSCMVAAe-ukOcACK2RDwxw5xICnGOx0SVGDG2lo+hh-rARtpuDB+sgABz8dTAiCcEaeDAdYHUODGRZRdQAR0e8H2mjsnSoAFpIsVin1jHB8dpafsakckDFXqdOEFtJkchybnBcK1-vRunBLJjwpEXm8qPyHk8oqyTuoYIZ6GCIVCkAAmFWebQOdIAYQgQRZIGoAFY+tlOAAVNV2NlvRa5ACSSgQAT+AJguCU-nQt2lcAAvqGgA)

```sh
--parser typescript
```

**Input:**

```tsx
type A = typeof testObject.second[0]

typeof testObject.second[0]
```

**Output:**

```tsx
type A = (typeof testObject.second)[0];

typeof testObject.second[0];

```

**Comment by angelod1as** [comment]
Ohhh that's the issue, then. Yes, my example was flawed, will edit it now and reopen because I still don't know how to fix/disable that.

**Comment by fisker** [comment]
We are not breaking code, and we won't change the output. This is also why we add parens, because it's confusing for TS beginers.

**Comment by angelod1as** [comment]
Honest question: why do you say you are not breaking code when the output without parens change? Isn't this breaking code? And shouldn't this be possible to be disabled, as it's aimed at TS beginners, but there are projects where no beginners are around?

**Comment by flamincode** [comment]
This is cropping up for us as well. Looking for a solution.

**Comment by flamincode** [comment]
@angelod1as our workaround is just to keep everything as type. Instead of referencing variables.

**Comment by flamincode** [comment]
@fisker this isn't really a realistic solution though.

**Comment by angelod1as** [comment]
@flamincode keeping everything as a type goes against a good code organization. We use this array-indexed type in a lot of places. So I'm supposed to copy `typeof testObject.second[0]` instead of `A` all around my code?

**Comment by flamincode** [comment]
@angelod1as it turns out this doesn't actually break the code. At least in our case. Got some helpful links from @fisker here: https://github.com/prettier/prettier/issues/14990 
Seems to be a strange typescript mistake that is now a rule.
