### ISSUE TITLE
Support for the new Angular Control Flow Syntax

### ISSUE THREAD

**Issue by eneajaho** [prettier/prettier#14991]
Angular is introducing a new control flow syntax in it's [RFC](https://github.com/angular/angular/discussions/50719).

I'm opening this issue in order to track the support for it in the prettier formatter.

Because the new sytanx follows the svelte syntax a lot, I believe we can learn/be-inspired/copy a lot from the svelte one.

**Comment by eneajaho** [comment]
Update: Angular choose to go with @-syntax for the control flow.

https://blog.angular.io/meet-angulars-new-control-flow-a02c6eee7843

**Comment by michaelfaith** [comment]
Thanks for opening this.  With v17 right around the corner, I hope this gets some love in time.

**Comment by sosukesuzuki** [comment]
Thank you for sharing, I'll look into this.

**Comment by sosukesuzuki** [comment]
Notes:

- Introduce AST fro control flow: https://github.com/angular/angular/pull/51299
- Control flow keywords are `defer`, `switch`, `for`, `if
-

**Comment by sp90** [comment]
@sosukesuzuki cant wait to see it arrive thanks for taking your time and doing it 🎉

**Comment by dylhunn** [comment]
> Notes:
> 
> * Introduce AST fro control flow: [Introduce AST for control flow angular/angular#51299](https://github.com/angular/angular/pull/51299)
> * Control flow keywords are `defer`, `switch`, `for`, `if`

The full list of keywords: `@defer`, `@placeholder`, `@loading`, `@error`, `@if`, `@else`, `@else if`, `@for`, `@empty`.

All of these keywords are followed by optional parentheses, then curly braces, e.g.:
```
@if (foo) {
   <span></span>
} @else if {
   <div></div>
}

**Comment by fisker** [comment]
This looks like a big change needed to our HTML printer (maybe also parser?).

**Comment by sosukesuzuki** [comment]
Latest angular template parser supports `tokenizeBlocks?` option( https://github.com/angular/angular/commit/29aaded0c3fbf669a95ea70928b4458579fbcc39 ). I think we need to enable that when `parser="angular"` for parsing blocks (`@if`, `@else`, `@defer`, etc...).

So, I plan that I would start by updating angular-html-parser to the latest version.

**Comment by jpike88** [comment]
Can I confirm that this will ensure that control flow blocks will always have a newline between them and the enclosing code?

So this:
```
@if (foo) {
   <span></span>
} @else if (bar) {
   <div></div>
}
```

Never this:
```
@if (foo) { <span>
</span> }
```

**Comment by huevosyitz** [comment]
now that Angular 17 has just release, any updates to this? Thanks in advance!

**Comment by DingWeizhe** [comment]
@sosukesuzuki 
Thank you for updating angular-html-parser.
I implemented a simple version through the tokenizeBlocks parameter to solve this issue.

The following are pull requests: 
https://github.com/prettier/prettier/pull/15606

**Comment by jpike88** [comment]
@DingWeizhe just tested it against my codebase, seems to work perfectly, I can't find any issues with it.

**Comment by rickvandermeij-aanzee** [comment]
it works, but i rather see a better indenting on tabs when in a `@if`. see example
```
@if (mealType !== 'lodging' && !package) {
<span class="mx-0.5 text-base font-normal sm:text-lg"> + </span>
@switch (mealType.toLowerCase()) { @case ('breakfast') {
<svg-icon
	class="h-6 w-6 grow-0 text-dark-primary"
	data-test-id="breakfast-icon"
	src="assets/icons/icon-coffee-cup.svg"
/>
} @case ('halfboard') {
<svg-icon
	class="h-6 w-6 grow-0 text-dark-primary"
	data-test-id="halfboard-icon"
	src="assets/icons/icon-fork-knife.svg"
/>
} @default {
<svg-icon
	class="h-6 w-6 grow-0 text-dark-primary"
	data-test-id="fullboard-allin-icon"
	src="assets/icons/icon-checklist.svg"
/>
} } }
```

**Comment by fisker** [comment]
@rickvandermeij-aanzee  Please open a new issue with issue template.

**Comment by rickvandermeij-aanzee** [comment]
@fisker will do -> https://github.com/prettier/prettier/issues/15833
