### ISSUE TITLE
adding parenthesis around typeof when indexing an array

### ISSUE THREAD

**Issue by flamincode** [prettier/prettier#14990]
You closed this issue https://github.com/prettier/prettier/issues/14985 but I don't believe a resolution was reached.

**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8MEEBO+AhgJ6YC8mA2gOQBuRANgK5wCMNANJvU6wExceDFnADMNALqYiaTJCgYAOlBUwSABziYAKnAwA1PvorZNcCADNs+mAWIkqUZgFsARnHySQnEBA0wAJboyKBEhBAA7gAK4QhoyCBMkaQJvm7EYADWcDAAykQucAAygVBwyJZMaHDpmTn5GkRgZQDmyDD4rL5w7nAAJv0DxURQrcxErXAAYhD4LkQwQWOJRMwwED4gABYwLowA6tuBOE1gcHnxJ4F0JySJYGhpIGU1+DDRxK0LldW1IAArNAADzybUYcAAiswIPBfowar4mvg3ol1Fo0GB8IEAlsNNjYAdAv0YNtkAAOAAMSPwEBqB2IGkS+P0njoFV8AEcYfBPv4EihZABacoDAZbfBwbmBSWfSY-JBVBH-GouQIdLoq8FwXBLbFudZwaKeUrleGIkBobXQ2EVRV-XwwIhuIkkslIfiO4iBRhtADCEBcCpA+gArFtmDUdM6BUqLXRWABJKBDWB5LE4uwpvLqCHmuAAXwLQA)

```sh
--parser typescript
```

**Input:**

```tsx
const testArray = ['value1', 'value2', 'value3'] as const

type TestValues = typeof testArray[number]
```

**Output:**

```tsx
const testArray = ["value1", "value2", "value3"] as const;

type TestValues = (typeof testArray)[number];

```

**Expected behavior:**
It should not have parenthesis as it breaks the code in this instance.

**Comment by dmcninch** [comment]
I agree this is a problem. There should be an optional exception at least for this common case. Right now it's introducing bugs unless I prettier-ignore a lot of lines of code.

**Comment by fisker** [comment]
> it's introducing bugs

What kind of bug? Will it make your code result differently?

**Comment by fisker** [comment]
For the ones may interest, [1](https://stackoverflow.com/questions/70102722/whats-the-precedence-of-typescript-operators) [2](https://github.com/microsoft/TypeScript/issues/19707)

**Comment by flamincode** [comment]
@fisker this is helpful, thanks for those links. It looks like we were assuming a breaking of code. We still find it syntactically bizarre, but this actually seems to be a typescript issue.

**Comment by fisker** [comment]
Close as completed.
