### ISSUE TITLE
Odd breaks in a multi-line expression

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#1499]
See https://github.com/facebook/jest/blob/bb72d065743dc973ab42447777419644db996920/packages/jest-cli/src/TestRunner.js#L144-L149

Not sure how long it's been like this but it isn't pretty.

**Comment by vjeux** [comment]
Thanks, yeah that's not pretty at all. I want to make better support for !( and !!(. It looks weird inlined right now.

**Comment by vjeux** [comment]
Closing as it's already tracked in https://github.com/prettier/prettier/issues/774
