### ISSUE TITLE
prettier-plugin-latex

### ISSUE THREAD

**Issue by analytic-bias** [prettier/prettier#15006]
People write ugly LaTeX code all the time, perhaps even more than general-purposed languages, which obviously makes editing documents, especially in a collaborative setting, difficult. Currently, the `LaTeX-fill-*` of AUCTeX is primitive and unsatisfactory, so is there a plan for a `prettier-plugin-latex`?

**Comment by sosukesuzuki** [comment]
We have no plan to implement prettier plugin for latex. But you can create it as a community plugins.
