### ISSUE TITLE
estree.d.ts is not a module

### ISSUE THREAD

**Issue by kingyue737** [prettier/prettier#15017]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: Browser API
- Runtime: Chrome 114
- Operating System: Windows
- Prettier plugins (if any): built-in estree and babel plugin

**Steps to reproduce:**

I'm using standalone prettier to format code text in browser
![image](https://github.com/prettier/prettier/assets/40021217/a7aae6e4-ad85-4ad7-b997-f64493bae3f7)

Import `prettier/plugins/estree` in source code will raise typescript error:
```
File './node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/plugins/estree.d.ts' is not a module.ts(2306)
```

**Expected behavior:**
No type error

**Actual behavior:**
I found `estree.d.ts` is an empty file

**Comment by fisker** [comment]
https://github.com/prettier/prettier/blob/e2f4ce38f7c1dac1d1ec5371670a93e3844f6b39/scripts/build/build-types.js#L40-L41

Any idea to fix it?

**Comment by kingyue737** [comment]
@fisker Add the following line can fix it
```ts
// estree.d.ts
export {}
```

**Comment by fisker** [comment]
Would you like to send a PR?
