### ISSUE TITLE
jsdoc comment parenthesis removal breaks return in some case

### ISSUE THREAD

**Issue by 700software** [prettier/prettier#15013]
**Prettier 3.0.0**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlPvgE5wzoN2m330D0AVL5y75e+AAIwAngAc4VAHQKAvoK69upOAA8pTInrxRygo1GVQQAGhAQpuaEWSgAhgwYQA7gAUXCByicANu5OEg5WAEYMTmAA1swAyk4AtnAAMjhQcMiogURwEVGxCVLRGQDmyDAM6PkgeUk4ldW1ROUBcACK6BDw2bm1AFZEmvFtnd29SDkBeVYAjhNwnm5SfiBORAC0mXAAJnuWIFVOOAHlAMIQSUlOyOsBAYetUGXtAIIwVTjh6PCecAx0pk+jNagALGBJAIAdTBOGIJTAcHivnhOAAbvCJHcwHpDuiagBJKD7WDxMAMHC2N4k+KSdog2YgHQQPLQqJSO46OB5BjorJWDK8mDLJxlG6M2olBi8u7hJzhOCPKw6DIwaE4XYwMHIAAcAAYrEwFjgmKLxbcpv0rDAFRqtTqkAAmKzoPIAFQVfmmTLgSUVu32u1SThe6DFcAAYhAGDdPuU7k5fhAQIpFEA

**Input:**

```jsx
function test() {
  return (
    /**
     * @type {...}
     */(expresssion)
  )
}

```

**Output:**

```jsx
function test() {
  return /**
   * @type {...}
   */ (expresssion);
}

```

which is interpreted as `return;` by JavaScript runtime

**Comment by gusbmurphy** [comment]
Would the following be the expected output?

```
function test() {
  return (
    /**
     * @type {...}
     */
    (expression)
  )
}
```

Seems tricky given that Prettier (I'm assuming) wants to do away with one set of the parentheses.

**Comment by 700software** [comment]
#15037 fixes this beautifully from my testing

https://deploy-preview-15037--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjAOo4wAWAUkQCYRgAqAngA5wDCAhiQMo4oAcwA2cADKC4ACgCU+YAB0o+fACc4MdGpXTpy1aoD0AKhP4AAjHZwFAOgcBffCaP6Vh1dLgAPNhqJAvChZA3xFGFCPWSjHZWUMLFwCYjIKGnpGVg4eEgBZdBFcSSgZeSUPDS0dfD0w4zN61XMrG3snJpc3bz8AoOgYsMGoOKgEzGxgwjgScioAQSgWAHkqODVOCABbLYQYAWExErKFMKrtXXdPU3NrDna7Z1crz1rffxn+kKao1WHR8ZJKapOaURYrNYbba7WAFIo4Y5yU6VTQXWovBomTq3NrAByPbHdd59IjBYZ-WLKEAAGhAEDYySgRGQoG4ajUEAA7gAFNkIZkobgiTncFjM2kAIzU3DAAGtNHxuLtjshUEKiHBJdK5Qq2DLBEJkDA1OhNSANVscEaTWbSYc4ABFdAQeCq9VmgBWRB8B1EjudrqQapEGtpAEcA3BuRy2AKQLwALSlOB0FM0kDG7g4EQGzY7bjIeMiETpu1++YwY04CXoeDc9YqoPu2mUGBbESkSgUGZ6sBwPj8ig4ABuFBYhbAgXTw9NAEkoKnYHwwGocAzFnQ+NYxG6Q2b-BANaRpWxCx8NWph3B04ILzBo9whFsC0297S9WoL4WJdwJXAS++q6wOQdBUMgAAcAAMtIaBGOAaA+T4vsGoYZr+IFgUgABMtLoBqTC-gKKFmnAWx-nQqZ0OI3DCOgj5wAAYhAajPpWBqFtwtYQCAjiOEAA

<table>
<thead>
<th>Input</th>
<th>Output</th>
<tr>
<td>

```ts
function testWithJsdocTypeCastSingleLine() {
  return ((
    /** @type {...} */(
      (expresssion)
    )
  ))
}

function testWithJsdocTypeCastMultiLine() {
  return ((
    /**
     * @type {...}
     */((expresssion))
  ))
}

function testWithAnyOtherCommentSingleLine() {
  return ((
    /** type {...} */(
      (expresssion)
    )
  ))
}

function testWithAnyOtherCommentMultiLine() {
  return ((
    /**
     * type {...}
     */((expresssion))
  ))
}
```

</td>
<td>

```ts
function testWithJsdocTypeCastSingleLine() {
  return /** @type {...} */ (expresssion);
}

function testWithJsdocTypeCastMultiLine() {
  return (
    /**
     * @type {...}
     */ (expresssion)
  );
}

function testWithAnyOtherCommentSingleLine() {
  return /** type {...} */ expresssion;
}

function testWithAnyOtherCommentMultiLine() {
  return (
    /**
     * type {...}
     */ expresssion
  );
}

```

</td>
</tr>
</table>
