### ISSUE TITLE
Force two blank lines between `return` statement and functions declarations below

### ISSUE THREAD

**Issue by Alexsey** [prettier/prettier#15023]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEE+AFAIYA0+ARtWAJT7AA6U++kUAzjPlHADuAQXwBeTuQA2YAELlucACYB5KMIoM2HLr35DZ4yTPmLVUWaRpb2naHoGCAwkbDS5C5WqelGbbfgATnAw6IHspI6iAFT6grJMAPRxTv62ARhYuARuJp7moprMARzBoeH45PgA1PgAjAEAvgEZmNh47LkeZmqW1sW2pSFh7DT4sQBMTS22me057qZeUD6MAxxD5Z3jsQDM01CNIJQgEAAO2TzIoOSBgRCCAAq3CNzIINKC5ACebyc0gXIYAA1iEAMrkAC2cAAMjgBMhUNJFP9ASDwWcgfCAObIGCBdBwE6KSE4PEEokgbg4qRwACK6Ag8ERyMpACtuAAPME0+mM5lIJFSFEgACO-Lgj3uZzeKAUAFoBMplMcQPjyDgpDinBBIZDyO9pFJVdSoNjacIYPicDR0PBHnBAnCEYLWScABYwSFSADq7pw8G4mLAcDBrwDOAAbgHvu8wNw-iBI4SAJJQJQIGBgsCBHAXYTpsEwb60lnCylne6KH2As7vStwRSBSNwVXwpswKXkbH6ssizGBJvvGjkGhwY0nSvwmA+nBKGDu5AADgADCdguKcMEuz2Da7yycYKPZ-PF0gJid0IoACqj2VCkVwSFjpQZpQw8hm9DduAAMQggT6laOKGnaEAgI0jRAA)

**Input:**

```js
function foo (a, b, c) {
  const newA = calcBasedOnA(a)
  const newB = calcBasedOnB(b)
  const newC = calcBasedOnC(c)

  return (newA * newB) / newC

  
  function calcBasedOnA (a) {
    return a + 1
  }
  
  function calcBasedOnB(b) {
    return b * 2
  }
  
  function calcBasedOnC(c) {
    return c ** 3
  }
}
```

**Output:**

```js
function foo(a, b, c) {
  const newA = calcBasedOnA(a);
  const newB = calcBasedOnB(b);
  const newC = calcBasedOnC(c);

  return (newA * newB) / newC;

  function calcBasedOnA(a) {
    return a + 1;
  }

  function calcBasedOnB(b) {
    return b * 2;
  }

  function calcBasedOnC(c) {
    return c ** 3;
  }
}
```

**Expected behavior:**

```js
function foo(a, b, c) {
  const newA = calcBasedOnA(a);
  const newB = calcBasedOnB(b);
  const newC = calcBasedOnC(c);

  return (newA * newB) / newC;


  function calcBasedOnA(a) {
    return a + 1;
  }

  function calcBasedOnB(b) {
    return b * 2;
  }

  function calcBasedOnC(c) {
    return c ** 3;
  }
}
```

### Reasoning

It is considered good practice to split a long function or a function that touches multiple abstraction layers into small functions. Usually, there are blank lines between code blocks, it is because it simplifies reading them one by one. But in such a case, it is because the code above `return` should be read from top-to-bottom, but the code below `return` has no order and is usually not even the point of interest. So it is beneficial to separate these two types of code visually. 

Also, it gives an immediate distinction between bad-smelling code with very long functions and a well-structured code with a small body with a separation of abstraction layers.

**Comment by sosukesuzuki** [comment]
Sorry, we will probably never support this format. I recommend using comments to improve code visibility.
