### ISSUE TITLE
Support for a global config, which is not used if a local config exists

### ISSUE THREAD

**Issue by vishalnandagopal** [prettier/prettier#15036]
From the [configuration page](https://prettier.io/docs/en/configuration.html) in the official docs,

```
Prettier intentionally doesn’t support any kind of global configuration. This is to make sure that when a project is copied to another computer, Prettier’s behavior stays the same. Otherwise, Prettier wouldn’t be able to guarantee that everybody in a team gets the same consistent results.
```

This could easily be solved by just looking for the global config file after the 7 other methods to find a config file do not succeed. This way, if a project wants to maintain a consistent formatting, it can include a `.prettierrc ` file in it's root directory or any other supported method.

**Expected behavior:**

Prettier searches for a local config file, i.e any of these
![image](https://github.com/prettier/prettier/assets/61023404/3a818132-d25a-4af3-a9e0-6b0fd5bd7be5)
When it does not find any of these files, it looks for a global config file (for example, a config file located at `~/.prettierrc`, and the location could be configurable in the extension settings).

This is useful for solo developers, who do not want to manually add a .prettierrc file to each folder they code in, especially when creating small 1 day/week projects.

**Actual behavior:**
Prettier does not support a global configuration.

**Comment by sosukesuzuki** [comment]
I disagree with this. For example, if you run Prettier on your machine with a global config against another repository that does not have a .prettierrc, you will get a big diff. The fact that "`prettierrc` is not put in a repository" means "using the default settings in that repository".

**Comment by vishalnandagopal** [comment]
> you will get a big diff

I was talking about the use case for solo developers. You can put this behind a setting in an IDE, like VSCode.

If some developer wants to mess up the formatting of a repository that does not use prettier, he can do it easily by adding a prettierrc file and letting prettier format it automatically.

A setting in VSCode that tells prettier to look for a config file in a user folder is what I meant.
