### ISSUE TITLE
Extra comma in `import.meta.glob`

### ISSUE THREAD

**Issue by rbatllet** [prettier/prettier#15031]
I upgraded to version 3.0.0 for a VueJS & Vite project and it generated erroneous code by adding a trailing comma in `import.meta.glob`:

**Input:**

```
async () => {
  try {
    const langList = import.meta.glob(
      "../../node_modules/quasar/lang/(ca|es|en-US).mjs"
    );
    // ...
  } catch (err) {
    console.error(err);
  }
};
```

**Output:**

```async () => {
  try {
    const langList = import.meta.glob(
      "../../node_modules/quasar/lang/(ca|es|en-US).mjs",
    );
   // ...
  } catch (err) {
    console.error(err);
  }
};
```

**Expected behavior:**
```
Do not add a trailing comma in `import.meta.glob` function.
```

**Comment by fisker** [comment]
`import.meta.glob` is not a standard, you should ask vite to support tailing comma.

Also, as I tested, `import.meta.resolve` allows trailing comma.

**Comment by rbatllet** [comment]
In the previous version before 3.0.0 it worked correctly because it did not add a final comma at the end of the parameters of the "import.meta.glob()" function. 

And why do I have to ask Vite to support the final comma if this latest version of Prettier is the reason why it doesn't work anymore ?

It is not a reasonable request at all.

**Comment by fisker** [comment]
In Prettier v2, if you set `{trailingComma: 'all'}`, it will insert commat too. I don't know why nobody complain.

**Comment by rbatllet** [comment]
What is not acceptable is a unilateral change that leaves the project in an inconsistent state. Apparently this version is not backwards compatible and should be.

I'm not asking you to recognize that you have screwed up, but it would cost something to fix that in a reasonable time?

**Comment by kachkaev** [comment]
I am going to close this issue based on @fisker’s reply.

@rbatllet you can choose to stick with Prettier v2 or configure `{trailingComma: 'es5'}` in your Prettier config. You can find more details in [v3 blog post](https://prettier.io/blog/2023/07/05/3.0.0.html#change-the-default-value-for-trailingcomma-to-all-11479httpsgithubcomprettierprettierpull11479-by-fiskerhttpsgithubcomfisker-13143httpsgithubcomprettierprettierpull13143-by-sosukesuzukihttpsgithubcomsosukesuzuki). Please follow the [code of conduct](https://github.com/prettier/prettier/blob/main/CODE_OF_CONDUCT.md) when participating in future discussions.
