### ISSUE TITLE
TypesScript types issue with node with readonly array and `.map`, `.each` on `AstPath`

### ISSUE THREAD

**Issue by timotheeguerin** [prettier/prettier#15034]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via:  n/a / TypeScript
- Runtime:  Node v18.16.0, Typescript 5.1
- Operating System:  MacOS
- Prettier plugins (if any):  Issue happen when writing a plugin 

Typescript produce an error when trying to use `.map` for a property that is a readonly array.

**Steps to reproduce:**

Using the following typescript code will produce an error when trying to `.map` a property that is a readonly array(same for `.each`)

```ts
import { AstPath } from "prettier";

interface TestNode {
  regularArray: string[];
  readonlyArray: readonly string[];
}

const path: AstPath<TestNode> = undefined as any;

// Works fine
path.map(() => "", "regularArray");
// Ts error
path.map(() => "", "readonlyArray");
//                 ^ Argument of type '"readonlyArray"' is not assignable to parameter of type '"regularArray"'.ts(2345)
```

**Expected behavior:**
Should not be any difference between a readonly and regular array.

**Actual behavior:**
Typescript produce an error when trying to use `.map` for a property that is a readonly array.
<img width="952" alt="image" src="https://github.com/prettier/prettier/assets/1031227/bd98e954-2609-4ed5-92c1-71564c207f66">

**Comment by auvred** [comment]
It guess that to fix this issue it is enough to add `readonly` here:

https://github.com/prettier/prettier/blob/6e5dee0a0154b03a9a3318b41603c8abc9c565b7/src/index.d.ts#L36

```tsx
type ArrayProperties<T> = { 
   [K in keyof T]: NonNullable<T[K]> extends readonly any[] ? K : never; 
 }[keyof T];  //                               ^ here
 ```

[TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAksECcAKCD2kHAJYQM4B4AVAPigF4pCoIAPeAOwBNcoBDekAbQF0AoKKAH5YTWinSJseIsX5QAXFACCCBKxDiMUgiQDcvXqEjLV6zZJw7SFAN5zOAaShZ6UANYQQqAGaVuigDlUegCAVwAbcNYAI3CIIkduUloGZigECFZGYPCQNg4eISgnRXoIADdEfQBfTg8vX0JuXSgAelaBTq7unt7OgD0oAAtECAMjaBhRGnNMSyJqOggmFhsoOPoAc2Ah0tCAW2jEKGrrWFxCULA4mUXUlmAEULGBYQBRGgBjcNDGeKRWHNWOEZJwAEQbbZDMHcAA0lHBkJ2MNkAj2hyq43AkwuVxuJHIlDuyzSPDkwkezzkiioKRJLE4Lm8xwAYlgELhgPCAHS8pnHABKEH2rBcfFe50u13iQpFLlRCig3mBuAg+gMvBc8AQys+0CUnIBOwWFHYIFIdgEIrA+AAqvCkABGYkrWDa2baGTEAAUcgEn2B4WirE+bkU3oAlORSGbYX6oGA0GBHYonXGBBHFLaeDUNVrELroIQ8MAgn8oJb0hBNhFASo1CBFJyEC5Njm5BksjkQPX1IpO9l6LkoM3W+3qgZPsFOQnWDtFAbgEahkQS2WIGdQqJvC4IIw2Cwzer2lAAOqoBBuFg7sq8MBzobc63eyPRqBgsHwsEZGtRBC9kAwQjfQTyCAB3KAwIvK8lV3KBgFQVA7wfJ9WDAF8ozIUgPy-AduwAoDdCAA)

If this is correct, I can submit a PR

**Comment by timotheeguerin** [comment]
yeah, i copied the types after and adding that `readonly` works, though got into some very bad performance issue in the IDE. Not sure if that was related or due to something else at the same time
