### ISSUE TITLE
Should --list-different return exit code 1 if it finds differences?

### ISSUE THREAD

**Issue by wdhorton** [prettier/prettier#1504]
I'm trying to add `prettier` to an existing pre-commit hook, using `--list-different` (very similar to the example in the documentation). However, the script already has `set -o errexit` at the top, so that it will exit if it encounters an error, rather than committing. This means that, even though `--list-different` gets the correct output, the script can't proceed past that line because it sets the exit code to 1.

My question is, if the point of the `--list-different` option is to find the files that would be different, does it make sense for `prettier` to set an error exit code when it finds those files?

**Comment by bakkot** [comment]
I think so, by analogy to `diff`.

**Comment by wdhorton** [comment]
Fair point, but on the other hand, `git diff` doesn't behave that way (unless you use the `--exit-code` flag to make it behave like `diff`).

**Comment by vjeux** [comment]
This is modeled after the same command in gofmt which returns non zero error code when there is a difference.

**Comment by micahstubbs** [comment]
wondered about this too 🤔
