### ISSUE TITLE
prettier 3.0.0 stable version does not work

### ISSUE THREAD

**Issue by MrOxMasTer** [prettier/prettier#15062]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
{
  	"useTabs": false,
  	"trailingComma": "all",
  	"tabWidth": 4,
  	"semi": true,
  	"singleQuote": true,
  	"endOfLine": "lf",
  	"printWidth": 80,
  	"bracketSameLine": true,
  	"plugins": ["prettier-plugin-tailwindcss"]
}
```

**Input:**

after upgrading to the latest STABLE version, prettier simply refuses to work in any way.  I have an extension installed in vs code and an additional library for tailwind installed.  The only thing that helps me solve the problem so that it starts formatting again is deleting the content from the file .prettierrc.json, but how would I need my settings.

```jsx

const Header = () => (
    <header>
        <div className="container pb-[30px] pt-8">
            <div className="flex justify-between border-b border-solid border-silver "><h1 className="visually-hidden">eatly</h1>
                <Logo />
                <span />
            </div>
        </div>
    </header>
);

```

And another question is, can prettier work without a plugin in vs code? If not, why not?

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

formatting

**Comment by MrOxMasTer** [comment]
Working version: 2.8.8.
![image](https://github.com/prettier/prettier/assets/59291123/fb371d1e-3617-4f0d-9f69-8b1a71974cde)
![image](https://github.com/prettier/prettier/assets/59291123/ed9c0e66-7849-4a98-b31e-261ecaf1e6be)

**Comment by sosukesuzuki** [comment]
Yes, prettier-plugin-tailwindcss does not support Prettier v3. https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176

**Comment by MrOxMasTer** [comment]
> Yes, prettier-plugin-tailwindcss does not support Prettier v3. [tailwindlabs/prettier-plugin-tailwindcss#176](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176)



> Yes, prettier-plugin-tailwindcss does not support Prettier v3. [tailwindlabs/prettier-plugin-tailwindcss#176](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176)

what's the difference. Prettier doesn't work for me at all, even if I remove the plugin

**Comment by MrOxMasTer** [comment]
> Yes, prettier-plugin-tailwindcss does not support Prettier v3. [tailwindlabs/prettier-plugin-tailwindcss#176](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176)

if I remove the plugin from the config, then prettier won't work for me anyway and it won't format even jsx

**Comment by sosukesuzuki** [comment]
Can you show us more detailed log?

**Comment by MrOxMasTer** [comment]
> Можете ли вы показать нам более подробный журнал? Какое сообщение об ошибке появляется в результате выполнения `prettier` команды?

I use formatting when saving and I don't get any errors

**Comment by MrOxMasTer** [comment]
It's just that when I try to format, I don't get any errors. It just doesn't work. Of course, I can throw off the vs code logs, but there are too many files there and I do not know which ones will be useful and which ones will not

**Comment by sosukesuzuki** [comment]
Most likely a problem with https://github.com/prettierprettier-vscode . If I disable the plugin and reload the VSCode, does the same problem occur?

**Comment by MrOxMasTer** [comment]
> Most likely a problem with https://github.com/prettierprettier-vscode . If I disable the plugin and reload the VSCode, does the same problem occur?

prettier doesn't work for me at all without the vs code plugin

**Comment by MrOxMasTer** [comment]
And it's like it should work without vs code extensions at all? It's just that when I installed it, it didn't work at all no matter how hard I tried

**Comment by sosukesuzuki** [comment]
Sorry, I mean plugin is `prettier-plugin-tailwindcss`

**Comment by sosukesuzuki** [comment]
Also, can you show output from Prettier in VSCode? Post it here and it will help us solve the problem.

<img width="889" alt="スクリーンショット 2023-07-09 17 15 31" src="https://github.com/prettier/prettier/assets/14838850/eee4f30f-57ee-4e8f-9bd8-4999844864ba">

**Comment by MrOxMasTer** [comment]
I removed the plugin from the configuration and it didn't help. It helps if I completely clear the config file

**Comment by MrOxMasTer** [comment]
Okay, now I'll recreate the situation and show

**Comment by MrOxMasTer** [comment]
![image](https://github.com/prettier/prettier/assets/59291123/f71c9286-f63d-4f0d-b566-fa0beaaf0b84)
![image](https://github.com/prettier/prettier/assets/59291123/a22ac036-35ed-44fd-a023-e8d05b106b3a)
![image](https://github.com/prettier/prettier/assets/59291123/0ec525d1-8e2d-485b-991a-24b8d963bbb3)

This is the first situation, well, it's clear why it doesn't work

**Comment by sosukesuzuki** [comment]
Hmmm, sorry. I couldn't tell from that information alone. If you can create a repository where we can reproduce it, we may be able to investigate.

**Comment by MrOxMasTer** [comment]
![image](https://github.com/prettier/prettier/assets/59291123/9aec2d72-8cd2-4872-8048-62b29ce683a3)
![image](https://github.com/prettier/prettier/assets/59291123/2cacb0dc-70d3-4569-b437-9e4eb1999ca3)

mmm. This is strange. It didn't work before. Now it works without a plugin in the configuration. Sorry for misleading you. 
But I have another problem with prettier. You don't know why prettier can sometimes think very long before formatting. A window appears on the bottom left and says that formatting is in progress? Moreover, the bigger the project, the longer he thinks. I'm trying to catch this window now, but it's not working yet

**Comment by MrOxMasTer** [comment]
![image](https://github.com/prettier/prettier/assets/59291123/ea6ae986-c1e9-41c6-8cde-cec942e062ae)

Here is such a window appears. Sometimes it just takes a long time to load. I understand that maybe my laptop is not very powerful, but simple, why not make prettier, which can be said to be an npm package, and not dependent on the extension in vs code
