### ISSUE TITLE
Plugin is not automatically loaded from `node_modules`

### ISSUE THREAD

**Issue by Janther** [prettier/prettier#15061]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: CLI
- Runtime: Node 20
- Operating System: macOS
- Prettier plugins (if any): prettier-plugin-solidity

**Steps to reproduce:**

1. clone [https://github.com/pcaversaccio/create-util](https://github.com/pcaversaccio/create-util)
2. update to prettier 3.0.0 and run `npm install`
3. `npm run prettier:check`

**Expected behavior:**

The plugin should be loaded and the parser inferred.

**Actual behavior:**

there's an error `No parser could be inferred for file "/create-util/contracts/Create.sol".`

**Current Workaround:**

if there's a configuration file naming the plugin, prettier loads it.

`.prettierrc.yml`
```YML
plugins:
  - "prettier-plugin-solidity"
```

related to https://github.com/prettier-solidity/prettier-plugin-solidity/issues/881

**Comment by sosukesuzuki** [comment]
Yes, plugin auto search has been removed https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker
