### ISSUE TITLE
Plugin migration guide broken links

### ISSUE THREAD

**Issue by Gudahtt** [prettier/prettier#15074]
The Prettier v3 plugin migration guide ([here](https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F)) has broken links. They all reference the `next` branch, which no longer exists.

**Comment by fisker** [comment]
Fixed.  https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F
