### ISSUE TITLE
[v3] plugins declared in `.prettierrc` are not loaded on directory

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#15079]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via:  CLI
- Runtime:  v18.16.0
- Operating System:  Linux
- Prettier plugins (if any):  prettier-plugin-sh

**Steps to reproduce:**

https://github.com/un-ts/prettier/issues/273#issuecomment-1629109603

**Expected behavior:**

Like prettier v2, `.sh` files should be checked

**Actual behavior:**

`.sh` files are not checked

---

After debugging, `getSupportedFilesGlob` here https://github.com/prettier/prettier/blob/79d8a3983842d1d8a077f177ed8b983c1c596088/src/cli/expand-patterns.js#L130-L145
does not resolve `.sh` files correctly.

**Comment by fisker** [comment]
It's a known issue, are you sure it works in v2?

**Comment by JounQin** [comment]
@fisker I tried @devcrev's reproduction at https://github.com/devcrev/p-sh-old, it works on v2.

```log
> p-sh-old@1.0.0 format
> prettier --check .

Checking formatting...
[warn] level-0/go.sh
[warn] level-0/hello.sh
[warn] level-0/level-1/another.sh
[warn] level-0/level-1/library.js
[warn] level-0/level-1/runme.sh
[warn] level-0/program.js
[warn] Code style issues found in 6 files. Forgot to run Prettier?
```

**Comment by JounQin** [comment]
Could be related to ***Plugin search feature has been removed***?

**Comment by tylervz** [comment]
I am having this same issue with the `.xml` files and `.properties` files in my project. I'm using [plugin-xml](https://github.com/prettier/plugin-xml) version 3.1.0 and the latest commit of[ prettier-plugin-properties](https://github.com/eemeli/prettier-plugin-properties) (`npm install -D git@github.com:eemeli/prettier-plugin-properties.git#0c7072dae2006c0d0a588f70b19940390a50add1`)

**Comment by Jeto143** [comment]
I've noticed that you now need to specify something like `**/*.*` to the CLI command in order to parse files that have been registered by a plugin declared in the prettier configuration file. This wasn't the case with 2.*. It might be related to https://github.com/prettier/prettier/pull/14759, as @JounQin pointed out.

Related: https://github.com/shufo/prettier-plugin-blade/issues/213

**Comment by devcrev** [comment]
The documented behavior seems to indicate that the behavior should be as it was in version 2.

![image](https://github.com/prettier/prettier/assets/44066444/8265801a-6176-4c33-90f5-dc758cc0007a)

**Comment by devcrev** [comment]
This `package.json` script for v3 does what I want and what v2 did with `prettier . --check`:

 ```
 "scripts": {
    "format": "prettier './**/*' --check --ignore-unknown"
  },
```

**Comment by thorn0** [comment]
@dummdidumm Indeed. Config files are resolved for each processed file, which is too late.

**Comment by sdellysse** [comment]
Just chiming in that I was just bit by this trying to get `.sh` files to be formatted with `prettier-plugin-sh`. I have to do `prettier --plugin=prettier-plugin-sh .` to get it working. I'm willing to take a stab at fixing this, but I have no knowledge of the codebase. Would anyone have any pointers as to where to start debugging this issue?

**Comment by sosukesuzuki** [comment]
@sdellysse I'm working on this, please wait. https://github.com/prettier/prettier/pull/15433
