### ISSUE TITLE
[v3] [error] Cannot find package plugin-name imported from /.../root-project/noop.js

### ISSUE THREAD

**Issue by vighnesh153** [prettier/prettier#15085]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: CLI
- Runtime: Node.js v18
- Operating System: macOS
- Prettier plugins (if any): prettier-plugin-tailwindcss

**Steps to reproduce:**

Minimal reproducible repo: https://github.com/vighnesh153/prettier-unable-to-find-pkg

* Install deps
```sh
# Install in prettier-config directory
cd prettier-config && npm install
cd ..
# Install in root directory
npm install
```
* Run `npx prettier --write .` from the root directory

Checked with the plugin's project and they suspect the issue is with prettier v3: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176#issuecomment-1631094080

**Expected behavior:**
Prettier should work without throwing the following error as this works with `v2.8.8`

**Actual behavior:**
```
[error] Cannot find package 'prettier-plugin-tailwindcss' imported from /.../prettier-unable-to-find-pkg/noop.js
```

**Comment by fisker** [comment]
As I tested, this doesn't work in v2.

The plugin should be resolvable from your `CWD`, or related to the prettier config file, which is `./package.json` in your case.

**Comment by vighnesh153** [comment]
Sorry, this seems to be working in v2. Have pushed a v2 branch to help reproduce.

https://github.com/vighnesh153/prettier-unable-to-find-pkg/tree/v2

Please delete `node_modules` and `package-lock.json` in both directories before running `npm install`.

**Comment by fisker** [comment]
You are right, your v2 branch works, but I don't know why. There should be something to do with npm.

v2
```console
$ ls node_modules/
prettier  prettier-config  prettier-plugin-tailwindcss
```

main

```console
$  ls node_modules/
prettier  prettier-config
```

**Comment by fisker** [comment]
Just to be clear, we didn't export this case work in v2, we can't expect a transitive dependency to be solved, it just happened works somehow. 

I don't think we will do anything, you can use one of the following js config 

```js
plugins:[
  require.resolve("prettier-plugin-tailwindcss")
]
```

```js
plugins:[
  import.meta.resolve("prettier-plugin-tailwindcss")
]
```

```js
plugins:[
  require("prettier-plugin-tailwindcss")
]
```

```js
plugins:[
  await import("prettier-plugin-tailwindcss")
]
```

**Comment by anentropic** [comment]
I had to fork a plugin and install it from github 

then I started getting this error `Cannot find package '<myproject>/node_modules/<prettier plugin/' imported from <myproject>/noop.js`

`<myproject>/noop.js` doesn't exist

I had a `.prettierrc` that just imported the plugin by name, but doesn't work now that the package comes from github.

I tried deleting node_modules and package-lock.json and reinstalling

I tried changing to a `prettier.config.js` file and the various `plugins` imports styles listed in comment above but I get errors for each:

- `require is not defined in ES module scope, you can use import instead`
- `(intermediate value).resolve is not a function`
- `require is not defined in ES module scope, you can use import instead`
- `Cannot find package '<myproject>/prettier.config.js`

I have `"prettier": "3.3.1"` in my devDependencies

I am running as `npx prettier --write` (this used to work before forking the plugin and installing it from github)

I can't follow all the inconclusive issue threads - is this something that's expected to work and has a fix?

**Comment by anentropic** [comment]
there's this https://github.com/prettier/prettier/issues/8474 marked resolved and locked but I can't tell what I'm supposed to do

**Comment by Vrajs16** [comment]
The solution @fisker posted is what I used to fix this issue. If you have a .prettierrc file change it to a .prettierrc.js file and in the plugin section use `require.resolve("prettier-plugin-tailwindcss")`, after this I didn't face this issue. Thanks @fisker.

**Comment by mauriciocrecencio** [comment]
> Just to be clear, we didn't expect this case work in v2, we can't guarantee a transitive dependency to be solved, it just happened works somehow.
> 
> I don't think we will do anything, you can use one of the following js config
> 
> ```js
> plugins:[
>   require.resolve("prettier-plugin-tailwindcss")
> ]
> ```
> 
> ```js
> plugins:[
>   import.meta.resolve("prettier-plugin-tailwindcss")
> ]
> ```
> 
> ```js
> plugins:[
>   require("prettier-plugin-tailwindcss")
> ]
> ```
> 
> ```js
> plugins:[
>   await import("prettier-plugin-tailwindcss")
> ]
> ```

This solution worked for me on my new project, thank you very much!
A curious fact, I was having this problem on an old project and I didn't go away to find a solution in the moment, but suddenly the problem disappeared after a while

**Comment by D-Mass-RR** [comment]
```rm -rf node_modules yarn.lock ```

```yarn```  

works for me


my prettier version:
```
{
    "prettier": "^3.4.2",
}
```
