### ISSUE TITLE
[v3] Embed now called recursively at the start instead of each time before print

### ISSUE THREAD

**Issue by dummdidumm** [prettier/prettier#15093]
I'm currently migrating `prettier-plugin-svelte` to Prettier version v3. After some headscratching I realized that in Prettier v3, the call behavior of `embed` has changed. In Prettier v2, the calls to embed and print were alternating: For each node, first call embed, and if that does not return something, then call print. In Prettier v3, the whole AST is first traversed to find embeds - in other words, `embed` is called recursively on the AST. Only after that, `print` is called.

My question: Why was this changed? This seems wasteful from a computation perspective because in contrast to `print` where I can determine explictly which property on the AST to invoke next, `embed` will traverse all properties of the AST. There's the new API `getVisitorKeys` which can help here but it feels duplicative to do this.

This should also be noted as a breaking change in the changelog, as a plugin may rely on the previous alternating behavior - `prettier-plugin-svelte` for example added some meta info on the AST which `embed` would retrieve at a later stage. That meta info adding now has to move to `embed`.

**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: CLI
- Runtime: Node 16
- Operating System: Windows
- Prettier plugins (if any): prettier-plugin-svelte

**Steps to reproduce:**

Run tests in https://github.com/sveltejs/prettier-plugin-svelte/pull/365

**Expected behavior:**

Call order is embed->print->embed->print etc

**Actual behavior:**

Call order is embed->embed->embed->... until everything's traversed, then print

**Comment by fisker** [comment]
The links in this comment are the whole story. https://github.com/prettier/prettier/issues/15080#issuecomment-1630969910

**Comment by fisker** [comment]
> My question: Why was this changed? 

To support async parser, if we do embed->print->embed->print, `embed` and `print` has to be async, and this caused performance issue, so we only make `embed` async by traverse AST before `print`.

**Comment by dummdidumm** [comment]
Thanks for the quick reply - I take this as a "works as designed" and not as an accidental change, so I need to adjust the plugin. Leaving this open because I think this needs to be mentioned in the list of breaking changes.

**Comment by fisker** [comment]
It's mentioned in blog post. https://prettier.io/blog/2023/07/05/3.0.0.html#api-1

**Comment by thorn0** [comment]
The old order of calls wasn't documented either. Relying on such implementation details is on own risk.

**Comment by sosukesuzuki** [comment]
I agree with thorn0. If you find a bug please open other issue.
