### ISSUE TITLE
--print-width should be applied to long comments

### ISSUE THREAD

**Issue by joeltine** [prettier/prettier#15097]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAKgCwJYDOGhGAhhgDbQDmleUcANJTXAE4Yw6lQYAcABgxhubIgDMIHAgFc2cAHQYAynDgYcEAO4sotLiQr11hZnhgByInAAeMeQFs4FAJ67qCgDpRxMqGBg8aAwACWcqAHUpCgATAApgank4QL0MAF4MTxAccIhs5iS1eBiMjAtsqLZY7ItmAjwKBBgy8VIKAiYMaABZCBlOgHkAN3ZGAF8ASgxgb29xkEYQCAAHQOgCZFBSNjZtAAUdhE2Udq1SF02lgCM2UjAAaxTlUicAGWNkNo6mEFv7p4wZQre70ajIewyX6dBx4CFsKFLBp6JoARRkEHgX3anSWACsCDZlGC0RisUhvriQABHMlwfZ7FYnECkAgAWgYcBiXMWIHspEaYIAwhAHA5SMgWRQKLzkdQmgBBGD2PDXGTwfbsD4MbE-JY4GAOCgRfDwAggsBwVRQBqBYbmFySsAEK4gYZQgCSUG5sGUYDYeDWCu9yhgLiauqpKz2nQidxWkujcE6bFGvPoKZgDNI1HFkd+ILE7El11I12cvOj9BgETwMS4yEES3ktLw8mzuYlFJxvxgZdr9ZwyAATEsBnAsGWTpTfnAHOWYtyYm8eNQZDm4AAxKTi5VgyWkdUQEDjcZAA)

```sh
--parser babel
```

**Input:**

```jsx
// This is a long line, longer than 80 chars for sure. See how long this line is, it's extremely long.
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

}
```

**Output:**

```jsx
// This is a long line, longer than 80 chars for sure. See how long this line is, it's extremely long.
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver,
}) {}

```

**Expected behavior:**

The long comment above HelloWorld should be wrapped to 80 (same as --print-width). This should also hold true for multi-block comments using `/** */`.

**Comment by auvred** [comment]
Hi, prettier [doesn't break comments](https://prettier.io/docs/en/rationale.html#:~:text=There%20are%20some%20edge%20cases%2C%20such%20as%20really%20long%20string%20literals%2C%20regexps%2C%20comments%20and%20variable%20names%2C%20which%20cannot%20be%20broken%20across%20lines%20(without%20using%20code%20transforms%20which%20Prettier%20doesn%E2%80%99t%20do)). You can read more about this [here](https://prettier.io/docs/en/rationale.html#comments) and [here](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about:~:text=as%20breaking%20changes.-,What%20Prettier%20is%20not%20concerned%20about,-Prettier%20only%20prints)

But if you want, you can use this plugin for jsdoc comments formatting: [prettier-plugin-jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc)

**Comment by joeltine** [comment]
Ah. So just for a little more context, our organization recently made the switch for our whole code base to use Prettier by default. This was one of the functionalities our previous formatter (clang-format) handled quite nicely.

**Comment by kachkaev** [comment]
Thanks for your reply @auvred!

@joeltine you can search for other (ESLint plugins?) tools that would split the comments for you. This is out of scope for Prettier.
