### ISSUE TITLE
!DOCTYPE is forced to lowercase

### ISSUE THREAD

**Issue by yoyo837** [prettier/prettier#15096]
**Prettier 3.0.0**

```js
module.exports = {
  semi: true,
  singleQuote: true,
  singleAttributePerLine: true,
  trailingComma: 'es5',
  printWidth: 120,
  arrowParens: 'avoid',
  endOfLine: 'lf',
  overrides: [
    {
      files: '.prettierrc',
      options: { parser: 'json' },
    },
  ],
};

```

**Input:**

```html
<!DOCTYPE html>
<html
  lang="zh-Hans"
  translate="no"
>
  <head> </head>

  <body></body>
</html>

```

**Output:**

```html
<!doctype html>
<html
  lang="zh-Hans"
  translate="no"
>
  <head> </head>

  <body></body>
</html>

```

**Expected behavior:**

Please do not modify the `DOCTYPE`.

**Comment by sosukesuzuki** [comment]
What is the problem with this behavior?

**Comment by yoyo837** [comment]
> What is the problem with this behavior?

Thanks for your reply. Personally I want it to stay uppercase regardless of the standard, how do I control it from being converted to lowercase by `prettier`?

**Comment by kachkaev** [comment]
> I want it to stay uppercase regardless of the standard

Why? What breaks if you don’t?

**Comment by sosukesuzuki** [comment]
We have no way to disable lowercasing for HTML doctype. If you can show us specific use cases where this is a problem, rather than a matter of preference, we may be able to do something about it.

**Comment by yoyo837** [comment]
Ok, Thanks for the reply, it's just a personal preference.

**Comment by stefanroelofs** [comment]
Unfortunately I think that my IDE breaks with lowercase doctype declaration 😞 
I have to use [VisiWin7 ](https://www.inosoft.com/en/), and I guess it has some XML parser:

![image](https://github.com/prettier/prettier/assets/37924749/2ab1c5c1-9d74-44df-be46-c44e54e6cf87)

I will revert to using Prettier version 2.8.8. 

Thank you.

**Comment by yoyo837** [comment]
So, as @stefanroelofs said, can we now say, is this a breaking change?

**Comment by CrazyStevenz** [comment]
@yoyo837 With all due respect but prettier doesn't care what your personal preference is as it's an enforcement of standards. If you really want the previous behavior, add  above the html line, or, if you don't like the standard, remove prettier from you project.

@stefanroelofs Parsing html with an xml parser is an issue on the VisiWin7 side and you should report the issue to them instead.

**Comment by glen-84** [comment]
The [standard](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype) uses uppercase. [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Doctype) uses uppercase. Prettier used uppercase.

What was the motivation for changing this? Voting was just 11-5 – there are issues with 643-23 voting that haven't even made it in.

Where was the consensus? Did you run a community poll on Twitter or similar?

Bizarre.

**Comment by JosephMing** [comment]
<img width="1586" alt="image" src="https://github.com/prettier/prettier/assets/31059354/af320b8f-2b8d-40f1-8b14-56583f770bfa">
<img width="1592" alt="image" src="https://github.com/prettier/prettier/assets/31059354/e2b22f1f-39a8-4e0f-afff-0077ec47d740">

**Comment by JosephMing** [comment]
May I ask what was the intention behind the change made?

**Comment by fisker** [comment]
Check the original issue #6502,  https://github.com/prettier/prettier/issues/6502#issuecomment-533840708

**Comment by glen-84** [comment]
@fisker,

So it was changed because:

- It "slightly improves GZIP compression" (a few bytes)
- "That's what Bootstrap and h5bp do"

Seriously?

And now:

- It diverges from the spec examples, MDN, etc.
- It potentially breaks some editors/tools. ([ref 1](https://github.com/twbs/bootstrap/pull/29363#issuecomment-527390135), [ref 2](https://github.com/prettier/prettier/issues/15096#issuecomment-1641783877))
- It makes the document incompatible with XHTML.
- It requires every user of Prettier+HTML to make code changes, for almost no benefit.

... all for a 4-year-old issue with (12 - 7) 5 up-votes.

Bizarre.

**Comment by eligrey** [comment]
This change broke my XHTML pages

**Comment by eligrey** [comment]
@sosukesuzuki this change broke all of my XHTML pages as lowercase DOCTYPE is invalid XML

**Comment by sosukesuzuki** [comment]
Prettier doesn't support XHTML.

**Comment by Psypher1** [comment]
> ~Prettier doesn't support XHTML.~ Sorry, I misunderstood. It may be better not to apply this to *.xhtml.

I would prefer a config option to turn this behaviour on/off, because I can't be refactoring my project over this
