### ISSUE TITLE
ENOTDIR when using yarn 3

### ISSUE THREAD

**Issue by commscheck** [prettier/prettier#15119]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: `yarn prettier`
- Runtime: Node.js v18.16.1
- Operating System: macOS
- Prettier plugins (if any): none

**Steps to reproduce:**

```bash
# Enable yarn 3:
# https://yarnpkg.com/getting-started/install
corepack enable
corepack prepare yarn@stable --activate

# Create a new project:
yarn init -2

# Install prettier:
yarn add --dev --exact prettier

# Ignore generated files:
cat > .prettierignore << EOL
.yarn/*
.pnp.cjs
yarn.lock
EOL

# Run prettier:
yarn prettier .
```

**Expected behavior:**

Prettier commands succeed.

**Actual behavior:**

All prettier commands fail with the following output:

```
❯ yarn prettier .
node:fs:1615
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, stat '/Users/ben/src/prettier-test/.yarn/cache/prettier-npm-3.0.0-7ffbcce680-6a832876a1.zip/node_modules/prettier/internal/cli.mjs'
    at statSync (node:fs:1615:3)
    at tryStatSync (node:internal/modules/esm/resolve:176:13)
    at finalizeResolution (node:internal/modules/esm/resolve:316:17)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1188:29) {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Users/ben/src/prettier-test/.yarn/cache/prettier-npm-3.0.0-7ffbcce680-6a832876a1.zip/node_modules/prettier/internal/cli.mjs'
}

Node.js v18.16.1
```

**Comment by commscheck** [comment]
Confirmed the issue doesn't happen in prettier v2.8.8.

**Comment by so1ve** [comment]
Maybe add `preferUnplugged` to prettier's package.json will solve thisissuy?

**Comment by fisker** [comment]
Any documation link for `preferUnplugged`?

**Comment by so1ve** [comment]
@fisker Here you are:

https://yarnpkg.com/configuration/manifest#preferUnplugged

https://github.com/evanw/esbuild/issues/2523

**Comment by fisker** [comment]
Your suggestion make sense.

> Maybe add `preferUnplugged` to prettier's package.json will solve this issue?

**Comment by fisker** [comment]
Maybe we can remove this line too

https://github.com/prettier/prettier/blob/24dfe5afe768b627f09484426b26fca764251225/tests/config/install-prettier.js#L68

**Comment by fisker** [comment]
@commscheck I tried your steps to reproduce, but it didn't work on my machine. Can you test #15169 with this install command?

```sh
yarn add --dev prettier@fisker/prettier#preferUnplugged
````

**Comment by vajahath** [comment]
```
  "devDependencies": {
   ...
    "prettier": "fisker/prettier#preferUnplugged",
    "typescript": "^5.1.6",
    ...
  },
```
![image](https://github.com/prettier/prettier/assets/12165822/fbabb3f3-1445-44b9-84f5-253cf7d751be)

@fisker This works for me. (Ubuntu 22)

**Comment by fisker** [comment]
Thank you!

**Comment by commscheck** [comment]
> Can you test https://github.com/prettier/prettier/pull/15169 with this install command?

@fisker working for me too, thanks for the fix!
