### ISSUE TITLE
new call(await x) over-parenthesis

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1512]
```js
async () => new call(await x);
```

outputs

```js
async () => new call((await x));
```

Note that CallExpression is fine. cc @bakkot, I think you tweaked this recently.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22async%20()%20%3D%3E%20new%20call(await%20x)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by m1ckm** [comment]
Is that ok before I exit from it.

**Comment by m1ckm** [comment]
??

**Comment by bakkot** [comment]
Don't think I've touched this in a while, but it's a quick fix anyway.
