### ISSUE TITLE
`getVisitorKeys` not part of type definitions

### ISSUE THREAD

**Issue by dummdidumm** [prettier/prettier#15121]
`getVisitorKeys` is not part of the Prettier type definitions.

**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: Node
- Runtime: Node 16
- Operating System: Windows

**Steps to reproduce:**

```ts
import { Printer } from 'prettier';

export const printers: Record<string, Printer> = {
    'my-printer': {
        print: null as any,
        embed: null as any,
        getVisitorKeys: null as any,
    },
};
```

**Expected behavior:**

`getVisitorKeys` should be part of the type definitions

**Actual behavior:**

Code snippet errors because `getVisitorKeys` is missing

**Comment by fisker** [comment]
PR welcome.
