### ISSUE TITLE
Unexpected formatting in version 3.0.0

### ISSUE THREAD

**Issue by always-awake** [prettier/prettier#15128]
Hello.
I couldn't find the rule related to the changes mentioned below in the release notes for version 3.0.0. 
(Just for your information, I use JavaScript and TypeScript, so I reviewed the changes in the JavaScript and TypeScript sections only.)
Could it be that there is a rule I missed or that the changes occurred as a side effect of another rule?
 

#### Environments:

Prettier Version: 3.0.0
Running Prettier via: prettier '**/*.{js,ts,tsx}' --write
Runtime: Node.js v18.12.0
Operating System: macOS
Prettier plugins (if any): none

**Input:**

```jsx
// input 1
res?.writeHead(302, {
    Location: url,
}).end();

// input 2
res.writeHead(302, {
    Location: url,
}).end();
```

**Output:**

```jsx
// input 1 - prettier 2.8
res?.writeHead(302, {
    Location: url,
}).end();

// input1 - prettier 3.0
res
    ?.writeHead(redirectCode, {
        Location: url,
    })
    .end();
    
// input2 - prettier 2.8, 3.0
res.writeHead(302, {
    Location: url,
}).end();
```

**Expected behavior:**
```js
// input1
res?.writeHead(302, {
    Location: url,
}).end();
```

**Comment by thorn0** [comment]
Can't reproduce. 2.8.8 and 3.0.0 format this code the same way:
```
d:\dev\prettier-test>npx prettier@2.8.8 test.js
// input 1
res
  ?.writeHead(302, {
    Location: url,
  })
  .end();

// input 2
res
  .writeHead(302, {
    Location: url,
  })
  .end();

d:\dev\prettier-test>npx prettier@3.0.0 test.js
// input 1
res
  ?.writeHead(302, {
    Location: url,
  })
  .end();

// input 2
res
  .writeHead(302, {
    Location: url,
  })
  .end();
```

**Comment by always-awake** [comment]
First of all, I apologize for causing confusion by providing only a partial code snippet 🙏
I suspect that the current issue may be related to the `file extension`. 
Here is the additional test code I performed for your reference.

### Test 1 (testJs.js)
```js
// testJs.js
export default function foo(res, url) {
    res?.writeHead(302, {
        Location: url,
    }).end();
}

```

➜  npx prettier@2.8.8 testJs.js  
```js
export default function foo(res, url) {
    res?.writeHead(302, {
        Location: url,
    }).end();
}
```
➜  npx prettier@3.0.0 testJs.js
```js
export default function foo(res, url) {
    res?.writeHead(302, {
        Location: url,
    }).end();
}
```
### Test 2 (testTs.ts)
```ts
// testTs.js
export default function foo(res, url) {
    res?.writeHead(302, {
        Location: url,
    }).end();
}

```

➜  npx prettier@2.8.8 testTs.ts  
```ts
export default function foo(res, url) {
    res?.writeHead(302, {
        Location: url,
    }).end();
}
```
➜ npx prettier@3.0.0 testTs.ts
```ts
export default function foo(res, url) {
    res
        ?.writeHead(302, {
            Location: url,
        })
        .end();
}
```
