### ISSUE TITLE
Revert `DOCTYPE` tag case

### ISSUE THREAD

**Issue by cesalazar** [prettier/prettier#15137]
Please consider keeping the `DOCTYPE` uppercase as it was in `prettier < 3`.

**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAiHMo5cmzhcAJmIkTUNODC7kwlLgCcAzisEgArjABmAWgAcQ8gHp5km5WlyWE15IBGEGQE97imQBLADdyQJkDLQgIGFFUGyDg+3ivXzF49kYQABoQCAAHGEDoHWRQbSiAd2JtBFKULjpKrh9S3I8tLjAAaxUAZS5lABlAqDhkE0a9ds6e-vyu0d5kGC1DOFy9GkCVtY2QHSW6OABFQxjxpEm6aZAAKx0ADz6j0-P4Can9gEd3uGIovl6iAuDozGM4DJITkQKsuIE6EtcBAaDQuMgQXQ6DDDnxjgBBGCrQIeYz-OBaEZjT43faZADqlEC8B0CzAcD6dWZIWZPgxYB0bRAwXWAEkoFDYH0wFpAoV8RK+jAfMcabd8lE9PTOvkMRq4HotMFxrlRoaYACuLw0Wr9gtdBSMZkYRrRjB6eEYJRkBYAAy5LRwX6BQOW63oq5fXKqDwemRe5AAJlyhj0+C4Hnq11ucBoHkhUJkQx4vEMVrgADEIFo0USlhiuMYICAAL4toA)

```sh
# Options (if any):
--write
```

**Input:**

```html
<!DOCTYPE html>
```

**Output:**

```html
<!doctype html>
```

**Expected behavior:**

The tag `DOCTYPE` is kept uppercase as it used to be in prettier v2, and as referenced in [the specification](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype). I understand this tag is case-insensitive, but this issue is about sticking to naming conventions and to avoid unnecessary noise in PRs after bumping prettier and formatting files.

**Comment by kachkaev** [comment]
👋 @cesalazar! Please see https://github.com/prettier/prettier/issues/15096. Let’s close this issue as a duplicate.
