### ISSUE TITLE
easy to close - indent question

### ISSUE THREAD

**Issue by mvolkmann** [prettier/prettier#1514]
It seems Prettier does this now:
```
<foo
  bar="1"
  baz="2"
  />
```

Is that intentional or should the `/>` start in the same column as `<`?

**Comment by lydell** [comment]
I tried to reproduce this, but couldn’t :(

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cfoo%5Cn%20%20barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr%3D%5C%221%5C%22%5Cn%20%20baz%3D%5C%222%5C%22%5Cn%20%20%2F%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by mvolkmann** [comment]
Sorry. I'm using prettier-eslint and an ESLint rule was doing this.
