### ISSUE TITLE
Super-long template string variable declaration is not breaked into two lines

### ISSUE THREAD

**Issue by so1ve** [prettier/prettier#15158]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAcgEZSzyLKrqba76HHTCAdKSKDHfTAAyYGChwkaV4gANCAgAHGAEt0yUNgBOqiAHcACmoRpkIbABtN2AJ4GpAI1XYwAazgwAytgC2cADLyocZABmJmhwNnaOzi4y9r4A5sgwqgCuoSAh7vIJyaloccZwAIpJEPCBwakAVmgAHi55hcWlSEHGIVIAjo1w2hoyBijYaAC0fnAAJuOSIInY8sZxAMIQ7u7YhibGU7lQsfkAgjCJ8tZJ8Npwqj5+Za2pABYw7sYA6nfy8GjRYHAu+u-yADd3uZDGA0FYQACUgBJKATWAuMCqeRyPZwlwwcz5G5tEAyDQhZ52GSGfFwEKqAH+KS+CkwHrYWKrHGpaKqCmGazYaxwTZSfG+GDPeRjGB3ZAADgADFJVHBOvI5QymWtmuUpDBucLReKkAAmKRJEIAFW5-RauLg7h5YwmYy82B2SUZcAAYhBVKtDnF1qcICAAL4BoA)

```sh
--parser babel
```

**Input:**

```jsx
const a = '11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'
const a = `11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111`
```

**Output:**

```jsx
const a =
  "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
const a = `11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111`;

```

**Expected behavior:**
They should be consistent - both break into multiple lines.

**Comment by auvred** [comment]
Hi! It seems that this issue is already tracked here: https://github.com/prettier/prettier/issues/4719

**Comment by so1ve** [comment]
Ah yeah! Thanks @auvred, it's duplicate of #4719.
