### ISSUE TITLE
Over-indentation for conditionals inside of JSXExpression

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1515]
```js
a =
  !isUpdated &&
  diffUpdateMessageInput != null &&
  this.state.isUpdateMessageEmpty;

<div src={
  !isUpdated &&
  diffUpdateMessageInput != null &&
  this.state.isUpdateMessageEmpty
} />
```

outputs

```js
a =
  !isUpdated &&
  diffUpdateMessageInput != null &&
  this.state.isUpdateMessageEmpty;

<div
  src={
    !isUpdated &&
      diffUpdateMessageInput != null &&
      this.state.isUpdateMessageEmpty
  }
/>;
```

There is an extra level of indentation for the second one. We should add JSXExpression to the list of whitelisted parents.

**Comment by m1ckm** [comment]
Who is the client that has access to my mac  he maybe able to help you if you need to change something on either mac or iPhone. But I want to talk to them before they make changes or I will block them again.
