### ISSUE TITLE
Why does prettier add parens to `x * y / z`?

### ISSUE THREAD

**Issue by tremby** [prettier/prettier#15160]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAKnQT3QenQC8QAaECABxgEtoBnZUAQwCdWIB3ABTYUZTMANp2Y5G5AEatmYANZwYAZWYBbOABkaUOMgBmw+nCkz5ipZVnaA5shisArsZBHVNO4+f0bQuAEUHCHh9Q2cAK3pUJR9-QOCkAyEjcgBHOLhuDkoBEGZ6AFodOAATErIQe2YaIRsAYQhVVWZkXKEhcu8oa18AQRh7GkkHeG44Vi0dEKTnAAsYVSEAdRmaeHpLMDglflWaADdVnBawegkQPacASShS2CUwVhpqHpulGBxfKeSQSg4jRZklBavzgRlYe105G0YJgmWY1iaX2cllYYJakmYkjg7XIv20MEWNGKMBmyAAHAAGcisOBpGg0uEI5oJULkGCYwnE0lIABM5AcRgAKpiBIlvnBVFjiqVihpmF0HPC4AAxCCsJr9GwtZjDCAgAC++qAA)

```sh
--parser babel
```

**Input:**

```jsx
x * y / z
```

**Output:**

```jsx
(x * y) / z;

```

**Expected behavior:**

No change: `x * y / z`

`(x * y) / z` is the same as `x * (y / z)` so it makes no difference to the evaluated result.

IMO the parens only *add* confusion, because it makes one wonder why they're there.

In my actual use case it was `newHeight * width / height`, i.e. use an aspect ratio `width / height` to calculate a new width given a new height. If parens are going to go anywhere, they make most sense around `width / height` since that is the aspect ratio, but prettier decided to add some around `(newHeight * width)`. It made the code less readable.

**Comment by kachkaev** [comment]
👋 @tremby! This is intended behavior. See https://github.com/prettier/prettier/issues/187#issuecomment-385495801 and https://github.com/prettier/prettier/issues/4407 for context.

**Comment by tremby** [comment]
That comment is about `a / b * c`. It makes sense to complain and ask for parens there, because `(a / b) * c` is different from `a / (b * c)`.

But I'm talking about `x * y / z`. `(x * y) / z` and `x * (y / z)` are the same.
