### ISSUE TITLE
plugins is not available in project of TS & NestJS

### ISSUE THREAD

**Issue by OneLeal** [prettier/prettier#15189]
![截屏2023-07-31 15 18 31](https://github.com/prettier/plugin-ruby/assets/55690294/ab15b1e6-29bf-44a9-8b35-e14bd5727c84)
![截屏2023-07-31 15 18 46](https://github.com/prettier/plugin-ruby/assets/55690294/90c940c7-32db-4525-bff5-104257a6457b)
![截屏2023-07-31 15 19 01](https://github.com/prettier/plugin-ruby/assets/55690294/63028711-c33a-4c75-aad6-06f15676f9f4)
![截屏2023-07-31 15 18 46](https://github.com/prettier/plugin-ruby/assets/55690294/5d268672-83a3-459c-87c0-5de32f99cec1).
![截屏2023-07-31 15 19 01](https://github.com/prettier/plugin-ruby/assets/55690294/5adb4985-6d7d-4508-a907-043142d331c4)
![截屏2023-07-31 15 23 22](https://github.com/prettier/plugin-ruby/assets/55690294/7dc72651-ee48-4568-b1f5-3205f43d09ce)

plugins-ruby is not available but others is OK.

**Comment by fisker** [comment]
@prettier/plugin-ruby only support prettier v3, https://github.com/prettier/plugin-ruby/blob/main/CHANGELOG.md#changed-2, and you are running prettier v2 
![Screenshot_2023-08-01-01-03-29-411_com microsoft emmx canary-edit](https://github.com/prettier/prettier/assets/172584/0f4848cc-6d1c-4c50-aa91-e7c2199347eb)

**Comment by OneLeal** [comment]
thanks you
