### ISSUE TITLE
Mdx parsing cause problems if the last element is a list

### ISSUE THREAD

**Issue by ahigueratw** [prettier/prettier#15191]
## Description 
Hi all, I was trying to use Prettier to format some MDX files, but I'm getting an indentation error. Basically, after parsing the mdx, the closing tag is incorrectly indented if the last element inside the component is a list. That causes an mdx error if I try to read the output with an mdx processor. You can test the output below at https://mdxjs.com/playground/.

## Additional data
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAZQgWzugEwEMYiAdKAHgGFcAHaBGAPgtQ2z3RgEsYAbfBQqd88AB4x0FALToAkvBzoAjADp0AGQgAnOMp50AzgFdlBCP13ojfdETxTIUI3DDwYJnfYKGetsB4oAHN0OH4+NVkFJXQAJg1tPQNjM0JLa1spBzgnaFd3XK8fPwCg0PDI6MV9dABmRN1aw1NzDO8s+0d0ZwKPYqJfOn8eQJCwiJgoqDka5QAWRuT0FrSLKw67HLyXN37vQdLR8omqqgB6WhwGKCZWKHYbEwAjXgE4EVx8Df0QABoQBA6Lx8shQEQdDoIAB3AAKEIQRmQICI-GhRAAnkiAc8dEQwABrXKYHKaIJwZAAM1RrhxeMJxLo+PKyBgOhMcABrhwPFZ7M5IFsIUEAEUTBB4FSaQKAFZGcSYcqi8WSpDU-i0kAARxVcFhUOMyKIRhktzgBHN-xAbKIPAiISuOCIRv4-CtQuCggAgjA2TxniZ4LC4DoybcpRqBQALGA4fgAdSjfDgRiZYDgmERfB4ADc+BjkWAjNiQDmOfIoBbYJgwDpDDAvZXMDAMYII5q6FDXPG8XRkZ2UyGcxSAUFXDoYPqiMEne2BUydOPkTgCOIrZ2gjB4zwCDAo8gABwABgBeh1PD0U5nzrV0oBpGe293+6QcQBJlcABUiM8kbfIwC+jPOaFoEJoRAhCY05wAAYroTq+iyKBEIGEAgAAvuhQA)

```sh
--parser mdx
```

**Input:**

```mdx
# Some data
<Component>
## Some title 

Some text 
- Item 1. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 2. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 3. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 4. Lorem ipsum dolor sit amet consectetur adipisicing elit.
</Component>
## subtitle
Some lorem
```

**Output:**

```mdx
# Some data

<Component>
## Some title

Some text

- Item 1. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 2. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 3. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 4. Lorem ipsum dolor sit amet consectetur adipisicing elit.
  </Component>

## subtitle

Some lorem

```

**Expected behavior:**
```mdx
# Some data

<Component>
## Some title

Some text

- Item 1. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 2. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 3. Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Item 4. Lorem ipsum dolor sit amet consectetur adipisicing elit.
</Component>

## subtitle

Some lorem
```

**Comment by kachkaev** [comment]
I believe that this issue is a part of #12209. Let’s track it there in one place.
