### ISSUE TITLE
`declare` keyword not formatted for a particular namespace name

### ISSUE THREAD

**Issue by ematipico** [prettier/prettier#15207]
**Prettier 3.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAimwFs4BnAB2zEO3JlwgAkAVAWQBkA6AKQGUAGgWABfEABoQESjACW0cslB4mAdwAKeBEpTZMa7AE8lUgEa4aAazgx+pOJzlQ4yAGb7ycc5bA271GDOAObIjACu3iBeJHJhuJFS5CGYcACK4RDw7p5RAFbkAB78KemZ2UgemF5SAI7lcBpMlLog9AC0LnDoqJIgjNhymCEAwhAkJNjIbZiYfclQwakAgjCMcmbh8BpwuE4uOdVRABYwJJgA6sdy8FQ0cPw6N3IAbjdG02DkpiAvkQCSUHQsH4YFwclkyyB-BgRlShxqIEoTC8F0slGmyIouxerikzi8uBgTWwwUmCKi1FwhOmsMoFDBEJgfWRzhgFzkqBgx2QAA4AAxSfD1OT4ElkqaVXJSGDYMwcrk8pAAJik4S8rDluiqiLgJDM3R6nGwi3CpLgADEILhJmsQtNsFsICBRKIgA)

```sh
# Options (if any):
```

**Input:**

```jsx
declare namespace astroHTML.JSX {}
```

**Output:**

```jsx
namespace astroHTML.JSX {}
```

**Expected behavior:**

```jsx
declare namespace astroHTML.JSX {}
```

**Comment by sosukesuzuki** [comment]
Parse following code with `@typescript-eslint/typescript-estree`.

```ts
declare namespace astroHTML.JSX {}
```

The `@typescript-eslint/typescript-estree@6.2.1` downloaded from npm generates the following AST:

```json
{
  "type": "TSModuleDeclaration",
  "kind": "namespace",
  "body": {
    "type": "TSModuleBlock",
    "body": []
  },
  "declare": false,
  "global": false,
  "id": {
    "left": {
      "decorators": [],
      "name": "astroHTML",
      "optional": false,
      "type": "Identifier"
    },
    "right": {
      "decorators": [],
      "name": "JSX",
      "optional": false,
      "type": "Identifier"
    },
    "type": "TSQualifiedName"
  }
}
```

However, typescript-estree built from source code produces the following AST

```json
{
  "type": "TSModuleDeclaration",
  "kind": "namespace",
  "id": {
    "type": "Identifier",
    "name": "astroHTML"
  },
  "body": {
    "type": "TSModuleDeclaration",
    "kind": "namespace",
    "id": {
      "type": "Identifier",
      "name": "JSX"
    },
    "body": {
      "type": "TSModuleBlock",
      "body": []
    }
  },
  "declare": true
}
```

This difference is strange. Is something different from the source code being published to npm...?

**Comment by auvred** [comment]
Hi, this is the AST produced by `@typescript-eslint/typescript-estree` from the main branch

```json
{
      "type": "TSModuleDeclaration",
      "kind": "namespace",
      "body": {
        "type": "TSModuleBlock",
        "body": [],
        "range": [32, 34],
        "loc": {
          "start": { "line": 1, "column": 32 },
          "end": { "line": 1, "column": 34 }
        }
      },
      "declare": false,
      "global": false,
      "id": {
        "left": {
          "decorators": [],
          "name": "astroHTML",
          "optional": false,
          "range": [18, 27],
          "type": "Identifier",
          "loc": {
            "start": { "line": 1, "column": 18 },
            "end": { "line": 1, "column": 27 }
          }
        },
        "right": {
          "decorators": [],
          "name": "JSX",
          "optional": false,
          "range": [28, 31],
          "type": "Identifier",
          "loc": {
            "start": { "line": 1, "column": 28 },
            "end": { "line": 1, "column": 31 }
          }
        },
        "range": [18, 31],
        "type": "TSQualifiedName",
        "loc": {
          "start": { "line": 1, "column": 18 },
          "end": { "line": 1, "column": 31 }
        }
      },
      "range": [0, 34],
      "loc": {
        "start": { "line": 1, "column": 0 },
        "end": { "line": 1, "column": 34 }
      }
    }
```

**Comment by Penguinlay** [comment]
This bug also affects `export namespace`.

**Comment by AlexAegis** [comment]
If anyone struggles with this, in the meanwhile you can use `// prettier-ignore` until this bug is resolved

**Comment by kachkaev** [comment]
@AlexAegis, yep, that’s correct!

**Prettier 3.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAimwFs4BnAB2zEO3JlwgAkAVAWQBkA6AKQGUAGgWABfADpRJAemkFK+GDACWcXAFplAcygR8k9FjyFiZKjToMmbLnyEiJUqHAAelPTCKkK1WgQBiEBAAQngOkjJyCnBKqhrauvrObh5eZr6EgSFhYhFQIAA0IBCUKtDkyKB4TADuAArGUBUo2Jg12ACeFUUARrg0ANYx-N6cys7IAGat5HC9-WBDMPy+41rIjACucyCzJMobuNtF5GuYcACKmxDwUzM7AFbkLvxnl9e3SNOYs0UAjh84HUmJRmiB6OpnHB0KhCiBGNhlJg1gBhCAkEjYZDgzCYOGnKBac4AQSUuGUPU28DqajGEy+9yKAAsYCRMAB1JnKeDmWj8BCnFQAN25HWxYHI3RAQu2AEkoOhYPwwOTSsSFfwYB1zncfjsFBBZuz+pRsdFZrghXA4eMLTBgdgtJjdb8QNRcBbsVrKBQVcpSnCFOMYOzlKgYEzkAAOAAMRXwAOU+AdTqxDL1RRg2B6ofDkaQACYiptZqxs81vq64CQetCYZxsITNo64IFcJjYoTsdgqRAQKJREA)

```sh
--parser typescript
```

**Input:**

```tsx
declare namespace astroHTML.JSX {}

// prettier-ignore
declare namespace astroHTML.JSX {}

export namespace FooBar {}

// prettier-ignore
export namespace FooBar {}


```

**Output:**

```tsx
namespace astroHTML.JSX {}

// prettier-ignore
declare namespace astroHTML.JSX {}

export namespace FooBar {}

// prettier-ignore
export namespace FooBar {}

```
