### ISSUE TITLE
Option to disable addition of parenthesis for TypeofTypeAnnotation

### ISSUE THREAD

**Issue by testplop** [prettier/prettier#15202]
Hi,

Is there an option to disable the addition of parentheses to `TypeofTypeAnnotation` ?
Change introduced here: https://github.com/prettier/prettier/blob/main/CHANGELOG.md#add-parentheses-for-typeoftypeannotation-to-improve-readability-14458-by-fisker

Thank you.

**Comment by kachkaev** [comment]
👋 @testplop! Please see [Prettier’s Option Philosophy](https://prettier.io/docs/en/option-philosophy.html)
