### ISSUE TITLE
Official Container Image

### ISSUE THREAD

**Issue by 6543** [prettier/prettier#15206]
looking at [docker hub](https://hub.docker.com/search?q=prettier&sort=updated_at&order=desc) and [Github Packages](https://github.com/orgs/prettier/packages) I can not find an official image.

It's easy to create an own one ([example](https://github.com/tmknom/dockerfiles/blob/main/prettier/Dockerfile)) but it would be better in terms of trust and supply-chain-attacks, to see "official" images build from this project directly.

It can then be used in CI/CD applications (WoodpeckerCI, GitlabCI, ...) and a lot of other use-cases ...

**Comment by 6543** [comment]
Well that's also a way to do, it just would be faster as npm dont need to install anything just a container pull would be enough.

e.g it's more efficient

**Comment by kachkaev** [comment]
I think it is fine for someone to create an unofficial image and share a link here. Those who search for Prettier inside Docker will be able to find it. If there is enough demand (i.e. the number of downloads gets reasonable), we can consider making that repo official. It is hard to predict the demand in advance. This creates a risk of focusing the team’s efforts on something that won’t be used that much.

Let’s close this issue as not planned for now. We can reconsider this decision if there is data that confirms a need for such feature. It’s still possible to continue the discussion below: share use cases, links and supporting data.

**Comment by kachkaev** [comment]
Current stats from https://hub.docker.com/search?q=prettier&sort=updated_at&order=desc

<img width="960" alt="Screenshot 2023-08-04 at 12 01 52" src="https://github.com/prettier/prettier/assets/608862/c6d34ee0-5387-4c40-ab51-8de5952a9c5a">

(these are all-time download counts)
