### ISSUE TITLE
VSCode language-specific integration with json

### ISSUE THREAD

**Issue by AlanBlanchet** [prettier/prettier#15218]
Hello. This is just a quick issue because I managed to get prettier to format my document but by using more language-specific vscode attributes. I believe it wasn't intended to work this way.

**Environments:**

- VSCode prettier extension version : 10.1.0.
- VSCode version : 1.81.0

**Steps to reproduce:**

You have to have the `esbenp.prettier-vscode` extension installed.

Simply add this to workspace specific configuration in the `.vscode/settings.json` file : 

```json
{
  "editor.formatOnSave": true,
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

**Expected behavior:**

By adding a few empty lines in the same config and pressing `CTRL+S`, I expect the `json` file to be formatted. But it is not the resulting behaviour.

**Actual behavior:**

This is the code I tried it on : 
```json
{
  "editor.formatOnSave": true,


  
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

Nothing happens when hitting `CTRL+S`. I also tried `F1` and `Format Document`. And it tells me to configure a default formatter which tells me that the `json` rule isn't being applied.

**Workaround**

Adding more `json` file extensions to the vscode langage-specific configuration attributes.

```json
{
  "editor.formatOnSave": true,
  "[json][jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

I don't know why adding `jsonc` works. But it works.

I don't believe that having to add `[jsonc]` should be needed to format a `json` file considering we already have the `[json]` language specific attribute.

Maybe there is something I'm misssing and it might be something to do with vscode. Feel free to tell me if you believe it is the case.

Thanks

**Comment by auvred** [comment]
Hi, this is how VS Code language identifiers work. You can read more about it here:

- [Language Identifiers](https://code.visualstudio.com/docs/languages/identifiers)
- [JSON with comments](https://code.visualstudio.com/docs/languages/json#_json-with-comments)

VS Code allows to write comments in its `settings.json`. That's why it treats it as `jsonc`, not `json`.

**Comment by auvred** [comment]
The VS Code won't even call `prettier-vscode` unless you specify `[jsonc]`.

The language id does not always match the file extension. For example, `.jsx` files have the `javascriptreact` language identifier

**Comment by so1ve** [comment]
Well, bro @AlanBlanchet, VSCode's settings file is not actual `json` files. They are `jsonc` files, you can use comments inside them. That's why `[json]` doesn't work: VSCode's settings files's identifier is `jsonc`, not `json`. If you create a fresh json file, it well work properly as you expected.

**Comment by AlanBlanchet** [comment]
I find it kind of nonintuitive for people who just specify `[json]` in their file and that it doesn't work on a file ending in `.json`. They might not understand.

Hopefully they'll come across this issue to see that they need to add `[jsonc]`.

But of course with this detailed information of how `vscode` handles it I can see that `prettier` has nothing to do with it. It's `vscode` that's saying that `settings.json` is a `jsonc` file and thus doesn't let prettier run on it.

Thanks for clarifying.

I'll close this issue since prettier can't do anything about it even if it wanted to.
Thanks for your quick replies @auvred @auvred
