### ISSUE TITLE
Vue + typescript type assertion results in unexpected token (and incorrect code)

### ISSUE THREAD

**Issue by maartenbrakkee** [prettier/prettier#15224]
**Prettier 3.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARnpwDOMAtJNtAjGUgCYF53MC8xIABTxaZPNTIAVGjACSsOACcAZnjBwAlALacY3GAHcI-ISJgAmMROm158FWs3ayAehJRULzLgJx3pVGowRQBLLBh3HDhWAAVFaJgQpTJeMmUIRQwCFMIyYDIATwgAV0UAOgArakEAchgACxKAc3qajTIAXwCXINDw-w9aAqj3MrwodjyyMGpqJDIYCAgyAEIQpkU9WE7uoZGQABoQCHCQ6GpkUDxFRQgDGOuEC5Q8HAM8AoujgCNFNQBraIAZTwGDgABkQlA4MgYIpinAfn8wICYECsGooU1YfDESBqHAMCEcQijtQsVEAIrFCDwEl4qoADyBFLg1NpMKQqhwBKOAEcafA4idniBxHRoXB2FLDiA4XgQjgsQBhCAYLLIMU4HCy8lQJpRACCMDhIW+xSFSkh0OQ3N5IHqMAwOAA6vUQiIMeogU8PSEAG4egqamZfED+hHyaWwIHBMIwQ0TIEwYacu14rC3Akuv5YTWZmhKf0wo5QgmbOJ4Joarmve0YxTlzURksgTNQmAukLsBrIACMAA4AAxHeICkLxSvVvC2ut4vTfLs9+rIcxHYoEyR4b7PdNHQnfKXS9jg8ZNYpVuAAMQyWRNWM1eAtEBAHQ6QA)

```sh
--parser vue
--print-width 180
--single-quote
--bracket-same-line
```

**Input:**

```vue
<template>
  <test-component :data-one="(test as TestInterface)" :data-two="(test2 as TestInterface)"  />
</template>

<script>
let Prettier = format => { your.js('though') }
</script>

<style>
.and { css: too !important }
</style>
```

**Output:**

```vue
SyntaxError: Unexpected token, expected "," (1:7)
> 1 | (test as TestInterface)
    |       ^
```

**Expected behavior:**
Right now Prettier removes the parentheses in my project. Maybe this is related to the SyntaxError shown above. 

Prettier should allow Typescript in Vue templates, and keep the parentheses to keep the code valid.

**Comment by fisker** [comment]
You need add `lang="ts"` to your script tag.

**Comment by fisker** [comment]
[Vue playground](https://play.vuejs.org/#eNp9kj9vwjAQxb/K1UtBgiCVLQKktmKgQ1u1jF6s5Aihjh3ZZ/4I5bv3bAplQEw53/vd+b3IR/Hcttk2oMjFhLBptSKcSQPAJ0/DwjatNWgI8lKRGnI9laIXNVAelvxdGEK3UgX2pfijaGfP1NNNDEZ8x2R0dSEffeHqlrjWSPDpkKhGB1NYWdcogukMjnCwwWUb33uktQ3V+rEPXVx0GY1r6KDjxkyZkicK73Mga+Gh5iiOFGc5zSRODAT5wppVXfFea/g/HGN8KWL0WqP7aKm2xkuRQ1KiprS2u7fUIxdwcO4Xayx+bvQ3fh97UnAsj26LUlw0Uq5COsnz73fcc30RG1sGzfQd8Qu91SF6PGEvwZRs+4pLbhcpfW2qpZ/vCY0/h4pGI9klXgp+DK93ov/bHWfjNCdNJ7pfZuvDgg==)

[Vue playground(with lang)](https://play.vuejs.org/#eNp9UstuwjAQ/JWtL4AEQSq3CJDaigM9tFXL0RcrWUKoY0f2hodQ/r1rBygHxMn2zuzszMon8VLXya5BkYopYVVrRTiXBoBfnkaZrWpr0BCkuSI14vtMin7AQHlY8bk0hG6tMhxIcWbR3l5Yz3dpMOYZ0/HNQH76zJU1gVam4G7yUnBdI8GXQ6ISHcxgbV2lCGZzOMHRNi7Z+n6PNrYpNr0BtEG0kzlL0lEH9USZnDsy71Mga+Gp5FiOFOfqeiJPDHlqZs26LFjXGt7JKaxCirCGUqP7rKm0hp2lEJGAKa3t/j3WyDU4vNSzDWa/d+pbfwg1KTiWR7dDKa4YKVcgdfDi5wMPfL+Clc0bzewH4Dd6q5vgsaO9NiZn2ze86HYZ05emWPnFgdD4S6hgNDDbyJeCP8bbg+j/difJJPZJ04r2D4lMx2Q=)

**Comment by maartenbrakkee** [comment]
@fisker thanks for solving the SyntaxError.

However, the result is the same, the parentheses are removed. With parentheses removed, syntax highlighting breaks. The highlighter (Volar) has a [fix for this](https://github.com/vuejs/language-tools/issues/859), but in VS Code, Prettier is run as last (on save). Therefore, the parentheses are removed again by Prettier which results in a broken highlighter.

How can I bypass Prettier removing the parentheses in this case?

**Comment by fisker** [comment]
https://github.com/prettier/prettier/issues/15197#issuecomment-1663170622
