### ISSUE TITLE
Requiring ES Module

### ISSUE THREAD

**Issue by yordis** [prettier/prettier#15227]
**Environments:**

- Prettier Version: 3.0.1
- Running Prettier via: CLI 
- Runtime: NodeJS v18.17.1
- Operating System: macOS
- Prettier plugins (if any): N/A Directly

**Steps to reproduce:**

1. `gh repo clone straw-hat-team/nextjs-starter-kit` clone the repo
2. `git checkout upgrade-prettier-config` https://github.com/straw-hat-team/nextjs-starter-kit/pull/17
3. `yarn install`
4. `yarn format`

**Expected behavior:**

It should work.

**Actual behavior:**

```
yarn format       
[error] Invalid configuration for file "/Users/ubi/Developer/github.com/straw-hat-team/nextjs-starter-kit/.eslintrc.json":
[error] require() of ES Module /Users/ubi/Developer/github.com/straw-hat-team/nextjs-starter-kit/prettier.config.mjs not supported.
[error] Instead change the require of /Users/ubi/Developer/github.com/straw-hat-team/nextjs-starter-kit/prettier.config.mjs to a dynamic import() which is available in all CommonJS modules.
```

**Comment by auvred** [comment]
Hi! You're using `prettier-plugin-tailwindcss@0.2.8` which, as far as I know, doesn't support `prettier@3`

```shell
$ yarn why prettier-plugin-tailwindcss
├─ @straw-hat/prettier-config@npm:3.1.0
│  └─ prettier-plugin-tailwindcss@npm:0.2.8 (via npm:^0.2.7)
│
└─ @straw-hat/prettier-config@npm:3.1.0 [dc3fc]
   └─ prettier-plugin-tailwindcss@npm:0.2.8 [e6d9e] (via npm:^0.2.7 [e6d9e])
```

Try to upgrade it at least to `v4.0.0`

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/releases/tag/v0.4.0

**Comment by yordis** [comment]
I upgraded all the packages, so `"prettier-plugin-tailwindcss@npm:^0.5.1"` is in used now

**Comment by fisker** [comment]
The `prettier.config.mjs` only support default export.

**Comment by yordis** [comment]
Just pushed the changes with your suggestion and it didn't work neither 😭

**Comment by fisker** [comment]
You config package is broken, run `node prettier.config.js` to see the error.

**Comment by yordis** [comment]
Turns out that I shouldn't be importing plugins but instead use the name in the `plugins` section.

Here was the fix: https://github.com/straw-hat-team/nodejs-monorepo/commit/4a46441c7b61f9e020f375854fcb85e560a887e3

```patch
--- a/packages/@straw-hat/prettier-config/lib/index.js
+++ b/packages/@straw-hat/prettier-config/lib/index.js
@@ -1,8 +1,7 @@
-import organizeImportsPlugin from 'prettier-plugin-organize-imports';
 import baseConfig from './base.js';
 
 export default {
   ...baseConfig,
   organizeImportsSkipDestructiveCodeActions: true,
-  plugins: [...baseConfig.plugins, organizeImportsPlugin],
+  plugins: [...baseConfig.plugins, 'prettier-plugin-organize-imports'],
 };
```

**Comment by iamandrewluca** [comment]
> Your config package is broken, run `node prettier.config.mjs` to see the error.

Thanks! In my case, I was importing a base config which was a JSON file.

```
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "@allindevelopers/prettier-config/index.json" needs an import assertion of type "json"
```
Fixed the import, and it worked

```
import baseConfig from "@allindevelopers/prettier-config" assert { type: "json" };
```
