### ISSUE TITLE
<!doctype> removed in Handlebars

### ISSUE THREAD

**Issue by Eejit43** [prettier/prettier#15220]
Prettier 3.0.1 strips `<!doctype html>` from Handlebars files.

Note: no playground link as it appears to be broken.

**Input:**

```hbs
<!doctype html>
<html lang='en'></html>
```

**Output:**

```hbs
<html lang='en'></html>
```

**Expected behavior:**

Not to be removed! :)

**Comment by fisker** [comment]
Duplicate of #11223

**Comment by Eejit43** [comment]
> Duplicate of #11223

Whoops sorry, not sure how I didn't find that when searching!
