### ISSUE TITLE
Async API is cumbersome for standalone in browser

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#15235]
**Environments:**

- Prettier Version: 3.0.1

Just wanted to note that having only async API is annoying for standalone, in contexts like React. This adds a lot of complexity (handling display while the async formatting is finishing etc.).

There seems to be no easy workaround for this:
https://github.com/prettier/prettier-synchronized/issues/15

**Edit:** I gave up for now on upgrading to v3, because this change requires too much effort for our modestly-sized React app which displays code in a bunch of places.

**Comment by kachkaev** [comment]
👋 @xixixao! Not sure that changing back to sync API is feasible. If you want to simplify state management in React, you can call Prettier via `react-query` or `swc`. This will help you reduce boilerplate code and save you from reinventing the wheel.
