### ISSUE TITLE
Wrong formatting of ".?" in JS.

### ISSUE THREAD

**Issue by Tuurtie** [prettier/prettier#15248]
**Prettier 3.0.1**
This is an easy fix I think, the ?. is formatted wrong, this broke my code...

```json
{
    "tabWidth": 4,
    "semi": true,
    "singleQuote": false
}
```

**Input:**

```js
if (userExists[0]?.username == q.newUser) {
    ...
}
```

**Output:**

```js
if (userExists[0] ? .username == q.newUser) {
    ...
}
```

**Expected behavior:**
```js
if (userExists[0]?.username == q.newUser) {
    ...
}
```

**Comment by fisker** [comment]
Can't reproduce.

**Prettier 3.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQFcDOcATgKIAeq+M+A2gAwC6A-AHQHFQCGAtnJgLz9MARxZQ4AdwCqhIgEpMwADpRMagPTrMLHSoC+IADQgIABxipo+ZKE5EiECQAU7Cayk4AbCZwCe14wAjIk4wAGs4GABlHjgAGVRxZHQvQiCQ8Mio01DEgHNkGCJcOGNCblRC4tKQfHzPOABFXAh4ZNSagCt8Mij6ppa2pBTPNJBhQbgnB1N3EE58AFpxOAATNaMQIs5UT3yAYQhubk5kec9PTbqoPIaAQRgi1EDceCdiBKThjuMACxhuJ4AOq-VDwfA5MBwKJuMGoABuYN8ZzA+ACIHhJQAklB1rAomAiKhzHdcVEYL4Gu1RjVTA5CECQqYznS4LJ4XBNolZDBppw8idqWMckRZGdApxAnBLsY6YkYEDUKsYL9kAAOOjGIhwCaobV8gWnb404wwSWK5WqpAAJmM7AAKpL3CMxnBuFLVutVnFODdcPy4AAxCBEE6PfJnTivCAgPR6IA)

```sh
--parser babel
```

**Input:**

```jsx
if (userExists[0]?.username == q.newUser) {
   // ...
}
```

**Output:**

```jsx
if (userExists[0]?.username == q.newUser) {
  // ...
}

```


Please follow the issue template next time.
