### ISSUE TITLE
Change the logo of Twitter to X

### ISSUE THREAD

**Issue by Hero-codes** [prettier/prettier#15251]
In the footer, you should remove the bird and add X
![Screenshot_2023-08-16-11-29-07-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/prettier/prettier/assets/98174971/f5ad5a70-0316-46a5-9f41-693d8f16fe4e)
.

**Comment by fisker** [comment]
It's provide by https://shields.io/badges/twitter-follow

**Comment by fisker** [comment]
https://github.com/badges/shields/issues/9479
