### ISSUE TITLE
Inconsitent behavior using .editorconfig

### ISSUE THREAD

**Issue by sharpenedblade** [prettier/prettier#15288]
**Environments:**

- Prettier Version: 3.0.2
- Running Prettier via: CLI
- Runtime: Node.js v20.5.1
- Operating System: Macos and Linux (I didnt test Windows)
- Prettier plugins (if any): 

**Steps to reproduce:**

1. Put this in `test.js`:

    ```
    function test(){
        const a = "qwerty";
    }
    ```
2. Put this in `.editorconfig`:

    ```
    root = true
    [*]
    indent_style = space
    indent_size = 4
    ```
3. Put this in `prettier.config.js`:

    ```
    {}
    ```

4. Run `npx prettier@latest --parser=typescript < test.js`

5.  Run `npx prettier@latest --parser=typescript test.js`.

**Expected behavior:**
Both commands use 4 spaces for tabs, and have identical output.

**Actual behavior:**
Piping to `stdin` uses 2 spaces for tabs instead of following `.editorcconfig`

**Comment by fisker** [comment]
Have you try [`--stdin-filepath`](https://prettier.io/docs/en/cli#--stdin-filepath)?

**Comment by sharpenedblade** [comment]
Using `--stdin-filepath` works, but I think prettier should still look for `.editorconfig` starting in `$PWD` when it is not passed `--stdin-filepath`. I am using prettier in an environment where the input filename is not easily available, but it would be nice if resolving `.editorconfig` using the detected project root still works.

**Comment by fisker** [comment]
Problem is we can't know where the stdin from, use `.editorconfig` in `$pwd` not really make sense, for the same reason we also not reading `.prettierrc`. Don't forget `.editorconfig` and `.prettierrc` also supports `overrides` which based on file names. I don't think we want change current behavior.

**Comment by sharpenedblade** [comment]
> Problem is we can't know where the stdin from, use .editorconfig in $pwd not really make sense, for the same reason we also not reading `.prettierrc`.

Prettier detects and uses `prettier.config.js` in the "project dir". Allowing a cli flag to specify the `.editorconfig` file to use would work for simple projects. It could recurse up from the specified config all the way to the root config.

>  Don't forget .editorconfig and .prettierrc also supports overrides which based on file names. I don't think we want change current behavior.

Just applying "global" settings would help a lot.

**Comment by fisker** [comment]
We are not going to change current behavior.
