### ISSUE TITLE
Prettier formatting is inconsistent when using escaping in string

### ISSUE THREAD

**Issue by iteriani** [prettier/prettier#15284]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFkBlAcQH1KBRAOToCUBJAYWoHkAFFgQQAqrLg2oAxfqwAyAVWZ1qAIS4ARAJp4AvAB0oeAwHMIEQwDpDcGKSKGAFAHJBACwCGMHTodE8rgDZ+eADucHgA1lAQQQ4AlADcIAA0IBAYMACW0ETIoK7Y2FE8eQjZKP5BrgCe2ckARtiuYGFW5K4AtnDS6VBwyABm-kRwdQ1NLRiN3YbIMNgArsMgQ23pM-OLRFN+cACKcxDw-YOLAFZEaORbu-uHSAN+Q8kAjjdwPAUYpSCuRAC0PXAACZApIgWaudJ+KbsCBtNquZDfAKgzZQQzbfgwWbpWpzeA8ODYLo9I4PRbOGBtPwAdWc6XgRAmYDg5BK9PSADd6ZVEWAiDUQByFqwoMDYOQwNh0ml+KLyDBKttSY8QBgCkNqQ0MIi1XAhtgOb1kt19TB3q5DPDlYsJth9Yjaq5anA-KC1d0YNT0oCYM5kAAOAAMyWwcBe6VD5stCLux2SMCdXp9fqQACZknMhoInaV7iq4G1nYDgYDpK40XMLXBxDh4VipojXHiICAAL6toA)

```sh
--parser babel
```

**Input:**

```jsx
export const MSG_GENERIC_OPERATION_FAILURE_BODY =
   goog.getMsg('That\'s all we know');
```

**Output:**

```jsx
export const MSG_GENERIC_OPERATION_FAILURE_BODY = goog.getMsg(
  "That's all we know",
);

```

**Second Output:**

```jsx
export const MSG_GENERIC_OPERATION_FAILURE_BODY =
  goog.getMsg("That's all we know");

```

**Comment by iteriani** [comment]
Note that the first snippet has a That's which contains a "\'" to escape the apostrophe

**Comment by sosukesuzuki** [comment]
Please follow the issue template.
