### ISSUE TITLE
Ugly formatting on conditional types and type parameters

### ISSUE THREAD

**Issue by so1ve** [prettier/prettier#15292]
**Prettier 3.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYgQwBtCAjfMAa10PwHMBnAHl2zgA94oATevGh7AB9sAV25wAZgEsocLgD5sAXgA6UbNgCiARxFEmAOWgGRxfCUJxqdZvIDaKkBP71HAXQA02YAF9F7Th5sGAAnETg1DQ0AfmwAESkwGEZ8KDR5SKikbCMoEzMLK35bBycXdwBuEA8QCAwYKWh6ZFB8EJCIAHcABTaEZpQiTvw0ZpqSEPIKOBgAZXwAWzgAGRk4ZAl9OHHJyhnZjHIZWmRQ8Jr6OAWpU7DtkHpjywBFEQh4Da2agCt6NlmnnBXu91khNoRLjVdCDuh0MAMQPh6ABaWRyOTVVCTKSEY4AYQgCwW+GQiOImMeUFolgAgjBQlISCJ4N04CFVrJPhD7gALGALQgAdR5Ung9EOYDgs36oqkADdRWhSWB6GMQHLwgBJcSwWZgEJSeo07izdCWLmQkAYDqXQWTDCk61wS4hOXrGoyF0wWF0YkW+6HEIu0noLD0fWGmCY60yGCCqRcGA85AADgADDUQnBdFIsz7aH6wV9UOZ44nk0gAEw1ESXAAq5gG4MtVxIci4cmWqVoeloVggIWJ9OOpPwzIgIB8PiAA)

```sh
--parser typescript
```

**Input:**

```tsx
type FallbackFlags<F extends Flags | undefined> =
  Equals<NonNullableFlag<F>["flags"], {}> extends true
    ? Dict<any>
    : NonNullableFlag<F>["flags"];
```

**Output:**

```tsx
type FallbackFlags<F extends Flags | undefined> = Equals<
  NonNullableFlag<F>["flags"],
  {}
> extends true
  ? Dict<any>
  : NonNullableFlag<F>["flags"];

```

**Expected behavior:**
The input is better and more readable.

**Comment by so1ve** [comment]
I just fired #15205 weeks ago. Are they the same problem?

**Comment by seiyab** [comment]
This can be formatted well to me with `--experimental-ternaries`. 

Output:
```ts
type FallbackFlags<F extends Flags | undefined> =
  Equals<NonNullableFlag<F>["flags"], {}> extends true ? Dict<any>
  : NonNullableFlag<F>["flags"];
```

**Comment by so1ve** [comment]
Indeed, but personally I don't like the experimental ternary formatting :(

**Comment by sosukesuzuki** [comment]
Closed by https://github.com/prettier/prettier/pull/15811
