### ISSUE TITLE
AstPath#node not present in released files

### ISSUE THREAD

**Issue by Janther** [prettier/prettier#15291]
In v3.0.0 `AstPath#getValue` was deprecated in favour of `AstPath#node`. But when I adapted our code to respond to it, it doesn't find the function.

**Environments:**

- Prettier Version: 3.0.2
- Running Prettier via:  CLI
- Runtime:  Node v20
- Operating System:  macOS
- Prettier plugins (if any):  `prettier-plugin-solidity`

**Steps to reproduce:**

```Bash
git clone git@github.com:prettier-solidity/prettier-plugin-solidity.git
cd prettier-plugin-solidity
git checkout deprecated-getValue
npm i
```

then in the file `src/common/util.js` replace `path.getNode()` with `path.node()` on line 32.

finally

```Bash
npm run test
```
**Expected behavior:**

`path.node()` returns the current node in the `AstPath` and all test would pass.

**Actual behavior:**

I get the following error `path.node is not a function`

**Comment by fisker** [comment]
It's a getter, not a function to call, use `path.node` directly.
