### ISSUE TITLE
/* GraphQL */ comment tag does not format with typescript `as const`

### ISSUE THREAD

**Issue by hanayashiki** [prettier/prettier#15315]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAlA8gIVwBUBlAfQEUBVAUWwE0yB1ASSIAkyBhXAORKKYAvJgD0AKkwBxAE4BDAA4ALCgBlM40ZgAGAHSiZMARwCucGQE9MJTMExolEBZgC++7ZjlpMkKBgDc+vq+GDgExOTUdPTCYpKyiirqmjr6hqbmVjZ2Dk6u7oFQIAA0IE4wAJboyKByMjIQAO4ACnUIaMggcgA2jXIWHaUARvJgANZwMCRyALZwqhVQcMgAZj1ocMOjE1MKcmCLAObIMDJmpRszFSdnmyBoR91wFCYQ8KvrdwBWaAAeJI9nq93kg1t0NqVTG84M0GgoOigvABaJZwAAm6JKIFOcgq3SOXAgMxmck6PW6WIeUEOTwAgjBThUhiZ4M1zAslh9wXclDAZt0mEoKvA0HswHASO1hRUAG7CiydMBoQYgGVmFhQDGwEhgGQVBQwWmakgwCxPLkQkAKBobJjyBSda1wDYyGXLUqLF0wWFyQ4ki13PYyF2dIZyIZwbpImAq62LGBMCpomBKZAADgADKUZHBTBUcz6-aTQZ9SjBw4nk6mkAAmUomDZEcMIsGWuAzCNojFo1RyakmX1wABiEBkJIZRzJLIgIBcLiAA)

```sh
--parser babel-ts
```

**Input:**

```tsx
const ROBOTS_QUERY_WITH_CONST = /* GraphQL */ `
  query S { shop }
` as const;

const ROBOTS_QUERY = /* GraphQL */ `
  query S { shop }
`;

```

**Output:**

```tsx
const ROBOTS_QUERY_WITH_CONST = /* GraphQL */ `
  query S { shop }
` as const;

const ROBOTS_QUERY = /* GraphQL */ `
  query S {
    shop
  }
`;

```

**Expected behavior:**

Should get the same formated result within the tagged string.

```
const ROBOTS_QUERY_WITH_CONST = /* GraphQL */ `
  query S { shop }
` as const;

const ROBOTS_QUERY = /* GraphQL */ `
  query S { shop }
`;

```

Of course, when it doesn't work with `as const`, you can drop that `as const` because it does not affect typescript's typing. However, there are places where dropping such `as const` might affect devs' experience

**Comment by sosukesuzuki** [comment]
I don't think we need to support this.

**Comment by sosukesuzuki** [comment]
@hanayashiki Hi, can you tell me why this is needed? Is there any meaning in adding `as const` to template literal in TypeScript?

**Comment by hanayashiki** [comment]
> @hanayashiki Hi, can you tell me why this is needed? Is there any meaning in adding `as const` to template literal in TypeScript?

If you don't use as const, it will be inferred as "string" instead of a string literal.

**Comment by sosukesuzuki** [comment]
thank you. I got that there are differences in the inference results. I think this is acceptable.
