### ISSUE TITLE
Unstable comment location - after the last parameter property

### ISSUE THREAD

**Issue by bradzacher** [prettier/prettier#15314]
**Prettier 3.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMIbY7AA6UOOkUmMATgK5gwS0AUZFnOADrQJYA3dPBy046ACbRUATx7pa6ALYAFWhCQ4AKjO5wANB04B6Y5QhKlCGEYCUxIwF8yjkPpARuMPtEzJQCuoA7ioKCH4o6KhB6DJ+7gBGimAA1nAwAMrKcAAyfFBwyABmUZgGIEnoqekZ3FX5AObIdPTlZUp8zQxtjahwAIr0EPDFpeUAVpgAHhm9A0MjSCWoZe4Ajgtwap4RIFgAtAVwEsduIHTofKiNeBZK6Mh7qKhnmHMAgjB0fAn08CpwWh5AqjFblAAWMCUqAA6uC+PBMHUwHAMuEEYIETJHmBsGcBK0AJJQE6wDJgfhed4kjIwGR9UGrEC8CBlGGKbiPXhwMq0ASFdz5XkwNToBr3RnlOq0XmPOl6TAUvheM68fIwGF8CQwcHIAAcAAZ3GINnwxKLxQ8lmN3DB0AlNdrdUgAEzuehlLT2iLLJlwJQJY4nCQ5dBQBr0MVwABiLHuX0aj3QfwgIEcjiAA)

```sh
--parser typescript
```

**Input:**

```tsx
class Class {
  constructor(
      private readonly paramProp: Type,
    // comment
  ) {
  }
}
```

**Output:**

```tsx
class Class {
  constructor(private readonly paramProp: Type) // comment
  {}
}

```

**Second Output:**

```tsx
class Class {
  constructor(
    private readonly paramProp: Type, // comment
  ) {}
}


```

**Expected behavior:**

Comment location should be stable.

Similar to #11639

**Comment by fisker** [comment]
Tip: We have <kbd>show second format<kbd> option in playgroud left panel.
