### ISSUE TITLE
When prettier inserts <> characters in markdown links, it should encode existing <> characters too.

### ISSUE THREAD

**Issue by julienw** [prettier/prettier#15341]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtANgSygawLoAUAFjDAA4DOSA9NQO4MB0A5hBM+nIwGYBO1BAJTc2AWgB8AIwCGvQYwA6UEABoQEMjEzQKyULN4Q6ABVkJdKaejrSAnrrWTe0sDjgwAytIC2cADLYcMjcVhRwjs6u7h5kLtjMyDC8AK7hIGHemIkpaRTxnACKyRDwwaFpAFYUAB4e+XBFJUFIIehhagCOxfDGhpTIINIUolBwcAAmE6ogSdKYWFDMAMIQ3t7SA1bo03mLnACCpLyYksk9cLwBo2VtaSTe6ADqRJjwFLFgcB7mr5gAbq9bAMwBQHCA-qkAJJQSawDxgY6afYwjwwWycG7tEBkQxhR7OMgDHFwMK8P5BNTYUkwXrSZjrTFpWK8UkDda8HDjIzKNQ47AwR6YcYwIjIAAcAAY1Lw4F1MDLafSNi1ymoYNJJILhaKkAAmNTJMIAFQ1FlaWLg3kkE0m4z80kWyTpcAAYhBeOtSPFNmcICAAL7+oA)

```sh
--parser markdown
```

**Input:**

```markdown
[link](https://www.google.fr/()foo->bar).
```
Note that the link contains a `>` character.

**Output:**

```markdown
[link](<https://www.google.fr/()foo->bar>).
```
Now it's broken because of the `>` character inside the link matching the first `<`.

**Expected behavior:**
Either:

```markdown
[link](https://www.google.fr/()foo->bar).
```
(no change -- this is valid markdown)

or:

```markdown
[link](<https://www.google.fr/()foo%3Ebar>).
```
The latter is probably easier to implement.

See the spec in https://spec.commonmark.org/0.30/#link-destination.

Thanks!

**Comment by vivekjoshi556** [comment]
Hi. I worked on this issue. I encoded the angular brackets so that the link won't break.

Please check this PR #15400 and let me know if anything else needs to be done.
