### ISSUE TITLE
ESM config modules are not loaded

### ISSUE THREAD

**Issue by notaphplover** [prettier/prettier#15352]
**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: NodeJS
- Runtime: Node.js v18
- Operating System: Linux
- Prettier plugins (if any): None

**Steps to reproduce:**

1. Create a new npm package: `mkdir my-pck && cd my-pck && npm init`
2. Install prettier: `npm i -D prettier`
3. Add a `prettier.config.mjs` like this one:

```js
export default config = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  bracketSpacing: true,
  arrowParens: "always",
  endOfLine: "lf",
  trailingComma: "all",
};
```

4. Run `npx prettier ./*.mjs`

**Expected behavior:**

I expect the prettier conifg to be loaded and the prettier config to be formatted.

**Actual behavior:**

An error is thrown:

```
[error] Invalid configuration for file "[...]/prettier.config.mjs":
[error] require() of ES Module [...]/prettier.config.mjs not supported.
[error] Instead change the require of [...]/prettier.config.mjs to a dynamic import() which is available in all CommonJS modules.
```

### Caveats
- [Docs](https://prettier.io/docs/en/configuration.html) claim prettier is using [cosmiconfig](https://github.com/cosmiconfig/cosmiconfig), but prettier is using [lilconfig](https://github.com/antonk52/lilconfig) instead.

**Comment by fisker** [comment]
```diff
- export default config = {
+ export default {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  bracketSpacing: true,
  arrowParens: "always",
  endOfLine: "lf",
  trailingComma: "all",
};
```
