### ISSUE TITLE
formatting is worse with 3.0.0

### ISSUE THREAD

**Issue by unicornware** [prettier/prettier#15358]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbOAnAczgHUBLGAC0wF5MAeAFUzgA94oATNTAeQCMAVnDAxSAMwCedAIZQJAPgA0mAKrM2CLpjxxpHaABsJvQcJgBhAK54jAbQC68gBQAdKJkxhLGCNlIAvfCRMAFl8IisfP0C8RTcPPmk0OGCGOPdMADpstAhrMBTVNwBKYLDCOEZlFXkaWuB47TgYa3dc-LhMnQ5LArpyoirVeWcnaTAwZTQ8MGK6zAaMjx0WvHcABzwIdfxRODQnadmuuB6+gcq04dHxsGD+IRFxKVkFZQBrOAk56nrGjw8AHoAFTA-4AzDA3iWGAECCkKAETCbba7YwAN2kBksnXBALBSwhUIAApAoBgFpYoO8oBAAO5QAC+mDysPhiLxHmBgM5ZIprLhCIIwSpNPp7lot1snwk9jcnJBBIh+MwAEkoJA-IjkVsdngYBisTjMpzIaaSZi8JTqbSGcyEZqheaeYSPAZmpgHb4hSKbeKaJgjtKvnKoArAZh9E0vHg0KR0XAcOFE+JPRrvdrZBwWTDBdrMdj9phpDpkQZpAiWaYRGhOamnKQ0A8zAAFcsIpwC9kEOYAMl7nqb1ZgbYrUAb6a1Pbmi2VAK9U4DuAqZEoTi8UQC+GUXaFygXQuKnMZ8tdmEBEY4cDECMTKL1BpZ7lulmwlnL8Gzy6ITTQ75gnIrK0kbXreYwTB8XzKLOc5ZNkV5oGAeCkOsMAQHghwzJB3zpLBmAFjiwQbmh0T4J2ubdvuk57pgMpHmejL0RCjLKLcTGYCxnhJDA64GNAcBOIkyTFCJbgnlAICKCA2yiOgyCgCWWx0i2JYIGgyAgNI6LwhwkkgHweDjJ8MAAMrSLgAAyt7IGIWLJFJBlGc0JnrOMQrIDAeA4lJyR+DZdlwD5QrugAipYEDwB5XmBSAAhoCwJnBXAYURXAUXeSAACO4XwC2urqSgSQALRQHApynHpnkVgYQrmL42DSBptKlXpcaIu6ACCMCeaQfAwnALb4FZLVILZBj2SAFAwNgBjEBQ5D7K5BQmWp5DxuQEgaWAaDqVJ6I4uqV6wCZSEoTAHWcCZBruv540xSiyTEIZ6waZs+z4AmekIsk+p5dIBANbdE2ubG+AaQaOyIchqF6ZsCIwGQHCUMgAAcAAMUk6NlpA6H9AONaNAVSTA0h8IjyNIAATFJ3hwAwpMFWNE1wNgfCnFeHAWbIBCWP9cAAGLoQ13XuYVMIQCAjKMkAA)

```sh
--parser typescript
--no-semi
--single-quote
--jsx-single-quote
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx
const mergeWith = <T extends Objectify<any>, U extends readonly ObjectCurly[]>(
  customizer: MergeCustomizer,
  base: T,
  ...source: U
): Merge<T, U> => {
  return source.reduce<Merge<T, U>>((acc, src) => {
    return properties(src).reduce<Merge<T, U>>((acc: Objectify<any>, key) => {
      /**
       * Outgoing property value.
       *
       * @const {unknown} outgoing
       */
      const outgoing: unknown = acc[key]

      /**
       * Incoming property value.
       *
       * @var {unknown} incoming
       */
      let incoming: unknown = src[key]

      // do recursive merge if incoming and outgoing values are plain objects
      if (isObjectPlain(outgoing) && isObjectPlain(incoming)) {
        incoming = mergeWith(customizer, outgoing, incoming)
      }

      // define property on accumulated merge result
      return define(acc, key, {
        ...descriptor(src, key),
        value: customizer(outgoing, incoming, key)
      })
    }, acc)
  }, cast(clone(base)))
}

```

**Output:**

```tsx
const mergeWith = <T extends Objectify<any>, U extends readonly ObjectCurly[]>(
  customizer: MergeCustomizer,
  base: T,
  ...source: U
): Merge<T, U> => {
  return source.reduce<Merge<T, U>>(
    (acc, src) => {
      return properties(src).reduce<Merge<T, U>>((acc: Objectify<any>, key) => {
        /**
         * Outgoing property value.
         *
         * @const {unknown} outgoing
         */
        const outgoing: unknown = acc[key]

        /**
         * Incoming property value.
         *
         * @var {unknown} incoming
         */
        let incoming: unknown = src[key]

        // do recursive merge if incoming and outgoing values are plain objects
        if (isObjectPlain(outgoing) && isObjectPlain(incoming)) {
          incoming = mergeWith(customizer, outgoing, incoming)
        }

        // define property on accumulated merge result
        return define(acc, key, {
          ...descriptor(src, key),
          value: customizer(outgoing, incoming, key)
        })
      }, acc)
    },
    cast(clone(base))
  )
}

```

**Expected behavior:**

the input and output should be **exactly** the same.

**Comment by unicornware** [comment]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AAQDMBLAGzlwFUpSZcAVOAZxhdwFpcIA3OAE4B3AfTg58RALYQAJgFdKuGPJgUWqVetTw2G+XRio+gkWInpUOHKSkAHCAIYwAnnaoA1OAAtSYJcQCEFK4AOQAxGQAHioCrDpu8fy+-nChNvaOzqwwAMryAEYAVnBgDIHBYQB0Vcb8wqLw6VA4sqxgogVwABShBvRIWuQaJg1ioQA0uN0AlLgAvAB8uMASuPS9LN4QirK4cbF4o2bw+6yKMJPTc0sra7i4qKi4AIICAgCGUADm4ngPuEgUDYuAKHxYcCQK1wvFIUChXhSlAA2qFYVBQgBdXAAXwW0PRUNCoVx90B0BBLAAjFDgDCBFIoWxRD9cfi6bwGVDiB8ANaCKrJPyUQUM2ak-4PIGUgBMtJhcIRPmFcFR6KxbPmBMVuB5-IEguVqUFcPFOOsksezxeZVwAGpcABRKLuMpkuAu0owbq6PKFEplbpgiFTamhmUzGZVGAQKpwACO5G6LAjVQKqiqUAgMDj8fkHyTwbgMzWOJLUDLOBAExAEDsagpyFAH3eECEAAUWwgWMgQB9eBBSLJqyACp8wPy8h8pHAADJwuDIHnDOA1scfCdwPJ2Ddw77IGACeSrkAQqSkJcFkOnveUACK8mzi6Qh+PNaKLCiuVvcAfT4PR4nnmT7tkEdg9ig4KcFAcBwG0w41oeHwUHuADCwRSB8vZZjBI4sD+LwwIepDpvA7aCPOuFIMu17eDAUjkAA6r4ug7mAcC5N29CkLCri9mALA9jWvDHgAklAbSwLkHSkPWLwSbkriUJeK41nYQQQoxnx2L26msII-AjnCEJOKBHzfJhKnXjuAgmb2rjuCwMn1iO6lwjAjFDjA3jIAAHAADDWcR5qQcRmRZWHUVeJ4wB8BSebI3nIDKNbyBCjBxRBNEnnAUhdLI8Gzl83z5r8ABijiYURe69h8qgQCAOI4kAA)

```sh
--parser typescript
--no-semi
--jsx-single-quote
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx
/**
 * @file Unit Tests - overwrite
 * @module tutils/utils/tests/unit/overwrite
 */

import type Vehicle from '#fixtures/types/vehicle'
import testSubject from '../overwrite'

describe('unit:utils/overwrite', () => {
  it('should return overwrite result', () => {
    // Arrange
    const base: { vin: Vehicle['vin'] } = { vin: '' }
    const s1: { vrm: string } = { vrm: faker.vehicle.vrm() }
    const s2: { vin: Vehicle['vin'] } = { vin: faker.vehicle.vin() }

    // Act + Expect
    expect(testSubject(base, s1, s2)).to.eql(s2).but.not.equal(base)
  })
})

```

**Output:**

```tsx
/**
 * @file Unit Tests - overwrite
 * @module tutils/utils/tests/unit/overwrite
 */

import type Vehicle from '#fixtures/types/vehicle'
import testSubject from '../overwrite'

describe('unit:utils/overwrite', () => {
  it('should return overwrite result', () => {
    // Arrange
    const base: { vin: Vehicle['vin'] } = { vin: '' }
    const s1: { vrm: string } = { vrm: faker.vehicle.vrm() }
    const s2: { vin: Vehicle['vin'] } = { vin: faker.vehicle.vin() }

    // Act + Expect
    expect(testSubject(base, s1, s2))
      .to.eql(s2)
      .but.not.equal(base)
  })
})

```

**Comment by unicornware** [comment]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AAQDMBLAGzlwBUBPAByoBE4ypSZToBnXAWlwAlOJCjcYAJwCuYGAEEJEgIa0c+IgFsIAEymVcMKZ3LdUMBnFPDR46bIXLVedKhw5SG+hAkwDF3ACinuYOKrjEEhAauADkAHSocMG0fEqKKjHunt6+5oy4AJLEAHJSGgBGcBLhkdHxqKTEfFBllRKZ7Nk+fvlFpRpVpGA1UbEJjc1lg2AdHl7deVQF3HJQtCN149ypa7Nduf7LxXAAblUbYw3bUKdVe-MH+QAyCADmMAAWF-WUUO8f9xyPSo1Ck9EoADFatZvNpvglDOC4HwIlE+BIRLDAQt-ABVKAAd2U9H603hqCkhOJkwGEiGHRwGGwzlwAAUMTBzLh6HTYLglHg0o4+ORSABrKgQcoAKxEMDiamZ6kIpFgVSgSnIisVRHgnnISngNH4NH8MAguFOmqkhrgitcsH8MLEkhk8nStAAPNQAHy4AC8hRWa29frgAA94FBtLxXXa8LgAPw0ADaAF01LgkEHjmcJKHLZGEDGDNJ47gk4FkqEnBXs9RC1GSxilNpoOR1pSxVAIASoOnM8mABSZisV4CjscVlMAaVwqtwEtoEGIxqUvD6rSqnsnU4rM4ANLu9y0KucI03eHPkzc81ncIfj1PN7Shp7D7h8USlCSpnSwO+PoHrgt5VD6T64D6ab1rOGYJlOAC+jbFrwqrEOcACyyHRrwwC4LO854KebRpom2Zdj2fa4AhEE3lu1QXihuAvH8nyhhBFbDhhKZLiuuAYWmuAAD6psRVRpgAlAO8F7nWNBgpC0KYhI2iehh4EyVO2agRIk4SdhJZoecAAaBm8C2bZQB2uAUb2-ZwVOw4QQ2jE4TZUDdnZ6aVqZ2bCK27ZesZGmyfprmGVA6HVAAmmZuAWYF7meX20mycmE6aXuBELrxq4NuuhQlH+b4cWOj6ZbJOlHhVe5zuFvC5UllH2ZWOn3jOpVQTBM4ObJ1FxUZ1QAFq0Tmtz5o1Q1hkWblxqVybRaV2axQAZLgI01dp43HlteaTrtVSZvWbg3OGDzArgeHOrYbo1vyvDaKwSh6L4NFQCAB4gBA9CcDwyCgEKvasmkCDcMgIBKCcECkNoH0gOUyhgBKMAAMpKAMTyqnAyDEJq3BwJ9CNKEjcCo-QxOqq8yBxp9+MaKQON4wTIDcJTlAAIpSBA8DU2Wn3Stw4Yo2zcCc9z2NIDTIAAI5c-A7LfWDKDrs0cBwI9sOfZISgUJTADCUQaEo4M9jccOs38lByJydLlEYcCslUmNm0guMmMzHwwBo5AAOofBwljk2AcAo6DHCkCcHC0ODYDcGDn0nFIcAFNGCCo2AdI-as2go+YlCM+7n08hA+M+8S4M8pYVRnHDqr4z47JKK8RsF-jRdpPX4OLNwGekD9cM8qqMA+zDnzIAAHAADJ9GKy6QGKN83xuu0zWtKOUI-aGPSAAEyfVI+PUOvStu23IBJJU2ga08AqvDarxwBC3hG5ylPg895ogAhCFAA)

```sh
--parser typescript
--no-semi
--single-quote
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx
/**
 * @file Type Definitions - ReconstructArray
 * @module tutils/types/ReconstructArray
 */

import type EmptyArray from './empty-array'
import type IfNumber from './if-number'
import type IfNumeric from './if-numeric'
import type IsAny from './is-any'
import type IsNever from './is-never'
import type Length from './length'
import type TupleFromRecord from './tuple-from-record'
import type UnwrapNumeric from './unwrap-numeric'

/**
 * Pretty print an array-like object.
 *
 * @internal
 *
 * @template T - Type to evaluate
 */
type ReconstructArray<T> = IsAny<T> extends true
  ? T[]
  : IsNever<T> extends true
  ? EmptyArray
  : T extends readonly unknown[]
  ? (
      {
        [K in keyof T as IfNumber<
          K,
          number extends K ? never : K,
          IfNumeric<K, UnwrapNumeric<K>, never>
        >]: T[K]
      } extends infer M extends { [K in number]?: unknown }
        ? number extends Length<T>
          ? (M[keyof M] | T[number])[]
          : TupleFromRecord<M>
        : never
    ) extends infer X extends readonly unknown[]
    ? (
        T extends unknown[] ? X : Readonly<X>
      ) extends infer Y extends readonly unknown[]
      ? {
          [K in keyof T as IfNumeric<
            K,
            never,
            K extends keyof unknown[] ? never : K
          >]: T[K]
        } extends infer Z
        ? IsNever<keyof Z> extends true
          ? Y
          : Y & Z
        : never
      : never
    : never
  : T

export type { ReconstructArray as default }

```

**Output:**

```tsx
/**
 * @file Type Definitions - ReconstructArray
 * @module tutils/types/ReconstructArray
 */

import type EmptyArray from './empty-array'
import type IfNumber from './if-number'
import type IfNumeric from './if-numeric'
import type IsAny from './is-any'
import type IsNever from './is-never'
import type Length from './length'
import type TupleFromRecord from './tuple-from-record'
import type UnwrapNumeric from './unwrap-numeric'

/**
 * Pretty print an array-like object.
 *
 * @internal
 *
 * @template T - Type to evaluate
 */
type ReconstructArray<T> = IsAny<T> extends true
  ? T[]
  : IsNever<T> extends true
  ? EmptyArray
  : T extends readonly unknown[]
  ? (
      {
        [K in keyof T as IfNumber<
          K,
          number extends K ? never : K,
          IfNumeric<K, UnwrapNumeric<K>, never>
        >]: T[K]
      } extends infer M extends { [K in number]?: unknown }
        ? number extends Length<T>
          ? (M[keyof M] | T[number])[]
          : TupleFromRecord<M>
        : never
    ) extends infer X extends readonly unknown[]
    ? (T extends unknown[] ? X : Readonly<X>) extends infer Y extends
        readonly unknown[]
      ? {
          [K in keyof T as IfNumeric<
            K,
            never,
            K extends keyof unknown[] ? never : K
          >]: T[K]
        } extends infer Z
        ? IsNever<keyof Z> extends true
          ? Y
          : Y & Z
        : never
      : never
    : never
  : T

export type { ReconstructArray as default }

```

**Comment by unicornware** [comment]
in the examples above, prettier has made **unnecessary** formatting changes that result in considerably uglier code. are these changes permanent? i was using prettier prior to this, so these changes are not only unwanted, but unexpected as well.

**Comment by unicornware** [comment]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAgHNMIAjbTA4AHSgIIDc8CAzbAazlyQJgE8ADnAisCASwC2giLhgAKAOQABdl1wBaAFYBnAPRruigJQBtRYdyKAunQC+dOnAAeMudQdQQAGhARBMOLQOsigeLgQAO4ACngIISjYjBDiqD4gZLjYYFwwAMrYknAAMuJQcMjsmDpwvpnZuXmC2WVEyDC4AK61IDWS4pWUNb46rZhwAIqdEPDtXT26znljk9OzSFXDIACOa3DREYIJINg6GuVw6Gm+HdjimK0AwhCSktjIIFDQFSMrAIIwDriMideDRbilcqDao9AAWMEkmAA6rDxPAdM0wHA8vE0eJGGj+B8wDoQr5GN0AJJQdCwPJgXDiAJ-Gl5ATjaFbQQRGpIrKCD7cuA1XCMH4gMoimAHbBEN6cnrNXAij4CYQ6BlMmDpbllGBI1IwWHIAAcAAZfPhduJ8DK5e8NkMejBsGQDagjcgAEy+To1AAqroSmx6cEkZEuV2K2CgRE6srgADFZG9Aa0PthQRAQHY7EA)

```sh
--parser typescript
--no-semi
--single-quote
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx
declare global {
  var faker: typeof import('@faker-js/faker')['faker']
}

export {}

```

**Output:**

```tsx
declare global {
  var faker: (typeof import('@faker-js/faker'))['faker']
}

export {}

```

**Comment by fregante** [comment]
It's hard to tell the difference with these huge blocks of code, but the differences I saw are definitely improvements in v3, except maybe the last one

**Comment by unicornware** [comment]
@fregante 

1. i updated the code blocks
2. i would **not** consider any of these changes improvements, especially the changes in the first three examples. does that mean my only options are being stuck on `2.8.8` or switching formatters? as i mentioned above, i was using prettier prior to this, so these changes are both unwanted and unexpected

**Comment by fisker** [comment]
Close since it's not actionable. You can choose to stay at an old version.

**Comment by fisker** [comment]
@fregante About the last one, https://github.com/prettier/prettier/issues/14990#issuecomment-1614537479

**Comment by unicornware** [comment]
this is a bug in my book, but okay.
