### ISSUE TITLE
Please unarchive `stylelint-config-prettier` and allow installs on v15

### ISSUE THREAD

**Issue by fregante** [prettier/prettier#15355]
The repo was archived because Stylelint deprecated stylistic rules in v15, which makes sense, but they key here is "deprecated", not "removed".

I'm using a [shared config](https://github.com/xojs/stylelint-config-xo) that hasn't been updated for v15 yet, so it still includes all those rules, causing deprecation warnings.

I'd like to be able to use `stylelint-config-prettier` for what it was made to do: disable stylistic rules, which still exist in v15.

**Comment by fregante** [comment]
I'd like to note that I can still install it for v15, but npm will show a verbose warning for every and each install unless I disable peerDependencies checks for the entire project.

Also it looks like a few rules are missing from the config:

```
 - The "function-whitespace-after" rule is deprecated.
 - The "media-feature-range-operator-space-after" rule is deprecated.
 - The "media-feature-range-operator-space-before" rule is deprecated.
```

**Comment by fisker** [comment]
#15033

**Comment by fisker** [comment]
I may misunderstood the request. 

I think you should remove these rules from `stylelint-config-xo`, you already submit an issue there, https://github.com/xojs/stylelint-config-xo/issues/19

For others should just remove `stylelint-config-prettier`.

**Comment by fregante** [comment]
Right, but "just doing things" isn't always easy. In fact my PR was rejected as I wrote it. Plus as I said the rules are still part of Stylelint, so it makes sense to keep this config around until the rules are actually removed.

**Comment by fisker** [comment]
The `stylelint-config-prettier` repo is not maintained by Prettier core team.

@shannonmoeller Any comments?

**Comment by fregante** [comment]
Suggesting to create forks instead of just changing one line and running npm publish isn't the best solution to this. I already have my solution, but more will have the same problem and this is a general waste of human resources for all.
