### ISSUE TITLE
Plugins not detected when running prettier CLI, configured via prettierrc

### ISSUE THREAD

**Issue by gitKrystan** [prettier/prettier#15351]
**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: CLI
- Runtime: Node.js v16.20.1
- Operating System: macOS
- Prettier plugins (if any): https://github.com/gitKrystan/prettier-plugin-ember-template-tag

**Steps to reproduce:**

Repo:
https://github.com/gitKrystan/prettier-plugin-ember-template-tag/tree/e97eb70f089fefbc20f3b98a2be91c7753a3adee/examples

The plugin is added in a prettierrc file, like so:
```
module.exports = {
  plugins: ['prettier-plugin-ember-template-tag'],
};
```

Run `prettier . --write`

**Expected behavior:**

Because the plugin registers the `.gts` and `.gjs` extensions, I expect running `prettier . --write` to format `example.gts` and `example.gjs`

**Actual behavior:**

Running `prettier . --write` with this config in prettierrc does not format `example.gts` and `example.gjs`.

However:
Running `prettier . --write --plugin prettier-plugin-ember-template-tag` _does_ format `example.gts` and `example.gjs`.
Running `prettier **/*.{gjs,gts} --write` _does_ format `example.gts` and `example.gjs`.

Is this expected behavior? I'm a little confused based on the docs and past issues.

Thanks!

**Comment by auvred** [comment]
Probably duplicate of https://github.com/prettier/prettier/issues/15079

**Comment by gitKrystan** [comment]
Thanks! Indeed this sounds like a duplicate of that issue. I will close this one.
