### ISSUE TITLE
`--no-config` ignores the `.editorconfig`

### ISSUE THREAD

**Issue by mrazauskas** [prettier/prettier#15365]
**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: CLI
- Runtime: Node.js 18
- Operating System: macOS
- Prettier plugins (if any): none

**Steps to reproduce:**

Add `.editorconfig` file with the following content:

```ini
max_line_length = 120
```

Run `prettier .`, the `max_line_length` is respected.
Run `prettier . --no-config`, the option is not respected.

**Expected behavior:**

I would expect `--no-config` to only ignore Prettier config file, but respect `.editorconfig` settings. There are few reasons:

- The `--config` flag only takes the path to Prettier config file. Passing path to `.editorconfig` throws an error. (Perhaps it makes sense to allow `.editorconfig` paths as well?)
- There is a dedicated `--no-editorconfig` to ignore only `.editorconfig` settings.

**Actual behavior:**

The `--no-config` flag ignores `.editorconfig` settings. The documentation states: "Do not look for a configuration file." Might be just an explainer is missing. What is the configuration file in this context?

I find it useful to ignore only Prettier config file. An obvious thing, but better to write it down (;

**Comment by fisker** [comment]
I don't even understand why `--no-config` exits..

**Comment by fisker** [comment]
Since there is `--no-editorconfig` flag, I think make it only effect `.prettierrc` make sense.

**Comment by mrazauskas** [comment]
Thanks for quick reply. It makes sense for me too. Is that a breaking change? Hm..

**Comment by fisker** [comment]
Can you share why you use `--no-config`?

**Comment by mrazauskas** [comment]
See see documentation of the [`--find-config-path`](https://prettier.io/docs/en/cli#--find-config-path-and---config) flag. It speaks about the tiny performance cost introduced by resolving path to the configuration file each time running Prettier. Using `--config path/to/.prettierrc` makes Prettier slightly faster.

Unfortunately that will not work if a repo does not include a config file. In this case the `--no-config` flag can be used for the same result.

It’s minor gain, of course. But nice to have it.

**Comment by fisker** [comment]
Ah, make sense.

**Comment by mrazauskas** [comment]
For now I will remove the `--no-config` flag. That’s alright.

Adding an empty config file also would work, but somehow it’s not fun to check in empty files.

**Comment by mrazauskas** [comment]
Skip it. I am migrating to `dprint`.
