### ISSUE TITLE
// prettier-ignore NOT WORKING!!!???

### ISSUE THREAD

**Issue by blaasvaer** [prettier/prettier#15362]
Adding:

```
// prettier-ignore
```
to any js file does absolutely nothing, what am I missing?

I've set up the default formatter in VSCode ... but does NOT ignore formatting. It constantly indent the code as it normally would without the comment.

**Comment by fisker** [comment]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSgDMIIAKejDAIzgBp2OMAVwoAbAJ78MAShA8QELEWgBnZKACGOHBADuABU0JVKdSJ3qxquZxzqwAa3wBldQFs4AGUJQ4yBqeVeEBs7RxgnLDtvCmQYHEEgwNdCWPjE6JE4AEVBCHg-AKCAK2UADycM7Nz8pH8RQLkAR2q4PW0sYxB1ZVIfOAATAdkQOPVCEWiAYQhXV3VkLpERYeVKgEECHEJOQXg9Ei8fAvqggAsYVxEAdVPCeGVIsDgnIzvCADc7sQWwZSsQd4JACSUEGsCcYC2ijWoKcMDEmWODRAuAggSutiwC1wcECOHevjk3jxMDa6gocyRQUiODxC046m4yzkuG8MCuhH6MFOyAAHAAGOR4ZqEPBkinzWqFOQwRkcrk8pAAJjkgkCABVGcY6si4K5uP1Bv0POooBRBOS4AAxGhzAjRBbqXYQEAAX1dQA)

```sh
--parser babel
```

**Input:**

```jsx
// prettier-ignore
foo(
  be,
    ugly
   )
```

**Output:**

```jsx
// prettier-ignore
foo(
  be,
    ugly
   )

```

**Comment by blaasvaer** [comment]
Don't know if this was an attempt to help. If, then it didn't. I have no clue about what you were trying to say?
