### ISSUE TITLE
Multiple `xml-stylesheet` tags ending up on one line in XHTML file

### ISSUE THREAD

**Issue by loganrosen** [prettier/prettier#15387]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeA-ADwLYBsAEAbnAE4DOAltALwA6IAjAHQAM96AfLVNxjrgFoyMAJ644ZABZw4MfJJJwAZnXAKI2OEgD02gOa4IAIwCGubWQDWFKPsOncTMGTLsuUPniGjxUmXIVlVTB1TR1tIxIIAHcyUgtrWwAHRSVSBDAJbRTldKhMsicXN14sL2ExCWlZeVTg0K1dSJi4kgSbCxMoChgKAC84ABEKMwg9ItcQTm5S-m9KvxrAlXoQqLCmqNj4yFgEGE7u3oHh0fHnSc4QABoQCCTe6DJkUBMSLYAFN4RnlDNokwiZ63SImMCWWQAZRMmgAMjY4MglGY4iCSGCITBIUkwTY9MgYCQAK5wW5xbAUAnE0kgShQAxwACKRIg8CRKJpACsyJhIXjxMzWYikMjcKiQABHFnwD5RJK-EAmMgCKAyAAmcDVNxAhJMFFweIAwhpsCZkIrcLhtXSGQBBGCEihGIky0jw1XssU0yQwPAAdUkPQkOMykJ+PQohB6InNF21hBJAEkoBrYJCwCQKA9bSnIT5haLxSkIHE-eikuacq1iNqbK0YLKTHpTZ6i29WuafXhtSkbDA-RQ1TBJMgABwsW6KKUURSN5tmkUc24wExGAdDkdIABMtyJcQAKqvfoWaXBsEZNRq1bCunoiU24AAxCAkU0OvHmkwuiAgAC+v6AA)

```sh
--parser html
```

**Input:**

```html
<?xml version="1.0"?>

<?xml-stylesheet href="chrome://global/skin/global.css"?>
<?xml-stylesheet href="chrome://browser/skin/preferences/preferences.css"?>
<?xml-stylesheet href="chrome://browser/skin/sanitizeDialog.css"?>

<?xml-stylesheet href="chrome://browser/content/sanitizeDialog.css"?>
```

**Output:**

```html
<?xml version="1.0"?>

<?xml-stylesheet href="chrome://global/skin/global.css"?> <?xml-stylesheet
href="chrome://browser/skin/preferences/preferences.css"?> <?xml-stylesheet
href="chrome://browser/skin/sanitizeDialog.css"?> <?xml-stylesheet
href="chrome://browser/content/sanitizeDialog.css"?>

```

**Expected behavior:**
The `xml-stylesheet` tags should stay on separate lines for clarity/readability. This appears to be a regression in Prettier v3 (this didn't happen in v2).

**Comment by sosukesuzuki** [comment]
Prettier HTML printer does not support XML. Could you use https://github.com/prettier/plugin-xml ?

**Comment by loganrosen** [comment]
Unfortunately that plugin does not support XHTML. I tried forcing Prettier to use that plugin/parser on XHTML files, and it failed to parse them. Looks like we'll have to wait on #7397 and disable XHTML formatting for now in that case.

**Comment by sosukesuzuki** [comment]
I got it. I think it would be better to track this issue in https://github.com/prettier/prettier/issues/7397. So I'll keep this issue closed.
