### ISSUE TITLE
Need a way to parse ts and tsx files differently

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1538]
Right now, it can only parse the jsx variant.

```js
test.js: SyntaxError: JSX element 'any' has no corresponding closing tag. (2:15)
  1 |
> 2 | assert.notOk((<any>swapi._opts)['planet']);
    |                ^
  3 |
```

**Comment by JamesHenry** [comment]
This is the relevant config that needs to be toggled: https://github.com/prettier/prettier/blob/master/src/parser.js#L66-L68

**Comment by azz** [comment]
Is there a good heuristic for this? TypeScript it self (AFAIK) does not have one, it relies on the file extension to toggle on/off JSX support.

**Comment by azz** [comment]
Had a thought. We could parse with `jsx: false`, and if it throws an error, parse with `jsx: true`?

**Comment by vjeux** [comment]
If there is no /> or </, we can be confident that it's not jsx and parse it with jsx: false.

If we parse it with jsx: true and it triggers a "jsx unclosed element" error then we can try with jsx: false.

I think that those two heuristic would get us 99% there.

**Comment by vjeux** [comment]
#1551 is a reasonable heuristic.
