### ISSUE TITLE
`--write` to show text identifier for unchanged files ('grey color only' an accessibility concern 🧑‍🦯)

### ISSUE THREAD

**Issue by ADTC** [prettier/prettier#15396]
The output of `--write` can't distinguish between changed and unchanged text if color is not visible.

### Suggestion: Distinguish using text.

Consider that the use of color to distinguish changed vs unchanged files is not the best way to convey this difference. It has these problems:
* Visually impaired users may use a two-tone terminal that doesn't output any color information. It's impossible to distinguish in such case.
* Copying the log and pasting it somewhere else that only support plain text and no formatting, will cause the user to lose the color information. It's impossible to distinguish in such case.
* Scripts that grep the output cannot distinguish the files unless they programmatically inspect the color information. The `(cached)` keyword is unreliable as it only appears when `isCacheExists` is true.
* Cloud services that only log the text output and not the color information will not be able to display to the service user which files changed and which remain unchanged.

I think while the grey color is useful to visually distinguish, to solve the above cases we should also add the keyword `(unchanged)` after the file name. See example below.

### Example demonstrating suggestion

Take two exact copies of a project with three files, only the second of which will change in formatting.

With the current version of Prettier, running `npx/yarn prettier --write .` on first copy:

```
path/to/file1.ext 1ms
path/to/file2.ext 5ms
path/to/file3.ext 0ms (cached)
```
_(can't show color but you can imagine it: file1 and file3 will be grey)_

With a fixed version of Prettier, running `npx/yarn prettier --write .` on second copy:

```
path/to/file1.ext 1ms (unchanged)
path/to/file2.ext 5ms
path/to/file3.ext 0ms (unchanged) (cached)
```
_(can't show color but you can imagine it: file1 and file3 will be grey)_

Note: Although `(cached)` only appears for cached unchanged files, I would suggest not combining the keywords to `(unchanged, cached)` because it's harder to grep for both `(unchanged)` and `(unchanged,` in the output. Also any scripts that grep for `/ \(cached\)$/` would start to fail. That's why I suggest `(unchanged) (cached)`.

### Relevant information

Relevant code:

https://github.com/prettier/prettier/blob/f7959cccbfaf38f685b660f39eed061f5eec5ec2/src/cli/format.js#L432-L441

Relevant issues:

This was kind of hinted before in #3525 but apparently misunderstood. I believe the original author there possibly couldn't see the grey vs white distinction because the terminal didn't support colors, and everything was in the same color. This may have led to the **false** impression that all files are being overwritten when in reality, all filenames were being output to log, but only changed files were overwritten. If the output included the keyword `(unchanged)` this could possibly be avoided.

Suggestion to reduce verbosity was moved to #15480.

### I can open a pull request

I believe both suggestions can be achieved with a simple change:
* On line 435, change ``}ms`;`` to ``}ms (unchanged)`;``

Just let me know if the suggestions are acceptable.

**Comment by sosukesuzuki** [comment]
I agree with giving `(unchanged)` to output for accessibility.

**Comment by ADTC** [comment]
Thanks @sosukesuzuki how about showing unchanged files in debug-mode logging only?

**Comment by sosukesuzuki** [comment]
I don't have any opinion on it. If other maintainers want to progress it I can accept it.

But let's start one step at a time.

**Comment by ADTC** [comment]
Thank you @sosukesuzuki  🙂
