### ISSUE TITLE
Newlines added to mdx component content

### ISSUE THREAD

**Issue by JustinBeckwith** [prettier/prettier#15403]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAQgVxjaACACwCc4AzAXgB0QCcAHAZyQHpmATASwciLYDpIAW3ZwAbnAA2EOnCINmAQzp0JHMApgdoDAPxQ4AdwD6SlWo1ao5GEUxxqeSFKJUQAIyIKobagD4AwiQacHgAgsqozFg40L4gADQg0prayKAKREQQBgAKGQgMyCAKEgYKAJ6FiR4KYADWcDAAygqCcAAyHPrIpCUMcNWe9Y1NdLVdAObINnaJ-YIc07YDIAyTEnAAipgQ8D19KwBWDAAeTetbO3tIvRL9iQCOV3A5WYxFCgwAtPpwbH8JEA2BQcVRQCb+CCCQQKD4SCSAtbgjahHBEDhubAvWSdbo3A6JWiCCQAdQIHHgDDGYDgTQKFI4ogp5SKYAYVRAojsAElvAhmmB0XQYKFvE0YOUNvs7is6Fl+iTPHQinK4P0iOJAV11TBXgoJjDpfcQGM5LIioI2CdAXKujASRw2DACMgABwABkSJCeHBIeoNsPxMsSMAUbgdTpdSAATIlMP0ACphwpB41wQRuP7-NjtLwTTD6uAAMQgRBhOEmH2wEBAAF9a0A)

```sh
--parser mdx
```

**Input:**

```mdx
<Button href="https://discord.com/developers/applications?new_application=true" color="brand">Create App</Button>
```

**Output:**

```mdx
<Button
  href="https://discord.com/developers/applications?new_application=true"
  color="brand"
>
  Create App
</Button>

```

**Expected behavior:**
Since React components are potentially sensitive to white space within the tags:

```mdx
<Button href="https://discord.com/developers/applications?new_application=true" color="brand">Create App</Button>
```

**Why**
When newlines are added after the `<Button>` tag, it causes `mdx` to insert an additional `<p>` element when converting to React.  This additional `<p>` causes all kinds of spacing/layout issues, and is semantically changing the code from it's original form.

**Comment by tats-u** [comment]
Prettier supports only MDXv1.
They are almost identical in MDXv1.
#12209

**Comment by sosukesuzuki** [comment]
Thank you for the information. This issue is closed as it is included in https://github.com/prettier/prettier/issues/12209.
