### ISSUE TITLE
prettier --write should work for case insensitive file filter.

### ISSUE THREAD

**Issue by ikanni** [prettier/prettier#15405]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--write
```

**Input:**

```jsx
npx prettier --write  TestDB*
```

**Output:**

```jsx
[error] No files matching the pattern were found: "TestDB*".
```

**Expected behavior:**
```jsx
prettier --write should work for case insensitive file filter.
```

**Screen shot showing the issue:**

![image](https://github.com/prettier/prettier/assets/16600949/01ec41fd-f1b3-4ed7-8f10-286694f0ba44)

**Comment by sosukesuzuki** [comment]
I don't think we need to support this. For example, popular tools such as git also treat filenames as case sensitive.
