### ISSUE TITLE
[Windows] Error with file name containing square brackets and dots when running 'prettier --write'

### ISSUE THREAD

**Issue by saoudi-h** [prettier/prettier#15426]
**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: CLI
- Runtime: Node.js v18.15 
- Operating System:  Windows
- Prettier plugins (if any): No

**Steps to reproduce:**

1- Create a file with the name [...nextauth].ts at the root of your project (mine is a nextjs project).
2- Run the command prettier --write with this file as an argument.

**Expected behavior:**
I expected that running the 'prettier --write' command with a file named '[...nextauth].ts'  would execute without errors, formatting the file as intended.

**Actual behavior:**
 Observe the following error: "Explicitly specified file was ignored due to negative glob patterns."

**Comment by sosukesuzuki** [comment]
Hmm, I cannot reproduce

```
$ npx prettier --write '[...foo].ts'
[...foo].ts 75ms
```

```
$ npx prettier . --write
[...foo].ts 76ms
package-lock.json 15ms
package.json 1ms
```

**Comment by sosukesuzuki** [comment]
If you provide repository that reproduce it, we can investigate.

**Comment by saoudi-h** [comment]
> If you provide repository that reproduce it, we can investigate.

Hi

I created a repository that reproduces the problem. You can find it here :  https://github.com/saoudi-h/prettier-issue

I've included step-by-step instructions in the README file to assist you in comprehending my configuration and successfully replicating the problem.

If you come across any issues or require further information, feel free to reach out to me.

Thanks for your work.

**Comment by sosukesuzuki** [comment]
I see, this is a Windows specific problem.

**Comment by adarshjhaa100** [comment]
@sosukesuzuki I could help out debugging the issue if nobody's working on it

**Comment by sosukesuzuki** [comment]
Thank you, feel free to send a PR!

**Comment by fisker** [comment]
Should be something wrong in https://github.com/prettier/prettier/blob/270ea3e0903d5addbcdecbd3f9193f9213ee236b/src/cli/expand-patterns.js#L186C2-L186C2 and maybe related to https://github.com/mrmlnc/fast-glob/pull/423

**Comment by saoudi-h** [comment]
> Should be something wrong in https://github.com/prettier/prettier/blob/270ea3e0903d5addbcdecbd3f9193f9213ee236b/src/cli/expand-patterns.js#L186C2-L186C2 and maybe related to [mrmlnc/fast-glob#423](https://github.com/mrmlnc/fast-glob/pull/423)

Hi,

Indeed, there is a connection with fast-glob. By looking a little further, we can see that the difference between a request made on Linux and one made on Windows is at the level of the escapePath() function, which first checks which system we are in before deciding which regular expression to escape the pattern. This returns .\[.myFile\].ts on Linux and [.myfile].ts on Windows. This result will be used later to find the matching files. I imagine that this nomenclature is interpreted as a pattern and not as the name of a single file.

One solution would be to use the same regular expression as for Linux. However, I do not fully understand the other implications that such a simplification could cause.


https://github.com/mrmlnc/fast-glob/blob/28a3d61e44d5d9193ba97de4f21df6dc7725f7c0/src/index.ts#L107

can see the used regexp's here for each system
https://github.com/mrmlnc/fast-glob/blob/28a3d61e44d5d9193ba97de4f21df6dc7725f7c0/src/utils/path.ts#L13C1-L14C94

I also found this in the README.md of the fast-glob repo: 
https://github.com/mrmlnc/fast-glob/blob/28a3d61e44d5d9193ba97de4f21df6dc7725f7c0/README.md?plain=1#L267

**Comment by sosukesuzuki** [comment]
I think this issue should be reported to fast-glob with a specific use case.

**Comment by saoudi-h** [comment]
Hi @DamianGlowala,

not until now, I've just reported the issue on Fast-glob.

You can find it here: https://github.com/mrmlnc/fast-glob/issues/425

**Comment by brodwen83** [comment]
Hi everyone, have you found any workaround?

**Comment by sosukesuzuki** [comment]
Maybe there is currently no workaround other than not using Windows...

**Comment by saoudi-h** [comment]
> Hi everyone, have you found any workaround?

Hi,

If you're just looking to format or check your file:

 This doesn't work:
```shell 
    npx prettier --write ./src/pages/api/auth/[...nextauth].ts
```

This works: 
```shell
npx prettier --write ./src/pages/api/auth/*
```

However, if you're looking to automate the formatting, especially with Husky/Lint-staged, there is no clean solution to my knowledge. My approach was simply to temporarily disable my Lint-staged script during the commit of the problematic file.

Furthermore, you can work with WSL. In this case, this will work : 
```shell 
    npx prettier --write ./src/pages/api/auth/[...nextauth].ts
```

However, I couldn't get my Lint-staged script to run while keeping my directory in Windows.
I'm sure that if I moved my entire project into WSL, it would work, but it might be a bit overkill

**Comment by Bro3Simon** [comment]
>My approach was simply to temporarily disable my Lint-staged script during the commit of the problematic file.

I had to resort to this as well. 

1. Comment out `npx lint-staged` in `.husky/pre-commit` .
2. Commit `.husky/pre-commit` and problemetic file `app\api\auth\[...nextauth]\route.ts` . 
3. Uncomment `npx lint-staged` in `.husky/pre-commit` .
4. Commit `.husky/pre-commit`  and the rest of you changes.
5. Fix up latest commit into parent.
6. Push to origin.

**Comment by Di-void** [comment]
> > My approach was simply to temporarily disable my Lint-staged script during the commit of the problematic file.
> 
> I had to resort to this as well. It isn't a fix but a workaround until this is resolved.
> 
> 1. Comment out `npx lint-staged` in `.husky/pre-commit` .
> 2. Commit `.husky/pre-commit` and problemetic file `app\api\auth\[...nextauth]\route.ts` .
> 3. Uncomment `npx lint-staged` in `.husky/pre-commit` .
> 4. Commit `.husky/pre-commit`  and the rest of you changes.
> 5. Fix up latest commit into parent.
> 6. Push to origin.

I'm having the same issue on my project. I've been using these exact steps to get by but it's getting more and more frustrating😓

**Comment by saoudi-h** [comment]
A fix has been made to fast-glob by [mrmlnc](https://github.com/mrmlnc), so it's only a matter of time before it gets picked up by Prettier hopefully. See: https://github.com/mrmlnc/fast-glob/issues/425#issuecomment-1784067199

**Comment by ohadschn** [comment]
> A fix has been made to fast-glob by [mrmlnc](https://github.com/mrmlnc), so it's only a matter of time before it gets picked up by Prettier hopefully. See: [mrmlnc/fast-glob#425 (comment)](https://github.com/mrmlnc/fast-glob/issues/425#issuecomment-1784067199)

Why wait for Prettier?
Can't we just explicitly set `fast-glob` to 3.3.2 in our `package.json`?

**Comment by risu729** [comment]
Prettier bundles all dependencies in it, so we cannot override the dependency versions.
https://www.npmjs.com/package/prettier?activeTab=dependencies

**Comment by ohadschn** [comment]
> Prettier bundles all dependencies in it, so we cannot override the dependency versions. https://www.npmjs.com/package/prettier?activeTab=dependencies

May I ask why?
Some sort of DLL hell avoidance?

**Comment by risu729** [comment]
I guess so, but I'm not really sure why...
