### ISSUE TITLE
Prettier v3 doesn't run on plugin extensions

### ISSUE THREAD

**Issue by andershagbard** [prettier/prettier#15436]
**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: CLI
- Runtime: Node.js v.18
- Operating System: macOS
- Prettier plugins (if any): @shopify/prettier-plugin-liquid, prettier-plugin-tailwindcss

**Steps to reproduce:**

```json
{
  "singleQuote": true,
  "plugins": ["@shopify/prettier-plugin-liquid", "prettier-plugin-tailwindcss"],
  "overrides": [
    {
      "files": ["**/*.liquid"],
      "options": {
        "singleQuote": false
      }
    }
  ]
}
```

Running `yarn prettier . --write` only runs on "default" extensions, and not `.liquid` files, even though the plugin specifies `.liquid` as an extension.

Running `yarn prettier . --write --plugin="@shopify/prettier-plugin-liquid" --plugin="prettier-plugin-tailwindcss"` works as expected, and formats `.liquid` files.

Ref: https://github.com/Shopify/prettier-plugin-liquid/issues/208

**Comment by sosukesuzuki** [comment]
Duplicated of https://github.com/prettier/prettier/issues/15079
