### ISSUE TITLE
Ugly line breaks for conditional assignments

### ISSUE THREAD

**Issue by avin-kavish** [prettier/prettier#15439]
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcYYgGwgCdUBeVACgB0p10YIAlAcQCEBBCzAMwEsBzAHSRCRANowAFnAC2cALoBKVAH4VqGnVQBDMDF4A3OABVpclYP0x8cC-AAeMAMowAnjYsjim1IpAAaEAgAB31oLGRQbSIiCAB3AAVohAiUbXw47VcIwIAjIl0AazhnbTkAGV4oOGRudKw4PIKwYudg3Sr+ZBgiAFdGkFlcuAATEdHy7Sh+Xu1+OAAxYhltGH1p5BBtXoYAkEkYGXwAdUleeCx2sDgnFPPDc9dNsCwckCqGohgEgv4V2vqAwAVlh7E5OjYAIq9CDwAH4BqBdpET6bXLaYb4PbBIhVGDHXgjKTIAAcAAYkbEGscCsFNji4J8jHsAI4w+A-EKpLZYAC01VGoz2RDgbN4Ip+c3+SDqCIGDRkvG6fXlELg7DWuNyOzgCTgREq1XhiJAWDV0NhNRlgMCMAxBKJkmQACZbQVePhOgBhCAyaVbfBYwK9BrGDGpWUmgz9ACSUHGsCcYFxoXY8Zc7itkbgAF8c0A)

```sh
--parser babel
```

**Input:**

```jsx
  const color = (
    toRGBA(config.color[theme]) ?? 
    activeTheme?.title?.textStyle?.color
  )
```

**Output:**

```jsx
const color =
  toRGBA(config.color[theme]) ?? activeTheme?.title?.textStyle?.color;

```

Breaking after the assignment operator loooks sooo bad....

**Expected behavior:**

**Comment by sosukesuzuki** [comment]
Sorry, we cannot accept this probably.

**Comment by avin-kavish** [comment]
If I wanted to add it, do I have to fork prettier or is there plugin system?

**Comment by sosukesuzuki** [comment]
We don't have plugins systems that extends our default formatter. You can fork.
