### ISSUE TITLE
Add parentheses around `!...` on the left of `in`/`instanceof`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [prettier/prettier#15434]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQEIAemqUmAngJSbAC+AOlBjgUVAM4wCGUYcEWFVOlHqNsefJWJlKNEVjEFJbTt178ZQkABoQEAA4xU0VslAcATuYgB3AAoWEJlBwA21jqRM6ARuY5gAazgYAGUOAFs4ABliOGR0V1Y4Hz9A4JC9f2IAc2QYcwBXZJAk8NQ8wuLWHJc4AEUCiHh4xOKAK1Z8EJr6xuakBJcknQBHPrhbKz0nEA5WAFooODgAE1XtEHyOVBccgGEIcPCOZFmXFw3qqGzagEEYfNRvAvhbOHMYpZah4oALGHCLgA6r9UPBWJkeCFHGDUAA3MGkU5gVheEBwooASSga1gITA5lQBluOJCMFItW+wxAeisSSBfj0p1pcCS5jhcR0xDZMEmHGyxypxUy5jZp28HG8cAuOlpxBgQNQKxgv2QAA4AAw6cxwMaoHV8gUnAatHScbyK5WqpAAJh0BSSABVJU5BtS4OEpSs1isolxsgV+XAAGIQczHB45U4cF4QEDUahAA)

```sh
# Options (if any):
```

**Input:**

```jsx
if (!x in y) {}
if (!x instanceof y) {}

if ((!x) in y) {}
if ((!x) instanceof y) {}
```

**Output:**

```jsx
if (!x in y) {
}
if (!x instanceof y) {
}

if (!x in y) {
}
if (!x instanceof y) {
}
```

**Expected behavior:**

```jsx
if ((!x) in y) {
}
if ((!x) instanceof y) {
}

if ((!x) in y) {
}
if ((!x) instanceof y) {
}
```

**Motivation**

At a [TC39 meeting next week](https://github.com/tc39/agendas/blob/main/2023/09.md) we'll discuss about a proposal for `!in` and `!instanceof`, to allow writing `x !in y` rather than `!(x in y)`.

One of the main motivator factors is that it's very common ([see the slides that will be presented](https://docs.google.com/presentation/d/1vwNOjUiUvy6TzK6t0Mb8qgyKwBNszly9HibJJpUa_Eo/edit#slide=id.g27f462e9ca3_0_0)) to forget parentheses around `(x in y)` when writing `!(x in y)`.

I wonder if prettier could format `!x in y` as `(!x) in y`, similarly to how it formats `a ^ b | c` to `(a ^ b) | c`, so that developers can more easily notice that their code is wrong.

**Comment by fisker** [comment]
I like the idea 👍 .

**Comment by nicolo-ribaudo** [comment]
If anybody wants to open a PR, you probably have to add a check in https://github.com/prettier/prettier/blob/772c7b6305c53af7000b8f93af71d6b6258f071c/src/language-js/needs-parens.js#L20 for the case in which `parent.type` is `"BinaryExpression"`, `parent.operator` is `"in"` or `"instanceof"`, and `node.type` is `"UnaryExpression"`. You can then add a test somewhere in https://github.com/prettier/prettier/tree/main/tests/format/js/binary-expressions.

**Comment by lucacasonato** [comment]
I'm going to take this.
