### ISSUE TITLE
Change behavior of `max_line_length = off` to ignore line breaks

### ISSUE THREAD

**Issue by Richard87** [prettier/prettier#15446]
This is relevant: https://github.com/prettier/prettier/issues/14514

When I discovered the "max_line_length = off" option, and that Prettier supported it, I expected Prettier to leave newlines alone, and let me add them inn where I thought appropriate.

Instead I got *super* long lines.

I want to controll newlines my self, and if I want max_line_length to be `9007199254740991`, i can set it myself (or something more reasonable like 500, 5.000 or 50.000 :)

**Comment by sosukesuzuki** [comment]
Can you update this issue according to the issue template?

**Comment by fisker** [comment]
We don't have an existing option for the expected behavior "leave newlines alone", you can use `"off"` for your other tools, but you have to pick a `printWidth` in `.prettierrc` if you don't want us treat it as `Infinity`.

**Comment by Richard87** [comment]
Yes, thats what i found out.

My request is to make it work like I expexted (i hope Im not the only one that feels thid way).

But, is it something Prettier would be interredting in supporting? Would it be possible, or very hard? 🙂

**Comment by fisker** [comment]
We won't support it, sorry!
