### ISSUE TITLE
Different behavior when plugin is specified on command-line vs in a config file

### ISSUE THREAD

**Issue by jylin** [prettier/prettier#15469]
**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: CLI
- Runtime: Node 18
- Operating System: Linux
- Prettier plugins (if any): prettier-plugin-astro

**Steps to reproduce:**

When prettier CLI is run using a command-line argument like `--plugin=prettier-plugin-astro`, then it formats *.astro files automatically. When the plugin is specified in a .prettierrc file in the "plugins" field (I confirmed this works because it throws an error if the plugin name is incorrect), then it does not format *.astro files by default.

**Expected behavior:**

I would expect it to format *.astro files when the "prettier-plugin-astro" is enabled via configuration (e.g. .prettierrc or in a "prettier" field of package.json)

**Actual behavior:**

It only formats *.astro files when the plugin is specified directly on the command line via `--plugin=prettier-plugin-astro`.

**Comment by sosukesuzuki** [comment]
Maybe this is fixed by https://github.com/prettier/prettier/pull/15433. Please waiting next minor release.
