### ISSUE TITLE
Prettier Not Loading Plugins Directly Despite Global Installation

### ISSUE THREAD

**Issue by elnebuloso** [prettier/prettier#15474]
## Description

After globally installing both Prettier and its PHP plugin via Yarn, Prettier fails to load the PHP plugin directly, even when specific PHP version options are provided.

### Steps to Reproduce:

1. Globally install Prettier and the PHP plugin using the following command:

````shell
yarn global add prettier @prettier/plugin-php
````

2. Run the following Prettier command:

````shell
prettier . --check --ignore-unknown --no-error-on-unmatched-pattern --php-version 8.2
````

### Expected Behavior:

Prettier should be able to detect and utilize the globally installed PHP plugin without any errors or warnings.

### Actual Behavior:

The following warning is displayed:

````text
[warn] Ignored unknown option --php-version=8.2.
````

As a workaround, explicitly providing the plugin option allows Prettier to recognize and use the plugin:

````shell
prettier . --check --ignore-unknown --no-error-on-unmatched-pattern --php-version 8.2 --plugin=@prettier/plugin-php
````

Just for additional context, this functionality used to work as expected with Prettier v2. The issue seems to have arisen with subsequent versions.

## Additional Information:

- Prettier Version: 3.0.3
- Plugin Version: 0.20.1
- OS: Ubuntu 22.04
- Node Version: v20.7.0

**Comment by so1ve** [comment]
I'm not sure if this is the expected behavior because prettier has removed it's plugin auto discovery feature in 3.0

**Comment by sosukesuzuki** [comment]
Yes, since 3.0, plugins will not be loaded unless configured with the --plugin option or in .prettierrc. Please see https://prettier.io/blog/2023/07/05/3.0.0#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker
