### ISSUE TITLE
Prettier API throws config error for wrong plugin

### ISSUE THREAD

**Issue by austinbailie** [prettier/prettier#15473]
Prettier API throws this error when using the BABEL parser.

`ConfigError: Couldn't find plugin for AST format "estree". Plugins must be explicitly added to the standalone bundle.`

I don't understand why its throwing an error in general, as I do have the plugin added to the standalone. Also, I am using the Babel parser and its throwing an error for estree.

**My Code**

```
import * as prettier from "prettier/standalone"
import parserBabel from "prettier/plugins/babel";

prettier.format("foo ( )", { parser: "babel", plugins: [parserBabel] });
```

**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: Node.js API
- Runtime: Node.js v17.4.0
- Operating System: macOS
- Framework: NextJS

**Comment by sosukesuzuki** [comment]
Can you try with `prettier/plugins/estree`?

```js
import * as prettier from "prettier/standalone"
import parserBabel from "prettier/plugins/babel";
import * as prettierPluginEstree from "prettier/plugins/estree";

prettier.format("foo ( )", { parser: "babel", plugins: [parserBabel, prettierPluginEstree] });
```

Please see https://prettier.io/blog/2023/07/05/3.0.0#npm-package-file-structures-changed-12740httpsgithubcomprettierprettierpull12740-by-fiskerhttpsgithubcomfisker-13530httpsgithubcomprettierprettierpull13530-by-fiskerhttpsgithubcomfisker-14570httpsgithubcomprettierprettierpull14570-by-fiskerhttpsgithubcomfisker
