### ISSUE TITLE
The formatting of self-closing tags in HTML5

### ISSUE THREAD

**Issue by its-all-waves** [prettier/prettier#15475]
Can we revisit this please? There are options for nearly every aspect of the formatting except this... and it's a standard... that is being wholly ignored.

Why? 

Why, for example, give an option for trailing semi-colons in JS, but not provide an option to stop forcing the use of a trailing slash in the closing of a void tag?

W3 validation throws a million warnings per html page. Yes, we know this is inconsequential to the functionality of the code, but it seems outright silly to staunchly stand against this implementation when there's flexibility in nearly every other aspect of the formatter.

**Comment by sosukesuzuki** [comment]
Thank you for sharing your opinion. However, please do not create a new issue for an already open issue ( https://github.com/prettier/prettier/issues/5246 )

**Comment by its-all-waves** [comment]
I swear I could not interact with the original issue when I tried, although I can now... So sorry! 😳
