### ISSUE TITLE
Update `@babel/parser` to v7.23.0

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#15471]
[Babel 7.23.0 has been released!](https://babel.dev/blog/2023/09/25/7.23.0):tada:

So we need to support new features of JS:

## Source Phase Import

https://github.com/tc39/proposal-source-phase-imports

```js
import source fooSource from "foo";
```

## Defer Import Evaluation

https://github.com/tc39/proposal-defer-import-eval/

The import defer syntax only support namespace imports.

```js
import defer * as myMod from "./mod";
```

## Optional Chaining Assignment

https://github.com/tc39/proposal-optional-chaining-assignment

```js
maybeAnObj?.prop = theValue;
```

**Comment by fisker** [comment]
All done?

**Comment by sosukesuzuki** [comment]
Yes!
