### ISSUE TITLE
TypeScript breaks on long line with "as" expression

### ISSUE THREAD

**Issue by azz** [prettier/prettier#1547]
Currently prettier changes this:

```ts
    const config: PrettierVSCodeConfig = workspace.getConfiguration('prettier') as any;
```

to this:

```ts
    const config: PrettierVSCodeConfig = workspace.getConfiguration(
        "prettier"
    ) as any;
```

Which looks not very pretty.

I'd suggest we print like this:

```ts
    const config: PrettierVSCodeConfig = workspace
        .getConfiguration("prettier") as any;
```

Found when implementing TypeScript support in `prettier-vscode`:
https://github.com/esbenp/prettier-vscode/pull/100/files#diff-fa3857b18646da342e242c38dee65615L32

**Comment by vjeux** [comment]
This is actually not related to typescript. We don't break on the `.` if there's only a single call. The method chaining logic is very complicated and we've reached a local maxima around what works, if we start changing things it breaks other things unfortunately.

I would like to make it better but right now I don't know how to fix it, so I'm going to close this issue for now.
