### ISSUE TITLE
Prettier breaks XHTML documents by incorrectly lowercasing DOCTYPE

### ISSUE THREAD

**Issue by eligrey** [prettier/prettier#15476]
The change in https://github.com/prettier/prettier/pull/7391 caused prettier to break my XHTML documents by lowercasing the DOCTYPE, resulting in XML well-formedness errors for my use case.

DOCTYPE is case-sensitive in XML contexts. I cannot wrap it with prettier ignore comments as that would produce invalid XML.

**Comment by fisker** [comment]
We only lowercase doctype when it's HTML5.
Can you share an example that we break it?

**Comment by eligrey** [comment]
I have plenty of `.xhtml` documents that prettier started doing this to recently. Here's an example XHTML document that was affected (src redacted):

```xhtml
<!DOCTYPE html><script xmlns="http://www.w3.org/1999/xhtml" src="[...]"/>
```

**Comment by eligrey** [comment]
The HTML5 doctype is not orthogonal to XHTML (i.e. it does not indicate that the current document is non-XHTML). You should only apply this lowercasing to `text/html`, `*.html`, `*.htm` and `*.hta` files.

**Comment by sosukesuzuki** [comment]
@eligrey Could you share a specification text that indicates that XML doctype declarations are case-sensitive?

**Comment by eligrey** [comment]
Instead of finding a spec reference for you, I emplore you to create an .xhtml file locally and test this for yourself in literally any browser.

**Comment by eligrey** [comment]
[Here's the relevant standard](https://www.w3.org/TR/xml/#NT-doctypedecl:~:text=Physical%20Structures.-,Document%20Type%20Definition,%27%3C!DOCTYPE%27,-S%20Name%20\() which shows that XML requires an all-capital DOCTYPE.

**Comment by yoyo837** [comment]
In XML serializations (i.e. XHTML) the DOCTYPE is not required, but if you use it, DOCTYPE should be uppercase.

If the xml contains a lowercase doctype, the browser cannot parse it, but the uppercase one will not.

<img width="597" alt="image" src="https://github.com/prettier/prettier/assets/6134547/691ee9e1-459f-480a-8d2d-0e722df82e7c">

**Comment by eligrey** [comment]
@sosukesuzuki any updates here?

**Comment by dreampasssser** [comment]
I can't understand why they must modify it to lowercase. It's so stupid! Uppercase has become the default standard over the years.
