### ISSUE TITLE
Prettier omits necessarry parentheses of "satisfies" expression statements

### ISSUE THREAD

**Issue by seiyab** [prettier/prettier#15491]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFAJT7AA6U++kUAzjPjAJ4AOc+AvPgOSoQIvANxUaOVPiKsO3Lj36DeZStRr4ATnBjoN1GBvRwx+AL4np7OGXoBDXPVQ449fFDgA3OBtFqtOvUJbABt6OF9TEAAaEAg2XGh6ZFBbDQ0IAHcABVSEJJQQjNsWJJiAIw1bMABrbQBlWwBbOAAZHHdkVBCw8sqa+rYq9oBzZAMjGLDGnDHDOEmR4LgARXQIeE7u+ZAAK3oADzrFlbWNpC7Q7YBHU7gs9LZ8kFt6AFp3OAATL+iQA1scMERgBhCCNRq2ZDPYLBX70Y4AQRgBhwZXQ8Cy3jaHXOWxiAAsYI1ggB1fE4eD0QZgOB1PIUnAeCksKFgeilEAeIwASSg31gdTAGhw8QRfLqrCWm0uMTY6TCJMqbChcpc3i8v3aYQ0MHutmGEOlPRAgw02qhMhcQpFMF+cvaMBJOE+MHxyAAHAAGGJaG44LR6g2Q3Eyv62MpOl1upAAJhi6DCABVw-kLsa4I0yl9vp8WrYoMN0Pq4AAxCAaCHIkZQ2zoiAgUymIA)

```sh
--parser typescript
```

**Input:**

```tsx
function f() {
  const type = 'foo';
  if (type === 'foo') {
    return true
  }
  (type) satisfies never;
  return false;
}
```

**Output:**

```tsx
function f() {
  const type = "foo";
  if (type === "foo") {
    return true;
  }
  type satisfies never;
  return false;
}

```

**Expected behavior:**
Same as input.
The current output violates TypeScript syntax.
https://www.typescriptlang.org/play?ssl=18&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABMAFASkQbwFCMRBAZykSgE8AHAU0QF5EByYOOBgbl0RmERXOrq16TFgww48eAE5UoIKUihSQVTgF9OfSlQyEAhrELAYVQojBUAblSkdps+UmB6ANoSocN2UJFgJEAOboWJwEYMSk2nSIAETMcDF2XDxaAkL0cSwx4pz2cgqkyh7qnPw0+obGpuZWNkky+U6u7p7YQA

**Other contexts**
`expr satisfies never;` statements can be used for exhaustiveness checking.
https://dev.to/cefn/typescript-satisfies-never-exhaustiveness-checking-in-typescript-49-58fh
When `expr` is an identifier like "type", it looks to need parentheses.

As expressions probably requires parentheses such cases too.
Expression statement of as expression can't make sense, though.
```ts
(type) as unknown;
```

**Comment by sosukesuzuki** [comment]
I didn't now that...

**Comment by fisker** [comment]
```ts
(let) satisfies never;
```

should also add parens.

**Comment by seiyab** [comment]
Here are other keywords. I don't know where I can get complete list.
```ts
(interface) satisfies unknown;
(module) satisfies unknown;
(using) satisfies unknown;
```
[TypeScript Plaground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlmKBTATgMwIbCTAvDMAVwBtiBuAKAAoFl0skBKGCDKOCNOJCGQsANZgQAdzCVaqTNhZsOXHn0HCxlCqEiwAtiAAmJHPiKlKVHfuJNZ7Tt178ho8RXMHr8u0seqK68ND4IBABzPAIScmpCILBg5lYbBXtlJ0pokPdbRQcVcSA)

**Comment by fisker** [comment]
enum interface yield

**Comment by fisker** [comment]
`await`

**Comment by fisker** [comment]
@seiyab Would you like to work on it? We should add some extra logic here https://github.com/prettier/prettier/blob/19ea8ad8c227bde3952bab49748589e1297bd248/src/language-js/needs-parens.js#L43

**Comment by fisker** [comment]
This also breaks `flow`, #15130 not released yet, the following from playground of #15130.

**Prettier pr-15130**
[Playground link](https://deploy-preview-15130--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFAJT7AA6U++kUAzjPjAJ4AOc+AvPgOSoQIvANxUaOVPiKsO3Lj36DeZStRr4ATnBjoN1GBvRwx+AL4np7OGXoBDXPVQ449fFDgA3OBtFqtOvUJbABt6OF9zKBAAGhAINlxoemRQWw0NCAB3AAU0hGSUEMzbFmTYgCMNWzAAa20AZVsAWzgAGRx3ZFQQsIqq2oa2ao6Ac2QDI1iwppxxwzgp0eC4AEV0CHgunoWQACt6AA96pdX1zaRu0J2ARzO4bIy2ApBbegBadzgAE2+YkANbDhgqMAMIQJpNWzIF7BYJ-egnACCMAMOHK6Hg2W87U6F22sQAFjAmsEAOoEnDwehDMBwer5Sk4DyUljQsD0MogDxGACSUB+sHqYA0OASiP59VYyy2V1ibAyYVJVTY0PlLm8Xj+HTCGhgD1sI0hMt6ICGGh10NQwSyf3lHRgpJwXxgBOQAA4AAyxLS3HBafWGqF42X-WzlR3O11IABMsXQYQAKmGCpcTXAmuVvj8vq1bFARugDXAAGIQDSQlGjaG2DEQECmUxAA)

```sh
--parser flow
```

**Input:**

```jsx
function f() {
  const type = 'foo';
  if (type === 'foo') {
    return true
  }
  (type) satisfies never;
  return false;
}

```

**Output:**

```jsx
function f() {
  const type = "foo";
  if (type === "foo") {
    return true;
  }
  type satisfies never;
  return false;
}

```

**Second Output:**

```jsx
SyntaxError: Unexpected token `never`, expected the token `=` (6:18)
  4 |     return true;
  5 |   }
> 6 |   type satisfies never;
    |                  ^^^^^
  7 |   return false;
  8 | }
  9 |
```

**Comment by seiyab** [comment]
I might work on it later. But I'm not eager to do. I don't mind that you / someone fix it if they feel it is a serious issue for them.

**Comment by seiyab** [comment]
Probably binding the variable as another name can be an instant workaround.
```ts
const t = type;
t satisfies never;
```

**Comment by seiyab** [comment]
Babel parser also looks to have a bug around here https://github.com/babel/babel/issues/16047.
Some cases can't be put in regular typescript test case directory (but misc/typescript-only?).
