### ISSUE TITLE
Prettier adding closing </DOCTYPE> and wrapping <img> tags

### ISSUE THREAD

**Issue by mrjimhubbard** [prettier/prettier#15497]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAIgeQMIBUCaACgKIAEAFjALYA2AfADpSmmqW2k0CGUA5gLwMQCIY2YtW5OFwAmYiRNRU4MLqTDkuAJwDOKwSACquAGIBaABxDSAenkLWy1aShdlBgG4BLOAHcADhBaMNaQsAgwBr5eMjDk-DJw3mBwZtGx5AA0pF5QXjBeXDRmOmBFcPwAjAB0AAzWdkwOrAUwNHB0mFqJWqQAygCuVFTaAJ6k2BBUgVARqDat7fYKqDS5ANakWnA0Bjowo+06UirW5NsAZnsHR9VgOjoNy6w2UrJiTYoARhAyo88sVAyLwedTcB4GMrdUSfZqoLxUXiw5pgrgQoRSLQQMwIri8OBCZHNHRaMAGao2XH4nSUmg0Ab7LRcArQMyYiDVHQeJEgIkOIqRIQACTgWJyI3xhPEzUaUD5gOBoLA4J0kOgqlyoph0pRbAATKj0SBFgSQJ1uqL+kMRlpRvNyHqAYobIqnfNXcj5j8-vZ7dR6J95lg8ERiHQQJkQBB-CyoDpkKBtFjfIRtAh4ygir4uKN45GvkywOsVH03HAADKa5AXIp6fOF4swPr+LhgXK8ZAwLQDOCRvRULyd7u9kA6dvtACKAwg8GrtZHACsdAAPPrjuBTmdwOc0OsgACO0-ghCx-gzIDRZlmcESMgjxqZXjWfEmwy4yAvdPvY747QAgjAXZeF8AzHqKlazDue7sDQADq5D5HAOgtikfTpvkIL5KMH73HmIAeD2ACSUCJLAfRgFoXgxn+JF9Dc25IDWu4jv4WJ6LBTL+B+rFIaKHjbpGuR6MEJ54iMUEsdowkfl8XBfDs96sbkMCwTEcTIBYtSRtsh5eNsom8OJjHzpGqhfKpGTIHqkYMnAuByRmTF7nAVDyTIt7ljwvADHicAmEEIyAe2H5cKBEAgAAvhFQA)

```sh
--parser babel
```

**Input:**

```jsx
<DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Order Summary Component</title>
      <link rel="stylesheet" href="styles.css" />
    </head>

    <body>
      <div class="card">
        <img
          class="hero-image"
          src="./images/illustration-hero.svg"
          alt="Hero image"
        />

        <div class="container">
          <h2 class="title">Order Summary</h2>
        </div>
      </div>
    </body>
  </html>
  </DOCTYPE>
```

**Output:**

```jsx
<DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Order Summary Component</title>
      <link rel="stylesheet" href="styles.css" />
    </head>

    <body>
      <div class="card">
        <img
          class="hero-image"
          src="./images/illustration-hero.svg"
          alt="Hero image"
        />

        <div class="container">
          <h2 class="title">Order Summary</h2>
        </div>
      </div>
    </body>
  </html>
</DOCTYPE>;

```

**Expected behavior:**
There is no closing </DOCTYPE> tag so I don't expect Prettier to add one. I also expected Prettier to not wrap the <img> tag across 5 lines (yes Prose Wrap is set to "never").

These two behaviors do not happen when Prettier is not installed in VS Code.

**Comment by mrjimhubbard** [comment]
This is how it was entered in your online tool, but it will not parse without the </DOCTYPE> added
![i7 snagit 10-8-2023 9 03 16 AM ](https://github.com/prettier/prettier/assets/90149731/c28dc43f-7536-496a-a4c4-f33113c9d7f4)

**Comment by fisker** [comment]
You are using wrong parser, maybe you mean to use `html`? (change parser on left panel)

**Comment by fisker** [comment]
Also, it should be

```diff
-<DOCTYPE html>
+<!DOCTYPE html>

**Comment by mrjimhubbard** [comment]
Thank you. Changing that in the Playground worked for fixing the DOCTYPE issue (I had to remove the ! in <!DOCTYPE> to get it top parse before changing the parser from babel to html). 

But the issue of the wrapping img tag remains even in the playground - even with prose-wrap set to "never".

**Comment by fisker** [comment]
`--prose-wrap` only works for markdown. https://prettier.io/docs/en/options.html#prose-wrap

**Comment by mrjimhubbard** [comment]
That being the case, what setting stops Prettier from splitting the attributes of the img tag across 5 lines?
