### ISSUE TITLE
typescript parser doesn't convert object keys written as string numbers to numbers

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#15493]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mwAOlJpgOQAsADLdZUpjAE4CucZAviADQgIABxgBLdMlABDVqwgB3AAoyEaZCCkAbeVICeagQCNWUsAGs4MAMpSAtnAAyoqHGTYtaOEZPnLVoabOAObIbJwCnraioRxeIGjBmnAAiuwQ8G4ecQBWaAAeVokpaRlI7pqeAgCOJXCKckJqKFJoALQucAAmXfwgbFKimsEAwhC2tlLqWpq9CVBBSQCCMGyihuzwinCsTi6ZFXEAFjC2mgDqh6LwaAFgcFaqV6IAble66mBoBiDPnACSUG6sCsYFYohEi0BVhguiS+0qICEck8ZxMQnUSLgnlYz1cAmc2Jg9SkQQm8LiAVY2PUMKEWNB4JgvSRzhgZ1EnRgh2QAA5aAJWHAaqJBcTSZMylkBDApIZ2ZzuUgAEwCdieAAqsqa5QRcFshi63U6Dik83YJLgADEIKwJitglMNhAQNxuEA)

```sh
--parser typescript
```

**Input:**

```tsx
const foo = {
  '4004': true
}
```

**Output:**

```tsx
const foo = {
  "4004": true,
};

```

**Expected behavior:**

```tsx
const foo = {
  4004: true,
};

```

**Comment by fisker** [comment]
This is  intentional behavior see https://github.com/prettier/prettier/pull/8508
