### ISSUE TITLE
Allow customization of  doc output

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#1550]
It'll be great if prettier will allow some custom formatting choices to be configured on top of prettier.

I found that it would be possible, if developers will have a mean to customize `doc` structure after it's resolved by [`printAstToDoc`](https://github.com/prettier/prettier/blob/eabff629dd93ceeec713548ab2ce4b42622c8f22/index.js#L82) but before it's consumed by [`printDocToString`](https://github.com/prettier/prettier/blob/eabff629dd93ceeec713548ab2ce4b42622c8f22/index.js#L84).

While this probably can be achieved now by relying on [`__debug`](https://github.com/prettier/prettier/blob/eabff629dd93ceeec713548ab2ce4b42622c8f22/index.js#L116-L144) functions, this doesn't belong to public API. Is there a chance to receive some official (public) means to do that?

**Comment by azz** [comment]
^ Didn't mean to add that reference 😅...

I'd be interested to see the kinds of modifications you can make to the intermediate representation "doc" without the full context of the AST. I think it would be rather limiting.

For the near term, I think prettier will remain not pluggable (check with @vjeux for an official position on that though).

There's a lot of thought that would need to be put into making prettier pluggable, and I think the focus is on solidifying the printer as-is, as well as gaining adoption (this includes adding TypeScript support 😄).

**Comment by medikoo** [comment]
> I'd be interested to see the kinds of modifications you can make to the intermediate representation "doc" without the full context of the AST. I think it would be rather limiting.

I want to present var declaration blocks (ones especially containing requires) in following form:

```javascript
var eloBar     = require("elo-bar")
  , foo        = require("foo")
  , otherThing = require("other-thing");
```

while prettier does this:

```javascript
var eloBar = require("elo-bar"),
  foo = require("foo"),
  otherThing = require("other-thing");
```

I've already written some test decorator, that proves it's possible just by manipulating "doc" structure. I would even prefer to work with "doc" instead of full AST, as such whitespace manipulation appears to be easier when working with "doc" unified form.

**Comment by vjeux** [comment]
Thanks for the use case! Comma first notation is something that comes up often. While you can hack this for variable declaration using the IR (doc), it's going to be very tricky to do so in every places where we print sequences delimited with comma.

This really needs to be implemented inside of the printer. But even then, this is not easy, you first need to track down all the places where commas are printed and print it comma first.

Then, it's likely going to interact in strange ways with other ways we print things and you need to fix it. Also, you absolutely should not introduce bugs where printed code doesn't parse anymore or parses with different semantics. With JavaScript it's unfortunately easy to do.

You may think that you don't need it to be that good and can start with just a small hack. But in practice, you need this extremely high quality in order for people to use it. You are formatting all of people's code and give them no choice once they use the formatter after all.

I'm not sure how we can support your use case in a sustainable way yet, but I'm convinced that giving you the ability to tweak the IR after the fact is not going to work :(

**Comment by medikoo** [comment]
> you first need to track down all the places where commas are printed and print it comma first.

In my use case it's only about `var`, `let` and `const` blocks, I do not use (and don't want) comma first anywhere else. This makes probably things easier implementation wise, but indeed that's quite custom approach.

I understand it may be too personal to include within prettier as an option, still it'll be good to have some official door to apply it externally :)

> You may think that you don't need it to be that good and can start with just a small hack. But in practice, you need this extremely high quality in order for people to use it. 

I wholeheartedly agree!

**Comment by vjeux** [comment]
So, I do want people to experiment and I think that forking prettier is actually a good solution for this. Unfortunately, right now none of the tools in the ecosystem use the version of prettier that's checked in your repo, instead they bring their own, so this makes forking prettier not a viable solution. I do want to figure out a way to address this though.

**Comment by tqwhite** [comment]
I do almost entirely solo work so the goal of team formatting consistency is not so much of an issue for me. That said, I want consistency and admire the stance @vjeux has taken.

To accommodate my peculiarities (in particular, I find it essential that I am able to keep blank lines to help me navigate my code in process), I run prettier inside of a nodejs wrapper attached to my code editor. I capture prettier's output and do some transformation. 

I explain my process [HERE](http://tech.genericwhite.com/using-prettier-a-javascript-formatter-in-bbedit). 

Maybe that's easier than trying to change prettier. Good luck.

**Comment by azz** [comment]
@vjeux `prettier-vscode` will resolve a local copy of prettier if you have one!

https://github.com/esbenp/prettier-vscode#prettier-resolution

**Comment by azz** [comment]
@medikoo Why not replace `  ,` with `var`? Then you are more free to rearrange your imports. Is it a stylistic thing?

**Comment by medikoo** [comment]
> @medikoo Why not replace , with var? Then you are more free to rearrange your imports. Is it a stylistic thing?

Yes, to me code looks cleaner and more readable without `var` repeated every line, so yes, stylistic thing.

Thanks for `prettier-vscode`, it's good to know, I'll definitely make use of that.

**Comment by medikoo** [comment]
I published my customization here: https://github.com/medikoo/prettier-elastic-vars works well for projects I tested so far.

It's IR (doc) decorator that works on what's exposed on `prettier.__debug`, additionally original binary is reused with help of [proxyquire](https://github.com/thlorenz/proxyquire)

It still would be better if some official ends are exposed for that (even though I learned that due to various internal optimizations techniques it's a rocky terrain) :)

**Comment by vjeux** [comment]
This is really cool, thanks for doing this project :) I'm going to close this issue as it's not actionable on prettier side of things.
