### ISSUE TITLE
Formatting breaks syntax highlighting in template literals

### ISSUE THREAD

**Issue by Knaackee** [prettier/prettier#15509]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaCOAbTAXk0wHoAqbfTc0gAwB0oSXMBlAUQBkOBhAFRqYAZgCcIAW0zwMAbiZ0QAGhAQADjACW6ZKACGo8QHcACgYRpkIPXiN6AnpZUAjUXrABrODDZ6JcLk0oOGRhGzQ4FzdPbzY1dyCAc2QYUQBXSJAIiU0U9My0JLw4AEU0iHhQ8MyAKzQADzYi0vLKpDC8CJUcVrgTcTVLFD00AFpguAATKeUQVL1NPCTeSQk9Kxs8WcKoROKAQRhUzWc0+BM4UUDgqs7MgAsYCTwAdXvNGXiwODYLD80AG4fexWMBoJwgAEZACSUGmsDYYFEmg0+zhbBg9mKty6IDU4giLzcais+LgEVEAJCKiCFJg-T0iTWOMy8VEFKszj0zjgWxU+KCMBemkmMHuyAAHAAGFSiOA9TRyhlM9btaoqGDc4Wi8VIABMKjSEX43KGHVxcAkPMm00mXD0uzSjLgADEIKI1kckhszhAQABff1AA)

**Input:**

```jsx
    const sql =  /* sql */`
          SELECT * from test;
    `
```

**Output:**

```jsx
    const sql = /* sql */ `
          SELECT * from test;
    `;
```

The space between the `/` and the tick breaks the syntax formatting of the query (SELECT ....).

How to change this?

**Comment by sosukesuzuki** [comment]
What syntax highlighter do you use? I think this is an issue that should be reported to the syntax highlighting software rather than Prettier.
