### ISSUE TITLE
[format issue]  HTML parser crash for <p><div>anything or nothing</div></p>

### ISSUE THREAD

**Issue by cottom** [prettier/prettier#15527]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPlQEwJYBu2A9PkasViADQgTox7QDOyoAhgE6cQDuAClwSsU7ADa92AT1a0ARp3ZgA1nBgBldgFs4AGTxQ4yAGbjmceYpVr16JQYDmyGJwCuFkOa15nbj80cxOABFVwh4EzMPACtmAA91QJCwiKRTMXNaAEcUuH4edBEQdmYAWkM4HEqaEBd2PDFHAGEILS12ZGKxMRqAqAcggEEYFzw5V3h+OE59Q0iMjwALGC0xAHVFvHhmOzA4dWEtwi2pTrBmWRACdwBJKCrYdTBOPAZB+-UYKSD5zJB0HjmNaKdCdAFwcycAhGWgGSEwfLsBztX4eOycSGdZarGoAgwwNZ4HAwRbIAAcAAZaJw4Dk8DTEciOmkorQYOw5ITiaSkAAmWiucwAFQ5InSfzgWjklSqOF07H6riRcAAYhBOO0Ro5OuwJhAQABfA1AA)

```sh
--parser html
```

**Input:**

```html
<p><div></div></p>
```

**Output:**

```html
SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:15)
> 1 | <p><div></div></p>
    |               ^^^^
```

**Expected behavior:**
Format normal

**Comment by c2tz** [comment]
Hello @cottom , sorry for replying late. 

I don't think it's a problem with Prettier, it's more of a problem with your HTML code

The P element represents a paragraph. It can't contain block-level elements (including the P element itself). You need to use a span, for example. 

I don't think the error reported is a Prettier bug, just a syntax error, and Prettier doesn't allow it.

I admit that the error message can be confusing and should be more explicit.

**Comment by kachkaev** [comment]
This has been brought up in https://github.com/prettier/prettier/issues/11907 and https://github.com/prettier/prettier/issues/12610. Closing as duplicate.
