### ISSUE TITLE
Assignment of template literal to indexed access property causes odd formatting

### ISSUE THREAD

**Issue by jkillian** [prettier/prettier#15534]
I noticed today that assigning a template literal string to an indexed access property of an object can lead to odd formatting where the property access is broken into many lines.

This does not happen if 1) dot property access is used instead or 2) the RHS string literal uses normal quotes instead of template literal quotes.

Thanks for considering this issue!

**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAHAhgJ3QWwM4DaAOiJnACYCWZYMAKhCQLoAEAvCwAYAkwA7pSjkIfAHQAbCGHQxK0URhgALKLjgBfXgKEiJUmXKii8cLGCWb+g4WMnTZ8pejwXOAbhAAaEBFQOoeMigWJgiAApYCIEo6OJ86ACegd4ARthgANZwMADKagAygnDIAGaxJqnpWbkYYIIA5sgwmACucN4mOJRNre0geA3icACKLRDwpeV9AFZ4AB45gyNjE0hl4hUgAI4rcGGhqNEgzgC0UHAUFF4gzeiU4g0AwhA4OOjIx+Li1wNQ9UMAQRgzUoKRa8DCcEwhXOkw2fSUMBw4gA6kpKPA8LU4DkohjKAA3DEJD5gPDJEAEtoASSECFyYEwlD8AKEORgCSGcM2qFCJhR2FQH15cBMmAJxW8gjFMH26Hqb25fQwmDFHxS6BScG+3l5ghgKMo5GUyAAHAAGbxkHbUPbYBXvNZTbwwTWG41KZAAJm8LRMdE10XWmzgOC15HIFHy6D+LXlcAAYhBMG9gQ0PuhwRAQOp1EA)

```sh
--parser babel
```

**Input:**

```jsx
params["redirectTo"] = `${window.location.pathname}${window.location.search}${window.location.hash}`;
```

**Output:**

```jsx
params[
  "redirectTo"
] = `${window.location.pathname}${window.location.search}${window.location.hash}`;
```

**Expected behavior:**

```jsx
params["redirectTo"] = 
  `${window.location.pathname}${window.location.search}${window.location.hash}`;
```

**Comment by coolCucumber-cat** [comment]
As a temporary solution do `params.redirectTo`. Might be short enough to wrap around
