### ISSUE TITLE
Support reading Prettier-specific settings from .editorconfig

### ISSUE THREAD

**Issue by benblank** [prettier/prettier#15530]
### Environments

- Prettier Version: 3.0.3
- Running Prettier via: CLI
- Runtime: Node.js v18.17.0
- Operating System: Linux
- Prettier plugins (if any): *none*

### Steps to reproduce

1. In an empty directory, create files with the following names and contents:

    <details><summary><code>.editorconfig</code></summary>

    ``` editorconfig
    root = true

    [*.md]
    max_line_length = 40

    # Various potential prefixes
    prettier/prose_wrap = always
    prettier.prose_wrap = always
    prettier_prose_wrap = always

    # No prefix
    prose_wrap = always
    ```

    </details>
    <details><summary><code>example.md</code></summary>

    ``` markdown
    This is a single, long line which is intended to be wrapped by Prettier.
    ```

    </details>
2. Run `prettier example.md`.

### Desired behavior

The `proseWrap` option to be set using a key-value pair in `.editorconfig`, resulting in the line being wrapped at forty characters:

``` markdown
This is a single, long line which is
intended to be wrapped by Prettier.
```

### Current behavior

Only specific EditorConfig values read from `.editorconfig` are translated into their equivalent Prettier settings, which do not include `proseWrap`, resulting in no changes to the input file.

### Rationale

The primary motivation behind supporting Prettier-specific settings in `.editorconfig` is to centralize formatting configuration for projects, which both allows easier overview of formatting configuration and reduces the proliferation of configuration files.

#### Conformance to the EditorConfig specification

The EditorConfig specification (0.15.1 at time of writing; there don't seem to be versioned permalinks available) [implicitly supports](https://spec.editorconfig.org/#supported-pairs) keys not included in the specification, requiring that:

> * EditorConfig cores shall accept and report all syntactically valid key-value pairs, even if the key is not defined in this specification.
> * EditorConfig plugins shall ignore unrecognized keys and invalid/unsupported values.

Further, the EditorConfig wiki discusses [editor support](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#supported-by-a-limited-number-of-editors) for [keys not in the specification](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length).

#### Prior art

Notably, certain major tools in the .NET ecosystem (e.g. `dotnet` and Roslyn) allow configuration of a project's stylistic preferences [via `.editorconfig` files](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options).

Additionally, Prettier itself already recognizes keys which are not part of the EditorConfig specification (`max_line_length` and `quote_type`), though they are not Prettier-specific.

**Comment by fisker** [comment]
I'm 👎 for this, I don't want read prettier specific options from .editorconfig  file. Let tools do their own job.

**Comment by fisker** [comment]
@sosukesuzuki What's your opinion?

**Comment by sosukesuzuki** [comment]
I'm :-1: for this too. If you want to specify Prettier-specific keys, you should use prettierrc. In my opinion, the reason Prettier supports editorconfig is to avoid setting the same keys twice in editorconfig and prettierrc.

**Comment by fisker** [comment]
Sorry @benblank, we won't accept this.
