### ISSUE TITLE
Directives must be printed with the same escape sequences

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#1555]
Directives [are](https://tc39.github.io/ecma262/#directive-prologue) exact code unit sequences, which means that you can't change the escape sequences they use.

For example, prettier formats

```js
" \" ";
```
[as](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5C%22%20%5C%5C%5C%22%20%5C%22%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)
```
' " ';
```
but these are not the same directive, because they do not contain the same exact code unit sequence. (It's okay to change the type of quotation marks used, but only if doing so does not require changing any characters within the directive.)

This is one of the issues in #1553 (cc @josephfrazier).

**Comment by josephfrazier** [comment]
Ah, that explains this failure: https://travis-ci.org/prettier/prettier/jobs/230151061#L2848

Thanks for the cc!

**Comment by vjeux** [comment]
mind blown :)

**Comment by josephfrazier** [comment]
This should be fixed by https://github.com/prettier/prettier/commit/32d9d681548fc1b092bb10ece3ffa343e9e7bfd7

**Comment by josephfrazier** [comment]
Oops, nevermind! I merged that PR prematurely. See https://github.com/prettier/prettier/pull/1570
