### ISSUE TITLE
BUG! - prettier extremly load my CPU and I got infinity file saving with prettier code formetter

### ISSUE THREAD

**Issue by nicitaacom** [prettier/prettier#15551]
**Environments:**

- Prettier Version: 3.0.3

**Steps to reproduce:**
Just use pretter 1 day and save files and randomly you got an error in bottom right cornet 'saving file with prettier with codeformetter' and at this time prettier load my CPU

**Expected behavior:**
No errors or bugs or CPU payload

**Actual behavior:**
Prettier load CPU and infinity file saving

### Info
If you need more info - please let me know in comments

**Comment by sosukesuzuki** [comment]
This is difficult to investigate. Please post information such as reproduction repository and screenshots.

**Comment by nicitaacom** [comment]
> This is difficult to investigate. Please post information such as reproduction repository and screenshots.

Its diffucult to reproduce - just use prettier whole day and at some point you got info message in vs code that tells 'saving this file with prettier formatter' and during this process my CPU get load 100%

**Comment by sosukesuzuki** [comment]
I think this is an issue that should be reported to https://github.com/prettier/prettier-vscode rather than prettier.
