### ISSUE TITLE
Incorrect output (no semicolon + IIFE on next line)

### ISSUE THREAD

**Issue by Andreyco** [prettier/prettier#1556]
I am getting incorrect output if I explicitly don't use semicolon to end expression and IIFE appears as next code block. Formatted code is completely incorrect, dangerous possibly.

**Input**
```js
const result = 'whatever'

(function iife() {})();
```

**Expected output**
```js
const result = 'whatever';

(function iife() {})();
```

**Actual output**
```js
const result = 'whatever'(function iife() {})();
```

"semi" option turned off does not make any difference here.

**Comment by vjeux** [comment]
This is actually the correct output. This is how JavaScript will execute this piece of code. You should look into "Automatic Semi-colon Insertion" as to why it is doing that. http://cjihrig.com/blog/the-dangers-of-javascripts-automatic-semicolon-insertion/

**Comment by Andreyco** [comment]
Very correct. Sorry for false issue here.
