### ISSUE TITLE
Remove quotes in import attribute

### ISSUE THREAD

**Issue by sxzz** [prettier/prettier#15563]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmAF98AzHCdfAcmvwHdUYALQ-AHRBgE9M5OknAFYBnaJ3xEQAGhARMMVNBHJQAQxwV6ABQ0IVKNQBt6a7itkAjHGrABrODADKa9HAAyqKHGSljIuCsbe0cnTFsvAHNkGBwAV0CQAPRUGPjEkSijOABFOIh4X39E0QAPJyzc-MKkPyMA2QBHarhtCkwDEDURAFpvOAATQZkuG1QjKIBhSnQ1ZC6jIxHMqEjsgEEYWNRLOPhtOBxPbyL6xOYYdCMAdWYmOBFwsDgnfSZUADcmbnmwEQsQB8EgBJKBDWBOMA4VAKdZgpw8bJpBKyTAUALXGyYeZoh6HD4+WReAJ4NpqSKzU4NEDhHAk+aWNSWOBLVHQ2DXVADFjIAAcAAZZDg4M1UMKyRS5rVirIYEzOdzmMgAEyyOIBAAqTIMdWpcHQzIGQwG7jUqzi5LgADFcLMtlF5mo9hAQEQiEA)

```sh
--parser babel
```

**Input:**

```jsx
import {} from '' with { "type":"json" }
```

**Output:**

```jsx
import {} from "" with { "type": "json" };

```

**Expected behavior:**

```jsx
import {} from "" with { type: "json" };
```

**Comment by sosukesuzuki** [comment]
It is intended to remove quotes from keys in object literals. Does Import Attribute keys have a different meaning depending on whether it is quoted or not?

---

**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mwmAOiLhOUpgMyYC+A3KVCADQgQAOMAlumSgAhgCdREAO4AFMQjTIQwgDaThATwWcARqOFgA1nBgBlYQFs4AGT5Q4ybCrRwdew8ZPd9tgObIYogCuLiDO5nz+QSFovspwAIqBEPAOTiEAVmgAHiaxCUkpSI7KzpwAjgVw0hLcCijCaAC0dnAAJm0cIAHCfMq+AMIQ5ubCiirKnTFQPnEAgjABfNqB8NJwojZ2qSUhABYw5soA6rt88GheYHAm8md8AG5n6opgaFog98EAklDtsCZgUR8XizX4mGDqOLbUogbgSZxHPTcRRwuDOUT3eycWzomDVYQ+EbQkJeUToxTaYTaOATThw2wwI58VowXbIAAcAAZOKI4BU+Lz8YTRkU0pwYFSmSy2UgAEycQLOAAqVLqxRhcHM1Na7VaVmE00CBLgADEIKIRgtfGMVhAQAwGEA)

```sh
--parser babel
```

**Input:**

```jsx
const foo = { "foo": 3 };

```

**Output:**

```jsx
const foo = { foo: 3 };

```

**Comment by sxzz** [comment]
I think it's similar to object expression. Only need quotes for special characters like `-`

**Comment by sosukesuzuki** [comment]
Ah sorry, I misunderstood that output and expected were the opposite. understood. thank you.

**Comment by sosukesuzuki** [comment]
@nicolo-ribaudo Is it safe to remove quotes from Import Attributes keys using the exact same algorithm as for object literal keys?

**Comment by nicolo-ribaudo** [comment]
Yes, except for numeric keys like `"0"`.

**Comment by fisker** [comment]
... What about `"0n"`?

**Comment by nicolo-ribaudo** [comment]
Also not safe — the only valid keys are strings and identifiers.
