### ISSUE TITLE
No supported files were found in the directory

### ISSUE THREAD

**Issue by hqwlkj** [prettier/prettier#15587]
Directory:

![image](https://github.com/prettier/prettier/assets/12181423/a3674d84-633b-46bf-8e02-f0d89ce3ec8c)

`.prettierignore`

```
# Ignore artifacts:
.prettierignore
node_modules
build/
dist/
package.json
src/static/fonts/**
src/static/images/**
src/static/svg/**
yarn.lock

```

Abnormal screenshot:

![image](https://github.com/prettier/prettier/assets/12181423/8820cdeb-9a84-4648-a0c3-b3957aef0796)

**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: 
- Runtime: 
- Operating System: 
- Prettier plugins (if any): 

**Steps to reproduce:**

`prettier -c --write src/**/*`

Please tell me how to ignore several directories.

**Comment by sosukesuzuki** [comment]
Can using https://prettier.io/docs/en/cli#--ignore-unknown solve your problem?

**Comment by hqwlkj** [comment]
> Can using https://prettier.io/docs/en/cli#--ignore-unknown solve your problem?

Using `prettier -c --write --ignore-unknown src/**/*` does not take effect

**Comment by fisker** [comment]
Will it work if you quote the pattern?

```bash
prettier -c --write "src/**/*"
```

**Comment by hqwlkj** [comment]
> Will it work if you quote the pattern?
> 
> ```shell
> prettier -c --write "src/**/*"
> ```

When used in this way, the problem I described will occur. The main problem is that there are no files that need to be formatted in some directories. This problem will occur.

**Comment by fisker** [comment]
When you quote the pattern, it should work differently. Have you try?
