### ISSUE TITLE
Prettier does not detect git merge conflict markers within multi-line comment

### ISSUE THREAD

**Issue by tjcouch-sil** [prettier/prettier#15613]
Hello prettier devs! Thank you very much for all the hard work on this great tool. Our team loves it!

We are facing an issue with prettier not properly detecting git merge conflict markers in multi-line comments. It seems that, when a git merge conflict marker is in a file, prettier throws and logs `Error formatting document.` and `Merge conflict marker encountered.` instead of formatting the file. Example ([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdK6A82eYAQASAogIIAiSAZgJYA2cAdDAB4zoAqAFtVAOYDO6ALwjRQ9AGUYAV0qV0APiXKFeAOxqAnGoBsAEwCGAZgCsBgIzm9AIwAsJgBwAGa84NwATGrgO9Ok2AGlCYeTs4OOlR0jCxsGFAA9ABU6HhJeFzU-Hi0PHB4ehBw-FAA5DB4UHBwengwEHjW+ZxwAE5wADSN0hXUvbS00vwwrQbw2TAteFn80nBYuNiEpBQ09EysqekA8pNtddx82Tx4kAC2ZwhxYqJbeLstrXjDspTTUKcQF1eKKkrqWl0hlMFisdkcLjcnm8vn8gWCoXCkTWMU2H3SmWyuSqeAMtH4DUKxTKFSqNTqDSaeEenW6vX6g2Go3GB3yMzmWwSIA6IAgAAcYNRoPxkKADK1WhAAO4ABXFCBFKDxUoMAE8RTzrKMwABrOAwCQGS4AGTyyEoeP4nRAWoMuv1Ej5dp4vGQIzmPKtZ2obtaHpA-Bd9AAitIIPBzZbrQArfjMCRBuCh8NwSP460ARzD8Blkr5ipABn4AFoyXoatyQCMDHQXQBhL5nAzIQsDSuBvj0EgwEbUaw9OAytqmqppq08zgwM60ADq3HGTrAcAkCr61AAbn1VS2wPwNSB13MAJJQcuwCRgVrUAUkU9SVX0MfWvmSq0z0Z8lsv4ptdepnk8FarQwLmBi8E2T48k6rRAS21gGE0tCVi+PAwDO1B6JMyDODy7RZtQ7SgeBzZUFGPIwAh6GYZwyAeDyQxwOwCGKha6Y8nAZxNHo5Z6MaBh8NIYFwAAYhArRNj2LotgYPQQCAAC+8lAA)):
```
<<<<<<< HEAD:file.txt
Things
=======
Stuff
>>>>>>> 77976da35a11db4580b80ae27e8d65caf5208086:file.txt
```

However, prettier does not detect git merge conflict markers within a multi-line comment and successfully formats the document as follows:

**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAHSgAnTgFQAsBLAZxwBsSo4cATCOMqAchh1rnpxghwBGdInABOcADSCArhxJzKlaWRiiAhvAowROcmWlxsAHhOmjOABIBRAIIARJADMSlOADoYADxjY8OAPLaYrykUADmFDQ4kAC2MQg+UAC8KalJvviBIqI4KtKOjrq4sfGw2AB8lVXlOADstQCctQBs9GoAzACsagCMPfQCACydABwADALjanAATLVwI-TNnWBqjp0zY+MjzU4u7l6JfsTkVDR0apRk-IzMbBxcPHyCwmKSMnIKSirqmiF0egMGVQIAkIAgAAcYCRoGRkKA1KJRBAAO4ABURCDhKEuKLUAE84WCBOowABrOAwADKaniABlzshHJcyJIQCS1OTKVSIZyaGFkKoDGDWTESILRMKQGR+a4AIrSCDwJkstkAKzInipsrgCqVcBVVzZAEdFfA0ciIdiQGoyABaR7cUEgVRqFz8gDCEDiamQNsUzpl4VcNhgqhIAlkcDRYgZtENrLBRBgMUoAHVSJpeWA4FSsfISAA3eT4v1gMhEkCFgwASSg9ASVLAohIUJs9apMHxrgTbIhyNZafUEL9-eYYkLBrBNFZohgFrUYRivqcqrBvNEs79AjUQkozv7NBgaZI9G0yHGYPEppI4gXS5XzKNYJgu5PZ6IyBmYOUcAIu+xJ9ExAOAYiEegG3oOk1HCaRFzgAAxCBRGXMN+T9NRZAgEAAF8cKAA)

```sh
--parser babel
```

**Input:**

```jsx
/*
 * This line doesn't need to be here, but it illustrates the issue
<<<<<<< HEAD:file.txt
 * Other things in comment
=======
 * Other stuff in comment
>>>>>>> 77976da35a11db4580b80ae27e8d65caf5208086:file.txt
 * This line also doesn't need to be here, but it illustrates the issue
 */
```

**Output:**

```jsx
/*
 * This line doesn't need to be here, but it illustrates the issue
<<<<<<< HEAD:file.txt
 * Other things in comment
=======
 * Other stuff in comment
>>>>>>> 77976da35a11db4580b80ae27e8d65caf5208086:file.txt
 * This line also doesn't need to be here, but it illustrates the issue
 */

```

**Expected behavior:**
Prettier detects git merge conflict markers anywhere in a document including within multi-line comments, throws and logs `Error formatting document.` and `Merge conflict marker encountered.`, and does not format the document.

Thank you again very much!

**Comment by fisker** [comment]
Sorry, but we are not going to support this.

**Comment by kachkaev** [comment]
I agree with @fisker – the example contains a valid JS comment so it should be treated as such. It is possible that someone may want to explain what git conflicts are and how the codebase deals with them. We should not fail parsing in that case.

**Comment by tjcouch-sil** [comment]
That makes sense. Thank you for considering!
