### ISSUE TITLE
Trailing slash on void elements 

### ISSUE THREAD

**Issue by E-Emmy** [prettier/prettier#15612]
I'm having problems with prettier...I mean it's giving trailing slash to void elements like this <meta/>

And again giving unnecessary space  <meta charset= "UTF-8"  />.

Latest prettier 

IS THERE A WAY I CAN FIX THIS?

**Comment by auvred** [comment]
Please follow the issue template. Duplicate of https://github.com/prettier/prettier/issues/5246

**Comment by fisker** [comment]
Duplicate of #5246

**Comment by junaga** [comment]
@E-Emmy no, you have to install https://github.com/awmottaz/prettier-plugin-void-html
