### ISSUE TITLE
does prettier work with ejs?

### ISSUE THREAD

**Issue by ZEINTRY11** [prettier/prettier#15659]
**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeApAWgAQEspgA2ArgCZwAUAOiAA4CGATjLvYQM4D0AFnPeYxoAabMGwAjCDBG5SI4uziMo9ALZwR9AG70YTEYQgBzfAFVGhEQxjcRLGIThJsAAwDKcR2BjZ62RYxaSi4AvgCU2OgAfFRQsagAhJg4ADIQ-PhG2AAK9EZw2MkxUKikuFp4pAC8NIYZUEaYDPk0xdjt2Bg4+ERklDQAdJx1ZQ0DcABW7DQR0fGcZVrF8Uk4ALL0+Dl5BUXxi5U1IKqbUE07NP4wAJ6OR2XstIT0185Q0HAA3K2xHZ2r2AAwtA9PglNgAGYQRj+JRBRjsbA2XRI3gSKR4RFbCgAJTg3noDUc7Aieygf1K5WwRHo7HYRwC8MwkFgpyUl1kR0kMEw+EwjKU0xAbT+HQweAhFFkETEcziMCoCqVitQ3AAjFEPIFBZ10FV0TABgolCp1JEopi8FAEqgeBrfqLHeLcBDsBQAIKMRgvAa4die73XCjGxgAcWIuEIpBJ2AAZLHsCHw5HowNHA0bNgLQAGGXmh2Owu6xMBZNR9gDKGMACi9DA3AoRgjUewVQtwALRa7LPYPloSlU7AA8lAy6RW9goHAAO7YfuMQeN5ukAbz1R+9i4aDsAD6U+nYW+5K7J5dbrXw9Hy4G3FpFAvAwAYil3aG3AM1u6AHKv6s70OmAAkikAAiETxgaAxNimFZgHWvA3ne0FRr6pBhHmconlhYp+NwjBwBCRwYPq3JQcusHwXAUFwDAS4pqhEQAPyuAstLcJITCkJwAAkwDISusghC42DOC4vH4FoISxvxO6crx-GoUJ+YgJ22HYTSdIMnCSiYJIAAe2D4QSRJwDQqlqSeva3HAXJ1gA1kYjAQMQUCkLyJz5M4xAWBQADkxHYApuAstgzEuNwMAwLQ7BIJwnBgKQUADA8kCMKQ9C0LQAyQKonDBduPF8degmFUFLJKc4vkRVFMVxQlSUpdC6WZdlEC5boej1uosBcAA7AAbAArAAnGqw0ACyDQAzAN-VTYNABMo39ZwAAcvUbet-Vqv1w29eN-ULQtG3Zpw06AhCAASMDEBAkwpIB4jus9z0AEIAFI4qYg3VowdnvUYgOrg0vnmr5YRmceFnYeleiYPxpo2TQAUKYjykitDWGoI8hLUs8mk0AKjCYIjrQo9eaPRLaONQBjmOira9B05j4ohOZJ7hJ8+ZQ12rPYJ4iiiNzLPqlEADqcC4GlCRAs5LZfhioY0dgACazkwmO7AiBsdkFG43kFGrxDYJ6BRpIDcDjoBSW2qL7MM+g2AhMLha2osyw8xSALAqyYIwlWsLagiqIojYBTcpiUC+T42KAlLRBwDGZJFpSFQafShPacTLKglOgggIcNDciTUi8mcRNCszruO2eHpej6foBi8waluR4EJkm5FpggRiZjmGFVye4qdzBlbQrW9Z0S2bZC5h9PtOKPZ9gOl5jhO+5zivU8rmuG5blAu77oeLvz86rr3ivI5joh7AXwuFbPq+76fj+oZ-gBwFgXGCYJKR-EUfWKit5b5BTQgPe288F5+HTlpIOukIAGTAPHRwkNIFqSsncIu9lHLOVcu5HYXkfL+T1IFYqIUwrVWirFeKiVkp+lSs1LKOU8o9lKsVUgIQ2H0XylACq2AqqRSoXVWhjU0oZSYW1TgHV4LdRgH1Iao0JrTVmvNJaO01obV6ltHae0DpHROmdC611br3Uei9N6n1vq-X+oDIwwMjCg2iODVBaCsKw3oPDZciMiIkNRmoAocwC6cmRr49h6MIGuIXjTPGtIM4gCJiTfxZNQn0UplEamDBaYRNPlIweak+ZzwsqzY+hTeaO2dgLAoso8kp1FhLKWpAZbAmIPLRWysjYa3ItregutsD63wqrZyJsBnm3yFbG2doalinKSfBmCxygexTjMyps8pkL1FkbbAl1tAFAACoQGwK9M2xgxnYGtjaSZ9sCl0zdgs2InYuhWl6OQagdAmAsDYFwKEUh2QgFmIsqJNxHB004AAKhNqQcc1x1b8z0n6FgDQrjWURLwAZoLOCdgAMTFz5BXUQ9txDYKci5NykBDCMGcJiiEC1qXUq5mCoEt4GgFDDhIIluDxxkuhJCblRk9AmUROi+2DBIWZGcAtbMtA9L0vBe6SF-g2oFBFaMLIMADmKAYN6eAkInKqFRAUJBjAE6CoxTzNmcQebYtLu8HkuKs6Ig7J7DohKwAOWJXgrlFLsCYrgP1X1vqZWMsJPkfVbLXU4JJdSCA5KeUwkNca7AQqnXtGVWK7AEqpWBrleOdgiq5z8BVUidVcBNW6AKBCXVoa+XBuJIm01fxzWdgGAknObIYSOqLA8J4LxnAQkcNK+2fa4B6UwNOb0tBnBjoykeIsEwFAsAhNcZkIIEAwGcGAVdSgZ0dEbTzZtWd4EGQ7YWWgEBNwsGgM4fCzwWBBG3Y6acsgbDODVINSV0rsAMrxKQYgG7Q2PtIJmJNRZeC4CMBFF9b7M2fvBd+39LK0SgfAz4YDhZ9L8lvKQCA05nDZmwHhtU+E9V4cYEYQlFBswiEo-hqjAwFqHgJU1HS3oygKGcKtTN9sIDwj7dh5w3BZDkCgPe0UXbnivCtIQMEulDCupE38MA3lc1etPfgeAjB5MdBOKR-AL732Brg3+1l2mTDklQ46CADAkE3FwwMYag1NPtBdW6jl-JcAAC8nDYDVNmbM6BHNhpcySpoZ7cAXqgM4N9-n7nKkit6A+YX97OBgPF9gVZiMDDVIiPgigy6YGctIQLEaPXRu5dmAYU1su0jgHlgrAXnPFdJaVr1jk4DXBE7uv4+64H6WysgqpjG0rMYyGx7AUWOv3L3Qk-SSBuDcfBMex0KXCRpehKoZw7A4KOAoGqTLEQnJ6HgAADQo+QIwDGzWTa6wk3AHkBvJuwAB593nfPRYe0hiDL2-P1fZcFz1V6yP0Ao1RkH+G6MXaLAy7N2BoXeSK+68ct2dhIqk4i1FBRzNOyux0brTI0aLdFKe89SXfDiFzSQeA9WpBqvW-hgLjgIRrrp-bRgYHPvZgC-APSPI2BgYi9STdGmCW-ZK+SgH5HqOS9o2qCHhZ-veohIrgLlm6xhYk2qALqaGiYDVRO5nD2oSwDc55l9RGAuG55NOSWyHnD9V85z1L6XkupZvXAFWO3XsXcVN7uLK3EuXqRI7tbYOsv82q7V4ghWGsI+XTG8rlWw+5b5HV4XrrSBOVoJgCEkZ1POHECQRgFBxq+albL9onWcfTYQbN+bMJcc6Xx-bZbB8neB5W6793g10DHwZWseboaElo2ILQCQ1wXuO0x38Bl0fXPy9IxL0HkuBi9R77K0gc7eyhpn5Gz12BoDYDm-COt2BOwV-aPX4mvX42OGwBfxJZoCd-At8brzu3CNwFUBNi1Pvb9V70n1o1RwGvI-O-RveUH-ZvVbBcZ3dvMtd3TAKabvGLRULHC1KfcFNYS2VgbAAAR2ICUDHzVQP0JFIBv1oDmynERG5XIC0GCkTkezCzm0jwP1rzrU7AAAF1Ayg-AKBD8lA3gPgwgRB7wIA1N+Co0mBFAZR7Y78Zs+D21sk28W81sNsttKAZdDIpAy0Ttswzsy9RQz9RRZCEFf8D0wDsJIDW9ICO8KN9CG1kClRjD-9r8ChQD-F8VwDYtLCVClD2AbCECkDPDFRzV7CShOAME4AAUokwBWdaAYBlhYssNFNZEBgC1qwghYAUh4UEAlA-IQIhw1gfZ4BMj0hyBSBfIRAIQXJvB943RpCgjYs4otlZACgTgthmgCh8BEs2BCBrgHCfdFQkjiAUj8gYBqxHBZFXprhAJSA-I2izgOjwZm0gUqIxMXgJxfJ3gpxfIjx+jGjOBP0Di3A5tZwRhMh80Q1pwBMb8c5V1LQziGg9ifchiRiaJxiP9V0piZi-IHjGhFiwhljrI6FHhxMNj88IBXUdjJsBj9jmjyBsBfiLiCgSD-ATjsB5ikTHteByRWVbjYB7jSjLYnilRH1XJsNUjIV0jV0sjewcjC9fIRgKjIRqjws6iPCYTvcGiOTEiIThjV1qIxiJjPjpjZiGTSjMhzh8gliIjgTu0x99RNiPgoSuTYsYSXj+TRj3jJiRS5jThJS4BpSVjZTQSFTwTITdjVSFQVTgivcVSETlZ9wxZ8AsNpx6UDiQJ8RngBlHTnTsM99I9Nx4TWU4AMifApNaS85oTLSfcl5qR+tER9R1TYABg8CCCPAvA1VGB3RCBCA-InCACE5wZdjrSlQXCKwqwJ4GwKAXCIgZ5HVuTuSXCKTSAqTMjsi84-IiBgo7ImSKA4Baz2xiSGylQfSyTZx9RSSXSBhLMEAKBwpBFap5lNsmpWp2paBcBOB0hI9uAFopFtzoQPM4BGIuzV1ZJqhhoppxpJp+p+pVpVoppswbz7zhoFpBpYxd46R956Repswppbz9pxo1QNoho3zlz+wqhuRpJlwzyqheImzBIXARBfIdx89CQeykKntuAqg7dKMPsYBsLfMiyozhzGztwY5YA4Q2AZiJxFAYBrZ1MdBcyKABz2Toy2KYSmjAReBXUJRQ0N5Jy-S-Q8Yz0iSSySKlRa5RypyiARLxwAAfOSycGcJ0sctMCE3QWoqoLSycFpQgeo8Sgy0sxwJgeiyi3MsQwIKitCN0vpXXUNCyxivfAgBDAoAS2cISmSxQUgIc9i2LCpDgTo8+KS8k2TDS6AG8fCV0LShUyhRc0RFcZhLcmwXc+gfc1nTzco-S3ywyxUYK6cbKQwRQZii0nK3ytygYSK-CdgBsL3bKuqxUBOEyiiyy8y5qximY2q0qmExteqvykQN9XMEquqzmHym0oan-EatAsUcImI3AOIqIEAIQEASzcLdgZAUAJgJyacXIfCA+ZAEANgacF4Napa8Qb0V1GiNwfxLIqcZACET5DQEAM6+yS6qzTIZAFLfApaxQdcD6xgL6+JTIRwAARVungDuoeqWqmD0jcCBrgFBp+QhoCqWrwJ+WyAzzWpQFpBJjgEtktkWpAGW0jEyGBFUBOH2p6IJs3BMndDi1wHEEjzgGyCUBurgCRsUCWoilUEIDFgE3gBxg3Q8AS1vTV32rADpAJq0HwOtiExgDcFmriPdFcjcBWPZsetoCckUDFnHX2o1sTm0gJvwACBgHRryHJqQHuuRreQRCUH2sJXEE8AJo1rUydMA24GQFWkoxAHwjwKliZu9CMHNsto5sJvoHEFdpsGQAWiWuNF2TDsxuDseo-wdshUthSGDWIB2EfDWw6neqxsjwgBABCBCCAA)

```sh
--parser babel
```

**Input:**

```jsx
<%- include("partials/header", { bot, id, username, avatar, loginUrl, path, title: `Select a server`}) %>

<!-- Loading Page -->
<div id="loading-page">
    <%- include("./loading.ejs") %>
</div>

<!-- Main Page -->
<div id="main-page" style="display: none;">
    <!-- Container for servers that the bot is in (Rectangles) -->
    <div class="server-container" id="bot-in-servers">
        <% if(id) { %>
					<h1>Servers <%= bot.username %> is in!</h1>
            <% if (Array.isArray(userGuilds) && userGuilds.length > 0) { %>
                <% userGuilds.forEach(guild => {
                    const permsOnGuild = new perms(guild.permissions_new);
                    if (permsOnGuild.has(perms.FLAGS.MANAGE_GUILD) && bot.guilds.cache.has(guild.id)) { %>
                        <a href="<%= bot.guilds.cache.get(guild.id) ? `/dashboard/${guild.id}` : `${inv}&guild_id=${guild.id}` %>"
                            class="server-box rectangle"
                            style="background-image: url('<%= guild.icon ? `https://cdn.discordapp.com/icons/${guild.id}/${guild.icon}` : 'https://cdn.discordapp.com/attachments/765919453766352916/877787616974622770/wCfHtuoejLIbAAAAABJRU5ErkJggg.png' %>')"
                            data-guildname="<%= guild.name %>">
                            <span class="server-name"><%= guild.name %></span>
                        </a>
                    <% }
                }); %>
            <% } else { %>
                <h1>Weird! Could Not Get Your Guilds, Make Sure You Are Logged In.</h1>
            <% } %>
        </div>

        <!-- Container for servers that the bot isn't in (Circles) -->
        <div class="server-container" id="bot-not-in-servers">
            <% if (Array.isArray(userGuilds) && userGuilds.length > 0) { %>
                <% userGuilds.forEach(guild => { %>
                    <% const permsOnGuild = new perms(guild.permissions_new); %>
                    <% if (permsOnGuild.has(perms.FLAGS.MANAGE_GUILD) && !bot.guilds.cache.has(guild.id)) { %>
                            <a class="server-box circle"
                                style="background-image: url('<%= guild.icon ? `https://cdn.discordapp.com/icons/${guild.id}/${guild.icon}` : 'https://cdn.discordapp.com/attachments/765919453766352916/877787616974622770/wCfHtuoejLIbAAAAABJRU5ErkJggg.png' %>')"
                                data-guildname="<%= guild.name %>" id="<%= guild.id %>">
                                <span class="server-name"><%= guild.name %></span>
                            </a>
                    <% } %>
                <% }); %>
            <% } else { %>
                <h1>Weird! Could Not Get Your Guilds, Make Sure You Are Logged In.</h1>
            <% } %>
        </div>

        <% } else { %>
            <h1>You Have To Be Logged In!</h1>
        <% } %>
    </div>

    <%- include("partials/footer") %>

   <style>
    /* Add your existing styles here */
    #bot-in-servers {
        background-color: #f2f2f2; /* Change the background color for rectangles */
        padding: 20px; /* Add some padding to separate from the circles */
    }

    #bot-not-in-servers {
        background-color: #e6e6e6; /* Change the background color for circles */
        padding: 20px; /* Add some padding to separate from the rectangles */
    }

    .server-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    .server-box {
        position: relative;
        width: 150px; /* Reduce the width */
        height: 150px; /* Reduce the height */
        box-shadow: 0 0 1rem 0 rgba(0, 0, 0, 0.2);
        border-radius: 8px;
        overflow: hidden;
        display: inline-block;
        cursor: pointer;
        margin: 10px; /* Reduce the margin */
        opacity: 0.95;
        background-size: 100%;
        background-position: 50%;
			transition: transform 0.1s ease-in-out, background-color 0.3s ease-in-out;
        background-color: grey;
    }

    .server-box.circle {
        border-radius: 50%;
    }

    .server-box:hover {
        transform: scale(1.1) rotateX(0deg);
    }

    .server-image {
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.2);
        /* Add your background image styling here */
    }

    .server-name {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        text-align: center;
        background-color: rgba(0, 0, 0, 0.1);
        color: #fff;
        opacity: 1;
        padding-top: 0;
        font-size: 1rem;
        font-weight: 600;
        transform: translateY(100%);
			transition: transform 0.1s ease-in-out, background-color 0.3s ease-in-out;
        backdrop-filter: blur(400px);
    }

    .server-box:hover .server-name {
        transform: translateY(5%); /* Move the server-name up by 10% */
        /* background-color: rgba(0, 0, 0, 0.7); /* Adjust the background color on hover */ 
    }

    .server-box.circle .server-name {
        font-size: 1.1rem;
    }

		 .server-box.circle:hover .server-name {
			 transform: translateY(-3%)
		 }

    /* Media query to handle phones or devices without hover */
    @media (hover: none), (pointer: coarse) {
        .server-box:hover {
            transform: scale(1) rotateX(0deg);
        }

        .server-box .server-name {
            transform: translateY(0);
        }
			.server-box.circle .server-name {
				transform: translateY(-3%)
			}
    }
</style>

    <script>
			document.addEventListener('DOMContentLoaded', function () {
					// Hide main page initially
					document.getElementById('main-page').style.display = 'none';

					// // Show loading page while content is loading
					document.getElementById('loading-page').style.display = 'block';

					// Hide loading page and show main page when the content is loaded
					window.addEventListener('load', function () {
				
									document.getElementById('loading-page').style.display = 'none';
									document.getElementById('main-page').style.display = 'block';
				
					});

				 let newWindow; // Declare newWindow outside the event listener

						const circles = document.querySelectorAll('.server-box.circle');

						circles.forEach((circle) => {
								circle.addEventListener('click', (e) => {
										newWindow = window.open(`https://discord.com/api/oauth2/authorize?client_id=934456688306683925&permissions=70368744177655&scope=bot&guild_id=${circle.id}`, '_blank', 'width=600,height=600');

										const intervalId = setInterval(() => {
												// Check if the new window is closed
												if (newWindow.closed || newWindow.location === null) {
														clearInterval(intervalId); // Stop the interval once the window is closed
												} else if (newWindow.location.href === 'https://discord.com/oauth2/authorized') {
														newWindow.close();
														window.refresh();
														clearInterval(intervalId);
												}
										}, 500);
								});
						});
				 });

    </script>
```

**Output:**

```jsx
SyntaxError: Unexpected token (1:2)
> 1 | <%- include("partials/header", { bot, id, username, avatar, loginUrl, path, title: `Select a server`}) %>
    |  ^
  2 |
  3 | <!-- Loading Page -->
  4 | <div id="loading-page">
```

**Expected behavior:**
does it not work with ejs?

**Comment by auvred** [comment]
No. You can find a list of supported parsers here: https://prettier.io/docs/en/options#parser
