### ISSUE TITLE
Regression in v3.1 when formatting Angular templates with ICUs

### ISSUE THREAD

**Issue by minijus** [prettier/prettier#15650]
**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQAQCWAjABxQB8AqpgCbbw1J7AC2BUArvOgDR6YAbDgCdsAvgF4ADMwBWHdDDxQIAdwC+eCUWbQ4eNp3h5sAcwiaIMABZxhzYK3Zc46dZsMv0J8+9QB6LFxyAB0oEB4QCEwYAmh0ZFBsYWE1AAVkhASUMVVsAE8EyIAjUTAAazgYAGVsFjgAGXY4ZAAzMXQ4ErLKmpwwdlNkGGEOLpBOtmHR8fRBgTgARQ4rFqR2gU7I2XQAD2r5pZX4No7xgEdjuDTUzGyQbHQAWig4OBp3iJAR7AIBQYAwhAWCxsMgHgIBF85lBTAsAIIwEYEYouNJ2JqvU6bcbWGAsAQAdWsBG4-Tg1SypIIADdSflwWB0EUQDSxgBJKAfWDVMDCAgxeFc6owfILbFbECYVKdQmiTDg6WuOw0lqRdidYQwG5mUES8Y4YSa8G4UwcATJL7S9gwQkEGg2ZAkKSRYRwS4EN060x69ZnSIwbDFO0O6zIABMkQUcAAKkHshtJXAWMV3h8aA1TRwzHAAGIQYSgpGDE1cCAgdxAA)

```sh
--parser angular
```

**Input:**

```html
<span i18n>Updated: {minutes, plural, =0 {just now} =1 {one minute ago} other {{{minutes}} minutes ago}}</span>

```

**Output:**

```html
SyntaxError: Unexpected closing block. The block may have been closed earlier. If you meant to write the } character, you should use the "&#125;" HTML entity instead. (1:51)
> 1 | <span i18n>Updated: {minutes, plural, =0 {just now} =1 {one minute ago} other {{{minutes}} minutes ago}}</span>
    |                                                   ^
  2 |
```

**Expected behavior:**
It should not fail when parsing templates with ICUs.

**Comment by Zefling** [comment]
It's not work for with Angular too: 

```HTML
@for (background of stage.backgrounds; track background ) {
  @for (item of background; track item ) { @if
(item) {
<div
    [ngClass]="item.style?.class"
    [ngStyle]="item.style?.style"
    [attr.id]="item.style?.id || null"
    [style.--col]="item.x * 3 + 1 | math: 'round'"
    [style.--row]="item.y * 3 + 1 | math: 'round'"
></div>
} } } 
```
becomes:
```HTML
@for (background; of: stage.backgrounds; track: background) {
    @for (item; of: background; track: item) {
        @if (item) {
            <div
                [ngClass]="item.style?.class"
                [ngStyle]="item.style?.style"
                [attr.id]="item.style?.id || null"
                [style.--col]="item.x * 3 + 1 | math: 'round'"
                [style.--row]="item.y * 3 + 1 | math: 'round'"
            ></div>
        }
    }
}
```

**Comment by minijus** [comment]
> Having a similar issue:
> 
> If you meant to write the @ character, you should use the "@" HTML entity instead.

This is not related to prettier parsing/formatting. Usage of `@` and failure that is mentioned is from Angular itself - simply replace `@` with `&#64;` as the error message states.

**Comment by reduckted** [comment]
Just a bit of info. I've just tested the example code from https://github.com/prettier/prettier/issues/15650#issue-1989996111 and it works in 811eb0a08505c2a1aad4ef9dfae6db8065063dd5 but fails from 0176a33db442e498fdb577784deaa77d7c9ae723 which is the very next commit, and that added Angular Control Flow support.

**Comment by fisker** [comment]
@sosukesuzuki  What do you think we do the 

```js
tryCombinations(
  () => parse(..., {tokenizeAngularBlocks: true}),
  () => parse(..., {tokenizeAngularBlocks: false}),
)
```

trick, like we did in some js parsers?

**Comment by terencehonles** [comment]
> Does anybody have a workaround like which rule needs to be disabled?

@TheSlimvReal it's not a rule, but how the parser is being called, and the new control flow syntax is hardcoded to be on. I've suggested a PR https://github.com/prettier/prettier/pull/15726 which allows disabling it for those of us who are either upgrading prettier only or are not using the new control flow syntax yet.

**Comment by mattlewis92** [comment]
Just sent a PR with a fix for this regression 😄 https://github.com/prettier/prettier/pull/15773

**Comment by reduckted** [comment]
This should probably be reopened until #15777 is merged.
