### ISSUE TITLE
Break on multiple chained calls

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#1565]
I've mentioned this possibility in a few different issue (#1099, #1282, #1401), but I thought a separate issue might be appropriate. 😄

I'd like for prettier to break on multiple chained calls. I prefer a higher `printWidth` than 80 in most cases (such as strings, log statements, class declarations etc), but increasing it leads prettier to one-line a lot of chained expressions that were multi-lined.
Eslint has a rule for this called [`newline-per-chained-call`](http://eslint.org/docs/rules/newline-per-chained-call). It defaults to 3 chained calls should break, which sounds like a sane starting point. This rule is unfixable, unfortunately, but Prettier could fix it! 😀

Even for the default width of 80 some things are inlined which IMO are more readable expanded.

I don't think there's any doubt which of these two are the easiest to read  (especially considering the git diff scenario from eslint's docs): https://prettier.github.io/prettier/#%7B%22content%22%3A%22d3%5Cn%20%20.select(%5C%22body%5C%22)%5Cn%20%20.selectAll(%5C%22p%5C%22)%5Cn%20%20.data(%5B1%2C%202%5D)%5Cn%20%20.enter()%5Cn%20%20.style(%5C%22color%5C%22%2C%20%5C%22white%5C%22)%3B%5Cn%5Cnd3%5Cn%20%20.select(%5C%22body%5C%22)%5Cn%20%20.selectAll(%5C%22p%5C%22)%5Cn%20%20.data(%5B1%2C%202%2C%203%5D)%5Cn%20%20.enter()%5Cn%20%20.style(%5C%22color%5C%22%2C%20%5C%22white%5C%22)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by azz** [comment]
Prettier will generally try to fit content in one line if possible.

I don't think a simple solution like "break when 3 or more chains" can be reasonably applied, consider:

```js
point().x(4).y(3).z(6).plot();
```

```js
point()
  .x(4)
  .y(3)
  .z(6)
  .plot();
```

Which is prettier?

**Comment by SimenB** [comment]
>Prettier will generally try to fit content in one line if possible.

Yes, and it _mostly_ turns out better. Not always though. This is a less abstract answer to #1099 maybe?

>consider:

I do think the second one is prettier, although I can see the argument it's "verbose".

The real gain in that case is on diffs, though (same reason we do trailing commas, it's not necessarily prettier).

```diff
point()
  .x(4)
-  .y(3)
+  .y(4)
  .z(6)
  .plot();
```

```diff
- point().x(4).y(3).z(6).plot();
+ point().x(4).y(4).z(6).plot();
```

---

```diff
point()
  .x(4)
  .y(3)
+  .foo(4)
  .z(6)
  .plot();
```

```diff
- point().x(4).y(3).z(6).plot();
+ point().x(4).y(3).foo().z(6).plot();
```

---

```diff
point()
  .x(4)
-  .y(3)
+  .y(4)
+  .foo(4)
  .z(6)
  .plot();
```

```diff
- point().x(4).y(3).z(6).plot();
+ point().x(4).y(4).foo().z(6).plot();
```

**Comment by tinynumbers** [comment]
An ideal solution (for me, at least) would simply be the ability to turn off the "generally try to fit content in one line if possible" rule altogether.

If I've broken code down across multiple lines (even though it _could_ be placed on one line), I've generally done so for explicit reasons of readability and clarity, and don't want to to be changed.

**Comment by vjeux** [comment]
@SimenB the problem here is more about tooling. In phabricator diff view, the individual piece of the line will be highlighted in bright red/green, so you know that only the number changed. It sucks that github is still not doing that :(

**Comment by azz** [comment]
GitHub does do that in PRs, but not patches in comments. :man_shrugging:

![image](https://cloud.githubusercontent.com/assets/1297597/25876211/1fa0e9b0-355f-11e7-985d-14a600ff30a8.png)

My point with the `point()` example (pun not intended), is that it is not black and white as to which way it should be printed.

That being said, I too prefer the multi-line variant.

**Comment by SimenB** [comment]
>@SimenB the problem here is more about tooling.

All of the tools I use for diffing supports word diffing as well, so maybe that point is moot. But I still think the multi-lined one is easier to read 😄

>An ideal solution (for me, at least) would simply be the ability to turn off the "generally try to fit content in one line if possible" rule altogether.

I don't agree with this. One thing I really like about prettier is that it mostly ignores input formatting in order to make code consistent. But sometimes it is overly eager.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%5Cn%20%20doMapping%2C%5Cn%20%20doFilter%2C%20%5Cn%20%20doSecondMapping%2C%20%5Cn%20%20doReduce%2C%5Cn%7D%20from%20'someCommonCode'%3B%5Cn%5CnsomeArray%5Cn%20%20.map(doMapping)%5Cn%20%20.filter(doFilter)%5Cn%20%20.map(doSecondMapping)%5Cn%20%20.reduce(doReduce)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

While I think the first one is fine to one-line, the second one loses readability, IMO. And this is on 80 width, the problem is much worse if you use 100 or 120 as width.
Some way of breaking even if it would have fit seems like it might solve some the issues I have.

It might still be that #1099 is better, but I don't know if @vjeux has gotten the time to work on that.

**Comment by dburrows** [comment]
Could we manage chains like we manage object literals, in that if they have a break within them they get broken e.g.

this examples stays formatted as it it is
```
d3.select("body").selectAll("p").data([1, 2]).enter().style("color", "white");
```

this example:

```
d3.select("body").selectAll("p")
  .data([1, 2])
  .enter()
  .style("color", "white");

```

gets formatted as this
```
d3
  .select("body")
  .selectAll("p")
  .data([1, 2])
  .enter()
  .style("color", "white");

```

**Comment by apazzolini** [comment]
Definitely agree with @dburrows's comment above. It's following an already accepted pattern (object literals) and adding it to function chaining when the user opts in.

**Comment by SimenB** [comment]
I like that one as well!

**Comment by JakeGinnivan** [comment]
@vjeux thoughts on the above suggestion?

This particular issue is probably the main one stopping my team from adopting prettier.

**Comment by apazzolini** [comment]
We've adopted prettier, but we have a *lot* of `// prettier-ignore` for this scenario. It's especially prevalent when chaining with point-free style.

**Comment by jhnns** [comment]
@dburrows suggestion sounds good. In my case, prettier is printing

```js
Object.keys(props).filter(key => key in own === false).reduce((a, key) => {
    a[key] = props[key];

    return a;
}, {}),
```

while I would prefer

```js
Object.keys(props)
    .filter(key => key in own === false)
    .reduce((a, key) => {
        a[key] = props[key];

        return a;
    }, {});
```

But I totally understand why people prefer

```js
point().x(4).y(3).z(6).plot();
```

over 

```js
point()
    .x(4)
    .y(3)
    .z(6)
    .plot();
```

To me, the line-break rules totally makes sense.

**Comment by Koblaid** [comment]
I would go a step further and argue that even very short chained calls should go into separate lines, so that

```js
point().x(4).y(3).z(6).plot();
```
would be formatted as

```js
point()
    .x(4)
    .y(3)
    .z(6)
    .plot();
```

In my opinion each call is like a separate statement. And multiple normal statements are always written in separate lines, right?

For example if the same was written with a class it should be formatted

```js
const p = point();
p.x(4);
p.y(3);
p.z(6);
p.plot();
```

and not

```js
const p = point();p.x(4);p.y(3);p.z(6);p.plot();
```

**Comment by aboyton** [comment]
I'd prefer prettier to ***not*** respect the original formatting as much as possible. The best advantages for prettier for me is that code that different people write is as consistent as possible.

Personally I'd much prefer to not allow lines line `point().x(4).y(3).z(6).plot();`. If you are chaining that many things together, then I think you should put them on multiple lines. I think the ESLint rule `newline-per-chained-call` is terrific in that regard.

For examples like
```js
Object.keys(props).filter(key => key in own === false).reduce((a, key) => {
    a[key] = props[key];

    return a;
}, {}),
```
I completely agree that this is much better written as
```js
Object.keys(props)
    .filter(key => key in own === false)
    .reduce((a, key) => {
        a[key] = props[key];

        return a;
    }, {});
```
I'd love a solution that didn't require me to manually break things if possible and prettier to do this automatically. That way prettier would never output the former and always the latter, rather than leaving this up to the developer and thus having inconsistencies in the codebase.

Is the problem just with prettier's breaking strategy that it can't break each chained function just because one of them broke? That said, maybe there are too many edge cases to do that well 😞

**Comment by Akkuma** [comment]
This is probably the biggest barrier for my team to adopt prettier as well. I normally love prettier, but the output it produces for lines that aren't over the line length for chained calls and instead get single lined break the expectations of myself and those I work with.

**Comment by alphashuro** [comment]
Any news on this? can't wait for the feature

**Comment by brickyang** [comment]
YES. Break on multiple chained calls PLEASE.

**Comment by Akkuma** [comment]
This issue seems to have a large consensus on how people want this to behave, but almost no momentum on getting fixed :(

**Comment by levithomason** [comment]
It seems the [clear majority consensus](https://github.com/prettier/prettier/issues/1565#issuecomment-305208956) is to keep consistent with object literal treatment, keep one line chained calls or break into lines if already broken.

Implementation aside, it would be superb to get a decision from the core maintainers.  Perhaps someone will contribute the PR.

**Comment by azz** [comment]
A problem I see with @dburrows' suggestion is that code previously formatted with prettier will be on one line, so if we make that change the previously formatted code will never change to the multi-line version.

Another issue is that it increases the knowledge users need to have of the inner workings of prettier. Having to do things a certain way to produce a certain output sucks.

I think I'd prefer to have a "3 chained function calls causes a multi-line expansion" rule as originally suggested in the OP.

 This would also close #1282.

**Comment by levithomason** [comment]
Works for me. The 3 chained call rule forces more consistency, which I like. Thanks for the PR.

**Comment by ValentinH** [comment]
@azz Thank you really much for this! 👍

**Comment by stephenh** [comment]
FWIW, probably too late, and everyone has an opinion, but this changed some code like:

```
assert.equal(this.$().text().trim(), '1000');
```

To be:

```
assert.equal(
  this.$()
    .text()
    .trim(),
  '1000'
   );
```

(I may not have copy/pasted the indentation 100% right from our code review tool.)

Which seems objectively much worse; a 1-liner assertion that was very readable IMO (e.g. not the complex `foo.a().b().zaz().plot().whatever()` examples in the above discussion) got turned into a 6 line method that, again I would assert objectively but technically IMO, is actually harder to read, because it's needlessly strung out over multiple lines.

FWIW I love the prettier ethos/goal, just disagree on this point solution.

3 seems arbitrarily low to wrap on, regardless of line length. Something like ~6-7 seems like a more reasonable number for "yeah, this chaining is getting complex and needs broken up".

If anything, let this be configurable? :-) (I originally thought prettier was zero-config, but I noticed there is a config file, so had to ask. Thanks!)

**Comment by Shahor** [comment]
> 3 seems low

I suppose it's a matter of taste. Your example might convince you that 6 or 7 would be the right choice, but what about this : 

```js
something().then(() => doSomethingElse()).then(result => dontForgetThisAsWell(result))
```

Which would be faaaar easier to read like so : 

```js
something()
    .then(() => doSomethingElse())
    .then(result => dontForgetThisAsWell(result))
```

I know this can be written in a simpler way, but so does your example.

My point being: there's no perfect choice and one was made with the value `3`.

Sometimes it will suit your needs, sometimes it won't. Overall I believe we have gained from this feature.

**Comment by apazzolini** [comment]
I still think [dburrow's earlier suggestion](https://github.com/prettier/prettier/issues/1565#issuecomment-305208956) would have been the way to go.

If the user puts a line break in a chain of function calls, respect it. Otherwise, let prettier do its thing. 

It's the same pattern prettier uses for objects, which works really nicely in practice.

**Comment by stephenh** [comment]
@Shahor agreed examples can be found for both, and agreed for your example the 3 wrap makes sense; FWIW your example had method calls with non-trivial arguments/lambdas, so maybe that would be worth differentiating? E.g. method calls with no args (`this.foo().bar().zaz()`), or only non-lambda args, don't need wrapped at 3, but calls-with-lamdas do (`this.foo(() => ...).bar(() => ...).zaz(() => ...)`.

That said, being consistent with object literals per @dburrows and @apazzolini does seem like a simpler approach.

**Comment by Doeke** [comment]
I don't like how it currently forces line breaks into function chains. Here's an example:

```

return await db.branch(
  db.table('users').filter({ email }).count(),
  db.table('users').insert({ email }),
  db.table('users').filter({ email }),
)

// becomes...

return await db.branch(
  db
    .table('users')
    .filter({ email })
    .count(),
  db.table('users').insert({ email }),
  db.table('users').filter({ email }),
)
```

I think this looks pretty awful! I wish it didn't wrap chained calls unless they'd extend past print width.

**Comment by JakeGinnivan** [comment]
For what it's worth, not having this feature was a blocking issue for our team. I love the new behavior.

Respecting what is there would also work for us, or a configurable number of chains before it breaks would also be fine, but going back I don't think is an option.

**Comment by jeffijoe** [comment]
Sorry for the noise but I'm hoping it might call attention to this issue once more; I am very much in favor of @dburrows and @apazzolini suggestion of checking whether there were any newlines manually added by the user, just like with object literals.

To once more illustrate the reasoning:

### Ugly

![image](https://user-images.githubusercontent.com/2505474/34298766-a9f572b2-e71f-11e7-81a7-79e5bcc7e2c6.png)

### Pretty

![image](https://user-images.githubusercontent.com/2505474/34298774-b5d4b2be-e71f-11e7-947d-0ce41a166b50.png)

**Comment by lydell** [comment]
@jeffijoe FYI, see also #3524.

**Comment by demisx** [comment]
Currently, I get this 

```ts
   sandbox.stub(config, 'get').withArgs('env').returns('dev')
```

converted to:

```ts
sandbox
  .stub(config, 'get')
  .withArgs('env')
  .returns('dev')
```

With multiple stub statements, this makes our tests much longer and harder to comprehend. Is it possible to configure this option? I'd love to wrap only those lines that go over preset line length (i.e. 120 chars) or, at least, after 5th chained call.

**Comment by apazzolini** [comment]
@demisx As far as I know, this option is non-configurable.

The suggested behavior of this feature has been:

1. Wrap after hitting the line length limit
1. Wrap after 3 chained methods
1. Wrap after a configurable number of chained methods
1. Wrap when one of the two conditions is met:
    - The line length limit is reached
    - The user opts into it by manually inserting a newline, like object literals

The initial implement was (1). The current implementation is (2). (3) is unlikely to happen since prettier tries to avoid configuration. The consensus is against (4) due to wanting to minimize user input influence in prettier's output.

I think the current implementation (2) makes sense in the majority of cases, but I find myself wanting (4) often enough that I no longer use prettier for JS.

**Comment by demisx** [comment]
@apazzolini Agreed. Wrapping after 3 chained methods is way too soon for us too. This option needs to be at least configurable. Sticking `// prettier-ignore` everywhere makes it no as pretty anymore.

**Comment by j-f1** [comment]
@demisx As a workaround, you could make a helper function:

```js
function stub(obj, prop, returns, ...args) {
  sandbox
    .stub(obj, prop)
    .withArgs(...args)
    .returns(returns);
}
// ...
stub(config, "get", "dev", "env");

```

**Comment by demisx** [comment]
@j-f1 Thanks for the suggestion. We have multiple occurrences of the same scenario throughout the code base and creating a helper function for each will unnecessarily bloat the code up. Hopefully, this option will become configurable in the nearest future.

**Comment by demisx** [comment]
Certainly, wrapping after certain number of chained calls is not a panacea for all. My preferred fix would most likely be to turn off this wrapping completely. This is not something I want prettier to handle.

**Comment by saarmae** [comment]
This not being configurable means our team can't use prettier.
`	const { error } = Joi.validate(promotion, Joi.object().keys({
		companyId: Joi.number().integer().required(),
		newPlanId: Joi.number().integer().required(),
		oldPlanId: Joi.number().integer(),
		oldPlanPrice: Joi.number(),
		start: Joi.date().iso().required(),
		end: Joi.date().iso().min(Joi.ref('start')).required()
	}));`

turn to 

`	const { error } = Joi.validate(
		promotion,
		Joi.object().keys({
			companyId: Joi.number()
				.integer()
				.required(),
			newPlanId: Joi.number()
				.integer()
				.required(),
			oldPlanId: Joi.number().integer(),
			oldPlanPrice: Joi.number(),
			start: Joi.date()
				.iso()
				.required(),
			end: Joi.date()
				.iso()
				.min(Joi.ref('start'))
				.required()
		})
	);`

Using prettier-ignore all over our controllers is unacceptable, workarounds are unacceptable, not using Joi is unacceptable.

**Comment by paulintrognon** [comment]
I believe the user sometimes knows best what's prettier, and it seems to be the case here.
Prettier wants consistancy ; which one of the following really feels more consistant?

  - Current Prettier behavior: (3+ chains = break)
```
const a1 = b1.c1().d1();
const a2 = b2
            .c2()
            .d2()
            .e2();

return fetchApi().then(res => res.data).catch(err => err.stack);
```

  - Suggested behavior: (leave the choice to the user, as long as he doesn't mix)
```
const a1 = b1.c1().d1();
const a2 = b2.c2().d2().e2();

return fetchApi()
         .then(res => res.data)
         .catch(err => err.stack);
```

This issue is a big turn off for my team and me. When users starts using abusively `// prettier-ignore`, it's generally a bad sign. And that's sad because appart from that, I really love this tool :+1:

**Comment by demisx** [comment]
Please make this option configurable. 🙏 We can't use prettier because of this as well.

**Comment by misterbridge** [comment]
Please let make dburrows' suggestion be the norm.
That makes prettier "ignore" chained calls (as requested by a large groupe of people), but keep things consistent as no mixing solutions.

Any number of chained calls to be a condition on linebreaking cannot be a good solution as it depends enormously on what those calls are. For a letter or a whole function behavior cannot be forced to be the same.

To my eyes, the only good solutions are either to ignore formating chained calls or format following what the dev want for the specific situation, as dburrows suggested.

**Comment by stephenh** [comment]
Seems like eventually someone should fork prettier to loosen up some of it's more opinionated decisions, and then users can decide which one they like better.

(I know this is heresy to the "no formatter options" crowd; I get that view point, but IMO ~80% of prettier's adoption/value is from being the first/only (AFAICT?) AST-aware JS formatter (and AST-aware formatters are amazing compared to the old line-too-long + blindly-indent ones) and maybe ~20% of the adoption/value is driven specifically by the "no formatter options" approach. It's perfectly fine for the prettier maintainers to make that choice and couple the two features/decisions, but they are not strictly coupled.)

**Comment by stephenh** [comment]
@apazzolini I would like to agree with you, but we're ~a year into this issue, and AFAICT the maintainers are taking a principled stand on this. None of them have commented/chimed in since the PR to move to the "must be 3".

Granted, I'm assuming their silence means they disagree with both the config & object-literal approach, but it could also very well be lack of time/interest, and maybe they would bless/accept a PR to move to object-literal convention.

**Comment by vjeux** [comment]
> I haven't seen a single person argue that the current behavior works well and that it's the gold standard for chained calls.

The only people that are going to look for this issue are people that are not satisfied with the status quo. There may be (and likely is) a silent majority which is happy with the current behavior.

> Seems like eventually someone should fork prettier to loosen up some of it's more opinionated decisions, and then users can decide which one they like better.

I'm very surprised that people didn't fork prettier more often. I would highly encourage you doing that :)

The value proposition of prettier to me is the ability to write code badly formatted and when you press save, there's a canonical version of the output. This means that the developer can stop --thinking-- about formatting the code.

> I believe the user sometimes knows best what's prettier, and it seems to be the case here.
Prettier wants consistancy ; which one of the following really feels more consistant?

The fact that similar-looking expressions output pretty different formatting is not ideal and indeed not consistent. But in my opinion it's better than having to give developers a choice.

If we preserve the way developers print their member expressions, this means that now based on where you are in the codebase they can be printed in a different way, based on the mood of the author. It also invites back all the nitpick discussions that prettier is hoping to solve and I'm sure that we'll see people writing linters to enforce certain patterns. Especially in the case of member expressions which are --everywhere--.

For context, member expressions is the most complex piece of code of prettier. As seen in this issue, there are still issues with it and it doesn't get everything right, but in the grand scheme of things it works really well. All the real code examples I've seen where it doesn't output ideal code, the output is a more verbose than one would hope but it doesn't look completely broken.

I'm happy with the current state of member expressions in prettier. If you are not, please try to come up with specific fixes for scenarios where it doesn't print code the way you like and send pull requests. There are a ton of existing snapshot tests so you'll see what other pieces of code you break in the process. Or feel free to fork the project and enable following the existing code, it should be easy to build this, but I don't want to add it to the main project as I believe it's the wrong trade-off.

**Comment by apazzolini** [comment]
@vjeux I appreciate your work on Prettier, and I'm sure that you've thought about how to handle specific cases a lot more than I have. I understand the desire to discard all user input and consistently apply formatting, and definitely agree that's the main value prop of Prettier.

With that in mind, would you please explain your rationale for respecting a user's choice of keeping an object literal on one line if it was inputted that way and fits the line length limit vs not doing the exact same thing on chained method calls?

The advocates in this thread are not suggesting introducing new behavior to Prettier - we're simply trying to mirror already implemented patterns into another situation it applies.

**Comment by demisx** [comment]
> But in my opinion it's better than having to give developers a choice.

@vjeux  We'd like to have a choice over how the chained calls are being formatted.  What's wrong with us (developers) having this choice?

**Comment by vjeux** [comment]
> With that in mind, would you please explain your rationale for respecting a user's choice of keeping an object literal on one line if it was inputted that way and fits the line length limit vs not doing the exact same thing on chained method calls?

I've tried adding/thinking of a ton of heuristics to object literals in order to produce something that would behave decently but I just couldn't find reasonable heuristics for it. It showed as the issue tracker was dominated by issues about object literals in a bunch of contexts. Something had to be done for prettier to be successful.

The technical challenge is roughly similar here but the scope isn't. With all the heuristics we've added to member expressions, most of the code now look fine and there are issues like this one but it has been at the level of an annoyance for most people rather than deal-breaker. So given that, it doesn't justify using a giant hammer of respecting written patterns (which comes with a bunch of downsides) as the situation doesn't appear to justify it.

@j-f1 idea of respecting user choice in specific contexts is interesting, that's worth digging into.

**Comment by stephenh** [comment]
> (vjeux) code badly formatted and when you press save, there's a canonical version of the output

For sure! What you've done is amazing, we're/I'm just quibbling about minor details.

> (vjeux) I'm very surprised that people didn't fork prettier more often. I would highly encourage you doing that :)

:-) yeah...

Thanks for chiming in! Glad to hear you're open to PRs that tweak the behavior. That is primarily what I was curious about.

For me personally, and I hope?/assume many others on this thread, a few tweaks to method call wrapping to handle the super-simple/no-param cases like `foo().bar().zaz()` would hit the "good enough". It'd be fun to hack on that...will see if I can ever get around to it. I would also love for someone else to beat me to it (of course :-)).

Given this chatter is all happening on a closed issue, maybe it's worth opening a new issue of "Tweak chained calls" (with a "open to PRs"-type label) and people could start submitting cases, just as comments, for what they'd like to see, for whenever eventually someone wants to tackle it?

**Comment by duailibe** [comment]
@stephen That would be great. Are you interested in opening a new issue and starting the discussion?

**Comment by j-f1** [comment]
I’m planning to work on the idea I proposed this evening and perhaps open a PR.

**Comment by stephenh** [comment]
@duailibe sure, I'll wait ~a few days to see what @j-f1 comes up with, albeit I think his "respect existing one-line-ed-ness" does not 100% match the prettier/maintainer's ethos, and then create a new issue and link to it here.

**Comment by shellscape** [comment]
I've read through 5 different issues on this topic, as the behavior was throwing me off as well. What I can't figure out is why Prettier doesn't want to seem to listen to the `newline-per-chained-call` ESLint rule, which clearly defines the behavior here. If modifications are being done to the behavior of Prettier in this regard, I would like to suggest that obeying the settings in ESLint for this particular behavior should be a priority.

**Comment by duailibe** [comment]
@shellscape Prettier doesn't (and has no intent to) read ESLint configuration. For conflicts, we recommend disabling any rules that conflict with Prettier's style, or simply run ESLint after Prettier (https://github.com/prettier/prettier-eslint).

**Comment by shellscape** [comment]
@duailibe why not the inverse, allowing for that chain modification behavior to be disabled?
