### ISSUE TITLE
Flow default case - extra semicolon

### ISSUE THREAD

**Issue by TAQ2** [prettier/prettier#1566]
Hello,

 I am using the latest version of flow and prettier. 

When using the default case in flow [(documentation)](https://flow.org/en/docs/frameworks/redux/#typing-redux-reducers-a-classtoc-idtoc-typing-redux-reducers-hreftoc-typing-redux-reducersa). I am getting an extra semi colon for the specifying the default case

The code is as follows
```javascript

type Thing = 'First' | 'Second'

type GetSomethingT = Thing => number

const getSomething: GetSomethingT = item => {
  if (item === 'First') {
    return 1
  } else {
    ;(item: 'Second')
    return 100
  }
}

```

Thanks! :)

**Comment by lydell** [comment]
That semicolon is actually intentional. The idea is to help you not make mistakes.

Without it, the following change would result in an accidental runtime exception:

```diff
 type Thing = 'First' | 'Second'
 
 type GetSomethingT = Thing => number
 
 const getSomething: GetSomethingT = item => {
   if (item === 'First') {
     return 1
   } else {
+    console.log('Do we even get here??')
     (item: 'Second')
     return 100
   }
 }
```

Because the above actually means:

```js
type Thing = "First" | "Second";

type GetSomethingT = Thing => number;

const getSomething: GetSomethingT = item => {
  if (item === "First") {
    return 1;
  } else {
    console.log("Do we even get here?")((item: "Second"));
    return 100;
  }
};
```

**Comment by TAQ2** [comment]
Ok thanks very much for the help!
