### ISSUE TITLE
"Integrating with Linters" documentation. Do these recommendations apply to VS Code?

### ISSUE THREAD

**Issue by DanKaplanSES** [prettier/prettier#15669]
This is a question about the [Integrating with Linters](https://prettier.io/docs/en/integrating-with-linters) article, in particular, the advice in the [Notes section](https://prettier.io/docs/en/integrating-with-linters#notes):

> When searching for both Prettier and your linter on the Internet you’ll probably find more related projects. These are **generally not recommended,** but can be useful in certain circumstances.
> 
> First, we have plugins that let you run Prettier as if it was a linter rule:
> 
> - [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier)
> - [stylelint-prettier](https://github.com/prettier/stylelint-prettier)
> 
> These plugins were especially useful when Prettier was new. By running Prettier inside your linters, you didn’t have to set up any new infrastructure and you could re-use your editor integrations for the linters. But these days you can run `prettier --check .` and most editors have Prettier support.
> 
> The downsides of those plugins are: ...

Ever since I've read this, I've tried my best to follow the advice therein, but I can't figure out a way to do it with Visual Studio code—not without sacrificing the behavior I want, at least. [I want "Format Document" to run eslint **and** prettier](https://stackoverflow.com/questions/77491378/in-vscode-how-do-i-effectively-run-eslint-fix-and-prettier-write-on-format/77497166#77497166). One response in that link says, "[T]he answer is: do not use both. Use ESLint with [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier)." 

But the official documentation says I shouldn't need to use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier). It says, "These plugins were ... useful when Prettier was new. But these days ... most editors have Prettier support." Visual Studio code is pretty popular, so I feel like it applies? Does that mean I'm trying to do something wrong or do I have a use case that doesn't apply? Can the article be updated to include this information? Thank you! 

---

Related (barely): https://github.com/prettier/prettier/issues/8353

**Comment by saltman424** [comment]
@DanKaplanSES 
Not exactly what you've asked for, but this is what my team uses in our VSCode `settings.json` to get both ESLint and Prettier to format on save:
```json
{
  "editor.codeActionsOnSave": { "source.fixAll.eslint": true },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[typescript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[graphql]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[scss]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "vscode.css-language-features"
  }
}
```

**Comment by DanKaplanSES** [comment]
@saltman424 Thank you for sharing, I appreciate that. Yeah, it's much easier to do this on save. Doing it on "Format Document" is the part I struggle with.

**Comment by DanKaplanSES** [comment]
@kachkaev Although I am asking a question, this is more of a documentation request, specifically to clarify an aspect of the ["Integrating With Linters" article](https://github.com/prettier/prettier/blob/main/docs/integrating-with-linters.md). I can reword this so it's not a question if you'd like, or I can submit a PR with the change I'd like to see, but I was hoping to gather some information first. Let me know what you'd prefer, thanks!

**Comment by kachkaev** [comment]
IC. Feel free to create a PR referencing this issue 👍 It’s easier to discuss potential improvements to doc when there is a preview
