### ISSUE TITLE
Include Plugins in shareable configurations

### ISSUE THREAD

**Issue by yordis** [prettier/prettier#15667]
Related to: https://github.com/prettier/prettier/issues/15227

I added few plugins as part of my shareable configuration. At the beginning I tried to use `import` but it did not work, so I had to use the name of the plugin as a string.

Ideally I would like my shareable configuration to work by itself without having to install the plugin manually. But even adding the plugin dependencies to all packages doesn't work.

**Environments:**

- Prettier Version: 3.1.0
- Running Prettier via: CLI
- Runtime: Node.js v20.9.0
- Operating System: macOS
- Prettier plugins (if any): `prettier-plugin-organize-imports`

**Steps to reproduce:**

1. Clone `https://github.com/straw-hat-team/nextjs-starter-kit` 
2. Run `yarn add --dev prettier-plugin-organize-imports` (add it to all packages to be safe)
3. Run `yarn format:prettier`
4. It fails

**Expected behavior:**

I expect my plugin to use its local dependencies specified here:
https://github.com/straw-hat-team/nodejs-monorepo/blob/332ba2fdcbac99461d047bcbc5079700a4b9416e/packages/%40straw-hat/prettier-config/package.json#L35-L38

(Note: I changed the `@straw-hat/prettier-config` package back to CommonJS, but I did not publish it, so I am using the ESM version)

**Actual behavior:**

```
[error] Cannot find package 'prettier-plugin-organize-imports' imported from /Users/ubi/Developer/github.com/straw-hat-team/nextjs-starter-kit/noop.js
```

**Comment by fisker** [comment]
It's hard to find out where to import that plugin. I suggest use 

```js
url.pathToFileURL(require.resolve('prettier-plugin-tailwindcss'))

// Or

import.meta.resolve('prettier-plugin-tailwindcss')
```
 for now.


`url.pathToFileURL` should be able to remove after #15666

**Comment by yordis** [comment]
@fisker thank you for the help. I am gonna try your suggestion and see how it goes.

Aside from that, is there any reason we couldn't pass a object (or function, technicality aside) that represent the plugins instead of prettier trying to load the plugin?

I am pretty sure there is a reason why but I couldn't find it.

**Comment by fisker** [comment]
> is there any reason we couldn't pass a object (or function, technicality aside) that represent the plugins instead of prettier trying to load the plugin?

Yes, you can use `plugins: [require("prettier-plugin-tailwindcss")]` in your config. Prettier CLI works with no problem.

But this won't work if you use prettier-vscode, since it user a worker to resolve config, plugins can't be transferred to main thread. https://github.com/prettier/prettier-vscode/blob/4dc69a8f8b7c745ad54bfec6d66e8d41921d7414/src/worker/prettier-instance-worker.js#L1

**Comment by kachkaev** [comment]
This worked for me in a shared config:

```js
const config = {
  plugins: ["prettier-plugin-packagejson", "prettier-plugin-sh"],
};
```

[Source](https://github.com/kachkaev/routine-npm-packages/tree/bc3e658f88c0b41beb118c7a1b9b91ec647f8478/packages/prettier-config)

**Comment by fisker** [comment]
@kachkaev I guess your plugin is installed in `node_modules/` instead of `node_modules/@kachkaev/prettier-config/node_modules/`, so Prettier can import from your `.prettierc`, but it's possible to be in other places with different package managers, so it can be broken.

**Comment by yordis** [comment]
Using `import.meta.resolve(...)` solves the issue. I wonder if some documentation about it would help 🤷🏻 

Thank you for the help and patience!
