### ISSUE TITLE
Broken last comment placement & extra parenthesis have been added for no benefit

### ISSUE THREAD

**Issue by Peter-Sparksuite** [prettier/prettier#15661]
**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaIFs4wAWAllAOaYC8mA5JpgEYBOAhlGIQIwA63UAVI1btCAJl5R6zNhwDMNAHRoADgBtiMABQ0JNAJR8FAM2Kr4TTZvVQ4eqgD5MwPpgD0rzAEkyUCEzhCMoRwaJiELABupBRQLPihRCxYpAAmxGBJAURwAJ40-pi+WCpwYMQsqi6Y-jAArkySAISaVZjWcAq4SRyargB6ANq8KQC6ANQAtEPcAO4jrnYAPotuHgBytbgMcP4pgSIhrW2kHV0wPa4YLGTRi10YO4sAEgCiAIIAIguYy6uYAMrKUrEExgfYcEKYGAQTB4DRHdqdbqEXp9HD4IjRCYKSYDAAMEwAnCwJkYRsAABwAGgpAF8ACTfdwAvAEEjkKp6ADcfFpBigSj8Wm5fBAVJAEGUMGI6GQoBYTCYEBmAAUFQg0MgQBUZiwcprxdIwABrAj-OJwAAyJ2QRgqaDghtYJrNyhYZXIyBgTFqjpADtwxC9Pr9aGiqjgAEVahB4Lb7X6AFZoAAe-3DUZjcaQdtUDvFAEcs3AVUrlJqUCw0BMbHAUnWxSBvSxTNEAMJ4LpaiqqRth8gRt4wb3EBi1eAqnbWmzxvN+wgwXCqADqJHgKndcH+Go0xCiMByWrAaANIAivs8UHrsH+YCYxClbyv-wPEdn+ZAyiVDuXrGUWq-EIdgiOBG1IB0mBgUtri7HME3FN0mAgrUGBYbZewQ+9YGXYgUiIZAKTxcV-CLYh-GgshYNzD8YDQnC8MIZBRHFWoHQAFTQitqL9OAtjresUktNgyFqa44AAMT8M5pU9StxwgEBaVpIA)

```sh
--parser babel
```

**Input:**

```jsx
const something = '  branch1\n* branch2\n  branch3'.split('\n')
.filter((line) => {
 // Ignore branches having names that indicate they're not special
  return !(
   line.match(/^[\d]+-[\w]/) || // Numbered branches
    line.match(/staging|master|HEAD/) || // Specific branches to omit
    line.match(/^something-.+-[0-9a-f]{8,8}$/) // Something
  );
})
.sort();

```

**Output:**

```jsx
const something = "  branch1\n* branch2\n  branch3"
  .split("\n")
  .filter((line) => {
    // Ignore branches having names that indicate they're not special
    return !(
      (
        line.match(/^[\d]+-[\w]/) || // Numbered branches
        line.match(/staging|master|HEAD/) || // Specific branches to omit
        line.match(/^something-.+-[0-9a-f]{8,8}$/)
      ) // Something
    );
  })
  .sort();

```

**Expected behavior:**

```jsx
const something = "  branch1\n* branch2\n  branch3"
  .split("\n")
  .filter((line) => {
    // Ignore branches having names that indicate they're not special
    return !(
        line.match(/^[\d]+-[\w]/) || // Numbered branches
        line.match(/staging|master|HEAD/) || // Specific branches to omit
        line.match(/^something-.+-[0-9a-f]{8,8}$/) // Something
    );
  })
  .sort();

```

So, two things:

1. the placement of the last comment should still be on the same line, not moved
2. no need for extra parenthesis around the 3 line.match() statements.  They were *already* enclosed by a set of parenthesis

**Comment by sosukesuzuki** [comment]
Minimal reproduction:

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBCAFAHSgAh5KAEwEYcAfMnAeipwDMIJs8DCAmcymnAIwEMATs3zRCAZmq1+AL2wBKANzYQAGhAQADjACW0AM7JQggRADuABUEIDKPgBtTfAJ4G1PAXzABrODADKfAC2cAAy2lBwyHT2enBuHt6+fhqe4QDmyDACAK5xILGB2pk5eXAAHhpwAtrBsPYAKlVQgtpwNtF2sWp66XZwAIrZEPBRMXkAVnplfr0DQyNIHV0gAI7zcOYmGjYgfHoAtBFwhMeqIFl82nbpAMIQgYF8yLt2dmc9UGl9AIIwWdo8bLwcxVMIRUadPIACxggTsAHUodp4HoUmA4H5rMjtAA3ZFOZ5gPSuEA43IASSICH8YGqWm+RD8MCcfQhyw0Jli8I8GmeHLaVRxkTU4ViAhgmz4aUebLyKQEYue-B4cDeag54Rg8O0hBgUOQAA4AAxqARwNbaM2S6VPRZjNQwPg8bW6-VINhqbKxepO9r2kBwQIqwgnQghPifbJSuAAMQgAkef3Szz4QIgIAAvhmgA)

```sh
--parser babel
```

**Input:**

```jsx
!(
  cond1 || // foo
  cond2 || // bar
  cond3 // baz
);

```

**Output:**

```jsx
!(
  (
    cond1 || // foo
    cond2 || // bar
    cond3
  ) // baz
);

```

**Comment by Peter-Sparksuite** [comment]
Yeah, this is still happening with Prettier 3.2.4

**Comment by Peter-Sparksuite** [comment]
And still broken in Prettier 3.2.5, too!

**Comment by Peter-Sparksuite** [comment]
Hey there!  It would be *really nice* if we could have a fix for this problem some time soon.

I have no idea what else is being worked on, but, for me and those around me, this being fixed would be *really appreciated*.

Many thanks!

**Comment by Peter-Sparksuite** [comment]
Bummer, this is still broken with 3.3.0.  Would be really appreciated if this can be fixed soon!

thank you!

**Comment by Peter-Sparksuite** [comment]
Well, I see that 3.3.3 has been released, and this is still an issue.

Curiously, but perhaps not unexpectedly, this playground manages to avoid the issue by way of an undesirable hack of [adding another item to the list](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaIFs4wAWAllAOaYC8mA5JpgEYBOAhlGIQIwA63UAVI1btCAJl5R6zNhwDMNAHRoADgBtiMABQ0JNAJR8FAM2Kr4TTZvVQ4eqgD5MwPpgD0rzAEkyUCEzhCMoRwaJiELABupBRQLPihRCxYpAAmxGBJAURwAJ40-pi+WCpwYMQsqi6Y-jAArkySAISaVZjWcAq4SRyargB6ANq8KQC6ANQAtEPcAO4jrnYAPotuHgBytbgMcP4pgSIhrW2kHV0wPa4YLGTRi10YO4sAEgCiAIIAIguYy6uYAMrKUrEExgfYcEKYGAQTB4DRHdqdbqEXp9HD4IjRCYKSYDAAMEwAnCwJkYRsAABwAGgpAF8ACTfX7uAF4AgkchHIwVNBwKp6ADcfFpBigSj8WkFfBAVJAEGUMGI6GQoBYTCYEBmAAU1Qg0MgQBUZiwcvrZdIwABrAj-OJwAAyJ2Q3NUvPNrCtNuULDK5GQMCYtTgst5uGI-sDwZAcAAHkCmMR8LAKgAVHaxBMhZ08qNoaKqOAARVqEHg2ddUYAVmgY-980WS2WkC63SAAI6NuBajXKfUoFhoCY2OApEcykABlimaIAYTwXQNFVU47z5ALbxgAeIDFq8C1O0dNnLrcIMFwqgA6iR4CofXB-nqNMQojAcgawGgzSAIkHPFBR7A-xgAmCpvP+-yvgWx5RsoGq8herDKAasEhDsERwOOpC8kwMDdtcC7Njmsrekw2EGgwLDbMuxEJrAF7ECkRDIBSeKyv4HbEP4eFkARLZRjAlH0YxhDIKIsq1LyKaUX2fGynAWwjqOKT2mwZC1NccAAGJ+Gcip+v2u4QCAtK0kAA) of `OR`d tests.

But, I'm expecting there's a proper fix for this that should be done.

**Comment by Peter-Sparksuite** [comment]
Thank you so much for the fix!  I'm looking forward to this being available :)

👍
