### ISSUE TITLE
Preserve indentation of ignored blocks inside script tags

### ISSUE THREAD

**Issue by joseluisq** [prettier/prettier#1567]
For example, I have this GA script and I would like to ignore it:

![How ignore blocks inside script tag](https://cloud.githubusercontent.com/assets/1700322/25849366/7f440010-34be-11e7-9879-9029807adb85.png)

But prettier says:
```
prettier-atom failed!
SyntaxError: Invalid regular expression: missing / (1:18)
> 1 | rettier-disable */
    |                   ^
  2 |       (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  3 |       (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  4 |       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
```

**Comment by hawkrives** [comment]
I don't think that Prettier is intended to run on script tags? I'm fairly sure that the error you're getting is because it's trying to interpret your entire HTML file as JavaScript. 

Note: I may be entirely wrong.

**Comment by joseluisq** [comment]
Sure, but I think that "maybe" Prettier could behave like it does with Vue components. https://github.com/prettier/prettier-atom/pull/44/files#diff-27a1c86133de4310373decfdad200a91R64

"Maybe" this could be a future enhancement. I don't know.. :smile:

**Comment by lydell** [comment]
@joseluisq Sounds like an issue for prettier-atom?

**Comment by josephfrazier** [comment]
> `/* prettier-disable */`

I don't know if this has anything to do with the problem, but I think the correct syntax is `/* prettier-ignore */`. See https://github.com/prettier/prettier/blob/225fa577804aeed85cf537a434262c8a3001f36a/src/printer.js#L61

**Comment by joseluisq** [comment]
> /* prettier-ignore */

Thanks, now works! Sorry for confusion :smile: But it appears that Prettier doesn't preserve my indentation:

Before:
![image](https://cloud.githubusercontent.com/assets/1700322/25867496/011867e4-34fa-11e7-9f3e-6887bb9fde10.png)

After:
![image](https://cloud.githubusercontent.com/assets/1700322/25867553/2c5bc3a6-34fa-11e7-9e76-776cf8446a2b.png)

**Comment by lydell** [comment]
This sounds like #1324 now.

**Comment by joseluisq** [comment]
> @lydell
yep, it's related.

**Comment by vjeux** [comment]
#1609 fixes it :)))

**Comment by joseluisq** [comment]
:+1:
