### ISSUE TITLE
Option to turn off {' '} tags in JSX

### ISSUE THREAD

**Issue by grydstedt** [prettier/prettier#1569]
We have some localization code that assumes certain html structure is created from JSX. We love prettier but the adding of {' '} inserts unexpected spans in React. Would it be possible to add an option to turn this behavior off? I can try to cook up a PR if so.

**Comment by vjeux** [comment]
Could you try to patch https://github.com/prettier/prettier/pull/1120 and see if it fixes your issue? It should put {' '} way less often.

**Comment by grydstedt** [comment]
@vjeux thanks! will try that out.

**Comment by vjeux** [comment]
Does it work for your usecase?

**Comment by grydstedt** [comment]
It worked cleaning up some of it and for others I just used `prettier-ignored`. Definitely an improvement though

**Comment by vjeux** [comment]
Cool thanks!
