### ISSUE TITLE
Experimental ternaries enabled by default

### ISSUE THREAD

**Issue by arkadiuszbachorski** [prettier/prettier#15697]
**Environments:**

- Prettier Version: 3.1.0
- Running Prettier via: CLI
- Runtime: Node v18.18.2
- Operating System: MacOS 14.1 (23B74)
- Prettier plugins (if any): none

**Steps to reproduce:**

In project dir with v3.1.0 installed:

```bash
yarn run prettier --write '{src,design-system}/{**/*,*}.{js,ts,jsx,tsx,css,pcss}'
```

with config (inside `package.json`): 

```json
{
  "prettier": {
    "trailingComma": "es5"
  },
}
```

**Expected behavior:**

No experimental ternaries enabled

**Actual behavior:**

Experimental ternaries are enabled. Code is formatted according to new ternaries.

When I run `yarn run prettier --help` I see `--no-experimental-ternaries` option.

Ternaries are using experimental syntax when I run with `--no-experimental-ternaries` as well

**Comment by kachkaev** [comment]
👋 @arkadiuszbachorski could you please share a Playground example depicting issue? I guess you have noticed a diff i the ternaries like the one in https://github.com/kachkaev/njt/pull/511 and have concluded that you are opted-in to the new ternaries. Default behaviour has changed too in 3.1, see [blog post](https://prettier.io/blog/2023/11/13/3.1.0.html#add-indentation-back-to-nested-ternaries-9559httpsgithubcomprettierprettierpull9559-by-rattrayalexhttpsgithubcomrattrayalex) and https://github.com/prettier/prettier/pull/9559.

**Comment by arkadiuszbachorski** [comment]
@kachkaev Ouch I misunderstood the changes then. I understand it now after re-reading that blog post. It can be closed on my end, I'll leave that up to you. Thanks a lot!

Therefore I think I have to opt-in into experimental ternaries, as I am not a big fan of the nested ones. "case-style" ftw :)
