### ISSUE TITLE
Support for import attributes with TypeScript

### ISSUE THREAD

**Issue by marvinruder** [prettier/prettier#15699]
**Environments:**

- Prettier Version: 3.1.0
- Running Prettier via: VS Code plugin (`esbenp.prettier-vscode`), also via ESLint and `eslint-plugin-prettier@5.0.1`
- Runtime: Node.js v21.2.0
- Operating System: Dev Container based on Alpine Linux 3.18.4
- Prettier plugins (if any): –

**Steps to reproduce:**

Process the file

```typescript
import packageInfo from "../../package.json" with { type: "json" };
```

with TypeScript parser.

[https://prettier.io/playground/…](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAkwEMwBrIgczgEkoAzCfOnCdfAHRADouB6H3sTKU4XAFYBnaJ3wB3VDAAW+YPhgBPTHCQcQk6SHwBfANzsoIADQgImGKmgTkoIjhayACq4ROURADayROpO1gBGOCSkcDAAykTocAAyqFBwyHQBEnDhkWQxsUKpFMgwOACuOSDZ6KilFVVwAB5aOBgIMAEAKnA4UK6ocL6Z-tnWEsX+cACK5RDwGVlVkk2xkzNzC0gjYyAAjptwHiyYviBEEgC0aXAAJndWIGVEqP7FAMKs6ETI5-7+jwmUAoUwAgjAyqgwuV4B5eik0otRlVFDB0P4AOqKBRDIRwWI+BSoABuCnUvzAElCIGJlVo91gsTAbTsoKgt1iGimSN2mBY2QxkUwvz5Q16xPS1lS2Twx0o3x5VWIOBlvw0WgkzNQdkefNSMAxqFuSmQAA4AAzWHBwA6oa1yigK7ZLaydMKG42KZAAJms5WyXSIYWGLpAcHQYTu91uSSIwPKIgAYrhvhDir8iDCICAjEYgA)

**Expected behavior:**

No errors

**Actual behavior:**

`SyntaxError: ';' expected. (1:46)`

**Comment by fisker** [comment]
We need wait for  https://github.com/typescript-eslint/typescript-eslint/pull/7968

**Comment by Danones** [comment]
Need this working too. Thanks 🙏🏽
