### ISSUE TITLE
Ternary indentation changed from 2.8 to 3.1 without experimental flag on

### ISSUE THREAD

**Issue by Yohandah** [prettier/prettier#15702]
edit: I have now seen the 3.1 changelog in which the change is specified but it's supposed to be behind an experimental flag and not default behavior ?

From 2.8 to 3.0, the spaces for ternary operators changed, which is causing a lot of noise in my project's PR since we updated to 3.0. I was wondering if that was an intended change because I can't seem to find evidence of this change while exploring the 3.0 changelog.

**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8OYLyYAUAlPgHybAA6UmmkUuOMA8gEYBWcYWB1tdTADcAhgBsArnCQ1BggNZwAngDoYSgA5x8eAlRAB9AwBkAggCEAosaP7ZcwQH5M+mACcAlgHMvcN5aEEGGMRNjgxEjsBB0wkTEVVdS0dPUMDABVTAHFbEHsY51dPHz8AoPSRLzRIvOiHOIADd29ff0DYUxh3QgByABJgBJUoEQBbOABfHuIGgBp7CYBuGnsGJjgMdi4eACZ8SnzhcSkZOrohpO1dVKMzKxsDKJi6ZwvNK90XNMycx9rnpxfZolNrlSrVYhPAGxTBNYqtModLpuXoDIYjcZTGaHORxIotUrtYKhcI1eYCJY0SlQECzEAQDQwDzoZCgERuNwQADuAAV2Qg0MgQOIuSIlIK6Ww3CIwIoYABlMZwYweKBwZAAM3EaDgkulsrgCo0MtVXmQ7ikdJ1ow85rclpAcAAHlpPONYOJ0n4Rp4NprtbqQGhTWI4ABFCQQeB2h0cNBO+Uh8OR6NILViHV0gCOKbgPM5GkFKBEaAAtGq4AATKu0kDuEQeMSmgDCEFGoxEQvEYlrwagXlDnWabAk8B5fhVav9GcDAAsYKMxAB1WceHDGsBweUCtceIRrpRCsBoCUgIRSACSUGrsHlYE8jNM1-l6lD08zIA0nJ1S+lGiFX4bH4gS1qqOpuDA+aVB276BsabjgUKbAkj2dJfqqMBLh4lYwLOyAABwAAx0m4cA5h4pFQV4MFpgGdIwKEWE4XhSA7HSEg6hUbBFumH5wKMYSVtWlYhP2EiVHAABiEBuB2XSml2o4QCAEwTEAA)

```sh
--parser babel
--single-quote
```

**Input:**

```jsx
const test = () => {
  const testObject = {
    value:
      key.type === "__LABEL__"
        ? "triggerEventLabel()"
        : key.type === "__TAG__"
        ? "triggerEventTags()"
        : `triggerEventAttr('${key.name}')`,
  };

  const testObject2 = {
    value:
      key.type === "__LABEL__"
        ? key.type === "__TAG__"
          ? "triggerEventTags()"
          : `triggerEventAttr('${key.name}')`
        : "triggerEventLabel()",
  };
};
```

**Output:**

```jsx
const test = () => {
  const testObject = {
    value:
      key.type === '__LABEL__'
        ? 'triggerEventLabel()'
        : key.type === '__TAG__'
          ? 'triggerEventTags()'
          : `triggerEventAttr('${key.name}')`,
  };

  const testObject2 = {
    value:
      key.type === '__LABEL__'
        ? key.type === '__TAG__'
          ? 'triggerEventTags()'
          : `triggerEventAttr('${key.name}')`
        : 'triggerEventLabel()',
  };
};
```

**2.8:**

```jsx
const test = () => {
  const testObject = {
    value:
      key.type === "__LABEL__"
        ? "triggerEventLabel()"
        : key.type === "__TAG__"
        ? "triggerEventTags()"
        : `triggerEventAttr('${key.name}')`,
  };

  const testObject2 = {
    value:
      key.type === "__LABEL__"
        ? key.type === "__TAG__"
          ? "triggerEventTags()"
          : `triggerEventAttr('${key.name}')`
        : "triggerEventLabel()",
  };
};
```

**Comment by fisker** [comment]
Indentation is added

**Comment by kachkaev** [comment]
👋 @Yohandah! Please see replies in ttps://github.com/prettier/prettier/issues/15697. Closing as duplicate.

**Comment by Yohandah** [comment]
Thank you for your quick answer, indeed I misread the blog post into thinking all of the ternary changes were behind the feature flag 👌🏻

@fisker however, I have the ternary diff also with 3.0
