### ISSUE TITLE
`ifBreak` propagates a `break-parent` even if that option wasn't the printed result

### ISSUE THREAD

**Issue by Janther** [prettier/prettier#15710]
ifBreak has a funny behaviour when there's a `hardline` and a `line` in the `ifBreak` and `noBreak` respectively.

It would print the `line` but also propagate the `break-parent`.

**Environments:**

- Prettier Version: 3.1.0
- Running Prettier via: CLI
- Runtime: Node 21
- Operating System: macOS
- Prettier plugins (if any): 

**Steps to reproduce:**

I created this [gist](https://gist.github.com/Janther/6491d4c8f56d4ec5b4a0af7567f85a3b) to show. 

**Expected behavior:**

ifBreak will not propagate a `break-parent` if that option was not chosen.

**Actual behavior:**
ifBreak is propagating a `break-parent` even if the options chosen does not break.

**Comment by Janther** [comment]
The whole doc is traversed and the break lines propagated here:

https://github.com/prettier/prettier/blob/8d64505bd47bddb5f559f4a1eead64a158d81c5a/src/document/printer.js#L320

just before the tree is evaluated and the `ifBreak` decided.

**Comment by thorn0** [comment]
It's rather a design limitation than a bug. There usually are other ways to achieve the desired result. E.g. "break B if A is broken" usually means that A and B should be parts of the same group while not being groups themselves.

**Comment by Janther** [comment]
I did code without the need for it.

However this limitation could be added to the builder's documentation.

Since it was difficult to spot why my group was breaking.

The example I put in the gist was a simplified one.

**Comment by thorn0** [comment]
Totally agree that this should be mentioned in commands.md. I tripped over this too when I was new to Prettier.
