### ISSUE TITLE
`md` tagged template is unstable/incorrect for short strings

### ISSUE THREAD

**Issue by billyjanitsch** [prettier/prettier#15711]
When the `md` tagged template is used within JS on a short string, Prettier's output is unstable, and both outputs are unexpected.

**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjAhgE0wF5MBbfAAwB0pNMAzCCG6qGyKDTAcycJPKs6AQUwAbaNzgAnTBmkBLKN0wwAFriwB3abgAOaTFoVixmPdLgA3BFgAKlmDAUyG0iKUwarSleoWGAWgArnAsIAA0IBB6zujIoLjS7lp2SQhoyCC4Ylq4AJ6ZUdi6YADWcDAAyrikcAAySnDI9DlocMWlFdV6uGC+yDDSoVHtpAqDwx0gcAAeejIKdbA5ACoyUEkumUitYu2jvmJwAIrBEPAtbdMAVmizVUen55e711EAji9wDjE72WgALRQOBwfBgyIgIa4Ey+ADCHlIuCyOTEkLQT2ETkU2GC8DsMkaIKu+2mahgpDEAHU1Ap4GhemA4FUMnSFD4YPksmA0EUQFZQgBJKDg2BVMCKWLCEVVTnHEkHEAWCDtKm6PRZCxwdrSGyQpQ6mAOXDcJEK6a9aQ6rJ4bBwNFRCxKGBUhT4dTIAAcAAYopYvgpLMbTci3qSojBcNhXe61MgAExRYLtVZRnZ7RVwUh2-Dg-D1XDKYImuAAMQg0iRTgGKFweIgIAAvo2gA)

```sh
--parser babel
```

**Input:**

```jsx
const bad = md`
  foo
`

const good = md`
  A longer string that wraps will prevent Prettier from having this issue
`
```

**Output:**

```jsx
const bad = md`foo`;

const good = md`
  A longer string that wraps will prevent Prettier from having this issue
`;

```

**Second Output:**

```jsx
const bad = md`
foo
`;

const good = md`
  A longer string that wraps will prevent Prettier from having this issue
`;

```

**Expected behavior:**

There are two issues here:

1. The output is unstable.
2. Neither output seems correct.

The first output is somewhat understandable (though not what I'd expect) but the second output doesn't make sense, especially compared to the longer line below it.

Ideally, I'd expect the output to match the input exactly:

```jsx
const bad = md`
  foo
`

const good = md`
  A longer string that wraps will prevent Prettier from having this issue
`
```

This may or may not be related to https://github.com/prettier/prettier/issues/5885, which references a similar issue within JSX.

**Comment by kachkaev** [comment]
Thanks for sharing a playground example @billyjanitsch! Let’s track this issue in https://github.com/prettier/prettier/issues/5885. It was indeed scoped only to JSX, but I changed the title and included your example. Feel free to submit a PR!
