### ISSUE TITLE
NumericLiteralTypeAnnotation

### ISSUE THREAD

**Issue by jamiehodge** [prettier/prettier#1572]
Seeing the following exception in a flow declaration file:

```js
declare type FieldType =
  	| 0x00
  	| 0x01
  	| 0x02
...
```

`Error: did not recognize object of type "NumericLiteralTypeAnnotation"`

Using the flow parser converts the literals to ints

**Comment by vjeux** [comment]
Do you mind updating your prettier version to the latest one, it has been fixed a while ago. https://prettier.github.io/prettier/#%7B%22content%22%3A%22declare%20type%20FieldType%20%3D%5Cn%20%20%5Ct%7C%200x00%5Cn%20%20%5Ct%7C%200x01%5Cn%20%20%5Ct%7C%200x02%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
