### ISSUE TITLE
How to change prettier format?

### ISSUE THREAD

**Issue by zhaoyi0113** [prettier/prettier#1574]
I have below code need to prettier:

```
db.getSiblingDB("test").msg.find({$or: [
{ filename: "1046." }
,
{ "headers.From": "*com" }
]}).sort(
{"headers.To":1}
).limit(10)
```

the formatted result is shown as below:

```
db
  .getSiblingDB("test")
  .msg.find({
    $or: [{ filename: "1046." }, { "headers.From": "*com" }]
  })
  .sort({ "headers.To": 1 })
  .limit(10);
```
what I want is put the dot `.` at the end of each line as below:

```
db.
   getSiblingDB("test").
   msg.find({
     $or: [{ filename: "1046." }, { "headers.From": "*com" }]
   }).
   sort({ "headers.To": 1 }).
   limit(10);
```

I am not sure whether `prettier` support making such change.

**Comment by azz** [comment]
> I am not sure whether prettier support making such change.

It does not. This style of punctuation is quite rare, and prettier only has settings for the most controversial/common variance of stylistic choices, such as omission of semi-colons, and tab width.

**Comment by zhaoyi0113** [comment]
The reason I want to support such punctuation is required by `mongoldb-shell`. If it doesn't support such format could you give me a suggestion on which source code I should work on in order to add this support. I am going to fork this repo and make the changes by myself.

**Comment by azz** [comment]
You'll need to look at [printMemberLookup](https://github.com/prettier/prettier/blob/master/src/printer.js#L3159) and [printMemberChain](https://github.com/prettier/prettier/blob/master/src/printer.js#L3196).

You could also just add the `// prettier-ignore` comment if db queries are infrequent.

**Comment by vjeux** [comment]
This is highly surprising that mongodb-shell doesn't allow dots at the beginning, this would mean that they use a non standard JavaScript interpreter. Do you have more information I can read about this?

**Comment by zhaoyi0113** [comment]
The problem is that when I send the first line of above code which is `db`, it is a valid `mongo shell` command used to print the current database name. So after that starting from the second line, `mongo shell` will not recognise command start with `.`.

**Comment by vjeux** [comment]
Interesting... Can you try adding `{ }` around your code and see if mongodb executes them correctly?

I do not want prettier to handle those esoteric environments, as it raises the complexity by a lot to do it properly. In this case, we should look for a workaround that would work with mongodb shell such as the one I suggested.

If we can't find a suitable one, you may not be able to use prettier for your use case I'm afraid :(

**Comment by zhaoyi0113** [comment]
I have tried that but it doesn't work. Actually it would be great if prettier provide a way like `plugin` to allow other developers to change the formatting behaviour.

**Comment by vjeux** [comment]
I'm sorry but we're not going to support this use case with prettier :( You best option is to fork it if you want this to work. I can't guarantee that something else is not going to break though.
