### ISSUE TITLE
Code block wrong formatting in mdx file when immediately preceded by a component

### ISSUE THREAD

**Issue by tonai** [prettier/prettier#15740]
**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAyhAtnAwtgB2gRgHoA+AHSgAM6YBnAD2oEssiAnGAAgCU4AQzC8AZp2w8A5JyEipAbmrVSpHgHdOreDwbY4PSABM41OjRAAaEBAIxW0BslCDOE9QAVXCJykEAbdUEATydrACNOYQBrOBh0QRwAGVYoOGRRAIY4CKiwWPiCYVSAc2QYTgBXHJBsrFZyqpq4JgI4LRxYAIAVdqhXVjhfTP9s6wZS-zgARUqIeAysmoArZnRJmbmFpBGxkABHLbgPCQJfEEEGAFo0uBMjKxAKwVZ-UvwsLEFkC-9-R4mUBKUwAgjAKqxwpV4B52ik0otRjUABYwLD+ADqyO0QyKYDg6B82lYADdtMEfmAGGEQCTqgBJKAmWDoMBaOwgpnoGDBKaIvYECTZDFRAg-QVDdok9LWVLZbgnQQlL78mpFTjyn5YIxMR6C1IwDGsIwwZHIAAcAAZrLJDqxZIrld8dktrDBBOEjSazUgAEzWSrZboe4aukBwLDhO73JKCIGVJVwABiEE4X3BpR+gmhEBAAF880A)

```sh
--parser mdx
```

**Input:**

````mdx
<SomeComponent/>
```tsx
import React from 'react';

// write some code
```
````

**Output:**

````mdx
<SomeComponent />
```tsx import React from 'react';

// write some code

```

```

````

**Expected behavior:**

````mdx
<SomeComponent/>
```tsx
import React from 'react';

// write some code
```
````

**Comment by kachkaev** [comment]
Seems to be an issue with MDX 3 support. Let’s track it in https://github.com/prettier/prettier/issues/12209 with other similar issues.
