### ISSUE TITLE
Prettier v3 ESM jest compatibility ("A dynamic import callback was invoked without --experimental-vm-modules")

### ISSUE THREAD

**Issue by jdb8** [prettier/prettier#15769]
**Environments:**

- Prettier Version: 3.1.0
- Running Prettier via: Node.js API
- Runtime: Node.js 20.10.0
- Operating System: Linux, Mac
- Prettier plugins (if any): n/a

**Steps to reproduce:**

* Install prettier 3.1.0 and Jest 29.7.0
* Write a basic test such as:
```js
const prettier = require('prettier');

it('works', async () => {
  await prettier.format('var foo = 1;');
});
```
* Run the test via `jest`

**Expected behavior:**

The test passes with no errors, the same as prettier@2.8.5

**Actual behavior:**

```
❯ jest
 FAIL  ./index.test.js
  ✕ works (1 ms)

  ● works

    TypeError: A dynamic import callback was invoked without --experimental-vm-modules

    > 1 | const prettier = require('prettier');
        |                                     ^
      2 |
      3 | it('works', async () => {
      4 |   await prettier.format('var foo = 1;');

      at Object.<anonymous> (node_modules/prettier/index.cjs:593:23)
      at Object.<anonymous> (index.test.js:1:37)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.156 s, estimated 1 s
Ran all test suites.
```

under node 18 (via a [stackblitz repro](https://stackblitz.com/edit/stackblitz-starters-nwa2kc?file=index.test.js)) instead the error is:

```
❯ jest
 FAIL  ./index.test.js
  ✕ works (1 ms)

  ● works

    Expected value   undefined
    Received:
      undefined
    
    Message:
      You need to run with a version of node that supports ES Modules in the VM API. See https://jestjs.io/docs/ecmascript-modules

    Difference:

    Compared values have no visual difference.Error:

      at invariant (node_modules/jest-util/build/invariant.js:16:11)
      at Proxy._0x4ab5e0 (https:/stackblitzstartersnwa2kc-vjj3.w-credentialless.staticblitz.com/blitz.72112de7.js:352:200463)
      at Object.<anonymous> (node_modules/prettier/index.cjs:593:23)
      at Object.<anonymous> (index.test.js:1:37)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.226 s, estimated 1 s
Ran all test suites.
```

Both error cases seem to be related to prettier using functionality that requires ES modules, even in the .cjs file - which I would naively expect to be pure commonjs.

----

I want to add a bit more context here: I know that this issue could likely be raised on the jest side too since this seems to be related to the way jest imports/invokes scripts, but this is something that worked fine under 2.8.5 and seems to have broken since the migration to ESM in 3.0.

I couldn't find anything in the docs regarding changing the way we import prettier, but having experienced ESM incompatibilities before, I tried explicitly transforming `prettier` to commonjs using jest's `transformIgnorePatterns`, which introduced more issues regarding `import.meta`, `__dirname`, etc.

Mainly looking to rule out a simple fix before delving into this further. Apologies if I've missed an existing issue capturing this problem - I didn't find one when searching.

**Comment by christophehurpeau** [comment]
Prettier v3 will be supported in jest 30 (https://github.com/jestjs/jest/issues/14305)

**Comment by kachkaev** [comment]
Yep. https://github.com/jestjs/jest/issues/14305 has ben fixed upstream, so let’s close this issue. @jdb8 if you experience any problems with Prettier and Jest [v30.0.0-alpha.1](https://github.com/jestjs/jest/releases/tag/v30.0.0-alpha.1) or above, please open an issue in https://github.com/jestjs/jest.
