### ISSUE TITLE
Using prettierPluginEstree in standalone mode causes "Invalid left-hand side expression in postfix operation"

### ISSUE THREAD

**Issue by simerlec** [prettier/prettier#15762]
Hello,

when using the `esTree` plugin in standalone mode (like it is explained here https://prettier.io/docs/en/browser) we're getting a `Invalid left-hand side expression in postfix operation`. 

![image](https://github.com/prettier/prettier/assets/5793380/dc71738c-b9d1-4224-952f-8ed2275db28b)
![image](https://github.com/prettier/prettier/assets/5793380/4a115f9b-9596-413c-8ae6-7345934668f8)

This happens only on production builds so I guess it has something to do with minification? Not sure though 🤔 

**Environments:**

- NextJS project (13.1.0)
- Prettier Version: 3.1.0
- Running Prettier via browser (standalone mode), installed via npm
```
import prettier from 'prettier/standalone';
import prettierPluginBabel from 'prettier/plugins/babel';
import prettierPluginEstree from 'prettier/plugins/estree';
import prettierPluginHtml from 'prettier/plugins/html';
import prettierPluginPostCss from 'prettier/plugins/postcss';

export async function formatWithPrettier(filepath: string, text: string) {
  const result = await prettier.format(text, {
    filepath,
    plugins: [
      prettierPluginBabel,
      prettierPluginEstree,
      prettierPluginHtml,
      prettierPluginPostCss,
    ],
    tabWidth: 2,
  });

  if (filepath.endsWith('.css')) {
    return uppercaseHexColors(result);
  }

  return result;
}
```
- Runtime: any browser
- Operating System: any OS
- Prettier plugins (if any): see usage code snippet above

**Steps to reproduce:**

see usage code snippet above

**Expected behavior:**

Web app loads without error

**Actual behavior:**

Web app crashed with JS parse error.

**Comment by thorn0** [comment]
This repo isn't the right place for this issue. https://github.com/vercel/next.js/issues is.

**Comment by Jaikant** [comment]
I am seeing the same **nextjs** issue. The scenario is exactly the same and on nextjs production build.
@simerlec Did you find a solution?

**Comment by simerlec** [comment]
> I am seeing the same **nextjs** issue. The scenario is exactly the same and on nextjs production build.
> 
> @simerlec Did you find a solution? 

Hey @Jaikant,

The problem was Next 13.1.0 so the solution was to upgrade NextJS. I believe the issue was already fixed when using the next minor (or patch?) version. Give it a try.
