### ISSUE TITLE
[Request] Allow configuration variable to avoid breaking single attribute html tag into 3 lines

### ISSUE THREAD

**Issue by adamkdean** [prettier/prettier#15768]
In the ticket https://github.com/prettier/prettier/issues/15199 @christhofer described an issue of a single attribute HTML tag being formatted into three lines, with @kachkaev illustrating the issue perfectly like so:

**Input**

```html
<div id="categories" class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
  div content here
</div>

<div class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
  div content here
</div>
```

**Output**

```html
<div
  id="categories"
  class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
>
  div content here
</div>

<div
  class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
>
  div content here
</div>
```

**Desired behaviour:**

```html
<div
  id="categories"
  class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
>
  div content here
</div>

<div class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
  div content here
</div>
```

There is a very valid point that any change to default behaviour would lead to millions of lines of coding being needlessly changed, but I think it's also very valid to request that this be explicitly configurable. If there was a `dontBreakSingleAttributeLines` to disable this behaviour, we'd be able to avoid the needless line breaks while maintaining backward compatibility. 

What are your thoughts?

**Comment by kachkaev** [comment]
👋 @adamkdean! Please see [Option Philosophy](https://prettier.io/docs/en/option-philosophy.html)

> Prettier has a few options because of history. But we won’t add more of them.

**Comment by adamkdean** [comment]
That's a fair point about the diff there @kachkaev. Appreciate the feedback and chosen approach prettier is taking, wasn't aware of that. Thanks
