### ISSUE TITLE
await IIFE lacks space in TS markdown code block

### ISSUE THREAD

**Issue by kirkwaiblinger** [prettier/prettier#15775]
**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdMDOAdKBDAdzwEsYAKMgSgAIBeAPmuAF9KBuagek+rgA8ADnDDwAJtTzVMAvGDjUAFnABOcAIS48mAJ5Qw1AGYBXPTGLRDVJrmoSipahRoMmrDtyky51YpmoDVTAQYRRV1XGZcdFRcKPQAKxx8exCnOkYWdi4eAghlAGsJP34hEThxYihqRM0dPUMTEXMqgytgGzsSVKsXTLYIuNQQABoQCAEzaExkUDxlZQgCAAU5hGmUPAAbIm1p0YAjZVl8uBgAZTwAWzgAGUq4ZAMtoIOjsBPzr0qAc2QYZSMcFGQUuxD+AKBIBKKmI11gWwAKip8MpiHB1k9Ni8QJgfps4ABFIwQeCPZ6QxJ8M54wnE0lITHYgCOdLgSwWAnWIC0AFooHByuURiB-iRNj8AMIQS6XPDIbmbTbC3FQb74gCCMH+xH2RngSxUd35ZKxkIUMEumwA6gpSOivHAzmtSMQAG6kbTysCYPYgV2AgCSUFEwTOYFRE3VwbOMG0+JN2ICECCVqOAnlAXRKldD1GlSCyhg7Lw31lCchMmUBflsoKokWUGFAUqMCtxFEMAUyAAHAAGUaqFnEVTF0tyhnk0YwPD7NsdrtIABMoyMQQRM4xk6hl325RDohueFVRhLcAAYnlZVqfvK8HqICBmMwgA)

```sh
--parser markdown
```

**Input:**

````markdown
```ts
await(() => {}); // expected a space here!
async function f() {
  await (() => {}); // space is present here!
}
```

```js
await (() => {}); // work as expected in js
async function f() {
  await (() => {});
}
```
````

**Output:**

````markdown
```ts
await(() => {}); // expected a space here!
async function f() {
  await (() => {}); // space is present here!
}
```

```js
await (() => {}); // work as expected in js
async function f() {
  await (() => {});
}
```

````

**Expected behavior:**

````markdown
```ts
await (() => {}); // expected a space here!
async function f() {
  await (() => {}); // space is present here!
}
```

```js
await (() => {}); // work as expected in js
async function f() {
  await (() => {});
}
```

````

**Comment by kachkaev** [comment]
👋 @kirkwaiblinger! I have been able to reproduce the lack of space in plain TypeScript, i.e. outside Markdown. Seems that this issue is already tracked: https://github.com/prettier/prettier/issues/6608. Let’s continue the discussion there. Feel free to open a PR if you have capacity.
