### ISSUE TITLE
Different output for optional call/member expression using `typescript` parser vs `babel` and `babel-ts`

### ISSUE THREAD

**Issue by faultyserver** [prettier/prettier#15785]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAwgQQMoCiGAjEgDpToYByEATgLYCGANhgEZwAWTAbgJb0ANBhhc4GAAb8AzgQCOAV1aSMYVm3Z04TANYyAdBQBmiqGBiCoGGRAZwAYmYtXqTewAoKGG3bgAZaABzACFtPX4oIIAFJjp3OHg6N3shbwwmKAgxODpAqNj4+ySUuDSoAEoMYHTtGEU6a1kFZRYPJgNmAAcPDwBtGBEAfQBdKoBeAD5RAH4DfgATCpF2TqYe-sGMUYnpmDnFioqAbgoAXwoKKgB1cWsmMDA4GRlRCCkmVUyFqXZVWQwEC6lmgrBEMAAnl1nmA6PxgRgFhBnlAAOQwDjhXRXTA5NQaFaKDHsJicNjfDikuAsAC0MFeSKMUFM5hB1ls9icrNcCS81l89nyoSxkRicQSJQS5R8mWy4jywUKEtypXKVRq-LqDSaciUrHac26vQGwzGGCms3mSxWhvWxq2O3NewOSxO50ulEwuEIGAATORPTR6MxNNw+II6ODxFJjPwWElVOoWGxFDJnhkMEE6BBFNCfiwmBCcxiPF0ia8cjiMnRswB3DBwAAeXW0LysGC64uKuVe0FE0ZkCQwLEiEiYrzIIFj8dyk4qTMgUBkGJyADVWIoJOMMAB5dgAKzgFgMCBgcOeHg5AWCe8PFlK8+nST5Pn6I+XooAkgszRar-5ZBgAAVCAsDsTttBAgAJXI4HmcwWEUBYL3fSwom-ZYKDdKAq2ufgxAyawgTZVgMHsBhODoBtm1bGQrBWKlaXpDBdDgOAugrLgAXHDMsxzPMqwLIsiUJFcoRhOEETMPjc1efDAVgd4mAwKA4HrEdVIXaBl37OB10QrddwPI8YBPWBzxkS8-CFW8TIfAwn1yF8MDfQCvx-XYBQCQCQLAhgILgaDYIOBCkJQtz0OtLDThwwNvSIABmAMqFoRhSM4HgBGEXTRDgfyC3gaiW2eOi+y0HR9AyFdo1jOgdMiJIuggAqrCZFgICCIJcgMdqgmcyQcGHYJcvyphCuXOEogwWt8K4DNFwWfCrFYJAMAAEmAMAeCgVSWCtM4RApHJ2T8Mj6AkRd4FgfsxrUaA0M3V4zEsNgNoAKTwHdqAMCbRX4YwIQ8dr1DZCozkkaKPRuWbCMBYFlrYcjKKK2j6NEcSZFheEMSRFF0UxCqctq5cqwa3ImpavsKUiZcdB+cq9E4iQ0wWtqOq6ugeo6-rBvaqb4FG8az1FaaYeUhaltBFhVo2rbMl2l0DsIn5jq8s7tDu2BTxujFLsiR6MGeuN1uAD6vp+4Won+wHgbGqwwYhypjhAIQQGIqwZGQUA4jrQoEE9lBWFrQtPddrQHlYmA8ASADVOQYxWDTMP4jASO8E7MBRWQM9N1dtMGH4bO6FzkAm2hOF7FgVggNyKA4n4Z548TsoQDoqIWDgABFRRsjgJuWCTkB9xkRs8FFDvu97-vB6UXvomzDjkBAccaVUuBkIWF2QDPJg41FPzmCXjQt7boIO5wGBhfYIk4GiXJY77pAE4HluuBgBgWFufDngzuA8H9paAhIRLzAC8LevBNyfigMhWAeAsbAhwNAvAkIO7Txbi2CAaZrjxC6EvYqaY6C8D7q7GmuQYDzyYEEQ+T9m6uwggQpeJIyRb20Eofg2gKFUKYGg12MBSR4QWGIZAvpXapkCqSAOz9B55U4AsDe-hMhBGUF1BwwYxpoSCEfIkEAt4tgagIoRSBiC+gAAxnDOEAA)

```sh
--parser babel
--print-width 120
```

**Input:**

```jsx
// CASE 1:
// Normal behavior, the `isEqual` call breaks.
function someFunctionName(
  someLongBreakingParameterName,
  anotherLongParameterName,
) {
  return isEqual(a.map(([t, _]) => t?.id), b.map(([t, _]) => t?.id));
}

// When access to `a` and `b` is optional, typescript doesn't break
// the call, but babel and babel-ts do.
function someFunctionName(
  someLongBreakingParameterName,
  anotherLongParameterName,
) {
  return isEqual(a?.map(([t, _]) => t?.id), b?.map(([t, _]) => t?.id));
}

// CASE 2:
// Normal behavior, the `filter` call uses a grouped layout (puts the
// arrow expression parameters on the same line as "filter").
const theValue = Object.entries(someLongObjectName).filter(
  ([listingId]) => someListToCompareToHere.includes(listingId),
);

// With an optional member expression, babel-ts keeps this as a grouped
// layout, but typescript ungroups it onto a new line.
const theValue = Object.entries(someLongObjectName).filter(
  ([listingId]) => someListToCompareToHere?.includes(listingId),
);

// CASE 3:
// Normal behavior, the template expression breaks at the first interpolation.
logger.log(
  `A long template string with a conditional: ${channel.id}, and then some more content that continues until ${JSON.stringify(location)}`
);

// With an optional member expression, typescript doesn't break the first
// interpolation and instead breaks the second.
logger.log(
  `A long template string with a conditional: ${channel?.id}, and then some more content that continues until ${JSON.stringify(location)}`
);
```

**Output:**

```jsx
// CASE 1:
// Normal behavior, the `isEqual` call breaks.
function someFunctionName(someLongBreakingParameterName, anotherLongParameterName) {
  return isEqual(
    a.map(([t, _]) => t?.id),
    b.map(([t, _]) => t?.id),
  );
}

// When access to `a` and `b` is optional, typescript doesn't break
// the call, but babel and babel-ts do.
function someFunctionName(someLongBreakingParameterName, anotherLongParameterName) {
  return isEqual(
    a?.map(([t, _]) => t?.id),
    b?.map(([t, _]) => t?.id),
  );
}

// CASE 2:
// Normal behavior, the `filter` call uses a grouped layout (puts the
// arrow expression parameters on the same line as "filter").
const theValue = Object.entries(someLongObjectName).filter(([listingId]) =>
  someListToCompareToHere.includes(listingId),
);

// With an optional member expression, babel-ts keeps this as a grouped
// layout, but typescript ungroups it onto a new line.
const theValue = Object.entries(someLongObjectName).filter(([listingId]) =>
  someListToCompareToHere?.includes(listingId),
);

// CASE 3:
// Normal behavior, the template expression breaks at the first interpolation.
logger.log(
  `A long template string with a conditional: ${
    channel.id
  }, and then some more content that continues until ${JSON.stringify(location)}`,
);

// With an optional member expression, typescript doesn't break the first
// interpolation and instead breaks the second.
logger.log(
  `A long template string with a conditional: ${
    channel?.id
  }, and then some more content that continues until ${JSON.stringify(location)}`,
);

```

**Expected behavior:**

The output from each of these 3 cases should match regardless of which parser is used (`babel`, `babel-ts`, or `typescript`).

The consistent difference here is whether the expression is `optional` or not. Inspecting the parsed ASTs, Babel (and thus babel-ts) parses these as distinct node types (`OptionalCallExpression` and `OptionalMemberExpression`), but the TypeScript parser just uses the plain `CallExpression` and `MemberExpression` nodes with an extra `optional` property on them.

From https://github.com/prettier/prettier/issues/10244, it seems like maybe in the past (or in a different situation), these were parsed as `ChainExpression`, which then got transformed by Prettier into the appropriate optional expression nodes, but that is no longer the case, so the transform doesn't pick them up and convert as needed.

**Comment by faultyserver** [comment]
As an additional note, it looks like the parser hierarchy is set up to prefer `typescript` first and then use `babel-ts` otherwise: https://github.com/prettier/prettier/blob/c1ebae2e8303841e59bc02e9e719a93e964ab0e9/src/language-js/languages.evaluate.js#L61.

I wonder if preferring `babel-ts` first would make sense, though, since that's already true for regular js, and it would mean more consistent parsing to match it. Obviously TypeScript itself is the best source of truth, but the potential differences in the AST over time will lead to this kind of drift and might be avoidable by using the same parser when possible.

**Comment by seiyab** [comment]
For CASE1, it probably comes from here.
https://github.com/prettier/prettier/blob/1d45bce62575cc4415225545a4d6941f9b91748a/src/language-js/utils/index.js#L718

To find anonymous function in argument, it only checks CallExpression and OptionalCallExpression. However, for TypeScript ESTree, expression like `a?.map(([t, _]) => t?.id)` is not CallExpression nor OptionalCallExpression, but ChainExpression, that has CallExpression as a child ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjA-AOgLYEMAOAFIQNowA0ABAPoC6AlJQLwB8lMWAlgCb0A6UEORAR8MTtADOyULgBOciAHcACvITSUuADZLcAT2nDUc3GADWcGAGVc2OABlOUOMgBmOyXGOmLV6-hmzgDmyDByAK7eIF7YnGGR0XAAHvhwcpz2sDoAKulQ8pxwmh7aXsKSIdpwAIoREPDuntEAVpLJ1lW19Y1IpeUgAI49cCqK+JoguJIAtC5w3AtCIOG4nNohAMIQ2HjIU9ray5VQwdUAgjDhnKgR8CrpTi5NZdEAFjDY2gDqb5zwkkCYDg1g0-04ADd-vp9mBJEYQBCogBJKCLWDWMAZMTnNHWGD6aovAb4RReb6mfD7UnFdIQ1zCZxeOQwMa4YJ7PrNYSBOTM-YEtKSLGcMTLUnOGDfHgwN7IACMACYAAzCORwYacdVsjm4YnRGC4VDS7iy5CK4QRLw5I0lbkgODYVALRbcBy4U4RdlwABiEDkeCuIX2uDuEBAAF8I0A)).

Perhaps `isCallExpression` can cause other similar inconsistencies.
