### ISSUE TITLE
Trouble parsing JSON in browser using prettier/standalone

### ISSUE THREAD

**Issue by mklnz** [prettier/prettier#15780]
**Environments:**

- Prettier Version: 3.1.1
- Standalone in browser
- ESM/Typescript

I'm having trouble using prettier in browser parsing JSON from a string.
Uncaught (in promise) ConfigError: Couldn't resolve parser "json". Plugins must be explicitly added to the standalone bundle.

I understand standalone plugins must be imported, however there is no JSON plugin, how do I import the JSON parser?

**Comment by fisker** [comment]
`plugins/estree` + `plugins/babel`
