### ISSUE TITLE
Unexpected end of JSON input while parsing empty string on empty json config file

### ISSUE THREAD

**Issue by rmehner** [prettier/prettier#15781]
**Environments:**

- Prettier Version: 3.1.1
- Running Prettier via: npm (prettier --write '**/*.{js,ts,json,md}')
- Runtime: Node v20
- Operating System: macoS
- Prettier plugins (if any): none

**Steps to reproduce:**

Given a file `.prettierrc.json` that is just empty, run the command: `prettier --write '**/*.{js,ts,json,md}'`

**Expected behavior:**

Things don't break :)

**Actual behavior:**

With Prettier 3.1.1 this will throw with:

```
[error] JSON Error in /path/to/project/.prettierrc.json:
[error] Unexpected end of JSON input while parsing empty string
```

The fix is to add `{}` to `.prettierrc.json` and things will work just fine. It's a small regression from 3.1.0 to 3.1.1 that I ran into. It's likely related to #15363.

My use case was to have the empty file, so everything is using prettier defaults and VSCode uses the existence of that file to enable prettier within the editor.

Not sure if worth a fix, since my use case might be very much an edge case you don't need to account for, but with this issue here it's at least searchable & solvable for others who run into this :)

**Comment by fisker** [comment]
Our docs suggest use `{}` to  make the empty config  valid, so let's close this.

https://prettier.io/docs/en/install
