### ISSUE TITLE
`Prettier 3.1.1` destroy type declare code by `import()` in `*.d.ts` 

### ISSUE THREAD

**Issue by gyhyfj** [prettier/prettier#15786]
Before:
```ts
// index.d.ts
type LanFile = import('@/i18n/index.js').LanFile
type ReactiveKonva = import('@/konva-reactive').ReactiveKonva
```

After:
```ts
// index.d.ts
type LanFile = import('').LanFile
type ReactiveKonva = import('').ReactiveKonva
```

**Comment by fisker** [comment]
Can't reproduce

**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAMgQygDEBLAGxwF5sSBbDCAJxgAoByAAQHoSBGADig8oAEzgAPAHQArAM5sAlJILFycADqxMOAEpx8YGCQBucANLRj+bNToNm7bgGtL+ALSN9hk3EWS9BkamFlBWIAA0IBAYRtCyyKD4jIwQAO4ACkkI8Sj4ZKn4aPGRAEaMBk5wMADK+LRwuCRQcMgAZnmycKXlYJU1GAZNAObIMIwArl0gnbQkoxNTEliMdAgweQAqcIxQSSRwOe1knZGywxQAiuMQ8G0dU3Li1edwVzctSEcnIACO1-DpFIYHIgfCyNzNOBiEQRVDlcjDADCEFotHwyFBZDIsLOUCGFAAgjAxiQSuMAdtGs07scpgALGC0MgAdTpJHgsgGYDg1Wy7JM7LQGLAsmKIGMkwAkqI1tUwCsYgTRNV0BQad8MClOszyhgMZqDttTLCmp1mID8EM0eqpgNGGaMegsLJ5SQYrDNU0YMySCIYHTkPwAAyRTx-EieC1W9Gfe6RdYlH1+gNIABMkXGnQ2+BKhzjIDgtBKUOhKiG40tcCITDRxOGGPw5IgIAAvi2gA)

```sh
--parser typescript
```

**Input:**

```tsx
type LanFile = import('@/i18n/index.js').LanFile
type ReactiveKonva = import('@/konva-reactive').ReactiveKonva
```

**Output:**

```tsx
type LanFile = import("@/i18n/index.js").LanFile;
type ReactiveKonva = import("@/konva-reactive").ReactiveKonva;

```

**Comment by gyhyfj** [comment]
Sorry, it's one monorepo bug, caused by existing both `3.1.1` and `2.8.0`
