### ISSUE TITLE
Issue with blockquote wrapping when first line is link or link-like text

### ISSUE THREAD

**Issue by queengooborg** [prettier/prettier#15782]
When the first line of a blockquote is `[(anything)]`, if the second line is any type of node except for text, the entire second line is moved up and combined with the first line.

This is especially problematic for [GitHub's new proposed noteblock format](https://github.com/orgs/community/discussions/16925).

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA+ABAbQIQDkDyAKgKIC6AOlBgAYBmEE1lGARgIYBOlzW2A6gEEASrgCSuAOIUqWABJwANgojoA7hA4KAJqQAUAYgAWi5QEoQAGhAQADjACW0AM7JQnDhFUAFTghco2BVU2AE8XKxYONjAAazgYAGU2AFs4ABl7KDhkWkCnOAio2PiEm2jMgHNkGA4AVwKQfOT7arqGp0qFOABFWoh4HLyGgCsnAA8Ezp6+gaRchXyrAEcZuC8PG38QNicAWiy4LUPLEBq2ewVKgGEIZOS2ZG2lE46oCq6BGBr7Flr4LzgHAyWUGCwahhgyQUfEM9ngTjKYDgCT8cPsADc4SFHmAnOEQOj6qIoEdYAkwBx7HYBCSEjAQl1QYsQDYPPk+FEbI9WXB8hx0dkrJk+TB1mwKvcmQ0yhw+Y97hwYlpPFATqzMjA+PYtDBDMgABwABisHDgK3sprFEoecyGVhgbBYWp1eqQACYrLV8oRHf55sy4MkWIcjlo0mw3rVxXAAGIae5fSqPNh-CAgAC+6aAA)

```sh
--parser markdown
```

**Input:**

```markdown
> [!NOTE]
> `foo`
> bar

> [!WARNING]
> [Hello world](#hello)
```

**Output:**

```markdown
> [!NOTE] > `foo`
> bar

> [!WARNING] > [Hello world](#hello)

```

**Expected behavior:** No change; input should be the same.

**Comment by kachkaev** [comment]
👋 @queengooborg! This issue is being tracked in https://github.com/prettier/prettier/issues/9099, let’s continue the discussion there.

**Comment by queengooborg** [comment]
Oops!  Sorry, I forgot to check for an existing issue... 🤦‍♀️

**Comment by kachkaev** [comment]
As a workaround, you can try adding two spaces after `[!NOTE]` and `[!WARNING]`

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA+ABAbQIQDkDyAKgKIC666AOlBgAYBmEEt1GARgIYBO1rW2AdQCCAJVwBJXAHFyVGlgAScADbKI6AO4QuygCakAFAGIAFirUBKEABoQEAA4wAltADOyUNy4QNABW4I7igcyhocAJ7utmxcHGAA1nAwAMocALZwADJOUHDI9CGucNGxCUnJ9nE5AObIMFwArsUgRWlOdY3NcAAe9nBcThmwIYT9UNxOcEEFykW2rjXKcACKDRDw+YXNAFau3cmLK2sbSDNzIACOx3C+3vZBIByuALS5cLrvNiD1HE7KNQBhCBpNIcZCPVRfBZQapLIQwepONgNeC+frZXKbWbNEwwNLKAQmJzwVyVMBwZKBYlOABuxPC4LAriiIBpTXEUA+sGSYAGjiEnOSMHCSyx53s3iKAli9nBEqm-RpeVsOSKXBgtw41VBYualS4avBoK48V0PigXwlORgAicuhgJmQAA4AAy2LhwK5OD2a7Vg05bWwwDhsW32x1IABMtgaRUIIemgZAcDSbHeH10mQ4MIaWrgADFtKCETVwRwURAQABfKtAA)

```sh
--parser markdown
```

**Input:**

```markdown
> [!NOTE]  
> `foo`
> bar

> [!WARNING]  
> [Hello world](#hello)
```

**Output:**

```markdown
> [!NOTE]  
> `foo`
> bar

> [!WARNING]  
> [Hello world](#hello)

```
