### ISSUE TITLE
experimentalTernaries not included in Config typings

### ISSUE THREAD

**Issue by tamird** [prettier/prettier#15791]
See https://github.com/prettier/prettier/blob/23b3ca2f5220eab87612e21cf65c057035407e8d/src/index.d.ts#L318.

**Comment by sosukesuzuki** [comment]
Please see current main branch https://github.com/prettier/prettier/blob/66a23c9331e2c652f8e08fd05a65d2bea7fe5c1a/src/index.d.ts#L427-L432
