### ISSUE TITLE
enable temporarily disabled typescript test again

### ISSUE THREAD

**Issue by despairblue** [prettier/prettier#1579]
https://github.com/prettier/prettier/pull/1578/commits/615a21655bd719620a69891c4b982f9674a32d38 disabled a test for typescript temporarily.

The test fails because `eslint-parser-typescript` was updated, once the regressions are fixed it should be enabled again.

**Comment by vjeux** [comment]
Only one left!

**Comment by vjeux** [comment]
I'm going to close it as you know it's needed :)
