### ISSUE TITLE
Extra ">" inserted into square bracket expressions for Markdown block quotes

### ISSUE THREAD

**Issue by 18kimn** [prettier/prettier#15815]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA+ABAFQBYEsDO6B6AhugI4CuE86M2JM6DAJugNr4QC2c6ADiQBOMQmAZQA5nDZc6DGAB0oGenHx8ARkJJgA1nFGkhfKHBkyAdAF10AIThgSlDUSbEyAG2iSK1eAA0bsoY+IJQhBoAbnA6nuieuGb4lsogASAQ-DC40PjIoMJCEADuAArCCPkoJJ4lJACe+RnaugYwAMokvAAySXDIAGa1Gi06+oYdgmBJksgwQpRwGRrcuPOLyyBwAB78sbi8sLWYsVDCuOpDI1v4s55wAIr+A0jDnqMgAFb4Ox33Txe1w+WyoNDgZWK-GqIBI+AAtGYLCx0iAFiRcIkpABhHjcEjIWGeTyou5SB4AQRgC1wmko8DKsT6ZmBn2wMG4ngA6nh4GFdHAOlVcDkoiKGoSwPhmiAoksAJJQFgITpgIS4bIUpUdGANB6srb8YoaLk6fiE2r1JqopIaESQkiSfEGjKCIR2wn4oR6FilKCoo1JGBc3AsejIAAcAAYMiYqLgTA6nQS3jcMjASJoQ2HsMgAEwZFxwTCZ6rvT5wbiaGTKlg9EhSSiOuAAMQgQnx1NmFvpEBAAF9+0A)

```sh
--parser markdown
--prose-wrap always
```

**Input:**

```markdown
> This is a quote that had [some parts changed so that
> these brackets are needed.] Because it is a long quote, it
> spans several lines.

```

**Output:**

```markdown
> This is a quote that had [some parts changed so that > these brackets are
> needed.] Because it is a long quote, it spans several lines.

```

**Expected behavior:**

An extra ">" is inserted in the output in the first line. 

If the problem is that square brackets should not span multiple lines, then Prettier should leave alone square brackets that are placed on a single line instead of forcing them to wrap. In the below example, Prettier wraps a line to break square brackets, creating the conditions where an extra ">" is inserted into the output upon a subsequent formatting.

As far as I can tell, Prettier breaks spec here, since square brackets are printed as they are when they do not refer to links in the common mark reference implementation, [example here.](https://spec.commonmark.org/dingus/?text=%3E%20This%20is%20a%20quote%20that%20had%20%5Bsome%20parts%20changed%20so%20that%20these%20brackets%20are%0A%3E%20needed.%5D%20Because%20it%20is%20a%20long%20quote%2C%20it%20spans%20several%20lines.%0A)

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA+ABAFQBYEsDO6B6AhugI4CuE86M2JM6DAJugNr4QC2c6ADiQBOMQmAZQA5nDZc6DJvTj4+AIyEkwAazijSQvlDgyZAOgC66AEJwwJSiqJNiZADbRJFavAA0TgDpQGPiCUIQqAG5wGq7orrhG+KaBID4gEPwwuND4yKDCQhAA7gAKwgi5KCSuRSQAnrlp6po6MADKJLwAMglwyABm1SpNGtq6bYJgCZLIMEKUcGkq3Liz84sgcAAe-NG4vLDVmNFQwrjKA0Mb+NOucACK3n1Ig67DIABW+Ftttw9PlzeGyoNDgJUK-EqIBI+AAtEYTCxUiA5iRcPEpABhHjcEjIaGuVzIm5SO4AQRgc1wqko8BK0R6RkB72wMG4rgA6nh4CFNHA2hVcFkIkK6viwPhGiAIgsAJJQFgIdpgIS4TJkhVtGB1O7Mjb8QoqDkafj46q1BrIhIqETgkiSXF6tKCIQ2-G4oRaFjFKDIgxUXAGO0OvEvK5pGAkVQc3AsejIABMaQccEwUcqr3ecG4qhkipYXRIUko9rgADEIEJcZTpmbaRBkQaEjAY3HsMgABwABgAvj2gA)

```sh
--parser markdown
--prose-wrap always
```

**Input:**

```markdown
> This is a quote that had [some parts changed so that these brackets are needed.] Because it is a long quote, it
> spans several lines.

```

**Output:**

```markdown
> This is a quote that had [some parts changed so that these brackets are
> needed.] Because it is a long quote, it spans several lines.

```

**Comment by kachkaev** [comment]
👋 @18kimn! This issue is being tracked in https://github.com/prettier/prettier/issues/9099, let’s continue the discussion there.
