### ISSUE TITLE
Want to ignore css in style sheet

### ISSUE THREAD

**Issue by TechMainul-dev** [prettier/prettier#15837]
When i use  /* prettier-ignore  */ it's working only for one curly brace {}

want to set it for some lines as /* prettier-ignore-start */ /* prettier-ignore-end */

![code](https://github.com/prettier/prettier/assets/72866491/62cd3370-ce4d-4f1e-9ab6-988501d7e9ed)

**Comment by k-utsumi** [comment]
多分これと同じ。
https://github.com/prettier/prettier/issues/5287#issuecomment-1280028576

**Comment by k-utsumi** [comment]
(It was an Issue not a comment. I updated.)

**Comment by kachkaev** [comment]
Closing as duplicate of https://github.com/prettier/prettier/issues/5287
