### ISSUE TITLE
Recombine split JSX lines

### ISSUE THREAD

**Issue by karl** [prettier/prettier#1583]
With https://github.com/prettier/prettier/pull/1120 we now split JSX text across multiple lines when it gets too long to fit on a single line.

It would be nice to investigate whether we could automatically recombine split lines when they can fit on a single line (as mentioned in https://github.com/prettier/prettier/pull/1120#issuecomment-299666090).

For example:

```javascript
const Abc = () => {
  return (
    <div>
      Please state your
      {" "}
      <b>name</b>
      {" "}
      and
      {" "}
      <b>occupation</b>
      {" "}
      for the board of directors.
    </div>
  );
};
```

Would become:

```javascript
const Abc = () => {
  return (
    <div>
      Please state your <b>name</b> and <b>occupation</b> for the board of
      directors.
    </div>
  );
}
```

Doing this would be a major change from our current JSX behaviour where we always retain newlines in the source. I've opened this issue to discuss whether we want to make this change and if so how we would like it to behave.

**Comment by vjeux** [comment]
Just to be clear, my idea was to only recombine lines separated by {' '}, not arbitrary lines.

The reasoning is that in the shipped version of prettier we introduced a worse output by splitting all those up. Now that we know how to inline things, it would be nice to correct this error automatically, without having users have to do it manually.

**Comment by karl** [comment]
(Accidentally pressed the close button!)

**Comment by karl** [comment]
This is now done in https://github.com/prettier/prettier/issues/1831 🎉
