### ISSUE TITLE
Prettier always exits with exit code 1 with no error

### ISSUE THREAD

**Issue by Zethson** [prettier/prettier#15832]
On the repository https://github.com/theislab/ehrapy locally and via CI

**Prettier v4.0.0-alpha.7**

Whenever I run `pre-commit run -a` which runs prettier, I just get:

```
prettier.................................................................Failed
- hook id: prettier
- exit code: 1
```

even in verbose mode

**Comment by Zethson** [comment]
The Github CI just gives

`?25h?25h` and I have NO CLUE what this means

**Comment by csabasari** [comment]
Hi @Zethson , for us locally runs fine without this error if you do `export PRETTIER_LEGACY_CLI=1` , however it is failing in pre-commit.ci (because I was not able to figure out how can I inject ENV variables). If you are using the variable in the workflow - might be a workaround for you.

**Comment by jsoref** [comment]
This appears to have fixed it: https://github.com/theislab/ehrapy/pull/634
