### ISSUE TITLE
Bracket spacing in template literals

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#1584]
It'll be great if `bracketSpacing` option would be respected for template literals.

Currently following input:

```javascript
const { foo } = bar;
const elo = `${ foo }`;
```

Produces following output:

```javascript
const { foo } = bar;
const elo = `${foo}`;
```

Will you accept change that would ensure spacing in template literal brackets?

**Comment by azz** [comment]
I think the default behaviour should be maintained. `bracketSpacing` is defined as:

> Print spaces between brackets in object literals.

I don't think that scope should increase to include template literals, too.

**Comment by medikoo** [comment]
Why it covers only object literals block and not others?

At least I think either there should be fixed setting for all, or if there's any option it should work for all bracket cases. Code formatting doesn't look consistent otherwise.

**Comment by ndresx** [comment]
It should be either a separate option, or remove the spaces as it is doing now. These are 2 different things, hence it wouldn't be good to share the same option.

**Comment by medikoo** [comment]
> These are 2 different things

Sure, I can agree, still what's interesting is why for one there is an option and for other doesn't.

**Comment by vjeux** [comment]
I'm sorry but we're now past 1.0 and are not looking into making big formatting changes to prettier. Bracket spacing also doesn't put space inside of `{}` for jsx, so there is precedent to not put it inside here.
