### ISSUE TITLE
`declare` keyword should be in front  of `public`/`protected`/`private`

### ISSUE THREAD

**Issue by zanminkian** [prettier/prettier#15868]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOAJnGBgE5w4AONAlgG7rw53rnSoCeOKOgC2cJDkwwWUAOYBuEgF8QAGhAQGMZtEzJQ6GjQgB3AAqGEelOlQn0-PeoBGNdGADWcGAGVRcABlmKDhkADNbTDgXN09vHwZ3YNlkaQBXaJAokWZUmgz1OAAPBjgWMVhbABUy4RY4awjUKPVMZNQ4AEU0iHhwyMyAK0win3aunr6kJpaQAEdJuDNjBmsQLABaELhKcjUQaXRmVGSAYQgREXRkddRUfba5DrwYaWZnNPgzMqCQ-ubMgALGAiVAAdUBzHgmESYDgPisULYUP4NzA2H2rAyAEkoJRYD4wCwtHg8T4YPwOv9ZkwIFEwW4GDcmA0yqxQupglEaDBluhZFdqZlEjRuTcKaVMETmFp9kxgjAwcxyDBAcgABwABnUdAWzDofIF12mA3UMHQziVKrVSAATOo0lEqhbGqaQHARM4drsAug5Gl+XAAGIQGhXV7JG7oT4QEBKJRAA)

```sh
--parser typescript
```

**Input:**

```tsx
class A {
  declare private readonly name: string;
}
```

**Output:**

```tsx
class A {
  private declare readonly name: string;
}

```

**Expected behavior:**

```tsx
class A {
  declare private readonly name: string;
}
```

**Comment by sosukesuzuki** [comment]
Is there a rationale for saying "should be"?

**Comment by zanminkian** [comment]
`declare` keyword is the highest statement in ts. Other declare statements put the `declare` keyword in front of any other word. For example,

```ts
declare const a: string;

declare class A {};
```

Field declaration in class shouldn't be the exception. We should keep consistent like other declare statement.
