### ISSUE TITLE
Vue interpolation brackets and content separated on line breaks

### ISSUE THREAD

**Issue by iinuwa** [prettier/prettier#15871]
When using Vue and breaking lines for HTML elements that are whitespace-sensitive, the interpolation brackets are broken into multiple. This breaks syntax highlighting in some editors and is against Vue style guides.

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWW0OnPPX2McddtNenfACM4OMmHwBnaQF5iIAGYQAThgC0YABZwwAaw2jxiskhWqFICFhgA6OnhwBXOIsLBgZG-eMSAvv6oAPR+PEKUwazhfFHc7JxxAhQh0aQhmLgEcIwgADTWtjTQ0sigeKqqEADuAAoVCKUoTtV4AJ6lBSKqeAZwMADKeBhwADI0UHDISk7ScF09fYNYvRMA5sgwqq4Fcxg0m9vzIHAAHlhwqjQjsE4AKpdQFTRwTTM4c7vrOHAAis4QeDTWbHABW0lOA2+fwBQPMIIKAEdYXBalUsE0QHhpBpJnAqPj8iAtngaDh1gBhCAYDB4ZBYnA4InSaEAQRgWxoImc8Fql3Gk2BH2O2hgGBwAHVtDR4NIVmA4ANGjL6DK2vSwLIiXRXABJKAE2ADMBXWysg0DGBtH5Cz4gLBVOYSnpYekO16XOhTAoTOaqGBovBrWm244rVR++k6732q6wCU0KgwbTIAAcAAYCqo4MiaNnA8G6fDhQUYHgRAmkymkAAmArOOZ3ctvBEnDBiKgEqijPBQNbOINwABialpHPW9LwPIgIECQA)

```sh
--parser vue
```

**Input:**

```vue
<template>
  <div>
    <div>
      <div>
        <div>
          <label class="form-check-label" :for="opt.value">{{ opt.label }}</label>
        </div>
      </div>
    </div>
  </div>
</template>

```

**Output:**

```vue
<template>
  <div>
    <div>
      <div>
        <div>
          <label class="form-check-label" :for="opt.value">{{
            opt.label
          }}</label>
        </div>
      </div>
    </div>
  </div>
</template>

```

**Expected behavior:**
In Vue, the entire interpolation, including the braces, should be treated as one element. When a line break needs to occur with an interpolated string, the entire interpolation expression including the braces, should be on the next line. If the element is whitespace-sensitive, then the closing bracket of the element should be moved to the next line.

**Output:**

```vue
<template>
  <div>
    <div>
      <div>
        <div>
          <label class="form-check-label" :for="opt.value"
          >{{ opt.label }}
          </label>
        </div>
      </div>
    </div>
  </div>
</template>

```

**Comment by GervinFung** [comment]
same issue faced

**Comment by fisker** [comment]
>  against Vue style guides.

Reference link?

**Comment by ehoogeveen-medweb** [comment]
Sorry about the churn, I thought this was another ticket.
