### ISSUE TITLE
Doc of paragraph in markdown violates a rule of `fill()`

### ISSUE THREAD

**Issue by seiyab** [prettier/prettier#15877]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABB9AdK6BGB6OeY6ZJuxIANCBAA4wCW0AzsqKgE7cQDuABR4IOKVABt+qAJ4c6+bqjABrODADKqALZwAMsyhxkAM0ls4CpavUaGywwHNkMbgFdLIC9uYv3nuAAPBjhuZl1YSQAVUKgeZjgxMwkLOjYnCTgARTcIeFNzTwArNkCNDOzc-KRk1JAARyq4QT4GMTQ2AFojOAATPtoQV1RmCScAYQhtbVRkNAkJQfSoR0yAQRhXZnw3eEFQgyMClM8ACxhtCQB1U+Z4NnswOA1RO+YANzuZObA2eRB3h4AJJQfqwDRgMJMNagjQwGSZY51Bh8CxXJQMOaSaRyQaGCzcGAtVCOGZIzz2bgEuYzbgqXoCKCDFGGGBXZi9GCnZAADgADHRuHBGswhcTSbMaoU6DBUPh2ZzuUgACx0NwWKJypLSkBwbT4Pr9Xp6VArNwkuAAMQg3BmmycWN2EBAAF8XUA)

```sh
--parser markdown
--tab-width 4
--prose-wrap always
```

**Input:**

```markdown
a a  
 b b  
 c c  

  
```

**Doc:**

```markdown
[
  fill([
    "a",
    line,
    "a  ",
    markAsRoot(literalline),
    line,
    "b",
    line,
    "b  ",
    markAsRoot(literalline),
    line,
    "c",
    line,
    "c",
  ]),
  hardline,
]

```

**Expected behavior:**
The result doc should preserve the following invaliant:
https://github.com/prettier/prettier/blob/bab892242a1f9d8fcae50514b9304bf03f2e25ab/src/document/printer.js#L442-L443

I haven't found user-facing problem yet. I found it investigating https://github.com/prettier/prettier/discussions/15836#discussioncomment-7917975.

**Comment by seiyab** [comment]
Oh it can be reproduced without `--prose-wrap: always`. I changed the issue title.

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABKgOlARu3HMdMEAGhAgAcYBLaAZ2VFQCdWIB3ABTYSZSoANp1QBPJhVytUYANZwYAZVQBbOABlaUOMgBmwhnCkz5ipVVnaA5shisArsZBHVtO4+dwAHlTitadVhhABV-KDZaOAEDISMKBhshOABFBwh4fUNnACsGbyUk1PTMpFj4kABHErhuDioBNAYAWh04ABMO8hB7VFohGwBhCFVVVGQ0ISFuxKhrZIBBGHtaXAd4bn8tHSy45wALGFUhAHV92ngGSzA4JX4L2gA3C7EJsAZJEEenAEkoTtgSjAARoC3+ShgYmSuwqVA4RhOMioEzh0X8j10FG0RlYMDqqGsYxhzksrBxEzGrDk7S4UG6cO0MBOtHaMH2yAAHAAGCisODVWh8-GE8ZlbIUGCoXDM1nspAAFgoDiMISlMXFIDgqlwHU67Q0qDmDgJcAAYhBWGNljYJqh1hAQABfR1AA)

```sh
--parser markdown
--tab-width 4
```

**Input:**

```markdown
a a
b b
c c
```

**Doc:**
```
[
  fill([
    "a a",
    hardlineWithoutBreakParent,
    breakParent,
    "b b",
    hardlineWithoutBreakParent,
    breakParent,
    "c c",
  ]),
  hardline,
]
```

**Comment by seiyab** [comment]
I found I've misunderstood something.

**Comment by seiyab** [comment]
This should be one of the user-facing problems.

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVBDV8AeNtx4FG76nFmGUlUV3kO2NGoA6U6ARvU7zf9UE8Bwoc3xsOqMKNni5fMYoUt26ACYqlI+buV6Rk9HC2mD2i6ckgANCAgAHGAEtoAZ2SgMAJ28QA7gAKPggeKBgANv4YAJ4edpzeGGAA1nAwAMoYALZwADLOUHDIAGaRbnAJSanpGQ7JhQDmyDDeAK6VIBXZzi3tnYQOcN7OubCRACrDUD7OcGFlERV2bk0RcACKbRDwpeWdAFZuOBlrm9u7SIvLIACOF3CBfg5hIBhuALRFcOo-tiCtDDOCJNADCEGy2QwyDeEQi-1WUEa6wAgjBWs5OG14IFhgUinslp0ABYwbIRADqxOc8Dc9TAcAyoRpzgAbjSYjCwG54iBWR0AJJQX6wDJgEZOFHCjIwGLrQk3Bx+CoUpIOGGRaJxf6FCreGBPDCNKEKzr1bx6mFQ7wpdQBKD-JWFGAU5zqGDE5AADgADHZvHB7s4A4bjdCrvs7DAMJxXe7PUgACx2NoVCYxhaRkBwbKcH6-dR5DBItpGuAAMQg3ih6KaGuxEBAAF8m0A)

```sh
--parser markdown
--tab-width 4
--prose-wrap always
```

**Input:**

```markdown
  a text text text text text text text text text text text text text text text text  
  b text text text text text text text text text text text text text text text text  
  c text text text text text text text text text text text text text text text text  
  d text text text text text text text text text text text text text text text text  
  e text text text text text text text text text text text text text text text text  

```

**Output:**

```markdown
a text text text text text text text text text text text text text text text
text  
 b text text text text text text text text text text text text text text text text  

c text text text text text text text text text text text text text text text
text  
 d text text text text text text text text text text text text text text text text  

e text text text text text text text text text text text text text text text
text

```

**Expected behavior:**
Maybe following?

```markdown
a text text text text text text text text text text text text text text text
text  
b text text text text text text text text text text text text text text text
text  
c text text text text text text text text text text text text text text text
text  
d text text text text text text text text text text text text text text text
text  
e text text text text text text text text text text text text text text text
text  
```

**Comment by seiyab** [comment]
`normalizeDoc()` is suspicious.
https://github.com/prettier/prettier/blob/81efe72536d11ee673cca57e3bbc2117198f0f1f/src/document/utils.js#L392-L405
As `cleanDoc()` comment implies, `normalizeDoc()` is dangerous.
https://github.com/prettier/prettier/blob/81efe72536d11ee673cca57e3bbc2117198f0f1f/src/document/utils.js#L353-L359

**Comment by fisker** [comment]
Feel free to kill it, it's known dangerous.

**Comment by seiyab** [comment]
Yeah, I'm trying. It might be hard because Markdown printer seems to rely on this bug.
Fixing Markdown printer, we will be able to erase it🧹.

**Comment by fisker** [comment]
The originallyversion was for markdown, there might be difference with current one. https://github.com/prettier/prettier/pull/8496/files

I also tried to move it back, didn't finish  https://github.com/prettier/prettier/pull/13701
