### ISSUE TITLE
Document when input spacing is preserved?

### ISSUE THREAD

**Issue by shaunlebron** [prettier/prettier#1588]
__edit__: replaced with minimal example

Both of the following examples are unchanged by Prettier despite having same code:

```js
const foo = {
  bar: 1
};
```

```js
const foo = { bar: 1 };
```

It was my impression that newlines were thrown away in the input, but that doesn't seem to be the case here.  Is this intended?

**Comment by k15a** [comment]
Prettier keeps multiline objects on multiple lines. That's the reason why the first one is in a multiline mode and the second one isn't.

**Comment by shaunlebron** [comment]
Thanks!  Is it worth qualifying the following documentation

> Prettier bans all custom styling by parsing it away and re-printing the parsed AST...

with:

> Some spacing preferences are preserved (e.g. empty line padding and multiline objects).

**Comment by k15a** [comment]
As far as I know they want to get rid of the behaviour as well but there are many use cases of objects in JavaScript which you have to consider and so it's easier to have the current behaviour for now.

**Comment by shaunlebron** [comment]
Good to know!  I'll leave this open for a day in case someone wants to add more context.

**Comment by vjeux** [comment]
Hey, sorry about this, we need to make the documentation better around this. We started as printing everything directly from the ast but this turned out to be impractical in a few places. Objects is one of them. We couldn't find a good heuristic for when to keep them expanded or not, so we ended up maintaining it expanded if it already was.

This is the kind of trade-offs that makes the project actually be usable in practice, even if it's not exactly the ideal vision :)

**Comment by shaunlebron** [comment]
Thanks for extra context!  Makes sense, it's always about trade-offs.

I can submit a PR with my suggested amendment, otherwise I'll leave the issue open here for wording or correctness.

**Comment by vjeux** [comment]
A PR would be nice thanks!

**Comment by shaunlebron** [comment]
Love to!  I drafted a line for the readme below, but I'm really not sure how to word the object rule without understanding the use-case for when it is helpful.  ideas?

> For practical reasons, some styling preferences of the input text are currently in use to decide where to place empty lines, and to prevent multi-line objects from being collapsed to a single line.

**Comment by shaunlebron** [comment]
This example was the use-case I was looking for: https://github.com/prettier/prettier/issues/74#issue-199965534

And found the discussion on the actual change here: https://github.com/prettier/prettier/pull/495

> I think that in order to succeed we need a middle ground. Where most of the code is automatically formatted but the user still has some control for cases where it cannot be always be automatically formatted in a reasonable way. We've done this successfully so far for empty lines, and objects may be a place where this would work as well.

Found it interesting that elm-format set a precedent of allowing flexibility in this way by giving up some consistency, in contrast to something like refmt.  will start the PR soon, and close here when done.

**Comment by medikoo** [comment]
> We started as printing everything directly from the ast but this turned out to be impractical in a few places. Objects is one of them. We couldn't find a good heuristic for when to keep them expanded or not, so we ended up maintaining it expanded if it already was.

@vjeux wouldn't following heuristic work well for all cases:

In object block or an array, maintain same kind of formatting among items, so if one expands multi-line, force all to be multi-line, if none expands multi-line, force all to be one line. Some examples:

_Input 1:_
```javascript
const myList = [
  {
    id: 0,
    name: 'Short',
  },
  {
    id: 1,
    name: 'Short Too',
  },
  {
    id: 3,
    name: 'Too Long For Your Line Width',
  },
];
```

_Proposed output:_
```javascript
const myList = [
  {
    id: 0,
    name: 'Short',
  },
  {
    id: 1,
    name: 'Short Too',
  },
  {
    id: 3,
    name: 'Too Long For Your Line Width',
  },
];
```

_Input 2:_
```javascript
const myList = [
  {
    id: 0,
    name: 'Short',
  },
  {
    id: 1,
    name: 'Short Too',
  },
  {
    id: 3,
    name: 'Short Too #2',
  },
];
```

_Proposed output:_
```javascript
const myList = [
  { id: 0, name: 'Short', },
  { id: 1, name: 'Short Too', },
  { id: 3, name: 'Short Too #2', },
];
```
---

If there are cases when for short output we still want to provide a possibility to force multi-line output, then we can do as follows: If there's at least one multi-line, print all multi-line, so:

_Input 3:_
```javascript
const myList = [
  {
    id: 0,
    name: 'Short',
  },
  { id: 1, name: 'Short Too', },
  { id: 3, name: 'Short Too #2', },
];
```

_Proposed output:_
```javascript
const myList = [
  {
    id: 0,
    name: 'Short',
  },
  {
    id: 1,
    name: 'Short Too',
  },
  {
    id: 3,
    name: 'Short Too #2',
  },
];
```

_Input 4:_
```javascript
const myList = [
  { id: 0, name: 'Short', },
  { id: 1, name: 'Short Too', },
  { id: 3, name: 'Short Too #2', },
];
```

_Proposed output:_
```javascript
const myList = [
  { id: 0, name: 'Short', },
  { id: 1, name: 'Short Too', },
  { id: 3, name: 'Short Too #2', },
];
```

However I think it would be cleaner to just stick what's porposed with _1_ and _2_ examples.

**Comment by k15a** [comment]
@medikoo Your input 2 and input 3 are conflicting because if you format input 3 two times you will have the output 3 :)

**Comment by medikoo** [comment]
> @medikoo Your input 2 and input 3 are conflicting

@k15a  input _3_ and _4_ is proposed as an alternative (not complement) to _1_ and _2_ :) (I personally favor _1_ and _2_ version).

**Comment by k15a** [comment]
Sorry my bad. :)

**Comment by shaunlebron** [comment]
@medikoo might want to create an issue for the proposal so it's not lost in this discussion about how to document current behavior.

**Comment by shaunlebron** [comment]
fixed! https://github.com/prettier/prettier/pull/1620
