### ISSUE TITLE
plugins overrides the default one won't work without specific `--plugin x`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#15884]
**Environments:**

- Prettier Version: 3.1.1
- Running Prettier via:  CLI
- Runtime:  Node.js v20.10.0
- Operating System:  macOS
- Prettier plugins (if any):  `prettier-plugin-pkg`

**Steps to reproduce:**

```sh
yarn add prettier @1stg/prettier-config
```

```jsonc
// .prettierrc
"@1stg/prettier-config" // `prettier-plugin-pkg` is enabled inside
```

```sh
yarn prettier --write package.json
```

**Expected behavior:**

Order properties

**Actual behavior:**

No changes.

While the following will work

```sh
yarn prettier --plugin prettier-plugin-pkg --write package.json
```

**Comment by fisker** [comment]
Is there an existing repo I can debug?

**Comment by fisker** [comment]
Can't reproduce,

https://stackblitz.com/edit/stackblitz-starters-jmqyrz?file=package.json

```
❯ cat package.json
{
  "private": true,
  "scripts": {
    "test": "prettier --plugin prettier-plugin-pkg package.json"
  },
  "name": "node-starter",
  "dependencies": {
    "@1stg/prettier-config": "^4.0.0",
    "prettier": "^3.1.1"
  }
}

❯ yarn prettier --plugin prettier-plugin-pkg package.json
yarn run v1.22.19
$ /home/projects/stackblitz-starters-jmqyrz/node_modules/.bin/prettier --plugin prettier-plugin-pkg package.json
{
  "name": "node-starter",
  "private": true,
  "scripts": {
    "test": "prettier --plugin prettier-plugin-pkg package.json"
  },
  "dependencies": {
    "@1stg/prettier-config": "^4.0.0",
    "prettier": "^3.1.1"
  }
}
✨  Done in 1.45s.
```

**Comment by JounQin** [comment]
@fisker Can wr swap the dependencies order? `prettier-plugin-pkg` will resort them back correctly.

**Comment by fisker** [comment]
Your config file didn't load plugin correctly,

https://unpkg.com/browse/@1stg/prettier-config@4.0.0/base.js

Line 21, 

> Object.keys(require('./package.json').dependencies).map(pkg => import(pkg))

```js
Object.keys(require('./package.json').dependencies).map(async packageName => {
   const pkg = await import(packageName);
  return pkg.default ?? pkg;
})
```

**Comment by JounQin** [comment]
Ah, I'm so sorry for this.

**Comment by fisker** [comment]
Better change those plugins to named export, if it's your own package. Core plugins use named export  https://github.com/prettier/prettier/blob/main/src/plugins/babel.js.

**Comment by JounQin** [comment]
Thanks for your advice!
