### ISSUE TITLE
Treat .nvmrc as INI or YAML by default (without overrides)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [prettier/prettier#15898]
**Environments:**

- Prettier Version: 3.1.1
- Running Prettier via: CLI
- Runtime: Node.js 20
- Operating System: macOS
- Prettier plugins (if any): n/a

**Steps to reproduce:**

In an empty directory:

```
printf "20.10.0\n" > .nvmrc
npx -y prettier .nvmrc
```

**Expected behavior:**

Per https://github.com/nvm-sh/nvm/tree/6c9cd2f2d1779b91c0ab7ab0b243c0c55f25a8a5#nvmrc, `.nvmrc` is meant to contain a single string. It's essentially a YAML file. I would expect that running Prettier on it would default it to YAML and remove any trailing newlines/spaces.

#10920 -> #10924 added an explicit allowlist entry for `.stylelintrc`. I'm requesting permission to send a similar PR for `.nvmrc`. 🙂 

**Actual behavior:**

```plaintext
[error] No parser could be inferred for file "/Users/josh/repos/create-typescript-app/.nvmrc".
```

**Comment by fisker** [comment]
Isn't it INI?

**Comment by fisker** [comment]
Maybe it's plain text?

**Comment by fisker** [comment]
Maybe this will work for your use case?

```js
		overrides: [
				{
					files: ".*rc",
					excludeFiles: ['.nvmrc'],
					options: { parser: "json" },
				},
		]
```

**Comment by JoshuaKGoldberg** [comment]
> Isn't it INI?

Oh, maybe. I forgot that file format existed. There isn't really a difference to me as end-user though. I just want the file to be formatted by Prettier without any configuration on my end.

> Maybe this will work for your use case? ... `overrides`

That also gives a _No parser_ error:

```plaintext
[error] No parser could be inferred for file "/Users/josh/repos/create-typescript-app/.nvmrc".
```

What I have that works is:

```json
overrides: [
  {
    files: ".nvmrc",
    options: { parser: "yaml" },
  },
];
```

I.e. what I'd love to see is Prettier have _some_ default language for the `.nvmrc` file. Whatever that language is -ini, yml, etc- doesn't matter so much - so long as I don't have to use `overrides`.

**Comment by fisker** [comment]
> That also gives a No parser error:

Stop using `prettier "**/*"`, use `prettier .` instead. Mentioned in [v3.1 changelog](https://prettier.io/blog/2023/11/13/3.1.0#process-files-only-supported-by-plugins-15433httpsgithubcomprettierprettierpull15433-by-sosukesuzukihttpsgithubcomsosukesuzuki).

**Comment by JoshuaKGoldberg** [comment]
> Stop using `prettier "**/*"`, use `prettier .` instead. Mentioned in [v3.1 changelog](https://prettier.io/blog/2023/11/13/3.1.0#process-files-only-supported-by-plugins-15433httpsgithubcomprettierprettierpull15433-by-sosukesuzukihttpsgithubcomsosukesuzuki).

Ah great thanks! Filed an issue & will do. ❤️ 

Just confirming - that's separate from this suggested issue, right?

**Comment by fisker** [comment]
according to this https://github.com/nvm-sh/nvm/issues/995, I think It's just plain text, we don't have a formatter for it.

**Comment by JoshuaKGoldberg** [comment]
Come to think of it, there are several common files like this kind of >=1 plaintext lines + maybe some `#` comments format:

* [`.eslintignore`](https://eslint.org/docs/latest/use/configure/ignore#the-eslintignore-file)
* [`.gitignore`](https://git-scm.com/docs/gitignore)
* [`.markdownlintignore`](https://github.com/igorshubovych/markdownlint-cli#ignoring-files)
* [`.nvmrc`](https://github.com/nvm-sh/nvm?tab=readme-ov-file#nvmrc)
* [`.prettierignore`](https://prettier.io/docs/en/ignore.html)

Perhaps there should be a new parser defined?

**Comment by fisker** [comment]
Try implement/find  a plugin, I suggest.

**Comment by fisker** [comment]
We don't have builtin parsers for those files, so I'm going to close this.
