### ISSUE TITLE
Documentation Webpage Not Opening

### ISSUE THREAD

**Issue by drakejoshua** [prettier/prettier#15893]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

# The documentation webpage has not been loading for a while ... please check that out

**Comment by fisker** [comment]
It works as I checked, maybe some issue with your network connection.

**Comment by drakejoshua** [comment]
yeah actually
