### ISSUE TITLE
Object literals in Angular templates are missing trailing commas

### ISSUE THREAD

**Issue by matmeylan** [prettier/prettier#15897]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEBAVFAOYCSAZgLy4jD5FEDOADgIZiblIHtceZACQEAPgQ4sAnlDAAaJswCuLOACc+qjaIlTZCpQF9JLAmBgAPekoDa5AMIAbKSwC6dBkqIByNpYBaJzIfPgtLADoBbnICGhoCH2CfRUJmP0CAW3RQ8ysozhiyOISfbJTvRP8AyxZc8ILBWPjE2oq0oxsoAD4lAAlMAgAFdTgYGEwNAgBCfFQAeixsbpB5EAg2CegWZFAOdXUIAHch-YQdlA4nI45pHbWAI3UuAGsxgGUOTLgAGR44ZBUK5qR7PMBvGDvQpCZAwdTKOBrNSZTCw+GIkBwSxsDSYb6wK4AFQ0UH2kwuQKcIJALCETjgAEVlBB4IDgRiAFYsSzvOmM5mspCU6kARwFcBGGwuICkASgcDg6EVqxAcI4mCcQgcEEymQ4yBlTicKtp5HpAEFxupMA9lPAhho-vK2VSMQALGCZJwAdTdmHg0Tg73O-pw-ukBrALHuIGwCIoUCVsHeYGtm3NifeMGk9Jd1LYhzU3uebANBbganU2ABax4lZgIw4ZD1eYxnHUlYNHHIyhc6hVBZ4MG9mHQMDdyAAjAAmAAMa1GYswo0bzf1QvZaxgHAeI7HE6Q07W2kJO4pm8xmQeiqV6B+3bIyibcAAYhB1HrxjDLnaICAjEYQA)

```sh
--parser angular
--trailing-comma all
```

**Input:**

```html
<div
  *ngIf="{
    spacing: spacing$ | async,
    user: user$ | async,
  } as ctx"
  [ngClass]="{
    'px-lg': ctx.spacing == 'lg',
    'px-md': ctx.spacing == 'md',
    'px-xs': ctx.spacing == 'xs',
  }"
>
  Hi Prettier !
</div>
```

**Output:**

```html
<div
  *ngIf="{
    spacing: spacing$ | async,
    user: user$ | async
  } as ctx"
  [ngClass]="{
    'px-lg': ctx.spacing == 'lg',
    'px-md': ctx.spacing == 'md',
    'px-xs': ctx.spacing == 'xs'
  }"
>
  Hi Prettier !
</div>

```

**Expected behavior:**
Trailing commas should be kept/inserted in object literals. This used to work on 2.8.

```html
<div
  *ngIf="{
    spacing: spacing$ | async,
    user: user$ | async,
  } as ctx"
  [ngClass]="{
    'px-lg': ctx.spacing == 'lg',
    'px-md': ctx.spacing == 'md',
    'px-xs': ctx.spacing == 'xs',
  }"
>
  Hi Prettier !
</div>

```

**Comment by fisker** [comment]
It's indented to not support `trailingComma`, https://github.com/prettier/prettier/blob/b4ed91bffb0a9140259f4190b77cce1b77284ca0/src/language-html/embed/angular-attributes.js#L23

But maybe it's supportted now?

**Comment by fisker** [comment]
Ah, supported since May, 2023.  https://github.com/angular/angular/pull/49535

**Comment by fisker** [comment]
It seems still not supported in call arguments.

**Prettier 3.2.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEBAVFAOYCSAZgLy7gCGANkwBREMCU9+AfPqgD0WbLxAAaEBAAOMTNADOyUAwBOqiAHcACmoRKUzTQwCeSyQCNVDMAGs4MAMoMAtnAAymKHGRVmCuEtrOwdHaRsvMmQYVQBXQJAAl0xouIS4AA9pOFVMN1hmABUcqDVMOAM-JgDJBUimOABFWIh4X38EgCsFDMd6ppa2pCqakABHQbhtDWkDEAYFAFpvOHRViRAYhkwmSIBhCBcXBmR5lg268gaAQRgYzAtY+G0cz2926oSACxgXJgB1L6YeAKcJgOCOfTAnDAkynMAKcwgbDxChQNawRxgXKya7oxwwEwND6jaQaAL-azSU5kio5bA+SReAKqGDTBhkY4khLhVQs04McixJhqDZkrwwf6YdAwL7IACMACYAAySVRwCaYdXszknYYdSQwBgWKUyuVIRWSWIBQrGyoGkBwFwWVZrdDuQVkWIcuAAMQgqmOd0iAqeEBAAF8I0A)

```sh
--parser angular
--print-width 120
```

**Input:**

```html
<div
  *ngIf="call(  a)"
>
</div>
```

**Output:**

```html
<div *ngIf="call(a)"></div>

```

**Prettier 3.2.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEBAVFAOYCSAZgLy7gCGANkwBREMA0AlPfgHz5UAeizZ+ITiAgAHGJmgBnZKAYAnNRADuABXUJlKZloYBPZVIBGahmADWcGAGUGAWzgAZTFDjIqzRTgrG3tHJxlbbzJkGDUAVyCQQNdMGPjEuAAPGTg1THdYZgAVXKh1TDhDfyZAqUUopjgARTiIeD8AxIArRUynBubW9qRq2pAARyG4HU0ZQxAGRQBaHzh0NckQWIZMJiiAYQhXVwZkBZZN+vJGgEEYWMxLOPgdXK8fDprEgAsYVyYAOrfTDwRQRMBwJwGEE4EGmM5gRQWEDYBIUKDrWBOMB5OQ3DFOGCmRqfMYyTSBAE2GRncmVXLYXxSbyBNQwGYMMgnUmJCJqVlnBjkOJMdSbcneGAAzDoGDfZAARgATAAGKRqOCTTAajlc04jTpSGAMSzS2XypBKqRxQJFE1VQ0gOCuSxrdboDxCshxTlwABiEDUJ3uUUFzwgIAAvpGgA)

```sh
--parser angular
--print-width 120
```

**Input:**

```html
<div
  *ngIf="call(  a,)"
>
</div>
```

**Output:**

```html
SyntaxError: Unexpected token )
```
