### ISSUE TITLE
Request: Dockerfile support

### ISSUE THREAD

**Issue by mcandre** [prettier/prettier#15907]
Prettier appears well positioned as an extensible formatting system. I would like to see prettier add support for formatting Dockerfile's. Unfortunately, the available Dockerfile formatters online are not as high quality as other formatters. So there's a market gap there.

Additionally, I'd like to see the embedded `RUN` shell commands go through something similar to `shfmt`, so that the overall Dockerfile matches formatting for other shell related projects.

**Comment by kachkaev** [comment]
👋 @mcandre! If you want to format `Dockerfile`s, you can use this community plugin: [`prettier-plugin-sh`](https://www.npmjs.com/package/prettier-plugin-sh). I am using it in my projects and it works quite well, but don’t read this as an official endorsement 😄
