### ISSUE TITLE
quote formated to online line

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier#15908]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA+ABAbQIQDkDyAKgKIC6AOlBgAZwDOANgJazXpN3oAOccATgBE4PKABMEYJvQA06ALYBDANZx0dAK59VATwjr0ACwWj0ChluPb2UOjDMM4J2oxYxqIaSAhcYTaHWRQBT4+CAB3AAVghACUMzCFbQDPACM+BTAVGABlBTk4ABkWOGQAMzM6OFT0zLgcrgyWAHNkGD51KpBKuSZW9s64AA8ePiZ82DNCfihgqVjyhkrPOmaHAEV1CHgyis6AKzpB7NW4Da2SpAWlkABHTfgI0K5YkAU6AFooXnFRDxA2hRMZhQJoAYQgckUyFeDAYfxWIIcAEEYG0mCl1A9+EUvjtFp0DDA5AwAOoGJjwOgNMBwbIxClMABuFO00LAdGSIEZHQAkmIEDkwKMfEixNkYNoHHjrlxQpUSekuNDZfR+IySp4WJU+DBHgomlDLrtPA0+NroYo+EpROEoH9Za4SUxRDADMgABwABk8WjuTC0eoNCmlnTsKSdLrdSAATJ51JVCAoUvNjSA4HIUo4fgUFCD1Pq4AAxCB8RSo5rQhSYiAgAC+taAA)

```sh
--parser markdown
```

**Input:**

```markdown
> [!NOTE]
> `eslint` is peerDependencies, make sure you had already installed `eslint`
```

**Output:**

```markdown
> [!NOTE] > `eslint` is peerDependencies, make sure you had already installed `eslint`

```

**Expected behavior:**

**Comment by kachkaev** [comment]
👋 @tjx666! This issue is tracked in https://github.com/prettier/prettier/issues/13953, let’s continue the discussion there.
