### ISSUE TITLE
Babel plugin `importAttributes` can't be enabled and formatting fails

### ISSUE THREAD

**Issue by hdodov** [prettier/prettier#15911]
I'm trying to format a TypeScript file called *index.ts* with the following line inside:

```ts
import content from "./content.json" assert { type: "json" }; 
```

…but I get the following error:

> [error] src/index.ts: SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "importAttributes", "importAssertions". (3:37)

I tried adding a *babel.config.json* file containing the following:

```json
{
	"plugins": ["importAttributes"],
	"parserOpts": {
		"plugins": ["importAttributes"]
	}
}
```

…but it didn't work.

I also tried installing [@babel/plugin-syntax-import-assertions](https://www.npmjs.com/package/@babel/plugin-syntax-import-assertions) and putting it in *babel.config.json*, *.babelrc*, ***.prettierrc.json* as well**, etc, but nothing seems to enable the plugin.

**Environments:**

- Prettier Version: 3.1.1, @babel/parser 7.23.6 (from *package-lock.json*)
- Running Prettier via: `npx prettier --write .`
- Runtime: Node v20.9.0, npm 10.1.0
- Operating System: macOS Ventura 13.6.3
- Prettier plugins (if any): @trivago/prettier-plugin-sort-imports (don't think it's relevant)

**Steps to reproduce:**

Try to format the aforementioned line with Prettier 3.1.1 and you'll see an error.

**Comment by sosukesuzuki** [comment]
The version of @babel/parser and plugins you have installed has no effect on Prettier's output. Also import attributes syntax has been supported by Prettier 3.1.1. Can you reproduce on playground?

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAklgQIDMcJ18AdEAOgHoj5Y6ArAZ2lvwEMOOcPPmD4YAT0xwkNEJ24h8AXwDc+EABoQETDFTQOyULxwUA7gAUTCQyl4AbM73GGtAIxy8wAazgwAyrzocAAyqFBwyKQOgu6ePn7+mF7hAObIMDgArnBaguioGdm5IHAAHlI4GCQOACpCUCaocLbR9rEgHGn2cACKWRDwUTElnGX+3X0DQ0htHQCO03AWFJi2IPwAtBFwACZ7miCZvKj2aQDClOi8yBv29oddUKk9AIIwmahuWfAWQmERYbtEoACxg6HsAHUQah4BxkmA4P4bLDUAA3WHiW5gASHNE5ACSUH2sH8YCqulexP8Eh6QI6mAogkhnkwt0ZLSEaMiWnCgjwK14qWu9JKyRw-NuEikHHJqF0h0Z4RgkNQuxgIOQAA4AAxaHBwRaoA2C4U3WYjLQwXhuVXqzVIABMWiyglqNtaltK6Dce32uxCvGeWSFcAAYrhrh80rdeD8ICAlEogA)

```sh
--parser typescript
```

**Input:**

```tsx
import content from "./content.json" assert { type: "json" }; 
```

**Output:**

```tsx
import content from "./content.json" assert { type: "json" };

```

**Comment by hdodov** [comment]
@sosukesuzuki I've made a reproduction repo: https://github.com/hdodov/mcve-prettier-import-attributes

It appears that somehow [@trivago/prettier-plugin-sort-imports](https://www.npmjs.com/package/@trivago/prettier-plugin-sort-imports) is causing the issue. If I remove it from *.prettierrc.json* in the reproduction repo, everything works. Maybe the error message generated by Prettier is misleading? I can see that @fisker's PR is related to something like that.

**Comment by fisker** [comment]
#15928 is hiding this error message, since we don't read the babel config.

**Comment by fisker** [comment]
Maybe caused by [this line](https://github.com/trivago/prettier-plugin-sort-imports/blob/61d069711008c530f5a41ca4e254781abc5de358/src/preprocessors/preprocessor.ts#L26), can you open an issue there?

**Comment by lukeapage** [comment]
FYI I found this issue first and fixed it for the plugin with this:

```
importOrderParserPlugins: ['importAssertions'],
```
