### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by epmatsw** [prettier/prettier#15912]
**Prettier 3.2.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMAUBKAOlXGAOnRgCYd9CS4MKYALASygHMB+ItCAWzkZatsAbnwgANCAgAHGE2hpkoAIYAnVRADuABTUJFKZQBtNygJ6LJAI1XKwAa34BlZXwAyLOMgBmxtHGtbB2dpO0FkGFUAVwCQfx4mCOjYuAAPaThVJj5YYwAVTKg1JlofP1i0QSM4AEUoiHgyo39JACs0VKcq2vrGpF9m2IBHXrhtDWkDEGU0AFooODgAE2WJVFsmI0EAYV4eZWRpoyM1yrZqgEEYSKYrKPhtTI8FppaQBhgeIwB1ZnRQsBwJz6JhyABuoLMhzAaEsIDBMQAklAVrAnGAsrILiinDAzNVXrFpBp-N9bNJDsTaJkwV5JCx-KoYONlKx9oTJKFVIzDniMmgMUxZGtiSwYN8mEtGMgABwABkkqjgIyYSpZbIO-XKkhgyisEqlDGQZEkUX8eT1BgGbzgPCsyxWSzcyjYUVZcAAYhBVPtruFDPcICAAL7BoA)

```sh
--parser typescript
```

**Input:**

```tsx
test()
	.test2()
	.test2(thing?.something);

```

**Output:**

```tsx
TypeError: Cannot read properties of undefined (reading 'type')
    at Jn (https://prettier.io/lib/plugins/estree.js:7:16595)
    at be (https://prettier.io/lib/plugins/estree.js:9:605)
    at be (https://prettier.io/lib/plugins/estree.js:10:289)
    at https://prettier.io/lib/plugins/estree.js:36:14282
    at Array.every (<anonymous>)
    at https://prettier.io/lib/plugins/estree.js:36:14273
    at Array.some (<anonymous>)
    at Oi (https://prettier.io/lib/plugins/estree.js:36:14252)
    at Kr (https://prettier.io/lib/plugins/estree.js:36:14852)
    at Ta (https://prettier.io/lib/plugins/estree.js:36:58423)
```

**Expected output:**

Not exactly sure, it's an error.

**Why?**

This was not an error in 3.1.x.

**Comment by sosukesuzuki** [comment]
Thank you! I'll look into this

**Comment by sosukesuzuki** [comment]
Fixed https://github.com/prettier/prettier/releases/tag/3.2.1
