### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by Mozartuss** [prettier/prettier#15916]
**Prettier 3.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdrJQM41QJwEMoATCAWwDEBXKMAS2lQF5UAKAN0IBtq4BKJKg4R6JFgD5UwADpQMC1PQBm7LrzgA6Qv2lzFB1MtpgAgm32GrMkDYA0lqweN0AQhflOvJQgE8AVticPHzaAPyaMBAAyjD49FAA5mz8-I5eijIwWdokJGwAjHaoNj6+NmmeGZnZMJEQAJLRAPKx8Ukp6dWV3QDcXRgAvumD-VAgdiAQAA4wjDjIoIT4+BAA7gAKywjYyCA8a367kwBGRGAA1nAw0YTkcAAyCXDIyjzYcKfnVzfThAxJZBxPiTD7kehA-AgkBwAAe0zg8XusB4ABVEVBlvQ4LskG9uB9QQlEtw4ABFagQeCvd6fECBWHRYmkilUl542mTACOlPgG1W01x+2wAFooHA4CRJRMQHFCPRuMSAMIUciEPY8bgy7DMuCmGBxegnah8xFPcU0gl0gAWMHI3AA6tb6PBsH8wHBojsXfQOC7fHswNhjiAOHwGqQEDcwPFZqZSLFfKTLYSQNNVh8HURpnt0zjERwXpMEh98DB+YREmqU3S-vhS3sYL4EdgY-RZjL0wkYA6xDBrcgABwABkm+DgPPo44rVfVHKtkxghBOvZI-eQACZJtQPqjl7j8am4OQTpKpSQHsREtRK3BKBB8GqDcSNSaICBBoMgA)

```sh
--parser typescript
```

**Input:**

```tsx
    const randomFuncion = (value): void => {
        if (value.a) {
            funcA(
                "",
                funcB(
                    dayjs(value.a?.toString())
                  		.add(1, "day")
                  		.toISOString()
                )
            );
        }
    };

```

**Output:**

```tsx
TypeError: Cannot read properties of undefined (reading 'type')
    at Jn (https://prettier.io/lib/plugins/estree.js:7:16595)
    at be (https://prettier.io/lib/plugins/estree.js:9:605)
    at be (https://prettier.io/lib/plugins/estree.js:10:209)
    at https://prettier.io/lib/plugins/estree.js:36:14282
    at Array.every (<anonymous>)
    at https://prettier.io/lib/plugins/estree.js:36:14273
    at Array.some (<anonymous>)
    at Oi (https://prettier.io/lib/plugins/estree.js:36:14252)
    at Kr (https://prettier.io/lib/plugins/estree.js:36:14852)
    at da (https://prettier.io/lib/plugins/estree.js:36:58423)
```

**Expected output:**

```tsx
const randomFuncion = (value): void => {
  if (value.a) {
    funcA(
      "", 
      funcB(dayjs(value.a?.toString())
        .add(1, "day")
        .toISOString()
      )
    );
  }
};
```

**Why?**
That was not an Error in 3.1.1 here the error in version 3.2.0 which should be fixed in #15912

If I remove the question mark behind the `funcB(dayjs(value.a? ...` the error is gone.

**Comment by surgeboris** [comment]
I'm getting the same error with `prettier@3.2.0` in my project, here is the minimal reproduction example :

```js
  a(() => {}, c?.d);
```
The workaround is to introduce an additional variable:
```js
const b = c?.d;
a(() => {}, b);
```
