### ISSUE TITLE
print dependency versions, maybe whole config

### ISSUE THREAD

**Issue by xenoterracide** [prettier/prettier#15936]
I think it would be useful for anyone reporting bugs either to prettier, or a prettier plugin to be able output a list of dependencies, and possibly the resolved prettier configuration.

**Prettier 3.2.2**

**Why?**

So this is kind of annoying, this is the simplest thing I can think that would possibly work to give all potentially relevant information, and I'm not certain it does. Obviously it generates some output that a human then needs to parse and provide better formatting to report. 

I think prettier could probably add an option or two that gave all this and maybe included an option like `--markdown` which formatted nicely for bug trackers

```
❯ node --version && npm list | grep prettier && cat .editorconfig .prettierrc.yml
v20.9.0
├── @prettier/plugin-xml@3.2.2
├── prettier-plugin-java@2.5.0
├── prettier-plugin-properties@0.3.0
├── prettier-plugin-sh@0.13.1
├── prettier-plugin-toml@2.0.1
└── prettier@3.2.2
root = true

[*]
trim_trailing_whitespace = true
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 4
max_line_length = 120

[*.bat]
end_of_line = crlf

[*.{yml,yaml,json}]
indent_size = 2
plugins:
  - prettier-plugin-java
  - prettier-plugin-properties
  - prettier-plugin-sh
  - prettier-plugin-toml
  - "@prettier/plugin-xml"
```

maybe the command could be `prettier --version --resolved-config --markdown` (or similar), or maybe `prettier --bug-info --format-as=markdown`. 

Just a thought. This is not super critical to me.

**Comment by kachkaev** [comment]
We encourage Prettier users to report bugs via Playground: https://prettier.io/playground/. This helps reproduce all formatting bugs in the latest available version. If an issue is with a plugin, it needs to be reported outside of this repo, probably as a reproduction repo.

I am not sure that a new CLI argument like `--bug-info` can help in the sufficient number of cases. Can you please provide a specific example where it was needed? It’s important that we address real problems, not some hypothetical ones.

If we conclude that printing debug info is useful, we should probably implement it as a separate tool. Perhaps, something like `npx prettier-debug-info-whatever@latest --format=markdown`. Including this feature into the core will make Prettier bulkier and increase the surface of potential bugs.

**Comment by xenoterracide** [comment]
the biggest advantage I see of it though is that there are a lot of bugs here that probably ask for the same information and there's a lot of bugs on third-party plugins that probably want to know it too. So it seems like it would be nice to be able to write a one-liner that doesn't require me to think too much and probably aligns information like the merging of editor config and prettier RC... Basically I hate having to figure out commands like this. So I thought I'd suggest it. I don't necessarily have problems with an external thing although I feel like it might be good for it to have official support (on that note maybe it's questionable all the languages that have first party support but aren't plugins... At what point should everything be a plug-in?)
