### ISSUE TITLE
Freeze all option defaults

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#15938]
via https://github.com/prettier/prettier/issues/7475#issuecomment-1892908725

So that we do need to talk about changing them anymore at all.

@sosukesuzuki

https://github.com/prettier/prettier/issues/7475#issuecomment-1426618841

@fisker

https://github.com/prettier/prettier/issues/7475#issuecomment-1205440604

Question:

> Prettier has already had several breaking formatting changes, including more controversial than popular ones like arrowParens: "always". How is this relevant?

My answer:

> So we learned we maybe should not make such controversial changes at all, the option defaults should be frozen. And that one doesn't break edit experience after changed, the diff is much smaller than this one.

**Comment by ljharb** [comment]
Default are important enough that they should never be frozen permanently.

**Comment by JounQin** [comment]
@ljharb You're coercing the whole community sticking on Node v4 and commonjs, I don't think you have the position to clarify that statement.

**Comment by ljharb** [comment]
I'm not coercing anyone; platform support has nothing to do with defaults; if one applied your logic, then nobody without disabilities is allowed to comment on accessibility, which would remove a lot of your comments from the linked issue - so I don't think you want to go down that road.

**Comment by fisker** [comment]
I don't think freeze default value is a good idea.
