### ISSUE TITLE
Prettier 3.2.3 incorrectly formats `.estlintrc.json`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#15945]
I'll check how it's loaded.

**Comment by fisker** [comment]
Confirmed, we should not treat it as jsonc.
 https://github.com/eslint/eslintrc/blob/a61384731aff386a8260a80d9710c912e4f62aaa/lib/config-array-factory.js#L188-L203

**Comment by fisker** [comment]
Before we work on it, let's double check and make sure [these files](https://github.com/prettier/prettier/blob/6c6a332171f590a38c369673662d1a5baf765167/tests/integration/__tests__/__snapshots__/support-info.js.snap#L524-L538) are valid jsonc files.

**Comment by fisker** [comment]
- [x] `.babelrc`, JSON5 https://github.com/babel/babel/blob/218faee4351345415b40b23a9e0102f628d45108/packages/babel-core/src/config/files/configuration.ts#L158
- [ ] `.devcontainer.json`
- [x] `.eslintrc.json`， JSON  https://github.com/eslint/eslintrc/blob/a61384731aff386a8260a80d9710c912e4f62aaa/lib/config-array-factory.js#L188-L203
- [ ] `.jscsrc`
- [ ] `.jshintrc`
- [ ] `.jslintrc`
- [ ] `.swcrc`
- [ ] `api-extractor.json`
- [ ] `devcontainer.json`
- [x] `jsconfig.json`, JSONC
- [ ] `language-configuration.json`
- [x] `tsconfig.json`, JSONC
- [ ] `tslint.json`

**Comment by ghiscoding** [comment]
hello @fisker, I still see this regression with v3.2.4 of Prettier, it tries to add comma to all my JSON files which makes all my JSON files to become invalid

![image](https://github.com/prettier/prettier/assets/643976/f8c3b833-86ee-4fb6-87df-6e6f53defa1d)

ref Lerna-Lite GitHub Action Renovate [Job](https://github.com/lerna-lite/lerna-lite/actions/runs/7564125863/job/20598047571) failure

**Comment by cbazureau** [comment]
Agreed with @ghiscoding, tsconfig.json is in the [wrong section](https://github.com/microsoft/TypeScript/issues/4987) (typescript don't use a jsonc parser).

Seems to be the case [here](https://github.com/microsoft/TypeScript/issues/4987) after [this fix](https://github.com/microsoft/TypeScript/pull/5450) but it's not see the [fix code](https://github.com/microsoft/TypeScript/pull/5450/files#diff-4dd2736e47d6b51eaf8ff275c70e53dc5f6bca718a54a2af474cd06147413f68R409) and this [issue/comment](https://github.com/TypeStrong/tsconfig/issues/30#issuecomment-1016718351) it's still Json.parse behind (with just a comment pre-strip)

**Comment by kireerik** [comment]
@fisker I recommend we open this issue, because this was not resolved (#15947 does not resolves it).

**Comment by fisker** [comment]
What do you mean?

```
>cat .eslintrc.json
{
  "a":
"b"
}

>yarn prettier .eslintrc.json
{
  "a": "b"
}
```

**Comment by kireerik** [comment]
With version `3.2.` `3` and `4` we get an error message for this file that trailing commas are missing (non are missing):

jsconfig.json
```JSON
{
  "include": ["src"],
  "compilerOptions": {
    "baseUrl": "src"
  }
}

```

`2` (version `3.2.` `2`) works as expected.
