### ISSUE TITLE
Shouldn't add parenthesis around assignment for sequence expressions

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1594]
```js
for (i = 0, len = arr.length; i < len; i++) {
  console.log(arr[i]);  
}
```

outputs

```js
for ((i = 0), (len = arr.length); i < len; i++) {
  console.log(arr[i]);
}
```

This pattern is common enough that it's not worth adding parenthesis there.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22for%20(i%20%3D%200%2C%20len%20%3D%20arr.length%3B%20i%20%3C%20len%3B%20i%2B%2B)%20%7B%5Cn%20%20console.log(arr%5Bi%5D)%3B%20%20%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by k15a** [comment]
Hey,

what's with this one:
```js
(({} = 0), 1);
```
currently prettier outputs:
```js
({} = 0), 1;
```
but if I remove the parens from the assignment as well it will be invalid syntax.
```js
{} = 0, 1;
```
Should this rule only apply in for statements?

**Comment by vjeux** [comment]
Yeah, I think we should only remove parenthesis inside of the left or right parts of a for loop. We are already doing similar things for assignments if you want to look at some example.

**Comment by k15a** [comment]
If I understand prettier correctly that would mean that I have to check if the parent of an assignment is a sequence and if the parent of the sequence is a for loop and then return false from `FPp.needsParens`?

**Comment by vjeux** [comment]
Correct. Need to check that the parent (sequence) is the grand parent correct child (either first or last part of the for

**Comment by vjeux** [comment]
as well
