### ISSUE TITLE
Prettier 3.2.3 incorrectly formats .estlintrc.json

### ISSUE THREAD

**Issue by fstaffa** [prettier/prettier#15946]
After updating to prettier 3.2.3, it formats .eslintrc.json with trailing commas, here is an example:

```json
{
	"parser": "@typescript-eslint/parser",
	"extends": ["plugin:@typescript-eslint/recommended", "prettier"],
	"plugins": ["no-only-tests"],
	"parserOptions": {
		"ecmaVersion": 2018,
		"sourceType": "module", <--
	},
	"ignorePatterns": ["node_modules/", "build"],
	"rules": {
		"no-console": ["off"],
		"@typescript-eslint/consistent-type-assertions": [
			"error",
			{
				"assertionStyle": "angle-bracket", <--
			}, <--
		],
		"@typescript-eslint/no-explicit-any": "off",
		"@typescript-eslint/no-var-requires": "off",
		"@typescript-eslint/explicit-function-return-type": "off",
		"@typescript-eslint/no-use-before-define": "off",
		"@typescript-eslint/no-empty-function": "off",
		"prefer-const": "off",
		"no-only-tests/no-only-tests": ["error"], <--
	}, <--
}

```

When running eslint 8.56.0, it throw an error 
`Cannot read config file: [foldername]/.eslintrc.json Error: Unexpected token } in JSON at position 210`

I assume this is related to https://github.com/prettier/prettier/pull/15881 , and that it incorrectly identifies which files are json and which jsonc. While eslint config specifies it allows comments, I am not sure it implies it also accepts trailing commas https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file-formats

[Edit]: Here are minimal replication steps:
1. checkout https://github.com/fstaffa/prettier-eslintrc-issue
2. run `npm ci`
3. run `npm run eslint` (works as exptected)
4. run `npm run prettier` (changes .eslintrc.json)
5. run `npm run eslint` (fails with error similar to what was reported above)

**Comment by henrikvolmer** [comment]
We have the same issue. Please revert https://github.com/prettier/prettier/pull/15927 or fix the problem.

**Comment by fisker** [comment]
Close in favor of #15946

**Comment by fstaffa** [comment]
I think you meant https://github.com/prettier/prettier/issues/15945

**Comment by fisker** [comment]
Yes, thank you!
