### ISSUE TITLE
Prettier infers tsconfig.json file to be .jsonc, adding in trailing comma by default

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [prettier/prettier#15942]
**Environments:**

- Prettier Version: 3.2.3
- Running Prettier via: CLI
- Runtime: Node.js v20
- Operating System: macOS
- Prettier plugins (if any): _(none relevant)_

**Steps to reproduce:**

```plaintext
echo '{\n"a": "b"\n}' > tsconfig.json
npx prettier@3.2.3 tsconfig.json --write
cat tsconfig.json
```

**Expected behavior:**

```json
{
  "a": "b"
}
```

**Actual behavior:**

```json
{
  "a": "b",
}
```

Although TypeScript supports loading TSConfig files with comments regardless of their extension, it's not JSON-spec-compliant to allow trailing commas. Other tools may assume TSConfig files to be valid pure JSON.

For example, in https://github.com/JoshuaKGoldberg/create-typescript-app/issues/1257, I'm seeing that the `eslint-plugin-jsonc` rule `jsonc/comma-dangle` is newly failing on `tsconfig.json` files. A workaround could be to disable the rule in `tsconfig.json` files... but that means extra ESLint config complexity for a deviance from normal filename conventions.

**Comment by fisker** [comment]
Use

```js
{
  "overrides": [
   {
     files: ["tsconfig.json"],
     options: {
       trailingComma: "none",
     },
   },
  ],
}
```

**Comment by fisker** [comment]
> adding in trailing comma by default

That's because [the default value of `trailingComma` is `"all"`](https://prettier.io/docs/en/options#trailing-commas).

**Comment by JoshuaKGoldberg** [comment]
😬 Using `overrides` makes sense, but this really violates standard conventions for commas in `.json*` files. TypeScript _allowing_ files to have comments and trailing commas is one (useful!) thing but _writing them to the file by default_ is another. I think this is going to end up conflicting with other tools that expect pure-JSON-by-default.

**Comment by fisker** [comment]
> I think this is going to end up conflicting with other tools that expect pure-JSON-by-default when the extension is .json and not .jsonc.

Other tools should treat [those files](https://github.com/prettier/prettier/blob/6c6a332171f590a38c369673662d1a5baf765167/tests/integration/__tests__/__snapshots__/support-info.js.snap#L524) as "jsonc" as well, if not, that's their problem.

**Comment by filiptammergard** [comment]
Why did this change between v3.2.1 and v3.2.3 of Prettier? Seems like a breaking change in the sense that I'd have to either add a trailing comma in `tsconfig.json` or add an `override` in every TypeScript project I have.

I think `trailingComma: "all"` should only add trailing commas where it's compliant (in `.jsonc` but not `.json`.

**Comment by jiadesen** [comment]
This change is strange...

**Comment by fisker** [comment]
> Why did this change between v3.2.1 and v3.2.3 of Prettier? 

Current behavior is expected to work in `v3.2.0`, but it didn't work because we had bug.

**Comment by jeripeierSBB** [comment]
E.g. using `JSON.parse()` with trailing commas is (still) not possible: `JSON.parse('{"foo": "bar",}')` throws an error.
In my opinion as default for ".json" files it should not apply any trailing commas.

**Comment by filiptammergard** [comment]
You might be right that `tsconfig.json` should have trailing comma @fisker. But as a Prettier user, it's strange to have to manually handle a patch release. Shouldn't this change come as part of a major release?

**Comment by jeripeierSBB** [comment]
I did some testings with IDE. I agree with tsconfig.json: Intellij and VSCode accept it as jsonc as @fisker mentioned and it's valid. 
I don't agree with ".eslintrc.json" which is per default settings not recognized as jsonc and throws warnings now in VSCode and Intellij.

**Comment by fisker** [comment]
> I don't agree with ".eslintrc.json" which is per default settings not recognized as jsonc 

https://github.com/prettier/prettier/issues/15945

**Comment by filiptammergard** [comment]
Another thought: It's very common for projects (libraries) to have one `tsconfig.json` and one `tsconfig.build.json`. In v3.2.3, this will lead Prettier to treat the first one as JSONC (inserting a trailing comma) and the second one as JSON (not inserting a trailing comma). Both are JSONC.

**Comment by slifty** [comment]
A related question to this issue: what is the reason for including trailing commas to `jsonc` when the entity that defined the specification [explicitly discourages them](https://code.visualstudio.com/docs/languages/json#_json-with-comments)?

For instance, if I rename my tsconfig files to `.jsonc` then prettier's output [results in a warning in VSCode](https://github.com/microsoft/vscode/issues/102061).
