### ISSUE TITLE
Unexpected embedded formatting for Angular template

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#15969]
**Prettier 3.2.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8C2AHAGwEN5MBeTAHRADMIIAjIgJ2oG5KpOABAYQnzQEMABTBOmTAG1chEnAC6STAAMAPAAsAjAD5gwSYcka4BAhEwBfS2oD02nSoA0nSwEpOcAB54IzLGDEaGiYAIJ4ePyCUMKYwJacIE4gEHgwAJboyKAszBAA7gAKLAhoyCBEBPlEAJ5lyQzMRGAA1nAwAMpEOHAAMukxyDSVaHANTa3tHXjNAwDmyDDMAK5jIKM46Ysra954cMzpPbCVACoHUCzpcGVIwwSjyWjzBHAAissQ8EMjawBWaC8HRe70+3zuv2SAEcwXBCnk8LcKmgALQxOAAE0xSRASyI6QI8yiOCI5UqBBxzygc1eoRgS3SDGW8EKB36gwhDzWGhgOAIAHUNOl4GgZmA4B1SsL0gA3YU1cpgYI4mWrACSUCxsA6YEOaVCmo6MBqrx+XOSeDyo35TTw5UtNwOMrgOIGo388KIcxJZseIBmzHd5SYDFMOMtAxg-PSGJgGmQAA4AAzJZhwGHpNOe72kzl+mBEBjR2PxpAAJmSy1Gp0Lt3ufrgOFDGKxGN6RGpyy9cAAYn4SfT5mTmRAQNYgA)

```sh
--parser babel
```

**Input:**

```jsx
const template = "foobar";

@Component({
  [template]: `<h1>{{       hello }}</h1>`,
})
export class AppComponent {}

```

**Output:**

```jsx
const template = "foobar";

@Component({
  [template]: `<h1>{{ hello }}</h1>`,
})
export class AppComponent {}

```

**Expected output:**

```jsx
const template = "foobar";

@Component({
  [template]: `<h1>{{       hello }}</h1>`,
})
export class AppComponent {}
```

**Why?**

Prettier formats the content of the `template` field in Angular's `@Component` decorator as HTML. However, it now also formats the content of a different field named `template` as HTML. This isn't expected.

I think adding `!node.computed` to https://github.com/prettier/prettier/blob/4b1965ae45dcaeb4208e8c7ee366f54372b69256/src/language-js/embed/utils.js#L47-L51 will fix this.

**Comment by JounQin** [comment]
Seems easy to fix.

**Comment by JounQin** [comment]
@sosukesuzuki Here you are #15972

**Comment by sosukesuzuki** [comment]
@JounQin Thank you for working on this!
