### ISSUE TITLE
Prettier 3.2.4 incorrectly formats .babelrc

### ISSUE THREAD

**Issue by AndyGera** [prettier/prettier#15960]
**Expected Behavior:**
Prettier should treat the .babelrc file as a regular JSON file and should not add trailing commas.

**Actual Behavior:**
Prettier incorrectly identifies the .babelrc file as JSONC, leading to the insertion of unwanted trailing commas.

**Comment by ghiscoding** [comment]
probably related to issue #15956 and #15945

**Comment by fisker** [comment]
```
>prettier -v
3.2.4

> prettier --file-info .babelrc
{ "ignored": false, "inferredParser": "json" }
```

**Comment by jessekrubin** [comment]
@AndyGera same here with my good old `tsconfig.*.json` files... :/

**Comment by AndyGera** [comment]
> ```
> > prettier -v
> 3.2.4
> 
> > prettier --file-info .babelrc
> { "ignored": false, "inferredParser": "json" }
> ```

This is true.

After dancing with a tambourine around deletion, reinstalling, downgrading, and updating, the file formats normally.

**Comment by sosukesuzuki** [comment]
@AndyGera Can we close this?
