### ISSUE TITLE
[typescript] Incorrect formatting of constructor

### ISSUE THREAD

**Issue by edugouvfr** [prettier/prettier#15983]
**Prettier 3.2.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKcAeAHCAnGAAjABsBDAZwsIDEIJDDh1GXjoKY8BXMGfABTY8ASwBuZeIQBGZPEk6ioAcwA0MsgC8FXESoCUTAL7ojIVSAjYYIjslBy8EAO4AFOQgrIQZMRBEAJuYg0nhkYADWcDAAymQAtnAAMnpwyABmZCQUcBah4VGx2OF6yshc3LkgOfEi5TxVWNhwoomwWQAqLVByInBeSJnZVRSlJHAAitwQ8BlZORYAVhSYMWOT07OD81UAjptwrk7YAz4UALQYcAHXwVxkIiSlAMIQ8fFk3lDQaRajKuMAIIwXTSbjwVwtFIYObDCwACxg8RIAHV4SJ4BRimA4DFPBjxBiAJ7eMBUYJiSoASSgN1gMTAomsgNpMRgRPGsIWIGEEByKLC2G8wn6LTEvxAehyBCOZGUHy5VWKeGl3nZzQojJE1mCeDg+xEetl8s+2zhIBgZGkKMCMHhyAATBZuDkOlaBkNuXB4tJrjcAkkyCpuHK4HQ8B8QaVvGRwRBgstMAAhMKRaJxRLQtJm7kBCBgRUWSgwQuWcHYcEO0vCPQwG0BO3IAAcAAYjEYgA)

```sh
--parser typescript
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx

export class Foo  {
  
  constructor(private bar:string, baz:string) {}
}
```

**Output:**

```tsx
export class Foo {
  constructor(
    private bar: string,
    baz: string
  ) {}
}

```

**Expected output:**

```tsx

export class Foo  {
  
  constructor(private bar:string, baz:string) {}
}
```

**Why?**

Prettier force wrapping of constructor's arguments when a modifier is used

**Comment by fisker** [comment]
Expected behavior, see https://github.com/prettier/prettier/pull/14402
