### ISSUE TITLE
Add Vim Support

### ISSUE THREAD

**Issue by fingermark** [prettier/prettier#16]
Hope this is the appropriate place for tracking this.

For anyone interested in adding this, please see these potential references:

https://github.com/Chiel92/vim-autoformat/blob/master/plugin/autoformat.vim

https://github.com/facebook/reason/blob/0883fc938802a028c4e0c07ad8da67faf16625e7/editorSupport/VimReason/plugin/reason.vim

**Comment by jlongster** [comment]
Thanks! Yep here is good for now. I bet somebody will do vim soon. If not I'll do it when I get time.

**Comment by bspaulding** [comment]
Heyo, I use vim and would love to try to tackle this. I'm a bit light on vim script though, does this feel like a good or bad first project? heh.

**Comment by colbydehart** [comment]
[Neoformat](https://github.com/sbdchd/neoformat) has added this functionality today if anyone is wanting to implement prettier in another formatting plugin and needs inspiration/reference.

**Comment by vramana** [comment]
There is note for vim usage in Readme now. So, I am closing this issue.

**Comment by rauchg** [comment]
@vramana you might want to re-open this in view of: https://github.com/jlongster/prettier/issues/743 specially https://github.com/jlongster/prettier/issues/743#issuecomment-280958650

**Comment by vjeux** [comment]
This has been addressed. https://github.com/prettier/prettier#vim
