### ISSUE TITLE
Pre-commit hook does not work when repository is located on a mapped network drive on Windows.

### ISSUE THREAD

**Issue by KelSolaar** [prettier/prettier#16001]
**Environments:**

- Prettier Version: 3.1.0, v4.0.0-alpha.8
- Running Prettier via: Pre-Commit
- Runtime: Pre-Commit
- Operating System: Windows
- Prettier plugins (if any): None

**Steps to reproduce:**

With a project stored on a mapped network drive on Windows, e.g. `\\server\share\repository` -> `D:\repository`, the prettier pre-commit hook fails.

**Expected behavior:**

Pre-commit hook should support network drives.

**Actual behavior:**

```
prettier.................................................................Failed
- hook id: prettier
- exit code: 2

'\\server\share\repository'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
[error] No files matching the pattern were found: "foo/bar".
```

**Comment by tkalmar** [comment]
Shouldn't this be raised against https://github.com/pre-commit ? 
Perhaps also 
https://stackoverflow.com/questions/45071585/cmd-does-not-support-unc-paths-as-current-directories
helps

The error is in no way related to prettier, either it stems from pre-commit or Windows Explorer

**Comment by fisker** [comment]
Thank you @tkalmar 
Close since this should be fixed on pre-commit side.
