### ISSUE TITLE
Bare embedded GQL string in e.g. JS is not formatted

### ISSUE THREAD

**Issue by keithlayne** [prettier/prettier#16007]
**Prettier 3.2.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mA9AFSYDiATgIYAOAFgIoAympxmABgDpSaYAjgFc4VAJ448mYJgCWAE0wBfPlwDcfPmUq1Grdp178hoiVPyzFKtepAAaEBDow56ZKBpUqEAO4AFLwQ0ZBAaABtfGnEQxwAjWjAAazgYAGUaAFs4FjkoOGRsCLQ4eMSU9LoaMDyAc2QYKlFHEsy5BqbSkDgADzoxOWzYCIAVMSgvOTgQpCLwkpa68LgmYQh4QuKugCs0HrSllbWN2a3HEXW4fx86GbC0AFp8uAUXhxBGmjlwuoBhCEymRooQi4XeaEOAEEYI05HFhPB-GJcvlNvMugwYJlwgB1BhyeBoKpgOBpYIEuQANwJ4lCYDQsRAlNEAEkoK9YGkwFQ5C5Iey0jBxMs0QsQHQfCUcXpQhLpmJKQVHHkSlQYNcaLUgaKulUqKrQnEaHE4GDHBK8jAcYoYAxkAAOAAMjiocBEcldGq1wNO6McMGN1oUtuQACZHMISiNjTM5mK4JkTQpXgoWDQoLVhJq4AAxCBUIEwuoghEQEDKZRAA)

```sh
--parser babel
```

**Input:**

```jsx
const foo = /* GraphQL */ `
  query foo { id }
`;

foo(/* GraphQL */ `
  query foo { id }
`);

/* GraphQL */ `
  query foo { id }
`;
```

**Output:**

```jsx
const foo = /* GraphQL */ `
  query foo {
    id
  }
`;

foo(/* GraphQL */ `
  query foo {
    id
  }
`);

/* GraphQL */ `
  query foo { id }
`;
```

**Expected output:**

```jsx
const foo = /* GraphQL */ `
  query foo {
    id
  }
`;

foo(/* GraphQL */ `
  query foo {
    id
  }
`);

/* GraphQL */ `
  query foo {
    id
  }`;
```

**Why?**

We use GQL snippets in TS sometimes purely for codegen - these strings get stripped out during build. We don't need or want to assign to variables, so it would be nice to get these formatted by prettier.

I'd consider this to be a nice-to-have feature. I have no idea if this was a conscious decision, or if it's some kind of design limitation. I'd be willing to implement if this feature would be considered and somebody pointed me in the right direction.

**Comment by sosukesuzuki** [comment]
To the best of my recollection, I don't believe this is either an intentional design or a limitation.

**Comment by fisker** [comment]
If that's the real world case, I think we can accept.

**Comment by keithlayne** [comment]
Thanks - this may be trivial for someone who knows the codebase and has time to look at it, but otherwise, any pointers on where to look? I confess I haven't looked yet.

**Comment by keithlayne** [comment]
Also, I'm not clear on the scope of what I've requested - is this a generic thing that applies across embedded languages somehow, or limited to embedding languages in JS/TS, or specific to JS/TS/GQL? 

I know I need to do some reading of docs and code, but again, any pointers are welcome.
