### ISSUE TITLE
JSONC formatting: preserve comment spacing

### ISSUE THREAD

**Issue by kristof-mattei** [prettier/prettier#16003]
**Prettier 3.2.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm3ggWwAcBLAGzgCcB5QmY6AZ1yU3S20wHoAqTANWINiMTAAsYMQgySdOAQwDWcgHT4GnGA0hQAZsQDmmGBEwU4cgCaZ8EM5jkAjCAFcRMUYMx7ymbpwwYHFy8AAoUEABWcGCavv7sHLjEUGBm+AgwcqTMXlkMcAA0QcUlpWXBmADKcgBucJjKmg7OZBbJOibecAxGJlmkEADuXraYyalw6bBZmJBEZHJ00JgQOpiE4VExDMpxgRyyOHhEEELwOTAUzoXlt3fYPJgAolCOPtoMl3LJse6L9qQBsM5JgACoAT0IcEqqWItHWm2ibhMDnqznyVkGwlECMiSNMcB0lAQYG6uz8AQSFQAMnIoPpnHJ9PU6VYXjViOEoFMRBSqbhMhRmTAcrgnpUAHJwAAeIpARXuirKj0qcDconqAClanIYRQ4SJSHSGUz6nUKEJlh0KJhJsJ4FZtTVdbD4ayxilSM4LPU5oRFsQHD5SIGKHIKODMD6wEaw0soDs9uwAL4YZPykAQWj0BPIUDh8KDELhhAMZAgLKDOTgssFEAOMNgBRq6rpanJODIHR5Qr1xvNmCVf1gZL6ZCXa51-L4Yjjq69mVQ-U8rKgyivfXdLs9qej8gARWcEHg29I+TrEQY0sqe7gh+PnaQ3bPvYAjkf4GEs2WUHIGABaKA4DgH0LAzL4yFHABhAh8Dkct+gzIR6XIABBCR9WaT9KHbIDT3PEBxHwUgAHUPHgBhh2hUthGIDkYHBcswAYWsQBqa4AEkoB9WA9QNVDuMqBjyHw3sNlOOASLDQhyw2bpKDqDNknyCgYDCJk4NEut-QtShy0vaAwAzMx305OB1P0TSnx3EBMgcEjiAsdxkAAJjrdE4FBRwf2fAjJlRCxQNpelGWZAAxWw4IkUcENcCAQGTZMgA)

```sh
--parser jsonc
```

**Input:**

```jsonc
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Projects */
     "incremental": false,                               /* Save .tsbuildinfo files to allow for incremental compilation of projects. */
    // "composite": true,                                /* Enable constraints that allow a TypeScript project to be used with project references. */

    /* Language and Environment */
    "target": "ESNext",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
  }
}
```

**Output:**

```jsonc
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Projects */
    "incremental": false /* Save .tsbuildinfo files to allow for incremental compilation of projects. */,
    // "composite": true,                                /* Enable constraints that allow a TypeScript project to be used with project references. */

    /* Language and Environment */
    "target": "ESNext" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
  },
}

```

**Expected output:**

```jsonc
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Projects */
    "incremental": false,                                /* Save .tsbuildinfo files to allow for incremental compilation of projects. */
    // "composite": true,                                /* Enable constraints that allow a TypeScript project to be used with project references. */

    /* Language and Environment */
    "target": "ESNext",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
  },
}

```

**Why?**
 
I'm not sure if Prettier is the right place for this, but I rely on this formatting in my `tsconfig.json` to ensure that I can track new options introduced into newer versions of Typescript.

As such Prettier moving the `,` after the `/* ... */` and reducing the spacing between the value and the comment dramatically increase the diff when I want to look at new config options.

Right now I disable Prettier for my `tsconfig.json`. 

If Prettier is not the right tool for this, that's fine, but at least then the answer is explicit!

**Comment by sosukesuzuki** [comment]
We will not implement special formatting for comments exclusively for TypeScript. They will be treated the same as comments in other languages.

Also, probably we will stop formatting `tsconfig.json` as `jsonc` ( https://github.com/prettier/prettier/pull/16012 ).
