### ISSUE TITLE
Release notes or changelog for v4

### ISSUE THREAD

**Issue by purplepenguin2** [prettier/prettier#16009]
Apologies if I'm missing something obvious, but I looked high and low and couldn't find any official information on v4 (currently `4.0.0-alpha.8` on npm).  Is there any official place or tracking issue that lists the current set of changes / breaking changes, along with a tentative plan for when it'll come out of alpha?  If not, is it possible for a tracking issue or something to be created that the community can follow along at?  Basically, at the moment, I'm simply looking to answer the questions of "what's different between latest and next tags, and what's the tentative stable release date?"

Thanks.

**Comment by sosukesuzuki** [comment]
The alpha version of v4 has been released as a version to experimentally try out [the fast CLI](https://prettier.io/blog/2023/11/30/cli-deep-dive) currently in development. There are no specific milestones or issues yet. I believe they will be created eventually. Please wait for further updates.
