### ISSUE TITLE
Don't split short, expression-bodied arrow functions across multiple lines without parentheses

### ISSUE THREAD

**Issue by justingrant** [prettier/prettier#16006]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFsBDebAS3IBsA5c0uPAXgB0o88AKCmEjwBZSnBr0AlOwB8eAAYASYAIB0FKAFcAZuTAxN2caqjM4AXzzK1plpeuVVkOjnPyA3Fy7osuAtBI8AXFaRjN2PgEhUSpQ6TY5Xi4eJRVHDR09AyNsEzN7NJg8uytCpwgXbDcuSXcQABoQCAwYagDkUHJsbAgAdwAFLoQiZBB6XvIATxHGgCNsPQBrOBgAZTMAGWooOGRdOiI4OYWwZbWMPW2Ac2QYbE0j1FJZuAATV7eN8igrzXIruAAMRwAlaP1G5E0MAgDRAAAsYKQ6AB1OHUeBEC5gOCrYbo6gAN3Rk1GYCIMxA20OuH6CyuFD29EOjQAVkQ0KtrnQ4ABFTQQeCMg6PC7YamjGCTDBwIhgGgtWEYGiwZHUV4wOHIAAcAAZGkqIIdkQsMKMlTLxATdo0AI78+C05ojFDkIgAWh2bzesKMduoRlp-wZSH2zJAh1I1Fu90eRC5cAAgjA7tRZlC4P1xFsdkKw3Gfty+QLdiGmY8YORZqr1ZqkAAmRp3cjUOjXADCEFIwbGdDosM0hwAKpXnaHHgSHgBJKAfWCrOXUFoJmerSXc3MWcxAA)

```sh
--parser typescript
```

**Input:**

```tsx
export const materialName =
  (mat: Material) => `${mat.manufacturer.name} ${mat.name} ${mat.color}`;

export const materialName = (mat: Material) => (
  `${mat.manufacturer.name} ${mat.name} ${mat.color}`
);
```

**Output:**

```tsx
export const materialName = (mat: Material) =>
  `${mat.manufacturer.name} ${mat.name} ${mat.color}`;

export const materialName = (mat: Material) =>
  `${mat.manufacturer.name} ${mat.name} ${mat.color}`;

```

**Expected behavior:**

One of the inputs would be Prettier's output. Either put parentheses around the expression (like Prettier does for JSX) or put the parameters and expresion body on a single line.

The current behavior makes it easy to leave "orphan" expressions if the first line gets deleted, e.g. in a failed merge conflict resolution or by accident.

**Comment by DATEx2** [comment]
Damn bumped into this - and the issue was posted just 17 hours ago - while I was hoping to be already fixed by now

**Comment by sosukesuzuki** [comment]
It seems to be a difficult issue to judge which code is more appropriate. I don't think we'll be addressing this anytime soon. I'm closing this for now. Sorry.

**Comment by DATEx2** [comment]
Say whaat?
