### ISSUE TITLE
Add support to each-in for plugins/glimmer.mjs

### ISSUE THREAD

**Issue by rgaiacs** [prettier/prettier#16011]
[Glimmer](https://glimmerjs.com/) and [Handlebars](https://handlebarsjs.com/) has many similarities but they are not the same. For example, Glimmer defines the [`each-in` helper](https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/methods/each-in?anchor=each-in) but Handlebars lacks this helper.

**Comment by rgaiacs** [comment]
Sorry for the issue. I precipitate in the error. Thanks for the fabulous tool.

**Comment by fisker** [comment]
Are we formatting it wrong? What's expected?

**Prettier 3.2.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeArgGwHwB0oAEBwwAxHAIZgAWAtAJaEzX0DOAdACZwBucmEAA5wATgQqsCAHwDWcAJ4EeFTOjhSAvhvxEiqTPWwk58rUmLBlquFtQB6A3kIW7lGgyhb89rNhAAaECEYemhWZFAKEREIAHcABSiEcJQVWIp5cMCAIxEqORgAZQoAWzgAGUY4ZAAzFVY4HLywAsLBKkYAc2QYETVAhpL6Hr7GkDgAD2ERejLYFQAVUSgo+jgUuswGga7MOABFdAh4WvqxgCtWCcLdg6OTpE3tkABHe7h4mMEUkAlaKDgcG4nACIF6FHoBignQAwhASiUKMhfphMKDWLcAIIwXr0bLoeDxUSVAGnLZjagwEqYADqLHgrHaYDghWS9BCPHZ8mRYFYWRAPDUAEkoNxYIUwDNBDBMaLCjB5Hsyc9BDEGjS8oJkar1qI+KDGA0RDBPhROojlWN2iIjcjOgYEaJQarGDAafROMxkAAOAAMgREcDe9EDpvNSMeZ0CMAo2XdnuoyAATIF0A0FrGNlHxiVskDgeUKND0Ga4AAxCAiRE4rrIigEiAgLRAA)

```sh
--parser glimmer
```

**Input:**

```hbs
<ul>
  {{#each-in this.developer as |key value|}}
    <li>{{key}}: {{value}}</li>
  {{/each-in}}
</ul>
```

**Output:**

```hbs
<ul>
  {{#each-in this.developer as |key value|}}
    <li>{{key}}: {{value}}</li>
  {{/each-in}}
</ul>
```
