### ISSUE TITLE
Add lines between class methods

### ISSUE THREAD

**Issue by iRoachie** [prettier/prettier#1603]
This is a feature request to insert lines after class methods.

### Before
```js
method1() {
}
method2() {
}
```

### After (Expected)
```js
method1() {
}

method2() {
}
```

**Comment by azz** [comment]
Prettier respects the newlines from the source.

[Example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20A%20%7B%5Cn%20%20method1()%20%7B%5Cn%20%20%7D%5Cn%20%20method2()%20%7B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnclass%20B%20%7B%5Cn%20%20method1()%20%7B%5Cn%20%20%7D%5Cn%5Cn%20%20method2()%20%7B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by iRoachie** [comment]
I know this. I'm suggesting that this be added either natively or through a flag.

#### Current setup
Write React Typescript -> Compile to JS -> Prettier on compiled js

However the typescript compiler strips new lines from the source. So the compiled javascript has no spacing between methods.

This is why I'm asking if it can be added to insert new lines when running prettier

**Comment by azz** [comment]
Curious as to why you're running prettier on compiled code? Wouldn't source maps usually be the solution here?

**Comment by iRoachie** [comment]
Simple example.

Compiled JS from TS:
```js
import React from 'react';
import { Platform, View, TouchableOpacity, TouchableNativeFeedback } from 'react-native';
class Touchable extends React.Component {
    render() {
        if (Platform.OS === 'ios') {
            return (<TouchableOpacity style={this.props.style} onPress={this.props.onPress}>
          {this.props.children}
        </TouchableOpacity>);
        }
        return (<TouchableNativeFeedback onPress={this.props.onPress}>
        <View style={this.props.style}>
          {this.props.children}
        </View>
      </TouchableNativeFeedback>);
    }
}
export default Touchable;
```
After Prettier:
```js
import React from 'react'
import {
  Platform,
  View,
  TouchableOpacity,
  TouchableNativeFeedback
} from 'react-native'
class Touchable extends React.Component {
  render() {
    if (Platform.OS === 'ios') {
      return (
        <TouchableOpacity style={this.props.style} onPress={this.props.onPress}>
          {this.props.children}
        </TouchableOpacity>
      )
    }
    return (
      <TouchableNativeFeedback onPress={this.props.onPress}>
        <View style={this.props.style}>
          {this.props.children}
        </View>
      </TouchableNativeFeedback>
    )
  }
}
export default Touchable
```

**Comment by vjeux** [comment]
We tried to do add empty lines automatically but it didn't work all the time so now we are just letting the user do it. Sorry but we're not going to change this behavior.

**Comment by iRoachie** [comment]
@vjeux Cool 👍

**Comment by linesh-simplicity** [comment]
Just wondering if this feature is likely/planned to be added to prettier in the future, adding new lines between class members? Makes sense to me to have it as a default option.

**Comment by lydell** [comment]
No, this is not planned. It could be part of #2068 though. For now, we stick to the rules described here: https://prettier.io/docs/en/rationale.html#empty-lines

Not that there’s an ESLint rule with `--fix` support for this: https://eslint.org/docs/rules/lines-between-class-members
