### ISSUE TITLE
HTML parsing error for Angular components

### ISSUE THREAD

**Issue by tachojelev** [prettier/prettier#16044]
Hello,

We are using prettier in our angular application project for both TS and HTML. After implementing some code in the HTML, we started noticing a couple of parsing errors (across multiple HTML files) that prevent us from committing (we are also using husky).

The errors do not same to make any sense and we were unable to find the actual reason for them.

**Our project uses**:
"prettier": "3.2.5"
"eslint": "^8.37.0",
"eslint-config-prettier": "^9.0.0",
"eslint-plugin-prettier": "^5.0.1",

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```html
<header>
  <h1>Web SDK - Welcome to the Angular demo project</h1>
</header>

<div class="main-container">
  <app-navigation [logoImageSource]="'assets/logo.png'">
    <app-navigation-item
      title="Profile"
      routerLink="/profile"
      routerLinkActive
      #profileRouterLink="routerLinkActive"
      [selected]="profileRouterLink.isActive"
    ></app-navigation-item>
  </app-navigation>
</div>
```

**Output:**

```html
// output is the same
```

ERRORS:
```sh
demo-angular/src/app/app.component.html
  1:10  error  Parsing error: '>' expected
demo-angular/src/core/components/wallet-error/wallet-error.component.html
  1:11  error  Parsing error: ';' expected
```

**Expected output:**

```html
// same or similar output, but no errors
```
<img width="850" alt="app" src="https://github.com/prettier/prettier/assets/12784974/ae7d5512-d950-4b30-8ad0-e62d7be8ad14">
<img width="495" alt="wallet" src="https://github.com/prettier/prettier/assets/12784974/08630d75-703c-44df-a7ff-6db756a14e5d">

**Why?**

All brackets and tags are correctly opened and closed. There is no logical reason to expect ";" in the HTML.

Any assistance would be highly appreciated!

**Comment by fisker** [comment]
Can't reproduce

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFnAhgEzgJwD4AdKAAjIwEZCB1OAIzIGUARAaTIFoz6AbSAFs4ZGBFGYyAQSgBzAK58s+MnkHiADvggArOGBioA9OhqljmXARJRzOAJYA3MmCUBnNwF5iIQVntQXJCw-lAEPjYUqFgaGlxQWI72slgw9tBkANp8ELIQAJJ+snDMEPL4YHAAut4gAORYHnAwbkY5eQB0GnJ1EaQUUTFxCUkpadBc9vCC-QMUaTB8cLUACtoAZvZLPrNz2vLw+AAyAQDWtUZaEJvbILsD+4cnUKdSBk5w9xQAxFc3cAAlMpPM61R4EZ6vd6OT53chzLJuOBLAxwHA1Hx-LaA4EQs4dexuN5pGE7eEUQjGIbxRLJVLpQJTOCCSKUIzUkZ08ZQGzGByOQggAA0IAgGm5bmQoGU2gA7itlAhJSgsHxZVgAJ6SkUMfBYMCnZrMLDCZ5wZDrVVInV6g1GjT6gKyZAwfDyOAipGCewut0ekBwAAeGgI9mEIT4ABUCAl8PY4MrLXxrSA3E6lgBFeQQeAWq3+nRuQPMdNwLM581IJMpgCO2fgazFypAjXicDRaOFIFd-j4ToAwhBBH5kC2+Hwu2m5EspDBXfYGAc4Cs8WE88n-egYII+LR0Ey3A7KswlVMnFMNaOwB4u453fkoHhYMwwHHxTIcMwYBqluuU1ckVoPUNFHLQEwIGEuwCJF8BgNYsFkEcq3zEUHXwGDRywORFGULstACGBaHsHAYHQZAAA4AAYRXwOA63sWj4MQrA-39GAsAYIiSLIpAACYRXkJFIw4xMUIDQQGDRPAcCOLCFAQuAADEIHwPw5ydTCDggEAAF8dKAA)

```sh
--parser angular
```

**Input:**

```html
<header>
  <h1>Web SDK - Welcome to the Angular demo project</h1>
</header>

<div class="main-container">
  <app-navigation [logoImageSource]="'assets/logo.png'">
    <app-navigation-item
      title="Profile"
      routerLink="/profile"
      routerLinkActive
      #profileRouterLink="routerLinkActive"
      [selected]="profileRouterLink.isActive"
    ></app-navigation-item>
  </app-navigation>
</div>
```

**Output:**

```html
<header>
  <h1>Web SDK - Welcome to the Angular demo project</h1>
</header>

<div class="main-container">
  <app-navigation [logoImageSource]="'assets/logo.png'">
    <app-navigation-item
      title="Profile"
      routerLink="/profile"
      routerLinkActive
      #profileRouterLink="routerLinkActive"
      [selected]="profileRouterLink.isActive"
    ></app-navigation-item>
  </app-navigation>
</div>

```

**Comment by fisker** [comment]
There is nothing we can do with the information you provide. You can try to delete part of your code and post small pieces of part that it throws.

**Comment by fisker** [comment]
Maybe you have the wrong parser configured? Try to run `yarn prettier --file-info /path/to/file` and check if the parser is correct.
