### ISSUE TITLE
Unnecessary parenthesis when assigning in a while loop

### ISSUE THREAD

**Issue by sapegin** [prettier/prettier#1605]
See in a [playground](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20x%3B%5Cnwhile%20(x%20%3D%20true)%20%7B%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
):

```js
let x;
while (x = true) {}

// →

let x;
while ((x = true)) {
}
```

**Comment by vjeux** [comment]
This is actually intended, it calls out that you are making a mutation instead of a comparison

**Comment by gburtini** [comment]
I wonder if there isn't a way to make this intent more clear. Perhaps one way is for Prettier to always reassign static comparators to the left. e.g.,

`true === x`
vs
`x = true`

I prefer requiring a comment justifying the decision to do strange mutations like this, but it is obviously hard for Prettier to automatically add that comment.

**Comment by vjeux** [comment]
I'm going to close out this issue as we're not looking into making any changes inside of prettier for this. But feel free to keep the discussion going in order to find better ways to express this.
