### ISSUE TITLE
Out-of-the box VS-Code-like formatting for files

### ISSUE THREAD

**Issue by Nefcanto** [prettier/prettier#16068]
VS Code's default coding is awesome. Yet they have not exposed it via CLI/terminal. We asked them at https://github.com/microsoft/vscode/issues/189930 and it's not done yet and no date is clear for it.

You deliver your functionality via CLI, yet, to be honest, your default formatting is not suitable for our needs. I respect your philosophy. But I'm talking about formatting presets.

If you could give us a default preset like `"preset": "vs-code"` then we could use your CLI but the default VS Code formatting to be able to format our codes in CI/CD automatically, or to write some linting hints.

Is it possible for you to do that?

**Comment by kachkaev** [comment]
Hi @Nefcanto! I’m afraid that this is out of Prettier’s scope. Feel free to fork Prettier, copy CLI-related code and mix it with VS Code’s formatting logic.
