### ISSUE TITLE
Forces variable declarations onto single line

### ISSUE THREAD

**Issue by dhowe** [prettier/prettier#1607]
I'm using prettier in atom with eslint, all of which works great. The one problem I'm having is that it fixes
```
var assert = require('assert'),
  lookup = require('../lookup');
```

to
```
var assert = require('assert'),  lookup = require('../lookup');
```
even though the former is ok with my eslint config (is there a prettierOption I am missing?)

**Comment by SimenB** [comment]
This has come up before. Answer is to use this:
```js
var assert = require('assert');
var lookup = require('../lookup');
```

**Comment by josephfrazier** [comment]
If you're okay with the following formatting, you could use [`prettier-elastic-vars`](https://github.com/medikoo/prettier-elastic-vars):

```js
var eloBar     = require("elo-bar")
  , foo        = require("foo")
  , otherThing = require("other-thing");
```

**Comment by dhowe** [comment]
I guess my real question is why prettier is 'fixing' code which is correct according to my eslint config. 
It seems there should at least be a way of disabling such 'fixes'...

The code in this particular case is, one of many, relatively common conventions for js:
```
var assert = require('assert'),
  lookup = require('../lookup'); 
```

**Comment by k15a** [comment]
That's because Prettier ignores your ESLint config and has it's own rules to format your files.

If you want to know why Prettier should stay opinionated and shouldn't respect the styling preferences of everyone you can take a look at this discussion: https://github.com/prettier/prettier/issues/40

**Comment by dhowe** [comment]
This does not appear to be the case for the prettier-atom plugin which reads the eslint-config (there appear to be a number of such eslint/prettier integrations)...

![image](https://cloud.githubusercontent.com/assets/737638/26053737/83443f58-399c-11e7-9b65-76917ddb305c.png)

But perhaps this is a philosophical incompatibility between the projects (and one I should bring up in their repo as opposed to here) ?

**Comment by k15a** [comment]
The only thing that `prettier-eslint` does is to pipe the file after Prettier through `eslint --fix`. It's not that prettier uses your eslint config. It seems that ESLint can't autofix the variable declarations.

**Comment by dhowe** [comment]
So is that note in the interface: 'that prettier-eslint uses the eslint-config to set your prettier settings' incorrect? 

Or is this particular fix just one of the things from the eslint-config which does not apply to the prettier settings?

**Comment by k15a** [comment]
I don't know correctly how it works but I think that prettier will get the [few options](https://github.com/prettier/prettier#options) it has from the ESLint config. Because Prettier doesn't have an option for this fix it can't be configured through `prettier-eslint`.

**Comment by dhowe** [comment]
so if I want this behavior then my option is to fork the project...
understood

**Comment by jsnajdr** [comment]
Would there be any downside to adding a special case where there is a forced `hardline` break between variable declarators if all of them are `require()` calls? I.e.,
```js
const assert = require('assert'),
  request = require('request');
```
would be always formatted to two lines, even if it would fit into one line as well.

When we ran Prettier on the https://github.com/Automattic/wp-calypso codebase, this was one of the cases where the Prettier formatting was a clear step backwards.

There is already another special case for `require()` that prevents breaking it into multiple lines if the argument is too long.

The number of users affected by this change should be very small -- most codebases either use ES6 imports already, or have a separate variable declaration for each `require()`. Even for us, the form with multiple variable declarators is considered legacy and we'll codemod it to ES6 imports eventually. But in the meantime, it would make the Prettier adoption smoother for us.

**Comment by vjeux** [comment]
After thinking about it more, I think that we should always break in this case. If someone wants to send a PR i'll accept it.
