### ISSUE TITLE
`pre-commit` mirror continued support for version 3 after `v3.1.0`

### ISSUE THREAD

**Issue by jamesbraza** [prettier/prettier#16076]
As of 2/14/2024, the last non-alpha `prettier` mirror for `pre-commit` was `v3.1.0`: https://github.com/pre-commit/mirrors-prettier/tags. After that only alpha versions for `prettier v4 are added.

From https://github.com/prettier/prettier/releases, it looks like `prettier` is now on `v3.2.5`. In other words, the `pre-commit` mirror is no longer supporting `prettier` v3.

The request is: can we have https://github.com/pre-commit/mirrors-prettier continue supporting major version 3 of `prettier`?

**Comment by tkalmar** [comment]
Shouldn't this be raised against https://github.com/pre-commit ?

**Comment by fisker** [comment]
Please report to https://github.com/pre-commit/pre-commit

**Comment by jamesbraza** [comment]
Thank you, I have opened https://github.com/pre-commit/pre-commit/issues/3133
