### ISSUE TITLE
Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'Svelte'-files

### ISSUE THREAD

**Issue by qupig** [prettier/prettier#16093]
I know that this issue is related to [`prettier-plugin-svelte`](https://github.com/sveltejs/prettier-plugin-svelte), [`Svelte for VS Code`](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode), [`prettier-vscode`](https://github.com/prettier/prettier-vscode). 
But the issue is posted in this repo because this is where the damage is directly caused.

After my repeated testing, this issue occurred when [`prettier`](https://www.npmjs.com/package/prettier) was updated to 3.1.1, and also exists in 3.2.0 or the latest 3.2.5 version.
In other words, the last working version was prettier v3.1.0

**Specific issue manifestations:**
Upgrading to `prettier` 3.1.1 or newer versions with only the `prettier-vscode` plug-in installed will cause the `Format Document` menu to disappear in svelte files.

If the `Svelte for VS Code` plug-in is installed at the same time, the error message in the title will be prompted after clicking the `Format Document` menu.

It looks like the issue is that after `prettier` was updated to 3.1.1, the `svelte` support provided by `prettier-plugin-svelte` was not fed back to the `prettier-vscode` plugin while the config file remained unchanged.

`vscode settings`
```json
{
	"[svelte]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	}
}
```

`.prettierrc.json`
```json
{
	"plugins": ["prettier-plugin-svelte"],
}
```

It will work fine via the prettier command line or specifying the vscode formatter as `Svelte for VS Code`, but it has nothing to do with this issue.

**Comment by sosukesuzuki** [comment]
> We are having the same problem. Reverting back to prettier 3.1.0 did fix the problem, thanks for the info @qupig .

It is strange that there is a difference in behavior between 3.1 and 3.2, we need to look into it!

**Comment by nitriques** [comment]
I can add more context, hoping it can help.

1. We had issues on two macs, all with the latest vs-code and extensions.
2. Same issues with a windows 11 box.
3. It only for svelte files, prettier was able to format ts.
4. I diffed 3.1 vs 3.2 and could not find anything obvious.

**Comment by sveltecult** [comment]
This is indeed strange. I have a project that uses `^3.0.2` and it's perfectly working. Now, I started a new project and it has `^3.2.5` and it can't format `.php` or `.svelte` files even when I'm using the same `.prettierrc.js`. It's as if it's not reading the config files nor running the plugins.

**Comment by sosukesuzuki** [comment]
https://github.com/prettier/prettier-vscode/pull/3335 will solve this.

**Comment by nitriques** [comment]
That's good news !
Thanks !

**Comment by Synweigh** [comment]
Still an issue despite https://github.com/prettier/prettier-vscode/pull/3335 being merged.

**Comment by aplotor** [comment]
im having this issue with latest vsc + `"prettier": "3.3.3"`

**Comment by aplotor** [comment]
@qupig thanks, actually its working. i had to npm install `prettier-plugin-svelte`. i originally only wanted to use `prettier-plugin-tailwindcss` but the prior is required i guess

**Comment by BijuDey** [comment]
<img width="875" alt="Screenshot 2024-10-25 at 11 15 03 AM" src="https://github.com/user-attachments/assets/58008803-5d49-42b4-8762-0f2f07cc9e90">
<img width="985" alt="Screenshot 2024-10-25 at 11 15 10 AM" src="https://github.com/user-attachments/assets/832222f6-1540-4cec-8465-bb827eef802a">
Just install an old version of the prettier fixes the issue 👍
