### ISSUE TITLE
Issues with prettier-vscode not working properly with plugins since prettier 3.1.0 release

### ISSUE THREAD

**Issue by TOnDAhNe** [prettier/prettier#16102]
**There are plenty of issues about this problem in the prettier-vscode repository, but it seems like nobody cares, so I created this issue to draw attention to it.**

https://github.com/prettier/prettier-vscode/issues/3253
https://github.com/prettier/prettier-vscode/issues/3251
https://github.com/prettier/prettier-vscode/issues/3241
https://github.com/prettier/prettier-vscode/issues/3235
https://github.com/prettier/prettier-vscode/issues/3224
https://github.com/prettier/prettier-vscode/issues/3104
https://github.com/prettier/prettier-vscode/issues/3071

**Environments:**

- Prettier Version: 3.2.5
- Running Prettier via: prettier-vscode 
- Runtime: VSCode 1.86.2
- Operating System: macOS 
- Prettier plugins (if any): 

**Steps to reproduce:**

Install the prettier-vscode plugin in vscode, install any plugin, for example prettier-xml, set prettier-xml as the formatter for xml files, configure .prettierrc (or another config file), attempt to use prettier for formatting xml.

**Expected behavior:**

The file was formatted.

**Actual behavior:**

The file was not formatted.

**Comment by phocks** [comment]
Yep, same: https://github.com/prettier/prettier-vscode/issues/3253#issuecomment-1968173844

**Comment by MikeMcDonald83** [comment]
https://github.com/prettier/prettier-vscode/issues/3235#issuecomment-1879640587 fixed this for me. I put mine in the user settings like `"prettier.configPath": ".prettierrc",`. My 3.1.1 install is correctly loading plugins again. It's probably unintended behavior, but it's a pretty easy workaround.

**Comment by phocks** [comment]
> [prettier/prettier-vscode#3235 (comment)](https://github.com/prettier/prettier-vscode/issues/3235#issuecomment-1879640587) fixed this for me. I put mine in the user settings like `"prettier.configPath": ".prettierrc",`. My 3.1.1 install is correctly loading plugins again. It's probably unintended behavior, but it's a pretty easy workaround.

Thanks. Can confirm this works. With 3.1.1 and the latest prettier version 3.2.5. If you use yaml formatting etc, just replace it with `.prettierrc.yaml` or whatever your prettier config file is called.

**Comment by TOnDAhNe** [comment]
@MikeMcDonald83 

Yeah, users have already discovered a workaround, and it does function, but should an extension that doesn't operate correctly without external intervention be distributed? An intervention that a user can only discover by visiting the repository of that extension and spending some time looking for the solution?

I don't think so, at least not until the developers pay attention to this issue and fix it so the extension could work out of the box, just like it used to.

**Comment by MikeMcDonald83** [comment]
> @MikeMcDonald83
> 
> Yeah, users have already discovered a workaround, and it does function, but should an extension that doesn't operate correctly without external intervention be distributed? An intervention that a user can only discover by visiting the repository of that extension and spending some time looking for the solution?
> 
> I don't think so, at least not until the developers pay attention to this issue and fix it so the extension could work out of the box, just like it used to.

I totally agree about the expectations. That's why I meant by "It's probably unintended behavior." That being said, it looks like there aren't a lot of people working full time on these large and complex repos. Some of them are making many changes per day. Maybe they need help. Or maybe they are just working through a backlog.

**Comment by sosukesuzuki** [comment]
https://github.com/prettier/prettier-vscode/releases/tag/v10.4.0 has been released
