### ISSUE TITLE
2 new lines after import

### ISSUE THREAD

**Issue by ugros** [prettier/prettier#1610]
Hello,

Prettier works almost perfectly, but there's one eye-catching problem for me, that won't let me sleep.

I like having 2 new lines after imports. And I think it's common in most javascript projects.

![screen shot 2017-05-15 at 13 11 59](https://cloud.githubusercontent.com/assets/20205489/26055246/49b37492-3970-11e7-8129-4adaa27eb19b.png)

Would be great if you could provide this as an (optional) setting. Something like "--new-lines-after-import 2".

Thanks!

**Comment by k15a** [comment]
As far as I know it's currently not possible because Prettier reduces multiple blank lines to a single blank line. I don't think that prettier will support that because it aims to has as less configuration as possible.

**Comment by vjeux** [comment]
Thanks for raising this issue but we're not going to allow this, sorry :( We are trying to create a consistent formatter, preserving at most one empty line is a good heuristic that's simple to explain and works well in practice. It isn't perfect but reasonable. Allowing two lines in some places would be confusing.


I'm sorry that you are losing sleep over it but I'm going to close this issue. If you really want it, I would encourage you to fork prettier.
