### ISSUE TITLE
Typescript 5 const modifier on type parameters leads to SyntaxError

### ISSUE THREAD

**Issue by mme** [prettier/prettier#16113]
To reproduce, put the const modifier in a type parameter:

```ts
 function parseNames <const T>(names:T) {
    return names
  } 
```

```
SyntaxError: Type parameter declaration expected. (9:22)
   8 |
>  9 | function parseNames <const T>(names:T) {
     |                      ^
  10 |   return names
  11 | } 
  12 |
```

More about this Typescript feature:
https://xebia.com/blog/typescript-5-0-and-the-new-const-modifier-on-type-parameters/

**Comment by fisker** [comment]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAZgVymGBLaVABwEMAnAZzgDkSBbOC1AHkigplQBUA+ACij1GSLgEpUwADpRpqOajJwYmMlFSCGFabNQBfVCAA0ICEXzQKyUOTIQA7gAVyCSyhIAbOyQCel4wCMyEjAAayUAZSEAGTwoOGR0DyoAoNCI0jBYgHNkGDJMOGMqOjxc-MKQOAAPIjgyPAZYDy46wXrGBKSKimz3OABFTAh4TvdkkAArCirw3oGhkaREsYqARwW4B1siVxASCgBaOLgAE1OjEDySPHdsgGEIOjoSZD33dwueqCy+gEEYPJ4fyYeAOOoxOKjcYACxgdHcAHVoXh4BQMnBwi4UXgAG4o7yvMAUPwgHEFACSUDOsHCYHqZl+VPCMG8fShFSItioCKCRFenMYdRx8WMsSoZBgWxIWWe7OMpEodVeLNqFDpeDMF05sRgCLwJxg0OQAA4AAzGRTrPCKKUyl5LLrGGAkfx6g1GpAAJmMmCoXBdrmW4zgdH8pzOJyiJG+mGlcAAYhAyM8AdlXiQQRAQLpdEA)

```sh
--parser typescript
```

**Input:**

```tsx
 function parseNames <const T>(names:T) {

    return names

  } 
```

**Output:**

```tsx
function parseNames<const T>(names: T) {
  return names;
}

```
