### ISSUE TITLE
Add support for `#graphql` comment for formatting GraphQL

### ISSUE THREAD

**Issue by chrisvltn** [prettier/prettier#16124]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT77VwzrWcA5gEcSDALIBNAPoBxAEoBBAAqEAigBlpagKoBReZKYcAvhw6QoAZxj4pcpas3b9h-AF58AAwDEg6gCGAA4AFqIcXMLocNQAnnaxsoGhomrRcawR+AC2cHQ4AQw4dEhsIACMZSzsUMUc-CRZZpz4zV4A3CAANCAQQbjQVsigAdTUEADuyqMIQygBJBMBsUM9AEaBYADWvADKAbkaOFBwyKgLVnDrmzswu0EBYMeCyDDU0T2X2Tiv71cgcAAHkEYjhcrAFgAVGJQUY4OBzc4kS6fZ4kOBpCDwM4Xf4AKysgN2aIx6CxpyQSJRICi5OU4yCcxAASsAFoTnk8t0QG8AjgSM8AMIQbLZALIZlkblWEmKGBvHBrdDwZQxI4nHHI-4hGDZEgUEI4eBWB5gOC7WZGnAANyNsQlYCsqxA1uiAEkoHQEHcwNQcP1FJ7djBYujNdSguNLhRkhLIwiYtbTj1jpdqDB6QFBGLw-8HtQ0xK1gE1qRuZHjjAKMUYCFkAAOAAMPR4URwPEz2fFlNxPRgJerdFryAATD10JdISXEb2AdlS3QvXQNAEoIJ0Fm4AAxGhi+XPCUBZUQEAmExAA)

```sh
--parser babel
```

**Input:**

```jsx
function HelloWorld() {
  return gql(MY_GRAPHQL_QUERY)
}

const MY_GRAPHQL_QUERY = `#graphql
  query MyGraphqlQuery {
  media(id:"1") {
id
url
  }
  }
`;
```

**Output:**

```jsx
function HelloWorld() {
  return gql(MY_GRAPHQL_QUERY);
}

const MY_GRAPHQL_QUERY = `#graphql
  query MyGraphqlQuery {
  media(id:"1") {
id
url
  }
  }
`;

```

**Expected output:**
```jsx
function HelloWorld() {
  return gql(MY_GRAPHQL_QUERY);
}

const MY_GRAPHQL_QUERY = `#graphql
  query MyGraphqlQuery {
    media(id: "1") {
      id
      url
    }
  }
`;

```

**Why?**

Even though Prettier already supports the `/* GraphQL */` comment, using the `#graphql` comment is also one of the standard ways of highlighting GraphQL code. This is what is recommended at first in the [GraphQL: Language Feature Support VS Code extension](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) in the [How do I highlight an embedded graphql string?](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql#how-do-i-highlight-an-embedded-graphql-string) guide, and also what is used by default in frameworks like [Shopify Hydrogen](https://shopify.dev/docs/custom-storefronts/hydrogen/data-fetching).

**Comment by JounQin** [comment]
You can use https://github.com/Sec-ant/prettier-plugin-embed.

**Comment by sosukesuzuki** [comment]
Also you can use `/* GraphQL */ comment

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT77VwzrWcA5gEcSDALIBNAPoBxAEoBBAAqEAigBlpagKoBReZKYcAvhw6QoAZxj4pcpas3b9h-AF58AegBU+WdQAhgAOABaa+D5eAAYAxIJBYaIcXMLocNQAnnaZASGhomrpWawp+AC2cHQ4gQw4dEhsIACMTSzsUPUc-CRlZpz4-dEA3CAANCAQwbjQVsiggdTUEADuyosIcyiBJCuBmXMTAEZBYADWvADKgZUaOFBwyKg7VnDHpxcwl8GBYPeCyBg1HSE1e5RwgOBbxAcAAHsEMjhKrAdgAVDJQRY4OBbZ4kV6g-4kOBFCDwJ4vaEAKyssMuRJJ6DJjyQeIJIDSzOUy2CWxAgSsAFoHlUquMQEDAjgSP8AMIQcrlQLIflkcVWBmKGBAnBHdDwZQZO4PCn46GhGDlEgUUI4eBWH5gOCXTZ2nAANztmRVYCshxA7vSAEkoHQEF8wNQcNNFKHLjBMsTTezgstXhREirUziMu7HhN7q9qDBuYFBErk9CftQiyqjoEjqRxan7jAKPUYKFkAAOAAMEx4aRwPFL5eVrMpExgDfbdE7yAATBN0K9UQ3cZOYeVG3Qw3QNIEoIJ0GW4AAxGhK7X-FWBfUQEAmExAA)

```sh
--parser babel
```

**Input:**

```jsx
function HelloWorld() {
  return gql(MY_GRAPHQL_QUERY)
}

const MY_GRAPHQL_QUERY = /* GraphQL */`#graphql
  query MyGraphqlQuery {
  media(id:"1") {
id
url
  }
  }
`;
```

**Output:**

```jsx
function HelloWorld() {
  return gql(MY_GRAPHQL_QUERY);
}

const MY_GRAPHQL_QUERY = /* GraphQL */ `
  #graphql
  query MyGraphqlQuery {
    media(id: "1") {
      id
      url
    }
  }
`;

```

**Comment by sosukesuzuki** [comment]
And we don't add support for `#graphql` comment
