### ISSUE TITLE
Two equivalent object structures produce different output

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#1612]
Below example lists two very same objects, just formatted slightly differently. I would expect that prettier will return same representation twice, still it's not the case:

_Input:_
```javascript
[["user", { label: "User" }],
	[
		"manager",
		{
			label: "User Manager"
		}
	]
];

[["user", { label: "User" }],
	[
		"manager",
		{ label: "User Manager" }
	]
];
```

_Prettier:_
```javascript
[
  ["user", { label: "User" }],
  [
    "manager",
    {
      label: "User Manager"
    }
  ]
];

[["user", { label: "User" }], ["manager", { label: "User Manager" }]];

```

**Comment by k15a** [comment]
Prettier keeps objects which which span multiple lines separated. That's because objects are used in many different places and it's very hard to format every single use case correctly.

**Comment by medikoo** [comment]
> Prettier keeps objects which which span multiple lines separated.

Ok, so if ithere's a new line in object literal, prettier will always span it multiple lines. It's interesting, do you have some examples on why it was done that way (?).

It doesn't sound great, as one developer will write:

```javascript
var obj1 = {
  foo: 1
};
```
the other in same file will do:

```javascript
var obj2 = { bar: 2 };
```

and prettier won't ensure consistent style for both.

--- 

On additional note, same rule is not followed for arrays.

_Input:_
```javascript
const arr = [
  "foo",
  "bar"
]
```
_Prettier:_
```javascript
const arr = ["foo", "bar" ];
```

Which again seems not consistent

**Comment by josephfrazier** [comment]
(related to #1588: "Document when input spacing is preserved?")

**Comment by josephfrazier** [comment]
> On additional note, same rule is not followed for arrays.
> ...
> Which again seems not consistent


For what it's worth, `prettier-miscellaneous` has an `arrayExpand` option which can be used to force the expanded formatting. See here for details: https://github.com/arijs/prettier-miscellaneous/tree/dbdb984fbdb18d6efb6307dfcf4a355f1dd945ad#api

**Comment by bakkot** [comment]
See https://github.com/prettier/prettier/issues/74 / https://github.com/prettier/prettier/pull/495.

**Comment by medikoo** [comment]
@josephfrazier @bakkot great thanks for links, I'm going to close it as it's certainly a duplicate of #1588 (I'll add my comment there)
