### ISSUE TITLE
[MDX] Does not keep indentation in multiline strings

### ISSUE THREAD

**Issue by disog** [prettier/prettier#16138]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ33jRgHUBLGACwEkoATBGAQxiujwF48ADADpRhhEnja88wYXjwAjJHgCMAGlkElMqHLlMlAJnU68AX2GmA3MP6WQqkBAydoRZKDbZsEAO4AFTwQ3FDYAGx82AE83B3lsNjAAazgYAGU2AFs4ABkqKDhkADMwojhY+KSU1IwEvIBzZBhsAFcykFKMqkaWtvQMOGwqLNgwgBUBqE8qOGDi0NKHInrQuABFZoh4IpK2gCsiNFTltY2tpDmFkABHU7g-bwxgkDYiAFp8uBYmexAmtipQvUAMIQDIZNjIZ6hUI-JZQOorACCMCaVHkzXgfgGuXy23mbVoMAyoQotBoMxqYDgqSCNCoADcaJFIWAiDEQPTWowWLBUmBBs5EcxUjBIis8ZcMN5ShR4hhIVKZgN6QUHHlSrh7mw6uCJW0atgNZCMkw0D8pXlKFQmHRkAAOAAMDmwcBuVBdWp1EPOOwc7Hk1BttGQRhAzVKozY8lmvtQGXkny+2TY8Oa2rgADEcOCUfVIWwMRAQKZTEA)

```sh
--parser mdx
```

**Input:**

```mdx
export const textWithIndentation = `

const a = {
  b: 1,
  c: {
    d: 2,
  }
};
`;
```

**Output:**

```mdx
export const textWithIndentation = `

const a = {
b: 1,
c: {
d: 2,
}
};
`;

```

**Expected output:**

```mdx
export const textWithIndentation = `

const a = {
  b: 1,
  c: {
    d: 2,
  }
};
`;
```

**Why?**

Because it should keep indentation in multiline strings.

**Comment by kachkaev** [comment]
👋 @disog! I guess that this bug is a special case of https://github.com/prettier/prettier/issues/12209. Let’s track the issue there.
