### ISSUE TITLE
Give us the option to only apply a plugin on a file

### ISSUE THREAD

**Issue by Nefcanto** [prettier/prettier#16136]
We love Tailwind and we are also interested in `prettier-plugin-tailwind`. Yet we can't use it, because they don't offer their capability outside prettier, and prettier formats our entire codebase when we only want to apply that plugin to sort our classes.

Please add a flag to your CLI command to let us specify a plugin, and only apply the rules/formatting of that plugin on files:

    npx prettier --write src/Components --plugin prettier-plugin-tailwind

**Comment by kachkaev** [comment]
👋 @Nefcanto. Prettier is a printer, it takes the whole file and produces a new formatted version of it. You can skip certain parts of the file via [`// prettier-ignore`](https://prettier.io/docs/en/ignore.html#javascript) but that’s it.

If you want to sort TailwindCSS classes only, try [`eslint-plugin-tailwindcss`](https://www.npmjs.com/package/eslint-plugin-tailwindcss). When you run ESLint, you can choose which rules to apply, so [`tailwindcss/classnames-order`](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/HEAD/docs/rules/classnames-order.md) can be chosen in isolation if needed.

Closing this feature request as out-of-scope for Prettier.
