### ISSUE TITLE
Enforce consistent use of file extensions in import statements

### ISSUE THREAD

**Issue by IgniparousTempest** [prettier/prettier#16131]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEF8BffAMxwnXwB0QA6AektQBs4BaAQyZgBnAB6MA3PSgZseQvgBC5KjTqNW7LtwBG4yZLjCZBSgFcoYGKmj4AosN5YuACkw1MgpITIBKQpPz4OHAwJjhQ+E7+AfgAPAB8UdGxpCwJ4UmxiqmJsdnp3hJQZJIgADQgEJiW0ILIoLw4NADuAAoNCLUovBxNvACeteVaOLxgANbBAMoOcAAyqFBwyJTdgnBDI+NTmKMLAObIMDgm6yBr6KiHx6cGmHA4GAgw3QAq91ANqHCdKxxr5YJ9lwAIomCDwZarU4AKxEkyBcFB4KWSF+-xAAEcwfAWm5OiBeIJuIs4AATMllEBHXicfYAYVo6F4yAJHA4lMBUD2XGIMCOqC0Jhx93mi0hf1OAAsYOgOAB1SWoeCCHZgOCTDpK1AANyVfRZYEEgxA2pOAEkoOTYJMwA8qsRLZMYH0uOL0a4IGs5SNMCzXN97tqluUFms8LjeHsmW7TjscGGWc67oJbagqpTXAsYHLUKSYJLkAAOAAM5SCWNQQQjUeZqKh5WeWhzeYLSAATOUTGsXrwtD96yA4OgtGTyaTZrwuSZI3AAGK4Jl8-Ys3hCiAgMhkIA)

```sh
--parser typescript
```

**Input:**

```tsx
import { A } from "./file-a.tsx";
import { B } from "./file-b";

export function Example(props: {}) {
  return (
    <>
      <A />
      <B />
    </>
  );
}

```

**Output:**

```tsx
import { A } from "./file-a.tsx";
import { B } from "./file-b";

export function Example(props: {}) {
  return (
    <>
      <A />
      <B />
    </>
  );
}

```

**Expected output:**

```tsx
import { A } from "./file-a";
import { B } from "./file-b";

export function Example(props: {}) {
  return (
    <>
      <A />
      <B />
    </>
  );
}
```

**Why?**

I would expect no file extensions in import statement for TypeScript and JavaScript files: A file extension is not required for these imports, and the lack of a rule allows for inconsistent imports, as is demonstrated above. Having the file extension makes the import unnecessarily verbose.

If the maintainers feel that extensions add value, then they should be consistently enforced.

**Comment by kachkaev** [comment]
👋 @IgniparousTempest! Enforcing consistent use of file extensions would be out of Prettier’s scope. See [What Prettier is not concerned about](https://prettier.io/docs/en/rationale#what-prettier-is-_not_-concerned-about) for details.

You can try using [`import/extensions`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md) (or some other rule) in ESLint to solve your problem.
