### ISSUE TITLE
Dependencies required by scripts/build/utils.js are not reflected in package.json

### ISSUE THREAD

**Issue by cryptomilk** [prettier/prettier#16135]
**Environments:**

- Prettier Version: 3.2.5
- Operating System: openSUSE Tumbleweed

**Steps to reproduce:**

I'm currently trying to package prettier for openSUSE Tumbleweed. Distributions require to use as many as possible distribution packages for building packages. Distributions still use yarn 1.22.x, but you ship yarn 4.x as part of the source code. I've tried to get this working for packaging, but I couldn't.

So I used pnpm instead. This seems to reveal some issues.

https://github.com/prettier/prettier/blob/main/scripts/build/config.js seems to check for certain modules to be present required for building, however they are not listed as dependencies in the `package.json` file!

**Expected behavior:**

package.json should require the following modules from config.js:

* @babel/highlight
* @glimmer/util
* @glimmer/wire-format
* debug
* parse-entities
* ts-api-utils
* tslib
* tsutils

**Actual behavior:**

Required dependencies are missing

**Comment by fisker** [comment]
Files in scripts/ are for development, it works perfectly for us, not sure about your use case, there is nothing we can do.
