### ISSUE TITLE
Prettier adding trailing comma after implicit returns and after last param in function call in vue 2 projects

### ISSUE THREAD

**Issue by BoxenOfDonuts** [prettier/prettier#16148]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmpaEAqc2+8AzmXgE5xkBmEbGB8ACasWAdzg4cAOhmkKFVAHpqpJZlwE4JKKqZg2ASywxtOODDIAFDjBgG4bMgF5uvfhaeEywMgE8IAK5sUgBWTAAUAOQwABaBAOYxkQCUZAC+pJBQTBY4EOJsAMowBAEsLpDYAULh4ame3nJkBlxk4QCCbGx4vlIGTJ3dvuFYbBBYTFI5pUzJqcBNFFk5ZHkFAMJ4THAAMv0eZKPjk9MwZVL8WLWnZfVeN5MwEDsQYHhmLxtbcHWLZMkAbiaGXIZBsQXIRwmUxKZ0ez1e712+Qcm22dSBUDSgNImWgKyYASwDjyUHihQcADcDGA4AA5PAYTguBagiiE4lsF5kgCy5jiggZTJoEAA4uYRQB5SkOABiayQbTwABoAEbKsB3NrAFXqsDY4GkLgBKBgOzQMgxPBQMzrK1kn5weZ-bZsam0qYIQThXUa5KkEFKPSGYzaXQwXxmbRSa3CHxgJhMRVPCBkACEBmwvBKsHSqkUOUjWhAypA43N2WQoHYY1ElnYCCYyBA71EPSbpdV3TAAGtzIVGbsDFA4MguO9tp3u32YIUsHgwMP4sgYGwAnBS9sMAYV2uNyA4AAPTmZhAlHB0NhQdj2JtIcc4ScgJhLswARQCEHgY4n+7Ch8KV84A-L9R3vX9SwAR0-eBrGOZstgAWhHOBBFQksQFXPADBwJd1ggDB+AQyQMJfMkzHaWxDFVao4EsBw9hHH9H33GIYAwHAAHUYgMZh51pClsl4gxqQjZsEw7EBKXXABJKA0NgQp9CMGB2nk4oi2Yp8jm2TjuiwZtRjgV0ZQw4dXRgaw8HiIjwJY0t5zYV1m2k0cHMMWBOIMQRYmQAA2AAGUsOGggwOCsmy8C0-cSlVLyfJiZAACZSzKOAaDwVU7wfJ96FVVC0MEHZrXiAJrLgWU3AEJcEOqCAQDSNIgA)

```sh
--parser vue
--print-width 60
```

**Input:**

```vue
<template>
  <p>Templates are formatted as well...
    </p>
</template>

<script>
let Prettier = format => { your.js('though') }
const lowerStatus = computed(() => {
  if (Array.isArray(props.status)) {
    const lowerCaseList = props.status.map((status) => status.toLocaleLowerCase()
    );
  }
  return props.status.toLocaleLowerCase();
});

const superlongServiceName = {
    superLongMethodNameToGetToOverFlow: (a,b,c) => ({a,b,c})
  }
function hanleChange(e) {
    service.send(a,b,c)
}
</script>

<style>
.and { css: too !important }
</style>
```

**Output:**

```vue
<template>
  <p>Templates are formatted as well...</p>
</template>

<script>
let Prettier = (format) => {
  your.js("though");
};
const lowerStatus = computed(() => {
  if (Array.isArray(props.status)) {
    const lowerCaseList = props.status.map((status) =>
      status.toLocaleLowerCase(),
    );
  }
  return props.status.toLocaleLowerCase();
});

const superlongServiceName = {
  superLongMethodNameToGetToOverFlow: (a, b, c) => ({
    a,
    b,
    c,
  }),
};
function hanleChange(e) {
  superlongServiceName.superLongMethodNameToGetToOverFlow(
    a,
    b,
    c,
  );
}
</script>

<style>
.and {
  css: too !important;
}
</style>

```

**Expected output:**

```vue
const lowerStatus = computed(() => {
  if (Array.isArray(props.status)) {
    const lowerCaseList = props.status.map((status) =>
      status.toLocaleLowerCase()
    );
  }
  return props.status.toLocaleLowerCase();
});

const superlongServiceName = {
  superLongMethodNameToGetToOverFlow: (a, b, c) => ({
    a,
    b,
    c
  }),
};
function hanleChange(e) {
  superlongServiceName.superLongMethodNameToGetToOverFlow(
    a,
    b,
    c
  );
}
```

**Why?**
Expected: No comma after `status.toLocaleLowerCase()`, and no comma after `c` in the third param

Causing invalid js syntax to be created on build.
Behavior is different from prettier 2

**Comment by yanapeycheva** [comment]
Hello,
is it possible to contribute to this issue?

**Comment by bakkot** [comment]
This is valid syntax, supported in all reasonably modern environments, and is controlled by [the `--trailing-comma` option](https://prettier.io/docs/en/options.html#trailing-commas), whose value was changed from "es5" to "all" in Prettier 3. If for some reason you still need the ES5 style you can pass `--trailing-comma es5` explicitly.
