### ISSUE TITLE
Cannot read properties of undefined (reading 'languages')

### ISSUE THREAD

**Issue by piszczu4** [prettier/prettier#16155]
I'm getting the error from title when trying to parse `html` using 

```
import prettier from 'prettier/standalone';
import htmlParser from 'prettier/parser-html';


export const formatHTML = async (value: string) =>
  await prettier.format(value, {
    parser: 'html',
    plugins: [htmlParser],
    tabWidth: 2,
    htmlWhitespaceSensitivity: 'strict',
    bracketSpacing: false,
  });
```

Can anyone point what am I doing wrong?

**Comment by fisker** [comment]
Not sure about it, but possibly caused by bundlers, try use namespace import to see if it works.

```diff
import * as prettier from 'prettier/standalone';
import * as htmlParser from 'prettier/parser-html';
```

Or you can log keys of `htmlParser` to see if it's expected.

**Comment by shiroyasha9** [comment]
> Not sure about it, but possibly caused by bundlers, try use namespace import to see if it works.
> 
> ```diff
> - import prettier from 'prettier/standalone';
> + import * as prettier from 'prettier/standalone';
> - import htmlParser from 'prettier/parser-html';
> + import * as htmlParser from 'prettier/parser-html';
> ```
> 
> Or you can log keys of `htmlParser` to see if it's expected.

I was using `turbopack` with `next.js` where the OP's syntax was working fine. 

But on the prod website, since `next.js` uses `webpack` it caused the same issue. 

The suggested fix works great! 🔥
