### ISSUE TITLE
Add an option to optinaly disable changes introduced in 2.3.0

### ISSUE THREAD

**Issue by gdbd** [prettier/prettier#16150]
**Problem**:
After update to latest prettier version from 2.2.1 there are many changes applied to the unchanged code.
it is make dilemma: use old prettier (which has problems it called from api), or apply thousands of changes  to codebase

rollback to 2.2.1 is also unwanted it is not support format mixed type and instance imports 
(example: `import { type CallExpression, stringLiteral } from '@babel/types';`)

After research i am find that these changes started to apply from 2.3.0 version: "Format assignments more consistently"

**Suggested solution**:
Add an configuration option to optionally disable changes introduced in 2.3.0

**Comment by fisker** [comment]
Sorry, but we don't add options. https://prettier.io/docs/en/option-philosophy
