### ISSUE TITLE
Help for manually triggering prettier in vim

### ISSUE THREAD

**Issue by trotzig** [prettier/prettier#1615]
I'm a vim user, and I use prettier on a few of my projects, but not all. The current docs list ways to make prettier run automatically on save (and other `autocmd` events). I need a little better control than that, so I've added a manual keybinding: 

```
nnoremap gp :silent %!prettier --stdin --trailing-comma all --single-quote --print-width 100<CR>
```
(`gp` is mnemonic for `get pretty` 😄 )

I spent quite a while figuring out how to get the right thing to happen. If it's useful to others, I can add something to the README.

**Comment by vjeux** [comment]
That sounds like a good idea, feel free to send a PR for it :)
