### ISSUE TITLE
JS multi-line comments are not formatted when there are spaces between lines that are created with `*`

### ISSUE THREAD

**Issue by babakfp** [prettier/prettier#16151]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOldACAQyJx3yINNRABoQIAHGAS2gGdlQCAnLiAdwAK3BOxQEANnwIBPdrQBGXAmADWcGAGUCAWzgAZJlDjIAZhNZwFS1eo31lhgObIYXAK6WQF7UxfvPcAAe9HBcTLqwEgAqoVDcTHCiZuIWtKxO4nAAim4Q8KbmngBWrIEaGdm5+UjJqSAAjlVwArz0oiAErAC0RnAAJv00IK4ETOJOAMIQ2toEyB3i4kPpUI6ZAIIwrkzybvACoQZGBSmeABYw2uIA6mdM8Kz2YHAaIvdMAG730vNgrHIgD4eACSUAGsA0YDCjHWYI0MGkmROdXovAs1yU9HmqMSoQ+xlohgsXBgLQIjlmyM89i4xPm8gI8jgS1oqMMMGuTD6MDOyAAHAAGWhcOCNJgiskUuY1Qq0GCMznc3lIABMtDcFiijKSspAcG0TL6Az6egIqzc5LgADEIFxZlsnPMCHsICAAL5uoA)

```sh
--parser babel
```

**Input:**

```jsx
/**
* aaa

* aaa
*/
```

**Output:**

```jsx
/**
* aaa

* aaa
*/

```

**Expected output:**

```jsx
/**
 * aaa

 * aaa
*/

```

---

Note: Formatting completely stops working (for inside of that comment only) when a space is added.

**Comment by sosukesuzuki** [comment]
@babakfp Thanks for the report, Prettier does not format comments inside.
