### ISSUE TITLE
prettier formatWithCursor very slowed when use with *.min.js

### ISSUE THREAD

**Issue by onehe2211** [prettier/prettier#16164]
I have an issue:
Use prettier to format the min.js file content, but the problem is that prefromance takes a lot of time if used:
 prettier.formatWithCursor(contentFileMinJS, {
      parser: "babel",
      plugins: [prettierPluginBabel, prettierPluginEstree, prettierPluginHtml],
     cursorOffset: offset
    }),
Is there any way to make formatting speed faster?
please help me.

**Comment by sosukesuzuki** [comment]
Perhaps the minified JS file is huge. Formatting a huge file is time consuming. There may not be an easy solution to this.
