### ISSUE TITLE
If you are using Auto Import - ES6, TS, JSX, TSX extension, try to uninstall it and replace it with Auto Import.

### ISSUE THREAD

**Issue by SudiptaAdhikaryJoy** [prettier/prettier#16162]
If you are using Auto Import - ES6, TS, JSX, TSX extension, try to uninstall it and replace it with Auto Import.

![image](https://github.com/prettier/prettier-vscode/assets/29030165/d7749ada-78e0-44de-971e-e95e189fbc0b)
![image](https://github.com/prettier/prettier-vscode/assets/29030165/66bee744-15d1-48ac-b123-4bc992f405ac)

https://github.com/prettier/prettier-vscode/issues/1333#issuecomment-905404600

_Originally posted by @lawrence-cruz in https://github.com/prettier/prettier-vscode/issues/2999#issuecomment-1548740128_

**Comment by SudiptaAdhikaryJoy** [comment]
Whenever i installed these two extension one time together that occurs vs code laggy. You can not load prettier and can save any file. So, i recommend remove or uninstall **Auto Import - ES6, TS, JSX, TSX** extension.

**Comment by alexander-akait** [comment]
Sorry, wrong repo
