### ISSUE TITLE
Support top level return statement

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#1616]
It is valid in CJS, and it happens also to be used in [quite popular modules](https://github.com/substack/node-browserify/blob/89809c37e8d8cd4d54beb5b6efec18ab20f7d49f/bin/cmd.js#L42)

Currently prettier crashes when such CJS file is provided for formatting:
```javascript
var foo = [
  "bar"
];
return;
```

Results with `SyntaxError: 'return' outside of function (4:0)`

**Comment by k15a** [comment]
I think this is already fixed: https://github.com/prettier/prettier/pull/1608

**Comment by medikoo** [comment]
Sorry for noise, when do you think it'll be published?

**Comment by vjeux** [comment]
I'm in vacation this week, I'll do a release next week
