### ISSUE TITLE
Prettier breaks Markdown alert syntax

### ISSUE THREAD

**Issue by babakfp** [prettier/prettier#16193]
https://github.com/orgs/community/discussions/16925

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA+ABAbQIQDkDyAKgKIC6AOlBgFTUBCEANgCa1LoAScjjEANOgDqEAE4tslEHxAQADjACW0AM7JQAQxEiIAdwAKmhKpTrGO9QE9V0gEYj1YANZwYAZXUBbOABkFUOMgAZqbKcLb2Ti6usg5+AObIMCIArmEgoR4KiSlpcAAesnAiCl6wpoRFUJoKcMbBjKHSyvGMcACKyRDwQSFpAFbKea4t7Z3dSPWNIACOY3B62rLGIOrKALT+cMxbUiBJ6gqM8QDCEB4e6sgrPLvNUHGtAIIwSQo2yfB6Rb7+PQ1pAAsYB5GIIAQp4MoYmA4K4jBCFAA3CEWK5gZTWECI1IASSg21grjAxXkj3xrhgFlafymsm0oUE9lkVzptSKiIC0j8oREMAW6jiFxpaRiIh5VwuIkczF0UF2dL8MEECmYMAByAAHAAGaQiOCzBR6-mCy4TXrSGDqGzK1XqpAAJmkyVChCtdXNIDgHhsW22zG86nuyQFcAAYqILi94ld1B8ICAAL4JoA)

```sh
--parser markdown
```

**Input:**

```markdown
> [!NOTE]
> **Bold**: Hello, World!

```

**Output:**

```markdown
> [!NOTE] > **Bold**: Hello, World!

```

**Expected output:**
The same as input.

**More info**

This issue doesn't happen if I remove `**Documentation**: `.

**Comment by pozil** [comment]
I'm having the same formatting issue with this:
```md
> [!NOTE]
> `hello()` is called in two places....
```

**Comment by kachkaev** [comment]
👋 @babakfp! This issue is tracked in https://github.com/prettier/prettier/issues/13953, let’s continue the discussion there.
