### ISSUE TITLE
`printDocToString` with `useTabs` prints a tab for `align`, instead of a space

### ISSUE THREAD

**Issue by josephfrazier** [prettier/prettier#1619]
While I was working on https://github.com/prettier/prettier/pull/1609, I tried adding a test with `useTabs: true` after commit https://github.com/prettier/prettier/pull/1609/commits/ee94a375278c2db89b0e857b7e95c5056c3605ff. I noticed that it it inserted an extra tab instead of a space, then reduced the test case and found that the same behavior happens on master. To demonstrate, run this code in a prettier checkout:

```js
console.log(require('./src/doc-printer.js').printDocToString({
  "type": "align",
  "contents": {
    "type": "indent",
    "contents": {
      "type": "concat",
      "parts": [
        {
          "type": "concat",
          "parts": [
            {
              "type": "line",
              "hard": true
            },
            {
              "type": "break-parent"
            }
          ]
        },
        "2"
      ]
    }
  },
  "n": 1
}, {
  useTabs: true,
  printWidth: 80
}))
```

In the output, there should be 1 tab and 1 space before the `2` (one the same line) because there is 1 `indent` in the doc, and one `align` with n=1, but there are 2 tabs.

**Comment by josephfrazier** [comment]
Oops, the problem may not be with `printDocToString` itself. Rather, since [this code](https://github.com/prettier/prettier/blob/4e9cdc413c923d873ae0d2a033e0159646ccd88c/src/printer.js#L1680-L1688) puts `align`s outside `indent`s, it generates docs like the one I pasted above when there are an odd number of spaces. Swapping the two as shown in the diff below doesn't seem to help:

```diff
diff --git a/src/printer.js b/src/printer.js
index c578b58e..facb0203 100644
--- a/src/printer.js
+++ b/src/printer.js
@@ -4267,12 +4267,12 @@ function printAstToDoc(ast, options, addAlignmentSize) {
 function addAlignmentToDoc(doc, size, tabWidth) {
   let aligned = removeLines(doc);
   if (size > 0) {
+    // Use align for all the spaces that are needed
+    aligned = align(size % tabWidth, aligned);
     // Use indent to add tabs for all the levels of tabs we need
     for (var i = 0; i < Math.floor(size / tabWidth); ++i) {
       aligned = indent(aligned);
     }
-    // Use align for all the spaces that are needed
-    aligned = align(size % tabWidth, aligned);
     // size is absolute from 0 and not relative to the current
     // indentation, so we use -Infinity to reset the indentation to 0
     aligned = align(-Infinity, aligned);
```

**Comment by rhengles** [comment]
Yes, it is intended that `align()` outputs one tab character when `useTabs` is enabled, see #1026

**Comment by josephfrazier** [comment]
Thanks for clarifying, @rhengles, and for all your work on `useTabs`! It looks like this sort of situation might only arise when a code snippet that uses "tabs for indenting, spaces for alignment" is formatted, and the user also expects the "spaces for alignment" to be preserved. Since this is a pretty rare edge case that can only arise once https://github.com/prettier/prettier/pull/1609 is merged, I'll go ahead and close this issue.
