### ISSUE TITLE
Still the error "Error: Comment "Hello" was not printed. Please report this error!" even though I have added a comment in the Doc.

### ISSUE THREAD

**Issue by nurulakbaral** [prettier/prettier#16217]
**Prettier 3.2.5**

```sh
# Options (if any):
{
  "semi": false,
  "trailingComma": "all",
  "singleQuote": true,
  "printWidth": 120,
  "tabWidth": 2,
  "jsxSingleQuote": true,
  "plugins": ["./plugin.js"]
}
```

**Input:**

```jsx
import * as React from 'react'

export default function Component() {
  return (
    // Hello
    <div>
      <h1></h1>
      <h2></h2>
    </div>
  )
}

```

**Expected output:**

```jsx
import * as React from 'react'

export default function Component() {
  return (
    // Hello
    <div>
      <h1></h1>

      <h2></h2>
    </div>
  )
}

```

**Why?**

I created a Prettier Plugin, but the error always appears like this "Error: Comment "Hello" was not printed. Please report this error!". I even attached the comments manual in my Docs. Like this:

```jsx
      print(path, options, print) {
        let node = path.getNode()

        if (node.type === 'ReturnStatement') {
          if (Array.isArray(node.argument.children)) {
            if (node.argument.children.length > 2) {
              let children = node.argument.children.filter(child => child.type !== 'JSXText')
              let childrenWithHardLine = children.map((child, idx) => {
                return [
                  path.call(
                    print,
                    'argument',
                    'children',
                    node.argument.children.indexOf(child)
                  ),
                  idx === children.length - 1 ? [] : [hardline, hardline]
                ]
              })

              return group([
                'return', 
                ' ',
                group([
                  ifBreak('('),
                  indent([
                    softline,
                    "// Hello", <-- ATTACH MANUALLY, BUT STILL ERROR.
                    hardline,
                    group([
                      group([path.call(print, 'argument', 'openingElement')]),
                      indent([
                        hardline, 
                        group([...childrenWithHardLine.flat()])
                      ]),
                      hardline,
                      [path.call(print, 'argument', 'closingElement')]
                    ]),
                  ]),
                  softline,
                  ifBreak(')'),
                ]),
                ';'
              ])
            }
          }
        }
}

```

**Comment by fisker** [comment]
You need mark the comment is printed

https://github.com/prettier/prettier/blob/df998cd459d9bd87517effbf802011fbb0dac344/src/main/comments/print.js#L25

**Comment by nurulakbaral** [comment]
> You need mark the comment is printed
> 
> https://github.com/prettier/prettier/blob/df998cd459d9bd87517effbf802011fbb0dac344/src/main/comments/print.js#L25

```jsx
import { printers } from 'prettier/plugins/estree'

/** @type {Prettier.Printer} */
let estreePrinter = printers['estree']
estreePrinter.printComment(path, options) // Error
```

Still got error @fisker :
Error: Not a comment: {"type":"File","start":0,"end":121,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":10,"column":0,"index":121}},"range":[0,121],"errors":[],"program":{"type":"Program","start":0,"end":121,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":10,"column":0,"index":121}},"range":[0,121],"sourceType":"module","interpreter":null,"body":[{"type":"ExportNamedDeclaration","start":0,"end":120,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":9,"column":1,"index":120}},"range":[0,120],"specifiers":[],"source":null,"declaration":{"type":"FunctionDeclaration","start":7,"end":120,"loc":{"start":{"line":1,"column":7,"index":7},"end":{"line":9,"column":1,"index":120}},"range":[7,120],"id":{"type":"Identifier","start":16,"end":25,"loc":{"start":{"line":1,"column":16,"index":16},"end":{"line":1,"column":25,"index":25},"identifierName":"Component"},"range":[16,25],"name":"Component"},"generator":false,"async":false,"params":[],"body":{"type":"BlockStatement","start":28,"end":120,"loc":{"start":{"line":1,"column":28,"index":28},"end":{"line":9,"column":1,"index":120}},"range":[28,120],"body":[{"type":"ReturnStatement","start":32,"end":118,"loc":{"start":{"line":2,"column":2,"index":32},"end":{"line":8,"column":3,"index":118}},"range":[32,118],"argument":{"type":"JSXElement","start":58,"end":114,"loc":{"start":{"line":4,"column":4,"index":58},"end":{"line":7,"column":10,"index":114}},"range":[58,114],"openingElement":{"type":"JSXOpeningElement","start":58,"end":63,"loc":{"start":{"line":4,"column":4,"index":58},"end":{"line":4,"column":9,"index":63}},"range":[58,63],"name":{"type":"JSXIdentifier","start":59,"end":62,"loc":{"start":{"line":4,"column":5,"index":59},"end":{"line":4,"column":8,"index":62}},"range":[59,62],"name":"div"},"attributes":[],"selfClosing":false},"closingElement":{"type":"JSXClosingElement","start":108,"end":114,"loc":{"start":{"line":7,"column":4,"index":108},"end":{"line":7,"column":10,"index":114}},"range":[108,114],"name":{"type":"JSXIdentifier","start":110,"end":113,"loc":{"start":{"line":7,"column":6,"index":110},"end":{"line":7,"column":9,"index":113}},"range":[110,113],"name":"div"}},"children":[{"type":"JSXText","start":63,"end":70,"loc":{"start":{"line":4,"column":9,"index":63},"end":{"line":5,"column":6,"index":70}},"range":[63,70],"extra":{"rawValue":"\n      ","raw":"\n      "},"value":"\n      "},{"type":"JSXElement","start":70,"end":83,"loc":{"start":{"line":5,"column":6,"index":70},"end":{"line":5,"column":19,"index":83}},"range":[70,83],"openingElement":{"type":"JSXOpeningElement","start":70,"end":76,"loc":{"start":{"line":5,"column":6,"index":70},"end":{"line":5,"column":12,"index":76}},"range":[70,76],"name":{"type":"JSXIdentifier","start":71,"end":75,"loc":{"start":{"line":5,"column":7,"index":71},"end":{"line":5,"column":11,"index":75}},"range":[71,75],"name":"span"},"attributes":[],"selfClosing":false},"closingElement":{"type":"JSXClosingElement","start":76,"end":83,"loc":{"start":{"line":5,"column":12,"index":76},"end":{"line":5,"column":19,"index":83}},"range":[76,83],"name":{"type":"JSXIdentifier","start":78,"end":82,"loc":{"start":{"line":5,"column":14,"index":78},"end":{"line":5,"column":18,"index":82}},"range":[78,82],"name":"span"}},"children":[]},{"type":"JSXText","start":83,"end":90,"loc":{"start":{"line":5,"column":19,"index":83},"end":{"line":6,"column":6,"index":90}},"range":[83,90],"extra":{"rawValue":"\n      ","raw":"\n      "},"value":"\n      "},{"type":"JSXElement","start":90,"end":103,"loc":{"start":{"line":6,"column":6,"index":90},"end":{"line":6,"column":19,"index":103}},"range":[90,103],"openingElement":{"type":"JSXOpeningElement","start":90,"end":96,"loc":{"start":{"line":6,"column":6,"index":90},"end":{"line":6,"column":12,"index":96}},"range":[90,96],"name":{"type":"JSXIdentifier","start":91,"end":95,"loc":{"start":{"line":6,"column":7,"index":91},"end":{"line":6,"column":11,"index":95}},"range":[91,95],"name":"span"},"attributes":[],"selfClosing":false},"closingElement":{"type":"JSXClosingElement","start":96,"end":103,"loc":{"start":{"line":6,"column":12,"index":96},"end":{"line":6,"column":19,"index":103}},"range":[96,103],"name":{"type":"JSXIdentifier","start":98,"end":102,"loc":{"start":{"line":6,"column":14,"index":98},"end":{"line":6,"column":18,"index":102}},"range":[98,102],"name":"span"}},"children":[]},{"type":"JSXText","start":103,"end":108,"loc":{"start":{"line":6,"column":19,"index":103},"end":{"line":7,"column":4,"index":108}},"range":[103,108],"extra":{"rawValue":"\n    ","raw":"\n    "},"value":"\n    "}],"leadingComments":[{"type":"CommentLine","value":" Hello","start":45,"end":53,"loc":{"start":{"line":3,"column":4,"index":45},"end":{"line":3,"column":12,"index":53}},"placement":"ownLine","leading":true,"trailing":false,"printed":false,"nodeDescription":"JSXElement"}],"extra":{"parenthesized":true},"comments":[{"type":"CommentLine","value":" Hello","start":45,"end":53,"loc":{"start":{"line":3,"column":4,"index":45},"end":{"line":3,"column":12,"index":53}},"placement":"ownLine","leading":true,"trailing":false,"printed":false,"nodeDescription":"JSXElement"}]}}],"directives":[]}}}],"directives":[]},"tokens":[{"type":{"label":"export","keyword":"export","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"export","start":0,"end":6,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":1,"column":6,"index":6}}},{"type":{"label":"function","keyword":"function","beforeExpr":false,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"function","start":7,"end":15,"loc":{"start":{"line":1,"column":7,"index":7},"end":{"line":1,"column":15,"index":15}}},{"type":{"label":"name","beforeExpr":false,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"Component","start":16,"end":25,"loc":{"start":{"line":1,"column":16,"index":16},"end":{"line":1,"column":25,"index":25}}},{"type":{"label":"(","beforeExpr":true,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":25,"end":26,"loc":{"start":{"line":1,"column":25,"index":25},"end":{"line":1,"column":26,"index":26}}},{"type":{"label":")","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":26,"end":27,"loc":{"start":{"line":1,"column":26,"index":26},"end":{"line":1,"column":27,"index":27}}},{"type":{"label":"{","beforeExpr":true,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null},"start":28,"end":29,"loc":{"start":{"line":1,"column":28,"index":28},"end":{"line":1,"column":29,"index":29}}},{"type":{"label":"return","keyword":"return","beforeExpr":true,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"return","start":32,"end":38,"loc":{"start":{"line":2,"column":2,"index":32},"end":{"line":2,"column":8,"index":38}}},{"type":{"label":"(","beforeExpr":true,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":39,"end":40,"loc":{"start":{"line":2,"column":9,"index":39},"end":{"line":2,"column":10,"index":40}}},{"type":"CommentLine","value":" Hello","start":45,"end":53,"loc":{"start":{"line":3,"column":4,"index":45},"end":{"line":3,"column":12,"index":53}},"placement":"ownLine","leading":true,"trailing":false,"printed":false,"nodeDescription":"JSXElement"},{"type":{"label":"jsxTagStart","beforeExpr":false,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null},"start":58,"end":59,"loc":{"start":{"line":4,"column":4,"index":58},"end":{"line":4,"column":5,"index":59}}},{"type":{"label":"jsxName","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"div","start":59,"end":62,"loc":{"start":{"line":4,"column":5,"index":59},"end":{"line":4,"column":8,"index":62}}},{"type":{"label":"jsxTagEnd","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":62,"end":63,"loc":{"start":{"line":4,"column":8,"index":62},"end":{"line":4,"column":9,"index":63}}},{"type":{"label":"jsxText","beforeExpr":true,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"\n      ","start":63,"end":70,"loc":{"start":{"line":4,"column":9,"index":63},"end":{"line":5,"column":6,"index":70}}},{"type":{"label":"jsxTagStart","beforeExpr":false,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null},"start":70,"end":71,"loc":{"start":{"line":5,"column":6,"index":70},"end":{"line":5,"column":7,"index":71}}},{"type":{"label":"jsxName","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"span","start":71,"end":75,"loc":{"start":{"line":5,"column":7,"index":71},"end":{"line":5,"column":11,"index":75}}},{"type":{"label":"jsxTagEnd","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":75,"end":76,"loc":{"start":{"line":5,"column":11,"index":75},"end":{"line":5,"column":12,"index":76}}},{"type":{"label":"jsxTagStart","beforeExpr":false,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null},"start":76,"end":77,"loc":{"start":{"line":5,"column":12,"index":76},"end":{"line":5,"column":13,"index":77}}},{"type":{"label":"/","beforeExpr":true,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":10,"updateContext":null},"value":"/","start":77,"end":78,"loc":{"start":{"line":5,"column":13,"index":77},"end":{"line":5,"column":14,"index":78}}},{"type":{"label":"jsxName","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"span","start":78,"end":82,"loc":{"start":{"line":5,"column":14,"index":78},"end":{"line":5,"column":18,"index":82}}},{"type":{"label":"jsxTagEnd","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":82,"end":83,"loc":{"start":{"line":5,"column":18,"index":82},"end":{"line":5,"column":19,"index":83}}},{"type":{"label":"jsxText","beforeExpr":true,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"\n      ","start":83,"end":90,"loc":{"start":{"line":5,"column":19,"index":83},"end":{"line":6,"column":6,"index":90}}},{"type":{"label":"jsxTagStart","beforeExpr":false,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null},"start":90,"end":91,"loc":{"start":{"line":6,"column":6,"index":90},"end":{"line":6,"column":7,"index":91}}},{"type":{"label":"jsxName","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"span","start":91,"end":95,"loc":{"start":{"line":6,"column":7,"index":91},"end":{"line":6,"column":11,"index":95}}},{"type":{"label":"jsxTagEnd","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":95,"end":96,"loc":{"start":{"line":6,"column":11,"index":95},"end":{"line":6,"column":12,"index":96}}},{"type":{"label":"jsxTagStart","beforeExpr":false,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null},"start":96,"end":97,"loc":{"start":{"line":6,"column":12,"index":96},"end":{"line":6,"column":13,"index":97}}},{"type":{"label":"/","beforeExpr":true,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":10,"updateContext":null},"value":"/","start":97,"end":98,"loc":{"start":{"line":6,"column":13,"index":97},"end":{"line":6,"column":14,"index":98}}},{"type":{"label":"jsxName","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"span","start":98,"end":102,"loc":{"start":{"line":6,"column":14,"index":98},"end":{"line":6,"column":18,"index":102}}},{"type":{"label":"jsxTagEnd","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":102,"end":103,"loc":{"start":{"line":6,"column":18,"index":102},"end":{"line":6,"column":19,"index":103}}},{"type":{"label":"jsxText","beforeExpr":true,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"\n    ","start":103,"end":108,"loc":{"start":{"line":6,"column":19,"index":103},"end":{"line":7,"column":4,"index":108}}},{"type":{"label":"jsxTagStart","beforeExpr":false,"startsExpr":true,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null},"start":108,"end":109,"loc":{"start":{"line":7,"column":4,"index":108},"end":{"line":7,"column":5,"index":109}}},{"type":{"label":"/","beforeExpr":true,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":10,"updateContext":null},"value":"/","start":109,"end":110,"loc":{"start":{"line":7,"column":5,"index":109},"end":{"line":7,"column":6,"index":110}}},{"type":{"label":"jsxName","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"value":"div","start":110,"end":113,"loc":{"start":{"line":7,"column":6,"index":110},"end":{"line":7,"column":9,"index":113}}},{"type":{"label":"jsxTagEnd","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":113,"end":114,"loc":{"start":{"line":7,"column":9,"index":113},"end":{"line":7,"column":10,"index":114}}},{"type":{"label":")","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":117,"end":118,"loc":{"start":{"line":8,"column":2,"index":117},"end":{"line":8,"column":3,"index":118}}},{"type":{"label":"}","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null},"start":119,"end":120,"loc":{"start":{"line":9,"column":0,"index":119},"end":{"line":9,"column":1,"index":120}}},{"type":{"label":"eof","beforeExpr":false,"startsExpr":false,"rightAssociative":false,"isLoop":false,"isAssign":false,"prefix":false,"postfix":false,"binop":null,"updateContext":null},"start":121,"end":121,"loc":{"start":{"line":10,"column":0,"index":121},"end":{"line":10,"column":0,"index":121}}}],"printed":true}
