### ISSUE TITLE
Markdown undesirable formatting behaviour when new text added to paragraph

### ISSUE THREAD

**Issue by ncasdpo** [prettier/prettier#16223]
In a markdown file, if you have written out a new single line of text, the lorem ipsum paragraph in the recorded example, the formatting is fine.

But when you add text into the middle of the paragraph, the line breaks from the initial formatting will be kept instead of reformatting the whole paragraph again. Please see the screen recording here:
https://github.com/prettier/prettier/assets/153771236/6fd827b2-2e20-47df-88a0-2a62381ca0d2

**Comment by sosukesuzuki** [comment]
Can follow the issue template?

**Comment by kachkaev** [comment]
> I did try to use the playground to reproduce the error, but I couldn't see how to format the file.

@ncasdpo you need to set `--prose-wrap` in the Playground:

<img src=https://github.com/prettier/prettier/assets/608862/20877bed-067e-4bbc-8507-a803e4bfdee1 width=300>

<br/>
<br/>
<br/>
<br/>
<br/>

Here is what I tried:

## Initial formatting

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCAnOBbABASwAcBnAVzwBMIAbTXY-GXAQ2zhgBpdIpi4x4MUhhYUi+YmHxQA5rjjVGXPhVxV5+UsWwRV8bITrSpYiqVi5STaswBGmOPKZVaWXNmYyozFooCOpMwAdLgAqkwI+HjMqtjSUbgAbpGsXAESuFAQxDAYpKpwAB5wGFIwzDD40JbUNtiQuDb2GBlQEviWTMz+pETyhfI+kNg66jx8ARUhACK9xCxWjvh5bi5GULhYhFgAFggUJYwEG4k0pITl8EkKR3DEfNz4teRqNA7ypLgAZqQy+BWZUi1HyEZgtCrCEIAUUKYDgFzgwno0iYEDAYGY-ABYHO+AoFQBWQ22wgeIQnHo5iY0m4QNBuHSuAgXy++CkPgOfDyFh0tSOzDaeDx8hyjTsmHIQRAHBAEAuVV4yFAYIwEAA7gAFMEIYjIEDdNXMACeupltgwzDAAGt2ABlVhwVDSODIL7dPhmi3Wu2gqSyZC5UhwGV8OIBvLBkBFQiHNiwboAFRK3had1d7sjDFk1DgAEVSBB4OnqB6QAArYiFW3SGQ5-OFl1IN0lyMBBsa1UkPXMYgAWigcDgBwo0pAuWYTxrAGEICNmN3aqOs7W4ABBGC5fC2RYakpOgfF0s7GDYagAdR2jDuvrgtp1jHwiUYRr1YHuo8SQYAklADrBbWALQXKuv62jARo5oekYknwZ4WoQC6Giao7SFyMAdp4HhQTKoIYFyeoeBgVpUGqUCjtsKJnniMA7MgAAcAAMMpYOkWAYTIWFNhmMrlLYVEUDRyAAEwylocAJnYupcS2Mo4LYQ7DqgAoyIEMhwAAYpgHgbjW3ZWBAIAAL6GUAA)

```sh
--parser markdown
--prose-wrap always
```

**Input:**

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

**Output:**

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.

```


## Edit in the middle of the paragrpah

I copied the result into the left column and added a few `asdf`s on line 3:

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCAnOBbABASwAcBnAVzwBMIAbTXY-GXAQ2zhgBpdIpi4x4MUhhYUi+YmHxQA5rjjVGXPhVxV5+UsWwRV8bIUwAdKNKliKpWLlJNqzAEaY48plVpZc2ZjKjMWigCOpMwAdLgAqkwI+HjMqtjSsbgAbjGsXMESJszEFABmLHmFuQVFZaUlxeVVFdWVuFAQxDAYpKpwAB5wGFIwzDD40DbU9tiQuPZOGBKNEvg2TMxBpETynfL+kNg66jx8wQOhJgAiq8Qsti74bZ7udNK4WIRYABYIFD2MBFCpNKSEfrwVIKb5wYh8bj4UbkNQ0ZzyUgmfKkGT4AaNUijfyEZgzAbCcIAUU6YDggLgwno0iYEDAYGY-AxYAB+AoAwxTV+LwgbIQnHoViY0hMLOouNwWVwEHy+XwUn8nz4bWsOlG32YpjwbPkLUmjkw5GOUBAHBAEEBQ14yFAeIwEAA7gAFPEIYjIEDLB3MACe7rNDgwzDAAGt2ABlVhwVDSODIfLLPgBoOhiO4qSyZCtUhwM18RJZtq5kBdQhfNiwZYAFR6fhm4PjieLDFk1DgAEVSBB4I3qEmQAArYidcPSGRtzvduNIBN94vBKdO+0kD25AC0UDgcE+FFNIFazGhY4AwhAdsxV6M9y3x3AAIIwVr4BxXJ09GOb3v914wbDUADqryMOC6ZwOGbqMPgKSMD6HpgBCe4pDmACSUCfLA4ZgDMgJ3mh4YwD6bZfsWPJ8P+QaEJe3p+nu0jKjAS4+N4xFmriGDKh63gYCGVAOiarEzLA-5sjArzIAAHAADGaWBZFgjEyMxM5Nma-QOMJFCicgABMZpaHAVaOO6ylzmaOAONuO6oJqMghDIcAAGKYN4j5jqutgQCAAC+XlAA)

```sh
--parser markdown
--prose-wrap always
```

**Input:**

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.

```

**Output:**

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis asdf
asdf asdf asdf asdf asdf asdf asdf asdf asdf nostrud exercitation ullamco
laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
deserunt mollit anim id est laborum.

```

The result looks correct.

Can you please check if you are using Prettier in your editor or if it’s some other formatter that you run there? Prettier should behave the same way as in the Playground.
