### ISSUE TITLE
Github Actions for Node.js 14 x MacOS fails

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#16248]
GitHub Actions has changed to use M1 machines for `macos-latest`. [^1] [^2]
`actions/setup-node` cannot get a build of Node.js 14 for arm, so our CI is currently failing.

```
Attempting to download 14...
Not found in manifest. Falling back to download directly from Node
Error: Unable to find Node version '14' for platform darwin and architecture arm64.
```

[^1]: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
[^2]: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

**Comment by jsoref** [comment]
Wouldn't it make more sense to just drop support for node 14?

https://endoflife.date/nodejs
> 14 (LTS)
> Ended 1 year ago
(30 Apr 2023)

**Comment by sosukesuzuki** [comment]
It needs to be at least a major upgrade

**Comment by jsoref** [comment]
Do you try to queue all breaking updates together?

**Comment by sosukesuzuki** [comment]
Sorry, I don't understand your question. we are not ready for a major upgrade yet, until then we should keep testing macos x Node.js 14.

**Comment by jsoref** [comment]
That is the answer -- you apparently collect lots of breaking updates together and ship them out as one major upgrade.
