### ISSUE TITLE
SyntaxError: yield is a reserved word

### ISSUE THREAD

**Issue by msageryd** [prettier/prettier#1624]
I get **"SyntaxError: yield is a reserved word"** from Prettier. 

The function is a generator function used in a ReduxSaga:

    function* saveUnsavedJournalItemsToServer() {
      const journalItemsToSave = yield select(selectCompletedUnsavedJournalItems);
      journalItemsToSave.map(journalItem => {
        yield call(saveJournalItemToServer, journalItem);
      });
    }

Here is the complete output.

    journalSagas.js: SyntaxError: yield is a reserved word (177:4)
      175 |
      176 |   journalItemsToSave.map(journalItem => {
    > 177 |     yield call(saveJournalItemToServer, journalItem);
          |     ^
      178 |   });
      179 | }
      180 |

Is this a Prettier bug, or is my code flawed?

**Comment by k15a** [comment]
You call yield in a normal function but it is only allowed in a generator. I might be wrong but I think the correct code is:

```js
function* saveUnsavedJournalItemsToServer() {
  const journalItemsToSave = yield select(selectCompletedUnsavedJournalItems);
  yield* journalItemsToSave.map(function* (journalItem) {
    yield call(saveJournalItemToServer, journalItem);
  });
}
```

**Comment by msageryd** [comment]
Ah, thanks.
That makes sense. Didn't see that I wrapped it in a normal function.

So, Prettier did a good job catching the problem. Maybe a better error message would be good, if possible.

**Comment by k15a** [comment]
That's the error message from either babel or flow because prettier uses them to parse your code. :)

If you want to learn more about generators take a look at http://exploringjs.com/es6/ch_generators.html

**Comment by msageryd** [comment]
Thanks again.
You guessed it: I'm a generator newbie =)

I'll read up some more on the subject. Also, the "yield call" will probably make funny stuff happen. I have now changed to "yield fork".

**Comment by msageryd** [comment]
This is maybe a rare occation where a good old for-loop comes in handy (instead of map or each). No messing around with nested generators needed.

**Comment by vjeux** [comment]
The error message is indeed super confusing. If you could open an issue on babylon and flow projects to get it improved that would be awesome!

**Comment by msageryd** [comment]
https://github.com/babel/babylon/issues/530
