### ISSUE TITLE
Broken identation: "this" in function paramater signature

### ISSUE THREAD

**Issue by sequencerr** [prettier/prettier#16265]
**Prettier 3.2.5**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAiHMoTGGzhcAJmIkTUNODC7kwlLgCcAzisEgAqvgBiAWgAcQ8gHp5MRctXkoXZQYBuASzgB3AA4QWg4g6tDwsAa+XjIwlPwycN5gcGbRsZQANOReUF4wXlx0ZjpgRXD8AIwAdAAM1nYsCpIFMHRwDJgQYACuyrCoNq3t9oqlWl7+MKMOMOQAZj1QYAXQ5Fw6MgAUcV46AJTkwE2zEuTnF5cXkFA6c2r85JUATADMJ81XX+c3OhDt1ToEF4W32H1m30h31+-zggOBoPBZyhKNRMC0AE8jk1xKc5qiCd8AL7qLgwDTkLZwQ7HXGfQkMq4wgFwLRaIJUsF0iGMxlEpEwflQFHNZHQ6B-AFAkFc0UwRbLVbCjYyZ6g7HcuW-e7kR4vd6avHMuHSxGG5rG+EygXNdFY2ly5oksrkyiU6kax08n4S2HVVnsrScm2zIVysOzQbjSbTE6DSjSOQseO0RgsECZEAQKZeCXIUDadm+YjaBA6ZAgIq+LgY8uZgBGWi4YAA1ioAMpuOAAGVycGQ8yKegbTdbHf8zdyvGQ6J6cEzehoXhnWjnmbgAA9-KyvP1VHR8KzXBM4OWkIO6MOQDop+0AIo9CDwAdD+cgABWOg37dvcAfT-7c9X0zABHR94GIdl-DPSsdDMKA4DgRIZAzEB0S4Lw6CnXAIBoGguArIo6FQm8+HaABBGB0S8esegg1lewQl9Lzfdg6AAdUofJTwnFJ2zLfIvG8GAMQrMAdDrEAPDnABJKBElgdswAmKZyPk9sRPaZir38dk9HYpt-ArXTT1ZDx+0zXI9GCSCuF4fDtLfCddFZCs2NQ3TchgdiYjiZALFqTMtDgMCvGC2z7IIoCWMzVR6x8jJkAAFkzHo9HwLh6zPWc3zgGh6yQ5Dux4XgejsuATCCfCqKnQi6IgEAiSJIA

**Comment by fisker** [comment]
Please  follow the issue template.

**Comment by sequencerr** [comment]
@fisker Do I follow it now?

**Comment by fisker** [comment]
There is a checkbox on left side `rethrow embed errors`, as you can see your code in `<script>` is not valid JavaScript code.

**Comment by sequencerr** [comment]
https://github.com/prettier/prettier-vscode probably
