### ISSUE TITLE
Parentheses missing with `await` and `typescript` parser

### ISSUE THREAD

**Issue by edemaine** [prettier/prettier#16288]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAhgd3QSxgAg2z3wDM4YwALVASloDoArAZ2jsdIghABoQIABxg5oLZKHQAnKREwAFaQnEp0AG2wBPcfwBGU9GADWFAMroAtnAAyOKHGSl1LOHoPGzgw3YDmyGFIArq4gLhY4-kEhcAAegnBSOFaw6gAqCVDSOHAqTmou-Cy+anAAioEQ8I7OIawxpsVlFVVIeQUgAI7NcPKygiog6CwAtPZwACYTfCABuGq+AMIQFhboyINqatNFUD4lAIIwATi6gfDyCbb21fkhVDAWagDqVHg5XmBwpsp4OABueE06zALB0ID+wQAklBJrBTGBEsJ9jDTDBNCUbu1BLIXE8DIJ1ticgk-g5+HYXFIYL10D5VpiQl4pJT1mj4iwEThhNNsXYYE8cOMYFRkAAOAAM-CkcC6OGlNLpa1aNX4MHQugFQpFSAATPxAi5UurciqQHALLoJpNxtZ0LtArS4AAxCBSVZHXzrdBnHgAX19QA)

```sh
--parser typescript
```

**Input:**

```tsx
(await (await fetch()).json()).foo
```

**Output:**

```tsx
await(await fetch()).json().foo;

```

**Expected output:**

```tsx
(await (await fetch()).json()).foo
```

**Why?**

The parentheses are necessary to `await` the `.json()` response.

For comparison, [it works fine with the `babel` parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAhgd3QSxgAg2z3wDM4YwALVASloDoArAZ2jsdIghABoQIABxg5oLZKHQAnKREwAFaQnEp0AG2wBPcfwBGU9GADWFAMroAtnAAyOKHGSl1LOHoPGzgw3YDmyGFIArq4gLhY4-kEhcAAegnBSOFaw6gAqCVDSOHAqTmou-Cy+anAAioEQ8I7OIawxpsVlFVVIeQUgAI7NcPKygiog6CwAtPZwACYTfCABuGq+AMIQFhboyINqatNFUD4lAIIwATi6gfDyCbb21fkhVDAWagDqVHg5XmBwpsp4OABueE06zALB0ID+wQAklBJrBTGBEsJ9jDTDBNCUbu1BLIXE8DIJ1ticgk-g5+HYXFIYL10D5VpiQl4pJT1rp0Lo4Ft+Ni7DAnjhxjAqMgABwABn4UjgXRwUppdLWrRq-Bg7P5guFSAATPxAi5UuzcsqQHALBzxpNxtZ0LtArS4AAxCBSVZHXzrdBnHgAX29QA). (Is the `typescript` parser deprecated? I don't think so.)

I found a [very old similar bug](https://github.com/prettier/prettier/issues/239). Also [an active area of discussion](https://github.com/prettier/prettier/issues/3089).

**Comment by fisker** [comment]
I've asked the typescript-eslint team about source type support, will post updates.

**Comment by fisker** [comment]
Currently,  `typescript-eslint` is not able to pass a "source type", but it's confirmed that it should parse as module if file name is `.mts` or `.mjs`, see https://github.com/typescript-eslint/typescript-eslint/issues/9101
