### ISSUE TITLE
Odd indentation in MemberExpression

### ISSUE THREAD

**Issue by RReverser** [prettier/prettier#1628]
Using small line width (20) purely to demonstrate the problem: 

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFAIYA0ARmWAJT7AA6U++ATnDOq89gB4B07AI4B9ABZwSAEzisAzgG0A5BOmyRUEgFs4SgLpMAvkxBkQEAA65oc5KBKtWEAO4AFBwlsoSANwg4pUxASORhkVBIAGzk4MwpWEjAAaw4AZQtEnCgAc2QYVnRYkCkIMHComLMsmNYYVwTsrRJy6KKAKzleACEE5LTtOAAZLLgWyvN0GAtJgCYxooz5WWQQChIKAE9I6CCLViyYAHUAmDFkGYAGMz2IGMOEixW9uBqfUbNhdBx2epJG5qQEVaZhiWhweQKRTkWWykTgAEV0BB4PMzDB1scpKdzmiEjhIjCAMIQLRNFZQaDvEDoGIAFXWXiBMUMhiAA)
```sh
--print-width 20
```

**Input:**
```jsx
function f(a,b,c) {
  return ctx.req_headers['header_name']
}

```

**Output:**
```jsx
function f(
  a,
  b,
  c
) {
  return ctx
    .req_headers[
    "header_name"
  ];
}

```

I think either `.req_headers` needs to be dedented or its children should be indented too.

**Comment by thorn0** [comment]
Closing in favor of #8079

**Comment by RReverser** [comment]
@thorn0 This issue was a lot earlier, so technically that one is a dupe... but I guess doesn't matter much :)

**Comment by thorn0** [comment]
The case with optional chaining seems to be simpler to solve though:

```js
  // looks great
  return ctx
    .req_headers
    ?.["header_name"];

  // same logic, looks unusual
  return ctx
    .req_headers
    ["header_name"];
```
