### ISSUE TITLE
feat: add support for @let syntax in Angular

### ISSUE THREAD

**Issue by eneajaho** [prettier/prettier#16296]
Hello, 
Angular is adding support for `@let` syntax in https://github.com/angular/angular/pull/55848. 

Having prettier support that would be great!

**Comment by kachkaev** [comment]
Feel free to submit a PR! I’m not an expert in Angular, but I guess that it will be similar to #15777 (by @sosukesuzuki)

**Comment by sosukesuzuki** [comment]
Maybe we should merge upstream in prettier/angular-html-parser...

**Comment by sosukesuzuki** [comment]
Our angular parser's side pr https://github.com/prettier/angular-html-parser/pull/40

**Comment by fisker** [comment]
Parser support has been added in #16466,  @sosukesuzuki  is implementing the print logic. 

Maybe we need support `angular-estree-parser` support to parse "Block-like syntax"? I don't know if it supports deconstructing, if not, we can use js parser to parse it as assignments.

**Comment by sosukesuzuki** [comment]
Released 3.3.3

**Comment by lucasousi** [comment]
> Released 3.3.3

Excelent! Thanks.
What about the `prettier-vscode` extension?

**Comment by tomasdev** [comment]
> > Released 3.3.3
> 
> Excelent! Thanks. What about the `prettier-vscode` extension?

you can make prettier-vscode use a different prettier version by `npm i -g prettier`

**Comment by tomasdev** [comment]
@sosukesuzuki I think the tests missed a case:

```
@let foo = 'hello';
{{ foo }}
``` 

In v3.3.3 is still getting reformatted to:
```
@let foo = 'hello'; {{ foo }}
```

**Comment by sosukesuzuki** [comment]
@tomasdev Please create new issue

**Comment by fisker** [comment]
Locked due to age, if you have issues, please [submit](https://github.com/prettier/prettier/issues/new/choose)
