### ISSUE TITLE
Not formatting any xml files if file extension is not explicitly defined

### ISSUE THREAD

**Issue by renke0** [prettier/prettier#16314]
I am trying to format some files with the `xml-plugin`, but I am struggling to automate it. The plugin is correctly installed and this is my `.prettierrc` and file structure:

> `.prettierrc`
> ```json
> {
>     "tabWidth": 4,
>     "printWidth": 100,
>     "singleQuote": true,
>     "trailingComma": "all",
>     "bracketSpacing": true,
>     "bracketSameLine": true,
>     "arrowParens": "avoid",
>     "plugins": ["@prettier/plugin-xml"]
> }
> ```

> `file structure`
> ```
> project-root
> ├── data.xml
> ├── endpoint.wsdl
> ├── index.ts
> ├── package.json
> ├── .prettierrc
> └── random-file.yml
> ```

If I try to format all files, the output is as follows. The `xml` and `wsdl` files are ignored. 

```bash
> prettier --write .
.prettierrc 6ms
index.ts 77ms
package.json 10ms
random-file.yml 0ms
```

I already tried setting `overrides`, but the result is the same:

> `.prettierrc`
>  ```json
> {
>     {...}
>     "overrides": [
>         {
>             "files": ["**/*.wsdl", "**/*.xml"],
>             "options": {
>                 "parser": "xml",
>                 "plugins": ["@prettier/plugin-xml"]
>             }
>         }
>     ]
> }
> ``` 

Although, if I explicitly set the file extensions in the command, the formatting works:

```bash
> prettier --write '**/*.wsdl' '**/*.xml'
endpoint.wsdl 1ms
data.xml 2ms
```

The `xml` and `wsdl` file formatting should work in this config right? Or am I missing something really obvious here?

**Comment by dcyriller** [comment]
Is it possible that you're running a globally installed prettier with the plugin installed in the project's directory? Could you check `prettier --version`? And maybe `where prettier`? Can you also try `npx prettier --write .` instead of `prettier --write .`?

**Comment by renke0** [comment]
That didn't have any effect, and running it with `npx` had the same result. There's no global installation of prettier and it indeed is being executed from within `node_modules`:

```bash
> prettier --version
3.0.3

> where prettier
/Users/renke0/workspace/work/api/node_modules/.bin/prettier

> npx prettier --write .
.prettierrc 8ms
index.ts 63ms
package.json 12ms
random-file.yml 1ms

> npx prettier --write '**/*.wsdl' '**/*.xsd'
endpoint.wsdl 3ms
data.xml 2ms
```

**Comment by renke0** [comment]
Good news, I just upgraded prettier to the latest version and it works as expected. I guess this can be closed now, and thanks for the help!
