### ISSUE TITLE
 Cannot find package 'prettier-plugin-svelte again

### ISSUE THREAD

**Issue by bibibala** [prettier/prettier#16318]
# error
[error] Cannot find package 'prettier-plugin-svelte' imported from /Users/zhaoshuaiqi/project/DMCP/noop.js

# verison
        "prettier": "^3.0.3",
        "eslint-config-prettier": "9.0.0",
# order
        "format": "prettier --write \"**/*.{js,vue,scss,html,md,json}\" --ignore-path .gitignore",

# system
 macos
# describe
I use prettier in vue, but it says that it can't find the relevant resources of svelte

**Comment by kachkaev** [comment]
👋  @bibibala! Please share precise reproduction steps as it is currently impossible to understand the source of the issue. Note that Prettier v3 does not support plugin autoloading so you need to mention `prettier-plugin-svelte` in your prettier config. See details here: https://prettier.io/docs/en/plugins.html

**Comment by bibibala** [comment]
I haven't found the reason yet
