### ISSUE TITLE
Prettier throws with a comment before or after flow spread

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1632]
```js
type X = {...Y/**/};
type X = {/**/...Y};
```

```js
Error: did not recognize object of type "ObjectTypeSpreadProperty"
```

Note: this happens for both babylon and flow parser

https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20X%20%3D%20%7B...Y%2F**%2F%7D%3B%5Cntype%20X%20%3D%20%7B%2F**%2F...Y%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by azz** [comment]
Doesn't that just mean `ObjectTypeSpreadProperty` needs to be added to `def/flow.js` in [benjamn/ast-types](https://github.com/benjamn/ast-types)?

**Comment by vjeux** [comment]
@azz if adding it there fixes the issue, then we should send a PR to ast-types and upgrade :) Do you mind checking if it is that?

**Comment by vjeux** [comment]
@azz you are right! I'm sending a PR

**Comment by vjeux** [comment]
https://github.com/benjamn/ast-types/pull/221

**Comment by benjamn** [comment]
This should be fixed upstream in `ast-types@0.9.12` (just released). Sorry for the wait!

**Comment by vjeux** [comment]
@benjamn fyi, I removed the reliance on ast-types inside of prettier. I'm now traversing the ast object directly. It's less "pure" but works just as well as long as I make sure to not have cycles in the ast.

**Comment by benjamn** [comment]
Out of curiosity, what would you need from `ast-types` to switch back?

**Comment by vjeux** [comment]
The biggest use of ast-type was to traverse the tree in order to attach comments, but it was likely there because the project started as a fork of recast. I changed the heuristic to traverse everything and a node is an object with a `type` key.

It's not that ast-type was bad or caused trouble, it's more that it wasn't really useful in this context, if that makes sense.

The super power of ast-type I see is for constructing nodes. I think that jscodeshift kind of apis are super awesome thanks to it.

**Comment by vjeux** [comment]
You've been super responsive in the past to keep up with changes and I would recommend it to other people :)
