### ISSUE TITLE
let multi variable declarators one line

### ISSUE THREAD

**Issue by sunnyawake5** [prettier/prettier#16339]
typescript:

let i = 0,
    j,
    k,
    count = xml.length,
    el: Element;

how to fomat it one line:
let i = 0, j, k, count = xml.length, el: Element;

**Comment by kachkaev** [comment]
👋 @sunnyawake5! Please use the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1) to report issues. Bug reports that do not follow it are hard to triage.

You can [add `// prettier-ignore`](https://prettier.io/docs/en/ignore.html#javascript) before the statement you want to keep unformatted. See also:

- https://prettier.io/docs/en/why-prettier
- https://prettier.io/docs/en/option-philosophy
