### ISSUE TITLE
Add support for  "with"  keyword in import attributes

### ISSUE THREAD

**Issue by anilkumarum** [prettier/prettier#16338]
Chrome v126 is removed support for **assert** keyword and replace by **with** 
Prettier format properly if  **assert** keyword used
```js
import styleCss from "../style/style.css" assert { type: "css" };
```
Prettier show error if  **with* keyword used
```js
import styleCss from "../style/style.css" assert { type: "css" };
```

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcYBPAGzgGFDD8AzHCdfAHRADp2B6Y8uH0hXZgabfAHdUMABb5g+UpjhJW4USHwBfANwsoAEwhgArugQx2AQ0OZ4+gMqC496XDgxC7TMcLSAFLwU1IQAlNogADQgELao0ITIoJY4jOIACskICSiWZOKWJAlRAEY4lmAA1u72lmYAMqhQcMh0uYRwJWWV1ZjljQDmyDA4xh0g7eioQyNjcAAeSjgY5rkAKnA4UMmocNmtZO1RhAMUAIrGEPAtbWMAVoRz9idw55fNSPuHIACOF-BpjEw2RAlkIAFomnB9FDIiBhpZUGQBpQmOhLMgQWQyLDjlB+hQAIIwYaoYrGf4bBpNa4HMbSGDoMgAdWkUl2vTAziyUlQADcpCQMSIiiBeaMAJIGcz2MBLWwEgyOPg0r6YRjtJllTAYtW7Da85pRRrtPAAyz9NEqsa9HAmjHlXBQWFqxowJmofQyZAADgADFEcHBfqhA2aLeiPjcojBLMV3Z7pMgAExRHxwVaxvZRkBwdDFKHQ-R1Sx44zmuAAMVwaOJA3t5IgIE0miAA)

```sh
--parser acorn
```

**Input:**

```jsx
import styleCss from "../style/style.css" with { type: "css" };
document.adoptedStyleSheets.push(styleCss);
```

**Output:**

```jsx
SyntaxError: Unexpected token (1:43)
> 1 | import styleCss from "../style/style.css" with { type: "css" };
    |                                           ^
  2 | document.adoptedStyleSheets.push(styleCss);
```

**Expected output:**

```jsx

```

**Why?**

**Comment by sosukesuzuki** [comment]
Acorn supports only stage 4 feature. please use Babel parser.
