### ISSUE TITLE
resolveConfigFile bug?

### ISSUE THREAD

**Issue by Jack-Works** [prettier/prettier#16344]
**Environments:**

- Prettier Version: 3.3.0
- Running Prettier via: API
- Runtime: 22.2.0
- Operating System: macOS
- Prettier plugins (if any): 

**Steps to reproduce:**

run in a folder with a `.prettierrc` file

```shell
$ node
> await require('prettier').resolveConfigFile(new URL(url.pathToFileURL(process.cwd())))
null

> await require('prettier').resolveConfigFile(process.cwd())
null
```

**Expected behavior:**

Resolve the file

**Actual behavior:**

null

**Comment by kachkaev** [comment]
Try

```ts
await require('prettier').resolveConfigFile(require('path').resolve(process.cwd(), 'foobar.json'))
```

Config file is resolved relative to a file path, not dir path.

- [docs](https://prettier.io/docs/en/api.html#prettierresolveconfigfilefileurlorpath)
- [source](https://github.com/prettier/prettier/blob/80bdbfe312ed1b20d6f4111912121a574541d8c6/src/config/resolve-config.js#L78-L84)

**Comment by marcellino-ornelas** [comment]
@kachkaev any reason why this shouldn't work with directories? Seems kind of wrong to have to put some random file name just to get this to work

```ts
await require('prettier').resolveConfigFile(require('path').resolve(process.cwd(), 'foobar.json'))
//                                                                                      ^^
```

**Comment by fisker** [comment]
This was changed in #15363, but I intended to change behavior for `resolveConfig()`. It kind of make sense that `resolveConfigFile()` can accept a directory.

I'm curious what the usage of `resolveConfigFile` in your case, we don't have any API accept the config file path.

**Comment by marcellino-ornelas** [comment]
> This was changed in https://github.com/prettier/prettier/pull/15363, but I intended to change behavior for resolveConfig().

Oh this would be awesome and actually what I need! 

> I'm curious what the usage of resolveConfigFile in your case, we don't have any API accept the config file path

I wasn't sure why passing a directory to `resolveConfig` didn't work so I though I needed to use the value from `resolveConfigFile` pass that to `resolveConfig`.

```ts
const configPath = await prettier.resolveConfigFile(dest);
if (!configPath) return;
const config = await prettier.resolveConfig(configPath);
```

This is how I came across this issue because passing a directory to `resolveConfigFile` didn't work either so end up having to do something like this

```ts
const configPath = await prettier.resolveConfigFile(`${dest}/hey.json`);
if (!configPath) return;
const config = await prettier.resolveConfig(configPath);
```

-----

All in all, if `resolveConfig` could accept a directory than that would 100% solve my issue

```ts
const config = await prettier.resolveConfig(dest);
```

**Comment by fisker** [comment]
We can't accept directory in `.resolveConfig()`, We support `overrides` in .prettierrc,  can't tell the config without filename.

**Comment by marcellino-ornelas** [comment]
>  We support overrides in .prettierrc, can't tell the config without filename.

Can you clarify? Not sure how overrides effect this 🤔

 >We can't accept directory in .resolveConfig()

❓ Doesn't this function recursively just look up the file path searching for a prettier config and returns it if it finds one? 🤔

**Comment by fisker** [comment]
> ❓ Doesn't this function recursively just look up the file path searching for a prettier config and returns it if it finds one? 🤔

https://github.com/prettier/prettier/blob/1dfe28f857d5aefa61178cf11aa06ff184d07839/src/config/resolve-config.js#L64

https://github.com/prettier/prettier/blob/1dfe28f857d5aefa61178cf11aa06ff184d07839/src/config/resolve-config.js#L86-L105

**Comment by marcellino-ornelas** [comment]
Ahhhh got ya! Thanks for the explanation 🙇🏽‍♂️
