### ISSUE TITLE
handlebars attrbutes changed: {{@x.y.z}} becomes {{@x}}

### ISSUE THREAD

**Issue by happydude** [prettier/prettier#16356]
**Prettier 3.3.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAeAJgSwG7qFgA2AhgM7kC8AOiAjAE4CedhqAfDVOhgBYBGDsGDoYOGMTjsAvjIwB6QVx6ZcBdCQrU6AIwhZWIFexEABAB4A6ZlYBec7u2eERhfYZeFHUReo6YCv4gADQgEAAO4tDkyKCkjIwQAO4ACgkIsSikxMmkzLFhuoykYADWcDAAyqQAtnAAMjhQcMgAZjnkcEUl5ZVVEaXNAObITACu3SBdtThjjJNhcBYRcIw49bA5ACprUAk4cFkdxF1h5CNSAIrjEPDtnVMAVuQWVZdwN3etSCdnIABHW7wVJJCJZEAUAC0LTgWDhoRATFIOGIIwAwhBarVSMhIcRiIiLlBhlIAIIwJg4XTjEFrJotB6nKZ8GC1YgAdT4EiOgzAcCqmQk+AkzDxYEoiLwkwAklB4bAqmB1lEyfKqjBmFImf8IkkuhyShE8Xqjms8K0ws0uowYKDSMMcTqpoNGDa8aSNvVGIi9c0YBycFgYHxkAAOAAMYUYcCBOBj9sduN+jzCMFIukDwdDSAATGFxl1thnjqn6LVdHD4VgGqQSeMHXAAGIQRg4ykjPGkWkQEByIA)

```sh
--parser glimmer
```

**Input:**

```hbs
  <div     class="entry"    >
  <h1>{{  title    }}</h1>
  <div   class="body">
    {{@x.y.z}}
            {{   body         }}
</div> </div>
```

**Output:**

```hbs
<div class="entry">
  <h1>{{title}}</h1>
  <div class="body">
    {{@x}}
    {{body}}
  </div>
</div>
```

**Expected behavior:**
Starting with 3.3.1 {{@x.y.z}} is output as {{@x}} , if I add `--debug-check` it will catch that the output is different

**Comment by fisker** [comment]
Sorry for breaking your code, it's caused by #16346, print `node.tail` [here](https://github.com/prettier/prettier/blob/13163d9b7543021d1f24edadbc0e5a2b1598d478/src/language-handlebars/printer-glimmer.js#L796) should be able to fix it.

Do you want work on it?

**Comment by Princeyadav05** [comment]
@fisker I've made the change. However, I was not able to test it in the playground. Can you help with that please?

**Comment by happydude** [comment]
@Princeyadav05 I tried your branch and it fixed the issue for me

**Comment by cah-brian-gantzler** [comment]
Just got hit with this myself. Hit save, prettier ran, all my code changed and nothing works.  LOL

Glad someone is on it. 

Rolled back to 3.3.0 and works fine.
