### ISSUE TITLE
3.3.0 regression - link definitions / references in markdown cause incorrect wrapping with prose-wrap always

### ISSUE THREAD

**Issue by joshka** [prettier/prettier#16351]
**Prettier 3.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFgSwM4AIBmEANgCZwBOu6AhngNoBqAEgMoC6uM1ADnAZkTh4YEXGHJxq8XAHNM+PIUox0fOgHVMJGXBi4W6CAHcwtOGwB0uVKPIBXKJ1UBbADS5MUbFyJFczFgJyCGcAHShnak9cAAoVPnjnPmooElxscTgEbEM9SGdI1LxqCVwoCD0AT11cCUEzEgBKC3DwxlY2JCoYGG5sJAB6AbkVOwAjC3yBsBpyZzHyajA4QRgBgDd0bDbNbRqDY1Nscy70Hr7BgcWuGDtMC3JsAZzDswGjLR0YJ4BiFUxyCQALTcEowSpAj57b6tKAgVwgCDcGCYaDYZCgErBIwABRK2WQIGoRCM1Eq6IRCyWAGtdCxqEkADKeODIfDE46UxZgWkwFigsCeGTIGD2OAI47OTAisUIuAAD145EwSVgxNQFCgJUwQjZHPFIGwQsEAEU7BVWUh2UROSAAFbYeUsY1wM0WvU2g0AR3N8BxwT6hNoQKgWTIJHhIFFUSIQoAwiFIkHfJGjVAZIIAII9ZVjOx+ijM0Me21nZxEdRYeDYAVwFjZTAo9aNyqEsDYCkgdZ2OAASVSCD54kwyMzqRY4MEJYN3GCx3Ui24hNnQgo61ZCM8x3IMH91BkSat+oRoMeFEJkXI1JIxjhCIkPoBcD3B+o04RXDGuxUyAATAi7GOVBqDGdEj09OV5jgEhw0ZFIZDsfc4AAMQgOYpBRdMg3zCBI1nTwYG-dBkAARgABjIgBfSigA)

```sh
--parser markdown
--print-width 100
--prose-wrap always
```

**Input:**

```markdown
This folder has [VHS] tape files to create gifs for the [Widget Showcase]. To run them, install VHS
from main (the theme and screenshot commands are not yet released).

[VHS]: https://github.com/charmbracelet/vhs
[Widget Showcase]: https://ratatui.rs/showcase/widgets/#third-party-widgets

To fix this, we recommend you use a [nerd font], this is generally what works the best. [Kreative
Square] is also a good alternative. Though note that some characters may render a bit differently
from font to font.

 [nerd font]: https://www.nerdfonts.com/
 [Kreative Square]: http://www.kreativekorp.com/software/fonts/ksquare/
```

**Output:**

```markdown
This folder has [VHS] tape files to create gifs for the [Widget Showcase]. To run them, install VHS from
main (the theme and screenshot commands are not yet released).

[VHS]: https://github.com/charmbracelet/vhs
[Widget Showcase]: https://ratatui.rs/showcase/widgets/#third-party-widgets

To fix this, we recommend you use a [nerd font], this is generally what works the best. [Kreative
Square]
is also a good alternative. Though note that some characters may render a bit differently from font
to font.

[nerd font]: https://www.nerdfonts.com/
[Kreative Square]: http://www.kreativekorp.com/software/fonts/ksquare/
```

**Expected output:**

```markdown
This folder has [VHS] tape files to create gifs for the [Widget Showcase]. To run them, install VHS
from main (the theme and screenshot commands are not yet released).

[VHS]: https://github.com/charmbracelet/vhs
[Widget Showcase]: https://ratatui.rs/showcase/widgets/#third-party-widgets

To fix this, we recommend you use a [nerd font], this is generally what works the best. [Kreative
Square] is also a good alternative. Though note that some characters may render a bit differently
from font to font.

 [nerd font]: https://www.nerdfonts.com/
 [Kreative Square]: http://www.kreativekorp.com/software/fonts/ksquare/
```

**Why?**

This is a regression from 3.2.5, which renders fine.
3.3.0 with prose-wrap always causes the line length of markdown lines with link references to be miscalculated.
The first line exceeds 100 characters (104)
Line 7 wraps in the middle of a link ref, but then wraps immediately after that line leaving a weird line 8

I found this error in our docs website for Ratatui. https://github.com/ratatui-org/ratatui-website/ in about 8 poorly formatted files.

**Comment by fisker** [comment]
@seiyab This is caused by #16158, if we change `[VHS]` in the original input to even longer string the first line will be longer too, do you have time to look into it?

**Comment by seiyab** [comment]
Thank you for notifying me. I'm taking a look.
Two problems found:
- Before flattening `fill`, `line` doesn't exist between `fill(["This", line, "folder", line, "has", line, ""]),` and `"[", fill(["VHS"]), "]". This violates rule of `fill`.
- Before flattening `fill`, doc of `[Widget Showcase]` is `["[", fill(["Widget", [line, "Showcase"]]),
  "]",]`. This also violates rule of `fill`.

I'll continue to work. But it can take time. It doesn't look straight forward.

**Comment by seiyab** [comment]
I found the second one is just my careless mistake. And also, fixing the second one, the first one looks fixed too and the example reported in this issue get correct result. I'll submit a PR soon after making more sure. I feel still confused a bit about the first problem.

**Comment by joshka** [comment]
Thanks! Looking forward to seeing this fixed :)

**Comment by seiyab** [comment]
Actually, the former "problem" is not true. It's not `fill` before `flattenFill()` so there's no violation and `flattenFill()` handles this case correctly. The only problem is the latter one, and it's a simple mistake as I mentioned. I'll make #16546 ready for review soon.
