### ISSUE TITLE
format `useRef<number | null>(null)` wrong

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier#16389]
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAbAhhgZTmzjBgEkoATOADwCU4AzTAXkwFc05GmAeKBwC2AIzgAnTAB9Mg7NgB8ACjnYAlAG4QAGhAQADjACW6ZKFzjxEAO4AFCwjTIQubNdwBPJ7pHjcYAGs4GAJcITgAGSMoOGQmV24fP0Dggn1-aIBzZBhxDjhdbiEjHLyCkDp9CSNw2FcAFQkoCyM4JyR47ESQNCySAEUOCHg4hPKAKzRaAj64QeHYjrHdAEch+FsrfXaXNABaGLgaKh0QXNwjbCyAYQghIVxnV2xT3qhMkgBBGFyjEQ4NhIojFRl1ygALGBCbAAdXBRngaHSYDgRCgvWMADcER5nGA0N4QJj8pQaLACGBxEZDJ9qAQYB4SKDuvorNwYX59M5WW0JJjYrpotxxDBNrhMg9meV0uJhc4RLgxC9dKzojAYUYqDBwcgABwABl04jgayMxrFEseSzBuhgio1Wp1SAATLouHB6or2p1unBREdjhFcO8OOK4AAxCDiB4-LJPAEQEAAXyTQA)

```sh
--parser babel
```

**Input:**

```jsx
const lastSelectIndexRef = useRef<number | null>(null);
```

**Output:**

```jsx
const lastSelectIndexRef = (useRef < number) | (null > null);

```

**Expected output:**

```jsx
const lastSelectIndexRef = useRef<number | null>(null);
```

**Why?**

don't change it

**Comment by fisker** [comment]
You should use `typescript` or  `babel-ts` parser.

**Comment by fisker** [comment]
Different meaning for JS and TS.

**Comment by fisker** [comment]
> 在 js 和 ts 混编的项目中是这样的

可以把  parser 删了， 让 Prettier 自动决定。
