### ISSUE TITLE
[JavaScript]IIFE with a comment above it format issue

### ISSUE THREAD

**Issue by ntnyq** [prettier/prettier#16387]
**Prettier 3.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDMII8BePAcgCMBDbWgHSgHoO8BLH0uOwAUpAK5QwMHtDxCAlHmABfOfPYgANCAgYp0IslDNsEAO4AFZggMpGAG1OMAnga31sjMAGs4MAMqMALZwADI8UHDIpPZEcG4e3r5+GJ7hAObIMNiicSCxgTyZ2bnoGHDYPMGw9gAq5VDMPHA20XaxWkTpdnAAiqIQ8FExuQBWRGh+Xb39g0it7SAAjjNw5iYYNiCMRAC0EXAAJoeaIFmMPHbpAMIQgYGMyFt2diedUGndAIIwWTz0ovBzOUwhEhm1cgALGCBOwAdQhPHgRBSYDgfmsiJ4ADdEU5HmAiK4QFicgBJKBHWB+MAVXSfCl+GBObpghYYEyxWEeDCPdnNcpYyJacKxXBrRhpe6s3IpbCix5MehwF5adnhGCwngHGAQ5AADgADFpsHBljwTeLJQ85sMtDBGPRNdrdUgAExaUSxGoOlq21CBJUHI4HEKMd6iCVwABiOHuP3Sj0YAIgICUSiAA)

```sh
--parser babel
```

**Input:**

```jsx
export const foo = 'bar'
// iife
(function () {})()

```

**Output:**

```jsx
export const foo = "bar"(
  // iife
  function () {},
)();

```

**Expected output:**

```jsx
export const foo = 'bar'
// iife
(function () {})()
```

**Why?**

The start parentheses and the const statement in the same line may lead a misunderstanding.

**Comment by fisker** [comment]
This works as intended. See https://prettier.io/docs/en/rationale.html#semicolons
