### ISSUE TITLE
How can i get line number from the error while using Prettier API?

### ISSUE THREAD

**Issue by zahedkamal87** [prettier/prettier#16417]
Hi, How can i get the line of the error that detected via Prettier API while formatting? Trying to avoid applying codes to parse the line number from the error message.
```
import * as prettier from "prettier/standalone"
import parserBabel from "prettier/plugins/babel";
import * as prettierPluginEstree from "prettier/plugins/estree";

var code = `{
	"name": "Boop boop",
	"age": 30
	"location": "Unknown"
}`;
prettier.format(
    code,
    {
        parser: "json",
        plugins = [parserBabel, prettierPluginEstree];
    }

).then(function(data){
    

}).catch(function(error){
    console.log(error, error.message);
    // How can i get the line number of the error
});
```

- Prettier Version: 3.3.2
- Running Prettier via: API
- Operating System: Windows

![image](https://github.com/prettier/prettier/assets/8301775/221b6265-0875-4360-866f-4ea1c178c1a0)

**Comment by fisker** [comment]
You can use `error.loc` , but it's undocumented, use on your own risk.

https://github.com/prettier/prettier/blob/988b43b72de3ed8dcba686fbbcdaa615483e3877/src/main/parse.js#L31-L36
