### ISSUE TITLE
parenthesis removed in: (a - b) + "string"

### ISSUE THREAD

**Issue by gre** [prettier/prettier#1641]
prettier removes the parenthesis when you do 

```js
(number1 - number2) + "string" 
```

it gets transformed to

```js
number1 - number2 + "string" 
```

which feels "visually" wrong. better keep the parenthesis around a numeral expression ?

NB: a workaround is to write `String(number1 - number2) + "string"` or to assign the expression to a variable.

**Comment by bakkot** [comment]
There's no way for Prettier to know that `a - b + c` is a mixed-type operation in general; I don't think it should treat it specially when some or all of the operands happen to be literals.

**Comment by lydell** [comment]
Another way is to write `${number1 - number2}string`.

**Comment by gburtini** [comment]
See also #1304.

**Comment by vjeux** [comment]
I'm consolidating all the parenthesis issues into https://github.com/prettier/prettier/issues/187

**Comment by gre** [comment]
Ok thanks 👌
