### ISSUE TITLE
Option to format an object single-line if it fits in the printWidth

### ISSUE THREAD

**Issue by dword-design** [prettier/prettier#16427]
```sh
--format-objects
```

**Input:**

```jsx
const foo = {
  bar: 'baz'
}
```

**Output:**

```jsx
const foo = {
  bar: 'baz'
}
```

**Expected output:**

```jsx
const foo = { bar: 'baz' }
```

**Why?**

I saw that Prettier [keeps the object formatting if after the opening curly bracket follows a line break](https://prettier.io/docs/en/rationale.html#multi-line-objects). But I think it should be configurable if Pretter keeps it as-is or tries to put it in one line.

It's also inconsistent with how Vue templates are linted because here a component and its props are put into one line if they fit. I haven't had a case yet where this didn't make sense.

```jsx
<foo
  bar="baz"
/>
```

```jsx
<foo bar="baz" />
```

**Comment by kachkaev** [comment]
This issue has been brought up before, so let’s close this one as duplicate. Context:
- https://github.com/prettier/prettier/issues/2068
- https://github.com/prettier/prettier/pull/16163
