### ISSUE TITLE
.gitignore is not respected for 2.8.8 

### ISSUE THREAD

**Issue by dwjohnston** [prettier/prettier#16421]
**Environments:**

- Prettier Version: 2.8.8 
- Running Prettier via: CLI 
- Runtime: v18.17.1
- Operating System: MacOS
- Prettier plugins (if any): None

**Steps to reproduce:**

Repro here: https://github.com/dwjohnston/prettier-2.8.8

**Expected behavior:**

I'm sure that this is a 'works as expected' scenario -but my google fu is failing me - the Prettier documentation doesn't exist for 2.8.8, so posting this here for posterity. 

The documentation says that "Prettier will also follow rules specified in the ".gitignore" file if it exists in the same directory from which it is run." and while this is true for >3 this appears to be not the case for 2.8.8 

**Actual behavior:**

Prettier will still scan files that are ignored by .gitignore

**Comment by fisker** [comment]
V2 is not under maintenance, please upgrade or use `prettier . --ignore-path=.gitignore`
