### ISSUE TITLE
Format files with a plug-in using configuration only

### ISSUE THREAD

**Issue by dsumac** [prettier/prettier#16428]
**Context**

When we install a plugin, we'd like to be able to configure the plugin and launch the CLI without having to specify the plugin again.
In the documentation, it seems that this is exclusive.

- https://prettier.io/docs/en/plugins#using-plugins
- https://github.com/prettier/plugin-xml

**Environments:**

- Prettier Version: 3.3.2
- Running Prettier via: CLI, CLI through npm scripts
- Runtime: Node.js v20
- Operating System: macOS, Linux
- Prettier plugins (if any): 
  - @prettier/plugin-xml
  - prettier-plugin-toml

**Steps to reproduce:**

1. `npm install --save-dev --save-exact prettier`
2. `npm install --save-dev prettier @prettier/plugin-xml`
3. configure the plugin in `.prettierrc` file
```{
  "plugins": ["@prettier/plugin-xml"]
}
```
4. `prettier --write '*.xml'` without `--plugin=@prettier/plugin-xml` option

**Expected behavior:**
Files are formated.

**Actual behavior:**
The files are not formated.

**Comment by kachkaev** [comment]
👋 @dsumac! See https://github.com/prettier/prettier/discussions/16451. Let’s continue the discussion there, if needed.
