### ISSUE TITLE
Weird formatting

### ISSUE THREAD

**Issue by numlockkey** [prettier/prettier#16432]
**Input:**

```jsx
<a href="https://developer.mozilla.org/en-US/docs/Web/HTML">MDN Web Docs</a>
```

**Output:**

```jsx
<a href="https://developer.mozilla.org/en-US/docs/Web/HTML"
    >MDN Web Docs</a
>

```

**Expected output:**

```jsx

<a href="https://developer.mozilla.org/en-US/docs/Web/HTML">MDN Web Docs</a>

<!-- OR -->

<a href="https://developer.mozilla.org/en-US/docs/Web/HTML">
    MDN Web Docs
</a>

```

**Why?**

The way it's formatting it looks weird. Even the default VS.Code formatter does it as expected.

**Comment by sosukesuzuki** [comment]
Can [html-whitespace-sensitvity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) solve your problem?
