### ISSUE TITLE
`--html-whitespace-sensitivity` has no effect on JSX

### ISSUE THREAD

**Issue by musjj** [prettier/prettier#16436]
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAYhBABQCU+wAOlPvgE5wzoN0A8AJjgG4B8+ABZwANiIj4A7hAYjO+dgHpu-ANy0AviAA0ICAAdc0AM7JQAQwYMIkgAqWEplOZGTzAT1O6ARg3NgAa2YAZXMAWzgAGRwoOGRUF2M4Hz9AkP1-GIBzZBgGdGSQJLCcXPzCuAAPfTgGHAjYFwAVWqhLHDgnBJEk3WNskTgARXQIeHjEwoArY0rggeHR8aRu3pAARyW4W2t9JxBzYwBaWLhOM50QPPMcEWyAYQgwsPNkA7FL-qgswYBBGDyOG86Hgtlq0ViEx6hUEMDCIgA6oIcPBjBkwHBgo4UbwUe43jgslAZHFdDwCgBJKDnWDBMB1Qy-anBGDuQZQtb6axJBF+fRvLmdWo8UkgGJJBgwHbmLIvDmFDIMCVvVk1Yz0nCGS5cmIwBE4TgwQTIAAcAAZdExNjgmNLZa8VpNdDBzN59YbjUgAEy6dBJJqurpOkBwMLeM7nTiRczfdAyuDEBgvAHZN7mEEQEAaDRAA)

```sh
# Options (if any):
--html-whitespace-sensitivity ignore
```

**Input:**

```jsx
function Foo() {
  return <div> hello world </div>;
}
```

**Output:**

```jsx
function Foo() {
  return <div> hello world </div>;
}
```

**Expected output:**

```jsx
function Foo() {
  return <div>hello world</div>;
}
```

**Why?**

In HTML, the whitespace is properly stripped:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4AEAFnADYkT4DuEATievqgPRZ4gA0IEADjJtAGdkoAIY0aESgAUxCIShElKIgJ5DOAIxoiwAazgwAyiIC2cADKYocZADNFAuJu16Dh7jqsBzZDBoBXJxBHE0xfAKC4AA9uOBpMM1hFABU4qDFMOHl7EkdOAW8SOABFfwh4OwcggCsBKMNCkrKKpBy8kABHZrgpCW55EBEBAFprOHRxjhA-EUwSbwBhCBMTEWRBsimCqC8igEEYP0wNf3gpOMtrStygwhgTEgB1Qkx4AQ8wOEM5V5xXlXWmC8UFoNk42ECAEkoBNYIYwPFeHsYYYYCoitd2twJI5HtpuOtsVk4tgwSArI4aDBeiIvKtMUEPDRKes7g8ptirDBHph0DBCMgABwABk4NDgXUw4ppdLWrSqnBgIg0PL5AqQACZOP5HMlldkFSA4CYNOMJuhzCIdv5aXAAGK0VaHbzrESnCAgAC+nqAA)

**Input:**

```html
<div> hello world </div>
```

**Output:**

```html
<div>hello world</div>
```

**Comment by fisker** [comment]
JSX is not HTML, it works as expected.

**Comment by musjj** [comment]
Can this be re-opened as a feature request for a similar flag for JSX?

**Comment by fisker** [comment]
Yes, you can open an new issue to discuss, we applied `jsxBracketSameLine` to html in https://github.com/prettier/prettier/pull/11006
