### ISSUE TITLE
Remaining TypeScript Printing Issues

### ISSUE THREAD

**Issue by azz** [prettier/prettier#1643]
Latest run through the TypeScript codebase's test suite resulted in this output:

<details>
<summary>
13886 good, 886 bad
</summary>
<pre>
90      SyntaxError: ';' expected.
90      SyntaxError: Expression expected.
82      TypeError: Cannot read property 'type' of undefined
62      Error: Value undefined is not a valid document
58      prettier(input) !== prettier(prettier(input))
56      Error: did not recognize object of type "TSInterfaceHeritage"
46      SyntaxError: Invalid character.
44      SyntaxError: ',' expected.
42      ast(input) !== ast(prettier(input))
35      SyntaxError: Identifier expected.
24      SyntaxError: Declaration or statement expected.
23      SyntaxError: Type expected.
21      SyntaxError: '(' expected.
17      SyntaxError: ':' expected.
16      SyntaxError: Hexadecimal digit expected.
16      SyntaxError: Property or signature expected.
14      SyntaxError: '=' expected.
12      SyntaxError: Unterminated template literal.
10      SyntaxError: Parameter declaration expected.
8       SyntaxError: An extended Unicode escape value must be between 0x0 and 0x10FFFF inclusive.
8       SyntaxError: ')' expected.
8       SyntaxError: 'super' must be followed by an argument list or member access.
7       SyntaxError: Unexpected token. A constructor, method, accessor, or property was expected.
6       SyntaxError: Property assignment expected.
6       SyntaxError: '}' expected.
6       TypeError: Cannot read property 'some' of undefined
6       SyntaxError: Unterminated Unicode escape sequence.
6       SyntaxError: '{' expected.
5       SyntaxError: '{' or ';' expected.
4       Error: Comment "<omitted>" was not printed. Please report this error!
4       SyntaxError: Unterminated string literal.
4       SyntaxError: Digit expected.
3       SyntaxError: Argument expression expected.
3       SyntaxError: 'as' expected.
3       Error: Comment location overlaps with node location
3       SyntaxError: Merge conflict marker encountered.
3       SyntaxError: Unterminated regular expression literal.
3       SyntaxError: An unary expression with the '-' operator is not allowed in the left-hand side of an exponentiation expression. Consider enclosing the expression in parentheses.
3       SyntaxError: '=>' expected.
3       SyntaxError: ']' expected.
2       SyntaxError: Enum member expected.
2       SyntaxError: '>' expected.
2       SyntaxError: Declaration expected.
2       SyntaxError: Array element destructuring pattern expected.
2       SyntaxError: Variable declaration expected.
2       SyntaxError: Expression or comma expected.
2       SyntaxError: '*/' expected.
1       SyntaxError: An unary expression with the 'typeof' operator is not allowed in the left-hand side of an exponentiation expression. Consider enclosing the expression in parentheses.
1       SyntaxError: Unexpected end of text.
1       SyntaxError: Binary digit expected.
1       SyntaxError: Type parameter declaration expected.
1       SyntaxError: Cannot read property 'pos' of undefined (undefined:undefined)
1       SyntaxError: JSX element 'number' has no corresponding closing tag.
1       SyntaxError: 'case' or 'default' expected.
1       SyntaxError: Invalid 'reference' directive syntax.
1       SyntaxError: JSX element 'T' has no corresponding closing tag.
1       SyntaxError: An AMD module cannot have multiple name assignments.
1       SyntaxError: 'of' expected.
1       SyntaxError: An unary expression with the 'delete' operator is not allowed in the left-hand side of an exponentiation expression. Consider enclosing the expression in parentheses.
</pre>
</details>

Scrolling through the debug output, it appears that all of the `SyntaxError`s are fine (actual syntax errors in the input), but the following are still issues:

* [ ] `12` ~`13`~ ~`20`~ ~`21`~ ~`58`~      `prettier(input) !== prettier(prettier(input))` [gist](https://gist.github.com/azz/da812a1ae75a2e859ba427f0d96de128#file-prettier-input-prettier-prettier-input-log)
  #1769, #1770, #1771 and #1785
* [ ] `3`       `Error: Comment location overlaps with node location` [gist](https://gist.github.com/azz/da812a1ae75a2e859ba427f0d96de128#file-error-comment-location-overlaps-with-node-location-log)
* [x] `0` ~`2`~ ~`0`~ ~`4`~       `Error: Comment "<omitted>" was not printed. Please report this error!` [gist](https://gist.github.com/azz/da812a1ae75a2e859ba427f0d96de128#file-error-comment-omitted-was-not-printed-please-report-this-error-log)
  Fixed by #1685 and #1765
* [x] `0` ~`5`~ ~`82`~      `TypeError: Cannot read property 'type' of undefined` [gist](https://gist.github.com/azz/da812a1ae75a2e859ba427f0d96de128#file-typeerror-cannot-read-property-type-of-undefined-log) 
  _Note: most/all of these are issues with decorators_
  Fixed by #1678
* [x] `0` ~`62`~      `Error: Value undefined is not a valid document` [gist](https://gist.github.com/azz/da812a1ae75a2e859ba427f0d96de128#file-error-value-undefined-is-not-a-valid-document-log)
   Fixed by #1645 and eslint/typescript-eslint-parser#280
* [x] `0` ~`56`~      `Error: did not recognize object of type "TSInterfaceHeritage"` [gist](https://gist.github.com/azz/da812a1ae75a2e859ba427f0d96de128#file-error-did-not-recognize-object-of-type-tsinterfaceheritage-log)
  Fixed by #1644
* [x] `0` ~`5`~ ~`15`~ ~`42`~      `ast(input) !== ast(prettier(input))` [gist](https://gist.github.com/azz/da812a1ae75a2e859ba427f0d96de128#file-ast-input-ast-prettier-input-log)
  Fixed by #1763 and #1764
* [x] `0` ~`6`~       `TypeError: Cannot read property 'some' of undefined` [gist](https://gist.github.com/azz/da812a1ae75a2e859ba427f0d96de128#file-typeerror-cannot-read-property-some-of-undefined-log)
  Fixed by #1646

### 15 ~16~ ~23~ ~26~  ~31~ ~44~ ~313~ errors

Looks like we're getting close!

**Comment by LukeSheard** [comment]
@azz How do we run these TS tests? I just updated to `master` and I can't find any?

**Comment by azz** [comment]
@LukeSheard the tests aren't in this repo, they're in the TS repo: https://github.com/Microsoft/TypeScript/tree/master/tests

We just clone the TypeScript repo next to the prettier repo and run them that way.

I added a script `node scripts/run-external-typescript-tests.js` that runs them for you, but it currently only works properly on Windows.

**Comment by lydell** [comment]
Perhaps `scripts/run-external-typescript-tests.js` can be modified to ignore test cases that are invalid TypeScript as input, just like [`scripts/sync-flow-tests.js`](scripts/run-external-typescript-tests.js) does.

**Comment by azz** [comment]
@lydell Good idea. Done in #1647.

**Comment by vjeux** [comment]
```js
node scripts/run-external-typescript-tests.js
Error: this script currently only works on windows.
```

:(

**Comment by lydell** [comment]
Is there a reason the TypeScript tests aren't copied into the repo as the Flow tests are?

**Comment by vjeux** [comment]
@lydell there are 11k of them :x Only a hundred-ish for flow.

**Comment by azz** [comment]
@vjuex My MacBook died so I am unable to pursue fixing the script on Mac for the moment. I left a comment at the top of the script as to why it doesn't work.

**Comment by vjeux** [comment]
Oh noes, sad to hear!

**Comment by vjeux** [comment]
Posting this again here so we can check all those projects.

- https://github.com/palantir/tslint
- https://github.com/apollographql/apollo-client
- https://github.com/Microsoft/vscode
- https://github.com/infernojs/inferno
- https://github.com/ceolter/ag-grid
- https://github.com/Microsoft/TypeScript
- https://github.com/microsoft/reactxp
- https://github.com/tensorflow/tensorflow
- https://github.com/Mercateo/ws
- https://github.com/NativeScript/NativeScript
- https://github.com/Reactive-Extensions/RxJS
- https://github.com/angular/angular
- https://github.com/ant-design/ant-design
- https://github.com/artsy/emission/
- https://github.com/HearthSim/Joust
- https://github.com/postgraphql/postgraphql
- https://github.com/veloce/lichobile

**Comment by vjeux** [comment]
```js
../tslint/src//rules/semicolonRule.ts: SyntaxError: Expression expected. (94:43)
  92 |
  93 | class SemicolonWalker extends Lint.AbstractWalker<Options> {
> 94 |   private scanner?: ts.Scanner = undefined?;
     |                                            ^
  95 |   public walk(sourceFile: ts.SourceFile) {
  96 |     const cb = (node: ts.Node): void => {
  97 |       switch (node.kind) {
```

Any idea why it's not parsing?

**Comment by jgoz** [comment]
> Any idea why it's not parsing?

The `?` after `undefined` is not valid TS for value expressions (as far as I know). It's expecting a ternary expression there.

**Comment by azz** [comment]
So close!

```
13356 good, 531 skipped, 44 bad
100% of 13931 files processed without errors.
```

I think we need more accuracy on that percentage! (99.68%)

**Comment by vjeux** [comment]
On a related note, prettier for typescript is significantly slower than running it for normal js. I can't wait for the babylon integration to land, this would avoid having to parse it once and then completely reshuffle the ast.

**Comment by vjeux** [comment]
Okay I'm done for the day,

If we fix the following 5 issues, we should be good to go for all the projects (but angular):

- #1460
- #1694
- eslint/typescript-eslint-parser#288
- eslint/typescript-eslint-parser#289
- eslint/typescript-eslint-parser#290

I have yet to categorize all the angular errors, but I think that there are some unique ones that aren't tracked here.

**Comment by JamesHenry** [comment]
> On a related note, prettier for typescript is significantly slower than running it for normal js. I can't wait for the babylon integration to land, this would avoid having to parse it once and then completely reshuffle the ast.

@vjeux Would you mind sharing your method for evaluating this? Performance has never been an issue in `typescript-eslint-parser`, so it has accordingly not received much attention. There may well be some quick wins available in the short term

**Comment by vjeux** [comment]
@JamesHenry I've been running prettier on a bunch of files for both typescript and js and it **feels** significantly faster using flow. I haven't benchmarked it or anything yet :)

**Comment by azz** [comment]
Another one causing causing some `prettier(input) !== prettier(prettier(input))` checks to fail: eslint/typescript-eslint-parser#296.

```patch
-class Foo<___proto__> {}
+class Foo<____proto__> {}
```

**Comment by azz** [comment]
With #1785 and #1786:

>**12759** good, 568 skipped, **15** bad
>**99.89%** of **13342** files processed without errors.

**Comment by JamesHenry** [comment]
Nice!

**Comment by vjeux** [comment]
On master, angular has only those two issues remaining:

```js
../angular//packages/compiler-cli/integrationtest/ngtools_src/feature2/feature2.module.ts: SyntaxError: ',' expected. (19:91)
  17 |   declarations: [FeatureComponent],
  18 |   imports: [RouterModule.forChild([
> 19 |     {path: '', component: FeatureComponent}, {path: 'd', loadChildren: './default.module'} {
     |                                                                                            ^
  20 |       path: 'e',
  21 |       loadChildren: 'feature/feature.module#FeatureModule'
  22 |     }
```

```js
../angular//packages/platform-browser/src/dom/dom_adapter.ts: Error: Comment "<T extends Node>" was not printed. Please report this error!
    at /Users/vjeux/random/prettier/index.js:46:13
    at Array.forEach (native)
    at ensureAllCommentsPrinted (/Users/vjeux/random/prettier/index.js:44:15)
    at format (/Users/vjeux/random/prettier/index.js:70:3)
    at formatWithShebang (/Users/vjeux/random/prettier/index.js:233:12)
    at Object.module.exports.format (/Users/vjeux/random/prettier/index.js:246:12)
    at format (/Users/vjeux/random/prettier/bin/prettier.js:180:25)
    at /Users/vjeux/random/prettier/bin/prettier.js:304:16
    at /Users/vjeux/random/prettier/bin/prettier.js:359:7
    at Array.forEach (native)
```

**Comment by JamesHenry** [comment]
@vjeux Love how prettier is in your "random" folder 😄

**Comment by azz** [comment]
@vjeux What's the priority on the three `Error: Comment location overlaps with node location` errors?

**Comment by vjeux** [comment]
@azz: we should fix them :) This one is also an error that we should fix:

```js
../angular//packages/platform-browser/src/dom/dom_adapter.ts: Error: Comment "<T extends Node>" was not printed. Please report this error!
```

**Comment by vjeux** [comment]
Let's close this one now that TypeScript has been released.
