### ISSUE TITLE
No way to use markdown in HTML files without prettier mangling it

### ISSUE THREAD

**Issue by mangelozzi** [prettier/prettier#16431]
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRGYDOMAhgTDtgHwA6UqAWzYBrACYQA7lF5QAMqWZI+uAGKkCzHDAAWpKNWU4AynEhRRW3fr6oA9EIJjJ0m1lyFiZClVr04mBAtuEAAaEAg8MmhGZFA2AkkABTYEGJQWABsJFgBPGLCAIwIWMGFiIxYBOHkoOGQAM0zGOELi0vK8Er1qZBgCAFcWkGaBUl6BobgADzwKUirYTIAVCig2cjTGjOawxm6MuABFfoh4BqahgCtGKaN9o5OzpC2dkABHR7hEhLw0kBZGJhanBRCDQiA+ixSBlugBhCACITIEBwRgAVnBe30BwAgiQCKQCv14IkKDU6s8LmFtDABBkAOq6eCMTpgOAmKB7MgAN1IMByyLAjHyIG5gwAkuYEDAjGACZEceYjPyDudtkNCBBmvTinhkR5mgRuXUwnpDTBvixqEjKeqwp0NBRkTS6eDCHoYPTSKIdMgABwABjCRA+6i+xWtLDVr1YBS9Pu0yAATGF+s0liwCpsqSiBAUQaDRLIWPp+la4Cp6EISN1kSxiRAQABfJtAA)

```sh
--parser html
--trailing-comma es5
```

**Input:**

```html
<!-- prettier-ignore-start -->
<markdown>
List:
- First thing
- Second thing
</markdown>
<!-- prettier-ignore-end -->
```

**Output:**

```html
<!-- prettier-ignore-start -->
<markdown> List: - First thing - Second thing </markdown>
<!-- prettier-ignore-end -->

```

**Expected output:**

```html
<!-- prettier-ignore-start -->
<markdown>
List:
- First thing
- Second thing
</markdown>
<!-- prettier-ignore-end -->
```

**Why?**
Because white space matters in markdown. Plugs in like https://github.com/mdefy/ngx-markdown-editor/blob/master/README.md can be used to create blocks of markdown inside one's templates.
Ideally one could specify that it should not format text within `<markdown> ... </markdown>` tags at all, but second best is the start/end format tags.

**Comment by kachkaev** [comment]
👋 @mangelozzi! You can use `<!-- prettier-ignore -->` instead:

**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRE7YB8AOlKgLYCGBA1gCYQA7lFZQAMqQDOMJG1wAxUgRk4YAC1JRq8nAGU4kKPzWbtbVAHpufQSLEgANCAh4y0KclA8CwgAo8CJ4oXAA2QlwAnp7OAEYEXGC8xHpcHHCSUHDIAGZhUnBxCUkpeIla1MgwBACuhSAFHKRVtfVwAB54FKTpsGEAKhRQPOTBeaEFzlIVoXAAijUQ8Ln59QBWUu16M-OLy0jjkyAAjntwfr54wSBcUphZcPyPTiDVXKShFQDCEBzcyCA4FIAKwvabaWYAQRIBFIsRq8D8FEy2QOq2c6hgHFCAHVNPApGUwHADFBpmQAG6kGCRAFgKQxEAUuoASWMCBgejAsLckOMehpsxWE3qhAgBRxCTwAMIQIoFOyzi0BQIMAuXGo-zRIucZRUFABmOxL0IWhgONI-A0yAAHAAGZxEU7Kc4JTVcYVHGBcWIWq3qZAAJmcNQK-R9Y3RgI4sUeT344i42hqGrgCno3BIFQBXAREBAAF8C0A)

```sh
--parser html
--trailing-comma es5
```

**Input:**

```html
<!-- prettier-ignore -->
<markdown>
List:
- First thing
- Second thing
</markdown>

```

**Output:**

```html
<!-- prettier-ignore -->
<markdown>
List:
- First thing
- Second thing
</markdown>

```
