### ISSUE TITLE
Formatting e0 away breaks ganja.js 

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#16444]
Prettier formats `1e0` to `1` in JS. Fairly reasonable. Except there's a library https://github.com/enkimute/ganja.js which uses the syntax to express "complex" numbers (think `1 * i` in maths).

Now that's an inventive use of the language, and maybe the language the library uses could be considered separate to JS. But I'm opening this issue anyway in case people agree that formatting `1e0` to `1` is not a very useful transformation (like has it saved anyone time? Did people argue about whether they should express a number as `12e0` or `12`?). I'd bet this is formatting is not useful in practice to JS developers, but it breaks the use of this library.

In case someone runs into this issue, I just made a quick fork (that I'm **not** planning to keep up to date with prettier, although it just deleted one line of code from prettier):

`npm i @xixixao/prettier-ganja`

You can use it via 

`.vscode/settings.json`:
```
{
  "prettier.prettierPath": "./node_modules/@xixixao/prettier-ganja",
  "editor.formatOnSave": true
}
```

**Comment by sosukesuzuki** [comment]
Can you use the issue template?

**Comment by xixixao** [comment]
Addition: Also formatting `1e02` to `1e2` breaks the library, so I removed that from the fork as well.
