### ISSUE TITLE
Template literal string prints more than `--print-width` characters in a single line 

### ISSUE THREAD

**Issue by lulunac27a** [prettier/prettier#16442]
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDANnATjAFAAwBVUBnAawAIASYGUsgOjvIF8LIBbAB03gBMAhAB0hUAJoQArhTiosUOH2rAAHlwCichXyYQAMhDAY4AZRhYAllADmuISAQBaAKon7ASjYANAArDREtKy8orKXBBWMCSaITow+obGZpY2dg5QLm4gnhThkTR5sNFaoQC85RQAjBQA-BT29hRI9SAk9iwC+O4A3AD0vcY4FJIk2BTxFCQAFhAA7hQz8xyoUACeFL7jU3DrwdoUK0qFUTIlSqgAZvBY7BDcvFbWW3Dj9CAANCAQXDAW0CTIUByLBzHxyBAAlAYWaoVYAz4AIywqDAZDgMBMqA4cD0VjgyAuGFGiORqPRJi4KMeyHMkjgn1GHAsNKwdM+cDU2As2NgGEI2CgcgscEhhPQxNaj0wAEVJBB4ASifSQAArEgqExSuCy+X4pBiiUARzl8B8IK4kLQJEcCkUig+IHMqAs6EeAGE7stkGh0OgHSQtQBBGDmCwIySm7C4hSK8XKqYwDjoADqUws8BIlLApgh6YsADd06tvWASPCQPm6QBJKB8BAYsCWH6B2tmVaYWMSrgg0bJ5Fcb3dkXYfP4z5WUY4M2oaxe-VKz6UrCT70wVZcEWNiw-B1YODGix76ez1Cd5V0BHJix8GBTZAAJk+IzgxARooXDg4CMUdb4ehW1iSDOcAAGIQFgywhtSUIRhADrdpEV43neSAAOwACwsCwQA)

```sh
--parser typescript
--print-width 74
```

**Input:**

```tsx
alert(`Task ${task.task} completed!\nYou earned ${xpEarned.toLocaleString("en-US")} XP!\nYou earned ${pointsEarned.toLocaleString("en-US")} point${pointsEarned === 1 ? "" : "s"}!`);//alert user to show how many XP they earned and points earned after completing the task
```

**Output:**

```tsx
alert(
  `Task ${task.task} completed!\nYou earned ${xpEarned.toLocaleString("en-US")} XP!\nYou earned ${pointsEarned.toLocaleString("en-US")} point${pointsEarned === 1 ? "" : "s"}!`,
); //alert user to show how many XP they earned and points earned after completing the task

```

**Expected output:**

```tsx
alert(
  `Task ${task.task} completed!\nYou earned ${xpEarned.toLocaleString(
    "en-US"
  )} XP!\nYou earned ${pointsEarned.toLocaleString("en-US")} point${
    pointsEarned === 1 ? "" : "s"
  }!`
); //alert user to show how many XP they earned and points earned after completing the task
```

**Why?**

The expected output should not print more than the specified number of characters (`--print-width`) in a single line when using template string literals

**Comment by sosukesuzuki** [comment]
This is expected please see https://prettier.io/docs/en/rationale.html#template-literals
