### ISSUE TITLE
Extra spaces and backslashes in MDX v2+ JSDoc comments

### ISSUE THREAD

**Issue by karlhorky** [prettier/prettier#16457]
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwD0AqDAdKACPDPAARgE8AHOAEzgDM8AFAJwgoGdcCjiLWrm5PMHYxmASygBzAL54oAQwC2cLoQJ4A6gAsIeGHqnM4cGADo1GNDNy50WEuSq0GLNuxJ82cQWWGiJaTlFFQAmLV19Q2NTM0JrWygAYjwACTgAGwy9YC8OMxC4OQUoamE89gLlOFCZEAAaEDYYcWh2ZFAFZlYAd0YuhHaUBQyehTJ2xoAjZgUwAGtTAGVqgBlJOGQ6EfY4admF5Yo5ySlkMQBXPZBdpXFz5ivGuAAPAXEVWBGAFR9FCTgQ22GV2jXYpwycAAihcIPAtjtrgArdgvJYQ6Gw+FIYGgkAARyxcDcHGQIAU7AAtFATLRqA0QGIFOIMqcAMIQJRKBRkkYZBng6SQgCCMDE4imF3gjB86xpCJB120MCUGR04ng7GOYDgS0GGvEADcNWQyWB2JMQIargBJUoIGBLMASCgwYWlJbkSEKvFeXaaWYUMl8QE+Q2bRqSXaCFgKKTcn3XY7MaNkpTUF4MviSGCacTUGDaZAADgADI1jITxMZY-GeTjEY0YAopnmC0WkKFGhddt8W0DGyA4EopjQ6asSlILnG4AAxCDMbli068qUQEAyGRAA)

```sh
--parser mdx
```

**Input:**

```mdx
{/**
  * @typedef Props
  * @property {string} name
  *   Who to greet.
  */}

{/** @typedef Props @property {string} name2 Who to greet. */}

# Hello {props.name} and {props.name2}
```

**Output:**

```mdx
{/\*\*

- @typedef Props
- @property {string} name
- Who to greet.
  \*/}

{/* * @typedef Props @property {string} name2 Who to greet. */}

# Hello {props.name} and {props.name2}

```

**Expected output:**

```mdx
{/**
  * @typedef Props
  * @property {string} name
  *   Who to greet.
  */}

{/** @typedef Props @property {string} name2 Who to greet. */}

# Hello {props.name} and {props.name2}
```

(no formatting change from **Input**)

**Why?**

JSDoc has meaning and functionality in MDX documents (see [the Props section of MDX Analyzer docs](https://github.com/mdx-js/mdx-analyzer#props)), which is broken by the extra spaces and backslashes added above.

As an extension to [the MDX v2 comments feature](https://github.com/prettier/prettier/issues/10706) by @wooorm, it would be great to support:

1. JSDoc in MDX v2+ multi-line comments
2. JSDoc in MDX v2+ single-line comments

**Related**

- https://github.com/prettier/prettier/issues/10706

**Comment by kachkaev** [comment]
👋 @karlhorky! I believe that this particular issue is a part of this one
- https://github.com/prettier/prettier/issues/12209

Not sure we can do much until we upgrade the parser, and when it’s done, the problem will probably self-resolve. If that’s not the case here, let me know and I’ll re-open the issue.

**Comment by karlhorky** [comment]
Yeah, I thought so at first too. But since MDX v2/v3 comments support was already implemented by @wooorm before that issue was opened, I thought JSDoc support may be able to be a natural extension of that:

- https://github.com/prettier/prettier/pull/11563

**Comment by karlhorky** [comment]
## Workaround

Ignore any JSDoc comments until MDX v2+ comments w. JSDoc support added:

```mdx
{/* prettier-ignore-start */}

{/**
  * @typedef Props
  * @property {string} name
  *   Who to greet.
  */}

{/* prettier-ignore-end */}

# Hello {props.name}
```

Also added an MDX Analyzer PR here:

- https://github.com/mdx-js/mdx-analyzer/pull/455
