### ISSUE TITLE
Useless pipe (`|`) added to a particular TypeScript type expression

### ISSUE THREAD

**Issue by gfx** [prettier/prettier#16483]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAStgXmwAoBnGAJwEsoBzbOAD3igBNTtzq7sB+bSgFccSbADMAhgBtScAJQAdKNmwAfElEEBbAEZwKDZgnadKNevyEjx02XIDcSkABoQEDDCrRSyUBIoUEADuAAr+CD4o0kESaD6uOhQSYADWcDAAyhJacAAyNHDIkjJwCUmp6RkYyebIVq6yWlR1FMKuTFjUObDSACr6UP5UcJHFsg3mUnAAioIQ8EW2pSAAVqSMGZMzcwtIY8sAjjtwIYEYkSASpAC0UHBwrA8uqElUUuYAwhBaWhLIl1IpM9SFsAIIwMw6QTwEL6fJ3RYlVwACxgWikAHVkVR4KRqmA4BkIjiqAA3HFof5gUjxECk4QASTYCEyYGoHlBbAy6CmiPGIAwgVkGKSGH+gpG+lJhVcNFkFBgpwktF+fOW1Qo8v+6CwpDZVA8z0FNBgGKorBgyOQAA4AAyuChwI5UR1KlV-PZLVwwCQ6M0Wq1IABMrkEsl6vtGXpAcF0D0erFyEjogmVcAAYhAKL8IbUotCICAAL5FoA)

```sh
--parser typescript
```

**Input:**

```tsx
type R = (string extends string ? true : false)
  | (number extends string ? true : false);

```

**Output:**

```tsx
type R =
  | (string extends string ? true : false)
  | (number extends string ? true : false);

```

**Expected output:**

```tsx
type R = (string extends string ? true : false)
       | (number extends string ? true : false);
```

**Why?**

Prettier adds a useless `|` in particular TypeScript expressions. Interestingly, the output TypeScript is still valid (not sure why), but there's no reason to add an extra `|` in the case.

**Comment by kachkaev** [comment]
:wave: @gfx! This is expected behavior. See https://github.com/prettier/prettier/issues/2971#issuecomment-333890539 for explanation.

**Comment by gfx** [comment]
OMG! Thanks.
