### ISSUE TITLE
Prettier removes trailing comma in typescript constructors/methods when trailing commas is set to all

### ISSUE THREAD

**Issue by grossws** [prettier/prettier#16486]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAFTgFsM9gAdKPA6UmbAVzBhwApmrVhmwBLAG7F4ebHGIATaIQCeeUhLBI8AZU0AaIXgCUDAL5GjMAIyCWw4toCCh+6eAX7VgEx3heRzwXI1YAI20AIVdWd09WKwBmP2EAAQAFYmxiGn4AcmJc02IAfUJoAHNijEzsuHhsYqha5wAZCsoVDDgAOVro1IysnNzQwrxQ0oqqmpo6uAam2ci2qHKOrt7Z-vcjT08QfRAIDBgxdmRQTOwIAHdBhFJkEGJCG+IVR8PQrLAAazqdLUWmIoHBkJwuHAvj9-jAdNUwCDyuDuFCQKRaGIUZDDuguuJZrAXtRsE1xHBHkgAGYvDGHUhIwhwACKXAg8GQNMIdJAACtSGgdIyWWyOdTaWiAI6iuBpa4YSngdhiDgIGAHECcYhiQhIgDCEBoNGITxehA1DNWTKcME4YlCXHgaXmwNBnIlhwAFjAaIQAOqesTwUgIuA6B5ByRBlRPMDkDUSSEASSgCjVOjA4hOTlTOhgKiZ7u5aNEEAxfqyGCeogp8wkYMOIIxuDlxHKxqLPOq2GbT3zXVImbEJw1ohBMD9YgUME9yAAHAAGQ5yaViOSt9sm8XFw4wYihSfT2dIbyHLgYyj7ylcnm0UJwBRphQtYirLhtuAAMRwxttSNNjoQCAZhmEAA)

```sh
# Options (if any):
--parser typescript
--trailing-comma all
```

**Input:**

```ts
export class Temp {
  constructor(
    private readonly svc: Svc,
  ) {}
  
  t1(
    a: A,
  ) {}
  
  t2(
    a: A,
    b: B,
  ) {}
  
  t3(
    @Param('a') a_long_parameter_name: ALongTypeName,
    @Param('b') b_long_parameter_name: BLongTypeName,
  ) {
  }
}
```

**Output:**

```ts
export class Temp {
  constructor(private readonly svc: Svc) {}

  t1(a: A) {}

  t2(a: A, b: B) {}

  t3(
    @Param("a") a_long_parameter_name: ALongTypeName,
    @Param("b") b_long_parameter_name: BLongTypeName,
  ) {}
}
```

**Expected output:**

```ts
export class Temp {
  constructor(
    private readonly svc: Svc,
  ) {}

  t1(
    a: A,
  ) {}

  t2(
    a: A,
    b: B,
  ) {}

  t3(
    @Param("a") a_long_parameter_name: ALongTypeName,
    @Param("b") b_long_parameter_name: BLongTypeName,
  ) {}
}
```

**Why?**

Prettier should keep parameters on separate lines and keep trailing comma when it was present originally in code.

**Comment by kachkaev** [comment]
👋 @grossws! You can achieve sought behavior by adding `//` to the list of args:

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAFTgFsM9gAdKPA6UmbAVzBhwApmrVhmwBLAG7F4ebHGIATaIQCeeUhLBI8AZU0AaIXgCUDAL5GjMAIyCWwgPQOjrYtoCCh+6eAX7VgCY7YTwnFzw3PE9wgCNtACEvVh8-VisAZmDhAAEABWJsYhp+AHJiEtNiAH1CaABzKowCorh4bCqoFo8AGXrKFQw4ADkWpJz8wuKSmIq8GJr6xuaaVrh2zpWE3qg6-sGRlbGfIz8-EH0QCAwYMXZkUALsCAB3CYRSZBBiQmfiFQ+LjFCmAANatHQtbpiKBwZCcLhwQHAsEwHRNMDQupw7iIkCkWhibEIi7oQbiFawb7UbCdcRwD5IABm33xF1ImMIcAAilwIPBkMzCKyQAArUhoHQc7m8-lMlm4gCOMrguSeGAZ4HYYg4CBg5xAnGIYkImIAwhAaDRiJ9voR9eydpz3DBOGIYlx4Lk1lCYQL5RcABYwGiEADqAbE8FI6LgOnekckkZUnzA5H1EgRAEkoApdTowOJru4czoYCpOX6hbjRBB8aHChhPqJ6WsJLCLtD8bhVcQ6lbK8Kmtgu58y4NSAWxNd9aJoTBQ2IFDAA8gABwABguciVYjkPb71rlVYuMGIMQXS5XSACFy4+MoZ4ZguFtBicAUuYU3WIOy4vbgABiOBWi6mI2h6EAgGYZhAA)

```sh
--parser typescript
--quote-props consistent
--bracket-same-line
```

**Input:**

```tsx
export class Temp {
  constructor(
    private readonly svc: Svc,
  ) {}
  
  t1(
    //
    a: A,
  ) {}
  
  t2(
    //
    a: A,
    b: B,
  ) {}
  
  t3(
    @Param('a') a_long_parameter_name: ALongTypeName,
    @Param('b') b_long_parameter_name: BLongTypeName,
  ) {
  }
}

```

**Output:**

```tsx
export class Temp {
  constructor(private readonly svc: Svc) {}

  t1(
    //
    a: A,
  ) {}

  t2(
    //
    a: A,
    b: B,
  ) {}

  t3(
    @Param("a") a_long_parameter_name: ALongTypeName,
    @Param("b") b_long_parameter_name: BLongTypeName,
  ) {}
}

```

Trailing commas will preserve.

Prettier prints arguments on multiple lines only if they don't fit into a single line ([print width](https://prettier.io/docs/en/options.html#print-width)). Keeping trailing commas in multi-line mode makes sense for git diff minimisation.

See https://github.com/prettier/prettier/issues/14395 and  https://prettier.io/docs/en/option-philosophy.html for context.
