### ISSUE TITLE
[Markdown] Write fenced language in lowercase

### ISSUE THREAD

**Issue by regseb** [prettier/prettier#16482]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdApAhgNywZTACcBLABxgB0pIoBnCAGzgDpGIBzACgHIAzCBB4BKaulTUx6AFa4sdYuSo1oDZm068BQ0VHEgANCAgUSq5KCxEiEAO4AFKwjrIQWRrawBPF0YBGRFhgANZwMPhYALZwADIkUHDIfO50cP6BIWH4ZEHxHMgwRACuaSCpkSQFxaVwAB5kcKTRsO4AKo1QViRwLkjJjKlGdHnMAIpFEPBJKaXSdLX4I3Djk4l9M0YAjhPw9jZkvW50ALQJcAAmF4YghVgkjHkAwhCRkViu7ozXw1AczACCMEKJD8RV2jTiCWmA1KAAsYJFGAB1WEkeB0HJgOD4Zxokg4NFeVxgOi+EA4EoASSgl1ghFIFH+NPwMC8zGhgxAZBsqSRgTIrm5PUaOESRniqSIMD2WA4bw5pRyRElrjeRGC5zsUGu3PiMCRJHOMFhyAAHAAGIxEODbEjWmVy97rGFGGBYPwGo0mpAAJiMRVSrXdvX6nLgkT8F0u5xiWF+RVlcAAYhAiG8gXkPmCICAAL65oA)

```sh
--parser markdown
```

**Input:**

````
```JavaScript
console.log('foo')
```
````

**Output:**

````
```JavaScript
console.log('foo')
```
````

**Expected output:**

````markdown
```javascript
console.log("foo");
```
````

**Why?**

Write fenced language in lowercase, because the best practice seems to be lowercase and some interpreters don't support uppercase.

All examples are in lowercase (from the first _markdown fenced_ results on Google):

- [Markdown Guide](https://www.markdownguide.org/extended-syntax/#syntax-highlighting)
- [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)
- [Python-Markdown](https://python-markdown.github.io/extensions/fenced_code_blocks/#language)
- [w3schools.io](https://www.w3schools.io/file/markdown-code-fence-blocks/#markdown-code-fenced-blocks) (except `ECMAScript`)
- [JetBrains](https://www.jetbrains.com/help/hub/markdown-syntax.html#fenced-code-blocks)
- [Vercel](https://next-book.vercel.app/reference/fencedcode)

Libraries don't support uppercase:

- Prettier playground doesn't highlight code block when language has uppercase letters.
- Prettier doesn't format code block: in the example, it should have used double-quotes and a semicolon.
- GitLab doesn't apply syntax highlighting if the language has an uppercase letter.
- https://github.com/preservim/vim-markdown/issues/618
- https://github.com/jonschlinkert/sublime-markdown-extended/issues/157
- [Markdown Editor](https://jbt.github.io/markdown-editor/#S0hI8EosSwxOLsosKOFKzs8rzs9J1cvJT9dQT8vPV9fkSkhI4AIRWUBVxfhUAQA=)
- [Markdown Viewer](https://codebeautify.org/markdown-viewer/y24aef164) (only `javascript` in input is highlighted)

**Comment by fisker** [comment]
I don't think it's Prettier's job to do. We can't make "incorrect" code to "correct" one.
