### ISSUE TITLE
Parentheses around nullish coalescing operator within negation

### ISSUE THREAD

**Issue by HolgerJeromin** [prettier/prettier#16480]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEkA2BXAWygBE4AzASygpgukwF5Ng4ATGgQwCMc4kYATnjgBfANwAdKJCgZMAuB1YB5KDgCejTAEJchEuSo06UAHRtOPOJgD8NzIOFiQAGhAQADrXTJQHAQIQAO4ACv4IaMggHABuEBSsriBcAhxgANZwMADKHARwADJUcMhkHDhocG4paZk5HmlUAObIjlUglQQUrULtcAAeHnACFPmw5QAqw1D+FHCRSGUV7WjNvACKeBDwpeWVbgBWaP3Za3Cb2yWLe+0AjlvwIYEeC9FoALRQcGxsSYIcFBwzQAwhACAQOFEoNASm5VlAmrwAIIwQQULh4R7DIpfXbLNwACxgBBwAHUCTR5g0wHBshFjDEaOoomA0JE3DFhABJKCsBA5MAjLxI3nZGDqXh4-YgDyBSqk1IeKKy+bDGKwkBUSoCGBPDhNCFS9oNATaqLioZoQUULxJWVUGCkhIwAnIAAcAAY3Ap7hQFHqDZDrviQDBuE7WC7kAAmNx4SoTbgLJbSuAELhsPmsAocBF4fVwABiEAEENRzSiHExECSR36ACFUhksrl8jirinRCIgA)

```sh
--parser typescript
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx
const columnDefinition = {editable:true};
const readOnly = !columnDefinition.editable ?? true;
```

**Output:**

```tsx
const columnDefinition = { editable: true };
const readOnly = !columnDefinition.editable ?? true;

```

**Expected output:**

```tsx
const columnDefinition = { editable: true };
const readOnly = !(columnDefinition.editable ?? true);
```

**Why?**

I had to check in devtools if `!` or nullish coalescing operator has higher priority.

**Comment by fisker** [comment]
```js
!columnDefinition.editable ?? true;
```

is equivalent to

```js
(!columnDefinition.editable) ?? true;
```

not

```js
!(columnDefinition.editable ?? true);
```

**Comment by fisker** [comment]
[`no-constant-binary-expression`](https://eslint.org/docs/latest/rules/no-constant-binary-expression) can be helpful

**Comment by HolgerJeromin** [comment]
Yes! Thank you very much for your quick reply.
Will add the eslint rule in my code base.
