### ISSUE TITLE
Modification of nested arrays inside format string

### ISSUE THREAD

**Issue by manugoyal** [prettier/prettier#16493]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXnQAwCTADahAjADToBMAuhYQMwUAs11AvjiGSBAA4wBLaAGdkoAIYAnSRADuABSkJRKcQBtZ4gJ6juAI0niwAazgwAyuIC2cADICocZADN1wuPsMmz53kYcA5sgwkgCuHiDuVgLBYRFwqLxwkgI2sOoAKslQUgJwKq5q7tzCgWpwAIqhEPAubhEAVsKo5mWV1bVIhcUgAI4dcPIyvCog4sIAtI5wACazXCAh4gJqgQDCEFZW4shjamoLpVAB5QCCMCECeqHw8sn2jnVFEQAWMFZqAOovAvDCfmA4OZlL8BAA3X5aXZgYS6EBg8IASSgc1g5jAKX4pxR5hgWnKTx6vBk7k+hl4u2J+WSYKc3Ac7kkMCG4gC20JET8kkZuz04j0cAO3GJDhgnwEMxgL2QAA4AAzcSRwfoCJUstk7Lr1bgwfniyXSpCUbihdwZfkFbUgOBWAUzOYzWziY6hVlwABiEEk2wugV24huEBAbDYQA)

```sh
# Options (if any):
None
```

**Input:**

```jsx
x = `${[[1, 2], [3, 4]]}`
````

**Output:**

```jsx
x = `${[
  [2],
  [4],
]}`;
```

**Expected output:**

```jsx
x = `${[
  [1, 2],
  [3, 4],
]}`;
```

**Why?**

Prettier is changing the actual array contents, which it should not. Seems like it always takes the last element of each nested array.

I can work around it by pulling the array out into a separate variable ([playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDATugBAXiwbXwEYAaLAJgF0z8BmMgFksoB0oAPXLAAwBJgM6AL7cQJEBAAOMAJbQAzslCCIAdwAKGBIpSoANqtQBPReIBG6VGADWcGAGVUAWzgAZGVDjIAZvvlxzSxs7e0krDwBzZBh0AFcAkH8nGWi4hLh2STh0GRdYfQAVbKgMGTgdXz1-cXlIvTgARViIeB8-BIAreXZ7Osbm1qRK6pAARwG4dXQpHTR5AFpPOAATFbEQGNQZPUiAYQgnJ1RkND09ddqoCPqAQRgYmTNY+HVs9082qoSACxgnPQA6t8ZPB5GEwHB7NoQTIAG4gownMDyUwgWHxACSUFWsHsYBy0hu2PsMCM9U+I0k038AMskhOVPK2VhXnEHn86BgU1QESOFISYXQHJOZlQZjg53EVI8MABMmWMG+yAAHAAGcToODjGSa7m845DdriGBiuUKpVIcjiWL+ApiipGkBwJzi5arZauVBXWI8uAAMQg6CO90iJ1QzwgICEQiAA)).

**Comment by kachkaev** [comment]
> Seems like it always takes the last element of each nested array.

yep

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXnQAwCTADahAjADToBMFAzALoWE0UAsFArHXQL44hkgIABxgBLaAGdkoAIYAnORADuABXkIpKGQBslMgJ5SBAIzkywAazgwAyjIC2cADKiocZADMdEuCbOXrGyFzVwBzZBg5AFdfEB97UQjo2LhUITg5UUdYHQAVDKh5UThNL20fAQkw7TgARSiIeE9vWIArCVQbarqGpqQyipAAR164FUUhTRAZCQBaNzgAEyX+EEiZUW0wgGEIe3sZZGntbVWqqFCagEEYSNFjKPgVDJc3ZvLYgAsYe20AdU+ongEmCYDgNg0QNEADcgfojmAJEYQNCYgBJKDLWA2MCZERXTE2GD6GrvQZCRQ+P5mIRHCklDLQ9wCVw+OQwcYyUIHMmxYJyNlHYwyYxwU4CCmuGB-USLGCfZAADgADAI5HARqJ1ZzuYd+i0BDARTK5QqkNQQFEfLkRaUDSA4PZRYtlosnDILlEuXAAGIQOQHW5hI4yR4QEDcbhAA)

```sh
--parser babel
```

**Input:**

```jsx
x = `${[[1, 2, 3], [3, 4, 5]]}`
```

**Output:**

```jsx
x = `${[
  [3],
  [5],
]}`;

```

**Second Output:**

```jsx
x = `${[[3], [5]]}`;

```
