### ISSUE TITLE
why not format dist directory

### ISSUE THREAD

**Issue by imtaotao** [prettier/prettier#16523]
{
  "format": "prettier --write --parser typescript \"(src|demo|dist)/**/*.((m)?js|ts?(x))\""
}

This will only format files in the src and demo directories, why doesn't it work for the dist directory? I haven't added any filtering rules, this is only happening in `v3`, `v2` works fine.

**Comment by fisker** [comment]
https://prettier.io/blog/2023/07/05/3.0.0#ignore-gitignored-files-by-default-14731httpsgithubcomprettierprettierpull14731-by-fiskerhttpsgithubcomfisker
