### ISSUE TITLE
Prettier check fails with a suggestion that is incorrect syntax.

### ISSUE THREAD

**Issue by nabing8** [prettier/prettier#16527]
**Prettier 3.3.3**

```json
# Options (if any):
{
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "arrowParens": "avoid",
  "endOfLine": "auto"
}

```

**Input:**

```jsx
// code snippet
toast({
  message:
    ((e as Error)?.message ?? isJobSaved)
      ? "Failed to unsave job. Please retry."
      : "Failed to save job. Please retry.",
  type: "success",
});
```

**Output:**
Prettier check fails with  
```
Replace `e·as·Error)?.message·??·isJobSaved` with `(e·as·Error)?.message·??·isJobSaved)`
```

**Expected output:**
```
For prettier check not to fail.
```

**Why?**
```
The code is already formatted as per the config and the suggested change is incorrect syntax.
```

**Comment by kachkaev** [comment]
👋 @nabing8! I think it’s to do with using JS (babel) parser for TypeScript code (`as` syntax). Here is a similar case in the playground:

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPJmoCuAtgEZwBOmAvJgCwBMIANCBAA4wCW6yoAhuXIQA7gAUBCNMhB8ANsL4BPKSxLk+YANZwYAZT5E4AGU5Q4yAGZy0cVeq07dbDaYDmyGOQK2QNopw8vHzhsNgpOQ1g5ABUKKAFOOCkkK1kbFjQ3WTgARQIIeEtrHwArNGxdLNz8wpTilgBHGrhRITZkmTQAWjM4ABN+5hBPPk5ZNwBhCCIiPmk5WSHMqFdsgEEYT04SAnhRChMzIrSfAAsYIlkAdVPOeDRnMDhdSTvOADc7xWkwNBUQd7eACSUAGsF0YHInA4a1Buhgimyx3SIDYQhsV3UbGkaKSFHe5hYphs5BgrT4rlmyJ8znIJOkJD4ZEWLDRphgV04fRgp2QAA4AAwschwJqcEXkylzOonFgwJmc7m8pD0FgEGzRJnJVIouCkfoDPpGPgrAgUuAAMQg5Fmmzc812EBAAF9nUA)

```sh
--parser babel
```

**Input:**

```jsx
const x: number = 42
```

**Output:**

```jsx
SyntaxError: Unexpected token (1:8)
> 1 | const x: number = 42
    |        ^
```

**Second Output:**

```jsx
SyntaxError: Unexpected token, expected "," (1:33)
> 1 | SyntaxError: Unexpected token (1:8)
    |                                 ^
  2 | > 1 | const x: number = 42
  3 |     |        ^
```

---

Switching to `babel-ts` or `typescript` as parser works well for your example.

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMIEMDOMAUwA6UABEQLZyaboDmcShJJOOcRWRAogE5cRcCUAfgB05SjVaDBRAJaYAUhABGAZXQA3OABN+DRiWn4QAMXQyANtqJoiAVyhVNRAFbLhRAAqWsrLnBhcAJ7CRnr6SERGphZWNo6srkruXnA+RH4BwUYANHowgQAOdJEgmLZgYBSYOYQAvvwA3ISEINkgEAUwMtCYyKDoPBAA7h4DCL0o6OZD6IG9bUpc6GAA1v5q5AAyMlBwyABmU5hwC0ur6wXLO9TIAbYnpXCkMrdc921wAB5FXDLksFMACpwLhQAYyCgHI4PTDXSwARVsEHgUPMxzazkwnxUcLgiOReyQhzRDwAjkj4B5eAUJiAsABaXbabStVBLCzXADCEFIpHQyDp5nMrNhUGolgAgjAAjIlLZKSDtrtUeiQAALGCkcwAdTVMngmEulRU431MnU+sCArAlFZ6nuAEkoFoEDAVGBfp0Jc6VPlLCqHgVeMdtUsCgKgxQQZpWTtjlwYFSaHyA21Llx4wKlOglHBzPSYPMQEGdjBtTItDA1cgABwABjafnJMj8SeoKaJ0LaMBz5cr1aQACY2rZjoCcxNiaqnrmtC6tJt0GLbBJjHw+dLrgL0PKICBarUgA)

```sh
--parser babel-ts
```

**Input:**

```tsx
toast({
  message:
    ((e as Error)?.message ?? isJobSaved)
      ? "Failed to unsave job. Please retry."
      : "Failed to save job. Please retry.",
  type: "success",
});


```

**Output:**

```tsx
toast({
  message:
    ((e as Error)?.message ?? isJobSaved)
      ? "Failed to unsave job. Please retry."
      : "Failed to save job. Please retry.",
  type: "success",
});

```

---

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMIEMDOMAUwA6UABEQLZyaboDmcShJJOOcRWRAogE5cRcCUAfgB05SjVaDBRAJaYAUhABGAZXQA3OABN+DRiWn4QAMXQyANtqJoiAVyhVNRAFbLhRAAqWsrLnBhcAJ7CRnr6SERGphZWNo6srkruXnA+RH4BwUYANHowgQAOdJEgmLZgYBSYOYQAvvwA3ISEINkgEAUwMtCYyKDoPBAA7h4DCL0o6OZD6IG9bUpc6GAA1v5q5AAyMlBwyABmU5hwC0ur6wXLO9TIAbYnpXCkMrdc921wAB5FXDLksFMACpwLhQAYyCgHI4PTDXSwARVsEHgUPMxzazkwnxUcLgiOReyQhzRDwAjkj4B5eAUJiAsABaXbabStVBLCzXADCEFIpHQyDp5nMrNhUGolgAgjAAjIlLZKSDtrtUeiQAALGCkcwAdTVMngmEulRU431MnU+sCArAlFZ6nuAEkoFoEDAVGBfp0Jc6VPlLCqHgVeMdtUsCgKgxQQZpWTtjlwYFSaHyA21Llx4wL8kVMB6ZJ1WUGdjBtTItDA1cgABwABjafnJMj8SeoKaJ0LaMHQSlL5crSAATG1bMdAd2JsTVU8lNoXVpNugxbYJMY+HzpdcBeh5RAQLVakA)

```sh
--parser typescript
```

**Input:**

```tsx
toast({
  message:
    ((e as Error)?.message ?? isJobSaved)
      ? "Failed to unsave job. Please retry."
      : "Failed to save job. Please retry.",
  type: "success",
});


```

**Output:**

```tsx
toast({
  message:
    ((e as Error)?.message ?? isJobSaved)
      ? "Failed to unsave job. Please retry."
      : "Failed to save job. Please retry.",
  type: "success",
});

```

---
How did you come up with the issue? Just trying to understand how you got the wrong parser applied – it should be picked automatically.
