### ISSUE TITLE
[MDX] An unexpected newline is added between the return statement and the function's closing brace

### ISSUE THREAD

**Issue by ony3000** [prettier/prettier#16522]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPAISJhmgHFsIiNqBDAZ3LC4AoAlHmAAdKHjzY4MItgn9xkyQB4AJuQBuAPiXLVtekxZtdE-cpWGGUbQHkocFQHpr0MxctvbAFQDuEC7eHp54VnQ22j4AFtJOrhHuevpBiVDMrBghqs4aOnqCANziAL4gADQgEBgU0FzIoBzYLH4ACk0I9SgcADZ+HACe9ZUARtgcYADWMgDKHAC2cAAy5I7IBL1ccKPjU7MYE6sA5sgw2ETbIFvz5Kfnl+gYcNjki7C9Ps9QTeRwXRs9LaVHhQI49OAARSIEHg602lwAVlw0DNjuCoTC4HDAZcAI7Q+CtFgYLogbgAWkccDU1IqIDOHHIPWOAGEIPN5hxkGSej06SCwXAAIL0F4jOhwVrPFZrJAAoEgaIweY9ADq0XI8C4BzAcBmnU1Wk1A25fGGIE0FwAklAabAZmAXjUhbaZjABuDsQqMCwtqrxhhuT6-s9NFjKqstrgiRwjpyvZcDtgo9z5mo0HSfasYKryGoYNFkAAOAAMlWk+PI0hjca5cvhlRgHBGufzhaQACZKkQtj5m-8G6h5iNqTS1EsOKCiLG4AAxHCc+jHbkcOgQEAlEpAA)

```sh
--parser mdx
```

**Input:**

```mdx
export function ButtonGroupBasics() {
  return (
    <div>
      <ButtonGroup>
        <Button>One</Button>
        <Button>Two</Button>
        <Button>Three</Button>
      </ButtonGroup>
    </div>
  );
}
```

**Output:**

```mdx
export function ButtonGroupBasics() {
  return (
    <div>
      <ButtonGroup>
        <Button>One</Button>
        <Button>Two</Button>
        <Button>Three</Button>
      </ButtonGroup>
    </div>
  );


}

```

**Expected output:**

```mdx
export function ButtonGroupBasics() {
  return (
    <div>
      <ButtonGroup>
        <Button>One</Button>
        <Button>Two</Button>
        <Button>Three</Button>
      </ButtonGroup>
    </div>
  );
}

```

**Why?**

This issue does not occur when I add a newline at the end of the input. I don't think it's natural that a single character difference would cause a difference of two line breaks.

Also, when I run the second format on the output of this issue (the first format), the two outputs are not equivalent.

**Comment by kachkaev** [comment]
:wave: @ony3000! This issue should be fixed as part of MDX1 → MDX3 migration. Let’s follow it in #12209
