### ISSUE TITLE
Nested arrow function should have a trailing newline when expanded as last arg

### ISSUE THREAD

**Issue by jsnajdr** [prettier/prettier#1652]
Expanded arrow function as a last arg gets a trailing newline before the closing paren:
```js
f(action =>
    dispatch(action),
);
```
This doesn't happen, however, for a nested (curried) arrow function.

**Actual result:**
```js
f(action => next =>
    next(action));
```
**Expected result:**
```js
f(action => next =>
    next(action),
);
```

When printing an `ArrowFunctionExpression` with the `expandLastArg` option, maybe this option should be passed down to the nested `ArrowFunctionExpression`?

**Comment by lydell** [comment]
I tried to reproduce this, but failed. Am I missing something?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22fooooooooooooooooooooooooooooooooooooooooooooooooooo(action%20%3D%3E%5Cn%20%20%20%20dispatch(action)%2C%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by k15a** [comment]
@lydell You need 2 nested arrow functions.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22fooooooooooooooooooooooooooooooooooooooooooooooooooo(action%20%3D%3E%20next%20%3D%3E%5Cn%20%20%20%20dispatch(action)%2C%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
