### ISSUE TITLE
Strip trailing decimal zeroes? 2.0 → 2

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#1653]
Prettier already does some normalization on numbers:

```
1E+06 → 1e6
1e0 → 1
.5 → 0.5
2. → 2
```

Should we also removing trailing decimal zeroes? Examples:

```
2.0 → 2
2.000 → 2
2.01234500 → 2.012345
1.200e3 → 1.2e3
```

Arguments for:

- Consistent with the already existing rules to remove trailing dot, and remove unnecessary zeroes in scientific notation.
- JavaScript does not have ints and floats. This could help as a reminder.

Arguments agains:

- Some people are used to `2` being an int and `2.0` being a float in other languages, and seeing `x / 2` rather than `x / 2.0` immediately catches their attention.
- Fear of being a controversial change.

PR: #1639

**Comment by azz** [comment]
What about something like this?

```js
2.0 → 2.0
2.000 → 2.0
2.01234500 → 2.012345
1.200e3 → 1.2e3
```

**Comment by vjeux** [comment]
Feel free to send a pr for what you suggest @azz,  I don't reallu care about this specific part.

**Comment by azz** [comment]
Any excuse to test my regex fu! #1768

**Comment by lydell** [comment]
@azz Just because I’m curious, do you also think that `2.0 → 2` is a controversial change? What does the programmer gain by specifying `.0`? :)

**Comment by azz** [comment]
To me, I wouldn't mind stripping the `.0`. However I can see how others (esp. from other programming language backgrounds) could find it controversial.

I'd be interested to see a larger set of opinions on this, but at the same time, it's a pretty minor thing.

**Comment by SimenB** [comment]
I've learned to do `2d` in java when I want it as a double.

I think this is the PR that should be merged, mostly because it's what JS does when i interprets it.

```js
console.log(2); // => 2
console.log(2.0); // => 2
console.log(2.5); // => 2.5
console.log(2.500); // => 2.5
```

**Comment by lydell** [comment]
@SimenB Do you mean #1639 or #1768?

**Comment by SimenB** [comment]
Oh, thought this was the PR, sorry! I meant #1639 😄

**Comment by azz** [comment]
In Python 2, Ruby, C, C++, C#, Java, Swift (probably many others):
```py
3 / 2 == 1
3 / 2.0 == 1.5
```

But thinking about it more, I don't know it that's an argument for or against removing trailing zeros...

**Comment by SimenB** [comment]
That's not true in JavaScript, though. Also (at least in java), you can do this `3 / 2d == 1.5`, which I think is a better pattern.

>But thinking about it more, I don't know it that's an argument for or against removing trailing zeros...

It's the only argument against, isn't it?

**Comment by azz** [comment]
> It's the only argument against, isn't it?

Yes, but it could be an argument for, as well. If a formatting tool is removing `.0` it could serve as education or reassurance for devs less familiar with the language.

**Comment by azz** [comment]
Do we still want to do this?

My thoughts are it is such a minor thing that it might not be worth changing peoples code.

**Comment by vjeux** [comment]
Yeah, let's close this. Thanks @lydell for working on this area :)
