### ISSUE TITLE
Any thoughts on making `getPreferredQuote` part of the public `util` API?

### ISSUE THREAD

**Issue by Janther** [prettier/prettier#16537]
Since `makeString` is already public and many languages support strings declared with single and double quotes, providing this functionality would benefit many plugins.

**Comment by fisker** [comment]
I guess it's acceptable. [implementation](https://github.com/prettier/prettier/blob/main/src/utils/get-preferred-quote.js)

**Comment by sosukesuzuki** [comment]
It sounds good to me
