### ISSUE TITLE
Remove useless escapes in untagged template literals

### ISSUE THREAD

**Issue by Conaclos** [prettier/prettier#16542]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBnA3AHSm0wF5MADffAQ3IKNM3xCuud0xABoQIAHGAEto2ZKGoAnCRADuABUkJRKaqhnUAnqJ4AjCdTABrDAGVqAWzgAZQVDjIAZquxxd+o6b4HbAc2QwJAFdXEBdzQX8gkLgADz44CUFLWFUAFQSoSUE4ZSdUFx5sX3QARUCIeEdnEIArbBiTYrgyivskPIKQAEdy+DlpPmUQamwAWjs4ABMp7hAA6kFUXwBhCHNzamRh1FRZoqgfdABBGADBHUC+hJs7KvyQgAsYc1QAdQfBeGwvMDgTJU+ggAbp8NFswNhtCAgcEAJJQaawExgRICI4IkwwDToO6dPjSFyvfR8Lb4nIJIH2Hi2FwSGD9ag+Da4kJeCS0rY6ag6OC7Hj42wwV6CSYwB7IAAcAAYeBI4D1BHKGUzNu1qjwYNzhaLxUgAEw8QIuVLc3LqkBwcw8ybTSZWagHQKMuAAMQgEg2p18W2olwgIAAvgGgA)

```sh
--parser babel
```

**Input:**

```jsx
let s;
s = `\a`;
s = "\a"; 
```

**Output:**

```jsx
let s;
s = `\a`;
s = "a";

```

**Expected output:**

```jsx
let s;
s = `a`;
s = "a";
```

**Why?**

Prettier already removes useless escapes in regular strings.
While it is not safe to remove useless escapes in tagged template literals, it seems safe to me to do so in untagged template literals.
For consistency with regular strings, Prettier could remove them.

**Comment by sosukesuzuki** [comment]
I think this is acceptable.

**Comment by sosukesuzuki** [comment]
After discussing it in [prettier/prettier#16562](https://github.com/prettier/prettier/pull/16562), my perspective has changed. We now believe that removing useless `\` from string literals and template literals should be the responsibility of a linter. Therefore, we will drop support for removing useless `\` from string literals.
