### ISSUE TITLE
Prettier dont add semicolon in CSS

### ISSUE THREAD

**Issue by rogerwindberg** [prettier/prettier#16545]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHSh2JwAcBDDDASygHMkcAGQknAW3ICc7bGWoAXxAAaEBFIxq0AM7JQ3LhADuABW4I5KcgBtl5LHLGou5MAGs4MAMrl2cADK04yAGa6ZcY6YtXrFMFo6ZBguAFcvEE92ahDwyLgAD1I4Lmp7WF0AFVSobmo4LXcdTzEZIJ04AEUwiHg3D0iAKxlE6wrq2vqkYtKQAEcuuFUlUi0QchkAWig4OAx50RBQ8modIIBhCHZOZAmdHSXy+kqAQRhQ6lQw+FVUp1mGksiACxh2HQB1F+p4GQC4NZNL9qAA3X5YPZgGRGECgiIASSgC1g1jAaUkp2R1hgWEqTz6pCUnk+plIeyJhVSoJcYloni4MBG5Doux6jTEFC4DL2qHIqDgh05aVgn2oGBgL2QAA4mGIuHBBtQFczWeQCZEYPyxRKpUgAExiMKeLL8oockBwdgCqjzBzkehhFlwABiEC4nAuQT25BuEBAgkEQA)

```sh
# Options (if any):
semi: true
```

**Input:**

```css
body {
    padding: 0
    margin: 0
}
```

**Output:**

```css
body {
    padding: 0
    margin: 0
}
```

**Expected output:**

```css
body {
    padding: 0;
    margin: 0;
}
```

**Why?**

Prettier is expected to format the CSS by adding semicolons at the end to fix errors.

**Comment by fisker** [comment]
It's invalid CSS, we only format **valid** code.

**Comment by rogerwindberg** [comment]
> It's invalid CSS, we only format **valid** code.

And how will the CSS be valid if it doesn't have the semicolon that should be added by Prettier? Does not make sense

**Comment by fisker** [comment]
Prettier only works if your INPUT is valid. We don't turn invalid code to valid.  You can check your INPUT with [this online tool](https://jigsaw.w3.org/css-validator/) or other tool to validate your code.

**Comment by kachkaev** [comment]
CSS is unlike JS WRT semicolons. Newline does not necessarily mean ‘end of statement’. This is valid CSS, for example:

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHSh2JwAcBDDDASygHMkcBGUgD0JJwCY2cBmNhxIAWQVAC+IADQgIpGNWgBnZKHIAndRADuABQ0IVKcgBtt5LCpmp15MAGs4MAMrkAtnAAytOMgBmpkpw1rYOTs4UYLR0yDDqAK7BIEFu1LEJSXCspHDq1B6wpgAquVAa1HBGASZBMkrRJnAAivEQ8P6BSQBWSqzODc2t7UjVtSAAjkNwulqkRiDkSgC0UHBwGOvSIHHk1CbRAMIQbm7kyAsmJlv19I0AgjBx1Kjx8Lq53qsdNUkAFjBuEwAdV+1HgSkicGchjB1AAbmCsOcwEorCA4YkAJJQDawZxgPLyO445wwLCNb5jUhaIJA2ykc7Uyq5OG+GS0ILqGAzch0U6UpIUdSc5GorbU2gwIHUDAwX7IAAcAAYZOo4JNqGqeXyziNOjIYORUNLZfKkFwZPEgkUjVV9SA4G5UOsNhhPOR6PFeXAAGIQdSnR7Rc7kV4QEDicRAA)

```sh
--parser css
```

**Input:**

```css
body {
    padding: 1px
    2px 3px
    4px
}
```

**Output:**

```css
body {
  padding: 1px 2px 3px 4px;
}

```

A colon in the value (e.g. between `2px and 3px`) is a syntax error:

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHSh2JwAcBDDDASygHMkcBGUgD0JJwCY3GBmNhxIAWQVAC+IADQgIpGNWgBnZKHIAndRADuABQ0IVKcgBtt5LCpmp15MAGs4MAMrkAtnAAytOMgBmpkpw1rYOTs4UYLR0yDDqAK7BIEFu1LEJSXCspHDq1B6wpgAquVAa1HBGASZBMkrRJnAAivEQ8P6BSQBWSqzODc2t7UjVtSAAjkNwulqkRiDkSgC0UHBwGOvSIHHk1CbRAMIQbm7kyAsmJlv19I0AgjBx1Kjx8Lq53qsdNUkAFjBuEwAdV+1HgSkicGchjB1AAbmCsOcwEorCA4YkAJJQDawZxgPLyO445wwLCNb5jUhaIJA2ykc7Uyq5OG+GS0ILqGAzch0U6UpIUdSc5GorbU2gwIHUDAwX7IAAcAAYZOo4JNqGqeXyziNOjIYORUNLZfKkFwZPEgkUjVV9SA4G5UOsNhhPOR6PFeXAAGIQdSnR7Rc7kV4QEDicRAA)

```sh
--parser css
```

**Input:**

```css
body {
    padding: 1px
    2px: 3px
    4px
}
```

**Output:**

```css
SyntaxError: CssSyntaxError: Missed semicolon (2:17)
  1 | body {
> 2 |     padding: 1px
    |                 ^
  3 |     2px: 3px
  4 |     4px
  5 | }
```

**Second Output:**

```css
SyntaxError: CssSyntaxError: Unknown word (3:3)
  1 | SyntaxError: CssSyntaxError: Missed semicolon (2:17)
  2 |   1 | body {
> 3 | > 2 |     padding: 1px
    |   ^
  4 |     |                 ^
  5 |   3 |     2px: 3px
  6 |   4 |     4px
```
