### ISSUE TITLE
Inconsistent and almost certainly incorrect HTML tag splitting

### ISSUE THREAD

**Issue by jeremy-rifkin** [prettier/prettier#16544]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFgRgHyoIYAE6ATnAGYC8AOiOjDAA4DOSA9K2RBAHQBGexPngBefAJbCa2AGJcCAIQEFUYgmAA2eJk2ogyeALS9ieKABMmBfQYDmYmOgCuvKalZjcrPJ6zYQAGhAIBhgxaCZkUAFiCAB3AAUBBAiUPHVYvABPCMDjPDAAazgYAGU8AFs4ABkxKDhkfXUmOFyTQuKShnzam2QYYkcWkGbysT6BobgADwY4YjFK2DSAFTmoATE4FMbmwKYe9TgARUcIeAa03ZAAKyYpkoPj0-OkHaGAR2e4eJjmZBAtAY6nAzCCAiB+ngxOoegBhCDlcp4f5pdTg-ZQGyHACC9HmvEc8HicxqdQuTSGdHK6gA6uh7FsumA4CVkvYxAA3eyZf5gbTgjmDACS5gQpTA8xC2PMJRgmUO5KuDBizRpJgY-2VWzmHPqgVqzWIMB+eBsSMVQy6xEN-ypaMCytqMBpYjMDmQAA4AAyBUifMSkE1m5GvS5DGB4Xgut3oZAAJkCjmay0j2zDgTg5V4INBZiqphsjlNcFkxCR9B6KMJEBAAF9a0A)

```sh
# Options (if any):
```

**Input:**

```html
<h1><a href="https://foo.bar.baz.biz">Foo Bar <i class="fa-brands fa-github"></i></a></h1>
```

**Output:**

```html
<h1>
  <a href="https://foo.bar.baz.biz"
    >Foo Bar <i class="fa-brands fa-github"></i
  ></a>
</h1>
```

**Expected output:**

```jsx
<h1>
  <a href="https://foo.bar.baz.biz">
    Foo Bar <i class="fa-brands fa-github"></i>
  </a>
</h1>
```

**Why?**

I'm not opinionated about html formatting here, however, I don't think the behavior I'm seeing with html tags being split inconsistently can possibly be correct.

Also related: #15982

**Comment by fisker** [comment]
Check https://prettier.io/blog/2018/11/07/1.15.0#whitespace-sensitive-formatting

**Comment by jeremy-rifkin** [comment]
Oh I see, that makes sense and completely slipped my mind. Thank you so much!
