### ISSUE TITLE
Incorrect formatting of bracketed properties in TypeScript classes with `--no-semi`

### ISSUE THREAD

**Issue by benlesh** [prettier/prettier#16573]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATOAHBXWNTAXkwGUBPAWwCMIAbACgHJcCoiY1WBKADpRIUDDnyEEYAJZwS5avSZsOk4bN6Dh6LFAi4KMAIYwArvMq0GLVnoPGzmoUOmw4AJwBmRsHEwAVdzg4ADl9P2AhTEwAbVUuBB4AXSRKOBgAHkDgsNwAPijY+KIZORS0zOzQ8IKoaJi7OEMTc3LWCABrVkwAH0xWDCNGOFYhAF9nYUYjNBIqgDUh0z9pGjxhmkS5oOrcTEi6ookE4iSyTCg4AHcKrJ3cuDzmLXriqQ0z8kubinS7nJqz0KDXCzUcn36nVGUAmUBAABoQBA8DBpOhkKAjO53BArgAFLEINDIEBDK5GKjExF0dw+DrpChGTYAGVccGQ3kYaDg1NpYHpMAoeB8rgA5sgYO5lojuTRpByhtzEXAAB4EdyrRJDfweKBYjQKrk8kBoMXDACKpgg8ENSpAACs0CqKGa4JbreykJy7QBHK3wPE4vDElAzAC0lzguGwCJAkqM0kYYoAwhAaDQjCShoxY6aoKLhgBBGCS6R0UwBjysy6240ACxgNEYAHU69J4Ghhb5fqJ29IAG7tqgksCzWP95YASROgrAGpRha4hiow1riLwOO5zdpeBJG7kHn77MRrm57hggaMooza5AwvcZ5JMCoBDQc+kKNjG9cMGb0mwMB1sgAAcAAMiJBH60hBJe16Zl6irGsYdB-gBQFIAATIi5hwP4Rh0CG3rGnA9BRtGzJGPmphXnAABiEDuBmJZilmFYQCAYxjEAA)

```sh
--parser typescript
--no-semi
```

**Input:**

```tsx
const dependents = Symbol('dependents')
const dependencies = Symbol('dependencies')
const nodeStatus = Symbol('nodeStatus')

interface TreeNode {
  [dependents]: Set<TreeNode>
  [dependencies]: Set<TreeNode>
  [nodeStatus]: 'ok' | 'stale'
}

class TreeValue implements TreeNode {
  [dependents] = new Set<TreeNode>()
  [dependencies] = new Set<TreeNode>()
  [nodeStatus] = 'ok'
}

```

**Output:**

```tsx
const dependents = Symbol("dependents")
const dependencies = Symbol("dependencies")
const nodeStatus = Symbol("nodeStatus")

interface TreeNode {
  [dependents]: Set<TreeNode>
  [dependencies]: Set<TreeNode>
  [nodeStatus]: "ok" | "stale"
}

class TreeValue implements TreeNode {
  [dependents] =
    (new Set<TreeNode>()[dependencies] = new Set<TreeNode>()[nodeStatus] = "ok")
}

```

**Expected output:**

```tsx
const dependents = Symbol('dependents')
const dependencies = Symbol('dependencies')
const nodeStatus = Symbol('nodeStatus')

interface TreeNode {
  [dependents]: Set<TreeNode>
  [dependencies]: Set<TreeNode>
  [nodeStatus]: 'ok' | 'stale'
}

class TreeValue implements TreeNode {
  [dependents] = new Set<TreeNode>();
  [dependencies] = new Set<TreeNode>();
  [nodeStatus] = 'ok'
}
```

**Why?**

Otherwise, the code will output a class lacking the `[dependencies]` and `[nodeStatus]` properties, and the `[dependents]` property will be set to `'ok'`. Which is clearly not the intent of the code.

**Comment by fisker** [comment]
> Which is clearly not the intent of the code.

That's not true in your case, your input need add semi, our parser see your code as member expression. You need add semicolon yourself.

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATOAHBXWNTAXkwGUBPAWwCMIAbACgHJcCoiY1WBKADpRIUDDnyEEYAJZwS5avSZsOk4bN6Dh6LFAi4KMAIYwArvMq0GLVnoPGzmoUOmw4AJwBmRsHEwAVdzg4ADl9P2AhTEwAbVUuBB4AXSRKOBgAHkDgsNwAPijY+KIZORS0zOzQ8IKoaJi7OEMTc3LWCABrVkwAH0xWDCNGOFYhAF9nYUYjNBIqgDUh0z9pGjxhmkS5oOrcTEi6ookE4iSyTCg4AHcKrJ3cuDzmPgBuQrjjko0z8kubinSdxyNWeb0ODXCzUcP36nVGUAmUBAABoQBA8DBpOhkKAjO53BArgAFPEINDIEBDK5GKjk1F0dw+DrpChGTYAGVccGQ3kYaDg9MZYGZMAoeB8rgA5sgYO5lqj+TRpDyhvzUXAAB4EdyrRJDfweKB4jQqvkCkBoKXDACKpgg8FNapAACs0BqKFa4Lb7dykLynQBHO3wIkEvDklAzAC0lzguGwKJAsqM0kYUoAwhAaDQjBShoxE5aoJLhgBBGCy6R0Uwhjycy6O80ACxgNEYAHUm9J4Ghxb4AaJu9IAG7dqgUsCzRPD5YASROorAOoxpa4hiow0bqLwBP57cZeApO7kHmH3NRrn57hgoaMkpzW5A4vcV4pMCoBDQS+kGMTO9cMDttI2AwE2yAABwAAyokEQbSEEt73rmfqquaxh0EBIFgUgABMqLmHA-hGHQEb+uacD0HG8bskYxamHecAAGIQO4OYVlKeY1hAIBjGMQA)

```sh
--parser typescript
--no-semi
```

**Input:**

```tsx
const dependents = Symbol('dependents')
const dependencies = Symbol('dependencies')
const nodeStatus = Symbol('nodeStatus')

interface TreeNode {
  [dependents]: Set<TreeNode>
  [dependencies]: Set<TreeNode>
  [nodeStatus]: 'ok' | 'stale'
}

class TreeValue implements TreeNode {
  [dependents] = new Set<TreeNode>();
  [dependencies] = new Set<TreeNode>();
  [nodeStatus] = 'ok'
}

```

**Output:**

```tsx
const dependents = Symbol("dependents")
const dependencies = Symbol("dependencies")
const nodeStatus = Symbol("nodeStatus")

interface TreeNode {
  [dependents]: Set<TreeNode>
  [dependencies]: Set<TreeNode>
  [nodeStatus]: "ok" | "stale"
}

class TreeValue implements TreeNode {
  [dependents] = new Set<TreeNode>();
  [dependencies] = new Set<TreeNode>();
  [nodeStatus] = "ok"
}

```

**Comment by benlesh** [comment]
> That's not true in your case

So you're saying that you think it's unclear what the intention of this code is?

```ts
class TreeValue implements TreeNode {
  [dependents] = new Set<TreeNode>()
  [dependencies] = new Set<TreeNode>()
  [nodeStatus] = "ok"
} 
```

Or more concisely:

```js
class TreeValue {
  [dependents] = new Set()
  [dependencies] = new Set()
  [nodeStatus] = "ok"
}
```

It's actually fine by me if you don't want to change this. IMO, no-semis users should suffer as much as possible, because it's a bad idea. 

Maybe this is more of a lint rule thing, I guess. Thanks for responding. I'll leave it open and you can close if you wish. (Just in case some other weirdo like me using symbols runs into this)
