### ISSUE TITLE
Proposal: Add `--doctype-case` option for customizable DOCTYPE casing

### ISSUE THREAD

**Issue by ptu14** [prettier/prettier#16588]
**Prettier 3.3.3**

**Input:**

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
```

**Output:**

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Document</title>
  </head>
  <body></body>
</html>
```

**Expected output:**

### Depends on the --doctype-case option setting:
For `--doctype-case lowercase` (can be default):
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
</html>
```
For --doctype-case uppercase:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
</html>
```
For `--doctype-case preserve`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
</html>
```

**Why?**

Proposal to add a new configuration option `--doctype-case` to allow users to choose their preferred **DOCTYPE** casing style.

- Specification compliance: The **HTML5** specification allows for **DOCTYPE** to be written in both lowercase and uppercase (case-insensitive). However, the HTML specification explicitly states: "In other words, `<!DOCTYPE html>`, case-insensitively." This suggests that uppercase is the canonical form, which some developers prefer to follow strictly. https://html.spec.whatwg.org/multipage/syntax.html#the-doctype
- Special nature of DOCTYPE: It's important to note that the **DOCTYPE i**s not an HTML tag, but rather a required **preamble**. Its unique status as a declaration rather than a tag makes it a special case in HTML documents, which some argue warrants special consideration in formatting.
- Flexibility: Different developers and teams have different preferences regarding code style. Adding this option will allow for customization of formatting to individual or team coding standards.
- Backward compatibility: The preserve option will allow maintaining existing style in projects that don't want to introduce changes in DOCTYPE casing.
- Resolving controversy: There are differing opinions in the community about the preferred **DOCTYPE** casing. Adding this option will allow reconciling different preferences without imposing a single style on all users.
- Consistency with other tools: Some tools or environments may prefer a specific **DOCTYPE** casing style. This option will facilitate Prettier's integration with such tools. e.g. the Angular team is facing problems because of this change https://github.com/angular/angular/pull/51052#issuecomment-1974933556

The proposed implementation does not violate **Prettier's** opinionated principle as it concerns a purely stylistic aspect that does not affect the functionality or semantics of HTML code.

**Comment by mateusz-daniluk-xtb** [comment]
https://github.com/prettier/prettier/issues/15096

this topic is coming back, but I think such a change is needed

**Comment by sosukesuzuki** [comment]
Thank you for writing a detailed proposal. I understand the motivation behind it. However, I do not agree with this suggestion. I believe that Prettier should avoid adding more options unless absolutely necessary.

If formatting the DOCTYPE declaration in all uppercase causes an actual problem (e.g., rendering issues in certain browsers), then we can consider it. However, if it’s just a matter of user preference, I don't think we should add such an option.

As the Angular team has done, just run Prettier with the `--write` option.

**Comment by ptu14** [comment]
@sosukesuzuki thank you for answer.
Could you please provide a specific reference or link to where the Angular team used the `--write` option to address this `DOCTYPE` casing issue? I'd like to see the exact context where this approach was implemented or discussed.

**Comment by wenfangdu** [comment]
TBH, `<!doctype html>` looks very weird 🤔.

**Comment by joshuatshaffer** [comment]
There are use cases where an HTML can also be parsed by XML tools and a lowercase DOCTYPE is invalid in XML.

Also, uppercase DOCTYPE, although not required in HTML, has been the convention for decades. It was not broken; Why did Prettier "fix" it? (and break some rare use cases in the process)

**Comment by g-plane** [comment]
In [dprint](https://dprint.dev/) with [markup_fmt](https://github.com/g-plane/markup_fmt) plugin, it has an option call [`doctypeKeywordCase`](https://markup-fmt.netlify.app/config/doctype-keyword-case.html) which behaves like this. We can consider dprint and give it a try if we need to customize it.

**Comment by fisker** [comment]
Let's leave `DOCTYPE` as it is?
