### ISSUE TITLE
[BUG] When format a special code will auto add "|"  

### ISSUE THREAD

**Issue by FengMingQiang** [prettier/prettier#16590]
before format
```
<script lang="ts">
type MyExclude<T, K extends keyof T> = keyof T extends K | (infer U extends keyof T) ? U : never;
</script>
```

after format
```
<script lang="ts">
type MyExclude<T, K extends keyof T> = keyof T extends
    | K
    | infer U extends keyof T
    ? U
    : never;
</script>
```

Issues：
1、Line 2 has an extra  “|” symbol, it will fail to compile
2、The parentheses of "infer U extends keyof T" are removed, it will fail to compile

**Comment by HolgerJeromin** [comment]
> 1、Line 2 has an extra “|” symbol, it will fail to compile
> 2、The parentheses of "infer U extends keyof T" are removed, it will fail to compile

compiles without problems in playground
https://www.typescriptlang.org/play/#code/C4TwDgpgBAsiCiAPAxgGwK4BMIB4AqANFANJQSLAQB2mAzlANYQgD2AZlHgHxQC8jzdpzIVqdAFBQpUAD4lJ0uQEsqbCACcoAVRGUa9Jqw54FUgPzbTUAFxQqEAG4aA3EA

**Comment by fisker** [comment]
> This is expected behavior. See [#2971 (comment)](https://github.com/prettier/prettier/issues/2971#issuecomment-333890539) for explanation.

Quoted from https://github.com/prettier/prettier/issues/16483#issuecomment-2232756267
