### ISSUE TITLE
Wrong trailing comma position after comment in scss

### ISSUE THREAD

**Issue by DzmVasileusky** [prettier/prettier#16599]
**Prettier 3.3.3**
Playground doesn't support `scss` it seems

```sh
# Options (if any):
"trailingComma": "es5"
```

**Input:**

```scss
$z-indexes: (
    header: 1035,
    overlay: 1202 // TODO: change to 1050 after bootstrap modals will be removed
);
```

**Output:**

```scss
$z-indexes: (
    header: 1035,
    overlay: 1202 // TODO: change to 1050 after bootstrap modals will be removed,
);
```

**Expected output:**

```scss
$z-indexes: (
    header: 1035,
    overlay: 1202, // TODO: change to 1050 after bootstrap modals will be removed
);
```

**Why?**

It should add a comma to the last item not to the comment. It will also add it endless times, we already have like 5 repeated commas

**Comment by fisker** [comment]
This is known issue, but I can't find the original issue.

**Comment by Ma-hawaj** [comment]
I am trying to address this issue.
I was looking at the following file:
```
src/language-css/print/comma-separated-value-group.js
```
trying to find where the comma is printed but it seems it's not in that file.
Do you have any idea where I should I look to solve the problem ?
