### ISSUE TITLE
Inconsistent behavior with ternary expressions and optional chaining

### ISSUE THREAD

**Issue by anjitcubit** [prettier/prettier#16597]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpQeRQDOM+qGgFsAhjABimbHij4AvMzkA+drPz5qcGOmqyadONXly5+AOQieYMx3V37+APz4RjgHQxqOESR4BtEWloD2oRHBIAOXQhACNDfABafABGAF13TR50En5HR1sHQoAGRPwY909vXwCgqBCwyOi4oyS0jLgsnKd8tUL7IoK+-CQyiq8ff0DcYM8GqNj41vS3TOzcnqH+0tcQqsna+vD55tK2lY617sHNgagAXwLr-AB6Z-wAFQB5ABFPke-oGZ+OgeHANCIoHQIEJ8DhZJpIYYCiQtPgoNF5PgALJiAAWblQ5Bo+AYOJg+NCkOhzHwACoUgBRADUAHYmB4IABlSpQADmzHOAAcSIE4Axnmw2G5JXQmc8cLyADT4NggVVMDgFTTaXT4AA8dBwADclMQyBB8AB3fR656Gk0cO4gRUgCCC6a8ZCgETUagQS0ABR9CB4yBAPktIgAnqGXTFQmAANZaTkiIRwAAycLgyFQEzgcYTyZgnMFgThvOQnnQBZAoKEOFz+ZdcAAHoLDDh07AfO9DFAfTgOk3fLWeBWUQBFdAQeAj0EugBWPFbnIncGns5zSGrtYAjjP4AG-YLQyhLAkoHA4AY6M6QLNwhWAMLQ0RhjoAVnv475KIAgjAlQxOgR6GFmV7zrWuIwEIJAULiODwDwZZgHAnIhkhxpIVGYZgDwsYgEaNYAJKIrAnJgF47r-pC3JRiiUEuoKfqghQoSCmGLEdIYRo5i6cKgtQMDHiIvLvkgeajsxPpCWGMBRh2VjUTA94sXCMAUDgdDksgyRFEULqaAeOCaKJ4kiExD4iDEWk6biyAAEwuiCcDvDZZ5SQuIBwAsdC3hmEK8ugYlwOIwhiLgfJhiIoEQCAdx3EAA)

```sh
--parser typescript
--print-width 100
--no-semi
--jsx-single-quote
--trailing-comma es5
```

**Input:**

```tsx
function HelloWorld() {

const formatFunction =()=>{
   return order === 'asc'
          ? a?.trials[action.trailNumber - 1]?.result ??
            0 - b?.trials[action.trailNumber - 1]?.result ??
            0
          : b?.trials[action.trailNumber - 1]?.result ??
            0 - a?.trials[action.trailNumber - 1]?.result ??
            0
}
  
     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return <div>Hello word</div>
}
```

**Output:**

```tsx
function HelloWorld() {
  const formatFunction = () => {
    return order === "asc"
      ? (a?.trials[action.trailNumber - 1]?.result ??
          0 - b?.trials[action.trailNumber - 1]?.result ??
          0)
      : (b?.trials[action.trailNumber - 1]?.result ??
          0 - a?.trials[action.trailNumber - 1]?.result ??
          0)
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "")

  return <div>Hello word</div>
}

```

**Expected output: or this is what has been on my device**

```tsx
  order === 'asc'
            ? a?.trials[action.trailNumber - 1]?.result ??
              0 - b?.trials[action.trailNumber - 1]?.result ??
              0
            : b?.trials[action.trailNumber - 1]?.result ??
              0 - a?.trials[action.trailNumber - 1]?.result ??
              0
```

Second example
**Input**
```tsx
startDate={search?.start_date ? new Date(search?.start_date) ?? null : null}
```

**Output on playground**
```tsx
startDate={search?.start_date ? new (Date(search?.start_date) ?? null) : null}
```

**This is what has been on my device**
```tsx
startDate={search?.start_date ? new Date(search?.start_date ?? null) : null}
```

**Why?**
the question is why in my VS code it's not adding braces on the format but on playground and other devices.
I'm not against adding small braces here, but I'm looking for consistency, we share the same project with vs/prettier setting and getting different output on save.

**Comment by fisker** [comment]
> Second example

Our playground shows [different output](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgAgM43QJxgBF14BeYbOAsACwH4A6XAmAfQBNS5N7Mo4Ad0wl4ACio0GzPIU7cAlLz5QArgBt1mJPw3qAvgHoAfCAA0ICAAcYAS2jZkoAvgiCACgQSOU6dYPQAT0cLACN8dDAAazgYAGV0AFs4ABlbAWQAMz8qMIjo2LirSPSAc2QYfFU4CypE2wqqmpA4AA8rOHxbZNg-ABVOqAJbOB9s9VyQbDL1OABFVQh4LJzmgCtsVriZ+cXlpHHJgEc9uHdXKx8QdGwAWgE4DkfzEEr0W3UygGEIRMT0ZDXTQvaZQUqzACCMEqtlCqng7k6aQyB1WFloMES6gA6rRbPBsMUwHA4t58bYAG74wKAsDYEIgCnVACSUCesDiYC6NghbLiMECsxWE2aVlcVGxESsgLFo06FLgL3SVEI53QpX+wsmxXwKsBoXQoTg6heYvSMGxtg4MFoyAAHAAGCz4OAnWwutUagGokUWPChS3W21IABMFlUVD6hrGaJaiSNHCeHBS6DBqnVcAAYhB8P9oWVAeh4RAQPp9EA), maybe you have conflicting ESLint rules?

**Comment by anjitcubit** [comment]
@fisker yes that's my question too, even if its an eslint why is it different from device to device,
and prettier is supposed to override the eslint rule isn't it 

`extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react-hooks/recommended',
    'plugin:prettier/recommended',
  ],`

**Comment by dcyriller** [comment]
> prettier is supposed to override the eslint rule isn't it

No, not really. Have you checked out https://prettier.io/docs/en/integrating-with-linters? It should help you resolve your issue.
