### ISSUE TITLE
markdown list keep adding space after list symbol (-) when tab-width is greater than 2

### ISSUE THREAD

**Issue by kamontat** [prettier/prettier#16628]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAMwhAOlDAIwEMAnfddDACzgBs6IQAaECABxgEtoBnZUGVIQA7gAUyCfimJ0RxAJ79WhUsTABrODADKxALZwAMlyhxkmWbzgq1m7TvbrTAc2QxSAVxshr+ru5ePnAAHuxwpFyGsLIAKhFQZFxw0pZ01qy8rnRwAIqeEPAWVj4AVrwhOtl5BUVIaRkgAI61cGLC7NIgxLyoZnAAJoMsIB7EXHSuAMIQ+vrEyN0MI1lQLjkAgjAeXISe8GIRJmbF6T7UMPp0AOrUXPC8TmBwOlL3XABu9wqLYLzKIA+3gAklAhrAdGBIpwNmCdDAFDlTo12MJrNc1OxFqiUhEPuZWKZrKQYO1iC55sifE5SMTFvNSBoBqIoCNUaYYNcuAMYNRkAAOAAMrFIcBaXFFZIpC3qJVYMGIhC5PL5SAALKxPNZYorUnKQHB9IRBkMBkZiGtPOS4AAxCCkebbVyLYj7JgAX3dQA)

```sh
--parser markdown
--tab-width 4
```

**Input:**

```markdown
- foo
- bar
  - hello
```

**Output:**

```markdown
-   foo
-   bar
    -   hello
```

**Expected output:**

```markdown
- foo
- bar
    - hello
```

**Comment by kachkaev** [comment]
👋 @kamontat! This issue is tracked in https://github.com/prettier/prettier/issues/5019. Potential fix is in https://github.com/prettier/prettier/pull/15526.
