### ISSUE TITLE
markdown didn't format html content in markdown file

### ISSUE THREAD

**Issue by kamontat** [prettier/prettier#16629]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgAgIYBsCWA5lALwA64C8AThQHxlSaaoDO62UdAEnLrhFQB6dpwZRh6cSAA0ICOhj5orZKGzVqEAO4AFDQlUo827AE9VcgEbVsYANZwYAZWwBbOABl8UOMgBmeKxw1rYOTs4cYD6EyDDUAK4hIMFu+HGJyXAAHuhw1PgesHgAKvlQGvhwRoG4wXKsMbhwAIoJEPABQckAVqzZzk2t7Z1ItfUgAI4jcLpa6EYg2KwAtL5wACabsiDx2PgEUIQAwhBubtjIS-w7jUfNAIIw8fhWCfC6+d6+XXXJABYwNy4ADq-3w8FEYDgzkMEPwADcIWYrmBWJYQAikgBJKBbWDOMAFRQPPHOGBmZq-CboLTBEG2dBXWnVfIIvxyHzBagwObYQgXanJDjUblXC7UewbHRQHa0nwwEH4DYwf7IAAcAAY5NQ4NN8Lq+QLLmNunIYNgrEqVWqkAAWOQJYIlS01M0gOBuKybLYbTycQgJflwABiEGoF2eMSu2HeEBAAF8E0A)

```sh
--parser markdown
--tab-width 4
```

**Input:**

```markdown
<p align="center">
  <span>Hello</span>
</p>
```

**Output:**

```markdown
<p align="center">
  <span>Hello</span>
</p>
```

**Expected output:**

```markdown
<p align="center">
    <span>Hello</span>
</p>
```

**Comment by kachkaev** [comment]
👋 @kamontat! HTML syntax (or JSX, to be precise) works in mdx files, but not md files. Here is an example:

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgAgIYBsCWA5lALwA64C8AThQHxlSaaoDO62UdAEnLrhFQB6dpwZRh6cSAA0ICOhj5orZKGzVqEAO4AFDQlUo827AE9VcgEbVsYANZwYAZWwBbOABl8UOMgBmeKxw1rYOTs4cYD6EyDDUAK4hIMFu+HGJyXAAHuhw1PgesHgAKvlQGvhwRoG4wXKsMbhwAIoJEPABQckAVqzZzk2t7Z1ItfUgAI4jcLpa6EYg2KwAtL5wACabsiDx2PgEUIQAwhBubtjIS-w7jUfNAIIw8fhWCfC6+d6+XXXJABYwNy4ADq-3w8FEYDgzkMEPwADcIWYrmBWJYQAikgBJKBbWDOMAFRQPPHOGBmZq-CboLTBEG2dBXWnVfIIvxyHzBagwObYQgXanJDjUblXNwbbI7Wk+GAg-AbGD-ZAADgADHJqHBpvgtXyBZcxt05DBsFZ5YrlUgACxyBLBEpmmrGkBwNxWTZbDaeTiEBL8uAAMQg1AuzxiV2w7wgIAAvrGgA)

```sh
--parser mdx
--tab-width 4
```

**Input:**

```mdx
<p align="center">
  <span>Hello</span>
</p>

```

**Output:**

```mdx
<p align="center">
    <span>Hello</span>
</p>

```
