### ISSUE TITLE
Please consider allowing two blank lines

### ISSUE THREAD

**Issue by elesq** [prettier/prettier#16631]
Well worn road, but at almost 2025 I'd like to ask once more, acknowledging "it's an opinionated formatter" that it's opinion should be flexible here and at least a .prettierrc override that could blanket apply. Having read all previous conversations related to the main threads on this it feels like it's no more than "because we want to"

Sure to be shot down but here goes... can we have a configurable 2-blank-line rule, please?

**Comment by kachkaev** [comment]
👋 @elesq! Please refer to https://prettier.io/docs/en/rationale.html#empty-lines and #12053 for context.

**Comment by elesq** [comment]
I’ve seen the rationale link before. I think this is a decision to not do rather than a decision that can’t do. Such an odd hill to die on “add loads of comments to achieve what you want” - the antithesis of code cleaning and formatting. 

I shall seek an alternative
