### ISSUE TITLE
The default values of prettier plugin and prettier.js are inconsistent

### ISSUE THREAD

**Issue by Katarina-W** [prettier/prettier#16635]
![image](https://github.com/user-attachments/assets/a8a5c28d-9832-4322-bcf5-6771f6940cd9)
![image](https://github.com/user-attachments/assets/3a0f5e4d-c48f-4b2c-b288-f5555808be77)

**Comment by dcyriller** [comment]
As per the trailing comma documentation ([link](https://prettier.io/docs/en/options#trailing-commas)):
> Default value changed from `es5` to `all` in v3.0.0

Which version of the plugin are you using?

**Comment by Katarina-W** [comment]
> 根据尾随逗号文档（[链接](https://prettier.io/docs/en/options#trailing-commas)）：
> 
> > 在 v3.0.0 中默认值从 更改`es5`为`all`
> 
> 您使用的是哪个版本的插件？

插件版本为:    v11.0.0
npm包版本为: ^3.3.3

![image](https://github.com/user-attachments/assets/dc3cf606-c887-47a2-bfc6-c008f23a8e0b)
![image](https://github.com/user-attachments/assets/c77a7946-5cee-4fa6-a9c7-53d175509d5b)

**Comment by kachkaev** [comment]
This issue is related to https://github.com/prettier/prettier-vscode and is out of scope of this repo. Please create a [discussion](https://github.com/prettier/prettier-vscode/discussions) if upgrading `prettier-vscode` does not help.
