### ISSUE TITLE
HTML5 Support

### ISSUE THREAD

**Issue by Coder-Zertrax** [prettier/prettier#16636]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgJzugfAHSlQCN0BnOAo4zK1SAGzrgFti4ATOgC1sNQCWLAOZ0BUAA4BXGHQbiA1nRZwYefhKzoWdMhCmYwlfjEzowS-gHcauEABoQECTAHQyyUFkwQrABSwEDxR0Bit0AE8PRxpzBVUAZW04ABlxOGQAM1CKGLMLRM0wcWFkUyk4RwoWATLMCsc4AA8JOEwhBDUGABU2qCwBOGDshlyQMhKGOABFKQh4LJzKkAArMiaEyZm5haQRsYBHHbg-HwlgkHIAWig4Tk4HEFN0AXkoYQBhCBYWdGRLhgMR4Td5TACCMFMAmIMhObTStzqDRA3BgLAYAHVuAJ4GQinAEkEcQIAG44iL-ATCKAQbCPEkVACSUA4nQSYHaLjBLISMAiU0Wo2WEh8FAxZgk-xFQzaJIyjnEFEwMFO6GEv0FY00mCV-3Q7ykDCwjxF4hgGIEHBg3GQAEYAAz2xzYI4CbCq9V-PZLRxqYgWq02pAAJkcUgo3XQxGGPpArHYHFZHBS+uEUjVcAAYrTfpCSnqZBAQABfYtAA)

```sh
--parser angular
--print-width 100
--html-whitespace-sensitivity ignore
--single-attribute-per-line
```

**Input:**

```html
<area>
<base>
<br>
<col>
<embed>
<hr>
<img>
<input>
<link>
<meta>
<param>
<source>
<track>
<wbr>

```

**Output:**

```html
<area />
<base />
<br />
<col />
<embed />
<hr />
<img />
<input />
<link />
<meta />
<param />
<source />
<track />
<wbr />
```

**Expected output:**

```html
<area>
<base>
<br>
<col>
<embed>
<hr>
<img>
<input>
<link>
<meta>
<param>
<source>
<track>
<wbr>
```

When will prettier support full html5-formatting? The parser option with "html" and "angular" ist per definition wrong. This should be renamed to "xhtml", "xml" or "svg".
Selfclosing tags are defined only for foreign elements like SVG or for XHTML and XML (and custom angular elements). And Normal elements should have an end tag per definition. So there is no self-closing defined in th html itself people ...

HTML5 definition of void elements: https://www.w3.org/TR/2014/REC-html5-20141028/syntax.html#void-elements
> Void elements
> area, base, br, col, embed, hr, img, input, keygen, link, meta, param, source, track, wbr
...
> Void elements can't have any contents (since there's no end tag, no content can be put between the start tag and the end tag).

**Comment by kachkaev** [comment]
:wave: @Coder-Zertrax! This issue is tracked in https://github.com/prettier/prettier/issues/5246, let’s continue the discussion there. Closing as duplicae.
