### ISSUE TITLE
es2022: lacking support for arbitrary module namespace identifier names

### ISSUE THREAD

**Issue by laino** [prettier/prettier#16657]
The following [ES2022 syntax](https://github.com/tc39/ecma262/pull/2154) is valid in Typescript with esnext/es2022, but causes a Syntax Error in prettier:

```ts
const value = 3;
export { value as 'some-identifier' };
```

Syntax error in both ``3.3.3`` and the ``4.0.0 alpha 10``.

Typescript will accept that syntax if you set ``"module": "es2022"``

**Comment by sosukesuzuki** [comment]
Thank you, we need to update our typescript.

**Comment by sosukesuzuki** [comment]
We need to wait https://github.com/typescript-eslint/typescript-eslint/issues/9653

**Comment by fisker** [comment]
Looks like we don't need wait for `typescript-eslint`,  it already works in #16669

**Comment by fisker** [comment]
Fixed by #16669
