### ISSUE TITLE
No option to avoid line splitting for chained functions in javascript

### ISSUE THREAD

**Issue by SorinGFS** [prettier/prettier#16663]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQQEYBWcYMmAZGZgIQBuAhgDaoAm2A1nAJ4A0mA8oWIwAdB04BnXIJIBKYeIgBbONnZcZmALwA+TPSbM68NZxlmNAJzgwArhaiZ0jcXADcAHSieQ3EBAAOMKjQ4sigdBYWEADuAAoRCKEojNF0Ej4geBZ0YBwwAMp0ygAyqFBwyE4MLr5ZOXn5-jllAObIMBY2cL4uiqjtnd0gcAAe-nAWqMqwjAAqE1ARqHBJVTUg4q0McACKNhDwlc5DBOIj+Vu7+4dIa0MAjtdwsVH+SSB04gC05XDMfxkOnRUEwoC0AMJKRR0ZAfBgMDKbMHbACCMA6qDwNngsQmpXKR2qQwAFjBFAwAOrE1DwcRNMBwfKJGmoGg0ziwsDiUK+GhdACSUH+sHyYEmgRRQvyME420J638URcFOy-lhipWExoFV8ZRcFhgLzoLWh8qGTQs+thMvG4jFqECGUVZRgFJYMGJyAAbAAGXxWR6oKxGk0w27HXwwOh4N3MD3IABMvhsLlm0dWEeGijwf3+zGKdDBNmNcAAYhALND0a1YXRsRAQABfRtAA)

**Input:**

```jsx
if (object && !valid(key, Object.keys(object).some((key) => validate(key)))) return false;
```

**Output:**

```jsx
if (
  object &&
  !valid(
    key,
    Object.keys(object).some((key) => validate(key)),
  )
)
  return false;
```

**Expected output:**

```jsx
if (object && !valid(key, Object.keys(object).some((key) => validate(key)))) return false;
```

**Why?**

I think an option is needed to allow the user to choose how many chained functions above will accept line splitting.

**Comment by sosukesuzuki** [comment]
Please read https://prettier.io/docs/en/option-philosophy, we don't add a new option for this.
