### ISSUE TITLE
feature request: enclosing bracket for specific statements

### ISSUE THREAD

**Issue by nine-fox** [prettier/prettier#16661]
Hi there,

Prettier is really cool when I used to format my code. However, I didn't find the options for inserting brackets, like the following:
```
            for (i = a.size; i-- !== 0;)
                if (!b.has(keys[i])) return false;
```

I need it format automatically like this:

```
            for (i = a.size; i-- !== 0; ) { <---insert this
                if (!b.has(keys[i])) { <---insert this
                     return false;
                } <---insert this
            } <---insert this
```

Would you like to add this feature, please? 

Thanks,
nine-fox

**Comment by sosukesuzuki** [comment]
It would not add such a feature. It would change the AST. We can use https://eslint.org/docs/latest/rules/curly instead.
