### ISSUE TITLE
Prettier ignore comment for a code block without e.g. print-width

### ISSUE THREAD

**Issue by fudom** [prettier/prettier#16662]
Sometimes you have a code block which should be never break. For example a list like that:

```ts
// Print width demo: -------------------------------------|
this.doSomething(AnotherOne.BlahBlah, AnotherTwo.Blah);
this.doSomething(AnotherOne.BlahBlah1, AnotherTwo.Blah1);
this.doSomething(AnotherOne.BlahBlah10, AnotherTwo.Blah10);
this.doSomething(AnotherOne.BlahBlah2, AnotherTwo.Blah2);
```

after format:

```ts
// Print width demo: -----------------------------------|
this.doSomething(AnotherOne.BlahBlah, AnotherTwo.Blah);
this.doSomething(AnotherOne.BlahBlah1, AnotherTwo.Blah1);
this.doSomething(
  AnotherOne.BlahBlah10, 
  AnotherTwo.Blah10
  );
this.doSomething(AnotherOne.BlahBlah2, AnotherTwo.Blah2);
```

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOgCYQDKEAtnOhlAOYAUAglBOnAE4DyUcOAQgDYCGaPoIA0AAgZM0rACoB3CDwFoAlAG4AOrEy4CxMhWr1GzdpyWDhaAIzjJp+YqvX1WirqKlymI-elmuK2cABjsTf0cLG2DXbWx8TwMfWj9WDkDlKwAmMKlZBSis9RAREAgABxgMaCxkUH4WFgg5AAUGhFqUfl45fgBPWtKAIxZ+MABrckJ+MgAZSjhkADNurDhh0Ymp8rHKKmQYFgBXdZA1kgwD49O4AA9y1gwyWG6ZVigGjDhOld410qwe14cAAikcmIskL9-iAAFZYW6EIGg8HwZarU4AR1RcBaTXKnRA-CwAFpOHA8BSSqhRhheHsAMKkEj8ZBE3i8amA6jAugwQ4YIZHeAtVjzTjov6nNAwEi8ADqmHgWB2YDghA6GCqADctX02WAsIMQNqTgBJKCU2CEMAsDCVBh4QgwPrAyUw8pNNby0blNme76sbWLUqUNYsGB4-hUFnu047FjhtlDfhDOCc0qeygweUYPDoZAAVgAHKUWHBsRhy1GY6yoRjSjBU7n82hkDkQEc1jJUz8GyA4CQ03hKXhZvxqEdo3AAGIQFgs-l7Nn8YUQEAAXw3QA)

I chose a print width of 58 just for demo purposes. The point is that sometimes you just go a little too far behind the print-width and end up with ugly, hard to read code.

I could override the complete file in the config file. But I don't want this for the whole file. Only for a code block. And I want all other prettier stuff in this ignored section. Only one option should be ignored.

The solution could be:

```ts
// prettier-ignore-start print-width
this.doSomething(AnotherOne.BlahBlah, AnotherTwo.Blah);
this.doSomething(AnotherOne.BlahBlah1, AnotherTwo.Blah1);
this.doSomething(AnotherOne.BlahBlah10, AnotherTwo.Blah10);
this.doSomething(AnotherOne.BlahBlah2, AnotherTwo.Blah2);
// prettier-ignore-end
```

This ignores the print-width. Another solution could be `... print-width=240` to override.

**Comment by sosukesuzuki** [comment]
Duplicates https://github.com/prettier/prettier/issues/5287
