### ISSUE TITLE
🐞 - Don't break line before punctuation

### ISSUE THREAD

**Issue by nsbarsukov** [prettier/prettier#16686]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjATtA5gPgB0oACMkgVXTmPJNQENa7yALLOAMwF5CRWYMAA7okAejEcGYGADoAJnABukrnA5QwcVdJgBaeRAC2YyEaHQEMdKeNHoAYg6c9YBgBt3AI2kBrPswsJBzuvCBQEM7qHFgBpEEkMAxYuHAwYQD6Xu4MUP4ggSwwAK4AlgAypXmFRPFBzgAFbp4+YP519GIM+ACExKhimDhQBCAANCAQQjCl0OjIoMk4AO4ACskI8ygeywwAnvMTXlh+aQDKDEZwlVBwyJwe1EcnbedC0lW4yNjFcBPURlK3ywvwmcAAHkJ1KUrrAPAAVdRQZKlOBbB7uJ4gdCfdxwACKxQg8Hujz+IAAVuhwWdcQSiSSkBisQBHBlwVY4ETIEAMdB6W5wRTycYgbAMUruT4AYTsDB5HncopxIzxAEFBFhSl5ivBVuobncmWSJgIjO4AOqsUrwdDvLRnTY20pKG17HlgdCHEBKX4ASSgilgZzAWumasDZxgezxpMx5KEOGoFpOQh5ibR6iUdwmVWoWBgnIYuCM8uN8Ym7yw+Z5Pi8cCVla1sAtpXkMFYyAAHAAGCYcNmlDhFktl5nkpJeVvtztIABME2K1HhDC86JNIDgRnr8mF5VyuGKxbgADFIqXBJ8FbqICAAL53oA)

```sh
--parser babel
```

**Input:**

```jsx
<strong>
    Use
    <a
        href="https://react.dev/reference/react-dom/components/common#ref-callback"
        rel="noreferrer"
        target="_blank"
        tuiLink
    >
        ref callback
    </a>!
</strong>
```

**Output:**

```jsx
<strong>
  Use
  <a
    href="https://react.dev/reference/react-dom/components/common#ref-callback"
    rel="noreferrer"
    target="_blank"
    tuiLink
  >
    ref callback
  </a>
  !
</strong>;

```

**Expected output:**

```html
<strong>
    Use
    <a
        href="https://react.dev/reference/react-dom/components/common#ref-callback"
        rel="noreferrer"
        target="_blank"
        tuiLink
    >
        ref callback
    </a>!
</strong>
```

**Why?**
Redundant white space before punctuation sign
![image](https://github.com/user-attachments/assets/d56649b4-cf94-4e53-89c2-0ac34e202e76)

**Comment by kachkaev** [comment]
👋 @nsbarsukov! Your playground example uses `babel` parser, so the snippet is treated as JSX. JSX ignores newlines, so the ouput is expected. If you want to format HTML, not JSX, please use `html` parser (it is usually picked automatically based on file name):

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjATtA5gPgB0oACMkgVXTmPJNQENa7yALLOAMwF5CRWYMAA7okAejEcGYGADoAJnABukrnA5QwcVdJgBaeRAC2YyEaHQEMdKeNHoAYg6c9YBgBt3AI2kBrPswsJBzuvCBQEM7qHFgBpEEkMAxYuHAwYQD6Xu4MUP4ggSwwAK4AlgAypXmFRPFBzgAFbp4+YP519GIM+ACExKhimDhQBCAANCAQQjCl0OjIoMk4AO4ACskI8ygeywwAnvMTXlh+aQDKDEZwlVBwyJwe1EcnbedC0lW4yNjFcBPURlK3ywvwmcAAHkJ1KUrrAPAAVdRQZKlOBbB7uJ4gdCfdxwACKxQg8Hujz+IAAVuhwWdcQSiSSkBisQBHBlwVY4ETIEAMdB6W5wRTycYgbAMUruT4AYTsDB5HncopxIzxAEFBFhSl5ivBVuobncmWSJgIjO4AOqsUrwdDvLRnTY20pKG17HlgdCHEBKX4ASSgilgZzAWumasDZxgezxpMx5KEOGoFpOQh5ibR6iUdwmVWoWBgnIYuCM8uN8Ym7yw+Z5ZqVla1sAtpXkMFYyAAHAAGCYcNmlDhFktl5nkpJeZut9tIABME2K1HhDC86JNIDgRi8QuF5VyuGKxbgADFIqXBJ8FbqICAAL43oA)

```sh
--parser html
```

**Input:**

```html
<strong>
    Use
    <a
        href="https://react.dev/reference/react-dom/components/common#ref-callback"
        rel="noreferrer"
        target="_blank"
        tuiLink
    >
        ref callback
    </a>!
</strong>
```

**Output:**

```html
<strong>
  Use
  <a
    href="https://react.dev/reference/react-dom/components/common#ref-callback"
    rel="noreferrer"
    target="_blank"
    tuiLink
  >
    ref callback </a
  >!
</strong>

```
