### ISSUE TITLE
Please remove unused pendants.

### ISSUE THREAD

**Issue by YunheeKim2513** [prettier/prettier#16693]
Please remove unused pendants.
<img width="1112" alt="스크린샷 2024-09-27 오후 5 41 30" src="https://github.com/user-attachments/assets/ea3fa78e-7fcb-4409-9513-c17888b41456">

**Comment by fisker** [comment]
Stable version of Prettier has [zero dependencies](https://www.npmjs.com/package/prettier?activeTab=dependencies).

But 4.0.0-alpha.10 includes [@prettier/cli](https://www.npmjs.com/package/prettier/v/4.0.0-alpha.10?activeTab=dependencies), maybe installed from there?

**Comment by YunheeKim2513** [comment]
I downloaded Stable version with caret and I think the higher version has been downloaded. Thanks for the confirmation. I'll try the fixed version
