### ISSUE TITLE
Code-breaking semicolon added when range formatting across multiple arrow functions

### ISSUE THREAD

**Issue by yume-chan** [prettier/prettier#16721]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAFAHSgAjz9AShwF4A+HYHbfHAXwBob8jSLhm9HtCBubEAxAQADjACW0AM7JQAQwBOCiAHcACooQyUcgDYq5ATxlCARgrlgA1nBgBlOQFs4AGXFQ4yVHqlwzF61s7EUt3AHNkGAUAVz8QX0dxSJi4uAAPETgFcWdYPQAVLKhFcThtb11fISlw3TgARWiIeC8fOIArKTS7WoamlqQKqpAAR364NWURbRA5KQBaDzgAExXBECi5cV1wgGEIR0c5ZFndXXWaqDC6gEEYKPFTaPg1LLcPVsq4gAsYR10AOrfcTwKQhMBwOxaEHiABuIMMJzAUhMIFhsQAklBVrA7GBsmIbti7DBDHVPsMRMpfACLCITlSyllYZ4hO5fAoYJM5GEjhS4iEFByTqY5KY4OchFT3DAAeJljBvsgABwABiECjgY3Emu5vOOgzaQhgYrlCqVSAATEJor58mLykaQHBHOLlqtli45Fdojy4AAxCAKI73cInOTPCDrCxXSEmznIACMADYNd6wnAAKLY5AAZgALHQ6EA)

```sh
--range-start 16
--range-end 34
```

**Input:**

```jsx
f(
    () => { 
    },
    () => {
    },
);

```

**Output:**

```jsx
f(
    () => {}, () => {};,
);
```

**Expected output:**

```jsx
f(
    () => {}, () => {},
);
```

**Why?**

Coming from VSCode Prettier extension. The extra semicolon added causes a syntax error.

**Comment by kachkaev** [comment]
Thanks for sharing this example @yume-chan! Let’s track this issue as part of https://github.com/prettier/prettier/issues/12540.

**Comment by fisker** [comment]
Reopen this, since the original issue in #12540 was fixed, but not this case.
