### ISSUE TITLE
Prettier in inline scripts in HTML?

### ISSUE THREAD

**Issue by normmcgarry** [prettier/prettier#1674]
I didn't see this issue logged anywhere, so apologies if it is! I understand why this is happening based on how prettier works, but the formatting doesn't seem ideal, in my opinion.

In my use case, I'm using Polymer, but the issue is also relevant in using prettier in javascript anywhere in HTML.

Actual:

```html
<dom-module id="test-element">
  <template>
  </template>
  <script>
  class TestElement extends Polymer.Element {
  static get is() {
    return 'test-element';
  }
}
</script>
</dom-module>
```

Expected:

```html
<dom-module id="test-element">
  <template>
  </template>
  <script>
    class TestElement extends Polymer.Element {
      static get is() {
        return 'test-element';
      }
    }
  </script>
</dom-module>
```

**Comment by josephfrazier** [comment]
I initially thought that `prettier --range-start 71 --range-end 167` (see https://github.com/prettier/prettier/pull/1609) would correctly format the "Actual" code into the "Expected" code, but the changes in https://github.com/prettier/prettier/pull/1659 require the entire file to be parsed before the range is formatted ([here](https://github.com/prettier/prettier/blob/0adeadb16ea5e70e18902bc700d0cce3260f962d/index.js#L55-L57))

**Comment by vjeux** [comment]
This is something that would be awesome for vue files as well.

**Comment by muhajirframe** [comment]
+1

**Comment by vjeux** [comment]
We're working on it. Going to close it in favor of https://github.com/prettier/prettier/issues/2097

**Comment by jaichandra** [comment]
I don't intend to open an issue but have a query. How is the prettier plugin for vscode able to format html files with inline javascript. I am also talking about the same Polymer files here. But, when I run the prettier cli `prettier --single-quote --trailing-comma none --write \"src/**/*.html\"`, I get errors in console.

**Comment by lydell** [comment]
@jaichandra The VSCode plugin must be cutting out the JS inside `<script>` tags, format that with Prettier, and then paste back the result.

**Comment by web-padawan** [comment]
Created #3767 as it was suggested to file separate issue apart from the Vue support.
