### ISSUE TITLE
Flow Type Comments

### ISSUE THREAD

**Issue by k7n4n5t3w4rt** [prettier/prettier#16746]
In the past, Prettier was stripping out Flow comments. Now it seems to be doing it again... unless I'm losing it. The Playground link @hawkrives shared back in 2018, which used to preserve the Flow comments, now seems to strip them out.

QUOTE:

@k7n4n5t3w4rt Ah, you're using the Flow parser. 

If you don't _need_ to use it, you can use the (default) Babylon parser, which also supports Flow types, and doesn't have this bug: [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwDYQDuAOlKagFRJKkwCeADnBgCpwDOMGAvBsKcRgMAThCbD6ARiQZOwgJZQA5gBpSGDRhFi4EugCYZUAK4BbAEa7SAX1IVUAqCBUgxMedHbJQAQ2GjCAAU-BC8UHwA3CHkAE2cQc2EfMABrOBgAZQZkxSVkGGFjOBdFdl0YQKSlUx9kHB88MpcAK3YADwAhJNT0jJ9TOAAZRTg6hqaQbOEy4WQEn3M6AicXEUUYAHVYmAALZAAOAAZV0TKNpIY5kQ5dCNGXYTgAR2N5R8qfatqkesbikDKpnk+UK-3YuTwcAAisYIPAxn8XDAFlsYrtkPokUl5HhcgBhCCmGpzKDQe4gYxlFgLMK-MrWaxAA)

_Originally posted by @hawkrives in https://github.com/prettier/prettier/issues/719#issuecomment-390406762_

**Comment by fisker** [comment]
https://prettier.io/blog/2023/07/05/3.0.0#remove-support-for-flow-comments-13687httpsgithubcomprettierprettierpull13687-13703httpsgithubcomprettierprettierpull13703-by-thorn0httpsgithubcomthorn0
