### ISSUE TITLE
printWidth behavior suddenly changed

### ISSUE THREAD

**Issue by UP-MDK** [prettier/prettier#16783]
Hello,

recently i noticed, that the **default behavior** of auto-formatting has changed. I even tested on the [prettier playground](https://prettier.io/playground) and the same changes that are effecting my code base are also happening on the official site.

At the moment, the **printWidth** option is **ignored in some cases**, but not in others. I don't understand, why one would change the default behavior in such a significant way, as it is completely restructuring all previously saved files in my code base in a (for my liking) messy way.

I have the following config in prettier.config.mjs:

`const config = {
    semi: false,
    tabWidth: 4,
    endOfLine: 'lf',
    printWidth: 130,
    singleQuote: true,
    trailingComma: 'es5',
}`

Previously lines like this one `<div className="aux-logo"><ContentfulImage image={content.logo.fields} /></div>` were maintained.
Now it is getting wrapped, regardless of the **printWidth** option. This excessive wrapping is unnecessarily creating far too many line breaks, resulting in only a few chars per line, lots of scrolling and generally making it very difficult to oversee even small components.

I would appreciate, if someone would explain, why this was made and what the thinking behind this change was.

Thank you!

**Comment by seiyab** [comment]
Hello.

When the sudden change happens to you? Trying locally, even Prettier 2.7.1 (eeed611), that is more than 2 years old one, wraps `const x = <div><img /><div>` into 
```jsx
const x = (
  <div>
    <img />
  </div>
);
```
. Generally say, Prettier inserts line break regardless of printWidth for readability with heuristic rule.
