### ISSUE TITLE
Bug multiple Angular @ control flow elements will be placed in one line

### ISSUE THREAD

**Issue by muuvmuuv** [prettier/prettier#16786]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgMwAQApMBO6CAJgM64CUA3NgIZnaHFTmXbDYA6U22qmCATxhsEHM1JlaMAnTABrbGAB08mOgBu6GAE8V6EtloAbODGzpsAXmwASdKzgAPbO2A8+fADx0ADn4AtGB0BCSB6lo6uoEArmRwBJ5efADakdp6ALrWXOBqYBqZunnJKakkdPA5eaqV8KW8Kdipen5wNfltcI3NLfGJnaoDSSBlXqmOJC6d6L1eAPQAfMkAvvxwALZ+ehzJ3iRayiYMZLkgUBCBkqyMl4EJZoV5K00+-kHokLxQdJtw5zIdBIeWwy32C0OmlefFWPHWqD8JzAcAAFhATNNhB4mgctEsVNhCSpvJD8fCQAAaEAQHboaBkZCgUIECAAdwACqEEIyUHQTGy6LpGdSAEZyRTmADKfzgABlHHBkJh+QkxRKFNK-PJHABzZCyWJwakJTboA0EI3UlztIj-WD8gAqiV+RDgvJVJjVIDIerMAEVYhB4MrVcaQAArMjOKV+uCB4NKpCe70ARyD8A5rL8vJADECUDgcGmJCpIFkdHQJj1AGEIJtNnRkHmTCYy76oLqzABBGCydCi2KZxIKwuhr3h1EwTYmADqqJ07u1KKlPJ0UT0zbAZBFIE0RoAkk5YFKwEQdt3WFK9GZx96-KyErO5H5mw-3YlNErqY4EgQYFmdC6o2d7htqBB-s2U4zmWD6ODAs6GDAqLIAAHAADNSBBwOm6DYYBwFNsmYbUjAdCiohJDIcgABM1IDI65EeiRIBbKKxYlnKdCdrEQFwAAYkIjZ9nqzZ0EOEAgKsqxAA)

**Input:**

```html
@if (friends(); as friends) { 
  @for (c of friends; track c.activity.id ; let i = $index ) {
    <app-card-activity-user
      [activity]="c.activity"
      [date]="c.date"
      [type]="c.type"
      [user]="c.user"
      [index]="i"
    />
  } @empty {
  <div class="no-friends no-select">
    <app-icon name="sad" />
  </div>
  }
} @placeholder {
  <div>. . .</div>
}
```

**Output:**

```html
@if (friends(); as friends) { @for (c of friends; track c.activity.id ; let i =
$index ) {
<app-card-activity-user
  [activity]="c.activity"
  [date]="c.date"
  [type]="c.type"
  [user]="c.user"
  [index]="i"
/>
} @empty {
<div class="no-friends no-select">
  <app-icon name="sad" />
</div>
} } @placeholder {
<div>. . .</div>
}

```

**Expected output:**

```html
@if (friends(); as friends) { 
  @for (c of friends; track c.activity.id; let i = $index) {
    <app-card-activity-user
      [activity]="c.activity"
      [date]="c.date"
      [type]="c.type"
      [user]="c.user"
      [index]="i"
    />
  } @empty {
    <div class="no-friends no-select">
      <app-icon name="sad" />
    </div>
  }
} @placeholder {
  <div>. . .</div>
}
```

> Note: I think it should also remove these empty lines before `;` and at the end in `)`.

**Why?**

Indention and line breaks are really off since new control-flow parsing. I just waited a bit to post this since I guessed the parsing/regexing must be hard af but just that it gets recognition. 
Also indention and `$index` is on next line which is weird but one already reported that here #15698.

**Comment by sosukesuzuki** [comment]
If you specify `--parser=angular`, it will work as expected

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgMwAQApMBO6CAJgM64CUA3NgIZnaHFTmXbDYA6U22qmCATxhsEHM1JlaMAnTABrbGAB08mOgBu6GAE8V6EtloAbODGzpsAXmwASdKzgAPbO2A8+fADx0ADn4AtGB0BCSB6lo6uoEArmRwBJ5efADakdp6ALrWXOBqYBqZunnJKakkdPA5eaqV8KW8Kdipen5wNfltcI3NLfGJnaoDSSBlXqmOJC6d6L1eAPQAfMkAvvxwALZ+ehzJ3iRayiYMZLkgUBCBkqyMl4EJZoV5K00+-kHokLxQdJtw5zIdBIeWwy32C0OmlefFWPHWqD8JzAcAAFhATNNhB4mgctEsVNhCSpvJD8fCQAAaEAQHboaBkZCgUIECAAdwACqEEIyUHQTGy6LpGdSAEZyRTmADKfzgABlHHBkJh+QkxRKFNK-PJHABzZCyWJwakJTboA0EI3UlztIj-WD8gAqiV+RDgvJVJjVIDIerMAEVYhB4MrVcaQAArMjOKV+uCB4NKpCe70ARyD8A5rL8vJADECUDgcGmJCpIFkdHQJj1AGEIJtNnRkHmTCYy76oLqzABBGCydCi2KZxIKwuhr3h1EwTYmADqqJ07u1KKlPJ0UT0zbAZBFIE0RoAkk5YFKwEQdt3WFK9GZx96-KyErO5H5mw-3YlNErqY4EgQYFmdC6o2d7htqBB-s2dCdrEJwEGWD6ODAs6GDAqLIAAHAADNSBBwOm6B4YBwFNsmYbUjAdCiihJBocgABM1IDI6VEeuRIBbKKxYlnK0G6rEQFwAAYkIjZ9nqUFDhAICrKsQA)

```sh
--parser angular
```

**Input:**

```html
@if (friends(); as friends) { 
  @for (c of friends; track c.activity.id ; let i = $index ) {
    <app-card-activity-user
      [activity]="c.activity"
      [date]="c.date"
      [type]="c.type"
      [user]="c.user"
      [index]="i"
    />
  } @empty {
  <div class="no-friends no-select">
    <app-icon name="sad" />
  </div>
  }
} @placeholder {
  <div>. . .</div>
}
```

**Output:**

```html
@if (friends(); as friends) {
  @for (c of friends; track c.activity.id; let i = $index) {
    <app-card-activity-user
      [activity]="c.activity"
      [date]="c.date"
      [type]="c.type"
      [user]="c.user"
      [index]="i"
    />
  } @empty {
    <div class="no-friends no-select">
      <app-icon name="sad" />
    </div>
  }
}
@placeholder {
  <div>. . .</div>
}

```

**Comment by muuvmuuv** [comment]
Oh gosh... I thought I had that set all the time, sorry
