### ISSUE TITLE
ESM Shared Configurations Incompatible with Node v23

### ISSUE THREAD

**Issue by Kenneth-Sills** [prettier/prettier#16812]
**Environments:**

- Prettier Version: 3.3.3
- Running Prettier via: CLI
- Runtime: Node v23 (23.0.0 and 23.1.0 tested)
- Operating System: Linux
- Prettier plugins (if any):
    - `@prettier/plugin-xml`
    - `prettier-plugin-packagejson`
    - `prettier-plugin-organize-imports`
    - `prettier-plugin-sh`

**Steps to reproduce:**

1. Create a basic shared config project as described in ["Sharing Configurations"](https://prettier.io/docs/en/sharing-configurations). The specific configuration or plugins don't matter, but the config object should be exposed via `export default`.
1. Create a stub project, and install your shared config proejct created above. In `package.json` add the `"prettier": "@scope/project"` configuration.
1. Run `npx node@23 node_modules/.bin/prettier --check --log-level debug .`.

**Expected behavior:** Prettier should load the shared config and print errors in project files, as it would with `npx node@22 ...`. 

**Actual behavior:** Prettier fails to load the options from the shared configuration and every file checked emits a warning:

```txt
[debug] loaded options `{"__esModule":true,"default":{"plugins":["@prettier/plugin-xml","prettier-plugin-packagejson","prettier-plugin-organize-imports","prettier-plugin-sh"],"printWidth":100,"tabWidth":4,"singleQuote":true,"proseWrap":"always","vueIndentScriptAndStyle":true,"xmlWhitespaceSensitivity":"ignore","organizeImportsSkipDestructiveCodeActions":true,"overrides":[{"files":"**/*.y?(a)ml?(.dist)","options":{"tabWidth":2}},{"files":["CHANGELOG.md","husky/_/**/*"],"options":{"requirePragma":true}}]}}`
[warn] Ignored unknown option { __esModule: true }.
[warn] Ignored unknown option { default: { plugins: ["@prettier/plugin-xml", "prettier-plugin-packagejson", "prettier-plugin-organize-imports", "prettier-plugin-sh"], printWidth: 100, tabWidth: 4, singleQuote: true, proseWrap: "always", vueIndentScriptAndStyle: true, xmlWhitespaceSensitivity: "ignore", organizeImportsSkipDestructiveCodeActions: true, overrides: [{ files: "**/*.y?(a)ml?(.dist)", options: { tabWidth: 2 } }, { files: ["CHANGELOG.md", "husky/_/**/*"], options: { requirePragma: true } }] } }.
```

**Cause:**

[Node 23 made changes to `require`](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V23.md#2024-10-16-version-2300-current-rafaelgss) and where Node 22 [required a flag to import ESM modules with `require`](https://nodejs.org/docs/latest-v22.x/api/modules.html#loading-ecmascript-modules-using-require), Node 23 [enabled this by default](https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require).

Since `ERR_REQUIRE_ESM` is no longer thrown without the `--experimental-require-module` flag, we never get down to [explicitly handling ESM modules](https://github.com/prettier/prettier/blob/3e4b452b4a1f93049e2758a83b0eddf6334f180a/src/config/prettier-config/load-external-config.js#L25). Instead, `requireFromFile` ends up returning the ESM module wrapped up as:

```js
{
  __esModule: true,
  default: { /* The actual shared config. */ }
}
```

**Solution:**

- For backwards compatibility, we should leave the existing error handling strategy in.
- For foreward compatibility, we should check if `process.features.require_module` is set to `true` inside the `try` block [here](https://github.com/prettier/prettier/blob/3e4b452b4a1f93049e2758a83b0eddf6334f180a/src/config/prettier-config/load-external-config.js#L17). If so, and `requireFromFile(...).__esModule` is `true`, return `requireFromFile(...).default` instead of the result of `requireFromFile(...)` itself.

**Workaround:**

- Don't use Node 23! :sweat_smile:
- But if you must, pass `--no-experimental-require-module`. You can also add this to your environment's `NODE_OPTIONS` for convenience.

**Comment by fisker** [comment]
Need wait for https://github.com/jestjs/jest/issues/15363
