### ISSUE TITLE
comment handling problem, it asked to report it. (feel free to ignore i am not interested)

### ISSUE THREAD

**Issue by shimondoodkin** [prettier/prettier#16826]
hema.ts 45ms
src/modules/module/module.controller.ts 47ms
src/modules/module/module.module.ts 8ms
src/modules/module/module.service.ts
[error] src/modules/module/module.service.ts: Error: Comment "already used" was not printed. Please report this error!
[error]     at Object.ensureAllCommentsPrinted (/root/com/api-server/node_modules/prettier/index.js:8290:17)
[error]     at coreFormat (/root/com/api-server/node_modules/prettier/index.js:8839:16)
[error]     at formatWithCursor2 (/root/com/api-server/node_modules/prettier/index.js:9021:18)
[error]     at Object.formatWithCursor (/root/com/api-server/node_modules/prettier/index.js:38183:12)
[error]     at format (/root/com/api-server/node_modules/prettier/cli.js:15017:24)
[error]     at formatFiles2 (/root/com/api-server/node_modules/prettier/cli.js:15131:22)
[error]     at async main (/root/com/api-server/node_modules/prettier/cli.js:15356:5)
[error]     at async Object.run (/root/com/api-server/node_modules/prettier/cli.js:15303:5)
src/modules/module/modules-get-server.service.ts 31ms
src/modules/module/dto/moduleId.dto.ts 4ms

the code:

                for (let i = 0; i < foundOrdermodule.versions.length; i++) {
                    const aVersion = foundOrdermodule.versions[i];
                    if (aVersion.status === 'error') continue;
                    if (versionsUsed.includes(i)) continue; // already used
                    else {

                        versionsUsed.push(i);
                        versionsUsedTime.push(new Date());

                        await this.ordermoduleModel.updateOne(
                            { _id: new Types.ObjectId(moduleId2) },
                            {
                                versionsUsed,
                                versionsUsedTime
                            },
                            { session }
                        );
                        return { avalibleVersion: aVersion, versionIndex: i, foundOrdermodule }
                    }
                }

**Comment by kachkaev** [comment]
👋 @shimondoodkin! Can you please share the reproduction? I’m unable to replicate the issues in the Playground:

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdHPoGYQE6oAUANnDKgJaoC8qADANyWoA8quArlACYDye3OHgC2Ebh1IA6AG5CAzhWhzJpKAHMYACyYUA1LoCUqYAB0oWC1khQ55AIYA1eYvO1OPfoJFiJcGc6UAbQoAXQYzS0jKbCJHAKhJWzsYDjkaaloAciE8fEyjaxgKKA44cPMoiwoYwlk8BSUAVTk4bklisGIOQTlCCgMC6CKSstQAejHUO2I8ODtuAE9UVNaIyqw4YhbjMzX1yzqGm2bWyQAHVM0+g3L9yMOXORPuABUKYT8LuSuoOAB3VAAEWScEIA3KezumDsfzsFHIWgoynwXlE4lIAFkxJtJBwztwQbxfoRIVCLMBUAB9CjcJCoX4Al4LM5wZS8ABGACs4GAYABJbiENG+AUAJiMAF8ADSksmYUwVOWVB5NFrcGWKpX3eJPNVvD6yrXSw1KiktORHVASk37G429azFJ4cwUuzSaYUdmkJz1Fx0uK+6BS1AqqB8nhwAAedIowfcfAEQmFpCt9os1s1kQzIClIAgZyKSmQoDseFyfwACqWEHJkCBprCFrXc+y8HYwABrMgAZTsHwAMsU4MhsNMWi2252e2d28U1MgYHhSrmWsIKAul3Bc1GWXh3ggYNMXkIoKWKKyR2OtyAFOpSABFDgQeCXrbXzlySPducPp8vpCjm+uYAI5-nAFa5GctYoHYcgALS-K0rQ5iAi5wsQc4AMIQMIwh2HW0zECht5qKQACCMCLp6HDwBWQiDr8r7jiAmgwMIxAAOqaPCrIzmAcDdjW8IUNI8ILHWYAWih0ilOGgiwN2YB7gWZE8N2MALKQTHXmcuQtBxbZnHWumskIsgocULR4DAEF2GoeHabmM71EIdbsnY7KbChunFDAHE0loyAABx0LmsygRQsy2fZ+EAVeuaHuy-ncIFSCirmKwvB50GAcxcDCJ53CCNw-Z2OoHB2XAABi+B4ZRc4ETREAgBKEpAA)

```sh
--parser babel
```

**Input:**

```jsx
            for (let i = 0; i < foundOrdermodule.versions.length; i++) {
                const aVersion = foundOrdermodule.versions[i];
                if (aVersion.status === 'error') continue;
                if (versionsUsed.includes(i)) continue; // already used
                else {

                    versionsUsed.push(i);
                    versionsUsedTime.push(new Date());

                    await this.ordermoduleModel.updateOne(
                        { _id: new Types.ObjectId(moduleId2) },
                        {
                            versionsUsed,
                            versionsUsedTime
                        },
                        { session }
                    );
                    return { avalibleVersion: aVersion, versionIndex: i, foundOrdermodule }
                }
            }

```

**Output:**

```jsx
for (let i = 0; i < foundOrdermodule.versions.length; i++) {
  const aVersion = foundOrdermodule.versions[i];
  if (aVersion.status === "error") continue;
  if (versionsUsed.includes(i))
    continue; // already used
  else {
    versionsUsed.push(i);
    versionsUsedTime.push(new Date());

    await this.ordermoduleModel.updateOne(
      { _id: new Types.ObjectId(moduleId2) },
      {
        versionsUsed,
        versionsUsedTime,
      },
      { session },
    );
    return { avalibleVersion: aVersion, versionIndex: i, foundOrdermodule };
  }
}

```

**Comment by shimondoodkin** [comment]
I will try later
