### ISSUE TITLE
Feature suggestion: reorder class methods?

### ISSUE THREAD

**Issue by breck7** [prettier/prettier#1684]
I've been loving Prettier. I no longer spend any time worrying about formatting. Thanks for making a fantastic library that is super fast and reliable.

One task I still waste time on is rearranging methods in classes. For example, should methods be:

```js
// In this order (sort by setters then getters)
class Button {
  setText(value) {
    this.value = value;
    return this;
  }
  getText() {
    return this.value;
  }
}

// Alphabetical
class Button {
  getText() {
    return this.value;
  }
  setText(value) {
    this.value = value;
    return this;
  }
}
// Or some other order?

```

I've played with sorting by public/private(using a _ prefix to denote a private method); alphabetically; setters first then getters. I haven't settled on the best system but more importantly I haven't found a library that will just pick one convention and consistently apply it on save. I think this might be a great feature addition to Prettier. For all I know it already exists (in which case I apologize for the unnecessary comment).

Thoughts?

**Comment by lydell** [comment]
In general Prettier can't reorder things. There's been requests for sorting imports, object keys and JSX attributes, but none of those can be done safely because of side effects. For class methods, though, it looks like it's safe to change the order (as long as duplicates come out in the same internal order). But since Prettier so far doesn't change the order of anything (as far as I know), it might feel unexpected if it reorders class methods. ¯\\\_(ツ)\_/¯

**Comment by k15a** [comment]
You can also only safely reorder class methods which will look odd if you also use class properties.

Other than that this is a breaking change which we probably won't include because it will reorder many files for many people.

**Comment by josephfrazier** [comment]
As @lydell explained, there's been a variety of requests for prettier to format in a way that alters the AST. For reference, here are the ones I could find:

* https://github.com/prettier/prettier/issues/323
* https://github.com/prettier/prettier/issues/766
* https://github.com/prettier/prettier/issues/767
* https://github.com/prettier/prettier/issues/949
* https://github.com/prettier/prettier/issues/1096

Even if this particular transformation could be applied in a way that can't affect program semantics, I think it's best to let a separate program take care of the AST transformation, and keep prettier itself focused on formatting.

For what's it's worth, you can use `prettier.__debug.parse` to get your AST, then use a separate program to transform the AST as you like, then use `prettier.__debug.formatAST` to pretty-print it. However, this might not work as expected, for the reasons mentioned in https://github.com/prettier/prettier/issues/1274#issuecomment-294168312

---

In some of the issues in the above list, there's talk of adding a plugin system (https://github.com/prettier/prettier/issues/949#issuecomment-285097994, https://github.com/prettier/prettier/issues/1096#issuecomment-291012181). Maybe the easiest way to do this would be to add an `astTransform` option to the API, which would be a function that takes and returns an AST? Then, prettier would apply the transform after parsing the file, so the user doesn't have to dig into `prettier.__debug`. This could also be exposed as a CLI option that takes a path to a file that exports the `astTransform` function. Of course, the user would still be responsible for avoiding any caveats mentioned in https://github.com/prettier/prettier/issues/1274#issuecomment-294168312

---

Should we also create a [`.github/ISSUE_TEMPLATE.md`](https://github.com/blog/2111-issue-and-pull-request-templates) which includes a comment saying that requests to alter the AST will be denied?

**Comment by vjeux** [comment]
> Should we also create a .github/ISSUE_TEMPLATE.md which includes a comment saying that requests to alter the AST will be denied?

I don't think so, it's useful to know what people want. That doesn't mean that we should implement it but it's good context to know what the next steps are.

**Comment by josephfrazier** [comment]
Yeah, I guess preemptively denying feature requests is a bit harsh. Maybe a `CONTRIBUTING.md` with an FAQ could encourage folks to comment on existing issues rather than creating duplicates? Though, of the issues I listed in my previous comment, it looks like only https://github.com/prettier/prettier/issues/767 and https://github.com/prettier/prettier/issues/949 are duplicates of each other.

**Comment by breck7** [comment]
Thanks all for the responses. I like the philosophy of not having prettier alter the AST. That seems like a great design decision.

So I just need to find/build a module for reordering what can be reordered (maybe it could be called Ranker/Sorter). I'll do some searching to see who has already implemented something like this. I'm also just curious in general what the best design patterns are when there is ambiguity in how to order things.

@k15a said:

> You can also only safely reorder class methods which will look odd if you also use class properties.

Does JS have class properties? I was under the impression it only had class methods (at compile time, at least).

**Comment by k15a** [comment]
It's a stage-2 proposal but as far as I know facebook and others are using it and it's pretty widely adopted. https://github.com/tc39/proposal-class-public-fields

**Comment by vjeux** [comment]
We're unlikely going to do it, so I'm going to close this issue as it is not actionable, but please keep the discussion going!

**Comment by Skaronator** [comment]
Might be cool if the React Lifecycle functions would be ordered/sorted how they are actually executed.

1. constructor()
2. componentWillMount()
3. componentDidMount()
4. componentWillReceiveProps()
5. shouldComponentUpdate()
6. componentWillUpdate()
7. componentDidUpdate()
8. componentWillUnmount()
9. componentDidCatch()
10. render()

**Comment by azz** [comment]
@Skaronator check out https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md 😄

**Comment by Skaronator** [comment]
Oh thanks! 😆
