### ISSUE TITLE
Release new version of Prettier (or clarify release process in documentation)

### ISSUE THREAD

**Issue by theoludwig** [prettier/prettier#16849]
**Environments:**

- Prettier Version: 3.3.3
- Running Prettier via: CLI 
- Runtime: Node.js v22.11.0
- Operating System: GNU/Linux
- Prettier plugins (if any): 

**Question:**

Since the last release, v3.3.3 in July 2024, there have been a number of changes that landed on `main` branch, I'm wondering when we'll be able to use all those improvements, at least in alpha channel (on npm, the last alpha release [4.0.0-alpha.10](https://www.npmjs.com/package/prettier/v/4.0.0-alpha.10), released the 2024-09-02).

Also, I haven't seen a GitHub milestone for v3.4, does it mean, there won't be any minor release for v3 release lines, and you are currently working/planning for v4?

It's quite opaque for the moment, how/when releases are done with Prettier, it could be great to clarify the process and the decisions (in the documentation or blog, for examples).

**Comment by sosukesuzuki** [comment]
とりあえず 3.4 をリリースするための issue を作成しました https://github.com/prettier/prettier/issues/16850
