### ISSUE TITLE
Prettier v3.4 adds parens around statement in v-on

### ISSUE THREAD

**Issue by ntnyq** [prettier/prettier#16885]
**Prettier 3.4.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoBGArjDNGQAJg4CWYA1gLzEhsBnAGIQIVPACcy3MgEJBIsZL6EAwuy6oA9LXrQSUbZlwE4B0iAA0ICFhhtoA5KEkSIAdwAKkhE5R4cdzwATydrKgk8LjgYAGU8DDgAGTYoOGQAMwCBOHDI6LisKNSAc2QYCRpckByMNnLK6rgADyw4CTZE2ACAFXaoSTY4PyycHOsBUpw4AEUaCHhM7OqAKwFm2KnZ+cWkUfGQAEcduE83LD8QPAEAWjS4ABNHqxAKvDZ2KBLVCAwMPGQVxwOBeky+0wAgvQOrpTu0UmklmNqgALGAYHAAdRRbHgAiKYDgsV8uLYADdccFAWABGEQGSqgBJKBPWCxMAdOwQlmxGDBaZIg5YNw5TGRLCA4XDdpk9LWVI5CQwM54Er-QXVIoSRWAhlykDC1IwTFsB4wFHIAAcAAZrBI4Mc2PaVWqAXtltYYHgqCazRakAAmaw0HI9b0jD0gOAYKiPJ4PJJ4L40VVwEQSf70UqAvB0CAgAC+BaAA)

```sh
--parser vue
```

**Input:**

```vue
<template>
  <button @click="isFoobar = !isFoobar">Click</button>
</template>


```

**Output:**

```vue
<template>
  <button @click="(isFoobar = !isFoobar)">Click</button>
</template>

```

**Expected output:**

```vue
<template>
  <button @click="isFoobar = !isFoobar">Click</button>
</template>
```

**Why?**

There is no need to add parens around the statement. 

So we should left it as it is.

v3.4 docs doesn't mention this change.

**Comment by fisker** [comment]
Releasing new version

**Comment by jesspinklet** [comment]
At least give us an option for that inside config file, sometimes parentheses are needed when assigning a type inside v-on. It can break the IDE (vs-code) syntax highlighting

**Comment by fisker** [comment]
Example?

**Comment by jesspinklet** [comment]
![{1A125CDF-DA40-4809-B675-DF9CD67B9200}](https://github.com/user-attachments/assets/93721bc2-cbd6-4097-b2af-c3e5205e1ed1)
![{81EA800D-4196-4EA6-A92C-B21A65B30919}](https://github.com/user-attachments/assets/a392edbe-cf8a-489e-9765-15a94c46b676)

**Comment by jesspinklet** [comment]
Any update in this matter?
