### ISSUE TITLE
Output changing between 2 options (regression?)

### ISSUE THREAD

**Issue by tiagoskaneta** [prettier/prettier#16897]
**Prettier 3.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT77VwzrWcGHLlwA8dHADcAfMJFiJMufK6oIEZStEAjavgD0sziq7aAhtWAByfFYC+m+aIDOABzOcwJM8+cA5MwBbOABeNjRoGABaZzhAnG0IenCjE3k1CHM9DKz8HIs89VyARgAmAGYAFgBWRxFRfTcPaQAaQsyC-OyiizqGxVT6-QG5Jg4HKA4MLFwCYjJKGnpmVjkePgF8IWMFKUGnEZ2VDLqxXQN9lSzrWwm0-Bd3T29fAOCwiNgYuISkuhSuu1coDAWUqtUGk0oJd5G0QT1uh1qH1hntNP00cYxlAJiAWiAIK5ZlBnMhQBZqBAAO4ABQsCFJKDMJCpZgAnqT8bozGAANa8ADKQTgABkcFA4MhUMzYlzqDz+TABe4wOKAObIGDUdBwfGxeJSmW6kBwAAerjg1BwwVgzIAKpaoBYcHBGdKSLKQM51SQ4ABFdAQeCa7XGgBWzlNAp9-sDwaQ7s9AEc43AaZTXIzwNBvc54Ih8VqzDgSOqAMIQQKBMzIEDMkh4r0xgCCMC1CXQ8BplrFEpDOvxAAsYIESBRBzh4E0wHABQzJ1JJ2za2BfI3JDqAJJQOgIJVgK1E5s7gUwNm+w0e42uSmxCjy1y1m+uy2SSX48WxagwdNmNXVy9PXcagv1rcxtFIRsb3FGAKBwOgYEHZAAA4AAZ8R4FMcB4X9-xrBMjULMxtDghCkKQUp8XQWI7WIt1CJNQIILoXc6BFDw1XQP84AAMRoas23VWszE7CAQDsOwgA)

```sh
# Options (if any):
--print-width 80
--tab-width 2
```

**Input:**

```jsx
function HelloWorld() {
  return (
    <div>
      <div>
        foo
        <br />
        bar{' '}
        <span className="font-semibold">
          foobar foobar foobar foobar 12345
        </span>, foobar foobar foobar
      </div>
    </div>
  )
}

function HelloWorld() {
  return (
    <div>
      <div>
        foo
        <br />
        bar{' '}
        <span className="font-semibold">foobar foobar foobar foobar 12345</span>
        , foobar foobar foobar
      </div>
    </div>
  )
}

```

**Output:**

```jsx
function HelloWorld() {
  return (
    <div>
      <div>
        foo
        <br />
        bar{" "}
        <span className="font-semibold">foobar foobar foobar foobar 12345</span>
        , foobar foobar foobar
      </div>
    </div>
  );
}

function HelloWorld() {
  return (
    <div>
      <div>
        foo
        <br />
        bar{" "}
        <span className="font-semibold">
          foobar foobar foobar foobar 12345
        </span>, foobar foobar foobar
      </div>
    </div>
  );
}

```

**Expected output:**
Either one but consistently the same

**Why?**
The same code keeps alternating between 2 possible outputs on every execution. Both outputs are reported as invalid tho, leading to the format checking never passing. It looks like a regression on 3.4, given that the same code format was stable previously.

**Comment by fisker** [comment]
@seiyab Maybe you know what causes the result?

**Comment by seiyab** [comment]
c921abee76929109d40e9b21fcd5c0480db1929c caused it. I'll investigate.

**Comment by seiyab** [comment]
slightly simpler reproducing input:

**Prettier 3.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UABCUQGYQSEmoDOADgIZS4UQBGjATuZZz2368O3YUMGiJAvpJnDUAegbMCxUgBoijdmGpFFWPIQDchQhhyqSbPXSYs91mdJEvxzsbNee3XzsNsle1xNbV0oA0tTKBB1EAh6GExoWmRQbi4IAHcABW4EVJRGABssxgBPVLj2LkYwAGs4GABlRgBbOAAZTCg4ZDIS2jhq2oam5qYwHoBzZBguAFdhkCG2zDnF5bgAD3o4LkwO2BKAFX2obkw4QoHiobjaGeK4AEUFiHh+weWAK1pt5pPV7vT5IW73EAARxBcBymXohRAjFoAFpenB0BjYiB5oxMMUZgBhCBtNqMZBI4rFbGPKDTZ4AQRg80w7AW8By+26vS+d2WAAsYG1igB1fmYeDKMBwZoFCU4CXlClgWhVEDYJYASSgmNgzTAB0SDJ1zRg5WevIh9EyQxFtXoFOt1322D6cR6Qy4MDhjGmZMtyyYXE9FM47Dg1Li1p6MBFmHQMH5yAAHAAGOJcODQzCZn1+8lg75xGDaOMJpNIABMcQWQxO2huRZAcDa4fQmPQnWY0wWvrgADEIFwycyZhTGOyICAAL7ToA)

```sh
--parser babel
```

**Input:**

```jsx
<div>
    foo
  <span>foobar foobar foobar foobar foobar foobar foobar foobar fooba foo</span>
    , abc
  </div>
;

<div>
  foo
  <span>
    foobar foobar foobar foobar foobar foobar foobar foobar fooba foo
  </span>, abc
</div>;

```

**Output:**

```jsx
<div>
  foo
  <span>
    foobar foobar foobar foobar foobar foobar foobar foobar fooba foo
  </span>, abc
</div>;

<div>
  foo
  <span>foobar foobar foobar foobar foobar foobar foobar foobar fooba foo</span>
  , abc
</div>;

```
