### ISSUE TITLE
Comment position changing in destructured array

### ISSUE THREAD

**Issue by aryzing** [prettier/prettier#16902]
**Prettier 3.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtTB6AKkwDMBLAJw0wLwBpM05IoATAXUwF4SIIAKAJQBuELRAQADjFLpkoAIblyEAO4AFRQjTIQ8gDYr5AT21iARuXlgA1nBgBleQFs4AGVJQ4yYvsbnLNnb2ElYeAObIMOQArnBijE6kkTFxIHAAHhJw5KQusPoAKtlQiqRw2kg+en4gaOF6cACK0RDw3r6pAFZo6fb1TS1tlR1iAI6DcGrKEhW6aAC0nnAsy6IgUfKkeuEAwhBOTvI6+nprdVBhDQCCMFGkZtHwatnunu3VqQAWME56AOqfUjwNAhMBwexaIGkABuQKMOjAaFMIGhsQAkqwEA4wDkpFdWPYYEYGu8ahJlIw-pYJDpyeVstCvGIPIxyDApvIwodSakQpRsjozPIzHBTmJyR4YH9SCwYJ9kAAOAAMYnIcHGFEmli5R2GHzEMGF0tl8qQACYxNFGAVhRUqjU4E4RSwVixXPILtFOXAAGIQciHW7hY6PCAgAC+4aAA)

```sh
--parser babel
```

**Input:**

```jsx
const [ /* first */, second] = foo();
```

**Output:**

```jsx
const [, /* first */ second] = foo();

```

**Expected output:**

```jsx
const [ /* first */, second] = foo();
```

**Why?**

The comment's position with respect to the `,` is changed, loosing its meaning

**Comment by kachkaev** [comment]
👋 @aryzing! I believe that this issue is the same as https://github.com/prettier/prettier/issues/1013, let’s track it there.
