### ISSUE TITLE
[Markdown] multiline blockquote breaks after format

### ISSUE THREAD

**Issue by ntnyq** [prettier/prettier#16906]
**Prettier 3.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA+ABAbQIQEkCyACgPIBKAKgIIBy5AugDpQaaEBOcMMAlnG3QAoAFlwAOAZyQB6KaI5debAHTcIUgJTpu49JAgAbJUxAAaEBFE9o45KACGbNhADuhBwhso7+53YCeNmYARmx2YADWnADKdgC2cAAy3FBwyABm3uJwwaER0aJhyQDmyDBsAK7ZIFmx3KUVVXAAHqJ83PGw3uR8UA68nhn6WWbixfpwAIrlEPDpmVUAVuJNUWOT07NIg8MgAI4bcOwWniB24gC0KXAAJjemIGV23PrFAMIQsbF2yKf6+vejKBFcaULhsbhBcrwQh8JIpOZDKoiWL6ADqQm48HEBTAcCiHkx3AAbpi-D8wOJAiAiZVcFBbrAomBwZZKPSojA-OMETs5BAsqjQqIfnI4Fk2ETUmZkuKYOw7EUvjyqgU2OKfl82OFri4oPc5MkYKjuNcYEJkAAOAAMZg4+24HHliu+W3mZhgdiCxtN5qQACYzOUsuRPQM3SA4LEgjdbtcEnYgeUFXAAGIQNhfBRAn52KEQEAAXwLQA)

```sh
--parser markdown
```

**Input:**

```markdown
> [!IMPORTANT]
> [Prettier](https://prettier.io/) is cool.

```

> [!IMPORTANT]
> [Prettier](https://prettier.io/) is cool.

**Output:**

```markdown
> [!IMPORTANT] > [Prettier](https://prettier.io/) is cool.

```

> [!IMPORTANT] > [Prettier](https://prettier.io/) is cool.

**Expected output:**

```markdown
> [!IMPORTANT]
> [Prettier](https://prettier.io/) is cool.

```

**Why?**

It's valid syntax should be left as it is .

**Comment by tats-u** [comment]
https://github.com/prettier/prettier/issues/15479

**Comment by ntnyq** [comment]
Closed as duplicated with https://github.com/prettier/prettier/issues/15479.
