### ISSUE TITLE
folder with spaces cant commit

### ISSUE THREAD

**Issue by VictorRandom** [prettier/prettier#16916]
"prettier": "3.2.5"

When I try to commit using Prettier, it doesn't recognize the entire file because the folder has a space in its name, and it breaks the flow to commit, causing Prettier to fail.

It's a business notebook that I'm using, so I can't rename the folder to my name, and since there is a space in the folder's name, it breaks.

C:/Users/Name Surname/Documents/

It only recognizes up to 'C:/Users/Name'.

It only worked when I moved the folder to C:

```
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 4 files
    ❯ **/*.?(c|m)[tj]s?(x) — 1 file
      ✖ tscw --noEmit src/vite-env.d.ts [FAILED]
      ◼ eslint --fix --max-warnings 0
      ◼ vitest related --run
      ◼ prettier --write
    ↓ **/*.{css,scss} — no files
    ❯ **/*.{md,mdx,html,json,yml} — 3 files
      ✖ prettier --write [FAILED]
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

`✖ tscw --noEmit src/vite-env.d.ts:
'C:\Users\Name' is not recognized as an internal or external command,
operable program or batch file.

✖ prettier --write:
[error] Explicitly specified file was ignored due to negative glob patterns: "C:/Users/Name Surname/Documents/...".        
[error] Explicitly specified file was ignored due to negative glob patterns: "C:/Users/Name Surname/Documents...".        
package.json 85ms (unchanged)`
```

**Comment by fisker** [comment]
Looking at the error message, it seems your file is ignored?

> [error] Explicitly specified file was ignored due to negative glob patterns: "C:/Users/Name Surname/Documents/...".
