### ISSUE TITLE
Three backticks changed to four, leading to broken code block

### ISSUE THREAD

**Issue by Tobbe** [prettier/prettier#16952]
**Prettier 3.4.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAKgQwEYGcAEA5gE4QCuADgJIAmAvADogBWuAtDLkwHwNQY4q8ALb4AbpgA2ZOIxZcQ+STjiS5AKUwSAymGIBLCjB598+PgAMrrAB584NihGIx8kKLlfY4AM2dwARRliAE98OnwACmB8CkxCOHwAXwBKcO58YFNY+MSIuIT8AH4c4lw4KlhIgrgAGnwARgAGNKRGvmziOBgyYigchL4kyysO-gB6LGwhOGFefimZ0QlpWSZOJiUVNSZ0EIo4XQMjEygRi047KAcnFzdoT3xvPy6guFDwqJia5LS6DKy-QGeWBxVK5UqMGquXqzVa7SBnW6vX6NSG5zGqEmghE8yxU1w8xAtRAECM+geyFAmGIpAA7gAFGkIXDIEBSOmYEKsknYYiYMAAa262kwwjgABl9NdkD4pOVefyhSK4mBpYRkDBiDISeVhPpNdq6iAbu99OLYFJ0O8oDT9HBWUg5ZIFSBcOrJIEyBB4LL5cbbNoPV6fXA-S7jQBHb3wBmkCiO9nsa5wGip4kgLWYfSSdUAYQgwmEmDZUkkGfdUEInoAgjAtfpsGRY+8pTKnf6SQALGDCSQAdS7+nguFVhxZw-0YmHITZYFwPJAYhklTTsCOhhgNagNG0MBCnvDroopHK-f5FDZJ4d7zEYZJ0vKLjj8WLR+NcTK7zZxeIgpoEB0lAGYntKMD9voNAwF2yAABxNCSXTRvoXQvoQb4dhGJIwDgEFQTBSAAEwkmQ5QEu+JKzN4NBpjQEqYFWZC5AAYs4xb1uqpbNhAIBJEkQA)

```sh
--parser markdown
```

**Input:**

````markdown
<Tabs groupId="js-ts">
<TabItem value="js" label="JavaScript">
  
```jsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1

  return page
}
```

</TabItem>
<TabItem value="ts" label="TypeScript">

```tsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1
  
  return page
}
```

</TabItem>
</Tabs>

````

**Output:**

`````markdown
<Tabs groupId="js-ts">
<TabItem value="js" label="JavaScript">
  
```jsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1

return page
}

````

</TabItem>
<TabItem value="ts" label="TypeScript">

```tsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1

  return page
}
````

</TabItem>
</Tabs>

`````

**Expected output:**

````markdown
<Tabs groupId="js-ts">
<TabItem value="js" label="JavaScript">
  
```jsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1

  return page
}
```

</TabItem>
<TabItem value="ts" label="TypeScript">

```tsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1
  
  return page
}
```

</TabItem>
</Tabs>

````

**Why?**

Prettier shouldn't break the codeblocks by changing the closing triple-backticks to quadruple backtics

**Comment by fisker** [comment]
Looks like a parser issue, it's not parsed as code block.

**Comment by kachkaev** [comment]
Yes, correct. It's an issue with MDX1 which Prettier still uses. It does not understand empty lines inside code blocks. If I remove a line before `return`, code is parsed as expected. Closing as part of #12209 

**Prettier 3.4.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAKgQwEYGcAEA5gE4QCuADgJIAmAvADogBWuAtDLkwHwNQY4q8ALb4AbpgA2ZOIxZcQ+STjiS5AKUwSAymGIBLCjB598+PgAMrrAB584NihGIx8kKLlfY4AM2dwARRliAE98OnwACmB8CkxCOHwAXwBKcO58YFNY+MSIuIT8AH4c4lw4KlhIgrgAGnwARgAGNKRG7OI4GDJiKByEviTLKz4+VAB6LGwhOGFefimZ0QlpWSZOJiUVNSZ0EIo4XQMjEyhhi047KAcnFzdoT3xvP06guFDwqJia5LS6DKyfX6eWBxVK5UqMGquXqzVa7SBHS6PT6NUG51G-EmghE8wmU1w8xAtRAECM+geyFAmGIpAA7gAFGkIXDIEBSOmYEKsknYYiYMAAay62kwwjgABl9NdkD4pOVefyhSK4mBpYRkDBiDISeVhPpNdq6iAbu99OLYFJ0O8oDT9HBWUg5ZIFSBcOrJIEyBB4LL5cbbNoPV6fXA-S7jQBHb3wBmkCiO9nsa5wGip4kgLWYfSSdUAYQgwmEmDZUkkGfdUEInoAgjAtfpsGRY+8pTKnf6SQALGDCSQAdS7+nguFVhxZw-0YmHITZYFwPJAYhklTTsCOhhgNagNG0MBCnvDroopHK-f5FDZJ4d7zEYZJ0vKLjj8WLR+NcTK7zZxeIgpoEB0lAGYntKMD9voNAwF2yAABxNCSnTRvonQvoQb4dhGJIwDgEFQTBSAAEwkmQ5QEu+JKzN4NBpjQEqYFWZC5AAYs4xb1uqpbNhAIBJEkQA)

```sh
--parser markdown
```

**Input:**

````markdown
<Tabs groupId="js-ts">
<TabItem value="js" label="JavaScript">
  
```jsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1
  return page
}
```

</TabItem>
<TabItem value="ts" label="TypeScript">

```tsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1
  
  return page
}
```

</TabItem>
</Tabs>

````

**Output:**

````markdown
<Tabs groupId="js-ts">
<TabItem value="js" label="JavaScript">
  
```jsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1
  return page
}
```

</TabItem>
<TabItem value="ts" label="TypeScript">

```tsx
export const beforeQuery = ({ page }) => {
  page = page ? parseInt(page, 10) : 1;

  return page;
};
```

</TabItem>
</Tabs>

````
