### ISSUE TITLE
[TypeError: Cannot read property 'length' of undefined] for typescript

### ISSUE THREAD

**Issue by cyberhck** [prettier/prettier#1700]
running `./node_modules/.bin/prettier --write --parser typescript "generated-sdk.ts"` throws error
is there something I'm missing here?

**Comment by vjeux** [comment]
Can you try on master?

**Comment by vjeux** [comment]
I'm going to close this since it's not actionable. Please let us know if running it on master is failing. TypeScript support is not yet ready in the published version.

**Comment by cyberhck** [comment]
@vjeux I'll try on master when I'll work on the project which is using this. any estimated time when will you guys release next version (the one with typescript support) ?

**Comment by vjeux** [comment]
I don't want to give estimates because it means that I'll slip but next week is likely. We'll see how fast we can work through all the issues here: https://github.com/prettier/prettier/issues/1722

**Comment by cyberhck** [comment]
I tried out on master, since packages are marked as dev dependencies, I can't run using `require` statements, why are the real dependencies marked as dev dependencies?
