### ISSUE TITLE
Meteor Blaze support

### ISSUE THREAD

**Issue by Kolyasya** [prettier/prettier#1704]
Hello, thank you for a great tool, we use it much in our projects.
The problem is on older Meteor projects, which are written with [Blaze Spacebars](http://blazejs.org/guide/spacebars.html) prettier doesn't work nice :)

Do you have any plans on support Blaze?

![prettier-meteor](https://cloud.githubusercontent.com/assets/3371143/26406856/3d31d4aa-40a2-11e7-8f29-6dfdbcd13927.gif)

**Comment by vjeux** [comment]
FYI, what you are seeing is not prettier. Prettier doesn't know how to format html right now, only JavaScript and JSX, but this code is not valid JSX.

The next steps right now is to support CSS.

I think that we're going to support HTML and potentially handlebar/blaze in the future but this is not a priority right now.

**Comment by Kolyasya** [comment]
@vjeux I'm sorry. I missed that VS Code setting `formatOnSave` is for `editor` and not for `prettier` :-)

**Comment by vjeux** [comment]
I'm going to close this as we're not going to implement it anytime soon, but if we get to html printing, I'll make sure to remember this use case ;)
