### ISSUE TITLE
How to run prettier Automatically when I save file.

### ISSUE THREAD

**Issue by nsisodiya** [prettier/prettier#1705]
I write code on editor and when I save the file, prettier should run automatically on it.
Instead of having a pre-commit hook, I will like to see prettier on auto save.
It will be great if we have add proper instruction on ReadMe for this.

**Comment by lydell** [comment]
Doesn't [this section in the readme](https://github.com/prettier/prettier#editor-integration) cut it?

**Comment by nsisodiya** [comment]
No

**Comment by lydell** [comment]
Do you mind explaining what's missing? Even better – make a pull request with your suggested edits! Sometimes people who already know something have problems explaining things. Perhaps you can do a better job :)

**Comment by nsisodiya** [comment]
Sure I will add section for how to use it with `npm-watch` package.
 npm-watch gives flexibility to watch files using pattern and execute
particular npm script on such changes. In this case prettier. However this
approach is not highly recommended because editor face problem in
synchronisation. You save file in editor and some external script again
modify and save it again. I am using Webstorm and it do not reflect changes
immediately. I have to focus outside of current tab and then inside the cut
tab.

**Comment by lydell** [comment]
I searched the Internet for "webstorm prettier support" and found this: https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/. It has a section called "Prettier" – is that what you're looking for?

**Comment by darahak** [comment]
There's a tutorial for WebStorm in this repo, even with a section on file watcher: https://github.com/prettier/prettier/blob/master/editors/jetbrains/README.md

**Comment by lydell** [comment]
@darahak Nice! Perhaps we should just mention the word "webstorm" in the readme, then? I'm not sure what the correct way to do it would be, though. Replace the word "JetBrains" with "JetBrains/WebStorm"?

**Comment by darahak** [comment]
@lydell I am editing the `README.md` to reflect that.
I just replaced "JetBrains" with "WebStorm" though.

Is there really a JetBrains editor?
As far as I know, JetBrains is just the company.

**Comment by nsisodiya** [comment]
Let me try to explain. Those blog try to add a button or menu item entry in
editor. In this case it is Webstorm. So if anybody want to prettier a file
he has to click the menu item. This is almost equal to run from command
line. What I wrote is different. I wrote about running prettier whenever
somebody save changes in a file.
Editor do not support that much.

**Comment by lydell** [comment]
@nsisodiya The document that @darahak linked to contains more information: https://github.com/prettier/prettier/blob/master/editors/jetbrains/README.md. It says both how to set up keyboard shortcuts and run-on-save/watcher.

**Comment by nsisodiya** [comment]
There's a tutorial for WebStorm in this repo, even with a section on file
watcher: https://github.com/prettier/prettier/blob/master/editors/
jetbrains/README.md


I didn't knew about this README. Yes it has section for file watcher and
auto run on save. This will fix my problem.

**Comment by nsisodiya** [comment]
It will be great if Main README has direct link to above README file. Current it has link to that blog which do not mention file watcher thing. Your README is well documented, all you need to put it's link. I went to main README and clickes that blog entry. Instead make your README as first link.

**Comment by lydell** [comment]
@nsisodiya Look again ;) The link is already there.

**Comment by nsisodiya** [comment]
Yes now it is perfect

**Comment by dmwyatt** [comment]
Probably should not have changed the text from JetBrains to Webstorm.  Most of JetBrains IDE's (for example PyCharm) are supersets of Webstorm and/or have intermingling feature sets with the other IDE's.  Because of this it's pretty common for users of JetBrains products to search for "JetBrains" instead of "Webstorm" or "PyCharm".

**Comment by k15a** [comment]
Maybe change it to "JetBrains Webstorm".

**Comment by atodd-geoplan** [comment]
And now after all these arguments, the link https://github.com/prettier/prettier/blob/master/editors/jetbrains/README.md is now 404.

The spangled webnet is so giggles.

**Comment by Geoff-Ford** [comment]
Where is this now?
