### ISSUE TITLE
Comments between switch case do not properly preserve empty lines

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1708]
```js
switch(x) {
  case x: {
  }

  // other

  case y: {
  }
}
```

outputs

```js
switch (x) {
  case x: {
  }
  // other


  case y: {
  }
}
```

instead of staying as is

https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch(x)%20%7B%5Cn%20%20case%20x%3A%20%7B%5Cn%20%20%7D%5Cn%5Cn%20%20%2F%2F%20other%5Cn%5Cn%20%20case%20y%3A%20%7B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by lydell** [comment]
Probably related:

```js
switch (true) {
  case true:
    
  // Good luck getting here
  case false:
}
```
```js
switch (true) {
  case true:
  // Good luck getting here
  case false:
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(true)%20%7B%5Cn%20%20case%20true%3A%5Cn%20%20%20%20%5Cn%20%20%2F%2F%20Good%20luck%20getting%20here%5Cn%20%20case%20false%3A%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
