### ISSUE TITLE
Handle `| null` case better

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1727]
Looking at https://github.com/artsy/emission/pull/567/files, because TypeScript doesn't have `?` operator, it is way more common to have `| null` and the leading version looks really weird.

```js
interface RelayProps {
  articles: Array<{
    __id: string,
  } | null> | null,
}
```

outputs

```js
interface RelayProps {
  articles:
    | Array<
      | {
        __id: string,
      }
      | null
    >
    | null
}
```

**Comment by azz** [comment]
TypeScript does have the `?` operator but it allows the property to be absent or explicitly `undefined`.

**Comment by vjeux** [comment]
What is the syntax for `?`, I couldn't make it work.

**Comment by kjbekkelund** [comment]
See "Optional properties" here: https://www.typescriptlang.org/docs/handbook/interfaces.html#optional-properties
