### ISSUE TITLE
Trailing character for interface

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1728]
It seems like all those are valid in TypeScript:

```js
// Comma
interface Styles {
  container: ViewStyle,
  section: ViewStyle,
}

// Semicolon
interface Styles {
  container: ViewStyle;
  section: ViewStyle;
}

// Nothing
interface Styles {
  container: ViewStyle
  section: ViewStyle
}
```

We should figure out which is best to output. Right now it outputs the last version which feels weird.

**Comment by vjeux** [comment]
More context: https://github.com/artsy/emission/pull/567#discussion_r118515881

**Comment by azz** [comment]
I think I opted for number two with `semi: true`, and number three with `semi: false`.

**Comment by alloy** [comment]
After a while [we settled on number three](https://github.com/artsy/reaction-force/pull/133/files#r114416340) (with `semi: false`) because with modifiers such as `readonly` etc it definitely no longer looks like a more typical Object declaration.

**Comment by JamesHenry** [comment]
FYI, I asked the TypeScript team for an opinion on this a while ago: https://github.com/Microsoft/TypeScript/issues/10730

It is not explicitly in the TypeScript spec, but personal opinions were for `,` or `;` to be used (1 or 2 here).

I personally tend to write them with no separators (3)

```¯\_(ツ)_/¯```

**Comment by azz** [comment]
I think the current behaviour provides a good balance of flexibility while re-using the existing `semi` option.

In my (completely arbitrary) opinion it doesn't really make sense to use `,` to separate interface fields.

**Comment by alexburner** [comment]
I agree with @azz, using (2) or (3) helps prevent interfaces from looking like object literals.

On a similar note, I don't think TS shouldn't be adding spaces in their types...
```
interface Styles {
  container:ViewStyle;
  section:ViewStyle;
}

const thing:Thing = { ... }

(arg1:string, arg2:number):boolean => { ... }
```
(like how ActionScript has been doing for years: https://en.wikipedia.org/wiki/ActionScript#Using_data_types)

But it seems the community is already well on their way with that one

**Comment by azz** [comment]
@alexburner 

I find the example on wikipedia super dense.

```as
var myArray:Array = [5,"Hello!",{a:5, b:7}];
```
vs
```ts
var myArray: Array = [5, "Hello!", { a: 5, b: 7 }];
```

**Comment by vjeux** [comment]
Going to close this as I got an answer.

**Comment by alexburner** [comment]
@azz I agree with you there, I only advocate for unspaced types. I'd write that example as:
```javascript
var myArray:Array = [5, "Hello!", { a: 5, b: 7 }];
```
I feel unspaced types can help with ambiguities such as:
```javascript
const thing = { a: 'one', b: 'two' };
type Thing = { a:string; b:string; };
```
And can also help maintain gestalt grouping of variables:
```javascript
// original
function myFunc(thing1, thing2) {
   ...
}

// tight types
function myFunc(thing1:string, thing2:number):boolean {
   ...
}

// loose types
function myFunc(thing1: string, thing2: number): boolean {
   ...
}
```

But I apologize, this is completely off topic for this issue, I'll get off my little soapbox.
