### ISSUE TITLE
ternary indentation

### ISSUE THREAD

**Issue by jasonkuhrt** [prettier/prettier#1762]
```js
  const preferredZones =
    settings.preferredZones
      ? fitsOfBestClass(zoneFits)
        .filter(x =>
          settings.preferredZones.indexOf(x.side) > -1
        )
      : []
```
formatted as:
```js
  const preferredZones = settings.preferredZones
    ? fitsOfBestClass(zoneFits).filter(
        x => settings.preferredZones.indexOf(x.side) > -1
      )
    : []
```

I think the former is more readable. At least part of the heuristic is if a ternary assignment cannot fully fit into a single line then indent all three parts, that is: `<1> ? <2> : <3>`.

**Comment by vjeux** [comment]
Hey, sorry for the lack of response! This is indeed something that we could do. I need to think more about it.

**Comment by vjeux** [comment]
It's now what prettier does
