### ISSUE TITLE
Formatted code exceeds line limit sometimes

### ISSUE THREAD

**Issue by jmzhang** [prettier/prettier#1767]
This seems to be a bug, I'm using Atom 1.17.2 and prettier-atom 0.31.1, the following code does not get prettier when eslint integration is turned on... 

```js
import { SOME_ACTION } from '../actions';

export default function (action$, store) {
  return action$.ofType(SOME_ACTION).distinctUntilKeyChanged('stamp').switchMap(({ stamp }) => {
    // some code
  });
}
```

If I make the prettier run last, the code now get formatted like this:
```js
import { SOME_ACTION } from '../actions';

export default function(action$, store) {
  return action$
    .ofType(SOME_ACTION)
    .distinctUntilKeyChanged('stamp')
    .switchMap(({ stamp }) => {
      // some code
    });
}
```
However, the `space-before-function-paren` rule is not being followed.

**Comment by k15a** [comment]
That's probably a problem with ESLint or your ESLint configuration. Do you have [`dot-location`](http://eslint.org/docs/rules/dot-location) set to `object`?

**Comment by jmzhang** [comment]
I just tried to override that rule but prettier still can't break that long line. However, if I insert just five more characters anywhere into that line, things start to work again. This is weird.

```
  return action$.ofType(SOME_ACTION).distinctUntilKeyChangedXXXXX('stamp').switchMap(({ stamp }) => {
```

Not sure if this is a prettier bug or some prettier-eslint interop issues.

**Comment by k15a** [comment]
I think you should open an issue at prettier-eslint because they probably can help you more.
