### ISSUE TITLE
Unstable yield re-print with TypeScript parser

### ISSUE THREAD

**Issue by azz** [prettier/prettier#1769]
Test file:
```
../TypeScript/tests/cases/conformance/emitter/es5/asyncGenerators/emitter.asyncGenerators.classMethods.es5.ts
```

Debug output:

```patch
: prettier(input) !== prettier(prettier(input))
Index: 
===================================================================
--- 	
+++ 	
@@ -20,5 +20,5 @@
 class C4 {
   async f() {
-    const x = yield* [1];
+    const x = yield * [1];
   }
 }
@@ -26,7 +26,9 @@
 class C5 {
   async f() {
-    const x = yield* (async function*() {
-      yield 1;
-    })();
+    const x =
+      yield *
+      (async function*() {
+        yield 1;
+      })();
   }
 }
```

**Comment by azz** [comment]
The input actually seems invalid.

```ts
class C4 {
    async * f() {
        const x = yield* [1];
    }
}
```

`generator` is false in the AST, but the method contains `YeildExpression`.

On the first print, the `*` is removed, causing the second print to treat the `yield*` as multiplication.

Might be a stretch to call this a parser bug. Should we just ignore it, @vjeux?

**Comment by azz** [comment]
Just reading up on the async iteration stage 3 proposal, and according to the [spec text](
https://tc39.github.io/proposal-async-iteration/#prod-AsyncGeneratorMethod) it is valid syntax.

Since the TypeScript parser parses it ok, and it's a stage 3 proposal, I'll raise a bug on the parser.

**Comment by vjeux** [comment]
Note that babylon and flow parse and print it just fine.

```js
(683) >> ./bin/prettier.js test.js
class C4 {
  async *f() {
    const x = yield* [1];
  }
}
[/Users/vjeux/random/prettier]                                                                                                                                      [vjeux@MacBook-Pro-98]
(684) >> ./bin/prettier.js test.js --parser typescript
class C4 {
  async f() {
    const x = yield* [1];
  }
}
```

**Comment by azz** [comment]
Endless syntax!

Should add Scheme support, just because it would take maybe half an hour... http://www.scheme.com/tspl2d/grammar.html

**Comment by vjeux** [comment]
Are you sure it would? I'm pretty sure that people have come up with various ways of indenting and breaking different kinds of statements over the years.

But yeah, I'd love to see prettier as a tool to format all sorts of programming languages and dsl. Its infrastructure is really good!

**Comment by vjeux** [comment]
I want to make sure that each language we add is really high quality.

**Comment by azz** [comment]
Of course. Scheme would be a completely odd pick anyway since prettier only does web languages at the moment.

Elm, on the other hand...

Has there been much discussion on exposing the doc-builder and doc-printer as an API with which people can implement any language?

**Comment by vjeux** [comment]
I haven't seen anyone discuss it. If you are interested in building this, I'd love to support it and stamp diffs that would make it standalone :) It's already pretty separated anyway.

**Comment by vjeux** [comment]
By the way, I think that we shouldn't just expose the low-level apis but also the logic to place comments and the cli to go through files. Those are very useful building blocks too.

**Comment by vjeux** [comment]
If you're interested in building an elm formatter, that would be really awesome!

**Comment by azz** [comment]
Looks like there's already an AST-based Elm formatter:
https://github.com/avh4/elm-format

**Comment by vjeux** [comment]
Interesting, it's written in haskell and not elm

**Comment by vjeux** [comment]
Great discussion: https://github.com/avh4/elm-format/issues/324

**Comment by azz** [comment]
Rather than further derail this issue, I left a comment here https://github.com/prettier/prettier/pull/1710#issuecomment-304489056
