### ISSUE TITLE
prettier-ignore adding extra comma

### ISSUE THREAD

**Issue by cliedeman** [prettier/prettier#1796]
[Test Case](https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Props%20%3D%20%7B%5Cn%20%20%2F%2F%20prettier-ignore%5Cn%20%20prop1%3A%20int%2C%20%5Cn%20%20prop2%3A%20int%5Cn%7D%5Cn%5Cntype%20Props%20%3D%20%7B%5Cn%20%20prop1%3A%20int%2C%20%2F%2F%20prettier-ignore%5Cn%20%20prop2%3A%20int%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

```
type Props = {
  // prettier-ignore
  prop1: int, 
  prop2: int
}

type Props = {
  prop1: int, // prettier-ignore
  prop2: int
}
```

becomes

```
type Props = {
  // prettier-ignore
  prop1: int,,
  prop2: int
};

type Props = {
  prop1: int,, // prettier-ignore
  prop2: int
};
```
As to why I am ignoring a flow type I found a bug in my IDE that fails to parse on single argument function types with no parenthesis. E.g.` int => void`

**Comment by vjeux** [comment]
Hey, sorry about it! It is now fixed on master (I'm going to do a release this week). In the meantime you can put `// prettier-ignore` on the entire type definition or use the flow parser which doesn't have this bug.

**Comment by cliedeman** [comment]
Thanks, should I be using the flow parser? I originally had it but from the docs:

> Parser - Specify which parser to use. Both parsers support the same set of JavaScript features (including Flow). You shouldn't have to change this setting.

**Comment by vjeux** [comment]
The reason we have it is for those times where there's a bug in one and we need to use the other which doesn't have it. Good news is that in the next release, there are no known issues with any of the two.
