### ISSUE TITLE
Add prettierjs emacs code to melpa

### ISSUE THREAD

**Issue by joeheyming** [prettier/prettier#180]
I generally install my emacs packages using package-list-packages

It would be nice to be able to install prettierjs.el using that instead of physically downloading the .el file

**Comment by DamienCassou** [comment]
I can do it if an author is ok with that.

**Comment by rcoedo** [comment]
I really find prettier useful, but this issue is keeping me from using it.

I can also help with this if you need it! 😃

**Comment by felipernb** [comment]
If it's just a matter of getting permission to do so, who's the person to give such authorization? @jlongster?

**Comment by troglotit** [comment]
My elisp in spacemacs is `                                      (prettier-js :location (recipe :fetcher url :url "https://gist.githubusercontent.com/troglotit/48da99263b0f4f1f24edf8e0db797027/raw/92a367cdd9f547634c050907cd9c1a5485cc0048/prettier-js.el"))
`
Beware, it doesn't check for specific modes, you have to add hooks in your emacs config 
```
  ;; prettier hook
  (add-hook 'js2-mode-hook
            #'(lambda ()
                (add-hook 'before-save-hook 'prettier-before-save nil t)))
```

I was going to publish using name something like prettiel.el - to make it clear that it's just a fork. But I'm kinda busy and lazy. From point of view of permission - you surely can ask for one, but ultimately don't need one. Right now it seems that maintainers are extremely busy with other stuff, and I'm almost certain they'd be happy if someone'd step in and provide a package.

**Comment by pcardune** [comment]
While this PR doesn't address this specific issue, it may be of interest to people following along here: #1496 "Make prettier into a global minor mode that can be toggled on and off"

**Comment by wyuenho** [comment]
I wrote a 1-liner to get this into Melpa

https://github.com/melpa/melpa/pull/4765

**Comment by vjeux** [comment]
It's now merged :)

**Comment by lydell** [comment]
Shouldn't we move prettier-js.el into another repo, and let some Emacs fan maintain it?

**Comment by vjeux** [comment]
That would be great indeed!

**Comment by lydell** [comment]
Would anyone in this issue like to create a repo?

**Comment by rcoedo** [comment]
prettier-emacs is now in melpa, I guess we can close this issue 😄 

https://github.com/melpa/melpa/pull/4777 🍻
