### ISSUE TITLE
Adds parentheses around short-circuited await calls, which causes bugs

### ISSUE THREAD

**Issue by tuckerconnelly** [prettier/prettier#1812]
I had something like:

```js
const whatever = yo && await somethingElse()
```

Which was converted to

```js
const whatever = yo && (await somethingElse())
```

Which called caused the function to call `somethingElse()`, which caused a bug :P

**Comment by vjeux** [comment]
I'm not on a computer but I think that it is fixed on master

**Comment by azz** [comment]
Babylon provides a syntax error (`await` is reserved). Flow prints correctly.

```js
var x = yo && await;
f();
```

**Comment by vjeux** [comment]
@azz you need to put an async function around to get the right behavior.

**Comment by vjeux** [comment]
@tuckerconnelly both 

```js
const whatever = yo && await somethingElse()
const whatever = yo && (await somethingElse())
```

parse and therefore execute the same way. So prettier is not doing anything wrong here.

Are you sure that your logic isn't incorrect?
