### ISSUE TITLE
parens in flow typelevel functions incorrectly removed

### ISSUE THREAD

**Issue by also** [prettier/prettier#1813]
Parens in a typelevel function (shown in https://flow.org/en/docs/types/utilities/#toc-objmap) are removed, which results in a syntax error `Unexpected token, expected (`

```
type ExtractType = <V>(X<V>) => V
```

becomes

```
type ExtractType = <V>X<V> => V;
```

```
SyntaxError: Unexpected token, expected ( (1:22)
> 1 | type ExtractType = <V>X<V> => V;
    |                       ^
  2 | 
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20ExtractType%20%3D%20%3CV%3E(X%3CV%3E)%20%3D%3E%20V%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Good catch!

**Comment by vjeux** [comment]
Sorry about this. In the meantime you can add `// prettier-ignore` in the line before to keep the parenthesis.
