### ISSUE TITLE
[Subjective] TypeScript property and parameter decorators become less readable

### ISSUE THREAD

**Issue by JamesHenry** [prettier/prettier#1817]
Subjective issue, but important for Angular/Aurelia/MobX(?) worlds...

This legacy AngularJS source (written in an Angular 2+ style using ng-metadata):

```ts
export class BrandEditDefaultsComponent {

	@Input('=') currentAccount: a.IAccount
	@Input('=') currentBrand: a.IBrand
	@Input('=') brandModel: any
	@Input('=') allCurrencies: a.ICurrency[]
	@Input('=') allLanguages: a.ILanguage[]
	@Input('=') allCreativeCategories: any

	data: any
	allTimezones: any
	allRevenueTypes: any

	constructor(
		@Inject('TargetingManager') private TargetingManager: any,
		@Inject('TargetingSettings') private TargetingSettings: any,
		@Inject('$scope') private $scope: any,
		@Inject('AppError') private AppError: any,
		@Inject('Alert') private Alert: any,
		@Inject('$stateParams') private $stateParams: any,
		@Inject('$state') private $state: any,
		@Inject('$timeout') private $timeout: ng.ITimeoutService,
		@Inject('$q') private $q: ng.IQService,
		@Inject(TimezoneService.$ng1InjectableName) private timezoneService: TimezoneService,
	) {
```

Gets formatted by prettier to be:

```ts
export class BrandEditDefaultsComponent {
	@Input('=')
	currentAccount: a.IAccount
	@Input('=')
	currentBrand: a.IBrand
	@Input('=')
	brandModel: any
	@Input('=')
	allCurrencies: a.ICurrency[]
	@Input('=')
	allLanguages: a.ILanguage[]
	@Input('=')
	allCreativeCategories: any

	data: any
	allTimezones: any
	allRevenueTypes: any

	constructor(
		@Inject('TargetingManager')
		private TargetingManager: any,
		@Inject('TargetingSettings')
		private TargetingSettings: any,
		@Inject('$scope')
		private $scope: any,
		@Inject('AppError')
		private AppError: any,
		@Inject('Alert')
		private Alert: any,
		@Inject('$stateParams')
		private $stateParams: any,
		@Inject('$state')
		private $state: any,
		@Inject('$timeout')
		private $timeout: ng.ITimeoutService,
		@Inject('$q')
		private $q: ng.IQService,
		@Inject(TimezoneService.$ng1InjectableName)
		private timezoneService: TimezoneService,
	) {
```

IMO this makes the code seem more verbose, and the constructor parameters in particular are less readable because you have to group multiple lines together in your mind as you read them.

IMO we should follow standard line length conventions in prettier, and only print the decorator on the line above if writing it on a single line would violate the character limit.

Let me know your thoughts @azz @despairblue @vjeux

**Comment by azz** [comment]
I don't have any strong feelings either way. I think it becomes more complex if there's more than one decorator for a given node.

E.g. I prefer
```ts
@foo()
@bar()
class Baz {}
```

To 

```ts
@foo() @bar() class Baz {}
```

Maybe this is one of those cases where we can look at the source to decide whether to inline or not?

**Comment by JamesHenry** [comment]
Hmm yeah I don't think I have ever seen _class_ decorators put on the same line like that - whereas it's commonplace for property and parameter decorators

**Comment by azz** [comment]
Maybe:

Class and method decorators: always on new line.
Property decorators: inline if fits.

**Comment by vjeux** [comment]
The current heuristic is:

if there is a single decorator and it looks like `@identifier` or `@member.expression` then we inline, otherwise we put it on its own line.

Looks like we also want to add `@fn('stringliteral')`, `@fn(identifier)` and `@fn(member.expression)` to the list.

Also, I agree that for class decorations, we probably don't want to inline ever.

If anyone is interested in building this, that would be great!
