### ISSUE TITLE
TypeScript "trailing comma not allowed" error in type parameters

### ISSUE THREAD

**Issue by JamesHenry** [prettier/prettier#1820]
Source:

```ts
export class BaseSingleLevelProfileTargeting <T extends ValidSingleLevelProfileNode> {
```

Prettier output:

```ts
export class BaseSingleLevelProfileTargeting<
	T extends ValidSingleLevelProfileNode,
> {
```

TypeScript (2.3.3) compiler when compiling the prettier output:

```ts
T extends ValidSingleLevelProfileNode,
                                     ~

(59,39): error TS1009: Trailing comma not allowed.
```

Strangely typescript playground does not seem to have a problem with it:
http://www.typescriptlang.org/play/#src=type%20ValidSingleLevelProfileNode%20%3D%20any%0D%0A%0D%0Aexport%20class%20BaseSingleLevelProfileTargeting%3C%0D%0A%20%20%20%20T%20extends%20ValidSingleLevelProfileNode%2C%0D%0A%3E%20%7B%20%7D

Although that is logging `ts.version: 2.1.4-insiders.20161201` to the console, so perhaps the behaviour changed at some point between those two TypeScript versions?

@danielrosenwasser do you know if that is the case?

**Comment by vjeux** [comment]
I'd love to get more context on the TS side around this. What versions are supported, what versions aren't...

**Comment by DanielRosenwasser** [comment]
Disallow it for now, though I just opened up https://github.com/Microsoft/TypeScript/issues/16152 for you.

**Comment by vjeux** [comment]
Thanks for the quick reply, i'll do it this afternoon!
