### ISSUE TITLE
💖 Way to donate

### ISSUE THREAD

**Issue by alfonsoperez** [prettier/prettier#1823]
Thanks for this!!

Prettier is making my javascript dev life so much nicer, is there a way I can donate a beer worth of money?.

**Comment by vjeux** [comment]
Hey, I'm glad that this is helping you out :)

I'm currently very well (probably way too much :p) paid by Facebook. So don't need the money to get prettier going.

I have no idea how to setup a donation system, what the legal and tax implications are and how to redistribute the money.

From experience, unless there is some major fundraising event, it's unlikely to result in a meaningful amount of money so my inclination is to not go through the motions.

If you want to help, the best thing you can do is to spread the word! Get everyone in your entourage to use it, write blog posts about it, tweet about it, speak at meetups/conferences about it... :)

I'm going to close it but feel free to keep the discussion going! And thanks for the kind words!
