### ISSUE TITLE
Flow Array<Type> angled brackets separated into multiple lines

### ISSUE THREAD

**Issue by dxu** [prettier/prettier#1825]
Hi, I started integrating prettier into one of my projects, and I'm seeing some formatting that I wasn't expecting. [Here's a link to the snippet being converted in prettier](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Cn%20%20%20%20%20%20const%20path%3A%20Array%3Cnumber%3E%20%3D%20this.collider.body.vertices.reduce(%5Cn%20%20%20%20%20%20%20%20(%5Cn%20%20%20%20%20%20%20%20%20%20memo%3A%20Array%3Cnumber%3E%2C%5Cn%20%20%20%20%20%20%20%20%20%20vertex%3A%20Matter.Vector%2C%5Cn%20%20%20%20%20%20%20%20%20%20index%3A%20number%2C%5Cn%20%20%20%20%20%20%20%20%20%20arr%3A%20Array%3CMatter.Vector%3E%2C%5Cn%20%20%20%20%20%20%20%20)%3A%20Array%3Cnumber%3E%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20memo.push(vertex.x)%3B%5Cn%20%20%20%20%20%20%20%20%20%20memo.push(vertex.y)%3B%5Cn%20%20%20%20%20%20%20%20%20%20if%20(index%20%3D%3D%3D%20arr.length%20-%201)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20memo.push(arr%5B0%5D.x)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20memo.push(arr%5B0%5D.y)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20return%20memo%3B%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%5B%5D%2C%5Cn%20%20%20%20%20%20)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

Essentially, I have a variable declaration, the line of code in particular looks like `const path: Array<number> = this.collider.body.vertices.reduce(`, and it's being separated into 

```
const a: Array<
  Type,
> = this.collider.body.vertices.reduce(
```

Is prettier expected to format flow types in this multiline style as well? Note that the line, if kept on one line, doesn't actually hit the 80 character limit, either.

Thanks for all the great work you guys do! I'm excited to start using this in all my projects.

**Comment by vjeux** [comment]
Hey @dxu, thanks for the report!

This is actually an unfortunate side effect of the way prettier works. It only knows how to break nested structures. In this case, we have two groups side by side. I wonder if we could come up with a better design for this use case. @jlongster would you have good ideas?

**Comment by lydell** [comment]
Would it be possible to use the logic around `array[0]` for this somehow? https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Cn%20%20%20%20%20%20Brray%5Ba%5D%20%3D%20this.collider.body.vertices.reduce(%5Cn%20%20%20%20%20%20%20%20(%5Cn%20%20%20%20%20%20%20%20%20%20memo%3A%20Array%3Cnumber%3E%2C%5Cn%20%20%20%20%20%20%20%20%20%20vertex%3A%20Matter.Vector%2C%5Cn%20%20%20%20%20%20%20%20%20%20index%3A%20number%2C%5Cn%20%20%20%20%20%20%20%20%20%20arr%3A%20Array%3CMatter.Vector%3E%2C%5Cn%20%20%20%20%20%20%20%20)%3A%20Array%3Cnumber%3E%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20memo.push(vertex.x)%3B%5Cn%20%20%20%20%20%20%20%20%20%20memo.push(vertex.y)%3B%5Cn%20%20%20%20%20%20%20%20%20%20if%20(index%20%3D%3D%3D%20arr.length%20-%201)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20memo.push(arr%5B0%5D.x)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20memo.push(arr%5B0%5D.y)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20return%20memo%3B%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%5B%5D%2C%5Cn%20%20%20%20%20%20)%3B%5Cn%5Cn%20%20%20%20%20%20Brray%5B0%5D%20%3D%20this.collider.body.vertices.reduce(%5Cn%20%20%20%20%20%20%20%20(%5Cn%20%20%20%20%20%20%20%20%20%20memo%3A%20Array%3Cnumber%3E%2C%5Cn%20%20%20%20%20%20%20%20%20%20vertex%3A%20Matter.Vector%2C%5Cn%20%20%20%20%20%20%20%20%20%20index%3A%20number%2C%5Cn%20%20%20%20%20%20%20%20%20%20arr%3A%20Array%3CMatter.Vector%3E%2C%5Cn%20%20%20%20%20%20%20%20)%3A%20Array%3Cnumber%3E%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20memo.push(vertex.x)%3B%5Cn%20%20%20%20%20%20%20%20%20%20memo.push(vertex.y)%3B%5Cn%20%20%20%20%20%20%20%20%20%20if%20(index%20%3D%3D%3D%20arr.length%20-%201)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20memo.push(arr%5B0%5D.x)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20memo.push(arr%5B0%5D.y)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20return%20memo%3B%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%5B%5D%2C%5Cn%20%20%20%20%20%20)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
@lydell we could add some special cases for common ones indeed. But that is just a band-aid and not a real solution tbh.

**Comment by smithad15** [comment]
This issue also seems to exist with TypeScript code as well. Type generic declarations inside `<>` should be broken into multiple lines only after all other logical groups have been broken. 

_Actual_
```
const a: Array<
  Type,
> = this.collider.body.vertices.reduce(
```

_Expected_
```
const a: Array<Type> = this.collider
  .body
  .vertices
  .reduce(
```
_or_
```
const a: Array<Type> = 
  this.collider.body.vertices.reduce(
```

How the rest of the line gets broken can follow the standard rules, it's more the breaking of the type definition that seems off since it's a logical chunk. Thanks for this tool! It's removed an entire class of nonsense conversations that can usually crop up 😄  One less thing to worry about.

**Comment by ikari-pl** [comment]
I too have this problem with TypeScript and generic types :( There are usually much better places to break the line.

**Comment by dfischer** [comment]
Any hack to make this not look so weird short-term? I want to avoid

```
Promise<
  void
> => {
...
```

**Comment by vjeux** [comment]
Oh I thought I fixed this. We shouldn't ever break if the first element of a generic is a simple value. PR would be welcome!

**Comment by sgwatgit** [comment]
Here with a class, the extends keyword, a generic super class and an interface.

![prettier-generic-subclass-line-break](https://user-images.githubusercontent.com/1382768/28398390-03025de0-6cd5-11e7-8245-3c34c6e0f0b5.jpg)

`"prettier": "^1.5.3",`

**Comment by masaeedu** [comment]
@vjeux If I have a type definition like this:

```
export type Scrollable = (options: ScrollableOptions)
  => <T extends ScrollableProps>(Container: ReactComponent<T>)
  => React.StatelessComponent<T>;
```

Is it possible to tell prettier to prefer splitting at particular operators (specifically `=>`)? Alternatively, is there a way I can globally disable prettier formatting for particular types of AST nodes without having to add `// prettier-ignore` everywhere?

**Comment by fpoumian** [comment]
I'm also having this issue with TypeScript generics:
```typescript
function delayedHello(name: string, delay: number = 2000): Promise<string> {
  return new Promise<
    string
  >((resolve: (value?: string | PromiseLike<string>) => void) =>
    setTimeout(() => resolve(`Hello, ${name}`), delay)
  )
}
```

**Comment by MathieuLorber** [comment]
I have the problem with TS & JSX (TSX). It's weird to observe it doesn't seem systematic : some of my react components have been formatted as expected (generics on the same line), some others not. I don't understand what's the differentiating point.
I think that's the only thing which stops me using prettier yet.

**Comment by jwbay** [comment]
This was the largest source of pushback from my team on adapting Prettier -- heavy TypeScript usage, so lots of generics, and lots of weird breaks that hurt readability.

Would fixing this need https://github.com/prettier/prettier/issues/3014?

**Comment by suchipi** [comment]
@jwbay not necessarily, but it would make fixing it more straightforward. Issues like this one were the motivation for #3014.

**Comment by duailibe** [comment]
I agree with https://github.com/prettier/prettier/issues/1825#issuecomment-313218068, I think we can special case simple generics anyway. A more robust solution would be welcome for the other cases.

**Comment by shaungrady** [comment]
To echo @jwbay, this is prevent our team from adopting Prettier. Would love to see this fixed!

**Comment by suchipi** [comment]
I think we should special-case a generic with only a single identifier as never breaking (like we did for template literals) as a stopgap until we have something like #3014 to handle the general case.

**Comment by vjeux** [comment]
We already prevent breaking for single elements in a bunch of places, if it’s not already be the case for flow generics, we should definitely do that. It is easy to implement if someone wants to give it a go.

**Comment by shaungrady** [comment]
@vjeux I’m completely unfamiliar with the code base, but if you want to point me at a line or two to help get started on the right path, maybe I can see about implementing it when I have some free time.

**Comment by vjeux** [comment]
The usual workflow is the following. You start with the snippet of code and paste it on astexplorer.net and figure out what the tree structure is:

http://astexplorer.net/#/gist/62128d0541f5094945f145ca38c0a007/d8019fa9311c5d5f994484c22c6320a2a4f6c521

![image](https://user-images.githubusercontent.com/197597/38321693-217dde14-37ed-11e8-9424-b242306b4fab.png)

In this case this is a TypeParameterInstantiation with params being an array with a single GenericTypeAnnotation

The next step is to look at the code that prints TypeParameterInstantiation: 
- https://github.com/prettier/prettier/blob/6d7bc4402f78190a2ebce43bc53172d8d26d6299/src/language-js/printer-estree.js#L2512-L2516

What you want is to remove the "group" which is what makes the ability to break into multiple lines when your in this situation.

Looks like there's already logic to do so: https://github.com/prettier/prettier/blob/6d7bc4402f78190a2ebce43bc53172d8d26d6299/src/language-js/printer-estree.js#L3729-L3742

So you need to figure out why this logic isn't working for this specific case.

In order to test, what I recommend is to do `shouldInline = true;` and comment out the rest of the logic and to run the test: `yarn test`. This will show you all the examples that are affected by this change, and you're going to be able to figure out why this rule exists in the first place and add another test case there.

**Comment by shaungrady** [comment]
@vjeux, thanks so much for that awesome write-up of the process. The logic is a little opaque for me, I'm afraid. I don't have a lot of experience working with Node apps, and I'm having difficulty debugging it to pull apart how the logic is working. I'm hoping someone else can step up and make this fix.

**Comment by ralexand56** [comment]
I'm getting this formatting with Typescript 2.9 support for types in template literals
const Wrapper =
  styled.div <
  AppProps >
  `
  padding: 10px;
  font-family: ${p => p.name}
`;

Is there a workaround to get to look like this: 

const Wrapper =
  styled.div<AppProps>`
  padding: 10px;
  font-family: ${p => p.name}
`;

**Comment by lydell** [comment]
@ralexand56 That does not appear to be valid code.

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEB1ATgQwAdC5dMBeAHSk0wwE8AbOAEwDoWBLAN0wB5qtAILEACrgiE0mAHwgANCEkxO6ZKHy4JAd1GaEaZCHzcInFgpAAjAmADWcGAGVC+MJygBzZDFwBXOEUPNFIYcXxPAFt8ZAAzfEYQxQArNAAPACFbB2d8SLgAGQ84OISkkFdcENwjGHoSNDBcTkIYS0Jm2GxzGAALZAAOAAZFDogQvCIjDrhq7hLFXDgARz9OJfComKR4xMCQEMjOH399tA9PZgBFPwh4Ur3FGHwrbpY+5AAmJ4JORguAMIQSLRIxQaALEB+EIAFRehh2ZTgAF9kUA)
```sh
--parser typescript
```

**Input:**
```tsx
const Wrapper =
  styled.div <
  AppProps >
```

**Output:**
```tsx
SyntaxError: '(' expected. (3:13)
  1 | const Wrapper =
  2 |   styled.div <
> 3 |   AppProps >
    |             ^
```

**Comment by ralexand56** [comment]
Sorry, had trouble formatting the code.

`
const Wrapper =
  styled.div<AppProps>`
  padding: 10px;
  font-family: ${p => p.name}
`;
`

After
`const Wrapper =
  styled.div <
  AppProps >
  `
  padding: 10px;
  font-family: ${p => p.name}
`;`

**Comment by duailibe** [comment]
@ralexand56 Typescript parses that as binary expressions: ``(styled.div < AppProps) > `...` ``. Are you sure that works?

**Comment by ralexand56** [comment]
Yes, with typescript 2.9 release candidate

________________________________

**Comment by duailibe** [comment]
Ah ok, then that's a separate issue, we need to bump the parser. Can you open a new issue, please?

**Comment by duailibe** [comment]
@ralexand56 Oh that'll be included in the next release.. should be out in a few days

**Comment by ralexand56** [comment]
Great. Thanks for your help!

**Comment by emilyaviva** [comment]
What's the latest on this issue? It would be really terrific to get this fixed so we could feel better about adopting Prettier across the board.

**Comment by suchipi** [comment]
@emilyaviva I don't think anyone is working on it right now. Could you make a PR to fix it?

**Comment by borisonr** [comment]
Not sure what the status is here, but oddly enough I found that the spacing for typing styled component props works with prettier 1.4.4 but not 1.10.2
