### ISSUE TITLE
double quotes when using switch statement ( case '"[]"': )

### ISSUE THREAD

**Issue by Dkra** [prettier/prettier#1826]
Editor: Atom
Language: Javascript
Config:
single quote => enabled

![image](https://cloud.githubusercontent.com/assets/5117252/26622204/2b8d90e8-461c-11e7-8fcb-de4c988c20b6.png)

should be only one pair of qoutes around the case string

**Comment by azz** [comment]
Can you create a repro at [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20switch%20(env%5B'process.e'%5D)%20%7B%5Cn%20%20%20%20case%20%5C%22ci%5C%22%3A%5Cn%20%20%20%20%20%20return%20require(%5C%22.%2Fci%5C%22)%3B%5Cn%20%20%20%20case%20%5C%22staging%5C%22%3A%5Cn%20%20%20%20%20%20return%20require(%5C%22.%2Fstaging%5C%22)%3B%5Cn%20%20%20%20case%20%5C%22production%5C%22%3A%5Cn%20%20%20%20%20%20return%20require(%5C%22.%2Fproduction%5C%22)%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)?

**Comment by Dkra** [comment]
Please kindly paste the code below to reproduce. (re-click the link is not able to reproduce)

var getConfigFile = function() {
	switch (env['process.env.NODE_CONFIG']) {
		case '"ci"':
			return require('./config-ci.json');
		case '"staging"':
			return require('./config-staging.json');
		case '"production"':
			return require('./config-production.json');
		default:
			throw new Error('This config is not existed');
	}
};

**Comment by k15a** [comment]
What's wrong with this code? You're using double quotes inside a string. We are not going to modify the string because this will change the meaning of the program.

**Comment by k15a** [comment]
`'"foo"'` is not equal to `'foo'`

**Comment by Dkra** [comment]
Yes, the syntax is legal just not make sense to show this after save the file.

**Comment by k15a** [comment]
What output do you expect?

**Comment by Dkra** [comment]
I got what you mean. My bad. Please feel free to close this issue.
