### ISSUE TITLE
Flow functions with generics reported as error

### ISSUE THREAD

**Issue by shashanktomar** [prettier/prettier#1828]
Following is a valid flow statement, but is reported as error by prettier.
`const fun1 = <T>(param: T): T => param;`
`const fun2 = <T>(param: T): T => param;`

Here is the Prettier's REPL: [link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20fun1%20%3D%20%3CT%3E(param%3A%20T)%3A%20T%20%3D%3E%20param%3B%5Cnconst%20fun2%20%3D%20%3CT%3E(param%3A%20T)%3A%20T%20%3D%3E%20param%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by lydell** [comment]
Thanks for the report!

This has been fixed in master, and will be out in the next release! This only happens with the Babylon parser, so until then you could switch to the Flow parser (`--parser flow`).
