### ISSUE TITLE
SyntaxError: private is a reserved word in strict mode

### ISSUE THREAD

**Issue by Jrmy2402** [prettier/prettier#1830]
Hello,

I have a error with prettier in file in typescript.
![capture d ecran_2017-05-31_15-18-37](https://cloud.githubusercontent.com/assets/23458744/26633684/8385d362-4614-11e7-8cf6-e59f4cb2539d.png)

**Comment by vjeux** [comment]
Hey, we're going to release official typescript support this week, it isn't working yet on the version on npm.

**Comment by Jrmy2402** [comment]
Ok thanks

**Comment by vjeux** [comment]
You can try it out on master with --parser typescript if you want :)

**Comment by Jrmy2402** [comment]
I have try, it work perfectly :)

**Comment by Jrmy2402** [comment]
I have a error with the interfaces :

Before:

![capture3](https://cloud.githubusercontent.com/assets/23458744/26669471/4ea36f8e-46ae-11e7-8213-2ae38648fe0e.png)

After:

![capture4](https://cloud.githubusercontent.com/assets/23458744/26669483/56da2d5a-46ae-11e7-86fe-aee92cfdcc85.png)

**Comment by vjeux** [comment]
https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20interface%20Shape%20%7B%5Cn%20%20color%3A%20string%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

I can't reproduce your last example

**Comment by Jrmy2402** [comment]
I have moving my version of Prettier in 1.4.2, it resolve my problem :)
