### ISSUE TITLE
Do not break single Flow type imports to multiple lines

### ISSUE THREAD

**Issue by gillesruppert** [prettier/prettier#1833]
Similar to how we treat `requires`, single imports of flow types should not break across lines if it exceeds 80 characters. 
Multiple items should still break if they exceed 80 characters.

i.e.
# Single line
```javascript
import type Test from 'MyVeryLongModuleNameThatMakes80CharactersAbsolutelyImpossible';
```

# Multiple lines
```javascript
import type {
  Test,
  Foo,
  Bar,
} from 'MyVeryLongModuleNameThatMakes80CharactersAbsolutelyImpossible';
```

Arguably, multiple imports should always be spread over multiple lines, though I have no strong opinion on this, i.e.

# Short multi-line
```javascript
import type {
  Foo,
  Bar,
} from 'ShortModule';
```

**Comment by vjeux** [comment]
I've implemented it in https://github.com/prettier/prettier/commit/267c6edaf5a31dde210c2318e232356c1fffc1e7
