### ISSUE TITLE
Extra parenthesis around jsx with leading comment

### ISSUE THREAD

**Issue by montemishkin** [prettier/prettier#1834]
see here: https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%2F%2F%20some%20comment%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%5Ctfoo%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Seems like the outer parenthesis are not needed? 

Let me know if I can provide any other info :)

**Comment by vjeux** [comment]
This is fixed in master, sorry about that! I'll do a release this week and ship it to Facebook next week.
