### ISSUE TITLE
80 column limit not being honoured

### ISSUE THREAD

**Issue by jasonkuhrt** [prettier/prettier#1840]
I'm running into a problem where 80 column set limit is not being honoured. Screenshot:

![image](https://cloud.githubusercontent.com/assets/284476/26662615/356fc4dc-4653-11e7-920e-c0bc14645d74.png)

You can see many lines well past `80` (the faded grey line is 80). Also, if I add one more `a` to `aaaaaaaaaa` then that line will wrap to become:

```js
const resource = (type: string, value: number): string =>
  `${type}aaaaaaaaaaa${Base62.encode(value)}`
```
And it turns out that line is 100. So it seems that somehow prettier is honouring `100` not `80`. Its very likely this is _not_ a problem with `prettier` but rather with atom-prettier or a config I haven't found yet, etc.

**Comment by lydell** [comment]
Could you post a repro in the [online demo](https://prettier.github.io/prettier/#%7B%22content%22%3A%22hello%20(%20%5C%22world%5C%22%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)?

**Comment by k15a** [comment]
Do you have prettier-eslint enabled? Probably ESLint is moving them to one line again so you don't see the prettier output.

**Comment by jasonkuhrt** [comment]
> Do you have prettier-eslint enabled? Probably ESLint is moving them to one line again so you don't see the prettier output.

Yup I do. I'll try disabling it to see what happens.

> Could you post a repro in the online demo?

Sure thing. Will do later today.

**Comment by jasonkuhrt** [comment]
@k15a nailed it. I updated my eslint rules to not deal with line length anymore e.g. `"max-len": 0,`.

Thanks everyone for responding so quickly!
