### ISSUE TITLE
Medium-length arrow function argument weirdly prettified

### ISSUE THREAD

**Issue by avaly** [prettier/prettier#1843]
An arrow function with a medium-length body as a first argument will be broken in the following way:

Input:
```js
filter(
  filePath => filePath.match(/^(foo|bar|ham|other-long-thing-here-to-break)\//)
);
```

Prettier output:
```js
filter(filePath =>
  filePath.match(/^(foo|bar|ham|other-long-thing-here-to-break)\//)
);
```

It feels like the input version is more readable than the Prettier version.

**Comment by bakkot** [comment]
I prefer the latter, personally.

**Comment by azz** [comment]
This one is working as intended.
