### ISSUE TITLE
TypeScript: `readonly` modifier gets removed

### ISSUE THREAD

**Issue by clebert** [prettier/prettier#1845]
Version: v1.4.0-beta

Input:

```js
class Foo {
  public readonly foo = 'string';
}
```

Actual Output:

```js
class Foo {
  public foo = 'string';
}
```

Expected Output:

```js
class Foo {
  public readonly foo = 'string';
}
```

**Comment by vjeux** [comment]
Thanks, we should fix it!

**Comment by vjeux** [comment]
This is actually an issue with the underlying project. https://github.com/eslint/typescript-eslint-parser/issues/302

**Comment by vjeux** [comment]
You can add `// prettier-ignore` on the line before while we are fixing this. Sorry about it!
