### ISSUE TITLE
TypeScript: Brackets around statement before 'as' get removed

### ISSUE THREAD

**Issue by crohlfs** [prettier/prettier#1851]
Input:
```ts
({}) as {};
```
Output:
```ts
{} as {};
```

[Input](https://prettier.github.io/prettier/#%7B%22content%22%3A%22(%7B%7D)%20as%20%7B%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

[Output with syntax error](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%7B%7D%20as%20%7B%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D):

**Comment by vjeux** [comment]
Fixed by https://github.com/prettier/prettier/pull/1852 :)
