### ISSUE TITLE
Typescript: 'export default function' gets replaced with 'export function'

### ISSUE THREAD

**Issue by crohlfs** [prettier/prettier#1854]
[Reproduction](https://prettier.github.io/prettier/#%7B%22content%22%3A%22declare%20module%20%5C%22hello%5C%22%20%7B%5Cn%20%20%20%20export%20default%20function()%20%7B%7D%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

Input:
```ts
declare module "hello" {
    export default function() {};
}
```

Output:

```ts
declare module "hello" {
  export function() {
  }
}
```
[Syntax error in output](https://prettier.github.io/prettier/#%7B%22content%22%3A%22declare%20module%20%5C%22hello%5C%22%20%7B%5Cn%20%20export%20function()%20%7B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
Go already reported here fyi

https://github.com/eslint/typescript-eslint-parser/issues/263

**Comment by crohlfs** [comment]
Ok nice - no more issues from my end, great work 👍

**Comment by vjeux** [comment]
Okay, thanks! While those are being fixed you can add `// prettier-ignore` on the line before to get you unblocked.

I'm likely going to add cheap and dirty workarounds for tomorrow's release!
