### ISSUE TITLE
Typescript: 'private static' method get replaced with 'static private'

### ISSUE THREAD

**Issue by netanelgilad** [prettier/prettier#1855]
Just checked version 1.4.0-beta on my typescript codebase. Got 2 issues that created invalid typescript. Will open another issue for the other one.

Input:
```
class Check {
  private static aMethod() {}
}
```

Actual Output:
```
class Check {
  static private aMethod() {}
}
```

Expected Output:
```
class Check {
  private static aMethod() {}
}
```

Gets Typescript error:
```
Error:(2, 10) TS1029:'private' modifier must precede 'static' modifier.
```

[Reproduction repository](https://github.com/netanelgilad/prettier-repro)

Thanks for the great effort on adding typescript support!

**Comment by fifafu** [comment]
Same for "public static".

**Comment by menzer** [comment]
@vjeux I'm still encountering this issue in the released 1.4.0 version. Maybe I'm misreading the commit history, but it looks like the PR that closed this issue should be included in that release.

**Comment by vjeux** [comment]
@menzer the PR that closes the issue has been included in the release. The original issue is no longer a problem:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Check%20%7B%5Cn%20%20private%20static%20aMethod()%20%7B%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

But, it's not impossible that there are other places where we have this issue. Do you have a piece of code that is not working that you can share?

**Comment by menzer** [comment]
@vjeux Ah, I see. The issue was fixed for methods, but not properties. The following will print incorrectly:

```ts
export class Check {
  private static property = 'test';
}
```

Would you like me to file a separate issue?

**Comment by vjeux** [comment]
Yes, a separate issue would be great, thanks!
