### ISSUE TITLE
How to use prettier in browser?

### ISSUE THREAD

**Issue by janryWang** [prettier/prettier#1867]

**Comment by vjeux** [comment]
I'm curious, what is your use case?

**Comment by janryWang** [comment]
I want make a web editor, it needs a jsx formatting feature

**Comment by janryWang** [comment]
@vjeux when i use webpack to build my project , so UglifyJs throws an error , when i check the prettier code, I found prettier/index.js is not es5 version code. Could you please compile the code with babel before npm publish ? Although I can use local babel compiler, but the efficiency is too low.

this is my webpack config.

```
var baseConfig = require('./webpack.base.js')
var webpack = require('webpack')
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = Object.assign({}, baseConfig, {

    module: {
        loaders: [
            {
                test: /\.html$/,
                loaders: ['html-loader']
            }, {
                test: /\.css$/,
                loaders: [
                    'style-loader',
                    'css-loader'
                ]
            },{
                test: /\.less$/,
                loaders:[
                    'style-loader',
                    'css-loader',
                    'postcss-loader',
                    'less-loader'
                ]
            }, {
                test: /\.(png|woff|woff2|eot|ttf|svg|gif)/,
                loaders: ['url?limit=100000,img?minimize']
            }, {
                test: /\.(js|jsx)$/, 
                //I can not add exclude node_modules
                loaders: [
                    'babel-loader'
                ]
            }
        ]
    },

    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'production')
            }
        }),
        new ExtractTextPlugin('index.css'),
        new webpack.optimize.UglifyJsPlugin({
            compressor: {
                screw_ie8: true,
                warnings: false
            }
        })
    ]
})

```

**Comment by vjeux** [comment]
Sooo, we kind of have a version that works on the browser ( https://github.com/prettier/prettier/tree/master/docs ) but the whole pipeline is super fragile. I'd love to make it more robust but don't have the motivation right now.

**Comment by janryWang** [comment]
Awesome! Thanks! @vjeux

**Comment by Gregoor** [comment]
@vjeux anything one could do to speed up the process? PR's welcome?

**Comment by vjeux** [comment]
@gregoor try to make it better? :p

**Comment by Gregoor** [comment]
Sure, if PR's are welcome on that, I'll look into it next week!

**Comment by ritz078** [comment]
If someone is looking for a quick solution you can use https://bundle.run/prettier@1.6.1 . You may get an error on Safari and that is because of a bug with the browser which has been fixed in the latest Safari Tech Preview 31.

**Comment by mstijak** [comment]
I managed to bundle (and minify) prettier using webpack like this:

```
import parse from "prettier/src/parser-babylon";
import { printAstToDoc } from "prettier/src/printer";
import { printDocToString } from "prettier/src/doc-printer";

export function format(code) {
   let opts = {
      cursorOffset: -1,
      rangeStart: 0,
      rangeEnd: Infinity,
      useTabs: false,
      tabWidth: 2,
      printWidth: 80,
      singleQuote: false,
      trailingComma: "none",
      bracketSpacing: true,
      jsxBracketSameLine: false,
      parser: "babylon",
      insertPragma: false,
      requirePragma: false,
      semi: true
   };
   const ast = parse(code);
   const doc = printAstToDoc(ast, opts);
   const result = printDocToString(doc, opts);
   return result.formatted;
}
```
The only minor annoyance is that prettier package doesn't include `src` so I had to change to:
```
 "prettier": "git://github.com/prettier/prettier.git#1.7.4",
```
in `package.json`.

**Comment by siefkenj** [comment]
Could someone who has gotten this working spell out the process for me? I am unfamiliar with proper usage of `webpack` and `bundle`. (Nor can I seem to imitate what is going on in the _playground_. Whenever I try to get similar code working, I get missing `require` errors...)

**Comment by duailibe** [comment]
Let's discuss this in #3296 so we can get built-in support for prettier.
