### ISSUE TITLE
JSX params and children bracket spacing

### ISSUE THREAD

**Issue by pandaiolo** [prettier/prettier#1871]
<Hello value={ 'world' }>
      { children }
    </Hello>

Is corrected to the following despite using the `bracketSpacing` option:

    <Hello value={'world'}>
      {children}
    </Hello>

I now that option is for object literals, but is there a way for those who use spaces inside JSX components params or children to keep them? I did not find the option nor closed issues about this, so not sure what is the official opinion about this? 

I use spaces inside all my brackets, even if they are not object literals. Am I doing it wrong? :)

**Comment by vjeux** [comment]
Hey, thanks for creating an issue. This has been asked a number of times but unfortunately, we are not going to provide an option for this. If you really want to use prettier, you'll either have to live with how it prints things or fork it I'm afraid.

By the way, you should likely be writing it without `{}`:

```js
<Hello value="world">
  {children}
</Hello>
```
