### ISSUE TITLE
No-semi + class properties edge case with `in`/`instanceof`.

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#1875]
Sorry, these too did not occur to me. (From [here](https://github.com/tc39/proposal-class-public-fields/issues/63#issuecomment-305853251).)

With no-semi,

```js
class A {
  prop = a;
  in;
  b;
}
```
gets [rendered as](https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20A%20%7B%5Cn%20%20prop%20%3D%20a%3B%5Cn%20%20in%3B%5Cn%20%20b%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)
```js
class A {
  prop = a
  in
  b
}
```
which is
```js
class A {
  prop = a in b;
}
```

Same problem with `instanceof`.

**Comment by vjeux** [comment]
I just published 1.4.1 which fixes it!
