### ISSUE TITLE
Inline call({} as Type)

### ISSUE THREAD

**Issue by prencher** [prettier/prettier#1881]
Input:
```ts
interface State {
  next: string;
  nonce: string;
}

const state = JSON.stringify({
  next: window.location.href,
  nonce,
} as State);
```
Output:
```ts
interface State {
  next: string;
  nonce: string;
}

const state = JSON.stringify(
  ({
    next: window.location.href,
    nonce
  }) as State
);
```
The surrounding parens here are superfluous, and in general the output should probably stay identical in this case?

**Comment by vjeux** [comment]
We should be able to make both of your suggestions.

**Comment by clebert** [comment]
Here is a simpler example:

Input:

```js
let config: Config = {} as Config;
```

Output:

```js
let config: Config = ({}) as Config;
```

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/pull/1923 fixes the parenthesis issues. For inlining the `as`, I'm not sure if we should do it. I'm going to leave the issue open for it.

**Comment by azz** [comment]
We now inline `as`, as of #2439
