### ISSUE TITLE
TypeScript: `private static` property prints as `static private`

### ISSUE THREAD

**Issue by menzer** [prettier/prettier#1883]
Input

```ts
export class Check {
  private static property = 'test';
}
```

Output

```ts
export class Check {
  static private property = 'test';
}
```

Expected

```ts
export class Check {
  private static property = 'test';
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20class%20Check%20%7B%5Cn%20%20private%20static%20property%20%3D%20'test'%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
I just published 1.4.1 which fixes it!
