### ISSUE TITLE
TypeScript: Inconsistent parens for union types

### ISSUE THREAD

**Issue by prencher** [prettier/prettier#1885]
Input (with `--print-width 1` so it doesn't condense it to a single line):
```ts
export type A = (
  string |
  number
);

export type B = (
  | string
  | number
);

export type C = string | number;
```
Output:
```ts
export type A = (
  | string
  | number);

export type B = (
  | string
  | number);

export type C =
  | string
  | number;
```

Would expect the closing `);` to be on its own line, and for case C to match the output of A and B (or for A and B to match C).

**Comment by vjeux** [comment]
Grrr, TypeScript adds a TSParenthesizedType around :( I'll see what I can do

**Comment by vjeux** [comment]
Right now the workaround is to not use parenthesis there. But we should probably do something about it. It's not a very easy fix though unfortunately.

**Comment by KevinKelchen** [comment]
Hi! :wave:

I'm not sure if it should be a separate issue (if it should I will gladly open one!), but note that prettier is adding an extra `|` character between the `=`operator and the first type listed. This results in a TypeScript compilation error.

The syntax should be like this example:

`export type A = string | number;`

Not how it's actually printing:

`export type A = | string | number;`

**Comment by vjeux** [comment]
@KevinKelchen could you create a different issue? It has nothing to do with the original one :)

**Comment by KevinKelchen** [comment]
Will do! Thank you! 👍

**Comment by christophercliff** [comment]
I'm experiencing a problem with string unions and dynamic keys that's possibly related:

Input (valid TS):

```ts
interface foo {
    myEnum: ('a' | 'b')
    [k: string]: any
}
```

Output (invalid TS, doesn't compile):

```ts
interface foo {
    myEnum: 'a' | 'b'
    [k: string]: any
}
```

Note that the following is valid:

```ts
interface foo {
    myEnum: 'a' | 'b'
    myStaticProp: any
}
```

**Comment by azz** [comment]
That seems more like a bug in TypeScript. @JamesHenry what do you think?
