### ISSUE TITLE
Version 1.4.0 seems to be built with old dependencies

### ISSUE THREAD

**Issue by clebert** [prettier/prettier#1887]
The bug fixed with Commit #1865 still occurs with Prettier@1.4.0

If I build the master myself, with `npm run build`, the bug is fixed.

**Comment by vjeux** [comment]
Arrrggg, you are right, I forgot to do `yarn` before publishing :( I'll make sure I do when I release 1.4.1, sorry about that!

**Comment by vjeux** [comment]
I just published 1.4.1 which fixes it!
