### ISSUE TITLE
Ugly line break in a template string

### ISSUE THREAD

**Issue by clebert** [prettier/prettier#1893]
Not really an error, but in my opinion, ugly.

Input:

```js
const description =
  `The value of the ${cssName} css of the ${this._name} element`;
```

Output:

```js
const description = `The value of the ${cssName} css of the ${this
  ._name} element`;
```

Expected:

```js
const description = `The value of the ${cssName} css of the ${
  this._name
} element`;
```

Or something like that...

**Comment by Skywalker13** [comment]
Maybe templates should never be wrapped because it looks ugly most of time.

This input
```js
const description =
  `The value of the ${cssName} css of the ${this._name} element`;
```

looks better that
```js
const description = `The value of the ${cssName} css of the ${
  this._name
} element`;
```

even if it's longer than 80 cols

**Comment by ndresx** [comment]
I agree @Skywalker13, such strings should never wrap.

**Comment by O4epegb** [comment]
Do i understand correctly, that wrapping also adds new line characters? If so, then it can break some formatting when someone not expecting additional newline there, doesnt it?

**Comment by Skywalker13** [comment]
@O4epegb not here, because the new line is added in the JS code `${... HERE ...}`, not in the string.

**Comment by O4epegb** [comment]
@Skywalker13 Yes, i mean otherwise, even if it breaks correctly inside the string, it will add new line character, right?

**Comment by Skywalker13** [comment]
Yes, in the source code; it's the case between `v1.3.x` and `v1.4.x`. It was looking better with `v1.3.x`.

**Comment by Widdershin** [comment]
I used `git bisect` to determine the commit where this behaviour changed:

commit 374a68201c966ee9064a1173f5dfeb37980cfbe3 (pr #1664)
Author: Joseph Frazier <1212jtraceur@gmail.com>
Date:   Mon May 22 12:00:01 2017 -0400

    Don't removeLines() from TemplateLiteral quasis (#1664)

    * Add tests for newlines in template literals

    These are related to the following issues:

    * https://github.com/prettier/prettier/issues/1662
    * https://github.com/prettier/prettier/issues/821
    * https://github.com/prettier/prettier/issues/1183
    * https://github.com/prettier/prettier/issues/1626

    * Don't removeLines() from TemplateLiteral quasis

    This fixes https://github.com/prettier/prettier/issues/1662
    and fixes https://github.com/prettier/prettier/issues/1626

    It also affects https://github.com/prettier/prettier/issues/821 and
    https://github.com/prettier/prettier/issues/1183

The code change was in `src/printer.js`:

```diff
@@ -1672,11 +1672,7 @@ function genericPrintNoParens(path, options, print, args) {
             size = util.getAlignmentSize(value, tabWidth, index + 1);
           }

-          const aligned = addAlignmentToDoc(
-            removeLines(expressions[i]),
-            size,
-            tabWidth
-          );
+          const aligned = addAlignmentToDoc(expressions[i], size, tabWidth);

           parts.push("${", aligned, lineSuffixBoundary, "}");
         }
```

Personally I would like to see this changed.

Here is the example I was testing:

```js
const foo = `such a long template string ${foo.bar.baz} that prettier will want to wrap it`;
```

which now becomes

```js
const foo = `such a long template string ${foo.bar
  .baz} that prettier will want to wrap it`;
```

Which definitely seems like a bug to me, I don't think prettier should wrap inside of template strings.

**Comment by azz** [comment]
@Widdershin
> I don't think prettier should wrap inside of template strings.

Sometimes it is necessary. We don't want to regress on progress made from #1662, #821, #1183, and #1626.

We need to find a sufficient heuristic to determine _when_ to wrap, and when we do, we should output:

```js
const foo = `such a long template string ${
  foo.bar.baz
} that prettier will want to wrap it`;
```

**Comment by Widdershin** [comment]
> We need to find a sufficient heuristic to determine when to wrap, and when we do, we should output

I am unconvinced that a suitable heuristic can be made to satisfy everybody's requirements. If someone has an idea, please share it.

I am now personally of the belief that prettier should respect existing formatting within template strings. This seems at odds with the prettier design, but it's the only long term solution I can see.

Is this even possible with the way prettier is implemented?

**Comment by vjeux** [comment]
> I am now personally of the belief that prettier should respect existing formatting within template strings.

We actually experimented just printing the string as is, but people complained that prettier didn't change ' to " and format their code.

The current status is not ideal for sure, we'll keep iterating on it. I do believe that we can get it to work well for most use cases. We're just not 100% there yet (but getting way better in each version of prettier).

**Comment by leipert** [comment]
Here are some more examples / test cases that I had after a recent upgrade:
```js
console.log(
  `Trying update appcast for ${app.name} (${app.cask.appcast}) -> (${app.cask.appcastGenerated})`
)

console.log(`brew cask audit --download ${_.map(definitions, 'caskName').join(' ')}`)

console.log(`\nApparently jetbrains changed the release artifact for ${app.name}@${app.jetbrains.version}.\n`);

// turns into 

console.log(
    `Trying update appcast for ${app.name} (${app.cask.appcast}) -> (${app
        .cask.appcastGenerated})`
);

console.log(
    `brew cask audit --download ${_.map(definitions, "caskName").join(
        " "
    )}`
);

console.log(
    `\nApparently jetbrains changed the release artifact for ${app.name}@${app
        .jetbrains.version}.\n`
);


```

[in playground](https://prettier.io/playground/#%7B%22content%22%3A%22%5Cnconsole.log(%5Cn%20%20%60Trying%20update%20appcast%20for%20%24%7Bapp.name%7D%20(%24%7Bapp.cask.appcast%7D)%20-%3E%20(%24%7Bapp.cask.appcastGenerated%7D)%60%5Cn)%5Cn%5Cnconsole.log(%60brew%20cask%20audit%20--download%20%24%7B_.map(definitions%2C%20'caskName').join('%20')%7D%60)%5Cn%5Cnconsole.log(%60%5C%5CnApparently%20jetbrains%20changed%20the%20release%20artifact%20for%20%24%7Bapp.name%7D%40%24%7Bapp.jetbrains.version%7D.%5C%5Cn%60)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A75%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

(I adjusted the line width to get the ugly line break in example 2)

**Comment by constantyn** [comment]
Changing the output of template string means that prettier will change the working of the code by adding newlines and spaces to a string. This is not wat prettier should be about. Prettier is about code format not code output. I will have to revert to 1.3.1 until this issue is fixed.
Please remove this behaviour because I love prettier a lot and I really want to stay up to date with the latest release.

**Comment by azz** [comment]
@constantyn The runtime behavior is not modified. Could you provide an example where it is?

**Comment by jwbay** [comment]
What if we just never break 'simple' expressions in template strings? The definition of simple is TBD unless there's a precedence in Prettier already. Off the cuff:
* Identifiers
* Property access
* Ternaries or BinaryExpressions, where each node is one of the above

Or instead the line could be drawn at the other end. Don't break unless for:
* Functions
* Object/Array literals
* ?

What seems to be difficult is telling the difference between graphql and css-in-js, where breaks are encouraged from what I can tell, and situations like user-facing strings and regexes, where breaks hurt readability and lead to more [WTFs/min](http://www.osnews.com/story/19266/WTFs_m). So another option could be adding a blanket don't-break-expressions rule for template strings, and adding special casing for these libraries.

**Comment by vjeux** [comment]
@jwbay that sounds reasonable to avoid breaking simple ones. Do you want to give it a shot?

**Comment by DorZion** [comment]
Any news on this one?
Still happening on versions `1.15.0` and `1.16.0`.

**Prettier 1.16.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAhAggZQFEB9AVQCUAZJTDAJwEsoBzTAXkwAMALGGAByQB6IQBJg-OhDBw0aAHQIAbvIBqhcgE1ilAPIA5AOLFVucgElc2SoUwAfO5gDkAG2kBDF9wgYnAXyQAZgAGYIBGTgBuEAAaEAh+GAZ0ZFB3OikAdwAFdIQ0ZBB3JQgGABNYkAAjOncwAGs4GHx+OqZmZBg6AFc4ON4AWxcAdW4GeDRWmXx88YYlcYBPQrA5SqY0ODoYbNrmAfdkADNPTbiAKzQAD2xahqb8dwG4SiY4Y9O+kEur-HaXOAARW6EHgHxcZxArTomzohRgi34sjAjESlUkTBgw3KMG4yAAHME4pIfHBhrV+IVJLItkp3nE6HAAI7dBiM3bufaHJAnCFfTYDBidHr8-5AkFgnmfOIwdxVbFlXHIABMMtqDBc7QAwhABgdClBoPSQN1NgAVOUFKV8vx+IA)
```sh
--parser typescript
```

**Input:**
```tsx
const BASE_URL: string = `http://${process.env.VERY_LONG_VARIABLE || 'localhost'}:3001`;
```

**Output:**
```tsx
const BASE_URL: string = `http://${process.env.VERY_LONG_VARIABLE ||
  "localhost"}:3001`;

```

**Expected behavior:**
```jsx
const BASE_URL: string = 
  `http://${process.env.VERY_LONG_VARIABLE || 'localhost'}:3001`;
```

The string in the expected behavior is in the print width range (80).

**Comment by nhustak** [comment]
Why is this closed - it's still a problem.

**Comment by suchipi** [comment]
This is closed because the code in the original post now formats as expected:

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATOawBOAlgA4xHSYC8AOlJpgAYAqAFnJgG4CGANgK4cIAM0wx2mACTAwaNADluAWzgBfTLLSYRYidPFE0AOgD6UZWsxxecFbEYBuEABoQEMhShpkobgQIQAO4ACn4I3ijcnBBE2C4gAEYE3GAA1nAwAMokKURQAObIMASCrqwwSrwA6qxE8Gg5YHCZ4XVEnHUAnsjgcvF5aHAEMMHJ+UrcyMJ8g64AVmgAHgBCyWkZmRYAMnlwUzNw80uZefk2AIr8EPD7vLMgOQSDBD0J3AmdvNDxJMSwVbFxMgABwABlcvwggyqyRIPV+eCGnD2rgIcAAjvwiGjRtxxpMkNM7ocQIMlEQiiUSWhThcrjdCQdXDB3gDsECkAAmZnJIi8U4AYQgSgmPSg0BRIH4g2Y7wiRMGqlUQA)
```sh
--parser babylon
```

**Input:**
```jsx
const description =
  `The value of the ${cssName} css of the ${this._name} element`;
```

**Output:**
```jsx
const description = `The value of the ${cssName} css of the ${
  this._name
} element`;

```

If you have a different example that doesn't format nicely, please open a new issue.

I know they look very similar but internally these are different code paths and if we aren't specific with this type of work, it's easy to get lost or miscommunicate.

@DorZion could you open a new issue for your example?

**Comment by nhustak** [comment]
ok I think I understand what we're seeing now.   Thanks - I'm getting what looks like a format due to the length of my string.

**Comment by arobinson** [comment]
Has this had a regression?
I have my print width set to 140, and this line is not wrapping at all in this Angular typescript :
```    const moduleUrl = `src/app/gen-apps/nw-component-${component}/nw-component-${component}.module#NwComponent${component.toUpperCase()}Module`;```
(line length of 145)
I would have expected it to wrap after the equal sign or at least somewhere in the template string. If I manually correct it and re-run prettier it breaks the fix, putting it back on one line.

**Comment by hawkrives** [comment]
@arobinson Can you open a new issue with a reproduction on the playground (prettier.io), please?

If you can't reproduce on the playground, it's _probably_ something else on your computer, but either way, a new issue is probably better to get to the bottom of this.

**Comment by trevor-anderson** [comment]
Here's another example that formats poorly:

`const initials = `${profile.givenName.charAt(0)}${profile.familyName.charAt(
      0
    )}`;`

**Comment by trevor-anderson** [comment]
Here's another example that formats poorly:

```
const initials = ${profile.givenName.charAt(0)}${profile.familyName.charAt(
    0
)};
```

**Comment by Itach1Uchixa** [comment]
Example prettier version 2.3.0 [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwGUBXAIwCs4wCBffAMxwnXwB0QcAPSgZ04BudlAzY8hJqgA28HABp8fABYBDHHEXo4OAOZwAsqsyKYx-A2asOXXnwD0ETDtUxcAkMNFZcBaRF19HCYWNk4AOnD7Ph0AN1QwOAdjTGkE11RoAFp-QJ0hETFffAAlOHECKzCQFPt0CAATOGkHDQqC7wrS8t8yKhoYAFEoUjYqm1r6ppb7Nt8svgpqWiyEUY6ROG4upsZVUll8KDgAdxIlgYAKAEpwzFRnS5F8KVkdS8uiKFVtRThYhAwPiKPhmeAWa74AC8AD4jj84PgAGRI-D-QF8ZGo0GuODXeTPfDaPSGYwfIg4+BIfBgBE4VTEMFwADCaig+gh0JhhJetOJDKZrNU7LgdwecCeUBe0tecg+fJckNhNLpqnCqD4ZUgOAaqHZwyaDRu+J50uJ+iMmEuqj4AE8oGB8JcFfSlXDgKaZbkguqoIwIJcAAbMjQZdlHU74ADkABJgIt+rRwm5GTg9bobnQo-g5hJxi7VNG4wXwt9tFnA9cvDKXnRrqb61L8Camyp1BLG1WRCB5CAnDBMlA+MhQOoWCcAArtofIGrSE6qW3D3vkelgADWcBgxEwqjA6eQMBwpE0IDg6HIcAahoAMsLdKRVPoAGK4dCuAfs2f7Nw9kDKGB0GkAB1ZRUHgPhd0SYgED4cDUHiGBbVnMA+GXNAhx0GAJ3pXR32QPYWlPfhuAAITXTdtwRG89TgAjVCI3sSOIdNpDgABFUgIHgejGJAXccBiHBZ3IVRL2kP9MDTWBgNQBoYGUZAAA4AAZeykiAYmA+lMFnKSkjiOjewARy4+AcKcYcUBtLJjivK8-w0UzUA0HCn3wpBCJiXsYnQVBD2PU84PZNjOO4ujPIY7yQDMchZPkxSkAAJl7I9VBkdNmVYDyzz4ABWP9SBiAAVMSrK809YhPABJKAmlgYgwDTTAYAAQTqxlbTY3iYjoOggA)
```js
logger.info(`Creating new '${subject.toString()}' report from camera '${camera.name}'`);
```

got converted to:
```js
logger.info(
  `Creating new '${subject.toString()}' report from camera '${
    camera.name
  }'`
);
```
which is way uglier

**Comment by GongT** [comment]
Is there an option to configure this? It always uglier in my life.

If I really think it's too long, I will do this manually:
```ts
console.log(`hash mismatch:\n` + 
	`        want: ${md5}\n` +
	`        got : ${calc}`
);
```

**Comment by philippefutureboy** [comment]
Would implementing an ignore config option in the config be a suitable option for most users?
Something like:

```
"stringWrap": undefined // defaults to break string at printWidth
"stringWrap": "none" // disable
"stringWrap": "split" // splits the string over multiple line and concatenate using the + sign
"stringWrap": 120 // break the string only if the line is above 120 chars
```

Alternatively, taking from the python ecosystem, maybe strings shouldn't be wrapped at all; by default in the Python ecosystem, the equivalent of `prettier`, `black`, does not break strings.
My opinion is: Leave it to the developers to break their strings correctly because otherwise prettier has to satisfy everybody's requirement of natural language split readability, which varies from case to case and language to language.

**Comment by nickyvanurk** [comment]
I also wish prettier would have a hard printWidth limit. That nothing will exceed its length, no strings and no comments, etc. I am developing with 3 code tabs open in VSCode so any code that's longer than let's say 80 characters forces me to use horizontal scrolling which is suboptimal. I wish I could just enforce this rule and never think about it again. This also is my biggest issue with prettier.

**Comment by philippefutureboy** [comment]
All the more for having a config point to support your case and the other cases :) 👍
