### ISSUE TITLE
[Subjective] TypeScript inline class member decorator becomes less readable

### ISSUE THREAD

**Issue by menzer** [prettier/prettier#1898]
Related to #1817  one inline class member decorator case that's still missed, which affects Angular readability, is inline class member decorators called with empty arguments:

Input, and expected output

```ts
@Component({
  selector: 'angular-component',
})
class AngularComponent {
  @Input() myInput: string;
}
```

Actual output

```ts
@Component({
  selector: 'angular-component',
})
class AngularComponent {
  @Input()
  myInput: string;
}
```

While subjective, this matters because this is an extremely common use case in Angular, and this is preferred over using these decorators with parameters when possible. `@Input` is not a replacement in this case for `@Input()`.

See https://angular.io/styleguide#!#05-12 and https://angular.io/styleguide#!#05-13 for Angular's style guidance and reasoning related to this use case.

**Comment by prencher** [comment]
This is the exact opposite of what we would want on our projects, so I would think this has to be an option if implemented.

**Comment by menzer** [comment]
Can you elaborate? I'm not disagreeing, but I'd be curious to see an example where, given the changes already added to prettier from #1817, this current behavior is not an inconsistent outlier.

**Comment by vjeux** [comment]
@menzer thanks, this is indeed an oversight, we'll get a fix. (Or if you want to, shouldn't be hard to implement)

**Comment by menzer** [comment]
Looks like you beat me to it. 👍

**Comment by vjeux** [comment]
Yeah sorry... Trying to fix as much as a can quickly and do another release :)

**Comment by vjeux** [comment]
I just published 1.4.1 which fixes it!

**Comment by Strate** [comment]
Any chance to get this configurable?
For me, for class properties, which are prefixed by visibility keyword (private, public, protected) decorators should be on different line

**Comment by azz** [comment]
The accessibility modifier use case is interesting, it won't be made configurable but we can talk about changing the behaviour in that case.

**Comment by Strate** [comment]
This is good for me:
```ts
class SomeClass {
  @decorate property

  @decorate
  private property
}
```

**Comment by azz** [comment]
Open a new issue with a proposal. 😄
