### ISSUE TITLE
Typescript: Unexpected Token on private when using --stdin

### ISSUE THREAD

**Issue by sheldonkwok** [prettier/prettier#1900]
```
stdin: SyntaxError: Unexpected token (376:11)
  374 |   }
  375 | 
> 376 |   private foobar() {
      |           ^
```

However, it doesn't error when not using `--stdin`

**Comment by vjeux** [comment]
It's likely using the flow parser. You either need to provide the --filepath something.ts option or --parser typescript

**Comment by sheldonkwok** [comment]
Yep that was it thanks! The --help is missing typescript in the `--parser` options
