### ISSUE TITLE
Extra semicolon in the begin of the line

### ISSUE THREAD

**Issue by Rudeg** [prettier/prettier#1907]
Input:
```js
[a,b ,c ]
  .forEach(x => {
  console.log(x)
})
```

Output:
```js
;[a, b, c].forEach(x => {
  console.log(x)
})
```

Expected:
```js
[a, b, c].forEach(x => {
  console.log(x)
})
```

Example:
https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Ba%2Cb%20%2Cc%20%5D%5Cn%20%20.forEach(x%20%3D%3E%20%7B%5Cn%20%20console.log(x)%5Cn%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by k15a** [comment]
This semicolon is actually required.
```js
hello()

;[a, b, c].forEach(x => {
  console.log(x)
})
```

is something different then
```js
hello()

[a, b, c].forEach(x => {
  console.log(x)
})
```

**Comment by Rudeg** [comment]
@k15a Yeah, it's true. But not for the all cases. For exmaple:

```
function hello() {
[a,b, c]
  .forEach(x => {
  console.log(x)
})
}
```

If expression is a first line after the function declaration - it will be valid
In this case prettier will add an extra semicolon.

Example:
https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20abc()%20%7B%5Cn%5B1%2C2%2C%203%5D%5Cn%20%20.forEach(x%20%3D%3E%20%7B%5Cn%20%20console.log(x)%5Cn%7D)%5Cn%7D%5Cn%5Cnfunction%20abc()%20%7B%5Cn%20%20console.warn(123)%3B%5Cn%5Ba%2Cb%2Cc%5D%5Cn%20%20.forEach(x%20%3D%3E%20%7B%5Cn%20%20console.log(x)%5Cn%7D)%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by k15a** [comment]
That's a good point. Don't know if there is a specific reason why we add a semicolon there. Maybe @bakkot and @rattrayalex can clarify this.

**Comment by vjeux** [comment]
This is actually intended. If you move this line around, then it's always safe and you can't get into a weird issue where you forgot and now it behaves differently.

**Comment by lydell** [comment]
For reference, here’s a list of issues explaining the decision further: https://github.com/prettier/prettier/issues/1935#issuecomment-306729468
