### ISSUE TITLE
The website doesn't work anymore on safari/iphone

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1928]

**Comment by SimenB** [comment]
`ReferenceError: Can't find variable: prettier`, interesting!

**Comment by ndresx** [comment]
`SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.` in `index.js`. 

Unfortunately there is no way to build this locally at the moment as the `rollup.config.js` file for `build:docs` is missing.

**Comment by vjeux** [comment]
Oops. The new way to build the docs is via yarn build. I need to remove yarn bulild:docs as it's not working anymore

**Comment by ndresx** [comment]
I could take care of it if you want. Also regarding the website problem, I saw that for the different parsers rollup's `useStrict` option is set to `false`. I guess that's the preferred way to go for the `index.js` too?

**Comment by vjeux** [comment]
I set `useStrict: false` for the flow parser because it doesn't work without it. I didn't dig into why.

**Comment by vjeux** [comment]
@ndresx if you want to help cleaning this up, that would be awesome!
