### ISSUE TITLE
output of prettier typescript parser is inconsistent with typescript compiler server

### ISSUE THREAD

**Issue by JLarky** [prettier/prettier#1931]
Here's simple example. FIle `test.ts`
```
function a( ) {   }
function b( ) {
}
```

output of prettier
```
function a() {}
function b() {}
```

output of [tsfmt](https://github.com/vvakame/typescript-formatter) or [typescript sublime](https://github.com/Microsoft/TypeScript-Sublime-Plugin)
```
function a() { }
function b() {
}
```

since tsfmt much more conservative with what it does to the code (for example it doesn't replace ' to " or vice versa), I expect being able to run tsfmt after prettier and see no changes as long as my tabs/spaces setting are the same. This is important for me since I use sublime plugin and I don't want prettier and sublime to fight over the formatting :)

p.s. settings I used in my real project
```
prettier --parser typescript --tab-width 4 --trailing-comma es5 --print-width=120  --write src/**.ts
```
`tsfmt.json`
```
{
    "newLineCharacter": "\n"
}
```

**Comment by JLarky** [comment]
In simplest terms prettier outputs empty blocks as `{}` and tsfmt as `{ }` and I would like to see option to emulate the `{ }` behavior in prettier

**Comment by vjeux** [comment]
Hey, i'm curious, why do you want to run both of them at the same time?

**Comment by JLarky** [comment]
@vjeux tsfmt using typescript's internal "prettier" :) and I use typescript plugin for sublime, which uses the same internal library. It won't be really good issue if I said "first, please install sublime and package manager, then install typescript plugin, configure it, and hit ctrl+t ctrl+f which will produce exact same result as if you run `tsfmt`

**Comment by vjeux** [comment]
What has been successful for JavaScript was to disable all the formatting-related rules from eslint. The only thing you have to do is to add a single line to your config and you're set: https://github.com/prettier/eslint-config-prettier.

I think it's more realistic to go that route rather than trying to match all the edge cases that TypeScript server does.

**Comment by vjeux** [comment]
So, to be clear, I think the next step is to make all the existing tooling aware of prettier so that you don't run into those kind of conflicts in the first place. TypeScript support just got released so this is rough right now, but I expect it to be better really soon.

**Comment by JLarky** [comment]
@vjeux makes sense. One other way of looking at it: can we get option in prettier for '{ }' instead of '{}'? :)

**Comment by azz** [comment]
Unlikely. Prettier only has options for the most controversial issues (tabs vs spaces, quote marks, etc). Prettier is after all an *opinionated* formatter.
