### ISSUE TITLE
TypeScript: Trailing commas inconsistent with tslint for enums

### ISSUE THREAD

**Issue by vsaarinen** [prettier/prettier#1932]
When the `--trailing-comma all` option has been set, the last trailing comma is removed from the following code:
```ts
enum LoadingStatus {
  LOADING,
  DONE,
}
```
If you're using tslint with the [trailing-comma](https://palantir.github.io/tslint/rules/trailing-comma/) rule enabled, this generates a linter error. If I want to keep trailing commas enabled in both prettier and tslint, there's currently no good solution (as far as I know) since the tslint rule can't be disabled for just enums.

Would it be possible to get prettier to keep the last trailing comma, or should I start talking to the tslint team?

Big :clap: for all the work around getting TypeScript support! So happy to be able to start using prettier.

**Comment by azz** [comment]
If you're formatting the code with prettier you can turn off that rule completely.

**Comment by SimenB** [comment]
It's a bug that it's removed though, isn't it?

**Comment by azz** [comment]
Yes.

I'm not 100% whether to insert the trailing comma in `--trailing-comma es5` mode, since it's not an ECMAScript feature. The PR enables it for both `es5` and `all`.

**Comment by vjeux** [comment]
I just published 1.4.2 with this fix.
