### ISSUE TITLE
Nested control statements and new line wrapping behavior

### ISSUE THREAD

**Issue by ndresx** [prettier/prettier#1939]
When a longer control statement exceeds the maximum `printWidth`, prettier wraps them by adding new lines at the beginning and the end, but doesn't apply the same behavior to nested statements like in the example below. It's not a bug, but might be worth a discussion.

Input:
```js
if(abc === 123 && (foo === 'nothing else than bar') && (bar === 'nothing else than foo' || foobar === 'reality without any doubt?' || shouldThisBeLikeThat() )) {}
```

Output:
```js
if (
  abc === 123 &&
  foo === "nothing else than bar" &&
  (bar === "nothing else than foo" ||
    foobar === "reality without any doubt?" ||
    shouldThisBeLikeThat())
) {
}
```

Output (2 times nested):
```js
if (
  abc === 123 &&
  foo === "nothing else than bar" &&
  (bar === "nothing else than foo" ||
    foobar === "reality without any doubt?" ||
    shouldThisBeLikeThat() ||
    (bar === "nothing else than foo" ||
      foobar === "reality without any doubt?" ||
      shouldThisBeLikeThat()))
) {
}
```

Alternative Output:
```js
if (
  abc === 123 &&
  foo === "nothing else than bar" &&
  (
    bar === "nothing else than foo" ||
    foobar === "reality without any doubt?" ||
    shouldThisBeLikeThat()
  )
) {
}
```

Alternative Output (2 times nested):
```js
if (
  abc === 123 &&
  foo === "nothing else than bar" &&
  (
    bar === "nothing else than foo" ||
    foobar === "reality without any doubt?" ||
    shouldThisBeLikeThat() ||
    (
      bar === "nothing else than foo" ||
      foobar === "reality without any doubt?" ||
      shouldThisBeLikeThat()
    )
  )
) {
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22if(abc%20%3D%3D%3D%20123%20%26%26%20(foo%20%3D%3D%3D%20'nothing%20else%20than%20bar')%20%26%26%20(bar%20%3D%3D%3D%20'nothing%20else%20than%20foo'%20%7C%7C%20foobar%20%3D%3D%3D%20'reality%20without%20any%20doubt%3F'%20%7C%7C%20shouldThisBeLikeThat()%20))%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by azz** [comment]
There hasn't been much demand for this style, and it would cause some pretty huge diffs if we changed it, so I'm closing this one.
