### ISSUE TITLE
No trailing comma for rest arguments

### ISSUE THREAD

**Issue by calebmer** [prettier/prettier#1945]
The following code:

```js
function reallyLongFunctionNameThatWillBreak(arg1, arg2, ...restArgumentWithAnotherReallyLongName) {}
```

Formats to:

```js
function reallyLongFunctionNameThatWillBreak(
  arg1,
  arg2,
  ...restArgumentWithAnotherReallyLongName
) {}
```

Even when trailing commas is set to `all`. I would expect that the rest argument gets a trailing comma.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20reallyLongFunctionNameThatWillBreak(arg1%2C%20arg2%2C%20...restArgumentWithAnotherReallyLongName)%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by simonkberg** [comment]
Trailing commas after rest parameters are invalid syntax.
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=const%20foo%20%3D%20(%0A%20%20bar%2C%0A%20%20...baz%2C%0A)%20%3D%3E%20%7B%0A%20%20%2F%2F%20Invalid%0A%7D

**Comment by k15a** [comment]
Exactly
