### ISSUE TITLE
Hyperscript formatting

### ISSUE THREAD

**Issue by dragosbulugean** [prettier/prettier#1949]
You try to create HTML with: 
[https://github.com/hyperhype/hyperscript](url) and [https://github.com/ohanhi/hyperscript-helpers](url)
Whenever your children number is smaller than 4, prettier inlines the whole thing making it very hard to read.
Example of current formatting:
```javascript
div(".resizers", div(".resize.nw"), div(".resize.n"), div(".resize.ne"))
```
instead of 
```javascript
div(
  ".resizers",
  div(".resize.nw"),
  div(".resize.n"),
  div(".resize.ne")
)
```
Probably other unreadable effects happen, for example when declaring attributes.

**Comment by lydell** [comment]
From #2123 by @tusharmath:

## Input

```ts
const t = h('div.account-summary', [
    h('div.account-summary__header',
      {
        on: {}
      },
      []
    )
  ])
```

## Output 
```ts
const t = h('div.account-summary', [
  h(
    'div.account-summary__header',
    {
      on: {}
    },
    []
  )
])

```

## Expected 
```ts
const t = h('div.account-summary', [
  h('div.account-summary__header',
    {
      on: {}
    },
    []
  )
])
```

[Sample](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20t%20%3D%20h('div.account-summary'%2C%20%5B%5Cn%20%20%20%20h('div.account-summary__header'%2C%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20on%3A%20%7B%7D%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%5B%5D%5Cn%20%20%20%20)%5Cn%20%20%5D)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
I'm afraid that we're not going to change prettier for this. We're trying as much as possible to be a general JavaScript printer and avoid special casing libraries that have unusual ways of printing code. In this case, while not optimal, the prettier output is reasonable.

**Comment by tusharmath** [comment]
I think a generic logic might work here —

Keep everything inline unless u have an array which could be split into multiple ones?

**Comment by tusharmath** [comment]
Prettier is kind of uglifying :P an otherwise properly indented code here.  Is there a way I can write a plugin for handling this specifically. Like when prettier sees an  `h` it handles in a special way?

Some pointer to where I can start would be greatly appreciated.

**Comment by RyanZim** [comment]
> Alternatively we could have a comment inside the code which prettier could understand ?

It's called `// prettier-ignore`. https://github.com/prettier/prettier#excluding-code-from-formatting

**Comment by tusharmath** [comment]
@RyanZim That will completely ignore. I don't want that :)

**Comment by makepost** [comment]
@vjeux Please reopen this or one of the referenced issues. Hyperscript is a feasible syntax for building virtual DOM, often used with libraries such as Inferno and Mithril. Worth thinking about [some general case](https://github.com/prettier/prettier/issues/2988#issuecomment-334955450) to handle this kind of nested functions better. Single-letter function names are rare. Code parser could understand seeing one as start of a Hyperscript construction. Maybe reusing JSX rules is possible, formatting looks quite alike.

**Comment by vjeux** [comment]
@makepost: you are free to keep commenting on the issue and propose solutions, the fact that an issue is closed doesn’t mean that it’s locked and won’t be re-evaluated in the future.

**Comment by benmerckx** [comment]
For anyone looking for a quick fix, I'm running the following on my js files after prettier (with `m` being mithril's hyperscript function):
```
perl -i -0777pe 's/\bm\(\s+/m(/gs'
```
This removes whitespace after `m(` and makes the code a lot more readable.
