### ISSUE TITLE
JSX with one long string attribute exceeds max line length

### ISSUE THREAD

**Issue by avaly** [prettier/prettier#1953]
Input:

```js
function App() {
  return (
    <Provider store={store}>
      <Router>
        <ResetPasswordPage
          path="/account/reset-password/:accountID/:recoveryCode"
        />
      </Router>
    </Provider>
  );
}
```

Prettier Output:

```js
function App() {
  return (
    <Provider store={store}>
      <Router>
        <ResetPasswordPage path="/account/reset-password/:accountID/:recoveryCode" />
      </Router>
    </Provider>
  );
}
```

Expected output should be equal to input.

**Comment by vjeux** [comment]
Hey, thanks for the bug report. This one is not obvious but it is actually intended. A lot of people actually disregard the line length when there's a jsx element with a single attribute which is a string literal. In many cases it looks better when not breaking and would likely go beyond 80 columns even if it did.
