### ISSUE TITLE
TypeScript imports not respecting maximum length

### ISSUE THREAD

**Issue by wayneashleyberry** [prettier/prettier#1954]
As far as I'm aware, the default maximum line length in Prettier is `80`. The following TypeScript code doesn't get reformatted at all - maybe because it can't fit into `80` characters at all?

**Input**

```ts
import { CollectionDashboardComponent } from "./components/collections/collection-dashboard/collection-dashboard.component";
```

**Output**

```ts
import { CollectionDashboardComponent } from "./components/collections/collection-dashboard/collection-dashboard.component";
```

**Expected**

Although the third line here is still longer than `80` characters, it's still closer.

```ts
import {
  CollectionDashboardComponent
} from "./components/collections/collection-dashboard/collection-dashboard.component";
```

---

Using prettier `1.4.2`

**Comment by azz** [comment]
This isn't specific to TypeScript.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%5Cn%20%20CollectionDashboardComponent%5Cn%7D%20from%20%5C%22.%2Fcomponents%2Fcollections%2Fcollection-dashboard%2Fcollection-dashboard.component%5C%22%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Comment by wayneashleyberry** [comment]
That makes sense @vjeux, and I had a feeling that this behaviour was intentional. I was just surprised getting linting errors and seemingly inconsistent formatting :) Thanks for the response.

**Comment by OliverJAsh** [comment]
Just ran into this. ESLint will complain because the line exceeds the max len. Given this is by design, the only workarounds I can think of are:

- Disable ESLint rule for that line, e.g. `// eslint-disable-line max-len`
- Disable prettier for that line e.g. `// prettier-ignore`

**Comment by vjeux** [comment]
You probably want to disable max-len if you are using prettier

**Comment by yfr** [comment]
I would suggest using `"max-len": [2, {"code": 80, "ignorePattern": "^import\\W.*"}]` as `max-len` setting then

**Comment by aboyton** [comment]
Prettier only uses the maximum length as a guide, see say #1966. I'd strongly encourage you just turn off `max-len` entirely if you'r using prettier. It's also worth noting that you can't do this in TSLint palantir/tslint#1123.
