### ISSUE TITLE
Comment in chained method return statement adds parenthesis

### ISSUE THREAD

**Issue by dotlouis** [prettier/prettier#1959]
Hi,
first of all thank you for the amazing work !

I ran prettier on my entire codebase and found only one thing that probably should not behave as it is.

[demo](https://prettier.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%20environment%20as%20ENV%20%7D%20from%20'..%2F..%2Fenvironments%2Fenvironment'%3B%5Cn%5Cn%40Injectable()%5Cnexport%20class%20ShopService%20%7B%5Cn%5Cn%20%20%20%20constructor(protected%20firebase%3A%20AngularFireDatabase)%7B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20getShop(arg)%20%7B%5Cn%20%20%20%20%20%20%20%20return%20this.firebase.object(%60%2Fshops%2F%24%7BshopLocation.shop%7D%60)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20keep%20distance%20info%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.first((shop%3A%20ShopQueryResult%2C%20index%3A%20number%2C%20source%3A%20Observable%3CShopQueryResult%3E)%3A%20any%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20add%20distance%20to%20result%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20s%20%3D%20shop%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20s.distance%20%3D%20shopLocation.distance%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20s%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Input**
```TS
    getShop(arg) {
        return this.firebase.object(`/shops/${shopLocation.shop}`)
            // keep distance info
            .first((shop: ShopQueryResult, index: number, source: Observable<ShopQueryResult>): any => {
                // add distance to result
                const s = shop;
                s.distance = shopLocation.distance;
                return s;
            });
    }
```

**Output**
```TS
getShop(arg) {
    return ( // <= why is this in parenthesis ?
      this.firebase.object(`/shops/${shopLocation.shop}`)// keep distance info
      .first(
        (
          shop: ShopQueryResult,
          index: number,
          source: Observable<ShopQueryResult>,
        ): any => {
          // add distance to result
          const s = shop;
          s.distance = shopLocation.distance;
          return s;
        },
      )
    );
  }
```

When I remove the `// keep distance info` the output is fine without any parenthesis
Any ideas ?
Cheers

**Comment by vjeux** [comment]
If there's a comment before the expression returned, we're going to put it in the next line meaning that we need to put () around return otherwise the automatic semi colon insertion is going to kick in and it's going to execute as `return;`.

But, our detection logic doesn't quite work here and should be looked into.

**Comment by vjeux** [comment]
I just published 1.4.3 which fixes it. Thanks for reporting it!
