### ISSUE TITLE
Assignment not respecting line length limit

### ISSUE THREAD

**Issue by aboyton** [prettier/prettier#1966]
Thanks for all the great work with prettier, especially TypeScript support.

One thing I am noticing is that long assignments exceed the maximum line length limit. While I realise that you can't always fit everything under 80 characters, and sometimes we've decided not to (say with imports) I do feel that it would be good to make assignments/declarations fit into the maximum line length if possible (or just easily).

For example:

```js
const aVeryLongNameThatGoesOnAndOn = this.someOtherObject.someOtherNestedObject.someLongFunctionName();
```
and
```js
this.someObject.someOtherNestedObject = this.someOtherObject.whyNotNestAnotherOne.someLongFunctionName();
```
would be better (prettier) to break this onto two lines like
```js
const aVeryLongNameThatGoesOnAndOn =
  this.someOtherObject.someOtherNestedObject.someLongFunctionName();
```
and
```js
this.someObject.someOtherNestedObject =
  this.someOtherObject.whyNotNestAnotherOne.someLongFunctionName();
```
respectively.

Similar comments have been made regarding template strings (say https://github.com/prettier/prettier/issues/1893#issuecomment-305965489 and #1894), but personally I think it would be nicer to fix the general case.

**Comment by ianobermiller** [comment]
Worth noting that it also happens with multiple assignment expressions together:

```js
this.isaverylongmethodexpression.withmultiplelevels = this.isanotherverylongexpression.thatisalsoassigned = 0;
```

**Comment by azz** [comment]
Closing this one, track #2482 for updates.
