### ISSUE TITLE
Support autoformatting JSON too

### ISSUE THREAD

**Issue by Wilfred** [prettier/prettier#1973]
I couldn't see any existing issues for this, but is it possible to autoformat JSON with prettier? If not, would you be interested in adding this feature?

**Comment by josephfrazier** [comment]
There was a bit of prior discussion on this at https://github.com/prettier/prettier/issues/322.

A similar issue concerns aligning object property literals in JS (https://github.com/prettier/prettier/issues/1622), which was implemented in [`prettier-miscellaneous`](https://github.com/arijs/prettier-miscellaneous/) behind the [`--align-object-properties`](https://github.com/arijs/prettier-miscellaneous/pull/7) option.

Another option is to use [`prettier_d`](https://github.com/josephfrazier/prettier_d), which offers a `--json` option to both sort and align keys in JSON files (but not JS object literals).

**Comment by vjeux** [comment]
Now that we have CSS and are going to have TypeScript, I think it makes sense to add JSON to the mix.
