### ISSUE TITLE
Force initial indent in arrow function body if parameter list is multiline

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#1975]
For example
```es6
const getDefaultSpaceName = (
  platform: SomePlatformTypeType,
  featureType: SomePlacementFeatureTypeType,
): string => platform + ' ' + featureType;
```
I feel like humans would indent the function body unless it's the simple
```es6
x => f(x)
// or
(x: A, y: b) => f(x, y)
```
which fit on one line completely, so prettier should output:
```es6
const getDefaultSpaceName = (
  platform: SomePlatformTypeType,
  featureType: SomePlacementFeatureTypeType,
): string =>
  platform + ' ' + featureType;
```

**Comment by vjeux** [comment]
Template literals are tricky, we don't know what kind of indentation they are going to have inside so if you put them on the same line, we're going to put them on the same line, otherwise on the next line.

But, in this case, there are no `\n` inside of the template literal so it should be treated as a normal value.

**Comment by xixixao** [comment]
@vjeux Edited original post to make it obvious this is unrelated to template literals. It's not a bug either, more of a feature request.

**Comment by vjeux** [comment]
Ohh, I see. So we go to the next line if the arguments break. If it fits in one line, we keep it in one line.

If we remove the group around the body, it should break if the arguments break which is probably what you have in mind.

If you want to try it out, I'd be curious to see how it looks in practice.

**Comment by Tibfib** [comment]
I actually prefer the look of 

```javascript
const getDefaultSpaceName = (
  platform: SomePlatformTypeType,
  featureType: SomePlacementFeatureTypeType,
): string => platform + ' ' + featureType;
```
to 
```javascript
const getDefaultSpaceName = (
  platform: SomePlatformTypeType,
  featureType: SomePlacementFeatureTypeType,
): string =>
  platform + ' ' + featureType;
```
I'm not one of those humans who would indent the function body 😄 . But perhaps the majority are? Just thought I'd put this out there in case others feel the same as me.

**Comment by azz** [comment]
Might be just me but I find both those examples a bit hard to read. I'd almost always write:

```ts
const getDefaultSpaceName = (
  platform: SomePlatformTypeType,
  featureType: SomePlacementFeatureTypeType,
): string => {
  return platform + ' ' + featureType;
}
```

or remove the obvious `string` return type and write:

```ts
const getDefaultSpaceName = (
  platform: SomePlatformTypeType,
  featureType: SomePlacementFeatureTypeType,
) => platform + ' ' + featureType;
```

**Comment by vjeux** [comment]
Going to close this as it's not clear that it would be a win.
