### ISSUE TITLE
TypeScript: Comment above interface function property splits arguments across multiple lines

### ISSUE THREAD

**Issue by mafredri** [prettier/prettier#1976]
**Input:**

```typescript
interface ScreenObject {
	// I make things weird.
	at(point: Point): Screen | undefined;
}
```

**Output:**

```typescript
interface ScreenObject {
	// I make things weird.
	at(
		point: Point
	): Screen | undefined;
}
```

**Expected:**

No change from input.

Problem seems to go away if e.g. a regular property appears before the function, like this:

```typescript
interface ScreenObject {
	// I make things weird.
  	prop: string;
	at(point: Point): Screen | undefined;
}
```

Reproduction link can be found [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22interface%20ScreenObject%20%7B%5Cn%5Ct%2F%2F%20I%20make%20things%20weird.%5Cn%5Ctat(point%3A%20Point)%3A%20Screen%20%7C%20undefined%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%7D%7D).

**Comment by vjeux** [comment]
I just published 1.4.3 which fixes it. Thanks for reporting it!
