### ISSUE TITLE
How to ignore one or more folders/files in CLI?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#1977]
I tried this on CLI and it works.

`prettier --write --use-tabs  /Users/jitendravyas/app-v3/styles/**/*.scss`

But I want to ignore some folders like

`/Users/jitendravyas/app-v3/styles/vendor/**/*.scss`
`/Users/jitendravyas/app-v3/styles/sprite-generated*.scss`

How to do this?

**Comment by lydell** [comment]
This should do the trick:

```
$ tree styles
styles
├── one
│   └── one.scss
├── sprite-generated-1.scss
├── sprite-generated-2.scss
├── sprite-generated.scss
├── top.scss
├── two
│   └── two.scss
└── vendor
    ├── bootstrap
    │   └── bootstrap.scss
    └── vendor.scss

4 directories, 8 files

$ prettier --write --use-tabs "styles/{!(sprite-generated*),!(vendor)/**/*}.scss"
styles/one/one.scss 59ms
styles/top.scss 1ms
styles/two/two.scss 0ms
```

**Comment by jitendravyas** [comment]
Thanks for the reply. 

Just a suggestion

It could be useful to have an ignore file for prettier or use `.stylelintignore`

**Comment by lydell** [comment]
My example above uses relative paths.

I also find an ignore file very useful! So I use Prettier inside of ESLint using [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier). Then I can piggyback on `.eslintignore`. It woks really good!

**Comment by jitendravyas** [comment]
I tried it but I guess Prettier CLI doesn't bother whether `.eslintignore` is present or not

**Comment by lydell** [comment]
Correct, Prettier CLI doesn’t care about .eslintignore. I meant using Prettier inside of `eslint --fix`.

**Comment by jitendravyas** [comment]
@lydell this command is not working 

`prettier --write --use-tabs "styles/{!(vendor)/**/*}.scss"`

**Comment by lydell** [comment]
@jitendravyas I guess this one should work:

```
prettier --write --use-tabs "styles/!(vendor)/**/*.scss"
```

I guess node-glob treats `{...}` without commas as literal `{` and `}` characters, and I doubt you have an files with `{` or `}` in their names ;)

**Comment by jitendravyas** [comment]
No even this is not working. I want to ignore only /vendor folder which is in styles/ folder

**Comment by lydell** [comment]
Globs are so much fun (not).

**Comment by jitendravyas** [comment]
@lydell I tried using  eslint-plugin-prettier too  https://github.com/prettier/eslint-plugin-prettier/issues/29

**Comment by jitendravyas** [comment]
Because of Prettier do not have an ignore file and I'm not able to solve how to ignore files I'm not able to use Prettier to add in the hook https://github.com/prettier/prettier#1-lint-staged

**Comment by Wilfred** [comment]
Note that you can specify exclusions in a separate pattern, so something like this should work:

```
prettier --write --use-tabs "styles/**/*.scss" "!styles/vendor/**"
```

**Comment by hckrmoon** [comment]
@Wilfred awesome !
