### ISSUE TITLE
Better handle multine of functions with array as argument

### ISSUE THREAD

**Issue by FezVrasta** [prettier/prettier#1978]
```
PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
```
In case this row needs to be split in multiple lines, Prettier will output this:

```
PropTypes.oneOfType([PropTypes.string, PropTypes.number])
  .isRequired,
```

Instead I think it would look better as:
```
PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.number,
]).isRequired,
```

[demo](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20const%20fooobar%20%3D%20%7B%5Cn%20%20%20%20foooobar%3A%20%7B%5Cn%20%20%20%20%20%20cofveve%3A%20%7B%5Cn%20%20%20%20%20%20%5Ctblabla%3A%20PropTypes.shape(%7B%5Cn%20%20%20%20%5Ct%20%20id%3A%20PropTypes.oneOfType(%5BPropTypes.string%2C%20PropTypes.number%5D).isRequired%2C%5Cn%20%20%5Ct%5Ct%7D)%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A70%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
Looks like you ran into some edge case

At 56 it does

```js
PropTypes.oneOfType([
	PropTypes.string,
	PropTypes.number
]).isRequired;
```


https://prettier.github.io/prettier/#%7B%22content%22%3A%22PropTypes.oneOfType(%5BPropTypes.string%2C%20PropTypes.number%5D).isRequired%22%2C%22options%22%3A%7B%22printWidth%22%3A56%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

Between 68 and 57 it does

```js
PropTypes.oneOfType([PropTypes.string, PropTypes.number])
	.isRequired;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22PropTypes.oneOfType(%5BPropTypes.string%2C%20PropTypes.number%5D).isRequired%22%2C%22options%22%3A%7B%22printWidth%22%3A57%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by azz** [comment]
@vjeux It may look a little odd but I don't think this is a bug, right?

**Comment by vjeux** [comment]
I treat as bugs all the things I want to be fixed. We should be breaking inside of [] and not like it is :)

**Comment by j-f1** [comment]
This looks fine to me 🤷‍♂️
