### ISSUE TITLE
Mention TypeScript in repo description

### ISSUE THREAD

**Issue by shamrin** [prettier/prettier#1998]
I've nearly ignored `prettier` when I was looking for gofmt-like TypeScript prettifier.

What do you think about changing the current "Prettier is an opinionated JavaScript formatter" into something like this?

<img width="743" alt="screen shot 2017-06-06 at 12 47 24" src="https://cloud.githubusercontent.com/assets/510678/26823449/587dcc00-4ab6-11e7-9765-b5b3d033bc14.png">

**Comment by azz** [comment]
README states:

> Prettier is an opinionated code formatter.

Prettier supports JS, TS, CSS, SCSS, Less, and other languages are in the works.

**Comment by vjeux** [comment]
Fixed! thanks :)

**Comment by shamrin** [comment]
Repo description is better now, thank you!

But the first sentence in the README could still be better in my opinion :) It currently states:

> Prettier is an opinionated code formatter inspired by [refmt](https://facebook.github.io/reason/tools.html) with advanced support for language features from:
> * JavaScript, including [ES2017](https://github.com/tc39/proposals/blob/master/finished-proposals.md)
> * [JSX](https://facebook.github.io/jsx/)
> * [Flow](https://flow.org/)
> * [TypeScript](https://www.typescriptlang.org/)
> * CSS, [LESS](http://lesscss.org/), and [SCSS](http://sass-lang.com)

I find it difficult to read. Especially when one is quickly skimming through the project description. E.g., "with advanced support for language features from" is quite a mouthful.

I've tried to make it simpler here:

> Prettier is an opinionated code formatter for:
> * JavaScript, including [ES2017](https://github.com/tc39/proposals/blob/master/finished-proposals.md)
> * [JSX](https://facebook.github.io/jsx/)
> * [Flow](https://flow.org/)
> * [TypeScript](https://www.typescriptlang.org/)
> * CSS, [LESS](http://lesscss.org/), and [SCSS](http://sass-lang.com).
>
> Prettier is inspired by [refmt](https://facebook.github.io/reason/tools.html).
