### ISSUE TITLE
TypeScript: `--list-different` always detects interfaces as different

### ISSUE THREAD

**Issue by evanw** [prettier/prettier#2004]
Create a file called foo.ts:

```ts
interface Foo {
  foo: {};
}
```

Run the following:

```sh
$ yarn add prettier
$ yarn run prettier -- --write foo.ts
$ yarn run prettier -- --list-different foo.ts
```

Unexpected: foo.ts shows up as different despite having just been overwritten. This prevents the use of prettier in pre-commit hooks for TypeScript. This seems especially strange to me because I would intuitively expect `--list-different` to be comparing the raw contents of the file.

**Comment by evanw** [comment]
I tracked it down to this:

```js
const formatted = format(text, normalizeOptions(opts));
return formatted === text;
```

The problem is a semicolon:

```js
"interface Foo {\n  foo: {};\n}\n" // text
"interface Foo {\n  foo: {}\n}\n"  // formatted
```

**Comment by k15a** [comment]
Is this a duplicate of #1971?

**Comment by evanw** [comment]
Yeah it looks like this is the same issue. Running this works fine:

```sh
$ yarn run prettier -- --list-different foo.ts --parser typescript
```
