### ISSUE TITLE
prettier-ignore being ignored in .less

### ISSUE THREAD

**Issue by jfranty** [prettier/prettier#2007]
```js
$ cat foo.less
// prettier-ignore
@blue:  blue;
@black: darkgray;

$ ./node_modules/.bin/prettier foo.less
// prettier-ignore
@blue: blue;
@black: darkgray;

$ ./node_modules/.bin/prettier --version
1.4.2
```

**Comment by vjeux** [comment]
Oh yeah... We don't have it implemented there! We absolutely should :)

**Comment by ndresx** [comment]
@vjeux Guess that would be something nice to start with? If so I would like to give this a try in the next few days unless @jfranty wants to do it ofc!

**Comment by vjeux** [comment]
@ndresx please be my guest :)
