### ISSUE TITLE
Please release a new patch version

### ISSUE THREAD

**Issue by cvbuelow** [prettier/prettier#2019]
Between v1.4.0 and v1.4.1 there was a breaking change for Node@4 (#1986) that has since been fixed. However we need v1.4.3 to be published so we can use this fix. All our jenkins jobs have been failing the past couple days for our 50+ repos. Thank you 😃

**Comment by vjeux** [comment]
I'll look into it. Thanks for telling me about it.

**Comment by cvbuelow** [comment]
👍

**Comment by vjeux** [comment]
Shipped!
