### ISSUE TITLE
Typescript: SyntaxError: private is a reserved word in strict mode

### ISSUE THREAD

**Issue by igghera** [prettier/prettier#2020]
First of all, thanks for all the hard work you guys are doing, the typescript support makes me and my team so happy, and saves us so much time!

I have updated my `prettier-atom` plugin and started using it on Typescript files, but I keep getting that SyntaxError in the title when I have a constructor like this:

```
constructor(private router: Router) {
  ...
}
```

same thing happens when I use the `private` keyword on an instance variable or a method like this:

```
class Foo {
  private bar: string;  <-- SyntaxError

  private doSomething() {    <-- SyntaxError
    ...
  }
}
```

as soon as I remove that `private` keyword, prettier-atom is happy and formats my code as expected. 

Am I the only one who ran into this issue? Is it something I'm doing wrong? Can it be something related to the prettier-atom package?

**Comment by azz** [comment]
Sounds like it's using the Babylon parser. From a quick check, it looks like prettier-atom isn't passing either `parser: "typescript"` or `filepath: "foo.ts"`. You should raise this issue [over there] (https://github.com/prettier/prettier-atom/issues).

**Comment by igghera** [comment]
Will do, thanks azz!
