### ISSUE TITLE
Off by one on line length/indenting JSX props

### ISSUE THREAD

**Issue by tgriesser** [prettier/prettier#2027]
[Example here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20A%20%3D%20%5B%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20CustomComponent%3A%20()%20%3D%3E%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3CEmployeeCheckbox%20rowData%3D%7BrowData%7D%20selectEmployee%3D%7BselectEmployee%7D%20selectedEmployees%3D%7BselectedEmployees%7D%20%2F%3E%5Cn%20%20%20%20%7D%2C%5Cn%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

The output of the `EmployeeCheckbox` component line reaches to 121 characters (should limit 120). If you add a character anywhere in the props, the component will wrap. Started to try to fix this, but haven't had the time to dive into how everything in prettier works yet.

**Comment by vjeux** [comment]
Doesn't seem off by one to me. Look, the `|` is right after the last character.

![image](https://user-images.githubusercontent.com/197597/26892088-0069b2c0-4b6c-11e7-9485-89914eb88960.png)

**Comment by vjeux** [comment]
![image](https://user-images.githubusercontent.com/197597/26892122-1f9f20f8-4b6c-11e7-9210-43b4e65efc4a.png)

**Comment by SimenB** [comment]
`'            <EmployeeCheckbox rowData={rowData} selectEmployee={selectEmployee} selectedEmployees={selectedEmployees} />'.length` also say 120

**Comment by tgriesser** [comment]
Oops, wasn't looking close enough here, the issue I was seeing was due to a script running `eslint --fix` adding a semicolon after prettier ran and pushing it over the line length! Thanks for the quick reply!
