### ISSUE TITLE
How to format a codebase with a large branch?

### ISSUE THREAD

**Issue by ccorcos** [prettier/prettier#2030]
I have a typescript codebase that I'm eager to format with Prettier. However we have a large branch that's based on master right now. Its not going to get merged anytime soon and we keep rebasing to keep it up to date.

Any ideas how I could format master and have it propagate through this other branch without nasty conflicts?

**Comment by ccorcos** [comment]
Basically what I want to do is `git rebase -i master`, select `edit` for all commits, run prettier on each commit, and continue. I think that should work. Not sure how to automate this though.

**Comment by vjeux** [comment]
If you run (and enforce) prettier on both master and the branch, you shouldn't have merge conflicts. It may even reduce the number of conflicts as the style will be consistent.

**Comment by ccorcos** [comment]
Ah yes. But then we're merging master into our dev branch and not rebasing... I feel like that could be an issue at some point

**Comment by ccorcos** [comment]
For others in a similar situation, here's what I did. First off `dev` and `master` need to be up to date with each other, either merged or rebased.

```
npm install -g prettier

git checkout master
prettier --use-tabs --tab-width 2 --no-semi --trailing-comma es5 --parser typescript --write './src/**/*.ts*'
git add .
git commit -m "Prettier"
git push

git checkout dev
prettier --use-tabs --tab-width 2 --no-semi --trailing-comma es5 --parser typescript --write './src/**/*.ts*'
git add .
git commit -m "Prettier dev"
git merge -Xours master
git push
```
