### ISSUE TITLE
In TypeScript, long interface/extends lines don't break

### ISSUE THREAD

**Issue by astashov** [prettier/prettier#2043]
Thanks for finally adding TypeScript support. I tried on our project, and the only outstanding issue that it doesn't break long `interface`/`extends` lines, and the TSLint linter complains about them. I.e.:

Input:

```ts
interface AVeryLongAndBoringInterfaceName {
  a: string;
}

interface AnotherVeryLongAndBoringInterfaceName {
  b: string;
}

export interface ThirdVeryLongAndBoringInterfaceName extends AVeryLongAndBoringInterfaceName, AnotherVeryLongAndBoringInterfaceName {
  c: string;
}
```

I run it

```bash
$ ./node_modules/prettier/bin/prettier.js --no-bracket-spacing --print-width 120 --write src/foo.ts 
```

Output is the same

Expected output: I'd expect the

```ts
export interface ThirdVeryLongAndBoringInterfaceName extends AVeryLongAndBoringInterfaceName, AnotherVeryLongAndBoringInterfaceName {
```

line to be broken somehow so it wouldn't exceed 120 chars.

**Comment by vjeux** [comment]
Wow, I had no idea we could extend multiple things. Yeah, we can print it better
