### ISSUE TITLE
JSDoc comments 

### ISSUE THREAD

**Issue by rryter** [prettier/prettier#2044]
JS-Doc comments are not being indented correctly:

![formatting-issue](https://user-images.githubusercontent.com/798709/26916181-8d93dadc-4c29-11e7-8b16-873ee1597270.png)

`/**` and the function have been indented correctly. However the body of the comment and the closing `*/` stayed at their original position.

**Comment by vjeux** [comment]
We don't re-indent comments currently. https://github.com/prettier/prettier/issues/648 is tracking it. This is something we want to do in prettier at some point. Right now, you've got to do it manually.

**Comment by rryter** [comment]
Sorry, didn't catch that issue. Thanks a lot!
