### ISSUE TITLE
Arrow function line did not break when exceeded max line length

### ISSUE THREAD

**Issue by dzhytomyrsky** [prettier/prettier#2045]
Hello! I'm using prettier + prettier-eslint +  prettier-eslint-CLI in my project, there is an issue with line breaking in arrow functions like this: 

` actions.createNewPassword = (password) => (dispatch) => dispatch(creators.createNewPassword(password));`

prettier does not break the line and deletes all my line breaks when I add it. The npm script I use is next: 

`"format": "prettier-eslint --list-different 'development/**/*.js'; prettier-eslint --write 'development/**/*.js'"`

the line is breaking, when I set --print-width to 98, but it does not, when --print-width option set to 100, while the string is 104 signs length.

please help me to figure out how to fix this.

++ 

tested with different --print-width properties, the issue appeared not only with arrow function, in general the line length is unexpectedly longer than --print-width parameter.

**Comment by vjeux** [comment]
Hey, thanks for the report.

```js
'actions.createNewPassword = password => dispatch => dispatch(creators.createNewPassword(password));'.length
> 99
```

So, if you have --print-width 98, it's going to break, if you have more it is not.

My best guess is that you are using eslint --fix and force `()` around single arguments. eslint rules do not take into account the line length limit, they just add characters around. This is one of the big reason why we created prettier in the first place.

My two suggestions are:
1) Do not enable this lint rule and accept the parenthesis-less arrow functions
2) Accept that if you have it, then the line limit will not be respected.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22actions.createNewPassword%20%3D%20(password)%20%3D%3E%20(dispatch)%20%3D%3E%20dispatch(creators.createNewPassword(password))%3B%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A99%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by dzhytomyrsky** [comment]
It looks like we should disable max-len rule in .eslintrc, set --print-width to 100 and be ready to see lines which exceeds 100.
