### ISSUE TITLE
Template strings when accessing object via the array notation

### ISSUE THREAD

**Issue by kennydee** [prettier/prettier#2046]
Hi,

Since the 1.4 version of Prettier, something strange is done on object accessed via array notation in ES6 template strings : 

This line valid in prettier 1.3 (to concat firstname and the first letter of the lastname): 
```javascript
// before prettier 1.4
const lineTxt = `${players[composition.team1Defense].firstName} ${players[composition.team1Defense].lastName[0]}. `;
```
is transformed via prettier 1.4 to : 

```javascript
// after prettier 1.4
const lineTxt = `${players[composition.team1Defense].firstName} ${players[
  composition.team1Defense
].lastName[0]}. `;
```
See live on the prettier website : [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20lineTxt%20%3D%20%60%24%7Bplayers%5Bcomposition.team1Defense%5D.firstName%7D%20%24%7Bplayers%5Bcomposition.team1Defense%5D.lastName%5B0%5D%7D.%20%60%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

Maybe this behavior is intended ? 
Or it will be better to do nothing, or split line between variables ?
```javascript
const lineTxt = `${players[composition.team1Defense].firstName}
 ${players[composition.team1Defense].lastName[0]}. `;
```

Thanks

**Comment by bakkot** [comment]
Splitting between the two expressions isn't valid; that changes the contents of `lineText` (by adding a linebreak). Unfortunately I can't think of any actually good way to format this particular code.

**Comment by SteinarArnason** [comment]
this jumped out at me as well, how about formatting it like:

```js
const lineTxt = `${players[
  composition.team1Defense
].firstName} ${players[
  composition.team1Defense
].lastName[0]}. `;
```

This way it's consistent.

**Comment by kennydee** [comment]
@bakkot you're right about the line breaks.

@SteinarArnason i think both are better than what is done actually :)
Also thanks for the duplicate issue which is almost similar.

One question is why, in prettier 1.3 this line was valid, and why prettier 1.4 introduce this "line splitting" in it ?

Thanks

**Comment by vjeux** [comment]
Before 1.4, we removed all the soft `\n` from the expression. It worked well for those, but people wrote bigger expressions and it would completely mess things up.

#1662, #1626, #821 and #1183 are some examples.

**Comment by kennydee** [comment]
i think this one is also a duplicate of #1893

**Comment by azz** [comment]
Merging into #1893
