### ISSUE TITLE
Typescript: failes to parse JSX <object /> tag

### ISSUE THREAD

**Issue by mkusher** [prettier/prettier#2049]
Using typescript parser it failed to parse code like:
```typescript
function Render() {
      return (
        <object
            className={ st.pdf }
            data={ document }
          />
      );
  }
```

[Demo link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Cnfunction%20Render()%20%7B%5Cn%20%20%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%3Cobject%5Cn%20%20%20%20%20%20%20%20%20%20%20%20className%3D%7B%20st.pdf%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20data%3D%7B%20document%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%20%20)%3B%5Cn%20%20%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by mkusher** [comment]
Simple workaround for such case can be:
```
function Render() {
      const Object = "object"
      return (
        <Object />
      );
  }
```

**Comment by frederickfogerty** [comment]
Or just use `// prettier-ignore` to unblock yourself

```js
function Render() {
	// prettier-ignore
      return (
        <object
            className={ st.pdf }
            data={ document }
          />
      );
  }
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Cnfunction%20Render()%20%7B%5Cn%5Ct%2F%2F%20prettier-ignore%5Cn%20%20%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%3Cobject%5Cn%20%20%20%20%20%20%20%20%20%20%20%20className%3D%7B%20st.pdf%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20data%3D%7B%20document%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%20%20)%3B%5Cn%20%20%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
