### ISSUE TITLE
Import type is not respecting printWidth

### ISSUE THREAD

**Issue by michalkvasnicak** [prettier/prettier#2050]
After upgrading from `1.3.1` to `1.4.4` `printWidth` for flow `import { type }` stopped to work correctly.

Example:

```js
// previously in 1.3.1 it was wrapping to next line
import transformRouterContext, { 
  type TransformedContextRouter 
} from '../../helpers/transformRouterContext';

// in 1.4.4 it results in line with 109 characters
import transformRouterContext, { type TransformedContextRouter } from '../../helpers/transformRouterContext';
```

Eslint configuration:

```js
module.exports = {
  "env": {
    "browser": true,
    "jest": true,
    "node": true,
  },
  "extends": ["airbnb", "plugin:flowtype/recommended", "prettier"],
  "plugins": ["flowtype", "prettier"],
  "globals": {
    "LC_API": true,
  },
  "parser": "babel-eslint",
  "rules": {
    "import/first": "off",
    "import/no-named-as-default": "off",
    "import/no-named-as-default-member": "off",
    "import/no-extraneous-dependencies": "off",
    "import/prefer-default-export": "off",
    "no-duplicate-imports": "off",
    "no-underscore-dangle": "off",
    "react/require-default-props": "off",
    "flowtype/generic-spacing": "off",
    "flowtype/space-after-type-colon": "off",
    "prettier/prettier": [
      "error",
      {
        "trailingComma": "all",
        "singleQuote": true,
        "printWidth": 100,
      },
    ],
    "react/jsx-filename-extension": "off",
  },
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true,
    },
  },
}
```

**Comment by vjeux** [comment]
Thanks, this is a bug indeed!

It should only keep it in a single line if there's a single element on the left. In this case you have two, so we should break. We'll fix it.

**Comment by ivanvoznyakovsky** [comment]
this issue is back again. prettier version 1.13.7.
typescript file has the following import statement
```js
import {IDXActivityTrackerEditModalBindings}
  from '../activity-tracker-edit-modal/activity-tracker-edit-modal.component';
```
which gets formatted into a single line with of length 121 when `printWidth` is 80

`.prettierrc` is
```json
{
  "parser": "typescript",
  "singleQuote": true,
  "printWidth": 80,
  "bracketSpacing": false
}
```

**Comment by suchipi** [comment]
@ivanvoznyakovsky this is intended behavior, and is happening because you only have one item in your import statement. See https://github.com/prettier/prettier/issues/1954

**Comment by ivanvoznyakovsky** [comment]
I see but this is really confusing. doesn't this break the main goal of prettier to make code formatting consistent and to follow a defined set of rules? there's a rule that max line length is 80 characters. but 💥 there's an exception for `import` statements. 
why? where does it come from? is it mentioned in the rule description? no.

**Comment by j-f1** [comment]
@ivanvoznyakovsky Of which rule description do you speak?

**Comment by suchipi** [comment]
@ivanvoznyakovsky the explanation is here: https://github.com/prettier/prettier/issues/1954#issuecomment-306067705

**Comment by ivanvoznyakovsky** [comment]
@j-f1 it's about `printWidth` rule. No mentions of any exceptions or special applications.

@suchipi thx for pointing that out but I still think that this kind of info should be in rule description. one should note go google why this happens and eventually find it in an issue comment.

**Comment by lydell** [comment]
https://prettier.io/docs/en/rationale.html#imports
