### ISSUE TITLE
Suggestion: Keep the JSX Element's Key on the Same Line as Element Name

### ISSUE THREAD

**Issue by joewood** [prettier/prettier#2051]
One effective style that I see a lot is to treat the JSX `key` attribute as a special case as it acts as a unique index in a list of elements. For this reason it makes sense to move it to the start of the attribute list and keep it on the same line as the element name.  For example:
```JSX
<div>
    <Element
        max="auto"
        foo={data}
        key="element1"
        title="name1"
        showAxis={true}
        showTitle={false}
    />
    <Element
        max="auto"
        foo={data}
        key="element2"
        title="name2"
        showAxis={true}
        showTitle={false}
    />
</div>
```

Would become:
```JSX
<div>
    <Element key="element1"
        max="auto"
        foo={data}
        title="name1"
        showAxis={true}
        showTitle={false}
    />
    <Element key="element2"
        max="auto"
        foo={data}
        title="name2"
        showAxis={true}
        showTitle={false}
    />
</div>
```
This also encourages the use of `key` attributes and makes it more obvious when they're missing. I admit, reordering attributes may have some processing side effects (i.e. mutating code in attribute value), but I'm not sure if that's something that should be relied upon anyway.

**Comment by k15a** [comment]
We don't really want to reorder attributes or alter the AST. Therefore I don't think we will change this behavior at all.

**Comment by joewood** [comment]
What if the key attribute was already the first attribute, could it then be promoted to the same line to improve readability?

**Comment by k15a** [comment]
That could be possible. Let's see what others have to say about this.

**Comment by vjeux** [comment]
This is actually the first time I hear about someone doing something like this. I'm sorry but at this point, we're not going to do any changes to the way we print JSX attributes. You are going to have to accept that prettier moves it to another line or not use prettier I'm afraid.

Thanks for raising this issue though!
