### ISSUE TITLE
typescript: do not break paratemerized type

### ISSUE THREAD

**Issue by victornoel** [prettier/prettier#2052]
Hi,

I have the following code:
```ts
export interface IContainersTable extends IContainersCommon, JsMap<IContainerRow> {}
```

and applying prettier gives me this:
```ts
export interface IContainersTable extends IContainersCommon, JsMap<
  IContainerRow
> {}
```

I think that prettier should keep `JsMap<IContainerRow>` as one element and break the line before `JsMap`.

**Comment by vjeux** [comment]
This is the same issue as https://github.com/prettier/prettier/issues/2043, I'm going to close this one. Thanks for the report. It should be easy to fix.
