### ISSUE TITLE
Put @else on the same line as }

### ISSUE THREAD

**Issue by dzhytomyrsky** [prettier/prettier#2053]
Hello, guys! I am really thankful to you for prettier, it is really cool! It is nice that now prettier supports scss, but I faced a situation, where I need to prittify my scss using rules from .scss-lint.yml. Is it possible and if not, please consider this as a request for such possibility.

**Comment by vjeux** [comment]
We are not going to read from those rules and the best thing to do is to disable the ones that conflict with prettier.

But, it would be useful if you could tell us which ones are in conflict with prettier so that we can discuss whether it is worth improving prettier to follow them.

**Comment by dzhytomyrsky** [comment]
For example I need scss-lint "SingleLinePerSelector" to work properly.

**Comment by vjeux** [comment]
We just merged https://github.com/prettier/prettier/pull/2047 which does it. Any other issue you are facing? :)

**Comment by dzhytomyrsky** [comment]
ElsePlacement, `@else` should be placed on same line as previous curly brace`

**Comment by vjeux** [comment]
Can you give a code snippet with before/after?

**Comment by dzhytomyrsky** [comment]
Before 

    @if $media == phonePortrait {
        $k: .15625;
    } 
    @else if $media == phoneLandscape {
        $k: .08803;
    } 
    @else if $media == tabletPortrait {
        $k: .065106;
    }

After

@if $media == phonePortrait {
        $k: .15625;
    } @else if $media == phoneLandscape {
        $k: .08803;
    } @else if $media == tabletPortrait {
        $k: .065106;
    }

**Comment by vjeux** [comment]
So, for this one, we are actually using

```js
if (x) {

} else if (y) {

} else {

}
```

in JS so we want to be consistent and use the same one for CSS.

**Comment by vjeux** [comment]
Anything else you are having issues with? :)

**Comment by dzhytomyrsky** [comment]
These two are all I got stack with for today)

**Comment by vjeux** [comment]
Okay thanks. I'm going to close this issue. Feel free to open other issues if you find something else that you'd like prettier to print differently :)

**Comment by dzhytomyrsky** [comment]
Please inform mr when you are done with "ElsePlacement, @else should be placed on same line as previous curly brace" ;)

**Comment by vjeux** [comment]
Ohhh, it's actually --not-- putting them on the same line. Sorry I misunderstood. We need to fix it.
