### ISSUE TITLE
Typescript: Comments inside generic arguments are incorrectly moved outside

### ISSUE THREAD

**Issue by frederickfogerty** [prettier/prettier#2054]
Hey there guys, comments behave weirdly with generics when using Typescript.

Input
```ts
functionName<A /* A comment */>();
```

Output
```ts
functionName<A> /* A comment */();
```

Expected
```ts
functionName<A /* A comment */>();
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22functionName%3CA%20%2F*%20A%20comment%20*%2F%3E()%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks, this looks like a bug, we need to fix it.

**Comment by vjeux** [comment]
This is due to an issue with a dependency: https://github.com/eslint/typescript-eslint-parser/issues/316

**Comment by JamesHenry** [comment]
This has been fixed on master, please see my follow-up PR for more details https://github.com/prettier/prettier/pull/2132
