### ISSUE TITLE
prettier does not remove semis when splitting long typescript type aliases

### ISSUE THREAD

**Issue by aaronjensen** [prettier/prettier#2055]
Running prettier again does remove them as expected.

```typescript
const foo: {aasdf?: string; asdf?: number; foob?: string; zzz?: string; yyy: string}  = {}
```

becomes

```typescript
const foo: {
  aasdf?: string;
  asdf?: number;
  foob?: string;
  zzz?: string;
  yyy: string;
} = {}
```

then, when run again:

```typescript
const foo: {
  aasdf?: string
  asdf?: number
  foob?: string
  zzz?: string
  yyy: string
} = {}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20foo%3A%20%7Baasdf%3F%3A%20string%3B%20asdf%3F%3A%20number%3B%20foob%3F%3A%20string%3B%20zzz%3F%3A%20string%3B%20yyy%3A%20string%7D%20%20%3D%20%7B%7D%5Cn%5Cnconst%20foo%3A%20%7B%5Cn%20%20aasdf%3F%3A%20string%3B%5Cn%20%20asdf%3F%3A%20number%3B%5Cn%20%20foob%3F%3A%20string%3B%5Cn%20%20zzz%3F%3A%20string%3B%5Cn%20%20yyy%3A%20string%3B%5Cn%7D%20%3D%20%7B%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
This is weird. Note that this only is an issue if you have the `--no-semi` option.
