### ISSUE TITLE
[CSS] Don’t combine multiple selectors onto same line

### ISSUE THREAD

**Issue by keithjgrant** [prettier/prettier#2057]
Right now, Prettier merges multiple selectors into the same line if space allows:

```
.foo,
.bar,
.baz {}
```

becomes:

```
.foo, .bar, .baz {}
```

I don’t think this behavior jives with the way most people write CSS. It is both my preference and, I think, more common to always separate selectors onto their own lines, regardless of length. This helps when scanning a file visually for a particular selector, so `.foo, .bar` isn’t mis-read as `.foo .bar`.

Additional support for this reasoning: reading through the [Bootstrap source](https://github.com/twbs/bootstrap), they keep selectors separate, regardless of length, in almost every instance. The [Foundation framework](https://github.com/zurb/foundation-sites) also follows this practice for the most part, though it’s a little less consistent.

**Comment by keithjgrant** [comment]
BTW, thanks for the CSS support. This is awesome! 😃

**Comment by vjeux** [comment]
I just merged @yuchi's PR to fix this! https://github.com/prettier/prettier/pull/2047 In the next release of prettier it'll always print them line by line.
