### ISSUE TITLE
On NPM executable files `#! /usr/bin/env node` is stripped

### ISSUE THREAD

**Issue by zachleat** [prettier/prettier#2058]
via https://docs.npmjs.com/files/package.json#bin

Can’t use `// prettier-ignore` here since `#! /usr/bin/env node` is required to be on the first line.

**Comment by vjeux** [comment]
Can you provide the steps your are using to get to that result and which version of prettier you are using? We fixed some edge cases with this recently. Thanks!

**Comment by zachleat** [comment]
Sure @vjeux, I was using https://packagecontrol.io/packages/JsPrettier through the command palette 
![image](https://user-images.githubusercontent.com/39355/26938620-5828a718-4c3a-11e7-9e95-f5e3324ac7bc.png)

**Comment by vjeux** [comment]
Can you look at what version they are using. 1.4.4 (the latest) should have this bug fixed.

**Comment by zachleat** [comment]
Found this:

```
	// - Locally installed prettier, relative to the Sublime Text Project file's
	//   root directory, e.g.: `node_modules/.bin/prettier'.
	// - The user's home directory, e.g.: `$HOME/node_modules/.bin/prettier`.
	// - Look in the JsPrettier Sublime Text plug-in directory for
	//   `node_modules/.bin/prettier`.
	// - Finally, check if prettier is installed globally,
	//   e.g.: `yarn global add prettier`
	//     or: `npm install -g prettier`
```

Upgraded my global prettier (was at 1.4.0 now at 1.4.4) and this now works as expected. Thanks!

**Comment by vjeux** [comment]
Awesome!
