### ISSUE TITLE
TypeScript: Prettier unable to Parse readonly property on interface

### ISSUE THREAD

**Issue by theseyi** [prettier/prettier#2059]
According to the TypeScript documentation, `readonly` only properties are valid on interface declarations. However, it seems prettier does not consider this scenario valid.
http://www.typescriptlang.org/docs/handbook/interfaces.html

Sample:
```typescript
interface SessionRoute {
  readonly session: Ember.Service;
  [prop: string]: any;
}
```

Exception:
```
SyntaxError: Unexpected token, expected : (6:11)

  4 | 
  5 | interface SessionRoute {
> 6 |   readonly session: Ember.Service;
    |            ^
  7 |   [prop: string]: any;
  8 | }
  9 | 
```

Expected:

prettier source

**Comment by vjeux** [comment]
You need to configure your integration to use typescript, it is using normal JavaScript for your example.

Either name your file `.ts` or `.tsx` or add `--parser typescript`

https://prettier.github.io/prettier/#%7B%22content%22%3A%22interface%20SessionRoute%20%7B%5Cn%20%20readonly%20session%3A%20Ember.Service%3B%5Cn%20%20%5Bprop%3A%20string%5D%3A%20any%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
