### ISSUE TITLE
Typescript: bad behaviour with interface declaration

### ISSUE THREAD

**Issue by Wenqer** [prettier/prettier#2064]
Running prettier on function with declared as multiline interface without delimiters
```
const test = (args: {
  foo: string
  bar: boolean
}) => {}
```
becomes broken
```
const test = (args: { foo: string bar: boolean }) => {}
```
https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20test%20%3D%20(args%3A%20%7B%5Cn%20%20foo%3A%20string%5Cn%20%20bar%3A%20boolean%5Cn%7D)%20%3D%3E%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A100%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Maybe related to https://github.com/prettier/prettier/issues/1930

**Comment by vjeux** [comment]
Sorry about it, it's actually still an issue in master!

**Comment by vjeux** [comment]
Actually, I fixed it in https://github.com/prettier/prettier/pull/2063
