### ISSUE TITLE
Respect line breaks around directives

### ISSUE THREAD

**Issue by langdonx** [prettier/prettier#2067]
prettier does a great job of respecting line breaks (for separating ideas).  Unfortunately it always removes line breaks after directives.  Is this part of the opinionated-ness of prettier?

I'm using ESLint's [lines-around-directive](http://eslint.org/docs/rules/lines-around-directive), which will fail for files formatted by prettier.

Input:
```js
export default class {
  constructor($log, $uibModal) {
    'ngInject';

    Object.assign(this, { $log, $uibModal });

    this.prop1 = '';
    this.prop2 = '';
    this.prop3 = '';

    this.separateIdea = 'respecting line breaks';
  }
}
```
Output:
```js
export default class {
  constructor($log, $uibModal) {
    "ngInject";
    Object.assign(this, { $log, $uibModal });

    this.prop1 = "";
    this.prop2 = "";
    this.prop3 = "";

    this.separateIdea = "respecting line breaks";
  }
}
```

Desired Output:
```js
export default class {
  constructor($log, $uibModal) {
    "ngInject";

    Object.assign(this, { $log, $uibModal });

    this.prop1 = "";
    this.prop2 = "";
    this.prop3 = "";

    this.separateIdea = "respecting line breaks";
  }
}
```

**Comment by langdonx** [comment]
This is only an issue w/ the `babylon` parser apparently.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20default%20class%20%7B%5Cn%20%20constructor(%24log%2C%20%24uibModal)%20%7B%5Cn%20%20%20%20'ngInject'%3B%5Cn%5Cn%20%20%20%20Object.assign(this%2C%20%7B%20%24log%2C%20%24uibModal%20%7D)%3B%5Cn%5Cn%20%20%20%20this.prop1%20%3D%20''%3B%5Cn%20%20%20%20this.prop2%20%3D%20''%3B%5Cn%20%20%20%20this.prop3%20%3D%20''%3B%5Cn%5Cn%20%20%20%20this.separateIdea%20%3D%20'respecting%20line%20breaks'%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Nope, this is a bug, prettier should maintain the empty line if you add one there.
