### ISSUE TITLE
TypeScript: Extra vertical bar in union types that wrap

### ISSUE THREAD

**Issue by KevinKelchen** [prettier/prettier#2069]
Hi! 👋

Prettier is adding an extra `|` character between the `=` operator and the first type listed when the union type wraps to a new line. This results in a TypeScript compilation error.

Here's an example of how a union type is formatted when the Print Width hasn't been exceeded and therefore doesn't wrap. This is valid TypeScript:

```js
export type PizzaTypeNoWrap = "Cheese" | "Pepperoni" | "Supreme";
```

Here's an example of how a union type is formatted when the Print Width _has_ been exceeded and the line wraps. Note the `|` to the left of `Cheese`. This results in a TypeScript compilation error:

```js
export type PizzaTypeWraps =
  | "Cheese"
  | "Pepperoni"
  | "Supreme"
  | "Taco"
  | "BLT"
  | "Canadian Bacon";
```

This is the compilation error:

```js
Type expected.

      L82:  export type PizzaTypeWraps =
      L83:    | "Cheese"
      L84:    | "Pepperoni"
```

Please let me know if I can provide more information to be helpful! Thanks for creating such an awesome tool! :sparkles: :heart:

P.S. Thanks, @vjeux, for suggesting to open a new issue!

**Comment by vjeux** [comment]
I'm curious, what version of TypeScript are you using? It seems to be working fine on the playground

http://www.typescriptlang.org/play/index.html#src=export%20type%20PizzaTypeWraps%20%3D%0D%0A%20%20%7C%20%22Cheese%22%0D%0A%20%20%7C%20%22Pepperoni%22%0D%0A%20%20%7C%20%22Supreme%22%0D%0A%20%20%7C%20%22Taco%22%0D%0A%20%20%7C%20%22BLT%22%0D%0A%20%20%7C%20%22Canadian%20Bacon%22%3B%0D%0A

**Comment by vjeux** [comment]
Looks like it was added in "TypeScript 2.1.3, Community on Nov 28, 2016"

https://github.com/Microsoft/TypeScript/issues/12071

**Comment by KevinKelchen** [comment]
Wow, great find! :clap:

I am using 2.0.10. That explains it. 😄 

It probably makes sense to go ahead and close the issue, although it does raise an interesting question about which version of TypeScript a given version of Prettier supports. Is there information available for that?

**Comment by vjeux** [comment]
Well, looks like 2.1.3 is the minimum we support :p You are the first one to report an incompatibility between what prettier outputs and what TypeScript supports fwiw. So hopefully this means that it's not a major issue in practice.

I'm not sure how hard it is to upgrade TypeScript, but that's likely a good idea. If we see a major amount of people running into this issue, we may want to address it inside of prettier, but in the meantime, I'm going to close this issue.

**Comment by vjeux** [comment]
Just updated the README to include that information: https://github.com/prettier/prettier/commit/d062961ccfec6ccf77e49fa2fc29b01b92894161

**Comment by KevinKelchen** [comment]
Glad I could be the first! :tada:

Thank you so much for all of your help! I really appreciate you taking the time to do so. Thank you for your hard work on prettier and TypeScript compatibility! :grinning:
