### ISSUE TITLE
Pre-Push or part of jenkins process

### ISSUE THREAD

**Issue by OverseePublic** [prettier/prettier#2071]
Hi guys I have two main questions.

- Do you recommend using pre-commit or pre-push

- Can this be part of jenkins process where the code gets formatted then merges?

**Comment by azz** [comment]
The recommenced way is either pre-commit or on-save. Personally I prefer on-save as it keeps my code nice and tidy while I move things around.

There is some more information on how to do pre-commit in the readme:
https://github.com/prettier/prettier#pre-commit-hook-for-changed-files

I wouldn't recommend having jenkins format your code.

**Comment by vjeux** [comment]
Going to close it as there's been a response.
