### ISSUE TITLE
Removes indentation for one-var declarations

### ISSUE THREAD

**Issue by karanjthakkar** [prettier/prettier#2072]
```js
var templateTagsMapping = {
    '%{itemIndex}': 'index',
    '%{itemUrl}': 'url',
    '%{itemImage}': 'imageUrl',
    '%{itemContentHeader}': 'username',
    '%{itemContentTitle}': 'title',
    '%{itemContentMetaTextTime}': 'createdAt',
    '%{itemContentMetaTextViews}': 'views'
  },
  separator = '<span class="item__content__meta__separator">•</span>',
  templateTagsList = $.map(templateTagsMapping, function(value, key) {
    return key;
  }),
  data;
```

is changed to: 

```js
var templateTagsMapping = {
  '%{itemIndex}': 'index',
  '%{itemUrl}': 'url',
  '%{itemImage}': 'imageUrl',
  '%{itemContentHeader}': 'username',
  '%{itemContentTitle}': 'title',
  '%{itemContentMetaTextTime}': 'createdAt',
  '%{itemContentMetaTextViews}': 'views'
},
  separator = '<span class="item__content__meta__separator">•</span>',
  templateTagsList = $.map(templateTagsMapping, function(value, key) {
    return key;
  }),
  data;
```

This is a normal pattern if you have enabled the http://eslint.org/docs/rules/one-var rule

Repro: https://prettier.github.io/prettier/#%7B%22content%22%3A%22var%20templateTagsMapping%20%3D%20%7B%5Cn%20%20%20%20'%25%7BitemIndex%7D'%3A%20'index'%2C%5Cn%20%20%20%20'%25%7BitemUrl%7D'%3A%20'url'%2C%5Cn%20%20%20%20'%25%7BitemImage%7D'%3A%20'imageUrl'%2C%5Cn%20%20%20%20'%25%7BitemContentHeader%7D'%3A%20'username'%2C%5Cn%20%20%20%20'%25%7BitemContentTitle%7D'%3A%20'title'%2C%5Cn%20%20%20%20'%25%7BitemContentMetaTextTime%7D'%3A%20'createdAt'%2C%5Cn%20%20%20%20'%25%7BitemContentMetaTextViews%7D'%3A%20'views'%5Cn%20%20%7D%2C%5Cn%20%20separator%20%3D%20'%3Cspan%20class%3D%5C%22item__content__meta__separator%5C%22%3E%E2%80%A2%3C%2Fspan%3E'%2C%5Cn%20%20templateTagsList%20%3D%20%24.map(templateTagsMapping%2C%20function(value%2C%20key)%20%7B%5Cn%20%20%20%20return%20key%3B%5Cn%20%20%7D)%2C%5Cn%20%20data%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Is this expected? Am I doing something wrong? Or is this a bug?

**Comment by vjeux** [comment]
This is a bug, looks like we're not indenting the first one properly.

**Comment by karanjthakkar** [comment]
@vjeux I'm not sure where to start but if you could point me then I could send in a fix for this.
