### ISSUE TITLE
Typescript wrapping strings with parentheses

### ISSUE THREAD

**Issue by frontendherodk** [prettier/prettier#2074]
Im currently using `ngInject` for my angular project which means that in your constructor you have to specify `'ngInject'` as the first statement. The problem is that prettier wraps that in parentheses breaking it. 

```js
class MyClass {
  constructor(private abc) {
    'ngInject'
  }
}
```

outputs

```js
class MyClass {
  constructor(private abc) {
    ('ngInject');
  }
}
```

Is there a way to fix that without adding `//prettier-ignore` ?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22hello%20(%20%5C%22world%5C%22%5Cn)%5Cn%5Cnclass%20MyClass%20%7B%5Cn%20%20constructor(private%20abc)%20%7B%5Cn%20%20%20%20'ngInject'%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by azz** [comment]
Seems to work for me

https://prettier.github.io/prettier/#%7B%22content%22%3A%22hello%20(%20%5C%22world%5C%22%5Cn)%5Cn%5Cnclass%20MyClass%20%7B%5Cn%20%20constructor(private%20abc)%20%7B%5Cn%20%20%20%20%2F%2F%20prettier-ignore%5Cn%20%20%20%20'ngInject'%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by frontendherodk** [comment]
@azz Sorry, it should have said without of course  :)

**Comment by vjeux** [comment]
Sorry about this, we need to fix this!

**Comment by azz** [comment]
This was likely introduced with #1999, but it is technically an issue with a dependency (typescript-eslint-parser#267) and the ESTree spec (estree/estree#6).

**Comment by maraisr** [comment]
Sorry - when is this going to a release?

**Comment by vjeux** [comment]
I'm planning a new release for tomorrow morning california time.

**Comment by maraisr** [comment]
Thank you so much @vjeux appreciate all your efforts!
