### ISSUE TITLE
Method chaining with square brackets doesn't work

### ISSUE THREAD

**Issue by Graham42** [prettier/prettier#2075]
When chaining methods and one of them is being accessed with the square bracket notation, the method is not wrapped as I would expect. 

```js
nock(/test/)
  .matchHeader('Accept', 'application/json')
  [httpMethodNock(method)]('/foo')
  .reply(200, {
    foo: 'bar',
  });
```

outputs

```js
nock(/test/)
  .matchHeader("Accept", "application/json")[httpMethodNock(method)]("/foo")
  .reply(200, {
    foo: "bar",
  });
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22nock(%2Ftest%2F)%5Cn%20%20.matchHeader('Accept'%2C%20'application%2Fjson')%5Cn%20%20%5BhttpMethodNock(method)%5D('%2Ffoo')%5Cn%20%20.reply(200%2C%20%7B%5Cn%20%20%20%20foo%3A%20'bar'%2C%5Cn%20%20%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Agreed, it should break, I'm not sure why it isn't off the top of my head.
