### ISSUE TITLE
Import with just one function doesn't break down respecting --print-width 80

### ISSUE THREAD

**Issue by pragmaticivan** [prettier/prettier#2077]
Version: 1.4.4
ES2017

```
import {
  myBigFunctionImportThatOverflows
} from './src/middleware/my-big-function-import-that-overflows';
```
becomes 
```
import {myBigFunctionImportThatOverflows} from './src/middleware/my-big-function-import-that-overflows';
```

**Comment by vjeux** [comment]
This is actually on purpose. If there's a single element being imported, we are going to inline it. Apparently a lot of people disregard the 80 columns in this case for require and imports in order for them to line up better.

**Comment by pragmaticivan** [comment]
Thanks @vjeux

**Comment by ikatyang** [comment]
For reference, this is a duplicate of #1954.
