### ISSUE TITLE
Glob recursively

### ISSUE THREAD

**Issue by kmiyashiro** [prettier/prettier#2078]
I'm attempting to run prettier on a directory recursively, but the following glob pattern only matches a single directory level: `prettier "src/**/*.js"`. This will match `src/blah/foo.js` but not `src/foo.js` or `src/blah/bar/foo.js`. According to https://github.com/isaacs/node-glob/blob/master/README.md#glob-primer, a globstar `**` should match "zero or more directories and subdirectories searching for matches".

Is this due to the way prettier uses node-glob or is this a bug in node-glob?

**Comment by vjeux** [comment]
Can you give the exact command you are running?

**Comment by kmiyashiro** [comment]
In my package.json under `scripts`:

`"prettier": "prettier --print-width 100 --no-semi --single-quote --trailing-comma es5",`

I then run `yarn run prettier -- --write "src/**/*.js"`.

```
yarn run v0.17.8
$ prettier --print-width 100 --no-semi --single-quote --trailing-comma es5 --write src/actions/addBillingDetails.js src/actions/addBillingDetailsFailed.js src/actions/addBillingDetailsPending.js src/actions/addBillingDetailsSuccess.js src/actions/addProduct.js src/actions/addProductFromFeatureSetName.js src/actions/browse.js [...]
```

The list of files is always exactly one directory deep, which doesn't match up with http://www.globtester.com/

What is odd is that if I add enough directories to the glob such that it exceeds the levels of directories in my path, it then behaves as I expect `src/**/*.js` to work.

`yarn run prettier -- --write "src/**/**/**/**/**/*.js"` will behave as I expect `"src/**/*.js"` to work.

**Comment by hawkrives** [comment]
What shell are you using? Bash, zsh, fish, etc.

**Comment by kmiyashiro** [comment]
bash

**Comment by hawkrives** [comment]
So the fact that `yarn` prints out the expanded glob means that your shell is doing the expansion, not `node-glob` (prettier's glob implementation).

Try using single quotes when you invoke prettier – bash won't do any expansion inside of single quotes.

```bash
yarn run prettier -- --write 'src/**/*.js'
```

The single `/**/` segment should be enough to do a recursive glob; I'm not sure why it's not. I also wouldn't have expected bash to expand a glob inside of double-quotes. However! Try single quotes and report back.

Good luck!

**Comment by lydell** [comment]
Running things through `yarn` means two levels of quoting is needed: `yarn run prettier -- --write '"src/**/*.js"'` should do the trick.

It's still odd that your output wasn't this, though:

```
yarn run v0.17.8
$ prettier --print-width 100 --no-semi --single-quote --trailing-comma es5 --write src/**/*.js
```

**Comment by kmiyashiro** [comment]
@lydell @hawkrives single quotes with double quotes inside appears to work (`'"src/**/*.js"'`), just single quotes doesn't! Thanks!

**Comment by capaj** [comment]
@hawkrives thanks so much, single quotes fixed the globbing it for me!
