### ISSUE TITLE
Don't newline long strings?

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier#2079]
:wave: Hey all! I love this tool!

My team and I have a request here.

Input:

```
const foo = {
  longString: 'I am a long string and I do not like that it goes on a brand new line all by itself'
}
```

Output:

```
const foo = {
  longString:
    'I am a long string and I do not like that it goes on a brand new line all by itself'
}
```

[Live](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20foo%20%3D%20%7B%5Cn%20%20longString%3A%20'I%20am%20a%20long%20string%20and%20I%20do%20not%20like%20that%20it%20goes%20on%20a%20brand%20new%20line%20all%20by%20itself'%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

I can appreciate the goal is to prevent the line exceeding the max width, but the string is so long it doesn't even accomplish that. So the output is not prettier than the input, _and_ we didn't even accomplish the goal anyway.

I'm curious what folks think here.

**Comment by kentcdodds** [comment]
This is semi-related to https://github.com/prettier/prettier/issues/1893 which we're also having trouble with.

**Comment by lydell** [comment]
![screenshot from 2017-06-11 14-18-45](https://user-images.githubusercontent.com/2142817/27010950-effa767a-4eb0-11e7-83cb-8e8780cf2d80.png)

I can't see the entire input code without scrolling horizontally, but I can see the entire output code without scrolling. So I guess my point is that while moving to a new line doesn't accomplish the goal of not exceeding the max length, it still let's you see more of the long string than before. ¯\\\_(ツ)\_/¯

**Comment by azz** [comment]
![image](https://user-images.githubusercontent.com/1297597/27010999-e8e12d7c-4ef4-11e7-8303-4bf64262ac2a.png)

_Sorry, couldn't help myself._

I agree with @lydell on this one. I might have my editor showing ~90 columns when prettier is set to 80 columns wide, so this will still prevent horizontal scrolling in some cases.

**Comment by kentcdodds** [comment]
Bad example I guess. It does let you see a few characters more and may prevent scrolling in very few cases, but at the cost of not looking prettier. The benefit is not worth the cost.

**Comment by mafredri** [comment]
I happen to think that the output in this case is prettier and more readable than the input, but I didn't always feel this way. I was using `clang-format` for a while before I started using `prettier` and there the behavior was the same, so I got used to it.

Biggest issue here IMO is that seeing output like this has not been common in the JS community. So people aren't used to it.

The property name could easily be longer, `thisIsAVeryLongPropertyName: '...'`, in which case the line splitting starts paying off more and more. Now, we could argue that the property name could be short as well, `p: '...'`, but we can't make exceptions depending on which property name is used. If we started using different formatting depending on the length of the property name it would make `prettier` overly complex and the user could not understand how we ended up with a certain result. Personally I would pick the line-split for the long property name over the non-split variant (it's an either or game).

I happen to think that this is an excellent opportunity to reconsider the long string, maybe split it further for better readability:

```js
const foo = {
  longString:
    'I am a long string and I do not like that it goes on a brand new line ' +
      'all by itself'
}
```

**Comment by azz** [comment]
I'm not a fan of splitting strings.

1. If you delete some characters or change the print-width, prettier would have to know to recombine.
2. Prettier could create awkward breaks in the string (semantically).
3. It changes the run-time behaviour of the code (if only slightly).

I'd be more inclined to turn on max-line-len on a linter and fix those error manually.

**Comment by mafredri** [comment]
Oh, sorry that I wasn't clear. Under no circumstance do I want prettier to split the string, I meant it's an opportunity for manual effort.

**Comment by vjeux** [comment]
I'm with @lydell on the fact that you can now see more of the string. We've added the ability to break here as the key can be very long and it helps when it is split.

If you write code that is more than 80 columns, I think it makes sense for prettier to be doing a best effort...

I'm going to close this. I don't think that there's an ideal way to print this and the current behavior is reasonable, so I don't think it's a good idea to change it.
