### ISSUE TITLE
[Prettier SCSS] reformatting function values onto newlines

### ISSUE THREAD

**Issue by topherauyeung** [prettier/prettier#2080]
Would be nice if Prettier could differentiate between scenarios like this when reformatting function values onto new lines:

![1](https://user-images.githubusercontent.com/1114632/26990331-14cabcc8-4d0b-11e7-88f9-a999898a817c.png)
and
![2](https://user-images.githubusercontent.com/1114632/26906214-9432f6d6-4ba0-11e7-9199-f3e66b18cd21.png)

Top one seems like an improvement, but the bottom one less so?

**Comment by vjeux** [comment]
For the bottom one, this is because the comment makes it go past 80 columns, so it's going to break. If you move the comment above, it's going to "fix" it.
