### ISSUE TITLE
--list-different does not work when use --write, using prettier+prettier-eslint+prettier-eslint-cli

### ISSUE THREAD

**Issue by dzhytomyrsky** [prettier/prettier#2090]
I wrote such npm script in my package.json: 

`"format-js": "prettier-eslint --print-width 100 --list-different --write 'webpack/**/*.js' 'development/**/*.js'"`

it formats my js, but does not print prettified files. Is it possible to use  --list-different with --write?

If not, it would be great to))

**Comment by vjeux** [comment]
@josephfrazier I remember you made both of them work together, do you know if there's a bug with it?

**Comment by azz** [comment]
I suspect `prettier-eslint` is using an older version of prettier. This was fixed in #1633.

**Comment by vjeux** [comment]
This got released in 1.4.0

**Comment by dzhytomyrsky** [comment]
Opened same issue in prettier-eslint

https://github.com/prettier/prettier-eslint/issues/93
