### ISSUE TITLE
Emoji messes up location in flow

### ISSUE THREAD

**Issue by Haroenv** [prettier/prettier#2091]
Hey, great job on Prettier, I've been in love since it was released. I just noticed some weird reformatting regarding multiline comments.

The original code (can also have a newline after the comment): 

```js
/**
 * Set the html stub
 */
const stub = fs.readFileSync('./__tests__/stub.html').toString();
```

Gets formatted as:

```js
/**
 * Set the html stub
 */ const stub = fs
  .readFileSync('./__tests__/stub.html')
  .toString();
```

While I think it should be like this:

```js
/**
 * Set the html stub
 */
const stub = fs
  .readFileSync('./__tests__/stub.html')
  .toString();
```

A similar thing happens at the beginning of a multiline comment:

```js
// before:

function setStub() {
  document.body.innerHTML = stub;
}

/**
 * Enter a string into this Holmes input
 * @param  {string}      text text to input
 * @param  {HTMLElement} element to input in (optional)
 * @return {Promise}     resolves when the input has been doen
 */
function input(text, input) {

// after:

function setStub() {
  document.body.innerHTML = stub;
} /**
 * Enter a string into this Holmes input
 * @param  {string}      text text to input
 * @param  {HTMLElement} element to input in (optional)
 * @return {Promise}     resolves when the input has been doen
 */
 ```

Have a great day everyone :smile: :heart:

**Comment by vjeux** [comment]
This is most likely not prettier doing. Could you tell us what you are doing to run prettier?

**Comment by Haroenv** [comment]
Was using the visual studio code integration. I’ll check if it also occurs with the command line.

**Comment by Haroenv** [comment]
Yep, it’s actually a different bug in the vscode integration related to having an emoji as last character of the comment before. Can’t replicate with plain prettier:

```js
// capital 😡

/**
 * Set the html stub
 */
const stub = fs
  .readFileSync('./__tests__/stub.html')
  .toString();

function setStub() {

}
/**
 */
```

gets converted to 

```js
// capital 😡
/**
 * Set the html stub
 */ const stub = fs
  .readFileSync('./__tests__/stub.html')
  .toString();

function setStub() {} /**
 */
```

**Comment by azz** [comment]
I love this bug.

**Comment by Haroenv** [comment]
This is an issue in the flow parser (I didn’t notice I had that one enabled)

[link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20capital%20😡%5Cn%5Cn%2F**%5Cn%20*%20Set%20the%20html%20stub%5Cn%20*%2F%5Cnconst%20stub%20%3D%20fs%5Cn%20%20.readFileSync('.%2F__tests__%2Fstub.html')%5Cn%20%20.toString()%3B%5Cn%5Cnfunction%20setStub()%20%7B%5Cn%5Cn%7D%5Cn%2F**%5Cn%20*%2F%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
This is indeed a bug in flow. I raised this issue to the flow team FYI.

**Comment by betaorbust** [comment]
It looks like it's a larger issue. Here's the minimum reproducible case: 
https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8OYLyYDkgvBuBpO4QDpQD01mAEnAE5yYCGLmaEAtq5Dz6w0VWtgAWbLAHcAlgBt5mAOZwskRWwAOaOABNRdWVHaYWbRQE8uMJmyirM0tpYB07kABoQELTFnoyKAcTBDSAAocCGjIIGwAbhCyel4gAEZ2YADWagDKWmxgxsrItgCucN7Gukww4XbKPGzIAGYWut4AVmgAHgBCmTkwuWx8ADLGcK3tlSAFTDWxLfJhqVpMxjAA6skw4sgAHAAM3usQult2WrHrcDXxU94sAI5lsiz1bI3NSG3yHSBdDxZKUmBVvGhivI4ABFMoQeCg8EgGBsNI7PR7ZAAJm8tjYCmKAGFeE1YlBoI8QGVdAAVNExX4zAC+zKAA
This was originally in a huge file, and I stripped it down to just having any emoji anywhere in the file while the flow parser is working means that line comments get jumbled and pulled together.

**Comment by vjeux** [comment]
^^ cc @mroch, I thought this was no longer an issue

**Comment by betaorbust** [comment]
It looks like the comments in https://github.com/facebook/flow/issues/4219 are that they don't think it's a flow bug, exactly, but rather an encoding issue. Is there some path forward to address this?

**Comment by vjeux** [comment]
@betaorbust I replied, I do think that it's a bug in flow, but it may be tricky to fix. Do you have a reason to use the flow parser instead of babylon?

**Comment by thorn0** [comment]
This has been fixed. Most probably #6830.
