### ISSUE TITLE
Unnecessary new lines inside generics

### ISSUE THREAD

**Issue by tusharmath** [prettier/prettier#2099]
## Input
```ts
export const forwardS = R.curry(
  <V,T>(prop: string, reducer: ReducerFunction<V, T>, value: V, state: {[name: string]: T}) =>
  R.assoc(prop, reducer(value, state[prop]), state)
)
```
## Output

```ts
export const forwardS = R.curry(<
  V,
  T // unnecessary new lines
>(prop: string, reducer: ReducerFunction<V, T>, value: V, state: {[name: string]: T}) =>
  R.assoc(prop, reducer(value, state[prop]), state)
);

```

## Expected

```ts
export const forwardS = R.curry(
  <V,  T>
  (prop: string, reducer: ReducerFunction<V, T>, value: V, state: {[name: string]: T}) =>
    R.assoc(prop, reducer(value, state[prop]), state)
)

```

[Example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20const%20forwardS%20%3D%20R.curry(%5Cn%20%20%3CV%2CT%3E(prop%3A%20string%2C%20reducer%3A%20ReducerFunction%3CV%2C%20T%3E%2C%20value%3A%20V%2C%20state%3A%20%7B%5Bname%3A%20string%5D%3A%20T%7D)%20%3D%3E%5Cn%20%20R.assoc(prop%2C%20reducer(value%2C%20state%5Bprop%5D)%2C%20state)%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by azz** [comment]
Thanks for the report!

This seems to be a difficult one to fix. I had an attempt with ee923bfe42a6730aafa39170f4db9413d3c0e615 but I couldn't get the indentation correct with the `R.assoc`:

https://github.com/azz/prettier/commit/ee923bfe42a6730aafa39170f4db9413d3c0e615#diff-5b476c7f446681f2ad5e208aea6f45a3R18

@vjeux Since the `<V, T>` and the `R.assoc(...)` belong to different, adjacent `group`s, does this mean prettier can't actually print this?

**Comment by azz** [comment]
Actually, I think we should print it like this:

```ts
export const forwardS = R.curry(<V, T>(
  prop: string,
  reducer: ReducerFunction<V, T>,
  value: V,
  state: {[name: string]: T}
) =>
  R.assoc(prop, reducer(value, state[prop]), state)
)
```

**Comment by tusharmath** [comment]
@azz I like your version as well.

**Comment by azz** [comment]
It's how prettier [will format it](https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20const%20forwardS%20%3D%20R.curry(%5Cn%20%20(prop%3A%20string%2C%20reducer%3A%20ReducerFunction%3CV%2C%20T%3E%2C%20value%3A%20V%2C%20state%3A%20%7B%5Bname%3A%20string%5D%3A%20T%7D)%20%3D%3E%5Cn%20%20R.assoc(prop%2C%20reducer(value%2C%20state%5Bprop%5D)%2C%20state)%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A61%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) if you remove the `<V, T>`.

**Comment by bhavinkamani** [comment]
I am running into a situation where line breaks are happening inside generics. Here's the [sample code](https://prettier.io/playground/#%7B%22content%22%3A%22Rx.Observable%5Cn%20%20%20%20.from%3Cstring%3E(data.split(%5C%22%5C%5Cn%5C%22))%5Cn%20%20%20%20.map((datum%3A%20string)%3A%20string%5B%5D%20%3D%3E%20datum.split(%5C%22%2C%20%5C%22))%5Cn%20%20%20%20.groupBy((%5BuserId%2C%20_%5D%3A%20%5Bstring%2C%20string%5D)%3A%20string%20%3D%3E%20userId)%5Cn%20%20%20%20.flatMap((tuple%3A%20GroupedObservable%3Cstring%2C%20string%5B%5D%3E)%3A%20Rx.Observable%3Cstring%3E%20%3D%3E%5Cn%20%20%20%20%20%20tuple%5Cn%20%20%20%20%20%20%20%20.pairwise()%5Cn%20%20%20%20%20%20%20%20.map(%5Cn%20%20%20%20%20%20%20%20%20%20(%5B%5B_%2C%20l1%5D%2C%20%5B__%2C%20l2%5D%5D%3A%20%5B%5Bstring%2C%20string%5D%2C%20%5Bstring%2C%20string%5D%5D)%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%60%24%7Bl1%7D%20%3D%3E%20%24%7Bl2%7D%60%5Cn%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20)%5Cn%20%20%20%20.flatMap((transitions%3A%20GroupedObservable%3Cstring%2C%20string%3E)%3A%20Rx.Observable%3C%5Bstring%2C%20number%5D%3E%20%3D%3E%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20Rx.Observable.of%3Cstring%3E(transitions.key).zip(transitions.count()))%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D). 

On Line no 5-7, 15-17, I see a line break on the generics. This seems to be the case when arrow function's return value signature is using generics.

**Comment by bhavinkamani** [comment]
Thanks @azz I like your example. IMO that would be preferred over exceeding print width
