### ISSUE TITLE
TypeScript "new" in interfaces doesn't linebreak at 80 characters

### ISSUE THREAD

**Issue by dphilipson** [prettier/prettier#2105]
Hi Prettier, I'm a big fan of your work!

I would expect a TypeScript interface with a `new` entry, if longer than 80 characters, to be formatted as follows:
``` javascript
interface FooConstructor {
  new (
    a: number,
    b: number,
    c: number,
    d: number,
    e: number,
    f: number,
    g: number,
    h: number
  ): Foo;
}
```
Instead, it is formatted as:
``` javascript
interface FooConstructor {
  new (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): Foo;
}
```
This differs from the behavior of methods on an interface, which are formatted as the first case.

Demonstration [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22interface%20FooConstructor%20%7B%5Cn%20%20new%20(%5Cn%20%20%20%20a%3A%20number%2C%5Cn%20%20%20%20b%3A%20number%2C%5Cn%20%20%20%20c%3A%20number%2C%5Cn%20%20%20%20d%3A%20number%2C%5Cn%20%20%20%20e%3A%20number%2C%5Cn%20%20%20%20f%3A%20number%2C%5Cn%20%20%20%20g%3A%20number%2C%5Cn%20%20%20%20h%3A%20number%5Cn%20%20)%3A%20Foo%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D).

**Comment by azz** [comment]
Thanks for the report. Turns out we weren't doing the right thing for constructor and call signatures in types and interfaces.
