### ISSUE TITLE
Glob pattern runs against node_modules

### ISSUE THREAD

**Issue by jthegedus** [prettier/prettier#2110]
I wasn't sure if this was an error here or in [node-glob](https://github.com/isaacs/node-glob/), apology if I picked the wrong of the two.

Prettier CLI runs against `node_modules` when the path glob is prepended with `./`

example scripts:
```shell
"scripts": {
    "formats-wrong": "prettier --write \"./**/*.js\"",
    "formats-right": "prettier --write \"**/*.js\""
  }
```
Many people prepend relative filepaths with the `./` elsewhere in their code. Consistency would be awesome. It took quite a while to find this error too as the `./` works in every other tool or script I have written with Node.

[A test repo](https://github.com/jthegedus/prettier-node-modules-test).

**Comment by cirpo** [comment]
👍

**Comment by vvo** [comment]
I thought prettier always formatted code in node_modules when using **/*.js? This was recently fixed but not yet released no?

**Comment by azz** [comment]
@jthegedus Can you confirm, are you running on Windows?

**Comment by jthegedus** [comment]
@vvo I believe the fix for ignore node_modules was released in v1.4.0

@azz I tested this on ZSH and Bash on Ubuntu

**Comment by jthegedus** [comment]
So I tested this on Windows 10 v1703 using Powershell, Node 6.11.0 and Yarn 0.24.6 - I got the same result as before.

<img width="444" alt="prettier-glob-error" src="https://user-images.githubusercontent.com/20798510/27252457-6644d6a4-53a2-11e7-8655-c6b1a534d41f.PNG">

I feel I should mention again that I'm not sure if this is an error in how node_modules ignoring is computed in prettier or if it's an issue with node-glob. The docs clearly state that users should use node-glob patterns and node-glob doesn't ever say it supports `./`. Despite this, it would be good to have the support for `./` in prettier however that is achieved.

**Comment by azz** [comment]
Confirming this is an issue with node-glob. 

```
$ node -p 'require("glob").sync("**/*.js", { ignore: "**/node_modules/**" })'
[ 'index.js', 'src/file.js' ]
$ node -p 'require("glob").sync("./**/*.js", { ignore: "**/node_modules/**" })'
[ './index.js',
  './node_modules/balanced-match/index.js',
  './node_modules/brace-expansion/index.js',
  './node_modules/concat-map/example/map.js',
  './node_modules/concat-map/index.js',
  './node_modules/concat-map/test/map.js',
  './node_modules/fs.realpath/index.js',
  './node_modules/fs.realpath/old.js',
  './node_modules/glob/common.js',
  './node_modules/glob/glob.js',
  './node_modules/glob/sync.js',
  './node_modules/inflight/inflight.js',
  './node_modules/inherits/inherits_browser.js',
  './node_modules/inherits/inherits.js',
  './node_modules/minimatch/minimatch.js',
  './node_modules/once/once.js',
  './node_modules/path-is-absolute/index.js',
  './node_modules/wrappy/wrappy.js',
  './src/file.js' ]
```

Interestingly it can be fixed like so:

```
$ node -p 'require("glob").sync("./**/*.js", { ignore: ["**/node_modules/**", "./node_modules/**"] })'
[ './index.js', './src/file.js' ]
```

**Comment by azz** [comment]
Worked around the problem for now.

Found this report over at node-glob: https://github.com/isaacs/node-glob/issues/309

**Comment by jthegedus** [comment]
@azz Thanks for the support 😄
