### ISSUE TITLE
Ambiguous error message when using reserved words

### ISSUE THREAD

**Issue by Sajjadhosn** [prettier/prettier#2111]
Reproduction [link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22var%20package%20%3D%20require('..%2Fpackage')%3B%5Cn%5Cn%2F**%5Cn%20*%20My%20amazing%20comment%5Cn%20*%2F%5Cnfunction%20myFunction()%20%7B%5Cn%5Ctreturn%20'StringGainz'%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D).

`Comment <comment> was not printed. Please report this error!` in this case is not descriptive. In migration of a repository from a certain linter to `prettier`, I faced a module which was using `package` reserved word and it took me 3 hours of trial and error to pinpoint the failure cause. If the comment would have warned me with something like:

`WARN: reserved word "package" is used in this module. Parsing might be done incompletely due to this.`

It would have been better.

**Comment by azz** [comment]
We definitely should be able to do better there. That's an interesting one for sure.

**Comment by vjeux** [comment]
Looks like it's only an issue for babylon. Flow and TypeScript parser are printing it just fine.
