### ISSUE TITLE
Typescript: Dynamic imports cause syntax errors

### ISSUE THREAD

**Issue by crohlfs** [prettier/prettier#2117]
Copied the Dynamic Import Expressions example from [here](https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/) and it causes `SyntaxError: Expression expected`

[Replication](https://prettier.github.io/prettier/#%7B%22content%22%3A%22async%20function%20getZipFile(name%3A%20string%2C%20files%3A%20File%5B%5D)%3A%20Promise%3CFile%3E%20%7B%5Cn%20%20%20%20const%20zipUtil%20%3D%20await%20import('.%2Futils%2Fcreate-zip-file')%3B%5Cn%20%20%20%20const%20zipContents%20%3D%20await%20zipUtil.getContentAsBlob(files)%3B%5Cn%20%20%20%20return%20new%20File(zipContents%2C%20name)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by azz** [comment]
We don't officially support TypeScript 2.4 yet. We'll need to do some work with [our dependency](https://github.com/eslint/typescript-eslint-parser) to ship it!

**Comment by azz** [comment]
Opened for tracking this:
https://github.com/eslint/typescript-eslint-parser/issues/321

**Comment by crohlfs** [comment]
I thought as much, sounds like a good plan!

**Comment by vjeux** [comment]
@azz typescript is a peer dependency so we should upgrade it here. But I have no idea if it's going to transform it correctly though.

**Comment by vjeux** [comment]
Upgrading to TS 2.4.0 triggers a giant warning but otherwise everything works.

```js
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~2.3.2

YOUR TYPESCRIPT VERSION: 2.4.0

Please only submit bug reports when using the officially supported version.

=============
```

It looks like it introduces a new node type:

```js
test.js: Error: unknown type: "TSImportKeyword"
```

**Comment by vjeux** [comment]
```diff
     }

+    case "TSImportKeyword":
     case "Import":
       return "import";
```

is all what is needed for supporting this.

**Comment by azz** [comment]
`"Import"` is correct according to estree, I've pushed a commit to the parser to make that transform.

**Comment by sammkj** [comment]
is this fixed? I'm still getting error when running prettier.

**Comment by hawkrives** [comment]
@sammkj No.
