### ISSUE TITLE
Typescript readonly interface properties

### ISSUE THREAD

**Issue by ForbesLindesay** [prettier/prettier#2119]
```ts
export interface Position {
  readonly line: number,
  readonly column: number,
}
```

Produces an error of:

```
SyntaxError: Unexpected token, expected : (2:11)
  1 | export interface Position {
> 2 |   readonly line: number;
    |            ^
  3 |   readonly column: number;
  4 | }
  5 | 
```

in prettier

**Comment by azz** [comment]
How are you invoking prettier? If you're using stdin you need to pass `--stdin-filepath foo.ts` or `--parser typescript`.

**Comment by ForbesLindesay** [comment]
I hadn't added the `--parser` option.  I ended up at the release notes on https://github.com/prettier/prettier/releases/tag/1.4.0 after googling for prettier typescript, and it didn't mention needing that option.

**Comment by vjeux** [comment]
@azz: we should print which parser triggers a syntax error, this would help with those issues.
