### ISSUE TITLE
Invalid whitespace

### ISSUE THREAD

**Issue by tusharmath** [prettier/prettier#2123]
## Input

```ts
const t = h('div.account-summary', [
    h('div.account-summary__header',
      {
        on: {}
      },
      []
    )
  ])
```

## Output 
```ts
const t = h('div.account-summary', [
  h(
    'div.account-summary__header',
    {
      on: {}
    },
    []
  )
])

```

## Expected 
```ts
const t = h('div.account-summary', [
  h('div.account-summary__header',
    {
      on: {}
    },
    []
  )
])
```

[Sample](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20t%20%3D%20h('div.account-summary'%2C%20%5B%5Cn%20%20%20%20h('div.account-summary__header'%2C%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20on%3A%20%7B%7D%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%5B%5D%5Cn%20%20%20%20)%5Cn%20%20%5D)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by lydell** [comment]
Thanks for your issue! Merging into #1949.
