### ISSUE TITLE
SCSS - Multiple files in a single import not supported

### ISSUE THREAD

**Issue by karl** [prettier/prettier#2125]
According to the SCSS/SASS documentation you can import multiple files in a single `@import` declaration:

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import

Given this SCSS:

```scss
@import "rounded-corners", "text-shadow";
```

Prettier currently only keeps the last import:

```scss
@import "text-shadow";
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%40import%20%5C%22rounded-corners%5C%22%2C%20%5C%22text-shadow%5C%22%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by karl** [comment]
Interestingly as soon as you use nested selectors then multiple imports start working!

```
@import "first", "second";

div {
  color: red;

  div {
    color: blue;
  }
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%40import%20%5C%22first%5C%22%2C%20%5C%22second%5C%22%3B%5Cn%5Cndiv%20%7B%5Cn%20%20color%3A%20red%3B%5Cn%5Cn%20%20div%20%7B%5Cn%20%20%20%20color%3A%20blue%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by azz** [comment]
Maybe it's using the Less parser in the first case?

**Comment by sgangadhar02** [comment]
Any update on this one?

**Comment by karl** [comment]
Thanks @vjeux!
