### ISSUE TITLE
There is an intention to support es6 template strings ？

### ISSUE THREAD

**Issue by isbasex** [prettier/prettier#2130]
```
return `<label class="radio-inline">
<input type="radio" name="board_id" data-name="board_id" value="${board['id']}"> 
${board['name']}
</label>`
```
to

```
 return `<label class="radio-inline">
             <input type="radio" name="board_id" data-name="board_id" value="${board['id']}"> 
             ${board['name']}
         </label>`
```

**Comment by lydell** [comment]
That would change the contents of your template string, which could change the meaning of your program, so Prettier can’t do that.

However, Prettier has recently started to identify certain _tagged_ template literals and format them. See #2086, #2102 and #2092. But in your case you have no tag on your template literal so Prettier can’t know if it is safe to touch it or not.

So in conclusion: In your specific case there’s nothing Prettier can do, but if you start using some popular template tag for HTML, Prettier can add support for it.
