### ISSUE TITLE
Unexpected semicolon in output

### ISSUE THREAD

**Issue by havaliza** [prettier/prettier#2133]
Prettier 1.4.4 outputs an extra `;` formatting the following code **with `--no-semi` flag enabled**:

```js
function f() {
  ['foo', 'bar'].forEach(e => console.log(e))
}
```

Resulting:

```js
function f() {
  ;["foo", "bar"].forEach(e => console.log(e))
}
```

I produced it [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20%5B'foo'%2C%20'bar'%5D.forEach(e%20%3D%3E%20console.log(e))%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) using the online editor.

The smallest code producing the extra semicolon is `[]` which results `;[]`. Is this the intended output? This violates the `--no-semi` flag and raises lint error.

Cheers,
Hamed

**Comment by lydell** [comment]
This is actually intended. As described in the [options](https://github.com/prettier/prettier#options):

> Semicolons - Print semicolons at the ends of statements.
>
> Valid options:
> - true - add a semicolon at the end of every statement
> - false - only add semicolons at the beginning of lines that may introduce ASI failures

See #1935 and the issues it links to.
