### ISSUE TITLE
length of CSS colors

### ISSUE THREAD

**Issue by bardware** [prettier/prettier#2139]
After I ran prettier on my `.scss` files I see some colors written in upper case and some in lower case. Some are 3 chars long, others 6.
Is there a way prettier would standardize the way colors are written? I personally prefer 6 chars lower case.

**Comment by k15a** [comment]
We are doing these things in JavaScript as well. For example, 1.0000 gets 1.0 so this should be possible too.

**Comment by jitendravyas** [comment]
Stylelint has a autofix for this but I'm not sure if this comes under scope of Prettier

**Comment by mafredri** [comment]
I think prettier could easily take a stance on either lower or upper case colors. If I had to pick one, I'd say lower case since that's how I type them (not like I want to hold shift while typing colors). But I wouldn't make a fuzz either choice.

I'd be a bit opposed on normalizing 3 vs 6 though. Say I try out the color `#ffffff`, let's say I didn't like it and want to try out a tone of yellow `#ffff0f` or pink `#ff0fff`, it would be quite inconvenient if prettier kept truncating the color to `#fff` between saves. Same applies to the other way around, say I have `#fff` and want to try yellow `#ff0` which is more convenient than changing `#ffffff` to `#ffff00`.

These examples may be trivial, but I feel that the result would just be text that *jumps around* and causes distractions.

**Comment by vjeux** [comment]
In js, prettier normalizes hexadecimal numbers to be lowercase, so it makes sense to follow suit in CSS.

I agree that normalizing 3 vs 6 seems out of scope and likely going to create a lot of drama for something that doesn't really matter. Another thing that people would likely want is to replace hex values with named colors when they exist. I think that both are better implemented as lint rules with autofix.

**Comment by vjeux** [comment]
If someone is interested in sending a pr to lowercase hexadecimal colors, that would be very welcomed

**Comment by bardware** [comment]
> I'd be a bit opposed on normalizing 3 vs 6 though

as 6 HEX digits ist most precise I prefer it over named colors (except for black, white, red, yellow, green, cyan; the very basic ones)

**Comment by jitendravyas** [comment]
This has been added but is there any benefit of this feature?

**Comment by lydell** [comment]
@jitendravyas Only adjusting the case has been implemented, and the length of the colors was decided to be out of scope, so no need to worry!

**Comment by jitendravyas** [comment]
ok does case even matter in source files? this can be done by minifier too. but that is just my opinion

**Comment by mafredri** [comment]
@jitendravyas it can matter. Generally programmers tend to prefer consistency and having a mix of upper / lower case hex colors can be a serious hit for someones OCD. A purpose of prettier is to eliminate style discussions, and I believe this does just that.

**Comment by lydell** [comment]
Yes, case matters! By enforcing case, Prettier takes away yet one item from pointless code style debates between programmers. Besides, Prettier already enforces case for hexadecimal numbers in JS, as an example. What a minifier can and can’t do has nothing to do with prettier.

**Comment by jitendravyas** [comment]
@mafredri I didn't get meaning of this line

` colors can be a serious hit for someones OCD.`

**Comment by mafredri** [comment]
@jitendravyas OCD - Obsessive–compulsive disorder. A trait that programmers often have, the need for things to be consistent, in order, aligned, etc.

In other words, mixing upper and lower case can bother someone who wants everything to be consistent. This results in meaningless discussions and arguments about what is essentially personal preferences.

**Comment by jitendravyas** [comment]
Thanks for the explanation. I never came across anyone online and offline who has preference over the color case. People bother about how code formatting, tabs vs space etc but never seen the color case.

But anyway. It's good to have it. But this path has got me thinking that many case related rules of stylelint can be added in Prettier. One of the rule is this https://stylelint.io/user-guide/rules/unit-case/

**Comment by lydell** [comment]
@jitendravyas Good point! I guess all rules ending with `-case` on https://stylelint.io/user-guide/rules/ are potential candidates for Prettier.

**Comment by jitendravyas** [comment]
Should I create issue for every rule in Prettier repo? or a single issue for all `-case` rules?

**Comment by azz** [comment]
Just one please.

**Comment by jitendravyas** [comment]
ok. but in the case of a single issue for the multiple suggestion, we won't be able to close the issue before implementing every rule team decide to implement

**Comment by lydell** [comment]
That’s not a problem.

- [x] We can
- [x] have a checklist
- [ ] in it
