### ISSUE TITLE
Comment after class member not printed when using TypeScript parser

### ISSUE THREAD

**Issue by fortes** [prettier/prettier#2141]
Input:

```
class myClass {
  foo/*hi*/() {
  }
}
```
Repro: 
https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20myClass%20%7B%5Cn%20%20foo%2F*hi*%2F()%20%7B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks for the report and sorry about that, we need to fix it! You can move the comment a bit or add // prettier-ignore on the line before to workaround for now.

**Comment by azz** [comment]
This is an issue with both `flow` and `typescript` parsers and affects both object methods and class methods.
