### ISSUE TITLE
Object property `'__'` gets rewritten to `___` in TypeScript parser

### ISSUE THREAD

**Issue by fortes** [prettier/prettier#2143]
Input:

```
obj = {                                                                               
  '__': 42 
};                                                                                                      
```

Output (note extra underscore, there are now three instead of the original two):

```
obj = {
  ___: 42,
};
```

Repro: https://prettier.github.io/prettier/#%7B%22content%22%3A%22obj%20%3D%20%7B'__'%3A%2042%7D%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks for the report and so sorry about that, we need to fix it. You can add // prettier-ignore on the line before to workaround for now.

**Comment by azz** [comment]
We had the same thing here: https://github.com/eslint/typescript-eslint-parser/issues/296, we'll get it fixed there.

**Comment by azz** [comment]
Raised it here: https://github.com/eslint/typescript-eslint-parser/issues/328
