### ISSUE TITLE
prettifying Typescript breaks some imports.

### ISSUE THREAD

**Issue by nikmartin** [prettier/prettier#2145]
In order to use the Google Maps API in Typescript, you have to do:
`import {  } from '@types/googlemaps';`, 
but when formatting with prettier, gets re-written as 
`import '@types/googlemaps';` 
which then throws  a module not found error on compile. I'm using the atom-prettier module which uses prettier 1.4.4

**Comment by vjeux** [comment]
Thanks! We need to fix this! You can add // prettier-ignore on the line before to workaround for now. Sorry about it
