### ISSUE TITLE
TSEP commit no longer available

### ISSUE THREAD

**Issue by JamesHenry** [prettier/prettier#2154]
I'm really sorry @vjeux @azz, I rebased the `ts-2.4` branch instead of merging in master and so this had the effect of redoing all the commit hashes.

The commit `6da23fd004ea60b84a5cfff469c89e93c0770b6f` currently in use on master of prettier no longer exists.

This will be solved by completing this WIP PR:
https://github.com/prettier/prettier/pull/2153

The only breaking test is not semantically meaningful so maybe we should just go ahead and merge it?

**Comment by JamesHenry** [comment]
I have added a note to the TSEP to try and avoid this happening again: https://github.com/eslint/typescript-eslint-parser/pull/326#issuecomment-308812622

**Comment by SimenB** [comment]
Why not just push betas to the npm registry? Those are immutable

**Comment by JamesHenry** [comment]
@SimenB No NPM users will be affected by this issue, only people installing prettier from the very latest commit on master

**Comment by SimenB** [comment]
Sure, but publishing a pre-release to npm isn't that much work.

**Comment by vjeux** [comment]
Don't worry about that, having specific commits is fine and I agree it's better than a branch as we don't want it to magically update.
