### ISSUE TITLE
Added commas, invalid JavaScript

### ISSUE THREAD

**Issue by JustenRickert** [prettier/prettier#2157]
I was playing around with passing functions as arguments, and found that when line length is too high the arguments split across lines (which is great!) but prettier adds an additional comma after the last argument, causing a syntax error. This happens only when the line length becomes too high.
```javascript
let identity = x => x;
let multiply = c => x => c * x;
let divide = d => x => x / d;
let duplicateInArray = x => [x, x, x, x, x];
let curryMap = f => x => x.map(f);

let y = compose(
  identity,
  multiply(2),
  divide(3),
  duplicateInArray,
  curryMap(divide(15)), //Note the comma added here
)(5);
```

**Comment by karl** [comment]
@JustenRickert Are you able to recreate this in the Prettier playground (https://prettier.github.io/prettier/)?

When I try your example above Prettier removes the trailing comma:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20identity%20%3D%20x%20%3D%3E%20x%3B%5Cnlet%20multiply%20%3D%20c%20%3D%3E%20x%20%3D%3E%20c%20*%20x%3B%5Cnlet%20divide%20%3D%20d%20%3D%3E%20x%20%3D%3E%20x%20%2F%20d%3B%5Cnlet%20duplicateInArray%20%3D%20x%20%3D%3E%20%5Bx%2C%20x%2C%20x%2C%20x%2C%20x%5D%3B%5Cnlet%20curryMap%20%3D%20f%20%3D%3E%20x%20%3D%3E%20x.map(f)%3B%5Cn%5Cnlet%20y%20%3D%20compose(%5Cn%20%20identity%2C%5Cn%20%20multiply(2)%2C%5Cn%20%20divide(3)%2C%5Cn%20%20duplicateInArray%2C%5Cn%20%20curryMap(divide(15))%2C%20%2F%2FNote%20the%20comma%20added%20here%5Cn)(5)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

I wonder if you are running Prettier with `--trailing-comma all`?

**Comment by luftywiranda13** [comment]
@JustenRickert run with flag `--trailing-comma es5`

**Comment by JustenRickert** [comment]
Alright. I found my problem. `prettier --help` tells me that `--trailing-comma` defaults to none, but Emacs was defaulted to all.
