### ISSUE TITLE
TypeScript regression: interface function (new) is split when comment is present

### ISSUE THREAD

**Issue by mafredri** [prettier/prettier#2163]
This regression is present on the master branch, a git bisect reveals the offending commit to be: 9c608d2ec11343cce4bb0b488ab5a228b2c7fa06.

**Input:**

```typescript
interface TimerConstructor {
  // Line-splitting comment
  new (interval: number, callback: (handler: Timer) => void): Timer;
}
```

**Output:**

```typescript
interface TimerConstructor {
  // Line-splitting comment
  new (
    interval: number,
    callback: (handler: Timer) => void
  ): Timer;
}
```

**Expected:**

No change between input and output.

Reproduction link can be found [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22interface%20TimerConstructor%20%7B%5Cn%20%20%2F%2F%20Line-splitting%20comment%5Cn%20%20new%20(interval%3A%20number%2C%20callback%3A%20(handler%3A%20Timer)%20%3D%3E%20void)%3A%20Timer%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D).

**Comment by azz** [comment]
I can minimize the repro down to this:

Input:
```ts
interface T {
  //
  (i): T;
}
```

Output:
```ts
interface T {
  //
  (
    i
  ): T;
}
```

**Comment by azz** [comment]
Thanks for the bisect, by the way! Definitely speeds up the fix.
