### ISSUE TITLE
Daisy-chain indentation bad for reading

### ISSUE THREAD

**Issue by rasenplanscher** [prettier/prettier#2164]
Formatting daisy-chains with `prettier`, I get structures like this:
```js
alpha
    .cooker(function(1) {
        some
            .thing()
            .should()
            .happen();
        elsewhere
            .some_other_thing()
            .should()
            .happen();
    })
    .thenclose();
beta(zeta);
omega
    .cage(function() {
        random
            .things()
            .should()
            .happen();
        elsewhere
            .some_other_thing()
            .should()
            .happen();
    })
    .thendie();
```
When scanning code like this, I will be halted by the lines before `.thenclose` and `.thendie`. The problem here being that it looks like something is missing. Of course, it's easy to read up the stream and find that everything checks out. But we all know, that in practice, code is rarely so simple. And if you throw an arrow function or two in there, it's not trivial to determine what's going on where. And that is a real performance leech in my view.

What I'd like to see, is this:
```js
alpha
.cooker(function() {
    some
    .thing()
    .should()
    .happen();

    elsewhere
    .some_other_thing()
    .should()
    .happen();
})
.thenclose();

beta(zeta);

omega
.cage(function() {
    random
    .things()
    .should()
    .happen();

    elsewhere
    .some_other_thing()
    .should()
    .happen();
})
.thendie();
```
Everything closes nicely and is seen on the level of indentation where actually happens. Can this be at least an option?

**Comment by k15a** [comment]
I don't think that we will change this behavior. Indenting the lines like we do is way more popular and changing this behavior break prettier for many people.

**Comment by azz** [comment]
@k15a agreed. Prettier is past 1.0 now and won't be making significant changes to the way method chains are formatted. 

@rasenplanscher I would suggest raising this formatting idea with [prettier-miscellaneous](https://github.com/arijs/prettier-miscellaneous), who may be interested in adding an option for it.

**Comment by ifeltsweet** [comment]
I completely agree with @rasenplanscher. That's how I format my code also. Consider another example and see for yourself which one is easier to read and makes more sense:

```js
http({
  type: 'POST',
  url: '/bans',
  data: {entity: entity, value: value, type: type, duration: duration},
})
  .then(function(response) {
    publish('bans.created', response);
  })
  .catch(function() {
    publish('bans.create-failed');
  });
```

```js
http({
  type: 'POST',
  url: '/bans',
  data: {entity: entity, value: value, type: type, duration: duration},
})

.then(function(response) {
  publish('bans.created', response);
})

.catch(function() {
  publish('bans.create-failed');
});
```

**Comment by jwalton** [comment]
I'm happy to make that a PR for prettier itself.  Seems like a popular option.

**Comment by jwalton** [comment]
I'm just going to note here that js-beautify has `--unindent-chained-methods`.  :P

**Comment by j-f1** [comment]
@jwalton 6 👍s isn’t really a popular request. #2676 is a popular request (62 👍 - 12 👎 = 50 👍).

**Comment by jwalton** [comment]
Yes, but *I* want it.  :P :P :P

**Comment by jwalton** [comment]
And I'm happy to do the work to support it.
