### ISSUE TITLE
case of poor assignment layout

### ISSUE THREAD

**Issue by jasonkuhrt** [prettier/prettier#2184]
This nice-ish code:

```js
const areaPercentageDiff = (
    topRankedZoneFit.areaPercentageRemaining
  - previousZoneFitNow.areaPercentageRemaining
).toFixed(2)

```
gets formatted into uglier code:

```js
const areaPercentageDiff = (topRankedZoneFit.areaPercentageRemaining -
  previousZoneFitNow.areaPercentageRemaining).toFixed(2);
```

**Comment by azz** [comment]
It [doesn't respect print width](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20areaPercentageDiff%20%3D%20(%5Cn%20%20%20%20topRankedZoneFit.areaPercentagRemaining%5Cn%20%20-%20previousZoneFitNow.areaPercentageRemaining%5Cn).toFixed(2)%22%2C%22options%22%3A%7B%22printWidth%22%3A60%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) either.

**Comment by duailibe** [comment]
FTR this is now printing:

```js
const areaPercentageDiff = (topRankedZoneFit.areaPercentageRemaining -
  previousZoneFitNow.areaPercentageRemaining
).toFixed(2);

**Comment by duailibe** [comment]
This now prints as:

**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDATnbABTlzARmwHM4ARASwDMHMBeTACgB0pNfMYIABwBK2KAGs4AEwBa0OADE6MAHR4CxUuSpxhcALbY6UY5W68AtJkH4AbnQgBXNHKiLlAOQgB3NfiIkZLA6eobGptwAlCoCSgAe0uwATJHcIAA0IEIwDlBoyKB4uD6E6nnIINi2EHRSGZUYyAzYADZocJkARrjYYJIwAMqCvabIMLiOHSBSEGBNre2Zxu24MIQ9lIbzbVMAVmhxAEI9fXCD2PpwADLGcNuLWY4wgk9J91PDuCsVndidAJ4taD1GzGGAAdVqMAAFsgABwABkyNgg7XBPUEFRscBWtjumXwAEdHHR8OsqFskM0dpl2vo6GMJlM0KYWnAAIqOCDwd6ZCidSFSGHIJJ8np0FqmADCEH0lJAUHk9WccAAKn98lSFnAAL46oA)

**Input:**
```jsx
const areaPercentageDiff = (
    topRankedZoneFit.areaPercentageRemaining
  - previousZoneFitNow.areaPercentageRemaining
).toFixed(2)

```

**Output:**
```jsx
const areaPercentageDiff = (
  topRankedZoneFit.areaPercentageRemaining -
  previousZoneFitNow.areaPercentageRemaining
).toFixed(2);

```

Which is pretty similar to the input, except for where the `-` sign stays (end of line / start of next line) but I guess the primary issue was fixed.. if anyone dislikes the `-` placement, please open a new issue :-)
