### ISSUE TITLE
"Projects using prettier" images are broken on yarnpkg.com

### ISSUE THREAD

**Issue by azz** [prettier/prettier#2186]
The icons are not loaded when the readme is viewed on https://yarnpkg.com/en/package/prettier.

I'm not sure if this is fixable. Maybe use absolute URLs?

Screenshot:
> ![image](https://user-images.githubusercontent.com/1297597/27258194-98a9efb8-5437-11e7-9a5a-844ef6dbf401.png)

Document:
> ![image](https://user-images.githubusercontent.com/1297597/27258203-d2cdcbd8-5437-11e7-9616-436285a2ece8.png)

**Comment by vjeux** [comment]
cc @bestander

**Comment by bestander** [comment]
Opened issue on yarn

**Comment by vjeux** [comment]
This is now working :)
