### ISSUE TITLE
Breaks My Code, and Alt + Control + F broken on OSX

### ISSUE THREAD

**Issue by bradennapier** [prettier/prettier#2191]
The comma dangles fails for anonymous arrow functions

```js
module.hot.accept('./routes', () => {
    import('./routes',).then((routes) => {
      RenderApp(Root, routes.default)
    })
  })
```
**-->**
```js
module.hot.accept('./routes', () => {
    import('./routes',).then(routes, => {
      RenderApp(Root, routes.default,);
    },);
  },);
```

it added a comma to the then statement after routes, breaking it completely.

Additionally I can not use the keyboard shortcut on atom -- have to right click and select the option to format 

Is there plans to support promises?  Kind of crazy it doesn't.  Other than that this seems awesome.

**Comment by vjeux** [comment]
This is likely not prettier doing. Can you tell me what you have installed, what versions and what you are doing to get to this point? Thanks!

**Comment by bradennapier** [comment]
I installed atom then i installed the package.  Zero other changes or anything going on .  It ONLY happens when I tell prettier to format.

**Comment by bradennapier** [comment]
I noticed that even though i hhave trailing commas (all) it does not work:

![image](https://user-images.githubusercontent.com/15365418/27265372-53d7c448-5449-11e7-9906-bcbbf326f5fa.png)

When I have that no trailing commas will be added at any point.

Only when enabling eslint integration does it work -- however then it breaks everything as shown.

**Comment by bradennapier** [comment]
Hmm this is weird - it actually works perfectly on other files, just not this one.  I'll dig deeper.  Working awesome .  The shortcut does not work still though.

**Comment by vjeux** [comment]
Can you try on the playground? https://prettier.github.io/prettier/

If you can get a repro that would be helpful
