### ISSUE TITLE
not-so-pretty output, function call followed by operators

### ISSUE THREAD

**Issue by daintycode** [prettier/prettier#2192]
**Input, looks quite good imho**
```JS
var angle = Math.floor(
	Math.atan2(
		entity.gridY - this.gridY,
		entity.gridX - this.gridX
	) * 180 / Math.PI
);
```
**Prettier Output**
```JS
var angle = Math.floor(
	Math.atan2(entity.gridY - this.gridY, entity.gridX - this.gridX) *
		180 /
		Math.PI
);
```

**Comment by vjeux** [comment]
Agreed, the input looks better and the output worse. I'm not really sure how to fix it though. Prettier doesn't know how to print the first form and making it know about it would change a bunch of other things. I'll think about it but right now you'll have to live with it i'm afraid :(

**Comment by lydell** [comment]
```js
function toDegrees(radians) {
  return radians * 180 / Math.PI;
}

var dx = entity.gridX - this.gridX;
var dy = entity.gridY - this.gridY;
var angle = Math.floor(toDegrees(Math.atan2(dy, dx)));
```

**Comment by vjeux** [comment]
I'm going to close this since I don't really know how we can gracefully handle this case :(
