### ISSUE TITLE
leading chained method does not indent

### ISSUE THREAD

**Issue by jasonkuhrt** [prettier/prettier#2199]
```js
const create = (
  queue: AWS.SQS,
  queueSettings: AWS.SQS.ReceiveMessageRequest,
): Most.Stream<Job> =>
  Most.periodic(secondsToMilliseconds(queueSettings.WaitTimeSeconds))
    .map(() => pull(queue, queueSettings))
    .await()
    .concatMap(({ Messages }: AWS.SQS.ReceiveMessageResult) =>
      Most.from(Messages.map(parseMessage).map(createJob)),
    )
    .multicast()
```
Would read better as:

```js
const create = (
  queue: AWS.SQS,
  queueSettings: AWS.SQS.ReceiveMessageRequest,
): Most.Stream<Job> =>
  Most
    .periodic(secondsToMilliseconds(queueSettings.WaitTimeSeconds))
    .map(() => pull(queue, queueSettings))
    .await()
    .concatMap(({ Messages }: AWS.SQS.ReceiveMessageResult) =>
      Most.from(Messages.map(parseMessage).map(createJob)),
    )
    .multicast()
```

**Comment by azz** [comment]
The heuristic is if the identifier (here `Most`) starts with an uppercase letter, it is probably a factory of some sort (like `Promise.resolve()`), which it looks like `Most` is in this case.

You can actually get around this behaviour by doing:

```patch
-import * as Most from "most";
+import * as most from "most";

const create = (
  queue: AWS.SQS,
  queueSettings: AWS.SQS.ReceiveMessageRequest,
): Most.Stream<Job> =>
-  Most.periodic(secondsToMilliseconds(queueSettings.WaitTimeSeconds))
+  most
+   .periodic(secondsToMilliseconds(queueSettings.WaitTimeSeconds))
    .map(() => pull(queue, queueSettings))
    .await()
    .concatMap(({ Messages }: AWS.SQS.ReceiveMessageResult) =>
      Most.from(Messages.map(parseMessage).map(createJob)),
    )
    .multicast()
```
[(link)](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20create%20%3D%20(%5Cn%20%20queue%3A%20AWS.SQS%2C%5Cn%20%20queueSettings%3A%20AWS.SQS.ReceiveMessageRequest%2C%5Cn)%3A%20Most.Stream%3CJob%3E%20%3D%3E%5Cn%20%20most.periodic(secondsToMilliseconds(queueSettings.WaitTimeSeconds))%5Cn%20%20%20%20.map(()%20%3D%3E%20pull(queue%2C%20queueSettings))%5Cn%20%20%20%20.await()%5Cn%20%20%20%20.concatMap((%7B%20Messages%20%7D%3A%20AWS.SQS.ReceiveMessageResult)%20%3D%3E%5Cn%20%20%20%20%20%20Most.from(Messages.map(parseMessage).map(createJob))%2C%5Cn%20%20%20%20)%5Cn%20%20%20%20.multicast()%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by azz** [comment]
Completely tangential, I really wish Amazon had an option to use camelCased properties on their SDK. The XML that these objects get translated to actually have camel cased tags 😞.

**Comment by jasonkuhrt** [comment]
@azz Thanks for the prompt feedback!

@azz Snide solution: Use GCP and live happier life.

> The heuristic is if the identifier (here Most) starts with an uppercase letter, it is probably a factory of some sort (like Promise.resolve()), which it looks like Most is in this case.

I use uppercase identifiers as for namespaces as you would see in `Go` `Haskell` `Reason` and many other languages. Regardless of the casing, and regardless of "namespace" or "factory", why should the leading `.<method>` not be put on its own line? I suggest a good heuristic for this is:

* If there is a single `.<method>` and it fits on same line, put on same line
* Otherwise newline + indent (I would actually even maybe prefer no ident but that's a separate issue and I care less about it)

**Comment by azz** [comment]
Because this looks funny:

```js
Promise
  .resolve()
  .then(something)
  .then(somethingElse);
```

People tend to write:

```js
Promise.resolve()
  .then(something)
  .then(somethingElse);
```

More examples:

```js
Rx.Observable.fromEvent(someElement, "click")
  .throttle(200)
  .subscribe(doSomething);
```

Or

```js
_.chain(matrix)
  .flatMap(foo)
  .reduce(add)
  .value();
```

**Comment by jasonkuhrt** [comment]
```

**Comment by jasonkuhrt** [comment]
### Warning: Bike Sheds Ahead


> Because this looks funny:

```js
Promise
  .resolve()
  .then(something)
  .then(somethingElse);
```
^ IMHO looks great to me. It is a computational pipeline along the lines of functional composition, I don't see anything silly here personally.

```js
Rx.Observable.fromEvent(someElement, "click")
  .throttle(200)
  .subscribe(doSomething);
```
^ IMHO worse than silly this is just plain harder to read. Personally I would write this as:

```js
Rx
  .Observable
  .fromEvent(someElement, "click")
  .throttle(200)
  .subscribe(doSomething);
```

Which once again captures the functional pipeline nature (and some namespace access, fine) and is easy on the eyes because incremental steps follow along a single dimension.


```js
_
  .chain(matrix)
  .flatMap(foo)
  .reduce(add)
  .value();
```
^ Silly because `_` is not a great identifier. Use almost anything else and its fine. `F` or `L` or whatever.

**Comment by vjeux** [comment]
This is indeed not ideal but it's the best we could find. At this point, we don't have a better ideas on how to make it better so I'm going to close this issue. Thanks for the report!

**Comment by jasonkuhrt** [comment]
> This is indeed not ideal but it's the best we could find.

Do you mean there is a technical limitation preventing adoption of the suggestion in this issue, or rather the community has decided this is the best style all things considered?

**Comment by vjeux** [comment]
We started by implementing the suggestions you put last (which is the easiest way so solve the problem at a technical level) but got so many reports by people saying that it's not how they format their code.

With the current version of prettier, the only complains we get are from people that are using some custom libraries and most of the time the output is a bit weird but not terrible.

So it feels like a good trade-off. It's not perfect for sure but we're unfortunately not going to reach perfection when formatting all the code automatically.

**Comment by jasonkuhrt** [comment]
@vjeux Great context to have thanks! 

> So it feels like a good trade-off. It's not perfect for sure but we're unfortunately not going to reach perfection when formatting all the code automatically.

Is there a strategy that dictates when a formatting style warrants inclusion but only opt-in via a setting. For example this is the case with semi-colons. From your report of it my taste here is niche here so maybe its not a valid case, but in theory this feature could be made available on an opt-in basis no? Again I realize its a tradeoff for the complexity of `prettier`, more things to support, test, maintain, etc.

**Comment by vjeux** [comment]
The ultimate goal of prettier is to have no options. Unfortunately, it's not achievable in practice because there are so many ways of writing code in the wild, so we settled on only adding options that are in the camp "if this isn't printed like this, i'm never going to use prettier". Space vs tabs, semi vs no-semi are in this camp. There are subtle ones like bracket spacing and where do put the `>` in jsx which are also great debates.

This one doesn't fall into this bucket so we're not going to support it, I'm sorry. There's a project called "prettier-miscellaneous" that attempts to cover many options people are asking ( https://github.com/arijs/prettier-miscellaneous ), which may be a recourse for you.

**Comment by jasonkuhrt** [comment]
@vjeux clear! Thanks
