### ISSUE TITLE
nested ternaries don’t look prettier after formatting

### ISSUE THREAD

**Issue by davidaurelio** [prettier/prettier#2202]
When using nested ternaries for selection like this:

```js
const thing = 
    condition === 1 ? 'the a thing' :
    condition === 2 ? 'the b thing' :
    condition === 3 ? 'the c thing' :
    'the default thing';
```

prettier’s output is

```js
const thing = condition === 1
  ? "the a thing"
  : condition === 2
    ? "the b thing"
    : condition === 3 ? "the c thing" : "the default thing";
```

which I find a lot less readable than the input. Is there any way to support this particular use case?

**Comment by kjbekkelund** [comment]
There is some discussion about this in https://github.com/prettier/prettier/issues/737

**Comment by lydell** [comment]
Thanks for your issue! Merging with #737.
