### ISSUE TITLE
Support .babelrc

### ISSUE THREAD

**Issue by zimme** [prettier/prettier#2206]
It would be awesome if prettier's babylon parser would respect `.babelrc`, this way I can just add `parserOpts` to enable `allowImportExportEverywhere` instead of having to use my own custom parser.

I'm thinking we should be able to use the config loading utilities from `babel-core`.

https://github.com/babel/babel/blob/0eae6a432c344759b5869144d4f1bd0b4145cd05/packages/babel-core/src/config/option-manager.js

https://github.com/babel/babel/blob/0eae6a432c344759b5869144d4f1bd0b4145cd05/packages/babel-core/src/config/loading/files/configuration.js

**Comment by vjeux** [comment]
For parsers we're trying to parse as many things as possible. Can you send a PR to make prettier turn this option on?

**Comment by zimme** [comment]
That sounds good to me, I just assumed that this wasn't an option as nested imports isn't really adopted by the wider javascript community yet. I'm not sure if it's been decided if it's gonna get into the spec, however I am hopeful.

I'll create a PR for that instead for now.

Should I keep this issue open if we wanna support `.babelrc` in the future or should we close?

**Comment by vjeux** [comment]
If this is the only thing that's blocking you, we should close this issue :) If someone else have some other issue with babelrc, we should look at it case by case.
