### ISSUE TITLE
Respect paren + newline

### ISSUE THREAD

**Issue by ryanflorence** [prettier/prettier#2208]
Hi friends!

Been using prettier full time for a while now and it's prettier great. I'd like to request one change that I think makes refactoring less error prone: respect `(` + newline the same way `if {` + newline is treated.

```js
// prettier maintains the block
if (foo) {
  doStuff()
}

// but changes this:
if (foo)
  doStuff()

// to this:
if (foo) doStuff()
```

I think doing the same for multi-line expressions (which happen all the time in JSX) would be equally beneficial. Since using prettier, I am getting *a lot more syntax errors* as I refactor my code because it puts the code on the same lines as the syntax. JSX is the most affected part in my code since it's expression heavy, and also the most likely to be moved around as you build and refactor a UI.

## Some examples

For example, consider this code:

```jsx
const Slider = ({ isOpen, title, children }) => (
  <div>
    <h1>{title}</h1>
    {isOpen && (
      <div>
        {children}
      </div>
    )}
  </div>
);
```

Prettier changes it to:

```jsx
const Slider = ({ isOpen, title, children }) =>
  <div>
    <h1>{title}</h1>
    {isOpen &&
      <div>
        {children}
      </div>}
  </div>;
```

If I am refactoring and move the `<div/>` somewhere else, maybe I'm inlining it into a different component, that semi-colon comes along with the div leading to syntax errors or in this case just a printed `;` in the UI if you don't catch it.

![semicolon](https://user-images.githubusercontent.com/100200/27356345-7627a630-5651-11e7-947c-6a4c9af47446.gif)

Additionally, the closing `}` in the `isOpen` block gets put on the same line as the closing div, so refactoring that block is more likely to result in accidental syntax errors:

![closing-curly](https://user-images.githubusercontent.com/100200/27356701-e0f71d3c-5652-11e7-8972-5253de5ad370.gif)

## If parens were respected like if block curlies

However, if the parens were respected (just like if block's curlies) we can just move stuff around w/o spending extra time adjusting syntax.

![closing-curly2](https://user-images.githubusercontent.com/100200/27357375-4f0fe6e4-5655-11e7-9809-eaf318d33c4e.gif)

![semicolon2](https://user-images.githubusercontent.com/100200/27357711-b7c96e48-5656-11e7-9bf1-40d5bebe418f.gif)

Ternaries are also much easier to work with if the parens are respected:

![ternary](https://user-images.githubusercontent.com/100200/27357409-6eec1514-5655-11e7-9100-3953ff5436fe.gif)

As compared to not respecting them:

![ternary-hard](https://user-images.githubusercontent.com/100200/27357428-7744756c-5655-11e7-8887-f9797a7824a7.gif)

I am not proposing prettier *insert parens and new lines* but rather, do what it does today, except when a developer puts a paren + newline in, respect it the same way an `if {` is respected.

Thanks! 💙💙💙

**Comment by vjeux** [comment]
Fwiw, this is the way I move things around.

![](http://g.recordit.co/C54gbwSbXO.gif)

**Comment by nilliams** [comment]
I would like to add avoiding stuff like:
```
</div>}
```
... also makes for better diffs.

Otherwise, adding 1 line below `</div>`, inside `}` results in a 2 line diff:
```diff
- </div>}
+ </div>
+ <h2>New element!</h2>}
```

**Comment by vjeux** [comment]
@nilliams your diff is not valid JSX, you can't have two JSX elements next to each others without a wrapper.

**Comment by ryanflorence** [comment]
@vjeux some people can't use a mouse. Also, respecting parens still allows you to do the same thing you are right now.

**Comment by mjackson** [comment]
I just wanted to chime in here and say that, for whatever it's worth, this is the single biggest thing keeping me from using prettier from day to day. If prettier would respect my use of `(` + `\n`, I'd definitely use it.

**Comment by nilliams** [comment]
@vjeux Oops, you're right, sorry it's late. (Deleted to remove noise).

**Comment by thelastnode** [comment]
+1!

This would also help with making `collection.map(x => ...)` more legible:

```javascript
{things.map(
  thing =>
    somePredicate ? <div>Some stuff</div> : <div>Some other stuff</div>
)}

// vs

// closer to an if-else, easier to logically group
{things.map(thing =>
  somePredicate ? (
    <div>Some stuff</div>
  ) : (
    <div>Some other stuff</div>
  )
)}
```

I've also noticed that diffs are easier to read in this style, especially with GitHub intra-line highlighting.

**Comment by devinrhode2** [comment]
Why wouldn't prettier make the unilateral decision to have delimiters added or removed in certain situations? I thought the goal of prettier was to alleviate engineers from spending time on this sort of stuff. And maybe it's easier/cleaner/simpler to implement.

There are good reasons to stick to @ryanflorence's style in the examples he presents. Can anybody come up with counter examples where you'd really want the current style?

**Comment by suchipi** [comment]
I've generally only run into this issue when dealing with JSX, but that might just be because ternaries and wrapping parens are more common in JSX.

That said, it does feel like the "one last thing" that makes prettier feel not-quite-ready-yet, at least for projects using JSX.

**Comment by aaronjensen** [comment]
@ryanflorence does your atom vim emulation have the tag text object? `dat` is a nice way to move tags around in vim or vim emulated editors. At least in spacemacs, it doesn't work to `vat` and move the lines up/down like you do in your picture as it drags the curly along w/ it, but deleting it then pasting elsewhere works fine. Obviously breaking muscle memory is hard, I've seen you move text around in that way in talks and such, so I know you prefer it 😄 

I personally prefer ensuring consistent (removal of unnecessary) paren usage, but I wouldn't be angry if prettier respected some of them in certain situations.

**Comment by lydell** [comment]
I like and use Prettier a lot, but when reading this I realized that I often mess up my `}`s and `;`s in JSX: Sometimes leaving a `;` behind in the output, and sometimes concentrating hard on matching up those brackets. Not sure what the best solution is, but there's definitely a problem.

**Comment by btnwtn** [comment]
This is especially painful with vim and emacs and other non-mouse based text editors.

**Comment by taylorham** [comment]
This change would also have the added benefit of keeping clear and consistent indentation with closing parens/braces.

**Comment by EnoahNetzach** [comment]
Fwiw, even with a mouse it's still easier to select maintaining parens + `\n`:  from the end of the opening paren to the last line, no need to be precise with starting or ending point, no extra parens copied.

**Comment by AlteredConstants** [comment]
For those unfamiliar, the first example is actually the result of a recent change which some people were not thrilled about, [myself included](https://github.com/prettier/prettier/pull/1733#issuecomment-306737591). The idea seems to be to remove parens everywhere possible, consistently, but I'm unclear on the motivation for that. At least for me, this seems to ignore important semantics/conventions (e.g. Airbnb style) which this issue and @taylorham's "spidey-sense" are specific manifestations of. 

I'd personally still like to see parens auto-included for all multi-line expressions (with possible, unconditional exceptions?) rather than conditionally maintaining them, but I would appreciate the consistency with curly-brace blocks in this proposal.

**Comment by ryanflorence** [comment]
@vjeux how do these things get decided? What does the "needs discussion" label mean? I have no idea if 50 👍's on the issue means anything, but I'm hopeful. I'm really excited about prettier with this one small adjustment.

**Comment by suchipi** [comment]
For semicolons, it seemed like the pattern was "people discussed it for ages, then someone made a PR that just added it, and it got merged"...

**Comment by skovhus** [comment]
To me Ryans suggestion will also make it easier to review changes, as the diff for moving a block around will not contain noise bracket modifications.

**Comment by ericclemmons** [comment]
It sounds like my issue #2180 is similar.

**Comment by vjeux** [comment]
Could someone try to implement parenthesis with ?: as displayed in the original post within prettier to see how it would look?

**Comment by suchipi** [comment]
@vjeux I haven't looked at prettier's codebase enough to know what things are hard and what are easy, but would this heuristic work?
```
When I'm about to print a JSX expression
If the expression is currently multiline
Wrap it in parentheses
```
or if that's too hard:
```
When I'm about to print a JSX expression
If the expression is not a self-closing tag
Wrap it in parentheses
```
This would cover JSX arrow expressions and JSX expressions in ternaries, which seem to be the most common case.

@ryanflorence is asking for "leave parens around if I put them there", but my understanding is that this is nontrivial to do in prettier (particularly because parens aren't a node in the AST). Is that correct?

This isn't the first time I wished Babylon had a nonstandard node for parens just so you could differentiate this type of situation. If it did, then implementing what Ryan is asking for would probably be what had happened anyway.

**Comment by vjeux** [comment]
I don't think that the solution of putting parenthesis if the user inputted them or dropping them if not is great. It's going to introduce inconsistencies within a codebase and is just a crutch because we want to support two different opinions.

I've been quiet on this because I was focused on other things (TypeScript, CSS, GraphQL, CSS-in-JS, Website, Facebook rollout) but now that those are in order, it's time to look into parenthesis and JSX as it's the last thing that people are heavily in disagreement with the current way prettier is printing code.

I would like to investigate how hard it would be to implement the following style for JSX and what are the unforeseen consequences.

```js
cond
  ? (
    <div>
      Text 1
    </div>
  ) : (
    <div>
      Text 2
    </div>
  )
```

Also I want to revisit dropping the parenthesis for arrow functions and figure in what other context JSX is being printed and if we need to do something about it.

**Comment by ryanflorence** [comment]
@vjeux a few "precendents" I see.

> I don't think that the solution of putting parenthesis if the user inputted them or dropping them if not is great. It's going to introduce inconsistencies within a codebase

Prettier already allows for this type of inconsistency, prettier leaves both of these alone:

```js
if (bool) {
  doStuff();
}

if (bool) doStuff();
```

But indeed, I'd be even happier if adding parens was the prettier opinion 😍

- Makes diffs easier to review
- Has nice "open/close" symmetry which leads to fewer refactoring syntax errors
- Removes the "broken indentation" look.
- Makes complex expressions look exactly like `if` `else if` `else` blocks with same number of lines, same position of lines, with a lot less syntax. A declarative if block, essentially.
- Has nice symmetry to component `render` method returns (that inserts parens if you leave them off)
- Gives editors some syntax to help you navigate around

I tried to dig in a little but I have very little experience with ASTs. I didn't really get anywhere and some other stuff is on my plate now.

> I would like to investigate how hard it would be...

Are you doing this investigation or do we need to try to find somebody?

> Also I want to revisit dropping the parenthesis for arrow functions

👍

**Comment by suchipi** [comment]
For what it's worth, I would usually write this:
```jsx
cond ? (
  <div>
    Text 1
  </div>
) : (
  <div>
    Text 2
  </div>
)
```
(`cond` on same line as as `?`).

But I don't want to bikeshed too much.

Here's the places where I (personally) find myself wanting parens around JSX:
* Arrow function with no block body that returns JSX. Parens go around returned expression
```jsx
const Something = ({ foo }) => (
  <div>
    {foo}
  </div>
);
```

* Arrow function with block body that returns JSX. Parens go around returned expression
```jsx
const Something = ({ foo }) => {
  const calculatedFoo = foo + 2;
  return (
    <div>
      {calculatedFoo}
    </div>
  );
};
```

* Render method returning JSX. Parens go around returned expression
```jsx
// (in class body)
render() {
  return (
    <div>
      {this.props.foo}
    </div>
  );
}
```

* Multiline JSX expression in a variable declaration made at some point. Parens go around the declarator's init
```jsx
// (in class body)
render() {
  const formattedFoo = (
    <div className="bla">
      {foo}
    </div>
  );

  return (
    <div>
      {formattedFoo}
    </div>
  );
}
```

When using a ternary within JSX (even if the ternary's consequent or alternate are *not* JSX)
```jsx
// in render method or functional component
const { isFoo, bar } = this.props;

return (
  <div>
    {isFoo ? (
      "Foo ()"
    ) : (
      <span>{bar}</span>
    )}
  </div>
);
```

When using a ternary in a React render method where the outermost expression is not JSX (and the ternary's consequent or alternate may or may not be JSX)
```jsx
// in render method or functional component
const { isFoo, bar } = this.props;

return isFoo ? (
  "Foo ()"
) : (
  <span>{bar}</span>
);
```

That last one is hard to detect, I know...

There might be more edge cases but these are what I can think of off the top of my head right now.

**Comment by vjeux** [comment]
> Are you doing this investigation or do we need to try to find somebody?

I'm heading to a ~2-week vacations in France, so hopefully trying to find somebody. But I'll be actively involved.

**Comment by vjeux** [comment]
The issue with

```js
cond ? (
  <div>
    Text 1
  </div>
) : (
  <div>
    Text 2
  </div>
)
```

is that it's different from the way we print ternaries everywhere else inside of prettier. But that's worth exploring.

**Comment by suchipi** [comment]
I'd personally be fine with changing all ternary printing for the sake of this use case... but I recognize that change might carry some heavy weight 😉 

I might be able to take a stab at this on July 4th.

**Comment by lydell** [comment]
I agree with @suchipi in that it’s worth testing out always printing multiline ternaries the @ryanflorence way, regardless of whether there’s JSX inside or not. Might turn out really nice (or not, but we’ll see).

**Comment by EnoahNetzach** [comment]
I'd say not if one or both expressions could be inlined: 

```javascript
cond
  ? a
  : b

cond
  ? a
  : (
    <div>
      text
    </div>
  )

cond
  ? (
    <div>
      text
    </div>
  ) : b
```

**Comment by suchipi** [comment]
I've made a PR that:
* Adds wrapping parens back to JSX Arrow functions (when the JSX is multiline):
```jsx
// Before
const MyThing = () =>
  <div>
    <span>Hi</span>
  </div>;

// After
const MyThing = () => (
  <div>
    <span>Hi</span>
  </div>
);
```
* Uses different formatting for `?:` when using JSX
```jsx
// Before
const MyThing = () =>
  <div>
    {isGood
      ? <div>
          <span>"yeah it's good"</span>
        </div>
      : isOkay ? <div>it's okay</div> : null}
  </div>;

// After:
const MyThing = () => (
  <div>
    {isGood ? (
      <div>
        <span>
          "yeah it's good"
        </span>
      </div>
    ) : isOkay ? (
      <div>it's okay</div>
    ) : (
      null
    )}
  </div>
);
```
* Adds wrapping parens when JSX is used in a logical expression: 
```jsx
// Before:
<div> 
  {a || <span />} 
</div>;

// After:
<div>
  {a || (
    <span />
  )}
</div>;
```

**Comment by drcmda** [comment]
@vjeux 

Is there a flag to switch this new formatting off? I thought it's a bug at first and landed here. I don't use vim and i have no problems refactoring. All i see is that suddenly it stretches code into something that i wouldn't call an improvement. 

![screen shot 2018-03-12 at 16 10 44](https://user-images.githubusercontent.com/2223602/37291893-f7049f9a-260f-11e8-9998-f199fccbee01.png)

![screen shot 2018-03-12 at 16 10 51](https://user-images.githubusercontent.com/2223602/37291902-fa1c4084-260f-11e8-9bea-9c48d58dde2f.png)

Essentially i had to switch off prettier - and it feels so weird to format by hand again. Maybe it's just the editor extension that's missing a setting or is this fixed now?

**Comment by rattrayalex** [comment]
@drcmda please move your comment to a new issue. (FWIW, I expect that issue will be closed, but it's helpful to be able to track community reaction – if lots of people agree with you, we may consider).
