### ISSUE TITLE
Odd indentation inside Boolean()

### ISSUE THREAD

**Issue by davidgilbertson** [prettier/prettier#2209]
Using prettier `1.4.4`

I have this code:
```js
const variableWithQuiteALongNameOne = true;
const variableWithQuiteALongNameTwo = true;
const variableWithQuiteALongNameThree = true;

const testObject = {
    everythingTrue: Boolean(
        variableWithQuiteALongNameOne &&
        variableWithQuiteALongNameTwo &&
        variableWithQuiteALongNameThree
    ),
};
```

which is formatted into:

```js
const variableWithQuiteALongNameOne = true;
const variableWithQuiteALongNameTwo = true;
const variableWithQuiteALongNameThree = true;

const testObject = {
    everythingTrue: Boolean(
        variableWithQuiteALongNameOne &&
            variableWithQuiteALongNameTwo &&
            variableWithQuiteALongNameThree,
    ),
};
```

It seems related to https://github.com/prettier/prettier/issues/1499 and https://github.com/prettier/prettier/issues/774 but wasn't fixed by commit https://github.com/prettier/prettier/commit/62679f20f0fa7f26115d9a23169e9baaea952971

The options I'm using are are `--tab-width 4 --single-quote --trailing-comma all`. It's treating those as a function argument I guess (hence the trailing comma).

It doesn't behave this way for `!!()`.

**Comment by azz** [comment]
The indentation is intentional, but maybe the indentation is only needed if there's more than one function argument?

```js
const testObject = {
    everythingTrue: Foo(
        variableWithQuiteALongNameOne &&
            variableWithQuiteALongNameTwo &&
            variableWithQuiteALongNameThree,
        variableWithQuiteALongNameOne &&
            variableWithQuiteALongNameTwo &&
            variableWithQuiteALongNameThree,
    ),
};
```

**Comment by davidgilbertson** [comment]
Oh I see, yes in the context of multiple args that indenting makes sense.

@azz IMO the indenting should be the same regardless of the number of args (the current behaviour). Otherwise, a change to add a second one would change the formatting of the first one.

**Comment by vjeux** [comment]
This is an interesting case. I'm not sure that we want to special case `Boolean` for this :x

**Comment by aboyton** [comment]
You could always use `!!` rather than `Boolean` if you wanted.

```js
const variableWithQuiteALongNameOne = true;
const variableWithQuiteALongNameTwo = true;
const variableWithQuiteALongNameThree = true;

const testObject = {
  everythingTrue: !!(
    variableWithQuiteALongNameOne &&
    variableWithQuiteALongNameTwo &&
    variableWithQuiteALongNameThree
  )
};
```

**Comment by azz** [comment]
This is a small issue that probably isn't worth adding more complexity to the Prettier for.
