### ISSUE TITLE
Prefer JSX string attributes over strings in the attribute value

### ISSUE THREAD

**Issue by ianobermiller** [prettier/prettier#2211]
Input:

```js
<Foo hello={"what's up"} />
```

Expected output:

```js
<Foo hello="what's up" />
```

It should ignore single quotes with a double quote inside and template literals.

**Comment by lydell** [comment]
Prettier has this rule not to change the AST. In the first case, the attribute value is a StringLiteral; in the second case it is a JSXExpressionContainer (_containing_ a StringLiteral). So while it is a nice idea, it falls out of scope for Prettier.

There has been talk about combining Prettier with AST transforms, but nothing's been done on that area yet. Perhaps there's an ESLint rule you can use?
