### ISSUE TITLE
Splitting generic type definition breaks syntax highlighting for TypeScript

### ISSUE THREAD

**Issue by egeozcan** [prettier/prettier#2212]
![code_2017-06-20_22-16-08](https://user-images.githubusercontent.com/185294/27371464-3dc4cd30-5661-11e7-8cf4-4b5c2f21c177.png)

According to Microsoft/TypeScript-TmLanguage#475 , this issue won't be fixed by TypeScript-TmLanguage authors. Maybe prettier can ignore max line length on this occasion? (Please see the linked issue for details).

Typescript type definitions can get pretty complicated. This will probably be an issue for most people using TS on VSCode.

**Comment by vjeux** [comment]
Thanks for raising this issue. I suggested a workaround here which may work https://github.com/Microsoft/TypeScript-TmLanguage/issues/475#issuecomment-310138174

I'm very hesitant to bake this in prettier, we've had a lot of complains from people before we added the ability for `<>` to break. They may feel like there's a bug in prettier when it sometimes doesn't break.

**Comment by egeozcan** [comment]
@vjeux Thank you very much, it makes sense for me to have it fixed there as well. I hope there will be a solution.

**Comment by thorn0** [comment]
I verified that the syntax highlighting issue in VS Code is gone.
