### ISSUE TITLE
Some CSS/SCSS feedback

### ISSUE THREAD

**Issue by ahmedelgabri** [prettier/prettier#2213]
I ran prettier on our SCSS files to see if we can use it also for `.scss` files next to `.js` files & I noticed a couple of things:

- Selectors are flattened 

```diff
-  &:before,
-  &:after {
+  &:before, &:after {
```
```diff
- @media all and (-webkit-min-device-pixel-ratio : 1.5),
- all and (-o-min-device-pixel-ratio: 3/2),
- all and (min--moz-device-pixel-ratio: 1.5),
- all and (min-device-pixel-ratio: 1.5) {
+ @media all and (-webkit-min-device-pixel-ratio: 1.5), all and (-o-min-device-pixel-ratio: 3/2), all and (min--moz-device-pixel-ratio: 1.5), all and (min-device-pixel-ratio: 1.5) {
```

- Some values are formatted in a kind of weird way, I assume Prettier is trying to limit the line to 80 characters so that's why this is happening. But for S/CSS maybe the limit can be disabled or changed to something like 120?

Some examples:

```diff
- border-left: 1px solid mix($warningBackgroundColor, $warningBorderColor, 50%);
+ border-left: 1px
+  solid
+  mix($warningBackgroundColor, $warningBorderColor, 50%);
```

```diff
- $fontFamily: "Lato", -apple-system, "Helvetica Neue", Helvetica, Arial, sans-serif;
+ $fontFamily: "Lato",
+  -apple-system,
+  "Helvetica Neue",
+  Helvetica,
+  Arial,
+  sans-serif;
```

- Some problems with inline comments 

```diff
- background-position: center bottom; // center the image using background position
+ background-position: center
+   bottom; // center the image using background position
```
```diff
- span.label { // 1
+ span.label {
+  // 1
```

**Comment by yuchi** [comment]
A small note: your first point (flattened selectors lists) has been already addressed in #2047 and merged but not released yet (happened the day after the 1.4.4 release).
@vjeux when is the ETA for this?

**Comment by vjeux** [comment]
1) was fixed by #2047, I just fixed 2) with #2219.

For 3) and 4), I'm going to look into using `fill()` for those, it's indeed weird when it breaks for everyone of them.

5) is intended, we don't want the comment to go past 80 columns so we break.

6) is intended as well. The underlying comment algorithm has a limited number of ways we can encode them and we cannot support comments attached to `{`. This is a bit unfortunate but it's usually easy to fix by putting the comment on the line above.

@yuchi, I'm back from vacation and had to spend time rewriting the README in order to defuse drama around eslint. Hopefully by the end of the week/early next week.

**Comment by yuchi** [comment]
Thanks for the feedback on the release. Can we help on some of these? Any pointers? (Also related to wording on readme if a non-native english speaker can help)

**Comment by vjeux** [comment]
@yuchi I'm not actively looking for help but if you come up with better wording on the README or send a fix for an issue labelled as "bug", it'll be appreciated :)

**Comment by vjeux** [comment]
Actually, #2224 also fixes the issue you have with comments :)

**Comment by ahmedelgabri** [comment]
Thanks @vjeux!

One small question :)

> 5. is intended, we don't want the comment to go past 80 columns so we break.

makes sense, but what can prevent us from passing `--print-width` to CSS too?

**Comment by vjeux** [comment]
--print-width is already working for css. I just used 80 as an example.

**Comment by ahmedelgabri** [comment]
> --print-width is already working for css. I just used 80 as an example.

I didn't know that, thanks!
