### ISSUE TITLE
Object destructing strips default values on typescript, errors on flow

### ISSUE THREAD

**Issue by danielbrodin** [prettier/prettier#2229]
Sorry for bad title, but here is something I noticed after moving some variables into an object (hence why the first bit is wrong)

```js
const test = {
  foo = {
    bar: 'baz'
  },
  foo = [
    'bar', 'baz'
  ]
}
```
This object isn't correct (`foo =` instead of `foo:`), but instead of giving an error when formatting it turns into
```js
const test = {
  foo,
  foo,
};
```

**Comment by k15a** [comment]
It's working for me: https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20test%20%3D%20%7B%5Cn%20%20foo%20%3D%20%7B%5Cn%20%20%20%20bar%3A%20'baz'%5Cn%20%20%7D%2C%5Cn%20%20foo%20%3D%20%5B%5Cn%20%20%20%20'bar'%2C%20'baz'%5Cn%20%20%5D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by danielbrodin** [comment]
Managed to get it down to using the Typescript parser

**Comment by azz** [comment]
This is quite odd, but the TypeScript parser itself thinks it is a shorthand property, and has something called an `objectAssignmentInitializer` which contains the RHS of the assignment. This initializer is not handled by typescript-eslint-parser, and as a result it is stripped from the AST.

![image](https://user-images.githubusercontent.com/1297597/27505223-f8f9ded2-58dd-11e7-8211-14c7ace0a175.png)

**Comment by azz** [comment]
There is a comment in typescript-eslint-parser:
```js
// TypeScript uses ObjectLiteralExpression in destructuring assignment, too
```
This doesn't seem to be the case anymore, `ObjectBindingPattern` is used in destructuring assignments. Maybe this behaviour is an artifact of this change.

**Comment by azz** [comment]
Actually TypeScript still uses `ObjectLiteralExpression` instead of `ObjectBindingPattern` in the following case:

```ts
({ foo = [] } = bar);
```

Prettier currently prints this as

```ts
// --parser typescript
({ foo } = bar);
// --parser babylon
({ foo = [] } = bar);
// --parser flow
> 1 | ({ foo = [] } = bar);
    |        ^
``

Babylon is the only one that is correct.

**Comment by azz** [comment]
Raised this issue here: https://github.com/eslint/typescript-eslint-parser/issues/332
