### ISSUE TITLE
JSX Improve output when there is no meaningful whitespace around text

### ISSUE THREAD

**Issue by karl** [prettier/prettier#2231]
Extracted from https://github.com/prettier/prettier/pull/1831

Current, this:

```javascript
x =
  <div>
    <h2>Message</h2>
    Hello, I am a simple message.
  </div>
```

Is output as:

```javascript
x = (
  <div>
    <h2>Message</h2>Hello, I am a simple message.
  </div>
);
```

It looks nicer with the line break.

There are a number of cases similar to this, where would get an improved output by having line breaks separating text from tags/expressions when there is no meaningful white space between them.

**Comment by vjeux** [comment]
Here's a thought: if there is not meaningful space between a tag and text, then keep whatever was inputted by the user.

If there was a \n, then put it back. If there was nothing, then keep nothing.

This way it works for our fb use case and also works for this edge case.

Can you think of times when it wouldn't work?

**Comment by karl** [comment]
Keeping the existing white space should work.

I'd like to try and see if we can get something nice working without needing to care about existing formatting. But that may well not work in practice, so we can definitely fall back to keeping existing white space if that is the case.

**Comment by rattrayalex** [comment]
Hmm, I think it may be more about whether the jsx element is at the beginning/end of the parent, eg, it is not surrounded by text/expressions... does that make sense? thoughts?

**Comment by karl** [comment]
I've done most of the work to support this change in #2272 so I'm happy to close this issue.

We can re-open it, or create a new issue if there is further discussion to be had around this.
