### ISSUE TITLE
JSX - Only inline single expressions when the parent element contains text

### ISSUE THREAD

**Issue by karl** [prettier/prettier#2232]
Extracted from https://github.com/prettier/prettier/pull/1831

Currently we always inline JSX if the element just contains a single expression:

```jsx
<div>{variable}</div>
```

Generally there seems to be a preference to format the above as:

```jsx 
<div>
  {variable}
</div>
```

But we still want to allow inlining expressions when the parent element contains text.

```jsx
// The expression can stay inlined here
<div>
  First <span>{variable}</span>
</div>
```

I'd need some time to investigate the approach, as I don't currently know how to pass information about a parent element (whether it contains text) down to the child elements.

**Comment by SimenB** [comment]
>Generally there seems to be a preference to format the above as

Looks identical? DId you mean
```jsx
<div>
  {variable}
</div>
```
?

**Comment by karl** [comment]
Yep! I've updated the examples. Thanks for the heads up!

**Comment by rattrayalex** [comment]
This seems like a good idea to me. Should be possible to either pass an arg down or access `path.getParentNode()`, though the latter might be slow. 

Passing an arg down might be harder/slower in the case where the jsx child is the first child, but perhaps in that case it can simply never inline?

```
<div>
  <a href="blah">
    {I18n.t("click_here")}
  </a>{" "}
  to go to my awesome website
</div>
```
... or something like that... doesn't seem great...

**Comment by vjeux** [comment]
This is changing a ton of files when I'm running this through the codebase. I can get behind it being inlined for the top level, but if you want to switch it back to expanded, this is going to churn users as they are going to see the back and forth.

Do you think you could look into it?

`path.getParentNode()` is a good way to look at the parent.

**Comment by karl** [comment]
I should be able to spent a little time on it tomorrow. I'll see what I can come up with!

**Comment by karl** [comment]
@vjeux `path.getParentNode()` made this fix nice and easy 😀
