### ISSUE TITLE
JSX - Should we inline single tags

### ISSUE THREAD

**Issue by karl** [prettier/prettier#2234]
Extracted from https://github.com/prettier/prettier/pull/1831

At the moment the new JSX formatting behaviour doesn't inline JSX elements contains a single tag.

So this:

```js
<div><a>Click me</a></div>
```

Is converted to:

```js
<div>
  <a>Click me</a>
</div>
```

There was some previous discussion about allowing single tags to be inlined (https://github.com/prettier/prettier/pull/1831#discussion_r120167331).

I've created this issue as a place for us to continue this discussion.

**Comment by k15a** [comment]
I really like the more clear look of the current behavior even if it is a bit verbose.

**Comment by vjeux** [comment]
I think that always expanding is fine.

**Comment by rattrayalex** [comment]
I'm 👍 to this too, can re-open this issue if enough people ask for it with compelling examples

**Comment by B-Reif** [comment]
Just wanted to chime in to say I'd like some cases of JSX inlining. I have a component like this:

```js
const ProjectTitle = props =>
	props.title
		? <span>{props.title}</span>
		: null;
```
which prettier turns into
```js
const ProjectTitle = props =>
	props.title
		? <span>
				{props.title}
			</span>
		: null;
```

I find this look a lot less clear. Maybe allow inline when there's only one `<Tag></Tag>` with a non-tag child?

**Comment by rattrayalex** [comment]
@B-Reif what you are asking for is what has been implemented; it just hasn't shipped yet 😄 

this issue is about an element within an element; `<h1><span>{title}</span></h1>` vs `<h1>{title}</h1>`
