### ISSUE TITLE
Incorrectly removes parenthesis from TS arrow function body 

### ISSUE THREAD

**Issue by LaurensRietveld** [prettier/prettier#2237]
In typescript, parenthesis are sometimes incorrectly removed from the arrow function body. 
The smallest reproduction I could make is the following:
```
var someFunction:any;
someFunction(c => ({ bla:1})) || [];
```
results in:
```
var someFunction: any;
someFunction(c => { bla: 1 }) || [];
```
or [click](https://prettier.github.io/prettier/#%7B%22content%22%3A%22var%20someFunction%3Aany%3B%5CnsomeFunction(c%20%3D%3E%20(%7B%20bla%3A1%7D))%20%7C%7C%20%5B%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) for a repl

This seems to be caused by the `|| []` at the end. 
This is a TS-only issue. JS seems to work just fine

**Comment by azz** [comment]
Thanks for the bug report.

I've found the root cause and opened an issue on our dependency: https://github.com/eslint/typescript-eslint-parser/issues/331
