### ISSUE TITLE
Odd linebreak for sequence of assignment expressions with ternaries

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#2240]
```js
(a = b ? c : 'lllllllllllllllllllllll'),
  (a = b ? c : 'lllllllllllllllllllllll'),
  (a = b ? c : 'lllllllllllllllllllllll'),
  (a = b ? c : 'lllllllllllllllllllllll'),
  (a = b ? c : 'lllllllllllllllllllllll')
```
[formats as](https://prettier.github.io/prettier/#%7B%22content%22%3A%22(a%20%3D%20b%20%3F%20c%20%3A%20'lllllllllllllllllllllll')%2C%5Cn%20%20(a%20%3D%20b%20%3F%20c%20%3A%20'lllllllllllllllllllllll')%2C%5Cn%20%20(a%20%3D%20b%20%3F%20c%20%3A%20'lllllllllllllllllllllll')%2C%5Cn%20%20(a%20%3D%20b%20%3F%20c%20%3A%20'lllllllllllllllllllllll')%2C%5Cn%20%20(a%20%3D%20b%20%3F%20c%20%3A%20'lllllllllllllllllllllll')%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

```js
(a = b ? c : "lllllllllllllllllllllll"), (a = b
  ? c
  : "lllllllllllllllllllllll"), (a = b ? c : "lllllllllllllllllllllll"), (a = b
  ? c
  : "lllllllllllllllllllllll"), (a = b ? c : "lllllllllllllllllllllll");
```

which seems... very wrong.

**Comment by bakkot** [comment]
Although not just ternaries:

```js
(a = b ? c : function() { return 0; }),
  (a = b ? c : function() { return 0; }),
  (a = b ? c : function() { return 0; }),
  (a = b ? c : function() { return 0; }),
  (a = b ? c : function() { return 0; })
```
[formats as](https://prettier.github.io/prettier/#%7B%22content%22%3A%22(a%20%3D%20b%20%3F%20c%20%3A%20function()%20%7B%20return%200%3B%20%7D)%2C%5Cn%20%20(a%20%3D%20b%20%3F%20c%20%3A%20function()%20%7B%20return%200%3B%20%7D)%2C%5Cn%20%20(a%20%3D%20b%20%3F%20c%20%3A%20function()%20%7B%20return%200%3B%20%7D)%2C%5Cn%20%20(a%20%3D%20b%20%3F%20c%20%3A%20function()%20%7B%20return%200%3B%20%7D)%2C%5Cn%20%20(a%20%3D%20b%20%3F%20c%20%3A%20function()%20%7B%20return%200%3B%20%7D)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)
```js
(a = b
  ? c
  : function() {
      return 0;
    }), (a = b
  ? c
  : function() {
      return 0;
    }), (a = b
  ? c
  : function() {
      return 0;
    }), (a = b
  ? c
  : function() {
      return 0;
    }), (a = b
  ? c
  : function() {
      return 0;
    });
```

**Comment by vjeux** [comment]
Looks like we don't encode the fact that `,` can break into multiple lines if it doesn't fit in a single line.

**Comment by bakkot** [comment]
Have an in-progress fix for this.

@vjeux, how do you feel about the formatting

```js
x => (
  "llllllllllllllllllll",
  "llllllllllllllllllll",
  "llllllllllllllllllll",
  "llllllllllllllllllll"
);
```

? In particular, having the parentheses on their own lines when a sequence expression is the body of an arrow, like we do for `ReturnStatement`?

Also, when appearing in statement position, do you prefer

```js
"llllllllllllllllllll",
"llllllllllllllllllll",
"llllllllllllllllllll",
"llllllllllllllllllll";
```
or
```js
"llllllllllllllllllll",
  "llllllllllllllllllll",
  "llllllllllllllllllll",
  "llllllllllllllllllll";
```

**Comment by vjeux** [comment]
1) look fine. 3) feels a bit better but I can go with 2. Honestly given how low usage there is for it, I don't really care :) Do what you feel look the best for your use case.
