### ISSUE TITLE
transform to camelCase, PascalCase and snake_case

### ISSUE THREAD

**Issue by Rayraegah** [prettier/prettier#2243]
Will `prettier` consider a case transform feature? 

example:

- variable names to camelCase or snake_case
- object keys names to camelCase or snake_case
- class names to PascalCase or snake_case
- class type function names to PascalCase or snake_case

I managed to toy with babylon parser's AST to see if this was possible and had some success.

There is an [eslint issue](https://github.com/eslint/eslint/issues/3730) that was closed because transformations like these are unsafe.

**Comment by k15a** [comment]
Unfortunately, this is out of scope of Prettier. We are only pretty printing your code but we will never transform the AST because this would change the meaning of your code. You should probably write a codemod or something else if you want to have this functionality.

**Comment by azz** [comment]
It won't be a part of prettier core, but it will be possible to do codemods like this using the [custom parser API](https://github.com/prettier/prettier#custom-parser-api) as of the next release.

But as mentioned in the eslint issue, proceed with caution.

**Comment by bennyn** [comment]
Anyone interested in building such a **codemod**? 

[Lodash](https://lodash.com) has [snakeCase](https://github.com/lodash/lodash/blob/d10b44bdef2b735865c493fbaec8687ec8998aef/snakeCase.js), [camelCase](https://github.com/lodash/lodash/blob/d10b44bdef2b735865c493fbaec8687ec8998aef/camelCase.js) and [kebabCase](https://github.com/lodash/lodash/blob/d10b44bdef2b735865c493fbaec8687ec8998aef/kebabCase.js) mappers. There is also a [snakeCaseMapper](https://github.com/Vincit/objection.js/blob/1.0.0/lib/utils/identifierMapping.js#L113) in [objection.js](http://vincit.github.io/objection.js/). Maybe the business logic of these can be reused.

@Rayraegah: Have you tried hooking up your code with [Prettier's Custom Parser API](https://prettier.io/docs/en/api.html#custom-parser-api)? [Babylon](https://github.com/babel/babel/tree/master/packages/babylon) seems to be a great AST parser and "just" renaming function names would be a super milestone! ⭐️

**Comment by lipis** [comment]
What about conflicts..?

**Comment by Rayraegah** [comment]
@bennyn Yes and had some success with it.

**Comment by bennyn** [comment]
@lipis Conflicts can be found everywhere but I am not here to look for problems.

@Rayraegah Great! Do you mind sharing your code in a GitHub repository? I would like to contribute. 😃

**Comment by j-f1** [comment]
@bennyn I think @lipis was asking about what would happen if you had a variable named `fooBar` and another one named `foo_bar` in the same scope.

**Comment by Rayraegah** [comment]
@j-f1 @lipis my use case was quite specific, I did not have conflicts. I used it for transforming python code into javascript code.

@bennyn Let me find the script for you. I don't have one online. Like I said, I used to do parse py to js... a one time thing.

**Comment by bennyn** [comment]
@Rayraegah Did you find the code? I am attending an [ANTLR](https://en.wikipedia.org/wiki/ANTLR) workshop next weekend and would like to present our issue here to the workshop members. 😃
