### ISSUE TITLE
Range formatting the first node formats the entire file

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#2245]
Formatting the first node of a file formats the entire file.
First node has to start at 0
`echo "call( ); call ( )" | prettier --range-start 1 --range-end 2`
```js
call();
call();
```
`echo " call( ); call ( )" | prettier --range-start 1 --range-end 2`
```js
 call(); call ( )
```
It works as expected with other nodes in the file.
ref: esbenp/prettier-vscode#134

**Comment by vjeux** [comment]
cc @josephfrazier
