### ISSUE TITLE
Unable to range format ImportDeclaration

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#2246]
Trying to range format an ImportDeclaration throws
`TypeError: Cannot read property 'node' of undefined`

`echo "import x from 'x'" | prettier --range-start 1 --range-end 2`

Seems [this list](https://github.com/prettier/prettier/blob/f702c2c61484241f1d0ca33a6603dcdcc0102256/index.js#L156-L183) is base on ECMA 5.1 and Modules are not covered.
https://www.ecma-international.org/ecma-262/7.0/#sec-ecmascript-language-scripts-and-modules

For babylon/flow this means:
- ImportDeclaration
- ExportDefaultDeclaration
- ExportNamedDeclaration 

Also ClassDeclaration and maybe others.

Typescript / flow specific nodes are also missing:
- Type alias
- Interface
- ...

ref: esbenp/prettier-vscode#133

**Comment by vjeux** [comment]
cc @josephfrazier

**Comment by josephfrazier** [comment]
Thanks for the report, @CiGit! Would you be willing to make a pull request with the needed changes? It looks like you already have a pretty good idea of what they are.
