### ISSUE TITLE
Range formatting a white-space throws.

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#2247]
`echo  "   " | prettier --range-start 1 --range-end 2`
`TypeError: Cannot read property 'node' of undefined`

Expected:
Not an error at least, same output or striped selected white-spaces

**Comment by vjeux** [comment]
cc @josephfrazier

**Comment by josephfrazier** [comment]
Thanks for the report, @CiGit! I think that using the original input is the correct thing to do in this case, so I opened https://github.com/prettier/prettier/issues/2250 with a fix.
