### ISSUE TITLE
JSX - {' '} being dropped

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#2249]
```js
<fbt>
  You can edit some targeting options for this audience on mobile. Other
  {' '}
  targeting options can be edited on desktop.
</fbt>
```

outputs

```js
<fbt>
  You can edit some targeting options for this audience on mobile. Other
  targeting options can be edited on desktop.
</fbt>;
```

on master.

cc @karl

**Comment by karl** [comment]
I believe these should be equivalent when rendered. The explicit white space and the new lines on either side (which won't generate spaces) should be equivalent to the implicit space generated by the new line between `Other` and `targeting`. 

Are you seeing different output from this in practice?

**Comment by vjeux** [comment]
Ohhh, you are totally right!

**Comment by karl** [comment]
Phew!

Thanks for doing further testing on this, it's great to have another pair of eyes looking for possible issues. If any high priority issues come up let me know and I should be able to take a look on Monday morning.

**Comment by vjeux** [comment]
I'm running it through the Facebook codebase. Lots of changes related to JSX but so far so good :)
