### ISSUE TITLE
Compatibility with angular 1.6 and typescript

### ISSUE THREAD

**Issue by proProbe** [prettier/prettier#2268]
Hello!

Im here to ask how the compatibility is with angular 1.6 and typescript? Im currently working with a project and wanted to have a consistent format across all developers. We are using vscode as an IDE but I dont believe that it would matter in this instance.

**Comment by vjeux** [comment]
Hey! Prettier should work well with TypeScript and Angular 1.6, it also has a good vscode integration. I would encourage you to try it out and if there's anything not working, please create a specific issue :) Thanks!

**Comment by proProbe** [comment]
Thanks for the quick answer. I will test it out and see what we decide :)
