### ISSUE TITLE
Quotes left as is in (s)css files

### ISSUE THREAD

**Issue by iscekic** [prettier/prettier#2271]
I expected prettier to output consistent quotes when formatting scss, however quotes are left as is.

See [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%40import%20''%3B%5Cn%40import%20%5C%22%5C%22%3B%5Cn%5Cn.lato%20%7B%5Cn%20%20font-style%3A%20'Lato'%3B%5Cn%7D%5Cn%5Cn.roboto%20%7B%5Cn%20%20font-style%3A%20%5C%22Roboto%5C%22%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) for an example.

**Comment by lydell** [comment]
Yeah, it has been mentioned that we should do this somewhere, but nobody has gotten around doing it yet.

**Comment by keithjgrant** [comment]
I think this can be closed...? It seems to be working as expected now.
