### ISSUE TITLE
Formatting moves eslint-disable-line comments and the effect is lost

### ISSUE THREAD

**Issue by blainekasten** [prettier/prettier#2273]
I'll say it over and over again, ❤️ ❤️ ❤️  this project. Thanks for your hard work and sacrificing time for it.

I've noticed that when working with prettier and eslint, using eslints disable-line feature breaks often when prettier moves the comment.

[Example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22hello%20(%20%5C%22world%5C%22%5Cn)%3B%5Cn%5Cn%5B%20%5C%22lorem%5C%22%2C%20%5C%22ipsum%5C%22%2C%20'dolor'%2C%20sit(%5C%22amet%5C%22)%2C%20consectetur%5B%20'adipiscing'%20%5D%20%2B%20%5C%22elit%5C%22%20%5D.reduce(%5Cn%20%20(first%2C%20second)%20%3D%3E%20first%20%2B%20second%2C%5Cn%20%20%5C%22%5C%22)%5Cn%5Cn%2F%2F%20the%20eslint%20comment%20should%20stay%20on%20that%20line%20as%20it%20applies%20to%20the%20func%20def%5Cnconst%20Foo%20%3D%20(%7B%20bar%2C%20baz%2C%20things%20%7D)%20%3D%3E%20%7B%20%2F%2F%20eslint-disable-line%20consistent-return%5Cn%20%20if%20(bar)%20%7B%5Cn%5Ctreturn%20%5Cn%20%20%20%20%20%20%3Cdiv%20style%3D%7B%7B%5Cn%5Ct%5Ctcolor%3A%20%5C%22papayawhip%5C%22%7D%7D%5Cn%20%20%5Ct%20%20%3E%5Cn%20%20%20%20%5Ct%3Cbr%2F%3E%7Bthings.map(thing%20%3D%3E%20reallyLongPleaseDontPutOnOneLine(thing)%20%3F%20%3Cp%3E%7Bok%7D%3C%2Fp%3E%20%3A%20%3CQuax%20bar%3D%7Bbar%7D%20baz%3D%7B%20baz%20%7D%20%7B...thing%7D%3E%3C%2FQuax%3E)%7D%5Cn%5Ct%20%20%3C%2Fdiv%3E%20%20%20%20%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Would love some discussion on if this should be a fixable issue or not. I don't think that in general eslint-disable-line is a good tool to be using, as it generally makes your code less stable, but it is a feature in eslint and becomes awkward when prettier breaks it.

**Comment by lydell** [comment]
`eslint-disable-next-line` (not the **next**) generally works fine for me. That might help you getting unblocked for now.

**Comment by vjeux** [comment]
prettier doesn't support the following form of comments: `{ // comment`, instead it moves the comment to the next line. This is a limitation in how we encode comments: attaching to an ast-node before or after.

As mentioned by @lydell, if you use `disable-next-line` it usually works fine.

I'm going to close this issue as we're likely not going to be able to fix this without some big re-thinking on how we handle comments. Sorry!

**Comment by blainekasten** [comment]
That's totally fine. I didn't think it was really that important but just wanted to get your take on it. Thanks for the work around @lydell!
