### ISSUE TITLE
[Feature Request] Alpha sort imports

### ISSUE THREAD

**Issue by AaronVasquez** [prettier/prettier#2277]
I miss this feature from gofmt

**Comment by vjeux** [comment]
JavaScript imports can have side effects so it's not safe to do that unfortunately. Also, we've taken the stance with prettier not to do those kind of transforms that change the ast.

We recommend that those would be implemented as eslint rules with autofix.

Thanks for asking :)

**Comment by steida** [comment]
I believe the order of imports should be enforced. Fail fast fail cheap. Otherwise, it can happen the developer looking for the "right" order ends up in the cycle. We can add some flag for that. Order for imports is important for a quick scan (or OCD whatever). Please reconsider it. Thank you.

**Comment by steida** [comment]
@vjeux Or via plugin?

**Comment by vjeux** [comment]
@steida: at Facebook we're doing it via a eslint plugin with autofix. I would recommend going that route instead of inside of prettier.

**Comment by steida** [comment]
During dev or after build? Not sure which workflow I should choose for Next.js. Thank you.

**Comment by vjeux** [comment]
We show eslint warnings and autofix within Nuclide and before you send the equivalent of a PR. So it's both.

**Comment by steida** [comment]
I learned how to transform Eslint errors to warnings for dev hour ago :-)
https://github.com/este/este/commit/8865ee80338531ff5bae7cccbffc3f600855dbd6

Thank you again, you are saving souls.

**Comment by alexeagle** [comment]
For what it's worth, clang-format does alpha-sort imports in TypeScript/JavaScript code. We haven't had a problem with it at Google.

**Comment by suchipi** [comment]
If you have modules that modify global state, or circular dependencies, then rearranging imports is not safe. For most cases, it is, but since there are some cases where it is not, prettier is going to err on the side of caution so that we don't break user's code.

**Comment by lydell** [comment]
I wish something like [prettier-transform](https://github.com/azz/prettier-transform) will take off, so people can pick and choose such transforms (100% safe or not). I also want import sorting, but haven't find a really easy to use solution yet.

**Comment by alexeagle** [comment]
I totally understand why prettier doesn't do this - if you start introducing unsafe options then you blur the line with linting, and pollute the mental model of "always accept what the formatter does".

TSLint has a fixer for this too. https://palantir.github.io/tslint/rules/ordered-imports/
If I find time, I'll try switching the main Angular repository to prettier and use that tslint check with `--fix` to fill in this bit.
