### ISSUE TITLE
Delete `.(` warning in React Stateless Component

### ISSUE THREAD

**Issue by tapas4java** [prettier/prettier#2278]
Hi,

Prettier is keep complaining about `(` and `)` around JSX on a stateless component. Is it a bug or are there any rule to disable this warning?
```javascript
const App = ({ session }) => (
   <div>Hello!</div>
);
```

**Comment by notrab** [comment]
Depending on the size of your component, Prettier could format it like either of the following...

```js
const App = ({ session }) => <div>Hello!</div>
```

```js
const App = ({ session }) => 
    <div>Hello!</div>
```

This is how I've always declared my stateless components but maybe Prettier has a flag to stop this behaviour anyone?

**Comment by lydell** [comment]
There was a change recently if the parentheses should be there or not, but there’s no bug here, and no flags. Since this seems to answer the questions asked, I’m closing this one, but feel free to add more information if I’ve missed something!

**Comment by tapas4java** [comment]
Hi @lydell 

Do you think it is a good idea to provide a flag for disabling this behavior?? I am sure many people won't like the open JSX statement without brackets around. Of course I can do like below to make prettier happy but writing extra code for this doesn't make sense.

```javascript
const App = ({ session}) => {
  return (
    <div>Hello!</div>
  );
};
```

**Comment by lydell** [comment]
@tapas4java see #1733 and the issues that link to it.
