### ISSUE TITLE
Octal numbers do not parse in babylon

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#228]
Incorrect output for babylon:

```js
echo '0777' | ./bin/prettier.js --stdin
{ SyntaxError: Invalid number (1:0)
```

```js
echo 'function f() { "use strict"; 0777 }' | ./bin/prettier.js --stdin
{ SyntaxError: Invalid number (1:29)
```

Flow parser gets it right:

```js
echo '0777' | ./bin/prettier.js --stdin --flow-parser
511;
```

```js
echo 'function f() { "use strict"; 0777 }' | ./bin/prettier.js --stdin --flow-parser
Error: Octal literals are not allowed in strict mode. on line 1
```

The issue on babylon ( https://github.com/babel/babylon/issues/130 ) mentions that you need to set `sourceType` option in order to execute it in non strict mode. Need to investigate.

**Comment by vjeux** [comment]
Okay, so this is going to be annoying, `sourceType: "script"` makes `0777` work but it refuses to parse `import` and `export`.

**Comment by demoneaux** [comment]
I think the best solution is to expose a way to pretty print with some customisability. This could be through a `parser` option which passed in an instance of a parser, which could be Esprima, Babylon, Flow or any other parsers. This would allow users to configure the parsers before hand to allow it to parse their code structure. Another alternative would be to provide a `formatAST` option which would just format an AST. This would force the user to have to get the AST themselves, which might also be suited for plugins as users can run their own code to transform the AST before prettier prints it.

**Comment by phpnode** [comment]
being able to work from an AST directly is really important, +1 for `formatAST()`

**Comment by lydell** [comment]
The only things to do here, as far as I can tell, are:

- Add a `--source-type <script|module>` option.
- Tell people to use `0o777`.

**Comment by vjeux** [comment]
Changing it to "Needs discussion" as there isn't any concrete fix we can do except for adding a flag for source-type, which I'm not sure we should do

**Comment by lydell** [comment]
Related: facebook/flow#3292

**Comment by vjeux** [comment]
We're unlikely going to support this option for such a rare edge case. I'm going to close this issue.
