### ISSUE TITLE
Trying to override eslint (using prettier) to use single quotes not double

### ISSUE THREAD

**Issue by appsolutegeek** [prettier/prettier#2280]
Hi,

I have passed command line arguments to prettier so it is formatting the way I want using single quotes.

I setup eslint as per the instructions but i can't seem to override the quotes rule, it appears to still be coming from prettier/prettier, Anyone know what I am doing wrong ?

Here is my eslintrc

```
{
    "extends": "prettier",
    "env": {
        "browser": true,
        "node": true
    },
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "plugins": [
        "prettier"
    ],
    "rules": {
        "prettier/prettier": "error",
        "quotes": ["error", "single"]
    }
}
```

I thought I placed it correctly to be overridden i.e. 

        "quotes": ["error", "single"]

**Comment by SimenB** [comment]
`"prettier/prettier": ["error", { "singleQuote": true }],`

**Comment by appsolutegeek** [comment]
Thanks @SimenB

**Comment by travisdahl** [comment]
@SimenB does this still work for you? It was working for me with version `1.6.1`  but not after that. I always get double quotes now (and no, im not referring to JSX)

**Comment by SimenB** [comment]
I still works, yes

**Comment by theednaffattack** [comment]
For me using "prettier/prettier": ["error", { "singleQuote": true }] saves as double quotes.

I'd like to save as single if I can.  Are there additional steps I need to be taking?  I'm a Mac VSCode user, not sure if that matters.

**Comment by ylnkancheti** [comment]
@theednaffattack It works for me.

**Comment by azz** [comment]
New recommended way is:

```json
// .eslintrc.json
{
    "extends": "prettier",
    "plugins": [
        "prettier"
    ],
    "rules": {
        "prettier/prettier": "error",
    }
}
```

```json
// .prettierrc
{
  "singleQuote": true
}
``

**Comment by ylnkancheti** [comment]
@azz Can't we keep this rule under rules section?

**Comment by azz** [comment]
It's better to use .prettierrc because more tools (editors) will respect it.

**Comment by ylnkancheti** [comment]
@azz Got it. Thanks.

**Comment by guillaumecochard** [comment]
Hi, in webstorm, even using the .prettierrc file, Prettier replace my single quotes in JSX files by doble quotes (in the imports it's okay but no in the code).
Is there a way to force it ? Thanks !

import HistoryContainer from './HistoryContainer';
import StyledFooter from './StyledFooter';

export default class Chat extends Component {
  render() {
    return (
      <div id="frame">
        <div className="content">
          <Header />
          <Container />
          <Footer />
        </div>
      </div>
    );
  }
}

**Comment by lydell** [comment]
@guillaumecochard See https://prettier.io/docs/en/rationale.html#strings and #1080.

**Comment by guillaumecochard** [comment]
@Iydell "JSX always uses double quotes"
Is there any way to bypass it?
