### ISSUE TITLE
Removes linebreaks from styled-components tagged template literals in an odd way

### ISSUE THREAD

**Issue by dgcoffman** [prettier/prettier#2291]
Using prettier 1.5.0.

before
``` javascript
const Direction = styled.span`
  ${({ up }) => up && `color: ${color.positive};`}
  ${({ down }) => down && `color: ${color.negative};`}
`;
```

after
``` javascript
const Direction = styled.span`
  ${({ up }) => up && `color: ${color.positive};`} ${({ down }) =>
       down && `color: ${color.negative};`};
`;
```

I'd expect it to preserve the existing linebreak.

**Comment by vjeux** [comment]
Thanks, i'll look into fixing it :)

**Comment by vjeux** [comment]
this is rewritten as

```js
  @prettier-placeholder
  @prettier-placeholder
```

which is being parsed as a media query. I managed to get it working for this case but then there are things like

```js
  @prettier-placeholder
  color: red;
  @prettier-placeholder
```

which are getting busted. If you add a `;` at the end of the expressions, then it prints as is:

```js
const Direction = styled.span`
  ${({ up }) => up && `color: ${color.positive};`};
  ${({ down }) => down && `color: ${color.negative};`};
`;
```

I'm not sure we can make it work without unfortunately :(

cc @pomber in case you have ideas.

**Comment by dgcoffman** [comment]
That's cool -- I can add semicolons. You'll likely hear about this a bit since this pattern is common when using styled-components.

**Comment by dgcoffman** [comment]
Another styled-components thing:
``` javascript
const Dropdown = styled.div`
  position: relative;
`;
```
becomes
``` javascript
const Dropdown = styled.div`position: relative;`;
```

which causes:
"block-closing-brace-space-after": "always-single-line",
"block-closing-brace-space-before": "always-single-line",
"block-opening-brace-space-after": "always-single-line",
"block-opening-brace-space-before": "always-single-line",

stylelint rules to fail. We'd prefer always line-breaking.

**Comment by pomber** [comment]
First issue looks hard, maybe we could always preserve linebreaks after expressions in CSS template literals? No idea how to do it, but I know it is being done for [some cases](https://github.com/prettier/prettier/blob/master/Rationale.md#multi-line-objects).  

Second issue should be easy, looks like a missing `breakParent`. In fact if you run it [without the assignment](https://prettier.io/#%7B%22content%22%3A%22%2F*%20first%20issue%20*%2F%5Cnstyled.span%60%5Cn%20%20%20%20%24%7Bfoo%7D%5Cn%20%20%20%20%24%7Bfoo%7D%5Cn%60%3B%5Cn%5Cnstyled.span%60%5Cn%5Ct%24%7Bfoo%7D%20%5Cn%5Ctdisplay%3A%20%24%7Bfoo%7D%5Cn%5Ct%24%7Bfoo%7D%20%5Cn%60%3B%5Cn%5Cn%2F*%20second%20issue%20*%2F%5Cnvar%20x%20%3D%20styled.span%60%5Cn%20%20%20%20display%3A%20none%5Cn%60%3B%5Cn%5Cnstyled.span%60%5Cn%5Ctdisplay%3A%20none%3B%5Cn%60%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) it inserts the linebreaks.

**Comment by NameFILIP** [comment]
@dgcoffman a temporarily workaround for this is to add a comment

```
const Dropdown = styled.div`
  /* A long comment to prevent the block from reformatting by prettier to be on one line */
  position: relative;
`;
```

**Comment by dgcoffman** [comment]
Same behavior in 1.6.0.

**Comment by vjeux** [comment]
@lydell any idea how to workaround this? It's triggering for a lot of people :(

**Comment by azz** [comment]
Maybe we just need to look at the source and add a semi to the interim step.

```css
  @prettier-placeholder;
  @prettier-placeholder
```

**Comment by MrLoh** [comment]
Is there any way to help get the second issue of the one line formatting of short templates to stop. I have `//prettier ignore` in front of some styles all over my codebase 🙁

**Comment by lydell** [comment]
@MrLoh `// prettier-ignore` is the only way right now.

**Comment by MrLoh** [comment]
I know I’m wondering wether anyone could give me some pointers towards where it would need to be fixed.

**Comment by dgcoffman** [comment]
Happy to report that the linebreaking bug has been fixed (tested 1.7.4).

**Comment by azz** [comment]
I can still repro?

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20Direction%20%3D%20styled.span%60%5Cn%20%20%24%7B(%7B%20up%20%7D)%20%3D%3E%20up%20%26%26%20%60color%3A%20%24%7Bcolor.positive%7D%3B%60%7D%5Cn%20%20%24%7B(%7B%20down%20%7D)%20%3D%3E%20down%20%26%26%20%60color%3A%20%24%7Bcolor.negative%7D%3B%60%7D%5Cn%60%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
const Direction = styled.span`
  ${({ up }) => up && `color: ${color.positive};`}
  ${({ down }) => down && `color: ${color.negative};`}
`;
```

**Output:**
```jsx
const Direction = styled.span`
  ${({ up }) => up && `color: ${color.positive};`} ${({ down }) =>
      down && `color: ${color.negative};`};
`;

```

**Comment by dgcoffman** [comment]
@azz 

Sorry for being unclear (and reporting two bugs in a single issue).

If you [add semicolons](https://prettier.io/playground/#%7B%22content%22%3A%22const%20Direction%20%3D%20styled.span%60%5Cn%20%20%24%7B(%7B%20up%20%7D)%20%3D%3E%20up%20%26%26%20%60color%3A%20%24%7Bcolor.positive%7D%3B%60%7D%3B%5Cn%20%20%24%7B(%7B%20down%20%7D)%20%3D%3E%20down%20%26%26%20%60color%3A%20%24%7Bcolor.negative%7D%3B%60%7D%3B%5Cn%60%3B%5Cn%5Cnconst%20Single%20%3D%20styled.span%60color%3A%20red%3B%60%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D), the line-breaks will work as expected in your example.

I was saying that
``` javascript
const Single = styled.div`
  color: red;
`;
```
will now remain formatted as such.

**Comment by DevanB** [comment]
I'm noticing some odd things happening also. Maybe I am causing this somehow though?

This is seemingly correct:

```jsx
export const MilestoneIcon = styled.div`
  border-radius: 50%;
  border: 5px solid rgba(var(--green-rgb), 0);
  display: inline-block;
  height: 40px;
  width: 40px;

  ${props =>
    (props.complete || props.inProgress) &&
    css`
      border-color: rgba(var(--green-rgb), 0.15);
    `}
  
  div {
    background-color: var(--purpleTT);
    border-radius: 50%;
    border: 4px solid rgba(var(--purple-rgb), 0.2);
    color: var(--purpleTT);
    display: inline-flex;

    ${props =>
      props.complete &&
      css`
        background-color: var(--green);
        border-width: 7px;
      `}
      
    ${props =>
      (props.complete || props.inProgress) &&
      css`
        border-color: var(--green);
      `}
  }
`;
```

But after Prettier works on it, I end up with:

```jsx
export const MilestoneIcon = styled.div`
  border-radius: 50%;
  border: 5px solid rgba(var(--green-rgb), 0);
  display: inline-block;
  height: 40px;
  width: 40px;

  ${props =>
    (props.complete || props.inProgress) &&
    css`
      border-color: rgba(var(--green-rgb), 0.15);
    `} div {
    background-color: var(--purpleTT);
    border-radius: 50%;
    border: 4px solid rgba(var(--purple-rgb), 0.2);
    color: var(--purpleTT);
    display: inline-flex;

    ${props =>
      props.complete &&
      css`
        background-color: var(--green);
        border-width: 7px;
      `} ${props =>
      (props.complete || props.inProgress) &&
      css`
        border-color: var(--green);
      `}
  }
`;
```

**Comment by evilebottnawi** [comment]
Somebody have ideas how we can solve this? I think we can look ` ${({ up }) => up && `color: ${color.positive};`}` on `semicolon` inside and expression and if we have add `hardline`. It is allow write without break pretty output:
```
${props => props.red ? 'color: red;' : ''}
${props => props.red ? 'color: red' : ''};
```
Feedback welcome. Especially rare and bleeding use cases. I want to fix it before we release `1.12.0`.

**Comment by aehrt55** [comment]
@evilebottnawi I think we should consider some case like:
```javascript
import styled, { css } from 'styled-components'

const mixin = css`
  color: ${props => props.color};
  ${props => props.otherProperty}: ${props => props.otherValue};
`
styled.div`
  display: flex;
  ${props => props.useMixin && mixin}
`
```

I think we should not remove the last `semicolon` from the mixin, because we expect that mixin should be css declarations' set.

**Comment by evilebottnawi** [comment]
@aehrt55 Thanks for examples :+1:

**Comment by fisker** [comment]
I think this is already fixed

**Comment by lydell** [comment]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEARAlgJzjBl2kwF5MMBPAGzgBMA6NABwEMoADAHSk0wASYAApgmAK6tMAXwCUFAHyTpAMlWYukWhHxIhwbbqasIaXCQBucGQG4uMvgOFjMDCAHd+8pW8-91TSM9A2CmKDgAc3YrG3tHblsQABoQCFYSdGRQdnx8TwAFXIQ0ZBB2SwhcBhSQACN8djAAazgYAGUOMFwoSOQYfAk4VIALGABbWgB1EYs4Nia4dpKLXEsLajKwNFLUnrQ4fBgCxsjx9mQAM3ZaA9SAKzQADwAhRpa29vZxuAAZHrgVxudxAjye7R6kXoAEUJBB4EDbsMQBx8Ad8GU6uw6nBaLVWPgejAptUYCNkAAOAAMqQJZjgU0arDKBPmh2stQAjnD4Cd0qUUOw0ABaCKMRi1QjcghwE7sM4XJDXJGpA7jXD9QbI8y9GE8wFK4HImDYkkMMnIABMqQG7FwtEhAGEIONzmUoNBAakJAcACrYgXKkGWIYASSgDAQHTAhIyAEEI+0YHQDUGbDIgA)
```sh
--parser babel
```

**Input:**
```jsx
const Direction = styled.span`
  ${({ up }) => up && `color: ${color.positive};`}
  ${({ down }) => down && `color: ${color.negative};`}
`;
```

**Output:**
```jsx
const Direction = styled.span`
  ${({ up }) => up && `color: ${color.positive};`}
  ${({ down }) => down && `color: ${color.negative};`}
`;

```

Feel free to open a new issue if there’s still something wrong!

**Comment by lydell** [comment]
Wait, we should add tests.

**Comment by evilebottnawi** [comment]
I will add tests in separate PR, because many issues will be solved and https://github.com/prettier/prettier/pull/6794 need more work, i will put feedback in near future
