### ISSUE TITLE
How does prettier handle when there are double quotes inside single quotes in css and "single quote" option is on

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2293]
Example issue https://github.com/stylelint/stylelint/issues/2601#issuecomment-304864056

**Comment by vjeux** [comment]
Right now prettier doesn't change quotes for CSS. But when we're going to (looking for help!) we'll make sure to handle this case properly. Thanks for raising it!

**Comment by lydell** [comment]
@jitendravyas See #2271 (which you somehow already have since you've reacted with "thumbs up" on one of the comments over there).
