### ISSUE TITLE
Support .gitignore

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#2294]
Do not touch files that are in `.gitignore`.

**Comment by dashed** [comment]
If this is added, can there be an option to *ignore* `.gitignore`? 😄

**Comment by evilebottnawi** [comment]
If your accept this, i will do PR.

**Comment by azz** [comment]
FYI `.eslintignore` works already with `eslint-plugin-prettier`.

**Comment by evilebottnawi** [comment]
@azz i use prettier standalone without `eslint`

**Comment by jitendravyas** [comment]
Also for CSS, files ignored in` .stylelintignore`

**Comment by jackson-sandland** [comment]
What's the status on this? Can we .gitignore when using pretty-quick, or prettier?

**Comment by azz** [comment]
pretty-quick only runs on changed files from git so implicitly respect `.gitignore`. With prettier you need to use `prettier. ignorePath: ".gitignore"`
