### ISSUE TITLE
Range and graphql parser throws

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#2296]
`echo '{NPC{life}}' | prettier --parser graphql --range-end 3`
throws:
`RangeError: Maximum call stack size exceeded`

I will update with more info once I have.

**Comment by vjeux** [comment]
cc @josephfrazier

**Comment by josephfrazier** [comment]
It looks like `comments.getSortedChildNodes()` is returning a circular object in this case.

**Comment by vjeux** [comment]
Okay, this is easy, I can fix.

**Comment by vjeux** [comment]
@josephfrazier after https://github.com/prettier/prettier/pull/2304, it no longer throws but now does

```js
(558) >> echo '{NPC{life}}' | ./bin/prettier.js --parser graphql --range-end 3
stdin: SyntaxError: Syntax Error GraphQL request (1:1) Unexpected <EOF>

1:
   ^
 (1:1)
> 1 |
    | ^
```

it's probably missing graphql nodes?

**Comment by vjeux** [comment]
This document is for queries, we also support the schema definitions. I would just look at the printer and take all the ones that end with it
