### ISSUE TITLE
GraphQL imports not supported

### ISSUE THREAD

**Issue by arnarthor** [prettier/prettier#2299]
It seems that graphql imports are not supported. I've added a file below that breaks this.

https://prettier.io/#%7B%22content%22%3A%22%23%20import%20%5C%22.%2FclaimsFragment.gql%5C%22%5Cn%5Cnquery%20claimsByBookingReferenceAndLastName(%24bookingReference%3A%20String!%2C%20%24lastName%3A%20String!)%20%7B%5Cn%20%20claimsByBookingReferenceAndLastName(bookingReference%3A%20%24bookingReference%2C%20lastName%3A%20%24lastName)%20%7B%5Cn%20%20%20%20...%20claim%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22graphql%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks, this needs to be fixed!
