### ISSUE TITLE
Trailing Comma "all" setting breaking JSON

### ISSUE THREAD

**Issue by kkemple** [prettier/prettier#2308]
I'm not sure if I am not using properly but the issue I'm facing is having the trailing comma option set to all adds it to JSON entries as well. This is causing syntax errors and I have to disable prettier to edit JSON files unless I turn of trailing commas.

This was discovered in VSCode prettier extension so could be an issue there and not here, just thought I would bring it to your attention! If this does end up being an issue it looks interesting and if given some direction I would gladly take a look and open a PR to fix!

![jun-27-2017 22-00-11](https://user-images.githubusercontent.com/3629876/27617419-2d988f5a-5b84-11e7-85a5-1d31ba0ba23a.gif)

**Comment by kkemple** [comment]
after running `prettier` cli against JSON file it did NOT add trailing commas so seems to be a VSCode extension bug. Will file over there!

**Comment by CiGit** [comment]
Could you reopen please.
Repro on prettier [here](https://prettier.io/#%7B%22content%22%3A%22%7B%5C%22a%5C%22%3A1%2C%5Cn%20%20%5C%22b%5C%22%3A2%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22json%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

and with the cli
`echo -e '{"a":1,\n"b":2}'|prettier --trailing-comma all --parser json`
```json
{
  "a": 1,
  "b": 2,
}
```
As a side note: trailing-comma es5 gives the same result

**Comment by kkemple** [comment]
ah! i didn't run prettier with parser set to JSON

**Comment by josephfrazier** [comment]
It looks like filename-based forcing of `trailingComma` to "none" was done in https://github.com/prettier/prettier/pull/2216, but this wasn't also extended to the `parser: "JSON"` case. I'll send a PR.

**Comment by codepunkt** [comment]
Would love to see this released, using prettier/prettier directly from gh for the time being.
