### ISSUE TITLE
template string bad formatting example

### ISSUE THREAD

**Issue by 2c2c** [prettier/prettier#231]
```js
    const formatted_display = `${display.substring(0,1)}h ${display.substring(1,3)}m ${display.substring(3,5)}s`
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20const%20formatted_display%20%3D%20%60%24%7Bdisplay.substring(0%2C1)%7Dh%20%24%7Bdisplay.substring(1%2C3)%7Dm%20%24%7Bdisplay.substring(3%2C5)%7Ds%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

(Edit by vjeux: this issue has been fixed)

**Comment by vjeux** [comment]
Thanks for reporting this!

@jlongster do we have a way to force print everything in one line? I wonder if we shouldn't do that for ${}. It seems like it's never a good idea to try and pretty print those.

**Comment by jlongster** [comment]
@vjeux not retroactively, but we could create a utility function that simply traverses the document (that's what a piece of intermediate representation is called) and removes all lines. Potentially we could see if it's easy to tweak the print algorithm to add it, but I'd like to keep that simple. So far we haven't had a use case for forcing flat mode.

Are we sure we don't want to print it that way? Why wouldn't you want to break a template string up? The second one shows more of it on the screen and allows you to build a big string without it being huge on one line.

But we wouldn't need to force print on one line: if we don't

**Comment by gaelduplessix** [comment]
An other example where formatting gets really broken with template strings (this one is quite common when using `styled-components`):

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20Test%20%3D%20styled.div%60%5Cn%5Ct%24%7B(customCss)%20%3D%3E%20customCss.map(%5Cn%5Ct%5Ct(%7B%20selector%2C%20key%2C%20value%20%7D)%20%3D%3E%20(%5Cn%5Ct%5Ct%5Ct%60%24%7Bselector%7D%20%7B%5Cn%5Ct%5Ct%5Ct%5Ct%24%7Bkey%7D%3A%20%24%7Bvalue%7D%3B%5Cn%5Ct%5Ct%5Ct%7D%60%5Cn%20%20%20%20%5Ct)%5Cn%20%20)%7D%5Cn%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by clempat** [comment]
We use as well in our project `styled-components` and we face as well some formatting issue in string nested template string.

For example things like:
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20Test%20%3D%20styled.div%60%5Cn%5Ctheight%3A%2020px%3B%5Cn%5Ct%24%7Bprops%20%3D%3E%20props.fullwidth%20%26%26%20%60%5Cn%5Ct%5Ctwidth%3A%20100%25%3B%5Cn%5Ct%60%7D%5Cn%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Atrue%7D%7D

**Comment by vjeux** [comment]
Maybe we need to expose some hooks such that `styled` can provide a way to format this. It seems like it requires parsing the content of the template literal in order to be able to properly print those.

**Comment by clempat** [comment]
For me it would be enough. But would that mean that any template string use in other context than styled-component would have the current formatting ?

Looks like the formatting rules applied otherwhere should not be the same as inside template string variable. so for exemple "&&" does not trigger line.

For the indent it is true that it is not the same as the text out of js should keep the indent.

For @gaelduplessix example it is funny to see how it act when you take 
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20Test%20%3D%20styled.div%60%5Cn%24%7B(customCss)%20%3D%3E%20customCss.map(%5Cn%20%20(%7B%20selector%2C%20key%2C%20value%20%7D)%20%3D%3E%20%60%5Cn%20%20%20%20%24%7Bselector%7D%20%7B%5Cn%20%20%20%20%20%20%20%20%24%7Bkey%7D%3A%20%24%7Bvalue%7D%3B%5Cn%20%20%20%20%7D%60%5Cn)%7D%5Cn%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Atrue%7D%7D

and just adding the tab on the string template bloc so vs:

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20Test%20%3D%20styled.div%60%5Cn%20%20%24%7B(customCss)%20%3D%3E%20customCss.map(%5Cn%20%20%20%20(%7B%20selector%2C%20key%2C%20value%20%7D)%20%3D%3E%20%60%5Cn%20%20%20%20%20%20%24%7Bselector%7D%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%24%7Bkey%7D%3A%20%24%7Bvalue%7D%3B%5Cn%20%20%20%20%20%20%7D%60%5Cn%20%20)%7D%5Cn%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Atrue%7D%7D

**Comment by vjeux** [comment]
It looks like in this example, you want the indent to match where the `${` started and not blindly do +2 like we do everywhere else. That sounds reasonable. What do you think @jlongster?

**Comment by jlongster** [comment]
Interesting, yeah we can play with that! Note that this is the output with [this PR](https://github.com/jlongster/prettier/pull/749):

```js
const Test = styled.div`
  ${customCss => customCss.map(({ selector, key, value }) => `
      ${selector} {
          ${key}: ${value};
      }`)}
`;
```

The thing that's hard about this is that it's by definition taking the original user's formatting into account because they are in a string. So the number of spaces to indent the line starting with `${selector}` is just going to be blindy copied. Hopefully #749 helps with this because it won't break things up for you anymore, and users just sometimes have to readjust things. But it makes getting this right automatically almost impossible.

**Comment by jonikorpi** [comment]
[styled-jsx](https://github.com/zeit/styled-jsx) causes similar issues. No errors, but the resulting formatting is undesirable/ugly. 

```jsx
<style jsx>{`
      p {
        color: red;
      }
`}</style>
```
->
```jsx
<style jsx>
      {
        `
      p {
        color: red;
      }
    `
      }
</style>
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20default%20()%20%3D%3E%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%3Cp%3Eonly%20this%20paragraph%20will%20get%20the%20style%20%3A)%3C%2Fp%3E%5Cn%20%20%20%20%7B%20%2F*%20you%20can%20include%20%3CComponent%20%2F%3Es%20here%20that%20include%5Cn%20%20%20%20%20%20%20%20%20other%20%3Cp%3Es%20that%20don't%20get%20unexpected%20styles!%20*%2F%20%7D%5Cn%20%20%20%20%3Cstyle%20jsx%3E%7B%60%5Cn%20%20%20%20%20%20p%20%7B%5Cn%20%20%20%20%20%20%20%20color%3A%20red%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%60%7D%3C%2Fstyle%3E%5Cn%20%20%3C%2Fdiv%3E%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Let's consolidate all the template literal issues in this one. From #786

```js
insertRule(`*, *:before, *:after {
  box-sizing: inherit;
}`)
```

outputs

```js
insertRule(
  `*, *:before, *:after {
  box-sizing: inherit;
}`,
)

**Comment by vjeux** [comment]
Actually, it looks like all the original issues have now been fixed. I'm going to switch back to the other one as the canonical one.
