### ISSUE TITLE
JSX with functional component and arrow syntax with bracket formatting looks strange

### ISSUE THREAD

**Issue by mech** [prettier/prettier#2320]
Hi I have a pretty good format for this code and believe is the correct one:

```javascript
const Workspace = () => (
  <div>
    <h1>Employee Workspace</h1>
  </div>
)
```

But Prettier will format like this:

```javascript
const Workspace = () =>
  (<div>
    <h1>Employee Workspace</h1>
  </div>)
```

Is that correct or am I setting up Prettier the wrong way.

**Comment by lydell** [comment]
It feels like some other tool adds those parens. This is how Prettier formats it: https://prettier.io/#%7B%22content%22%3A%22const%20Workspace%20%3D%20()%20%3D%3E%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%3Ch1%3EEmployee%20Workspace%3C%2Fh1%3E%5Cn%20%20%3C%2Fdiv%3E%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
This is likely an issue with something else (maybe an eslint rule with autofix). I'm going to close this issue on prettier. Thanks for reporting it!

**Comment by mech** [comment]
Yes this happen if I use Atom editor with prettier-atom and did not install the prettier package. Once I include the prettier as dependencies, everything worked fine :)
