### ISSUE TITLE
prettier not respecting line width constraint in certain import situations

### ISSUE THREAD

**Issue by hesher** [prettier/prettier#2321]
Check out these two import lines:

```
import {UserManagerEmptyExperience} from '../../containers/UserManagerEmptyExprience/UserManagerEmptyExperience';
import {UserManagerEmptyExperience, Another} from '../../containers/UserManagerEmptyExprience/UserManagerEmptyExperience';
```
Live example [here](https://prettier.io/#%7B%22content%22%3A%22import%20%7BUserManagerEmptyExperience%7D%20from%20'..%2F..%2Fcontainers%2FUserManagerEmptyExprience%2FUserManagerEmptyExperience'%3B%5Cnimport%20%7BUserManagerEmptyExperience%2C%20Another%7D%20from%20'..%2F..%2Fcontainers%2FUserManagerEmptyExprience%2FUserManagerEmptyExperience'%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)
Assuming line width constraint of 110.
The first line doesn't break correctly while the second one does.

Bug?

**Comment by vjeux** [comment]
The first one is intentional. Apparently a lot of people do not split it into multiple lines when there's only one. I'm going to close this issue, thanks for reporting it :)

**Comment by hesher** [comment]
Ok. Thanks. 
So in fact the Max line width is a recommendation and not a strict limit. Is that by design?

**Comment by lydell** [comment]
@hesher Very much so. In fact, it's impossible to have a 100% strict limit, because there are things that cannot  be broken across several lines, such as long variable names, string literals, regexes, comments and indentation.
