### ISSUE TITLE
prettier doesn't format a variable declaration with type

### ISSUE THREAD

**Issue by hesher** [prettier/prettier#2322]
For this example ([live version](https://prettier.io/#%7B%22content%22%3A%22export%20const%20listAuthorizedSitesForDefaultHandler%3A%20ListAuthorizedSitesForHandler%20%3D%20aListAuthorizedSitesForResponse%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A110%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Atrue%2C%22ast%22%3Afalse%7D%7D)):

```typescript
export const listAuthorizedSitesForDefaultHandler: ListAuthorizedSitesForHandler = aListAuthorizedSitesForResponse;
```

prettier doesn't format this line correctly so the max line width would be respected.

**Comment by vjeux** [comment]
I'm curious, how would you break this?

**Comment by hesher** [comment]
I would split it after the equals.

**Comment by azz** [comment]
Closing in favour of #2482.
