### ISSUE TITLE
JSX whitespace moved to same line as tag

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#2325]
Upgrading from `1.4.4` to `1.5.2`.

```jsx
const Something = () =>
    <article>
        <section>
            <div>
                <h1 className="u-screen-reader-only">Troika</h1>
                <span className="d1">Version: {__VERSION__}</span>
                <span className="d1"> Published: {__DATE__}</span>
                <span className="d1">
                    {" "}
                    <a
                        href="https://github.schibsted.io/finn/troika"
                        className="link"
                    >
                        {" "}GitHub
                    </a>
                </span>
            </div>
        </section>
    </article>
```

Becomes
```jsx
const Something = () =>
  <article>
    <section>
      <div>
        <h1 className="u-screen-reader-only">Troika</h1>
        <span className="d1">
          Version: {__VERSION__}
        </span>
        <span className="d1">
          {" "}Published: {__DATE__}
        </span>
        <span className="d1">
          {" "}<a
            href="https://github.schibsted.io/finn/troika"
            className="link"
          >
            {" "}GitHub
          </a>
        </span>
      </div>
    </section>
  </article>;
```

I don't like this change, especially the part where the `{" "}` is moved to the same line as the `a`:

```diff
diff --git i/source/docs/content/Home.jsx w/source/docs/content/Home.jsx
index 24e54da..dd8da92 100644
--- i/source/docs/content/Home.jsx
+++ w/source/docs/content/Home.jsx
@@ -19,11 +19,14 @@ const HomePage = () =>
                 }}
             >
                 <h1 className="u-screen-reader-only">Troika</h1>
-                <span className="d1">Version: {__VERSION__}</span>
-                <span className="d1"> Published: {__DATE__}</span>
                 <span className="d1">
-                    {' '}
-                    <a
+                    Version: {__VERSION__}
+                </span>
+                <span className="d1">
+                    {' '}Published: {__DATE__}
+                </span>
+                <span className="d1">
+                    {' '}<a
                         href="https://github.schibsted.io/finn/troika"
                         className="link"
                     >
```

https://prettier.io/#%7B%22content%22%3A%22const%20Something%20%3D%20()%20%3D%3E%5Cn%20%20%20%20%3Carticle%3E%5Cn%20%20%20%20%20%20%20%20%3Csection%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ch1%20className%3D%5C%22u-screen-reader-only%5C%22%3ETroika%3C%2Fh1%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20className%3D%5C%22d1%5C%22%3EVersion%3A%20%7B__VERSION__%7D%3C%2Fspan%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20className%3D%5C%22d1%5C%22%3E%20Published%3A%20%7B__DATE__%7D%3C%2Fspan%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20className%3D%5C%22d1%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%5C%22%20%5C%22%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ca%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20href%3D%5C%22https%3A%2F%2Fgithub.schibsted.io%2Ffinn%2Ftroika%5C%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20className%3D%5C%22link%5C%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%5C%22%20%5C%22%7DGitHub%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fa%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fspan%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%20%20%3C%2Fsection%3E%5Cn%20%20%20%20%3C%2Farticle%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by karl** [comment]
@SimenB Would you prefer that the leading `{" "}` was on a line by itself?

**Comment by SimenB** [comment]
Yup, that way opening and closing tags align :)

**Comment by SimenB** [comment]
Same as https://github.com/prettier/prettier/pull/1831#discussion_r119936775

**Comment by karl** [comment]
@SimenB I have a PR that would change the formatting to:

```jsx
const Something = () =>
  <article>
    <section>
      <div>
        <h1 className="u-screen-reader-only">Troika</h1>
        <span className="d1">
          Version: {__VERSION__}
        </span>
        <span className="d1">
          {" "}
          Published: {__DATE__}
        </span>
        <span className="d1">
          {" "}
          <a href="https://github.schibsted.io/finn/troika" className="link">
            {" "}
            GitHub
          </a>
        </span>
      </div>
    </section>
  </article>;
```

Would you be happy with that? Or do you feel there is anything else we could do to improve the formatting?

**Comment by SimenB** [comment]
Yeah, that PR looks exactly like what I want! 🙂

**Comment by karl** [comment]
Closing as the fix has now been merged in 😀
