### ISSUE TITLE
Typescript global keyword

### ISSUE THREAD

**Issue by LaurensRietveld** [prettier/prettier#2327]
Prettier turns this:
```
global {
    export namespace JSX {
    }
}
```
into this:
```
namespace global {
  export namespace JSX {  }
}
```
See [repl](https://prettier.github.io/prettier/#%7B%22content%22%3A%22global%20%7B%5Cn%20%20%20%20export%20namespace%20JSX%20%7B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).

Where the first one declares something globally, the resulting TS makes sure it's scoped to a namespace called 'global' (breaking anything that might depend on the global def).
Tbh, not using such statements myself, but found this issue when applying prettier on some typescript definition files

**Comment by azz** [comment]
Thanks for the report!

I fixed this for `declare global {}`, but not `global {}` it seems. To be honest I didn't know this was valid syntax. 

You can change to `declare global` or use `// prettier-ignore` to get you unblocked while we fix this.

**Comment by LaurensRietveld** [comment]
Didn't know it was valid either... Already managed to work around the issue by updating the defs (or removing it if it wasnt needed anymore). Apparently some old react definitions on definitely-typed use `global {}`
