### ISSUE TITLE
Website: Not formatting styled-components

### ISSUE THREAD

**Issue by zanza00** [prettier/prettier#2328]
I have found two examples in my codebase where prettier fails inside a styled component.

I have replicated the problem in the playground, as you ca see it cannot format the literals (the ugly spacing is to highlight the problem, prettier can still format outside the literals

[div with inner classes](https://prettier.io/#%7B%22content%22%3A%22import%20styled%2C%20%20%20%20%20%20%20%7B%20%20css%20%7D%20from%20%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn'styled-components'%3B%5Cnimport%20theme%20%5Cnfrom%20'theme%2Ftheme'%3B%5Cn%5Cnexport%20const%20header%20%3D%20css%60%5Cn.top-bar%20%7Bbackground%3Ablack%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20margin%3A%200%3B%5Cn%20%20%20%20position%3A%20fixed%3Btop%3A%200%3Bleft%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%200%3Bwidth%3A%20100%25%3B%5Cn%20%20height%3A%20%24%7Btheme.headerHeight%7D%3B%5Cn%20%20%20%20text-align%3A%20center%3Bpadding%3A%2015px%200%3B%5Cnz-index%3A%209999%3B%5Cn%7D%5Cn%5Cn.top-bar%20.logo%20%7B%5Cn%20%20%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ctheight%3A%2030px%3B%5Cnmargin%3A%20auto%3Bposition%3A%20absolute%3B%5Cn%5Cn%5Cn%5Cn%5Cn%20%20%20%20%20%20%20%20%20left%3A%200%3Bright%3A%200%3B%5Cn%7D%5Cn%60%3B%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

[mutiple styled.div in file](https://prettier.io/#%7B%22content%22%3A%22%5Cnimport%20styled%2C%20%5Cn%20%20%5Cn%20%20%5Cn%20%20%5Cn%20%20%5Cn%20%20%5Cn%20%20%7B%20keyframes%20%7D%20from%20%5Cn%20%20%20%20%20%20%20%20%20%20'styled-components'%3B%5Cnimport%5Cn%5Cn%5Cn%5Cn%5Cntheme%20from%20'theme%2Ftheme'%3B%5Cn%5Cnexport%20%5Cn%5Cn%5Cn%5Cn%5Cn%5Cnconst%20StyledContainer%20%3D%20%5Cn%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%5Cn%20%20%20%20%20%20styled.div%60%5Cn%20%20%20%20%20%20%20%20%20%20%20position%3A%20absolute%3B%5Cn%20%20width%3A%20100%25%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20height%3A%2075%25%3B%5Cn%60%3B%5Cn%5Cnexport%20const%20%20%20%20%20%20StyledDiv%20%3D%20%20%20%20%20%20%20%20%20%20styled.div%60%5Cn%20%20background%3A%20%24%7Btheme.mainColor%7D%3B%5Cn%5Cn%5Cn%5Cn%20%20%24%7Btheme.innerContainer%7D%3B%5Cn%60%3B%5Cn%5Cnexport%20const%20Logo%20%3D%20styled.img%60%5Cn%20%20position%3A%20absolute%3B%5Cn%5Cn%5Cn%5Cn%5Cn%20%20top%3A%200%3B%5Cn%5Cn%5Cn%5Cn%5Cn%20%20bottom%3A%200%3B%5Cn%20%20left%3A%200%3B%5Cn%20%20right%3A%200%3B%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%20%20margin%3A%20auto%3B%5Cn%20%20width%3A%2015%25%3B%5Cn%20%20max-width%3A%2090px%3B%5Cn%60%3B%5Cn%5Cnconst%20rotateKeyframe%20%3D%20keyframes%60%5Cn%20%20to%20%7B%5Cn%20%20%20%20transform%3A%20rotate(360deg)%3B%5Cn%20%20%7D%5Cn%60%3B%5Cn%5Cnexport%20const%20StyledLoader%20%3D%20styled.svg%60%5Cn%20%20animation%3A%20%24%7BrotateKeyframe%7D%201.4s%20linear%20infinite%3B%5Cn%5Cn%20%20width%3A%2050%25%3B%5Cn%20%20%5Cn%5Cn%5Cnheight%3A%2050%25%3B%5Cn%20%20position%3A%20absolute%3B%5Cn%20%20top%3A%200%3B%5Cn%20%20bottom%3A%200%3B%5Cn%20%20left%3A%200%3B%5Cn%20%20right%3A%200%3B%5Cn%20%20margin%3A%20auto%3B%5Cn%5Cn%20%20%26%20.path%20%7B%5Cn%20%20%20%20stroke-linecap%3A%20round%3B%5Cn%20%20%20%20stroke-dasharray%3A%20170%3B%5Cn%20%20%20%20stroke-dashoffset%3A%2035%3B%5Cn%20%20%7D%5Cn%60%3B%5Cn%5Cnexport%20const%20TextArea%20%3D%20styled.div%60%5Cn%20%20position%3A%20absolute%3B%5Cn%20%20top%3A%2080%25%3B%5Cn%20%20left%3A%200%3B%5Cn%20%20right%3A%200%3B%5Cn%20%20margin%3A%20auto%3B%5Cn%20%20text-align%3A%20center%3B%5Cn%20%20color%3A%20%24%7Btheme.bgColor%7D%3B%5Cn%20%20font-weight%3A%20%24%7Btheme.fontSemiBold%7D%3B%5Cn%20%20font-size%3A%201.3em%3B%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%20%20text-transform%3A%20uppercase%3B%5Cn%20%20padding%3A%2010px%3B%5Cn%60%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Thanks in advance and if I am doing something wrong let me now.

**Comment by azz** [comment]
You've actually found a bug in the website! We're only loading the parser selected in the dropdown, so the CSS printing doesn't work. 

As a workaround, if you switch to `postcss` and back to `babylon` everything will automagically start working again.

**Comment by zanza00** [comment]
Thanks for the reponse, the second file it's ok now 😃 

the first one still has the problem with the `css` keyword. if I change it to `styled.css` prettier can format the code 

```javascript
// doesn't work
export const header = css`...`

// works
export const header = styled.css`...`

```

 If you need I can open another issue.

**Comment by azz** [comment]
> If you need I can open another issue.

Yeah that'd be great, they're two separate issues.

**Comment by azz** [comment]
Some options to fix this:

1. Load all of the parsers. Con: increases initial responsiveness time.
2. Add some UI to indicate which parsers are loaded. Con: increases UI complexity.
3. Set `process.env.PRETTIER_DEBUG` to true, catch the currently hidden parse error and handle accordingly.

Number three seems the most reasonable.

**Comment by lydell** [comment]
Yet one idea: If the input code contains a `` ` ``, load in all parsers.

**Comment by azz** [comment]
@lydell I implemented number three in #2374 and it seems to work well. Want to take a look?
