### ISSUE TITLE
styled-components not formatting with only the keyword css

### ISSUE THREAD

**Issue by zanza00** [prettier/prettier#2330]
Prettier cannot format the template string if its only consist of `css`

[Here is an example](https://prettier.io/#%7B%22content%22%3A%22import%20styled%2C%20%20%20%20%20%20%20%7B%20%20css%20%7D%20from%20%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn'styled-components'%3B%5Cnimport%20theme%20%5Cnfrom%20'theme%2Ftheme'%3B%5Cn%5Cnexport%20const%20header%20%3D%20css%60%5Cn.top-bar%20%7Bbackground%3Ablack%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20margin%3A%200%3B%5Cn%20%20%20%20position%3A%20fixed%3Btop%3A%200%3Bleft%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%200%3Bwidth%3A%20100%25%3B%5Cn%20%20height%3A%20%24%7Btheme.headerHeight%7D%3B%5Cn%20%20%20%20text-align%3A%20center%3Bpadding%3A%2015px%200%3B%5Cnz-index%3A%209999%3B%5Cn%7D%5Cn%5Cn.top-bar%20.logo%20%7B%5Cn%20%20%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ctheight%3A%2030px%3B%5Cnmargin%3A%20auto%3Bposition%3A%20absolute%3B%5Cn%5Cn%5Cn%5Cn%5Cn%20%20%20%20%20%20%20%20%20left%3A%200%3Bright%3A%200%3B%5Cn%7D%5Cn%60%3B%5Cn%5Cnexport%20const%20header2%20%3D%20styled.css%60%5Cn.top-bar%20%7Bbackground%3Ablack%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20margin%3A%200%3B%5Cn%20%20%20%20position%3A%20fixed%3Btop%3A%200%3Bleft%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%200%3Bwidth%3A%20100%25%3B%5Cn%20%20height%3A%20%24%7Btheme.headerHeight%7D%3B%5Cn%20%20%20%20text-align%3A%20center%3Bpadding%3A%2015px%200%3B%5Cnz-index%3A%209999%3B%5Cn%7D%5Cn%5Cn.top-bar%20.logo%20%7B%5Cn%20%20%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ctheight%3A%2030px%3B%5Cnmargin%3A%20auto%3Bposition%3A%20absolute%3B%5Cn%5Cn%5Cn%5Cn%5Cn%20%20%20%20%20%20%20%20%20left%3A%200%3Bright%3A%200%3B%5Cn%7D%5Cn%60%3B%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) to make it work open **options**, select `postcss` from the dropdown and back to `babylon`

originally found in #2328

**Comment by vjeux** [comment]
Sounds like a good thing to support

```js
css`...`
```

This is the code that is responsible for it: https://github.com/prettier/prettier/blob/master/src/multiparser.js#L292-L308

**Comment by zanza00** [comment]
I have fixed it, I will do a PR in a short time

**Comment by azz** [comment]
This was fixed in #2337
