### ISSUE TITLE
Mixins in styled-components are not put on a newline

### ISSUE THREAD

**Issue by philpl** [prettier/prettier#2331]
Consider a mixin inside some styled-components code:

```js
const Example = styled.div`
  ${p => p.theme.fonts.title}
  color: ${p => p.color};
`;
```

It won't have a semicolon at the end, since it's just a mixin and that semicolon is not necessary at this point in the code.

Then prettier will format it to look like this:

```js
const Example = styled.div`
  ${p => p.theme.fonts.title} color: ${p => p.color};
`;
```

Which still works, but is undesirable :wink:

**Comment by pomber** [comment]
Probably another case of #2291.

**Comment by vjeux** [comment]
Let's close this one in favor of #2291, thanks for the report!
