### ISSUE TITLE
Multiple glob arguments have weird behavior

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#2332]
Example (all files include nesting directories):
```shell
prettier --write '{**/*,*}.{js,jsx,json}'
```
But if i want to ignore some directories (example `vendor` - `composer` for `php`), i am use for `eslint`, `stylelint` and etc second glob argument:
```shell
prettier --write '{**/*,*}.{js,jsx,json}' '!vendor/**'
```
But it is not work with `prettier`. I can do PR if this accept.

**Comment by lydell** [comment]
Could you show which files you expected to be touched, and which actually were touched?

**Comment by evilebottnawi** [comment]
@lydell all files from root directories exclude `vendor` directory.
Also this have weird behavior:
```shell
prettier --write 'src/**/*.{js,jsx,json}' '!src/vendor/**/*.{js,jsx,json}'
```
Want to all files from `src` ignore vendor directory in `src`.

**Comment by lydell** [comment]
So you're saying that an exclude pattern makes no difference? If so, a PR fixing that would be great.

**Comment by evilebottnawi** [comment]
@lydell yep, do PR in near future

**Comment by evilebottnawi** [comment]
Done in https://github.com/prettier/prettier/pull/2356
