### ISSUE TITLE
Single quotes are sometimes replaced with double quotes even when "prettier.singleQuote: true" is specified

### ISSUE THREAD

**Issue by alexjlockwood** [prettier/prettier#2338]
I am using the vscode extension and am having an issue with the prettier.singleQuote setting. The only settings I have customized are:

```
"prettier.singleQuote": true,
"prettier.trailingComma": "all",
"prettier.printWidth": 100
```

Specifically, when prettier is run on a string like this:

```
'You\'ll lose any unsaved changes.'
```

the string is changed to:

```
"You'll lose any unsaved changes."
```

The expected behavior (I think) is to continue using single quotes since the setting prohibits the use of double quotes.

My temporary workaround is to change the string to:

```
`You'll lose any unsaved changes.`
```

**Comment by josephfrazier** [comment]
This is as intended. From https://github.com/prettier/prettier/tree/21733e441dc01f7d85b483edee92b7e7507bfd9a#quotes:

> * If the number of quotes outweighs the other quote, the quote which is less used will be used to format the string - Example: `"I'm double quoted"` results in `"I'm double quoted"` and `"This \"example\" is single quoted"` results in `'This "example" is single quoted'`.

Maybe we should change the preceding description "Use single quotes instead of double quotes." to something like "Prefer single quotes over double quotes.".

**Comment by lydell** [comment]
FYI, this is how Prettier handles quotes:

1. JSX always uses double quotes.
2. The quote that results in the least number of escapes is chosen.
3. Finally, the singleQuote options is used to choose quote.

See also #973.

**Comment by alexjlockwood** [comment]
The reason I reported is because prettier modifies the code to use double quotes, which results in an eslint error. Is there any way this can be avoided?

**Comment by lydell** [comment]
Yes! Disable the ESLint rule. It gains you nothing.

**Comment by alexjlockwood** [comment]
Ahh, good point! Thanks for the advice and the great tool. :)

**Comment by oliamb** [comment]
Instead of disabling it entirely, you can use avoidEscape option (http://eslint.org/docs/rules/quotes).

**Comment by lydell** [comment]
@oliamb Even if you do, the rule still doesn't gain you anything, does it? It only makes ESLint take a little longer to run?

**Comment by oliamb** [comment]
I have at least one interesting use case that can justify this rule. When using string constants, it is useful to be able to search and replace using `'myStringConstant'` rather than `myStringConstant` or `/['"]myStringConstant['"]/`. I was wondering if the rule in prettier will forbad me to do so anymore but it is not the case as it is still deterministic (`'it is green'` VS `"it's green"`)

NB: let's maybe not dive into whether it is a good idea to use string constants ;-)

**Comment by brocoli** [comment]
Code style is all about consistency, it doesn't need to "gain something" beyond consistency for it to be useful.

Still, using `avoidEscape` in eslint seems like a good idea, and the correct resolution to this issue anyway.

**Comment by neossoftware** [comment]
My .prettierrc looks : 

`{
    "useTabs": false,
    "printWidth": 80,
    "tabWidth": 2,
    "singleQuote": true,
    "trailingComma": "none",
    "jsxBracketSameLine": false,
    "parser": "typescript"
}`

**Comment by ConnorChristie** [comment]
FYI the tslint rule for avoid escape is here: https://github.com/palantir/tslint/blob/master/test/rules/quotemark/double-avoid-escape/tslint.json
