### ISSUE TITLE
Enhancement: Comments

### ISSUE THREAD

**Issue by DanielMSchmidt** [prettier/prettier#2340]
Hi there,
First of all thanks for this awesome project, I really love how prettier enables devs to focus on the code and not on formatting.

That being said I might have a bit of a strange use-case: I am currently trying to get a nice human-readable output from babel. As babel is mostly targeting JS only to be used in a form where no human interaction with the code is required anymore it conflicts a bit with my use-case. One of the owners hinted me to prettier, so here I am. It is all related to wix/detox#178, but here is the TL;DR:

I would like to have input like this

```js
class GREYActions {
  /*@return A GREYAction that performs multiple taps of a specified @c count.
*/static actionForMultipleTapsWithCount(count) {}
}
```

formatted look something like this

```js
class GREYActions {
  /*
    @return A GREYAction that performs multiple taps of a specified @c count.
  */
  static actionForMultipleTapsWithCount(count) {}
}
```

Is this something worthy for prettier or is it out of the scope of this project? I would love to do a PR if you hint me to the right direction 👍

**Comment by lydell** [comment]
Thanks for you issue! I think this is tracked in #648, so I'm closing this one. Please tell me if I overlooked something, though!
