### ISSUE TITLE
Enhancement request: End-of-line "//" comments sometimes not positioned well

### ISSUE THREAD

**Issue by mmorearty** [prettier/prettier#2343]
Input:

```
someFunc(
        1, // the loneliest number
        2, // how many it takes to tango
        3  // number of sheets to the wind
      );
```

Output:

```
      someFunc(
        1,
        // the loneliest number
        2,
        // how many it takes to tango
        // number of sheets to the wind
        3
      );
```

**Comment by vjeux** [comment]
Can you tell me how you run prettier to get this result? It works just fine:

```js
someFunc(
  1, // the loneliest number
  2, // how many it takes to tango
  3 // number of sheets to the wind
);
```

https://prettier.io/#%7B%22content%22%3A%22someFunc(%5Cn%20%20%20%20%20%20%20%201%2C%20%2F%2F%20the%20loneliest%20number%5Cn%20%20%20%20%20%20%20%202%2C%20%2F%2F%20how%20many%20it%20takes%20to%20tango%5Cn%20%20%20%20%20%20%20%203%20%20%2F%2F%20number%20of%20sheets%20to%20the%20wind%5Cn%20%20%20%20%20%20)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by mmorearty** [comment]
I ran it from the inline editor in the blog post http://jlongster.com/A-Prettier-Formatter

**Comment by vjeux** [comment]
As mentioned in the other issue, the inline version in this blog post is when prettier was first launched 6 months ago. If you want to see what prettier is doing today, you should use prettier.io :) Thanks!
