### ISSUE TITLE
Comment inside empty class is discarded

### ISSUE THREAD

**Issue by mmorearty** [prettier/prettier#2344]
Input:

```
class C {
  // TODO fill in this class
}
```

or, the same thing with a `/* ... */` style comment.

Output:

```
class Z {}
```

Expected:

The comment would be preserved somehow.

**Comment by vjeux** [comment]
It also seems to be working fine:

https://prettier.io/#%7B%22content%22%3A%22class%20C%20%7B%5Cn%20%20%2F%2F%20TODO%20fill%20in%20this%20class%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by mmorearty** [comment]
Hmm okay. I observed this when using the inline editor in the blog post http://jlongster.com/A-Prettier-Formatter, but you're right. Maybe it's been fixed?

**Comment by vjeux** [comment]
Ohhh, the inline editor in the blog post used the version when prettier was first published. We spent the last 6 months making it drastically better. You should use prettier.io if you want to know what prettier today would output.

**Comment by mmorearty** [comment]
Got it, thanks!
