### ISSUE TITLE
Dictionary key 'value' transformed to 'name'

### ISSUE THREAD

**Issue by kushal** [prettier/prettier#2345]
For example, here's a dif from running `-l` on our code
```
-                    "type": "StringLiteral",
-                    "value": "Wyoming"
+                    "type": "Identifier",
+                    "name": "Wyoming"
```

Thanks for the great tool!

**Comment by lydell** [comment]
I tried to [reproduce](https://prettier.io/#%7B%22content%22%3A%22(%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%22type%5C%22%3A%20%5C%22StringLiteral%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%22value%5C%22%3A%20%5C%22Wyoming%5C%22%5Cn%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) this, but couldn't. Could you show which options you use and exactly how you invoke Prettier?

**Comment by azz** [comment]
Is that an AST diff? Removing quotes from object keys where possible is intentional.

**Comment by vjeux** [comment]
Closing as the author didn't reply.
