### ISSUE TITLE
Way to force dictionary keys to stay quoted?

### ISSUE THREAD

**Issue by kushal** [prettier/prettier#2346]
Sometimes it's useful to leave a key as quoted to indicate it's more string-like than code-like, e.g. this change from -l

```
-  'Alabama': 'AL',
+  Alabama: 'AL',
```

**Comment by lydell** [comment]
Hi, thanks for your issue! This has been discussed before in #1103 and #1108, so I'm closing this one. There is no way to change this behavior, and there is no plan to add a config switch or something. Sorry!

**Comment by kushal** [comment]
Bummer. Is there any guidance on how else to indicate in code which names are okay to mangle to tools like uglify?

**Comment by lydell** [comment]
Does uglify have such a feature?
