### ISSUE TITLE
Typescript cannot parse // inside of JSX 

### ISSUE THREAD

**Issue by bryce-larson** [prettier/prettier#2347]
I'm having a problem with the following when running prettier version 1.5.1 (typescript)
```const link = <a href="example.com">http://example.com</a>```

This might be related to #1578.
This is valid JSX, but the // is being parsed as a comment.
 
The follow console error:
```
Error: Comment location overlaps with node location
    at decorateComment (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:693:11)
    at decorateComment (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:669:7)
    at decorateComment (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:669:7)
    at decorateComment (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:669:7)
    at decorateComment (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:669:7)
    at comments.forEach (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:736:5)
    at Array.forEach (native)
    at Object.attach (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:735:12)
    at attachComments (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:13659:14)
    at formatWithCursor (/Users/username/.nvm/versions/node/v6.11.0/lib/node_modules/prettier/index.js:13711:23)
```

https://prettier.io/#%7B%22content%22%3A%22const%20link%20%3D%20%3Ca%20href%3D%5C%22example.com%5C%22%3Ehttp%3A%2F%2Fexample.com%3C%2Fa%3E%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks for raising this issue, we need to find a solution for this.

**Comment by vjeux** [comment]
In the meantime, you can put it on its own line and add `// prettier-ignore` in front to get it to print

```js
// prettier-ignore
const link = <a href="example.com">
  http://example.com
</a>
```

https://prettier.io/#%7B%22content%22%3A%22%2F%2F%20prettier-ignore%5Cnconst%20link%20%3D%20%3Ca%20href%3D%5C%22example.com%5C%22%3E%5Cn%20%20http%3A%2F%2Fexample.com%5Cn%3C%2Fa%3E%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by azz** [comment]
https://github.com/eslint/typescript-eslint-parser/issues/339

**Comment by phiresky** [comment]
Same issue here. Minimal example:

```
const x = <div>//</div>;
```

**Comment by Kuzmenkoar** [comment]
I`m having same problem.
I used tsx and render should return some text-link:
`<span className='source-popup-row_url'>https://en.wikipedia.org/wiki/Plagiarism</span>`

The next way hasn`t worked: 
`<div>
   {/*prettier-ignore*/}
   <span className='source-popup-row_url'>https://en.wikipedia.org/wiki/Plagiarism</span>
<div/>`

And next one hasn`t worked too
``<div>
   <span className='source-popup-row_url'>
      {/*prettier-ignore*/}
      https://en.wikipedia.org/wiki/Plagiarism
</span>
<div/>``

Even if i add // prettier-ignore before return it doesn`t help me.
Can somebody give me some example how to deal with it??

I dont like this way!!! 
`<span className='source-popup-row_url'>
    https:{'/'}{'/'}en.wikipedia.org/wiki/Plagiarism
</span>`

**Comment by lydell** [comment]
@Kuzmenkoar Until the bug is fixed, I think this is the nicest workaround:

```js
<div>
  <span className='source-popup-row_url'>
    {'https://en.wikipedia.org/wiki/Plagiarism'}
  </span>
<div/>
```

**Comment by mattyfresh** [comment]
Been a while since this thread was updated, any progress made on this?  If someone can point me in the right direction I can try and fix this issue!

For the record, we ended up going with @lydell solution of putting the entire url in curly brackets like `{'http://foo-bar/baz'}`.  Not the end of the world, just concerned that this will trip up devs (junior or otherwise) unless we have it noted in a README somewhere.

**Comment by trusktr** [comment]
Please fix this one. Thanks for the great work on prettier!

**Comment by balupton** [comment]
Any ETA on this? For users of the prettier eslint plugin, this is causing eslint checks to fail.

**Comment by vjeux** [comment]
This is still an issue in the underlying parser unfortunately: https://github.com/JamesHenry/typescript-estree/issues/6

**Comment by JamesHenry** [comment]
FYI I started https://github.com/prettier/prettier/pull/5728

**Comment by JamesHenry** [comment]
PR is ready for review, you can take a look at the original source given in this issue here:

https://deploy-preview-5728--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEAbAllAa0wF5MAeAQ0wAsAnOAM2IB0Q4APCgWwAds4AdJC6sAfNRgweSAPQyO3PoOFkZFUSAA0ICDxi50yUBVq0IAdwAKJhGmQgKANwi4AJlpAAjWhTAE4MADKPL74AObIMLQArnDaElzYAOrUuPBoIWBwgbZpuI5pAJ72YGh22vhocLQwlj5hXBTIDBTYVdoAVmjsAEI+fgGB3HAAMvhwza3tIF3sgeH8AIrREPCTbXEgIbRVtPYwhTxwaGC0uHoePGewSW4w1MgAHAAM2lcQVUk+PPZXx9WOCbaegAR2iuHodQoDSaSBaG20VS4uEiMU2aAWcGWqwmcKmmxgFE8t1c92QACZtFEKLg8FAwgBhCBcRr2KDQIEgaJVAAqRLseI2AF8hUA
