### ISSUE TITLE
How to tell prettier to keep first func argument on the same line as opening parenthesis?

### ISSUE THREAD

**Issue by umarashfaq** [prettier/prettier#2349]
I need this because [it breaks syntax highlighting in my editor](https://github.com/Microsoft/TypeScript-TmLanguage/issues/481#issuecomment-311246670), and apparently there is no way to fix it.

**Comment by k15a** [comment]
There is no way to tell Prettier to do this. This should probably be fixed by the syntax highlighting.

**Comment by rattrayalex** [comment]
Please report the bug in your syntax highlighter, or try another one.

**Comment by radosavljevic** [comment]
Apparently this will not be fixed in the syntax highlighter, is there any other way to fix this?

https://github.com/Microsoft/TypeScript-TmLanguage/issues/481
