### ISSUE TITLE
styled-components formatting issues

### ISSUE THREAD

**Issue by gribnoysup** [prettier/prettier#2350]
Hi team!

~~I'm not sure that the following examples of formatting are bugs, intentional decisions or just corner cases that were skipped during development. So I just want to share them with you and get some feedback.~~

~~I understand the rationale behind prettier, so if these are not bugs but intentional, it is okay, i'd just want to know this :)~~

~~1) When css rule is one line, it is collapsed~~

~~This one is the minor one, but still not very convenient. I'm extending some component and start with one simple rule. I'll probably add more after this initial one and I don't want even one-liners to collapse. If you look [at some examples in styled-components ](https://www.styled-components.com/docs/basics#react-native), you can see that this is a common pattern for many styled components to leave template literal multiline.~~

~~2) Template literal expressions collapsed with next line~~

~~This one is a real pain. If you have an expression that takes full line in template literal and there is no semicolon at the end of the line, newline is removed and the next line is collapsed with it. This could quickly became a total mess if you have several lines of expressions like that.~~

3) Semicolon is inserted at the end of template literal if it ends with expression

This just looks like a bug.

Example:

```jsx
const RedBlock = styled.div`
  display: block;
  background-color: red;
  ${props => props.rounded && 'border-radius: 5px;'}
`;

// After formatting --->

const RedBlock = styled.div`                        
  display: block;
  background-color: red;
  ${props => props.rounded && 'border-radius: 5px;'}; // <-- notice this semicolon
`;
```

**Comment by gribnoysup** [comment]
I could try to fix some of those you somebody will assist me or at least point me to the right direction 😺

**Comment by gribnoysup** [comment]
Oops, sorry, I totally missed https://github.com/prettier/prettier/issues/2291, where 1) and 2) are already mentioned. I'll change the original post and only leave 3), I couldn't find the same issue in any other issue

**Comment by danilobuerger** [comment]
This got worse now with the 1.6 release where its also applied inside `styled("div")` template strings

**Comment by nryoung** [comment]
This is totally preventing me from using prettier. I wish there was a way to exclude template strings from formatting rules.

**Comment by lydell** [comment]
@nryoung Just in case you didn't know, one workaround is to add a `// prettier-ignore` comment to every problematic template string ([playground](https://prettier.io/playground/#%7B%22content%22%3A%22%2F%2F%20prettier-ignore%5Cnconst%20RedBlock%20%3D%20styled.div%60%5Cn%20%20display%3A%20block%3B%5Cn%20%20background-color%3A%20red%3B%5Cn%20%20%24%7Bprops%20%3D%3E%20props.rounded%20%26%26%20%27border-radius%3A%205px%3B%27%7D%5Cn%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)).

**Comment by arvinsim** [comment]
My problem is that it turns

```
const Wrapper = styled.div`
  background-color: orange;
`
```

to

```
const Wrapper = styled.div`background-color: orange;`
```

which triggers the `block-opening-brace-space-after` and `block-opening-brace-space-before` stylelint errors

**Comment by lydell** [comment]
@arvinsim There’s no need to have stylelint (or ESLint for that matter) check for stylistic things – you always end up with conflicts between the linter and Prettier (see [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier/) for more information). So just turn those rules off and your problem is solved :)

**Comment by ckknight** [comment]
I have to add `// prettier-ignore` before every one-line `styled` call because of the issue @arvinsim is running into.

I _do not want_ prettier to collapse those template strings into a single line, even if it can fit, because then it would look inconsistent with every other `styled` call.

**Comment by lydell** [comment]
@ckknight I agree that the code looks nicer when the newlines aren't removed; @arvinsim's comment was about trouble with stylelint, not a request to change Prettier's output, though.

**Comment by vjeux** [comment]
@ckknight why not add a `;` at the end of each line and be done with it?

**Comment by vjeux** [comment]
I don't think that the fact that it inlines the string was a conscious decision. It indeed looks weird to have those inlined when the rest isn't. Someone should try to always expand single lines and see how it feels.

**Comment by dgcoffman** [comment]
@ckknight see https://github.com/prettier/prettier/issues/2291#issuecomment-311489067

**Comment by ryanzec** [comment]
any update of the #3 of the original issue as this is causing a plugin the styled-compoents plugin I am using in vscode to say there is an error in my code when there is not?

**Comment by ryanzec** [comment]
@j-f1 While I would love to try to fix that, not sure that I can. I spent a couple of hours trying to fix this and while I was able to get it fixed for a number of use cases, there are still a few use cases that don't work (or that my changes break) and unfortunately don't have enough free time to really dig into the code to understanding what is actually going on since I have no prior knowledge of this codebase.

**Comment by evilebottnawi** [comment]
Can fix this tomorrow, if problem not in scope, feel free to ping me

**Comment by ryanzec** [comment]
@evilebottnawi If you would like I can upload what I have done so far however I don't this it is any in the right direction as the more I tried to fix things, the more other things broke.

**Comment by evilebottnawi** [comment]
@ryanzec PR welcome :+1:

**Comment by evilebottnawi** [comment]
Btw it should be easy fix, wip

**Comment by evilebottnawi** [comment]
Done, it will be very easy :smile:

**Comment by evilebottnawi** [comment]
It will be not easy as i think :smile: 
@ryanzec Done in https://github.com/prettier/prettier/pull/4151

**Comment by fisker** [comment]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAwB0oACa41ABywEMMlqAjLCMAawG4qtDsz4BzAE4QArlFwBaSNwnsJeQTWoASYAykNU1ALwA+anogH8U2bjzUAZA+oByDhAl2J8ic2LTUdgBWBgAPfhcAXyoyDRAAGhBLGCJoVGRQZgkpAHcABSyEdJRmEggiXASQDl8+OBgAZQZRIigxZBgJaThEgAsYAFssAHVeonhGUTgGovHScYxkcFR0xNbUOAkYPN8xAeZkADNmLA3EgCtUUIAhWt56huYBuAAZVrgjk7OQS9CG1rEOAAitIIPBPqceiBmhINhIlv0hlU9K0YMMKjBesgABwABkSFg2w18DCWejgcJIH0SAEdQfAdpZiiBmKh5FA4Hg8FU1HSiGodsw9gckMdIYkNgMiB0ulDUADgfSPqKvlCYMwOOjcJjkAAmRKdZhELAAgDCEAG+yWUGg1JAATgABUNcUxRtIpEgA)
```sh
--parser html
```

**Input:**
```html
styled.div`
  display: block;
  background-color: red;
  ${props => props.rounded && 'border-radius: 5px;'}
`;

```

**Output:**
```html
styled.div` display: block; background-color: red; ${props => props.rounded &&
'border-radius: 5px;'} `;

```

**Comment by fisker** [comment]
please close

**Comment by lydell** [comment]
Looks like this has been fixed at some point then. Feel free to open a new issue if there still are buggy cases!
