### ISSUE TITLE
Parenthesis of Function types in flow removed

### ISSUE THREAD

**Issue by age2pierre** [prettier/prettier#2351]
When i run prettier against this code :
```js
// @ flow
const myFunc = (aFunc: (number) => number): number {
  return myFunc(0)
}
```
It get changed into :
```js
// @ flow
const myFunc = (aFunc: number => number): number {
  return myFunc(0)
}
```
Prettier seems to not distinguish between arrow function and function types

**Comment by vjeux** [comment]
The example that you have given is not valid JavaScript, it doesn't parse:

```js
SyntaxError: Unexpected token : (2:43)
  1 | // @ flow
> 2 | const myFunc = (aFunc: (number) => number): number {
    |                                           ^
  3 |   return myFunc(0)
  4 | }
```

If you put a `=>` in there it does parse and outputs something that is similar to what you experience:

```js
// @ flow
const myFunc = (aFunc: (number) => number): number => {
  return myFunc(0)
}
```

outputs

```js
// @ flow
const myFunc = (aFunc: number => number): number => {
  return myFunc(0)
}
```

but it is valid JavaScript. We just remove the parenthesis around the first argument the same way we do it for non-type arrow functions. Is this not what you expect?

**Comment by age2pierre** [comment]
You're right about that arrow... my bad.
![image](https://user-images.githubusercontent.com/8728093/27740345-0c45ab78-5db2-11e7-8d56-c23adcab35a7.png)
In fact Flow doesn't complain... only Webstorm parser does. I guess I'll close that issue and i'll see with Jetbrain about those misleading syntax highlights.
