### ISSUE TITLE
Add padded blocks

### ISSUE THREAD

**Issue by piotrblasiak** [prettier/prettier#2352]
I love prettier so far, but it would make the code much more readable for a lot of people I think if you added the option to get padded blocks (http://eslint.org/docs/rules/padded-blocks).

**Comment by vjeux** [comment]
Hey @piotrblasiak, I'm sorry but we're not going to support this style inside of prettier :(

**Comment by azz** [comment]
You should be able to use `eslint-plugin-prettier` and then use `eslint --fix` to get that style.

**Comment by lydell** [comment]
@azz No, that would create conflicts. [prettier-eslint](https://github.com/prettier/prettier-eslint) is what you need here.

**Comment by azz** [comment]
Ah of course, I had my wires crossed because my editor "format" binding runs `prettier --write`, not `eslint --fix`.
