### ISSUE TITLE
Do I need to install postcss-scss module to autoformat scss?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2360]
I get this error. Not very sure whether it's because of Prettier or not. https://github.com/prettier/prettier/releases/tag/1.4.0

```
Error: Cannot find module 'postcss-scss'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
```

Have this in my code

```
    "*.scss": [
      "stylelint --syntax=scss",
      "prettier --parser postcss --use-tabs --write",
      "git add"
    ],
```

**Comment by hawkrives** [comment]
You might try upgrading to prettier 1.5?

I know that Prettier bundles it's source code before publishing to npm, but I forget if it bundles all of the optional parsers or not.

**Comment by vjeux** [comment]
Prettier bundles all its dependencies, so this is not because of it. It's likely `stylelint --syntax=scss`
