### ISSUE TITLE
Flaky snapshot test?

### ISSUE THREAD

**Issue by azz** [prettier/prettier#2361]
Seen this test fail twice now. Need to figure out why.

![image](https://user-images.githubusercontent.com/1297597/27734203-15ba2d34-5ddd-11e7-8cd7-a63295dccd70.png)

**Comment by vjeux** [comment]
I've also seen it fail, not sure what's going on :(

**Comment by azz** [comment]
`src/parser-create-error.js:5:17` is the `new` in `new SyntaxError`:

```js
function createError(message, loc) {
  // Construct an error similar to the ones thrown by Babylon.
  const error = new SyntaxError(
    message + " (" + loc.start.line + ":" + loc.start.column + ")"
  );
  error.loc = loc;
  return error;
}
```

I don't get how that can possibly be null?

**Comment by azz** [comment]
Do'h! I just realised the message `"Cannot read property `'loc'` of null"` is not coming from that function, it's from somewhere in `typescript-eslint-parser`.

**Comment by azz** [comment]
Haven't seen this since 123d350 (which wasn't supposed to be a fix) so I guess we can close it.
