### ISSUE TITLE
Combination of UTF-8 BOM, Block comment, and Interpolated string breaks

### ISSUE THREAD

**Issue by Kerrick** [prettier/prettier#2362]
As you can see in [this link](https://prettier.io/#%7B%22content%22%3A%22%EF%BB%BF%5Cn%5Cn%2F*%20Block%20comment%20*%2F%5Cn%5Cnhtml%20%7B%5Cn%20%20content%3A%20%5C%22%23%7B1%7D%5C%22%3B%5Cn%20%20%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D), there is a problem prettifying a file that meets the following conditions:

- The file begins with a UTF-8 BOM
- There is a CSS block comment within the file
- There is a Sass interpolation within the file

In that case, the Block comment's closing `/` is omitted, causing the rest of the file to be commented out.

**Comment by anthony-redFox** [comment]
@vjeux  Why I get string without BOM? 

in change log wrote:
```
// After
[BOM]/* Block comment */
html {
  content: "#{1}";  
}
```
But I get without BOM string. And currently prettier converts file from UTF-8-BOM to just UTF-8.

**Comment by azz** [comment]
I think this is intentional. Any reason you need a byte order mark?

**Comment by anthony-redFox** [comment]
We use BOM for detect that file in UTF-8 encoding and tool opens js files and check BOM in build procedure. Unfortunately, I don't know the same easy way to detect just UTF-8.

We had the issue when one of developer added symbol NEL(https://en.wikipedia.org/wiki/Newline) and it is looks like '...' in Windows-1252 encoding. But Japanese Windows IE  it is parses like UTF-8 encoding as new line and the JavaScript file has syntaxes error. Yes, it is very old bug, but I don't know a way to 100% detect  that file is UTF-8.

**Comment by azz** [comment]
I'd have to check, but I'm fairly sure prettier is hardcoded to parse files as utf-8, so even with BOM it probably won't work.

**Comment by josephfrazier** [comment]
Maybe we should reprint the BOM if it was present in the input? It sounds like not doing so, was just an oversight in the first place... https://github.com/prettier/prettier/pull/2373#issue-239940547

**Comment by anthony-redFox** [comment]
@josephfrazier @azz  Can you verify commit #3283 ?

**Comment by Download** [comment]
> Unfortunately, I don't know the same easy way to detect just UTF-8.

There is no easy way to detect UTF-8 without a BOM. Trying to detect the encoding is done in some apps using heuristics (e.g. if we detect certain characters it's probably UTF-8).

> Maybe we should reprint the BOM if it was present in the input?

Please do. The Unicode BOM is part of the Unicode standard and as such actually the best way to include the meta information of what encoding was used inside the Unicode text itself. I would recommend all tool authors *writing* Unicode to include the BOM and *reading* Unicode to use it to detect the encoding and then skip it.

**Comment by josephfrazier** [comment]
@Download we're working on it, see https://github.com/prettier/prettier/pull/3283

**Comment by azz** [comment]
From wikipedia (emph mine):

> The Unicode Standard permits the BOM in UTF-8,[3] but **does not require or recommend its use**.[4] Byte order has no meaning in UTF-8,[5] so its only use in UTF-8 is to signal at the start that the text stream is encoded in UTF-8, or that it was converted from another stream that contained an optional BOM. The **standard also does not recommend removing a BOM when it is there**, so that round-tripping between encodings does not lose information, and so that code that relies on it continues to work.[6][7]

**Comment by Download** [comment]
It also does not ban it's use, or recommend against it. But in practice, the Unicode BOM is useful to distinguish ascii/latin from utf-8. Without it, editors are left guessing at the encoding. Many editors will pick a wrong encoding if no BOM is present.
