### ISSUE TITLE
Multi-line comments are not formatted properly if there are long strings before it

### ISSUE THREAD

**Issue by sathishpaul** [prettier/prettier#2363]
Hi,

Thanks for making prettier. 

I am working in an AMD environment and I notice that long dependency names trip up the alignment of multi-line comments after prettier has formatted JS code. I have set the print width to be 120, all other options are the default.

Please see this link to view the issue [Link to reproducible example on prettier.io](https://prettier.io/#%7B%22content%22%3A%22define(%5B%5C%22myDep1%5C%22%2C%20%5C%22myDep2%5C%22%2C%20%5C%22jquery%5C%22%2C%20%5C%22myDep3%5C%22%2C%20%5C%22someOhterRandomDep%5C%22%2C%5Cn%5C%22aReallyLongDependencyName-that-didnt-quite-fit-in-the-previous-line%5C%22%5D%2C%5Cnfunction%20()%20%7B%5Cn%20%20function%20ObjectMetricsModel(params)%20%7B%20%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20some%20long%20line%20of%20comment%20goes%20here.%20Typically%20it%20is%20typed%20over%20%5Cn%20%20%20%20%20*%20multiple%20lines%20like%20these.%20Also%20the%20multi%20line%20comment%20is%20generated%20by%20editors%5Cn%20%20%20%20%20*%20when%20a%20user%20type%20the%20characters%20%2F%20*%20*%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20this.myFunctionName%20%3D%20function%20()%20%7B%5Cn%20%20%20%20%20%20%2F%2Fdo%20something%20here%5Cn%20%20%20%20%7D%3B%5Cn%20%20%20%20%5Cn%20%20%20%20%2F%2FA%20lot%20of%20other%20code%20here%2C%20removed%20for%20brevity%5Cn%20%20return%20ObjectMetricsModel%3B%5Cn%20%20%7D%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Basically, code with comments like this:

```js
    /**
     * some long line of comment goes here. Typically it is typed over 
     * multiple lines like these. Also the multi line comment is generated by editors
     * when a user type the characters / * *
     */
    this.myFunctionName = function () {
      //do something here
    };
```
    
gets formatted like this

```js
      /**
     * some long line of comment goes here. Typically it is typed over 
     * multiple lines like these. Also the multi line comment is generated by editors
     * when a user type the characters / * *
     */
      this.myFunctionName = function() {
        //do something here
      };
```

My only gripe is that comments that are on the lines after the / * are missing a space at the beginning. I was able to narrow down the issue to the length of the included dependency in the define() call (please see link above). If I remove the one particularly long-string in the dependencies list, the formatting is pretty awesome. As I missing something else?

It is a very minor detail, but will be great to have the prettier formatting working as expected for multi-line comments in all cases. If there is something wrong in the example code(structurally or otherwise), please let me know.

-Sathish.

**Comment by lydell** [comment]
What happens here is that when the array no longer fits in a single line and Prettier breaks it, the rest of the function needs to be indented one extra level. The start of the comment is indented to this new level, but everything _inside_ the comment is left exactly like it was before, because Prettier never changes the contents of comments – yet. That is tracked in #648, so I’m closing this one. Thanks for your issue, though!

**Comment by sathishpaul** [comment]
Thanks a lot for the explanation. I look forward to issue #648 being fixed. 👍
