### ISSUE TITLE
What is the difference between Prettier, StandardJS and ESLint?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2364]
I understand that [Prettier is code formatter only, not linter](https://github.com/prettier/prettier/blob/master/README.md#how-does-it-compare-to-eslint-or-tslint-stylelint) but I don't understand well that how StandardJS is different from Prettier and how StandardsJS and ESlint are different.

**Comment by vjeux** [comment]
Standard is a set of eslint rules, some of them with autofix. When you do not comply it's going to warn you.

**Comment by jitendravyas** [comment]
> Standard is a set of eslint rules, some of them with autofix

But should not I use Eslint then, as it has `--fix` option too?

**Comment by vjeux** [comment]
Sorry misclick. Prettier takes your code and reprints it from scratch. So there's only one way code can be printed, not many.

In your workflow, with prettier you can just write code in one line and press format, and you've got it printed. With standard if you do that, you'll be warned but it won't actually reformat it in most cases.

**Comment by lydell** [comment]
Is the action here to add a little note about standard in the readme?

**Comment by jitendravyas** [comment]
Yes and and example would be better too

**Comment by azz** [comment]
There's already [explanation in the readme](https://github.com/prettier/prettier#how-does-it-compare-to-eslint-or-tslint-stylelint) and links to `standard` tools in Related Projects. I don't think it should be prettier's responsibility to explain what `standard` is.

**Comment by jitendravyas** [comment]
You are right that it's not a prettier's responsibility to explain what `standard` is but for some people, it's not easy to know the difference between these tools. 
Standard is the only tool which looks similar to Prettier so an explanation would be good to have, not must to have.

**Comment by jitendravyas** [comment]
I liked how this project shows comparison with similar tools https://www.npmjs.com/package/file-name-linter
