### ISSUE TITLE
CSS-in-JS template strings with ternaries

### ISSUE THREAD

**Issue by trevordmiller** [prettier/prettier#2365]
First off, thank you for such a fantastic tool! Really helps ease the burden of formatting :)

Could CSS-in-JS template strings with ternaries be improved? Lines 36-45 in the attached example show some odd output for ternaries in CSS-in-JS template strings:
![image](https://user-images.githubusercontent.com/5497885/27755954-9cdc99fa-5db0-11e7-99b6-38f5eda0753c.png)

Thank you!

**Comment by vjeux** [comment]
Do you have any suggestions on how to print it in an optimal way?

**Comment by trevordmiller** [comment]
@vjeux Although it is just my opinion, I think the formatting for vanilla JavaScript ternaries + template strings is great; here is the same syntax pulled out of a CSS-in-JS component, formatted with prettier:
![image](https://user-images.githubusercontent.com/5497885/27756742-b0c7d3c4-5db7-11e7-84a4-09b861693f69.png)

VS when it is in a styled-component:
![image](https://user-images.githubusercontent.com/5497885/27756779-0da1708c-5db8-11e7-85a8-c9cd24c35260.png)

The main diffference being each sub template literal expression has its own line.

I don't know how prettier works, but it seems that maybe the difference is the inner template literals being a function vs just an expression?

Anyways, not a big deal - prettier has been fantastic for almost everything but this :) I really apprecaite all the great work!

**Comment by vjeux** [comment]
There is an issue opened for the bug where it puts all those expressions inline instead of on every line. We want to fix it but not sure yet how.

In the meantime, if you add ; at the end, it prints on their own line.

**Comment by trevordmiller** [comment]
@vjeux Oh ok, great to know! Sorry for the duplicate issue. Will close and follow the other one. Thank you.
