### ISSUE TITLE
Appears to break HTML

### ISSUE THREAD

**Issue by bradennapier** [prettier/prettier#2366]
I believe something is going on with the HTML.  Prettier is breaking and giving errors on the HTML I have here.  

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dash OS - System Monitor</title>
    <script>
      (function() {
        if (!process.env.HOT) {
          const link = document.createElement('link');
          link.rel = 'stylesheet';
          link.href = './dist/style.css';
          // HACK: Writing the script path should be done with webpack
          document.getElementsByTagName('head')[0].appendChild(link);
        }
      }());
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script>
      {
        const scripts = [];

        // Dynamically insert the DLL script in development env in the
        // renderer process
        if (process.env.NODE_ENV === 'development') {
          scripts.push('../dll/vendor.dll.js');
        }

        // Dynamically insert the bundled app script in the renderer process
        const port = process.env.PORT || 1212;
        scripts.push(
          (process.env.HOT)
            ? 'http://localhost:' + port + '/dist/bundle.js'
            : './dist/bundle.js'
        );

        document.write(
          scripts
            .map(script => '<script defer src="' + script + '"><\/script>')
            .join('')
        );
      }
    </script>
  </body>
</html>

```

This will actually format the first time -- it formats it to a really weird format though.  Then after it formats it then it is broken and gives me "Unterminated template" at the document.write:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dash OS - System Monitor</title>
    <script>
    (function () {
  if (!process.env.HOT) {
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = './dist/style.css';
    // HACK: Writing the script path should be done with webpack
    document.getElementsByTagName('head')[0].appendChild(link);
  }
}());
</script>
  </head>
  <body>
    <div id="root"></div>
    <script>
    {
  const scripts = [];

  // Dynamically insert the DLL script in development env in the
  // renderer process
  if (process.env.NODE_ENV === 'development') {
    scripts.push('../dll/vendor.dll.js');
  }

  // Dynamically insert the bundled app script in the renderer process
  const port = process.env.PORT || 1212;
  scripts.push(
    process.env.HOT ? `http://localhost:${port}/dist/bundle.js` : './dist/bundle.js',
  );

  document.write(scripts.map(script => `<script defer src="${script}"></script>`).join(''));
}
</script>
  </body>
</html>

```

Additionally, may be a good idea to allow turning off the formatting of HTML?

**Comment by bradennapier** [comment]
**Note:** In this case if i manually add the escape character back to the the `</script>` it starts working again.  So it's likely the parser is simply not expecting html within javascript within html :)

**Comment by bradennapier** [comment]
PS: Absolutely freaking love this package!  Going through the hundreds of scripts and saving and seeing the results was definitely an interesting / fun experience :)

**Comment by azz** [comment]
HTML support hasn't actually shipped yet. Check out #2097 as it ties in with Vue support.

But how are you invoking prettier? Prettier will never replace concatenated strings with template strings, which makes me think you might be using a different formatting tool.

**Comment by bradennapier** [comment]
I am using atom-prettier - I do not have any other tools that I am aware of, although it is possible that the passing to eslint --fix is doing it?

**Comment by bradennapier** [comment]
Hmm if it isnt activated yet then why does my Javascript Scopes look like this:

```
source.js, source.jsx, source.js.jsx, source.babel, source.js-semantic, text.html.basic, text.html.vue
```

It is now completely broken - ih ave no idea why - i can not hot reload as prettier fails and errors out whenever i do it

"unknown type: "Import"

**Comment by azz** [comment]
If you can't reproduce it on https://prettier.io/ you should raise this issue with [pretier-atom](https://github.com/prettier/prettier-atom/issues).

(Re-open this if you do manage to reproduce)
