### ISSUE TITLE
There is no info in read me about Who made Prettier who are main maintainers?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2369]
Many people think that it's developed by Facebook and influence by React and JSX and formatting rules are mainly in favour of Facebook  #developers. Tool use used by Facebook and React community mainly.

A section in readme could be useful.

**Comment by azz** [comment]
This information is available through GitHub itself.

Contributors:
https://github.com/prettier/prettier/graphs/contributors

We also have a "projects using prettier" section in the main README.
