### ISSUE TITLE
.json which include comments

### ISSUE THREAD

**Issue by bryce-larson** [prettier/prettier#2378]
Although comment in json files are not part of the spec, they are used in some project.
Please support comments within json file, or else maybe a work could be if the .json file starts with `// prettier-ignore` it would tell prettier to ignore the entire json blob.

**Comment by azz** [comment]
I agree we should do one of those things.

@josephfrazier Do we have the ability to attach comments to the JSON ast?

**Comment by lydell** [comment]
Related: #2301

**Comment by josephfrazier** [comment]
> @josephfrazier Do we have the ability to attach comments to the JSON ast?

Not with `json-to-ast`, but we probably could switch to `babylon.parseExpression` instead.

**Comment by vjeux** [comment]
Could we use babylon.parseExpression() for json and if parser is json then output double quotes and no trailling commas.

This way, if people have valid json, it's going to print it correctly. If they have comments or other non standard features, we're still going to print it.

**Comment by josephfrazier** [comment]
Wait, so have you changed your mind from https://github.com/prettier/prettier/pull/2301#issuecomment-311712810?

> I don't think that's a good idea to use a loose json parser here. There are plenty of times where people name files .json but the tools are actually more lenient and accept any JavaScript. I'd rather the json mode to throw if it's not valid json than to try and "fix" json and drop things as a result.

**Comment by vjeux** [comment]
I don't want to drop comments (or things ever). But if the comments are already there and we can preserve them, then I'm all for it.

**Comment by josephfrazier** [comment]
Ah, so it's ok to parse invalid/extended JSON, as long as everything is preserved. I might try to get replace `json-to-ast` with `babylon.parseExpression`, since it sounds like that would meet the requirements.

**Comment by Robinfr** [comment]
This could also be supported with the [json-ast](https://github.com/neuroo/json-ast) parser but it doesn't seem to want to write the JSON back however..

```bash
test.json: SyntaxError: (json-to-ast) Cannot tokenize symbol </> at (4:5)
  2 |     "test": "foo",
  3 |     "test2": "bar"
> 4 |     /*test*/
    |     ^
  5 | }
  6 | 
```

**Comment by josephfrazier** [comment]
This should be fixed by https://github.com/prettier/prettier/commit/a78d1389f6addf73d5364941d242f8aae79fc8b8

**Comment by Robinfr** [comment]
So is outputting the comments going to be added also?

**Comment by josephfrazier** [comment]
Yes, comments are printed out as of that commit. Note that they might move around a little, due to difficulties with determining which node they belong to:

```bash
$ echo '/*comment*/ [1,2,3]' | ./bin/prettier.js --parser json
[/*comment*/ 1, 2, 3]
```
