### ISSUE TITLE
Does Prettier do this by default no-missing-end-of-source-newline for CSS and SCSS file?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2381]
If I use prettier for `scss` can I remove this rule from https://stylelint.io/user-guide/rules/no-missing-end-of-source-newline/ ?

**Comment by lydell** [comment]
yes

**Comment by jitendravyas** [comment]
Don't see anything regarding it in docs or not able to find

**Comment by jitendravyas** [comment]
I formatted a scss file with prettier but see this in diff

**Comment by jitendravyas** [comment]
any comment on it? @lydell

**Comment by hawkrives** [comment]
I can't tell if that diff is saying that the _old_ copy had no newline, or if the _new_ copy has no newline. Prettier should ensure that there is a newline at the end of the file.

**Comment by vjeux** [comment]
prettier does add a new line at the end of the file. If you see a case where it doesn't, it's a bug.

**Comment by jitendravyas** [comment]
How can we test it properly?

**Comment by vjeux** [comment]
prettier file.css | cat -e

See if there's a $ on the last line
