### ISSUE TITLE
Confusing documentation for column width being default at 80

### ISSUE THREAD

**Issue by zaccolley** [prettier/prettier#2382]
Hey there, looking at: https://github.com/prettier/prettier#print-width

And it says:

> **We strongly recommend against using more than 80 columns.**

Is there a reason why, and should we update the docs to reflect this reason?

**Comment by k15a** [comment]
https://github.com/prettier/prettier/issues/2375

**Comment by zaccolley** [comment]
Cheers for the explanation but I don't know think this is closed as the documentation is still confusing. 

Shall I create a PR with your explanation added to that part of the documentation?

**Comment by lydell** [comment]
@zaccolley If you feel like you can clarify this section it would be great:

> Prettier works by cramming as much content as possible until it reaches the limit, which happens to work well for 80 columns but makes lines that are very crowded. When a bigger column count is used in styleguides, it usually means that code is allowed to go beyond 80 columns, but not to make every single line go there, like Prettier would do.
