### ISSUE TITLE
varying exit codes with --stdin

### ISSUE THREAD

**Issue by lukebaker** [prettier/prettier#2389]
I would like to have prettier return with an exit code of 1 when the input from STDIN is altered by prettier. In other words, I'd like the exit code behavior of `--list-different` when using `--stdin`. I don't know if this needs to be a separate option or if we can just re-use the `--list-different` option.

Is this possible / reasonable?

**Comment by vjeux** [comment]
We should definitely not return a non zero exit code with `--stdin` if the output is different by default. It would mean that the command failed.

If you want to make it work with --list-different, maybe. Could you describe your use case?

**Comment by josephfrazier** [comment]
I think it's reasonable to have `prettier --stdin --list-different` return non-zero if the output is different. For reference, this is how `prettier --stdin --debug-check` currently behaves when the following code (from https://github.com/prettier/prettier/issues/2194#issue-236906192)  is input:

```js
let icecream = what == "cone"
  ? p => !!p ? `here's your ${p} cone` : `just the empty cone for you`
  : p => `here's your ${p} ${what}`;
```

**Comment by lukebaker** [comment]
> We should definitely not return a non zero exit code with `--stdin` if the output is different by default. 

Agreed.

> If you want to make it work with --list-different, maybe. Could you describe your use case?

Yes, this is the sort of thing I had in mind, but I wasn't sure if `--list-different` would fit as nicely for input from STDIN.

My use case is verifying that the content within the git index is formatted properly. The directions in the README for lint-stage run prettier on staged filenames but using their content in the *working tree* rather than the content of those files within the git index. I'd like to be able to run `git show :path/to/file | prettier --stdin --list-different` and have the exit code be non-zero when the prettier output is different from the input. I'm looking for a precommit hook setup that'll bail if the staged content is not prettier-formatted, even when the working tree is prettier-formatted.

**Comment by vjeux** [comment]
That sounds good. If you want to make --list-different to work with --stdin, I'll merge a pull request

**Comment by josephfrazier** [comment]
I just submitted #2393 to fix this.

> The directions in the README for lint-stage run prettier on staged filenames but using their content in the *working tree* rather than the content of those files within the git index. I'd like to be able to run `git show :path/to/file | prettier --stdin --list-different` and have the exit code be non-zero when the prettier output is different from the input.

@lukebaker, once you have this working, would you be willing to write up how you did it? It sounds like this behavior should be preferred over simply checking what's on disk.
