### ISSUE TITLE
do-expression formatting

### ISSUE THREAD

**Issue by ambar** [prettier/prettier#2390]
[https://prettier.io/playground/#...](https://prettier.io/playground/#%7B%22content%22%3A%22let%20component%20%3D%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%7Bdo%20%7B%5Cn%20%20%20%20%20%20if%20(true)%20%7B%20%5Cn%20%20%20%20%20%20%20%20%3CA%20%2F%3E%5Cn%20%20%20%20%20%20%7D%20else%20%7B%20%5Cn%20%20%20%20%20%20%20%20%3CB%20%2F%3E%20%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%7D%5Cn%20%20%3C%2Fdiv%3E%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

# Unnecessary semicolons？

## Before

```js
let component = (
  <div>
    {do {
      if (true) { 
        <A />
      } else { 
        <B /> 
      }
    }}
  </div>
)
```

## After

```js
let component = (
  <div>
    {
      do {
        if (true) {
          ;<A />
        } else {
          ;<B />
        }
      }
    }
  </div>
)
```

**Comment by azz** [comment]
This can be reduced to:

Input:
```js
<A />
```
Output:
```js
;<A />
```

Prettier will prepend a semicolon in `--no-semi` mode when the line may cause ASI issues, usually with lines starting with `(` or `[`, but there are other cases.

This seems to be done on purpose, listed in https://github.com/prettier/prettier/pull/1129#issuecomment-292243414, but I'm not sure if it is required or not. Need to check the JSX grammar. 

c.c. @rattrayalex

**Comment by lydell** [comment]
This has already been discussed in #1433. Thanks for the issue though!

**Comment by vjeux** [comment]
I'm curious, what's the ambiguity with jsx that adding a semincolon would solve?

**Comment by lydell** [comment]
@vjeux See https://github.com/prettier/prettier/issues/1433#issuecomment-297793119 and the comments after it

**Comment by rattrayalex** [comment]
shameless plug, @ambar if you like everything-as-expression / implicit returns and don't like semicolons, you might try [LightScript](http://lightscript.org). 

But yes, unfortunately it is best for us to put that semicolon there :-( as noted in those threads
