### ISSUE TITLE
Support @prettier pragma comment

### ISSUE THREAD

**Issue by ajhyndman** [prettier/prettier#2397]
I'd like to propose a new option for prettier.

[`eslint-plugin-prettier`](https://www.npmjs.com/package/eslint-plugin-prettier) supports a pragma comment. This comment tells eslint which files to apply prettier formatting rules to. This is a great affordance for incremental adoption in large codebases.

It would be great if prettier, when run over a codebase, could match this behaviour and respect a pragma comment.

Option would look something like:

```
$ prettier --pragma "@prettier" [filename ...]
```

**Comment by azz** [comment]
I like this idea. Not sure that it needs to be configurable, the only use-case I can think of is hijacking `@flow`, but that can be in a single-line comment.

I wonder if there's a use-case for `@noprettier`. Though that could be covered by #2412 (`. prettierignore`)

The other thing that comes to mind is overrides. Would the following make sense?

```js
/** @prettier trailingComma:all */

export default [
  "string a",
  "string b",
];
```

Maybe rename the option to `--require-pragma`?

**Comment by ajhyndman** [comment]
`--require-pragma` would serve my purpose.

**Comment by azz** [comment]
We're currently looking at supporting `.prettierignore` files. Would that suit your purpose?

```
**/*.js
!./pretty/code/**/*.js
```

**Comment by ajhyndman** [comment]
We have a pretty large codebase, and are using the `@prettier` flag to avoid merge conflicts while giving us a migration path.

While `.prettierignore`sounds like a great idea, I'm not sure it would be help avoid merge conflicts in an incremental adoption strategy.

**Comment by wbinnssmith** [comment]
hi folks! I just opened #2772 to implement what was discussed here. Please feel free to provide any feedback on the api or implementation over there 😊
