### ISSUE TITLE
Prettier is unable to reformat the comment within 80 character limit

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2405]
https://prettier.io/playground/#%7B%22content%22%3A%22%5Ct%2F%2F%20Check%20if%20this%20is%20not%20a%20cached%20load%2C%20fallback%20to%20system%20font%20so%20that%20login%20doesn't%20have%20to%20wait%20for%20the%20main%20fonts%20to%20load%20and%20neither%20sees%20a%20flicker%20on%20login%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by lydell** [comment]
Yep, comments are not touched in any way right now. I'm sure there has been previous discussions about this, but I couldn't find any right now.

A problematic thing here is that you can put _anything_ inside comments, such as commented out code and ASCII diagrams, so formatting them is a tricky problem. Not sure if it's possible.

**Comment by azz** [comment]
As @lydell mentioned, this is by design.
