### ISSUE TITLE
Unbalanced comment tag indentation

### ISSUE THREAD

**Issue by KayLeung** [prettier/prettier#2407]
Wrong indentations of Comment tag in the following examples:
(Please read the inline comments in below link)

[BUG Example Code](https://prettier.io/playground/#%7B%22content%22%3A%22%2F%2F%20INCORRECT%5Cn%5Cn%5Cn%5Cn(function%20(%24)%20%7B%5Cn%20%20%24.extend(TableHeader.prototype%2C%20%2F**%20%40lends%20Drupal.TableHeader%23%20*%2F%20%7B%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Testing%201%5Cn%20%20%20%20%20*%5Cn%20%20%20%20%20*%20%40type%20%7Bnumber%7D%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20minHeight%3A%20100%2C%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Testing%202%5Cn%20%20%20%20%20*%5Cn%20%20%20%20%20*%20%40type%20%7Bnumber%7D%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20minHeight2%3A%20100%2C%5Cn%20%20%7D)%3B%5Cn%7D(jQuery))%3B%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2F%2F%20INCORRECT%3A%20Removed%20IIFE%20%26%20Indentation%5Cn%5Cn%5Cn%5Cn%24.extend(TableHeader.prototype%2C%20%2F**%20%40lends%20Drupal.TableHeader%23%20*%2F%20%7B%5Cn%20%20%2F**%5Cn%20%20%20*%20Testing%201%5Cn%20%20%20*%5Cn%20%20%20*%20%40type%20%7Bnumber%7D%5Cn%20%20%20*%2F%5Cn%20%20minHeight%3A%20100%2C%5Cn%20%20%2F**%5Cn%20%20%20*%20Testing%202%5Cn%20%20%20*%5Cn%20%20%20*%20%40type%20%7Bnumber%7D%5Cn%20%20%20*%2F%5Cn%20%20minHeight2%3A%20100%2C%5Cn%7D)%3B%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2F%2F%20CORRECT%3A%20Removed%20IIFE%20%26%20Keep%20Indentation%20(BUT%20this%20is%20formatted%20different%20than%20next%20example)%5Cn%5Cn%5Cn%5Cn%20%20%24.extend(TableHeader.prototype%2C%20%2F**%20%40lends%20Drupal.TableHeader%23%20*%2F%20%7B%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Testing%201%5Cn%20%20%20%20%20*%5Cn%20%20%20%20%20*%20%40type%20%7Bnumber%7D%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20minHeight%3A%20100%2C%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Testing%202%5Cn%20%20%20%20%20*%5Cn%20%20%20%20%20*%20%40type%20%7Bnumber%7D%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20minHeight2%3A%20100%2C%5Cn%20%20%7D)%3B%5Cn%5Cn%5Cn%5Cn%2F%2F%20CORRECT%3A%20break%20the%20%60%7B%60%20to%20new%20line%5Cn%5Cn%5Cn%5Cn(function%20(%24)%20%7B%5Cn%20%20%24.extend(TableHeader.prototype%2C%20%2F**%20%40lends%20Drupal.TableHeader%23%20*%2F%20%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Testing%201%5Cn%20%20%20%20%20*%5Cn%20%20%20%20%20*%20%40type%20%7Bnumber%7D%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20minHeight%3A%20100%2C%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Testing%202%5Cn%20%20%20%20%20*%5Cn%20%20%20%20%20*%20%40type%20%7Bnumber%7D%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20minHeight2%3A%20100%2C%5Cn%20%20%7D)%3B%5Cn%7D(jQuery))%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

[BUG Example Code 2](https://prettier.io/playground/#%7B%22content%22%3A%22(function%20(%24%2C%20Drupal)%20%7B%5Cn%20%20Drupal.tableSelect%20%3D%20function%20()%20%7B%5Cn%20%20%20%20checkboxes%20%3D%20%24table.find('td%20input%5Btype%3D%5C%22checkbox%5C%22%5D%3Aenabled').on('click'%2C%20function%20(e)%20%7B%5Cn%20%20%20%20%20%20%2F**%5Cn%20%20%20%20%20%20%20*%20%40this%20%7BHTMLElement%7D%5Cn%20%20%20%20%20%20%20*%2F%5Cn%20%20%20%20%20%20%24(this).closest('tr').toggleClass('selected'%2C%20this.checked)%3B%5Cn%20%20%20%20%7D)%3B%5Cn%20%20%7D%3B%5Cn%7D(jQuery%2C%20Drupal))%3B%5Cn%5Cn%5Cn(function%20(%24%2C%20Drupal)%20%7B%5Cn%20%20Drupal.tableSelect%20%3D%20function%20()%20%7B%5Cn%20%20%20%20checkboxes%20%3D%20%24table%5Cn%20%20%20%20%20%20.find('td%20input%5Btype%3D%5C%22checkbox%5C%22%5D%3Aenabled')%5Cn%20%20%20%20%20%20.on('click'%2C%20function%20(e)%20%7B%5Cn%20%20%20%20%20%20%2F**%5Cn%20%20%20%20%20%20%20*%20%40this%20%7BHTMLElement%7D%5Cn%20%20%20%20%20%20%20*%2F%5Cn%20%20%20%20%20%20%24(this).closest('tr').toggleClass('selected'%2C%20this.checked)%3B%5Cn%20%20%20%20%7D)%3B%5Cn%20%20%7D%3B%5Cn%7D(jQuery%2C%20Drupal))%3B%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%5Cn%2F%2F%20CORRECT%3A%20Shorten%20selector%20in%20%24.find()%5Cn%5Cn%5Cn(function%20(%24%2C%20Drupal)%20%7B%5Cn%20%20Drupal.tableSelect%20%3D%20function%20()%20%7B%5Cn%20%20%20%20checkboxes%20%3D%20%24table%5Cn%20%20%20%20%20%20.find('td')%5Cn%20%20%20%20%20%20.on('click'%2C%20function%20(e)%20%7B%5Cn%20%20%20%20%20%20%2F**%5Cn%20%20%20%20%20%20%20*%20%40this%20%7BHTMLElement%7D%5Cn%20%20%20%20%20%20%20*%2F%5Cn%20%20%20%20%20%20%24(this).closest('tr').toggleClass('selected'%2C%20this.checked)%3B%5Cn%20%20%20%20%7D)%3B%5Cn%20%20%7D%3B%5Cn%7D(jQuery%2C%20Drupal))%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by azz** [comment]
We're aware of this issue, closing a duplicate of #648.
