### ISSUE TITLE
Return type of arrow func is moved to inside parens with flow comment types

### ISSUE THREAD

**Issue by simonkberg** [prettier/prettier#2409]
Using babylon parser. Flow parser handles the unambiguous examples correctly, and throws a `SyntaxError` on the ambiguous one, but converts comment types to regular types. [playground](https://prettier.io/playground/#%7B%22content%22%3A%22%2F%2F%20%40flow%5Cn%5Cn%2F%2F%20Unambiguous%5Cnconst%20foo%20%3D%20(arg%20%2F*%3A%20any%20*%2F)%20%2F*%3A%20Promise%3Cany%3E%20*%2F%20%3D%3E%20Promise.resolve(arg)%5Cnconst%20foo%20%3D%20(arg)%20%2F*%3A%20Promise%3Cany%3E%20*%2F%20%3D%3E%20Promise.resolve(arg)%5Cn%5Cn%2F%2F%20Ambiguous%5Cnconst%20bar%20%3D%20arg%20%2F*%3A%20Promise%3Cany%3E%20*%2F%20%3D%3E%20Promise.resolve(arg)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

# Input
```jsx
// @flow

// Unambiguous
const foo = (arg /*: any */) /*: Promise<any> */ => Promise.resolve(arg)
const foo = (arg) /*: Promise<any> */ => Promise.resolve(arg)

// Ambiguous
const bar = arg /*: Promise<any> */ => Promise.resolve(arg)
```

# Output
```jsx
// @flow

// Unambiguous
const foo = (arg /*: any */ /*: Promise<any> */) => Promise.resolve(arg);
const foo = (arg /*: Promise<any> */) => Promise.resolve(arg);

// Ambiguous
const bar = (arg /*: Promise<any> */) => Promise.resolve(arg);
```

# Expected
```jsx
// @flow

// Unambiguous
const foo = (arg /*: any */) /*: Promise<any> */ => Promise.resolve(arg)
const foo = (arg) /*: Promise<any> */ => Promise.resolve(arg)

// Ambiguous
const bar = (arg /*: Promise<any> */) => Promise.resolve(arg) // or throw?
```

**Comment by azz** [comment]
Does babylon support flow comment types?

**Comment by simonkberg** [comment]
Oh, doesn't seem like it: http://astexplorer.net/#/gist/13ff8d141bee632cf0535022c0a76105/cf6bb0fce2a412c616d459df6920da967dc57f38

Is there anything prettier could do here? Since the flow parser coverts the comments to regular types, there is currently no safe way to use prettier with the comment syntax.

**Comment by vjeux** [comment]
Yeah, there's another issue tracking it.

I think we should attack it from two angles:
1) Make sure we beef up our comment logic to keep them in places where they don't change meanings
2) When using the flow parser and if there's one type-comment in the file, then output comments instead of types.

Help is wanted for both

**Comment by azz** [comment]
Related issues: #204, #719.

**Comment by simonkberg** [comment]
Closing in favor of #719 since it already covers this particular issue
