### ISSUE TITLE
Can't Integrate Global Prettier installation with WebStorm

### ISSUE THREAD

**Issue by Mohamed3on** [prettier/prettier#2415]
I followed this [guide](https://github.com/prettier/prettier/tree/master/editors/webstorm) on Windows,
The problem is it doesn't specify what **Program** should be set to on Windows, the [original article](https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/) says it should be the global node modules folder with `node_modules\prettier` appended to it.
I did that, but I got the error `CreateProcess error=5, Access is denied`.

**Comment by azz** [comment]
Did you make sure the global `node_modules\.bin` is in your `PATH`? (Usually in `%APPDATA%\roaming\npm` from memory)

**Comment by Mohamed3on** [comment]
@azz Yes, it is. When combined, what I wrote in **Program** was `C:\Users\Mohamed\AppData\Roaming\npm\node_modules\prettier`.

**Comment by azz** [comment]
Perhaps try:

`C:\Users\Mohamed\AppData\Roaming\npm\node_modules\.bin\prettier.cmd`

**Comment by Mohamed3on** [comment]
I tried that too, but it gave me another error: `CreateProcess error=2, The system cannot find the file specified`. Note that when I run prettier in the terminal it's recognized and works with no problems.

**Comment by azz** [comment]
@Mohamed3on did you have any luck?

**Comment by Mohamed3on** [comment]
@azz unfortunately not, I gave up and turned it off for now.

**Comment by azz** [comment]
I don't think I have any more ideas to try out.  😞 

I'm closing this issue as its not an issue with prettier itself. You should raise the issue with WebStorm, I'm sure they'll be able to help better than I can.

**Comment by pulmo** [comment]
@Mohamed3on Hello, I had some issue, and writing in **Program** `C:\Users\user_name\AppData\Roaming\npm\prettier.cmd` (instead `C:\Users\user_name\AppData\Roaming\npm\node_modules\prettier` or `C:\Users\user_name\AppData\Roaming\npm\node_modules\.bin\prettier.cmd` ) is solution.

**Comment by WhiteNoise15** [comment]
@pulmo Thanks. It helped

**Comment by difo23** [comment]
@pulmo Thanks. It helped

**Comment by avalanche1** [comment]
If some1 is having troubs with osx - specify `/usr/local/bin/prettier` as your prettier executable path.
