### ISSUE TITLE
Documented option `--no-bracket-spacing false` does not work

### ISSUE THREAD

**Issue by scharf** [prettier/prettier#2421]
It seems there is no command line option `--no-bracket-spacing`

```
prettier --write  --no-bracket-spacing false /tmp/x.js
false
Unable to read file: false
Error: ENOENT: no such file or directory, open 'false'
```

But there is a option `--bracket-spacing`:

```
 prettier --write --bracket-spacing true /tmp/x.js
/tmp/x.js 49ms
```

**Comment by lydell** [comment]
Where is it documented that it should be `--no-bracket-spacing false`? The correct way is `--no-bracket-spacing`.

In general, boolean options work like this:

```
--foo # Enable foo
--foo true # Enable foo
--foo=true # Enable foo
--foo false # Disable foo
--foo=false # Disable foo
--no-foo # Disable foo
```

All we do in the CLI is to define 'foo' and its default value. `--no-foo` comes for free from the CLI arguments parser we use (minimist).

**Comment by scharf** [comment]
Well, I did not realize that the `CLI OVERRIDE` is different form other documented option (it does not take the same argument as the API).

Carefully reading all the docs, I realized that there are different types of overrides.:

| default | cli override | api override | comment
|--|--|--|:--|
|`"none"` | `--trailing-comma <none,es5,all>` | `trailingComma: "<none,es5,all>"`| same args|
|true | `--no-bracket-spacing` | `bracketSpacing: <bool>`| cli has no args|

I was lazy and "transferred" my understanding form one type of *cli override* to another one. I am not a big fan of those kind of inconsistencies...

==> my fault -- I did not expect that there is a difference between the api override and the cli override (I assumed that the default is always the same for both, which is true in some cases but not true in other cases)
