### ISSUE TITLE
Remove trailing whitespace in comments

### ISSUE THREAD

**Issue by Bulan** [prettier/prettier#2422]
Using prettier with Typescript and it's currently leaving trailing whitespace in JsDoc/Multiline comments

Current:
```
  /**
   * Lorem Ipsum 
   * @param payload 
   */
  onImageDelete(payload: any) {

 /* 
Multiline 
*/

```
Should be:
```
  /**
   * Lorem Ipsum
   * @param payload
   */
  onImageDelete(payload: any) {

 /* 
Multiline
*/
```

Since it's trailing space only and nothing after, it should not affect any diagrams and whatnot that ppl put in their comments

Edit, hard to show a space in this :) But After Lorem Ipsum, payload and Multiline, there's a space that doesn't get removed in current version

**Comment by azz** [comment]
We _could_ do this in prettier but its probably better just to configure your editor to do this for you.

In VSCode:
```json
"files.trimTrailingWhitespace": true
```

In atom (`whitespace` package):
```
  whitespace:
    removeTrailingWhitespace: true
```
