### ISSUE TITLE
Prettier breaking tests run on Node v4.x

### ISSUE THREAD

**Issue by yeskunall** [prettier/prettier#2426]
So I just added `prettier` as a dev dependency to one of my npm modules, just to try it out. Everything works fine, except that the Travis build fails for Node `v4.x`.

In fact, this error was caught by [Hound CI](https://houndci.com/) as well, which is why I think this might be more than just an error on my end. [Here's](https://github.com/yeskunall/fish-names/pull/9) the pull request. Hope this clears things up a bit.

Thanks for looking into this! ❤️

**Comment by vjeux** [comment]
You are using --trailing-comma=all which only works with node 8 or with a babel transform. You need to use --trailing-comma=es5 for environments that don't yet support the latest trailing comma spec.

**Comment by yeskunall** [comment]
Yup, I figured it out minutes after posting this issue. Thanks a lot @vjeux. Much appreciated! ❤️
