### ISSUE TITLE
Properties at end of method chains on same line

### ISSUE THREAD

**Issue by matthewwithanm** [prettier/prettier#2427]
Properties at the end of method chains aren't put on their own line. This makes the type of the expression less obvious. For example:

```js
const result = value
  .aaaaaaaaaa()
  .bbbbbbbbbb()
  .cccccccccc()
  .dddddddddd()
  .eeeeeeeeee()
  .filter(x => {}).length;
```

Skimming this, it's easy to expect result to be of the type returned by `filter()`, but it's actually not.

It's also somewhat awkard if you start chaining methods again:

```js
const result = value
  .aaaaaaaaaa()
  .bbbbbbbbbb()
  .cccccccccc()
  .dddddddddd()
  .eeeeeeeeee()
  .filter(x => {})
  .length.g.h.i.split("1");
```

Ideally (imo) once you start breaking a chain into lines, you would keep breaking it at every dot.

**Comment by azz** [comment]
> Ideally (imo) once you start breaking a chain into lines, you would keep breaking it at every dot.

This is not feasible as people expect this kind of code to remain as-is.

```js
const result = value
  .x.y.z()
  .x.y.z()
```

It _may_ be possible to print the following, but the code handing member chains is already quite complex.

```js
  // ...
  .filter(x => {})
  .length;
```

@vjeux Do you think this is actionable?

**Comment by vjeux** [comment]
Yeah, there's another issue about this.

We only do the special method chaining logic starting at the CallExpression. We should figure out a way to deal with the outer MemberExpression.

I'd be down supporting this use case but haven't looked into it yet.

Also, we do want to keep it inline for .isRequired proptypes, so it's likely not as straightforward as alway breaking.

**Comment by azz** [comment]
Found it. Closing in favour of #875.
