### ISSUE TITLE
Is it possible to format .*rc files with Prettier?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2436]
Like `.stylelintrc` `.eslintrc` etc.

**Comment by azz** [comment]
JSON is support, yes. 

```bash
prettier --write --parser json .eslintrc
```

**Comment by jitendravyas** [comment]
How to use it here? https://github.com/prettier/prettier/issues/2151#issuecomment-308777166

I want to add both `.styleintrc` and .`eslintrc`

**Comment by azz** [comment]
Something like this?

```
 "lint-staged": {
    ".*rc": [
      "prettier --write --parser json",
      "git add"
    ]
  }
```

**Comment by jitendravyas** [comment]
I tried but get this 

![2017-07-11 00-35-04](https://user-images.githubusercontent.com/77309/28035136-1b795c76-65d1-11e7-8b42-9e8d49bd04f3.jpg)

**Comment by azz** [comment]
That looks like a very old version of prettier. You'll need v1.5 for json

**Comment by jitendravyas** [comment]
you are right. I had updated it some days ago but now found that [this is the problem ](https://github.com/npm/npm/issues/17710)

**Comment by jitendravyas** [comment]
Ok the problem was that my global version was not updated. 

I get this now

```
/Users/jitendravyas/app-v3/.stylelintrc: SyntaxError: (json-to-ast) Cannot tokenize symbol <i> at (37:5)
  35 | 		"at-rule-no-unknown": [
  36 | 			true,
> 37 | 			{ignoreAtRules: ['include', 'extend', mixin, if, content, else, each
     | 			 ^
  38 | 				],
  39 | 			}
  40 | 		],
```

**Comment by CiGit** [comment]
You should write **strict** JSON. The error you have is missing quotes `"`.
`ignoreAtRules` -> `"ignoreAtRules"`
You should also replace single-quotes in the array and quote strings.
And remove trailing commas.

If you have, remove javascript comments.
