### ISSUE TITLE
Destructuring without const/let breaks prettier

### ISSUE THREAD

**Issue by lifeiscontent** [prettier/prettier#2438]
not sure if this is in core, or the atom plugin https://github.com/prettier/prettier-atom/issues/232

**Comment by CiGit** [comment]
In core:
 - [flow parser](https://prettier.io/playground/#%7B%22content%22%3A%22(%7Bx%3D1%7D%3D%7B%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)
`({x=1}={})` -> Unexpected token first `=`
 - [typescript parser](https://prettier.io/playground/#%7B%22content%22%3A%22(%7Bx%3D1%7D%3D%7B%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)
`({x=1}={})` -> `({ x } = {});` missing default value.
- As expected with [babylon](https://prettier.io/playground/#%7B%22content%22%3A%22(%7Bx%3D1%7D%3D%7B%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).
`({x=1}={})` -> `({ x = 1 } = {});`

**Comment by azz** [comment]
Here's the bug for typescript: https://github.com/eslint/typescript-eslint-parser/issues/332

**Comment by azz** [comment]
And here's the bug for flow: https://github.com/facebook/flow/issues/183

**Comment by azz** [comment]
Going to close this as we've already got this issue open: #2229.
