### ISSUE TITLE
Ternaries break on assignment operator instead of "?" operator

### ISSUE THREAD

**Issue by hawkrives** [prettier/prettier#2440]
[prettier.io reproduction](https://prettier.io/#%7B%22content%22%3A%22const%20endFormat%20%3D%20endTimeFormatted%20%3D%3D%3D%20midnightTime%5Cn%20%20%20%20%20%20%3F%20'MMM.%20D'%5Cn%20%20%20%20%20%20%3A%20'MMM.%20D%20h%3Amm%20A'%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

In Prettier 1.4, my ternaries would break on the `?`, leading to code like the following:

```js
// 1.4.4
const endFormat = endTimeFormatted === midnightTime
  ? "MMM. D"
  : "MMM. D h:mm A";
```

I liked that 😄 

In 1.5, though, and on `master`, ternaries seem to split on the `=`, instead:

```js
// 1.5.2
const endFormat =
  endTimeFormatted === midnightTime ? "MMM. D" : "MMM. D h:mm A";
```

I don't remember seeing any discussion around changing the ternary format, and a cursory search of the issues didn't turn anything up.

Is this an intentional change?

---

A `git bisect` between the 1.4.4 tag and the 1.5.0 tag says that the offending commit was 39954f79510eab7b45a80f79710ccb5d0190eb60, which was the merge commit for #2228, which was a fix for https://github.com/prettier/prettier/issues/2122.

Looking at that issue, this looks like an accidental change.

I'd offer to help, but I don't know my way around the prettier codebase 😸 

Thanks for the awesome tool!

**Comment by azz** [comment]
I actually noticed this here:

https://github.com/prettier/prettier/pull/2431/files#diff-dfe37da45692c74369de6fcb0546f58b

But wasn't sure if it was intentional.

**Comment by vjeux** [comment]
This is actually intentional, even though not ideal.

What we would really like is to try the following:

```js
const endFormat = endTimeFormatted === midnightTime ? "MMM. D" : "MMM. D h:mm A";

const endFormat = endTimeFormatted === midnightTime
  ? "MMM. D"
  : "MMM. D h:mm A";

const endFormat =
  endTimeFormatted === midnightTime
    ? "MMM. D"
    : "MMM. D h:mm A";
```

But we can't express this with the underlying algorithm. So we break after `=` more often than we could. I don't really know what's the solution for it unfortunately. The solution we have in 1.5 is the one that never produces bad edge cases even though normal code look less optimal. It doesn't look too bad so I figured that it was an okay trade-off.

**Comment by hawkrives** [comment]
Alright, thanks. I'll probably wind up just pulling out part of the expression into a variable.

Thanks again!
