### ISSUE TITLE
Ignored unknown option `--no-semi`

### ISSUE THREAD

**Issue by levithomason** [prettier/prettier#2448]
On the latest master `--no-semi` produces `Ignored unknown option: --no-semi`.  Note that `--semi false` does not.

The latest `README.md` notes to use `--no-semi`.  Not sure if this is a doc issue or if the CLI should handle `--no-*` arg prefixes when checking `booleanOptionNames`.

**Comment by azz** [comment]
Yes, this is indeed a minor regression. Thanks for the catch.

The warning doesn't actually mean the flat is ignored, it still should work.
