### ISSUE TITLE
Wrong formatting for class method and function

### ISSUE THREAD

**Issue by Alphapage** [prettier/prettier#2457]
(edited by @josephfrazier to wrap code in a code block)

Hello,

I get the wrong formatting for a class method like the following:

```js
class cl {
    
    test(arg//an arg
    ,arg2//arg2
    ,arg3//arg3
    )//comment 
    {
        console.log(arg)
    }
} 
``` 
It works for classic function.

This is related to a dependent project: https://github.com/esbenp/prettier-vscode/issues/162 and can be reproduced:
[playground](https://prettier.io/playground/#%7B%22content%22%3A%22class%20cl%20%7B%5Cn%20%20%20%20%5Cn%20%20%20%20test(arg%2F%2Fan%20arg%5Cn%20%20%20%20%2Carg2%2F%2Farg2%5Cn%20%20%20%20%2Carg3%2F%2Farg3%5Cn%20%20%20%20)%7B%5Cn%20%20%20%20%20%20%20%20console.log(arg)%5Cn%20%20%20%20%7D%5Cn%7D%20%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Thank you in advance for your help.

**Comment by Alphapage** [comment]
I think this could be related to this issue I reported: https://github.com/babel/babylon/issues/653

**Comment by duailibe** [comment]
Same as #2816
