### ISSUE TITLE
indentation of chained JS calls

### ISSUE THREAD

**Issue by bardware** [prettier/prettier#2459]
I have this jQuery AJAX call.

```
			$.post(
				'my.cfc?method=function&_cf_nodebug=true',
				struFormFields
			).done( function( data ) {
				console.dir( data );
			} ).fail( function() {
				//
			} );
``` 

I call `node_modules\.bin\prettier --write --single-quote --use-tabs js.js` and get the following output:

```
$.post('my.cfc?method=function&_cf_nodebug=true', struFormFields)
	.done(function(data) {
		console.dir(data);
	})
	.fail(function() {
		//
	});
```

I wonder why `done` and `fail` are indented. Can you tell about it? Why was the decision made to indent like this?

**Comment by lydell** [comment]
It's a common JavaScript style.

**Comment by lydell** [comment]
This has already been discussed in #2164, so I'm closing this one.
