### ISSUE TITLE
sort imports & object keys alphabetically

### ISSUE THREAD

**Issue by tomdavidson** [prettier/prettier#2460]
Is sorting imports and object keys alphabetically with in prettier's scope?

**Comment by josephfrazier** [comment]
No, prettier tries not to change the semantics (specifically, the AST) of the program, and sorting imports/keys could break that guarantee. See here for more details and context, as well as links to similar/duplicate issues: https://github.com/prettier/prettier/issues/1684#issuecomment-303547552
