### ISSUE TITLE
Inconsistency in object quotes

### ISSUE THREAD

**Issue by sanfilippopablo** [prettier/prettier#2461]
First, awesome project. Thank you all for the work on this.

The current behavior of prettier removes quotes in object keys when they're not necessary, and it converts this:
```es6
{
  "City": "A city",
  "Street Name": "A street"
}
```
to this:
```es6
{
  City: "A city",
  "Street Name": "A street"
}
```
I like my object keys without quotes, but when one key needs quotes, I think all the keys should have quotes regardless if they need them or not. The inconsistency makes the code weird and hard to read, even more when code editors highlight with different colors quoted and unquoted keys.

**Comment by azz** [comment]
Thanks for the report!

There's some discussion on this in #838.

@vjeux Is this something we want to change?

**Comment by vjeux** [comment]
I think at this point we're going to keep it as is.
