### ISSUE TITLE
TypeScript: comment + Index Signatures is unnatural format 

### ISSUE THREAD

**Issue by azu** [prettier/prettier#2462]
Original Issue: https://github.com/almin/almin/pull/227#discussion_r126717556

**Env**:

- Prettier: 1.5.2

**Input**:

Reproduce: [Prettier Playground URL](https://prettier.io/playground/#%7B%22content%22%3A%22export%20type%20StoreMap%3CT%3E%20%3D%20%7B%5Cn%20%20%20%20%2F%2F%20T%5BP%5D%20as%20Store%3CState%3E%5Cn%20%20%20%20%2F%2F%20Now%2C%20State%20is%20T%5BP%5D%5Cn%20%20%20%20%5BP%20in%20keyof%20T%5D%3A%20Store%3CT%5BP%5D%3E%20%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D "Prettier")

```ts
export type StoreMap<T> = {
    // T[P] as Store<State>
    // Now, State is T[P]
    [P in keyof T]: Store<T[P]> 
};
```

**Actual Output**:

```ts
export type StoreMap<T> = {
    [// T[P] as Store<State>
    // Now, State is T[P]
    P in keyof T]: Store<T[P]>
};
```

**Expected Output**:

```ts
export type StoreMap<T> = {
    // T[P] as Store<State>
    // Now, State is T[P]
    [P in keyof T]: Store<T[P]> 
};
```

**Comment by thorn0** [comment]
This seems to have been fixed.

**Comment by j-f1** [comment]
Awesome 🎉
