### ISSUE TITLE
Typescript: Weird indentation of promise chain in return

### ISSUE THREAD

**Issue by CameronDiver** [prettier/prettier#2464]
Prettier seems to behave weirdly when indenting promise chains which also are part of a return. This is an example (logic removed for brevity):

Actual output:

```typescript
resolver
	.resolve(bundle)
	.then(additionalItems => {
		return Promise.map(additionalItems, (file: FileInfo) => {
			....
		})
			.then(() => {  /* Weird .then indentation here */
				return Promise.try(() => {
					...
				});
			})
			.then(() => {
				...
			})
		});
```

Expected output:
```typescript
resolver
	.resolve(bundle)
	.then(additionalItems => {
		return Promise.map(additionalItems, (file: FileInfo) => {
			....
		})
		.then(() => {  /* This should be at the same level, right? */
			return Promise.try(() => {
				...
			});
		})
		.then(() => {
			...
		})
	});
```

It seems that this is completely arbitrary. If it in fact turns out to be a decision made to format in this way, would it be possible to get a configuration setting which would alter this behaviour?

**Comment by lydell** [comment]
Prettier consistently indents one level in method chains. (You seem to do it in the top level, but not inside the promise callbacks). Merging this one into #2459.

**Comment by CameronDiver** [comment]
@lydell that top level indenting was also performed by prettier. The issue that you linked to links to another issue which is now closed. Does this mean that this behaviour is expected and therefore won't be changed?

**Comment by lydell** [comment]
Sorry, I should have linked to #2164 directly.
