### ISSUE TITLE
add stylus support

### ISSUE THREAD

**Issue by yukulele** [prettier/prettier#2465]
add stylus support http://stylus-lang.com/

**Comment by vjeux** [comment]
We may support it in the future if someone is interested in building and maintaining support for it. But it's not something that we have on the roadmap for now, so I'm going to close this.

**Comment by phun-ky** [comment]
Just out of curiosity, how can this be added?

**Comment by evilebottnawi** [comment]
@phun-ky PR welcome :+1:

**Comment by alxtz** [comment]
Just for anyone who would be interested to work in a PR, there seems to be an existing parsing lib for stylus https://github.com/sveisvei/pretty-styl , but still need to dig out the AST related code to support prettier
