### ISSUE TITLE
Smart quote in multi-line comment causes code to start on last comment line.

### ISSUE THREAD

**Issue by alloy** [prettier/prettier#2466]
Given the following code:

```js
/**
 * That’s
 */
const foo = () => {
}
```

Prettier formats it to the following incorrect code:

```js
/**
 * That’s
 */ const foo = () => {}
```

The issue is caused by the smart quote used in `That’s`. With a regular single-quote prettier works as intended.

**Comment by azz** [comment]
I [can't reproduce](https://prettier.io/playground/#%7B%22content%22%3A%22%2F**%5Cn%20*%20That%E2%80%99s%5Cn%20*%2F%5Cnconst%20foo%20%3D%20()%20%3D%3E%20%7B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) this issue with the `babylon`, `flow`, or `typescript` parsers.

Are you sure this isn't another tool doing that formatting? (perhaps prettier-eslint?)

**Comment by alloy** [comment]
Good catch!

I thought I had properly upgraded prettier to the latest before posting this ticket, but it appears that prettier-vscode loads and keeps using the prettier version you had installed _at the time of launching vscode_. After relaunching vscode it works as intended, so this was just an old bug.

Sorry for the hassle 😑
