### ISSUE TITLE
prettier-ignore doesn't work inside jsx

### ISSUE THREAD

**Issue by eenagy** [prettier/prettier#2467]
Using prettier-ignore is not supported inside jsx.
We have some compile issues (third-party compile issues), when prettier reformats some elements.

Example
```js
<div>
  {/* prettier-ignore */}
  <style jsx global>{ComponentStyles}</style>
</div>
```

outputs
```js
<div>
  {/* prettier-ignore */}
  <style jsx global>
    {ComponentStyles}
  </style>
</div>
```

**Comment by lydell** [comment]
In your code example you have written prettier-<strong>disable</strong>, not prettier-<strong>ignore</strong>. Does it work if you change "disable" to "ignore"?

**Comment by karl** [comment]
@eenagy Although it doesn't relate directly to this bug report I'd be really interested in knowing what the 3rd party tools are, and what changes to JSX are breaking them!

**Comment by vjeux** [comment]
This would indeed be great for JSX to support prettier-ignore comment that way. If someone is interested in building support for it, that shouldn't be too hard.
