### ISSUE TITLE
Flow intersection types are off

### ISSUE THREAD

**Issue by brenmcnamara** [prettier/prettier#2469]
Thanks to the engineers who built prettier, it has definitely helped me save a ton of time writing code and worrying about styling nits in other people's code.

I had one piece of feedback. When styling flow intersection types, the formatting seems a bit off.
I provided pictures of how prettier formats the code and two alternatives that I think would be better.

Here's an example of how prettier formats my flow intersection types:
```js
export type Filter$EnumKey<TFilter: string> = FilterFragment<TFilter, 'KEY'> &
  Op<OpType$Key> &
  Value$Enums;

export type Filter$EntityKeyList<TFilter: string> = FilterFragment<
  TFilter,
  'KEY_LIST'
> &
  Op<OpType$KeyList> &
  Value$Entities;

export type Filter$EnumKeyList<TFilter: string> = FilterFragment<
  TFilter,
  OpType$KeyList
> &
  Op<OpType$KeyList> &
  Value$Enums;
```

Here are a couple of alternatives I think would be better:

```js
export type Filter$EnumKey<TFilter: string> =
  FilterFragment<TFilter, 'KEY'> & Op<OpType$Key> & Value$Enums;

export type Filter$EntityKeyList<TFilter: string> =
  FilterFragment<TFilter, 'KEY_LIST'> & Op<OpType$KeyList> & Value$Entities;

export type Filter$EnumKeyList<TFilter: string> =
  FilterFragment<TFilter, OpType$KeyList> & Op<OpType$KeyList> & Value$Enums;
```

```js
export type Filter$EnumKey<TFilter: string> = (
  FilterFragment<TFilter, 'KEY'> &
  Op<OpType$Key> &
  Value$Enums
);

export type Filter$EntityKeyList<TFilter: string> = (
  FilterFragment<TFilter, 'KEY_LIST'> &
  Op<OpType$KeyList> &
  Value$Entities
);

export type Filter$EnumKeyList<TFilter: string> = (
  FilterFragment<TFilter, OpType$KeyList> &
  Op<OpType$KeyList> &
  Value$Enums
);
```

I know that code formatting is a touchy subject, and I wouldn't post about it unless I felt that I had a styling alternative that was clearly more legible.

**Comment by vjeux** [comment]
We have some special cases in place for intersection but haven't done a good job at this one. It should be printed:

```js
export type Filter$EnumKey<TFilter: string> =
  FilterFragment<TFilter, 'KEY'> &
  Op<OpType$Key> &
  Value$Enums;
```

If someone wants to take a pass at it, that would be great.

**Comment by brenmcnamara** [comment]
I'd actually like to tackle this. I'm new to the prettier code so it may take a while.

**Comment by azz** [comment]
If you do take a look could you add #2485 as a test case, too?

**Comment by vjeux** [comment]
@azz: the two are unrelated. This one is an issue with intersection type, the other one is an issue with `=`

**Comment by azz** [comment]
Isn't it a more general problem of breaking on other things instead of `=`? i.e. #2482

**Comment by vjeux** [comment]
I don't know how to solve the general problem for `=`, so unlikely going to be a good first task. But we can special case intersections to break in a better way with `=`.

**Comment by brenmcnamara** [comment]
I found some test flow types [here](https://github.com/prettier/prettier/blob/master/tests/intersection/intersection.js) that are following what appears to be a different formatting rule on intersection types. @vjeux Is this formatted incorrectly or is this somehow a different edge case on styling.

**Comment by thorn0** [comment]
Closing in favor of #3986
