### ISSUE TITLE
Add support for smart quotes

### ISSUE THREAD

**Issue by callmeaponte** [prettier/prettier#2475]
As I've recently [learned](http://practicaltypography.com/straight-and-curly-quotes.html), using single quotes is typographically invalid, and the react eslint plugin [will throw an error](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md) if they are being used inside of text.

Would it be possible to add an option for converting straight quotes to smart quotes inside of text?

**Single Quotes**
Input: `<div>I'm.</div>`
Output: `<div>I’m</div>`

**Double Quotes**
Input: `<div>"Hello"</div>`
Output: `<div>“Hello”</div>`

**Comment by josephfrazier** [comment]
Prettier generally avoids making changes that alter the AST of the program, like this one would do. See here for more context: https://github.com/prettier/prettier/issues/1684#issuecomment-303547552

Maybe it would be better to add/use an autofixer for that eslint-plugin-react rule?

**Comment by callmeaponte** [comment]
Alright I'll try to find something else to handle this. If not, I'll keep checking back to see if you guys decide to make an exception to the rule.

I mean technically speaking, smart quotes would make your code “prettier“ 🙂
