### ISSUE TITLE
Print width ignored for JSX elements with multiple attributes

### ISSUE THREAD

**Issue by adamroyle** [prettier/prettier#2477]
It appears as though JSX elements will always have it's children moved to a new line if it has more than 2 attributes. eg.

```jsx
<button type="submit">Submit</button>

<button type="submit" className="button-primary">
  Submit
</button>
```

I think print width should be respected in this case. eg.

```jsx
<button type="submit">Submit</button>

<button type="submit" className="button-primary">Submit</button>
```

This worked as expected in v4

**Comment by adamroyle** [comment]
From source code I can tell this was an intentional change, however I question its relevance across actual codebases. I disabled these two conditions below and ran it over a few codebases of ours. It results in more concise components. 

```diff
   let forcedBreak =
     willBreak(openingLines) ||
-    containsTag ||
-    containsMultipleAttributes ||
     containsMultipleExpressions;
```

I had a look at the snapshots and compared them with this change applied. Most of the failing snapshots are rather contrived tests that don't reflect actual codebases. eg

```diff
-      <div>
-        <div>
-          <div>
-            <div>
-              <div>hey hiya how are ya</div>
-            </div>
-          </div>
-        </div>
-      </div>
+      <div><div><div><div><div>hey hiya how are ya</div></div></div></div></div>
```

The only "real-world" example I could find in the snapshots that would be affected by this change is:

```diff
-<Something>
-  {() => (
-    <SomethingElse>
-      <span />
-    </SomethingElse>
-  )}
-</Something>;
+<Something>{() => <SomethingElse><span /></SomethingElse>}</Something>;
 
 <Something>
-  {items.map(item => (
-    <SomethingElse>
-      <span />
-    </SomethingElse>
-  ))}
+  {items.map(item => <SomethingElse><span /></SomethingElse>)}
 </Something>;
 
 <Something>
   {function() {
-    return (
-      <SomethingElse>
-        <span />
-      </SomethingElse>
-    );
+    return <SomethingElse><span /></SomethingElse>;
   }}
 </Something>;
```

In this case I would still prefer the conciseness.

**Comment by hawkrives** [comment]
What does current `master` produce? I know there were some JSX formatting PRs produced recently that I think affect this situation.

**Comment by azz** [comment]
cc. @karl

**Comment by adamroyle** [comment]
@hawkrives The above examples are from current master.

**Comment by azz** [comment]
Related: #2208,  #2398, #1831.

**Comment by adamroyle** [comment]
So there's really two separate issues that I'm raising here.

1. Breaking if contains a tag
2. Breaking if has more than one attribute

#2208 is more about parenthesis which I'm not debating.

I can understand breaking if has child tags because in this makes for easier refactoring (at the cost of conciseness)

However I don't understand the reason for breaking if more than one attribute.

**Comment by karl** [comment]
@adamroyle I made the changes that introduced the new behaviour where containing multiple attributes or a tag causes the JSX element to output across multiple lines.

The main rational was to make it easier to scan JSX. I noticed that in our codebase at Geckoboard we tended to make elements with multiple attributes multiline to make it clearer what the child text was.

Very happy to use this issue to discuss this behaviour, and any changes we might want to make. I'm going to close the issue now, and if we have a concrete proposal for a change we want to make I'll reopen it.

**Comment by adamroyle** [comment]
Thanks for your response @karl 

This feels like a arbitrary heuristic that may just be specific to Geckoboard. Would be great to get others' feedback on this.

**Comment by gpoitch** [comment]
I found that multiple attributes was an odd reason to enforce multiline children.
Here's an [example](https://prettier.io/playground/#%7B%22content%22%3A%22function%20nav()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%5Ct%20%20%3Ca%20href%3D%5C%22%2Fhome%5C%22%3Ehome%3C%2Fa%3E%5Cn%20%20%20%20%20%20%3Ca%20href%3D%5C%22%2Fabout%5C%22%20class%3D%5C%22active%5C%22%3Eabout%3C%2Fa%3E%5Cn%20%20%20%20%20%20%3Ca%20href%3D%5C%22%2Fcontact%5C%22%3Econtact%3C%2Fa%3E%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) of the current behavior (1.6.0):
in:
```jsx
    <div>
      <a href="/home">home</a>
      <a href="/about" class="active">about</a>
      <a href="/contact">contact</a>
    </div>
```
out:
```jsx
    <div>
      <a href="/home">home</a>
      <a href="/about" class="active">
        about
      </a>
      <a href="/contact">contact</a>
    </div>
```

I would say to either respect the print width, or alternatively multiline all those children so it looks consistent.
