### ISSUE TITLE
Backspace is omitted from strings in JSX element props

### ISSUE THREAD

**Issue by jozan** [prettier/prettier#2478]
A `\` is omitted from strings in JSX element props. Doesn't affect when a using template strings. `\n` works as expected.

```jsx
<list>
  <Component text={'\U2019\n'} />
  <Component text={"\U2019\n"} />
  <Component text={`\U2019\n`} />
</list>
```

Converts to
```jsx
;<list>
  <Component text={"U2019\n"} />
  <Component text={"U2019\n"} />
  <Component text={`\U2019\n`} />
</list>
```

[Playground](https://prettier.io/playground/#%7B%22content%22%3A%22%3Clist%3E%5Cn%20%20%3CComponent%20text%3D%7B'%5C%5CU2019%5C%5Cn'%7D%20%2F%3E%5Cn%20%20%3CComponent%20text%3D%7B%5C%22%5C%5CU2019%5C%5Cn%5C%22%7D%20%2F%3E%5Cn%20%20%3CComponent%20text%3D%7B%60%5C%5CU2019%5C%5Cn%60%7D%20%2F%3E%5Cn%3C%2Flist%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
`\U2019` is not a valid unicode sequence. It needs to be a lowercase u to be one. So prettier just removes the extra useless `\`.

![image](https://user-images.githubusercontent.com/197597/28212558-4b3baf30-68a2-11e7-9da2-3e67142345f4.png)
