### ISSUE TITLE
Misleading formatting of trailing space after conditional expression

### ISSUE THREAD

**Issue by stas-vilchik** [prettier/prettier#2479]
I've just upgraded to prettier **1.5.2** and noticed a small issue. The following code
```javascript
<div>
  {foo
    ? bar
    : <Baz>
        {qux}
      </Baz>}
  {' '}
  <span>Failed</span>
</div>
```
gets reformatted to
```javascript
<div>
  {foo
    ? bar
    : <Baz>
        {qux}
      </Baz>}{" "}
  <span>Failed</span>
</div>
```

The space between the conditional expression and the `<span />` changed its place. With this formatting it's hard to understand that the space is not a part of the condition, and will be always printed.

**Comment by adamroyle** [comment]
Current master will format it like this:

```jsx
<div>
  {foo ? bar : <Baz>{qux}</Baz>} <span>Failed</span>
</div>
```

or this

```jsx
<div>
  {longfooooooooooooooooooooooooooooooooooooooooooooooooo ? (
    bar
  ) : (
    <Baz>{qux}</Baz>
  )}{' '}
  <span>Failed</span>
</div>
```

**Comment by vjeux** [comment]
The new behavior looks better. I'm closing this issue.

**Comment by azz** [comment]
Note that in an upcoming release, this will look more like:

```jsx
<div>
  {foo ? (
    bar
  ) : (
    <Baz>{qux}</Baz>
  )}{" "}
  <span>Failed</span>
</div>
```
