### ISSUE TITLE
line break after "use strict" removed

### ISSUE THREAD

**Issue by andreynering** [prettier/prettier#2480]
Is this intentional? This line break is always removed.

```js
(function() {
  "use strict";

  console.log("My code...");
})();
```

Becames:

```js
(function() {
  "use strict";
  console.log("My code...");
})();
```

I think that line should be actually added (or at least kept as is).

**Comment by vjeux** [comment]
You must be using an old version of prettier. The empty line is now preserved there.

https://prettier.io/playground/#%7B%22content%22%3A%22(function()%20%7B%5Cn%20%20%5C%22use%20strict%5C%22%3B%5Cn%5Cn%20%20console.log(%5C%22My%20code...%5C%22)%3B%5Cn%7D)()%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D
