### ISSUE TITLE
Odd linebreak when splitting chained arrows

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#2481]
```js
const foo = (aVeryLongName = 0xffffffffffff) =>
  (aVeryLongName = 0xffffffffffff) => 0;
```
[formats as](https://prettier.io/playground/#%7B%22content%22%3A%22const%20foo%20%3D%20(aVeryLongName%20%3D%200xffffffffffff)%20%3D%3E%5Cn%20%20(aVeryLongName%20%3D%200xffffffffffff)%20%3D%3E%200%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)
```js
const foo = (aVeryLongName = 0xffffffffffff) => (
  aVeryLongName = 0xffffffffffff
) => 0;
```

which seems... bad. I'd definitely prefer to break at the arrow, rather than inside the parameters.

Not sure if this is worth changing but I thought I'd throw it out there.

**Comment by azz** [comment]
Similar kind of thing here: https://github.com/elastic/kibana/pull/12667/files#diff-eeffa987338fd543b38ae2bd04dce36dR111

**Comment by vjeux** [comment]
The root cause is the support for inlining arrow functions:

```js
a => b => c =>
  content
```

but if `a => b => c =>` doesn't fit in one line it looks weird. If you manage to make it break correctly if it doesn't fit, that would be better.

**Comment by bakkot** [comment]
Ah, I think this is a duplicate of #1389.

**Comment by azz** [comment]
Yeah, looks like it is.
