### ISSUE TITLE
Surprising line-breaks in ternary, based on presence of spaces

### ISSUE THREAD

**Issue by stewartulm** [prettier/prettier#2491]
The number of lines a ternary statement uses seems to be dictated by whether the conditional contains any spaces in it. This leads to some inconsistent results, that use more lines than necessary to express the same thing:

    // if the ternary condition is unbroken by spaces, the result is three lines
    const threeLines = !myConditional
      ? someValueReallyLongValueHere
      : someOtherReallyLongValueHere;

    // if the ternary condition contains any spaces, the result is four lines
    const fourLines = 
      myConditional === false
        ? someValueReallyLongValueHere
        : someOtherReallyLongValueHere;

**Comment by azz** [comment]
We're aware of this class of issues, but we haven't got any short-term strategy for solving it. See https://github.com/prettier/prettier/issues/2440#issuecomment-315377084 for more info.
