### ISSUE TITLE
Prettier ignores config, doesn't know --config, --find-config-path options

### ISSUE THREAD

**Issue by jleclanche** [prettier/prettier#2492]
I'm a little confused. I ran `yarn add --dev prettier` on a project (https://github.com/HearthSim/Sunwell), but `yarn run prettier` doesn't seem to pick up on the config whether I put it in .prettierrc or package.json, it only picks up on it if I give it on the command line.

Additionally, it doesn't seem to understand --config or --find-config-path (which are specified in the readme).

```
% yarn run prettier -- --version                                                                                                                       ~ master:f848c71 - Sunwell 
yarn run v0.27.5
$ "/home/adys/src/HearthSim/Sunwell/node_modules/.bin/prettier" "--version"
1.5.3
Done in 0.30s.

% yarn run prettier -- --find-config-path src/Sunwell.ts                                                                                               ~ master:f848c71 - Sunwell 
yarn run v0.27.5
$ "/home/adys/src/HearthSim/Sunwell/node_modules/.bin/prettier" "--find-config-path" "src/Sunwell.ts"
Ignored unknown option: --find-config-path
(...)
```

Am I doing something wrong?

**Comment by jleclanche** [comment]
Alright so apparently the version with --config wasn't released, that was unclear and got me confused :)

**Comment by azz** [comment]
That's right. The readme reflects the state of master, not what's been released to npm.

**Comment by jussi-kalliokoski** [comment]
Is there any issue / milestone tracking the 1.6 release? A quick search didn't produce any results.

**Comment by vjeux** [comment]
The repo is in a good state for 1.6. I just want to get back to work in order to thoroughly test it before shipping it to everyone. Expect it in the next couple of weeks.

**Comment by goldo** [comment]
@vjeux any planned date on this 1.6 release ? We'd love to have a shared config file.
Thx

**Comment by azz** [comment]
@goldo see #2589

**Comment by goldo** [comment]
@azz thx

**Comment by Kikketer** [comment]
So I'm confused.  Is this supposed to be in version 1.6 or in a later unreleased version?

**Comment by hawkrives** [comment]
@Kikketer This is in v1.6
