### ISSUE TITLE
Parser for JSON5

### ISSUE THREAD

**Issue by JosefJezek** [prettier/prettier#2505]
Could you add parser for JSON5?

https://github.com/json5/json5

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/pull/2476 is a similar idea.

**Comment by azz** [comment]
#2476 will get us most (or all?) of the way with parsing, but we'd still to either add a flag to say not to quote object properties, or use `parser: json5` which delegates to `json`.

Or just always quote the object keys...

**Comment by vjeux** [comment]
@azz: I think that prettier should output json syntax (no trailing commas, quote as keys...) but maintain whatever non standard json things you write: comments, Infinity, hexadecimal numbers...

I'm not really a fan of adding yet another mode for prettier. The great thing is that if you are using prettier, it's not annoying to type. You can just type it without double quotes as keys and prettier will add them.

**Comment by azz** [comment]
Agreed. The only one that could be contentious with json5 is if we don't respect `--trailing-comma all`, but given the low usage of json5 it's probably not worth adding core complexity.

**Comment by levithomason** [comment]
>given the low usage of json5 it's probably not worth adding more complexity

^ worth echoing

**Comment by vjeux** [comment]
Closing this as #2476 will allow people using json5 to be in a relatively good shape.
