### ISSUE TITLE
Comment between decorator and class formats oddly

### ISSUE THREAD

**Issue by karptonite** [prettier/prettier#2507]
[See here](https://prettier.io/playground/#%7B%22content%22%3A%22%40Foo()%5Cn%2F%2F%20FOO%5Cnexport%20class%20Bar%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

```typescript
@Foo()
// FOO
export class Bar{}
```

formats to:
```typescript
@Foo()
export // FOO
class Bar {}
```

It works, but I think the expected output should be:
```typescript
@Foo()
// FOO
export class Bar {}
```

Awesome project--Thanks so much for the hard work!

**Comment by lydell** [comment]
Just out of curiosity, why do you add a comment there? To me it seems like a bit odd location; I would have put it _above_ the decorator.

**Comment by karptonite** [comment]
For a very large decorator, it doesn't make as much sense to put it above, if you want to say something about the `Bar` class rather than the `Foo` decorator.

**Comment by aboyton** [comment]
Have big decorators is a common pattern in angular components, say in the example component from the angular.io website. https://angular.io/tutorial/toh-pt1#the-road-youve-travelled

**Comment by karptonite** [comment]
Just to be clear, this is for Typescript, although it may affect other languages as well.
