### ISSUE TITLE
inconsistent formatting on chained calls

### ISSUE THREAD

**Issue by karptonite** [prettier/prettier#2508]
Converting to prettier for the first time, and I found a couple places in my code where running prettier made a change, then running it again made an additional change. Here is an example.

This is the original code. Note that it was originally formatted with tabs:
```typescript
	@Effect()
	delete$: Observable<Action> = this.actions$
		.ofType( pins.DELETE )
		.map( toPayload )
		.switchMap( payload => this.tagsService.deletePin( payload.pinid )
			.map( (successPayload: any)  => new pins.DeleteSuccessAction( { parent: payload.parent, pinid: payload.pinid } )) );
}
```

This is the same code after the first run through prettier
```typescript
  @Effect()
  delete$: Observable<Action> = this.actions$
    .ofType(pins.DELETE)
    .map(toPayload)
    .switchMap(payload =>
      this.tagsService
        .deletePin(payload.pinid)
        .map(
          (successPayload: any) =>
            new pins.DeleteSuccessAction({
              parent: payload.parent,
              pinid: payload.pinid,
            }),
        ),
    );
}
```

And this is the same code after the second run through prettier
```typescript
  @Effect()
  delete$: Observable<Action> = this.actions$
    .ofType(pins.DELETE)
    .map(toPayload)
    .switchMap(payload =>
      this.tagsService.deletePin(payload.pinid).map(
        (successPayload: any) =>
          new pins.DeleteSuccessAction({
            parent: payload.parent,
            pinid: payload.pinid,
          }),
      ),
    );
```

There were a couple other examples, but all of them similarly involved a first reformatting that put chained calls on separate lines, and a second that moved them to the same  line.

**Comment by karptonite** [comment]
Just wanted to make clear that I observed this bug with Typescript, although it may affect other languages as well.

**Comment by azz** [comment]
Merging this with #2803
