### ISSUE TITLE
Inconsistent new lines on function arguments

### ISSUE THREAD

**Issue by ssylvia** [prettier/prettier#2511]
I'm using prettier with ESLint plugin and have the following rules in my eslint file:

```js
'prettier/prettier': ['error', {
  printWidth: 100,
  singleQuote: true,
  trailingComma: 'es5'
}],
```

It looks like both this:

```js
const settings = merge(
    {},
    {
      array: ['Lorem ipsum dolor sit amet.'],
    },
    options
);
```

and this:

```js
const settings = merge({}, { array: ['Lorem ipsum dolor sit amet.'] }, options);
```

are valid even if the second goes over the max-line length.

Is there a way to force consistent line breaks? Or have it always break when the second example overflows the max-line length?

**Comment by vjeux** [comment]
`const settings = merge({}, { array: ['Lorem ipsum dolor sit amet.'] }, options);` is exactly 100 columns, so it stays there.

**Comment by ssylvia** [comment]
What about the trailing commas? Shouldn't the second one be broken into new lines for the array to get trailing commas?

**Comment by vjeux** [comment]
Trailing commas are added when it's multiline. We don't put trailing commas when it fits in a single line.
