### ISSUE TITLE
Odd line break with arrow function as argument

### ISSUE THREAD

**Issue by karptonite** [prettier/prettier#2512]
```typescript
const sub = this.parent$
	.subscribe( parent => this.store.dispatch( new pins.LoadAction( { parent } ) ) );
```
formats to
```typescript
const sub = this.parent$.subscribe(parent =>
  this.store.dispatch(new pins.LoadAction({ parent })),
);
```
when `trailing-comma` is set to `all`. The combination of the split in the middle of the arrow function and the trailing comma was a bit jarring to see, although I wouldn't call it a bug.

It might look better like this, although I don't know what other repercussions that would have:
```typescript
const sub = this.parent$.subscribe(
  parent => this.store.dispatch(new pins.LoadAction({ parent })),
);
```

**Comment by vjeux** [comment]
This is actually on purpose and even though it may look a bit jarring, you'll likely get used to it.

**Comment by kentor** [comment]
I think that example with 1 argument is not the best to point out the bizarreness. Here's what prettier does with 2 arguments and one is an arrow:

Original:

```js
resolveFirst(
  'aws-credit-transfer-submit', 
  () => api.updateAwsCreditTransfer(data),
).then(response => {
  // something
});
```

prettier:
```js
resolveFirst('aws-credit-transfer-submit', () =>
  api.updateAwsCreditTransfer(data),
).then(response => {
  // something
});
```
