### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by pcvandamcb** [prettier/prettier#2514]
This project uses master as the working branch it seems, which causes the "current" documentation on GitHub to be incorrect. This is the documentation people will find when Googling the prettier project and is a common place to look for documentation.

For example there is a notion of config files and associated CLI-options, that do not actually work right now (1.5.3). It cost me personally a lot of time figuring out why those options didn't work when I just started with Prettier, which is a bad (new) user experience.

I would suggest using a "next" branch or similar for upcoming releases, so the master documentation is correct.

**Comment by vjeux** [comment]
@azz could you revert the docs commits until we actually release it, a lot of people are getting caught by this.

**Comment by azz** [comment]
Can do.

**Comment by azz** [comment]
Done https://github.com/prettier/prettier/commit/e8425a48998805a75e48e6b2b11696ada93add0e
