### ISSUE TITLE
JSX space turns into {" "}

### ISSUE THREAD

**Issue by sherzader** [prettier/prettier#2515]
before prettier:
```
<div><label><input type="checkbox" /> some@email.com <span className="calendar-icon" /></label></div>
```
after prettier:
```
<div>
	<label>
		<input type="checkbox" /> some@email.com{" "}
		<span className="calendar-icon" />
	</label>
</div>
```

**Comment by azz** [comment]
Prettier is splitting your code over multiple lines. When doing so, `{" "}` is inserted to preserve the space between the text node (`some@email.com`) and the next element (`<span>`).

This is required by JSX, and is by design.
