### ISSUE TITLE
Add option to keep quotes consistent instead of removing escape characters.

### ISSUE THREAD

**Issue by ssylvia** [prettier/prettier#2516]
Prettier provide an option to in use consistent quotes but will start mixing quotes to avoid escape characters. Can we provide an option to always use the same quote style and keep escape characters?

Looks like there's other interest in keeping all quotes consistent:
https://github.com/prettier/prettier/issues/838
https://github.com/prettier/prettier/issues/2031
https://github.com/prettier/prettier/issues/973
https://github.com/prettier/prettier/issues/2338

**Comment by azz** [comment]
We won't be adding an option for this at this time. There hasn't been a lot of demand for this so I think the default behaviour is good.

> https://github.com/prettier/prettier/issues/973#issuecomment-302964833
> We are now past 1.0 and are not going to do any big formatting changes like the one proposed here. There are pros and cons for both approaches and I don't think that we're going to get everyone happy, so it's best to keep with the status quo.
>
> As for prettier being a code formatter and not a refactoring tool, this is true. But single/double quotes is more often than not lumped inside of the formatting category, so prettier has to make a decision around those.
