### ISSUE TITLE
Assignment with cast gets parens stripped incorrectly in TypeScript

### ISSUE THREAD

**Issue by fortes** [prettier/prettier#2521]
```typescript
(foo.bar as Baz) = [bar];
```

Gets transformed to:

```typescript
foo.bar as Baz = [bar];
```

If you run that output again through prettier, you get:

```
SyntaxError: ';' expected. (1:16)
> 1 | foo.bar as Baz = [bar];
    |                ^
 ``` 

Repro: https://prettier.io/playground/#%7B%22content%22%3A%22(foo.bar%20as%20Baz)%20%3D%20%5Bbar%5D%3B%5Cn%2F%2F%20Line%20elow%20is%20the%20output%20of%20the%20above%20transform%5Cnfoo.bar%20as%20Baz%20%3D%20%5Bbar%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by azz** [comment]
Thanks for the report. We'll get this one fixed ASAP.
