### ISSUE TITLE
JSX files <span> with dynamic value inside creates a redundant {" "}

### ISSUE THREAD

**Issue by Rejpal** [prettier/prettier#2523]
Hello,

I am new to prettier so please be patient with me if this is a dumb question. 
I just tried to applicate prettier on my project where I use react (JSX files) to show count inside of branckets. Prettier reformatted the code and added some weird {" "} into it and I do not understand why?

Am I correct that this is a bug or it actually has a reason behind that I am missing?

Example of code: 
```
export default class Search extends Component {
  render () {
    let test = 1234;
    return (<span> ({test})</span>);
  }
}

```

the span from this example is resolved into 
```
<span>
  {" "}({test})
</span>
```

Live demo:
https://prettier.io/playground/#%7B%22content%22%3A%22export%20default%20class%20Search%20extends%20Component%20%7B%5Cnrender%20()%20%7B%5Cn%20%20let%20test%3D12%5Cnreturn%20(%3Cspan%3E%20(%7Btest%7D)%3C%2Fspan%3E)%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

Thanks for answer
Roman

**Comment by jindrichsamec** [comment]
Hi Roman, I think this is correct behavior, because you have space before `({test})` which Prettier translates to `{" "}`. Otherwise it will be part of indent and fails because you have set 2 spaces indent.

**Comment by azz** [comment]
That's right.

If prettier were to print this without the `{" "}` (which is the canonical JSX way to solve the following problem, btw), we'd end up with this:

```jsx
<span>
  ({test})
</span>
```

Which in HTML will look like:

```html
<span>(1234)</span>
```

And the space will be lost.

It is similar to the `&nbsp;` character in HTML.
