### ISSUE TITLE
Idea: what if we version-controlled the AST?

### ISSUE THREAD

**Issue by tamethecomplex** [prettier/prettier#2524]
Hi All,

I had a thought per @jlongster 's quote here (http://jlongster.com/A-Prettier-Formatter):

> The minutiae of syntax does not matter. Let it go. Let a tool like prettier just do it's job and focus on the real problems.

**If I like working without semicolons, but the rest of my team uses semicolons, shouldn't I be able to work in the code without semicolons?  If we version controlled the AST, I could view the code however I want,** and save it back to git as the AST.  Prettier would need to run on both ends to make the code readable when analyzing diffs, but we would accomplish this goal of taking styling debates out of software teams completely.

Anyone know of an existing effort on this?  Maybe it would be feasible to create a plugin for the version control server (GitLab, GitHub, BitBucket) so that when viewing files and commits, you see readable code, but behind the scenes, git is keeping track of the AST.

Note: sorry to create extra noise in the issues of this repo - but I thought those reading these comments were the most likely to resonate with this idea and know if a similar effort exists.

**Comment by azz** [comment]
It sure is an interesting concept. You could even have prettier wrap at the width of your text editor...

As you alluded to, a lot of tooling is developed around viewing source control, and merging diffs will be tricky with ASTs.

Maybe running prettier without semicolons in your editor integration, and _with_ semicolons in your precommit script would be a simpler solution?

**Comment by tamethecomplex** [comment]
@azz that makes sense.  I've actually never used a precommit script before, so this sounds like a good time / reason to learn and see how that could elegantly solve this problem.  I'll close the issue for now but comment back with a solution for any of those wanting to do the same thing.  Thanks for the lead :-)
