### ISSUE TITLE
Flow multiline unions should be kept

### ISSUE THREAD

**Issue by ooflorent** [prettier/prettier#2526]
I really like multiline unions in Flow:

```js
type TypeOfCard = 
  | "player"
  | "creature"
  | "structure"
  | "spell"
```

However, prettier converts the above snippet to:

```js
type TypeOfCard = "player" | "creature" | "structure" | "spell"
```

I think the type declaration should be kept on multiple line if the union starts with `|`.
Thoughts?

**Comment by aboyton** [comment]
For short unions I personally prefer them on one line. (At least for TypeScript, I assume Flow is the same here.)

**Comment by azz** [comment]
Prettier will always try to fit your code onto one line if it makes sense, which it does in this case, so it is working as intended.

We generally want to avoid looking at the source when making formatting decisions, it makes prettier much less predictable.

Additionally I don't think we've had a lot of requests for this feature so unfortunately you might be in the minority.

You can always use `// prettier-ignore` to keep the multiline formatting.
