### ISSUE TITLE
TS: missing semicolon on function with declare modifier

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#2534]
**Version**

1.5.3 / [current master](https://github.com/prettier/prettier/tree/a78d1389f6addf73d5364941d242f8aae79fc8b8)

**Code**

([Playground](https://prettier.io/playground/#%7B%22content%22%3A%22declare%20function%20x()%3B%5Cndeclare%20function%20y()%3A%20void%3B%5Cn%5Cndeclare%20namespace%20A%20%7B%5Cn%20%20%20%20function%20x()%3B%5Cn%20%20%20%20function%20y()%3A%20void%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```ts
declare function x();
declare function y(): void;

declare namespace A {
    function x();
    function y(): void;
}
```

**Expected**

no changes

**Actual**

```diff
-declare function x();
+declare function x()
-declare function y(): void;
+declare function y(): void
```

**Comment by azz** [comment]
This for the report. We should definitely print a semicolon there.
