### ISSUE TITLE
TypeScript: Function calls with generic type variables are wrongly formatted

### ISSUE THREAD

**Issue by christianhg** [prettier/prettier#2535]
Thanks for this great tool!

When passing function calls (or class constructions) with type variables through Prettier you get some weird formatting. 

One example is that this:

```
let output = identity<string>("myString");
```

Becomes this:

```
let output = identity < string > "myString";
```

https://prettier.io/playground/#%7B%22content%22%3A%22function%20identity%3CT%3E(arg%3A%20T)%3A%20T%20%7B%5Cn%20%20return%20arg%3B%5Cn%7D%5Cn%5Cnlet%20output%20%3D%20identity%3Cstring%3E(%5C%22myString%5C%22)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by ikatyang** [comment]
[It seems you're not using TypeScript parser?](https://prettier.io/playground/#%7B%22content%22%3A%22function%20identity%3CT%3E(arg%3A%20T)%3A%20T%20%7B%5Cn%20%20return%20arg%3B%5Cn%7D%5Cn%5Cnlet%20output%20%3D%20identity%3Cstring%3E(%5C%22myString%5C%22)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by lydell** [comment]
@ikatyang is correct, you need to enable the TypeScript parser here. What happened here is that your code is both valid TypeScript and valid (though unusual) JavaScript (with Flow), so you got no error.

**Comment by christianhg** [comment]
Oh! Sorry about that. Thanks for the quick answers.
