### ISSUE TITLE
option to insert systematically one empty line after if statement.

### ISSUE THREAD

**Issue by VincentBailly** [prettier/prettier#2537]
Prettier helps our code reviews to be more focused on the code itself rather than the styling, that is great, than you for enable this :)
There is one styling comment that still appears regularly in our code reviews, it is when we forget to insert an empty line after an if statement. Can we add an option to for the insertion of a new line after an if statement?

**Comment by popealex** [comment]
Maybe this is more about curly braces than if blocks specifically.  Examples:

```
// bad
function foo() {
    return 1 + 2;
}
function bar() {
    return 2 + 3;
}

// good
function foo() {
    return 1 + 2;
}

function bar() {
    return 2 + 3;
}

// bad
function baz(x) {
    if (x) {
        return 0;
    }
    return 1;
}

// good
function baz(x) {
    if (x) {
        return 0;
    }

    return 1;
}
```

**Comment by vjeux** [comment]
Thanks for raising this. We've tried to automatically add/remove empty lines early on the project but we couldn't find a good way to do so. We instead chose to give people the ability to decide where they want to put empty lines.

This is not a very happy trade-off but I don't really see a good way to get around it. I also think that adding lots of one-off rules like this is going to be more confusing to users than actually help.

So, I'm going to close this issue as wont-fix. Sorry about it!
