### ISSUE TITLE
Some consistency between object & array spacing?

### ISSUE THREAD

**Issue by zyklus** [prettier/prettier#2538]
It bothers me that objects have internal spacing when arrays don't!

    var x = { a: 10 };
    var y = [1, 2, 3];

**Comment by vjeux** [comment]
At this point we're not going to change this, sorry about it!

**Comment by lydell** [comment]
@zyklus See the [bracket-spacing](https://github.com/prettier/prettier#bracket-spacing) option.

**Comment by zdychacek** [comment]
Just curious, is there any rationale behind this different behaviour?

I can only see incosistency...
