### ISSUE TITLE
"[]"-notation assignment is getting broken

### ISSUE THREAD

**Issue by ipanasenko** [prettier/prettier#2540]
Hey, guys. Given this code:

```js
manifestCache[templateId] = readFileSync(`${MANIFESTS_PATH}/${templateId}.json`, { encoding: 'utf-8' });
```

Prettier formats it like this:

```js
manifestCache[
  templateId
] = readFileSync(`${MANIFESTS_PATH}/${templateId}.json`, {
  encoding: 'utf-8',
});
```

Do you think this is fine? Shouldn't it be more like this?
```js
manifestCache[templateId] =
  readFileSync(`${MANIFESTS_PATH}/${templateId}.json`, {
    encoding: 'utf-8',
  });
```

**Comment by azz** [comment]
I think this is a duplicate of #2482.

**Comment by mnpenner** [comment]
Sounds like the opposite problem to me. Those assignments *aren't* wrapping when they should, this one *is* wrapping but in a weird way.

**Comment by azz** [comment]
Might be the same root cause though - the `=` isn't allowed to break.

**Comment by azz** [comment]
Merging into #2482
