### ISSUE TITLE
CLI not doing anything

### ISSUE THREAD

**Issue by AloeDream** [prettier/prettier#2544]
Having prettier as a command in package.json

> "prettier": "prettier --single-quote --write 'src/**/*.scss'"
running command doesn't do anything, no errors given

prettier is installed as dev dependency today
Node 6.x LTS version.

**Comment by azz** [comment]
Hmm. Does the `src` directory live next to your `package.json`?

**Comment by AloeDream** [comment]
sure

**Comment by azz** [comment]
Sounds like the glob isn't matching any files. What happens if you replace `'` with `\"`?

**Comment by AloeDream** [comment]
@azz thanks, man! This helped! Thanks a lot!
