### ISSUE TITLE
Do not move eslint comments

### ISSUE THREAD

**Issue by arvigeus** [prettier/prettier#2549]
[Example code](https://prettier.io/playground/#%7B%22content%22%3A%22function%20thisIsNotOk(type)%20%7B%20%2F%2F%20eslint-disable-line%5Cn%20%20var%20thisIsOk%3B%20%2F%2F%20eslint-disable-line%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

The first comment should not be moved (and maybe every other "eslint-disable" comment)

**Comment by azz** [comment]
This has been a long-time outstanding issue and I don't think it will be fixed. We generally recommend using `// eslint-disable-next-line` on the previous line, rather than `} // eslint-disable-line`

**Comment by arvigeus** [comment]
Sorry, I was unable to find the existing issue. I know it's trivial to work around, and I thought it would be trivial to fix too.

**Comment by azz** [comment]
Yeah unfortunately it is far from trivial 😞 .

#1267 is the existing issue.
