### ISSUE TITLE
Consistent option names and values

### ISSUE THREAD

**Issue by Siilwyn** [prettier/prettier#2556]
When changing Prettier options I found some of the options confusing at first. Specifically the inverse naming of certain options `--no-*` and the wording e.g. `tab-width`.

I'd like to propose the following changes:
### From:
Default | CLI Override | API Override
--------|--------------|-------------
 `2` | `--tab-width <int>` | `tabWidth: <int>`

### To:
Default | CLI Override | API Override
--------|--------------|-------------
 `2` | `--indent-width <int>` | `indentWidth: <int>`

### From:
Default | CLI Override | API Override
--------|--------------|-------------
`false` | `--use-tabs` | `useTabs: <bool>`

### To:
Valid options:
 * `"spaces"` - Use spaces for indentation.
 * `"tabs"` - Use tabs for indentation.

Default | CLI Override | API Override
--------|--------------|-------------
`"spaces"` | <code>--indent-style <spaces&#124;tabs></code> | <code>indentStyle: "<spaces&#124;tabs>"</code>

### From:
Valid options:

 * `true` - Add a semicolon at the end of every statement.
 * `false` - Only add semicolons at the beginning of lines that may introduce ASI failures.

Default | CLI Override | API Override
--------|--------------|-------------
`true` | `--no-semi` | `semi: <bool>`

### To:
Valid options:

 * `true` - Add a semicolon at the end of every statement.
 * `false` - Only add semicolons at the beginning of lines that may introduce ASI failures.

Default | CLI Override | API Override
--------|--------------|-------------
`true` | `--semicolon` | `semicolon: <bool>`

### From:
Default | CLI Override | API Override
--------|--------------|-------------
`false` |  `--single-quote` | `singleQuote: <bool>`

### To:
Valid options:
 * `"single"` - Use single quotes.
 * `"double"` - Use double quotes.

Default | CLI Override | API Override
--------|--------------|-------------
`"double"` | <code>--quote <single&#124;double></code> | <code>quote: "<single&#124;double>"</code>

### From:
Valid options:
 * `true` - Example: `{ foo: bar }`.
 * `false` - Example: `{foo: bar}`.

Default | CLI Override | API Override
--------|--------------|-------------
`true` | `--no-bracket-spacing` | `bracketSpacing: <bool>`

### To:
Valid options:
 * `true` - Example: `{ foo: bar }`.
 * `false` - Example: `{foo: bar}`.

Default | CLI Override | API Override
--------|--------------|-------------
`false` | `--bracket-spacing` | `bracketSpacing: <bool>`

___

Thoughts? :bulb:

**Comment by azz** [comment]
The `--no-*` flags are just [minimist](https://github.com/substack/minimist).

You can already pass `--semi=false`, it means the same as `--no-semi`.

The documentation says to use `--no-X` in cases where doing `X` is the default prettier behaviour.

The `tabWidth` setting is from [recast](https://github.com/benjamn/recast).

With `--indent-style`, why have an enum for something that is fundamentally a boolean?

**Comment by lydell** [comment]
Naming things are hard. I don't think the current names are confusing enough to warrant all the work of deprecating old names and getting all other tools around prettier to do the same.

**Comment by Siilwyn** [comment]
@azz If the `--no-*` flags are also possible without it I would say using them without the `no` is clearer.

Prettier does not have to use the same naming as underlying modules such as `recast`.

Using `--ident-style` is related to `--indent-width`, because this removes the `tabs` assumption making it an enum.

@lydell it could be changed using 'aliases/fallbacks' so other tools don't have to change.

**Comment by azz** [comment]
Having two sets of names for everything seems much more confusing that just one.

I don't understand how `--no-semi` is more confusing than `--semi=false`, especially since the prior informs the user of the default behavior, rich prettier encourages people to use.

I'm going to close this for these reasons, and the reasons @lydell mentioned.
