### ISSUE TITLE
Allow passing parserOptions?

### ISSUE THREAD

**Issue by charlike** [prettier/prettier#2557]
Hi! :ok_hand:  Sorry but didn't find such issue in the tracker.

It seems that they are hardcoded. Is that needed of some internal use or what? I by default uses `babylon`, so thought that i can activate some plugins, then i just navigate to its file here and seen that there some hardcoded plugins. I believe we should have that ability to pass custom options to the chosen parser. In that way i will just activate only the stage-3 plugins.

**Comment by vjeux** [comment]
What is the option you'd like enabled?

**Comment by charlike** [comment]
It seems most of them are there, but the problem is that there are some below stage-3 too. I just want to ensure stage-3, nothing below it. Users may not feel it, of course, but guarantees in both sides for the future.

**Comment by vjeux** [comment]
With prettier we are lenient on what we parse and try to parse everything. This way if you use a feature, it'll be printed correctly, if you don't then you don't care. At the end of the day, the runtime will decide whether it works or not, not prettier.
