### ISSUE TITLE
Functions/function type defs are less readable with prettier

### ISSUE THREAD

**Issue by masaeedu** [prettier/prettier#2558]
Given the following function type definition:

```ts
type Display =
  (configType: ConfigType) =>
  (lens: MakeLens<State>) =>
  (x: any) =>
  StatelessComponent<any>;
```

Prettier will turn it into:

```ts
type Display = (
  configType: ConfigType
) => (lens: MakeLens<State>) => (x: any) => StatelessComponent<any>;
```

Which is basically unreadable to me. I realize what looks "pretty" is a matter of subjective opinion, but if there was some option for a more "mechanical" printing of function types that would be very useful for me.

**Comment by masaeedu** [comment]
Another example:

```ts
export type PropsTransformed =
  <P1, P2>(transform: (p2: P2) => P1) =>
  (Cmp: StatelessComponent<P1>) =>
  StatelessComponent<P2>;

export const transformed: PropsTransformed =
  transform =>
  Cmp =>
  props =>
  <Cmp {...transform(props)} />;
```

which is turned into:

```ts
export type PropsTransformed = <P1, P2>(
  transform: (p2: P2) => P1
) => (Cmp: StatelessComponent<P1>) => StatelessComponent<P2>;

export const transformed: PropsTransformed = transform => Cmp => props =>
  <Cmp {...transform(props)} />;
```

The implementation function isn't so bad, but the wrapping of `<P1, P2>(` seems rather strange. 

I think the two options needed would be a way to ask Prettier to leave the RHS of `=` blank when it needs to wrap, and an option to line break on `=>`.

**Comment by vjeux** [comment]
The issue with this one is that we inline those type definitions in order to be able to have functional calls be:

```js
a => b => c
```

instead of the normal way we would print it as:

```js
a =>
  b =>
    c
```

What's missing is to check that the arguments do not overflow. If they do, we should go back to the previous style. I haven't personally tried to do it, so I don't know if it's hard or just that no one tried to do it.
