### ISSUE TITLE
invalid reformat for array of functions with inline function type

### ISSUE THREAD

**Issue by tihonove** [prettier/prettier#2559]
Array of functions typed with flow:
```javascript
const actionArray: (() => void)[] = [];
```
reformats to
```javascript
const actionArray: () => void[] = [];
```
and cause flow errors.
Reproduced in [playground](https://prettier.io/playground/#%7B%22content%22%3A%22const%20actionArray%3A%20(()%20%3D%3E%20void)%5B%5D%20%3D%20%5B%5D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).

**Comment by azz** [comment]
Thanks for the report. This issue has now been fixed.

I'm surprised this one hasn't been reported yet!

**Comment by vjeux** [comment]
X[] was the array notation that was introduced early on to align with TypeScript but the flow team recommends Array<X> instead.
