### ISSUE TITLE
How to ignore next line in .css so it doesn't format 

### ISSUE THREAD

**Issue by nikitavoloboev** [prettier/prettier#2566]
I have .css file where on formatting, it actually messes up how I want CSS to be structured. Is it possible to ignore next line with prettier by specifying in a comment or something?

**Comment by azz** [comment]
Yep. Put `/* prettier-ignore */` on the previous line.

Could you post the code that prettier is messing up?

**Comment by nikitavoloboev** [comment]
[This line](https://github.com/calintat/minimal/blob/master/layouts/partials/css.html#L25) breaks into two and thus semantically it stops working too, no idea why. Also it formats that file really strangely too like this : 


![2017-07-31 at 10 59](https://user-images.githubusercontent.com/6391776/28770394-47e25a4c-75df-11e7-9f47-60a3d0500b84.png)

Also how do I insert /* prettier-ignore */ since CSS comments are <!-- -- > like this.

**Comment by azz** [comment]
HTML comments use `<!-- -->`, CSS comments use C style `/* */`.

It looks like what you are formatting is not CSS since it contains some templating language which prettier doesn't support.

**Comment by nikitavoloboev** [comment]
Is it possible to then specify Prettier to ignore formatting that single file? I use VS Code. Thank you.

**Comment by azz** [comment]
Not right now but with the next release of prettier it will be. (`.prettierignore` file support).
