### ISSUE TITLE
"declare" keyword for typescript interface is remove by prettier

### ISSUE THREAD

**Issue by e-cloud** [prettier/prettier#2567]
source:
```ts
declare interface Dictionary<T> {
    [index: string]: T
}

declare interface NDictionary<T> {
    [index: number]: T
}
```

prettier output: 
```ts
interface Dictionary<T> {
    [index: string]: T
}

interface NDictionary<T> {
    [index: number]: T
}
```

the expected output should be the same as source.

**Comment by e-cloud** [comment]
prettier version is 1.5.3

**Comment by ikatyang** [comment]
Looks like formatting `declare` behaves differently, should be both existed or both not-existed.

Notice that the `declare` modifier does nothing here.

([Playground](https://prettier.io/playground/#%7B%22content%22%3A%22declare%20interface%20X%20%7B%7D%5Cndeclare%20type%20Y%20%3D%20%7B%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

**source**

```ts
declare interface X {}
declare type Y = {};
```

**formatted**

```ts
interface X {}
declare type Y = {};
```

**Comment by azz** [comment]
What does `declare interface` do? Aren't interfaces already implicitly ambient?

**Comment by vjeux** [comment]
We have some regex going on to figure out if a node has declare or not, we probably aren't doing it on all the nodes.

Note that this is not a correctness issue, both mean the same thing.

**Comment by e-cloud** [comment]
The fact is we define these *declared* interface in a global typing file. It will not be imported by any ts file with real logic, but only used by typescript compiler to parse the typings.

These are common usecase. Take a exmpale, if you use a global library which is attach to `window`, you may have to do something like this:

```
declare interface Window {
    MyLib?: any;
}
```

**Comment by e-cloud** [comment]
@vjeux why not just preserve them all?

**Comment by vjeux** [comment]
We should preserve them all, it's a bug we need to fix

**Comment by frankwallis** [comment]
I am seeing this issue but relating to enums:

declaration.d.ts
```
declare enum ChangeType {
    Add = 0,
    Remove = 1
}
```
becomes
```
enum ChangeType {
    Add = 0,
    Remove = 1
}
```
And the build then fails with ```TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.```
Can you reopen please or let me know if I should raise a separate issue?

**Comment by azz** [comment]
@frankwallis This is an issue reported in #2709 which is fixed and will be in the next patch release.
