### ISSUE TITLE
You can only use optional-chaining when the 'optionalChaining' plugin is enabled. 

### ISSUE THREAD

**Issue by kurtextrem** [prettier/prettier#2568]
So how do I enable it?

**Comment by bakkot** [comment]
Prettier will need to add support for it explicitly.

We try to turn on all the optional syntax plugins, but when they add new node types they need explicit support.

We have a few others to do too - notably [`optionalCatchBinding`](https://github.com/michaelficarra/optional-catch-binding-proposal/), to support `try {} catch {}`.
