### ISSUE TITLE
RegExp is broken

### ISSUE THREAD

**Issue by wasd171** [prettier/prettier#2569]
Hello!

Prettier is incorrectly formating new RegExp() construction.
For example:
```
const reg = new RegExp('foo_(\d)')
```
is turned to
```
const reg = new RegExp("foo_(d)");
```
which is obviously not correct

**Comment by azz** [comment]
Prettier found a bug in your code, it should be `"foo_(\\d)"`.

**Comment by wasd171** [comment]
Oh, true. Sorry for disturbance :)
