### ISSUE TITLE
Removes Parentheses around "any" casts in TypeScript

### ISSUE THREAD

**Issue by ollwenjones** [prettier/prettier#2571]
There are cases where a legitimate piece of _unit test_ JavaScript involves monkey-patching a value that TypeScript says you cannot assign over. The typical workaround is to cast said thing as `<any>` to get around the type-checking
```typescript
(<any> myImportedFunc) = jest.fn();
```
Prettier handles all the other formatting well, but removes the parentheses, which generates a syntax error. 
```typescript
<any>myImportedFunc = jest.fn();
```
I thought it was perhaps related to JSX parsing, but the `as` keyword syntax does the same thing.
`(myImportedFunc as any) = jest.fn();` yields `myImportedFunc as any = jest.fn();`

**Comment by ikatyang** [comment]
Looks like [this PR](https://github.com/prettier/prettier/pull/2525/files#diff-bfbb946abbe1acdadb68ecac9c74538f) covered that case.

**Comment by azz** [comment]
Thanks for finding that, @ikatyang. Yes this should be fixed in master.

**Comment by ollwenjones** [comment]
Sorry I didn't do a more thorough search prior to opening the issue. Thank you, both.
