### ISSUE TITLE
Add configuration for ensuring file ends with newline.

### ISSUE THREAD

**Issue by mthadley** [prettier/prettier#2575]
Currently prettier ensures that the file ends with a newline. Is this something that we could allow to be configured or turned off? So something like `--no-newline-eof`.

If it seems reasonable, I'm perfectly willing to send a PR.

Thanks!

In general, I would prefer the default behavior of adding the newline. However, sometimes you need to satisfy other constraints outside of your control.

**Comment by vjeux** [comment]
What are those constraints outside of your control you are talking about?

**Comment by mthadley** [comment]
@vjeux Styleguides, niche tooling, etc.

It's a setting that is pretty standard in every text editor, so I wonder if it makes sense to have it available in prettier as well.

**Comment by vjeux** [comment]
Do you have something concrete that prevents you from using prettier because of it? I'd like to know the actual reason and not some generalities. Most of the time there's actually a better solution when you know the root cause than blindly adding an option.

**Comment by rhengles** [comment]
What would you need beyond `prettier(code).replace(/[\r\n]+$/,'')` ?

**Comment by mthadley** [comment]
@vjeux Sorry for being so vague. In my case, it's a style guide that mandates no trailing newlines at the end of the file. However this means that our CI fails when I run prettier with `--list-different`. 

So maybe I should just make use of the prettier API instead of the CLI?

**Comment by vjeux** [comment]
I would recommend trying to change this style guide at your company. It shouldn't be hard: flip the rule and do a codemod that adds a trailing line everywhere.

The recommended way to deploy prettier is to actually disable all those formatting rules. So you could also just disable this rule as part of the conversion.

I'm sorry but the goal of prettier is to have the minimum number of options. We're not looking into adding more and if we were to, this one is far from being on-top of the list.

Thanks for helping me understand your use case!

**Comment by mthadley** [comment]
@vjeux That totally makes sense, and I appreciate you taking the time to respond!

**Comment by azz** [comment]
This the first time I'm hearing about a style guide that _bans_ EOF newlines. Could you share some background on this? (Just for my own curiosity)

**Comment by probablyup** [comment]
Can this be reopened please? The fact that prettier removes EOF newlines without being able to turn that off is a really bad practice.

**Comment by kachkaev** [comment]
@probablyup Prettier should not be removing new lines - it adds them and there is not option to change such behavior by design.

If you notice that a final new line gets removed on save, this must be some other tool that does it. I’d check editor settings and eslint first, but that’s not a full list.

Let us know what you find out as this can help others.

**Comment by probablyup** [comment]
@kachkaev Hmm ok, thank you. I'm using VSCode + Prettier extension so maybe it's doing something itself.

**Comment by joglr** [comment]
@probablyup I'm experiencing the same issue as well. I use the prettier extension in Visual Studio Code and prettier seems to remove EOF newlines.

**Comment by herbowicz** [comment]
In VS Code you can set `"files.insertFinalNewline": true` and Prettier won't override this settings.

**Comment by titoBouzout** [comment]
@vjeux https://github.com/prettier/plugin-php/issues/681

**Comment by titoBouzout** [comment]
https://www.google.com.uy/search?q="Warning%3A+Cannot+modify+header+information+-+headers+already+sent+by"
