### ISSUE TITLE
VS Code Extension has been moved to Prettier organization

### ISSUE THREAD

**Issue by esbenp** [prettier/prettier#2577]
I moved the prettier-vscode repository from my profile to the prettier organization today. Surely, some links needs to be changed. I have opened up the party by submitting https://github.com/prettier/prettier/pull/2576 :-) I am unsure what other links exist that needs changing

**Comment by vjeux** [comment]
Awesome, thanks a ton for building this extension. Editor integrations are the main way people use prettier so the project success is in no small part thanks to your work!

Let me know if I can help you in any way :)

**Comment by esbenp** [comment]
Thanks for the kind words. I am still interested in letting go of the extension administration. Unfortunately, it is not really an option (https://github.com/prettier/prettier-vscode/issues/41#issuecomment-313622390). I think a good first step would be to give someone from the prettier organization collaborator access to the extension. Is that you? Send me any number of e-mails I should add to the extension so you can publish.

**Comment by CiGit** [comment]
I'd like to know who has admin rights on the repository? We will need to add collaborators (now and in the future) 😄

**Comment by vjeux** [comment]
I just bumped the two of you as admin of the repo. Feel free to handle it as your own :)

For admin rights on the vscode plugin, I'm still in vacation without a computer, I'll create a vscode account when I get home.

**Comment by vjeux** [comment]
Okay, I have an account if you want to add me: vjeuxx@gmail.com (if not, it's totally fine as well :p )

**Comment by esbenp** [comment]
You need a Visual Studio marketplace account https://www.visualstudio.com/da-dk/docs/setup-admin/team-services/sign-up-for-visual-studio-team-services

**Comment by vjeux** [comment]
Okay, I have vjeux.visualstudio.com

**Comment by esbenp** [comment]
![screen shot 2017-08-04 at 10 06 34](https://user-images.githubusercontent.com/934819/28959885-b10fd1aa-78fc-11e7-9f67-9718b4d45870.png)

Alright I have no idea what is wrong I cannot find you with either username or e-mail. Honestly, the Visual Studio Marketplace backend is fairly confusing. Have no idea how to do it

**Comment by CiGit** [comment]
I've never done it, but I think it should be in your publishers. Yes, it is far from user-friendly.
![image](https://user-images.githubusercontent.com/1453420/28960409-d11ae41a-78fe-11e7-8bdd-467497c495b1.png)
https://marketplace.visualstudio.com/manage/publishers/esbenp

**Comment by esbenp** [comment]
Thanks @CiGit !
@vjeux you have been added now. I guess we can close this issue for now. :-)
