### ISSUE TITLE
Prettier breaks LESS-code for comments with comma between selectors

### ISSUE THREAD

**Issue by paleite** [prettier/prettier#2579]
E.g. https://github.com/twbs/bootstrap/blob/master/less/type.less#L234 will be broken into multiple lines and the comment will be split at the comma, resulting in:
```
 abbr[title],
-// Add data-* attribute to help out our tooltip plugin, per https://github.com/twbs/bootstrap/issues/5257
+// Add data-* attribute to help out our tooltip plugin,
+per https://github.com/twbs/bootstrap/issues/5257
 abbr[data-original-title] {
```

**Comment by azz** [comment]
The root cause of this is shared with #2468. It's due to the selector parser we're using doesn't support comments. As a workaround you could try moving the comments above the selector.
