### ISSUE TITLE
Don't remove parens after keyof in TypeScript

### ISSUE THREAD

**Issue by bartq** [prettier/prettier#2582]
prettier 1.5.3

Before:
`type T = keyof (A & B)`

After:
`type T = keyof A & B;`

Problem:
`keyof A & B !== keyof (A & B)`;

I had to solve it like that:
```
type And = A & B;
type T = keyof And<A,B>;
```

Expected: don't strip parens.

**Comment by azz** [comment]
On mobile at the moment but I seem to recall fixing this. Could you try installing prettier master from GitHub?

`npm i prettier/prettier`

**Comment by azz** [comment]
Found it.

https://github.com/prettier/prettier/pull/2503/files#diff-227221cc4845e19a1bd37ff9e7f5f858

Reopen if it is still an issue.

**Comment by bartq** [comment]
Yeah, but I've checked it online: https://prettier.io/playground/#%7B%22content%22%3A%22type%20T%20%3D%20keyof%20(A%20%26%20B)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

Footer says it's prettier 1.5.3 master.

**Comment by azz** [comment]
Yeah that's a bit misleading... It's using generated code on master (see https://github.com/prettier/prettier/tree/master/website/static/lib), which is _roughly_ 1.5.3, plus potentially some changes from master. We should change that to just say 1.5.3 perhaps (or always rebuild master)

**Comment by bartq** [comment]
it should be definitely rebuilt on each commit. It's too bad if it's manual build job run occasionally.
