### ISSUE TITLE
Validation error: trailing comma

### ISSUE THREAD

**Issue by tbillington** [prettier/prettier#2583]
I get this issue running prettier from both atom and vscode, but only in 1 of my repos, others are fine.

I don't know what is causing this. In vsconfig the default value is `"prettier.trailingComma": "none"`. I tried setting it in my user settings to `"prettier.trailingComma": false` but there was no change to the error message.

Is there someplace I should be looking for prettier config file ? I searched my disk but couldn't find anything.

```
● Validation Error/Users/john/src/github.com/foo/bar/src/file.js::

  Option "trailingComma" must be of type:
    boolean
  but instead received:
    string

  Example:
  {
    "trailingComma": false
  }
```

**Comment by azz** [comment]
That looks like a very old version of prettier.
