### ISSUE TITLE
Single quotes option does not apply if string contains single quote

### ISSUE THREAD

**Issue by ValeriiVasin** [prettier/prettier#2585]
If string contains single quote - string is printed with double quotes.

for example:
```js
const str = 'Hello wold\'s best';
```

will become
```js
const str = "Hello wold's best";
```

even if single-quotes option is used.

Example on playground: https://prettier.io/playground/#%7B%22content%22%3A%22const%20str%20%3D%20'Hello%20wold%5C%5C's%20best'%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

I would assume that correct behavior would be to left string untouched (since its already using single quotes)

**Comment by azz** [comment]
This is by design.

https://github.com/prettier/prettier#quotes

> If the number of quotes outweighs the other quote, the quote which is less used will be used to format the string - Example: `"I'm double quoted" `results in `"I'm double quoted"` and `"This \"example\" is single quoted"` results in `'This "example" is single quoted'`.
