### ISSUE TITLE
Comments in switch statements (JavaScript)

### ISSUE THREAD

**Issue by schalkneethling** [prettier/prettier#2586]
The indentation of comments inside `switch/case` blocks causes inconsistent indentation of code block. See here for an example:

https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/events.js#L55

**Comment by josephfrazier** [comment]
Can you describe the expected/actual output? I pasted the code in the linked file into the online playground, and couldn't find anything wrong with it: [demo](https://prettier.io/playground/#%7B%22content%22%3A%22(function()%20%7B%5Cn%20%20%20%20'use%20strict'%3B%5Cn%5Cn%20%20%20%20var%20exampleChoiceList%20%3D%20document.getElementById('example-choice-list')%3B%5Cn%20%20%20%20var%20liveEditorContainer%20%3D%20document.getElementById('live')%3B%5Cn%20%20%20%20var%20liveEditor%20%3D%20document.getElementById('editor')%3B%5Cn%20%20%20%20var%20newLineRegExr%20%3D%20%2F%5C%5Cn(%3F!%24)%2Fg%3B%5Cn%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Binds%20an%20event%20to%20the%20%60window%60%20object%20and%20listens%20for%20the%20onload%20event.%5Cn%20%20%20%20%20*%20When%20the%20event%20is%20fired%2C%20the%20iframe%20load%20time%20is%20calculated%2C%20and%20the%20result%5Cn%20%20%20%20%20*%20passed%20on%20to%20%60trackFrameLoadTime%60%20for%20performance%20analytics.%5Cn%20%20%20%20%20*%20%40param%20%7BString%7D%20exampleType%20-%20One%20of%20js%20or%20css%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20function%20sendPerformanceMetric(exampleType)%20%7B%5Cn%20%20%20%20%20%20%20%20window.onload%20%3D%20function%20sendLoadTime()%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20mceAnalytics.trackFrameLoadTime(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20exampleType%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mceUtils.calculateFrameLoadTime()%5Cn%20%20%20%20%20%20%20%20%20%20%20%20)%3B%5Cn%20%20%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20%2F%2F%20only%20bind%20events%20if%20the%20container%20exist%5Cn%20%20%20%20if%20(exampleChoiceList)%20%7B%5Cn%20%20%20%20%20%20%20%20sendPerformanceMetric('css')%3B%5Cn%5Cn%20%20%20%20%20%20%20%20exampleChoiceList.addEventListener('keyup'%2C%20function()%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20if%20(!localStorage.getItem('firstCSSEditRecorded'))%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mceAnalytics.trackFirstEdit('css')%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20if%20(liveEditor)%20%7B%5Cn%20%20%20%20%20%20%20%20var%20lastNewLineCount%20%3D%200%3B%5Cn%5Cn%20%20%20%20%20%20%20%20sendPerformanceMetric('js')%3B%5Cn%5Cn%20%20%20%20%20%20%20%20liveEditorContainer.addEventListener('click'%2C%20function(event)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20switch%20(event.target.id)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20case%20'execute'%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mceAnalytics.trackRunClicks()%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D)%3B%5Cn%5Cn%20%20%20%20%20%20%20%20liveEditor.addEventListener('keyup'%2C%20function(event)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20var%20code%20%3D%20liveEditor.querySelector('code').innerText%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20get%20the%20line%20numbers%20container%5Cn%20%20%20%20%20%20%20%20%20%20%20%20var%20lineNumbersRows%20%3D%20liveEditor.querySelector(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'.line-numbers-rows'%5Cn%20%20%20%20%20%20%20%20%20%20%20%20)%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20switch%20(event.keyCode)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Enter%2FReturn%20key%20was%20pressed%5Cn%20%20%20%20%20%20%20%20%20%20%20%20case%2013%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20spanElem%20%3D%20document.createElement('span')%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20lastNewLineCount%20%3D%20code.match(newLineRegExr).length%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F*%20append%20the%20empty%20span%20element%20to%20the%20end%20of%20the%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20line%20numbers%20container.%20The%20causes%20additional%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20numbers%20to%20be%20added%20as%20a%20user%20presses%20the%20enter%20key%20*%2F%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20lineNumbersRows.appendChild(spanElem)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Backspace%20was%20pressed%5Cn%20%20%20%20%20%20%20%20%20%20%20%20case%208%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20newLineCount%20%3D%20code.match(newLineRegExr).length%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(newLineCount%20%3C%20lastNewLineCount)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20lineNumbersRows.removeChild(lineNumbersRows.lastChild)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20if%20(!localStorage.getItem('firstJSEditRecorded'))%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mceAnalytics.trackFirstEdit('js')%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Catches%20JavaScript%20errors%20from%20the%20editor%20that%20bubble%20up%20to%20the%5Cn%20%20%20%20%20*%20window%20and%20passes%20them%20on%20to%20GA%5Cn%20%20%20%20%20*%2F%5Cn%20%20%20%20window.onerror%20%3D%20function(msg%2C%20url%2C%20lineNo%2C%20columnNo%2C%20error)%20%7B%5Cn%20%20%20%20%20%20%20%20var%20errorDetails%20%3D%20%5B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20'URL%3A%20'%20%2B%20url%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20'Line%3A%20'%20%2B%20lineNo%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20'Column%3A%20'%20%2B%20columnNo%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20'Error%20object%3A%20'%20%2B%20JSON.stringify(error)%5Cn%20%20%20%20%20%20%20%20%5D.join('%20-%20')%3B%5Cn%5Cn%20%20%20%20%20%20%20%20mceAnalytics.trackEvent(%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20category%3A%20'JavaScript%20Errors'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20action%3A%20errorDetails%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20label%3A%20msg%5Cn%20%20%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D%3B%5Cn%7D)()%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by schalkneethling** [comment]
@josephfrazier The indentation in the demo is indeed correct. You will notice that, on the linked example, the comments are indented an additional 4 spaces, and does not line up as it does in the demo.

Wonder if it may be a clash between prettier and something like .editorconfig. I toggle the two off and then turn on one and then the other to see what happens.

**Comment by josephfrazier** [comment]
Oh, are you referring to how

```js
                    /* append the empty span element to the end of the
                    line numbers container. The causes additional line
                    numbers to be added as a user presses the enter key */
```

becomes

```js
          /* append the empty span element to the end of the
                    line numbers container. The causes additional line
                    numbers to be added as a user presses the enter key */
```

? If so, I think that is covered in https://github.com/prettier/prettier/issues/648

**Comment by schalkneethling** [comment]
@josephfrazier Yup, that very much sounds like it might be the same thing here. Thanks!
