### ISSUE TITLE
SugarSS Support

### ISSUE THREAD

**Issue by calebeby** [prettier/prettier#2596]
Hello,

I think it would be really cool if `prettier` could prettify `sugarss` code. [SugarSS](https://github.com/postcss/sugarss) is an indent-based syntax for PostCSS. It supports both [parsing](https://github.com/postcss/sugarss#sugarss-to-css) and [stringifying](https://github.com/postcss/sugarss#css-to-sugarss). Is this feasible for Prettier to implement?

Thanks

**Comment by calebeby** [comment]
@vjeux Care to provide your input?

**Comment by vjeux** [comment]
Sorry I didn't respond. We're trying to only support officially mainstream languages and variants. However, we do have all the infrastructure in place to support new languages, I would recommend forking prettier to do so :)
