### ISSUE TITLE
flow parser: annotations in comments are printed without comments

### ISSUE THREAD

**Issue by davidaurelio** [prettier/prettier#2597]
When using the flow parser, all flow annotations inside of special comments (`/*: ... */` and `/*:: ... */`) are printed as annotations *without* comments. [Example](https://prettier.io/playground/#%7B%22content%22%3A%22%2F*%3A%3A%5Cndeclare%20class%20A%20%7B%7D%5Cn*%2F%5Cn%5Cn%5Cnclass%20B%20%7B%5Cn%20%20%2F*%3A%3A%5Cn%20%20a%3A%20A%3B%5Cn%20%20*%2F%5Cn%20%20constructor(a%2F*%3A%20A*%2F)%20%7B%5Cn%20%20%20%20this.a%20%3D%20a%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).

It is not always feasible to switch to babylon as parser, so it would be nice if prettier would support outputting comments with flow’s parser, too.

**Comment by hawkrives** [comment]
See also https://github.com/prettier/prettier/issues/719

**Comment by vjeux** [comment]
Using the flow parser to output comments if there's any `/*:` comment inside of the file would actually be pretty easy but haven't had the time to work on it and won't be in the forseeable future. If someone is interested, it should be fun to work on and impactful.

**Comment by duailibe** [comment]
`/*: ... */` comments handling just landed in master (#3449)

`/*:: ... */` comments are WIP :)

**Comment by dmnd** [comment]
> `/*:: ... */` comments are WIP :)

@duailibe, does this happen to still be in progress?

**Comment by thorn0** [comment]
Not an issue anymore because support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687
Now this output is intended.
