### ISSUE TITLE
preserve headroom and legroom?

### ISSUE THREAD

**Issue by kswope** [prettier/prettier#2599]
I find the following reformatting counterproductive, meaningless, and just ugly

```
function func(){

  // first chunk
  let x = 1
  let y = 2
  let z = 3
  
  // second chunk
  let a = 1
  let b = 2
  let c = 3
  
  // third chunk
  let i = 1
  let j = 2

}
```

```
function func() {
  // first chunk
  let x = 1;
  let y = 2;
  let z = 3;

  // second chunk
  let a = 1;
  let b = 2;
  let c = 3;

  // third chunk
  let i = 1;
  let j = 2;
}
```

**Comment by k15a** [comment]
We already said in a couple of issues that we will not support this: #2352

**Comment by kswope** [comment]
Why take code that is more readable and make it less readable?  Are you saying this is outside the scope of functionality, will cause conflicts, is too difficult to do, or that prettier wants to make your code less readable, as demonstrated above.  This issue will keep coming up until the end of time, believe me.

**Comment by vjeux** [comment]
@kswope prettier is an opinionated code formatter. One of the opinion is that code should not have empty lines at the beginning or end of a block. What I found is that the important piece is not the actual decision about having space or not in this context, but the fact that it is consistently applied.

As for this issue, you're probably going to be surprised but it hasn't come up a lot. There are parts of prettier that are much more controversial than putting spaces around blocks :)
