### ISSUE TITLE
CSS-in-JS ampersand unexpected behavior

### ISSUE THREAD

**Issue by petetnt** [prettier/prettier#2601]
Hey,

we ran into this slightly awkward behaviour / edge case with ampersands in `CSS-in-JS` scenarios. Prettier transforms code that looks like this:

``` js
const Foo = styled.p`
  max-width: 980px;
  ${mediaBreakpointOnlyXs`
    && {
      font-size: 0.8rem;
    }
  `}

  &.bottom {
    margin-top: 3rem;
  }
`;
```

to this:

``` js
const Foo = styled.p`
  max-width: 980px;
  ${mediaBreakpointOnlyXs`
    && {
      font-size: 0.8rem;
    }
  `} &.bottom {
    margin-top: 3rem;
  }
`;
```

Expected would be something along the lines of:

``` js
const Foo = styled.p`
  max-width: 980px;
  ${mediaBreakpointOnlyXs`
    && {
      font-size: 0.8rem;
    }
  `};

  &.bottom {
    margin-top: 3rem;
  }
`;
```

See the positioning of `&.bottom` after the prettifying. Like said it might be an edge case that only happens with interpolated things that don't end with ; and are followed with &, but will check if this occurs with other similar cases (and in LESS/SASS situations) if needed.

Thanks for prettier, it saves me hours every week ❤️ ❤️

**Comment by azz** [comment]
Workaround is to add a semicolon after `\`}`

https://prettier.io/playground/#%7B%22content%22%3A%22const%20Foo%20%3D%20styled.p%60%5Cn%20%20max-width%3A%20980px%3B%5Cn%20%20%24%7BmediaBreakpointOnlyXs%60%5Cn%20%20%20%20%26%26%20%7B%5Cn%20%20%20%20%20%20font-size%3A%200.8rem%3B%5Cn%20%20%20%20%7D%5Cn%20%20%60%7D%3B%5Cn%5Cn%20%20%26.bottom%20%7B%5Cn%20%20%20%20margin-top%3A%203rem%3B%5Cn%20%20%7D%5Cn%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by fisker** [comment]
this one is fixed

**Comment by lydell** [comment]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAxCFMC8mGAngDZwAmAdAA4AGAOlJpgLYCGAHgLQDuAS0owAFkkwBOABwAGWlwDczVgBJgbKgI4AhAE5wOAa1oQBsAPJQyJABpomLVpgBkzzMGVPWAM2gweaAIAXnDiMtRS+mxKjqwAvp70CVCeztQARhAwMBBs7p6snLoA5mY8ObTiAMxRMfHM9AogADQgELQwAujIoBy6uhB8AAp9CGjIIBwAbqaULSDpuhxghnAwAMq0y2bFyDC6AK5wrSIwbGQA6iIC8GhbYHDrYzcCUzckE2Bo461maHC6GBDJbFTjIbwcMj-VoAKzQXD0y1WGw4GgAMmY4ODIdCQHCuOsdhQAIoHLJYpAQqHHEBbXT-XQTdIcdJwMjzWi6MwwC5CUTIWStTkQf4XJa0CacuAMqZY1oARzJ8GB7XGKA4aB4UDgVCo830ioE+mBHFBHGx1Na-zYAj2hxpgSgxRJSopVNxMBZvOEImQACZWvsOAIyDsAMK5MEoKDQOUgA7-AAqLLV7ppUyOAEkoJQEBswFyOgBBHPrGDkN04uBxOJAA)
```sh
--parser babel
```

**Input:**
```jsx
const Foo = styled.p`
  max-width: 980px;
  ${mediaBreakpointOnlyXs`
    && {
      font-size: 0.8rem;
    }
  `}

  &.bottom {
    margin-top: 3rem;
  }
`;
```

**Output:**
```jsx
const Foo = styled.p`
  max-width: 980px;
  ${mediaBreakpointOnlyXs`
    && {
      font-size: 0.8rem;
    }
  `}

  &.bottom {
    margin-top: 3rem;
  }
`;

```

We need to make sure there are tests for this.
