### ISSUE TITLE
`declare` in comments gets added to following variable declarations

### ISSUE THREAD

**Issue by Pinpickle** [prettier/prettier#2604]
TSLint has a rule that ends with the word "declare", so if it is disabled in comments, you can end up with the last word in a comment being "declare". Prettier interprets this as a `declare` keyword before the statement on the following line.

Input

```
// tslint:disable-next-line:no-use-before-declare
const hello = 5;
```

Output

```
// tslint:disable-next-line:no-use-before-declare
declare const hello = 5;
```

Expected behaviour is that the `declare` keyword not appear before `const`.

Playground: https://prettier.io/playground/#%7B%22content%22%3A%22%2F%2F%20tslint%3Adisable-next-line%3Ano-use-before-declare%5Cnconst%20hello%20%3D%205%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

I've checked that this happens with `let`, `var`, `function`, `const` and `type` keywords in lines following these comments.

For anyone else running into this, you can work around it by adding something else to the end of the comment

```
// tslint:disable-next-line:no-use-before-declare //
const hello = 5;
```

**Comment by azz** [comment]
Thanks for the report.

@vjeux We should probably fix this in the parser and remove the current hack.
