### ISSUE TITLE
JSON formatting not working in playground.

### ISSUE THREAD

**Issue by ritz078** [prettier/prettier#2606]
Here is the [repl link ](https://prettier.io/playground/#%7B%22content%22%3A%22%7B%5Cn%20%20%5C%22hello%5C%22%3A%20%5B%20%7B%5Cn%20%20%20%20%20%20%5C%22_id%5C%22%3A%20%5C%225988946e45e52d60b33a25c7%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22latitude%5C%22%3A%2050.087977%2C%5Cn%20%20%20%20%20%20%5C%22longitude%5C%22%3A%2072.167197%2C%5Cn%20%20%20%20%20%20%5C%22tags%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%20%20%5C%22nulla%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22ullamco%5C%22%5Cn%20%20%20%20%20%20%5D%2C%5Cn%20%20%20%20%20%20%5C%22friends%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%5C%22id%5C%22%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Robinson%20Woods%5C%22%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%5C%22id%5C%22%3A%201%2C%5Cn%20%20%20%20%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Lottie%20Hogan%5C%22%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%5D%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%7B%5Cn%20%20%20%20%20%20%5C%22_id%5C%22%3A%20%5C%225988946ef6090217857d7b0f%5C%22%2C%5Cn%20%20%20%20%20%20%5C%22latitude%5C%22%3A%2047.460772%2C%5Cn%20%20%20%20%20%20%5C%22longitude%5C%22%3A%2085.95137%2C%5Cn%20%20%20%20%20%20%5C%22tags%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%20%20%5C%22aliqua%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%5C%22nulla%5C%22%5Cn%20%20%20%20%20%20%5D%2C%5Cn%20%20%20%20%20%20%5C%22friends%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%5C%22id%5C%22%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Mamie%20Wyatt%5C%22%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%5C%22id%5C%22%3A%201%2C%5Cn%20%20%20%20%20%20%20%20%20%20%5C%22name%5C%22%3A%20%5C%22Alejandra%20Mcdaniel%5C%22%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%5D%5Cn%20%20%20%20%7D%5Cn%20%20%5D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) 

Let me know if there is something I am missing.

Thanks for this awesome module.

**Comment by mitermayer** [comment]
Looks like `parser-json.js` can't be found: https://prettier.io/lib/parser-json.js 

```
worker.js:80 Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://prettier.io/lib/parser-json.js' failed to load.
```

**Comment by airato** [comment]
yeah, the repl link is missing "parser" param, so the initial error is misleading. But when parser set to json, we have the 404 error for paser-json.js file.

**Comment by airato** [comment]
so, there is no such file, since it was removed in https://github.com/prettier/prettier/pull/2476 
cc @josephfrazier

**Comment by ritz078** [comment]
Here is another link without any 404 error https://runkit.com/ritz078/598b561a60eb630014a2b9fc. Still receiving the same error.

**Comment by airato** [comment]
@ritz078 in this example it works if you add the `parser` option:
`const x = prettier.format(json, { parser: 'json'});`

**Comment by ritz078** [comment]
Oh thanks. That's totally my mistake. But should I let this issue open until its resolved on repl ?

**Comment by airato** [comment]
yeah, let's keep it open since JSON formatting in the playground is not working. 
Maybe rename the issue to point out, that this is a playground issue.

**Comment by azz** [comment]
There is no longer a `parser-json`, we just use `parser-babylon`. We need to hard code that knowledge in the webworker.
