### ISSUE TITLE
Ability for Prettier to auto waterfall code (imports and variables)

### ISSUE THREAD

**Issue by spoco2** [prettier/prettier#2607]
It would be awesome if prettier could automatically 'waterfall' code imports and consts/let/vars

By way of example:

**Non waterfalled:** 
```static CARD_TEMPLATE_TABLE = "card_template";
static PROGRAM_TEMPLATE_ID = "program_template_id";
static CARD_TEMPLATE_ID = "card_template_id";
static CARD_TEMPLATE_LOOKUP_TABLE = "program_template_to_card_template";
 
createdAt: Date;
createdBy: number;
name: String;
cardTemplates: CardTemplate[];
id: number;
orgId: number;
key: String;
 
static validationSchema: any = {
    name: "required|string"
};
```

**Waterfalled:**
```static CARD_TEMPLATE_LOOKUP_TABLE = "program_template_to_card_template";
static PROGRAM_TEMPLATE_ID = "program_template_id";
static CARD_TEMPLATE_TABLE = "card_template";
static CARD_TEMPLATE_ID = "card_template_id";
 
static validationSchema: any = {
    name: "required|string"
};
 
cardTemplates: CardTemplate[];
createdBy: number;
createdAt: Date;
orgId: number;
name: String;
key: String;
id: number;
```

While it seems a silly thing to provide or enforce initially, it reduces cognitive load and, as with all mandated styles, it reduces the amount of time spent pondering layout when coding.

**Comment by ikatyang** [comment]
This looks like [Code Quality Rules](https://github.com/prettier/prettier#how-does-it-compare-to-eslint-or-tslint-stylelint) to me, which is the role of linter not formatter, formatter won't affect their AST.

**Comment by spoco2** [comment]
@ikatyang It's exactly not code quality, it's purely formatting. It has zero actual effect on the correctness of the code, it's purely a visual conformity thing.

**Comment by ikatyang** [comment]
Considering the `Object.keys` case, you may not use its ordering but it did affect the correctness, the most important rule is that formatter must not affect the AST (including ordering).

```ts
class X {
    static A = "A";
    static B = "B";
    static C = "C";
}

console.log(Object.keys(X)) //=> ['A', 'B', 'C']
```

```ts
class X {
    static C = "C";
    static B = "B";
    static A = "A";
}

console.log(Object.keys(X)) //=> ['C', 'B', 'A']
```

**Comment by lydell** [comment]
There have been several issues about sorting imports, object keys, destructuring and CSS properties. For imports and objects keys, it is not safe to reorder things, since side effects will run in a different order. Destructuring and CSS have similar problems. For this reason, Prettier never reorders things.
