### ISSUE TITLE
RawText ";" must be wrapped in an explicit <Text> component

### ISSUE THREAD

**Issue by mark0978** [prettier/prettier#2608]
I really like format on save, but I've had to disable it because

Prettier is forcing
```
        if (!reviews[bizid]) {
            return (<Text>Loading...</Text>);
        }
```
To be:
```
        if (!reviews[bizid]) {
            return <Text>Loading...</Text>;
        }
```
On save in Atom.

Which react is NOT happy about.  I'm using it in atom
├── prettier@1.5.3
└─┬ prettier-eslint@6.4.2
  └── prettier@1.5.3  deduped

**Comment by vjeux** [comment]
What do you mean by "Which react is NOT happy about"? This is totally valid JavaScript/JSX.

**Comment by mark0978** [comment]
Yea, nevermind.  I had a ; in another spot that was actually causing the problem.  The traceback on this message from ReactNative sucks because it gives you no idea where that bare ; is.  This is NOT an issue.
