### ISSUE TITLE
eslint indent fails for prettier JSX ternary

### ISSUE THREAD

**Issue by matt-sm** [prettier/prettier#2609]
this is an example of code formatted by prettier:
```
<li>
  {this.props.memberInfo.isAuthenticated
    ? <span>
        {this.dashBoardLink()}
      </span>
    : <a href="/signup">Join the Marketplace</a>}
</li>
```
eslint indent actually wants:
```
<li>
  {this.props.memberInfo.isAuthenticated
    ? <span>
      {this.dashBoardLink()}
    </span>
    : <a href="/signup">Join the Marketplace</a>}
</li>
```
(4th and 5th lines bought back 2 spaces) 
indent config is:
```
"indent": ["error", 2, { "SwitchCase": 1 }],
```
I've spent a lot of time playing with config on both sides (prettier/indent) to no avail.

**Comment by SimenB** [comment]
You should turn off the indent rule when using prettier (recommended to just use https://github.com/prettier/eslint-config-prettier)

**Comment by matt-sm** [comment]
I already had `eslint-config-prettier` installed but it seems I had to remove that extra `indent` config as well.

`./node_modules/.bin/eslint-config-prettier-check` helped.

Thanks!

**Comment by lydell** [comment]
> I already had `eslint-config-prettier` installed but it seems I had to remove that extra `indent` config as well.

Yep, rules that you yourself add to your eslintrc always override every config that you `extend`. (eslint-config-prettier can only override other configs you extend, but not your own rules.)

> `./node_modules/.bin/eslint-config-prettier-check` helped.

Correct, this is exactly what that CLI tool is supposed to help with! Glad it was of use to you.
