### ISSUE TITLE
[Option] Don't log untouched files

### ISSUE THREAD

**Issue by christianhg** [prettier/prettier#2611]
I have a setup where `prettier --write` runs through my codebase on each file change. This pollutes my terminal log since Prettier outputs all files it comes across (and highlights the ones that it changes).

Is it possible to configure Prettier to only log the changed files?

**Comment by hawkrives** [comment]
I have a script that queries git for the changed JS files since the last commit (and another one that gets all changed files since master) and only runs them through prettier, if you'd like them.

**Comment by azz** [comment]
Would something like this work?

```bash
prettier --write > /dev/null
git diff --name-only
```

**Comment by christianhg** [comment]
Thanks, @azz. That didn't really seem to work for me. It didn't show the file names at just showed this at the end of each file change: 

![screen shot 2017-08-18 at 12 30 01](https://user-images.githubusercontent.com/4602382/29455313-0247327e-8411-11e7-8041-1843f4d20bce.png)

Is it possible to keep this issue open as a feature request? I really see the value in having the option to not output unchanged files. In a big project the amount of logging is just crazy :)

**Comment by azz** [comment]
![image](https://user-images.githubusercontent.com/1297597/29458453-917c372c-8462-11e7-9f10-5f3560bb1179.png)

**Comment by vjeux** [comment]
Closing this as it's now inactive.
