### ISSUE TITLE
Cannot format json-like files such as .editorconfig, .eslintrc

### ISSUE THREAD

**Issue by Jonathan0wh** [prettier/prettier#2622]
Files like .editorconfig, .eslintrc, eslintrc.json (mainly some kinds of config files) have a similar format as json, but they do not follow the strict json rule. For example, these files allow comment.
Therefore, if I want to format a .eslintrc file which contains some line comment like ```// comment```, the formatter would report ```(json-to-ast) Cannot tokenize symbol </>``` error.

Is it possible to allow comment in such kind of files?

**Comment by k15a** [comment]
It's already fixed at master AFAIK.

**Comment by josephfrazier** [comment]
Yes, this is a duplicate of https://github.com/prettier/prettier/issues/2394
