### ISSUE TITLE
[styled-components] Automatically add semicolon for template string interpolation

### ISSUE THREAD

**Issue by viankakrisna** [prettier/prettier#2623]
Maybe a duplicate of https://github.com/prettier/prettier/issues/2402, but can we add a semi colon if the interpolation is in the middle of rule list? so the next rule not dangling at the end of the interpolation

[Demo](https://prettier.io/playground/#%7B%22content%22%3A%22const%20A%20%3D%20styled.a%60%5Cn%20%20display%3A%20inline-block%3B%5Cn%20%20color%3A%20%23fff%3B%20%20%5Cn%20%20%24%7Bprops%20%3D%3E%20props.a%20%26%26css%60%5Cn%20%20%20%20display%3A%20none%3B%5Cn%20%20%60%7D%5Cn%20%20%20height%3A%2030px%3B%5Cn%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by azz** [comment]
I don't know if it is safe to do this in the general case.

e.g. what if you wanted to do:

```js
css`
  ${props => props.lightTheme ? "color" : "background"}: black;
`
```

**Comment by viankakrisna** [comment]
I agree, there are a lot of ways that this could change the meaning of the code. Any way to preserve the whitespace then? It's blocking us to use prettier :(

**Comment by dgcoffman** [comment]
@viankakrisna you can try an older version of prettier that ignores tagged template literals.

We've been stuck on 1.4.2 for a couple months because of issues with formatting styled-components strings.

1.4.2 works just fine tho!

**Comment by evilebottnawi** [comment]
@viankakrisna [payground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBBTBeTDATwBs4ATAOgEMADAHSk03IEs0AHE6opTVqCQFwAtACMSEMAGsA3I2aRJAJz4BiAGZbZzBZgAkwDsogc0+AHyZjptDUwAyB2DRoGTZi3ZcefKNDh5D1oAXz1MAAs4VgBzCJg+AGYABg4ADyDaEAAaEFMYVnRkUGplEwB3AAVShDRkEGoScp463OoMZA1GtDhcsWVqGTgYAGUOQYEY5BhlAFdekHIpTu6FgR7lGEqBmIBbahWSHtyAKzQ0gCEBodHqXbgAGWFD47zZmA53gCYXhfHlDb1MTUMSkaA5EDGAQwADqrHIMAiyAAHMlcjYejCBhx6o1mkRWiBlHAAI6zVjE7bUPYHJBdI4LHq7Vi-XJoSZkACKswg8FZIBgILhCKRSC+uRm1FYQigMQAwhBdvt6nA0ABWCGzHoAFRBdTpqxCISAA) seems fixed, right?

**Comment by duailibe** [comment]
@evilebottnawi it doesn't, see `} height: 30px` is printed, instead of a newline between those

**Comment by fisker** [comment]
this is fixed
