### ISSUE TITLE
prettier-ignore still doesn't allow an intentional leading semi-colon

### ISSUE THREAD

**Issue by marcins** [prettier/prettier#2625]
I have a file in my codebase where for reasons I need a leading semi-colon, here's a minimal example:

```js
;(function () {
    // ...
})();
```

Prettier strips the leading semi, even with `// prettier-ignore`, it shouldn't.

Input:
```js
// prettier-ignore
;(function () {
    // ...
})();
```

Output:

```js
// prettier-ignore
(function () {
    // ...
})();
```

**Comment by vjeux** [comment]
The issue is that the `;` is not an AST-node and `prettier-ignore` doesn't work there, I'm not sure we can fix this :( If you want, you can put `!` instead of `;` to produce the same effect.

**Comment by vjeux** [comment]
```js
!(function () {
    // ...
})();
```

**Comment by marcins** [comment]
Thanks for the quick response! I figured that was going to be the case. 

Since we're running prettier through eslint (we need `eslintignore` support), I've worked around it for now by using eslint to disable prettier before that line which seems to work OK:

```js
/* eslint-disable prettier/prettier */
;(function(window) {
/* eslint-enable prettier/prettier */
    // ...
})();
```

I don't think using `!` instead will actually do what I want, as in this case it's a script that gets appended to another script that may not having a trailing semi-colon. To use a contrived example `console.log('foo')!(function () { console.log('bar') })();` doesn't parse as valid JS.

**Comment by lydell** [comment]
@marcins You can also configure ESLint not to bother with the semicolons since Prettier has that covered for you :)

**Comment by ryanpcmcquen** [comment]
Sad to see that a leading semi-colon cannot be allowed. This is a deal breaker for me on Prettier.

**Comment by vjeux** [comment]
@ryanpcmcquen could you expand on why it's a deal breaker?

**Comment by ryanpcmcquen** [comment]
@vjeux, this would also work: https://github.com/prettier/prettier/issues/1428
