### ISSUE TITLE
Additional comma is added when using front spread with --prasre flow

### ISSUE THREAD

**Issue by Gozala** [prettier/prettier#2626]
Here is [an example](https://prettier.io/playground/#%7B%22content%22%3A%22var%20%5B...rest%2C%20last%5D%20%3D%20%5B1%2C%202%2C%203%5D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) that causes prettier to misbehave, also inline below for convince:

```js
var [...rest, last] = [1, 2, 3]
``` 

Prettier prints following code back:

```js
var [...rest, , last] = [1, 2, 3];
```
In fact every time prettier runs new `,` is being added :) 

It seems that it's not valid JS but at least flow does not seem to raise issues [with that code](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVA3AhgJzAbQA8BnAGjEIF0wBeAgRnICZyBmSoA). I would expect that prettier either would reject such input as invalid (as it does with babel parser) or produce output without additional commas.

**Comment by k15a** [comment]
Mhh I think this is a bug with Flow so you might raise an issue there. This is clearly invalid JavaScript and shouldn't be parsed IMO. You can only have the `...rest` at the end of a destructured array.

**Comment by azz** [comment]
Yes, flow is giving us `[RestElement, null, Identifier]` for the ArrayPattern's elements.

**Comment by vjeux** [comment]
I just opened an issue on flow, thanks for the report! https://github.com/facebook/flow/issues/4605

**Comment by vjeux** [comment]
@Gozala this is actually not valid javascript and should be a syntax error. Babylon reports it correctly as a syntax error and flow has been fixed 2 days ago to make it so as well.

**Comment by Gozala** [comment]
> @Gozala this is actually not valid javascript and should be a syntax error. Babylon reports it correctly as a syntax error and flow has been fixed 2 days ago to make it so as well.

That's exactly what I said in the last paragraph of the description :) Thanks for following up with flow team, donno why I have not done it myself.
