### ISSUE TITLE
How do I disable a prettier rule on an individual file.

### ISSUE THREAD

**Issue by joswalt** [prettier/prettier#2629]
Is there a way to disable a prettier rule for an individual file? For example the the default printWidth is 80 characters, is there a way to disable this rule or add a custom rule for an individual page?

It would be nice to be able to do something like you can with tslint or eslint.

/* tslint:disable:max-line-length */

**Comment by azz** [comment]
Prettier doesn't have rules, it has options. You can't really turn off an option (though you could set it to a different value, or the default).

I doubt we'll be adding this on a file basis. However, with 1.6 there will be support for `.prettierrc`, in which you can list files to have different options applied.
