### ISSUE TITLE
not stripping unnecessary quotes around keys in flow object types

### ISSUE THREAD

**Issue by montemishkin** [prettier/prettier#2632]
Behavior of stripping unnecessary quotes around object properties is inconsistent between flow type declarations and js object instantiation.

see example here

https://prettier.io/playground/#%7B%22content%22%3A%22type%20Foo%20%3D%20%7B%5Cn%20%20'prop'%3A%20string%2C%5Cn%7D%5Cn%5Cnconst%20foo%3A%20Foo%20%3D%20%7B%5Cn%20%20'prop'%3A%20'asdf'%2C%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

expected output: 
```js
type Foo = {
  prop: string
};

const foo: Foo = {
  prop: "asdf"
};

```

**Comment by vjeux** [comment]
Good catch, this is an easy fix if you (or someone else) is interested.

**Comment by azz** [comment]
Same goes for `interface` in TS and Flow.

**Comment by jackyho112** [comment]
I will give this a go this weekend. Hopefully, it won't be as difficult as https://github.com/prettier/prettier/issues/2483.
