### ISSUE TITLE
Option Request: Keep JSON style of object formatting – don’t strip quotes

### ISSUE THREAD

**Issue by RoHePu** [prettier/prettier#2634]
Hi Prettier Team,

Thanks for your incredible work. This is the best formatter I have seen for the JS world. We would love to use Prettier as formatter in our big web projects. Unfortunately, our developers hate that Prettier strips the quotes of objects in keys. They are used the JSON style of objects. 

Could you please insert an option `keepJsonLikeObjects` or something like this in one of the next releases that allows us to keep the JSON like object formatting? If you give me a short introduction where to start I can try to implement the feature on my own.

Current output: 
```javascript
const foo = {
  bar: 1,
  "bar bar": 2
};
```

Expected output with flag:
```javascript
const foo = {
  "bar": 1,
  "bar bar": 2
}
```
Thanks & Best
Robin

**Comment by hawkrives** [comment]
You will be interested in https://github.com/prettier/prettier/pull/90, https://github.com/prettier/prettier/issues/79, https://github.com/prettier/prettier/issues/838, and especially https://github.com/prettier/prettier/issues/1103.

**Comment by lydell** [comment]
Thanks your issue! As @hawkrives points out, this has already been discussed several times. Since it doesn't look like this is happening, I'm closing this one. Sorry!
