### ISSUE TITLE
Failing to recognize expression statements without semicolons

### ISSUE THREAD

**Issue by ephetic** [prettier/prettier#2635]
Input:
```javascript
const {things, thangs} = thingmaker()

[things, thangs].forEach(it => {})

[thangs, things].forEach(it => {})
```

Produces:
```javascript
const { things, thangs } = thingmaker()[(things, thangs)]
  .forEach(it => {})
  [(thangs, things)].forEach(it => {});
```

1.5.3 in [playground](https://prettier.io/playground/#%7B%22content%22%3A%22const%20%7Bthings%2C%20thangs%7D%20%3D%20thingmaker()%5Cn%5Cn%5Bthings%2C%20thangs%5D.forEach(it%20%3D%3E%20%7B%7D)%5Cn%5Cn%5Bthangs%2C%20things%5D.forEach(it%20%3D%3E%20%7B%7D)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) (regardless of `--no-semi`)

Undesirable work arounds to get it to parse correctly: 
- manually add semicolons between expressions/statements (leadign or trailing produces equivalent code)
- wrap `[].forEach` in code blocks `{[].forEach}` (after which it inserts superfluous leading semis)

**Comment by vjeux** [comment]
Unfortunately, the behavior you describe is how JavaScript sees your code, so prettier makes it obvious by reformating the code.

**Comment by ephetic** [comment]
Interesting. Prettier-miscellaneous does the desireable.
