### ISSUE TITLE
[styled-components] adding extra semi at the end

### ISSUE THREAD

**Issue by dlebedynskyi** [prettier/prettier#2636]
[Demo](https://prettier.io/playground/#%7B%22content%22%3A%22export%20const%20ButtonWrapper%20%3D%20styled.button%60%5Cn%20%20%24%7Bbase%7D%5Cn%20%20%24%7Bhover%7D%5Cn%20%20%24%7Bopaque%7D%5Cn%20%20%24%7Bblock%7D%5Cn%20%20%24%7Bactive%7D%5Cn%20%20%24%7Bdisabled%7D%5Cn%20%20%24%7Boutline%7D%5Cn%20%20%24%7Bdashed%7D%5Cn%20%20%24%7Bspacing%7D%5Cn%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Source** 
```
export const ButtonWrapper = styled.button`
  ${base}
  ${hover}
  ${opaque}
  ${block}
  ${active}
  ${disabled}
  ${outline}
  ${dashed}
  ${spacing}
`;
```

**Expected** 
```
export const ButtonWrapper = styled.button`
  ${base}
  ${hover}
  ${opaque}
  ${block}
  ${active}
  ${disabled}
  ${outline}
  ${dashed}
  ${spacing}
`;
```
or 
```
export const ButtonWrapper = styled.button`
  ${base} ${hover} ${opaque} ${block} ${active} ${disabled} ${outline} ${dashed} ${spacing}
`;
```

**Problem**
extra ; added to end of line after ${spacing}
```
export const ButtonWrapper = styled.button`
  ${base} ${hover} ${opaque} ${block} ${active} ${disabled} ${outline} ${dashed} ${spacing};
`;

```

**Comment by danhoran** [comment]
Could anyone point me in the direction of a workaround for this?

**Comment by suchipi** [comment]
A `// prettier-ignore` comment should work as a workaround

**Comment by stevemao** [comment]
There are quite a few interpolation problems similar to this. Do you guys consider reading tags just like how stylelint-processor-styled-components does it?

```
sc-block
sc-selector
sc-declaration
sc-property
sc-value
```

**Comment by evilebottnawi** [comment]
`stylelint-processor-styled-components` is deprecated `stylelint` support `styled` components out of box using `postcss-jsx`m we should rewrite parser/print on `postcss-jsx` to avoid problems with output `styled` components

**Comment by stevemao** [comment]
> `stylelint-processor-styled-components` is deprecated

Didn't know that. It looks quite active to me...

I'm just throwing away an idea since nobody mentioned tags yet. But if there's a better solution it'd be really good :)

**Comment by fisker** [comment]
1.18.2 new ERROR


**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOgCMBXGGaAAwB0oACWgEmEIENU4BfG+pgCwgBucAE5c6jYBAAOLAI7FO3CYSwQwAazE9gLMDACWQrRNz7ULFXmNMIpLPqiLxTXG15WlTVDLAOA5mIUANwgADQg0gbQqMigLMLCEADuAArxCDEoLAIQ+rhhIITCuupwMADKPv7IMMIK4bwwALZYAOq8+vDeunDlGZ2GnRjI4Kgx4Q7swjApxX5NLMgAZixY7OEAVqgAHgBCxRpl5SxNcAAyDnDLq+sgW9vl-jgAisQQ8NdrcOEywlMjrEI2GgBSkwgcMFaeRgvGQAA4AAw-RLsVrFKQjMFwKZCAryd5wWbSTIgNgAWkceDwBWEcHk+lpsxY80WSBWX3C7Ca+hqdW+aCecFeBM+txgFihuBhyAATOFaix9PYoH4AMIQJoLEZQaBXcLEdgAFQsmXZt1walF-LYMCtHA4QA)
```sh
--parser babylon
```

**Input:**
```jsx
styled.button`
  ${base}
  ${hover}
  ${opaque}
  ${block}
  ${active}
  ${disabled}
  ${outline}
  ${dashed}
  ${spacing}
`;
```

**Output:**
```jsx
Error: Couldn't insert all the expressions
    at transformCssDoc (https://prettier.io/lib/standalone.js:22212:11)
    at Object.embed$4 [as embed] (https://prettier.io/lib/standalone.js:22050:18)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15816:31)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15934:29)
    at https://prettier.io/lib/standalone.js:15899:16
    at Object.printComments (https://prettier.io/lib/standalone.js:15621:17)
    at printGenerically (https://prettier.io/lib/standalone.js:15898:22)
    at FastPath.call (https://prettier.io/lib/standalone.js:15735:16)
    at printPathNoParens (https://prettier.io/lib/standalone.js:25282:91)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:23704:28)
```
