### ISSUE TITLE
Missing .pre-commit-hooks.yaml file?

### ISSUE THREAD

**Issue by sam-untapt** [prettier/prettier#2637]
I can see .pre-commit-hooks.yaml in master but not in any tags. I've configured pre-commit to use prettier 1.5.0 in .pre-commit-config.yaml and it works great, but I have to create .pre-commit-hooks.yaml in ~/.pre-commit/repoXXX manually.

Am I doing something wrong?

**Comment by azz** [comment]
I don't think it has been released yet. For now you'll have to create your own `.pre-commit-config.yaml` file.
