### ISSUE TITLE
<pre /> tag inner content is wrapped

### ISSUE THREAD

**Issue by brikou** [prettier/prettier#2639]
1st thank for what you've done with prettier.

Here is playground url: 

https://prettier.io/playground/#%7B%22content%22%3A%22()%20%3D%3E%20%3Cpre%3E%5CnText%20in%20a%20pre%20element%5Cnis%20displayed%20in%20a%20fixed-width%5Cnfont%2C%20and%20it%20preserves%5Cnboth%20%20%20%20%20%20spaces%20and%5Cnline%20breaks%5Cn%3C%2Fpre%3E%5Cn%5Cn%2F%2F%20formatting%20should%20be%20kept%20as%20is%20within%20pre%20tag%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by azz** [comment]
Should we be treating `<pre>` contents the same as template literals?

**Comment by vjeux** [comment]
JSX doesn't preserve any of those, you need to do ``{`...`}`` to preserve them which prettier support.

http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=BQSgBAvAfGA8AOAnAplAUAFWQDwC5gEsA7MAQzCWTGQBtkBbZI3NAgZzABN34bSBPZJ0IlyAMwLYhAWgDuBTrgAWaMQHtmAGjJFhBfJTbJEAN2Rs0AIzXKwd-23ikAxuZ2c0NYlUspSAawtYAHpKKCA

**Comment by azz** [comment]
Hah. Didn't know that.

**Comment by jashmenn** [comment]
(Future reference for anyone stumbling upon this)

What vjeux is saying is that to maintain `pre` tag formatting your JSX needs to use backticks as a string in the JSX like this:

```
() => <pre>
  {`Text in a pre element
is displayed in a fixed-width
font, and it preserves
both      spaces and
line breaks`}
</pre>
```

**Comment by j-f1** [comment]
It looks like multiple spaces [are preserved](http://babeljs.io/repl/#?code_lz=DwEwlgbgfAzg9gWwKYAI0oC5IB4eAenGgCgg&presets=react&version=6.26.0) in JSX (at least by Babel), but line breaks aren’t.

**Comment by duailibe** [comment]
Babylon, Flow and TypeScript include the whitespaces in the AST.

**Comment by vjeux** [comment]
The ast doesn't matter much here, correctness is about how JSX is transformed to createElement calls btw.
