### ISSUE TITLE
New flow react component definitions

### ISSUE THREAD

**Issue by carlitux** [prettier/prettier#2642]
Flow released new type to use with React 16, here is the post about it https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627.

Now fixing in this way:

```js
export default class SearchList extends React.Component<Props> {
  props: Props; // Adding this line to pass prettier errors.
}
```

**Comment by lydell** [comment]
Hi! I don't understand what the issue is here. Could you post input, actual output and expected output, or something?

**Comment by carlitux** [comment]
@lydell sorry for noise I put the issue in wrong project, it is related with eslint and prettier integration.

**Comment by lydell** [comment]
Thanks! Pro-tip for the future: It's possible to close your own issues :)
