### ISSUE TITLE
import member aliasing breaks print width [es6, ts]

### ISSUE THREAD

**Issue by Fahrradflucht** [prettier/prettier#2645]
Import member aliasing will be formatted in a way that exceeds the maximum print width even though there would be a way to adhere to the rule.

## Input
```es6
import { myFunctionWithALongName as myFunctionWithALongNameThatExceedsTheMaxLength } from '../../../../function-with-long-name';

import {
  myFunctionWithALongName as myFunctionWithALongNameThatExceedsTheMaxLength
} from '../../../../function-with-long-name';
```

## Output
```es6
import { myFunctionWithALongName as myFunctionWithALongNameThatExceedsTheMaxLength } from '../../../../function-with-long-name';

import { myFunctionWithALongName as myFunctionWithALongNameThatExceedsTheMaxLength } from '../../../../function-with-long-name';
```

## Expected
```es6
import {
  myFunctionWithALongName as myFunctionWithALongNameThatExceedsTheMaxLength
} from '../../../../function-with-long-name';

import {
  myFunctionWithALongName as myFunctionWithALongNameThatExceedsTheMaxLength
} from '../../../../function-with-long-name';
```

---

[Playground](https://prettier.io/playground/#%7B%22content%22%3A%22import%20%7B%5Cn%20%20myFunctionWithALongName%20as%20myFunctionWithALongNameThatExceedsTheMaxLength%5Cn%7D%20from%20'..%2F..%2F..%2F..%2Ffunction-with-long-name'%3B%5Cn%5Cnimport%20%7B%20myFunctionWithALongName%20as%20myFunctionWithALongNameThatExceedsTheMaxLength%20%7D%20from%20'..%2F..%2F..%2F..%2Ffunction-with-long-name'%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by lydell** [comment]
Hi! Thanks for the issue! Actually, this is intended behavior.

https://github.com/prettier/prettier/issues/1954#issuecomment-306067705

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.
