### ISSUE TITLE
Ugly formatting of if statement comments

### ISSUE THREAD

**Issue by phiresky** [prettier/prettier#2650]
The following code:

```js
if (typeof err === "string") //USER_DOES_NOT_EXIST
    callback(err);
```

becomes

```js
if (
    typeof err === "string" //USER_DOES_NOT_EXIST
   )
    callback(err);
```

Which looks pretty ugly.

The comment is moved into the if clause. I don't think it should be moved into the if clause. Maybe if the condition is longer / has multiple parts, but in this case this transformation looks pretty weird.

Prettier 1.5.3, Typescript parser.

**Comment by vjeux** [comment]
Yeah, this is a bug, we should print
```js
if (typeof err === "string")
    //USER_DOES_NOT_EXIST
    callback(err);
```

instead

**Comment by jackyho112** [comment]
I will give this one a go!
