### ISSUE TITLE
Feature request - bracket spacing inside JSX

### ISSUE THREAD

**Issue by AdamYahid** [prettier/prettier#2651]
Hi,
I just set up prettier and it's amazing, thanks for the work!

I noticed that bracket spacing only works on object literals.
Is it possible to add bracket spacing inside JSX as well? right now this
`<div>{ foo }</div>` would result in `<div>{foo}</div>`

Thanks

**Comment by lydell** [comment]
Turns out this has been discussed before and rejected:

- #989
- #1097
- #1584
- #1871

But I think we could just as well keep this open and let people :+1: it. Now there's also a similar request for Angular: #5478

**Comment by lipis** [comment]
We are closing this as we are not adding any more options due to the latest [option philosophy](https://prettier.io/docs/en/option-philosophy.html).
