### ISSUE TITLE
Trailing comma doesn't work on single-line objects and arrays

### ISSUE THREAD

**Issue by bdukes** [prettier/prettier#2655]
With the `trailing-comma` option set to `es5` or `all`, objects or arrays that are one a single line do not have a trailing comma.

For example: `var a = { b: 1, };` is rewritten as `var a = { b: 1 };`, whereas a trailing comma is correctly added to 
```
var a = { 
  b: 1
};
```

The same issue happens for arrays, so that a short array does not have a trailing comma and an array that splits into multiple lines does.

[Repro on Prettier Playground](https://goo.gl/wVNXdK)

**Comment by lydell** [comment]
Hi! Thanks for the issue! Actually, the `trailing-comma` options is intended to work this way – trailing commas are only added for multi-line stuff.
