### ISSUE TITLE
Request: Ignore Jest snapshots by default

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier#2656]
Jest can automatically generate test snapshots in `__snapshots__` directories. However if prettier is configured a certain way (for example disabling semicolons) the syntax will switch back and forth depending on which tool was run last. It would be nice to have these ignored by default to reduce confusion and churn if possible.

**Comment by vjeux** [comment]
Snapshot tests are named .js.snap, so they shouldn't be picked up by default in the first place. Can you tell us more at how you are setup in a way that they do?

**Comment by nickmccurdy** [comment]
Ah I didn't think about that, I'm currently passing files from `git ls-files` which is why they showed up. I assume I should filter by extension.
