### ISSUE TITLE
Feature: `@prettier-config` - Ability to change prettier config per file

### ISSUE THREAD

**Issue by moshest** [prettier/prettier#2658]
On our project we have some files that use `babel` and some that aren't.

It would be nice if we could set all files to `{ trailingComma: 'all' }` but change it explicitly for the non-babel files like:

```js
/**
 * @prettier-config --trailing-comma es5
 */

**Comment by lydell** [comment]
Just noting here that this is possible by running Prettier inside ESLint using [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier).

**Comment by moshest** [comment]
How exactly?

**Comment by lydell** [comment]
Like any other ESLint rule: https://eslint.org/docs/user-guide/configuring

**Comment by moshest** [comment]
Oh! you right. I probably missed it.

I solve it using:

```js
/* eslint prettier/prettier: ["error", { trailingComma: "es6" }] */
```
