### ISSUE TITLE
Prettier with semis disabled doesn't prevent human error.

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#2662]
For example, paste this error into eslint's demo box:

```js
var bar = 'string'
var foo = bar

(function() {
  var foo = 'blah'
  console.log(foo) // eslint-disable-line no-console
})()

console.log(foo) // eslint-disable-line no-console
```

And you will see it throw an error that is useful in preventing `bar` from being called like a function.

However, prettier enforces this human error. Run the [same code through prettier](https://prettier.io/playground/#%7B%22content%22%3A%22var%20bar%20%3D%20'string'%5Cnvar%20foo%20%3D%20bar%5Cn%5Cn(function()%20%7B%5Cn%20%20var%20foo%20%3D%20'blah'%5Cn%20%20console.log(foo)%20%2F%2F%20eslint-disable-line%20no-console%5Cn%7D)()%5Cn%5Cnconsole.log(foo)%20%2F%2F%20eslint-disable-line%20no-console%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) and you will see that prettier will move right along with that error.

I strongly believe prettier should either throw an error or format this code in another way.

With semis enabled, the output would be like

```js
var bar = "string";
var foo = bar;

(function() {
  var foo = "blah";
  console.log(foo); // eslint-disable-line no-console
})();

console.log(foo); // eslint-disable-line no-console
```

and without semis it would be like

```js
var bar = "string"
var foo = bar

;(function() {
  var foo = "blah"
  console.log(foo) // eslint-disable-line no-console
})()

console.log(foo) // eslint-disable-line no-console
```

and therefore no human error. Most people will never write code in that way and intend for the previous line to have been called as a function.

---

Now, I know prettier intends to only format code without changing it's meaning.

What do you recommend then?

**Comment by vjeux** [comment]
In the example you made, prettier will put the parenthesis right after `bar`:

```js
var bar = 'string'
var foo = bar(function() { // <---------------------------------------------
  var foo = 'blah'
  console.log(foo) // eslint-disable-line no-console
})()

console.log(foo) // eslint-disable-line no-console
```

If you see this while working or during code review, you're likely going to figure out that something is wrong and probably put a `;` to fix it. I believe that prettier will actually help here.

**Comment by trusktr** [comment]
That is exactly what my co-worker and I thought. But it could fail with
more complicated examples, and f.e. a reviewer not completely familiar with
everything yet.

Oh well, we just will avoid writing code like that

**Comment by vjeux** [comment]
What I recommend is to use semi-colons so you don't have this problem in the first place :)

**Comment by trusktr** [comment]
Prettier can add those. ESLint has a rule that can throw an error with code
like this. But prettier fixes the formatting so running eslint after
prettier doesn't detect this error anymore.

*/#!/*JoePea

**Comment by lydell** [comment]
@trusktr Prettier follows the JavaScript specification. It says that

```js
var foo = bar
(function() {
  console.log(foo)
})()
```

means the same as

```js
var foo = bar(function() {
  console.log(foo)
})()
```

even though that's confusing to humans. Prettier follows this standard specification by parsing and printing the code this way. It does not treat your code as an arbitrary superset of JavaScript with different semantics. One rule we have is that running any piece of JavaScript through Prettier should never change its meaning. If we did add a semicolon in your example, that promise would be broken.

Also see #1143.

**Comment by trusktr** [comment]
I totally understand. The downside is that after prettier reformats xode, eslint can no longer throw on that formatting. I could run eslint both before and after prettier, with a different config for the first round to catch the possible-error formats, but that increases the time it takes.
