### ISSUE TITLE
Useful but unnecessary parens removed over-eagerly in arithmetic

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [prettier/prettier#2666]
I was surprised to find prettier (1.5.3) strips parens from some moderately complex arithmetic expressions.

Unformatted:

```javascript
const y = fret > 0
  ? (fretSpacing * (fret - lowFret)) - (fretSpacing / 2)
  : (-fretSpacing / 4)
```
With prettier:
```javascript
const y =
  fret > 0
    ? fretSpacing * (fret - lowFret) - fretSpacing / 2
    : -fretSpacing / 4;
```

The code afterward is still semantically the same (and that last set of parens can probably safely be dropped), but I found it surprising that all the other not-strictly-necessary parens were also dropped here.

Thoughts?

**Comment by lydell** [comment]
Thanks for your issue! This has already been discussed in #187. Check it out!

(Also, IMO, the code after Prettier above is more readable to me.)

**Comment by uhoh-itsmaciek** [comment]
Thanks, I looked for open issues but missed that one.
