### ISSUE TITLE
[Less] Rulesets invoked as mixin argument is not properly format

### ISSUE THREAD

**Issue by chbdetta** [prettier/prettier#2667]
```less
.somemixin(@rules) {
  @rules();
}
```
will be formatted to
```less
.somemixin(@rules) {
  @rules ();
}
```
It won't be compiled by `less` compiler and result in `@rules ()` in css.

**Comment by ashsearle** [comment]
This looks fixed (see in [prettier playground](https://prettier.io/playground/#%7B%22content%22%3A%22.somemixin(%40rules)%20%7B%5Cn%20%20%40rules()%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22less%22%2C%22printWidth%22%3A120%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D))

**Comment by azz** [comment]
It does indeed. Thanks!

@lydell any idea when this was fixed?

**Comment by lydell** [comment]
I have no idea.
