### ISSUE TITLE
Improve / add heuristic for JSX components properties aligning (when the same comp is in the same parent)

### ISSUE THREAD

**Issue by Skywalker13** [prettier/prettier#2668]
Hello,
I've just a suggestion of improvements with this sample:

```jsx
  function renderConnectForm () {
    const id = this.props.id;
    const Form = this.Form;
    return (
      <Container kind="views">
        <Container kind="view" width="800px">
          <Container kind="pane-header">
            <Label text="Chat-client" kind="pane-header" />
          </Container>
          <Container kind="panes">
            <Form {...this.formConfig}>
              <LabelTextField model=".bus.host" labelText="Hostname" />
              <LabelTextField model=".bus.commanderPort" labelText="Commander port" />
              <LabelTextField model=".bus.notifierPort" labelText="Notifier port" />
              <LabelTextField model=".user.name" labelText="Nick name" />
              <Button text="Se Connecter" onClick={this.onSubmit} />
            </Form>
          </Container>
        </Container>
      </Container>
    );
  }
```

The result with prettier 1.5.3 is (a bit ugly):
```jsx
function renderConnectForm() {
  const id = this.props.id;
  const Form = this.Form;
  return (
    <Container kind="views">
      <Container kind="view" width="800px">
        <Container kind="pane-header">
          <Label text="Chat-client" kind="pane-header" />
        </Container>
        <Container kind="panes">
          <Form {...this.formConfig}>
            <LabelTextField model=".bus.host" labelText="Hostname" />
            <LabelTextField
              model=".bus.commanderPort"
              labelText="Commander port"
            />
            <LabelTextField
              model=".bus.notifierPort"
              labelText="Notifier port"
            />
            <LabelTextField model=".user.name" labelText="Nick name" />
            <Button text="Se Connecter" onClick={this.onSubmit} />
          </Form>
        </Container>
      </Container>
    </Container>
  );
}
```

But some heuristics should be able to produce something really pretty by seeing that the same component `<LabelTextField />` is in the same parent then align the properties always with the same way (even if the line is not longer than 80):

Expected result:
```jsx
function renderConnectForm() {
  const id = this.props.id;
  const Form = this.Form;
  return (
    <Container kind="views">
      <Container kind="view" width="800px">
        <Container kind="pane-header">
          <Label text="Chat-client" kind="pane-header" />
        </Container>
        <Container kind="panes">
          <Form {...this.formConfig}>
            <LabelTextField
              model=".bus.host"
              labelText="Hostname"
            />
            <LabelTextField
              model=".bus.commanderPort"
              labelText="Commander port"
            />
            <LabelTextField
              model=".bus.notifierPort"
              labelText="Notifier port"
            />
            <LabelTextField
              model=".user.name"
              labelText="Nick name"
            />
            <Button text="Se Connecter" onClick={this.onSubmit} />
          </Form>
        </Container>
      </Container>
    </Container>
  );
}
```

https://prettier.io/playground/#%7B%22content%22%3A%22%20%20function%20renderConnectForm%20()%20%7B%5Cn%20%20%20%20const%20id%20%3D%20this.props.id%3B%5Cn%20%20%20%20const%20Form%20%3D%20this.Form%3B%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%3CContainer%20kind%3D%5C%22views%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%3CContainer%20kind%3D%5C%22view%5C%22%20width%3D%5C%22800px%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3CContainer%20kind%3D%5C%22pane-header%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3CLabel%20text%3D%5C%22Chat-client%5C%22%20kind%3D%5C%22pane-header%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2FContainer%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3CContainer%20kind%3D%5C%22panes%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3CForm%20%7B...this.formConfig%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CLabelTextField%20model%3D%5C%22.bus.host%5C%22%20labelText%3D%5C%22Hostname%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CLabelTextField%20model%3D%5C%22.bus.commanderPort%5C%22%20labelText%3D%5C%22Commander%20port%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CLabelTextField%20model%3D%5C%22.bus.notifierPort%5C%22%20labelText%3D%5C%22Notifier%20port%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CLabelTextField%20model%3D%5C%22.user.name%5C%22%20labelText%3D%5C%22Nick%20name%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20text%3D%5C%22Se%20Connecter%5C%22%20onClick%3D%7Bthis.onSubmit%7D%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FForm%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2FContainer%3E%5Cn%20%20%20%20%20%20%20%20%3C%2FContainer%3E%5Cn%20%20%20%20%20%20%3C%2FContainer%3E%5Cn%20%20%20%20)%3B%5Cn%20%20%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by lydell** [comment]
So, in my opinion, this is not specific to JSX. The same could be said about a series of function calls, object literals or items of an array. I'm pretty sure that has been discussed somewhere before, but I can't find it right now. As far as I remember, the arguments against this was:

- Changing one line somewhere can cause other blocks of code to be reformatted, causing unnecessary diff and a higher risk of merge conflicts.
- This has some pretty high complexity to it computing wise, which will hurt the performance of running Prettier (which lots of people do on save in their editor and expect to be instant).

**Comment by Skywalker13** [comment]
> Changing one line somewhere can cause other blocks of code to be reformatted, causing unnecessary diff and a higher risk of merge conflicts.

Sorry, it looks like a bad argument. The focus of prettier is formatting, not considering possible merge conflicts. It's the problem of the merge algorithm that are too much generic (without knowledge of languages) and it should be debated in the git mailinglist.

**Comment by lydell** [comment]
The diffing argument has been used several times in many discussions, so it is not something I made up just now :) I agree we you in theory that it is a problem of diff/merge tools, but I also think that until better such tools exist it is smart to avoid unnecessary diffs.

Either way, consider my comment mostly as an attempt to remind people who follow this issue tracker of previous discussions (although I failed to find them – perhaps someone else can...)

**Comment by vjeux** [comment]
This is indeed something that would be nice, it happens quite often that you have multiple patterns that should ideally be formatted the same way. The issue is how to find those kind of patterns in an efficient and predictable way. I've tried and ideated a few possibilities but couldn't find any that would actually work in practice.

One thing to remember is that we're never going to have a perfect pretty printer, I feel like the current way prettier prints things is good enough that it's worth putting aside the few edge cases like this one where it doesn't print ideal output compared to all the advantages it gives you :)

**Comment by Skywalker13** [comment]
@vjeux: you can take the problem by an other way.

Something great will be to do exactly like with the JS objects (and user linefeed).

![image](https://user-images.githubusercontent.com/397862/29725325-f74065c4-89cb-11e7-8023-c5fe7dfb3e09.png)
https://prettier.io/playground/#%7B%22content%22%3A%22const%20foo%20%3D%20%7B%5Cn%20%20bar%3A%20%7Ba%3A1%2Cb%3A2%7D%5Cn%7D%5Cn%5Cnconst%20foo%20%3D%20%7B%5Cn%20%20bar%3A%20%7Ba%5Cn%20%20%20%20%20%20%20%20%3A1%2Cb%3A2%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

Doing that with JSX (and other...) will be great and enough for most people I think. Prettier should not oneline the JSX tag just because it can be write on one line (that's too simple). Exactly like the JS object in my example.

IMHO, you close this issue too quickly.

**Comment by vjeux** [comment]
The reason why we keep the objects expanded is because objects in JavaScript can mean different things: classes, hashmaps, configuration, named arguments, returning a tuple... We want to be able to print those use cases in different ways but unfortunately we haven't found a good way to automatically figure out which is which based on the AST.

ES6, Flow and TypeScript have been awesome for prettier because it added a bunch of syntax to differentiate those different use cases.

The decision to keep the newlines around in objects has not been taken lightly because it chips away the value of not having to care about how you format your code. This is an exception and has caused a bunch of confusion already.

JSX doesn't have this wide range of use cases so we don't want to apply the same technique.

**Comment by Skywalker13** [comment]
ok :-( thanks for the explanations
