### ISSUE TITLE
join in template literal split over multiple lines

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#2671]
I really don't find this more readable.

```js
const didYouMean = (scmd, commands) => {
    const bestSimilarity = meant(scmd, commands);

    if (bestSimilarity.length > 0) {
        throw new ReferenceError(`[envalid] Environment var ${scmd} not found, did you mean ${bestSimilarity.join(', ')}?`);
    }
};
```
Is turned into

```js
const didYouMean = (scmd, commands) => {
    const bestSimilarity = meant(scmd, commands);

    if (bestSimilarity.length > 0) {
        throw new ReferenceError(
            `[envalid] Environment var ${scmd} not found, did you mean ${bestSimilarity.join(
                ", "
            )}?`
        );
    }
};
```

The part with moving the string into its own line is perfect, but splitting the `join` looks really weird, IMO. I think it should be:

```js
const didYouMean = (scmd, commands) => {
    const bestSimilarity = meant(scmd, commands);

    if (bestSimilarity.length > 0) {
        throw new ReferenceError(
            `[envalid] Environment var ${scmd} not found, did you mean ${bestSimilarity.join(", ")}?`
        );
    }
};
```

https://prettier.io/playground/#%7B%22content%22%3A%22const%20didYouMean%20%3D%20(scmd%2C%20commands)%20%3D%3E%20%7B%5Cn%20%20%20%20const%20bestSimilarity%20%3D%20meant(scmd%2C%20commands)%3B%5Cn%5Cn%20%20%20%20if%20(bestSimilarity.length%20%3E%200)%20%7B%5Cn%20%20%20%20%20%20%20%20throw%20new%20ReferenceError(%60%5Benvalid%5D%20Environment%20var%20%24%7Bscmd%7D%20not%20found%2C%20did%20you%20mean%20%24%7BbestSimilarity.join('%2C%20')%7D%3F%60)%3B%5Cn%20%20%20%20%7D%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A100%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by Skywalker13** [comment]
Duplicate of #1893

**Comment by SimenB** [comment]
True story
