### ISSUE TITLE
Flow typed JSX syntax regression in v1.6.0

### ISSUE THREAD

**Issue by etrepum** [prettier/prettier#2678]
Repro: 

https://prettier.io/playground/#%7B%22content%22%3A%22let%20child%3A%20Element%3Cany%3E%20%3D%20%3Cimg%20src%3D%7Burl%7D%20key%3D%5C%22img%5C%22%20%2F%3E%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

Input:

```javascript
let child: Element<any> = <img src={url} key="img" />;
```

Error message:

```
SyntaxError: Unexpected token, expected , (1:32)
> 1 | let child: Element<any> = <img src={url} key="img" />;
    |                                ^
```

If you add parentheses around the expression it will parse, but the output will not include the parentheses so the output is not parseable. A workaround that is idempotent with respect to prettier is to use an inline annotation.

```javascript
let child = (<img src={url} key="img" />: Element<any>);
```

**Comment by existentialism** [comment]
@etrepum thanks for the report, will look into this!

**Comment by existentialism** [comment]
@etrepum fixed in https://github.com/babel/babylon/pull/702, will update prettier once we release a new version!

**Comment by vjeux** [comment]
I just shipped 1.6.1 that contains this fix! Thanks for reporting it!

**Comment by etrepum** [comment]
Thanks! Confirmed that it works for us. We had another (real) syntax error to fix after this one, but that was on us :)

FWIW it looked something like this:

```javascript
const f = ({ ...childProps, Component = TextField }) =>
  <Component {...childProps} />;
```

For some reason babel/flow/eslint and previous versions of prettier didn't seem to care about the rest argument not being last before.

**Comment by existentialism** [comment]
@etrepum yeah I fixed that bug recently too, thanks again for the bug report!
