### ISSUE TITLE
Misses closing parenthesis

### ISSUE THREAD

**Issue by Geczy** [prettier/prettier#2679]
# Before
```js
{enableCouponStats &&
                    <td>
                      <NumberFormat
                      value={
                          stats[coupon.id] ? stats[coupon.id].total_sent : 0
                        }
                      displayType={'text'}
                      />
                    </td>}
```

# After
```js
{enableCouponStats && (
                <td>
                    <NumberFormat
                        value={
                          stats[coupon.id] ? stats[coupon.id].total_used : 0
                        }
                        displayType={'text'}
                      />
                    </td>}
```

It formatted to that, but it missed the closing parenthesis

**Comment by vjeux** [comment]
Hey, I cannot reproduce this, can you tell me what you did to get to that result?

**Comment by Geczy** [comment]
1. IntelliJ IDEA 2017.2.3
1. Right clicked my directory
1. Clicked Fix ESLint Problems

**Comment by Geczy** [comment]
```js
import React from 'react'
import PropTypes from 'prop-types'
import {
  DropdownItem,
  DropdownMenu,
  DropdownToggle,
  Table,
  UncontrolledDropdown,
  Badge,
} from 'reactstrap'
import styled from 'emotion/react'
import { Link, ErrorMessage, EmptyState, Loader } from 'components'
import NumberFormat from 'react-number-format'
import { toastr } from 'react-redux-toastr'

const Th = styled.th`
  opacity: 0.5;
  color: #2e3640;
  font-size: 14px;
  font-weight: bold;
  line-height: 20px;
  border-bottom: none;
  border-top: none !important;
`

const Tr = styled.tr`
  &:hover {
    background-color: #e0f0fd !important;
  }
`

const I = styled.i`font-size: 21px;`

const CouponSnippetList = ({
  enableCouponStats,
  activateCoupon,
  deactivateCoupon,
  list,
  stats,
  loading,
  failed,
}) => {
  return (
    <div>
      {loading && <Loader />}
      {failed && <ErrorMessage />}
      {!loading &&
        !failed &&
        list &&
        !list.length &&
        <EmptyState
          title="You have no snippets"
          buttonText="Create snippet"
          to="/snippets/create"
          icon="money"
        />}
      {list && list.length && !failed && !loading
        ? <Table hover size="lg">
          <thead>
            <tr>
              <Th>Name</Th>
              <Th>Status</Th>
              {enableCouponStats && <Th>Total Sent</Th>}
              {enableCouponStats && <Th>Total Used</Th>}
            </tr>
          </thead>
          <tbody>
            {list.map(coupon =>
              <Tr key={coupon.id}>
                <td>
                  <Link to={`/snippets/${coupon.id}`} exact>
                    {coupon.name
                      ? coupon.name
                      : <span className="font-italic">
                            no name available
                      </span>}
                  </Link>
                </td>
                <td>
                  {(() => {
                    switch (coupon.status) {
                      case 'ACTIVE':
                        return (
                          <Badge color="success">
                            {coupon.status}
                          </Badge>
                        )
                      case 'INACTIVE':
                        return (
                          <Badge color="danger">
                            {coupon.status}
                          </Badge>
                        )
                      default:
                        return (
                          <Badge className="badge-secondary">
                            {coupon.status}
                          </Badge>
                        )
                    }
                  })()}
                </td>
                {enableCouponStats &&
                    <td>
                      <NumberFormat
                      value={
                          stats[coupon.id] ? stats[coupon.id].total_sent : 0
                        }
                      displayType={'text'}
                      />
                    </td>}
                {enableCouponStats &&
                    <td>
                  <NumberFormat
                    value={
                      stats[coupon.id] ? stats[coupon.id].total_used : 0
                    }
                    displayType={'text'}
                  />
                </td>}
                <td>
                  <Link
                    style={{ padding: 0 }}
                    to={`/snippets/${coupon.id}/email/`}
                  />
                </td>
                <td>
                  <UncontrolledDropdown>
                    <DropdownToggle
                      color="default outline"
                      style={{ border: 'none' }}
                    >
                      <I className="fa fa-ellipsis-v" aria-hidden="true" />
                    </DropdownToggle>
                    <DropdownMenu style={{ padding: 0 }} right>
                      {coupon.status === 'ACTIVE' &&
                          <DropdownItem
                        onClick={() => {
                          const toastrConfirmOptions = {
                            onOk: () =>
                              deactivateCoupon(coupon.id).then(() =>
                                toastr.success(
                                  'Deactivated',
                                  'The snippet has been deactivated'
                                )
                              ),
                            onCancel: () => console.log('CANCEL: clicked'),
                          }
                          const message = (
                            <div>
                              <p>
                                    Warning: Since you have deactivated snippet
                                    "{coupon.name}", the coupons normally
                                    generated by this snippet will not be sent
                                    by any emails.
                              </p>
                              <p>
                                    Please modify any email templates that
                                    reference this snippet.
                              </p>
                            </div>
                          )
                          toastr.confirm(message, toastrConfirmOptions)
                        }}
                      >
                        <span style={{ color: 'rgba(254,89,95,1)' }}>
                          <i className="fa fa-trash" /> Deactivate
                        </span>
                      </DropdownItem>}
                      {coupon.status === 'INACTIVE' &&
                          <DropdownItem
                        onClick={() =>
                          activateCoupon(coupon.id).then(() =>
                            toastr.success(
                              'Activated',
                              'The snippet has been activated'
                            )
                          )}
                      >
                        <span className="text-success">
                          <i className="fa fa-check" /> Activate
                        </span>
                      </DropdownItem>}
                    </DropdownMenu>
                  </UncontrolledDropdown>
                </td>
              </Tr>
            )}
          </tbody>
        </Table>
        : null}
    </div>
  )
}

CouponSnippetList.propTypes = {
  list: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string,
      id: PropTypes.string,
      status: PropTypes.oneOf(['ACTIVE', 'INACTIVE']),
      created: PropTypes.string,
      amount: PropTypes.number,
      total_delivered: PropTypes.number,
      total_opens: PropTypes.number,
      total_clicks: PropTypes.number,
    })
  ),
  stats: PropTypes.objectOf(
    PropTypes.shape({
      total_sent: PropTypes.number,
      total_used: PropTypes.number,
    })
  ),
  deactivateCoupon: PropTypes.func.isRequired,
  activateCoupon: PropTypes.func.isRequired,
  loading: PropTypes.bool,
  failed: PropTypes.bool,
}

export default CouponSnippetList
```

**Comment by lydell** [comment]
@Geczy [It works out in the online playground](https://prettier.io/playground/#%7B%22content%22%3A%22import%20React%20from%20%27react%27%5Cnimport%20PropTypes%20from%20%27prop-types%27%5Cnimport%20%7B%5Cn%20%20DropdownItem%2C%5Cn%20%20DropdownMenu%2C%5Cn%20%20DropdownToggle%2C%5Cn%20%20Table%2C%5Cn%20%20UncontrolledDropdown%2C%5Cn%20%20Badge%2C%5Cn%7D%20from%20%27reactstrap%27%5Cnimport%20styled%20from%20%27emotion%2Freact%27%5Cnimport%20%7B%20Link%2C%20ErrorMessage%2C%20EmptyState%2C%20Loader%20%7D%20from%20%27components%27%5Cnimport%20NumberFormat%20from%20%27react-number-format%27%5Cnimport%20%7B%20toastr%20%7D%20from%20%27react-redux-toastr%27%5Cn%5Cnconst%20Th%20%3D%20styled.th%60%5Cn%20%20opacity%3A%200.5%3B%5Cn%20%20color%3A%20%232e3640%3B%5Cn%20%20font-size%3A%2014px%3B%5Cn%20%20font-weight%3A%20bold%3B%5Cn%20%20line-height%3A%2020px%3B%5Cn%20%20border-bottom%3A%20none%3B%5Cn%20%20border-top%3A%20none%20!important%3B%5Cn%60%5Cn%5Cnconst%20Tr%20%3D%20styled.tr%60%5Cn%20%20%26%3Ahover%20%7B%5Cn%20%20%20%20background-color%3A%20%23e0f0fd%20!important%3B%5Cn%20%20%7D%5Cn%60%5Cn%5Cnconst%20I%20%3D%20styled.i%60font-size%3A%2021px%3B%60%5Cn%5Cnconst%20CouponSnippetList%20%3D%20(%7B%5Cn%20%20enableCouponStats%2C%5Cn%20%20activateCoupon%2C%5Cn%20%20deactivateCoupon%2C%5Cn%20%20list%2C%5Cn%20%20stats%2C%5Cn%20%20loading%2C%5Cn%20%20failed%2C%5Cn%7D)%20%3D%3E%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%7Bloading%20%26%26%20%3CLoader%20%2F%3E%7D%5Cn%20%20%20%20%20%20%7Bfailed%20%26%26%20%3CErrorMessage%20%2F%3E%7D%5Cn%20%20%20%20%20%20%7B!loading%20%26%26%5Cn%20%20%20%20%20%20%20%20!failed%20%26%26%5Cn%20%20%20%20%20%20%20%20list%20%26%26%5Cn%20%20%20%20%20%20%20%20!list.length%20%26%26%5Cn%20%20%20%20%20%20%20%20%3CEmptyState%5Cn%20%20%20%20%20%20%20%20%20%20title%3D%5C%22You%20have%20no%20snippets%5C%22%5Cn%20%20%20%20%20%20%20%20%20%20buttonText%3D%5C%22Create%20snippet%5C%22%5Cn%20%20%20%20%20%20%20%20%20%20to%3D%5C%22%2Fsnippets%2Fcreate%5C%22%5Cn%20%20%20%20%20%20%20%20%20%20icon%3D%5C%22money%5C%22%5Cn%20%20%20%20%20%20%20%20%2F%3E%7D%5Cn%20%20%20%20%20%20%7Blist%20%26%26%20list.length%20%26%26%20!failed%20%26%26%20!loading%5Cn%20%20%20%20%20%20%20%20%3F%20%3CTable%20hover%20size%3D%5C%22lg%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3Cthead%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTh%3EName%3C%2FTh%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTh%3EStatus%3C%2FTh%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7BenableCouponStats%20%26%26%20%3CTh%3ETotal%20Sent%3C%2FTh%3E%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7BenableCouponStats%20%26%26%20%3CTh%3ETotal%20Used%3C%2FTh%3E%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2Fthead%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3Ctbody%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7Blist.map(coupon%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTr%20key%3D%7Bcoupon.id%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CLink%20to%3D%7B%60%2Fsnippets%2F%24%7Bcoupon.id%7D%60%7D%20exact%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bcoupon.name%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20coupon.name%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3A%20%3Cspan%20className%3D%5C%22font-italic%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20no%20name%20available%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fspan%3E%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FLink%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B(()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20switch%20(coupon.status)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%27ACTIVE%27%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CBadge%20color%3D%5C%22success%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bcoupon.status%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FBadge%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%27INACTIVE%27%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CBadge%20color%3D%5C%22danger%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bcoupon.status%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FBadge%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20default%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CBadge%20className%3D%5C%22badge-secondary%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bcoupon.status%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FBadge%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)()%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7BenableCouponStats%20%26%26%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CNumberFormat%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%3D%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20stats%5Bcoupon.id%5D%20%3F%20stats%5Bcoupon.id%5D.total_sent%20%3A%200%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20displayType%3D%7B%27text%27%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftd%3E%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7BenableCouponStats%20%26%26%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CNumberFormat%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%3D%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20stats%5Bcoupon.id%5D%20%3F%20stats%5Bcoupon.id%5D.total_used%20%3A%200%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20displayType%3D%7B%27text%27%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftd%3E%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CLink%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20style%3D%7B%7B%20padding%3A%200%20%7D%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20to%3D%7B%60%2Fsnippets%2F%24%7Bcoupon.id%7D%2Femail%2F%60%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CUncontrolledDropdown%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CDropdownToggle%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20color%3D%5C%22default%20outline%5C%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20style%3D%7B%7B%20border%3A%20%27none%27%20%7D%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CI%20className%3D%5C%22fa%20fa-ellipsis-v%5C%22%20aria-hidden%3D%5C%22true%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FDropdownToggle%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CDropdownMenu%20style%3D%7B%7B%20padding%3A%200%20%7D%7D%20right%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bcoupon.status%20%3D%3D%3D%20%27ACTIVE%27%20%26%26%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CDropdownItem%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onClick%3D%7B()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20toastrConfirmOptions%20%3D%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onOk%3A%20()%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20deactivateCoupon(coupon.id).then(()%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20toastr.success(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27Deactivated%27%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27The%20snippet%20has%20been%20deactivated%27%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onCancel%3A%20()%20%3D%3E%20console.log(%27CANCEL%3A%20clicked%27)%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20message%20%3D%20(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Warning%3A%20Since%20you%20have%20deactivated%20snippet%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%22%7Bcoupon.name%7D%5C%22%2C%20the%20coupons%20normally%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20generated%20by%20this%20snippet%20will%20not%20be%20sent%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20by%20any%20emails.%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fp%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Please%20modify%20any%20email%20templates%20that%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20reference%20this%20snippet.%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fp%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20toastr.confirm(message%2C%20toastrConfirmOptions)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20style%3D%7B%7B%20color%3A%20%27rgba(254%2C89%2C95%2C1)%27%20%7D%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ci%20className%3D%5C%22fa%20fa-trash%5C%22%20%2F%3E%20Deactivate%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fspan%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FDropdownItem%3E%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Bcoupon.status%20%3D%3D%3D%20%27INACTIVE%27%20%26%26%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CDropdownItem%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onClick%3D%7B()%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20activateCoupon(coupon.id).then(()%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20toastr.success(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27Activated%27%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27The%20snippet%20has%20been%20activated%27%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20className%3D%5C%22text-success%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ci%20className%3D%5C%22fa%20fa-check%5C%22%20%2F%3E%20Activate%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fspan%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FDropdownItem%3E%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FDropdownMenu%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FUncontrolledDropdown%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTr%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20)%7D%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2Ftbody%3E%5Cn%20%20%20%20%20%20%20%20%3C%2FTable%3E%5Cn%20%20%20%20%20%20%20%20%3A%20null%7D%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%5Cn%7D%5Cn%5CnCouponSnippetList.propTypes%20%3D%20%7B%5Cn%20%20list%3A%20PropTypes.arrayOf(%5Cn%20%20%20%20PropTypes.shape(%7B%5Cn%20%20%20%20%20%20name%3A%20PropTypes.string%2C%5Cn%20%20%20%20%20%20id%3A%20PropTypes.string%2C%5Cn%20%20%20%20%20%20status%3A%20PropTypes.oneOf(%5B%27ACTIVE%27%2C%20%27INACTIVE%27%5D)%2C%5Cn%20%20%20%20%20%20created%3A%20PropTypes.string%2C%5Cn%20%20%20%20%20%20amount%3A%20PropTypes.number%2C%5Cn%20%20%20%20%20%20total_delivered%3A%20PropTypes.number%2C%5Cn%20%20%20%20%20%20total_opens%3A%20PropTypes.number%2C%5Cn%20%20%20%20%20%20total_clicks%3A%20PropTypes.number%2C%5Cn%20%20%20%20%7D)%5Cn%20%20)%2C%5Cn%20%20stats%3A%20PropTypes.objectOf(%5Cn%20%20%20%20PropTypes.shape(%7B%5Cn%20%20%20%20%20%20total_sent%3A%20PropTypes.number%2C%5Cn%20%20%20%20%20%20total_used%3A%20PropTypes.number%2C%5Cn%20%20%20%20%7D)%5Cn%20%20)%2C%5Cn%20%20deactivateCoupon%3A%20PropTypes.func.isRequired%2C%5Cn%20%20activateCoupon%3A%20PropTypes.func.isRequired%2C%5Cn%20%20loading%3A%20PropTypes.bool%2C%5Cn%20%20failed%3A%20PropTypes.bool%2C%5Cn%7D%5Cn%5Cnexport%20default%20CouponSnippetList%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

So the problem does not appear to be in Prettier. Instead, the cause could be:

- Your Prettier configuration.
- ESLint.
- Your ESLint configuration.
- Some ESLint plugin you might use.
- The IntelliJ ESLint integration.

Looks like you need to go dig into what's happening there for you. When you have, totally feel free to come back here and tell how it went and if there's something we need to fix in Prettier after all!

**Comment by Geczy** [comment]
```
    "prettier/prettier": ["error", {
      "singleQuote": true,
      "semi": false,
      "trailingComma": "es5"
    }],
```

Can you run it in the playground with this?

**Comment by k15a** [comment]
Still working with your options as well ;)

**Comment by Geczy** [comment]
Oh good! Then I will look into it
