### ISSUE TITLE
config file doesn't work at the way other libraries do

### ISSUE THREAD

**Issue by e-cloud** [prettier/prettier#2691]
**First, It's very exciting that config file support is out.**

However, after a few tries, I find its usage is a bit ambiguous.

For example, I define a `.prettierrc` like the follow:
```json
{
  "printWidth": 120,
  "tabWidth": 2,
  "singleQuote": true,
  "semi": false,
  "trailingComma": "all",
  "overrides": [
    {
      "files": "src/**/*.ts",
      "options": {
        "parser": "typescript",
        "tabWidth": 4
      }
    },
    {
      "files": "./**/*.js",
      "options": {
        "parser": "babylon",
        "singleQuote": false
      }
    },
    {
      "files": "src/**/*.{scss,css}",
      "options": {
        "parser": "postcss",
        "singleQuote": false,
        "semi": true
      }
    },
    {
      "files": "./**/*.json",
      "options": {
        "parser": "json"
      }
    },
    {
      "files": ".prettierrc",
      "options": {
        "parser": "json"
      }
    }
  ]
}
```

Since I specify the files in `overrides`, prettier should do the right job with `prettier --write` or `prettier --list-difference`.

However, prettier doesn't work that way now. If I run the command above, prettier will only output the help message and exit. Apparently, prettier is waiting for source input. But it doesn't make sense to specify input again. 

 There is a dirty workaround `prettier --write ./**/**.{ts,js,json,scss,css}`. But it lose the ability to prettier various specify path.

**Comment by lydell** [comment]
As I told you here: https://github.com/prettier/prettier/issues/2506#issuecomment-325570177

> @e-cloud See #2683. That has been fixed and will be released in 1.6.1!

Workaround: `prettier ./**/**.{ts,js,json,scss,css} --write` (move `--write` last)

**Comment by lydell** [comment]
@azz Why reopen? What am I missing? :)

**Comment by azz** [comment]
It's actually a separate issue.

@e-cloud is expressing that `prettier --write` should know where to look for files based on the configuration file, rather than passing a glob to the CLI.

**Comment by lydell** [comment]
I see.

@e-cloud Sorry, I was too quick – your issue looked way too similar to the other one.

**Comment by azz** [comment]
I believe ESLint will run on all `.js` files not ignored by `.eslintignore`.  TSLint must be passed a glob. I'm not sure how other tools work.

If we are to implement this we'd need a whitelist of globs or extensions which we want to run prettier on.

We could expose this as `"extensions"`, something like:

```json
{
  "printWidth": 120,
   ...
  "extensions": [".ts", ".js", ".css", ".scss", ".json"],
  "overrides": [
    ...
  ]
}
```

The default value could be all of the extensions here: 
https://github.com/prettier/prettier/blob/3319db6d51f134e192a7df1545775e4e8f85fc77/src/options.js#L32

**Comment by atty-stripe** [comment]
+1 on this; whitelisting globs where prettier should run would be very helpful.

**Comment by athyuttamre** [comment]
+1 on this; whitelisting globs where prettier should run would be very helpful.

**Comment by benblank** [comment]
I came here to request something similar — a way to specify file patterns in the config file rather than on the command line.

How's this for a solution?  Add a config file parameter `patterns` (which can be either a glob string or an array of glob strings) that defaults to all supported file types (e.g. `**/*.{css,less,scss,html,ts,tsx,graphql,gql,json,js,jsx}`).  That gives a pretty sane default behavior of "format everything" that can be overridden in the config if desired.

(I'm less of a fan of defaulting to just those patterns in `overrides`, as it means a project still has to list out all of Prettier's supported file types in the config file, one way or another.)

**Comment by felixfbecker** [comment]
I would really like Prettier to just format all files in the cwd that it supports. Currently I have to construct a glob in every project, which is highly non-trivial when it comes to dotfiles like `.travis.yml` and other config files:
```
`prettier '**/{*.{js?(on),ts,y?(a)ml,graphql,md,scss},.*.y?(a)ml,.*.json,.prettierrc,.stylelintrc}'`
```

**Comment by remcohaszing** [comment]
@felixfbecker You may want to use the following glob instead. It works for all files in the project directory in the extensions list.

```
prettier '{**/,}*.{html,json,md,yaml,yml}'
```

Of course you could add more extensions if you wish.

_.prettierrc_ and _.stylelintrc_ can be given a _.json_, _.yaml_, or _.js_ extension. This should also make it work better with tooling, i.e. syntax highlighters.

**Comment by felixfbecker** [comment]
@remcohaszing what does the `,` do? I have never seen that syntax. Are you 100% this will match files starting with a dot?

**Comment by remcohaszing** [comment]
`{**/,}` means it matches either `**/` (directories, optionally nested), or an empty string (no parent directories). It’s actually the same as the comma between the extensions.

I am not 100% sure whether or not this pattern works for all tools. I believe some glob implementations do indeed treat dotfiles differently. However, I am sure this works for prettier.

**Comment by felixfbecker** [comment]
`**/` also matches no parent directories (i.e. `**/*.txt` would also match `./foo.txt`) so I don't understand the point of the comma?

**Comment by felixfbecker** [comment]
Seems like the glob matching actually was fixed and the pattern `**/*.yml` now also matches `.travis.yml` 🎉

**Comment by trevordmiller** [comment]
Would be very nice to have sensible defaults in Prettier 2.0. My typical setup is something like `prettier write "**/*.{js,json,md}"` direct or in npm scripts like `"format": "prettier --write \"**/*.{js,json,md}\""`. Would be nice to be able to run `prettier --write` with defaults, like how other tools work with defaults (like `jest` and `eslint .` without having to do things like `--ext js).

**Comment by lydell** [comment]
@trevordmiller Sounds like you’d be interested in #7073.

**Comment by thorn0** [comment]
@trevordmiller Prettier 2.0 is going to support `prettier --write .`, see https://github.com/prettier/prettier/pull/7660.

**Comment by thorn0** [comment]
Now that we have `prettier --write .`, this can be considered resolved.

**Comment by czerwinskilukasz1** [comment]
I noticed that while `prettier --write .` finishes successfully, running `prettier --check .` fails with errors:
```
src/playground/dist/views/main.handlebars[error] No parser could be inferred for file: src/playground/dist/views/main.handlebars
src/playground/src/views/main.handlebars[error] No parser could be inferred for file: src/playground/src/views/main.handlebars
```

Shouldn't both commands behave the same?

**Comment by fisker** [comment]
Please open  a  new  issue.
