### ISSUE TITLE
unnecessary semi insertion for typescript type cast

### ISSUE THREAD

**Issue by e-cloud** [prettier/prettier#2693]
Example:
**source:**
```ts
class A {
    handleInputFocus(): void {
        (<HTMLInputElement>this._input.nativeElement).select()
    }
}
```

**expected output:**
the same as source.

**actual output:**
```ts
class A {
    handleInputFocus(): void {
        ;(<HTMLInputElement>this._input.nativeElement).select()
    }
}
```

a semicolon is inserted before the left parentheses, which should not be.

**Comment by lydell** [comment]
This is actually intended. As described in the [options](https://github.com/prettier/prettier#options):

> Semicolons - Print semicolons at the ends of statements.
>
> Valid options:
> - true - add a semicolon at the end of every statement
> - false - only add semicolons at the beginning of lines that may introduce ASI failures

See #1935 and the issues it links to.

**Comment by e-cloud** [comment]
I use tslint check the code for typescript files.

However, I notice that, after i use prettier to format ts files, all that warning tslint is complaining about are some code like:

```
{
     ;(<SomeType>varibale).somemethod()
     //...
}
```

Since the semi-inserted statement is the first statement within a code block, there is no way it would raise ASI failures. Am i right?

**Comment by lydell** [comment]
https://github.com/prettier/prettier/issues/736#issuecomment-291934981
