### ISSUE TITLE
unexpected double quotes transform for string with escaped quote

### ISSUE THREAD

**Issue by e-cloud** [prettier/prettier#2694]
Example:
a string like: `'Can\'t load map without an app key'` is formatted by prettier with `singleQuote: true`.

**expected output**: the same as the source

**actual output**: `"Can't load map without an app key"`,  the string is outputed as double-quote string.

**Comment by azz** [comment]
This is explained in the README

https://github.com/prettier/prettier#quotes

> * If the number of quotes outweighs the other quote, the quote which is less used will be used to format the string - Example: "I'm double quoted" results in "I'm double quoted" and "This \"example\" is single quoted" results in 'This "example" is single quoted'.

**Comment by e-cloud** [comment]
But is it reasonable? If so, that would break both eslint and tslint checking.

**Comment by lydell** [comment]
@e-cloud This has already been discussed several times before.
