### ISSUE TITLE
Babel — Syntax Error: Cannot overwrite primitive type bool

### ISSUE THREAD

**Issue by k15a** [prettier/prettier#2696]
When I use Prettier to format the [`prop-types` declaration of flow-typed](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/prop-types_v15.x.x/flow_v0.41.x-/prop-types_v15.x.x.js) there is a syntax error which is only happening with babylon as the parser and not when I use flow as the parser.

Babylon: [Example](https://prettier.io/playground/#%7B%22content%22%3A%22type%20%24npm%24propTypes%24ReactPropsCheckType%20%3D%20(%5Cn%20%20props%3A%20any%2C%5Cn%20%20propName%3A%20string%2C%5Cn%20%20componentName%3A%20string%2C%5Cn%20%20href%3F%3A%20string)%20%3D%3E%20%3FError%3B%5Cn%5Cndeclare%20module%20'prop-types'%20%7B%5Cn%20%20declare%20var%20array%3A%20React%24PropType%24Primitive%3CArray%3Cany%3E%3E%3B%5Cn%20%20declare%20var%20bool%3A%20React%24PropType%24Primitive%3Cboolean%3E%3B%5Cn%20%20declare%20var%20func%3A%20React%24PropType%24Primitive%3CFunction%3E%3B%5Cn%20%20declare%20var%20number%3A%20React%24PropType%24Primitive%3Cnumber%3E%3B%5Cn%20%20declare%20var%20object%3A%20React%24PropType%24Primitive%3CObject%3E%3B%5Cn%20%20declare%20var%20string%3A%20React%24PropType%24Primitive%3Cstring%3E%3B%5Cn%20%20declare%20var%20any%3A%20React%24PropType%24Primitive%3Cany%3E%3B%5Cn%20%20declare%20var%20arrayOf%3A%20React%24PropType%24ArrayOf%3B%5Cn%20%20declare%20var%20element%3A%20React%24PropType%24Primitive%3Cany%3E%3B%20%2F*%20TODO%20*%2F%5Cn%20%20declare%20var%20instanceOf%3A%20React%24PropType%24InstanceOf%3B%5Cn%20%20declare%20var%20node%3A%20React%24PropType%24Primitive%3Cany%3E%3B%20%2F*%20TODO%20*%2F%5Cn%20%20declare%20var%20objectOf%3A%20React%24PropType%24ObjectOf%3B%5Cn%20%20declare%20var%20oneOf%3A%20React%24PropType%24OneOf%3B%5Cn%20%20declare%20var%20oneOfType%3A%20React%24PropType%24OneOfType%3B%5Cn%20%20declare%20var%20shape%3A%20React%24PropType%24Shape%3B%5Cn%5Cn%20%20declare%20function%20checkPropTypes%3CV%3E(%5Cn%20%20%20%20propTypes%3A%20%24Subtype%3C%7B%5B_%3A%20%24Keys%3CV%3E%5D%3A%20%24npm%24propTypes%24ReactPropsCheckType%7D%3E%2C%5Cn%20%20%20%20values%3A%20V%2C%5Cn%20%20%20%20location%3A%20string%2C%5Cn%20%20%20%20componentName%3A%20string%2C%5Cn%20%20%20%20getStack%3A%20%3F(()%20%3D%3E%20%3Fstring)%5Cn%20%20)%20%3A%20void%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)
Flow: [Example](https://prettier.io/playground/#%7B%22content%22%3A%22type%20%24npm%24propTypes%24ReactPropsCheckType%20%3D%20(%5Cn%20%20props%3A%20any%2C%5Cn%20%20propName%3A%20string%2C%5Cn%20%20componentName%3A%20string%2C%5Cn%20%20href%3F%3A%20string)%20%3D%3E%20%3FError%3B%5Cn%5Cndeclare%20module%20'prop-types'%20%7B%5Cn%20%20declare%20var%20array%3A%20React%24PropType%24Primitive%3CArray%3Cany%3E%3E%3B%5Cn%20%20declare%20var%20bool%3A%20React%24PropType%24Primitive%3Cboolean%3E%3B%5Cn%20%20declare%20var%20func%3A%20React%24PropType%24Primitive%3CFunction%3E%3B%5Cn%20%20declare%20var%20number%3A%20React%24PropType%24Primitive%3Cnumber%3E%3B%5Cn%20%20declare%20var%20object%3A%20React%24PropType%24Primitive%3CObject%3E%3B%5Cn%20%20declare%20var%20string%3A%20React%24PropType%24Primitive%3Cstring%3E%3B%5Cn%20%20declare%20var%20any%3A%20React%24PropType%24Primitive%3Cany%3E%3B%5Cn%20%20declare%20var%20arrayOf%3A%20React%24PropType%24ArrayOf%3B%5Cn%20%20declare%20var%20element%3A%20React%24PropType%24Primitive%3Cany%3E%3B%20%2F*%20TODO%20*%2F%5Cn%20%20declare%20var%20instanceOf%3A%20React%24PropType%24InstanceOf%3B%5Cn%20%20declare%20var%20node%3A%20React%24PropType%24Primitive%3Cany%3E%3B%20%2F*%20TODO%20*%2F%5Cn%20%20declare%20var%20objectOf%3A%20React%24PropType%24ObjectOf%3B%5Cn%20%20declare%20var%20oneOf%3A%20React%24PropType%24OneOf%3B%5Cn%20%20declare%20var%20oneOfType%3A%20React%24PropType%24OneOfType%3B%5Cn%20%20declare%20var%20shape%3A%20React%24PropType%24Shape%3B%5Cn%5Cn%20%20declare%20function%20checkPropTypes%3CV%3E(%5Cn%20%20%20%20propTypes%3A%20%24Subtype%3C%7B%5B_%3A%20%24Keys%3CV%3E%5D%3A%20%24npm%24propTypes%24ReactPropsCheckType%7D%3E%2C%5Cn%20%20%20%20values%3A%20V%2C%5Cn%20%20%20%20location%3A%20string%2C%5Cn%20%20%20%20componentName%3A%20string%2C%5Cn%20%20%20%20getStack%3A%20%3F(()%20%3D%3E%20%3Fstring)%5Cn%20%20)%20%3A%20void%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

```
SyntaxError: Cannot overwrite primitive type bool (9:15)
   7 | declare module 'prop-types' {
   8 |   declare var array: React$PropType$Primitive<Array<any>>;
>  9 |   declare var bool: React$PropType$Primitive<boolean>;
     |               ^
  10 |   declare var func: React$PropType$Primitive<Function>;
  11 |   declare var number: React$PropType$Primitive<number>;
  12 |   declare var object: React$PropType$Primitive<Object>;
```

**Comment by existentialism** [comment]
@k15a thanks for the report, fixed in https://github.com/babel/babylon/pull/705! Will update prettier as soon as we tag a new release.

**Comment by gtdeng** [comment]
for anyone else that has this issue, you can either 1. upgrading prettier and potentially causing massive file changes throughout the code or 2. ignore the `flow-typed` folder in your `.prettierignore` file.
