### ISSUE TITLE
CSS: Formatting is wrong with interpolations

### ISSUE THREAD

**Issue by satya164** [prettier/prettier#2701]
When a CSS string contains interpolations, it's incorrectly formatted.

```js
const title = css`
  ${snippet}

  color: blue;
  font-family: sans-serif;
`;
```

is formatted into

```js
const title = css`
  ${snippet} color: blue;
  font-family: sans-serif;
`;
```

I'd expect the interpolation to be on it's own line if it's not part of a property declaration.

**Comment by lydell** [comment]
Thanks for the issue! I believe this is already tracked in #2291, so I'm closing in favor of that one.
