### ISSUE TITLE
package.json has problems with '--config'

### ISSUE THREAD

**Issue by jason0x43** [prettier/prettier#2704]
Say I have this file structure:

```
/path/to/project
    package.json
/tmp
    some_file.js
```

If I cd into `/tmp` and run `prettier --config /path/to/project/package.json some_file.js`, the values in the "prettier" key in the package.json are ignored. However, if I have this structure:

```
/path/to/project
    .prettierrc
/tmp
    some_file.js
```

and run `prettier --config /path/to/project/.prettierrc some_file.js`, the config values in .prettierrc are used.

**Comment by jason0x43** [comment]
From a quick look, it _seems_ like the problem might be that when prettier is loading a package.json file (or any config file) specified with `--config`, it treats the entire file as a config file. However, when loading a package.json file during config discovery, prettier pulls out the "prettier" property.

**Comment by azz** [comment]
^ I've opened an issue with cosmiconfig

**Comment by jason0x43** [comment]
Great, thanks
