### ISSUE TITLE
CSS - formatting leading decimal zeroes

### ISSUE THREAD

**Issue by ivancuric** [prettier/prettier#2705]
When using prettier to format CSS, it's formatting numbers without leading zeroes to them having it, eg `.5 => 0.5`

Any way to bypass it? Haven't found any options for it in `.prettierrc`

**Comment by lydell** [comment]
Thanks you for the issue!

- This is new in 1.6.0.
- We already do this in JS.
- [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard/) enforces it.

This is a super minor thing and the decision has already been made. There won't be an option – sorry! Easier to just get used to it and move on with styling that website really nice!

**Comment by xereda** [comment]
@CiGit How did you solve this need?

**Comment by xereda** [comment]
@ivancuric How did you solve this need?
