### ISSUE TITLE
Improve readability of array iteration in jsx

### ISSUE THREAD

**Issue by vladshcherbin** [prettier/prettier#2707]
```jsx
// in
const UsersList = ({ users }) => (
  <section>
    <h2>Users list</h2>
    <ul>
      {users.map(user => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  </section>
)

// out
const UsersList = ({ users }) => (
  <section>
    <h2>Users list</h2>
    <ul>{users.map(user => <li key={user.id}>{user.name}</li>)}</ul>
  </section>
)
```

Prettier removes parentheses and inlines array iteration which reduces readability.

Prettier 1.6.1, [playground](https://prettier.io/playground/#%7B%22content%22%3A%22import%20React%20from%20'react'%5Cn%5Cnconst%20UsersList%20%3D%20(%7B%20users%20%7D)%20%3D%3E%20(%5Cn%20%20%3Csection%3E%5Cn%20%20%20%20%3Ch2%3EUsers%20list%3C%2Fh2%3E%5Cn%20%20%20%20%3Cul%3E%5Cn%20%20%20%20%20%20%7Busers.map(user%20%3D%3E%20(%5Cn%20%20%20%20%20%20%20%20%3Cli%20key%3D%7Buser.id%7D%3E%7Buser.name%7D%3C%2Fli%3E%5Cn%20%20%20%20%20%20))%7D%5Cn%20%20%20%20%3C%2Ful%3E%5Cn%20%20%3C%2Fsection%3E%5Cn)%5Cn%5Cnexport%20default%20FormError%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by albertogasparin** [comment]
I agree, v1.6.1 "one line" version is much harder to read. It happens also when using other combinations like:

```js
const TodoList = ({ todos }) => (
  <div className="TodoList">
    <ul>{_.map(todos, (todo, i) => <TodoItem key={i} {...todo} />)}</ul>
  </div>
);
```

**Comment by vladshcherbin** [comment]
@duailibe awesome, thank you!
