### ISSUE TITLE
Formatting of Spread Properties differs between Babylon and TypeScript

### ISSUE THREAD

**Issue by mariusschulz** [prettier/prettier#2708]
Using the **Babylon** parser:

```js
// In
const x = { ...a || b };

// Out
const x = { ...(a || b) };
```

Using the **TypeScript** parser:

```js
// In
const x = { ...a || b };

// Out
const x = { ...a || b };
```

Prettier should also add clarifying parentheses around `a || b` in TypeScript.

**Comment by azz** [comment]
Looks like TypeScript is using `ExperimentalSpreadProperty`. Flow uses `SpreadProperty`and Babylon uses `SpreadElement`.
