### ISSUE TITLE
Removal of the `declare` modifier from `enum`

### ISSUE THREAD

**Issue by mariusschulz** [prettier/prettier#2709]
Using the **TypeScript** parser within a `.d.ts` type definition file:

```ts
// In
declare const enum Foo {}

// Out
const enum Foo {}
```

However, the `declare` keyword must be preserved here, otherwise the TypeScript compiler issues the following error:

```plain
A 'declare' modifier is required for a top level declaration in a .d.ts file.
```

**Comment by azz** [comment]
Are you using 1.6, I seem to recall fixing this issue.

**Comment by mariusschulz** [comment]
Yeah, I remember reading about it. I am using prettier@1.6.1 (I just double-checked).

**Comment by azz** [comment]
Ah, this is specific to `enum`.
