### ISSUE TITLE
Chained Short Circuit Conditionals in JSX

### ISSUE THREAD

**Issue by brycehill** [prettier/prettier#2714]
Just upgraded to 1.6.1 and noticed that chained "short circuit" conditionals no longer get indented. Is this intentional? 

**v1.5.3**
```js
const Foo = (bar, baz) =>
  <div>
    {bar &&
      baz &&
      <span>hello there. make this long enough to wrap to the next line</span>}
  </div>
```

**v1.6.1**
```js
const Foo = (bar, baz) => (
  <div>
    {bar &&
    baz && (
      <span>hello there. make this long enough to wrap to the next line</span>
    )}
  </div>
)
```

**Comment by lydell** [comment]
@suchipi Do you know if this was intended?

**Comment by suchipi** [comment]
Not intentional; this is a bug.

Should we change it to A:
```jsx
const Foo = (bar, baz) => (
  <div>
    {bar &&
      baz && (
        <span>hello there. make this long enough to wrap to the next line</span>
      )
    }
  </div>
)
```

B:
```jsx
const Foo = (bar, baz) => (
  <div>
    {bar &&
      baz && (
        <span>hello there. make this long enough to wrap to the next line</span>
    )}
  </div>
)
```

or C?
```jsx
const Foo = (bar, baz) => (
  <div>
    {bar && baz && (
        <span>hello there. make this long enough to wrap to the next line</span>
    )}
  </div>
)
```

(Or something else).

My preference is C or A.

**Comment by lydell** [comment]
I vote for A. C could be nice as an extra improvement when all the conditions don't fit on a single line.

**Comment by vjeux** [comment]
You're going to have a ton of issues trying to make C work. I vote for A.

**Comment by vjeux** [comment]
@suchipi: I would love to do a new patch release with those JSX fixes in this week. Do you think you'd have time to implement them?

**Comment by suchipi** [comment]
Probably not this week, honestly- which is a shame, because I'd like to. But I recently moved, and have been spending most of my free time unpacking. And I don't have bandwidth to do open-source contributions at work.

I'd be able to review a PR, though. Or I could tackle this in a couple of weeks.

**Comment by vjeux** [comment]
@suchipi thanks for the context :) Enjoy your new place!

**Comment by vcarel** [comment]
I vote for C. Otherwise B.
A makes too many line jumps compared to v1.5.3 (btw parenthesis are annoying; I really dislike them)

**Comment by duailibe** [comment]
I believe this issue isn't exclusive to JSX though. See [playground](https://prettier.io/playground/#%7B%22content%22%3A%22const%20foo%20%3D%20bar%20%26%26%20baz%20%26%26%20%7Bkey%3A%5C%22make%20this%20string%20long%20enough%20to%20break%20in%20multiple%20lines%5C%22%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)
