### ISSUE TITLE
Inline comment after func params is printed inside the params

### ISSUE THREAD

**Issue by levithomason** [prettier/prettier#2715]
### Original

I've migrated a large codebase which used this function definition style:
```js
function func(a, b)  // `a` is the first arg
{
 return 'done'
}
```

### Reprinted

`prettier` reprinted all comments following function params like this:

```js
function func(
  a,
  b // `a` is the first arg
) {
  return "done";
}
```

This is extra confusing as the comment is on the same line as a parameter it does not refer to. We have many of these cases as you might imagine.

### Proposal

The comment must be moved since an inline comment can't appear between the closing paren and opening curly: `) {`.  Since the original comment was not inside the parentheses, IMHO, it should not be moved inside when reprinted.

I would think most humans would rewrite the original function with the comment on the line above the function:

```js
// `a` is the first arg
function func(a, b) {
  return "done";
}
```

***

Would love to hear feedback on this.

https://prettier.io/playground/#%7B%22content%22%3A%22function%20func(a%2C%20b)%20%20%2F%2F%20%60a%60%20is%20the%20first%20arg%5Cn%7B%5Cn%20return%20'done'%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
That sounds fine, if you want to try and implement it.

**Comment by levithomason** [comment]
Thanks for the quick reply.  I'll take a look when I get some time.

**Comment by levithomason** [comment]
Hm, thinking this through.  I'm not sure what the impact might be to code that must appear directly above a function like decorators, docblocks, etc.

A less desirable alternative might be to print the inline comment on the first line of the func body. 
 Will leave it at that for now.

**Comment by vjeux** [comment]
Fwiw, my stance on comments is that we should support common places where comments are added and do some reasonable job for places where it's a bit crazy. In this case, I feel like we're doing a reasonable job, we didn't find the correct location where to attach the comment but the code is properly indented. If we can fix it, then for the better. If we can't, then it's okay, we need to accept the fact that we won't be able to handle all the places where people add comments.

**Comment by levithomason** [comment]
Agreed, closing for the sake of progress.
