### ISSUE TITLE
mongoose .populate() failing prettier checks

### ISSUE THREAD

**Issue by jeffreyxchan** [prettier/prettier#2721]
My project uses prettier with Travis CI to run tests on my project. When making a PR today, Travis reported a build failure, and that a file `/admin/teams.js` was not formatted properly with prettier.

I use the prettier integration on atom to format on save, and even ran prettier through the CLI to make sure prettier ran through the `/admin/teams.js` file, but it still failed.

I kept making small commits and pushing them until I found a fix to the issue, and the commit that ultimately fixed the build was to remove `.populate('members')` from my mongoose query.
```
Team.find().populate('members').then(teams => {
 ....
})
```
It's very weird because just right underneath that section of code, there exists another `Team.find().populate('members')` and that doesn't fail the build....
It's probably worth noting that the other .populate() function that doesn't fail the build was formatted on a separate line instead of the same line like so:
```
Team.find()
  .populate('members')
  .then(teams => {
    .....
  })
```

Could anyone tell me why this is happening?
prettier version on package.json: 1.5.3
prettier-check version on package.json: 1.0.0
PR: https://github.com/ideahacks/ideahacks.la/pull/90
Commit: https://github.com/ideahacks/ideahacks.la/pull/90/commits/681fdf77e605137741b9b3f57749418576a5c4a0

![image](https://user-images.githubusercontent.com/16298586/29932341-dcbea164-8e28-11e7-9345-a8c56fd109b9.png)

**Comment by azz** [comment]
Your package.json has `prettier@^1.5.1`, which permits your CI to upgrade to 1.6.
If you upgrade locally you'll notice the `.populate('members')` code will format into another line.

**Comment by azz** [comment]
Side note: I'd recommend changing your package.json to use `~` instead of `^` for prettier so you know you're running the same version in both environments.
