### ISSUE TITLE
Prettier does not format styled(Component).attrs(...)``

### ISSUE THREAD

**Issue by lixiaoyan** [prettier/prettier#2723]

**Comment by WickyNilliams** [comment]
Here is [an example](https://prettier.io/playground/#%7B%22content%22%3A%22const%20ToastTransition%20%3D%20styled(CSSTransition).attrs(%7B%5Cn%20%20classNames%3A%20%5C%22toast%5C%22%5Cn%7D)%60%5Cn%20%20transition%20%3A%20all%201s%5Cn%60%3B%5Cn%5Cnconst%20ToastTransition%20%3D%20styled(CSSTransition)%60%5Cn%20%20transition%20%3A%20all%201s%5Cn%60%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22es5%22%2C%22useTabs%22%3Afalse%7D%7D)

You can see that colon position is not corrected, nor is a semicolon added
