### ISSUE TITLE
Add option for parentheses around JSX.

### ISSUE THREAD

**Issue by MartynasZilinskas** [prettier/prettier#2724]
I think prettier should have an option ~for TypeScript~ to omit JSX parentheses.

Instead of this:
```tsx
public render(): JSX.Element {
    return (
        <div>
            <div>Hello world!</div>
        </div>
    );
}
```

Expected behavior:
```tsx 
public render(): JSX.Element {
    return <div>
        <div>Hello world!</div>
    </div>;
}
```

**Comment by azz** [comment]
Why would this be related to TypeScript?

**Comment by MartynasZilinskas** [comment]
My bad, I thought that JSX without parentheses doesn't work in ES6 ([Code example](https://codesandbox.io/s/k801np6l7)). 

I think I need to rename this issue.

**Comment by azz** [comment]
We actually had a strong number of requests to add parenthesis in this case, and we will unlikely be adding an option for this unless there is significant demand for it.

**Comment by superfunkminister** [comment]
SIGNIFICANT DEMAND! xD

**Comment by DovydasNavickas** [comment]
SIGNIFICANT DEMAND TOO!

**Comment by Domysee** [comment]
What counts as significant demand here? Our team would also very much like to have an option for that. 
Is this completely off the table?

**Comment by lydell** [comment]
@Domysee This counts as significant demand: #812

**Comment by Domysee** [comment]
@lydell Thanks. That's quite a difference.

**Comment by moljac024** [comment]
SIGNIFICANT DEMAND!

**Comment by lydell** [comment]
Please 👍 the OP instead of … shouting. Makes it much easier to track popularity :)

**Comment by maciek134** [comment]
@azz will you accept a PR for this?

**Comment by lydell** [comment]
@maciek134 Thanks for your offer! However, at the moment we would not accept a PR for this.

**Comment by EmiJX** [comment]
SIGNIFICANT DEMAND! +10086

**Comment by markatk** [comment]
I considered using prettier, but this decision is a no-go for me. I cannot understand how adding an option to disable this would hurt anyone. I can understand you don't want to invest work into unused features, but I think you miss many users who are not vocal about their opinion.

**Comment by lydell** [comment]
@markatk https://prettier.io/docs/en/option-philosophy.html

**Comment by dimaqq** [comment]
I too wish there were no redundant parentheses around JSX 🙏
Someone dropped `prettier` into our codebase and now it looks like LISP 😭

**Comment by rottitime** [comment]
Can we build this in please? I love Prettier but this issue just bugs me.
The parentheses just add extra lines for no reason.

**Comment by qpwo** [comment]
One year later, with fragment tags being more common, I personally would still love to see an option to remove the parens around JSX return statements. The indentation is significant:

```jsx
function Intro() {
    return (
        <>
            <h1>Intro</h1>
            <div className="foo">
                <p>Lorem ipsum</p>
                <p>dolor sit amet</p>
            </div>
        </>
    )
}
```

**Comment by camsjams** [comment]
Parenthesis overall are useless, just do:
```
 "arrowParens": false
```

Fun fact, eslint used to describe the [no-extra-parens](https://eslint.org/docs/rules/no-extra-parens) rule "Gratuitous parentheses" :smile: :eyes:

**Comment by qpwo** [comment]
@camsjams arrowParens: false has no effect on jsx returns

**Comment by camsjams** [comment]
It did for our code, but its coupled with our eslint config `"no-extra-parens": 2`

**Comment by dantman** [comment]
I'm hesitant about random tags like `<div>`s. But I do agree that it's excessive to wrap the `<>...</>` fragment syntax. That syntax cannot have props and is effectively itself a form of parenthesis that just accepts multiple values. It kind of feels like wrapping `[...]` syntax in parenthesis. Which Prettier does not do.

```js
<RenderProp>
  {(a) => [
    <RenderProp>
      {(b) => [
        <RenderProp>
          {(c) => [
            <input value={a} />,
            <input value={b} />,
            <input value={c} />,
          ]}
        </RenderProp>,
      ]}
    </RenderProp>,
  ]}
</RenderProp>;
```

```js
<RenderProp>
  {(a) => (
    <>
      <RenderProp>
        {(b) => (
          <>
            <RenderProp>
              {(c) => (
                <>
                  <input value={a} />
                  <input value={b} />
                  <input value={c} />
                </>
              )}
            </RenderProp>
          </>
        )}
      </RenderProp>
    </>
  )}
</RenderProp>;
```

**Comment by maciek134** [comment]
As much as I'd like no wrapping around JSX at all, removing it around
fragments would allow people to circumvent the coding style enforced by
prettier.

To be honest I'm not sure why this issue is still open - a new option is
clearly not going to happen, and for some reason the majority of the React
community likes to wrap JSX in parentheses.

**Comment by dantman** [comment]
> removing it around fragments would allow people to circumvent the coding style enforced by prettier.

I'm not sure what you mean by circumventing. Prettier already has options to make small changes to its coding style. And Prettier's coding style changes continually. My argument is that `<>...</>` is effectively similar to `[...]` and the current Prettier style makes code less readable.

**Comment by maciek134** [comment]
> I'm not sure what you mean by circumventing.

From https://prettier.io/docs/en/option-philosophy.html:
> The same applies to requests to preserve elements of input formatting (e.g. line breaks) since that’s nothing else but an option in disguise with all the downsides of “real” options.

Not adding parens around `<>...</>` is effectively "preserving elements of input formatting" since you could stop the default behavior by replacing `( ... )` with `<>...</>`.

**Comment by dantman** [comment]
> Not adding parens around `<>...</>` is effectively "preserving elements of input formatting" since you could stop the default behavior by replacing `( ... )` with `<>...</>`.

No, that's not what I'm asking for at all. I'm not saying Prettier should preserve the input formatting. I'm saying that `<>...</>` are effectively parenthesis and having extra parenthesis around them is as pointless as writing `(\n[...]\n)`. Existing `(\n<>...</>\n)` should be converted to `<>...</>`.

**Comment by maciek134** [comment]
Let's try another way. One of Prettier's goals is to stop people from arguing over formatting. Once you add something like that, it means people can change this code:
```
return (
  <div>test</div>
);
```
to
```
return <>
  <div>test</div>
</>;
```
And now you will have a mix of those in your codebase, which means you have to write "(don't) wrap things in fragments" in some code style guide instead of letting the tool handle all formatting.

**Comment by dantman** [comment]
You could say the exact same thing about.

```js
return [
  <div key='a'>test</div>
];
```

And there are piles of other things Prettier doesn't enforce you need your own code style for. const/let, import order, function style, etc.

Except the fragment has the important function of being needed wherever you need multiple children and should not become harder to read with a huge pile of extra indentation and pointless lines of code added by Prettier. It should not look cleaner to write `[<a />, <b />]` than `<><a /><b /></>` in a React component, that is the opposite of best practice.

**Comment by maciek134** [comment]
I wouldn't say the exact same thing, since if you are returning arrays you have bigger problems than formatting.

I'd say any parentheses around JSX add extra indentation and pointless lines of code, but apparently that's what people want.

**Comment by qpwo** [comment]
For future googlers there's a dumb-as-rocks package `prettier-no-jsx-parens` now:

- https://www.npmjs.com/package/prettier-no-jsx-parens
- https://github.com/qpwo/prettier-no-jsx-parens

It's just a one-line change in `src/language-js/print/jsx.js` to `maybeWrapJsxElementInParens` to make it do nothing.

https://github.com/qpwo/prettier-no-jsx-parens/commit/12184bcaf75857d8b8673067e440bfc8bc7d19e8#diff-03c0c60f14ea0de8026d9fda184945e03330f514eeee757fcebd84c5a090b048

**Comment by nicodes** [comment]
Please add this! I agree that prettier should be opinionated, but those opinions should be set in the config

**Comment by DreamWorld420** [comment]
SIGNIFICANT DEMAND

**Comment by Malabarba** [comment]
> @Domysee This counts as significant demand: #812

Firstly, thanks for all your patience with this thread (and all the effort put into prettier, of course).

From what I can tell, the original post has quite a few more :+1:  than the linked issue. Are PRs still not being accepted?

Parentheses around jsx are redundant and tend to contribute to visual clutter in a syntax (HTML) that's usually burdened with a high clutter-to-logic ratio. I'm not arguing to change the default, I'm just explaining why some of us would like to be able to configure this behavior.

Regardless of the decision, thanks a ton for this package. :bow:

**Comment by wasek23** [comment]
SIGNIFICANT DEMAND!
I am not using prettier, just for this!

**Comment by dcworldwide** [comment]
Function vs form. 

Is there function to excess parenthesis? No
Is there form to excess parenthesis?  Maybe. But it's weak at best. So a flag to disable it? Seems intelligent.

**Comment by RoVixen** [comment]
plz add this! i hate those parenthesis

**Comment by chrisgitrepo** [comment]
I've had to remove Prettier entirely from my company's codebase due to unconfigurable superfluous parenthesis. It's such a shame as I've always loved Prettier. Hopefully this will be considered in the future.

**Comment by hakt0r** [comment]
I concur with op and all the significant demands:
1. It's not **prettier** like this
2. Makes code less readable
3. [] exists as a precedent
4. Clinging to an archaic style that was rectified in the JSX spec in order to **improve readability**
5. parens and fragments are two separate use cases being confused into one ... vv
6. this would be perfectly valid if parens were an equivalent to fragments **but they are not**
7. ... **fork** ... for the time being...

**Comment by SankarshanDudhate** [comment]
It feels like a necessity now.

```
const x = 5
const y = 6
if(someCondition) {
  console.log(x)
  content = (
    <p>x</p>
  )
} else {
  content = (
    <p>y</p>
  )
}
return {<div>{content}</div>}
```
Instead of rendering the value of x or y, it prints 'x' or 'y'. The console log works fine though.

If this isn't a necessity, then I don't know what is.

**Comment by harshmoorjani** [comment]
So, looks like this is not going to happen.

Hence, what's the easiest way to fork prettier, make changes and use that in your codebase - while still being able to get new features from prettier (automatically or via a simple git pull)?

**Comment by silviogutierrez** [comment]
@harshmoorjani : probably using [patch-package](https://github.com/ds300/patch-package) . I don't use to for prettier but have with other tools and it works very well.

**Comment by harshmoorjani** [comment]
@silviogutierrez : Super, thanks for the nudge in the right direction. 

After checking the [patch-package](https://github.com/ds300/patch-package) repo, I ended up -

1. Upgrading to yarn 2
2. Patching prettier with `yarn patch` (based on comment from @qpwo)

**Comment by tranvansang** [comment]
If you want to patch a package, use `patch-package`  for yarn 1 or use yarn 2 native patch protocol (no package required). 

I have a tut here.

https://transang.me/how-to-patch-a-package-with-yarn/

If anyone forks this package, I will definitely give it a try. prettier is too opinionated, too many parentheses, too many newlines.

**Comment by ajhawkings** [comment]
> This counts as significant demand: #812

@lydell This pull request now has nearly double the thumbs up as #812, which you mentioned as counting as significant demand. Can the discussion over whether there should be brackets and whether a config option is needed please be reopened? This seems to be a very polarising issue for a lot of people - we would really appreciate work on this :)

**Comment by ZeeshanAhmadKhalil** [comment]
Is there any property for this yet?

**Comment by cAttte** [comment]
i'd love this option as much as the next guy but please just [read](https://prettier.io/docs/en/option-philosophy.html):
> Prettier has a few options because of history. **But we won’t add more of them.**

**Comment by nabato** [comment]
SIGNIFICANT DEMAND!

**Comment by silviogutierrez** [comment]
@qpwo problem is this is now a separate package and needs to be maintained upstream.

Whereas a plugin would be much cleaner. 

I think maybe https://github.com/prettier/prettier/issues/7884#issuecomment-2089846929 would work? @Yikes2000

**Comment by kimtaejin3** [comment]
SIGNIFICANT DEMAND

**Comment by tizu69** [comment]
love it when an open source project does not like community requested features :rocket:

**Comment by Yikes2000** [comment]
> Is there any good alternative to prettier? this is a deal breaker for us :(

In case it was missed, now there is a Prettier plugin that offers this syntax by default:
`  return <div>
    <div>Hello world!</div>
  </div>;`

- https://www.npmjs.com/package/@yikes2000/prettier-plugin-merge-extras#user-content-return-parentheses

Install Prettier (v2 or v3) and this plugin.  That's it!  Simple and easy.  Upgrade Prettier in the future will not break the plugin -- but if it does, it will be patched quickly.

**Comment by zuccha** [comment]
I think it would make sense for this to work with ternary operators, when an expression would fit on a single line. For example, I think this is more readable
```jsx
return (
  <div>
    {isSomeConditionIsTrue
      ? <div>This condition is true<div>
      : <div>This condition is false</div>}
  </div>
);
```
than this
```jsx
return (
  <div>
    {isSomeConditionIsTrue ? (
      <div>This condition is true</div>
    ) : (
      <div>This condition is false</div>
    )}
  </div>
);
```
That would also match with the behavior for inline strings
```jsx
return (
  <div>
    {isSomeConditionIsTrue
      ? "This condition is true"
      : "This condition is false"}
  </div>
);
```
