### ISSUE TITLE
Prettier reports a --no-config error

### ISSUE THREAD

**Issue by pmdownie** [prettier/prettier#2735]
Hi there

Getting the following error when trying to use prettier with JsPrettier in sublime text 3

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error:

Ignored unknown option: --no-config

Process finished with exit code 0

Can't seem to find how to fix this.

**Comment by azz** [comment]
Likely you're using a version of prettier prior to 1.6. Can you confirm?

**Comment by pmdownie** [comment]
yes, prettier version is 1.5.2

**Comment by azz** [comment]
Configuration file support (and the `--no-config`) flag was added in 1.6.

Older version of prettier will report a _warning_ for unknown arguments. It shouldn't be causing errors.

You should raise this over at JsPrettier: https://github.com/jonlabelle/SublimeJsPrettier

**Comment by tscizzle** [comment]
@pmdownie were you able to fix it?

**Comment by finbarr** [comment]
For me the issue was that my package.json defined a dependency on the ^1.5 version of prettier. Changing to ^1.6 and reinstalling packages fixed it.

**Comment by JohannBillar** [comment]
I upgraded my Prettier package to 1.6 globally and updated my node path in the JsPrettier user settings file to the updated package.

**Comment by marcfalk** [comment]
Simply ran ```npm upgrade prettier -g```
