### ISSUE TITLE
Support cosmiconfig rc extensions?

### ISSUE THREAD

**Issue by elektronik2k5** [prettier/prettier#2740]
Thank you for making prettier! :smile: 
The new config file option is awesome too. Can we support `.prettierrc` with extensions? Like so:

- `.prettierrc.json`
- `.prettierrc.yml`
- `.prettierrc.yaml`
- `.prettierrc.js`

It's [supported by cosmiconfig](https://github.com/davidtheclark/cosmiconfig#rcextensions) and will disambiguate the format when used with an extension.

I can make the PR :)

**Comment by josephfrazier** [comment]
This seems like a no-brainer. Feel free to make the PR :)

**Comment by azz** [comment]
I thought I'd roll with the defaults until people asked for it, so since you're asking, go ahead!
