### ISSUE TITLE
Consider avoiding / forcing consistent breaks in long, flat lists of identically-structured values.

### ISSUE THREAD

**Issue by threehams** [prettier/prettier#2743]
This was a tricky one to search for, so hopefully it's not a dupe.

Prettier has been working really well for mixed expressions or mixed types within an object, but when working with lists of items which are all identical structures, it'd be nice to avoid breaking lines unless they're excessively long (120 vs 80). This is common for configuration files.

## Current Behavior

This example is from a tslint config file:
```
{
  "ban-types": [
    true,
    [
      ["Object", "Avoid using the `Object` type. Did you mean `object`?"],
      ["Function", "Avoid using the `Function` type. Prefer a specific function type, like `() => void`."],
      ["Boolean", "Avoid using the `Boolean` type. Did you mean `boolean`?"],
      ["Number", "Avoid using the `Number` type. Did you mean `number`?"],
      ["String", "Avoid using the `String` type. Did you mean `string`?"],
      ["Symbol", "Avoid using the `Symbol` type. Did you mean `symbol`?"]
    ]
  ]
};
```

After formatting:
```
{
  "ban-types": [
    true,
    [
      ["Object", "Avoid using the `Object` type. Did you mean `object`?"],
      [
        "Function",
        "Avoid using the `Function` type. Prefer a specific function type, like `() => void`."
      ],
      ["Boolean", "Avoid using the `Boolean` type. Did you mean `boolean`?"],
      ["Number", "Avoid using the `Number` type. Did you mean `number`?"],
      ["String", "Avoid using the `String` type. Did you mean `string`?"],
      ["Symbol", "Avoid using the `Symbol` type. Did you mean `symbol`?"]
    ]
  ]
};
```

Prettier is doing exactly what it says it'll do, but it's more difficult to scan a list like this.

## Possible Approaches

I don't think I like any of these, but I guess I'll use them as a start.

For more than X items:
1. If an object/array/block of expressions all contain other objects with the exact same structure, use 120 characters as the line limit instead of 80.
2. If the items are the same structure, and a certain percentage are not broken, leave all lines unbroken.
3. Force break (or force no breaks) based on the percentage of items which are broken / unbroken.

I can hack on this to see what negative effects it might have. Maybe there's a simpler rule to apply that can feel predictable.

**Comment by lydell** [comment]
Hi! Thanks for the issue! This has been discussed in the past, most recently in #2668 (although it seems to be about JSX at a first glance, it then generalizes). Closing in favor of that one.
