### ISSUE TITLE
Unexpected token error in TypeScript Promise return type definition

### ISSUE THREAD

**Issue by karlito-who-else** [prettier/prettier#2747]
A `SyntaxError: Unexpected token` error is generated on the closing square bracket of the `Promise` constructor in the following code:

```
const myPromise = (param1: string): Promise<object[]> => new Promise<object[]>((resolve, reject) => {
```

The error is only generated when setting the return type as an array.

**Comment by azz** [comment]
cc @JamesHenry 

This looks similar-ish to #2702

**Comment by azz** [comment]
I _can_ repro [on the playground](https://prettier.io/playground/#%7B%22content%22%3A%22const%20myPromise%20%3D%20(param1%3A%20string)%3A%20Promise%3Cobject%5B%5D%3E%20%3D%3E%20new%20Promise%3Cobject%5B%5D%3E((resolve%2C%20reject)%20%3D%3E%20%7B%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D), but not locally?

```
$ git checkout 1.6.1
Previous HEAD position was 828a7b8f... docs(readme): add and sort cli options (#2700)
HEAD is now at c3506198... 1.6.1

azz at macOS in ~/code/prettier on c3506198 [$]
$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.75s.

azz at macOS in ~/code/prettier on c3506198 [$]
$ prettier test.js --parser typescript
const myPromise = (param1: string): Promise<object[]> =>
  new Promise<object[]>((resolve, reject) => {});
```

**Comment by azz** [comment]
I _can_ reproduce this on the [playground](https://prettier.io/playground/#%7B%22content%22%3A%22const%20myPromise%20%3D%20(param1%3A%20string)%3A%20Promise%3Cobject%5B%5D%3E%20%3D%3E%20new%20Promise%3Cobject%5B%5D%3E((resolve%2C%20reject)%20%3D%3E%20%7B%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D), but not locally?

```
HEAD is now at c3506198... 1.6.1

azz at macOS in ~/code/prettier on c3506198 [$]
$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.46s.

azz at macOS in ~/code/prettier on c3506198 [$]
$ node ./bin/prettier.js --parser typescript test.js
const myPromise = (param1: string): Promise<object[]> =>
  new Promise<object[]>((resolve, reject) => {});
```

**Comment by ikatyang** [comment]
It seems you're using the babylon parser on the playgroud, [typescript parser](https://prettier.io/playground/#%7B%22content%22%3A%22const%20myPromise%20%3D%20(param1%3A%20string)%3A%20Promise%3Cobject%5B%5D%3E%20%3D%3E%20new%20Promise%3Cobject%5B%5D%3E((resolve%2C%20reject)%20%3D%3E%20%7B%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) works fine to me.

**Comment by azz** [comment]
D'oh! Hadn't had :coffee: yet. 

@karlito-who-else Looks like you're also using the babylon parser, you'll need to use a file ending with `.ts` or `.tsx`, or pass the `--parser typescript` command line flag.
