### ISSUE TITLE
Weird formatting of JSX ternary (update 1.6.1)

### ISSUE THREAD

**Issue by jurosh** [prettier/prettier#2751]
After updating to version 1.6.1 (from 1.5.2) JSX formatting looks updated, but result is here.
![Diff](http://screen.jurosh.com/i15/2017_09_05_1775517141146321110.png)

I would really like to use latest version of prettier without any configuration but as you can see, it's quite weird that everything is on single line. It's really hard to read and find where parentheses ends without any indentation.

I am not sure if this was intention, or it's bug, so I would like to open discussion here.

[Link to playground](https://prettier.io/playground/#%7B%22content%22%3A%22const%20Main%3A%20React.SFC%3CIProps%3E%20%3D%20(%7B%20children%2C%20isError%2C%20isLoading%2C%20errorMessage%20%7D)%20%3D%3E%5Cn%20%3Cdiv%3E%5Cn%20%3CHeader%20%2F%3E%5Cn%20%3Cdiv%20className%3D%7Bcss.mainContentWrapper%7D%3E%5Cn%20%7BisError%5Cn%20%3F%20%3Cdiv%3E%5Cn%20%7BerrorMessage%7D%5Cn%20%3C%2Fdiv%3E%5Cn%20%3A%20%3Cdiv%3E%5Cn%20%7BisLoading%5Cn%20%3F%20%3Cdiv%3ELoading...%3C%2Fdiv%3E%5Cn%20%3A%20%3Cdiv%3E%5Cn%20%7Bchildren%7D%5Cn%20%3C%2Fdiv%3E%7D%5Cn%20%3C%2Fdiv%3E%7D%5Cn%20%3C%2Fdiv%3E%5Cn%20%3CFooter%20%2F%3E%5Cn%20%3C%2Fdiv%3E%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by lydell** [comment]
Hi! Thanks four your issue! Could you please post the code in the image as text, so we can copy-paste it? Actually, the easiest thing to do when reporting issues here is to post a link to the [online playground](https://prettier.io/playground/) with the code in it. This helps us verify your issue and debug!

**Comment by jurosh** [comment]
Hello, there is link to playground:

    https://prettier.io/playground/#{"content"%3A"const Main%3A React.SFC<IProps> %3D ({ children%2C isError%2C isLoading%2C errorMessage }) %3D>\n <div>\n <Header %2F>\n <div className%3D{css.mainContentWrapper}>\n {isError\n %3F <div>\n {errorMessage}\n <%2Fdiv>\n %3A <div>\n {isLoading\n %3F <div>Loading...<%2Fdiv>\n %3A <div>\n {children}\n <%2Fdiv>}\n <%2Fdiv>}\n <%2Fdiv>\n <Footer %2F>\n <%2Fdiv>%3B"%2C"options"%3A{"printWidth"%3A120%2C"tabWidth"%3A2%2C"singleQuote"%3Afalse%2C"trailingComma"%3A"none"%2C"bracketSpacing"%3Atrue%2C"jsxBracketSameLine"%3Afalse%2C"parser"%3A"babylon"%2C"semi"%3Atrue%2C"useTabs"%3Afalse%2C"doc"%3Afalse%2C"ast"%3Afalse}}

**Comment by suchipi** [comment]
The reason that this is happening is because your print width is set to 120; prettier tries to fit everything onto one line if it can, but will break it onto multiple lines if it won't fit.

If you change the print width to 80, you'll see that the `isError` ternary breaks onto multiple lines.
