### ISSUE TITLE
JSX ternary looks weird

### ISSUE THREAD

**Issue by vinhlh** [prettier/prettier#2752]
<img width="1242" alt="screen shot 2017-09-05 at 9 57 21 pm" src="https://user-images.githubusercontent.com/261283/30064729-412d716a-9285-11e7-9f1f-6183edc761e1.png">

[prettier.io](https://prettier.io/playground/#%7B%22content%22%3A%22const%20renderInput%20%3D%20()%20%3D%3E%20%7B%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%3Cdiv%5Cn%20%20%20%20%20%20%20%20onBlur%3D%7Bthis.onInputBlur%7D%5Cn%20%20%20%20%20%20%20%20className%3D%7B%60mdl-textfield%20mdl-js-textfield%20%24%7BclassName%7D%20%24%7Bcontent.length%20%3E%200%5Cn%20%20%20%20%20%20%20%20%20%20%3F%20'is-dirty'%5Cn%20%20%20%20%20%20%20%20%20%20%3A%20''%7D%20combo-box__input%60%7D%5Cn%20%20%20%20%20%20%3E%5Cn%20%20%20%20%20%20%20%20%3Clabel%20className%3D%5C%22mdl-textfield__label%5C%22%20htmlFor%3D%5C%22combo-box__input%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%7Blabel%7D%5Cn%20%20%20%20%20%20%20%20%3C%2Flabel%3E%5Cn%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20)%5Cn%20%20%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
This isn't an issue with jsx, but with template literals:

```js
x = `mdl-textfield mdl-js-textfield ${className} ${content.length > 0
          ? 'is-dirty'
          : ''} combo-box__input`
```

outputs

```js
x = `mdl-textfield mdl-js-textfield ${className} ${content.length > 0
  ? "is-dirty"
  : ""} combo-box__input`;

```

**Comment by lydell** [comment]
What is the expected behavior here?
