### ISSUE TITLE
[Feature Request] : prettier-standalone

### ISSUE THREAD

**Issue by ritz078** [prettier/prettier#2753]
It would be great if there is a version of prettier that can run on browser. It can be used by many REPLs. I tried figuring out a way to bundle it myself seeing the build process of docs but was stuck.

even a bit of help on that front is appreciated.

Thanks for this awesome tool 👏

**Comment by lydell** [comment]
Hi! Thanks for issue! This is already discussed in #1867. Could you read through that one and see if that gets you going? Otherwise totally feel free to keep the discussion going in #1867 (even though it is closed)!

**Comment by vjeux** [comment]
It would indeed be great if we improved our packaging story in the browser. This is something that we want but don't really have the energy to do ourselves.
