### ISSUE TITLE
Conflict with ESLint@4 "indent"

### ISSUE THREAD

**Issue by alexlrobertson** [prettier/prettier#2754]
ESLint@4 introduces new parsing of JSX blocks which results in some errors about indentation that result from using Prettier.

Prettier formats some example code like this:

```jsx
import React from 'react';

function Foo() {
    return (
        <div>
            {foo &&
            bar.qux() && (
                <div>
                    <span>Hellow</span>
                </div>
            )}
        </div>
    );
}
```

ESLint expects the code to be formatted as such:

```jsx
import React from 'react';

function Foo() {
    return (
        <div>
            {foo &&
            bar.qux() &&
            (
                <div>
                    <span>Hellow</span>
                </div>
            )}
        </div>
    );
}
```

I think the easiest and clearest solution to this is to force opening parenthesis in JSX expressions that contain JSX blocks to be forced onto a new line.

**Comment by SimenB** [comment]
You should turn off all eslint style rules when using prettier (`eslint-config-prettier`) makes it easy.
