### ISSUE TITLE
Objects in ternary has extra indent when using --use-tabs

### ISSUE THREAD

**Issue by jishaal** [prettier/prettier#2771]
**Prettier Version:** 1.6.1 

**Code**

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22const%20abc%20%3D%20props.something%5Cn%20%20%20%20%3F%20xyz%5Cn%20%20%20%20%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20prop1%3A%20a%2C%5Cn%20%20%20%20%20%20%20%20%20%20prop2%3A%20b%2C%5Cn%20%20%20%20%20%20%20%20%20%20prop3%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```js
const abc = props.something
    ? xyz
    : {
          prop1: a,
          prop2: b,
          prop3: false,
      };

```

**Expected behavior:**

The object in the ternary has the correct indentation as above JS snippet

**Actual behavior:**

We get an extra level of indentation in the object. This seems to only happen if using the `--use-tabs` option. If spaces are used, there is no issue.

```js
const abc = props.something
	? xyz
	: {
			prop1: a,
			prop2: b,
			prop3: false,
		};
```

**Comment by lydell** [comment]
That is certainly not very pretty!
