### ISSUE TITLE
CSS adds comma after @import url

### ISSUE THREAD

**Issue by torarnek** [prettier/prettier#2773]
**Prettier Version:** 1.6.1 / master

```js
@import url("responsive/gt768.css") screen and (min-width: 768px);
```

**Expected behavior:**
```js
@import url("responsive/gt768.css") screen and (min-width: 768px);
```

**Actual behavior:**
```js
@import url("responsive/gt768.css"), screen and (min-width: 768px);
```

Please see [`@import doc`](https://developer.mozilla.org/en-US/docs/Web/CSS/@import)

**Comment by gimenete** [comment]
I have the same issue. Quick way to test it:

```javascript
require('prettier').format('@import url(https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css) screen;', {parser: 'postcss'})
```

Outputs:

```css
"@import url(https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css),
  screen;
```

**Comment by lydell** [comment]
Wow, I didn't even know that people used the media-query thing of `@import`s for real! Or `@import`s at all, for that matter. One workaround (which should also be more performant) is to use `<link>` tags instead. You can also use a `/* prettier-ignore */` comment: [playground](https://prettier.io/playground/#%7B%22content%22%3A%22%2F*%20prettier-ignore%20*%2F%5Cn%40import%20url(https%3A%2F%2Fmaxcdn.bootstrapcdn.com%2Ffont-awesome%2F4.7.0%2Fcss%2Ffont-awesome.min.css)%20screen%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by gimenete** [comment]
I think the problem is here: https://github.com/prettier/prettier/blob/master/src/printer-postcss.js#L103

The structure of an @import statement is: `@import <url> <media-query>?`. For an import with media-query the node has this structure:

```
{
  after: '',
  before: '',
  type: 'media-query-list',
  value: 'url(foo.css) screen',
  sourceIndex: 0,
  nodes:
   [ Node {
       after: ' ',
       before: '',
       type: 'media-url',
       value: 'url(foo.css)',
       sourceIndex: 0 },
     Node {
       after: '',
       before: ' ',
       type: 'media-query',
       value: 'screen',
       sourceIndex: 13,
       nodes: [Array] } ] }
```

So, the first node is a `media-url` node type and the second node is a `media-query`, so I think if `n.name === "import"` the `concat()` should be called in a different way: first concat the media-url and then concat the media-query.
