### ISSUE TITLE
Weird Javascript format 

### ISSUE THREAD

**Issue by maxime1992** [prettier/prettier#2775]
**Prettier Version:** 1.6.1 / master

**Code**
```typescript
    return (valid
      ? helper.responseBody(this.currentUser)
      : helper.response(401)).map(res => res.json() as ICurrentUserBackend);
```

([playground](https://goo.gl/r5yGsg))

**Expected behavior:**
```typescript
    return (valid
      ? helper.responseBody(this.currentUser)
      : helper.response(401)
    ).map(res => res.json() as ICurrentUserBackend);
```

Or

```typescript
    return (
      valid
        ? helper.responseBody(this.currentUser)
        : helper.response(401)
    ).map(res => res.json() as ICurrentUserBackend);
```

When I was reading my code I thought this was the same instruction:  
`helper.response(401)).map(res => res.json() as ICurrentUserBackend);`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;but this, is really confusing

**Comment by azz** [comment]
This isn't specific to TypeScript.

**Comment by duailibe** [comment]
What should the output be here? Could make it match the chained calls:

```js
return (valid ? helper.responseBody(this.currentUser) : helper.response(401))
  .map(res => res.json())
  .filter(res => res.auth === "logged");
```
But if the conditional gets too long, it will break like:
```js
return (valid
  ? helper.responseBody(this.currentUser)
  : helper.responseStatus(401))
  .map(res => res.json())
  .filter(res => res.auth === "logged");
```

That would also match the style of chained logical expressions:

```js
return (valid &&
  helper.responseBody(this.currentUser) &&
  helper.responseStatus(401))
  .map(res => res.json());
```

Not quite pretty, in my opinion

**Comment by azz** [comment]
Yes that is the output I would expect.

**Comment by maxime1992** [comment]
I find this one more readable:
```typescript
    return (valid
      ? helper.responseBody(this.currentUser)
      : helper.response(401)
    ).map(res => res.json() as ICurrentUserBackend);
```

**Comment by azz** [comment]
I could be wrong, but I don't think prettier ever outputs a line starting with `).`

**Comment by maxime1992** [comment]
Ok! Well in that case I prefer @duailibe proposal
```
return (valid
  ? helper.responseBody(this.currentUser)
  : helper.response(401))
  .map(res => res.json());
```

rather than current output :)

**Comment by lydell** [comment]
@azz Here is an example of Prettier outputting a line starting with `).`: [playground](https://prettier.io/playground/#%7B%22content%22%3A%22functionCall(firstArgument%2C%20secondArgument).execute()%22%2C%22options%22%3A%7B%22printWidth%22%3A40%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by duailibe** [comment]
@lydell I prefer that too, but I found it tricky to implement if there are more calls in the chain. This is what I currently got:

```js
(a
  ? b
  : c
)
  .call()
  .call()
```
