### ISSUE TITLE
not working with JSX configuration/eslint

### ISSUE THREAD

**Issue by andy9775** [prettier/prettier#2778]
When running `prettier` with eslint and JSX it tends to convert code to a format which fails eslint

for example, it creates the following code:
```
<div className="button-container" key="container">
      <FaEdit
        onClick={() => this.onAnnouncementEdit(announcement.id)}
        size={25}
      />
</div>

```
when the expected is:
```
<div className="button-container" 
     key="container">
    <FaEdit onClick={() => this.onAnnouncementEdit(announcement.id)}
            size={25} />
</div>
```

As you can see, the `key` prop is placed on the same line as `className` and `onClick` is placed on its own line. Both of these throw errors when running through eslint.

My eslint config looks something like:

```
{
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 8,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true,
      "arrowFunctions": true,
      "classes": true,
      "spread": true,
      }
  },
   "plugins": [
    "react"
  ],
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": ["airbnb", "prettier"],
  "rules": {
      "react/jsx-max-props-per-line": [2, {"maximum": 1, "when": "always" }]
      "react/jsx-first-prop-new-line": [2, "never"], 
   }
}
```

**Comment by ikatyang** [comment]
Hi, Prettier is an opinionated code formatter, and the point of [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) is to disable all rules that conflict with Prettier, those two rules (`react/jsx-max-props-per-line` and `react/jsx-first-prop-new-line`) are also listed in [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier/blob/master/react.js).

It's recommended to not turn on those conflict rules, but if you'd still like to use those rules, you have to put `// prettier-ignore` on their previous line.

**Comment by andy9775** [comment]
I don't suppose there's a way to force prettier to format according to eslint configurations without having to place `// prettier-ignore` inside my code?

**Comment by ikatyang** [comment]
You might be interested in [prettier-eslint](https://github.com/prettier/prettier-eslint), which runs Prettier first and then ESLint fixer, but I'm not sure if those two rules have fixer.
