### ISSUE TITLE
Support graphql() fn and so make 2nd arg prettier

### ISSUE THREAD

**Issue by brikou** [prettier/prettier#2780]
It would be nice to have prettier format 2nd arg of graphql function when given arg is template literal. WDT?

BTW prettier rocks :metal: 

**Prettier Version:** 1.6.1 / master

**Code**

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22graphql(%5Cn%20%20schema%2C%5Cn%20%20%60%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20query%20(%24id%3A%20ID!)%20%7B%5Cn%20%20%20%20%20%20book(id%3A%20%24id)%20%7B%5Cn%20%20%20%20%20%20%5Ct%5Ct%5Ct%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%60%2C%5Cn%20%20undefined%2C%5Cn%20%20context%2C%5Cn%20%20%7B%20id%3A%20%5C%227ddc7f93-f040-41a3-8dcd-a7fbf9e93c58%5C%22%20%7D%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```js
// code snippet
graphql(
  schema,
  `
                query ($id: ID!) {
      book(id: $id) {
      			                  id
            }
        }
                `,
  undefined,
  context,
  { id: "7ddc7f93-f040-41a3-8dcd-a7fbf9e93c58" }
);
```

**Expected behavior:**

```js
graphql(
  schema,
  `
  query($id: ID!) {
    book(id: $id) {
      id
    }
  }
  `,
  undefined,
  context,
  { id: "7ddc7f93-f040-41a3-8dcd-a7fbf9e93c58" }
);

```

**Actual behavior:**

```js
graphql(
  schema,
  `
                query ($id: ID!) {
      book(id: $id) {
      			                  id
            }
        }
                `,
  undefined,
  context,
  { id: "7ddc7f93-f040-41a3-8dcd-a7fbf9e93c58" }
);
```

**Comment by azz** [comment]
Sure, why not 😄

**Comment by vjeux** [comment]
I'm curious, what library is making you write this?

**Comment by brikou** [comment]
@vjeux the library making me write this is a little library from the startup "facebook" (a website like "copains d'avant" but not in french).

**Comment by azz** [comment]
This one: https://www.npmjs.com/package/graphql
