### ISSUE TITLE
Feature request: allow setting to keep parenthese for single parameter methods

### ISSUE THREAD

**Issue by rmaclean** [prettier/prettier#2787]
I would like a setting which allows me to control if parentheses are kept when you have a method with a single parameter.

For example, this input
```js
const test = (dog) => {
  return woof;
};
```

would ideally remain unchanged. Currently, it changes to
```js
const test = dog => {
  return woof;
};
```

**Prettier Version:** 1.6.1 / master

**Comment by lydell** [comment]
For the record, this is already discussed in #812.

**Comment by rmaclean** [comment]
@lydell only found once I created this - thus why I closed this

**Comment by lydell** [comment]
Yeah, that’s what I guessed, but it’s still important to link to other issues because people might find this one when searching and wonder why you closed it :)
