### ISSUE TITLE
TypeScript with | and parenthesis produces broken code

### ISSUE THREAD

**Issue by Ciantic** [prettier/prettier#2790]
**Prettier Version:** 1.6.1 / master

**Code**

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22%5Cninterface%20IMessage2%20%7B%5Cn%20%20%20%20name%3A%20string%3B%5Cn%7D%5Cn%5Cninterface%20IMessage1%20%7B%5Cn%20%20%20%20name%3A%20string%3B%5Cn%7D%5Cn%5Cntype%20SortedMessage%20%3D%20(IMessage2%20%26%20%7B%20type%3A%20%5C%22message1%5C%22%20%7D)%20%7C%20(IMessage1%20%26%20%7B%20type%3A%20%5C%22message2%5C%22%20%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```ts
interface IMessage2 {
    name: string;
}

interface IMessage1 {
    name: string;
}

type SortedMessage = (IMessage2 & { type: "message1" }) | (IMessage1 & { type: "message2" });
```

**Expected behavior:**
```ts
interface IMessage2 {
  name: string
}

interface IMessage1 {
  name: string
}

type SortedMessage =
  (IMessage2 & { type: "message1" })
  | (IMessage1 & { type: "message2" });
```

**Actual behavior:**

```ts
interface IMessage2 {
  name: string
}

interface IMessage1 {
  name: string
}

type SortedMessage =
  | (IMessage2 & { type: "message1" })
  | (IMessage1 & { type: "message2" });
```

**Comment by Ciantic** [comment]
this could also be a TypeScript version issue, I was using rather old, 2.1.0

**Comment by ikatyang** [comment]
Hi, thanks for the issue. [The minimum version of TypeScript supported is 2.1.3](https://github.com/prettier/prettier#language-support) as it introduces the ability to have leading `|` (see https://github.com/Microsoft/TypeScript/pull/12386) for type definitions which prettier outputs.
