### ISSUE TITLE
Semicolon before arrow IIFE

### ISSUE THREAD

**Issue by rkurbatov** [prettier/prettier#2800]
**Prettier Version:** 1.6.1 / master

**Code**

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22(async%20()%20%3D%3E%20%7B%7D)()%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```js
(async () => {})()
```
**Actual behavior:**

Semicolon is added before IIFE if `--no-semi` param is used. Is it required here?
```js
;(async () => {})()
```

**Comment by ikatyang** [comment]
Hi, thanks for the issue. That semicolon is not required there, but it's the most consistent way to print with `--no-semi`, the rules that prettier followed to prevent problems from ASI (Automatic Semicolon Insertion) can be found in https://github.com/prettier/prettier/pull/1129#issuecomment-292243414:

> Prefix ExpressionStatements with a semicolon when they "start with" one of the following:
> - Array, +Unary, -Unary, Template String, JSXElement, Regex
> - **Any expression wrapped in parens**

And there's also related discussions in https://github.com/prettier/prettier/issues/12.
