### ISSUE TITLE
line break on code like:  aLine(veryLoooooooooooooooooooooooooooooong).short(true)

### ISSUE THREAD

**Issue by liuchong** [prettier/prettier#2801]
**Prettier Version:** 1.6.1 / master

```js
aLine(veryLoooooooooooooooooooooooooooooooooooooooooooooooooooooong).short(true)
```

**Code**

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22aLine(veryLoooooooooooooooooooooooooooooooooooooooooooooooooooooong).short(true)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

**Expected behavior:**
```js
aLine(veryLoooooooooooooooooooooooooooooooooooooooooooooooooooooong)
  .short(true)
```
**Actual behavior:**
```js
aLine(veryLoooooooooooooooooooooooooooooooooooooooooooooooooooooong).short(
  true
)
```

Is there any argument could help to make the format to be expected?
Thanks!

**Comment by lydell** [comment]
@liuchong Do you have a real world example?

**Comment by TrySound** [comment]
@lydell Promise with only one `then`. Looks confusing sometimes.
https://prettier.io/playground/#%7B%22content%22%3A%22Promise.resolve(%5B1%2C%202%2C%203%2C%204%2C%205%5D.map(String))%5Cn%20%20.then(result%20%3D%3E%20console.log(result))%5Cn%5CnPromise.resolve(%5B1%2C%202%2C%203%2C%204%2C%205%5D.map(String))%5Cn%20%20.then(result%20%3D%3E%20console.log(result)%20%7C%7C%201)%5Cn%20%20.then(result%20%3D%3E%20console.log(result)%20%7C%7C%201)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by liuchong** [comment]
@lydell Like this?
([playground](https://prettier.io/playground/#%7B%22content%22%3A%22%20expect(wrapper.containsMatchingElement(%3Cbutton%3ESubmit%20request%3C%2Fbutton%3E)).toBe(true)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

**Comment by liuchong** [comment]
@lydell Like this?
([playground](https://prettier.io/playground/#%7B%22content%22%3A%22%20expect(wrapper.containsMatchingElement(%3Cbutton%3ESubmit%20request%3C%2Fbutton%3E)).toBe(true)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```js
expect(wrapper.containsMatchingElement(<button>Submit request</button>)).toBe(true)
```
**Expected behavior:**
```js
expect(wrapper.containsMatchingElement(<button>Submit request</button>))
  .toBe(true)
```
**Actual behavior:**
```js
expect(wrapper.containsMatchingElement(<button>Submit request</button>)).toBe(
  true
);
```

**Comment by lydell** [comment]
@liuchong Thanks! That's a really good example!

**Comment by lydell** [comment]
Merging into #2522.
