### ISSUE TITLE
Feature request: optional leading comma for function parameters

### ISSUE THREAD

**Issue by Alphapage** [prettier/prettier#2805]
Hello,

I would like to have leading comma for function parameters, something like this:

function test(arg1
,arg2
,arg3) {}

instead of:

function test(arg1,
arg2,
arg3) {}

Is there a plan to support this behaviour ?

Thanks in advance for your answers.

**Comment by lydell** [comment]
Hi! Leading commas has been discussed in #1098 and it was decided not to add support for it in Prettier.
