### ISSUE TITLE
ternary in JSX attributes don't follow ternary pattern

### ISSUE THREAD

**Issue by soojeen** [prettier/prettier#2806]
ternaries in JSX attributes don't follow the same pattern as ternaries elsewhere.

**Prettier Version:** 1.6.1 / master

**Code**

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22class%20newComponent%20extends%20React.Component%20%7B%5Cn%20%20render()%20%7B%5Cn%5Ctreturn%20(%5Cn%5Ct%5Ct%3Cdiv%3E%5Cn%5Ct%5Ct%5Ct%3CSelect%5Cn%20%20%20%20%20%20%20%20%5Ct%5Ctsize%3D%7Bthis.props.templateOptions.length%20%3D%3D%3D%201%20%3F%202%20%3A%20this.props.templateOptions.length%7D%5Cn%5Ct%5Ct%5Ct%2F%3E%5Cn%5Ct%5Ct%3C%2Fdiv%3E%5Cn%20%20%20%20)%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```js
class newComponent extends React.Component {
    render() {
        return (
            <div>
                <Select
                    size={
                        this.props.templateOptions.length === 1 ? (
                            2
                        ) : (
                            this.props.templateOptions.length
                        )
                    }
                />
            </div>
        );
    }
}
```

**Expected behavior:**
```js
class newComponent extends React.Component {
    render() {
        return (
            <div>
                <Select
                    size={
                        this.props.templateOptions.length === 1
                            ? 2
                            : this.props.templateOptions.length
                    }
                />
            </div>
        );
    }
}
```
shouldn't the formatting look more like ([this](https://prettier.io/playground/#%7B%22content%22%3A%22const%20size%20%3D%20this.props.templateOptions.length%20%3D%3D%3D%201%20%3F%202%20%3A%20this.props.templateOptions.length%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

**Comment by suchipi** [comment]
This appears to be the same as https://github.com/prettier/prettier/issues/2729, which will be fixed in 1.6.2

**Comment by soojeen** [comment]
thanks! my apologies for the redundancy

**Comment by suchipi** [comment]
No worries 😄
