### ISSUE TITLE
The comment is moved inside of the parentheses with arguments

### ISSUE THREAD

**Issue by NameFILIP** [prettier/prettier#2808]
**Prettier Version:** 1.6.1

**Code**

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22function%20deserialize%20%2F*%20%3A%3A%20%3CT%3A%20Function%3E%20*%2F(%5Cn%20%20data%20%2F*%20%3A%20Buffer*%2F%2C%5Cn%20%20record%20%2F*%20%3A%20T*%2F%5Cn)%20%2F*%20%3A%20T*%2F%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```js
function deserialize /* :: <T: Function> */(
  data /* : Buffer*/,
  record /* : T*/
) /* : T*/ {}
```

**Expected behavior:**
The comment `/* :: <T: { read: (protocol: thrift.TCompactProtocol) => mixed }> */` should stay right after the function name, before the parentheses with arguments

**Actual behavior:**
The comment is moved inside of the parentheses with arguments

**Comment by azz** [comment]
Minimal repro:

**Prettier 1.7.2**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22function%20f%20%2F*%20comment*%2F(promise)%20%7B%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
function f /* comment*/(promise) {}
```

**Output:**
```jsx
function f(/* comment*/ promise) {}

```

**Comment by lydell** [comment]
Flow comment type annotations example:

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22function%20identity%2F*%3A%3A%3CT%3E*%2F(value%20%2F*%3A%20T%20*%2F)%2F*%3A%20T%20*%2F%20%7B%5Cn%20%20return%20value%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
function identity/*::<T>*/(value /*: T */)/*: T */ {
  return value;
}
```

**Output:**
```jsx
function identity(/*::<T>*/ value /*: T */) /*: T */ {
  return value;
}

```

**Comment by zyklus** [comment]
nice! Though I don't feel anonymous functions are "edge cases". I'd suggest leaving this open until that's fixed to properly track it
