### ISSUE TITLE
Seeming misindentation with bodyless arrow func

### ISSUE THREAD

**Issue by ginter** [prettier/prettier#2809]
**Prettier Version:** 1.6.1 / master

**Code**

```js
const obj = {
  key: myFunction({
    key2: (state, { payload: { roles = [] } }) =>
      roles.reduce(
        (obj, role) => ({
          ...obj,
          [role.uid]: role,
        }),
        state
      ),
      key3: (state, { payload: data }) =>
        data.roles.reduce((obj, role) => ({ ...obj, [role.uid]: role }), state),
  }),
};
```

**Expected behavior:**

Expect key2 and key3 to align

**Actual behavior:**

key3 has an extra level of indentation

**Comment by lydell** [comment]
[They do line up](https://prettier.io/playground/#{"content"%3A"const obj %3D {\n key%3A myFunction({\n key2%3A (state%2C { payload%3A { roles %3D [] } }) %3D>\n roles.reduce(\n (obj%2C role) %3D> ({\n ...obj%2C\n [role.uid]%3A role%2C\n })%2C\n state\n )%2C\n key3%3A (state%2C { payload%3A data }) %3D>\n data.roles.reduce((obj%2C role) %3D> ({ ...obj%2C [role.uid]%3A role })%2C state)%2C\n })%2C\n}%3B"%2C"options"%3A{"printWidth"%3A80%2C"tabWidth"%3A2%2C"singleQuote"%3Afalse%2C"trailingComma"%3A"none"%2C"bracketSpacing"%3Atrue%2C"jsxBracketSameLine"%3Afalse%2C"parser"%3A"babylon"%2C"semi"%3Atrue%2C"useTabs"%3Afalse%2C"doc"%3Afalse%2C"ast"%3Afalse}}). Am I missing something?

**Comment by ginter** [comment]
hm so weird, sorry. must have been something weird going on in vim.
