### ISSUE TITLE
Private Class Fields

### ISSUE THREAD

**Issue by bradennapier** [prettier/prettier#2810]
**Prettier Version:** 1.6.1 / master

**Code**

([playground](https://prettier.io/playground/#.....))

```js
class Test {
  #foo = undefined 
  constructor() {
    this.#foo = 'hi'
  }
} 
```

**Expected behavior:**

It works with private fields syntax 

I know its a proposal only so understandable - but would be nice to support and seems like it shouldn't be very hard since it would be jsut allowing the hash.

**Actual behavior:**

26/Users/bradennapier/.atom/packages/prettier-atom/node_modules/loglevel-colored-level-prefix/dist/in…:54 prettier-eslint [ERROR]: prettier formatting failed due to a prettier error

**Comment by existentialism** [comment]
@bradennapier I actually have a branch ready to go for private class fields (and a separate one for methods, but was going to wait on that a bit). Just waiting for our upcoming next Babylon beta release!

**Comment by bradennapier** [comment]
yay!  Thanks!
