### ISSUE TITLE
(maybe) suboptimal line breaking with || conditioned functions

### ISSUE THREAD

**Issue by 0x24a537r9** [prettier/prettier#2836]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20genTrue%20%3D%20async%20(packageName)%20%3D%3E%20true%3B%5Cn%5Cnasync%20function%20foo()%20%7B%5Cn%20%20const%20isAppUpdated%20%3D%20await%20(options.isAppUpdated%20%7C%7C%20LaunchAPI._impl.isAppUpdated%20%7C%7C%20LaunchAPI.isAppUpdated%20%7C%7C%20genTrue)(packageName)%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
const genTrue = async (packageName) => true;

async function foo() {
  const isAppUpdated = await (options.isAppUpdated || LaunchAPI._impl.isAppUpdated || LaunchAPI.isAppUpdated || genTrue)(packageName);
}
```

**Output:**
```jsx
const genTrue = async packageName => true;

async function foo() {
  const isAppUpdated = await (options.isAppUpdated ||
    LaunchAPI._impl.isAppUpdated ||
    LaunchAPI.isAppUpdated ||
    genTrue)(packageName);
}

```

**Expected behavior:**
Not sure, tbh. I prefer the following alternatives, but I'm not sure how consistent they are with the rest of prettier style:

```jsx
const genTrue = async packageName => true;

async function foo() {
  const isAppUpdated = await (
    options.isAppUpdated ||
    LaunchAPI._impl.isAppUpdated ||
    LaunchAPI.isAppUpdated ||
    genTrue)(packageName);
}

```
or
```jsx
const genTrue = async packageName => true;

async function foo() {
  const isAppUpdated = await (
    options.isAppUpdated ||
    LaunchAPI._impl.isAppUpdated ||
    LaunchAPI.isAppUpdated ||
    genTrue
  )(packageName);
}

```

**Comment by 0x24a537r9** [comment]
To clarify, all of the isAppUpdate properties are async functions of the same shape as `genTrue`, so the `||`s are just finding the first one that's defined, then awaiting the result of calling it.

**Comment by azz** [comment]
This will look a lot cleaner if you extract it into two statements.

```
async function foo() {
  const isAppUpdated =
    options.isAppUpdated ||
    LaunchAPI._impl.isAppUpdated ||
    LaunchAPI.isAppUpdated ||
    genTrue;

  const packageIsUpdated = await isAppUpdated(packageName);
}
```

**Comment by thorn0** [comment]
Works as expected since version 1.19.
