### ISSUE TITLE
HTML comments get intended per every save

### ISSUE THREAD

**Issue by codeofsumit** [prettier/prettier#2838]
hey there, I use prettier in vscode. Whenever I press save, HTML comments get intended one more. So when I save 10 times, this happens:
![html comment](https://user-images.githubusercontent.com/2399810/30504279-1c023d94-9a6e-11e7-8e48-00e139de7489.gif)

**Comment by azz** [comment]
Prettier doesn't support html (yet, see #1882 ). Are you using a different formatter?

**Comment by codeofsumit** [comment]
no, but this is in a `.vue` file and prettier supports the javascript and css part in it. Could that be related?

**Comment by azz** [comment]
Prettier has some capability to print vue components, but it's not officially release or supported yet. Work is in progress, see #2097 for tracking.
