### ISSUE TITLE
`VERIFY_ALL_PARSERS=1 jest` fails – what is it and what should we do about it?

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#2845]
Today I stumbled upon this environment variable used in the tests:

https://github.com/prettier/prettier/blob/ed67690925ecd7172eacfcf7ec9f3145ef6571f6/tests_config/run_spec.js#L11-L14

So I tried it out. Here's the result:

```
Test Suites: 167 failed, 574 passed, 741 total
Tests:       218 failed, 3134 passed, 3352 total
```

I also tried removing "graphql" from ALL_PARSERS, since it was not there originally:

```
Test Suites: 98 failed, 643 passed, 741 total
Tests:       101 failed, 3114 passed, 3215 total
```

This was added by @ChristianHersevoort in commit 04c959d687ee3ebe680fbc56f6b7f4532db6d0c2 (#1087).

**Comment by azz** [comment]
There are a lot of tests that are specific to one parser.

* There are a lot of flow and typescript tests that will fail without their respective parser.
* There are a lot of proposals that have syntax only supported by babylon.
* All parsers other than graphql will fail on graphql tests, same applies for json.
