### ISSUE TITLE
package.json should match npm/yarn output

### ISSUE THREAD

**Issue by ericclemmons** [prettier/prettier#2849]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%2F%2F%20This%20first%20line%20exists%20simply%20for%20the%20demo.%5Cn%2F%2F%20package.json%20should%20be%20bypassed%20or%20use%20JSON.stringify(json%2C%20null%2C%202)%5Cn%2F%2F%20so%20that%20it%20isn't%20formatted%20differently%20than%20npm%2Fyarn.%5Cnmodule.exports%20%3D%20%5Cn%7B%5Cn%20%20%5C%22workspaces%5C%22%3A%20%5B%5Cn%20%20%20%20%5C%22examples%2F*%5C%22%2C%5Cn%20%20%20%20%5C%22packages%2F*%5C%22%5Cn%20%20%5D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```json
{
  "workspaces": [
    "examples/*",
    "packages/*"
  ]
}
```

**Output:**
```json
{
  workspaces: ["examples/*", "packages/*"]
};

```

**Expected behavior:**

`package.json` should match the output of npm/yarn:

```js
JSON.stringify(code, null, 2)
```

Because `package.json` is mutated by npm/yarn (compared to `.babelrc`), this file should be bypassed by prettier.

_Note: I learned of this behavior while using `prettier-atom`._

**Comment by azz** [comment]
I'd say just put package.json In your `.prettierignore` file.

**Comment by ericclemmons** [comment]
I _guess_, if you like 1-line code changes ;) ⛳️

**Comment by lydell** [comment]
I think I agree with @azz.

**Comment by azz** [comment]
We're unlikely going to be formatting files based on the filename, and since there's a simple workaround lets close this one.

**Comment by mrm1ck** [comment]
Is this actually a mining machine and is it going to work and why have youse not let me release it on my machine yet but now I know about the Dao and withdraw only wallet I brought in 2012 are you going to give me the mining with a good percentage of what I actually own anyway or do I just go through my old hard drive from that time and find the wallet and use the password that I remember and withdraw it all or is this mining machine in aid of me getting a percentage and developers also getting some out of it which I can handle as long as you aren't ripping me off totally

**Comment by aboyton** [comment]
There's another alternative, `yarn` and `npm` should be using `prettier` to format `package.json` 😛

**Comment by mrm1ck** [comment]
So is there a manual anywhere that explains which order and what files I need to change to run this project it's a very complex and almost daunting task for me and also I believe I may have downloaded some incorrect components also. So any help to steer me in the right direction would be more then appreciated especially as I can't seem to find anyone around me that has any knowledge of this at all. I asked a sister last night and it overwhelmed her but she usually only doing super computers and servers and terminals for large firms and banks. So all guidance will be very welcome and appreciated thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by suchipi** [comment]
Hi @mrm1ck,

Please see the [Editor Integration](https://github.com/prettier/prettier#editor-integration) section in the README.

Also, in the future, please create a new issue for questions instead of commenting on an unrelated issue.
