### ISSUE TITLE
symbol is not a valid type, when it is?

### ISSUE THREAD

**Issue by maraisr** [prettier/prettier#2851]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22function%20test(abc%3A%20Map%3Csymbol%2C%20string%3E)%20%7B%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Atrue%7D%7D)
```sh
--parser typescript
--single-quote
--tab-width 4
--use-tabs
```

**Input:**
```tsx
function test(abc: Map<symbol, string>) {}
```

**Output:**
```tsx
Error: unknown type: undefined
```

**Expected behaviour:**
Things should lint correctly - So apparently, `symbol` is not a valid type, but TypeScript doesn't seem to complain. `Symbol` fixes the issue.

**Comment by ikatyang** [comment]
Thanks for the report. I've opened eslint/typescript-eslint-parser#385 to fix this in our dependency.

As a temporary workaround you can put `// prettier-ignore` on the previous line.

```diff
+// prettier-ignore
function test(abc: Map<symbol, string>) {}
```

**Comment by maraisr** [comment]
Thanks for that @ikatyang - can't wait :)
