### ISSUE TITLE
Comment gets moved away

### ISSUE THREAD

**Issue by cilice** [prettier/prettier#2853]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20API%20%3D%20%7B%5CnloadLocale%3A%20(locale%3A%20string)%20%3D%3E%20%5Cn%20%20%2F%2F%20%24FlowFixMe%5Cn%20%20import(%2F*%20webpackChunkName%3A%20%5C%22locale%2F%5Brequest%5D%5C%22%20*%2F%20%60..%2F..%2Fpublic%2Fstatic%2Flocales%2F%24%7Blocale%7D.json%60)%2C%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser flow
```

**Input:**
```jsx
const API = {
loadLocale: (locale: string) => 
  // $FlowFixMe
  import(/* webpackChunkName: "locale/[request]" */ `../../locales/${locale}.json`),
}
```

**Output:**
```jsx
const API = {
  loadLocale: (locale: string) =>
    import(// $FlowFixMe
    /* webpackChunkName: "locale/[request]" */ `../../locales/${locale}.json`)
};

```

**Expected behavior:**
```jsx
const API = {
  loadLocale: (locale: string) =>
    // $FlowFixMe
    import(/* webpackChunkName: "locale/[request]" */ `../../locales/${locale}.json`)
};

```

**Comment by lydell** [comment]
This is certainly unexpected behavior. Possibly a side effect of #2748.

A few related questions:

- Does Flow, webpack or both break because of the moved comment?
- Why do you need `$FlowFixMe` there in the first place?

**Comment by cilice** [comment]
Hey @lydell 

Flow, at least currently in 0.52 that we use (we haven't got around to update it to 0.54.1 yet), doesn't understand `import` with variables, only static paths work. To ignore this, we added `// $FlowFixMe` to suppress the message.

So flow does break, because the comment is always moved this way after formatting and will throw errors about import.

**Comment by vjeux** [comment]
You can add `// prettier-ignore` to get you unblocked in the meantime:

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20API%20%3D%20%7B%5Cn%20%20%2F%2F%20prettier-ignore%5Cn%20%20loadLocale%3A%20(locale%3A%20string)%20%3D%3E%20%5Cn%20%20%20%20%2F%2F%20%24FlowFixMe%5Cn%20%20%20%20import(%2F*%20webpackChunkName%3A%20%5C%22locale%2F%5Brequest%5D%5C%22%20*%2F%20%60..%2F..%2Fpublic%2Fstatic%2Flocales%2F%24%7Blocale%7D.json%60)%2C%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser flow
```

**Input:**
```jsx
const API = {
  // prettier-ignore
  loadLocale: (locale: string) => 
    // $FlowFixMe
    import(/* webpackChunkName: "locale/[request]" */ `../../public/static/locales/${locale}.json`),
}
```

**Output:**
```jsx
const API = {
  // prettier-ignore
  loadLocale: (locale: string) => 
    // $FlowFixMe
    import(/* webpackChunkName: "locale/[request]" */ `../../public/static/locales/${locale}.json`)
};

```

**Comment by vjeux** [comment]
Adding `{}` would also work:

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20API%20%3D%20%7B%5Cn%20%20loadLocale%3A%20(locale%3A%20string)%20%3D%3E%20%7B%5Cn%20%20%20%20%2F%2F%20%24FlowFixMe%5Cn%20%20%20%20import(%2F*%20webpackChunkName%3A%20%5C%22locale%2F%5Brequest%5D%5C%22%20*%2F%20%60..%2F..%2Fpublic%2Fstatic%2Flocales%2F%24%7Blocale%7D.json%60)%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser flow
```

**Input:**
```jsx
const API = {
  loadLocale: (locale: string) => {
    // $FlowFixMe
    import(/* webpackChunkName: "locale/[request]" */ `../../public/static/locales/${locale}.json`)
  }
}
```

**Output:**
```jsx
const API = {
  loadLocale: (locale: string) => {
    // $FlowFixMe
    import(/* webpackChunkName: "locale/[request]" */ `../../public/static/locales/${locale}.json`);
  }
};

```

**Comment by vlad-zhukov** [comment]
Not sure if related but I've got a similar problem:

__Prettier 1.7.0__
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20API%20%3D%20%7B%5Cn%20%20loader%3A%20()%20%3D%3E%20import('.%2Ftest'%20%2F*%20webpackChunkName%3A%20%5C%22test%5C%22%20*%2F)%2C%5Cn%7D%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

__Input:__

```js
const API = {
  loader: () => import('./test' /* webpackChunkName: "test" */),
};
```

__Output:__

```js
const API = {
  loader: (/* webpackChunkName: "test" */) => import("./test")
};
```

**Comment by lydell** [comment]
@vlad-zhukov Good find!

In your case, the workaround is easier: Just flip the order of the comment and the string.

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20API%20%3D%20%7B%5Cn%20%20loader%3A%20()%20%3D%3E%20import(%2F*%20webpackChunkName%3A%20%5C%22test%5C%22%20*%2F%20%27.%2Ftest%27)%2C%5Cn%7D%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser flow
```

**Input:**
```jsx
const API = {
  loader: () => import(/* webpackChunkName: "test" */ './test'),
};
```

**Output:**
```jsx
const API = {
  loader: () => import(/* webpackChunkName: "test" */ "./test")
};

```

**Comment by markkemper1** [comment]
I have a similar issue... 

Input: 

```javascript
const api = {
  hello() {
    console.log("hello");
    api.count++;
    return api;
  },
  count: 0
};

api.hello()
  //adding a comment here so I can force a line break
  .hello()
  //another line break force
  .count;
```


Formatted to : 

```javascript
const api = {
  hello() {
    console.log("hello");
    api.count++;
    return api;
  },
  count: 0
};

//another line break force
api.hello()
  //adding a comment here so I can force a line break
  .hello().count;

```

**Comment by jackyho112** [comment]
I will try looking into this!
