### ISSUE TITLE
feedback about prettier-stylelint

### ISSUE THREAD

**Issue by hugomrdias** [prettier/prettier#2854]
Hi guys, 
i made a new tool to integrate prettier and stylelint, i would like to ask the prettier community for feedback and also leave here some of my findings.

[prettier-stylelint](https://github.com/hugomrdias/prettier-stylelint)

@lydell asked me [here](https://github.com/stylelint/stylelint/issues/2898#issuecomment-329977775) about why a made a new tool and not a stylelint plugin and also about prettier css formatting. 

First this was about building a tool for my needs and **learning** (cli, vscode extension, cosmiconfig, etc etc).

Now answering @lydell all started with me setting up vscode with stylelint, stylefmt, prettier you guys know the drill. Basically i ended up find it was kind hard to have the same setup i had for js (prettier extension with eslintIntegration === true **done** everything works perfect each time a press `ctrl+s`)

the first piece of code i noticed didnt play well with prettier and my stylelint config was : 
```css
/* prettier version */
background: linear-gradient(rgba(255, 255, 255, 0), white 70%) 0 100%,
        radial-gradient(
                farthest-side at 50% 100%,
                rgba(0, 0, 0, 0.2),
                rgba(0, 0, 0, 0)
            )
            0 100%;
/* stylelint  approved */
background:
        linear-gradient(rgba(255, 255, 255, 0), white 70%) 0 100%,
        radial-gradient(
            farthest-side at 50% 100%,
            rgba(0, 0, 0, 0.2),
            rgba(0, 0, 0, 0)
        ) 0 100%;
```

The prettier version has indentation problems and conflicts with [declaration-colon-newline-after](https://stylelint.io/user-guide/rules/declaration-colon-newline-after/) = `"always-multi-line"`

the second one was : 

```css
/* prettier */
--font-family-sans: 'Open Sans', -apple-system, BlinkMacSystemFont,
        'Segoe UI', Roboto, 'Noto Sans', Ubuntu, 'Helvetica Neue', sans-serif;

/* stylelint says if you go multi line go all the way   */
--font-family-sans:
        'Open Sans',
        -apple-system,
        BlinkMacSystemFont,
        'Segoe UI',
        Roboto,
        'Noto Sans',
        Ubuntu,
        'Helvetica Neue',
        sans-serif;
```

This one is questionable which is better its all about prettier max-line-length approach. But in the first example the stylelint version is clearly better.    
So my reasoning was i'm gonna do something that allows me to learn more about these tools and examples like these can be improved in prettier or stylelint. Also as stylelint adds more fixable rules people have the choice to change specific things they don't like in the opinionated formatting of prettier.

So basically right now i have a simple api, cli, stylelint config (to disable conflicting non fixable rules) and a [PR](https://github.com/prettier/prettier-vscode/pull/218) to the prettier-vscode extension. Some stuff still needs to be improved mostly on the stylelint side but its working. 

During the development i went through a lot of css code and all the stylelint stylistic rules, and found a couple of quirks on both sides which i already reported. 
Also and perhaps the most important findings are some whitespace stylelint rules that prettier doesn't account for. So i'm gonna share below those rules and hopefully this is valuable info to improve prettier.

 Please check the disabling config [here](https://github.com/hugomrdias/prettier-stylelint/blob/master/config.js) and look for the comments.

The rules are: 

- `function-whitespace-after` [link](https://stylelint.io/user-guide/rules/function-whitespace-after/)
- `selector-attribute-operator-space-after` [link](https://stylelint.io/user-guide/rules/selector-attribute-operator-space-after/) 
- `selector-attribute-operator-space-before` [link](https://stylelint.io/user-guide/rules/selector-attribute-operator-space-before/#selector-attribute-operator-space-before) 
- `media-feature-range-operator-space-after` [link](https://stylelint.io/user-guide/rules/media-feature-range-operator-space-after/#media-feature-range-operator-space-after) 
- `media-feature-range-operator-space-before` [link](https://stylelint.io/user-guide/rules/media-feature-range-operator-space-before/#media-feature-range-operator-space-before)
- `comment-whitespace-inside` [link](https://stylelint.io/user-guide/rules/comment-whitespace-inside/#comment-whitespace-inside)

**Comment by lydell** [comment]
Nice. So, to sum up, you've made prettier-eslint but for stylelint. 👍 Feel free to send a PR if you want prettier-stylelint in the "Related project" section of the readme.

Note that the CSS support in Prettier is far from done. If you find any bugs or ugly formatting, totally feel free to open issues :)

**Comment by vjeux** [comment]
For the first one, it looks like a bug that can be fixed.
For the second one, we actually started expanding everything but this was the most complained about thing so we now use a "fill" strategy where we put as much as possible within a single line.

**Comment by hugomrdias** [comment]
Consider looking at the rules at the bottom to further improve CSS support, in my testing prettier didn't touch the white space related to those rules.
