### ISSUE TITLE
CLI doesn't find config file .yaml/.yml/.json/.js

### ISSUE THREAD

**Issue by cmalard** [prettier/prettier#2861]
**Prettier 1.7.0**
Hello there, running `prettier --find-config-path somefile.js` only works for:
- `.prettierrc`
- `prettier.config.js`

It doesn't work for `.prettierrc.(yaml|yml|json|js)`

**Comment by lydell** [comment]
Support for .yaml/.yml/.json/.js was added #2749 a few days ago, and hasn't been released yet. Unfortunately, the readme is for the current master branch, not for the latest Prettier release, which always creates confusion.
