### ISSUE TITLE
Add insertPragma option

### ISSUE THREAD

**Issue by samouri** [prettier/prettier#2864]
With the merge of https://github.com/prettier/prettier/pull/2772 and the release of [Prettier 1.7](https://github.com/prettier/prettier/releases/tag/1.7.0), Prettier has added an option that allows you to specify that it should only format files with a 'prettier' or 'format' docblock.

The feature was probably inspired by the post about [Facebook's adoption strategy](https://github.com/prettier/prettier/releases/tag/1.3.0).  

There are really two sides to the pragma coin though.  Prettier needs to be able to not only recognize when a file has the pragma, but should also have an option to prepend a properly formatted pragma into a pragma-less file during format.

I've essentially already implemented this feature for WordPress's fork of Prettier called [calypso-prettier](https://github.com/Automattic/calypso-prettier/pull/6).  I'll try taking a stab at this and maybe if people think its a good idea it can be included into  Prettier 1.8.

New option name: ~~`--prependPragma`~~ `insertPragma`
Docblock format: [jest-docblock.print()](https://github.com/facebook/jest/tree/master/packages/jest-docblock#print-comments-string-pragmas-key-string-string--string)

**Comment by vjeux** [comment]
Yeah, this sounds like a good idea, we have a script to do that internally.

**Comment by azz** [comment]
How would you handle the case where there is already a top level doc block? I've seen some code that looks like 

```
/** @flow */
/**
 * Legal...
 */
```

Would you append to the flow comment? And if so, how will you prevent adding it to the legal doc block (maybe that's a non issue)?

**Comment by vjeux** [comment]
What we do is to put * @flow as the last line of a multi-line docblock which works for fb. But I have no idea how people write their docblocks outside :p
