### ISSUE TITLE
Unwanted Formatting

### ISSUE THREAD

**Issue by bhargavjoshi** [prettier/prettier#2868]
I am calculating 1% of the price and adding/subtracting it to the price.  but prettier is removing the brackets and hence the calculation is wrong.

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22let%20priceUpperBound%20%3D%20this.state.price%20%2B%20((this.state.price%20*%201)%20%2F%20100)%3B%5Cnlet%20priceLowerBound%20%3D%20this.state.price%20-%20((this.state.price%20*%201)%20%2F%20100)%3B%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A120%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22es5%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--print-width 120
--single-quote
--tab-width 4
--trailing-comma es5
```

**Input:**
```jsx
let priceUpperBound = this.state.price + ((this.state.price * 1) / 100);
let priceLowerBound = this.state.price - ((this.state.price * 1) / 100);
```

**Output:**
```jsx
let priceUpperBound = this.state.price + this.state.price * 1 / 100;
let priceLowerBound = this.state.price - this.state.price * 1 / 100;
```

**Expected behavior:**
```jsx
let priceUpperBound = this.state.price + ((this.state.price * 1) / 100);
let priceLowerBound = this.state.price - ((this.state.price * 1) / 100);
```

**Comment by duailibe** [comment]
This is actually the expected behavior since prettier doesn't print unnecessary parens (with some exceptions). In this case, the `*` and `/` have a higher precedence than `+` and `-` so it's not necessary to output parens.

I don't understand what you mean by "the calculation is wrong", since it's not. The prettier output is equivalent to the input.
