### ISSUE TITLE
Prettier: command not found

### ISSUE THREAD

**Issue by cmendezco** [prettier/prettier#2869]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22Charlie%40LAPTOP-I1MN5SLU%20MINGW64%20~%2Fcomplete-intro-to-react%2Fnode_modules%20(start)%5Cn%24%20yarn%20global%20add%20prettier%5Cnyarn%20global%20v1.0.2%5Cn%5B1%2F4%5D%20Resolving%20packages...%5Cn%5B2%2F4%5D%20Fetching%20packages...%5Cn%5B3%2F4%5D%20Linking%20dependencies...%5Cn%5B4%2F4%5D%20Building%20fresh%20packages...%5Cnsuccess%20Installed%20%5C%22prettier%401.7.0%5C%22%20with%20binaries%3A%5Cn%20%20%20%20%20%20-%20prettier%5CnDone%20in%202.48s.%5Cn%5CnCharlie%40LAPTOP-I1MN5SLU%20MINGW64%20~%2Fcomplete-intro-to-react%2Fnode_modules%20(start)%5Cn%24%20prettier%20-v%5Cnbash%3A%20prettier%3A%20command%20not%20found%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
Charlie@LAPTOP-I1MN5SLU MINGW64 ~/complete-intro-to-react/node_modules (start)
$ yarn global add prettier
yarn global v1.0.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "prettier@1.7.0" with binaries:
      - prettier
Done in 2.48s.

Charlie@LAPTOP-I1MN5SLU MINGW64 ~/complete-intro-to-react/node_modules (start)
$ prettier -v
bash: prettier: command not found

```

**Output:**
```jsx
SyntaxError: Unexpected token, expected ; (1:8)
> 1 | Charlie@LAPTOP-I1MN5SLU MINGW64 ~/complete-intro-to-react/node_modules (start)
    |        ^
  2 | $ yarn global add prettier
  3 | yarn global v1.0.2
  4 | [1/4] Resolving packages...
```

**Comment by cmendezco** [comment]
Hi, I am trying to use prettier, I installed it globally but when I run the command "prettier" it gives me error.

Any help appreciate.

Thanks!

**Comment by cmendezco** [comment]
I solved using npm instead of yarn. 

$ npm install -g prettier

Sorry about this.

Thanks anyway.

**Comment by azz** [comment]
I have also noticed this when doing global installs with yarn using MINGW64 fwiw. Might be this issue: https://github.com/yarnpkg/yarn/issues/2224

**Comment by BrendanBerkley** [comment]
I had the same problem. Installing with sudo fixed it for me.

**Comment by stefenphelps** [comment]
same problem here. sudo ftw
