### ISSUE TITLE
prettier seems not to respect package.json

### ISSUE THREAD

**Issue by bebbi** [prettier/prettier#2871]
Despite recognizing the presence of a `prettier` key, prettier doesn't appear to respect some `package.json` settings. Specifically, I've tried `singleQuote` and `semi`.

The issue was first filed under [sublime prettier plugin](https://github.com/jonlabelle/SublimeJsPrettier/issues/74) but appears to be a prettier issue.

An example `package.json` file, prettier version (1.7.0) and command are located [in this comment](https://github.com/jonlabelle/SublimeJsPrettier/issues/74#issuecomment-331060699):
This reproduces the issue for the `singleQuote` key.

**Prettier 1.7.0**
ok

**Input:**
any js file

**Output:**
js file formatted with double quotes (all strings, not just jsx)

**Expected behavior:**
js file formatted with single quotes

**Comment by lydell** [comment]
To clarify, the problem here is that `prettier --config package.json` fails to read options from package.json. This has already been reported in #2704 and has been fixed, but not released yet. Thanks for the report!
