### ISSUE TITLE
SCSS %placeholder case unexpectedly modified

### ISSUE THREAD

**Issue by nrako** [prettier/prettier#2872]
**Prettier 1.7.0**
Prettier **CSS**
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
// code snippet
%rightIcon {
  background-position: center;
  //...
}
```

**Output:**
```jsx
// code snippet
%righticon {
  background-position: center;
  //...
}
```

**Expected behavior:**
SCSS `%placeHolder` are case sensitive and shouldn't' be changed.

**Comment by lydell** [comment]
Nice find! I totally forgot about Sass placeholder selectors when implementing the lowercasing stuff.

**Comment by nrako** [comment]
wow awesome, thanks for the fast response @lydell!
