### ISSUE TITLE
Still Breaks HTML 

### ISSUE THREAD

**Issue by bradennapier** [prettier/prettier#2875]
I didnt use the template because this bug doesnt work with prettier directly  Not sure what is going on really since I was told prettier ignores html files.  However, it is not the actual case it would seem.

This could be a `prettier-atom` issue - but either way its pretty annoying one!

Essentially with my "index.html" template, I have a javascript that looks like this:

```js
  <script>
    {
  const scripts = [];

  // Dynamically insert the DLL script in development env in the
  // renderer process
  if (process.env.NODE_ENV === 'development') {
    scripts.push('../dll/renderer.dev.dll.js');
  }

  // Dynamically insert the bundled app script in the renderer process
  const port = process.env.PORT || 1212;
  scripts.push(
    (process.env.HOT)
      ? 'http://localhost:' + port + '/dist/renderer.dev.js'
      : './dist/renderer.prod.js'
  );
  document.write(
    scripts
      .map(script => '<script async src="' + script + '"><\/script>')
      .join('')
  );
}
</script>
```

If I save this file with prettier-atom turned on:

![image](https://user-images.githubusercontent.com/15365418/30702479-eac0515c-9ea1-11e7-9fb7-f7bc1cca35d9.png)

It then turns it into:

```js
<script>
    {
  const scripts = [];

  // Dynamically insert the DLL script in development env in the
  // renderer process
  if (process.env.NODE_ENV === 'development') {
    scripts.push('../dll/renderer.dev.dll.js');
  }

  // Dynamically insert the bundled app script in the renderer process
  const port = process.env.PORT || 1212;
  scripts.push(
    process.env.HOT
      ? `http://localhost:${port}/dist/renderer.dev.js`
      : './dist/renderer.prod.js',
  );
  document.write(scripts.map(script => `<script async src="${script}"></script>`).join(''));
}
</script>
```

This is an error as it says "unexpected template literal".

Toggling prettier off before I do anything fixes the issue.

**Comment by bradennapier** [comment]
I just edited the scopes and removed text.html.basic and it does fix it so it doesnt format it... but it would be nice to have it work for that.  `prettier-atom` has this on by default but it does appear it doesnt work at this time in a way that is compatible.

**Comment by lydell** [comment]
This has to be debugged starting from the prettier-atom side (where the bug likely is). Please open an issue on prettier-atom, and come back if it turned out to be a problem with Prettier after all! :)

**Comment by suchipi** [comment]
Prettier would not change your single-quoted strings into template literals, so this may be an eslint rule, if you are using the prettier eslint integration.
