### ISSUE TITLE
Playgrounds without content show debug panes on initial page load

### ISSUE THREAD

**Issue by jakegavin** [prettier/prettier#2881]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Current Playground:**
Includes AST, Doc, and Second Format panes on initial page load.
![image](https://user-images.githubusercontent.com/5965895/30765368-3f1c8524-9fa4-11e7-8aa1-9d164270f695.png)

**Expected Playground:**
Does not include AST, Doc, and Second Format panes on initial page load. 
![30765391-53c53cfa-9fa4-11e7-9f3a-6a9ebeb79907](https://user-images.githubusercontent.com/5965895/30765447-8ff6c770-9fa4-11e7-836e-b1d8688ba0a2.png)

**Cause:**
The playground [HTML includes elements](https://github.com/prettier/prettier/blob/master/website/pages/playground/index.html#L323-L334) for AST, Doc, and Second Format panes. During `window.onload`, the [editor value is set](https://github.com/prettier/prettier/blob/master/website/static/playground.js#L138) using the content from `state`. When this happens, the on change event listener calls `formatAsync` which [sets the display](https://github.com/prettier/prettier/blob/master/website/static/playground.js#L261-L265) value for these panes to `none`, according to the options. However, if the playground content is empty, `inputEditor.setValue` is called with an empty string `""` and the change event doesn't fire. Without the change event, the display value for the AST, Doc, and Second Format panes never get set to `none` so they don't disappear until the user types something or changes a setting. 

**Proposed Solution:**
If you willing to review a fix, I'd like to submit a PR for this. I'd extract [this code](https://github.com/prettier/prettier/blob/master/website/static/playground.js#L261-L265), which sets the display values, into its own function. Then I'd call that function both during `formatAsync` and [`window.onload`](https://github.com/prettier/prettier/blob/master/website/static/playground.js#L88) so that it always updates the pane display values on the initial page load. 

Thanks for your work on Prettier! It's an awesome library.

**Comment by azz** [comment]
Thanks for the detailed report. If you want to send a fix, that would be awesome!
