### ISSUE TITLE
Prettier breaks with interpolation and complex CSS selector

### ISSUE THREAD

**Issue by brikou** [prettier/prettier#2883]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22export%20const%20foo%20%3D%20css%60%5Cn%26.foo%20.%24%7Bbar%7D%3A%3Abefore%2C%26.foo%5Bvalue%3D%5C%22hello%5C%22%5D%20.%24%7Bbar%7D%3A%3Abefore%20%7B%5Cn%5Ctposition%3A%20absolute%3B%5Cn%7D%5Cn%60%3B%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser typescript
--tab-width 4
```

**Input:**
```tsx
export const foo = css`
&.foo .${bar}::before,&.foo[value="hello"] .${bar}::before {
	position: absolute;
}
`;

```

**Output:**
```txt
Error: Error: Couldn't insert all the expressions
```

**Expected behavior:**

```tsx
export const foo = css`
    &.foo .${bar}::before,
    &.foo[value="hello"] .${bar}::before {
        position: absolute;
    }
`;
```
If I replace `before,&` by `before, &` (space before `&`), it works but is not pretty...

Thank you to look at this :D you are wonderful!

**Comment by brikou** [comment]
Here is another example https://prettier.io/playground/#%7B%22content%22%3A%22export%20const%20foo%20%3D%20css%60%5Cna.%24%7Bbar%7D%3Afocus%2Ca.%24%7Bbar%7D%3Ahover%20%7B%5Cn%20%20color%3A%20red%3B%5Cn%7D%5Cn%60%3B%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D

**Comment by brikou** [comment]
another example, this one iis really anoying because no workaround can be applied (like adding a space)

https://prettier.io/playground/#%7B%22content%22%3A%22export%20const%20global%20%3D%20css%60%5Cnbutton.%24%7Bfoo%7D.%24%7Bbar%7D%20%7B%5Cn%20%20color%3A%20%23fff%3B%5Cn%7D%5Cn%60%3B%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D

**Comment by brikou** [comment]
Thanks @lydell for updating comments

**Comment by fisker** [comment]
new Error

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDMII8BeAoogAwB0oAyAOnMrYBJgAjAIbYAvkiR845bHAA07TgG0AbgIA2AVzhVGIABZxVqiDoC6eHvyGjxknHDzBmjGFiIBLGG+hI8AvkQgNeABuZmFmemCQGRAIDE9oImRQIWwIAHcABSEEJJQBJQg3ABNokD5sATAAazgYAGUMKrcoAHNkGGxNGN0YAFtVAHVdDzgiJrA4etyPNyUPAE9kcDoylqI4XEzK1r6BZFI1DZiAKyI0ACFKmrr6gT64ABkWuAOj2RAztHqW1tU4ACK6gg8DeqmOICa2A22GWMAWGDGYGwbniZQwKNggxKMF0yAAHAAGGIYiAbQaVDDLDFjTZKV4xACOwPg2zieRAAiIAFooHA4MUBWVpMy3NJtgJdvskIdwR8Nn03B0uvLfv8gSDXjL3jEYH5scVccgACy6ypuVS-ADCED6e2WUGgDJA6g2ABU-HlZRClJoAJJQQWwerI1EwACCgfq8P+YIhXJgcY+xQgYCTMQg6hcWYATEnhMIgA)
```sh
--parser typescript
--tab-width 4
```

**Input:**
```tsx
export const foo = css`
&.foo .${bar}::before,&.foo[value="hello"] .${bar}::before {
	position: absolute;
}
`;
```

**Output:**
```tsx
Error: Couldn't insert all the expressions
    at transformCssDoc (https://prettier.io/lib/standalone.js:22539:13)
    at Object.embed$3 [as embed] (https://prettier.io/lib/standalone.js:22377:20)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15170:30)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15288:31)
    at https://prettier.io/lib/standalone.js:15253:18
    at Object.printComments (https://prettier.io/lib/standalone.js:14974:19)
    at printGenerically (https://prettier.io/lib/standalone.js:15252:24)
    at FastPath.call (https://prettier.io/lib/standalone.js:15089:18)
    at printPathNoParens (https://prettier.io/lib/standalone.js:26413:92)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:24859:30)
```
