### ISSUE TITLE
SCSS: Nested selector case is changed

### ISSUE THREAD

**Issue by testerez** [prettier/prettier#2885]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.foo%20%7B%5Cn%20%20%26Foo%20%7B%5Cn%20%20%20%20%2F%2F...%5Cn%20%20%7D%5Cn%20%20%26Bar%20%7B%5Cn%20%20%20%20%2F%2F...%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser postcss
```

**Input:**
```scss
.foo {
  &Foo {
    //...
  }
  &Bar {
    //...
  }
}
```

**Output:**
```scss
.foo {
  &foo {
    //...
  }
  &bar {
    //...
  }
}

```

**Expected behavior:**
The nested selectors case shouldn't be changed

**Comment by lydell** [comment]
Thanks for the issue! This has already been reported in #2860 and #2830, but it hasn't been released yet.
