### ISSUE TITLE
eslint no-unexpected-multiline error was ignored when I fixed with eslint

### ISSUE THREAD

**Issue by yinshuxun** [prettier/prettier#2901]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20a%20%3D%201%5Cn%20%20%20%20%20%20(()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20const%20c%20%3D%201%3B%5Cn%20%20%20%20%20%20%20%20console.log(c)%5Cn%20%20%20%20%20%20%7D)()%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
# Options (if any):
--fix
```

**Input:**
```jsx
const a = 1
      (() => {
        const c = 1;
        console.log(c)
      })()
```

**Output:**
```jsx
const a = 1(() => {
  const c = 1;
  console.log(c);
})();
```

**Expected behavior:**

**Comment by lydell** [comment]
Closing in favor of https://github.com/prettier/eslint-config-prettier/issues/30
