### ISSUE TITLE
printWidth vs --print-width

### ISSUE THREAD

**Issue by andy013** [prettier/prettier#2902]
Hey, I noticed a small issue and I'm not sure if it's expected behaviour or not. Using prettier from the CLI and using the sublime plugin gives me 2 different results with the same settings. I noticed that the printWidth setting will give you different results than using the --print-width argument. Is that normal?

**Comment by azz** [comment]
They should be the same. Could you provide some more detailed reproduction steps?

**Comment by andy013** [comment]
Sorry, I figured it out. The plugin for sublime was putting in additional CLI arguments by default and that was changing the formatting.
