### ISSUE TITLE
Pattern recognition feature

### ISSUE THREAD

**Issue by ChristianKohler** [prettier/prettier#2905]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22class%20MyClass%20%7B%5Cn%20%20constructor()%20%7B%5Cn%20%20%20%20if%20(true)%20%7B%5Cn%20%20%20%20%20%20const%20asdf%20%3D%20%7B%5Cn%20%20%20%20%20%20%20%20propertyName%3A%20%7B%20myproperty%3A%20this.aFunctionWithALongName()%20%7D%2C%5Cn%20%20%20%20%20%20%20%20longPropertyName%3A%20%7B%20myproperty%3A%20this.aFunctionWithALongName()%20%7D%2C%5Cn%20%20%20%20%20%20%20%20anotherLongPropertyName%3A%20%7B%20myproperty%3A%20this.aFunctionWithALongName()%20%7D%2C%5Cn%20%20%20%20%20%20%20%20anotherTooLongPropertyName%3A%20%7B%20myproperty%3A%20this.aFunctionWithALongName()%20%7D%5Cn%20%20%20%20%20%20%7D%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%5Cn%20%20aFunctionWithALongName()%20%7B%7D%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
class MyClass {
  constructor() {
    if (true) {
      const asdf = {
        propertyName: { myproperty: this.aFunctionWithALongName() },
        longPropertyName: { myproperty: this.aFunctionWithALongName() },
        anotherLongPropertyName: { myproperty: this.aFunctionWithALongName() },
        anotherTooLongPropertyName: { myproperty: this.aFunctionWithALongName() }
      };
    }
  }

  aFunctionWithALongName() {}
}
```

**Output:**
```jsx
class MyClass {
  constructor() {
    if (true) {
      const asdf = {
        propertyName: { myproperty: this.aFunctionWithALongName() },
        longPropertyName: { myproperty: this.aFunctionWithALongName() },
        anotherLongPropertyName: { myproperty: this.aFunctionWithALongName() },
        anotherTooLongPropertyName: {
          myproperty: this.aFunctionWithALongName()
        }
      };
    }
  }

  aFunctionWithALongName() {}
}

```

**Expected behavior:**
Prettier works as expected. It breaks the "anotherTooLongPropertyName" object. 

My question is whether it would be possible to recognize patters like these and keep the properties in one line if there are more than 4 properties and only one breaks.

What do you think?

**Comment by lydell** [comment]
Hi! Thanks for the issue! This has been discussed in the past. See #2668 (although it seems to be about JSX at a first glance, it then generalizes) and #2743.
