### ISSUE TITLE
Glob pattern issues in 1.7.1 

### ISSUE THREAD

**Issue by icopp** [prettier/prettier#2908]
**Input:**
```sh
node_modules/.bin/prettier --parser json --write package.json
```

**Output:**
```sh
Unable to expand glob patterns: package.json !**/node_modules/** !./node_modules/**
TypeError: Cannot read property 'name' of undefined
```

**Expected behavior:**

Prettier runs and parses the given file

**Comment by suchipi** [comment]
I'm unable to reproduce; could you provide more info? What node version are you using?

**Comment by ikatyang** [comment]
I cannot reproduce, this is how I tested:

```sh
mkdir test && cd test && yarn --init && yarn add prettier && node_modules/.bin/prettier --parser json --write package.json
```

Can you share steps to reproduce?

**Comment by icopp** [comment]
```
node -v
v8.5.0

npm -v
5.4.2
```

Interestingly, making a new repo and testing there works fine. However, on my existing repo, 1.7.0 works fine while 1.7.1 fails. I'm trying to figure out what the difference is, but so far I can only think that there must be a dependency getting pulled in with a slightly different version that must be mucking things up.

**Comment by ikatyang** [comment]
Prettier bundled all the dependencies before publishing to npm, so that it's impossible to be affected by dependencies.

<https://www.npmjs.com/package/prettier>: 0 dependencies

**Comment by ikatyang** [comment]
I'm able to reproduce something like this in #2924 with single line js config:

```sh
mkdir test
cd test && yarn --init
yarn add prettier
echo 'module.exports = { semi: true };' > myConfig.js
echo 'const x = 1' > index.js
node_modules/.bin/prettier --config myConfig.js index.js
```

`cosmiconfig` parses `myConfig.js` as yaml (parsed = `{ "module.exports = { semi": "true };" }`) causing invalid config error catched by this `try...catch`:

```js
  try {
    const filePaths = globby
      .sync(patterns, { dot: true })
      .map(
        filePath =>
          path.isAbsolute(filePath)
            ? path.relative(process.cwd(), filePath)
            : filePath
      );
    if (filePaths.length === 0) {
      console.error(`No matching files. Patterns tried: ${patterns.join(" ")}`);
      process.exitCode = 2;
      return;
    }
    ignorer
      .filter(filePaths)
      .forEach(filePath =>
        callback(filePath, getOptionsForFile(argv, filePath)) // <-----------------
      );
  } catch (error) {
    throw error;
    console.error(
      `Unable to expand glob patterns: ${patterns.join(" ")}\n${error}` // <-------------
    );
    // Don't exit the process if one pattern failed
    process.exitCode = 2;
  }
```

---

Not sure if this is your case, can you share your config setting?

**Comment by bd82** [comment]
I have the same issue, tried creating a reproducing repo and surprisingly everything works...
I have a suspicion this is related to the file structure of he project.

**Comment by bd82** [comment]
Reproducible example here:
https://github.com/bd82/prettier_172_issue

The issue seems related to the existence of a "prettier" section in the package.json file.

I would hazard a guess this has something to do with default options behavior.

**Comment by ikatyang** [comment]
@bd82 

It seems you're using incorrect config, `no-semi` is for CLI, you should write `semi: false` there, it'll just work fine, but we should show better warning message.

**Comment by bd82** [comment]
Thanks. @ikatyang 

Was this changed? as the no-semi option was definitely working in 1.6

**Comment by ikatyang** [comment]
@bd82 

Maybe it's caused by our original implementation, but it's never mention on [official docs](https://github.com/prettier/prettier#semicolons) before, so it should be an issue.

**Comment by ikatyang** [comment]
I believe @icopp's issue is something like I mentioned before, opened https://github.com/davidtheclark/cosmiconfig/issues/95 to track it.

**Comment by icopp** [comment]
It's definitely the config file doing it.

When I have a `.prettierrc` file with these options, it breaks:

```
{
  "eslintIntegration": true,
  "semi": false,
  "singleQuote": true
}
```

When I have no such file, it works.

The `eslintIntegration` option is used by some editors as a setting lookup, and previously didn't cause any trouble.

**Comment by ikatyang** [comment]
OK, I think #2929 should fix it, sorry for causing such issue, I forgot there may be some unknown options while implementing the normalization.

**Comment by bd82** [comment]
Thanks @ikatyang
