### ISSUE TITLE
Different formatting for function with multiline arguments in 1.7.1

### ISSUE THREAD

**Issue by vanduynslagerp** [prettier/prettier#2909]
**Prettier 1.7.1**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%20%20t.throws(%5Cn%20%20%20%20()%20%3D%3E%20validate(%7BTRAVIS%3A%20'true'%2C%20GH_TOKEN%3A%20'GH_TOKEN'%2C%20TRAVIS_TEST_RESULT%3A%20undefined%7D)%2C%5Cn%20%20%20%20'Not%20running%20in%20Travis%20after_success%20step'%5Cn%20%20)%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
  t.throws(
    () => validate({TRAVIS: 'true', GH_TOKEN: 'GH_TOKEN', TRAVIS_TEST_RESULT: undefined}),
    'Not running in Travis after_success step'
  );
```

**Output:**
```jsx
t.throws(
  () =>
    validate({
      TRAVIS: "true",
      GH_TOKEN: "GH_TOKEN",
      TRAVIS_TEST_RESULT: undefined
    }),
  "Not running in Travis after_success step"
);

```

**Expected behavior:**
In prettier 1.7.0 the input was valid and prettier kept this formatting. In 1.7.1 prettier reformat as seen in the output.
It seems to be a big change for a patch release, so I guess it's involuntary.

**Comment by lydell** [comment]
This sounds like a bug fix to me. Previously, the `validate` line was too long, now Prettier correctly breaks it to fit.

**Comment by vanduynslagerp** [comment]
For information this is settings:
```json
"prettier": {
    "printWidth": 120,
    "singleQuote": true,
    "bracketSpacing": false,
    "trailingComma": "es5"
  }
```

**Comment by ikatyang** [comment]
Looks like you forgot to setup options on the playground.

**Prettier 1.7.1**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%20%20t.throws(%5Cn%20%20%20%20()%20%3D%3E%20validate(%7BTRAVIS%3A%20'true'%2C%20GH_TOKEN%3A%20'GH_TOKEN'%2C%20TRAVIS_TEST_RESULT%3A%20undefined%7D)%2C%5Cn%20%20%20%20'Not%20running%20in%20Travis%20after_success%20step'%5Cn%20%20)%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A120%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22es5%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--print-width 120
--single-quote
--trailing-comma es5
```

**Input:**
```jsx
  t.throws(
    () => validate({TRAVIS: 'true', GH_TOKEN: 'GH_TOKEN', TRAVIS_TEST_RESULT: undefined}),
    'Not running in Travis after_success step'
  );
```

**Output:**
```jsx
t.throws(
  () => validate({ TRAVIS: 'true', GH_TOKEN: 'GH_TOKEN', TRAVIS_TEST_RESULT: undefined }),
  'Not running in Travis after_success step'
);

```

**Comment by vanduynslagerp** [comment]
Ok it seems that on the playground when I put the proper settings it works as expected.
I set my setting in the `package.json` so it appears they are ignored now. So it seems prettier try to format to fit 80 characters instead of 120.

**Comment by lydell** [comment]
@vanduynslagerp Note that objects literals are a special case where Prettier actually looks at the original code to decide how to format. If there's a newline in the object literal, Prettier is going to print it on several lines even if it fits on one line. So when an object has gone multiline, it never goes singleline again – unless you manually join up those lines. Perhaps that's what's happening to you? Can you try and join the lines back manually and then run Prettier again?

**Comment by vanduynslagerp** [comment]
Yes I did that, but still prettier reformat to fit 80 lines.

**Comment by ikatyang** [comment]
Can you share an example repo to reproduce the issue? I cannot reproduce it.

**Comment by vanduynslagerp** [comment]
Absolutly: https://github.com/semantic-release/travis-deploy-once
File travis-deploy-once/test/verify-jobs-state.test.js

**Comment by vanduynslagerp** [comment]
For info if I comment out this line https://github.com/prettier/prettier/blob/master/src/resolve-config.js#L11 it works again as expected.

Not sure why enabling `rcExtensions` would prevent to read the package.json properly.

**Comment by vanduynslagerp** [comment]
Here is an updated link. Contrary to what I thought the problem doesn't seems to be related to where the configuration is set.

**Prettier 1.7.1**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22test('Throw%20error%20if%20GitHub%20authentication%20missing'%2C%20t%20%3D%3E%20%7B%5Cn%20%20t.throws(%5Cn%20%20%20%20()%20%3D%3E%20validate(%7BTRAVIS%3A%20'true'%2C%20GH_TOKEN%3A%20undefined%2C%20TRAVIS_TEST_RESULT%3A%20undefined%7D)%2C%5Cn%20%20%20%20Error%2C%5Cn%20%20%20%20'GitHub%20authentication%20missing'%5Cn%20%20)%3B%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A120%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--print-width 120
--single-quote
```

**Input:**
```jsx
test('Throw error if GitHub authentication missing', t => {
  t.throws(
    () => validate({TRAVIS: 'true', GH_TOKEN: undefined, TRAVIS_TEST_RESULT: undefined}),
    Error,
    'GitHub authentication missing'
  );
});
```

**Output:**
```jsx
test('Throw error if GitHub authentication missing', t => {
  t.throws(() => validate({
        TRAVIS: 'true',
        GH_TOKEN: undefined,
        TRAVIS_TEST_RESULT: undefined
      }), Error, 'GitHub authentication missing');
});
```
**Expected behavior:**
Similar to prettier 1.7.0

**Comment by lydell** [comment]
Thanks. This is definitely a bug. Especially since the indendation is odd.

**Comment by duailibe** [comment]
Sorry about this 😞 it was definitely not intended

**Comment by vanduynslagerp** [comment]
No worries @duailibe ! This happens sometimes :)

**Comment by vanduynslagerp** [comment]
Just for info, do you plan to release a 1.7.2 right away with this fix, or one later with more fixes?
Thanks!

**Comment by lydell** [comment]
I wouldn't mind releasing 1.7.2 after a day or so when most of the 1.7.1 issues have come in.

**Comment by vanduynslagerp** [comment]
OK. I'm using `eslint-plugin-prettier` so all my build are failing, so I was wondering if should modify the code on all my repo, or pin version 1.7.0.
But if the new version comes in a day or so, I might way for it.

**Comment by vjeux** [comment]
I would go for a quick 1.7.2 asap. If we see anything else that's bad we can do 1.7.3. It sucks having out there things that are obviously broken.

By the way, you absolutely want to pin versions with prettier. We do stylistic changes during minors.

**Comment by duailibe** [comment]
There are more issues popping up about this

**Comment by suchipi** [comment]
I'll release 1.7.2

**Comment by suchipi** [comment]
This is now fixed in 1.7.2. Sorry about that!

**Comment by azz** [comment]
> By the way, you absolutely want to pin versions with prettier. We do stylistic changes during patches.


@vjeux Think we should recommend using `--save-exact` (npm) and `--exact` (yarn) in the README?

**Comment by vjeux** [comment]
Yes, absolutely!
