### ISSUE TITLE
Source map bug when using Prettier with PostCSS

### ISSUE THREAD

**Issue by sherlockwang** [prettier/prettier#2911]
I'm using Prettier by Gulp Prettier Plugin with Gulp Sass, Gulp Source map and PostCSS together. After I started using Prettier formats my SCSS files, the Source map to SCSS source files is broken. 

After formatting SCSS files one by one, I realized that the Source map is broken by a `font-family` property. The Prettier config is very simple. Since I'm using Gulp Prettier Plugin, the Prettier config uses API version. 

```js
{
  parser: "postcss"
}
```

**Input:**
```scss
font-family: "Helvetica Neue", Helvetica, Ubuntu, "Segoe UI", Verdana, sans-serif;
```

**Output:**
```scss
font-family: "Helvetica Neue", Helvetica, Ubuntu, "Segoe UI", Verdana,
  sans-serif;
```

After testing in different format, it looks like the source map will only broken when the property is cut inside a group of property, like `"Segoe UI", Verdana, sans-serif` with CRLF line break. If the cutting is happened between different group or the line break is LF, then the source map is correct. It is a very wired bug. My guessing is the source map don't understand CRLF line break inside a group of property. 

My current solution is just increase `printWidth` in my Prettier config, which tells Prettier don't cut any long line. But if Prettier can make the output like 

```scss
font-family: 
  "Helvetica Neue", Helvetica, Ubuntu, 
  "Segoe UI", Verdana, sans-serif;
```

I think this will be better for human reading and also cut the long line into multiple short line. There is also an issue about `font-family` property formatting. (https://github.com/prettier/prettier/issues/2854) Hope there will be better solution in the future version. 

Thanks

**Comment by lydell** [comment]
Looks like you have some source map debugging to do! If some tool you are using can't generate a correct source map if certain lines are broken with a CRLF, that's an issue with that tool, not Prettier.
