### ISSUE TITLE
v1.7.0 -> v1.7.1; Patch version have such a drastic change?

### ISSUE THREAD

**Issue by maraisr** [prettier/prettier#2917]
v1.7.0 -> v1.7.1; Patch version have such a drastic change?

Patching has touched close to 36% of our entire code base, are we sure this wasn't mean to be a new minor?

```diff
it('should return correct string', () => {
-	expect(
-		dateIso({
+				expect(dateIso({
				year: '2017',
				month: '08',
				day: '10'
-			})
-		).equal('2017-08-10');
+})).equal('2017-08-10');
});

it('should default the day to the 1st', () => {
-	expect(
-		dateIso({
-			year: '2017',
-			month: '12'
-		})
-	).equal('2017-12-01');
+	expect(dateIso({ year: '2017', month: '12' })).equal('2017-12-01');
});

**Comment by andrewdhazlett** [comment]
This is affecting me too. It seems the `--print-width` option is being completely ignored.

**Comment by andrewdhazlett** [comment]
[playground link](https://prettier.io/playground/#%7B%22content%22%3A%22it('gets%20all%20the%20action%20data%20per%20UserAction'%2C%20async%20()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20const%20user_id%20%3D%201%5Cn%20%20%20%20%20%20const%20actions%20%3D%20await%20UserActions.getActions(user_id)%5Cn%20%20%20%20%20%20forEach(actions%2C%20action%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20expect(action).to.have.all.keys(%5Cn%20%20%20%20%20%20%20%20%20%20'id'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'category'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'name'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'description'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'impact'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'uom'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'user_id'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'action_id'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'completions'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'status'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'created_at'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'updated_at'%2C%5Cn%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%7D)%5Cn%20%20%20%20%7D)%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Comment by duailibe** [comment]
Yeah, sorry about that. It's a bug introduced in the last version.

It's the same of #2909 and #2910. It's already fixed on master, a new release should come out soon.

**Comment by suchipi** [comment]
Just released 1.7.2 where this is fixed. Sorry about that!
