### ISSUE TITLE
Plugin support for AST changes

### ISSUE THREAD

**Issue by k15a** [prettier/prettier#2931]
Hey,

I thought that I've read about this feature in the issue tracker already but I cannot find it again so I will create a new issue to get a discussion started.

A common request for Prettier is to sort import order or to change template strings to normal strings if they don't have interpolations.

The reason why Prettier can't support this is that we promise to keep the AST the same so the meaning of the code doesn't change.

I think it would be great to support plugins which could change the AST. A plugin is a function which will get the AST and return the changed AST. Prettier will then pass the AST to the next plugin. After all plugins, Prettier will print the code with the current algorithm.

**Comment by lydell** [comment]
I think you were looking for #1020 and #1710.

**Comment by azz** [comment]
#1783 already provides an API to grab an AST and do whatever you want with it before passing it to prettier, but it's more of a low-level tool and doesn't support chaining multiple transforms without writing some user-space code.

But there's no real need to clutter `prettier`'s API to add support for this, we could actually build a separate module which utilizes the custom parser API (called `prettier-transform` or something like that) which acts as a base for AST transformations.

Its API could look something like:

```bash
prettier-transform --parser babylon -t sort-imports -t normalize-strings -- --write --single-quote "**/*.js"
```

**Comment by azz** [comment]
Had a quick crack at this:

https://github.com/azz/prettier-transform

**Comment by thorn0** [comment]
This is now possible with plugins. E.g. see https://github.com/simonhaenisch/prettier-plugin-organize-imports
