### ISSUE TITLE
--config-precedence broken for prettier 1.7.2 with value prefer-file

### ISSUE THREAD

**Issue by mitermayer** [prettier/prettier#2936]
Having the input file 

```css
.a {
     background: red;
}
```

and running the command 

```bash
cat t.css | prettier --parser css --config-precedence prefer-file --stdin
```

causes:

```
stdin: SyntaxError: Unexpected token (1:1)
> 1 | .foo {
    | ^
  2 |       background: red;
  3 | }
  4 | 
```

It is not reading the `parser` configuration from the cli and is ignore the option completely.

Note:
 - No configuration files is anywhere in the path
 - running with this command ` cat t.css | prettier --parser css --config-precedence file-override --stdin` works
 - running with this command  `cat t.css | prettier --parser css --config-precedence cli-override --stdin` works
 - running with this commad ` cat t.css | prettier --parser css --stdin` works

**Comment by mitermayer** [comment]
@ikatyang I thing that is related to the work done around the cli refactoring, do you think you can have look into it ? 

cc @lydell  @azz

**Comment by mitermayer** [comment]
I manage to create a test and snapshot that can reproduce this behaviour

**Comment by azz** [comment]
I'm unable to reproduce so far. 

```
HEAD is now at 75781a6d... 1.7.2

azz at macOS in ~/code/prettier on 75781a6d [$]
$ cat test.css
.a {
    color: red;
}

azz at macOS in ~/code/prettier on 75781a6d [$]
$ ./bin/prettier.js --find-config-path test.css

azz at macOS in ~/code/prettier on 75781a6d [$]
$ cat test.css | prettier --parser css --config-precedence prefer-file --stdin
.a {
  color: red;
}

```

**Comment by mitermayer** [comment]
whats the best way for me to share the tests / snapshopt ?

**Comment by mitermayer** [comment]
Here, created a WIP PR for it

https://github.com/prettier/prettier/pull/2938/files

**Comment by mitermayer** [comment]
```
miter@primus ~/tmp $ cat test.css | prettier --parser css --config-precedence prefer-file --stdin
stdin: SyntaxError: Unexpected token (1:1)
> 1 | .foo {
    | ^
  2 |       background: red;
  3 | }
  4 | 
miter@primus ~/tmp $ prettier --version
1.7.2
```

**Comment by azz** [comment]
Can you also run `prettier --find-config-path .` ?

**Comment by mitermayer** [comment]
no config on my path returns empty
