### ISSUE TITLE
Add `--loglevel` option

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#2939]
from https://github.com/prettier/prettier/pull/2903#issuecomment-333285580

Possible option choices:

- `silent`: nothing
- `error`: error message
- `warn` (default): error message + warning
- `debug`: error message + warning + debug message

**Comment by lydell** [comment]
Could you give an example of:

- an error message
- a warning
- a debug message

**Comment by azz** [comment]
Error message:

```
error: Invalid --print-width value.
error: Expected an integer, but received: "0.3"
```

Warning:

```
warn: `--flow-parser` is deprecated. Use `--parser flow` instead.
```

Debug:

```
debug: found config file `/path/to/.prettierrc`
debug: resolved options `{ semi: false }`
```

**Comment by azz** [comment]
I usually use [`debug`](npmjs.com/package/debug) for this kind of stuff because colors are cool.
