### ISSUE TITLE
stdin with overrides

### ISSUE THREAD

**Issue by patlux** [prettier/prettier#2946]
Hi,

I don't know if it's a bug or a unsolvable problem. Without the cli option `--stdin` it's working like expected. I cannot provide a playground example, because it only happens with the stdin option.

See yourself:

**Working** (without --stdin)
```bash
prettier --config .prettierrc.json --config-precedence prefer-file index.js
```

**Not working** (with --stdin)
```bash
cat index.js | prettier --stdin --config .prettierrc.json --config-precedence prefer-file
```

.prettierrc.json
```json
{
  "tabWidth": 2,
  "overrides": [{
    "files": "*.js",
    "options": {
      "parser": "babylon",
      "tabWidth": 4
    }
  }]
}
```

input.js
```js
const hello = {
  beatiful: "world"
};
```

output.js
```js
const hello = {
  beatiful: "world"
};
```

expected-output.js
```js
const hello = {
    beatiful: "world"
};
```

I think the problem here is, that prettier cannot detect which file extension the source has, because it comes from the stdin. I'm right?

I'm using the JsPrettier Plugin for Sublime Text.
https://github.com/jonlabelle/SublimeJsPrettier/issues/77

**Comment by lydell** [comment]
> I think the problem here is, that prettier cannot detect which file extension the source has, because it comes from the stdin. I'm right?

Correct. That's why the `--stdin-filepath` option exists.

```
$ prettier --help stdin-filepath
--stdin-filepath <path>

  Path to the file to pretend that stdin comes from.
```

Can you try that option and see if it helps?

**Comment by patlux** [comment]
$ cat input.js | prettier --stdin --stdin-filepath input.js --config .prettierrc.json --config-precedence prefer-file
    const hello = {
      beatiful: "world"
    };

Thanks @lydell. But it's not working, too.

**Comment by mitermayer** [comment]
I run into that issue too on `vim-prettier` I think what we need is having the option `--config-precedence prefer-file` still apply the all the ` --stdin-*` args.

What is happening above is that when passing the `prefer-file` option to `--config-precedence` the `--stdin` and `stdin-filepath` options are getting ignored.

One solution to the above problem is whitelisting some CLI options that would always work as override even when `prefer-file` or any other `config-precedence` is passed.

@lydell thoughts around it ? I can submit a PR for it as well

**Comment by lydell** [comment]
Isn't the problem simply that we forgot to check the stdin-filepath against the globs in the config?
