### ISSUE TITLE
Consolidate GitHub labels

### ISSUE THREAD

**Issue by azz** [prettier/prettier#2949]
I've just gone through and "normalized" some of the [labels](https://github.com/prettier/prettier/labels) (mostly just changed them to lowercase), and I removed <kbd>Assigned</kbd> as you can just use the [assignee:*](https://github.com/prettier/prettier/issues/assigned/*) query.

I had a few questions:

1. What's the difference between <kbd>needs more info</kbd> and <kbd>awaiting response</kbd>? Can we merge them?
2. What's the difference between <kbd>external</kbd> and <kbd>dependency</kbd>? Can we merge them?
3. Should we rename <kbd>infrastructure</kbd> to <kbd>meta</kbd> or something like that?
4. The colors are kind of random. Should we use particular colors to mean particular things?

**Comment by ikatyang** [comment]
> What's the difference between external and dependency? Can we merge them?

external (out of scope): something that is not our dependency, e.g. SublimeJsPrettier
dependency: something that is our dependency, e.g. cosmiconfig

**Comment by azz** [comment]
It's really annoying that you can't add tooltips to labels to explain what they mean.

**Comment by ikatyang** [comment]
- We can add them in wiki just like [what TypeScript did](https://github.com/Microsoft/TypeScript/wiki/Contributing-to-TypeScript#issue-tracking-101), actually I borrow some labels from there.
- I'd like to suggest adding a `JavaScript` tag as Prettier is now not only for js formatting.
- Maybe rename `external` to `out of scope` would be better?

**Comment by lydell** [comment]
Feel free to go nuts with the labels, as long as you feel like doing the work and it helps filtering through the open issues. A wiki page with explanations would be awesome! Make sure to link to such a page here if you make one, and ping contributors who handle issues so we know how to label :)

**Comment by lydell** [comment]
> What's the difference between <kbd>needs more info</kbd> and <kbd>awaiting response</kbd>?

We've had <kbd>needs more info</kbd> for a long time, and used it on issues that didn't provide enough information to continue with. Recently, I went through all open pull requests and noticed that many of them were mostly good, but we were waiting for an update from the author, a response or consensus on some question, so I added <kbd>awaiting response</kbd> to them. Not sure what's best :)

**Comment by azz** [comment]
Probably add <kbd>awaiting response</kbd> to all the issues with <kbd>needs more info</kbd> and then remove it.

**Comment by azz** [comment]
Alright, I've gone through and meddled with all the labels!

I wrote some documentation, too: https://github.com/prettier/prettier/wiki/Issue-Labels

Pinging @vjeux @existentialism @despairblue @josephfrazier @bakkot @k15a @karl  @JamesHenry @suchipi @rattrayalex

I'm open to any feedback on improving them further.

**Comment by ikatyang** [comment]
`lang:typescript` says "I'm lonely." 😭

**Comment by suchipi** [comment]
Looks great to me :smile:

**Comment by rattrayalex** [comment]
Awesome work! Looks great to me. Love the use of <kbd>kbd</kbd> btw.
 
I plan to break out `type:infrasctructure/meta` into `type:infra`, `type:meta`, and `type:tests` shortly (if I don't within half an hour, someone else can 😄 )

**Comment by suchipi** [comment]
We might also want tags for the website/playground

**Comment by rattrayalex** [comment]
@suchipi I created `type:site` but haven't used it anywhere. I'll add docs.

**Comment by azz** [comment]
Closing the issue but feel free to further revise.

**Comment by JamesHenry** [comment]
Nice one, @azz, thanks!

**Comment by ikatyang** [comment]
https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more

**Comment by j-f1** [comment]
Added descriptions. Changes from the wiki:

* <kbd>area:comments</kbd>
  
  > Comments are one of the most complicated parts of prettier. This label means the issue relates to how prettier is printing comments.

  was too long. I changed it to

  > Issues about how Prettier prints comments.

* <kbd>area:multiparser</kbd>

  > Multi-parser is the code that makes it possible to format one programming language inside another, such as CSS-in-JS.

  was too long. I changed it to

  > Issues about printing one language inside another, like CSS-in-JS.

* <kbd>area:playground</kbd> + <kbd>area:website</kbd>
  I removed the link since Markdown doesn’t work in the descriptions.

* <kbd>priority:facebook blocker</kbd> + <kbd>priority:high</kbd>

  > Although Prettier is not an official project of Facebook OpenSource, engineers working at Facebook (primarily @vjeux) have devoted a significant number of working hours to improving Prettier for everybody. Facebook use Prettier internally, and issues marked with this label block Facebook upgrading Prettier.

  > High priority issues are ones that either re-print code in a way that unintentionally changes the AST, or are significant regressions and need to be fixed urgently.

  I didn’t change these ones since they’re too long. Can someone come up with something shorter?


* <kbd>scope:dependency</kbd>

  > This is a real issue but cannot be solved by modifying Prettier itself, it must be fixed in one of our dependencies.

  changed to

  > This is a real issue but cannot be solved inside Prettier itself, it must be fixed in a dependency.

* <kbd>scope:external</kbd>: too long

  > This issue cannot be resolved in Prettier itself, it is an issue with something external, such as an editor integration.

* <kbd>status:awaiting response</kbd>: too long

  > In a pull request, this means a review has been left that requires the author to reply. On an issue, this means that a collaborator has replied and requires more information from the reporter to proceed.

* <kbd>status:has pr</kbd>

  > This issue has an accompanying PR. By excluding this label from your search it is easier to find actionable items.

  shortened to:

  > This issue has an accompanying pull request.

* <kbd>type:editor support</kbd>

  > This issue pertains to ensuring Prettier provides the right tools to be used inside editor integrations.

  shortened to:

  > This issue pertains to tools Prettier provides for use inside editor integrations.

* <kbd>type:feature</kbd>: removed “to Prettier”

* <kbd>type:option request</kbd> + <kbd>type:question</kbd>: too long
