### ISSUE TITLE
prettier 1.7.3 misreports its version

### ISSUE THREAD

**Issue by jason0x43** [prettier/prettier#2954]
Running `prettier --version` from with prettier v1.7.3 outputs

```
1.7.2
```

The `package.json` in the npm module does have a version value of "1.7.3". However, the package data that was built into the package's `index.js` has a version value of 1.7.2.

**Comment by ikatyang** [comment]
See https://github.com/prettier/prettier/commit/099cf760d03ef7a94db485aa3d486ec7bdafb150#commitcomment-24670336.

I think this bug(?) is not critical so we can just fix(?) it in the next release?

cc @azz

**Comment by azz** [comment]
Ah, this is because I accidentally ran the build steep before bumping the package version. Rookie mistake. Closing since it's not actionable, but thanks for letting us know.

**Comment by azz** [comment]
I'll probably do another patch release tomorrow as there have been a few fixes.

**Comment by jason0x43** [comment]
Yeah, it's definitely not critical, I just wanted to point it out in case there was some underlying issue with the release process.
