### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#2955]
Inspired by #2954.

Should we make `yarn build` error or something if it sees that the version in package.json hasn't changed? (If so, we also need to add a way to force building anyway, since it is useful for testing.)

@suchipi @azz You've released versions before. Is there anything else we could improve? Would be nice to be able to chunk of patch releases super quickly.

**Comment by azz** [comment]
Perhaps a `prepublishOnly` script that checks

```js
require('.').version === require('..').version
```

?

**Comment by azz** [comment]
Would be great if we could get it compatible with https://github.com/sindresorhus/np

I noticed all the existing tags are `1.5.0` etc (without the leading `v` that `npm version patch` will add), this is actually the reason I botched the release a bit. I ran `npm version patch`, rolled back, removed the tag, ran the build, re-bumped the package.

**Comment by suchipi** [comment]
The part that usually takes me the longest is the changelog- It'd be cool to have a script that gets the tag for the last release, compiles a list of all the PRs that were merged since then, and updates CHANGELOG.md.

Also, I often accidentally make a tag and push it instead of creating the release on GitHub- if you create the release on GitHub (which also makes a tag), then you can put a description on it. Not sure if we want to do anything about this (maybe just print a note in the build output)?

**Comment by azz** [comment]
I usually use something like `git diff --oneline 1.7.2..1.7.3` to start off with the changelog.

**Comment by lydell** [comment]
I like the `prepublishOnly` check. The only bad thing is that one has to rebuild the entire thing if the check fail, rather than getting help upfront.

Regarding the changelog, I actually think that we should start filtering it more, leaving out internal changes (fixes for tests, the playground, docs, small refactoring, etc). So I don't think we can generate it automatically. IMO, changelogs always take a little bit of time, but that's also what makes them better.

**Comment by ikatyang** [comment]
Mark those notable issues/PRs as `changlog-item` label?

**Comment by azz** [comment]
There aren't that many PRs merged from release to release, easier to filter by removing `-label:type:infro -label:type:meta` etc.

**Comment by azz** [comment]
Merged #2963 and made a small change in 2e655a37550604a742c07d51bc939291dbbbaeb7, release 1.7.4.

**Comment by azz** [comment]
Side note, my internet dropped out in the middle of `npm publish` and I almost 💩 myself. How do we prevent that?!

**Comment by lydell** [comment]
Deploy from the bathroom.

**Comment by azz** [comment]
Lets close this one as we have made some improvements. If there are more ideas we can open another issue.
