### ISSUE TITLE
One test fails on master on Travis CI, but not locally

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#2956]
https://travis-ci.org/prettier/prettier/jobs/282316211

```
Summary of all failing tests
FAIL tests_integration/__tests__/write.js
  ● do not write file with --write + formated file › (stdout)
    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    - "formated.js%s %dms
    + "formated.jss
      "
      
      at Object.test (tests_integration/runPrettier.js:98:32)
          at Promise (<anonymous>)
          at <anonymous>
```

Edit: #2957

**Comment by lydell** [comment]
To me, the saved snapshot value is strange. So perhaps this has uncovered a very subtle bug?

**Comment by ikatyang** [comment]
It seems Travis somehow set some kind of `--no-color` environment variable?

**Comment by lydell** [comment]
https://github.com/chalk/supports-color/blob/master/index.js

I'm not sure, but it feels like sometimes the logs on Travis are in color and sometimes not. This has happened before: I've also added `--no-color` to a test after merging a PR. The PR build suceeded, but the master build failed. Super confusing.
