### ISSUE TITLE
[question] .prettierignore syntax?

### ISSUE THREAD

**Issue by ahmedelgabri** [prettier/prettier#2964]
I'm trying to use `.prettierignore` file & I'm not sure why it's not working properly? I'm using `1.7.4`

`.prettierignore`

```
path/to/file.*.js
path/to/another/file.js
path/to/folder/
path/**/to/folder/
*.min.*
public/**/
```

```
$ prettier --find-config-path ./
prettier.config.js
```

`prettier.config.js`

```js
module.exports = {
  parser: 'flow',
  singleQuote: true,
  printWidth: 120,
  trailingComma: 'es5',
};
```

if I do this from the command line 

```sh
$ ./node_modules/.bin/prettier --write path/to/folder/*.js
# all .js files gets formatted although the path is in .prettierignore
```

I tired `--config-precedence file-override|prefer-file` but still these files which are inside paths that are ignored are getting formatted. Not sure what is the problem?

**Comment by azz** [comment]
Is the prettier you're using to get the config path (`prettier`) the same one as you're running at the bottom (`./node_modules/.bin/prettier`)?

**Comment by azz** [comment]
Unable to reproduce with the following steps:

```bash
mkdir temp
cd temp
npm init -y
npm i prettier@1.7.4

mkdir -p path/to/folder/
echo code > path/to/folder/x.js
echo path/to/folder > .prettierignore

./node_modules/.bin/prettier --write path/to/folder/*.js
```

**Comment by azz** [comment]
I did notice the files _are_ formatted if you do the following:

```
$ ./node_modules/.bin/prettier --write ./path/to/folder/*.js
                                       ^^
```

I think we should be doing a `path.relative()` on these globs.

**Comment by ahmedelgabri** [comment]
> I did notice the files are formatted if you do the following:
>```
> $ ./node_modules/.bin/prettier --write ./path/to/folder/*.js
> ```                                    ^^
> I think we should be doing a path.relative() on these globs.

I can confirm this, seems like this is the issue indeed. When I remove the `./` it works as expected.

**Comment by ahmedelgabri** [comment]
@azz I can help with a PR if you point me where to look

**Comment by azz** [comment]
Thanks. Basically you want to make sure the `filePaths` passed in to `ignorer.filter()` don't start with `./`. (But we are already doing a `path.relative()`, so I'm not sure what's up there)

https://github.com/prettier/prettier/blob/master/src/cli-util.js#L252-L269

**Comment by ikatyang** [comment]
Actually we only do `path.relative()` for absolute paths, we should always do it.

**Comment by azz** [comment]
Wow, my brain totally read that the other way around.

**Comment by ahmedelgabri** [comment]
So this should be enough I guess?

```diff
diff --git a/src/cli-util.js b/src/cli-util.js
index 2fd62ba7..b5e5e580 100644
--- a/src/cli-util.js
+++ b/src/cli-util.js
@@ -251,12 +251,8 @@ function eachFilename(argv, patterns, callback) {
   try {
     const filePaths = globby
       .sync(patterns, { dot: true })
-      .map(
-        filePath =>
-          path.isAbsolute(filePath)
-            ? path.relative(process.cwd(), filePath)
-            : filePath
-      );
+      .map(filePath => path.relative(process.cwd(), filePath));
+
     if (filePaths.length === 0) {
       console.error(`No matching files. Patterns tried: ${patterns.join(" ")}`);
       process.exitCode = 2;
```

**Comment by ikatyang** [comment]
@ahmedelgabri  Yes, and also you have to add tests for it in `tests_integration/__tests__`.

**Comment by Hotell** [comment]
hmm this behaviour is still present

prettier 1.11.1

-> when my codebase includes not valid files ( let's say json files for angular schematics with template syntax ), prettier still executes on those files and exits with error. Any ideas how to prevent this behaviour ?

![image](https://user-images.githubusercontent.com/1223799/37532358-1d03227a-293f-11e8-858c-d40eea3f82ae.png)

thx!

**Comment by j-f1** [comment]
Does `yarn prettier "src/**/*.json" --write` work?

**Comment by Hotell** [comment]
nope 

![image](https://user-images.githubusercontent.com/1223799/37532629-d579d2f4-293f-11e8-8a0b-87a20d3550e2.png)

**Comment by ikatyang** [comment]
`--config <your-config-file>` or `--no-config` should fix it.

**Comment by Hotell** [comment]
> --config <your-config-file> or --no-config should fix it.

nope

![image](https://user-images.githubusercontent.com/1223799/37532758-36c8f58a-2940-11e8-8e66-65c84cf662e2.png)

**Comment by ikatyang** [comment]
@Hotell Could you open a new issue with steps to reproduce?

**Comment by ikatyang** [comment]
Hmm, actually I think `--config .prettierrc` (fix `Invalid configuration file`) and a `.prettierignore` with that filename (ignore file with SyntaxError) should fix it.

**Comment by Hotell** [comment]
hmm so adding --config explicitly to my package json fixed the issue. I though that prettier is consuming `.prettierrc` by default. Is this a bug or works as expected ( the default config file consumption )

![image](https://user-images.githubusercontent.com/1223799/37534368-f615dcba-2944-11e8-9aa0-6c4eeb6772ce.png)


**.prettierrc**
```js
{
  "semi": true,
  "printWidth": 100,
  "trailingComma": "es5",
  "singleQuote": true,
  "arrowParens": "always"
}

```

**.pretieringore**
```
src/**/files/**/*
src/**/other-files/**/*
*.map
package.json
tsconfig.json
tslint.json
tsconfig.*.json
package-lock.json
yarn-lock.json
```

**package.json**
```json
{
"scripts": {
    "format": "prettier src/**/*.{ts,js,json,md,scss,less,css} --config .prettierrc",
}
}
```

```

**Comment by ikatyang** [comment]
(https://prettier.io/docs/en/configuration.html)

> Prettier uses [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) for configuration file support. This means you can configure prettier via:
> 
> * A `.prettierrc` file, written in YAML or JSON, with optional extensions: `.yaml/.yml/.json/.js`.
> * A `prettier.config.js` file that exports an object.
> * **A `"prettier"` key in your `package.json` file.**
>
> The configuration file will be resolved starting from the location of the file being formatted, and **searching up the file tree until a config file is (or isn't) found**.

It works as expected, but there's [an invalid `package.json` in your file tree](https://github.com/prettier/prettier/issues/2964#issuecomment-373769688) so you need to specify your config explicitly to avoid trying to load others.

**Comment by Hotell** [comment]
oh damn! 1 hour of my life wasted ! :D

maybe it should be stated in the docs explicitly to save time to my future me ?  I can submit PR .

Anyways, huge thanks for your quick responses folks, you rock ! ❤️

**Comment by duailibe** [comment]
@Hotell yes, if you're able, please send a PR :) docs are never finished!
