### ISSUE TITLE
Playground doesn't work

### ISSUE THREAD

**Issue by frontsideair** [prettier/prettier#2965]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground)

I get this error on the console, for latest versions of Safari and Chrome:

```
index.js:1842 Uncaught TypeError: Cannot read property 'PassThrough' of undefined
    at index.js:1842
    at worker.js:23
```

**Comment by azz** [comment]
Thanks for the catch.

@lydell This is a regression from #2942, due to adding `getStream` to the prettier API, it is now bundled loaded in the playground differently...

**Comment by azz** [comment]
Ok, if you reload twice (caching) it should be good to go!

**Comment by frontsideair** [comment]
I cleared the cache and tried again, it works. Thanks!
