### ISSUE TITLE
Support injectGlobal as css templateLiteral

### ISSUE THREAD

**Issue by brikou** [prettier/prettier#2970]
injectGlobal is a templateLiteral used by emotion (and maybe more css in js lib?). Prettier should treat it as css template literal.

Great work, can't imagine not using prettier anymore... :+1: 

**Prettier 1.7.2**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22export%20default%20()%20%3D%3E%20injectGlobal%60%5Cn*%2C%20*%3A%3Abefore%2C%20*%3A%3Aafter%20%7B%5Cnbox-sizing%3A%20inherit%3B%20%7D%5Cn%5Cn%40-ms-viewport%20%7B%20width%3A%20device-width%3B%20%7D%5Cn%60%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
export default () => injectGlobal`
*, *::before, *::after {
box-sizing: inherit; }

@-ms-viewport { width: device-width; }
`;
```

**Output:**
```jsx
export default () => injectGlobal`
*, *::before, *::after {
box-sizing: inherit; }

@-ms-viewport { width: device-width; }
`;

```

**Expected behavior:**

```jsx
export default () => injectGlobal`
  *,
  *::before,
  *::after {
    box-sizing: inherit;
  }

  @-ms-viewport {
    width: device-width;
  }
`;
```

**Comment by azz** [comment]
We actually briefly supported `injectGlobal` but it was removed because it is specific to one library, see https://github.com/prettier/prettier/pull/2337#issuecomment-311803127

We _might_ look at making this mapping configurable in the future.

**Comment by kripod** [comment]
Are there any news about supporting this behavior? Making the mapping configurable would definitely help.

**Comment by azz** [comment]
Still needs a proposal.
