### ISSUE TITLE
Extra pipe operator added to long typedefs after first newline character

### ISSUE THREAD

**Issue by gaganjakhotiya** [prettier/prettier#2971]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22type%20StringVals%20%3D%20'asasf'%20%7C%20'asdasdasd'%20%7C%20'asdaadasd'%20%7C%20'asdaassd'%20%7C%20'ascxcdasd'%20%7C%20'asdzxzcasd'%20%7C%20'aszzxdasd'%20%7C%20'asdzxxasd'%7C%20'azxxzsdasd'%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Atrue%2C%22output2%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22printWidth%22%3A120%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22es5%22%2C%22useTabs%22%3Atrue%7D%7D)
```sh
--jsx-bracket-same-line
--parser typescript
--print-width 120
--no-semi
--single-quote
--trailing-comma es5
--use-tabs
```

**Input:**
```tsx
type StringVals = 'asasf' | 'asdasdasd' | 'asdaadasd' | 'asdaassd' | 'ascxcdasd' | 'asdzxzcasd' | 'aszzxdasd' | 'asdzxxasd'| 'azxxzsdasd'

```

**Output:**
```tsx
type StringVals =
	| 'asasf'
	| 'asdasdasd'
	| 'asdaadasd'
	| 'asdaassd'
	| 'ascxcdasd'
	| 'asdzxzcasd'
	| 'aszzxdasd'
	| 'asdzxxasd'
	| 'azxxzsdasd'

```

**Expected behavior:**
```tsx
type StringVals
	= 'asasf'
	| 'asdasdasd'
	| 'asdaadasd'
	| 'asdaassd'
	| 'ascxcdasd'
	| 'asdzxzcasd'
	| 'aszzxdasd'
	| 'asdzxxasd'
	| 'azxxzsdasd'

```

**Comment by ikatyang** [comment]
Hi, thanks for the report. This is actually intended since it's more `git diff`-friendly and leading pipe is valid (Microsoft/TypeScript#12386).

```diff
type StringVals =
+	| 'asasf'
	| 'asdasdasd'
	| 'asdaadasd'
	| 'asdaassd'
	| 'ascxcdasd'
	| 'asdzxzcasd'
	| 'aszzxdasd'
	| 'asdzxxasd'
	| 'azxxzsdasd'
```
