### ISSUE TITLE
Ugly linebreak for chained promise function of instance object access

### ISSUE THREAD

**Issue by queicherius** [prettier/prettier#2974]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22this.actions%5Baction%5D(attributes)%5Cn%20%20.then(result%20%3D%3E%20%7B%5Cn%20%20%20%20%2F%2F%20...%5Cn%20%20%7D)%5Cn%20%20.catch(err%20%3D%3E%20%7B%5Cn%20%20%20%20%2F%2F%20...%5Cn%20%20%7D)%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--no-semi
--single-quote
```

**Input:**
```jsx
this.actions[action](attributes)
  .then(result => {
    // ...
  })
  .catch(err => {
    // ...
  })
```

**Output:**

This only seems to happen when you use both `then` **and** `catch` **and** you use an instance variable (`this.actions`) **and** you have an object access.

```jsx
this.actions
  [action](attributes)
  .then(result => {
    // ...
  })
  .catch(err => {
    // ...
  })

```

**Expected behavior:**

```jsx
this.actions[action](attributes)
  .then(result => {
    // ...
  })
  .catch(err => {
    // ...
  })
```

**Comment by azz** [comment]
This is actually working as intended. Note that if you replace `[action]` with `.action` is is formatted in the same way.

[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22this.actions.action(attributes)%5Cn%20%20.then(result%20%3D%3E%20%7B%5Cn%20%20%20%20%2F%2F%20...%5Cn%20%20%7D)%5Cn%20%20.catch(err%20%3D%3E%20%7B%5Cn%20%20%20%20%2F%2F%20...%5Cn%20%20%7D)%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--no-semi
--single-quote
```

**Input:**
```jsx
this.actions.action(attributes)
  .then(result => {
    // ...
  })
  .catch(err => {
    // ...
  })
```

**Output:**
```jsx
this.actions
  .action(attributes)
  .then(result => {
    // ...
  })
  .catch(err => {
    // ...
  })

```

There is a [sneaky workaround](https://prettier.io/playground/#%7B%22content%22%3A%22const%20Actions%20%3D%20this.actions%3B%5Cn%5CnActions%5Baction%5D(attributes)%5Cn%20%20.then(result%20%3D%3E%20%7B%5Cn%20%20%20%20%2F%2F%20...%5Cn%20%20%7D)%5Cn%20%20.catch(err%20%3D%3E%20%7B%5Cn%20%20%20%20%2F%2F%20...%5Cn%20%20%7D)%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D) that relies on prettier only inlining the call if the object starts with a capital letter.

The origin of this behaviour is https://github.com/prettier/prettier/pull/469#issuecomment-275591917.
