### ISSUE TITLE
How to enable max props per line

### ISSUE THREAD

**Issue by chuanxie** [prettier/prettier#2980]
I am trying to use `react/jsx-max-props-per-line` in the eslintrc setting to allow `"react/jsx-max-props-per-line": ["error", {"maximum": 1, "when": "multiline"}],`
but I cannot get it to work. prettier always give me the warning.

anyone knows how to override prettier?

I got `eslint-plugin-prettier` and `eslint-plugin-react` as well. 
the version of pretter is `1.7.4` and eslint `4.8.0`
 Thanks

**Comment by lydell** [comment]
Hi! Thanks for the issue! This has already been discussed before #2778. See that issue for more information, including the possible ways to go.
