### ISSUE TITLE
--write and --list-different can't agree; --write is producing incorrect results

### ISSUE THREAD

**Issue by iEchoic** [prettier/prettier#2985]
**Prettier 1.7.4**

Here's my code before running prettier:

![image](https://user-images.githubusercontent.com/8085742/31299872-74eb8ffe-aaa5-11e7-860d-d85142c6281e.png)

After running prettier with the command `prettier --write  "<redacted path>/**/*.jsx" --config <redacted path>/.prettierrc`, it erroneously tabs this section forward:

![image](https://user-images.githubusercontent.com/8085742/31299876-7b97e690-aaa5-11e7-9378-e87b5362b11a.png)

Then when I run `prettier --list-different "<redacted path>/**/*.jsx" --config <redacted path>/.prettierrc`, I get back an error that this file is different.

Here's the section of code that it's having trouble with:

```
            {(canClearAll || this.hasAnyOptionsDisabled) && (
                <div
                  className="UserActivitySettingsControlGroup-clear-all-text"
                  onClick={
                    this.hasAnyOptionsDisabled ? this._enableAllClicked : this._clearAllClicked
                  }
                >
                  {this.hasAnyOptionsDisabled ? 'enable all' : 'clear all'}
                </div>
              )}
```

Here's my .prettierrc:
```
{
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "es5",
  "bracketSpacing": false,
  "jsxBracketSameLine": false,
  "parser": "babylon",
  "semi": true,
  "requirePragma": false
}
```

This is only reproing when I run the command over my file, not in the sandbox. The filename ends in .jsx. Adding `--parser=babylon` to each doesn't work. Any ideas?

**Comment by lydell** [comment]
Can you make a repo or a gist which we can clone, and then run `npm install && npm test` to reproduce the problem?
