### ISSUE TITLE
Add Support for Virtual HyperScript function h

### ISSUE THREAD

**Issue by streamich** [prettier/prettier#2988]
As title says, add support for Virtual Hyperscript function `h`. If it sees the function name is `h` and it's
parameters conform to hyperscript function signature:

```
h(Element, props, ...children)
```
Then it should format output to look more like HTML.

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22function%20HelloWorld()%20%7B%5Cn%20%20return%20h('div'%2C%20%7B%7D%2C%5Cn%20%20%20%20h(Button)%2C%5Cn%20%20%20%20this.state.hide%20%3F%20null%20%3A%20h(Button)%2C%5Cn%20%20%20%20h('div'%2C%20%7BonClick%3A%20()%20%3D%3E%20this.setState(%7Bhide%3A%20!this.state.hide%7D)%7D%2C%5Cn%20%20%20%20%20%20%20%20'Toggle%20button%202'%5Cn%20%20%20%20)%5Cn%20%20)%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
function HelloWorld() {
  return h('div', {},
    h(Button),
    this.state.hide ? null : h(Button),
    h('div', {onClick: () => this.setState({hide: !this.state.hide})},
        'Toggle button 2'
    )
  );
}
```

**Output:**
```jsx
function HelloWorld() {
  return h(
    "div",
    {},
    h(Button),
    this.state.hide ? null : h(Button),
    h(
      "div",
      { onClick: () => this.setState({ hide: !this.state.hide }) },
      "Toggle button 2"
    )
  );
}

```

**Expected behavior:**

Should detect Virtual Hyperscript function `h` and format output as if it is HTML-ish:

```js
function HelloWorld() {
  return h('div', {},
    h(Button),
    this.state.hide ? null : h(Button),
    h('div', {onClick: () => this.setState({hide: !this.state.hide})},
        'Toggle button 2'
    )
  );
}
```

**Comment by streamich** [comment]
Same could be applied to JSON-ML:

```js
['div', {},
    [Button],
    this.state.hide ? null : [Button],
    ['div', {onClick: () => this.setState({hide: !this.state.hide})},
        'Toggle button 2'
    ]
]
```

**Comment by lydell** [comment]
Hi! This has already been discussed in #1949.

(Usually, it's really hard to search for duplicates in Prettier, but "hyperscript" is a super specific word and as such is super easy to look for :) Please remember to search for previous issues before opening issues in open source projects in the future 👍 )

**Comment by streamich** [comment]
#1949 does not discuss JSON-ML. Also, in this case prettier works as uglifier. It could be that should not look specifically for the hyperscript `h` function but have some general case to format these kind of nested functions better.
