### ISSUE TITLE
Backticks for single-line template literals without placeholders should pretty to quotes

### ISSUE THREAD

**Issue by jaydenseric** [prettier/prettier#2996]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20foo%20%3D%20%60bar%60%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--single-quote
```

**Input:**
```jsx
const foo = `bar`;
```

**Output:**
```jsx
const foo = `bar`;
```

**Expected output:**
```jsx
const foo = 'bar';
```

**Comment by ikatyang** [comment]
See [Rationale.md](https://github.com/prettier/prettier/blob/master/Rationale.md#what-prettier-is-not-concerned-about):

> ## What prettier is _not_ concerned about
> 
> Here are a few examples of things that are out of scope for prettier:
> 
> - **Turning single/double quotes into template literals or vice versa.**
> - Adding/removing `{}` and `return` where they are optional.
> - Turning `?:` into `if then else`.

**Comment by k15a** [comment]
Template strings and strings are two different things in JavaScript so we will not change them.

**Comment by suchipi** [comment]
If you want this behavior, you can use prettier-eslint with the 'quotes' eslint rule.

**Comment by jaydenseric** [comment]
Yes, here is the specific eslint config `rules` entry to match `--single-quote`:

```json
{ "quotes": ["error", "single", { "avoidEscape": true }] }
```

Thanks for the speedy response guys, I did spend about 5 mins searching the repo for past issues but that Rationale.md doc must have slipped through the cracks 🙂
