### ISSUE TITLE
`resolveConfig` does not load `process.cwd()` by default

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#2997]
from README:

> #### `prettier.resolveConfig([filePath [, options]])`
> 
> `resolveConfig` can be used to resolve configuration for a given source file. The function optionally accepts an input file path as an argument, which **defaults to the current working directory**.

`prettier.resolveConfig()` should equal to `prettier.resolveConfig(process.cwd())` but:

```js
const prettier = require("prettier");
console.log(prettier.resolveConfig.sync()); //=> null
console.log(prettier.resolveConfig.sync(process.cwd())); //=> { ... }
```

steps to reproduce:

```sh
mkdir prettier-test
cd prettier-test
yarn add prettier
echo '{}' > .prettierrc
echo 'var r = require("prettier").resolveConfig; Promise.all([r(), r(process.cwd())]).then(console.log);' > test.js
node test.js
```

I've tried `v1.6.1` and `v1.7.4`, they behave the same, should we fix its behavior or just docs?

cc @azz 
cc @josephfrazier as this will affect editorconfig support if it's considered a bug.

**Comment by suchipi** [comment]
I'd prefer to update the docs so that filePath isn't optional, and add a note saying something along the lines of "you might want to use process.cwd()"

**Comment by josephfrazier** [comment]
Seconding @suchipi, that does feel a little cleaner and more "API-ish" than defaulting to `process.cwd()`

**Comment by azz** [comment]
Yeah I think we should just update the docs
