### ISSUE TITLE
Unnecessary parens added with ternary operator

### ISSUE THREAD

**Issue by billscheidel** [prettier/prettier#3001]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%20%20%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%7Bdata.toArray().map(item%20%3D%3E%20(%5Cn%20%20%20%20%20%20%20%20%20%20%3Cspan%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7BhasAlerts%20%3F%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CAlert%20style%3D%7Bthis.styles.alert%7D%20%20%2F%3E%20%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CIcon%20style%3D%7Bthis.styles.check%7D%20name%3D%5C%22check%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2Fspan%3E%5Cn%20%20%20%20%20%20%20%20))%7D%5Cn%20%20%20%20%20%20%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
      <div>
        {data.toArray().map(item => (
          <span>
            {hasAlerts ?
              <Alert style={this.styles.alert}  /> :
              <Icon style={this.styles.check} name="check" />
            }
          </span>
        ))}
      </div>
```

**Output:**
```jsx
<div>
  {data
    .toArray()
    .map(item => (
      <span>
        {hasAlerts ? (
          <Alert style={this.styles.alert} />
        ) : (
          <Icon style={this.styles.check} name="check" />
        )}
      </span>
    ))}
</div>;

```

**Expected behavior:**
```jsx
<div>
  {data
    .toArray()
    .map(item => (
      <span>
        {hasAlerts ?
          <Alert style={this.styles.alert} /> : 
          <Icon style={this.styles.check} name="check" />
        }
      </span>
    ))}
</div>;

```

**Comment by lydell** [comment]
This is very much intended. See #2208 and #2398.

**Comment by lydell** [comment]
@billscheidel _Humans_ requested that change because the already wrote their code like that :wink:

**Comment by suchipi** [comment]
FWIW, I think the rationale doc still says "we try to avoid adding parens", which isn't true anymore. That doc could use some love in general
