### ISSUE TITLE
eslint errors with prettier formatting (due to indentation and newline)

### ISSUE THREAD

**Issue by niftylettuce** [prettier/prettier#3002]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20beep%20%3D%20%7B%5Cn%20%20boop%3A%20()%20%3D%3E%20%7B%5Cn%20%20%20%20return%20%7B%5Cn%20%20%20%20%20%20baz%3A%20()%20%3D%3E%20%7B%7D%5Cn%20%20%20%20%7D%3B%5Cn%20%20%7D%5Cn%7D%3B%5Cn%5Cnbeep.boop().baz('foo'%2C%5Cn%20%20%7B%5Cn%20%20%20%20some%3A%20%7B%5Cn%20%20%20%20thing%3A%20%7B%5Cn%20%20%20%20%20%20%20%20nested%3A%20true%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%7D%5Cn%20%20%7D%2C%5Cn%7B%20another%3A%20%7B%20thing%3A%20true%20%7D%20%7D%2C%5Cn()%20%3D%3E%20%7B%7D)%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
const beep = {
  boop: () => {
    return {
      baz: () => {}
    };
  }
};

beep.boop().baz('foo',
  {
    some: {
    thing: {
        nested: true
      }
  }
  },
{ another: { thing: true } },
() => {});
```

**Output:**
```jsx
const beep = {
  boop: () => {
    return {
      baz: () => {}
    };
  }
};

beep.boop().baz("foo",
{
  some: {
    thing: {
      nested: true
    }
  }
},
{ another: { thing: true } },
() => {});

```

**Expected behavior:**

It should not reformat with those errors.  Otherwise it throws this eslint error:

```sh
  test.js:10:1
  ✖  10:1  Delete ··                                      prettier/prettier
  ✖  11:1  Delete ··                                      prettier/prettier
  ✖  12:5  Expected indentation of 6 spaces but found 4.  indent
  ✖  13:1  Replace ········ with ······                   prettier/prettier
  ✖  13:9  Expected indentation of 6 spaces but found 8.  indent
  ✖  14:5  Delete ··                                      prettier/prettier
  ✖  14:7  Expected indentation of 4 spaces but found 6.  indent
  ✖  15:3  Expected indentation of 4 spaces but found 2.  indent
  ✖  16:1  Delete ··                                      prettier/prettier
```

I'm using https://github.com/prettier/eslint-plugin-prettier and that's how I discovered this bug.

**Comment by niftylettuce** [comment]
fwiw here's the `eslint --fix` output:

```js
const beep = {
  boop: () => {
    return {
      baz: () => {}
    };
  }
};

beep.boop().baz('foo',
  {
    some: {
    thing: {
        nested: true
      }
  }
  },
{ another: { thing: true } },
() => {});
```

also, I'm on eslint v3.x

**Comment by lydell** [comment]
Hi! Thanks for your issue!

As far as I understand, your problem is not that Prettier and ESLint disagree, but that Prettier has printed your code with weird indentation. That’s already tracked in #2984, so I’m closing in favor of that one.

**Comment by niftylettuce** [comment]
Thank you for being so clear @lydell, appreciate it, will follow #2984
