### ISSUE TITLE
prettier.resolveConfig does not apply overrides for absolute paths

### ISSUE THREAD

**Issue by not-an-aardvark** [prettier/prettier#3005]
**Prettier 1.7.4**

`.prettierrc`

```json
{
  "singleQuote": true,
  "overrides": [
    {
      "files": "folder/foo.js",
      "options": {
        "singleQuote": false
      }
    }
  ]
}

```

**Input:**
```js
const path = require('path');
const prettier = require('prettier');

console.log(prettier.resolveConfig.sync('folder/foo.js'));
console.log(prettier.resolveConfig.sync(path.resolve('folder/foo.js')));
```

**Output:**
```js
{ singleQuote: false }
{ singleQuote: true }
```

**Expected behavior:**

```js
{ singleQuote: false }
{ singleQuote: false }
```

This is causing https://github.com/prettier/eslint-plugin-prettier/issues/59, because `eslint-plugin-prettier` passes an absolute path to `prettier.resolveConfig`.

**Comment by azz** [comment]
I must be missing something, the test case I added in 062ea42 passes without code changes.

**Comment by not-an-aardvark** [comment]
To clarify, were you able to reproduce the issue based on the original description? I'm unsure whether you mean that (a) the repro instructions are correct and you're unsure what's wrong with the test, or (b) I made a mistake with the repro instructions and you can't reproduce the issue at all.

**Comment by azz** [comment]
I thought it would be a simple one and just straight to writing a test. I haven't had a change to try the repro steps precisely. Will update when I do.

**Comment by azz** [comment]
Finally got back to this one. Turns out this is only a problem if the `files` property has no glob magic. Managed to get the test to fail without the code change, so it's good to PR now.
