### ISSUE TITLE
Fighting with spaces in JSX.

### ISSUE THREAD

**Issue by t1ger-0527** [prettier/prettier#3006]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22import%20React%20from%20'react'%5Cn%5Cnconst%20Foo%20%3D%20()%20%3D%3E%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20This%20block%20should%20not%20be%20padded%20with%20space.%7B%2F*%5Cn%20%20%20%20*%2F%7D%3Cspan%3EBa%3C%2Fspan%3E%7B%2F*%5Cn%20%20%20%20*%2F%7Daaaaaaar%5Cn%20%20%3C%2Fdiv%3E%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%2C%22output2%22%3Afalse%7D%7D)

**Input:**
```jsx
import React from 'react'

const Foo = () => (
  <div>
    This block should not be padded with space.{/*
    */}<span>Ba</span>{/*
    */}aaaaaaar
  </div>
)
```

**Output:**
```jsx
import React from "react";

const Foo = () => (
  <div>
    This block should not be padded with space.{/*
    */}
    <span>Ba</span>
    {/*
    */}aaaaaaar
  </div>
);

```

**Expected behavior:**
Prettier should not correct this case, the comment block is placed this way on purpose.

**Comment by lydell** [comment]
I guess you're used to how whitespace works in HTML?

```html
<!-- Causes unwanted spaces around the span. -->
<div>
  This block should not be padded with space.
  <span>Ba</span>
  aaaaaaar
</div>

<!-- Gets rid of the spaces, but the line is a bit long. -->
<div>
  This block should not be padded with space.<span>Ba</span>aaaaaaar
</div>

<!-- Using comments as a workaround. -->
<div>
  This block should not be padded with space.<!--
  --><span>Ba</span><!--
  -->aaaaaaar
</div>
```

But **Babel does not handle whitespace like HTML.** Whitespace is stripped in some cases to allow you to format your code in a readable way without introducing unwanted spaces.

The input and output are equivalent. You don't even need the comments. The following is equivalent as well:

```jsx
const Foo = () => (
  <div>
    This block should not be padded with space.
    <span>Ba</span>
    aaaaaaar
  </div>
);
```

Check out the [Babel repl](http://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAYiEBGGBeGAKAlGgfJgKBhgB4ATASwDdcjiYAVACwohgCMAbEYAaxghMQAV05kYYELHYBTGAAcAhmTIzxAdwpQmApcBkA6AN4B6AFR1iZkwF8SEJWFwAhRSRMPFT0xfoxrNopBwYoATnTulDQEWAQEoJCwCCAATGiYOKj4GBFRtH7MrBzcfAJCouKS0nJKKmowmtq6ivrG5pb-th32ji5uHr0dPh0BIcHhxJHUtFgA3HEJ0PCIAMzp2HiEk3kdhWxcPPyCImISUhw1yqoaWjqerd2eTq7uT_n0Y0ETpCY7c0A&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0) to see how whitespace is stripped.

(If the above isn't your issue, just leave a comment and we'll reopen!)
