### ISSUE TITLE
Previous node ignored if prettier-ignore is the last line

### ISSUE THREAD

**Issue by imranolas** [prettier/prettier#3008]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22Promise.resolve().then().then()%3B%5Cn%5Cn%2F%2F%20prettier-ignore%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
Promise.resolve().then().then();

// prettier-ignore
```

**Output:**
```jsx
Promise.resolve().then().then();

// prettier-ignore

```

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22Promise.resolve().then().then()%3B%5Cn%5Cn%2F%2F%20prettier-ignore%5Cn%5CnPromise.resolve().then().then()%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
Promise.resolve().then().then();

// prettier-ignore

Promise.resolve().then().then();
```

**Output:**
```jsx
Promise.resolve()
  .then()
  .then();

// prettier-ignore

Promise.resolve().then().then();

```

When the `// prettier-ignore` comment is the last line, it ignores the previous node.

**Expected behavior:**

The first line should be formatted in both examples.

**Comment by azz** [comment]
This is likely due to the way comments with in prettier. They are attached to AST nodes, and in this case there's nothing after the comment so it is added as a dangling comment of the previous statement.

We could probably fix it by checking that the start index of the comment is less than the start index of the AST node.

I'm curious what caused you to find this issue? Was it just by observation, or is it causing a real issue?

**Comment by imranolas** [comment]
Granted it's very much an edge case. I actually found it whilst attempting to recreate another issue with `prettier-ignore`.

**Comment by duailibe** [comment]
@azz There's a case where we expect a `prettier-ignore` in a line after the node:

https://github.com/prettier/prettier/blob/b53a426e153247b309ac693763a4613905aa7bfb/tests/ignore/ignore.js#L59-L60

**Comment by azz** [comment]
Found it - looks like it is:

https://github.com/prettier/prettier/pull/671#issuecomment-279591481

**Comment by azz** [comment]
Going to close this as there could be cases where people are relying on the lack of a leading check, and fixing this would break them for no good reason.
