### ISSUE TITLE
prettier-ignore causes an extra semicolon

### ISSUE THREAD

**Issue by imranolas** [prettier/prettier#3009]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%2F%2F%20prettier-ignore%5Cn%5Ct'some%20text'%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
// prettier-ignore
	'some text';
```

**Output:**
```jsx
// prettier-ignore
'some text';;

```

**Expected behavior:**
I'd expect indentation to be preserved in the output. (There's also an additional semi colon in the output)

**Comment by thorn0** [comment]
The indentation isn't supposed to be preserved, but the extra semicolon is a bug.
