### ISSUE TITLE
Prettier should not move eslint-disable-line comment from the current line

### ISSUE THREAD

**Issue by keul** [prettier/prettier#3011]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22for%20(const%20id%20in%20obj)%20%7B%20%2F%2F%20eslint-disable-line%5Cn%20%20console.log(id)%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%2C%22output2%22%3Afalse%7D%7D)

**Input:**
```javascript
for (const id in obj) { // eslint-disable-line
  console.log(id)
}
```

**Output:**
```javascript
for (const id in obj) {
  // eslint-disable-line
  console.log(id);
}
```

The comment for disable eslint on the current line must not be moved

**Comment by lydell** [comment]
Hi! This is unfortunately a known problem with Prettier. We recommend using `// eslint-disable-next-line` instead. See #2549 and #1267.
