### ISSUE TITLE
Support CJK and emoji in markdown

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#3013]
from @azu https://github.com/prettier/prettier/pull/2943#issuecomment-335819324:

> I have a question.
> Does this markdown formatter support multi-bye language like Japanese or emoji?
> 
> It seem that current implementaion has two problems.
> 
> First, current implementation will be broken in Chinese-Japanese-Korean(CJK) and emoji.
> Because, some printing algorithm depened on `string.length`.
> 
> For example, `"❤️".length` is `2`. Following algorithm jolt out of alignment.
> 
> - https://github.com/prettier/prettier/pull/2943/files#diff-385bd78c43a57ae55923bfea744a5ae3R359
> 
> This issue is known as East Asian Width or Unicode problem.
> 
> - [UAX #11: East Asian Width](http://unicode.org/reports/tr11/ "UAX #11: East Asian Width")
> - [JavaScript has a Unicode problem · Mathias Bynens](https://mathiasbynens.be/notes/javascript-unicode "JavaScript has a Unicode problem · Mathias Bynens")
> 
> I know that East Asian Width problem is very difficult.( I don't know perfect solution...)
> Some library get unicode length.
> 
> - [timoxley/wcwidth: Port of C's wcwidth() and wcswidth()](https://github.com/timoxley/wcwidth)
> - [sindresorhus/string-width: Get the visual width of a string - the number of columns required to display it](https://github.com/sindresorhus/string-width)
> - [power-assert-runtime/packages/power-assert-util-string-width at master · twada/power-assert-runtime](https://github.com/twada/power-assert-runtime/tree/master/packages/power-assert-util-string-width)
> 
> Second, Following tokenizer can not tokenize non-English text.
> Because, non-English text like cheniese doesn't put a space between words.
> 
> ```
>     .split(/(\s+)/g)
> ```
> 
> - https://github.com/prettier/prettier/pull/2943/files#diff-0f09e16c6ee7c5a40fef83b315027002R149
> 
> It will be resolved by using tokenizer like [nlcst-parse-japanese](https://github.com/azu/nlp-pattern-match/tree/master/packages/nlcst-parse-japanese "nlcst-parse-japanese"), [parse-english](https://github.com/wooorm/parse-english "parse-english"), and [rakutenma](https://github.com/rakuten-nlp/rakutenma "rakutenma").
> But, It is not realistic and is not perfect. because toknizer is heavy weight(File size is large and Parse speed is slow)
>
> Toknizer example is [Text Tokenizer · Hivemall User Manual](https://hivemall.incubator.apache.org/userguide/misc/tokenizer.html "Text Tokenizer · Hivemall User Manual")
> 
> 
> Thanks.

**Comment by ikatyang** [comment]
from @ikatyang https://github.com/prettier/prettier/pull/2943#issuecomment-335841160:
> Thanks for the suggestion, I've already thought about it and just merged #3003 to fix the printer first, the CJK support is working in progress now, but it should be in a separate PR I think, this PR is somehow too large.
> 
> I think there's no need to use tokenizer for CJK, since AFAIK they can be broke in any place, and that's how CJK books printed, e.g.
> 
> ```
> 一串很長很長很長很長很長很長很長很長很長很長很長的中文字，一串很長很長很長很長很長很
> 長很長很長很長很長很長的中文字，一串很長很長很長很長很長很長很長很長很長很長很長的中
> 文字，一串很長很長很長很長很長很長很長很長很長很長很長的中文字。
> ```
> 
> For the string width thing, use [`string-width`](https://github.com/sindresorhus/string-width) should be enough, but we have to disable the `stripAnsi` feature.

**Comment by azz** [comment]
Was this done in #3015?

**Comment by ikatyang** [comment]
No, I have to define how to split the CJK text, they're not separated by whitespaces.

**Comment by azz** [comment]
Gotcha!

**Comment by azu** [comment]
In the future, we will can use [Intl.Segmenter](https://github.com/tc39/proposal-intl-segmenter "Intl.Segmenter") API that is based on CLDR/ICU. 
(Currently, This proposal is [Stage 2](https://tc39.github.io/process-document/).)
Also, V8 has prefixed `Intl.v8BreakIterator` that is nonstandard segmentation API and deprecated

- [Intl: Consider deprecating Intl.v8BreakIterator · Issue #8865 · nodejs/node](https://github.com/nodejs/node/issues/8865 "Intl: Consider deprecating Intl.v8BreakIterator · Issue #8865 · nodejs/node")

**Comment by ikatyang** [comment]
We may have to add an option for splitting CJK texts (`--split-cjk-text`) as there will be an additional whitespace in the rendered content, some markdown converter (or via plugin) handles it properly but most of them are not.

(markdown)

```md
中文中文中文
中文中文中文
中文中文中文
```

(html)

```html
<p>中文中文中文
中文中文中文
中文中文中文</p>
```

(rendered content)

```
中文中文中文 中文中文中文 中文中文中文
```

There shouldn't be whitespaces between CJK characters.

```html
<p>中文中文中文中文中文中文中文中文中文</p>
```

```
中文中文中文中文中文中文中文中文中文
```

Related discussion: markdown-it/markdown-it#334
