### ISSUE TITLE
Add support for YAML files

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3017]
I'm not sure how difficult/useful it will be but I'm guessing that it's less complicated than adding Java or Python :D

**Comment by lydell** [comment]
Thanks for the idea! I'm going to close this for the same reason as #2326:

> I'm going to close this as we're not going to do it anytime soon, but I would encourage people to hack on it if you are interested :)

And #2465:

> We may support it in the future if someone is interested in building and maintaining support for it. But it's not something that we have on the roadmap for now, so I'm going to close this.

In other words, a YAML support PR would likely be accepted, but there's no need to keep an issue for it.

**Comment by ikatyang** [comment]
Things to notice: 

To support YAML, we'll need its AST parser implemented in JS with full feature (or main feature at least), but AFAIK the only AST parser for it is [`yaml-ast-parser`](https://github.com/mulesoft-labs/yaml-ast-parser) and [it does not support comments](https://github.com/mulesoft-labs/yaml-ast-parser/issues/27).

**Comment by ascorbic** [comment]
I've not tried it, but there is now a YAML AST parser that claims to support comments: https://github.com/eemeli/yaml

**Comment by lipis** [comment]
@evilebottnawi what else do we need to discuss?  We just need someone to implement it..

**Comment by lipis** [comment]
Right! Good question.. my vote is to be part of Prettier as it's just another configuration file like JSON.

**Comment by evilebottnawi** [comment]
I support this as part of prettier

**Comment by nevir** [comment]
Might be able to leverage https://github.com/redhat-developer/yaml-language-server which has (basic) formatting

**Comment by azz** [comment]
Hey @ikatyang, have you started this? I wouldn't mind giving it a go!

**Comment by ikatyang** [comment]
Opened PR #4563, feedbacks welcome.

**Comment by nacimgoura** [comment]
Today, yaml is supported by prettier ?
