### ISSUE TITLE
Different indent for different languages is important!

### ISSUE THREAD

**Issue by sebastijandumancic** [prettier/prettier#3019]
Hi all,

as far as I know, Prettier still doesn't support different indenting for different languages. Case in point: 

This is my setup for JS:
```
"[javascriptreact]": {
    "editor.tabSize": 2
},
"[javascript]": {
        "editor.tabSize": 2
}
```

And this *should* be setting for CSS
```
"[css]": {
    "editor.tabSize": 4
 },
"[postcss]": {
    "editor.tabSize": 4
 }
```

But the CSS settings keep getting ignored, and CSS gets two spaces indent. It would be awesome if we could get this to work. Or am I doing something wrong? Thanks all!

**Comment by ikatyang** [comment]
Hi, it seems what you're saying is about vscode integration, which should be reported to [`vscode-prettier`](https://github.com/prettier/prettier-vscode/issues).

And in this case, you can use config file to determine which option to apply based on the filename (e.g. `*.js`, `*.jsx`), see [Configuration Overrides](https://github.com/prettier/prettier#configuration-overrides).
