### ISSUE TITLE
Changes string contents in at-rules

### ISSUE THREAD

**Issue by tzi** [prettier/prettier#3021]
Hi everyone!

In SCSS, we can output some text with `@debug`, `@warn` and `@error` directive.
I noticed that prettier try to reformat my text, like adding a space after parenthesis.

**Input:**
```scss
@if ($error) {
  @error 'error (#{$error}).';
}
```

**Output:**
```scss
@if ($error) {
  @error 'error (#{$error}) .';
}
```

Here is a [Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%40if%20(%24error)%20%7B%5Cn%20%20%40error%20%27error%20(%23%7B%24error%7D).%27%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22scss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D) (prettier 1.7.4).

Thanks for a lot this tool!

Cheers,
Thomas.

**Comment by lydell** [comment]
Good catch! What's happening here is that the parser does not consider that to be a string at all, so all sorts of weird things could happen.

**Comment by zeorin** [comment]
I'm also having this issue with [node-sass-selector-importer](https://github.com/maoberlehner/node-sass-magic-importer/tree/master/packages/node-sass-selector-importer):

__Input:__
```
@import '{ $shadow, $accent-1, $placeholder } from settings/colour';
```

__Output:__
```
@import , $accent-1, $placeholder } from settings/colour';
```

Temporary workaround:
```
@import '{ $shadow } from settings/colour';
@import '{ $accent-1 } from settings/colour';
@import '{ $placeholder } from settings/colour';
```
