### ISSUE TITLE
Expose list of supported parsers, etc.

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3023]
Currently every time Prettier adds another language, a lot of editor integrations have to release another version of their plugin to support it. This might be adding more language types, extensions, etc.

I'm wondering if we'd be able to support some kind of feature detection within Prettier that editor integrations can call and run more dynamically. Something along the lines of:

```js
require('prettier').getSupportInfo();
```

Which might return:

```js
{
  languages: [
    {
      language: "javascript",
      parsers: ["babylon", "flow"],
      ids: ["javascript", "javascriptreact"],
      extensions: [".js", ".jsx", ".mjs"]
    },
    {
      language: "typescript",
      parsers: ["typescript"],
      ids: ["typescript", "typescriptreact"],
      extensions: [".ts", ".tsx"]
    },
    ...
  ]
}
```

Would be nice to release this alongside Markdown support.

Love to get some feedback from some plugin maintainers on whether this kind of thing could be useful.

cc. @robwise @CiGit @mitermayer

**Comment by robwise** [comment]
Yeah I definitely think that would be helpful

**Comment by CiGit** [comment]
This may be useful from what I see here to have a map between language ids and parsers.
We will still need to release a new version if a language is added. In our case it would be a new setting `<LANGUAGE>Enable`. We maybe could find a way to avoid those.

Are those `language.ids` something common to other editors? I know them from vscode.

**Comment by robwise** [comment]
> Are those language.ids something common to other editors? I know them from vscode.

Atom has "scopes," sort of like CSS selectors, I assume they are going to be slightly different for each editor, assuming the editor has that. So we may have to write our own mappings. 

![atom settings](https://cl.ly/1Z2N0T1g1V41/Image%202017-10-14%20at%203.57.40%20AM.png)

Also, we format code embedded in `<script>` tags inside normal `.html` files so I don't think the extensions thing is going to work? But having the ability to know ahead of time that a certain local version of prettier lacks the parser needed for the scope, that would be very useful.

**Comment by CiGit** [comment]
Knowing for local version what it supports is indeed welcome. Even if it won't be useful in a near future. Older version would still need to be handled by us. `getSupportInfo is not a function`

language.ids seems to target vscode ;-)

**Comment by azz** [comment]
It does :P

We could use these instead: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L4615

```js
{
  language: "typescript",
  aliases: ["ts"],
  extensions: [".ts", ".tsx"],
  tmScope: ["source.ts"],
  aceMode: ["typescript"],
  codemirrorMode: "javascript"
  codemirrorMimeType: "application/typescript"
}
```

**Comment by ikatyang** [comment]
FYI, if `getSupportInfo is not a function` you can use `getSupportInfo` from the bundled prettier, which should always support this feature.

The support info may contains the `since` field, e.g. `since: "1.4.0"`.

**Comment by azz** [comment]
That's a great idea. Means you can still use the old version of prettier to do the formatting, but you know from a future version of prettier which parsers it supports.

**Comment by azz** [comment]
@robwise Can the settings panel be built dynamically or does it have to be defined statically via the schema?

**Comment by CiGit** [comment]
I though about `getSupportInfo` from bundled, but if the point is to not have to update the extension for each release the function should have a way to query the loaded one (or to know ahead of time...)

>We could use these instead: github/linguist:lib/linguist/languages.yml@master#L4615

@azz with that  we would have all but vscode 😄 which works with its languageids.

**Comment by azz** [comment]
Oops, didn't mean to delete language IDs. Edited the comment.

**Comment by azz** [comment]
Algorithm would be:

```js
let local = requireLocal("prettier")
let bundled = require("prettier")
// fallback to bundled if not found locally
let { format, version } = local || bundled;

let supportInfo = (local && local.getSupportInfo)
  ? local.getSupportInfo(version)
  : bundled.getSupportInfo(version)

let shouldFormat = supportInfo.languages.find(l =>
  l.languageIds.includes(currentLanguageId)
)
```

**Comment by CiGit** [comment]
I first thought all of this would be done inside `getSupportInfo(version)`

I can see this work for us (vscode) and simplify some of our code path.
(And merging our `<language>Enable` in `enable:languageIds[]` this way we won't have to update with each release)

**Comment by mitermayer** [comment]
Hi @azz, Thanks a lot for putting this together!

This is definitely great, for vim this would not avoid having to do a new release however would def make it easier to triaging reported bugs caused by users with older/incompatible  versions of prettier.

**Comment by robwise** [comment]
> @robwise Can the settings panel be built dynamically or does it have to be defined statically via the schema?

Statically :(

**Comment by azz** [comment]
Seeking some more feedback on the implemention #3033. If there's anything you can think of that should go in there, let me know!
