### ISSUE TITLE
Should use the most popular unordered list style

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#3025]
Based on @azz https://github.com/prettier/prettier/pull/2943#issuecomment-336607685:

> Big Data research part two: https://bigquery.cloud.google.com/savedquery/652929483875:69be015faec8444c8a2e7d055eeb32f8
> 
> `* item` | `- item` | `+ item`
>  -- | -- | --
> 642,106 | 413,627 | 10,954
> 
> type | regex
> --|--
> `* item` | `/^\s*\*\s/gm`
> `- item` | ` /^\s*-\s/gm`
> `+ item` | ` /^\s*\+\s/gm`

Should change

- listItem: `-`(always), `+`(switch between two style for continuous lists)
- thematicBreak: `- - -`(always), `* * *` (in list)

to

- listItem: `*`(always), `-`(switch between two style for continuous lists)
- thematicBreak: `- - -`(always), `- - -` (in `*`-style list), `* * *` (in `-`-style list)

**Comment by suchipi** [comment]
FWIW, I've always used `*` for list items, and `---` for thematic break

**Comment by ikatyang** [comment]
`---` may conflict with yaml's syntax if you put two thematic breaks together:

```md
---

---
```

so we decided to use `- - -`.

---

For the continuous lists, we have to choose another style for them, otherwise they'll be considered the same list, so I think the second popular `-` should be suitable.

```md
* 123
* 123

- 456
- 456
```

```html
<ul>
  <li>123</li>
  <li>123</li>
</ul>
<ul>
  <li>456</li>
  <li>456</li>
</ul>
```

**Comment by nhoizey** [comment]
I've always used `-` for unordered lists, because it is what automatically becomes a list item in word processors like Microsoft Word or LibreOffice.

I find `*` really "ugly"… 😄

**Comment by ikatyang** [comment]
I do prefer `-`-style personally but as you can see in the BigQuery, the `*`-style is more popular.

**Comment by azu** [comment]
📝 Research regexp includes Horizontal Rule.
`/^\s*\*\s/gm` match `* * *`.
Also, `/^\s*-\s/gm` match `- - -`.

- http://spec.commonmark.org/0.27/#list-items

**Comment by lipis** [comment]
It's one of these cases that maybe they didn't know any better..! :) we should do it YAML style.. lists look better with `-`..

**Comment by nhoizey** [comment]
I agree with @lipis, maybe it's time to show everyone how `-` is better… :-D

**Comment by azz** [comment]
Oops, I merged  #3027 before reading these comments!

**Comment by SimenB** [comment]
+1 for `-`, mostly as it's used in yaml (and ms word, apparently!)

(I can't wait for MD support to be released)

**Comment by azz** [comment]
MSWord also support `*` FWIW (IIRC)

**Comment by vjpr** [comment]
@azz Are there any config settings for markdown.

I use `-` for everything, and `---` for line breaks. Much easier to type.

**Comment by ikatyang** [comment]
@vjpr 

You can still type `-` and `---`, Prettier will format all valid syntax.

**Comment by vjpr** [comment]
@ikatyang When I run prettier on `---` it turned it into `- - -`...

**Comment by ikatyang** [comment]
Yes, I mean you can still type `---` and Prettier will format it to `- - -`, you don't have to type `- - -` directly.

**Comment by vjpr** [comment]
I want it to be formatted to `---`. I've never even seen the `- - -` before. 

And `*` is two key presses, versus `-` which is one. Its not just style preference, its more keystrokes.

Could we please have a config option for these settings?

**Comment by azz** [comment]
Is there a way to unambiguously determine `---` as yaml or thematic break?

**Comment by ikatyang** [comment]
> I want it to be formatted to `---`. I've never even seen the `- - -` before. 

After second thought, the [YAML syntax from Front Matter](https://jekyllrb.com/docs/frontmatter/) seems only available on the first thing in the file, but `remark` allowed it to be in anywhere.

---

> And `*` is two key presses, versus `-` which is one. Its not just style preference, its more keystrokes.

You can still type `-` for unordered list, Prettier will format all valid syntax. I'm not sure why you mentioned the key presses repeatedly, all valid syntax are available for typing.

**Comment by vjpr** [comment]
> all valid syntax are available for typing.

But ideally you would want to type code that will be as close to the formatted version as possible. So if the standard only allows `*`, then you have to `shift+8` each time you want a list item. Dash is a lot more convenient.

Maybe it would be best to detect which is currently used and just keep that?

**Comment by ikatyang** [comment]
OK, the conflict between YAML syntax and continuous thematic breaks only occurred in the first thing in the file, which should always be considered as YAML.

My bad, the `---` style for thematic break should be fine.

**Comment by vjpr** [comment]
So can we offer an option to use dashes for lists?

**Comment by lipis** [comment]
Or actually use `-` by default.. we have to do some magic with BigQuery in GitHub's codebase to figure out the actual usage. Instead of the initial query of checking the total numbers of `-` vs `*` in all .md files, we have to figure out how many different .md files are using `-` vs `*`

So for each file we just have to figure out from the first found list which symbol is used.. can someone do that kind of magic to at least check what's actual most popular option from the users?

Maybe we can only check projects that have at least 5 stars.. just to make it a bit more acceptable.

**Comment by ashfurrow** [comment]
I'm disappointed to see Prettier favour `*` and provide no configuration option for `-`. From the stats listed above, 39% of markdown files use the `-`, right? That's a lot! And from the linked to GitHub issues above, we see that [some folks are trying prettier, then deciding against it](https://github.com/strongloop/loopback-next/pull/1139) because of this decision. I'm in that camp, too.

It seems like there's more discussion to be had about this issue, where would be the most appropriate place to have that discussion?

**Comment by ashfurrow** [comment]
@j-f1 Maybe you or some other contributor could open the issue? I'm new here and this line of the issue template has scared me off:

>  If you are requesting a new option, your request will almost certainly be denied.

**Comment by j-f1** [comment]
IMO we should just change the default behavior and not add an option.

**Comment by ashfurrow** [comment]
I agree! But like I said, I'm new here and have zero sway.

**Comment by evilebottnawi** [comment]
@ashfurrow Just create issue and add your opinion why you think the behavior should be changed (popular style guides, user experience, better reading or other). Thanks!

**Comment by ashfurrow** [comment]
Okay! Thanks for the encouragement. I've opened https://github.com/prettier/prettier/issues/4251 so if you're keen on `-` I'd recommend heading over an giving a 👍

**Comment by azz** [comment]
Locking this. Discussion has moved to #4251.
