### ISSUE TITLE
Auto-link should be printed as-is

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#3030]
Found in https://github.com/prettier/prettier/pull/3022#discussion_r144690127:

input

```md
https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/
```

output

```md
[https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/](https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/)
```

~~expected~~

```md
<https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/>
```

**Comment by ikatyang** [comment]
Print it with shortcut-style will conflict with http://spec.commonmark.org/0.25/#example-452, decided to print it as-is.

expected

```md
https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/
```

**Comment by lipis** [comment]
What about: `[https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/]()`

**Comment by ikatyang** [comment]
@lipis 

Its AST is different from the original one, see http://astexplorer.net/#/gist/c0b609d1c6886a215d9c94167a49d2b2/9d2d7803c4a74459492e84b3f7f62b62e7f1cde7

**Comment by lipis** [comment]
As far as I know.. the autolinking is not part of the spec, but of course most of the editors are doing it and it works on GitHub.. just wanted to mention the other option. I'm fine with it..

**Comment by ikatyang** [comment]
It's a part of the [GFM spec](https://github.github.com/gfm/#autolinks-extension-), printing it as-is should be suitable for both GFM and non-GFM user.

**Comment by ikatyang** [comment]
And there are some edge cases that the remark parser can't handle it properly:

```md
<<https://www.example.com> abc>
```

```json
[
    {
        "type": "link",
        "title": null,
        "url": "<https://www.example.com",
        "children": [
            {
                "type": "text",
                "value": "<https://www.example.com"
            }
        ]
    },
    {
        "type": "text",
        "value": " abc>",
    }
]
```
