### ISSUE TITLE
The autogenerated toc in the main README.md should comply with the new markdown parser

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3031]
Because it's breaking the tests.. #3022

**Comment by ikatyang** [comment]
Maybe we should run `node bin/prettier.js --write README.md` after `toc` and before `git diff`.

https://github.com/prettier/prettier/blob/2ef879f20d877793a3a9daf896b059349cb6c562/.travis.yml#L18-L19

**Comment by azz** [comment]
Or we could replace
https://github.com/prettier/prettier/blob/c3b965145bc7fb6c798d96b6e992a66b0cb857bd/scripts/table-of-contents.js#L11

with

```js
const newReadme = prettier.format(
  toc.insert(oldReadme, { maxdepth: 3, bullets: ["*", "+"] }),
  { parser: "markdown" }
);
```

**Comment by duailibe** [comment]
TOC was removed in #3139
