### ISSUE TITLE
Standalone parsers

### ISSUE THREAD

**Issue by avaly** [prettier/prettier#3034]
Currently the `prettier` package ships with all parsers bundled in the same package. It might be useful for some projects to selectively use the parsers they need only and not have to download the rest. I propose that the parsers should live in their own separate packages.

**Comment by azz** [comment]
```java
-rw-r--r--  1 azz  staff   165K  4 Oct 01:19 parser-babylon.js
-rw-r--r--  1 azz  staff   464K  4 Oct 01:19 parser-flow.js
-rw-r--r--  1 azz  staff    28K  4 Oct 01:20 parser-graphql.js
-rw-r--r--  1 azz  staff   189K  4 Oct 01:20 parser-parse5.js
-rw-r--r--  1 azz  staff   1.4M  4 Oct 01:20 parser-postcss.js
-rw-r--r--  1 azz  staff   1.5M  4 Oct 01:20 parser-typescript.js
-rw-r--r--  1 azz  staff   1.2M 15 Oct 01:51 prettier-1.7.4.tgz
```

The whole thing is only 1.2MB gzipped. Is the download really a concern?

**Comment by lydell** [comment]
> It might be useful for some projects

That's too vague to motivate this change.
