### ISSUE TITLE
'filepath' not available .prettierrc

### ISSUE THREAD

**Issue by johnjiang** [prettier/prettier#3042]
filepath is an config option but it doesn't seem supported in the configuration file and is not specified in the schema either http://json.schemastore.org/prettierrc

**Comment by lydell** [comment]
Do you mean the `--stdin-filepath` CLI option? How is it useful in .prettierrc?

**Comment by azz** [comment]
This is intentional. When using a config file, the filepath of the actual file is automatically provided, there's no need to put it in `.prettierrc`.
