### ISSUE TITLE
LESS: imports with globs get broken

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#3043]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%40import%20'..%2F!(style)%2F*.less'%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22less%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser less
```

**Input:**

I'm using https://github.com/just-boris/less-plugin-glob which adds support for imports like this:
```less
@import '../!(style)/*.less';
```

**Output:**
```less
@import '../!(style) /*.less';

```

**Expected behavior:**

Same as input.

**Comment by lydell** [comment]
Thanks for the issue! Merging with #3021.
