### ISSUE TITLE
"Ignored unknown option: _comment" — in VIM

### ISSUE THREAD

**Issue by getnashty** [prettier/prettier#3045]
My Vim config has:

```
Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript'
Plug 'sbdchd/neoformat'
```
&

```
augroup fmt
  autocmd!
  autocmd BufWritePre *.js,*.jsx Neoformat prettier
augroup END
```

After I save (:w) - prettier does reformat the file, but the top line is always:

`Ignored unknown option: _comment`

It happens in every file - always with the same message

**Comment by suchipi** [comment]
Could you post your .prettierrc? Also, I think @sbdchd is the right person to cc on this?

**Comment by getnashty** [comment]
Someone else had set this up in my project, there was a _comment key in my prettierrc file that was the culprit - thank you suchipi!
