### ISSUE TITLE
Ignored unknown option: $schema

### ISSUE THREAD

**Issue by michaeljota** [prettier/prettier#3047]
**Prettier 1.7.4**

When using `prettier` cli with a config file defining the schema of prettier, the cli complains about not knowing that option 

**Input:**
```json
{
  "$schema": "http://json.schemastore.org/prettierrc",
  "parser": "babylon",
  "bracketSpacing": true,
  "printWidth": 80,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false
}
```

**Output:** (on terminal)
```bash
Ignored unknown option: $schema
```

**Expected behavior:**
I think this should not be ignored and should be validated with only one possible value, the $schema itself.

**Comment by suchipi** [comment]
Is the `$schema` key used by a program to validate the shape? Or is that name a convention for humans to use to look up the schema?

**Comment by michaeljota** [comment]
I think is a convention. If you look at the schema itself, have a `$schema` key to validate the schema of the schema file.

**Comment by azz** [comment]
Yeah it's a convention. We should delete it in `resolveConfig`
