### ISSUE TITLE
JSDoc:  Wrong indent for already incorrect indents

### ISSUE THREAD

**Issue by RinatMullayanov** [prettier/prettier#3054]
**Prettier 1.7.4**
**TypeScript 2.5.3**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22export%20enum%20BindingEnum%20%7B%5Cn%20%20%2F**%5Cn%20%20%20*%20Administrative%20binding%5Cn%20%20%20*%2F%5Cn%20%20Administrative%20%3D%201%2C%5Cn%20%20%2F**%5Cn%20%20%20*%20Organization%20binding%5Cn%20%20%20*%2F%5Cn%20%20Organization%20%3D%202%2C%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20Technological%20binding%5Cn%20%20%20%20%20*%2F%5Cn%20%20Technological%20%3D%203%2C%5Cn%20%20%20%20%2F**%5Cn%20%20%20%20%20*%20PowerSupply%20binding%5Cn%20%20%20%20%20*%2F%5Cn%20%20PowerSupply%20%3D%204%2C%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22es5%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser typescript
--single-quote
--trailing-comma es5
```

**Input:**
```tsx
export enum BindingEnum {
  /**
   * Administrative binding
   */
  Administrative = 1,
  /**
   * Organization binding
   */
  Organization = 2,
    /**
     * Technological binding
     */
  Technological = 3,
    /**
     * PowerSupply binding
     */
  PowerSupply = 4,
}

```

**Output:**
```tsx
export enum BindingEnum {
  /**
   * Administrative binding
   */
  Administrative = 1,
  /**
   * Organization binding
   */
  Organization = 2,
  /**
     * Technological binding
     */
  Technological = 3,
  /**
     * PowerSupply binding
     */
  PowerSupply = 4,
}

```

**Expected behavior:**
```tsx
export enum BindingEnum {
  /**
   * Administrative binding
   */
  Administrative = 1,
  /**
   * Organization binding
   */
  Organization = 2,
  /**
   * Technological binding
   */
  Technological = 3,
  /**
   * PowerSupply binding
   */
  PowerSupply = 4,
}

```

**Comment by azz** [comment]
cc. @maxdeviant

**Comment by ikatyang** [comment]
This should be fixed by #2470.

(output from master branch)

```ts
export enum BindingEnum {
  /**
   * Administrative binding
   */
  Administrative = 1,
  /**
   * Organization binding
   */
  Organization = 2,
  /**
   * Technological binding
   */
  Technological = 3,
  /**
   * PowerSupply binding
   */
  PowerSupply = 4
}
```

**Comment by azz** [comment]
Yep. Just confirmed that myself.

**Comment by maxdeviant** [comment]
@azz Do you have an idea of when the next Prettier release will be so we can get that change rolled out?

**Comment by azz** [comment]
Soon, I think. Want to wrap up #3033 first.
