### ISSUE TITLE
The experimental HTML support unexpectedly leaks through the CLI

### ISSUE THREAD

**Issue by luisrudge** [prettier/prettier#3058]
Edit by @lydell:

```
prettier foo.html
```

The above formats foo.html as HTML. It should try to format it as JS (as usual with unknown file extensions, until  #2884 is resolved).

Original issue description:

`<script src="/build.js"></script>`

is being prettified to

`<script src="/build.js" />`

which prevents the script from running for some reason.

**Comment by lydell** [comment]
Hi! You unfortunately haven't provided enough information for us being able you. Could you fill out the issue template?

**Comment by luisrudge** [comment]
AFAIK, the playgorund doesn't run in "html" mode, so I can't repro there

**Comment by luisrudge** [comment]
I mean, I can repro, but this is treating code as javascript: https://prettier.io/playground/#%7B%22content%22%3A%22%3Cscript%20src%3D%5C%22%2Fbuild.js%5C%22%3E%3C%2Fscript%3E%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D

**Comment by luisrudge** [comment]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%3Cscript%20src%3D%5C%22%2Fbuild.js%5C%22%3E%3C%2Fscript%3E%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```html
<script src="/build.js"></script>
```

**Output:**
```html
<script src="/build.js" />;

```

**Expected behavior:**
```html
<script src="/build.js"></script>
```

**Comment by duailibe** [comment]
Prettier doesn't support HTML yet

**Comment by luisrudge** [comment]
Well, it sure enough is formatting my html files though.

**Comment by lydell** [comment]
@luisrudge Why don't you show us what you do?

**Comment by luisrudge** [comment]
if you call prettier passing a html file, it should do nothing, since it's not supported. currently, it's formatting the file.

**Comment by lydell** [comment]
@luisrudge Thanks! That's really bad, our unfinished, experimental HTML formatter is leaking through :(

**Comment by luisrudge** [comment]
urgh. sorry to be this confusing. It was hard for me to finally find the words! For now, I removed html files from the precommit hook (I thought html was already supported, my bad).

**Comment by azz** [comment]
I'll fix this in the getSupportInfo PR since we have the unreleased metadata there. #3033
