### ISSUE TITLE
Over-aggressive breaks for JSX conditionals

### ISSUE THREAD

**Issue by jwbay** [prettier/prettier#3059]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22function%20HelloWorld(props)%20%7B%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7Bprops.x%20%26%26%20props.y%20%26%26%20(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%3Eblahblahh%20alsjdhlk%20alskdhf%20aksdhfjalksdh%3C%2Fspan%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20)%7D%5Cn%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--tab-width 4
```

**Input:**
```jsx
function HelloWorld(props) {
    return (
        <div>
            {props.x && props.y && (
                <span>blahblahh alsjdhlk alskdhf aksdhfjalksdh</span>
            )}
        </div>
    );
}

```

**Output:**
```jsx
function HelloWorld(props) {
    return (
        <div>
            {props.x &&
                props.y && (
                    <span>blahblahh alsjdhlk alskdhf aksdhfjalksdh</span>
                )}
        </div>
    );
}

```

**Expected behavior:**

Input preserved

Possibly related to or a regression of https://github.com/prettier/prettier/issues/2483? I'm not sure if that was released for 1.7 or not.

**Comment by suchipi** [comment]
See also https://github.com/prettier/prettier/issues/2714 for some discussion.

I prefer your input, but we decided to go with what you see here (as of 1.7.0). 
I think it's worth revisiting eventually though.

**Comment by jwbay** [comment]
Fair enough!
