### ISSUE TITLE
TypeScript: Invalid line separation in case of Union Type

### ISSUE THREAD

**Issue by RinatMullayanov** [prettier/prettier#3060]
**Prettier 1.7.4**
**TypeScript 2.5.3**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22export%20interface%20IGridGroup%20%7B%5Cn%20%20fontWeight%3F%3A%20'initial'%20%7C%20'inherit'%20%7C%20'unset'%20%7C%20'normal'%20%7C%20'bold'%20%7C%20'bolder'%20%7C%20'lighter'%20%7C%20100%20%7C%20200%20%7C%20300%20%7C%20400%20%7C%20500%20%7C%20600%20%7C%20700%20%7C%20800%20%7C%20900%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22es5%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser typescript
--single-quote
--trailing-comma es5
```

**Input:**
```tsx
export interface IGridGroup {
  fontWeight?: 'initial' | 'inherit' | 'unset' | 'normal' | 'bold' | 'bolder' | 'lighter' | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;
}

```

**Output:**
```tsx
export interface IGridGroup {
  fontWeight?:
    | 'initial'
    | 'inherit'
    | 'unset'
    | 'normal'
    | 'bold'
    | 'bolder'
    | 'lighter'
    | 100
    | 200
    | 300
    | 400
    | 500
    | 600
    | 700
    | 800
    | 900;
}

```

**Expected behavior:**
I know how exactly it is right from the point of view of style, but definitely not in this way.

**Comment by lydell** [comment]
That's valid TypeScript. The decision to print unions this way was made way back in #67 and is not going to change by now. Sorry!
