### ISSUE TITLE
Inconsistent indentation of intersection types

### ISSUE THREAD

**Issue by kassens** [prettier/prettier#3064]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22type%20unionTest%20%3D%5Cn%20%20%7C%20%7B%5Cn%20%20%20%20%20%20propA%3A%20X%5Cn%20%20%20%20%7D%5Cn%20%20%7C%20%7B%5Cn%20%20%20%20%20%20propB%3A%20X%5Cn%20%20%20%20%7D%5Cn%20%20%7C%20%7B%5Cn%20%20%20%20%20%20propC%3A%20X%5Cn%20%20%20%20%7D%5Cn%20%20%7C%20%7B%5Cn%20%20%20%20%20%20propD%3A%20X%5Cn%20%20%20%20%7D%3B%5Cn%5Cntype%20intersectionTest%20%3D%5Cn%20%20%26%20%7B%5Cn%20%20%20%20%20%20propA%3A%20X%5Cn%20%20%20%20%7D%5Cn%20%20%26%20%7B%5Cn%20%20%20%20%20%20propB%3A%20X%5Cn%20%20%20%20%7D%5Cn%20%20%26%20%7B%5Cn%20%20%20%20%20%20propC%3A%20X%5Cn%20%20%20%20%7D%5Cn%20%20%26%20%7B%5Cn%20%20%20%20%20%20propD%3A%20X%5Cn%20%20%20%20%7D%3B%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
type unionTest =
  | {
      propA: X
    }
  | {
      propB: X
    }
  | {
      propC: X
    }
  | {
      propD: X
    };

type intersectionTest =
  & {
      propA: X
    }
  & {
      propB: X
    }
  & {
      propC: X
    }
  & {
      propD: X
    };

```

**Output:**
```jsx
type unionTest =
  | {
      propA: X
    }
  | {
      propB: X
    }
  | {
      propC: X
    }
  | {
      propD: X
    };

type intersectionTest = {
  propA: X
} & {
  propB: X
} & {
    propC: X
  } & {
    propD: X
  };

```

**Expected behavior:**
No change of input, or at least consistent indentation of the different branches.

**Comment by duailibe** [comment]
Looks like the treatment for intersection and unions are intentionally different, so I guess the correct output here would be like the following?

```js
type Props = {
  propA: X
} & {
  propB: X
} & {
  propC: X
} & {
  propD: X
};
```

It's also special casing going from "non objects" to object types, so that would look like:

```js
type Props = PropA &
  PropB & {
    propC: X
  } & {
    propC: x
  };
```

But I'm not sure how it should look like if you had the following instead:

**Comment by duailibe** [comment]
Is there a special reason we don't do the same for unions and intersections?

**Comment by lydell** [comment]
@duailibe I didn't even know we treated them differently :) I guess it is more uncommon to make long chains of `&` though, while long chains of `|` is pretty common.

**Comment by duailibe** [comment]
@lydell I didn't either, I've just found out while working on this bug :-)

**Comment by existentialism** [comment]
Ref: https://github.com/prettier/prettier/pull/1018
