### ISSUE TITLE
Reporting ugly

### ISSUE THREAD

**Issue by onecityuni** [prettier/prettier#3065]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
// code snippet
```

**Output:**
```jsx
// code snippet
```

**Expected behavior:**

**Comment by ikatyang** [comment]
It seems you haven't filled in anything, can you share the content you want to report?

**Comment by azz** [comment]
Closing this. Please re-open if you add details
