### ISSUE TITLE
[JS,TS] Range formatting ObjectExpression throws

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#3068]
Trying to format an ObjectExpression -- with at least 2 props -- throws. 

**Prettier master**

**Input:**
```sh
echo "const y = {a:1,b:2}" |  prettier --range-start 12 --range-end 14
```

**Output:**
```sh
[error] stdin: SyntaxError: Unexpected token, expected ; (1:7)
[error] > 1 | {a:1,b:2}
[error]     |       ^
```

**Expected behavior:**
Shouldn't throw and format the object as an object.
Note: if they were only 1 prop in the object it wouldn't throw but it would be considered as a `LabeledStatement`
```js
const y = {
     a: 1 ; // It would work with no-semi 
}
```
Other issue which seems highly related:
```sh
> echo "const y = [1]" |  prettier --range-start 11 --range-end 12
const y = [1;]
```

**Comment by suchipi** [comment]
This is a common gotcha with JavaScript parsers; I don't know if the ECMAScript standard specifies a labeled statement as higher parsing precedence than an object, but it's frequently implemented that way.

One workaround is to wrap the object in parens.

**Comment by suchipi** [comment]
Maybe the proper thing to do is change prettier to parse the entire input stream, then find which AST nodes are within with the selected range, and format them (using the nodes as parsed in the whole program). However, this would break formatting selected js within a markdown or vue file.
