### ISSUE TITLE
problem in "fill" call to fit()

### ISSUE THREAD

**Issue by acthp** [prettier/prettier#3071]
Sorry, no examples of bad output. Experimenting with "fill", I found that it would inexplicably break after the first word, if the fill had small indentation. With larger indentation, it would not break after the first word, which is somewhat backwards.

I believe the width parameter passed to fit() is incorrect, here:

https://github.com/prettier/prettier/blob/master/src/doc-printer.js#L274

I suspect it should be ```rem```, not ```width - rem```, which I believe is the current position (explaining why it happens only with small indent: if the current indent is less that the current word length, it causes a break).

I'm unaware of any particular code example that is incorrectly formatted due to this, but perhaps the JSX printer is affected.

**Comment by azz** [comment]
cc @karl

**Comment by karl** [comment]
Good catch!

I have a PR that fixes that and updates the test that hit this edge case:
https://github.com/prettier/prettier/pull/3081

**Comment by karl** [comment]
I've merged in the fix to `fill`, thanks for the great bug report!
