### ISSUE TITLE
Raise awareness with lint-staged problems with staging hunks.

### ISSUE THREAD

**Issue by juanjoLenero** [prettier/prettier#3076]
The proposed **lint-staged** workflow in the readme:
```
{
  "scripts": {
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,json,css}": [
      "prettier --write",
      "git add"
    ]
  }
}
```
Conflicts with git workflows that include commiting partial files via hunks. This can lead to bad commits where the whole file is pulled into the commit instead of just the selected hunks (file belonging to hunk is prettified -> whole new file is added).

A visible warning next to the snippet would probably help people avoid hitting this issue in the future. At least until okonet/lint-staged#62 is resolved.

**Comment by duailibe** [comment]
There is already a warning about this issue in README: https://github.com/prettier/prettier/blame/b53a426e153247b309ac693763a4613905aa7bfb/README.md#L406

But not in the site docs. Besides that, how we could make this issue clearer?

**Comment by juanjoLenero** [comment]
My bad, I completely missed the warning.

The message could be highlighted or at the very least more strongly worded. Adding it to the code-block as a comment right next to the `git add` line would increase visibility.

```
There is a limitation where if you stage specific lines this approach will stage the whole file after regardless. See this issue for more info.
```
->
```
This approach breaks staging separate lines/hunks in a file. See (Link to github issue detailing problem)
```

**Comment by lydell** [comment]
@juanjoLenero Feel free to send a PR! :)

**Comment by silvenon** [comment]
I like the idea of Prettier, this is just a current limitation of lint-staged, but I don't understand how anyone who partially stages files is ok with this limitation… 😕

Yay for submitting a PR with the warning!
