### ISSUE TITLE
Different original style inputs of object array output different style

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#3080]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20A%20%3D%20%5B%7Bid%3A1%2Cname%3A'a'%7D%2C%7Bid%3A2%2Cname%3A'b'%7D%5D%5Cn%5Cnconst%20B%20%3D%20%5B%7Bid%3A1%2Cname%3A'a'%7D%2C%7Bid%3A2%2Cname%3A'b'%7D%2C%7Bid%3A3%2Cname%3A%20'c'%7D%2C%7Bid%3A4%2Cname%3A'd'%7D%5D%5Cn%5Cnconst%20C%20%3D%20%5B%7Bid%3A1%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20name%3A'a'%7D%2C%7Bid%3A2%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2Cname%3A'b'%7D%2C%7Bid%3A3%2Cname%3A'c'%7D%2C%7Bid%3A4%2Cname%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'd'%7D%5D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--no-semi
--single-quote
```

**Input:**
```jsx
const A = [{id:1,name:'a'},{id:2,name:'b'}]

const B = [{id:1,name:'a'},{id:2,name:'b'},{id:3,name: 'c'},{id:4,name:'d'}]

const C = [{id:1,
            name:'a'},{id:2
                       ,name:'b'},{id:3,name:'c'},{id:4,name:
                                                   'd'}]

```

**Output:**
```jsx
const A = [{ id: 1, name: 'a' }, { id: 2, name: 'b' }]

const B = [
  { id: 1, name: 'a' },
  { id: 2, name: 'b' },
  { id: 3, name: 'c' },
  { id: 4, name: 'd' }
]

const C = [
  {
    id: 1,
    name: 'a'
  },
  {
    id: 2,
    name: 'b'
  },
  { id: 3, name: 'c' },
  {
    id: 4,
    name: 'd'
  }
]

```

**Expected behavior:**
*B* and *C* should output same and pretty style. It seems the output is related to original code style, I don't know it that as expected.

**Comment by ikatyang** [comment]
It works as expected, see [Rationale.md - Multi-line objects](https://github.com/prettier/prettier/blob/master/Rationale.md#multi-line-objects).
