### ISSUE TITLE
Add line break before else and if else

### ISSUE THREAD

**Issue by jagi** [prettier/prettier#3084]
I would like to use Prettier but I'm missing one important configuration options. I don't know how it's called but it can be called "adding line break before else and if else"

Here is an example of what I'm talking about:

**Input:**
```js
// First condition comment.
if (firstCondition()) {
  doSomething();
}
// Second condition comment.
else if (secondCondition()) {
  doSomethingElse();
}
```

**Output:**
```js
// First condition comment.
if (firstCondition()) {
  doSomething();
} else if (secondCondition()) {
  // Second condition comment.
  doSomethingElse();
}
```

**Expected behavior:**

**Output:**
```js
// First condition comment.
if (firstCondition()) {
  doSomething();
}
// Second condition comment.
else if (secondCondition()) {
  doSomethingElse();
}
```

It shouldn't move `else if` up and move comment into brackets. I very often want to add a comment just before the `else if` statement and it seems to be impossible to achieve with Prettier, or is it? Putting comment just before `if` or `else if` statement is a good practice. You can easily do it before the `if` statement but putting a comment for the `else if` inside brackets does not make any sense. Such a comment is responsible for describing the next line of code. Comments are always about describing current or the next line of code or block of code.

**Comment by azz** [comment]
It's kind of a bug in the way prettier prints comments, I'm merging this issue in with #2573

**Comment by waitingsong** [comment]
I prefer to use the style:
```js
// First condition comment.
if (firstCondition()) {
  doSomething();
}
// Second condition comment.
else if (secondCondition()) {
  doSomethingElse();
}
```
Because i can comment block of "else if" or "else" out quickly by vim through visual mode (shift+v), and do revert also quickly.

**Comment by lydell** [comment]
```js
if (firstCondition()) {
  doSomething();
// } else if (secondCondition()) {
//  doSomethingElse();
}
```

**Comment by waitingsong** [comment]
I think it's better:
```js
// First condition comment.
if (firstCondition()) {
  doSomething();
}
// Second condition comment.
// else if (secondCondition()) {
//  doSomethingElse();
// }
```

**Comment by lukejagodzinski** [comment]
I agree with you @waitingsong it looks much cleaner. Just by quickly looking at it you clearly see what is commented. With @lydell solution and with much more code you can get confused.

@waitingsong maybe add your suggestions to this thread https://github.com/prettier/prettier/issues/2573

**Comment by suchipi** [comment]
See also prior discussion in https://github.com/prettier/prettier/issues/807 and https://github.com/prettier/prettier/issues/840
