### ISSUE TITLE
JSX comment moves to wrong place

### ISSUE THREAD

**Issue by Argo483** [prettier/prettier#3087]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEBA9MQZALYUIz4B8+RwAZhBAL76rFbYNQgANCAgAHGJmgBnZKACGUmMmZyANlLjCARgCc5YANZwYAZVH7MUAObIYOgK6aQ6CGGVqNwgFZSAHgCE9Q2MTOWoAGUs4WwcnCHsYUQSAJnd1J3MdDR1kEC05LQBPVWghEFEdSxgAdUx0GAALZAAOAAZhDQpMGMcOyytVOABFewh4NM8QGALa+qakZOE7OUxVfoBhCCo5XKhoaOF7DQAVApkkFXT2diA)
```sh
--jsx-bracket-same-line
```

**Input:**
```jsx
<div
  // comment
>
  {foo}
</div>

```

**Output:**
```jsx
<div>
// comment
  {foo}
</div>;

```

**Expected behavior:**
same as input

**Comment by azz** [comment]
High-pri since the output creates a text node that looks like a comment.
