### ISSUE TITLE
Comment prettier-ignore seems to be ignored by VSCode plugin in HTML

### ISSUE THREAD

**Issue by Jackbennett** [prettier/prettier#3090]
```html
// prettier-ignore
---
draft: true
---
<h1>...
```

The above cannot seem to use `// prettier-ignore` in a way to prevent prettier from flattening the metadata into `--- draft: true ---` which my static site generator then chokes on.

Is there a config method I'm not finding? Closest other option would be to skip lines but it's not a fixed number of lines the metadata could use.

Maybe I've misunderstood how to use it. I couldn't see a config way to maybe extend prettier for the file type to teach it about `---`

Hope there's a solution, currently I'm just excluding the blog path.

**Comment by azz** [comment]
Prettier actually doesn't support HTML (_yet_, see #1882), so it's likely some other tool that is doing this formatting. prettier-vscode doesn't run prettier on HTML at all. My guess is that you're unknowingly using the built-in VSCode HTML formatter, which lives in the VSCode repo: https://github.com/Microsoft/vscode/tree/master/extensions/html/server

**Comment by Jackbennett** [comment]
My bad, I know I wrote those files in VSCode and prettier was a new addition. I guess I must have toggled "editor.FormatOnSave" in the interim.

**Comment by skube** [comment]
It's an easy miss, the [docs](https://github.com/prettier/prettier-vscode#format-on-save) say to turn on `editor.FormatOnSave`, though it's imperative that you turn it on only for JS:
```json
// Enable per-language
"[javascript]": {
    "editor.formatOnSave": true
}
```
