### ISSUE TITLE
Convert to single-line comments where possible in JSDoc

### ISSUE THREAD

**Issue by KrickRay** [prettier/prettier#3094]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABL9XAKQGUARCMXSAWxoRh33VRABoQIAHGAS2gDOyUAEMBMZADMRAGwFwOAIwBOIsAGs4MElzW8oAc2QxlAVwUgAJpSmz5HAFYCAHgCFVGrSRH0AMvrhbOQsIUxguMIAmIPsQXWV5ZWQQRRFFAE8ZaHY45X0YAHVeSxgAC2QADgAGDnkaXmMzCwF9Axk4AEVTCHgYixg0opLypEiOExFeGVaAYQg6EWSoaECOU3kAFTShJGlggF99oA)

**Input:**
```jsx
/**
  * JSDoc comment
  */
```

**Output:**
```jsx
/**
  * JSDoc comment
  */

```

**Expected behavior:**
```jsx
/** JSDoc comment */

```

**Comment by azz** [comment]
In general we dont modify comments at all. #265 tracks wrapping comments, and this would be doable as part of that. Question is, is this something that's generally preferred? I've certainly seen more cases of the multiline variant.

**Comment by KrickRay** [comment]
@azz I would not want the prettier to change comments like #265. 

Just when JSDoc is written in one line:
```
/**
  * JSDoc comment (Lorem ipsum dolor sit amet, utroque sensibus in sit, et duo unum aeque. Doctus nusquam an sea. Vocent eligendi facilisi ut qui. Has ad viris nobis ocurreret, cum erroribus liberavisse ex. Cu natum hendrerit vituperata pri, dicit consequat quaerendum eam an, eu vim putant volumus repudiare.)
  */
```
Format to:
```
/** JSDoc comment (Lorem ipsum dolor sit amet, utroque sensibus in sit, et duo unum aeque. Doctus nusquam an sea. Vocent eligendi facilisi ut qui. Has ad viris nobis ocurreret, cum erroribus liberavisse ex. Cu natum hendrerit vituperata pri, dicit consequat quaerendum eam an, eu vim putant volumus repudiare.) */
```
---
When we have a multi-line comment:
```
/**
  * JSDoc comment (Lorem ipsum dolor sit amet, utroque sensibus in sit, et duo unum aeque. Doctus nusquam an sea. Vocent eligendi facilisi ut qui. Has ad viris nobis ocurreret, cum erroribus liberavisse ex. Cu natum hendrerit vituperata pri, dicit consequat quaerendum eam an, eu vim putant volumus repudiare.)
  * Second line (Lorem ipsum dolor sit amet, utroque sensibus in sit, et duo unum aeque. Doctus nusquam an sea. Vocent eligendi facilisi ut qui. Has ad viris nobis ocurreret, cum erroribus liberavisse ex. Cu natum hendrerit vituperata pri, dicit consequat quaerendum eam an, eu vim putant volumus repudiare.)
  */
```
Leave unchanged:
```
/**
  * JSDoc comment (Lorem ipsum dolor sit amet, utroque sensibus in sit, et duo unum aeque. Doctus nusquam an sea. Vocent eligendi facilisi ut qui. Has ad viris nobis ocurreret, cum erroribus liberavisse ex. Cu natum hendrerit vituperata pri, dicit consequat quaerendum eam an, eu vim putant volumus repudiare.)
  * Second line (Lorem ipsum dolor sit amet, utroque sensibus in sit, et duo unum aeque. Doctus nusquam an sea. Vocent eligendi facilisi ut qui. Has ad viris nobis ocurreret, cum erroribus liberavisse ex. Cu natum hendrerit vituperata pri, dicit consequat quaerendum eam an, eu vim putant volumus repudiare.)
  */
```

**Regardless of the length of the line**

**Comment by KrickRay** [comment]
@azz Probably need to think about other cases

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABL7PA3AKQGUARCMXSAWzoRh30NZeLLkigBNcANgEsocDmwKoQAGhAQADjCHQAzslABDFTGQAzDQJVxZAIwBOGsAGs4MMvMsiA5shhmArsZC9qeg0dkAKxUADwAhC2tbMg1GABkROD9DLwh3GHl0gCZkgJAHMyMzZBATDRMATwFoGXyzERgAdSFeGAALZAAOAAZZIzohVw8vFWcBOABFdwh4XK8YcubWjqQs2TcNIWEoJwBhCAYNEqhoJNl3IwAVcrUkfRSAXwegA)

**Input:**
```jsx
/**
  *
  * JSDoc comment
  *
  *
  * Second line
  *
  */
```

**Output:**
```jsx
/**
  *
  * JSDoc comment
  *
  *
  * Second line
  *
  */

```

**Expected behavior:**
```jsx
/**
  * JSDoc comment
  *
  * Second line
  */
```

- delete empty lines at the top and bottom
- multiple empty lines in one empty line

**Comment by AlexNisnevich** [comment]
Having an option for this would be extremely helpful for my org.

**Comment by j-f1** [comment]
Considering adding support for JSDoc, although I’d need to find a sufficiently well-maintained parser.

**Comment by matchai** [comment]
I, too, have been looking for a solid JSDoc parser and have found TypeScript to provide the most consistently detailed ASTs. I think it would be worthwhile to create a separate issue to discuss plans around JSDoc support; what tools we can consider using, and start discussing what cases we would like to address.

**Comment by j-f1** [comment]
⏩ #5659
