### ISSUE TITLE
Less variable is lowercased when there's a space before the :

### ISSUE THREAD

**Issue by slorber** [prettier/prettier#3095]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAzhAtnAwgQxwBsD04A1fAJwEt8AjIuAAiWYHYAGTgBwA8A3CAA0ICDxg1o6ZKHzoYyAGb4iZUfSr4wAazgwAyj200oAc2QwqAVziiAJhDDLV6kACt0fAEJbd+g0I4ABlTOBc1OzFrGB4YgCYIt2MqMipkECZ0GVEeWlgAdRp7GAALZAAOTlEyLBpLGyj0UzMmAEVrCHgkqJgGIpLypHjRK3waIhbcbCx8DNUiERBrMgAVBhkkFUiAXx2gA)
```sh
--parser less
--trailing-comma all
```

**Input:**
```less
@someCamelCaseVariable : 700px;
```

**Output:**
```less
@somecamelcasevariable : 700px;

```

**Expected behavior:**

```less
@someCamelCaseVariable: 700px;
```

The input is valid less variable declaration and there's no reason "rename" the variable (since variable usages are not renamed as well)

The role of prettier here should probably just be to "normalize" variable declarations by just removing the useless space before the `:`

**Comment by slorber** [comment]
see for example a problematic case of my app:

![image](https://user-images.githubusercontent.com/749374/31944008-e9ae6798-b8ca-11e7-8f54-39de451976eb.png)

**Comment by ikatyang** [comment]
Hi, thanks for the report. This is already tracked in #2925, closing in favor of that.
