### ISSUE TITLE
"use strict"; should always have semi even when option no semi is specified

### ISSUE THREAD

**Issue by aymericbouzy** [prettier/prettier#3097]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdEBXAznABFmAJwEswZ0BuEAGhAgAcZjotlQBDA5AM3YBsctAEaF2YANZwYAZXpjiUAObIiGOLQAmEMD36CQAKywAPAEKiJU6ewC2cADIK4ugeroYY9DwCYX+uYQ4hMggQuxCAJ580DQg9CSwAOrEGjAAFsgAHAAMtDg2xH5uWAqKfHAAihgQ8EW0MOHJqRlI3vWixHylAMIQNjbsIVDQzrTYcAAq4axIvK4AvvNAA)
```sh
--no-semi
```

**Input:**
```jsx
"use strict";
```

**Output:**
```jsx
"use strict"

```

**Expected behavior:**
`"use strict";` should always be followed by a semi column, even when option `no-semi` is specified

**Comment by lydell** [comment]
Why?

**Comment by aymericbouzy** [comment]
Well I read 

> To invoke strict mode for an entire script, put the exact statement "use strict"; (or 'use strict';) before any other statements.

on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode, so I thought we should comply, but maybe we don't ... Maybe you know more about it than I do, is it valid without the semi? is it added automatically later on?

**Comment by aymericbouzy** [comment]
At the very least, it's confusing that Prettier is modifying a statement that is very specifically stated as not to be modified by MDN.

**Comment by lydell** [comment]
https://tc39.github.io/ecma262/#directive-prologue

> A Directive Prologue is the longest sequence of ExpressionStatements occurring as the initial StatementListItems or ModuleItems of a FunctionBody, a ScriptBody, or a ModuleBody and where each ExpressionStatement in the sequence consists entirely of a StringLiteral token followed by a semicolon. **The semicolon may appear explicitly or may be inserted by automatic semicolon insertion.**

**Comment by aymericbouzy** [comment]
Thanks @lydell, looks like `"use strict"` is valid when semi columns are automatically added afterwards. I didn't know. My bad!
