### ISSUE TITLE
ImportDeclaration should appear when the mode is ES6 and in the module context.

### ISSUE THREAD

**Issue by chenshuai2144** [prettier/prettier#3098]
**Prettier 1.7.4**
 
After the new version of the upgrade has been so, how can I modify.
 I use typescript ,tslint and mobx.

![image](https://user-images.githubusercontent.com/8186664/31948769-4b32e8ec-b90a-11e7-925f-286728516284.png)

**Comment by ikatyang** [comment]
I'm not seeing any `ImportDeclaration` in your screenshot, and I'm not sure what are you talking about, can you fill in the template so that we can understand easily?

**Comment by chenshuai2144** [comment]
sorry ,I might be wrong.
I think it's a question of annotation。


import { observable, action } from "mobx";
import { openFile } from "../data/PptStroe";
import { wordState } from "../data/WordStroe";
import { imageAction } from "../data/ImageStroe";

After the removal of this just fine

**Comment by ikatyang** [comment]
@chenshuai2144 

Can you fill in the issue template? I still don't know what are you talking about. And Prettier is a formatter, we just format code and do not add code, what do you mean "should appear"? It seems what you're talking about is the TypeScript Language Server.

**Comment by chenshuai2144** [comment]
sorry！
my English is poor！
I'm trying to build a little demo.
Thank you for your reply

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/31998682-40b7628a-b9c3-11e7-9505-d243118abfd8.png)
vscode  
Just modify the prettier.eslintIntegration on it
😭

**Comment by lydell** [comment]
1. Go to https://prettier.io/playground/
2. Paste code
3. Click "Copy markdown" button
4. Paste here

**Comment by jakeleboeuf** [comment]
I'm experiencing the same issue- but not clear where it's coming from.

For me, this line is the cause of the issue:

`import { TweenMax, Elastic } from 'gsap';`

**Comment by duailibe** [comment]
@jakeleboeuf what issue exactly you are experiencing?

**Comment by nnyegaard** [comment]
let me try to shred some light on this.

In VSCode I started to experience the following message from prettier when I saved my nodejs project:

> ImportDeclaration should appear when the mode is ES6 and in the module context.

It only happend in my nodejs project, using Webpack, Typescript and the import syntax - not in react with the same tech. 
The reason for this was the following setting:   
> "prettier.eslintIntegration": true,

if it's changed to false the message will "go away". So something with eslint is conflicting here.

**Comment by duailibe** [comment]
@nnyegaard can you share your ESLint config file?

**Comment by duailibe** [comment]
@nnyegaard Yeah, this looks like it's a problem with https://github.com/prettier/prettier-eslint or https://github.com/prettier/prettier-vscode (less likely). Unfortunately I don't use either so I'm not quite sure how to help with this. I suggest you open an issue on those repositories, with your ESLint config file and an example of a file that you're experiencing this error.

**Comment by nnyegaard** [comment]
Im not using eslint anymore, so it was more of an info to anyone experiencing thise

**Comment by FredyC** [comment]
I am using `create-react-app-typescript` and I was getting the same error in VSCode. I had `prettier.eslintIntegration` enabled globally and after turning it off, it's indeed working. However, there is no ESlint installed within that boilerplate so it's rather shocking how it can be relevant :)
