### ISSUE TITLE
A prettier site?

### ISSUE THREAD

**Issue by joecritch** [prettier/prettier#3099]
Hi folks,

I've just spent a little bit of time mocking up a visual refresh for the Prettier site.

If you like it, I'm happy to continue working on it, designing in browser from this point with new HTML and CSS, and no architectural/technical changes.

No dramas if you're not feeling it; I can take honesty. 👍 

![prettier-site 2x-border](https://user-images.githubusercontent.com/24449/31959019-76ee4c0c-b8eb-11e7-8c6f-0d309307d328.png)

cc @vjeux 

*Edit*: I understand this is just the homepage, and is not necessarily the most important page. I'd be happy to mockup a docs template

**Comment by vjeux** [comment]
Omg, it looks awesome! The current prettier website was just using the default template and wasn't even really meant to be promoted.

I'm onboard if you want to make it real :)

cc @azz, @ikatyang, @suchipi, @karl, @existentialism who also may be interested.

**Comment by mitermayer** [comment]
Looks great!! Please do it!

**Comment by karl** [comment]
Love it! 👍🏻

**Comment by joecritch** [comment]
Thanks all. Really happy you like it so far. Look out for a PR in due course 👍

**Comment by azz** [comment]
Yes! Let us know if you have any questions!

**Comment by joecritch** [comment]
I had an early PR here, #3115 (it was closed because it was so WIP)

After reassessing, I think customisation is too leaky for the kind of design I'm after here. It could easily break between Docusaurus updates, or have a regression through further customisation. I'd love to see custom stylesheets be replaced by React composition.

I'm going to pause on the build for now. If someone else wants to have a go, I'm happy to provide further visuals. Alternatively, I'd hold out for full React-based customisation.

**Comment by vjeux** [comment]
@joelmarcey would you be able to chat with @joecritch to figure out how to move forward?

**Comment by joecritch** [comment]
@joelmarcey You can find me on Hangouts joecritch@gmail.com or FB messenger, joe.critchley 👍 Would love to hash it out.

**Comment by JoelMarcey** [comment]
@joecritch Hi! Sure. I will try to set up a conversation with you this week. Hangouts or Messenger could work just fine. Just curious -- do you use Slack? That could be another option as well.

**Comment by joecritch** [comment]
@JoelMarcey Slack is good too :) Feel free to invite me to a channel with that same email. Cheers Joel.

**Comment by JoelMarcey** [comment]
@joecritch Hi. Sorry for the delay here getting back to this. I am planning on setting up a Docusuarus communication channel early next week. Maybe we can get together in that and discuss how to move forward here?

**Comment by joecritch** [comment]
@JoelMarcey Sounds great! Let us know :)

**Comment by orta** [comment]
Related: #3669 - I've been giving this a shot too

**Comment by sandhose** [comment]
I've done a fancy animation for the prettier logo for #3669 

Here are some iterations:

![2018-01-07 17_07_58](https://user-images.githubusercontent.com/1549952/34655344-14cb1c5a-f408-11e7-845a-f75f70bedc8e.gif)
![2018-01-07 23_40_59](https://user-images.githubusercontent.com/1549952/34655343-14aebb82-f408-11e7-854a-f562b366023e.gif)
![2018-01-08 00_06_13](https://user-images.githubusercontent.com/1549952/34655342-148d4b3c-f408-11e7-8dd3-7d493ef31b83.gif)

The code is here: https://github.com/sandhose/prettier-animated-logo, and you can see it live there: https://sandhose.github.io/prettier-animated-logo/

**Comment by vjeux** [comment]
You’re all so awesome! I can’t wait to see the end result live :)

**Comment by sandhose** [comment]
I just [started a branch](https://github.com/sandhose/prettier/tree/animated-logo) which integrates the animated logo in the prettier website. 
It's WIP, the code is quite ugly ; I haven't found a clean solution to inject dynamically created CSS with docusaurus, so there's a [`<style>` tag](https://github.com/sandhose/prettier/blob/eef9335a6e1cb0c90293074b4b1b6eaf20f85efc/website/core/AnimatedLogo.js#L72) with CSS created on the fly.

![2018-01-08 19_51_32](https://user-images.githubusercontent.com/1549952/34687083-fce5c206-f4ad-11e7-8e08-6bf55ed8a2de.gif)

**Comment by j-f1** [comment]
The [Docusaurus docs](http://docusaurus.io/docs/en/api-pages.html#styles) say:

> You can provide your own custom styles by adding them anywhere in the `website/static` folder. Any `.css` files you provide in the `static` folder will get concatenated to the end of Docusaurus's provided styles, allowing you to add to or override Docusaurus default styles as you wish.

**Comment by lipis** [comment]
I think we already have the Prettier site :) So I'll close this issue.
