### ISSUE TITLE
Consistent quotes in object key properties

### ISSUE THREAD

**Issue by ismail-syed** [prettier/prettier#3100]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhuAB0oaaByAMwgnaRoCMAGhZt2AIwCG5PjQBMI1h24QAtFJn8AzIoC+AbhYghICCRgBLaFWShJVGMk6ScVOCfHlJYANZwYAMok3hZQAOZOLm4mGBBgka7uIABWVEQAQl6+-gGSqHAAMqFwCdGmWDAkFXKlScHkbuTIIFLiAJ440MYgJOShMADqFhgwABbIABwADCZuqBbIMORYSVShYXgAilgQ8IvLSTCS4kMj40gKIEuSFjjrAMIQqKiSzXBUAKzdWG4AKsc2JDORK6XRAA)
```sh
--no-bracket-spacing
--single-quote
--trailing-comma es5
```

**Input:**
```jsx
module.exports = {
  'foo': 1,
  'bar': 2,
  'foo-bar': 3,
};

```

**Output:**
```jsx
module.exports = {
  foo: 1,
  bar: 2,
  'foo-bar': 3,
};

```

**Expected behavior:**
It seems that prettier formats object key property quotes to follow an [`as-needed`](https://eslint.org/docs/rules/quote-props#consistent) approach. IMHO, this doesn't seem to follow the rationale of [consistency](https://github.com/prettier/prettier/blob/master/Rationale.md#consistency). The [`consistent-as-needed`](https://eslint.org/docs/rules/quote-props#consistent-as-needed) approach seems to adhere to the prettier rationale more. 

Similar to the [`quotes`](https://github.com/prettier/prettier#quotes`) option, would the project consider `quote-props` options to help adhere to the rationale.

**Comment by lydell** [comment]
Hi! This has already been discussed before. See #838 and the issues that link to it.
