### ISSUE TITLE
Prettier insert extra semi-colon on each pass / run with `prettier-ignore`

### ISSUE THREAD

**Issue by theseyi** [prettier/prettier#3102]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgHV0ATCAd0OAB0pDCBbXTAazjIAoAHV3JkkIBnGJnQBzAJRDghABYwmAGwDKubHCFcphALwA+EWMmEAvgG569RgClh0ABIBXFlFk3GhbBEwsYXJ5ehGS4MLhCuFAAngA0QV4QPDCo0MIA-B4MwV7C8lQAgpiYuNEAklBkcAAeQgBuEKhkhAA+hABGEBDKcFFW2TkK0TxYyuhswrKECLjtPUKd3b1QFoQc0ZOEUM7Kyq2ERSXRADyi4lASBqvhmBJwMEJnppYJwQD0b4Q8mPcpWAC0qAkUF8cFeXkWyiyg2C8GqDxohAA5GJnHAkY8TBdVki8MphOjMecJOZ+jCvKgWHcpijMGiMcZiTi8QSGU8LqTwcE8lQylStB0uj0+lzcvlKAAVGoIyHLMkwl4DLxmBIyQgAUR6TAQMHlirMIFiICSKTSyFAuFEyBZcCN7RKYA4MFUfDAkmQqNtIAoYGtuHxXoAVsJqgAhB1O9TagAy6DgfoDRogzhgPBTACYEwSjXxMATMMgQDBhnBhGBxMlDSBvugYKQyDB5MgABwABiNBKYqA9dK9wkkPQAis4IPAs17wu1643kOmjWJcKgxhcAMIQJgsQsgqDxo3OAkS2bCcdmMxAA)
```sh
--parser typescript
```

**Input:**
```tsx
interface Window {
  marked(param: string): { htmlSafe: () => string };

  JsonHuman: {
    format(
      data: any,
      options?: {
        showArrayIndex: void | boolean;
        hyperlinks: { enable: boolean; keys: null | Array<string>; target: string };
        // prettier-ignore
        bool: {
          text: { 'true': string; 'false': string };
          image: { 'true': string; 'false': string };
          showImage: boolean;
          showText: boolean;
        };
      }
    ): Element;
  };
}
```

**Output:**
```tsx
interface Window {
  marked(param: string): { htmlSafe: () => string };

  JsonHuman: {
    format(
      data: any,
      options?: {
        showArrayIndex: void | boolean;
        hyperlinks: {
          enable: boolean;
          keys: null | Array<string>;
          target: string;
        };
        // prettier-ignore
        bool: {
          text: { 'true': string; 'false': string };
          image: { 'true': string; 'false': string };
          showImage: boolean;
          showText: boolean;
        };;
      }
    ): Element;
  };
}

```

**Expected behavior:**
No extra semi-colon after bool type definition with //prettier-ignore

**Comment by duailibe** [comment]
Minimal repro:

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgEkMd8jgAdKQwgensIAdM4YZUsBaVAcygRMNOqwjMkhGAE9mcANw0AviAA0IcZ2gBnZKFzaYyGJgCucdQCNM+ANbsAys3zo+xsxZAATCGGR4AG21PACttAA8AIRswexgHXABbOAAZdDh-XCDPCFMYZjyAJkzs9WdMYMxkEBk5bTBMVGYjMsbYAHVULxgAC2QADgAGdWDE1HdzEdcAuABFUwh4EuD1GFxLTu6+pELVm1QA1wBhCETE3GrBKAz1U2CAFXXdJEDgpSUgA)
```sh
--parser typescript
```

**Input:**
```tsx
interface Interface {
  // prettier-ignore
  prop: type;
}
```

**Output:**
```tsx
interface Interface {
  // prettier-ignore
  prop: type;;
}

```
