### ISSUE TITLE
Sort imports

### ISSUE THREAD

**Issue by milesj** [prettier/prettier#3104]
This is a feature request, not a bug report. It might also go beyond what Prettier is used/intended for, but basically, it would also be nice if Prettier sorted the imports at the top of each file.

**Comment by ikatyang** [comment]
See https://github.com/prettier/prettier/issues/2277#issuecomment-311216366:

> JavaScript imports can have side effects so it's not safe to do that unfortunately. Also, we've taken the stance with prettier not to do those kind of transforms that change the ast.
>
> We recommend that those would be implemented as eslint rules with autofix.
