### ISSUE TITLE
Multiple comments on top of if statement get separated

### ISSUE THREAD

**Issue by timm-gs** [prettier/prettier#3105]
When adding explanatory comments after `Istanbul` comments, `prettier` moves them around into a basically unformatted state.

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoB6oC8qADANwA6U6V6A9AFSoCWOAhlAEYCuANiwHMoEAE5wWAM1QM6qOrIAmcHgIxss4sNxFjYvAJ6phuGCOYCBcMQtqTUAClPc4ASlTBb6PJWqoAviAANCAQAA4wzNBYyKDqMMgSbLwawZwibGAA1nAwAMqhGcxQAshOcMEKEGAJSSkgAFZYeABC6Vk5uWwAtnAAMkVwNcnlIdwwoWMATEN1BSIaIsggnGyc+rzQQSChZrAA6swKMAAWyAAcJMEaXcylIs5XRQK8cACK3BDwMyMwqwdHpyQk2CpjYzF4TwAwhAul02EthFBBsFuBoACqraJIRLDPx+IA)

**Input:**
```jsx
  const x = 0;
  
  /* istanbul ignore if */ // debug case currently not triggered
  if (true) {
    x;
  }
```

**Output:**
```jsx
const x = 0; // debug case currently not triggered

/* istanbul ignore if */ if (true) {
  x;
}

```

**Expected behavior:**

I would expect the following output to remain unchanged with regards to the comments:

```
  const x = 0;
  
  /* istanbul ignore if */ // debug case currently not triggered
  if (true) {
    x;
  }
```
 
I would expect the comments to stick to the `if`, where they must be for `Istanbul` to pick them up

**Comment by lydell** [comment]
You can move the line comment above the block comment as a workaround.

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoB6oC8qADANwA6U6V6A9HagCZwBGArgOYYCGWcGdgCchCGABsAnqigRcMIQEtOnOKKa1UdAFSpFOHlA7i9nWaL0AzVNrqbF1gBQL2cAJSpgm9HkrVUAL4gADQgEAAOMIrQWMigfDDIljzi-KGsQjxgANZwMADK4VmKUJzILnChTBBgSSlpIABWWHgAQpk5efk8ALZwADIlcHWplWHsMOETAEwjDUVC-ELIIKw8rJLi0CEg4UqwAOqKTDAAFsgAHCSh-D2K5UKuNyWc4nAAiuxyw0jJo6EwdZHE7nJDTAGZRTiF4AYQgPR6PBWsigw1C7H4ABV1rFfvU4AEAkA)

**Input:**
```jsx
  const x = 0;
  
  // debug case currently not triggered
  /* istanbul ignore if */
  if (true) {
    x;
  }
```

**Output:**
```jsx
const x = 0;

// debug case currently not triggered
/* istanbul ignore if */
if (true) {
  x;
}

```
