### ISSUE TITLE
Trailing curly brace after arrow function is inlined

### ISSUE THREAD

**Issue by sharmilajesupaul** [prettier/prettier#3109]
Just to give you some context on this, I've been working with @ljharb to bring Prettier to @airbnb.
We noticed a few cases where Prettier’s formatting could be adjusted to more closely align with our style guide.

cc. @vjeux

**Prettier 1.7.4**

If an arrow function with an implicit return exceeds the specified `printWidth` Prettier places the closing curly brace in inline with the arrow function body.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT5fVwzrWcGHLiNH4APACEIEANY4oAcwCSsahAAKAQyilhYg+RUBbAA48AzhbxQATAF5gdLTC357APn0H8bGH5gACxwLADojZTNLa2gGAHJyJQB9KC1jOCTExRS0jKyc9LiAGnwE6GzU9Mzygryayrhi-GdXJm9RPz8AX3affCMAYRIcMFlHFrdPfCCQ8IhFIZHZePyG6uS11dymso3c9Yr9rcKSiaYezj78AHovS5E2qAuOECKQCFNcaAtkUC0LGDIVBaEgWOBvABG1C0o14AGVTDCFIpkDBqOhwSA6BAwECQWC3gArCwAD0k0NhMDhuQAMgo4HjQZiIOgYKZWbZGQSQIjqGDqMgQBCtBCAJ6JV486gKGAUHB0ILIACMAAYVW8wcYcKj0ZjrEoSHAAIroCDwHUYt6uCFyhWBZC2K3QnDDJQDCDGYxaQUgkiS9BggAqIp+SGBTK6XSAA)
```sh
# Options (if any):
--single-quote
--print-width 100
--trailing-comma "all"
```

**Input:**
```jsx
function HelloWorld() {
  return (
    <BookingIntroPanel
      logImpression2={data =>
        this.logImpression('long_name_long_name_long_name', 'long_name_long_name_long_name', data)
      }
      logClick={data => this.logClick('long_name_long_name_long_name', 'long_name_long_name_long_name', data)}
    />
  )
}
```

**Output:**
```jsx
function HelloWorld() {
  return (
    <BookingIntroPanel
      logImpression2={data =>
        this.logImpression('long_name_long_name_long_name', 'long_name_long_name_long_name', data)}
      logClick={data =>
        this.logClick('long_name_long_name_long_name', 'long_name_long_name_long_name', data)}
    />
  );
}
```

**Desired behavior:**
I would want Prettier to follow a block pattern where the opening and closing curly braces are on the same level of indentation. This makes the code more readable by clearly identifying what the block encapsulates.

eg: 
```jsx
function HelloWorld() {
  return (
    <BookingIntroPanel
      logImpression2={data =>
        this.logImpression('long_name_long_name_long_name', 'long_name_long_name_long_name', data)
      }
      logClick={data =>
        this.logClick('long_name_long_name_long_name', 'long_name_long_name_long_name', data)
      }
    />
  );
}
```
--------

Diff between Prettier & desired output:
```diff
*** prettier.js	2017-10-25 16:34:15.000000000 -0700
--- desired.js	2017-10-25 16:34:28.000000000 -0700
***************
*** 2,10 ****
    return (
      <BookingIntroPanel
        logImpression2={data =>
!         this.logImpression('long_name_long_name_long_name', 'long_name_long_name_long_name', data)}
        logClick={data =>
!         this.logClick('long_name_long_name_long_name', 'long_name_long_name_long_name', data)}
      />
    );
  }
--- 2,12 ----
    return (
      <BookingIntroPanel
        logImpression2={data =>
!         this.logImpression('long_name_long_name_long_name', 'long_name_long_name_long_name', data)
!       }
        logClick={data =>
!         this.logClick('long_name_long_name_long_name', 'long_name_long_name_long_name', data)
!       }
      />
    );
  }
```

**Comment by vjeux** [comment]
This is a bug and not really the intended behavior. It shouldn't be too hard to fix if you are interested in giving it a try.

**Comment by sharmilajesupaul** [comment]
Sure thing, I can take a stab at fixing this one. 🙂

**Comment by suchipi** [comment]
@sharmilajesupaul I believe @duailibe already has a fix in https://github.com/prettier/prettier/pull/3110

**Comment by sharmilajesupaul** [comment]
oh perfect, thanks @duailibe and @suchipi!
