### ISSUE TITLE
parentheses should be preserved in ternary operator

### ISSUE THREAD

**Issue by JLarky** [prettier/prettier#3111]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#.....)
**Input:**
```jsx
const x = q ? (a || b) : c;
```

**Output:**
```jsx
const x = q ? a || b : c;

```

**Expected behavior:**

prettier should just preserve original input, even though that seem to be returning the same result it's harder to reason about

**Comment by lydell** [comment]
Here's an example:

```js
a || b && c
```

If you don't remember the precedence rules, there are two ways to interpret the above:

```js
(a || b) && c
// or:
a || (b && c)
```

So Prettier helps you by adding in some parentheses:

```js
a || (b && c)
```

Now let's apply the above to your example:

```js
const x = q ? a || b : c;
```

In what ways can we interpret that?

```js
const x = (q ? a) || (b : c);
// or:
const x = q ? (a || b) : c;
```

But `q ? a` and `b : c` are not even syntactically valid expressions! So there's no ambiguity here.

**Comment by JLarky** [comment]
> But q ? a and b : c are not even syntactically valid expressions! So there's no ambiguity here.

I'm not talking about syntactical validity, I'm talking about code meaning. I would adopt prettier to make my code more maintainable, not less.

It's easier to understand what is going on with simple example, but when code get's bigger it's harder to follow, I noticed that in my (almst) real code:
```jsx
type === "some_type" ? formatName(name) || name : type === "some_other_type" ? `${name}` : "UNKNONW"
```

**Comment by lydell** [comment]
Prettier already does a pretty good job there, doesn't it? How would you format it?

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAvP7AHRAGcIBbOAfXS2OwH5sAzCAJ3IEMYA5TygBRR+cAJTYAPhOzDK2JNlo58uIqQrUIMABZw2NTHHpMABgBJgsuAF8T8tQFUeAaR4B5HgHVihKCAA0IBAYMACW0CTIoJwkMMjMnAA2JHCBAEZsnGAA1nAwAMoYWaFQAObIMGwArqkgACYQYPFJKYEAViQAHgBCmTl5+SIAMiVwzcm1EFUwGNMATOOtIEVsKWzIIGmcaWiJ0AHLbCUwnqF1OsgAHAAMgSnkoRXVtSQlpYlwAIpVWmNICRNAjBtqdztpkHMgZlQok3gBhChcDZQaBjQJVFIAFW2kX+LRs1iAA)

**Input:**
```jsx
type === "some_type" ? formatName(name) || name : type === "some_other_type" ? `${name}` : "UNKNONW"

```

**Output:**
```jsx
type === "some_type"
  ? formatName(name) || name
  : type === "some_other_type" ? `${name}` : "UNKNONW";

```

**Comment by JLarky** [comment]
right, it will depend on amount of text and allowed width
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAvP7AHRAGcIBbOAfXS2OwH5sAzCAJ3IEMYA5TygBRR+cAJTYAPhOzDK2JNlo58uIqQrUIMABZw2NTHHpMABgBJgsuAF8T8tQFUeAaR4B5HgHVihKCAA0IBAYMACW0CTIoJwkMMjMnAA2JHCBAEZsnGAA1nAwAMoYWaFQAObIMGwArqkgACYQYPFJKYEAViQAHgBCmTl5+SIAMiVwzcm1EFUwGNMATOOtIEVsKWzIIGmcaWiJ0AHLbCUwnqF1OsgAjHMADIEp5KEV1bUkJaWJcACKVVpjSAkJoEYNtTudtMg5sDMqFEu8AMIULgbKDQMaBKopAAq20iAJaNmsQA)

**Comment by lydell** [comment]
So ... don't use 120 in print width?

(I'm trying to challenge you to come up with really good examples that motivates this change.)

**Comment by JLarky** [comment]
not using ternary operator will also fix the issue, not using `||`, not using prettier also fixes this. thanks for help

**Comment by antoinerousseau** [comment]
Chaining ternary operators is not very readable:
`console.log(status >= 500 ? "❗️" : status >= 400 ? "⚠️" : "✅", response)`
I'd prefer at least:
`console.log(status >= 500 ? "❗️" : (status >= 400 ? "⚠️" : "✅"), response)`

**Comment by j-f1** [comment]
@antoinerousseau Can you open a new issue and fill out the template os we can discuss this separately?
