### ISSUE TITLE
(Re)formatting of conditional statement causes linter warning

### ISSUE THREAD

**Issue by rousselle** [prettier/prettier#3114]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdH2SgZxqgVwCcAbVAXlTGKIRgAUBDAczlQH5UB9AOlZgAU1IrVhNWAGlQByAA4s4OHlDgAPGNICUqJAB0omQxgAGACxgxZOJAHobjWQEsej2HCKQAti4g2AJMAwpo5KjvCeACoAnrJwAL7GANwgEiAQsjCO0DjIoIx4yABmjCQ4cKkARkSMYADWcDAAyvJgrszIMEQE5SAAJhBgRSVlqQBWOKoAQtV1DY2MnnAAMq5wQ6U9EASW2wBM6yMg8kRlRMggFYwVUSTQKUdErjAA6o69QcgAHAAMqWWejg6XR6ODaJDgAEUCBB4AcejArq93qZkLtUp1GI4SG0AMIQTyeRjnKDQNapAhlCJXHJIYobOJxIA)

**Input:**
```jsx
        const url = currentPage ? _.get(currentPage, 'pages.next') :
            `https://api.intercom.io/${this.itemType}`;
```

**Output:**
```jsx
const url = currentPage
  ? _.get(currentPage, "pages.next")
  : `https://api.intercom.io/${this.itemType}`;

```

**Expected behavior:**
Statement should not be changed

Prettier's (re)formatting of this line gets this warning from my linter, JSHint: "W014 misleading line break before '?'; readers may interpret this as an expression boundary."

**Comment by suchipi** [comment]
This is the intended behavior; this is how prettier formats ternaries. If you don't want JSHint to warn about this case, I think you can add `laxbreak: false` to your JSHint configuration.
