### ISSUE TITLE
camelcasing being overridden?

### ISSUE THREAD

**Issue by lucastobrazil** [prettier/prettier#3118]
Hey guys i have something weird going on since upgrading. Using **React Native** and `styled-components`, Prettier is doing the following:
### Before Prettier:
```
const Card = styled.View`
    shadowColor: black;
    shadowOffset: 2px;
    shadowOpacity: 0.04;
    shadowRadius: 4px;
`;
```

### After Prettier:
```
const Card = styled.View`
    shadowcolor: black;
    shadowoffset: 2px;
    shadowopacity: 0.04;
    shadowradius: 4px;
`;
```

Are there some sort of camelCase settings that have changed?

**Comment by hawkrives** [comment]
See https://github.com/prettier/prettier/issues/2897, in particular https://github.com/prettier/prettier/issues/2897#issuecomment-332321448:

> So as far as camel cases SC goes, try not to use it! It’s from our side unsupported but does work due to how we transform styles. Since it’s unsupported t might break in the future :)

> This is not because we want people to use it that way though, necessarily. I'm open to discussing about deprecating this by checking for camelCased properties and not passing them through, but that feels slightly weird because why do camelCased properties have a special case/behavior? 😕

**Comment by lucastobrazil** [comment]
Ah yes, thanks! FWIW i changed the properties to `shadow-color` etc and all works.

**Comment by adamkleingit** [comment]
I don't understand why prettier changes template literals? Does it somehow recognize that it is CSS?

**Comment by suchipi** [comment]
Yes, we have special handling for styled components, and so it knows it's CSS.

**Comment by adamkleingit** [comment]
That's interesting. If there's special handling for styled components - I think this should be fixed by prettier and turn camelCase selectors in kebab-case (or leave them as they are).

If it remains like this it makes it difficult to use prettier (we need the assurance that after running prettier the code will continue to work as before).

What do you think?

**Comment by lydell** [comment]
I think a codemod to fix the camelCase to kebab-case thing would be better.

**Comment by duailibe** [comment]
@adamkleingit be aware that according to the issue linked above, the fact that camelCase selectors work now is an accident, so it's not like prettier is breaking your code.
