### ISSUE TITLE
Wrong comments position

### ISSUE THREAD

**Issue by Alphapage** [prettier/prettier#3119]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEYD0OCG2EAtsQjADpQC8mAjANwgA0IEADjAJbrKj4ZkAM3wAbNHFYAjAE74wAazgwAyu3lcoAc2QwZAV0kgAJhDDCxE1gCs0ADwBCcxcpX4yAGU1wL4oxH0YdkCAJl8rEHUZCRlkECl8KQBPUWgWSJlNGAB1LmMYAAtkAA4ABlYJYi5dAyM0TS1ROABFfQh4cKMYRNz8oqQQ1j18LlEGgGESYnw4qGgfVn0JABVEtE6AXw2gA)

**Input:**
```jsx
const c//a comment
= 1;
```

**Output:**
```jsx
const c = 1; //a comment

```

**Expected behavior:**
Same as input

It is a big problem that prettier is unable to format comments correctly. The tool is unusable because of remaining issues like: 
https://github.com/prettier/prettier/issues/3105
https://github.com/prettier/prettier/issues/2874
https://github.com/prettier/prettier/issues/2853
https://github.com/prettier/prettier/issues/2457
and many others about #comments.

I tried to solve some of them, but it is really a headache to debug and understand how comments are generated.

Thank you in advance for your help.

**Comment by lydell** [comment]
Why isn't the output acceptable in this case? I think it could be considered a feature that Prettier has moved the comment to a more sane location in this case.

**Comment by Alphapage** [comment]
I think all code prettifiers respect the comments locations because we want Prettier to trust the author of the code.
I use Prettier to format my code only, but I am responsible of comments positioning.
So, it should respect that or provide an option if you want Prettier to format comments using it own engine.
This is just my opinion and for now, I can't use prettier because of this problem.

**Comment by lydell** [comment]
Thanks!

I don't think this issue is actionable, so I'm closing.
