### ISSUE TITLE
Extra spaces in the template string `${}`

### ISSUE THREAD

**Issue by edouard-lopez** [prettier/prettier#3121]
```
$ prettier-eslint --version
4.4.0
```

[Playground link](https://prettier.io/playground/#.....)
```sh
--semi
--single-quote
--bracket-spacing
```

**Input:**
```js
return this.get('i18n').t('server.errors.' + this.get('model.code'))
```

**Output:**
```js
return this.get('i18n').t(`server.errors.${  this.get('model.code')}`);
```

There is 2 extra spaces in the template string `${}`

**Expected behavior:**

Should have none.

**Comment by SimenB** [comment]
That's not prettier, it doesn't convert string concatenation to template strings (which you can see on the playground)

**Comment by duailibe** [comment]
Hey there! This looks like it's a problem with the [prefer-template](https://eslint.org/docs/rules/prefer-template) that ESLint auto fixes. Prettier won't change the concatenation.

**Comment by edouard-lopez** [comment]
My bad, thanks for the info
