### ISSUE TITLE
Prevent expanding function parameters into multiline

### ISSUE THREAD

**Issue by 19majkel94** [prettier/prettier#3122]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDMBLKAEwCEBPAEQEN4k8AlOIiAGwDc42ADx8I5KgBoOcMOQxwA2gF0pwPFRZw2zeHgC+APjwBePAB0oePAAoA+qvWb9D7HACO+vAEoTR4BasrQhI8VywTUPcAOgBzOBhOLCJyGBw6a05ZeS8AbgDA1xgAV2xLMIgoimprNTBXTR0tR109XPy9EAkQCAwYcmgiZFAmEmRSJh4iOC6AI2wmMABreIBlDAXKGOQYbCLpkCoIMDGJqa6AKyI0Gnml1aYAWzgAGUo4E8n9iCKYDB+AJg+ZxA62wU2wyBAMDo8iIdTkME6IOwlBgAHVxDAABbIAAcAAYulMHuRtrt9skoDEeHAAIpFCDwIH7GBMGYYqjY5D-Lo7JjkHibADCEAeDyYkKg0HeXSKUwAKmzBkhxp89HogA)
```sh
--parser typescript
```

**Input:**
```tsx
export const findByDate: Resolver<void, Recipe[], { date: Date }> = 
  (_, { date }, { req } ) => {
    const repo = req.getRepository(Recipe);
    return repo.find({ createDate: date });
  }
```

**Output:**
```tsx
export const findByDate: Resolver<void, Recipe[], { date: Date }> = (
  _,
  { date },
  { req }
) => {
  const repo = req.getRepository(Recipe);
  return repo.find({ createDate: date });
};

```

**Expected behavior:**
Don't expand parameters into multi lines as long as it can fit in print width in second line.
With short param names it easy to have very long function hard to read instead of simple twoliner:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDMBLKAEwCEBPAEQEN4k8AlOIiAGwDc42ADx8I5KgBoOcMOQxwA2gF0pwPFRZw2zeHgC+APjwBePAB0oePAAoA+qvWb9D7HACO+vAEoTRzrPkAOgpqazUwV00dLUddPS8AbhAJEAgMGHJoImRQJhJkUiYeIjgUgCNsJjAAazgYAGUMKsoAc2QYbABXUpAqCDACopKUgCsiNBpKmrr6pgBbOAAZSjhB4p6ITpgMLYAmNeGQJuwS7GQQMqYyuh5oZKPsShgAdXEYAAtkAA4ABhSSubkdpdHpEVo8OAARU6EHgBx6MCuryoH2QuxSHSY5B4rQAwhA5nMmOcoNBVilOiUACpXbJIQrrPR6IA)

**Input:**
```tsx
export const findByDate: Resolver<void, Recipe[], { date: Date }> = 
  (_, { date }, { req } ) => Recipe.find({ createDate: date });
```

**Output:**
```tsx
export const findByDate: Resolver<void, Recipe[], { date: Date }> = (
  _,
  { date },
  { req }
) => Recipe.find({ createDate: date });
```

**Comment by lydell** [comment]
I believe this is something that #3014 could potentially solve.

**Comment by bakkot** [comment]
I think this an instance of #2482, which is the general issue for "prettier refuses to put linebreaks after `=`"

**Comment by lydell** [comment]
@bakkot Thanks, I think so too. Merging into #2482.
