### ISSUE TITLE
Blank lines aren't preserved when using nested template literals

### ISSUE THREAD

**Issue by dstaley** [prettier/prettier#3123]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEGCeAbOTAXmxnzgBMAKAcgoEsA3GgSgAMAdKDmAM2hgBaNPQBecJJgCMAJgAOADwDcXVTAAkwALaV6AQwCKAVzgAnenDQA6CpYDWMCHM7cYPfrGFiJ0gCyKVVzYAX1VXTR0GQxNzSys8PVMAczgAEXtHZzV3AS9xSSkADgC1EK42QK5IKAxScmI6gmo6JlYXHM8RfOl5ZTCeCN1oswtrWzQHJ3a3Plyunyl-PqDQ7lcAIz0wOyTTCCMoCkFIPAhTSVNKQIqQABoQJxh6dGRQPQxkXj08NDh79dMWzscBgAGU5Ft6FAksgYKYTPcKBAwJ9vr97gArNAKABCgO2INBeh0ABkoXBUT8-g8jDA5LSZJT0SAIaZfqZkCBNut8NA7izzLAAOr0CgwAAWyEKAAZ7r8tPRYfDqSJoQRjBB4EzqTA9OsRWLJUgZPc4Xp6HgoUkAMIQLRaPScqDQCn3Iy-AAqerQ2uCwSAA)

**Input:**
```jsx
const style = styled('div')`
	font-size: 12px;

	${mediaQueries.desktop`
		font-size: 14px;
	`}

	${mediaQueries.largeDesktop`
		font-size: 18px;
	`}
`;

const style = styled('div')`
	font-size: 12px;

	${mediaQueries.desktop`
		font-size: 14px;
	`}

	background-color: red;
`;
```

**Output:**
```jsx
const style = styled("div")`
  font-size: 12px;

  ${mediaQueries.desktop`
		font-size: 14px;
	`} ${mediaQueries.largeDesktop`
		font-size: 18px;
	`};
`;

const style = styled("div")`
  font-size: 12px;

  ${mediaQueries.desktop`
		font-size: 14px;
	`} background-color: red;
`;

```

**Expected behavior:**

Prettier should preserve the blank lines following the nested template literal. The output in this case should be the exact same as the input.

**Comment by mariusschulz** [comment]
Here's a minimal repro:

**Input:**

```js
function css(strings) {
    return strings[0];
}

const foo = css`
`;
```

**Output:**

```js
function css(strings) {
    return strings[0];
}

const foo = css``;
```

The resulting value in `foo` is `""`, but should be `"\n"`.

**Comment by duailibe** [comment]
Related: #1872, #2300

**Comment by fisker** [comment]
I think this is fixed, please close

**Comment by lydell** [comment]
Yeah, the blank lines seem to be preserved these days:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEGCeAbOTAXmxnzgBMAKAcgoEsA3GgSgAMAdKDmAM2hgBaNPQBecJJgCMAJgAOADwDcXVTAAkwALaV6AQwCKAVzgAnenDQA6CpYDWMCHM7cYPfrGFiJ0gCyKVVzYAX1VXTR0GQxNzSys8PVMAczgAEXtHZzV3AS9xSSkADgC1EK42QK5IKAxScmI6gmo6JlYXHM8RfOl5ZTCeCN1oswtrWzQHJ3a3Plyunyl-PqDQ7lcAIz0wOyTTCCMoCkFIPAhTSVNKQIqQABoQJxh6dGRQPQxkXj08NDh79dMWzscBgAGU5Ft6FAksgYKYTPcKBAwJ9vr97gArNAKABCgO2INBeh0ABkoXBUT8-g8jDA5LSZJT0SAIaZfqZkCBNut8NA7izzLAAOr0CgwAAWyEKAAZ7r8tPRYfDqSJoQRjBB4EzqTA9OsRWLJUgZPc4Xp6HgoUkAMIQLRaPScqDQCn3Iy-AAqerQ2uCwSAA)
```sh
--parser babylon
```

**Input:**
```jsx
const style = styled('div')`
	font-size: 12px;

	${mediaQueries.desktop`
		font-size: 14px;
	`}

	${mediaQueries.largeDesktop`
		font-size: 18px;
	`}
`;

const style = styled('div')`
	font-size: 12px;

	${mediaQueries.desktop`
		font-size: 14px;
	`}

	background-color: red;
`;
```

**Output:**
```jsx
const style = styled("div")`
  font-size: 12px;

  ${mediaQueries.desktop`
		font-size: 14px;
	`}

  ${mediaQueries.largeDesktop`
		font-size: 18px;
	`}
`;

const style = styled("div")`
  font-size: 12px;

  ${mediaQueries.desktop`
		font-size: 14px;
	`}

  background-color: red;
`;

```
