### ISSUE TITLE
Avoid unnecessary template literals with no interpolation and new lines

### ISSUE THREAD

**Issue by mohsen1** [prettier/prettier#3125]
**Prettier 1.7.2**

**Input:**
```jsx
`foo`
```

**Output:**
```jsx
`foo`
```

**Expected behavior:**

Since

```
`foo` === "foo"
```
it makes sense to convert the template literals to a regular strings when they don't have interpolations and line breaks. This is result of prettier being to damn good and making me assuming it will fix all my lazily written code. I start with <code>const url = `/api/${id}`</code> but then later I remove the interpolation. My code now has an unnecessary template literals which should be just a regular string.

Unless I'm not understanding template literals and this conversion is not correct...

**Comment by duailibe** [comment]
Hi there, thanks for the suggestion!

That's actually one of the things prettier is not concerned about (see https://github.com/prettier/prettier/blob/master/Rationale.md#what-prettier-is-not-concerned-about). Also, one of the core principals of prettier is to not change the AST (which would be the case).

**Comment by mohsen1** [comment]
yup, will defiantly change the AST.
