### ISSUE TITLE
What about creating a Twitter account for Prettier (news, announcements, etc)

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3127]
https://twitter.com/prettier (for some reason it's suspended, but I'm sure you know people that know people)

Plus it will be easier to praise Prettier on Twitter :)

**Comment by vjeux** [comment]
If someone is interested in creating it and maintaining it, please go ahead and do it :)

I would do @prettier_ for now and there's a form to request a name change somewhere, I'm sure we can get @prettier after the account has been active for a while.

**Comment by lipis** [comment]
Awesome.. I created https://twitter.com/PrettierCode (for now) as the other ones were taken.. will set it up later :)

**Comment by lipis** [comment]
Is it OK to add another badge in the README.md file to follow Prettier on Twitter?

[![Twitter Follow](https://img.shields.io/twitter/follow/prettiercode.svg?style=social&label=Follow)]()

**Comment by lipis** [comment]
I think we can close that one.. 1200+ followers is a good start :)
