### ISSUE TITLE
Async array function error

### ISSUE THREAD

**Issue by jagi** [prettier/prettier#3131]
**Prettier 1.7.4**

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwARgBZxgDW2AvNugM4CeUY2AFFgOYCUZAfNsADpTbYA9IOwARCNkoQAtnAo06uAsQB0fAL4BuEABoQEAA4wAltErJQVGMgBm6ADaU4egEaZ0xODADKBj8ahmZBhMAFdnEAATCDBbByc9ACtKAA8AIXdPH3RZABkAuDjHCIhQmAMygCYihJA-TCdMZBAXdBdqe2hdOswAmAB1Y0iYPGQADgAGPSdpY2CwiMoA5ns4AEVQiHgaiJg2weHRpEq9EPRje2WAYRlpdGaoaEK9UKcAFTbzJDti9XUgA)

**Input:**
```js
var check = async (arg) => {
  // Do some async check.
};
```

**Output:**
```jsx
var check = async arg => {
  // Do some async check.
};
```

**Expected behavior:**
```js
var check = async (arg) => {
  // Do some async check.
};
```

Prettier removes brackets around argument which is wrong when using `async`

**Comment by ikatyang** [comment]
What do you mean "error"? The syntax is valid.

**Comment by jagi** [comment]
Sorry I've accidentally clicked Add before writing comment. I'm just describing it.

**Comment by jagi** [comment]
Ups sorry I've tried to replicate this bug in pure Babel but it works. Apparently, it's a problem with a framework I'm using that it does not transpiles code properly.
