### ISSUE TITLE
Non-optimal line break before array accessor

### ISSUE THREAD

**Issue by tmquinn** [prettier/prettier#3134]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzuuAnGA6CAawAoAzASygBNiByA7AcwFoAbMVgB2bivJmaROAT2YBXbK2YAjVFCg4A+otaVCtAJQBtAAwBdPIzgwAgjBjZy0sfDoALbHFKa8lKnAAeAeVLEYd8nQ8Vjk+KEYABVQjABk1DQACAD4E5gBGABoE2hjQykYEzmi4BNUoQgTHahx0BMhsRzAYVmFNAG4QDJAIThhyaHRkUAwYZFJUViwu6WxUMEJjAGUisHzkCzE4LqoIMDGJqZAAK3QPACFZ+aXUAFs4OIV9ya3um04bACYnw6LsLGxkCBZNJhKxoJ0QJxLLAAOrkKj+ZAADh0XSwN3I62wmzR+VYcAAimIIPAsTiQDBUNI4Qi7MgPl0LKhyGVGABhCA3G6oQFwdAAVghYiwABUqYMkONngBfaVAA)
```sh
--single-quote
--trailing-comma es5
```

**Input:**
```jsx
assert.ok(find('.org-lclp-edit-copy-url-banner__link')[0].getAttribute('href').indexOf(this.landingPageLink) > -1, 'Landing page link renders correctly');
```

**Output:**
```jsx
assert.ok(
  find('.org-lclp-edit-copy-url-banner__link')
    [0].getAttribute('href')
    .indexOf(this.landingPageLink) > -1,
  'Landing page link renders correctly'
);

```

**Expected behavior:**
`[0]` should remain on the same line as `find(...)`

**Comment by vjeux** [comment]
@lydell: I don't think that discussion is needed here, it should be next to find().
