### ISSUE TITLE
Is there an option to organize my import statements?

### ISSUE THREAD

**Issue by Anenth** [prettier/prettier#3141]
I like to organize my import statement in a particular order, i.e
```
<npm modules>
<UI modules>
<Service modules>
<business modules>
```

eg.
**Input:**
```js

import Button from '../../ui/Button';
import React from 'react'
import InputForm from './inputForm';
import {post} from '../../services/http';
```

**Output:**
```jsx
import React from 'react'
import Button from '../../ui/Button';
import {post} from '../../services/http';
import InputForm from './inputForm';
```

1. Is it possible to do it right now?
2. Is it possible to support it?
3. if 2 then How?

**Comment by ikatyang** [comment]
See https://github.com/prettier/prettier/issues/2277#issuecomment-311216366:

> JavaScript imports can have side effects so it's not safe to do that unfortunately. Also, we've taken the stance with prettier not to do those kind of transforms that change the ast.
>
> We recommend that those would be implemented as eslint rules with autofix.
