### ISSUE TITLE
Extend config

### ISSUE THREAD

**Issue by felixfbecker** [prettier/prettier#3146]
Inside an org with a lot of repos we would like to maintain a consistent code style by sharing formatting/linting configuration files. TSLint, ESLint, TypeScript tsconfig etc. all allow this by specifying an `extends` property that points to another config, resolved by node module resolution algorithm. Meaning it's possible to do this:
```json
{
  "extends": "@sourcegraph/tslint-config"
}
```
The rules get shared, but individual rules can still be overridden where it makes sense for only that project. Just passing the path to the config file also prevents editors from detecting that they should use prettier.

**Comment by ikatyang** [comment]
I'm currently doing it this way in all of my repos to maintain consistent style:

```js
// prettier.config.js
module.exports = require("prettier-config-ikatyang");
```

The proposed feature (ref: [ESLint config](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns)) looks good to me and it seems not hard to implement (use `opts.config`): https://github.com/prettier/prettier/blob/d4768e1336108f2ed672f4d288b1751b9c40c526/src/resolve-config.js#L32

**Comment by azz** [comment]
This is already possible though with Object.assign. 

Would/should overrides be inherited?

Prettier doesn't have many options, so having built-in inheritance seems excessive to me.

**Comment by suchipi** [comment]
I agree with @azz on this one; Users should use `Object.assign` (or a deep merge function if that's the behavior they want, instead of shallow) in `prettier.config.js`.

**Comment by lydell** [comment]
In Node.js 8 you can even use object spread `{...base, override: 12}`.

**Comment by azz** [comment]
Since this is super easy to workaround and the inheritance strategy might vary between use cases, let's close this one for now.

**Comment by donaldpipowitch** [comment]
Is there a similar "workaround" (I actually like the way with a plain `.js` file) to extend a shared `.prettierignore`?

**Comment by azz** [comment]
There isn't. There was a PR to support multiple ignore paths via the CLI in #2720 that could be revived.

**Comment by donaldpipowitch** [comment]
Okay, thank you. Not sure, if this is what I want 🤔  I want to share a `.prettierignore` across projects, not extend the config.

Different question... The whole `.prettierignore` functionality is only accessible via CLI, if I'm not mistaken? I can import `resolveConfig` function, but it doesn't cover the ignore functionality and there is no `resolveIgnoreConfig` or something like that. If I see correctly the CLI uses [`createIgnorer`](https://github.com/prettier/prettier/blob/7b299fb94ecfcec0e57d3f4c82c4ab9ef9e9fd7a/src/cli-util.js#L256) function to read the `.prettierignore` and uses it for filtering [here](https://github.com/prettier/prettier/blob/7b299fb94ecfcec0e57d3f4c82c4ab9ef9e9fd7a/src/cli-util.js#L292). Hmm... looking at it... I guess I need to use the [`ignore`](https://www.npmjs.com/package/ignore) module myself and try to append a `.prettierignore`, if available 🤔

**Comment by azz** [comment]
Yeah that's the current way of doing it if you're working with the API. Room for improvement.

**Comment by donaldpipowitch** [comment]
Thank you for clarifying this 👍

**Comment by davidbarral** [comment]
IMHO the @felixfbecker's proposal is quite useful. Other tools like babel, jest, and eslint allows this kind of configuration. We use this approach to share common configuration between projects. The proposed workarounds are only applicable to the `prettier.config.js` file. I thinkg there's no current way to do the same using the `package.json` (or other JSON/YAML config files).

+1 to reopen this issue :)

**Comment by donaldpipowitch** [comment]
Yes. We did it as well and I can only recommend it.

And other projects like Babel support .js as well. This is very nice, because the extend behavior is basically the same across different libs.

**Comment by davidbarral** [comment]
@lydell due to our specific needs we prefer  each and every project to have all its configuration stored in a single file (the package.json). Our projects have several packages (over a dozen) and each one shares the same basic config (beware: not real package names xD):

```
"devDependencies": {
    "shared-tools": "x.y.z"
  },
  "babel": {
    "extends": "shared-tools"
  },
  "jest": {
    "preset": "shared-tools"
  },
  "eslintConfig": {
    "extends": "shared-tools"
  }
```

Now we want to add some shared "prettier" overrides and it would be great to be able to do it the same way we do with other tools without having different config files.

Using the programatic approach would be my choice if I need to customize the config based on environment settings or stuff like that, but it's not the case.

**Comment by lydell** [comment]
I see, thanks for explaining!

**Comment by pablorsk** [comment]
Sample code:
```
// .prettierrc.js
module.exports = {
    ...require("./your-global-ci-folder/.prettierrc.js"),
    printWidth: 140,
    tabWidth: 4,
    parser: "flow"
};
```

**Comment by TuckerWhitehouse** [comment]
Would it be possible to have this issue re-opened or should a new ticket be created?

I work on a team that has a similar use case to @davidbarral's and would like to avoid adding a `prettier.config.js` file to the root of our project just to require our external config...

**Comment by pablorsk** [comment]
@TuckerWhitehouse, if you like avoid root file, you can use somethink like this on `package.json`

```json
{
    ....,
    "scripts": {
        "prettier": "prettier --config ./my/real/.prettierrc",
        "prettier:fix": "prettier --config ./my/real/.prettierrc --write"
    },
}
```

Then, just do `yarn prettier`. I don't recommend this solution because your IDE can't find the correct configuration (if you use any extension).

Also, If you don't put any file on root or package, how can prettier (or IDE) found your config? What is your idea? I can only think of one item in `package.json` :thinking:

**Comment by TuckerWhitehouse** [comment]
Hey @pablorsk - ideally a field in the `package.json` config, similar to `babel`, `eslint`, `jest`, etc as @davidbarral described.

**Comment by psyrendust** [comment]
I'm working on a project that is a mono repo and our configs are stored in parent folder like so:
```
../
├── frontend
│   ├── eslintrc.js
│   ├── prettier.config.js
│   └── tslint.json
├── project1
│   ├── README.md
│   ├── node_modules
│   ├── package.json
│   ├── src
│   ├── test
│   ├── tsconfig.json
│   └── webpack.config.js
└── project2
    ├── README.md
    ├── node_modules
    ├── package.json
    ├── src
    ├── test
    ├── tsconfig.json
    └── webpack.config.js
```
Everything works fine for running our scripts from `package.json`:
```json
```

**Comment by suchipi** [comment]
@psyrendust as a workaround, you can use a symlink.

**Comment by psyrendust** [comment]
@suchipi That would also require me creating a new file in my project folders and potentially needing to exclude them in `.gitignore`, which is not something that I want to do.

**Comment by suchipi** [comment]
🤷

**Comment by Undistraction** [comment]
An API suporting `extends` and making prettier consisant with eslint, stylelint and babel would be most welcome.

**Comment by jayrylan** [comment]
@ikatyang @suchipi - if I were to submit a PR to add config extends functionality with full code coverage and accpetable code quality, would it likely be merged?

I just want to check beforehand, if the team members are against the idea I won’t bother to submit.

**Comment by j-f1** [comment]
Almost certainly!

**Comment by jayrylan** [comment]
@j-f1 Awesome! I’ll get on it and submit a PR probably late next week.

**Comment by suchipi** [comment]
Actually, I disagree- I don't think this needs to be in prettier. See https://github.com/prettier/prettier/issues/3146#issuecomment-342030530

**Comment by davidbarral** [comment]
@suchipi what @jayrylan proposes is a way to extend config using json in the package.json, which has nothing to do with the JS config. It cannot be solved using Object.assigns as you stated in #3146. 
I believe that we all agree about the advantages of using JS config over JSON. IMHO the point here is that prettier already supports configuration using a "prettier" key in the package.json (as most other tools do) and seems reasonable to support the "extends" keyword (as most other tools also do). If @jayrylan can provide a patch with good code quality I don't think there is any reason not to merge it.

**Comment by duailibe** [comment]
> I don't think there is any reason not to merge it

Of course there are reasons.. the first and most important is that once this code is included and this feature is released, we'll have to maintain it forever. We're a small team of volunteers and there's only so much we can do on our spare time.

**Comment by j-f1** [comment]
Would it be possible to do this inside of cosmiconfig instead?

**Comment by j-f1** [comment]
Ah: https://github.com/davidtheclark/cosmiconfig/issues/40

**Comment by jayrylan** [comment]
I’m working on a package that’s an alternative to cosmiconfig with more functionality (but still very lightweight+extendable). If I submit a PR, it would be to change Prettier’s existing config loader with the package I’m writing, so ongoing maintainence would fall on the work I’m doing…which should be updated for the foreesable future, as my company is in the process of publishing over 40 npm packages and our config utility package is used in several of them.

**Comment by tunnckoCore** [comment]
I also did a few works on this field.

https://github.com/tunnckoCore/resolve-plugins-sync

[@tunnckocore/pretty-config](https://npmjs.com/package/@tunnckocore/pretty-config) - I believe the published on npm source is currently living at https://github.com/tunnckoCore/hela/tree/v3-major/packages/pretty-config 

Currently supports

```js
const configFiles = [
  '.%src.json', // 1
  '.%src.json6', // 2
  '.%src.yaml', // 3
  '.%src.yml', // 4
  '.%src.js', // 5
  '.%src.mjs', // 6
  '%s.config.js', // 7
  '%s.config.mjs', // 8
  '.%s.config.js', // 9
  '.%s.config.mjs', // 10
  '.%src', // 11 - first try JSON, if fail to parse then fallback to YAML
  'package.json', // 12 - pkg.eslint || pkg.eslintConfig || pkg.config.eslint
];
```

It's very much stable and we are using it for like half year, just don't have the time to organize so many repos and things that I'm doing.

More than a year ago started locally the work on `resolve-plugins` (async) but never managed to publish it. Everything is in tons of linked issues around the repos.

**Comment by yacinehmito** [comment]
> This project is all about predictability and consistency, so an API supporting extends and making prettier consistent with eslint, stylelint and babel would be most welcome.

Looks like ESLint considers moving away from this because resolving a config through `extends` incurs significant complexity (See https://github.com/eslint/rfcs/pull/9)

**Comment by jayrylan** [comment]
@j-f1 I finally got around to publishing the package we're using with my company, it's a drop-in replacement for `cosmiconfig`, in fact it still uses `cosmiconfig` under the hood:

https://www.npmjs.com/package/configomatic

We're using this internally across 40 or so packages, and publicly I'm using it in `packlint` an npm package linter that is published, but I need to write up documentation for:

https://www.npmjs.com/package/packlint

Let me know if you'd like me to send a pull request to switch out `cosmiconfig` for `configomatic`.

**Comment by j-f1** [comment]
cc @prettier/core

**Comment by azz** [comment]
Happy to consider using it if we get a "no" [here](https://github.com/davidtheclark/cosmiconfig/issues/1#issuecomment-471232652).

**Comment by azz** [comment]
I had an alternate idea which could be considered: Instead of using an `extends` clause, we let the settings be a string referring to a node module instead. You'd just do this in `package.json`:

```json
{
  "prettier": "@scope/prettier-config"
}
```

This removes all complexity around merging configurations, which shouldn't really be necessary. If you want to overwrite some settings just use a `.prettierrc.js` file. 

👍 / 👎 ❓

**Comment by duailibe** [comment]
@azz I like it a lot

**Comment by tunnckoCore** [comment]
@azz agree! <3

**Comment by yacinehmito** [comment]
@azz Excellent! We were considering including a .prettierrc.js in all our projects with the following content:

```js
module.exports = require('@spendesk/prettierrc');
```

You solution makes things way simpler.

**Comment by jayrylan** [comment]
@azz, my concern with that sort of approach is that it's only aimed at package.json usage. 

In the context of prettier supporting multiple programming languages, there are plenty of developers that exclusively use prettier through IDE integration and do not even have a need for a `package.json`. file.

By using configomatic or something similar, developers could still use a plain json file: `.prettierrc.json` .

**Comment by lydell** [comment]
@jayrylan I think @azz meant that you could use a string as options _anywhere._ For example, .prettierrc.json:

```json
"@scope/prettier-config"
```

**Comment by duailibe** [comment]
@jayrylan Theoretically a `.prettierrc.json` with "@scope/prettier-config" would be the same as `"prettier": "@scope/prettier-config"` in `package.json`

**Comment by tunnckoCore** [comment]
@yacinehmito I'm doing the same, pointing to the eslint config package where I host all the style things.

But still, I don't like to have such files and bloat the root so much with some config files. In a monorepo setup, it might not feel that bad, but otherwise it is, and I was feeling bad about that most of my repos have dozen of things other than `src` dir and package.json.

**Comment by chrisblossom** [comment]
I've released two packages that you might want to consider.

[resolve-with-prefix](https://github.com/chrisblossom/resolve-with-prefix) - If you wanted to resolve presets similar to `babel` / `eslint`. Examples:

- `@scope/config` -> `@scope/prettier-preset-config`
- `recommended` - > `prettier-preset-recommended`
- `@prettier/recommended` -> `@prettier/preset-recommended`

[ex-config](https://github.com/chrisblossom/ex-config) - Extend configurations (`resolve-with-prefix` is build in). Meant to be used in combination with a config loader, such as [cosmiconfig](https://github.com/davidtheclark/cosmiconfig).

In my opinion, because prettier's config is so basic I think extending configurations is overkill, and @azz's idea about resolving a node module from a string is the best option.

**Comment by suchipi** [comment]
I don't think we should convert strings like that- it makes grepping harder for little value. It also encourages the creation of presets which feels a little silly for prettier.

**Comment by yacinehmito** [comment]
> It also encourages the creation of presets which feels a little silly for prettier.

But that's the whole point. In an organisation with multiple projects where you want to standardise on a prettier configuration, this is invaluable.

**Comment by tunnckoCore** [comment]
> it makes grepping harder for little value

What grepping? We don't need anything like that. When it's a string it will just be passed to require, plus if config is found locally (on the project root, or given cwd) merge.

> encourages the creation of presets which feels a little silly for prettier.

It already encouraged "a bit more configuration" than strictly been "opinionated", once it introduced semi and the few other options.

**Comment by lydell** [comment]
I think @suchipi responded to @chrisblossom's comment specifically, not to the idea of being able to re-use a configuration in general.

**Comment by suchipi** [comment]
Yes, @lydell is correct- that was in response to @chrisblossom. Sorry for the lack of clarity.

It makes sense to have organization-wide or monorepo-wide configs but creating a special naming convention would make some public npm names more valuable than others which feels odd because I don't think there is much value in public prettier configs on npm, since we have so few options.

If we encouraged public prettier configs and found that people started all using them for one reason or another (maybe it treats some special files like `.babelrc` differently), then we should probably adopt those as the defaults anyway.

So I don't want to create a situation where public configs have value because encouraging public configs isn't aligned with our design philosophy and I don't want to send mixed signals.

**Comment by azz** [comment]
PR for [my proposal](https://github.com/prettier/prettier/issues/3146#issuecomment-471518548) is up at #5963.
