### ISSUE TITLE
Upgrade Docusaurus

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3149]
We should upgrade docusaurus to the latest beta (10 at time of opening this issue).

I installed it locally and it seems to work fine. 

We should also [enable search](https://docusaurus.io/docs/en/search.html).

@joelmarcey any known breaking changes from `alpha.35` to `beta.10`?

**Comment by JoelMarcey** [comment]
Hi @azz - The biggest change between `alpha.35` and `beta.10` is our switch from using Marked/Prism to [Remarkable](https://github.com/jonschlinkert/remarkable) as our markdown parser. That could affect you, although I think possibly the only real breaking change may be in some of the keywords used in the `siteConfig.js`. 

If the upgrade is done, we will know when Prettier is run locally for testing and we can work through any issues then.

As we actually release docusaurus, we will be more diligent in documenting release logs with breaking changes when we bump version numbers.
