### ISSUE TITLE
Custom parser not compatible with writers

### ISSUE THREAD

**Issue by ThaNarie** [prettier/prettier#3150]
When following the [custom-parser-api](https://github.com/prettier/prettier#custom-parser-api) example from the docs with a non-js file format, it fails on selecting the correct writer:

```
prettier.format(
  '.foo { color: red; }',
  {
    // parser: 'scss'
    parser: (text, parsers) => {
      const ast = parsers.scss(text, parsers, { parser: 'scss' });
      return ast;
    }
  }
)
```

```
node_modules/prettier/index.js:8014
      throw new Error("unknown type: " + JSON.stringify(n.type));
      ^

Error: unknown type: "css-root"
    at genericPrintNoParens (node_modules/prettier/index.js:8014:13)
```

It checks `options.parser`, but since that's a function, it will fallback to the default writer:
https://github.com/prettier/prettier/blob/ec8deb6c0baaa3eb17a7236f9c1cd9e1a8063c44/src/printer.js#L53-L68

I believe the option to pass a function (#1783) was added before the custom languages, but I think this feature needs a fresh look. Some suggestions:
* Either go back to a separate option like #1710 (astTransform)
* Or add a `printer` option that can be set to a string (not needed when parser is a string or can be detected on filetype)
* Or allow the response of the parser function to return an object with the options that the writer can use.

**Comment by lydell** [comment]
As far as I remember, there are places where we do stuff like `if (options.parser === "json")` and `if (options.parser === "css")`, so I guess using a function as the `options.parser` is pretty broken.

There might be a quick fix we can do. A more ambitious solution could be doing something like this: #2846.

**Comment by azz** [comment]
Hacky but effective workaround: Put a `printer` property on the `parse` function?

```js
const parser = (text, parsers) => {
  const ast = parsers.scss(text, parsers, { parser: 'scss' });
  return ast;
}
parser.printer = "scss";

prettier.format('.foo { color: red; }', { parser });
```

Otherwise passing `filepath: "foo.scss"` should work.

**Comment by xixixao** [comment]
Ran into this as well. Cannot use a custom parser and print JSON - because as @lydell mentioned we do `"options.parser === "json"`. There's 18 cases of checking `options.parser` against a string in `src`. Let's add a helper in `util` and do what @azz suggested?

**Comment by azz** [comment]
Just thinking - we can probably supersede this API with the plugins API, as you can now do this:

```js
const parserPlugin = {
  parsers: {
    "custom-css-parser": {
      parse(text, { postcss }, opts) {
        const ast = postcss(text);
        mutate(ast);
        return ast;
      },
      astFormat: "postcss"
    }
  }
};

prettier.format("code", {
  plugins: [parserPlugin],
  parser: "custom-css-parser"
})

```

**Comment by duailibe** [comment]
@azz that doesn't solve it if the `postcss` printer does checks like `options.parser === "css"` (or `"less"`, or `"sass"`)

**Comment by azz** [comment]
Yes we need to change that to use `astFormat` instead

**Comment by azz** [comment]
I found another workaround that works with `typescript`.

```js
prettier.format('ts()', {
  parser(text, parsers, options) {
    options.parser = 'typescript'; // <--
    return parsers.typescript(text);
  }
});

**Comment by xixixao** [comment]
> I found another workaround that works with typescript

That's horrible :D

**Comment by azz** [comment]
Horribly _fantastic_ 🤣

**Comment by yxliang01** [comment]
I think custom parser itself shouldn't be just a "parser" but a plugin like object, since we generally also need to specify the printer. E.g. implement like what https://github.com/prettier/prettier/issues/3150#issuecomment-392622776 does. And, adding `printer` to the parser function looks weird. Maybe the official documentation can be changed to say that "if you want to do AST tranform, etc... , you should implement a plugin object."

**Comment by thorn0** [comment]
The custom parsers are a relic of the past and going to be deprecated. The Plugin API should be used instead. It can do everything custom parsers can and much more.
