### ISSUE TITLE
Remove unneeded template literals

### ISSUE THREAD

**Issue by ocboogie** [prettier/prettier#3151]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOEA2cB0mIDmAFAAYByEABFHHACaUxUCuaclAho3ALYAOmDvEqYAlvABOHTCQCUAbgA6USFDQxu-QfAAy4uFMyUAvJUUgAKrwFD2YydPNKV6LLnzESAdXY16jFjZOSgASYHgtWz0HTABfOXkQABoQCD4YUXRkUA51ZAAzaTYUgCMpMABrOBgAZT4OMFEoAmQYCWY4FLoIMAKizpAAKzQADwAhcqrajh44PRo+zGLU5hg+VYAmReX6iTYJZBASjhKAT3woZJA+CSaYL1E6GAALZAAOAAYUth5RVvaBmgmgRsABFZgQeDbAYwE4PJ6vJAbFJtDiiMTNADCEB4PA4hyg0DgV1YcAsJzQ0NisSAA)

**Input:**
```jsx
console.log(`No need to use a template literal`);
const templateLiteral = "Template literal";
console.log(`We need to use a ${templateLiteral}`);
```

**Output:**
```jsx
console.log(`No need to use a template literal`);
const templateLiteral = "Template literal";
console.log(`We need to use a ${templateLiteral}`);

```

**Expected behavior:**
```jsx
console.log("No need to use a template literal");
const templateLiteral = "Template literal";
console.log(`We need to use a ${templateLiteral}`);
```

**Comment by ikatyang** [comment]
See [Rationale.md](https://github.com/prettier/prettier/blob/master/Rationale.md#what-prettier-is-not-concerned-about):

> ## What prettier is _not_ concerned about
> 
> Here are a few examples of things that are out of scope for prettier:
> 
> - **Turning single/double quotes into template literals or vice versa.**
> - Adding/removing `{}` and `return` where they are optional.
> - Turning `?:` into `if then else`.

One of the core principals of Prettier is to not change the AST, StringLiteral (`''`/`""`) and TemplateLiteral (` `` `) are different.

**Comment by ikatyang** [comment]
For reference, duplicate of #2996 and #3125.
