### ISSUE TITLE
Inline comments inside jsx tags is broken.

### ISSUE THREAD

**Issue by lixiaoyan** [prettier/prettier#3152]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAGgHSgAhwenxwEMYYAnbAPm1X3SoG5tatcSzL3COLrb6TFlAzY8pCgF5gARgC+YgkQlca7eAA8YAhsyitFKyZhAnFPFf3VwtOofpFtxnY6dPdlnQy7Pu1eTW0RQUYQABoQCAAHGABLaABnZFBiBJhkADNiABsEuAiAI3JiMABrOBgAZSiS2KgAc2QKAFd8kAATCDBMnLyIgCsEjQAhYrKKyuIAWzgAGTq4Hty2iGaYKLWAJiW+kBryPPJkEALiAoBPbOhwvfI6mAB1WPaYAAtkAA4ABgi8qdimuRWr86vVsnAAIrNCDwHZtGBnJ4vd5ITYRCjEWLZUEAYQgUymxGOUGgiwizTyABUzkkkFllnI5EA)

**Input:**
```jsx
<X
  // attr
>
</X>;

<X
  attr
  // attr
>
</X>;

<X
  attr={1}
  // attr
>
  text
</X>;

<X
  attr=""
  // attr
>
  text
</X>;

<X
  attr=""
  // attr
  attr=""
>
  text
</X>;
```

**Output:**
```jsx
<X
// attr
/>;

<X
  attr
  // attr
/>;

<X
  attr={1}
  // attr
>
  text
</X>;

<X attr="">
// attr
  text
</X>;

<X
  attr=""
  // attr
  attr=""
>
  text
</X>;
```

**Expected behavior:**
```jsx
<X
  // attr // <- wrong indent
/>;

<X
  attr
  // attr
/>;

<X
  attr={1}
  // attr
>
  text
</X>;

<X
  attr=""
  // attr // <- bug: inline comments should remain here
>
  text
</X>;

<X
  attr=""
  // attr
  attr=""
>
  text
</X>;
```

**Comment by lixiaoyan** [comment]
May be related to #1209, but the code above is more commonly used.

**Comment by ikatyang** [comment]
Similar to #3087 but another case, marked as high-pri since it affected the AST.

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAGgHSgAhwQxhgCcBeTEC7PAehoKOOwD5qd4APGbVG9ZgNwgANCAgAHGAEtoAZ2Sh8smMgBm+ADay4ogEbF8YANZwYAZXGGpUAObISAVx0gAJhDBrN20QCtZHACEDY1MzfABbOAAZazhPLWcIBxhxZIAmeO8QS2JtYmQQXXxdAE8NaBFs4msYAHUpFxgAC2QADgAGUW1wqXtiJy7rGw04AEUHCHhM5xhi+saWpDTREnwpDSGAYQhw8PwCqGg40QdtABVi+SR1BIBfW6A)

**Input:**
```jsx
<X
  attr=""
  // attr
>
  text
</X>;
```

**Output:**
```jsx
<X attr="">
// attr
  text
</X>;

```

**Comment by azz** [comment]
Looks the same as #3087 to me. Could you check against master? (I'm on mobile at the moment)

**Comment by duailibe** [comment]
The case @ikatyang mentioned is bugged on master.

**Comment by duailibe** [comment]
Did some digging, it's not the same case. It tries not to break components with a single text attribute. Looks like it's an easy fix

**Comment by azz** [comment]
Fix landed in `1.8.0`

**Comment by Stupidism** [comment]
@szz It's happening again!
```
> prettier 'src/**/*.js' --list-different

src/components/Form/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-webpack@1.1.0 lint:js: `prettier 'src/**/*.js' --list-different`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-webpack@1.1.0 lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

The code causing this error: 
```
                dropdownAlign={{ points: ['tr', 'br'] }}// docs: https://github.com/yiminghe/dom-align
```
It passes if I add a space
```
                dropdownAlign={{ points: ['tr', 'br'] }} // docs: https://github.com/yiminghe/dom-align
```

**Comment by j-f1** [comment]
@Stupidism that looks reasonable — Prettier formatted it differently than you wrote it, and exited with `1` to tell you to fix the formatting.
