### ISSUE TITLE
Casing of hexadecimal digits in escape sequences

### ISSUE THREAD

**Issue by mathiasbynens** [prettier/prettier#3157]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAcgB1iAPAMQDNSBXa6u4ABmwCEwAROAX0IG4QAGhAQADjACW6ZKGwZkVbABs0cEQCMATtjABrODADKY3ZKgBzZDC211IACYQwilWpEArNGTY79ho2wAWzgAGXM4V1V7CFoYMTiAJij3EFMtNS1kEA1sDQBPZWhhNK1zGAB1SQcYAAtkAA5mETUgyWtbezRzC2U4AEVaCHgU+xg8qpr6pESRG2xJZR6AYQggoOxsqGhIkVo1ABU8tFGeHiA)

**Input:**
```jsx
const a = '\xFf\uFfFf\u{0aBcDe}';
```

**Output:**
```jsx
const a = "\xFf\uFfFf\u{0aBcDe}";
```

**Expected behavior:**

```jsx
const a = "\xFF\uFFFF\u{ABCDE}";
```

Hexadecimal digits in escape sequences can be uppercased or lowercased. Prettier should normalize everything to use the same style. My personal preference would be to use uppercase as such characters more clearly stand out from the lowercase `x` or `u` that start commonly-used escape sequences. (OTOH, Prettier already uses lowercase for non-decimal integer literals. I disagree with that style choice for similar reasons.)

**Comment by duailibe** [comment]
For reference, Prettier used to do this (#522) but was reverted later (#562 and #574)

**Comment by lydell** [comment]
Unfortunately, this can't be done in a nice and safe way :(. See the issues and PRs @duailibe linked to.

(For the record, my original consistent-case PRs _did_ use uppercase for hex digits, but it was decided to go with lowercase. Oh well.)
