### ISSUE TITLE
Rule for destructuring

### ISSUE THREAD

**Issue by pustovalov** [prettier/prettier#3159]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20%7B%5Cn%20%20prop1%2C%20prop2%2C%20prop3%2C%5Cn%20%20prop4%2C%20prop5%2C%20prop6%2C%5Cn%20%20prop7%2C%20prop8%2C%20prop9%2C%5Cn%20%20prop10%2C%20prop11%2C%20prop12%5Cn%7D%20%3D%20props%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--no-semi
```

**Input:**
```jsx
const {
  prop1, prop2, prop3,
  prop4, prop5, prop6,
  prop7, prop8, prop9,
  prop10, prop11, prop12
} = props
```

**Output:**
```jsx
const {
  prop1,
  prop2,
  prop3,
  prop4,
  prop5,
  prop6,
  prop7,
  prop8,
  prop9,
  prop10,
  prop11,
  prop12
} = props

```

**Expected behavior:**
```jsx
const {
  prop1, prop2, prop3,
  prop4, prop5, prop6,
  prop7, prop8, prop9,
  prop10, prop11, prop12
} = props
```

Can I specify an option to get expected behavior?

**Comment by lydell** [comment]
Hi!

There is no such option.

There are several things that can either fit on one line or several lines besides destructuring: arrays, objects, JSX attributes, imports, exports, function parameters, variable declarations... If we add support for your proposed printing for destructuring, people will start asking for the same thing for all those other things. And then people will start asking for 4 items per row instead of 3. And so on :)

The current rule is very simple: Either all of the items are printed on one line, or every item is printed on its own line.

Thanks for your proposal, but I don't think this will make Prettier better, so I'm going to close this one.

**Comment by iurevych** [comment]
@lydell Oh, that would be a useful addition I think. It would improve readability a lot and save some vertical space so all imports don’t take an entire screen to scroll through.

I would suggest simplifying a rule somehow to avoid supporting columns size. What about adding an option called something like `stackElements` to stack props (or any other elements as you pointed out) horizontally until they hit `printWidth` limit? The option value could be an array for easier flexibility in a future:
```js
// .prettierrc
{
  "stackElements": ["destruct"]
}
```

The option will convert a following destruct:
```jsx
const {
  prop1, prop2, prop3,
  prop4, prop5, prop6,
  prop7, prop8, prop9,
  prop10, prop11, prop12
} = props
```

Into this one (assuming `printWidth` is `80`):
```jsx
const {
  prop1, prop2, prop3, prop4, prop5, prop6, prop7, prop8, prop9, prop10, prop11
  , prop12
} = props
```

Here is where it benefits more (with `import` notation):
```jsx
import { injectField, injectSectionHeader, superAdminOnly, injectFieldUpdater, notGleamCampaignOnly } from './misc'
```

After re-formatting:
```jsx
import {
  injectField, injectSectionHeader, superAdminOnly, injectFieldUpdater,
  notGleamCampaignOnly
} from './misc'
```

This way there is no need to think about columns size.
Thank you for Prettier!

🤞

**Comment by aboyton** [comment]
There's nothing special about destructuring here. The exact same thing happens for function parameters, if it fits on one line it will, otherwise it's one per line.
