### ISSUE TITLE
Can't add space before function parentheses

### ISSUE THREAD

**Issue by dijonkitchen** [prettier/prettier#3161]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9SBnATyjD2PKZgEtoAKCDT6LSR4ASnACO5OLRgB5flyi0AlHmABfEABoQfAUuSg6MZGUq04OgEbZSYANZwYAZQx2OUAObIY2KToIIMFNSc0sQACtaNAAhWwcnZ1IAWzgAGQ84ELCdCHIYDHyAJmyLHTdsC2xkECtSK3pKaG0QDGwPGAB1DgIYAAtkAA4ABh0LZI4fP3DaD09KOABFcgh4UvCYeu7egaQinV9SDko5gGEIZOTSGqhoLJ1yCwAVetp19XUgA)

Note: This is an incompatibility with Standard JS: https://standardjs.com/#the-rules

**Input:**
```jsx
export default async function(options: RequestOptions) {}
```

**Output:**
```jsx
export default async function(options: RequestOptions) {}

```

**Expected behavior:**
```jsx
export default async function (options: RequestOptions) {}

```

**Comment by suchipi** [comment]
This is the intended behavior/formatting style of prettier. See https://github.com/prettier/prettier/issues/1139 for more detail.

**Comment by coolemur** [comment]
This is an ugly bug.
Because it goes against Standard JS.

When one program code prettifiers, one shall follow the standards of code.
When one program code prettifiers, one shall add turn on/off options for all prettifier actions.

Please, fix this ASAP and don't link people to further discussions.
Because this is obvious and non-questionable.

Cmon, people, use your common sense.

**Comment by evilebottnawi** [comment]
@coolemur no, thanks for issue

**Comment by coolemur** [comment]
@evilebottnawi No? You mean you don't fix your bugs?

**Comment by evilebottnawi** [comment]
@coolemur it is not bug, where you see bug?

**Comment by coolemur** [comment]
@evilebottnawi Prettier doesn't follow JS standards AND no space before brackets is forced (no option to turn it off). You limit your tool. You can't even answer the question with your own words and your own thoughts (not linking to discussions).

I guess this tool is not for vue users then. Thanks for clarification. :)

**Comment by evilebottnawi** [comment]
@coolemur holy war :trollface: This is specifically your preference and only, a lot of vue users do not use your writing style. Your given standard is not a standard (there are no documents that say that this style is required for use when writing `js/jsx/vue/etc`). It's just an example of how many/few people gathered and decided to use a single style. We decided that this style is not beautiful, so just take prettier style and do not try to argue with it.

**Comment by coolemur** [comment]
@evilebottnawi I will talk facts. You can talk your troll words. Ok ? :) It's not "holy war" it comes from practice coding projects.

1. With default vue project comes default linter. Which says space must be added. That's a fact.
2. Your tool has forced rules. Thus it creates it's own "custom standard". That's a fact.
3. Your tool would be much better and would be used by vue developers if you'd just add customisation to turn on/off this option. That's a fact.
4. Your tool would be much better if you would keep "default option set" as your standard as you want it to be, just let people to tweak it. That's a fact.

I am not here to fight your imaginary "wars". I have an issue with your tool which blocks me to go further. And this is why I try to help you improve your tool.

**Comment by coolemur** [comment]
@evilebottnawi https://github.com/standard/standard . You can't use your tool if you follow these standards. Thats a fact.

**Comment by evilebottnawi** [comment]
@coolemur Tomorrow there will be another hundred people who will ask to add an option. Maybe you will help us to develop and maintain the project? It's always easy to argue, than to help. 

1. You can change linter settings, many people and companies change default linter settings. That's a fact.
2. We don't say what we standard, we just print beautiful code. That's a fact.
3. That's not a fact, it is just you opinion.
4. That's not a fact, it is just you opinion.

You can use https://github.com/prettier/prettier-eslint which run prettier and then run eslint rule. But i can just don't use this tool :trollface: 

Also if you read answer better you can found this https://github.com/prettier/prettier/issues/3503#issuecomment-359863688. It is breaking changes and shipped only in `2` version.

**Comment by evilebottnawi** [comment]
@coolemur You repo is not standard. Where is written that this is the standard?

**Comment by coolemur** [comment]
@evilebottnawi So you force me to change default project rules (which are official at vue) instead of making your rules optional ? (I am not asking to ADD a rule, just to make your rules optional while keeping your default options as they are). This would end all your "wars" in those discussions.

**Comment by evilebottnawi** [comment]
@coolemur This would not end all your "wars" in those discussions. It is start wars, add one prefer option, other people start own prefer options. You can don't change default lint option. Just use `prettier-eslint` and all.

**Comment by coolemur** [comment]
@evilebottnawi You don't listen to those who use your library. Well good luck maintaining it. :) Have a nice day sir.

**Comment by evilebottnawi** [comment]
@coolemur look on stars :+1:

**Comment by j-f1** [comment]
@coolemur This issue is a duplicate of #3847. Please add your 👍 there. We’re considering changing this behavior.
