### ISSUE TITLE
Alternate between * and - for sub-lists

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3174]
**Prettier 1.8.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABAQQDpXegWiwEZd98NNiA6UvQrAJlwwCEyHW78jXn6K6PrVwgANCAgAHGAEtoAZ2SgAhgpjIAZioA2CuBIBGAJxVgA1nBgBlKWdlQA5shjGArgZAATCGC279CQArBQAPVlMLK2sVAFs4ABkHOH89Twg3GClMxlTAkDtjfWNkEFiVY3MfAHcocQLjBxgAdVkvGAALZAAOAAYJfVjZF3dPBQdHHTgARTcIeDzPGBVDVvaupEYJVxVZHQmAYQhY8tLdHXq3fQAVFaUkbTSAXyegA)
```sh
--parser markdown
```

**Input:**
```markdown
* A
  - A1
    * A1.1
  - A2
* B
  - B1
  - B2
    * B2.1

```

**Output:**
```markdown
* A
  * A1
    * A1.1
  * A2
* B
  * B1
  * B2
    * B2.1
```

Expected output same as input.

**Comment by lydell** [comment]
Is this a common thing? I've never written nested lists like this (but now that I've seen it, I wouldn't mind if Prettier formatted this way), and I could easily see people reporting that as "inconsistent list markers" or "list markers don't always change".

**Comment by suchipi** [comment]
I've never seen this before...

**Comment by azz** [comment]
Huh, I thought this was common practice. Needs further research!

**Comment by azz** [comment]
As I mentioned, I thought this was common practice. If it's not we can close it.
