### ISSUE TITLE
JSON in markdown should not get trailing commas

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#3175]
**Prettier 1.8.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAztAOlYfAAiNxADMIIylSQAjAQwCcz8BffdVEAGhAgAHGAEtoWZKEZYYycowA2WOP3rNGYANZwYAZUEaRUAObIYzAK4qQAEwhg5i5f2wAPAELqtO3YwC2cAAyRnCOStYQFjCCUQBMYc4gBszKzMggfiyadgDuUHxJzEYwAOoiNjAAFsgAHAAM-Mp+ImaW1lhGxgpwAIoWEPAJ1jCM9GUV1Uix-OaMIgqdAMIQfpnpigoFFsoAKqMSSPLh7OxAA)
```sh
--parser markdown
--trailing-comma all
```

**Input:**
````markdown
```json
{
  "foo": "bar"
}
```
````

**Output:**
````markdown
```json
{
  "foo": "bar",
}
```

````

**Expected behavior:**
No change (to match json standalone https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm0gGYQS5I4gBGAhgE64YC+GIANCBAA4wCW0AzsqBR4xkeCgBsecFmSoUwAazgwAymzmcoAc2QwqAVykgAJhDAjxklgCseADwBCshUuUUAtnAAyGuOYmGIPRg2IIAmP0sQNSpJKmQQG2hmKKoNGAB1TiMYAAtkAA4ABhZJN04dfUMeDU0xOABFPQh4CMMYCjJM7LykUJZdCk4xGoBhCDc3CnjxMWS9SQAVDr4kUX86OiA)

**Comment by azz** [comment]
This has been fixed in `1.8.1`.
