### ISSUE TITLE
JSON comment at the top moved into object

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#3178]
**Prettier 1.8.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgQzAaxwHM4A6AKwGdoAdKYOjDdDGACwEtKMuMAzCBEYYaIAUOQiQAIxwAnUXQC+IADQgIWGB2iVkoHJRjI+OADaU466XLz44MAMq4wHKEWQw5AVysgAJhBgJuaW6lQAHgBCtgQOjjgAtnAAMm5wIRZ+EN4wWLkATJlhILhylnLIIFTQaqVybjAA6hz+7MgAHAAM6paJHJ4+fpRuRGZwAIreEPDFfjA40i1tbMgF6l44HGajAMIQiYk4VVDQGerelgAqi3pIpllKSkA)
```sh
--parser json
```

**Input:**
```json
// package.json
{
  // this is foo
  "foo": "bar"
}
```

**Output:**
```json
{
  // package.json
  // this is foo
  "foo": "bar"
}

```

**Expected behavior:**
I expected input to be unchanged.

**Comment by azz** [comment]
This has been fixed in `1.8.2`.
