### ISSUE TITLE
Markdown: make line wrapping an option

### ISSUE THREAD

**Issue by Haroenv** [prettier/prettier#3183]
**Prettier 1.8.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB5KcAEBbCAnKASygHMAaTAdwAsFMBxPOE-TAZQENsBnDqiANZYAZngjZMMMQFcARgBs4AE0xKmXbhVqZhEaVBXVCPOPOGS8HKN115syzMUxHumWQ+IwImPtXx5CBSwANzg7YgA6TAAJLHkOAE9MaGdCVw47PTwAWnlCITcOMAEKKxVCc2084XhDNOc4DhU+PJgYRQbMSGl5FW44LBc3MUooN1N5BIpuPJJqdqSlcQcy1UJgwiUHWSSMsFpXT29uGArzfrBT6G4ogBVtdyUlYhIqDldqDKVJnyDJb0goTwjhgPgMmH6cHsKnUSiSXgheS2yWE5isSVw9lgUWi9Ww6MwihImkwAAdCKdhD0fjAjGNINhSRkHJQKdRJNpuIQAF5YCDmWlYJgnFGpbAUSgcULNWR6UG0eSkxTcGa7D5xCCCZRRAA6IAA6p8YAByD4cUmkhAOBH2AD8es6tL0cxgUQAkqDJdwoMbQXw1I1sDj6mJxKUyWJLcDqNJ8WNQxIOPIndI5j5CRT2lgvMd8fJ5BR4klLUU4FT80l3DBKAMxhTXLppMDhFxCHkMm98zdMABBLoQfNwS6EFL8yRwAAepw6vEZysJiQhpNhyWkoJSgskHD+2XYGj4XvTUilExeEKTcG4ccwu9W24goRBHLCg30rz45MuTezRs6nxhQ4IAsXRrqu65onW+bSCcli1DgHAkBw3LEFgqx+NBHhjHwRBgHAFAkG2WwqKIXBwO6oLcH4NbNAucI6JmDhylQbLplS0YcH64JsW4EAHn456gtIy6EC6FCWGkZ6+I0wRJNx2DSKiHIcf2QLWtoNADnylRhISEA1sCGQSF4kp4EoribhscD6VEjDMKwgpjDATYYCoCLyJqAhgc+zEGHpPigpuSjUlQjSCngUQACKRtwOpQLFIBkCAECklc1jIKAwmwPqmy0sgAAcAAMiUwNu2VKLlSAAEyJVypCKAAitIEDwMgLbyP0xXiXkpAAMLiPiyAgFA0BwAlICyJYxRwDAbBMmALzIFI0h4SAABW3ATgAQpNQgzaRAAyKGtUmHUgEyeD9Hgg34ngAhLKMY39NghCLXgy2JRhtzbtwx3tStSxgL9p3vDAQMrXKpJrpVYMAL4w0AA)
```sh
--parser markdown --prose-wrap=false
```

**Input:**
```markdown
One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look out the window at the dull weather. Drops
```

**Output:**
```markdown
One morning, when Gregor Samsa woke from troubled dreams, he found himself
transformed in his bed into a horrible vermin. He lay on his armour-like back,
and if he lifted his head a little he could see his brown belly, slightly domed
and divided by arches into stiff sections. The bedding was hardly able to cover
it and seemed ready to slide off any moment. His many legs, pitifully thin
compared with the size of the rest of him, waved about helplessly as he looked.
"What's happened to me?" he thought. It wasn't a dream. His room, a proper human
room although a little too small, lay peacefully between its four familiar
walls. A collection of textile samples lay spread out on the table - Samsa was a
travelling salesman - and above it there hung a picture that he had recently cut
out of an illustrated magazine and housed in a nice, gilded frame. It showed a
lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur
muff that covered the whole of her lower arm towards the viewer. Gregor then
turned to look out the window at the dull weather. Drops
```

**Expected behavior:**

```markdown
One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look out the window at the dull weather. Drops
```

**Comment by azz** [comment]
Bikeshedding for the name, I think `--no-word-wrap` would be better.

**Comment by Haroenv** [comment]
but we would still want wrapping for JS in codeblocks, I'm not sure if that was clear 😄

**Comment by azz** [comment]
I think it's clear. If you didn't want code to wrap you could set `--print-width: 1000000`.

**Comment by ikatyang** [comment]
With this option, CJK users can also use Prettier for CJK-line-ending-unsupported renderer.

**Comment by Haroenv** [comment]
My main reason is that small changes will have bigger diffs is sentences start to flow over into other lines, and in count the complete paragraph. Otherwise because it's the style already used by a lot of people, and we don't want to scare them away maybe?

**Comment by suchipi** [comment]
For what it's worth, editors with soft wrap / line wrapping / word wrapping features can align a long, long one-line paragraph into the viewport, similar to how MS Word works.

**Comment by azz** [comment]
I think this is a valuable option. Who wants to give it a shot?

- Go with `--no-prose-wrap` for now
- Entire paragraph per line.

**Comment by azz** [comment]
_Alternatively_, do we want a third option?

- No wrap (paragraph per line)
- Sentence-per-line
- Auto-wrap

**Comment by suchipi** [comment]
Do people do sentence-per-line?

**Comment by lydell** [comment]
I read about that in a blog post or article some time (which even suggested splitting after commas and other punctuation sometimes to minimize git diff / merge conflicts), but I’ve never seen or used it for real.

**Comment by azz** [comment]
I often do sentence per-line. I find it much easier to comment on in PRs.

**Comment by azz** [comment]
This has been added in `1.8.2`.

**Comment by Haroenv** [comment]
awesome, thanks @ikatyang

**Comment by borekb** [comment]
This is great! We never wrap Markdown for better diffs and simpler writing experience so this makes Prettier MD usable for us. Thanks!
