### ISSUE TITLE
Force space after ATX style heading prefixes

### ISSUE THREAD

**Issue by joemaller** [prettier/prettier#3197]
**Prettier 1.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABJgEnAhgEwEsoBzdARgB0pVUcDiyAma29eo09J9ACmPwJ4+AJQgANCAgAHGIWgBnZKGkAnYjADqhfDAAWyABwAGSTFwAjbboNImkhYwA2cAIoBXCPGQAzXE4U4M1VcQidGAGEIAFto3GQQKGg4CRALELAAazgYAGVpXDBGZBhVdyCQACsFAA8AIQzsvNxouAAZYhSkPwCKgtVA1QSLSwBPJ2hUwOjCErKK90CAFUslbv9AyXwIMF8NitwFGD3eyQh3GGkLphPAgF87oA)

**Input:**
```markdown
#   Heading 1
##Heading 2
## Heading 2 (indented)
```

**Output:**
```markdown
# Heading 1

##Heading 2

## Heading 2 (indented)
```

**Expected behavior:**

```markdown
# Heading 1

## Heading 2

## Heading 2 (indented)
```

Headings should be normalized to a single space after `#` characters. Both are occasionally legal, but GitHub notoriously chokes if there's no space after the `#`s. 

Extra spaces are already normalized down to a single space, but no spaces are inserted if they're missing. 

See CommonMark Spec [4.2 ATX headings](http://spec.commonmark.org/0.27/#atx-headings)

> The opening sequence of `#` characters must be followed by a space or by the end of line.

> At least one space is required between the `#` characters and the heading’s contents, unless the heading is empty. Note that many implementations currently do not require the space.

**Comment by azz** [comment]
This is because it is being parsed as a regular paragraph, not a heading. (Which is to spec).

**Comment by ikatyang** [comment]
As you mentioned above:

> At least one space is required between the `#` characters and the heading’s contents

There's nothing we can do for it since we promised not to affect the AST.

**Comment by suchipi** [comment]
Does the "no changing the AST" promise make sense for markdown? Markdown is read by humans, not machines- the "no changing the AST" promise is useful when working with code, because then we can guarantee that we aren't changing the semantics of the program. But in Markdown, we might want to reconsider.

**Comment by ikatyang** [comment]
Yeah, but in OP's case, the proposed change is to change a heading-like paragraph into heading, which will affect the rendered content (won't change if the renderer not followed CommonMark spec, but we do follow the spec).

**Comment by suchipi** [comment]
But I think that when that heading-like paragraph structure shows up, it *might* always be a typo. I'm not 100% sure, though (and don't know how I'd find out).

**Comment by lydell** [comment]
@suchipi No, it is not always a typo: http://spec.commonmark.org/0.25/#example-32

```markdown
#5 bolt

#hashtag
```

**Comment by suchipi** [comment]
Ah okay, those make sense.
