### ISSUE TITLE
Comma operator inside array

### ISSUE THREAD

**Issue by zonzujiro** [prettier/prettier#3200]
**Prettier 1.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEcAeAHAJzjTQEtpMBeTAfQDoAzAGwgHcAKeh0p+AzuqQAmCGKRgBPAJQAaWnQBWEUlHYByAGRqpUgNpEAjgFdiMAPIAjBXDAw6AGQgBzUmACGTAKL4iJclDkAA3YAcQIIIzwaABJgJ3DIgEkhAF8pQIBdEBkQCDwxdGRQNwxkBg80OByLAjcwAGs4GABlPDqVJ2QYAhMcoQgwMoqqkAU0HAAhWoam5rcAWzh7FTghpkqciJg8IxgAJjWNkDaCSoJkEAs3CwkWKGzjghUYAHVhGAALZAAOAAYcyrzUhdHojMhQJxMOAARSMEHgIN6IBg1zeQk+yD2OW6bh4HQAwhB5vM3BdiABWB5GSoAFWuaEOcBSKSAA)
```sh
--single-quote
--trailing-comma es5
```

**Input:**
```jsx
const expression = _.flow(_.filter(_.identity), _.join('&'))[requestObject.logicalExpression, `(Group_${groupId})`]
```

**Output:**
```jsx
const expression = _.flow(_.filter(_.identity), _.join('&'))[
  (requestObject.logicalExpression, `(Group_${groupId})`)
];

```

**Expected behavior:**

As you can see, prettier adds [comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator) into the array, therefore array always will be with one element — last operand of the comma operator.

Expected behavior will be array without comma operator.

**Comment by suchipi** [comment]
Not sure why this was closed, but this changes the AST, and so should be fixed.

**Comment by suchipi** [comment]
Oh, wait, I lied. It was actually a sequence operation before; the brackets are a computed member expression, not an array.

**Comment by zonzujiro** [comment]
I closed issue because I made mistake in the code.

This is how it's *must* be:

```jsx
const expression = _.flow(_.filter(_.identity), _.join('&'))([requestObject.logicalExpression, `(Group_${groupId})`])
```

And this is the result:

```jsx
const expression = _.flow(_.filter(_.identity), _.join('&'))([
  requestObject.logicalExpression,
  `(Group_${groupId})`,
]);
```
So everything is ok.
