### ISSUE TITLE
Style template literals are not indented properly

### ISSUE THREAD

**Issue by chadfawcett** [prettier/prettier#3208]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20Test%20%3D%20()%20%3D%3E%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%3Cp%3ETest%20text%3C%2Fp%3E%5Cn%20%20%20%20%3Cstyle%3E%7B%60%5Cn%20%20%20%20p%20%7B%5Cn%20%20%20%20%20%20color%3A%20pink%3B%5Cn%20%20%20%20%7D%5Cn%20%20%60%7D%3C%2Fstyle%3E%5Cn%20%20%3C%2Fdiv%3E%5Cn)%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
const Test = () => (
  <div>
    <p>Test text</p>
    <style>{`
    p {
      color: pink;
    }
  `}</style>
  </div>
)
```

**Output:**
```jsx
const Test = () => (
  <div>
    <p>Test text</p>
    <style>{`
    p {
      color: pink;
    }
  `}</style>
  </div>
);

```

**Expected behavior:**

I expect the style tags to be indented evenly and their content indented appropriately.

```jsx
const Test = () => (
  <div>
    <p>Test text</p>
    <style>{`
      p {
        color: pink;
      }
    `}</style>
  </div>
);
```

**Comment by duailibe** [comment]
Actually we don't format anything for `<style>`, it just re-prints the template literals as is. Did you mean `<style jsx>` ?

**Prettier 1.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVOHMC8mAFAJSEB8JAOlJpgDwAmAlgG4W330MAOFufPAAeMBgHp+XbgwwBPADZxMAKzTCKwAAa9MwTJAUQATkky8WUANaYAvltsT5SznUbjWHWqRAAaEBC8MCzoyKAAhhjIAGbhCmhw-gBGxuFgVnAwAMq8aZYA5sgwxgCuiSBMEGAxcQn+asIAQqnpmVnhALZwADKWcDXx5RAlMLwjAEwDdSC5xgnGyCBJ4UmK0H4zxpYwAOosTDAAFsgAHAAM-gkdLEWl5WgFSgCKJRDwU+UwK3sHx0jj-mK4RYCgKAGEIB0OuFFlBoP1-CUEtgVmgPrZbEA)

**Input:**
```jsx
const Test = () => (
  <div>
    <p>Test text</p>
    <style jsx>{`p { color: pink }`}</style>
  </div>
)
```

**Output:**
```jsx
const Test = () => (
  <div>
    <p>Test text</p>
    <style jsx>{`
      p {
        color: pink;
      }
    `}</style>
  </div>
);

```

**Comment by chadfawcett** [comment]
Oops, I didn't realize I needed the `jsx` attribute. Thanks!
