### ISSUE TITLE
Ignored unknown option: --insert-pragma

### ISSUE THREAD

**Issue by gnarmedia** [prettier/prettier#3210]
So I'm just trying to run prettier as a test run against come js to see the pragma in action, but it seems to be broken?

```
$ ./node_modules/.bin/prettier --insert-pragma --write "modules/Store/docroot/cm
n/sitejs/brand-landing/brand-landing.js"
Ignored unknown option: --insert-pragma

Ignored unknown option: insertPragma
```

```
/mnt/VMSharing/GCWorkspace/SourceCode * ECMD-4740 $ ./node_modules/.bin/prettier -v
1.7.4
```

I am confused, I also tried it at the end of the line and after --write

Then I checked the downloaded dependency's source and I don't even see this functionality in the index.js?  I'm confused, is it just me?

**Comment by SimenB** [comment]
You need to use version 1.8

**Comment by gnarmedia** [comment]
@SimenB wow, thanks, I didn't see that the docs were updated 2 days ago
