### ISSUE TITLE
Some test dirs don't have snapshots

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3214]
```bash
prettier/tests $ for d in *; do [ -e $d/jsfmt.spec.js ] || echo $d; done
css_less_docs
css_loose
flow
stylefmt
typescript
```

`flow`, `stylefmt` and `typescript` are exceptions (they have more directories inside) but the other two are missing snapshots. We need to add them! Maybe even add a validation script, too?

**Comment by fisker** [comment]
css_loose #7378

**Comment by fisker** [comment]
css_less_docs: 

https://github.com/prettier/prettier/blob/310fba57ccb6409c95083f41f68a47365ab7fedd/tests/css_less_docs/less_docs.css

seems live in `css_less` now

https://github.com/prettier/prettier/blob/master/tests/css_less/less.less

Should good to close after #7378
