### ISSUE TITLE
`[warn] Ignored unknown option: proseWrap`

### ISSUE THREAD

**Issue by icylace** [prettier/prettier#3216]
**Prettier 1.8.1**

I have [`proseWrap`](https://prettier.io/docs/en/options.html#prose-wrap) set in my `prettier.config.js` file but when I use the `prettier` CLI tool on my JavaScript files I get the message `[warn] Ignored unknown option: proseWrap`.

Obviously, `proseWrap` is only relevant for Markdown files but the `prettier` tool needs to be able to recognize that option and silently ignore it when appropriate.

Other than that, things seem to work well.

**Expected behavior:**

The `prettier` CLI tool does not warn about "unknown" options that are actually real options that appear in Prettier's documentation.

**Comment by ikatyang** [comment]
Sorry for the confusing, the `proseWrap` option haven't released yet but it'll be in the [next patch release (1.8.2)](https://github.com/prettier/prettier/milestone/6?closed=1).

We should add a `since vX.Y.Z` note for it.

**Comment by icylace** [comment]
Ah, I see.  Thanks  :)
