### ISSUE TITLE
Similar one-liner objects in an array

### ISSUE THREAD

**Issue by icylace** [prettier/prettier#3220]
**Prettier 1.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATAhjXTAXkwG0AdKTTYTASyUwFZMBfAGkuoqupswAejAGztMAT0YB2AAxtOvarSGYAHGMmYAnHI5c+yxuomMd8-QF0F1AIwyFFyiHYgIABxh10yULgzIAM1wAGzQ4FwAjACdcMABrOBgAZTdYuigAc2QYKIBXcJBsCDBAkLCXACs0AQAhGPjEpNwAWzgAGXS4UtCCiFyYN36AJm7ykFSosKjkEAjcCPFg6GdxqPSYAHU6bBgAC2RVexAw5rpRgrR0jOC4AEVciHhzlwIIrZ39pCGXmLpgq4AwhBms1cDMQsEVrkwgAVeZoc6sVhAA)
```sh
--no-semi
--trailing-comma all
```

**Input:**
```jsx
const data = [
  { i: 5 },
  [
    { x: 6, y: 70 },
    { x: 8, y: 90 },
    { x: 8, y: 90 },
  ],
  10,
]

```

**Output:**
```jsx
const data = [{ i: 5 }, [{ x: 6, y: 70 }, { x: 8, y: 90 }, { x: 8, y: 90 }], 10]

```

**Expected behavior:**
Within the nested array are some one-liner objects that have similar keys.  Since these one-liner objects are similarly shaped, stacking them vertically offers a column-like visual consistency.  In other words, there's an `x` "column", and a `y` "column".  So, here the expected output should be exactly the same as the input.

**Comment by RyanZim** [comment]
I'd argue this is just a good place for `// prettier-ignore`, since you want arrays collapsed onto one line most of the time.

**Comment by G-Rath** [comment]
I want to throw my opinion into the ring, since this has got the "needs discussion" tag, and frankly this is one of the only formatting opinions that I'm against and so is greatly slowly my adoption of it. 

> since you want arrays collapsed onto one line most of the time.

I very much disagree, and also say it's (unfortunately) very contextual.

The majority of my arrays are ones like this:

```
  return Array.from(
    new Set([
      ...a.split(UNION_SEPARATOR),
      ...b.split(UNION_SEPARATOR)
    ])
  ).join(UNION_SEPARATOR);
```

```
        [
          'strips out ":" from times',
          { timeFrom: '08:00', timeTo: '08:00' },
          [
            { startTime: { $gte: '0800' } },
            { startTime: { $lte: '0800' } }
          ]
        ],
```

```

**Comment by thorn0** [comment]
Fixed by https://github.com/prettier/prettier/pull/6694 ([1.19 release notes](https://prettier.io/blog/2019/11/09/1.19.0.html#break-arrays-of-arraysobjects-if-each-element-has-more-than-one-elementproperty-6694-by-sosukesuzuki)). The heuristic found there turned out to be good enough.
