### ISSUE TITLE
--print-width is ignored

### ISSUE THREAD

**Issue by vitalii-svitla** [prettier/prettier#3228]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoByAWwE8ACeDGKjAV13hIBoqiBKKgXgD4qwADowWpVBEwMIZODAAWuKAHMq2OAEMANturboazVFRVIZAA7bcYTfFMYIVAJJUFmgG5waTgO554Kk0qL2x9QyooTTkqADMIbBoFb1oYdk4eASEqHKpRSChHbTgAOgMVUmTdCABCEi4AbmEoXKoAX0bmnK68sRhKzQxI6JT3emxGQvVcFQV6RgsfJO84VBVvR2Wg7GwIXzjJsDFoKlwh31w4bFR07j5BYFb86CLS8tJfBO1UOs6W3I6TSggJAbBAEAsx0KyFAgxgyFiOgwcDB+GwmjAAGt5ABlCwY5QqBFIlFoCBgYnaZFg5TI7AwAAK6JUZE0lOpIAAVhgAB4AIXRWNxIwAMso4OzSRBGDALDKAEySsH47B05AgUEgCx4WAAdVwqEUyAAHMaAAzK3bI3XoixKkAaACOzA0TM0LLZSERVNJyLIuHtGEJxQAiowIPBkDAJqSYJp8PrDQpkPKwdHNLhrKoAMKyVnqzWMZEAFXjGElbTaQA)
```sh
--no-bracket-spacing
--parser 
--print-width 880
--no-prose-wrap
--no-semi
--single-quote
--trailing-comma 
```

**Input:**
```
describe('my test suite', () => {	it('does something really long and complicated so I have to write a very long name for the test', () => {    	console.log('hello!');
    });
  
  	it('has name that runs right up to the edge so the arrow function is wierd', () => {    	console.log('world!');
    });
});
```

**Output:**
```
describe('my test suite', () => {
  it('does something really long and complicated so I have to write a very long name for the test', () => {
    console.log('hello!')
  })

  it('has name that runs right up to the edge so the arrow function is wierd', () => {
    console.log('world!')
  })
})

```

**Expected behavior:**

Due to --print-width 880, shouldn't the Output be the same as Input? In this case, first line of the Output should be 
```
describe('my test suite', () => {	it('does something really long and complicated so I have to write a very long name for the test', () => {    	console.log('hello!');

**Comment by lydell** [comment]
There are places where Prettier puts line breaks regardless of print width. It never tries to shove multiple statements on the same line like that. Imagine this:

```js
const a = b + c;
const d = a + 5;
```

... being turned into:

```
const a = b + c; const d = a + 5;
```

... just because it fits in a single line. Not nice at all.

That being said, there _are_ things that can be printed in a 880 chars long line if you want:

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAFAQwDQ77g-Iwk4s0i8qym6u2h+pxl5t1j9rzn7v3gfyGCRwsaInjyAShDYQEAA4wAltADOyUJnUxkqTABt1ceQCMATpjABrODADKi6yqgBzZDAsBXUyAAmEGD6RibyriYWMAAKVm4Atpghxn4AVuoAHgBCVrb2DpjxcAAyrnDJYQreMIrVAEwVfs4WkcggciCKFq4wAOoq-jAAFsgAHKMADPJdECa9VoqePn4WcACO3iqrsZgJSUgGKfIm8SpLvseuboZwAIreEPCN8jCYZv2DI0h1L1YqhlcAMIQeKJNodbwmAAqb00B1CcAAvoigA)
```sh
--parser 
--print-width 880
--trailing-comma 
```

**Input:**
```
f(a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,)
```

**Output:**
```
f(a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a, a);

```

**Comment by vitalii-svitla** [comment]
Hi, thanks for fast answer!

But what about the arguments? For example, i want to prevent transformation of this code

```
this.rM.hA = this.rM.startHA + 2 * diffX * 360 / size;
this.rM.vA = Math.max(Math.min(this.rM.startVA + 2 * diffY * 180 / size, 90), -90);
```

into this

```
this.rM.hA =
  this.rM.startHA + 2 * diffX * 360 / size;
this.rM.vA = Math.max(
  Math.min(
    this.rM.startVA + 2 * diffY * 180 / size,
    90
  ),
  -90
);
```

Shouldn't it be handled by --print-width? Even if its not a bug - still it looks a bit unintuitive.
Please, see the details at https://stackoverflow.com/questions/47209641/prettier-in-vs-code-formatting-new-lines-before-arguments

**Comment by lydell** [comment]
Your example already prints on one line just fine. Perhaps you have made a mistake in configuration somewhere? Or another tools does something?

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOgE4CyOaAggAQC8Z62+RWMAhnjABLkDUZATGQFRkAJhgBmIgBr8yAZgBsABjIB6MlgwAvOAG4AOrEy5COAG7kqBRuhwBbRgA8AFBavWMUBzUP0mLAGqceKWExAE0pAEYADkUVNU0AGjIATnkASkSAWhTUrRB4kAgABxgMaCxkUEYGZBFGABssOHyAIzxGMABrOBgAZUL2twBzZBg8AFcmkEEIMBr6xvy3RpYABTbB2zmGyYArLDsAITbO7p7GazgAGTc4LYWCsZhCx+47yf68ZeQQZsZmgE86tA8iBCng3DAAOoYQToZCRaT5MEQRqQtqFEbjSZ4OAARzGGBxa0YG0Yb3yjVcmImFKGdTgAEUxhB4OTUH9obC0MhuPlRowMHUhgBhCDWTYoKDQW75MaNAAqf3KSFq2wAvmqgA)
```sh
--print-width 83
```

**Input:**
```jsx
this.rM.hA = this.rM.startHA + 2 * diffX * 360 / size;
this.rM.vA = Math.max(Math.min(this.rM.startVA + 2 * diffY * 180 / size, 90), -90);
```

**Output:**
```jsx
this.rM.hA = this.rM.startHA + 2 * diffX * 360 / size;
this.rM.vA = Math.max(Math.min(this.rM.startVA + 2 * diffY * 180 / size, 90), -90);

```

**Comment by vitalii-svitla** [comment]
Yeah, at first i was thinking about Tslint, but after playing a bit, i've figured out that it was Prettier (by disabling/enabling plugins one-by-one). I'm using Prettier as a part of Angular Essentials, in MS Code.

**Comment by vitalii-svitla** [comment]
@lydell so, any suggestions? Or can you refer someone who can help? 
It isnt looking like uncommon issue, i believe its pretty basic stuff.

**Comment by lydell** [comment]
@vitalii-svitla Find a couple of hours, dig into Angular Essentials and MS Code, make a minimal reproduction, report to the relevant project, try to fix it, etc. Debugging tool integrations is often tricky – it can be hard to find exactly what happens, where and why. Good luck!

**Comment by vitalii-svitla** [comment]
Yeah, pretty obvious stuff :)
I was thinking someone have already faced it.

Thanks, i'll update this thread if/when i find the issue.
