### ISSUE TITLE
Config override only root .js files

### ISSUE THREAD

**Issue by chrisblossom** [prettier/prettier#3231]
How do you only override base ``.js`` files?

```js
// prettierrc.js:
'use strict';

module.exports = {
    semi: true,
    'tab-width': 4,
    'single-quote': true,
    'trailing-comma': 'all',
    overrides: [
        {
            files: './*.js',
            options: {
                'trailing-comma': 'es5',
            },
        },
    ],
};
```

**Expected behavior:**
All root ``.js`` files should have the config ``'trailing-comma': 'es5'``. As of ``1.8.2`` this does not work.

Thank you!

**Comment by duailibe** [comment]
Good question! I'm not sure there is a pattern that matches only the root folders, maybe using `!`? I didn't get it to work, but this seemed to work though:

```js
// prettierrc.js:
'use strict';

module.exports = {
    semi: true,
    'tab-width': 4,
    'single-quote': true,
    'trailing-comma': 'es5',
    overrides: [
        {
            files: '*/**/*.js',
            options: {
                'trailing-comma': 'all',
            },
        },
    ],
};
```

Maybe someone can come up with a more straightforward solution :-)

**Comment by duailibe** [comment]
Ahhh how could I forget. You can just add an `excludeFiles` key:

```js
// prettierrc.js:
'use strict';

module.exports = {
    semi: true,
    'tab-width': 4,
    'single-quote': true,
    'trailing-comma': 'all',
    overrides: [
        {
            files: '*.js',
            excludeFiles: '*/**',
            options: {
                'trailing-comma': 'es5',
            },
        },
    ],
};
```

**Comment by lydell** [comment]
It sounds like this question has been answered, so I'm closing.

**Comment by azz** [comment]
Configuration should be camelCase (`trailingComma`) by the way. Not sure if it even works with kebab-case, and if it does, that's an accident.

**Comment by chrisblossom** [comment]
@duailibe your suggestions worked, thank you!
@azz Thanks. kebab-case was working, but I will update my config files to camelCase.
