### ISSUE TITLE
not formatting .ejs files

### ISSUE THREAD

**Issue by vajahath** [prettier/prettier#3232]
**Prettier 1.8.2**
`.prettiuerrc`
```json
{
	"trailingComma": "all",
	"useTabs": true,
	"singleQuote": true,
	"tabWidth": 4,
	"semi": true
}
```
```
$ prettier 'src/**/*.*' --write
```
makes this err

**Output:**
```
src/views/error.ejs
[error] src/views/error.ejs: SyntaxError: Unexpected token (1:6)
[error] > 1 | <h1><%= message %></h1>
[error]     |      ^
[error]   2 |     <h2><%= error.status %></h2>
[error]   3 | <pre><%= error.stack %></pre>
[error]   4 |
```

**Comment by ikatyang** [comment]
Prettier will use babylon parser if it can't infer which parser to use based on the filename.

In this case, you will have to:

- add `.prettierignore` file with content `*.ejs`
- or specify the extname you want to format, e.g. `prettier 'src/**/*.{js,ts}' --write`

**Comment by duailibe** [comment]
In addition to what @ikatyang said, Prettier does not support formatting the EJS syntax, so you can't use prettier on those files.
