### ISSUE TITLE
[website] Update VS Code logo

### ISSUE THREAD

**Issue by kenrick95** [prettier/prettier#3233]
At [prettier.io website](https://prettier.io), VS Code logo shown is in orange color, but VS Code latest logo is back to [blue color](https://code.visualstudio.com/updates/v1_18#_blue-logo-for-stable).

I believe it would be a "good first bug" to update VS Code logo at "prettier/website/static/images/vscode-128px.png" ?

**Comment by ikatyang** [comment]
Yes, PRs welcome :)
