### ISSUE TITLE
Call chains with nested single calls

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#3239]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGEBOBDA5nAZTkwDcBLMOAHSgAJaA6fGAIWzAGsAbMqDgGTLoAIthjYAFAEoa9BjAAWCCWGxRKXYgwDuOAA4SAJmOy0AvAD5awWfTsB6e4wYNbAXyky6jVTDAKVNQ0tXWwDaXMrG287WkUhBmNxc1oAbQBdAG53T1sGADNebC4uAE9A9ThNTB19CQjLa1tY+NQGLghsQ15cFPzi1Dhs7w8pTJAAGhAIPRgyaFRkUGx0ZH6uQamAIxxOOBgCPXYe5BhMAFc4KcMIMDWBq5BeQcwYAAUcXABbbHuNx4AVqgAB4sXYcfYEbBfOCCKBwP6babnGB6FEAJkRjyOmBeyBAW2wW1KHSgkxAekwvBgAHUyIZFMgABwABimlIggxp+lOF0emDgAEdzmQBR88D8sVNBl8yLzLtKepoAIrnCDwKUgcRbOkMhTIdFTM7YMg8KC4ADCEC+kpQUGgCKm50GABUiYskOtBm43EA)

**Input:**
```jsx
storageService
  .getBacklinkListData()
  .then(canceler.wrap(data => {
    // ...
  }))
  .catch(canceler.wrap(() => {
    this.data = [];
  }))
  .finally(canceler.wrap(() => {
    this.loading = false;
  }));
```

**Output:**
```jsx
storageService
  .getBacklinkListData()
  .then(
    canceler.wrap(data => {
      // ...
    })
  )
  .catch(
    canceler.wrap(() => {
      this.data = [];
    })
  )
  .finally(
    canceler.wrap(() => {
      this.loading = false;
    })
  );

```

**Expected behavior:**
Would be nice if the `canceler.wrap` calls didn't get separate lines and looked like in the **Input**. Doesn't the input look more readable?

**Comment by EthanRutherford** [comment]
I'd also like to request that chains like this prefer to chain on the previous line (when lineWidth permits)

i.e.
```js
promise.then((result => {
    // ...
}).catch((error) => {
    // ...
}).finally(() => {
    // ...
});
```

otherwise the style seems to clash with actual try blocks...

```js
try {
    // ...
} catch(error) {
    // ...
} finally {
    // ...
}
```

Absolute least favorite

**Comment by azz** [comment]
This would cause significantly churn, plus I think the current behaviour is more consistent.

**Comment by azz** [comment]
Going to close this as I doubt we'll be making a change this drastic.
