### ISSUE TITLE
Markdown: Heading after list becomes part of last element

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#3247]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABAZQgWzjACwEsoBzAHSgGIatc50C4BDAExIqhABoQIAHGEWgBnZKGYiYyAGbMANiLi8ARgCdmYANb5M-TR2Qw1AV2UhWEMLIVLeJJWpgAFDaRzMbi8wCsRADwAhDW1dZjwAGRI4Lzs+Exh+BIAmWPN9NUdkEA81LUsAdy5efjUSGAB1IlZCZAAOAAYStQglCo1+I1NzNTgARxMiXtdmd08kOW9eJRwiLrNpjnk4AEUTCHg03hhmFSqagmRk7Y0ieQ4AYVwPbKhoGN4TJQAVXbEJ2zgAXy+gA)
```sh
--parser markdown
```

**Input:**
```markdown
* Something
### Some heading
```

**Output:**
```markdown
* Something
  ### Some heading
```

**Expected behavior:**
```markdown
* Something

### Some heading
```

**Comment by ikatyang** [comment]
This seems to be [`remark` mis-parsing](http://astexplorer.net/#/gist/e3eaf84774057db35a17b3065aa3f8a3/69aa50de7bc313fad863946ebe318aa88d288afa), can you [raise an issue there](https://github.com/wooorm/remark/issues)?

**Comment by SimenB** [comment]
https://github.com/wooorm/remark/issues/313
