### ISSUE TITLE
Strict word wrapping rules

### ISSUE THREAD

**Issue by vladik7244** [prettier/prettier#3256]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwAEkoGcZq2BOLNAXjQDMAbCAdwAoAdKNFtAWwEMAHO-Q0gHxo66AJYATJGgCuUUQEdpcAJLi6Acj5Q4AWnUBKADRoAdGa1w0AX31GmrCqMrwATnVFYAygW3KoYSmlxOHF9ezR9Ong2LkoOeAAReI4TCyx9AG4mKxBDEAguGFFoLGRQDhxkcg5KLDg8gCMXDjAAazgYTy4W0SgAc2QYFyU88QgwKpq6vN66lxgABWa+zkna+pAAKywADwAhZraOzw42OAAZXrg16fzpGC57gCYbje6XOeQQBo4GgE9qFBciAuC5ejAAOoSGAAC2QAEYngAGPKgiB1CHNLiDYYbFxwRSifFLDgrDivPJ1NiiHEjEBYXp9ShwACK0gg8ApIBgvyh4lhyCeeSGHCcjIAwhA2KsUFBoNc8tI6gAVX6lJDVdZWKxAA)
```sh
--print-width 120
```

**Input:**
```jsx
{
  const scenes = flow(
    map(scene => ({ id: uniqueId('scene-'), ...scene })),
    filter(isSceneIncluded)
  )(templateData.scenes);
}
```

**Output:**
```jsx
{
  const scenes = flow(map(scene => ({ id: uniqueId("scene-"), ...scene })), filter(isSceneIncluded))(
    templateData.scenes
  );
}

```

**Expected behavior:**
```jsx
{
  const scenes = flow(
    map(scene => ({ id: uniqueId("scene-"), ...scene })),
    filter(isSceneIncluded),
  )(templateData.scenes);
}

```

Is there a way to achieve this? I think it reads better

**Comment by lydell** [comment]
Lower the print width :wink: ((link)[https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwAEkoGcZq2BOLNAXjQDMAbCAdwAoAdKNFtAWwEMAHO-Q0gHxo66AJYATJGgCuUUQEdpcAJLi6Acj5Q4AWnUBKADRoAdGa1w0AX31GmrCqMrwATnVFYAygW3KoYSmlxOHF9ezR9Ong2LkoOeAAReI4TCyx9AG4mKxBDEAguGFFoLGRQDhxkcg5KLDg8gCMXDjAAazgYTy4W0SgAc2QYFyU88QgwKpq6vN66lxgABWa+zkna+pAAKywADwAhZraOzw42OAAZXrg16fzpGC57gCYbje6XOeQQBo4GgE9qFBciAuC5ejAAOoSGAAC2QAEYAAyIvKgiB1CHNLiDYYbFxwRSifFLDgrDivPJ1NiiHEjEBYXp9ShwACK0gg8ApIBgvyh4lhyCeeSGHCcjIAwhA2KsUFBoNc8tI6gAVX6lJDVdZWKxAA])

Other than that, there’s currently no way. But we have several similar cases. #3014 is a suggestion for how this could be solved.

**Comment by ikatyang** [comment]
Looks like an issue about currying, closing in favor of #1420.
