### ISSUE TITLE
Proposal: GitHub App

### ISSUE THREAD

**Issue by olstenlarck** [prettier/prettier#3262]
Heya!

I'm thinking that it would be great if we create a GitHub App directly, which will look and format the commits of PRs and these directly pushed to master too.

It should also respect the config file.

Just wanted to open it for tracking and to notify if someone is interested. I can try soon to get it started.

**Comment by azz** [comment]
Someone built https://stylejs.io a while ago, but I can't vouch for it

**Comment by olstenlarck** [comment]
yea, that sounds good, but seems that it dont understand eslint.

I will experiment with it and try to collaborate if it is open.

**Comment by azz** [comment]
Closing this issue as it's not actionable in this repository.
