### ISSUE TITLE
Odd JSX indentation with an expression that wraps

### ISSUE THREAD

**Issue by dustinsoftware** [prettier/prettier#3271]
I don't think this is a bug, but it is a bit ugly.

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6U+MwhxxAhgGZWYA2mFMm0AzgEICeA0plOgDpWAVwBGAcwBOEYQAdWAugnEwAFgAIA1GRjkY1WgyYsoHHn0EH6jeOgDi0uQqVQVG1DuIBlABIB5AHUAfR8AUQBBABFQgCUggFkASQA5RPiAVXig8IAxHMSAGUTwgBVEv2SvT10YAH51KGE6OmriJHU1TAVJBHQ4SUiu2ToKTh84Cj7JAApVClYABQoe2ABKAF9CVAB6LDwAbkIQABoQCFlmNmRQeZhkKgo6VjhT0UkKMABrOBgvWQ++OJkDBJMIXiB0BAwPdHs9TnxnpIYAt3uIALYUGFPcEAK1YAA92O8vj8vBQ0XACnw4Fi4WdhDBZAyAEy08H-SSI5AgUQUUScOjQE4gWSSPgwAKYdBqZAADgADKdRRBngF3rJgaDwT0AI7CTA9FEUdGYpAPbGnZ5ozCasGWwFKACKwgg8DZp30okl0tUyGZHve1lcAGEIGiMdzHnRhcJniU+axbXB1usgA)
```sh
--trailing-comma all
--use-tabs
```

**Input:**
```jsx
<div>
	{
		affiliationsByKind.subgroups.length +
			affiliationsByKind.affiliatedGroups.length <
		SHOW_HEADER_MINIMUM_AFFILIATIONS
			? null
			: this.renderDisplayHeader(hasParent)}
</div>;

```

**Output:**
```jsx
<div>
	{affiliationsByKind.subgroups.length +
		affiliationsByKind.affiliatedGroups.length <
	SHOW_HEADER_MINIMUM_AFFILIATIONS
		? null
		: this.renderDisplayHeader(hasParent)}
</div>;

```

**Expected behavior:**
It seems like the third line should not left align with the opening curly brace, as it is a bit more difficult to see where the expression ends in JSX. The current indenting behavior seems fine if the expression was used outside of JSX, e.g.

```
const foo =
	(affiliationsByKind.subgroups.length +
		affiliationsByKind.affiliatedGroups.length <
	SHOW_HEADER_MINIMUM_AFFILIATIONS
		? null
		: this.renderDisplayHeader(hasParent)) || bar;
```

**Comment by Marcholio** [comment]
Is this still relevant? If not, it could be closed as there hasn't been any activity for over a year.

**Comment by lydell** [comment]
This is what it looks like today:

**Prettier 1.16.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6U+MwhxxAhgGZWYA2mFMm0AzgEICeA0plOgDpWAVwBGAcwBOEYQAdWAugnEwAFgAIA1GRjkY1WgyYsoHHn0EH6jeOgDi0uQqVQVG1DuIBlABIB5AHUAfR8AUQBBABFQgCUggFkASQA5RPiAVXig8IAxHMSAGUTwgBVEv2SvT10YAH51KGE6OmriJHU1TAVJBHQ4SUiu2ToKTh84Cj7JAApVClYABQoe2ABKAF9CVAB6LDwAbhAAGhAIWWY2ZFBl6QB3JZXWZBAKbAhMdGOQUUkKMABrOAwLyyP58cTIGCSYRwE6qGAAWzoAVUmHgrFBYDgXgQrDRODRnGeYFYTxOfFY-RgC1+4gRFGQVAodEpJwAVqwAB7sX4AoFeCgIuAFPhwRnM1kgDmcrzgpQARWEEHg4pZsJAoMklMkz1EFFEcDoX1kkj4MACHzUyAAHAAGE4miCUgK-WTPE1wbXYMUnHoAR2EmB6NIodIZSCZapOlIRmEh0PVeNcCqVKojEvV+lEFvQVqQACYTlCKNZXABhCAI+nPKDQH0gYSUkr6p5IKEw9brIA)
```sh
--parser babel
--use-tabs
```

**Input:**
```jsx
<div>
	{
		affiliationsByKind.subgroups.length +
			affiliationsByKind.affiliatedGroups.length <
		SHOW_HEADER_MINIMUM_AFFILIATIONS
			? null
			: this.renderDisplayHeader(hasParent)}
</div>;
```

**Output:**
```jsx
<div>
	{affiliationsByKind.subgroups.length +
		affiliationsByKind.affiliatedGroups.length <
	SHOW_HEADER_MINIMUM_AFFILIATIONS
		? null
		: this.renderDisplayHeader(hasParent)}
</div>;

```

Not sure if that’s good enough.

**Comment by dustinsoftware** [comment]
It isn’t a show stopping issue or anything :) thanks for circling back
