### ISSUE TITLE
[Question] Nested .prettierignore not respected

### ISSUE THREAD

**Issue by ismail-syed** [prettier/prettier#3274]
I have an example repo [here](https://github.com/ismail-syed/prettier-ignore-nested-paths-issue) that attempts to use a nested `.prettierignore` file but prettier does not seem to respect nested ignore files. 

Tools such as eslint respect nested `.eslintignore`s. Is there a reason why the same isn't provided by default with prettier?

**Comment by ismail-syed** [comment]
Another semi-related comment. 
ESLint falls back to a `.gitignore` if `.eslintignore` is not found. Can similar behavior for this be added to prettier by default?

**Comment by lydell** [comment]
I _think_ neither ESLint nor cosmiconfig support nested ignore files.

**Comment by suchipi** [comment]
ESLint does, but my atom plugin for ESLint does not, so I don't use the feature 😅

**Comment by duailibe** [comment]
I don't think ESLint has this feature: https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories

> When ESLint is run, it looks in the current working directory to find an `.eslintignore` file before determining which files to lint

> Only one `.eslintignore` file can be used at a time, so `.eslintignore` files other than the one in the current working directory will not be used.

**Comment by azz** [comment]
That's my understanding too. Only config files are searched for.

**Comment by chrisblossom** [comment]
@azz / @duailibe - Eslint does support nested ``.estlintignore`` files. This is a welcome feature, especially when working with lerna repos. 

I made a very basic repo to demonstrate this behavior: [chrisblossom/prettier-issue-3274](https://github.com/chrisblossom/prettier-issue-3274)
