### ISSUE TITLE
Feature: Smarty template support

### ISSUE THREAD

**Issue by caugner** [prettier/prettier#3275]
I would be interested in formatting [Smarty templates](https://www.smarty.net/docs/en/what.is.smarty.tpl) (of a legacy system) using prettier. Smarty is basically html with the addition of square bracket block tags, such as `{$title}`, `{if}...{else}...{/if}` and `{literal}...{/literal}`.

Would this be feasible either by creating a plugin or by implementing this in prettier directly? I would be glad to contribute this feature myself.

**Comment by TrySound** [comment]
@caugner Prettier does not handle html. And smarty is quite legacy, at least in modern stack. Long term support does not make sense.

**Comment by caugner** [comment]
@TrySound Sorry, not sure how I came to think prettier would support html. My feature request obviously doesn't make sense then.
