### ISSUE TITLE
extra comma in function

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#3276]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAZgVymAFAHSlVQG1DjUByAGwEso5UBGAWjfY867coBpziNeowBM3cd0oCAugDoAVhHq5KlAJSE1IXiAgAHGLWgBnZKACGxmMnTnqxuDoBGAJ3NgA1nBgBlPe-oAc2QYF0xHEAATCDAbOwcdegcXGAAFN0CAW3M4+wj5YwAPACE3T28fc0y4ABlhXITdTBg9ZpEGiP8XZOQQJ3MnAE9qaG0QPRd6GAB1WkiYAAtkAA4ABh0JiAdptz0OnRc4AEdMWkP08yycpFs8nQdM2hCwiOMg6jgARUwIeH2QGADWbzJZIEQ6ULmWh0KCBADCEEy2V6dmoY0wDgAKgNTDd4nAAL4EoA)
```sh
--no-prose-wrap
--trailing-comma all
```

**Input:**
```jsx
 func(
  [
   'line 1-----------------------',
   'line 2----------------------'
  ].join('')
)
```

**Output:**
```jsx
func(
  ["line 1-----------------------", "line 2----------------------"].join(""),
);

```

**Expected behavior:**
```jsx
func(
  ["line 1-----------------------", "line 2----------------------"].join("")
);

```

**Comment by LeBenLeBen** [comment]
I think this is intended, see https://github.com/prettier/prettier/issues/2788

**Comment by fisker** [comment]
thanks
