### ISSUE TITLE
IntelliJ IDEA Plugin

### ISSUE THREAD

**Issue by xeoneux** [prettier/prettier#3278]
Will there be an official plugin for Prettier integration into JetBrains IDEs?

**Comment by suchipi** [comment]
Maybe someday, but I don't know of any plans to make one at this time.

In the meantime, see https://prettier.io/docs/en/webstorm.html

**Comment by suchipi** [comment]
I'm going to close this issue since editor integrations have come from the community, so creating a plugin is not something that we plan on solving in this repo. Also, because the WebStorm configuration mentioned in the docs should work in other JetBrains IDEs.

**Comment by DamianFekete** [comment]
@xeoneux, see http://plugins.jetbrains.com/plugin/10456-prettier . I don't think the integration is that nice, but it's a start. You'll need to download the zip file and install it manually as I don't see it in the official repository.

**Comment by SimenB** [comment]
If you're using the EAP, it's available to be downloaded frmo the plugins part of settings
