### ISSUE TITLE
Add a flag to skip formatting the code inside the Markdown files

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3284]
If you ask me to personally, TBH I don't really need this option.. but I can see that in some cases you might don't want to reformat your code inside the documentation for your own reasons.. One example can be found here and I'm not sure how to fix it :)

https://github.com/electron/electron/pull/11143

WDYT?

**Comment by lydell** [comment]
I think it is better to close this and only add an option when somebody that wants it asks for it.

**Comment by ikatyang** [comment]
This flag should be useful for someone only cares about the markdown formatting and they have their own js coding style that is conflict with Prettier.

The implementation should be pretty easy, just adding a condition to not enter the subtree-parser, but I'm not sure what should we name it, `--no-multi-parser`?

https://github.com/prettier/prettier/blob/4b070c3a933204befb13ece2f1c3fe6e5c127ad5/src/multiparser.js#L31-L42

**Comment by lipis** [comment]
Maybe something with code fences `no-style-code`? Yes I think there is a case for the need of this option.

**Comment by azz** [comment]
What's wrong with `<! - - prettier-ignore - ->`? Doesn't seem like we need an option for this...

**Comment by lipis** [comment]
if you have a big codebase with documentation and lots of code for this could be annoying..

**Comment by suchipi** [comment]
@lipis For that electron case, eslint could add the spaces in function declarations after a prettier run... but I dunno if eslint can format code within markdown code blocks.

**Comment by lipis** [comment]
eslint is parsing .js files and not .md so I'm not sure if we can do anything about it.

**Comment by azz** [comment]
@suchipi 
>I dunno if eslint can format code within markdown code blocks.

https://github.com/eslint/eslint-plugin-markdown

**Comment by lipis** [comment]
Electron closed that issue https://github.com/electron/electron/pull/11156 so I will close this one as well and in case somebody is going to need that flag we can rethink of it.. until then 🍻 🍺
