### ISSUE TITLE
unnecessary parentheses at typescript function type

### ISSUE THREAD

**Issue by dhcmrlchtdj** [prettier/prettier#3289]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAZgVyjAEZsBebACioA8lsp8BbAIzgCcBKcgPmwGcY7AJZQA5tmycA3AB1YmHASIAmcrXqNWHbmT6CR46SAA0ICBhjDo-ZKACGg5LnsAbfnDMt29sAGs4GABlDF9RMWQhfE8QABMIMGc3DzNRD3YYAAUfMSZ7JPcYgCt+GgAhH39AoPsmOAAZUTgClPN8GAx2lRaY0PZ05FRFfjARS1MQDEMYAHVhWJgAC2QADgAGMymIDxmfDEj2aLN2OABHfGET7Ptc-KQXQrMPJmEDo5B+cNc4AEV8CHgPTMMHsLDmC2WSBUwJ8wlc4QAwhAmHlBlBoM0zPgPAAVUG2e7JOAAX2JQA)
```sh
--parser typescript
```

**Input:**
```tsx
type func1 = ( (x: number) => string  );
type func2 = (x: number) => string;
```

**Output:**
```tsx
type func1 = ((x: number) => string);
type func2 = (x: number) => string;

```

**Expected behavior:**
Parentheses at func1 should be omitted.

**Comment by Kacppian** [comment]
Is this open?

**Comment by dhcmrlchtdj** [comment]
I have a PR for this bug. https://github.com/prettier/prettier/pull/3291

**Comment by j-f1** [comment]
@dhcmrlchtdj Why did you close the issue and PR?
