### ISSUE TITLE
Maximum call stack exceed in playground

### ISSUE THREAD

**Issue by LestaD** [prettier/prettier#3300]
![image](https://user-images.githubusercontent.com/5620073/33066406-4381dbea-cebc-11e7-9e10-360de859e858.png)

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAzAhgJ0wF5MBnGAT3QBMA6agSwDcADAMQgkwCECWBuADpQQAGhAQADjAbRSyULnLI8qUnHEAjfLjABrDAGVJuhlADmyGPgCuGkNQhgVuNfbPr8MAAo7zAW1wXN3EAK1IAD24dfSNcfzgAGTM4YPVxCBsYSSyAJjT7E3xPZBBNXE0qaDEQSXwzGAB1BmoYAAtkAA4ABnE6iHVGnUkrW3t8OABHGwYJ31wAoKRVdJB1fwZRu3FSM3N0AEUbCHgC8RgK5taOpFzznQZUPYBhCH9A0qhoVPEbdQAVCryZaudQAXzBQA

**Comment by suchipi** [comment]
I saw this intermittently (as I typed) this week, too, when testing styled.div css formatting. Thanks for opening the issue.

**Comment by duailibe** [comment]
FWIW this error is not exclusive to the playground. But with the cli the error is caught and it's just no-op. 

I don't know the error happens in the first place though.

**Comment by duailibe** [comment]
Fixed now. But I could only check in a new anonymous tab, probably some cache thing I didn't manage to get it to update

**Comment by ikatyang** [comment]
You'll need to hard reload to get the fresh content.

![image](https://user-images.githubusercontent.com/8341033/33130630-f8f5d216-cfce-11e7-9f5a-375482744be7.png)
