### ISSUE TITLE
Is the lack of HTML support intentional? (issues with self closing tags)

### ISSUE THREAD

**Issue by Rialgar** [prettier/prettier#3301]
I like prettier a lot. However, it is bugging me that it does not support standard conform HTML5.

It looks like it does on first glance, since it will pick up and reformat html files, but as far as I can see, it is using jsx rules which produce a slightly problematic result. In particular: it uses self-closing tags for empty tags. This is invalid in html5 except for void elements or foreign elements (that being SVG and MathML) (see https://www.w3.org/TR/html5/syntax.html#start-tags). Due to the error correction of browsers, this means that e.g. `<div />` is interpreted as a starting tag only, NOT being equal to `<div></div>`. (see this fiddle https://jsfiddle.net/aehpgm4y/ )

Is this lack of support intentional? Is it reasonable to expect it to arrive someday / try to contribute it myself?

(note: I realize that using xhtml would solve this issue for me. But this is not an option due to circumstances not important to this question.)

Thanks for your time.

**Comment by Rialgar** [comment]
After browsing the code

https://github.com/prettier/prettier/blob/master/src/printer-htmlparser2.js

looks like it contains what I miss, but I can't find any documentation on how to enable it.

**Comment by Rialgar** [comment]
After reading through the printer-htmlparser2.js, I think this is actually a bug in the printer. It actively prints self closing tags for everything BUT void tags, fo which the / at the end is ommited. I may submit a PR later if nobody tells me not to.

**Comment by azz** [comment]
The HTML implementation in prettier is not complete (undocumented, unsupported). #1882 tracks it. However, feel  free to open a pr!

**Comment by lydell** [comment]
@Rialgar Prettier used to have this bug where the experimental HTML support could accidentally be used in some cases. Prettier 1.8 should no longer format HTML files.

**Comment by Rialgar** [comment]
Cool, thanks for the answers. Will close this as my questions have been answered. I will add my 5 cents to the discussion about self-closing tags
