### ISSUE TITLE
Markdown: one sentence per line

### ISSUE THREAD

**Issue by simonrelet** [prettier/prettier#3302]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiVACAQgVwJYA2AJnlAOYYCGURGCAZhAE5ikWUYDOMAngXBjL4icADpRxWHhnqUmGGAAsBAIzxkycbhiZxKnaDOZUiEAA4w2GAAq6YluPLycFELjHNUCBBcozQAWjIIKxEVSngXCAA3R3c+LQA6DABJGAxnQQRHSm9pSjAwOAs4WiUIjEVKaKsOSABbesNuBMFhAUzo3JxKFX4jeQ4zJggAKzgwdOoyvXqMFRx0zXsrJUcOlw5YpmkzSlJ6HB9pjBwoXQB3ORJyDGGIIs5OZOs4c37ljG3pOCbLaFyVBGZ1oeyYljARzkGCuPCi9BhTDwllukBEVBoGCgEBUECI0gIeAA1louGYEDcKJZ6gILkiUexMboingarcoMjniAADQgcz-KCcZCgfQwZCyAicOC8lRMAokmAAZT2rHIyBgTBw0pApjA4tyUt5pCl4NslDI9Uo+sl2tGnAAHlg5WAFYrKDSADKkODWw18xZmRYAJl92rBJuQIEtTCJpguUB5IGGpBgAHU8EQlMgABwABl59ylqblZnVmu1ugAjvhdGaLVakBK-VL6ngy1reZw2PwAIo4CDwUO8mC9dOZxTIIPDuWENgAYQgjQbIGxUB9vJwUoAKr0hY2DXAAL6HoA)
```sh
# Options (if any):
--parser markdown
```

**Input:**
```markdown
## Building and enforcing a style guide

By far the biggest reason for adopting Prettier is to stop all the on-going debates over styles. It is generally accepted that having a common style guide is valuable for a project and team but getting there is a very painful and unrewarding process. People get very emotional around particular ways of writing code and nobody likes spending time writing and receiving nits.
```

**Output:**
```markdown
## Building and enforcing a style guide

By far the biggest reason for adopting Prettier is to stop all the on-going
debates over styles. It is generally accepted that having a common style guide
is valuable for a project and team but getting there is a very painful and
unrewarding process. People get very emotional around particular ways of writing
code and nobody likes spending time writing and receiving nits.
```

**Expected behavior:**

I would _love_ an option to have the markdown formatting follow the _one sentence per line_ technique. There's are good explanation in [Asciidoctor's recommended practices](http://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line).

```markdown
## Building and enforcing a style guide

By far the biggest reason for adopting Prettier is to stop all the on-going debates over styles.
It is generally accepted that having a common style guide is valuable for a project and team but getting there is a very painful and unrewarding process.
People get very emotional around particular ways of writing code and nobody likes spending time writing and receiving nits.
```

**Comment by ikatyang** [comment]
Ref: previous discussion https://github.com/prettier/prettier/issues/3183#issuecomment-342644669 https://github.com/prettier/prettier/pull/3199#issuecomment-342664082

**Comment by suchipi** [comment]
I wrote a lot of markdown over the weekend and found myself wanting this option, too. But I do have concerns about detecting sentences properly.

**Comment by tibdex** [comment]
Hi all and thanks for this amazing tool,

I think the _one sentence per line_ technique makes a lot of sense. For me, the _It prevents reflows_ point of Asciidoctor is really important.
Indeed, currently, if I change a sentence in a paragraph by removing/adding characters it will very likely lead to a diff impacting all the remaining lines/sentences of this paragraph. It obviously makes the diff harder to read as it's not immediate to pinpoint the actual small change.
This problem would not happen with the _one sentence per line_ technique.

https://github.com/prettier/prettier/pull/3199 added the `--no-prose-wrap` option but it still prevent having one sentence per line:

#### Input (manually writing one sentence per line):

```
By far the biggest reason for adopting Prettier is to stop all the on-going debates over styles.
It is generally accepted that having a common style guide is valuable for a project and team but getting there is a very painful and unrewarding process.
People get very emotional around particular ways of writing code and nobody likes spending time writing and receiving nits.
```

#### Default output: 

```
By far the biggest reason for adopting Prettier is to stop all the on-going
debates over styles. It is generally accepted that having a common style guide
is valuable for a project and team but getting there is a very painful and
unrewarding process. People get very emotional around particular ways of writing
code and nobody likes spending time writing and receiving nits.
```

#### Output with `--no-prose-wrap`: 

```
By far the biggest reason for adopting Prettier is to stop all the on-going debates over styles. It is generally accepted that having a common style guide is valuable for a project and team but getting there is a very painful and unrewarding process. People get very emotional around particular ways of writing code and nobody likes spending time writing and receiving nits.
```

#### Expected behavior:

The output is the same as the input: _Prettier_ didn't put all the sentences of the paragraph into a single line. 

Should we change the `--no-prose-wrap` so that it doesn't actually wrap prose in any way?
Or should we change it to an option with three values (not sure about the naming):

```javascript
proseWrap:
  'usePrintWidth' /* current default */
  | 'oneLinePerParagraph' /* same as --no-prose-wrap */
  | 'off' /* let the sentences where they are */
```

What do you think?

**Comment by lydell** [comment]
@tibdex The pros and cons of having all on one line vs. wrapping at 80 chars vs. wrapping after each sentences are known. And if sentence-wrapping _is_ added, there will be three choices. The only missing pieces are:

- How much demand is it for this feature? This will take some time to find out. So far this issue only has 1 :+1:
- How should a sentence be defined?

**Comment by tibdex** [comment]
> How should a sentence be defined?

That's the hard part of course. _Prettier_ uses [remark-parse](https://github.com/wooorm/remark/tree/master/packages/remark-parse) which is a [unified](https://github.com/unifiedjs/unified) parser. So the integration with [retext](https://github.com/wooorm/retext) plugins should be doable. In particular, there is [retext-english](https://github.com/wooorm/retext/tree/master/packages/retext-english) wrapping [parse-english](https://github.com/wooorm/parse-english) which is able to produce an AST with *SentenceNode*. For other latin-based languages there is [parse-latin](https://github.com/wooorm/parse-latin) but it's not ideal according to https://github.com/wooorm/remark/issues/25.

So I guess adding robust support for _one sentence per line_ auto-formatting in any language would require a huge amount of work and would maybe still lead to mediocre results.

Do we still want to try it?
Maybe just for English or maybe with a disclaimer saying that it only works well with latin-based languages?
Or do you think it's [feature creep](https://github.com/prettier/prettier/pull/3199#issuecomment-342664082) and that NLP shouldn't be baked inside _Prettier_?
If it's not the role of Prettier to perform _one sentence per line_ auto-formatting, then shouldn't we provide an option to completely disable prose wrapping like I suggested in my previous comment? It would allow people to use a dedicated tool for _one sentence per line_ formatting without loosing all the other Markdown-formatting goodies provided by _Prettier_!

**Comment by lydell** [comment]
Nice, research @tibdex! 👍 

Also, thanks for pointing out your alternative proposal: Preserving the original wrapping of text. I missed that.

**Comment by simonrelet** [comment]
Preserving the original wrapping of the text is a good compromise.

**Comment by jbe456** [comment]
> So I guess adding robust support for one sentence per line auto-formatting in any language would require a huge amount of work and would maybe still lead to mediocre results.

Why don't we just consider a point as a sentence separator? and we would then have in the Prettier configuration a list of customizable exceptions such as `i.e.`...

It seems like it would make the development much cheaper while still being flexible enough to fulfill most of the "one sentence per line" use case.

**Comment by suchipi** [comment]
Since prettier is an opinionated formatter, I don't think such an option will be making it in anytime soon. I also think there might be less friction in doing the line breaks by hand than to try to maintain a list of exceptions, which feels it would grow larger and larger as time went on. However, with `--prose-wrap preserve`, you could prettier in conjunction with an additional tool that wraps sentences if you wanted to.

**Comment by azu** [comment]
> How should a sentence be defined?

FYI: https://github.com/diasks2/pragmatic_segmenter
