### ISSUE TITLE
Braces around string literal in JSX props can be removed

### ISSUE THREAD

**Issue by frontsideair** [prettier/prettier#3303]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeA4gJznGACKAQwFs4BeYAcgHUJMAbAE0oF88B6APgB0oQAaEBAAOMAJbQAzslCFJMZADNC9SXEEAjTITABrXAGVhOsVADmyGJgCu6kIwhglKtYNNrMMAArazxQs6qdgBWkgAeAELaeoYkcAAypnCBrkLWMMLpAEwpdsaYHsggGoQaAJ700AIgwpimMNRijDAAFsgAHAAMgrUQatTawpY2dtgAjtZi2D6EfgFIykGCasRiw7bLpmb0cACK1hDwuYIwpY3NbUhZJ9pi9FsAwhDE-kVQ0MmC1moAKqXSCxccBYLCAA)

**Input:**
```jsx
<Greet name={'World'} />
```

**Output:**
```jsx
<Greet name={"World"} />
```

**Expected behavior:**
```jsx
<Greet name="World" />
```

I think braces around string literals in JSX props can be removed safely and would result in better looking output. If there are no objections to this, I'd like to help if you can point me in the right direction. I'm a fan of the project, I'd be happy to be of any help. Thanks!

**Comment by suchipi** [comment]
We generally try to avoid changing the AST in prettier because it could change the meaning of the code. However, we change the AST for JSX sometimes (to collapse whitespace, etc). So I'm open to this idea, but I'm worried that someone may have written a babel plugin or something that treats these differently for some reason.

Maybe this would be better handled by eslint? [`react/jsx-curly-brace-presence`](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-curly-brace-presence.md) is automatically fixable.

**Comment by lydell** [comment]
Previous discussion: #2211

Yes, [`react/jsx-curly-brace-presence`](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-curly-brace-presence.md) is the way to go.

Also note that automatically converting between the two is super complicated:

- https://github.com/yannickcr/eslint-plugin-react/issues/1449
- https://github.com/yannickcr/eslint-plugin-react/issues/1479
- https://github.com/yannickcr/eslint-plugin-react/pull/1458/

Having helped out with that ESLint rule, I know how complicated it is, so I don't think we should take a departure from our "don't change the AST" rule here.

**Comment by frontsideair** [comment]
I understand the concern, since a comprehensive solution would be way too complicated. But a simple one that only cares about single and double quoted strings (ignoring template literals) and work only on props (ignoring children) is supposed to be bulletproof if I'm not missing something huge.

I don't intent to push the issue further, as there's already a solution around. But when it's limited to single- and double-quoted strings, surrounding braces (JSXExpressionContainer) are like parens Prettier removes when they are unnecessary. I presume this is the only case this happens, as any other type of value needs to be wrapped in braces.

**Comment by lydell** [comment]
@frontsideair Single and double quoted strings are just as complicated as template literals and children, unfortunately.

**Comment by suchipi** [comment]
Thanks for your insight @lydell
