### ISSUE TITLE
Styled-components integration lowercases SVG tag names in selectors

### ISSUE THREAD

**Issue by seancurtis** [prettier/prettier#3304]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAxCFMC8mGAngDZwAmAdGgA4CGUABgDpSaZkCWUcDAJwDiAhpW4Iswdp04YIdALSQyEAUky8AFnAHcYAbhmYAvu2YGQAGhAKY3dMlAMMyAGYMyaODYBGosABrOBgAZUYwXgBzZBgBAFcfEEoIMHdPbxtebwEYAAVRKIBbBnSvJIArNAAPACEA4LCGIrgAGV44MszbeJg6XoAmLqTGARzkEF8GX3JoaxA6PVgAdW5KGC1kAA4ABhtFiG9l0TpYhKSBOABHeO5LgoZi0qQPcptvIu4zxPfoigBFeIQeDDGwwaardabJADMGibg8KBRADCECKJQmUGgnRs8W8ABVpmhhiYTEA)

**Input:**
```jsx
const Foo = styled.span`
  linearGradient {
    stop-color: inherit;
  }
`;
```

**Output:**
```jsx
const Foo = styled.span`
  lineargradient {
    stop-color: inherit;
  }
`;

```

**Expected behavior:**
Expected the selector of "linearGradient" to not be changed to "lineargradient".

The SVG element is &lt;linearGradient&gt;, but prettier rewrites the selector as "lineargradient" which no longer matches in Firefox or Safari.

**Comment by suchipi** [comment]
Priority high since the selector doesn't target the correct element anymore once it's been lowercased.

**Comment by seancurtis** [comment]
We can get around this temporarily by either adding these files to our `.prettierignore` file, or by doing:

```
const styld = styled;
const Span = styld.span`...`;
```

Not a great workaround, but it'll work until this gets fixed.

Very much a rare occurrence, as not many people would ever be targeting a `<linearGradient>` node in a styled-component selector. We've got some SVG icons that use gradients, which is why we ran into this.

**Comment by duailibe** [comment]
We format the contents of the styled components as CSS. And one the formatting we do is normalization: lowercase tags, properties and values; numbers; quotes; etc.

We didn't take into account case sensitive tags..

**Comment by lydell** [comment]
Sorry, I didn't read the CSS specification carefully enough when I implemented the lowercasing stuff :(

https://www.w3.org/TR/css3-selectors/#casesens

> All Selectors syntax is case-insensitive within the ASCII range (i.e. [a-z] and [A-Z] are equivalent), except for parts that are not under the control of Selectors. The case sensitivity of document language element names, attribute names, and attribute values in selectors depends on the document language. For example, in HTML, element names are case-insensitive, but in XML, they are case-sensitive.

SVG is XML, not HTML, so that explains why it's case sensitive.

We have to remove all lowercasing of element names and attribute names, because we cannot know if a piece of CSS is styling HTML or XML.

<details>
<summary>SVG CSS case sensitivity test case</summary>

If things _were_ case <strong>in</strong>strong>sensitive, you'd see green stuff in this test case. But in the real, case sensitive, world, things are red.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>SVG case</title>
    <style>
      svg {
        border: solid;
      }

      linearGradient stop {
        STOP-COLOR: red;
      }

      lineargradient stop {
        STOP-COLOR: green;
      }

      svg#two[viewBox] {
        background-color: red;
      }

      svg#two[viewbox] {
        background-color: green;
      }
    </style>
  </head>
  <body>
    <svg viewBox="0 0 100 100" height="100">
      <defs>
        <linearGradient
          x1="0"
          x2="0"
          y1="0"
          y2="1"
          id="gradient"
        >
          <stop offset="0%" />
          <stop offset="100%" />
        </linearGradient>
      </defs>
      <rect x="0" y="0" width="50" height="50" fill="url(#gradient)" />
    </svg>

    <svg id="two" viewBox="0 0 100 100" height="100">
      <rect x="0" y="0" width="50" height="50" />
    </svg>
  </body>
</html>
```

</details>

**Comment by suchipi** [comment]
I was going to recommend keeping a whitelist of HTML tag names to lowercase and keeping the case of everything else, but unfortunately, you could create an XML document that uses the same tag names as HTML does...
