### ISSUE TITLE
Consider using Netlify for the website

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#3306]
I don't have much experience with it but I'm aware of a few upsides considering other OSS projects that use (e.g. babel):

- no need to commit artifacts: we have seen several people send PRs that change code in `website/static/lib`. It runs the build step on the server and deploys, automatically on specified hooks (e.g. every commit to master)

- preview PRs: this is the actual a game changer for me. This would allow us to test changes made in PRs in the playground so easily. Babel has this and looks really nice.

There might be other upsides, but these looks pretty relevant to me.

**Comment by azz** [comment]
Yep. I've used it for [styled-css-grid](https://github.com/azz/styled-css-grid), it's great. Docusaurus would need to support it though.

Cc. @joelmarcey

**Comment by duailibe** [comment]
@azz doesn't it just generate static pages? Since it works on GitHub pages, it should work on Netlify, right?

**Comment by duailibe** [comment]
I managed to get a working version of this on my fork, see the [fork's playground](https://deploy-preview-1--elegant-wing-256d9d.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIAOAThPgIwC8w2AhgDYC+BxZlNDTJFVdjRnrPXAHoAfAG4QAGhAkYmaAGdkoagpjIAZnQVxpAI0LUwAazgwAyviOYoAc2QxCAV10h0EMJu2ubOwjAAFQ1sAW2ovWh1pACsFAA8AIUMTM3NqELgAGRs4CKiZJxh8QoAmPNcrQj9kED1qPQBPWmgpECIbGAB1THQYAAtkAA4ABmk+HU7DfAdnV0I4AEcnTHmg6lDwpC1I1x0QzBmXaQUbW1o4AEUnCHhy6Rh67t6BpBL7w0xaU4BhCBCwmpQaC5aROHQAFXqSi23no9CAA)

**Comment by suchipi** [comment]
I'm all for it; PR previews would be rad.

**Comment by JoelMarcey** [comment]
@azz I haven't used Netlifly much - I know [Yarn](https://yarnpkg.com) uses it for its [site](https://github.com/yarnpkg/website). But as I understand it, you would set it up by pointing Netlifly to the Prettier repo, tell it how to build the site, and off it goes. Docusaurus supports it insofar that you can use it (`yarn build`) to build the site and deploy the build files to any host you would like, Netlifly being one of them.

We could add a guide in the Docusaurus docs on how to deploy with Netlifly -- that just wasn't our primary use case to start (GitHub Pages, as you know, is). But, yeah, we could add guides or pointers on how to deploy to Netlifly too. If Prettier does move to it, then maybe it could be our use case to make sure it works ok with Docusaurus and we can create the guide based on it.

**Comment by azz** [comment]
https://prettier.netlify.com/

@vjeux Just need to point the DNS for prettier.io to Netlify:
https://www.netlify.com/docs/custom-domains/#dns-configuration

**Comment by vjeux** [comment]
cc @JoelMarcey

**Comment by suchipi** [comment]
FYI, deploy preview failed in https://github.com/prettier/prettier/pull/3324. Is there something more that needs to be done?

**Comment by duailibe** [comment]
I can't see what failed :(

"Page not found"

**Comment by suchipi** [comment]
Same here...

**Comment by duailibe** [comment]
Well it worked now!

**Comment by JoelMarcey** [comment]
Hi all. I can work to make the DNS changes for the domain. Just want to verify that you want the changes to happen asap or is there more testing that needs to be done?

**Comment by azz** [comment]
@JoelMarcey Main build and PR builds are looking good. Feel free to make the switch. Thanks!

**Comment by JoelMarcey** [comment]
OK. DNS changes have been made.

A                prettier.io      points to 104.198.14.52
CNAME      www              is an alias of prettier.netlify.com

Might take a bit to propagate.

**Comment by JoelMarcey** [comment]
@azz Yeah, other than not having propagated yet, I am not quite sure what is going on.

DNS before was:

```
A        prettier.io     192.30.252.153
A        prettier.io     192.30.252.154
CNAME    www             prepack.io
``` 

DNS now is:

```
A        prettier.io     104.198.14.52
CNAME    www             prettier.netlify.com
```

**Comment by JoelMarcey** [comment]
Technically we are supposed to allow 24 hours for DNS changes. So let's wait another 10 hours or so to see if something positive happens. If not, then we can do more investigation.

I assume everything is set on the Netlify side with respect to assigning the domain there, etc.

**Comment by azz** [comment]
> I assume everything is set on the Netlify side with respect to assigning the domain there, etc.

Yeah it is... And still nothing. Never seen DNS take anywhere near this long to propagate before.

**Comment by JoelMarcey** [comment]
@azz Me neither. I assume something must be wrong on the provider where I set the DNS info. I will have a look at this in the morning U.S. Pacific time to see what might be happening.

**Comment by azz** [comment]
Ok now I'm super confused. I noticed that DocSearch wasn't working on `prettier.io` or `prettier.netlify.com`. I added the environment variable for the Algolia search to Netlify, did a rebuild, and now DocSearch works on both. Yet:

1. Netlify still thinks DNS is a no-go.
2. ```bash
   $ curl https://prettier.io -v 2>&1| grep server:
   < server: cloudflare-nginx

   $ curl https://prettier.netlify.com -v 2>&1| grep server:
   < server: Netlify
   ```

**Comment by azz** [comment]
Everything is working, but I'm not sure how or why 🤣

**Comment by JoelMarcey** [comment]
:)

So, I just made one more change on the DNS side to see if we can really get all traffic to route through Netlify instead of Cloudflare.

**Comment by JoelMarcey** [comment]
Ok, the change I made seems to have done something, like point to the right DNS IP address, but now the SSL/TLS of https://prettier.io is broken. Is there an SSL certificate on the Netlify side?

```
 $ curl https://prettier.io -v
* Rebuilt URL to: https://prettier.io/
*   Trying 104.198.14.52...
* TCP_NODELAY set
* Connected to prettier.io (104.198.14.52) port 443 (#0)
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

So I am going to go back to the old setup until that is resolved.

**Comment by azz** [comment]
Switch it back on and I'll click the button.

![image](https://user-images.githubusercontent.com/1297597/33532078-368b0a8c-d8ea-11e7-93f4-20df121354da.png)

**Comment by JoelMarcey** [comment]
Done!

**Comment by azz** [comment]
We're live!

![image](https://user-images.githubusercontent.com/1297597/33532115-b62dfd30-d8ea-11e7-8388-29c412c45e2b.png)

**Comment by JoelMarcey** [comment]
Yay! I figured out what I missed when I made the DNS change. Now I know for next time.

**Comment by JoelMarcey** [comment]
Just curious -- does Netlify have a way to automatically redirect http://prettier.io to https://prettier.io?

**Comment by azz** [comment]
Just turned that on :D
