### ISSUE TITLE
Trailing comma added after rest parameters 

### ISSUE THREAD

**Issue by tmaciej** [prettier/prettier#3311]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEwA6VOYA20A5gNJwCeAyhACoAWAlmgOpOGEDiEA8lAFkAroRhMADoTgAZJlDhoANHgLEo5KrUYt2nHv2GiJU2fLQAmZfiKkKNeszYdufQSLGSZchQGYrBADoggCcFGDwAX0wAXkw0CABbOBhmdQBuEEUQCHExdGRQAEMMZAAzQsI0OCyAI2DCsABrZOpxBrkSZBhgoWqQABMIMDKKqqy5KuCYAAV6kgTCkcq+gCs0AA8AIXqmlsKk0zglseyhGHEz82O+tuDJ5BAYSnEFMGCJGEyQcXfYdn6UsgABwABiyPwgVVY9XEXR6fVCAEchExQrNCvNFkhyssslUEkw4b08R0pABFIQQeDXLIwQo1f6ApCWR71DgdADCiQWDwUAFYvkIqnR6WhrhEIkA)
```sh
--parser typescript
--trailing-comma es5
```

**Input:**
```tsx
const {
  longKeySoThisWillGoOnMultipleLines,
  longKeySoThisWillGoOnMultipleLines2,
  longKeySoThisWillGoOnMultipleLines3,
  ...rest
} = something;
```

**Output:**
```tsx
const {
  longKeySoThisWillGoOnMultipleLines,
  longKeySoThisWillGoOnMultipleLines2,
  longKeySoThisWillGoOnMultipleLines3,
  ...rest,
} = something;

```

**Expected behavior:** Trailing comma shouldn't be added after rest parameters. This problem only happens for Typescript files (parser typescript), which breaks builds if someone for example is using Typescript together with Babel 7

**Comment by ikatyang** [comment]
[TypeScript allowed trailing comma being there](http://www.typescriptlang.org/play/index.html#src=const%20%7B%0D%0A%20%20longKeySoThisWillGoOnMultipleLines%2C%0D%0A%20%20longKeySoThisWillGoOnMultipleLines2%2C%0D%0A%20%20longKeySoThisWillGoOnMultipleLines3%2C%0D%0A%20%20...rest%2C%0D%0A%7D%20%3D%20%7B%7D%20as%20any%3B), so it shouldn't be a problem. 

What did you mean `breaks builds`? Are you using `--parser typescript` for js files?

**Comment by tmaciej** [comment]
@ikatyang No, I let `prettier` decide which parser to use but parsing `.ts` files with `prettier` results in trailing comma (as described above) which in turn when used with `webpack -> ts-loader -> babel-loader` (a pretty standard approach imo) results in errors thrown when using Babel 7 as its prohibits trailing commas after rest parameters. The only way around it is to either go with `--trailingComma none` (which breaks our linting) or pollute code with `// prettier-ignore` comments everywhere we use rest parameters.

I think that `prettier` should remove / add those trailing commas consistently no matter which parser is used (the trailing comma is for example properly removed / not added when using `--parser babylon` in js files).

**Comment by duailibe** [comment]
This looks like a bug to me, not because it being valid or not, but because it's inconsistent with arrays and function arguments (see [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtAOlTTAG2gHMBpOATwGUIAVACwEs0B1ZoogcQgHkoAWQCuRGMwAOROABlmUOGgA0+QiSgVqdJqw5deAkWMnS5CtACYVBYmUq0GLdpx78ho8VNnzFAZmuEAHTBAE6KMNYAupgAvJhoEAC2cDAsGgDc+PiQUBiYwKq2GvbaTnquhh4m3uYBRZoOOs76bkaepj6WdeoNpbouBu7GXmZ+dcGBYRjWAL6x8UkpaaSZUPgAZsJQYOLQmJvbABSFPSWO-S2Vwx21J3Za580VQ+01ilZ3xQ9N5YNt1aM0P5ChMphF8ABKfKFAD0MIWyVS8lI+BmICUIAgEl2uWQoAAhhhkOt8UQ0HAMQAjEL4sAAaxSNAktORyBgIWEFJAABMIGBiaTyRj5OSQjAAAo00iJfECslcgBWaAAHgAhGn0xn45KjOVCzHCGASQ0WPVc5khUXIEAwKgSRRgEKSGDokASJ2wDjc1LIAAcAAYMe6IOS2DSJGyOVywgBHYTMMKS-HS2VIEnyjHkxLMSOczPI6QARWEEHgZoxMHxlK9PqQVhtNM4yIAwkkZdbFABWV3Ccn0KtoM0zGZAA)).

Nonetheless, I'm confused (I have never used TypeScript). Shouldn't ts-loader compile your .ts files and output JS to babel-loader? I don't understand why it would break since the syntax is valid TypeScript.

**Comment by tmaciej** [comment]
@duailibe 

> Shouldn't ts-loader compile your .ts files and output JS to babel-loader

But it does just that, exactly. So trailing commas are added by `prettier` which `ts-loader` ignores because it's valid typescript but then the output from `ts-loader` is passed to `babel-loader` which throws error because it's invalid syntax (Babel 7 only)

**Comment by ikatyang** [comment]
The `breaks builds` part looks like a TS emitter bug:

(example.ts)

```ts
const {
  longKeySoThisWillGoOnMultipleLines,
  longKeySoThisWillGoOnMultipleLines2,
  longKeySoThisWillGoOnMultipleLines3,
  ...rest,
} = something;
```

```sh
tsc example.ts --target esnext
```

(example.js)

```js
const { longKeySoThisWillGoOnMultipleLines, longKeySoThisWillGoOnMultipleLines2, longKeySoThisWillGoOnMultipleLines3, ...rest, } = something;
```

since [the current stage 3 proposal](https://tc39.github.io/proposal-object-rest-spread/) does not allow trailing comma being there, TS emitter should not emit the trailing comma.

**Comment by duailibe** [comment]
@tmaciej Yeah I meant exactly what @tmaciej, ts-loader should output valid JS, meaning it should remove the comma, not ignore it.

**Comment by tmaciej** [comment]
@duailibe This still in my opinion doesn't justify inconsistent behavior of `prettier` because code formatting happens before transpilation and i don't think those trailing commas should be removed when using one parser and left using another.

**Comment by duailibe** [comment]
@tmaciej I wasn't arguing that, I was just trying to figure out if this should be high priority or not (it should be if prettier was printing invalid syntax).

**Comment by tmaciej** [comment]
@duailibe 

> I wasn't arguing that, I was just trying to figure out if this should be high priority or not

Sorry, i misunderstood then.

Anyways, thanks for lighting fast response and PR @duailibe @ikatyang :+1:

**Comment by duailibe** [comment]
@tmaciej Thanks for the report!
