### ISSUE TITLE
Ugly TypeScript formatting when using `!` in destructuring assignments 

### ISSUE THREAD

**Issue by clentfort** [prettier/prettier#3312]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExNogWzgAUAnCABwBUALAQxgAla0BBAJTloBsuBPAGWgBzAHK1CAGky0oEGNTglSFGvSatBUUeLiYAvpgC8meQEs0AOnJlyl0-g7c+AZQCuJOCwBGEVzBrmAIQA3AA6UOGQUBjYuATENqqMzOycPALCYpLSsvKKylR0yRqZOvpGJtTmVjZ2Dmku7p4+fgFogRYycgokAPJeAFZwYDDBIBIgFDCm6MigzDDIAGbcaHATXiS0YADWcDDO5NumWsgwJK7rIAAmEGDLq1cnayQwpLRC+LQPXGsTA2gAB4AIS2u32zh0-BOcB+f0mfnIfgATHCrkcSC9kCAYLxyHA0GASKZyIsJtYTjAAOqma7yZAADgADOSyGsqVtyGcLlcPABHVymDzvT7fJArX5XNb4Uzcy4TNAnIRcOAARVcclh4seExgtC8NLp1GQyN1W1MXCVAGECF9sbIoLCJq41pR9Wg0Xo9EA)
```sh
--parser typescript
```

**Input:**
```tsx
const { somePropThatHasAReallyLongName, anotherPropThatHasALongName } = this.props.imReallySureAboutThis!;

const { somePropThatHasAReallyLongName, anotherPropThatHasALongName } = this.props.imReallySureAboutThis!.anotherObject;
```

**Output:**
```tsx
const { somePropThatHasAReallyLongName, anotherPropThatHasALongName } = this
  .props.imReallySureAboutThis!;

const { somePropThatHasAReallyLongName, anotherPropThatHasALongName } = this
  .props.imReallySureAboutThis!.anotherObject;
```

**Expected behavior:**

```tsx
const {
  somePropThatHasAReallyLongName,
  anotherPropThatHasALongName
} = this.props.imReallySureAboutThis!;


const {
  somePropThatHasAReallyLongName,
  anotherPropThatHasALongName
} = this.props.imReallySureAboutThis!.anotherObject;
```

**Comment by duailibe** [comment]
Fixed in 1.9.2!
