### ISSUE TITLE
Markdown: Adding option to have links as references at the bottom or inline

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3314]
Not sure how to name it.. but I think it would be useful especially if converting the whole codebase.

**Comment by lydell** [comment]
Could provide examples?

**Comment by lipis** [comment]
I would like to get rid of all the references to links from this file for example: https://raw.githubusercontent.com/gae-init/gae-init/master/README.md and add them all inline.

Some people might prefer to have the whole list underneath.. if that would happen then all the links should be sorted alphabetically.

**Comment by lydell** [comment]
That's an AST transform, so IMO this should not be part of Prettier.

**Comment by lipis** [comment]
_You speak in riddles old man_ :)

How can we get that in, in few words?

**Comment by duailibe** [comment]
That's more than just formatting the Markdown, that's actually changing the "structure" of the content, so it should not be part of Prettier.. That's better suited in a tool that runs after (or before, in this case) prettier.

**Comment by azz** [comment]
You can currently do this with a custom parser
