### ISSUE TITLE
Support top-level interpolations in gql tags

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#3318]
apollo supports _toplevel_ interpolations in `` gql`...` `` tagged template literals (it throws an error if you try to use interpolations in nested situations). This allows sharing GraphQL fragments between queries without loosing static analysis (both eslint-plugin-graphql and apollo-codegen support this).

Currently, we skip gql tags if they contain interpolations. It would be awesome if we could support toplevel ones though!

My idea is that we should _try_ to parse and print every literal part independently. If _all_ succeeds, we join the results up with the interpolations. If any of them fails, we bail out like today.

What do you think?

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBFArnAJwE9MBeTAcwEcAbAAwB0or9jMBVNQzYJzTXFwIAKAJYATJAxAAjCDOkBKXlH78AdJs6EAInBgBDUTTR81m9QDECohONOrMAXyYuoTACTB2AZQCiAEoA+jp+ACoAggCSADI+QZYBEQDiALJ+AHJhTl6JUZk68Ykp6VludCAANCAQAA4woujIoAYYyABmBiZw1TIEBmAA1vo+tQOiUBTIMAT41eIQYB1dXNUTQjAACv0UALYGy93VAFZoAB4AQv1DIwa7cDETcIerNbgwte8ATC89IGMEITIWQGGREGjQKr-GywADqEhgAAtkAAOAAM1VqBAgXFh-Vq01mfwIcBYohJ2wMewOSE6RxAXF2okJcwZEwoNDgeAg8F+1UMMnh4iRyC+-P6xnZAGEILt9sCoNBntVBHAwqC0L8nE4gA)

**Input:**
```jsx
const Query = gql`
query User {
  user(id:"bob"){
    ...UserDetails
    ...Friends
  }
}

${USER_DETAILS_FRAGMENT}${FRIENDS_FRAGMENT}
`
```

**Output:**
```jsx
const Query = gql`
query User {
  user(id:"bob"){
    ...UserDetails
    ...Friends
  }
}

${USER_DETAILS_FRAGMENT}${FRIENDS_FRAGMENT}
`;

```

**Expected behavior:**

```jsx
const Query = gql`
  query User {
    user(id: "bob") {
      ...UserDetails
      ...Friends
    }
  }

  ${USER_DETAILS_FRAGMENT}
  ${FRIENDS_FRAGMENT}
`;
```

**Comment by azz** [comment]
Yeah that's a simple implementation that should count for most (or all?) use cases. Sgtm.

**Comment by lydell** [comment]
@azz Since you know the multi-parser best, do you have any ideas on how to do this? The current architecture does not seem to support this. (If things become too complicated I guess we could drop the ”all parts must succeed” requirement. That might be easier to implement.)
