### ISSUE TITLE
Markdown: Preserve non-breaking spaces

### ISSUE THREAD

**Issue by infotexture** [prettier/prettier#3320]
Prettier currently replaces all non-breaking spaces with standard space characters.

This  makes sense in JavaScript or other source file formats where they may have been entered inadvertently — but when they appear in Markdown, they are most likely intentional and should **not** be discarded.

_(In prose writing, non-breaking spaces are often essential to keep numbers and units together, or ensure multi-word product names aren't torn apart.)_

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBrOcAOACmALOAZzmwHcIAnAE0NwgHM584KQAaECTGAS2kOSgAhoRjIAZkIA2xDgCMKQsOhgBlTEp5R6yGBQCucDlQhgJ02SC3EKMAAqL6AWyHmZRkACtCADwBCispMqkJOcAAyWnBulhD6MJjxAEwxHhoUNsggLhSoJqRQ7CCYFFowAOo8VPjIABwADBwlEMTlipi6Bh4UcACO+jw9DkLOrkiS7hzETjydhlNa9FJwAIr6EPCpHDBCcpXVeMhJ24o8UosAwhBOLllQ0NEc+sQAKrsC4xZwAL7fQA)
```sh
--parser markdown
```

**Input:**
```markdown
keep•these•words•together
```

_(the • character is used above to represent non-breaking spaces)_

**Output:**
```markdown
keep these words together

```

**Expected behavior:**

```markdown
keep•these•words•together
```

To support this use case, the `markdown` parser defaults should be adjusted to preserve non-breaking spaces, or a new configuration option added that allows users to enable this behavior as  required.

**Comment by lydell** [comment]
Likewise, we might want to preserve thin spaces, hair spaces, etc.

**Comment by ikatyang** [comment]
You mean `"\u00A0"`, right?

I'd like to confirm if we should preserve multi-`"\u00A0"` or normalize it to single `"\u00A0"`? e.g. `"X\u00A0\u00A0Y"` -> `"X\u00A0Y"` or `"X\u00A0\u00A0Y"`.

And also the same question applies to the other kind of spaces.

**Comment by ikatyang** [comment]
Oops, seems only `"\n"`, `"\t"` and `" "`(standard space) will be normalized in rendered html, we should preserve all the other whitespaces.
