### ISSUE TITLE
SCSS: Preserve YAML front matter block

### ISSUE THREAD

**Issue by infotexture** [prettier/prettier#3321]
Prettier is smart enough to preserve YAML front matter blocks in Markdown files, but currently strips them from SCSS files, which breaks Jekyll sites such as those deployed via GitHub Pages.

Recent Jekyll versions provide native Sass support, but the Sass processing is only triggered if the file contains a valid YAML front matter block per [Jekyll docs](https://jekyllrb.com/docs/frontmatter/):

> Any file that contains a YAML front matter block will be processed by Jekyll as a special file. 

When Prettier removes the YAML header, site output appears unstyled, as the stylesheet is not parsed.

The same logic that allows Prettier to ignore YAML headers in Markdown files should be applied to SCSS.

**Comment by azz** [comment]
Maybe not a bug in the strict sense, but we should fix it if we can.

**Comment by lipis** [comment]
Maybe we should ask Jekyll to support/use valid comments per supported filetype for these headers instead of having something that is breaking the linters/editors :)

<img width="314" alt="screen shot 2017-11-27 at 15 55 00" src="https://user-images.githubusercontent.com/125676/33272742-5b229414-d38b-11e7-9127-de5af1fde8e3.png">

**Comment by infotexture** [comment]
I don't think it's likely that Jekyll would be willing to change this, since so much of Jekyll's processing depends on the content of the YAML front matter, and every site on GitHub Pages depends on Jekyll, so the installed base that would be affected is huge.

Since Prettier already preserves YAML front matter blocks in Markdown files, it seems easier to enable similar processing in Prettier's SCSS parser than to hope for changes in Jekyll.

**Comment by lipis** [comment]
My question was, why Jekyll is not supporting both..

**Comment by lipis** [comment]
Will that make it to 1.9? #3333

**Comment by duailibe** [comment]
If someone manages to get a PR in the next few weeks or so, sure.

**Comment by infotexture** [comment]
**Until this is fixed, what's the best way to convince Prettier to ignore this single file?**

So far, I've tried the following entries in a `.prettierrc.yaml` file, but none of them seem to prevent Prettier from choking on the YAML header in the SCSS file:

_Skip the whole file:_
```yaml
overrides:
- excludeFiles: "styles.scss"
```

_Require pragma (since it doesn't have one, skip the file):_
```yaml
overrides:
- files: "styles.scss"
  options:
    requirePragma: true
```

_Exclude the range with the YAML header:_
```yaml
overrides:
- files: "styles.scss"
  options:
    rangeStart: 149
    rangeEnd: Infinity
```

**Comment by azz** [comment]
Just put the filepath in. `.prettierignore`

**Comment by infotexture** [comment]
Thanks, that'll work. Somehow I missed that in the docs.

**Comment by infotexture** [comment]
Thanks @evilebottnawi, this should make Prettier much more Jekyll-friendly. 🎉

**Comment by evilebottnawi** [comment]
@infotexture looks like new issue, can you create?

**Comment by infotexture** [comment]
@evilebottnawi Sure, will do.
