### ISSUE TITLE
Code formatting with respect to Array of objects

### ISSUE THREAD

**Issue by Aftabnack** [prettier/prettier#3336]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT5eRQDOM+AIbVq+ALz4A2u05c5+KIIC2cJPjYh4-DRzkBfADStd8ropVqNWmACYNBk6etqZpt+dXrNcfgGZ7jm5czlKuQUEelt78ACw6suH4hsYJiXKRXtYArAGpafgh0oH58hlWPjAAbPEl+gC6xW56DXlceo7NANwc7VAcIAYgEAAOuNC8yKCC-MiogiS8cIMARtSCYADWcDAAysPrOFAA5sgw1OhLIHQQYLPzi4OHi9QwAAprR0qCdwuXAFa8AAeACE1pttjtlHAADKHOA-B5DdAwYbImwIy77ajPZAgZaCZYAT3IUAGIGG1EOMAoODoMAAFsgAIwABhZgwpEEWFDWwwxg2ocAAjugcIL3oJPt8kHNfoNFkocKdzpdeIcjiQ4ABFdAQeDKi6DGAEml0xlIGJGtY4EjqgDCECUX1x8xIZPQiwAKgSJjL7nA9HogA)
```sh
--print-width 100
--no-prose-wrap
--single-quote
--tab-width 4
--trailing-comma all
```

**Input:**
```jsx
function HelloWorld() {
   const arr = [{
       name: "test"
   }, {
       name: "test2",
       test: {
           name: "test3",
           test: [{
               name: "test4"
           }, {
               name: "test5",
               test: [{
                   name: "test6"
               }]
           }]
       }
   }];
}


```

**Output:**
```jsx
function HelloWorld() {
    const arr = [
        {
            name: 'test',
        },
        {
            name: 'test2',
            test: {
                name: 'test3',
                test: [
                    {
                        name: 'test4',
                    },
                    {
                        name: 'test5',
                        test: [
                            {
                                name: 'test6',
                            },
                        ],
                    },
                ],
            },
        },
    ];
}

```

**Expected behavior:**

* It would be helpful to maintain the code formatting as it is in the Input, since the more deeper the object is, the more harder it is for me to read most of the object at once.
* Is this already possible? If not, would you be willing to consider this? I am willing to work on a PR for this.

**Comment by duailibe** [comment]
Hey! I don't think there's much we can do here in this case, as I personally don't think the proposed syntax is more readable at all.

What you could though is remove the line breaks in the simple objects `{name: 'test6'}` to make it contain in a single line:

```js
function HelloWorld() {
    const arr = [
        { name: 'test' },
        {
            name: 'test2',
            test: {
                name: 'test3',
                test: [
                    { name: 'test4' },
                    {
                        name: 'test5',
                        test: [{ name: 'test6' }],
                    },
                ],
            },
        },
    ];
}
```

**Comment by Aftabnack** [comment]
That was just a dummy sample I gave. In reality I have bigger objects with multiple keys at each level. So I cannot inline them
