### ISSUE TITLE
Markdown: line break behaviour creates new elements and changes meaning, makes Prettier non-idempotent

### ISSUE THREAD

**Issue by ryantriangles** [prettier/prettier#3344]
**Prettier 1.8.2**

Giving Prettier this single line of markdown, representing a paragraph,

```markdown
She grew up in an isolated village in the 19th century and met her father aged 29. Oh no, why are we in a numbered list now?
```

triggers the "hard wrap to enforce 80-character lines" rule, resulting in this output:

```markdown
She grew up in an isolated village in the 19th century and met her father aged
29. Oh no, why are we in a numbered list now?
```

Which is not just an aesthetic reformatting but an actual change in meaning, converting an intended `p` into a `p` and an `ol`. Wrapping in a way that made line 2 begin with a number created an ordered list element. This is, as far as I can tell, the only situation in which Prettier changes the behaviour of the code/markup it's applied to rather than just its formatting.

Additionally, because Prettier enforces a blank line between paragraphs and lists, Prettier's output here doesn't meet its own definition of pretty, also creating (as far as I know) the only situation in which running `prettier --write` twice is different to running it once, the second application producing

```markdown
She grew up in an isolated village in the 19th century and met her father aged

29. Oh no, why are we in a numbered list now?
```

**Expected behaviour**:

- That Prettier affect only aesthetic formatting, without the potential for for making your program behave differently/markup render differently, and
- That running Prettier once is enough to get a 'pretty' file.

**Comment by ikatyang** [comment]
Similar to #3168, but `/[0-9]+[.)]/` in this case.

**Comment by azz** [comment]
I thought this was actually OK according to commonmark...

**Comment by azz** [comment]
http://spec.commonmark.org/0.28/#example-248

**Comment by azz** [comment]
(More pointing out this is probably a bug in `remark-parse` too.)

**Comment by ikatyang** [comment]
It seems the example-248 only applied to empty list, [it's still parsed as list for non-empty list](http://spec.commonmark.org/dingus/?text=foo%0A*%20123%0A%0Afoo%0A1.%20123%0A).

**Comment by azz** [comment]
Interestingly only for `1.`.
