### ISSUE TITLE
--no-semi with JSX

### ISSUE THREAD

**Issue by Andarist** [prettier/prettier#3348]
A semicolon is inserted before a `JSXOpeningElement` when `--no-semi` is used, probably to guard against ASI, but as JSX desugars to a CallExpression there is no reason to guard this.

If you think this is worth changing (I do 😉) - I can prepare a PR for this.

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AID0AfADpQBKcAhmDAHRgBOV8AogDZwC2CMAFAORZs-AJQgANCAgAHGJmgBnZKEoKYyAGaU2CuJIBGDagGs4MAMrTqmKAHNkMBgFc9IdBDCbtuyTd0MYAAUjW05KLx1XACsFAA8AISMwUwtKbgAZGzgInyknGGl8gCYc1ysGf2QQfUp9AE82aAkQaQYbGAB1THQYAAtkAA4ABklWiF0Oo2kHZ1cmAEcnTCZgylDwpC1IyV1OTFKdm1sOAEUnCHgDkBharp7+pCLJR0pMNiOAYQhOMKqoaGykicugAKrUlJtvHAAL7QoA)

```sh
# Options (if any):
--no-semi
```

**Input:**
```jsx
<div />
React.createElement('div')
```

**Output:**
```jsx
;<div />
React.createElement("div")
```

**Expected behavior:**
```jsx
<div />
React.createElement("div")
```

**Comment by duailibe** [comment]
Hi @Andarist, thanks for the report! This has actually been discussed in #1433. It's not much about desugaring, but parsing the code in the first place.

I'm gonna close this as duplicate, but comment again if you think something was not addressed and we'll re-open.
