### ISSUE TITLE
Typescript: decorator + readonly + comment leads to un-compilable code

### ISSUE THREAD

**Issue by nicolaslt** [prettier/prettier#3351]
**Prettier 1.8.2**
```sh
# Options (if any):
```

**Input:**
```ts
class Something {                 
  @Annotateme()                   
  //TODO will it break            
  readonly property: Array<string>
}                                 
```

**Output:**
```ts
class Something {
  @Annotateme()
  readonly //TODO will it break
  property: Array<string>;
}
```

**Expected behavior:**
Unchanged code. Current version leads to code that Typescript 2.4.1 refuses to compile.

**Comment by azz** [comment]
Same thing for flow, too.

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMoQC2cMAFgJZQDmOwO9DjT9AOlPQAICCUUEM6eMQAUASmYTmbegHoZAFQDyAEUU4A7uVSoc5GDgBGAJzjoA1pMbScmATHJgcAByMQncIzACeSHFyNG6F4APLZGlFQAfGwAvtZsIAA0IG720JjIoFgwyABm6KiYcMnG6GBmJHhOZRHIMEYArsUgACYQYHkFRcmURZ4ACoFUhOidhc0AVpgAHgBCgeWV6MQAMpRwY90pDTBOOwBMm83VRn3IIAboBl6o0EkgLpQwAOrkLWTIABwADMkuEEVnoEnHVGs0TABHBrkEyDdDDUZIfLjZJFQjkUFNVERVBwACKDX4GyRXWaAgMr3epGQ+2S9XQWgiAGEiCNznwoBtkg0ivIrhkSeMYjEgA)

**Input:**
```jsx
class Something {                 
  @Annotateme()                   
  //TODO will it break            
  static property: Array<string>
}
  

```

**Output:**
```jsx
class Something {
  @Annotateme()
  static //TODO will it break
  property: Array<string>;
}

```
