### ISSUE TITLE
Build playground options automatically

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#3352]
Recently after every a new option or a new language we have to manually add it to playground. @suchipi suggested building the HTML automatically and that would be nice. I've created this issue just so we don't forget it.

To keep in mind: we are now using the dist code to bundle the playground so we don't have access to the `cli-constant.js` at this point. We could get it from `src/` but that would mean exposing unsupported options. Another options is having a similar `getSupportInfo` but for options.

**Comment by ikatyang** [comment]
`getOptionInfo()` looks good to me.

We can extract the format option part from `cli-constant`, proposed interface:

```ts
function getOptionInfo(version?: string): OptionInfo[];

interface OptionInfo {
  name: string;
  since: string; // available since version
  deprecated?: string; // deprecated since version
  type: 'int' | 'boolean' | 'choice';
  default: boolean | number | string | {
    [since: string]: boolean | number | string; // for default value that has changed before
  };
  range?: { start: number, end: number, step: number }; // for int, recommended range for playground
  choices?: ChoiceInfo[]; // for choice
}

interface ChoiceInfo {
  name: string;
  value: boolean | string; // boolean for the option that is originally boolean type
  since?: string; // undefined if available since the first version of the option
  deprecated?: string;
}
```

**Comment by suchipi** [comment]
Would we use OptionInfo.since to decide whether it's shown on the playground? Or rather, how would we detect/handle options that aren't released yet?

**Comment by ikatyang** [comment]
PR branch uses `getOptionInfo()`, which returns the latest options, and master branch uses `getOptionInfo(package_json_version)`, which returns the stable options.

It should work fine this way I guess.

**Comment by duailibe** [comment]
Actually the official playground always builds from the NPM version and the PR preview runs `yarn build` on src/ and uses that for the playground.

So just the output would already work..

**Comment by azz** [comment]
I left space in the return value of `getSupportInfo` for other things. Could add `options` to it.

```
{
  languages: [...],
  options: [...]
}
```

**Comment by duailibe** [comment]
Nice!

**Comment by duailibe** [comment]
I tried taking a stab at building the playground options automatically but my CSS-fu isn't that great. Do you have any suggestions on how to split the options in the groups like today? Or suggestions of a redesign to stop depending on those `div`'s?

**Comment by ikatyang** [comment]
IMO, a vertical panel would be better as the scrolling is available, just like [babel REPL](https://babeljs.io/repl/).

**Comment by duailibe** [comment]
> IMO, a vertical panel would be better

I haven't thought about that! I'll try to make that work

**Comment by duailibe** [comment]
I started working on this but it's really confusing right now.. we have a `normalizeConfig` function in `cli-util.js` that does a lot and should work for CLI and API (it expects a `type` parameter that can be either) but is only used in CLI. Then in `options.js` we have a `normalize` function that's pretty similar to the former.

Also, some defaults are in `cli-constant.js` and others are in `options.js`. It's pretty confusing, I'm not familiar with this area of code, I'd appreciate help or let me know if someone wants to collaborate.

**Comment by duailibe** [comment]
It happened!
