### ISSUE TITLE
Change run_spec to have explicit parser list.

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3355]
Currently `run_spec` runs `"flow"` by default. To change that:

```js
run_spec(__dirname, { parser: "foo" });
```

or to run multiple

```js
run_spec(__dirname, { parser: "foo" }, ["bar"]);
```

We should probably remove the default and require the Array.

We could do this with a code-mod.

**Comment by duailibe** [comment]
Does it make sense to invert the options as well? Thinking about the case of default options:

```js
run_spec(__dirname, null, ["babylon", "flow"]);

// vs

run_spec(__dirname, ["babylon, "flow"]);
```
