### ISSUE TITLE
 Backslash removed from string

### ISSUE THREAD

**Issue by sylvainbaronnet** [prettier/prettier#3358]
Hi,
You can see below that a `\` is removed from the string for no reason

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMB0MCeAHOAVOADxgAoDiBRAEwEsYIAncmAQwbhbQGc4AbOMPQYAaAAQByPAEviAegA680QHc6AC1EBTsGADXsUQEJxAShDCQEbDBrQuyUCy4xkAMxa8eFgEYMWYAGs4GABlbH8aKABzZBgGAFc4CyoIMDcPLxBIngYYAAU-KIBbFnTPJJAAKy5CACE-QOCQliK4ABlIuDLMiHiYbD6AJm6K8IYc5BBvFm9MXmhzEGwGSJgAdRoqGDVkAA4ABgtliB41v2xYhIr2AEd4mnYClmLSpHdyix4imkvEz8iovwAIrxCDwEYWVjeDZbHZIQaQvw0XgAgDCECKJUmUGgXQs8R4eBm9jeGTgAF9yUA

Thanks

**Comment by azz** [comment]
This is intentional. `\ ` is the same as ` `, so prettier normalizes it.

**Comment by sylvainbaronnet** [comment]
it's removed even if it's not a space after : https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMB0MCeAHOAVOADxgAoDiBRAEwEsYIAncmAQwbhbQGc4AbOMPQYAaAAQByPAEviAegA68gO50AFqICnYMAGvYogITiAlCGEgI2GDWhdkoFlxjIAZi149zAIwYswAazgYAGVsPxooAHNkGAYAVzhzKggwV3dPEAieBhgABV9IgFsWNI9EkAArLkIAIV8AoOCWQrgAGQi4UoyIOJhsXoAmLvKwhmzkEC8WL0xeaDMQbAYImAB1GioYVWQADgAGcyWIHlXfbBj48vYARziadnyWIpKkNzLzHkKaC4SPiMj+ABFOIQeDDcysLzrTbbJADCG+Gi8f4AYQghWKEyg0E65jiPDw0zsr3ScAAvmSgA

**Comment by sylvainbaronnet** [comment]
also, not sure `'\ '` is the same than `" "`

**Comment by karl** [comment]
Prettier removes a `\` when it would leave the string unchanged, but it leaves backslashes that have meaning.

For example:

```
x = "\ \a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u1234\v\w\x12\y\z"
```

becomes:

```
x = " a\bcde\fghijklm\nopq\rs\t\u1234\vw\x12yz";
```

This playground link might help illustrate that:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXnQHRDnXHAQwICMCwCATAuAgMwIHMCALAgSwICsCBrAgBsCAWwJQCEAgAcCARwIAnAgGcCMAgFcAjACYAzABYCANwIB3Aqn0EAngQBeeHJKggANCAgyYnaKrIoMSqMMgMxEKqcF5kSsRg-HAwAMoyCZxQzMgwSloxINQQYOGR0V6Z0UowAArxzKLEpVEFPKqoAELxickpxKJwADKZcM3l3lowMpN6YwXpSlXIIGTEZHZC0J4gMkqZMADqnNQwbMgAHAAMXrsQ0QfxMjl5BUpw8lqcb3XEDU1IERaXmiok4z3ywMyzCEcAAiloIPA5l4YGsjiczkg9Cj4pwhFCAMIQUSNZZQaCjLxaaIAFTWgQBZTgAF9mUA

**Comment by azz** [comment]
It's the same.

https://tc39.github.io/ecma262/#table-34
> The SV (String value) of CharacterEscapeSequence::NonEscapeCharacter is the SV of the NonEscapeCharacter.

**Comment by sylvainbaronnet** [comment]
I see, thanks !
