### ISSUE TITLE
Text in <pre> tag collapsed

### ISSUE THREAD

**Issue by houshuang** [prettier/prettier#3359]
I had text in a < pre> tag, where line spacing was significant, which was collapsed by Prettier 1.8.2.

Prettier 1.8:
```
            <pre>{`127.0.0.1    localhost
127.0.0.1   dev1
127.0.0.1   dev2
127.0.0.1   dev3
127.0.0.1   dev4`}</pre>
```

Prettier 1.8.2:
```
            <pre>
              127.0.0.1 localhost 127.0.0.1 dev1 127.0.0.1 dev2 127.0.0.1 dev3
              127.0.0.1 dev4
            </pre>
```

This obviously changes the way it displays. I guess < pre> has to be special-cased, it's the only HTML tag (?) where white-space is significant...

**Comment by azz** [comment]
Cannot reproduce?

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgJzgPmAAwEYAmAdgDoAGK8wgAgboBsIwBDJgCwgGcYAdKCQrVq9BgBM4AN0KDhNMYynTi8sotrKZAZnUia4uioAs+AL6oA9FlwgANCAjoYAS2g9koNn2QAzDh44RwAjTDYwAGs4GABldAjXKABzZBhMAFdgkAlWf0DspKDMGAAFcOSAWzZ8piDHACseAA8AIXComNi2SrgAGSS4WvqnDJh0MeJh7ITMYuQQELYQgE8WKAcQLCSYAHVXCRhOZAAOSkcsXjhd8PQ0zOzsAEcM12xytiqapAC67KDKq57llHDwkskmHAAIoZCDwaaOGDLfaHY5IYiI8KuJjggDCEEq1QWUGgQ0cGSCABVlp4fgVzOYgA)

**Input:**
```jsx
<pre>{`127.0.0.1    localhost
127.0.0.1   dev1
127.0.0.1   dev2
127.0.0.1   dev3
127.0.0.1   dev4`}</pre>
```

**Output:**
```jsx
<pre>{`127.0.0.1    localhost
127.0.0.1   dev1
127.0.0.1   dev2
127.0.0.1   dev3
127.0.0.1   dev4`}</pre>;
```

**Comment by houshuang** [comment]
Apologies, turns out it was Eslint fix which automatically removed the curly braces ('dont' need them here'), and then Prettier came around to reformat... I upgraded Prettier and Eslint at the same time - should have made a reproducible example before posting.

Thank you!
