### ISSUE TITLE
Typescript, unexpected token when using implements and dot operator

### ISSUE THREAD

**Issue by gimenete** [prettier/prettier#3360]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3wDMIIqcJ18ByaiJgHSk7ABtyKAsgE8Aklh5x0CGCRipo+DJglTYFVgDoRAZQZwRsODkokwcfME4BfEABoQETHOhlkocjGQmeZOPYBGOKYA1nAw2pimqFAA5sgwOACufiAAJhBgXiQ+KdG+eAAKQTHoJFk59gBWZAAeAEJBYKHhJFIAMtFw5b72EIkwmP0ATN0pkTj5yCD+JP5CPNB2IJg40TAA6qipMAAWyAAcAAz2KxC+60GY8UkpOHAAjomod0UkJWVI3j0gvuio18l7GRojEJABFRIQeCjewyfybbZ7JBDWFBVA8EEAYQYpSmUGgXXsiV8ABVZq5PtlfFYrEA)

**Input:**
```jsx
import * as foo from 'foo'

class MyImplementation implements foo.ISomeInterface {
}
```

**Output:**
```jsx
SyntaxError: Unexpected token, expected { (3:38)
  1 | import * as foo from 'foo'
  2 | 
> 3 | class MyImplementation implements foo.ISomeInterface {
    |                                      ^
  4 | }
```

**Expected behavior:**

The TypeScript input is fine and it should be supported.

**Comment by ikatyang** [comment]
You have to specify `--parser typescript`.

---

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3wDMIIqcJ18ByaiJgHSk7ABtyKAsgE8Aklh5x0CGCRipo+DJglTYFVgDoRAZQZwRsODkokwcfME4BfEABoQETHOhlkocjGQmeZOPYBGOKYA1nAw2pimqFAA5sgwOACufiAAJhBgXiQ+KdG+eAAKQTHoJFk59gBWZAAeAEJBYKHhJFIAMtFw5b72EIkwmP0ATN0pkTj5yCAwQphwZGA4qE52IJhLsADqqKkwABbIABwADPbrEL6bQZjxSSk4cACOiagPRSQlZUjePSC+6Khbsl7GRojEJABFRIQeCjewyfzbXYHJBDeFBVA8MEAYQYpSmUGgXXsiV8ABUSP5XN9sr4rFYgA)
```sh
--parser typescript
```

**Input:**
```tsx
import * as foo from 'foo'

class MyImplementation implements foo.ISomeInterface {
}
```

**Output:**
```tsx
import * as foo from "foo";

class MyImplementation implements foo.ISomeInterface {}

```
