### ISSUE TITLE
Admonitions destroyed

### ISSUE THREAD

**Issue by msageryd** [prettier/prettier#3362]
**Prettier 1.8.2**

Markdown formatting destroys admonitions, i.e. the colored "note" box that can be created with the markdown extension **python-admonition**.

**Input:**
```markdown
!!! note "Note title"
    Note text..
```

**Output:**
```markdown
!!! note "Note title" Note text..
```

**Expected behavior:**
I'm not sure how this should be formatted according to the spec. But the way it behaves has forced me to disable prettier for markdown-files for now.

In order to have python-admonitions extension to work (I'm using it with mkdocs) I need to have the new line and indentation preserved.

Is there a setting for this that I have missed?

https://pythonhosted.org/Markdown/extensions/admonition.html

**Comment by ikatyang** [comment]
It seems what you need is the [`<!-- prettier-ignore -->` comment](https://prettier.io/docs/en/ignore.html#markdown).

---

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRE7YB8AOlOhznfDiyAHIQeZGABs4fNjmk5BwuAA8YAOmUgANCAh4y0AM7JQAQz0xkAMyOi9cTQCMCRsAGtiAZTxPSUashgEAV1sQABMIMAsrG01vGwIYAAVHagBbI0jrYIArPQUAIUcXdyMUuAAZbzgM6K0AmDw6gCZq4M8COOQQNIJnMIB3KA0QQm8YAHVSEJgAC2QADgAGTUIIGzHHPD9A4KIARwDSIiSjVPSkS0zNGxTSLaCr72pxAEUAoSrzqOCYIzsJqdmSEamn8RlIokeAGEICk0p06FAqpoAjYACq-AyfTIAX2xQA)
```sh
--parser markdown
```

**Input:**
```markdown
<!-- prettier-ignore -->
!!! note "Note title"
    Note text..
```

**Output:**
```markdown
<!-- prettier-ignore -->
!!! note "Note title"
    Note text..

```

**Comment by msageryd** [comment]
Great, thanks!
Now I can enable prettier again :)

Is this the only way to solve this? Or would it be reasonable for prettier to recognise admonitions somehow and leave them alone?

**Comment by ikatyang** [comment]
I thought about it and found that there's no [remark-plugin](https://github.com/wooorm/remark/blob/master/doc/plugins.md) for those syntax (we use remark to parse markdown), and also it seems there's no spec (something like  [this](http://spec.commonmark.org/)) for them so that we're not able to know how to print it correctly.

**Comment by msageryd** [comment]
Thanks for your time. I'll use **prettier-ignore** where I need it. It's totally worth it to have all the other goodie-autoformat-stuff.
