### ISSUE TITLE
feature request: sane cli defaults

### ISSUE THREAD

**Issue by jasonkarns** [prettier/prettier#3365]
The best tools (IMO) require no configuration. Or rather, their configuration is implicit by convention.
This was the biggest selling point for standardjs, and I assume is a feeling shared by prettier.

**Desired behavior:**
Be able to run prettier without any options, and have it do the "right" thing for 90% of js projects. Standardjs does this and has its defaults defined thusly:

> If FILES is omitted, then all JavaScript source files (*.js, *.jsx) in the current
    working directory are checked, recursively.
>    Certain paths (node_modules/, coverage/, vendor/, *.min.js, bundle.js, and
    files/folders that begin with '.' like .git/) are automatically ignored.
>    Paths in a project's root .gitignore file are also automatically ignored.

It would be a much nicer CLI UX if one's `lint` package script were just `prettier --write`.

**Comment by duailibe** [comment]
I think this is really similar to #2691, I'm merging this issue there.
