### ISSUE TITLE
Multi line render methods in React

### ISSUE THREAD

**Issue by marco-fp** [prettier/prettier#3369]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBhCBbAB2gSwF5MAKYMACwEsAbAEwCcEBfASk1ID5KAOlEyYAPAHUWAQwIE4LXkJEjq9ZmyjslYgPSSZchUM4BuEABoQEAjDrpkoKRmQAzKQzRxLAI2lgA1nAwAMoEUmB0UADmyDAsAK5eIEwQYK7unpaRniwwAArSUXhS6R5JAFZoAB4AQn6BIVJ4cAAykXClmVbxMAQ9AEydSWEsOcggLgwQAO4WIAQskTDidEwwNMgAHAAMlgsQnvoEsQlJbACO8XRsBVJFJUhuZZaeeHQniS+RUQxwAIrxCDwIaWGBSbwrNYbJD9UHSRjfXB4YrjKDEObxTwAFXBaCG7HYQA)
```sh
--parser flow
```

**Input:**
```jsx
const Component = ({children}) => (
  <Wrapper>
    {children}
  </Wrapper>
);
```

**Output:**
```jsx
const Component = ({ children }) => <Wrapper>{children}</Wrapper>;

```

**Expected behavior:**

In previous versions I would have an output that accepts multi lines for render methods, after updating to the latest version, I'm receiving 300+ errors regarding this situations.

Is there any way of configuring prettier to make it correct the code the way it was before?

Thank you for your time.

**Comment by j-f1** [comment]
Because we try to avoid looking at the original source code, we don’t know whether the element was broken into multiple lines or not. We generally do not add options to change Prettier’s behavior, so we won’t be providing an option for this.
