### ISSUE TITLE
Eslint disable with max-len line break

### ISSUE THREAD

**Issue by f0rr0** [prettier/prettier#3375]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2AB0pNMB6KzONAGwEtYBaAEybQEMcG5WUOAA8YrZkMwBbbsPEJyldvTAAnJgAcYTaEkwByAPIBXVZgBuEBsdhw4qtJm5gwcLXHaYAHADMmMQEwCRwBGACZWAHc7AGtMMAALbgZ+KABzOAAaTBwAT0wfKwYICJZU7FNpXCZ+Jw0NIMwIiFVoiGMsNASPYxruKE8odvVtaEwNBj60ADpMAGF4uDBYtqwYBaYzGFVJgtUZEag0LL7PNDtGxNWFvMTzOEwYCEwePN4V7z8YGYAKABUnrZ5Xz+RrNVrtI6YdJXe4+VTnKRVGp3Bw6CgQHzlMzcOpOLARAlTYFfSBSKjQgD6nwAlPoMuQAL4gDIgCBaNFoZCgbgYZA+JJnFk4bZLOAwADKGmcpWQW2MmRA7AgYD5AoVLDOqhgAAVtqkZKqGIKQHg0MIAEIi6Ji8XcKRwAAyLDghuNKw07VCroVUoc9mQIBwvByRSgzJAGnUsAA6kx2GtkF4AAwsyMQM7R7YaWWqeUs+EAR2MGzguu4+u43pZZykTBzeZAaFK-AAisYIPAqyAYLxY-H4shQiyttxqqVZhApAaUFBoC6WcYzr9eJykPyjXAGQygA)

**Input:**
```jsx
const obj = {
  // eslint-disable-next-line max-len
  description: 'Our volunteers accepted 8fit’s 12-week challenge, by following our mobile app’s workout schedule and nutrition plans. Check out their transformations, and see what they have to say about 8fit. (To try 8fit workouts, get the free mobile version of our app at www.8fit.com/get_fit)',
}
```

**Output:**
```jsx
const obj = {
  // eslint-disable-next-line max-len
  description:
    "Our volunteers accepted 8fit’s 12-week challenge, by following our mobile app’s workout schedule and nutrition plans. Check out their transformations, and see what they have to say about 8fit. (To try 8fit workouts, get the free mobile version of our app at www.8fit.com/get_fit)"
};

```

The disable doesn't work and eslint is unhappy because the long string is formatted to the next line with a line break.

**Comment by duailibe** [comment]
We actually recommed that you turn off the `max-len` rule since prettier will already take care of that whenever possible (see github.com/prettier/eslint-config-prettier).

However if you do want to keep that rule on, for this specific case I think your only option would be:

```js
const obj = {
  // eslint-disable max-len
  description:
    'Our volunteers accepted 8fit’s 12-week challenge, by following our mobile app’s workout schedule and nutrition plans. Check out their transformations, and see what they have to say about 8fit. (To try 8fit workouts, get the free mobile version of our app at www.8fit.com/get_fit)',
};
```

Other than that, there's not much we can do here.

**Comment by suchipi** [comment]
This works, too:
```js
const obj = {
  // prettier-ignore
  // eslint-disable-next-line max-len
  description: 'Our volunteers accepted 8fit’s 12-week challenge, by following our mobile app’s workout schedule and nutrition plans. Check out their transformations, and see what they have to say about 8fit. (To try 8fit workouts, get the free mobile version of our app at www.8fit.com/get_fit)',
}
```
