### ISSUE TITLE
Add support for formatting template literals in emotion CSS props

### ISSUE THREAD

**Issue by kripod** [prettier/prettier#3378]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAyhALZwDCpADtAjPgBRUBOEVAzgJT7AA6U+fAHoh+cszgBDePnYwAngBs47fJNU5U+eRHQByCfjCTFinFADmR9qslQAJvhgALOEcXrVAdxyn8AIzdJKiozOEcYCCdXI2paWH5BCRh0ZgEGAB57HAA3a3YAXmAAA0TBWMUIZiQAxXQ4AG4ywVRoGABadhwALzgagBJgFjZ2ADpW2EIeuABfKgAPJqhm-AAyJGcIHLhmHhXBSErq-AsJBCXy-Bn+FdX8UfZSOHawDxs9gUv8CY6u3pqAEwABgWF3K10+xRmAD4VgAVZw4by+RQBNz+OpuTC4VGbbYSeyjFZZXLuTwAOUkZAKvBAjzILze7FpsM+lwRSO+bVk03wPj8gXwwIWxKE2RyrMEGTFuWhnH4EP4kCgcnwcJUMEoJBoUDo+AKjGARkRinsEigABp7qNRsMOFduAVoYwyiS8mAbEViocqjUvIj4A0ApIwABrU66Bw1DEh0NQyXlYBgE1mhAQqUyiX8ThLEAWkBsXDQdjIUDqGDIVAmdhwfP+ZixuAwQhUEPmCzIGDMer5+wQMCV6u1kDmGvMGAABQbFhIkkHihr+YAVux5gAhBthpuEKlwAAy5jg88XBfQMCoZ4Bx+HreYY+QIH8kn8SmgeZALHMMAA6jh7C5kAADiBfNhhrb8GyoTtu2HCQAEd0BwCQp0kGc5yQKsF2HGsSBwaCezpdtlAARXQCB4Hw4cYGfX9-2cZAAXzLtJF8dstVnB8TEUd90BrOFnxLDChxmGYgA)
```sh
--single-quote
--trailing-comma all
```

**Input:**
```jsx
function SomeComponent (props) {
  // Create styles as if you're calling css and the class will be applied to the component
  return (<div css={`
    color: blue;
    font-size: ${props.fontSize}px;

    &:hover {
      color: green;
    }

    & .some-class {
      font-size: 20px;
    }
  `}>
    This will be blue until hovered.
    <div className="some-class">
      This font size will be 20px
    </div>
  </div>)
}

const TestComponent = ({ children, ...props }) => (
  <div css={`color: white; background: black`}>
    {children}
  </div>
);

```

**Output:**
```jsx
function SomeComponent(props) {
  // Create styles as if you're calling css and the class will be applied to the component
  return (
    <div
      css={`
    color: blue;
    font-size: ${props.fontSize}px;

    &:hover {
      color: green;
    }

    & .some-class {
      font-size: 20px;
    }
  `}
    >
      This will be blue until hovered.
      <div className="some-class">This font size will be 20px</div>
    </div>
  );
}

const TestComponent = ({ children, ...props }) => (
  <div css={`color: white; background: black`}>{children}</div>
);

```

**Expected behavior:**
Styles specified as [emotion CSS props](https://emotion.sh/#css-prop) should get CSS formatting.

**Comment by duailibe** [comment]
Yeah seems reasonable to me. Should be easy to do it

**Comment by kripod** [comment]
Also, please support simple strings too (e.g. `<div css="color: white; background: black">{children}</div>`), as my ESLint configuration disallows using template strings if they don't have `${variables}` in them.

**Comment by kripod** [comment]
In addition to that, [reusable media queries](https://emotion.sh/#reusable-media-queries) make Prettier "escape" from CSS mode. I think that CSS mode should be activated for every `${...}` descendant of a CSS template literal.

**Comment by suchipi** [comment]
@kripod could you please open a separate issue for the reusable media queries? Fixing the css prop is pretty easy, but fixing reusable media queries will be harder (since the query names are not standardized).

**Comment by kripod** [comment]
@suchipi Sure, I'm glad to help!

**Comment by suchipi** [comment]
Thanks!

**Comment by duailibe** [comment]
> Also, please support simple strings too (e.g. `<div css="color: white; background: black">{children}</div>`)

I'm not sure how to do this.. Prettier will break those two rules in separate lines, how should we handle this as a simple string?

**Comment by kripod** [comment]
@duailibe I may just disable the ESLint rule in question or open a separate issue for it.
