### ISSUE TITLE
wrong indent (tab width) when using ternary in jsx

### ISSUE THREAD

**Issue by brikou** [prettier/prettier#3384]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAxCFMC8mAFAJSEB8JAOlJvZgDwAmAlgG4W0M+bABmeQgSJQArgBsJ3XrID8maiCUzZPJJkH4RRGACcxcVWp4KlATThoVdE7w1KAchCUBfY4wD0bTrVIBuWhAAGhAIAAcYVnRkUABDDGR+OIk0OFCAIz04sABrOBgAZXCc1igAc2R9Q1DmCDAklLTQgCs0AA8AIWy8gsK4gFs4ABkyuEbU9LCxGHCZgCYJ5pASvTS9ZBAMuIyATwloEJW9MpgAdVZmGAALZAAWAAZQtIHWKoMptDLyiTgARTEEHgSymMB2FyutyQd1C+jirAk3wAwhABgM4psoNBxqExGkACo7NAg1yuIA)
```sh
--print-width 40
--tab-width 4
```

**Input:**
```jsx
const Foo = () => (
    <div>
        {foo === null
            ? ""
            : foo === true
              ? "Yes"
              : "No"}
    </div>
);

```

**Output:**
```jsx
const Foo = () => (
    <div>
        {foo === null
            ? ""
            : foo === true
              ? "Yes"
              : "No"}
    </div>
);

```

**Expected behavior:**
```diff
 const Foo = () => (
     <div>
         {foo === null
             ? ""
             : foo === true
-              ? "Yes"
-              : "No"}
+               ? "Yes"
+               : "No"}
     </div>
 );

```

BTW thank you all!

**Comment by lydell** [comment]
My guess is that only the “align with two spaces in ternaries” thing is done here, and we forgot to indent. Most tests use 2-space indentation, so this probably slipped through because of that...

**Comment by brikou** [comment]
@lydell great it should be easy to fix then :)

**Comment by azz** [comment]
Similar to #2771
