### ISSUE TITLE
Markdown Parsing differently each run

### ISSUE THREAD

**Issue by lukepolo** [prettier/prettier#3387]
**Prettier 1.8.2**

Each time prettier is ran, it will write the markdown file in a different format (mabye line endings?).
In certain files. You can see our bot : (https://github.com/gatsbyjs/gatsby/compare/KyleAMathews-patch-1). It kinda went a bit crazy (500+ commits), which would commit the new changes. 

The process : 

1. Checkout repo 
2. Change branch
3. Run :
`prettier packages/gatsby-source-wordpress/README.md --no-semi --tab-width 2 --print-width 80 --no-prose-wrap --trailing-comma es5 --write`
4. Commit
5. Repeat 3

**Comment by ikatyang** [comment]
Thanks for the report, it seems it's somehow fixed on master, though I don't know how it happened and fixed.

<details>
<summary>1.8.2</summary>

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiVACA6hATgEwAVc4BnUjQgGwFcBzASylIB0o2AVACzLgwAdajZhgDucEhnil4+AHTY+4qpAC2fQgCUKAQ3z4mdDKRr9+eGBgBmeDPh0wd13BFUYIMHrgFCmpOWxsAFQYANoAHgC6GADCNDKulBAyGBwAnvxkGEgYDJaiDFRUYngA1sZwcKpUZKRUaQA0GFAQ1jS4nhLu-DAM0M2V+BQwrQBGfDpgvQBuDnDyGAAULCAAylwQorlQGJoAoqscGACChACSKxUwvVBGUIPDY3ykcJYjUrg0fP2dGGDxIzc5hSTCkPB89FBL2uhgoNm8ngYjxKuFKCjOMAA5BRoVJWisrDoqC9LqM0nY4ISaFQYHIAJSBKAhCLRULHGIAMUiiy4134pCQAHpBaJRXI9LMoGB5v8EqorAw4FQhnI1IK6alwRAen0dgADeJwdkcnIwT5wPUYVQAjDjDCTGZzfDbDBpCDtYx5ODYjB6ugOUhkgC0kCgCrocgAVqQ9QF2DsMCEAJruq02rg6aZ8X6CSE7UKTKxBkZBkgyIM6fgMbm8mD8oWCxieGijVWuQU6Bhl6akOgdsBFktlmAVqsavyOIrzF04AjEWpxjCJ7CFYr8anFX56ws5YAYOQHjAAX0tCqVQx9ofgsDhLjcOig5IQvRg5NEXAYYC4GAzFDy9uuSYeGdRZ+B0OgyCaYEYFIJp1AMHRYP3Q83RoP4NmSPgrDvGc8CIMsKFGSZSiDBBnXfQo+DAEgHEMe0MAAcRcUx3CsDAOUVZVSDpRdlzZTlKBcGs+QFYVRVEcV8ElaV8FlQEzy4ttVEFfgXHVYwdHUe0KGNbI2CXEIsFXFFygKTwwg5GpwgYUYaj+aBrxgYS61EkUxQlB8ZLk1wFJVNUy3dXBpVIQUrCsmyahDBzn3Uh9nVUqoGBoNwZBoKw2KoBhSmzDNLEWEhMjmXAmn9KdcEaZD6V4wzjPXIowSo6LYAAxwv2nd5flCbVemgCgwIg5z6zE9ypM8mUAR8zi-PbPR8CDXrBW63VSCDfq4HVONgjCKIwiwQgg1OM4gwAWT2AA5ABVVZBtc0Q8IS8g5DwPtc2EELRH4UcGCDdQoHidSKK-DBGCzChUIaq0EHie0oGdX60KoCAwFo3qMDI8wmFpRlmR20I9uOgAZIN9kOA7zhuhsmy4FslMFUgM1EKAMMyXARX4apSzIEdKwYDVAe-WbhnBf5cBIZrEeRuy4vtWZCh0Wzs1wB86hRkR3iJNdkjeDIyDkEAGhAJbeuQUBEJgZBCWJOADdGJWwGymBVjAsBDGQM0vgN-AkYtokXgNvwJBgYhwNUHQfatg3o3CAAhO2HdWTS4AJpg4HDv3DZoOtM4AJjd80DbA3AXlwZAQFD1EvcZ-WQFUzGjPwTxkAADgABgLlwXiwJX+DT62QBIABHGguzgYO6FD3uDZeVQGDzj2QFIQwagARRoDxU6QS308cUZ68bpBs4Ns1O0y24YlcCeUBae5q8NDh5dIXujyPIA)
```sh
--parser markdown
--no-prose-wrap
```

**Input:**
```markdown
## WordPress Plugins

These plugins were tested. We welcome PRs adding support for data from other plugins.

* [x] Custom Post Types : it will work seemlessly, no further option needs to be activated. ("Show in REST API" setting needs to be set to true on the custom post in the plugin settings for this to work. It's set to "false" by default.)

* [x] [ACF](https://www.advancedcustomfields.com/) The option `useACF: true` must be activated in your site's `gatsby-config.js`.

  * You must have the plugin [acf-to-rest-api](https://github.com/airesvsg/acf-to-rest-api) installed in WordPress.
  * Will pull the `acf: { ... }` fields's contents from any entity which has it attached (pages, posts, medias, ... you choose from in WordPress back-end while creating a Group of Fields).
  * [ACF Pro](https://www.advancedcustomfields.com/pro/) same as ACF :
  * Will work with [Flexible content](https://www.advancedcustomfields.com/resources/flexible-content/) and premium stuff like that (repeater, gallery, ...).
  * Will pull the content attached to the [options page](https://www.advancedcustomfields.com/add-ons/options-page/).

* [x] [WP-API-MENUS](https://wordpress.org/plugins/wp-api-menus/) which gives you the menus and menu locations endpoint.

* [x] [WPML-REST-API](https://github.com/shawnhooper/wpml-rest-api) which adds the current locale and available translations to all post types.
```

**Output:**
```markdown
## WordPress Plugins

These plugins were tested. We welcome PRs adding support for data from other plugins.

* [x] Custom Post Types : it will work seemlessly, no further option needs to be activated. ("Show in REST API" setting needs to be set to true on the custom post in the plugin settings for this to work. It's set to "false" by default.)

* [x] [ACF](https://www.advancedcustomfields.com/) The option `useACF: true` must be activated in your site's `gatsby-config.js`.

      * You must have the plugin [acf-to-rest-api](https://github.com/airesvsg/acf-to-rest-api) installed in WordPress.
      * Will pull the `acf: { ... }` fields's contents from any entity which has it attached (pages, posts, medias, ... you choose from in WordPress back-end while creating a Group of Fields).
      * [ACF Pro](https://www.advancedcustomfields.com/pro/) same as ACF :
      * Will work with [Flexible content](https://www.advancedcustomfields.com/resources/flexible-content/) and premium stuff like that (repeater, gallery, ...).
      * Will pull the content attached to the [options page](https://www.advancedcustomfields.com/add-ons/options-page/).

* [x] [WP-API-MENUS](https://wordpress.org/plugins/wp-api-menus/) which gives you the menus and menu locations endpoint.

* [x] [WPML-REST-API](https://github.com/shawnhooper/wpml-rest-api) which adds the current locale and available translations to all post types.

```

**Second Output:**
```markdown
## WordPress Plugins

These plugins were tested. We welcome PRs adding support for data from other plugins.

* [x] Custom Post Types : it will work seemlessly, no further option needs to be activated. ("Show in REST API" setting needs to be set to true on the custom post in the plugin settings for this to work. It's set to "false" by default.)

* [x] [ACF](https://www.advancedcustomfields.com/) The option `useACF: true` must be activated in your site's `gatsby-config.js`.

          * You must have the plugin [acf-to-rest-api](https://github.com/airesvsg/acf-to-rest-api) installed in WordPress.
          * Will pull the `acf: { ... }` fields's contents from any entity which has it attached (pages, posts, medias, ... you choose from in WordPress back-end while creating a Group of Fields).
          * [ACF Pro](https://www.advancedcustomfields.com/pro/) same as ACF :
          * Will work with [Flexible content](https://www.advancedcustomfields.com/resources/flexible-content/) and premium stuff like that (repeater, gallery, ...).
          * Will pull the content attached to the [options page](https://www.advancedcustomfields.com/add-ons/options-page/).

* [x] [WP-API-MENUS](https://wordpress.org/plugins/wp-api-menus/) which gives you the menus and menu locations endpoint.

* [x] [WPML-REST-API](https://github.com/shawnhooper/wpml-rest-api) which adds the current locale and available translations to all post types.

```

</details>


<details>
<summary>master</summary>

**Prettier pr-3367**
[Playground link](https://deploy-preview-3367--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBiVACA6hATgEwAVc4BnUjQgGwFcBzASylIB0o2AVACzLgwAdajZhgDucEhnil4+AHTY+4qpAC2fQgCUKAQ3z4mdDKRr9+eGBgBmeDPh0wd13BFUYIMHrgFCmpOWxsAFQYANoAHgC6GADCNDKulBAyGBwAnvxkGEgYDJaiDFRUYngA1sZwcKpUZKRUaQA0GFAQ1jS4nhLu-DAM0M2V+BQwrQBGfDpgvQBuDnDyGAAULCAAylwQorlQGJoAoqscGACChACSKxUwvVBGUIPDY3ykcJYjUrg0fP2dGGDxIzc5hSTCkPB89FBL2uhgoNm8ngYjxKuFKCjOMAA5BRoVJWisrDoqC9LqM0nY4ISaFQYHIAJSBKAhCLRULHGIAMUiiy4134pCQAHpBaJRXI9LMoGB5v8EqorAw4FQhnI1IK6alwRAen0dgADeJwdkcnIwT5wPUYVQAjDjDCTGZzfDbDBpCDtYx5ODYjB6ugOUhkgC0kCgCrocgAVqQ9QF2DsMCEAJruq02rg6aZ8X6CSE7UKTKxBkZBkgyIM6fgMbm8mD8oWCxieGijVWuQU6Bhl6akOgdsBFktlmAVqsavyOIrzF04AjEWpxjCJ7CFYr8anFX56ws5YAYOQHjAAX0tCqVQx9ofgsDhLjcOig5IQvRg5NEXAYYC4GAzFDy9uuSYeGdRZ+B0OgyCaYEYFIJp1AMHRYP3Q83RoP4NmSPgrDvGc8CIMsKFGSZSiDBBnXfQo+DAEgHEMe0MAAcRcUx3CsDAOUVZVSDpRdlzZTlKBcGs+QFYVRVEcV8ElaV8FlQEzy4ttVEFfgXHVYwdHUe0KGNbI2CXEIsFXFFygKTwwg5GpwgYUYaj+aBrxgYS61EkUxQlB8ZLk1wFJVNUy3dXBpVIQUrCsmyahDBzn3Uh9nVUqoGBoNwZBoKw2KoBhSmzDNLEWEhMjmXAmn9KdcEaZD6V4wzjPXIowSo6LYAAxwv2nd5flCbVemgCgwIg5z6zE9ypM8mUAR8zi-PbPR8CDXrBW63VSCDfq4HVONgjCKIwiwQgg1OM4gwAWT2AA5ABVVZBtc0Q8IS8g5DwPtc2EELRH4UcGCDdQoHidSKK-DBGCzChUIaq0EHie0oGdX60KoCAwFo3qMDI8wmFpRlmR20I9uOgAZIN9kOA7zhuhsmy4FslMFUgM1EKAMMyXARX4apSzIEdKwYDVAe-WbhnBf5cBIZrEeRuy4vtWZCh0Wzs1wB86hRkR3iJNdkjeDIyDkEAGhAJbeuQUBEJgZBCWJOADdGJWwGymBVjAsBDGQM0vgN-AkYtokXgNvwJBgYhwNUHQfatg3o3CAAhO2HdWTS4AJpg4HDv3DZoOtM4AJjd80DbA3AXlwZAQFD1EvcZ-WQFUzGjPwTxkAADgABgLlwXiwJX+Dzj2QBIABHGguzgYO6FDtPrZAF5VAYXup9IQwagARRoDxU6QS308cUZ68bpBs4Ns1O0y24YlcCeUBae5q8NDh5dISejyPIA)
```sh
--parser markdown
```

**Input:**
```markdown
## WordPress Plugins

These plugins were tested. We welcome PRs adding support for data from other plugins.

* [x] Custom Post Types : it will work seemlessly, no further option needs to be activated. ("Show in REST API" setting needs to be set to true on the custom post in the plugin settings for this to work. It's set to "false" by default.)

* [x] [ACF](https://www.advancedcustomfields.com/) The option `useACF: true` must be activated in your site's `gatsby-config.js`.

  * You must have the plugin [acf-to-rest-api](https://github.com/airesvsg/acf-to-rest-api) installed in WordPress.
  * Will pull the `acf: { ... }` fields's contents from any entity which has it attached (pages, posts, medias, ... you choose from in WordPress back-end while creating a Group of Fields).
  * [ACF Pro](https://www.advancedcustomfields.com/pro/) same as ACF :
  * Will work with [Flexible content](https://www.advancedcustomfields.com/resources/flexible-content/) and premium stuff like that (repeater, gallery, ...).
  * Will pull the content attached to the [options page](https://www.advancedcustomfields.com/add-ons/options-page/).

* [x] [WP-API-MENUS](https://wordpress.org/plugins/wp-api-menus/) which gives you the menus and menu locations endpoint.

* [x] [WPML-REST-API](https://github.com/shawnhooper/wpml-rest-api) which adds the current locale and available translations to all post types.
```

**Output:**
```markdown
## WordPress Plugins

These plugins were tested. We welcome PRs adding support for data from other
plugins.

* [x] Custom Post Types : it will work seemlessly, no further option needs to be
      activated. ("Show in REST API" setting needs to be set to true on the
      custom post in the plugin settings for this to work. It's set to "false"
      by default.)

* [x] [ACF](https://www.advancedcustomfields.com/) The option `useACF: true`
      must be activated in your site's `gatsby-config.js`.

  * You must have the plugin
    [acf-to-rest-api](https://github.com/airesvsg/acf-to-rest-api) installed in
    WordPress.
  * Will pull the `acf: { ... }` fields's contents from any entity which has it
    attached (pages, posts, medias, ... you choose from in WordPress back-end
    while creating a Group of Fields).
  * [ACF Pro](https://www.advancedcustomfields.com/pro/) same as ACF :
  * Will work with
    [Flexible content](https://www.advancedcustomfields.com/resources/flexible-content/)
    and premium stuff like that (repeater, gallery, ...).
  * Will pull the content attached to the
    [options page](https://www.advancedcustomfields.com/add-ons/options-page/).

* [x] [WP-API-MENUS](https://wordpress.org/plugins/wp-api-menus/) which gives
      you the menus and menu locations endpoint.

* [x] [WPML-REST-API](https://github.com/shawnhooper/wpml-rest-api) which adds
      the current locale and available translations to all post types.

```

</details>
