### ISSUE TITLE
Prettier 1.9.0 TypeError: Cannot read property 'useTabs' of undefined

### ISSUE THREAD

**Issue by ImadBoumzaoued** [prettier/prettier#3399]
**Prettier 1.9.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbm9fPz8Aeiz8ABVbABFbJHxC6AV9Gzh8akMoOggAW394tganDN19RJa+C0MYIQA6VHIafAYBoeG6huaGDwAqfABGAFEAagB2N2GYCABlGGpw5kXZuAAHEkMwOAYs-n5h57pNrJxmSUFBN3T4rUOLF4gAeOg4ez4MC3TSaAByhiacB4CmIZEoNHoCnwuBguh4wAABgBNaz4QxsfD2HDaA7UBLoJoAIyc+AAJMBGS0XESXPhLNY7I5qITBdUHE4XAA+AGZfCgzQnaDMaVc0KcZjDTQkHD3Bj4AAMklW+D2BwAqlcrk4AMKGUyLfCbKRsMJcbW6-Wrc0QAAyEAA7naHQ8PC5QVkldQVbLAX4WG7NcMEHRNBQcEMGBI-vgAPwCECF-ClRVXer4JUATwJwGAkHI1FKSn40irChcMokhcjmnLUGl+BcGT8oLgTTj-Bg6qTcDkw58MEj47j8q5DG0ulg-3jmQLgleIBHmVKgiCggXx8jEPs0rSPigLhA4hAECuuGgmmQoEpMcDAAVKQQL8UEMewIBwOhnxAB0YGQIwTDMEBmTqMAAGsOEOcswDOZATnQJDGjAeDjFMF9wlMagYH-OpmCaQwSMQl8ACtNAADwAIVQjCYEOJE4D9cI4EYsjX3QGArnEgAmESkPLahKOQZDDGZGtoGgq5TlgDM6CGZAAA5jRATSIFMCg6iuJTNLgSjHGgtgAEd0BwNgaMMOiGKQBDRNMJocDw6gCJfbQuF0ABFdAIHgWSXxgFSdL0pApNiuodDOW1mnopSoGgYSX2qPIVJA-C4E7IA)
```sh
# Options:
--use-tabs
```

**Comment by sampi** [comment]
Also able to reproduce by having ```json
{
	"useTabs": true
}
```
as my `.prettierrc`

**Comment by Nimelrian** [comment]
Can confirm, just blew a few of our CI builds

**Comment by ikatyang** [comment]
Sorry, my fault. Opened #3401 to fix it.

**Comment by duailibe** [comment]
Fixed in 1.9.1!
