### ISSUE TITLE
Comment in destructuring pattern in wrong place

### ISSUE THREAD

**Issue by mariusschulz** [prettier/prettier#3400]
**Prettier 1.9.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtA9AKkwEsBzKCAJzkwRiKswFsBDGMAC031wBpMSKEAK4AHAIx8BwkQCYAupgC8mKiTgAPALKsOAbhA8QEEXXTJQIikVgB1IgBMY7ZAA4ADIZjMARncfOkGUM0axIAGzgARSEIeGQAM2YwtDhPCmYiMNCAYQhGFmQQcig4AxBvdLAAazgYAGURZjBQ5BgKIVSQACs0dQAhSpr65kY4ABlrUqRE5M7GihSKQu8fAE8w6DKUxiJW9s6hFIAVHzQEpJTDa0WYAAV0kgLpi86qAEchejh75kfmc9mhksEBSNnSIkKJQAbnAloZmBRBAB3W4IhBnFBlewQMAAy4gZgYPGdYQwERCGAyYkAX2pQA)

Prettier currently moves the inline comment in the following destructuring pattern behind the comma. If would be nice if the comment remained where I put it (to signal that the omission was intentional).

**Input:**
```jsx
const [/* ignore entire match */, group1, group2] = regexMatch;
```

**Output:**
```jsx
const [, /* ignore entire match */ group1, group2] = regexMatch;

```

**Expected behavior:**

Unchanged input.

**Comment by duailibe** [comment]
Thanks for the report! We're already tracking this bug in #1013, and https://github.com/prettier/prettier/issues/1013#issuecomment-287094920 explains why this happens.
