### ISSUE TITLE
Closing parenthesis of multi-line intersection/union type

### ISSUE THREAD

**Issue by mariusschulz** [prettier/prettier#3403]
**Prettier 1.9.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAyjAQ3mwF5tgAdKbG7AZwAsCAnOAEwAVmItn0lsBKGioBfbADJsACiq1sAH3LY2ASzphmqgLaqoQmAIogAYgHkzxgNzYAZhAgChabKLm0lwFes069BoxAAIQBBACVrbAAjFidhV3caT28NLV19WEDQgC1ImIAvOJdxKgBKKyoQABoQHhhVaDpkUBZuAHcOFgQmlAIANwhVNmqQAjoYZFsCABs6OBqo5gIwAGs4GFwMZb0Ac2QYZgBXeZA2CDBJmbmavTm+LgId7QJL2ZOAKzoADyCl1fXcARtHAADJ6OCva61Q4wDAwgBMkJOW2Yd2QqEwcFSqgwExqGC0sAA6kMYAxkAAOAAM+O4cyJSww6IJWLgzD6EJqrAAjodVKwHk8Xkgpm8anNdPsjic6LtpnAAIqHCDwJE1QhRElsMnIAAs6qWqmmuwAwhBtM90VBoJyQIc5gAVAhRHqiuaiURAA)
```sh
--parser typescript
--tab-width 4
```

**Input:**

```tsx
type State = {
    sharedProperty: any;
} & (
    | { discriminant: "FOO"; foo: any }
    | { discriminant: "BAR"; bar: any }
    | { discriminant: "BAZ"; baz: any } 
);
```

**Output:**

```tsx
type State = {
    sharedProperty: any;
} & (
    | { discriminant: "FOO"; foo: any }
    | { discriminant: "BAR"; bar: any }
    | { discriminant: "BAZ"; baz: any });
```

**Expected behavior:**

```diff
type State = {
    sharedProperty: any;
} & (
    | { discriminant: "FOO"; foo: any }
    | { discriminant: "BAR"; bar: any }
-   | { discriminant: "BAZ"; baz: any });
+   | { discriminant: "BAZ"; baz: any }
+);
```

**Comment by duailibe** [comment]
Fixed in 1.9.2!
