### ISSUE TITLE
Sort/Dedupe ES Module Imports

### ISSUE THREAD

**Issue by sparty02** [prettier/prettier#3408]
Not sure how controversial this will be, but this is a proposal to include prettier rules for dealing with ES modules (ESM).  Over time, imports can quickly become unorganized, especially when using an "auto-import" feature that several editors have.

To demonstrate, note the following changes below:

1. Imports were "deduped", e.g. @angular/material had two entries, which were combined into one import
2. Imports were sorted, according to their package name
3. Relative imports were sorted _after_ external module imports
4. Existing formatting of line-breaking named imports has been maintained from what happens today.

While these rules may be opinionated, it's better than nothing!

**Input:**
```js
import { FlexLayoutModule } from '@angular/flex-layout';
import { AppComponent } from './app.component';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { MatButtonModule, MatIconModule, MatSelectModule } from '@angular/material';
import { MatSidenavModule } from '@angular/material';
```

**Output:** 
```js
import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { FormsModule } from '@angular/forms';
import {
  MatButtonModule,
  MatIconModule,
  MatSelectModule,
  MatSidenavModule
  } from '@angular/material';
import { AppComponent } from './app.component';
```

**Comment by SimenB** [comment]
Quite a few feature requests for import sorting already. There was some talk about being able to plug in transforms, not sure if they led anywhere

**Comment by duailibe** [comment]
Yeah this has been discussed before, see https://github.com/prettier/prettier/issues/2277#issuecomment-311216366
