### ISSUE TITLE
Prettier couldn't go through the directories recursively [error] EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by RIP21** [prettier/prettier#3409]
Hi guys. 
I assume that it's not probably connected to the prettier. But I gave up already to fix that somehow, cause it's the only node based tool which doesn't work with GLOB pattern for now.

Mac OS High Sierra
Latest node and npm.
prettier: 1.9.0

```
prettier --write {scripts,config,bin}/**/*
```
throws lot's of errors in my face like:
```
bin/react-scripts.js 58ms
config/custom-react-scripts
[error] Unable to read file: config/custom-react-scripts
[error] EISDIR: illegal operation on a directory, read
config/env.js 26ms
config/jest
[error] Unable to read file: config/jest
[error] EISDIR: illegal operation on a directory, read
config/paths.js 31ms
config/polyfills.js 6ms
config/webpack.config.dev.js 34ms
config/webpack.config.prod.js 44ms
config/webpackDevServer.config.js 9ms
scripts/build.js 17ms
scripts/eject.js 33ms
scripts/init.js 26ms
scripts/start.js 8ms
scripts/test.js 6ms
scripts/utils
[error] Unable to read file: scripts/utils
[error] EISDIR: illegal operation on a directory, read
template/README.md 819ms
```

In the same, this script returns all required files in the deeply nested paths with no arguing.
```javascript
require('glob')('{scripts,config,bin}/**/*', (e, f) => console.log(f));
```

I have prettier of the same version (1.9.0) both installed globally as well as the prettier in the package.json.

I tried to call it with `sudo` and tried to reinstall it etc. not much of a result.
Running it through the npm scripts or directly result in the same output.

Node and npm are the latest and were installed using brew. I'm under administrator profile.

**Comment by duailibe** [comment]
Can you try running with quotes around the list of files? i.e.
```
prettier --write {scripts,config,bin}/**/*
```

**Comment by RIP21** [comment]
@duailibe 
The result is following:
```
prettier --write "{scripts,config,bin}/**/*"
bin/react-scripts.js 67ms
config/custom-react-scripts
[error] Unable to read file: config/custom-react-scripts
[error] EISDIR: illegal operation on a directory, read
config/custom-react-scripts/config.js 7ms
config/custom-react-scripts/customizers
[error] Unable to read file: config/custom-react-scripts/customizers
[error] EISDIR: illegal operation on a directory, read
config/custom-react-scripts/customizers/babel-plugins.js 1ms
config/custom-react-scripts/customizers/loaders.js 7ms
config/custom-react-scripts/customizers/plugins.js 2ms
config/custom-react-scripts/options
[error] Unable to read file: config/custom-react-scripts/options
[error] EISDIR: illegal operation on a directory, read
config/custom-react-scripts/options/extract-text-plugin-options.js 3ms
config/custom-react-scripts/options/postcss-options.js 3ms
config/custom-react-scripts/utils
[error] Unable to read file: config/custom-react-scripts/utils
[error] EISDIR: illegal operation on a directory, read
config/custom-react-scripts/utils/map-object.js 4ms
config/custom-react-scripts/webpack-config
[error] Unable to read file: config/custom-react-scripts/webpack-config
[error] EISDIR: illegal operation on a directory, read
config/custom-react-scripts/webpack-config/style-loader.js 13ms
config/env.js 20ms
config/jest
[error] Unable to read file: config/jest
[error] EISDIR: illegal operation on a directory, read
config/jest/babelTransform.js 2ms
config/jest/cssTransform.js 2ms
config/jest/fileTransform.js 1ms
config/paths.js 27ms
config/polyfills.js 5ms
config/webpack.config.dev.js 32ms
config/webpack.config.prod.js 36ms
config/webpackDevServer.config.js 11ms
scripts/build.js 28ms
scripts/eject.js 45ms
scripts/init.js 34ms
scripts/start.js 15ms
scripts/test.js 6ms
scripts/utils
[error] Unable to read file: scripts/utils
[error] EISDIR: illegal operation on a directory, read
scripts/utils/createJestConfig.js 9ms
```
So it means that it's format all the stuff, but still error out on dirs.
Will use with `|| exit 0` for now in npm scripts, but it's still quite messy.

**Comment by duailibe** [comment]
@RIP21 Can you tell the exact command you are running?

**Comment by RIP21** [comment]
@duailibe exactly as you told me.
`prettier --write "{scripts,config,bin}/**/*"`

**Comment by suchipi** [comment]
Please try using single quotes instead of double quotes (yes, really)

**Comment by RIP21** [comment]
@suchipi same result.

**Comment by duailibe** [comment]
@RIP21 Thanks, the reason I asked is because we've seen some problems when people ran prettier through a npm script and had the quotes problem..

I managed to reproduce the error, not sure what the bug is yet

**Comment by RIP21** [comment]
And BTW I'm using zsh if it can affect anything.

**Comment by duailibe** [comment]
To clarify: running without quotes IS a problem because prettier receives the paths as arguments and not the glob:

```js
// console.log(process.argv)
[ 'node',
  'prettier.js',
  '--write',
  'src/a',
  'src/a/a.js',
  'src/b',
  'src/b/a.js' ]
```

But even with quotes I reproduced this bug (using the `**/*` pattern):

[ 'node',
  'prettier.js',
  '--write',
  'src/**/*' ]

**Comment by duailibe** [comment]
We should be passing `nodir: true` here:

https://github.com/prettier/prettier/blob/e09359d2428bdac40c30cd6a82c92a627d1e1d05/src/cli-util.js#L284

**Comment by RIP21** [comment]
Yay. Glad that it's actually an issue of the prettier and not mine :)
And that i didn't spend the time of the maintainers for nothing :)

**Comment by azz** [comment]
Workaround should be to provide extensions in the glob. `**/*.{js,css,json}`

**Comment by azz** [comment]
Be very careful with globs ending with  `*` because Prettier's will format unknown file formats as JS.

**Comment by RIP21** [comment]
@azz thanks. But I wanted to use wildcard only because  prettier supports lots of things now, so I just plan to use match everything except htmls and few others via .prettierignore.
But sure, I will put {css,md,js,json} instead. And maybe some others with handler.
Glad I found a bug :)

**Comment by duailibe** [comment]
Fixed in 1.9.1!

**Comment by Dimitreee** [comment]
Same issue today

**Comment by j-f1** [comment]
@Dimitreee Please open a new issue and explain what’s happening in more detail.
