### ISSUE TITLE
Line wrapping union of flow's exact object type results in syntax error

### ISSUE THREAD

**Issue by eqyiel** [prettier/prettier#3417]
The playground is throwing an error like `ReferenceError: constants is not defined` for the flow parser, so I'll do this manually:

**Prettier 1.9.0**
```sh
# Options (if any):
--single-quote
--trailing-comma 'all'
```

**Input:**
```jsx
// @flow

import type { $Admin } from '../../../models/Admin';

export default function fetchAdmin({
  connection,
  selectProps,
}: {
  connection: *,
  selectProps: {| email: string |}
    | {| facebook_id: string |}
    | {| google_id: string |},
}): Promise<$Admin> {
  return new Promise((resolve, reject) => {
    connection('admins')
      .where(selectProps)
      .asCallback((error, [user]) => {
        if (error) {
          return reject(error);
        }

        if (!user) {
          return reject(new Error('Admin does not exist'));
        }

        return resolve(user);
      });
  });
}
```

**Output:**
```jsx
// @flow

import type { $Admin } from '../../../models/Admin';

export default function fetchAdmin({
  connection,
  selectProps,
}: {
  connection: *,
  selectProps:
    | {| email: string |}
    | {| facebook_id: string |}
    | {| google_id: string |},
}): Promise<$Admin> {
  return new Promise((resolve, reject) => {
    connection('admins')
      .where(selectProps)
      .asCallback((error, [user]) => {
        if (error) {
          return reject(error);
        }

        if (!user) {
          return reject(new Error('Admin does not exist'));
        }

        return resolve(user);
      });
  });
}

```

**Expected behavior:**

Should not format the second argument of the default export like this because it's a syntax error (the leading pipe character is not valid).

**Comment by eqyiel** [comment]
Looks like this is #1197

**Comment by duailibe** [comment]
@eqyiel Actually #1197 has nothing to do with this.

But nevertheless, I don't understand what you mean by

>the leading pipe character is not valid

Looks fine to me: [flow.org/try link](https://flow.org/try/#0C4TwDgpgBAJAggEwLYEsB2UC8UDeBfAbgCgiIAPMAewCdgoEIAzAQwFcAbOx1tAY2BSUMjCMF4ALRKjQAKHEShReQtBH6C0AGgVQAzhHZrgABWqUwu7XgBcuHcrSr1Q2wCpti-Yf6nzu6zqKAD64IRBIzCjstrrA1OgA5lBBeIHJoVAsvBAARpSUANYA+igIMXGJyamKwRkJ+QmGJWV6FWhJKVYAlLa+qPoAPPDI6AB8dorUoqzUGKoA7lB9KPoyMlO6lOwAbhCaUFMAVkZdWOPyNUoqRhoyAOTMI2i6d11pigB08+IQUzJeRl8Fjel0+zF0AGFmOx2DlmLwCmtfmZqPsANqsfTUAC6p0w53eNRQjCgMmRNFOF1BlymwBmGCORjJ1BRXWI1MUqUJimJpIAhJjfpTuTVafSDhBjvwZAsoABRFk0e5SdD0SgQXRQNCUOjkFbAV5skVcjkSumzCWbHYQGSC6hG6l4B1QJ3EPBAA)

**Comment by duailibe** [comment]
Also, playground is back up [link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAhgE9M59h8ASAQQBN1Up8BffAMxwnXwHIA6PgHoBwoegi04AGwDOgugyg8A3AB0o6uAA9sefJLYBDAK5SCbY1DAxU0dnBhgAFgsYAKYOvz5IUKHGtbKAAaL3wZaQCYAAVOTBlQqGYkcjDff0DoFIAqRO8IqSjYiHikMO8AH3IquHRDVCkUmRgcRgBzfArmcs7q9kMwOAAjCAgAawB9VFomlvbO7qZvXuAqttG2wqmZ8LmoDq7E5gBKFOKGCIAeGnpGAD5UpZwHYxwmfwB3fHPUCLc3Z4yCBSABucGC+GeACsosd8ABeB6eJbedJRIJuHiGW5QGQ8Y49bx8D5OODPNwFIpxGQElHLPiGGQAYUMUikQwGY3+ZM4OAhAG1jBEcABdOGIx7LKX4VBsfBuHm4OHI6XS54wV5MaFRBU4XnHNR0qWLQnLWXygCEQrJytNUvVmshcBh1jcn3wAFE9bhMa4mLQIHAZPgoBACNpfjB8Qa7Sx1LGHW8nUDQXA3NacDGjSws94TobmCBgiASjZoDJkKBDN6PtFqwgKyhDCCINMiyBGTBkEZZOCQEMcJyHABlTADdrIFrGPsBsDd1kRYuMYUxQdtOrz3vFqEyLQAIUHYDGI8M6DgABlGHBN4uS8YYJh7wAmSc4afFsc4YXIEBsKQQD520wVpYAAdWmGAnGQAAOAAGD9OAiUDB0wH9gKDMkwXbZ4AEdjFQZ5YkMddDBvPsIgYV93xAGR2kKABFYww2vJAe1vGBDCGcDaEg5An2LFp6ikdomS4DcUFDfx22tAAVTjGzYuBmGYIA) and 2nd output is fine (which means the output is valid Flow syntax)

**Comment by eqyiel** [comment]
@duailibe my bad, it looks like my build was failing due to a linter error that actually doesn't have anything to do with flow: https://github.com/gajus/eslint-plugin-flowtype/blob/master/.README/rules/space-after-type-colon.md

Thanks for checking it out.
