### ISSUE TITLE
Feature request: Drop curlies and return from single-expression arrow functions

### ISSUE THREAD

**Issue by jbr** [prettier/prettier#3425]
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAlAAgLwD5PCYBOcMArkVJjEWXJgL4gA0IEADjAJbQDOyoAIZEiEAO4AFYQn4pBANwhcAJixCDeMZADNBAG15xWAIyKCwAa1IBldua5QA5shp1WyiGB37DrB4aIYCTNHAFtBbwMjEAArXgAPACEzSxtBULgAGQc4SN82Mhh2QoAmPOi7IgDkEGNBYwBPPWg1diIHGAB1FRgAC2QADgAGVjaIQ06zdhq2uAD5XNYSAEcyLhJgwTCIpF0o1kNQrhdaaN4HRz04AEUyCHhy1hh67uU+5BKnsy49C4BhCChcI1KDQRYgMiGAAq9Vke0MDAYQA)

**Input:**
```js
() => { return true }
```

**Output:**
```js
() => {
  return true;
};

```
**Expected (desired) behavior:**
```js
() => true;
```

Is this something that prettier would welcome? I'd happily make an effort at implementation if so.

**Comment by duailibe** [comment]
Thanks for the report! This is not something Prettier actually does. We just focus on formatting the code (pretty much only dealing with whitespace and semi colons only), not changing this type of stuff. As a rule of thumb, we try not to change the AST, see the [rationale](https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about) section on the docs.

This would suit better as an ESLint rule.

**Comment by duailibe** [comment]
Actually there is an ESLint rule! https://eslint.org/docs/rules/arrow-body-style

**Comment by jbr** [comment]
Awesome, thanks! I didn't quite understand the boundaries of prettier's scope. The ESLint rule looks perfect
