### ISSUE TITLE
Babylon misplaces comments around class constructors

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#3429]
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAZSmI1IAsIYAZCAczbmz2AB0ZeUPAWikY2AK5gYOABT9Bw4djjxYAS2gAFLpoAmSPFAkBbAEZc8AXjwBWPACo8ANgAMjvAEZXPgDR4AegC8FRhidSEMMnwAM3UANzg8EwiJeFIFISVSGjpGGABJWC544kJDY3NLGwBmdydvP0DgnNoGJiMIZJwkmHpiIThE7ABPPDqMgSyASh5M4QBfTKWoEF8QCAwYTShSZFBibGwIAHctQ4Q9lGJ4iHU9NZBo5Biy0jh1s2xiMABrVUoUTAETYyHEEg+ID0EDALzekIi71wWm+bBMxDhhHe6wAVqQ0AAhb5-AHEExwZgROCY7EbNIYNIAJhpkKi2CRyBAZmIZhGhGgjww2AiMAA6vc+sgAByudZCiDvUXfDCcoVwJGJR4qACOEnUKhRxDRGKQryxkPeKTBkgtIMIcAAihImNTTfD1mEzOK9JKkIyPd91IQQQBhCAmdGcqDQanrCTvAAqPKuZveCwWQA)

**Input:**
```jsx
export class SnapshotLogger {	
  constructor(	
    retentionPeriod: number = 5 * 60 * 1000, // retain past five minutes	
    snapshotInterval: number = 30 * 1000, // snapshot no more than every 30s	
  ) {	
  }	
}

```

**Output:**
```jsx
export class SnapshotLogger {
  constructor(
    retentionPeriod: number = 5 * 60 * 1000,
    snapshotInterval: number = 30 * 1000 // snapshot no more than every 30s
  ) {} // retain past five minutes
}

```

**Expected behavior:**

Note that if you run it through the flow parser it works fine.

For context, I'm trying to figure out if we could use babylon on Facebook codebase. I've ran prettier on the Nuclide codebase with babylon instead of flow and there's only a few files that are not the same and it's always because of some comments that were misplaced like this.

**Comment by vjeux** [comment]
And the other case where it seems to happen:

**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOizAQ3gAIBeY4AHSmOIDMMAbBAgWzgCU4BzOADyTVatAPQj6jCAHdGGWAFoo-GPNlLiWANZwYYNAE9FAV0aN5+AE5zuSCHTpDhcjDAwFGAZTgELegAo+bLgMzFBsnDz8xAA+0Y60vDAAYkws7CmM8BYAFAAOFhAAVnBgMDg+YH4FxaUANMT5RSVlWEYARgAmGBbNEBb6AJS11AC+1CC1IBC5rtBYyKA+BVIBPVDzKAQAbhAYHRMgBPjIdO5YcJNtFgRg2jAeuTfWyDAWRhcgHRBgJ2cfcucLDAqgRuKwCL9GOdJoUsHwAELXW46DzhAAycjgkOhUyMMFyeIATNiPo8LIDkCA2gQ2vpJFADvk5DAAOp7dDIAAcAAZJo1zizrrlKfk4ICtljJj0AI5GbpwEFgiFIU5Qj7nVgYF5vdXWZgARSMEHgJMmhDabI6HKQhLN1yY1gAwhBWODKVBoJKQEZzgAVGkbVXnEYjIA)

**Input:**
```jsx
this.state = {
  filenameRegex:
    // flowlint-next-line sketchy-null-string:off
    initialSearchParams.filenameRegex ||
    getFilenameFilter(project.arcProject, project.subdirectory),
}

```

**Output:**
```jsx
this.state = {
  // flowlint-next-line sketchy-null-string:off
  filenameRegex:
    initialSearchParams.filenameRegex ||
    getFilenameFilter(project.arcProject, project.subdirectory)
};

```

**Comment by vjeux** [comment]
Good news is that I've ran babylon through more code and those two issues seem to be the only one. This is really exciting :)

**Comment by duailibe** [comment]
FTR the comment misplace happens for any class method, not just constructor :)
