### ISSUE TITLE
Please unlock issue #1080 (Provide way to use single quotes in jsx)

### ISSUE THREAD

**Issue by iansinnott** [prettier/prettier#3437]
#1080 was locked a while back by @rattrayalex. I totally understand not wanting to be bombarded with new issue notifications as a maintainer, but I'm suggesting it be unlocked because:

* Users of Prettier who have found new workarounds for the issue can't share them with everyone else
* The issue may get more 👍 / 👎 which provides passive information on the community's interest, without generating noise
* The issue is marked as "help wanted" so anyone who is not yet a contributor might want to ask questions about what direction to take in making a PR

Even if that issue gets marked as a wontfix there's still conversation to be had that can benefit the wider community.

**Comment by rattrayalex** [comment]
Hmm, I think we'd prefer PR's to workarounds, and further demonstration of
interest isn't likely to inspire a maintainer to file a PR.

If you're interested in submitting one, give it a shot -- we'd probably
rather answer questions about approach once there's already a draft up.

It's likely to be moderately straightforward. Look for JSXAttribute in
printer.js.

**Comment by iansinnott** [comment]
Hey @rattrayalex thanks for the quick response. There was already a PR by @trotzig (https://github.com/prettier/prettier/pull/1084) made for this but it was closed down before you reopened #1080. So let's reopen that PR? 😄 

The workarounds are for users in the meantime before a decision is reached on whether or not to include this quotes functionality. And if it's eventually decided not to include this feature then people will need the workarounds.

**Comment by josephfrazier** [comment]
@iansinnott another option is to port [`--jsx-single-quote`](https://github.com/arijs/prettier-miscellaneous/pull/23) from `prettier-miscellaneous`

**Comment by azz** [comment]
Don't think it's a good idea to add this. I can't think of a single reason why single is better than double quote beyond personal preference, which Prettier is built to eliminate. https://github.com/prettier/prettier/issues/1080#issuecomment-289585626

**Comment by iansinnott** [comment]
Good point @josephfrazier (and thanks for updating the title). Yeah that option works great in prettier-miscellaneous.

@azz Prettier was built for such a purpose but the project does currently support options based solely on personal preference (semicolon, quotes, bracket spacing, etc) so it seems there's precedent for such a thing. But more importantly configuration like this would helps to avoid fragmentation of the community (like the aforementioned [prettier-miscellaneous](https://github.com/arijs/prettier-miscellaneous)).

Anyway, my purpose in opening this issue was not to reopen discussion in a separate place, but rather to allow the discussion to continue on the original issue and come to a conclusion, whichever way it goes.

**Comment by duailibe** [comment]
@iansinnott I personally don't like the argument of "other options exist" very much.. if we follow that we can make a case for every single style option people suggest.

To be fair, some of the options exist for historical reasons and I believe they were likely to be denied if they were suggested today.

**Comment by azz** [comment]
> the project does currently support options based solely on personal preference (semicolon, quotes, bracket spacing, etc)

Post hoc ergo propter hoc. The three options you mentioned, along with `tab-width`, `print-width` and `trailing-comma`, have been in Prettier since the beginning, pretty much inherited from [recast](https://github.com/benjamn/recast) (of which Prettier is a fork). They should not be considered "precedent" because they were never really "requested" so much as they were a part of the [original documented API](https://github.com/prettier/prettier/tree/HEAD@%7B2017-01-10T15:20:53Z%7D#api). 

The semicolon option was (requested way back in in #12) added to allow a huge number of people following styles such as `standard` to adopt Prettier. I really doubt changing `"` to `'` for JSX falls into that bucket.

**Comment by rattrayalex** [comment]
Sorry, @iansinnott , I would personally be open to reopening #1084 but judging by reactions from other maintainers on this thread it would be closed again. I'll close this if that's okay. 

It seems `prettier-miscellaneous` supports the feature you're after, so if this is a deal-breaker for you, I'd suggest going there instead.

**Comment by amsul** [comment]
As much as I _**love**_ prettier, I still find this to be a really odd default convention.

If the config specifies `singleQuote`, why would JSX not respect that? Especially when you consider that JSX !== "HTML in JS". 

Kinda unfortunate that a library that's supposed to be used to ensure "consistent style" has this form of inconsistency..and the suggested solution is to use a fork instead of fixing it in the actual library itself.

**Comment by duailibe** [comment]
@amsul I'm sorry you find that odd, but the "consistent" is supposed to mean that, given an AST, it will always print your code the same way, regardless of your original code; it's not supposed to mean that we'll print a similar parts the same way through your code.

That means Prettier will always print strings in JSX attributes with double quotes and the rest as you specified. This might seem silly but Prettier applies some normalizations your non-JSX strings (i.e. [remove unnecessary escapes](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAXnQHRDnAcgBUALASwGd0BHAVwngMPQBMI5KpCZ0o44rdJzCoADnDwBuHFAzZCBPGSq0GTAiDYdq-QcMqiJAGnQAjOr2YwK1dpyjXmhKSGMgIYmOWiVkoVAAnQIgAdwAFIIQ-FFQANwhyVjc0ShhkADNUABtKOHczQNQwAGs4GABlMWLyKABzZBhAunyQdjBMnLz3WrzAmHCiuoBbVE7c1oArSgAPACEi0vKK1GG4ABlauHHuj0sxSwAmHdbqwL7kEDNUMwBPbOgUsUDamAB1JJtkAA4ABndnhA8m8imJLs9OHBAnFtu5AnB6OR4YNUCMxkgshN3HlhuRGs1WpRanVsnAAIrqbYYrqtGA3D6sL5IQ7uJqocjZYkAYQgw1Glyg0FhIDoeWINximLyAF9pUA)) while if you do those in JSX [it would break](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIAOAThPgLwA6IAogM5gCG+cuMAFpjbudyAI4CuEeN0qVcAegB8IADQgSMTNBrJQ9QsQDuABXUIVKetgiZ0skPRoxkAM3oAbGnDkAjQvTABrODADK+D0woAHNkGEJ+ZxB0CDBbByc5IKdCGG13YIBbenjHKIArGgAPACF3Lx9feky4ABkguFzE+X4YfFaAJiaogMIU5BAXehcAT3tocyIgmAB1UzZkAA4ABjkiCCcZ93wBojgU7Ea5QjgBTBP0+iycpDs8uSdMzDCIqJog4Ps4AEVBeG65DBhnN0AskB1Ae5MPYPgBhCCZbIDKDQI4gfhOAAqwwMdycAF98UA) your code.

**Comment by iansinnott** [comment]
Thanks for taking the time to respond everyone. I'm not trying to change anyone's mind on this. But #1080 is still locked, so those of us who have already expressed interest in this issue are prevented from sharing solutions with each other and anyone else who might come across the issue.

**Comment by rattrayalex** [comment]
@iansinnott do you have a solution to share?

**Comment by amsul** [comment]
I'd just like to say, I realize the goal of Prettier is quite ambitious..and would essentially stop these kinds of discussions from ever happening (which is a great goal!)

However, I'm curious about what the maintainers think is considered "in scope" of what Prettier will and won't tackle.

Considering JSX is just sugar on top of JS, why should Prettier bother applying extra semantics (and exceptions to rules) for it by adding a unique way to handle strings? In my opinion, **that** is an additional configuration which just cannot be "unconfigured".

In fact, a configuration that actually seems to spawn from trying to bring XML conventions into JS.

Does that mean these silly discussions will pop up every time the community introduces new syntactic sugar on top of JS that bring conventions from other languages?

**Comment by duailibe** [comment]
Hi @amsul!

For Prettier, I don't think it matters if JSX is sugar or not. We only care about the syntax, which is spec'ed at http://github.com/facebook/jsx and that syntax _requires_ extra semantics (which I have just showed above).

**Comment by amsul** [comment]
@duailibe I understand your point about the extra semantics required for normalization - which is simply resolved by adding `{}`.. but that's independent of `'` vs `"`.

Anyways, I've said my final thoughts above - I hope it registers with people enough to fix this!

@duailibe I appreciate you taking time to give responses 🙏

**Comment by iansinnott** [comment]
@rattrayalex yup (run prettier output through string replacement). 

But even if I can share this solution it doesn't help anyone else share theirs (or improve on existing ones). That's why I suggest unlocking the original issue. 

Also, perhaps the issue should be closed if the prettier community decides against single quotes in JSX. Either way though, keeping it locked makes it difficult for those of us that care about this to help each other.

**Comment by ljharb** [comment]
Can’t comment on the original issue, but huge 👎 for this - jsx is html, html has double quotes, and JS has single quotes. Please do not change the default behavior.

**Comment by j-f1** [comment]
> jsx is html

Not really:

```jsx
// This references `Component`
<Component notANumber="2" invalid=100% yesYouCan=<DoThis /> {...notHTML}>
  <!-- this is not a comment -->
  a
  {/* no space rendered here */}
  b
</Component>
```

**Comment by ljharb** [comment]
Conceptually, it is, even though it follows slightly different semantic rules. It’s certainly not JS, by any metric, so “consistency between JSX and JS” is a brittle strawman.

**Comment by j-f1** [comment]
@ljharb: @gaearon echoes my thoughts very well in https://github.com/airbnb/javascript/issues/269#issuecomment-135201861.

**Comment by ljharb** [comment]
Fair. But all those confusions are or can be addressed by linter rules (ones the airbnb config enforces), which is a much more reliable signal than “it has single quotes”.

**Comment by gaearon** [comment]
FWIW I've long stopped caring about things like this and I can't recommend that enough

**Comment by georgeawwad** [comment]
I for one welcome our new double quote JSX overlords

**Comment by ravencrest** [comment]
I've created a pull request that addresses this [here](https://github.com/prettier/prettier/pull/3839).

**Comment by Kovensky** [comment]
@azz Users of `standard` absolutely have single quotes in their JSX. The rule there still is to use single quotes unless you need to write an `'`, at which point you use double quotes.
