### ISSUE TITLE
Ignore empty scss files instead of writing a newline?

### ISSUE THREAD

**Issue by ghost** [prettier/prettier#3440]
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEsZF6AVgQAeAISmz5CkrbgAGVU4R1NMbRgsSIAmML1lMgtkEAIwAiIMLDJVGAB1DhgAC2QADgAGLMpRPKksFOy4C2ZQjDI4AEdtXHbrEjsHJEEnDFFbXE0dPQJVNSE4AEVtCHhJ3QwYEnEC9mLkGI2pXCFZgGEIW3sUpoBWLm1RABUtxmHRAF93oA)

```sh
# Options (if any):
--single-quote --parser scss --trailing-comma es5
```

**Input:**
```scss
[blank line]
```

**Output:**
```scss
[blank line]
\n
```

**Expected behavior:**
No newline (`\n`)

**Comment by lydell** [comment]
Prettier makes sure that all files it formats ends with a single newline. Why would you want an exception for SCSS files with only a comment in it?

**Comment by KSuttle-cng** [comment]
There is no comment in it. There is literally nothing in it. It's not that I want an exception for SCSS. I'm pointing out an SCSS-specific issue.

**Comment by duailibe** [comment]
I can reproduce this:
```
> touch file.css && git add file.css
```

After prettier:
```diff
diff --git a/file.css b/file.css
index e69de29b..8b137891 100644
--- a/file.css
+++ b/file.css
@@ -0,0 +1 @@
+

**Comment by KSuttle-cng** [comment]
It's present in the playground link above as well.

**Comment by lydell** [comment]
For empty _JS_ files, Prettier does _not_ add a newline. I didn't know it worked that way. Since that is the case for JS, it should work the same for SCSS as well.

**Comment by lydell** [comment]
Or is JS wrong? Tough question.
