### ISSUE TITLE
Expose config.resolveConfigFile in API?

### ISSUE THREAD

**Issue by darahak** [prettier/prettier#3451]
We have this [issue](https://github.com/prettier/prettier-atom/issues/270) with `prettier-atom` where it keeps using the cached config, even when the user modified their `.prettierrc` file.

We need the config file path if we want to watch it and clear the cache if it gets updated. 

I wanted to check with you, if you see any downsides/caveats in exposing this method or if you think there could be a better solution.

Thanks!

**Comment by josephfrazier** [comment]
I think it's a good idea, there was a tad of discussion about it here: https://github.com/prettier/prettier/pull/2760#discussion_r145536461

**Comment by darahak** [comment]
Thanks @josephfrazier! Totally missed this convo in the search results...

**Comment by duailibe** [comment]
Hm, that's an unfortunate issue and I don't oppose this solution but I think a "Reload option" on prettier-atom could solve the issue.

Changing a config file is generally a set and forget it action.. I'm not sure how useful it is to keep watching this file. But that's your call and again I don't oppose exposing this method

**Comment by darahak** [comment]
@duailibe I agree a "force reload config" command would be nice too, but ideally I would like the user to not have to do anything.

A watcher might consume too many resources for this kind of event.
A good compromise could be checking modification dates on config files when appropriate? (e.g. text editor focus + eligible file type)

We could have both.

**Comment by SavePointSam** [comment]
I’d be happy to look at posting an update to PR to accomplish this. I was going to follow the pattern that Prettier#formatWithCursor uses. By creating a Prettier#resolveConfigWithFile that will encapsulate the tradition response in an `options` property and a `file` property that contains all the information an editor may need to watch configurations reliably.

**Comment by duailibe** [comment]
FTR this was done in #4364, will be included in next release!
