### ISSUE TITLE
Formatter removes escaped single quotes and replaces entire string with double quotes

### ISSUE THREAD

**Issue by trevorgk** [prettier/prettier#3453]
Fantastic tool - I love it. Especially the 1.9.0 release with arrowParens which brings us closer to being able to use it. I have encountered a small problem and am wondering if it is known or expected behaviour.

**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLGAKA5AdVQG3wAJJYBDVKIgdiIB06sA6ABQCc4BnBGAfV4BGEAB4MsROPjgBbHpywAaIhgCURALwA+IsDpUiBuMIAOcMJgDubMsdNsmAM0oATbKw7dY-IcKwqVTDAQTAAWZABucExSUADmMCEY1CoA3HoAvqkgCiAQxjCo0JzIoGRsbBAWLGUIxSgREKjO2SBknDDIDmT43DkC1mAA1nAwAMrGZGCUscgwbACucDnOEGCd3b1oUNxsMOxksdJk6z1LIABWnMIAQgPDY2SyADKUcCebEPMwxl8ATO9nCZsHbIEACMgCACe+GgLWMbEoMDwzgSyAAHAAGHLwiDcHDWYyg+FcOBsSItDgAR3mqA4+0OxyQXVOOW40lQswWZ040ykAEV5hB4ACcjAIcjUUhfqLrARpgBhCDSI6gqDQN45ebcAAqELqzO46XSQA)

**Input:**
```jsx
it('Will contain 7 \'.Present__box\' elements', () => {
    expect(wrapper.find('.Present__box')).to.have.length(7);
});
```

**Output:**
```jsx
it("Will contain 7 '.Present__box' elements", () => {
  expect(wrapper.find(".Present__box")).to.have.length(7);
});

```

**Expected behavior:**

That the formatter would not change the quotes, as they are valid.

We have specified { "prettier.singleQuote": true } but the formatter seems to prefer double quotes and removes the escaped quotes. This throws a linting error.

**Comment by josephfrazier** [comment]
I think this is expected behaviour, see https://prettier.io/docs/en/options.html#quotes

**Comment by trevorgk** [comment]
Hi Joseph, thanks for the quick response and the link to the documentation.
