### ISSUE TITLE
Wrong formatting of braces in complex condition

### ISSUE THREAD

**Issue by marvinhagemeister** [prettier/prettier#3456]
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAFBAEYBWmAhAUQK5QAmc2AllHE5gGQ8A6UTCXIUAdLny0GzVhy68BQ4ZlES8ASkwAfbYNKUxZAIYAnGnUyMW7Ttz6rDJ0xo0BuEABoQEAA4w2dGRQM1MIAHcABTMENGQQYwA3CDYmLwSMZGxjABs0OG8yU2MwAGs4GABlXxKOAHNkGFN6ApAmCDAs3PzvDnzTGEjiuoBbYy681oo0AA8AIWKyisrjEbgAGXkJnp96GF89gCZt1prTfviTMgBPHOh031MOGAB1VJgAC2QADgAGb0eEHyL2Kvnijzg-UScHSpjgAEd6Gw4UNjKNxkhspNvPkRmxGs1Wmh6jk4ABFegQeAnbwwYxkN5MT7IQ604psHL1ADCEBGY3iUGgMO89HyABV6XFMd04ABfWVAA)

**Input:**
```jsx
const foo = (obj !== undefined &&
  (obj.foo !== undefined &&
    obj.foo) ||
(obj.bar !== undefined && obj.bar));
```

**Output:**
```jsx
const foo =
  (obj !== undefined && (obj.foo !== undefined && obj.foo)) ||
  (obj.bar !== undefined && obj.bar);

```

**Expected behavior:**
```jsx
const foo =
  obj !== undefined && (
  (obj.foo !== undefined && obj.foo) ||
  (obj.bar !== undefined && obj.bar)
);

```

**Comment by duailibe** [comment]
I don't see how this expected is better than the output, is there a typo somewhere?

I could see how this one could be considered better:
```js
const foo =
  (obj !== undefined &&
    (obj.foo !== undefined && obj.foo)) ||
  (obj.bar !== undefined && obj.bar);

**Comment by marvinhagemeister** [comment]
@duailibe Oh wow, after looking at it again I see that I got confused with the braces.

Closing as non-issue :)
