### ISSUE TITLE
Markdown: Preserve code blocks within list items

### ISSUE THREAD

**Issue by infotexture** [prettier/prettier#3459]
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgMIAsCGUA5nJjBJgJ4QCuATprhALakAmAlnXGOXZUgA6UYZjHixYNsOEAmLABkOAZxhlcpSLAQxlQkVAkSANsswBaY8JAAaEBAAOMDtGXJQ+OnQgB3AAqeCG4o+ABuEBxstiD4qsgAZvimcHYARnT4YADWcDAAyg6ZHMTIMHQ0KSBsEGAJScqVxQ10MH4ZRMz4dcl2AFbKAB4AQhnZuXn4rEpQcN0NdrQwDjQwsnOVhXTNyCCddFnVPlDRDnTFMADqkTC4yAAcAAx2pxANFxkOO6dwzaGzdtwAI40LhwNr4DpdJCJHogBrMDilcqVZTFIjGOAARRoEHg6zsMHwqSubBuyFkBIyHGMaOwLE6Oyg0H+IBoDQAKkTgjCGgBfXlAA)
```sh
--parser markdown
```

**Input:**

Code blocks may be nested within list items per the original [Markdown syntax for lists](https://daringfireball.net/projects/markdown/syntax#list):

> To put a code block within a list item, the code block needs to be indented twice 
> — 8 spaces or two tabs:

```markdown
1. Change to your home directory:

········cd

2. List the contents:

········ls -l

```

**Output:**

Prettier strips the 8 leading spaces and replaces them with 3 to align with the list item content:

```markdown
1. Change to your home directory:

···cd

2. List the contents:

···ls -l

```

This treats the nested code blocks as subsequent paragraphs in the list items rather than as code blocks:

1. Change to your home directory:

   cd

2. List the contents:

   ls -l

**Expected behavior:**

The original input should either be preserved, indented with tabs or fenced to ensure the nested code blocks are rendered properly:

1. Change to your home directory:

       cd

2. List the contents:

       ls -l

## Subsequent runs change result

If the nested code blocks are indented with 2 tabs (rather than 8 spaces), they are initially converted to 7 spaces. If the same file is saved again, the 7 spaces are converted to 3 spaces.

## Fenced code blocks as workaround

If the nested code blocks are fenced, the input is preserved and output is generated as expected:

~~~markdown

1. Change to your home directory:

   ```sh
   cd
   ```

2. List the contents:

   ```sh
   ls -l
   ```
~~~

**Comment by ikatyang** [comment]
It seems to be [remark mis-parsing](http://astexplorer.net/#/gist/866b3eb0af642c9c60b635cb52b11bc4/3a58a22acc487107b5f7ecbd1c73611bd761d964), could you [raise an issue there](https://github.com/wooorm/remark/issues)?

<details>
<summary>Prettier playground</summary>

**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgCoAsCWAzpkZpFIfgCZwBOcVJUNsDZENAOlN5n-3zBVu3DDgLFS5SjXqN8zBPEaQuPKAP5CRUMXlKkoEGOwrU6bBS2Xs1vTUJAAaEBAAOMfNELJQAQ1paCAB3AAUAhB8UPwA3CGpnED9CGGQAMz8AG0I4FwAjWj8wAGs4GABlNyKFAHNkGFoAV1yQKggwdKyclwUc2hhQwpqAWz9O7JaAK0IADwAhQpKy8r9huAAZBThx7tdGmDd9gCZ6ppaq2j7kEFHaYrbgqES3WgUYAHVqGFxkAA4ABhcLwgOXehTc1xecD6MW2LnoAEdGvh6IM-CMxkgMhMXDlhvhTs1cbVMnAAIqNYzbLFdFowPx5T5Ub7II4uBp+fCZWoAYQgw1G1yMUDhIEaOWwDKi2JyAF9ZUA)
```sh
--parser markdown
```

**Input:**
```markdown
1. This is considered indented code

        cd

1. This is considered indented code

       cd

1. This is not considered indented code

      cd
```

**Output:**
```markdown
1. This is considered indented code

       cd

1. This is considered indented code

   cd

1. This is not considered indented code

   cd

```

**Second Output:**
```markdown
1. This is considered indented code

   cd

1. This is considered indented code

   cd

1. This is not considered indented code

   cd

```

</details>

<details>
<summary>CommonMark playground</summary>

[link](http://spec.commonmark.org/dingus/?text=1.%20This%20is%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20%20cd%0A%0A1.%20This%20is%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20cd%0A%0A1.%20This%20is%20not%20considered%20indented%20code%0A%0A%20%20%20%20%20%20cd)

![image](https://user-images.githubusercontent.com/8341033/33861696-328c9460-df1a-11e7-9d3b-7e4e43d23cb4.png)


</details>

**Comment by infotexture** [comment]
@ikatyang I'm not quite sure where the boundaries lie between remark and Prettier in this case, so I'm not entirely certain how to describe the issue for the remark maintainers. 🤔

Is it that `remark` does not reliably recognize the 8-space indentation as a nested code block within the list item, so Prettier trips up later and writes the code as a regular paragraph instead?

**Comment by ikatyang** [comment]
Actually, the 8-space indentation is not correct, from [CommonMark spec](http://spec.commonmark.org/0.28/#indented-code-block):

> An indented code block is composed of one or more indented chunks separated by blank lines. An indented chunk is a sequence of non-blank lines, each indented **four or more spaces**. The contents of the code block are the literal contents of the lines, including trailing line endings, minus four spaces of indentation. An indented code block has no info string.

I think the indented codeblock in list should be the current indentation (e.g. `1. ` = 3, `11.` = 4) + 4 whitespace, see [CommonMark playground](http://spec.commonmark.org/dingus/?text=1.%20This%20is%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20%20cd%0A%0A1.%20This%20is%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20cd%0A%0A1.%20This%20is%20not%20considered%20indented%20code%0A%0A%20%20%20%20%20%20cd%0A%0A11.%20This%20is%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20%20cd%0A%0A11.%20This%20is%20not%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20cd%0A%0A11.%20This%20is%20not%20considered%20indented%20code%0A%0A%20%20%20%20%20%20cd%0A%0A), the number matters:

![image](https://user-images.githubusercontent.com/8341033/33915175-e9163f52-dfdc-11e7-918f-d78e9ee941db.png)

---

> Is it that remark does not reliably recognize the 8-space indentation as a nested code block within the list item, so Prettier trips up later and writes the code as a regular paragraph instead?

It does not recognize the 7-space (3+4=7) indentation as a nested code block within the list item, we followed the CommonMark spec, so the parsed remark AST should be same as the result in the CommonMark playground.

**Comment by infotexture** [comment]
So it seems there are 2 aspects to this:

1. **CommonMark diverges from the original Markdown syntax for code blocks in list items**\_(where 8-space indentation is indeed valid & explicitly recommended)_.

    CommonMark still treats this as a code block (as shown in your [CommonMark playground example above](http://spec.commonmark.org/dingus/?text=1.%20This%20is%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20%20cd%0A%0A1.%20This%20is%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20cd%0A%0A1.%20This%20is%20not%20considered%20indented%20code%0A%0A%20%20%20%20%20%20cd%0A%0A11.%20This%20is%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20%20cd%0A%0A11.%20This%20is%20not%20considered%20indented%20code%0A%0A%20%20%20%20%20%20%20cd%0A%0A11.%20This%20is%20not%20considered%20indented%20code%0A%0A%20%20%20%20%20%20cd%0A%0A), but after applying its (3+4=7) indentation rule it treats the 8th space as part of the code block.

2. The `remark` parser apparently fails to recognize CommonMark's (3+4=7) indentation for nested code blocks within list items

**Comment by chriskrycho** [comment]
There's what looks to me to be a closely related issue (which I can open in a new, dedicated issue if desired/appropriate) where code blocks in footnotes are fully de-indented.

This text...

~~~markdown
Some text.[^fn]

[^fn]: Here is a footnote which includes code.

    ```rs
    fn main() {
        println!("this is some Rust!");
    }
    ```
~~~

...gets transformed into this:

~~~markdown
Some text.[^fn]

[^fn]: Here is a footnote which includes code.

```rs
fn main() {
    println!("this is some Rust!");
}
```
~~~

**Comment by ikatyang** [comment]
@chriskrycho 

That's a different issue, I didn't realize footnote definitions can be multiline since they're not in CommonMark/GFM spec. Could you open another issue for it?

**Comment by chriskrycho** [comment]
Will do!

**Comment by chriskrycho** [comment]
[Done!](https://github.com/prettier/prettier/issues/3786)

**Comment by kachkaev** [comment]
I also find the current indenting rules quite painful. After converting a document that contains a very long numbered list with some setup instruction, the structure got lost.

IMO It'd be more reasonable to have one extra space in the numbered lists. Yes, that creates a not very neat double spacing after a period, but in return you don't end up with triple spacing in front of the nested items. I'm not sure about other editors, but VSCode does not know what to do with three spaces and either overindents or underindents a block of text when I try to edit it with select + tab.

I think it'd be more reasonable to offset both numeric and bullet-point lists by four characters including spaces. This way the markdown's source looks clean, GItHub's and GitLab's preview are not broken and the indentation in the editors is guaranteed to work. What is also superimportant is that __changing the type of the list does not cause a huge git diff because two spaces has suddently turned into three or vice versa.__

It'd be great if Prettier team could reconsider list indentation in markdown. It's still not too late! We've got years ahead of us and so fixing things when they are not is right is extremely important.
