### ISSUE TITLE
Prettier adds tabs to already 'prettiefied' files

### ISSUE THREAD

**Issue by Mohamed3on** [prettier/prettier#3461]
I had run prettier on a repo I'm working on before with the below options:
```sh
# Options (if any):
--single-quote --print-width=80
```
Now suddenly even though my options haven't changed, the code is getting reformatted again (I have it on save in VSCode).  I thought it could be a problem with the VSCode extension, but running:
```sh
prettier C:\path\to\file --write --single-quote --print-width=80
```
Also reformats the file again, mainly cutting previously 'fine' lines into separate lines.
**Note:** In the playground it outputs the expected code.
**Note:** This only happens with prettier >1.9.0

**Input:**
```javascript
 hasSubcategories =
            category.subcategories && category.subcategories.length !== 0;
```

**Output:**
```javascript
   hasSubcategories =
                        category.subcategories &&
                        category.subcategories.length !== 0;
```

**Expected behavior:**
```javascript
 hasSubcategories =
            category.subcategories && category.subcategories.length !== 0;
```

**Comment by lydell** [comment]
Hi! Could you make a reproduction in the playground? I started [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAFgQwM4GUCuARmJvAOYQBOAlnNqgLwA6Uqb7HbJ5VAngHTYi3OBRp1UAMkmoRYgUOKlRVWtn4AbBGRjpUAQgYNUABgDcIADQgIABxjVo2ZKEyVKEAO4AFNwmcomABuENQAJlYgODDIAGaYGthw1oSUmGAA1nAwuLbp1FBkyDCU+MkgYRBgcQlJ1gVJlDDeaWQAtpg1ieUAVtgAHgBCaZnZuJhtcAAyBXBddTb4MLZLAEzFpeV5lI3IIISYhLwa0JG2NLAA6uG6yAAcJtbnEEmXabZ753RwlEFz1pQ4ABHfDUQEtTDtTpIeLdaxJNrUDZleEFMhaACK+Ag8Hm5Rgh2uYVuSFW1hKmGoGjRAGEIG0OnsoNB-iB8EkACqHAKwpIAXz5QA) – could you finish it? (Note that you can press “Show options” in the bottom-left corner if you need to set more options.)

**Comment by Mohamed3on** [comment]
Yep, it doesn't reformat it in the playground.

**Comment by lydell** [comment]
I see! Feel free to post back here when you have figured out which tool(s) the bug resides in!

**Comment by CiGit** [comment]
I suspect you have an `editorconfig` file somewhere.

**Comment by Mohamed3on** [comment]
Yes! @CiGit. I don't know what it does, though it was there before too.
Here's the config:
```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 4
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
insert_final_newline = false
trim_trailing_whitespace = false
```

**Comment by CiGit** [comment]
```
indent_style = space
indent_size = 4
```
This also configures prettier since 1.9
But in your case, it seems indented more than 4 spaces.

**Comment by Mohamed3on** [comment]
Thank you! I've removed those and it's working fine again now.

**Comment by gnapse** [comment]
I wonder why prettier reads the configuration from an editorconfig file. The whole point of prettier is to enforce a common style for a project across all people collaborating on it. By reading settings from `~/.editorconfig` it is prone to behave and format code inconsistently across different computers.

We needed to add to our `~/.prettierrc` all the default configuration values explicitly (well at least the ones affecting indentation) because of this.

**Comment by lydell** [comment]
@gnapse See #42.

**Comment by SimenB** [comment]
Reading configuration outside of the root of the project is sorta weird in Prettier's case, isn't it? As mentioned, it leads to potential inconsistencies between machines

**Comment by azz** [comment]
Yeah I don't think that was ever intentional. Is there a reliable way to get project root?

https://www.npmjs.com/package/find-project-root

**Comment by thorn0** [comment]
@azz The `.editorconfig` file itself has the `root` option to mark the project root. Doesn't prettier respect this option?

**Comment by thorn0** [comment]
@gnapse Just commit `.editorconfig` to the project and the format will be consistent everywhere. Asking why prettier uses it is like asking why prettier uses `.prettierrc`. The only difference is that `.editorconfig` is also used by other tools (IDEs etc), it contains shared settings.

**Comment by SimenB** [comment]
I don't want prettier to read _any_ config file outside of the project root, I don't care if it's `.prettierrc` or `.editorconfig`

**Comment by thorn0** [comment]
@SimenB Well, you're covered. Just commit both `.editorconfig` with `root = true` and `.prettierrc` to your project root.

**Comment by gnapse** [comment]
There is still a problem however. This is not explicitly mentioned upfront to newcomers like me. And then it happens that a team member happened to have a `~/.editorconfig` in their home directory, and all of a sudden, prettier (which we have set up with husky and lint-staged to format everything on commit) started to introduce in our repo code that was violating our `.prettierrc`.

Not sure what can be done here, but this behavior is very confusing and if there's no way around it, then the instructions for always including a `/.editorconfig` with `root = true` in the root folder of projects using prettier must be mentioned in the `README`.

Also, still seems odd to me that having prettier following the instructions of `.editorconfig` is desirable. What happens if they are at odds what the `~/.prettierrc` file states? Or with the options passed to prettier in the script that invokes it in a given project? Why have to potential sources of truth? Even if there's a priority for one of these configuration sources, this leads to confusion.

**Comment by josephfrazier** [comment]
@gnapse, thanks for clarifying the situation where a repo doesn't include an `.editorconfig`, but a user's home directory does, and Prettier counter-intuitively respects it. I agree that a repo shouldn't have to include an `.editorconfig` with `root = true` to use Prettier, and https://github.com/prettier/prettier/pull/3559 should fix this.

> Also, still seems odd to me that having prettier following the instructions of `.editorconfig` is desirable. What happens if they are at odds what the `.prettierrc` file states? Or with the options passed to prettier in the script that invokes it in a given project? Why have two potential sources of truth? Even if there's a priority for one of these configuration sources, this leads to confusion.

As was mentioned [above](https://github.com/prettier/prettier/issues/3461#issuecomment-353731012), the reasoning for respecting `.editorconfig` (overridden by `.prettierrc` and CLI arguments, of course) is covered in #42 and the related issues/pulls linked to/from it. You can find my main argument for it in https://github.com/prettier/prettier/issues/42#issuecomment-327217226

**Comment by thorn0** [comment]
I'd argue that prettier should know nothing about such vague entities as "repo", "project", etc. There is a lot of possible setups that people use, and the current behaviour of prettier is already flexible enough to cater for all these possible setups. Please don't break it. Also an important feature (one of the key features probably) of EditorConfig is that its configs are parsed the same way by all tools (which includes traversing up the FS of course). Let's stay compatible with other tools.

> There is still a problem however. This is not explicitly mentioned upfront to newcomers like me. 

So it's merely a matter of good documentation.

**Comment by gnapse** [comment]
@thorn0 I personally did not have this file, so advising to "simply don't keep this config file" is not enough. It just happened that a person new to our project started to commit code formatted differently that what we had expected, and after confirming it was not a problem of husky git hooks not being configured, we realized this was the reason.

And yes, if at the end prettier does not need or shouldn't be aware of the concept of a repo or a project (a proposition with which I think I don't agree but I also don't have any strong arguments against) then the need for this safe guard in the form of a `.editorconfig` with `root = true` should be better and more prominently documented. Especially in the context of documenting prettier setups that lead users to believe they're guaranteeing that prettier will reformat all their code no matter what, such as configuring it on [a git precommit hook](https://prettier.io/docs/en/precommit.html).

And also, if I may add, I get your point that a global `~/.editorconfig` will affect editors and other tools, so it makes sense to respect it as well. But I'd argue in that case that prettier should at least warn the user that it found such a globally affecting config file, and that it will follow its lead, perhaps with an accompanying url to a page documenting how to avoid this, etc. (Kind of what react does in its warnings in the browser js console 😉) cc. @josephfrazier 

If needed, I can volunteer to help in any PR to amend the documentation accordingly.

**Comment by thorn0** [comment]
A precedent from the Visual Studio docs: https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options#override-editorconfig-settings
