### ISSUE TITLE
API: Accept array of paths

### ISSUE THREAD

**Issue by montogeek** [prettier/prettier#3462]
Hi!

I have been using prettier since it exists but only in the standard way, as a precommit-hook etc.
But now I need to use it in an internal tool, by using its API, I found that `prettier.format` only accepts a string, it would be great if it could accept an array of path as strings: 
`prettier.format(['path/file.js', 'path/file2.js'])`, this would make things easier.

After reading the source code I found that this already exists in the `cli-util.js` file (https://github.com/prettier/prettier/blob/master/src/cli-util.js#L306).

Would you accept a PR that add this functionality to the API? It would use `formatFiles` internally.

**Comment by azz** [comment]
Possibly what you really want is to expose the CLI as an API? (Include config resolution, ignore files, etc)

**Comment by suchipi** [comment]
If we add this, I think it should be a different function, instead of overloading `prettier.format`.

**Comment by jahredhope** [comment]
This sounds like [eslint's CLIEngine](https://eslint.org/docs/developer-guide/nodejs-api#cliengine).
Which would be a great feature in my opinion.

Something like this:
```js
const PrettierCLIEngine = require("prettier").CLIEngine;

const cli = new CLIEngine({
  usePrettierrc: false,
  ...
});

const report = cli.executeOnFiles(['path/file.js', 'path/file2.js']);

```
