### ISSUE TITLE
Support more Markdown options

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3463]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAeQE4BM7Zy7oAyAlgM4wUA6UdABgLRMR4FFMA2lM6kUKgENYDOnQCMAOnQBJSTJ4BrOAvQArAK5U12slADmahtLH0oLJuKjNW7Qrm690+sIQC2CGGbUAhTTB0AEwyMAAWlHQAzIq8dAAsMpRQAOSBUACsMgIUvF7WGACqUGz4DqS8tOa2PFRMAEaaXFxwfClMKT4W6LXU6ADuZOHouEIUYXBVTOhChOhwY2QE6DAQKwCeAA6q3QDaAFRgQ0IwZNDoUHBERPsAutaW1jW8DU0tbQDUndYf6I187iE63qO1+sgGIj4DA+XUe1RYvVezVa6BS+2+5n26DY6EBwJ2WPCcH4mmwhFgIzgADMhE0YAAaOhYhj7LoYACi7k2YUWVUYLDgXJ5uQoqIA+hi6GKqRAIGL0GKxfVZoqFYrlQAvRVih4sJ4CoW81Horr7GUQLH7fbK7BW9BW61CDUOgpyKD4WAnM7mflMGBCepMQa4YZBWEzHpxKDodDTfQe+C4Ogx6ZUMjNFzurxEZMx2O4tjE+PZ4h0aYlPjF2A58xw33+wPB4bxU0R3q5mNYquJjv29BpjPdmt5kd99yFzMJmtYiuTkvWOgYACKmgg8D5gggnnQux4UCUt12uAgmnqLSYAEdV-BbugJoRrEeT2e4Jfr3Bbkg7zAYJsKEgAHoALgAAPIQuRaKRIHcdAaBAc04N1Kx4SYXJDHPK81zgLoKC3Yld30A9djQgwMPfW97x2OhiP0UjX0wm8vzCH8-0A4CwIguAoK3VFzRSOgQHpEAIE2U5oAoZBQFmbAIH6AAFWYEAklAhAANwgMhcEEkAxhgZAaS4Cg4CE+psCEMAVBgABlTZzNo5AYGwTRjJAY8wH0oRDJc-QjOwGA5LMgxAQ8ryhPUCgQN8MyLNaKzwLgchLhCoyhJPX8AiCZKXNs7BfOQEBAWwJRj36KBtM2bB9BgAB1TTwmQAAOAAGISKogIzqrMzZ8oqyYCFUuBtMIK8yEIAKhCCoQsqEoz3DIBynJckiWhXLDppABtapDMJkCCITHKEdNaIAYS3YKUBKJKhO0OAABUA2UgyjIAX2eoA)
```sh
--parser markdown
```

<details><summary><strong>Input</strong>:</summary>

```markdown
# Ordered Lists

`--ordered-list constant`

1. I
1. like
1. just
1. using
1. `1.`

---

`--ordered-list increment`

1. But
2. this
3. list
4. isn't
5. consistent

# Unordered Lists

`--list-bullet '-'`

- lists with dashes
- are easier to type
- [*citation needed*]

---

`--list-bullet '+'`

+ but maybe
+ I want `+`

---

`--list-bullet '*'`

* or maybe
* the current default,
* `*`

# Emphasis

`--emphasis '_'`

_foo_ __bar__ ___baz___

---

`--emphasis '*'`

*foo* **bar** ***baz***

# Indentation

`--tab-width 2`

- a list
  - indented
  - still indented
    - more indented 
- not indented

---

`--tab-width 4`

* a list
    * indented
    * still indented
        * more indented
* not indented


# Quotes

some [link][double-quote] here

[double-quote]: https://example.com "foo"

---

`--single-quote`

some [link][single-quote] here

[single-quote]: https://example.com 'foo'

```

</details>

<details><summary><strong>Output</strong>:</summary>

```markdown
# Ordered Lists

`--ordered-list constant`

1. I
1. like
1. just
1. using
1. `1.`

---

`--ordered-list increment`

1. But
2. this
3. list
4. isn't
5. consistent

# Unordered Lists

`--list-bullet '-'`

* lists with dashes
* are easier to type
* [*citation needed*]

---

`--list-bullet '+'`

* but maybe
* I want `+`

---

`--list-bullet '*'`

* or maybe
* the current default,
* `*`

# Emphasis

`--emphasis '_'`

_foo_ **bar** **_baz_**

---

`--emphasis '*'`

_foo_ **bar** **_baz_**

# Indentation

`--tab-width 2`

* a list
  * indented
  * still indented
    * more indented
* not indented

---

`--tab-width 4`

* a list
  * indented
  * still indented
    * more indented
* not indented

# Quotes

some [link][double-quote] here

[double-quote]: https://example.com "foo"

---

`--single-quote`

some [link][single-quote] here

[single-quote]: https://example.com "foo"

```

</details>

**Expected behavior:**

Output is the same as input, with flags set as specified in `` `code` `` blocks

**Comment by lydell** [comment]
Prettier tries to have as few options as possible on purpose. When markdown support was implemented, we made some research to find the best compromise between the most popular formatting choices, readability and git diff-ability. Thanks for the super nicely written issue though! Feel free to comment here if there's something specific you'd like to discuss, or if I missed something.

Note to maintainers: We should really write that option philosophy part of the docs we have been talking about...

**Comment by j-f1** [comment]
Thanks for getting back so quickly @lydell!

> Prettier tries to have as few options as possible on purpose. When markdown support was implemented, we made some research to find the best compromise between the most popular formatting choices, readability and git diff-ability. Thanks for the super nicely written issue though! Feel free to comment here if there's something specific you'd like to discuss, or if I missed something.

👍 I agree with this. However, a few sections of my (excessively long, sorry) document have some additional things I’d like for consistency:

```md
Both of these are allowed:

1. First
1. Second
1. Third

----

1. First
2. Second
3. Third
```

IMO Prettier should choose one of these and make you stick to it. Similarly, no style is enforced for emphasis (both `*foo*` and `_foo_` pass through unchanged). I’m not necessarily asking for an option. I’m just asking for consistency in some form.

Also, several of the proposed options (`--tab-width` and `--single-quote`) already exist, and it’s currently confusing since they don’t apply to Markdown code.

**Comment by lydell** [comment]
Interesting!

Can you provide an example of how `--tab-width` and `--single-quote` could be utilized in markdown? (Sorry if you already showed that in the OP and I didn't find it.)

Regarding how ordered lists are numbered, there's some logic around how Prettier chooses between incrementing and all-same-number, I think, but I don't remember the details. cc @ikatyang 

> both `*foo*` and `_foo_` pass through unchanged

That's not true. Perhaps you've encountered some edge case bug?

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqadUAID6MDuEOIANCBAA4wCW0AzsqAIYBOLE+ACqwgykwDcI1ACakQTOjGQAzJgBs6cMgCMWTMAGs4MAMoUN1KAHNkMFgFdlIERDCyFSskaUsYndcYC2TB4usAVnQAHgBC6lo6ukxecAAyRnB+TuQWMBRpAEzJ1gYsrsggPiyatvhQ4hQsRjAA6qIwABbIABwADGRVEEq16hSFVXCuAklkLHAAjhbU4x5M3r5Icv5kSl7UZpbWdEbG8nAAihYQ8DlkMEwq9SJNyJnn6tTyuwDCEF4+hVAY4hZKACqXPjLJQAX1BQA)
```sh
--parser markdown
```

**Input:**
```markdown
*one* _two_
```

**Output:**
```markdown
_one_ _two_

```

**Comment by j-f1** [comment]
> Can you provide an example of how `--tab-width` and `--single-quote` could be utilized in markdown? (Sorry if you already showed that in the OP and I didn't find it.)

`--tab-width 2`

```markdown
- foo
  - bar
    - baz
- quux
```
`--tab-width 4`

```markdown
- foo
    - bar
        - baz
- quux
```

`--single-quote`

```markdown
[Link Text][foo]

[foo]: https://example.com 'title'
                           ^ here^
```

not `--single-quote`

```markdown
[Link Text][foo]

[foo]: https://example.com "title"
                           ^ here^
```

**Comment by lydell** [comment]
Wow, I didn't even know one could put a title at the end of a link reference definition! Never seen it in the wild. I guess that's a valid place to normalize quotes.

`--tab-width` is a bit trickier though, because in many places 4 or more spaces results in a code block. So we'd have to clamp it?

**Comment by ikatyang** [comment]
The git-diff friendly ordered list (all-same-number) is applied if the second number is `1`.

---

For the `--tab-width`, what would you expect for the following case?

```md
- foo
  
  bar

  baz
```

IMO, it'd be weird if we applied `--tab-width 4` in this case:

```md
- foo
  
   bar

   baz
```

So we currently do not respect `--tab-width` at all.

---

For the `--single-quote`, yes, it's a valid case, but I originally thought it's considered a part of HTML so I just enforce it to double quote style, seems we should respect the `--single-quote` option there.

**Comment by j-f1** [comment]
Title formatting added in #3481.
