### ISSUE TITLE
Disable printWidth or add exceptions to the rule

### ISSUE THREAD

**Issue by nechita** [prettier/prettier#3468]
The printWidth is a very useful rule to keep the lines readable, but in typescript we have certain areas where we want to avoid the rule because of it doesn't really help us that much.

Is there a way to disable the rule entirely or make it ignore certain patterns?

We want to skip the lines containing the import statements and the constructor.

**Comment by azz** [comment]
In prettier, print width is not a rule, it's actually an input into the algorithm used to print code. Due to this it is impossible to turn off. You can set it to a very high number (not recommended) or use `// prettier-ignore` comments to disable prettier on a chunk of code.

**Comment by nechita** [comment]
Can you please give me an example on how to discard prettier on a chunk of code?

**Comment by azz** [comment]
Checkout the docs :) https://prettier.io/docs/en/ignore.html

**Comment by nechita** [comment]
Sorry for being annoying about this, but I was wandering if there is a way to create some  rule in the ignore file to match different language constructs to be ignore with regex or something?

Wouldn't hurt to add to the docs if there is this possibility of creating regex rules for formatting or not.

**Comment by duailibe** [comment]
I think that'd be easier as a ESLint autofixable rule and run `prettier-eslint`.. that would mean: your code is formatted by Prettier and then ESLint rules can change the code.

You could match `import`s and join the statement in a single line.

**Comment by caub** [comment]
It's not really practical, with this strict `printWidth` you end up with things like

```js
storiesOf("Multi-select", module)
  .add("chips", () => <StarWarsMultiSelect onChange={action("onChange")} />)
  .add("grouped", () => (
    <StarWarsMultiSelectGroup onChange={action("onChange")} />
  ));
```

where I'd prefer

```js
storiesOf("Multi-select", module)
  .add("chips", () => (
    <StarWarsMultiSelect onChange={action("onChange")} />
  ))
  .add("grouped", () => (
    <StarWarsMultiSelectGroup onChange={action("onChange")} />
  ));
```
for consistency/readability

Changing just slightly `printWidth` for this case, would impact all the codebase

Too bad `printWidth` is a core settings, I'd prefer avoiding it

**Comment by j-f1** [comment]
@caub `printWidth` is a necessary part of how our printer works. We print code until we either get to a linebreak between statements or `printWidth` characters.
