### ISSUE TITLE
Reformatting a Markdown link where the URL includes with "&currency=" breaks the URL

### ISSUE THREAD

**Issue by stefanwille** [prettier/prettier#3470]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#.....)

**Input:**

In a Markdown file:

```markdown
[Test](http://localhost:8080/test?language=DE&currency=EUR)
```

**Output:**
```markdown
[Test](http://localhost:8080/test?language=DE¤cy=EUR)
```

**Expected behavior:**
The URL should remain untouched.

**Comment by ikatyang** [comment]
This is a bug in `remark`, see remarkjs/remark#307.

As a temporary workaround, you may have to add a `<!-- prettier-ignore -->` comment.

**Comment by stefanwille** [comment]
Thanks for the info
