### ISSUE TITLE
Format CSS hex colors in JS

### ISSUE THREAD

**Issue by Kerumen** [prettier/prettier#3472]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEY1swXk2AB0pNMAnOAEwGEIAbCCpTAcgGIAzLgBn95sANKXIAjBgFc49Ji3YcBvAGLLhpAL4ghICAAcYAS3TJQAQwoUIAdwAKFhGmQgzANwiHq2lxmRczDGhwOmIUZmAA1nAwAMp64YZQAObIMBTSOtQQYH4BQTqJQRQwtmFJALZmuYHBIABWaAAeAEJhkdExZuVwADKJcNX5upIweiMATIO18RRFzmJmYgCeTFDeehSJMADqnjAAFsgAHLw6GxBB22F6zhtwRa4DOlQAjpKGVKVmFVVI-jU6ILlQypdK1NCJJIMOAARUkEHgUx0MEWu2oB2Q42RYUMDEh9HKlWcUGgTxAkiCABVFk4-nk4BoNEA)

**Input:**
```jsx
const css = {
  redColor: '#ff0000',
  blueColor: '#0000FF',
}
```

**Output:**
```jsx
const css = {
  redColor: "#ff0000",
  blueColor: "#0000FF"
};

```

**Expected behavior:**

In an ideal world, I expect prettier to format my CSS colors hex strings written in my JS.

**Comment by k15a** [comment]
This is not really possible. How should we figure out that they are CSS variables?

**Comment by Kerumen** [comment]
I know that this would be tricky. Maybe a regex would handle it?
This library exists https://github.com/segmentio/is-hex-color and use the following regex:

```
/^#[a-f0-9]{3}([a-f0-9]{3})?$/i
```

**Comment by duailibe** [comment]
@Kerumen that works to match a hex color but we can't know for sure that's meant to be a hex color in a JS context.

We'd need to know we're in a CSS context, like below:

```js
foo = css`color: #FF0000`;
```

Otherwise, it'd be too risky to change the content of a string.
