### ISSUE TITLE
How are people using prettier in practice?

### ISSUE THREAD

**Issue by avanderhoorn** [prettier/prettier#348]
I love the idea of this project and what its doing. Linting is great, but this takes it one step further. That said I'm wondering where people are fitting this into there workflow? Are running this on all changed files pre checkin, only when you want to format a block of code, as part of your build script or something else? I like the idea of a consistent format across the whole code base but am interested in how other are doing in practice.

**Comment by kpuputti** [comment]
I'm interested in this as well.

I just made a separate ESLint configuration based on eslint-config-airbnb that turns off all the rules that deal with style. We currently only have a separate NPM script command that needs to be run manually to reformat the whole app.

Has anyone integrated Prettier to a CI workflow? I'm thinking a setup where the CI fails if running Prettier would yield any changes. Or would this make any sense?

**Comment by vjeux** [comment]
Some more discussions here: https://github.com/jlongster/prettier/issues/238

Once we have a good printer, the focus is going to be on integrations. My belief is that we need a "defense in depth" approach where at each stage of the developer workflow we need some integrations: in the editor as a shortcut and on save, as a lint rule, as a github bot like danger and as a post-commit stage where it gets reformatted automatically if it didn't in the earlier phases.

But, staging is important. Right now prettier still outputs invalid JavaScript sometimes and outputs some non optimally formatted code in a lot of ways, so we need to focus on that first, otherwise none of the other steps matter :)

**Comment by rcsole** [comment]
Hi! I just thought I'd share how we're using it:

We thought of a few options: git hooks, asking people to do it when they submit a PR, and having a CI push when there are differences. In the end, we decided for a mix of the last two. We have included `npm run format` (which runs prettier) as part of our `npm test` script. Now, you'd hope people would run tests before they submit a PR but that's not always the case, so we also have our Jenkins job on master check for differences and publish said differences if there are any. We found this to be the easiest way to enforce the usage of it.

Our Jenkins job looks kind of like this:

```sh
npm test && \
git diff --quiet && \
git diff --staged --quiet || \
git commit -am "chore(prettier): formatted from jenkins"
```

I hope that's helpful to someone, we are also happy to take criticism! We haven't really encountered a point where prettier has generated invalid JS yet, though. It's also worth mentioning that changes only get committed if tests pass, and we have close to 100% coverage.

**Comment by lydell** [comment]
Possibly crazy idea for those who already have an eslint workflow set up:

What if it was possible to create an eslint plugin for prettier. Then, running `eslint` would fail if a file is not formatted with prettier, and `eslint --fix` would fix would it. I’ve found that I’d like to run prettier on the same set of files as in eslint in a few projects.

**Comment by hawkrives** [comment]
@lydell: @not-an-aardvark posted in https://github.com/jlongster/prettier/issues/165#issuecomment-275304898 that they'd made [`eslint-plugin-prettier`](https://github.com/not-an-aardvark/eslint-plugin-prettier)

**Comment by lydell** [comment]
@hawkrives Thank you so much for that link! Exactly what I was thinking, it seems.

**Comment by ravicious** [comment]
> I just made a separate ESLint configuration based on eslint-config-airbnb that turns off all the rules that deal with style.

I'd like to recommend [create-react-app ESlint config](https://github.com/facebookincubator/create-react-app/blob/master/packages/eslint-config-react-app/index.js). [It doesn't include style rules](https://github.com/facebookincubator/create-react-app/issues/808#issuecomment-252928970), so it's works well with prettier. I see that [at the moment some import rules are disabled](https://github.com/facebookincubator/create-react-app/blob/8964dd6f134a71494a3271c26e017717e7941e9b/packages/eslint-config-react-app/index.js#L159-L187), so you may want to enable them. But other than that, the config is ready to use!

**Comment by lydell** [comment]
@ravicious You might also want to check out https://github.com/lydell/eslint-config-prettier :)

**Comment by vjeux** [comment]
Let's close this issue as it is not very actionable. We can open a new one for specific actions to be taken.

**Comment by MartinX3** [comment]
I want to use it in Angular 4, installed it with npm and runned into this error

```
ERROR in ./node_modules/prettier/bin/prettier.js
Module parse failed: /home/martin/Dokumente/Development/Projekte/internPredic8/shop-api-graphql/website/frontend/node_modules/prettier/bin/prettier.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| 'use strict';
| 
 @ ./src/app/app.component.ts 12:0-45
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

webpack: Failed to compile.
```

**Comment by MartinX3** [comment]
@GGICE , sorry but I couldn't reolve it. :(
Instead I usw GraphiQL now, to format my GraphQL-Queries.

_Sent from my Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vjeux** [comment]
@MartinX3 & @GGICE could you create a separate issue for this? This way it can be tracked and acted on properly. Thanks!
