### ISSUE TITLE
Print comment type includes as comments

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#3493]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVEpAdKuMAEMAFgJYDOBFBAhgZALYMIwHoC0quuMAngA5wCAWV4AVAUIC8BYLgIEA1nF5IC5GACdSUAOa4AvrnRc8UADZxWAMwgQ1oiYIIzgy1QWwhicc+YheBiAANCAQ-DCk0OTIoDSamhAA7gAK8QgxKDQAbhCkACYhIDQayNY05uRwoQBGmjRgyjAAyvwNOrrIWgCu1SD5EGBlFVWhOlWaMCn1ugw0w5V9AFbkAB4AQvWNVs00zAAyOnALo2HdMPznAEwnfW2aE8gg1v5JRfzasADqBSTIABwABlCHwgVS+9X4Tw+cAm2WOoU0cAAjt1SEjpjRZvMkOVFqEqgxSF1NL0CR1LABFboQeC3UIwGg1H75P5IK4M+qkcwdADCECYOJAUGgCJA3SqYiZmTxVQMBiAA)
```sh
--parser flow
```

**Input:**
```jsx
/*::

/* this is a comment *-/

type MyType = {
  key: string
}
*/

let foo: MyType = {key: "hello"}
```

**Output:**
```jsx
/* this is a comment */

type MyType = {
  key: string
};
let foo: MyType = { key: "hello" };

```

The `/*:: ... */` comment syntax simply parses the comment as if it wasn't a comment at all and the flow parser exposes those as regular nodes.. so we'd need to access the original code to find out if those are comments or not.

I have the following idea:

1. before printing every node, go backwards from `node.loc.start` in original text skipping whitespace and check for `/*::`.. if found, prepend the node with that.
2. after printing every node, skip whitespace for `node.loc.end` for `*/`.
3. I think those are safe if we only skip whitespace...
4. Figure out a way to handle comments in that case, because they aren't nodes when traversing the API to use the logic above

I'm experimenting with this already but I wanted to gather feedback/opinions/suggestions as well... if anyone wants to collaborate as well let me know

**Comment by duailibe** [comment]
Also, I'm in doubt if we should reformat what's inside `/*:: */` for flow or just print as is to align with babylon's output.

It'd be nice to format what's inside, since that's code but we've been aligning the output of flow and babylon.. Also, depending on what we want to do, the implementation may change a lot =)

cc @vjeux who's been interested in this feature

**Comment by vjeux** [comment]
Prettier is all about formatting code to make it consistent, so I’m in favor of pretty printing the output inside of flow comments in the flow parser.

As for babylon vs flow, I don’t think it’s such a big deal that they are different in this case.

**Comment by duailibe** [comment]
@vjeux thanks for the comment! :)

**Comment by vjeux** [comment]
If there’s a comment inside of a flow type comment, it’s not unreasonable to throw. We don’t want to silently drop it, but it’s also crazy in the first place so not supporting it is an option.

**Comment by vjeux** [comment]
Actually, if you can detect it, might as well print the original source instead of throwing.

**Comment by duailibe** [comment]
Doing #3449 I had the same doubt, if I should preserve formatting and inner comments. The formatting decision there is trickier because I can totally see people complaining "I want `foo(bar/* : string*/)` instead of `foo(bar /*: string*/)` can you add an option???"

**Comment by vjeux** [comment]
I would not worry about that. Build one style that’s consistent and push it all the way through. Then if it becomes a high contention point, we can revisit.

Otherwise you’re never going anywhere if you have to constantly think about what people may or may not like.

Note that all you see at this point is the above because all those kind of decisions have been made a while ago. But in this case you’re back in this “creation” mode and not “maintainer” mode, so you need to switch your thought process.

**Comment by duailibe** [comment]
That's a good point, thanks.

**Comment by timoweave** [comment]
I just like point out good practical comment styles: C like or C++ like.
- C++-style-comment `//` can be recursive or nested. 
- C-style-comment `/* ... */` should be top root flat non-recursive.  one pair of `/*` and `*/`
  lint should warn and remove any nested or inner `/* ... /* ... /* ... /* ... */`.

If you follow the above rules, any source code inside comment can be handled by prettier.
The steps could be outlined as follow:
1. un-comment c-style block
2. prettier --ignore-error --keep-going
3. re-comment c-style block

For example, if we use the example given above (with nested c++-style-comment):

1. un-comment c-style block
```javascript


this is a comment *-/

type MyType = { // NOTE:  must be string, not number, to work with hash-like-id
  key: string 
}

```

2. prettier that ignore errors and keep going.
   2.1. prettier will failed `this is a comment *-/`,  but ok
   2.2. prettier will reformat `type MyType = { ...}` as if any normal source code, 
   (say the prettier indentation is 4-space and trailing comma)

3. re-comment c-style block
```javascript
/*

this is a comment *-/

type MyType = {
      // NOTE:  must be string, not number, to work with hash-like-id  
      key: string,
}
*/
```

**Comment by sahrens** [comment]
Any ETA on a fix or suggestions on how to work around this? For example, I can't get prettier-ignore to fix it, e.g.

```
// prettier-ignore
/*:: const foo = fizz.buzz();*/
```

still drops the flow comments and becomes:
```
// prettier-ignore
const foo = fizz.buzz();
```

as does
```
/*::
// prettier-ignore
const foo = fizz.buzz();
*/
```

**Comment by vjeux** [comment]
For context, @sahrens wants it in order to use a silly hack by using flow comments as a nice way to get the return type. https://github.com/facebook/flow/issues/4002#issuecomment-303251536

**Comment by duailibe** [comment]
@sahrens no ETA. Current workaround is to use the babylon parser

**Comment by ezequiel9** [comment]
::
/**
         * Preview feature.
         *
         * @type {number}
         */
        var locationsViewed = 0;
        rendition.on("locationChanged", function(locationCfi){
            locationsViewed++;
            if (locationsViewed > 20) {
                console.log(locationsViewed);
                $('#modal-login').modal('show');
                // Display Login Prompt
            }
        });

**Comment by thorn0** [comment]
Not an issue anymore because support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687
