### ISSUE TITLE
Ternary operators behave differently on OS X & Windows

### ISSUE THREAD

**Issue by Neglexis** [prettier/prettier#3500]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAzArlMMCW0qAtgJ4BiOehUAFAJSrAA6U66ATnDFh27a3bsAPAFlSAYQjEADtAQxBQ9pFgKAvCzbKh8PgEMOkgBZwwAayU6hAflTCAJvgBuAPgAqx-AGdUP1PqoADbQAObB+FBwqDDG+jCoAO74QUGo3sYQiUmmbGQxcAZGqGCmFn6+MBxYcAB0wgD0Tm5W1uhI9s2uAMr6xNGxkeGmXAA0qABGWAnQQaR+GH4wAOS+GPpB3nWNXa1CAL57qA2urfQA3Er7IKMgEDIE0N7IoIYcWQAKhgjPKPrOEHwDhuIH03hgyHWmzgtwmHH0Fm43RkCKGyCqNVuDggYEhGy2t0iWw4MA+8NCxH0eOhtwAVt4AB4AIXhiJgvX6ABlInBqQS7tMZNMAEx8mEgFEcYnIEATfQTUghKAgmQcSIwADqQNiyAAjAAGfW3VUQLYa+EyGWquDE5y825cACOWHwXDJ+gpVKQUP5W2I+HR1XF3iGQTgAEUsBB4IHMSAYPKtQ4dUhhbcqvoUkMpMRKTKNkEQVgtu55b8fXB9vsgA)
```sh
--print-width 100
--single-quote
--trailing-comma all
```

**Input:**
```jsx
  function myFunction() {
    return (
      <MyComponent
        content={
          ternaryCheck
            ? <div>This is a long line that will show when my ternary check is true.</div>
            : <div>Same thing here, but only if it's false.</div>
        }
      />
    );
  }
```

**Output:**
```jsx
function myFunction() {
  return (
    <MyComponent
      content={
        ternaryCheck ? (
          <div>This is a long line that will show when my ternary check is true.</div>
        ) : (
          <div>Same thing here, but only if it's false.</div>
        )
      }
    />
  );
}

```

**Expected behavior:**

The input is what my code (OS X) gets converted to (and is, in my opinion, preferred). Output is what happens on the Prettier Demo and my colleagues Windows.

All have updated to the latest Prettier.

Any idea what's going wrong?

**Comment by azz** [comment]
The input looks like an older version of Prettier. Maybe 1.5.x?

**Comment by azz** [comment]
Ref #2398

**Comment by Neglexis** [comment]
Hmm, I have the latest version installed `npm list -g` gives me `1.9.2`. I even restarted my Webstorm to be sure.

Also, any reason there was chosen for that syntax? Linked issue doesn't really give me the answer for the reasoning. I'm a much bigger fan of the older version.

**Comment by azz** [comment]
Check out #2208.

**Comment by Neglexis** [comment]
While I now understand the reasoning behind it, I still can't get it to work on my machine. I've tried restarting my Webstorm, my pc and even installed it as a dev dependency instead of globally, but still no change..

For reference, this is my External Tools window in Webstorm
![image](https://user-images.githubusercontent.com/29750443/34043437-6877b594-e1a1-11e7-90c9-902f128bb69b.png)

**Comment by Neglexis** [comment]
Ok, nevermind me. Turns out I was running a ssh connection and was installing prettier on that remote machine. So yeah, now a random server also has prettier installed! 🎉 

My sincerest apologies
