### ISSUE TITLE
Keep the empty line at the beginning of a function, if present.

### ISSUE THREAD

**Issue by electrotype** [prettier/prettier#3501]
I'm new to Prettier (for Typescript) and I like pretty much all the decisions it makes except the one that removes the empty line at the beginning of a function. 

I wish Prettier would keep such empty line if there's one, _the same way it keeps an empty line elsewhere in the function_.

For example : 

--------------------------------

```
beforeEach(async () => {

  // Sets the server port
  serverPort = 123;

  // The previous empty line is kept
});
```

would stay as is, and _not_ reformatted to:

```
beforeEach(async () => {
  // Sets the server port
  serverPort = 123;

  // The previous empty line is kept
});
```

--------------------------------

But if there is no empty line, none would be added :

```
beforeEach(async () => {
  // Sets the server port
  serverPort = 123;

  // The previous empty line is kept
});
```
would also stay as is.

--------------------------------

Any chance we can have this feature?

**Comment by lydell** [comment]
Hi!

Empty lines have been discussed a lot, and Prettier has settled on its current "at most one blank line in  a row, and no blank lines at the start and end of things" rule which seems to reasonable in 99% of the cases. Here is the most similar issue I could find right now: #2352.

I'm closing this one since it does not seem like this will be changed. Sorry! Feel free to comment here if I missed something.

**Comment by electrotype** [comment]
Thanks @lydell . Sorry to ask, but do you know of another issue or article with more information on why this won't be supported?

I think it's the only odd choice Prettier makes. 
Mostly when the first line of a function is a comment, it think it's ugly (my opinion)...

**Comment by lydell** [comment]
This answer about allowing 2 blank lines in a row could be helpful: https://github.com/prettier/prettier/issues/1613#issuecomment-302976810

**Comment by rasdaniil** [comment]
@lydell Could you please kindly point to the file and line where this rule is implemented, I just thought of forking the lib because of this option, but feel quite lost looking at the code 
Thanks!
