### ISSUE TITLE
Prettier unignore

### ISSUE THREAD

**Issue by masaeedu** [prettier/prettier#3509]
You can ignore AST nodes using `prettier-ignore`, but there doesn't seem to be any way to enable Prettier again for a subtree. E.g. I occasionally have objects mapping string keys to function values, and want to manually align the argument lists regardless of the length of the keys. However I still want formatting inside the function bodies.

I don't know if this is technically feasible (seems it would be difficult to emit a prettified AST into an arbitrary position in unformatted code), but thought I'd open an issue anyway.

**Comment by azz** [comment]
Not currently possible. `// prettier-ignore` is more of an escape-hatch for when Prettier is producing undesirable code, and adding more complexity to it is probably not something we want to do.

**Comment by duailibe** [comment]
To clarify, what `// prettier-ignore` does is simply print the whole node as-is from the original code so we don't even check what's inside

Can you share a code sample of what's your use case?

**Comment by masaeedu** [comment]
@duailibe Sure:

```
// prettier-ignore
export const stateMachine = {
  // Need these keys to stay aligned, so prettier-ignore parent
  CLR: (s, c) => [initState()],
  PEN: (s, c) => [{ ...s, down: c.down > 0 }],
  CO:  (s, c) => [{ ...s, color: c }],
  MV:  (s, c) => {
    // All the stuff in here needs to be auto-formatted though
    const { movements
 } = c;

    const positions = scan(sum)(s.position)(movements);
               const states = positions.map(p => ({ ...s, position: p }));

    return states.slice(1);
  }
};
```

**Comment by duailibe** [comment]
Thanks @masaeedu, I understand how that would be useful in your case. Unfortunately, the `prettier-unignore` and other options (such as ESLint's `disable`/`enable` comments) would add unwanted complexity like @azz already explained.

Might be easier to handle this case out of band: run once through prettier, then fix whitespaces in the arguments lists, then add `// prettier-ignore`. Following runs of prettier in the last function body, you can remove `// prettier-ignore`, run prettier, but only add to version control the lines you want changed.

**Comment by duailibe** [comment]
I'm gonna close this, since it's not actionable, but if you have something to add to the discussion, please feel free to comment and we can re-open if necessary.
