### ISSUE TITLE
Option to disable new line formatting for import statements only in Typescript or ES6

### ISSUE THREAD

**Issue by mumairofficial** [prettier/prettier#3514]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAthAbgSygHMM4BDMACw3ywAcIAnGDaDKOAdwwBtC5sZANYDIAEwGUyjMRhgQMjcrMwBXIjwCeAHSi0GzDMAwAxJlgDijCKroAaU+YDC0GNZ4OAamT5iy8xgBnBzNGLAAhVXweCUYMAF8MADNrLAwAcgABMmJVHmlUJPNA9IBuXX0mFmMAJRt4RgcAQTAYfFx-ODE61XgE5NSM7Nz8xlRrXrhGMor6KqMMFzmOWAcAeSgAST0YdagAEThAtwhNL3wuJ0posQcAUR44LAQYGrgk88vXMn5GN6T+ikIGksjkiHkCpAlDM9HNDMY1gAjQJTDqIx6AwbpRgADwAVoFUEiUYw0Y8YZV4RgAMqqZFgRj4OhtNiJIEg3EE1C0+mM5n4aAUuEsbH4wlkMRiVAQOhTfxMVBYMh0GG6TJLBgrGAACmAugwGBRj1aTCQGWVdAAtBxOOk7Pq5E86Pl4ABVRg8M3pAB0qBt3sgyxe3soMCwPDtDuOmke7p4gTNAG0fX6uAHgZrg2BAiUALq6eIASl0cBxBhYYHyOYwADkvkHYDR6I9nrBAhgNtt8LsOwcjidNEYHXQ6XwwMlzGbQpYJnRylAHegJ2F-G1iDR20QIBBZPJsHgBOQqBh9ptWFB2FxePwHZAoMdGKoTYxtQ6DXRGR0+jbqaj8GA4DNJo6DoX9SX-OB7QvA0MA-dpOnYMhcDAggALNABZBBVDuXAXigmDYM-BDcDAf4zU8C5OBcWAfg4P53nwmC4K-Q9GGsRgAAkcjER5GDNO42KYLioB4qYUIgxj3yIvp5DIY4pjNAAVCA5IaSTCPgvokkRKdzEiG4pgdQsjHiAsQDsEAZRZe9kFAODYAAdXwMQYEoZAAA4AAYLJgMhEScly3KQAAmCzAkIDQ4AARVUCB4GQJIfBRHzGB+PhiCWJVkBAKBoDgcyQERVKwBEGBqToCgIuQNxVEgkACRxcJitK6kyGeAAZfgEqSuqKqCKZspgTRZUCBkmRgAqUSwfBqsfOrVBRRS-MCbr4zqwgSRgAAFVKiCypBErWiylAARyiJQdrIPayFW5KQA-CAUQc1K6Gyj8jlRfKLOkaxOC26QEBWlAkIgZyCrECAwFuurVOhiz6hHGBguh+J4iAA)
```sh
--parser typescript
```

**Input:**
```tsx
// moving each import on new line make code hard to read / ugly
import { FormGroup, FormControl, Validators, FormBuilder } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, ViewContainerRef } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Subscription } from 'rxjs/Subscription';
import 'rxjs/add/operator/map';

@Component({
  selector: 'app-new',
  templateUrl: './new.component.html',
  styleUrls: ['./new.component.css']
})
export class NewComponent implements OnInit, OnDestroy {
  public form: FormGroup;

  // formatting is good to move each DI on new line
  constructor(
    private newService: AppService,
    private navService: MenuEvent,
    private vcRef: ViewContainerRef,
    private errorHandler: ErrorHandlerService,
    private toaster: Toaster,
    private fb: FormBuilder
  ) {}
}
```

**Output:**
```tsx
// moving each import on new line make code hard to read / ugly
import {
  FormGroup,
  FormControl,
  Validators,
  FormBuilder
} from "@angular/forms";
import { Router, ActivatedRoute } from "@angular/router";
import {
  Component,
  OnInit,
  OnDestroy,
  ViewChild,
  ElementRef,
  ViewContainerRef
} from "@angular/core";
import { Observable } from "rxjs/Observable";
import { Subscription } from "rxjs/Subscription";
import "rxjs/add/operator/map";

@Component({
  selector: "app-new",
  templateUrl: "./new.component.html",
  styleUrls: ["./new.component.css"]
})
export class NewComponent implements OnInit, OnDestroy {
  public form: FormGroup;

  // formatting is good to move each DI on new line
  constructor(
    private newService: AppService,
    private navService: MenuEvent,
    private vcRef: ViewContainerRef,
    private errorHandler: ErrorHandlerService,
    private toaster: Toaster,
    private fb: FormBuilder
  ) {}
}

```

**Expected behavior:**
There must be an option to disable formatting for *import statements* because it moves imports on new line after certain count; which make code really hard to read.

**Comment by azz** [comment]
> which make code really hard to read.

That's completely subjective. The output looks better to me, and we don't want to be adding options for this kind of thing.

**Comment by filipvh** [comment]
actually, for imports it would be better if they all were on new lines, since it would reduce the chance of merge conflicts
