### ISSUE TITLE
Allow unnecessary escapes (do not remove them)

### ISSUE THREAD

**Issue by dhoko** [prettier/prettier#3517]
Hey :wave: , 
I found this issue with prettier, it should not change the value of a string.

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAhjMACwFUAlAGQGVMBeTAczhgAU4AnbAVxnwEtoAFAG0hAcgBkAYgCM0gOwBuUQBpMozqIC6qsVNkAWJatFsVagDrm90w1p0SZABgAcRtQBszoy3pdvv5p6amgCUCiDKIBAADjD8UGjIoLhsbBAA7swpCIkouABuELwAJhEguBjIAGa47mhwkQBGbLhgANZMlNGtvFD0yDBsnA0gxRBg1bX1kb31bCwt9HiTdSMAVmgAHgBCLe2duNhw5L1wK9NR3NHcAEznI91sc8ggjbiNAJ7u0GXRbL0wADqJRghGQzkckT+EHqgJa0Refzgc3yZ0ibDgAEdOLwMcxFsskDVVpF6theAMhiM0L16O44ABFTgQeD3SI8RrA4qg5A3dktXjuWkAYQg2EJICg0DRIE49QAKu9csT6gBfVVAA)

**Input:**
```jsx
const matchURLS = getPermutation([['&#117;', 'u'], ['&#114;', 'r', '\&#114;'], ['&#108;', 'l', '\&#108;', '\l']]);
```

**Output:**
```jsx
const matchURLS = getPermutation([
  ["&#117;", "u"],
  ["&#114;", "r", "&#114;"],
  ["&#108;", "l", "&#108;", "l"]
]);

```

**Expected behavior:**
```jsx
const matchURLS = getPermutation([
  ["&#117;", "u"],
  ["&#114;", "r", "\&#114;"],
  ["&#108;", "l", "\&#108;", "\l"]
]);

```

tmp patch -> `.prettierignore`

**Comment by j-f1** [comment]
`'\&'` is equivalent to `'&'` in JS. Is this change causing issues somehow?

**Comment by j-f1** [comment]
If you want a literal ` \ ` in your code, you have to use `\\`.

**Comment by lydell** [comment]
Your issue title says: “Allow unnecessary escapes (do not remove them)”. If that’s what you want, please motivate!

But your description says: “I found this issue with prettier, it should not change the value of a string.” As @j-f1 mentioned, the value of the string is _not_ changed, since the backslash is unnecessary.

Could you clarify what youractual problem is?

**Comment by dhoko** [comment]
I get a raw HTML input, I need to clean its content before inserting the message inside the view.
We use a regexp to parse the input. (_We also have DOMPurify before_).
And why using `\l` instead if `\\l` because it's not the same cf https://jsbin.com/tujeqidasu/2/edit?html,output

@lydell because of this rule from eslint -> `/* eslint no-useless-escape: off */`

**Comment by dhoko** [comment]
@lydell why did you close the issue ?

**Comment by lydell** [comment]
Oops, my comment got lost in the Internets.

Can you post a piece of code that shows your problem?

Let's imagine that Prettier had a bug where it incorrectly converted `\0` into `0`. Then you could post something like this:
> Input code:
> ```js
> console.log("\0" === "\u0000")
> ```
>
> Result: "true" is logged to the console.
>
> After Prettier:
> ```js
> console.log("0" === "\u0000")
> ```
>
> Result: "false" is logged to the console.
