### ISSUE TITLE
Remove the bracketSpacing option or change the default value

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3520]
This comes from the [Prettier 2.0 issue](https://github.com/prettier/prettier/issues/3503)

@jlongster:

> People are pretty opinionated about trailing commas, and I think it's worth having it as an option. However, I am open to removing the `bracketSpacing` option. I haven't seen many people talk about it or use it. I think it's mainly there because recast had that option.

@lydell:

> I’d like to make a poll to see if the `bracket-spacing` option could be removed: https://github.com/prettier/prettier/issues/715#issuecomment-281096495. It’s harder to say no to new spacing options when this one exists.

@azz:

> Facebook uses `no-bracket-spacing`, and it's actually kind of growing on me.

@duailibe:

> If we were to remove the option, I'd vote to make "no spacing" the default, to be consistent with other brackets

@j-f1:

> @duailibe I like the style with spacing since it’s easier to focus on the stuff inside the brackets if there’s whitespace around it IMHO.

@azz: 

> We probably can't change the value and remove the option at the same time - we don't want people to not upgrade because it changes too much of their code.

@duailibe:

> @j-f1 That's pretty much what people who asks for spacing between [] and () say

**Comment by j-f1** [comment]
Which value of the option will be used?

**Comment by lipis** [comment]
My vote is for no spacing :)

**Comment by pbarbiero** [comment]
I really debate the benefit of this, especially given how the recent capitulation on adding https://github.com/prettier/prettier/pull/3324.

Leave it.

**Comment by rattrayalex** [comment]
Given that it's unclear which option should become the new behavior, we should probably keep the option. 

Changing the default is probably worth considering, however.

**Comment by suchipi** [comment]
There's little value add in removing an option just for the sake of removing it. Whether we philosophically like options or not, I think we should keep the ones we have.

**Comment by lydell** [comment]
When  #3855 is merged, I don't think there's any need to remove the option anymore.

**Comment by evilebottnawi** [comment]
Agree with deleting this option in 2 version

**Comment by azz** [comment]
This seems to be more trouble than it is worth. There's no need to remove the option, and changing the default value for no strong reason is only going to cause confusion.
