### ISSUE TITLE
Regression: A trailing comma is not permitted after the rest element (tsx)

### ISSUE THREAD

**Issue by rosskevin** [prettier/prettier#3528]
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3wCU4SwCAzHCdfAchxrtYG4AdKDNjxFSFAApNMAFQCemOBUbM2mSQFoYchT36DcBYuXxgANuTIA5EugX4lLVqfNRr2vgKz78UnCShlUGFRoOyYHDloYDV9-QOCoNQBzJgBXTAB6Hz8AoOgdDyECYHwAYTMyS1cAWRJMfABfUOVWADoW9LJNEwV0gHdAgAsAZS63XU9hYqzY3KgJCEwKRvs2NvSYGJz4snXNuLz3fjgAD0L8TXkqVExMbrLzAGk4GXwAXn58fAAfNiYIGFYH2+bF6vhucBwgKgnx+rFBtXkOAAMjQAG6oKCJKEwkFgxFiFImMgkIKY7HA9jXW5wcmwnBU7oANVQAQARt1ab8GXAAGLkAGHKAnM4Y+A4ei0OBXG7deaLfAneBQAAmFGmW2gcoowCBTgqCiQpXKlRsNUwAB5KNz7hUnjIAHzuT6YQnE+AAfkNrIgEG6fid+HpMrgQ1QAC84J78FAUuhWRCA0HqQANKMxuMJoFJ7oATTTsfjOHc9X4ulgEIlYClIxJUp10MD3OZbO6Xp9fqgie5KJI6Mxbd9NE7-BLUH46UIhA+xAAAqhElBcFK1PhRRCXCZjMxsELYC1p+l+HqKFbgwrjkrVVRODAWiVt9AEDBLdytQAafA1+D2-D1z6dElUDAfBlTgCVCRgLU3l-IFnVdWtDQlIk4DfIF6gDAD4ENL8pVeGCG0+bM4GbVB2TgRCSGQ1CCMbYMez7RIKKotDBU+AY-GVboAFFyxwaCAAoAEo3h-P9PnOAYWRaMg4BgHD+LE8TaOpEiyMNDYUhQ2CGkEgN0NLBt2JVbjjkCAThNeUTtJgSSyGk2T5MU8SiPojFGPOHBNOopT6l0liDMIhBQJwIT8KUyB-CKbTPmPBRvKU4xjSsGxDWPZK4DleKlJdIlayy5zuWTfLCO5HNiuU7pQwjcq2haf4BghfLGjwmypNUBYyADGLoE6X8KuIllSO6D8XLRNyGmg1q7MwuBWPEiLerS1xoKWmwyH46LEvMBQWnhcEcHKpylIAbViuy9sRVzMQAXUNUbezc8rPlO40douiECVy0lElu-AcrdLSaM+epytWjLJHyvyxxohaCCIm0TVwraKnS9azpaIiPyO-AXu2uyiNU7pfoJwayPK3H9Xx7k+U6X7-ry7TfLm7rIv6kYZG6Cg8Ox-plRsu7uSqwGEvwBr5wGGABeDIXypgBZDTUfiiKF-B0nwAAmYSAGp+rKzbunoSX8EV5XwylNXNfwHWiKKxnmcDWSUhwaENqB-BzXVfZoWgHixVeYAppaIzOLgX2IUaH3TJgf3A+DkzAkaYBavq8P7U2z5zTITA-GRxH-bB+o07dpTM+z6Ewf9+GktcRpOg5uBK8F0YyEadIi5FjOOjL9uEvNTI9lmHvPih4GRwM-jT2pURSCgGRBJadrpC0LmwtVydYOIABVGT6EJc4IHPS8JKlOvulIGVUDgZV963TxdxgOyN8PBszsNOVZHkOyIFZAArOA6BaCyagABHFIqAODKnihOKcBFZzzkXBwJ+upq4pXwO-Ze0kNiPSBNAje+AACS9B8AAAMNJwGIR+GyUoiJ-XgvAMglC5BAUoiYF4GJlTMO+sffAABrZ43oSA4GvvQCAYAUgUBmvgCARCc5wG6DYPcSCGz0ywmgyQH8drel9FA9esD8AABFUCuDFFIohVD+r7lgc-Eq0szZv3URg9MhYdEwPEsQAAErgcM0AYCUT+hADU3szENX6sYJ8EJLFuOsf1ZM9iFgaLsk4xqODdFuPwIyCEQQwB+OwIE0x3CaFVl4pEz4hBolERzHEpen8WhJIOiOQUwovCgXAiYAgk9ujuBAG+EACxZhkGQKAQRTBehiEEQgAZKBewQFQMqbpIB+TICQjJHprJfBgD4XJbOYA3LIDIT05UoilmURWWgfwmSJAkESOgEgxyqIgB-mQY4AAhdZmyhiuCRBiOAdzTkQBSDAF0MB1a-JQiAbOOAZI4GQCAVkJBWQc2gPM1QooADqsybLIAABwAAYentRkqisEMLVAKAhKiH5PSOCgPAeDK5NzQU9JkugVAezPJgoCJiboABFFI-wflIGWWC3xrJ0V8wGMgdWPSNgkFQCYNy950AMpQIuIU8zxFwCkPCyZQr6j1CAA)

**Input:**
```jsx
import * as React from 'react';
import * as PropTypes from 'prop-types';
import * as classNames from 'classnames';
import Transition from 'react-transition-group/Transition';
import { ClassNameMap } from '../styles/withStyles';
import { TransitionProps } from '../transitions/transition';

export type RippleClassKey =
  | 'root'
  | 'wrapper'
  | 'wrapperLeaving'
  | 'wrapperPulsating'
  | 'ripple'
  | 'rippleVisible'
  | 'rippleFast';

export interface RippleProps extends TransitionProps {
  classes: ClassNameMap<RippleClassKey>;
  pulsate?: boolean;
  rippleSize?: number;
  rippleX?: number;
  rippleY?: number;
}

interface State {
  rippleVisible: boolean;
  rippleLeaving: boolean;
}

/**
 * @ignore - internal component.
 */
class Ripple extends React.Component<RippleProps, State> {
  static defaultProps = {
    pulsate: false,
  };
  state: State = {
    rippleVisible: false,
    rippleLeaving: false,
  };

  handleEnter = () => {
    this.setState({
      rippleVisible: true,
    });
  };

  handleExit = () => {
    this.setState({
      rippleLeaving: true,
    });
  };

  render() {
    const {
      classes,
      className: classNameProp,
      pulsate,
      rippleX,
      rippleY,
      rippleSize,
      ...other,
    } = this.props;
    const { rippleVisible, rippleLeaving } = this.state;

    const className = classNames(
      classes.wrapper,
      {
        [classes.wrapperLeaving]: rippleLeaving,
        [classes.wrapperPulsating]: pulsate,
      },
      classNameProp,
    );

    const rippleClassName = classNames(classes.ripple, {
      [classes.rippleVisible]: rippleVisible,
      [classes.rippleFast]: pulsate,
    });

    const rippleStyles = {
      width: rippleSize,
      height: rippleSize,
      top: -(rippleSize / 2) + rippleY,
      left: -(rippleSize / 2) + rippleX,
    };

    return (
      <Transition onEnter={this.handleEnter} onExit={this.handleExit} {...other}>
        <span className={className}>
          <span className={rippleClassName} style={rippleStyles} />
        </span>
      </Transition>
    );
  }
}

(Ripple as any).propTypes = {
  /**
   * Useful to extend the style applied to components.
   */
  classes: PropTypes.object.isRequired,
  /**
   * @ignore
   */
  className: PropTypes.string,
  /**
   * If `true`, the ripple pulsates, typically indicating the keyboard focus state of an element.
   */
  pulsate: PropTypes.bool,
  /**
   * Diameter of the ripple.
   */
  rippleSize: PropTypes.number,
  /**
   * Horizontal position of the ripple center.
   */
  rippleX: PropTypes.number,
  /**
   * Vertical position of the ripple center.
   */
  rippleY: PropTypes.number,
};

export default Ripple;

```

**Output:**
```jsx
SyntaxError: A trailing comma is not permitted after the rest element (62:15)
  60 |       rippleY,
  61 |       rippleSize,
> 62 |       ...other,
     |               ^
  63 |     } = this.props;
  64 |     const { rippleVisible, rippleLeaving } = this.state;
  65 | 
```

**Expected behavior:**
When I run prettier on a `tsx` file, it does not add a comma to the end or a rest element.  Regression of #507 it seems, the only potential difference I see is that this is a `tsx`.

If I delete the comma manually then re-run prettier, it adds the comma back.

`trailingCommas` is currently `all`, but I tried with `es5` and it made no difference.

**Comment by ikatyang** [comment]
You have to specify `--parser typescript` on the playground.

<details> 
<summary>playground</summary>

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3wCU4SwCAzHCdfAchxrtYG4AdKDNjxFSFAApNMAFQCemOBUbM2mSQFoYchT36DcBYuXxgANuTIA5EugX4lLVqfNRr2vgKz78UnCShlUGFRoOyYHDloYDV9-QOCoNQBzJgBXTAB6Hz8AoOgdDyECYHwAYTMyS1cAWRJMfABfUOVWADoW9LJNEwV0gHdAgAsAZS63XU9hYqzY3KgJCEwKRvs2NvSYGJz4snXNuLz3fjgAD0L8TXkqVExMbrLzAGk4GXwAXn58fAAfNiYIGFYH2+bF6vhucBwgKgnx+rFBtXkOAAMjQAG6oKCJKEwkFgxFiFImMgkIKY7HA9jXW5wcmwnBU7oANVQAQARt1ab8GXAAGLkAGHKAnM4Y+A4ei0OBXG7deaLfAneBQAAmFGmW2gcoowCBTgqCiQpXKlRsNUwAB5KNz7hUnjIAHzuT6YQnE+AAfkNrIgEG6fid+HpMrgQ1QAC84J78FAUuhWRCA0HqQANKMxuMJoFJ7oATTTsfjOHc9X4ulgEIlYClIxJUp10MD3OZbO6Xp9fqgie5KJI6Mxbd9NE7-BLUH46UIhA+xAAAqhElBcFK1PhRRCXCZjMxsELYC1p+l+HqKFbgwrjkrVVRODAWiVt9AEDBLdytQAafA1+D2-D1z6dElUDAfBlTgCVCRgLU3l-IFnVdWtDQlIk4DfIF6gDAD4ENL8pVeGCG0+bM4GbVB2TgRCSGQ1CCMbYMez7RIKKotDBU+AY-GVboAFFyxwaCAAoAEo3h-P9PnOAYWRaMg4BgHD+LE8TaOpEiyMNDYUhQ2CGkEgN0NLBt2JVbjjkCAThNeUTtJgSSyGk2T5MU8SiPojFGPOHBNOopT6l0liDMIhBQJwIT8KUyB-CKbTPmPBRvKU4xjSsGxDWPZK4DleKlJdIlayy5zuWTfLCO5HNiuU7pQwjcq2haf4BghfLGjwmypNUBYyADGLoE6X8KuIllSO6D8XLRNyGmg1q7MwuBWPEiLerS1xoKWmwyH46LEvMBQWnhcEcHKpylIAbViuy9sRVzMQAXUNUbezc8rPlO40douiECVy0lElu-AcrdLSaM+epytWjLJHyvyxxohaCCIm0TVwraKnS9azpaIiPyO-AXu2uyiNU7pfoJwayPK3H9Xx7k+U6X7-ry7TfLm7rIv6kYZG6Cg8Ox-plRsu7uSqwGEvwBr5wGGABeDIXypgBZDTUfiiKF-B0nwAAmYSAGp+rKzbunoSX8EV5XwylNXNfwHWiKKxnmcDWSUhwaENqB-BzXVfZoWgHixVeYAppaIzOLgX2IUaH3TJgf3A+DkzAkaYBavq8P7U2z5zTITA-GRxH-bB+o07dpTM+z6Ewf9+GktcRpOg5uBK8F0YyEadIi5FjOOjL9uEvNTI9lmHvPih4GRwM-jT2pURSCgGRBJadrpC0LmwtVydYOIABVGT6EJc4IHPS8JKlOvulIGVUDgZV963TxdxgOyN8PBszsNOVZHkOyIFZAArOA6BaCyagABHFIqAODKnihOKcBFZzzkXBwJ+upq4pXwO-Ze0kNiPSBNAje+AACS9B8AAAMNJwGIR+GyUoiJ-XgvAMglC5BAUoiYF4GJlTMO+sffAABrZ43oSA4GvvQCAYAUgUBmvgCARCc5wG6DYPcSCGz0ywmgyQH8drel9FA9esD8AABFUCuDFFIohVD+r7lgc-Eq0szZv3URg9MhYdEwPEsQAAErgcM0AYCUT+hADU3szENX6sYJ8EJLFuOsf1ZM9iFgaLsk4xqODdFuPwIyCEQQwB+OwIE0x3CaFVl4pEz4hBolERzHEpen8WhJIOiOQUwovCgXAiYAgk9ujuBAG+EACxZhkGQKAQRTBehiEEQgAZKBewQFQMqbpIB+TICQjJHprJfBgD4XJbOYA3LIDIT05UoilmURWWgfwmSJAkESOgEgxyqIgB-mQY4AAhdZmyhiuCRBiOAdzTkQBSDAF0MB1a-JQiAbOOAZI4GQCAC4CgwBBhgPM1QooADqsybLIAABwAAYentRkqisEMLVAKAhKiH5PSOCgPAeDK5NzQU9JkugVAezPJgoCJiboABFFI-wflIGWWC3xrJ0V8wGMgdWPSNgkFQCYNy950AMpQIuIU8zxFwCkCQVkkyhX1HqEAA)
```sh
--parser typescript
```

**Input:**
```tsx
import * as React from 'react';
import * as PropTypes from 'prop-types';
import * as classNames from 'classnames';
import Transition from 'react-transition-group/Transition';
import { ClassNameMap } from '../styles/withStyles';
import { TransitionProps } from '../transitions/transition';

export type RippleClassKey =
  | 'root'
  | 'wrapper'
  | 'wrapperLeaving'
  | 'wrapperPulsating'
  | 'ripple'
  | 'rippleVisible'
  | 'rippleFast';

export interface RippleProps extends TransitionProps {
  classes: ClassNameMap<RippleClassKey>;
  pulsate?: boolean;
  rippleSize?: number;
  rippleX?: number;
  rippleY?: number;
}

interface State {
  rippleVisible: boolean;
  rippleLeaving: boolean;
}

/**
 * @ignore - internal component.
 */
class Ripple extends React.Component<RippleProps, State> {
  static defaultProps = {
    pulsate: false,
  };
  state: State = {
    rippleVisible: false,
    rippleLeaving: false,
  };

  handleEnter = () => {
    this.setState({
      rippleVisible: true,
    });
  };

  handleExit = () => {
    this.setState({
      rippleLeaving: true,
    });
  };

  render() {
    const {
      classes,
      className: classNameProp,
      pulsate,
      rippleX,
      rippleY,
      rippleSize,
      ...other,
    } = this.props;
    const { rippleVisible, rippleLeaving } = this.state;

    const className = classNames(
      classes.wrapper,
      {
        [classes.wrapperLeaving]: rippleLeaving,
        [classes.wrapperPulsating]: pulsate,
      },
      classNameProp,
    );

    const rippleClassName = classNames(classes.ripple, {
      [classes.rippleVisible]: rippleVisible,
      [classes.rippleFast]: pulsate,
    });

    const rippleStyles = {
      width: rippleSize,
      height: rippleSize,
      top: -(rippleSize / 2) + rippleY,
      left: -(rippleSize / 2) + rippleX,
    };

    return (
      <Transition onEnter={this.handleEnter} onExit={this.handleExit} {...other}>
        <span className={className}>
          <span className={rippleClassName} style={rippleStyles} />
        </span>
      </Transition>
    );
  }
}

(Ripple as any).propTypes = {
  /**
   * Useful to extend the style applied to components.
   */
  classes: PropTypes.object.isRequired,
  /**
   * @ignore
   */
  className: PropTypes.string,
  /**
   * If `true`, the ripple pulsates, typically indicating the keyboard focus state of an element.
   */
  pulsate: PropTypes.bool,
  /**
   * Diameter of the ripple.
   */
  rippleSize: PropTypes.number,
  /**
   * Horizontal position of the ripple center.
   */
  rippleX: PropTypes.number,
  /**
   * Vertical position of the ripple center.
   */
  rippleY: PropTypes.number,
};

export default Ripple;

```

**Output:**
```tsx
import * as React from "react";
import * as PropTypes from "prop-types";
import * as classNames from "classnames";
import Transition from "react-transition-group/Transition";
import { ClassNameMap } from "../styles/withStyles";
import { TransitionProps } from "../transitions/transition";

export type RippleClassKey =
  | "root"
  | "wrapper"
  | "wrapperLeaving"
  | "wrapperPulsating"
  | "ripple"
  | "rippleVisible"
  | "rippleFast";

export interface RippleProps extends TransitionProps {
  classes: ClassNameMap<RippleClassKey>;
  pulsate?: boolean;
  rippleSize?: number;
  rippleX?: number;
  rippleY?: number;
}

interface State {
  rippleVisible: boolean;
  rippleLeaving: boolean;
}

/**
 * @ignore - internal component.
 */
class Ripple extends React.Component<RippleProps, State> {
  static defaultProps = {
    pulsate: false
  };
  state: State = {
    rippleVisible: false,
    rippleLeaving: false
  };

  handleEnter = () => {
    this.setState({
      rippleVisible: true
    });
  };

  handleExit = () => {
    this.setState({
      rippleLeaving: true
    });
  };

  render() {
    const {
      classes,
      className: classNameProp,
      pulsate,
      rippleX,
      rippleY,
      rippleSize,
      ...other
    } = this.props;
    const { rippleVisible, rippleLeaving } = this.state;

    const className = classNames(
      classes.wrapper,
      {
        [classes.wrapperLeaving]: rippleLeaving,
        [classes.wrapperPulsating]: pulsate
      },
      classNameProp
    );

    const rippleClassName = classNames(classes.ripple, {
      [classes.rippleVisible]: rippleVisible,
      [classes.rippleFast]: pulsate
    });

    const rippleStyles = {
      width: rippleSize,
      height: rippleSize,
      top: -(rippleSize / 2) + rippleY,
      left: -(rippleSize / 2) + rippleX
    };

    return (
      <Transition
        onEnter={this.handleEnter}
        onExit={this.handleExit}
        {...other}
      >
        <span className={className}>
          <span className={rippleClassName} style={rippleStyles} />
        </span>
      </Transition>
    );
  }
}

(Ripple as any).propTypes = {
  /**
   * Useful to extend the style applied to components.
   */
  classes: PropTypes.object.isRequired,
  /**
   * @ignore
   */
  className: PropTypes.string,
  /**
   * If `true`, the ripple pulsates, typically indicating the keyboard focus state of an element.
   */
  pulsate: PropTypes.bool,
  /**
   * Diameter of the ripple.
   */
  rippleSize: PropTypes.number,
  /**
   * Horizontal position of the ripple center.
   */
  rippleX: PropTypes.number,
  /**
   * Vertical position of the ripple center.
   */
  rippleY: PropTypes.number
};

export default Ripple;

```

</details>

**Comment by rosskevin** [comment]
Fantastic - thanks @ikatyang - we are trying to switch a codebase to typescript and still had `parser: babylon`.
