### ISSUE TITLE
package.json 2+ spacing / tabs

### ISSUE THREAD

**Issue by chrisblossom** [prettier/prettier#3533]
Using npm <5, ``package.json`` does not allow anything but two space indents. https://github.com/npm/npm/issues/4718. It might be a good idea to set the following default unless explicitly overridden:

```js
// ...
overrides: [
    {
        files: 'package.json',
        options: {
            tabWidth: 2,
            useTabs: false,
        },
    },
],
// ...
```

Note, this is not an issue with Yarn or npm 5.

**Comment by azz** [comment]
I usually add package.json to `.prettierignore` because npm/yarn format it differently.

**Comment by chrisblossom** [comment]
That is a much better solution than the override. I do think ignoring ``package.json`` by default is best thing to do. Otherwise it is possible prettier can break an npm library for people using npm <5.

Either way, I've started adding ``package.json`` to my ``.prettierignore`` files. Thank for the tip!

**Comment by rdmurphy** [comment]
Dunno if this is the best place to suggest this as well, but I do wonder if `package.json` should be ignored by default just like the `node_modules` directory. 🤔

`npm` tends to rule that file with an iron fist, and it often becomes a battle of the formatters.

**Comment by azz** [comment]
Let's document putting package.json in the ignore file instead.

**Comment by chrisblossom** [comment]
Closing in favor of https://github.com/prettier/prettier/issues/3671
