### ISSUE TITLE
[typescript] missing dangling comma in function parameter desctructuring

### ISSUE THREAD

**Issue by no23reason** [prettier/prettier#3539]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3wCU4SwCAzHCdfAHRBxrvYG5WoM2PPmD4AKnAAeMADT4AaqjgB3OQGUYATwA2cAApNMcxSo064+AL75GzNhy4wAtFBIxUANzi9+-QbgJRPTgcMmgrGyYWdgA6GIB6OPitTDgyHwEsAJF8Mi1dCmtbaJAEvPN0kD4ofikhAkgoPPxg0OgAeS8cDyVlfABefAAKYH58cfxUtqgZMYm4mMxDMlmoSyQROfGpsKgN1t3qidz8uAB+DbNdAwhMAB4TZSu4AD5qywBKAZfhrfwH3oncz9YAAbXKBRijRgJFQUBCciWtzIMQhcAAupYXn9xncJNIXsAACZuEgxVzoOCWO7xfEwbFQY40x4Mj7VEAyEC3dzQMjIUAkHBMZR6QUIPkoEgeCCoIkckDkGDIegkbRkOCcgBGOFoAGs4DA1JhaHCAObIGA4ACuGpARIgYGVqvVnLh6rwBhIpvQJCdattACsyJIAEI6sD6w0kSkAGThcD9Lq5VpgmBTACZE7bjaEQsgQCk0mAcKhMErOUs4TAAOqymAAC2QAA4AAwVpjq6s6zD5pZpEJeeWcACOVtQnE93t9SBV-s56vQqAt1ttZDNugAilaIPAs5yYZra0SG8gACz7nWobRmgDCzB9+dV2nlVvVYhImols-VlksQA)
```sh
--parser typescript
--tab-width 4
--trailing-comma all
```

**Input:**
```tsx
import * as React from "react";
import { Text, View, StyleProp, ViewStyle } from "react-native";

import { Person } from "../../types";
import { styles } from "./styles";

export const PersonOverview = ({
    person,
    ...props,
}: {
    person: Person;
    style?: StyleProp<ViewStyle>;
}) => (
    <View style={[styles.container, props.style]}>
      <Text>{data.name}</Text>
    </View>
);

```

**Output:**
```tsx
import * as React from "react";
import { Text, View, StyleProp, ViewStyle } from "react-native";

import { Person } from "../../types";
import { styles } from "./styles";

export const PersonOverview = ({
    person,
    ...props
}: {
    person: Person;
    style?: StyleProp<ViewStyle>;
}) => (
    <View style={[styles.container, props.style]}>
        <Text>{data.name}</Text>
    </View>
);

```

**Expected behavior:**
There should be a comma after the `...props` destructuring on line 9 (e.g. it should look like in the input).

**Comment by azz** [comment]
This is intentional. See #3311

**Comment by no23reason** [comment]
Oh, sorry I missed that one, thank you!
