### ISSUE TITLE
Feature Request: html.format.wrapAttributes like in vscode

### ISSUE THREAD

**Issue by alexandermikuta** [prettier/prettier#3540]
Currently I see no possibility to wrap HTML-Attributes in prettier like it is possible in vscode via html.format.wrapAttributes. Is there any option available (or planned) to wrap HTML-Attributes when formatting with prettier?

**Comment by lydell** [comment]
All of use don't use vscode. Can you show input, Prettier's output and your desired output, please?

**Comment by alexandermikuta** [comment]
Of course.

`<my-hero-list [heroes]="heroes" (selectHero)="onSelect($event)" class="nav"></my-hero-list>`

should e.g. become

`<my-hero-list [heroes]="heroes" 
    (selectHero)="onSelect($event)"
    class="nav">
</my-hero-list>`

**Comment by lydell** [comment]
Prettier does not support HTML and HTML-like languages currently. (There’s a hidden experimental implementation, though.) So I don’t understand your feature request? Have you confused Prettier with some other tool?

**Comment by thearabbit** [comment]
+1
