### ISSUE TITLE
wrong new line in js

### ISSUE THREAD

**Issue by denghui1010** [prettier/prettier#3543]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOizAQ3hzAKgAUAnOATTgMoAIBeAEyLhwHM4YBZaOgAUASkYBaALYYoAEQ7deA2GlGMA1EPbEeMAGIBXADZG6DNeMbS5C3YZNnKosQCpGARgBMjAHzMvANwAOirYeITEpFAAcnAAHjCOLEKSBHHyOrz2pvROYpbanHbGOeYirh7e6qnptkqCqvlwGUX1Kmp+gSAANCAQAA4wGNBYyKAMlBAA7uQMCKMoBABuEBisPSAE+MgAZgRGWHC9AEaUBGAA1rwAyv3nMlzIMJQGRyCsEGC7+4e9MoeUGBUAhcVLfA5vABWWDiACEzpcbgRJHAADIyODg359Awwfq4zxYt53SgA5AgY4EY4ATyM0A2-UoMhgAHU1uhkAAOAAMvUZEEOLLO-XJjLgAKWmN61AAjgYMNRgaCCETeodpE8Xm8sA8jHAAIoGCDwVWoKls1gcpCeXrPAgYIwPADCEEkYJQUGgUpABkOABUqQs9hCAL4hoA)

**Input:**
```jsx
this.state.canPreYear =date.getMonth() -minDate.getMonth() +(date.getFullYear() - minDate.getFullYear()) * 12 >=12;
this.state.canNextYear =(maxDate.getFullYear() - date.getFullYear()) * 12 +maxDate.getMonth() -eDate.getMonth() >=12;
```

**Output:**
```jsx
this.state.canPreYear =
  date.getMonth() -
    minDate.getMonth() +
    (date.getFullYear() - minDate.getFullYear()) * 12 >=
  12;
this.state.canNextYear =
  (maxDate.getFullYear() - date.getFullYear()) * 12 +
    maxDate.getMonth() -
    eDate.getMonth() >=
  12;

```

**Expected behavior:**

**Comment by lydell** [comment]
Can you point out what specifically you don’t like here, and how you’d like it to be formatted?

**Comment by denghui1010** [comment]
@lydell 
I'd like this
if printWith = 80
```
xxxxx = xxxxx + xxxxx + xxxxx + xxxxxx +     |(printWith=80)
          xxxxxxxx + xxxxxxxxxxx +           |(printWith=80)
            xxxxxxxxxxxxxxxxx > 20;          |(printWith=80)
```

**Comment by denghui1010** [comment]
@lydell currently if I set printWith = 100, I get this:
```
this.state.canPreYear =
  date.getMonth() - minDate.getMonth() + (date.getFullYear() - minDate.getFullYear()) * 12 >= 12;
this.state.canNextYear =
  (maxDate.getFullYear() - date.getFullYear()) * 12 + maxDate.getMonth() - eDate.getMonth() >= 12;
```
I don't understand why...

**Comment by lydell** [comment]
Is this what you want?

```js
this.state.canPreYear =
  date.getMonth() -
    minDate.getMonth() +
    (date.getFullYear() - minDate.getFullYear()) * 12 >= 12;
this.state.canNextYear =
  (maxDate.getFullYear() - date.getFullYear()) * 12 +
    maxDate.getMonth() -
    eDate.getMonth() >= 12;
```

Regarding printWidth = 100, what's wrong there? All lines are <100 chars in you example.

**Comment by denghui1010** [comment]
@lydell 
I mean, when printWidth =100 or printWidth=80, the logic of new line seems to be completely different, which makes it impossible to understand. Why `date.getMonth () -` would be a single line? If `date.getMonth () -` should be a single line. why the output is not like this:
```
this.state.canPreYear =
  date.getMonth() -
    minDate.getMonth() +
      (date.getFullYear() - 
        minDate.getFullYear()) *
          12 >=
            12;
```
The correct logic should be the following:
```
this.state.canPreYear = date.getMonth() - minDate.getMonth() + (date.getFullYear() -
  minDate.getFullYear()) * 12 >= 12;
```
this is [js-beautify](https://github.com/beautify-web/js-beautify) output with 'wrap lines near 80 characters'. Line breaks should be near width=80, not at the beginning
Course, I prefer it:
```
this.state.canPreYear = date.getMonth() - minDate.getMonth() + (date.getFullYear() -
                          minDate.getFullYear()) * 12 >= 12;
```
