### ISSUE TITLE
linter Plugin support for 2.0

### ISSUE THREAD

**Issue by tjbenton** [prettier/prettier#3547]
Currently the prettier eco system is a little bit spread out and confusing to work with when you're trying to get it to work with other packages.

  - [prettier-eslint](https://www.npmjs.com/package/prettier-eslint)
  - [prettier-eslint-cli](https://www.npmjs.com/package/prettier-eslint-cli)
  - [prettier-standard](https://www.npmjs.com/package/prettier-standard)
  - [prettier-package-json](https://www.npmjs.com/package/prettier-package-json)
  - [prettier-stylelint](https://www.npmjs.com/package/prettier-stylelint)
  - [prettier-tslint](https://www.npmjs.com/package/prettier-tslint)
  - [prettier-stylelint-formatter](https://www.npmjs.com/package/prettier-stylelint-formatter)
  - [prettier-markdown](https://www.npmjs.com/package/prettier-markdown)
  - [prettier-vue](https://www.npmjs.com/package/prettier-vue)

Each of the packages above have their own **unique** cli and options which is great if you love a completely different experience and like to read documentation on how to use it.

While the discussions are going on for [v2.0](#3503) I would like to propose adding support for plugins. This way there is only 1 way to use the prettier cli, not multiple ways.

The other advantage of adding support for plugins is that they can work together. For example when parsing markdown files each of the js blocks and be parsed using eslint, or each of the scss blocks could be parsed with the stylelint plugin. That way not only are all the files formatted correctly according to eslint/stylelint/etc. they're also formatted correctly in markdown files. Another example would be with vue files and script, and style tags since you can specify the language that's used.

Here's a rough concept of what the plugin api could look like. 

```js
export default {
  // this defines the languages that this plugin supports. This is determined in 3 different ways
  // 1. By the file extension
  // 2. By the language attr/element
  //   - `<script>` This assumes the language is js
  //   - `<script lang="js">` same thing as above
  //   - `<style>` // assumes css
  //   - `<style lang="css">` same thing as above
  //   - `<style lang="scss">` changes language to css
  // 3. By the codeblock language
  // 
  //   - ```js
  //     const foo = ''
  //     ```
  //   - ```scss
  //     .foo { background: blue; }
  //     ```
  // They can pass in string/array/regex
  lang: [ 'js', 'jsx' ],
  // runs before the file is returned/written
  handler({ 
    // any options that are passed to prettier, this way if a 
    // plugin needs access to one of them they have it
    options,
    // the code that's going to formatted
    content,
  }) {
    // the modified content would be returned
    return content
  },
}
```

**Comment by j-f1** [comment]
FYI `prettier-markdown` has been superseded by markdown support included in Prettier by default.

**Comment by tjbenton** [comment]
I know that but the prettier-markdown package hasn't been updated to say that it's deprecated, and direct people to use the built in markdown support.

**Comment by josephfrazier** [comment]
There's some work-in-progress on a plugin API at https://github.com/prettier/prettier/pull/3536

**Comment by azz** [comment]
As @josephfrazier mentioned I'm working on a plugin API as we speak! See some notes: https://github.com/prettier/prettier/issues/3511#issuecomment-352688871 and https://github.com/prettier/prettier/issues/3511#issuecomment-353020072
