### ISSUE TITLE
Support hyperhtml, lit-html and other html templates using html tagged template literals 

### ISSUE THREAD

**Issue by kasperpeulen** [prettier/prettier#3548]
I would be great to have support for formatting html in template literals.

It seems like solutions like libraries like hyper html and lit html will become a nice alternative to JSX.

Actually, you can also write such templates with a simple html function as described here:
http://2ality.com/2015/01/template-strings-html.html

I was experimenting with it today:

```javascript
function journalEntries(entries) {
    return html`
        <div class="row">
            ${entries.length === 0 ? '' : `    
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Account name</th>
                            <th>Debit</th>
                            <th>Credit</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${entries.map(post => journalRow(post))}
                    </tbody>
                </table>
            `}
        </div>
    `;
}
```

It would be nice if prettier could somehow format such html tagged  template literals in a similar fashion as it does with JSX.

Edit: I changed the wording so that it is about tagged template literals as suggested below.

**Comment by lydell** [comment]
Hi, thanks for the issue!

Prettier formats _some_ template literals. _Tagged_ template literals, to be precise. For example, ``gql`...` `` is formatted as GraphQL. In your example, though, there does not seem to be anything that indicates that you template literal is special, so Prettier can't safely change its contents. It can't even know _how_ to format your template literal!

So sadly this isn't possible. Thanks for the suggestion, though! Feel free to comment if there's something more I don't know of that Prettier could use to identify those template literals.

(On a side note, Prettier does not yet support HTML formatting, which is another blocker.)

**Comment by yorrd** [comment]
@lydell  I would like you to reconsider in the case of `lit-html` as soon as HTML formatting is supported. The tag `html\`\`` will then be used like this: 

```
static get template() {
     return html`<div></div>`;
}
```

**Comment by JosefJezek** [comment]
@yorrd any progress?

**Comment by sgtpep** [comment]
In case anyone interested in it to experiment with, I made a hacky solution: [prettier-plugin-html-template-literals](https://github.com/sgtpep/prettier-plugin-html-template-literals). It monkey-patches Prettier a bit, parses HTML using the prettier's JSX parser (part of the babylon parser) and massages the formatted output to get rid of JSX artifacts.

**Comment by suchipi** [comment]
Regarding prettier-plugin-html-template-literals, see also https://github.com/prettier/prettier/issues/4618

**Comment by kasperpeulen** [comment]
Any progress on this?

**Comment by SimenB** [comment]
Tagged `html` works now, https://prettier.io/blog/2018/11/07/1.15.0.html#html-template-literal-in-javascript

**Comment by yorrd** [comment]
I'm loving it :) works flawlessly. A few opinioned things changed in our code, but that's fine, at least it's consistent now! Thanks guys <3

**Comment by suchipi** [comment]
Gonna close this since it works :)
