### ISSUE TITLE
Ignored blocks containing emoji strips out following content

### ISSUE THREAD

**Issue by amsul** [prettier/prettier#3556]
Hello all! I just found a bit of a nasty bug while using `prettier-ignore` on an object block containing emoji.

**Actual behavior:**

<summary>
Adding emoji to a block ignored by Prettier results in content being stripped out 😵

You can see this in action by removing the `prettier-ignore` comment [here in the Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwDYQDuAOlKehgA4BOcMMAlnNQLQMDmUEtpkUAzjAwxqAQwF5RjaBgC8GYKVIYMAcgBCAVwZ4hhBjAAWGQLwbgHJ2M4gCYYwo2qqQLlKjAicbtujPqOmL1rb2cKoANC4AvuFkUCqqAMLQ7GIw-BgyRnAYALZSYIYAhBiAPBuAkftlZY7Osa7uaolQyVJpGYZZuTD5RRXlpWGR0SouqgCSMICYBGmiOXmFJb2VToo1KnWjE1MznXM9lYMYUUo1qgASDKEKOAzUggByotlwEUUmgNI7VcuublBO8NmUkngAFVGHgAHQwUTsDAAAzOFwAJMBVFcbjB7o9VM9TK8YftDjE4gBNCCaajCOAPGZQKHMHw6PAYWhgOAMABuWWm-EIokoTLgAEdNHBBBgcNwMABPUnkgBUwGoEDwT1lGH4hgYOCEUgw8sYjwiqpk8qsUhVYI+LlWPwp-0BcBBOghUNhJLJFKpuRp7Dp+jwjOZrI5ljVPL5tCFIqE4vJ0vdsqRqkVyqxqvVmu1QgTyP1IUN6Vi2dUpvgqbBeIGwzd439GB92opAA9MwpKIZoE9LStvr84HazY7wZDoTDq7X6yH4M3LEJE22O1iKzUCaQIkdshArJplWC4I3KNxUnJhGIJFIGNAjnuD9QhDBJZQsgAVU-8QEXqAAaTgkqfD6y8gIt+kr8AAPPej4QDgJ7iG+57QAAfKQIChCAECUNIAjIKA9iKoQAAKwRYSgohshADBWChICiIIyA4KIeD8HAqEAEZiGAADWdAAMqUKIYAMI0yAiMKqFWBAYB0QxTGoYJTG3vhYjsLkUmMcxIAAFb8I26jsVxMDcQ8cAADKCXAqkyWhmgwJQ1kAEwWepfE3MwyAgPgRBUTQgkwAA6hRRjIAAHAADKhNAQExvliJQbk0CKzAclREbaLQilQipSD0WpqFMdkDCOblgnsMqACKmgQPAwnUKJICQix-lWIFSB2ahIiiDoxWJNkmUgCKACsVGaExT6iCx-COREERAA).
<details>

**Prettier 1.9.2**
```sh
--parser flow
--no-semi
--single-quote
--trailing-comma es5
```

**Input:**
```jsx
// @flow

// prettier-ignore
const translation = {

  'Built with 💜 and care': {
    en: 'Built with 💜 and care',
  },

  'Congrats on the match! 🎉🎉🎉': {
    en: 'Congrats on the match! 🎉🎉🎉',
  },
  
  'It’s a match! 🎉🎉🎉': {
    en: 'It’s a match! 🎉🎉🎉',
  },

  'Hi, {firstName}! 👋': {
    en: templateUtil.tag `Hi, ${'firstName'}! 👋`,
  },

  'Your team manager will receive a swap request for your *{role}* shift at *{time}* on *{date}*.': {
    en: templateUtil.tag `Your team manager will receive a swap request for your *${'role'}* shift at *${'time'}* on *${'date'}*.`,
  },
  'You’ll get a text at {phone}': {
    en: templateUtil.tag `You’ll get a text at ${'phone'}`,
  },

}

module.exports = translation

export type TranslationKeyType = $Keys<typeof translation>

```

**Output:**
```jsx
// @flow

// prettier-ignore
const translation = {

  'Built with 💜 and care': {
    en: 'Built with 💜 and care',
  },

  'Congrats on the match! 🎉🎉🎉': {
    en: 'Congrats on the match! 🎉🎉🎉',
  },
  
  'It’s a match! 🎉🎉🎉': {
    en: 'It’s a match! 🎉🎉🎉',
  },

  'Hi, {firstName}! 👋': {
    en: templateUtil.tag `Hi, ${'firstName'}! 👋`,
  },

  'Your team manager will receive a swap request for your *{role}* shift at *{time}* on *{date}*.': {
    en: templateUtil.tag `Your team manager will receive a swap request for your *${'role'}* shift at *${'time'}* on *${'date'}*.`,
  },
  'You’ll get a text at {phone}': {
    en: templateUtil.tag `You’ll get a text at ${'p
module.exports = translation
export type TranslationKeyType = $Keys<typeof translation>

```
</details>
</summary>

<br />

**Expected behavior:**

Content not being stripped out 😅

**Comment by ikatyang** [comment]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwDYQDuAOlKehgA4BOcMMAlnNQLQMDmUEtpkUAzjAwxqAQwF5RjaBgC8GYKVIYMAcgBCAVwZ4hhBjAAWGQLwbgHJ2M4gCYYwo2qqQLlKjAicbtujPqOmL1rb2cKoANC4AvuFkUCqqAMLQ7GIw-BgyRnAYALZSYIYAhBiAPBuAkftlZY7Osa7uaolQyVJpGYZZuTD5RRXlpWGR0SouqgCSMICYBGmiOXmFJb2VToo1KnWjE1MznXM9lYMYUUo1qgASDKEKOAzUggByotlwEUUmgNI7VcuublBO8NmUkngAFVGHgAHQwUTsDAAAzOFwAJMBVFcbjB7o9VM9TK8YftDjE4gBNCCaajCOAPGZQKHMHw6PAYWhgOAMABuWWm-EIokoTLgAEdNHBBBgcNwMABPUnkgBUwGoEDwT1lGH4hgYOCEUgw8sYjwiqpk8qsUhVYI+LlWPwp-0BcBBOghUNhJLJFKpuRp7Dp+jwjOZrI5ljVPL5tCFIqE4vJ0vdsqRqkVyqxqvVmu1QgTyP1IUN6Vi2dUpvgqbBeIGwzd439GB92opAA9MwpKIZoE9LStvr84HazY7wZDoTDq7X6yH4M3LEJE22O1iKzUCaQIkdshArJplWC4I3KNxUnJhGIJFIGNAjnuD9QhDBJZQsgAVU-8QEXqAAaTgkqfD6y8gIt+kr8AAPPej4QDgJ7iG+57QAAfKQIChCAECUNIAjIKA9iKoQAAKwRYSgohshADBWChICiIIyA4KIeD8HAqEAEZiGAADWdAAMqUKIYAMI0yAiMKqFWBAYB0QxTGoYJTG3vhYjsLkUmMcxIAAFb8I26jsVxMDcQ8cAADKCXAqkyWhmgwJQ1kAEzCdQokgHxNzMMgID4EQVE0IJMAAOoUUYyAABwAAyoTQEBMf5YiUB5NAiswHJURG2i0IpUIqUg9FqahTHZAwFnqfwgnsMqACKmgQPAjnOZCLGBVYwVIHZqEiKIOhlYk2TZSAIoAKxUZoTFPqILH8MVEQREAA)

**Second Output:**
```jsx
SyntaxError: Unexpected token ILLEGAL (26:52)
  24 |   },
  25 |   'You’ll get a text at {phone}': {
> 26 |     en: templateUtil.tag `You’ll get a text at ${'p
     |                                                    ^
  27 | module.exports = translation
  28 | export type TranslationKeyType = $Keys<typeof translation>
  29 | 
```

**Comment by josephfrazier** [comment]
I'm guessing this has something to do with string length calculation. If you iteratively remove the emoji in the playground, you can see the content come back piece-by-piece. Not yet sure where the bug is, though.

**Comment by j-f1** [comment]
Since this is a bug with the Flow parser, I’d recommend using the Babylon parser (it *should* support the same features).

**Comment by amsul** [comment]
Yeah I can verify that switching to the babylon parser fixed it.

**Comment by thorn0** [comment]
This has been fixed. Most probably #6830.
