### ISSUE TITLE
--insert-pragma breaks GraphQL, CSS

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3557]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBHArnATgTwAQCKmuewAOlHngJYAmFAvhSADQgQAOM10AzsqACGWLBADuABWEJ+KQQDcIdViEG8YyAGaCANrzhsARlkFgA1nBgBlDqepQA5shhZMbWhDBbd+tvf1YMBImDgC2gs6uBiAAVrwAHgBCJuaWVoKhcAAy9nDeetEQ6DAcxQBM+b4gtlgByCAOJhwAFqg6KhxY9jAA6nQwzcgAHAAMbJ0Q+j1N9Z1wAfJ5bFhwGNQrwYJhEUjaBWz6odSRbiC89g46cEQQ8JXRMIKGfbQDyGVsLoLUOhcAwhBQuF6lBoEsQOh9AAVJ6yPb6BgMIA)
```sh
--insert-pragma
--parser graphql
```

**Input:**
```graphql
query Query {
  id
}

```

**Output:**
```graphql
SyntaxError: Syntax Error GraphQL request (1:1) Cannot parse the unexpected character "/".

1: /** @format */
   ^
2: 
 (1:1)
> 1 | /** @format */
    | ^
  2 | 
  3 | query Query {
  4 |   id
```

---
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABACzgGxxEAGhAgAcYBLaAZ2VAEMAnRiAdwAUmFaV6A3CBQAmREPWoxkAM3o5qcYgCNG9MAGs4MAMqlVFKAHNkMRgFcFIIRDDTZ84vvmMY7FQYC29Y2YsAragAeAEIq6ppa9O5wADL6cLZyFhCmMKQpAEwJ9iC6jE7IIJ6MalasUKKkjPowAOrCMJjIABwADMSVEPI1KqQFlXBOfPHEjHAAjqYUo670Hl5IMonE8u4U3ubL+gY4cACKphDwWRYw9Ip1Qg3I6cQm9BQ4WwDCEO6eBVDQwyCm8gAqZx4i3kAF8QUA)
```sh
--insert-pragma
--parser markdown
```

**Input:**
```markdown
# hello
```

**Output:**
```markdown
/\*_ @format _/

# hello

```

---
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwAEAdEAzCEtKYgBGAhgE5ZoC+IANCBAA4wCW0AzsqBeRAO4AFCgi4pSANwisAJvRCkOMZNlIAbDnAbFypMAGs4MAMpM9rKAHNkMcgFctIGRDAr1mhhc3kYg3ZYBbUht7RwArDgAPACFdAyNjUgC4ABkLODcNRwg7GCZcgCZMjxAzcm9kEAjoeSZyCxgAdVkYAAtkAA4ABgY6iE1G3SZKurhvCQyGcjgARztWab9SQOCkVSyGTQDWEIdNi0s1OABFOwh4YscYUmJmmTbkAoZbUlY1A4BhCACgyqhoSYgOyaAAqNzE6001GoQA)
```sh
--insert-pragma
--parser json
```

**Input:**
```json
{ "foo": "bar" }
```

**Output:**
```json
/** @format */

{ "foo": "bar" }

```

**Comment by azz** [comment]
From https://github.com/prettier/prettier/pull/3536#issuecomment-353722030 (@j-f1):

> Markdown:
> 
> ```markdown
> 
> ```
> 
> GraphQL:
> 
> ```graphql
> # @format
> ```

I guess in JSON it shouldn't do anything.

**Comment by duailibe** [comment]
@azz I'm gonna work on this now, thought about moving this to plugins, wdyt?

**Comment by duailibe** [comment]
One option I see possible right now is including a `pragma` object in plugins:

```js
module.exports = {
  languages,
  parsers,
  printers,
  pragma: {
    hasPragma(text) { /* ... */ },
    insertPragma(text, opts) { /* ... */ }
  }
};
```

**Comment by ikatyang** [comment]
How about `parser.hasPragma` and `printer.insertPragma`?

**Comment by duailibe** [comment]
What should happen if `--require-pragma` is passed but a parser does not implement `hasPragma`?

**Comment by azz** [comment]
Format anyway. If not they can just put that language in `.prettierignore`, it's a bit trickier the other way around.

**Comment by azz** [comment]
Added it to the milestone but don't feel obligated to get it done by then :smile:

**Comment by suchipi** [comment]
I'm gonna cut a 1.11 release, so I'm going to remove this from the milestone (but we could add it to a 1.11.1 or etc if we want to)

**Comment by duailibe** [comment]
I should probably leave this open until we get GraphQL, CSS and Markdown implemented

**Comment by j-f1** [comment]
Looks like Markdown support [has been added](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABACzgGxxEAGhAgAcYBLaAZ2VAEMAnRiAdwAUmFaV6A3CBQAmREPWoxkAM3o5qcYgCNG9MAGs4MAMqlVFKAHNkMRgFcFIIRDDTZ84vvmMY7FQYC29Y2YsAragAeAEIq6ppa9O5wADL6cLZyFhCmMKQpAEwJ9iC6jE7IIJ6MalasUKKkjPowAOrCMJjIABwADMSVEPI1KqQFlXBOfPHEjHAAjqYUo670Hl5IMonE8u4U3ubL+gY4cACKphDwWRYw9Ip1Qg3I6cQm9BQ4WwDCEO6eBVDQwyCm8gAqZx4i3kAF8QUA), while [JSON](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEpp16AVgQAeAISmz5CkrbgAGVU4YxE9CG0YLCiAJjDTEGUyC2QQV2guLDJVGAB1DhgAC2QADgAGDGyIUTypLDTsuAtmUIwyOABHbVwO6xI7ByRBcIxRW1xHXTHVNSE4AEVtCHgEvRgScQL2YuRYjC0SXCFZgGEIW3s0qGg2kG1RABVNxhHRAF93oA) is still broken, and [CSS](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEpp16AVgQAeAISmz5CkrbgAGVU4YxE9CG0YLCiAJjDTEGUyC2RwAiIMLDJVGAB1DhgAC2QADgAGLMpRPKksNOy4C2ZQjDI4AEdtXHbrEjsHJEFwjFFbXEddUdU1ITgARW0IeAS9GBJxAvZi5FiMLRJcIRmAYQhbezSoaFaQbVEAFQ3GYdEAXzegA), [LESS](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEpp16AVgQAeAISmz5CkrbgAGVU4YxE9CG0YLCiAJjDTEGUyC2QQITgCIgwsMlUYAHUOGAALZAAOAAYcylECqSw03My4MmZQjDI4AEdtXC7rEjsHJEFwjFFbXEddCdU1DIBFbQh4BL0YEnEi9lLkWIwtElwheYBhCFt7NKhoDpBtUQAVLcYx0QBfD6A), and [SCSS](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEpp16AVgQAeAISmz5CkrbgAGVU4YxE9CG0YLCiAJjDTEGUyC2QQAjACIgwsMlUYAHUOGAALZAAOAAYcylECqSw03LgLZlCMMjgAR21cTusSOwckQXCMUVtcR11x1TUhOABFbQh4BL0YEnEi9lLkWIwtElwhOYBhCFt7NKhodpBtUQAVLcZR0QBfD6A) still don’t have pragmas. Adjusting labels to reflect current status.

**Comment by ikatyang** [comment]
JSON5 pragma support is added in #4367 and the JSON one is disabled in #4333. 

Adjusting labels to reflect current status.

**Comment by ikatyang** [comment]
Opened #4682, #4683, and #4684 to track their statuses.
