### ISSUE TITLE
Don't read .editorconfig outside the project root

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#3558]
See https://github.com/prettier/prettier/issues/3461#issuecomment-353732090

Want to help? Make a small reproduction case!

**Comment by josephfrazier** [comment]
It looks like `editorconfig` supports a `root` option, so hopefully it's simply a matter of passing in the right path: https://github.com/editorconfig/editorconfig-core-js/tree/0c623dd8b5a8fc890c6e19fb0a17f7e983a1e015#parsefilepath-options

**Comment by azz** [comment]
#3559

**Comment by OliverJAsh** [comment]
I came here wanting the opposite behaviour. My editor respects my global EditorConfig (`~/.editorconfig`) and sets my tab width to that setting, but when I use my editor to run formatting (i.e. Prettier), it uses its own default tab width setting.

**Comment by OliverJAsh** [comment]
@lydell That's one usage of it. However for projects where there isn't an `.editorconfig` defined (yet), e.g. new projects or temporary workspaces, it's useful to have a global config so you don't have to spend time setting things up. Of course as a project matures, it's good to share the config so everyone uses the same style.

**Comment by lydell** [comment]
I usually use the default Prettier options for temporary workspaces. They’re temporary anyway.
