### ISSUE TITLE
TypeScript 2.7: exclamation marks in property declarations aren't parsed

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#3561]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgLICeAwhALYAO0CMOwAOlDjlAOZ4QAmcqAhEsywB0ASQBybTtxKwAThFSo4MgNwMAviAA0ICORgBLaJmSh0MuQHcACmYTGU6AG4R9HLSCwxkAM3SpMcNoARjLoYADWcDAAyuRh+qzIMDIAroEgHBBgPn4B2gkBMjBWoSyk6Dn+6QBWmAAeAEKhEVHR6KRwADIJcJV5Oikw5IMATH3pcTKFyCAwBORwmGAy+nru5CuwAOquMAAWyAAcAAzaGxABW6HkMxuLSo692jJwAI4p+i8l6GUVSL5VbQBUj6JKpdKYBIsRQARRSEHg420MHQQR2HH2yBGyNC+lQUJIpHKMygVHcKQCABVUfYAQE1GogA)
```sh
--parser typescript
```

**Input:**
```tsx
class MyComponent {
  ngModel!: ng.INgModelController;
}
```

**Output:**
```tsx
SyntaxError: '=' expected. (2:10)
  1 | class MyComponent {
> 2 |   ngModel!: ng.INgModelController;
    |          ^
  3 | }
```

**Expected behavior:**
It's valid TypeScript. `!` is a kind of type assertion. It's used to assert that even though the property doesn't have an initializer, we're sure it'll contain a value of the specified type in runtime, not `undefined`.

**Comment by thorn0** [comment]
Turns out I'm using the nightly builds of TypeScript, and this feature hasn't been released yet. It'll be part of TypeScript 2.7: https://github.com/Microsoft/TypeScript/pull/20075

**Comment by azz** [comment]
Thanks for catching this early! I've raised an issue in the parser here: https://github.com/eslint/typescript-eslint-parser/issues/424

**Comment by thorn0** [comment]
Same with the [`unique symbol` type](https://github.com/Microsoft/TypeScript/pull/15473).

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgGUBPAWwCMIAbAYWgGcZMBXMGCTQ4AHSkKFMcXABNoNUoVTxMuTpiSFWUVAEdWRRhWo0A3IX4BffiAA0ICAAcYqJslC5MmCAHcACk4SNkIXADcIVFFzP2ZkPBpGOAtKOTAAazgYYit8dABzZBZNC3EwCNwomLQoaMwYdzkM8lxC4osAK0YADwAheKSU3HI4ABl0OHroiwhWGCtxgCZhkrTMct8YUis4RjBMVBtQq03YAHVgmAALZAAOAAYLXYho-bkrX121rH8hi2ENVGEq3Bq6pCREYgaLkVDZNglRiZGhwACKrAg8FmFhguEoh1EJ2QU1RclQNEyDHItV8UGg7xArGiABV0T5AUVokYjEA)
```sh
--parser typescript
```

**Input:**
```tsx
interface SymbolConstructor {
  readonly iterator: unique symbol; 
}

```

**Output:**
```tsx
SyntaxError: ';' expected. (2:29)
  1 | interface SymbolConstructor {
> 2 |   readonly iterator: unique symbol; 
    |                             ^
  3 | }
  4 | 
```

**Comment by thorn0** [comment]
And [numeric separators](https://github.com/Microsoft/TypeScript/pull/20324).

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXmwEYB9ABgvMorIG4AdKDHAIwOzJaKLNN95I9eDJlmxh2ZAB4BBAKIkAYgoBMi2iAA0ICAAcYAS2gBnZKCyYIAdwAKWBKZTpUEAwBMtIdMZjIAZugANsZw2iyY6GAA1nAwAMq6kQZQAObIMJgArqEgbhBg-kEh2skhmDA2ESkAtuiFwTkAVsZSAEIR0bFx6NVwADLJcPXFOpkwumMqwzmJmGXIIDAAnrpwxmCYBvqeupuwAOruMAAWyAAcZNq7ECH7EboLu2twmKhD2phwAI6ZBp+V6BqdSQAQa2hC1QM6SyOWMyRSgTgAEVMhB4NNtDB0CxDm4TsgVJiIgZAvCAMIQaq1BZQaDvECZEIAFWxjlBIQAvhygA)
```sh
--parser typescript
```

**Input:**
```tsx
var a = 1_000_000_000;
var b = 0b1101_0101_1001;
var c = 0xAE_FE_2F;
```

**Output:**
```tsx
SyntaxError: ',' expected. (1:10)
> 1 | var a = 1_000_000_000;
    |          ^
  2 | var b = 0b1101_0101_1001;
  3 | var c = 0xAE_FE_2F;
```

**Comment by ikatyang** [comment]
@thorn0 Could you open issues one by one so that we can easily track them?

**Comment by thorn0** [comment]
@ikatyang Done: #3578, #3577

**Comment by maciejw** [comment]
this ! is called definite assignment assertions, someone might search for this phrase, I tried :)

**Comment by pelotom** [comment]
FYI, [TypeScript 2.7 has been officially released](https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/), so support for this syntax is very much needed.

**Comment by j-f1** [comment]
@pelotom We’re currently trying to figure out the name for the flag in the AST at https://github.com/eslint/typescript-eslint-parser/pull/432, and once we figure that out, we just need to  upgrade our parser version and print the `!`.

**Comment by osnoser1** [comment]
Same problem here! 😢

**Comment by DanielStep** [comment]
Any progress on this?

**Comment by cevek** [comment]
At this time no way to work with React with context
```ts
class Foo extends React.Component {
    context!: {my: string}
    render() { return this.context.my }
}
```
We cannot assign to context anything like `undefined!` because it's extended

**Comment by gcanti** [comment]
(as a temporary workaround) quoted properties aren't enforced by `strictPropertyInitialization`

```ts
export class Foo extends React.Component {
  // prettier-ignore
  'context': { my: string }
  render() {
    return this.context.my
  }
}
```

**Comment by j-f1** [comment]
You can use `// prettier-ignore` as a workaround until we fix this:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ5wAe8UAJrgEpzpgwB0AwhALYAO0CMOwAOlBw4A9CJwcATnBgwAlnEkBaOQHMoEaYOGRYpGAEIkfNgE9jmGJLlRVAX205plRQAoAlHycyArpKEwABZymIy68GSMZjgOULEgADQgEBzy0JjIoOiSkhAA7gAK2QgZKOgAbhByFIkgWDDIAGboqJhwSQBGkvQA1jIAyhz0NqrIVj7tIBQQYE0tbUk2bZIwBd2qbOhzrZMAVpgkAELdYH0w-ehscAAyNnDbC8k+MBzPAEwPk0OSy8ggMKYOHBMGBrKlalIbDAAOrVILIAAcAAYklIIG1od0OH8pMDFOV7klpABHHxyaRrdAbLZIZo7JJtNhyMaSCYMkaoOAARR8EHgnySMHQHVhFHhSDegu6clQI1YbE2fw0UEJIB8bQAKsLSnS2nY7EA)
```sh
--parser typescript
```

**Input:**
```tsx
class Foo extends React.Component {
  // prettier-ignore
  context!: {my: string}
  render() { return this.context.my }
}

```

**Output:**
```tsx
class Foo extends React.Component {
  // prettier-ignore
  context!: {my: string}
  render() {
    return this.context.my;
  }
}

```

**Comment by j-f1** [comment]
[`typescript-eslint-parser` v14](https://github.com/eslint/typescript-eslint-parser/releases/tag/v14.0.0) has been released, so we just need to bump the version and print the `!` now.

**Comment by strongui** [comment]
Yea prettier keeps complaining and breaking on files, that contain code like this:

`const { controlsInitialized, status } = store!.appStore;`

**Comment by j-f1** [comment]
Can you open a new issue and fill out the issue template @strongui?

**Comment by strongui** [comment]
@j-f1 [Done.](https://github.com/prettier/prettier/issues/4474)
