### ISSUE TITLE
Arrange array elements aplhabetically

### ISSUE THREAD

**Issue by aberba** [prettier/prettier#3569]
Arrays (string, numbers) are more readable when arranged alphabetically.

**Comment by azz** [comment]
Hi! This is not something that is within the scope of Prettier because it can change the behaviour of your program.

**Comment by thorn0** [comment]
Sorting object keys in **JSON**, on the other hand, is safe and could be a useful feature.

@azz If I come up with a PR for this (sorting keys in JSON), how likely will it be accepted?

**Comment by azz** [comment]
No it's not safe. You can't make any assumptions about how the code interpreting the JSON file will work. Arrays are ordered lists, not sets.

**Comment by thorn0** [comment]
I'm talking about object keys in JSON, not arrays.

**Comment by thorn0** [comment]
UglifyJS 1 had it and I find myself still using it sometimes for formatting JSON just because of this small feature. Of course, it's not safe in JS, but in JSON it should be okay in 99,(9)% of cases. We can have it off by default though.

**Comment by azz** [comment]
While that might be safe but I find it weird to _always_ sort JSON properties. e.g. package.json should have `"name"` and `"version"` at the top.

**Comment by thorn0** [comment]
So what about an option?

**Comment by azz** [comment]
We don't add options for this kind of thing (see #40). I'd suggest using ESLint (prettier-eslint) to do this.
