### ISSUE TITLE
TypeScript 2.7: `unique symbol` type isn't parsed

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#3577]
See https://github.com/Microsoft/TypeScript/pull/15473

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgGUBPAWwCMIAbAYWgGcZMBXMGCTQ4AHSkKFMcXABNoNUoVTxMuTpiSFWUVAEdWRRhWo0A3IX4BffiAA0ICAAcYqJslC5MmCAHcACk4SNkIXADcIVFFzP2ZkPBpGOAtKOTAAazgYYit8dABzZBZNC3EwCNwomLQoaMwYdzkM8lxC4osAK0YADwAheKSU3HI4ABl0OHroiwhWGCtxgCZhkrTMct8YUis4RjBMVBtQq03YAHVgmAALZAAOAAYLXYho-bkrX121rH8hi2ENVGEq3Bq6pCREYgaLkVDZNglRiZGhwACKrAg8FmFhguEoh1EJ2QU1RclQNEyDHItV8UGg7xArGiABV0T5AUVokYjEA)
```sh
--parser typescript
```

**Input:**
```tsx
interface SymbolConstructor {
  readonly iterator: unique symbol; 
}

```

**Output:**
```tsx
SyntaxError: ';' expected. (2:29)
  1 | interface SymbolConstructor {
> 2 |   readonly iterator: unique symbol; 
    |                             ^
  3 | }
  4 | 
```

**Comment by ikatyang** [comment]
Opened https://github.com/eslint/typescript-eslint-parser/issues/426.
