### ISSUE TITLE
TypeScript 2.7: numeric separators aren't parsed

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#3578]
See https://github.com/Microsoft/TypeScript/pull/20324

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXmwEYB9ABgvMorIG4AdKDHAIwOzJaKLNN95I9eDJlmxh2ZAB4BBAKIkAYgoBMi2iAA0ICAAcYAS2gBnZKCyYIAdwAKWBKZTpUEAwBMtIdMZjIAZugANsZw2iyY6GAA1nAwAMq6kQZQAObIMJgArqEgbhBg-kEh2skhmDA2ESkAtuiFwTkAVsZSAEIR0bFx6NVwADLJcPXFOpkwumMqwzmJmGXIIDAAnrpwxmCYBvqeupuwAOruMAAWyAAcZNq7ECH7EboLu2twmKhD2phwAI6ZBp+V6BqdSQAQa2hC1QM6SyOWMyRSgTgAEVMhB4NNtDB0CxDm4TsgVJiIgZAvCAMIQaq1BZQaDvECZEIAFWxjlBIQAvhygA)
```sh
--parser typescript
```

**Input:**
```tsx
var a = 1_000_000_000;
var b = 0b1101_0101_1001;
var c = 0xAE_FE_2F;
```

**Output:**
```tsx
SyntaxError: ',' expected. (1:10)
> 1 | var a = 1_000_000_000;
    |          ^
  2 | var b = 0b1101_0101_1001;
  3 | var c = 0xAE_FE_2F;
```

**Comment by azz** [comment]
This one just requires bumping our TS version.

**Comment by j-f1** [comment]
Should there be an option to automatically insert these every three characters? (`100000` → `100_000`)

**Comment by thorn0** [comment]
@j-f1 Sounds interesting but it'll be making code incompatible with older version of TS. So it's rather an idea for a TSLint rule.

**Comment by j-f1** [comment]
That’s why I proposed an option. Plus, the option can be applied to regular JS, too.

**Comment by duailibe** [comment]
I also think this makes more sense as ESLint/TSLint

Also, let's not derail issues like this, if you want to suggest an option please open a new one

**Comment by thorn0** [comment]
In this project, the standard response to the "What about an option then?" question is:

> We don't add options for this kind of thing (see #40)
