### ISSUE TITLE
PR preview playground seems broken

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#3581]
For example: https://deploy-preview-3580--prettier.netlify.com/playground/

![image](https://user-images.githubusercontent.com/8341033/34357946-5bcf7884-ea86-11e7-8573-c34872bbcda2.png)

Probably caused by some changes in #3536, cc @azz.

**Comment by duailibe** [comment]
I've noticed that, thought it was related to my PR... looking at this ATM

**Comment by duailibe** [comment]
Can't work on this right now, if anyone wants to take a shot at it

**Comment by kootoopas** [comment]
Running `yarn start` locally gives more elaborate errors (`NetworkError`):
<img width="1371" alt="screen shot 2017-12-27 at 8 20 59 pm" src="https://user-images.githubusercontent.com/601001/34389641-8681e720-eb43-11e7-881d-8cb8bc50bb10.png">
