### ISSUE TITLE
Auto-insert `_` in numeric literals

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3583]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGADJrmQBoQQAOMAltAM7KgCGATrRAO4AKdClK1AbhCQCZ4Q1cjGQAzagBtycfACNa1MAGs4MAMqElJKAHNkMWgFdZIPhDDipM-Dpm0YzRboC21K9NMArcgA8AQooqaurULnAAMjpwHjYERjCECQBMsaZatPbIIHLUcgCektCChLQ6MADq-DAAFsgAHOj4pRAyFYqE2aVw9lwx+LRwAI5GJINO1K7uSBKe+DIuJAbGpuQ6upJwAIpGEPBp+DB5VXy1yMmHiiSS6wDCEC5u2VDQ-SBGMgAqeRyzMgC+-yAA)

**Input:**
```jsx
100000000
```

**Output:**
```jsx
100_000_000;

```

**Expected behavior:**
```jsx
100000000;

```

This should be implemented as an option so that people don’t run into syntax errors when coding for non-esnext-compatible targets, kind of like how `--trailing-comma` has the `es5` option.

Ref https://github.com/prettier/prettier/issues/3578#issuecomment-353971726.

**Comment by azz** [comment]
Thousands separators are not universal and may confuse some people.

**Comment by j-f1** [comment]
What other separators are used besides thousands?

**Comment by azz** [comment]
> Hindi uses a 2-digit grouping, except for the 3-digit grouping for denoting hundreds: 12,34,56,789.00

https://docs.microsoft.com/en-us/globalization/locale/number-formatting

**Comment by j-f1** [comment]
However,

> the 3-digit group is used for most cultures.

[Another website](http://www.statisticalconsultants.co.nz/blog/how-the-world-separates-its-digits-m.html) seems to indicate that everyone groups by 3, except China (groups of 4, sometimes used in Japan, too) and India (groups of 2). It also says that people in China often don’t group digits at all.

It also appears to be common to only start grouping when there are at least two more digits in the number than there are in a group.

**Comment by hawkrives** [comment]
Japanese does 3-digit groupings, but starts after 1000 - 10,000,0000 vs 100,000,000, if I recall correctly.

**Comment by thorn0** [comment]
I read somewhere that in Poland, they use the separators only for numbers greater than 10000.

**Comment by lydell** [comment]
I guess this would also mean _removing_ underscores in numbers?

I'm onboard with this, but perhaps it's better to wait for 1 or 2 runtimes to support a feature before starting to use it in general formatting? In other words, I think it's better to wait than adding a flag here. (The flag might be needed eventually anyway, but we'll see then).

**Comment by bakkot** [comment]
This isn't yet part of JavaScript; definitely such an option should not go in until it's stage 4 at the very earliest.

For my part, I don't think it makes sense for prettier to add them: as I understand it numeric separators are meant to be case-by-case; that is, where it makes sense to put the separators depends on what the value is intended to represent. This is especially clear for hex digits: for example, for RGB values you'd probably want `0xfff` or `0xff_ff_ff`, but never `0xf_ff`, `0xf_ff`, or `0xfff_fff`.

I also don't think it makes sense for prettier to remove them. By way of analogy, I think the choice of where to put `_`s is pretty similar to the choice of whether to write a numeric literal in decimal or hex, which prettier also preserves. I know prettier's ethos is generally to ignore formatting decisions, but for this particular case the choice of formatting depends on something prettier can't know about from the AST, namely, what kind of value is being represented. 

That is: I think prettier should not add any options, and should add underscores in the same places they were in the original.

Ping @rwaldron and @samuelgoto, the champions of the proposal, in case you have any thoughts about how numeric separators should be used.

**Comment by suchipi** [comment]
I'm in agreement with @bakkot; let's just leave them as-is

**Comment by azz** [comment]
Agreed. Preservation sounds like the best bet here.
