### ISSUE TITLE
Export the logger for plugins?

### ISSUE THREAD

**Issue by taion** [prettier/prettier#3585]
Plugins might need to log errors/&c. too. However, the logger currently isn't exported from the top-level entry point.

**Comment by azz** [comment]
I don't think any of the current printers/parsers use the logger, it's just for the CLI.

**Comment by taion** [comment]
I'm going through prettier-python bit by bit... specifically, looking at https://github.com/prettier/prettier-python/blob/b61ddd6b84db5212b9a27f0beade94687e6fbb95/src/parser.js#L15-L19

It seems a bit odd to me that it's throwing the contents of stderr, rather than logging them, then throwing `executionResult.error`.

**Comment by azz** [comment]
Seems fine to me, Prettier will log the error correctly, no?

**Comment by taion** [comment]
Well, you lose `executionResult.error`. But perhaps for a CLI thing, that doesn't matter.
