### ISSUE TITLE
SyntaxError: A trailing comma is not permitted after the rest element

### ISSUE THREAD

**Issue by Cap32** [prettier/prettier#3586]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExMDp8BOcGANJgL6YC8mEARgFYDcIJIEADjAJbrKgcC3WAHVuAExgALZAA4ADGxgBDOmMkykAJjZphAcwA2cAIoBXCPGQAzZYbRwlBZd0MGAwhAC2X5chBQ0HCsIHTOYADWcDAAyhzKYAbIMARmjiAMaAAeAELhUbHKXnAAMsLBSLb26fEEDgT+dKoAnobQIQ5e3Mmp6WYOACqqaDZ2DmzC9TAACs76vqPVbEQAjmbcRLPK836VYzUEEA4izhz+gsRwBABuwWzKBIcA7tMPCCMoytcQEiHiEGBFuMQMoMED0hAzDAOFCtODyOQgA)

**Input:**
```jsx
const { ...rest, } = obj;
```

**Output:**
```jsx
SyntaxError: A trailing comma is not permitted after the rest element (1:16)
> 1 | const { ...rest, } = obj;
    |                ^
```

**Expected behavior:**
```jsx
const { ...rest } = obj;
```

**Comment by j-f1** [comment]
Since Prettier can’t parse the code, it’s unable to remove the comma.

**Comment by ikatyang** [comment]
Trailing comma is not allowed to be there, see [Rest/Spread Properties Proposal](https://tc39.github.io/proposal-object-rest-spread/#prod-ObjectBindingPattern).

You may want to use `--parser typescript` in this case as TS Spec allowed it to be there.
