### ISSUE TITLE
Flow type generic with array breaks inside generic brackets

### ISSUE THREAD

**Issue by ppvg** [prettier/prettier#3587]
Prettier seems to really like adding spacing inside the generic type syntax when the type inside the brackets is an array, like `Promise<{ ... }[]>`. This is unlike generics with a plain object type  (e.g. `Promise<{ ...}>`), which are formatted [without extra whitespace](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEADgE4QC2OAznAPIBGAVnNgBQCUS+ACqRdQDzB8OACaco6MnTjEANPigBDMnE6UYxHFADm8xdhwA3VfjoQIAGziKo+AL4A+fMAA6t-MTgx0xWz3JUcAB0npSWxiwA2gC6bADcbnYgsiAQhLjQlMigisSkAO5cuQhZKMkgiurIqIoW1Cl0xPoA1l4AyoT6WtrIGuhwKSIQYNW19SBa1MQwPIraZIqjdQMgDJQAHgBCTWCtMG3KcAAyWnBL4xDoMIRXAEznK53EU8ggdIp0AJ4W0OUkWjAAOqiGAAC2QAA4AAwpEgQaiApqEV7lTwAR3QOE8s3miyQNWWKWoFF6xH6RO6VgAiugIPAHikYB9gSIwchboymjgLN0AMLkBavKDQM4pdDUAAqH1KBOodjsQA) (maybe in relation to #1486).

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEADgE4QC2OAznAILHECGAngPKosBGAVnNpQBQBKJPgAKpCtQA8wfDgAmIqOjIc4xADT4oDMnBGUYxHFADmWhthwA3ffg4QIAGzgMo+AL4BtALoA+fGAAHXd8YjgYdGJ3cXIqOAA6cMpnW35fQQBuEI8QkIwsXAISOOo6RlZ2bl4YAWExCXiZEPw5RW0VNU0W7V07Q2MzDR7LXFsRB2dXKBzfAODQ8MjohtLE5NS4dJ8snJANEAhCIqhKZFAGeggAd1FLhDOUfZAGQ2RUBidqA45GMABrCIAZUIlhMpmQRnQcAO8ggYHen2+IBM1GIMHEDFMZAYiK+MJAXEoAA8AEJ-QEwIF9AAyJjgeOREHQMEILIATIyCaDiGjkCAOAwOEwnNBniQTDAAOoKGAAC2QAA4AAwHErUKWMQj857hACO6Bw4Ux2NxSA++IO1AokOI0Kt4JcAEV0BB4FyDjAhTL5PLkOzPYwcE5wQBhcg4-lQaAMg7oagAFSFjwt1A8HiAA)

**Input:**
```jsx
function promiseArrayOfObjects(): Promise<{ id: number, name: string, active: boolean }[]> {
  return Promise.resolve([]);
}
```

**Output:**
```jsx
function promiseArrayOfObjects(): Promise<
  { id: number, name: string, active: boolean }[]
> {
  return Promise.resolve([]);
}
```

**What's the problem?**

The way prettier formats this conflicts with the ESLint rule `flowtype/generic-spacing`. There is a [proposal for allowing line breaks in multi-line generics](https://github.com/gajus/eslint-plugin-flowtype/issues/220), but since this is a generic with a single type, I don't think that would apply here. 

**Expected behavior:**

Preferrably, prettier would add line breaks to the object type:

```jsx
function promiseArrayOfObjects(): Promise<{
  id: number,
  name: string,
  active: boolean
}[]> {
  return Promise.resolve([]);
}
```

**(Failed) workaround attempt:**

With code from the **expected behaviour** above as input, prettier still adds whitespace:

```jsx
function promiseArrayOfObjects(): Promise<
  {
    id: number,
    name: string,
    active: boolean
  }[]
> {
  return Promise.resolve([]);
}
```

**Comment by lydell** [comment]
Thanks for your issue!

> **What's the problem?**
>
> The way prettier formats this conflicts with the ESLint rule `flowtype/generic-spacing`.

We recommend turning off all stylistic ESLint rules that conflict with Prettier. See [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier). Since this issue seems to be only about an ESLint rule conflict, I'm going to close it. Please comment if I missed something!

**Comment by ppvg** [comment]
@lydell fair enough, although I think it would make sense for prettier to format `Promise<{...}[]>` similar to how it formats `Promise<{...}>`.

**Comment by lydell** [comment]
@ppvg Feel free to edit the issue, or open a new one. There are a few issue open around generics already, so it's worth spending some time searching the issue tracker first.
