### ISSUE TITLE
CSS in JS semicolon missing in template literal interpolation

### ISSUE THREAD

**Issue by greggb** [prettier/prettier#3589]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBBTBeTDATwBs4ATAOgEMADAHSk0wCMIAncudpTAZgAOAD0IQSAS3KYAJMDQQAtnADCYjgF9GzcuLQCS1Ir3FQJUOAFoWJCGADWAbkYMoAeleNGkKBkwAhfEIYUgpKFhdtXX1DY1MTS2tbRy1WDi4efmFRCSlZeSVVG3ZNKFoQABoQCAEYcXRkUGp2dggAdwAFJoQ0ZBAKkGoMZAAzahI0OEqWdmp7OBgAZQFZkwBzZBh2AFdJkHJbEbGJypMJ9hh2mdWFakPx3YArNCE-GbnF6iUAGXi746qtjABICAEx-XbLdhnXosagsUjQfoCdgmGAAdUkMAAFsgABwABkqyIgEzRMwEvX67DgAEctuJqZdqNdbkhRvdKhMFOINttdmg1mQAIpbCDwcGVGBwjHkbHIEGSmbiMyrVQKG69KDQOD9LYTAAqcJ6bKOcHU6iAA)
```sh
--arrow-parens 
--prose-wrap 
```
**Input:**
```jsx
// doesn't work
const A = styled.a`
  border: 3px solid ${someColor}
  display: inline-block;
`

// works
const B = styled.b`
  display: inline-block;
  border: 3px solid ${someColor}
`
```

**Output:**
```jsx
SyntaxError: (postcss) CssSyntaxError Missed semicolon (2:21)
  1 | 
> 2 |   border: 3px solid @prettier-placeholder
    |                     ^
  3 |   display: inline-block;
  4 | 
```

**Expected behavior:**
Semicolon should be inserted after a rule even if it contains an expression. This only happens when the interpolation is not the last rule.

**Comment by j-f1** [comment]
Why don’t you have a `;` after `${someColor}`?

**Comment by greggb** [comment]
It was an oversight. Prettier catches this in every other case.

**Comment by j-f1** [comment]
That’s because semicolons in JS are optional, whereas they’re required in CSS, so Prettier won’t be able to parse your CSS if they’re missing.

**Comment by ikatyang** [comment]
FYI, [declarations are separated by semicolons](https://www.w3.org/TR/css-syntax-3/#syntax-description), it's a syntax error if there's not a semicolon between declarations.

---

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBBTBeTDATwBs4ATAOgEMADAHSk0wCMIAncudpTAZgAOAD0IQSAS3KYA7gAtx8Rs3Li0AktSK9xUCVDgBaFiQhgA1gG5GtEABoQEATHHpkoau3YRpABQ8I0ZBBqADcISTtgjGQAM2oSNDh7FnZqczgYAGUBNJ0Ac2QYdgBXJJByU1j4xPsdRPYYH1S8gFtqKoSygCs0IQAhVPSs6ha4ABkdOA6ah2KYATmAJmmynPZ6oJZqFlJoSIF2HRgAdUkYWWQADgAGewOIROPUgSCDuHqQqft2OABHYvEPya1Fa7SQcU69kSLXEhRKZTQ+TIAEVihB4Ct7DBtqdyOdkIssalxHo8gBhCAtNpBKDQL4gYqJAAq20C4OqcAAvpygA)

**Input:**
```jsx
const A = styled.a`
  border: 3px solid white
  display: inline-block;
`
```

**Output:**
```jsx
SyntaxError: (postcss) CssSyntaxError Missed semicolon (2:21)
  1 | 
> 2 |   border: 3px solid white
    |                     ^
  3 |   display: inline-block;
  4 | 
```

**Comment by greggb** [comment]
Sure, just thought this is something Prettier could discern. Thanks for the feedback
