### ISSUE TITLE
.prettierignore displays no output when running on ignored file breaking editor integrations

### ISSUE THREAD

**Issue by mitermayer** [prettier/prettier#3590]
This may seem at first glance the ideal behaviour, when trying to run the prettie CLI on an ignored file. However for editor integrations such as `vim-prettier` where it does not have any knowledge about the ignored files from `.prettierignore` it means it will then wipe all the contents of the ignored file.  

see https://github.com/prettier/vim-prettier/issues/92

Would be great if there was an `option` or any other way to simply print the ignored file as it is instead of just having an empty `stdout`, other valid options would be display an error or warning message.

@ikatyang, @azz, @suchipi  please let me know what are your thoughts around it, happy to submit a PR for this

**Comment by duailibe** [comment]
Sounds reasonable to me to warn if the use passed a specific path (i.e. not a glob) of an ignored file

**Comment by ikatyang** [comment]
I think adding a warning (only when `--stdin-filepath` applied) for it should be better, but I'm not sure if it can fix your case since IIRC you seem to use `--loglevel silent` for `vim-prettier`?

**Comment by azz** [comment]
This sounds like a bug.

```bash
echo "foo()" > foo.js
echo "foo.js" > .prettierignore
prettier --stdin-filepath=foo.js < foo.js
```

Should output the contents of `foo.js`

**Comment by azz** [comment]
So basically we want two modes:

* With `--write`, don't read or write to the ignored file
* Without `--write`, read the ignored file and output as-is.

**Comment by mitermayer** [comment]
@azz  I really like your approach!

I think `Without --write, read the ignored file and output as-is.` is exactly what we need for `vim-prettier`

**Comment by hsribei** [comment]
Thank you all for this! <3
