### ISSUE TITLE
Enforce blank lines around imports/exports

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3597]
Prettier preserves up to one blank line between code segments, but I think there's a case where we should always force a blank line: Imports and exports.

```js
import { bar } from 'bar';
import baz from 'baz';
const foo = bar({});
export default foo;
```

Should expand to:

```js
import { bar } from 'bar';
import baz from 'baz';

const foo = bar({});

export default foo;
```

Thoughts?

**Comment by j-f1** [comment]
👍, especially because `import` and `export` are the same length.

Where should `export { foo } from 'bar'` go?

**Comment by azz** [comment]
I usually do it like this:

```js
import { bar } from 'bar';
import baz from 'baz';

export { foo } from 'bar';

const foo = bar({});

export default foo;
```

**Comment by duailibe** [comment]
I'm against this as standard prettier formatting, but should be a rule of #2068 if we ever do that

**Comment by vjeux** [comment]
This is a huge can of worms. At Facebook we're in the process of solving it via an eslint plugin with autofix that reorders all the require/imports but it's been difficult.

There's a bunch of cases where you have imports and code mixed together, how do you define when imports end? Do you force a new line after each group of imports?

```js
import { MyConstants } from 'MyConstants';
const { A, B, C } = MyConstants;
import ...;
```

Same for exports, they are often in between the code, so it's not as clear when to put a \n.

My gut feeling is that we're unlikely going to find something that works all the time and if/when we do so, it's going to be very complex and not provide a ton of value compared to the frustration it's going to cause. But I could be wrong :)

**Comment by jeysal** [comment]
One reason why I'd love to see this is that using my vim + TS language server setup, the "add import" quick actions tends to insert new import declarations into the empty line below the last import declaration / above the first statement. I then need to either need to re-add the empty line manually or often do not notice at all.

**Comment by jeysal** [comment]
As for the details of where we should enforce empty lines, I think putting them between a statement and a module declaration should suffice, between different kinds of module declarations (e.g. an import and an export) I would worry that people might write something like
```js
import a from './a';
export { a };
import b from './b';
export { b };
```
and then have it exploded to twice as many lines.
Of course this code should be using `export from` in the first place, but I suspect in the real world code like the above might exist nevertheless.

**Comment by azz** [comment]
"Too hard basket" for now 😢

**Comment by lydell** [comment]
Also, since it does not seem to have been mentioned in the discussion: There's also [import/newline-after-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/newline-after-import.md). It has autofix!

**Comment by azz** [comment]
Oh that's so much better than the horrible `padding-line-between-statements` config I had set up!
