### ISSUE TITLE
GraphQL: Support new stuff in the latest version

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#3601]
- Block strings: https://github.com/facebook/graphql/pull/327
- Descriptions as strings: https://github.com/graphql/graphql-js/pull/927
- New multiple inheritance syntax: https://github.com/graphql/graphql-js/pull/1169
- `extend type`: https://github.com/graphql/graphql-js/pull/1117/files
- `UndefinedType`: https://github.com/graphql/graphql-js/pull/1117/files
- Empty types are no longer allowed: https://github.com/graphql/graphql-js/pull/1171

This file contains all syntax: https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-kitchen-sink.graphql

To try to support both old and new syntax we should set these options:

```js
{
  allowLegacySDLEmptyFields: true,
  allowLegacySDLImplementsInterfaces: true,
}
```

**Comment by vjeux** [comment]
@lydell thanks for the comprehensive list of changes! I sent https://github.com/prettier/prettier/pull/3605 to fix all the things you mentioned that I could. Two things have been committed but not yet released :(
