### ISSUE TITLE
Ugly: 'do-expression' line break in JSX

### ISSUE THREAD

**Issue by bryceosterhaus** [prettier/prettier#3602]
_Tried to see if another issue was out there for this but couldn't find one._

How come do-expressions in a JSX expression cause a new line break and indentation? It's really ugly IMO and adding further indentation causes more headache for large jsx chunks within a do statement.

It would be great to see this changed and fall inline with conditional operators in a jsx expression

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpRszVwzrVR8DDvlH4uAHjo4AbgD4RYpaOB0IrRcq34cqId3RwW7QdrMB6c-gB0tzWbEBffKQDOcDaYfLLNu1+98R3stR2CApQ4Q5WADDwAyeOjlSWl5ZJSYCVcABwBDQXMFCO0JczTi73CzMor7Jg5HEAAaEAgc3GhXZFA86moIAHcABT6EbpQ8mQgcOhaQPNcYZFQ8kndWgCNqPLAAa14AZXywHCgAc2Q41rUwFbWNkDP3ahhhnfOAWzz79bhWgBWrgAHgAhHb7I55T5wAAyZzgv0eEHQMByqIATEj-iB8tQXsgQJs8psAJ7kKDzHLUM4wCizGAAC2QAA4AAytakQdwUHY5QnUuAvGSI1o8ACO6BwPHeeS+PyQqz+rXcnxwV2ohhVZ3OJDgAEV0BB4NjWjASfS6EzkBizTscCQdQBhCCfb6EqDQUUgdDuAAqJImSvcYSAA)

**Input:**
```jsx
{do {
 \\ ...
}}
```

**Output:**
```jsx
{
    do {
     \\ ...
    }
}
```

**Comment by vjeux** [comment]
Here's a fix: https://github.com/prettier/prettier/pull/3607

**Comment by bryceosterhaus** [comment]
You guys are awesome. Thanks for the hard work!
