### ISSUE TITLE
1.10 Release

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#3603]
January 10 will be the first anniversary of prettier, it should be a good time for a release :) Creating this issue to start the process.

I have started writing a retrospective blog post to put at the beginning of the releases note: https://github.com/prettier/prettier/releases (only people with commit access can see it for now).

**Comment by azz** [comment]
Milestone: https://github.com/prettier/prettier/milestone/9

What do we think about moving the release notes to a Docusaurus blog like [Jest does](http://facebook.github.io/jest/blog/)? Having them as diff-able mardown files would be nice.

**Comment by vjeux** [comment]
@azz I'm in favor. I used the github release notes feature because it was there but it's not ideal.

**Comment by azz** [comment]
Cool, I'll put together a PR to copy all the older release notes across.

**Comment by duailibe** [comment]
[off-topic] @vjeux FYI is great seeing you here :)

**Comment by duailibe** [comment]
I've added issues and PRs to the milestone according to https://github.com/prettier/prettier/compare/1.9.2...master

**Comment by taion** [comment]
Might be worth considering flagging the plugin API as "experimental" ahead of any upcoming release.

It's very neat, but there are some limitations right now like plugins not being able to define config options, &c.

Given that, it might be good to discourage third-party plugins and disclaim standard SemVer guarantees until everything is fully in place (and e.g. use tilde ranges in first-party plugins instead of caret ranges).

Depends on the timing of a v2 release, though.

**Comment by azz** [comment]
> Might be worth considering flagging the plugin API as "experimental"

I don't know how much more we can possibly warn...

![image](https://user-images.githubusercontent.com/1297597/34459289-48188bba-ee40-11e7-846f-96ea5e1efe5e.png)

> but there are some limitations right now like plugins not being able to define config options

This was started in #3433, but may require some tweaks before we can get it running in external plugins.

**Comment by taion** [comment]
My bad, I thought that just referred to "it's only on master and hasn't landed in a release yet".

**Comment by azz** [comment]
Opened #3615 to track the missing bits.

**Comment by taion** [comment]
What I mean is – for the 1.10 release, that should probably say "experimental" rather than "unreleased".

**Comment by azz** [comment]
I'd like to be able to transition in to more of a "beta" mode for the plugin API in 1.10 if we can get everything together by then. In 2.0 we do a full release (maybe Python support will be usable by then).

**Comment by taion** [comment]
Sure. I think we're saying the same thing. I was just under the impression that some of those caveats would go away with the release. If not, then everything's good.

**Comment by duailibe** [comment]
@vjeux do you want to open a PR with the post draft and we can iterate on release notes? :)

**Comment by vjeux** [comment]
@duailibe I'd like to change the tone of what I've written so far to be less about me before making it visible to a wider audience if that makes sense.

**Comment by GrahamCampbell** [comment]
What's changed regarding parsers? Is `postcss` as a parser option deprecated now? The docs are conflicting currently.

**Comment by vjeux** [comment]
@azz @duailibe @ikatyang, I'm now happy with the "blog post" part of the release notes. Is any one of you interested in driving the release and writing the notes?

**Comment by azz** [comment]
I'll write up the release notes today. We should also do some smoke tests on large codebases as we usually do.

**Comment by SimenB** [comment]
Just ran prettier master against Jest, and there are 0 changes, which is pretty cool :D

**Comment by azz** [comment]
## Prettier 1.10: "Complete Edition"

**Comment by azz** [comment]
Just ran it on React (they're on 1.8.1 but I ran 1.9 first) and there were also zero changes. :tada:

**Comment by vjeux** [comment]
That’s really exciting :)

The big new feature this release is Vue Sfc support, we should try it out on a few codebases

**Comment by vjeux** [comment]
Are we on-track for doing the release on the 10? Who is going to press the button?

**Comment by MichaelDeBoey** [comment]
There are still some issues (#2597 & #3664 & the blogpost (#3659) of course) open when looking at the milestone... 😕
https://github.com/prettier/prettier/milestone/9

**Comment by duailibe** [comment]
#2597 unlikely to make it to the release

**Comment by azz** [comment]
#3664 is good to go, just waiting on CI now.

**Comment by azz** [comment]
What time should we do the release? Morning of the 10th US time?

**Comment by vjeux** [comment]
I would figure out when it fits your schedule best and work around that. But if you have some latitude, morning of the 10th US time would work great for me :)

**Comment by azz** [comment]
I'll do the release in 4-6 hours.

**Comment by azz** [comment]
🍰 **https://prettier.io/blog/2018/01/10/1.10.0.html**
