### ISSUE TITLE
Long CSS rules in template literals should not have line breaks

### ISSUE THREAD

**Issue by ericclemmons** [prettier/prettier#3608]
**Prettier 1.9.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt8B3ASxgAsAVRuAWzgAoBnGAT0pwCAOkqkARnEoADADpQ8ecVMp5gCpUoD02vKzo88PRhCoE8pSmql5ocZXShwAhJq0ZSBAk4DmSPAASYC4MbAgMHgBKPABeAD53LQ9wyJEmDjgRQwAxKkoACTg6X0Z8AH48AAY8AM9vPyKSstDU6IBfDDQ8AEYAVi7q3oG0AG53doUZKIUQABoQCJg6aB5kUFJscJoABU2ENZRSADcIOgJ5kFI+ZDJKHjgFiWxSMABrOBgAZU8wP2QYNhyI8QAQIGBblYHgsnA9cDsXr52KRIfcQQArHhoABCL3eny+pE4ABknHBUdDFuQYBhqQAmCkgzzYOHIEASSSCaCXMJOGAAdXOTGQAA4qgswhAHvyXhg2WE4HDjuSFtg4ABHch0NUI0hIlFIO6Uh7sOgAoEgnh+IQARXIEHgjIWMEkgoIwqQdOdLzolD8AGEIOxkWyoPZLuQHsxJIcjXB2u0gA)

**Input:**
```jsx
export default withTheme(styled.label`
  label {
    // This should all be one line!
    padding: ${(props) =>
        props.theme.isFullHeight ? 0 : paddingHeight(props)}px 15px 0 15px;
  }
`)

```

**Output:**
```jsx
export default withTheme(styled.label`
  label {
    // This should all be one line!
    padding: ${props => (props.theme.isFullHeight ? 0 : paddingHeight(props))}px
      15px 0 15px;
  }
`);

```

**Expected behavior:**

The `padding` rule needs to stay as one line, otherwise the CSS rule breaks.  (Thankfully we had snapshots in place.)

Content within the template literal shouldn't have newlines introduced.

**Comment by duailibe** [comment]
I don't quite understand what is the problem here.. doesn't the lib support the following?
```css
padding: 0px
  15px 0 15px;
```

> Content within the template literal shouldn't have newlines introduced.

Yeah this is not true at all, this is what's expected of Prettier:

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAywEMAjOLAAmEiwgCcl6BiABl4G4ADpVzEoAcw4BGbgIAe9AKxyAvmT4gANCAgCYRaKmShKrVhADuABRMJDKSiQhFcmkJXTIAZpSyo4W6lZKMABrOBgAZSEwInFkGFYAV38QXAgwLx8-LVi-VhhLILEAW0pM3xSAK1RZACEg0PCIymK4ABlYuHLs7USYAT6AJm6UoVY85BBqGmxoVwFWWJgAdWcYAAtkAA5uLQWIP2WggUmFuDySLq1WOABHRKIbwsoSsqRvCq0-YqJ4pJTULExDgAIqJCDwEZaGA0Va4DbIQbQoJELBAgDCEGKpUmUGgVxAiT8ABUaHYPn5lMogA)

**Input:**
```jsx
styled.label`label {color: #000;padding: 10px 5px}`;
```

**Output:**
```jsx
styled.label`
  label {
    color: #000;
    padding: 10px 5px;
  }
`;

```

Can you clarify exactly what is the problem?

**Comment by ericclemmons** [comment]
When the line is too long (see my example), it causes part of the rule to go onto the next line.

IIRC this is using Emotion, but this seems to be an invalid CSS rule as a result:

```css
padding: 0px
  15px 0 15px;
```

**Comment by duailibe** [comment]
Understood! So the problem is that the lib doesn't parse the CSS (even though it's valid CSS), but I guess that's not pretty anyway.

> Within a template literal, I expect everything within `${...}` to be formatted, but not the text around it.

Why exactly do you have this expectation? When the template literal is CSS we format the whole text (just like I showed in my example).

**Comment by ericclemmons** [comment]
I didn't realize Prettier was formatting the CSS, which is why I was surprised that it was inserting newlines seemingly incorrectly.  (If Prettier reformatted a plain-text template literal, that'd be incorrect)

If the new lines are valid CSS (a surprise to me), then it's an issue with the underlying library for not handling the new lines correctly.
