### ISSUE TITLE
PR preview playground: `Invalid Version: pr-1234`

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#3612]
https://github.com/prettier/prettier/blob/7eca8011bc5e6f6071e94116619b3fda377befbb/src/common/support.js#L12

https://github.com/prettier/prettier/blob/7eca8011bc5e6f6071e94116619b3fda377befbb/scripts/build/build-docs.js#L27

![image](https://user-images.githubusercontent.com/8341033/34453300-026246d8-ed8c-11e7-8ce5-a7dd326d1a04.png)

Not sure what the proper version should be, maybe `999.999.999-pr.1234`?

---

**Prettier pr-3611**
[Playground link](https://deploy-preview-3611--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEADdAdK7UgDQgQAOMAltAM7KgCGATnRAO4AK9CVKNAbhKQCb4QNCjGQAzGgBsKcAgCM6NMAGs4MAMpFlpKAHNkMOgFc5IfhDATpsgrtl0YLJXoC2NazLMArCgA8AISVVdQ0aVzgAGV04T1tCYxgiRIAmOLNtOgdkEHc6FQsmKCEiOl0YAHUBGAALZAAOAAYCUohZCqUiHNK4B25Ygjo4AEdjUiHnGjcPJEkvAllXUkMTMwpdPSk4AEVjCHh0ghgaeSr+WuQUo6VSKQ2AYQhXdxyoaAGQY1kAFRPOOdkAF9AUA)
```sh
--parser markdown
```

**Input:**
````markdown
```
```
````

**Output:**
```markdown
TypeError: Invalid Version: pr-3611
```

**Comment by azz** [comment]
I guess we could use a different package.json field? `pkg.prVersion || pkg.version`?

**Comment by ikatyang** [comment]
Something like these?

(src/common/support.js)

```js
const pkg = require("../../package.json");
const currentVersion = pkg.prVersion || pkg.version;
```

(package.json)

```json
{
  "prVersion": "1.10.0"
}
```

**Comment by azz** [comment]
No I mean in worker.js

```patch
-    version: prettier.version
+    version: prettier.prVersion || prettier.version
```

and in build-docs.js

```patch
-  pkg.version = `pr-${process.env.REVIEW_ID}`;
+ pkg.prVersion = `pr-${process.env.REVIEW_ID}`;
```
