### ISSUE TITLE
Support for Java

### ISSUE THREAD

**Issue by torarnek** [prettier/prettier#3630]
If there is one language would benefit from some prettifying, it is Java.  This would have been a killer-feature for those of us that live in Java-land!

**Comment by azz** [comment]
Hi! We've recently built a [plugin API](https://prettier.io/docs/en/plugins) so it should be possible to build this as a language plugin.

We won't be taking on more large languages in this repository to keep it focussed and maintainable, but I'd be willing to help get a new plugin off the ground in a separate repository like [prettier-php](https://github.com/prettier/prettier-php) and [prettier-python](https://github.com/prettier/prettier-python).

Firstly a parser needs to exist to parse a Java program into an abstract syntax tree in JavaScript. A quick Google found https://github.com/mazko/jsjavaparser.

I'll close this issue as it's not actionable here.

**Comment by thorbenvh8** [comment]
If we decide to develop prettier-java, you want us to that locally first and then we can move it under prettier/prettier-java?

**Comment by azz** [comment]
Yes, start your own repo and we can move it to the Prettier org once everything is underway. Python and PHP started out as PRs here, so they were fairly established before they moved to their own repos. It might even make sense to fork one of them to get started!

**Comment by thorbenvh8** [comment]
@torarnek Hey are you in this with me? :)

**Comment by thorbenvh8** [comment]
The jsjavaparser even has a fork which supports Java 8! https://github.com/victordidenko/jsjavaparser

**Comment by thorbenvh8** [comment]
Create a new project for prettier-java, will stark working on it this weekend!
https://github.com/thorbenvh8/prettier-java
If anyone wanna help in any way, I'm very open to it :)

**Comment by stigkj** [comment]
This could just be a wrapper around [google-java-format](https://github.com/google/google-java-format).

**Comment by thorbenvh8** [comment]
@stigkj thanks for the input, thats a cool tool, but not really how prettier works, as far as I understand it now
