### ISSUE TITLE
Error on Markdown with empty alt and a reference-style source

### ISSUE THREAD

**Issue by tzi** [prettier/prettier#3642]
Hello !

I found a bug when trying prettier with our Markdown documentation.
It's impossible to lint an image without an alt text and with a reference-style source.

**Input:**
```markdown
![][9]

[9]: https://www.alphabounce.com/img/vigs/vig1000.png
```

**Output:**
```markdown
TypeError: doc is null
```

Here is a [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBCA2gXXQTkwHSkN0yQAIALGGABwGckB6RuADwEMBbGgGzgDpInEABoQEGjACW0OslDsAToogB3AApKEclOwBuEKQBNRIdnRjIAZux504YgEaL2YANZwYAZRqupUAHNkGEUAVwcQIwgwa1t7MX97RRh1FwDOdli7CIArOlYAIRd3Ty8uOAAZfzgs+PFQ2gaAJlqI30Uk5BAMxTco1ShTGkV-GAB1YxgKZAAOAAYxYYh7MZcaLuG4JL0asUU4AEdQqX3U9nTMpBtssXtOKWCwiLp-AL4ARVCIeFaxGHZHBMjFNkE0-i4pDxXgBhCCcDJdKDQXYgUL2AAqAJ013sAF9cUA)

Cheers,
Thomas.

**Comment by j-f1** [comment]
Looks like `imageReference.alt` is null in this case.

**Comment by tzi** [comment]
Thanks a lot!
