### ISSUE TITLE
using `requirePragma` and `insertPragma` together

### ISSUE THREAD

**Issue by ferdibiflator** [prettier/prettier#3644]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbm9fPz8Aeiz8ABVbABFbJHxC6AV9Gzh8akMoOggAW394tganDN19RJa+C0MYIQA6VHIafAYBoeG6huaGDwAqfABGAFEAagB2N2GYCABlGGpw5kXZuAAHEkMwOAYs-n5h57pNrJxmSUFBN3T4rUOLF4gAeOg4ez4MC3TSaAByhiacB4CmIZEoNHoCnwuBguh4wAABgBNaz4QxsfD2HDaA7UBLoJoAIyc+AAJMBGS0XESXPhLNY7I5qITBdUHE4XAA+AGZfCgzQnaDMaVc0KcZjDTQkHD3Bj4AAMklW+D2BwAqlcrk4AMKGUyLfCbKRsMJcbW6-Wrc0QAAyEAA7naHQ8PC5QVkldQVbLAX4WG7NcMEHRNBQcEMGBI-vgAPwCECF-ClRVXer4JUATwJwGAkHI1FKSn40irChcMokhcjmnLUGl+BcGT8oLgTTj-Bg6qTcDkw58MEj47j8q5DG0ulg-3jmQLgleIBHmVKgiCggXx8jEPs0rSPigLhA4hAECuuGgmmQoEpMcDAAVKQQL8UEMewIBwOhnxAB0YGQIwTDMEBmTqMAAGsOEOcswDOZATnQJDGjAeDjFMF9wlMagYH-OpmCaQw8OoAiXwAK00AAPAAhVCMJgQ4kTgP1wjgEjEJfawYCudAYAAJlEsiQHLahKOQZDDGZGtoGgq5TlgDM6CGZAAA5jUUmNTAoOorlUnS4EoxxoLYABHdAcDYGjDDohikHwpDTCaHBGOYkBtC4XQAEV0AgeB5KQmB1P0wykBkl8TkMHQzltZp6NUqBoBEl9qjydSQIQ0xOyAA)
```sh
--insert-pragma
--require-pragma
```

**Input:**
```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>;

}
```

**Output:**
```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>;

}
```

**Expected behavior:**
Following the description on the https://prettier.io/docs/en/options.html#insert-pragma it supposed to put a pragma on the top of the file and then do format, right? If so then there is a bug.

**Comment by azz** [comment]
Does it make sense to use both of those flags together? If they did work together it would be the same as using neither of them.

**Comment by ferdibiflator** [comment]
Probably it's not related to `prettier`.

I'm resolving the issue for `prettier-atom` https://github.com/prettier/prettier-atom/issues/324.
I want to put the pragma with `prettier` programmatically changing the `insertPragma` to `true`. In this case both `requirePragma` and `insertPragma` will be `true`. I could change `requirePragma` to `false`, but this confused me:
```
This works well when used in tandem with the --require-pragma option. If there is already a docblock at the top of the file then this option will add a newline to it with the @format marker.
```
I suppose that using `reuirePragma` with `insertPragma`, the last one will put the pragma if there is no pragma.

I hope I explained it well.

**Comment by suchipi** [comment]
I think the intended usage here is that you run `--insert-pragma` once, and then use `--require-pragma` afterwards. Maybe we should clarify the docs.

**Comment by hampustagerud** [comment]
Sorry for bumping but we are currently trying to set up Prettier for converting a large code base so we want to format the files when we are working on them. Like @ferdibiflator I assumed that formatting the file would insert the pragma and then format the file.

We never format the entire code base, just the file open in an editor so having the pragma inserted automatically for files that do not have the it would make this process a lot smoother.  Wouldn't it make sense in this use case to allow both options to be set to true? 🙂

**Comment by thorn0** [comment]
These two options aren't supposed to be set to `true` **at the same time**. This should be made clearer in the docs.
