### ISSUE TITLE
comment in function chain causes function to be wrapped in `()` with an extra space

### ISSUE THREAD

**Issue by theverything** [prettier/prettier#3648]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMBGAFBrGAS2lwEoACYAHSgooCc4Z0G6CwAmW+3igen6QAtsIQwefCgDoARgEMG5ANy0AvmWUgANCAgAHYtADOyUIoYQA7gAVFCUynkA3CEQAmOkPOMxkqeQAbYzhdWQZ5MABrZgBlfUiiKABzZBgGdFCQdwgwfyCQ3SSQhhgbCOTheXzgrIArYwAPACEI6Lj5MQAZJLgawr10GH0hzn6shIYS5BAFWQBPQOgvfQYkmAB1DxgAC2QADgAGXVWIEI2I-RnVuBLnPt0mAEd0IiZy+UrqpADa3RDhEQ0hkssYkslAnAAIroCDwca6GDyWRbdy7ZCcRERIiBcEAYQgom+ICg0AeIHQIQAKsjHL8Qmo1EA)

**Input:**
```jsx
func1(function() {
  return func2
      //comment
      .bar();
});
```

**Output:**
```jsx
func1(function() {
  return (func2
      //comment
      .bar() );
});

```

**Expected behavior:**

 I wouldn't think it would wrap the function chain in `()` and at the least the extra space at the end wouldn't be necessary.

**Comment by theverything** [comment]
Looks like this isn't an issue when using `=>`

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMBGAFLgSgAIBeAPiOAB0oiiAnOGde2jLAJhrp6IHo+kALZCEMbryIA6AEYBDeoQDcNAL4ElIADQgIABxgBLaAGdkoBfQgB3AAoKEZlHIBuEQwBNtIOSZjJUOQAbEzgdGXo5MABrJgBlPSjDKABzZBh6dDCQDwgwAODQnWTQ+hhbSJShOQKQ7IArEwAPACFImPi5UQAZZLhaot10GD1hjgHsxPpS5BB5GQBPIOhvPXpkmAB1TxgAC2QADgAGHTWIUM3IvVm1uFKXfp1GAEd0Q0YKuSqapEC6nVCQkM6Uy2RMyRSQTgAEV0BB4BMdDA5DJth49sgOEjIoYghCAMIQEQ-EBQaCPEDoUIAFRRTj+oVUqiAA

**Comment by hawkrives** [comment]
To add to this interesting bug, if that function is a top-level function, the return value gets wrapped in parens and expanded (as I'd expect the OP to do, too.) (playground)[playground]

```js
function x() {
  return func2
      //comment
      .bar();
};
```

```js
function x() {
  return (
    func2
      //comment
      .bar()
  );
}
```

[playground]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAHgBQCU+wAOlPvgE5wzp00ZYBM1t3+A9L5AC2ghDC498AOgBGAQzpkA3NQC+yqCAA0ICAAdc0AM7JQ8uhADuABXkJjKWQDcIOACZaQswzGSpZAG0M4bWk6WTAAa0YAZV1wnCgAc2QYOnRgkFcIMF8AoO0EoLoYKzDEwVlcwIyAK0NCACEwyJjZEQAZBLgq-J10GF1+9h6MuLoi5BA5aQBPf2gPXToEmAB1NxgAC2QADgAGbSWIINWw3UmluCLHbu0GAEd0HAZS2XLKpD9q7SDBHBS0hlDAlEv44ABFdAQeAjbQwWTSdauLbIdhwsI4fwggDCEGEHxAUGgtxA6CCABUEfYvkEVCogA

**Comment by duailibe** [comment]
I suspect this is another case of `removeLines`: https://github.com/prettier/prettier/blob/e4e3c757fb85f47f0336fc2f13678ae93facde40/src/language-js/printer-estree.js#L3211-L3233
