### ISSUE TITLE
Make the playground example a placeholder

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3652]
This would allow the user to enter their code right away without having to delete the example first. Plus, it would make the playground easier to use on mobile — it’s really hard to delete large amounts of content in the code editor on an iOS device.

Also, would it be possible to have different examples for each language? The JS one doesn’t work very well for CSS and Markdown.

(ref https://github.com/prettier/prettier/pull/3573#issuecomment-354602726)

**Comment by lydell** [comment]
FYI: There is a "Clear" button.
