### ISSUE TITLE
single line if without  else is put on one line

### ISSUE THREAD

**Issue by mschipperheyn** [prettier/prettier#366]
Prettier changes

```js
if (this.state.url !== url)
  this.toggleLoading(true);
```

to

```js
if (this.state.url !== url) this.toggleLoading(true);
```

This is a style I don't like. Is there any way to customize the prettier defaults?

I also find 

```js
this.state = { 
  theUrl: null, 
  myTitle: null, 
  loaded: false 
};
```

changed to 

```js
this.state = {theUrl: null, myTitle: null, loaded: false };
```

which is less readable imho

**Comment by vjeux** [comment]
The two behavior you mentioned are behaving the way they are meant to be implemented right now. But we're still early in the project and they may be subject to change. Thanks for adding a datapoint to make that decision!

**Comment by mschipperheyn** [comment]
Yeah, I thought it was intentional. I guess everybody has his own preferences in the way code looks. I guess it would be nice to have something like the Eclipse code formatter (Eclipse => Java => Code Style => Formatter)

**Comment by kennetpostigo** [comment]
I tend to prefer the way prettier defaults to at the moment 😆 .

**Comment by vjeux** [comment]
The second object will remain as is now FYI.

**Comment by vjeux** [comment]
We are now past 1.0 and we're not going to change core printing like this one anymore. Sorry!

If you want code to be printed on the next line, you can add `{}`. Feel free to fork prettier if you really want this behavior.

**Comment by pstanton** [comment]
i disagree with this decision for the objective reason that it is harder to debug! you cannot step on-to the "then" line in a debugger if it is on the same line as the "if". subjectively i feel it is harder to read as well, but the first reason should trump all others.

**Comment by azz** [comment]
As of Chrome 60-ish you can use inline breakpoints

**Comment by Springrbua** [comment]
@vjeux In my opinion, the configuration is pretty limited at the moment and if I didn't missunderstand your statement, you won't add new configurations anymore?  
I have seen, that there is an option to inline JSX-Brackets (`jsxBracketSameLine`), but similar options for `TypeScript`/`JavaScript` are missing.  
I, for example, preffer to have the `if`-body in it's own line.  
Also I dont inline the `else`-statement with the closing-bracket of if (`}`).  
So if `prettier` does not support a configuration for this, I (and probably many others) can't use it for my projects.

**Comment by azz** [comment]
@Springrbua don't let those kind of things block your Prettier adoption 😄, if you really care about those things you can always use https://github.com/prettier/prettier-eslint/ which runs Prettier for overall formatting, then `eslint --fix` to make some small changes like you mention above.

**Comment by Springrbua** [comment]
@azz This kind of things is actually the purpose of formatters. So if they don't format things the way I want, I can't use them.  
I'll take a look at `prettier-eslint`, but we are using `tslint` as we are working with typescript, so I am not sure, how well it works.

**Comment by azz** [comment]
[`prettier-tslint`](https://github.com/azz/prettier-tslint) exists too, but it is _much_ less battle tested.

**Comment by Springrbua** [comment]
Thanks for your information. I'll take a look at it, maybe I can use it in our environment.  
FYI: I am using @nrwl/nx to develop multiple Angular Applications in a mono-repository.  
@nrwl/nx uses `prettier` to format the code, but they seem to hardcode some options (like `single-quotes`) so there are multiple issues at the moment, which keep me from using the auto formatting.

**Comment by pstanton** [comment]
what is the problem with a config file? this such a good project marred by one bad decision....

it is pretty much the standard, everywhere, to put the "if" and "then" on separate lines.

**Comment by j-f1** [comment]
https://prettier.io/docs/en/option-philosophy.html

**Comment by pstanton** [comment]
i had an idea.

there are times when the formatter makes a different descision based on what the programmer has done with line breaks.

for eg:

```
	Object.assign(myObj, {
		name: "good code"
	});
```
and:
```
	Object.assign(myObj, { name: "good code" });
```

If i run the formatter on each of these, no change is made by the formatter.

So then is it too much of a stretch to make:
```
	if (someCondition) thenDoThis();
```
and:
```
	if (someCondition)
		thenDoThis();
```

both valid results?

**Comment by lydell** [comment]
The few times we let the original source decide are workarounds. We don't want more of those.
