### ISSUE TITLE
Add information for creating other languages in the wiki 

### ISSUE THREAD

**Issue by lramirez925** [prettier/prettier#3663]
So this might not belong here and I apologize. But I have been looking for documentation on how to add a new language. Not looking for a step to step guide tho that would be nice for those who want to add a language as a separate plugin.
 I saw you created a more friendly plugin style so I appreciate that.  
I also think since antlr is such a big player in generating a lot of parsers/Lexars having a way to plug in the parser it generates would be nice.

**Comment by azz** [comment]
Is this what you're after? https://prettier.io/docs/en/plugins

**Comment by lramirez925** [comment]
Yes that is helpful tho having a bit of a description on how to go from the parser antlr generates to something useful for the library would still be helpful.

**Comment by thorn0** [comment]
Closing in favor of #4100.
