### ISSUE TITLE
Add playground examples

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#3667]
Add examples to `getExample()`:

https://github.com/prettier/prettier/blob/5e2e7a2881d07ff0aa4b4673becc9cb4ce2f6cae/website/static/playground.js#L356-L381

- [x] JavaScript (babylon)
- [ ] JavaScript (flow)
- [x] TypeScript (typescript)
- [x] CSS (css)
- [ ] Less (less)
- [x] SCSS (scss)
- [x] JSON (json)
- [ ] GraphQL (graphql)
- [ ] Markdown (markdown)

**Comment by arefaslani** [comment]
I have created a Next boilerplate that support importing scss, css, preconfigured with ESlint and prettier and many more features. Take a look at it and if you liked it, give it a star ;)
https://arefaslani.github.io/next-boilerplate
