### ISSUE TITLE
WIP Homepage design thread

### ISSUE THREAD

**Issue by orta** [prettier/prettier#3669]
~**We're looking for someone to implement this design BTW**~  See #3718

I started looking at a homepage design after [this tweet](https://twitter.com/Vjeux/status/949852418195402752) (and the subsequent thread)

![prettier-homepage](https://user-images.githubusercontent.com/49038/34657379-7a6b95d6-f3f3-11e7-8942-2771b22e371a.png)

Current setup:

- Hero unit
  - See [animation](https://twitter.com/Sandhose/status/950135401544642561)
- Prettier TLDR unit 
  - would like to iterate more here, are these the right tenets of prettier?
  - could there be another way to show this?
- Prettier examples for different langs etc
  - Some langs might not be available for example (swift/python)
- Prettier integrations
- Very simple getting started 
  - This is basically the 90% use case
- People use prettier 
  -  GH says [50k repos](https://github.com/prettier/prettier/network/dependents) - worth a mention? 
  - I fleshed it to 8 by adding danger + storybooks
  - white feels eye-catching when zoomed out, but feels alright when eat 100%

[Sketch doc](https://ortastuff.s3.amazonaws.com/prettier/prettier-home-page.sketch)

Note: I kept in a light border so that I can measure the edges (1000px) regardless of how width the browser.

<p>Will update this thread and add comments as I expand on this<p>
<details>
<summary>Old drafts.</summary>

First shot:

![prettier_home](https://user-images.githubusercontent.com/49038/34651811-7b86119e-f3a3-11e7-9868-672a63194c48.png)

Second

![prettier-home](https://user-images.githubusercontent.com/49038/34652237-8ae871d0-f3a9-11e7-8080-3215e38cf35a.png)

Third

![wip-prettier-2](https://user-images.githubusercontent.com/49038/34653261-7b89057a-f3b7-11e7-9542-2bf24b67acca.png)

Fourth

![prettier-homepage](https://user-images.githubusercontent.com/49038/34653550-52283a3a-f3bb-11e7-9c56-130d56b82fd6.png)

Fifth

![prettier-homepage](https://user-images.githubusercontent.com/49038/34654747-ff9a0e70-f3cd-11e7-97dc-004dd463aa1b.png)

Sixth

![prettier-homepage](https://user-images.githubusercontent.com/49038/34655269-d73c9f2c-f3d4-11e7-8627-16867be8793d.png)

</details>

<details>
<summary>This is really filling out my artsy-themed logos repo.</summary>

<img width="1377" alt="screen shot 2018-01-07 at 1 19 39 pm" src="https://user-images.githubusercontent.com/49038/34652533-80dee3a0-f3ad-11e7-835a-7ba79a2a6882.png">

</details>

**Comment by azz** [comment]
![](http://www.reactiongifs.com/r/2013/11/Andy-Dwyer-Shock.gif)

**Comment by orta** [comment]
Idea: A section that lets you easily preview a before and after example for the different filetype/formats that prettier supports. It can be read-only, so just would need a nice example of unformatted code for all of the different options currently listed which can be then be ran through prettier on deployment and saved into the file.

<img width="1576" alt="screen shot 2018-01-07 at 12 34 50 pm" src="https://user-images.githubusercontent.com/49038/34652057-496a8b1e-f3a7-11e7-9561-4ee3232d2c81.png">

**Comment by vjeux** [comment]
Random idea: the text illumination animation from this tweet looks pretty cool. Could do something like this for the before/after unit.
https://twitter.com/sarah_edo/status/948219340096024576

**Comment by vjeux** [comment]
We should also figure out the selling points of prettier. I think the big two are:
- (personal) don’t spend time formatting code when it can be done on save
- (team) don’t spend time arguing and fixing lint rules about style

**Comment by j-f1** [comment]
I really like how [Babel’s website](http://babeljs.io) has a demo on the front page that’s also a stripped-down version of the playground.

... what if we made a JS API for the playground, and used it in other places? (like the [docs homepage](https://prettier.io/docs/en/index.html) and the [ignore docs](https://prettier.io/docs/en/ignore.html))

**Comment by vjeux** [comment]
Would be nice to also get some really simple instructions on how to get started

**Comment by j-f1** [comment]
```shellsession
$ yarn add --dev prettier
$ # TODO:
$ yarn prettier --init
- Analyzing source files...
- Detected style:
  - single quotes
  - no semicolons
  - trailing commas everywhere
  - bracket spacing enabled
- wrote .prettierrc.yml
$ yarn prettier
```

**Comment by orta** [comment]
> ... what if we made a JS API for the playground, and used it in other places? (like the docs homepage and the ignore docs)

Yep, that'd be optimal

> We should also figure out the selling points of prettier.

Agree, could be handled by the TRDR chunk being two sections on "what" and "why"

<img width="1118" alt="screen shot 2018-01-07 at 1 57 36 pm" src="https://user-images.githubusercontent.com/49038/34652919-c6ae7094-f3b2-11e7-88df-657875ec459b.png">

**Comment by orta** [comment]
OK, I've left my 6th iteration up in the sketch and updated the issue above. It's getting close enough that this structurally feels pretty solid for me ( I didn't add the footer, but that'd stay the same as the rest of the site in the same way the header is )

Also @sandhose has got really far on the animating logo: https://sandhose.github.io/prettier-animated-logo/

**Comment by j-f1** [comment]
Looks really nice @orta! Just a few things:

- I feel like the `#` characters at the beginning of the headers don’t look very nice. Similarly, I’d prefer the normal bullet style ( • ).
- Could you put each editor integration on its own line next to the editor icon?
- The current search bar feels a little out of place. Would it fit in better if it was hidden under a button (like [Babel](http://babeljs.io/)) or identified with an underline instead of a background (like [ESLint](https://eslint.org/))?

**Comment by duailibe** [comment]
I prefer the editor names on the side of the icons.

As for the header, I believe @orta said he didn't change anything on that, or the footer

**Comment by j-f1** [comment]
@duailibe I was suggesting that the plugin names be split onto their own lines (like Atom’s in the picture above), instead of being strung together on one line (like Vim’s).

**Comment by duailibe** [comment]
Ah! In that case, I prefer the way it is on the picture but I don't really care either way :)

**Comment by themre** [comment]
I would put languages in the "show me" section on top, also better for mobile.

**Comment by orta** [comment]
Agree WRT splitting the plugin names 👍 :

<img width="1074" alt="screen shot 2018-01-08 at 9 14 58 am" src="https://user-images.githubusercontent.com/49038/34674553-65aed188-f454-11e7-9388-ff5b740ae0cf.png">

**Comment by orta** [comment]
> I would put languages in the "show me" section on top, also better for mobile.

I don't want to list all of them, there's too many and it's ever evolving, perhaps a subheading with an overview could work

<img width="1106" alt="screen shot 2018-01-08 at 9 16 44 am" src="https://user-images.githubusercontent.com/49038/34674652-bd978e76-f454-11e7-9cb8-b75e2217a83d.png">

**Comment by orta** [comment]
The text illumination example seems to be built using [GSAP Text  Plugin](http://greensock.com/docs/#/HTML5/GSAP/Plugins/TextPlugin/) another example [looks like it has a pretty simple API](https://codepen.io/natewiley/pen/xGyZXp)

**Comment by orta** [comment]
This is shipped, closing :heart:
