### ISSUE TITLE
Prettier respects template literals, but not tagged templates

### ISSUE THREAD

**Issue by btraut** [prettier/prettier#3670]
As far as I can tell, it's prettier's philosophy to leave template literals unaffected (except for breaking on the tokens) because adding breaks and indentation actually modifies the code. This tends to work fine, but it breaks when it comes to tagged templates, the syntax where you call a function with a template literal and leave off the parens.

A simple fix in my code was to add the parens back in to the function call, but this won't work for everyone as it actually changes the arguments for the resulting function call.

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAJgAwDpQCoAWAlgM4AEANkVHGSQRAK4XpQDkMZARrdegvHRkAhp2EUKZamRgFaAJzglmMagHMyTGAAdGMADTc9UzqQB0uHFFwYAFFYAKimKrjyy6CEplyy8omoEnLLqmlA+pJTUtMJQQtqKJG4Abt6yvHECokTQlHCpFBZQmACUuCD6IBDaqtAkyKDC8vIQAO4OTQj1KBUgwiQwyABm4kmVXPLCYADWcDAAytpT6sgw8oxwlZ5gw6ObINRJ8jBOwmqowrsUYyAAViQAHgBCkzNz88KocAAy0Vc3Wl0MAATP99kt5EdkCAuMIuABPCjQXoJagwADqRHQsmQAA4AAyVBIQJLoybaaEJJQpOC9RQAR0YREUp3OlyQI2u+ySqCIq3W3PUFDgAEVGBB4GDKjA4ZjsQRkMDpZMiFQoGoAMIQVAXaFQaC0yqMJJ4OHdTlJAC+lqAA)

**Input:**
```jsx
md`
This line shouldn't be indented at all in the resulting output, but it is.
`

md(`
Prettier does the right thing on this line and preserves the indentation level.
`)
```

**Output:**
```jsx
md`
  This line shouldn't be indented at all in the resulting output, but it is.
`;

md(`
Prettier does the right thing on this line and preserves the indentation level.
`)
```

**Comment by btraut** [comment]
Oh strange, I just dug into the source and realized that calls to `md` (along with `gql`, `graphql`, `css`, and `markdown`) is allowed to format template literals. In this case, `md` was actually the name of our own function. It happened to format markdown, but it wasn't a call to any particular module/package. Looks like I ran head-first into a convenience you attempted to build for other developers?

**Comment by azz** [comment]
This is easy to fix but has the unfortunate side effect of changing this:

```js
function foo() {
 if (something) {
   return md`
      # foo
   `;
  }
}
```

to 

```js
function foo() {
 if (something) {
   return md`
# foo
   `;
  }
}
```

It's probably just used in conjunction with something like https://www.npmjs.com/package/common-tags#stripindent ?

**Comment by btraut** [comment]
Well I clearly don't have enough context in this case, but I would prefer if my strings were completely left alone. Don't strip indents. Don't add indents. That's how prettier usually works, but I unfortunately used one of their magic function names unknowingly which made it so it reformatted my string.

**Comment by azz** [comment]
It's the same as the CSS-in-JS support, e.g.:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAwAJIsIAnCpC2vMkAGhAgAcYjpVkoAIa1aEAO4AFEQgEohJCEVzsQQ9MgBmQrKjgcARrSFgA1nBgBlLiaJQA5shi0ArvpC4IYLTr0c7erQwksb2ALZCPrruAFaoAB4AQsZmFpZCYXAAMnZwUX6cLjBcRQBM+e42tIHIIAZCBtjQqly0djAA6sowABbIABwADBytEHodxly1rXCBJHkczACOLkTMIULhkUja0Rx6YUROru6odvY4AIouEPAVHDANXbi9yKUPxkRY5wDCEGERWpQaALEAuPQAFQacl2egAvnCgA)

**Input:**
```jsx
styled.div` color : red`
```

**Output:**
```jsx
styled.div`
  color: red;
`;

```

I'd be happy to change the expected output to keep the original indentation level.

**Comment by btraut** [comment]
Well, like I said -- I don't have enough context to encourage you to go one way or the other. These few function names were clearly whitelisted for a reason, and I wouldn't want to break meaningful formatting for others.

Like I mentioned, this could be made opt-in by making a new option. I'm not sure what is important enough to warrant creating a new option (and all the corresponding tests/docs/etc), so maybe this is too heavy-handed as well?

For the time being, I can either add parens or just rename the function. :)

**Comment by azz** [comment]
Well the thing is you actually _are_ tying to format Markdown so the heuristic was correct. If we can correctly format your code we'd rather do that than add an option for this kind of thing. But you're right in that we shouldn't be messing with your indentation.

**Comment by duailibe** [comment]
> Well the thing is you actually are tying to format Markdown so the heuristic was correct.

I think the problem here is that is not meant to be Markdown, just a coincidence of using `md`.. otherwise this would not be an issue, as the indentation would be ignored if it was supposed to be Markdown.

**Comment by lydell** [comment]
> the indentation would be ignored if it was supposed to be Markdown

Why? Doesn’t indentation cause everything to be a code block in markdown?

**Comment by duailibe** [comment]
Oh yeah, you're right! I must've been thinking of something else.. in any case, I'm not sure from the issue @btraut meant for the content to be Markdown

**Comment by ikatyang** [comment]
The `md` trigger is from https://github.com/Thinkmill/react-markings, it'll dedent the input before passing to the renderer, and I think all the other similar libraries should have done the same thing, otherwise the input will be ugly. The current indentation logic should be fine.

I think what OP wants is a way to disable the `md` trigger, but I think we can just put a `// prettier-ignore` before `md` to not trigger formatting, otherwise I'll suggest to change the function name since `md` is not a common naming.

**Comment by lydell** [comment]
Thanks @ikatyang, that makes sense.

@btraut Can you tell exactly what your problem is so that we can decide on how to proceed?

**Comment by btraut** [comment]
@lydell: You nailed it. My markdown is becoming indented which is turning it into a code block in the markdown parser (I’m using marked).

**Comment by btraut** [comment]
To clarify what I meant earlier, the `md` function in my code is my own. It takes a string, pipes it out to `marked`, then wraps it a react component. So, yes, adding indentation breaks my code because it is markdown, but I wanted to specifically point out that I’m not just piping my code straight into an external markdown package — I stumbled on the `md` function name in my own code.

**Comment by lydell** [comment]
Since we cannot know that it is safe to add indentation, maybe we should either:

- Always have no indentation in `md` tagged template literals.
- Check if the input was indented, and choose between no or nice indentation based on that.

**Comment by ikatyang** [comment]
Option 2 looks good to me.

**Comment by btraut** [comment]
Either would work for me.

**Comment by azz** [comment]
I'd vote for option two also, but there might be some edge cases with mis-detecting code blocks as actual markdown or vice versa.

**Comment by j-f1** [comment]
What if we check if the `md` variable comes from `import md from 'react-markings'`?

**Comment by aboyton** [comment]
Presumably there are other Markdown string templates that aren't just from `react-markings` that could benefit from markdown formatting.

**Comment by btraut** [comment]
Thanks for the quick effort, ikatyang and community! Really appreciate it.
