### ISSUE TITLE
Ignore package(-lock).json by default

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3671]
@duailibe EDIT: see before implementing https://github.com/prettier/prettier/issues/3671#issuecomment-355933794

---

Proposal: If no `.prettierignore` file is found, default to the contents:

```
package.json
```

If an empty `.prettierignore` file is provided the behaviour is revoked.

Rationale: Every project I have created recently has a `.prettierignore` containing `package.json`, and I can't think of a reason why you _would_ want Prettier to format this file, as it is aggressively reformatted by other tools.

Disadvantage is that it creates a bit of hidden functionality. Note that there is _some_ precedent, globs automatically ignore `node_modules`.

👍 / 👎 ❓

**Comment by SimenB** [comment]
>Rationale: Every project I have created recently has a `.prettierignore` containing `package.json`

Same here, +1 to this! They also contain `package-lock.json` for the same reason.

**Comment by lydell** [comment]
Let’s say we add this feature, and a user does not add a .prettierignore. One day the user needs to ignore a file, so the user creates a .prettierignore with that file in it. Suddenly Prettier starts to format the user’s package.json. Is that unexpected?

**Comment by j-f1** [comment]
Why not ignore it by default, like `node_modules` is? If you want it formatted for some reason, you can put `!package.json` in your `.prettierignore`.

**Comment by duailibe** [comment]
I'm :-1: with the suggestion as is, but :+1: for the idea of ignoring `package(-lock).json`.

@j-f1's idea seems good.

**Comment by azz** [comment]
Yeah I like @j-f1's alternative more. Anyone want to implement this?

**Comment by duailibe** [comment]
And when should we run prettier on the file? `--with-package-json` ?

**Comment by SimenB** [comment]
What about copying eslint's approach when you try to lint ignored files? `0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override`

**Comment by azz** [comment]
There is an issue though... As prettier doesn't have a `prettier.isFileIgnored(path)` API, the changes would only affect the CLI, and not any editor integrations or other tools which are using `ignore` directly.

**Comment by duailibe** [comment]
@SimenB that makes sense as a feature (we can do this now with `--ignore-path /dev/null` or something similar) but it's not related here since `node_modules` is ignored in addition do the ignore file.

@azz editors should be using the `filepath` with the API, right? We could ignore it then

**Comment by lipis** [comment]
I personally don't care what the other tools are doing, but I would like to run prettier on `package.json`  because sometimes it gets [complicated](https://github.com/wireapp/wire-webapp/blob/dev/package.json) and regardless of what tools are doing there is a pre-commit hook that fixes it.. 

Even though some tools are (wrongly) reformatting the whole thing instead of just the parts they have to, that doesn't mean that we need to ignore that file by default. `package.json` (and arguably the `package-lock.json`) are part of the source code and very often edited by humans, so we should not ignore it by default..
