### ISSUE TITLE
Pasting an array inserts a semicolon

### ISSUE THREAD

**Issue by jdhines** [prettier/prettier#3674]
This doesn't reproduce in the playground, but in VS Code, if I disable every extension except Prettier, I see this issue, and if I disable Prettier, there is no semicolon insertion.

**Input:**
```javascript
let myThings = {
  group1: [1,2,3],
  group2: [1,2],
  thing: ''
}
```

And if I copy `[1,2,3]` from the first item, select `[1,2]` or `''` in the second or third item and paste, it inserts a semicolon after the closing bracket:
**Output:**
```javascript
let myThings = {
  group1: [1,2,3],
  group2: [1, 2, 3];,
  thing: ''
}
//OR
let myThings = {
  group1: [1,2,3],
  group2: [1,2],
  thing: [1, 2, 3];
}
```

**Expected behavior:**
Pasting an array doesn't automatically add a semicolon at the end

**Comment by ikatyang** [comment]
It looks similar to prettier/prettier-vscode#257, and I'm not able to reproduce, can you provide your versions/settings?

![kapture 2018-01-08 at 21 46 47](https://user-images.githubusercontent.com/8341033/34673512-7a351568-f4bd-11e7-9e87-362243282c03.gif)

**Comment by jdhines** [comment]
It does seem similar, but I don't get that exact issue either, just when pasting an array. I'm on version 1.0.1 of prettier-vscode, which is Prettier 1.9. All settings are default.

**Comment by CiGit** [comment]
Format on paste calls the range formatter.
```shellsession
$ cat test.js
let myThings = {
    group1: [1,2,3],
    group2: [1,2],
    thing: ''
}
$ npx prettier@1.5 --range-start 50 --range-end 55 test.js
let myThings = {
  group1: [1, 2, 3],
  group2: [1, 2],
  thing: ""
};
$ npx prettier@1.7 --range-start 50 --range-end 55 test.js # [1.6 - 1.7]
let myThings = {
    group1: [1,2,3],
    group2: [1, 2];,
    thing: ''
}
$ npx prettier@1.8 --range-start 50 --range-end 55 test.js # [1.8 - latest]
let myThings = {
  group1: [1, 2, 3],
  group2: [1, 2],
  thing: ""
};
```
I suppose you have a prettier installed locally (range 1.6 - 1.7) which is the one taken by the extension.

Over **Prettier**(Bottom right your editor) after having called the formatter to see which version it picked up.

**Comment by azz** [comment]
Thanks for looking into that @CiGit.

I'll close this issue as it was probably fixed in #3069 which was in 1.8.

Re-open if this is not the case.

**Comment by jdhines** [comment]
`prettier@1.7.4`
I see I do have that in my `package.json` 
If I have the VS Code plugin, should I remove it from my project? Or should I just make sure the version in my project is updated?

**Comment by azz** [comment]
Just update your local prettier to 1.9
