### ISSUE TITLE
Markdown nested lists are not indented properly

### ISSUE THREAD

**Issue by iamcam** [prettier/prettier#3679]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAWQIYCcDWAJhAO5ToAqcAzjADpQMBU6AgugDYCWM6PcAWwboR6FgHEeACwCuAI3TYohdACEecmWHxxeAvEVLlccAI4yuJ9ABZ01AA7YwNdADMIudFBrwV3WnzwAtTCoiwAynBw6FIwMPbUSAD0SbRO+BAAbnC4rhykAHSQAklwhDxcUADmALRScBz2qNiEmUrOhDX+MCFQLAAKJnE5fMoIPegwEOgATHaOztToABQw2AokXIQwUujENFAA5LzUUQKT09iurnBgvDwAlAwgADQgEPYwXNDUyKB4uFI-TwCF+KGwmQgW1eIGwtGQrmwHFObzkuHSunCC0qVWQMFwMjgb2IYARSJRIEqp1wMEG2Cq+jJyKJIAAVtQAB6qdHaTHYARwAAylTgTIpEBk8UlMzFLMcuGpyBA+gIxDIMPsuEqMAA6lsdsgABwABjemogpx16PsSs1NBy2RhJnMljgdIZ2Flb1OAi4eIJLOoOI4cAAijIIPAvSA1nI9dspMgZm98dguNxqgBhCACRkoKDQUVvGSnCjrMGI5kAXyrQA)
```sh
--parser markdown
```

**Input:**
```markdown
# Markdown Test

* A lit item
    * Bitbucket markdown requires 4 spaces for nested list items (https://stackoverflow.com/a/37594372)
* Pretter indents to 2 spaces (tab width doesn't seem to affect it)

```

**Output:**
```markdown
# Markdown Test

* A lit item
  * Bitbucket markdown requires 4 spaces for nested list items (https://stackoverflow.com/a/37594372)
* Pretter indents to 2 spaces (tab width doesn't seem to affect it)

```

**Expected behavior:**

The nested list items require 4 spaces for proper display formatting in Bitbucket (likely others. see this SO https://stackoverflow.com/editing-help#advanced-lists )

**Comment by vjeux** [comment]
It seems like prettier doesn't even respect tab-width for this :(

**Comment by ikatyang** [comment]
FYI, the reason why we did not respect tabWidth/useTabs, see #3223 and https://github.com/prettier/prettier/issues/3463#issuecomment-351245529.

The markdown renderer used by BitBucket is really weird... I'm not sure what should we do here, see https://github.com/prettier/prettier/pull/3531#issuecomment-353769112.

**Comment by duailibe** [comment]
What would be the downside of simply changing the nested lists indentation from 2 to 4?

**Comment by iamcam** [comment]
Docs: https://bitbucket.org/tutorials/markdowndemo/overview#markdown-header-lists

I'll submit a feature/bug to their Jira and see what comes of it. I think a few links to widely-used parsers (common mark, GitHub, and SO) could help sway them. Lists aren't the only things that get screwy in Bitbucket md, but they're certainly the biggest pain points when I bring docs in from other sources.

**Comment by iamcam** [comment]
In the meantime, would it be such a big deal to infer the intent of nested list items and just make the indention 4 spaces (or two - give us a setting)?

**Comment by ikatyang** [comment]
After second thought, we can respect `tabWidth` here.
