### ISSUE TITLE
Removes parentheses when spread operator mixed with ternary (TypeScript parser)

### ISSUE THREAD

**Issue by jmrog** [prettier/prettier#3680]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEAOMCW6mAvJsADpSaYBmEESmA5AEYCGATkwDSXXsAvRkwCOAVzEAPHpQC+AbkqQoGTGLRwA8nkIqStNgBsNiqEvRYocAO6aWAK30UqmNBAC2WmAAs4HACJsMGyMAIy8LgD0kZgAKt74aJiG+FaYiZg+cJg4HBAshnDuQfhg2FZIfJgAdLUAFOpaOkQA-NjNeozAsgCUcqYg3CC4BOjIoJx51gAKnAhoyCCDIGwYyDRGGkMsHGxgANZwMADKOHupAObIMBxicEMAJhBg65v3IKkaHDDTuxfFr2M73saEkACFdgcjsc2J4ADKpOCArbDMQwHBogBMyPeZw4X0WMAAnjg4GgwBx8HhlrlUjAAOr4B4+ZAADgADENchANPTdjhFssOHBxPhhb82P82Dihhp3PgZSA0JdCgBFMQQeCK4IsRnM7zITFDG5sfApKAXADCHgBKCg0CRQ0asTYLAWSA2QNksiAA)
```sh
--arrow-parens 
--parser typescript
--prose-wrap 
--no-semi
```

**Input:**
```tsx
const options = {
  foo: 'bar',
  baz: 'quux',
};
const useOptions = false;

const newObj = {
  someOtherData: 1,
  // This line is the problematic one:
  ...(useOptions ? options : {})
};

```

**Output:**
```tsx
const options = {
  foo: "bar",
  baz: "quux"
}
const useOptions = false

const newObj = {
  someOtherData: 1,
  // This line is the problematic one:
  ...useOptions ? options : {}
}

```

**Expected behavior:**

I'd expect the parentheses around the ternary to be left in place, given the stated goal of leaving them in place when it helps to disambiguate code ([here](https://github.com/prettier/prettier/issues/187#issuecomment-356162615)).

Note that this happens only when using the TypeScript parser.
 
Thanks!

**Comment by duailibe** [comment]
Oh that should be an easy fix!
