### ISSUE TITLE
A single line of function in jsx becomes a fat multi-lines

### ISSUE THREAD

**Issue by Tanoemon** [prettier/prettier#3684]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeCAbABAJzgMwF5hMtCA+LYLGACwEsBnAOlMK0wF9PyAdKLFlQZ65VAHoRfKBMzkQAGhAQADjHrRGyUAEMcOCAHcACnoRaUOgG4R6AE0UgdjGMnw6MjOEoBGOHWAA1nAwAMoqAfRQAObIMDgArt4gdhBgbh5eSlFeODDG-tEAtjoZnskAVowAHgBC-kEhoTpFcAAyUXBlWcoJMCp9AEzdyRE4ucggPjo+AJ4Y0I4qOFEwAOr2dMgAHAAMSssQXmv+KpPLcLlWXUp4AI4J9HgFOsWlSO7lSl5F9HGJyUYUWiGDgAEUEhB4CMlDAZhs7FskINYf56CIYgBhCBFEqTKDQG4gBJeAAqMwsny83CAA)

**Input:**
```jsx
<ol ref={ol => { this.ol = ol}}>
  <li></li>
</ol>
```

**Output:**
```jsx
<ol
  ref={ol => {
    this.ol = ol;
  }}
>
  <li />
</ol>;
```

**Expected behavior:**
I think one line function is better because markdown readability is more important than function readability in jsx.

**Comment by azz** [comment]
We'll always be expanding blocks to multiline, but you can just remove the braces and it will be printed inline.

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeCAbABAJzgMwF5hMtCA+LGACwEsBnAOlMK0wF9yAdKLLVDLXKoA9IO5RRmciAA0ICAAcYtaPWSgAhjhwQA7gAVtCdSk0A3CLQAmckJvoxk+TRnpx5AIxyawAazgYAGVFX1ooAHNkGBwAVw8QawgwZ1d3eXD3HBgDHwiAW01UtwSAK3oADwAhH39AoM18uAAZcLhi9IVYmEVugCYOhNCcLOQQT01PAE8MaDtFHHCYAHUbGmQADgAGeQWId2WfRTGFuCzzdvk8AEdY2jxczQKipBcS+Xd82mi4hPpwiIYOAARViEHgg3kMEmq2s6yQfShPlogkiAGEIPlCmMoNBLiBYu4ACqTUxvdzsdhAA)

**Input:**
```jsx
<ol ref={ol => this.ol = ol}>
  <li></li>
</ol>
```

**Output:**
```jsx
<ol ref={ol => (this.ol = ol)}>
  <li />
</ol>;

```
