### ISSUE TITLE
Use cherow parser for JavaScript

### ISSUE THREAD

**Issue by rattrayalex** [prettier/prettier#3688]
The speed of prettier makes a difference to its usability, especially in a format-on-save scenario. 

I don't know how much of our current time is spent in parsing, but I would guess it's substantial.

According to [this benchmark](https://cherow.github.io/cherow/performance/), on my macbook pro in chrome 63, [Cherow](https://github.com/cherow/cherow) is about 40% faster than Babylon: 

<img width="934" alt="screen shot 2018-01-09 at 8 03 13 am" src="https://user-images.githubusercontent.com/704302/34730253-b0f1d8f6-f513-11e7-9815-7d9f7bac2fa3.png">

Note that Cherow does not yet support Flow syntax, which I assume would block use of Cherow by default; the author has claimed interest in adding support for Flow: https://github.com/cherow/cherow/issues/35

**Comment by azz** [comment]
TypeScript too. Ideally we'd be able to remove the `typescript` dependency too and go through babylon, as it will be much faster.

**Comment by duailibe** [comment]
Are there benchmarks comparing with Babylon 7 beta?

**Comment by j-f1** [comment]
Note that it [only supports stage 3 features](https://github.com/cherow/cherow#features) which could be a problem for users of stage 0-2 features.

It might be better to create a `prettier-plugin-cherow` module that allows people to opt into Cherow if they’re using stage 3+ JS features.

**Comment by suchipi** [comment]
We should probably benchmark how much time is actually spent parsing before pursuing this, to avoid implementing a premature optimization.

I think it should definitely be a plugin, though, rather than a builtin parser, due to the limitations.

**Comment by Airkro** [comment]
`cherow` is no longer maintained.

**Comment by thorn0** [comment]
its successor: https://github.com/meriyah/meriyah
