### ISSUE TITLE
Version 1.10 breaks the CLI

### ISSUE THREAD

**Issue by fatso83** [prettier/prettier#3697]
**Prettier 1.10.0**

```
$ npm i -g prettier
/usr/local/bin/prettier -> /usr/local/lib/node_modules/prettier/bin/prettier.js
+ prettier@1.10.0
added 1 package in 0.619s

$ prettier
module.js:529
    throw err;
    ^

Error: Cannot find module '../../index'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier/bin/prettier.js:38012:20)
```

**Expected behavior:**
It would list out the options

**Comment by fatso83** [comment]
By changing the `require` statements in line 38012 and 38746 from `../../index` to `../index` the CLI starts working again.

**Comment by fatso83** [comment]
This is fixed by 1.10.1!

**Comment by azz** [comment]
Sorry about that! Looks like our distribution tests didn't catch this. I've patched it in 1.10.1 but we'll have to improve the process.

**Comment by fatso83** [comment]
Thanks for the quick turnaround!

**Comment by azz** [comment]
Fix is in https://github.com/prettier/prettier/commit/cf511ec2e973ed6d794c5b99321f2b3a3458a919, I've opened #3698 to prevent this in the future.
