### ISSUE TITLE
Improve distribution tests

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3698]
`yarn test:dist` runs the tests against the built JS files, but it didn't catch an issue in 1.10 where a file with path `../../index` couldn't be resolved, because in the `dist` directory, `../../index` resolves to the original source. We could fix this by copying the files to a tempdir before running the tests.

It would be nice to test the actual `.tgz` file, too.

https://github.com/prettier/prettier/commit/cf511ec2e973ed6d794c5b99321f2b3a3458a919

#3697

**Comment by duailibe** [comment]
I've just seen this on twitter.. create a local npm registry, do an actual publish and install from it.

https://github.com/facebookincubator/create-react-app/compare/99c14e710ffb01d1c4a1124fc3ed2172bf58afbd...1098a4a177521f06febb1fcf7da94791febb19ba

**Comment by azz** [comment]
Nice. I've heard about this kind of thing.

I think a simple way of doing this is just to use `npm pack`.

```bash
dir=$(pwd)
cd dist
name=$(npm pack)

cd `$(mktemp -d)`
npm install $dir/dist/$name
$dir/scripts/test.sh
```
