### ISSUE TITLE
Support math expressions in Markdown

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3700]
From [a Gitter message](https://gitter.im/jlongster/prettier?at=5a1ac18371ad3f87362ff51c) by @Ciantic:
> Does people here use math extension of markdown? The prettier breaks the `$env$` because it re-wraps it, I know it's an extension of markdown, but it's very widely used in CS, I was wondering could Prettier include an exception for `$env$` and `$$env$$` for math mode?

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFnABHAjgVwEMYBLaLAMwgCcsZMssA3CAG3wFtsIKtCtqcMDEJQA5vlaFaAB2okAzhyyKsAEgBqWALxYAOnritWWAFRYA7mazo1AOj1RHag4VYz0hNSAA0ICDKk0ArIoNLUEBYACtIIISiELCQAJr4ghAowyBRuCnB+AEbUhGAA1nAwAMoyJSTiyDDU+PkgyRBg2bktdXnUMFHFYhyEnax5fgBWCgAeAELFZRWVhFwAMnVwo+P++DAyuwBMWy011L3IIMPUpW0WUGlydTAA6in0yABsAIx+chB5z2KMgubgshAAniE-IICCRBANCEMRkgcmMWnkOCQGk10XUxKw4ABFfAQeDHPwiAqvZLvJAHCnFEisPEAYQgHGGFyg0E2fnweVQhAK8VReQAvmKgA)
```sh
--parser markdown
--print-width 61
--prose-wrap always
```

**Input:**
```markdown
The equation for the  volume of a rectangular prism is $V = \ell * w * h$.

$\alpha$
```

**Output:**
```markdown
The equation for the volume of a rectangular prism is $V =
\ell _ w _ h$.

$\alpha$

```

**Expected behavior:**
```markdown
The equation for the  volume of a rectangular prism is
$V = \ell * w * h$.

$\alpha$
```

Note: [`remark-math`](https://www.npmjs.com/package/remark-math) is the plugin we should use here.

**Comment by Ir1d** [comment]
Hi I wonder if there's a way to set ignore all math during linting ?

adding `<!-- prettier-ignore-start -->` for each expression takes too much effort and messy my markdown file.

**Comment by suchipi** [comment]
@Ir1d there is not a way to ignore all math because up until #5050 was merged, prettier didn't know it was special. However, if you use the latest prettier from github, it will treat your math expressions correctly. Alternatively, you can wait for the next version of prettier to come out; it will include this change.

**Comment by Ir1d** [comment]
@suchipi Hi, thx for informing, I noticed #5050 yesterday and am still testing :smile: remark-math is really a good tool.
