### ISSUE TITLE
Self-closing tags prevent following nodes from being formatted

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3702]
**Prettier 1.10.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG5kD0JUqjmuBcLpqAzmABONLDBYAzCBAAUZAJS9GA4aJYgANCAiia0PslB5BgiAHcACkYT6UeOhBpUNIPHxjJxeHHziaARoJ4YADWcDAAylhBNFAA5sgwggCuviBUEGAeXj6aMT6CMOaBsRh4Wd6pAFZ8AB4AQoEhYeF4GHAAMjFw5TlaSTBY-QBMPalRgvnIIHQpzljCsADqjjAAFsgAHAAMmvMQPouBWFPzcPl03ZqCcACOSTTXRXglZUieFZo+GDQJyal8MViODgAEUkhB4KNNDA8H5llQ1sghtDAjQcICAMIQDClKZQaCXEBJHwAFVhNnePgAvlSgA)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <div />
</template>

<script>
foo( )
</script>

```

**Output:**
```vue
<template>
  <div />
</template>

<script>
foo( )
</script>

```

Related to #3692 

cc. @vjeux do you want to take a look at this?

**Comment by duailibe** [comment]
Looks like the parser doesn't handle self-closing tags at all.. it's not that it doesn't add `end` properties, but it parses everything below as children.

**Comment by vjeux** [comment]
@yyx990803 sorry to tag you here, but do you know how Vue works with self closing tags? I copy and pasted the parser file from vue but it seems like it's not working as expected.

Parser: https://github.com/prettier/prettier/blob/master/src/language-vue/parser-vue.js#L370-L406

Thanks!

**Comment by duailibe** [comment]
@vjeux I was just gonna comment here, I think it's actually this code here the problem:
https://github.com/prettier/prettier/blob/0e0fa5cc234edfb78a64086f6d72c483289a4cb4/src/language-vue/parser-vue.js#L385-L397

We shouldn't push an unary to the stack. Let me try to fix this and I'll report back :)

**Comment by duailibe** [comment]
Fixed in 1.10.2

**Comment by vjeux** [comment]
@duailibe thanks!

**Comment by azz** [comment]
Thanks! That's almost identical to my attempt at fixing the parser, I just missed the "don't push the unary onto the stack" bit!
