### ISSUE TITLE
Is there a way to use yarn prettier someFile.js to test the current project status like in the plugins?

### ISSUE THREAD

**Issue by thorbenvh8** [prettier/prettier#3704]
And if can we add it to the readme somewhere or to the contributing.md? Would be easier to work with it :)

**Comment by thorbenvh8** [comment]
yarn prettier doesn't show any changes

**Comment by duailibe** [comment]
Well what I usually do is use the tests for that.. `yarn test --watch` will rerun after code changes and you can quickly see the changes. Does that make sense?

**Comment by thorbenvh8** [comment]
what if you want some console.log(..) in the output?

**Comment by duailibe** [comment]
It will show up in the terminal

**Comment by thorbenvh8** [comment]
oh yeah sorry, my fault :)

**Comment by thorbenvh8** [comment]
After working with this solution for a little bit, im satisfied :)
@duailibe thanks!

**Comment by azz** [comment]
You can also do `./bin/prettier.js test.js`

**Comment by thorbenvh8** [comment]
But i need to do a "yarn build" before right? And that takes a long time, especially on the parsers.

**Comment by duailibe** [comment]
No, it should work without building

**Comment by thorbenvh8** [comment]
ok cool :)
