### ISSUE TITLE
Print Width Whitelist should be optional

### ISSUE THREAD

**Issue by tmquinn** [prettier/prettier#3706]
or at the very least, whitelisted methods should be exposed through config.

I would LIKE my testing methods to be prettier-fied. Also, since 'skip' is not one of the whitelisted words, when my bot goes in to auto-skip flakey tests, all of a sudden I have tons of prettier lint errors.

**Comment by j-f1** [comment]
Can you go to [the playground](https://prettier.io/playground/), paste in a sample of code that reproduces the behavior, then click on “Copy markdown” and paste the result into your issue description?

**Comment by tmquinn** [comment]
This is not an issue, specifically with a bad transform. It's related to 
https://github.com/prettier/prettier/blob/0e0fa5cc234edfb78a64086f6d72c483289a4cb4/src/language-js/printer-estree.js#L5123
https://github.com/prettier/prettier/issues/159
https://github.com/prettier/prettier/pull/953

**Comment by j-f1** [comment]
Can you still fill out an example so we make sure to fix the right issue and also so we have a test to prevent regressions?

**Comment by tmquinn** [comment]
To clarify, this would be more categorized as a critical feature request rather than a bug. I believe Prettier is performing as intended, I just don't like it's intentions... I will still attempt to include some sort of output.

**Comment by tmquinn** [comment]
**Prettier 1.10.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMAUByGALASzQAIjiBDYgJznIBs6BPYu6Ac2IBM40wqCADjALRiEAGbE0EALZxi6GMQCSxAO7lYCiMTY68cGtgA0xcQFcoYYaMzk0aQzACUxYAB0oxCg6c4DVAIAtNyB2M4A3J4Avs4gxiAQQiJQaMig5FRUEGoACpkIaSjkAG4QBJzxIPYwyOL0jgkARlTkYADWcDAAygJtBFBsyDBU5nAJnBBgdQ3jIAOOVDC5rWwy5DN0jSAAVmgAHgBCrR1d3eRyADIDcJvbEOYwAo8ATHdzfVSLyCBN5E2MVhQKoCfiwADqFXwyAAHAAGBKgiCOcGtAQ-UE8QwlW4JGgAR3MBBoK3Iaw2SHqWzmjhkBGGoxpAzYdDgAEVzBB4O8EjB-pDONCkC9ea0CHRmQBhWTrH5QaC4kDmRwAFX+RSpjmi0SAA)

**Input:**
```jsx
test('this is a really long description of some test I want to go here', function (assert) {
  assert('herp-derp');
})
```

**Output:**
```jsx
test("this is a really long description of some test I want to go here", function(assert) {
  assert("herp-derp");
});

```

**Expected behavior:**
This is the expected behavior

**Comment by tmquinn** [comment]
**Prettier 1.10.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnA1gSwA4AoDkMAFpqgASlkCGZATnFQDaMCeZj0A5mQCZyphaOGJmhkIAMzKoIAWzhl4qGGQCSZAO5VYiiGU56icevgA0ZCQFcoYEWNxVUqYzACUZYAB0oZak5cERrTYALR8wfiuANzeAL6uIKYgENh2UKjIoFS0tBAaAArZCBkoVABuEJg8iSCOMMgSTM5JAEa0VGDocDAAytgdmFCcyDC0lnBJPBBgDU0TIIPOtDD57ZyyVLOMzSAAVqgAHgBC7Z3dPVTyADKDcFs7EJYw2E8ATPfz-bRLyCAtVC0WBwoDVsEJYAB1KrEZAADgADEkwRBnBD2thfmD+MYynckvQAI6WTD0VZUdabJCNbbzZyyTAjMa0wacRhwACKlgg8A+SRgAKhPBhSFefPamEYLIAwnINr8oNA8SBLM4ACoAkrU5yxWJAA)

**Input:**
```jsx
skip('this is a really long description of some test I want to go here', function (assert) {
  assert('herp-derp');
})
```

**Output:**
```jsx
skip(
  "this is a really long description of some test I want to go here",
  function(assert) {
    assert("herp-derp");
  }
);

```

**Expected behavior:**
This is how I want it to look, or at least have 'skip' added to the whitelist, or even better, expose the whitelist

**Comment by j-f1** [comment]
👍 Thanks for the examples!

Maybe we should instead have it look for functions called with a string and a function. i.e. `foo("test name", function () { /* test */ })`.

Also, note that `test.skip` works here:

**Prettier 1.10.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMB0aDWBLABwAoByGACzzQAIrqBDagJznoBs2BPat6Ac2oATOGjBNCMPNGoQAZtTQQAtnGroY1AJLUA7vVhqI1PkfJwWJADTVZAVyhhJ0ovTRpzMAJTVgAHSjUDG4epGZMBAC0wuEkngDc-gC+niCWIBAETlBoyKD0TEwQOgAK+Qg5KPQAbhB4gqkgrjDIsuzuaQBGTPRgOHAwAMoEPXhQfMgwTLZwaYIQYC1tMyCj7kwwxd18SvSLbO0gAFZoAB4AQt29-QP0KgAyo3B7BxC2MARvAEzPy8NMa8gQB16B1OLwoA0COJYAB1OoUZAADgADGkoRB3DDugRAVCROYqk80iwAI62PAsTb0ba7JCtfbLdxKPATKaM0Z8NhwACKtgg8B+aRgILhggRSE+Qu6eDYHIAwsodoCoNAiSBbO4ACogir09yJRJAA)

**Input:**
```jsx
test.skip('this is a really long description of some test I want to go here', function (assert) {
  assert('herp-derp');
})
```

**Output:**
```jsx
test.skip("this is a really long description of some test I want to go here", function(assert) {
  assert("herp-derp");
});

```

**Comment by tmquinn** [comment]
yes, but test.skip is not a function of QUnit, while I would prefer to disable the whole whitelist, at the very least I would like to add skip() to the whitelist.

**Comment by azz** [comment]
`test.skip = skip`?

**Comment by duailibe** [comment]
> Maybe we should instead have it look for functions called with a string and a function. i.e. `foo("test name", function () { /* test */ })`.

That is already one of the conditions (function call with 2 arguments: first a string, second a function).. The other one is the name of the callee

https://github.com/prettier/prettier/blob/d0d5845af140fed30309a1966b05692dcae37f40/src/language-js/printer-estree.js#L5123-L5142

**Comment by suchipi** [comment]
I don't think a config option for this would be appropriate, but I think we could add support for a bare `skip` in `unitTestRe`, if that's common in QUnit.

Somewhat related... I have been selfishly wishing that prettier formatted my [`describeComponent`](https://github.com/suchipi/describe-component) helper with the `isTestCall` logic, but it didn't seem appropriate to do for such a small library.

**Comment by j-f1** [comment]
@suchipi What do you think about my comment above?

> Maybe we should instead have it look for functions called with a string and a function. i.e. `foo("test name", function () { /* test */ })`.

**Comment by suchipi** [comment]
I think that heuristic would hit too many false positives, eg:
```js
addListenerForPath("foo.bar", () => { /* ... */ }
```

**Comment by tmquinn** [comment]
@suchipi which of the config options do feel is not appropriate, printWidthWhitelist: 'disable', or having an printWidthWhitelistMethods: ['test', 'skip']

Personally, I feel like this whole feature is a bit of a kludge, which is kinda surfaced by @azz's suggested workaround. Specifically I take issue with the arbitrariness of the whitelisted method names and the effort that is going to be required to keep this up to date for every user's setup. It seems to me that removing the internal printWidthWhitelist list, and making it 100% configurable as I mentioned above would make it more clear to users what is going on...

**Comment by suchipi** [comment]
I don't think either config option is appropriate. A project goals of prettier is to have very few configuration options and be opinionated, but still work well despite the lack of configuration. The special-case formatting for tests is a very fine-grained and scoped feature, and it does not feel appropriate to add an option for such a specific case when we have rejected adding options for other more broad cases, such as adding a space between the keyword `function` and the parameter list.

Prettier has chosen to format test methods this way because that's what users of jest, mocha, and jasmine requested, and often would have written by hand anyway. I recognize that the current behavior is inconsistent when using QUnit which is frustrating. I think the appropriate fix is to format `skip` like we do `describe` and `it` and etc, instead of making this behavior configurable.

**Comment by tmquinn** [comment]
Hey, thanks for your response, I will submit a PR shortly. 

As a parting comment, I'd like to say that I love opinionated and appreciate it it's value. I agree that either config option would not be in the best interest of Prettier, but perhaps the feature itself should be re-evaluated. It seems to simply be // disable-prettier-ing based on an arbitrary and not particularly well documented list of methods. I believe that more users, such as myself, will be using test suites that Prettier will feel compelled to support. This adds overhead. In the absence of such curation, users will begin to implement workarounds, as mentioned above, or just fork the repo.
