### ISSUE TITLE
Missing `bin/prettier.js` in 1.10.2 release

### ISSUE THREAD

**Issue by kwiniarski** [prettier/prettier#3709]
It seems that `bin/prettier.js` has gone in the last npm release. However I don't see this is CHANGELOG.md so not sure is it intentional. Nevertheless, some tools depending on it now fail. For example Angular CLI with nx schematics.

https://unpkg.com/prettier@1.10.1/bin/prettier.js - OK
https://unpkg.com/prettier@1.10.2/bin/prettier.js - Cannot find module "/bin/prettier.js" in package prettier@1.10.2

**Comment by ikatyang** [comment]
We've changed it in https://github.com/prettier/prettier/issues/3574#issuecomment-356605745 and it's now [bin-prettier.js](https://unpkg.com/prettier@1.10.2/bin-prettier.js), not sure if it's considered a public interface. Isn't `node_modules/.bin/prettier` the standard entry point?

cc @azz

**Comment by lydell** [comment]
Seems like you’ve been relying on an implementation detail.

**Comment by azz** [comment]
You should read `"bin"` from `package.json` https://unpkg.com/prettier@1.10.2/package.json, as we occasionally restructure the files we ship to npm.

**Comment by kwiniarski** [comment]
Problem is inside tool I use: https://github.com/nrwl/nx/blob/3531323fb5210b995b1296a198c8e76ee8bf9a07/packages/schematics/src/command-line/format.ts#L59. I wonder how many other tools may do this in similar way, since I have seen this practice in other places (not related with Prettier).
So you suggest it should be fixed inside `@nrwl/schematics`?

**Comment by azz** [comment]
Yes, it should be

```diff
-      `node ./node_modules/prettier/bin/prettier.js --single-quote --print-width 120 --write ${patterns.join(' ')}`,
+      `node ./node_modules/.bin/prettier --single-quote --print-width 120 --write ${patterns.join(' ')}`,
```

**Comment by mnemanja** [comment]
Would be nice if you can update the documentation with it. 
https://prettier.io/docs/en/webstorm.html

**Comment by mnemanja** [comment]
It should point to `/bin-prettier.js` instead of `.bin/prettier` or `.bin/prettier.cmd`.
![image](https://user-images.githubusercontent.com/1423218/38465510-e1be35ca-3b1c-11e8-9a0b-f32f1f23c539.png)

**Comment by j-f1** [comment]
@mnemanja That’s the correct path. We could change the path of `bin-prettier.js` to `this-is-the-cli.js` in the next patch release, but `node_modules/.bin/prettier` (or `node_modules\.bin\prettier.cmd`) will always link to the CLI.

**Comment by mnemanja** [comment]
@j-f1 thanks for the explanation 👍

**Comment by ilikebits** [comment]
This also breaks `yarn global add prettier`, which creates a symlink to the non-existent `prettier/bin/prettier.js` instead of `prettier/bin-prettier.js`

**Comment by ikatyang** [comment]
@ilikebits 

The `bin` field in [`package.json`](https://unpkg.com/prettier@1.10.2/package.json) did point to `./bin-prettier.js`, I don't think it's possible for yarn to create a symlink to `bin/prettier.js`, I guess there might be some cache issues in your yarn?
