### ISSUE TITLE
cannot do selection highlight on the left side of playground

### ISSUE THREAD

**Issue by viankakrisna** [prettier/prettier#3710]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoWATrrAOq4AmMAFsgBwAMGMAhgEbV2NIAmDAQoBzADZwAigFcI8ZADMO4gnHakOucWIDCEALYGOyEFGhx0ILprABrODADKWDmDHIYpGepAArAgAPACFbB2cOAzgAGQpLJGVVX1dSNVJTLm4AT3FoKzUDXE9vXxk1ABVuIgSVNQwKNJgABU1RYyVa31I4AEcZXG6WjjaTGqSMMgg1Sk0sUzI4NIA3SwwOUlIIAHcm9YRqkA4liForGggwDvHDghgruswZGCwngXu4AF8PoA.)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
// code snippet
```

**Output:**
```jsx
// code snippet
```

**Expected behavior:**
i can edit the left side to see how it works on the right side

**Comment by ikatyang** [comment]
Can you share more context on how to reproduce? and a screenshot with error message?

![image](https://user-images.githubusercontent.com/8341033/34817065-d36b95d6-f6f1-11e7-8c95-4174622bc882.png)

**Comment by viankakrisna** [comment]
Sorry for the short reports, I was just checking if it happens only for me. Turns out that I cannot highlight the code in the left area using `command + A` on my mac, that's why i think it's broken.

**Comment by ikatyang** [comment]
That's a placeholder, see #3657. 😂

**Comment by viankakrisna** [comment]
yea 😭

**Comment by viankakrisna** [comment]
maybe keeping this open? Even if it's only a placeholder, the result is already on the right. I think that's why my first instinct is to select all to clear the left side. Would be useful for a sleep-deprived people like me that wanted to play. 😄

**Comment by ikatyang** [comment]
Yeah, that's something we can improve but need some ideas, can you open another issue to track it?

**Comment by suchipi** [comment]
For what it's worth, this confused me, too.

**Comment by duailibe** [comment]
I don't think there's enough value in having placeholders anyway, I'd remove them if it was up to me :)
