### ISSUE TITLE
Rename the “status:help wanted” label to “help wanted”

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3717]
GitHub has special support for the “help wanted” label, including putting “X issues need help” near the repository name at https://github.com/prettier, and saying

![Issues labeled [help wanted] can be good first contributions.](https://user-images.githubusercontent.com/25517624/34833681-0731590c-f6be-11e7-8eaf-c34bad6c2202.png)

on the issues page. However, this doesn’t work for our “status:help wanted” label. Should we rename “status:help wanted” to “help wanted”?

**Comment by azz** [comment]
Works for me, just don't forget to update [the wiki page](https://github.com/prettier/prettier/wiki/Issue-Labels) if you change it.

**Comment by duailibe** [comment]
Done!
