### ISSUE TITLE
[vue] SFC with ESLint results in "Unexpected token <"

### ISSUE THREAD

**Issue by sanderwapstra** [prettier/prettier#3720]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQVmoAmAlgG4nmUsAStANGTABa0DOZAWTxk4ADzzYccMpGzQEMAHSkWqAPR1GpTZlwE4TXfzAAnWlhhMWErBDMwy1OADM8AVxxPgalpQwID1g4agAKAEoyX2Z-f0gofggZZRwIAHMwgHIAYQgFKCUyQOD4amUsiIBuPziAX1qyOpqoTVMLKyYQDhAIK1pofmRQPDMzCAB3AAVRhCGUPHoIWmpukDx+GGR3HH44HoAjMzwwAGs4GABlLBPaKHTkGDMPfZBqCDBtvF3Xu73HKbHdIYPBfH49ABW-HEACFjmcLpcpHAADJ3OBgvY9IIwLAeGAAJkxrxuZn+yBA9BeaywFlgAHUVrxkAAOAAMPVpED29OOWAptLg-3oGJ6ZjgAEcPLRxYC8MDQUgdliQHsMLRHs9Xvw7ukZABFDwQeDEnowPAHRnUZlIAlm460HC6vIYEEUqCKNYePYAFQt82VcDqdSAA)
```sh
--parser vue
```

**Input:**
```vue
<template>
    <div>
        Hi, this is a example component.
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.');
        }
    };
</script>

```

**ESLint config:**
```json
{
    "extends": "plugin:prettier/recommended",
    "parserOptions": {
        "sourceType": "module",
        "ecmaVersion": 8
    },
    "env": {
        "es6": true,
        "browser": true
    },
    "rules": {
        "no-console": "off",
        "linebreak-style": "off"
    }
}

```

**Expected behavior:**
In the playground everything works but when using with ESLint (gulp) the error `Parsing error: Unexpected token <` occurs.

**Comment by azz** [comment]
I think you need to use [eslint-plugin-html](https://www.npmjs.com/package/eslint-plugin-html) or [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) for ESLint itself to parse the HTML files.

**Comment by sanderwapstra** [comment]
@azz Thank you, solved!
