### ISSUE TITLE
Playground not working with Vue SFC

### ISSUE THREAD

**Issue by jackmu95** [prettier/prettier#3726]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoBGArjDNKRRWPgM5sC8x4OEbcHk2YwAnljjcQteoxDCKSPACcAlngC0+KnBxTtuoeWYABVqrABrAHRZlcAG4IYUgCRwMqmAAoA5OatfAEojChJjClRVDQtGCOYoPAxJHigwDSoIHAATDXsMCCdQ5kU2VQAvFJBYqABlCsF5eMU8HFUAcygNBm64AA8XHgBCEZr6yp4yAHpwyKmZBihw1CnMXAI4cNJUNjA1LBhw1WwIZRgyVQBJSHIAM2UIDDJfayma3wBuUlJ+rFPz7JwW54Gg4c7AYSQE5QZxsJBkYAXa7QMgAXwANMI7BAsHCEQoyAYcPCIc0yGIJPDajA1FB2piyYDgaCfEF8WSKPYYDRlOQYAALVRsayuHz+U5waztBBwZStaysfhwYJfMmogkYgljBokgkUClweEAORoGB0ygZJQoTJBYPhUFBOA1wnVUFRqpWu32h1IIHRIBxMFU0DYyFAKgeAHcAAoqBChlB4BwQVTZP0gPBsGDIYE4AT+qhyqxwGC1LB4MCqOnIGk0OD+7IQMA51r56pQARnaNy9oYPAtvP1kAAKzYfQAQkXLCXakk4AAZKtwAdtiB0LB0ABMK6H5eUneQ0jwVFEfCg6bsVZgAHVUwLkABGAAMT-92IE17lWEPdjgnac6b2AAjjQqj2N2eC9v2SC5m2AieDWyh1v6ZR0jgcAAIo0BA8CIchIAwMet7ZPeSCbv6NJ4KobR0gAwo8faHlA0DLv6NACAAKseCawXAqKokAA)
```sh
# Options (if any):
--print-width="100"
--single-quote
```

As seen in the playground a `SyntaxError: Unexpected token (5:5)` is thrown complaining about the `v-bind` shorthand (`:aria-label="label"`) on line 5.

**Comment by azz** [comment]
It's a bit hidden right now, but you need to go to `options` -> `parser: vue` for it to work.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoBGArjDNKRRWPgM5sC8x4OEbcHk2YwAnljjcQteoxDCKSPACcAlngC0+KnBxTtuoeWYABVqrABrAHRZlcAG4IYUgCRwMqmAAoA5OatfAEojChJjClRVDQtGCOYoPAxJHigwDSoIHAATDXsMCCdQ5kU2VQAvFJBYqABlCsF5eMU8HFUAcygNBm64AA8XHgBCEZr6yp4yAHpwyKmZBihw1CnMXAI4cNJUNjA1LBhw1WwIZRgyVQBJSHIAM2UIDDJfayma3wBuUlJ+rFPz7JwW54Gg4c7AYSQE5QZxsJBkYAXa7QMgAXwANMI7BAsHCEQoyAYcPCIc0yGIJPDajA1FB2piyYDgaCfEF8WSKPYYDRlOQYAALVRsayuHz+U5waztBBwZStaysfhwYJfMmogkYgljBokgkUClweEAORoGB0ygZJQoTJBYPhUFBOA1wnVUFRqpWu32h1IIHRIBxMFU0DYyFAKgeAHcAAoqBChlB4BwQVTZP0gPBsGDIYE4AT+qhyqxwGC1LB4MCqOnIGk0OD+7IQMA51r56pQARnaNy9oYPAtvP1kAAKzYfQAQkXLCXakk4AAZKtwAdtiB0LB0ABMK6H5eUneQIAcdfTdirMAA6qmBcgAIwABnv-uxAgvcqwh7scE7TnT9gAjjQqj2N2eC9v2SC5m2AieDWyh1v6ZR0jgcAAIo0BA8BwQhIAwHgVBXtkN5IJu-o0ngqhtHSADCjx9oeUDQMu-o0AIAAq+EJlBcCoqiQA

**Comment by azz** [comment]
I think we should add a list of language buttons to the header of the page, rather than hidden away as it is now. @duailibe maybe you want to do this in #3573?

**Comment by jackmu95** [comment]
Is the `parser` option dynamically set when running `prettier` via CLI on multiple filetypes?

**Comment by ikatyang** [comment]
Yes, it'll infer the `parser` based on the extname, but you have to specify glob with extname (e.g. `prettier **/*.{js,vue} --write`) so that it won't accidentally format unsupported filetype since our default `parser` is `babylon`.
