### ISSUE TITLE
Weird formatting when a paren is following a template string literal

### ISSUE THREAD

**Issue by rhysd** [prettier/prettier#3727]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8OYLyYAGhAOlABQAsATAJRkgA0IEADjAJbrKgCGATvwgB3AAoCEaZCF4A3CBwAmTGRmQAzXgBs0cZgCN+vMAGs4MAMqtjHKAHNkMfgFc9IRRDAbtu5rd38MKJGdgC2vN46bgBWaAAeAEJGpuYWvKFwADK2cJG+LM4wrIXUeW7W-AHS+rz6AJ5a0Cqs-LYwAOpKMAAWyAAcAAzMLRC67Uas0i1wAbK5zPxwAI7OHIvBvGERSJpRzLqhHI4ubmi2dlpwAIrOEPBlzDC1nYo9yNSPRhxa5wDCEKFwtIoNB5iBnLoACq1KQ7HxwAC+CKAA)

**Input:**
```jsx
const test = ``
(42)

```

**Output:**
```jsx
const test = ``(42);

```

**Expected behavior:**

```jsx
const test = ``;
42;
```

or

```jsx
const test = ``;
(42);
```

I'm not sure that this is a real problem. It may be a restriction of automatic semicolon insertion.

**Comment by azz** [comment]
>  It may be a restriction of automatic semicolon insertion.

Correct. Prettier is actually pointing out a mistake in the code. Both of your expected behaviours would alter the running of the program.

There's a PR to the JS spec to warn about these kinds of ASI hazards: https://github.com/tc39/ecma262/pull/1062

**Comment by rhysd** [comment]
Thank you for your explanation. I understood.
