### ISSUE TITLE
Italic underscore in markdown

### ISSUE THREAD

**Issue by aduh95** [prettier/prettier#3728]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABACTgGxxAHSiOwCc50BLAZ3WogFsLKYBDHSsJdAKmzwgB9AOoRSOACY8ScclVr0m6BmLjdB-fAQIixkwUSIARaHAB0REABoQEAA4xK0aslCtSpCAHcACu4QuKKwAbhCUEtYgrNQwyABm7NRwNgBGpKxgANZwMADKdhmUUADmyDCkAK7JIBIQYPGJ1UVJpDA+6cUMrA04STYAVtQAHgBC6Vk5uaxMADJFcD19thUwdisATIvVBaQtyCBdpJm1XlCRdqRFMMLhMAAWyAAcAAw2FxBJwul2+xdwLcEFjZyABHCqUcjtVidbpIBK9apJBiUMqVRFFYo4OAARQqEHgWxsbBSNwk92Q6yJ6UoHBKAGFGF19lBTJEKkkACqsFKBeFJAC+-KAA)
```sh
--parser markdown
```

**Input:**
```markdown
# Hello

Here is some italic: *Hello_World*
Here is some more: _Hello\_World_

Done.

```

**Output:**
```markdown
# Hello

Here is some italic: _Hello_World_
Here is some more: _Hello_World_

Done.

```

**Expected behavior:**

It should be possible to have underscore in an italic expression. All the markdown parser I tried don't render correctly my example:

```html
<!-- Current behavior -->
_Hello<i>World</i>
<!-- Or -->
<i>Hello</i>World_

<!-- Expected behavior -->
<i>Hello_World</i>
```

**Comment by ikatyang** [comment]
It's a valid formatting based on [CommonMark playground](http://spec.commonmark.org/dingus/?text=%23%20Hello%0A%0AHere%20is%20some%20italic%3A%20*Hello_World*%0AHere%20is%20some%20more%3A%20_Hello%5C_World_%0A%0ADone.%0A%0A%23%20Hello%0A%0AHere%20is%20some%20italic%3A%20_Hello_World_%0AHere%20is%20some%20more%3A%20_Hello_World_%0A%0ADone.%0A):

![image](https://user-images.githubusercontent.com/8341033/34877079-711f0a18-f7df-11e7-84ef-46347cb8f2a1.png)

It seems the parser you used is not following the CommonMark spec, I'm not sure what we can do here.

**Comment by aduh95** [comment]
Thanks for your answer, indeed Prettier have the correct behavior and the parsers I tried don't. I'll open open an issue to them, then.

There is [an example in the CommonMark spec](http://spec.commonmark.org/0.28/#example-356) describing this very behavior.

**Comment by ikatyang** [comment]
The first case looks good, but the second one is not safe since it can be parsed as `*`-style `strong` if you type something `**` before it, e.g. `**x __Hello**World__`, I think it's important to let people keep typing valid syntax without being parsed as something unexpected, i.e. whatever you typed (the inserted part) is valid, then the output should be valid.
