### ISSUE TITLE
Indentation rule conflict with `react/jsx-indent`

### ISSUE THREAD

**Issue by IanEdington** [prettier/prettier#3734]
Issue with Prettier support for eslint. Eslint rule saying one thing prettier rule saying the other.

Of course I can just remove the eslint rule from my config... but I hope others can benefit from me finding this.

By the way this didn't work for me: https://prettier.io/playground

Indentation of HorizontalLine

```
      .concat(
        user ? (
          <UserDetails
            email={user.email_address}
            name={`${user.first_name} ${user.last_name}`}
          />
        ) : null,
      <HorizontalLine key="hr1" />
      )
```
throws: `Insert `··` (prettier/prettier) [javascript/eslint]`

```
      .concat(
        user ? (
          <UserDetails
            email={user.email_address}
            name={`${user.first_name} ${user.last_name}`}
          />
        ) : null,
        <HorizontalLine key="hr1" />
      )
```
throws: `Expected indentation of 6 space characters but found 8. (react/jsx-indent) [javascript/eslint]`

**Comment by suchipi** [comment]
Please use `eslint-config-prettier/react` to disable rules from the react plugin that conflict with prettier; see https://prettier.io/docs/en/eslint.html#turn-off-eslint-s-formatting-rules and https://github.com/prettier/eslint-config-prettier#installation for more info.

.eslintrc.json:
```json
{
  "extends": ["prettier", "prettier/react"]
}
```

**Comment by IanEdington** [comment]
Should that not be included in

"plugin:prettier/recommended"

**Comment by j-f1** [comment]
No, because it requires `eslint-plugin-react`, which isn’t installed by default.
