### ISSUE TITLE
RFC: Inline comma selector if headers are being selected

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3742]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALAjAGgASoEw6oDMhALNsADpTbYBm0MAtAO5wCWA5qjEtgDZceAbmoBfatQyYpJKQFYK1WpH4QATnwDERXaKgSoITCAgAHGO2gBnZKACG69RBYAFRwlsp7ANwjsAE2MQe2sYZDp7fms4EwAjdXswAGs4GABlMyT2KE5kGHUAV1iQAIgwCKiYkxyY9RhXRM4AW3tK6JKAK2sADwAhRJS09PtmuAAZHLh26tNCmDN5vBmSrPU65HBrWxMzdRyYAHVAmFRkAA4ABl3nGMPEs029uDqfaZN1OABHQvZPxvsLTaSEiHRMMWa7HyRRK1hynH4cAAioUIPAViYYPY4scAqdkAQQAV7OxBLkAMIQZqtTZQaDvECFGIAFWxXlBMTEYiAA)
```sh
--parser css
```

**Input:**
```css
h1, h2, h3, h4 {
  font-weight: light;
}

h1,
h3,
h5 {
  color: #333;
}

```

**Output:**
```css
h1,
h2,
h3,
h4 {
  font-weight: light;
}

h1,
h3,
h5 {
  color: #333;
}

```

**Expected behavior:**
Same as the input

**Proposed heuristic:**

Inline the `,` selectors if **all** of the following are true:

- All selectors are element selectors
- All selectors match `h[1-6]`
- Each selector in a sorted copy of the selector list is exactly one level lower than the previous selector

This is more legible IMO because [in some cases](https://github.com/j-f1/forked-desktop/commit/15e8fcf623b32c0d2f865b0f9c4be03810c76443#diff-fde369b8ffcd39029676e27fae6861cfL84), you’re selecting all `h*` elements, but there’s no way to do that with one selector, so you have to say `h1, h2, h3, h4, h5, h6` which gets broken onto 6 lines.

---

I wonder if we should do this for [`ol` and `ul`](https://github.com/j-f1/forked-desktop/commit/15e8fcf623b32c0d2f865b0f9c4be03810c76443#diff-2392f0eab6cafa1b700c71df883d1b1dL236) or [`input` and `button`](https://github.com/j-f1/forked-desktop/commit/15e8fcf623b32c0d2f865b0f9c4be03810c76443#diff-5ba2057f32edb21b549c419e997f4dedL56), too.

…or is this way too much effort for a tiny (or negative) readability gain?

**Comment by lydell** [comment]
> This is more legible IMO because in some cases

I'd say once per code base. Tops twice. So in my opinion it's not worth it. It's not like this is going to improve every CSS file of a code base or so.

**Comment by j-f1** [comment]
> I'd say once per code base. Tops twice.

Very good point. The feature started making less and less sense to me as I finished writing up the issue.

Closing for now, but if anyone feels that this would be a worthwhile improvement, feel free to comment.
