### ISSUE TITLE
If i know my current path is in an array

### ISSUE THREAD

**Issue by thorbenvh8** [prettier/prettier#3743]
How can I find out was was my previous element?

[element1, current, element2]

How do i get element1 from current?

**Comment by j-f1** [comment]
Maybe `path.getParentNode()[Number(path.getName())-1]`?

**Comment by thorbenvh8** [comment]
Yes you got me to the right idea :)
`path.getParentNode().parentProperty[Number(path.getName())-1]?`
Didn't know getName gives me the index :)
