### ISSUE TITLE
Getting the plugins into the playground?

### ISSUE THREAD

**Issue by thorbenvh8** [prettier/prettier#3744]
prettier-java is getting along and I would like to have it in the playground. My question is do I need to build my own, or can we add it there somehow?
I think the playground is the first step of giving it a try and for prettier-java to get more usability, this would be a first step.
Thanks :)

**Comment by azz** [comment]
This  is a good question. If it can bundled in to single file then we should be able to build a mechanism to load it. Maybe even from `unpkg.com`?

**Comment by azz** [comment]
Or maybe even https://bundle.run?

**Comment by thorbenvh8** [comment]
Ok I understand that concept, but I have no idea how to implement this.

I'm going to publish prettier-java to npm, so you can try it out? :)

**Comment by thorn0** [comment]
Closing in favor of #4400
