### ISSUE TITLE
New line type for better supporting of comments

### ISSUE THREAD

**Issue by thorbenvh8** [prettier/prettier#3746]
Another line type, where wen it breaks you can add some characters to the beginning of the line.

For example you have a comment:
`"//Some comment that is very long".replace(" ", charline("// "));`
so when it needs to break because of the length it turns out like this:
`"// Some comment that"`
`"// is very long"`

I would implement this myself, just point me into the right direction? :)

**Comment by azz** [comment]
Is this #265?

**Comment by thorbenvh8** [comment]
Yes thats the feature, but I basically only need a way to create a new line type, and its very easy to implement.

I looked into the code and I couldn't find where the print decides for example "hardline" && max width, create new line

**Comment by thorbenvh8** [comment]
I published it but I think the bundling is incorrect :) I have to bundle it correclty first...

**Comment by azz** [comment]
Oh, we have that with `indent("//", parts) ` from memory.

**Comment by azz** [comment]
https://github.com/prettier/prettier/blob/master/src/language-markdown/printer-markdown.js#L171

**Comment by j-f1** [comment]
Is this still needed?
