### ISSUE TITLE
Bad logs

### ISSUE THREAD

**Issue by splincode** [prettier/prettier#3752]
If my code failed 

npm scripts for angular applications
```
"prettier:fix": "prettier --parser typescript --single-quote --trailing-comma es5 --write \"./**/*.ts\" -l",
"precommit": "npm run prettier:fix"
```

I don't understand what happened

![image](https://user-images.githubusercontent.com/12021443/35035141-741ef00c-fb81-11e7-9788-d3c0f5087a1e.png)

![image](https://user-images.githubusercontent.com/12021443/35035132-6be52636-fb81-11e7-9ee5-754fa2f1f89f.png)

**Comment by ikatyang** [comment]
Could you share steps to reproduce? I don't really understand what happened from the screenshot, there's no stack trace from prettier.
