### ISSUE TITLE
Markdown doesn't format table correctly if column contains ``

### ISSUE THREAD

**Issue by maximbaz** [prettier/prettier#3753]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABJANgRnR7AJn0wiwGZ8AdKVAWgfrqdRoy2gHN14APGEgANBJPgNQgANCAgAHGAEtoAZ2ShZAJwWwA6goAmMABbIAHAAZpMAIYAjPYZNJC05ds5Y4ARQCuEeMgAZtZYynBWGtYKWO4AwhAAtgnWyCBQ0HBSILaRYADWcDAAyrLWYO7IMBo+4SAAVsq8AEK5BcXWCXAAMtqZSMGhtaUaYRqpyRp5+hAA7lBZYQkKldW1PmEAKnaq-SFh0tqjMAAKkZzJQXu1GnAAjj4KN6fW5ym7g9KaEGE6kbKpmjgowAbplpNYNBpZscIQgdiBrMCIAYstMwJcPgjlDAMfsZD4YLICYRcXAAL5koA)
```sh
--parser markdown
```

**Input:**
```markdown
| col1 | col2 | col3 |
|---|--|--|
| long text | `` | text |
```

**Output:**
```markdown
| col1      | col2      | col3 |
| --------- | --------- | ---- |
| long text | `` | text |

```

**Expected behavior:**
```markdown
| col1      | col2      | col3 |
| --------- | --------- | ---- |
| long text | ``        | text |

```

**Comment by ikatyang** [comment]
This is caused by mis-parsing from our markdown parser, opened remarkjs/remark#320.
