### ISSUE TITLE
Markdown: do not remove leading & trailing whitespaces in inline code blocks

### ISSUE THREAD

**Issue by maximbaz** [prettier/prettier#3754]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAHATnAzndA3OAAgBs4BDAEwEsoBzQsqCwmdMq4m+gdwAsr4WVGTDZCNcVE5QikCnCSEABoVW84xYhFWqlIADQgIqGFWhZkoMunQRuABWsILKMnghUKBkGSwxkAGZkxDiGAEZsYADWcDAAysJgXMisAK5whhQQYIHBoSA0OOgw9my0ALZkuSEZIABWWAAeAEKRMfFk5XAAMjRw1fkQqTCowwBMA7XC6EXIIJXoUVncUN4YNDAA6p4wvMgAHAAMhhgQOJtsqHMY2LgE3pgAjqlUmKVkFVVIQTWGOOVUFLodJ-LikACKqQg8EmhhgZDC2wou2QYzhbA4XAAwhBypU5lBoP1DKkcAAVBEuH44AC+NKAA)
```sh
--parser markdown
```

**Input:**
```markdown
preserve leading and trailing whitespaces in inline code: `   hello    `
```

**Output:**
```markdown
preserve leading and trailing whitespaces in inline code: `hello`

```

**Expected behavior:**
```markdown
preserve leading and trailing whitespaces in inline code: `   hello    `
```

**Comment by ikatyang** [comment]
Based on [CommonMark spec - code spans](http://spec.commonmark.org/0.28/#code-spans), whitespaces did nothing there. Is there any reason you want to preserve it?

**Comment by maximbaz** [comment]
Oh thank you for this comment, you are completely right and it is a bug on our side. 

I initially reported this, because in our documentation we have a few configuration variables, whose default value is a symbol with trailing whitespace (e.g. `_`), and until now I have not noticed that when the documentation is rendered, it actually strips leading and trailing whitespaces.

Prettier has helped us catch the bug 🎉

**Comment by j-f1** [comment]
If you want a space in a code span, you can try ` ` (U+00A0 NO-BREAK SPACE)

**Comment by maximbaz** [comment]
Awesome, thank you!

**Comment by maximbaz** [comment]
Ha ha, but prettier strips this no-break space too... Bug after all?

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAHATnAzndA3OAAgBs4BDAEwEsoBzQsqCwmdMq4m+gdwAsr4WVGTDZCNcVE5QikCnCSEABgAK1vOMWIQ1KpSAA0ICKhhVoWZKDLp0EbgAUbCSyjJ4IVCoZBksMZAAzMmIcIwAjNjAAazgYAGVhMC5kVgBXOCMKCDAgkLCQGhx0GAc2WgBbMjzQzJAAKywADwAhKNiEsgq4ABkaOBqCiDSYVBGAJkG64XRi5BAq9Gjs7igfDBoYAHUvGF5kAA4ABiMMCBwttlR5jGxcAh9MAEc0qkwyskrqpGDaoxwKlRUugMv8uKQAIppCDwKZGGBkcI7Ch7ZDjeFsDhcADCEAqVXmUGgAyMaRwABVEa5fjgAL60oA

**Comment by ikatyang** [comment]
That's another [mis-parsing](http://astexplorer.net/#/gist/981820a08e2310097ed01236175fcaf7/880d65bab3c76e74913fc6fd74f9c22c3c8103fc) from remark...

**Comment by maximbaz** [comment]
Nice finding 👍 Should I reopen the issue, and will you report this to remark or should I do it?

**Comment by j-f1** [comment]
[According to the JS spec](https://tc39.github.io/ecma262/#prod-WhiteSpace), [`\s` matches `\u{A0}`](https://runkit.com/embed/6gtxdfohxfit).

**Comment by ikatyang** [comment]
I think it'd be better to open another issue, and if you could also report to remark that would be appreciate.

**Comment by maximbaz** [comment]
Created #3755.

@j-f1 agree, but since markdown _allows_ me to add `trailing no-break whitespaces      `, prettier shouldn't remove them.
