### ISSUE TITLE
Is it possible to only run prettier on staged files - akin to pretty-quick

### ISSUE THREAD

**Issue by jackson-sandland** [prettier/prettier#3765]
I'm running a javascript project - and I've got the following in my `package.json`:

```
"pretty-scss": "prettier src/**/*.scss --write",
"precommit": "prettier src/**/*.js --write && npm run pretty-scss && npm run test"
```
Using the `pretty-quick` npm module it's possible to add `--staged` to the script, and have prettier only run on the staged files. 

Is this possible using `prettier`?

Thanks!

**Comment by hawkrives** [comment]
I think that [option 4 on the Prettier CLI docs](https://prettier.io/docs/en/precommit.html#option-4-bash-script) is what you're looking for?

But, I guess I'm wondering why, if `pretty-quick` does what you want, why not use it?

**Comment by azz** [comment]
I don't think we should add version-control-specific code to `prettier` (that's why I made [`pretty-quick`](https://github.com/azz/pretty-quick) in the first place). I have the same question as @hawkrives, is there an issue preventing you from using `pretty-quick`?
