### ISSUE TITLE
Support for script tags in .html files

### ISSUE THREAD

**Issue by web-padawan** [prettier/prettier#3767]
As suggested per [#2097(comment)]( https://github.com/prettier/prettier/issues/2097#issuecomment-358940631), I'm creating this issue just to separate support for `<script>` tags in `.html` files, apart from the `.vue` which is kinda already supported.

List of projects using Polymer can be found [here](https://github.com/abdonrd/PolymerProjects) (to be aligned with the Vue issue and just in case if someone is interested in why this matters 😄 ).

**Comment by matthewp** [comment]
Can we change the title to "HTML"? There's nothing Polymer specific here.

**Comment by azz** [comment]
There's already an issue for HTML: #1882

**Comment by web-padawan** [comment]
Does it make sense to keep separate issues for the HTML itself and the JS inside of the `<script>` tags? If not, feel free to close in favor of #1882

**Comment by j-f1** [comment]
I think we should have separate issues since HTML support has been a long time coming, but formatting the JS/CSS should be something we can do separately, while printing the HTML itself separately.

**Comment by web-padawan** [comment]
Since the latest Polymer 3.0 is using ES modules, I have renamed the issue. We are still interested in having this feature, as most of the products are likely to use earlier versions for a while.

**Comment by evilebottnawi** [comment]
@web-padawan can you update issue, what you have and what you expected?

**Comment by matthewp** [comment]
@evilebottnawi as someone else interested in this issue, I would like to be able to prettify the JavaScript in something like this:

```html
<!doctype html>
<html lang="en">
<title>Some demo</title>

<script type="module">
  import lib from './lib.js';

  function myFunction() { return 'foo'; }
</script>
```

**Comment by evilebottnawi** [comment]
@matthewp PR welcome https://github.com/prettier/prettier/issues/1882
