### ISSUE TITLE
Make evilebottnawi a collaborator

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#3773]
@evilebottnawi has shown interest in maintaining the CSS/SCSS part of prettier, and has submitted a lot of good Pull Requests contributing to that part of prettier already.

cc @vjeux @jlongster who I think are the only two who can grant write access to the project?

**Comment by vjeux** [comment]
Welcome to the team @evilebottnawi!

**Comment by duailibe** [comment]
Congrats @evilebottnawi and welcome!

**Comment by existentialism** [comment]
👏

**Comment by azz** [comment]
:star:

**Comment by evilebottnawi** [comment]
Thanks for everyone. :star: :star: :star:
