### ISSUE TITLE
Config file doesn't work!

### ISSUE THREAD

**Issue by pagner** [prettier/prettier#3778]
Am I missing something? I created a simple .prettierrc file and placed it everywhere in the project, including right next to the file I'm trying to format. Restart VSCode, Doesn't do a thing!

`{
  "printWidth": 500
}`

> The configuration file will be resolved starting from the location of the file being formatted, and searching up the file tree until a config file is (or isn't) found.

> A .prettierrc file, written in YAML or JSON, with optional extensions: .yaml/.yml/.json/.js.
A prettier.config.js file that exports an object.
A "prettier" key in your package.json file.

Am I reading that correctly? I hope that's on startup? Does this parse my node_modules folder too? Where does it stop?

Why not place a config file in one place and be done with it? Or at least have one extension it looks for. I don't see the value of parsing my entire project including every single .yaml/.yml/.json/.js. file. Objects, JSON.

It's just a config file! Make it JSON in 1 file that works and be done with it!

**Comment by pagner** [comment]
Not really. I have a huge Angular5 project I was trying to get this to work in with a plethora of configuration files. Again, I am just shocked at how the configuration file is "found"! Unless I'm mistaken, this program loops through files and folders looking to parse json or js objects that meet the format. Is it safe to say that's how it works?

**Comment by azz** [comment]
No, it only looks for files called `.prettierrc`, `.prettierrc.json`, and a few others. 

You can use `prettier --find-config-path path/to/file.js` to determine if the correct file is located.

**Comment by pagner** [comment]
Okay, thanks. I tried the first format .prettierrc with no luck. I'm using the VSCode extension, so maybe there is a problem there. Even though; it appears from the documentation that it bubbles up the hierarchy looking for said file. Does this include the node_modules folder? If so, maybe I just didn't wait long enough =)~

**Comment by azz** [comment]
How are you determining that the config file is not found?

**Comment by pagner** [comment]
printWidth is still wrapping my lines on elements. If I remove all the attributes and get the line below 80 characters it doesn't wrap. I end up with formatting that looks like this and it's not what I want.
`<element attribute="blah" attribute2="blah" ...
/>`

**Comment by azz** [comment]
Are you formatting a HTML file? Prettier doesn't support HTML at all.

**Comment by pagner** [comment]
html string representations in my typescript files. Probably still considered html.

**Comment by azz** [comment]
So it is a JS string? Prettier doesn't wrap those. 

Please try and reproduce this on [the playground](
https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEGBOBLKAc0wF5MADAQ2pss1pvobuZeaYYpABoQIAHGHnTJQlHDggB3AAriEaZCEoA3CHgAmPZRmQAzSgBs0cXgCMclMAGs4MAMr8rBQshg4ArqZAaIYfUYmvAQmODAyloQAtpQBxt4AVmgAHgBCljZ29pRRcAAyBHBxQXweMPxlAEzF3k44oUpmlGYAnobQ2vz4sADqmjAAFsgArAAMvF0QJj2W-EpdcKEqRbw4cACOHnhrEZTRsUgG8bwmUXhunt5oLoZwAIoeEPA1vDDNfRqDyJWvlniGLgAwhAojElFBoCsQB4TAAVZqKQ6BOAAXxRQA)
