### ISSUE TITLE
Writing your own parser *help wanted*

### ISSUE THREAD

**Issue by thorbenvh8** [prettier/prettier#3781]
Hi,
tldr;
I need help writing my own parser in javascript, any links etc you can provide? :)

---- 
I'm working currently on the prettier-java plugin.

It's going pretty good getting more and more features included. But sometimes the generated parser from a grammer via pegjs, is super slow and nearly impossible to debug.

That's why I want to write my own parser. I already have a lot of test cases so I can do this step by step.

Thanks for any help :)

**Comment by azz** [comment]
It could be a large undertaking, but here's some js parsers which are popular:

https://github.com/acornjs/acorn/tree/master/src
https://github.com/babel/babel/tree/master/packages/babylon/src
https://github.com/jquery/esprima/tree/master/src

**Comment by thorbenvh8** [comment]
Well if I don't do this, the parser takes more than 30 seconds to parse and nobody will use the prettier-java plugin

**Comment by thorbenvh8** [comment]
Which one of those three is the fastest?

**Comment by suchipi** [comment]
@thorbenvh8 those parsers parse JavaScript, not Java. You won't be able to use them to parse Java code. You might be able to get better speed by shelling out to a non-js parser. A google search suggests https://github.com/javaparser/javaparser.

**Comment by thorbenvh8** [comment]
Using it like this? Using a python parser written in python to get the ast and do rest in prettier?
https://github.com/prettier/prettier-python/blob/22f4b3f32c9d64519a06cc498e617895004e1af2/src/parser.js#L7-L13
Will this still work inside the plugins for visual studio code etc?

**Comment by suchipi** [comment]
I don't know exactly what the tradeoffs are. I think the approach made in prettier-python assumes that `python` is in the `PATH` when it gets run, and works as long as that is true.

**Comment by lydell** [comment]
Sounds like the questions have been answered here and this is not actionable so I’m closing :)
