### ISSUE TITLE
Incorrect formatting of `typeof`

### ISSUE THREAD

**Issue by TryingToImprove** [prettier/prettier#3782]
When calling `.toString` on a `typeof` it will remove the `()` making the object always a string

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXm2AF8BuAHVgE8AHOCAMwAp0BKAOhggGUYBLKAHMmrSpQD047AFEAHnTDwAJkmwxa9Zm049+QkQXyEA5BABGAKziLjEqQEFFAV3QAbVerqNcO3pgHCrIYmAM4w-kLGIAA0IBA0-NAhyKA0ETAA6nxKMAAWyAAcAAyxMOhmWTn5SABMsSEBrnAAik4Q8MgMbiFwpZjofK4BAMIQALZj6MggUNBwMSBm-WAA1nAw3DToYAHI4U69IBYhsgBCy2sb6GNwADIC80hdrj2xW5g9mNNm5VSu0AsemM+HtMAdYk4egAVcrJJ7dQ4CT4wAAK-UEk06CNimDgAEcnHxcWj0BipvCXoc0hAehl+jRpmk4J9UPNYlhMBAAO4orAIOEgdCoCDZBZKCBgLGU9lhKWvOJOGA0RU1OVwYjEIA)

**Input:**
```jsx
var a = {};
typeof(a).toSting()

// Expected: typeof(a).toSting() === 'object'
// Actual: typeof a.toString() === 'string'
```

**Output:**
```jsx
var a = {};
typeof a.toSting();

// Expected: typeof(a).toSting() === 'object'
// Actual: typeof a.toString() === 'string'

```

**Comment by ikatyang** [comment]
The parenthesis did nothing there, the [`typeof`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) operator is not a function.

![image](https://user-images.githubusercontent.com/8341033/35212813-5a17f8a2-ff96-11e7-8a32-4ed1ca4dc5fd.png)

I guess what you probably want is `(typeof a).toString()`.

**Comment by lydell** [comment]
I guess `(typeof a).toUpperCase()` is a better example. Parentheses would be nice here to make things clearer.

**Comment by TryingToImprove** [comment]
Ups, always used `typeof (a)`.. You are right @ikatyang 

@lydell  it seems ot format correctly when using `(typeof a)`
