### ISSUE TITLE
Format range produces additional whitespace for method of exported class

### ISSUE THREAD

**Issue by undeadcat** [prettier/prettier#3789]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAMT2AB0o89s4AzHAW2JgBUALAS1IAKAJQ16jRsxgBXbAwCMAbgl4AvvVUATaDwgywvPoNF0Gk6XIYAmSXhXmNUJ-RAAaEBAwx+0UslBibGwIAHcABSCEfxRiADcIfi13EAAjbGIwAGs4GABlDEz+KABzZBhsGTgPYtI4XHCMks5kFmJCOo8AK1I0ACEM7Ny84nY4ABliuFb2zpBC7DrsZDTiVIBPQmgUjGximAB1JJheZAAOAAYPXYg6g4yMFd24Jbjpj2YARxl+ZkbiZrEGYdaogOrsfjlSqg0jFEqEOAARRkEHgwLmMDWRy0J2Q1g8FWI-EIcIAwhB2C0UFBoO8QDI6tw1jE2iCPGQYOjQTowFyPPoYBgZDBrHyQBlSnA8pjcMgFAB2D7ESUAUSgySQAGZrGo1EA)
```sh
--range-end 32
--range-start 17
```

**Input:**
```jsx
export class F {
  reformatThis() {
    return 1;
  }

  dontTouchThis(){
    return 2    ;
  }
}


```

**Output:**
```jsx
export class F {
         reformatThis() {
           return 1;
         }

         dontTouchThis() {
           return 2;
         }
       }


```

Same result with `--range-start 17 --range-end 18`

Expected behavior would be to reformat only the first method and not produce additional  whitespace that is not present using full-file reformat.

Reproducible with prettier 1.10.2, also with prettier-vscode if only first method is selected in editor.
Not reproducible if 'export' is removed.

**Comment by JamesHenry** [comment]
@josephfrazier @azz We just hit something in this area too via some internal usage of `precise-commits`.

It may not be exactly the same issue, but I will keep things here for now.

In our case the minimal reproduction was this:

**initial.ts**
```ts
export class Rule {
  constructor(
    options: IOptions,
  ) {}
}
```

**staged.ts** (some extra whitespace between options and type annotation)
```ts
export class Rule {
  constructor(
    options:    IOptions,
  ) {}
}
```

`precise-commits` therefore identifies the range data for the affected line as:

```
{
  "rangeEnd": 60,
  "rangeStart": 34,
}
```

(Hacky proof that it is the right subsection of the code)
![screen shot 2018-02-15 at 22 39 04](https://user-images.githubusercontent.com/900523/36315878-b1d074f4-1330-11e8-8f3a-da6f4441d627.png)

Running prettier on the whole file gives:

```ts
export class Rule {
  constructor(options: IOptions) {}
}
```

Running prettier with `--range-start=34 --range-end=60` gives:

```ts
export class Rule {
         constructor(options: IOptions) {}
       }
```

**Comment by thorn0** [comment]
Closing in favor of #4926
