### ISSUE TITLE
Ugly formatting for Angular unit tests

### ISSUE THREAD

**Issue by variadicintegrity** [prettier/prettier#3791]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwBU4BnGAITgBMAafAQzIE8ox8BffAMxwnT4A5AAFGUAOYBXADaMcAekg44C+BVSShAbgA6UDNjyF8AQUyYAwgOxQEBbnwHCAdAsYWXkLNHs79+jTkYDioAEZwABRC5lY2vrBCDJEAlPgAvAB8hPr4+BE8uHAAooxgABaRzGxgkakZ2cC5eSTkVLRe0Dyo0iqkGpIAshA0slFNUC0tQWByOIwwqNBkSPgA2rHWPnawALrNeZwpnVioMnBbtvZkqXqTXCkpd3moMNFk5RCyNPghcAtwfAwcqAjyYJJMVjsOppLI5e55SBQCi8VAADxgUhUGVaFGoNC8KgBlwSb028R2MCeB1+ywIYJx3QxWLgLiCYSkEmK53Q9hOV1gAElkTBxGA4M8WnA0Zg4GA3mDjjAINRiDgpMCWLdmkdqfdXpEAAYfL4yH7lRgAN1BZCBr3OwjBQkNDGq0PqcImUyRKKZmOx6Vx7QJf2JFPskXJ23seu9dKYFkZ6P9rPZnO5cF5sH5pOFFDFEpp0tl8qqnkWMHOSogxQAjlJGDJooMWPgAGKoHAo0ySWTyMwWISxh7Dg26EAm774FRQII4O2VwGaJj4coARiBjAk49dUNqHsaNJ9BD9LJx-WDhP+8BJlMjFlvMcleVPKjZcHg8ssFsk5G1CNpEVaVOc4fkDV9UzgDkuR5PkoAWVBrQzLMYGffBizlN5vEwM4OnrOAcBYABlOBznlXBonXIcXHgDFrFgGMaIgejRU0ZtWw7LsCB7aQ5gHcFh11O4jjuEA6BACBMEWZZkFATBQlgAB1VAaGBZAAA4AAZxNFMJlNU8pkAAJnEshNAkc4AEUpAgeBkB4RsyDgHT5jOcytnQRhkBAKBfDEkAwnmMAAGsPyIzAynM5AYHVZyQAAKzINFKCC0KYCIxheQAGU0OB7McuKIq7AjvLCRgwhYGRoH8pz0FQaLYvEqQnOIcqyHymQnPEzQnLwAAFeYJE8jqupAFR607OABq3YakAczrCv4JzFPmTBvPk8gCOtfz5H4AB3Pr5AQdqUH8mgIDAEa4uYGArvEr4YEwDUjKuzhOCAA)
```sh
--arrow-parens 
```

**Input:**
```jsx
import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [AppComponent]
    }).compileComponents();
  }));
  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));
  it(`should have as title 'app'`, async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('My First Angular App');
  }));
  it("should render title in a h1 tag", async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain('My First Angular App');
  }));
});

```

**Output:**
```jsx
import { TestBed, async } from "@angular/core/testing";
import { AppComponent } from "./app.component";

describe("AppComponent", () => {
  beforeEach(
    async(() => {
      TestBed.configureTestingModule({
        declarations: [AppComponent]
      }).compileComponents();
    })
  );
  it(
    "should create the app",
    async(() => {
      const fixture = TestBed.createComponent(AppComponent);
      const app = fixture.debugElement.componentInstance;
      expect(app).toBeTruthy();
    })
  );
  it(
    `should have as title 'app'`,
    async(() => {
      const fixture = TestBed.createComponent(AppComponent);
      const app = fixture.debugElement.componentInstance;
      expect(app.title).toEqual("My First Angular App");
    })
  );
  it(
    "should render title in a h1 tag",
    async(() => {
      const fixture = TestBed.createComponent(AppComponent);
      fixture.detectChanges();
      const compiled = fixture.debugElement.nativeElement;
      expect(compiled.querySelector("h1").textContent).toContain(
        "My First Angular App"
      );
    })
  );
});

```

**Expected behavior:**
I would expect functions wrapped in Angular's async wrapper to be formatted the same way that native async arrow functions are in unit tests.

In this case, the test names and body should be on one line.

**Comment by ad1992** [comment]
@duailibe can I take this up ?

**Comment by duailibe** [comment]
@ad1992 Yes! Please, go ahead! :-)

**Comment by ad1992** [comment]
@duailibe I have made some change for fixing this issue but I don't think its a good fix. This is the first issue I have taken up in prettier. Can you please look into this commit https://github.com/ad1992/prettier/commit/5807ce2193a71006fc2ac762f5ebb85f9dcd1d9f  and guide me how can I make it better ?

**Comment by j-f1** [comment]
@ad1992 Why not open a PR so that we can more easily review and test it?
