### ISSUE TITLE
"jsxBracketSameLine: false" doesn't work correctly if prop value spans across multiple lines

### ISSUE THREAD

**Issue by szimek** [prettier/prettier#3803]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UABEQHTmGoD0WeA3IZQIa7mnUsNSNQY5EBnAK4AHOACcAMtADmABSbimAWwC8+EACNFGokygQYACwkBlUROlR5ileq1MAXroCecGAEEDxsxamyFJTUNbWcQAl4aHFwuShEmYyJ0ewBZABZSAHYANgBWIgBGbNIADgAmAE4AGwBmUgAGbIqAWjLSCrTsolzSgprurLSSwhJRsYKC0hqa5onSMpqyojr6xuXSApLZjJqugoz6kvqwokIqGJAAGhAIERhMaAFkUBFxTFgAdUx0Y2Qj65gTE0Xx+RmQZWuAneMiqcAAikJDHBkAAzJhVARwAFKTBVaEAYQgymUTGQIAMUGR100SjAAGt3KZ4mBocgYOIhFiQAArAQADwAQrSGTBTCo4JJ3sikGiMVz4uJMeIydpNC4qtAriBMcpMGyOVyhJiACpAp4y9GY67vJUwORKGQk1GWrniOAARyEmDd9qYjtJFrl11eEExHyUIjJrzgSuwVJAinEEAA7oEEOaE9gIN8tegIGBnUGEwIYIWrTchDARJWymW4ABfetAA)

**Input:**
```jsx
<div>
  ...
</div>;

<a>...</a>;


<div superLongParam="bar" anotherSuperLongParam="baz" yetAnotherSuperLongParam="baz">
</div>;

<path d="M4.765 16.829l3.069-2.946 5.813 5.748
  11.33-11.232 3.006 3.18-14.36 14.080z" 
/>;
```

**Output:**
```jsx
<div>...</div>;

<a>...</a>;

<div
  superLongParam="bar"
  anotherSuperLongParam="baz"
  yetAnotherSuperLongParam="baz"
/>;

<path d="M4.765 16.829l3.069-2.946 5.813 5.748
  11.33-11.232 3.006 3.18-14.36 14.080z" />;
```

**Expected behavior:**
```jsx
<div>...</div>;

<a>...</a>;

<div
  superLongParam="bar"
  anotherSuperLongParam="baz"
  yetAnotherSuperLongParam="baz"
/>;

<path d="M4.765 16.829l3.069-2.946 5.813 5.748
  11.33-11.232 3.006 3.18-14.36 14.080z"
/>
```

`jsxBracketSameLine: false` option handles most cases correctly, but I'd expect the closing bracket in the last element (`path`) to be moved to a separate line. I'm using `eslint-config-airbnb` and its `'react/jsx-closing-bracket-location': ['error', 'line-aligned']` rule is violated after running this code through prettier.

**Comment by j-f1** [comment]
It looks like this could be fixed by always  breaking the parameter list if one of the string values has a newline in it.

**Comment by suchipi** [comment]
Huh, I didn't know newlines were valid in JSX attribute value strings, but sure enough, the spec allows them:

![](https://puu.sh/z8dh3/53d00e6291.png)

TIL
