### ISSUE TITLE
--single-quote not working inside an escaped error message string

### ISSUE THREAD

**Issue by jeremenichelli** [prettier/prettier#3804]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBnCBbDACwEsoBzTAXkwDMBDVbOAbgB0p3ibMAKXAmCXJVK1GACcArnACUmYO0yZB4iAHceAcn5xMcbGDoAHOABMcE0hWLYOrTVjURxAayuY1cVKk0z2AXxAAGhAIIxhiaGxkUDpxVTUABTiEaJRgkDpsGGR6RjgQgCNxOjAXDABlI1KrZAlpENMIMFyGJhDSJnEYRJKyPDpW-JCAK2wADwAhErLKugIAGVI4IfbQyRgjDYAmVYKQavEu5BBCukKAT1RoDKNxUhgAdWJTQWQADgAGELuIJkeSkYThlxHAAI6SYig3p0fqDJB5NZMPDEOpSfbYKzoACKkgg8DRDRAMHOz1ehGQ2xCEjoxFQVgAwvgBicoNAViFJEwACrnNKIuD+fxAA)
```sh
--arrow-parens 
--prose-wrap 
--single-quote
```

**Input:**
```jsx
let something = false;

if (something === true) {
  throw('some escaped string isn\'t working well')
}
```

**Output:**
```jsx
let something = false;

if (something === true) {
  throw "some escaped string isn't working well";
}

```

**Expected behavior:** This might be an expected behavior since I'm new at Prettier, but if single quotes option is enable, shouldn't that be respected and keep the escaped single quoted string when reporting this error? Or is this an exception for the option?

**Comment by j-f1** [comment]
Prettier has two goals when printing strings, in order of priority:

1. Minimize the number escaped quotes in the string
2. Respect the `--single-quote` option

Changing single quotes to double quotes and vice versa is less of a readability cost than having to ignore lots of `\` characters in the string.

**Comment by jeremenichelli** [comment]
Good to know, thanks for taking the time to explain it Jed 😊

**Comment by j-f1** [comment]
If using single quotes at all times is important to you, we recommend using [`prettier-eslint`](https://github.com/prettier/prettier-eslint) which runs your code through ESLint after it gets formatted by Prettier, which will allow you to enforce patterns that Prettier doesn’t have an option for.

**Comment by mboughaba** [comment]
Hi @j-f1 

> We’ve decided that changing single quotes to double quotes and vice versa is less of a readability cost than having to ignore lots of \ characters in the string.

Wouldn't be better to make this decision configurable by the user? 
We can still have sensible default where we respect the priority you mentioned, but as well give the users possibility to keep their quote of choice even if the string contains an escaped one.

### Why it is important?
using tslint we can enforce the quote of choice
```json   
"quotemark": [
  true,
  "single"
],
```
using prettier we can enforce the quote of choice 
```json   
  "singleQuote": true,
],
```
The if you run both prettier then linter on your pre commit hook you are basically stuck 😕 

Thanks for you feedback.

**Comment by lydell** [comment]
> Wouldn't be better to make this decision configurable by the user?

No, not according to the philosophy of the project. https://prettier.io/docs/en/option-philosophy.html

> Why it is important? ... tslint

We recommend turning off all tslint and eslint rules that conflict with Prettier. See [tslint-config-prettier](https://github.com/alexjoverm/tslint-config-prettier) [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

**Comment by mboughaba** [comment]
I like this philosophy don't get me wrong. What I found odd is that even with config `"singleQuote": true` prettier will double the quotes in some cases. Maybe the issue is that config shouldn't be there in the first place?.
