### ISSUE TITLE
Option for Eslint Brace Style？

### ISSUE THREAD

**Issue by 599316527** [prettier/prettier#3807]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBTohASk2EwCMBDAJ2wIG5MBfTOAGwGc5izyAvG+hgB1YlAJ5c2EALZwYAC1RQA5gCVUbANaj+jTGHIwwc7HCIk55KABMWcAKKVKEanUYgANCAgAHGKmhsyKBUTgDuAApUCIEo5ABuEKhWHiDkbDDI6OTscJ6klORgGrIAyt6FikrIMJQArrkgVhBgmdkcnooclDDhBUpS5K05ngBWbAAeAEIFRaXkMgAyinBD7V61MN4bAEyrDeWUXcggFKSiLNAp3pSKMADqSfLIABwADJ7XEBx3Bd7H13AunEVp5KHAAI61VBg3rkfqDJBZYYgDhSVDVOoNNiVWwARVqEHge08MHIpAeVieSG2JIKqBYlQAwtIBscoNAQSBahwACpkmJIjgMBhAA)
```sh
# Options (if any):
```

**Input:**
```js
if (foo) { bar(); } else { baz(); }
try { somethingRisky(); } catch(e) { handleError(); }
```

**Output:**
```js
if (foo) {
  bar();
} else {
  baz();
}
try {
  somethingRisky();
} catch (e) {
  handleError();
}

```

**Expected behavior:**

https://eslint.org/docs/rules/brace-style .

There shall be an option which provides a choice to format codes into the following style.

```js
if (foo) {
  bar();
} 
else {
  baz();
}
try {
  somethingRisky();
} 
catch (e) {
  handleError();
}
```

**Comment by j-f1** [comment]
Hi! Thanks for bringing this up. Unfortunately, we [generally don’t add configuration options](https://github.com/prettier/prettier/issues/40), and instead encourage you to use [`prettier-eslint`](https://github.com/prettier/prettier-eslint-cli), a tool that runs your code through an ESLint config of your choice after running Prettier, enabling you to choose and enforce your own style guide while still taking advantage of Prettier’s features.
