### ISSUE TITLE
Multiple passes sometimes produces different results

### ISSUE THREAD

**Issue by ForbesLindesay** [prettier/prettier#3823]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEYATnAIbwAqAFjlAOYAUAlEvtbXQDwPAA6IAGWh0ACkQgAHOERgBPAHKkAtnH6so6JQCNpAGnz8ta-AGcYRDvv5hjG7dIC+TAHz4+UByF0hJuaCeRQUiJxAHcRYIQAlFIANwgcABMvEFIzZFRSABsTOG8tIlIwAGs4GABlCSKOZHN0PJBEiDAM7NzvWlyZMVI6JVJWnIaAKxMADwAhQpKy8uU4AVo4QfafdBgJdYAmWqJ67yqiLuQQOSkTYhwJGBSJC1gAdSSYKmQADgAGA-Fch8KJE53OBdWLLbwkACO6BwJB6fQGSEyQ28uSUOF2+xAJg4WTgAEV0BB4CsGjBSFonokXsgtt5zKQcFkOABhCBKfonKDQMEgdC5Cjk6JI3IOBxAA)
```sh
--parser typescript
```

**Input:**
```tsx
function createThing(): Thing<({"LongPropertyName": number, "b": string, "c": number})> {
}
```

**Output:**
```tsx
function createThing(): Thing<
  { LongPropertyName: number; b: string; c: number }
> {}

```

**Second Output:**
```tsx
function createThing(): Thing<{
  LongPropertyName: number;
  b: string;
  c: number;
}> {}

```

**Comment by j-f1** [comment]
This [works fine if you remove the parens](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEYATnAIbwAqAFjlAOYAUAlEvtbXQDzAA6IAMtDoAFIhAAOcIjACeAOVIBbOH1ZR0igEZSANPj6bV+AM4wiHPXzBH1WqQF8AfPl5R7IHSAm5ox5KFIiMQB3YUCEPxRSADcIHAATDxBSU2RUUgAbYzhPTSJSMABrOBgAZXECjmQzdByQeIgwNMzsz1ps6VFSOkVSZqy6gCtjAA8AIXyiktKlOH5aOH7Wr3QYcVWAJmqiWs8Kog7kEFlJY2IccRgk8XNYAHUEmCpkAA4ABj2xbLv88SObuAdaKLTwkACO6BwJC6PT6SHSA082UUOG2uxAxg4GTgAEV0BB4Es6jBSJoHvEnsgNp4zKQcBkOABhCCKXpHKDQEEgdDZCikyII7L2exAA), and [it works fine when parsed as Flow](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEYATnAIbwAqAFjlAOYAUAlEvtbXQDwPAA6IAGWh0ACkQgAHOERgBPAHKkAtnH6so6JQCNpAGnz8ta-AGcYRDvv5hjG7dIC+TAHz4+UByF0hJuaCeRQUiJxAHcRYIQAlFIANwgcABMvEFIzZFRSABsTOG8tIlIwAGs4GABlCSKOZHN0PJBEiDAM7NzvWlyZMVI6JVJWnIaAKxMADwAhQpKy8uU4AVo4QfafdBgJdYAmWqJ67yqiLuQQLVItWSzoFIkLWAB1JJgqZAAOAAYD8Vz7wokT25wLqxZbeEgAR3QOBIPT6AyQmSG3lyShwu32IBMHCycAAiugIPAVg0YOdHolnsgtt5zKQcFkOABhCBKfonKDQUEgdC5CjnaKI3IOBxAA).

**Comment by ForbesLindesay** [comment]
The code is auto-generated, so I can't remove the parens, and the real example contains some code that is typescript so it cannot be parsed as flow. I don't think there should be any situations in which prettier outputs different code on a second pass as this breaks the workflow of using pre-commit hooks to prettier and `--list-different` in CI to check that has been done.

**Comment by j-f1** [comment]
I’m not suggesting switching over to Flow for this :)

I was just doing a couple of checks to narrow down the bug.

**Comment by josephfrazier** [comment]
(for reference, this is a specific instance of https://github.com/prettier/prettier/issues/2803, and could be fixed by https://github.com/prettier/prettier/issues/2068)

**Comment by j-f1** [comment]
@josephfrazier It’s not that simple — the parens are actually part of the AST.

**Comment by ForbesLindesay** [comment]
I have a very simple workaround, but it's not exactly pretty: https://github.com/bicyclejs/ts-bicycle/blob/master/src/formatResult.ts#L9-L18

**Comment by josephfrazier** [comment]
> @josephfrazier It’s not that simple — the parens are actually part of the AST.

Thanks for clarifying, @j-f1. I had glossed over the details about the parentheses, and only noticed the idempotency issue.

**Comment by duailibe** [comment]
So there are two bugs here.. one is the same as #2803 and the other a high priority bug since we're changing the AST.

@ForbesLindesay I'll update this issue to only the parenthesis being removed, the idempotency is tracked on #2803. Let me know if you think this is not right

**Comment by azz** [comment]
I'm confused. Why is removing the parens here an issue?

**Comment by ForbesLindesay** [comment]
The parentheses don’t have any semantic value here. It’s correct that they are being removed, but once removed they shouldn’t have any effect on the way the ast gets printed.

**Comment by duailibe** [comment]
My bad.. in that case the issue here is the same as #2803, i.e., on the first time we have no way of knowing that object will break when building the docs and for the second output, when we already have breaks in the docs, we format it differently.
