### ISSUE TITLE
TypeScript: Unstable case with ParenthesizedType UnionType

### ISSUE THREAD

**Issue by JHilker** [prettier/prettier#3831]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwDMII8BePAQW2wENCAeACgB0o88AfPMG69eAfVFESUJgFs4SPJxAAhJgC8lAGmF4AvjoFCeI8ZISz5ilQFc1GkNuP6oASgB83ByAgYYAS2gAZ2RQJkYIAHcABTCEYJQmADcIPwATLyZAmGQyJgAbQLhNEAAjZjAAazgYAGUMJjA-KABzZBhsayKQVIgwHPzC4qbC3CjmZpkmfoKugCtAtGVyqtqLABkmuGnB72sYDD2AJm2u+uwR5BAzQLBsP18vDDvYAHU0mAALZAAOAAZip4QQovZgYS5POAjRJbYrYOAAR2sfjhYyYEymSFyM2KhRkfjaHS6gSazTycAAitYIPATsUYEwSm9Up9kIc6cw-HkSQBhCAySaXKDQGEgayFAAqDPiWMKul0QA)
```sh
--parser typescript
```

**Input:**
```tsx
export type foo = Array<(
  | {
    __typename: "Baz",
  }
  | {
    __typename: "Buzz",
  }
)>

```

**Output:**
```tsx
export type foo = Array<

    | {
        __typename: "Baz";
      }
    | {
        __typename: "Buzz";
      }
>;

```

**Expected behavior:**
If you run the result through prettier again, you get the stable result of:
```tsx
export type foo = Array<
  | {
      __typename: "Baz";
    }
  | {
      __typename: "Buzz";
    }
>;
```

[ASTExplorer](https://astexplorer.net/#/gist/f53bd5cfed45137b5e495daa13379746/6666eca993bb8479142af1b67baeeb2c4bb4b2e5)

**Comment by azz** [comment]
This is _almost_ identical to #1434. I suspect it is the original parens causing this issue.

**Comment by azz** [comment]
Confirmed, the `TSParenthesizedType` is the cause.

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwDMII8BePAQW2wENCAeAHSjzwB89hO3bgH1hRElCYBbOEjzsQAISYAvBQBpBeAL5a+ArkNHiE02fKUBXFWpCbDuqAD5OdkBAwwAltADOyUCZGCAB3AAUghH8UJgA3CC8AEzcmXxhkMiYAG184dRAAI2YwAGs4GABlDCYwLygAc2QYbEs8kESIMAzs3Py63Nww5nqpJm6ctoArXzRFYrLKswAZOrhx3vdLGAwtgCYmlrbq7AHkEBNfMGwvTzcMa9gAdSSYAAtkAA4ABnz7iFzHswMGd7nABrE1vlsHAAI6WLzQoZMEZjJCZCb5XJSLwHVqYur1LJwACKlgg8HWbRgTAKz0Sb2Qu3yzSYXiyBIAwhApKMzlBoJCQJZcgAVGnRdG5bTaIA)
```sh
--parser typescript
```

**Input:**
```tsx
export type foo = Array<
  | {
    __typename: "Baz",
  }
  | {
    __typename: "Buzz",
  }
>

```

**Output:**
```tsx
export type foo = Array<
  | {
      __typename: "Baz";
    }
  | {
      __typename: "Buzz";
    }
>;

```

**Comment by jpbufe3** [comment]
any progress on this? also running into this bug
