### ISSUE TITLE
Flow doesn't seem to be working

### ISSUE THREAD

**Issue by anthonybrown** [prettier/prettier#3833]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEsZF6AVgQAeAISmz5CkrbgAGVU4R1NMbRgsSIAmML1lMgtkEH4hai4sMlUYAHUOGAALZAAOAAYMLIhRXKksFKy4C2ZQjDI4AEdtXHbrEjsHJEEnDFFbXE0dPQJVNSE4AEVtCHh4jBgScXz2IuQY9alcIVmAYQhbexSoaFaQbVEAFU3GYdEAXzegA)
```sh
--parser flow
```

**Input:**
```jsx

```

**Output:**
```jsx

```

**Expected behavior:**

**Comment by anthonybrown** [comment]
Sorry if I didn't format this correctly, when trying out prettier, I was switching through the options. TypeScript worked but when I tried `Flow` there was nothing on the screen. I figured it was supposed to be pre-populated like the other examples?

**Comment by lydell** [comment]
Yes, it feels pretty confusing when you end up with an empty text area – it looks a bit broken. The thing is that we simply don't have a Flow example yet. Feel free to submit one! See #3667.
