### ISSUE TITLE
Prettier removes the new "definite assignment assertion" in TypeScript 2.7

### ISSUE THREAD

**Issue by pelotom** [prettier/prettier#3852]
[A new feature in TypeScript 2.7](https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/) is the "definite assignment assertion", which can either be on a variable:

```ts
let foo!: number;
```

or a class member:

```ts
class Foo {
  foo!: number;
}
```

In both cases currently, Prettier is removing the `!` when it formats.

**Comment by j-f1** [comment]
Duplicate of #3561
