### ISSUE TITLE
Weird indentation when wrapping an expression in function parens

### ISSUE THREAD

**Issue by manuelbieh** [prettier/prettier#3865]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFci5sBhAQygGUaA3OPAXgOzhvnrgBs4YGDgAUAHSh5peANoBzODACiAEwCWI7ADF1A1QDkaAWzgAaPIpi79AcTgQAUkWgWrfQcLirtNbMYBJVQBdM0kZPFEAMz1+QxNzPBi7B2dXJL9A1QBKdgA+PGBwiJkuGFJsKQAhCAhBOgkpEuaozKC8ADIO4uaI5Lj7JxcoADoo7nKuIk7upt6ZAEFsbBoATxH1IiWV1ejY1UG00fGeCrgiXK6e+aT9w+GxibOiWQAGYJnr+f6D1IeTybnN7BEaKCCmGDYdaQHAaKA8c6fOY3H73aCPU5TYGghwQqEjGHYOEIogjQRQeQwAAWSJuMh+RlMtLpt30jLgZIQlKpXxk2QA3NcAL6SAUgMwgCAYGDqaBEZCgPzYCAAdwACn4EPKUMwIOpVOKQDQSMhWvwKBKAEYrMAAayU9AwNDA6gpyEhpHMIFUEDAppo5q9roouDVK3kxho-sDEoAVkQ0FUbfaYIxTAAZV1waMWyWkGAYfMAJhzXqd2BDyBAlpoltW-Gghow2FdMAA6vrqcgAByvCXNiAUNsrDBV5vnSgsQ1cACOpHUXDDNAjUaQZtzFGM6nd2E9EqIrvkggAiqQIPBSxKYLWO6ou0gi1eVup+IeqODI1WoNBsxLyHAABVa21dc4CFIUgA)
[Playground link 2](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFci5sBhAQygGUaA3OPAXgOzhvnrgBs4YGDgAUAHSh5peANoBzODACiAEwCWI7ADF1A1QDkaAWzgAaPIpi79AcTgQAUkWgWrfQcLirtNbMYBJVQBdM0kZPFEAMz1+QxNzPBi7B2dXJL9A1QBKdgA+PGBwiJkuGFJsKQkpEtqozKC8ADIm4tqI5Lj7JxcoADoo7nKuImbWmvaZAEFsbBoATz71Ihm5+ejY1W60-sGeCrgiXJa2yaTN7d6BoYOiWQAGYLHTyc6t1Ku94cOH4L7FCCmGDYRaQHAaKA8Q7PCZnN6XaDXfYjX7-BxAkF9MHYCFQoh9QRQeQwAAWMLOMjeRlM5Ip5301LgBIQxJJLxk2QA3KcAL6SLkgMwgCAYGDqaBEZCgPzYCAAdwACn4EJKUMwIOpVIKQDQSMh6vwKEKAEZzMAAayU9AwNDA6iJyGBpHMIFUEDA+pohpd9oouAVc3kxhonu9QoAVkQ0AAhM2WmCMUwAGXtcFDRuFpBgGCzACZ0y6bdg-cgQMaaMb5vxoNqMNh7TAAOqa0nIAAc9yFdYgFEbcwwpbrh0oLG1XAAjqR1FwAzQgyGkAaMxRjOpHdhnUKiPb5IIAIqkCDwAtCmAV5uqVtIXOnubqfg7qiA4OlqDQNNC8hwAAqFdVS7gHkeSAA)

**Input:**
See playground links

**Output:**
See playground links

**Expected behavior:**
I'd expect to have all the checks within `Boolean()` (Playground link 1) on the same indentation level as they are when they're not inside of `Boolean()` (Playground link 2). Using implicit coercion `!!()` instead of `Boolean()` also results in a "correct" indentation.

**Comment by j-f1** [comment]
Minimal repro:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAlAAgLwD5MA6UmmAZhBKkSSQIYDOAJqQ86y0x85gGQ-U12QzsLYjxYyaV79igiV0XsB6IiAA0ICAAcYAS2j1koWgCdTEAO4AFMwiMpaANwh7GGkAxjIWAG3pwmgBGprRgANZwMADK2mF6UADmyDCmAK6BIIwQYD60-pkJAaYw1qGJALa0eQWaAFb0AB4AQqERUdG0FXAAMglwNQGaEGkw2qMATIOZcabFyCBBtEEAnr7QHtqmCTAA6m4wABbIABwADJpbEAG7odoLW3DFTgOapnAAjml672W0ldUkH4hiAAhU9Cl0pl6AlEr44ABFNIQeDTTQwZb7RhHZATdGhPS+WEAYQgFSqCyg0FeIDSAQAKssHMC4ABfVlAA)

**Input:**
```jsx
() => 
  foo(
    asdfasdfasdfasdfasdf &&
    asdfasdfasdfasdfasdfasdfasdfasdfasdfasdf &&
    asdfasdfasdfasdfasdf
  )

```

**Output:**
```jsx
() =>
  foo(
    asdfasdfasdfasdfasdf &&
      asdfasdfasdfasdfasdfasdfasdfasdfasdfasdf &&
      asdfasdfasdfasdfasdf
  );

```

**Comment by lydell** [comment]
Thanks for the issue! This has actually been discussed before: #2209. Feel free to give that issue a 👍 and leave a comment there!
