### ISSUE TITLE
The site with the documentation does not work

### ISSUE THREAD

**Issue by splincode** [prettier/prettier#3866]
![image](https://user-images.githubusercontent.com/12021443/35692606-dc3d9352-078c-11e8-8f09-bc4b5a256206.png)

**Comment by j-f1** [comment]
It looks like Netlify, our website host, [is having issues](https://netlifystatus.com/incidents/2018/02/01/elevated-errors-from-cdn-origin/).

**Comment by splincode** [comment]
Where can I find the API options in the repository?

**Comment by j-f1** [comment]
All of our docs are in the `docs/` directiory, and the [options docs are here](https://github.com/prettier/prettier/blob/master/docs/options.md).

Sorry about the outage. Hopefully, Netlify will fix the issues and have the website back soon!

**Comment by suchipi** [comment]
It looks like the site is back up, so I'll close this.
