### ISSUE TITLE
Invalid code with prettier-ignore for flow ? type

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#3878]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXm2AB0ptsB6S7DAJzhhgEs46BaZgcyggbIoBqZlAwBXGEmwB+ABTSAQgEoANGQC+ZECpAQMLaAGdkoAIZ06EAO4AFcwmMpTANwjMAJtpCnDMZADNTABtDOB0AIzpTMABrRgBlDGiRLmQYOjEwkHcIMADg0J0RULoYGyiuAFtTfJCsgCtDAA8FKNiE00q4ABkROFrC3QlxGAAmAaykuhLkEH8g6y96ERgAdQ8YAAtkAA4ABh16CFDVqIxZ+jgS536dBgBHMWYGctMqmqRAup1QyuY0jJZQwpIJwACKYgg8AmOhgpnC63cW2Qo1hUWYQRSAGEIJVqrNeFBbiAxKEACrwxxfULqdRAA)
```sh
--parser flow
```

**Input:**
```jsx
type A = {
  // prettier-ignore
  +input: ?(?B),
}
```

**Output:**
```jsx
type A = {
  // prettier-ignore
  +input: ?(?B
};
```

**Comment by vjeux** [comment]
This is an issue with the flow parser giving out incorrect location: https://github.com/facebook/flow/issues/5758

**Comment by suchipi** [comment]
Is `?(?B)` ever a useful construct?

**Comment by vjeux** [comment]
There's currently a bug in flow where `??T` is different than `?T`. It should mean the exact same thing.

**Comment by vjeux** [comment]
Also ??T parses on flow but not on babylon
