### ISSUE TITLE
Invalid printWidth value. Expected an integer, but received: "null"

### ISSUE THREAD

**Issue by deathmood** [prettier/prettier#3880]
**Prettier 1.10.2**
```sh
prettier --write "**/*.{js,css}"
```

**Output:**
![image](https://user-images.githubusercontent.com/2758540/35765663-5ea96740-08d1-11e8-9122-99cf1f4b8b4c.png)

![image](https://user-images.githubusercontent.com/2758540/35765671-9ed861b8-08d1-11e8-9078-0ad77d8ed03a.png)

![image](https://user-images.githubusercontent.com/2758540/35765675-a8742f68-08d1-11e8-9a7a-979f7ce13267.png)

**Expected behavior:**
prettier formats code without errors, automatically sets printWidth to 80 (as default according to this https://prettier.io/docs/en/options.html)

**Comment by ikatyang** [comment]
I cannot reproduce the issue, I guess there's a `.prettierrc` or `.editorconfig` in your cwd, can you share more info?

**Comment by AtrisMio** [comment]
I reproduce the situation of this issue, when I not set printWidth to `.prettierrc` use 1.10.2,

`.prettierrc`
```js
// Prettier configuration
// https://prettier.io/docs/en/configuration.html
module.exports = {
    singleQuote: true,
    trailingComma: 'all',
};
```

`.editorconfig`
```sh
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# http://editorconfig.org

root = true

[*]

# Change these settings to your own preference
indent_style = space
indent_size = 4

# We recommend you to keep these unchanged
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

# editorconfig-tools is unable to ignore longs strings or urls
max_line_length = null
```


when i set `printWidth` in `.prettierrc` Prettier run well.
there same to be some throuble at setting default config.

**Comment by ikatyang** [comment]
We treated `max_line_length` as `printWidth` ([ref](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options)), you probably want to:

- set `max_line_length = 80`
- or just disable it: [`--no-editorconfig`](https://prettier.io/docs/en/cli.html#no-editorconfig)

**Comment by AtrisMio** [comment]
thanks a lot
