### ISSUE TITLE
proposition: add flags or options to use famous presets like `standard`

### ISSUE THREAD

**Issue by le93us** [prettier/prettier#3882]
It will be convenient, if `js` community define unified formatting style like `gofmt` tool.

As I understand, `prettier` defaults are different to `standard` style.

Let's discuss it!

**Comment by j-f1** [comment]
You can use something like [`prettier-standard`](https://github.com/sheerun/prettier-standard) if you want to stick with Standard’s style, but do you have anything specific about Prettier’s style you don’t like?

**Comment by le93us** [comment]
@j-f1 by default `prettier` inserts semicolons, and, by example, `prettier-standard` is no-name brand tool.

**Comment by j-f1** [comment]
> by default `prettier` inserts semicolons

Just set `semi: false` or `--no-semi` to disable them.


> `prettier-standard` is no-name brand tool

Many people probably don’t know what Prettier or Standard are, either :)

**Comment by josephfrazier** [comment]
See also:

https://github.com/prettier/prettier/issues/3759
https://github.com/prettier/prettier/issues/1343
https://github.com/standard/standard/issues/996
https://github.com/standard/standard/issues/811

**Comment by suchipi** [comment]
I'm going to close this as it's not really actionable. Prettier is okay with its formatting being different from standard, as it's not as common as it might seem it is. However, tools like prettier-standard should work for you. If you find specific formatting from prettier that you dislike, please open or +1 an issue containing the code in question.
