### ISSUE TITLE
`trailingComma: 'all'` does not work when using rest operator in destructuring assignment

### ISSUE THREAD

**Issue by aquilae** [prettier/prettier#3883]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCGATgOYCU+wAOlIzJFCQ-gA6UTcBGADQ8+3AEwiAdDIgwAFnEoAFMUXwBffAF58VagG5mG5iCEh+uaEWSgqfAO7KqCGynIA3CDgAmZkOQkyDCU6HDmAEaU5GAA1nAwAMrcMThQ1MGh4SA+EGDIqOQANkTZaaWUMKrk1AC25AXFpeYAVkQAHgBC0XEJieS1cAAyaXCNJdkQ6DDc0+LjzSAplBXIIBHkEQCeRdD+vGkwAOq+CsgAzAAM5rwQpUfR3Gu8cBUeY+aUcACO6Dhf1TqDSQhQm5lKtRwmTC4LS1CKcAAiug5GMQU1sjBNicfGckJIQCFyDginCAMIQWr1NbFIr+dClAAqmzcoNKGg0QA)
```sh
--print-width 30
--trailing-comma all
```

**Input:**
```jsx
function test(arg) {
	const { prop1, prop2, ...otherProps } = arg;
}

```

**Output:**
```jsx
function test(arg) {
  const {
    prop1,
    prop2,
    ...otherProps
  } = arg;
}

```

**Expected behavior:**
Should add trailing comma to `...otherProps`.
Saw some discussion about it here, but the fact is it's definitely inconsistent as it is as removing the rest operator results in comma being there.

**Comment by j-f1** [comment]
This is intentional: https://github.com/tc39/proposal-object-rest-spread/issues/47. The trailing comma is forbidden after the rest property.

It was fixed in #3313.

**Comment by aquilae** [comment]
Isn't the whole point of `all` option is to add commas everywhere even if it's not supported by spec?
If that's not the case then the difference between `all` and `es5` seems pretty vague.
And what's the difference between this and function parameters comma which is, as I understand, forbidden as well?

**Comment by j-f1** [comment]
> Isn't the whole point of `all` option is to add commas everywhere even if it's not supported by spec?

No, because we strive to always output valid JS.

> If that's not the case then the difference between `all` and `es5` seems pretty vague.

`es5` outputs commas where they’re allowed by the (9-year-old) ECMAScript 5 spec, whereas `all` outputs commas where they’re allowed by the current spec, including in syntax proposals.

> And what's the difference between this and function parameters comma which is, as I understand, forbidden as well?

Not in the latest edition of ECMAScript.

**Comment by aquilae** [comment]
OK, I see, thanks for extensive answer.
Guess we'll have to tweak our lint config instead.
