### ISSUE TITLE
Suggestion: move `editorconfig` support back to `docs/configuration`

### ISSUE THREAD

**Issue by olsonpm** [prettier/prettier#3884]
I'm refactoring `prettier-atom` to use prettier for editorconfig options now that you guys support it.

I want to link to prettier documentation, but it currently sits under the [api docs](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options) and there's no direct header or id for me to clearly link to.  I see it was previously added to [`docs/configuration.md`](https://github.com/prettier/prettier/commit/8f58ca0f4802db62719ef6689bd5fb7c476c7afb#diff-76e731333fb756df3bff5ddb3b731c46) which imo is more fitting/discoverable, though I'm open to other solutions.

I will create a PR if this sounds good.

Thanks for this library - it's saved me tons of time 👍

**Comment by olsonpm** [comment]
Ah - looking for an alternative link I found the blog which provides the explanation for why it's no longer in configuration.  I'll link to that and sorry for the noise.

**Comment by pronebird** [comment]
@olsonpm you did not provide the link and prettier still has no reference that it supports `.editorconfig`

**Comment by olsonpm** [comment]
https://prettier.io/blog/2017/12/05/1.9.0.html#configuration

**Comment by pronebird** [comment]
Thank you! 👍
