### ISSUE TITLE
Comment in css (in markdown) identation keeps increasing 

### ISSUE THREAD

**Issue by ZeeCoder** [prettier/prettier#3889]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgEwDpVwA0IAcx11cA6AQQDdUZUAnAAmF2eYHoAqZi-5t0652zAGQB9CQEsAtqgDmcVqI48+AoSKgcOAAUixU0qHBYAKAO7TMMABbMAfMwCMABjdEAHgEoVO3TVuVV0AYTtUKCVmdAhZZXQYAE8AGzh0Zmhme2U5RWU4NPjYZks7BGzy5kMGEzNmaXIAwOtMevtI1w9vEI4tZuYAX1FhvACDaFrTCwwiODAYAFpGemkIJ2YAZj82AfVwyOjE1PTMnRzmVDoGFmkYdEKAMwAaUvLzqtn5pZWYNYaMgpfu0IjpNoJhAFRqIJkY6hZWvYNu5PL5LlBMMxzOVpAo7DBkd00btAup+BQISNcKNCPhcCBniAIEQ-tB0MhQExGBBLAAFJgIdkoK4QGwMtCJZCPVApB6MgBGKzAAGs4DAAMpEVBgEwKZAwRgAVzgjMwEDAUplcpAJgejBgvJWCnkltlJpAACt0F4AEJK1Ua1DxAAydVd1oghpgRCjACZw+6tYw7cgQPJGMqzZYoOKiIwTDAAOo2ezIAAcbkZeYgD0LKyIqbz6TMNDg4sYcAAjobpB3HYoXUhpW7GQ9ZNJ9Ub3ehdWkAIqGiDwBOMhjy4u2OzIWOrlbSFK60JxQcgKDQNuMw0PAAqqHlQuHD0GgyAA)
```sh
--parser markdown
```

**Input:**
````markdown
asd

```pcss
.Avatar {
  /* ... */

  &__image {
    /* ... */

    @container (width > 100px) {
      /*
      Change some styles on the image element when the container is
      wider than 100px
      */
    }
  }

  @container (aspect-ratio > 3) {
    /* Change styles on the avatar itself, when the aspect-ratio is grater than 3 */
  }

  @container (width > 100px) and (height > 100px) {
    /* ... */
  }
}
```

````

**Output:**
````markdown
asd

```pcss
.Avatar {
  /* ... */

  &__image {
    /* ... */

    @container (width > 100px) {
      /*
            Change some styles on the image element when the container is
            wider than 100px
            */
    }
  }

  @container (aspect-ratio > 3) {
    /* Change styles on the avatar itself, when the aspect-ratio is grater than 3 */
  }

  @container (width > 100px) and (height > 100px) {
    /* ... */
  }
}
```

````

**Expected behavior:**
Identation shouldn't keep increasing.

**Comment by j-f1** [comment]
**Third Output:**
````markdown
```css
a {
  /*
        */
}
```

````

**Fourth Output:**
````markdown
```css
a {
  /*
          */
}
```

````

**Comment by ZeeCoder** [comment]
yep, I noticed it after quite some time, so it was quite far to the right at that point. 😂
