### ISSUE TITLE
Parenthesis, await and chained functions

### ISSUE THREAD

**Issue by lukejagodzinski** [prettier/prettier#3894]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaXedGACgEpdgAdKXXG1Ad1VJlwFV0cAE7oAdPlJQAJjSEAbOGBgRhdFmzZiADsIgArJbWC4oqALZwkuAIy4Avutaax51NpqEhw3AF4AfLheImJmlk6auGIqAILCwqiY9Bq4ES5uHmFwfoHMzpHCcDCEwqxZ0RD82toiAMIYcPQA3Clsjq1RkvLwwjRZOYyOLVD2IAA0IBDaZNDoyKCo8RCcAAqLCHMoqABuEKTS42jUyPio8kITAEYJYADWRQDK2qhgUgDmyDDChHAT0hBgE5nC4gKTeGArBJvNxA86-ED6dAADwAQjd7jAHhY4AAZKRwWEgiCEGDaEkAJkJ8OeohEyBAl1Ql0w8mgh10UhgAHV9jAABbIAAcAAYJroIEIuQltPTdHBvNsCRNCgBHQikQqQ1DQ1BUiZCcykT7feHod6KACKhAg8D1IBgTJ50n5yHJEy+PHk71qEHMMJQUGgSpAwQAKkzNqc4fZ7EA)

**Input:**
```js
async function test() {
  (await Users.find(selector)
    .project({ name: 1 })
    .map(user => user.name)
    .toArray()
  )
    .map(name => {
      return name.toUpperCase();
    })
    .filter(name => {});
}
```

**Output:**
```js
async function test() {
  (await Users.find(selector)
    .project({ name: 1 })
    .map(user => user.name)
    .toArray())
    .map(name => {
      return name.toUpperCase();
    })
    .filter(name => {});
}
```

**Expected behavior:**
```js
async function test() {
  (await Users.find(selector)
    .project({ name: 1 })
    .map(user => user.name)
    .toArray()
  )
    .map(name => {
      return name.toUpperCase();
    })
    .filter(name => {});
}
```

I would expect `)` to be moved to the next line so that it visually presents that it's where the promise for the `await` has to be returned and everything after `)` is just working with the promise's resolved values. Currently, it looks like all the chained methods are relate to `Users.find()` but it's not true. Everything util `toArray()` is related with the promise generation and from the `map()` it's working on the promise's resolved value.

**Comment by thorn0** [comment]
Looks good in 2.0.2.

**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaXedGACgEpdgAdKXXG1Ad1VJlwFV0cAE7oAdPlJQAJjSEAbOGBgRhdFmzZiADsIgArJbWC4oqALZwkuAIy4Avutaax51NpqEhw3AF4AfLheImJmlk6auGIqAILCwqiY9Bq4ES5uHmFwfoHMzpHCcDCEwqxZ0RD82toiAMIYcPQA3Clsjq1RkvLwwjRZOYyOLVD2IAA0IBDaZNDoyKCo8RCcAAqLCHMoqABuEKTS4yAARglgANZFAMraqGBSAObIMMKEcBMAFjDm8gDq77xwdA3MBwS4bXikba8TDIcDoOYTKTeGArBL3NzIfCoeRCCb6dAADwAQqcLjBLhY4AAZKRwTHY3EgfEEy4PRQARUIEHg9JxbxAN1EIlhR1QRzg8kOuikMB++xg72QAA4AAwTXQQIQ-BLaWG6QEibZ0iYARy58FRU02aHQAFooHA4NInYdCmbSIVUah0aheYyhOZSE8Xvz0Gy4JzuXSkFi+RMYGK5dIFcgAEzxhKkeQPWoQcwYlBQaDGkDBAAqYs2scZ21eAEkZAhyWBhKRpjEZJcYJhFH7+RgYH2JtIIGAh5NCDBtJPU337PYgA)
```sh
--arrow-parens avoid
--parser babel
--trailing-comma none
```

**Input:**
```jsx
async function test() {
  (await Users.find(selector)
    .project({ name: 1 })
    .map(user => user.name)
    .toArray()
  )
    .map(name => {
      return name.toUpperCase();
    })
    .filter(name => {});
}
```

**Output:**
```jsx
async function test() {
  (
    await Users.find(selector)
      .project({ name: 1 })
      .map(user => user.name)
      .toArray()
  )
    .map(name => {
      return name.toUpperCase();
    })
    .filter(name => {});
}

```
