### ISSUE TITLE
Cleaner line-breaking for multiple nested ternary statements

### ISSUE THREAD

**Issue by 0x24a537r9** [prettier/prettier#3895]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAQnG8BOGARnAGYT5wYAOleAlnISWAIYCuAzlRKRjAAsqUemCrVW+VgBtpcaRk4x87MDHaVOGXhgA64aABN6MetAwB+DADcZ7Kkn26okKEsUwAnnIwBePVAYihAAtnAAwkYmZoFWSt5wnAB01owA7gBykvgQaRiOgdqCTJFQxqbmcV5yyalwaQDq9IYOzkGsUBDF+KXlMZYeCbXpADLQAOb5bYM1KekA3M7Oru7xPv7TnKFwAGpMnmNQ473R0AAqAqwwAGIUYpwj9FBwWJSsANZP49NBVUNz9Sy+ByeQKQS6Qh6UQqsRmiQBjWarUKHQhTD2+AOExOMIuV1ecA+DyeiR+AzW8LqaUOkzBcOG9UWUGc6AwAEFpAQoFd6NZ5J4ADQYNImAT8IQYSDScxXcVUEjjJ4iI4FFYwOF+AJBLZhHH9P6zKlAkHTJBFSF6yr0hFNFqmjCo7qW2EUhnUib210IpnLaCrapUDaFHW7fY0514m53RKPZ4Ej5fMkGynpY25e1oqFlU4ugNu21we2OyEYrFHCOXGDx97E56cJPWqk0z1573OEACkAQagwzjIUDZXIABUkCD7KFY1ggzQ7IFYSmQpBk3E7RCkYHeuAAyhIwF9F8u4J3DBAwAfpCuQE9uPgYEOpOMQqxz5eAFacAAer1YG+3rDCsZwMgyj2J2EDsDA1AQQATC+R4gBI+A3sgICkNKaSzrQTwwLagjIAAHAADJ2tAQNwDRSNQKG0IkTB8rOlAAI7sPQlD3qwj7PkgS4XvB3AhPQwEqHxXxyAAiuwXRAUgIHwTArBELhAjINBnbKKw9DSF8kQhE+KEyNIs5cHAZwKeOPHcAAvpZQA)
```sh
--no-bracket-spacing
--jsx-bracket-same-line
--parser flow
--single-quote
--trailing-comma all
```

**Input:**
```jsx
// Better before prettier because of the nice parallel structures of "condition ? value :"
const style = 
  someCondition ? styles.viewNarrow :
  otherCondition ? styles.viewWide :
  anotherCondition ? styles.viewLong :
  styles.view;

const style = 
  someVeryLongConditionThatForcesLineBreaking
    ? styles.viewNarrow :
  otherCondition ? styles.viewWide :
  anotherVeryLongConditionThatBreaksLines
    ? styles.viewLong :
  styles.view;

// Alternatively, with the colon at the beginning:
const style = 
  someCondition ? styles.viewNarrow
  : otherCondition ? styles.viewWide
  : anotherCondition ? styles.viewLong
  : styles.view;

const style = 
  someVeryLongConditionThatForcesLineBreaking
    ? styles.viewNarrow
  : otherCondition ? styles.viewWide
  : anotherVeryLongConditionThatBreaksLines
    ? styles.viewLong
  : styles.view;

```

**Output:**
```jsx
// Better before prettier because of the nice parallel structures of "condition ? value :"
const style = someCondition
  ? styles.viewNarrow
  : otherCondition
    ? styles.viewWide
    : anotherCondition ? styles.viewLong : styles.view;

const style = someVeryLongConditionThatForcesLineBreaking
  ? styles.viewNarrow
  : otherCondition
    ? styles.viewWide
    : anotherVeryLongConditionThatBreaksLines ? styles.viewLong : styles.view;

// Alternatively, with the colon at the beginning:
const style = someCondition
  ? styles.viewNarrow
  : otherCondition
    ? styles.viewWide
    : anotherCondition ? styles.viewLong : styles.view;

const style = someVeryLongConditionThatForcesLineBreaking
  ? styles.viewNarrow
  : otherCondition
    ? styles.viewWide
    : anotherVeryLongConditionThatBreaksLines ? styles.viewLong : styles.view;

```

**Expected behavior:**
In this case, I think the original is vastly clearer--much closer to a switch case or functional pattern matching. The current formatting doesn't handle the last (else) case clearly (since it's on the same line), and it's hard to track quickly tell which parts of the expressions are the conditions and which parts are the values. The parallel structure of the original is much easier to parse, and I would propose it become Prettier's way of handling such

**Comment by lydell** [comment]
Thanks for the issue! I believe this is already discussed in #737. Feel free to move you comment over there! Let me know if I missed something!

**Comment by j-f1** [comment]
Duplicate of #737
