### ISSUE TITLE
JSX spread operator syntax error on the flow parser

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#3898]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAUgZQBoD4A6UABEcAHQVwAmA5nAM4C+hqA9FniADQgQAOMAJbR6yUAEMATpIgB3AApSEolOIBuEQVW4hx9GMgBm4gDb04PAEaTxYANZwYmPrcFQayGJICuFkFQgwI1NzHjdzSRh5GxoAW3Fgsz8AK3oADwAhG3tHTHFYuAAZNzhE0N5vGD5KgCYyvxdJCOQQQxM5HT5JNxgAdS0YAAtkAA4ABh4uiHNemz4WroY4STVSnkk4AEdvQQ3o8TiEpGMknnNYwU8fP3o3GhM4AEVvCHh6nhhxS36qIeQaj42QQmO4AYQgsXiLSg0DWIG85gAKl8VCdzIxGEA)
```sh
--parser flow
```

**Input:**
```jsx
<JSX>
  {...edges}
</JSX>
```

**Output:**
```jsx
SyntaxError: Unexpected token ... (2:4)
  1 | <JSX>
> 2 |   {...edges}
    |    ^^^
  3 | </JSX>
```

It works in babylon, so my guess is that we just need to upgrade flow and it should just go away.

**Comment by j-f1** [comment]
What does this even do? [the Babel 6 REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=DwKQygGgfAUABHA3gOlQUwCYHM0GcC-MwA9ONDEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact&prettier=false&targets=&version=6.26.0&envVersion=) passes the spread through unchanged, even in ES5 mode. Babel can’t parse the result in standards mode, either.

**Comment by vjeux** [comment]
I have some more context. In React currently we don't need to use `...` because the type of an child in React is either an object or an array of objects. We're playing around a version of React that doesn't handle arrays and you've got to manually spread in order to get the same behavior. We have a custom jsx transform step for it.

It's unclear at this point if we are going to move forward with it but the latest version of both flow and babylon are parsing it so it shouldn't be a burden on prettier to print it.

**Comment by mroch** [comment]
https://github.com/facebook/jsx/issues/57

It's part of JSX now
