### ISSUE TITLE
Object destructuring without declaration

### ISSUE THREAD

**Issue by brunovandamme** [prettier/prettier#3902]
When using object destructuring with already declared variables, parenthesis around the expression should be used (according to [this page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)). When doing so, prettier precedes the statement with a semicolon. 

```
let a, b, object = { a: 1, b: 2};

({ a, b} = obj)
```

Prettier rewrites the destructuring as (notice the semicolon in front):

```
;({ a, b} = obj)
```

Is this expected behaviour?

**Comment by TrySound** [comment]
@brunovandamme That's "no semi" behavior. Because a sequence of paren pairs will give you call expression.

**Comment by brunovandamme** [comment]
I see, when using semicolons it is indeed left as like ({ a, b} = obj);
Thanks for clarifying!
