### ISSUE TITLE
[css] Incorrect format of multiline @value (modules values)

### ISSUE THREAD

**Issue by cjies** [prettier/prettier#3916]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAbgQwDYFc4AEAZhBAPpYBOANAQEaaUWO3bQDmzNBbU7v-Dl2KUIAWwIByAHQB6KgEtMdbHADO0sRAAmuVdLBq1kgNwAdKCGogIABxgLoa5KFuUFsAOoLtMABbIABwADNYwyt6+AUgATNZqHvxwAIq4EPDIRDhqcGGUmArYiQDC4mKYyCBQ0HBWIHT5YADWcDAAyraYYInIMJT41gBWagAeAEKNLe2YYnAAMh61SFnYOdadlDmUlYbO8XBiCr39uSC4OQAqys7L2aceWzAACvns5Zl31pRwAI64Ct8Xpg3hVbqtTm4IDlPPlbJU3Oo4JR0LVrIxRAB3J6MBA3ECYdAQHx1bQQMAfcFotQwClrGy4GC2BkxWlwAC+bKAA)

**Input:**
```postcss
@value foo_var, bar_var, long_var, longlonglong_var from "./variables.module.css";
```

**Output:**
```postcss
@value foo_var,
  bar_var,
  long_var,
  longlonglong_var from "./variables.module.css";
```

**Expected behavior:**
should grouping multiple values with parentheses `( )` on multiple lines.

```postcss
@value (
  foo_var,
  bar_var,
  long_var,
  longlonglong_var
) from "./variables.module.css";
```
As the spec of postcss-modules-values or postcss-icss-values:
https://github.com/css-modules/postcss-icss-values/blob/v1.3.0/test/index.js#L124
https://github.com/css-modules/postcss-icss-values/blob/v2.0.0/test/test.js#L163

**Comment by zaygraveyard** [comment]
Duplicate of #2355 ?

**Comment by evilebottnawi** [comment]
@zaygraveyard yes, thanks :+1:

**Comment by j-f1** [comment]
Duplicate of #2355

**Comment by evilebottnawi** [comment]
@j-f1 Thanks, I often forget to do `duplicate`
