### ISSUE TITLE
JSX Wrong identation

### ISSUE THREAD

**Issue by VIMGAS** [prettier/prettier#3928]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEATggCZyEAUAlMADpTEzqFT4X374A8JOAbgD4O3dABshULqJz4A1nACeAXmA4oZAB4BfCbRjAYACxwBnAHQmYAQ3hniAWwh81AcwCyVqFZfl8AMj96PSNTC2tbe09vcgAVCAAlOEc+ODNIewAHTwV8JSV8PitRdFScEn9AqGDjc0sbVMivH0I4xOTS8rz8RujCMzL8AH42IJg9cbHJienJrgAZCCteKBd8K2x+OBUYQhKtfAB6XSmTmZmqfCQRqtPbs8me5rNUHEJLADkrezh8AGp8WggAFA-6PchmURWD5fOCje7wyZULRwu6ovTAQrFVLESG4aAmADaAAYALpmdZgOAmExzOApUT4AT5ADMRIqKIR9zBfQGAEJ8gBBdBGMw+GAASSgqAg1DM6BM4IGAQ5aNu3LMHia4IpVJpdLgDK4BSKJTsBpseCghNJ5LAlOptPpQ2unNVei4JiyVRurtdYEh1M+3yUgP9EAVgJVvtu0AAwtIwLIVNRcgJ8HQfW6syFzGRRHB4JrehR1WUADTGrH9EhUADcUazMy0yMz0ZmxzbqI0Dc7XAOns8HcbJwuV3YreH0xAkYnnaRPdVfekQ+jdYXTfXswOYhXtz7vEEwk4x5Pp7P5+Pa6gWhAZZAEAyeKtyFAVkIhAgAHcAApvhAmZAQCsPgIDKW8gMsZBUCKBU7wAI0IdZ5BgABlLIwFcZAdhKO8SAgMAoJguA7zUBVCBgb9EJcSJCNEWCQAAKxMDQACFEMTAsUJhOY1DgLDdmI+9hQyYUACZaPorI3nIQC4KsOCFFEaBwIyQg1BgAB1MojGQAAOIk71U8M4A0xCMkA1SqXIFJwOIABHdBXjgSjvBopBoLowSFXsHAJK81x8wARXQCB4D8u9rDgrSSB0pBRIixCcGkFZYwgew3KA0RRHA+U4BieSAKQbC4GbIA)
```sh
--jsx-bracket-same-line
--no-semi
--trailing-comma all
--use-tabs
```

**Input:**
```jsx
function render(){
return (
  <div>
  <ul>
<li key={index}>
	{this.state.removingManager &&
	this.state.managerToRemove.company == value.id &&
	this.state.managerToRemove.id == manager.id ? (
												<Loading active={true} />
											) : (
												manager.firstName + " " + manager.lastName
											)}
											{value.relations[0].accessLevel >= 30 &&
											manager.id != Auth.getInfo().user.id &&
											manager.Manager.accessLevel < value.relations[0].accessLevel ? (
												<span
													className="close"
													onClick={() => {
														this.deleteManager(manager.id, value.id);
													}}
												>
													x
												</span>
											) : (
												""
											)}
										</li>
									);
								}
							</ul>
						</div>
                                );
}
```

**Output:**
```jsx
function render() {
	return (
		<div>
			<ul>
				<li key={index}>
					{this.state.removingManager &&
					this.state.managerToRemove.company == value.id &&
					this.state.managerToRemove.id == manager.id ? (
						<Loading active={true} />
					) : (
						manager.firstName + " " + manager.lastName
					)}
					{value.relations[0].accessLevel >= 30 &&
					manager.id != Auth.getInfo().user.id &&
					manager.Manager.accessLevel < value.relations[0].accessLevel ? (
						<span
							className="close"
							onClick={() => {
								this.deleteManager(manager.id, value.id)
							}}>
							x
						</span>
					) : (
						""
					)}
				</li>
				); }
			</ul>
		</div>
	)
}

```

**Expected behavior:**
```jsx
function render() {
	return (
		<div>
			<ul>
				<li key={index}>
					{this.state.removingManager &&
					this.state.managerToRemove.company == value.id &&
					this.state.managerToRemove.id == manager.id ? (
							<Loading active={true} />
						) : (
							manager.firstName + " " + manager.lastName
						)}
					{value.relations[0].accessLevel >= 30 &&
					manager.id != Auth.getInfo().user.id &&
					manager.Manager.accessLevel < value.relations[0].accessLevel ? (
							<span
								className="close"
								onClick={() => {
									this.deleteManager(manager.id, value.id);
								}}>
							x
							</span>
						) : (
							""
						)}
				</li>
				); }
			</ul>
		</div>
	);
}
```

**Comments:**
Eslint lints the Tabs formatted by prettier. It says it should be one more on lines 9,10,11,12,16,17,18,19,20,22,23,24,25.

**Print:**
![image](https://user-images.githubusercontent.com/20145874/35976503-79d1fc86-0cc7-11e8-84e7-ff86cf0fdf93.png)

**Comment by j-f1** [comment]
We recommend you disable all ESLint rules that check your formatting with something like [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier), since Prettier doesn’t always match the rules’ expectations.

**Comment by VIMGAS** [comment]
@j-f1 It worked. Thanks!
