### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by dhoko** [prettier/prettier#3929]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEATgOYQwCyEAJnADYAUAlPvsADpRdu++RQAzjHxQAhgFs4+ALz4A5PIDcPPr2JwY6YlHYBfFdyh6ucAB4AHEiLqox6eiKJkK1OvSUgANCAgXc0ILIoGLExBAA7gAKoQhBKGL0EWIAnkE+YsLIdvSCcD4ARsRiYADWmgDKFiU4UKTZiXk+NBBgDbn5ILV5xDBRxaQSYu1NIABWgmYAQsVllZJwADK1cCOdEOgwFpsATGs+1cQ9yCAFYgUp9NDeIBbEtTAA6jg0MAAWyACMAKwADAfhPKPYoWE53OA9ABuqx8GgAjugcBp+mJBsMkDBiOhOnkJDhkJjsT5BLVSPQ4ABFdAUVYYrGdGDnZ6vD5IAAsPkxYhw9FJAGEIBIhicoNAYSB0HkACrneI5PJ6PRAA)
```sh
--arrow-parens always
--no-bracket-spacing
--print-width 150
--require-pragma
--single-quote
--tab-width 4
```

**Input:**
```jsx
function forgotModel()  {

        const name = '';
        return {};

}
export default forgotModel;
```

**Output:**
```jsx
function forgotModel()  {

        const name = '';
        return {};

}
export default forgotModel;
```

**Expected behavior:**

```js
function forgotModel() {
    const name = "";
    return {};
}
export default forgotModel;
```

---

I tried with the default config and it works. cf:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEATgOYQwCyEAJnADYAUAlPvsADpRdu++RQAzjHxQAhgFs4+ALz4A5PIDcPPr2JwY6YlHYBfFdyh6ucAB4AHEiLqox6eiKJkK1OvSUgANCAgXc0ILIoGLExBAA7gAKoQhBKGIAbhA4NN4gYsLIdvSCcD4ARsRiYADWmgDKFiU4UKTIMMTo+SA0EGDZYrkttXnEMFHFpBJind0+AFaCZgBCxWWVknAAMrVwY3k+EOgwFjsATBst1cR9yCAFYgUAnvTQ6RbEtTAA6qkwABbIABwADD6PCB5F7FCznR5wPqJdY+DQAR3QOA0gzEw1GSBymxAeQkOAaTRaglqpHocAAiugKOsMV0sTArm8aJ9kPsfI0xDh6MSAMIQCQjc5QaAwkDoPIAFSu8UxcD0eiAA

**Comment by j-f1** [comment]
> ```
> --require-pragma
> ```

`--require-pragma` requires that you add a comment containing `@prettier` or `@format` to the beginning of your file. If you add `/** @prettier */` to the top of the file, it should be formatted as you expect.

**Comment by dhoko** [comment]
#facepalm I didn't read this :-1: 
thx
