### ISSUE TITLE
--insert-pragma removes duplicate @pragmas

### ISSUE THREAD

**Issue by azz** [prettier/prettier#3933]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AAQA9cBGHfI0gJkvVRxABoQIAHGAS2gGdlQAQwBOwiAHcACiIT8UggG4QuAExYhBvGMgBmggDa84rAEbDBYANZwYAZXYWuUAObIYwgK7GQKiGF0GRqxORsIwkubOALaCbp7eAFa8xABC5lY2toJRcAAyTnABht4QHjDsZTRFQSAOwqHIICaCJgCe+tDq7MJOMADqqjAAFsgAHAAMrN0QRn3m7I3dcKEKhazCcACOHlwbEYLRsUh6xaxGUVxxXmdOzvpwAIoeEPDV3jAtAyrDyDSs7oIuPpbgBhCBRGKNKDQNYgDxGAAqLTkJyMAF80UA)
```sh
--insert-pragma
```

**Input:**
```jsx
/**
 * @x 1
 * @x 2
 */

```

**Output:**
```jsx
/**
 * @format
 * @x 2
 */

```

**Expected behavior:**

```jsx
/**
 * @format
 * @x 1
 * @x 2
 */

```

Fixed in https://github.com/facebook/jest/pull/5502

**Comment by SimenB** [comment]
jest-docblock 22.2.2 is available
