### ISSUE TITLE
ambiguity on ternary and flow types

### ISSUE THREAD

**Issue by MarkKahn** [prettier/prettier#3936]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAFMQIwD8ATEgMwCUSmUArgLYBGcATvQNwgANCAgAHGAEt0yUAENu3CAHcACvIRpkIWQDcIEgCZDtGZNlkAbNHGEdussAGs4MAMqiHEqAHNkMbiw2IAYQYGaW1sJe1twwKvbebLLhVkEAVmgAHgBC9k4urrJscAAyXnApkSIsMKI1VJVBHtwxWtgWysai3F4wAOqGMAAWyAAcAAzC3RDWffaiWt1wMToVwtxwAI4sEhvxsonJSOapwtZsEn4BQWhe3hZwAIosEPCNwjCyHAMGw8hUH3sEgsdwAwhA2EktFBoGsQCxrAAVL6aY4ROAAXwxQA)
```sh
--parser flow
```

**Input:**
```jsx
const foo = ((1?2:3): number);
```

**Output:**
```jsx
const foo = (1 ? 2 : 3: number);

```

**Expected behavior:**

I find the output very confusing.  It reads to me as `1 ? 2 : (3: number)` but it means `((1 ? 2 : 3): number)`

**Comment by lydell** [comment]
Thanks for the issue! I think we can bake this one into #3850.

**Comment by MarkKahn** [comment]
#3850 is a different issue in my opinion since it doesn't involve flow/ts types.  If you really feel it belongs in the same place for eng reasons or whatnot I'll comment over there.

**Comment by lydell** [comment]
Both are about printing parens around the "else-part" of ternaries when the "else-part" is another ternary?

**Comment by MarkKahn** [comment]
But it's not another ternary in this case, it's a static type.  And I'm suggesting parens around the entire ternary so that the type binding is clear

**Comment by evilebottnawi** [comment]
@lydell seems, it is other issue and not related to link on issue above, let's reopen to discussion

**Comment by j-f1** [comment]
Happens in Babylon, too:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAFMQIwD8ATEgMwCUSmUArgLYBGcATvQNwgANCAgAHGAEt0yUAENu3CAHcACvIRpkIWQDcIEgCZDtGZNlkAbNHGEdussAGs4MAMqiHEqAHNkMbiw2IAYQYGaW1sJe1twwKvbebLLhVkEAVmgAHgBC9k4urrJscAAyXnApkSIsMKI1VJVBHtwxWhyyHACeFtDGotxeMADqhjAAFsgAHAAMwv0Q1kP2olr9cDE6FcLccACOLBI78bKJyUjmqcLWbBJ+AUFoXt4WcACKLBDwjcIwHSMG42QVB+9gkFieAGEIGwklooNAtiAWNYACodTTnCJwAC+2KAA)

**Input:**
```jsx
const foo = ((1?2:3): number);
```

**Output:**
```jsx
const foo = (1 ? 2 : 3: number);

```

**Comment by lydell** [comment]
Haha, it is indeed confusing since it fooled me so thoroughly!

**Comment by j-f1** [comment]
@lydell Should I check if the `TypeCastExpression`’s child is a `ConditionalExpression` or if the `ConditionalExpression`’s parent is a `TypeCastExpression`?

**Comment by lydell** [comment]
@j-f1 I don't know. I'd probably check some other cases where we _sometimes_ print parens and try to use the same approach.
