### ISSUE TITLE
Init command for config creation

### ISSUE THREAD

**Issue by darahak** [prettier/prettier#3944]
This recent [issue](https://github.com/prettier/prettier-atom/issues/375) we had on the prettier-atom repo (typo in `.prettierrc` config) made me wonder if there was a CLI tool to automatically create config files for Prettier.

I found a closed PR from last year (https://github.com/prettier/prettier/pull/1258) and a mention in the website rework thread (https://github.com/prettier/prettier/issues/3669#issuecomment-355843909).

When this PR was opened, Prettier didn't support configuration files, so I thought it was worth reconsidering this feature. What do you think?

**Comment by azz** [comment]
My thoughts are it could be useful, but there's no need for it to live in this repo. It could be a standalone CLI tool.

**Comment by olsonpm** [comment]
Is there a reason prettier doesn't throw upon invalid input?

**Comment by gabrielperales** [comment]
I just have created this CLI https://github.com/gabrielperales/prettier-init for creating `.prettierrc` files. I've been missing a `prettier --init` command for a while, so I decided to build a tool. I hope this can be useful for others.

**Comment by suchipi** [comment]
I'm going to close this since we aren't going to add it to prettier core and there's a community-provided solution. @olsonpm let's open a new issue to track that prettier doesn't throw when it can't parse the .prettierrc file.
