### ISSUE TITLE
Suggestion: `bracketSpacing: true` spaces in array literals and destructuring, no spaces in array indexes

### ISSUE THREAD

**Issue by sompylasar** [prettier/prettier#3950]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExMAs4A2BEAjADSYDuEATgQCYmYC+mAvNnocUpgDoh8RCAIrU69XgPEMBLANx8okKBkwBtLsIBMY2g22YAuu36DuEKvvoCAdGgAOBAJYwAFHIEBKRVAFDiKwk7Rxd3TxAvdQAGI19-CyDZEHsnVw8QMyjozABqTBI4pRAyEAgHGGd0ZFAAQxoaCEoABXqENGQQWoA3CGd6Eq6MZAAzWoI0OFKAIxpasABrOBgAZQd55ygAc2QYGgBXKZB6CDBR8cnSzcmaGGa5rYBbWvOJo4ArNAAPACE5xeWK1qjzgABlNnBXpcyvsYA5YdooUd1jQbp1prVpgBPYhQQYOGibGAAdX6MFwyAAHNFSgSIJNiXMHJ0CXAbt1IaUaHAAI77Zzc+61J4vJBjN6lSaPZy7A5HNCbLYEOAARX2EHgSNKMExpPo5OQuhAe1qzhc2wAwhBHs9OlBoJyQPtJgAVTEdMUXODMZhAA)
_(default options: `bracketSpacing: true`, not `--no-bracket-spacing`)_

**Input:**
```jsx
const helloWorldObject = { hello: "hello", world: "world" }; // new object
const { helloFromObject, worldFromObject } = helloWorldObject; // object destructuring
const helloFromObjectByIndex = helloWorldObject["hello"]; // object indexing
const worldFromObjectByIndex = helloWorldObject["w" + "orld"]; // object indexing with expression

const helloWorldArray = [ "hello", "world" ]; // new array
const [ helloFromArray, worldFromArray ] = helloWorldArray; // array destructuring
const helloFromArrayByIndex = helloWorldArray[0]; // array indexing
const worldFromArrayByIndex = helloWorldArray[0 + 1]; // array indexing with expression
```

**Output:**

Note the missing space around new array and array destructuring, where in the same scenarios there is a space when using objects:
```jsx
const helloWorldObject = { hello: "hello", world: "world" }; // new object
const { helloFromObject, worldFromObject } = helloWorldObject; // object destructuring
const helloFromObjectByIndex = helloWorldObject["hello"]; // object indexing
const worldFromObjectByIndex = helloWorldObject["w" + "orld"]; // object indexing with expression

const helloWorldArray = ["hello", "world"]; // new array
const [helloFromArray, worldFromArray] = helloWorldArray; // array destructuring
const helloFromArrayByIndex = helloWorldArray[0]; // array indexing
const worldFromArrayByIndex = helloWorldArray[0 + 1]; // array indexing with expression
```

**Expected behavior:**

If Prettier can distinguish between different usages of square brackets `[]`:
- new array
- array destructuring
- object and array indexing

I expect it to format them consistently with the same scenarios for objects:
```jsx
const helloWorldObject = { hello: "hello", world: "world" }; // new object
const { helloFromObject, worldFromObject } = helloWorldObject; // object destructuring
const helloFromObjectByIndex = helloWorldObject["hello"]; // object indexing
const worldFromObjectByIndex = helloWorldObject["w" + "orld"]; // object indexing with expression

const helloWorldArray = [ "hello", "world" ]; // new array
const [ helloFromArray, worldFromArray ] = helloWorldArray; // array destructuring
const helloFromArrayByIndex = helloWorldArray[0]; // array indexing
const worldFromArrayByIndex = helloWorldArray[0 + 1]; // array indexing with expression
```

I saw the previous issues about bracket spacing, notably the comment explaining the decision to omit the bracket spaces that mentions the commonly used styles, but I believe they don't attempt to distinguish array/object **creation** and array/object **indexing** which I think is useful and consistent with how objects with curly braces `{}` are formatted.
- https://github.com/prettier/prettier/issues/296#issuecomment-274840112
- https://github.com/prettier/prettier/issues/1303
- https://github.com/prettier/prettier/issues/3520

Thank you for your attention.

**Comment by lydell** [comment]
Thanks for the issue!

I was going to link you to all the previous discussions (how `--bracket-spacing` used to add spaces for arrays as well a long time ago, and how we’ve discussed removing the option altogether) but it seems like you already found them yourself. Good job!

As mentioned in https://prettier.io/docs/en/option-philosophy.html, `--bracket-spacing` is exactly the type of option we’d like to avoid. In exactly which situations should it add spacing? Should there be an option for every situation? You get the picture.

Now, it does not look like you’re suggesting an option, but asking for a style change, which is fine. However:

- As far as I understand and remember, Prettier used to work like you describe that you want it to work, but changed after feedback from early users. (#296)
- `--bracket-spacing` is on by default, so changing this now would mean a lot of churn for lots of Prettier users when upgrading Prettier.

I don’t think this change will be made. But now I’m unsure if I should close the issue or not. Oh well.

**Comment by sompylasar** [comment]
I don't think it worked before like I described: it added spaces within *every kind of* brackets, indexing brackets as well. And #296 does not mention that: it chooses from either "space in *every* brackets" or "*no* space in *every* brackets".

What I suggest is to differentiate index brackets (no space) from other brackets (yes space).

Yes, I understand that this style change may cause a lot of changes, but that is why Prettier exists, not to just fixate one set of style rules that most agree on for eternity but to provide automatic opinionated code style that can eventually be updated automatically (for example, in a separate commit).

How does Prettier team plan for such upgrades? Do y'all think the style is set in stone? What about newer JS features that may appear in the future that you cannot know about now?

**Comment by j-f1** [comment]
> What about newer JS features that may appear in the future that you cannot know about now?

That shouldn’t be a problem — we’ll just add support for them as they appear.

**Comment by suchipi** [comment]
We aren't going to make the proposed change, so I'm going to close this issue.
