### ISSUE TITLE
Parens are removed from (void 0)! in TypeScript (changes AST)

### ISSUE THREAD

**Issue by cevek** [prettier/prettier#3961]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQBNsC82AFKhAJb4AMAlAIQA6UYANugM7vYDK2wT2QXjpJsUAK4BbAEZxMAbiYBfJiAA0ICAAcY5aO2SgsmCAHcAClgQGU6MpXUgOMZADN0LdnA3TM6MADWcDDcWv7kUADmyDCY4t4guBBgbh5eGhFemDDmfpGS6KmeCQBW7AAeAEJ+gcHc6JJwADIRcEXpmuIwWl0ATO0JYZhZyCAwAJ5acOxgmOQ6jlpzsADqlDAAFsgAHFQaSxBeK35ao0vTcqhtGphwAI7i5Le56PmFSO7FGl6S5DFxCXYEUiLDgAEVxBB4AMNDB0NI1rhNsherC-OQWMCAMIQSQFUZQaDXEDiLwAFXhNk+XiUSiAA)
```sh
--parser typescript
```

**Input:**
```tsx
var d = (void 0)!
class S {
    d!: number;
}

```

**Output:**
```tsx
var d = void 0!; // don't remove parentheses
class S {
  d: number; // don't remove exclamation mark!
}

```

**Comment by j-f1** [comment]
> don't remove exclamation mark

That’s covered by #3852.

**Comment by j-f1** [comment]
Marking as a bug because `void 0!` and `(void 0)!` produce different ASTs (`UnaryExpression` → `TSNonNullExpression` for the first, `TSNonNullExpression` → `UnaryExpression` for the second).
