### ISSUE TITLE
Why `config` implicitly ignores editorconfig?

### ISSUE THREAD

**Issue by olsonpm** [prettier/prettier#3963]
I read through some comments in the [pr](https://github.com/prettier/prettier/pull/3255) introducing editorconfig integration - but I can't find a reason why [specifying a config should ignore a search for editorconfig](https://github.com/prettier/prettier/blob/master/src/config/resolve-config-editorconfig.js#L12).

My expectation is for the cli to parse `.editorconfig` for the filenames unless I specify `--no-editorconfig`.  I also expect a specified `--config` to only modify where `.prettierrc` is found.

I ask because I'm trying to create a PR integrating an API change in cosmiconfig, and I would like to understand this behavior before I continue.

**Comment by azz** [comment]
cc. @josephfrazier. I don't think we settled intentionally on one side or the other.

I think you are right in that `--config .prettierrc` should still respect `.editorconfig`, and `--config .prettierrc --no-editorconfig` should not.

**Comment by josephfrazier** [comment]
Hmm, it looks like I originally added this behavior in https://github.com/prettier/prettier/pull/2760/commits/7c2b54529c222e345459da9cac94286e1136debe, but I don't remember why. I agree with @azz that passing `--config` should still respect `.editorconfig`, so I'll open a PR to fix this. However, one side effect of fixing this will be that editor integrations calling `prettier --config ...` will still have to wait for the editorconfig resolution process if they don't also pass `--no-editorconfig`, but that seems preferable to the current behavior.

**Comment by olsonpm** [comment]
hey thanks so much.  I can work on the PR if you'd like as well.
