### ISSUE TITLE
Is it possible to setup "allman" braces style?

### ISSUE THREAD

**Issue by vitalysoftech** [prettier/prettier#3964]
Is it somehow possible to configure "allman" braces style instead of default "K&R" style? It would be nice to have such feature. I thought to apply tslint --fix after that but tslint doesn't support auto fix for braces style (overall brace-style is absent in tslint and can be inherited from eslint via plugin).

**Comment by j-f1** [comment]
Prettier is an opinionated code formatter, so we don’t offer options for these kinds of things. We encourage you to just follow our code style 😄

If that’s a dealbreaker for you, there are [`prettier-eslint`](https://github.com/prettier/prettier-eslint-cli) and [`prettier-tslint`](https://github.com/azz/prettier-tslint), which run ESLint or TSLint, respectively, after you run Prettier.
