### ISSUE TITLE
Angular.component.html files. Can we ignore specific file extensions?

### ISSUE THREAD

**Issue by Fallenstedt** [prettier/prettier#3970]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8BnADgQygD4AdKDDTARwFd8AneegWmzgBs4wYyL0AKGBADmwzgEU6jOPQCyCGgFEAtgEsYTAJQBeEiCGiJUpvKg1+AEjgA3BDE17effmAAWhYXEkMmK9Vt1wdyhPb2l6Sxs7BxAnChdgzwBNOAY-DRkdPTcPOBSGSNtYGLiMAG1VbDCmAHlcBABdQMrqmTqER3I+MvYIfAATVRCAZRh8eCa9XoGh4VHxuE6+VDKwGnp6O3FJ8HXN2HEl7rWNu3z6HZP9mHOjijL8dnYABQhsbFUAI05zuphsHaPF5vD7fPKpeh-bB3cq4EFfIw+GTYACSUHOOzh7wRXmMyLRt1iXXuADNVOwmADAmSKci9ERMAB6WhIlhsTjcUjEygk-BUVD8VwcXBZfQiMRwAASwsK0XpTN5VC5FCZeEIRBAABoQBBcDBVNBsMhQAx6BAAO7PBgII0ofDWCCqfpakD4bAwZC89hsbWfej4MAAazgMGGBDAs2QMHoNDg2v6EDAnsePpAQzYjGe-uEynwye9cZAACtsAAPABC-qDIeG+GUcAAMkM4PnUxAaDBcB2AEytwsEegZ5D6ACe9WwYHoqj1LtwU9gAHUnTBXMgABwABm1c7ecAX-tww7ncAzthdm1oqk2WfwObzSC9qbYaijMcLHxCRgg8D72rGnyXfoV2Qbs-39clZgAYQgZRc2HKBoBbbUaDYAAVfBPltR84AAXxwoA)
```sh
--parser typescript
```

**Input:**
```tsx
    <span>
      <quarter-select
      (toggleQuarterMenuEmitter)="toggleQuarterMenu($event)"
      (changeQuarterEmitter)="changeQuarter($event)"
      (changeYearEmitter)="changeYear($event)"
      [isQuarterOpen]="isQuarterOpen"
      [loadingState]="loadingState"
      [currentQ]="currentQ"
      [currentYear]="currentYear"
      [allPossibleYearOpts]="allPossibleYearOpts"
      [possibleQuartersInYear]="possibleQuartersInYear"
      [filters]="filters"></quarter-select>
      <faq (help)="toggleHelp($event)"></faq>
    </span>
```

**Output:**
```tsx
    <span>
      <quarter-select (toggleQuarterMenuEmitter)="toggleQuarterMenu($event)" (changeQuarterEmitter)="changeQuarter($event)" (changeYearEmitter)="changeYear($event)"
        [isQuarterOpen]="isQuarterOpen" [loadingState]="loadingState" [currentQ]="currentQ" [currentYear]="currentYear" [allPossibleYearOpts]="allPossibleYearOpts"
        [possibleQuartersInYear]="possibleQuartersInYear" [filters]="filters"></quarter-select>
      <faq (help)="toggleHelp($event)"></faq>
    </span>
```

**Expected behavior:**
I expect that any `angular.component.html` file to be ignored. I am binding a lot of information to my components, and it would be nice if they 'stack' like how they do in a .js or .ts file. 

Is there a way to ignore specific file extensions? I have a `.prettierignore` file however I can't figure out how to have it ignore files with a specific file extension.

**Comment by j-f1** [comment]
How are you running Prettier?

**Comment by Fallenstedt** [comment]
@j-f1 I have installed "Prettier - Code formatter" via the VSCode extensions marketplace.

**Comment by j-f1** [comment]
You should be able to put this in your `.prettierignore` file:

```
*.html
```

This will ignore all HTML files.

**Comment by Fallenstedt** [comment]
@j-f1 I am such a nincompoop. Thank you :)

**Comment by Fallenstedt** [comment]
@j-f1 
![prettier](https://user-images.githubusercontent.com/13971824/36177859-d8d42616-10cb-11e8-9fa0-d6c0beae13bb.gif)

And it still happens. I am emptied my vscode configs and I still encounter this issue.

**Comment by Fallenstedt** [comment]
@j-f1 This issue still occurs. The only setting I have active on vscode is `"editor.formatOnSave": true`

![prettier](https://user-images.githubusercontent.com/13971824/36177979-53638368-10cc-11e8-89f6-c9a6e1a26c53.gif)

**Comment by j-f1** [comment]
I’m not exactly sure what’s going on here. Reopening so another maintainer can provide feedback.

**Comment by suchipi** [comment]
@Fallenstedt When using VSCode's `editor.formatOnSave` setting, VSCode uses a built-in formatter to format HTML, not prettier. So this isn't a prettier issue. If you want to format JS on save but not HTML, [this StackOverflow answer](https://stackoverflow.com/questions/44831313/is-it-possible-to-exclude-some-file-extensions-in-format-on-save-in-visual-stu) recommends using language-specific settings:
```json
"[javascript]": {
    "editor.formatOnSave": true
}
```

**Comment by Fallenstedt** [comment]
@suchipi That makes sense. Thank you.

**Comment by suchipi** [comment]
Sure thing :+1:
