### ISSUE TITLE
Weird formatting of a method invocation in TypeScript

### ISSUE THREAD

**Issue by merlinnot** [prettier/prettier#3973]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEdMF5PAAMSBAjCcPALYAOANgIbwkBKAdAE5wBWcYMACgAeeAHyYRuKZgCuUACZwAZgEsoceQBpMaOHT7x5ANRVwA7pgZpM7ACIr+K6Aw4BPADwMor0QEoAvoEAOlAgmiAQNDBOUGjIoC4cEGYACi4IcSgMAG4QKvJhIFYwyEoMdLrhAEYcDGAA1nAwAMo0dWoA5sgwHDJw4fIQYKXllSBquhwwKbUdVAwjFf0g3GhCAEK1DU3NDFRwADJqcItjEDIwNBcATKfLbRyTyCAwrjRwaGAcKlGFNN+wADq+RgAAtkAAOQjhf4QXSA2o0Z7-D5wDjZE7hLgARxkKi4MwYcwWSDKS3CuioKm6vWWaE6+gAijIIPA7uEYAwqsD5GDkNcObUVHROgBhCBUebPKDQTEgGS6AAqXMyZN0gSAA)
```sh
--parser typescript
```

**Input:**
```tsx
const e = {0: {1: {template: R.reject(x => x === undefined, selectedView as R.Dictionary<any>)}}}

```

**Output:**
```tsx
const e = {
  0: {
    1: {
      template: R.reject(x => x === undefined, selectedView as R.Dictionary<
        any
      >)
    }
  }
};

```

**Expected behavior:**
```ts
const e = {
  0: {
    1: {
      template: R.reject(
        x => x === undefined, selectedView as R.Dictionary<any>,
      )
    }
  }
};
```

**Comment by j-f1** [comment]
Given Prettier’s current style, I’d expect it to look something like this:

```ts
const e = {
  0: {
    1: {
      template: R.reject(
        x => x === undefined,
        selectedView as R.Dictionary<any>,
      )
    }
  }
};
```

([playground example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEdMF5PAAMSBAjCcPALYAOANgIbwkBKAdAE5wBWcYMACgAeeAHyYRuKZgCuUACZwAZgEsoceQBpMaOHT7x5ANRVwA7mwZo27ACIr+K6Aw4BPAQyiuAlN4C+AQA6UCCaIBA0ME5QaMigLhwQZgAKLgixKAwAbhAq8qEgVjDISgx0umEARhwMYADWcDAAyjS1agDmyDAcMnBh8hBgJWUVIGq6HDDJNe1UDMPlfSDcaEIAQjX1jU0MVHAAMmpwC6MQMjA05wBMJ0utHBPIIDCuNHBoYBwqkQU0X7AAdTyMAAFsgAByEMJ-CC6AE1GhPP7vOAcLLHMJcACOMhUXGmDFm8yQpUWYV0VBUXR6SzQHX0AEUZBB4LcwjAGJUgfJQcgruyaio6B0AMIQKhzJ5QaAYkAyXQAFU5GVJugCQA) with the syntax slightly altered to show correct behavior)

**Comment by merlinnot** [comment]
@j-f1, you're right.

**Comment by merlinnot** [comment]
This seems to work as expected now.
