### ISSUE TITLE
Blank lines in JavaScript

### ISSUE THREAD

**Issue by jthalliley** [prettier/prettier#3977]
I like that prettier is minimal, but I wish there were an option to retain blank lines (or squish multiple blank lines down to one).

Thoughts?
Tom

**Comment by suchipi** [comment]
We currently *do* retain blank lines in many places, squishing multiples lines into one. However, there are many places where we remove blank lines (like the first line in a function declaration).

Are there specific things that are being formatted in a way contrary to your expectations?

**Comment by jthalliley** [comment]
I guess I'd prefer that if I put a blank line in anywhere, I did so for
readability. If I put 2 or more blank lines together, it's probably a
mistake, so swishing down to one is a good thing.

**Comment by j-f1** [comment]
Can you give us an example of where this is causing problems for you?

**Comment by jthalliley** [comment]
Sure. Will do.

**Comment by ralves09** [comment]
I hope my answer reopen this discussion.

In my opinion, prettier is all about readability and consistency, not about linters or code error. So, blank lines are a question for prettier cares about.
Sincerely, I don't think that a javascript file with a bunch of functions squished together (one blank line is still squish to me) is something visually easy to read.

I do use 7 blank lines to separate different functions, and usually 2 blank lines inside the function to separate some steps like "create a object with some user input - do some calculations - send this info via ajax - get the answer and show some alert to user"

So, like the option for the tabs size, prettier definitely should have options like "max blank lines permitted" or "blank lines between main functions" or "blank lines before function call"



    function saveAll() {
	   let post = {};
	   for (let b of boxes) post[b.id.substr(3)] = b.value;

	   if (document.getElementById('divDetails').querySelectorAll('input:invalid, select:invalid').length > 0) {
		alert('There are input errors!');
		return;
	   }


	   getCredentials(credentials => {
		credentials.purpose = 'provider';
		post.credentials = credentials;


		axios.post('/provider', post)
			.then((response) => {
				alert('It works');
			})
			.catch(err => alert(err.response.data));
	   });
    }





    function getSomethin() {
