### ISSUE TITLE
Semi is removed from `declare export default` statement in flow libdef

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#3978]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAjgA8AHCXGA9AM2wFdMqBWAbgB0oQAaECUmAEtoAZ2Sg8uCAHcACngRiU2AG4RBqHiGwiYyOphFxeAI1zYwAazgwAyqQuCoAc2Qxc9Y2ghh92Q15ORpSy5s4Atth+AbwAViLEAELmVja22OFwADJOcNFGvBD0MKTFAEz5Xg64wcggJtgmAJ6Y0FqkuE4wAOoaMAAWyAAcAAy8HRBG3eakdR1wwSp5vPgAjvSC+KHYEVFIBgUgRuGCbh5eIk7OmHAAivQQ8JW8MI29qAPIZS-mgphXAGEIOFInUoNBliB6EYACqNJQHOAAXyRQA)

(Not using `--no-semi`)

**Input:**
```jsx
declare export default 5;

```

**Output:**
```jsx
declare export default 5

```

**Expected behavior:**
```jsx
declare export default 5;

```

**Comment by j-f1** [comment]
[Also reproducible using the Flow parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAjgA8AHCXGA9AM2wFdMqBWAbgB0oQAaECUmAEtoAZ2Sg8uCAHcACngRiU2AG4RBqHiGwiYyOphFxeAI1zYwAazgwAyqQuCoAc2Qxc9Y2ghh92Q15ORpSy5s4Atth+AbwAViLEAELmVja22OFwADJOcNFGvBD0MKTFAEz5Xg64wcggNJgyWqS4TjAA6howABbIABwADLwtEEbt5qR1LXDBKnm8+ACO9IL4odgRUUgGBSBG4YJuHl4iTs6YcACK9BDwlbww2CadqD3IZQ-mgphnAMIQ4UidSg0HmIHoRgAKk8lDs4ABfeFAA).

**Comment by suchipi** [comment]
Thanks!
