### ISSUE TITLE
Unexpected output with nested `else if`

### ISSUE THREAD

**Issue by bobisjan** [prettier/prettier#3982]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground) not available, because playground does not support Glimmer parser yet.

**Input:**
```hbs
{{#if a}}
  {{#if b}}
    ab
  {{else if c}}
    ac
  {{/if}}
{{/if}}
```

**Output:**
```hbs
{{#if a}}
  {{#if b}}
    ab
  {{#if c}}
    ac
  {{/if}}
  {{/if}}
{{/if}}
```

**Expected behavior:**

Same output as input?

**Comment by n8n8baby** [comment]
If it helps, I have another failing case:
```
    {{#if boolean}}
    {{else}}
        {{#each members as |member|}}
        {{/each}}
    {{/if}}
```

It does not fail when the #each isn't there.

**Comment by n8n8baby** [comment]
I have filed a PR to address the two cases above:

https://github.com/prettier/prettier/pull/4256
