### ISSUE TITLE
`return (` for JSX

### ISSUE THREAD

**Issue by NekR** [prettier/prettier#3993]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt8xLSBnevAJQgn3XigKeblLAwAdAGEIAWyxQE+YAB0oePNgRFsACgCUeeYqXK4MctkUAePgOEAxbKQDm4mQD4F+-aYAS-NXgD0LvTdTMVhnVzd9cKDfEK4YAOiLQSEbe0dYJwBucIBfBRyQABoQCAwYAEtoemRQUmxsCAB3AAU6hGqUUgA3CHKCIpAGGGQySno4YoAjWzAAa0MAZQwBcqg7ZBhscgmQAggwEdIxndXx3GbbB1JD4+KAK3o0ACEZ+ZgF0kcAGVW4G-HihByDAMMCAEz-HbLbBnZAgSakSYAT0o0AGGGwqxgAHU+jAABbIAAcAAZihiIONsbYMHCMXAzl0-sUVABHcjlFQXNLXJCjAEgcbicobLY7eirOyUOAARXI7D+fKOApgiNxBAJyDBxU2pHKlElYnE4l5ICg0GZIHI4wAKoiOvy4DkckA)

**Input:**
```jsx
export default class Root extends React.Component {
  render() {
    return <React.Fragment>
      <Header />
      <Content>
        
      </Content>
    </React.Fragment>;
  }
}
```

**Output:**
```jsx
export default class Root extends React.Component {
  render() {
    return (
      <React.Fragment>
        <Header />
        <Content />
      </React.Fragment>
    );
  }
}

```

**Expected behavior:**

I don't understand why `(` is needed after `return`. Yes, I understand what exactly it does and that it prevents this:
```jsx
  return
  <div />
```
But that kinda was making sense only when you were writing/formatting code manually. I actually even understand eslint having such warning, just to make sure everything is written correctly. But prettier actually re-formats the code, it's the final instance of truth, but it needs such things? For me, it just wastes one colon of code.

Also, yes, I always, for years write it without `(` and never had any issues.

**Comment by lydell** [comment]
I think you are correct on all points. Here’s a comment explaining it: https://github.com/prettier/prettier/issues/1291#issuecomment-294367708

As far as I can tell, Prettier prints JSX this way due to this being the most common way people already formatted their JSX.

Prettier tries to avoid options: https://prettier.io/docs/en/option-philosophy.html

But a change here would be a massive one at this point. Also, I think there would be lots of people complaining about their start and end tags no longer lining up.

**Comment by azz** [comment]
Ryan Florence makes some excellent points _for_ `return (` in https://github.com/prettier/prettier/issues/2208.

As it was an intentional change and is working as expected, I'm closing the issue.

**Comment by NekR** [comment]
@lydell yeah, I agree that would be a massive change. Thanks for a detailed answer 👍 

@azz not sure if I agree with those points, but if it was intentional and previously it was different, then of course changing back wouldn't do any good.

Thanks!
