### ISSUE TITLE
JSON example option in demo results in error 

### ISSUE THREAD

**Issue by skube** [prettier/prettier#3994]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEsZF6AVgQAeAISmz5CkrbgAGVU4R1NMbRgsSIAmML1lMgtkEFdoLiwyVRgAdQ4YAAtkAA4ABgxMiFEcqSwUzLgLZlCMMjgAR21cNusSOwckQScMUVtcTR09AlU1ITgARW0IeHiMGBJxPPZC5Bi1qVwhGYBhCFt7FKhoFpBtUQAVDcYh0QBfV6A)
```sh
--parser json
```

**Input:**
```json

```

**Output:**
```json
SyntaxError: Unexpected token (1:1)
> 1 | 
    | ^
```

**Expected behavior:**
Expect to see something, not an error

**Comment by j-f1** [comment]
That’s because an empty file isn’t valid JSON. If you’re interested in contributing an example JSON file for the playground, we’d really appreciate it.

**Comment by ikatyang** [comment]
See #3667 for more info.

**Comment by skube** [comment]
I've attempted a [PR](https://github.com/prettier/prettier/pull/3995) 🕺

**Comment by j-f1** [comment]
Let’s keep this open until the PR is merged.
