### ISSUE TITLE
TS: `!` confuses prettier

### ISSUE THREAD

**Issue by ericanderson** [prettier/prettier#3999]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOhhAawQBkIBDAE1wHM4YAKAGwjDPwCcBKHWhrGMuxjcADgFcsaesAC+nANwAdKMvTY8hEuSo86TFmwhcAhLr4ChoiVNkKQAGhAQRMDNCzJQg9hADuABUEEDxQyADcIDAoHEDJ+ZAAzMkYsOEcAI3YyMCIYAGURbIwoamQYdjE0kAoWROTUx2LUoX8s6gBbMjqUqoArLAAPACEsnLo8sna4YmK4boanMRhxGAAmearC9mbkVABPETgsMHYMFxiRU9gAdSj0ZAAOAAZHS4hU66yRXcujuHYwnNHOw4ABHMQYEGtMgdLpIJI9RypdoYMoVKpYYrURhwACKYgg8A2jgE6VuFHuSFWJKyGEYWIAwhB2p1dlBoECQBI4AAVMjpEII1IyGRAA)
```sh
--parser typescript
```

**Input:**
```tsx
this.tokenLoads.get(locator).get(start).push({});

this.tokenLoads.get(locator)!.get(start).push({});
```

**Output:**
```tsx
this.tokenLoads
  .get(locator)
  .get(start)
  .push({});

this.tokenLoads.get(locator)!.get(start).push({});

```

**Expected behavior:**
```tsx
this.tokenLoads
  .get(locator)
  .get(start)
  .push({});

this.tokenLoads
  .get(locator)!
  .get(start)
  .push({});

```

**Comment by azz** [comment]
Very good catch! 

My suspicion is something is causing this `if` to be true only when there's a `!`:

https://github.com/prettier/prettier/blob/1b61b819d7f58c645c97a89b26e86915cad3c1f1/src/language-js/printer-estree.js#L4080-L4091

**Comment by j-f1** [comment]
This is how it renders at > 80 characters:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOhhAawQBkIBDAE1wHM4YAKAGwjDPwCcBKHWhrGMuxjcADgFcsaesAC+nANwAdKMvTY8hEuSo86TFmwhcAhDjLmLlq9ZuXe9foOE5xk6XPkgANCAgiYGNBYyKCC7BAA7gAKggjBKGQAbhAYFN4gZPzIAGZkjFhwPgBG7GRgRDAAyiJlGFDUyDDsYoUgFCw5eQU+dQVCUaXUALZknfmtAFZYAB4AQqXldJVkQ3DEdXBj3b5iMOIwAExbrTXsfcioAJ4icFhg7Bj+6SIPsADqqejIABwADD4vCAFN6lEQXF63ODsRKbHzsOAARzEGHhAzIw1GSFy4x8BSGGEazVaWDq1EYcAAimIIPBjj4BEUPhQvkgDvTShhGKSAMIQIYjC5QaCwkASOAAFTIRXi2IKMhkQA)
```sh
--parser typescript
```

**Input:**
```tsx
this.tokenLoads.get(locator).get(start).push({});

this.tokenLoads.get(locator)!.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaget(start).push({});
```

**Output:**
```tsx
this.tokenLoads
  .get(locator)
  .get(start)
  .push({});

this.tokenLoads.get(locator)!
  .aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaget(start)
  .push({});

```

**Comment by ericanderson** [comment]
I am going to try to fix this and put up a PR
