### ISSUE TITLE
Prettier behaves differently when formatting tests

### ISSUE THREAD

**Issue by Smedzlatko** [prettier/prettier#4002]
I am using prettier-std in my React Typescript application and I noticed it behaves differently in tests. When running `prettier-std --write '**/*.ts'`, it correctly added semicolons to all imports and lines, but it removed them (even when I manually added them) from the tests written in following style: 

```js
import * as actions from './record' // missing semicolons here
import * as constants from '../constants'

describe('record actions', () => {
  it('should fetch records', () => {
    const expectedAction = {
      type: constants.FETCH_RECORDS,
      id: 1
    }

    expect(actions.fetchRecords(1)).toEqual(expectedAction)
  })
})
```

**Expected behavior:**

I am not sure what part of configuration I am missing but I would expect to get the same behavior in my source files and in my test files.

**Comment by ikatyang** [comment]
I'm not sure what the issue you're facing, could you copy your example code to our [playground](https://prettier.io/playground/) then click the <kbd>Copy Markdown</kbd> button, paste it here and add your expected code so we can easily know what the problem is?

**Comment by Smedzlatko** [comment]
It seems that the expected behavior matches the output from your playground. That means that there is something wrong with my configuration, because prettier is not behaving this way when I run it in my project.

I have the following setup in my `package.json`. I am not sure how to fix it so it does what it is supposed to do. It works in my other source file (non tests):

```js
"scripts": {
    ...
    "lint": "standard --verbose | snazzy",
    "format": "prettier-std --write '**/*.ts'"
  },
  "devDependencies": {
   ...
    "prettier-std-cli": "^1.0.0",
    "snazzy": "^7.0.0",
    "standard": "^10.0.3"
  },
  "prettier": {
    "singleQuote": true
  }
```

**Comment by ikatyang** [comment]
It looks like there's something wrong in `prettier-std` instead of our options, which is out of our scope, you'll probably have to raise an issue there.
