### ISSUE TITLE
Prettier should have an ES6 mode (by flag) that hoists imports

### ISSUE THREAD

**Issue by ericanderson** [prettier/prettier#4004]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmADMIIBffInCdfAHRBIgYG46p2ATCAZRgFciRABQBKNhygZseQgCMAhjgpUa9EIpysQAGhARMMVNADOyUEuoB3AApKEZlAoBuEVJ10gFJmMiIKAGxM4PTkcBTAAazgYHkwI1CgAc2QYHH4QkG4wP0DgvUTgvBtwpPQFXKDMgCsTAA8AIXComJ4FdDgAGUS4Svz9fhhMQYAmPsz4nCLkDQU5AE8A6E9MHESYAHV3GAALZAAOAAY9VYhgjfDMGdW4IudevRw4AEd+VCeShTKKpH8qvWC6FQqXSmRMiSSATgAEV+BB4OM9DA5ltOLtkCMkeFUAEIQBhGjlGZQaAPED8YIAFTmjj+wTIZCAA)

**Input:**
```jsx
import {foo} from "foo";

doStuff();

import {bar} from "bar";
```

**Output:**
```jsx
import { foo } from "foo";

doStuff();

import { bar } from "bar";

```

**Expected behavior:**

Imports in es6 are hoisted. You can end up with code that has different effects based on its target environment. Its best to hoist in the source so there are no surprises.

```jsx
import { foo } from "foo";
import { bar } from "bar";

doStuff();

```

**Comment by ericanderson** [comment]
In ES6 module land, the run time behavior matches the expected

**Comment by j-f1** [comment]
Unfortunately, these imports could have side effects, which we can’t statically determine. Also, Prettier has a goal of never changing the AST, but this would alter the AST of the file.
