### ISSUE TITLE
Invalid newline/spaces added in JSX with &nbsp;

### ISSUE THREAD

**Issue by danez** [prettier/prettier#4014]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT77VwzrWcGHLlwA8AFTgAPGAD5hIsQEEAbgEMYa6gHpZAMigAjAM4AHANwTpcgyYuizaqLOBgndHHQ1wAdFDUAtnAAvrZmlo7OegGedBAwltqRsqJJpk4p2pIy8pwiqdlyCkzmHMEcIAA0IBCmuNDGyKBa1BAA7gAKWgiNKGoqEJ5VIGrGMMioaiTGcNWG1GpgANa8AMrpYDhQAObIMNTosyBxYBNTM9VbM9QwHQvbAWpn00cAVsZSAEILy2uBcAAZLZwZ4XGroGCmCEAJlBR3S1GuyBAhjUhgAnuQoMNTNQtjAKJ4YAALZAADgADNVcRAZhQFqZkbi4NcVCDqjwAI7oHA8O5qB5PJCTF7VGYxPYHI7GLbbEhwACK6HiIOF5yOmkMhLoJOQ0Oq+zUOBIsoAwhAAo9kVBoOyQOgZuI0b0RTNgsEgA)

**Input:**
```jsx
function HelloWorld() {
  return (
    <Text>
      <Avatar/>&nbsp;<Text>&nbsp;<span>{candidate.name}&nbsp;<span>&middot;</span></span></Text>
    </Text>
  );
}

```

**Output:**
```jsx
function HelloWorld() {
  return (
    <Text>
      <Avatar />&nbsp;<Text>
        &nbsp;<span>
          {candidate.name}&nbsp;<span>&middot;</span>
        </span>
      </Text>
    </Text>
  );
}

```

**Expected behavior:**

The whole line starting with `<Avatar />` needs to stay untouched and no newlines or spaces should be added, because otherwise it completely removes the value of having non-breaking spaces there.

```jsx
function HelloWorld() {
  return (
    <Text>
      <Avatar />&nbsp;<Text>&nbsp;<span>{candidate.name}&nbsp;<span>&middot;
          </span>
        </span>
      </Text>
    </Text>
  );
}
```

So  i guess the rule should be do not add spaces/newlines around `&nbsp;` (excluding jsx tags inbetween `jsxText` for this check)

So for example  `&nbsp;text&nbsp;` should be treated the same as `&nbsp;<span>text</span>&nbsp;`

**Comment by j-f1** [comment]
It looks like [Babel parses both the same way](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABACQKYBt1wOpwE7oAmAFAJSIDeAUIonqlCHksTbYgDwAqqAHlAD427TgEEAbgEMokvAHoBAMjAAjAM4AHANzc-g5eu0dNksAIoRThGIWmoAdGEkBbVAF8DmnSbOLnNwjgoHTkfAQ5QjVNwuR5-IREIuME2Ui0qNyoqUEhYBBQMLFwCEnJqWnpGZkRWROSEkTEpGTxEBU8jeuFGju8os27Gykswa1soBydXD1UvY36lf0JA4IiwwfY1hY2kvQbaXfjU9MygA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=react&prettier=true&targets=&version=7.0.0-beta.5&envVersion=). Is there a problem you’re encountering with this?

**Comment by danez** [comment]
Yes was my mistake sorry
