### ISSUE TITLE
Prettier strips exclamation points for TS 2.7

### ISSUE THREAD

**Issue by ericanderson** [prettier/prettier#4029]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOADgE4CWAbuvDgEbrUCESOmMdUAcwDcZMhUoBXFqlpgcAM0IAKAJTExFHNTgwJ1cjAAWtTADo21EeRwBfMjZAAaEBEoxa0TMlDtqEAO4ACuwIXijo9BC0ACZOIFgwyPLoqJhwzizU6GAA1joAypTZtILIfBLpINEQYEkpac4ladQwgVkCALbodamVAFaYAB4AQlm5BegdcAAyJXA9DS4SMJIwAEwLlUXUzcggMACelHCYYHRucTQlMADqMUbIABwADM40EGk3WZR7NCdw1Ho82c2gAjhJaNo2uhOt0kMles40h1aGVqBUkSUBKg4ABFCQQeCbZwwdAsO7RB5INYkrK0GSCADCEA6XT2UGgwJAEjSABUyWEEWkbDYgA)
```sh
--parser typescript
```

**Input:**
```tsx
class Foo {
  private bar!: string;

  public foo() {
    return this.bar;
  }
}
```

**Output:**
```tsx
class Foo {
  private bar: string;

  public foo() {
    return this.bar;
  }
}

```

**Expected behavior:**
```tsx
class Foo {
  private bar!: string;

  public foo() {
    return this.bar;
  }
}
```

**Comment by ericanderson** [comment]
I'll take a stab

**Comment by ericanderson** [comment]
Note to self:
```ts
private bar!: string; //AST type: ClassProperty, definite: true
private foo: string; // AST type: ClassProperty, definite: undefined
```

**Comment by ericanderson** [comment]
Duplicate of #3561

**Comment by j-f1** [comment]
Duplicate of #3561
