### ISSUE TITLE
Empty lines not removed in .json files

### ISSUE THREAD

**Issue by tenretC** [prettier/prettier#4033]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6U0zSKBDAWzhyQAIcBnGPAJwGsBaCmsCnAGgyxwDc4aKAS2glyIAIwAGAHQzJDPABsADgAs8sjl2whlNQTzzxRAMyUU4nTDsWCwCC6JwBZAJIAVLdZwIA5oKg4NmRSdG8dKAgAE2IQnAA+AF4ANmlxcU0QK24I5QInECSAVmkAZkztAF9snQAjAFdfYLIcVRgYZQokAHpu-xhVetrpSAJu-BhhfEVavCg6WrhFf3qxqlo6bsEKCnqgr24QVQgiZTxfWJaj9s6evsEBoZGT8aMppVn5xeXBVe71+gHHQ0ODKCBCGAQGgAT1EYRyOBg0OUlzE-SBh3qNEUBTaHS6vX6g2Go1ek2gHzmCyWKzW1Ho0nRICq2W8IBiPAAIqCEDEoGBBPsQvDsDYAjAmNQLlECgB2WSZGqHQYUOiwuIgGTiAAsZQxOj0cHagpoBQyUmkACZ9YiKLZYAUSgAORXaQ4wO3ihiQKAmQS+BiG438M3SF2SG0gJEoihgfTKHRXS3SVLW5nWapukCx+MeuFug0g0YEB4Fe0S9bSyNByb8b2qOBgOgFGsm0gAKnb3Xb0mArAo7AAVgPh9B2Mp++xYzt2B7KqQGAwAO76YxZAu28sFD1b9fhTdesANpvbz2wb3QP0B1t1o+NuikaTdHfi6SjzDprCZzBs8uS85wDKwobiAPZ9jOw5DhQY4TjO04DnOogANo4DeNALsuq6xOwaIPKQeBREBAC6VQYJUWQgBACZTBQyCgLQNAQEuAAKtAOMgIB4DwECCFEFF4FQyBmIoFjsCAtQ0HgTZGgAymcApQL4yAwDQexiVEEBgEJ5iWCAAQWDQMDMZJvgEHg2kibpw4AB4AEKSdJMAyYQcAADIBHAFmiZR9QdL5lpebpZwCPwHHvhRejigA6rxAzIE6khiXo4JwFFknKBxhoGXwFEggAjvUgggsZ5xmYFYkWCWymqbpQiKYocAAIr1BA8DlVGeC1DFURxUglpiSpeCCPavgAMInGVKCRIEFH1BY7idbRSDCRYlSVEAA)
```sh
--parser json
```

**Input:**
```json
{
	"name": "stark-srcs",
	"version": "10.0.0-alpha.0",
	"private": false,
	"license": "MIT",
	"engines": {
		"node": ">=6.11.0",
		"npm": ">=5.3.0"
	},
	"bugs": "https://github.com/nationalbankbelgium/stark/issues",
	"homepage": "https://github.com/nationalbankbelgium/stark",
	"repository": {
		"type": "git",
		"url": "https://github.com/nationalbankbelgium/stark.git"
	},

	"devDependencies": {
		"lint-staged": "7.0.0",
		"husky": "0.14.3",
		"prettier": "1.10.2",
		"tslint": "5.8.0",
		"tslint-config-prettier": "1.8.0",
		"typescript": "2.6.2"
	},
	"scripts": {
		"precommit": "lint-staged",
		"prettier-check": "prettier **/*.{css,js,json,pcss,scss,ts} --write",
		"tslint": "tslint",
		"tslint-check": "tslint-config-prettier-check ./tslint.json"
	},

	"lint-staged": {
		"*.{css,js,json,pcss,scss,ts}": ["prettier --write", "git add"]
	}
}
```

**Output:**
```json
{
  "name": "stark-srcs",
  "version": "10.0.0-alpha.0",
  "private": false,
  "license": "MIT",
  "engines": {
    "node": ">=6.11.0",
    "npm": ">=5.3.0"
  },
  "bugs": "https://github.com/nationalbankbelgium/stark/issues",
  "homepage": "https://github.com/nationalbankbelgium/stark",
  "repository": {
    "type": "git",
    "url": "https://github.com/nationalbankbelgium/stark.git"
  },

  "devDependencies": {
    "lint-staged": "7.0.0",
    "husky": "0.14.3",
    "prettier": "1.10.2",
    "tslint": "5.8.0",
    "tslint-config-prettier": "1.8.0",
    "typescript": "2.6.2"
  },
  "scripts": {
    "precommit": "lint-staged",
    "prettier-check": "prettier **/*.{css,js,json,pcss,scss,ts} --write",
    "tslint": "tslint",
    "tslint-check": "tslint-config-prettier-check ./tslint.json"
  },

  "lint-staged": {
    "*.{css,js,json,pcss,scss,ts}": ["prettier --write", "git add"]
  }
}

```

**Expected behavior:**
Removing the empty lines before the "devDependencies" section and the "lint-staged" section.
I don't know if it is normal or not.

**Comment by lydell** [comment]
Prettier uses the same rules for blank lines in JSON as for all other types of code.

https://prettier.io/docs/en/rationale.html#empty-lines

> It turns out that empty lines are very hard to automatically generate. The approach that Prettier takes is to preserve empty lines the way they were in the original source code. There are two additional rules:
>
>  -  Prettier collapses multiple blank lines into a single blank line.
>  -  Empty lines at the start and end of blocks (and whole files) are removed. (Files always end with a single newline, though.)

**Comment by tenretC** [comment]
thanks
