### ISSUE TITLE
Idea: sort package.json keys

### ISSUE THREAD

**Issue by simonepri** [prettier/prettier#4040]
It would be really cool to integrate something like [this](https://www.npmjs.com/package/prettier-package-json) directly inside Prettier.

**Comment by suchipi** [comment]
@azz @ikatyang does the current plugin API surface area make it possible to have a plugin that only formats files named exactly package.json?

**Comment by ikatyang** [comment]
`filenames` field should work.

https://github.com/prettier/prettier/blob/b6c27893cc32f0ad8800b045d4e88d14e04057ba/src/language-markdown/index.js#L30

https://github.com/prettier/prettier/blob/b6c27893cc32f0ad8800b045d4e88d14e04057ba/src/main/options.js#L75-L91

**Comment by suchipi** [comment]
If I'm reading that right, it looks like extensions have higher precedence over filenames, so I don't think you could make something that formats `package.json`, since the builtin `json` language would handle the json extension.

**Comment by ikatyang** [comment]
Oops, looks like we should give `filenames` or later plugins higher priority.

**Comment by simonepri** [comment]
What's the best way to integrate it?
We should use the [plugin API](https://prettier.io/docs/en/plugins.html) and release it as separate package?

**Comment by suchipi** [comment]
Yeah, that was my idea, but it looks like we need to make a small change in order for that to be possible first.

**Comment by simonepri** [comment]
Yeah I got this.
Should we discuss also about which will be the preferred order for the keys for this plugin?

**Comment by j-f1** [comment]
> Should we discuss also about which will be the preferred order for the keys for this plugin?

I’d recommend just using `prettier-package-json`.

**Comment by lipis** [comment]
It's under [MIT license](https://github.com/cameronhunter/prettier-package-json/blob/master/package.json#L5) but we could still ask @cameronhunter :)

**Comment by j-f1** [comment]
I was suggesting using it directly (i.e. via `require`) 😀

**Comment by simonepri** [comment]
@j-f1 actually there are a lots of 'orders' within the community, I believe that a short discussion on which one we want to choose will be appropriate.

Some of them:
[sort-package-json](https://github.com/keithamus/sort-package-json/blob/HEAD/index.js#L49) _(247,160 downloads in the last month)_
[fixpack](https://github.com/henrikjoreteg/fixpack#fixpack) _(9,384 downloads in the last month)_
[prettier-package-json](https://github.com/cameronhunter/prettier-package-json/blob/HEAD/src/defaultOptions.js) _(5,451 downloads in the last month)_
[sort-pkg](https://github.com/niksy/sort-pkg/blob/master/index.js#L9) _(1,408 downloads in the last month)_
[format-package](https://github.com/camacho/format-package/blob/master/README.md#order) _(427 downloads in the last month)_

**Comment by lipis** [comment]
Alphabetically.. universal and no discussions..!

**Comment by simonepri** [comment]
The tendency is to leave `dependencies`, `devDependencies`, `peerDependencies` and `optionalDependencies` on the bottom.
The aim should be both consistency and making it more readable for humans.

**Comment by lipis** [comment]
Yep! But in one case you still have to think and in the other one not anymore.. just scroll.. it's all there indexed :)

**Comment by simonepri** [comment]
Yes, but for instance anyone expects 'name' to be the first key inside the `package.json`.
Imagine a project with thousands of dependencies. No one will like to scroll indefinitely to find it.

**Comment by lipis** [comment]
`cmd+F` :)

**Comment by simonepri** [comment]
Too easy answer 😁.

The fixpack's approach seems really reasonable to me:
> name first
> description second
> version third
> author fourth
> all other keys in alphabetical order
> dependencies and devDependencies sorted alphabetically

**Comment by lipis** [comment]
I would also argue that the name, description, etc.. not changing that much.. and you mostly go to the `package.json` to check the scripts, dependencies and other more critical stuff.

**Comment by cameronhunter** [comment]
Key order is configurable in `prettier-package-json` by passing the `keyOrder` option – it can be an array of keys or a function (see [keyOrder tests](https://github.com/cameronhunter/prettier-package-json/blob/master/tests/key-order.test.js) for examples). If you specify the order using an array of keys, then any unspecified keys will be placed in alphabetical order at the end.

For example:

```javascript
const { format } = require('prettier-package-json');

const uglyPackageJson = {
  jest: {
    useBabelrc: false
  },
  description: 'My package description',
  version: '1.0.0',
  name: 'my-npm-package'
};

const explicitOrder = {
  keyOrder: ['name', 'description', 'version'] // Notice `jest` key isn't specified
};

console.assert(format(uglyPackageJson, explicitOrder) === `{
  "name": "my-npm-package",
  "description": "My package description",
  "version": "1.0.0",
  "jest": {
    "useBabelrc": false
  }
}
`);

const alphanumericOrder = {
  keyOrder: (keyA, keyB) => {
    if (keyA === keyB) {
      return 0;
    } else {
      return keyA < keyB ? -1 : 1;
    }
  }
};

console.assert(format(uglyPackageJson, alphanumericOrder) === `{
  "description": "My package description",
  "jest": {
    "useBabelrc": false
  },
  "name": "my-npm-package",
  "version": "1.0.0"
}
`);
```

See the [default options](https://github.com/cameronhunter/prettier-package-json/blob/master/src/defaultOptions.js) for other configuration values and the [tests for `keyOrder`](https://github.com/cameronhunter/prettier-package-json/blob/master/tests/key-order.test.js) may also provide insight.

**Comment by lipis** [comment]
Maybe for the scripts it makes sense..  it would it be possible to sort the rest in alphabetical order but the scripts in sensibly order?

**Comment by cameronhunter** [comment]
Yeah `prettier-package-json` will do that. The second example I gave above (passing `alphanumericOrder` function as `keyOrder` option) will sort top-level keys alphanumerically but still sort `scripts` sensibly.

Personally I don't think that alphabetical order is _pretty_, it's just _sorted_. In `prettier-package-json` I tried to choose an order of _importance_ but it's just my opinion, that's why it's configurable. CMD+F isn't a valid argument for alphanumeric ordering since CMD+F is also available when choosing any other order.

**Comment by lipis** [comment]
In alphabetical order you can just quickly scroll as it's all indexed.. while Cmd+F will be more useful when you don't know the order.. if really care about the name.. it's fast to do the `Cmd+F` and type `name`.. but I'm happy that it's doable through the settings.. it would just be nice to do that without settings.. we want less not more :D

**Comment by duailibe** [comment]
I don't think there's anything else we should do here. Gonna close since it's not actionable for Prettier.

**Comment by duailibe** [comment]
@simonepri we won't add this functionality here. It's best suited in an external tool.

**Comment by lydell** [comment]
See:

- [`prettier-plugin-packagejson`](https://github.com/matzkoh/prettier-plugin-packagejson)
- #6314
