### ISSUE TITLE
[SCSS] Selector starting with `&` is lowercased

### ISSUE THREAD

**Issue by ruedap** [prettier/prettier#4044]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAMgFoBGAIQEMAnXAogXwKZABoQIAHGAS2gBnZKDq0IAdwAKdBMJTUAbhD4ATDiGqCYydNQA2guJwBGtamADWcGAGVuFvlADmyGLQCuxkKohhdBkacTka0MFLmzgC21AGG3gBWggAelOZWNrbUUXAAMk5wcUFcHjDcpQBMRd4OtKHIIIJggsKc3LROMADqajAAFsgAHAAMbeJGXebcDe1woYqFnLRwAI4efMsR1NGxSHrxnEZRfG6e3oJOzvpwAIoeEPDVnDDUJj2q-cgVz+Z8+pcAYQgURiDSg0EWIA8RgAKq95PsjEwmEA)

**Input:**
```scss
.foo {
  &-1Bar {
  }
}
```

**Output:**
```scss
.foo {
  &-1bar {
  }
}
```

**Expected behavior:**

```scss
.foo {
  &-1Bar {
  }
}
```

**Comment by suchipi** [comment]
Does this actually break your code? CSS selectors are case-insensitive.

**Comment by ruedap** [comment]
> Does this actually break your code? CSS selectors are case-insensitive.

yes. HTML class names are case-sensitive.
https://stackoverflow.com/questions/12533926/are-class-names-in-css-selectors-case-sensitive

**Comment by suchipi** [comment]
Huh, the selectors are case-insensitive, but HTML class names are case-sensitive. That's confusing 😅  Today I learned.

**Comment by lydell** [comment]
cc @evilebottnawi

**Comment by evilebottnawi** [comment]
@lydell wip
