### ISSUE TITLE
Strange formatting for Flowtype object intersections

### ISSUE THREAD

**Issue by zaynv** [prettier/prettier#4047]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYhAJwFsAlBAEzgIAUCIMBnbAXm2AB0ptsALAQyjkANnADKAVwBGRAJYwk2ABSi0sHnBgywAUQBuCGAB4AEgBUAsgBl8xbSKIGAfAEoWj7LogzynAL7YAMjxCIlEYPnhA7AlJBg0bIgBBDBkAbk4QABoQek1oBmRQDAIZWAB1bxgeZAAOAAZs8MkK8irkACZshlKAcxEARXEIeGQAMz4hOMaCPhkhXoBhCCIiPmQQKGg4LJBJGbAAaw1RDD4wXuQYAnE4bIArBgAPACF9o5hRPgdLUu2kccmtxApwIcQI61GQggAHcdnFZJdrkDxHFTHxYmMJlMQKUwTBaHweqtMYDsgQ4ABHcQyckEolrf5YoHFCBxMozDDrYpwMH6HZ8Ah0aHUAUIAooPiebw7cgQMAk7F8BgwBVAiDiGAYDXtVW+XxAA)
```sh
--parser flow
```

**Input:**
```jsx
type FormRenderProps = {
  handleSubmit: (SyntheticEvent<HTMLFormElement>) => void
} & FormState & SubsetFormApi;

```

**Output:**
```jsx
type FormRenderProps = {
  handleSubmit: (SyntheticEvent<HTMLFormElement>) => void
} & FormState &
  SubsetFormApi;

```

**Expected behavior:**
I think even the original format looks way better... the "formatted" version seems out of place. Thank you all for your time.

**Comment by j-f1** [comment]
Here’s how #3988 formats this:

**Prettier pr-3988**
[Playground link](https://deploy-preview-3988--prettier.netlify.com//playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYhAJwFsAlBAEzgIAUCIMBnbAXm2AB0ptsALAQyjkANnADKAVwBGRAJYwk2ABSi0sHnBgywAUQBuCGAB4AEgBUAsgBl8xbSKIGAfAEoWj7LogzynAL7YAMjxCIlEYPnhA7AlJBg0bIgBBDBkAbk4QABoQek1oBmRQDAIZWAB1bxgeZAAOAAZs8MkK8irkACZshlKAcxEARXEIeGQAMz4hOMaCPhkhXoBhCCIiPmQQKGg4LJBJGbAAaw1RDD4wXuQYAnE4bIArBgAPACF9o5hRPgdLUu2kccmtxApwIcQI61GQggAHcdnFZJdrkDxHFTHxYmMJlMQKUwTBaHweqtMYDsgQ4ABHcQyckEolrf5YoHFCBxMozDDrYpwMH6HZ8Ah0aHUAUIAooPiebw7cgQMAk7F8BgwBVAiDiGAYDXtVW+XxAA)
```sh
--parser flow
```

**Input:**
```jsx
type FormRenderProps = {
  handleSubmit: (SyntheticEvent<HTMLFormElement>) => void
} & FormState & SubsetFormApi;

```

**Output:**
```jsx
type FormRenderProps =
  & {
      handleSubmit: (SyntheticEvent<HTMLFormElement>) => void
    }
  & FormState
  & SubsetFormApi;

```

**Comment by pronebird** [comment]
Same here:

```
type RelaySettingsNormal<TTunnelOptions> = {
  location:
    | 'any'
    | {
        only: RelayLocation,
      },
  tunnel:
    | 'any'
    | {
        only: TTunnelOptions,
      },
};
```

This emits the warning in plugin-eslint-flowtype:

>error  There must not be a line break after "location" type annotation colon  flowtype/space-after-type-colon

**Comment by j-f1** [comment]
@pronebird This is a different — and intentional — behavior. We recommend you disable all rules that enforce formatting, and we make this easy to do with [our ESLint config](https://github.com/prettier/eslint-config-prettier). You could extend the `prettier` and `prettier/flowtype` configs to disable the rules causing issues.

**Comment by pronebird** [comment]
@j-f1 yep it seems like including `prettier/flowtype` solves this. Thank you! 👍

**Comment by thorn0** [comment]
Closing in favor of #3986
