### ISSUE TITLE
`requirePragma` doesn't seem to work if there is a shebang line present

### ISSUE THREAD

**Issue by depeele** [prettier/prettier#4049]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiAhAegK4GcBOmARgJZSYIBuABFBACZwA65AVKy9a9QAIBmEfAFsAhjE6tMLPtihgYJaNXi4YACgCU1YNUhRV1EfoDucfNQC81ACwAmANx7cEADZwAdC4gBzNUxAApLjUJMEwABZwhiZmyhDULiR8cAA0ypHUsiSUZrip0fTUcDn4AJ4RZN7+aUa4pvga9gC+LCApIBAADgrQuMigIvj4EMYACoMIfSgilBAk9G0gIqrIfCIuee1E+CJgANZwMADKnbuVyDD42Kkg9BBgq+ubIGR5+DCjO96ijxs3AFa4AAeACEdvtDkcREI4AAZMhwX7PCDYGCdVG2JE3U74N7IEBEEREUpeKCLTr4MgwADq8wiyAAHAAGdoUiB5ak7Tr4ilwN45Rb4OAAR2wJCFnxE3xEFyuNzyQhIsuu7VwlTcAEVsBB4Fj2jAibT6PSkLZ9TsSIkoN4AMIQIQ-FB0KCI9p4OAAFSJUzWfyaTSAA)
```sh
--require-pragma
```

**Input:**
```jsx
#!/usr/bin/env node
/**
 * @format
 */
function test() { const answer = 42;console.log("%s is the answer to life, the universe, and everything", answer);}

```

**Output:**
```jsx
#!/usr/bin/env node
/**
 * @format
 */
function test() { const answer = 42;console.log("%s is the answer to life, the universe, and everything", answer);}

```

**Expected behavior:**
I expected the `@format` pragma to be honored.

Looking through the npm installed version of prettier, it appears that the issue is related to the `docblockRe` on line 372 of `bin-prettier.js`.

Adding the `m` option to this regular expression results in the expected behavior:
```javascript
const docblockRe = /^\s*(\/\*\*?(.|\r?\n)*?\*\/)/m;
```

**Comment by jedwards1211** [comment]
The pragma ought to work anywhere in the code, not just the very first comment.

**Comment by dfirebaugh** [comment]
This issue exists in the dependency jest-docblock.  I've submitted a PR to resolve.  I've also added a test in this repo with your exact problem that demonstrates that the docblock is not extracted when a shebang exists on the previous line.
