### ISSUE TITLE
Typescript: Definite flag formatting issue

### ISSUE THREAD

**Issue by ericanderson** [prettier/prettier#4051]
**Prettier 1.11.0-rc.1**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
foo!.bar().baz().what();
```

**Output:**
```jsx
foo
  !.bar()
  .baz()
  .what();
```

**Expected behavior:**
```jsx
foo!
  .bar()
  .baz()
  .what();
```

**Comment by ericanderson** [comment]
I'll take a crack at it, since I broke it probably :)

**Comment by ericanderson** [comment]
Hmm, `master` failing for `typescript_conditional_types`.

**Comment by vjeux** [comment]
If you are doing this change, you should also do it for `?.` operator.

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCGD8A6AhgCgEocDi8iSLyzSQAaECABxgEtoBnZUXAJ14gB3AAp8EXFLgBuEVgBN6IXBxjJUuADYc4DAEa9cYANZwYAZSaHWUAObIYvAK46QciGDWbtDa9t4xhAxsAW1xPLRcAKw4ADwAhA2NTM1xguAAZazhw70ZHGCZ8gCYcl0teP2QQXVxdAE8NaEUmXmsYAHV5GAALZAAOAAYGFohtdoMmKpa4Pylshl44AEdHVkXA3BCwpHUIhm1g1nsnFw5rGw04AEVHCHhShhhazrke5CLHg1YNc4BhCGCoSqUGg8xAjm0ABVahJdtoAL7woA)

**Input:**
```jsx
fooo?.a()?.a()?.a()?.a()?.a()?.a()
```

**Output:**
```jsx
fooo
  ?.a()
  ?.a()
  ?.a()
  ?.a()
  ?.a()
  ?.a();

```

**Comment by duailibe** [comment]
@vjeux I didn't read your message before merging the PR :(

**Comment by vjeux** [comment]
For context, there's a discussion in the PR and we actually can't have `?.` be on two different lines nor we can have `!.` be on the same. So that solves the styling debate :p
