### ISSUE TITLE
Add an option to end file with a newline

### ISSUE THREAD

**Issue by szeck87** [prettier/prettier#4054]
I've read through the docs, and I did read this: https://prettier.io/docs/en/rationale.html#empty-lines.  Specifically the part where it says

> Files always end with a single newline, though

It would be great if this was built into its own option so we could specify whether we want this behavior or not.  Sorry I can't get the playground to work, doesn't let me remove or insert code.

**Comment by j-f1** [comment]
Why do you want to avoid a newline at the end of the file?

**Comment by szeck87** [comment]
So it matches what linters do.  ESLint has https://eslint.org/docs/rules/eol-last

**Comment by duailibe** [comment]
@szeck87 Besides the ESLint thing, are there any other downsides in having a newline at the end of the file?

**Comment by szeck87** [comment]
There is no downside no, but it it would be better if it were an option versus forcing it.

**Comment by lydell** [comment]
Well, if there's no dowside there's no issue :)

**Comment by j-f1** [comment]
@szeck87 See also https://prettier.io/docs/en/option-philosophy.html.
