### ISSUE TITLE
Add title to the /en/users/

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#4062]
Users page should have a proper/different title: https://prettier.io/en/users/

<img width="267" alt="screen shot 2018-02-27 at 13 53 08" src="https://user-images.githubusercontent.com/125676/36727352-96e4e844-1bc5-11e8-8098-40dc5dd8080b.png">

**Comment by j-f1** [comment]
I can’t find a way to change the title with Docusaurus. Given that we’re not using most of the features of Docusaurus (translation and version support), would it make sense to use a more general-purpose static-site generator (like [Gatsby](https://www.gatsbyjs.org/))?

**Comment by lipis** [comment]
There was a discussion with @vjeux about translating the website, and TBH I like the simplicity of Docosaurus. There is no real need about switching to something else.

I also couldn't find a way to change the title, but I'm sure it's doable, otherwise we can open an issue and it will be eventually fixed in the [source](https://github.com/facebook/Docusaurus).
