### ISSUE TITLE
Ignored files are written to stdout during --debug-check

### ISSUE THREAD

**Issue by mthurlin** [prettier/prettier#4065]
Prettier 1.11.0 outputs the source of ignored files to stdout when running with --debug-check.

Reproduce by creating the following three files:

foo.js
`console.log("foo");`

bar.js
`console.log("bar");`

.prettierignore
`bar.js`

Then run prettier:
`prettier.js --debug-check "**/*.js"`

It will output the source of bar.js, instead of ignoring it.

It seems to be caused by:
https://github.com/prettier/prettier/blob/2cb9498ab67615f67ba5b431198d0f434f4ab282/src/cli/util.js#L338-L341
introduced in https://github.com/prettier/prettier/commit/2cb9498ab67615f67ba5b431198d0f434f4ab282

**Comment by duailibe** [comment]
This is the intended behaviour as per #3590. So maybe we should detect if it was passed a glob or a specific filename?

- if passed a glob, ignore the ignored files
- if passed specific filename, write the contents unchanged to output

I don't really know what should be the behavior here, this seems a little confusing to me :P

**Comment by mthurlin** [comment]
I agree that it is the intended behavior in regular usage, but **not** when running --debug-check.

**Comment by mthurlin** [comment]
#3590 mentions these two cases:

```
With --write, don't read or write to the ignored file
Without --write, read the ignored file and output as-is.
```

I'd argue there are three cases to take into account:
```
With --write, don't read or write to the ignored file
With --debug-check, don't check the ignored file
Without --write and --debug-check, read the ignored file and output as-is.
```

**Comment by duailibe** [comment]
Yeah, I agree

**Comment by mthurlin** [comment]
Thanks for the quick response and fix!

**Comment by duailibe** [comment]
@mthurlin no problem! Until this is released, you can install prettier directly from github if you need this fix asap

**Comment by mthurlin** [comment]
Thanks, but as I only needed to run with --debug-check once (before migrating my codebase), I just commented out the print statement directly in node_modules.
