### ISSUE TITLE
Flow: Intersection Types should be formatted similarly to Union types

### ISSUE THREAD

**Issue by IvanGoncharov** [prettier/prettier#4068]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYhCAQSgBMAhAQwCdsBePAgFUzgBloBzdqLz73ngDkKAWxwAybJSrMs-eX0VDRcANwAdKJvRYGEAPJVpdPbLZKBl-sLHYAPlOpmFPF5ZtqQAGhAQMMAEtoAGdkUGoqCAB3AAVqBFCUCgA3CACSbxAKYJhkADMKABtguB8AIyoKMABrOBgAZQwqgJ5kGCoAV1KQEggwfKKSnxaSqhgYyo4RCgHi7oArYIAPMkqauvqVVha4WaHfDpgMQ4AmPe6mqlHkEDKKMrRC6EyMKhaYAHV0mAALZAAOAAMPleEBKH0qGBurzgo2Sux8VDgAEcOgEkRMKFMZkgCnMfCURAE2p1usEWhxCnAAIodCDwc4+GD3L4kX7IE5MyoBQoUgDCEBE0xuUGgCJAHRKjHuiTxJQAvvKgA)

**Input:**
```jsx
type FooAndBar = FooTypeLongLongLongLongLongName & BarTypeLongLongLongLongLongName;

type FooOrBar = FooTypeLongLongLongLongLongName | BarTypeLongLongLongLongLongName;
```

**Output:**
```jsx
type FooAndBar = FooTypeLongLongLongLongLongName &
  BarTypeLongLongLongLongLongName;

type FooOrBar =
  | FooTypeLongLongLongLongLongName
  | BarTypeLongLongLongLongLongName;
```

**Expected behavior:**
Intersection Types should be formatted similarly to Union types:

```jsx
type FooAndBar = 
   & FooTypeLongLongLongLongLongName
   & BarTypeLongLongLongLongLongName;

type FooOrBar =
  | FooTypeLongLongLongLongLongName
  | BarTypeLongLongLongLongLongName;
```

**Comment by IvanGoncharov** [comment]
Duplicate to #3986

**Comment by j-f1** [comment]
Duplicate of #3986
