### ISSUE TITLE
Typescript: inconsistent/incorrect formatting of format strings

### ISSUE THREAD

**Issue by kmsquire** [prettier/prettier#4069]
**Prettier 1.11.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEA3AhgJwEtcAjdTAXkwHJqBuAHSnSzyNPQCZLNhMBrOAE8kNapgC+jKEwD0szAFEAHrgC2AB3IBGJm2Jk4PAAYASYPo5wJmc5cM27BA+kcXnVt-dfHp3o1Rm7uwOtsEu1mH+Xh6hTiGuUbGJ8RExCZGpnr5Mcgoq6lpGnHrJAZhB0UkZnAB0gkLpadXNWQ45UP4mbSnhVnUNTZ4twz2ZfXETvdEdeUqqmuQAzKUZ3VPj-gPCQ5NVxpgA1BVjuz50IAA0IBAaMITQAM7IoAT4EADuAAoECM8ouGwEEIABMriBcI8YMgAGa4VCPODXEj4XBgQQwADKGjRhCgAHNkDB8ABXJEgEEQMCw+GI654xH4GBfVH4tS4GkI8kAK0eygAQqj0RhMeo4AAZPFwTl0m4kmAaeWcGXknH4RnIEAwIQaOCPMBEO7gjREWAAdVBMAAFsgABwABmuJogiLNqI0mpNerg+Gw0uu+DgAEcSYRAyzcGyOUg4Vzroi1IQiaTyY88fj0ABFEkQeAq64wUgWkHW5CcAuowiodMAYQganZmqg0H9IBJiIAKqR-rHERIJEA)
```sh
--parser typescript
```

**Input:**
```tsx
let variable = '';
let variable2 = { key: '' };

// Example 1
variable = `${variable} ${variable} ${variable} ${variable} ${variable}`;
variable = `${variable} ${variable} ${variable} ${variable} ${variable} ${variable} ${variable} ${variable} ${variable}`;

// Example 2
variable = `${variable} ${variable2.key} ${variable} ${variable} ${variable}`;
variable = `${variable} ${variable2.key} ${variable} ${variable} ${variable} ${variable} ${variable} ${variable}`;

// Example 3
variable = `${variable} ${variable2.key} ${variable} ${variable} ` + `${variable} ${variable}`;
```

**Output:**
```tsx
let variable = "";
let variable2 = { key: "" };

// Example 1
variable = `${variable} ${variable} ${variable} ${variable} ${variable}`;
variable = `${variable} ${variable} ${variable} ${variable} ${variable} ${variable} ${variable} ${variable} ${variable}`;

// Example 2
variable = `${variable} ${variable2.key} ${variable} ${variable} ${variable}`;
variable = `${variable} ${
  variable2.key
} ${variable} ${variable} ${variable} ${variable} ${variable} ${variable}`;

// Example 3
variable =
  `${variable} ${variable2.key} ${variable} ${variable} ` +
  `${variable} ${variable}`;

```

**Expected behavior:**
```tsx
let variable = "";
let variable2 = { key: "" };

// Example 1
variable = `${variable} ${variable} ${variable} ${variable} ${variable}`;
variable = `${variable} ${variable} ${variable} ${variable} ${variable} ${
  variable
} ${variable} ${variable} ${variable}`;

// Example 2
variable = `${variable} ${variable2.key} ${variable} ${variable} ${variable}`;
variable = `${variable} ${variable2.key} ${variable} ${variable} ${variable} ${
   variable
} ${variable} ${variable}`;

// Example 3
variable =
  `${variable} ${variable2.key} ${variable} ${variable} ` +
  `${variable} ${variable}`;

```

**EDIT: with reference to [this comment](https://github.com/prettier/prettier/issues/4069#issuecomment-369048493), the suggestion below modifies the AST, and one of the goals of prettier is not to do this.  So please ignore this section and see above.**

~~Arguably, splitting on the format variable isn't very pretty (IMHO).  I'd rather see the first two examples formatted like the third, breaking the format string into multiple strings and joining them with `+`:~~

```tsx
## IGNORE THIS CODE BLOCK; SEE ABOVE
let variable = "";
let variable2 = { key: "" };

// Example 1
variable = `${variable} ${variable} ${variable} ${variable} ${variable}`;
variable = 
  `${variable} ${variable} ${variable} ${variable} ${variable} ` + 
  `${variable} ${variable} ${variable} ${variable}`;

// Example 2
variable = `${variable} ${variable2.key} ${variable} ${variable} ${variable}`;
variable = 
  `${variable} ${variable2.key} ${variable} ${variable} ${variable} ` +
  `${variable} ${variable} ${variable}`;

// Example 3
variable =
  `${variable} ${variable2.key} ${variable} ${variable} ` +
  `${variable} ${variable}`;
```

**Comment by ericanderson** [comment]
This is likely to be rejected. There is a goal that the AST must be equal before and after. This change breaks that. Prettier doesnt want to be responsible for changing the meaning of your code, even if its this subtle.

**Comment by suchipi** [comment]
As an FYI, not breaking a single identifier in a template string expression was a requested feature. However, I don't think anyone is perfectly satisfied with the way template strings are formatted yet.

**Comment by kmsquire** [comment]
>This is likely to be rejected. There is a goal that the AST must be equal before and after.

Okay, I edited the proposal above to ignore the suggestion to breaking up the string.

The section above that still contains a proposal which does not modify the AST, and removes the difference between splitting on `{variable2.key}` and `{variable}`).  Even if this proposal is not followed exactly, I feel these should be treated identically.

**Comment by ericanderson** [comment]
@kmsquire Now what you've reported looks like a genuine bug. Do you want to take a stab at fixing it?

**Comment by suchipi** [comment]
Before attempting to fix this... it has been discussed a lot before. Let me try to find the relevant issues.

**Comment by suchipi** [comment]
Here's some prior discussion: https://github.com/prettier/prettier/issues/3368
There is a suggested change on that issue as well.

**Comment by kmsquire** [comment]
> Now what you've reported looks like a genuine bug. Do you want to take a stab at fixing it?

I’ll take a look tomorrow and see what I can come up with (after looking at the discussion in #3368 that @suchipi pointed out). 

(BTW, the only edits I made were to remove the suggestion to break up the string. The rest of the report was there all along...)

Cheers!

**Comment by kmsquire** [comment]
I just looked at #3368, and this seems essentially to be a duplicate, so I’ll close this and post there about trying to tackle this (based on the proposal there), assuming no one else is working on it.

**Comment by j-f1** [comment]
Duplicate of #3368
