### ISSUE TITLE
Weird break on generic instead of putting whole function on new line

### ISSUE THREAD

**Issue by ericanderson** [prettier/prettier#4070]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAFQAsBLKAcz1oFsNC4WEYKB5GanGw16TYAB0oePABMISPAAoYATwxwFlNXACUeALwA+PAAVsEAG60ZQgDxmIGY-rxcWEWgC84i5doW8AEYAVnBgMFrqOgoOVjbYtrwYPM7GwAC+OgDckukgADQgjjC00KTIoMTY5gDuJlUI5SjEFh4yBSBkMMgAZsSEpHCFgdjEYADWcDAAyhhjosgw2ACuQyByYL39g4X0g7hmxAwsxFsDa8GkaABCoxNT08RcADL0cGc7RcswGN8ATB81nNsPtkCBVOpSGBsLRkh0MDDYAB1awCZAADgADIUERBBkjRhgwQi4PsLO9Ctg4ABHZa0KmHY6nJB9c6FQYsWiLFZrUiiDgARWWEHggMKMGIgRRMjRSD+4tGtEIogAwhAWCcwVBoBSQMtBpRJU1WYN0ukgA)
```sh
--parser typescript
```

**Input:**
```tsx
export class Thing implements OtherThing {
  do: (type: Type) => Provider<Prop> = memoize((type: ObjectType): Provider<Opts> => {});
}
```

**Output:**
```tsx
export class Thing implements OtherThing {
  do: (type: Type) => Provider<Prop> = memoize((type: ObjectType): Provider<
    Opts
  > => {});
}

```

**Expected behavior:**
```tsx
export class Thing implements OtherThing {
  do: (type: Type) => Provider<Prop> = memoize(
    (type: ObjectType): Provider<Opts> => {}
  );
}

```

Same number of lines, WAY easier to read

**Comment by kpdonn** [comment]
Heads up I opened PR #4228 that will fix this if accepted.
