### ISSUE TITLE
deprecated postcss parser no longer working

### ISSUE THREAD

**Issue by olsonpm** [prettier/prettier#4071]
The problematic commit is [dc26445](https://github.com/prettier/prettier/commit/dc26445e518dfc122810850fde23df449c8b7095)

I was unable to reproduce on the playground because this is a deprecated option, thus I created a [github repo](https://github.com/olsonpm/test-prettier) with reproduction instructions.

I looked a bit at the code but was pretty lost at the intent of what all was going on in that commit.  It would be helpful to have someone more familiar with the codebase take a look, though I will spend some more time myself tomorrow.

Workaround: `npm i prettier@1.10`

I noticed this issue when prettier-atom was unable to format my `*.scss` file - it still relies on the deprecated option.

Thanks so much again for this library

**Comment by suchipi** [comment]
This fix went out in 1.11.1

**Comment by olsonpm** [comment]
Oh nice - I checked a few hours back and didn't see a release pushed to npm.  This was taken care of very quickly - thanks so much :+1:
