### ISSUE TITLE
Released version of TypeScript parser is out of date

### ISSUE THREAD

**Issue by utatti** [prettier/prettier#4073]
**Prettier 1.11.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwBE44MAlOAQwBNoAbQgHgBUA+PAXjw5508KAwDOeOlEIBtALp4A-OUo16TKKwCC2bHXYcZUAK4BbAEZxscnkgFC0I8XgjmAVnDD5lFKrUYshADy7p4wnLYCANwgADQgEBgwAJbQYsigdLoQAO4AClkI6Sh0AG4QyQxxIHRiMMgAZnTMYnDx5npgANZwMADKGHRgyVAA5sgw2MZtIExgjc2t8SOtuHl6o6Z0Cy0zbmJoAEKdPf10pnAAMiNwO0sJxjAYjwBMdzOD2KvIIEQkYmBsMkktUMEDYAB1SowAAWyAAHAAGeJgiCtCF6DA-MFwValW7xbBwACOxmSRPWdE22yQTV28VapmSEymMzEI1GzDgAEVjBB4O94jA6OYoQxYcgXkK9MlmByAMIQUxbH5QaAEkDGVocEXFOmtAC+BqAA)
```sh
--parser=typescript
```

**Input:**
```typescript
export type DeepReadonly<T> = T extends any[] ? DeepReadonlyArray<T[number]> : T extends object ? DeepReadonlyObject<T> : T;
```

Actually, the snippet is copied from [tests/typescript_conditional_types/conditonal-types.ts](https://github.com/prettier/prettier/blob/master/tests/typescript_conditional_types/conditonal-types.ts). Because it neither works with Prettier 1.11.

**Output:**
```
SyntaxError: ';' expected. (1:33)
> 1 | export type DeepReadonly<T> = T extends any[] ? DeepReadonlyArray<T[number]> : T extends object ? DeepReadonlyObject<T> : T;
    |                                 ^
```

**Expected behavior:**

Parsing succeeds.

---

Concerning #4006.

I found that conditional type doesn't still work in Prettier 1.11, although a patch seems like merged and released.

For investigation, I cloned this repository, `reset --hard` to the tag `1.11.0` and build source with `yarn build`. As expected, I found that `dist/parser-typescript.js` is different from one installed by `npm i prettier@1.11.0`. I also confirmed that it works well when replacing `parser-typescript.js` with the built one. I guess `parser-typescript.js` included in 1.11 release wasn't built properly.

Can we have a quick fix for this as 1.11.1?

**Comment by ericanderson** [comment]
@suchipi thoughts?

**Comment by duailibe** [comment]
I guess something went wrong when building the production version?

**Comment by suchipi** [comment]
Yeah something must have gotten messed up...

**Comment by suchipi** [comment]
I'll make a 1.11.1 release.

**Comment by suchipi** [comment]
I released 1.11.1 with the correct TypeScript parser version. I think I forgot to remove my node_modules before building 1.11.0, and I must have not noticed the failing test. I did a `git clean -dfX; yarn install` first this time around and all seems good.

**Comment by j-f1** [comment]
@suchipi The checklist item in [`e5429d58`](https://github.com/prettier/prettier/wiki/Release-Checklist/_compare/1b2222e1a23d4fd8ec0840372356e7fbf08f5514...e5429d581ce6c5a1848dd4d135324ea53bf50bdb) should do the trick too.

**Comment by suchipi** [comment]
Looks like that item didn't make it into the checklist in https://github.com/prettier/prettier/issues/3931; maybe it hadn't been added yet. I guess next time we should link to that wiki page instead of copying the checklist into the issue?

**Comment by j-f1** [comment]
@suchipi That’s because I just added it :smile:

**Comment by suchipi** [comment]
Oh haha! Thanks :)

**Comment by utatti** [comment]
I've just tested with 1.11.1 and everything works without any problem.

Thanks for maintaining a great project.
