### ISSUE TITLE
SCSS lists/maps break with comments

### ISSUE THREAD

**Issue by jgerigmeyer** [prettier/prettier#4074]
**Prettier 1.11.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgTwLQBsCWAzjEgDpQAEFA5AGYQTUA0FA9KxQGIPlXUBGAQwBO1ANxsOAIRHlyGHOkEAHJBQAUvGvUZqAjC3ZcelGkNFqATIemyoASjEgmICMpj5ohZKBHCIAO4ACiII3iiCAG4Q+AAmziCCxMi0griEcC78woJgANZwMADKyrn4UADmyDDCAK6ZILEQYClpGS7lGcIwQTkVSq3pDQBWhAAeUjn5hUWC6HAAMuVwg+2utTDKG5arDaXCXcgghGCE3i7KwuUwAOpxMAAWyAAcAAwX-hk3OcpHl3BdSIrFzCOAAR1q+FBvUE-UEuxcGXQ+GqdQahHKFVwcAAirUIPAESAYIJ+HdYo9kNZiTl8ARKgBhCDoAYoKDQYEgWoZAAqpPCqSGAF8hUA)
```sh
--parser scss
```

**Input:**
```scss
$my-list:
  'foo', // Foo
  'bar'; // Bar

$my-map: (
  'foo': 1, // Foo
  'bar': 2, // Bar
);
```

**Output:**
```scss
$my-list: "foo", / / Foo "bar"; // Bar

$my-map: (
  "foo": 1,
  / / Foo "bar": 2,
  / / Bar
);

```

**Expected behavior:**

This is similar to #2686 (which has been fixed), but causes syntax errors when lists or maps include inline comments.

**Comment by suchipi** [comment]
Thanks for the report

**Comment by evilebottnawi** [comment]
Value parser don't respect `//` comments, i will send PR

**Comment by evilebottnawi** [comment]
Just information.
Need also tests:
```scss
$colors: (
    // Neutral Tints/Shades
    black: (
        primary: #242629,
        lighten-1: #333437,
        lighten-2: #4a4c51,
        lighten-3: #5a5e65
    ),
    white: (
        primary: #fafafa,
        darken-1: #efefef,
        darken-2: #c7cad0,
        darken-3: #979aa0
    )
)
```

**Comment by evilebottnawi** [comment]
About above example, we should rewrite all logic around `groups` :disappointed: Right now it is very difficult pretty output this structures. I will think how we can do with this. Help welcome :tired_face:

**Comment by ekfuhrmann** [comment]
Is it possible to maybe treat SASS maps like JSON for formatting?

**Comment by evilebottnawi** [comment]
@ekfuhrmann yes, but difficult need rewrite groups, i will send PR in this mouth, very busy and no many time on open source (need work for money :disappointed: )

**Comment by evilebottnawi** [comment]
PR fix comments: https://github.com/shellscape/postcss-values-parser
