### ISSUE TITLE
trailingComma setting is not respected in SCSS lists/maps.

### ISSUE THREAD

**Issue by jgerigmeyer** [prettier/prettier#4076]
**Prettier 1.11.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgTwLSQDYQBOAzkgAQAUAOlGWQOSFwAm9ANDXfQEZ4CucdjQCUAbhBsQEAA4wAltGLJQAQ0KEIAdwAKahEpQqAbhDnMJIFcRjIAZirzE4k7oRVgA1nBgBlae7koAHNkGEIBSWYIMDsHJ0lAp0IYbTcg9BVYx2cQACtiAA8AITdPbx8VdDgAGUC4LPipPhhpZoAmBpz-EjhCZBBiMGIlSWlCQJgAdTMYAAtkAA4ABlGNJ0m3aX6xuCSjeskmAEc+OSZUlXTMpHtsySd0OVDwnOJAoLw4AEU+CHhOyQwFTcabMObINqAtxyPDvADCEHQGX6DjwFj4TgAKsCDLcnABffFAA)
```sh
--parser scss
--trailing-comma all
```

**Input:**
```scss
$my-colors: (
  'red',
  'blue',
);
```

**Output:**
```scss
$my-colors: (
  "red",
  "blue"
);

```

**Expected behavior:**

This might be intentional, but is there a reason why the `trailingComma` setting isn't respected in other-than-JS languages (e.g. SCSS)?

**Comment by suchipi** [comment]
It probably should be respected; I think this was just an oversight.

**Comment by evilebottnawi** [comment]
@jgerigmeyer @suchipi we decided add trailing in scss, yes it is easy, but we should discuss this

**Comment by suchipi** [comment]
Are we already using the trailing comma anywhere else in the SCSS printer? I thought we were

**Comment by evilebottnawi** [comment]
@suchipi scss can have trailing comma only in maps/list, css/less can't support this. For consistently we decided adding trailing comma anywhere in css/less/scss, but i am open to improve this. 
@jgerigmeyer Can you provide link on popular styleguide where used trailing comma

**Comment by suchipi** [comment]
To clarify, you meant that for consistency, we decided *not* to add a trailing comma anywhere in css/less/scss?

**Comment by evilebottnawi** [comment]
@suchipi yes

**Comment by evilebottnawi** [comment]
@suchipi let's leave issue open to discission

**Comment by lipis** [comment]
Would be nice to add them and respect the setting if supported.

**Comment by jgerigmeyer** [comment]
The clearest SCSS styleguide I'm aware of that mentions trailing commas is Hugo Giraudel's "Sass Guidelines":

- https://sass-guidelin.es/#lists
- https://sass-guidelin.es/#maps

But regardless, I think trailing commas in multiline maps/lists is a common standard for most languages where there's support, given the advantages for adding/removing/reordering items.

**Comment by evilebottnawi** [comment]
@jgerigmeyer sound reasonable

Let's do it :+1:

**Comment by j-f1** [comment]
Labelling as a feature since the current output is valid SCSS.

**Comment by ad1992** [comment]
@j-f1  can I take this up ?

**Comment by j-f1** [comment]
Sure, go ahead @ad1992!

**Comment by ad1992** [comment]
@j-f1  please look into https://github.com/prettier/prettier/pull/4317
