### ISSUE TITLE
computed class members are indented 

### ISSUE THREAD

**Issue by mohsen1** [prettier/prettier#4079]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgKKxwBOADkQJaZwCKAruquTAJ4DCG2OwAOlNzCVoAjRmBwAzCBCQ4AjAAZ5Abl79BI8mKHoiMgEwq+A4aIlTtRHAF4cvHPYf8A9E5wB3ODgDmcGGYg46FAAJjgAtrSoMOQkqMw4QvEAzHYO9vwwABaUAHSSAQBUOEk4ANSpac6uWQiBwaEWgSHhkdGx8Yk4AJzyONFhnvk4sbS4ehWOMAAUWbmNRT0AlDhFM9mYeVJlOHqLE+kwvAC+IAA0IBAk0dCYyKA6RBBuAAo6CLco6ABuEOTBZyAsDBkOIGFRzkIiOgwABrXwAZRI0PIUC8yBgRFocHOwQgYBBYOxIBRVCIMGeUK8YXQBNQ4JAACtMAAPABCUNhCPQAwAMii4LT6RBaMYYHpBUSkURScgQCwSHBMGAKFcAWQUTAAOp-LLIAAc8nOZAgVE1UJIsrIiuIXwF5yIcAAjrRyA6KegqTSkKC6USqGFyOjMX6UV5UDRaBB4BLzjB0EJtcFdUg9LGoeRGKjWBAwtTZVBoHaQKM4AAVeMfH1UI5HIA)

**Input:**
```tsx
class EnterpriseQualityClass {
	public foo: 100;
	public bar: 2;
	public foobar = 
      	// we get foo and multiply by 3
      	this.foo * 3 +
      	// then add bar and multiply by 90 time foo plus 2
      	(this.bar * 90) * (this.foo + 2)
      	
}
```

**Output:**
```tsx
class EnterpriseQualityClass {
  public foo: 100;
  public bar: 2;
  public foobar =
    // we get foo and multiply by 3
    this.foo * 3 +
      // then add bar and multiply by 90 time foo plus 2
      this.bar * 90 * (this.foo + 2);
}

```

**Expected behavior:**
I was not expecting line 7 (comment `// then add...`) to be indented. 
```tsx
class EnterpriseQualityClass {
  public foo: 100;
  public bar: 2;
  public foobar =
    // we get foo and multiply by 3
    this.foo * 3 +
    // then add bar and multiply by 90 time foo plus 2
    this.bar * 90 * (this.foo + 2);
}
```

Is this expected behavior?

**Comment by duailibe** [comment]
I think this is a bug, it doesn't happen with regular variable assignments, but it's not related to typescript, but to class properties:

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgKKxwBOADkQJaZwCKAruquTAJ4DCG2OwAOlNzADMIEAEboiOALw5eOOfP4B6RTgDucHAHM4MHEIg50UACY4AtrVQxyJVMxwj7AZlny5-GAAtKAOn04AKhwnHABqVzclFS8EQ2NTMQkjUwsrGzsHewBOAAYcazMNf1taXAAmCIUYAAovX0TAnFyASkba70w-YTCcMubK9xheAF8QABoQCBJraExkUHEiCFUABXEEOZR0ADcIcmNxkCwYZAEGKgmRInQwAGsdAGUSG-IoTWQYIlo4CeMIMFO5x+IFeVCIMBW100ZnQgNQFxAACtMAAPABC1zuj3QhQAMq84HCERBaDASKSykTgc8iGDkCAxI5UNBDmRXjAAOr7LzIAAcOQmZAgVA51xI9LIcDB20JEyIcAAjrRyPLIehobCkGd4cCqGZyB8vrrXppUDRaBB4FSJjB0CIucYeUgyjbruRGG9WBAzDD6VBoLKQKU4AAVO2bbVUYbDIA)

**Input:**
```jsx
class EnterpriseQualityClass {
	foobar = 
      	// we get foo and multiply by 3
      	this.foo * 3 +
      	// then add bar and multiply by 90 time foo plus 2
      	(this.bar * 90) * (this.foo + 2)
      	
}
```

**Output:**
```jsx
class EnterpriseQualityClass {
  foobar =
    // we get foo and multiply by 3
    this.foo * 3 +
      // then add bar and multiply by 90 time foo plus 2
      this.bar * 90 * (this.foo + 2);
}

```

**Comment by j-f1** [comment]
For reference, outside of a class:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBTohASk2AB0pNNIoBnGTAIwEMAnTAXjIooHpvMB3OJgDmcOngiZGUACaYAtgFcANjFQAHZQE8GOgMycuMABapqAOgmYAVJj2YA1IZ58TCKTLlNW0uUtUa2rqYAJwADJhq8kJWmorUmABMzpGmFt42oRG22CZmlviOSQQA3GQAviAANCAQ6mrQ1MigLMwQ-AAKLAhNKIwAbhCoMtUgjLTI6IzK1HA19MyMYADWYgDK6kuoUMLIMMyKcyAyEGCT07M127PMMB2LwvKM5zNHAFbUAB4AQosr64xogAZbZwF6XWqKGDqKGJcFHTbMG7IEBMehaZTQUbqZjbGAAdWGJmQAA4wjUcRBZvjFuoUTi4Dd+mCasw4ABHRSoNn3RiPZ5IKavGqzeSoPYHI7UbbCZRwACKigg8HhNRgjHohJkxKQiTVi1QyhlAGEIPIniioNAWSB4nAACoa3pC2blcpAA)

**Input:**
```jsx
if (foo) {
  const bar =
    // we get foo and multiply by 3
    this.foo * 3 +
    // then add bar and multiply by 90 time foo plus 2
    this.bar * 90 * (this.foo + 2);
}
```

**Output:**
```jsx
if (foo) {
  const bar =
    // we get foo and multiply by 3
    this.foo * 3 +
    // then add bar and multiply by 90 time foo plus 2
    this.bar * 90 * (this.foo + 2);
}

```
