### ISSUE TITLE
Comments are indenting on every format

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#4080]
**Prettier 1.11.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAzgDwDpSRRYwAEAYhBKQLykAUAlLQHynAGmkBOcMArtygNOXUgB4AJgEsAbi1Fj2AegBUipaQAqAC2lZSAG2lQA1gZjUAhqQAOVgOZxSMHVbKSIcA1AhkAnnykcDj6MAB0GlyqygC+SlESOtykygrCYuLKMvKijADcBLGFUOioBCAANCAQtjDS0FjIoFbc3BAA7gAKrQhNKFayENKSVSBWJMgAZlaGWHDVAEbcVmCmfADK9mAmDsgw3PwLIJ5g07Pz1Sbz3DBdKw4Atlbnc8fYOABCK2ubVo9wAAyJjgr0uNX4MFskIATPtDsd7NwbsgQM9uKZPB0oGNbNwTDAAOojVzIAAcAAZqniIPNCStbKi8d44NxZKDqrwAI78aS8e6OZ5g47zR7SeFHapYXaGOAARX4flBSBmb2qMCsi2JklJSBh6pW0mMUAcAGEII8hShfFAOSB+PMtJr+qr5rFYkA)
```sh
--parser markdown
```

**Input:**
````markdown
```jsx
const Foo = () => {
  return (
    <div>
      {/*
        This links to a page that does not yet exist.
      */}    
      <hr />
    </div>
  );
};
```

````

**Output:**
````markdown
```jsx
const Foo = () => {
  return (
    <div>
      {/*
              This links to a page that does not yet exist.
            */}
      <hr />
    </div>
  );
};
```

````

**Second Output:**
````markdown
```jsx
const Foo = () => {
  return (
    <div>
      {/*
                    This links to a page that does not yet exist.
                  */}
      <hr />
    </div>
  );
};
```

````

**Expected behavior:**

Unchanged

**Comment by j-f1** [comment]
Note that this **doesn’t** happen with a regular JSX file:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAxCFMC8mAFAJSEB8mwAOlJpgE5wwCuj9xdDDAPACYBLAG4VuPBsAD0AKnESGAFQAWgtJgA2gqAGt1MfAENMAB0MBzOJhjLDWfhDjqoELAE8WmOAA81MAHTyPDJSAL4SQXzKjJhSYvQ8vFJCouKkANx0oZlQIAA0IBAmMILoyKCGjIwQAO4ACpUIaMgghsIQgvz5rRjIAGaGGmhwBQBGjIZgOiwAymZg2ubIMIysIyAOYP2DwwXaw4wwdRPmALaG20PrAFZo3gBCE1OzhqdwADLacJe7hawwJn+ACZlqt1mZGAcWqNDKM3BpoN0TIxtDAAOqdGzIAAcAAYCsiIMM0RMTC1kU44IxhN8CswAI6sQTMY4Wc4-dbDU6CUFrApoRYaOAARVYrm+SAGVwKMFhGP4WKQQJlE0EWig5gAwhBTuyUC4oLSQKxhopYc1JTs4KFQkA)

**Input:**
```jsx
const Foo = () => {
  return (
    <div>
      {/*
        This links to a page that does not yet exist.
      */}    
      <hr />
    </div>
  );
};

```

**Output:**
```jsx
const Foo = () => {
  return (
    <div>
      {/*
        This links to a page that does not yet exist.
      */}
      <hr />
    </div>
  );
};

```

**Comment by ericanderson** [comment]
Nice find
