### ISSUE TITLE
CLI behaves differently on Windows (doesn't work) than on Linux

### ISSUE THREAD

**Issue by sandrosc** [prettier/prettier#4086]
A friend and I found this bug when the prettier command worked on his Mac, but not on my Windows laptop.

If I use the Linux subsystem for Windows prettier works:

```bash
C:\git\core>yarn lint
yarn run v1.3.2
$ prettier 'lib/**/*.ts' 'spec/**/*.js' --write && tslint -c tslint.json 'lib/**/*.ts'
[error] No matching files. Patterns tried: 'lib/**/*.ts' 'spec/**/*.js' !**/node_modules/** !./node_modules/**
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\git\core>bash
sandro@R:/mnt/c/git/core$ yarn lint
yarn run v1.3.2
$ prettier 'lib/**/*.ts' 'spec/**/*.js' --write && tslint -c tslint.json 'lib/**/*.ts'
lib/blackbox/getRandomValues.ts 594ms
[...]
Done in 4.20s.
sandro@R:/mnt/c/git/core$
```

**Comment by j-f1** [comment]
Does running

```
C:\git\core>prettier 'lib\**\*.ts' 'spec\**\*.js' --write
```

work for you?

**Comment by evilebottnawi** [comment]
@j-f1 
> !**/node_modules/** !./node_modules/**
Without quotes?

**Comment by j-f1** [comment]
I think those are the built-in ignores. It doesn’t matter that they’re not quoted since they aren’t parsed by the shell AFAIK.

**Comment by sandrosc** [comment]
@j-f1 no, following output:

```bash
C:\git\tichu-core>yarn lint
yarn run v1.3.2
$ prettier 'lib\**\*.ts' 'spec\**\*.js' --write && tslint -c tslint.json 'lib/**/*.ts'
[error] No matching files. Patterns tried: 'lib\**\*.ts' 'spec\**\*.js' !**/node_modules/** !./node_modules/**
error Command failed with exit code 2.
```

**Comment by MarkTiedemann** [comment]
Single quotes don't identify strings in Windows `cmd.exe`.

A common mistake is `git commit -m 'Initial commit'`, which will be interpreted as two words: "`'initial`" and "`commit'`", thus ruining your commit message in this example.

So, to make the prettier work on Windows and Unix systems well, just use double quotes. :)

You must escape the double quotes in your `package.json` script, however:

```json
{
  "scripts": {
  ‎  "format": "prettier --write \"lib/**/*.ts\""
  ‎}
}
```

Hope this helps!

**Comment by sandrosc** [comment]
Thank you very much, @MarkTiedemann! 
Replacing `'` with `\"` indeed solved my problem.

**Comment by sandrosc** [comment]
Perhaps this would be worth documenting over at https://prettier.io/docs/en/cli.html?

**Comment by sandrosc** [comment]
@j-f1 yes, this issue can be closed. Thanks for the help!
