### ISSUE TITLE
Dangling chained property

### ISSUE THREAD

**Issue by jasonkuhrt** [prettier/prettier#4094]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqBmEBOqAUkUAzjKnACYDmcqEm51cxAlKsADpQYZGmoBDCgCsBYBGACeAYQgBXWKgC8jGgDoKAmALVzicHMVkKYXHuj5kIMABYGAQjgFQKxAOoBLWwBUbH4gCCImISMvKKKgDyAEbCcGAwagBuAgA2csz4lOowEGrZzCxm5uhqqQhUtsU8BRpaOjAUAJIUmADKkDi0KjCYLZj41eZCouJQUsawADRDPMRyALZBo6GTMMQz3CWoudqpjs6um9t0tg5OLu5eNr7+yyHjYSbH5kVb6AC+IFMgEAAOMA80GIyFAAhwOAgAHcAArghAglACJIQDwUb4gASkZCYNL6H7RJxgADWcBgbT+Yg8UCoyBgOAyPwoEDAOLxcB+1P0OBgMKcVAWAjZqXxIGExAAHgcSWS2gIFnAADLUuDC0XyGB-OQwABMao5IEphgMyBA0QE0UkqWgGL+OGpME8FFsyAA7ABWH52iD6NxOP6mu3MAxJVU-LoARzkHi6fIEAqFSFxIoN+gWHn1P2I1Ko5QAinJrKqk+yftpok6XUgdWWnB5UjnZAtBaa0qkMXo4N4LYj6RkPh8gA)
```sh
--print-width 75
--no-semi
--trailing-comma all
--use-tabs
```

**Input:**
```jsx
    for (const edge of edges) {
      const adjacencyCount = edge.data.usersCount
      const otherBrandsWithThisAdjacencyCount = Object.values(edge.to.edges)
        .length
      edge.data.tdIdfScore = tfIdf(
        adjacencyCount,
        sumAdjacencyCounts,
        totalBrands,
        otherBrandsWithThisAdjacencyCount,
      )
    }
```

**Output:**
```jsx
for (const edge of edges) {
	const adjacencyCount = edge.data.usersCount
	const otherBrandsWithThisAdjacencyCount = Object.values(edge.to.edges)
		.length
	edge.data.tdIdfScore = tfIdf(
		adjacencyCount,
		sumAdjacencyCounts,
		totalBrands,
		otherBrandsWithThisAdjacencyCount,
	)
}

```

**Expected behavior:**

Would have preferred:

```js
for (const edge of edges) {
	const adjacencyCount = edge.data.usersCount
	const otherBrandsWithThisAdjacencyCount = 
          Object
              .values(edge.to.edges)
              .length
	edge.data.tdIdfScore = tfIdf(
		adjacencyCount,
		sumAdjacencyCounts,
		totalBrands,
		otherBrandsWithThisAdjacencyCount,
	)
}
```

**Comment by j-f1** [comment]
Minimal repro:
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQGcIC2cMAFqlAOYCUmwAOlJppFLjJhKXAE4BC3AQygATXAHVUpACplcAQWEArAWARgAngGEIAV1iYAvJgDyAI0VwwMAHQA3AQBsdcXNjjCKcazAjX3n3CprBwQKUgYAXxAAGhAIAAcYVGhcZFABbm4IAHcABQyEVJQBWwhUYRiQATZkdEdcOFjTQTAAa2IAZXiVcgpkGG5nWOEIMFr6xrRWHhhcwQoCAXGHBtjFXAAPfhV2mA6BIgAZcjhl1bidGHjLgCYzye7uBu5kEFMBU3UHaEr47nIYBJhKRkAB2ABssT+EAaYkE8VefxcPFsp1i3DgAEcdKgMXMBAslkg6itJg0CKh+oMyb0QgBFHScU7EiaxGAfIEgpA3NmCVAOXraAiLV6OByVHQNKQfIokhoRCJAA)
```sh
--print-width 76
--trailing-comma all
```

**Input:**
```jsx
if (something) {
  const otherBrandsWithThisAdjacencyCount = Object.values(edge.to.edges).length
}
```

**Output:**
```jsx
if (something) {
  const otherBrandsWithThisAdjacencyCount = Object.values(edge.to.edges)
    .length;
}

```

**Comment by suchipi** [comment]
I think this is because we're detecting Object.values as a "factory function". I would argue it's intended behavior.

**Comment by ericanderson** [comment]
I disagree with the OPs expected. I would expect this:
```js
if (something) {
  const otherBrandsWithThisAdjacencyCount =
    Object.values(edge.to.edges).length;
}
```

Worse, if we pretend length is a function we get the following from prettier:
```js
if (something) {
  const otherBrandsWithThisAdjacencyCount = Object.values(
    edge.to.edges
  ).length();
}
```
which I would think would be more consistent:
```js
if (something) {
  const otherBrandsWithThisAdjacencyCount =
    Object.values(edge.to.edges).length();
}
```

**Comment by lydell** [comment]
There's at least one issue open about breaking after `=` in assignments. Couldn't find it right now though.

**Comment by bakkot** [comment]
@lydell, you're probably thinking of #2482.
