### ISSUE TITLE
Markdown formatting inside html files

### ISSUE THREAD

**Issue by inakianduaga** [prettier/prettier#4095]
Prettier already formats JS `<script>` tags inside html files. 

It would be great if support for inline markdown

```html
<script type="text/markdown">
... some markdown here
</script>
```
 would be added, so adding inline markdown would be formatted correctly. 

this is very useful for example for JS presentations using RevealJS or RemarkJS where you want to have the whole presentation in a single html file but most of the content is actually markdown.

**Comment by kylecordes** [comment]
Indeed this would be a very nice feature to have. So far I have not found any automatic HTML formatter which does not destroy markdown  inside the HTML.
