### ISSUE TITLE
Remove deprecated options

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#4097]
The `--flow-parser` and `--parser postcss` options are deprecated. Let’s remove  them 🔥 

Let’s also search for other deprecations in the code base and get rid of them too.

**Comment by thorn0** [comment]
What exactly are we going to remove in 2.0? Only `--flow-parser` and `--parser postcss`?

**Comment by sosukesuzuki** [comment]
I don't think `getSupportInfo` need to return removed features after 2.0.

**Comment by sosukesuzuki** [comment]
options we should remove in 2.0:

- `--flow-parser`
- `--parser=postcss`
- `--parser=babylon`
- `true` and `false` for `proseWrap`
- `true` and `false` for `trailingComma`

Is there any other?

Also, we need to discuss the specification of `getSupportInfo` after 2.0 as @thorn0 says.

**Comment by fisker** [comment]
TODO comments in codebase: 

- parser `typescript-eslint`
- parser `markdown`
- api `prettier.utils.mapDoc`

see PR: #6993

**Comment by thorn0** [comment]
The `markdown` parser is documented and not even deprecated. On the other hand, `remark` never was documented. That TODO seems to express just an intent to rename `markdown` → `remark` sometime. But if we really want to go that way, it should be done gradually like it's been done with `babylon` → `babel`. I doubt we want to though. What for?

**Comment by fisker** [comment]
I've send all PR on them

- [ ] `--flow-parser` (#7511)
- [ ] `--parser=postcss` (#7535)
- [ ] `--parser=babylon` (#7533)
- [ ] `true and `false` for `proseWrap` (#7536)
- [ ] `true` and `false` for `trailingComma` (#7536)

**Comment by thorn0** [comment]
One more thing to remove: `--stdin`. https://github.com/prettier/prettier/issues/4559

**Comment by thorn0** [comment]
All the PR have been merged.

**Comment by fisker** [comment]
@thorn0 Could you check does this need clean? https://github.com/prettier/prettier/search?utf8=%E2%9C%93&q=redirect&type=

**Comment by thorn0** [comment]
We'll need this if we deprecate options in the future.

**Comment by fisker** [comment]
We don't need old values anymore, since we remove version support in `getSupportInfo`,if we change some value later we can just do if/else. We don't need that `redirect`.
