### ISSUE TITLE
Prettier shouldn't convert exported variable names to lowercase in scss

### ISSUE THREAD

**Issue by dfdeagle47** [prettier/prettier#4110]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZcAeAHCAnGACYAHSjzwFsBPAYQgBsck9s4ATAbmIF8QAaECDDACW0AM7JQAQ2zYIAdwAK0hOJSSAbhCEteISaJjIAZpNqi4fAEbZJYANZwYAZQy2hUAObIY2AK4WQFggwY1NzPndzXAUbDzJJULMAgCtRNAAhG3tHJ0kyOAAZdzhE8P5fGAwKgCZSgNdsKOQQUTBRcT4MbHcYAHVtGAALZAAOAAZO2XNemwxmrrgo9RK+ZgBHXyFmGMk4hKQTJL5zMiFvPwDRdw9aOABFXwh4Or4YSUt+liHkatebIVo1xoZHizSg0BWIF85gAKu9VIdzJxOEA)
```sh
--parser scss
```

**Input:**
```scss
:export {
  myColor: red;
}
```

**Output:**
```scss
:export {
  mycolor: red;
}

```

**Expected behavior:**
Exported variable names shouldn't be lowercased (or changed in any way). We're using css-modules with webpack and the scss variables are required by jsx files as
```
import { myColor } from './component.scss';
```

Changing the name of the exported variable will break the import in the jsx file.

**Comment by evilebottnawi** [comment]
@dfdeagle47 what is? css modules ? or what?

**Comment by dfdeagle47** [comment]
[css-modules](https://github.com/css-modules/css-modules) allows to easily share/require variables and class names from the scss to the jsx files.

When running prettier on the scss file, it changes the exported variable name from `myColor` to `mycolor`.

**Comment by evilebottnawi** [comment]
@dfdeagle47 why do you use `:export` directly?

**Comment by dfdeagle47** [comment]
We have some variables that must be shared between the scss file and the js file. I guess our use case is pretty specific, and it might not affect a lot of people, but I think prettier should only be concerned with formatting and shouldn't make changes that might break the code.

**Comment by evilebottnawi** [comment]
Ok, let's wait other opinion.

For information, we should ignore also `:import`:
```
:import("path/to/dep.css") {
  localAlias: keyFromDep;
  /* ... */
}
:export {
  exportedKey: exportedValue;
	/* ... */
}
```

**Comment by j-f1** [comment]
I think we should format both of these since they have a usecase.

**Comment by LordCHTsai** [comment]
It's also a case in the project I am working on. I tried to keep color variables in one place (`scss` file), and the chart library we use requires the color code input as a javascript string. I use [css-modules](https://github.com/css-modules/css-modules) to import variables from `scss` file, but then all variables name become lowercase from camelCase after running Prettier. :(
Now I use prettier-ignore as a workaround
```
/* prettier-ignore */
:export {
  ...
}
```
Would be happy to see this as a config option.

**Comment by Coobaha** [comment]
@evilebottnawi I am not sure but custom selectors are not fixed?

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABMBXAzjCBbAWizgBs4xcAnAAiQILAEM9SBhR46gOjwE8GsWIqXJUA3AB0oUug2ZsOcasCnVIJCJSTVKcACaSoAXykgANCAgAHGAEtoWZKCuVbsAOq29MABbIAHAAMFjCMAEae3n5IAEwWWG4A5mQAihgQ8MgAZowkxCGUjLYkSaz4eIzIIFDQcOYgYYVgANZwMADKVoxgScgwlBhwFgBWWAAeAEJNrR3yADJudUg5eUMgXZTElFVggvXEeLZ9A2vYcAAq4Y7LufkgblswAAqFiRXZt2u6AI4YtrovRhvSo3VYWFwQYjuQpWKouOBbABudQsjEolAgAHcnmiENcQIxERAvPU9BAwB8wQScJS7hAMDArAyYrS4EYjEA)

**Comment by evilebottnawi** [comment]
@Coobaha Thanks for issue, can you create new issue?

**Comment by Coobaha** [comment]
@evilebottnawi done #4254

**Comment by thedamon** [comment]
This caused another issue where prettier broke code, which is against the whole mantra.
It's not well-documented but using `:export` to share css variables with js is a really awesome functionality.
Is there documentation about how exactly prettier renames variables in scss? It's broken code many times on us, and it would be nice to have an option to turn it off.

**Comment by duailibe** [comment]
@thedamon Prettier should not rename variables in scss. If it is, it's a bug, please open an issue.

**Comment by duailibe** [comment]
@thedamon You can try the playground (https://prettier.io/playground) which uses the latest release (1.12.1) to see if the issue still affects you.
