### ISSUE TITLE
TypeScript: typing constructor breaks

### ISSUE THREAD

**Issue by NaridaL** [prettier/prettier#4111]
Sometimes it is necessary to type the "constructor" prop of the instance of a class.

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOZOA5JFJjAE4CuYMEdFSOMAngA5wQAzfCXI5a6GAEswOAGIQIACgCUhEaPJ04MBnVJQ4Ad3wr1ZAL4lLUEtVo50OALw4DxvKajoAdHfpMWOm95JWUQABoQCB4paExkUHQ6OghDAAUkhHiUdAA3CEkAEwiQLBhkAXRUTDhIgCM6dDAAa20AZR4mySgAc2R-WpBCiDAKqprI7pq6GDTGnoBbdDHqwYArTAAPACFGlvb0BbgAGW64FYmohhgea4AmC8HOumnkEDr0Oq5UaBKeOm6MAA6kUYAALZAADgADJF-hAakDGjw3v84NNcudIloAI4MSRaOboRbLJCVVaRGoLST9RiDTDdHqoOAARQYEHgj0iME+IMK4OQd25jUkqEZAGEIAslm8oNAsSAGDUACqfbLkmrmcxAA)

**Input:**
```jsx
class A {
    'constructor': typeof A
    static Foo() {
        return new A()
    }
}

const a = new A()
a.constructor.Foo()
```

**Output:**
```jsx
class A {
  constructor: typeof A;
  static Foo() {
    return new A();
  }
}

const a = new A();
a.constructor.Foo();

```

**Expected behavior:**
Quotes around `constructor` should not be removed, as the current behavior leads to `constructor implementation missing` and removing the type declaration leads to `Foo` does not exist on type `Function` in `a.constructor.Foo()`

See [typescript playground](https://www.typescriptlang.org/play/#src=%2F%2F%20prettier%20input%3A%0D%0Aclass%20A%20%7B%0D%0A%20%20%20%20'constructor'%3A%20typeof%20A%0D%0A%20%20%20%20static%20Foo()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20A()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20A()%0D%0Aa.constructor.Foo()%0D%0A%0D%0A%0D%0A%2F%2F%20prettier%20output%3A%20(names%20changed%20to%20avoid%20conflicts)%0D%0Aclass%20A_Prettier%20%7B%0D%0A%20%20%20%20constructor%3A%20typeof%20A%0D%0A%20%20%20%20static%20Foo()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20A()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a_prettier%20%3D%20new%20A_Prettier()%0D%0Aa_prettier.constructor.Foo()) for errors caused

**Comment by duailibe** [comment]
FYI this looks like a bug in TypeScript to me, but if you need to preserve quotes, you can use a computed property:

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOZOA2gOSRSYwBOArmDBA1QLpI4wCeABzgQAZvhLkc9dDACWYHADEIEABQBKQhMnkGcGEwakocAO74N2sgF8StqCVr0c6HAF4cJ83ktR0AOidGFjYGf2U1dRAAGhAIATloTGRQdAYGCFMABTSEZJR0ADcIWQATGJAsGGQRdFRMOFiAIwZ0MABrfQBlATbZKABzZGDGkFKIMBq6htj+hoYYLNaBgFt0KfrRgCtMAA8AIVaO7vQVuAAZfrgNmbimGAF7gCYb0d6GeeQQJvQmvlRoBUBAx+jAAOplGAAC2QAA4AAyxYEQBpg1oCL7AuDzQrXWJ6ACOTFkeiW6FW6yQtU2sQaK1kw2Yo0w-QGqDgAEUmBB4K9YjBfhDStDkE9+a1ZKhWQBhCArNZfKDQPEgJgNAAqv3y1Ia1msQA)

**Input:**
```jsx
class A {
    ['constructor']: typeof A
    static Foo() {
        return new A()
    }
}

const a = new A()
a.constructor.Foo()
```

**Output:**
```jsx
class A {
  ["constructor"]: typeof A;
  static Foo() {
    return new A();
  }
}

const a = new A();
a.constructor.Foo();

```

**Comment by lydell** [comment]
@duailibe I don't know TypeScript very well, but are you sure this issue should be closed? It sounds like Prettier broke the code, which Prettier should never do.

**Comment by duailibe** [comment]
I don't know TypeScript at all so I'll reopen.

It seemed to me this is a bug in TypeScript that `constructor: type of A` is different than `'constructor': typeof A`. Even if it's not, I don't think Prettier broke the code.

**Comment by duailibe** [comment]
It's like saying Prettier breaks the following code:

```js
// input
const foo = {
  'bar': 'value'
};
console.log(foo['bar']);

// output
const foo = {
  bar: 'value'
};
console.log(foo['bar']);
```

because uglify/GCC will now mangle the `bar` key (for reference, #1103).

**Comment by NaridaL** [comment]
I've updated the link to the typescript playground. The first section is the input which has no errors. The second part is the prettier output, which now has errors.

**Comment by duailibe** [comment]
@NaridaL and here it is working with my proposed workaround: [typescript playground](https://www.typescriptlang.org/play/#src=%2F%2F%20prettier%20input%3A%0D%0Aclass%20A%20%7B%0D%0A%20%20%20%20'constructor'%3A%20typeof%20A%0D%0A%20%20%20%20static%20Foo()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20A()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20A()%0D%0Aa.constructor.Foo()%0D%0A%0D%0A%0D%0A%2F%2F%20prettier%20output%3A%20(names%20changed%20to%20avoid%20conflicts)%0D%0Aclass%20A_Prettier%20%7B%0D%0A%20%20%20%20constructor%3A%20typeof%20A%0D%0A%20%20%20%20static%20Foo()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20A()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a_prettier%20%3D%20new%20A_Prettier()%0D%0Aa_prettier.constructor.Foo())

**Comment by lydell** [comment]
@NaridaL Can you post a link to some TypeScript docs for this thing?

**Comment by NaridaL** [comment]
@lydell The issue which discusses this https://github.com/Microsoft/TypeScript/issues/3841#issuecomment-337560146 ...lol.

**Comment by NaridaL** [comment]
@duailibe Sure, but should prettier require prettier-specific workarounds? I guess this TS could also be considered a bug in TS ...

**Comment by duailibe** [comment]
@NaridaL well, class properties `"foo": type` and `foo: type` should be semantically the same. Other tools are considering them to be different... I'm not sure what you mean by "prettier require prettier-specific workarounds"

**Comment by lydell** [comment]
Thanks. I read through that issue, but I don't really understand what's going on. Let's leave this open until things get clearer on the TypeScript side.

**Comment by ericanderson** [comment]
It seems in typescript `constructor` is a keyword, so it makes sense why the quotes are currently needed. It also makes sense that this could be a bug in typescript.

That said, the spec for typescript is typescript, and we are converting valid typescript to invalid typescript.

If we follow the principle of least astonishment, then prettier shouldn't break this.

But also, in the giant typescript code bases I work with, I have never seen a real need for the syntax presented by OP (not to say it isnt needed sometimes, but its probably a low percentage of code) and thus the work around might be acceptable.

In essence, I have helped not at all ;)

**Comment by lipis** [comment]
Low percentage of code or not.. Prettier shouldn't break a valid code. Period.

**Comment by lipis** [comment]
Is there any other keyword that could break it?

**Comment by ericanderson** [comment]
None that I know of

**Comment by thorn0** [comment]
Doesn't happen anymore, at least with the `typescript` parser.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOZOA5JFJjAE4CuYMEdFSOMAngA5wQAzfCXI5a6GAEswOAGIQIACgCUhEaPJ04MBnVJQ4Ad3wr1ZAL4lLUEtVo50OALw4DxvKajoAdHfpMWOm95JWUQABoQCB4paExkUHQ6OghDAAUkhHiUdAA3CEkAEwiQACM6dDAAa20AZR5KySgAc2R-OEiACxgAW1QAdU7JeEwGsDharOHJXOGuZHBsEqbMODoYNIrmnvRkAXRUVciAK0wADwAhCuq69B64ABkmuD2Do5BTs9qm5tQ4AEUGBB4K9Dh0QA06Ks6AtuHxMGA6JIYiUeEjYP0ijBOsgABwABkiaIgq36FR4CzRcGhuRekQAjkD4JtotkQFgALQGOCFHklLSMyRaTboba7JD7MGRVY9SRtRjgzA-P6A4EvCVvcEwdClTGFbHIABMkXo6EkqB+AGEID0dgsoNA6SAGKsACo67KS95YGCg96FCBgP3giAMGA8MOG4PmcxAA)
```sh
--parser typescript
```

**Input:**
```tsx
class A {
    'constructor': typeof A
    static Foo() {
        return new A()
    }
}

const a = new A()
a.constructor.Foo()
```

**Output:**
```tsx
class A {
  "constructor": typeof A;
  static Foo() {
    return new A();
  }
}

const a = new A();
a.constructor.Foo();

```

**Comment by thorn0** [comment]
But we need a test for this to make sure it won't break again. Reopening.
