### ISSUE TITLE
In Markdown Files, Nested Code Block/Raw HTML Indent For Each Format on Save 

### ISSUE THREAD

**Issue by wunderman4** [prettier/prettier#4112]
I apologize if this is already an open ticket, I didn't see anything for this in particular. The issue is appearing in markdown files. When attempting to nest code blocks or raw HTML the format on save feature will add more spacing each time the file is saved which breaks the indentation. When using code blocks the issue is intermittent where once the code is nested correctly it will not break again but with raw HTML the only way to prevent the issues is to turn off format on save or ignore markdown files, neither of which is a solution. Any thoughts on a setting that may help are appreciated. 

p.s. I'm using Prettier in VS Code. 

![formatonsave](https://user-images.githubusercontent.com/25302911/37053023-4a36a348-2138-11e8-9f2a-af057a9998e7.gif)

**Input:**

1.  Some test text, the goal is to have the HTML table below nested within this number. When formatting on save Prettier will continue to add an indent each time pushing the table further and further out of sync. 

    <table class="table table-striped">
    <tr>
    <th>Test</th>
    <th>Table</th>
    </tr>
    <tbody>
        <tr>
        <td>will</td>
        <td>be</td>
        </tr>
        <tr>
        <td>pushed</td>
        <td>When</td>
        </tr>
        <tr>
        <td>Format on</td>
        <td>Save</td>
        </tr>
    </tbody>
    </table>

**Output on first save:**
1.  Some test text, the goal is to have the HTML table below nested within this number. When formatting on save Prettier will continue to add an indent each time pushing the table further and further out of sync.

    <table class="table table-striped">
<tr>
<th>Test</th>
<th>Table</th>
</tr>
<tbody>
    <tr>
    <td>will</td>
    <td>be</td>
    </tr>
    <tr>
    <td>pushed</td>
    <td>When</td>
    </tr>
    <tr>
    <td>Format on</td>
    <td>Save</td>
    </tr>
</tbody>
</table>

**Output on fourth save:**

1.  Some test text, the goal is to have the HTML table below nested within this number. When formatting on save Prettier will continue to add an indent each time pushing the table further and further out of sync.

                <table class="table table-striped">

            <tr>

        <th>Test</th>

    <th>Table</th>
</tr>
<tbody>
    <tr>
    <td>will</td>
    <td>be</td>
    </tr>
    <tr>
    <td>pushed</td>
    <td>When</td>
    </tr>
    <tr>
    <td>Format on</td>
    <td>Save</td>
    </tr>
</tbody>
</table>

**Expected behavior:**

1.  Some test text, the goal is to have the HTML table below nested within this number. When formatting on save Prettier will continue to add an indent each time pushing the table further and further out of sync. 

    <table class="table table-striped">
    <tr>
    <th>Test</th>
    <th>Table</th>
    </tr>
    <tbody>
        <tr>
        <td>will</td>
        <td>be</td>
        </tr>
        <tr>
        <td>pushed</td>
        <td>When</td>
        </tr>
        <tr>
        <td>Format on</td>
        <td>Save</td>
        </tr>
    </tbody>
    </table>

**Comment by duailibe** [comment]
Hi! Can you post a code snippet in https://prettier.io/playground and click on `Copy markdown` ?

You can enable in `Show options` -> `Debug` -> `show second format` to demonstrate things happen after subsequent formats

**Comment by wunderman4** [comment]
Ahh that makes more sense. Below is the copied markdown. 

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAkwZQgWzk3gGcZi4APGAGmIAsiBzCAQwBtMBLE4iTeqwBuRGIwEx8nGKwBG7IrLjsIAd0xQ4ZOABNMqrmK5QGPDQFd8SgE5YA6oxMAzCNfysYxppmiYSwogAFazgYTzhrfS52TkhYY3NRflYdPVYTYx0EcjhWMHpiLkJMAAdzEnovBlE5BUwnc2sxCMx0vQamxkiIc3IIJz8ATygwLAAdKAnsbAAeGXkiMHZWEhIAXjGQebrtuABaMmsuEt1NgD4p6bnrC5MrsTOAFS0YGYB6B8vZh8fauHfPndZh8bl9MHNZBAdINbtM4eCYKCgfC5jozgYYgC0WC4aizkosbD4cDEUTidcySiYGiyhVdIScfc0Q4EAzkbiQZTcaTGd80QAxVzuPpQNnEvlnHABMXigFIjkwSHQykAv5nEA0EAQEqeaAkZCgVjWaxqQJGhD6lDCCBcHQakArGDIJwcEhwTWyax5ADWoRwJTyXmQiMSmp0EDAztd7pAxjdTWCrCY7ij7DdmoAViRKAAhL1gX0wKWEAAyxjgqfTWt6ZRgACZg9ZQyAA9Z48gQLI5IMVFB7SUjrA7LaxMgABwABk1A4gbrsXpKHYHWgiIntIQAjuYuCFE8nWJWY278FxG82SF4FABFcwQeCHzXzYc6UdIOuPr3RLwAYQIKZQUDQBWmrlHAvyyJaLppnAAC+MFAA)

**Input:**
```jsx
1.  Some test text, the goal is to have the html table below nested within this number. When formating on save Prettier will continue to add an indent each time pushing the table further and further out of sync. 

    <table class="table table-striped">
    <tr>
    <th>Test</th>
    <th>Table</th>
    </tr>
    <tbody>
        <tr>
        <td>will</td>
        <td>be</td>
        </tr>
        <tr>
        <td>pushed</td>
        <td>When</td>
        </tr>
        <tr>
        <td>Format on</td>
        <td>Save</td>
        </tr>
    </tbody>
    </table>
```

**Output:**
```jsx
SyntaxError: Unexpected token, expected ";" (1:5)
> 1 | 1.  Some test text, the goal is to have the html table below nested within this number. When formating on save Prettier will continue to add an indent each time pushing the table further and further out of sync. 
    |     ^
  2 | 
  3 |     <table class="table table-striped">
  4 |     <tr>
```

**Second Output:**
```jsx
SyntaxError: Unexpected token, expected ";" (1:25)
> 1 | SyntaxError: Unexpected token, expected ";" (1:5)
    |                         ^
  2 | > 1 | 1.  Some test text, the goal is to have the html table below nested within this number. When formating on save Prettier will continue to add an indent each time pushing the table further and further out of sync. 
  3 |     |     ^
  4 |   2 | 
```

**Comment by lipis** [comment]
(@no-response bot is cool 🍺)
