### ISSUE TITLE
[Prettier API] crashing in printJSXChildren with custom parser and JSX whitespace

### ISSUE THREAD

**Issue by darknoon** [prettier/prettier#4113]
I'm trying to avoid parsing some text again after generating the AST with babylon, so I'm using this code to return the ast directly in parsing:

https://runkit.com/darknoon/5a9ef2674d0ffc001297fd53

It works for most cases, but if there is a JSX element with extra whitespace, I get this exception:
```
TypeError: Cannot read property 'split' of undefined
```

You can see the full exception on the runkit above.

**Input:**
```jsx
const var = <A>  </A>;
```

**Output:**
throws a TypeError

**Comment by darknoon** [comment]
_If there is a better way to generate code directly from an AST, please tell me!_

**Comment by suchipi** [comment]
Prettier uses babylon `7.0.0-beta.34` internally. I don't see a way to use that version in RunKit, but does using that version solve your issue?

**Comment by suchipi** [comment]
Also, obviously, a workaround would be to re-generate the code from your AST and let prettier parse it again, but that's what you're trying to avoid doing.

**Comment by duailibe** [comment]
Looks like you're using babylon6 in your code which parses the children of `<A> </A>` as:

```json
[
  {
    "type": "JSXText",
    "start": 13,
    "end": 14,
    "loc": {
      "start": {
        "line": 1,
        "column": 13
      },
      "end": {
        "line": 1,
        "column": 14
      }
    },
    "extra": null,
    "value": " "
  }
]
```

Which doesn't include `raw` nor `extra.raw` which Prettier expects: https://github.com/prettier/prettier/blob/f6f6f2e2eaa8d784ddb54e9219416e37cc3b94ec/src/doc/doc-utils.js#L185-L187

For comparison, here's the AST output of babylon7:

```json
[
  {
    "type": "JSXText",
    "start": 13,
    "end": 14,
    "loc": {
      "start": {
        "line": 1,
        "column": 13
      },
      "end": {
        "line": 1,
        "column": 14
      }
    },
    "extra": {
      "rawValue": " ",
      "raw": " "
    },
    "value": " "
  }
]
```

(You can check this at astexplorer.net)

**Comment by darknoon** [comment]
@suchipi I tried using `7.0.0-beta.34` locally, but it didn't fix the issue.
I was trying to use runkit to make it easier for you to reproduce

 instead I get this:

```   
    TypeError: Cannot read property 'raw' of undefined

      at printPathNoParens (node_modules/prettier/index.js:11367:41)
      at Object.genericPrint [as print] (node_modules/prettier/index.js:10120:30)
      at genericPrint$6 (node_modules/prettier/index.js:23410:18)
      at comments.printComments.p (node_modules/prettier/index.js:23348:14)
      at Object.printComments (node_modules/prettier/index.js:9006:19)
      at printGenerically (node_modules/prettier/index.js:23346:22)
      at FastPath.call (node_modules/prettier/index.js:20010:18)
      at printPathNoParens (node_modules/prettier/index.js:11836:44)
      at Object.genericPrint [as print] (node_modules/prettier/index.js:10120:30)
      at genericPrint$6 (node_modules/prettier/index.js:23410:18)
      at comments.printComments.p (node_modules/prettier/index.js:23348:14)
      at Object.printComments (node_modules/prettier/index.js:9006:19)
      at printGenerically (node_modules/prettier/index.js:23346:22)
      at FastPath.call (node_modules/prettier/index.js:20010:18)
      at printPathNoParens (node_modules/prettier/index.js:11756:25)
      at Object.genericPrint [as print] (node_modules/prettier/index.js:10120:30)```

pushed the actual code up to this branch here (run with `$ jest test`):

https://github.com/darknoon/auto-code-react/tree/babylon-version/test

**Comment by duailibe** [comment]
@darknoon Actually it did fix the issue

```
 FAIL  test/editXCoord.test.js
  ✓ find first comment in canvas (14ms)
  ✕ output with no change is same as input (37ms)
  ✕ change value of x to x+1 (27ms)
```

The `"output with no change is same as input"` test fails because Prettier looks at the original code to detect newlines, but you don't pass anything there:

https://github.com/darknoon/auto-code-react/blob/17000d735ee212524fb759cf009398452a309dd8/test/editXCoord.test.js#L55-L60

If you change `prettier.format('', {` to `prettier.format(text, {`, that test now passes:

```
 FAIL  test/editXCoord.test.js
  ✓ find first comment in canvas (18ms)
  ✓ output with no change is same as input (37ms)
  ✕ change value of x to x+1 (28ms)
```

Now the `"change value of x to x+1"` is the only one that failing and inspecting that, it's because you change the expression of an expression container in 

https://github.com/darknoon/auto-code-react/blob/17000d735ee212524fb759cf009398452a309dd8/test/editXCoord.test.js#L92-L94

If you print the before/after of that `NumericLiteral` what you get is:

```js
// before
    Node {
      type: 'NumericLiteral',
      start: 277,
      end: 278,
      loc: 
       SourceLocation {
         start: Position { line: 17, column: 16 },
         end: Position { line: 17, column: 17 } },
      extra: { rawValue: 0, raw: '0' },
      value: 0 }

// after
    { type: 'NumericLiteral', value: 1 }

```

If you check how Prettier prints `NumericLiteral`s, you see it relies on `node.extra.raw`:

https://github.com/prettier/prettier/blob/f6f6f2e2eaa8d784ddb54e9219416e37cc3b94ec/src/language-js/printer-estree.js#L1309-L1310

**Comment by darknoon** [comment]
@duailibe thanks for your help!
