### ISSUE TITLE
empty markdown lists 

### ISSUE THREAD

**Issue by mlrawlings** [prettier/prettier#4122]
Empty markdown lists are not idempotent and eventually collapse to incorrect output.

**Prettier 1.11.1**

### **Step 1**: 
When there are spaces after period, they are removed
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgDpQExa4DMhUALFiADQgQAOMAltAM7KgCGATlxAO4AFbgjYoOANwiMAJtRAcWMZADMOAGxZwaAIy4cwAazgwAynX2MoAc2QwuAVy0hpEMCvWaalzVxgC9VgC2HO4aTgBWLAAeAEJ6hsYmHIFwADKWcKGetPYwdLl4WU7mXD7IIMFcBi58UHJ0XJYwAOoyMAAWyAAcAAw0DRCazXp05Q1wPuKZNFxwAI72jLP+HEEhSKphNJqBjLYOTiyWVmpwAIr2EPBFNDAc2q3SHch4t3qMascAwhCBweVQaDTED2TQAFXuok2mgAvjCgA)

**Input:**
```markdown
1. 
2. 
3. 
4. 
```

**Output:**
```markdown
1.
2.
3.
4.
```

**Rendered:** (this is fine)
1.
2.
3.
4.

### **Step 2**: 
When there are no spaces after period, list collapses
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAHSgJi1AZnwBZ0QAaECABxgEtoBnZUAQwCd2IB3ABQ4TMUrAG4Q6AEwohWjGMgBmrADaM4lAEbtWYANZwYAZWo66UAObIY7AK7qQEiGEUq1lM2vYxe28wFtWF1V7ACtGAA8AIW09A0NWPzgAGTM4ILcqGxhqLJx0+xN2T2QQAPZdR24oaWp2MxgAdUkYAAtkAA4ABkpaiDUG7WoS2rhPETTKdjgARxs6KZ9Wf0CkJWDKNT86K1t7RjNzZTgARRsIeHzKGFYNJolW5Bwr7TplA4BhCD8AkqhoCZANjUABUbkI1moAL6QoA)

**Input:**
```markdown
1.
2.
3.
4.
```

**Output:**
```markdown
1. 2. 3. 4.

```

**Rendered:** (not okay)
1. 2. 3. 4.

### **Step 3**: 
In a collapsed list, single space becomes double space
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgExYMxYAs6IANCBAA4wCW0AzsqAIYBOrEA7gApsKMpmANwg0AJmRDN6MZADNmAG3pxyAI1bMwAazgwAypS00oAc2QxWAV1UgxEMPKUryJlaxjdNpgLbMnyrYAVvQAHgBCmjp6+sw+cAAyJnABLhRWMJQZ2Km2RqzuyCB+rNr2nFCSlKwmMADq4jAAFsgAHAAM5NUQKnWalEXVcO5CKeSscACOVjQTXsy+-kgKgeQqPjQW1rb0JqaKcACKVhDwueQwzGoNYs3I2BeaNIp7AMIQPn5FUNBjIFYqAAqVwEKxUAF9wUA)

**Input:**
```markdown
1. 2. 3. 4.
```

**Output:**
```markdown
1.  2.  3.  4.

```

### **Expected behavior:**
1. Running prettier on the same file three times should not result in three different outputs.
2. Prettier should not change the meaning of the markdown

**Comment by ikatyang** [comment]
Tracked in remarkjs/remark#327.
