### ISSUE TITLE
Parentheses for closure compiler type casting not handled well

### ISSUE THREAD

**Issue by roelkok** [prettier/prettier#4124]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgBAARgTwAc4tgB5AIwCs4wYBfLdVACgFt9Ka6A6QgJwjF+BAJQ8AzhDZwACoMJYAvFhj8ArnADcAHSgsM2PERLlqtBk1YcuFvgrgj8o8VJnyhy1Ru169kKAkYLAFPFUNcAmJSWzpGZnZOc15Q4TFJaTkFLRAAGhAhGABLaAlkUABDfkEAd1kqhDKUCoA3CCKAEzyQCqDkADMKgBsJOHyKfgqwAGs4GABlQimiqABzZDVNfI6IMAHh0fyV0ZF5CtW2Cv2RsZAqCQAPACFJmbn5ipkAGRW4a8OCuoYIQgQAmDY+fJLfgnZAgCgVCj4IbQboCFYwADqnRgAAtkAAOAAMUMEo0xk0IcIEcBOLT++X4cAAjuoikyzhcrkhBjd8qM2EUIVsQBIVqshnAAIrqCDwf63GCI7EdPHIUH5NQVIpDcUAYWklzhUGgDJA6lGABVEU1eaN6PQgA)

**Input:**
```jsx
/** @type {Object} */(myObject.property).someProp = true;
(/** @type {Object} */(myObject.property)).someProp = true;

const prop = /** @type {Object} */(myObject.property).someProp;
```

**Output:**
```jsx
/** @type {Object} */ myObject.property.someProp = true;
/** @type {Object} */ (myObject.property).someProp = true;

const prop = /** @type {Object} */ (myObject.property.someProp);

```

**Second Output:**
```jsx
/** @type {Object} */ myObject.property.someProp = true;
/** @type {Object} */ myObject.property.someProp = true;

const prop = /** @type {Object} */ (myObject.property.someProp);

```

**Expected behavior:**

The parentheses should be kept as per https://github.com/prettier/prettier/pull/2484
Also I would expect the prettier output not to be different for consecutive parsings. Now the second line of the input above gets rewritten to the first one and eventually without parentheses at all.

In the last case of the output above, the parentheses are maintained, but the closing one is moved to the back.

**Comment by ikatyang** [comment]
This issue seems somehow fixed.

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgBAARgTwAc4tgB5AIwCs4wYBfLdVACgFt9Ka6A6QgJwjF+BAJQ8AzhDZwACoMJYAvFhj8ArnADcAHSgsM2PERLlqtBk1YcuFvgrgj8o8VJnyhy1Ru169kKAkYLAFPFUNcAmJSWzpGZnZOc15Q4TFJaTkFLRAAGhAhGABLaAlkUABDfkEAd1kqhDKUCoA3CCKAEzyQCqDkADMKgBsJOHyKfgqwAGs4GABlQimiqABzZDVNfI6IMAHh0fyV0ZF5CtW2Cv2RsZAqCQAPACFJmbn5ipkAGRW4a8OCuoYIQgQAmDY+fJLfgnZAgCgVCj4IbQboCFYwADqnRgAAtkAAOAAMUMEo0xk0IcIEcBOLT++X4cAAjuoikyzhcrkhBjd8qM2EUIVsQBIVqshnAAIrqCDwf63GCI7EdPHIUH5NQVIpDcUAYWklzhUGgDJA6lGABVEU1eaN6PQgA)
```sh
--parser babylon
```

**Input:**
```jsx
/** @type {Object} */(myObject.property).someProp = true;
(/** @type {Object} */(myObject.property)).someProp = true;

const prop = /** @type {Object} */(myObject.property).someProp;
```

**Output:**
```jsx
/** @type {Object} */ (myObject.property).someProp = true;
/** @type {Object} */ (myObject.property).someProp = true;

const prop = /** @type {Object} */ (myObject.property).someProp;

```

**Comment by aaronogan** [comment]
There are still some edge cases, such as multi-line statements, and it seems that #1445 is still an issue.
[Playground  link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VALGMAOBnJdAcwEsYMBXAIwDpIBbVIiCIgGzlTDYjwoCc4AWgY4SHfqgDuJANYlUAQShQIMAIYwSUIkIBS6gG7qAymH4kcMIQDMI-IeWEBhHn0FDnEemIkBiGABPHGEwdTwtHQAdKBj0AAIAEwg4PCgAchh4qXtZJIo4eJgIeIZ6BCz6CENtIniqODtBePSAXnSYyCgIotSs1vjUACoh+IABIJD4gAobCigwLWgZoYBKJHiAfgAfecTG7ThE1fih1Bj4y6vp5lYaHHV+LXU2aYA5OCkAFQxammgvnAfGxNHBnBh1Do4AAaeL8TQkaAvOAAMRIcDYiVhk1R6Mxq1WAG4YnFUPU4Ng4PxYVQKFk3Kl4g9BLAMKlUp1oD14D0BsNRhNgoVZvNFoioCt1ltdlB9jZDsdTmSbiwiPdHs9Xh9vr8dP8oIDgaDwZCiDC4QikRw0RisUUhTb8USSVAEnh1OVOd1KhB9mx4nyRuMcfFgJtgGaYABJWVwAAeGxRoqWUAAvqmlTMqn6iSBoSAIFZxXhkKBHvwIFIAAqPBAllBGCAkRJ5kBUeFgWQUkwPMC1ZAwfgFfPaPBUmBV+FEejqZA2F5j-MAKzwcYAQh2uzATB64AAZQ5zhcwkDMsf8ZBt9RUQI8KCtnAWWAAdWb5GQAA4AAz5x+8ODPvCOCXo+7L8IYcCtoIACOFAkIIk7qNOs5IPObCLiAY70CQA5DieeC1BwACKFBqJBSCDsOIAaFQr6JO+SAAEz5oO6jiLUXj0DOl6pAArK2FBjl8171mhGHhDAR7oSeyRgFJGEQHSOB0oxuEFOmQA)

Input
```js
//https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#type-casting

// doesn't work due to comment moving before '='
const test = /** @type (function (*): ?|undefined) */
      (goog.partial(NewThing.onTemplateChange, rationaleField, typeField));

// better, but loses parentheses
const test = /** @type (function (*): ?|undefined) */ (goog.partial(NewThing.onTemplateChange, rationaleField, typeField));

// same
const model = /** @type {?{getIndex: Function}} */ (model);
```

Output
```js
//https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#type-casting

// doesn't work due to comment moving before '='
const test /** @type (function (*): ?|undefined) */ = goog.partial(
  NewThing.onTemplateChange,
  rationaleField,
  typeField
);

// better, but loses parentheses
const test = /** @type (function (*): ?|undefined) */ goog.partial(
  NewThing.onTemplateChange,
  rationaleField,
  typeField
);

// same
const model = /** @type {?{getIndex: Function}} */ model;

```

**Comment by sosukesuzuki** [comment]
Note: Bugs related to Closure Compiler type casting

## 1:

- Remove parens with new line.
- Move comments to before assignment operator.
  - [This is general problem](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mA9AFSaQC2lCWpxAOlJi6wEYCGATgNwgA0ICAAcYAS3TJQ3LhADuABW4I0yEBwBuEMQBMBINlw5gA1nBgBlYcbFQA5shhcArnEEALGJQA2AdXdi8GjWYHAWKoFiGoEAnmpgaKqCtmhwXDAKRnaUHMjYHN6pggBWaAAeAEJGpuYWHDQAMrZweQVFIKVlFrZ23nAAis4Q8K2FbiDWXKlcapxscN76wly2ML66MO7IABwADILLEKm+RsJqy3DTGi2CAI5D8JkiqigcaAC0UHBwOj-6XHB7mIAZkONlckh8mNBKlKGJHC5xmgen1BsMWpC2uMYBw2OsdJtkAAmQRODhibw9ADCEGoEJAUGgNxAzlSABVcS8oe0NK4AJJQX6wCxgFaiACCgosMBifVGqQAvgqgA), not only for Closure Compiler type casting comment.

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mA9AFSmYACMAngA5ybAYBOAllAOYC+mpxAHSiZMACgBGAQxYBKANwgANCAh0YbdMlDSWEAO4AFaQjTIQkgG4Q2AEyUhxLSWADWcGAGU6zjp2QwWAFc4ZQALGABbABsAdVC2eDRvMDgPEwS2CwSaMzA0U2UONDgWGAMnTgjJZGxJKOLlACs0AA8AISdXdw9JCLgAGQ44GrqGkGaWj18ouABFQIh4EfqQkG8WYpYzKXEaKOh7OnZYGNsYUOQADgAGZSOIYpinOjMjuE2LYeUARwX4ctUphQkjQAFooHA4DYofYWHBfmw4eVJJVqkhaitlMUImx-EFVmhpnM-sMkAFgsoYJJxKcbOdkAAmSlONhRXwAYQgESqZneAFZ7IFigAValAjFjCzBACSUGhsA8YHYagAgnKPLQZssxiCYNrVjYIGB9coIIEYHRzQy8cFuNwgA)

```js
// Input
const foo = /** @type {string} */
  (bar);

// Output
const foo /** @type {string} */ = bar;
```

## 2:

- Remove parens with complex type annotation.

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8OYLyYD0AVMZgAIwCeADnJgBQBmArlGDAJbSPECUSTAH4APmwAmcJpyhxxfTMUKMmECHwDcAHSggANCAg0u6ZKACGAJ0sQA7gAUrCNMhDmAbhE7j9IAEaW5mAA1nAwAMo0QTIA5sgwlixwBgAWMAC2ADYA6imcOFFgcOHO+Zzu+VSuYGguBjJocJYw9oEx6ebITOaZjQYAVmgAHgBCgSFh4ebpcAAyMnBdPX0gg0PhsZlwAIosEPBLvckgUZaNlq5+5n5UmdC+NJYyMNneMCnIABwADAaPEI1soEaK5HnBzu5FgYAI57eCtIwuFDmNAAWlkcjkvkscFhnBxrXM7U6SG6RwMjXSnHiiWOaE2OzhiyQCSSBhg11e4neyAATOzApxMrEAMIQdIdVzggCsvhYjQAKtckWSVu4kgBJKCSWDhMBPYwAQW14WoW0OKxRMAtx3EEDANoMEBYMBoLt5NKSAF8vUA)

```js
// Input
const test = /** @type (function (*): ?|undefined) */ (foo);

// Output
const test = /** @type (function (*): ?|undefined) */ foo;
```

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/7791
