### ISSUE TITLE
Extraneous semicolon with TypeScript interfaces as a default export

### ISSUE THREAD

**Issue by severen** [prettier/prettier#4127]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt8BLWObMsOPAMQgj2AB0o89scUgWiUAnngBGpbAH4keAM4xsdAOYBuXgF9evOvEalmeAEIyuvfoOGiJxDvLYcdvEABoQEDDBrRFyKAy2BAA7gAKMggBKKQAbhA0BB4gpMrIZJSKcJ6S2MYA1nAwAMoYxurIKuQ5ICJgGaRZtXTZuOH5agC2pI3NngBWimim+WBFpaRdcAAydHB92Z4Q5DAYqwBMi7Xl2G3IIDBiGHCKYKo+KRiqsADqSTAAFsgAHAAMntcQ2bf5GAfXU4MOILTyCACO5Bogg6pG6vSQmSWIGyXRoVWwNU8inUlDgAEVyBB4NtPDBSJJ7gQnsgNmT8jRKOoAMIQLo9A5QaCgkDkbIAFQpMSRcG02iAA)
```sh
--parser typescript
```

**Input:**
```tsx
export default interface Foo {
  readonly bar?: string;
}

interface Bar {
  readonly foo?: Foo
}
```

**Output:**
```tsx
export default interface Foo {
  readonly bar?: string;
};

interface Bar {
  readonly foo?: Foo;
}
```

**Expected behavior:**
```tsx
export default interface Foo {
  readonly bar?: string;
}

interface Bar {
  readonly foo?: Foo;
}
```

This is inconsistent with how a default export of a class would be formatted, of which interfaces are quite closely linked.

**Comment by j-f1** [comment]
It looks like this only happens with default exports, not named ones.

**Comment by severen** [comment]
Yeah, that is true, I should've added one as part of the examples to make
that clearer.
