### ISSUE TITLE
Playground not editable

### ISSUE THREAD

**Issue by cztomsik** [prettier/prettier#4132]
Chrome 64.0.3282.186

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoWATrrAOq4AmMAFsgBwAMGMAhgEbV2NIAmDAQoBzADZwAigFcI8ZADMO4gnHakOucWIDCEALYGOyEFGhx0ILprABrODADKWDmDHIYpGepAArAgAPACFbB2cOAzgAGQpLJGVVX1dSNVJTLm4AT3FoKzUDXE9vXxk1ABVuIgSVNQwKNJgABU1RYyVa31I4AEcZXG6WjjaTGqSMMgg1Sk0sUzI4NIA3SwwOUlIIAHcm9YRqkA4liForGggwDvHDghgruswZGCwngXu4AF8PoA)

**Comment by ikatyang** [comment]
Uh.., It's a placeholder for demo. 😅

**Comment by cztomsik** [comment]
Oh, now I can see it, but I was really clicking and trying to delete the code and I was also trying it in other browsers :-D
Closing, and sorry.
