### ISSUE TITLE
resolve .prettierignore files recursively upwards

### ISSUE THREAD

**Issue by fahrradflucht** [prettier/prettier#4133]
**Change Request:**
It would be useful if `.prettierignore` files would get resolved recursively upwards like other .ignore files (e.g .gitignore).

If that is not desired or to difficult it would be great to have a least some way to extend a `.prettierignore` file.

**Use Case:**
We have a mono repo setup where not all packages use prettier and therefor prettier is executed inside the packages since there are folder names which contain artifacts in one but source code in another package they can't all share one file. It would be great if we would not have to replicate all the common stuff in all `.prettierignore`s. Ideally we wouldn't even need one in the packages that have no special artifacts.

**Comment by duailibe** [comment]
Hi, thanks for the suggestion. This has been suggested already, let's track it in #4081
