### ISSUE TITLE
mongoose Model prettier

### ISSUE THREAD

**Issue by xinshangshangxin** [prettier/prettier#4134]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAFOAnNaTAXkwFtoBzCCNOAOgoBM4AbACgHJcDpOAaHPkJQAymAAWcMgEMAlAG4AOlBU8R9AGYBLKEwDyUOO2ArM5zAH1tTJJk6EycTAEkmnM5gC+cz-RhSUOzsTBBgciQAfJimUBaYeHAwAK54caFgnj5+AQjBGRHE0bHxkFCErAysEJQhYYpZiiD8IBAADjDa6MigMnh4EADu2H0IaMggMgBuEDbNkxjImjKsdC0ARngyYADWSaJt27qUyDB4yXAtGUsrayC6dHgw2FuUsjerlyAAVmgAHgAhLa7fYyJwAGV0cA+dwgyRgbXhACYYV9DgR8BN1jJ1gBPapQeZtPC6GAAdRsAWQAA4AAwtYm0OBkrZtCbEuCPKbQlqJACOyW0iReMjeMlRLToZG0p3OXzQx0qAEVkhB4LKLi0YDiKUwqUgkVqttpWMcAMIQMjvFCcgCs82SdAAKjjxkhlp8vF4gA)

[link 2](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAHOAnNaTAXkwFtoBzCCNOAOgoBM4AbACgHIAFfQqTgBpMvAtADKYABZwyAQwCUAbgA6UNbjFR6AMwCWUJgHkocdsDWYrmAPp6mSTJ0Jk4mAJJNOlzAF8FPvQwMlDs7EwQYAokAHyYFlDWmHhwMACueIkRYD7+gcEIYdnRxHEJSZBQhKwMrBCU4ZHKucoggiAQ2DB66Migcnh4EADu3AMIaMggcgBuEPZt0xjIOnKsdO0ARnhyYADWqeLYuwaUyDB4aXDt2StrGyAGdHgw3DuU8nfr1yAAVmgADwAQjt9oc5K4ADIGOBfB4QNIwbCIgBMcJ+xwI+CmmzkmwAnnUoItsHgDDAAOr2YLIAAcAAZ2qTaHAKTtsFNSXBnjNYe0UgBHNJ6FJvOQfOTo9p0Mh6c6XH5oU41ACKaQg8HlV3aMDxVKYNKQKJ1Oz0rFOAGEIGRPihuQBWRZpOgAFTxkyQq2+vl8QA)

```sh
--single-quote
```

**Input:**
```jsx
const Person = mongoose.model('Person', PersonSchema);

Person
  .findOne({
    _id: 'some Id'
  })
  .then((doc) => {
    return doc
  })
  .then((doc) => {
    console.log(doc);
  });
```

**Output:**
```jsx
// code snippet
```

**Expected behavior:**
the code start with `Person` and `person` not same, why?

**Comment by j-f1** [comment]
Can you fill out the issue template so we know exactly what you’re requesting?

**Comment by josephfrazier** [comment]
Judging by the playground links, I think they're referring to the behavior of this section of the code: https://github.com/prettier/prettier/blob/4c363a7a2f2c37da765c003ccc065cd3f308406e/src/language-js/printer-estree.js#L4079-L4093

**Comment by xinshangshangxin** [comment]
@josephfrazier is correct

but if I defined mongoose Model name with capital letter, the code format was not look good
I want:
```js
const Person = mongoose.model('Person', PersonSchema);
Person
  .findOne({
    _id: 'some Id'
  })
  .then((doc) => {
    return doc
  })
  .then((doc) => {
    console.log(doc);
  });
```

but format to:
```js
const Person = mongoose.model('Person', PersonSchema);
Person.findOne({
  _id: 'some Id',
})
  .then(doc => {
    return doc;
  })
  .then(doc => {
    console.log(doc);
  });

```

**Comment by josephfrazier** [comment]
I read through some of the PRs associated with the code I linked earlier, and it really sounds like this behavior isn't going to change. I think your options are:

* Use `person` instead of `Person`
* Put `// prettier-ignore` on the preceding line and format it how you like
* Use this code instead:

```js
const Person = mongoose.model("Person", PersonSchema);
Person.findOne({ _id: "some Id" })
  .then(doc => {
    return doc;
  })
  .then(doc => {
    console.log(doc);
  });
```

**Comment by xinshangshangxin** [comment]
I read the Mongoose doc, the `Model` build with `Schema` always start with  capital letter, I thought the last solution may better in some case

```js
const Person = mongoose.model("Person", PersonSchema);
Person.findOne({ _id: "some Id" })
  .then(doc => {
    return doc;
  })
  .then(doc => {
    console.log(doc);
  });
```

**Comment by josephfrazier** [comment]
You should be able to use whatever variable names you like, but I definitely understand the desire to capitalize it here. I'm going to go ahead and close this one, now that you have a few workarounds to choose from. Let me know if you have any more questions!
