### ISSUE TITLE
Idea: Ignore Prettier on json files

### ISSUE THREAD

**Issue by areijngoudt** [prettier/prettier#4135]
When a json file is touched in VSCode and auto-format-on-save is enabled, the json file is formatted in an illegal maner. This can be overcome by entering the name of the json file in .prettierignore. But if there are a lot of json files in a project, this is a bore.

Could you please provide an option to ignore all json files?

**Comment by ikatyang** [comment]
https://github.com/prettier/prettier-vscode#format-on-save:

> You can turn off format-on-save on a per-language basis by scoping the setting:
>
> ```json
> // Set the default
> "editor.formatOnSave": false,
> // Enable per-language
> "[javascript]": {
>     "editor.formatOnSave": true
> }
> ```

**Comment by areijngoudt** [comment]
This does not solve my problem - I want to use VSCode to edit and save json files, be it via automatic or manual save

**Comment by duailibe** [comment]
@areijngoudt I don't understand why that doesn't solve your problem? You'll still be able to edit and save JSON files, but Prettier won't touch them.

Either way, you can add `*.json` to `.prettierignore` and it will ignore all JSON files. You don't have to add one by one

**Comment by areijngoudt** [comment]
@duailibe ah, perfect, did not know about the wildcard

**Comment by j-f1** [comment]
> When a json file is touched in VSCode and auto-format-on-save is enabled, the json file is formatted in an illegal maner.

I’m interested in this part. How are we printing JSON incorrectly?

**Comment by areijngoudt** [comment]
Hm, strange. It did remove the " around the proeprty names. But now I retest, everything works as expected. Don't know why
