### ISSUE TITLE
Decorators containing anonymous function expressions are removed

### ISSUE THREAD

**Issue by zhipenglin** [prettier/prettier#4136]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZgVymGBLaACgEpgBfAHSg21wKhOCoAJmAnOGTNqZsAGwCGAZ2HkA3FUo4ho5gEEADoqa9mUkABoQERfmjDkoQWzYQA7gAUTCQykEA3CHgAmWkCJjJ0g-sLjaAEZsgmAA1pwAyoqheFAA5sgwbJgBIC4QYN6+-tpx-mwwliHxALaC2X5pAFbCAB4AQiHhUYKlcAAycXCVuTqYMIoDAEy9aTFsBcgggYKBAJ780O6KbHEwAOquMAAWyAAcAAzaqxD+GyGK06twBQ492hwAjph4HMWCZRVIPlXa-qU8EkUmlhHF4vw4ABFTAQeBjbQwOZbFy7ZDDREhPD8cEAYQgpXK0yg0AeIEw-gAKnM7L9-GQyEA)

**Input:**
```jsx
@function(){}
@function(){
  return class{};
}
class App{
  
}
```

**Output:**
```jsx
class App {}

```

**Comment by evilebottnawi** [comment]
@j-f1 looks like it is typescript :confused: and already works as expected https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZgVymGBLaACgEpgBfAHSg21wKhOCoAJmAnOGTNqZsAGwCGAZ2HkA3FUo4ho5gEEADoqa9mUkABoQERfmjDkoQWzYQA7gAUTCQykEA3CHgAmWkACM2gsAGtOAMqKPnhQAObIMGyYcNqhwnBsMJbeYQC2gsjogvwJ2gBWwgAeAELefoGCaXAAMqFwWTl5IMFsCWzIIDAAnopwwmBseHruikOwAOquMAAWyAAcAAzaYxAJE96KnWP9iQ4N2hwAjph4HCmC6ZlI2bmxIAlpeJHR98KhYfxwAIqYEPCNO7aGCCDxTFyzZAAJmB3jw-A+AGEIGkMp0oNADiBMAkACqguy3BJkMhAA

**Comment by j-f1** [comment]
@evilebottnawi It’s also a syntax proposal for JS, and we’re removing code,so I think we should fix this.

**Comment by fisker** [comment]
We are not removing code any more, `babel` `babel-*` parser throw an SyntaxError, other parsers format like this, 

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZgVymGBLaACgEpgBfAHSg21wKhOCoAJmAnOGTNqZsAGwCGAZ2HkA3FUo4ho5gEEADoqa9mUkABoQERfmjDkoQWzYQA7gAUTCQykEA3CHgAmWkACM2gsAGtOAMqKPnhQAObIMGyYcNpwALYecC4uyQAyguGYgmFwAGIQbPGCMPjhyCCCmDAQ7gAWMPH8AOp1ePDCwWBwAbbteA7tAJ4VYKLuocJwbDCW3mHFyOiC-FPaAFbCAB4AQt5+gYLxcGmhcEsrayCbWwGhYfxwAIqYEPAXq7EgwWxTbBUwIaKODCMBsPB6dyKcGwZquGB1ZAADgADNpoRAps1vIoKtCQdMHOdtABHV7wOa6OyVYQAWigcGSyXcHDJeA4cxyiyQy0+2im8TwkWiX2E90eLze5x5ly+MEEHjhLgRyAATNoooI8Px7gBhCDxbkgKDQYkgTBTAAqCrsvKuDhiAEkoKlYAEwRCYPIXQFAY8PlcRDAA18XBAwCHtBBqopqqqQ2QyEA)
```sh
--arrow-parens avoid
--parser typescript
--trailing-comma none
```

**Input:**
```tsx
@function(){}
@function(){
  return class{};
}
class App{
  
}
```

**Output:**
```tsx
@(function () {})
@(function () {
  return class {};
})
class App {}

```

**Comment by thorn0** [comment]
Let's close this issue and #7950 as Prettier doesn't remove code anymore and the demand for this legacy syntax in JS seems to be really low.
