### ISSUE TITLE
negate async function result will break in safari 11

### ISSUE THREAD

**Issue by KnisterPeter** [prettier/prettier#4138]
Negating the return value of an async function call in an if statement breaks in safari.

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABACgEpcBeAPl2AB0pdcBLAMwIEJUB3VemXedGIsWq06uAPRjc6CAFs4NOgF8F4yXAA26eVEUBuEABoQEAA4x60dMlAmATvVgB1egBMYAC2QAOAAxGYqABGzm6eSABMRugOAObqcACKAK4Q8MiMqJpw-rZc6rEAwrIyqMggUNBwhiCBuWAA1nAwAMomqGCxyDC2SdkgAFboAB4AQnWNLahyADIOVUgZWUZttlq2ZYFBmOrQ1Voy9F09fUlaACpBVguZWkYOazAACrkxJek3fbZwAI5J9F-PVCvUrXJYgOwQLSOXImMp2OBrABuVSMqFstgg7EeaIQVzQiIgrmqLggYHeYIwMHJt2MSRgJjp4WpcEUiiAA)

**Input:**
```jsx
async () => {
  if (!await test()) {
    // some
  }
  // else
};
```

**Output:**
```jsx
async () => {
  if (!await test()) {
    // some
  }
  // else
};

```

**Expected behavior:**

**Output:**
```jsx
async () => {
  if (!(await test())) {
    // some
  }
  // else
};

```

**Comment by bakkot** [comment]
[Here](https://bugs.webkit.org/show_bug.cgi?id=176685) is the relevant JavaScriptCore bug.

This is kind of an interesting situation for prettier. Should it work around browser bugs? I'd lean towards not, especially given the reliance on transpilers. On the other hand, in this *particular* case, we might want to add those parentheses anyway for readability (see also #3089, #1513).

**Comment by suchipi** [comment]
I'm hesitant to set a precedent that we'll work around browser grammar bugs- that said, I think we should add parens here for readability.

**Comment by lydell** [comment]
Let's do it!
