### ISSUE TITLE
Conditional operator and some object has format bug --useTabs

### ISSUE THREAD

**Issue by QuietWind** [prettier/prettier#4140]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgEkpsJDgAdKKmKXAWziUIGcZN0BzAbhrq5uLQlACujAEZZ+UAL4CokKB0K5JAfQAmuGLlalyAbQC6hAD6ixAG2uEAvIVOyay1YwCeUOAHcHhAEFMTFwPADpUNiCQjwAKdW1dXABKARgAfic0ujpqWhgcgpgwAAtWKnASioAabKK6SUlWAGYAFjq6BSgTNNZxW1kQapAIAAcYVGg2ZFBcYIgfAAU5hGmUXAA3CFQtIZBcDmQ8azY4YckQsABrOBgAZVH8HmROMTOQLQgwI9wT9-RTpgYIsQtxGLgfn9hgArNgADwAQpcbvcmHAADLoOCQ07DCBiGCjAkAJhx70emEByBAMA8ozgbDAXHGe1GXFgAHUdjASsgABwABmGbIgpw5IVG1LZDKwG2xw0wcAAjmJUIqQUJwWThqdGKgXpg3jqeNY4ABFMQQeDamnqLlaHnIVrDTi4VDWHgAYQgjC1KCg0HlIDEpwAKuo1q84HI5EA)
```sh
--parser typescript
--tab-width 4
--use-tabs
```

**Input:**
```tsx
interface Info {
	name: string;
	age: number;
}

const ab_data: Info[] | null = [];

const mynew = Array.isArray(ab_data)
	? [
			{
				ch: "ch",
				bb: 34
			}
]
	: null;

```

**Output:**
```tsx
interface Info {
	name: string;
	age: number;
}

const ab_data: Info[] | null = [];

const mynew = Array.isArray(ab_data)
	? [
			{
				ch: "ch",
				bb: 34
			}
	  ]
	: null;

```

**Expected behavior:**

```tsx
interface Info {
	name: string;
	age: number;
}

const ab_data: Info[] | null = [];

const mynew = Array.isArray(ab_data)
	? [
			{
				ch: "ch",
				bb: 34
			}
		]
	: null;
```

![image](https://user-images.githubusercontent.com/8223607/37327794-ae0ea22c-26d2-11e8-9c75-49b3022ac255.png)

has two space！pls check some error

**Comment by ikatyang** [comment]
It's intended, see #2771 and #3745.

---

<details>
<summary>tabs</summary>

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgEkpsJDgAdKKmKXAWziUIGcZN0BzAbhrq5uLQlACujAEZZ+UAL4CokKB0K5JAfQAmuGLlalyAbQC6hAD6ixAG2uEAvIVOyay1YwCeUOAHcHhAEFMTFwPADpUNiCQjwAKdW1dXABKARgAfic0ujpqWhgcgpgwAAtWKnASioAabKK6SUlWAGYAFjq6BSgTNNZxW1kQapAIAAcYVGg2ZFBcYIgfAAU5hGmUXAA3CFQtIZBcDmQ8azY4YckQsABrOBgAZVH8HmROMTOQLQgwI9wT9-RTpgYIsQtxGLgfn9hgArNgADwAQpcbvcmHAADLoOCQ07DCBiGCjAkAJhx70emEByBAMA8ozgbDAXHGe1GXFgAHUdjASsgABwABmGbIgpw5IVG1LZDKwG2xw0wcAAjmJUIqQUJwWThqdGKgXpg3jqeNY4ABFMQQeDamnqLlaHnIVrDTi4VDWHgAYQgjC1KCg0HlIDEpwAKuo1q84HI5EA)
```sh
--parser typescript
--tab-width 4
--use-tabs
```

**Input:**
```tsx
interface Info {
	name: string;
	age: number;
}

const ab_data: Info[] | null = [];

const mynew = Array.isArray(ab_data)
	? [
			{
				ch: "ch",
				bb: 34
			}
]
	: null;

```

**Output:**
```tsx
interface Info {
	name: string;
	age: number;
}

const ab_data: Info[] | null = [];

const mynew = Array.isArray(ab_data)
	? [
			{
				ch: "ch",
				bb: 34
			}
	  ]
	: null;

```

</details>

<details>
<summary>spaces</summary>

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgEkpsJDgAdKKmKXAWziUIGcZN0BzAbhrq5uLQlACujAEZZ+UAL4CokKB0K5JAfQAmuGLlalyAbQC6hAD6ixAG2uEAvIVOyay1YwCeUOAHcHhAEFMTFwPADpUNiCQjwAKdW1dXABKARgAfic0ujpqWhgcgpgwAAtWKnASioAabKK6SUlWAGYAFjq6BSgTNNZxW1kQapAIAAcYVGg2ZFBcYIgfAAU5hGmUXAA3CFQtIZBcDmQ8azY4YckQsABrOBgAZVH8HmROMTOQLQgwI9wT9-RTpgYIsQtxGLgfn9hgArNgADwAQpcbvcmHAADLoOCQ07DCBiGCjAkAJhx70emEByBAMA8ozgbDAXHGe1GXFgAHUdjASsgABwABmGbIgpw5IVG1LZDKwG2xw0wcAAjmJUIqQUJwWThqdGKgXpg3jqeNY4ABFMQQeDamnqLlaHnIVrDTi4VDWHgAYQgjC1KCg0HlIDEpwAKuo1sdTnI5EA)
```sh
--parser typescript
--tab-width 4
```

**Input:**
```tsx
interface Info {
	name: string;
	age: number;
}

const ab_data: Info[] | null = [];

const mynew = Array.isArray(ab_data)
	? [
			{
				ch: "ch",
				bb: 34
			}
]
	: null;

```

**Output:**
```tsx
interface Info {
    name: string;
    age: number;
}

const ab_data: Info[] | null = [];

const mynew = Array.isArray(ab_data)
    ? [
          {
              ch: "ch",
              bb: 34
          }
      ]
    : null;

```

</details>
