### ISSUE TITLE
CLI: --list-different + --write = Exit status 1 if something was modified

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#4144]
It doesn't play very well with npm scripts:

```
d:\dev\foo>npm run format

> @ format d:\dev\foo
> prettier --write --list-different *.js

foo.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ format: `prettier --write --list-different *.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Without `--list-different` though it doesn't behave like this.

**Comment by josephfrazier** [comment]
related issues from searching `write "list-different"`:

* https://github.com/prettier/prettier/pull/1633
* https://github.com/prettier/prettier/issues/4129

**Comment by centigrade-thomas-becker** [comment]
I use yarn/npm to run prettier and I am getting the error "Exit status 1" or "Exit code 1" for pretty much any command, except for "--help" and "-v".

If I install and run prettier globally then there are no errors.

**Comment by hhubik** [comment]
I started getting this error after I modified a project file in VS Code running on Windows 8.1 x64. Could this be related to Windows and/or VS Code?

**Comment by bennyn** [comment]
I also have issues with my CI when using `--list-different`:

![image](https://user-images.githubusercontent.com/469989/38780220-72c7fdc4-40d3-11e8-81dd-1f776be89f3d.png)

Without `--list-different` it works.

**Comment by thorn0** [comment]
Guys, this issue is about the `--write` + `--list-different` combination. Please stop writing unrelated things here.

**Comment by pascaloliv** [comment]
Getting same error when running `prettier --list-different`.
npm ERR! code ELIFECYCLE

Prettier: 1.11.1
Node: v8.9.4
npm: 5.7.1

**Comment by thorn0** [comment]
@bennyn `--list-different` without `--write` is a check. It checks that the files are formatted properly and lists the ones that aren't. It's totally expected that it fails with the exit code 1 when it finds something (`package.json` in your case).

With `--write` however, Prettier immediately reformats the files rectifying all the formatting problems, so this exit code 1 makes very little sense in that case. That's what this issue is about.

**Comment by pascaloliv** [comment]
Sorry @thorn0 for this misunderstanding - everything works as expected in the documentation 😄

**Comment by aMoniker** [comment]
I'd like an exit code `1` when something is changed so I can use it in git hooks.

**Comment by aMoniker** [comment]
@j-f1 I'm using `--write` and `--list-different` to write & get an exit code of `1` when something is written, which ensures my git hook is aborted. Can I rely on this, or will there be a different method to ensure an exit `1` when using `--write`?

**Comment by kachkaev** [comment]
I'm curious what `--list-different` users think of https://github.com/prettier/prettier/issues/5520 (a new `--lint` / `--check` option)

**Comment by hardikdot** [comment]
Thanks for great tools

Everything is working fine but some space error not displaying when i run `prettier -l MYPATH`
Instated of errors like eslint its displaying following error

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prettier: `prettier -l --pretty-error ./code/extensions/login/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ankit/.npm/_logs/2018-11-27T10_40_49_070Z-debug.log
but when i run `prettier -l --write MYPATH`
```

and then `git diff` its showing that some files is changed adding some space where its need.


I am using typescript + graphql + tslint + prettier

Here is my versions

prettier: 1.15.2
tslint : 5.11.0


Thanks

**Comment by lydell** [comment]
@hardikdot Please open a new issue with exact steps to reproduce if you need help.
