### ISSUE TITLE
flow Exact Object Types causes christmas tree indentation

### ISSUE THREAD

**Issue by jsphweid** [prettier/prettier#4147]
Prettier wants to turn this:
https://gyazo.com/974d867ea2f2bbe1e383f36ab67d5ecc
into a christmas tree
https://gyazo.com/4f948bb459f9b881cba85e10c2012b64

with these settings:
```
printWidth: 120
useTabs: true
semi: false
singleQuote: true
```

It looks like it is caused by flow's "Exact Object Types" (https://flow.org/en/docs/types/objects/). 

If I remove the pipes, it formats it correctly.

Also, these are my vscode settings:
```
    "prettier.singleQuote": true,
    "prettier.tabWidth": 4,
    "prettier.printWidth": 120,
    "prettier.semi": false,
    "prettier.useTabs": true,
```
Interestingly, it doesn't christmas-tree-ify it with the precommit hook we have, but if I manually edit and save a file, my editor will change it

**Comment by duailibe** [comment]
Can you fill out the issue template? Go to [Prettier playground](http://prettier.io/playground), paste your code and select the options in the left pane (click `Show options`), click `Copy Markdown` and paste here, please.

**Comment by jsphweid** [comment]
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACACgJwgwGdsBebYAHwB0oaZIBXDaJbAZQgFs4AVTHAA0dBlACGvdsRj4AllADmI+jHEATdfjjFi7AIKbtugVhUMN4jDDkA3OAfVWb908NEwM82AFkI6h2wAIwgIABs4cXooKgBfOhAhECIbaGJkUHF8QgB3XCyEdJRxWwg5dUSQcRlkADNxMOJhECD8cTAAazgYDgx2hUVkWSZm9QgwOoampIUm-BgCcUVucUnG5oArYgAPACE2zu6OSTgAGQU4Nenkpk9bgCYr5r78OeQQWrCIHMqvBRgAOrlGAAC2QAEZ7gAGJJeCBNAFtDDvLw6OD4eyVbQARyYcm0i2WqyQ9XWSSa3DkT3JAwiAEUmBB4EN8CMkmogkD1KDkAAWdltORhAYAYR4K3eUGglySTCafHEQSKwzgsViQA

Hmm... I couldn't replicate the issue. Does this mean it's an issue with the vscode plugin?

**Comment by duailibe** [comment]
@jsphweid it's possible. Either the Prettier plugin, another plugin or some VSCode "native" functionality? I don't use vscode so I can't help :/

I suggest you raise an issue in https://github.com/prettier/prettier-vscode that you're getting this formatting with the editor, but not when using Prettier alone and maybe they can help you better.

I'm gonna close this since it doesn't seem related to this project, but let me know if I'm wrong!

**Comment by jsphweid** [comment]
Nope, you're right. It seems to be related to the extension. Thanks so much for your fast help!
