### ISSUE TITLE
bug: breaking code with TypeScript 2.8 mapped type modifier 

### ISSUE THREAD

**Issue by lacolaco** [prettier/prettier#4158]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgCVcB3ABUwgAcBnQ4AHSkMOwggH4lC6ZM6AOYBuFgF8WLAPTTCAAwC08wmVQAbdYQBGRTHAC2EAG5wAJgEILhABRkAFgE8uAShYxHNIgDFUAD3MAHgAVAD5CAF5GQn1cM2h1R0IAbQpCdEIAazhHCGxCYIBdRR4C1MLCcREQABoQWhhUaDpkUFxMakp2hBaUXGMIVDNakFx+ZDx1Ojg67Ux8bJgAZRp8YWQBAFcZkHiwCdwpnfRpzBgqXCEDXAOjuoArOj8AIXmwRaXcAzgAGXQ4W7TOoQTYwGiggBMgJ2q0wp2QIA8XjoYEENBgIxoglgAHUhjB7MgABwABjqWIg0xx8xoCKxcFOphG+gAjptUPoLlcbkhJkCQNMDKgNphtnU6MJ1HAAIqbCDwaF1GC4bR4swE5AQpXzDTCADCEAM1wRUGgALqm2mwRVvT5cHE4iAA)
```sh
--parser typescript
```

**Input:**
```tsx
interface RawProps {
  foo?: string;
}

// `-` will be removed!! (why?)
type Fixed<T> = { readonly [P in keyof T]-?: T[P] };
```

**Output:**
```tsx
interface RawProps {
  foo?: string;
}

// `-` will be removed!! (why?)
type Fixed<T> = { readonly [P in keyof T]?: T[P] };

```

**Expected behavior:**

**Comment by existentialism** [comment]
Ref: https://github.com/prettier/prettier/pull/4156

**Comment by suchipi** [comment]
Although we are ready to print this once it can be parsed, we are still waiting for a change in `typescript-eslint-parser`, and will need to update that before we can close this: https://github.com/eslint/typescript-eslint-parser/pull/454

**Comment by ikatyang** [comment]
We're now in the `eslint/typescript-eslint-parser#ts-2.9` branch. (Ref: #4268 and #4353)
