### ISSUE TITLE
Making Print Width optionally mean a maximum length

### ISSUE THREAD

**Issue by voliva** [prettier/prettier#4160]
For `Print Width` option, there's a recomendation that says not to put in values larger than 80 cols, because Prettier will always try to fit in as much as it can into a single line.

It would be nice if we could make this behaviour optional, so prettier can take the `Print Width` option as a maximum line length: If the line is shorter than the set length, it gets untouched, and if the line is larger than the set length, it gets broken to fit in.

**Comment by lydell** [comment]
Note to self and maintainers: We should write something in the Rationale page that explains print width and contrast it with elm-format’s way of doing it. This and similar questions pop up all the time.

**Comment by zroug** [comment]
I have a similar issue #4093.

**Comment by suchipi** [comment]
The proposed change is a pretty fundamental change to prettier's core algorithm which is nontrivial to implement, so we're not going to do this, so I'm going to close this.

**Comment by voliva** [comment]
@suchipi alright. Just to know, is it because prettier parses and rewrites
all code based on the rules?

Or where can I find info on how prettier works?

**Comment by lydell** [comment]
https://prettier.io/docs/en/technical-details.html
