### ISSUE TITLE
Strips empty Jekyll front-matter blocks

### ISSUE THREAD

**Issue by thomaslaunch** [prettier/prettier#4162]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdK7VawIwgBMBPYPGQgJyLiqQAIBGABwA8GBnCAGwEsiDKnCIBuLAF8QAGhAQWMPtE7JQAQypUIAdwAKGhCpRqAbhAEyQazjGQAzNT05xZ+KmrABrODADKLDz4oAHNkGCoAVxcQIggwe0dnWSDnKhhdd2CAWzUEp2iAK042ACF3Lx9fNSy4ABkguDykuQiYFlaAJibogKpU5BBOME4VWRYqIJgAdQEYAAtkAA4ABjGtZyn3FgHxuFSTRtlhAEcIvmEMtWzcpAd82WcsvjDI6M4g4J44AEUIiHhurIYGp8DMiPNkB0ge4+PwQgBhCBZHIDKDQQ4gCLOAAqIKMd2cEgkQA)
```sh
--parser scss
```

**Input:**
```scss
---
---

body{
	border: 1px solid red;
}
```

**Output:**
```scss
body {
  border: 1px solid red;
}

```

I noticed prettier will retain Jekyll-style front matter blocks if they have content but remove them if they are empty. I believe this to be incorrect behavior as Jekyll requires the front-matter block to be present to process the file, even if that block has no content. Specifically this is happening with a .scss file in Jekyll with empty front-matter. 

See #3321 & #3802

**Comment by evilebottnawi** [comment]
@thomaslaunch please use issue template

**Comment by thomaslaunch** [comment]
@evilebottnawi sorry updated.

**Comment by evilebottnawi** [comment]
Issue in deps https://github.com/jonschlinkert/gray-matter/issues/65

**Comment by jonschlinkert** [comment]
I just mentioned a potential solution on the linked issue, but I'd also be happy to discuss adding an option. Other suggestions welcome.
