### ISSUE TITLE
TypeScript: Parenthesis incorrectly removed from typecast expression

### ISSUE THREAD

**Issue by UselessPickles** [prettier/prettier#4167]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgFkBPAeQCMArQ4AHSkMMzlwBNoAbUwgN1xcArnCSEoQgLaUsAbkYBfRo3ZwwXXK0KQoAZxiEINMWSrV5URgAoj1AHQDhRXLsK4opAJQBqb4xAANCAQAA4wqNC6yKCamBAA7gAKmghRKLh8EKjsgSAuMMh4XLpwQZSY+ADWcDAAyiH46ADmyDCYIkGcYIWCJUHoJZgwiRVNkrg9xaUg1LoAHgBCFWDVdbiScAAy6HCTfcFCMCGHAEx70w2Yg8ggMKQhcLpgmKhhuSEvsADq2TAAFsgABwABiCHwgJS+FRCNw+jywfF2QVYAEchKhWCNcGMJkgivsSpJUK12tNdM0uHAAIpCCDwc5BGC4Sg-dj-ZAnRkVVBcZoAYQgknGNyg0CRICEJQAKsy0vi4AoFEA)
```sh
--parser typescript
```

**Input:**
```tsx
interface MyObj {
  readonly value: number;
}

declare const obj: MyObj;

(obj.value as any)++

```

**Output:**
```tsx
interface MyObj {
  readonly value: number;
}

declare const obj: MyObj;

obj.value as any++;

```

**Expected behavior:**
`obj.value as any++;` is invalid code. The parenthesis should be retained around the typecast expression: `(obj.value as any)++;

**Comment by existentialism** [comment]
@UselessPickles thanks for the issue!

Should be as easy as adding `UpdateExpression` to:
https://github.com/prettier/prettier/blob/master/src/common/fast-path.js#L322

Interested in sending a PR?

**Comment by UselessPickles** [comment]
@existentialism Looks easy enough because you told me what to change. The hard part is knowing where to add unit tests. Existing file somewhere? New file? Where? Does this change affect TypeScript only, or also Javascript? Other languages? What exactly is an "UpdateExpression", so that I know what other examples to include in unit tests?

If you can easily point me in the right direction with less effort that it would take for you to make the changes yourself, then I'll take a crack at it :)

**Comment by existentialism** [comment]
@UselessPickles

If you're interested in contributing, I'm happy to help!

It may be easiest to visualize this, if you check out the [AST](http://astexplorer.net/#/gist/c8fa8185e41c71b799f9d5df3ea56294/d3f75528cdd06cfcc9c5f29f02306fb05c8f389c) for your code sample, you'll notice that the `TSAsExpression` is the argument for an `UpdateExpression`.

You can add your code to the existing TSAsExpression tests over at : https://github.com/prettier/prettier/blob/master/tests/typescript_as/as.js

Let me know if you have any other questions!

**Comment by UselessPickles** [comment]
@existentialism PR submitted.
