### ISSUE TITLE
Very ugly formatting for Typescript union type type assertion

### ISSUE THREAD

**Issue by ethanresnick** [prettier/prettier#4168]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAHgBQCU+wAOlPvpFAM4z4AOcATgLY4MN6MBhABZwwAaw74AvNVq0APAAUO3XvwbDRE9vICGUAJ4A+fAB98mACZxUOKHEtHiew0bZcefaA1IBtdqJwOABuHAAqBmwAugDclDDUAL4gADQgECy43siguuzsEADuinkIDMggusEQOJaplUzIqLoANgxwaQBG7LricDAAyiy9dgDmyDDs6B0glhBgTa3taXbt7DCKPaOcuottMwBWDIQAQj19g7qccAAydnB7y+noMCwvAEyPM8PsaxUwkTgDDA7BwmXqLFBsAA6rUYEJkAAOAAMaUhEHa0J6LAqkKBHFC9QCAEd0DgAptdNtdkhmvs0u1uBMpjM+FBRi04ABFdAQeBfNIwXSdWGWeHId6Cno4FpjAQQTg7CpQaAPNLodphYXlWlLOCJRJAA)
```sh
--parser typescript
```

**Input:**
```tsx
function x() {
  const permissionsChecker =
    <PermissionsChecker<any> | undefined>(<any>permissions)[receiverType];	
}
```

**Output:**
```tsx
function x() {
  const permissionsChecker = <
    | PermissionsChecker<any>
    | undefined>(<any>permissions)[receiverType];
}

```

**Expected behavior:**
Ideally, I think it would leave the code as input.

**Comment by thorn0** [comment]
And if we use `as` instead of `<...>`, it looks kind of strange too:

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAHgBQCU+wAOlPvpFAM4z4AOcATgLY4MN6MBhABZwwAaw74AvPmq1axADwBDKAE8AfGy48+0BqQDa7UXBwA3DgBU1bALr5lDOfIAKHbr34NhoiexV1DXwAH3xMABM4VBwoOAjqAF8QABoQCBZcfWRQZXZ2CAB3VzyEBmQQZXMIHAjUyqZkVGUAGwY4NIAjdmVxOBgAZRZe2IBzZBh2dA6QCIgwJtb2tNj29hhXHtHOZUW2mYArBkIAIR6+weVOOAAZWLg95fT0GBYXgCZHmeH2NYqYWxwBhgdg4TL1Fig2AAdVqMCEyAAHAAGNKQiDtaE9FgVSFAjiWeomACO6BwJk2ym2uyQzX2aXa3AmUxmfCgoxacAAiugIPAvmkYMpOrCIvDkO9BT0cC0xgIIJwdhUoNAHml0O0rMLyrSlnBEokgA)
```sh
--parser typescript
```

**Input:**
```tsx
function x() {
  const permissionsChecker = 
    (<any>permissions)[receiverType] as
    PermissionsChecker<any> | undefined
}
```

**Output:**
```tsx
function x() {
  const permissionsChecker = (<any>permissions)[receiverType] as
    | PermissionsChecker<any>
    | undefined;
}

```

Or is it okay? What do you think?

**Comment by thorn0** [comment]
> Ideally, I think it would leave the code as input.

But what if the line is too long and needs to be broken?

**Comment by ethanresnick** [comment]
> Or is it okay? What do you think?

It's definitely less bad in the `as` case. Personally, I don't think union types always need to be split over multiple lines with a leading pipe — in the same way short object literals are allowed to stay on one line, I think short union types probably should as well. Therefore, my preferred formatting would probably be:

```ts
  const permissionsChecker = 
    (permissions as any)[receiverType] as PermissionsChecker<any> | undefined
```

> But what if the line is too long and needs to be broken?

I'd imagine it would depend on where the possible line breaks are... I'll see if I can find any real-world examples in my code bases and get back to you.

**Comment by ethanresnick** [comment]
Ok, first, another example related to the OP:

```ts
const value = 
  <TypeALongNameXYZ | TypeBLongNameXYZ>(obj.property!.subprop as any).value;
```

This currently gets formatted as:

```ts
const value = <TypeALongNameXYZ | TypeBLongNameXYZ>(obj.property!
  .subprop as any).value;
```

which also seems very weird. I'd want it to be preserved as is.

Now, if the union above had one more constituent, the assertion + the expression it applies to might not fit on one line, in which case I'd suggest something like: 

```ts
const value = <TypeALongNameXYZ | TypeBLongNameXYZ | TypeNameCLongName>(
  (obj.property!.subprop as any).value
);
```

That formatting is very related to #4171, and has the advantage that it could extend to type assertions in general where the assertion + the expression it's applied to don't fit on one line. E.g.:

```ts
let x = <typeof MyObject>require("./some/long/import/path/../to/my/module").default;
```

would become:

```ts
let x = <typeof MyObject>(
  require("./some/long/import/path/../to/my/module").default
);
```

rather than the current (imo awkward):

```ts
let x = <typeof MyObject>require("./some/long/import/path/../to/my/module")
  .default;
```

The current approach of breaking the union could also be fine in the wrapping case.

**Comment by lydell** [comment]
Just a random observation: It feels like there are several open issue now on the same theme, where Prettier is to "greedy" when it comes to filling lines. When Prettier breaks a line like this:

```
.............................................................................
  .......
```

... rather than like this:

```
................................................
  ....................................
```

**Comment by suchipi** [comment]
I think the correct behavior for the first example when it needs to break onto the next line would be:

```tsx
function x() {
  const permissionsChecker = <
    | PermissionsChecker<any>
    | undefined
  >(<any>permissions)[receiverType];
}

```

or:

```tsx
function x() {
  const permissionsChecker = <PermissionsChecker<any> | undefined>(
    <any>permissions
  )[receiverType];
}

```

**Comment by Edwardzyc** [comment]
Why does it add an extra '|' <-- does that not change the meaning of the type because it is an OR?

**Comment by suchipi** [comment]
Right, both are valid syntax and mean the same thing:
```ts
type A = B | C;
// OR
type A =
  | B
  | C
```
