### ISSUE TITLE
Respect language-specific tabWidth in fenced code blocks inside markdown files

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#4170]
Context: https://github.com/prettier/prettier/issues/4114#issuecomment-371756680

When markdown language has an overridden`tabWidth` in `prettier.config.js`, fenced code blocks inherit markdown's `tabWidth`, which feels intuitively incorrect.

**Prettier 1.11.1**
<s>[Playground link](https://prettier.io/playground/#.....)</s>
↑ it does not support overrides

`prettier.config.js`:
```js
module.exports = {
  tabWidth: 2, // default value; applies to all languages including javascript
  overrides: [
    {
      files: "*.md",
      options: {
        tabWidth: 4, // only applies to markdown
      }
    }
  ]
};
```

**Input (markdown):**
````md
* hello

  ```js
  if (true) { console.log('hello word')}
  ```

* world
````

**Output:**  
the list is indented by four spaces (expected), but the javascript code block uses four spaces too (unexpected)
````md
*   hello

    ```js
    if (true) {
        console.log("hello word");
    }
    ```

*   world
````

**Expected behavior:**  
the list is indented by four spaces, but the javascript code block uses two spaces
````md
*   hello

    ```js
    if (true) {
      console.log("hello word");
    }
    ```

*   world
```
````

Perhaps, in addition to `files: "*.md",` Prettier can allow for defining `languages: ['md']`, so that there was no ambiguity in config interpretation. Formally speaking, the current behaviour is correct, it's just not what people might be expecting. For us, humans, a fenced block in markdown is more like a mini-file in another file rather than a node in a single all-embracing syntax tree.

**Comment by ikatyang** [comment]
FYI, the `language` option is an 2.0 item (#2846), and current configs are all file-level since our [core printer](https://github.com/prettier/prettier/tree/master/src/doc) is currently not able to use different `printWidth` in a single `Doc`, I guess we could store the `printWidth` in [`indent`, `align`, etc.](https://github.com/prettier/prettier/blob/master/commands.md) so as to apply different `printWidth` but I'm not sure if it'll work.

**Comment by j-f1** [comment]
We could run the doc though the printer (with the `printWidth` decreased by the indentation level) and store it in the doc as a plain old string.

**Comment by thorn0** [comment]
closing in favor of https://github.com/prettier/prettier/issues/5378
