### ISSUE TITLE
Ugly formatting for Typescript generic type type assertion

### ISSUE THREAD

**Issue by ethanresnick** [prettier/prettier#4171]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAngBQCU+wAOlPvpFAM4z6o5QCGANgMLSsDm6AE7tcBALzVatADwBJALYL0MdgCNOcAHQBZdgAcZTIW34AafOyiEAfDYYQFcAKIAPHE1O8oAvfq1OQvxwACJwcPrEqFycauxgANYA8vowDKQA3FLSObTZOKjEMELocORUNNL0TCxsXN4CwqJ4NJKVOfJKKuqaugZGxaYWVrb2ji7unlD8DTj8fgFwQaHhkdGcsfHJqS3pWZUAvtQHIGYgEDvQDMig7EJCEADuAAp3CNco7ABuEDgAJqcQOwmMh1gw4Gc1CJEnAYABlfTxUzIYqlM5-CBgUFccFnNjgoQwZ4ifgKdjYzi4kAAKwYrgAQtCErC4ewnAAZNhwClUiAqfQqABMPIhIERQgJyBAMEI+jgDDAJlSgP0JlgAHV-jAABbIAAcAAYzqqIOD1SJ9FLVfKll9uWchHAAI7oHCO4nsUnkpBg0XghQ4FElP2mTQARXQEHgIrOqjUmr+OuQgtjIhwnC8jjJUqg0HtIHQ4IAKuoPr6DgcgA)
```sh
--parser typescript
```

**Input:**
```tsx
function y() {
  const finalConfiguration =
    <Immutable.Map<string, any>>someExistingConfigMap.mergeDeep(fallbackOpts);
          
  if(true) {
    const finalConfiguration =
      <Immutable.Map<string, any>>someExistingConfigMap.mergeDeep(fallbackOptions);
  }
}
```

**Output:**
```tsx
function y() {
  const finalConfiguration = <Immutable.Map<
    string,
    any
  >>someExistingConfigMap.mergeDeep(fallbackOpts);

  if (true) {
    const finalConfiguration = <Immutable.Map<
      string,
      any
    >>someExistingConfigMap.mergeDeep(fallbackOptions);
  }
}

```

**Expected behavior:**

First assignment would be left as is. The second assignment, which can't fit on one line even with a break after the equals sign, would be rewritten to something like:

```ts
if(true) {
    const finalConfiguration = <Immutable.Map<string, any>>(
      someExistingConfigMap.mergeDeep(fallbackOptions)
   );
}
```

(Adding the parentheses around the expression that's subject to the type assertion is clearer, imo, than:

```ts
if(true) {
    const finalConfiguration = <Immutable.Map<string, any>>
      someExistingConfigMap.mergeDeep(fallbackOptions);
```

where the type assertion might be read as applying to `someExistingConfigMap` and not the result of `mergeDeep`).

**Comment by kpdonn** [comment]
Heads up I submitted PR #4219 that will fix this if accepted.

**Comment by dantman** [comment]
Note that flow has this same issue IIRC.
