### ISSUE TITLE
Dropping parens & line-breaks makes intent unclear

### ISSUE THREAD

**Issue by MarkKahn** [prettier/prettier#4173]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgCgDpQAR6aYAeeA1HpADYCUeAPHgAx0A+ruBRpF1dAfAF48Ad1QATGAAs2HfIUwBPcngBOEEXUYs87TguUV1mvELxS4qAOZSYNXDWD7cAXxAAaEBAAOMVNABnZFAAQ1VjAAUwhCCUEIA3CAkPEBCAmGR0EKoAuE8AI1UQsABrOBgAZW9i1CgrZBhVAFc8kHEIMEzs3M9a3NUYCKKrAFsQrpzWgCsA4gAhItLyipCRuAAZWrgJnq8mmG99gCYd1urVfuQQfJD8xSpoFO9VWpgAdQlpZAAOJk9niC5N5FbxXZ5wfrxbaeVRwACOTVQsKGIVG4yQWUmnlyI1QDWarQCtSsVDgAEUmhB4KdPDBbh9JFJkEdaUVUFRiQBhCAjMZXKDQaEgJq5AAqt1imNyLhcQA)

**Input:**
```jsx
if(
  ((x + col) < 0) ||
  ((x + col) >= width) ||
  ((y + row) < 0) ||
  ((y + row) >= height)
){
  
}
```

**Output:**
```jsx
if (x + col < 0 || x + col >= width || y + row < 0 || y + row >= height) {
}

```

I'm sure that someone can look at that output and clearly read it, but I certainly can't!

**Comment by lydell** [comment]
Hi, thanks for the issue! This has already been discussed in #187. This is not going to change at this point. Sorry!
