### ISSUE TITLE
Avoid unnecessary template literals

### ISSUE THREAD

**Issue by caub** [prettier/prettier#4175]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mABvBpgCTACMA1NQL7EDcAOlJFOQEYCGAToRJksAJmLsQAGhAQADjACW6ZKAH8IAdwAKAhGmQheANwiKAJtKMZk2XgBs0cGd368wAazgwAynPeKUADmyDD8AK7OIOYQYLYOTjKBTvww2m5BALa88Y5RAFZoAB4AQm6e3j68mXAAMoFwuYmy4TByraJNUf78KYZ83ACe9tBWcvyBMADqFjAAFsgAHAAMMuMQTlNucobjcCnGjTL8cACO4Yon6bxZOUh2eTJOmYqhEVFogUH2cACK4RB4G9IjIYLxuDNzPNkKJQW5FPYvgBhCCZbKGKDQI4gcJOAAq4IM9wScAYDCAA)
```sh
--single-quote
```

**Input:**
```jsx
const foo = `test ${1+1}`;
const bar = `test 2`
```

**Output:**
```jsx
const foo = `test ${1 + 1}`;
const bar = `test 2`;
```

**Expected behavior:**

Similarly to [eslint](https://github.com/eslint/eslint/commit/f83dc7784547a9054e2ed2425e1edcd3bc7132a3) it would be great to have `bar` with single-quotes since it doesn't use variables

```jsx
const foo = `test ${1 + 1}`;
const bar = 'test 2';
```

**Comment by j-f1** [comment]
We try to avoid changing the code’s syntax, and this includes changing template literals to regular strings. Feel free to comment if you have any more questions!

**Comment by caub** [comment]
I think in that case, it's better to transform to a string literal (either single-suoted or double-quoted depending settings)

The reasons are discussed [there](https://github.com/eslint/eslint/issues/3090), mostly consistency

**Comment by ikatyang** [comment]
I think this one is similar to #2243, see https://github.com/prettier/prettier/issues/2243#issuecomment-310821373.

**Comment by caub** [comment]
Ok, thanks for the longer explanation

I guess the way to go is run prettier + eslint on save then.

**Comment by caub** [comment]
> We try to avoid chainging the code's syntax

For example, prettier [changes the syntax for object keys](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDAJrgJzjTWMwF5MBZbABwApgAdKTTAcgFsA3XdpDgDEIEdgBoWbdgCYAcgEZ+HAELYC7FgF8AlCDEgItGAEt0yUGoIQA7gAU1CNMhDZuEY7j0uMyAGbYAG1J9ACMCbDAAazgYAGVaCOMoAHNkGAIAVzh9XAgwP0DgkCTSAhhbcOTObAKg7JAAKzQAD2VwqJjY7E44ABkkuFqiiAyYWlHpIfqEglLnEOwQgE8A6C9aAiSYAHUPGAALZAAOAAZ9DYhSbfDaZw3iOAJuQf0iAEcM4yIK7CqapH8dX0pE4xjSmXqaCSyQCcAAihkIPBwVl9DBFrtcAdkNI0eFjAFoQBhCCcarOKDQF4gDKkAAqiycAMKcE0miAA) there, even if I could prefer to have always keys quoted for consistency

**Comment by lydell** [comment]
Prettier avoids changing the _AST._ Removing or adding quotes around keys in object literals makes no difference in the AST. But swapping a string literal node for a template literal node is an AST change.

**Comment by j-f1** [comment]
@lydell Technically, changing `{ 'foo': bar }` to `{ foo: bar }` [changes the AST](https://astexplorer.net/#/gist/195bcf6d08a57f9d9a56e6c9022adfa2/latest).

**Comment by lydell** [comment]
Ah, sorry, I was sure that wasn’t the case. :confused:

**Comment by josephfrazier** [comment]
Yeah... it's occurred to me that Prettier doesn't (try to) leave the AST intact so much as the ASG ([Abstract semantic graph](https://en.wikipedia.org/wiki/Abstract_semantic_graph)), especially once you take the variety of tagged template literal formatters (markdown, graphql, etc) into account (they definitely change the AST).
