### ISSUE TITLE
The tarball on npm contains another prettier tarball

### ISSUE THREAD

**Issue by sandorfr** [prettier/prettier#4179]
**Prettier 1.11.1**

The tarball currently available on npm contains another tarball `prettier-1.11.1.tgz`. It seems like there a bug in your publish process which trigger this tarball inception. 

![image](https://user-images.githubusercontent.com/2660262/37629108-015abdfe-2c31-11e8-9518-a75fb73b9a7a.png)

**Expected behavior:**

The package on npm should not contain this tarball. it adds unnecessary overhead.

**Comment by suchipi** [comment]
Sounds like a good solution
