### ISSUE TITLE
[feature request]  solidity  language support 

### ISSUE THREAD

**Issue by foxundermoon** [prettier/prettier#4180]
solidity is  eth blockchain smart contract language.
it is very hot and popular.

https://github.com/ethereum/solidity

**Comment by kachkaev** [comment]
@foxundermoon feel free to create a plugin for this language:
https://prettier.io/docs/en/plugins.html

**Comment by lydell** [comment]
Yeah, feel free to make a plugin!

**Comment by mattiaerre** [comment]
hello,
did you close this issue because no action has been taken?
I'd love to help if a prettier solidity plugin is still needed.

// cc @foxundermoon @kachkaev @lydell

**Comment by lydell** [comment]
This won't be added to Prettier core, but you are free to make your own repo with a Prettier plugin, just like this ones: https://prettier.io/docs/en/plugins.html#community-plugins

**Comment by mattiaerre** [comment]
this is my WIP if you'd live to have a look:

https://github.com/mattiaerre/prettier-plugin-solidity

// cc @lydell @kachkaev @foxundermoon @j-f1
