### ISSUE TITLE
function `needsParens` from `FastPath` should be language-specific

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#4185]
We implement `plugin-php` for `prettier` and have other type of nodes and other logic for parens. I think `needsParens` should be part of language (i.e. option, example - `parsers.php.needsParens`) and should be remove from `FastPath` class.

/cc @vjeux @azz @czosel @mgrip

**Comment by mgrip** [comment]
I'll try to get something together in the next week! @evilebottnawi if you come across any breaking issues for the php plugin make sure to create an issue on that repo and mark as high priority, otherwise I think this is going to be a little lower on my to-do list

**Comment by mgrip** [comment]
Also for reference here's where that fn currently exists: https://github.com/prettier/prettier/blob/master/src/common/fast-path.js#L134

**Comment by azz** [comment]
But it doesn't have to be `parsers.php.needsParens`, it's not used at all by any Prettier internals, so you can just call your own function. This is purely refactoring.

**Comment by azz** [comment]
Done ✨
