### ISSUE TITLE
handling of read-only files

### ISSUE THREAD

**Issue by mvolkmann** [prettier/prettier#4187]
What should Prettier do when it attempts to format files that are read-only?
In Windows I get "Unable to write file", which is understandable.
Maybe there should be an option to skip unwritable files.
This comes up when people have to use version control systems like Perforce (feel pity for me) where only checked out files are writable.

**Comment by lydell** [comment]
Do you know how other tools, such as `eslint --fix`, handles this?

**Comment by mvolkmann** [comment]
I just tried `eslint --fix` and it gives the same error as Prettier. This could be viewed as a reason to not add special support to Prettier, but that seems problematic for people that have to use version control systems like Perforce.

**Comment by lydell** [comment]
I worked on a project that used Perforce a couple of years ago. It was not fun.

**Comment by lydell** [comment]
Hmm ... as far as I remember `prettier --write` won't write files at all if they are already printed correctly. Do you have files committed that aren't already correctly printed by Prettier?

**Comment by mvolkmann** [comment]
Yes, that is the issue. Maybe that isn't worth addressing. Feel free to close this if you think that doesn't need to be considered.

**Comment by lydell** [comment]
At least it feels like you could solve your immediate problem by running Prettier on the entire project.
