### ISSUE TITLE
Feature: skip processing unsupported file types, for example .gitignore or dot files in general

### ISSUE THREAD

**Issue by revelt** [prettier/prettier#4191]
I want to migrate all my libraries to prettier, so I created `.prettierignore` which ignores `dist/` (Rollup CJS, ESM and UMD builds) and ran with glob `npx prettier '*' --no-config --write`

<img width="619" alt="errors" src="https://user-images.githubusercontent.com/8344688/37777322-2887e460-2ddf-11e8-87d9-db11160ddb3e.png">

Since prettier _does_ clean JSON and HTML files, my expectation was that **all files** should either be cleaned where prettier supports them, or prettier would skip them.

> Prettier also supports TypeScript, CSS, Less, SCSS, Vue, JSON, GraphQL, and Markdown.
> — https://prettier.io/docs/en/language-support.html

However, prettier is trying to parse its unsupported file types and CLI **reports errors**.

**I wish prettier would skip processing the files it doesn't support.**

Currently, it seems that:

* dotfiles are not supported neither in `.gitignore` nor in `.npmignore`
* hashes (`#`) are also not supported neither in `.gitignore` nor in `.npmignore`
* Slashes are causing errors during `.prettierignore` parsing, for example, `dist/` would cause a prettier's error
* yml files are also using wrong parser, generic Travis yml's are errorring-out.

What's interesting, if somehow the files satisfy a current prettier's parser, for example, `.gitignore` contains a folder name without a dot, it doesn't error-out.

What do you think?

**Comment by ikatyang** [comment]
This should be covered by #2884.

As a workaround, you have to specify those extnames explicitly, for example:

```sh
npx prettier '*.{js,ts,css,less,scss,vue,json,gql,md}' --no-config --write
```

**Comment by revelt** [comment]
Tedious but definitely a temporary solution... 👍 

I'll close since this will pop up in searches and direct peoples to #2884. #2884 is not very search-friendly, it's difficult to track it down judging from title...

**Comment by lydell** [comment]
I tried to update the issue title for #2884 to make it a little more search-friendly

**Comment by j-f1** [comment]
Duplicate of #2884
