### ISSUE TITLE
Extraneous semicolon prior to array destructuring

### ISSUE THREAD

**Issue by NerdsvilleCEO** [prettier/prettier#4193]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQAcIDOqMqAbnAJSbAA6UNMA2pADYQBOANJqpFALqYAvJhgALVAQB06DgFsAhjADqcVAHMx8ACYAFQsTJwC2AIwU6AXxCcQEXCWgFkoBe3YQA7rrcJnKBVIIVG0bEAUCGGR0BRYCOFsAI3YFMABrOBgAZVxU1Ch1ZBh2AFcEkG0IMGjY+Nt8+PYYXRT1RRq48oArAgAPACEU9MyshTk4ABl8uA66uxKYXAWAJlny3PZG5BBEhUSATzYoMNx2fJUQ8WQADgAGW1PCOGUU3G3T4zh2cjD2OABHEqoP4tBRtBRrWzxOSoSEgIgFFhwACKJQg8DhMD2ykuYmQy1sxQUqBY+XUAGEIHJ2igoNAZrYSvEACp7fwxTqWSxAA)
```sh
--no-semi
```

**Input:**
```jsx
if (positive) {
	[color, icon] = this.formatWeightedPositives(1)
}
```

**Output:**
```jsx
if (positive) {
  ;[color, icon] = this.formatWeightedPositives(1)
}

```

**Expected behavior:**
```jsx
if (positive) {
  [color, icon] = this.formatWeightedPositives(1)
}

```

**Comment by j-f1** [comment]
This is intentional behavior, because if you put another line before the destructuring (maybe a function call, for example), the `[` will be interpreted as the beginning of a property access expression instead of a destructuring assignment. Adding the `;` prevents this from happening.

**Comment by lydell** [comment]
https://prettier.io/docs/en/rationale.html#semicolons

**Comment by NerdsvilleCEO** [comment]
Oh I feel so stupid haha, thanks for the insight on this, it threw me off seeing this as I am not used to the format w/out semicolons :) Thanks @j-f1 :D
