### ISSUE TITLE
markdown files - let's limit excessive lines when prettying the markdown tables

### ISSUE THREAD

**Issue by revelt** [prettier/prettier#4195]
Currently, there is no limit on the length of the contents of the cleaned markdown table columns. When we process tables which contain HTML, for example, all-contributors tables, the cleaned lines get very long:

![long-lines](https://user-images.githubusercontent.com/8344688/37824140-923e818a-2e83-11e8-9ca3-ad890c08be26.png)

In the case above, line is 865 characters long.

Let's detect such cases and turn off the table normalising, falling back to usual three-dash pattern, `| :---: | :---: | :---: | :---: | :---: | :---: | :---: |`

Update.

Since we're using `all-contributors` spec tables as an example, we have to use a real-world markdown table for testing. I'm going to post the contributors table from one of my libraries here. Please don't consider this as a shameless plug, I first wanted to use all-contributors readme itself but later thought, technically, we should then mention its MIT copyright licence in Prettier's licence. Since I'm providing piece of my own library licence, licensing issues don't really apply.

Here is an original markdown example:

```md
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
| [<img src="https://avatars1.githubusercontent.com/u/8344688?v=4" width="100px;"/><br /><sub><b>Roy Revelt</b></sub>](https://github.com/revelt)<br /> [💻](https://github.com/codsen/detergent/commits?author=revelt "Code") [📖](https://github.com/codsen/detergent/commits?author=revelt "Documentation") [⚠️](https://github.com/codsen/detergent/commits?author=revelt "Tests") | [<img src="https://avatars3.githubusercontent.com/u/1874682?v=4" width="100px;"/><br /><sub><b>Max Lapides</b></sub>](https://github.com/maxlapides)<br /> [🐛](https://github.com/codsen/detergent/issues?q=author%3Amaxlapides "Bug reports") | [<img src="https://avatars3.githubusercontent.com/u/9990521?v=4" width="100px;"/><br /><sub><b>Nacim Goura</b></sub>](https://github.com/nacimgoura)<br /> [🐛](https://github.com/codsen/detergent/issues?q=author%3Anacimgoura "Bug reports") | [<img src="https://avatars2.githubusercontent.com/u/23390212?v=4" width="100px;"/><br /><sub><b>Jack Steam</b></sub>](https://github.com/jacksteamdev)<br /> [🐛](https://github.com/codsen/detergent/issues?q=author%3Ajacksteamdev "Bug reports") |
| :---: | :---: | :---: | :---: |
<!-- ALL-CONTRIBUTORS-LIST:END -->
```

Here it is after being ran through Prettier:

```md
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->

| [<img src="https://avatars1.githubusercontent.com/u/8344688?v=4" width="100px;"/><br /><sub><b>Roy Revelt</b></sub>](https://github.com/revelt)<br /> [💻](https://github.com/codsen/detergent/commits?author=revelt "Code") [📖](https://github.com/codsen/detergent/commits?author=revelt "Documentation") [⚠️](https://github.com/codsen/detergent/commits?author=revelt "Tests") | [<img src="https://avatars3.githubusercontent.com/u/1874682?v=4" width="100px;"/><br /><sub><b>Max Lapides</b></sub>](https://github.com/maxlapides)<br /> [🐛](https://github.com/codsen/detergent/issues?q=author%3Amaxlapides "Bug reports") | [<img src="https://avatars3.githubusercontent.com/u/9990521?v=4" width="100px;"/><br /><sub><b>Nacim Goura</b></sub>](https://github.com/nacimgoura)<br /> [🐛](https://github.com/codsen/detergent/issues?q=author%3Anacimgoura "Bug reports") | [<img src="https://avatars2.githubusercontent.com/u/23390212?v=4" width="100px;"/><br /><sub><b>Jack Steam</b></sub>](https://github.com/jacksteamdev)<br /> [🐛](https://github.com/codsen/detergent/issues?q=author%3Ajacksteamdev "Bug reports") |
| :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |


<!-- ALL-CONTRIBUTORS-LIST:END -->
```

Imho, ideally, Prettier should leave such table as it is, with three-dash separators (`:---:`) instead of long lines. Feel free to do it differently.

**Comment by ikatyang** [comment]
Make sense, but could you provide the example input so we can use it as a test case?

**Comment by revelt** [comment]
Updated. Thanks for picking this up quickly.

**Comment by j-f1** [comment]
What about reprinting everything between `<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->` and `<!-- ALL-CONTRIBUTORS-LIST:END -->` as-is, additionally?

**Comment by revelt** [comment]
@j-f1 Sure! There are two specs I've ever seen - official-one you mentioned and also [Atom plugin](https://github.com/o-d-i-n/all-contributors-atom) which comprises of two parts:

```
<!-- Contributors START
Contributors END -->
```

and 

```
<!-- Contributors table START -->
<!-- Contributors table END -->
```

normally these two chunks are tightly close, on nearby-lines. 

Maybe there are more specs.

**Comment by lipis** [comment]
I like the idea to have a special case for `<!-- Contributors table START -->...` (or whatever it will be), but I would still like to format tables normally regardless the length.

What about just use the `<!-- prettier-ignore -->`, if someone doesn't want the specific table to be formatted?

**Comment by duailibe** [comment]
FTR the feature to accomplish this is https://prettier.io/docs/en/ignore.html#range-ignore which will be included in the next Prettier release

**Comment by lipis** [comment]
Speaking of which.. it's been almost a month since the last release :)

**Comment by revelt** [comment]
hi guys,
I came back here to leave some feedback. So, now we have the ignore comment but it's not enough - now I have to wrap the tables with prettier-ignore comments, manually fix the long lines... until I edit the table. Then I repeat the process again. But Prettier was meant to automate editing, wasn't it?

How nice would it be if the table algorithm was even smarter and we didn't need any prettier-ignores, if it just didn't do anything to the table line if the prettifying action resulted in row length, longer than recommended line length (arbitrary number, but usually `80` characters).

The markdown table rows could be skipped if they already are beyond max line length, plus algorithm would skip rows if it produced row longer than that length...

And line length could be set to _really_ high, like 200 characters. Still, that would catch nearly all cases of excessively normalised markdown table lines.

Currently, I believe **we didn't solve this markdown table issue yet**.

**Comment by revelt** [comment]
@ikatyang ok. Thank you for taking care of this 👍
