### ISSUE TITLE
Range formatter weird indent with ClassDeclaration

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#4206]
When range formatting a ClassDefinition, there is an offset which is the same as `class`.

Original issue prettier/prettier-vscode#398

`echo -e "export default class Foo{\n/**/\n}" | prettier --range-start 16 --range-end 31`
```js
export default class Foo {
                 /**/
               }
```
This behavior differs from:
`echo -e "export default function Foo(){\n/**/\n}" | prettier --range-start 16 --range-end 31`
```js
export default function Foo() {
  /**/
}
```

Those 2 following behavior look similar:
`echo -e "/*     */      function Foo(){\n/**/\n}" | prettier --range-start 16 --range-end 31`
```js
/*     */      function Foo() {
                 /**/
               }
```
`echo -e "/*     */      class Foo{\n/**/\n}" | prettier --range-start 16 --range-end 31`
```js
/*     */      class Foo {
                 /**/
               }
```

### Expected
I expect `export default` to be part of ClassDeclaration, they shouldn't increase indentation. Behave the same as with `function`
For **comment** and **whitespace** case, I don't know what to expect 😞 It may be already what I would expect.

**Comment by wKich** [comment]
Is any progression?

**Comment by evilebottnawi** [comment]
It is open source, PR welcome

**Comment by wKich** [comment]
@evilebottnawi can you clarify where from can I start to debug this issue?

**Comment by evilebottnawi** [comment]
https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L2349

**Comment by thorn0** [comment]
Closing in favor of https://github.com/prettier/prettier/issues/4926
