### ISSUE TITLE
Typescript: casting as any breaks code

### ISSUE THREAD

**Issue by leejh3224** [prettier/prettier#4207]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAttA5hCBnOAAgEM8SoBPASgDoAFAJwnQEsDCBeQrAGwgCNiPek1YEQAGhAQADjBbQ8yUMQZMA7nVUIlKYgDcILACaSQpGMgBmQglP4NiYANZwYAZRlOWULMhgMAK5wUsYQYNa2ISA+BAwwjMRY6MSRPHYgAFZ4AB4AQo4ubu7E6HAAMj5waRkQgTAy9QBMNdFeDHHIIDAUMnB4YAwscmYyQ7AA6iYwABbIABwADFJj+HATjjJdY-1wDPrVUgxwAI6BLMeJyalINunRBKytUng+vHAAioEQ8M-dxPwpsZZsgmlIAsQWDw3gBhZgpLpQaCHECBAgAFQBujuBAAvrigA)
```sh
--parser typescript
--no-semi
```

**Input:**
```tsx
(mongoose as any).Promise = global.Promise
```

**Output:**
```tsx
;(mongoose as any).Promise = global.Promise

```

**Expected behavior:**

Typescript: casting as any should not produce unnessary semicolon in front of parenthesis.

**Comment by ikatyang** [comment]
See https://prettier.io/docs/en/rationale.html#semicolons.

**Comment by ikatyang** [comment]
Did it break your code?!

**Comment by leejh3224** [comment]
TS lint gives me two warnings.

First one is "Unnecessary semicolon" and second one is "statements are not aligned" errors.

Right now I'm disabling prettier by adding /* prettier-ignore */ on top of my code.

![2018-03-26 10 30 48](https://user-images.githubusercontent.com/25929117/37909252-5eef6294-3145-11e8-8fb9-3451322375c5.png)

**Comment by ikatyang** [comment]
We recommend you to use [`tslint-config-prettier`](https://github.com/alexjoverm/tslint-config-prettier) to disable rules conflict with prettier, see https://prettier.io/docs/en/eslint.html#turn-off-eslint-s-formatting-rules for similar reason.

**Comment by leejh3224** [comment]
It works well. Lovely!
