### ISSUE TITLE
prettier-1.11.1.tgz is being published on npm

### ISSUE THREAD

**Issue by ankurk91** [prettier/prettier#4209]
Hi,

You can check that a **.tgz** file is also being published on npm
see
https://unpkg.com/prettier@1.11.1/

Here is how to keep unwanted files out of package
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by lydell** [comment]
Thanks! We're already aware of this issue: #4179

(tgz is a pretty unique search keyword here)

**Comment by lydell** [comment]
Duplicate of #4179
