### ISSUE TITLE
Option for brace style

### ISSUE THREAD

**Issue by Narvey** [prettier/prettier#4212]
I would like to see an option to change the brace style between:
```
function doThis(){
  blah;
}
```
(1TBS)

**AND**

```
function doThis()
{
  blah;
}
```
(perhaps you could call the option C# or K&R style, though I expect this to be language-independent)

**Comment by evilebottnawi** [comment]
@Narvey plugins have ability to change default option and introduce own

**Comment by lydell** [comment]
Here are the top three search results for "brace style" in this issue tracker:

- #3964
- #3832
- #3807

They are all closed. In other words, this has been discussed before and won't happen.
