### ISSUE TITLE
Need help setting up .prettierignore

### ISSUE THREAD

**Issue by mssngr** [prettier/prettier#4215]
Version Prettier 1.11.1

I am probably setting up my .prettierignore incorrectly. Looking for somebody to correct me. I am trying to get Prettier to stop formatting my `.eslintrc` file. So, I set up my `.prettierignore` file like so:

**.prettierignore**
```
.eslintrc
```

But it still formats it on save.
![2018-03-27_17-18-16](https://user-images.githubusercontent.com/23464169/38000202-b130c4dc-31e3-11e8-8f1a-f00b787760dd.gif)

I've also tried...
**.prettierignore**
```
**/.eslintrc
./.eslintrc
*.eslintrc
```
...and every other combination I can think of. I'm obviously doing something wrong.

**Expected behavior:**
For it _not_ to format my files that I've told it to ignore.

**Comment by ikatyang** [comment]
Can you provide more information or a repro repo? It works for me in VSCode:

(.prettierignore)

```
.eslintrc
```
