### ISSUE TITLE
`prettier-ignore` mangles template literal css string by swapping parts of lines in output

### ISSUE THREAD

**Issue by jesstelford** [prettier/prettier#4218]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAwB0oACayLCAJyWoBJgAHRiD1agXgB81Lj1T4YACzgBbOPnpNxHAIaMVAc3UdJAXwDcVWgHoAVCMZwYMInEYBaIhqhM41U8aNtO3XgOGivPioMipYWNQA-NQA5ABm0DD2qEQAXnAsAAz4AByy+jHULDExBlRkIAA0IDw20KjIoGrcAO4ACmoIDSgqJBBEuFUgKujIcWGocNUARupgANZWAMqqYERQGsgwjACuUyC4EGBjE-vrk4wwbeoaoSdYk9UAVqgAHgBCc4swSypyADLrOD3R41HYwDjggBMIP2qkYF2QIGmKmm2GgQy46xgAHUBlJkDlMtVRJMcdokVw4BcSMDqpYAI47IiWa6aO5IcYPfaTGRELa7HnrDQ4ACKOwg8Fh1RgqLxuAJSChMvURCwwoAwhAZByQC4oHSQDtJgAVVHdLmTXS6IA)

**Input:**
```jsx
styled.div`
  color: ${props => props.theme.colors.paragraph};
  /* prettier-ignore */
  ${props => props.small ? 'font-size: 0.8em;' : ''};
`
```

**Output:**
```jsx
styled.div`
  color: ${props => (props.small ? "font-size: 0.8em;" : "")};
  /* prettier-ignore */
  ${props => props.theme.colors.paragraph};
`;

```

**Expected behavior:**

To not produce broken output.

**Notes:**

Note the redundant semi-colon at the end of the last line of input. This is to work around #2291. However, if we [remove that semicolon](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAwB0oACayLCAJyWoBJgAHRiD1agXgB81Lj1T4YACzgBbOPnpNxHAIaMVAc3UdJAXwDcVWgHoAVCMZwYMInEYBaIhqhM41U8aNtO3XgOGivPioMipYWNQA-NQA5ABm0DD2qEQAXnAsAAz4AByy+jHULDExulRkIAA0IDw20KjIoGrcAO4ACmoIDSgqJBBEuFUgKujIcWGocNUARupgANZWAMqqYERQGsgwjACuUyC4EGBjE-vrk4wwbeoaoSdYk9UAVqgAHgBCc4swSypyADLrOD3R41HYwDjggBMIP2qkYF2QIGmKmm2GgQy46xgAHUBlJkDlMtVRJMcdokVw4BcSMDqpYAI47IiWa6aO5IcYPfaTGRELa7HnrDQ4ACKOwg8Fh1RgqLxuAJSChMvURCwwoAwhAZByQC4oHSQDtJgAVVHdLmTXS6IA), we get an error!

Weirder still: The issue doesn't occur when [the comment is anything else other than `prettier-ignore`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAwB0oACayLCAJyWoBJgAHRiD1agXgB81Lj1T4YACzgBbOPnpNxHAIaMVAc3UdJAXwDcVWgHoAVNVQQ5UolA3VTxo207deA4aN75UMlVixqAH5qAHIAM2gYAFpUIgAvOBYABnwADll9UOoWUNDdKjIQABoQHhgiaFRkUDVuAHcABTUEapQVEggiXBKQFXRkcP9UOFKAI3UwAGs4GABlVTBbDWQYRgBXUZBcCDBB4a3bEcYYRvUNP32sEdKAK1QADwAhSZn5lTkAGVs4K5uy9YwDiAgBMfy2qkYx2QIDGKjG2GgvS4thgAHVulJkGlkqVRCM0doYVw4McSL9Sow4ABHdZEKlnTSXJBDa5bEYyIirDbs5Y4ACK6wg8HBpRg8IxuCxSBBYvURCwywAwlZmSAoNAKSB1iMACrwtqska6XRAA).

**Comment by j-f1** [comment]
cc @evilebottnawi

**Comment by evilebottnawi** [comment]
@j-f1 i will look on this in near future, but i think it is difficult, but possible

**Comment by evilebottnawi** [comment]
Problem inside `replacePlaceholders` (`quasisDoc` and `expressionDocs` have valid value), search how to fix,

**Comment by evilebottnawi** [comment]
@j-f1 Situation:
When we use `/* prettier-ignore */` it is ignore `@prettier-placeholder` and `replacePlaceholders` don't work as expected. First we concat in `["@", "prettier-placeholder"]` and when found second `@prettier-placeholder` - already concatenated (because we says prettier ignore this line and don't parse as `at-rule`) and replace on first expression. When we concat `["@", "prettier-placeholder"]` to `@prettier-placeholder` and replace on second expression. I don't have a lot of knowledge with multi parser. `CSS` printer works as expected.

**Comment by evilebottnawi** [comment]
Fixed :+1:
