### ISSUE TITLE
JSX {" "} spaces

### ISSUE THREAD

**Issue by Kosai106** [prettier/prettier#4223]
Is there any way at all to stop Prettier adding these horribly ugly spaces?
Perhaps just _not_ format strings like this if it needs to add spaces like this.

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgBZwDZ4QAEqAhkdgE5wBmAvADogDETRMplA5nDIyAH0ARnlJQA1k0wAZAJIA5ANKoA9KUxEA7hEp4AJqqwgANCAjoYAS2gBnZKE6UImgAqcEdlKQBuES3pMQUhsYZBpSPBs4UyFKUjBxXgBldHjLKC5kGEoAV2iQPQgwMIio03SoyhgXOK4AW1ISyPyAKxsADwAhOITk0jq4aXS4JrKzHJh0CYAmUfzUykrkECFSIQBPQihA9Ep0mAB1fxhsZAAOAAZTXYgog7j0Zd24Su8R02oARxzLahrSeqNJDhZqmKJ1SxZXL5GzpLh4OAARRyEHgc1MHCERz0J2Q0wxcUseDhAGEIHUGssoNB3iAclEACprTwgqIAXzZQA)

**Input:**
```jsx
<p>hello <a href="#" target="_blank">LINK</a> world</p>
```

**Output:**
```jsx
<p>
  hello{" "}
  <a href="#" target="_blank">
    LINK
  </a>{" "}
  world
</p>;

```

**Comment by timothykang** [comment]
An alternative might be to use the HTML entity representation of the breaking space, `&#32;`:

```jsx
<p>
  hello&#32;
  <a href="#" target="_blank">
    LINK
  </a>&#32;
  world
</p>;
```

**Comment by lydell** [comment]
@timothykang That’s not better, is it? `{" "}` – obviously a space. `&#32;` – could be anything. Both have the same length.

**Comment by timothykang** [comment]
The length is the same, but I disagree that the entity "could be anything". While I see the ASCII code might be a bit cryptic, the entity canonically represents the normal space as a single unit.

That being said, I'm just pointing out an alternative. Do as you see fit. 😀

**Comment by josephfrazier** [comment]
> While the ASCII code might be a bit cryptic

Yeah, it's not so much that it *actually* "could be anything", but that the developer might think it "could be anything" before researching it.

**Comment by Kosai106** [comment]
How about a boolean value in the config to allow|disallow formatting a string if it means adding spaces in this manner?

Something like:

| DEFAULT | CLI OVERRIDE | API OVERRIDE   |
|---------|--------------|----------------|
|         |              |                |
| `false`    | `--jsx-ignore-line-break`  | `jsxIgnoreLineBreak: <bool>` |

**Comment by j-f1** [comment]
@Kosai106 See https://prettier.io/docs/en/option-philosophy.html.

**Comment by hawkrives** [comment]
@Kosai106 Just to be clear, Prettier _has_ to add those spaces when it breaks over multiple lines. 

With HTML, whitespace between two tags is collapsed to a single space - 

```html
<span>
    a
        <strong>tag</strong>
</span
```

will produce "a **tag**". 

With jsx, though, trailing and leading whitespace on a line is removed:

```js
<span>
    a
        <strong>tag</strong>
</span
```

becomes "a<b>tag</b>". 

You have to add `{" "}` if you want the space to show up, if the space is at the end or beginning of the line. 

The only way to avoid the explicit space is to not have leading/trailing whitespace, and instead keep all of the whitespace that needs to be kept between the tags on any given line:

```js
<span>
    a <strong>tag</strong>
</span
```

That will produce "a **tag**", just like the HTML one. 

---


I think everything I wrote here is correct. Anyway, I just wanted to clarify that the ugly spaces are actually semantically important to JSX, unlike HTML, so Prettier really _can't_ add an option to not print them.

**Comment by Kosai106** [comment]
@hawkrives What you wrote is correct, yes.

But an option to ensure it __doesn't__ break the code onto multiple lines _if_ there's a need to add those types of spaces, would be ideal I believe - Otherwise Prettier is useless in JSX for me and the people I work with.

**Comment by mrchief** [comment]
@Kosai106 Prettier's output here is the right thing in JSX. JSX's space handling is [different](https://reactjs.org/docs/jsx-in-depth.html#string-literals-1). It is important to draw out attention to this fact in your code so that subsequent developers do not glance over this subtle difference.

P.S. And yes, I also had the same WTF reaction the first time I saw prettier doing this. 😄

**Comment by suchipi** [comment]
Maybe the empty spaces should get broken across lines like the other JSX children are?
```jsx
<p>
  hello
  {" "}
  <a href="#" target="_blank">
    LINK
  </a>
  {" "}
  world
</p>;
```

cc @karl @vjeux

**Comment by lydell** [comment]
Don't forget Facebook's own JSX space rules. See https://github.com/prettier/prettier/pull/1671 and https://github.com/prettier/prettier/issues/1581#issuecomment-300975032

**Comment by karl** [comment]
When I first worked on the JSX formatting I did have it always put {“ “} on a line by itself, but decided to put it at the end of the previous line after some discussion:

https://github.com/prettier/prettier/issues/1582

My gut feeling on this is that either way we print this (end of line or line by itself) there will be some pros and cons. So I’d only suggest changing this if we can show that the pros of having it on a line by itself heavily outway any cons.

**Comment by justin-calleja** [comment]
For some reason, formatting is done properly (without the extra `{' '}`) when I rename the file to have a `.jsx` extension. (Note: I am using `prettier` through an `eslint` plugin). Here's my `.eslintrc` if that makes any difference:

```
{
  "extends": ["react-app"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "printWidth": 120,
        "tabWidth": 4,
        "singleQuote": true,
        "trailingComma": "all"
      }
    ]
  }
}
```

(I'd rather not have to stay renaming files to `.jsx`).

**Comment by j-f1** [comment]
@justin-calleja That shouldn’t happen. Is Prettier/ESLint run on `.jsx` files?

**Comment by Kosai106** [comment]
@justin-calleja Are you sure Prettier is running correctly? As far as I can tell, there's no way to disable this behaviour. _(Sadly.)_

One reason why you haven't noticed, could be because your `printWidth` is larger than the default.

**Comment by justin-calleja** [comment]
@Kosai106 no please disregard my message. It was a fault on my end. I think I have a Prettier plugin (or some other formatter) in my VSCode setup which auto formats on save. I was experimenting on the current project to format on save through eslint (with prettier plugin). There must have been some conflict between the two... I forgot I switched to another project and enabled the editor's format on save setting (as this project did not have the eslint setup to format on save). Going back to this project, both pieces of software were formatting on save and I got very unpredictable results.

My fault - I now put a project specific `settings.json` file in the project that formats through eslint / prettier plugin.

Sorry, not completely sure about my own setup... I just want to format on save ^^; (copy / pasted my way through).

Thanks!

**Comment by Pyrolistical** [comment]
I don't understand why prettier only break when it doesn't need to introduce `{" "}`

Isn't this easier to read?
```jsx
<p>
  hello <a href="#" target="_blank">
    LINK
  </a> world
</p>;
```

**Comment by Kosai106** [comment]
@Pyrolistical That's pretty much what I'm suggesting - At the very least as a setting, although at this point I've just stopped using Prettier for my React code.

**Comment by Pyrolistical** [comment]
I'm in the "no settings" camp, which is why I'm trying to just change this rule for everybody. I really don't understand how more people would prefer their code littered with `{" "}`

**Comment by karl** [comment]
I personally do prefer my code formatted with `{" "}` as I like that it keeps tags on separate lines to text, making it easier to find opening tags.

Because it was a simple change to make I've created a PR that shows how Prettier would behave if we never introduced `{" "}`. Look at the updated test snapshots here:

https://github.com/prettier/prettier/pull/4669

If anyone wants to add this as an option to `prettier-miscellaneous` (https://github.com/arijs/prettier-miscellaneous) then it should be easy to do!

**Comment by duailibe** [comment]
@hellatan that's a bug in https://github.com/yannickcr/eslint-plugin-react

**Comment by hellatan** [comment]
thanks @duailibe. i'll look into it there then

**Comment by j-f1** [comment]
Specifically, the issue is https://github.com/yannickcr/eslint-plugin-react/issues/1717.

**Comment by bschwartz757** [comment]
Did anyone find a way to remove these? I've got a stock CRA that I ran CLI formatting on:
`prettier --single-quote --print-width 80 --tab-width 2 --write "src/**/*.{js,jsx,json,css}"` and now it's got `{' '}`'s all over the place. Hoping I don't have to manually remove them all....

**Comment by NaumanAhamad** [comment]
Does any one had a sollution or just infiniting your comments

**Comment by NaumanAhamad** [comment]
Please let me no the sollution couldn't find any where

**Comment by NaumanAhamad** [comment]
> How about a boolean value in the config to allow||disallow formatting a string if it means adding spaces in this manner?
> 
> Something like:
> 
> DEFAULT	CLI OVERRIDE	API OVERRIDE
> `false`	`--jsx-ignore-line-break`	`jsxIgnoreLineBreak: <bool>`
> Yes, the wording might need some changes - I'm no good at naming things.

Bro this configuration setting is disable from the docs please update

**Comment by Kosai106** [comment]
@NaumanAhamad This is a conversation discussing the inclusion of a config like this, nothing more for now, so of course the commands you find in here aren't working.

**Comment by toobulkeh** [comment]
what about `&nbsp`?

**Comment by JemarJones** [comment]
Still no update on this? I can't really fathom how anyone thinks that adding these spaces is _prettier_ than the alternative.. It's something completely unnatural and looks like machine generated code..

**Comment by acidjunk** [comment]
FWIW: I increased my "printWidth" to 120 and Instead of a lot {" "} it's now on a couple of places -> Decent React readable code.

**Comment by Kosai106** [comment]
Just figured I'd give my two cents on this since I posted the issue - I no longer have any issue with this personally. 🤷‍♂

**Comment by minimaldesign** [comment]
This is issue's been open for a couple of years. Is it safe to assume that "it's a feature, not a bug"?

No offense. I think prettier is totally awesome. But this is a deal breaker for me and I'm trying to figure out my options…

**Comment by lydell** [comment]
> Is it safe to assume that "it's a feature, not a bug"?

Yes.

**Comment by noudadrichem** [comment]
Any update on this? I'm using TSX. And still get this `{' '}`. Can't find a way to disable it..

**Comment by lydell** [comment]
No updates, no way to disable it.

I wonder if it makes sense to make the `proseWrap` option apply to JSX? I usually set `proseWrap: never` in my projects these days, since it gives nicer `git diff`. For example, try to spot the _actual_ change here: https://github.com/lydell/LinkHints/pull/7/files.

**Comment by thorn0** [comment]
It wouldn't. If you need whitespace between text and a subsequent element on the next line, you can't avoid `{" "}`.

**Comment by noudadrichem** [comment]
I think it's not alway about Whitespace. Also about formatting code with more spaces or new lines.

**Comment by thorn0** [comment]
What alternative do we have? Let's take this code for example:

**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgBZwDZ4QAEqAhkdgE5wBmAvADojYwzoDOSA9FwOYCWMbAFcARgDpIAWy7pqrfnEqz5MRcv7t2wuOy4AWAEyGAzAGJN2uNKkIYAWgBsARn2OADCYCcAVgDsTEQwpJS8cDCMIAD6onikUADWTJgAMhDUUkT8HMKZACYQhJRE7IJEpLYwWTn5heklZRXhqFykmEQA7ul4eS1YIAA0IBDoatDsyKAhlBAdAAohCBMopHgdpACeE0OilKRgCeEAyuj7-FC8yDCUOkMsUngA6tiCuqdgcEdLgvwAboIbZDgLSDEDndhKGBzPa8KSkZA0VYQoYAK3YAA8AEJ7A7HJopc5wBFIuCojFHc68PBwACKwgg8GJeGRIFOlAhlCBolIonwoLk5xgj34eSEyAAHO4hnIIBDHnt0EC5LolL8iUMAI70+DQkbLECkdj2KBwOB5M2g6ha-jUaGkWHwpCI5mkkAQqT8K43V2lC7UukMolOklDYKiYWi7DIQyhvb8PCUgDCECkcKBuh8oOEEIAKjzls6Wb8dABJKDm2BHMCUbIwACC5aOMA21KZLMNMDbroKYC7QwgwjYg8MXYAvqOgA)

**Input:**
```jsx
<p>hello <a href="https://github.com/prettier/prettier/issues/4223#issuecomment-614603957" target="_blank">Lorem ipsum dolor sit amet ipsum dolor sit amet</a> world</p>
```

**Current output:**
```jsx
<p>
  hello{" "}
  <a
    href="https://github.com/prettier/prettier/issues/4223#issuecomment-614603957"
    target="_blank"
  >
    Lorem ipsum dolor sit amet ipsum dolor sit amet
  </a>{" "}
  world
</p>;
```

**Possible output if we try to avoid `{" "}`:**
```jsx
<p>
  hello <a
    href="https://github.com/prettier/prettier/issues/4223#issuecomment-614603957"
    target="_blank"
  >
    Lorem ipsum dolor sit amet ipsum dolor sit amet
  </a> world
</p>;
```

The version with `{" "}` looks better IMHO.

**Comment by amitava82** [comment]
This also breaks react-i18next translations when using Trans with html markup. Need to be a way to disable this.

**Comment by karl** [comment]
If anyone is interested as to what the problem is with `react-i18next` and the `Trans` component it is detailed in a closed issue in the `react-i18next` project:

https://github.com/i18next/react-i18next/issues/575

**Comment by tiotdev** [comment]
In React Native the inserted {" "} causes an exception (Text outside a <Text> component). There should definitely be an option to disable this annoying behaviour.

**Comment by thorn0** [comment]
@tiotdev Don't add text outside a component. 🤷‍♂️ Prettier just moves it around.

**Comment by tiotdev** [comment]
@thorn0 I am not adding text outside a component, I am adding a new component but whenever there is a space prettier formats it to {" "}

e.g.

![Screenshot 2020-05-25 at 14 03 31](https://user-images.githubusercontent.com/18411522/82811222-890c8600-9e90-11ea-9d90-fc44a12e7a94.png)


![Screenshot 2020-05-25 at 14 01 44](https://user-images.githubusercontent.com/18411522/82811113-506cac80-9e90-11ea-9caf-bbb54658fa7a.png)

**Comment by thorn0** [comment]
A space *is* text.

**Comment by tiotdev** [comment]
It's indentation

**Comment by panlina** [comment]
I understand that eslint is doing this to try to keep the whitespace rules of jsx, but I want to add that, this transformation is also changing the semantics of the original code.

Breaking `"hello "` into `"hello"` and `" "` may cause no harm in most cases where it's only displayed by html, but it may break things where the structure is significant. Previously mentioned https://github.com/i18next/react-i18next/issues/575 is an example. We can also imagine that a word processing application in React may rely on the structure of the DOM at runtime.

Anyway, this transformation is not strictly equivalent. The semantics is slightly changed and may break things in certain circumstances.

Prettier is pretty widely used nowadays. It may work with various kind of toolchains, building various kind of applications, I think prettier should at least provide an option to avoid this kind of "formatting".

**Comment by gauthierm** [comment]
This formatting breaks React Native code where all text in JSX needs to be wrapped in `<Text>` components. In this context, it makes more sense to omit entirely than try to preserve the code that causes an error. For example:

```tsx
<Text
  style={[styles.text, textStyle]}
  allowFontScaling={allowFontScaling}
>
  {title}
</Text>    <View style={styles.underline} />
```

becomes

```tsx
<Text
  style={[styles.text, textStyle]}
  allowFontScaling={allowFontScaling}
>
  {title}
</Text>{' '}
<View style={styles.underline} />
```

which is valid JSX, but causes a runtime error in React Native. It is a minor annoyance with prettier to constantly have to remove these `{' '}` spaces while quickly iterating code and not caring about formatting.

**Comment by Kosai106** [comment]
I'm closing the issue as I honestly don't believe it to be a problem anymore.

For those of you who have issues with Prettier formatting things you don't want, you can always throw a `// prettier-ignore` comment in your code and carry on. You can read more about it here: https://prettier.io/docs/en/ignore.html

**Comment by vjeux** [comment]
@gauthierm there is a runtime error in the code you actually wrote. Prettier makes it painfully obvious that it will happen by changing the way it is written. So in practice prettier in this case helps you prevent it where it may have gone unnoticed otherwise.

**Comment by panlina** [comment]
> I'm closing the issue as I honestly don't believe it to be a problem anymore.
> 
> For those of you who have issues with Prettier formatting things you don't want, you can always throw a `// prettier-ignore` comment in your code and carry on. You can read more about it here: https://prettier.io/docs/en/ignore.html

We want an option to disable this formatting and not care about adding `//prettier-ignore` everywhere.

**Comment by vjeux** [comment]
@panlina do you have a specific example where you add // prettier-ignore related to this issue that you’d be willing to share?

**Comment by panlina** [comment]
> @panlina do you have a specific example where you add // prettier-ignore related to this issue that you’d be willing to share?

We're doing i18n using our own babel plugin and we are meeting the same situation of https://github.com/i18next/react-i18next/issues/575.

Currently we've managed to solve this by adjusting our matching algorithm to treat `{' '}`, which is a `JSXContainer` node, as if it's a `JSXText` node.

But I still think it valuable to provide an option to disable this formatting.

**Comment by SeyyedKhandon** [comment]
Is there any solution to remove `{" "}` from code?[example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgBZwDZ4QAEqAhkdgE5wBmAvADogDETRMplA5nDIyAH0ARnlJQA1k0wAZAJIA5ANKoA9KUxEA7hEp4AJqqwgANCAjoYAS2gBnZKE6UImgAqcEdlKQBuES3pMQIUpSMHFeAGVSAFs4aUsoOGQaUjwbOFNg0PCYCPRQhK5kGEoAVwyQOGihOD09WukxLlLSHgAxHWjSGCsoIq9SmAhA7BhovAB1bEt4G3ywOAiPGctvGYBPZHAbO1ME9MoYFxCuLuTU9NMAKxsADwjCvDgARVKIeHO0ivzKA62hUg1PCBdCUBIwCb+GDYZAADgADKZQRB0hMQugtqC4AdvElTABHN7wY7mTwgUg2AC0iVqtUC1EJlmox1aZyQKS+pnS0UsxTKFRsjxeRKS7IuFQ4QkhemhyAATKYSqRLHhCgBhCDRNkgKDQPEgUrpAAqgM8HMuIG85VkUHqsAiYDBFgAgraIjB1k9PhaKTBvRU9BAwP7rncAEIhMKRGJxBKi80VCCDdCDOX+gC+6aAA)

**Comment by Kosai106** [comment]
> Is there any solution to remove useless `{" "}` from code?[example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgBZwDZ4QAEqAhkdgE5wBmAvADogDETRMplA5nDIyAH0ARnlJQA1k0wAZAJIA5ANKoA9KUxEA7hEp4AJqqwgANCAjoYAS2gBnZKE6UImgAqcEdlKQBuES3pMQIUpSMHFeAGVSAFs4aUsoOGQaUjwbOFNg0PCYCPRQhK5kGEoAVwyQOGihOD09WukxLlLSHgAxHWjSGCsoIq9SmAhA7BhovAB1bEt4G3ywOAiPGctvGYBPZHAbO1ME9MoYFxCuLuTU9NMAKxsADwjCvDgARVKIeHO0ivzKA62hUg1PCBdCUBIwCb+GDYZAADgADKZQRB0hMQugtqC4AdvElTABHN7wY7mTwgUg2AC0iVqtUC1EJlmox1aZyQKS+pnS0UsxTKFRsjxeRKS7IuFQ4QkhemhyAATKYSqRLHhCgBhCDRNkgKDQPEgUrpAAqgM8HMuIG85VkUHqsAiYDBFgAgraIjB1k9PhaKTBvRU9BAwP7rncAEIhMKRGJxBKi80VCCDdCDOX+gC+6aAA)

[Yes](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VAHATnGMCWcWAtPgOZQQ4A6UAPBgHwAWcANmxAAR0CGXzHADMAvNRABicVxi8sZXGJAB9AEZteUANbjGAGQCSAOQDSdVL0ZcA7lTYATc0xAAaEBAwFoAZ2Sg5WBDWAApyCL4ovABuEPj2riCqWLxgWrgAyrwAtnB6+FBwyEK8bN5wbkkpaTDpGCn5ZMgwWACu5SBwWapw9vY9eppkLbwKAGJUWbx4DcggvC0wEAnMMFlsAOrM+PDedWBw6eHb+FHbAJ6zYN6+bvllWDDByWSTRSVlbgBW3gAe6Q1sOAARRaEHgb1K7TqWHus1UvG6bAS2HyMHWcRgzGQAA4AAxubAQMrrZIYWbYOD3KKFNwAR1B8CeHgic28xAKPR6CRw9PwOCeI1eSGKkLcZSy+CarXa3gBwIZhWF73aslU6PsmOQACY3M1ePg2A0AMIQLJCkCUAoJFplAAqCIiIo+ICibQMUD6sHSYCw+E8AEEPekYGdARDnbxvDBw+17BAwDGvr8AELJVIZbK5fKKp3tCALDALLUxgC+JaAA)

**Comment by SeyyedKhandon** [comment]
> > Is there any solution to remove useless `{" "}` from code?[example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgBZwDZ4QAEqAhkdgE5wBmAvADogDETRMplA5nDIyAH0ARnlJQA1k0wAZAJIA5ANKoA9KUxEA7hEp4AJqqwgANCAjoYAS2gBnZKE6UImgAqcEdlKQBuES3pMQIUpSMHFeAGVSAFs4aUsoOGQaUjwbOFNg0PCYCPRQhK5kGEoAVwyQOGihOD09WukxLlLSHgAxHWjSGCsoIq9SmAhA7BhovAB1bEt4G3ywOAiPGctvGYBPZHAbO1ME9MoYFxCuLuTU9NMAKxsADwjCvDgARVKIeHO0ivzKA62hUg1PCBdCUBIwCb+GDYZAADgADKZQRB0hMQugtqC4AdvElTABHN7wY7mTwgUg2AC0iVqtUC1EJlmox1aZyQKS+pnS0UsxTKFRsjxeRKS7IuFQ4QkhemhyAATKYSqRLHhCgBhCDRNkgKDQPEgUrpAAqgM8HMuIG85VkUHqsAiYDBFgAgraIjB1k9PhaKTBvRU9BAwP7rncAEIhMKRGJxBKi80VCCDdCDOX+gC+6aAA)
> 
> [Yes](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VAHATnGMCWcWAtPgOZQQ4A6UAPBgHwAWcANmxAAR0CGXzHADMAvNRABicVxi8sZXGJAB9AEZteUANbjGAGQCSAOQDSdVL0ZcA7lTYATc0xAAaEBAwFoAZ2Sg5WBDWAApyCL4ovABuEPj2riCqWLxgWrgAyrwAtnB6+FBwyEK8bN5wbkkpaTDpGCn5ZMgwWACu5SBwWapw9vY9eppkLbwKAGJUWbx4DcggvC0wEAnMMFlsAOrM+PDedWBw6eHb+FHbAJ6zYN6+bvllWDDByWSTRSVlbgBW3gAe6Q1sOAARRaEHgb1K7TqWHus1UvG6bAS2HyMHWcRgzGQAA4AAxubAQMrrZIYWbYOD3KKFNwAR1B8CeHgic28xAKPR6CRw9PwOCeI1eSGKkLcZSy+CarXa3gBwIZhWF73aslU6PsmOQACY3M1ePg2A0AMIQLJCkCUAoJFplAAqCIiIo+ICibQMUD6sHSYCw+E8AEEPekYGdARDnbxvDBw+17BAwDGvr8AELJVIZbK5fKKp3tCALDALLUxgC+JaAA)

It will ignore the prettier... So it is not the solution...

**Comment by MikeAlvarado** [comment]
Looking forward a way to disable this as well. 👀

**Comment by Brysonmk1984** [comment]
If this isn't getting addressed, I'd like to know if there are any other formatters out there that aren't religiously opinionated about silly things like this?

**Comment by potatosenior** [comment]
helloo, how can i disable this within one file only?

**Comment by ajnozari** [comment]
> I'm closing the issue as I honestly don't believe it to be a problem anymore.
> 
> For those of you who have issues with Prettier formatting things you don't want, you can always throw a `// prettier-ignore` comment in your code and carry on. You can read more about it here: https://prettier.io/docs/en/ignore.html

This is NOT the solution, this should be able to be disabled project wide.

**Comment by AI-93s** [comment]
Has anyone found an answer on how to solve **this problem**?

**Comment by Kosai106** [comment]
> This is NOT the solution, this should be able to be disabled project wide.

Then don't use Prettier.

**Comment by simpsonphile** [comment]
prettier staff is so annoying

**Comment by dhiegomaga** [comment]
So annoying, I was getting a mf error because of this for like 30 min, jesus stop adding useless characters

**Comment by akhilalekha** [comment]
Hi currently I'm facing a problem with prettier deleting this space inside a jsx element but i actually need this space. Can anyone tell me how to get this space back?!

**Comment by Justin99b** [comment]
@dhiegomaga is completly right, Prettier should not add any characters but should just format. I think there should really be an option to Disable adding characters like this since i only want to format something and not add Characters while doing so.

**Comment by cheshrkat** [comment]
While this has been closed I'll add a comment in case it's ever resurrected...

We use JSX for a documentation site, meaning we have prose in JSX. Maintaining prose quickly becomes annoying when Prettier stuffs it full of `{" "}` as you have to remove them before making your edits. This is not application code, it's documentation - and no we can't and don't produce these pages with markdown so that's not an option.

We are left having to ignore that whole section of the repo, or inject ignore comments in a large number of files (and then try to ensure everyone remembers to preserve those comments etc etc). A setting similar to the markdown prose settings might make sense here instead; or even just a way to configure "preserve" for line length.

I realise Prettier doesn't want to add lots of options, but in this case it's altering the code in a really unhelpful/unproductive way; and being able to control that would make Prettier more useful to us.

**Comment by vietanh171002** [comment]
Thats beacause file .js is not compatible with HTML inside it. Change your file extension to .jsx will fix it

**Comment by landsman** [comment]
This is crazy

**Comment by tanchu** [comment]
THIS is crazy! 
this line 
`</TableRow> <TableRow>`
converts to 
```
<TableRow>{' '}
<TableRow>
```
But the same code (below) with trailing space works fine. Trailing space just removed after formatting.
`</TableRow> // here is trailing space
<TableRow>`

What's the difference between those two examples? Why the fist works "incorrect"?
