### ISSUE TITLE
RFC: Break strings in Error messages by converting to chain of `+`

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#4225]
I'll preface this by saying that I'm aware this proposal breaks our (occasionally-broken) "no changing the AST" rule.

I'm tired of doing this:
![2018-03-29 20 48 55](https://user-images.githubusercontent.com/1341513/38122640-6be8c5d0-3393-11e8-81a4-8ce0e6cc5105.gif)

I'd like to propose the following:

When a long non-template literal string appears within `throw new Error(...)` or `invariant(...)`, it should be broken across multiple lines by converting it to several string literals combined with `+`.

I think there are other places where we could do this, too (maybe everywhere), but I want to only start with Error messages, because I want to be careful about introducing AST changes, and Error messages are where I most commonly run into this.

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwHSoDOAkgCYIwapwBO2UE5AlE5sADpSaaRSEyYARqiikRAc0wBeTIUgAHOHmGiJhANoNyeKAEMAtnAC6Abk7cMOFWKiSpMqAFcANs9Ycu3TDAAWNCADumFBwQQCiNP505l7c7CAAKj5wmABuujSouoLOKfK6hIRwpJgiMBDeyZg0jlAA8lAAyrSptDy6rpgBBZhwqL5tDALk6CLFmBA01XDotDTj5Zi6mOLOEIIdlboC3YTBEMMzYyUilUSYo7l4mEkpNVAAtNAPRTStUxuCcM6Y8s6O4lOYF0XGgzgAnrJHPJ5JMBOlMtlcntfNtSgJgVx+NtUMDXJD5oQIM5Wnh4jFuEwzJ4AL6cOlQEAAGhAEHklGghGQoAy-gCAAUMgguShdKkIKhSMyQAUYMh0B0iizBDRdGAANZwGCNfJgCTIGA1OAs0gQMDyxXGtB8Wgwfmq8T6XQW5xKkAAK0IAA8AEKqjVaxoGOAAGTGLrdEEcMHk0YATBGrfkaK9kCBPuC1oyWfJMrAAOqS3zIAAcAAYc-4ivnVfI07m4K9WtL5gBHRyoeb23SO51IBWuq1FfSoA1GlmECS5ACKjgOcETLJg2ULpGLSDjS9VqGcEgAwhB9E60wwQtLHEUEtkRQOijSaUA)

**Input:**
```jsx
if (t.isIdentifier(node)) {
  const binding = scope.bindings[node.name];
  if (binding == null) {
    throw new Error(
      "The variable passed into the runOnServer call was either not defined or referred to a global that was not defined in this file. The run-on-server babel plugin can only support variables that it can statically resolve."
    );
  }
}

```

**Proposed Output:**
```jsx
if (t.isIdentifier(node)) {
  const binding = scope.bindings[node.name];
  if (binding == null) {
    throw new Error(
      "The variable passed into the runOnServer call was either not defined " +
      	"or referred to a global that was not defined in this file. The " +
      	"run-on-server babel plugin can only support variables that it can " +
      	"statically resolve."
    );
  }
}

```

**Comment by aboyton** [comment]
Personally I'm not convinced, if I wanted this I'd use something like `oneLine` from [common-tags](https://github.com/declandewet/common-tags).

A question though, what is your plan if there's already existing concatenation? Does your algorithm basically join them and reflow them or do you keep the existing breaks and add new ones as necessary?

Examining the two possibilities, turning
```ts
throw new Error(
  "One line of text. " +
    "Another line of text that's a bit longer but still fits on one line."
);
```
into
```ts
throw new Error(
  "One line of text. Another line of text that's a bit longer but still fits " +
  "on one line"
);
```
seems less than desirable to me, but conversely if you have your original sample
```ts
if (t.isIdentifier(node)) {
  const binding = scope.bindings[node.name];
  if (binding == null) {
    throw new Error(
      "The variable passed into the runOnServer call was either not defined " +
      	"or referred to a global that was not defined in this file. The " +
      	"run-on-server babel plugin can only support variables that it can " +
      	"statically resolve."
    );
  }
}
```

and you indent everything by wrapping it in something like an `if` statement then do you just break lines and end up with a bunch of short strings?
```ts
if (someOtherCondition) {
  if (t.isIdentifier(node)) {
    const binding = scope.bindings[node.name];
    if (binding == null) {
      throw new Error(
        "The variable passed into the runOnServer call was either not " +
        "defined " +
      	"or referred to a global that was not defined in this file. The " +
      	"run-on-server babel plugin can only support variables that it can " +
      	"statically resolve."
      );
    }
  }
}
```
or do you reflow (and thus end up with noisy diffs)?
```ts
if (someOtherCondition) {
  if (t.isIdentifier(node)) {
    const binding = scope.bindings[node.name];
    if (binding == null) {
      throw new Error(
        "The variable passed into the runOnServer call was either not " +
        "defined or referred to a global that was not defined in this file. " +
        "The run-on-server babel plugin can only support variables that it " +
        "can statically resolve."
      );
    }
  }
}
```

**Comment by suchipi** [comment]
I would reflow, but I agree that when it's two different sentences, it looks odd (especially if there's a hanging cap).

**Comment by suchipi** [comment]
Maybe I should make a fixable eslint rule instead of this being part of prettier.

**Comment by lydell** [comment]
I usually let those error message lines be super long these days and rely on my editor and other tools displaying them wrapped. ¯\\\_(ツ)\_/¯

**Comment by suchipi** [comment]
Based on the discussion, I'll close this. Thanks for the input everyone!
