### ISSUE TITLE
Preserve lines

### ISSUE THREAD

**Issue by dashie** [prettier/prettier#4227]
Is it possible to preserve "new lines" character and do not joins lines?

**Comment by j-f1** [comment]
Can you add an example to clarify what you’re asking for? I’m afraid I don’t quite understand your request.

**Comment by dashie** [comment]
Imagine I write this constructor definition:

```
constructor(
  private authService: AuthService, 
       private spinnerService: Ng4LoadingSpinnerService)    {
}
```

I don't want that prettier joins the lines on a single line when it formats the file but simply indent them with the right tab spaces

```
constructor(
  private authService: AuthService, 
  private spinnerService: Ng4LoadingSpinnerService) {
}
```

So if I choose to split the line on more lines my CR must be preserved.

**Comment by j-f1** [comment]
It already does that for you:

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOkUmMATgK5gwS0AUZFADrQJYBu6eDnT0YACwDKcWnx5g4SHAEFRk6bPkAaHBwp6c3foLg5MnHlCjSpMuQpwA5AOYAWADIR0AEwtOJ5y2t1OwBKfVJyHABfMjIokE0QCE4YHmhMZFB0WloIAHcABWyEDJR0PggeLwSQLBhkADN0VEw4RIAjWnQwAGs4GH9u32Q6ejaQLwgwRubWxItW2hgCrqcAW3QZlvGAK0wADwAhLt7+iXQ1uDcLOC25pNFOUQAmO-HObMXkEBgAT044JgwLwUjVDLAAOpVcTIAAcAAZEtwIK0IV1ON9uID1LdErQ4ABHeg8fErdDrTZIJrbRKtNY8EYMcaYXyoOAARXoEHgb0SMHQ7ShXhhSGefK6PFQvgAwhA1htvlBoLiQPRWgAVAWlamtKJRIA)
```sh
--parser typescript
```

**Input:**
```tsx
class Foo {
  constructor(
  private authService: AuthService, 
       private spinnerService: Ng4LoadingSpinnerService)    {
  }

}
```

**Output:**
```tsx
class Foo {
  constructor(
    private authService: AuthService,
    private spinnerService: Ng4LoadingSpinnerService
  ) {}
}

```

(note that if you have a `printWidth` larger than 80, this might not happen — that’s why we recommend keeping it at 80)

**Comment by dashie** [comment]
It is not true, look at the [link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOkUmMATgK5gwS0AUZFOADrQJYBu6eDnT0YACwDKcWv15g4SHAEExUmXIUAaHBwo8BQuDkxdeUKDOmz5inFADmAFgCUnUuRwBfMj6ggtEAguGF5oTGRQdFpaCAB3AAVohAiUdH4IXgATAJAsGGQAM3RUTDhAgCNadDAAazgYSS4a8wdkOnpykCyIMCKSssDzMtoYBOqHAFt0ftKugCtMAA8AIWq6hsl0SbgAGXM4WcGgsS4xACYjrubaEeQQGABPLjhMMD4Q3INYAHVsiWQAA4AAyBHgQMo-apce4lOLoR4RQK0OAAR3ovBR43QUxmSGKc0CZUmvHaDC6mFaqDgAEV6BB4FdAjB0BU-lkAUhzszqrxUK0AMIQSbTe5QaCHQL0MoAFVZqQJZS8XiAA)

**Comment by j-f1** [comment]
Sorry, I was unclear. I meant that in the case you provided, the code would stay on multiple lines. Since Prettier tries to avoid looking at the original code when re-printing it (this helps maintain a consistent style), we probably won’t add support for this. If you want to keep newlines as-is, I’d recommend using a simpler formatter, such as the one most IDEs provide.

**Comment by dashie** [comment]
And if a would like to have always a parameter per line in the constructor=

**Comment by j-f1** [comment]
You could put `// prettier-ignore` on the line before the constructor.
