### ISSUE TITLE
prettier don`t format vue file

### ISSUE THREAD

**Issue by gwallan** [prettier/prettier#4229]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQVmoAmAlgG5m3UC8xIeWW7J5l-qAEa0ArgFoAFnDzU4AJ0KoA9MPFSZ83vwF1GYfAGcDbcNHiwyqsVjk9S2h1SsHmcQXgXLnr9wvuOBOQgReDkxelo4AHcyfTwjEyw8AHM4Ax5lIJD5cMiorUdlXQKKIoZeZUxcAjheUlQDMDlaLBheWmwIORhLUQAJaVk5MgAzIIwydgABSE6oBBgDFVFJQfl2AG5SDqwuntUAZR8PUfHJkBmIOYWl71lfTdJSOAAPXe6yWRG8ERwe4H8FCgeAwcCQ5043BAABpAbErrt5rADOCAXwHKoBho5LD0dpDsdbHiAL64-jUAh4AAUAEoyGiAnI4DARHJyMBiVsSaROfUlI1mq06lAGjAAJ44OBkfBQZImRpGOxQAB0+mkchGtBe9LhAC8IFdwQBGLnE0iqyUeTUvJBIPAjUI6vGQWALcHsc5c-hSWjJCQwcEABi9lAiLmEOFo4vBEmYsigIYodAM1TF4MEOAgYAA1onYpa5OmIDAJKbzWqTgzKBB6PIRpmojG4wgy1BzVZ607+PWIARwZKHa32ysxl3KD2+2Rmn6YK3lVYbGOKLsXDBaNBwUz8Gva3OrIIYOy4T6Z+CAEwADiwLzzgi6Q3BUGgcFv95ychkohRZAALNe80k1B0LKYgDgGZBGgAzP+cKAcByRiNO-rGtBN5wiMZhiC4upghBf5oXi8AvDAYh4JGyRQOCYALPIeZgKyBhdOCuy0K6ch5iIBg5FxkpgOBT7zHmABkSAYfRBhLtowQwJG8yPs+eZmm2eIicmeAZnA1BkpQQnKmpGnUJJ-B3nIQxiJAmaFmQADEcAAKz2fZeb8BZTE2WAACcnmeYpPLDuIB5QNYzQYB4YqSa5VnWSMMW3ngObJFkUDUOZECWeC1lnpBeBniMdnCXafEMFKVYYvF2aJcEyWpelNmBoGADsYBgNQvlQEp84rIFYhfD8fySSZD4QdeZCMZGhnWR5Rp4D+MhxQlSUpZFGUxSMdFpW51kOdtL5wiJ8U7iVcLGeVlUiNVy02dQghwAAbNIbUdU+FIwHgA2nYt4KsjgVLsMqSgdMkSjPZSypYLK7B0tRbGxDRwxPohcBYNIs5wu4C1VSl2G4UaZ6BiNuP4wR-AYKxqy+shZCQZBROtsoBjipKFQMxKUoynK7AKukICjZAyPULwqpmAsklwaxyTnkTZB4yNUsebTfkqkkqQSaVZCk0FJ6Uxe9UwXig3vp+nHgvhdP8oztSkDCIAQK065QAYyCgB4QRRAACh4CCOygeD0BAzDW-EMDIN8OBcdCICCB+ObMgcSRgOLyAwHIIhwBH1BZiHZHhyArFcd0bsfskoVZ2HacgAAVgYLwAELR9mscgnAAAyrFwKXOfSVgIRnh35dJHI+fIJH6kStA1s2KxMAAOrMCWyA6xHNgQFx08flgw82Gk8i1tbTIAI4iLQTKFykJeidn5dcaTScp1f4uSgAiiIxbtxfZcR69giz9Q89IGen8Py0FkskAAwlcc+IABLtwjpxOAAAVdS3tQ5cWJMSIAA)

**Input:**
```jsx
<template>
    <div id="app">
        <biu-header></biu-header>
        <div class="content biu-pr">
            <biu-sidebar></biu-sidebar>
            <router-view class="pages"></router-view>
        </div>
    </div>
</template>

<script>
import biuHeader from "@components/biu-header";
import biuSidebar from "@components/biu-sidebar";

export default {
    name: "app",
    components: {
        biuHeader,
        biuSidebar
    },
    data() {
        return {};
    }
};
</script>

<style lang="scss">
.clearfix {
    zoom: 1;
}
.clearfix::after {
    content: " ";
    height: 0;
    visibility: hidden;
    display: block;
    clear: both;
}
.clear {
    overflow: hidden;
}

.biu-fl {
    float: left;
}

.biu-fr {
    float: right;
}
.biu-pr {
    position: relative;
}
.biu-btn {
    height: 28px;
    border: none;
    border-radius: 4px;
    padding-left: 13px;
    padding-right: 13px;
    font-size: 14px;
    text-align: center;
    cursor: pointer;
    user-select: none;
    &:focus {
        outline: none;
    }

    &:disabled,
    &.disabled {
        border-color: #e5e5e5;
        color: #c9c9c9;
    }
}
.biu-btn-primary {
    color: #fff;
    background-color: #23a2f5;
    &:active {
        background-color: #007ccd;
    }
}
.biu-btn-default {
    border: 1px solid #91a4ad;
    background-color: #fff;
    color: #5e5e5e;
    &:active {
        background-color: #dbe6ea;
    }
}
.nodata {
    background: url("./img/nodata.png") center center no-repeat;
    background-size: 120px 120px;
    min-height: 330px;
}
</style>
<style lang="scss" scoped>
.content {
    padding: 20px 20px 0px 90px;
}
.pages {
    min-height: 800px;
    border-radius: 4px;
}
</style>

```

**Output:**
```jsx
SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (11:1)
   9 | </template>
  10 | 
> 11 | <script>
     | ^
  12 | import biuHeader from "@components/biu-header";
  13 | import biuSidebar from "@components/biu-sidebar";
  14 | 
```

**Expected behavior:**

**Comment by ikatyang** [comment]
Hi, you have to specify `--parser vue` on the playground.

![image](https://user-images.githubusercontent.com/8341033/38135107-dda3fa40-3448-11e8-804d-d656f08068d9.png)

<details>

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQVmoAmAlgG5m3UC8xIeWW7J5l-qAEa0ArgFoAFnDzU4AJ0KoA9MPFSZ83vwF1GYfAGcDbcNHiwyqsVjk9S2h1SsHmcQXgXLnr9wvuOBOQgReDkxelo4AHcyfTwjEyw8AHM4Ax5lIJD5cMiorUdlXQKKIoZeZUxcAjheUlQDMDlaLBheWmwIORhLUQAJaVk5MgAzIIwydgABSE6oBBgDFVFJQfl2AG5SDqwuntUAZR8PUfHJkBmIOYWl71lfTdJSOAAPXe6yWRG8ERwe4H8FCgeAwcCQ5043BAABpAbErrt5rADOCAXwHKoBho5LD0dpDsdbHiAL64-jUAh4AAUAEoyGiAnI4DARHJyMBiVsSaROfUlI1mq06lAGjAAJ44OBkfBQZImRpGOxQAB0+mkchGtBe9LhAC8IFdwQBGLnE0iqyUeTUvJBIPAjUI6vGQWALcHsc5c-hSWjJCQwcEABi9lAiLmEOFo4vBEmYsigIYodAM1TF4MEOAgYAA1onYpa5OmIDAJKbzWqTgzKBB6PIRpmojG4wgy1BzVZ607+PWIARwZKHa32ysxl3KD2+2Rmn6YK3lVYbGOKLsXDBaNBwUz8Gva3OrIIYOy4T6Z+CAEwADiwLzzgi6Q3BUGgcFv95ychkohRZAALNe80k1B0LKYgDgGZBGgAzP+cKAcByRiNO-rGtBN5wiMZhiC4upghBf5oXi8AvDAYh4JGyRQOCYALPIeZgKyBhdOCuy0K6ch5iIBg5FxkpgOBT7zHmABkSAYfRBhLtowQwJG8yPs+eZmm2eIicmeAZnA1BkpQQnKmpGnUJJ-B3nIQxiJAmaFmQADEcAAKz2fZeb8BZTE2WAACcnmeYpPLDuIB5QNYzQYB4YqSa5VnWSMMW3ngObJFkUDUOZECWeC1lnpBeBniMdnCXafEMFKVYYvF2aJcEyWpelNmBoGADsYBgNQvlQEp84rIFYhfD8fySSZD4QdeZCMZGhnWR5Rp4D+MhxQlSUpZFGUxSMdFpW51kOdtL5wiJ8U7iVcLGeVlUiNVy02dQghwAAbNIbUdU+FIwHgA2nYt4KsjgVLsMqSgdMkSjPZSypYLK7B0tRbGxDRwxPohcBYNIs5wu4C1VSl2G4UaZ6BiNuP4wR-AYKxqy+shZCQZBROtsoBjipKFQMxKUoynK7AKukICjZAyPULwqpmAsklwaxyTnkTZB4yNUsebTfkqkkqQSaVZCk0FJ6Uxe9UwXig3vp+nHgvhdP8oztSkDCIAQK065QAYyCgB4QRRAACh4CCOygeD0BAzDW-EMDIN8OBcdCICCB+ObMgcSRgOLyAwHIIhwBH1BZiHZHhyArFcd0bsfskoVZ2HacgAAVgYLwAELR9mscgnAAAyrFwKXOfSVgIRnh35dJHI+fICA9Cp9bNisTAADqzAlsgOsRzYEBcVPH5YMPNhpPItbW0yACOIi0EyhcpCXonZ+XXGk0nKeX+LkoAIoiMW7fn2XEevYIM-UHPSBnh-H5aCyWSAAYSuGfEAAl24R04nAAAKupb2ocuLEmJEAA)
```sh
--parser vue
```

**Input:**
```vue
<template>
    <div id="app">
        <biu-header></biu-header>
        <div class="content biu-pr">
            <biu-sidebar></biu-sidebar>
            <router-view class="pages"></router-view>
        </div>
    </div>
</template>

<script>
import biuHeader from "@components/biu-header";
import biuSidebar from "@components/biu-sidebar";

export default {
    name: "app",
    components: {
        biuHeader,
        biuSidebar
    },
    data() {
        return {};
    }
};
</script>

<style lang="scss">
.clearfix {
    zoom: 1;
}
.clearfix::after {
    content: " ";
    height: 0;
    visibility: hidden;
    display: block;
    clear: both;
}
.clear {
    overflow: hidden;
}

.biu-fl {
    float: left;
}

.biu-fr {
    float: right;
}
.biu-pr {
    position: relative;
}
.biu-btn {
    height: 28px;
    border: none;
    border-radius: 4px;
    padding-left: 13px;
    padding-right: 13px;
    font-size: 14px;
    text-align: center;
    cursor: pointer;
    user-select: none;
    &:focus {
        outline: none;
    }

    &:disabled,
    &.disabled {
        border-color: #e5e5e5;
        color: #c9c9c9;
    }
}
.biu-btn-primary {
    color: #fff;
    background-color: #23a2f5;
    &:active {
        background-color: #007ccd;
    }
}
.biu-btn-default {
    border: 1px solid #91a4ad;
    background-color: #fff;
    color: #5e5e5e;
    &:active {
        background-color: #dbe6ea;
    }
}
.nodata {
    background: url("./img/nodata.png") center center no-repeat;
    background-size: 120px 120px;
    min-height: 330px;
}
</style>
<style lang="scss" scoped>
.content {
    padding: 20px 20px 0px 90px;
}
.pages {
    min-height: 800px;
    border-radius: 4px;
}
</style>

```

**Output:**
```vue
<template>
    <div id="app">
        <biu-header></biu-header>
        <div class="content biu-pr">
            <biu-sidebar></biu-sidebar>
            <router-view class="pages"></router-view>
        </div>
    </div>
</template>

<script>
import biuHeader from "@components/biu-header";
import biuSidebar from "@components/biu-sidebar";

export default {
  name: "app",
  components: {
    biuHeader,
    biuSidebar
  },
  data() {
    return {};
  }
};
</script>

<style lang="scss">
.clearfix {
  zoom: 1;
}
.clearfix::after {
  content: " ";
  height: 0;
  visibility: hidden;
  display: block;
  clear: both;
}
.clear {
  overflow: hidden;
}

.biu-fl {
  float: left;
}

.biu-fr {
  float: right;
}
.biu-pr {
  position: relative;
}
.biu-btn {
  height: 28px;
  border: none;
  border-radius: 4px;
  padding-left: 13px;
  padding-right: 13px;
  font-size: 14px;
  text-align: center;
  cursor: pointer;
  user-select: none;
  &:focus {
    outline: none;
  }

  &:disabled,
  &.disabled {
    border-color: #e5e5e5;
    color: #c9c9c9;
  }
}
.biu-btn-primary {
  color: #fff;
  background-color: #23a2f5;
  &:active {
    background-color: #007ccd;
  }
}
.biu-btn-default {
  border: 1px solid #91a4ad;
  background-color: #fff;
  color: #5e5e5e;
  &:active {
    background-color: #dbe6ea;
  }
}
.nodata {
  background: url("./img/nodata.png") center center no-repeat;
  background-size: 120px 120px;
  min-height: 330px;
}
</style>
<style lang="scss" scoped>
.content {
  padding: 20px 20px 0px 90px;
}
.pages {
  min-height: 800px;
  border-radius: 4px;
}
</style>

```

</details>
