### ISSUE TITLE
1.12.0 release

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#4231]
It's that time again, friends 😃 

Part of my motivation is due to @evilebottnawi's recommendation that we get https://github.com/prettier/prettier/issues/4218 out. However I know there are other fixes as well; so I'm not sure if this should be 1.11.2 or 1.12.0.

Either way, I will try to find some time to put stuff together this weekend. If not this weekend, sometime soon.

**Comment by ruiaraujo** [comment]
1.12.0 because #4012. 😉

**Comment by kpdonn** [comment]
A release would be very appreciated so we can get 

- #4156 _feat(typescript): support TSMinusToken and TSPlusToken_

Typescript 2.8 has been released but prettier can't handle that syntax yet.

**Comment by vjeux** [comment]
#4120 is going to change a bunch of code so we cannot just sneak it inside of a patch release. 1.12 it is :)

**Comment by suchipi** [comment]
I'm still intending to do this soon™ 😅

**Comment by vjeux** [comment]
We’d like to start using ?. at Facebook. Any chance we could get a release this week? :)

https://github.com/prettier/prettier/pull/4296#merged-event

**Comment by suchipi** [comment]
I'll to get the changelog put together tomorrow night

**Comment by suchipi** [comment]
The release is done: https://prettier.io/blog/2018/04/11/1.12.0.html

**Comment by duailibe** [comment]
Thank you for doing this @suchipi ❤️

**Comment by suchipi** [comment]
You're welcome 😄
