### ISSUE TITLE
[styled-components] Ugly line breaking 

### ISSUE THREAD

**Issue by SilencerWeb** [prettier/prettier#4233]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlAagcUwF5MMBPAGzgBMA6NANwHMADAHSk02oEs0AHCgEMySTDygUJcALQAjChDABrANwcuDOACcYPMEIozDPJlDEwI-dVA2YAJMAAU-AJTEAfJn6190TABkAZhgaGjsnFxRAO481DAAFmKOPn5QtFAQ1HC0DDxw0QBCEAAetEJQPAC2uIa0sfEJmAD03r6Q6ZnZuflFpeWVNXUJcKYJMAC+cFU2UVEjYzBiAIzTs3OYAGbQMDJoPABecMnAPgtM45gAPldtaRlZOXkFxWUV1bUUtOfjE-wl6y4LAmNjsmx4FAoYjAAFdtNoEDAAMIQRTaGwsVQgAA0ICsenQyFAQnhEGiAAUSQg0MgQIZoiIabihBhkJtDGg4Li5NohCo4DBsPw+RImMgYNoYVyQNQlGyOdKJJzdOTeUwqkJ5RRObiAFZoEqFXn8wVCKpwAAy0i1OrxMJg-HtACYbdLhdplbTNopojiQPxtBIYAB1OKJZAADgADLiAxBOcHefxaQG4MqtH6EQBHGE8BGqoTqzVIdna6Wcqo8cWS8uiqgARRhEHg1aluJgQjkocayCd7d5ENFKKqGtphgofphnIAKp2aSWFRMJkA)

**Options:**
```sh
{
  "printWidth": 100,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": true,
  "arrowParens": "always",
  "parser": "flow"
}
```

**Input:**
```jsx
const SVG = styled.svg`
  display: inline-block;
  vertical-align: top;

  ${(p) => p.icon && css`
      width: ${p.icon.node.viewBox.animVal.width / p.icon.node.viewBox.animVal.height}em;
      height: 1em;
      font-size: ${p.height || p.icon.node.viewBox.animVal.height}px;
    `};

  fill: currentColor;
`;
```

**Output:**
```jsx
const SVG = styled.svg`
  display: inline-block;
  vertical-align: top;

  ${(p) =>
    p.icon &&
    css`
      width: ${p.icon.node.viewBox.animVal.width / p.icon.node.viewBox.animVal.height}em;
      height: 1em;
      font-size: ${p.height || p.icon.node.viewBox.animVal.height}px;
    `};

  fill: currentColor;
`;
```

**Expected behavior:**
```jsx
const SVG = styled.svg`
  display: inline-block;
  vertical-align: top;

  ${(p) => p.icon && css`
      width: ${p.icon.node.viewBox.animVal.width / p.icon.node.viewBox.animVal.height}em;
      height: 1em;
      font-size: ${p.height || p.icon.node.viewBox.animVal.height}px;
    `};

  fill: currentColor;
`;
```

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/issues/1872

**Comment by j-f1** [comment]
Duplicate of #1872
