### ISSUE TITLE
does not format files with .js.flow extension

### ISSUE THREAD

**Issue by budarin** [prettier/prettier#4234]
I have generated flow declarations files with ```.js.flow ``` extension but prettier doesn't format them

Is there a way to configure the prettier recognize ```.js.flow ``` as correct flow type files?

**Comment by ikatyang** [comment]
Hi, currently our default parser is still `babylon` (for parsing javascript or flow) so it should work without additional config.

Can you share some steps to reproduce?

**Comment by budarin** [comment]
I'm sorry, but without changing extension to .js.flow - it does not reformat my code
I use to WebStorm with integrated prettier support on save

My .prettierrc
```
{
    "tabWidth": 4,
    "singleQuote": true,
    "trailingComma": "all",
    "printWidth": 110
}
```

Steps to reproduce:
- create file with name index.css.flow
- put in it the code
```js
// @flow
/* This file is automatically generated by css-modules-flow-types */
declare module.exports: {|
  +'animationTime': string;
  +'appSideMenu': string;
  +'layout': string;
  +'layoutContent': string;
  +'layoutHeader': string;
  +'menu': string;
  +'menuAnimation': string;
  +'menuBody': string;
  +'menuHeader': string;
  +'menuHeaderTitle': string;
  +'menuIcon': string;
  +'title': string;
|};
```
- try to safe (if editor supports autorun prettier on save) or run prettier manually

-> code still be untouched

- change extention to .js.flow
- try to save or run prettier - code will be formatted

**Comment by ikatyang** [comment]
I'm confused, is it the issue about `.js.flow` or `.css.flow`? And it seems [`.js.flow` is the only extname for flow declarations](https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-module), there's no docs for `.flow` extname so that WebStorm didn't recognize it.

**Comment by budarin** [comment]
Thanks for pointing!

**Comment by j-f1** [comment]
Shouldn’t `.js.flow` get added to this list?

https://github.com/prettier/prettier/blob/30bcd110e4781c46d5d3ffa94df4763853387f6f/src/language-js/index.js#L77-L98

**Comment by ikatyang** [comment]
We currently just check for `path.extname()` which does not support double extname, we probably have to change it to `.endsWith()` check or something.

https://github.com/prettier/prettier/blob/f2f239011454b2042f29333378e39d6a0a75de70/src/main/options.js#L102-L118

**Comment by mrm007** [comment]
Maybe it was working a while back, but as of today formatting `.flow` files still causes an error:

```
$ prettier --write <somewhere>/Button.types.js.flow
[error] No parser could be inferred for file: <somewhere>/Button.types.js.flow
```

It works only if I specify the parser (either for the CLI or globally via `.prettierrc`).
