### ISSUE TITLE
let's not process .MD files between doctoc tags

### ISSUE THREAD

**Issue by revelt** [prettier/prettier#4235]
We should not touch the code between the [doctoc](https://github.com/thlorenz/doctoc) tags:

```
<!-- START doctoc -->
<!-- END doctoc -->
```

and also:

```
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- END doctoc generated TOC please keep comment here to allow auto update -->
```

Currently my TOC (Table of Contents) tables are being mangled because of blank lines being added and this messes up `doctoc` algorithm when it tries to update the code.

`doctoc` is a [popular](https://npmcharts.com/compare/doctoc) TOC generator, many people use it.

**Comment by evilebottnawi** [comment]
@revelt please use issue template

**Comment by revelt** [comment]
@evilebottnawi I would but it does not apply, it's a request to ignore code between given lines. There's no "expected behaviour" or "input" or "output"...

**Comment by ikatyang** [comment]
Hey @revelt, we just added [range ignore](https://prettier.io/docs/en/ignore.html#range-ignore) for markdown files in #4202, and I think it should perfectly address this issue.

---

**Prettier pr-4202**
[Playground link](https://deploy-preview-4202--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBaABARgEwGYA6U66GALAKwBshhAPAISoYAOATnDDAJZyupcBzKBHaoAzjACGrGCVQA+OowwBlACoBBAEpr0AEwhgYhuYqiEAmgHkAqluLENNtVdQBxAKIA5D1o1qPABEHdABhKy8AyJooBiZ0b2CDIxMmMziWdk4ePkFhUQQ9UxiMHAIiEnQKaigQABoQCGZuaDFkUGlWCAB3AAVpBDaUSQA3CC49epBJCWQAM0kAGzE4BoAjVkkwAGsOFWYtrigBZBhWAFdVkGT5pZWGo5WZXs2BAFtJW+WrgCsxAA8AEKbHZ7SRvOAAGSOcC+90a5xgzER2DhVwOrCeyBAH1Y2wM3VqDTYRxgAHUJjAABbIAAcAAZiV0VmTNsxsWw4E8RrCGuwAI7nLjsF6Sd6fJALb4NFZvLinC5XMRHASLOAARXOEHgaIaUjWFL01OQ2D1my4ixVoQgbw+2OEUF5IHOKzUkjWQylKwAvt6gA)
```sh
--parser markdown
```

**Input:**
```markdown
- 123
  - 456

<!-- prettier-ignore-start -->
<!-- START doctoc -->

YOUR    AUTO-GENERATED    CONTENT

<!-- END doctoc -->
<!-- prettier-ignore-end -->

- 123
  - 456

```

**Output:**
```markdown
* 123
  * 456

<!-- prettier-ignore-start -->
<!-- START doctoc -->

YOUR    AUTO-GENERATED    CONTENT

<!-- END doctoc -->
<!-- prettier-ignore-end -->

* 123
  * 456

```

**Comment by revelt** [comment]
I can definitely use it! Thanks, closing.

**Comment by revelt** [comment]
For posterity, here's a doctoc wiki recipe to achieve this:

https://github.com/thlorenz/doctoc/wiki/Using-doctoc-in-projects-cleaned-by-prettier

**Comment by suchipi** [comment]
Please be aware that range ignore has not been released on npm yet. If you need it now, you can use prettier directly from GitHub with `yarn install prettier/prettier`.

**Comment by revelt** [comment]
I was in the middle of hacking doctoc, why does it add bloody spaces ... hahahaa

Thank you for letting me know.

I hope we release prettier pretty soon...
