### ISSUE TITLE
Flow – Unable to declare a class that implements an interface

### ISSUE THREAD

**Issue by saadq** [prettier/prettier#4240]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAgFsJUBXTQgHRDgA9siAHSmg4KqAg9LPQgJaw4uAGbYwhAKIA3BDClEBMeLnadu3aAAoYATyZwkBAM4xcQgOYAaApgFmEI4wDEyUMDAHQAlMZkQAqgA3BqaEKKiugZGpuZWtvaOUM4Ebh5evv6BIWEAvpxhvDj4BPRMELgwBHwmJgQAKiJKUNiYBALMlETy9bLyisqq6lzhUNGGxmYWUDZ2DvApuK7unt5QfgQBQaGjWpETsdMJ88mp6WtZWzm73AVQ9yDWIBBMmVAmyKB4uBAA7gAFfgfZAgbDbVBPMFmZDiTAmODPABGuAkAGs4DAAMpMCRWZDmMiItAQMCwtoI55CBFVAGoyxEbDk+HEgBWJjoACFUWAMdjGHAADJCODMykvMgwJiSgBMYuJuNwNNBokw-yhTBmMAA6kEYAALZAADgADM9NRAEdrUUxQZq4DS5FD8ABHMgCfB07AMplIOHihFKAm4InPExWSgARTIEHg8ueMGwSN1qANyBlCdRAnsswAwhAiIzQVBoKLnmQEQ0k58-RS4Hk8kA)
```sh
--parser flow
```

**Flow v0.69.0**
[Try link](https://flow.org/try/#0CYUwxgNghgTiAEBbA9sArhBByEAPKiADplvAN4BQ88oksCAlgHYAuIMAZlGAgKIBuIVr0QMWbGOSrwAkMiYAKFgE9CIAFzwAzixjMA5gBp4EBjqHtNAMTRMwLBvICUm-sgbAA3NOrIOHJVUNbV0DY1NzJkt4GzsHZ1d3L2kAX2lpWmg4eDxCZBgWeDotLXgAFXZRJigIeAYiTEQhFlKBZpExCSlqOUUVNU0dPSYjEzM2KJhrW3tHJhd4Nw9val9-QIGQ4dGIiejY2YTFpJX4NLSgA)

**Input:**
```jsx
declare module "example" {
  declare interface EventEmitter {
    on(type: string, listener: Function): void;
    off(type: string, listener: Function): void;
  }

  declare export class Terminal implements EventEmitter {
    on(type: string, listener: Function): void;
    off(type: string, listener: Function): void;
  }
}

```

**Output:**
```jsx
SyntaxError: Unexpected identifier (7:33)
   5 |   }
   6 | 
>  7 |   declare export class Terminal implements EventEmitter {
     |                                 ^^^^^^^^^^
   8 |     on(type: string, listener: Function): void;
   9 |     off(type: string, listener: Function): void;
  10 |   }
```

**Expected behavior:**
This should be supported. It works in the `flow.org/try` but not in the `prettier.io/playground`.

**Comment by duailibe** [comment]
We are currently using Flow 0.64, we need to upgrade it.
