### ISSUE TITLE
Update .prettierrc documentation

### ISSUE THREAD

**Issue by nbosscher** [prettier/prettier#4247]
Update https://prettier.io/docs/en/configuration.html or http://json.schemastore.org/prettierrc to include documentation on the `insertPragma` option (created in issue https://github.com/prettier/prettier/issues/2864 and PR https://github.com/prettier/prettier/pull/2865)

**Comment by ikatyang** [comment]
Are you looking for https://prettier.io/docs/en/options.html#insert-pragma?

**Comment by j-f1** [comment]
I couldn’t find that on the JSON Schema page, though.

**Comment by ikatyang** [comment]
FYI, I found this one http://json.schemastore.org/prettierrc-1.8.2 (SchemaStore/schemastore#400), which includes `insertPragma`.

**Comment by nbosscher** [comment]
Thanks @ikatyang that was what I was looking for. I think it would be good to update the json-schema referenced by https://prettier.io/docs/en/configuration.html
