### ISSUE TITLE
Add Lua plugin to org

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#4252]
I've started work on a [lua plugin](https://github.com/suchipi/prettier-plugin-lua).

Could we move it into the org like `plugin-python`, etc?

Also maybe the core contributors should be members of the org?

**Comment by duailibe** [comment]
cc @vjeux

**Comment by vjeux** [comment]
@suchipi I added you on the prettier org, you should be able to move your repo there. This is pretty cool :)

**Comment by duailibe** [comment]
@vjeux wdyt about adding the core contributors to the org?

**Comment by vjeux** [comment]
I'm a bit hesitant to do that. I'd like people that are working on those projects to be the owners of their destiny. If you want to contribute on prettier-lua, prettier-php... then it's up to the people managing those projects to let you in. I'm not sure that giving automatic admin rights on everyone that got them on prettier core is the best strategic move.

**Comment by suchipi** [comment]
I think the question was about adding @azz, @duailibe, @lydell, @ikatyang, @evilebottnawi, et al to the org, not the plugin's core contributors.

**Comment by suchipi** [comment]
Also thanks @vjeux :)

**Comment by vjeux** [comment]
I'm not very familiar with github permission model. What power does being added to the org gives you if not being able to have commit access on all the repos?

**Comment by vjeux** [comment]
Ohhh I see, by org you meant the lua repo. You are building it, feel free to add whomever you feel is going to make you succeed!

**Comment by suchipi** [comment]
No, I meant the prettier org- but I hadn't considered what you're saying re: permission.

It looks like we don't have any teams in the org, so every member has collaborate access on all repos. I think if we added teams we could change stuff, but it'd be a bit to manage.

**Comment by duailibe** [comment]
I wasn't considering automatically being able to contribute to all plugins, more like being able to act on organizational tasks in the Prettier org. I know I've wanted to do something in the past but was limited, but I can't remember now :-)

**Comment by vjeux** [comment]
Ping me if you ever find yourself stuck wanting to do things you can't, I'm happy to get you unblocked :)

**Comment by suchipi** [comment]
I'll close this since I'm unblocked (I haven't moved the repo yet but I can do it later). Thanks again @vjeux
