### ISSUE TITLE
Feature request: prettier.getFileInfo(path) API and CLI option

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#4253]
We were [discussing Prettier plugin support in Atom](https://github.com/prettier/prettier-atom/issues/395) with @robwise and [faced](https://github.com/prettier/prettier-atom/issues/395#issuecomment-378357499) the default parser problem.

Until Prettier stops parsing unsupported files as suggested in https://github.com/prettier/prettier/issues/2884, its editor extensions need to be fed with a whitelist of supported scopes. Without this list, Prettier would throw an exception when a user presses `cmd+s` for an unsupported file type or _silently_ fail on real parse errors, which is also undesired. Because #2884 cannot be resolved until Prettier 2.0 and this might take a while, is there any room for a new API call like `prettier.isFileSupported(file)` and a corresponding CLI option? This feature could be used by the editor extensions before applying format on safe, and as a consequence, save a user from maintaining a whitelist of scopes.

How do you see the exterior of this feature look like? I can help with a PR if it has a potential to land to Prettier < 2.0.

**Comment by ikatyang** [comment]
What's the difference between `prettier.getSupportInfo()` and the proposed API?

**Comment by kachkaev** [comment]
@ikatyang `prettier.getSupportInfo()` returns a JSON with a list of supported extensions and it's the user's job to then match this list with the given file path. The new potential API would let you skip this second step and get the answer straight away. Perhaps, it could return the name of the parser and some other metadata for a provided file name.

Given that formally any file is supported now, the result could also contain some flag indicating that a fallback JS parser is being used. In this case, an editor extension would not format on save. Additionally, the result could tell if the file is in `.prettierignore`.

Having said that, I'm open to alternative solutions that would help resolve https://github.com/prettier/prettier-atom/issues/395#issuecomment-378486356 😉

**Comment by suchipi** [comment]
What about `getParserForFilePath(path: string): string` and `isFilePathIgnored(path: string): boolean`?

**Comment by suchipi** [comment]
Also, `getParserForFilePath` could NOT return the JS parser as a fallback, even without https://github.com/prettier/prettier/issues/2884. Since it's a new API, this behavior would be a non-breaking change.

I guess that means its return value would be `?string`, not `string`.

**Comment by kachkaev** [comment]
@suchipi the problem with two separate API calls is that they will require Prettier process spawning two times before editor plugin makes an attempt to prettify a given file. So how about `getInfo(path: string): FileInfo` where `FileInfo` is:

```ts
interface FileInfo {
  path: string;
  parser?: string;
  ignored: boolean;
}
```

or until 2.0:


```ts
interface FileInfo {
  path: string;
  parser: string;
  parserIsFallback: boolean;
  ignored: boolean;
}
```

In this case a Prettier editor extension could call ```prettier --file-info $FILENAME``` and then  execute _Format on save_ if the parser is present in the output and `ignored` is not true. The good thing about `FileInfo` is that we can stuff it with more data in future releases and it won't be necessary to create extra API methods and CLI options. WDYT?

**Comment by robwise** [comment]
This `FileInfo` interface seems like a good idea to me. I like that you've also put whether the file is ignored (currently prettier-atom has to do this via its own implementation). 

Maybe this is stating the obvious, but we'd also need to make sure that parsers coming from plugins are properly picked up when returning the file info results.

**Comment by kachkaev** [comment]
> Is the path property on a FileInfo just a pass-through from the input path?

Yep, that's just an absolute path of a file. It may be useful when someone calls `prettier --file-info **/*.` and thus gets the info for multiple files. I'd return an array in any case, even if we're querying info for just one file.

**Comment by kachkaev** [comment]
Will you be happy if I submit a PR with the following feature API?

```
getFileInfo(filePatterns: string[]): FileInfo[]

interface FileInfo {
  path: string;
  parser: string;
  parserIsFallback: boolean;
  ignored: boolean;
}
```

```
prettier --file-info filePattern1 [...filePatternN]
```

?

**Comment by suchipi** [comment]
Yup, looks good to me :+1:

**Comment by kachkaev** [comment]
Hmm... Now I'm wondering: at what point should `.prettierignore` come into play if I'm running `prettier --file-info **/*.*`. Should I get the list of _all_ files including those in `.git` and `node_modules` or should that list only contain files that will be prettified? In the latter case, what's the point of `ignored` flag in `FileInfo` if we'll be getting `[]` when calling `prettier --file-info path/to/ignored/file`?

**Comment by suchipi** [comment]
I think that if the pattern matches multiple files, it should omit ignored entries. If it matches only one file, include it even if it's ignored (and the ignored boolean will be present).

That way, `**/*` won't include a ton of ignored entries, but you can use eg `./package.json` to find out if the current file is ignored.

**Comment by suchipi** [comment]
Sorry, I didn't mean that we would sometimes not return an array, I just meant that the array would sometimes be of length 1, and sometimes have more entries.

Aside from removing the ignored property, it looks like that's still what you're doing in your code block...?

**Comment by suchipi** [comment]
Oh, I see, you're *always* filtering out ignored files.

🤷‍♀️ 

Feels kinda 6-in-the-one, half-dozen-in-the-other to me.

**Comment by kachkaev** [comment]
Yep, I'm always excluding non-existing and ignored files from the result for API consistency. A consumer of the method will always see only the list of files that Prettier will attempt to format if it's ran with the same args but without `--file-info`. That looks like the cleanest possible API design for this case, but I'm open to other interface suggestions.

Once we've agreed, I'm happy to proceed with a PR – really want to help @robwise with [his Atom package simplification](https://github.com/prettier/prettier-atom/pull/404)!

**Comment by suchipi** [comment]
Sounds good to me

**Comment by robwise** [comment]
> @robwise will this API solve the concerns you raised in prettier/prettier-atom#395 (comment)?

Yes, but just in case this wasn't clear, most plugins do not use prettier via the CLI, we use it programmatically so it needs to be a part of the API, not the CLI (or I guess you could do both).

Also, for the pre-2.0 version, is the idea that prettier-atom would check for `fallbackParser` and not try to format if this is true?

>  I'm now tending to think that getting rid of ignore property and always referring to .gitignore is a cleaner solution.

Referring to `.gitgnore`? What do you mean here? I think just returning `null` from `getFileInfo` to mean the file is `prettierignored` isn't totally intuitive. Why do we handle it this way for `prettierignore` but not for an unknown parser?

**Comment by suchipi** [comment]
@kachkaev :+1:

**Comment by robwise** [comment]
It's a bit unintuitive that a file being prettierignored means the file doesn't show up in the array, but a file not having an appropriate parser does show up.

It seems to me that it would be more consistent if we represented both cases consistently, such as using flags for both as originally suggested.

> I know this API may look a bit strange for a single file, but this is to open more opportunities when FileInfo needs to be obtained for multiple files/globs.

This is breaking the [YAGNI principle](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) IMO—we're making the API for the thing we actually need (determining if we're able to format a given, single file) very strange in order to support something we're not even sure will ever be useful. 

With this proposed array API, in order to determine what I want, I will have to check for 3 things and (somewhat unintuitvely), do so only for the first item of the array. This is going to seem very strange to those reading the code ("What about the other elements in the array?" or "Why is it called file info but is actually an array?"):

```js
const fileInfo = getFileInfo(file);
if (fileInfo[0] && !fileInfo[0].parserIsFallback && fileInfo[0].parser) {
  format(file)
}
```

I suggest we solve the problem at hand; determining whether we should format a file or not. If we want to return an object instead of a simple boolean so we can add additional info later, that's fine, but let's still have a simple boolean flag like `isFormattable` or something so I can check one property. And I think we should only return an array if I pass a pattern (or leave that for a different function later on if and when we ever need that functionality).

That way I can just do:

```js
if (getFileInfo(file).formattable) {
  format(file)
}
```

Oh that reminds me of something—`resolveConfig` is asynchronous so it also has a `resolveConfig.sync`. We should think about what we want to do in this case.

**Comment by kachkaev** [comment]
@robwise I take your argument about simplicity – indeed, let's start with just `getFileInfo` that would work for one file only and return an object, not an array.

I'll work on a PR this afternoon and will let know about the results.

**Comment by duailibe** [comment]
I've read this thread an the PR superficially, so excuse me if I say something wrong, but I tried to give the most attention I could.

@kachkaev and @robwise, with #2884, we'd only need an additional API for `isPathIgnored`, right? If the file is not ignored, always call Prettier on it. Am I missing something?

Now maybe the editor integration wants to be smart: when an user opens a file, check if a parser can be inferred and cache that information to prevent ever calling Prettier. Now a `getParser(filepath)` would make sense.

I think `getFileInfo()` is too broad and can be easily abused. For example, I don't think `exists` should be part of it.

Let me know what you think!

**Comment by kachkaev** [comment]
> with #2884, we'd only need an additional API for isPathIgnored, right? 

Yep, I guess so. The main reason for #4341 is an assumption that a fallback `babel` parser will be used at least till Prettier 2.0 for backwards compatibility. `getParser()` and `isPathIgnored()` sound cleaner to me when it comes to using Prettier methods, but I'm not sure that having two extra CLI options is a good thing. Do we want to bloat CLI API?

If `getFileInfo()` is not the ideal solution and it'll be quicker get default parser removed, I'm totally happy with an alternative approach. I'm just trying to get Prettier working correctly with plugins and not rely on hand-crafted lists of file types that current implementations of editors have to have 🙂   WDYT?

**Comment by kachkaev** [comment]
Let's see if removing default parser can be fast-tracked.

> To clarify, getParser() wouldn't be necessary unless you wanted to "cache" that information. It's kind of an optimization. You can just always call Prettier on the file.

Agree. But would not calling `getParser()` or `getFileInfo()` be considered a good practice? Imagine a have a huge csv file that I'm editing in VSCode or Atom and then hit save. Do we want all these megabytes go via Prettier instead of just padding a filename and getting `false` from it? Remember, we can't black-list any extensions because added prettier plugins can support them.

> I'm on board 👍

One more thing I'm trying to get through is https://github.com/prettier/prettier/pull/4192. It'd be great if you could give a hand there.

**Comment by duailibe** [comment]
What about a `formatFile` ?

Kind of like #3462

**Comment by duailibe** [comment]
@kachkaev Fair enough. :+1: I'm convinced this is a good api

**Comment by kachkaev** [comment]
Not sure it will help. Here are the usual workflows in an editor as I see them:

1. make changes
2. run prettier manually

1. enable format on save
2. edit
3. press save and see prettier _first_ formatting my text and _then_ saving it to a fs

I’m not sure how avoid getFileInfo() or getParser() + isIgnored() here. We can’t hit a file system in the first place and we don’t want to send prettier large csvs or simply unsupported formats for a dummy run in the second case.

**Comment by kachkaev** [comment]
I'm really amazed to see this one and #4000 fixed! ❤️  Prettier owners: would it be possible for you to release `1.13.0-beta` that would include #4192 and #4341 so that @robwise could test editor integration in https://github.com/prettier/prettier-atom/pull/404?

I could also cut a new unofficial version as I [once did earlier](https://github.com/prettier/prettier/issues/4000#issuecomment-376119478), but it'd be probably better if it was ‘official’. There is a past record of beta/RCs for prettier package, although these were not very frequent:

<img width="645" alt="screen shot 2018-05-09 at 20 08 17" src="https://user-images.githubusercontent.com/608862/39834639-8ae1e91a-53c5-11e8-87be-30009786cbd4.png">

https://www.npmjs.com/package/prettier (tab `versions`)
