### ISSUE TITLE
Typescript JSX generic component elements

### ISSUE THREAD

**Issue by jonaskello** [prettier/prettier#4259]
Support for generics in JSX elements has been [added](https://github.com/Microsoft/TypeScript/pull/22415) to typescript 2.9 (currently in the prerelease, typescript@next):

```
<MyComponent<number> data={12} />
```

However when I tried this prettier complained so I cannot use it which is a pity. Not sure if this is the correct place to put the issue about this or if it is an upstream babel issue. However for me as end-user I just want prettier to work with this new syntax :-).

**Comment by ikatyang** [comment]
Opened eslint/typescript-eslint-parser#461.
