### ISSUE TITLE
New option - Curly braces on statements

### ISSUE THREAD

**Issue by igor-ribeiro** [prettier/prettier#4262]
First, thanks for that great tool!

It would be good to have an option to add curly braces on statements.

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwE4CucAlADpSaaRQDOEANnAHT0QDmuhJA3CADQgIABxipoNZKACGePBADuABRkIJKKQDcIqACb8QUmjGTop9GnAEAjPFLABrODADKQu6ihtk+IgJ0QwEzMLAQ8LPBhFWzYAWykg80sQACsaAA8AIVsHJ2cpGLgAGQ84BJDBAhghSoAmMqS3PHDkECspKwBPVih9ITwPGAB1XRgAC2QADgAGAT6IC0HbIRa+uHCNUoFbTzgAUSg9JBmQbbY4ZxgZYyOtuABHAlQ8OCipWPikU0SBCxjUby4Pw8bEYAEUCBB4PUBJcrMMdGNkDUYbZUPRgQBhCAxOItKDQTYgAgWAAq7TUXwsAF8qUA)
```sh
--range-end 
--range-start 
```

**Input:**
```jsx
if (true)
  console.log(true);
```

**Output:**
```jsx
if (true) console.log(true);
```

**Expected behavior:**
```jsx
if (true) {
  console.log(true);
}

**Comment by suchipi** [comment]
Hello,

We are not going to add this option because we don't want to change the AST in this case. See also https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about

You can use ESLint to do this if you want to.
