### ISSUE TITLE
Some promise chains are vertically over-long

### ISSUE THREAD

**Issue by Drarok** [prettier/prettier#4270]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEcAHgIYC2ADgDZwCMAFAJT7AA6U++ATnDOlxwAKXCGRwBnOADoe4iFQBucJu06cpMABYJ6TfAF4AfPihwA7vmGiJy+rPlKANNzgArONmZGWqtZwD0-vgAIhD4ZhBcANb4OBzaPL6cAL6MjADc7Mns7BhYuATE5NRwAEx6bBwufAKWImKSMnByisqMSfga2lC6XsamFlYNtvatzjzungbGlX4BQaHhkTFx+AlwHakZWSCOIBAUBVDiyKAUXHEwAOo4ACZayAAcAAx7MCQARjf3msile+I4gBzGgARXQEHgyFQJCokjeXBIOCowIAwqIyCRkCAoNA4LsQB9EWAorwAMoUEhgYHIGBcdBwPaucREABCxNJMDJ5DgABk4vikDC4YyQJSuJIuNiPp8AJ5UaAEyRiWn00XoSQAFU+JyFsPhIDikpgwhIQMx0P1op4AEd0DgeKbzVi9SK9ucIJIroiKNjzs04FwlASSFwRGZBKGELqQCQFBA7gTEVAgXAye8uDBkK8QMnUwBRKC3bN7W4QMCWt2x8RZ10GiDoGAURulSuSZLJIA)
```sh
--range-end 0
--range-start 0
```

**Input:**
```jsx
function example1() {
  return Promise.resolve()
    .then(() => new Promise((resolve, reject) => {
      // Do work in here
    }));
}

function example2() {
  return Promise.resolve()
    .then(() => new Promise((resolve, reject) => {
      // Do work in here
    }));
}
```

**Output:**
```jsx
function example1() {
  return Promise.resolve().then(
    () =>
      new Promise((resolve, reject) => {
        // Do work in here
      })
  );
}

function example2() {
  return Promise.resolve()
    .then(() => new Promise((resolve, reject) => {
      // Do work in here
    }));
}
```

**Expected behavior:**

(As an aside, there appears to be a bug in the playground – the content of the two functions is exactly the same, but they're formatted differently)

I'd expect the format of example2 in both cases, given that it fits easily inside the 80 character limit.

**Comment by ikatyang** [comment]
The issue appears to be `--range-end` is cosidered 0 even if `$('#rangeEnd').val() === ""`.

**Comment by Drarok** [comment]
I don't think this bug should be tagged `area:playground`, as that was just something I noticed when writing about my _main_ point re: `promise.then(…)`, that example1 is over-long and ugly.
