### ISSUE TITLE
Bad formatting on markdown nested ordered lists

### ISSUE THREAD

**Issue by joakin** [prettier/prettier#4272]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgEwGYB0r4DEhABALKoCWsCqUYc++AjAHQmXwC2J0jUAJnac4PGAHcI+EiQBUJdAFcARgBtK6GNJlyFK9ZqZRipACJwADgkwIwlOOiMADKBZ4RFMTKniYnRthIABUowAGsSVBIbKygbegBPbUCAFVQwuBIYAAtMrmoIACdeYosfMGySADc4QvRKaHQSbEo6rUF2AGFc8Kzckgq6AHM4VQghgBoSbI0YIoSpwtG4DEyoCHgmopI1ce15TogLBL7MwagRxygQCZAjmAaodGRQVELCiHEgt4RnlFQqhBKJgbmhNMhsKhVOg4LdlIVUOE4DAAMplOwXZAwQqKWEgTAQMAQqEw27UGGFGBBBFDLioYnQvEAK3QAA8AEIIpGo1BcOAAGWocAZpLungsngEIrxZTqtWQIDphTCBPE11uFkK1BgAHVgTlkAAOAAMGo+MJ1CIsCqh4lQCWetwRFzgAFE4shTSBnSMUTA3jBPU64ABHRStODU1C0+lISGM24w-JYnF4+oXVRwACKig2wrjJLx-uUeswBqQAlu2Ko6guhy4dIV6ygwtuihhaWUf3jMIAvr2gA)
```sh
--parser markdown
--prose-wrap always
--range-end 0
--range-start 0
```

**Input:**
```markdown
asdf

## Maintenance

1. item one
2. item two
  * sublist
    * sublist

### Dependencies

`npm outdated`

1. Pick a dependency
  1. Take the minor or patch versions first
2. Check the changelog, history, release notes or blog
  * Copy the changes

```

**Output:**
```markdown
TypeError: options.locStart is not a function
    at findNodeAtOffset (https://prettier.io/lib/index.js:2314:2119)
    at calculateRange (https://prettier.io/lib/index.js:2328:346)
    at formatRange (https://prettier.io/lib/index.js:2328:1148)
    at _formatWithCursor (https://prettier.io/lib/index.js:2313:288)
    at _format (https://prettier.io/lib/index.js:2314:239)
    at Object.format (https://prettier.io/lib/index.js:2333:277)
    at formatCode (https://prettier.io/worker.js:130:21)
    at self.onmessage (https://prettier.io/worker.js:80:19)
```

**Output in my computer (playground seems broken):**
```markdown
asdf

## Maintenance

1.  item one
2.  item two

* sublist
  * sublist

### Dependencies

`npm outdated`

1.  Pick a dependency
1.  Take the minor or patch versions first
1.  Check the changelog, history, release notes or blog

* Copy the changes
```

**Expected behavior:**

Nested lists should be respected? Right now it is changing the whole meaning of the lists 😞

**Comment by joakin** [comment]
Nested unordered lists seem to behave well

**Comment by ikatyang** [comment]
Hi, that's the correct behavior based on [CommonMark spec](http://spec.commonmark.org/0.28/#example-274), see [CommonMark playground](http://spec.commonmark.org/dingus/?text=asdf%0A%0A%23%23%20Maintenance%0A%0A1.%20item%20one%0A2.%20item%20two%0A%20%20*%20sublist%0A%20%20%20%20*%20sublist%0A%0A%23%23%23%20Dependencies%0A%0A%60npm%20outdated%60%0A%0A1.%20Pick%20a%20dependency%0A%20%201.%20Take%20the%20minor%20or%20patch%20versions%20first%0A2.%20Check%20the%20changelog%2C%20history%2C%20release%20notes%20or%20blog%0A%20%20*%20Copy%20the%20changes).

You're probably using a renderer that does not follow the CommonMark spec.

**Comment by joakin** [comment]
Wow, sorry for the noise. Thanks a lot for the links ❤️
