### ISSUE TITLE
Block comment attached to ContinueStatement is not printed

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#4276]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgCQCWWAvFgAwDcWhWAPFgKxUDUzhAlFsADpRb9YCqXDWKkATO14CZWSLAJQArnCwB6AFRYAwhAC2ehDCwa1FXgF8QAGhAQADjALQAzslABDDBggB3AApeCG4oHgBuEAQAJjYgHi4wyKgeADYucLYARhgeYADWcDAAyva5igDmyDAYKrZREGBJqem2iukYMP455XoeTWkZIABWLgAeAEI5+YVFHoYAMopw-S12SjD26+Irg6UY7cggmR6ZAJ4p0LH2GIowAOrRMAAWyAAcZLbXEOl3OfaH1zg7TCy1sOSg5TgAFEoDEkB8QODIUUYF5EvCwXAAI5KAgYOBdDw9PpIZIDWzpPQEKo1QYuCopOAARSUEHgO1sqMyDyiz2Q4k5OQIKQqugMJJAUGgoJASnSABUTiEyekLBYgA.)

**Input:**
```jsx
for ($i = 0; $i < 5; ++$i) {
    if ($i == 2)
        continue /* Comment */;
}
```

**Output:**
```jsx
Error: Comment "Comment" was not printed. Please report this error!
    at https://prettier.io/lib/index.js:2312:75
    at Array.forEach (<anonymous>)
    at ensureAllCommentsPrinted (https://prettier.io/lib/index.js:2312:22)
    at _formatWithCursor (https://prettier.io/lib/index.js:2313:949)
    at _format (https://prettier.io/lib/index.js:2314:239)
    at formatRange (https://prettier.io/lib/index.js:2331:215)
    at _formatWithCursor (https://prettier.io/lib/index.js:2313:288)
    at _format (https://prettier.io/lib/index.js:2314:239)
    at Object.format (https://prettier.io/lib/index.js:2333:277)
    at formatCode (https://prettier.io/worker.js:130:21)
    at self.onmessage (https://prettier.io/worker.js:80:19)
```

**Expected behavior:**

Comment should be printed :+1: 

We have some problem in `plugin-php` :smile:

**Comment by evilebottnawi** [comment]
@j-f1 fixes, my mistake

**Comment by duailibe** [comment]
I have no idea what this issue means, what is wrong and what exactly we should fix here.

**Comment by suchipi** [comment]
The issue is that the comment attached to the ContinueStatement doesn't get printed. Prettier has a built-in condition where it throws an error if a comment in the input does not appear in the output, which is why we can't see the output in the playground. But if we could see it, we would see the comment disappear.

**Comment by duailibe** [comment]
Ohhh thanks @suchipi! I didn't understand that at all, I was thinking it was describing something about prettier-php 😂

**Comment by suchipi** [comment]
No prob, I was a bit confused at first too because the code looks like PHP code, but it happens to be valid JS, too 😅.

**Comment by evilebottnawi** [comment]
@suchipi yes, php code in some places is valid js code, it is very funny :smile:
