### ISSUE TITLE
Some ugly formatting of a template string

### ISSUE THREAD

**Issue by opennota** [prettier/prettier#4282]
**Prettier 1.11.1**  Playground link  https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAIAGAJMAF4AOAhgCYBMAFFRQJ4CUAvgLTEC20MAFp2LlqAFjpM4FVO1zDKtOv3ZJ51etxVrFAZ3b4A3CAA0ICGRgBLaDuShpqCAHcACtIS2UFAG4RLVExAKHRhkADMKABsdOFMAI1QKMABrDABlSjBLKABzZBhUTFiQKggwcKiY02yY1BgXRJzuCgro4oArHQAPACFElPSKbjgAGWy4VqqzTBgyGZpJ4spUWuQQOIo4pkjoQLJUbJgAdX8BZAAOAAZTfYgYo8SyNf24Wu8J03QAR0xLdAaKE0WkgIm1TDFuJZ8oVijpsjlInAAIqYCDwRamGCbE5UM5IGiYxKWSLwgDCEG4zTWUGgHxAmBiABVNp5QTE2GwgA

**Input:**
```
return `${zpad2(day)}-${month}-${zpad4(year)} ${zpad2(h)}:${zpad2(m)}:${zpad2(s)}`;
```

**Output:**
```
return `${zpad2(day)}-${month}-${zpad4(year)} ${zpad2(h)}:${zpad2(m)}:${zpad2(
  s
)}`;
```

**Expected behavior:**

I don't know, but the result looks kinda ugly. Maybe it would be better to leave this line alone?

**Comment by duailibe** [comment]
Thanks for the report! There's already a similar issue tracking problems with template string interpolations: #3368

Let's keep the discussion over there.
