### ISSUE TITLE
Single quotes in Atom

### ISSUE THREAD

**Issue by sunny-mittal** [prettier/prettier#4284]
I couldn't find anything in the existing issues but I'm having trouble getting Atom to use single quotes with prettier (for typescript). `prettier:debug` gives me this:
```
  ...
  "prettierOptions": {
    "semi": false,
    "singleQuote": true,
    "bracketSpacing": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
```
and running `yarn prettier src/index.ts` uses the correct quotes, but fixOnSave is replacing them all with double quotes. Any help would be greatly appreciated. Thanks!

**Comment by ikatyang** [comment]
Hi, this looks like an issue in [`prettier-atom`](https://github.com/prettier/prettier-atom), could you raise the issue over there?
