### ISSUE TITLE
Add support for JSDoc based TypeScript typecasting

### ISSUE THREAD

**Issue by alippai** [prettier/prettier#4287]
This is an unsupported construction for Prettier, as it rewrites the parentheses
```
const a = /** @type {myType} */ (b).map();
```

The pattern: https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript (the last one)

---

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA6nDYCGUGAOuPgM4ykYwCeADnOTRBhDABZwBONDTGAK7kAllADmGfBgBSAZQAiEMH0ZTy5HjBHRiUdBgBGtKQBNTYyYQwADAAJ1GNmvivcIgqKalQT9fNwInEwiAF5w3nAAHvSBGjpQAHR6eqgAVGl6GGkYDvwYwFCCALaGPBgAPhgAgtzc+LQAvllpqHoAbgEYRaU8APLctfUmALwYALL4nIn1XhDFABQAlBgAPBgADIkArBgA-BgA2gC6GEgYAIwbGwDcHV1QcADuQw0YY+k5eWrAAcON2UwCx6ZW4AzkMG4liWiWK+HoCyi7wAfBgoks7lAQAAaEAQejaaDkZCgWJiGBYESmTjIAAcG1xMHwhkp1I4yAATLjRBIADZwACKgnYcGQADN8LzNIz6iJeZYAMLzOHIEBQaCi3GGepgADWcBgcn8YEsyEhgjguIAVuQogAhHX6w34YpwAAyYlFSAlUstIH83E03FVhmZtF50BxIE0xREZu4FtxwjgABVmcTvZLpSAxEGYAAFeriFWZ324wIAR0EIkChdcJZ92diEE0WHq9FVsSYPHampAfwgT3zAQQGf77QgVKjpmU4qzfooMDnZbxghg9DXHOXmkajSAA)

**Input:**
```jsx
// We can "cast" types to other types using a JSDoc type assertion
// by adding an `@type` tag around any parenthesized expression.

/**
 * @type {number | Array}
 */
var numberOrArray = Math.random() < 0.5 ? [] : 100;
var newArray = /** @type {array} */ (numberOrString).map(x => x);

```

**Output:**
```jsx
// We can "cast" types to other types using a JSDoc type assertion
// by adding an `@type` tag around any parenthesized expression.

/**
 * @type {number | Array}
 */
var numberOrArray = Math.random() < 0.5 ? [] : 100;
var newArray = /** @type {array} */ (numberOrString.map(x => x));

```

**Comment by ikatyang** [comment]
Marked as `high-pri` since it actually breaks the AST in a sense, `TSParenthesizedType` has special meaning in TypeScript's checkJs mode if there's a JSDoc-style type assertion in front of it.

![image](https://user-images.githubusercontent.com/8341033/38499055-036f5628-3c39-11e8-8db8-5547192d2e7a.png)

![image](https://user-images.githubusercontent.com/8341033/38499188-58482c38-3c39-11e8-9588-53c414cca6f0.png)

**Comment by ikatyang** [comment]
Oops, it seems there's no `TSParenthesizedExpression` in `typescript-eslint-parser`, opened eslint/typescript-eslint-parser#464.
