### ISSUE TITLE
Export block with prettier-ignore duplicates comments

### ISSUE THREAD

**Issue by christopherthielen** [prettier/prettier#4291]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQDMITYC82AjANwA6UGOARlsdgExVTUD0H2ADpnDBgBLOJgC0QgOZQI-anAAePWTGzBq2PAQA02LtkgBbQwhgbsDTLv1GTsagF8Q2kBB7DoAZ2SgsmCADuAApYCN4o6KgQQgAmziDonjDIuOgANp5wLnSY6GAA1gIAyjx5QlCSyDCYAK5ZIDEQYCnpmS7lmZgwQbmShugtGfUAVp4KAEK5BcXoJgAy5XCDba41MDxrzMv1pZidyCAMdACeadDxfOUwAOqxMAAWyAAcAAwufBCZ17k8B3xwnVQSxc-AAjjUhPweug+gMkKkhi5MoYhFVavVPOVJGk4ABFGoQeDbFwwdB0W4xB7IZgk3JCNJYgDCEGMcJAMigwJANUyABUyeEEZkHA4gA)

**Input:**
```jsx
var foo = 1;
var bar = 2;

// prettier-ignore
export {
  foo, // comment
  bar, // comment
}
```

**Output:**
```jsx
var foo = 1;
var bar = 2;

// prettier-ignore
// comment
// comment
export {
  foo, // comment
  bar, // comment
}

```

**Expected behavior:**
```jsx
var foo = 1;
var bar = 2;

// prettier-ignore
export {
  foo, // comment
  bar, // comment
}
```

---

Each time prettier is run on this block, it adds more copies of the comments

**Comment by evilebottnawi** [comment]
@christopherthielen Thanks for issue :+1:

**Comment by christopherthielen** [comment]
This also affects `lang:typescript`

**Comment by j-f1** [comment]
We use the same code to print JavaScript and TypeScript, so we only use the TypeScript label on issues about TypeScript-specific constructs.
