### ISSUE TITLE
Flow generic comment formatted incorrectly

### ISSUE THREAD

**Issue by helixbass** [prettier/prettier#4295]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBLAJgmbGAT0wF5MAzAVyjEOgHoAqJJAHgBUA+ZxgCgBuAQwA21OCySZOmPgEopMuY0zAAOlEyYATnBjUdWkeLgBuTQF8zIADQgIABwZQ0yUMJ06IAdwAKnghuKMKCEHh2IMIYyJRiaHD2AEY6wmAA1voAyo5p2FAA5sgwOhL2uBBgsfGJIPkJOjB+qQUAtsLVogn2AFZoAB4AQqkZ2cKtcAAy+XCd3Q7UMI6LAExztbk6DcggScJJxKLQkY46+TAA6ngwABbIABwADPanEAkXqY47p3ANgrP2PQAR2o2D0zWEbQ6SDiXVqCVa2GKpXh+QKojgAEVqBB4Ot7DB9ldcLdkCsCalsKI0QBhCCtdo7KDQAEgagJTj7YKwhKWSxAA)

**Input:**
```jsx
const identity = function/*::<T>*/(value/*: T */)/*: T */ {
  return value;
};
```

**Output:**
```jsx
const identity = function(/*::<T>*/ value /*: T */) /*: T */ {
  return value;
};

```

**Expected behavior:**
It seems as though the generic comment `/*::<T>*/` needs to remain between the `function` keyword and the `(` in order for the Flow parser to correctly recognize the comment (pasting Prettier's output into https://flow.org/try gives errors). Not sure if there is a corresponding case for arrow functions or not

**Comment by helixbass** [comment]
Here are two other Flow comment syntaxes that seem not to be formatted correctly (ie in such a way that Flow will still parse them):
```
const x = ([1, 2, 3]/*: Array<number> */);
```
gets formatted as:
```
const x = [1, 2, 3]; /*: Array<number> */
```
and this:
```
([1, 2, 3]/*: Array<number> */);
```
gets formatted as:
```
[1, 2, 3] /*: Array<number> */;
```
Basically both need to preserve the surrounding parens

**Comment by thorn0** [comment]
Not an issue anymore because support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687
