### ISSUE TITLE
Styled-components css injection issue in 1.12.0

### ISSUE THREAD

**Issue by thebuilder** [prettier/prettier#4301]
Updated Prettier, and noticed my global CSS stopped working. Something changed in Prettier, that causes it to remove the `html` tag from my styled-components `css`.

**Note:** If i use `injectGlobal` instead of `css` it works as expected.

**Prettier 1.12.0**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHzAGcT8BffAMxwnXwHISYBPAGzgBMBaSLaAhglGAHSgZseQvhIBDCTFQAvOJRp0GjAHQB6eYpVwxEgdKLVow9bXpM9l2CPHi4ADykEucanICu7ASkJAAG4vj4ACTABqhKqhThUcCOwolQEQAWMOjshEkR6HI4AOaoUEj4AAwA3EnpYVAgADQgEJhK0CTIoMV0AO4ACsUI3ShyAG4QqFwtIHIsyL7sJHCtAEY4cmAA1nAwAMqY2+UlyDA4fmsgXBBgS3Ir1+WreINbJUUPT60AViRuABCW12+wOcnQcAAMuU4N9Vq0IH4YJhkQAmeHXY44V7IEDrOTrDjQOaYHDlGAAdRmMEyyAAHFVWmSIKtKVtMHiyXBXhM4a0cHAAI5+VCC95yT5yTGtVboVAykAkU6cACKfgg8HOl2uMEJ1K4tOQaNaFzkqHYpwAwvQvigoII5n5VgAVQljZarCgUIA
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
import { css } from 'styled-components'
import { sanitize } from './sanitize'
import { fonts } from './fonts'

export default css`
  ${sanitize}
  ${fonts}
  html {
    margin: 0;
  }
`
```

**Output:**
```jsx
import { css } from 'styled-components'
import { sanitize } from './sanitize'
import { fonts } from './fonts'

export default css`
  ${sanitize} ${fonts} {
    margin: 0;
  }
`
```

**Expected behavior:**
It shouldn't remove the `html` element from the css. Earlier versions preserved the `html` tag correctly:

```jsx
export default css`
  ${sanitize} ${fonts}
  html {
    margin: 0;
  }
`
```

**Comment by evilebottnawi** [comment]
Stupid bug, will fix in near time :+1:
