### ISSUE TITLE
[Update doc]: change option "postcss" by "css" and "scss"

### ISSUE THREAD

**Issue by JulioJu** [prettier/prettier#4304]
**Prettier 1.12.0**

Hi,

Maybe it could be cool to update http://json.schemastore.org/prettierrc, http://json.schemastore.org/prettierrc, and http://json.schemastore.org/prettierrc ? "postcss" option should be replaced by "css" and "scss"? 

What do you think about that?

I've not seen issue about this problem.

Thanks in advance!

**Comment by duailibe** [comment]
Sure!

Are you interested in opening a PR to https://github.com/SchemaStore/schemastore ?

**Comment by JulioJu** [comment]
@duailibe @ikatyang 
Thanks ;-) !
Ok… But I havn't time tonight and tomorrow ;-).

**Comment by kbariotis** [comment]
It seems like this has been resolved. It can close.

**Comment by ikatyang** [comment]
Ref: SchemaStore/schemastore#435
