### ISSUE TITLE
Code blocks in markdown list items with two or more empty lines may crash parser

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#4306]
Looks like the following code crashes the parser (at least in the latest Playground):

````markdown
1.  Two or more empty lines with no spaces:

    ```js
    const a = 1;


    const b = 2;
    ```
````
(note no spaces in lines between `const`)

Chrome:
```
TypeError: Cannot read property 'split' of null
    at Object.embed$2 [as embed] (https://prettier.io/lib/index.js:1380:20)
    at Object.printSubtree (https://prettier.io/lib/index.js:1646:1643)
    at genericPrint$6 (https://prettier.io/lib/index.js:1652:21)
    at https://prettier.io/lib/index.js:1648:206
    at Object.printComments (https://prettier.io/lib/index.js:562:873)
    at printGenerically (https://prettier.io/lib/index.js:1648:165)
    at FastPath.call (https://prettier.io/lib/index.js:1540:261)
    at processor (https://prettier.io/lib/index.js:1398:535)
    at https://prettier.io/lib/index.js:1398:905
    at FastPath.map (https://prettier.io/lib/index.js:1549:380)
```

FF:
```
embed$2@https://prettier.io/lib/index.js:1380:5
printSubtree@https://prettier.io/lib/index.js:1646:1627
genericPrint$6@https://prettier.io/lib/index.js:1652:9
printGenerically/res<@https://prettier.io/lib/index.js:1648:206
printComments@https://prettier.io/lib/index.js:562:873
printGenerically@https://prettier.io/lib/index.js:1648:156
call@https://prettier.io/lib/index.js:1540:261
processor@https://prettier.io/lib/index.js:1398:525
printChildren/<@https://prettier.io/lib/index.js:1398:905
map@https://prettier.io/lib/index.js:1549:380
printChildren@https://prettier.io/lib/index.js:1398:821
printRoot@https://prettier.io/lib/index.js:1398:18
genericPrint$3@https://prettier.io/lib/index.js:1381:1739
genericPrint$6@https://prettier.io/lib/index.js:1653:10
printGenerically/res<@https://prettier.io/lib/index.js:1648:206
printComments@https://prettier.io/lib/index.js:562:873
printGenerically@https://prettier.io/lib/index.js:1648:156
printAstToDoc@https://prettier.io/lib/index.js:1648:347
_formatWithCursor@https://prettier.io/lib/index.js:2366:1221
_format@https://prettier.io/lib/index.js:2367:239
format@https://prettier.io/lib/index.js:2386:277
formatCode@https://prettier.io/worker.js:130:12
self.onmessage@https://prettier.io/worker.js:80:19
```

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB5KcAEcC2AHGAT0wBsBLDJAHShoAMGArAZxsimZkwENMBeTAEYA3DTbROmAEb9MAJlFQGdMVAAqAdwiYIAJ0w49WXAWLkMzarSVNWUdpN4CRqh1xkCF9Bqs3a9BkbY+ESkFHDMmBSYVt50cCQ44hxcTkKKrhLusl42KtYAsty6ANYAJhAaUGGcqoIAdJiY6MYhZuGx1U2Yyiw03ZhuPLIu1gNDHvKKA8p1jZh+OvqGuq2mYRaYGmQwABaYzHjcYBGdM7b93UNpo5dNEznT3bPWDU2LAStroeYRWzv7KDaQ7HU6qc50Ppde5ZYbODJjK6wya5CFzJoAQSBezg+nIkh2uBoIAANCAIAQyBJkKBirpKgAFYoIZjIEDcABuEDIZVJ7M4yAAZtwSMw4GSpLpjiU4DAAMpHMAUADmyBgugAruKQBUwEKRWKyRQxboYAypcqcNx9aLtSwAB4AISlYBl8u4ODgABlwjbDeSNTA8IG5H7tUddCa2VbShUqny8LoKDAAOo8vbIAAcAAYyYmIGKU1K8GzExFcRy4HzVgBHDVkVbm7iW61IYW2slinBkNWa7XMFUkOAARQ1EHgYbJMG4UjTZQzSAALFOpWRzMqAMIQHBWtlAjB8jVitQz1ltg1wAC+l6AA)

```sh
# Options (if any):
--parser=markdown
```

**Expected behavior:**

I'm not quite sure what the expected behaviour should be here. As an author of [`prettier-plugin-elm`](https://github.com/gicentre/prettier-plugin-elm), I'd say it'd be great if the code block remained as is despite more than one empty line of code. That's because two empty lines are common in Elm. E.g.:

```diff
module Main exposing (..)
+
import Html exposing (text)
+
+
main =
    text "Hello, World!"
```

In `1.11.0` the output was the following (see [playground](https://deploy-preview-4035--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEB5KcAEcC2AHGAT0wBsBLDJAHShoAMGArAZxsimZkwENMBeTAEYA3DTbROmAEb9MAJlFQGdMVAAqAdwiYIAJ0w49WXAWLkMzarSVNWUdpN4CRqh1xkCF9Bqs3a9BkbY+ESkFHDMmBSYVt50cCQ44hxcTkKKrhLusl42KtYAsty6ANYAJhAaUGGcqoIAdJiY6MYhZuGx1U2Yyiw03ZhuPLIu1gNDHvKKA8p1jZh+OvqGuq2mYRaYGmQwABaYzHjcYBGdM7b93UNpo5dNEznT3bPWDU2LAStroeYRWzv7KDaQ7HU6qc50Ppde5ZYbODJjK6wya5CFzJoAQSBezg+nIkh2uBoIAANCAIAQyBJkKBirpKgAFYoIZjIEDcABuEDIZVJ7M4yAAZtwSMw4GSpLpjiU4DAAMpHMAUADmyBgugAruKQBUwEKRWKyRQxboYAypcqcNx9aLtSwAB4AISlYBl8u4ODgABlwjbDeSNTA8IG5H7tUddCa2VbShUqny8LoKDAAOo8vbIAAcAAYyYmIGKU1K8GzExFcRy4HzVgBHDVkVbm7iW61IYW2slinBkNWa7XMFUkOAARQ1EHgYbJMG4UjTZQzSDkU6lZHMyoAwhAcFa2UCMHyNWK1DPWW2DXAAL4XoA) for #4035):

````markdown
1. Two or more empty lines with no spaces:

   ```js
   const a = 1;
   ```


    const b = 2;
    ```
````

Still broken, but at least no crash.

Would it be feasible to leave two or more empty lines in code blocks (even without spaces) given that a plugin that formats that block may want so? If not, I'd have to get rid of double empty lines in Elm blocks, which some users might not like.

**Comment by duailibe** [comment]
The problem here is not the empty lines inside the block but the fact there are 4 spaces before ` ```js `. See [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAzgHSpKLGAAgENiBeYgRgG491U9mocZHs9jviCizKNelB7FGLEABoQEAA4wAltCzJQpAE7qIAdwAKGhCpSkAbhAUATKSFJFkMdQFc40gEbrSYANZwYAZVlPBSgAc3snFxALCDBkADNSABssSOCU9RhdDxCAW1J4pJTpbAAPACEPb18-Uhy4ABlguALkyIhHGFkOgCYWopBA9XTkEDz1L2jtKGtZdWCYAHVLGAALZAAOAAZpWYgUhY9ZEdm4dJNm6XU4AEdHBSus0lz8pATW6RSchXDnD+CQxJwACKjgg8D6kRgpFcSwsq2QABZpA5SApEv8AMIQHJ5EZQaAXECOFIAFWhRjeKQAvlSgA) (click on `show AST`)

**Comment by kachkaev** [comment]
That's true. When a code block does not have any indentation on the left, all works.

**Comment by ikatyang** [comment]
FYI, the playground crashing is fixed in #4307.

---

**Prettier pr-4307**
[Playground link](https://deploy-preview-4307--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBGAdAAkwFQO4SYQBOmAtiXJnGQA4wCemANgJZRwDOmerMAFpiiFOtAIZguSADpRZ2bAANlAK07yFkKJxiYxmALyZUAblnmoCzFp2YARocwAmM5YXLFIADQgI9VtCcyKBixMQQeAAKoQhBKGIAbhCsACbeIGI6yABmYsyccD52xBIA1nAwAMriYOwA5sgwxACuhSApEGA5eQU+7AXEMJEldWRi3fltagAeAEIlYOVVYmRwADLscBO9vs0wtHtO223ixAPIIGPEpR14UOm0xOwwAOqpAsgAHAAMPo8QBReJVoF0eXDgxASWx8xDgAEdmqxYcMxKNxkhcpMfAUyKxGi02px6sw4ABFZoQeDHHwwMR2N4pD5IJw0kqsNhQOoAYQgZDGF2EHHSzQKODpcUxBQAvlKgA)
```sh
--parser markdown
```

**Input:**
````markdown
1.  Two or more empty lines with no spaces:

    ```js
    const a = 1;


    const b = 2;
    ```
````

**Output:**
````markdown
1.  Two or more empty lines with no spaces:

    ```js
    const a = 1;
    ```


    const b = 2;
    ```

````

**Comment by kachkaev** [comment]
Shall we close this issue? WDYT of keeping 2+ empty lines in indented code blocks? Curious as this is quite topical for Elm.

**Comment by kachkaev** [comment]
Not sure if the current behaviour can be considered as consistent 🤔 

[Playground](https://deploy-preview-4307--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBGAdAAkwFQO4SYQBOmAtiXJnGQA4wCemANgJZRwDOmerMAFpk60AhmC5IAOlGnZsAA0WcIZOAFpmIqAHMAriO1xZcyFE4xMIzAF5MqANzHsTzC9PnMAIxuYATI6g5TEV5aWkMbHxCEnJKajpGFnYuHj5BKEJhMQkwwLkQ5VUNLT0DIzzsdwsrWwdct2gPb1t-FxDciMwAQQyBOFI2Dz4aaRAAGhAIelZG5FARYmIIPAAFBYROZBARADcIVgATce3zZAAzEWZOOAnPYjEAazgYAGVRMHZtZBhiXRuQA4QMDnS7XCbsa7EGAre7aMgiEFXf4AK04AA8AEL3MBPV4iVQAGWSiLBk10MFo5N8JP+omIkK28OID0BeCgx1oxHYMAA6ocBMgABwABgmnIg1x591oW05XH6Ozgx2IcAAjrpWCqYQZ4TSJtcyKxvr9-pxPsw4ABFXQQeB6kAwESePkHAVIXwTH4iVhsHQAYRUupQGQ4x101xwTs2SAuSIAvnGgA)

**Comment by ikatyang** [comment]
It's just a bug about parsing multiple empty line in "indented" codeblock in remark, we don't actually touch anything from plugins except removing the trailing newline.

We should keep this issue open for tracking remarkjs/remark#330.

**Comment by kachkaev** [comment]
OK. Good to know that you are considering this a bug and don't say that a closed code block after a 2+ empty lines is an OK behaviour 😉
