### ISSUE TITLE
Typescript: debug check error for ternary and multiple variable children

### ISSUE THREAD

**Issue by gtod** [prettier/prettier#4308]
**Prettier 1.12.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3wCU4SwCAzHCdfAHRBxrvdal7gAe2PPgAmceiQCuAGwZSodVNHwAxCBAAUASnzBe+fJChkCAWQRT8AXnwAeUagBu+APQA+XgfycYUnFD4ZiQwABYAdDgkUKLMOvju+AAM4QCs+AD8QZb4SN6GDs6egYalwBZQUgC++WUV1bV2ro5OxTVQIAA0IBCYMMomyKAkOEwA7gAKIwhkyCAkThCool3zpsiSMmRw3QBGUWAA1nAwAMqYtKhQAObIMDhSOyCxYBskW09X23gTUdfoJDeH26ACsyAIAEIHY5nEjoOAAGSucCB226ECkMEwmIATHcHk8LjhvnMYABPTBwMhgHCoPqrTC02AAdWWYWQAA4kt1GRBtsyopg5oyqXAcE4Ud1OABHKSoTi-Ej-QFITZokDbdCofGPbpkK7XGRwACKUgg8FRTxgJF2rNE7KQOO69xIqBkBoAwswAXMoNBJSApNsACo22aq97bKpVIA)
```sh
--parser typescript
```

**Input:**
```tsx
import * as React from "react"

export default function Foo() {
  const Menu = <div />

  return Math.random() > 0.5 ? Menu :
    <div>
      {Menu}
      {Menu}
    </div>
}

```

**Output:**
```tsx
import * as React from "react";

export default function Foo() {
  const Menu = <div />;

  return Math.random() > 0.5 ? (
    Menu
  ) : (
    <div>
      {Menu}
      {Menu}
    </div>
  );
}

```

**Second Output:**
```tsx
SyntaxError: '>' expected. (4:21)
  2 | 
  3 | export default function Foo() {
> 4 |   const Menu = <div />;
    |                     ^
  5 | 
  6 |   return Math.random() > 0.5 ? (
  7 |     Menu
```

**Expected behavior:**
No `--debug-check` error.  

#### Notes
No error is reported with the babylon parser.

This is the smallest case I could make.  Specifically:
- if there is only one `{Menu}` child or if both of them are literal `<div/>` then there is no error.
- If your remove the ternary and just return the div, there is no error.

**Comment by thorn0** [comment]
Fixed long time ago.
