### ISSUE TITLE
Skip semicolon insertion in lines following an opening brace

### ISSUE THREAD

**Issue by tav** [prettier/prettier#4316]
**Prettier 1.12.0**

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQAcCuAzgBYCiAbgjIQJSbAA6UmmA2gOTSECGl7ANJk5RIAW1GoY7ALoA6dBABOpbmGLY4lWJgC8APkxgYAD1nFuUACYAbOBq0waNJgF8mIfiAi4YqLslBuRUUIAHcABSCEQmQQXghUSw84whhkdG5rQjhPACNFVQBrOBgAZVxVVCgAc2QYRXwckEsIMHTM7M8q7MUYcILq0W52rKaAK0JjACECsGKy7lE4ABkquBHOr3wYAhgAJg2misUe2NzuXIBPa2hk3EUqmAB1RJhiZAAOAAZPe4hsp4FXCxe5wHqUZKKOAAR3wqCh-W4g2GSAyo082QkhwxVWqtgAivgIPBsSAYBcXpY3sg9p56txUNZcQBhCDiFEgKDQdaeIhwAAqFxiqI6cBcLiAA)
```sh
--no-semi
```

**Input:**
```jsx
if (pushEvents) {
  ['onsave', 'oncommit'].forEach(event => ctx.handle(event))
}

```

**Output:**
```jsx
if (pushEvents) {
  ;["onsave", "oncommit"].forEach(event => ctx.handle(event))
}

```

**Expected behavior:**
```jsx
if (pushEvents) {
  ['onsave', 'oncommit'].forEach(event => ctx.handle(event))
}
```

The automatic semicolon insertion seems unnecessary in this case, where the line immediately follows an opening brace `{`.

This has been brought up before in #3927 by @ichitera and closed by @lydell, but I think this particular case merits exclusion from the rest of the ASI failure protection.

Thoughts?

**Comment by ikatyang** [comment]
See https://prettier.io/docs/en/rationale.html#semicolons.
