### ISSUE TITLE
How to get Prettier to not break up pipeline operator

### ISSUE THREAD

**Issue by babakness** [prettier/prettier#4319]
Hi,

How can I prevent prettier from breaking up the pipe-forward operator or nullish-coalescing operator?

```javascript
const double = x => x * 2
console.log( 10 |> double )
```

Prettier does this

```javascript
const double = x => x * 2
console.log( 10 | > double )
```

**Comment by ikatyang** [comment]
We do support pipeline operator, can you share steps to reproduce?

---

**Prettier 1.12.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATCBXAIwBs5MBeTAD3ID4rMAqTAJgB0pIo0ISA6IiAHMAFJgCMABkwAfOrkIlMAShAAaEBAAOMAJbpkoAIYAnYxADuABRMI0yEIYBuEHdjUOMyAGaGiaOOoExoZgANZwMADKmiE6UILIMMZ4ASC4YN6+-upx-sYwlsGCALaGmX6pAFZolABCwWERkYbFcAAycXDl2Rp4MJp9zN2pMcZ59gSGBACeAlDumsZxMADqrjAAFsgAHBLqixD+K8Ga9otweY5d6sZwAI54OreFhiVlSD4V6v7FOonJqTQcUEJAAingIPBhuoYFM1thNshmDDgjoiMCAMIQYqlexQaDXEB4fwAFSmdg+WTgAF9qUA)

**Input:**
```jsx
const double = x => x * 2
console.log( 10 |> double )
```

**Output:**
```jsx
const double = x => x * 2;
console.log(10 |> double);

```

**Comment by babakness** [comment]
Hi all, after installing the plugin again and restarting clean, it worked! Perhaps some conflict with a different plugin in VS Code, as the plugin used (the most popular) relied on "Format Document" which seemed to already be there before installing Prettier. Thanks again!
