### ISSUE TITLE
Docs - a note about global install on Webstorm

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#4320]
Pls update https://prettier.io/docs/en/webstorm.html to reflect that you might need to specify `/usr/local/bin/prettier` as your prettier executable path on [mac](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000181790-cannot-create-file-watcher-for-prettier-global-install-on-mac) or `C:\Users\user_name\AppData\Roaming\npm\prettier.cmd` on [windows](https://github.com/prettier/prettier/issues/2415#issuecomment-316980139).

**Comment by duailibe** [comment]
Do you want to submit a PR to fix this, @avalanche1 ?

**Comment by prigara** [comment]
Hey! I'm already working on it and will soon send a PR :)
