### ISSUE TITLE
Bug with nested maps and lists

### ISSUE THREAD

**Issue by ad1992** [prettier/prettier#4324]
Looks like there is some issue in formatting nested maps and lists.
Please check the link below
**Prettier 1.12.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASSUBmBLA5kgAgAoAdKAgmACzgFs4BnQ08ig27BmZsttmgIYATOACdCAYiFhMAsAAYANLz4EM8WJPnyAnADYAHACNlrPpggR44ghIMBWMAHYdYFRQCUpvqgYAHUWwofGJ3fjhhMUlMABZZZ29VdQRuWzAAJhj7GLhE80traMwjAEZ7AzCPFSqoDwBuMjIQRRAIPxhsaAZkUAFRUQgAdwAFPoRulAEANwhsIWaQAS5kWQAbBlyQI1E5AGs4GABlPzkg3GQYUQBXTaEIMBWBdc2gjdEYYZ3cWgFH55aAFYMAAeACEdmB9kcBPQADJBOB-DYtCBXGB+NHpJGbE6iN7IEAMMAMbotAJBGAAdTm1GQBiUIACEA2lJ2fgJAUYYimiJaojgAEcrth+Z8BN9fkg1sjCXRsBdrpsGGdVnAAIpXKyIqVPGUwARGalCWlIdItS4CbCrM4AYQgtB+BKg0F5ICuGwAKgaJtK4ABfP1AA)
```sh
--parser scss
```

**Input:**
```scss
$config: (
  themes: (
    mist: (
      header: #dcfac0,
      content: #00968b,
      footer: #85c79c
    ),
    $spring: (
      header: #f4fac7,
      content: #c2454e,
      footer: #ffb158
    )
  )
);


```

**Output:**
```scss
$config: (
  themes:
    (
      mist: (header: #dcfac0, content: #00968b, footer: #85c79c),
      $spring: (header: #f4fac7, content: #c2454e, footer: #ffb158)
    )
);

```

**Expected behavior:**
```scss
$config: (
  themes: (
    mist: (
      header: #dcfac0,
      content: #00968b,
      footer: #85c79c
    ),
    $spring: (
      header: #f4fac7,
      content: #c2454e,
      footer: #ffb158
    )
  )
);

```

**Comment by evilebottnawi** [comment]
@ad1992 please use issue template

**Comment by evilebottnawi** [comment]
@duailibe `(` and `)` looks have incorrect position

**Comment by duailibe** [comment]
Good catch.. I was misguided by the "expected" with the nested ones broken down in multiple lines

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/prettier/prettier/issues/3235, same problem. Thanks for issue!
