### ISSUE TITLE
Respect quoted object keys, as unquoting breaks aggressive minifiers like Closure Compiler

### ISSUE THREAD

**Issue by alextreppass** [prettier/prettier#4327]
Hi, related to the discussions in [#838](https://github.com/prettier/prettier/issues/838#issuecomment-381831221) and [#1103](https://github.com/prettier/prettier/issues/1103#issuecomment-290996915), Prettier uses a `consistent-as-needed` approach for quoting object keys (ref: https://eslint.org/docs/rules/quote-props#options).

This behaviour is a blocker for us using Prettier in my current company (...and we'd really love to use it!) because it strips quoted object keys. This negatively impacts the input to Closure Compiler in our tool chain, which mangles all unquoted keys, and breaks places like http call serialisation where those keys have meaning.

We're unfortunately stuck with CC in our current setup, and hacks like using `{ ['foo']: bar }` or adding `// prettier ignore` in various places have been viewed as muddying the code and/or too much overhead.

I'd love to see Prettier support for something like:

- preserving object quotes, i.e. the approach suggested in [#1103](https://github.com/prettier/prettier/issues/1103#issuecomment-290996915)

- handling quotes in a `consistent` way instead of `consistent-as-needed`, i.e. if it finds at least one quote in an object, it will ensure all keys are quoted

Is this something I could help with? Something like the PR in #1108 would be fine for us. We'd also be totally ok with `consistent` quoting if that's more in-line with Prettier's strongly-opinionated philosophy.

Thanks,

**Comment by alextreppass** [comment]
cc: @vjeux who asked me in #838 to open a seperate issue for this

**Comment by vjeux** [comment]
Okay, so it sounds like there's actually a reasonable workaround for Closure Compiler with advanced mode: putting brackets around the key: `{['key']: value}`. While it is not optimal, I believe that it is the best way forward for two reasons:

- Closure Compiler with Advanced Mode is barely used in practice. In all the existence of prettier, you are only the second person to say that they are actually using it.
- The workaround of adding `[]` around keys is not pretty but is not unreasonable either and I would argue that it is more explicit than just having quotes changing the meaning of the key.
- My understanding is that quoted keys should be the exception rather than the norm, so it shouldn't affect most of your codebase (I could be wrong though, if you could get some stats on this from your codebase that would be very helpful).
- If we can get away with not adding an option for this, I believe that it would be better for the future of prettier.

Let me know what your thoughts are.

**Comment by alextreppass** [comment]
Hi @vjeux, thanks for engaging with this.

> Closure Compiler with Advanced Mode is barely used in practice. In all the existence of prettier, you are only the second person to say that they are actually using it.

I suspect others will be in the same boat, just suffering silently. Maybe some Googlers can chime in too? It may also affect Uglify's prop mangling in a similar fashion.

> The workaround of adding [] around keys is not pretty but is not unreasonable either and I would argue that it is more explicit than just having quotes changing the meaning of the key.

It actually produces different, far-less-optimal output:

```js
const a = { ['foo']: 1};
const b = { ['bar']: 2};
console.log(a, b);
```

becomes:
```js
var a={},b=(a.foo=1,a),c={},d=(c.bar=2,c);console.log(b,d);
```

...which is nuts. Whereas the output without `[]` is:
```js
console.log({foo:1},{bar:2});
```

[link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconst%2520a%2520%253D%2520%257B%2520%255B'foo'%255D%253A%25201%257D%253B%250Aconst%2520b%2520%253D%2520%257B%2520%255B'bar'%255D%253A%25202%257D%253B%250Aconsole.log(a%252C%2520b)%253B%250A%250A)

> My understanding is that quoted keys should be the exception rather than the norm, so it shouldn't affect most of your codebase

You are correct in that it's the exception here. 

The fear among the team is that Prettier in its current mode reduces safety - whereas before string keys would be kept, this time we'd need to make sure the devs include a `// prettier-ignore` above the statements going forward, which may be hard to enforce with tooling. Or we'd have to rewrite a bunch of our code to use different structures (e.g. `Map<string, X>`, or `Array<Array<string>>`), which is a hard refactor to justify for better formatting in a large codebase.

> If we can get away with not adding an option for this, I believe that it would be better for the future of prettier.

I'm torn here. I (and others - there are quite a few related issues + duplicates in the project here) would love to see Prettier preserve keys, or work in a `consistent` way (instead of `consistent-as-needed`). 

I realise that can be viewed as being a subjective preference though. 

For us, it's not about subjectivity - it's that without it, I can't think of a tenable / scalable way to use Prettier here, because we can't move away from CC.

We'd _really_ love to use Prettier, and a bunch of us in the company are trying to come up with ways to make it happen, but there doesn't seem to be an elegant way we can enforce it with our current tooling.

**Comment by duailibe** [comment]
What are our options (on Prettier side)? Don't change the quotes, either always (i.e. stop removing quotes) or with an option.. What else?

```jsx
var a={},b=(a.foo=1,a),c={},d=(c.bar=2,c);console.log(b,d);
```

This is really nuts and someone should probably be raise an issue in CC about that

**Comment by alextreppass** [comment]
@duailibe the options on the Prettier side I can think of are:

- Keep string names where they are found (pretty simple, see example implementation in #1108)

- Work in a `consistent` way instead of `consistent-as-needed` (https://eslint.org/docs/rules/quote-props), i.e. if Prettier finds at least one quoted key, then quote all keys.

**Comment by bakkot** [comment]
@alextreppass:

> It actually produces different, far-less-optimal output:

Seconding @duailibe that this is a bug in the closure compiler; if this bug with them is the only blocker, I don't think prettier should be working around bugs in other tools. Perhaps the best way forward is to raise this with them? Probably worth doing so regardless of how prettier proceeds, honestly.

> Whereas before string keys would be kept, this time we'd need to make sure the devs do things like include a // prettier-ignore above the certain statements going forward, which may be hard to enforce with tooling.

Really? I would expect this to be almost trivial to write an eslint plugin for. A sketch:

```js
module.exports = {
  meta: { /* the usual boilerplate */ },
  create: function(context) {
    return {
      Property: function(node) {
        if (node.computed || node.key == null || node.key.type !== 'Literal') {
          return;
        }
        let comments = context.getSourceCode().getCommentsBefore(node);
        if (!comments.some(c => c.value === ' prettier-ignore')) { // TODO use whatever check prettier does, not this simple matching
          context.report({
            node,
            message: 'String keys should have prettier-ignore comments, for compat with closure compiler',
          });
        }
      },
    };
  }
};
```

**Comment by alextreppass** [comment]
Have opened a ticket with the CC team, let's see how that goes: https://github.com/google/closure-compiler/issues/2897

**Comment by kushal** [comment]
In addition to the Closure/mangler needs here, the aesthetic issue raised in https://github.com/prettier/prettier/issues/1103#issuecomment-330839212 is a real thing - I'm surprised more people haven't run into that!

**Comment by j-f1** [comment]
Once the Closure issue gets fixed, I think we can close this issue as there will be no runtime issues.

**Comment by alextreppass** [comment]
Agree, thanks

**Comment by duailibe** [comment]
I don't think we need to leave this open since it's not actionable. Comment if anyone disagrees and we'll reopen.

**Comment by evmar** [comment]
For what it's worth, within Google we have discussed adopting prettier but (obviously) as the main users of Closure compiler, this bug means we cannot.  I also suspect converting all our existing code to put brackets around quoted object properties is a non-starter.

I appreciate the rationale given on these bugs, and it's not your responsibility to solve our problems, but just in case you wanted another use case.  In any case clang-format works well enough for us.

**Comment by bakkot** [comment]
@evmar, can I ask why converting existing code to put brackets around quoted objects is a non-starter? You wouldn't need to do it for all code, just for projects which are trying to adopt prettier, and it can be [done automatically](https://github.com/prettier/prettier/issues/1103#issuecomment-297842553) with little effort. I appreciate wanting to avoid that sort of churn in general, but doing it as part of the process of adopting prettier wouldn't create much additional churn over just introducing prettier in the first place, I'd think.

**Comment by evmar** [comment]
We already use an automated formatter (clang-format) and it's even required for all TypeScript files, so I would hope rolling out prettier wouldn't change our code much.  You're of course right that it's possible to automate.  I worry much more about how to train everyone who touches JavaScript about this new rule ("use square brackets around quoted keys if the quoting matters for your code").

Property renaming in Closure compiler is already really subtle, and frequently breaks code in a way where the tests pass and it breaks in production, which means it's easy for people to get this wrong and not notice until it's too late.  (In my opinion the design of the feature is pretty wrong, but we have a large quantity of code&sup1; that relies on it in hard to notice ways.)

1 total repository size is over a billion source files, though that includes non-javascript languages

**Comment by alextreppass** [comment]
> I worry much more about how to train everyone who touches JavaScript about this new rule ("use square brackets around quoted keys if the quoting matters for your code").

@evmar for what it's worth, I wrote a tslint rule for it, and this is caught by a CI step that will fail the build if there are lint errors.

**Comment by calebegg** [comment]
Many (most?) of our users have their editor configured to format on save, or are at least accustomed to running the formatter often. So by the time tslint ran, it might be too late and the quotes might be gone.

**Comment by alextreppass** [comment]
@calebegg in our case the lint rule was auto-fixable (edited my above post to mention it), so on save it'll become computed.

**Comment by bakkot** [comment]
@evmar Personally, from afar I think the "use computed properties if you want closure not to mangle them" rule is much easier to learn than the "use quoted property names if you want closure not to mangle them" rule you're presumably currently teaching, especially given that there are other reasons to use quoted property names (i.e., non-identifier keys). And then non-mangled keys stand out a lot more: I think that, for myself, I would be much more likely to see `{ ['some-key']: val }` and think to myself "oh, that's not going to get mangled, I should change the key if I want it to be" than I would be for `{ 'some-key': val }`. Especially if my editor changed my `'some-key'` to `['some-key']` on save.

As such, I'd think that long-term it would be better to switch to computed keys anyway, even if it does come with some transitional cost.

**Comment by evmar** [comment]
I appreciate that you don't want to budge on this.  I am just creating a mini-doc internally about why we hadn't adopted prettier and wanted to make sure I covered all the points.  Here, it's not "cannot quote object properties", but rather "would need to change our JS style, linter, and education around object properties".  It's not surmountable for sure, but also not an obvious win.  Thanks for thinking it through with me1

**Comment by vjeux** [comment]
@evmar: I’d love to read that document if you’d be willing to share it. Maybe we can work on finding a middle ground such that you can use prettier at Google

**Comment by evmar** [comment]
@vjeux The biggest hurdle is that clang-format works decently well already and is integrated into lots of other layers due it covering C++/Java.  So the main benefit for adopting prettier for us would just be synchronizing with best practices "outside".  This is definitely something we care about, but it's hard to justify the work of doing it.

**Comment by vjeux** [comment]
That makes a lot of sense. I’ve been involved in similar challenges at Facebook.

**Comment by vjeux** [comment]
It's a shame that people using Google Closure Compiler Advanced Mode can't use prettier. The intention behind having few options is to prevent bike-shedding, not to prevent people from using the project altogether.

Let's discuss and find a solution that would solve this problem. I know that @azz has some ideas.

**Comment by azz** [comment]
I'm thinking we can solve this, as well as #838 with a new option:

### `--quote-props`

Values:

`as-needed` (default) - Only add quotes around object properties where required. Current behaviour.
`preserve` - Respect the input (solves this issue)
`consistent` - If _at least one_ property in an object requires quotes, quote all properties (#838)

**Comment by azz** [comment]
PR is up at #5934 - Feedback welcome!
