### ISSUE TITLE
Parser flow SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by psamim** [prettier/prettier#4328]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9jsIBbPAcgDoB6AYVIGcALASzjYO0GKX5QhLAFbcmAbhAAaEBAwx+0bslClsdAO4AFPQm0pSANwj8CykDxjIylbnBUAjbKTABrODAAyhg+EgDmyDDY5O4gBBBgzqSusRJuuEbeYfSkSSkqsmgAQt5+AYGk9HAAMhJweW4qEOQwGC0ATA2xIdjpyCDElBAG9hjYEjAA6rYwvMgAHAAMKmMQbpPeGP1jcOmW9SrYcACO5PxHmaTZuUgujSBu9PyR0bHc4ZRwAIrkEPBdKjEHmmBFmyHagO8-Eo4RE9By-Sg0AOIHIbgAKqQPOY7nAAL54oA)
```sh
--parser flow
```

**Input:**
```jsx
export default from './CashierContainer.js';
```

**Output:**
```jsx
SyntaxError: Unexpected string (1:21)
> 1 | export default from './CashierContainer.js';
    |                     ^^^^^^^^^^^^^^^^^^^^^^^
```

**Expected behavior:**
The code has no syntax error and can be transpiled by babel.

**Comment by lydell** [comment]
This syntax is not part of the ECMAScript spec. It comes from this proposal: https://github.com/tc39/proposal-export-default-from

Babylon supports that syntax, but Flow doesn’t. See https://github.com/facebook/flow/issues/940.

You can use this syntax instead:

```js
export { default } from './CashierContainer.js';
```

**Comment by j-f1** [comment]
You could also switch to the Babylon parser, since it supports Flow, too.
