### ISSUE TITLE
Single quotes convert to double if there are escaped single quotes

### ISSUE THREAD

**Issue by aelyseev** [prettier/prettier#4331]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoByGAC1wwAINyIBXAG1SgB02ySAaaogSmoBeAHzVgbKNWq4YpQtQBmAQyYY4PPoNHjJ06XAAeABzhg5MbAzj8AdDAgAhYpev8A3HuoBfD5N+eUCDcIBDGMLjQGMigytjYEADuAApxCNEoygBuELiowSDKGDDIKmpwIfjYymAA1nAwAMrGNbhQAObIrhVoEGClquohberYMMnV7QC2ygPlIQBWGIaO1XUNjcpTcAAybXBzQ6EMMMYnAEyHPS3Yo8ggMACeplh44QXGeLAA6nkUyAAOAAMIU+EHU32qxnun0wcGwWQOIWwcAAjgxcCiJspprMkGUjuoprgulYehg2u0mHAAIoMCDwUnWEIwZT4X6of5Ic4s6q4JiUgDCECmM3uUGgSJADHUABU2RkCXBvN4gA)
```sh
--parser typescript
--single-quote
```

**Input:**
```tsx
describe('this shouldn\'t', () => {
  it('be false', () => {
    expect(true).toBe(true);
  });
});

```

**Output:**
```tsx
describe("this shouldn't", () => {
  it('be false', () => {
    expect(true).toBe(true);
  });
});

```

**Expected behavior:**

The quotes inside `describe` should be single.

```tsx
describe('this shouldn\'t', () => {
  it('be false', () => {
    expect(true).toBe(true);
  });
});

```

**Comment by j-f1** [comment]
This is intentional behavior — we try to minimize escaped quotes, although we will use your preferred quote style when there are equal numbers of single and double quotes in the string.

**Comment by lydell** [comment]
https://prettier.io/docs/en/rationale.html#strings

**Comment by aelyseev** [comment]
@j-f1, @lydell do you know, could I ask prettier to ignore quotes at all? Or are you going to add this?

Unfortunately, I can't turn off quote's lint settings for a project, but from another perspective, I'd like to use prettier.

**Comment by j-f1** [comment]
We almost never add options, so I’d recommend convincing your team to disable the lint rule (check out `eslint-config-prettier` for an easy-to-use config that prevents conflicts with Prettier.
