### ISSUE TITLE
JSON keys wrongly unquoted

### ISSUE THREAD

**Issue by artola** [prettier/prettier#4332]
**Prettier 1.12.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm4A95QAmAzkpmiDMQDYCWsAtAE5wCGYMFANBtkwK7U4pTOizZyIAFbFcDVnQDmUALYJOyTDAFwe47BRlyARhAhDWUBgDcF-OBTLb7eiZKMMw-JtQCeDYgAHdnpFR0wAbWddSSg4azgmCgBdVwlDWQY4AEd+BWIA4LBQ8KidLlj4xJS0g2lMgGs4X3Do2vdMqAgGY3pCVvLedPq5LoZqVhVjQlYBlyG6jzGVQRhaOjiGGTndBY7R7uJtUOY4ADMd9ozcYjhqM7BqCFvLveuGAHcmVkCGFeo1hsHJpokMAL4YCFQEBcEAQQJraDEZCgVhMJgQD4ABTRCGRKFY1ggtEIMJArCOyDO+V0IGM3zATRgAGUiqFkG0QIQIGAqTTYfRbkwYFjvooVKw+dRbrCjAAhBlM5mTOAAGXocClMrh-BggV1ACYtbTgkwhch6tAyYEmPQYAB1EkwAAWyAAHAAGWE255we3fQIWm3CRIJMksXK0Fii1jiyVIanS2m3FS0DnlEDEUJCACK-Ag8GNsJgrGMjsILuQBuL33WoQAwhAVBKLQpqGT+LcACql-GJ25gsFAA)
```sh
--parser json
--trailing-comma all
```

**Input:**
```json
{
  extends: "tslint-react",
  rules: {
    "jsx-alignment": true,
    "jsx-boolean-value": true,
    "jsx-curly-spacing": [true, "never"],
    "jsx-equals-spacing": [true, "never"],
    "jsx-key": true,
    "jsx-no-bind": true,
    "jsx-no-lambda": true,
    "jsx-no-multiline-js": true,
    "jsx-no-string-ref": true,
    "jsxselfclose": true,
    "jsx-wrap-multiline": true
  }
}

```

**Output:**
```json
{
  extends: "tslint-react",
  rules: {
    "jsx-alignment": true,
    "jsx-boolean-value": true,
    "jsx-curly-spacing": [true, "never"],
    "jsx-equals-spacing": [true, "never"],
    "jsx-key": true,
    "jsx-no-bind": true,
    "jsx-no-lambda": true,
    "jsx-no-multiline-js": true,
    "jsx-no-string-ref": true,
    "jsxselfclose": true,
    "jsx-wrap-multiline": true
  }
}

```

**Expected behavior:**
All keys must be quoted with `"`. See above `extends` and `rules` are not fixed.

```json
{
  "extends": "tslint-react",
  "rules": {
    "jsx-alignment": true,
    "jsx-boolean-value": true,
    "jsx-curly-spacing": [true, "never"],
    "jsx-equals-spacing": [true, "never"],
    "jsx-key": true,
    "jsx-no-bind": true,
    "jsx-no-lambda": true,
    "jsx-no-multiline-js": true,
    "jsx-no-string-ref": true,
    "jsxselfclose": true,
    "jsx-wrap-multiline": true
  }
}

```

**Comment by ikatyang** [comment]
Marked as `feature request` since the input is a valid [JSON5](https://github.com/json5/json5#objects) and so does the output, we currently just print property keys as-is for json files.

https://github.com/prettier/prettier/blob/00b7aed75e324ca76484f0d12d76e6f97e71a23b/src/language-js/printer-estree.js#L3056-L3073

**Comment by artola** [comment]
@ikatyang to be consistent, if JSON5 is applied, `Objects and Arrays may have a single trailing comma.` specially when flagged `--trailing-comma all`
But I would prefer just `JSON` compliant output.
