### ISSUE TITLE
Prettier is not able to format this javascript code...

### ISSUE THREAD

**Issue by Ravi-Rajpurohit** [prettier/prettier#4337]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBnMALOAEwFd1CBhAJ2gFEAPAB0rm2wEtpMBeTAAzGpQAFABJg2BIQAiAQ3gA6AOYYAsmyjF42IQEoAvpjESo0uXCUYAEhGKVt+w+MmyFymC7i6DR52YswVaBg8XUwAagAdKAiYGLjYhIBGAwB+R2NTVwwAMVJUAE04GUovHV4AbhAAGhAIBhgOKGxkUCZ1GAB1NkJg5AAOAAYamBkAIy6evGQAJhr2KEV0AEViCHhkADMZVAlhyhk2VHVFcggAWzOZZBAoaDhqkFH9sABrDABlBhkwY+QYSmIcBqACtsHQAELPN4wd4yM5wAAy6nuSC2OyBIC+djglGuozGAE9UNAHhIzmw-gCMcQJAAVMbNVHbXYgdQSSgwAAK+0Ul02zIxzAAjsQ2MxuTJeVcmeiakwIBIOvsGNcmCwcQA3e41YrUADunOKCEZIBkGog3QehAgYH5stN2BgdpZNhgDE002dcD0eiAA)

**Input:**
```jsx
let scheduledCronExpression = `cron(${sendDate.getMinutes()} ${sendDate.getHours()} ${sendDate.getDate()} ${sendDate.getMonth() +
						1} ? ${sendDate.getFullYear()})`;
```

**Output:**
```jsx
let scheduledCronExpression = `cron(${sendDate.getMinutes()} ${sendDate.getHours()} ${sendDate.getDate()} ${sendDate.getMonth() +
  1} ? ${sendDate.getFullYear()})`;

```

**Expected behavior:**

**Comment by j-f1** [comment]
@Ravi-Rajpurohit What is your expected behavior here?

**Comment by Ravi-Rajpurohit** [comment]
Expected Behavior : The code should fit in the default limit of 80 columns.

**Comment by j-f1** [comment]
Prettier uses its print width as a guideline, not a hard-and-fast rule. In some cases, like this one, we will go over the limit. We do so here because people didn’t like how the template string looked when member expressions were wrapped.
