### ISSUE TITLE
Ternary expressions as call arguments can be difficult to read

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#4338]
I'm not sure whether it is by design or a bug, but it can be really difficult to see how many arguments the `fn` function is called with in the code below.

**Prettier 1.13.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzKAKAOlABLgIwEtUIAnKAYTKKgHM4yBZCAZwAs4ATABUYAcANnAAeAZQCGAdy6MANDnwTWAawAqZCADcEEgEJxdAETj8EXVgCUIUiVFYK8uOoKIBbVnADiggJ792VgAJCQAvCTIuADkICH5WNSI4RLhcAF4M3AkdMjJuPQkYTjJWPQgRTQg3PQBXOjpfKJqyQXwAMjbFfCyoCC5fKDhKaC42JglBQrgAeRypyzgYWghWru7cAH4eqBrJsmGIQy4xISIwOFYAdQmVK4lfa99cNe6kXBUIMHYJAgOkrwkbhmUGmBBWcAAqlApHBsqkcABKADcOBAchAcSW0FYyFAEU0Uh4EQQOJQ2QgRC4aJAyhgyFQE086IIZAkYBUixObNodGQMDINTg6NGYHpjKFIFonjIMB4rLobgkYsETJAACtWCI9Kz2ZzAXAADK0ODK1UQGowfgWgBMpol-Ai0uQIAIP18gmg1P4NFgl0pRWQAA4AAzo71sOCXVn8Z3ei6MHTUvIARxqRDycokCqVSAZKolnjcRD5AoLPOEAEUahB4Hb0TAfn6uAGkNb66yiK56MM3Irnb1BtSap41D9SXnPABfSdAA)
```sh
--parser babylon
```

**Input:**
```jsx
fn(
  bifornCringerMoshedPerplexSawder,
  askTrovenaBeenaDependsRowans,
  glimseGlyphsHazardNoopsTieTie === averredBathersBoxroomBuggyNurl  &&
    anodyneCondosMalateOverateRetinol 
      ? annularCooeedSplicesWalksWayWay 
      : kochabCooieGameOnOboleUnweave 
);

```

**Output:**
```jsx
fn(
  bifornCringerMoshedPerplexSawder,
  askTrovenaBeenaDependsRowans,
  glimseGlyphsHazardNoopsTieTie === averredBathersBoxroomBuggyNurl &&
  anodyneCondosMalateOverateRetinol
    ? annularCooeedSplicesWalksWayWay
    : kochabCooieGameOnOboleUnweave
);

```

**Expected behavior:**

Same as the input, probably.

**Comment by lydell** [comment]
I agree!

**Comment by duailibe** [comment]
Not exclusive to call arguments

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBzANgSwLYGc4Di6AngA4AWuAEgIYBeNATgCYByEEpuAKpnL3AAEAXlGCaANziNGcZgCEaMctNzyIAD0Yds8gK6pUxVnsbpBggGSWAOlAs0oEZsShwAwtGYRcAWRroSnAA8lKMQQBKcDCYTuZ2FhYA-OJQUHqBjJ4QcHIAyqRYYHC4AOoBANZlNMTlxIIJiUiCFRBg5DQARtl8BDTYIVDBnRDocACqUADucJJwANx2IAA0IJwx0LjIoEzaUwAKTAhbKJIQmMwrIDS4MMgAZgH4q53hYBXRBTRgsajIMIw9HBVt4wA8nsCQLF8IwYPtwqhsDRwehniAAFa4DTyN4fGB5fpwAAysTgKLRED0MFIVIATOTIaQmDDkCBOl1iOhoFdSIxYjBShdlMgABwABlWvJ8cFK4VIrN5JWkUiusgAjnpMLJ4TREcikI9UZD8NhMP9AcbfmMAIp6CDwBmrGBdQXMYVIWlO8KYLBQVCebBI1lONxXPT4bhdE6G-AAX1jQA)

**Input:**
```jsx
glimseGlyphsHazardNoopsTieTie === averredBathersBoxroomBuggyNurl  &&
  anodyneCondosMalateOverateRetinol 
    ? annularCooeedSplicesWalksWayWay 
    : kochabCooieGameOnOboleUnweave;

```

**Output:**
```jsx
glimseGlyphsHazardNoopsTieTie === averredBathersBoxroomBuggyNurl &&
anodyneCondosMalateOverateRetinol
  ? annularCooeedSplicesWalksWayWay
  : kochabCooieGameOnOboleUnweave;

```

**Comment by evilebottnawi** [comment]
Looks like bug

**Comment by malcolmsgroves** [comment]
I'd like to work up a PR for this if no one has started

**Comment by lydell** [comment]
@malcolmsgroves The examples you posted are not part of a function call so I don't understand what you are trying to show?

**Comment by malcolmsgroves** [comment]
Oh I get it. Just for clarification @lydell is @duailibe's example expected? That's where I was a bit hung up

**Comment by lydell** [comment]
Not sure what @duailibe tried to show. Let's start with focusing on the function calls.

**Comment by malcolmsgroves** [comment]
I'm a bit stuck...it's easy to do this
```javascript
fn(
  bifornCringerMoshedPerplexSawder,
  askTrovenaBeenaDependsRowans,
  glimseGlyphsHazardNoopsTieTie === averredBathersBoxroomBuggyNurl &&
    anodyneCondosMalateOverateRetinol 
    ? annularCooeedSplicesWalksWayWay 
    : kochabCooieGameOnOboleUnweave 
);
```
but indenting the last two operands is challenging because they are in the same level in the AST as the test node, and therefore the level of indentation from the test doc is lost. I couldn't think of any solutions that don't require editing the test doc object. Any ideas?

**Comment by j-f1** [comment]
Some improvements were made in #4368, but we’d like to have the `?` and `:` lines indented another step. Leaving this open until that gets fixed.

**Comment by thorn0** [comment]
closing in favor of #8741
