### ISSUE TITLE
Print width not respected in case of nested functions

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#4339]
There are some related issues that point that same issue happens in case of assignment, but I didn't find one relating to nested functions.

Please close if it's a duplicate

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQDMITYC828AzjMQHzbAA6U22AJnGWJgJYBGcAFHwCU1WgyZNW7LrwHCiNeo3FNOMPgHIASnBhc4qNqQAWcbKs5Q4mLAE9sAMmwAbOAHMyZxgAUAggEkAEWwIHB8AYQAVPwA1HwiAUSCKdHgAGmxuAgBrC3dPbF9A9M14gGV4zWjE4JwwgHkAOQAxP00AWWrk+HV0oRFFZSYAX0EAbjFxEfGlKYYh6ZBUkAgABxhOaDJkUCxMCAB3LywELZR0VAhOZkWQdApkXHQnMjgl7mswLJ1SlfQwXOQugArq8QMwIGAHk8XksLC9MDAvNZXABbdBQ56ggBWZAAHgAhD5fGCldAouAAGQscAxMOWQJgKwZACZaaDfph4cgQNx0NwbE5oDcVlxYAB1K4wIzIACMzIADEsRRAXmLrCtuSK2FYDDdMHAAI5Azj6pHoVHopCPTFLF4oziAzAg225FwARSBEHgbKWMD5EuYUuQzN91k4TlyYQgKLR3Kg0BpSyBLwifNO1peQyGQA)
```sh
# Options (if any):
--print-width 120
```

**Input:**
```js
var foo = test => {
  describe(() => {
    describe(() => {
      it('Retrieves the itinerary & legs in PAID or ACTIVATED state, bookings in PAID, RESERVED or CONFIRMED state', () => {
      });
    });
  });
};

```

**Output:**
```jsx
var foo = test => {
  describe(() => {
    describe(() => {
      it("Retrieves the itinerary & legs in PAID or ACTIVATED state, bookings in PAID, RESERVED or CONFIRMED state", () => {});
    });
  });
};

```

**Expected behavior:**

Should put most inner `it` arguments into new line as:

```js
var foo = test => {
  describe(() => {
    describe(() => {
      it(
        'Retrieves the itinerary & legs in PAID or ACTIVATED state, bookings in PAID, RESERVED or CONFIRMED state',
        () => {}
      );
    });
  });
};
```

**Comment by ikatyang** [comment]
This is intended, see #842.

**Comment by medikoo** [comment]
I see, it'll be great if it's an option, and not something forced, at least I don't favor that behavior

**Comment by j-f1** [comment]
See https://prettier.io/docs/en/option-philosophy.html for why we generally don’t add options.

**Comment by medikoo** [comment]
I'm aware of that, that's why I rely on a [fork](https://github.com/medikoo/prettier-elastic) ;-) So not that big issue for me.

**Comment by evilebottnawi** [comment]
@medikoo you can create plugin-prettier-elastic, run prettier inside you plugin and reformat as you want again without fork

**Comment by medikoo** [comment]
> @medikoo you can create prettier-plugin-elastic, run prettier inside you plugin and reformat as you want again without fork in theory

I want this to be backed with all prettier tests (updated according to changes), so plugin seems not as solid option.

Also it seems faster to make prettier expected output instantly instead of doing two passes.

**Comment by j-f1** [comment]
You could run `git revert 184382d` in your fork to get back the old-style formatting for `describe`/`it`, but you’ll probably have to fix some merge conflicts.

**Comment by medikoo** [comment]
Thanks @j-f1 good tip
