### ISSUE TITLE
Assignment chains aren't wrapped

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#4340]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjAlgMwgJygYR3SgHM4cBZCAZwAs4ATABXIAcAbOADwGUBDAO4NyAAgC8IvtQDWAFRwQAbgj4AhOCoAicVggbUAShAF8o1cSIA6UESJLt0AW2pwA4uwCerWtQASfAC8+HAYAOQgIVmpZdDgYuAsAVyhhTGJGAG5rEAAaEEiYdGhqZFBghQEmYIQSlD5FCHQGXJApGGRMPnYXPNQcPjBpOBgeVgHiEmQYHES4PIYIMA6unpBiFxwYJn6SRz5l7rmQACtqLlV+weH+RzgAGXSD1YhEmFZXgCYno7GcDeQ0HxUB52NAWqwiLAAOpNGC0ZAADgADHkITQ4FD+qwARC4BtlC0cHAAI6JdBE7Z8Xb7JCdQ55FyOdBTGZHagTTgARUSEHg3zyMCBMIYcOQHwF-XQDlI+Agjj2AKg0DgLUSLlkQNqdJcAF8dUA)

**Input:**
```jsx
bifornCringerMoshedPerplexSawder = askTrovenaBeenaDependsRowans = 
  glimseGlyphsHazardNoopsTieTie = undefined;

```

**Output:**
```jsx
bifornCringerMoshedPerplexSawder = askTrovenaBeenaDependsRowans = glimseGlyphsHazardNoopsTieTie = undefined;

```

**Expected behavior:**

Same as input, probably.

**Comment by lydell** [comment]
How did you come up with the variable names?
