### ISSUE TITLE
Single quotes cfg does not remove double quotes inside React render() (as standard.js)

### ISSUE THREAD

**Issue by ReactGirl** [prettier/prettier#4344]
Using this configuration:

```
"prettier": {
    "semi": false,
    "singleQuote": true
  },
```

Then applying pretty for a code like:

```
render() {
...
<Button.Group floated="left">
            <div className="ui vertical animated button secondary" tabIndex="0">
...

```
This will not remove the double quotes. (it removes the double quotes on what is before the render method btw).

Note that the standard.js does this properly.

**Comment by j-f1** [comment]
See #1080 for the feature request for this, and https://prettier.io/docs/en/rationale.html#strings for an explanation of why it is the way it is.

**Comment by ReactGirl** [comment]
Ok you closed an issue and point to a thread that is closed. Beatiful.

**Comment by j-f1** [comment]
#1080 is not closed.
