### ISSUE TITLE
--list-different twice as slow as --write on large codebase

### ISSUE THREAD

**Issue by tryggvigy** [prettier/prettier#4345]
`--list-different` runs are twice as slow than `--write` runs on a very large codebase (~2650 files). This is counterintuitive to me since I would expect `--write` to have do more work. Is this a known issue? I can't find any related issues or docs explaining that `--list-different` takes a performance hit.

```
$ yarn prettier -v
1.12.1
```

```
$ prettier --write --loglevel silent "{apps,libs,tools}/**/*.js"
✨  Done in 43.48s.
```

```
$ prettier --list-different --loglevel silent "{apps,libs,tools}/**/*.js"
✨  Done in 85.87s.
```

**Comment by duailibe** [comment]
This was fixed in #4528
