### ISSUE TITLE
postcss-simple-vars: computed variable names broken

### ISSUE THREAD

**Issue by mleonh** [prettier/prettier#4348]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjAhmA1gcwE4QCuUAJgLSQA2EeSABACQMAUAzjAJ6VwCUAwhGp4A3AB0oIADQgIABxgBLaK2Sh0eAgHcACuoQqU6AG4QFJKSHTtkAM3SVWcaajyYscGAGVZmBVBzIMHiETiAkEGC29o7Sfo54MNquOAC26FEOoQBWrAAeAEKu2B6e6ClwADJ+cBkxMoQwsg0ATLWhPnjxyOCsKtKyeH4wAOpmMAAWyAAcAAz9BI7DrrLdA3DxRjXSeHAAjoQKO0noqelIdpnSjikKgcGhrH443ACKhBDwbdIw6KijJBNkM1vq4FJQngIUmlulBoFsQIRHAAVX4GC6OAC+GKAA)
```sh
--parser css
```

**Input:**
```css
background-color: $$(style)Color;

```

**Output:**
```css
background-color: $$(style) Color;

```

**Expected behavior:**
Output should be same as input, i.e. no additional space should be introduced.

**Comment by ad1992** [comment]
I think I know the fix for this. Can I take it up  @mleonh @evilebottnawi ?

**Comment by duailibe** [comment]
@ad1992 Go ahead

**Comment by seaneking** [comment]
Can this fix be made more general? Still having issues for plugins like `postcss-modular-scale`, which expects input like this

```css
font-size: ms(2)rem;
```

Which prettier turns into 

```css
font-size: ms(2) rem;
```
