### ISSUE TITLE
Playground: Opening the sidebar in Firefox causes full page scroll

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#4350]
... instead of causing scroll only inside the sidebar.

![screenshot from 2018-04-20 19-05-39](https://user-images.githubusercontent.com/2142817/39064214-f404603c-44cd-11e8-9849-8d0450dbfa22.png)

**Comment by johann-sonntagbauer** [comment]
I will give it a try. 

There is also a problem with Edge
![image](https://user-images.githubusercontent.com/1239401/39391983-eac3b3da-4aac-11e8-94a7-73812945ced5.png)

**Comment by duailibe** [comment]
Awesome. Thank you!
