### ISSUE TITLE
.editorconfig is not used with --stdin

### ISSUE THREAD

**Issue by maximbaz** [prettier/prettier#4351]
This is a similar bug to #2689, but here I'm talking about `.editorconfig` instead of `.prettierrc`.
The reason why this is important is the same - vim users are struggling because prettier integration via NeoFormat uses `--stdin`.

```
$ prettier -v
1.12.0
```

-----------

Create an empty folder `~/test` where we will be doing experiments; every file below will be created in that folder, every command will be executed from that folder.

Create a file `main.css` intended with 3 spaces:

```css
body {
   background-color: white;
}
```

Create `.editorconfig` with the following contents:

```
root = true

[*]
indent_style = space
indent_size = 4
```

Run prettier on a file: `prettier --parser css main.css`
* the result is indendation with 4 spaces - as expected.

Run prettier via stdin: `prettier --parser css --stdin <main.css`
* the result is indentation with **2 spaces - this doesn't respect `.editorconfig`**.

Create `.prettierrc` with the following contents:

```
tabWidth: 6
```

Run prettier on a file: `prettier --parser css main.css`
* the result is indendation with 6 spaces - as expected.

Run prettier via stdin: `prettier --parser css --stdin <main.css`
* the result is indentation with 6 spaces - as expected.

So the problem is only with `.editorconfig`.

**Comment by josephfrazier** [comment]
As the implementer of EditorConfig support, I think the problem here is when Prettier is given input via stdin, it no longer knows the name of the file being processed, so it can't look up the corresponding EditorConfig values (which are determined by the file path). The reason `.prettierrc` works is that its settings don't necessarily depend on file path, whereas `.editorconfig` settings do.

**Comment by lydell** [comment]
```
--stdin-filepath <path>  Path to the file to pretend that stdin comes from.
```

- @maximbaz Does it work if you provide `--stdin-filepath path/to/file.js`?
- Otherwise we need to fix that.

**Comment by maximbaz** [comment]
Thanks for telling me about `--stdin-filepath`! Yes it works as expected, and it makes sense now why it is required to provide.
