### ISSUE TITLE
TypeScript: nicer formatting for generics passed to tagged templates

### ISSUE THREAD

**Issue by beshanoe** [prettier/prettier#4352]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wCU4ATAIQjTwF48SBPAG0oDoKBLANwB5gAMwgQkTGNm5QA5gF8AfAAMAOlDx4ARgEMwAaxnYIAVygVx2SgG41GgCTAMRjEQYK8TiC44iIctUpWIAA0IF4w3NBEyKDa2EYA7gAKcQjRKNq8ENwUISCa2Lp6cDAAyhi60jLIksZwodJEcLhJhTIAttrIQtqsTaEAVkRoVIX6JaXa7XAAMtJw3b39IBXYTdjI+dqabNB5TtIwAOo5MAAWyAAcAAyhnk1HhRibTnDrvAuhlgCOxtyWrW0HS6SB6fXqICa7W4NWwdVCRCq7AAisYIPBFuDQjBticKOdkAAmbGFbisKoAYQg7U6myg0E+IGMTQAKtt0mCmnI5EA.)

**Input:**
```ts
export const RedBox = styled.div<{foo: string}>`
  background: red;
  ${props => props.foo}
`;
```

**Output:**
```ts
export const RedBox =
  styled.div <
  { foo: string } >
  `
  background: red;
  ${props => props.foo}
`;
```

**Expected behavior:**
Since passing generics to tagged templates has landed in typescipt@next and headed to 2.9(https://github.com/Microsoft/TypeScript/issues/11947#issuecomment-383252975) petter should add support for this kind of syntax

**Comment by ikatyang** [comment]
Opened eslint/typescript-eslint-parser#468.
