### ISSUE TITLE
Configuration option requests

### ISSUE THREAD

**Issue by buu700** [prettier/prettier#4354]
I have a number of suggestions, mainly in the interest of minimizing Prettier's impact on our existing code / style conventions. (I'm suggesting these as options, but of course I would be equally happy to see any of it become default behavior.)

Since I know you guys are intentionally conservative about configurability, I'll just list them all off here in one ticket in descending priority, rather than spam a bunch of tickets that will mostly (or all) get the same response.

---

1. Format ternary statements as below. In the past I've done something similar to what prettier currently does, but I like that this style better scales to indefinitely long chains of ternary statements.

```ts
const balls =
	foo === bar ?
		getValue(4) :
	getBoolean() ?
		something(
			'hello',
			2497,
			true
		) :
	somethingElse() === true ?
		{
			apple: 1,
			banana: 2,
			cantaloupe: 3,
			durian: 4
		} :
	getHelloString() === 'hello' ?
		helloObject() :
		goodbyeObject()
;
```

---

2. Format method headers with spaces around the parens, as below.

```ts
	/** Does something. */
	public balls (a: number, b: number) : void {
		...
	}

	constructor (
		...
	) {
		...
	}
```

---

3. Put things like `else` and `catch` blocks on new lines, as below.

```ts
if (balls) {
	console.log('true');
}
else {
	console.log('false');
}
```

---

4. Placement of commas in lists of things as below.

```ts
[
	'apple' +
		'banana' +
		'cantaloupe' +
		'durian'
	,
	something(
		1,
		2,
		3,
		4
	),
	'balls'
]
```

As is, the first comma would be placed as such:

```ts
		'cantaloupe' +
		'durian',
	something(
		1,
```

---

5. Placement of periods in multi-line statements as below.

```ts
return balls().
	map(o => o.getNumber()).
	reduce((a, b) => a + b, 0)
;
```

---

6. Insert exactly two newlines after the initial imports, as below.

```ts
import {balls} from 'balls';
import {log} from './log';


// Logs balls
log(balls);
```

---

7. Space after cast, as below.

```ts
(<any> balls).doSomething();
```

---

8. This last one may be a bit unusual, and might not be all that easy to automate well, but just throwing it out there since I like it and we have a custom tslint rule related to it: aligning nearby assignments (with either spaces or tabs of a specified intended width), as below.

```ts
const balls		= 4;
const helloGoodbye	= 5;

const foo		= getsomeValue(
	29374,
	39475,
	340273,
	348497
);

const bar	= 6;
const baz	= 7;

console.log(bar);

const abcdefghijklmnop	= 8;

return balls + helloGoodbye + foo + bar + baz + abcdefghijklmnop;
```

**Comment by lydell** [comment]
As you probably know, our [option philosophy](https://prettier.io/docs/en/option-philosophy.html) is not to add options.

Some of your requests have been discussed before. Search the issue tracker and you should be able to find them.

The others are … not styles I’ve seen before. If you want to use Prettier you’ll have to accept to give up on your more uncommon styles.

Closing since there’s nothing actionable in this issue. Sorry!

**Comment by buu700** [comment]
Got it, thanks.

**Comment by buu700** [comment]
Just throwing this out there: I think a change to the ternary style along the lines of my suggestion would make prettier a lot more usable.

Everything else was acceptable enough, but we had to back off from adopting prettier because some of our ternary code became pretty much unreadable — well over 100 characters/line, which would've caused lint failures, despite prettier being capped at 80.
