### ISSUE TITLE
One line arrow function followed by a parens produces invalid javascript even if they are separated by newlines

### ISSUE THREAD

**Issue by danielo515** [prettier/prettier#4356]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEkoYIayYC8mAFAJTEB8mAOlLTAOQCSmeANhwO54CeaTACc4MAK5ComGAAsAlmib16pYAA8kARgC+5EABoQEAA4w56ZKDxChEbgAVrCNMhB4AbhDkATAyABGQnhgANaiAMrGwXJQAObIMEJicIYxaHBCMPZBsQC2eMgAZpzphgBWaGoAQkGhEXi5cAAyMXBFJSkgUULpQq7+eP58HNB+xkIxMADqPrLIABwADIbjEOlTQcau43C97m2GIgCOYnIi2Xh5BUjFHKUg6blyCUmdaDGxHHAAimIQ8O07p0YIMZt45kgAEyGRJ4OQcD4AYQguXyrig0AOIDE6QAKoMXDcOtptEA)

**Input:**
```jsx
const constant = () => 
	'I allways return this'

({x:1})
```

**Output:**
```jsx
const constant = () => "I allways return this"({ x: 1 });

```

**Expected behavior:**

The provided input runs perfectly and is valid javascript, however the compilation produces invalid javascript that throws errors.
Seems that you just remove all newlines, but this is not always a safe behavior.

**Comment by j-f1** [comment]
This is the correct behavior — when the JS parser sees the `(`, it interprets it as a call expression, as shown in the output. To stop this from happening, put a `;` either before the `(` or after the closing `'`.

**Comment by danielo515** [comment]
Sorry but I disagree.
The code I posted works on any javascript file as expected. You can put it whenever you want and it will work without throwing any error. However, after applying prettier to it it becomes invalid javascript code that throws errors. So in this case prettier is turning a working javascript script into one that will fail, I think an automatic linter should never do that.
If that were the expected behavior then the javascript interpreter should throw an error on both codes but that is not the case.

**Comment by ikatyang** [comment]
Tested on Chrome 65:

![image](https://user-images.githubusercontent.com/8341033/39134196-9d2d5bb0-4748-11e8-9fe3-530c1bee8d11.png)

**Comment by danielo515** [comment]
Correct. You are right and I was wrong and this issue is just a demonstration of how stupid I am.
I didn't tried to execute the function, that was why I didn't got any error. Shame on me

**Comment by j-f1** [comment]
Don’t feel too bad 🙂 JavaScript’s [semicolon insertion rules](https://tc39.github.io/ecma262/#sec-automatic-semicolon-insertion) can be pretty confusing.
