### ISSUE TITLE
Bug with optional properties in typescript class

### ISSUE THREAD

**Issue by james-schwartzkopf** [prettier/prettier#4366]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAYRPIFE1iBbDQuPYAHSjzw5GIC0GbBAx8A-EjwAjCBFbEoAbi4BfLl3RZceAJaw42AGbEwbAJIHjpuPSYs2nbr35CRYkJJlyFytSAAaEFEYXWhSZFBibBEAdwAFaIQIlGIANwhdABNAkGlsUwBrOBgAZQxTfQBzZBhsAFc4IP1SQxh4gqrGYmQTQlaggCtSNAAhArBisqY4ABl9OF7ifqaQCuxW7GQQGABPDDhSMGxdDBhc4X0YAHVsmAALZAAOAAYg4QhW64KMbeFDwxpRZBbBwACO9V0oI6xC6PSQfQGIFajF0tQaq1I1VYAEV6hB4EsVkEYMRpLcsg9kAAmEkFXSEaqUCCMbrbKDQYEgeqtAAqZJSiLgqlUQA)
```sh
--parser typescript
```

**Input:**
```tsx
export class ClassExample {
  "a-prop"?: boolean;
}

export interface InterfaceExample {
  "a-prop"?: boolean;
}
```

**Output:**
```tsx
export class ClassExample {
  "a-prop": boolean;
}

export interface InterfaceExample {
  "a-prop"?: boolean;
}

```

**Expected behavior:**
The '?' should not be removed from "a-prop" in ClassExample.

**Comment by duailibe** [comment]
It's weird that without quotes, the parser sets `optional: true` in the property's `key` node (an `Identifier`), but with quotes, `optional: true` is set on the `ClassProperty` node. I raised https://github.com/eslint/typescript-eslint-parser/issues/472 before adding another `printOptionalToken`
