### ISSUE TITLE
Formtting a blank markdown files results in adding \n

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#4370]
**Prettier 1.12.1**
~~~[Playground link](https://prettier.io/playground/#.....)~~~ (playground formats a default example when the input is blank)

**Current behavior:**

Unlike for `.js` and `.ts` files, formatting an empty `*.md` file results a `\n` character in the end of a non-existing line one.

**Expected behavior:**

I'd expect `blank.md` to remain zero bytes in size, just as this happens for `blank.js` and `blank.ts`.

**Comment by ikatyang** [comment]
This one should be pretty easy, PRs welcome.

**Comment by huyvohcmc** [comment]
I would like to take this issue, thanks.

**Comment by lydell** [comment]
For quick experiments I usually run `./bin/prettier.js my-test-file.js` and look at the code printed to the console.

**Comment by ikatyang** [comment]
- add `your-test-case.md` to `tests/markdown_blahblah`
- `yarn test --watch markdown_blahblah`
- make some changes to `src/language-js/printer-markdown.js` and see if it's fixed

See [CONTRIBUTING.md](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md) for more info.

(There's no notification from edits so you probably have to send a new comment next time.)
