### ISSUE TITLE
Option Request: Multi-line formatting of object destructuring

### ISSUE THREAD

**Issue by tennisgent** [prettier/prettier#4384]
A recent change from https://github.com/prettier/prettier/pull/4267 resulted in an intentional change in how objects are destructured. I've been using prettier now for a long time and I love it. But I used to be able to do something like this:

**(edited by @duailibe)**

### Before
```javascript
const { match: { params: { id } } } = this.props  // 1 line
```
### After
```javascript
const { 
    match: { 
        params: { id }   // 5 lines
    } 
} = this.props
```

And there are a number of other places where this has caused a number of extra lines of code (that IMO are less readable). So I'm requesting that this change be given a config option so I can disable just this one rule. 

Thank you for your consideration, time and for putting such great work into prettier

**Comment by evilebottnawi** [comment]
:-1: on option
@tennisgent please provide example of code where you have less readable places

**Comment by j-f1** [comment]
How about only expanding the node onto multiple lines if:

- there are more than two keys in it that have children that are objects, OR
- one of its children has an object child that is expanded

**Comment by duailibe** [comment]
Hi @tennisgent, thanks for the report!

First of all, the `catch` one was unintended. For example, when in function arguments, we require one extra "level" in the hierarchy to break the destructuring, see [the example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQAUwAJgIYy1L7AC2cAzu7QOZwC+fAJTMAOlHz4A9JPyRqcMXzFiMWXAWJkIAJip0GTVhy69D7CGxgALHFG4Cho8VJlyFUPiAA0ICAAd1KHZkUFoAJzCIAHcABXCEYJRaADcIHGpvEAAjMNowAGs4GABlPzzbbmQYMPQ4H1t2ODCYGNzuFlpkVFoSRp8AK3YADwAhXIKi4to2ABlbOC6evpAysMaw5GzaLIBPcihMvzDbGAB1dOtkAA4ABh8jiEbT3L9No44m5IWfMLgAR3QOF+rR4HUWvTqIEaLBwVRqkPYFRIcAAiugIPBwcsGFlztRLkhtD5qrQcCQKgBhCxglBQaDfEDoRoAFW2iW6EIEQA) in the playground. So in your specific example, it should behave the same.

I appreciate your comment and I certainly prefer the previous behavior, but we won't be adding any options for that. Instead, I'd like to tweak our heuristics to print them better

**Comment by duailibe** [comment]
Oh the `handleClick` case is already printed correctly:

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqUAFMDAIYBOA5nDEvsAG7kA26cAvpwJSMA6UToMGQoAZxiEo+ALz5SFGnQbM2Hbn1kA+RpxAAaEBAAOuaOOSgqlCAHcAClQSWU5JhBwATQyABGlORgANZ0AMomQThQ1MgwlBxG0eJwlDAOgdQAtuTIqGwpRgBW4gAeAEKBIeHkWXAAMtFweQVwRpGUKZTI-uR+AJ6s0L4mlNEwAOreMAAWyAAcAAzttikTgSY9o3BdTM1GlHAAjug4hxnk2blI+ayFIClZOHEJbQ-R1KxwAIroEPAtO5vCh+KZeWbIABMRni5BwrA+AGEIFkcj0oNB9iB0CkACp9Vy3FLcIA)

**Input:**
```jsx
function fn({target: {value}}) {
}

const fn = ({target: {value}}) => {}
```

**Output:**
```jsx
function fn({ target: { value } }) {}

const fn = ({ target: { value } }) => {};

```

**Comment by duailibe** [comment]
@tennisgent I edited the OP to remove the outdated examples. If you have more, report back!
