### ISSUE TITLE
Update vim README to use setlocal

### ISSUE THREAD

**Issue by fingermark** [prettier/prettier#439]
Vim now supports setlocal on formatprg (which I requested just because of this plugin https://github.com/vim/vim/issues/1380).  Can we update the README:

```
- autocmd FileType javascript set formatprg=prettier\ --stdin
```

```
+ autocmd FileType javascript setlocal formatprg=prettier\ --stdin
```

Note that users with an old vim using setlocal will still have things work just as they did if they called `set formatprg`.  Also, this feature has not been released to MacVim yet, but will for their next release.

**Comment by vjeux** [comment]
Could you send a pull request instead of an issue, this way we could merge it if it is something we should do? Thanks!
