### ISSUE TITLE
Wrong indent when using an object as one of the operands for the trenary operator

### ISSUE THREAD

**Issue by eyal0803** [prettier/prettier#4391]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBXNcBOmAvDnvmgHS4EA6UmDjDA-JsHU55xT9eVWQA0HLqL5QAhgFs4SUgUp8KAGwgBzAJZRh9UVwkA3CTAn45fRWQqHjpgPrZ8ykXoC+LzubKWCIQSAgABxgNdGRQU3wIAHcABVMENGQQQwgNABM-EAAjfAkwAGs4GABlQPytNWQYfGw4fy0yGFi8tSkJZAAzCWU8fwArNAAPACE8wuKS6TgAGS04atr6kHLyXxRsiWyAT1UoLMD8LRgAdQyYAAtkAEYABlv-Q4g8E7zA5MO4MgMF-3w4ACO2A0-xaEjaHSQ3V6yzwUg0XR6fRAaEqyjgAEVsBB4Is6v4TNkzulLsgACwEvIaZSVADCECk7WSUGgvxA1AAKlsklCkXBXK4gA)
```sh
--jsx-bracket-same-line
--print-width 100
--no-semi
--single-quote
--tab-width 4
```

**Input:**
```jsx
const user = users.user
        ? {
              ...users.user,
              username: users.user.login,
              avatar: users.user.avatar_url
          }
        : users.user
```

**Output:**
```jsx
const user = users.user
    ? {
          ...users.user,
          username: users.user.login,
          avatar: users.user.avatar_url
      }
    : users.user

```

**Expected behavior:**
```jsx
const user = users.user
    ? {
        ...users.user,
        username: users.user.login,
        avatar: users.user.avatar_url
    }
    : users.user

```

**Comment by evilebottnawi** [comment]
@eyal0803 expected behavior, why you need save same indent `}` and `:`, it is ugly

**Comment by j-f1** [comment]
This is an intentional behavior added in #3745.

**Comment by eyal0803** [comment]
Thus far, every line Prettier has formatted for me has started on an indent break (4, 8, 12, ...). Why should this behavior differ when using the trenary operator?

@j-f1 , The issue you referenced uses `--use-tabs` while I don't.

**Comment by eyal0803** [comment]
From my understanding the main issue isn't fixed yet. I think that at least one of the issues (this one or #1271) should be reopened.
