### ISSUE TITLE
Get error name in output

### ISSUE THREAD

**Issue by Extarys** [prettier/prettier#4396]
**Prettier 1.12.1**

** Options **
```
module.exports = {
  root: true,
  extends: [
    'plugin:flowtype/recommended',
    'plugin:vue/recommended',
    'prettier',
    'prettier/flowtype',
  ],
  plugins: ['flowtype', 'vue', 'prettier'],

  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module',
    ecmaVersion: 6,
    ecmaFeatures: {
      unicodeCodePointEscapes: true,
      globalReturn: true,
      jsx: true,
    },
  },
  env: {
    browser: true,
    node: true,
    // commonjs: true,
    es6: true,
  },
  settings: {
    flowtype: {
      onlyFilesWithFlowAnnotation: false,
    },
  },
  rules: {
    // 'prettier/prettier': [
    //   'error',
    //   {
    //     singleQuote: true,
    //     trailingComma: 'all',
    //     bracketSpacing: false,
    //     jsxBracketSameLine: true,
    //     useTabs: true,
    //   },
    // ],
  },
};
```

I would like to see if the error is coming from ESlint, Flowtype or Prettier. Right now all I see is prettier.
At best, at least showing the error code name would help.
```
   5:1  error  Replace `··` with `↹`     prettier/prettier
   6:1  error  Replace `··` with `↹`     prettier/prettier
  10:1  error  Replace `··` with `↹`     prettier/prettier
  14:1  error  Replace `··` with `↹`     prettier/prettier
```

**Expected behavior:**

Having the error code like `no-tabs`, [ESLint rules](https://eslint.org/docs/rules/) would help a lot.
I may have missed it in some documentation, or maybe it's impossible?

**Comment by j-f1** [comment]
Do you have a `.prettierrc` and if so can you post it here?

**Comment by suchipi** [comment]
@Extarys you may find `eslint-config-prettier` useful: https://prettier.io/docs/en/eslint.html#turn-off-eslint-s-formatting-rules

**Comment by duailibe** [comment]
@Extarys I'm not sure I understand your problem.. we don't have errors names when using Prettier. We just reformat the code entirely. `eslint-plugin-prettier` compares the original to the reformatted code and prints what changed between them and show "kind of like" ESLint errors.

If using `eslint-plugin-prettier`, just run `eslint --fix` and ESLint/Prettier will reformat the code.

**Comment by Andreagar28** [comment]
Im having the same issue. No fix.
