### ISSUE TITLE
Separate proseWidth option

### ISSUE THREAD

**Issue by themadcreator** [prettier/prettier#4409]
Please consider separating the `printWidth` and `proseWidth` options. I would like wrap prose at 80 chars, but code at 120 chars.

### Reasoning
The note about [`printWidth`](https://prettier.io/docs/en/options.html#print-width) option makes an excellent point about readability. However, the 80 character line width is based on typical english prose, targeting 9-12 words per line.

Typical code, on the other hand, often has lengthy class names and extra syntax and coloring to help with readability. Wrapping _code_ at 80 chars often hampers readability due to few "words" per line.

**Comment by suchipi** [comment]
You can accomplish this partially with a [configuration override](https://prettier.io/docs/en/configuration.html#configuration-overrides) that sets printWidth to a different value for markdown, but I don't think it will properly handle inline code blocks in markdown documents.

@azz @ikatyang Am I forgetting something? Do we have a way to do configuration overrides in multiparser?

**Comment by duailibe** [comment]
We currently can't have a different `printWidth` for the code fences inside Markdown.

**Comment by suchipi** [comment]
Would anyone be opposed to detecting and using "catch-all" configuration overrides in the multiparser? So if the config override has `"files": "*.js"`, then we use that config override's options in multiparser when switching into JS. Likewise for other languages, based on extensions

**Comment by themadcreator** [comment]
@suchipi from my reading of the "overrides" documentation, this only allows you to change config _per file_, whereas im suggesting distinct width options within the same file.

For example, consider this code block:

```typescript
/**
 * Provides input terms to an `HomographicSolver` from a regular continued
 * fraction. The convergents of the regular continued fraction are provided an
 * `Iterator<number>` to this class.
 *
 * For example, the (possibly unbounded) convergents of the iterator
 *
 *     [b0, b1, b2, ...]
 *
 * represent a regular continued fraction x such that
 *
 *     x = b0 + 1 / (b1 + 1 / (b2 + ...))
 *
 * Given the homographic function:
 *
 *     a*x + b
 *     -------
 *     c*x + d
 *
 * an input of one term of the regular continued fraction transforms the state
 * matrix like so:
 *
 *     (a*x + b)*x + a
 *     ---------------
 *     (c*x + d)*x + d
 *
 */
export class RegularContinuedFractionHomographicInput
    implements IHomographicInput<number> {


}

**Comment by duailibe** [comment]
@themadcreator We assumed you were talking about Markdown when you talked about prose and the suggestion is to have different print width in the same file, but on different languages, e.g., CSS in JS, or code fences in Markdown, etc.

**Comment by themadcreator** [comment]
Oh i see! In that case i'll just set `printWidth` to 120 and wrap my comments to 80 manually. Thanks!
