### ISSUE TITLE
Lowercasing Postcss :export keys

### ISSUE THREAD

**Issue by ag-kylemh** [prettier/prettier#4410]
❤️  y'alls work

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASADgJwJYFsCGmAngMIQA2EmSABAMQBsDAzMwJxsDcAOlL0nAAe6KjBrBeNGljyEiAIRhQAYtBhlK1GhhwFiGqpxq8AviAA0ICOhjZoAZ2ShCmCAHcACoQSOU+AG4Q2AAmFiAARpj4YADWcDAAyujR2FAA5sgwmACucJap9nCYMB5RaQTIAGb45IWWAFb2gvJRsfEJ+LhwADKpcFU1dSDJmIWYyCD2YPaOljKwAOohMAAWyACMAAybc66FC1HoE1hwY-79lphwAI7Z2Fel+OX4A7V5k3C42Jk57-apaXIcAAitkIPBXkMYPhwktgqtkAAmSxZfDYcgAsi4CooKDQC4gbKFAAqMN81Telnw9hgkPewQgYDplgg2Rg6DZiLpJhMQA)

**Input:**
```scss
$primaryColor: #663399;

:export {
  primaryBtnFontColor: $primaryColor; 
}
```

**Output:**
```scss
$primaryColor: #663399;

:export {
  primarybtnfontcolor: $primaryColor; 
}
```

**Expected behavior:**
Should not be changing the key of my exported variable.

**Comment by lydell** [comment]
Hmm, I thought this was already fixed. See: #4110 

Also, I get different output on the playground?

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASADgJwJYFsCGmAngMIQA2EmSABAMQBsDAzMwJxsDcAOlL0nAAe6KjBrBeNGljyEiAIRhQAYtBhlK1GhhwFiGqpxq8AviAA0ICOhjZoAZ2ShCmCAHcACoQSOU+AG4Q2AAmFiAARpj4YADWcDAAyujR2FAA5sgwmACucJap9nCYMB5RaQTIAGb45IWWAFb2gvJRsfEJ+LhwADKpcFU1dSDJmIWYyCD2YPaOljKwAOohMAAWyACMAAybc66FC1HoE1hwY-79lphwAI7Z2Fel+OX4A7V5k3C42Jk57-apaXIcAAitkIPBXkMYPhwktgqtkAAmSxZfDYcgAsi4CooKDQC4gbKFAAqMN81Telnw9hgkPewQgYDplgg2Rg6DZiLpJhMQA)
```sh
--parser scss
--print-width 100
```

**Input:**
```scss
$primaryColor: #663399;

:export {
  primaryBtnFontColor: $primaryColor; 
}
```

**Output:**
```scss
$primaryColor: #663399;

:export {
  primaryBtnFontColor: $primaryColor;
}

```

Could it just be a caching thing? @ag-kylemh What if you hard-refresh the playground – does that change anything?

**Comment by ag-kylemh** [comment]
@lydell clearing cookies shows me the correct output. 👍
