### ISSUE TITLE
Formatting */ /** breaks output

### ISSUE THREAD

**Issue by lexs** [prettier/prettier#4412]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBhA8gOXwFFsAVASQIH0BlUgQVIFUbMBeTOADwAcIAnGGgB0eQiQrU6jFu0zAAOlEw4AMrhpEAIkky4ARgCs4YGMIBm-OHABecABTBMAawCWUACa6A5NnWatb0wAXwBKABolFTFiMm1dA2NTCytbByc3Tx8YiW0gsMjlHAJYinwAcQSjEzNLaztHF3cvTF8SiXIK-IiozHxcUiocuJ09auS6tMbMlu9+weHSPJDQkIBuJU2oAHoAKl3elSPjk9Oz84vL093MekwYAE8eOHuACwBDLDB35X0XgHd+K4YPBlDAIJh3ph9ABXczmOD8YSHK6otHoi67baYPYHIoYgmEgk3LRwNBgIF-NBvF6QKBQGquaCYDCfGHUiDmSGYABKcHeplcADc4DQIGBnHAYNstDCeAAbbjYaAMwXQZH4ola7XXTAAWj6AyG7RGuigELpqpgTOUZJg7308tcaFecA8mAEmGenncAHMNTrA0GbgbFp1Kph-q7lAADS01eyhGOYD7Uv4ITDfeWK92wrBQ+Nq5TOzDmrAPKUooPVjE3FR2h1Ol1ugM1tvokPFcSmyPR7mF63MksNx3O10eVvtqeY-VqDTxXsZmCuzMqxnM1PQ6y23hOsDA+UPTPyiBoN2YIWuKFxk9nxMxyfTp-HTtEHk83A83RRpcrgc2lN3jTbdj1Pc9zE9H4jwgZdEUwKwgPVKtnyfLEcX2ZCUJQm47jpGB+AFLAeH4CBLw8P1MHI+FEQQLB3HgAii0wABbCAPDgeVqWefgaUwABtPlCOFUVxUlIiSKUcFIHlABdTCsKfexXhBHg0CQbZtl9YFXhhfRhEgZjtkEwURTFCUpW2BCTLJUSLMdCB9G2ZigIY7YAAUSKkiB5WEZiPFCR8FOw7FcXkoLnxwlk-UVTAYSgYEPS5DxPihbgwA+KBfXPP4YH+EDYK9ax+A5Llr2M61TNsmAHzC8LpyxLYQHCEAIB4QcoDQZBQHefgSP+NyeoQTqUHeIUIFcDwmpAfRGLEmgeAFP1kHwmE4Ga9wz0EDz3l9ZzkHMd5OLWkBDDQLgACFZqlGh3mYuBVHcOB9sOs9moW4rEWQaaHQeE8oCm4j6IAdQm5dkAADgABjekizyBgieC+4iyUREUpqsABHGFXCsbbdveZ6juas9mNcZb+FW4norgABFGEYKepADqJkB7X0EGPDBpAACZmvw95XCdTLlWYvaUHNBkpvZOBSAdYbmdekAXMJxWPHFFXjogGEYB4bXufJ1bgmCIA)

**Input:**
```jsx
const CONNECTION_STATUS = exports.CONNECTION_STATUS = {
  CLOSED: Object.freeze({ kind: 'CLOSED' }),
  CONNECTED: Object.freeze({ kind: 'CONNECTED' }),
  CONNECTING: Object.freeze({ kind: 'CONNECTING' }),
  NOT_CONNECTED: Object.freeze({ kind: 'NOT_CONNECTED' }) };


/**
                                                              * A type that can be written to a buffer.
                                                              */ /**
                                                                  * Describes the connection status of a ReactiveSocket/DuplexConnection.
                                                                  * - NOT_CONNECTED: no connection established or pending.
                                                                  * - CONNECTING: when `connect()` has been called but a connection is not yet
                                                                  *   established.
                                                                  * - CONNECTED: when a connection is established.
                                                                  * - CLOSED: when the connection has been explicitly closed via `close()`.
                                                                  * - ERROR: when the connection has been closed for any other reason.
                                                                  */ /**
                                                                      * A contract providing different interaction models per the [ReactiveSocket pro
tocol]
                                                                      (https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md).
                                                                      */ /**
                                                                          * A single unit of data exchanged between the peers of a `ReactiveSocket`.
                                                                          */


```

**Output:**
```jsx
const CONNECTION_STATUS = (exports.CONNECTION_STATUS = {
  CLOSED: Object.freeze({ kind: "CLOSED" }),
  CONNECTED: Object.freeze({ kind: "CONNECTED" }),
  CONNECTING: Object.freeze({ kind: "CONNECTING" }),
  NOT_CONNECTED: Object.freeze({ kind: "NOT_CONNECTED" })
}); /**

/**
 * A type that can be written to a buffer.
 */
 * Describes the connection status of a ReactiveSocket/DuplexConnection.
 * - NOT_CONNECTED: no connection established or pending.
 * - CONNECTING: when `connect()` has been called but a connection is not yet
 *   established.
 * - CONNECTED: when a connection is established.
 * - CLOSED: when the connection has been explicitly closed via `close()`.
 * - ERROR: when the connection has been closed for any other reason.
 */ /**
                                                                      * A contract providing different interaction models per the [ReactiveSocket pro
tocol]
                                                                      (https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md).
                                                                      */ /**
 * A single unit of data exchanged between the peers of a `ReactiveSocket`.
 */

```

**Expected behavior:**

Valid Javascript outputted.

**Comment by lydell** [comment]
Minimal example:

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA3AHSgegFR4757aEgA0IEADjAJbQDOyoqATmxAO4AK7CzFKgBuEOgBMKIAEZtUYANZwYAZWry6UAObIYbAK5xKmxnDYwecrQFtUyAGaoANqcoArRgA8AQnMXKVVGs4ABlNOAdnVxB1NlM2ZBlUaQBPJ2gpajZNGAB1CRgAC2QADgAGSiyIU1y5akSsuHjhCMo2OABHfTp2y1QbOyRHFyMQU2s6XQNRxk0tJzgARX0IeEiRyhhk-PEi5AAmTbk6JzmAYQhrW0SoaFaQfVMAFWTBYejURhh16PEIMB+owg+hg1BB+ymhgAvlCgA)

**Input:**
```jsx
a;
/**//**
*/
```

**Output:**
```jsx
a; /**
/**/
 */

```

**Second Output:**
```jsx
SyntaxError: Unexpected token (3:2)
  1 | a; /**
  2 | /**/
> 3 |  */
    |  ^
  4 | 
```

**Comment by duailibe** [comment]
This was fun to track down! It happens because we print the first comment with a `lineSuffix` which buffers the comment until it finds a `hardline`. Now since the 2nd comment is a JSDoc, we print each line with a `hardline` at the end. So what happens is:
- prints the node;
- buffers the trailing comment `/**/`;
- prints the 1st line of the JSDoc `/**`;
- now we print the trailing comment;
- print the rest of the JSDoc

I'm not sure yet what the fix is, currently working on it
