### ISSUE TITLE
Problem with bind long name method in constructor

### ISSUE THREAD

**Issue by tomasztomys** [prettier/prettier#4417]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgBo7AA6UOOkUmMATgK5gwTUAUAlISWWTABYCWmAHTwqAGWgBzAHLoAtnACycXhAAmAQSiqAyhHm8+UCQFFUmOKPSoMGHAF4cSJAaEiY4ozPlKVGrbv1+I1NzS2srdABuThwAXxiYtw9pOUVlHjVNHT10wxMzCysbdDYOUi5qZVpqUhpaOGjy+KhYkAAaEAgABxg+aExkUHRqaggAdwAFYYQBlHQANwg+VXaQACNqdDAAa2VtLq285Dq4DsNzahgJzYlZdGQAMytzDoArTAAPACFNnb3U0SGOCPZ6nEAHagXZDrdBrACeqGgqy61EMMAA6steMgABwABg6KIg5nRmy60JRcAu82BHUqAEdaHxKtd0Ld7kgngUOuZZHxjnQwZg8qg4ABFWgQeAg7kgGCwzGqbFIABMHRo6D4qDyAGE9HdoVBoLSQLRzAAVWGzLnmWKxIA)

**Input:**
```jsx
class X {
  constructor() {
    this.testLongNameMethodAndSomethingElseLallala = ::this.testLongNameMethodAndSomethingElseLallala;
  }
  
  testLongNameMethodAndSomethingElseLallala() {
    return true;
  }
}
```

**Output:**
```jsx
class X {
  constructor() {
    this.testLongNameMethodAndSomethingElseLallala = ::this
      .testLongNameMethodAndSomethingElseLallala;
  }

  testLongNameMethodAndSomethingElseLallala() {
    return true;
  }
}

```

**Expected behavior:**
```jsx
class X {
  constructor() {
    this.testLongNameMethodAndSomethingElseLallala = 
      ::this.testLongNameMethodAndSomethingElseLallala;
  }

  testLongNameMethodAndSomethingElseLallala() {
    return true;
  }
}

```
or

```jsx
class X {
  constructor() {
    this.testLongNameMethodAndSomethingElseLallala = ::this.testLongNameMethodAndSomethingElseLallala;
  }

  testLongNameMethodAndSomethingElseLallala() {
    return true;
  }
}

```

**Comment by misoguy** [comment]
I'd like to try this if no one is on it

**Comment by j-f1** [comment]
Go ahead!
