### ISSUE TITLE
Support styled-components Foo.extend.attrs()``

### ISSUE THREAD

**Issue by sonaye** [prettier/prettier#4427]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBBTBeTDATwBs4ATAOnIEsA3AAwB0oAzMgDyUwEYXmoLSFAyYAQvkIxSFavUoBDGDABOaABQBKAezhde-FkPRYAwpOyU98KOR2dufKAOMisAEQtWONqktUa2iy6+k4MIAA0IBAADjA06MigCioqEADuAAopCGjIIAp0EDTkkSAARioKYADWcDAAyjHVNFAA5siqAK5wUa1ocCowmVVtALYKyKwKJANRAFZoHGJVtfUNCmNwADKtcFMzcyDNaoP55QrlpNBlMSqtMADqJTAAFsgAHAAMUXcQA48qjF8nc4AMVHR9lEVHAAI5dGgwkYKcaTJDTWa9EADMY0ToqHpRNCtNpkACKXQg8AOmKiMEuz3Ib2QACY6VUaCQSaYIGMJvkoNAoSAugMACqXPLow5wAC+sqAA)

**Input:**
```jsx
const A = styled.div`
flex: 1
`

const B = styled.div.attrs()`
flex: 1
`

const C = A.extend`
flex: 1
`

const D = A.extend.attrs()`
flex: 1
`
```

**Output:**
```jsx
// ✅
const A = styled.div`
  flex: 1;
`;

// ✅
const B = styled.div.attrs()`
  flex: 1;
`;

// ✅
const C = A.extend`
  flex: 1;
`;

// ❌, not detected
const D = A.extend.attrs()`
flex: 1
`;
```

**Comment by evilebottnawi** [comment]
Should be easy to fix
