### ISSUE TITLE
Startup time performance investigation

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#443]
In order to figure out how to make it faster, I wanted to see how it looked like right now.

## Node startup time

Doing nothing with node takes ~40ms. So no matter what we do, we'll never be able to get below 40ms.

```bash
time node -e ''
real	0m0.043s
```

## Prettier startup time

Pretty printing an empty file with prettier takes ~150ms. This includes loading all the JavaScript and parsing/generating IR/printing nothing... :p

```bash
time echo '' | ./prettier.js --stdin > /dev/null
real	0m0.153s
```

## Printing a 2k lines file

It takes ~420ms to print a 2.5k lines file.

```bash
time ./prettier.js ../src/printer.js > /dev/null
real	0m0.425s
```

## `npm run` time

`npm run` startup time is ~380ms. This means that you consistently pay the overhead just for the fancy alias.

```bash
"scripts": {
    "donothing": "true",
```

```bash
time npm run donothing > /dev/null
real	0m0.383s
```

## `yarn run` time

`yarn run` startup time is ~240ms. This is better (even though it's still super slow).

```bash
time yarn run donothing > /dev/null
real	0m0.246s
```

# Conclusion

If we want a snappy experience inside of the editor, we'll likely want to load the JavaScript code once and then use it multiple times. We absolutely don't want to do `npm run prettier` on every save otherwise we'd have to pay for **half a second** (380ms + 150ms = 530ms) every single time!

**Comment by jlongster** [comment]
Luckily we don't encourage using npm or yarn in production, people just use the prettier CLI.

Atom gets the benefit of already being in JS, so it loads the module once and will reuse it.

For other editors, we do re-execute the script every single time. For smaller files it's acceptable, but if we want to fix this, we'd need to start a "server" or something that can persist across executions.

I'm curious how much the 420ms for a 2k lines file goes down after JIT. You'd have to write a custom script for that which runs it multiple times.

**Comment by johann-sonntagbauer** [comment]
do you know if V8 code caching is already available in nodejs. Prettier would benefit from that quite a bit
https://v8project.blogspot.co.at/2015/07/code-caching.html

**Comment by lydell** [comment]
Could `require`ing some modules when they are needed instead of up-front help? For example, babel-code-frame isn't needed until a parse error is thrown, which won't even happen every time you prettify a file.

**Comment by johann-sonntagbauer** [comment]
ok no luck with the code caching. It seems node does already use precompiled caches. First executions of prettier are ~30% slower than repetitive executions. Also different v8 options don't take any effect. Only disabling lazy compilation showed some minor improvements.

**Comment by marvinhagemeister** [comment]
@vjeux Great findings. I'm surprised that both `yarn run` and `npm run` are that slow :S

**Comment by johann-sonntagbauer** [comment]
@marvinhagemeister they have to do a lot of stuff to build up the configuration.
Would be cool to have a fastpath of the setup to only execute scripts

**Comment by vjeux** [comment]
@lydell I'm already doing this for the parser, but we should probably investigate for more things!

**Comment by fhinkel** [comment]
Maybe, instead of turning off lazy parsing everywhere, it would help to target specific functions with iffe wrapping? [This discussions](https://bugs.chromium.org/p/v8/issues/detail?id=5702) has a bit more information on that. `--trace-preparse` and `--trace-parse` might shed some light.

Code caching only works for top-level code. That might be why it doesn't have a performance impact. 

I think Node 7 with V8 5.4 does not have ignition (interpreter) enabled by default. Can you try `--ignition` or `--ignition-staging`?

**Comment by johann-sonntagbauer** [comment]
```bash
time node ./prettier.js ../src/printer.js > /dev/null
real	0m0.623s
````

### with `--ignition-staging`
```bash
time node --ignition-staging ./prettier.js ../src/printer.js > /dev/null
real	0m1.071s
````

### with `--ignition`
```bash
time node --ignition ./prettier.js ../src/printer.js > /dev/null
real	0m0.890s
````

not the fastes machine :P 
I tried to generate a bundle of all required js files just to get a feeling about the size. The resulting bundle was 1.2 MB in size. Maybe minifying the code could help with the parse time.

`--trace-parse` no big surprises as far as I can tell, only lots of small scripts and functions which add up.

**Comment by vjeux** [comment]
In `src/parser.js`, you should comment out the flow-parser require, it's really big and we don't use it by default.

**Comment by johann-sonntagbauer** [comment]
V8 does already a good job here. After removing the flow parser the timings do not change at all. Median is 3ms faster.

**Comment by johann-sonntagbauer** [comment]
found an interessting project which caches the node_module locations. https://github.com/wix/fast-boot
median went down from 625ms to 600ms
worth further investigation :)

**Comment by johann-sonntagbauer** [comment]
a list of time spent per require
```
  1 [167]  ../index (..\index.js)                                                              94ms  ■■■■■■■■■■■■■■■■■■■ 19%
  2 [125]  ./src/comments (..\src\comments.js)                                                 55ms  ■■■■■■■■■■■ 11%
  3 [119]  ast-types (..\node_modules\ast-types\main.js)                                       52ms  ■■■■■■■■■■■ 10%
  4  [47]  glob (..\node_modules\glob\glob.js)                                                 19ms  ■■■■ 4%
  5  [63]  babel-code-frame (..\node_modules\babel-code-frame\lib\index.js)                    15ms  ■■■ 3%
  6 [168]  babylon (..\node_modules\babylon\lib\index.js)                                      14ms  ■■■ 3%
  7 [164]  ./src/options (..\src\options.js)                                                   14ms  ■■■ 3%
  8 [162]  jest-validate (..\node_modules\jest-validate\build\index.js)                        13ms  ■■■ 3%
  9  [62]  chalk (..\node_modules\chalk\index.js)                                               8ms  ■■ 2%
 10  [20]  minimatch (..\node_modules\minimatch\minimatch.js)                                   6ms  ■■ 1%
 11 [161]  ./validate (..\node_modules\jest-validate\build\validate.js)                         6ms  ■■ 1%
 12   [7]  chalk (..\node_modules\time-require\node_modules\chalk\index.js)                     6ms  ■■ 1%
 13 [138]  ./src/printer (..\src\printer.js)                                                    5ms  ■ 1%
 14 [148]  ./errors (..\node_modules\jest-validate\build\errors.js)                             5ms  ■ 1%
 15  [54]  esutils (..\node_modules\esutils\lib\utils.js)                                       5ms  ■ 1%
 16  [19]  brace-expansion (..\node_modules\brace-expansion\index.js)                           4ms  ■ 1%
 17   [3]  pretty-ms (..\node_modules\pretty-ms\index.js)                                       4ms  ■ 1%
 18 [160]  ./defaultConfig (..\node_modules\jest-validate\build\defaultConfig.js)               4ms  ■ 1%
 19 [147]  jest-matcher-utils (..\node_modules\jest-matcher-utils\build\index.js)               4ms  ■ 1%
 20  [44]  inflight (..\node_modules\inflight\inflight.js)                                      3ms  ■ 1%
 21  [48]  minimist (..\node_modules\minimist\index.js)                                         3ms  ■ 1%
 22  [39]  ./sync.js (..\node_modules\glob\sync.js)                                             3ms  ■ 1%
 23  [15]  fs.realpath (..\node_modules\fs.realpath\index.js)                                   3ms  ■ 1%
 24   [9]  get-stdin (..\node_modules\get-stdin\index.js)                                       3ms  ■ 1%

```

**Comment by johann-sonntagbauer** [comment]
First results from bundling the code. 
minified bundle size ~500k
overall median time went down from 625ms to 570ms

**Comment by vjeux** [comment]
This is not very actionable, I'm closing this issue.
