### ISSUE TITLE
Inconsistent formatting with matrices

### ISSUE THREAD

**Issue by saadq** [prettier/prettier#4432]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEMCGAjAGzkwF5MAnOARwFcBLSgCgHJ4APGAWl0LmYEoAOlGFEsEGjAAOk4cInTJpbPiKNhmTAG0Nm7czxw4U5gBpMzAIwAGAEwAWZgF1zuzVoMQIJ88wDMfvYArNbOrlB6+gBmXmYWNtYAbGGYbvp4OORxzMFhaR4xEM66LrrAmDgEdADmUEj6AHTOmAC+wkIiUAoyWGQ8aro6EXoehsbZNg4p+Z7e2QHBoS6pw+7MhRPWSdOr6ZnZuU4lpmUVVbX1Hk1Ore3CIKYg3jB06MigmeQQAO4ACpkINDIEA4ABuEDoABMHiA8OQcGAANZwGAAZSkCLoUGqyBg5BocEeWLQcHIMF+8OqAFscMgopUSY8AFZoNgAIXhSJRqJwVLgABksXA6QzCSAMeQSeRgRk8ABPAjQGFSchYmAAdShMAAFsgABzWR4qiAk9XwqTAlVwKWg4WPSi0BhwCk4am0pD0giMkAkql0XH4sVoLHVIgARRoEHgIq9Yp4mshOuQtkeeJwdCq2IAwhAqTTgV0oHaQDQSQAVfBAj2ilotIA)

**Input:**
```jsx
const table = require('text-table')

let output

output = table(
  [
    ['beep', '1024'], 
    ['boop', '33450'], 
    ['foo', '1006'], 
    ['bar', '45'],
    ['foo']
  ],
  { align: ['.'] }
)

output = table(
  [
    ['beep', '1024'], 
    ['boop', '33450'], 
    ['foo', '1006'], 
    ['bar', '45']
  ],
  { align: ['.'] }
)

```

**Output:**
```jsx
const table = require("text-table");

let output;

output = table(
  [
    ["beep", "1024"],
    ["boop", "33450"],
    ["foo", "1006"],
    ["bar", "45"],
    ["foo"]
  ],
  { align: ["."] }
);

output = table(
  [["beep", "1024"], ["boop", "33450"], ["foo", "1006"], ["bar", "45"]],
  { align: ["."] }
);

```

**Expected behavior:**
In both calls to `table()`, I am passing the exact same arguments with one difference – the first matrix has a `['foo']` at the end which gives the nice output but when that `foo` array is removed in the second matrix you can see that the formatting becomes weird. I would expect both cases to use the formatting from the first case.

**Comment by k15a** [comment]
This is because prettier can't fit the matrix with the foo into your maximum line length and therefore needs to break it into multiple lines. You can use a `// prettier-ignore`. Otherwise I am not sure how prettier can do better in this case.

**Comment by saadq** [comment]
Ah, I see. I assumed that the single-line output would not be desirable in any case, but if this is expected behavior I suppose you can close this.
