### ISSUE TITLE
Prettier strips flow comments when saving

### ISSUE THREAD

**Issue by bgdavidx** [prettier/prettier#4433]
**Prettier 1.12.1**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVEpAdKBLAWwAcIAnGAAhgE8i4KAjAGwEMALCgM1IgIoHIAdKmbt+udKhAAaEBCIw80AM7JQLUjwDuABQ0JVKFky0tqq2Q1IswAazgwAykRt4oAc2QxSAVziy3ZThyHWt3AhZkTmMg2QArZQAPACFrOwdHFgI4ABk3OC9ffxAXUiDSZBBOJggtGRKeIIB1ayJKolI4coA3AtlOgEcfPE7QlnDIpGimWJAggjwomOLlN3cmOABFHwh4Qr9ZGBYGJrwAExg2ZAAmQ+s8JjWAYV4IyuMmep8ggBVjw2msw6bhgpwuVyQAEYAAzQgC+cKAA
```sh
# Options (if any):
{
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": true,
  "jsxBracketSameLine": true,
  "semi": false,
  "parser": "flow"
}

```

**Input:**

```
/*::
import type blah from './blah'
*/
```

**Output:**
```
import type blah from './blah'
```

**Expected behavior:**
It should not remove the wrapping comment.

**Comment by j-f1** [comment]
In the meantime, you should be able to switch to the Babylon parser (it’s the default for JS files), which supports Flow types as well.

**Comment by duailibe** [comment]
Thanks for the report @bgdavidx. A quick search for "flow comments" gives me #3493. Closing this as duplicate.
