### ISSUE TITLE
Option Request: configurable empty multiple lines

### ISSUE THREAD

**Issue by manuel-di-iorio** [prettier/prettier#4439]
I'm using prettier alongside eslint which the airbnb style rule: `"no-multiple-empty-lines": ["error", { "max": 2 }]`

Due to prettier, unfortunally this:

```js
a = 1


b = 2
```

Becomes:

```js
a = 1

b = 2
```
As I said in the prettier-eslint issue (https://github.com/prettier/prettier-eslint/issues/176), opinionated behavior should only be the default and always should be configurable, to allow maximum flexibility of this awesome tool.

Ref: https://github.com/prettier/prettier/issues/1613

There are already some options in prettier, but this is missing unless it's not documented: https://prettier.io/docs/en/options.html

**Comment by kachkaev** [comment]
It is unlikely that this option will be added @manuel-di-iorio. See [Prettier's option philosophy](https://prettier.io/docs/en/option-philosophy.html).

**Comment by manuel-di-iorio** [comment]
Excume sir but the option philosophy is inconsistent, if there are already 15 options, why to extend it to cover all formatting behaviors 🤔

**Comment by kachkaev** [comment]
Each of the Prettier options would not exist if could be avoided. They either have a legacy background or a very long community debate (e.g. https://github.com/prettier/prettier/issues/812).

What you are proposing is a purely stylistic ‘enhancement’, which can be easily avoided.

> By far the biggest reason for adopting Prettier is to stop all the on-going debates over styles.
