### ISSUE TITLE
Empty JSON/graphql file throws error

### ISSUE THREAD

**Issue by azz** [prettier/prettier#4448]
If a JSON file is empty or just has whitespace, Prettier throws an error. I think we should just output an empty file in this case. This issue causes https://github.com/azz/pretty-quick/issues/28.

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACEAaEEAOMCW0AzsqAIYBOFEA7gAqUIkpkBuE+AJpiAEYVkwAazgwAyjkH4oAc2QwKAVzhZpROBRh0BMgLZlkAMzIAbdVgBWRAB4AhAcNFiyuuABlpcI6fMhJFdQpkECtoHhwKaRgAdS4YAAtkAA4ABiwIiHVogRxgiLhA1i8sCjgAR0V8Uu0yPQMkYzMVEHVdfHklZqJpGRM4AEVFCHhvJqwYMl5YzgTkACZxgXwTHoBhCF19YKhoYpBFdQAVSeZG9QBfc6A)
```sh
--parser json
```

**Input:**
```json
 
```

**Output:**
```json
SyntaxError: Unexpected token (1:2)
> 1 |  
    |  ^
```

**Comment by lipis** [comment]
What about other empty file types?

**Comment by azz** [comment]
I thought all the other would be fine (empty file is already ok), but looks like `graphql` fails too.

**Comment by ad1992** [comment]
@azz @lipis the graphql empty file error is due to the parse of graphql .
```js
  const parser = require("graphql/language");
  parser.parse("");
```
This gives `GraphQLError: Syntax Error: Unexpected <EOF>`
Can be veriffied here as well https://graphql.github.io/swapi-graphql/?
