### ISSUE TITLE
Making parser or printer async

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#4459]
This is a feature request, which may be useful for plugins that delegate parsing or compiling to an external processes. I can recall at least `prettier-plugin-ruby` (see [its parser.js](https://github.com/iamsolankiamit/prettier-ruby/blob/04de15a45869ce6ea7cfaac29ecda34ab15ccef7/src/parser.js#L7-L11)) and `prettier-plugin-elm` ([parser.js](https://github.com/gicentre/prettier-plugin-elm/blob/1a15233d580a68d49dbf1ab4455863e0f9cc74dc/src/parser.js#L6-L11)) that do this.

At the moment, when Prettier is given a markdown file, the code blocks in it are parsed and printed sequentially, which means that each third-party process is spawned one after another. This can quickly slow things down and make _Format on save_ feel quite glitchy (2-3 seconds of wait time when there are 10-20 code blocks is a bit too much). It would be great if the plugins' `parse()` or `print()` methods could return promises and thus allow Prettier to process more than one fenced code block in parallel (e.g. in a queue).

How feasible this internal change would be? What are the downsides? Is there any possible gain in calling standard JavaScript parsers and printers asynchronously too (e.g. to do block parsing in workers)?

Curious to know what you guys think!

**Comment by kachkaev** [comment]
Meanwhile, to speed-up `prettier-plugin-elm`, I introduced caching in v0.3.0 of this plugin. You can find its implementation in [src/cache.js](https://github.com/gicentre/prettier-plugin-elm/blob/master/src/cache.js). 

Caching uses [_Last Recently Used_ principle](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)). It stores the most recent `elm-format` results in a temp folder and thus makes `parse()` for an previously processed Elm code chunk much quicker. Older results are automatically garbage-collected, which prevents cache from going too large on disk.

Using caching in [gicentre/litvis](https://github.com/gicentre/litvis) (where there are lots of markdown files with Elm code blocks) has given a pretty positive performance boost. A ‘cold run’ of `yarn format` on my laptop takes about 23 seconds, while the following passes finish in only 6-8 seconds. In practice, formatting a markdown file that has multiple Elm code blocks becomes noticeably quicker too. That's because usually at most one Elm code block is changed between saves and so cache is successfully matched for most of the blocks. No more waiting for 2-3 seconds on each save!

If anyone is interested in caching `parse()` results in another Prettier plugin, I'm happy to extract the algorithm into an npm module.

**Comment by suchipi** [comment]
I'm on board

**Comment by GordonSmith** [comment]
Just a "me too" I have a JS lib which extracts meta information for my domain specific language, but it returns a Promise...

**Comment by j-f1** [comment]
@GordonSmith I know this isn’t an optimal solution, but you could `execSync` a new instance of Node that runs the async code.

**Comment by GordonSmith** [comment]
@j-f1  ...pleh (mind you I am sure I have done worse in the past...)

**Comment by thorn0** [comment]
More reasons for Prettier's API to become async: #7799
If we do this, will this be a breaking change, or will we support both sync and async plugins?

**Comment by kachkaev** [comment]
It's probably possible to support both sync and async plugins – we just call the plugin's method and check if it returns a promise or not. What's more challenging is that some Prettier methods will have to become sync, which will be breaking for editor extension authors.

**Comment by fisker** [comment]
I thought about this today.

 Let `prettier.format()` return string(if sync parser), a Promise with `toString: () => thow Error()`(if async parser), if he didn't check `isPromise()`, it will be a error. 😄

**Comment by fisker** [comment]
Tried to make the babel parser async #8263 🚶

**Comment by joelspadin** [comment]
I have another use case for asynchronous parsing. I'd like to be able to make a plugin that uses an existing tree-sitter parser with https://www.npmjs.com/package/web-tree-sitter, however the parser initialization is async.

https://github.com/tree-sitter/node-tree-sitter is an alternative that can be used synchronously, but it's more difficult to use since it has to compile the parser on NPM install instead of using a precompiled WASM file.

**Comment by ianks** [comment]
I have one too, I managed to speed up prettier ruby by an order of magnitude by running a server for parsing, unfortunately as of now I have to use `socat` to shell the results out since node sockets are async.

**Comment by fisker** [comment]
Let's do this

**Comment by hosseinmd** [comment]
Node JS have new thread worker for use in other cores of CPU.

Have we a way to work on other thread?

For plugins, we need async parser.

**Comment by fisker** [comment]
Maybe it's easier to maintain, if we just make everything async, let's remove all the sync version?

- `clearConfigCache` -> async version
- `formatWithCursor` -> async version
- `format` -> async version
- `check` -> async version
- remove `resolveConfig.sync`
- remove `resolveConfigFile.sync`

**Comment by bakkot** [comment]
I don't think it's a good idea to drop support for the sync version; a lot of other utilities depend on it. Instead, you can do what [babel did](https://github.com/babel/babel/pull/10507) and use [this library](https://github.com/loganfsmyth/gensync) to provide both sync and async versions.

**Comment by fisker** [comment]
There is no way to `import()` plugin in sync version.

So even if we want to maintain a sync version, it can't do

- Support plugin in ES Module.
- Support `prettier.config.mjs` and `prettier.config.js`(in ESM).

They will have to behave differently.

**Comment by bakkot** [comment]
It's fine to say that certain features are only available in the async version.

**Comment by fisker** [comment]
//cc @prettier/core Thoughts? https://github.com/prettier/prettier/issues/4459#issuecomment-982661922

**Comment by JounQin** [comment]
For anyone maybe interested, [`synckit`](https://github.com/rx-ts/synckit) is much more suitable to make async tasks to synchronously then `child_process`.

**Comment by fisker** [comment]
I think we'll just simply make everything asynchronous in V3. https://github.com/prettier/prettier/issues/4459#issuecomment-982661922

If someone want a sync version, they can use `worker_threads` or web worker. (Or maybe we can implement this future as a separate package later.)

**Comment by kachkaev** [comment]
I’ve added this issue and https://github.com/prettier/prettier/pull/12574 to [3.0 milestone](https://github.com/prettier/prettier/milestone/14), but feel free to remove it if we can’t make this change happen till then. Making core API async opens nice opportunities, but does not break existing plugins.

**Comment by fisker** [comment]
I just realized that our [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier) have to use synchronously.
I guess we'll have to  implement sync version.

//cc @BPScott

**Comment by JounQin** [comment]
@fisker It can use [`synckit`](https://github.com/rx-ts/synckit) like [`eslint-mdx`](https://github.com/mdx-js/eslint-mdx/blob/master/packages/eslint-mdx/src/worker.ts#L143)

**Comment by fisker** [comment]
@JounQin Yes, but maybe stylelint plugin need that too, so instead of asking them to implement, maybe we can do it for them.

**Comment by bakkot** [comment]
I continue to advocate for the use of [gensync](https://github.com/loganfsmyth/gensync) to support both async and sync versions, as babel does, which completely avoid this problem for that plugin and for any other tools which need to use prettier synchronously. It's not hard. It's not any harder than rewriting it to be completely async.

I wrote [a whole essay about this](https://writing.bakkot.com/gensync).

**Comment by fisker** [comment]
@bakkot Thank you for your advice, I did try gensync after you mentioned last time. It's handy to write function have both async and sync version. But I think it's hard to maintain. Also the code seems not easy to understand, it's like reading `yield*` as `await`.

FYI: I even send a [PR](https://github.com/sindresorhus/globby/pull/232) to `globby`.

**Comment by BPScott** [comment]
> You don't force changing plugins to asynchronous if you don't need. Your sync plugin can work with v3.

Yeah for sure if the sync APIs continue to exist. It sounds like part of the discussion here is "what if prettier went async only and remove the sync API".

**Comment by fisker** [comment]
Fixed in #13104

**Comment by hosseinmd** [comment]
Is esm plugins supported?

**Comment by fisker** [comment]
> Is esm plugins supported?

Soon.
