### ISSUE TITLE
CSS attribute selectors are printed with single quotes

### ISSUE THREAD

**Issue by filipmandaric** [prettier/prettier#4464]
Prettier is transforming this:
```css
input[type="radio"] {
}
```
into this:
```css
input[type='radio'] {
}
```
If attribute values are always escaped with double quotes within HTML, then double quotes should also be used when escaping them within CSS code.

**Comment by lydell** [comment]
The CSS printing obeys the [single-quote option](https://prettier.io/docs/en/options.html#quotes).

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLKAHArjA2jATwzgF4AdEAJwEMATVCCgXQAJgyoBfEAGhAgwwGUAM7JQ1SpQgB3AAqSEYlNQBuEVLV4gARjTABrODADKGamHQBzZDEpY4fdCLiUYcmlYC21ZADNqABsXPgArEQAPACF9I1NqLzgAGXQ4fyCQkHNKF0pkcBExPgxKdBgAdU0YAAtkAA4ABmLpF3KaDHySuFzVNL5KOABHLFQBj2pvXyQA4McQFy9UW3s5kWtAuABFLAh4dNm+GGodStoa5AAmQ5pUQOsAYQgvH3yoaD6QLBcAFWPlGZcnE4QA)
```sh
--parser css
```

**Input:**
```css
input[type="radio"] {
}
```

**Output:**
```css
input[type="radio"] {
}

```

vs

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLKAHArjA2jATwzgF4AdEAJwEMATVCCgXQAJgyoBfEAGhAgwwGUAM7JQ1SpQgB3AAqSEYlNQBuEVLV4gARjTABrODADKGamHQBzZDEpY4fdCLiUYcmlYC21ZADNqABsXPgArEQAPACF9I1NqLzgAGXQ4fyCQkHNKF0pkcBExPgxKdBgAdU0YAAtkAA4ABmLpF3KaDHySuFzVNL5KOABHLFQBj2pvXyQA4McQFy9UW3s5kWtAuABFLAh4ZYc+GGodStoa5AAmQ5pUQOsAYQgvH3yoaD6QLBcAFWPlGZcnE4QA)
```sh
--parser css
--single-quote
```

**Input:**
```css
input[type="radio"] {
}
```

**Output:**
```css
input[type='radio'] {
}

```

You can set single-quote based on file type using [config file overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides).

**Comment by filipmandaric** [comment]
@lydell 

What I'm trying to say is that it might be good to do one of the following:
(a) Ignore the single-quote option on HTML concepts throughout CSS, in the spirit of your giving special preference to double quotes within HTML [1],
(b) Allow the single-quote option across the board for all languages, including HTML.

Currently there is inconsistency, hence this issue, which can be considered a bug under your present philosophy. I would recommend allowing the single-quote option on JSX/HTML, as I believe that exhibiting inflexibility in any one area introduces unneeded complexity and unsatisfied users [1].

By the way, great work. I use Prettier very often, which is why I felt that I should bring up even a seemingly trivial criticism such as this.

[1] https://github.com/prettier/prettier/issues/656#issuecomment-306321171

**Comment by lydell** [comment]
Sorry, I don't understand what you mean.
