### ISSUE TITLE
[bug] Expression statements containing only do expressions need to keep parens

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#4466]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAJhABMAvgShABoQIAHGAS2gGdlQBDAJyYgHcAFZhOlBgNwiV0xEACMmDMAGs4MAMpkplKAHNkMJgFc4JFTThMYHSaoC2DZADMGAGwMkAVjQAeAIUky58hmbgAZFThrOwcQJSYDJmRxBjEAT1toUTJWAwB1STIY1Lgo-mCSJjgARy1KYpMGc0skG3tdEAMzSg1tRpoVVVs4AEUtCHgQhpIYOPThGAALZAAmUclKWy6AYQgzCxioaEKQLQMAFTjeerDUlRgJ9GnkAA4ABlxcIA)

**Input:**
```jsx
(do {})
```

**Output:**
```jsx
do {
};

```

**Expected behavior:**
```jsx
(do {
});

```

The prettier output won't parse at all (ie is invalid JS). Babylon has a test case for this, which is how I found it.

**Comment by j-f1** [comment]
Should be a fairly easy addition to `needsParens`.

**Comment by ad1992** [comment]
@j-f1 this needs to be fixed only for Babylon parser right? As its considered invalid js by the flow and typescript parser

**Comment by nicolo-ribaudo** [comment]
No, it needs to be fixed in prettier which doesn't put parentheses.
