### ISSUE TITLE
Chained functions should be aligned (v2)

### ISSUE THREAD

**Issue by testerez** [prettier/prettier#4467]
**Prettier 2.0 ?**
[Playground link](https://deploy-preview-4457--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEaBuBzAKTQDEBLAGzjUwF5MAzNAHSk0wDoAnOAQwBM+pTgGUAnlDAAKXHgAiQgJQs27ehXidJ9WgD5s+ImUoBRAB4wASnDxxT7eBi0KlrDgFseABy27MnnjAAFuwAVhCkUNL48pwANAzOANwgsSAQnjCk6MigPJycEADuAAp5CGjIIDw44XwpIABGnDxgANZwMML+YBF4yDCcAK5wqRFocJwwxc14Hsj0POTjqSFopgBCzW0dwjxucAAyEXDzi8sg-pzjnJUNPA2i5ND1npwRMADqpHxByAAcAAZUq8IOMPs1PJVXlQJjgTqluABHQZCODTHizHinJYjEDjNykfpDXFoXqUACKgwg8Gx5xg9y+P0CyAATKkBjwKL0AMIQNxzFBQaDwkCDcYAFXuFSQCxxAF85UA)

**Input:**
```jsx
const svgJsFiles = fs
  .readdirSync(svgDir)
  .filter(f => svgJsFileExtRegex.test(f))
  .map(f => path.join(svgDir, f));
```

**Output:**
```jsx
const svgJsFiles = fs.readdirSync(svgDir)
  .filter(f => svgJsFileExtRegex.test(f))
  .map(f => path.join(svgDir, f));
```

**Expected behavior:**
Keep first chained function call on a newline as it is in the input. So all chained functions are aligned.

Btw, I'm not sure what's the best way to get a playground link to next version or install it (I did `yarn add https://github.com/prettier/prettier`)

**Comment by ikatyang** [comment]
This looks like the false positive from #4285, I guess we should only apply the `name.length <= options.tabWidth` rule in `ExpressionStatement`.

cc @j-f1 

---

<details>

<summary><code>--tab-width 1</code></summary>

**Prettier pr-4285**
[Playground link](https://deploy-preview-4285--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEaBuBzAKTQDEBLAGzjUwF5MAzNAHSk0wDoAnOAQwBM+pTgGUAnlDAAKXHgAiQgJQs27ehXidJ9WgD5s+ImUoBRAB4wASnDxxT7eBi0KlrDgFseABy27MnnjAAFuwAVhCkUNL48pwANAzOANwgsSAQnjCk6MigPJycEADuAAp5CGjIIDw44XwpVRjI9DzkaHCpAEacPGAA1nAwwv5gEXjIMJwAru0gfBBgTS1tqRFtnDDF3Xgei60zIWimAELdfQPCPG5wADIRcLvLaZMwns8ATA8z-pxrlR08HVE5Gg9U8nAiMAA6qQ+EFkAAOAAMqTBEDakO6nkqYKocE4OHuqW4AEdJkI4JseNseJ9Um03KRxlMZmhRpQAIqTCDwWkgGAA6GwwLIACMqQmPAoowAwhA3DsUFBoISQJM2gAVAEVJDNPYAXz1QA)
```sh
--tab-width 1
```

**Input:**
```jsx
const svgJsFiles = fs
  .readdirSync(svgDir)
  .filter(f => svgJsFileExtRegex.test(f))
  .map(f => path.join(svgDir, f));
```

**Output:**
```jsx
const svgJsFiles = fs
 .readdirSync(svgDir)
 .filter(f => svgJsFileExtRegex.test(f))
 .map(f => path.join(svgDir, f));

```

</details>
<details>

<summary><code>--tab-width 2</code></summary>

**Prettier pr-4285**
[Playground link](https://deploy-preview-4285--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEaBuBzAKTQDEBLAGzjUwF5MAzNAHSk0wDoAnOAQwBM+pTgGUAnlDAAKXHgAiQgJQs27ehXidJ9WgD5s+ImUoBRAB4wASnDxxT7eBi0KlrDgFseABy27MnnjAAFuwAVhCkUNL48pwANAzOANwgsSAQnjCk6MigPJycEADuAAp5CGjIIDw44XwpVRjI9DzkaHCpAEacPGAA1nAwwv5gEXjIMJwAru0gfBBgTS1tqRFtnDDF3Xgei60zIWimAELdfQPCPG5wADIRcLvLaZMwns8ATA8z-pxrlR08HVE5Gg9U8nAiMAA6qQ+EFkAAOAAMqTBEDakO6nkqYKocE4OHuqW4AEdJkI4JseNseJ9Um03KRxlMZmhRpQAIqTCDwWkgGAA6GwwLIN6pCY8CijADCEDcOxQUGghJAkzaABUARUkM09gBfXVAA)

**Input:**
```jsx
const svgJsFiles = fs
  .readdirSync(svgDir)
  .filter(f => svgJsFileExtRegex.test(f))
  .map(f => path.join(svgDir, f));
```

**Output:**
```jsx
const svgJsFiles = fs.readdirSync(svgDir)
  .filter(f => svgJsFileExtRegex.test(f))
  .map(f => path.join(svgDir, f));

```

</details>

**Comment by duailibe** [comment]
> I guess we should only apply the `name.length <= options.tabWidth` rule in `ExpressionStatement`.

That sounds reasonable to me
