### ISSUE TITLE
async inline function not being formatted correctly

### ISSUE THREAD

**Issue by maxmedina05** [prettier/prettier#4473]
![image](https://user-images.githubusercontent.com/6037236/39963224-e67cda62-5633-11e8-8f8c-8e5f78fb0896.png)

The space between async keyword and parentesis is being removed. 
How can I work around this, using visual studio code?

**Comment by hawkrives** [comment]
Can you reproduce this on the playground? 

It feels like there's something else formatting your code, in addition to Prettier - VS Code's built in formatter, maybe, or something in ESLint.

**Comment by ikatyang** [comment]
Can you share some steps to reproduce? and also it'd be better to report issues using <kbd>Report issue</kbd> button on the [playground](https://prettier.io/playground/) next time.

---

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDM4YwALAYQFcSIBbObIvAXjwAoIMYAltHZdgAXwCUnAHx4AhkQCeUMNwAmAohjmUqUjrPEBuEABoQfQcOSg52bBADuABTsIiyEHIA2juYo9zACNsOTAAawoAZW0wASgAc2QYbDo4c3iiVhhnUISmOWRSHyzzACsiNAAhUIjouRYAGXi4IpL0kG02Vk8guSDFb2gzTux4mAB1ATUYKmQADgAGcwwHLInQjE9VuCzsADdW82w4AEc6ARPcuXzCpGLvUpAspgFk1I6ieITvOABFOgQeBtR4dGD9KYzOZIABM5hScgE3m+NGYBU8UGgRxADDgABV+h57u0xGIgA)
```sh
--arrow-parens always
```

**Input:**
```jsx
export const fetchCustomers = (options = {}) => async(dispatch) => {};
```

**Output:**
```jsx
export const fetchCustomers = (options = {}) => async (dispatch) => {};

```
