### ISSUE TITLE
TypeScript 2.8.3: bang operator results in Unexpected token, expected ";"

### ISSUE THREAD

**Issue by strongui** [prettier/prettier#4474]
**Environment**
VSCode : 1.23.1
Extension: Prettier - Code formatter esbenp.prettier-vscode
TS: 2.8.3

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEkBBTTAZRgEN58BffAMxwnXwHIA6bgel58AzjFxxOAbgA6UDNjyF8qKACs4YGABp8EAEZC4OAG6HGLNh07o9ADwC0OODQ2SZc3ASIAZZQGszrOxcjs4wDhAArvA4dgAm7K6yWB74AFT4NEL4AEpOGuZBnCEu0lAycDbyBMrRzM5wJD4A5gAWMEIACmyYWcAy+PgiYgD8SCTkVLTwpQwyYAA2mVnNbVkV8FCxWbmh3ADC7NhQCDAAPMQr7V0QPdrADAB8hP34jpuGABQAlM9QAwOQKAiRRDRxmAC8+BgLVQQm4mG6QlK-3wgOBRHmqFa7Qhg1EjgAhNwaBRqGJkf9HDAIjg-h8XijTrFUEZUYshEIAHI0dBwcFScDQWjKQx2ZjzCKoWICh4MlH4U4QeZspbc3n8kC6EKxMA4CLoXQyuXyhWYlUctV8gVapw6vUGuyoeDoI1-E3y04+KD+UQaviY7FCGWXISnPhe3yyt3uhX+1BRmMDU5mhaqnlWzXa3X63SO50ZDQsuAyg6wNjKlqRAz4ANtZRNMOYhPusNK5sm040PCoBZwdst5ms1MW9MasBd6Ugfsxpks81c0cC8c4WJ2XQQWIAT1diY9zFQcHmWzgBD405bfEH58Zl5Z19jXZgPfmfeNsavcq+FNmUB-5UqKSxHAdQRPM1SqOoMAfJwoLiF8Hx6AYxifCGXxfjIICaCANxPtAQjIKAXZsAA7h0XYIPhKA0EYEBSphmbOL4J6UJgzj1sgMB6nAWHKEhMBdDQTToDQyB1PMBhYSoQg2AAQjgjHMemXpwKJNDidxICsTgSHIJqNC6Ju8zQPRCI1AA6lK0LIAAHAADFhCIQAYZnyZgukInASEmPRjgAI6So4AlCSJSBiRJIAGOgqAcVxWFCPWL4AIoRBA8CqepWG0LoFmxFZSAAEyZfJqCYlATQHOgwm6VA0AqVhEQGAAKvplFhXADAMEAA)

**Input:**
```jsx
import { IAppState } from '../../store';
import { inject, observer } from 'mobx-react';
import { Link } from 'react-router-dom';
import * as React from 'react';

export interface ILightsProps {
  store?: IAppState;
}
class Lights extends React.Component<ILightsProps, {}> {
  render() {
    const { store } = this.props;
    const { lights } = store!.appStore;
    return (
      <div className="container-fluid">
        <ol className="breadcrumb">
          <li className="breadcrumb-item">
            <Link to="/lights">Lights</Link>
          </li>
          <li className="breadcrumb-item active">Control house lighting</li>
        </ol>
        <article>
          <div className="card">
            <div className="card-body">
              <fieldset />
            </div>
          </div>
        </article>
      </div>
    );
  }
}

export default inject('store')(observer(Lights));

```

**Output:**
```jsx
SyntaxError: Unexpected token, expected ";" (12:29)
  10 |   render() {
  11 |     const { store } = this.props;
> 12 |     const { lights } = store!.appStore;
     |                             ^
  13 |     return (
  14 |       <div className="container-fluid">
  15 |         <ol className="breadcrumb">
```

**Expected behavior:**

**Comment by ikatyang** [comment]
You have to specify `--parser typescript` on the playground.

---

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEkBBTTAZRgEN58BffAMxwnXwHIA6bgel58AzjFxxOAbgA6UDNjyF8qKACs4YGABp8EAEZC4OAG6HGLNh07o9ADwC0OODQ2SZc3ASIAZZQGszrOxcjs4wDhAArvA4dgAm7K6yWB74AFT4NEL4AEpOGuZBnCEu0lAycDbyBMrRzM5wJD4A5gAWMEIACmyYWcAy+PgiYgD8SCTkVLTwpQwyYAA2mVnNbVkV8FCxWbmh3ADC7NhQCDAAPMQr7V0QPdrADAB8hP34jpuGABQAlM9QAwOQKAiRRDRxmAC8+BgLVQQm4mG6QlK-3wgOBRHmqFa7Qhg1EjgAhNwaBRqGJkf9HDAIjg-h8XijTrFUEZUYshEIAHI0dBwcFScDQWjKQx2ZjzCKoWICh4MlH4U4QeZspbc3n8kC6EKxMA4CLoXQyuXyhWYlUctV8gVapw6vUGuyoeDoI1-E3y04+KD+UQaviY7FCGWXISnPhe3yyt3uhX+1BRmMDU5mhaqnlWzXa3X63SO50ZDQsuAyg6wNjKlqRAz4ANtZRNMOYhPusNK5sm040PCoBZwdst5ms1MW9MasBd6Ugfsxpks81c0cC8c4WJ2XQQWIAT1diY9zFQcHmWzgBD405bfEH58Zl5Z19jXZgPfmfeNsavcq+FNmUB-5UqKSxHAdQRPM1SqOoMAfJwoLiF8Hx6AYxifCGXxfjIICaCANxPtAQjIKAXZsAA7h0XYIPhKA0EYEBSphmbOL4J6UJgzj1sgMB6nAWHKEhMBdDQTToDQyB1PMBhYSoQg2AAQjgjHMemXpwKJNDidxICsTgSHICAMCbpgcBCLqqCYDA9EIjUADqUrQsgAAcAAMWEIhABhWfJmC6QiRmGCY9GOAAjpKjgCUJIlIGJEkgAY6CoBxXFYUI9YvgAihEEDwKp6lYbQug2bEdlIAATLl8moJiUBNAc6DCbpUDQCpWERAYAAqND6NlBgMAwQA)
```sh
--parser typescript
```

**Input:**
```tsx
import { IAppState } from '../../store';
import { inject, observer } from 'mobx-react';
import { Link } from 'react-router-dom';
import * as React from 'react';

export interface ILightsProps {
  store?: IAppState;
}
class Lights extends React.Component<ILightsProps, {}> {
  render() {
    const { store } = this.props;
    const { lights } = store!.appStore;
    return (
      <div className="container-fluid">
        <ol className="breadcrumb">
          <li className="breadcrumb-item">
            <Link to="/lights">Lights</Link>
          </li>
          <li className="breadcrumb-item active">Control house lighting</li>
        </ol>
        <article>
          <div className="card">
            <div className="card-body">
              <fieldset />
            </div>
          </div>
        </article>
      </div>
    );
  }
}

export default inject('store')(observer(Lights));

```

**Output:**
```tsx
import { IAppState } from "../../store";
import { inject, observer } from "mobx-react";
import { Link } from "react-router-dom";
import * as React from "react";

export interface ILightsProps {
  store?: IAppState;
}
class Lights extends React.Component<ILightsProps, {}> {
  render() {
    const { store } = this.props;
    const { lights } = store!.appStore;
    return (
      <div className="container-fluid">
        <ol className="breadcrumb">
          <li className="breadcrumb-item">
            <Link to="/lights">Lights</Link>
          </li>
          <li className="breadcrumb-item active">Control house lighting</li>
        </ol>
        <article>
          <div className="card">
            <div className="card-body">
              <fieldset />
            </div>
          </div>
        </article>
      </div>
    );
  }
}

export default inject("store")(observer(Lights));

```

**Comment by strongui** [comment]
@ikatyang There it is. My bad, I did not have `"parser": "typescript"` in my .prettierrc file.  :grimacing:
