### ISSUE TITLE
HTML comment throws SyntaxError

### ISSUE THREAD

**Issue by jasonhodges** [prettier/prettier#4497]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgMIQAOAngE4CWA5gBYw4AUYAlDgEwAMAjABw7YB8AHSipaAWwA2QqDhyoARhAAmxabNmoAhjmqk4AMwC8gkAGIT-AIJQw1CKVQB6TWvWol5AG47ySpQhwwCU0AZxDjEH0ICBMcX0N5TVJ+Jw9PVydFFWkncSkQABoQIhhyaBDkUCTSCAB3AAUkhAqUTU8IX0KQeVJNMABrOBgAZUI+8ihKZBhSAFc4IomQuFIYet7KMU1kfU0JZaKAKxCADwAhXoGh4c0xOAAZCbgdvYOQMdJl0mRuzXliCTQLqECiwADqvhg1GQ3HYRRBEGWYN6hB+ILgX08zyKegAjrNyHp1ppNtskLt9gsQMsxORpnMqSEJpQJHAAIqzCDwF6UoowP4QpRQ5CsPm9cgSZkEMRbH5QaDYkCzZYAFT+LQpywAvlqgA)

**Input:**
```jsx
<!-- Copyright (c) 2018 -->
<html>
  <body>
    <a href="#">Anchor</a>
    <div hidden class="foo" id=bar></div>
  </body>
</html>
```

**Output:**
```jsx
SyntaxError: Unexpected token (1:2)
> 1 | <!-- Copyright (c) 2018 -->
    |  ^
  2 | <html>
  3 |   <body>
  4 |     <a href="#">Anchor</a>
```

**Expected behavior:**
No syntax error to be thrown.

**Comment by evilebottnawi** [comment]
We don't support HTML right now. Main issue https://github.com/prettier/prettier/issues/1882

**Comment by jasonhodges** [comment]
I apologize, Seeing the following within the release notes is misleading. 
![image](https://user-images.githubusercontent.com/1988476/40201336-07f1afaa-59dc-11e8-9e8d-1dded355638c.png)
I understand if Prettier doesn't format HTML but it is throwing errors for any .html files under a directory you run the formatter on.

**Comment by lydell** [comment]
See #2846.
