### ISSUE TITLE
Boolean logic in class property has weird formatting

### ISSUE THREAD

**Issue by ccorcos** [prettier/prettier#4498]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgBo7AA6UOORMAlpgDKVQCuAHjgLw4AUJZPPA9Hxx1GTbr37DmfSgDp4mGByjoAbpQDm6GBABOMhpjg6AguoQwAlDgA+1seJwCcAYQAWOiAFs4AIQgQAa3txPmcdAHkAZWk5OAUlVQ0tXX1DEzNYC2CyKwAyXOzHQQARaAByGBxPLTBXIXpmAFoAIyw4ABMqiGbKVDgZQoBCGFdqGWoAWW7euBIAXxAAGhAIAAcqaExkUHQdDwB3AAVdhC2UVQhKdqWQZp10MAC4GEjVh-p1ZBgdBjhl+jSMEO93U1WQADN0KhDMsAFaYJg+e6PZ6RdDeYRwCFQmEgN46NLIW7oZoAT1Q0Buqx09BgAHUriNkAAOAAMy2pEEMdPuqyJ1LiRhUWOWOjgAEcGJQxcD0KD0NjoX8QIZPJQvj9lZgPn0AIoMCDwRW4mAkhntJlIABMy2+6F6H2cXjBKCg0BFIAMcAAKiSzpClXM5kA)

**Input:**
```jsx
class X {
    isLinux = (
        // Linux
        /Linux/i.test(navigator.userAgent) ||
        // ChromeBook
        /CrOS/i.test(navigator.userAgent)
      ) &&
      // Don't match Linux-based mobile.
      !this.isMobile
}
```

**Output:**
```jsx
class X {
  isLinux = // Linux
  (/Linux/i.test(navigator.userAgent) ||
    // ChromeBook
    /CrOS/i.test(navigator.userAgent)) &&
  // Don't match Linux-based mobile.
  !this.isMobile;
}

```

**Expected behavior:**

Unclear what exactly it should be -- I don't really care, but I find it awkward that `!this.isMobile` has the same indentation as `isLinux`

**Comment by duailibe** [comment]
#4442 fixed a bug for printing property initializers, here's how this will print in 1.13:

**Prettier pr-4442**
[Playground link](https://deploy-preview-4442--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgBo7AA6UOORMAlpgDKVQCuAHjgLw4AUJZPPA9Hxx1GTbr37DmfSgDp4mGByjoAbpQDm6GBABOMhpjg6AguoQwAlDgA+1seJwCcAYQAWOiAFs4AIQgQAa3txPmcdAHkAZWk5OAUlVQ0tXX1DEzNYC2CyKwAyXOzHQQARaAByGBxPLTBXIXpmAFoAIyw4ABMqiGbKVDgZQoBCGFdqGWoAWW7euBIAXxAAGhAIAAcqaExkUHQdDwB3AAVdhC2UVQhKdqWQZp10MAC4GEjVh-p1ZBgdBjhl+jSMEO93U1WQADN0KhDMsAFaYJg+e6PZ6RdDeYRwCFQmEgN46NLIW7oZoAT1Q0Buqx09BgAHUriNkAAOAAMy2pEEMdPuqyJ1LiRhUWOWOjgAEcGJQxcD0KD0NjoX8QIZPJQvj9lZgPn0AIoMCDwRW4mAkhntJlIABMy2+6F6H2cXjBKCg0BFIAMcAAKiSzpClXM5kA)

**Input:**
```jsx
class X {
  	isLinux = (
        // Linux
        /Linux/i.test(navigator.userAgent) ||
        // ChromeBook
        /CrOS/i.test(navigator.userAgent)
      ) &&
      // Don't match Linux-based mobile.
      !this.isMobile
}
```

**Output:**
```jsx
class X {
  isLinux =
    // Linux
    (/Linux/i.test(navigator.userAgent) ||
      // ChromeBook
      /CrOS/i.test(navigator.userAgent)) &&
    // Don't match Linux-based mobile.
    !this.isMobile;
}

```
