### ISSUE TITLE
eslint-disable-line comments should never move

### ISSUE THREAD

**Issue by MarkKahn** [prettier/prettier#4499]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgLICeAwhtjsDgPSU5yaoCWsAtACYOboBGqczjUOAB0oAXxAAaEBAAOMBtEzJQ6AE6qIAdwAKahEpToAbhAatJILqvRgA1nBgBlGTaYBzZDFUBXOFKaYcKow2tZuALboyABm6KiBUgBWmAAeAELWdg6O6OFwADJMcDFxCSAuqoGqyJbcBKjQFjKqTDAA6mYwABbIABwADFLNEIFt1jI1zXRBRsVSqnAAjt4MC6HoEVFIsfF+IIHhDJ4+e5juvACK3hDwJbtSMNwdrN3IAEwP1gwCbkQQ4ZEalBoHMQN5AgAVbgGHaBUSiIA)

**Input:**
```jsx
class MyClass { // eslint-disable-line
}
```

**Output:**
```jsx
class MyClass {
  // eslint-disable-line
}

```

**Expected behavior:**
Comment should be kept on the same line

**Comment by MarkKahn** [comment]
Sorry, dupe of #1267

**Comment by lydell** [comment]
Duplicate of #1267
