### ISSUE TITLE
Rename babylon to babel

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#4508]
Ref: babel/babel#7937

We should rename all `babylon` to `babel` but still remains the backward compatibility.

**Comment by wesleypearce** [comment]
I'm new to contributing and would like to help. Are you asking that all references "babylon" should be changed to "babel"?

**Comment by azz** [comment]
Think we should wait until babel 7 is released before doing this.

**Comment by ikatyang** [comment]
I don't have strong opinion on when we should address this, but I guess babel should be easier than babylon for people not familiar to parser to understand what it is.

I think this is a good change but babel 7 is under alpha/beta for over a year, I'm not sure when it'll be released. 😂

**Comment by duailibe** [comment]
> I guess babel should be easier than babylon for people not familiar to parser

I agree with the sentiment but I don't think it's the best way to achieve that.. instead doing the `--language` refactor should be the way to go (if we ever get around to it). Renaming babylon -> babel would be a marginal gain..

I don't oppose to it either though

**Comment by azz** [comment]
I'm fine with the change, but we should do it after switching to the actual `@babel/parser` package, and probably after 7.0 is released (there isn't really any urgency).

**Comment by duailibe** [comment]
I don't think we should wait for 7.0 (nor I think we shouldn't). `babel` should be more familiar than `babylon` if they deprecate that name or not.. IMO it's unrelated

**Comment by duailibe** [comment]
To be clear, what I mean is the fact that we use the `@babel/core` package or the `babylon` package is an implementation detail and not necessarily needs to be reflected on the API. `babel` is a good option regardless that we wait for `@babel/core` to be released or not.

**Comment by suchipi** [comment]
I work in the AST space a lot and `babylon` communicates to me what's happening better than `babel`; I compartmentalize `babylon` next to `acorn`, `esprima`, etc in my head, whereas "babel" is just this big thing. But it doesn't matter that much, especially if they're renaming it.

**Comment by viztor** [comment]
babel has recently released 7.0.0-rc. so this would be a good time for a pull-request to be opened for such change.

**Comment by j-f1** [comment]
I agree that we should switch to a `language` option, and deprecate most values of `parser`:

**`--language`**
* `javascript` (old `parser: babylon`)
* `json` (old `parser: json`)
* `json5` (old `parser: json5`)
* `json-stringify` (old `parser: json-stringify`)
* `flow` (old `parser: babylon`)
* `language: flow, parser: flow` (old `parser: flow`)
* `typescript` (old `parser: typescript`)
