### ISSUE TITLE
Issue with --stdin-filepath CLI flag

### ISSUE THREAD

**Issue by derekkramer** [prettier/prettier#4514]
**Prettier 1.12.1**
```sh
# Options (if any):
--stdin-filepath
```

The Prettier CLI is recognizing the wrong flag for `--stdin-filepath`. Only works when using `stdin-filepath` instead. Complete bash history showing the issue below:

```bash
# derekkramer in ~/test [18:54:20] 
$ ls
abc.css

# derekkramer in ~/test [18:54:23] 
$ cat abc.css 
.name { display: none; }


# derekkramer in ~/test [18:54:26] 
$ prettier --stdin-filepath abc.css
Usage: prettier [options] [file/glob ...]

By default, output is written to stdout.
Stdin is read if it is piped to Prettier and no files are given.

Output options:

  -l, --list-different     Print the names of files that are different from Prettier's formatting.
  --write                  Edit files in-place. (Beware!)

Format options:

  --arrow-parens <avoid|always>
                           Include parentheses around a sole arrow function parameter.
                           Defaults to avoid.
  --no-bracket-spacing     Do not print spaces between brackets.
  --jsx-bracket-same-line  Put > on the last line instead of at a new line.


  ...
  

  --require-pragma         Require either '@prettier' or '@format' to be present in the file's first docblock comment
                           in order for it to be formatted.
                           Defaults to false.
  --stdin                  Force reading input from stdin.
  --stdin-filepath <path>  Path to the file to pretend that stdin comes from.
  --support-info           Print support information as JSON.
  -v, --version            Print Prettier version.



# derekkramer in ~/test [18:54:47] C:1
$ prettier stdin-filepath abc.css 
.name {
  display: none;
}
```

### System and Prettier Version Information

```bash
# derekkramer in ~/test [19:01:02] 
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

# derekkramer in ~/test [19:02:40] 
$ prettier -v
1.12.1
```

**Comment by ikatyang** [comment]
I guess you meant to use either

- `prettier abc.css` or 
- `cat abc.css | prettier --stdin-filepath abc.css`

The `stdin-filepath` in `prettier stdin-filepath abc.css` is considered a glob pattern, which didn't match anything.

**Comment by derekkramer** [comment]
@ikatyang 
I see, perhaps I'm misunderstanding the `--stdin-filepath` flag.

What I noticed and drove me to raise the issue is when I run:
```
$ prettier --stdin-filepath abc.css
```
in the directory of `abc.css`, I receive the help docs of the Prettier CLI to the console, whereas running:
```
$ prettier stdin-filepath abc.css
```
prints the "prettified" file to the console as I expected with the first command.

Although upon further examination, I see that:
```
$ prettier abc.css
```
has the exact same effect, so my issue may be in error.

My thinking was that within the console help docs, I see:
```
--stdin-filepath <path>  Path to the file to pretend that stdin comes from.
```
but when I use that flag and the file path as I did in the first command, all I receive are the printed CLI help docs.

> The original `ls` and `cat` commands were just for the purpose of showing that the `abc.css` file existed and to show the contents of that file for more detail of the issue.

**Comment by lydell** [comment]
In 

```
prettier --stdin-filepath abc.css
```

there's no stdin coming into prettier, so `--stdin-filepath` is useless. However, you seem to have uncovered some buggy behavior around specifying that flag when it is not needed.

When you do `prettier abc.css`, Prettier infers to use the CSS parser since it sees that the file ends with `.css`. But when doing `prettier < abc.css` Prettier only gets a string of text as input and as such has no filepath to look for a file extension in. Finally, in `prettier --stdin-filepath abc.css < abc.css` we are giving Prettier a filepath so it can do its parser inference and stuff again.

**Comment by derekkramer** [comment]
@lydell 
That makes sense, I was confused by the console help docs and didn't see that the `--std-filepath` flag is meant to be used in conjunction with the `--stdin` flag. Thank you for the clarification!

closes #4514

**Comment by lydell** [comment]
Note that `--stdin-filepath` doesn't _have_ to be used with `--stdin`. `--stdin` is just for _forcing_ input to be read from stdin (instead of autodetecting).

**Comment by derekkramer** [comment]
Yes I see that now in conjunction with the `cli.md` edits I made for the `--stdin-filepath` flag.
