### ISSUE TITLE
Preserve quotes around property names in TypeScript classes

### ISSUE THREAD

**Issue by mariusschulz** [prettier/prettier#4516]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgKqZwBOOwAOlDjmSAK6FFToC2cNSOmMRAllAOYBuCgF8QAGhAQADjB7RMyUOiJEIAdwAKKhIpToAbhB4ATCSABGRdGADWcGAGVpNvv2TdacSXwYxN1vzM6MgAZuiohJIAVpgAHgBC1nYOjixwADJ8cGERUSAuRAzIIDAAntJwmGC8subSvLAA6qYwABbIABwADJINEIRN1tIlDVXEBjmSRHAAjrQ8MwHoQSFI4ZHeIITMPB5EXpKYbqhwAIq0EPC5m5Iw6BYtJu3IAEx31jyobgDCEMzBEpQaBTOiEAAqDz0G0IIhEQA)
```sh
--parser typescript
```

**Input:**
```tsx
class User {
  "username": string;
}
```

**Output:**
```tsx
class User {
  username: string;
}
```

**Expected behavior:**

The output should be identical to the input:

```tsx
class User {
  "username": string;
}
```

Otherwise, when the TypeScript code is compiled with `--strictNullChecks` and `--strictPropertyInitialization` (which are collectively set by default via the `--strict` flag), the type checker will raise a type error:

```
Property 'username' has no initializer and is not definitely assigned in the constructor.
```

This is because TypeScript's type checker treats properties with quoted names more leniently than unquoted ones. I suggest Prettier preserve quotes around property names in classes when using the TypeScript parser.

Steps to verify this behavior:

1. Open [this TypeScript playground](http://www.typescriptlang.org/play/index.html#src=class%20User%20%7B%0D%0A%20%20username%3A%20string%3B%0D%0A%7D).
2. Click "Options" and enable both `strictNullChecks` and `strictPropertyInitialization`.
3. Note the type error.

**Comment by ikatyang** [comment]
Ref: Microsoft/TypeScript#20075

> Strict property initialization checks only apply to properties that are declared with proper identifiers. It does not apply to properties with computed names or properties with names specified as string or numeric literals (this is analogous to how control flow analysis isn't applied to properties accessed using `obj["foo"]` syntax).
>
> ```ts
> // Compile with --strict
> class Test {
>   a: number;  // Error, not initialized
>   "hello world": number;  // No check
> }
> ```
