### ISSUE TITLE
Visual Studio 2017 Plugin ignores .eslintrc.json

### ISSUE THREAD

**Issue by fbacker** [prettier/prettier#4522]
Visual Studio 2017 Plugin ignores .eslintrc.json
When using the Prettier plugin with Visual Studio 2017 it ignores the rules set with .eslintrc.json. I'm not using the .prettierrc file because specifying 2 configuration files seems like a big source of issues and double work.

NOTE: I've tried the plugin for Visual Studio Code and here it works great without adding 'prettier' to eslint configuration rules and extends.

**package.json**
````
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-flowtype": "^2.46.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.8.2",
`````

**.eslintrc.json**
````
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true,
    "jquery": true
  },
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "sourceType": "module"
  },
  "plugins": [ "react", "import", "prettier" ],
  "rules": {
    "no-alert": "off",
    "no-restricted-globals": "off",
    "no-const-assign": "warn",
    "no-this-before-super": "warn",
    "no-undef": "warn",
    "no-unreachable": "warn",
    "no-unused-vars": "warn",
    "constructor-super": "warn",
    "valid-typeof": "warn",
    "no-console": "off",
    "react/prefer-stateless-function": "off",
    "no-param-reassign": "off",
    "import/no-named-as-default": "off",
    "linebreak-style": "off",
    "no-case-declarations": "off",
    "jsx-a11y/anchor-is-valid": "off"
  },
  "extends": [ "airbnb", "prettier" ]
}
````

**Input:**
> Right-click in file and choose 'Make Prettier'

**Output:**
Ignores rules from eslint with airbnb

**Expected behavior:**
Use the .eslintrc.json file for formatting rules.

**Comment by lydell** [comment]
I assume you use this extension? https://github.com/madskristensen/JavaScriptPrettier

Then please open an issue over there.

Let me know if I missed something and we’ll re-open this issue.
