### ISSUE TITLE
Feature request: file naming

### ISSUE THREAD

**Issue by sergeysova** [prettier/prettier#4525]
Add option to change file/directories names case in project.

Example:

```
./FooBar/Baz.js
```

Changed to: 

```
./foo-bar/baz.js
```

Change imports too.

to be consistent with package-names.

**Comment by duailibe** [comment]
Hi @sergeysova, thanks for the report. This feature is completely out of Prettier's scope, we only focus on formatting code. I think there are other tools to help you with that!

Gonna close this since it's not something we're gonna do.
