### ISSUE TITLE
Typescript 2.9 support?

### ISSUE THREAD

**Issue by mvestergaard** [prettier/prettier#4531]
This is mostly a question, and not a bug report.
I can see that efforts have been made in `typescript-eslint-parser` to make JSX generics, and template literal generics be parsed properly. However this still fails on the current version of `prettier`.

The current `package.json` in `master` points to a commit where these features should be included. But it's difficult to tell which version the current version of `prettier` actually uses, because it is bundled and minified.

We would very much like to move to TS 2.9 soon, because these new features can simplify alot of code. However we rely pretty heavily on `prettier`.

Can you give a guesstimate of when 2.9 will be properly supported?

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwHIdTy6BuAHSg7ABsSBnPvgCyATwDiCODlRgAwjWxQEMADwAVAHz44AD3hQAJoOJkYAOnlZoy-MA758jQ1IAUASlv2HjuDACuOFD4KgaoAG4afDRw+ADmktJg+JBWSrAqAPShEexB+AC+HIWcUJBQfJQQEPgAvMGiEkqJlorKKhXSULFaGRq5IAA0IBCYMKjQfMigJDjUAO4ACjMIkygkYRCoBoMgAEY4ZADWvgDKmGSoXcgwOH5wQ5d8UjALB7HoJMgUJNxPQwBWfB0ACEDmBjjATiR0HAADKXOBfH5-EDnHBPHDIEAwESYOB8MDSUY7TCdGAAdS2MAAFsgABwABiGpIgT3JB0wWNJ+KkYURQ0YAEc-KhGK8SO9Pkhvr97iAnuhUNdbnK+JdYtw4ABFPwQeBI2VDGAkXaUgw05AAJiNB1Q3HVlg+WKg1h2fieahNqxlT3y+SAA)
```sh
# Options (if any):
--parser typescript
```

**Input:**
```jsx
import React from 'react';

class MyGenericComponent<T> extends React.Component {
  render() {
    return <div>some generic component</div>;
  }
}

const foo = <MyGenericComponent<string> />;

```

**Output:**
```jsx
SyntaxError: ';' expected. (5:22)
  3 | class MyGenericComponent<T> extends React.Component {
  4 |   render() {
> 5 |     return <div>some generic component</div>;
    |                      ^
  6 |   }
  7 | }
  8 | 
```

**Expected behavior:**
No error

**Comment by j-f1** [comment]
Thanks for using Prettier!

We’re currently working on the blog post for 1.13 in #4530, and the overall issue tracking the release is #4444.
