### ISSUE TITLE
Braces style

### ISSUE THREAD

**Issue by qawsqs** [prettier/prettier#4546]
Add stroustrup style braces and make them default

**Comment by evilebottnawi** [comment]
@qawsqs What is problem with using issue template? Why we should add this? Why we should make them default. You issue request looks disrespectfully. Please use `issue` template and describe we we should do this and when reopen issue.

**Comment by qawsqs** [comment]
What's disrespectful is making arbitrary limitations

**Comment by j-f1** [comment]
Please check out [our reasoning behind not including options](https://prettier.io/docs/en/option-philosophy.html).
