### ISSUE TITLE
Decorator is removed when followed by an interface.

### ISSUE THREAD

**Issue by muhanadra** [prettier/prettier#4552]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwGEItoEYAafAeSgEkpUCBffAMxzPwHIABAIZQA5gFcANoJwB6SDji8A3AB0o-UuSiUAFMDX58AZzgS4YGLiR8ARnAC0E1EZi8qB-PCxT4AVRwS1rwAdDJ2js4wwZBalMEAFjDoErxqrACUaqiwcDgcgmBw+ACyAJ5M8HkFRfpQhqgAJtYuONkiqlCsanAAHth4+GBSRkb4AEJwADKRmtjasPgYmGbolKP0TCyEHpBQLWIWuDrp23X4XWeiG8wwx6eGhjDxzsEwLGb4ALx8ACrvih1DBcLiAqCAIJg3tAjMhQNJuAB3AAK0gQMJQggAbhBGqCQDYcAUANZwGAAZUwBTayBgODEcDB2RMeCRhJE6EEyHyEhMYIAVkYemNCWASeTBKtptouYIeQyQJScMzkCAYKVMHAjGBWpC8ZhWrAAOqNJ7IAAcAAYwfqICZDYTMCr9Zrcpi4HiFABHMSoBSswTszlIbm8kAmdCoGl0+VGNpmACKYgg8BlcrBMEENmNDVNSAATOnCagnKJNByVVAKHixCYfpn0SH5YIXKnQw0IGBW-KIGIYJhe3mu6xWEA)
```sh
--parser typescript
```

**Input:**
```tsx
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'be-list',
  templateUrl: './be-list.component.html'
})
interface MyInterface {
  id: string;
}
export class BeListComponent implements OnInit {
  constructor() {
  }
  ngOnInit() {
    this.title = 'Title';
  }
}

```

**Output:**
```tsx
import { Component, OnInit } from "@angular/core";
interface MyInterface {
  id: string;
}
export class BeListComponent implements OnInit {
  constructor() {}
  ngOnInit() {
    this.title = "Title";
  }
}

```

**Expected behavior:**
While the decorator is invalid, It should not be deleted. Either format it or throw a syntax error.
```tsx
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'be-list',
  templateUrl: './be-list.component.html'
})
interface MyInterface {
  id: string;
}
export class BeListComponent implements OnInit {
  constructor() {
  }
  ngOnInit() {
    this.title = 'Title';
  }
}

```

**Comment by ikatyang** [comment]
Tracked in eslint/typescript-eslint-parser#478.
