### ISSUE TITLE
--list-different flag in Windows makes Prettier not match any files 

### ISSUE THREAD

**Issue by mohsen1** [prettier/prettier#4561]
When adding `--list-different` command line flag all of the sudden Prettier fails to find files in Windows to check. 

This is happening in Parcel Bundler at this SHA:
https://github.com/mohsen1/parcel/tree/3403f36

AppVeyor builds:

https://ci.appveyor.com/project/devongovett/parcel/build/1.0.1995/job/ql975dqmfrquy4rv

**Prettier 1.9.1**

**`.prettierignore`**
```
src/builtins
test/integration
```
**`.prettierrc`**
```js
{
  "singleQuote": true,
  "bracketSpacing": false,
}
```
**Command**
```sh
prettier './{src,bin,test}/**/*.{js,json,md}' --list-different
```

**CLI Output**
```
[error] No matching files. Patterns tried: './{src,bin,test}/**/*.{js,json,md}' !**/node_modules/** !./node_modules/**
```

Related PR: https://github.com/parcel-bundler/parcel/pull/1442

**Comment by duailibe** [comment]
Does `path/to/file` work on Windows? Shouldn't it be `path\\to\\file`?

(I really don't know)

**Comment by j-f1** [comment]
> (Should we run CI on windows?)

We could do that with [AppVeyor](https://appveyor.com/), but it hasn’t been approved by org owners for access to the @prettier org.

**Comment by fathyb** [comment]
We fixed the issue by replacing `'./{src,bin,test}/**/*.{js,json,md}'` to `"./{src,bin,test}/**/*.{js,json,md}"`. Is `--list-different` changing how args are processed or is it due to how Windows handle quotes?

**Comment by duailibe** [comment]
@fathyb `--list-different` and `--write` are supposed to use the same logic for finding files. `--write` doesn't give any errors?

cc @mohsen1

**Comment by fathyb** [comment]
I don't use Windows so I can't tell. I created a branch to test it and pushed it to run it on AppVeyor : 
- [`prettier './{src,bin,test}/**/*.{js,json,md}' --write`](https://ci.appveyor.com/project/devongovett/parcel/build/1.0.2023)
- [`prettier './{src,bin,test}/**/*.{js,json,md}'`](https://ci.appveyor.com/project/devongovett/parcel/build/1.0.2024)

**Comment by duailibe** [comment]
> is it due to how Windows handle quotes?

Yep, apparently. Looks like other people have had the same problem in the past https://github.com/prettier/prettier/issues/4086#issuecomment-370228517

We should probably add that to the docs

**Comment by lydell** [comment]
Windows = use double quotes only

**Comment by mohsen1** [comment]
Isn't this an issue with yarn/npm? What environment (in sense of Unix hashbang environment) does npm run those scripts? if it's `bash`, single quotes should be fine.

**Comment by hawkrives** [comment]
@mohsen1 On Windows, Yarn and npm both spawn their "run" scripts in CMD.exe, which has some weird rules surrounding single quotes.
