### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by hsiaoyi0504** [prettier/prettier#4569]
**Prettier 1.13.0**

After running the installation through
`npm install --save-dev --save-exact prettier`

I tried to run the prettier
```zsh
prettier -v
```

But I get command not found error:
``` zsh
zsh: command not found: prettier
```

**Comment by j-f1** [comment]
This happens because your shell doesn’t know where to look for Prettier. If you run `prettier` inside an npm script, it should work. If you want to try it from the command line, `npx prettier` should work.

**Comment by hsiaoyi0504** [comment]
Thanks !
