### ISSUE TITLE
 No parser and no file path given, couldn't infer a parser.

### ISSUE THREAD

**Issue by xcsweb** [prettier/prettier#4577]
prettier@1.13.0
webpack@3.6
 No parser and no file path given, couldn't infer a parser.
![image](https://user-images.githubusercontent.com/20693737/40604171-d0b58fe4-6290-11e8-9b3c-8b1c8e578010.png)

**Comment by laodaxyz** [comment]
npm install prettier@~1.12.1 to fix it

**Comment by azz** [comment]
This has been fixed in vue-cli, try run:

```bash
npm update --depth=9999 @vue/component-compiler-utils
```
