### ISSUE TITLE
update to 1.13 breaks vue-webpack

### ISSUE THREAD

**Issue by nothingismagick** [prettier/prettier#4583]
https://stackoverflow.com/questions/50555953/vue-webpack-template-missing-parser

"This is fixed in vue-loader@13.7.2 and vue-loader@14.2.3. So just upgrade."

**Comment by lydell** [comment]
We're sorry about the trouble!

This has already been discussed in #4567.

**Comment by lydell** [comment]
Duplicate of #4567

**Comment by lydell** [comment]
Good idea! I'll re-open the other one!
