### ISSUE TITLE
Restore default parser for API only?

### ISSUE THREAD

**Issue by azz** [prettier/prettier#4585]
How do we think about doing a patch release where we restore the default parser for API usage only? This should cover most of the breakage while still offering some of the advantages from CLI usage.

We can then add a warning and re-remove it in 2.0.

**Comment by duailibe** [comment]
Yeah it's kind of hard since we don't know if it was called from the CLI or not, and the CLI uses the API.

https://github.com/prettier/prettier/blob/master/src/main/options.js#L33-L47

**Comment by j-f1** [comment]
You could check in the CLI if the parser can be guessed or is provided, then throw if it isn’t.

**Comment by azz** [comment]
Thanks @duailibe!
