### ISSUE TITLE
break line in dot promises

### ISSUE THREAD

**Issue by MohamadKh75** [prettier/prettier#4596]
**Prettier 1.13.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wBsIBzASygFUi5s8BePACmDzgFsBDK0gBo8GXkSIB3HABM8AXwCULAHx5gAHSh482ODACu2LdKpFRMMAAsVazdu0AzKroBGYuADpe+mJbYKPIioKKABJKAB1Kl8AUT4BAEEoaQAFMUkZNh5+IRF0qWxpBTt7bQ9fBDZ9BiZmVV5SRhgqmoUFAG4SuU6obpBBEAgMGCpoImRQXmxsCAk03WJkEF4ANwgqaX6QF2xeMABrPQBlUTAaCmQYbH04AZoamBTdij5kBwaGAYArIjQAIV2B2OvG4cAAMjQ4G8PrcQKJsDUlm4XABPchQLYYbA0GBRaS+ZAADgADAMsRAGBFdhglli4DUVlCBroAI76ZxwJ68F68aGkT4gBjcKiXa6woJQCiNACK+gg8D5ApgvBceIJSAATAMrjlzgBhCDcV4oKDQJkgapwAAqKvGSHe-LgcjkQA)
```sh
--parser babylon
```

**Input:**
```jsx
export const loginUser = ({ email, password }) => {
  return dispatch => {
    firebase.auth().signInWithEmailAndPassword(email, password)
      .then(user => alert(user));
  };
};
```

**Output:**
```jsx
export const loginUser = ({ email, password }) => {
  return dispatch => {
    firebase
      .auth()
      .signInWithEmailAndPassword(email, password)
      .then(user => alert(user));
  };
};

```

**Expected behavior:**
i just want my output code be the same as my input! i can set the ````Print Width```` but that affect all the code!

**Comment by lydell** [comment]
I think the output is easier to read. ¯\\\_(ツ)\_/¯

> i can set the Print Width

It doesn't look like that.

**Prettier 1.13.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wBsIBzASygFUi5s8BePACmDzgFsBDK0gBo8GXkSIB3HABM8AXwCULAHx5gAHSh482ODACu2LdKpFRMMAAsVazdu0AzKroBGYuADpe+mJbYKPIioKKABJKAB1Kl8AUT4BAEEoaQAFMUkZNh5+IRF0qWxpBTt7bQ9fBDZ9BiZmVV5SRhgqmoUFAG4SuU6obpBBEAgMGCpoImRQXmxsCAk03WJkEF4ANwgqaX6QF2xeMABrPQBlUTAaCmQYbH04AZoamBTdij5kBwaGAYArIjQAIV2B2OvG4cAAMjQ4G8PrcQKJsDUlm4XABPchQLYYbA0GBRaS+ZAATmJhIGWIgDAiuwwSyxcBqKyhA10AEd9M44E9eC9eNDSJ8QAxuFRLtdYUEoBRGgBFfQQeB8gUwXguPEEpAAJgGVxy5wAwhBuK8UFBoEyQNU4AAVFXjJDvflwORyIA)
```sh
--parser babylon
--print-width 9999
```

**Input:**
```jsx
export const loginUser = ({ email, password }) => {
  return dispatch => {
    firebase.auth().signInWithEmailAndPassword(email, password)
      .then(user => alert(user));
  };
};
```

**Output:**
```jsx
export const loginUser = ({ email, password }) => {
  return dispatch => {
    firebase
      .auth()
      .signInWithEmailAndPassword(email, password)
      .then(user => alert(user));
  };
};

```

**Comment by MohamadKh75** [comment]
@lydell two different points of view. so there is no option for that? 😁

**Comment by suchipi** [comment]
There's no option for method chaining, and we don't intend to implement one.
