### ISSUE TITLE
Prettier removes parentheses wrongly, turning a Flow type cast into an arrow function

### ISSUE THREAD

**Issue by roryokane** [prettier/prettier#4607]
**Prettier 1.13.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBDKBnAZhNAWwApiAHCAS1gBVMd8i40kACYgBStlYF4A+Vl2owAlOIDcIADQgIZGJWjZkoDGjQQA7h3UIVKDADcqAExkgARpjABrODADKZDGGoBzZOgCucWdWxmGA5Md0IMZFwMABtA2QArbAAPACEbeycMQjgAGWo4SJi4kBc0QLRkKwxLAE9o6AsyNBEAdUpTGAALZAAOAAZZJohAlswySqa4cqMC2TQ4AEdvSnmQjDCIpCjYvxBAwkovNF9ZbA9ouABFbwh4Qp3ZGGq2ju6kACZHzEpojwBhCCEcKVKDQWYgbyBGjVAzbQIAX3hQA)
~~~sh
--parser babylon
~~~

(the same wrong output results when using `--parser flow`)

**Input:**
~~~js
transform((pointTransformer: (Point => Point)));
~~~

**Output:**
~~~js
transform((pointTransformer: Point => Point));
~~~

**Expected behavior:**
~~~js
transform((pointTransformer: (Point => Point)));
~~~

As shown by [AST Explorer](https://astexplorer.net/#/gist/4b5238f40d3390f6bdd2997011840dad/9b143389348f9cc60ad024fe8fc9d643b757f427) when seeing how the Flow parser interprets this statement, Prettier **changes the semantics** of this expression when it removes the parentheses. With parentheses, the function argument is a [type cast](https://flow.org/en/docs/types/casting/#type-cast-expression-syntax-) of `pointTransformer` to a [function type](https://flow.org/en/docs/types/functions/#toc-function-types). Without parentheses, it turns into an arrow function with its [return type annotated](https://flow.org/en/docs/types/functions/#toc-arrow-functions).

This bug can also cause **unstable formatting**, requiring two runs to settle down. If you start with this:

~~~js
transform(((pointTransformer: any): (Point => Point)));
~~~

It [turns into this][unstable-step-1]:

~~~js
transform(((pointTransformer: any): Point => Point));
~~~

Which [turns into this][unstable-step-2] when formatted again:

~~~js
transform((pointTransformer: any): Point => Point);
~~~

[unstable-step-1]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBDKBnAZhNAWwApSAHCAS1gBVMd8i40kACLATwEo3iAFKrFYBeAHysB1GFxkBuEABoQEMjErRsyUBjRoIAdz46EmlBgBuVACaKQAI0xgA1nBgBlMhjDUA5snQArnBK1NjMMHyYPoQYyLgYADZhSgBW2AAeAEKOLu4YhHAAMtRwcYnJIJ5oYWjI9hh2HAnQtmRoUgDqlFYwABbIABwADEptEGEdmGR1bXA15qVKaHAAjgGUy5EY0bFI8UnBIGGElP5oQUrYvglwAIoBEPBlB0owDV09-UgATK+YlAlfABhCCEGJ1KDQRYgAJhGgNUz7MIAX2RQA
[unstable-step-2]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBDKBnAZhNAWwApSAHCAS1gBVMd8i40kACLATwEo2AFK2KwC8APlb9qMLlwDcIADQgIZGJWjZkoDGjQQA7r20INKDADcqAEwUgARpjABrODADKZDGGoBzZOgCucIrU2MwwvJjehBjIuBgANqGKAFbYAB4AQg7ObhiEcAAy1HCxCUkgHmihaMh2GLYc8dA2ZGiSAOqUljAAFsgAHAAMiq0Qoe2YZLWtcNVmJYpocACO-pRLERhRMUhxiUEgoYSUfmiBitg+8XAAiv4Q8KX7ijD1nd19SABML5iU8T4AMIQQjRWpQaALED+UI0eomPahAC+SKAA

**Comment by ikatyang** [comment]
Is this still an issue? I tried flow@0.79.1 on AST Explorer and got the same AST for both of the following cases:

```js
transform((pointTransformer: Point => Point));
```

```js
transform((pointTransformer: (Point => Point)));
```

**Comment by j-f1** [comment]
Reopening since the idempotency issue still exists:

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBDKBnAZhNAWwApSAHCAS1gBVMd8i40kACLATwEo3iAFKrFYBeAHysB1GFxkBuADpQQAGhAQyMStGzJQGNGggB3PvoQ6UGAG5UAJipAAjTGADWcGAGUyGMNQDmyOgArnCq1NjMMHyY-oQYyLgYADaRqgBW2AAeAEIu7l4YhHAAMtRwiSlpID5okWjIThiOHMnQDmRoUgDqlLYwABbIABwADKqdEJHdmGSNnXD1VhWqaHAAjsGUazEYcQlISalhIJGElEFooarYAclwAIrBEPCVx6owzb39Q0gATB9MJRkgEAMIQQjxRpQaArEDBSI0ZoWI6RAC+aKAA)
```sh
--parser babylon
```

**Input:**
```jsx
transform(((pointTransformer: any): (Point => Point)));

```

**Output:**
```jsx
transform(((pointTransformer: any): Point => Point));

```

**Second Output:**
```jsx
transform((pointTransformer: any): Point => Point);

```
