### ISSUE TITLE
Parentheses around function argument are removed despite prettier-ignore comment before it

### ISSUE THREAD

**Issue by roryokane** [prettier/prettier#4608]
**Prettier 1.13.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBDKBnAZhNAWwAoAdKAAgoHpqKAHNOGGASzjQFpWBzKAuOSrF6EVrAAqmHPiIckFYgAUxsCgF4AfBRXiYASn3l9AbhAAaEBHpto2ZKAxo0EAO5KnCeygwA3MQAmFiAARphgANbMAMr0GGDiPMjoAK5wluLYHDBKmDyEGMi4GAA2WZYAVtgAHgBC4VEw0RiEcAAy4nBFpeUgcWhZaMihGCEAniXQwYx6AOqsATAAFsgAHAAMlowQWbOY9MOMcIO+XZZMAI4prEy5GPmFSMVl6SBZhKzJaGmW2IklcAAiikIPBui9LDBRvNFiskAAmSGYVglRIAYQghAKw34UDOIBSWQko28zyyAF9yUA)
~~~sh
--parser babylon
~~~

**Input:**
~~~js
transform(
  // prettier-ignore
  (pointTransformer: (Point => Point))
);
~~~

**Output:**
~~~js
transform(
  // prettier-ignore
  pointTransformer: (Point => Point)
);
~~~

**Expected behavior:**
~~~js
transform(
  // prettier-ignore
  (pointTransformer: (Point => Point))
);
~~~

While trying to work around #4607 with a [`// prettier-ignore` comment][ignore-comment], I had trouble getting Prettier to leave the parentheses around the function argument alone. The type cast `(pointTransformer: (Point => Point))` is the next node after the comment, so Prettier should preserve its parentheses instead of deleting them.

It [also doesn’t work][doesnt-work-inline-comments] if I add adjacent inline `/* prettier-ignore */` comments:

~~~js
transform(
  /* prettier-ignore */(/* prettier-ignore */pointTransformer: (Point => Point))
);
~~~

The parentheses are still removed when I do that:

~~~js
transform(
  /* prettier-ignore */ /* prettier-ignore */ pointTransformer: (Point => Point)
);
~~~

### Workaround

You can work around this by moving the ignore comment [above the entire function call][works-annotate-function-call].

~~~js
// prettier-ignore
transform(
  // some other line comment
  (pointTransformer: (Point => Point))
);
~~~

Prettier correctly makes no changes when formatting the above code.

[ignore-comment]: https://prettier.io/docs/en/ignore.html#javascript
[doesnt-work-inline-comments]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBDKBnAZhNAWwAoAdKAAgoHoAqCgBzThhgEs40BaNgcygJwKtasTqNmrDtz4Dmw6gwhtYAFUw58RTkgrEACstgUAvAD4KhlTACUN8jYDcIADQgIDdtGzJQGNGgQAO76-gg+KBgAbsoAJq4gAEaYYADWLADKDBhgKrzI6ACucG4q2Jww+pi8hBjIuBgANuVuAFbYAB4AQinpMBkYhHAAMipw9U0tINlo5WjISRiJAJ6N0AlM1gDqbLEwABbIABwADG5MEOVbmAwLTHBzUeNuzACOhWzMVRg1dUgNzRKIHKhDYBTQxTc2DyjTgAEVChB4BNAW4YEsdntDkgAExozBsRp5ADCEEItQWAigzxAhXKqiWEQB5QAviygA
[works-annotate-function-call]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHVhwEMoBnAMxoFsAKejDdBhYROcDBBgALEhgA2hKGMidRsPhm5YICmABUmrDjlE4kGgArbYGALwA+DJZ0BKZ-WcBuEABoQELETQLMigjDg4EADu5mEIwSiMAG7aACY+IABGTGAA1vgAyliMYAoUyDA4AK5wvgosJDDmTBScjMhsjLL1vgBWLAAeAELZeTD5jKIAMgpw7Z3dIEU49TjImYwZAJ6y0Om4OgDqhClSyAAcAAy+uBD1B0xYa7hwK4mzvngAjpWEeE2MLTaSA6XRqIHqnEI5SqYJYpVkcAAipUJLNgfMwTANkcTpJkAAmXwVRiEeRQCgAYRErTW1EU6Uq9V0G3iIPqAF92UA

**Comment by ivoiv** [comment]
@lydell Having the same issue with prettier 5.7.1 for VSCode
Using TypeScript 4.1.0-beta  and latest VSCode Insider - 1.51.0-insider

```    
// prettier-ignore
[key in keyof ReturnType<Reducer>]: ReturnType<Reducer>[key] extends Function
   ? (...props: any) => State | void
   : State;
```

turns into 

```    
// prettier-ignore
key in keyof ReturnType<Reducer>: ReturnType<Reducer>[key] extends Function
   ? (...props: any) => State | void
   : State;
```

leading to code not compiling due to TS errors.

**Comment by thorn0** [comment]
@ivoiv Thanks for reporting. I opened a separate issue for your bug: #9550

**Comment by fisker** [comment]
This works with `flow` parser.

```js
> require('@babel/parser').parse('a((a:a))', {plugins: ['flow'],ranges:true}).program.body[0].expression.arguments[0].range
[ 3, 6 ]
> require('flow-parser').parse('a((a:a))').body[0].expression.arguments[0].range
[ 2, 7 ]
```
