### ISSUE TITLE
json5 embedded in markdown gets treated as js (quotes removed)

### ISSUE THREAD

**Issue by Haroenv** [prettier/prettier#4611]
**Prettier 1.13.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAztArAHSmEIAIT8QoBDAWzgqXJACMrm4AbAWkgCd6QAGlJNIUMFXjV4AEwBytAYwqt2HPgOFQyFGRADuUDhCoysAGSpYYAZgAMAESoBPLAxIBGOwE4A7AA5fABZvLR0QPUNjUywAJUkASwh3OwA6O38bLwA2XA9s-wAmAtx-bI8wpgALAFcaKigHAyMTM0treydXdwoPDxoKSooABwhhmo4qXncYXhq4IZAANzheLCSoHpBs1OL0wcIAX0J0VCEQMZgNrGRQKd4DAAUphBuUKiWIBJlz5l4qMAAazgMAAysMAQkoABzZCzeaCEBQrCrGCPf7Q+rIABmVA4KMR2AAHgAhf5AkGgxTmKFwHF4gkgCFrVbIED1XiAyJQc7DXhQmAAdW+MCqyH8dkRfIgKMF-2GbL5cBRvBW534AEcagl+OiqJiqPT8QsQCiaAk4XMTesYRw4ABFGoQeBGxkwNjCmSi5CFRGzKgJDhQ6EAYQgNCxKCg0DpiJqKIAKmw3rjjYdDkA)
```sh
--parser markdown
```

**Input:**
````markdown
```json5
{
  "name": "babel-core",
  "concatenatedName": "babelcore",
  "downloadsLast30Days": 10978749,
  "downloadsRatio": 0.08310651682685861,
  "humanDownloadsLast30Days": "11m",
  "popular": true,
  "version": "6.26.0",
}
```
````

**Output:**
````markdown
```json5
{
  name: "babel-core",
  concatenatedName: "babelcore",
  downloadsLast30Days: 10978749,
  downloadsRatio: 0.08310651682685861,
  humanDownloadsLast30Days: "11m",
  popular: true,
  version: "6.26.0"
}
```

````

**Expected behavior:**

**Comment by Haroenv** [comment]
whoa never mind, I didn't know that was the default behaviour of json5 --> https://json5.org/#short-example

However I'm not sure what highlighting I should use for "json with comments", like vscode settings? 🤔

**Comment by ikatyang** [comment]
[`jsonc` (JSON with Comments) should be treated as JSON (`parser: "json"`)](https://github.com/prettier/prettier/pull/4374) but highlighted as JSON5, I'm not sure what should we do here, maybe we should add a special case for it? e.g.

````
```json5 jsonc
{
  "name: "babel-core",
  "concatenatedName: "babelcore",
  "downloadsLast30Days: 10978749,
  "downloadsRatio: 0.08310651682685861,
  "humanDownloadsLast30Days": "11m",
  "popular": true,
  "version": "6.26.0"
}
```
````

**Comment by Haroenv** [comment]
what about `jsonc` as a language? I'm fine with using that

**Comment by ikatyang** [comment]
I thought about it but there's no highlighting, is it fine to you?

````
```jsonc
// comment
{
  "name": "babel-core",
  "concatenatedName": "babelcore",
  "downloadsLast30Days": 10978749,
  "downloadsRatio": 0.08310651682685861,
  "humanDownloadsLast30Days": "11m",
  "popular": true,
  "version": "6.26.0"
}
```
````

```jsonc
// comment
{
  "name": "babel-core",
  "concatenatedName": "babelcore",
  "downloadsLast30Days": 10978749,
  "downloadsRatio": 0.08310651682685861,
  "humanDownloadsLast30Days": "11m",
  "popular": true,
  "version": "6.26.0"
}
```

**Comment by Haroenv** [comment]
Didn't think of that, `json5 jsonc` will have to do then, since we can't really control directly what GitHub does unless we start contributing to linguist (slow)

**Comment by ikatyang** [comment]
Could you open an issue there to see what they think about it? Ideally it should be acceptable and easy to fix (i.e. add `.jsonc` to JSON5 extensions), if there's no luck, ` ```json5 jsonc ` should be the way to go.

**Comment by ikatyang** [comment]
Oops, it seems there also an `aliases` field available in linguist, which should be suitable for this case, I'll try to send a PR there.

**Comment by Haroenv** [comment]
https://github.com/github/linguist/issues/4153
