### ISSUE TITLE
Add diff in output of --list-different

### ISSUE THREAD

**Issue by pronebird** [prettier/prettier#4612]
Hi,

Currently `--list-different` only prints the filenames of files that aren't formatted. It would be great to add an option to print out a diff between current and formatted source.

Maybe an extra option like `--list-different --diff` that would affect the way `--list-different` works. I believe in any case `--list-different` runs formatter on the source code, so it shouldn't be too hard to run it through some `diff` tool and output a nicely colored code to console.

**Comment by ad1992** [comment]
@j-f1 can I take this up ?

**Comment by j-f1** [comment]
Sure, go ahead!

**Comment by martinsik** [comment]
I just encountered the same thing. It would be very helpful if I could see what exactly is different in the source and the re-formatted file.

**Comment by arnavb** [comment]
Any update on this issue by any chance? I'd also like to see this implemented, similar to how rustfmt does it.

**Comment by alex-arriaga** [comment]
This would be a great option to have, is there any news about it?
Thanks in advance.

**Comment by thorn0** [comment]
closing in favor of #6885
