### ISSUE TITLE
Call chains with short head identifiers again: does it work as intended?

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#4614]
So turns out [it was done](https://prettier.io/blog/2018/05/27/1.13.0.html#nicer-line-wrapping-for-d3-4285-by-1wheel-4505-by-duailibe) only for expression statements. Why not do this with all expressions?

**Prettier 1.13.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOgDYCGAnhAK4wAKBATjFgCoQASGAJnAAQC8H62O5DHlxoCWNFjgwAFAB0osmAH0cAM0IwAsgQAO0vrgBu2DACMhGGESYEorPHGpYANB1VRuAPjdRpASj95RUUcSCgwAhkDHGo4SGpWGLgsCDxDOFYlBwBzAjAiJWMsalIHLECFGBDVIXhqaQAhCFS4Wwq-AG55EGcQCB0YDGgsZFAaaggAdypYqBGUAkMINh6QU2o8gGspAGUdPIwobOQYErhew8laCg3sgFsCZFUCYXOQACssAA8GjbBtmA7Ah3OAAGUOcCeL0kvX2TkcyDWBFMRDw0FWOmohxgAHU2OhkAAOAAMsImkhxGx0iMxyUc6VWsQAjqQMLEbgR7o8kM9Xr1JHcMCczvzDtkHABFUgQeBQvmoZF41gEpAAJl6pwIFiOAGEIHcHoioNBIb1SJJ6Mj5rzJABfW1AA)
```sh
--parser babylon
```

**Input:**
```jsx
this.layoutPartsToHide = this.utils.hashset(
	_.flatMap(this.visibilityHandlers, fn => fn())
		.concat(this.record.resolved_legacy_visrules)
		.filter(Boolean)
);

```

**Output:**
```jsx
this.layoutPartsToHide = this.utils.hashset(
  _
    .flatMap(this.visibilityHandlers, fn => fn())
    .concat(this.record.resolved_legacy_visrules)
    .filter(Boolean)
);

```

**Expected behavior:**
```jsx
this.layoutPartsToHide = this.utils.hashset(
  _.flatMap(this.visibilityHandlers, fn => fn())
    .concat(this.record.resolved_legacy_visrules)
    .filter(Boolean);
);
```

**Comment by ikatyang** [comment]
In the initial implementation (#4285) we apply it everywhere, but we found that it shouldn't be applied to some places (#4467) so we limited it to only in `ExpressionStatement`, but sure, we should apply the same rule to the case you mentioned above, it's just not easy to figure out all the cases.

**Comment by j-f1** [comment]
Is there a way to find out if a certain node is printed at its indentation root? If so, we could check that and avoid breaking.
