### ISSUE TITLE
Webpack magic comments in import() statements look ugly and potentially break

### ISSUE THREAD

**Issue by mikegreiling** [prettier/prettier#4617]
Webpack allows for special comments within dynamic `import()` statements to effect the way in which it statically analyzes, splits, and names its bundles.  The comment block must be within the parens of the import function, and this tends to look somewhat ugly after they are run through prettier.

Here are several examples of my attempts to reconcile prettier reformatting with webpack import comments.

In most cases the easiest option is to keep everything in one line, but with multiple webpack options this can run rather long and it can look nicer to break these webpack comments onto separate lines, as in examples 2-4.

Note that **example 4 actually breaks the functionality entirely** by moving the comments outside of the function!

ref: https://webpack.js.org/api/module-methods/#import-

**Prettier 1.13.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEcAHgIYC2ADgDZwCMAFAJT7AA6U++OlEATjPQD0AKnwB3OACMKJMAGsAwgAtMcgHLk4SfKxBkAngFowKqHMNRNugDTipM+QFkIAEy06QVEgC99u-MKC+AAGAHSCVBBgJDSCACTAXlAA5ugkyXAAvsGMoTBKCPRkrug0+AC8AHz4xS6lcKFuqCSlAoyMANzsmezsGFi4BMTk1HAATEws7JzcFHwC05z4InbSsnIAklhU6G7agqysoQBWAM7QcUGBi5wrEmvyAKJEYDt7y4ehUBCz859nFyuBw4Szu9nWylUGjI7l0BmMpnMlhh-muINuonuDjkzneui8vlRwKWIXCkWisQSSVS6SywUWuXyhVq9Qq1RZNEacGarSYnW6vSg-WweA4w0oNAAzJM2CDfvwhMIbqtsVtXrt3AcjgCoJdrMqsetnur3lqvj8ePx-uddYJ9eiVRDEdDYXojCZVBYrCB7STDU5XK6CX4QMq0SSwhEojE4PFEiQUmkMtkGXkClAiiUylUalmGk0WlQ2vyoD0oH1MCKhqQJXAACwyxbyhYOyPkmNx6lJunKsEPRTOzTaOHuxFelEgALE0GY8EBvGeHwhqeppkZjlwNm5uqcgu89pdUuCn0gCAUQZQU7IUAkXi8CBiAAKt4QV5QJAAbj8XCfJLx1nAMAAMoODgKTIDAvDoHA1ggGBpxwPwj7-skZAkMgzRUAhsFnEQABC-7yIBQGaAAMmBcAYTE2EgDIvAIbwyAgJIJCSPokRQCeFC8GBMAAOo4C4+TIAAHAADLB3EQAhfH-hQTHcXADEfpRsG8HAACO6A4OpyHpGhVFYTBIAIWQOAQVBxmnGByQ0AAiugEDwIZNEwKxAlCUoyBjLBkEkDgVA2QoEBkAZKDfFAqkgOgCEACqsW+mEIZkmRAA)
```sh
--parser babylon
```

**Input:**
```jsx
function example1() {
  import(/* webpackChunkName: "my-chunk-name", webpackMode: "lazy" */ `./locale/${language}`).then(module => module.default());
}

function example2() {
  import(
    /* webpackInclude: /\.json$/ */
    /* webpackExclude: /\.noimport\.json$/ */
    /* webpackChunkName: "my-chunk-name" */
    /* webpackMode: "lazy" */
    `./locale/${language}`
  ).then(module => module.default());
}

function example3() {
  import(/*
    webpackInclude: /\.json$/,
    webpackExclude: /\.noimport\.json$/,
    webpackChunkName: "my-chunk-name",
    webpackMode: "lazy"
    */
    `./locale/${language}`
  ).then(module => module.default());
}

function example4() {
  import(
    `./locale/${language}`
    /* webpackChunkName: "my-chunk-name" */
    /* webpackMode: "lazy" */
  ).then(module => module.default());
}


```

**Output:**
```jsx
function example1() {
  import(/* webpackChunkName: "my-chunk-name", webpackMode: "lazy" */ `./locale/${language}`).then(
    module => module.default()
  );
}

function example2() {
  import(/* webpackInclude: /\.json$/ */
  /* webpackExclude: /\.noimport\.json$/ */
  /* webpackChunkName: "my-chunk-name" */
  /* webpackMode: "lazy" */
  `./locale/${language}`).then(module => module.default());
}

function example3() {
  import(/*
    webpackInclude: /\.json$/,
    webpackExclude: /\.noimport\.json$/,
    webpackChunkName: "my-chunk-name",
    webpackMode: "lazy"
    */
  `./locale/${language}`).then(module => module.default());
}

function example4() {
  import(`./locale/${language}`)
    /* webpackChunkName: "my-chunk-name" */
    /* webpackMode: "lazy" */
    .then(module => module.default());
}

```

**Expected behavior:**

1. Comments within function call parens should never be moved outside of the parens.  They were likely there for a reason and this can break expected behavior by other static analyzers that use comments to denote directives (e.g. webpack, istanbul, eslint, etc).

2. Comments within function call parens should be allowed to preserve leading whitespace.  e.g.

    ```javascript
    func(
      /* foo */
      bar
    );
    ```
    should not become
    ```javascript
    func(/* foo */
      bar
    );
    ```

3. Params within function calls that have embedded comments should still be indented properly.

    ```javascript
    func(
      /* foo */
      bar
    );
    ```
    should not become
    ```javascript
    func(
      /* foo */
    bar);
    ```

**Comment by evilebottnawi** [comment]
Looks we have bug
```
function example4() {
  import(
    `./locale/${language}`
    /* webpackChunkName: "my-chunk-name" */
    /* webpackMode: "lazy" */
  ).then(module => module.default());
}
```
to
```
function example4() {
  import(`./locale/${language}`)
    /* webpackChunkName: "my-chunk-name" */
    /* webpackMode: "lazy" */
    .then(module => module.default());
}
```

**Comment by lydell** [comment]
Possibly good to keep in mind while fixing: #2853 #1489

**Comment by noahsug** [comment]
I've put up a PR that fixes this issue: https://github.com/prettier/prettier/pull/6025
