### ISSUE TITLE
Remove formatting options from CLI

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#4622]
Now that we have an established configuration file interface and infra, we should consider removing the support of formatting options passed in the CLI and only read them from config.

There's a lot of complexity to deal with them in `cli/utils.js`, `main/option.js`, and I think there's a chance to remove lots of code and makes things simpler. We're getting to a point where it's difficult to refactor anything in CLI and things are unpredictable.

I can't personally see an use case to prefer CLI args over config files, but more importantly, we should encourage this, specially when people are also using Prettier in Git commit hooks, Editor integrations, ESLint integrations and should rely on the config to keep everything in sync.

**Comment by suchipi** [comment]
Sounds good to me, but it's obviously a breaking change, so it'd have to be 2.0.

**Comment by duailibe** [comment]
Yep, I had a **[BREAKING]** in the issue title but it seemed to aggressive 😅

**Comment by bakkot** [comment]
Strongly disagree with this, personally. I quite frequently use prettier to format random files which are not part of any project and therefore have no associated config file. Sometimes even on systems I which don't have a persistent prettier install, like VMs, using `npx`.

**Comment by suchipi** [comment]
Maybe the fix is to refactor the CLI so that all the various things called "options" have different names

**Comment by duailibe** [comment]
Yeah maybe we can just refactor the CLI so the code looks better, but it's still a "feature" we have to maintain.

> I quite frequently use prettier to format random files which are not part of any project and therefore have no associated config file

@bakkot I do that too, but in those cases I just go with the defaults, since I don't care about those random files (if I did I'd write a config file). I'm not convinced this use case is worth maintaining this feature.

It seems to me we have those options on CLI for historical reasons, when we didn't want to support config files. Maybe that would be different if Prettier had started with support for config file from day 1.

**Comment by suchipi** [comment]
I think we need a better reason than "the code is hard" to remove features, even if we do it as a major version bump. The only safe assumption is that everyone is using every feature you've released so far

**Comment by duailibe** [comment]
> I think we need a better reason than "the code is hard" to remove features

I disagree but that's fair

**Comment by duailibe** [comment]
I don't think that's gonna happen
