### ISSUE TITLE
Trailing comma causes TypeScript 2.9 compilation error

### ISSUE THREAD

**Issue by srmagura** [prettier/prettier#4624]
Under certain difficult-to-predict circumstances, Prettier will add a trailing comma in TypeScript "binding patterns" (e.g. `const [x, y] = [1, 2]`) when --trailing-comma is es5 or all.

When this happens, TypeScript 2.9 will give the error "A rest parameter or binding pattern cannot have a trailing comma". This was a breaking change from 2.8 to 2.9.

Some related but slightly different issues: #3673 #3311

**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaXedGACgEpdgAdKAGzhlwHc44BrAMqEAtsNQAnTC3acADuIgArOGBgARVJjUdUpVumkdcqVqwCC6dKQDmUOABMzq0gDdSMTAEl7BtkYBGeqykUNYASqhUhpzicACOhHDUSMZQUlAsANo8-EKiEpgANPJKKuqa2jC6+oUm5pY2do7Obh7e6IWBpiHhkUkAurgAvMZcujHxidQsAL4ghSAQsmTQ6MigEgpcAAoSCGsoqC4QpPbzIP7iqGB8HAKy1z3IMOKJCyHocOIw21fWYsh8CZPgtFOgAB4AISuNzuqGEcAAMiE4IDgXAFg9xJ9xMgQB5ZEkwOJSMtzvIQjAAOqnGAAC2QAA4AAyYhSfKlXWR4+RJL4uVELWIJUixX6of6oNH6DEgT7CUjPV6yqyhdgARUIEHg0pB+NQ-hp9npyAATAsXtUegBhCD5PF1c6ET4AFQNByBMpmMyAA)
```sh
--parser typescript
--trailing-comma all
```

**Input:**
```tsx
async function test() {
let weekSummary
let projectDayDetails
let allAssignedActivityIds
let billingRates
let request: any

[weekSummary,projectDayDetails,allAssignedActivityIds,billingRates] = await request
}
```

**Output:**
```tsx
async function test() {
  let weekSummary;
  let projectDayDetails;
  let allAssignedActivityIds;
  let billingRates;
  let request: any;

  [
    weekSummary,
    projectDayDetails,
    allAssignedActivityIds,
    billingRates,
  ] = await request;
}

```

**Expected behavior:**
No trailing comma after billingRates.

**Comment by ikatyang** [comment]
I think the trailing comma there should be allowed, tracked in Microsoft/TypeScript#24628.

**Comment by nickmccurdy** [comment]
As far as I'm aware this is an intentional change in TypeScript, I doubt they'd change it back.

**Comment by hawkrives** [comment]
@nickmccurdy IIRC, that's for rest parameters - e.g., 

```ts
[
  a, 
  b, 
  ...c,
] = data
```

 is invalid, but 

```ts
[
  a, 
  b, 
  c,
] = data
```

should still compile.

**Comment by nickmccurdy** [comment]
I see, that issue seems to be Microsoft/TypeScript#24628.

I think I'm having a different issue with trailing commands, and I'm not sure if it's because of Prettier or TypeScript. Using Prettier 1.13 and TypeScript 2.9.1, Prettier adds the last trailing comma inside this generic and TypeScript errors with `Trailing comma not allowed.`

```ts
export interface ButtonBaseProps<C>
  extends StandardProps<
    React.AnchorHTMLAttributes<HTMLElement> & React.ButtonHTMLAttributes<HTMLElement>,
    ButtonBaseClassKey,
  > {
```

**Comment by duailibe** [comment]
@nickmccurdy Can you open a separate issue for that, please?

**Comment by michaeljota** [comment]
The issue in TS seems to being closed after Microsoft/TypeScript#24672 is merge. So, it was an issue with TS after all. 👍

**Comment by ikatyang** [comment]
Fixed in Microsoft/TypeScript#24672 thanks to @bakkot!

**Comment by vaskevich** [comment]
As a workaround for anyone who stumbles into this issue, you can just append `// prettier-ignore` to an offending line and Prettier will not add a trailing comma there to satisfy TS.

**Comment by mscottx88** [comment]
This also happens to object destructure statements with default values.

To follow up on @vaskevich response, here is a clear picture of what to do to make both prettier and tslint happy in this situation:

```
      ({
        itemWorksheetRequestId: afterRequestId,
        // Typescript compiler error https://github.com/Microsoft/TypeScript/pull/24672
        // tslint:disable-next-line:trailing-comma
        skipOccurred = false // prettier-ignore
      } = await findAndProcessNewRequest({
        afterRequestId,
        client,
      }));
```

**Comment by ikatyang** [comment]
FYI, [TS 3.0](https://github.com/Microsoft/TypeScript/releases/tag/v3.0.1) just got released.
