### ISSUE TITLE
Space indents are included although I use `--use-tabs` option

### ISSUE THREAD

**Issue by lazex** [prettier/prettier#4626]
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAI0wD5MAGAHSkpgHo7MAPFl62gfmffsYE8BAnkkx9qIADQgIABxgBLdMlDYATqogB3AApqEaZCGwA3CPIAmkkIVXYwAazgwAyjLvyoAc2QxVAVzgpDzQ4VRhtW08AW2xkADNsABsQqQArNCYAIVsHJ2dsKLgAGQ84eKSUkDdVENVDQmxCPkToKxlVDxgAdQsYAAtkAA5yKXaIEK7bGUN2uFrjMqlVOABHP3lliOxo2KQE5MCQEKj5H39DtA9PRLgART8IeHKDqRhGnvN+5AAmV9t5RJXADCECiMUMUGgixAfhCABVGgYkL4AgBfVFAA)
```sh
--parser babylon
--use-tabs
```

**Input:**
```jsx
const a = b > 0
	// xxxxx
	? x
	// yyyyy
	: y

```

**Output:**
```jsx
const a =
	b > 0
		? // xxxxx
		  x
		: // yyyyy
		  y;

```

**Expected behavior:**

I use `--use-tabs`.
But, output code has space indents.

Expected output is same as input code or 

```
const a =
	b > 0
		? // xxxxx
			x
		: // yyyyy
			y;
```

**Comment by lydell** [comment]
Hi! I think you'll find the answer in #4199. In short, Prettier uses tabs for the indentation and a few spaces for alignment, and this is not likely to change. Thanks!
