### ISSUE TITLE
Typescript Casting, places a semicolon on the start of the line (I am using no semi colon)

### ISSUE THREAD

**Issue by appsolutegeek** [prettier/prettier#4630]
I know its the case to put semicolons at the start of the line in certain cases but I am only casting. This should be transparent - shouldn't it ?

Is there any fix or even a workaround ?

**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwBkIBzMuHAMQEMwZcBPfAX3wDMcJ18ByAHQCA9AGccYYQBtylHAFoO9RjiZ8AOlAzY8hErKptO3XoJHjJMilQ1RNmgCZxRYHKgBGcABR9S1msrMfAA0+F4AlPgAvAB8hJr4+FJwBKhQojC0UGBwSPr+dAzM9lCJnhy4cACi9AAWXhHRccAJiWF+cvi0ovgAshBgANYAPB1UMeEC6AODAMLJtDgRJW34aRlZOdH4UHAA7vlyhSpMy6Vs4Sv4Ti5unj4ClDBjS+EhYZGx8eeJqDA+AEkemBaFJkg58HAAB7KKQsaA5d7dJjZD5Nb6rRLJAhWTpRNbpTLZOCPFIvM6tVa0Pa0P6QqGYOAMLwvSaMAAStAAbnAAEJwBCzUHggAqGGcXgAjJc7D82tTaQRoYzmbiqGyIPyACJwDhpOAOM6rVgyxImzTmqAgYIgCCYGCoaCiZCgRbcPYABUWCGdKG5EFQDmtIHcOHogxSAGVMPQ0mRkDAcABXOA29ZUGAesNkdC0ZBKKSiVMgABWoihvLDQyjtHQcGI+vzoKLNpjOCLOGQIBgTEZt1Q9uDmDcsAA6oGYLVkAAOAAMre4RdHYcwXeHzioPODODgAEck6gd1naDm80gCy2QEX0Kgm4Xi6I48kAIpJiDwBPJ4uZdzjhyT5AACYbUTWkpDjWYeFzLsoGgOBgyTIsRVodxfQvOBWFYIA)
```sh
# Options (if any):
--single-quote
--no-semi
```

**Input:**
```typescript
  beforeEach(() => {
    (Logger as Mock<Logger>).mockClear()

    instance = new LoggerFactory()
  })
```

**Output:**
```typescript
  beforeEach(() => {
    ;(Logger as Mock<Logger>).mockClear()

    instance = new LoggerFactory()
  })
```

**Expected behavior:**

I was expecting the casting line without the start of the semi-colon on the line.

**Comment by lydell** [comment]
Just in case you haven’t seen it, here’s the rationale for the semi-colon: https://prettier.io/docs/en/rationale.html#semicolons

You should be able to use [prettier-eslint](https://github.com/prettier/prettier-eslint) if that semi-colon bothers you much.

**Comment by appsolutegeek** [comment]
Thanks for the reply. Yes, actually it didn't bother me too much, although TSLINT complains that there is a semicolon and there shouldn't be.

I suppose both tools are not aligned, I suppose I can disable my tslint rule although then it wouldn't warn me if i placed a semicolon at the end of a line.

**Comment by appsolutegeek** [comment]
Oh, there is a sort of workaround to stop the insertion of the semicolon when casting, placing the link here for others.

https://github.com/palantir/tslint/issues/2793

**Comment by lydell** [comment]
@appsolutegeek It’s better to use https://github.com/alexjoverm/tslint-config-prettier to disable conflicting rules.
