### ISSUE TITLE
Less backticks breaks after formatting

### ISSUE THREAD

**Issue by arv** [prettier/prettier#4634]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAAgWwIYGcDWAygG4DmAqgE4A2SqABusDgQJI6lxXUC+AdJTgAHatjBwAFAHoJ6AEwAPAJQB+ADpq+AbQB6fALoBqACRSANKjUg+uMgGIW+K0voBuEGZAQhMAJbRcZFBsSkoIAHcABRCEQJRsYghfABMPEAAjSjF8OBhCITFfKFJkGEoAVzhPItw4ShhIrNIcZAAzbGpazwArXAUAISywHLzsTDgAGSK4No6ukALKWspkEGo4XEDPIUoimAB1FJgAC2QADgAGbbDa-ayhVZ2NuuIZz0EAR3LfQUbsZuws06VRAtUwvlKFRBuCKpHWAEVyhB4ED5jBsOlDskTsg5J4ythfNRYQBhCCYFooKDQN4gcq1AAqGLi7WBPB4QA)
```sh
--parser less
```

**Input:**
```less
 @maskSvgUrl: `@{maskImageUrl}.replace(/(@2x)?\.[^.]+$/, ".svg#mask")`;
```

**Output:**
```less
@maskSvgUrl: ` @{maskImageUrl}.replace(/(@2x) ?\.[^.] + $/, ".svg#mask") `;

```

**Expected behavior:**

Everything in a backtick is JavaScript code and either needs to be left intact or formatted using JS rules. In this case the RegExp.

**Comment by evilebottnawi** [comment]
@arv it is possible use `js` inside in `less`? Can you provide link on documentation?

**Comment by evilebottnawi** [comment]
@arv it is `Deprecated`, i think better avoid using `js` inside `less`. Most likely this will never be supported in `prettier`.

**Comment by j-f1** [comment]
To get this working with Prettier right now, you can put `// prettier-ignore` on the line before it:

**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSgAEBbAQwGcBrAZQDcKBVHABskGAAYNgrTgElWFOIKEBfAHR4sQlmDgAKVLoYAmAB4BKAPy1aqgNoA9VQF0A1ABJUAGgy0QqtnwAxNIcvmZiANwgniAQWETQbMigLDg4EADuAAqpCEkoLDwQhAAm0SAARjjaHPhcWNqEUBTIMDgArnAxTWwkMFnVFKzIAGYsQr0xAFZsJgBC1WC1MFwsTHAAMk1wo+OTIA04vTjIIEJwbEkxuE0wAOqlMAAWyAAcAAzX6b131VinuAuJB4OxieAAju1CHgBiwhixdhMuiBekxCK0Osi2E0KOcAIrtCDwRH7GAsCoPErPZBGGJtFiEIQ4gDCECYwxQ1CgoJA7V6ABVyfkxkjlMogA)
```sh
--parser less
```

**Input:**
```less
// prettier-ignore
@maskSvgUrl: `@{maskImageUrl}.replace(/(@2x)?\.[^.]+$/, ".svg#mask")`;
```

**Output:**
```less
// prettier-ignore
@maskSvgUrl: `@{maskImageUrl}.replace(/(@2x)?\.[^.]+$/, ".svg#mask")`;

```

**Comment by arv** [comment]
@evilebottnawi Fair enough. We are OK with using `/* prettier-ignore */` for now.
