### ISSUE TITLE
Illegal trailing commas in multi-line TypeScript generic parameters using Babylon parser

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier#4641]
Using Prettier 1.13 and TypeScript 2.9.1, Prettier adds a trailing comma after ButtonBaseClassKey. TypeScript 2.9 errors with `Trailing comma not allowed`, which is a new breaking change. It works if I remove the trailing comma option (defaults to none) or use the TypeScript parser (which I'd prefer not to as I'm contributing a change to a project that uses the Babylon parser). This issue is also specific to when the interface signature is long enough to break the generic parameters onto separate lines from the angle brackets, when they're on one line a trailing comma is not inserted as expected.

**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPAIQFcYZobyBnOABWwg1YB0oePOnhQAJqzwBlGOXHlsYrj1YAeAUKEAlOJRgA6AIJQwACxwAJACoBZADKHG2AgCMGcNdfsBRADZwAWwQYAD48ADI8HT19ekZoLwcnV3dPWzs-QOCQgBoNTTimKBZ2AGFfNlYAaTgAT3yw4ABfARAckB4YAmhWZFAFbgB3DgUEXpRyADcIAjE2kBdsSgBrOBgpDEoiAHNkGGw6OHaidlwucm2A8mQKX3Z2gCtWNBolsFX18iC7Ijg9g6OIE22FOyAW5BctV80HmGGcsAA6rMYKZkABGAAMGPacIg7ARSwwYLhHhIkz+7WwcAAjnQCFTzpdrkhbvcQOwAgR-od2qwdv4AIp0CDwbmA2QuJFiFHIABM7X25AIvh2pQgASuYPIvl88zo7CsEPGrLgTSaQA)
```sh
--jsx-bracket-same-line
--parser babylon
--print-width 100
--single-quote
--trailing-comma all
```

**Input:**
```jsx
export interface ButtonBaseProps
  extends StandardProps<
    React.AnchorHTMLAttributes<HTMLElement> & React.ButtonHTMLAttributes<HTMLElement>,
    ButtonBaseClassKey
  > {}

```

**Output:**
```jsx
export interface ButtonBaseProps
  extends StandardProps<
    React.AnchorHTMLAttributes<HTMLElement> & React.ButtonHTMLAttributes<HTMLElement>,
    ButtonBaseClassKey,
  > {}

```

**Expected behavior:**
Trailing comma should not be added, as it is illegal in TypeScript 2.9.

**Comment by j-f1** [comment]
The `babylon` parser parses this as Flow, not TypeScript.

**Comment by nickmccurdy** [comment]
Oops I didn't think about that, thanks for the info. This is a .ts file so I would expect Prettier to use TypeScript, but the project I'm contributing to manually sets `parser: 'babylon'` in its config. Should I remove this parser line as recommended here? https://github.com/prettier/prettier/issues/4633#issuecomment-394515607

**Comment by suchipi** [comment]
@nickmccurdy Yes

**Comment by nickmccurdy** [comment]
Thanks, this fixes my issue. I'll close this since it was a configuration issue and I never intended to use the Flow parser to format TypeScript. Now following #4638.
