### ISSUE TITLE
Prettier: File package.json has unsupported type

### ISSUE THREAD

**Issue by maketroli** [prettier/prettier#4642]
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm0gM5gBOAlgA4x65KbpbY4gCGpxVDUEAJnJoYzMSgBzPAEEACgEkAdACtKIADQZ6DAGYRCAW35tcpQnBgC4hTAFpzAdxLwL5vIKEAbOOYCOAVwh3LBwTDWxJwwABYAvACMAEwADPakjIR4puFqzhBW9jCMAEZBIREALDhouPIA9ABUVdXSwPKK8gAeAL5luLjKdNi4zgF6IHB4-bCYNXUNeE14bfZexEaddK3dvSDcpAjcUGCLCtS0qriMzcQQBwyx0pEAbDddKvS4uXlwzuakzp5CguacAE8oIwtMQwOZiFpSJpAlY4LlEmAANaDSLSa6RR49BivXLvT7fX5QcwwPhQPAabT-OCQPgwTR4cyuISMMAA1HSADM0iKWOOIFx+MMvzw8EIg3u0SKDyUT3WkChhjwjmgHMlfOe4AZg2i0gAHFyNes4M0DMNLrhpZEAKyG2XY3AuCCvZyDAB60u50SNDAynEYeFCgytAHYeT79IZWTBBga0bEIyAzdHzArEjHkAxuXd0YmDBBSCSAVsLSAbdJbZEE-b+VGwBnqLhy7beTXNXXAoxOJxoIytoQ1KiW9JvW31h3-hAtEOK+GxwwJ4ZOJ5moNbddrYnFxBPGLJ9PM5abjK1u24MvV4eQNz7tXT+PzyuSaFPFAUVfdbq73KGKKAa5OFTKdoSgBAKB1dFc3nXA4QRVl30bEBdXuTFoJAWDESRakADdzFBbtXCsJI4A5KsR0TDD4PMUIfDw4JOEI4iIMiA1qyeVYnlwbhsIAETgLYoB2PZhjYI5NUFD5aRIq9JStRMJPMYZRgbBgw11Tl5LeD4Mi7UxBjDa5vwdAUtIJH4-kBYFQXBSFoUIQIOG4DlrlHe8cVMr5zOJPAgRyZp-iBEEwQhKEYQlG5WM0vEPk8okSTJClNC0VNnADPtCALUwTFLWSTx-F4PMJP5SUYclKWS4Y4htPCuE8VxGQVLRoHkcKpTy4yFLNFJAgQbCOUrKL8S6oxzA7Vq5LQhAAC8AS0aTEN1A1XPyoYRgGK8PRuABOdr+SUgIgKgNRiCEcxGGIQhcigXIZwxRN9tgQ7jtOs1jEWcUP2PVC3NwB7AkgI6TtGuBo1I6QQ3utbHp07gPsQtEw2+la-rMuL0kyCDoh2pHjJR2K-nRqwYGLeaGHU7kjL2qHAnx4lbLCz6Kch5TUb+FozsiSJ2Svdc7R+1aWdpz5DDevTPrRHGqcForiTGq8DN2zVCfMXJBEGa4igMxNZGGFTcDiSDW35nXRQcUxiEYfoptMRSoBmubnKg-mmrOC51Z5J2VscuAmqgUj4zzEWTDhhgJe5I2VonGjAhhsXEIp9EVaMRhpFuLcQfrEldeBwTTDj0PbRbCj4UwnCzcIbD8-1j3NxAdjT1wKzSdwNNXHgCFYAykkIGB0G21wSvknOP2rwTymGG4AgSHIYfBlETAAGFgLbnhJE7iBMHpTAACUM5gTArE0JFAwLDVcB0NWrxSCvTDkBQG5AQxoUcelCG5xDfhgAABT+X1yaQFRIFyGECAzgYAVFbkYNwAQu70l7vWaQn8z5MF3DREOuAABCJBSqYAABKgP3gAHmATRMBP8L7OAAVOAAfMg-oYAEApEGAAWUkAAFWWO0KASgQAFgEL2ZAoAkgZSsOIYi5JkBMGwhAYIPDch8GREYAAyoiJwyBSSeDgIoEAghr4wHEHwIQOhkBqEtikbRLQsHwWUSCOAAAZQQcATFmK0UmJI19JG4n-NAHh-hYAAHVghhGQHqWI2j8wpH8XwUgkjho3x4YYBYhgDGMCMYwZxzhzH4B9sQdRhBNHaMcMIVwABFbw8AMlZJyLkQJhRkDRG0SVYgowhBLy0MYlAHBQI8M8CkNheQ8CVLgK0VoQA)

**Input:**
```jsx
{
  "scripts": {
    "api": "node ratingsAPI.js",
    "format": "prettier --write --single-quote --print-width=120 --parser=flow --tab-width=4 \"js/**/*.{js,jsx}\"",
    "lint": "eslint **/*.{js,jsx} --quiet"
  },
  "dependencies": {
    "axios": "0.16.1",
    "babel-plugin-dynamic-import-webpack": "1.0.1",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-register": "6.24.1",
    "compression": "1.6.2",
    "cors": "2.8.3",
    "express": "4.15.3",
    "global": "^4.3.2",
    "lodash": "4.17.4",
    "preact": "8.1.0",
    "preact-compat": "3.16.0",
    "prop-types": "15.5.10",
    "react": "15.5.4",
    "react-addons-perf": "15.4.2",
    "react-dom": "15.5.4",
    "react-redux": "5.0.5",
    "react-router-dom": "4.1.1",
    "redux": "3.6.0",
    "redux-thunk": "2.2.0",
    "styled-components": "2.0.0",
    "webpack": "2.6.1",
    "webpack-dev-middleware": "1.10.2",
    "webpack-hot-middleware": "2.18.0"
  },
  "devDependencies": {
    "babel-core": "6.24.1",
    "babel-eslint": "7.2.3",
    "babel-loader": "7.0.0",
    "babel-plugin-dynamic-import-node": "1.0.2",
    "babel-plugin-syntax-dynamic-import": "6.18.0",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "6.24.1",
    "babel-preset-env": "1.5.1",
    "babel-preset-react": "6.24.1",
    "enzyme": "2.8.2",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "15.0.1",
    "eslint-config-prettier": "2.1.1",
    "eslint-config-react": "1.1.7",
    "eslint-loader": "1.7.1",
    "eslint-plugin-flow": "2.29.1",
    "eslint-plugin-flowtype": "2.33.0",
    "eslint-plugin-import": "2.3.0",
    "eslint-plugin-jsx-a11y": "5.0.3",
    "eslint-plugin-prettier": "2.1.1",
    "eslint-plugin-react": "7.0.1",
    "flow-bin": "0.47.0",
    "jest": "20.0.4",
    "jest-serializer-enzyme": "1.0.0",
    "moxios": "0.4.0",
    "nodemon": "1.11.0",
    "prettier": "1.13.4",
    "react-hot-loader": "3.0.0-beta.6",
    "react-test-renderer": "15.5.4",
    "webpack-dev-server": "2.4.5"
  },
  "name": "complete-intro-to-react",
  "version": "3.0.0",
  "description": "A Complete Intro to React workshop",
  "main": "server.js",
  "repository": "git@github.com:btholt/complete-intro-to-react.git",
  "author": "Brian Holt <btholt@gmail.com>",
  "license": "MIT"
}
```

>Error: Prettier: File package.json has unsupported type

**Expected behavior:**
Format json file properly.

In the playground; 2nd line it throws an error:
>SyntaxError: Unexpected token, expected ";" (2:12)

**Comment by duailibe** [comment]
In the playground, you need to specifiy which parser to use: see [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm0gM5gBOAlgA4x65KbpbY4gCGpxVDUEAJnJoYzMSgBzPAEEACgEkAdACtKIADQZ6DAGYRCAW35tcpQnBgC4hTAFpzAdxLwL5vIKEAbOOYCOAVwh3LBwTDWxJwwABYAvACMAEwADPakjIR4puFqzhBW9jCMAEZBIREALDhouPIA9ABUVdXSwPKK8gAeAL5luLjKdNi4zgF6IHB4-bCYNXUNeE14bfZexEaddK3dvSDcpAjcUGCLCtS0qriMzcQQBwyx0pEAbDddKvS4uXlwzuakzp5CguacAE8oIwtMQwOZiFpSJpAlY4LlEmAANaDSLSa6RR49BivXLvT7fX5QcwwPhQPAabT-OCQPgwTR4cyuISMMAA1HSADM0iKWOOIFx+MMvzw8EIg3u0SKDyUT3WkChhjwjmgHMlfOe4AZg2i0gAHFyNes4M0DMNLrhpZEAKyG2XY3AuCCvZyDAB60u50SNDAynEYeFCgytAHYeT79IZWTBBga0bEIyAzdHzArEjHkAxuXd0YmDBBSCSAVsLSAbdJbZEE-b+VGwBnqLhy7beTXNXXAoxOJxoIytoQ1KiW9JvW31h3-hAtEOK+GxwwJ4ZOJ5moNbddrYnFxBPGLJ9PM5abjK1u24MvV4eQNz7tXT+PzyuSaFPFAUVfdbq73KGKKAa5OFTKdoSgBAKB1dFc3nXA4QRVl30bEBdXuTFoJAWDESRakADdzFBbtXCsJI4A5KsR0TDD4PMUIfDw4JOEI4iIMiA1qyeVYnlwbhsIAETgLYoB2PZhjYI5NUFD5aRIq9JStRMJPMYZRgbBgw11Tl5LeD4Mi7UxBjDa5vwdAUtIJH4-kBYFQXBSFoUIQIOG4DlrlHe8cVMr5zOJPAgRyZp-iBEEwQhKEYQlG5WM0vEPk8okSTJClNC0VNnADPtCALUwTFLWSTx-F4PMJP5SUYclKWS4Y4htPCuE8VxGQVLRoHkcKpTy4yFLNFJAgQbCOUrKL8S6oxzA7Vq5LQhAAC8AS0aTEN1A1XPyoYRgGK8PRuABOdr+SUgIgKgNRiCEcxGGIQhcigXIZwxRN9tgQ7jtOs1jEWcUP2PVC3NwB7AkgI6TtGuBo1I6QQ3utbHp07gPsQtEw2+la-rMuL0kyCDoh2pHjJR2K-nRqwYGLeaGHU7kjL2qHAnx4lbLCz6Kch5TUb+FozsiSJ2Svdc7R+1aWdpz5DDevTPrRHGqcForiTGq8DN2zVCfMXJBEGa4igMxNZGGFTcDiSDW35nXRQcUxiEYfoptMRSoBmubnKg-mmrOC51Z5J2VscuAmqgUj4zzEWTDhhgJe5I2VonGjAhhsXEIp9EVaMRhpFuLcQfrEldeBwTTDj0PbRbCj4UwnCzcIbD8-1j3NxAdjT1wKzSdwNNXHgCFYAykkIGB0G21wSvknOP2rwTymGG4AgSHIYfBlETAAGFgLbnhJE7iBMHpTAACUM5gTArE0JFAwLDVcB0NWrxSCvTDkBQG5AQxoUcelCG5xDfhgAABT+X1yaQFRIFyGECAzgYAVFbkYNwAQu70l7vWaQn8z5MF3DREOuAABCJBSqYAABKgP3gAHmATRMBP8L7OAAVOAAfMg-oYAEApEGAAWUkAAFWWO0KASgQAFgEL2ZAoAkgZSsOIYi5JkBMGwhAYIPDch8GREYAAyoiJwyBSSeDgIoEAghr4wHEHwIQOhkBqEtikbRLQsHwWUSCOAAAZQQcATFmK0UmJI19JHyGgA4UkThiBqABDw-wsAADqwQwjID1LEbR+YUghL4KQSRw0b48MMAsQwBjGBGMYM45w5j8A+2IOowgmjtGOGEK4AAit4eAuT8k5FyGEwoyBojaJKsQUYQgl5aGMSgDgoEeGeBSGwvIeA6lwFaK0IAA)

**Comment by duailibe** [comment]
@johntran of course, since this is not a JS file. Why would you use the babylon parser for a non-JS file?

**Comment by johntran** [comment]
@duailibe In `1.12.1`, I was able to use babylon to parse json files. Allowing bablyon to parse JSON is great for IDE's that auto-format on save. I am not aware of any extensions that allow different parsers based on file extensions.

The error caught me off guard but I ended up setting different prettier configurations for each file extension that will run on every git commit. Developers aren't able to use prettier on a "save" basis reliably, but the code is consistent in the codebase at least.

**Comment by suchipi** [comment]
@johntran if you are setting the parser in your prettier config, you do not need to. Prettier does this out of the box. It will do it on save, too.

**Comment by johntran** [comment]
@suchipi Ah got it. I should read the docs more :)

https://prettier.io/docs/en/configuration.html#configuration-overrides

**Comment by suchipi** [comment]
To be clear, you do not need to set the parser anywhere in your config file, even in configuration overrides. If this is all you have in your `.prettierrc`:
```json
{}
```

Then prettier will format `*.json`, `*.js`, etc files using the correct parser; it autodetects based on the file name or extension.
