### ISSUE TITLE
Unable to format HTML files, is this normal?

### ISSUE THREAD

**Issue by maketroli** [prettier/prettier#4643]
What steps will reproduce the problem?
1. command+shift+option+p on an html file

What is the expected result?
Format HTML/Markup

What happens instead?
This error: Prettier: File index.html has unsupported type

Please provide any additional information below.

I have this code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>svideo</title>
    <link rel="stylesheet" href="/public/style.css">
</head>
<body>
<div id="app"></div>
<script src="/public/bundle.js"></script>
</body>
</html>
```
In the screenshot you will see the paths where I'am grabbing Prettier from. I am unable to select any other path in the field Prettier Package. Even if I type it in, it changes the letters color to red.

![screen shot 2018-06-06 at 00 01 53](https://user-images.githubusercontent.com/8395866/41020203-25258842-691f-11e8-8d18-bfd508fedc34.png)

I am using the last version of Prettier and I have this in the package.json

`"scripts": {"format": "prettier --write --single-quote --print-width=120 --parser=flow --tab-width=4 \"js/**/*.{js,jsx}\""}`

So I just don't know why it keeps throwing the error `Prettier: File index.html has unsupported type` when I try to Prettier those type of files. For the rest of the files it works great.

**Comment by lydell** [comment]
Yes, this is normal. Prettier does not support HTML yet. See #1882.
