### ISSUE TITLE
Extra Line Break in Destructed Assignment of Ternary

### ISSUE THREAD

**Issue by yungsters** [prettier/prettier#4645]
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEwA6VOYBGEMMEAtkphAGY0DOGAQiWeQDR4Ho0xW0MMAGTi9O+TACcAlgHMAFn2p1GMAEpzF4gmQAO-FRgAqEXeIC+mALyZZGAAqS49emrhgYAeUNYrNqACuqKiYAPyYACIAogBiAIIAqkJGAPr2alEAypkpGQDCRphUdjCOzq7uXj4AFACUANwg7CCmMNLQ9MigAIaSkhAA7va9CJ0o3QBuENIAJk0ghJLdYADWGJm6y9JQssgwkgFwzduMkqVLsuTdyDTdqIzNAFb0AB5MS6vr3eRwQttwNzuDxAm0kp2QC26hAAnqhoPNdDJYAB1WYweTIAAcAAZmoiIIxkUtdBDEc44JIJgDmk4AI4BaRORzdS7XJC3e5HECMcjSPYHLn0baydAARQCJAB7KBXJgUNRM3RyAATM19t1pKhhXkKFcIVBoNSQAFGEYoWMOYxzOYgA)
```sh
--parser babylon
```

**Input:**
```jsx
let {
  bottom: offsetBottom,
  left: offsetLeft,
  right: offsetRight,
  top: offsetTop,
} = getPressRectOffset == null ? DEFAULT_PRESS_RECT : getPressRectOffset();
```

**Output:**
```jsx
let {
  bottom: offsetBottom,
  left: offsetLeft,
  right: offsetRight,
  top: offsetTop
} =
  getPressRectOffset == null ? DEFAULT_PRESS_RECT : getPressRectOffset();

```

**Expected behavior:**
```jsx
let {
  bottom: offsetBottom,
  left: offsetLeft,
  right: offsetRight,
  top: offsetTop,
} = getPressRectOffset == null ? DEFAULT_PRESS_RECT : getPressRectOffset();
```

**Comment by skevy** [comment]
@duailibe has there been any progress on this issue? This issue is impacting our rollout of Prettier at Airbnb.
