### ISSUE TITLE
Improve formatting of comments in JSX 

### ISSUE THREAD

**Issue by astorije** [prettier/prettier#4646]
(I looked in open and closed issues about this as I'm kinda confident it has been brought up before, but couldn't find a duplicate issue)

**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwD0AqABAFQBYCWAzlsVgIZaQC21CMFARhAK4Mx5xYBiEEVEagAdo9AHRYMaAL4AdKAB5e-NAD4A3PPnoM8rFgCCUACZYOZMpWosANjAI2CULjTqw9TVu05YAQuQAnAWFRWDF5KTlFfyC1dRAAGhAIIXtoImRQQICIAHcABUCEDJRyADcIAmNEkEYA8jAAazgYAGUhBqcAc2QYAJY4JKciOACYfPqu6nJkADNyGxGkgCsiAA9feqaW1vI6ABknODmFpZAOgJGA5FryRgBPG2gaoQCnGAB1Ko5kAA4ABiSrwgIw+9SEN1ecCuZWOSQCcAAjiwCAiJuQpjMkPNFoMQCNqARev08URujY4ABFFgQeAnXFJGB3L7GH5IABMjPqDm6AGFBNMblBRDUWCMcHcSjiRtJpEA)

**Input:**
```jsx
{/* This is a comment about the Foo component. */}
<Foo />;

{/*
  And this is a multiline comment
  about the Bar component.
*/}
<Bar />;
```

**Output:**
```jsx
{
  /* This is a comment about the Foo component. */
}
<Foo />;

{
  /*
  And this is a multiline comment
  about the Bar component.
*/
}
<Bar />;
```

**Expected behavior:**

I am no JSX expert so apologies if I am mistaken about this at the core, but as far as I can tell, the common way to write comments in JSX is using the `{/* ... */}` syntax (or at least that's why the top 5 answers Google is reporting).

I know `{` and `/*` are separate tokens, but I have come to interpret `{/*` and `*/}` as their own tokens, and read them similarly to `<!--` and `-->` in HTML. I have the feeling this is what most people read as well (but I don't have data to back that up, besides said Google results above).

Prettier at the moment strips these tokens apart when the comment is single line, and when it's multi-line, doesn't align `*/` with `/*`.
I think "Input" above is a preferable result compared to "Output", the current output from Prettier.
Thoughts?

**Comment by lydell** [comment]
Prettier already keeps `{` and `/*` together in JSX like you suggest. _In JSX._ Your example is something else though: A good old [block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block) with a comment inside, followed by a JSX element. That _looks_ like a JSX comment, but isn’t. So Prettier actually found a very minor mistake for you. (See also https://eslint.org/docs/rules/no-lone-blocks).

Here’s what it looks like after wrapping in a `<div>` to “enter JSX mode”:

**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UwA9AFQAEAKgBaYDO595AhuZALbsIwsBGEAVx4xqccgDEIENhHYAHaNwB05UsQC+hVJOnFcAbkKESpQuXIBBKOnIimTVuwEAbGJmeYoYjl1hm+gsKi5ABCzABOMvKKsEqEappQqGGRelrEWHggADQgEHJu0HTIoBHhEADuAAoRCMUozNgQmOg5ILzhzGAA1nAwAMpyXZ4A5sgw4QJwuZ50cOEwVZ0j7MzIAGbMznO5AFZ0AB4hnT19-cxcADKecBtbOyBD4XPhyO3MvACeztBtcuGeGAAdRaImQAA4AAy5f4QOZAzpyN7-OAvbC3XLhOAARwEmCxS2YKzWSE222mIDm7Ew40mFLoo2ccAAigIIPA7uTcjAPiD0GCkAAmbmddyjADCslWbygijaAjmlA+9TJc3U6iAA)
```sh
--parser babylon
```

**Input:**
```jsx
<div>
{/* This is a comment about the Foo component. */}
<Foo />;

{/*
  And this is a multiline comment
  about the Bar component.
*/}
<Bar />
</div>
```

**Output:**
```jsx
<div>
  {/* This is a comment about the Foo component. */}
  <Foo />;
  {/*
  And this is a multiline comment
  about the Bar component.
*/}
  <Bar />
</div>;

```

**Comment by astorije** [comment]
That makes sense, thanks for pointing that out @lydell!

One small thing though when it comes to multiline comments, looking at your snippet: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UwA9AFSEAEFAglOhTABaYDOFrFAhhQLYCuAGxiYBmKHAqQePBDEpcARhD4wGjCQCFOAJ0kQeAB2iyAdIVLEAvoVRbdxAlFTEseEABoQEA8OgtkoDraEADuAAo6CP4onNgQmOgeIAranGAA1nAwAMoGaWIA5sgw2nxwnmIscNowYakFPJzIAGacAlWeAFYsAB4aqRlZ2ZwyADJicC1tHSB52lXayMmcCgCeAtBJBtpiMADqCUzIABwADJ7bEFV7qQZL23AL2JOe2nAAjnyYb3WcDU1IVrtcogKo8TDFUogliFARwACKfAg8CmwM8MBWB3QRyQACZ0akRIUAML6RpLKDGJJ8KoAFRW0SBVUsliAA)

Given this input:

```jsx
<div>
{/*
  And this is a multiline comment
  about the Bar component.
*/}
<Bar />
</div>
```

Prettier will change it into:

```jsx
<div>
  {/*
  And this is a multiline comment
  about the Bar component.
*/}
  <Bar />
</div>;
```

I think it should instead be:

```jsx
<div>
  {/*
    And this is a multiline comment
    about the Bar component.
  */}
  <Bar />
</div>
```

What do you think? I'm happy to open a separate issue but wanted to follow-up here first.

**Comment by lydell** [comment]
Yeah, that would be a lot nicer! I think that's part of: #265. Also related is #648 (we do fix indent in JSDoc-style comments).

But #265 seems to talk about formatting block comments in general, with auto-wrapping text and stuff. Perhaps it is possible to just fixup just the indentation? For example, if the `/*` line decreased in indentation with 2 spaces perhaps we could try removing two leading spaces from every line in the comment? If you feel like it, you could experiment in a PR and see if it works out.

**Comment by astorije** [comment]
Thanks for the feedback, @lydell!
I'll keep that in mind re: PR as I'd love to get closer to Prettier's codebase, but at the moment my FOSS TODO stack is overflowing, so I'm not going to be able to do that in near future.
