### ISSUE TITLE
TS/JS: don't remove expression brackets when @type override is used

### ISSUE THREAD

**Issue by Hotell** [prettier/prettier#4647]
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAjAzgWjAAs4wBrAHSitQCpaqNbsYBPABzg2AEsBbdhABOMABQByPPgA2EAIYATOEPEBKAHQAVXABl5SoeoDy7GD2i4Avo1qoqkKLhgY8excpNmLAJQCu0uFwMAF4MUWBGDAcAMx4AcwAxHgCkF1wAYWhYuIAaSJghOUd2ZLgjKGlWVILfOCpLDDpmHA4uXgFhMUkCWXcVDW03A2NTc0dLWwxVEByQCFGLZFA5ISEIAHcABRWEXGQQOWl1uVY92YAjQvI4GABldjkwHig45Bq4WefcZRhNwri+HJkNFDt9ZgArXAADwAQlcyDdbnI+HAdM84MDQR8QA8hN8hPs2JxcGAhDxTDMcWTYAB1HgKGBEZAADgADLN2GtvjTCux9pzAsoAG4Y2ZCOAAR18PHFfzkAKBSBB0jBIG+fB4mJV2NwzziAQAir4IPA3kJarMYHJznSGUykAAmS2FZJ6zJ8QH7QIAVkpvm+mmteyVWMsliAA)

```sh
--parser typescript
```

**Input:**
```tsx
// @ts-check

/**
 * @type {import('ts-loader').TsLoader.Options}
 */
const tsLoaderOptionsRules = ({
  configFile: tsConfig,
  transpileOnly: true
} /** @type {import('ts-loader').TsLoader.Options}*/ )
```

**Output:**
```tsx
// @ts-check

/**
 * @type {import('ts-loader').TsLoader.Options}
 */
const tsLoaderOptionsRules = {
  configFile: tsConfig,
  transpileOnly: true
} /** @type {import('ts-loader').TsLoader.Options}*/
```

```diff
-const tsLoaderOptionsRules = ({
+const tsLoaderOptionsRules = {
  configFile: tsConfig,
  transpileOnly: true
+} /** @type {import('ts-loader').TsLoader.Options}*/
-} /** @type {import('ts-loader').TsLoader.Options}*/ )

```

**Expected behavior:**
When expression brackets are removed, TypeScript will not catch type override. Currently I have to turn off prettier via `// prettier-ignore`

✌️

**Comment by ikatyang** [comment]
If I remember correctly, the JSDoc typecast for the parenthesized expression is only allowed to be a leading comment (Microsoft/TypeScript#5158):

> ```ts
> var x = /** @type {Foo.Bar} */ (y);
> ```

which should be tracked in #4287.

I tried you example with TS 2.9.1 and the trailing JSDoc indeed did nothing there, am I missing something? And also I guess what you really want to use should be either

```ts
/**
 * @type {import('ts-loader').TsLoader.Options}
 */
const tsLoaderOptionsRules = {
  configFile: tsConfig,
  transpileOnly: true
};
```

or

```ts
const tsLoaderOptionsRules = /** @type {import('ts-loader').TsLoader.Options} */ ({
  configFile: tsConfig,
  transpileOnly: true
});
```

**Comment by Hotell** [comment]
Yeah my mistake !

I needed to type it and then cast it, cause the type has all props required, that's why I used that cast at the end. But yeah , following is correct and works as override

```js
/**
 * @type {import('ts-loader').TsLoader.Options}
 */
const tsLoaderOptionsRules = /** @type {import('ts-loader').TsLoader.Options} */ ({
  configFile: tsConfig,
  transpileOnly: true
});
```

So I should probably close this issue right ? 

sorry for trouble and thanks for blazingly fast response. ❤️

**Comment by m1ck2** [comment]
I suppose this all to late to comment
