### ISSUE TITLE
Could prettier be used to print from an AST?

### ISSUE THREAD

**Issue by keyanzhang** [prettier/prettier#465]
I really like how prettier handles code wrapping and I'm experimenting with using it to print ASTs constructed with `babel-types` and `ast-types` (`jscodeshift`).

However, differentiating from recast, prettier's printing algorithm now relies on the `.raw` values of literals (https://github.com/jlongster/prettier/blob/6e68f7495fba705c4d1e58e63efb5a41dea2df7d/src/printer.js#L714-L723), which makes it unable to print a programmatically constructed AST literal node.

Is reading from the `.raw` field necessary for properly handling unicode characters? If I understand it correctly, would you be interested in a PR that let prettier check and fallback to use/cast the `.value` field when `.raw` does not present on a node? :)

**Comment by vjeux** [comment]
Looks like we'll need to bring back jsesc again :)

I'm onboard printing from the node value and aggressively escaping everything if the raw value is not there. cc @jlongster who should make the final call.

Can't wait to use prettier on-top of jscodeshift <3

**Comment by vjeux** [comment]
By the way, we also read from the original source in order to figure out if there are new lines for comments and preserve empty lines. You want to make sure that the location of the original source is preserved otherwise it's going to look completely broken.

**Comment by keyanzhang** [comment]
@vjeux yeah, it seems really hard to create something like
```js
var str = "multiline\
string";
```
programmatically without specify the `raw` field. Not sure what's a good way to solve this...

**Comment by vjeux** [comment]
What are you trying to print?

**Comment by keyanzhang** [comment]
I'm using postcss and recast/prettier to convert some CSS rules to JS objects, where all JS AST nodes are programmatically constructed. Handling literals doesn't seems hard, but I haven't figured out a good way to preserve comments. That said, the project I'm playing with isn't really related to this issue. :)

**Comment by jlongster** [comment]
Right now we're focused on printing files, but it would be cool to support programmatically-generated ASTs. One thing we also need to support is sourcemaps, which aren't important for prettying files, but is if it's part of a toolchain. I have ideas about that, but we are focusing on other bugs right now.

I'd be fine with falling back in cases where `raw` isn't present, although there are lot of complicated things to cover like regular expressions. If someone wants to do the work we'd accept it though!

**Comment by TheLarkInn** [comment]
The new scaffolding system that we are creating out of AST transforms could def benefit from this. Especially when it is from scratch!!

**Comment by vjeux** [comment]
@TheLarkInn: 
You can use the api to feed prettier an ast and output a pretty printed string.

https://github.com/prettier/prettier/blob/master/index.js#L94

I can't foresee any major issues we can't fix. You should try it and let us know what you end up with, this sounds super exciting!

**Comment by TheLarkInn** [comment]
@vjeux Thanks for the suggestion, I tried it out, but then the sadness loomed over me as I forgot _(Oh crap they are probably using flow and/or bablyon)_, which led to my search in the source code to find out, indeed it appears that way. 

I'm guessing theres probably not a way to use acorn/ESTREE format is there.

**Comment by vjeux** [comment]
If the acorn/estree formats are not too different from flow/babylon, we could support them. Do you know if somewhere on the internet there's a descriptive of their main differences?

We also have a ton of unit tests so it should be easy to have good confidence when adding support for it.

**Comment by vjeux** [comment]
After a bit of digging, it looks like the flow parser follows the estree spec: ["It produces an AST that conforms to the ESTree spec and that mostly matches what esprima produces."](https://www.npmjs.com/package/flow-parser) and that [Babylon only deviates a bit from it](https://github.com/babel/babylon/pull/41/files).

You should be good to go :)

**Comment by vjeux** [comment]
There are likely going to be some minor edge case differences between flow and acorn but they shouldn't be hard to fix.

**Comment by TheLarkInn** [comment]
I'll get some more info but for any reference I had passed it from jscodeshift'd ast. Maybe structure is different there when modifying or constructing the tree

**Comment by vjeux** [comment]
Honestly, I would recommend you to use recast to print the code to a js string and then feed it to prettier. This way you use the normal and battle tested codepath and get the result you want.

In the future, we're likely going to want to skip the js part but this is an optimization. If your templates are small (less than 100 lines), this should only take in the order of ~10ms so not worth the complexity right now.

**Comment by yamafaktory** [comment]
@TheLarkInn Babylon just got a new compatibility layer for ESTree https://github.com/babel/babylon/releases/tag/v6.16.0.

**Comment by TheLarkInn** [comment]
Awesome!! I will actually do that then. I haven't dug into the api's beyond the first few but will give this a shot!!!

**Comment by TheLarkInn** [comment]
Holy crap, its beautiful.

<img width="1497" alt="screen shot 2017-02-23 at 11 36 59 am" src="https://cloud.githubusercontent.com/assets/3408176/23271299/a0a1e1b0-f9bc-11e6-967e-1dbec404a134.png">

I think there are some specific nuances with spacing and indent we'll look into but it looks like I can pass recast and pretty options that seem pretty similar.

**Comment by vjeux** [comment]
Closing this issue as it is not very actionable. Feel free to open other issues with more concrete items we should work on to make this happen.
