### ISSUE TITLE
Extra line break before catch?

### ISSUE THREAD

**Issue by cbray** [prettier/prettier#4650]
Is it possible to somehow configure prettier to allow an extra line break before `catch` (and `finally`) statements, but no others? For instance, following a lengthy block of code prior to a `catch`, I sometimes prefer add an extra line break (I find that it helps with readability):

```
...
    console.warn(`selected_profile.get: filtering on id: '${filter_id}'`);
    store.filter('location_id', filter_id);
         
} catch (e) {
    console.error(e);
}
...
```

However, I don't want to disable breaks before the closing `}` in basically all other cases. Does anyone know if this is somehow possible? Thank you!

**Comment by suchipi** [comment]
Prettier doesn't have an option for that and we're not going to add one, see https://prettier.io/docs/en/option-philosophy.html

However, you might be able to run eslint --fix after prettier to accomplish what you want, but I'm not sure if a rule for what you want exists.

**Comment by lydell** [comment]
I don't think there are ESLint rules for this. [padded-blocks](https://eslint.org/docs/rules/padded-blocks) came to mind, but it is not quite what you want. I also thought of [padding-line-between-statements](https://eslint.org/docs/rules/padding-line-between-statements), but it only allows you to enforce blank lines _between_ things, not at the end of specific blocks.

I guess you could make your own rule though, with the above two as inspiration.

**Comment by cbray** [comment]
Ok great, thanks guys! I'll take a look to see if I can get something going with ESLint. @suchipi -- understood re the philosophy, being opinionated is one of the things that I like most about Prettier -- though in this case I was hoping that the opinion might be that "that one extra line is ok if you want it" :)
