### ISSUE TITLE
[bug] prettier playground compiles too slow when it came across syntax it doesn't know

### ISSUE THREAD

**Issue by xialvjun** [prettier/prettier#4652]
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAAwB0oATASzQAcAbbATyUwDNa4APAblICNswAawDmAJwgBXcs1FwyPKADpsvMJmCZKNek0y9aEIQsx6BI8VLLMA7gAsK8BQF9ShLiAA0ICNRgV0yKDYouLWAArBCGjIINgAbhAUZJ4gvKJmcDAAytQCFFDCyDCiEnBe+WhwojBh6cIAttjILNi0lV4AVmgcAELpQplZ2PVwADL5cM2t7SC5opWiMWwQ1inUovkwAOpJMLbIABwADF7rEJVb6dQx63ALcZNesgCOEhSytdgNTUgtbWUgSr1ChFEoAtD5YTsACKEgg8Cm-y8MBUOzIe2QACZkekKLRIQBhCD1RoxKDQR4gCSVAAqKmiv2mcCcTiAA)
```sh
--parser flow
```

**Input:**
```jsx
const a = `
display: flex;
background: red;
.abc { display: block;
  background: white;
}
`;
```

**Output:**
```jsx
const a = `
display: flex;
background: red;
.abc { display: block;
  background: white;
}
`;

```

**Expected behavior:**

When I change the code at left, the right part compiles too slow....

beside, how can I format a code block using a specific syntax like less/scss

**Comment by hawkrives** [comment]
It takes a fraction of a second to update for me. Can you give an example of how much time it's taking for you?

**Comment by xialvjun** [comment]
change a byte in left part will cause download `https://prettier.io/lib/parser-flow.js` four times.

**Comment by suchipi** [comment]
Thanks for the report @xialvjun
