### ISSUE TITLE
Code breaks row size limit in particular case

### ISSUE THREAD

**Issue by Guria** [prettier/prettier#4655]
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnCBbOAFATpgS1TgDoYALBACioENcBzVASgAIBeAPleAB0pWrCkRIAHfKNQlccMHAIA3OADFaCiLgLxUAQTAwC0VFQIATADSsA2gF0SkKGFowqJN-SbNmAbn4BfSypgViIAYVpHOAAbOFNWPzYuVgBCMIi5GLiAMizWKIgGBjhcEgB3eigqAANAPBBACRBADhBARhBALhBABhBWQH4QQD4QQG4QQGEQQHEQQFYQQF4QBsB5EFZAFhBhwE4QQEEQQCEQQCYQBrmZ3qnOwAEQbun+lqW2pFYAEmAzPyqvXygQcxAIUQMjZFB6fFLsegRUZBAaggZgeIAARrhaGAANZwGAAZVEUIIUAYyBguAArnBHijiLgYHhaAwMLRkAAzWhRYiPABWqAAHgAhSEwuHw2hYAAyKLgFKpNJASNw+IBYNoYIAnvl7o9xCiYAB1MwUZAADgADHL8MRFZDRADxHB8UpQTIAI6YggyIkkslISnUnFoOAYAjorHO1AohgxACKmIg8H5TseMAlytMqqQACYw5CCFEfaFMKSAVBoHzHpjiAAVCX-B0CuB+PxAA)

**Input:**
```jsx
// code snippet
somePromise.then((args) => {
  this.props.receiveFavoritesActions(id, [].concat(...args));
}, ({ isCanceled }) => !isCanceled && logger.warn(`Ошибка получения действий для продукта: ${id}`));
```

**Output:**
```jsx
// code snippet
somePromise.then(args => {
  this.props.receiveFavoritesActions(id, [].concat(...args));
}, ({ isCanceled }) => !isCanceled && logger.warn(`Ошибка получения действий для продукта: ${id}`));
```

**Expected behavior:**
Do not allow row to break 80 char limits.

Adding curly braces block to arrow function is the only way to fix this issue.
Though not sure if current behavior is on purpose or bug since I can't suggest good looking alternative.

**Comment by j-f1** [comment]
This looks like a bug. I suggest either one of these:

```js
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
somePromise.then((args) => {
  this.props.receiveFavoritesActions(id, [].concat(...args));
}, ({ isCanceled }) =>
  !isCanceled && logger.warn(`Ошибка получения действий для продукта: ${id}`)
);

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
somePromise.then(
  (args) => {
    this.props.receiveFavoritesActions(id, [].concat(...args));
  },
  ({ isCanceled }) =>
    !isCanceled && logger.warn(`Ошибка получения действий для продукта: ${id}`)
);
```

**Comment by suchipi** [comment]
I'm fine with either suggested format
