### ISSUE TITLE
Generic arguments are lost when using import types

### ISSUE THREAD

**Issue by aengl** [prettier/prettier#4656]
**Prettier 1.13.4**
[Playground link](https://prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAgEtY5cAzbMQgMQggOAB0oCCAjPJYgWwAcIuGAAoA5ER48ArjGztMcUQEoAdAFlsfADwBnGLhIBzADTFYAPgDcLAL4hjICHxhFoO5KDy4IAdwAKeAjuKNgAbhBEqPYg7LhUANZwMADKfFRGyPpScA4kOmQwfnGGPNjIlJj5DgBWOgAeAEJxYIkp2DxwADIkcOXYlTkgabj5uMggMACefHA6YAbO0XwGsADqkTAAFsgAHAAMDssQ+atxfOPLs2ShvQ74AI5SRPhF2CVlSBVVIPk8RJm4bIOHRGBQARSkEHgfQGDlk7HWqC2yAATHC4kRMEYAMIQSQfEBQaC3EBSfIAFTkwS+cBsNiAA)
```sh
--parser typescript
```

**Input:**
```tsx
declare interface Foo {
  bar: import('immutable').Map<string, int>;
}
```

**Output:**
```tsx
declare interface Foo {
  bar: import("immutable").Map;
}

```

**Expected behavior:**
Generic arguments `<string, int>` should not be stripped.

If this turns out to be complicated, I'd be happy to contribute code myself. Let me know! 😃

**Comment by ikatyang** [comment]
I guess you meant you'd like to contribute if it's not complicated, you just need to print the missing `typeParameters` here:

https://github.com/prettier/prettier/blob/35a42bef248a33032e52766b2260645a0a5e4279/src/language-js/printer-estree.js#L2935-L2942

and add a test case in `tests/typescript_import_type/import-type.ts` then `yarn test -u`.

See also https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md.

**Comment by aengl** [comment]
Happy to help in either case, actually. Thanks for the pointers, I'll work on a PR this weekend.

**Comment by aengl** [comment]
PR: #4662
