### ISSUE TITLE
`--prose-wrap never` not work

### ISSUE THREAD

**Issue by bluelovers** [prettier/prettier#4664]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA4guAnAQ3gBMMAjATw2JgGcBaMgVymIBs4MA3ABgDoA7HwDMAHSjoMAETgAHBMQRgAlnFoYAZhDwYYAC2XqAthGJMOScekwAePHA34lnWUT0BeUSBh5V9ewDmcAAeXhioAHzi4opgbAT2GCZmHBhePn6y9hrKwfQ+cHAATGHA4hgV4QBUVeWVGFUYAML2RHCklBhMtPgY0BhFPACMAByoAGyoAJyoPDxTfHWVVahLGMpGstowur5wADQYwBgAKnsYAL6aeBBGad579FkOufn2xai0eGBeANxrIS2eB2jQ0Nzu6UezxyeQKHy+PxA-yg9UB2yOp3OF2RqOCQJ2ig0BHMOwycGRF2irDgcQSnGS5k4kMy2VecKKn2+pTWG3xGIAkmdVAAlAgAd0Ogr2ADlTJwrmDbvcyU9WbD3hyEagwK14H8eZt0ccAKLSqQAfQAagBBAAyAFVjZdrkrmXBVS91YVNd9tdAcgF9SjKrz0WSThBhXAAsa8YdjvyAPKyGDKaC0a1sNgYAjqKWqCNRmN45Op9OZtiS0tpqDqXMYfNwQvR2Oyavp52KiEPPyBEJB3F8yC1nYAZQAmgBZc3C60AdSQXSgygAjkxOLQKEYyBA2DjKmjgboKPIG-yoLImDAbCcIhh3BhaBkoAEANoAXX3FUPpJPnH556XjAk4ELIN53g+r5Pr4L6HCc74fl+GA-sep6Nu2tb3kcaz1KgNQ4fUjQAAKEsSbCkng64EcsqzBvUFTKAEUDaHATS5nAAD8i47rucAEFASH1EYoGTnKXHkBAvH8Uh2IAni6K0rQ6hCnAN5YTAf4QBoGCmhaNoOsad5lHR9GvhO06znO76Lo2opiuBgmVBAKY1rQ4lRgQxDQGwFA2OhLnphEjkVMO0FMGAMDaAAFNR9HKBeV42YBV4gWBt77LF9TOWWtbif5OXqAAZNhJn0WVSQiXKi4+OuwX0RcGWleVfAtQkARcIu-EUB+sUAJR1aFNURdF8VAUlCXXulfQBblNkqRhtCHC1fBtR1OZQN1779bFeG1E1yzYHApJ6JwQRQPgbSkIQYq7KofRkAAVjSMCZSssVwlFvVzXsdkOTt+H7RUjQ4DsBCPs+AQYPYzw9LARA1n02n6JwZKvbR5UYGwECeVFECPd9IriuBX26AYtB1Vjnk2MKES4-jDYqb9NMk-ohgU9jxB0w9nUbSzZN1btr2HaD4MwZD0P2LDMDw-0Wmkyjexo7FZibFFtCuGA+DidB8WQwAPhgUBMNu+AkzrL4CwDGMNBg1rEKQYPnTdYraKQkXy7dcBK4DnnEHOrtRS7eDEIu5sBIcXAEGw67iScfNs7FWQQPAEXtBg5oANZwBQgeu6HENmxDlt7dbjRRiYXCcPxyHBIYqYvhgQekF2Huo4DDTo+V9gV3A-vB7nwf52L8fk4nNwpyQ6dgCdYAZwACmqMXt5U0K5EPut9YuxnWyvaoAGIQCwIcSVJAmZbvnqyooBNwFfqm3nVsmA4L7eNE0M8ZzmGCr8E6zqJHbBlDECFkRewMAmB4EwgAIUkhwfi3sMaGAXp6KKP914vhJj-P+otdbFyFiDL+gCnyIxzFmRurt1DxVbucMUyh9AewCMoSuKIf4gLARAzC1o8CEAoAg8qQQYDIJhGrHwQi144Ngo+bY7RxI8TgVAQuYtEL-RLhjYGR0v6EFYEqJu6wUTI09o3OhegGFMIQN-NUbCjocPUKOCGfCyoCNFNoowfc-bGLEcEEReBPHawLuggIeDX7NEPrAD2RsTY6Dlk3dQtD6EGMYcwixnpRx8W+HoKx4DIHqGlMbMg+AHH0UgCwQRi9oKeICSTCJ+S8BBNLsLUh2YYl6OoaoTJNjbbcIILw1+ndHFHTcRmLMatpHEFkbAviCiAnKOflbNRzQP4exCHXZwJCwa6KoQYtu9TQHWOyRgGBp9Cn1D0LmNxA9j5hxJnIyZdUk4TzToYa0UACABEIEYWgUUOAwHgHgWglTFzfN+ZQ9QYc6nzIIWDIhOw5YAKAetV57z1D6CIBgMA1d8kVUUC6O4CSzEoiBfgWg7T9lcJ4ccyoAjnmIoIB8r5R1gUAokW+T8Kj8EaKhXXNZZDaBMDIPQfiNKPmk1ReilEmLhLYpbnipJhK-kks4V0nppc+n0QEaOPl1K3m0s+XK-5zLFG6xmRjSKRZWzUywmavEtMNDxACG5AJhxsquTyipZsxY2wzVoCTYUdVTUtjxNTG1dqHXMqdV611ex3WtgWhWINPq9lQBOH+GwGl5By3DJGANsggprEpCZFCGgWARQRjqPi8AVJqQfGmuActdJWjtI6Wmo1ErMo-EtVqeB2o802iTStD85J8lIiSNFuomx7ApFSWI8REgMlSG6D0MI3jek5GAbUY7uQmVDEeE0ZpzRzkTMKKQhx636UdJ2cEyooRqmXfCX0w4AwDhDIaHdZ4JoXtdD2d0P9b0+jXfFRQoQkSDrDH+Bmewq2oVrdpU9jbDJYUbHfcCGADa2SJgOgt8kjzxV+USTW4HVBIZOOpTSMG91nvg9vcqr4M4BOsgR2+co-qAwACQsdjnVV89aD1HvfBxvNIHsOwHwHh-8jN0MkfTWRvScGjKxRo3Rm+RHc0mXzYOdERaoAlv6GWto4EootpgONIC4EO0rS7WtLqH4SZofshh9TR5h3kVHeW8k4h80xBpDO+kphGRXpZJ6X9q6-RQEfSAEqDmdiDR0nunjUgsJeDY0+78WGovph2LBgyi4PJeSgD5GwwALgqci2i9LMWLRSGNHvRcLBVzrkfFuHce5BNpZHBgOexphSTlHOaSc-JpTmltKaLCRQkLbpBDmdQD7GI4v89+m97JgvTcDMBzDQ6HBkVawGSdUBPO0lnb5+dX7F1sg1MFgD-ZwtUYYi+nYCZxMSgY3fD93YVQ-sW1qXTepVv1HGxiTL56FSXoXe9s7n3-SMWS+sW7nto1xgFLGsh9ZGxw89QVCsVYvWTYY6jhaL25v+GjJdpCKFovmRnPOGry41wbka7uEnqWoNvpM7eLCYdjUHkZzW5nKVQLIcgmHOCCFWVrdA2heaWOHzXfoi-HZTmKJUV6bFRizF7BsR6OM0+dVhKyFEooTX8iZIM6HPEJSmJVCQZrXW8jsmIvUfJ5ZejtnmMY2demdyfFcv5fyq5Yr5VBqUWGngJeO8GITWM7ztKERGqh+mgVSNqg8fFWl7HnXeu4DVUom55eFQGrnwqMtVaPaeqA22oDAP4VIrB8MxHya0e48upvgtMzRf1q9vBeVdRx1Tq4EIJPa6hi8ZPQihSioH0bMPZd+VWXEKOXMqhnISWCBpY5RIVsxWSvAaU05kPm+v1bwj3ZlTGmXM99E2ZtVfmsVt+n7b4ftlwTIXz4lmoZfMsUQZpOp7Uf1BjayDVhrFrAEihobHkqbAEh3mVI0HbA7IbHAM7K7LoBAK0l7JvhjL7Ock3I6twFHDHIuHHJfgnIDPcs9GnJnNnBckymCg-vUuXBAJXOtDXHXLrOQsHLNuvm0mgV3HAD3JgXnAaoQaPMQePKQaQOaNPDSPPIvPnskjCAEpvHbjvD-AfEfNxBMtJDIT-HfEpkxvZuVE-BjDPp3gspIV-FgoYDgYAsAsErslktAuobtlwWVEgovGggIbIbkNgtQbMqosYU-tCtyk0hQi0hwZwHEiYjKuYqwjYewqSkqj-gIp4t4hUmGlIsCDImoafIai+BzmVEYVAQ0mDFol5HcBsvol-mSEYvEl-oklEZYjEYmrYvYk4WqkdM4iUW4nOB4mUqImqH4sPBATQfMk0KEt3qAZEiQs0uEaYkkj-KkgkNPAqjkmAXgD-sUrAEkeUmqEytUvgJAfRF3o0qwcQJQuUQrJwTsrEYquSi0fUAIoMhWCMukWMpkfItkSyvsYRCYbPEsrXE+KsnLOsogZshURvpcY0Qcg4T-qcrQHwYPO4TchocIcnKIX-FqkivSj8kSkynql4UXEMX4XPgEbClHPCoKtqsKiilFhivSJ5JwNKjUfipjAykSksZ0jcSqrFFSi8hSbqiyX8lQRDLkTLnMoSSLMSdpFHNmLyvyuSUiiKtSeKrSVKpepEQSvycSg0XYeoGSt0gkUdBqmQOiTqpiYyu4eziLialmh6hag+FajmlFLaq8qGoLg3u7jfLjl6j6n6taeaifk6fav0brOGvHh6b6SWF6nGhfhgFGHYcmvIKmqRrDuGTmjJC1poMWqvl9uOhbsRtWkmQDoZAZuHm2u+C3hZsXltPgRBnoSlutkSCOtmSpDtiAPsCAG7rWMgKAAkDcGKHPHSJ2SgAQFwBAEAq2SAGQIQLPAaRrLrMgDVAcCAPFD0MCAvK8sJMgESGwD0G2Q9LQMEFAlOVnDAKOLSnALaPFHAJuVHDuSAK4H8vgMgN4H+LQDqMoCmOOVkDhl0TQHoMgCMDwG2UnD0HOIQLIE+edJXHgOOfYGuMoPYGuQEBuUgFubeT0EYMoPOVnm2bQLrBwAAIpMAonXnbmLnSxkA-n6DIAAAsbZPgBAyggCL4IxRgyFIAzE50453QTYBAZAtAJFPQFwFwQAA)
```sh
# Options (if any):
npx prettier --tab-width 4 --prose-wrap never --write trie-prefix-tree2.d.ts --parser typescript
```

**Input:**
```ts
        getSubAnagrams(letters: string): string[];
        toRegExp<R = RegExp>(flags?: string, options?: ITrieToRegExpOptions): R;
        toRegExp<R>(flags?: string, options?: ITrieToRegExpOptionsAll<R>): ReturnType<typeof trieToRegExp>;
```

**Output:**
```ts
getSubAnagrams(letters: string): string[];
        toRegExp<R = RegExp>(flags?: string, options?: ITrieToRegExpOptions): R;
        toRegExp<R>(
            flags?: string,
            options?: ITrieToRegExpOptionsAll<R>
        ): ReturnType<typeof trieToRegExp>;
```

**Expected behavior:**

only way is set `--print-width 999` for a big number

```ts
        getSubAnagrams(letters: string): string[];
        toRegExp<R = RegExp>(flags?: string, options?: ITrieToRegExpOptions): R;
        toRegExp<R>(flags?: string, options?: ITrieToRegExpOptionsAll<R>): ReturnType<typeof trieToRegExp>;
```

**Comment by lydell** [comment]
`--prose-wrap` is for markdown only. https://prettier.io/docs/en/options.html#prose-wrap

While the word “markdown” is mentioned in the above docs, perhaps we should make it clearer that the option is markdown only?

**Comment by bluelovers** [comment]
if `--prose-wrap` still is for markdown only

i think we need a option for disable `--print-width`

**Comment by lydell** [comment]
`--print-width` is at the heart of Prettier. It cannot be disabled.

**Comment by bluelovers** [comment]
or give a oprtion , don't not auto wrap argv when source didn't wrap  it

**Comment by j-f1** [comment]
We generally don’t add options and instead recommend that you just accept what Prettier outputs. Is there a reason that breaking this onto multiple lines is such a big problem?
