### ISSUE TITLE
When breaking single line ifs, braces should be added

### ISSUE THREAD

**Issue by eamodio** [prettier/prettier#4665]
I typically only use single line `if`s for flow control, and anytime I break them to be multi-line I will add braces to avoid the potential issues (see Apple's infamous *goto fail` bug). But now because prettier can decide to break them up, it doesn't add any braces.

**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBTohTAMkMwCMBDAJyJIoC8bMBnCAWzhgAtUoBzAfQDuqLv3L8AbnEoBPfgBtoAqOXYATJuSboN6Jmp3bd+7foCUmShwCulKJnTl5TOAG4AOlE8YceAsTIqRnpGFnYuHgFhUXEpWQUlfhV2ULYObj5+OGc4IRFOMUlpOUVM5LhMCysYW3tHHI8oEAAaEAgABxhUaCZkUCpKCEEABSoEXpRyCQhUNRaQUkpyMABrDgBlduXI5BhKazhWnhdKGGGl3lZyZHqXVoArJgAPACEl1Y3VOAAZHjgbpx3EBbSgnZALcikGSlebtSg8GAAdVmXGQAA4AAytOEQFyIpbtcFwuAnKTzKwAR2sqCs53Il2uSFuhxALlYqF2+xZTEi8jgAEVrBB4ACcq0YJDkWpUUgAEzipaoeSRADCbCu4Kg0H+rWsLgAKpCJsyAL4moA)
```sh
--parser babylon
```

**Input:**
```jsx
if (foo && bar && baz && something_with_a_very_long_namedsasfdsfsdfdsfdsfsdsfsd) return false;

if (foo && bar && baz && something_with_a_very_long_name && something_else_with_a_very_long_name ) return false;
```

**Output:**
```jsx
if (foo && bar && baz && something_with_a_very_long_namedsasfdsfsdfdsfdsfsdsfsd)
  return false;

if (
  foo &&
  bar &&
  baz &&
  something_with_a_very_long_name &&
  something_else_with_a_very_long_name
)
  return false;
```

**Expected behavior:**
```jsx
if (foo && bar && baz && something_with_a_very_long_namedsasfdsfsdfdsfdsfsdsfsd) {
  return false;
}

if (
  foo &&
  bar &&
  baz &&
  something_with_a_very_long_name &&
  something_else_with_a_very_long_name
) {
  return false;
}
```

**Comment by lydell** [comment]
Sorry, Prettier does not do this type of AST transformations. Quoting https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about:

> What Prettier is _not_ concerned about
>
> - Adding/removing {} and return where they are optional.

**Comment by j-f1** [comment]
Also, if you run Prettier on save in your editor, you’ll find it much harder to get confused by the lack of braces since any indentation errors will be corrected when you hit save.

**Comment by joeytwiddle** [comment]
That is true, Prettier will correct the indentation. But there is a risk that will be [too late](https://github.com/prettier/prettier/issues/3049#issuecomment-347692929).

I would urge the Prettier team to reconsider.

Using braces for multi-line blocks is a common rule in many style guides ([AirBNB](https://github.com/airbnb/javascript/blob/8ed1d855bbefccbb147fe17d902a18c8f9aa3977/packages/eslint-config-airbnb-base/rules/best-practices.js#L26), [Google](https://github.com/google/eslint-config-google/blob/394bf3c9f858b83514fdcbf23d74492e253d611f/index.js#L84)), and for good reason ([Apple goto bug](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/), similar bug at my company). It is somewhat undesirable for prettier to insist on outputting code which does not meet widely adopted practice.

Clearly some people do like the current behaviour, so this change would need to go behind a flag. But I suspect adoption of that flag would be quite broad, if it was made available.

**Comment by j-f1** [comment]
@joeytwiddle If you want to use braces, feel free to use a tool that enforces them — Prettier will keep them if they’re already there. Again, Apple’s go to bug might’ve been prevented by Prettier because it would’ve dedented the second goto, showing that it isn’t part of the if statement.

**Comment by aboyton** [comment]
Personally, I don't really mind either way on this one—I have a linter that enforces braces.

As much as you say that you don't change the AST, there are some changes to the AST Prettier does isn't there, like changing hex number casing [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTABgA9sBuAHSkig0wCN8jiBBMkAGhAgAcYBLdMlDYATqIgB3AApiEaZCGwA3CPwAmnEPVHYwAazgwAyjz38oAc2QxRAVzhcLaOKJjTdlgLbZkAM2wAGxcuACs0YgAhXQMjY2wvOAAZCzh-IJCQM1EXUUV6bHoAT0DoLR5RCxgAdQ0YAAtkAA5CLgqIF2rdHkUKuFzlNK5ROABHO34Rj2xvXyQA4McQFy9+G3sltAtLQLgARTsIeHTFrhhC2vUG5AAmM91+QO2AYQgvH0UoaCGQOxcAFUKCnmGTgAF8wUA), at least according to http://astexplorer.net/. That said, I'm not sure I'd count either braces nor hex capitalisation as part of the AST, that seems more concrete syntax to me.

**Comment by lydell** [comment]
Yeah, we do have a few places where the AST is changed, but we try to keep it to a minimum. Makes the "make sure the AST is the same before and after formatting" sanity check much harder to do.
