### ISSUE TITLE
`prettier.format()` slow for deeply nested function calls in input string

### ISSUE THREAD

**Issue by tony19** [prettier/prettier#4672]
When the input string contains many (about 25) nested function calls in JavaScript, `prettier.format()` takes about 2.5 minutes to return. This seems to occur when `coreFormat()` converts the AST to a document (in [`printAstToDoc()`](https://github.com/prettier/prettier/blob/dcc060a5a522bc9fa5d8560eb6e72ea25138e828/src/main/core.js#L84)).

**Environment:**
 * macOS High Sierra 10.13.4
 * Node 8.9.4 and 9.11.1
 * MacBook Pro 2017, 2.7GHz i7, 16GB 2133MHz LPDDR3

**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB9MAKAOiAJgSwDccAaAAgG0soyz1s8jTLrbb6cDiRyqa32mTkx4t+AwQy7M+EiR0bderOfKGKZK1Wqkjl47TuFKxhwwumjZZ8+sv6bNi3tOOndl9bfvdJr959jTQMAwI0rLVC3Zz9IqOiPWJD4hN9glJSY9IzMxOyc3LSI5ILQrKty3nKASgBdOuq40u96puazVpL2uU7ujsau7t6+gWGRsfaJgqmUmdC5twX+tsMliTXaNYWZieHO+p4QCAAHGHxoAGdkUABDACc7iAB3AAV7hCuUG8IIfFxDgBGdxuYAA1nAYABlY4g-BQADmyBgdwArnASCA4Rc4HcYC9gfCALY3ZAAMxuABtsRiAFYXAAeACFgWCIZCboS4AAZOFwMmU6kgGF3bF3ZAgAE3AEATwp0EOxzucJgAHU-jAABbIAAcAAYMYqINiVcDjuLFXBRYQ+Ri7nAAI4o-B2-E3IkkpDkqnokDYwn4fnejEXOHwilwACKKIg8EDgpgUrVuE1yAATBjkTd8BTQwBhCCE4niqDQG0gFHYgAqUs+XuxAF960A)

**Input:**
```javascript
_c("div", [
  _c("div", [
    _c("div", [
      _c("div", [
        _c("div", [
          _c("div", [
            _c("div", [
              _c("div", [
                _c("div", [
                  _c("div", [
                    _c("div", [
                      _c("div", [
                        _c("div", [
                          _c("div", [
                            _c("div", [
                              _c("div", [
                                _c("div", [
                                  _c("div", [
                                    _c("div", [
                                      _c("div", [
                                        _c("div", [
                                          _c("div", [
                                            _c("div", [_c("div", [_c("div")])])
                                          ])
                                        ])
                                      ])
                                    ])
                                  ])
                                ])
                              ])
                            ])
                          ])
                        ])
                      ])
                    ])
                  ])
                ])
              ])
            ])
          ])
        ])
      ])
    ])
  ])
])
```

**Output:**
*(same as input after 159 seconds)*

**Expected behavior:**
`prettier.format(input)` returns within a few seconds (much sooner than 159 seconds)

**Comment by tony19** [comment]
Possibly related to #1250 and #2259

**Comment by fisker** [comment]
This is not slow anymore, not sure how and when it got improved

**Comment by thorn0** [comment]
#6229 fixed it most probably.
