### ISSUE TITLE
TypeScript imports ignore settings, violate linting rules

### ISSUE THREAD

**Issue by jonrimmer** [prettier/prettier#4673]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmAB0p98A1OHATwBloBzAYQi2gRgDkBDdOEgL74AZjlb4A5AHpuUgG5Vq8xcpqqlCtZo0rt6-XoA2jKZm4wAFhIDcJEABoQETDFTQAzslDccYgO4ACj4InijcchCoACYOIABGONxgANZwMADKZmCoUAzIMDgArnCOOe5UMAGJDOjcyMLchuWOAFbuAB4AQokpaem8cLQ5cPWNzSBmOOU4yCAw1Jhw7mA4qC6xmKuwAOrRlsgAHAAMjpsQ5duJmLObS1QKsThwAI6FqE9V3DV1SA1NJSByuhUPkigD3DkGIY4ABFQoQeCjf6OGDcOK7KL7JAAJhRiVQhkhLHQtVmUHYsUK5QAKmjQn9ygIBEA)
```sh
--parser typescript
```

**Input:**
```tsx
import {
  VeryLongComponentName
} from '/a/very/very/very/very/very/very/very/very/very/very/very/long/path';

```

**Output:**
```tsx
import { VeryLongComponentName } from "/a/very/very/very/very/very/very/very/very/very/very/very/long/path";

```

This breaks our build, as tslint enforces maximum line lengths. 

**Expected behavior:**

We need prettier to respect the settings we give it, not ignore them.

**Comment by ikatyang** [comment]
See https://prettier.io/docs/en/rationale.html#imports for the reason why we format it this way.

And we recommend you to disable all the linter rules that'll conflict with Prettier using [`tslint-config-prettier`](https://github.com/alexjoverm/tslint-config-prettier), or use [`prettier-tslint`](https://github.com/azz/prettier-tslint) to run `tslint --fix` after Prettier.

**Comment by jonrimmer** [comment]
Applying `tslint-config-prettier` seems to disable linting of overlong lines entirely. That's not an acceptable "fix". We will just stop using pettier. It isn't worth dealing with this hassle.

**Comment by j-f1** [comment]
Why does it matter how long lines are @jonrimmer?

**Comment by jonrimmer** [comment]
@j-f1 The reasons for, and against, constraining line length in code have be discussed and debated at length elsewhere. I don't think there's anything to be gained by rehashing the arguments here. 

Sufficed to say, some developers find it useful to have a maximum line length, and to enforce it through automated tooling. The fact that prettier supports `print-width` suggests some of its developers were sympathetic to this idea. If it's going to suspend this rule for particular constructs, such as single-object imports, well, that's fine, but requiring the complete suspension of detection and enforcement of overlong lines, just to allow it this quirk, is not IMO a worthwhile trade-off. At least not for us.

**Comment by j-f1** [comment]
If I remember correctly, we do go past the print width in a few other cases, too. In this case, I think we found it more beneficial to print this all on one line since you don’t have to edit the line very much and we felt it was clearer on one line. If you wanted to, you could put `// prettier-ignore` on the line before it, or [put a single-line comment](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmAB0p98B6c-SddBGEsgMwghIF98mcJ18ByAEYBDHPxAAaEBEwxU0AM7JQongHcACqIRKUwgG4RUAE0khBOYWADWcGAGVMV1FADmyGDgCucKS4VweBqWrujCyEzCADYBUgBWCgAeAEKWNnb2wnQAMi5wEdGxIE44ATjI5sKCAJ5R0GaYOC4wAOomMAAWyAAcAAxSjRABLZaYFY1wZfr5UjhwAI5eqHPBwqHhSJExviAB6Kge3jsKLq5RcACKXhDwBdtSMFVtxp3IAEwPlqhRpwDCvGEKlBoDMQF4AgAVKq6LYBdjsIA) inside the `[]`.

**Comment by lydell** [comment]
@jonrimmer It _is_ possible to use a maximum-line-length rule together with Prettier. See https://github.com/prettier/eslint-config-prettier#max-len. You should be able to re-activate the rule even when using tslint-config-prettier.

**Comment by jonrimmer** [comment]
@lydell you can use it only if you're happy to fix-up every line that prettier makes too long (or I guess you can mark them as ignored, as j-f1 suggests). I just find it perverse that prettier will take code that has been manually formatted to fit *below* its own configured print-width, and transform it into something that exceeds it! Leaving some long lines alone when it finds them, I guess I could understand, but _actively_ reformatting them to be overlong is just... weird.
