### ISSUE TITLE
Is the position of the symbol "*" consistent?

### ISSUE THREAD

**Issue by jamieYou** [prettier/prettier#4680]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAVPgIYAUAlPsAL4A6UJAzgJ5b4Za4HEBGl1elgA2zJvgAq1BvlKt2xMANoMaIADQgIAB25QmyUCQBOxiAHcACiYQGUJAG4QcAEw0hexkmADWcGADK2t44UADmyDDG6HCaoUxwxjCWXmEAtiTIqCTCCZoAVkwAHgBCXr7+ASRpcAAyoXBZOXkgwcYJxsgeJLwswtDu2sahMADqrjAAFsgAHAAMmkMQCaNe2l1DcB0OjZrGcACO6Dj7KSTpmUjZubEgCWk4kdG3TKFhwnAAiugQ8E03mhgPXGLimyAATICvDhhG8AMIQNIZLpQaC7EDoBISHp2a4JGg0IA)
```sh
--parser babylon
```

**Input:**
```jsx
function * a() {}
async function * b() {}
class T {
  async * c() {}
}
```

**Output:**
```jsx
function* a() {}
async function* b() {}
class T {
  async *c() {}
}

```
The third function is inconsistent with the above.

**Comment by jamieYou** [comment]
Now I mainly use webstorm to develop it. It comes with formatting function. However, the configuration of its "*" symbol can only be selected. Prettier is mainly for colleagues, I am accustomed to webstorm.

**Comment by lydell** [comment]
@jamieYou I don't understand, why use another formatter if you're using Prettier?

**Comment by jamieYou** [comment]
@lydell I always use webstorm. Using Prettier is for team specification. However, the team does not yet fully accept Prettier, so it is now used by Prettier with ESLint. Automatic formatting is not turned on.

**Comment by thorn0** [comment]
closing in favor of #7590
