### ISSUE TITLE
[CSS] newlines/spaces between front-matter and comment

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#4687]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBnCBbOGACwEsoBzLdVLLAegCoACSPA2JhurAOlwOJlyTYFgC+IADQgIABxglo2ZKACGAJ3UQA7gAUNCZSlUA3CCQAmUkACN1qsAGtCAZVkOhyGOoCucaWTYcOowuvbkeKrIAGaqADZB0gBW2AAeAEL2Tq6qBAAyZHAx8Ykg7upB6sjg2MrSsupkMADqlsTIABwADPVaQc32stUNcJUmRdLqcACOPiRTYaoRUUixCf4gQXgkXr4b2EJxcACKPhDwxevSMKo2rRbtSABM1-YkcUIAwviR1VDQExAPiCABVbkY1kExGIgA)
```sh
--parser css
```

**Input:**
```css
---
something
---

/* comment */
.something {
}
```

**Output:**
```css
---
something
---
 /* comment */
.something {
}

```

**Expected behavior:**
Same as input.

**Comment by evilebottnawi** [comment]
@ikatyang should we always print one empty newline between front-matter and content?
