### ISSUE TITLE
Line break after =

### ISSUE THREAD

**Issue by domoritz** [prettier/prettier#4707]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wCMBLKJPACgB0o88IMZrg8BbAQzQuOpQArp1JxsAbjzp4sagElY4gG7cANgB5ho8QD48AXwYBKPAF59AIUoBhaADNyAc3MMmJbjCIA6fgH0JEAAaEBYYcmgiZFBubGwIAHcABViEKJRuZQhyABNgkFJsbjAAazgYAGUMYsonZBhsITgQyiJxGCSipx5ke3U2kIArIjRLItLyiu5OOAAZSjhe-uaQauw27GQQGABPDDgiMGxyVnyMY9gAdVyYAAtkAA4ABhDziDbLoowt84OVRZC2DgAEchOQgZ1uN1uEs1AMQG1OOR6o0VkRamo4ABFIQQeCw+Ewbika45O7IABMIQa3HIalqdk4PRQUGgAJAQjaABViek+nC4AYDEA)

```sh
--parser typescript
```

**Input:**
```tsx
export const bin: (
  opt: { maxbins: number; extent: Interval<number> }
) => BinConfig =
  stats.bin_;
```

**Output:**
```tsx
export const bin: (
  opt: { maxbins: number; extent: Interval<number> }
) => BinConfig =
  stats.bin_;
```

**Expected behavior:**

```tsx
export const bin: (
  opt: { maxbins: number; extent: Interval<number> }
) => BinConfig = stats.bin_;
```

**Comment by lydell** [comment]
Possibly related: #4674

**Comment by ikatyang** [comment]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wCMBLKJPACgB0o88IMZrg8BbAQzQuOpQArp1JxsAbjzp4sagElY4gG7cANgB5ho8QD48AXwYBKPAF59AIUoBhaADNyAc3MMmJbjCIA6fgH0JEAAaEBYYcmgiZFBubGwIAHcABViEKJRuZQhyABNgkFJsbjAAazgYAGUMYsonZBhsITgQyiJxGCSipx5ke3U2kIArIjRLItLyiu5OOAAZSjhe-uaQauw27GQQGABPDDgiMGxyVnyMY9gAdVyYAAtkAA4ABhDziDbLoowt84OVRZC2DgAEchOQgZ1uN1uEs1AMQG1OOR6o0VkRamo4ABFIQQeCw+Ewbika45O7IABMIQa3HIalqdk4PRQUGgAJAQjaABViek+nC4AYDEA)
```sh
--parser typescript
```

**Input:**
```tsx
export const bin: (
  opt: { maxbins: number; extent: Interval<number> }
) => BinConfig =
  stats.bin_;
```

**Output:**
```tsx
export const bin: (
  opt: { maxbins: number; extent: Interval<number> }
) => BinConfig = stats.bin_;

```
