### ISSUE TITLE
Bug: Markdown reference links need to always be single-line

### ISSUE THREAD

**Issue by orta** [prettier/prettier#4709]
**Prettier 1.13.5**

Effectively when prettier meets a reference link + url that's longer than the prose-wrap it will move the link to the next line. This breaks the markdown.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKBBA5gQwJZQA0ABDlMQfAE5wDOMBWxMVOAJnALQQBmPAdMQCaEAK7EwZYtAA2AT2JY4MYjIhZaxAO4ALBMTliA5DVUQIAa0bEeEKsz0BbEjk0QADu4i04bZhG09chxidyoIACMZOEd0RxwFHDAYURwZeWIdHAA3OGkwMFEqGjZBABU9GiNNGB1GTQBJCSk2AJgArTsLUnDRKD9avE002ggSCzg4d1JyAno0mRwGaGqzDR6xfps7dBC2BIpyAAU4KjwZdHQAbVwAXSRMmBh3WiQAejeo9X4sPFrRCL8SCON4AJgADABGABsnHBAE5OJCACycHCcXQQaKcKBwLScX7-CKcPp4XJUHxoqBQTZgRg4vGcdpY2icWxUUSOVlkNhsuBLIp0N4AYkocCwrHgnB8OEc0VotHkGL+OgJKoB1xptAAjjIhpAsfdHs9Xh8tOb+ARbJ0qDJSsC3jgqAwwNEwfD4VCABzIt77GA4CKuOBvLW66V4RzuJVDWCcOruKlyRx2OD8HQwOXXMKRCAwWhGjMm95vHMRPM-dWAvAQECEEAeZZQWjIUBO8JaI5OhAtlA5CB4Nh1kARVhgCYwADK7iSjGQLFEcHrc1OMCOrCw8WQPBGS5AACtaAAPABCY4nk9lcAAMgQ4Nvd-WZxTTsgQPEqBZWlooMOwpQAHVB1qZAvXBJ9wh8ADWHcN80i0BIW3rGhtVEPAaHXHBNxwB8ZB8esfEcPB5w5PdaEYaIAEVRDze8kB3PC9wDCIgLYECkFBesWHwPUoCwABhCBHC3FAaVxYdRB8MpA17BifAAX3koA)

```sh
--prose-wrap always
```

**Input:**
```markdown
Again, an interesting trade-off. You can only get logs when you're looking for them, as opposed to when a problem
may actually have occurred. There's things I can do to work around this also, keep an installation's logs around for
a day in Peril

[ga]: https://blog.github.com/2016-09-14-a-whole-new-github-universe-announcing-new-tools-forums-and-features/#integrate-seamlessly-with-github
[nosqliscool]: https://www.infoworld.com/article/2990184/database/nosql-simply-isnt-hip-anymore.html
[probots]: https://probot.github.io
```

**Output:**
```markdown
Again, an interesting trade-off. You can only get logs when you're looking for them, as opposed to when a problem
may actually have occurred. There's things I can do to work around this also, keep an installation's logs around for
a day in Peril

[ga]: 
  https://blog.github.com/2016-09-14-a-whole-new-github-universe-announcing-new-tools-forums-and-features/#integrate-seamlessly-with-github
[nosqliscool]: 
  https://www.infoworld.com/article/2990184/database/nosql-simply-isnt-hip-anymore.html
[probots]: https://probot.github.io
```

**Expected behavior:**

```markdown
Again, an interesting trade-off. You can only get logs when you're looking for them, as opposed to when a problem
may actually have occurred. There's things I can do to work around this also, keep an installation's logs around for
a day in Peril

[ga]: https://blog.github.com/2016-09-14-a-whole-new-github-universe-announcing-new-tools-forums-and-features/#integrate-seamlessly-with-github
[nosqliscool]: https://www.infoworld.com/article/2990184/database/nosql-simply-isnt-hip-anymore.html
[probots]: https://probot.github.io
```

**Comment by ikatyang** [comment]
This behavior is currently controlled by `--prose-wrap`, see #3531.

I'm not sure what should we do here since this formatting is valid in the CommonMark spec.

**Comment by orta** [comment]
Interesting!

Taking the example from the test case, this is likely an issue with the non-commonmark md renderer I'm using (it's a 4-5 year old ruby app) - as the examples in #3531 work fine in GitHub ( see below )

[just-url][] [url-with-short-title][] [url-with-long-title][] [long][] [long-with-title][]

So I'm going to close as not a bug, and the implementation is correct - thanks @ikatyang 

[just-url]: https://example.com
[url-with-short-title]: https://example.com "title"
[url-with-long-title]:
  https://example.com
  "a long, long title. It's really really long. Here have words."
[long]:
  https://example.com/a-long-url/another-segment/yet-another-segment/a-really-long-file-name.php.aspx
[long-with-title]:
  https://example.com/a-long-url/another-segment/yet-another-segment/a-really-long-file-name.php.aspx
  "look a title!"
