### ISSUE TITLE
Formatting range within constructor throws syntax error if range contains `super()`

### ISSUE THREAD

**Issue by MarkusSN** [prettier/prettier#4711]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCpyYw7AA6UOOkURATgK5gwS0AUAlCeZZZvQA5w27bjgC+5MSAA0ICPxgBLaJmSh0tWhADuABQ0JVKdADcIigCYyQAI1rowAazgwAyvweKoAc2QwGcLJemEIwuvbeALboyABm6KghsgBWmAAeAEL2Ti6u6JFwADJecHEJSSAetCG0yLboNgCeqNDW-LReMADqljAAFsgAHAAMsu0QIV32-HXthEImpbK0cACO9Ior4ehRMUjxiYEgIZGKfgGymF7eqHAAivQQ8GWHsjANPRb9yABMb-aKVDXADCEEi0TqUGgSxA9BCeAaRgOFXsPjgrnetBgyAAzKMQKjvHAAKJQKxIHEARjEYiAA)
```sh
--parser babylon
--range-end 31
--range-start 30
```

**Input:**
```jsx
class Test {
  constructor() {
    super()
  }
}
```

**Output:**
```jsx
SyntaxError: super is only allowed in object methods and classes (2:5)
  1 | {
> 2 |     super()
    |     ^
  3 |   }
```

**Comment by bakkot** [comment]
Fixing this should just be a matter of passing `allowSuperOutsideMethod` to babylon, assuming that's desirable.

**Comment by JamesHenry** [comment]
The same thing is true for other things, e.g. `await` when the async function is not included in the range. (reported via https://github.com/nrwl/precise-commits/issues/18)

I will report that here separately for clarity.
