### ISSUE TITLE
Assignment can exceed the print width

### ISSUE THREAD

**Issue by tommedema** [prettier/prettier#4712]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBzATgSwBMBRQ7ONAFQgHEDCBJeAWwCEIBXKQgQwIswBeTHAAeABwi4YaAHR4ipclVr0mcNp2598A4QsJCAfJmAAdKJky44MDrksGA3BYC+TkABoQEcTHzoyKB8uBAA7gAKfAhoyCA8AG4QRF4gAEa4PGAA1rYAyuJZ+FDYyDC4HHDexWhw0hGZ2Mw8yABmPAA2td4AVmiirJk5+TzMcAAyxXBtnd0ghbi1uHFpPGkAnh3QqeIEsADqRDAAFsgAHAAM3rsQtfuZ4nG7FHUJ0942AI4c+DYNPE0Wkh2l0qiBasx8GUKmC0MVsB04ABFDgQeAzUHeGBrQ6EE7IABMWMy+A68IAwhBmM04lBoO8QBxapQ1rFgbM4K5XEA)
```sh
--parser babylon
```

**Input:**
```jsx
const gridEdgesToGridItemBoundaries = exports.gridEdgesToGridItemBoundaries = grid => {
  return grid;
};
```

**Output:**
```jsx
const gridEdgesToGridItemBoundaries = (exports.gridEdgesToGridItemBoundaries = grid => {
  return grid;
});

```

---

Original post:

**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAlgMw1AQwFs4MATCOAZwzgA8sqYAaDAJzjAFc2rSuADgHcCbMjSxQMMABakA5myxkMQmVgA2pARxxYGUeRgGiEMfMWoYusTRZLYaNrAEcucADpQcENhgAUWuY6cABuAHKWGBB4BFBg1DC+kSRUAJQYwF4Avl5eWDD+HiBUMhBcGiryCHBsBPDWUK7u9lZcVJJGkmAcJLDGEEx6dFa4xqb9IcOO+BDBgx0ARlrFaSDMIBACMFjQVMigomwQQgAKE-soBKEQyusgi3VgANZwMADKJmCdyDBs7htJHw2DBTnV5EQCMgcAQNHwNgArKh0ABCT1eH0sABlJHBobD4SATLxasgHgRFgBPDTQe46SQwADqylkyAAHAAGDY6QZwRl1ARkkLA0J4jYcNxYDhgggQqFIGFwuAbPhELC-f7KkqdLQARS4czxCoJWpgFOZZFZSAATBs-gRNJ0AMIQIiQslQaBikDtOAAFQpl0VfGy2SAA)
```sh
--parser babylon
```

**Input:**
```jsx
// if name does exist, recurse upwards in the grid while prefixing parent names until name is unique
for (let prevName of ancestorNames) {
}

it("should generate unique names using increment postfixes if parent prefix is not possible")
```

**Output:**
```jsx
// if name does exist, recurse upwards in the grid while prefixing parent names until name is unique
for (let prevName of ancestorNames) {
}

it(
  "should generate unique names using increment postfixes if parent prefix is not possible"
);

```

**Expected behavior:**
```jsx
// if name does exist, recurse upwards in the grid while prefixing parent names
// until name is unique
for (let prevName of ancestorNames) {
}

it(
  "should generate unique names using increment postfixes if parent prefix is" +
  "not possible"
);

```

**Comment by tommedema** [comment]
Same for this case:

```jsx
const gridEdgesToGridItemBoundaries = (exports.gridEdgesToGridItemBoundaries = grid => {
  return grid;
});
```

Expected:
```jsx
const gridEdgesToGridItemBoundaries =
(exports.gridEdgesToGridItemBoundaries = grid => {
  return grid;
});
```

OR

```jsx
const gridEdgesToGridItemBoundaries =
exports.gridEdgesToGridItemBoundaries =
grid => {
  return grid;
};
```

**Comment by lydell** [comment]
Comments: #265
Strings: #4123 and #4225 
Case in second comment: Not sure

**Comment by marcospgp** [comment]
Bumperino

**Comment by chowey** [comment]
This also affects statements that can easily be split onto multiple lines.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQGsCWUA5gCYQC22AvNsAL4DcAOlAcWeQHQAWEmAznGp5CpCpzKs4AT2FsxXCPxiZ8YbnNEdOAIzhwYAGyE152sIfSVTW8ZnQwjcflHS4T2IgYCCUfOXRDAGlbcgAKAEpmKBAAGhAIAAcYfGh+ZFAsTAgAdwAFLAR0lHRUCHwSOJAdezB3GABlRPQwUWQVAFc4eO4YckMAdW58eH5msDgGopH8VBHpZHB+dPjCQUwYPPsiAOQAM0DBeIArfgAPACFa+oarOAAZQjh9w+6QU7OG0WMARQ6IeAvQxHEDNARwTCLHToHTSQzQKqJVSwAYVGDcZAADgADPEkUo4AN7IlFkjnBDUM94gBHf7wLZJYogdD8AC0UH0JDglXimDgtPwfK26B26CBIME5Hw7UwXXi-G+cD+AOeSAOwLeMBhqJI6OQACZ4ip0PhDKIAMIUXYoKDQKkgDqCAAqMOK6sEdDoQA)
```sh
--parser babylon
```

**Input:**
```jsx
var kingdom = {};
kingdom.horse = kingdom.donkey = kingdom.ostrich = kingdom.beetle = kingdom.clam = kingdom.rattlesnake = getAnimalKingdom();

```

**Output:**
```jsx
var kingdom = {};
kingdom.horse = kingdom.donkey = kingdom.ostrich = kingdom.beetle = kingdom.clam = kingdom.rattlesnake = getAnimalKingdom();

```

I'd expect something more like this:

**Expected:**
```jsx
var kingdom = {};
kingdom.horse =
  kingdom.donkey =
  kingdom.ostrich =
  kingdom.beetle =
  kingdom.clam =
  kingdom.rattlesnake = getAnimalKingdom();

```

**Comment by thorn0** [comment]
Closing this issue as it's too unspecific.

There are separate open issues for individual problems mentioned here:
- see https://github.com/prettier/prettier/issues/4712#issuecomment-397956457
- Assignment chains: https://github.com/prettier/prettier/issues/4340
