### ISSUE TITLE
Format yaml front matter

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#4725]
It should apply to `css` and `markdown`.

**Comment by j-f1** [comment]
What do you think about adding front matter support to all parsers (able to be switched off by the parser if it conflicts with the language’s syntax) and formatting the YAML there?

**Comment by ikatyang** [comment]
Sounds good to me, and we should also extract the shebang support:

https://github.com/prettier/prettier/blob/dcf44ffbdc2f403de02f12516b0c6d5d5813b16f/src/common/parser-include-shebang.js#L3

but I'm not sure what should the API look like since it contains both parser and printer part.

**Comment by j-f1** [comment]
How about a middleware-type API, where each layer returns a doc based on a portion of the source string, and calls a provided `next()` function with the remaining source string to get the doc for that substring.

**Comment by ikatyang** [comment]
We should probably split out the `language` first since this looks like a language-level operation, see https://github.com/prettier/prettier/pull/4586#issuecomment-394132363 for more info.

**Comment by ikatyang** [comment]
Let's track the plugin api thing in #4774.
