### ISSUE TITLE
Import and export formatted with different logic

### ISSUE THREAD

**Issue by k15a** [prettier/prettier#4729]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwBM4AzAQwFcAbAigZ3zIlbfY869fwF9mcEdPgDkLbhMmsRAHShwAHtjyES5anXyNmU3Vz4Cho8XtMQRIADQgImGKmgNkoCjkEB3AAquETlBQA3CFRiKxAAIxwKMABrOBgAZUxo1CgAc2QYHCo4a1SGODxPKLT0CmRKGgLrACsGBQAhKNj4hIp0OAAZVLgKiirckGScApxkCIpwgE8aaDDMHFSYAHUQmAALZAAOAAZrBYgC5ajMcYW4UYDe6xw4AEcqVFviilLypErqkAL0VEzswYMVJpGhwACKVAg8D6A2sMEmq2IG2QACY4VFUDRgQBhIRlcZQaDXEBUAoAFUmfk+cF4vCAA)
```sh
--parser babylon
```

**Input:**
```jsx
import { default as foooooooooooooooooooooooooooooo } from 'foooooooooooooooooooooooooooooo'
export { default as foooooooooooooooooooooooooooooo } from 'foooooooooooooooooooooooooooooo'
```

**Output:**
```jsx
import { default as foooooooooooooooooooooooooooooo } from "foooooooooooooooooooooooooooooo";
export {
  default as foooooooooooooooooooooooooooooo
} from "foooooooooooooooooooooooooooooo";

```

**Expected behavior:**

I expect that import and exports are printed the same. AFAIK the format of the import is intended so I would like if the export would align with that. The benefit it provides is that you can sort export statements a lot quicker if they are in a single line.

Also it looks a lot cleaner if you have a file which basically only reexports other modules.

**Comment by j-f1** [comment]
Note that these don’t get broken when you use the (canonical and stage 1, respectively) shorthands:

**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgDMITSzyLKSicJ18ByYql1khgHSjgA9s8ibIZRp1GzYZIgMQAGhARMMVNADOyUAEMctAO4AFbQnUpNANwioAJnJAAjHJrABrODADKmJ6igBzZDA4AK5w8j6qcHj6jr7omsiEmgA2EfIAVqo8AEKOLm7umuhwADI+cAnJqSBeOBE4yPaadgCeSdC2mDg+MADq1jAAFsgAHAAM8p0QET2OmA2dcHVm5fI4cACOQahr0Zqx8UiJKaEgEeioAcEnqj6+SXAAikEQ8BXH8jBNfVaDyABMH0cqCStwAwnQ4g0oNAViAghEACpNExHCIAXzRQA)
```sh
--parser babylon
```

**Input:**
```jsx
import foooooooooooooooooooooooooooooo from 'foooooooooooooooooooooooooooooo'
export foooooooooooooooooooooooooooooo from 'foooooooooooooooooooooooooooooo'
```

**Output:**
```jsx
import foooooooooooooooooooooooooooooo from "foooooooooooooooooooooooooooooo";
export foooooooooooooooooooooooooooooo from "foooooooooooooooooooooooooooooo";

```
