### ISSUE TITLE
member expression in case inside switch

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#4735]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnA7gSxmAFgAgAoBGASn2AB0p9b8wBDVOfAEjgA8w4AHGTaADoAbnABOATwBq46bJmSFcxfNWSAMtADmAWTgxcEACaFS1Ohfwi1y20vuzNULQAUxEHuJgSk5y7QAjMTgGAGsAbmoAXxAAGhAPfmhUZFAGMXd0F3SEFJQGYQhMIziQIIYwUP0AZR4KzGdkGDEAVzh4huYxGDcGLQBbBmQAMwYAG2Z4gCtUDgAhMQqqmGqGfrh1BrgR8cmQOrEu5DKGAIkx6FKeMQaYAHVig2QADgAGeOuIZjvFnmPruBdUSlYIARxamGCvQGQyQowm7TQcH6mCarURqAaWjGcAAii0IPAdgj4jBTg8jE8kAAmUmLTBjLEAYQg-UGxyg0G28RazAAKqc8vDmFEokA)
```sh
# Options (if any):
```

**Input:**
```jsx
switch (1) {
    case $exception.veryVeryVeryVeryVeryVeryVeryVeryVeryLongMethod().veryVeryVeryVeryVeryVeryVeryLongProperty:
        break;
}
```

**Output:**
```jsx
switch (1) {
    case $exception.veryVeryVeryVeryVeryVeryVeryVeryVeryLongMethod()
        .veryVeryVeryVeryVeryVeryVeryLongProperty:
        break;
}
```

**Expected behavior:**

Need discussion

/cc @vjeux I know it is very very rare use case, what do you think?

Ref: from `plugin-php` (found this use case in one old php library)

**Comment by vjeux** [comment]
It would be great if you could use real names, otherwise it's harder to make decision based on made up ones.

Though, it doesn't strike me as being badly printed. How would it print it differently?

**Comment by evilebottnawi** [comment]
@vjeux for me looks also good, just question what do you think same

**Comment by evilebottnawi** [comment]
Output as expected
