### ISSUE TITLE
Prettier removes spaces between the comments

### ISSUE THREAD

**Issue by xeoneux** [prettier/prettier#4750]
**Prettier 1.13.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgIIAOBOcAHvFACa4DCEAtgdAjDsADpQ46SPOwB1AJapUAWQgBXWAAoAlG07duAehU4A4nFZRtAdwgAnANY4ChiADchlOIZzoqOPXABGAZhxComGI7BwAHRKymo4AMpwcDiSMCKYKgDm2gJungBmRjj0RtHemcFQIarqyTCpHsU4YdyBMAAWCDKGcJiSqDC4ALwAfIpcoerKOA1CmIGY2uF+8DIcAyXDyi4eSDgtbR3jK+5VNcoAvnKce0ODOACSPn6wQujwPNAwhuhgrNABzmlmFta2lIVhvtuKNxt5fI44vc4HRYC83vJTodjgtqmdAmB7mB6jJ5Dhev0gWduJAfBBUEFUBBEjIAOQAUUMFns6W8lG8iS+HkCtJRRORIQOJwG4JuUPgsOerxgePmQIAVFUcPKImI8AAlAAqOBoAHkAHKa9V4Gja+kADTwYgACgAZelKxWo5U4fVGejoUQATxGjUmOHS0jeQmguAM7UoOFc0Uxojgke8vpjTzI73SDkdOAhDw9UHQyXoLBwqCErhehi9ABoo7EA1lSZYEEIEJ8LrTG2YMAFIw04PQcI0WoDhvKVML+aTfI84dL8es4ABHSRCFp056SdLpCkAWlJUrevKRk9YmCEjAp0yM+eiXWn+5l4TPBAvMCvyUl8JgfPOp-PcEvLzJBM2jWr8Nh2DIoITDMQQ7BikhMiwoFWOBhgokiYQACJwGAGCGByvpjHW9gYPA9iYBAXw8I4PD1OgiaBlAwahjg0ARE+L5vkESKWOg5Ecf+r6AXAVwQkxcDjucYRaKwryQNInTDosUHZrBaSBNo9SBGUeBgPJsCYLidjMtWclSAZCgEnK5zcL+z6CVxSLDIEtjPhAXrxoiqLAjgdSNFAMiiv4N59NZixLFmAkAdeok3J8t5BeJknhUsYQAa0Dg4IkQiNlwvGoJIcDVgArFGPq2Ok6DtDASlohF84wAhXB2ZxwmxcFwEysV1bAAGFj0GsZkKZgADaAAMAC6OBHE5ArecSvm9gFGzVfioWzfyMlJjg+WFX1DDbXun4jJR5hWHkrAGCY8a1T53AtI1hjNVFQkxdcHVlBinqoDIQ0GeNE3fil3AzfNSx+U0K0dGthI2al6gAKoEJQ0JZjBzhCA021QzVG3KA9TWEeMkwwNM0JzGjXEAGqeoVaw4xiAPTUDdXDKD-Ls9NnBCkUuikEwhisBVVXQ4QBCcCAlYgBABBxKGyCgHxFh6NafEIJgyAgOglgQDYksgGWrzGFMBCvByyDrkVIDgnYMCgfmHrIJVqCTFLABWmCkAAQvCxuk+gha2t4cBO56rsgKbhiTIYmuuOgrhelSUD6+Y3jlDYDTIAAHGNUtnZMAgvAQmvmK0diNvrLRLiucD24kjtIM74eTPQQgW4YhVS6eUCJBSACKkgQPAocu1bfiuMIlCZ0gABMUtSiIHJ0PQDcgFAzD65IkyavHGuN2HcAHAcQA)
```sh
--parser babylon
```

**Input:**
```jsx
class App extends Component {
  componentWillMount() {
    // Get network provider and web3 instance.
    // See utils/getWeb3 for more info.

    // getWeb3
    //   .then(results => {
    //     this.setState({
    //       web3: results.web3
    //     })

    //     // Instantiate contract once web3 provided.
    //     this.instantiateContract()
    //   })
    //   .catch(() => {
    //     console.log('Error finding web3.')
    //   })
  }

  instantiateContract() {
    /*
     * SMART CONTRACT EXAMPLE
     *
     * Normally these functions would be called in the context of a
     * state management library, but for convenience I've placed them here.
     */

    // const contract = require('truffle-contract')
    // const simpleStorage = contract(SimpleStorageContract)
    // simpleStorage.setProvider(this.state.web3.currentProvider)

    // // Declaring this for later so we can chain functions on SimpleStorage.
    // var simpleStorageInstance

    // // Get accounts.
    // this.state.web3.eth.getAccounts((error, accounts) => {
    //   simpleStorage
    //     .deployed()
    //     .then(instance => {
    //       simpleStorageInstance = instance

    //       // Stores a given value, 5 by default.
    //       return simpleStorageInstance.set(5, { from: accounts[0] })
    //     })
    //     .then(result => {
    //       // Get the value from the contract to prove it worked.
    //       return simpleStorageInstance.get.call(accounts[0])
    //     })
    //     .then(result => {
    //       // Update state with the result.
    //       return this.setState({ storageValue: result.c[0] })
    //     })
    // })
  }
}

export default App

```

**Output:**
```jsx
class App extends Component {
  componentWillMount() {
    // Get network provider and web3 instance.
    // See utils/getWeb3 for more info.
    // getWeb3
    //   .then(results => {
    //     this.setState({
    //       web3: results.web3
    //     })
    //     // Instantiate contract once web3 provided.
    //     this.instantiateContract()
    //   })
    //   .catch(() => {
    //     console.log('Error finding web3.')
    //   })
  }

  instantiateContract() {
    /*
     * SMART CONTRACT EXAMPLE
     *
     * Normally these functions would be called in the context of a
     * state management library, but for convenience I've placed them here.
     */
    // const contract = require('truffle-contract')
    // const simpleStorage = contract(SimpleStorageContract)
    // simpleStorage.setProvider(this.state.web3.currentProvider)
    // // Declaring this for later so we can chain functions on SimpleStorage.
    // var simpleStorageInstance
    // // Get accounts.
    // this.state.web3.eth.getAccounts((error, accounts) => {
    //   simpleStorage
    //     .deployed()
    //     .then(instance => {
    //       simpleStorageInstance = instance
    //       // Stores a given value, 5 by default.
    //       return simpleStorageInstance.set(5, { from: accounts[0] })
    //     })
    //     .then(result => {
    //       // Get the value from the contract to prove it worked.
    //       return simpleStorageInstance.get.call(accounts[0])
    //     })
    //     .then(result => {
    //       // Update state with the result.
    //       return this.setState({ storageValue: result.c[0] })
    //     })
    // })
  }
}

export default App;

```

**Expected behavior:**
It should not remove lines between the comments. I think this started happening recently with the new prettier release.

**Comment by lydell** [comment]
As far as I can tell after some quick testing, this behavior has been present at least from 1.0.

Given that the empty line is preserved for _toplevel_ comments, I think it should be preserved for comments within blocks as well.

Minimal example:

**Prettier 1.13.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACacA6U-oYwDuEeeweGGh2VNmJZUAvniADQgQAOMAltADOyUAEMAThIjEACpIQiUYgG4R+AE04gARhLFgA1nBgBlHgf5QA5shgSArnC5WhcCTFn7rAWzHIAMzEAGzcuACshAA8AIX0jE1MxHzgAGSs4QJCwkAsJNwlkXTEdAE9g6G0eCSsYAHVNGAALZAAOAAYuaog3Ov0eIuq4ApVMrgk4AEcHfgmvMV9-JCDQ5xA3H347RzWhK2tguABFBwh4LNWuGBKGjWbkACYr-X5g-YBhCB8-IqhsbQcbgAKiUlCs3CwWEA)
```sh
--parser babylon
```

**Input:**
```jsx
// one

// two

{
  // one
  // two
}

```

**Output:**
```jsx
// one

// two

{
  // one
  // two
}

```

**Comment by thorn0** [comment]
closing in favor of https://github.com/prettier/prettier/issues/8234
