### ISSUE TITLE
HTML: Preserve YAML front matter block

### ISSUE THREAD

**Issue by MarcelWoerner** [prettier/prettier#4752]
Prettier is smart enough to preserve YAML front matter blocks in Markdown files, but currently strips them from HTML files, which breaks HTML sites.

The same logic that allows Prettier to ignore YAML headers in Markdown files should be applied to HTML.

**Prettier pr-4392**
[Playground link](https://deploy-preview-4392--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBadAdWcDOMBuAhgE5IAEAtgJ5lHFaFQQwAWcxd51ZzbxtJLOlRYyZUQB4ccMDACW0AHyixZCQBM5+MmAA2hHDgC8GEAHNic9akixCcqO1PKoqt2s3a9B46YtXUAA8yf2sKEjMHILJCXTkzKBsEeHoQF3cMjy0dfUMTcDhdXTIcFksoAGsyeECYJOxU9MzmiRYAVkUACThCdTjHCQB6dqbmsSHPUfcJrSmZ-Bch6VkFKEUQABoQCAAHeWgcZFASYggAdwAFEgRDlEJ8CCtNkAAjYkIwCrgYAGUdj4cZmQMGIAFc4FsHNJiDALu8zOFkAAzWLSLYAKxwgQAQu9Pt8foQKHAADIOODI1EQkD-YjQ5CvQgvKi6aDPHblGAAdSsrGQAA4AAxbDkQaRc947Bkc3DsfAUrbEOAAR1BciVcMICMIlN0aJA0gocmBYOpOEBujgAEVQcwKUgUXrqTAmTz1HykAAmLYg+z9MwAYQgFERKCYjmeoOkABUmbdHdIAL6JoA)

**Input:**
```jsx
---
testvar: my var
anothervar: my other var
---
  
 <section>
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="cell shrink text-center">
                <h5>Headline</h5>
            </div>
        </div>
    </div>
</section>
```

**Output:**
```jsx
SyntaxError: Invalid left-hand side in prefix operation (1:3)
> 1 | ---
    |   ^
  2 | testvar: my var
  3 | anothervar: my other var
  4 | ---
```

**Expected behavior:**

**Comment by evilebottnawi** [comment]
@MarcelWoerner we don't support HTML right now https://github.com/prettier/prettier/issues/1882

**Comment by phifa** [comment]
@evilebottnawi i was just running into the same issue. is #1882 the official issue? any plans to make this work? thanks!

**Comment by lydell** [comment]
That's the official issue.
