### ISSUE TITLE
1.13.x breaks eslint-plugin-html/eslint-plugin-prettier

### ISSUE THREAD

**Issue by nappy** [prettier/prettier#4759]
Upgrading prettier from ~1.12.1 to ^1.13.6 causes eslint-plugin-html to break.
I add this issue here, because I think this violates semver.

**Environments:**
- Prettier Version: 1.13.6
- Running Prettier via: eslint-plugin-prettier
- Runtime: Node v10.5.0 Yarn 1.7.0 Npm 6.1.0
- Operating System: Windows
eslint@^5.0.1
eslint-plugin-html@^4.0.5
eslint-plugin-prettier@^2.6.1
prettier@^1.13.6

**Steps to reproduce:**
Add plugins html and prettier to .eslintrc
Add an html file to your project
Run eslint **/*.{js,html}

**Expected behavior: (1.12.1)**
yarn run v1.7.0
$ eslint **/*.{js,html}
Done in 5.89s.

**Actual behavior: (1.13.6)**
yarn run v1.7.0
$ eslint **/*.{js,html}
No parser could be inferred for file: C:\Code\eslint-html\assets\index.html
Error: No parser could be inferred for file: C:\Code\eslint-html\assets\index.html
    at normalize (C:\Code\eslint-html\node_modules\prettier\index.js:7058:15)
    at formatWithCursor (C:\Code\eslint-html\node_modules\prettier\index.js:10378:12)
    at C:\Code\eslint-html\node_modules\prettier\index.js:31217:15
    at Object.format (C:\Code\eslint-html\node_modules\prettier\index.js:31236:12)
    at Program (C:\Code\eslint-html\node_modules\eslint-plugin-prettier\eslint-plugin-prettier.js:412:45)
    at listeners.(anonymous function).forEach.listener (C:\Code\eslint-html\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Code\eslint-html\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Code\eslint-html\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Code\eslint-html\node_modules\eslint\lib\util\node-event-generator.js:280:22)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by duailibe** [comment]
The problem is Prettier does not support *.html files and `eslint-plugin-prettier` should not try to format those.

**Comment by nappy** [comment]
> Closing this since there's nothing we can do here.

This is 100% a false call, because it worked in 1.12.

> The problem is Prettier does not support *.html files and eslint-plugin-prettier should not try to format those.

The solution with eslint-plugin-html + eslint-plugin-prettier is not about formatting html, but javascript inside html script tags. (e.g. Polymer)

**Comment by j-f1** [comment]
Does overriding `*.html` in the Prettier config with `parser: babylon` fix the issue?

**Comment by nappy** [comment]
> Does overriding *.html in the Prettier config with parser: babylon fix the issue?

Yes this fixes the issue. Thank you.
Looking forward for prettier html support though, to clean up this configuration. I hope it will support inline script tags!

**Comment by duailibe** [comment]
> This is 100% a false call, because it worked in 1.12.

This was relying on a buggy behavior that would treat unknown files as JS (and because of that, would treat HTML tags as JSX).

> The solution with eslint-plugin-html + eslint-plugin-prettier is not about formatting html, but javascript inside html script tags. (e.g. Polymer)

I don't see anything in https://github.com/BenoitZugmeyer/eslint-plugin-html that would enable this behavior.

To achieve this functionality, `eslint-plugin-html` would need to call `prettier` directly passing only the JS code and setting the parser. I have no idea how this was working before.

**Comment by duailibe** [comment]
Understood now. 

`-html` plugin passes the filename to `-prettier` plugin and it passes to `prettier` to infer the parser. We have no parsers for `*.html` so `prettier` can only error.

`eslint-plugin-prettier` wasn't written with this use case in mind so they need to find a way to work together.

Again, I don't think there's something we can do here.

**Comment by j-f1** [comment]
@duailibe yeah, I didn’t realize the issue already had that label.

**Comment by BenoitZugmeyer** [comment]
eslint-plugin-html author here. Would a plugin option to fake the filename (ex: append a '.js') would make sense?

**Comment by suchipi** [comment]
@BenoitZugmeyer you can accomplish that with the `filepath` API option

**Comment by duailibe** [comment]
@BenoitZugmeyer unfortunately that will make ESLint reporter report a file that doesn't exist right?

**Comment by nappy** [comment]
Okay I am not as involved in the APIs as you, but from my understanding then, if prettier becomes a general code formatter (instead of a javascript formatter) and eslint remains just a javascript linter, then
eslint-plugin-prettier should always override the parser to babylon.
This seems the most appropriate solution for me.

Do we need a separate issue for this?

**Comment by j-f1** [comment]
Opening a new issue there is a good idea 👍

**Comment by BenoitZugmeyer** [comment]
So I added a new setting `html/fake-file-extension` to address this issue. As I am in the process of releasing a new major version of my plugin, this is not yet released, but you can try it with:

```
npm install eslint-plugin-html@next
```

See the upcoming [changelogs](https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/next/CHANGELOG.md) and setting [documentation](https://github.com/BenoitZugmeyer/eslint-plugin-html/tree/next#htmlfake-file-extension)

@suchipi I took a different approach here, basically I tell ESLint to report a fake file name to other plugins, not just prettier.

@duailibe It seems that the file path reported to plugins can be different than the ones in the messages, at least this is what I saw during my tests. Let me know if it works for you.
