### ISSUE TITLE
Should filepath be included in prettier.resolveConfig return object

### ISSUE THREAD

**Issue by BPScott** [prettier/prettier#4763]
`prettier.format` determines the parser to be used based upon the `filepath` key of the config you pass into it. That config can be built for a given file by calling `prettier.resolveConfig(filePath)`. However `resolveConfig(filePath)`'s output does not include a `filepath` key. This means I have to add `filepath` to the config before passing it to `prettier.format`.

Should I need to do that manually, or should calling `prettier.resolveConfig('check.scss')` return an object that contains `{filepath: 'check.scss'}`, thus removing the need for this extra step?

**Environments:**
- Prettier Version: 1.13.6
- Running Prettier via:  Node.js API
- Runtime: Node.js v8
- Operating System: macOS

**Steps to reproduce:**
In some folder that has prettier in the require() path:

Save the following as `check.scss`:

```check.scss
$greek: (
alpha: 100,
beta: 200,
gamma: 300
);
```

Save the following as  `check.js`:

```js
"use strict";

const fs = require('fs');
const path = require('path');
const prettier = require('prettier');

const filePath = path.resolve(process.cwd(), 'check.scss');
const text = fs.readFileSync(filePath, 'utf8');
const prettierConfig = prettier.resolveConfig.sync(filePath);
// It's easier to set this here instead of creating a .prettierrc
prettierConfig.trailingComma = 'all';

/*
Results in error:
No parser and no filepath given, using 'babylon' the parser now but this will
throw an error in the future. Please specify a parser or a filepath so one can
be inferred.

I would have expected this to use the scss parser
*/
console.log(prettier.format(text, prettierConfig));

/*
Adding the filepath to the Config makes things work. The text is parsed using
the scss parser, which is infered based upon the filepath in the options.
Question: should prettier.resolveConfig('check.scss') include the filepath key,
thus making this extra merge step unneeded.
*/
const newConfig = {
    ...prettierConfig,
    filepath: filePath
};

console.log(prettier.format(text, newConfig));
```

**Expected behavior:**

The first call to `prettier.format` uses the scss parser.

**Actual behavior:**

The first call to `prettier.format` fails with a "No parser and no filepath given" error, and falls back to using the babylon parser.

The second call to `prettier.format` uses the scss parser, as expected.

**Comment by duailibe** [comment]
I think it’d be more interesting returning the parser in `resolveConfig` ?

**Comment by suchipi** [comment]
I like that better :+1:

**Comment by BPScott** [comment]
After a bit of thinking (not the whole month, I've just been busy :p) and some poking around in prettier's internals I don't think adding either `filepath` or `parser` to the result of `resolveConfig()` is worthwhile.

It seems `filepath` is only used to infer a value for `parser` when one isn't passed in - hence @duailibe's preference for just pasing an object containing `parser` into `format()` in the first place.

Modifying the output of `resolveConfig()` is a bit weird as it is the output of the user's config - the normalisation of that config - including infering a parser if one is not passed - happens within `format()` so it feels odd to pull some of that inference up a level.

Instead I should be using `getFileInfo()` to get an inferred parser, and then pass that in:


```js
"use strict";

const fs = require('fs');
const path = require('path');
const prettier = require('prettier');

const filePath = path.resolve(process.cwd(), 'check.scss');
let text = fs.readFileSync(filePath, 'utf8');
const prettierConfig = prettier.resolveConfig.sync(filePath);
const prettierFileInfo = prettier.getFileInfo.sync(filePath, {ignorePath: '.prettierignore'});

if (prettierFileInfo.ignored) {
    text = prettier.format(text,  {
        parser: prettierFileInfo. inferredParser        
        ...prettierConfig,    
    });
}

console.log(text);

```
