### ISSUE TITLE
Parentheses incorrectly removed when combining await keyword with bind operator

### ISSUE THREAD

**Issue by joshlongerbeam** [prettier/prettier#4775]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwBMIBBAZwE8owAVAC1SgHMAaEiAZRvqdfwBffADMcEdPgDkAOgD0IgK60YqaBTJRiXGIpEipAbgA6UU5CgUCpAEIQYDRsxYV8AXnwBDarXwAKAEp3AD5CU3x8Cyt8HDgAR0U4aI9SSl4nVkCTKAjY3Rwcv08Ad09UAliEpJgApCRSHloMliyIuTl8TE8cT1gGJKSvWPwAN3LPABtTQWzTOAAPbDwSOBFPRQnrCDsHZopskDYQCExVdWRQbvFigAVuhApkEE8RiFRiQ5AAIx6wAGs4DAuF0wM5kDAcIkjswKHA8Dceix0J5kGsJrCjgArCjzGy-AFAzzoOAAGWYcFRkwxIC6OFhOCeX08XyoE2gn0wOGYMAA6u8HMgABwABiOnIgsJ5PUwT05AxwIwpR0qilQsQRniRKKQaOpsPQqHBkLgRwozgmcAAiop7BSdVSTSAYMy+cQBUgAExHCFlCbOADCEmRTyg0CVIEUsLozMe9vRcEEgiAA)
```sh
--parser babylon
```

**Input:**
```jsx
import { doAsyncThing, doSyncThing } from "./functionsAndStuff";

const doBothThings = async () => {
  const request = doAsyncThing();
  return (await request)::doSyncThing(); // parentheses are vital
};

export default doBothThings;

```

**Output:**
```jsx
import { doAsyncThing, doSyncThing } from "./functionsAndStuff";

const doBothThings = async () => {
  const request = doAsyncThing();
  return await request::doSyncThing(); // parentheses are vital
};

export default doBothThings;

```

**Expected behavior:**
Expected same as input.  
Output changes behavior of code, as the bound `doSyncThing()` no longer `await`s for `request` to resolve.

Current manual workaround is to alter 4th and 5th lines to
```jsx
  const request = await doAsyncThing();
  return request::doSyncThing();
```
to avoid behavior-mangling by Prettier

**Comment by joshlongerbeam** [comment]
Tagging @aikeru, super bind-operator advocate

**Comment by j-f1** [comment]
@ikatyang do you plan on doing this or should I add the `help wanted` label?

**Comment by ikatyang** [comment]
I'll assign myself before I start working on it.
