### ISSUE TITLE
AppVeyor permission

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#4780]
~~Send me your email and I'll give you the rebuild button. 😎~~

![image](https://user-images.githubusercontent.com/8341033/42123209-8434ffb0-7c80-11e8-8f9b-bbbbc7bafeec.png)

Closing since this is actually not an issue.

**Comment by j-f1** [comment]
Email is in my profile (@j-f1).

**Comment by ikatyang** [comment]
Changed to use GitHub Team to manage permission on AppVeyor, you should get the permission automatically.
