### ISSUE TITLE
prettier not reading the configuration provided from ale, in vim

### ISSUE THREAD

**Issue by yedhink** [prettier/prettier#4786]
im a total beginner to js. i used prettier + eslint as linters with ale in (neo)vim. i followed the instructions from the prettier documentaion to setup prettier with ale. but prettier is not reading  the options passed explicitely from the vim configuration in the form :-   
`let g:ale_javascript_prettier_options = '--single-quote --trailing-comma'`  
i use eslint and prettier together with the eslint-plugin-prettier+eslint-config-prettier.   
[relevant image link to show the error, my vim configuration and eslint configuration
](https://i.imgur.com/8RVpar6.png)  
why isnt prettier reading the options passed from vim? should i be creating a .prettierrc.json in the root of every project that im going to work on and add a rule for singleQuote? 
any sort of help would be appreciated.

**Comment by ikatyang** [comment]
I'm not familiar with vim but it seems you're using eslint-plugin-prettier (default  options) and Prettier CLI (options from ALE) simultaneously, which won't work. If you'd like to use them simultaneously, you should put your options in `.prettierrc`.

**Comment by yedhink** [comment]
thanks a lot. that was indeed causing the error. removed the eslint-plugin-prettier and all is good.
