### ISSUE TITLE
Incorrect formatting for union types within tuple types

### ISSUE THREAD

**Issue by grassator** [prettier/prettier#4794]
Prettier adds first one and then second empty line when formatting nested union of tuples.

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAcnAZ3gBMAeAFQD5sBebcgbgB0oX0tsAhAVwHNa8hEqRbZsAH2wBtJiACGsgDTYiAJwCWUXgF1RE6bIBGSlTA1bdUMZJngTazTr03Zxe2ceXrBkHHfmnK30ZILExWQAzJT0wsMlZAEYk5JTU1NkY2P1ZACY8-ILCoryM0Kz4kABmaprauvrq0tjLSgYQRRAIDBh1aAJkUDlVVQgAdwAFIYR+lDkANwh1YnaQQ1U5MABrOBgAZQwNx2QzbjgOzQI4VRhx9d4AWzlkCLkAG0uOgCsCAA9Oda2O12cnucAAMpo4M83h8QAdVJdVMhUJhCGANN0VhhzDAAOpLGAAC2QAA4AAwdbEQS649YYZHYwhXOZQjqqOAAR246nZtzkDyeSBe7zOIEu93Ux1Upw6BEcrzgAEVuBB4NCRR0YHJDPjiETkDlNet1K9HABhCD3R7IqDQVkgbiXcjambCy4AX3dQA)
```sh
--parser typescript
```

**Input:**
```tsx
type Nested<T> = T;

type Bug = Nested<
  | ["a", string]
  | ["b", string]
  | ["c", string]
  | ["d", string]
  | ["e", string]
  | [
      "f",
        | "11111111111111111111"
        | "22222222222222222222222"
        | "33333333333333333333333"
    ]
>;
```

**Output:**
```tsx
type Nested<T> = T;

type Bug = Nested<
  | ["a", string]
  | ["b", string]
  | ["c", string]
  | ["d", string]
  | ["e", string]
  | [
      "f",

        | "11111111111111111111"
        | "22222222222222222222222"
        | "33333333333333333333333"
    ]
>;

```

**Second Output:**
```tsx
type Nested<T> = T;

type Bug = Nested<
  | ["a", string]
  | ["b", string]
  | ["c", string]
  | ["d", string]
  | ["e", string]
  | [
      "f",


        | "11111111111111111111"
        | "22222222222222222222222"
        | "33333333333333333333333"
    ]
>;

```

**Expected behavior:**
```tsx
type Nested<T> = T;

type Bug = Nested<
  | ["a", string]
  | ["b", string]
  | ["c", string]
  | ["d", string]
  | ["e", string]
  | [
      "f",
        | "11111111111111111111"
        | "22222222222222222222222"
        | "33333333333333333333333"
    ]
>;

```

**Comment by nunocastromartins** [comment]
Just ran into this. This issue's title mentions "nested union types" but I could only reproduce it specifically with union types within tuple types.

Another (possibly simpler) test case: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA8gJwJYDmeUAhgDYA6UkUAzjBvPUhgNq0QC2cAKgJ4AHOABoMJKBBgALODn5CA6nmkBBADLQCAORLcMAH0ZS8tAMIQArmQAmAITgBlLnABKcSDmvy4KqNYCSMAqWNvYAoiS0fDwQDnC8Mg66cP60tBZwALoA3FRU6BgAYng49BiWMAIWMFQ0ZUwwLKxUGBgc3N7CeVCtrYbikjJygnBKqhpQ2sktvYbSJuZWdo7Obh5eI74BQSHLEVExcQmOyanpcFQ53QVxNNbl1VUMABT0JABGeGQmcLRiAGbwHAASlq0Hqv0abBm7V4Iy6UG6vQMYgk0lk3jGUnUmh03BmfSMC129ic3DWEE83i2gWCS3CkWisXiPESpzSGUu2RAwhAEAEMDw4OQoBIOBwEAA7gAFMUIWjIEAkABuEDw1h5IHeOBIYAA1nAYA4BLriARkDAcBleVIYJwyApjEwTWBHPLlHhlco+IqwGlNcRaLIYNKdQROCRkP9yEHeQArWgAD1sOv1hqS3DUxDgUZjIhACcTDjNZDgAEULJIc0ho2RYyATaVZIqYCNaGB8ALNQIJUGFDqBIqe79ZMqc7ycHAAI4WEpwUMkcORmt53lBzh4C1W-O0EvlyvwXN1-MwD5KazSZAAJl5lpIXzN5k4EcVEig45AFiDPA+CpXx95HtiCCdVLyQAAOAAGABfaCgA)
```ts
// Original
const test: [someType, anotherTypeWithALongName | thisCouldBeSomeRecordTypeAndItWouldBeEasyToSeeTheSameIssue];

// First output
const test: [
  someType,

    | anotherTypeWithALongName
    | thisCouldBeSomeRecordTypeAndItWouldBeEasyToSeeTheSameIssue
];

// Second output (stabilises after)
const test: [
  someType,


    | anotherTypeWithALongName
    | thisCouldBeSomeRecordTypeAndItWouldBeEasyToSeeTheSameIssue
];
```

**Comment by bradzacher** [comment]
[even simpler repro](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACA8hmAS2gGdsBebAbQB0ptsAfbAcgEMO2W6HmWAjQf25QAugG46IADQgIBYlBLJQbAE5qIAdwAK6hMpRsAbhEIATGSH5q2YANZwYAZQx3CUAObIYagK5wsgAWMAC2ADYA6kGE8CRuYHDOBrGExrFoyOAkyrIeJHBqMDq2nqFsyABmbOEFsgBWJAAeAEK2Dk7ObKFwADIecFU1dSCNTc4enuFwAIp+EPBDtYEgbmoFalnoWCRgaoQEVhiaBZG2GFnHcBvGg7IAjvPwJfKGIGwkALRQcHDmf1Y1HBHoQgSU2GUKkhqstZAVQoQfP4ViRJtM5gtBtDhisYGx+JELDAgsgAEyyXxsQjhSYAYQgoXKWSg0DuID8BQAKvjDDCRscPDBCeZicgAIwANgAvlKgA)

```ts
// --print-width=16
// --tab-width=2

// input
type Options = [
  | 'aaaa'
  | 'bbbb'
];
// expected unchanged output

// actual output
type Options = [

    | "aaaa"
    | "bbbb"
];
```

Note:
- the empty line that gets added.
- the extra indentation.


It's not just a typescript-specific bug.
The same bug occurs with `--parser`:
- `flow`
- `babel`
- `babel-flow`
- `typescript`
