### ISSUE TITLE
export default is moved after decorator

### ISSUE THREAD

**Issue by lipt0n** [prettier/prettier#4795]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKcAeAHCAnGAAgBM4AzAQwFcAbIgAUigzBgApgBfASnTBooBnQYQCimCgFtsNOISzwoxEQCU4FVgDoAwhGnQERYOkKE8CUnkIBeQm27WAfISi0a6TiAA0ICNhgAltCCyKAUeHgQAO4ACuEIISgUAG4QAcTeIABGeBoA1nAwAMrYGgFQAObIMHhUcD7lgnAEMbkVkhTIlDRNPgBWgpgAQrlgBcVScAAy5XBdFD31IKV4TXjI2RRZAJ400JnYeOUwAOrpMAAWyAAcAAw+hxBNJ7nYG4dwa8lzPuYAjlQAuZWhR2p0kN1eiAmpIAtVaktBOUKrIAIpUCDweaLHwwLZnYiXZAAJlxuQCNGRukkHQ2UAMmSoTQAKltEpC4JxOEA)
```sh
--parser babylon
```

**Input:**
```jsx

export default @connect({})
class Example extends React.Component {
  render = ()=> null
}
```

**Output:**
```jsx
@connect({})
export default class Example extends React.Component {
  render = () => null;
}

```

**Expected behavior:**
It should keep export default where I put it.

**Comment by j-f1** [comment]
Is there a reason you wrote it that way?

**Comment by seantimm** [comment]
Babel 7 is failing to compile some of our code due to a change that appears to require it after the export declaration.

**Comment by duailibe** [comment]
@seantimm Please post the code that is failing

**Comment by seantimm** [comment]
The example above was representative.  I worked around it by separating the export and the class definition which brought the decorator in line with the class, so I'm not blocked.  I was commenting because I think you'll start to see more of these complaints moving forward.

**Comment by lipt0n** [comment]
@seantimm is right, 
Babel 7 throw an error (and fails to transpile) if You put enything between decorator and class ( in this case export ) and prettier is  moving exports after the decorator. So for now I had to choose, disable prettier or downgrade Babel

**Comment by SimenB** [comment]
What about just

```js
@connect({})
class Example extends React.Component {
  render = () => null;
}

export default Example;
```
?

**Comment by lipt0n** [comment]
what about it? 
it will work ofc :) But I should be able to export decorated class where I declare it, or if Your proposition is consider to be prettier version let prettier make it for me (move export to the bottom)

**Comment by SimenB** [comment]
As an alternative to "So for now I had to choose, disable prettier or downgrade Babel"

**Comment by seantimm** [comment]
Here's the root cause (along with a way to keep the old behavior for now):
https://babeljs.io/docs/en/next/babel-plugin-proposal-decorators#decoratorsbeforeexport

**Comment by j-f1** [comment]
Based on the issue linked in @seantimm’s comment, it looks like Prettier’s behavior will be the one going in the spec.

**Comment by yoyo837** [comment]
https://github.com/babel/babel-eslint/releases/tag/v9.0.0

Babel now supports the new decorators proposal by default, so we need to switch between the new and the old proposal. This is a breaking change.
To enable the legacy decorators proposal users should add a specific parser option:

```
{
  parserOptions: {
    ecmaFeatures: {
      legacyDecorators: true
    }
  }
}
```
