### ISSUE TITLE
Prettier is changing the intent of an array of arrays instead of complaining about syntax

### ISSUE THREAD

**Issue by MarkKahn** [prettier/prettier#4800]
I realize that this is valid syntax, but it's syntax that is unlikely to (and shouldn't be) used by anything other than a minifier, so I believe prettier should either bail (or have an option to), or at the very least *not* add parens in this case since they're not needed and IMHO are more likely to break due to a typo than to clarify the valid, but poor case of using a comma op like this.

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAngQQCdCBDXTAXkwG0AdKTGgRhYBpMWAmAXVfseosAzOxYAWXv2ZMArKKYA2SQ2kB2eQA5umAPQ7MAGzgAzLBACuWEpkjZsJKYKYBOUZwAMygU05M3Pem4Abnp6SCgMHAJiMkoaRxY-Dh8vaRFkiT4VJzlkpSzvJnVkrXZGPUwoCBgASzA4ABNMGAALOBsIO2sSKCbjGoAPRswamEcAChZXDg8ASl5dfQAjS2aWmrRMDBqDA0w4AY2YNATff25AoJBWEAgAB1r0ZFASYggAdwAFV4Q0ZBASAA3CA1BrXEBLUhgADWcBgAGU7iQwDUoABzZAwQjmOA3VFoOCEGCfUho+zIYwkAwEm4AKzQAwAQlDYQiSNg4AAZVFwClUmkgJGEAmEf5LEhLXAGaDgu6EVEwADqoNayA07hucogBMVpDu-zlcBFgN5N0IcAAjuYauaSSQySQ+dTcSACdgapjsS60Ki0UYAIrmaq8pCU503GAS5UNVVITgR0g7X0AYU65JQVSgppA5gJABUJX9Q-y4ABfUtAA)
```sh
--parser babylon
```

**Input:**
```jsx
const myArray = [
  [111, 112],
  [113, 114],
  [115, 116],
  [117, 118] // left out a comma
  [119, 120],
  [121, 122]
];

const myArray = [
  [111, 112],
  [113, 114],
  [115, 116],
  [117, 118],   // noticed the comma and fixed it
  [(119, 120)], // but this still exists
  [121, 122]
];
```

**Output:**
```jsx
const myArray = [
  [111, 112],
  [113, 114],
  [115, 116],
  [117, 118][(119, 120)], // left out a comma
  [121, 122]
];

const myArray = [
  [111, 112],
  [113, 114],
  [115, 116],
  [117, 118], // noticed the comma and fixed it
  [(119, 120)], // but this still exists
  [121, 122]
];

```

**Expected behavior:**

```js
const myArray = [
  [111, 112],
  [113, 114],
  [115, 116],
  [117, 118][119, 120], // no parens -- they're not needed and they don't change the intent when a comma is re-added
  [121, 122]
];
```

This might seem easy to spot, but imagine:

```js
const myArray = [
  [() => true, 42],
];

...

const myArray = [
  [(() => true, 42)],
];
```

**Comment by lydell** [comment]
Hi, thanks for the issue!

> I believe prettier should either bail

We can't really do that: See #4749 for explanation on a similar problem.

> or at the very least not add parens in this case since they're not needed and IMHO are more likely to break due to a typo than to clarify the valid, but poor case of using a comma op like this.

I think you're looking for this ESLint rule? https://eslint.org/docs/rules/no-sequences

IMO it's a good thing that Prettier adds parens around sequence expressions, so that they stand out. They're tricky! Though I do agree that in your case where you made a mistake it's annoying:

- You have to manually remove those parens again. _But,_ if you run Prettier on save in your editor you could also hit undo. That's what I usually do in cases like this.
- You could forget/miss removing them, causing a bug. _But,_ the ESLint rule would help.

I understand the non-optimal experience, but I don't think we need to do anything on Prettier's side here. (Also, how often does this happen?)

I'm going to close this at least for now, but feel free to add more comments!

**Comment by MarkKahn** [comment]
Thanks for the explanation, that and your explanation in #4749 do make a lot of sense.

> Also, how often does this happen?

No idea, but I just spent 30 min tracking down a bug that made it through a code review :/

You say prettier can't bail -- why?  It seems to me that in "ridiculous" cases like this (and #4749, #1143, and I'm sure plenty of others) Prettier could just refuse to format at all, possibly adding a `--force` flag or similar.

**Comment by lydell** [comment]
> You say prettier can't bail -- why?

Quoting #4749:

> There has been a proposal to make Prettier accept a _superset_ of JS that would treat your example like a human would: #1143. However, that leads us down a very tricky path. We can no longer say "Prettier is 100% safe to use – it never changes the meaning of your code" (which is a reassuring thing to know for new users). Weird stuff always exist in really big code bases. And if we start with the semicolons, where do we stop? Soon we might be formatting "PrettierScript" instead of JavaScript. Also, this would require modifications to the parsers which would be tricky to maintain.

Am I misunderstanding what you mean by "bail"?

> I just spent 30 min tracking down a bug that made it through a code review :/

I know what you mean, bugs because of silly quirks like this is super annoying.

**Comment by lydell** [comment]
> Just not format at all.

Ah, I see. Yes, I guess that's something we could do. Not quite the same as #4749, then. Still, I think the ESLint rule is the best solution. Cheers!

**Comment by MarkKahn** [comment]
> I guess that's something we could do

+1000 for a blacklist!  ;)

Seriously though, a few things just never make sense, like `1[` or a sequence expression without side-effects.

**Comment by j-f1** [comment]
IMO Prettier’s job is to format whatever code it’s given, no matter how nonsensical it appears, while ESLint’s job is to report nonsensical or problematic code to the user so they can fix it.
