### ISSUE TITLE
Prettier does not recognize glob pattern on Windows

### ISSUE THREAD

**Issue by pronebird** [prettier/prettier#4804]
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: CLI
- Runtime: Node.js
- Operating System: Windows 10

**Steps to reproduce:**

Running prettier with glob pattern on Windows does not work at all. It works on macOS though, see the log:

```
yarn run format
yarn run v1.7.0
$ prettier --write 'app/**/*.js' 'test/**/*.js'
[error] No matching files. Patterns tried: 'app/**/*.js' 'test/**/*.js' !**/node_modules/** !./node_modules/**
error Command failed with exit code 2.
```

**Expected behavior:**

**Actual behavior:**

**Comment by evilebottnawi** [comment]
@pronebird what shell you use?

**Comment by pronebird** [comment]
@evilebottnawi it's Command prompt. The paths in command are escaped so I don't expect the shell to expand the paths, see the excerpt from `package.json`:

```
"format": "prettier --write 'app/**/*.js' 'test/**/*.js'",
```

Prepending the command with `cross-env` works though.

**Comment by evilebottnawi** [comment]
@pronebird maybe something in shell change basic process.cwd()?

**Comment by pronebird** [comment]
@evilebottnawi I don't think so, i.e running `yarn` with `--cwd` doesn't chanfe anything:

```
yarn --cwd 'C:\Users\pronebird\git-checkout' run format
yarn run v1.7.0
$ prettier --write 'app/**/*.js' 'test/**/*.js'
[error] No matching files. Patterns tried: 'app/**/*.js' 'test/**/*.js' !**/node_modules/** !./node_modules/**
error Command failed with exit code 2.
```

**Comment by duailibe** [comment]
You need to use double quotes on Windows. That's not related to prettier but how Windows handle quotes. 

See also #4156
