### ISSUE TITLE
Destructuring assignment to new variable names with default values and without declaration is broken in typescript.

### ISSUE THREAD

**Issue by maxlang** [prettier/prettier#4813]
In typescript, if you 
 - create a destructuring assignment 
 - that isn't a declaration
 - that is assigned to a new variable name
 - and that has a default value

prettier adds parentheses around the new variable name and the default value. However no parentheses should be added and this causes the code to break. The error I get is:

```
[ts] The left-hand side of an assignment expression must be a variable or a property access.
```

I searched around and couldn't find this bug. Hopefully I didn't miss something.

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEMIEEDO+AlgOZRKb4wBORUJA3ADpQAUwmADtRJxTgWJlMAXkxMQAEzgAzAIYBXVDAmYAvqMwduvChJ2cAbnNSq1ASgYgANCF4wi0fMlBzqPAO4AFNwmco5QwgiSRsQACNqOTAAawwAZU5ouhJkGgU4Wzp8OGoYLyiSAFs5ZHlUHNsAK3wADwAhKNiEuSK4ABk6ODKTSpAk6hzqZBAYAE9OOHwwWk4YMO46GAB1EJgAC2QADgAGWx0c5ajOEe4p3MNu22o4AEcFIhuCuWLSpHK+nKKiNOoM22I9HQAEUFBB4D0KplRnJwqtJBtkAAmWw0OREVApADCECKJRGUGgVxAChyABVYf4PnA1GogA)
```sh
--parser typescript
```

**Input:**
```tsx
let toAssign: string;
({ prop: toAssign = "default" } = { prop: "propval" });
```

**Output:**
```tsx
let toAssign: string;
({ prop: (toAssign = "default") } = { prop: "propval" });

```

**Expected behavior:**
```tsx
let toAssign: string;
({ prop: toAssign = "default" } = { prop: "propval" });

```

**Comment by ikatyang** [comment]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYACADgJwlpDGCAQQGcyBLAcygwF4MAdEAEzgDMBDAVwBsYLDAF8GGTLnyEWkrADcufIcICUAbhAAaEPhiVoZZKC448AdwAKJhIZRc5ESqy0gARji5gA1nBgBlLE9KKGpkGBweOG1gsjgcGAsPagBbLmRuPljtACsyAA8AIQ9vXz8uZLgAGWC4dMUskECcWJxkNy5XAE8+aBdcYJgAdScYAAtkAA4ABm1JWMGPLDbcOBa5Wu0cOABHHkotxK4UtKQMhtjkyjCIqJAqEL44AEUeCHg6zNuYDuHWMeQAEzacJcSh8YLUADCEGSqTaUGgGxAPFiABUOrYznBhMIgA)
```sh
--parser babylon
```

**Input:**
```jsx
({ prop: toAssign = "default" } = { prop: "propval" });
```

**Output:**
```jsx
({ prop: toAssign = "default" } = { prop: "propval" });

```

---

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYACADgJwlpDGCAQQGcyBLAcygwF4MAdEAEzgDMBDAVwBsYLDAF8GGTLnyEWkrADcufIcICUAbhAAaEPhiVoZZKC448AdwAKJhIZRc5ESqy0gARji5gA1nBgBlLE9KKGpkGBweOG1gsjgcGAsPagBbLmRuPljtACsyAA8AIQ9vXz8uZLgAGWC4dMUskECcWJxkEA4+CDMXXGCYAHUnGAALZAAOAAZtSVj+jyw23DgWuVrtHDgARx5KDcSuFLSkDIbY5MowiKiQKhC+OABFHgh4OszrmC5XQdYR5AAmbThLiUPjBagAYQgyVSbSg0DWIB4sQAKl9bCc4MJhEA)
```sh
--parser flow
```

**Input:**
```jsx
({ prop: toAssign = "default" } = { prop: "propval" });
```

**Output:**
```jsx
({ prop: toAssign = "default" } = { prop: "propval" });

```

---

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYACADgJwlpDGCAQQGcyBLAcygwF4MAdEAEzgDMBDAVwBsYLDAF8GGTLnyEWkrADcufIcICUAbhAAaEPhiVoZZKC448AdwAKJhIZRc5ESqy0gARji5gA1nBgBlLE9KKGpkGBweOG1gsjgcGAsPagBbLmRuPljtACsyAA8AIQ9vXz8uZLgAGWC4dMUskECcWJxkEBgATyw4MjAcSiwYF1xgmAB1JxgAC2QADgAGbUlYsY8sNtweuLla7Rw4AEceSn3ErhS0pAyG2OTKMIiokCoQvjgARR4IeDrMp5guK4JqxpsgAEzacJcSh8YLUADCEGSqTaUGguxAPFiABVAbZrnBhMIgA)
```sh
--parser typescript
```

**Input:**
```tsx
({ prop: toAssign = "default" } = { prop: "propval" });
```

**Output:**
```tsx
({ prop: (toAssign = "default") } = { prop: "propval" });

```
