### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#4824]
We haven’t had too many issues so far, but it would be helpful to have a set of rules everyone’s expected to follow so we can do something about trolls without them claiming they didn’t know the rules. GitHub recommends the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html), but since this is a quasi-Facebook project, we could use [Facebook’s](https://code.fb.com/codeofconduct/) instead (React has [a handy Code of Conduct that links to the Facebook one](https://github.com/facebook/react/blob/master/CODE_OF_CONDUCT.md) that we could steal).

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/5891
