### ISSUE TITLE
Mocha test cases not respecting line width.

### ISSUE THREAD

**Issue by mthorning** [prettier/prettier#4826]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLGAKA5ASQGYAEAnhAK4EDuATunAQIYFVz0A2rRBr0A5gQM4waUPqigEAFnGaUp4gCZx+YGgCMxfGFILxBWADQE8pKGBipoGedDgBKAsAA64gpCj8IrOADpuPDI4gACoSqPwCEmSs8gSqzPQA1oG2zgC+tgDcIPogEAAO5tD8yKD0VFQQFAAKZQjFKPQAbhCo8tkgcfRgCXAwAMp5XRrIQqRwOWL80jBVVPQ8ALb0yHhsUzkAVvwAHgBCc929ffQLcAAyYnAra+Mgg1RTVMgd9KpE3FDtecIwAOqtWmQAA4AAw5b4QKa-OZ5Z7fJTSRpXHLMACOpFQzFm8yW11Y6xAUwWqBGVDGOX4Gi8AEVSBB4HiCTBXv95ICkAAmHJCeioVgaADCEAWuJQUBs7VIUyCr3qq3xcFSqSAA)
```sh
--parser babylon
```

**Input:**
```jsx
it('If you write a really long string in here when describing the test', function(done) {
  console.log("This should break")
});
```

**Output:**
```jsx
it("If you write a really long string in here when describing the test", function(done) {
  console.log("This should break");
});

```

**Expected behavior:**

**Comment by ikatyang** [comment]
Hi, we special-cased those test functions to not break even if it exceeds the `printWidth`, see #842:

> This happens very frequently that naming a test makes the entire line go > 80 columns and requires to indent everything which takes a lot more space. We've had this being reported multiple times and it also affects a lot of tests inside of fb.

**Comment by mthorning** [comment]
Ok, I hadn't seen that when I had searched for the issue, many thanks for your reply.
