### ISSUE TITLE
Encoded characters get replaced with unicode

### ISSUE THREAD

**Issue by eamodio** [prettier/prettier#4831]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAyAxADwIwDEBsADAJwDcIANCBAA4wCW0AzsqAIYBOHEA7gAqcELFGwBuEegBNKIAEYc2YANZwYAZRqL6UAObIYHAK5wq2pnA4w+CnQFs2yAGZsANuaoArJpgBCC5apqbLZwADLacE6u7iCaHOYcyCD2HEqSvFAyNBzaMADqUjAAFsgAHIRU2RDmeQo0SdlwCaKRVBxwAI6G9O3WbHYOSM5uJiDmtvT6RqNM2joucACKhhDwUSNUMGyyBZLFyABMmwr0LnMAwhC29klQ0K0ghuYAKtvCw+YAvp9AA)
```sh
--parser markdown
```

**Input:**
```markdown
&#x1F609;
```

**Output:**
```markdown
😉

```

**Expected behavior:**
```markdown
&#x1F609;
```

This can cause issues with file encoding. For example, encoding detection in some editors can think the file is no longer UTF-8.

**Comment by eamodio** [comment]
FYI, this isn't specific to markdown, js/ts also has this issue

**Comment by j-f1** [comment]
@eadomio I can’t reproduce the issue in JS/TS:

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdNqCuwCMAxANgAYBOAX3QG5UoaAeAEwEsA3AAgDMIIBedAMgAe+YiWogAfEJGlKdAPTMWEkABoQEAA4wm0AM7JQAQwBOJiAHcACqYQGURlhCYM1IAEYmjYANZwYAMqa3kxQAObIMCaYcOqhenAmMFZeYQC2RsgcRgA2CeoAVnqCAEJevv4BRmlwADKhcFm5+SDBJgkmyB5G7gCeOdBumiahMADqLjAAFsgAHETqwxAJY16aXcNwHSyN6iZwAI6YTPspRumZSNl5sSAJaUyR0bd6oWE5cACKmBDwTTfqGA9CYMabIABMgK8TBybwAwhA0hkulBoLsQJgEgAVHr2a4JMhkIA) ([TS version](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdNqCuwCMAxANgAYBOAX3QG5UoaAeAEwEsA3AAgDMIIBedAMgDEAD3zES1EAD4howqUp0A9MxZSQAGhAQADjCbQAzslABDAE7mIAdwAKFhMZSmWEJg00gARudNgA1nAwAMo6fkxQAObIMOaYcFoRhnDmMLa+kQC2psgcpgA2yVoAVobCAEK+AUHBpplwADIRcLkFRSBh5snmyCAwAJ46cIZg5kx6njpjsADq7jAAFsgAHERaUxDJM746vVPDKSwtWuZwAI6YTKfpplk5SHmFCSDJmUwxcc+GEZH5cACKmAg8FaTy0MFMXjmDEWyAATODfEx8j8AMIQTLZXpQaDHECYZIAFUhTkeyTIZCAA))
```sh
--parser babylon
```

**Input:**
```jsx
"\u{1F609}";

<div foo="&x1F609;">&x1F609;</div>
```

**Output:**
```jsx
"\u{1F609}";

<div foo="&x1F609;">&x1F609;</div>;

```

**Comment by eamodio** [comment]
@j-f1 sorry, I was wrong, its `json` that doesn't work -- though from the playground, `json` works, but `json-stringify` doesn't and I guess that is what is used automatically to format a json file?

**Comment by eamodio** [comment]
Ah, that explains why I'm seeing it with my `package.json`

**Comment by eamodio** [comment]
The fix seems to only cover markdown -- should it still be open for `json-stringify` or is that expected behavior for it? Also curiously why is a different parser used for some json files vs others?

**Comment by ikatyang** [comment]
As far as I can tell, that's how npm/yarn works:

![kapture 2018-07-12 at 23 03 05](https://user-images.githubusercontent.com/8341033/42641748-d23d97d4-8627-11e8-81e5-d2fd322cac75.gif)

The `json-stringify` parser is only used for those machine-edit files such as `package.json` and `package-lock.json`, it's just a wrapper for `JSON.stringify` with cursorOffset support, see #4450 for more info.

**Comment by eamodio** [comment]
Yeah, I had opened https://github.com/npm/npm/issues/16927  against npm

**Comment by ikatyang** [comment]
Ah, didn't know we could use it this way:

> https://github.com/npm/npm/issues/16927#issuecomment-306392657
> I just edit/add packages to the package.json directly and then run npm install

Looks like a valid use case then, could you open another issue for it?
