### ISSUE TITLE
Prettier moves comments between function and `(`

### ISSUE THREAD

**Issue by yungsters** [prettier/prettier#4835]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnBATOqBqBDAGwFc4B6AKiSQAIAeAIwggLjygBpqAlVsGAOgByELAD5ypABQBLALZ4A5nE4AzQgGc4ASgDcIdiAgAHGNOjrkoPKlQQA7gAVrCCyjwA3CNIz6Q9VHhgANZwMADKRoHSUArIMKgkBtGaqDAOAQryyGoEmgYAVuoAHgBCAcGhYXiycAAy0XDZGsogkagpyH549ACeBNC+RqjRMADq3jAAFsgAHAAMBkMQmqMBRp1DcCnujQboAI5E0ujpillIOXkgmrLScQkt6tEKLACKRBDwTbktMN3jGCmyAATAZ4nhpARngBhCCyc4gKDQXYgIiaAAq3VclzgAF9cUA)
```sh
--parser babylon
```

**Input:**
```jsx
renderValue/*:: <boolean, React.Node>*/(image, false);
```

**Output:**
```jsx
renderValue(/*:: <boolean, React.Node>*/ image, false);

```

**Expected behavior:**
```jsx
renderValue/*:: <boolean, React.Node>*/(image, false);

```

**Comment by nickretallack** [comment]
It also move them into the arguments list when they were in the function body if there's no block.

Input:
```
(a, b) => // comment
  x;
```

Output:
```
(
  a,
  b, // comment
) => x;
```

**Comment by evilebottnawi** [comment]
/cc @thorn0 looks original issue was solved, maybe we need open a new issue for:
```js
(a, b) => // comment
  x;
```

**Comment by thorn0** [comment]
https://github.com/prettier/prettier/issues/8077
