### ISSUE TITLE
Support TOML for configuration files

### ISSUE THREAD

**Issue by jorgegonzalez** [prettier/prettier#4845]
It would be fairly easy for Prettier to support `.prettierrc.toml` files as `cosmiconfig` supports [loaders](https://github.com/davidtheclark/cosmiconfig#loaders).

```ts
// Example loader using toml from npm (https://github.com/BinaryMuse/toml-node)
import toml from 'toml';

function loadToml(filePath: string, content: string): Object | null {
  try {
    return toml.parse(content);
  } catch (error) {
    error.message = `TOML Error in ${filePath}:\n${error.message}`;
    throw error;
  }
}
```

This [issue](https://github.com/davidtheclark/cosmiconfig/issues/150) discusses adding TOML to `cosmiconfig`'s defaults. If they do implement this, Prettier would get this feature for free.

Some reasons why TOML is better than YAML for configuration files: https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html

Some arguments against JSON as a configuration language: https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/

**Comment by jorgegonzalez** [comment]
More arguments in favor of TOML: https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/

**Comment by j-f1** [comment]
Can you open a PR with just the upgrade so we can figure out what’s going wrong and fix it?
