### ISSUE TITLE
Ignore tag doesn't ignore Liquid in .scss.liquid files

### ISSUE THREAD

**Issue by ConduciveMammal** [prettier/prettier#4860]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgA4Cc4wwCWcuAtEQOZQT6bqoA6UAJGABZxgDWFkUSTMGCYA5By7cAtgENc3AHQBnAG6VRmAD6YZSpQQD6AV1wAbTAF8LAbhAAaEBGzFoS5KDm4IAdwAKchDcUGRUIIgATexAAI1wZHgIAZWx4oihKZBhcIzgHNP1cGF84yllkADMZU30HACslAA8AITiEmESZKTgAGTS4CqqakBTcAuQYmWiAT1NoKLw0mAB1CJh2ZAAOAAYHPAh9Jbjscbw4ApV+h3wARyMifGKZUpkB6tyQfSkiTOz3pTTKKY4ABFIwQeCvIYwSYrcJrZAAJgcWRkRFMAIAwhApGUUDQoJcQEZ9AAVSZBSpvKxAA)
I'm working with Shopify liquid within a .scss.liquid file. I'm trying to have Prettier ignore a single Liquid line using the ignore tag but it doesn't seem to be working.

**Input:**
```scss
/* prettier-ignore */
$check-icon: {{ 'checkmark.svg' | asset_url }};
```

**Output:**
```scss
/* prettier-ignore */

$check-icon: {
    {
    'checkmark.svg' | asset_url
  }
}

;
```

Also, I'm running Prettier within VSCode and have added these options in user settings.
```json
    "editor.formatOnSave": false,
    // Enable per-language
    "[scss]": {
        "editor.formatOnSave": true
    },
    "[javascript]": {
        "editor.formatOnSave": true
    }
```

**Comment by suchipi** [comment]
I don't see the same output in the playground:

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgA4Cc4wwCWcuAtEQOZQT6bqoA6UAJGABZxgDWFkUSTMGCYA5By7cAtgENc3AHQBnAG6VRmAD6YZSpQQD6AV1wAbTAF8LAbhAAaEBGzFoS5KDm4IAdwAKchDcUGRUIIgATexAAI1wZHgIAZWx4oihKZBhcIzgHNP1cGF84yllkADMZU30HACslAA8AITiEmESZKTgAGTS4CqqakBTcAuQQJTA9KLw0mAB1CJh2ZAAOAAYHPAh9ebjscbw4ApV+h3wARyMifGKZUpkB6tyJuCkiTOyXpTTKUzgAIpGCDwJ5DGAyaKLcLLZAAJgcWRkRFMvwAwhApGUUDQoGcQEZ9AAVSFBSrPKxAA)
```sh
--parser scss
```

**Input:**
```scss
/* prettier-ignore */
$check-icon: {{ 'checkmark.svg' | asset_url }};
```

**Output:**
```scss
SyntaxError: (postcss) CssSyntaxError Unknown word (2:17)
  1 | /* prettier-ignore */
> 2 | $check-icon: {{ 'checkmark.svg' | asset_url }};
    |                 ^
```

**Comment by ConduciveMammal** [comment]
Ahh yeah, in the Playground, it just returns a syntax error.
But in VSCode it still formats it but doesn't ignore the Liquid syntax

**Comment by suchipi** [comment]
@ConduciveMammal Are you sure that prettier is the plugin that is formatting it, not something else in vscode?

**Comment by ConduciveMammal** [comment]
@suchipi yeah it's definitely Prettier, when I entered:
```json
    "[scss]": {
        "editor.formatOnSave": false
    },
```

It straight away stopped happening (As well all formatting).
