### ISSUE TITLE
Error on Playground

### ISSUE THREAD

**Issue by meddlesome** [prettier/prettier#4864]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbm9fPz8Aeiz8ABVbABFbJHxC6AV9Gzh8akMoOggAW394tganDN19RJa+C0MYIQA6VHIafAYBoeG6huaGDwAqfABGAFEAagB2N2GYCABlGGpw5kXZuAAHEkMwOAYs-n5h57pNrJxmSUFBN3T4rUOLF4gAeOg4ez4MC3TSaAByhiacB4CmIZEoNHoCnwuBguh4wAABgBNaz4QxsfD2HDaA7UBLoJoAIyc+AAJMBGS0XESXPhLNY7I5qITBdUHE4XAA+AGZfCgzQnaDMaVc0KcZjDTQkHD3Bj4AAMklW+D2BwAqlcrk4AMKGUyLfCbKRsMJcbW6-Wrc0QAAyEAA7naHQ8PC5QVkldQVbLAX4WG7NcMEHRNBQcEMGBI-vgAPwCECF-ClRVXer4JUATwJwGAkHI1FKSn40irChcMokhcjmnLUGl+BcGT8oLgTTj-Bg6qTcDkw58MEj47j8q5DG0ulg-3jmQLgleIBHmVKgiCggXx8jEPs0rSPigLhA4hAECuuGgmmQoEpMcDAAVKQQL8UEMewIBwOhnxAZk6jAABrDhDnLMAzmQE50DMEBwlMagYH-OpmCaQxkCMEwsIAK00AAPAAhODEJgQ4kTgP1wjgUjjFMF9y2oXDkBgwxmRraBoKuU5YAzOghmQAAOY0QHEiBTAoOorgE8S4FwxxoLYABHdAcDYAjDCIkikDI7iQFMJocHQ6hMJfbQuF0ABFdAIHgTjyJfGAhKkmSkAAJl8uodDOW1mmIgSoGgDiX2qPIhJAyy4E7IA)
```sh
--parser babylon
```

**Input:**
```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>;

}
```

**Output:**
```jsx
ReferenceError: prettierPlugins is not defined
    at Object.get babylon [as babylon] (https://prettier.io/worker.js:18:5)
    at resolveParser$1 (https://prettier.io/lib/standalone.js:7272:21)
    at normalize (https://prettier.io/lib/standalone.js:7381:19)
    at formatWithCursor (https://prettier.io/lib/standalone.js:10701:12)
    at https://prettier.io/lib/standalone.js:19333:15
    at Object.format (https://prettier.io/lib/standalone.js:19341:12)
    at formatCode (https://prettier.io/worker.js:162:21)
    at handleMessage (https://prettier.io/worker.js:113:18)
    at self.onmessage (https://prettier.io/worker.js:89:14)
```

**Expected behavior:**

**Comment by j-f1** [comment]
I’m unable to reproduce this issue. Perhaps try hard-refreshing (Cmd/Ctrl+Shift+R)?

**Comment by meddlesome** [comment]
@j-f1 Thanks, seems random. It works now.

**Comment by duailibe** [comment]
Looks like a race condition when loading the plugins? A refresh makes it work

Either way we should fix this..

**Comment by gilbert** [comment]
I just got this error too. A hard refresh did the trick.
