### ISSUE TITLE
What are the formatting rules?

### ISSUE THREAD

**Issue by gandalfsaxe** [prettier/prettier#4871]
Apologies if I overlooked the answer the this quite obviously question. I've looked everywhere, but I can't find the actual formatting rules. Are these anywhere are is the user just expected to pick up in the style along the way as prettier reformats your files?

I recently started using [Black](https://github.com/ambv/black) for Python and they have very [clearly stated](https://black.readthedocs.io/en/stable/the_black_code_style.html) what the black formatting rules are. I'm really missing the same for prettier.

In particular, I'm mostly interested in how it reformats markdown (and trying to troubleshoot why I can't get vscode-prettier to work on markdown files, prettier/prettier-vscode#521).

**Comment by suchipi** [comment]
I don't think we have all of the rules written up anywhere. Some of the logic is *very* complicated and nuanced, so it would be difficult to write such documentation, and even harder to keep it in sync.

Your best bet would probably be to find a repo with a large amount of markdown and run prettier on it, then check the results. You can also use https://prettier.io/playground/ to test individual code snippets.

**Comment by GandalfSaxe** [comment]
Fair enough. But do you have *some* of the rules written down anywhere? Because I could find none 🤔 

Also, for markdown in particular, the rules shouldn't be _too_ complicated right?

Anyway I think it's a worthwhile venture to write down the most important formatting rules. It wouldn't have to be exhaustive and go through all edge cases, it's just useful to have the broad lines outlined IMO 🙂

**Comment by j-f1** [comment]
Prettier’s two main formatting rules are:

1. Always write valid JavaScript.
2. Hit save.

Your editor will provide the formatting.

Prettier’s exact rules shouldn’t matter since anything that is different from them will be automatically fixed.

**Comment by bardware** [comment]
> automatically fixed

Sometimes it's impossible to say if a change prettier introduces in my code is intended or why this rule is enforced.

**Comment by thorn0** [comment]
> I recently started using Black for Python and they have very clearly stated what the black formatting rules are. I'm really missing the same for prettier.

Prettier actually have had a similar page all this time: https://prettier.io/docs/en/rationale.html
It's not an exhaustive description of all the heuristics, but neither is Black's page.

I'm closing this issue as the question has been answered.
