### ISSUE TITLE
TSX spread bug still persists.

### ISSUE THREAD

**Issue by Ebuall** [prettier/prettier#4872]
Previous issue is locked https://github.com/prettier/prettier/issues/3158

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTAHgBMBLANwD5gA6OgbQAYBdAX0IHoyqQAaECAAcYpdMlABDAE5SIAdwAK0hGmQgJ5CKWJ8QAIykSwAazgwAyoKOkoAc2QwpAVzj8baOFJgLDtgLYSyABmEgA2HvwAVmjYAEKGJmbmEn5wADI2cMFhESBWUh5SajAAnoJwaGBSpMK6gtWwAOraMAAWyAAcjPz1EB6NhoJq9RWe5Fn8UnAAjk6kUz4S-oFIIeGuIB5+pA7OG2g2tqFwAIpOEPDZ6-wwEnrNxG3IAEw3hqShhwDCEH4BalBoBMQE4PAAVO6qVY5OCsVhAA)
```sh
--parser typescript
```

**Input:**
```tsx
const x = <div>{...[0]}</div>
```

**Output:**
```tsx
const x = <div>{[0]}</div>;

```

**Expected behavior:**
```tsx
const x = <div>{...[0]}</div>;
```

VSCode-prettier and `npx prettier Untitled1.tsx` both without any configuration give the same result.

**Comment by ikatyang** [comment]
Sorry, it seems it's only fixed in `babylon`, tracked in eslint/typescript-eslint-parser#500.

**Comment by ikatyang** [comment]
@j-f1 This item seems not able to be in 1.14 due to no merging for eslint/typescript-eslint-parser#501.

**Comment by JamesHenry** [comment]
@ikatyang Sorry for the delay, but it has been merged and released
