### ISSUE TITLE
Extra indentation of lines following comments within SCSS maps

### ISSUE THREAD

**Issue by morewry** [prettier/prettier#4878]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAZgQwDaQE4C0k2EeAzkgAQAUAOlJZQPROV5xkCu2MlE6lACaY8AawTUAxAGY40gJzSAHABpKAJgAMASnqMARtkxhRWzVUmb5mpTZV7mrALacyMEYMqu4n9KUrwAB4wDi5uHmYWYOhKACwAjJr2DJRh7niCWhZwOer60smM7IKJ5pSS6JXS6OqFlGRwmH6YTlnlggCsNXAAbHUsbBzcvPyU2ACWAOYAFvBQUtIKmJjxah06DvA4bZKCcOjVHf2s7Fw8fAITM3MLSytqsRspW9iPFvpKcB1wSvTaANwgFQgCAABxg42gZGQoBEeAgAHcAAoiBDQlCYABuEHGgiBIH0eGM4hgAGVQcZxlBJsgYHhOHBgVSGngYEiiZMnJhkFhsA1gQArMiBABCRJMcDJLTgABkqXAeTh+SAKeQ4HhkCAyGAyNDgaC8FSYAB1XEwabIWz6+ENY1E0Gag0cdWYhXA9gAR0443Y7MwnO5SF5yoaTnGtPpjK1VMm2DgAEVOBB4Iq+VH3PpTYJzchaiA6ZhxhNqQBhCBOLmaqDQN0gbwAFUw+nRwbgAF820A)
```sh
--parser scss
```

**Input:**
```scss
$falcor-colors: (
  // result of darken(#3e3938, 20)
  black200: #090808,
  // mustard used for text
  mustard200: #cf8410,
  mustard20: #eee2b3,
  red100: #fff3f2,
  seafoam20: #d5f2e6,
  // result of lighten(#339aa1, 50)
  teal20: #def3f5,
  // result of lighten(#339aa1, 40)
  teal40: #b8e5e8
);
```

**Output:**
```scss
$falcor-colors: (
  // result of darken(#3e3938, 20)
    black200: #090808,
  // mustard used for text
    mustard200: #cf8410,
  mustard20: #eee2b3,
  red100: #fff3f2,
  seafoam20: #d5f2e6,
  // result of lighten(#339aa1, 50)
    teal20: #def3f5,
  // result of lighten(#339aa1, 40)
    teal40: #b8e5e8
);

```

**Expected behavior:**

I would expect the output here to match the input. Instead, the lines following the comments are indented an extra level.

**Comment by rowild** [comment]
I can confirm this issue. Any progress on that?

**Comment by evilebottnawi** [comment]
@rowild feel free to send a PR with fix

**Comment by rowild** [comment]
@evilebottnawi Do you also have any more meaningful comment that addresses the question in petto?

**Comment by evilebottnawi** [comment]
@rowild no, printing comments in `css` is very hard so feel free to experiment and try to do it better

**Comment by rowild** [comment]
@evilebottnawi Are you core member?

**Comment by evilebottnawi** [comment]
@rowild yep

**Comment by rowild** [comment]
Well, in that case please accept that I only report, which is at least one thing that most open source project and their creators want. But I will not contribute. I have to use prettier, but don't like it. However, when I find things that need improvement, I at least report. Which should be something.
If you like your own project and want to improve it, I am sure you will evaluate my input to your likings.
However - fact remains: this is an annoying issue that needs to be fixed.

**Comment by morewry** [comment]
I'm curious how CSS comments are different from JS comments in a case like this? If this were a JS object or array with single-line comments between items, it wouldn't do this?

**Comment by CH-RhyMoore** [comment]
Related, but not _entirely_ identical to https://github.com/prettier/prettier/issues/4659

**Comment by elhorowitz** [comment]
@CH-RhyMoore Semi-related, if you add a comma at the end of the comment, the parser treats it as a list item and prevents it from collapsing into the comment (it also fixes some of the indent issues:

```
$dls-color-function-map: (
  // secondary,
    teal-100: (rgb(51, 154, 161)),
  teal100: (rgb(51, 154, 161)),
  // grayscale, 
  gray-80: (rgb(87, 83, 82)),
  gray80: (rgb(87, 83, 82)),
  // grayscale,
  gray-70: (rgb(112, 111, 110)),
  gray70: (rgb(112, 111, 110)),
  // primary,
  black-100: (rgb(62, 57, 57)),
  black100: (rgb(62, 57, 57))
);
```
