### ISSUE TITLE
Can't resolve 'module'  in '...../node_modules/prettier'

### ISSUE THREAD

**Issue by swufexlm** [prettier/prettier#4879]
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: Node.js API
- Runtime: Node.js v8.11.2
- Operating System: macOS,

**Steps to reproduce:**

I have a project base on create-react-app, typescript@2.9.2 and wepack@3.8.1.  When I try to add prettier to my project, the  webpack has a compile error: 
```
./node_modules/prettier/third-party.js
Module not found: Can't resolve 'module' in '../node_modules/prettier'
```
But I can find the 'module' declare in @types/node/index.d.ts:
```
declare module "module" {
    export = NodeJS.Module;
}
```

What can I do to solve this problem?

**Comment by j-f1** [comment]
Hello @swufexim!

Would it be possible for you to provide a small example that reproduces the problem?

**Comment by ikatyang** [comment]
This looks like a `webpack` issue caused by `require-from-string` (which is one of our sub-dependencies):

- https://github.com/floatdrop/require-from-string/pull/6#issuecomment-369216332
- webpack/webpack#5423

I guess this issue should probably be fixed either in `require-from-string` or `webpack`.

**Comment by swufexlm** [comment]
Thanks for your reply.

Hello @j-f1  
I commit an example to [https://github.com/swufexlm/prettier_issue4879](https://github.com/swufexlm/prettier_issue4879), which can reproduce this problem.

Hello @ikatyang 
According to [webpack#5423](https://github.com/webpack/webpack/issues/5423), I try to use `var module$1 = module.constructor;
` instead of `var module$1 = _interopDefault(require('module'));` in `third-party.js`. Webpack compiles  successful but I get another error: 
```
TypeError: existsSync is not a function
at node_modules/prettier/third-party.js:5400
```
I think this may be caused by the setting of webpack config:
```
node: {
    fs: 'empty'
}
```
because I will run my project in the browser.

Now, I use prettier with `<script src="https://unpkg.com/prettier@1.13.0/standalone.js"></script>` in the browser directly and it work well.

**Comment by grofit** [comment]
Has this been fixed? or is there some recommended work around? I am trying to use it in electron with webpack and it keeps blowing up with same error :(

**Comment by ikatyang** [comment]
FYI, we updated `cosmiconfig` to v5 in #4899, which dropped the `require-from-string` dependency, and it'll be in 1.14.1 in few days.

**Comment by suchipi** [comment]
@grofit you can either do this, to force using electron's `require` function to load it:
```
eval("require")("prettier")
```
Or you can require "prettier/standalone" instead of "prettier".

**Comment by swufexlm** [comment]
@grofit Now in my project,  I use `prettier` in this way:
```ts
const prettier = require("prettier/standalone");
const prettierBabylon = require("prettier/parser-babylon");
const prettierTS = require("prettier/parser-typescript");

const content1 = prettier.format("some typescript codes", {
  parser: "typescript",
  plugins: [prettierTS]
});

const content2 = prettier.format("some json texts", {
  parser: "json",
  plugins: [prettierBabylon]
});
```

**Comment by grofit** [comment]
ok thanks guys will give them a try

**Comment by grofit** [comment]
Any news on this one? I am trying to use the [csharp plugin](https://github.com/warrenseine/prettier-csharp) and trying @swufexlm approach looks sensible but just blows up for me, and the plugin docs imply you should provide a path (ideally want to bundle it in with the electron stuff so it doesnt need to lookup at runtime, so the passing of the plugin object seems a nicer approach).

Any info would be great!
