### ISSUE TITLE
Ternary alignment with components

### ISSUE THREAD

**Issue by leobrdar** [prettier/prettier#4880]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAzgFQE4Fc4AEA-AQQDwDCEAtgA7QIwHpxgyrQC8wLbHUAXwIB6AHwEkpcgGUacAPIwAFnGxU6DWM1bsuPHfyFiAOlFMYc+YqWMhKNelEba+e3rsEjRtiVNtlZagVlVXVHZ3d+bkjoI28QEAAaEAhaD3RkUABDbGwIAHcABRyEDJQsgDcIVAATJJAAI2wssABrOBhpWhbUKABzZBg8OGTelmwYQua+6izkADMsgBsWZIArdAAPACFmto7pLKCAGV64BeXVkG7sceRGrIaATyXoetpsXpgAdVrlZAAHAAGZIfCAsb7NWj3D5wcYVc7JbBwACOuFQyKmWRmcyQixWIxALGoqEGw2S6F6fSWcAAirgIPALgTkjBHr8av8kAAmVnNVBLKnqWb3KAMeq4FiYR5lfEsAQCIA)
```sh
--parser babylon
```

**Input:**
```jsx
isTrue ?  <Component section={section} /> :   <SomeOtherComponent section={section} />

isTrue ?  "<Component section={section} />" :   "<SomeOtherComponent section={section} />"
```

**Output:**
```jsx
isTrue ? (
  <Component section={section} />
) : (
  <SomeOtherComponent section={section} />
);

isTrue
  ? "<Component section={section} />"
  : "<SomeOtherComponent section={section} />";

```

**Expected behavior:**

```jsx
isTrue
  ? <Component section={section} />
  : <SomeOtherComponent section={section} />;

isTrue
  ? "<Component section={section} />"
  : "<SomeOtherComponent section={section} />";

```

Why use different alignment/formatting for components? I'd expect `?` and `:` to be at the beginning of the new line in both cases.

**Comment by j-f1** [comment]
This is an intentional behavior to make it easier to move JSX into and out of ternaries, since people might be less likely to notice extraneous punctuation when it’s rendered as text.

**Comment by ikatyang** [comment]
FYI, #2208.
