### ISSUE TITLE
Several CLI options generate Ignored unknown option warning 

### ISSUE THREAD

**Issue by barlowm** [prettier/prettier#4882]
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: NPM script
- Runtime: npm version - 6.2.0, node version: v8.11.3
- Operating System: Windows 7

**Steps to reproduce:**
I have created a simple [test repo](https://github.com/barlowm/prettier_test) with readme in github

**Expected behavior:**
No warnings generated

**Actual behavior:**
[warn] Ignored unknown option `{ "listDifferent": true }`
[warn] Ignored unknown option `{ "write": true }`
[warn] Ignored unknown option `{ "loglevel": "debug" }`

**Comment by ikatyang** [comment]
They're indeed unknown options from API perspective, only [options](https://prettier.io/docs/en/options.html) are allowed in config files. The options you mentioned above are CLI-only options.

**Comment by barlowm** [comment]
Thanks
