### ISSUE TITLE
strict mode for single empty line

### ISSUE THREAD

**Issue by a7madgamal** [prettier/prettier#4884]
prettier is taking the world by storm because it's less opinionated. we all love this.
However, it's 'relaxed' with single empty line which leaves room for opinions and YES they can get annoying and time consuming as well!

I would love if prettier becomes `the prettiest` and take a decision for those single lines. this way adding or removing a single empty line becomes something from the past.

I know (and love) the idea of less options so its up to the maintainers to
- make this the default behaviour in prettier 2 for example
OR
- add a `strict` or `prettiest` option to enable this mode

The logic for adding those lines is another story, but we can use recommended rules from linters to promote better readability

**Comment by duailibe** [comment]
Yeah this has been suggested before, we've discussed a bit about it: #2068.

Let's keep the discussion in one place. Thanks!
