### ISSUE TITLE
prettier traverses .git files and tries to format them

### ISSUE THREAD

**Issue by gillchristian** [prettier/prettier#4895]
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: CLI
- Runtime: node v8.9.4, npm v5.6.0, yarn v1.5.1
- Operating System: Linux

**Steps to reproduce:**
- In a git repository with `prettier` installed
- Create a git branch that ends in `.js`
- Run `prettier --write '**/*.js'`

I created a repository with everything ready to reproduce ([link](https://github.com/gillchristian/prettier-report)).

**Expected behavior:**
`.git/` directory should be ignored, `prettier` should run without errors.

**Actual behavior:**
`.git/` directory is traversed in files and `prettier` throws syntax error (obviously because `.git/` files aren't JS files).

---

I'm aware of #2882 but `.git/*` files are still parsed.

Also, I'm up to work on opening a PR solving this issue. But I believe it's better to ask first.

**Comment by azz** [comment]
Maybe we should add `.git`, `.hg`, `.svn` to `exclude` when expanding globs?
