### ISSUE TITLE
Release script improvements

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#4905]
Something I noticed during this release:

- `publish-to-npm.js` will throw error if 2FA enabled.
- Version-related steps need to be updated since we are now using prereleased version on master. (e.g. 435e8532cb969d9c0f89ec86f4352c78edfcb191)
- We can remove the `Updating integration snapshots` step. (Ref: #4821)
- `publish-to-npm.js`:

  > - Go to `https://github.com/prettier/prettier/releases/new?tag=${version}`
  > - Copy release notes from `CHANGELOG.md`
  > - **Attach all files in `dist/` folder.**
  > - Press `Publish release`

  I'm not sure which file should be attached (at least `README.md` should be excluded), so [I attached only ~~parsers, standalone~~, and the tarball](https://github.com/prettier/prettier/releases/tag/1.14.0). cc @duailibe 

- It takes 8 min running on my machine 😂, `--runInBand` should only be used on CI.

**Comment by azz** [comment]
For the GitHub attachment, should we only attach the npm packed `.tgz` file? What's the benefit of adding individual files?

**Comment by j-f1** [comment]
It looks like historically we haven’t attached anything to the releases (except @duailibe attached the npm bundle in 1.13.5), so perhaps we should leave those assets out and let people use [unpkg](https://unpkg.com/#/) instead.

**Comment by lydell** [comment]
> publish-to-npm.js will throw error if 2FA enabled.

It would be cool if it was the other way around – it would throw an error if 2FA is disabled. https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes

**Comment by j-f1** [comment]
It looks like that’s possible — [packages have a setting](https://docs.npmjs.com/getting-started/requiring-2fa-for-package-publishing-and-modification) that makes npm require 2FA when publishing.

**Comment by ikatyang** [comment]
- [x] Require Two Factor Authentication to publish or modify settings
