### ISSUE TITLE
Different config used when running Prettier from npm script

### ISSUE THREAD

**Issue by charlestati** [prettier/prettier#4909]
**Environments:**
- Prettier Versions: 1.14.0 (local) and 1.10.2 (global)
- Running Prettier via: CLI
- Runtime: Node.js v8.9.3
- Operating System: macOS

**Steps to reproduce:**
```
├── test/
│   ├── .prettierrc
│   ├── package.json
```

`.prettierrc`:
```
{
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false
}
```

`package.json`:
```
{
  "scripts": {
    "fix": "prettier --write package.json"
  },
  "devDependencies": {
    "prettier": "^1.14.0"
  },
  "lint-staged": {
    "*.js": [
      "eslint --fix",
      "git add"
    ],
    "*.{json,md}": [
      "prettier --write",
      "git add"
    ],
    "*.scss": [
      "prettier --write",
      "stylelint --fix",
      "git add"
    ]
  }
}
```

**Expected behavior:**

Both `prettier --write package.json` and `npm run fix` should format `package.json` using the `.prettierrc` config file since Prettier's config file is searched from the formatted file. Am I doing something wrong?

**Actual behavior:**

```diff
9,11c9,21
<     "*.js": ["eslint --fix", "git add"],
<     "*.{json,md}": ["prettier --write", "git add"],
<     "*.scss": ["prettier --write", "stylelint --fix", "git add"]
---
>     "*.js": [
>       "eslint --fix",
>       "git add"
>     ],
>     "*.{json,md}": [
>       "prettier --write",
>       "git add"
>     ],
>     "*.scss": [
>       "prettier --write",
>       "stylelint --fix",
>       "git add"
>     ]
```

**Comment by j-f1** [comment]
> Prettier Versions: 1.14.0 (local) and 1.10.2 (global)

We changed how we format `package.json` files at some point between those releases. Updating your global installation should fix the problem.
