### ISSUE TITLE
prettier --check

### ISSUE THREAD

**Issue by jessevdp** [prettier/prettier#4911]
Please forgive me if this issue turns out to be a duplicate. I did a couple of searches through other issues (both closed and opened) with some keywords that came to mind and found nothing relevant.

---

#### Question

**Is there a way to run prettier in a "diagnostic" sort of way where it outputs the issues it finds with your code?** The desired result would be something along the lines of what ESLint does. Consider the following screenshot.

![image](https://user-images.githubusercontent.com/15139826/43400574-5768b0f8-940e-11e8-9847-30c24f535470.png)

#### Background Info

The reason I'm asking this? I want to make sure all code in my repository is run through a linter and/or style checks pre-commit. However simply running prettier with the `--write` flag comes with one big issue: https://github.com/okonet/lint-staged/issues/62. In short: Running `prettier --write` changes the code if it finds an error, this fixed code should be added to the same commit. Simply running `git add` on the changed file adds all of the contents of that file to the commit, even if you only wanted to commit a part of that file. (Read https://github.com/okonet/lint-staged/issues/62 for details...)

As a workaround I decided that just running all the linters and style-checks would be good enough. If a linter or style check fails the commit won't be made and the developer can then manually deal with the problems.

I got this part working. Turns out running prettier with the `--list-different` flag will exit with a non-zero exit code if it finds any problems. On top of that the command will (as the flag suggests) list all of the files that have style problems in them.

**But this doesn't make for the best developer experience.** Telling the developer "prettier found some problems" and then just listing a some file(s) seems a bit confusing. Consider the following screenshot.

<img width="547" alt="screenshot" src="https://user-images.githubusercontent.com/15139826/43402137-4c776e88-9412-11e8-9cc0-376f88fe16c6.png">

#### Hopes and Dreams

In a perfect world I would want prettier to have the option to provide a detailed report of the issues it has found and the rules that are broken.

```
prettier --check
```

#### Alternative

Alternatively I think you could improve the developer experience by adding some format & extra information to what `--list-different` already does and call that `--check`. The following code snippet would be an example printout.

```
prettier --check

Prettier found some issues in the following files:
  - somefile.js
  - css/styles.css
  - README.md

Run 'prettier --fix' to automatically fix these issues.
```

---

I know it is possible to add prettier as a plugin for ESLint—but that doesn't work for all cases, since ESLint only works for JavaScript files (as far as I know) and prettier does more than that.

**Comment by jessevdp** [comment]
`precise-commits` doesn't solve all my problems—it does solve the problems related to prettier, but not the other linters (that too have `--fix` like options). And since I want a unified approach...

**Anyway, `prettylint` seems to do the trick indeed! Thanks!** I did a quick search both through the README and the [related projects page](https://prettier.io/docs/en/related-projects.html). Neither of them seems to mention `prettylint`. Perhaps it should be added somewhere?

**Comment by ikatyang** [comment]
Added in #4914. I guess this issue can be closed then?

**Comment by j-f1** [comment]
Closing for now, but if we missed something, feel free to comment and we’ll reopen.

**Comment by kachkaev** [comment]
I’m using [`prettier-check`](https://github.com/hexacta/prettier-check/blob/master/readme.md) inside my `lint` script and it reports the list of non-formatted files in a human-readable form.

However, I’d love to see the same functionality done by prettier itself, eg via `prettier --check`. This command could just be a linting-friendly variation of `prettier --list-different`, which requires quite few new lines of code. The main advantage that I see in this is the shape of the `node_modules` directory. Prettier alone does not have any npm dependencies, so `yarn install` is quick and the result is lite. Extra dependencies such as `prettier-check` or `prettylint` bring in quite a lot of extra sub-dependencies and bloat `node_modules`.
