### ISSUE TITLE
.prettierignore doesn't support negations in glob pattern

### ISSUE THREAD

**Issue by TheHolyWaffle** [prettier/prettier#4912]
**Environments:**
- Prettier Version: 1.14.0
- Running Prettier via: CLI
- Runtime: Node 8
- Operating System: Windows

**Steps to reproduce:**
I have 2 files sitting at:
```
- weblibs/mycompany/mymodule/1.0.0/index.js
- weblibs/mycompany/mymodule/snapshot/index.js
```
I would like to ignore the index.js in folder '1.0.0' so I have the following .prettierignore sitting at my project root
```
weblibs/mycompany/mymodule/!(snapshot)/**/*.js
```

After that I run prettier on my folder with: `yarn run prettier "**/*.js" --write`

**Expected behavior:**

Only index.js in folder 'snapshot' is prettified, while the '1.0.0' folder is ignored.

**Actual behavior:**
No files are ignored, and both files are 'prettified'. It looks like prettier doesn't understand the negation pattern of the glob.

**Comment by ikatyang** [comment]
Per [.gitignore spec](https://git-scm.com/docs/gitignore), negate pattern should start with `!`:

```
weblibs/mycompany/mymodule/**/*.js
!weblibs/mycompany/mymodule/snapshot/**/*.js
```
