### ISSUE TITLE
Too much indentation in method body selected by range if first line is comment or incompletely selected

### ISSUE THREAD

**Issue by cmcaine** [prettier/prettier#4926]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOFOA9AFQ04AiEcuMAFgJa4DWcAnjgC26GGDY50OAOYcAbghwBZDlA7DUAaX444AD3hQAJiqk4IAIwBWcMDAD8OGlTKUhIsQApefOPNgBKYhdXSioqHAByFQicQ2ZMKAiYHBUwVABXQzgcAAcAJwgYQr4clgAaHEwiDhgI3Ex0ADNsxog8nHYuMysbGAA6YJCcVvaPVDhkkRh2lQ7OTEDSciGQjkacD07MAG0pvIBdHABCAF4TnG9fBBhdmGn9wLyJ9LzyRvRUTDhBkIBfH9cTxgL3I03S32WFH+UF+IDKIAgORgHGgmGQoHQeQKAHcAAqYhBolDoWQQDiGOEgcx5dBgXgwADKOVpJmQYLg8JUXzyMFxNKkwmQ70+HJAlkwugAQjS6RMGehBHAADIqOBCj5feHMvLc5BU9DmPioaCU-IqGAAdXJ7GQAA4AAxagpfC00nJ6-IsOB5eSUp4AR3SHCefPQAvQ6pF8K+gg4bLy4OjJnGAEV0oU1UhhZqQDADVbDDakAAmeHTdAcVAmADCEEEgpQUGgavh6S+ABUDUTs6KaVApHAGXmecgAIz20fwvsDgCiRmQAGZ7QAWX6-IA)
```sh
--parser babylon
--range-end 304
--range-start 101
```

Can reproduce with just range 100 - 101 (the newline character after the brace on line 4), so that seems to be the culprit.

If I replace line 4 with an expression (e.g. let x) then the method is formatted correctly more often so long as my selection covers the second character of the expression, but you can break it again by moving the start of the selection over the brace on line 3.

**Input:**
```jsx
class Foo {
    /** Does this key match a given MinimalKey extending object? */
    match(keyevent) {
        // 'in' doesn't include prototypes, so it's safe for this object.
        for (let attr in this) {
            if (this[attr] !== keyevent[attr]) return false
        }
        return true
    }
}
```

**Output:**
```jsx
class Foo {
    /** Does this key match a given MinimalKey extending object? */
    match(keyevent) {
                      // 'in' doesn't include prototypes, so it's safe for this object.
                      for (let attr in this) {
                        if (this[attr] !== keyevent[attr]) return false;
                      }
                      return true;
                    }
}
```

**Expected behavior:**

Don't indent so much. Don't be so sensitive to range choice.

Ref: https://github.com/nrwl/precise-commits/issues/15

**Comment by j-f1** [comment]
I’m starting to wonder if we should change range formatting to format the whole file, but with two “cursors,” then replace what’s in the range with the text between the cursors.

**Comment by cmcaine** [comment]
Sounds sensible to me. In my project we just ended up running prettier on everything so that we could use whole file prettier.

**Comment by sheerun** [comment]
This makes range formatting unusable. Prettier randomly indents half of codebase

**Comment by sheerun** [comment]
btw. to make it worse range formatting is very slow because of API prettier is exposing (you can provide just one range, so if you need to format n ranges you need to call format n times)

**Comment by lydell** [comment]
@sheerun Kind of related: https://github.com/prettier/prettier/issues/5807

**Comment by sheerun** [comment]
Here's another even simpler example:

test.js 

```
function test() {
  'foo';
  'bar';
}
```

command:

```
cat test.js | prettier --parser babel --range-start 25 --range-end 25
function test() {
                  ("foo");
                  ("bar");
                }
```

**Comment by thorn0** [comment]
See one more manifestation of this bug in #7082.
