### ISSUE TITLE
Jest functions formatted differently than non-Jest funcs with same-length name

### ISSUE THREAD

**Issue by eldarshamukhamedov** [prettier/prettier#4929]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHxgENN8BffAMxwnXwHIcAPAKwGdGBuAHSgzY8+DqTwBlODgBuqMHBp0GjAHQqA9Bymz5PfvwAmcDmByoARnAAUjeKMYAafFYCU+ALwA+Qv3z4ANnAEqFCiJFDyfFC++Orq+ABSxgTUAK4RTv4koviYJDgI+Kgc+NDEABYKHCToCv4hCtn4AAYG0NYuzTGW1LhwAKIkYOVWbVAKXjF+YRLach1TfvgqmKiY1qSYVloy8x7eViFhERMic-Iul4t+Khyp5iZmllau+-hjHS4OMS5RMXH4ABy0AAtEkcmkIvgAO6oGDlEQ1OoIADm8PwUCRmWyBDyBSgRRKZRIGLg0ICDRiUAgMAAguCYAAxKCjdr7RYzGCSXbyVzXZardZWTbbc4TA5HUgnDxnHlwS4ufm3e6PCzWV5ed7tVxfH5RCi-fggBwgCCYGCoaAcZCgfJ0aEABXyCGtKBI0ggqAMxpA5hwQwA1kFxHkwCEUcgYDhUnATUcpDAHf6UegSMhqCR-FoTZwWAAhf1gINcpEAGQa6cz2ZAeJ2yF9JHMAE9-NAfZgzLAAOpe+HIAAcAAYTR2IFou-7MPWO8ZtHAfQUAI6pVAFJMkFNppAZrOxkBadCoSPRvcccOBACKqRp8+3Vb3pHMPYMfaQACYTVGSKh6lAUQBhehU3ralxh9VItAAFUbV0dy0CgKCAA)
```sh
--parser babylon
```

**Input:**
```jsx
import { tap } from 'rxjs';
import startService from '../service';

describe('test', () => {
  let instance;

  // Jest func, last paren is on the same line as `done()`
  beforeEach(done =>
    startService()
      .pipe(tap(service => (instance = service)))
      .subscribe(() => done()),
  );

  // Non-Jest func with same length name, last paren is on a new line
  notAJestFn(done =>
    startService()
      .pipe(tap(service => (instance = service)))
      .subscribe(() => done()),
  );
});

```

**Output:**
```jsx
import { tap } from "rxjs";
import startService from "../service";

describe("test", () => {
  let instance;

  // Jest func, last paren is on the same line as `done()`
  beforeEach(done =>
    startService()
      .pipe(tap(service => (instance = service)))
      .subscribe(() => done()));

  // Non-Jest func with same length name, last paren is on a new line
  notAJestFn(done =>
    startService()
      .pipe(tap(service => (instance = service)))
      .subscribe(() => done())
  );
});

```

**Expected behavior:**
I would expect the name of a function to not matter when formatting code with Prettier. It appears that Jest test funcs are treated differently (`beforeEach`, `beforeAll`, `afterEach`, `afterAll`). Not certain if this is intentional or a bug.

**Comment by j-f1** [comment]
This is a bug — we always inline the bodies of functions such as these to avoid excessive indentation, but we shouldn’t do that in this case.

**Comment by ericsakmar** [comment]
Seems to be related to #4241.

**Comment by peanutenthusiast** [comment]
Happy to look into this!

**Comment by eldarshamukhamedov** [comment]
Thanks @ericsakmar! 💯
