### ISSUE TITLE
Trailing Commas set none, when format autosave ,It's not working

### ISSUE THREAD

**Issue by believeZJP** [prettier/prettier#4934]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
// code snippet

"prettier.trailingComma": "none",
"editor.formatOnSave": true,
```

**Output:**
```jsx
// code snippet
```

**Expected behavior:**
trailingComma remove .

**Comment by believeZJP** [comment]
@duailibe

**Comment by suchipi** [comment]
@believeZJP you need to fill out the issue template so that we know what problem you are having.
