### ISSUE TITLE
Strange behavior with word `connect`

### ISSUE THREAD

**Issue by arch-mage** [prettier/prettier#4935]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc05hgCgBYQM4wA0ABAA4QBOMAlANwA6UkUU6WuBJ5VdjzLbHPiJlKNBlBCEQEUjACW0PMlABDChQgB3AArqEylKoBuEeQBMpIAEYVVYANZwYAZVL35UAObIYFAK5w0p54cFQ6dl4AtqrIAGaqADah0gBWeAAeAEJ2js4uqlFwADKecPFJKSDuFKEUyDaq1gCeidBWpBSeMADqFjDYyAAcAAzSnfhwPXakDZ1wdcbl0hRwAI7+8qsRqtGxSAnJQSChUfK+Acd4nl6JcACK-hDwFUfSME195gPIAEzvdnkiRuAGEIFEYg0oGgrP5QgAVJqGQ6hAC+qKAA)

**Input:**
```jsx
conect(host, port);
connect(host, port);
connnect(host, port);
```

**Output:**
```jsx
conect(host, port);
connect(
  host,
  port
);
connnect(host, port);
```

**Expected output:**
```jsx
conect(host, port);
connect(host, port); // should not be split to multiple lines
connnect(host, port);
```

**Comment by suchipi** [comment]
This is caused by https://github.com/prettier/prettier/pull/4431; see https://github.com/prettier/prettier/issues/1420 and https://github.com/prettier/prettier/issues/4172

**Comment by linorabolini** [comment]
Same thing is happening to me.
My problem is that from this: 

```javascript
g.connect("A", "B")
g.connect("D", "B")
g.connect("B", "C")
g.connect("D", "C")
```

I get this:
```javascript
g.connect(
    "A",
    "B"
)
g.connect(
    "D",
    "B"
)
g.connect(
    "B",
    "C"
)
g.connect(
    "D",
    "C"
)
```

The quick solution is to change my API, but I would love to have a way to override this behaviour.

**Comment by linorabolini** [comment]
Hi ! ping again, will there be a way to disable this ? I'm not even using redux :(

**Comment by lydell** [comment]
@linorabolini Sorry, there's no way to turn it off other than using a `// prettier-ignore` comment.

**Comment by makepost** [comment]
Maybe you could limit the Redux override to the `connect()` function import, but prevent it from affecting calls to `.connect()` instance methods? It's a common verb, used when you have to [join an OpenTok session](https://tokbox.com/developer/guides/connect-session/js/#connecting), [init a Node.js socket](https://nodejs.org/api/net.html#net_socket_connect) or, well, [connect to MongoDB](https://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html#connect). For [desktop apps](https://en.wikipedia.org/wiki/GObject), `.connect()` is like `.addEventListener()` for DOM elements and `.on()` for Node event emitters.

```js
// Should be:
button.connect("clicked", () => doSomething());
app.connect("activate", async () => {
  await data.load();
  win.show_all();
});

// But Prettier does:
button.connect(
  "clicked",
  () => doSomething()
);
app.connect(
  "activate",
  async () => {
    await data.load();
    win.show_all();
  }
);
```

**Comment by linorabolini** [comment]
> @linorabolini Sorry, there's no way to turn it off other than using a `// prettier-ignore` comment.

Lets wait for Redux to stop being used too much then! hahah
