### ISSUE TITLE
prettier v1.4 does not work on styled-components

### ISSUE THREAD

**Issue by sevenryze** [prettier/prettier#4937]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3wCU4SwCAzHCdfAHRBxrvYG5WoM2PEVIVqtGABEA8gFl8jZmw5cYAWgAmzXv0G4CAQUyYFTFuwB0AehLGdArPvzB8qKACs4dAOIAbCABGJL74AL6mSuxkMACevnAaapCOUAgwZPa6Hl4wfoHBAAb8+CWlARAaMc7FpWxQJawwjc1NMOgkOADmbkj4AAx8UPw1mCQaGm6dvQPDQ-UK0Or0JOiovjG9ZCRQZGpkcDio9IOh-AWD-OJ0MrIWnFAaBwAUADxGJlYAfAA0+FpgAFd0GkLJ04DAAKLxYGwABCMQAkhonuwmBAmiAAJSYwYgb4gCCYGCoaBkZCgDpMADuAAUOggySgSAA3CCoDR4kABHC0ADW4IAyqMwJNkDAcAC4Pi3Ps8DSeZ12shlr59vj3GQAB6wnlgfkwAUrOAAGTccGVwTVIFGOFlyC5JACcWgnMwh1gAHV2TAABbIAAcfXxbog+w9PMw9rdcFlzPN+M4AEcAahOPKSIqSBbVVKQPtVmKJbmyJN4gBFAHo81IFVWmCOr0aX3IABM+PFJDWkwAwswlSgoNB4yAAfsACqOxm1uChUJAA)
```sh
--parser babylon
```

**Input:**
```jsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import App from "./app";
import { injectGlobal } from "styled-components";

injectGlobal`
      body {
     
  					margin: 0;


  padding: 0;


  font-family: sans-serif;
}
`;

ReactDOM.render(<App />, document.getElementById("root"));

```

**Output:**
```jsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import App from "./app";
import { injectGlobal } from "styled-components";

injectGlobal`
      body {
     
  					margin: 0;


  padding: 0;


  font-family: sans-serif;
}
`;

ReactDOM.render(<App />, document.getElementById("root"));

```

**Expected behavior:**
Format the above tagged template.

**Comment by duailibe** [comment]
Hi, this has been discussed before. We don't support `injectGlobal` at the moment, but we might support making this list configurable. See #2970 and #4424.

Closing this as duplicate.
