### ISSUE TITLE
Typescript: unexpected tag is added when formatting declaration file

### ISSUE THREAD

**Issue by misoguy** [prettier/prettier#4938]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAkigGcYCBLAWyrlwAVMBXAcwqiQIAoBKAgXgB8BRq3YAeALIR0mEgBpKVAA4RcMLgB0QAOh0B6Pfsj59JXGH0wAnsvYsS2njoCCYGBWjjsUa4p-WgoIA3CDyIBDKHtAkyKB4uBAA7vR4CLEo2ABuEBSoYSAARrjYYADWcDAAysql9sgwuExw4ewkdDD0JSxU2MgAZthyLSAAViQAHgBCJeWVVdi0ADLscAND7eG1uO24yCA2ynAkYLgUUQXKZ7AA6nkwABbIABwADFuJ7TclyvtXx3QsmtwvgAI5MCj4LrYHp9JCDYbhdpUCgNJojEj2TBwACKTAg8HWiIO2EKd1Qj2QACZwo1sBRMPYAMIQGhwkBQaDAkBMdoAFVJGQR7QAviKgA)
```sh
# Options:
--parser typescript
```

**Input:**
```jsx
declare const immerPlugin: () => Plugin<Models, import("../../core/src/typings").Action<any, any>>;
```

**Output:**
```jsx
declare const immerPlugin: () => Plugin<
  Models,
  import("../../core/src/typings").Action<any, any><any, any> <-- unexpected
>;
```

**Expected behavior:**
```jsx
declare const immerPlugin: () => Plugin<
  Models,
  import("../../core/src/typings").Action<any, any>
>;
```

**Comment by ikatyang** [comment]
Tracked in eslint/typescript-eslint-parser#507.
