### ISSUE TITLE
After upgrading to v1.14.0 formatted by prettier code in some cases looks ugly

### ISSUE THREAD

**Issue by yuliaHope** [prettier/prettier#4941]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXnQHgCYCWAbgHwDKAhgDZwDO6MFGdMBAthfHugK60FQA5ugroATpzjoIAM3TBa1OgBUm6AFToAjAAYdAXwCkAOhwB6QqQA6UGxmz5iJG+nmsYNfQDIoAI1oADgDcNuaWJCAANCAQAazQtMigFGJiEADuAAopCIkoFEQQBHhRIL4SYADWcDBkARRgAoLIMGI8cNECtHBiMJkSghzIMtTd0QBWtKgAQhXVtRRscAAyAnDDox0g9WLdYshlFL4AnlTQpQFp3QDqEgEHl3Q9ROvRYnAAjjwE7-0UgxQNlQxiBumwCC02lt+EIaABFHgQeBAkGMXzXYowAAWyAATNFWhQCFQmgBhCBsIYoKDQV4gPhwVT+FFbS4CGAYvDY5C6PT6fRAA)
```sh
# Options (if any):
--parser babylon
--print-width 1000
```

**Input:**
```jsx
x = <div>Sales tax estimated using a rate of {salesTax * 100}%.</div>

x = <div>
  {title}&nbsp;
</div>
```

**Output:**
```jsx
x = (
  <div>
    Sales tax estimated using a rate of {salesTax * 100}
    %.
  </div>
);

x = (
  <div>
    {title}
    &nbsp;
  </div>
);

```

**Expected behavior:**
Don't split this jsx text and don't move it to new line.

**Comment by gpbl** [comment]
Yeah we are waiting to upgrade to 1.14 for the same reason, and see what others are saying.

Examples:

```diff
 <span>
-    <strong>{name}</strong>’s{' '}
+    <strong>{pet.name}</strong>
+    ’s{' '}

- </strong>.<br />
+ </strong>
+ .<br />

- <Text>You {type}ed this shipment to</Text>
+ <Text>
+     You {type}
+     ed this shipment to
+ </Text>
```

The last one is the worst :)

**Comment by dawnmist** [comment]
I was about to raise this as an issue, however I think it doesn't just look wrong, it changes the generated the string.

Every string inside a JSX tag that uses a combination of plain text and variables is being reformatted in this way (still in 1.14.2) - introducing additional white space into the string that should NOT be there.

examples:
```
<HelpBlock>
  {parameter.Description}: {errorMsg}
</HelpBlock>
```
is reformatted to
```
<HelpBlock>
  {parameter.Description}
  : {errorMsg}
</HelpBlock>
```
effectively turning the string from "Description: ErrorMsg" into "Description : ErrorMsg".
```
<label>
  {value} solution{plural}
</label>
```
turns into
```
<label>
  {value} solution
  {plural}
</label>
```
changing the meaning from "2 solutions" to "2 solution s".

Items inside JSX tags should not be processed as "normal code" unless they themselves are inside curly brackets - which the parts getting reformatted above are not.

The issue can be worked around by putting the entire string inside a template string inside curly brackets, e.g. ```{`${value} solution${plural}`}```- but that can get _really_ ugly if some of those variable calculations were already containing template strings of their own.

**Comment by lydell** [comment]
@dawnmist No. That’s how it works in HTML, but not JSX. Play around in the [Babel REPL](http://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DwGwhgRgpiB8BQACRBvAbmEBXKBfRAzgPbYAuAlkQHZKoAO2ATprvMAPTjRxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-0&prettier=false&targets=&version=6.26.0&envVersion=) and you’l see what I mean.

**Comment by quentez** [comment]
We're having the same problem as @dawnmist. Not only is the new formatting pretty bad to look at, it also changes the result once rendered in the browser. In our case, we have no choice but to stay on `1.13` until this is fixed.

**Comment by kachkaev** [comment]
@quentez how does the render result change for you? Could you please provide the example?

**Comment by quentez** [comment]
In prettier `1.13` we had this line:

```
Copy &quot;{name}&quot;
```

It's transformed in `1.14` to this:

```
Copy &quot;
{name}
&quot;
```

Code style preference aside, I agree that this change should not affect the output. But for some reason, because we use this within our [translation system](https://github.com/lingui/js-lingui), it ends up adding a space before and after the `name` variable.

It looks that this may be specific to this library (and I'll make sure to report that to them), but I wonder how many other libraries out there may make the same mistake and add spaces in that situation.

**Comment by jquense** [comment]
ditto the new rendering is weird, and makes reading text intermingled with jsx very hard to read...

**Comment by fatfisz** [comment]
One more example (only for the tests, nothing more to add here):

```jsx
// 1.13.7
<BasicText light>(avg. {value}/5)</BasicText>
```

```jsx
// 1.14.2
<BasicText light>
  (avg. {value}
  /5)
</BasicText>
```

**Comment by lydell** [comment]
That’s a really good example :+1:

**Comment by ericsakmar** [comment]
Looks like this is related to:
https://github.com/prettier/prettier/pull/2272

**Comment by jquense** [comment]
another common example we run into:
13.7
```
<p>
  Use the <code>Button</code>'s
</p>;
```

14.2
```
<p>
    Use the <code>Button</code>
    's
</p>
```

**Comment by ericsakmar** [comment]
Working on a fix, but I want to make sure I understand everything correctly...

Given this input:
```
this_really_should_split_across_lines =
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after
  </div>
```

Do we want this?
```
this_really_should_split_across_lines = (
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{
      stuff
    }after
  </div>
);
```

Or this?
```
this_really_should_split_across_lines = (
  <div>
    before
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
  </div>
);
```

**Comment by j-f1** [comment]
I’d say the second. We shouldn’t be breaking the `{}` like that.

**Comment by jquense** [comment]
the second would recreate the current behavior tho? If user provided line breaks were respected it'd ok so you can not get the whole word broken to a new line thing

**Comment by ericsakmar** [comment]
The second looks better, and that's the [documented behavior](https://prettier.io/blog/2018/07/29/1.14.0.html#handle-jsx-whitespace-separately-from-fbt-whitespace-4717-by-karl), but I'm having a hard time telling the difference between:

```
<BasicText light>(avg. {value}/5)</BasicText>
```
and
```
this_really_should_split_across_lines =
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after
  </div>
```

We don't want a break in the first one, but we do want breaks in the second one, correct? In the code, how can we figure out which is which?

**Comment by quentez** [comment]
I think in our case the problematic part is mostly that it will be split in multiple lines even when it's far from reaching the max-length. In cases with a lot of text it's completely Ok to break it, but the current version of Prettier does it even when there isn't a need.

**Comment by ericsakmar** [comment]
My apologies, I just noticed #4965. It seems to do what we want, yes?

**Comment by j-f1** [comment]
cc @lydell

**Comment by lydell** [comment]
Yeah, I guess #4965 seems pretty good when testing with the examples from this issue:

**Prettier pr-4965**
[Playground link](https://deploy-preview-4965--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAPABAXnQHgCYCWAbgHwDKAhgDZwDO6MFGdMBAthfHugK60FQA5ugroATpzjoIAM3TBa1OgBUm6AFToAjAAYdAXwCkAOhwB6QqQA6UGxmz5iJG+nmsYNfQDIoAI1oADgDcNuaWzlCudli44S64gRRQEa6uOLQwYtCCJMBQFGxw+uYZWUIkgJgEtMAA5Og1+vElAUkp6AAScFRUEAmZ2SQA7hBiVHgl-eWmvmLoZm04ynCoMCQAmhA8bgCeAUVw3DAAFgT0tCcBhbAMEOZLKxFhTjbRDp1UAQBCPWAA1m3AFoSQrwMTGAAidDAYgIAVY0H0SHkcDEWTEAFlaIJGlBzO8vj9-vFXrgqBRfF0AURqDwiuhaBAqDx4VBAUyJFQceYyRSqG0SekWskAMIQALbdBeACOPAgMCCeQKRWlsvlzVaxKg9lwnwo-DA9xg6CoBEER1WAAoKERBMZ5NSmUUzABWACU5l1+sN-K1MRwATaAFVaFJjlIcJA8HASJ9mTBoOZI9GarRQmYAyFbLATrQAPpiODUKjbXPnTZjUsBE0wXMUaEQWh5k1QOhYJpxSKpCkyEZwBQwHgyGT6CgyUH9wfD0fjjKTkdjlETofzmcD5fTxez9cLsRLqc7poWJwgAA0IDFLNoyFAFFREEGAAVbwgryhrRACHhTyAZnXfnAYDIFowAEQRkEyWkzwEEMxBgB8JEEDhkBkagQzPAArWhUE+CQ-gAyhCgAGQEOBkNQuAzyBGDkB-clth6KBvwCGFYAAdU-Y5kAADh0SishDViJACGjmLoFEiFIs8CxlAgC3gihEIoMiqDQkAQzYAhwLESC1NAmgAEVVVIpAUJUiiQEYXx2LwTikAAJjPTIKAIZtBFFNgkJQKBoEkkA+DgVR-GUkN9H0IA)
```sh
--parser babylon
```

**Input:**
```jsx
x = <div>Sales tax estimated using a rate of {salesTax * 100}%.</div>

x = <div>
  {title}&nbsp;
</div>
  
x = <div>
  <span>
    <strong>{name}</strong>’s{' '}
  </span>
  Hello <strong>world</strong>.<br />
  <Text>You {type}ed this shipment to</Text>
</div>

x = <HelpBlock>
  {parameter.Description}: {errorMsg}
</HelpBlock>
  
x = <label>
  {value} solution{plural}
</label>
  
x = <span>Copy &quot;{name}&quot;</span>
  
x = <BasicText light>(avg. {value}/5)</BasicText>
  
x = <p>
  Use the <code>Button</code>'s
</p>;

this_really_should_split_across_lines =
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after
  </div>
```

**Output:**
```jsx
x = <div>Sales tax estimated using a rate of {salesTax * 100}%.</div>;

x = <div>{title}&nbsp;</div>;

x = (
  <div>
    <span>
      <strong>{name}</strong>’s{" "}
    </span>
    Hello <strong>world</strong>.
    <br />
    <Text>You {type}ed this shipment to</Text>
  </div>
);

x = (
  <HelpBlock>
    {parameter.Description}: {errorMsg}
  </HelpBlock>
);

x = (
  <label>
    {value} solution{plural}
  </label>
);

x = <span>Copy &quot;{name}&quot;</span>;

x = <BasicText light>(avg. {value}/5)</BasicText>;

x = (
  <p>
    Use the <code>Button</code>'s
  </p>
);

this_really_should_split_across_lines = (
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}
    after{stuff}after
  </div>
);

```

If somebody could add the above as test cases to #4965 and double-check the intention of the 1.14 PR that made this change, I think we should merge it!

**Comment by j-f1** [comment]
Please try to use/credit @yuliaHope’s commits when creating the PR.

**Comment by yuliaHope** [comment]
@j-f1 @lydell I've added the above test cases and double-checked the intention of this PR https://github.com/prettier/prettier/pull/2272. After my changes tests for fb still unchanged and cases from #2231 looks good.

**Comment by lydell** [comment]
Awesome! @vjeux Would you mind double-checking that #5006 doesn't cause any problems for the Facebook stuff?

**Comment by vjeux** [comment]
@lydell i'm pretty busy today but I'll look into it tomorrow.

**Comment by vjeux** [comment]
Lots of things are going on in my life right now and I won't realistically have the time to check it in the next few days. Feel free to ship it and if anything breaks when we decide to update I can circle back and figure things out then. I don't want to slow you down.

**Comment by felixfbecker** [comment]
I've also waited with updating to 1.14 due to this. Here's an example that looks both weird and also doesn't seems equivalent (introduced additional whitespace):
```patch
diff --git a/web/src/org/area/OrgInvitationPage.tsx b/web/src/org/area/OrgInvitationPage.tsx
index 5148d8389e..3d26dedc11 100644
--- a/web/src/org/area/OrgInvitationPage.tsx
+++ b/web/src/org/area/OrgInvitationPage.tsx
@@ -144,7 +144,8 @@ export class OrgInvitationPage extends React.PureComponent<Props, State> {
                                     Join {this.props.org.name}
                                 </button>
                                 <Link className="btn btn-outline-link" to={orgURL(this.props.org.name)}>
-                                    Go to {this.props.org.name}'s profile
+                                    Go to {this.props.org.name}
+                                    's profile
                                 </Link>
                             </div>
                             <div>
```
