### ISSUE TITLE
Doc and API mismatch (getSupportInfo)

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#4942]
**Environments:**
- Prettier Version: 1.14.0
- Running Prettier via: Node API
- Runtime: Node 7.9 (vscode) irrelevant
- Operating System: All

**Steps to reproduce:**
`require('prettier').getSupportInfo().languages.find(l=>l.name === "Flow")`

**Expected behavior:**
It should match https://github.com/prettier/prettier/blob/11275bfa9d683a02c4ce969e2471baf11bc1448a/docs/api.md#prettiergetsupportinfoversion
(Also defined on DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/blob/37615f1933013e56854c09d35192014365328be5/types/prettier/index.d.ts#L240-L254)

In my case it I'm mostly concerned with `vscodeLanguageIds` which must be an array but is `undefined`. I'm using Array functions on it (includes, spread)

**Actual behavior:**
```js
{ name: 'Flow',
  since: '0.0.0',
  parsers: [ 'babylon', 'flow' ],
  extensions: [ '.js.flow' ] }
```
Defined at https://github.com/prettier/prettier/blob/1915cc3c46a6c6df46c192208505d6a7f456152a/src/language-js/index.js#L14-L19

**Actual workaround:**
`vscodeLanguageIds || []`

**Comment by ikatyang** [comment]
I think we should update the docs instead of the implementation since there's no such information for Flow in Linguist and VSCode, an empty array works for `vscodeLanguageIds` but not other Linguist properties. Only `name` and `parsers` are always presented.

**Comment by CiGit** [comment]
Couldn't a `.js.flow` extension simply be a javascript file?

**Comment by ikatyang** [comment]
Ah, I forgot we could reuse the information from js.
