### ISSUE TITLE
Understands `.scss` but not `.sass` files

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [prettier/prettier#4948]
I love this tool, hopefully I could use it with our `sass` files too.

I have tried the override option and run `scss` parser against our `sass` files but it did work out well it produced errors about semi colons (which I also explicitly set to `false` on the override), when I tried `--write` it broke the format.

Here's an example:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wAEA5JADb4DOxAOlBjvkcQGbQzV0O4EkCGULHxjpolAPSUy6ACZwAtAFdstelh7MBQkWPEs+c+eiiq6AOkpw+eMAAt5Adzx9s2OHjqFCuSuh1QkQhZ0AA84GU9CGAhsQIAGSLI4Fhh4yIdZGFtAgEY4uIBSSNs4dABzW1TCPMLIgC8jKDkQwIBmSK1MYVEAwilZBWVCVvzMSkizKD4AN0ivACM+MABrMrwIRSbAgBI1vgBPeRlrZfc5whLyysCAVgAmbBDzjJks3PyiqC8vbAMZYzKt0ehASX2+vxk-ygZXkSRSQKeYJ+fwB8jwVyqN0e52isRB5zhVVB30I-0o2DIB0CLCSiJJACtFJQRCxDpBYAgquSlgp5nAYA44AhznxpGUoEZ4GNAmBOWckYQGsZmoE7uczOhIJgINBzl42LB5L46nBVXg4Jg9YRyPgdvNnE15Nh0V08Ptzv9pkhYBK7OgyDIABQ5ACUVppcBaILMcTVCs93qy8j9AcDdzDCv1tPiZgAnAAOK3wEIweSi8q9WUcjyZ60QCh4HbF0s2msk-XsI3oE25Mx3G5xc2W2sG0v6TD+-Z2h0yeSj8eTq0+Pw9QLmykiaZwK0azBlK1eS4VKp3B509teF5vQh8RTRHeaiDa3W1juG42m6pmHL5-NDg91g204CLOezuq+hCLCsawbI6raBDADrcuasAAcu-iBHw8yUPWd7bhB6LHu82IQbity1KRSFsHgmAIUhG5wIGcQADSEPIA4FBmJIWFYNj2MY2B3la8GEAAxCwdwSRJVrzPgch4Mm9a2mJrSqTJSyrOsmyziJomqe0tayXg8logY6BMm0JEXkZ8lpLWEJQoChD5mYWIhNUcRWe2DmooR1zDG5VpXtkHkUReo5dj21RnhMyqasI+DnOhq43thuHwDiMTkV5XiEuRnwkohAiUNRtFRPRwiMexhSsXEXHfCJ2z2iBZZkDASUotCgS5sCOQACw5UEnYfrkMUKlBmmwTpSmNmJcQ5HcADsrQAGzPJkIVLWNJLSFAChHv5OSua0+Y3OcskhEatgGBADjxIQbkecCeBlIsTHMSxn19vVXidN00DUgYCjGMMozjAqABkSB8tR+EXmSFJUpBFArEuEC+BhqU4WQeHCewnKBMQqjWXJ7iwskVR5MC2OyOVxW-Ch7WGaTCl+ZTnnuTTMh01AyGcjJLPyLJMDRGVVOc-WtOifNS2rUWWVseLVp5Q9YXtkVvOlXRxUMYG1UFLV9UCXeADaMD7G4AC8zYALrnBsMC7Z+UDQHDhA8dYdhonAlCKG1lCwugzLnAdVRgKKYDBh8bEPWeP2EBAW54DSt3yFON53hA50aTB2mKUBhBNTORwnB1kKomRT3nl4kwQN7vttVaCOUunEbV98wXvGrJKh13BXtoyzLoKyikcrAMpym27bluKkoWpQE-VnjBfbM2+eJQqHt8fXftMxePlddUgW1s3SNtwLxlk8Lou5NTkvcy9b39jczHP6-Nwv3EMaLTc8deAmsB7ApiDOmACroyjGHJvCKuAFbB9QAm+UsI1oz5h-v+CCXhGrNUdKKPeF5vgRQXGQdO2woTOizhgwgTt5C9y-H1M6lC14axKvgMqyg3A2D4JYBBQ1DSCgxORYk+DsA8JEo-PgaYP7vxfm-L+fU-7tgisgr+P9BwWh4YQvgE5iE7EoMVI07hh4Pj3ABTuhA+oc1gaUIi5iOYgGYiAGI-hKDIFANYdYDgAAK1gEAuJQDMCAsh7EgGaisfkABlX4YAATIEQooOADjjCWAIJ45wZQujIH0GQSwDj6SUBCAAIWcGEmA4StFwAADLGDgJk0UOSQAM2ScgEJWF9gUCgME50xgYAAHUNrIHzCxBp6xLA9OcNgZpzofbuC3ME80ABHRQ6BzSpL4OkvgtTskJJAJYCcsS8DxIcb4aESQACKigIDwE2fUmAWE+mvFsMgO4Diir+gBAAYSfBklALs9rBKZHAAAKlhPxWTLAAF9wVAA

**Comment by evilebottnawi** [comment]
@sprlwrksAprilmintacpineda we don't support `sass`, only `scss`

**Comment by sprlwrksAprilmintacpineda** [comment]
@evilebottnawi can we?

**Comment by evilebottnawi** [comment]
@sprlwrksAprilmintacpineda PR welcome, but it is require a lot of work

**Comment by sprlwrksAprilmintacpineda** [comment]
Nah, I guess we'll use `scss` then.

For future readers who might want to convert from `sass` to `scss` to be able to use `prettier` (in case this is still not possible that time).

Do these:

```
// install sass to be able to use sass-convert
// more at https://sass-lang.com/documentation/
gem install sass

// convert all files in src directory from sass to scss
// note that this will not delete your original sass files
// instead it will create a file named [originalFileName].scss
// on the same directory as the sass file is.
sass-convert -F sass -T scss -R src/

// then if you want to delete the old sass files
find . -name "*.sass" -type f -delete
// but first you might want to check what you are deleting
find . -name "*.sass" -type f
```
