### ISSUE TITLE
Uncommitted changes remain after a commit in PHPStorm

### ISSUE THREAD

**Issue by igsm** [prettier/prettier#4951]
Hi. I use PHPStorm and prettier (1.13.6) + husky (0.14.3)  + lint-staged (7.2.0). All works well, except the cases when I use IDE's built-in VCS. When I do commit of changed files, it does run prettier formatting and I can see files are formatted properly and committed successfully. However, those files remain in the status of uncommitted changes. So, I need to commit them once again (there are no differences) and only then working tree becomes clean. When I use git commands in the terminal, then, everything works as expected from the single commit. Is it possible that I misconfigured something or is that a potential problem in pre-commit hook integration?

*macOS High Sierra

**Comment by j-f1** [comment]
This is probably an issue with the IDE’s Git implementation. Could you file a ticket with them instead?
