### ISSUE TITLE
problem with git hooks (husky) when using with flow as parser

### ISSUE THREAD

**Issue by paliwalgaurav** [prettier/prettier#4952]
When tried git hooks with `flow` parser then getting this error in `parser-flow.js`
Here is the log:
```
husky > npm run -s precommit (node v8.11.3)

🔍  Finding changed files since git revision d2fe7c5.
🎯  Found 6 changed files.
[directory]/node_modules/prettier/index.js:7129
      throw error;
      ^

SyntaxError: Unexpected token : (2:7)
  1 | {
> 2 | 	"env": {
    | 	     ^
  3 | 		"jest": true,
  4 | 		"browser": true,
  5 | 		"node": true,
    at t ([directory]/node_modules/prettier/parser-flow.js:1:310)
    at Object.parse ([directory]/node_modules/prettier/parser-flow.js:1:1160965)
    at Object.parse$2 [as parse] ([directory]/node_modules/prettier/index.js:7118:19)
    at coreFormat ([directory]/node_modules/prettier/index.js:10378:23)
    at format ([directory]/node_modules/prettier/index.js:10549:16)
    at formatWithCursor ([directory]/node_modules/prettier/index.js:10561:12)
    at [directory]/node_modules/prettier/index.js:32738:15
    at format ([directory]/node_modules/prettier/index.js:32757:12)
    at exports.default ([directory]/node_modules/pretty-quick/dist/formatFiles.js:18:41)
    at exports.default [directory]/node_modules/pretty-quick/dist/index.js:53:29)

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by j-f1** [comment]
What does your config file look like?

**Comment by paliwalgaurav** [comment]
This is in my `package.json` script
 `....
"scripts": {
        ...
        "precommit": "pretty-quick --staged && npm run lint"
    }...`

**Comment by j-f1** [comment]
Do you have a `.prettierrc` file in your repository?

**Comment by paliwalgaurav** [comment]
`.prettierrc.json` I am using eslint also where I've applied the same guide suggested by [prettier doc](https://prettier.io/docs/en/eslint.html#why-not-both)
```
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "all",
	"bracketSpacing": false,
	"printWidth": 120,
	"arrowParens": "avoid",
	"insertPragma": false,
	"jsxBracketSameLine": false,
	"parser": "flow",
	"proseWrap": "preserve",
	"requirePragma": false,
	"semi": true,
	"tabWidth": 2
}
```

**Comment by lydell** [comment]
It looks like the error you get comes from trying to prettify a JSON file. Your configuration says to use the `flow` parser for _everything_ – even JSON (and CSS and markdown etc). JSON is usually not valid JS programs, which is why Prettier errors out. Remove `"parser": "flow"` and you should be fine. If you really need the `flow` parser, set it only for .js files: https://prettier.io/docs/en/configuration.html#configuration-overrides

See #4638 for more information.

**Comment by j-f1** [comment]
The default `babylon` parser supports Flow syntax, so most people don’t need the `flow` parser.

**Comment by paliwalgaurav** [comment]
I solved my problem by ignoring `json` files. And still using `flow` parser.

**Comment by lydell** [comment]
That’s a workaround, yes.
