### ISSUE TITLE
webpack warning: "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by eranation** [prettier/prettier#4959]
**Environments:**
- Prettier Version: 1.14.2
- Running Prettier via: Angular 6, WebPack, TypeScript
- Runtime: Node v8.9.4, TypeScript 2.7.2
- Operating System: macOS

**Steps to reproduce:**

`npm install --save --save-exact prettier`

in some component 

```
import * as prettier from "prettier/standalone";
import * as parserYaml from "prettier/parser-yaml";

...

//somewhere within 
const formatted = prettier.format(..., { semi: false, parser: "yaml", plugins:[parserYaml] } );

```
**Expected behavior:**

No compilation warnings 

**Actual behavior:**

WARNING in ./node_modules/prettier/standalone.js
7397:15-64 Critical dependency: the request of a dependency is an expression

(everything seems to work well, the issue is just the compilation warning)

**Comment by lydell** [comment]
Hi! Can you make a repo that reproduces the problem? That would be really helpful!

**Comment by philcockfield** [comment]
Here's a sample repo demonstrating the problem: https://github.com/philcockfield/prettier-sample

![prettier](https://user-images.githubusercontent.com/185555/44324716-9e2dd700-a4aa-11e8-805d-70d872fb060d.gif)

**Comment by lydell** [comment]
Awesome! Is there any chance you could make the example smaller? For example, get rid of Storybook and Typescript? I think that would increase your chances of this getting fixed.

**Comment by philcockfield** [comment]
Here are details on what that error is and means within Webpack:
https://github.com/webpack/webpack/issues/196#issuecomment-71920500

**Comment by lydell** [comment]
Might be this line:

```
$ grep -n 'require(' standalone.js 
7393:        parse: require(path.resolve(process.cwd(), opts.parser)),
```

**Comment by philcockfield** [comment]
@nickarnold - cool, I haven't figured out how to use that `ContextReplacementPlugin` yet - but now we can see the specific line that is causing the fail, feels like a quick/easy fix (as found by @lydell )

    $ grep -n 'require(' standalone.js 
    7393:        parse: require(path.resolve(process.cwd(), opts.parser)),

**Comment by philcockfield** [comment]
Confirmed that if the following two lines in the build `standalone.js` file are commented out, webpack does not throw this error - so it looks like it's just these to call-sites that need to somehow pass in an explicit path to require, or maybe do something other than use `require` to get these files included.

```
7393:        parse: require(path.resolve(process.cwd(), opts.parser)),
```
Location in [source code](https://github.com/prettier/prettier/blob/cdcb7b11c9afc850ab24420407144772983eefee/src/main/parser.js#L47)

and

```
                case "TSExternalModuleReference":
14793        return concat$4(["require(", path.call(print, "expression"), ")"]);
```
Location in [source code](https://github.com/prettier/prettier/blob/d480858f016c6b165e55195027226a612e97d47c/src/language-js/printer-estree.js#L3116)

**Comment by lydell** [comment]
> webpack does not throw this error

It's a warning, isn't it?

---

Are you sure that line 14793 causes a warning? That sounds strange to me. That line is basically just building a string containing the word "require" – surely that has to be allowed by webpack?

**Comment by lydell** [comment]
> webpack does not throw this error

It's a warning, isn't it?

---

Are you sure that line 14793 causes a warning? That sounds strange to me. That line is basically just building a string containing the word "require" – surely that has to be allowed by webpack?

**Comment by philcockfield** [comment]
Damn, my bad on both accounts @lydell.  Just re-tested and it is just line `7393` that if commented out stops the "warning" (not "error")... yes.  Apologies for confusion.

```
        // parse: require(path.resolve(process.cwd(), opts.parser)),
```

**Comment by philcockfield** [comment]
I've just figured out I can suppress this with this [webpack plugin](https://www.npmjs.com/package/webpack-filter-warnings-plugin), so I'll do that for now.  Mentioning here if anyone else it trying to do the same.

```js
  config.plugins.push(
    new FilterWarningsPlugin({
      exclude: /Critical dependency: the request of a dependency is an expression/,
    }),
  );

```

It's a "warning" by Webpack really does scream blue-murder about this in the console, which makes it hard to disambiguate from actual errors when developing.

**Comment by j-f1** [comment]
Note that [that message has bundle size implications](https://github.com/webpack/webpack/issues/196#issuecomment-71917456).

**Comment by hedgepigdaniel** [comment]
It doesn't make sense to have this line of code https://github.com/prettier/prettier/blob/0c7c1bfde431d5810571834460be126a70bd0f30/src/main/parser.js#L47 being compiled to run in a browser (where there is no `process.cwd`). Webpack warns because that statement is implicitly asking it to compile all the code that could possibly be imported for any value of `process.cwd()` and `opts.parser`. Seeing as that's impossible I assume it gives up and lets it crash.

If you were compiling some node project that used prettier, and you wanted to use the functionality to specify a custom parser, you would probably want to pass it as a node API option, not as a CLI option.

Perhaps it makes sense for the main entry point not to import the code that parses the CLI `--parser` option and resolves it relative to CWD, so that that line is not included in projects that use prettier programmatically. Instead, only the binary entry point can import and use that code, and pass the resolved parser through to the node API.

**Comment by camdagr8** [comment]
This happens because Webpack doesn't actually use require() as a function but a RegEx, so the Node usage of require() as a file reader doesn't work in Webpack. 

This should be taken out for the stand alone version.

**Comment by duailibe** [comment]
PRs welcome

**Comment by j-f1** [comment]
Proposal:

- Wrap the affected `try` block in an `if (!process.env.PRETTIER_STANDALONE)`.
- Create a Babel plugin that replaces `if (!process.env.PRETTIER_STANDALONE) { ... }` with its contents in regular mode and removes the whole statement in standalone mode.

**Comment by j-f1** [comment]
If you’re currently experiencing this warning, can you try installing `prettier/prettier` instead of `prettier` to make sure my fix works?

**Comment by ikatyang** [comment]
@j-f1 `prettier/prettier` is not bundled. (The bundled `dist` will be available on Azure Pipelines after #5611 merged, see [here](https://dev.azure.com/prettier/prettier/_build/results?buildId=244&view=results) for example.)

**Comment by camdagr8** [comment]
Good and thanks for the fix!

**Comment by j-f1** [comment]
Ah, good point @ikatyang.

**Comment by tfrijsewijk** [comment]
When is this slated for release?

**Comment by j-f1** [comment]
Probably sometime in January.
