### ISSUE TITLE
MDX Support

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier#4960]
I would like to open this issue to formally track prettier support of [MDX](https://github.com/mdx-js/mdx) files. I don't know exactly what it would entail, but I _think_ it would actually be a matter of using the `markdown` parser for `.mdx` files and then fixing a handful of formatting bugs with html/jsx in markdown. [For example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAkIHEcBDTAC0PwDMcJ1r8ByAOgHpItoEYBndgHMylZgB0oEgMRT8ACTg44zPvlL5h5ChIkAeElokA3UgBsArnD4BeYAG0AjABoJhAExP8AZlf5PAFgBdAF8JdgA+ECcQCEwYVGg+ZFBSHHoAdwAFVIQklFIjCFQAEyiQACMyMABrOBgAZUxSMFQoQWQaMz44aNbuvEyyQXRSDq6ekAArPgAPACEq2obSdDgAGVa4MdNu6KacfuQQEZxq4oh0qDLMHFaYAHUSmApkAA4ABj36bvuRI5urIojFtokoAI7mVBKQakYajJCdHYTbroVDIGA4SzRPitQSmOAARXMEHg6MxExgpHKj2Kz2QHhAGNIqFMuIAwgwRkcoDwyuZugAVKl5RHdYLBIA):

```md
import   Graph   from    './components/graph'

## Here's a graph

<Graph
values={[1,
  2, 3
  , 4]}
/>
```

With prettier@1.14.2 Becomes:

```md
import Graph from './components/graph'

## Here's a graph

<Graph
values={[1,
2, 3
, 4]}
/>
```

I don't have time to personally work on this, but perhaps someone else would be able and willing to look into this?

**Comment by timneutkens** [comment]
Considering mdx is a remark transform it could actually work on the MDXAST spec and then run the JavaScript formatted on jsx blocks

**Comment by ikatyang** [comment]
Unfortunately, they didn't expose the MDAST -> MDXAST remark plugin ([they did have one but it's somehow deprecated](https://github.com/mdx-js/mdx/tree/master/packages/mdxast)), they currently [only exposed the MDAST -> MDXHAST part](https://github.com/mdx-js/mdx/blob/90ec9249fa8b5fc551a0c9f1ff4ff1d6c245efe5/packages/mdx/index.js#L51-L71), which is not suitable for our usecase.

**Comment by ikatyang** [comment]
Actually, the MDXAST implementation is pretty small so I just copy-paste them here. Opened #4975.
