### ISSUE TITLE
Bad format when using Ternary + Chaning methods

### ISSUE THREAD

**Issue by jquintozamora** [prettier/prettier#4967]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAngeQCMArOMLAXk2AF8BuAHSicig0wBMBDeNTCpphwESZLADJxwoqXIA6PAEEATsq65BQzAH5po+UtXrNWzAq4AHABQBLfgD5qJ05mVwYAV2VRMNxj5caAEpnITkAMxsAG3hlKwAhCAgouC4oEIChJEwAbQBdOhAAGhAICxgbdGRQLlUIAHcABVqENGQQLgA3CBsOYpBCNTAAa3cAZQsuMBsoAHNkGGUPOBKZtDhlGEa1WewuZHCuKPWS4jQAD3ih0Zgxrmw4ABkZuAOjk5BJ5XXldsIuQi4KLQfoWZQzGAAdV6MAAFsgABwABhKYIg60hags7TBcB+nVeJTcAEcPDY3NsuLt9khDscViB1tgbAslgy0DNZikAIoeCDwN70kowAHQjhw5AAJmFaminIAwhBsHt2lBoISQB51gAVAFtWnvOA0GhAA)
```sh
--parser babylon
```

**Input:**
```jsx
const myObject = {};

const dates =
  myObject && myObject.myArray
    ? myObject.myArray
      .map(i => {
        return i;
      })
      .filter(Boolean)
    : [];
```

**Output:**
```jsx
const myObject = {};

const dates =
  myObject && myObject.myArray
    ? myObject.myArray
        .map(i => {
          return i;
        })
        .filter(Boolean)
    : [];

```

**Expected behavior:**
[eslint] Expected indentation of 6 spaces but found 8. (indent)
That happens on  .map and .filter methods.
```
const dates =
  myObject && myObject.myArray
    ? myObject.myArray
      .map(i => {
        return i;
      })
      .filter(Boolean)
    : [];
```

**Comment by duailibe** [comment]
I think the ESLint "safe" version is worse

**Comment by lydell** [comment]
That's how Prettier prints ternaries: It indents once and aligns using two spaces (regardless of your type of indent). This has been discussed before and is not going to change. There are loads of issues related to this if you want to know more.

**Comment by jquintozamora** [comment]
@lydell any ideas to silence eslint indent rule for that specific behavior?

**Comment by lydell** [comment]
Put `"indent": "off"` in your config or use [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).
