### ISSUE TITLE
unnecessary comma prepend to start of an array

### ISSUE THREAD

**Issue by noscripter** [prettier/prettier#4973]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqCWAzVAKAW0wGcxUAyc1GATwAc4JcjTUBeD1AcggCMArOGBhcAlKmAAdKBgwBtLjACGxANYBJKNghcANN1IALOABMArgBs4m7XoMBHCwAUlAJyUFiXALoA6Akp0eKrsAHwS0rKyVjCoEACM7NQQAFIAynhKwphQAOZyqt6ikVHoMXEATEksYAXeJaU4+LQMTJXsnDwCQiIUVACEAEq+cPZmShbEeAn6EBWi4lIypRhZMDn5hUkA8t3CvirEmLlQ04kAPucSAL6z8w1R1w-o18XLLyC6IBB069DEyFAblcEAA7i5XAgASglAA3CCYEyfEC8dxgVRwGBpOhZDbIGCuMxwL45YhwVwwJzuXIBZDYCZkr78YgADwAQmiMViPHAADI5OD4wnEkA41xk1zIFFKXg0CzQZF0Vw5GAAdURMEMyAAHAAGL5KiBk1XuOhSpVwCWwwVfSFjTCQqlKGlKOkMkVkohuyYejZWACKZgg8CFRK+yl46pMmuQFXD7kwFg2AGEIARaSgoNAbSAzGSACoy6H0n3Xa5AA)

**Input:**
```javascript
    if (misc && typeof misc === 'object') {
      ;['taskInfo', 'scheduleInfo', 'sqlParams'].map(k => {
        let o1 = toJS(acting[k])
        let o2 = misc[k]
        if (typeof o2 === 'object' && !R.equals(o1, o2)) {
          acting[k] = Object.assign(o1 || {}, o2)
        }
      })
    }
```

**Output:**
```jsx
if (misc && typeof misc === 'object') {
  ;['taskInfo', 'scheduleInfo', 'sqlParams'].map(k => {
    let o1 = toJS(acting[k])
    let o2 = misc[k]
    if (typeof o2 === 'object' && !R.equals(o1, o2)) {
      acting[k] = Object.assign(o1 || {}, o2)
    }
  })
}
```

**Expected behavior:**

```javascript
if (misc && typeof misc === 'object') {
  ['taskInfo', 'scheduleInfo', 'sqlParams'].map(k => {
    let o1 = toJS(acting[k])
    let o2 = misc[k]
    if (typeof o2 === 'object' && !R.equals(o1, o2)) {
      acting[k] = Object.assign(o1 || {}, o2)
    }
  })
}
```

no comma should be prepend to the start of the array

**Comment by ikatyang** [comment]
It's intended, see https://prettier.io/docs/en/rationale.html#semicolons.

**Comment by noscripter** [comment]
Thanks for you explanation. @ikatyang
