### ISSUE TITLE
Can't format itself

### ISSUE THREAD

**Issue by atilkan** [prettier/prettier#4977]
<img width="634" alt="screen shot 2018-08-14 at 11 45 43" src="https://user-images.githubusercontent.com/1254613/44081589-bbd4fe66-9fb7-11e8-8c2e-5d1197ce6980.png">

**Comment by ikatyang** [comment]
You're currently forcing Prettier to use the `typescript` parser so it's indeed a SyntaxError from TypeScript perspective. You don't need to specify `parser` manually, Prettier will infer which parser to use based on the file extension by default.

It should work just fine if you remove the `"parser": "typescript"`, see #4638 for more info.

**Comment by atilkan** [comment]
@ikatyang 
Thank you. I think prettier should infer its own config file too. Also what if i use typescript inside other file types forex **.vue** file.

**Comment by j-f1** [comment]
Prettier does infer the parser for its config file, it’s just that if you explicitly set the parser, it won’t try to infer.

Also, we have a Vue parser currently, and if you specify the language as TypeScript in the `<script>`, it’ll parse it properly.

> I always setup but later find myself disabling prettier because of conflicts with tslint etc.

Check out [`tslint-config-prettier`](https://github.com/alexjoverm/tslint-config-prettier).

**Comment by atilkan** [comment]
@j-f1 
Thanks. I discovered that plugin yesterday. It does the job so far. I will give it some more time.
