### ISSUE TITLE
Prettier adding 2 spaces when using ternary operator and plain object definition

### ISSUE THREAD

**Issue by DanielHoffmann** [prettier/prettier#4979]
**Prettier 1.14.2**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlPvfgE5wzqN0yPpy0N-4B+Kr36j6xGAEYk+AOQTJsgDQix-CQCYZ8uCQ2zVYgL6G+MmnTXrdU7QuWmrmuzf2O+RgNy0TUWpCgiCAAbOAA6YIgAc1IJCnJvKBAlEAgAB1xoImRQAENGRggAdwAFfIRslFyANwgcABNkkAAjRlywAGsWAGU09pwoKORObhSBojhGGBK2qIBbXORUXOCJlIArIgAPACE2zp7cubgAGQG4JZW1kD7GCcZkFtzmgE9IpJS0xgGYAHUGmAAC2QAA4AAyfQoTX5tNKPL66SbVC4pZgAR3QOGYM1y80WSGWqzgKQmcxwwy4xJARAGUVCAEV0BB4BTRiAYM9-vUgcgACwpTi5HDBWkAYQgcwWjyg0BRIHQEwAKs9KoSJkYjEA

Happens with any set of options but easier to see with  `--tab-width 4`
```sh
--tab-width 4 --single-quote --trailing-comma none
```

**Input:**
```jsx
function test() {
    return true
        ? {
              test1: 'test1',
              test2: 'test2'
          }
        : {
              test1: 'test1',
              test2: 'test2'
          };
}

console.log(test());
```

**Output:**
```jsx
function test() {
    return true
        ? {
              test1: 'test1',
              test2: 'test2'
          }
        : {
              test1: 'test1',
              test2: 'test2'
          };
}

console.log(test());
```

**Expected behavior:**
```jsx
function test() {
    return true
        ? {
            test1: 'test1',
            test2: 'test2'
        }
        : {
            test1: 'test1',
            test2: 'test2'
        };
}

console.log(test());
```

2 extra spaces are added on lines subsequent to a ternary operator. This breaks eslint `indent` rule.

I set up a project showing this bug and how it breaks eslint:
clone https://github.com/DanielHoffmann/prettier-test
`npm install`
`npm run precommit`

The `precommit` script will run prettier with `--tab-width 4` and after that will run eslint with `rules: { indent: ["error", 4] }`, this will always result in an error because of the 2 extra spaces mentioned before

This seems related to #4976

**Comment by jespersage** [comment]
+1

**Comment by lydell** [comment]
We recommend turning off all ESLint rules that conflict with Prettier. See:

- https://github.com/prettier/eslint-config-prettier
- https://prettier.io/docs/en/eslint.html

**Comment by DanielHoffmann** [comment]
@lydell thanks for the info, sorry I didn't see this part of the docs earlier. I know prettier is supposed to be an opinionated code formatting tool, but the way it formats ternary operators is weird, I would vouch for changing it. Not only for eslint sake, but for keeping consistent tab spacing in the code.

For example check the vertical pipes that show the identation in this screenshot taken from VSCode:
![screen shot 2018-08-15 at 09 32 06](https://user-images.githubusercontent.com/2980150/44136750-3bf2a290-a06e-11e8-9240-3be4f1fbff40.png)

below `something` there is a vertical pipe that is not aligned correctly because of this weird behaviour from prettier. Do you think I should open another issue asking for this to be changed?

**Comment by lydell** [comment]
I think there are previous issues about that.
