### ISSUE TITLE
Using with RxJS marble diagrams

### ISSUE THREAD

**Issue by olessavluk** [prettier/prettier#4981]
Hello!
I would like to use prettier, but it is breaking formatting of [marble diagrams in rxjs tests](https://github.com/cartant/rxjs-marbles#with-mocha).
Is there any way to disable formatting for the block of code, or any other way to solve this issue?

What I have tried so far:
 - `/* prettier-ignore */` for every line makes diagram hard to read
 -  `.prettierignore` which ignores entire file, but I want to ignore only block with diagram

**Prettier 1.14.2**
[Playground example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmH3QEMcAjAGzgGd8BffAMxwnXwB0QcAPAKxoBaUhWo0A9OghgAFiS4BuDlAzY8hYiUwNmrdl14DxETHBwkYuGouXKAJrTA5U5OAAoD-ISKq0uAGnw3AEp8AF4APkJbKHw4-FQYDxAaGQgAV0o7fBp0zDUCH2p8eBoYaxBAoto3dkjoqGV45vxxACp8TBw4GBhUM0FUAHMoXDhBMrICNvEmlrjIKDKcjJwwOHC49AA6NKSuQUEAPUESQXJBMEEAHy5gpVj5-EXl3PI6MKeWrhPDv8EAIQ2R7zF4EOA8UxgeDZT5PA7nS6COw3YFfdqdbq9fo4QYjMaCBDZGYxL5g-AOMqoKAWVDQTY0VbrbaYVCmDwgr6aTBuABuJEo6Q29QAyjBnFAhtsWGwAMJyHCyiAOPkCoXbWRkJUOACCSQADKEANT4ACMwWCc3m9ytLR2EKhSUpfRpfWgwW2lgAQnAAPLvMz83xuB1waFwOw2znNe2QsNJRnpNZwD2WAASJF5cBF6XeTjZbqWbjeNCjzXoFoeFYUlRAJkLNGQoDIrAA7gAFMgIRsoTMQVB2WvkcxgADWPRFmBIYGpQ2Q4qF-jQSzMMHb5iGpGQTAFNDgS4EPC9I-HMBFJHQcAAMtS4Nvd-uQFOcHucMgQOQSOQAJ6UaC1rpqRgAB1AcYBkZAAA59SXLoID3YDzEwd8uloQM7yXboAEd0lQbp1xITcSHvSg9yXPd0FQeccEXFJZ2oABFdIIHgEiyJAGAv1AuxwOQAAmJdxRIVBKFnJV0C3FBRigDCQHSPcABUvx7HdSLgeh6CAA)

**Input:**
```jsx
const source =  m.hot("--^-a-b-c-|");
const subs =            "^-------!";
const expected =        "--b-c-d-|";
```

**Output:**
```js
const source = m.hot("--^-a-b-c-|");
const subs = "^-------!";
const expected = "--b-c-d-|";

```

**Expected behavior:**
```js
// prettier-ignore-start
const source =  m.hot("--^-a-b-c-|");
const subs =            "^-------!";
const expected =        "--b-c-d-|";
// prettier-ignore-end
```

**Comment by lydell** [comment]
There is such a thing in markdown, but not for any other languages.

You use comments to align your stuff up:

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaIFcBOYcmAvJgPQBUl5mAtgHQAWEMAFADogC03AetwCG3AEbcw3AD5cAlAG4OUSFAzZcItKQqVMuvfpqYuA3qe4BCLgqXoscAB4AHOGHgATLVX27DXXmIk3KStFEAAaEAhHGABLdGRQQXx8CAB3AAUkhDRkEEEANwgYt3CQEXxBMABrOBgAZUdKmKgAc2QYfFw4COa0OHwYdIqWukFkADNBABs+iIArNHsAIQrq2rrBOjgAGWa4CenZkEb8PvxckUERAE8p6FLHfGaYAHVimCZkAA4ABgjHiB9F4VRy5R5wM75fYRfBwACOuBisKGghGYyQkxm3RAfToMXanWxaGaLSmcAAirhWPsMYdsTArm83B9kAAmCIdQQxKYkgDCEDoo1yUGg0JAuD6ABUrjlaViAL7yoA)
```sh
--parser babylon
```

**Input:**
```jsx
const source = /**/ m.hot("--^-a-b-c-|");
const subs = /*          */ "^-------!";
const expected = /*      */ "--b-c-d-|";

```

**Output:**
```jsx
const source = /**/ m.hot("--^-a-b-c-|");
const subs = /*          */ "^-------!";
const expected = /*      */ "--b-c-d-|";

```

**Comment by suchipi** [comment]
You can also create an anonymous block and ignore it:

**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSmHow0igGcYM2IBXHMOBgC8GALYA6ABYQYAClohSpAHqkAhqQBGpMKQA+CgJQBuJi2gcuPTW2HN7DhaqUvSAQgWmozVpbgAPLDgweAATO0dFLR1SUP1PegBfehAAGhAILCILZFA1HBwIAHcABXyENmQQNQA3CEJQtJBNHDUwAGt8AGUsNsIoCmQYHB44dP62EhgS1opRNWQAMzUAG0n0gCs2fwAhVo7utVE4ABl+uCXV9ZBenEmcKs01TQBPFegm3H6YAHUGmEkyAAHAAGdK4CCTH6tLBVXBwe41C7pPAARx4hDwMzUcwWSGWazGIEmokIQxGRLY-QoKzgAEUeDILvirkSYM8-qEAcgAEzpYZqQgrakAYQgonmVWoUGRIB4kwAKs9KizCYlEkA)
```sh
--parser babylon
```

**Input:**
```jsx
// prettier-ignore
{
  const source = m.hot("--^-a-b-c-|");
  const subs =         "^-------!";
  const expected =     "--b-c-d-|";
}

```

**Output:**
```jsx
// prettier-ignore
{
  const source = m.hot("--^-a-b-c-|");
  const subs =         "^-------!";
  const expected =     "--b-c-d-|";
}

```

But this changes the scope of the `const`s, so you might have to use `let`s instead to get them to the outer scope.

**Comment by aboyton** [comment]
Another alternative is to use a different marble testing library that supports inline whitespace. I've been using 
https://github.com/kwonoj/rx-sandbox as it has support but it looks like 
https://github.com/synapse-wireless-labs/jasmine-marbles/issues/3 now has support.

With such libraries you should be able to write this as

```ts
const source = m.hot("--^-a-b-c-|");
const subs = "        ^-------!";
const expected = "    --b-c-d-|";
```

Another alternative to switching libraries would be to open an issue on https://github.com/cartant/rxjs-marbles The changes weren't hard for me to add to https://github.com/synapse-wireless-labs/jasmine-marbles when I was playing around with it.

**Comment by olessavluk** [comment]
In the end I am using method proposed by @aboyton (padding with inline whitespace), and it was already supported by rxjs-marbles

Thanks everyone for help 🎉
