### ISSUE TITLE
Problem with decorators format after upgrading from 1.13 to 1.14.2 using vscode editor

### ISSUE THREAD

**Issue by jmsstudio** [prettier/prettier#4983]
After upgrading to 1.14.2, as stated in the docs, the decorators now have a line break when declared within attributes. When using vscode (with the plugins eslint-config-prettier and eslint-plugin-prettier), the CLI formats it correctly, but it looks like vs code tries to format the code using the .eslintrc config file.

I searched the docs but didn't find any property that could explicitly state that the decorators should have a line break before the attribute name. Could you please help me? 

In my .eslintrc file I am extending the rules "prettier", "eslint:recommended", "plugin:react/recommended", but I couldn't find any rule to override / configure.

**Input:**
```jsx
@observable attribName;
```

**Output:**
```jsx
@observable
attribName;
```

**Comment by ikatyang** [comment]
Since you mentioned that the CLI worked correctly, this issue should be tracked in [`prettier-vscode`](https://github.com/prettier/prettier-vscode/issues).

(I guess it's caused by local/global Prettier version mismatching.)

**Comment by chrismcv** [comment]
I think this relates to https://github.com/prettier/prettier/issues/4922, and I get same behaviour with cli and vscode on 1.14.2
