### ISSUE TITLE
breakBeforeElse – closing an issue prevents thumbs up

### ISSUE THREAD

**Issue by dalgard** [prettier/prettier#4986]
When you close an issue, I can no longer add a thumbs up to it. Are there any other ways of voting on various features?

Like the poster of #840, it is a deal-breaker for me when `else` statements are put on the same line as the previous close bracket. The argument, in my case, is the same as with most other rules that Prettier is doing right: It gives **better commit diffs**.

I want to be able to add any number of `else if` or `else` statements under each other, with comments and all, without it changing the previous block whatsoever.

This has been added in `prettier-miscellaneous` as a rule named `breakBeforeElse`, but I want to add my vote that it should be native to Prettier. It's just more correct.

**Comment by dalgard** [comment]
I have a strong intuition that this preference wouldn't come up naturally, if coming to the language unbiased by the formatting in older languages or preexisting code – just learning about the logic of each language feature.

It's a weird exemption from other rules that applies only here.

At any rate, the point about each block being stand-alone in the context of a Git diff holds, even if it seems less important to you than in other places 🙂

**Comment by j-f1** [comment]
I guess the difference is that your code snippet first defines the function, then runs the `if` statement, whereas the `if`/`else` construct runs only one of its two alternatives. Also, an `if`/`else` statement is [only one statement](https://tc39.github.io/ecma262/#prod-IfStatement) — the `else` is part of the `if`.

**Comment by dalgard** [comment]
I like both your arguments. I guess that _control structure_ captures it better than statement, though, since several of the ways of writing these conditionals look very much like separate statements – or a mix of several:

```js
if (true) good();
else return "wtf";
```

It seems perfectly obvious that the above two don't belong on the same line. When the _block_ as a structure enters the conversation, my mind looks for the simplest possible rule for inserting it and finds the same rule as with lambas and object literals.

This is not necessarily an argument in itself, but cognitive overhead is important to avoid, especially when it promotes magical thinking, and then, of course, there is the added diff argument.

Semicolon-less example:

```js
const fun = (x) => x ** 1 / pi
const obj = {}

const fun (x) => {
  return "sod off"
}
const obj = {
  key: "val",
}
```

**Comment by j-f1** [comment]
#840 is now unlocked. Please comment there instead.

**Comment by j-f1** [comment]
Duplicate of #840
