### ISSUE TITLE
Prettier doesn't work with stylelint

### ISSUE THREAD

**Issue by Industrial** [prettier/prettier#4988]
**Environments:**
- Prettier Version: 1.14.2
- Running Prettier via: CLI 
- Runtime: v10.1.0 
- Operating System: Linux 

**Steps to reproduce:**

Use the stylelint rule `'color-hex-case': 'upper'`.

**Expected behavior:**
Prettier takes the stylelint configuration and formats the file using these rules.

**Actual behavior:**
Prettier has it's own rules and conflicts with other tools.

I can't find the list of configuration rules for prettier. So I don't know how this rule for formatting hex codes in CSS in prettier is called.

**Comment by evilebottnawi** [comment]
@Industrial `prettier` !== `stylelint`. It is difference tools for difference purpose.

**Comment by Industrial** [comment]
So every time I format with prettier stylelint is giving me errors because prettier did it wrong according to stylelint.

Why can't stylelint be leading in what rules to use?

**Comment by evilebottnawi** [comment]
@Industrial you should disable all stylistics rules in stylelint, because it is hard implement and `stylelint` doesn't respect print width.

**Comment by ikatyang** [comment]
See [`stylelint-config-prettier`](https://github.com/prettier/stylelint-config-prettier) and/or [`prettier-stylelint`](https://github.com/hugomrdias/prettier-stylelint).

**Comment by lydell** [comment]
> Why can't stylelint be leading in what rules to use?

Because you can pick and choose stylelint rules, but you can't pick and choose Prettier formatting. Prettier is more of a "all or nothing" tool.

**Comment by Industrial** [comment]
I have solved this in CI with the `lint-staged` tool by first running prettier and then `eslint --fix` (and then `git add`) on all the staged files and I opened a ticket for my editor (vim) to run multiple tools when prettier should trigger as well. Thanks.
