### ISSUE TITLE
Idea for a CLI

### ISSUE THREAD

**Issue by ameerthehacker** [prettier/prettier#4990]
Hey friends. I always wanted to run prettier on my entire old codebase which were not using prettirt while creating. So I thought of creating a CLI for doing it. I wanted to know whether I can join the prettier team and do this project in the prettier organization.

# I Would love to join the team ❤️

**Comment by suchipi** [comment]
@ameerthehacker Your enthusiasm is very welcome! However, I think what you want to do is already possible. Could you elaborate a bit?

**Comment by ameerthehacker** [comment]
What im trying to say is running

prettier foldername and it would recursively find all files under that folder and prettify it.

**Comment by SimenB** [comment]
`prettier foldername/**/* --write` should do the trick

**Comment by ameerthehacker** [comment]
Cool thanks
