### ISSUE TITLE
YAML: Prettier can't parse its own output

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#4991]
Prettier v1.14.2

I can't report this using the "Report issue" button because the code is too long, and the issue doesn't reproduce with shorter code.

Steps to reproduce:

1. Copy the content of [this file](https://raw.githubusercontent.com/AustinGreen/gatsby-starter-netlify-cms/master/static/admin/config.yml) to [Prettier Playground](https://prettier.io/playground).

2. Copy the result of formatting (Prettier's output).

3. Try to format it again by pasting it into the input pane of the Playground.

4. See this: `SyntaxError: The "undefine...ndefined" key is too long (76:13)`

**Comment by kachkaev** [comment]
[Playground link that include file contents](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjAhmA1ggJkgHSgAJip0BbOJYgcwEsYBaW9eAd3QE8jTUAndFDAALGhXQBnePyJEqueugD6AMwgAbXHH41pbemAD09CrSIAHAK6oNhtZu27iJs3OGaNcMDHrRJhCTETGSU1MQEaBoQ5iC8pMQa6KhwGjSRAELRsfGk6lo66SCS-MYW6LRwkka2MZG5xGD8cGzhMPxWcA2SGla0RcDAXC38AL6jTIMU0DAi45PAuNzzgz194-VBefSpuAENpCHASSlpESAAKnAUFknwxADScDwgADShVEXwN3dwTy-vdj0XCVGBFETA7RQSLvbSqdBWDRg861WhMCwQaSRUYHYLEY7JVJFC6MLwwj7hSK+GBkt7EIEguDIyLSfj0KCxHFbBJHE5E84ABRsdkkImIABFWuTyJ9zkt4OSGaCivKmaYuiAuQkefi+WdIuKqk16BZfNBpWEVUa2aa-NC6UqmV84AAPGDY3G8wn6kAZCC4AEUoqof2Bx3MkASfhYXAQdj2rXavEE07EiqSC2yqnpxXA5XnEXuzXuQ5B87lSoZuLcvVFAUVKqbbWqehefbc0strxFEplBvVZIQKwwExQbQugB0FFwTaTpFr5wAgiHh7O5zLKSBB6vq3Ptrt23udSn+ZErj9Wo9npnN99bq1-rnGRGIbgoeS4QikUVt8wKxrEyPL1U3OEkaQ1d4Ny+UkIPpPMnXOVl2U5XFtWA09fVDG9gywh14IjKMYzjBNPWILtN17Ix-2qCx+H9KwfGqdlxynGddz3BdIgFOjcAYmBJGIetKjXJMoPLHi+KrVCyJ2LRDyPZNOMua573uR86TEqkVN+dTAXw8FIQQD84HhREI1o+ifHRBsPQ7JN0LOMCvEgy1iGpZy4OfPR2mQwC9wcmgAEkJEqFzZVMBs9K84gIsqPy5wC4gAAkWkUDkwvCERUuQqL8yQjl4vs3VvRoQ1JGNW1oAymhtHKm0zSgXKEPy2hCrQ4qQMC2A6OqmLuogJrkQgVAACtvBgd4WwPGgAG0TzOFL0DS2heqypacs8vKfIK955tK60TQa3raoqo7NoQ+A3VGXaFyyKx+FQSRetse7HsGmhC0m2S9lmvbiGCyKy1iuB3pikK4Gujr+SuN1esuibzuReHRgAXVRtrjwXABZdB2V6iQ8cRmhhrGnwvum4g5oXRbltW7L0qJ4gWshv6ytOu1joOyrGsZ5GbpK-7wYARl64GRcZknxvJuTfoXAHQqB8HQeBlmF0XJFevQDXGeZtH+c68GACZRaN0HJbJmSKapgX5ZBxXAfDGgVf1-l1YRsStYRx2me21q9ahs5bYAZhNhsQ4l0apctmXKb+23Q4V73nYDmg3c17Xvd19HpNLP6rmkUxoCUDQnrLeAC+mKBi9L73Pujn7Y4XABFKwIHgXqAEdW-bnXfdVgXF2HEQIH4TWh5H0Gs5zxSBYAMURDRlGB3rVAXpelcZlXp8S7jDA2sTaL3hnvfNhGppj62QJp-fXLW2ne7ZHaU4lLmzrEk76o5h-fJds4BSSKApcD4AJrvpRI9BpDSwbpffk-8hC9XvDzTOfdf40F3mAO2B82QYMnig5+bNP5VTLB-Q6X9kGP1aqg-63wgGuUYNcUB0VCzozRkQN4IAIDc0kMgUA6B+B0XYPWZogDkBbgAG4QGBOwgQmAcAwAAMrlDAMhZA7ROivBAOySQOgYDcQqBIZA8IS4gxACNSQLoMiCGwEyeRYQAAy7I4CGK1tojR5R+DaP4KIrglANDsMPrAAA6sCWYyAAAcAAGNxdFtGBMEBYURtEqg6DEU4jRzQu70GaHo2gBikBGNccUa49BVEdBMZIZCXgW5tycfklxJiYDJGCbgUJSBjYgHaLjOwHIADCEAKB5JAFAaAaSQBWG0RcZI3C6nGPGEAA)

<img width="1916" alt="screen shot 2018-08-19 at 10 04 41" src="https://user-images.githubusercontent.com/608862/44307274-55392e00-a397-11e8-8965-74f6768e51ef.png">

**Comment by azz** [comment]
[More minimal repro](https://prettier.io/playground/#N4Igxg9gdgLgprEAucEA2a5hgS2gZyQB0oBaAAgDMc40ATQk88i4a2hpcgbWDQEMARrS4AJOPzo4oAcwA05KPwC2cLgAsJU2QoDuOOjLgwu+GACdpMgL4K+QkeQAicfGEsAHXNAVLVXOld3HC88KD0DIxNyeAAPGFtye2E0LgBJZX4jAEZfFTVyHEyciMNjLghBACssGAV2ekIeZMcMrLg8-0LijvJ9Muii9sSW1PIAQTQ6xXyufinSqNMLK2sAXRGBFPSegCZOgqGjfb7I8vJKmux6mkauXi3WnoOuI97+pe7hu0exyem-AV5tMPuczJZZOtNg4xm0jABmF5fBGLc6XWo3DhNB4wnbtJFvVGDHrQ7YTKZQjYkEByEAQUIEZCgfjmcwQXQABRZCHwyBA-AAbhADDSQIJzPwwABrYwAZQ8kqsyAsAFcOiBpPg4OYYByJTJMshKPMtbSqvhYgAhCXSuX5AAy0jgRpN6oV5i15j5AE8VGhRR4ITAAOoGGDqZAADgADLTAxAtcGJR4+YHXNqBc7aeY4ABHFU4HN6rKGpDGtCmkBa5Q4ZXmNW0-BWTAARRVEHgLor6pgQlDdHDyH2IAs-BwaCsAGEIMpSyAoNAsyAVVqACpCXll13WaxAA)

**Comment by ikatyang** [comment]
Tracked in eemeli/yaml#36.

**Comment by azz** [comment]
So quick @ikatyang ⚡️

**Comment by j-f1** [comment]
Removing the `{}` around the value in @azz’s repro [causes the error not to be thrown](https://prettier.io/playground/#N4Igxg9gdgLgprEAucEA2a5hgS2gZyQB0oBaAAgDMc40ATQk88i62hpcgbWDQEMARrU4AJOHzo4oAcwA05KHwC2cTgAtxkmfIDuOOtLgxO+GACcp0gL7zeg4eQAicfGAsAHXNHmKVnOi5uOJ54ULr6hsbk8AAeMDbkdkJonACSSnyGAIw+yqrkOBnZ4QZGnBACAFZYMPJs9ITcSQ7pmXC5fgVF7eR6pVGFbQnNKeQAgmi1CnmcfJMlkSbmllYAusP8yWndAEwd+YOGe70RZeQV1dh1NA2cPJst3fuchz19i11Dtg+jE1O++TmU3eZ1MFhkaw29lGrUMAGZnp94Qszhcatd2I17tDtm1Ea8UQNulCtuNJpDViQSCBZCAICECMhQHwzGYIDoAAoshD4ZAgPgANwg+hpIAEZj4YAA1kYAMruSWWZDmACu7RAUnwcDMMA5EukGWQlDmWtplXwMQAQhLpXK8gAZKRwI0m9UKsxasx8gCeyjQovc4JgAHV9DA1MgABwABlpgYgWuDEvcfMDLm1AudtLMcAAjiqcDm9ZlDUhjWhTSAtUocMqzGrafhLJgAIoqiDwF0V9UwQShujh5B7EDmPg4NCWADCECUpZAUGgWZAKq1ABVBLyy66rFYgA).
