### ISSUE TITLE
Keep parameters on separate lines even when one is an object or an array

### ISSUE THREAD

**Issue by angelo-mollame** [prettier/prettier#4996]
There seems to be an inconsistency in the "parameters on separate lines" rule that Prettier seems to follow.
Prettier does put parameters on separate lines, if necessary, if the line is too long.
But if one of the parameters is an object, it keeps the opening bracket of the object on the same line as the other parameter(s).
Would it be possible to be consistent, and always keep the parameters in separate lines in all these cases?

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDXf8GFFKYYBOAllAOaYC8mARsywBQA6U7MYvf-fADSduAE3ETJEgJQBuEVEhQMOImvV4S5KrQYs2IngONhhXGME6ZrNqXZJxHT51ZsBfOQqUqNv4qRhKGnomfUYOc2MzG0wTXjNuSygY6zspB2dM12sPWRBBEAgABxgKdGRQbDIyCAB3AAUqhDRkEGwANwgKUXyQRjJsMABrOBgAZSLBnWRAgFc4Aqo0ODIYeoHqAFtsZAAzbAAbZYKAKzQADwAhAeHRsexNuAAZKjg9w+OQSbJlslaYACeRTgaDAlBKvSKQRgAHVujAABbIAAcAAYClCIMsYQMiq0oSCVu03gUyHAAI6zChk9bYLY7JD7I4LEDLTYUGZkeYFNA6A5wACKswg8HezIKMGwjDhokRyAATBKBhQDjoAMIQTbbVpQaAkkCzZYAFSlLUZHzgbjcQA)
```sh
--parser typescript
```

**Input:**
```tsx
const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(
  ccccccccccccc,
  ddddddddddddd);

const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(
  ccccccccccccc,
  {
    ddddddddddd: eeeeeeeeee
  });

const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(
  cccccc,
  ccccccccc,
  {
    ddddddddddd: eeeeeeeeee
  });
```

**Output:**
```tsx
const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(
  ccccccccccccc,
  ddddddddddddd
);

const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(ccccccccccccc, {
  ddddddddddd: eeeeeeeeee
});

const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(cccccc, ccccccccc, {
  ddddddddddd: eeeeeeeeee
});

```

**Expected behavior:**
```tsx
const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(
  ccccccccccccc,
  ddddddddddddd);

const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(
  ccccccccccccc,
  {
    ddddddddddd: eeeeeeeeee
  });

const aaaaaaaaaaaaaaaaaaaaaaaaaaaa: string = bbbbbb(
  cccccc,
  ccccccccc,
  {
    ddddddddddd: eeeeeeeeee
  });
```

**Comment by lydell** [comment]
Prettier has special-cased this on purpose, since it is a common to have function which take an options object as the last parameter and many people write calls to such functions like Prettier does. This is not going to change, but thanks for the issue!
