### ISSUE TITLE
prettier typescript's type code if too long in a single line would bring error.

### ISSUE THREAD

**Issue by luozt** [prettier/prettier#4998]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKnAZxmwF5sByaOc7AHwpgHcIb7yYALAJzmrooBmEAK5dWggJYA3PmwISAHuPJwJAcw4xlUdZuXwo5ANwAdKCAA0ICBhgToBZKACGXLhEYAFVwkcpnUhASACaWIABGXM5gANZwMADKGNESUGrIMFzCcFapBHBcMJ5RagC2zsgCzgA2+VYAVgQKAEJRsfEJzqVwADKpcJU1dSDJXPlcyKiYhGBcErZhGHOwAOohnMgAHAAMVksQ+StRGJNLhAUyYTwAjsISPMXOZRVIVbU5IPmlEhlZH-JpapwACKwgg8F+2SsMGc4TWwQ2SAATNCohJqqk1ABhCClcqTKBUMLCfK4WF+N75AC+VKAA)
```sh
--parser typescript
--single-quote
```

**Input:**
```tsx
type Test = 'one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'eight' | 'night' | 'ten';

```

**Output:**
```tsx
type Test =
  | 'one'
  | 'two'
  | 'three'
  | 'four'
  | 'five'
  | 'six'
  | 'eight'
  | 'night'
  | 'ten';

```

The Output would make the webpack throw an error. 

Please take a look at the problem!

**Comment by ikatyang** [comment]
I guess you're using an old TS, our [minimum version of TypeScript supported is 2.1.3 as it introduces the ability to have leading `|` for type definitions which prettier outputs](https://prettier.io/docs/en/language-support.html).

**Comment by luozt** [comment]
You are right! I'm suing typescript@1.8.10 . It's time to update TypeScript! Thanks!
