### ISSUE TITLE
Indent related messages are difficult to decipher in code editor

### ISSUE THREAD

**Issue by Slapbox** [prettier/prettier#4999]
I'm interested in using Prettier, but the messages it outputs for indent issues could be improved I think.

Prior to adding Prettier to my project, messages would say something like: `Expected 8 spaces but found 2`

With Prettier the messages appear like: `Replace someFunc with ·······someFunc`

These messages are really quite difficult to decipher without leaning in close to the screen in some cases. Unfortunately Sublime Linter's method of highlighting issues does not immediately make clear what the issue is, which means there's an increased reliance on these messages

![image](https://user-images.githubusercontent.com/6835891/44363778-2a340480-a493-11e8-9aa0-e87e604cce0f.png)

**Comment by lydell** [comment]
Hi! That message comes from [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), not Prettier itself. Please open an issue over there!

On the other hand, I use that plugin myself. The way I read that message at a glance is "Replace `yada yada` with `yada yada` (prettier/prettier)", and all I do is run `eslint --fix` (usually via fix-on-save in my editor (Atom)). So in my opinion it doesn't really matter what the message says. Also, [linter-eslint](https://github.com/AtomLinter/linter-eslint) has the option not to show autofixable lint issues. Perhaps the Sublime Linter could do something similar.

**Comment by Slapbox** [comment]
@lydell thanks very much for the speedy reply. I'll open an issue over there.
