### ISSUE TITLE
Package version: v0.54.0 not found

### ISSUE THREAD

**Issue by diegoolavarria** [prettier/prettier#5001]
**Environments:**
- Prettier Version: 0.55.0
- Operating System: Ubuntu 18.04

I didn't like the current version of prettier, but couldn't revert to the previous version with the command given in the repo.
Alternatively, also couldn't set my own configuration (for example, set single quotes on save). Where and how do I set the .pretierrc file?

Thank you

**Comment by j-f1** [comment]
@diegoolavarria That’s a really old version of Prettier — the current one is 1.14. Which version were you using before?

**Comment by kachkaev** [comment]
I believe the issue is related to prettier-atom, which was upgraded recently:
https://github.com/prettier/prettier-atom

The new README should explain how to configure quotes etc - that’s no longer done via the UI.

**Comment by j-f1** [comment]
@kachkaev is right — this is not a Prettier issue.

**Comment by davidlukerice** [comment]
Related to prettier-atom,
not being able to set config options is a known issue: https://github.com/prettier/prettier-atom/issues/441
In addition, the docs did have the wrong command for downgrading, but they should be updated to work correctly now (you don't need the `v` in `apm install prettier-atom@v0.54.0`).
```
apm install prettier-atom@0.54.0
```
is what you want.

**Comment by diegoolavarria** [comment]
Oh, didn't realize that prettier-atom was different. Thank you!
