### ISSUE TITLE
Formatting Markdown and CSS files using Prettier through ESLint?

### ISSUE THREAD

**Issue by willem-aart** [prettier/prettier#5005]
Currently, I've got Prettier set up through ESLint using the following `.eslintrc.json`:
```js
{
  "extends": ["react-app", "plugin:prettier/recommended"]
}
```
This works fine for linting and formatting JavaScript files. 

However, when I'm trying to run ESLint (and thus Prettier) on Markdown and CSS files, errors like the following occur:

    /Users/willem-aart/Code/foo/bar.md
      1:1  error  Parsing error: Unexpected character '#'
    
    > 1 | ## foobar
        | ^
    
    ✖ 1 problem (1 error, 0 warnings)

It seems that ESLint cannot handle the file. On the other hand, Prettier – when run standalone – handles the file as expected.

Is it possible to format files _other than JavaScript_ using Prettier through ESLint? Or am I better off using Prettier standalone?

I guess Prettier can be applied to a broader range of file formats than ESLint is intended for.

**Comment by j-f1** [comment]
I don’t think it’s possible to use ESLint to lint non-JavaScript files. However, you can use ESLint for JS, then run Prettier directly for other file types.

**Comment by willem-aart** [comment]
@j-f1 That was quick, thanks! Are there any benefits of using Prettier through ESLint for JS, as opposed to using Prettier stand-alone for JS?

**Comment by j-f1** [comment]
One advantage is that you get better editor integration since you can see each error separately. However, [prettylint](https://github.com/ikatyang/prettylint) will do that for all file types. It also depends if you want to have just one lint task that runs on your JS as opposed to several.

**Comment by willem-aart** [comment]
Makes a lot of sense. For now, I will separate the two to keep things simple (as in [R. Hickey's definition of simple](https://www.infoq.com/presentations/Simple-Made-Easy)). Thank you.
