### ISSUE TITLE
How can I ignore some rules?

### ISSUE THREAD

**Issue by if2er** [prettier/prettier#5007]
for example:
```css
border: 1PX solid #ddd;
```

I don't want lowercase the unit - "PX", and don't break my origin code, like this:

```css
/* prettier-ignore */
border: 1PX solid #ddd;
```

**Comment by suchipi** [comment]
`prettier-ignore` is the only way- prettier is not a highly configurable formatter like eslint and etc, so there isn't an option for unit case normalization.

**Comment by lydell** [comment]
You can't, basically. Why would you don't want to lowercase units?

If you feel super strongly about this, there's a workaround: [prettier-stylelint](https://github.com/hugomrdias/prettier-stylelint). It runs first `prettier`, then `stylelint --fix`. By using [unit-case](https://stylelint.io/user-guide/rules/unit-case/) you could make stylelint enforce uppercase units, but from the documentation that rule does not seem to support autofix right now, so you'd probably have to start with making a contribution to stylelint.
