### ISSUE TITLE
Pipe operator with comment problem

### ISSUE THREAD

**Issue by sylvainbaronnet** [prettier/prettier#5009]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKcAeAHCAnGAAgBM4AzAQwFcAbIgYQgFtcNZ1DCB6LwgHwB8hAEZ4KUMAAsAFNjwRsAUQCO0gOQBLAM4AlOBWIBPNQBpClGlrgBKM3gSk8AOQgxJGqAHNrHfkMhQGGAw0r6cYPYU8ADKMHhUwVT2xNFwNHDB+NLAYZyE2noGhia5AL62vtYA3OggJiAKMBrQWsigFHjyAO4ACh0IrSgUAG4QGsR1IKIUYADWcDDR2DMenshxVHD1HlYEPWKeTBTIFlb1AFZamABCYnML0RRMcAAyHnAnFJZbIMt4u8gphRhIYaNBJnIPDAAOrjNzIAAcAAZ6nIIFZoWJsIC5HBdsMPvV7MoqBp7PsKIdjkhTj8rEwNOt4nTVukAIpUVwfGlfM4gGDA2HEeFIABM9TiFA0NFWjCYR0BUGghJAVCsABVgYNaaVSkA)
```sh
--parser babylon
```

**Input:**
```jsx

export default Component
  // |> branch(propEq('isReady', false), renderNothing)
  |> connect(
    createStructuredSelector({
      isReady,
    }),
  );

```

**Output:**
```jsx
export default Component
  |> // |> branch(propEq('isReady', false), renderNothing)
  connect(
    createStructuredSelector({
      isReady
    })
  );

```

**Expected behavior:**
(no change)
```jsx

export default Component
  // |> branch(propEq('isReady', false), renderNothing)
  |> connect(
    createStructuredSelector({
      isReady,
    }),
  );

```

**Comment by j-f1** [comment]
Thanks for opening an issue @sylvainbaronnet! Can you fill out the “expected behavior” section of the issue?

**Comment by sylvainbaronnet** [comment]
Sure, I did it

**Comment by flxwu** [comment]
Hey @j-f1 , I'd love to start contributing to Prettier :) And this sounds like a quite doable task, so I'd like to take on this!
However, it'd be quite cool to have some help from a maintainer here! 😊

**Comment by j-f1** [comment]
@flxwu Welcome to Prettier!

This issue is caused by how we *attach* comments to nodes. In this process, we essentially specify that each comment comes before or after a specific node. This allows us to print them in the correct place. [`src/language-js/comments.js`](https://github.com/prettier/prettier/blob/master/src/language-js/comments.js) is the file where that work happens. Since this comment is on its own line, you’d probably need to add a new condition to the [`handleOwnLineComment`](https://github.com/prettier/prettier/blob/58d34bb8447695f257ca307c8670d43277ddb6e3/src/language-js/comments.js#L11) function.

**Comment by flxwu** [comment]
Thanks! @j-f1 I'll take a look at it.

**Comment by lydell** [comment]
@flxwu One way of doing it is put your code you want to test format in `test.js` and running `./bin/prettier.js test.js`.

**Comment by flxwu** [comment]
Thanks for the hint! @lydell . I now added the additional condition for this operator, but however I am a bit wondering whether 

```javascript
export default Component
  // |> branch(propEq('isReady', false), renderNothing)
  |> connect(
    createStructuredSelector({
      isReady,
    }),
  );
```
should really stay the same as @sylvainbaronnet suggests, because |>, just like Prettier does with any other binary expression, should be appended to `Component`, resulting in:

```
export default Component |>
  // |> branch(propEq('isReady', false), renderNothing)
  connect(
    createStructuredSelector({
      isReady,
    }),
  );
```
after formatting, or not?

**Comment by flxwu** [comment]
And it seems like line 5207 in `printer-estree.js` is causing the observed error:
```
    const lineBeforeOperator = node.operator === "|>";
```
leads to the pipeline operator being put in front of the ownLineComment.

**Comment by flxwu** [comment]
@sylvainbaronnet Yeah it currently doesn't because it doesn't treat `|>` same like the other binary expressions like `*`, `+` etc. although IMHO it should, because

```
export default Component
  // |> branch(propEq('isReady', false), renderNothing)
  * connect(
    createStructuredSelector({
      isReady,
    }),
  );
```

gets formatted to:
```
export default Component *
  // |> branch(propEq('isReady', false), renderNothing)
  connect(
    createStructuredSelector({
      isReady,
    }),
  );
```

I think same should happen with the pipeline operator. cc @j-f1 @lydell

**Comment by j-f1** [comment]
I think it should stay before the second parameter since it’s kind of a control flow operator like `?:`. Also, I’d expect there to be some long chains of `|>`, while that is less likely to happen with `*`, or, given the presence of template expressions, `+`.

**Comment by flxwu** [comment]
right, okay. Going to change that then 👍 @j-f1

**Comment by flxwu** [comment]
On the other hand, bitwise operators like `>>` tend to be chained aswell or not?

**Comment by j-f1** [comment]
> shifting operators like `>>` tend to be chained aswell

I don’t think I’ve ever seen that happen in the wild. Do you have a real-world example of chained shifts in JS?

**Comment by flxwu** [comment]
Well, you're right. Shall I still leave the PR as-now or change it? Also, I somehow cannot get the comment to indent properly, because with 
```js
addTrailingComment(precedingNode, comment);
```
which seems like the single possible solution to keep the comment on the line where it is now, the comment doesn't get indented anymore:
```
export default Component
// |> branch(propEq('isReady', false), renderNothing)
  |> connect(
    createStructuredSelector({
      isReady
    })
  );
```
