### ISSUE TITLE
Error when testing components with mocha

### ISSUE THREAD

**Issue by artemanufrij** [prettier/prettier#5018]
Hey guys, I wrote a vue.js project and added some unit tests by using mocha. but everytime I try to test it mocha throws following error:

``` bash
TypeError: Super expression must either be null or a function
   at /builds/artemanufrij/anufrij-monitor/node_modules/prettier/index.js:32893:5
   at /builds/artemanufrij/anufrij-monitor/node_modules/prettier/index.js:32913:4
```

if I comment line 32893 it works as expected.

you can find my project here:
https://gitlab.com/artemanufrij/anufrij-monitor

currently it's not possible to test the project by using CI/CL

If you need more information, let me know it please...

**Comment by tpraxl** [comment]
seems to be the same here

**Comment by tpraxl** [comment]
Seems that 14.1 broke this. Temporary workaround:

package.json with yarn

```json
"resolutions": {
        "prettier": "1.14.0"
    },
```

This makes yarn use version 1.14.0 of the nested dependency.

Make sure to `rm yarn.lock && rm -r node_modules && yarn` afterwards. If you skip this, you might be left with the old state (as was my experience when I tested this).

In my case, the error was gone by then.

**Comment by artemanufrij** [comment]
@tpraxl doesn't work with `npm`

**Comment by themathmagician** [comment]
how can I solve this, if I use webpack and npm?

**Comment by duailibe** [comment]
Hi!

This error means we're trying to inherit the prototype of "something", but the "something" passed is `undefined`. In your specific case, `global.Date` is `undefined`. One of our dependencies (the TOML parser we use to support .toml config files) subclasses `Date`.

That means that `Date` is not defined in your test environment for some reason. But what I don't understand is why your tests are loading Prettier at all.

**Comment by artemanufrij** [comment]
@duailibe 

I don't load it explicit.
I have no depencies in my package.json (https://gitlab.com/artemanufrij/anufrij-monitor/blob/master/package.json)
Here is my test case: https://gitlab.com/artemanufrij/anufrij-monitor/blob/master/test/MonitorHdd.spec.js

**Comment by artemanufrij** [comment]
If I test it local it works as expected

**Comment by wslyhbb** [comment]
I am also having this issue.
@duailibe - vue-loader depends on prettier, that is why it is getting loaded.

**Comment by bobthemac** [comment]
I am having this issue, I am on a newer version 1.15.2 and for me commenting line 39769 `_inherits(Date, _DateTime);` makes it work.

**Comment by hawkrives** [comment]
@bobthemac Why are you loading prettier in your test suite?

**Comment by duailibe** [comment]
@hawkrives they aren't loading

> vue-loader depends on prettier, that is why it is getting loaded.

**Comment by bobthemac** [comment]
@hawkrives I am not loading it in my test suite vue loads it and thats what i am testing.

**Comment by hawkrives** [comment]
@duailibe, @bobthemac ah, apologies – I missed that/those messages earlier. Understood.

**Comment by iraklisg** [comment]
Hello, do we have any update on this issue? 

The error still occurs using `"mocha": "^6.0.2"`, `"mocha-webpack": "^2.0.0-beta.0"` and `"@vue/test-utils": "^1.0.0-beta.29"`

**Comment by S1019269** [comment]
Will there be a serious solution for this issue in the future? 
For me none of the above workarounds are working properly.

**Comment by evilebottnawi** [comment]
Somebody can provide example of code?

**Comment by Korijn** [comment]
FWIW Just want the maintainers to know that workarounds are being spread throughout the JS community that boil down to pinning prettier to 1.13.*
