### ISSUE TITLE
Markdown lists are unstable

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#5021]
Unstable means that Prettier produces a different result on second run. First run:

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwE4CucAlJsADpSaYC2AJgAaXwAeMAjJQLSbsBMAZkrUeAFgCsANkrM4bPt16DhmMVJmw5MIVB78dIzBOlQGAbkoBfSiAA0ICAAcYqaAGdkoAIZ48EAO4ACj4IHiheAG4QqHR2IABGeF5gANZwMADKjsmoUADmyPhE9rlucHgwgUl5NF7I6F4ANmX2AFZuLABCSanpGV40cAAyuXD1TS0g2XhleMgJXvEAno3QcY54uTAA6jEwABbIABwADPYbEGXbSY7zG3CzEWP2eHAAjgSor1VeNXVIDWacHsZRoqEKhGBIDcuTyjTgAEUCBB4OMgfYYItdnQDsg+BikqhGrCAMIQGi1eZQaDPEAEMoAFUWYUBZUsliAA)
```sh
--parser babylon
```

**Input:**
```jsx
if (true) {
  md`
text1
- 123
  - 456

text2
- 123
  - 456

text3
- 123
  - 456
`;
}

```

**Output:**
```jsx
if (true) {
  md`
text1

- 123
  - 456

text2

- 123
  - 456

text3

- 123
  - 456
  `;
}

```

Notice that lists got a new blank line above them. So far so good. Second run:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwE4CucAlJsADpSaYC2AJgAaXwAeMAjJZQLSbsBMAZkrVeAFgCsANi6w4bfrN4DhVTOOmzWMVTz5CR6zJJlqGAbkoBfSiAA0ICAAcYqaAGdkoAIZ48EAHcABV8ETxRvADcIVDp7EAAjPG8wAGs4GABlJxTUKABzZHwiBzz3ODwYIOT8mm9kdG8AG3KHACt3FgAhZLSMzO8aOAAZPLgG5taQHLxyvGRE7wSATyboeKc8PJgAdViYAAtkAA4ABgdNiHKd5KcFzbg5yPGHPDgARwJUN+rvWvqkI0WnAHOUaKgioQQSB3Hl8k04ABFAgQeATYEOGBLPZ0Q7IfiY5KoJpwgDCEBodQWUGgLxABHKABUluEgeUrFYgA)
```sh
--parser babylon
```

**Input:**
```jsx
if (true) {
  md`
text1

- 123
  - 456

text2

- 123
  - 456

text3

- 123
  - 456
  `;
}

```

**Output:**
```jsx
if (true) {
  md`
text1

- 123
  - 456

text2

- 123
  - 456

text3

- 123

  - 456
  `;
}

```

**Expected behavior:**

We got a another blank line above the last `-456`. Peculiar. Somehow the indentation of the body of the `if` statement is interacting with the markdown. Correct result would be the **Input:** (same as output of the first run).

**Comment by ikatyang** [comment]
FYI, there's a <kbd>show second format</kbd> button in the debug section:

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwE4CucAlJsADpSaYC2AJgAaUC0mAjAEwDMl1rALAFYAbJQYBuSgF8QAGhAQADjFTQAzslABDPHggB3AAo6EGlFoBuEVHTkgARni1gA1nBgBlRc9RQA5sj4RPK+anB4MIZOfjRayOhaADZh8gBWagAeAEJOru4eWjRwADK+cPFJKSDeeGF4yA5a9gCeidB2ini+MADqNjAAFsgAHAAM8p0QYT1Oig2dcHUW5fJ4cACOBKhrUVoxcUgJyXDyYTSogYQnIGq+folwAIoEEPAVx-IwTX10g8gcnycqESdwAwhAaLEGlBoCsQAQwgAVJpmI5hKRSIA)
```sh
--parser babylon
```

**Input:**
```jsx
if (true) {
  md`
- 123
  - 456
`;
}
```

**Output:**
```jsx
if (true) {
  md`
- 123
  - 456
  `;
}

```

**Second Output:**
```jsx
if (true) {
  md`
- 123

  - 456
  `;
}

```
