### ISSUE TITLE
Markdown footnotes formatted incorrectly with long lines

### ISSUE THREAD

**Issue by leebrian** [prettier/prettier#5023]
In markdown, for footnotes that have more characters than the column width, prettier breaks the footnote reference apart into a new line. This makes the footnote not generate properly using kramdown, as the new line after the reference block and colon makes the following text not included in the footnote.

Unfortunately, I don't have a fix contribution for this, but hope you can think about how to correct this behavior. 

This is sort of related to #3787, but this doesn't relate to blocks or codes, only to the too-long lines.

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFnABHASnAcwFcAbAQxgEtoBnLAB3JgDMIAnAWwBosB3dSmHRZ2lApSgU4AEywUsAYQBiABQBCWSnQBGcCQSxEaMrNoCeImJjZYlMuGzIk5BBGEpw6AbQB6ARgBdOShZSFgJIk8sGAhTbEoOejYIADcTbTJjWWgGIm0SQSxmOBkMsABrAG4sX0CAHSgG2oCkLAxsNSI2ODIiEWYsAEESSHQIEh5UCDLIHiVKbrJOGh4yEKwAUQAPRggaSjS6AApB1CUASix0TLlpCHp4WTI4mGe0tn2ciAHAHAI8QlIFGoUBWgFwCORgMCefb5bDyAA8z3Q3WYAF46iB0DAYPQaEgAPT4ijMAC0DkINAAdH4ABzMSkEVL4jEAPixOLxhOJZO6BCptPpjJS+PhRJZlJAXBA9yotGQoCWyV4KiWCBoyBAZBSEEo0klIG0jgqcBgAGV6GR3FACMgYGxIlKJMY2DAVI4CBwyMhmE5jFKAFY0LZqI3lE2msgcOAAGQkcG9vrgUotHwcGs9bHKd14UH1SQkMAA6rqrMgaQAGZPJYyFxz0DVJTwONL67oARyICzgbrIHq9SB9JD9IGMHEotvtSZH+hIcAAikQIPAE0Op69tMXpKWkAAmKV2siUArWhQQDiejVQaDxqVGOCoMjadUDxMAX1fQA)
```sh
--parser markdown
```

**Input:**
```markdown
The eRegulations platform, which originated at CFPB is being used by other Federal agencies [^1] and continues to be improved based on public feedback; [^1]

[^1]: The Bureau of Alcohol, Tobacco, Firearms, and Explosives (ATF) has adopted a beta version of “eRegulations,” accessible at <a href="https://atf-eregs.18f.gov/">https://atf-eregs.18f.gov/</a>.
```

**Output:**
```markdown
The eRegulations platform, which originated at CFPB is being used by other Federal agencies [^1] and continues to be improved based on public feedback; [^1]

[^1]:

  The Bureau of Alcohol, Tobacco, Firearms, and Explosives (ATF) has adopted a beta version of “eRegulations,” accessible at <a href="https://atf-eregs.18f.gov/">https://atf-eregs.18f.gov/</a>.

```

**Expected behavior:**
**Output:**
```markdown
The eRegulations platform, which originated at CFPB is being used by other Federal agencies [^1] and continues to be improved based on public feedback; [^1]

[^1]: The Bureau of Alcohol, Tobacco, Firearms, and Explosives (ATF) has adopted a beta version of “eRegulations,” accessible at <a href="https://atf-eregs.18f.gov/">https://atf-eregs.18f.gov/</a>.

```

**Comment by ikatyang** [comment]
Please note that [kramdown does not follow the CommonMark spec](https://github.com/gettalong/kramdown/issues/404#issuecomment-275213633), but we can inline it in this case since there's only one paragraph and it's not breakable (i.e., `proseWrap` is not set to `always`).
