### ISSUE TITLE
Support new decorators proposal

### ISSUE THREAD

**Issue by yoyo837** [prettier/prettier#5045]
https://github.com/babel/babel-eslint/releases/tag/v9.0.0

**Input:**
```jsx
import React, { PureComponent } from 'react';

import { connect } from 'dva';

export default
@connect(({ list }) => ({
  list,
}))
class Center extends PureComponent {
  render() {
    return <div>123</div>
  }
}

```

**Output:**
```jsx
import React, { PureComponent } from 'react';

import { connect } from 'dva';

@connect(({ list }) => ({
  list,
}))
export default class Center extends PureComponent {
  render() {
    return <div>123</div>;
  }
}

```

**Expected behavior:**
Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.

prettier/prettier-vscode#572

**Comment by lydell** [comment]
Previous discussion: #2630

**Comment by suchipi** [comment]
See also https://github.com/prettier/prettier/issues/4795

**Comment by suchipi** [comment]
Maybe we should preserve input (support either decorators before export or decorators after export, depending on user input), and then change it to be consistent and not respect user input once the spec is standardized?
