### ISSUE TITLE
Safari has issues with unicode characters in unquoted object properties

### ISSUE THREAD

**Issue by imadha** [prettier/prettier#5052]
If an object property has certain unicode characters in it that are unsupported by the browser, it will cause a SyntaxError.

For example, the following object:
```
const obj = {
  ゛: "゛",
  ゜: "゜"
};
```
Will yield

```
SyntaxError: Invalid character '\u309b'
```
in the latest version of Safari (11.1.2 at the time of writing this).

See 
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEMBOBDKNAGzxgEt1MBeTYAHSjpgHJBshmaUzeYBoGnmgHIYOXYT0wMAviB4gIAB3LpkoPDhwQA7gAU1CNMhB4AbhDIATGSABG+MAGs4MAMry8YMlADmyXAFc4WU80OBwYbXwvAFs8ZAAzPCIQ2QArNAAPACE7Rxc8KLgAGU84eMTkkDccEJxDazxrAE8iaCt5HE8YAHULGAALZAAOAAZZdogQrvx5Q3a4GuNS2Rw4AEc-MhWIvGjYpASkwJAQqLJfHADZNE8vIjgART8IeDLD2RgGnvN+5AAmd-wZCINwAwhAojFDFBoEsQH4QgAVBoGfblOCSSRAA)
```sh
--parser babylon
```

**Input:**
```jsx
const translations = {
	'゛': '゛',
	'゜': '゜', 
}
```

**Output:**
```jsx
const translations = {
  ゛: "゛",
  ゜: "゜"
};

```

**Expected behavior:**
Object properties with special characters should probably remain quoted in order to prevent errors in Safari and other browsers that do not support unicode object properties.

**Comment by suchipi** [comment]
Some viable workarounds in the meantime:

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSkigGcYMYcBDZgGw6OiYYAvBmD1aMAOSBshklIMMyQBpxUwDkMchRqUZ6AX3EMBrdlya9+zYaNUBtRQF15ilVAn2NTrct1QDUECUQCCxLJmRQDhwcCAB3AAUohHCUDgA3CEIAE0CQACNOMABrfABlLA4wQigKZHYAVzgg6qYSGHjOCgBbDmQAMw5uVqCAKyYADwAhQpKYUo4uuAAZarh+weGQCpxWnGR8jjyAT25oXNxqmAB1bJgAC2QADgAGINwIVqvOLH3cOF20msgngAI71Qh4Docbq9JADIZNECtLqEOo4RpBJjVCjcOAARXqEHg6wRQRghxuWXuyAATGTOIRuNiAMIQLo9fbUKBAkD1VoAFUOKXhrT0eiAA)
```sh
--parser babylon
```

**Input:**
```jsx
// prettier-ignore
const translations = {
	'゛': '゛',
	'゜': '゜', 
}

const translations = {
	['゛']: '゛',
	['゜']: '゜', 
}

```

**Output:**
```jsx
// prettier-ignore
const translations = {
	'゛': '゛',
	'゜': '゜', 
}

const translations = {
  ["゛"]: "゛",
  ["゜"]: "゜"
};

```

**Comment by bakkot** [comment]
These two `Other_ID_Start` characters, so I'm not too surprised Safari gets them wrong. [Here's](https://bugs.webkit.org/show_bug.cgi?id=159203) the relevant JavaScriptCore bug, I think, and [here's](https://github.com/tc39/test262/blob/f10582ee661c1079f725b27561bdd211cfd953a5/test/language/identifiers/other_id_start.js#L14) the relevant test262 test, which they [xfail](https://github.com/WebKit/webkit/blob/89c28d471fae35f1788a0f857067896a10af8974/JSTests/test262/expectations.yaml#L2923).

There's another example of this case, which is that `゛` is a legal identifier name in general - i.e., `var ゛;` is legal JS. But there's no way prettier can output that in a way Safari will like. (Even `var \u{309c}` gives a SyntaxError.) So at best we could mitigate it in some cases but not others.

I don't think Prettier should special-case these. Another case which came up was reserved words as property names (old browsers reject `({ catch: 0 })`), and the decision there IIRC was to target modern JS. I think that's the right call here too.

([Last time](https://github.com/prettier/prettier/issues/4138#issuecomment-372493782) there was a bug in Safari's parser we said we didn't want to set a precedent that we'd work around browser bugs, though we didn't affirmatively say we would not.)

**Comment by lydell** [comment]
@imadha Has this caused a problem for you in practice, or is it more of a fun quirk you found out about? I doubt this will cause any problems for people 99.99%™ of the time and there are workarounds, so given @bakkot's comment I'd say we close this.
