### ISSUE TITLE
`jsxBracketSameLine` config value does not work

### ISSUE THREAD

**Issue by kylecesmat** [prettier/prettier#5059]
I am attempting to override the default value for `jsxBracketSameLine` as described here: https://prettier.io/docs/en/options.html#jsx-brackets

**Environments:**
- Prettier Version: 1.14.2
- Running Prettier via: CLI & vscode-prettier
- Runtime: v8.11.4
- Operating System: MacOS

**Steps to reproduce:**
my `.prettierrc`:
```
{
  "jsxBracketSameLine": true,
  "singleQuote": true,
  "bracketSpacing": false
}
```

Repro - https://www.dropbox.com/s/0lejghis2ekkjkl/prettier-jsxBracketSameLine-bug.zip?dl=0
- Run `npm install`
- Inspect `src/index.tsx`, notice the unformatted code
- Run `npm format`

**Expected behavior:**
```
return (
  <Orders
    pagination={true}
    filter={this.state.orderState}
    paginationPageSize={7}
    gridAutoHeight={true} />
);
```

**Actual behavior:**
```
return (
  <Orders
    pagination={true}
    filter={this.state.orderState}
    paginationPageSize={7}
    gridAutoHeight={true}
  />
);
```

**Comment by lydell** [comment]
From the docs you linked to (emphasis mine):

> Put the `>` of a multi-line JSX element at the end of the last line instead of being alone on the next line **(does not apply to self closing elements).**

And for elements with children it does work:

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPAjAAgLyYBQA6UmmAPAPIBOAJnJQM5EkkAOAhgOYCWUbMX0bMBiUArnAC+TZgDMuAG3iUhMABZd6AOnow+cTRBp0AyrvhTizdt179oABU5xjXAF5whAdgvNMHSlzUAIKiMBAAEnBcHKowKmKS0gD0AHxEAJQA3EREqABMOPjSFEYM0qycPHwCUPHiPrIKSirqWjp6BqWmeg0VNtUOTi7uXr1+AcGhEVExccIJDSlg6vLUlAikSVS0DGlQWSAANCAQLHZQ9MigbJSUEADujusXyCBsAG4QgUcgAEaUbDAAGs4DBjOwwDwOMgROJjjx6HQYPYARwALZsZAyNjyRHHABW9FQACEAcDQcY2Gi4AAZHhwGEJY7sBh0V6-Ni-ACe8mgPxYAVgAHVAmpkAAOAAMzLuiKFAJYrwFcERlHeDOO6wAjqIuOsUZwMVicXiQIi0VxGXCzVD5HAAIqiCDwY24uDHXS-EXUMVIPIegEKKEAYQgaKNKCg0A1IFEiIAKpzLkhsW6JBIgA)
```sh
--jsx-bracket-same-line
--parser babylon
```

**Input:**
```jsx
x1 = (
  <Orders
    pagination={true}
    filter={this.state.orderState}
    paginationPageSize={7}
    gridAutoHeight={true}
  />
);

x2 = (
  <Orders
    pagination={true}
    filter={this.state.orderState}
    paginationPageSize={7}
    gridAutoHeight={true}
  >children</Orders>
);
```

**Output:**
```jsx
x1 = (
  <Orders
    pagination={true}
    filter={this.state.orderState}
    paginationPageSize={7}
    gridAutoHeight={true}
  />
);

x2 = (
  <Orders
    pagination={true}
    filter={this.state.orderState}
    paginationPageSize={7}
    gridAutoHeight={true}>
    children
  </Orders>
);

```
