### ISSUE TITLE
`it()` calls with a timeout are indented

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#5061]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLGAKA5ACQIZQAmANnAM4AEeMFpeZNAjAAwDWFArrAE55itxCFAGapSlAO7oAFhA41heMaigBzLABoqZAJ5QwFDAEoKAXgB8FYAB0oFCtLjFiEY7YC+WgEwBWZv6MQDRAIAAcYVGgyZFA8bm4ICQAFOIRolDwANwhUQiCQACNefjgYAGVQvhVVZBhuDjhglTI4bhgk3lUAWzxkRWIW4IArMgAPACFigXK8LrgAGRU4PrwBxpBK7hbuZEK8Ap0XKHzQ7hUYAHVcmGlkAA5mYNOIFoveUN3T8lbM5eDuOAARw4qABHTw3V6SH6gxALS6qFq9XWZGqpAAihwIPAVmtgjB9ldCDdkF58bxlGoAMIQLo9XZQaB-EAcFoAFX26RhcHc7iAA)
```sh
--parser babylon
```

**Input:**
```jsx
it('Handles at least 10k untracked files without failing', async () => {
  hello()
}, 25000)
```

**Output:**
```jsx
it(
  "Handles at least 10k untracked files without failing",
  async () => {
    hello();
  },
  25000
);

```

**Expected behavior:**

Same as input?

Encountered in https://github.com/desktop/desktop/pull/5528.

**Comment by suchipi** [comment]
Yeah, we should inline these.
