### ISSUE TITLE
Arrays of objects with matching keys should have matching linebreaks

### ISSUE THREAD

**Issue by thedamon** [prettier/prettier#5068]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBLKAHAVxjUwF5MBtAHSmCgEMBbOJTAcjAICcuEYBBAOZw2AGkwAbegCM4E1gAMAmhG6Z6wpAvEA3ehIItMAJgCsAX1E06TI214xsvZrCEjxU2fMwK3mAJ6qgJgEACaS2ADWcJgwEJgOTizamHoGLABsFla0DMysbIJcEGho-FBQBPoAklCQzGKSMnKKKmr05ZUSOLUQzJiyAGYQvDH0AB5waFq6+oasAMymAAwr5jQAuiCiIBB4jujIoPQ8EADuAArHCGjIIPQ6ENghWyDSXPRgUTAAyngfuIJkDAuIZtrg0HAuDBzu9BIx6MgBvoIdsAFZoMYAIXenzgP1sABlcHBEci4Ns-lwIVxbtIZP4JNAXnguLgYAB1J4wAAWyAAHEsKUUIez3nhbizJpCdCTtrwAI4ERIwjTw0kSFEgCGMbBAkHkrUAiRwACKBAg8HVmpgMk5IR5yGM22B9GwEgBAGFemqUFBoLKQAQIQAVGQ3JBIjVwczmIA)
```sh
--parser babylon
```

**Input:**
```js
const inputs = [
{name: 'currentAge', label: `Your age:`, value: 25},
{name: 'retirementAge', label: `Age you’d like to retire:`, value:65},
{name: 'grossAnnualIncome', label: `Your annual income before taxes:`, value: 35000}
]
```

**Output:**
```js
const inputs = [
  { name: "currentAge", label: `Your age:`, value: 25 },
  { name: "retirementAge", label: `Age you’d like to retire:`, value: 65 },
  {
    name: "grossAnnualIncome",
    label: `Your annual income before taxes:`,
    value: 35000
  }
];

```

**Expected behavior:**
```js
const inputs = [
  { 
    name: 'currentAge', 
    label: `Your age:`, 
    value: 25 
  },
  { 
    name: 'retirementAge', 
    label: `Age you’d like to retire:`, 
    value: 65 
  },
  {
    name: 'grossAnnualIncome',
    label: `Your annual income before taxes:`,
    value: 35000
  },
```

Not totally sure the best way to approach this, but I find the incongruity between this looks obviously incorrect. In an array of matching (or mostly matching) objects, I would argue the line-breaking should match from object to object in order for it to look pretty. This has happened to me a number of times with config/settings and it always looks bad (and makes Diffs and bulk changes very challenging). `prettier-ignore` doesn't work here bc i want consistent quotes and indentation, i just want each object to have the same indentation to make reading it easier. 

I'm not totally sure the best way to determine when to match line-breaking, but I think it's worth discussing as I strongly feel the output above is never desirable. I would like to say in an array of objects, each object should have matching linebreaks, but objects of objects could have an issue. We could target specifically only objects in an array or object with matching keys, but sometimes there are optional keys.

**Comment by kachkaev** [comment]
@thedamon I think you can manually add a new line in the first two objects and they will be formatted as the third item from then on.

**Comment by thedamon** [comment]
@kachkaev ... mind ... blown !!!
👍
