### ISSUE TITLE
rmarkdown semantic difference between single and triple backticks

### ISSUE THREAD

**Issue by haraldschilly** [prettier/prettier#5071]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADATgAgIwGpuoA6UxqZWeBZxxIANCBAA4wCW0AzsqAIbroQA7gAU+CLih4A3CKwAm9EACN0PMAGs4MAMpM1rKAHNkMdAFc4DAxzjoYw1YYC2PZADMeAGxsMAVhwAPACFVDS1tHic4ABkDOHcvHxA9dBt0ZBAXdHU5IShFJnQDGAB1eRgAC2QADgAGBkKIGxLVJgzCuDSpeIZ0OABHM1Y+hx5nVyQPb0sQGydWE3MZjgNDTzgARTMIeATphhgeJTK5SuQAJgPVVk9VgGEIJxcMqGgekDMbABUjiSmbAC+AKAA)
```sh
--parser markdown
```

**Input:**
````markdown
`r 1+1`

```r 1+1```


````

**Output:**
```markdown
`r 1+1`

`r 1+1`

```

**Expected behavior:**

I would expect triple backticks (at least when used inline!) are not converted to be single backtick. The reason is that [RMarkdown](https://rmarkdown.rstudio.com/) processes single and triple backticks differently. The first one uses the processed output verbatim, while the one with triple backticks displays the "raw" processed representation as being visible in the output. See screenshot below (on the left is RMarkdown, on the right hand side is the processed output, which is fed through R's `rmarkdown::render` function).

![screenshot from 2018-09-08 21-03-20](https://user-images.githubusercontent.com/207405/45257717-eace4900-b3aa-11e8-9236-aabf209c6f44.png)

**Comment by j-f1** [comment]
Would it make sense to only preserve the number of backticks for code spans starting with `r` and a space?

**Comment by haraldschilly** [comment]
I'm not an RMarkdown expert, but yes, that would make sense. Other languages like python are supported, but apparently not for inline code.

Also, just by experimenting around, I discovered a workaround: using ``` `` `r 4567 + 1` `` ``` (i.e. two and then one backtick) results in the same output as enclosing the expression in triple backticks. This variation of escaping backticks is preserved by prettier.

So, maybe it's just wrong to use triple backticks in the first place and my ticket is just noise.

**Comment by j-f1** [comment]
Is that workaround good enough or should we still try to fix this?

**Comment by haraldschilly** [comment]
I'm closing the ticket. If this comes up again, or in another context, I'll report it again. At least, mentioning that  workaround here could help others, too.
