### ISSUE TITLE
Premature break in JSX opening tag when template literal is inside it

### ISSUE THREAD

**Issue by vramana** [prettier/prettier#5075]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT5f6RQDOMfCRwCAkvAC2AFTgAPQQF58DDt24AeADIiY4uNLkxVa7gAdqOCQENqATwXtOJteoAKF63ZnyAfMAAGUgDuEPgAYlbYNPgAgugwABYIuGBWuAQi+AAkwAhWAEYkcHTeMAC+-mXqAPTulja2pT7GzmUt3NXNTlxMANwcbVAcGFjpnMRklDT0zKztvAJCOnoG8vhKKt0a2mKSpe1q5vV2Dgcmbh4NTWfOAcGhEVHUsfFJsDipY-iZOXmFxaUKoNnC5apcvIYuiD8MCTJ12n0BiAADQgCCmMZ8ZCgGzUCBBVw2BBYlBWABuEBwdBRIHy1EiAGs4DAAMqmSI4KAAc2QMGo6DgqM5fDg1Bg7isXOsyFQVhIItRACs+LIAEL0sBM1lWCRwbRQOAyuUKkDs6gi6jIWkFWzkKA0o6wChUxLIAAcAAZUeYICKKPTTFbzHALWTDajqHAAI7oHCRiVSqxG+WCkAiiQ4Xn81N8TlcooARXQEHgyZNMAKzrorqQACZUXyrDhhNyAMIQCTSlBQaDhkDoEVSAok2UpsplIA)

**Input:**
```jsx
function HelloWorld() {
    const listItemText = (
      <ListItemText
        primary={
          <PrimaryText>{`Two Factor Authentication is ${enabledText}`}</PrimaryText>
        }
      />
    );
}
```

**Output:**
```jsx
function HelloWorld() {
  const listItemText = (
    <ListItemText
      primary={
        <PrimaryText
        >{`Two Factor Authentication is ${enabledText}`}</PrimaryText>
      }
    />
  );
}
```

**Expected behavior:**

```jsx
function HelloWorld() {
    const listItemText = (
      <ListItemText
        primary={
          <PrimaryText>
            {`Two Factor Authentication is ${enabledText}`}
          </PrimaryText>
        }
      />
    );
}
```

This does not happen for 

```jsx
function HelloWorld() {
    const listItemText = (
      <ListItemText
        primary={
          <PrimaryText>
            {`Two Factor Authentication is ${enabledText}`}
          </PrimaryText>
        }
      />
    );
}
```

**Comment by duailibe** [comment]
Actually it does happen with

```jsx
<JSXTag>{`some template literal`}</JSXTag>
```

if it exceeds printWidth.

**Comment by vramana** [comment]
@duailibe Sorry I fixed the example now. I prematurely submitted it.
