### ISSUE TITLE
HTML with eslint-plugin-vue and prettier

### ISSUE THREAD

**Issue by xMikasa** [prettier/prettier#5076]
So i was just adding prettier to my pc and noticed it doesnt work with html combined with eslint

if i use eslint-plugin-prettier then i get can't find a parser error.
![bi6llyv](https://user-images.githubusercontent.com/6782462/45293949-b7f99180-b51f-11e8-9141-912a93f0c0c8.png)
 
now when i comment out eslint-plugin-prettier and add prettier as plugin it seems to work as u can see in problem dialog
<img width="1199" alt="screen shot 2018-09-10 at 17 36 25" src="https://i.imgur.com/3I8zaKC.png">

**Environments:**
"eslint": "^5.5.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-prettier": "^2.6.2",
    "eslint-plugin-vue": "^5.0.0-beta.3",
    "prettier": "1.14.2"
Steps to reproduce:
have eslint-plugin-vue and eslint-plugin-prettier.
changing it to prettier seems to work.

.eslintrc->module.exports = {
  "env": {
    "es6": true,
    "browser": true
  },
  "extends": [
    "plugin:vue/essential",
    "prettier",
    //"plugin:prettier/recommended",
    "airbnb-base"
  ]
};

**Comment by duailibe** [comment]
I don't fully understand your problem, but Prettier doesn't format HTML yet. Is that what you were expecting?

**Comment by xMikasa** [comment]
no the issue is why would HTML stop working with it enabled if it ignores HTML all together.

**Comment by lydell** [comment]
@xMikasa Do these links help?

- https://github.com/prettier/prettier/issues/4759#issuecomment-401451362 (from that comment and onwards)
- https://github.com/BenoitZugmeyer/eslint-plugin-html/tree/next#htmlfake-file-extension

**Comment by xMikasa** [comment]
eslint-plugin-vue handles html and it is incompatible with html according to 
https://github.com/BenoitZugmeyer/eslint-plugin-html/tree/next#linting-vue-files

**Comment by lydell** [comment]
Ah, sorry, I mixed up eslint-plugin-html and eslint-plugin-html.

Could you make a minimal repo showing your problem, using only the CLI tools (not VSCode), and showing expected and actual console output, please? That would be very helpful! It is not entirely clear what the issue here is.
