### ISSUE TITLE
Prettier Mangles Flow Parameterized Function Calls

### ISSUE THREAD

**Issue by stevemolitor** [prettier/prettier#5079]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVAFnAWzkwF5MAlOAQzBgDowAna+AYWngA8YAeAHRAAbAJYBzXDAGYAPpgEATKowDWAgHwAKASPGSQASgDcIADQgIABxjD0yUEsYQA7gAUlCNMhBUAbhGHypiAARow0ynAwAMoWNMJQosgwjACucGbxaHCMMC5hogRUyABmVIJZZgBWaJwAQmFgEdFURAAy8XAlZRUgsYxZjF7BVMEAnoLQQRaM8TAA6gEwuMgAHAAMZtMQWXNhFl7TcAM+nWbMAI4pwsx5VAVFSKXl6SBZBMJJqS9o8aKCcABFFIQeBdZ5mGAjBbyJbIABMELCwhECXYBEKXig0FOIBSWWwI08j26cAAvqSgA)
```sh
--parser babylon
```

**Input:**
```jsx
const Theme = React.createContext<"light" | "dark">("light");
```

**Output:**
```jsx
const Theme = (React.createContext < "light") | ("dark" > "light");

```

**Expected behavior:**

```jsx
const Theme = React.createContext<"light" | "dark">("light");

```

This example is from the React context documentation [here](https://flow.org/en/docs/react/context).

**Comment by stevemolitor** [comment]
Never mind, forgot the `// @flow` annotation.

**Comment by lydell** [comment]
I had no idea that the Babylon parser looks for `@flow` comments and parses differently based on its presence! /cc @existentialism

**Comment by duailibe** [comment]
🤯
