### ISSUE TITLE
Exceeds print-width (test framework describe/it/etc. Needs docs)

### ISSUE THREAD

**Issue by oskarer** [prettier/prettier#5081]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoByANVzgHcSAaAAiIEp6BeAPnuAB0p770WPIVIBbAIYAHACK4Mk8TDAALACoQACtgiSMdRiw5de-frhikycbAE96AG2gBzevAAeMV8sUDMOApj0GBCicEEwAK4AZlH04vgQEZ4YkTFxCUnh0VF0Jqb8zGycPHz5puIYGNYWeWWmUeIA1nCy8ooqAHRg4vb2cKgA6ubKAKJu4mAw9jZETnAwAMoh88q4UE4AcrhgcBsQVACCTuJrHdhwAI4RmBbA9FTiAF6P4q-0AL5MTLS1ZUwA3L9+J9AaUQbxwVAQLQQDoYLhoBhkKBxNhtFQNKiEEiUOIAG4QXCoaEgfDYCbNRYKMBrJzIGDYa4wtZVbAwLTiJwSZANexVGEAKwwbgAQuSwJSFuJQgAZNZwHk9fkgBTYVnIUnxGyOKEwyR4WBDVAwZTIAAcAAY9doqgNyZINfrMNY8QqYecrrhzhyueJFXy4DCqqJcPTGYGQBhaX0AIoRCDwf3KmDxI0m5AAJhhDJO9lpAGEQtyUFBoG6QBEqqp4jjeVV3u8gA)
```sh
--parser babylon
```

**Input:**
```jsx
describe('View', () => {
  describe('mapDispatchToProps', () => {
    it('Very long text that describes some stuff about stuff about stuff',
      () => {
        assert(
          fakeDispatch.calledWithExactly(getSomethingNiceNowAgain.request({ wazzaaa })),
        );
      });
  });
});

```

**Output:**
```jsx
describe("View", () => {
  describe("mapDispatchToProps", () => {
    it("Very long text that describes some stuff about stuff about stuff", () => {
      assert(
        fakeDispatch.calledWithExactly(
          getSomethingNiceNowAgain.request({ wazzaaa })
        )
      );
    });
  });
});

```

**Expected behavior:**
The arrow function should be on the line under the string.

**Comment by oskarer** [comment]
If I break the string it seems to get somewhat different result, where the arrow function is correct while the string is on one line.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoByANVzgHcSAaAAiIEp6BeAPnuAB0p770WPIVIBbAIYAHACK4Mk8TDAALACoQACtgiSMdRiw5de-frhikycbAE96AG2gBzevAAeMV8sUDMOApj0GBCicEEwAK4AZlH04vgQETAkJqamANT0JBiRMXEJSeHRUfrMbJw8fGmm4hgY1hap1aZR4gDWcLLyiioAdGDi9vZwqADq5soAom7iYDD2NkROcDAAyiEryrhQTgByuGBwuxBUAIJO4tu92HAAjhGYFsD0VOIAXm-iX-QAvkxMtCa1SYAG4gfw-mCqpDeDCoCBaCAdDBcNAMMhQOJsNoqBosQh0ShxAA3CC4VAIkD4bCzDprBRgbZOZAwbAPRHberYGBacROCTIVr2eqIgBWGDcACEaWA6atxKEADLbOCCwYikAKbBc5BU+I2RzwxGSPCwcaoGDKZAADgADMbtPVRjTJLqTZhrMTVYibvdcDdefzxGrhXBEfVRLgWWywyAMEzhgBFCIQeAhjUweLmy3IABMiNZl3sTIAwiEBSgoNBvSAIvVVPFCUL6j8fkA)

```
describe("View", () => {
  describe("mapDispatchToProps", () => {
    it(
      "Very long text that describes some stuff about" + "stuff about stuff",
      () => {
        assert(
          fakeDispatch.calledWithExactly(
            getSomethingNiceNowAgain.request({ wazzaaa })
          )
        );
      }
    );
  });
});
```

**Comment by oskarer** [comment]
Thanks for the answer @lydell ! So if I understand this right that in order to keep a strict max length of 80 characters I need to add a string concatenation [like this](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoByANVzgHcSAaAAiIEp6BeAPnuAB0p770WPIVIBbAIYAHACK4Mk8TDAALACoQACtgiSMdRiw5de-frhikycbAE96AG2gBzevAAeMV8sUDMOApj0GBCicEEwAK4AZlH04vgQETAk9ADU9CQYkTFxCUnh0VF0Jqb8zGycPHylcRgY1hYlNfRR4gDWcLLyiioAdGDi9vZwqADq5soAom7iYDD2NkRNzfROcDAAyiHryrhQTgByuGBwBxBUAIJO4nu92HAAjhGYFsD0VOIAXp-iv-QAvkxaMtSkCQfQmABuZaA6HVWG8BFQXiCfwiciUGgMcpGKr8VHCYgkCQyOQKJRqTTaXT6HGVZbmSzWOyOfauOAeLw+AkBDBBbYFHLxRKeLKFXIiwVFYHVUp04yy0ziOoNJaK0qtDpdcl9AZDEbjGBTGZzBZqlamNabbZGvaHY6nc5XG5QO6PZ5ZIhvD7fX7iAFg9WmQPNKEwsPwiNIkC0EA6GC4aAYZCgcTYbRUDRphDJlDiABuEFwqBjIHw2FmHU2CjAduQMGwz1je3q2BgWnETgkyFa9nqsYAVhg3AAhCtgKsbcShAAyezgPcG-ZACmwreQZfiNlZpckeFg41QRuQAA4AAyxvcQeqjCuSDd7zDWfML2P3J64e4drviRd9uCxvUoi4PWjYASAGB2sMACKEQQPAf7LjA8SHseSAAEyxg2Nz2HaADCITdigUDQK+IARPUqjxLmvb1P8-xAA)?

**Comment by lydell** [comment]
Yes, there are several clever workarounds to meet a strict length limit. The “correct” solution is to ask yourself why you have a strict max length on top of Prettier at all :)

**Comment by lydell** [comment]
The print width is a guideline for Prettier, not a hard limit. Mostly, Prettier stays below it, but there are a few exceptions added by popular demand, such as testing functions and some import statements. There are also some cases where there’s nothing Prettier can do, such as string literals or comments longer than 80 chars. Or if you nest your code 50 levels deep :)
