### ISSUE TITLE
--no-semi got ignored on typescript indexed class property annotation

### ISSUE THREAD

**Issue by arch-mage** [prettier/prettier#5082]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBrAQgVwDNC4AnTAXkwGUBPAWwCMIAbACgHJGiTSOBKADpRIUDDgDyxNHCxU6TVpwjTZA4cLAsAhmjSYASnG0ATMpmDDMmAA6kAlgDdt8TAG08PMgF0kmAsTmAPRBmAA8ALQRmAAWZHBWtg7Orh5ShDIwvphQ+ExkwgC+IAA0IBA2MPboyKDapKQQAO4ACvUIaMgg2o4Q9ialIIyk2mDYstQ2o-ZQAObIMKT4cGUzMqQwLSOz9NrIhNosMmUAVmgAHrgjYxPa9HAAMjNw+4fHIFOk610wtDZwaDADkqgzsMxgAHV+jAYsgABwABjKdggMghIxsXTsALIjheZVIcAAjvh7ISttodnskAcjisQDJ6PZXnSymgZrMWHAAIr4CDwBZLekwbSMKEmGHIABMZUW2nsLA5AGEIPRdl0oNB8SB8DIACqizo0t5wQqFIA)
```sh
--parser typescript
--no-semi
--single-quote
```

**Input:**
```tsx
const kBuffer = Symbol('buffer')
const kOffset = Symbol('offset')

class Reader {
  private [kBuffer]: Buffer // <-- here
  private [kOffset]: number
}
```

**Output:**
```tsx
const kBuffer = Symbol('buffer')
const kOffset = Symbol('offset')

class Reader {
  private [kBuffer]: Buffer; // <-- here
  private [kOffset]: number
}

```

**Expected behavior:**
```tsx
const kBuffer = Symbol('buffer')
const kOffset = Symbol('offset')

class Reader {
  private [kBuffer]: Buffer // <-- here
  private [kOffset]: number
}

```

Without semi colon there, it compiles just fine.

**Comment by j-f1** [comment]
Minimal repro:

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOARugE5I4CCZFADjQJYBu68OA2tQBeAXTIBfEABoQEFjHbRMyULRoQA7gAVaCJSnScI7ACZSQlGujABrODADKLK+ygBzZDBoBXONJeY4GhhNS1cAW3RkADN0VADpACtMAA8AIUsbO3t0MLgAGRc4aNj4kCcaAJpkEBgATxY4TDAOOTM2FxgAdRMYAAtkAA4ABmk2CADOyxZqtkbAziLpGjgARy92ZZD0cMikGLjfEACw9mKD6UwXV1Q4AEUvCHgPb0OYdEpu4z7kACZpT3Q7FQVwAwhAwhFqlBoIsQF4AgAVd56fYBMRiIA)
```sh
--parser typescript
--no-semi
--single-quote
```

**Input:**
```tsx
class Foo {
  bar: A
  private [baz]
}
```

**Output:**
```tsx
class Foo {
  bar: A;
  private [baz]
}

```
