### ISSUE TITLE
"export default async function" wraps function in parenthesis

### ISSUE THREAD

**Issue by roytz** [prettier/prettier#5084]
I know there's already an issue for it - https://github.com/prettier/prettier/issues/700
but it's closed and yet not fixed.
Using the prettier version 1.14.0 - I still get this error (while using flow parser).

**Comment by vjeux** [comment]
I'm very confused, when I closed the other issue, I added a test case where it worked. I don't understand why it's not fixed.

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9SBnATyjD2PKZgEtoWIIAKAJR5gAXwDcAHSggANCAgZO0WslCls2CAHcACuoQqUpAG4QOBWSABG2UmADWcGAGUMdjlADmyGNnJw5D1o4XB1bTwBbUmQySmC5ACtaNAAhWwcnZ1IIuAAZDzgY0jiAkDdsYOxkEGJKbUsMbA8YAHVzGAALZAAOAAY5RohgltsMasa4SuNCuWw4AEdyDjmw0kjopFj4kGCIjh8-UtoPT0o4AEVyCHgikrkYUis2gk7kACZ72w5KE4BhCAiUWqUGgMxA5GCABVHoYtnARCIgA)
```sh
--parser flow
```

**Input:**
```jsx
export default async function foo() {};

```

**Output:**
```jsx
export default (async function foo() {});

```

**Comment by vjeux** [comment]
Looks like the test was disabled: https://github.com/prettier/prettier/blob/master/tests/es6modules/jsfmt.spec.js#L2

**Comment by roytz** [comment]
Thanks @vjeux 
Yeah, I'm adding `// prettier-ignore ` for now... :/
Hope this issue will be resolved soon

**Comment by vjeux** [comment]
Is there a reason you are using the flow parser instead of babylon? Bith of them should have feature parity those days

**Comment by roytz** [comment]
Apparently not good enough of a reason... :)
Used it to be consistent with `create-react-app` that uses this configuration but now I'll remove this configuration so I'll use babylon as default.

**Comment by bakkot** [comment]
@vjeux 
> A fix is about to land on flow.

... Is it? Where?

Also, should we maybe reach out to create-react-app and suggest they change the default config? Babylon tends to be less buggy, I think. (And more responsive to bug reports, though of course flow will get features first.)

**Comment by vjeux** [comment]
It's still internal and accepted, not sure what's blocking for it to land. For reference D9790008 (you can't see it unless you are a facebook employee).

I agree that create-react-app should likely be switched to babylon by default at this point. If you want to drive this, that would be great. As for the features, we're using both babylon and flow everywhere in our internal toolchain so they have to be implemented in both before we can use any feature, so there shouldn't be any delay.
