### ISSUE TITLE
Decorators for member variables should be on the same line

### ISSUE THREAD

**Issue by hyperknot** [prettier/prettier#5088]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAZTmOzAAtKYc49gAdKPPAAQgCNScbADdi-QqyG0GAFXT4AvHgDkKztz6DhYiawC2ccsQDmrZWo28BQ0eMl4A7sQCWMF1BN5lAM2KEhKy1bXQchSTB4ABMASSjvPCgAV0JCIJsde1Z0DGIoKLh4339AqCtsIxSYCmUMuz0AOlpsYgBPAAoASk4gyH0MJOirM3xwuEjCrrYrAF9OGZAAGhAIDHdoUmRQZohHAAVaBE2UYhEIFyilkH4WsABrOBhKXLAPE2QYbCS4ZY9bGD2LRM+mIyD8AR+IAAVqQ0AAhW4PJ7EQwAGQ8cDBJUhuWwtmQ13ErUI0CuGGwHhgAHULjB6MgABwABmW5IgQipLQwBPJRh0mOWFQAjkkXBVAaYQViIcshPoXB8vpDSG9JABFJIQeDSoTLGDiGlROnIABMepaLkIbwAwhB9FKUFBoAKQEkhLJxMdwUIZjMgA)
```sh
--parser babylon
```

**Input:**
```jsx
export class SearchStore {
  @observable searchText = ''
  @observable message = ''
  @observable waiting = false
  @observable selectedId = null
  @observable expanded = false

  results = observable.array()

  @computed
  get selected() {}
}
```

**Output:**
```jsx
export class SearchStore {
  @observable
  searchText = "";
  @observable
  message = "";
  @observable
  waiting = false;
  @observable
  selectedId = null;
  @observable
  expanded = false;

  results = observable.array();

  @computed
  get selected() {}
}

```

**Expected behavior:**
1.14 introduced "all decorators are on separate line" behaviour, which is a good thing when decorating functions. 

However, when used in front of member variables, they should be on the same line. This is an extremely common use case for MobX for example. 1.14 simply makes MobX code unreadable.

**Comment by suchipi** [comment]
See also https://github.com/prettier/prettier/issues/4924, https://github.com/prettier/prettier/issues/2613.

**Comment by lydell** [comment]
Current plan: https://github.com/prettier/prettier/issues/4924#issuecomment-425659254

**Comment by hyperknot** [comment]
That's great news, I really appreciate that this project listens to developers!
