### ISSUE TITLE
JSX gets different indentation levels based on number of boolean conditions

### ISSUE THREAD

**Issue by ThiefMaster** [prettier/prettier#5089]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVOGDCEAtgA7QJYC8mAFAJSaUB8mwAOlJpgE5wwCu3TjQ5cuAHiaixXYGACGMNJgBkKzETibla2tJkSAYhAiYARvO5Nx2bhAA2Dh5gD01l8YhTOBugF99MWAAE34wAGsddREfA0xxT3NLa1snR3tXd09vOP9A8TdpOgBuDj8QABoQCBIYAEt0ZFBLOwB3AAVLBDRkEHkANwg64MqQM255CL4AZRJJuqgAc2QYbn44KoW0OG4YdonFonlkADN5e22qgCs0AA8AIQmpmGn5TQAZBbhT88uQOe4224vQsZgAno4oKMSNwFjAAOrDGAAC2QAA4AAxVGEQbbwiYkXowvA7frfKq8ACO-DqvH28kOxyQZwuGxA2yIdRWazZaAWi3scAAivwIPAfqyqjB5GZEcEUcgACxSiZ1ez8whEI69KDkUb8bbYGU9Zm-OB+PxAA)
```sh
--parser babylon
--tab-width 4
```

**Input:**
```jsx
const TestComponent = () => {
  return (
    <>
      {cats && memes && (
        <Foo bar><Trololol /></Foo>
      )}
      {ducks && (
        <Foo bar><Trololol /></Foo>
      )}
    </>
  );
}
```

**Output:**
```jsx
const TestComponent = () => {
    return (
        <>
            {cats &&
                memes && (
                    <Foo bar>
                        <Trololol />
                    </Foo>
                )}
            {ducks && (
                <Foo bar>
                    <Trololol />
                </Foo>
            )}
        </>
    );
};

```

**Expected behavior:**

Having different levels of indentations based on the number conditionals makes the code harder to read. I'd suggest to wrap only if the line exceeds the line length like it's already the case for normal `if (...)` conditions outside JSX, and maybe when wrapping use a style that does not require an extra indentation level (e.g. using half the tab-width when wrapping conditionals in JSX)

**Comment by ThiefMaster** [comment]
Thanks for fixing this! And ETA for a release containing it?

**Comment by duailibe** [comment]
@ThiefMaster We expect to cut a new release in a week or 2, but this may change
