### ISSUE TITLE
Questionable formatting for chained conditional types in TypeScript

### ISSUE THREAD

**Issue by dfreeman** [prettier/prettier#5090]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAPTBeTaOTASygGcYBDKMOCAM0xgHcJMB+ZgCwCc5iSTAwgBXXqQrVa9JgxIA3Yl3IlcQ8nCVRJlGnUaY4JAObcsXKGUHMEAbgA6UJzACeAB2K4CRI9nhQACbkzGycPPw2IuJ+AcHCisqYqurJWgixCPHGZhaYVlA2AY7OUCAANCAQ7jAk0OTIoFS8vBAsAArNCA0oVAoQJIEVIABGvFRgANYYAMruE2QmyDC8onCVZJq8MO3jJgC2VMgMVKialQBW5NgAQuNTs1T7cAAy1sen5yDzvFvIIG5POQwLwSDVhu5QbAAOqDGDcZAADgADJVIRBNNDxu5-pC4FslMN+ABHUQkfi7KgHI5IE5ndYgTT7EjLVYM1RQEzoACKogg8A+9Mq1BGsMC8OQACZheMSKhFgBhCD7Q7-KBEYaiTQAFSoIx6dM0AF8jUA)
```sh
--parser typescript
```

**Input:**
```tsx
let x = one instanceof two ? three : four instanceof five ? six : seven instanceof eight ? nine : ten;

type x = one extends two ? three : four extends five ? six : seven extends eight ? nine : ten;


```

**Output:**
```tsx
let x =
  one instanceof two
    ? three
    : four instanceof five
      ? six
      : seven instanceof eight
        ? nine
        : ten;

type x = one extends two
  ? three
  : four extends five ? six : seven extends eight ? nine : ten;

```

**Expected behavior:**

I know there's some open discussion in https://github.com/prettier/prettier/issues/737 around exactly how chained ternary expressions should be formatted, but no matter the outcome there, I think I would expect chained conditional types to be formatted the same way.

It seems as though the formatting for chained conditional types prefers to keep as much content on the final line as possible, which ends up giving more visual weight to some branches than others and leading to some weird readability issues. As far as I can tell, chained ternaries don't exhibit this behavior—as soon as the chain is forced to break across lines, the whole thing cascades.

**Comment by lydell** [comment]
Hi! This has already been reported here: https://github.com/prettier/prettier/issues/737#issuecomment-382571176

And there's a WIP PR here: #5039

**Comment by dfreeman** [comment]
Ah, apologies for the dupe @lydell! It wasn't clear to me that that PR was going to bring the behavior for conditional types in line with the behavior for ternary expressions. 👍

**Comment by lydell** [comment]
@suchipi Here's what this issue looks like with your PR. Would handling the conditional type case be in our out of scope for that PR, do you think? Just wondering if we should re-open this. 

**Prettier pr-5039**
[Playground link](https://deploy-preview-5039--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAbOMAEAPTBeTaOTASygGcYBDKMOCAM0xgHcJMB+ZgCwCc5iSTAwgBXXqQrVa9JgxIA3Yl3IlcQ8nCVRJlGnUaY4JAObcsXKGUHMEAbgA6UJzACeAB2K4CRI9nhQACbkzGycPPw2IuJ+AcHCisqYqurJWgixCPHGZhaYVlA2AY7OUCAANCAQ7jAk0OTIoFS8vBAsAArNCA0oVAoQJIEVIABGvFRgANYYAMruE2QmyDC8onCVZJq8MO3jJgC2VMgMVKialQBW5NgAQuNTs1T7cAAy1sen5yDzvFvIIG5POQwLwSDVhu5QbAAOqDGDcZAADgADJVIRBNNDxu5-pC4FslMN+ABHUQkfi7KgHI5IE5ndYgTT7EjLVYM1RQEzoACKogg8A+9Mq1BGsMC8OQACZheMSKhFgBhCD7Q7-KBEYaiTQAFSoIx6dM0AF8jUA)
```sh
--parser typescript
```

**Input:**
```tsx
let x = one instanceof two ? three : four instanceof five ? six : seven instanceof eight ? nine : ten;

type x = one extends two ? three : four extends five ? six : seven extends eight ? nine : ten;


```

**Output:**
```tsx
let x =
  one instanceof two
    ? three
    : four instanceof five
    ? six
    : seven instanceof eight
    ? nine
    : ten;

type x = one extends two
  ? three
  : four extends five ? six : seven extends eight ? nine : ten;

```

**Comment by dfreeman** [comment]
@suchipi Just a friendly ping—totally understand if this is out of scope for #5039, but want to make sure this doesn't get lost if that's the case 🙂

**Comment by suchipi** [comment]
Sorry for the late response, I've been pretty busy. My intention with that PR was to treat conditional types the same way, so I would consider it in-scope.
