### ISSUE TITLE
ESLint + Prettier integration

### ISSUE THREAD

**Issue by hasusozam** [prettier/prettier#5093]
I'm trying to configure ESLint with Prettier in VSCode and that is how it looks like:

`package.json`:

```
{
  "scripts": {
    "start": "nodemon bin/www",
    "lint": "eslint src",
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "src/**/*.js": [
      "eslint --fix src",
      "git add"
    ]
  },
  "devDependencies": {
    "eslint": "^5.5.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-prettier": "^2.6.2",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "nodemon": "^1.18.4",
    "prettier": "^1.14.2"
  }
}
```

`.eslintrc.json`:

```
{
  "extends": ["airbnb-base", "plugin:prettier/recommended"]
}
```

The prettier extension is installed on VSCode, the only thing left was to put this on the settings:

```
{
  "editor.formatOnSave": true,
  "prettier.eslintIntegration": true,
}
```

It worked like a charm, now the thing is that I'm trying to override a few settings like `singleQuote: true` and `semi: false`. I tried to create a `.prettierrc` file like this:

```
{
  "singleQuote": true,
  "semi": false
}
```

It does work in the VsCode, it fix the code from double quotes to single and removes all the semicolons, the problem is that it appears this error:

![image](https://user-images.githubusercontent.com/43224359/45517934-293a7e00-b786-11e8-8671-02d14de84e4f.png)

It's like a conflict between ESLint and Prettier.

I was reading the documentation and I saw that `"plugin:prettier/recommended"` in the `.eslintrc` already adds `"rules": { "prettier/prettier": ["error"] }` so I did like this:

- Removed the `.prettierrc` file
- Added the `"rules": { "prettier/prettier": ["error"] }` as `"rules": { "prettier/prettier": ["error", { "singleQuote": true, "semi": false }] }`

It worked, but now I'm wondering if I'm duplicating anything as the plugin is already adding this, or if `.prettierrc` is better suited for this.

What are your solutions for this?

**Comment by ikatyang** [comment]
[`prettier-eslint`](https://github.com/prettier/prettier-eslint) (`prettier.eslintIntegration` in vscode) can't be used with [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier), you should remove `eslint-plugin-prettier` if you'd like to use `prettier-eslint`.

- `prettier-eslint`: `code` -> `prettier --write` -> `eslint --fix`
- `eslint-plugin-prettier`: run `prettier --write` as an ESLint rule

**Comment by hasusozam** [comment]
It's really confusing. I want to be able to run ESLint and Prettier with the configurations I told you that is semi off and single quotes in vscode, and also support the `lint-staged`. What is the right way to do that?

Thank you very much

**Comment by ikatyang** [comment]
Ah, sorry. I thought you want to use `prettier-eslint` ([`prettier.eslintIntegration`](https://github.com/prettier/prettier-vscode#prettiereslintintegration-default-false---javascript-and-typescript-only)), but it seems you don't need it.

If you'd like to use `editor.formatOnSave` in vscode, you should put your options in `.prettierrc` (`prettier-vscode` does not read options from `.eslintrc`) and `"rules": { "prettier/prettier": ["error"] }` in `.eslintrc` (`eslint-plugin-prettier` loads `.prettierrc` by default), otherwise your current configuration is fine.

**Comment by hasusozam** [comment]
That is the thing, I did create the `.prettierrc` but it's conflicting as I put the image, prettier formats to single quote but at the same time says its an error and that I should use double quotes.

![](https://user-images.githubusercontent.com/43224359/45517934-293a7e00-b786-11e8-8671-02d14de84e4f.png)

**Comment by ikatyang** [comment]
I cannot reproduce the issue.

![gif](https://user-images.githubusercontent.com/8341033/45531621-2c377c00-b823-11e8-8496-00babfecb231.gif)

**Comment by hasusozam** [comment]
Are you sure that the eslint is working? Try to put a `console.log(a == b)` to see if eslint points out automatically the errors for the `console.log` and the `==`. The reason I'm saying this is because I started a empty project and did the same thing but noticed that eslint isn't working. Prettier does indeed work but ESLint doesn't.

**Comment by ikatyang** [comment]
![image](https://user-images.githubusercontent.com/8341033/45532949-8555de80-b828-11e8-8829-ee271b8e9f87.png)

The red lines are coming from the ESLint extension, Prettier extension won't show red lines.

**Comment by hasusozam** [comment]
That is weird, I really don't know what is happening.

**Comment by hasusozam** [comment]
For some (God knows what reason) it works now, I don't know if it's a vscode problem but it seems to be working now.
Thank you very much.
