### ISSUE TITLE
Keep keys quoted in Object for compatibility with google-closure-compiler

### ISSUE THREAD

**Issue by Aqours** [prettier/prettier#5094]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2AB0pNNSYByAQxqU3poBpzKadHLKBOAeygBfANzkQrEBAAOMAJbpkoOgCdVEAO4AFNQjTIQdAG4R5AE0kgcqumADWcGAGUZd+VADmyGKoCucFIeaHCqMNq2ngC2dMgAZnQANiFSeGgAHgBCtg5OznRRcAAyHnDxSSkgbqohqoY4dDgAnonQVjKqHjAA6hYwABbIABwADFIdECHdtjKGHXC1xmVSqnAAjn7yqxF00bFICcmBICFR8j7+x2genolwAIp+EPDlR1Iwjb3mA8gATO+2eSJG4AYQgURihig0GWID8IQAKo0DAcKnBhMIgA)
```sh
# Options (if any):
```

**Input:**
```jsx
const obj = {
  	'a': 'a',
  'b':    999,
};
```

**Output:**
```jsx
const obj = {
  a: "a",
  b: 999
};
```

**Expected behavior:**
```jsx
const obj = {
  "a": "a",
  "b": 999
};
```

**Comment by duailibe** [comment]
Hi! This has been discussed before: #4327

We recommend using wrapping the literals in `[ ]`
