### ISSUE TITLE
Error: unknown type: "TSJSDocNullableType"

### ISSUE THREAD

**Issue by sibelius** [prettier/prettier#5095]
I've got this error using babel 7 and typescript files
```jsx
Error: unknown type: "TSJSDocNullableType"
at printPathNoParens (node_modules/prettier/bin-prettier.js:21788:13)
[error]     at Object.genericPrint$1 [as print] (node_modules/prettier/bin-prettier.js:19544:28)
[error]     at genericPrint (node_modules/prettier/bin-prettier.js:10130:18)
[error]     at node_modules/prettier/bin-prettier.js:10076:16
[error]     at Object.printComments (node_modules/prettier/bin-prettier.js:9838:17)
[error]     at printGenerically (node_modules/prettier/bin-prettier.js:10075:22)
[error]     at node_modules/prettier/bin-prettier.js:23606:34
[error]     at FastPath.each (node_modules/prettier/bin-prettier.js:9977:7)
[error]     at printArrayItems (node_modules/prettier/bin-prettier.js:23604:11)
[error]     at printPathNoParens (node_modules/prettier/bin-prettier.js:21065:70)
```

**Comment by ikatyang** [comment]
Could you fill in the issue template so that we could investigate what's going on here?

**Comment by ikatyang** [comment]
I guess you're writing something like this, which is not a valid TypeScript, though TS can recognize it (`[ts] JSDoc types can only be used inside documentation comments.
`).

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAPJmD8AzjAE4CWUA5gNwgA0IEADjGdIcqAIYkkQDuABR4IOKLgDcIZACb0QAIxJcwAawwBlJioqVkpAK5wGFQnBIxByygFsuyAGZdUZhgCtC2AELK1mrjZwADIUcI7OriDaJGYkyCAwAJ5McIRg5CzyTOSwAOqyMAAWyAAcAAwM2RBmucpM8dmp5hJhDCRwAI4GZO1WXLb2SE4uxiBmNmT6JEYMhLroAIoGEPDhIwwwXAr5MkXIAEwbymSougDCEDZ28VDQrSAGZgAqW2LDZgC+H0A)
```sh
--parser typescript
```

**Input:**
```tsx
let x: ?string;
```

**Output:**
```tsx
Error: unknown type: "TSJSDocNullableType"
    at printPathNoParens (https://prettier.io/lib/standalone.js:14869:13)
    at Object.genericPrint$1 [as print] (https://prettier.io/lib/standalone.js:12625:28)
    at genericPrint (https://prettier.io/lib/standalone.js:10430:18)
    at https://prettier.io/lib/standalone.js:10376:16
    at Object.printComments (https://prettier.io/lib/standalone.js:10138:17)
    at printGenerically (https://prettier.io/lib/standalone.js:10375:22)
    at FastPath.call (https://prettier.io/lib/standalone.js:10249:16)
    at printPathNoParens (https://prettier.io/lib/standalone.js:14135:21)
    at Object.genericPrint$1 [as print] (https://prettier.io/lib/standalone.js:12625:28)
    at genericPrint (https://prettier.io/lib/standalone.js:10430:18)
```

**Comment by sibelius** [comment]
should prettier handle this ?

**Comment by j-f1** [comment]
If it’ll parse, we should probably support it.

**Comment by ikatyang** [comment]
@j-f1 That's not valid in TypeScript and only valid in JSDoc.

**Comment by ikatyang** [comment]
Though we may have to support it if we're going to support formatting JSDoc ([tsdoc](https://github.com/Microsoft/tsdoc)).

**Comment by jonnyarnold** [comment]
Hello :) I stumbled upon this in my own investigation of this error, and can shed a little more light on this.

Typescript 3.0 brought with it [optional tuple types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#optional-elements-in-tuple-types), so I can declare a type like:

```ts
// An array with either 2 or 3 elements. (The `?` is the new bit!)
type PairOrTriple = [string, number, boolean?];

// Valid typings
const pair: PairOrTriple = ["foo", 1];
const triple: PairOrTriple = ["bar", 2, true];
```

It looks like prettier (and Typescript's own compiler, before v3.0) considers the `?` as JSDoc that should be in a comment. However, it's now valid Typescript.

**Comment by itrew** [comment]
Just ran into this one as well. While it is now valid TS, Prettier coughs on it.
```typescript
/**
 * A 2-dimensional position with M values. The x coordinate is at index [0] and the
 * y coordinate is at index [1], and if there is an M value it is at index [2].
 */
export type Position2DWithM = [number, number, number?]; // valid in TS 3.0 but Prettier errors out.
export type Position2DWithM = [number, number, number]; // Prettier now works correctly.
```

**Comment by itrew** [comment]
@ikatyang Aye that'll do it. Thanks bud!

**Comment by Kovensky** [comment]
I encountered this error in a `.d.ts` file that incorrectly had `any?` as a function argument type in it. Perhaps this is also a parser bug?

**Comment by duailibe** [comment]
I don't think we should handle it, just improve the error message in this case.

@ikatyang sounds good? I'll try to come up with something good in a PR

**Comment by Ardeshir81** [comment]
yep! update to 1.14 solved for me

**Comment by evilebottnawi** [comment]
Solved
