### ISSUE TITLE
export * as Loader does not work on prettier for typescript

### ISSUE THREAD

**Issue by sibelius** [prettier/prettier#5097]
export * as Loader from '../modules/loader';

SyntaxError: 'from' expected. (3:10)

Use are using this guide https://medium.com/entria/incremental-migration-to-typescript-on-a-flowtype-codebase-515f6490d92d to migrate to Typescript

does makes sense to support the same syntax on TS?

**Comment by duailibe** [comment]
@sibelius I don't think TypeScript supports it yet https://github.com/Microsoft/TypeScript/issues/4813#issuecomment-356453845 so it's not up to us

@lydell I get a SyntaxError in the playground

**Comment by lydell** [comment]
Huh, now I do too. Cache problems?

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAKjwEMBnPAGQmIBM5s8AzbCAWzwHIA6LgelYg0ArgBs4pXiOp1sHANwgANCAgYYAS2ilkoYthYB3AAp6E2lMQBuEdTSUgARtmJgA1nBgBlDC-VQA5sgw2EJwyn6k9DBGzv6sxMiMxCKRygBWpGgAQs5uHp7ErHAUfnCJyakgPtiR2MggMACeGOJg2Opq9hjtsADqtjAAFsgAHAAMyt0Qkb3OGPXd4vSWZcrYcACOQurrMcRxCUhJKWEgkazqQSGnpH7+YgCKQhDw5SfKMMQO-TRDyABMH2c6hEdwAwmx4vUoNBViAhJEACpfczHSIAX3RQA)
```sh
--parser typescript
```

**Input:**
```tsx
export * as Loader from '../modules/loader';
```

**Output:**
```tsx
SyntaxError: 'from' expected. (1:10)
> 1 | export * as Loader from '../modules/loader';
    |          ^
```

**Comment by sibelius** [comment]
I think everything that works with babel parser should be enable on typescript, as we now can use babel + typescript together

maybe prettier could only use babel to handle both .js and typescript files, this would simplify a lot

**Comment by ikatyang** [comment]
I'm curious. I know it's possible to compile those esnext syntaxes with babel + typescript plugin but they're still errors in TypeScript (`tsc`). If it doesn't work in the `tsc`, what's the reason you want to use TypeScript?

**Comment by sibelius** [comment]
I think Typescript should at least parse properly this, as babel works

it could just fallback everything to `any` until the proposal reaches stage 3

**Comment by ikatyang** [comment]
You should ask TS team for this then, as we use the official TypeScript parser. And I don't think it's worth adding a babel-typescript parser for such invalid use cases.
