### ISSUE TITLE
The full license text is not present in the npm package

### ISSUE THREAD

**Issue by honzajavorek** [prettier/prettier#5113]
The MIT license contains a clause which requires the full text of the license itself to be attached to all copies of the code. Even though the repository has it, the npm package of prettier doesn't contain it:

```sh
$ npm i prettier
+ prettier@1.14.2
added 1 package in 0.737s
$ ls -l ./node_modules/prettier/
total 16448
-rw-r--r--  1 honza  staff     3920 Oct 26  1985 README.md
-rwxr-xr-x  1 honza  staff  1189677 Sep 19 14:10 bin-prettier.js
-rw-r--r--  1 honza  staff  1115121 Oct 26  1985 index.js
-rw-r--r--  1 honza  staff     1455 Sep 19 14:10 package.json
-rw-r--r--  1 honza  staff   191544 Oct 26  1985 parser-babylon.js
-rw-r--r--  1 honza  staff  1397777 Oct 26  1985 parser-flow.js
-rw-r--r--  1 honza  staff   138859 Oct 26  1985 parser-glimmer.js
-rw-r--r--  1 honza  staff    36059 Oct 26  1985 parser-graphql.js
-rw-r--r--  1 honza  staff   159328 Oct 26  1985 parser-markdown.js
-rw-r--r--  1 honza  staff   196754 Oct 26  1985 parser-parse5.js
-rw-r--r--  1 honza  staff   932038 Oct 26  1985 parser-postcss.js
-rw-r--r--  1 honza  staff  2010126 Oct 26  1985 parser-typescript.js
-rw-r--r--  1 honza  staff     4097 Oct 26  1985 parser-vue.js
-rw-r--r--  1 honza  staff   157142 Oct 26  1985 parser-yaml.js
-rw-r--r--  1 honza  staff   731205 Oct 26  1985 standalone.js
-rw-r--r--  1 honza  staff   124577 Oct 26  1985 third-party.js
```

No LICENSE file.

This is very strange to me though, because npm automatically adds the `LICENSE` file to the package before publishing even if it was explicitly ignored in `.npmignore`. It cannot be overruled. I guess the situation is possible only because prettier uses some kind of custom publishing life cycle.

The fact the full license text is missing might be problematic in some legal environments. Effectively, some more defensive company lawyers (like the ones supervising my job) might consider the distributed code as unlicensed, thus fully copyrighted.

If you advise me on what's needed to get the license text bundled, I'm willing to send a PR.

**Comment by ikatyang** [comment]
Sorry, it seems we forgot to copy LICENSE to the bundle.

We'll publish 1.14.3 later.

**Comment by ikatyang** [comment]
https://github.com/prettier/prettier/releases/tag/1.14.3
