### ISSUE TITLE
comments after keyword

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5115]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEB6bmDCEAtkQjADpTkwCGmAvJgIwDcIANCBAA4wCW6ZKBoAnERADuABVEI0yEDQBuEPgBMOIAEYiaYANZwYAZW56+UAObIYIgK5xOFtHBEwpuy0RrIAZjQAbF04AKzQADwAhXQMjYxpSABkLOD9A4JAzERcRBS0aLQBPAOhNbhELGAB1dRgAC2QADgAGTnKIFyrdbgVyuBylVM4ROABHOz4RjxovHyR-IMcQFyI+G3sltAtLALgARTsIeDTFzlotGrV65AAmM90+AO3CEjmQKGghkDsXABUC+TzdJwAC+IKAA)
```sh
--parser babylon
```

**Input:**
```jsx
const // Comment
	a = 1;
```

**Output:**
```jsx
const // Comment
a = 1;

```

**Expected behavior:**

```jsx
const 
    // Comment
    a = 1;
```

Same problem for `let`, `await`, `import`, `export`, `class` and maybe other.

**Comment by duailibe** [comment]
My expectation is a bit different than youts:

```js
const // Comment
  a = 1;
```
