### ISSUE TITLE
Add `allowTemplateLiterals` option to support `singleQuote` option

### ISSUE THREAD

**Issue by npetruzzelli** [prettier/prettier#5120]
Prior to opening this issue I ran the following search without finding a possible duplicate:  
`is:issue singleQuote`

**Environments:**
- Prettier Version: 1.14.2
- Running Prettier via: `eslint@4.19.1` & `eslint-plugin-prettier@2.6.2`
- Runtime: Node `v8.11.2` & npm `6.1.0` (or the ESLint plugin of your choosing for your IDE)
- Operating System: Windows 7 Pro 64-bit

```javascript
// .eslintrc.js
module.exports = {
    "root": true,
    "extends": [
        "standard",
        "prettier",
        "prettier/react",
        "prettier/standard"
    ],
    "plugins": [
        "prettier",
        "react"
    ],
    "rules": {
        "prettier/prettier": [
            "error",
            {
                "bracketSpacing": true,
                "jsxBracketSameLine": true,
                "printWidth": 80,
                "semi": false,

                /* `singleQuote: true`
                * IN PRETTIER IS SIMILAR TO THE ESLINT RULE:
                * `quotes: ["error", "single", { avoidEscape: true, allowTemplateLiterals: true }],`
                */
                "singleQuote": true,
                "tabWidth": 4,
                "trailingComma": "none",
                "useTabs": false
            }
        ]
    }
}
```

```javascript
// code.js
var someStringA = "lorem"
var someStringB = 'ipsum'
var someStringC = `dolor`

var aVariable = 'sit'
var someStringD = `${aVariable} amet`

function someTag(strings /*, expression1, expression2 , expressionN */ ) {
    return strings.map(str => str.toUpperCase()).join('')
}
var someStringE = someTag`consectetur adipiscing elit, sed do eiusmod`

var someStringF = `tempor incididunt ut
labore et dolore`
var someStringG = `tempor incididunt ut\nlabore et dolore`
var someStringH = 'tempor incididunt ut\nlabore et dolore'
```

`someStringA` is invalid, and will throw the expected error.

Use of template literals in `someStringC` and `someStringG` is not required. With ESLint, if we want to avoid unnecessary template literals we could set `allowTemplateLiterals: false` in the options for the `quote` rule. However, this rule gets disabled to avoid conflicts with Prettier's own `singleQuote` option.

For JSX, we can partially get this behaviour when setting [`react/jsx-curly-brace-presence`]( https://github.com/yannickcr/eslint-plugin-react/blob/v7.11.1/docs/rules/jsx-curly-brace-presence.md ) to "never". There is no way to get this behavior with "always" or "ignore" nor for JavaScript that is outside of JSX. This feels like a hack instead of intentional consistency.

Since it is best (or at least common?) practice to disable ESLint's `quote` rule with Prettier, would it be possible to add a separate Prettier option that accomplishes something similar `allowTemplateLiterals`? Would this excessively conflict with Prettier's goal of having as few options as possible? Setting the default value to `true` would be backwards compatible with existing Prettier configurations.

Please keep in mind I am not suggesting that something like `quotes: ["error", "backtick"]` (forcing all your strings to be template literals) be implemented.

See also: <https://github.com/prettier/eslint-config-prettier/tree/v3.0.1#quotes>

**Comment by lydell** [comment]
Hi! Sorry if I'm not understanding you correctly, but are you saying that this piece of documentation (and maybe also the CLI helper tool) needs updating? https://github.com/prettier/eslint-config-prettier#quotes

It sounds like you've discovered a valid use case for the ESLint "quotes" rule when used together with Prettier. If so (and there's nothing needed from Prettier's side), could you move this issue over to [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)?

**Comment by npetruzzelli** [comment]
Hi @lydell , thanks for the quick response!

I just ran a quick test.

```javascript
module.exports = {
    "rules": {
        quotes: ["error", "single", { avoidEscape: true, allowTemplateLiterals: false }],
        "prettier/prettier": ["error", { singleQuote: true }]
    }
}

// OR


module.exports = {
    "rules": {
        quotes: ["error", "double", { avoidEscape: true, allowTemplateLiterals: false }],
        "prettier/prettier": ["error", { singleQuote: false }]
    }
}
```

Will work. The trick is to keep `quotes` in sync with `singleQuote`'s value.

`quotes: ["error", "backtick"]` Will work, regardless of `prettier/prettier`'s setting for `singleQuote`.

My only hesitation at this point is using something in a way that is undocumented. If you are saying the above is intentional and won't disappear in the future, it sounds like all I have to do is open an issue in `eslint-config-prettier`'s repository to have the markdown file updated.

Have I understood you correctly?

**Comment by lydell** [comment]
Moving to https://github.com/prettier/eslint-config-prettier/issues/52
