### ISSUE TITLE
Breaks magic comments for eslint, Flow, &c.

### ISSUE THREAD

**Issue by haggholm** [prettier/prettier#5121]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAJAMQDYQDuOAlgB4CycSGFJAzvSVAOYYAmcAZsyTCdHoYuEAE4YARkXpxRAfgA6USFHowMAfRkwAkgFs9cdiQCG8DAF5J02QDo9TOBgA+z64Rmj7M9iydyMQmZ2IlttfUNjMzhbCWCACiCoEMIASgwacIMjU3gAbhAAGhAIAAd+QWRQE1FRIgAFGoR6ZBATADcIEnYikAlREzAAazgYAGVSweYWZBhRAFc4YuZPGHqBlj0TZC4TPBligCt6MgAhAeHRsZNDABlmOB29g5BJ0U9WiRMJAE8CKF6pVEzBgAHVujAABbIAAcAAZikCIDJQQNSq0gXBPO1HsVRHAAI7zEj49YmTbbJC7fZLEAyPQkWYLWlMVh4OAARXmEHgTxpxRg33B7ChyAATAKBiQ8NMAMIQAyUkBQaC4kDzGQAFW+LSpzzgAF8DUA)

**Input:**
```jsx
// $FlowFixMe: Missing definitions for bowser?
const _setImmediate = bowser.msie || bowser.msedge ? window.setImmediate.bind(window) : setImmediate;
```

**Output:**
```jsx
// $FlowFixMe: Missing definitions for bowser?
const _setImmediate =
  bowser.msie || bowser.msedge
    ? window.setImmediate.bind(window)
    : setImmediate;
```

**Expected behavior:**

Well…I don’t know what the *expected* behaviour would be, exactly; but what happens is that the magic comment, which applies to the next line, no longer applies to the code it was written for (in this case, the property lookups on `bowser`), because the line was chopped down. You can get the same effect with various `eslint-disable`-type directives (`eslint-disable-line`, `eslint-disable-next-line`). Result: Flow (or eslint) now fails.

I don’t know what the proper solution is; perhaps this needs discussion. Possibilities include:

* Issue warnings when reformatting AST nodes following known marker comments
* Refuse to change line numbers when reformatting AST nodes following known marker comments
* For some types of comments, it could possibly be automatically fixed: e.g. an `eslint-disable-line` directive could be replaced by `eslint-disable [rule]`/`eslint-enable [rule]` block comments before and after the AST node
* Do nothing but at least put a warning in the docs!

**Comment by lydell** [comment]
Good points!

I usually move my comment in this situation.

**Comment by suchipi** [comment]
I think we should start with at least a mention in the docs, and then if we want to do further work beyond that, we can add that later

**Comment by kaicataldo** [comment]
I've run into this in my own projects, and what I've done is change all the `eslint-disable-line` and `eslint-disable-next-line` comments to `eslint-disable` and eslint-enable` comments instead, since they can't be broken. Additionally, I was able to disallow using `eslint-disable-line` and `eslint-disable-next-line` comments using [`eslint-plugin-eslint-comments](https://github.com/mysticatea/eslint-plugin-eslint-comments).

To note: this is also an issue with `stylelint-disable-line` comments. I haven't found a plugin that enforces the behavior of `eslint-plugin-eslint-comments` for Stylelint, but I plan to write something that will also enforce this for Stylelint.

**Comment by bardware** [comment]
I noticed that behaviour these days. I have IIFE that have no name and eslint always reports unnamed functions. OK; I set eslint to report that but I want that, just not in that case. I wanted to comment every line like `/* eslint-disable-line func-names */`. That didn't work as prettier breaks the comment. If the comment is placed after the keyword `function` the comment is pushed to a new line.
If the line starts with that comment it stays there.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAZgVymGBLaVASmAAIB6AKlLgGcAbPWAWgBM9aBDAI3rmcZQ4pLDmZROAWzqlK5ADpRSpAE5wYmFUoCMAbkUBfIsUWKqNBkxhsOPPgKbDRYcVJlzSGbLgJRiwRWU1DS1SACZ9KCMTKEUQABoQCAAHfGhaZFBOFRUIAHcABWyEDJROADcIPFYEkG4VTjAAa3UAZWTGpgBzZBgVTDhEgAsYSXoAdSG8eFoOsDhWkum8cumAT2RwWgzEplo4FRgChq7JTmR0Tnp9xIArWgAPACEG5ra3ABlHC6ubkHuHq1unwAIqYCDwH7XQYgDoqfYqTbcHhrejQWrJFRWcbVGBDZAADgADIlMRB9uMGslNpi6AdynBamoAI6YPBqY6cU7nJCXaGJfaSPC9fow2jAuBgiGM3m-GEwHg41h45BhRJ9Th4QRdADCEEkZ02UGgjMSmH2ABUeKU+fsDAYgA

**Comment by lydell** [comment]
@bardware [As mentioned in the docs](https://prettier.io/docs/en/rationale.html#comments) we recommend using eslint-disable-<strong>next</strong>-line:

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAjgZwDYCWsAtACYE4CGARnnMVHAB4zGGOYBmArlGA5QC2uTOlQAdKAAoefGAWhSAlMEmZMAJzgxuGqJgCMAbkkBfJcskgANCAgAHedBzJQlDRogB3AAruELiiUAG4QBKQ2INQalGAA1toAyvaxRADmyDAa3HC2ABYwgngA6nkE8DgpYHCJAeUEweUAnsjgOC62RDhwGjA+MWmClMiclHjdtgBWOEwAQjHxSUJwADJEcCNjEyDTTInpdACK3BDwm+O5ICka3Rqt1DRNeNCR9hpEMMXhMHnIABwABlsbwg3WKMXsrTeuB6wQ2ti0AEduAQtP1KINhkhRhdbN1BARMtlLjgDnBjqcNtitpcYDQvqQfsgAEy2LKUAjsNIAYQggiGrSg0HhIG43QAKjRAjjuqZTEA)
```sh
--parser babylon
```

**Input:**
```jsx
/* eslint-disable-next-line func-names */
(function(){
  return 1;
})()

```

**Output:**
```jsx
/* eslint-disable-next-line func-names */
(function() {
  return 1;
})();

```

**Comment by thorn0** [comment]
It's been documented here: https://prettier.io/docs/en/rationale.html#comments

But it'd be good to add the tips from https://github.com/prettier/prettier/issues/5121#issuecomment-439962729 to that page.
