### ISSUE TITLE
Infer file type for CLI Javascript files

### ISSUE THREAD

**Issue by haggholm** [prettier/prettier#5122]
**Environments:**
- Prettier Version: 1.14.2
- Running Prettier via: CLI
- Runtime: Node.js v10
- Operating System: Linux

**Steps to reproduce:**

```bash
prettier bin/clean
```

where `bin/clean` is a Javascript CLI script.

```js
#!/usr/bin/env node
'use strict';

// Do stuff
```

**Actual behavior:**

```
[error] No parser could be inferred for file: bin/clean
```

**Suggested behavior:**

I’m guessing that Prettier infers file types from file extension. However, CLI scripts often aren’t given any extensions. It might be fairly easy to infer the type by reading the first line of such files and checking if it’s a common hashbang string, e.g. something like

```js
if (/^#![^\s]*\/node(js)?\b/.test(firstLine)) {
  // ... use a JS parser ...
}
```

Alternatively, if this is deemed unsafe, perhaps (somewhat less conveniently) the existing pragma could be augmented to accept an optional parameter indicating file type.

```js
#!/usr/bin/env node
/* @prettier:js */
'use strict';

// Do stuff
```

Not as convenient, *and* requires scanning more of the file than just the hashbang line to infer type, but if the former proposal is unsafe in some edge case I’m not thinking of (sufficiently common not to be relegated to `.prettierignore`), it would at last provide a way to opt in.

**Comment by j-f1** [comment]
IMO this shouldn’t be a CLI-only feature since it could be useful for API users too. (cc @lydell since you added the label)

**Comment by haggholm** [comment]
Created a PR that I think should work for both CLI and API. I don’t know if it’s any good, but if I’m missing a feature I can at least *try* to address it…

There’s no test, but I didn’t see any valid tests for inference to begin with (there are some weird missing-path tests). There are also some ugly swallowed exceptions because I don’t know how to address some of the weird cases exposed by the tests, where a path *is* provided but not to anything that can be opened.
