### ISSUE TITLE
Markdown line wrap not working?

### ISSUE THREAD

**Issue by aarong** [prettier/prettier#5123]
I'm running Prettier on a markdown file that has very long lines. It formats the file correctly except that the long lines are not wrapped.

I tried the following...

`prettier README.md --write`
`prettier README.md --write --print-width 80`

... and the long lines were not broken at the character limit (though the file was otherwise formatted).

My understanding is that lines should be wrapped unless `--no-prose-wrap` is specified.

**Comment by ikatyang** [comment]
[`--prose-wrap` defaults to `preserve`](https://prettier.io/docs/en/options.html#prose-wrap), you have to specify `always` to get it worked. If it's still not working, please provide steps to reproduce.

**Comment by aarong** [comment]
Worked. Thank you so much - apologies for cluttering the issues.

**Comment by j-f1** [comment]
🎉 the `no-response` bot works properly now
