### ISSUE TITLE
command line tool for creating basic config file

### ISSUE THREAD

**Issue by cyphernull** [prettier/prettier#5125]
Hey, I've created a simple tool for creating the basic yaml config file for prettier.

Just follow the command line guide to create the basic but most used config options.

[npm](https://www.npmjs.com/package/create-prettier)

</> with ☺️

**Comment by j-f1** [comment]
Very nice! To support people who use tabs, how about allowing `tabs` or `tab` as an option to `printWidth` then setting `useTabs` to `true` in the config file?

**Comment by j-f1** [comment]
Also, feel free to open a PR to add it to our website!

**Comment by Voyager-One** [comment]
thanks，I'll add some more after the mid-autumn festival.

**Comment by thorn0** [comment]
Closing as non-actionable
