### ISSUE TITLE
Disable spacing of JSX self-closing brackets

### ISSUE THREAD

**Issue by rm-rf-etc** [prettier/prettier#5146]
Is there no option to disable the spacing of self-closing brackets in JSX? This option exists in eslint-plugin-react, but without a matching setting in prettier, I don't see how these two can integrate. I have this in my `.eslintrc`:
```
rules:
  "react/jsx-tag-spacing": ['error', {
    beforeSelfClosing: 'never',
  }]
```
But because I'm also using prettier, I then get errors that I must insert a space before every self-closing JSX bracket (not what I want).

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md  
-> beforeSelfClosing

Sorry for opening an issue on this, but I don't see any mention of such an option, anywhere on the web.

**Comment by lydell** [comment]
Hi! We recommend turning all conflicting ESLint rules off. See:

- https://prettier.io/docs/en/eslint.html#turn-off-eslint-s-formatting-rules
- https://github.com/prettier/eslint-config-prettier
