### ISSUE TITLE
Inlined chunks of css in styled-component template literal gets joined to next line

### ISSUE THREAD

**Issue by scotttrinh** [prettier/prettier#5147]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEa6SgEwEMAnAT0wF5MADAHSk0wDNoYBaNASwC84lMAjACYADgA8A3PWpSoeDMwgRK2GKQA2cfADp8nAG50GmACTAceImQC+9Rk01j+ABkyvCAVxgRZM+iAAaEAgRGE50ZFASYggAdwAFEgQ0ZBBCfQhOfECQACNiQjAAazgYAGURQs4oAHNkGGIPOCDqnGIYeIKagFtCZCZCdRwggCs0MQAhAuLSssJuuAAZarh+weGQSuI21NzCXI1oHJFiapgAdSyYAAtkAA5nIJOIHHOCkVSTuDb9VaDiOAARw8nABnUIPT6SAGQ2aIBw3U49UacK4tU0AEUPBB4GtYUEYPtLvgbsghASCpx1NUagBhCDdXqpKDQP4gDw4AAq+xS0PWcGs1iAA)

**Input:**
```jsx
const secondary = `
  font-size: 12px;
`;
const foo = styled.div`
  ${secondary}
  flex: 0 0 auto;
`;
```

**Output:**
```jsx
const secondary = `
  font-size: 12px;
`;
const foo = styled.div`
  ${secondary} flex: 0 0 auto;
`;
```

**Expected behavior:**
Since a `${}` expression can be anything, don't join subsequent lines to it. It's not likely to ever be the correct thing to do.

**Comment by lydell** [comment]
@onurtemizkan Cool, go for it! :+1:

**Comment by scotttrinh** [comment]
Related:

Since the `${}` expression might include the closing semicolon, I feel like we ought not add the "missing" semicolon. Maybe we can be reasonable sure that users won't include them in variables that appear after property names, but in general, it seems aggressive?

## Reasonable:
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAHArgJ2wBs5MBeTAcnzgCM4wwBDABQOLkoG4AdKSKBkwAzCBHKYMATxIATAHSyAlgDcABn0yZaTMAGsA5vgi4osgLSQiEfEkwASYHkIkAvnzVcQAGhARsMEroyKBM+MYA7ixhCGjIIEwqEEqyPiC0+Lp6cDAAyti6SlAGyDD4uHC+RWhw+DAsmQYAtkzIwkxENb4AVmgAHgBCmfo5uUxNcAAyRXBtHV0gBfg1+PE6tDLQadj4RTAA6ikwABbIABwADL47EDX7mdjxO3ArKrO+NACOuEo0DUzNVpIdqdSogGpNJSlcpgtBFAwkACKuAg8DmoN8MCYtEOshOyAATJjMkoiPCAMIQJoteJQaDvEC4GoAFWxcWB8zgrlcQA)

**Input:**
```jsx
const purple = 'rebeccaPurple';
const foo = styled.div`
  background-color: ${purple}
`;
```

**Output:**
```jsx
const purple = "rebeccaPurple";
const foo = styled.div`
  background-color: ${purple};
`;
```

## Unnecessary:
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAHArgJ2wBs5MBeTAcgCMBDMAawHN8JcoATAWkiInySZ8canDBhaABQLE4AbkpyAOlEhQMmAGYQI5TBgCeJDgDoOASwBuAAxWZMAEmB5CJAL4rrckABoQEbBhzdGRQWnxWAHdJcIQ0ZBBaSwhzDl8Qanx6BjgYAGVsenMoJmQYfFw4P2K0OHwYSSymAFtaZE1aIlq-ACs0AA8AISzGXLzaZrgAGWK4ds7ukEL8WvwEumojaHTsfGKYAHVUmAALZAAOAAY-XYhag6zsBN24Vcs5v2EAR1xzYUbaC02kgOl0qiBas1zGUKuC0MUmCQAIq4CDweZgvwwWjUI4cU7IABMWKy5iICIAwhBmq0ElBoB8QLhagAVHHxEELOBuNxAA)

**Input:**
```jsx
const purple = 'background-color: rebeccaPurple;';
const foo = styled.div`
  ${purple}
`;
```

**Output:**
```jsx
const purple = "background-color: rebeccaPurple;";
const foo = styled.div`
  ${purple};
`;
```

**Comment by lydell** [comment]
I wish styled-components (and other CSS-in-JS solutions) had strict rules about where interpolation can appear, because as you've found, it's really hard to format all cases.

**Comment by scotttrinh** [comment]
@lydell 

Yeah, true, but there-in lies the flexibility, right? 😄 

I couldn't find a way, but is it possible to just turn off parsing of template literal content somewhere?

**Comment by joshjg** [comment]
I'd also be interested in a way to globally disable prettier within template literals.

**Comment by evilebottnawi** [comment]
In theory to avoid this issue we should keep line break if he exists, because it is hard to detect should we add newline or not

**Comment by Kovensky** [comment]
Trying this in master, this is what happens with a small sample of real code:

```tsx
const feedbackCountBlockCss = css`
  display: flex;
  margin: 0 -4px;
`

const FeedbackCountLink = styled.a`
  ${feedbackCountBlockCss}
  text-decoration: none;

  ${FeedbackCount} {
    margin: 0;
  }
`
```

Output:

```tsx
const feedbackCountBlockCss = css`
  display: flex;
  margin: 0 -4px;
`

const FeedbackCountLink = styled.a`
  ${feedbackCountBlockCss}
  text-decoration: none

  ${FeedbackCount} {
    margin: 0;
  }
`
```

Note how prettier has deleted the semicolon after `text-decoration: none` which now turns it into a *selector*.
