### ISSUE TITLE
RFC: Move stylelint-prettier to the prettier organization

### ISSUE THREAD

**Issue by BPScott** [prettier/prettier#5154]
Hi folks, I'm opening this here as I'm not sure where else to ask.

I maintain [stylelint-prettier](https://github.com/BPScott/stylelint-prettier) which exposes prettier changes a within `stylelint`, in the same way that `eslint-plugin-prettier` exposes prettier changes within `eslint`. I've been using this for about two months at work without issue, and I consider it stable and feature-complete (baring one or two possible bugs around processing CSS in custom filetypes).

Given that [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) and [stylelint-config-prettier](https://github.com/prettier/stylelint-config-prettier) are all part of the prettier organization I was wondering if the prettier team would be interested in having stylelint-prettier be housed under the prettier organization too?

**Comment by j-f1** [comment]
It looks like @azz @ikatyang @lipis or @vjeux can invite you to the organization. Once that happens, I’d recommend creating a stylelint team and adding yourself and both stylelint repos to it so people who need access can get it easily.

**Comment by azz** [comment]
Invite sent!

**Comment by vjeux** [comment]
@j-f1 I just added you as an admin :)

**Comment by lipis** [comment]
@BPScott What's your Twitter handle?

**Comment by BPScott** [comment]
@azz: Invite accepted! Thank you.

Transfered! https://github.com/prettier/stylelint-prettier

In doing so I have lost admin access to the repo (the stylelint team I created only has read access and I couldn't see if I could change that in the transfer process). Can one of the org admins please set me as an administrator of that repo, and add the stylelint team as having write access too https://github.com/orgs/prettier/teams/stylelint/repositories

@lipis: I'm [@BPScott on twitter too](https://twitter.com/BPScott)

**Comment by lipis** [comment]
@BPScott I made you an admin of both styling projects!

**Comment by lipis** [comment]
Shall we rename it to `prettier-stylelint` maybe?

**Comment by BPScott** [comment]
No, it's a plugin for stylelint, and [their convention is to name plugins `stylelint-THING`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md). `prettier-stylelint` would be a [tool that runs prettier then stylelint](https://github.com/hugomrdias/prettier-stylelint).

This is consistent with how the eslint tooling is named:

[eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier): A plugin for ESLint (as their conventions say to prefix the package name with eslint-plugin).
[prettier-eslint](https://github.com/prettier/prettier-eslint): A tool that runs `prettier --write` then `eslint --fix` over a file.

**Comment by lipis** [comment]
So I think we can close that issue now.
