### ISSUE TITLE
better print comment between UnaryExpression and argument

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5155]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAQgHoAqeDU4gRgG4QAaECABxgEt1lRsAnXiAHcACnwRpkIbADcI7ACaMQAI17YwAazgwAyi3XsoAc2QxeAVzhNDaOLxjC1RgLbZkAM2wAbW0wBWaAAeAEJqmto62M5wADKGcB7eviD6vLa8ksrYygCeXtBKLLyGMADqCjAAFsgAHAAMTEUQtqVqLJJFcOnSCUy8cACO5uz9jtgubkiePlYgts7sphazaIZGXnAAiuYQ8IkzTDDZ5fJVyABMh2rsXmsAwhDOrpJQ0L0g5rYAKtkSU0lwAC+gKAA)
```sh
--parser babylon
```

**Input:**
```jsx
const a = !/*test*/1;
```

**Output:**
```jsx
const a = !/*test*/ 1;

```

**Expected behavior:**

Maybe
```jsx
const a = !1; /*test*/
```

**Comment by j-f1** [comment]
IMO if someone wants to put a comment there, it’s their choice and it’s ok if it looks a little silly.

**Comment by evilebottnawi** [comment]
@j-f1 hm, maybe you are right, let's listen to what others will say

**Comment by evilebottnawi** [comment]
Let's close issue
