### ISSUE TITLE
Generics formatted with spaces by design?

### ISSUE THREAD

**Issue by kristianmandrup** [prettier/prettier#5162]
My generics type definitions, such as for React `Component` props always inserts spaces around the type/interface definition:

`class Abc extends Component < IAbcProps >`

Is this normal/expected formatting? How can I change this to collapse the spaces?

`class Abc extends Component <IAbcProps>`

**Comment by kristianmandrup** [comment]
I think I need to reinstall my VSC and add the basic extensions one at a time. Must be some extensions and settings conflict issue.

**Comment by aMarCruz** [comment]
This comes from eslint rule `space-infix-ops`
