### ISSUE TITLE
closing bracket position.

### ISSUE THREAD

**Issue by firattale** [prettier/prettier#5169]
hello, I have the latest jsprettier and sublime text 3 and I didnt change any default setting.

But it would be better for me if I can put the closing tag to the nearest attributes. let me show you.

When I use Jsprettier my input code goes like this:

					<input
						type="text"
						className="form-control"
						placeholder="Username"
						/>
But I think the below looks better.

					<input
						type="text"
						className="form-control"
						placeholder="Username"/>
Is there any way to change position of closing tag by default, otherwise I am doing it manually.

Thank a lot.

**Comment by j-f1** [comment]
We don’t have any setting for that. For non-self-closing elements, there’s [`jsxBracketSameLine`](https://prettier.io/docs/en/options.html#jsx-brackets) though.
