### ISSUE TITLE
Compress objects

### ISSUE THREAD

**Issue by danielreichhart** [prettier/prettier#5170]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATAhjXTAXkwG0AdKTTYS66gW2hgAslNyQApXKTgGjr0AKhADWATwjsA7ADoADIKr0AMtGzR2AZjkBOIQF9l1WisbM2HEADE4AIwFDqoydMwA2fSbUatmABY5ACYjHzN6TCZYK04AWVwAJydzTFcpdj05AFYfanUoTSh2bLkZI0oAXQBuShB+EAgABxgAS3RkUCTEiAB3AAUkhDRkEFwANwhW7HqQe0TcMDE4GABlJsXWqABzZBhEgFc4Bq20OESYfoXthlxkADNcABszhoArNAAPACEFpZXVrgGHBVFs4A9nq8QBtEmdEqN7Lh7BIntBZk1ElsYAB1aasZAADiU0J6Z2xCyaowxcDh43BDUScAAjgdWoyrrgbnckI8XscQGcGK09od+WgttsnnAAIoHCDwCF8hoEey47D4pDBZULVpPCUAYQgDFuoyg0HpIAOZ2ESJGPMhcEMhiAA)
```sh
--parser babylon
```

**Input:**
```jsx
const data = [
  {
    month: "Jan",
    Tokyo: 7.0,
    London: 3.9
  },
  {
    month: "Feb",
    Tokyo: 6.9,
    London: 4.2
  },
  {
    month: "Mar",
    Tokyo: 9.5,
    London: 5.7
  }
];

```

**Output:**
```jsx
const data = [
  {
    month: "Jan",
    Tokyo: 7.0,
    London: 3.9
  },
  {
    month: "Feb",
    Tokyo: 6.9,
    London: 4.2
  },
  {
    month: "Mar",
    Tokyo: 9.5,
    London: 5.7
  }
];

```

**Expected behavior:**
```jsx
const data = [
  { month: "Jan", Tokyo: 7.0, London: 3.9 },
  { month: "Feb", Tokyo: 6.9, London: 4 },
  { month: "Mar", Tokyo: 9.5, London: 5 }
];


```

**Comment by lydell** [comment]
If there's a newline anywhere inside an object literal, it will stay multiline even if it would fit in a single line. That's not ideal, but we couldn't find any good heuristic that works better. See:

- https://prettier.io/docs/en/rationale.html#multi-line-objects
- #2068
- #4685
