### ISSUE TITLE
Add an option to respect users' decorator line breaks

### ISSUE THREAD

**Issue by arackaf** [prettier/prettier#5171]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOAAhAEaZwBOAbujanDgJYAmOAvDgAMAbjIVqdRizYco6ALYcBJECtHkqtes1bsc6btwZxs-HCrVkAviAA0ICAAcYnaJmSh0DBhADuABS8EdxR0JggeOxAaBnQwAGs4GABlRzjOKABzZBgGAFc4ewztGH9YzPl0ZAAzdFR6ewArTAAPACFYhKTkhTgAGQy4GrqGkDSGbWRo1gBPVGgoxwYMmAB1HhgAC2QADkF7JYh6VdjHKaWTKSH7YwBHPM5jMvQKqqRa+sKQenlOHPyvpgMpl2ABFPIQeDDT72GCsdbcLbIABMsNinFQwIAwhB5JUplBoNcQHl6AAVVghD70KxWIA)

**Input:**
```jsx
class Foo {
  @observable id = 0;
  @observable name = "";
  @observable address = "";
}
```

**Output:**
```jsx
class Foo {
  @observable
  id = 0;
  @observable
  name = "";
  @observable
  address = "";
}
```

**Expected behavior:**

The recent change to break those decorators onto their own line results in incredibly ugly code, which necessitates adding a new line between them.  So the original 5 lines of code winds up as 

```jsx
class Foo {
  @observable
  id = 0;

  @observable
  name = "";

  @observable
  address = "";
}
```

Across various issues and PR's I'm seeing the same small group of vocal users complaining about the original code as being "ugly," with one user for some reason repeatedly citing screenshots of C# and Java code, as though that were somehow relevant in any way.

The simple reality is that the original code, above, is extremely common in some JS communities, and this change really hurts a lot of us.

> We get a lot of requests for adding options, but Prettier is built on the principle of being opinionated about code formatting. This means we have a very high bar for adding new options.

This seem about as good a time to add an option as any. Will you all accept a PR for an option allowing decorator line breaks to just be left alone?  This way devs would at least have the ability to write 

@observable @required id = 0;

if we wanted, without being forced into a style many of us want to avoid? By all means the option can be off; I'm just requesting the ability to *opt into* old behavior. 

--- 

I've seen this comment 

https://github.com/prettier/prettier/issues/4924#issuecomment-425659254

but that seems to imply Prettier will only accept a solution that forces all decorator fields to have identical line break rules, which seems needlessly constraining.

**Comment by lydell** [comment]
> but that seems to imply Prettier will only accept a solution that forces all decorator fields to have identical line break rules, which seems needlessly constraining.

No, that's not what I meant. All decorator fields will be independent.

**Comment by arackaf** [comment]
Oh I see - sorry!  "all decorators" means all decorators for a field, as opposed to all decorated fields.  My bad :)
