### ISSUE TITLE
I'm trying to use prettier with editorconfig but prettier doesn't respect

### ISSUE THREAD

**Issue by zefexdeveloper** [prettier/prettier#5174]
I have this `.editorconfig` file and it works fine:

```
# http://editorconfig.org

root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
insert_final_newline = false
trim_trailing_whitespace = false
```

If I enable prettier it doesn't respect the `editorconfig` and keeps adding final new line ven for the `.md` files.

How to fix this?

**Comment by lydell** [comment]
Hi!

Prettier ends all files with a single newline, and there's no way to disable that.

Prettier can look at your .editorconfig file to set some Prettier options. But as there's no option to disable the final newline, Prettier can't do anything for `trim_final_newline = false`. According to [the docs](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options), Prettier supports the following EditorConfig properties:


  -  indent_style
  -  indent_size/tab_width
  -  max_line_length

**Comment by zefexdeveloper** [comment]
So in this case my .editorconfig is doing actually nothing? Is it better to remove editorconfig and keep only prettier + eslint?

**Comment by lydell** [comment]
Your editorconfig sets:

```
indent_style = space
indent_size = 2
```

So it does do something for Prettier. And some other things might still be useful to for in your editor. Up to you.

**Comment by zefexdeveloper** [comment]
Does prettier also sets?

````
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by lydell** [comment]
`insert_final_newline = true` – yes, that's how Prettier works.

`trim_trailing_whitespace = true` – that's kind of how Prettier works. There could still be trailing whitespace inside multiline strings, though.

For files that are going to be run through Prettier, settings those two options in editorconfig doesn't gain you anything though.

**Comment by zefexdeveloper** [comment]
So my `.editorconfig` should look like this:

```
# http://editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
```

To imply the end of line and charset of the files, right?
