### ISSUE TITLE
fails to locate config file

### ISSUE THREAD

**Issue by titoBouzout** [prettier/prettier#5175]
For some reason, prettier can't find my config file, The config file is on "C:/.prettierrc"

When I run 
prettier --loglevel=debug --find-config-path "C:/Users/Tito/" # file IS NOT found, 
prettier --loglevel=debug --find-config-path "C:/Users/Lala/" # file IS found

It does not make any sense. https://i.imgur.com/YMFYBnS.png

**Comment by ikatyang** [comment]
We use cosmiconfig to load configs, which [stops at your home directory](https://github.com/davidtheclark/cosmiconfig#stopdir).

**Comment by titoBouzout** [comment]
The documentation in https://prettier.io/docs/en/configuration.html says 

> The configuration file will be resolved starting from the location of the file being formatted, and searching up the file tree until a config file is (or isn't) found.

Also looks like "home directory" has no meaning to prettier, because when the file is in my home directory is not found  https://i.imgur.com/IMO9uAV.png which is why I put the configuration in "C:/" instead of just using my home directory. Because when the path is outside my home directory prettier cant find it. 

I suggest to remove the limitation "stop at home directory"

**Comment by titoBouzout** [comment]
It also will be nice to check if the file is in the home directory when any of the parents does not have the file, so that way we can just keep a config file in our home directory instead of spreading the file in every drive.

**Comment by titoBouzout** [comment]
That has nothing to do with what I am saying.

**Comment by ikatyang** [comment]
I think "stop at home directory" makes sense since we don't want to touch system files, but we may want to load configs from home directory if not found.

**Comment by titoBouzout** [comment]
Just to clarify,

Let's say I have the file in my home directory: 
C:/Users/Tito/.prettierrc

Then, all the following commands will give file NOT FOUND:
prettier --find-config-path "C:/"
prettier --find-config-path "C:/Something/"
prettier --find-config-path "D:/"
prettier --find-config-path "D:/Something/"

Prettier will only find a config file if the directory is in "C:/Users/Tito/", like in:
prettier --find-config-path "C:/Users/Tito/"
prettier --find-config-path "C:/Users/Tito/Something/"

So the only purpose of "home directory" is to stop searching. Because when I put the file in 
C:/.prettierrc
D:/.prettierrc

Then the folling commands will work:
prettier --find-config-path "C:/"
prettier --find-config-path "C:/Something/"
prettier --find-config-path "D:/"
prettier --find-config-path "D:/Something/"

But not this ones because thats my home directory:
prettier --find-config-path "C:/Users/Tito/"
prettier --find-config-path "C:/Users/Tito/Something/"

**Comment by titoBouzout** [comment]
> I think "stop at home directory" makes sense since we don't want to touch system files, 

No, thats up to the system. Prettier should only check if the file exists and is readable, anything else is up to the organization of the system. I could have system files somewhere else and prettier has no reliable way to know that.

> but we may want to load configs from home directory if not found.

That would be good

**Comment by Omzig** [comment]
Does Prettier only find your .prettierrc file in the project folder?

**Comment by titoBouzout** [comment]
on the folder where you run it or on any of the parent directories. But if one of the parents is the home folder, then it will stop searching there....

**Comment by thorn0** [comment]
This is not a bug actually, rather an intentionally unsupported use case. Prettier doesn't support any kind of global configuration. This is to make sure that when a project is copied to another computer, Prettier's behavior stays the same. Otherwise, Prettier wouldn't be able to guarantee that everybody in a team gets the same consistent results.

**Comment by titoBouzout** [comment]
@thorn0 No man, you are wrong, you just didnt understand the issue.

**Comment by titoBouzout** [comment]
@thorn0 you should reopen

**Comment by thorn0** [comment]
Prettier should be configured on the project level. Other scenarios aren't supported. I'll reopen if you can show me how this behavior breaks configuring Prettier on the project level.

**Comment by titoBouzout** [comment]
--find-config-path  if broken on windows it stops on the user directory, I do not care how do you organize your own projects. You want to keep it broken? fine.

**Comment by titoBouzout** [comment]
This page https://prettier.io/docs/en/configuration.html is a blank page for me, but last time I checked said: 

> The configuration file will be resolved starting from the location of the file being formatted, and searching up the file tree until a config file is (or isn't) found.

That statement is not true, so fix this issue, or update the documentation.
