### ISSUE TITLE
Can't add official `plugin-php` to appveyor CI

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5181]
Original issue https://github.com/prettier/plugin-php/pull/695

Looks we have invalid configuration for appveyor org permissions. No button `Add new project`.

/cc @azz

**Comment by ikatyang** [comment]
The `prettier` AppVeyor account is just an account named `prettier`, which is authorized to act on behalf of @prettier-bot. I've added `plugin-php` to AppVeyor, and I'll update the permission later.

**Comment by evilebottnawi** [comment]
@ikatyang thanks!

**Comment by ikatyang** [comment]
I've gave you the admin permission on AppVeyor. If you'd like to give someone the rebuild permission, just move them to the Appveyor Maintainer team.

(The prettier account on AppVeyor is now authorized as the @prettier GitHub org.)

**Comment by evilebottnawi** [comment]
@ikatyang Thanks!

**Comment by ikatyang** [comment]
Ref: https://www.appveyor.com/docs/branches/#white--and-blacklisting

![image](https://user-images.githubusercontent.com/8341033/46413501-ab014400-c753-11e8-8247-78fb2a3482ae.png)

Looks like you disabled it in `.appveyor.yml`.

**Comment by evilebottnawi** [comment]
@ikatyang strange previous config works well with PR, investigate

**Comment by evilebottnawi** [comment]
Strange, same config as in `prettier` for `branches` - works well in prettier, doesn't work in `plugin-php`
