### ISSUE TITLE
Wrong indentation with ternary operator and chained calls with tabs-witdh 4

### ISSUE THREAD

**Issue by Niklv** [prettier/prettier#5187]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAzgeQNYAID8u6EAtnABQAmAhjNQJQB0JArgDYyrlNupQX1cSXNSgQYACzgAnbgG4QAGhAQADp2jpkoatOkQA7gAVdCLSmoA3CKkpKQAI2nUw2ODADKql3wDmyGGkWOGU+dBkYI2dfEmpkADNqNnDlACt0AA8AIWdXdw9qMgAZPjgEpJSQb2lw6WRHagcATzZoe1VpPhgAdVtJZAAOAAZlDohw7udVeo64Wssy5Wk4AEcWVGWo6hi4pETkkJBwklQAoMP0PzY4AEUWcTK9isO6B17KfqQAFmVA6lReFBfABhUixepifj2FjhAAqjXM+3CAF9kUA)
```sh
--parser babylon
--tab-width 4
```

**Input:**
```jsx
isOk ? some(data).multi().line() : another();
```

**Output:**
```jsx
isOk
    ? some(data)
          .multi()
          .line()
    : another();

```

**Expected behavior:**
```jsx
isOk
    ? some(data)
            .multi()
            .line()
    : another();

```

I think there are must be 12 spaces on 3 and 4 lines.

**Comment by j-f1** [comment]
We indent anything inside a ternary by 2 spaces so it lines up with the `?` and `:` lines. It’s unlikely we’ll change this.

**Comment by svpace** [comment]
linking #5184
