### ISSUE TITLE
potential comment issue with try finally

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5192]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACSBbbCYYCMAOrAE4CeGwpGdG6WEu+GATKQL6mM56wYAzKQBmASygBDADbSqvZvwIAWUjSj0GmPqwCsXEABoQEAA4wx0AM7JQksmQgB3AAr2ENlJIBuEMQBMjEAAjMkkwAGs4GABlU3CJAHNkGDIAVzhjCSs4MhgXMMTsSWQRGRzjACsrAA8AITDI6JjJPAAZCThS8syQeLIcsmQQyWCKaWgg0zIJGAB1AJgAC2QADgAGY2mIHLmw02HpuEHvLuMyOABHNLELgskikqQy6QqQHOwxFPTeqyTpOAARTSEHg3VevRgowW-mWyDYxlSkjE0iSAGFFE8QFBoGcQGkcgAVUaeF45TicIA)
```sh
--parser babylon
```

**Input:**
```jsx
// comment 1
try {
    // comment 2
}
// comment 3
finally // comment 4
{
    // comment 5
}
```

**Output:**
```jsx
// comment 1
try {
  // comment 2
} finally { // comment 4
  // comment 3
  // comment 5
}

```

**Expected behavior:**

```jsx
// comment 1
try {
    // comment 2
} finally {
    // comment 3
    // comment 4
    // comment 5
}
```

Looks we need add `handleTryStatementComments` to `handleOwnLineComment`.

**Comment by j-f1** [comment]
@evilebottnawi FYI the JSX tag is only for JSX-specific issues — it doesn’t need to be applied for issues with regular JS.

**Comment by aquibm** [comment]
Hey @j-f1, I've implemented @evilebottnawi's suggested fix for this. Would you expect the same behavior for try & catch clauses as well?

Here's what we produce if we add `handleTryStatementComments` to `handleOwnLineComment`

**Input:**
```javascript
// Comment 1
try { // Comment 2
  // Comment 3
  const x = 0;
}
// Comment 4
catch(e) { // Comment 5
  // Comment 6
  throw e;
  // Comment 7
}
// Comment 8
finally { // Comment 9
  // Comment 10
}
// Comment 11
```

**Output:**
```javascript
// Comment 1
try {
  // Comment 2
  // Comment 3
  const x = 0;
} catch (e) {
  // Comment 4
  // Comment 5
  // Comment 6
  throw e;
  // Comment 7
} finally {
  // Comment 8
  // Comment 9
  // Comment 10
}
// Comment 11
```

**Comment by evilebottnawi** [comment]
@aquibm Looks good, PR welcome
