### ISSUE TITLE
Convert block body arrow function to concise body if only return is present

### ISSUE THREAD

**Issue by rolfvandekrol** [prettier/prettier#5195]
If a arrow function with a block body only has a single return statement, it can easily be converted to a arrow function with a concise body. I think prettier should do that. 

I'm not sure the terminology 'block body' and 'concise body' are common. I got them from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Function_body

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAD3wD5NhMAnOGAV0qiMwF8QAaECABxgEt1kobJUoQA7gAVhCNMhDYAbhF4ATdiABGlbGADWNAMpcdvKAHNkMSrTgdTaOJRgTtZgLbZkAM2wAbBxwAVmiEAELaeobYbnAAMqZw3n4BIMaUDpRyGtgaAJ6+0OpclKYwAOqqMAAWyAAcAAwcxRAOZdpccsVwGQqJHNQAjrS81C7Y7p5IPv62IA5uvJbWs2imZr5wAIq0EPBJMxwwORUq1cgATIfavL5rAMIQbh5yUNB9ILQOACo5slPJcGYzCAA)
```sh
--parser babylon
```

**Input:**
```jsx
const a = x => { return x }
```

**Output:**
```jsx
const a = x => {
  return x;
};

```

**Expected behavior:**
```jsx
const a = x => x;

```

**Comment by lydell** [comment]
Hi! This is something we decided not to do – see [What Prettier is not concerned about](https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about).

You can use the [arrow-body-style](https://eslint.org/docs/rules/arrow-body-style) ESLint rule instead. It supports autofix.

**Comment by rolfvandekrol** [comment]
Ah, that's something I missed. Sorry :)
