### ISSUE TITLE
Converts $$latex block$$  to $latex inline$

### ISSUE THREAD

**Issue by nialltc** [prettier/prettier#5199]
**Prettier pr-5050**
[Playground link](https://deploy-preview-5050--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEASVAdDAZAhgFTgA0ACAIwBsIwBrdEAGhAgAcYBLaAZ2VFwCd+EAO4AFAQh4pcANwjsAJoxBl+uWnBgBlFuvZQA5shj8ArnCb6ucfjFFqDAW1zIAZrgrWmAKy4APACE1DW1cRzhsfTg3Dy8QXX5rfmQQZ34aBREoZRZ+fRgAdUUYAAtkAA4ABiZciGsCtRYU3LgkmWimfjgAR1N2LvtcJxckd08LEGtHdmMzCa59Awo4AEVTCHgY8aYYXDIihVLkACYdtXYKRYBhCEdnFKhoDpBTa3w9qTG43C4YLbjMmB-hMIKYYCwwcdgQBfaFAA)
```sh
--parser markdown
```

**Input:**
```markdown
$$\LaTeX block$$
```

**Output:**
```markdown
$\LaTeX block$

```

**Expected behavior:**
$$\LaTeX block$$

Thank you for your very quick reply yesterday and apologies for the duplicate..
Prettier pr-5050 treats latex in markdown much better but it converts double $ to single making a latex block in markdown into latex inline.  Obviously its a pre release, just bringing it to your attention.
Much thanks

**Comment by ikatyang** [comment]
We use [`remark-math`](https://github.com/Rokt33r/remark-math) to parse it, which [treats it as inline math](https://github.com/Rokt33r/remark-math#double-dollars-in-inline):

> Some TeX packages and Markdown processors use double dollars, `$$`, as a inline token. Remark Math will parse it also properly.

I'm not familiar with tex/latex so I'm not sure what should we do here, but the current output looks better to me since it's consistent with the code syntax:

````md
`inline code`
``inline code``

```
block code
```
````

```md
$inline math$
$$inline math$$

$$
block math
$$
```

**Comment by nialltc** [comment]
I see your reasoning. It is all very messy because there's alot of variation depending on what you parse with.
If using Pandoc to go from markdown with math it will treat it like 
```
$inline math$
$$block math$$
```
[pandoc math dollars](https://pandoc.org/MANUAL.html#extension-tex_math_dollars)
So depending on what is how it is being parsed, `$$math$$` could be intended to be inline or block. I would suggest not altering it at all because it can have an unwanted effect.
I am not an expert in any way with md or latex, its just a tool I use and only know what I need to know.
