### ISSUE TITLE
fakeAsync lines are not breaking when width bigger than Print Width

### ISSUE THREAD

**Issue by tspmelo** [prettier/prettier#5201]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVBLGAKAOlddAcgGcALCAVwBsATVAJ0oIAcISYAFBiMOEkqgCGUeiRbUsqGGTioARgzhDaYJgFt5ggO6yCUIQDcMAcyEwMUE9IioKHEkQA0+QqgBmQgNZwAgiQBPKDBsbABKVABeAD5UYFc3VDgADxY4MBwARjCAOhgIAFEAR0ohamxsgG4E9ABfMISwypAnEAgWC2gSZFAhBh5tTj6EbpQjCAxaFpBFITAfGABlFjnLE2QYJjhWyxI4Bi4GIRN1IWRPaj3WgCsSZIAhI-m4JaF1OAAZSzhzsquQFYMPYMZAzITyALUaDTFgMSwwADqkxkyAAHAAGVqw9hwBFHFig2H8faGH6tJQlDBKbjHU6-S7bEB7dQYDZbVokNbUOAARUoEHg9P+MHBSNoKKQACZWpshBhJFYAMIQdR0lBQaBkkCUPYAFXBowue1qtSAA)
```sh
--parser babylon
```

**Input:**
```jsx
  it(
    'should run postProcess and split the breadcrumbs when navigating to hosts',
    fakeAsync(() => {
      expect(1).toEqual(1);
    })
  );
```

**Output:**
```jsx
it("should run postProcess and split the breadcrumbs when navigating to hosts", fakeAsync(() => {
  expect(1).toEqual(1);
}));

```

**Expected behavior:**
1st line is longer than 80 cols so it should break.

This change was introduced in https://github.com/prettier/prettier/pull/4954.
I prefer the new fakeAsync formatting, but I think print width should have priority.

**Comment by lydell** [comment]
Hi! This is actually on purpose: https://prettier.io/docs/en/rationale.html#testing-functions
