### ISSUE TITLE
Prettier messing up .less files

### ISSUE THREAD

**Issue by incompletude** [prettier/prettier#5208]
Prettier messes up escape slashs in less files:

VSCode last version.
Prettier last version.

Source:

```less
.figcaption {
    .margin-top-1\/2;
    .large\:none;
}
```

Format:

```less
.figcaption {
    .margin-top-1\ / 2;
    .large\: none;
}
```

**Comment by j-f1** [comment]
cc @evilebottnawi 

For now, you can use a `// prettier-ignore` comment before each of these lines or around the entire block to stop Prettier from formatting it.

**Comment by evilebottnawi** [comment]
@incompletude sorry for delay, what you expected? It is not valid CSS

**Comment by incompletude** [comment]
It is a `.less` file, and valid `less` syntax.

**Comment by evilebottnawi** [comment]
@incompletude can you provide information how it is compile in `css`? Why write lines what is not works?

**Comment by j-f1** [comment]
@evilebottnawi I’m guessing that it’s used to include all the styles for the classes `margin-top-1/2` and `large:none` in the `figcaption` class.

**Comment by incompletude** [comment]
This is a valid less mixin:

```
.margin-bottom-1\/3() {
    margin-bottom: 0.8rem;
}
```

This is a valid less class declaration:

```
label {
        .margin-bottom-1\/3;
}
```

That will produce the following css:

```
label {
  margin-bottom: 0.8rem;
}
```
