### ISSUE TITLE
CSS in JS crashes with variable wrapped in quotes

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#5219]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHzAGcT8BffAMxwnXwHI50IZVpGBuAHSj8hQSBTAEMYACwAqEAGLQCAXiYB6EvTgrqC7nwHRh+dejgBlGAE8ANnHzLSJAAZ98RnGCT4eIACTAxkjLysBTevFCO4SAANCAQmOwGyKCiOHQA7gAKqQgkyCCiAG4QqAAmMSAARjiiYADWcDCmYmCoUADmyDA4AK5wsRIw6FYA6hKo8CQtZrkTqIUTFvkOFW0kcHiZNe3oosjUolbrsQBWJAAeAEI19Y2moiYAMm1w+4fHIGfnpm3tNgCKPTYryQByO-RAYhw6xw+UqokqcCsFUwODaMBGZUkyAAHAAGWKoiDrEY1TD5VFwGGFV6xHBwACOPVQ9K2oh2e1B7wh63QqC6vR5vwBQPgb3BsRgCMxpWxSAATJKaqgrL8AML0Xb5KDQWkgHrrKQIvJc8EUChAA)
```sh
--parser babel
```

**Input:**
```jsx
import { css } from 'emotion';

const pathToFont = '/some/font';

const someStyle = css`
  src: "${pathToFont}";
`;

```

**Output:**
```jsx
Error: Couldn't insert all the expressions
    at transformCssDoc (https://prettier.io/lib/standalone.js:22171:11)
    at Object.embed$4 [as embed] (https://prettier.io/lib/standalone.js:22011:18)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15781:31)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15898:29)
    at https://prettier.io/lib/standalone.js:15863:16
    at Object.printComments (https://prettier.io/lib/standalone.js:15586:17)
    at printGenerically (https://prettier.io/lib/standalone.js:15862:22)
    at FastPath.call (https://prettier.io/lib/standalone.js:15700:16)
    at printPathNoParens (https://prettier.io/lib/standalone.js:25178:91)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:23541:28)
```

**Expected behavior:**

For Prettier not to crash 😅

This is a reduced example, real world case is a `@font-face` declaration. I do think the quotes are not necessary, but Prettier shouldn't crash, it's valid CSS

**Comment by SimenB** [comment]
Still an issue in 1.16 (updated the OP)

**Comment by StephenHaney** [comment]
Possibly related: I get the same error when I have too many interpolations in my Styled Components I'm trying to format.

In this Playground link, remove one interpolation block to successfully output prettified code. The syntax inside the blocks is identical, so it's just the number of interpolation blocks that causes the crash.

[Playground Link](
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcYBPAGzgBN8AzHCdfAcmPKoFpItoEZCmA3AB0oIyFGL4AQgFcYMaPgC8RUhUoA6AEZyFUAAYj8xkwEMyqAOZR2qeOkJJ8YXnBwD8pzJjimcpqBcnKB4PLVxKN2DQ-HCcSJx2cPkGdgoaGHZ-SlQZR3wATiLMAA8wiLckiBT0LKsAC0zs3PyigtLy+MqFTDS4DKzTHLynNo7YisSeustGweHW4rLnCDJcJ3rCMlMACgAmAAYADgAaAEY9gFITgGYj67OASg8wGRxCdfxsVFg3DxzCJhtiQnD8LFA4OwaBRllpTGAANaWegyKCUTirT6bbb7Y4nPb3E4FAAsD2etBh7EI9RwPwRTgOHho0EyNFM6FQZBBnm8FCpJGIcHQJyk4IRAFl4QBlAX2ABiLJOTAAEnAyAA3OAwVBgUz4ABycBkcCYJwAgrTzCdCAFCFS3KgaEyWVTUAAvOBOM4AVnGzNg7AA7nAGjAnAA2A6M-D1EOzMP4G6+5YAKzy2poJAxv1gThcv3c+HBkNjoa9HggmHhdm5Bw0xIA7B4q5QclBLFUagzm0M2x30gmfeMW32Zo0vcme62fh2et2vhBCHZUNAnDg1aZtZqPPASplzFYoHnXIW8pVCGq4GAEyEIR5A-U7JDAfDPfgQoH-JhhFATPgRAAZEg9QQJqOD4MARh-vglbVqQ5ZQcYAC+IioVAAAkwCYMoAB8UGYBoS4emc+AAQBUFgIQhA7Ew-qZERb5nDc4ylvGTh7JOXy9jOfQZF6BzDtx7ZjoOAllEwjwoaIGFYbh+GEe6cB7KR5G-s4VE0XRroel6zHLKx474BxgnTsJA78SZo60mx+BnGJAgSVJIiYdhSh4WpBEMTcKkURptEugxuksXGhnGcsI48eZtn2VxpkdtZhl2R0jloWh+g-iIcAlNgeD4JEbIyGQBCyCkUA-iAJwgJW2rQIQyCgH49CBgACn4CB1SgpjqhAqCUBVIBaP4iJalKVZgDOyAwDgxqVY06BkAA6o+8Avi4Urtcu6o1sg4BUf1PwXngzX+JY6CmMgbJkBelUpoQJRSENCIjeycAADI-HAF3mNdIC3SUUozhQACKMjVJ9SCXT9VbvG4O1wlo5DQP1mC0rAC29TA9TIEcByVSji5wAtX47SjcCHZq-UAI6g-Ax2Vh1ICmHaEJUFQ-XrtTqDrsdpinedEPfXAlUXhyk3TULIBLu2wM0+DkMSzAphaOjlCY8geyVVNpicjOADCDBnTtt6fZVZ4ACpKx18tIUhQA)

**Comment by fisker** [comment]
minimum reproduction

https://prettier.io/playground/#N4Igxg9gdgLgprEAucBnVADAOlABL1AJzCVyxABJgAHAQxgAsAVCAMWhgF9yBuHDEABoQEajACW0VMlC1ChCAHcACnITSUtAG4RxAEyEgARoVpgA1nBgBlOmHFQA5shiEArnGEMYAWwA2AOoM4vCodnDW6iHiWiEAnsho0sIOqHCEMMqmjj60yABmtH5pwgBWqAAeAEKmFlbWtD5wADIOcAVFJSDlFdYOjn5wAIpuEPAdxZ4gdIRphIkwcdRwqGCE4mKG1OuwAfqMyAAcAAzC2xBpAabUidsr6VrtwgCOo-BZohogtKgAtFBwOB6IGGQhwV7iMFZWg5PJIQqTYRpHziFzuKaofqDEZjdpIVweYQwWhGPZ6A5IACsRNM4j8-QAwhAfLlElBoE8QG40kwSRoCXBOJwgA

**Comment by evilebottnawi** [comment]
We should migrate from `postcss-less` for styled in favor https://github.com/gucong3000/postcss-jsx
