### ISSUE TITLE
when use @babel/plugin-proposal-logical-assignment-operators, the prettier not work

### ISSUE THREAD

**Issue by luxueyan** [prettier/prettier#5237]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTYAHSkxwAoBKQkssmACwEs0A6KbAWzkwB9eCAcgbYRg2pgC+JSSAA0ICAAcYTdMlDYATlogB3AAraEaZCGwA3CEwAm8kACMt2MAGs4MAMpKXTKAHNkGC0AVzgFPzQ4LRgDZ39ObGQAM2wAGyiFACs0AA8AIWc3D08uOAAZPzgU9MyQHy0orTMHbAcATzToeyUtPxgAdVtGZAAOAAYFXogogeclM164JotqhS04AEcQpg247ASkpFSM8JAoziYg0LO0P380uABFEIh4GtOFGDahmxGkABMX2cTDS9wAwhBOIkzFBoGsQCEogAVNqmY61OCSSRAA)
```sh
--parser babylon
```

**Input:**
Below code with uncorrectted indent
```javascript
const a = {
    a() {
       this.name ||= 'haha'
  }
}
```

**Output:**
```javascript
const a = {
    a() {
       this.name ||= 'haha'
  }
}
```

**Expected behavior:** 
expected format the correct indent
```javascript
const a = {
  a() {
    this.name ||= 'haha'
  }
}
```

**Comment by lydell** [comment]
For me a syntax error is thrown:

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTYAHSkxwAoBKQkssmACwEs0A6KbAWzkwB9eCAcgbYRg2pgC+JSSAA0ICAAcYTdMlDYATlogB3AAraEaZCGwA3CEwAm8kACMt2MAGs4MAMpKXTKAHNkGC0AVzgFPzQ4LRgDZ39ObGQAM2wAGyiFACs0AA8AIWc3D08uOAAZPzgU9MyQHy0orTMHbAcATzToeyUtPxgAdVtGZAAOAAYFXogogeclM164JotqhS04AEcQpg247ASkpFSM8JAoziYg0LO0P380uABFEIh4GtOFGDahmxGkABMX2cTDS9wAwhBOIkzFBoGsQCEogAVNqmY61OCSSRAA)
```sh
--parser babylon
```

**Input:**
```jsx
const a = {
  a() {
    this.name ||= 'haha'
  }
}
```

**Output:**
```jsx
SyntaxError: This experimental syntax requires enabling the parser plugin: 'logicalAssignment' (3:15)
  1 | const a = {
  2 |   a() {
> 3 |     this.name ||= 'haha'
    |               ^
  4 |   }
  5 | }
```

We should enable that plugin and add support for `||=`.

**Comment by luxueyan** [comment]
@lydell  I upgrade babel-eslint to  v10.0.1 , there will be no syntax errors. Maybe the playground babel-eslint version is old!
