### ISSUE TITLE
Line comment between function an opening brace

### ISSUE THREAD

**Issue by fvictorio** [prettier/prettier#5241]
If you have the opening brace of a function on its own line, and a line comment after the function signature, the output of prettier is different if you run it once or twice.

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT4D0l+MAFjgM75P4CGhm2eUAOlMH758AJzgx0IqPgAsAJn4BfEABoQEAA65ojZKDYiREAO4AFAwl0o2ANwg4AJqpAAjEWzABrcQGUNHnCgAc2QYEXQ4NUDGOBEYU3cggFs2ZFQ2ABsYtQArRgAPACF3L182JLgAGUC4NMzskH8RGJFkVzYXAE8M6GcNEUCYAHVHemQADgAGNX6IGKH3DTb+uBabWrUxAEd0HDEEtmTUpHSsyJAYpJxQ8PPGQKCMuABFdAh4OrO1GA6RhzGkHJvu4cBkHgBhCBJFJtKDQDYgdAxAAqHSspxiikUQA)
```sh
--parser babylon
```

**Input:**
```jsx
function foo() // this is a function
{
  return 42
}
```

**Output:**
```jsx
function foo() { // this is a function
  return 42;
}

```

**Second Output:**
```jsx
function foo() {
  // this is a function
  return 42;
}

```

**Comment by evilebottnawi** [comment]
Unstable comment

**Comment by jaideng123** [comment]
I can work on this

**Comment by jaideng123** [comment]
Is the first output the expected behavior?

**Comment by evilebottnawi** [comment]
@jaideng123 I think second output

**Comment by j-f1** [comment]
I’d expect the first output to be maintained, but either way works.

**Comment by jaideng123** [comment]
If I were reading this code it would seem more natural for the comment to be inline (or maybe even above the function declaration?)

**Comment by jaideng123** [comment]
After digging into this bug a little more I found another layer of instability:

**Input:**
```jsx
function foo() 
// this is a function
{
  return 42
}
```

**Output 1:**
```jsx
function foo() // this is a function
{
  return 42
}
```

**Output 2:**
```jsx
function foo() { // this is a function
  return 42
}
```

**Output 3:**
```jsx
function foo() {
  // this is a function
  return 42;
}
```

**Comment by evilebottnawi** [comment]
@jaideng123 Just handle `1` and `2` variants
