### ISSUE TITLE
printWidth ignores comments

### ISSUE THREAD

**Issue by otorrillas** [prettier/prettier#5242]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAnBATObAYQgFsAHaBLAXk3OwnLUxoD5M0ALAQwBs+EAO4AKADwAxCNlIBZHlB4BzQpjBcAlnzy4oNYOq06EAX0zAAdFYZM0ZgPRsAlAG5M9+5jho+G2AFo8DTQeACM+OH9fKDgcOB4wGHsoCH9DbV1-G3IQABoQJhgNdGRQHmxGIQAFcoQ0ZBAeADcIDTw8kFDsBIBrOBgAZXIEvyVkGGwAVzh8vzRCGCrupVIeZAAzfnn8gCs0AA8AIW6wPsGeUjgAGT84Da2ZkGHseewG0LCAT0EoDoY-GAAdTaMC4yAAjAAmACs+Rs80B3RyKAY3kITTu+VwAEdJhpcEtlKt7nxtiB5qQNOMpo80KMIgBFSYQeAkskwMLAvCg5CQ-ITHhaUYkUjElApGIdSbzAAqYXqSE2pLgJhMQA)
```sh
--parser babylon
--print-width 125
```

**Input:**
```jsx
const renderComponent = props => shallow(<FormManager children={children} {...props} />); // eslint-disable-line react/no-children-prop
```

**Output:**
```jsx
const renderComponent = props => shallow(<FormManager children={children} {...props} />); // eslint-disable-line react/no-children-prop

```

**Expected behavior:**

It creates a new line before `shallow`, so none of the lines won't go over `printWidth`, as shown below:

```jsx
const renderComponent = props =>
  shallow(<FormManager children={children} {...props} />); // eslint-disable-line react/no-children-prop

```

**Comment by bartocc** [comment]
I am surprised nobody ever reacted to this issue. Is this by design?

**Comment by evilebottnawi** [comment]
@bartocc @otorrillas  sorry for delay, a lot of issues, it is expected output, it can't be fixed, we can't associate linter comment with potential problem places, it is impossible so you should move comment manually in right place

**Comment by bartocc** [comment]
thx for the feedback @evilebottnawi 👍
