### ISSUE TITLE
Unstable comment in while

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5245]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB3AFgSwDZwBQA6UABKcTAE4CucRZxA9A8QMIQC27CMRAlMcAC+IADQgIABxiZoAZ2SgAhhQoRUABWUJ5KRQDcImACaiQAIwqKwAazgwAyhKuYoAc2SUaYl7LgUY6pau7IrIAGaK2L5iAFayAB4AQpY2dvaKXAAyLnDhkdEgThS+FMjmimYAntjQphIULjAA6sYw6MgAHAAMYvUQvk2WEmX1cCV6uWIUcACOVJjTgYrBoUgRUXBivuyYHtSbILIurrgAilQQ8HkbYjAVLUZtyABMt5Y4x2ycqyBQ0JMgKi+AAqFR0618gkEQA)
```sh
--parser babylon
```

**Input:**
```jsx
while(
    true
    // Comment
) {}
```

**Output:**
```jsx
while (true) // Comment
{}

```

**Second Output:**
```jsx
while (
  true // Comment
) {}

```

**Expected behavior:**

```jsx
while(
    true
    // Comment
) {}
```

**Comment by jaideng123** [comment]
I can work on this

**Comment by jaideng123** [comment]
Hey, while I was fixing this I noticed there's some inconsistency with how comments are handing between while and if statements For example:
**Input:**
```jsx
while(true) // Comment
{}

if(true) // Comment
{}
```

**Output :**
```jsx
while (
  true // Comment
) {}

if (true) {
  // Comment
}
```

Is this something we should address in another issue or is it by design?

**Comment by evilebottnawi** [comment]
@jaideng123 hm, looks like bug for if
/cc @j-f1 What do you think?

**Comment by jaideng123** [comment]
There's code in the if handler function that explicitly defines this behavior of inserting the comment in the body if it's before the body so it might be a bug for while

**Comment by jaideng123** [comment]
I added the changes necessary to bring the while comment formatting closer in line with if to my PR, If you want to open a separate issue I can roll them back and submit a separate PR
