### ISSUE TITLE
Some utils have invalid export

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5255]
**Environments:**
- Prettier Version: 1.14.3
- Running Prettier via: no mater
- Runtime: no mater
- Operating System: no mater

**Steps to reproduce:**
1. Import `getNextNonSpaceNonCommentCharacterIndex` from shared utils.
2. Use `getNextNonSpaceNonCommentCharacterIndex` and try to use custom `locEnd`.
3. Looks on source https://github.com/prettier/prettier/blob/master/src/common/util-shared.js#L18
It is always `locEnd` of node, but i want to use custom `locEnd` (example it is `locStart` in some cases or custom function to detect location).

Example usage:
```php
const nextChar = getNextNonSpaceNonCommentCharacterIndex(
   options.originalText,
   node
   option.locStart // Or function() { return 10 + (node.name ? node.name.length - 1 : 0) + 1;  }
);
const isEmptyLine = nextChar === "\n" || nextChar === "\r"
```

**Expected behavior:**

Allow to use custom `locEnd`.

**Actual behavior:**

It is always `locEnd` of `node`.

-----
Not all utils affected. Only `isNextLineEmpty`, `isPreviousLineEmpty`, `getNextNonSpaceNonCommentCharacterIndex`. Looks it is was do in early prettier version when was introducing plugin api.
In theory it is bug, but it is breaking change if we change this. Should we fix it as unexpected/invalid behavior in path/minor version or wait major release for this?

/cc @vjeux

**Comment by vjeux** [comment]
@azz introduced the plugin API. I don't have much context on this. We have very few plugin usage so it should be fine to do a breaking change here I believe.

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/6993
