### ISSUE TITLE
semi issue with TypeScript !.

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#5256]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEcA2mC8mASnAIZgwAiA8gLIB0AZgJZQAmNtAchG3ABQAnOIwCUAHSgBufrkyk0mABIAVWgBkAojjgBbBDFEBCehgCeO+mACugtBEEFMAcgAOEVvEHOQAGhAQrjDM6MigpIKCEADuAAoRCGjIIKQAbh5sfiAARoLkANZwMADKruSsAObIMILWcP6saHCCMLF5FbqkyIykOE3+AFZoAB4AQnlghSWk+uqscN29-SBlds3JMGaucGhggsxBWa77sADqzGwwABbIABwADP7HEE2nea7JxzvNqQv+wgBHazMYRtUgdLpIHp9eogJq6ZiLGH+NCVHQARWsEHgSOWMFI2XOlxuSAATP4aqRmDhKgBhCC6TrJKDQP4gaxNFQEpJQpZwAC+-KAA)
```sh
--parser typescript
--no-semi
```

**Input:**
```tsx
const el = ReactDOM.findDOMNode(ref)
;(el as HTMLElement)!.style.cursor = 'pointer'
```

**Output:**
```tsx
const el = ReactDOM.findDOMNode(ref)
(el as HTMLElement)!.style.cursor = "pointer"
```

**Expected behavior:**

The output is definitely wrong

**Comment by j-f1** [comment]
Specifically:

**Second Output:**
```tsx
const el = (ReactDOM.findDOMNode(ref)(el as HTMLElement)!.style.cursor =
  "pointer")

```
