### ISSUE TITLE
invalid indent with nested ternary in test

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5257]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAbgQwE4AIC8uAFKlAK4C2ARnHgKS4CMADLgHyEBMuAZDwDpRcw4qUo16TZqwA8U3AB8FuMdVq4GLVh1ydmASkEjjuAPxMjJ4Ul2GhI880vXczANwgANCAgAHGACW0ADOyKA42BAA7gAKOAihKJjoEAEAJl4gVNiYYADWcDAAyr65AVAA5sgw2GRw3uXBtDAxORUUmMgAZpgANk3eAFbBAB4AQjn5hUWYFHAAMuVw3X0DIKXYTdjIWZhUAJ690Jm+2OUwAOrpMAAWyAAczN6nEE0XOb47p3Bb6Mve2DgAEcyAFAa1MO1Okgev16iAmhQAtVavDguUKr04ABFMgQeArOHeGB7K5pW7ITjEnIBXoYgDCEAoHR2UGg-xAZCaABU9olYU0AL6CoA)
```sh
--parser babylon
```

**Input:**
```jsx
$var = ($number % 10 >= 2 &&
    ($number % 100 < 10 || $number % 100 >= 20)
        ? 1
        : 2)
    ? 0
    : 0;
```

**Output:**
```jsx
$var = ($number % 10 >= 2 && ($number % 100 < 10 || $number % 100 >= 20)
? 1
: 2)
  ? 0
  : 0;

```

**Expected behavior:**

```jsx
$var = ($number % 10 >= 2 && ($number % 100 < 10 || $number % 100 >= 20)
  ? 1
  : 2)
    ? 0
    : 0;

```

Maybe even better output, hard to say what will be looks good, but indent should be don't loose.

**Comment by evilebottnawi** [comment]
More simple example:

Input:
```jsx
const value = (true ? 'true' : false)
    ? (true ? 'true' : false)
    : (true ? 'true' : false);
```

Output:
```jsx
const value = (true
? "true"
: false)
  ? true
    ? "true"
    : false
  : true
    ? "true"
    : false;
```

**Comment by evilebottnawi** [comment]
Looks latest version in master (we use as `dev` deps to catch integration problem in CI) broken (regression):
Input:
```js
 const afterInline =
        childNode.comments && childNode.comments.length
          ? concat([
              openTag,
              hardline,
              comments.printComments(childNode.comments, options),
              "?>"
            ])
          : isProgramLikeNode(node) && isLastNode
            ? ""
            : concat([openTag, " "]);
```

Output:
```js
 const afterInline =
        childNode.comments && childNode.comments.length
          ? concat([
              openTag,
              hardline,
              comments.printComments(childNode.comments, options),
              "?>"
            ])
          : isProgramLikeNode(node) && isLastNode
          ? ""
          : concat([openTag, " "]);
```

Lose `indent` in `nested` ternary

/cc @j-f1 @ikatyang @duailibe

**Comment by duailibe** [comment]
@evilebottnawi This is intended #5039

**Comment by evilebottnawi** [comment]
@duailibe looks ugly :confused:

**Comment by duailibe** [comment]
@evilebottnawi 🤷‍♂️ 

People complain about the nesting since forever (goes back to #737). I don't care either way but since we've just changed it I don't think we're gonna change it back anytime soon unless there's anything new to discuss

**Comment by j-f1** [comment]
IMO the first two examples should be fixed though.

**Comment by fbartho** [comment]
I'm exhibiting this issue in 1.15 as well

**Comment by fbartho** [comment]
I'd be happy to help fixing this if *anybody* can point me at the right code. I'm new to looking at Prettier's source!

**Comment by fbartho** [comment]
Looking at the snapshot tests, it looks like somebody intentionally changed things and updated these examples to work the way they do as described in this ticket.

Forgive me for being new here and not recognizing screen names, but has somebody with Prettier commit access actually agreed that this is unintentional and should be fixed?

**Comment by fbartho** [comment]
It looks like this PR https://github.com/prettier/prettier/pull/5039 introduced the changes to flatten Ternaries, and this happened on purpose?

**Comment by fbartho** [comment]
@evilebottnawi -- were you aware that this behavior change might have been intentional?

**Comment by fbartho** [comment]
Oh crap, now I've expanded the comments marked off topic & I see that yes, you knew that. But now I'm just confused as to what's supposed to happen here.

**Comment by brodybits** [comment]
I think this issue shows up even more ugly in case of JSX.

**Sample input:**

```jsx
(a ? b : c) ? (
  <Element>
    <Sub />
    <Sub />
    <Sub />
    <Sub />
    <Sub />
    <Sub />
  </Element>
) : (
  <Element2>
    <Sub />
    <Sub />
    <Sub />
  </Element>
)
```

**Output:**

```jsx
(a ? (
  b
) : (
  c
)) ? (
  <Element>
    <Sub />
    <Sub />
    <Sub />
    <Sub />
    <Sub />
    <Sub />
  </Element>
) : (
  <Element2>
    <Sub />
    <Sub />
    <Sub />
  </Element>
);
```

I think this is similar to the "more simple example" in <https://github.com/prettier/prettier/issues/5257#issuecomment-429425233>.
