### ISSUE TITLE
Blank lines aren’t preserved between parameters

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#5260]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOkUmMATgK5gwS0AUZFF0cANB5zn4UYAdwh9ynGAAtacXkJwAzCPVoSBgyZ0VKAlgDcF2nJj0APDZ0xwjUKxTh6A5tJgOcUPVGMD49xS0BOFRbBED+AEpiAF8yOKgyJXooJj1oZUJ2E24PIKkxDxk5X04VNTyIk30jDzNLRRs7DydXd0UvHyKESpMQsMSTLWjgGJAeEAgABxh06mRQdFpaCBEABSWETGQQdAMIPQATcZAAI1p0MABrOBgAZSnL72dkOnpeEG8bWhg1i+cALboZBKdCoGwTABWmHMACELtdbnd0AC4AAZbxwEFgiEgR60b47U7oU4AT1Q0BOU1o3hgAHUjjJkAAOAAME2pEBsdIuUx21Lg3yMJzkAEd6Ho5H90IDgUhQeCPjYAXpXgwlc9QgBFegQeDYxUTGAkhmHJlIABMRouelQzwAwhAAUCdlBuCd6DYACok7bynFwGIxIA)
```sh
--parser babylon
```

**Input:**
```jsx
class Foo {
  constructor(
    one,
     
    two,
    three,
    four,
     
     
    five,
    six,
    seven,
    eight,
    nine,
    ten,
     
    eleven
     
  ) {}
}

function foo(
    one,
     
    two,
    three,
    four,
     
     
    five,
    six,
    seven,
    eight,
    nine,
    ten,
     
    eleven
     
) {}
```

**Output:**
```jsx
class Foo {
  constructor(
    one,
    two,
    three,
    four,
    five,
    six,
    seven,
    eight,
    nine,
    ten,
    eleven
  ) {}
}

function foo(
  one,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  ten,
  eleven
) {}

```

**Expected behavior:**

```jsx
class Foo {
  constructor(
    one,

    two,
    three,
    four,

    five,
    six,
    seven,
    eight,
    nine,
    ten,

    eleven
  ) {}
}

function foo(
  one,

  two,
  three,
  four,

  five,
  six,
  seven,
  eight,
  nine,
  ten,

  eleven
) {}

```

Note that the blank lines are preserved when _calling_ a function:

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUAdKACAvaOAGl0IPMJgHcIz9qALAJzlKoPQFcWGK8nSoy4BLAG4cReAM6iAHv0Iy4kqEoJxRAcyYwNeKKKhSK8dUMHS4AG1UJLuAJQgSICAAcYo6DOSgAQxYWCBoABSCEPxQA8QhRABNXEAAjFgCwAGs4GABlDwzjbWQYFm5SEGMVFhgw9O0AWwDkVACbFTcAKxl5ACF0rJzcgIa4ABljOBa2jpAClmrkVICUgE8baGSPFmMYAHVEmCZkAA4ABjdtiBU99I8l7bhqyWS2AEduUTY6gMbmpFa7QqKgaohKZWBRTsAEVuBB4NMgW4YCsDgkjsgAEzI9KiGxFADCEAaTSWUGIyW4KgAKitooCVABfRlAA)
```sh
--parser babylon
```

**Input:**
```jsx
foo(
    one,
     
    two,
    three,
    four,
     
     
    five,
    six,
    seven,
    eight,
    nine,
    ten,
     
    eleven
     
)
```

**Output:**
```jsx
foo(
  one,

  two,
  three,
  four,

  five,
  six,
  seven,
  eight,
  nine,
  ten,

  eleven
);

```

This is especially important when there are decorators involved:

**Prettier pr-5188**
[Playground link](https://deploy-preview-5188--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOkUmMATgK5gwS0AUZFFAAgJZQBWcJqwBC6WgEoOnAA60eAN3TwctOOgAm0VAE8cAI3FIcASTG0ANGWnc+g4QFkdABVoQwcbCynlZ8pSpqmtp6ALYubh5etMYmTq7unpgsFjjWvrYCQjCsJllMPNAAKjoyngB0AIJQEDAAFnC0RXV8AOY+NjhyispwqupaULo46DX1jc1tsdW1DU0tUK04AD449FAacABmfHAaVr4SxDgAvmRnUCAWIBAyMIXUyKDibgDuzuIImMgg6AoQPA0VxA+lo6DAAGs4DAAMoycFtZB0ehwa58TCNGCudCtULoZBbdCoDHXfiYAAeIjBkOhMPQoTgABldgSiSSQPDaBjaD8YKVPGB5Hdgd1YAB1QH1ZAADgADNc5BAMWKwTIfnJPI0FHBgWoAI70HhqbG4-FIQnE1EgDGhHhIhhWzBtVBwACK9FqOvNbKtMHQ+glGilSAATNc6OgeKg2gBhCChPE-GpQHXXegYor+77ey0nE5AA)
```sh
--parser typescript
```

**Input:**
```tsx
class Foo {
  constructor(
    @inject(Bar)
    private readonly bar: IBar,

    @inject(MyProcessor)
    private readonly myProcessor: IMyProcessor, 

    @inject(InjectionTypes.AnotherThing)

    private readonly anotherThing: IAnotherThing | undefined,
  ) { }
}

```

**Output:**
```tsx
class Foo {
  constructor(
    @inject(Bar)
    private readonly bar: IBar,
    @inject(MyProcessor)
    private readonly myProcessor: IMyProcessor,
    @inject(InjectionTypes.AnotherThing)
    private readonly anotherThing: IAnotherThing | undefined
  ) {}
}

```

The above also raises the question if blank lines should be allowed between decorators. Not sure.

**Comment by RobertCZ** [comment]
It would nice if function parameters formatting used login similar to object literals eg if new line is found it's one-param-per-line otherwise use current algorithm. Would really help with React-without-JSX style:

```
div(
  {},
  h1({}, 'Title'),
  p({}, 'Text'),
  a(
    {
      className: 'link',
      href: 'x',
    },
    'some link',
  ),
)
```

[playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEFMF5PAAeSAjADQCeSATAL4A6UjkUG2eBx5jmvf-mKnUaMAJgEsAbgAoeBWmTkALErKj9gCzHN4ByACriYAGzi7F6zAEoLVxiDIgIABxjj0yUAEMATj4gA7gAKvghoyCBekhDiog4gAEY+XmAA1nAwAMrOKeJQAObIMD4ArnCOeWhwPjBByfkAtl7IAGZexlWOAFZohABCyWkZmV4NcAAyeXCt7Z0gOT5VPhEJXgkUxtDxzj55MADqsTBKyAAcAAyOOxBV+8nOETtwS5LTjj5wAI4l4h91Xo1mkg2h1yiAqg1xEVSmC0Hl8qYAIolCDwGagxwwNaHUTHZDUTHJcTGeEAYQgDSaESg0DeIBKVX0a3CwNmcFotCAA)

**Comment by evilebottnawi** [comment]
@RobertCZ can you create issue, it is not related to this issue?

**Comment by RobertCZ** [comment]
Sure, it just looks like the same issue to me: preserve empty lines when you find them otherwise format as usual. But no problem, will create a new issue
