### ISSUE TITLE
[JSON] Trailing comments are not handled

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#5263]
We use the js expression parser (which shares the same printer with JSON) to parse binding syntax in HTML, but the trailing comments are removed (reported by https://github.com/prettier/prettier/pull/5259#issuecomment-429571079).

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLKATOAPABAegCpcAVAeQBEylcBXAZzl1Q1wHcALBXAG3QGt67VDx64ARkwAOAJwgA3FnFbiAnrgCCABQCSuQvhAAaEBCkxU0eslABDGXLZb7CaylvyILYyHEzbYPxwMADKUgHoAObIMDK0cCbojDIwWv6RALa2yABmtjyMJgBW9NgAQv6BwSG2GXAAMuhwufmFIOEyycggJdA+sugwAOosMBzIABwADCayEIxD-lLdsnDJ8s0mMnAAjrSo22m2mdlIeQUJIIwZqDFxl-RRPHAAirQQ8C0XJjC24iMYMbIABMP38IiiAGEIBkst0oNBNiAGHASH83OdGABfLFAA)
```sh
--parser json
```

**Input:**
```jsonc
index /* TODO: use id when links will be provided by API */
```

**Output:**
```jsonc
Error: Comment "TODO: use id when links will be provided by API" was not printed. Please report this error!
    at https://prettier.io/lib/standalone.js:10671:13
    at Array.forEach (<anonymous>)
    at ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:10669:15)
    at coreFormat (https://prettier.io/lib/standalone.js:10719:3)
    at format (https://prettier.io/lib/standalone.js:10874:16)
    at formatWithCursor (https://prettier.io/lib/standalone.js:10886:12)
    at https://prettier.io/lib/standalone.js:21134:15
    at Object.format (https://prettier.io/lib/standalone.js:21142:12)
    at formatCode (https://prettier.io/worker.js:188:21)
    at handleMessage (https://prettier.io/worker.js:139:18)
```

**Expected behavior:**
Comments are printed.

**Comment by renatoagds** [comment]
Would love to help with this one @ikatyang ... Can you brief where can I start? 👍

**Comment by michaeljota** [comment]
@ikatyang I'm trying to reproduce this issue with a JSON, but I am unable to do so, please, forgive me as I maybe misunderstanding the issue, but currently trailing comments are being handle well I think

[Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwCWUAmcAeACAegCo8AVAeQBFyk8BXAZzjzUzwHcALBPAGwwDWDDml688AI2YAHAE4QAbqzhsJATzwBBAAoBJPEQJ4AvnhAAaEBGkw00BslABDWfPbaXCByicKIrCxAJWScwATgYAGVpUIwAc2QYWTo4SwwmWRhtELiAWydkADMnXiZLACsGHAAhELCIyKdcuAAZDDgikrKQGNkM5BBK6EC5DBgAdVYYTmQADgAGSzkIJnGQ6QG5OAyFDstZOABHOjQD7Kc8gqRi0tSQJly0ROS7hnjeOABFOgh4TtvLDAnBJJphpsgAEyAkKieIAYQguXyAyg0D2IEYcFIwO8NyYxmMQA)

**Comment by ikatyang** [comment]
@michaeljota The playground link on the OP can still reproduce the issue.

**Comment by ikatyang** [comment]
Hey @renatoagds, have you started to look into it? I'd like to give it a shot if you haven't.

**Comment by michaeljota** [comment]
@ikatyang This maybe an issue with the `vue` parser as I can't reproduce this with the `html` parser, although I understand that `html` does not evaluate js expressions, I don't have anything else to check on to as `angular` parser does not allow comments and throws.

**Comment by renatoagds** [comment]
@ikatyang hey! I didn't start it. go ahead 🤘

**Comment by ikatyang** [comment]
@michaeljota It's indeed a `vue`-only issue after we switch to use angular-estree-parser for angular expression.

(Angular only allows a single-line comment at the end of the expression, excluding microsyntax.)
