### ISSUE TITLE
JSDoc compatibility: support prettier-ignore inside multi-line/JSDoc comment?

### ISSUE THREAD

**Issue by jnst** [prettier/prettier#5268]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AYWgGcYBDWE3CAM1wCdKBrASygHMd9UdVVcABwZwYMVnAYBaVhygQROOAA9BCmLkhQyuAEot2HYtopVcAXlzBuuANIBRAJoB9ACIBBAJIAZF7vcAcraeAQDiuLhIuADkHj5+gcFh0QA0Ebj8dnAAnjT0ACbkrAA2uUxQbJw2Di4A6vb2tr7O-kEh4VHR9Y3NrUmhqRGZtjl5uADucHDMpYwGVXh2Ts4AsgDyAQAqABK9ie2d61u7CW3JacOjdLgAttAwABaz5ZVci96eK56bzmsAYs4AAruUL2dLpKIAVgADGlwfCEZlvKwbqwNNdBOQOHAbCt3AANIEgsEI8FRACM0NhpJpmRW5GUQixOKgAF8ANw4EApEAQQTiUjIUDkBgMCDjQEihAkZAgcgANwgrHy3JAACMmGBmKIAMqYsCGZAwBgAVzgPPYJEkMEBTA4N3IyFo5GKVp5ACsSMoAEKa7UwHXkG5wZFQOBOl1ukCYhhWhiytXkNXZYrQVXCdgwWrKx7IAAcsOjYqttSYgllwjgcfl4Z5IgAjibWCJbViHRHXeaQFbUUbTV2SIZinAAIomiDwDtRihq7P5XNIABMPONRWKhmIN3bKHkYdVJqtmyTMqQzs7rNZQA)

I value human readability, so I often adjust the position of the colon and the position of the comment.

```javascript
/**
 * Constants of ranking
 */
// prettier-ignore
export const RankingConstant = {
  KEY_DAILY_RANKING  : 'DAILY_RANKING',   // Key of daily ranking
  KEY_WEEKLY_RANKING : 'WEEKLY_RANKING',  // Key of weekly ranking
  KEY_MONTHLY_RANKING: 'MONTHLY_RANKING', // Key of monthly ranking
  LIMIT_OF_PAGE      : 50,                // Limit of page
  MAX_PAGE           : 100,               // Max page
};
```

## Problem

I can adjust it using `prettier-ignore` comment, but the way to write single-line comments under multi-line comments is ugly and It may affect JSDoc (unconfirmed though).  

## Expect

Could you please write like this?

```javascript
/**
 * Constants of ranking
 * prettier-ignore
 */
```

or

```javascript
/**
 * Constants of ranking
 * @prettier-ignore
 */
```

**Comment by lydell** [comment]
> may affect JSDoc (unconfirmed though)

Please confirm!

**Comment by lydell** [comment]
Can you share how you test the JSDoc stuff?

**Comment by jnst** [comment]
@lydell 

### ranking_constant.js

```javascript
/**
 * Constants of ranking
 */
// prettier-ignore
export const RankingConstant = {
  KEY_DAILY_RANKING  : 'DAILY_RANKING',   // Key of daily ranking
  KEY_WEEKLY_RANKING : 'WEEKLY_RANKING',  // Key of weekly ranking
  KEY_MONTHLY_RANKING: 'MONTHLY_RANKING', // Key of monthly ranking
  LIMIT_OF_PAGE      : 50,                // Limit of page
  MAX_PAGE           : 100,               // Max page
};
```

```bash
$ yarn add -D jsdoc
$ node_modules/.bin/jsdoc ranking_constant.js
$ open out/index.html
```

**Comment by lydell** [comment]
Thanks!

**Comment by ikatyang** [comment]
_Copied my comment from https://github.com/prettier/prettier/pull/5748#pullrequestreview-191924898:_

> Sorry, I missed that issue. I think we should not read `@prettier-ignore` from JSDoc since it'll be visible for the end users, which is super confusing:
> 
> ![image](https://user-images.githubusercontent.com/8341033/51068642-0f3d7900-165c-11e9-839f-2ded82f87441.png)
> 
> I'd suggest to put the `prettier-ignore` comment in front of the JSDoc to achieve this goal:
> 
> **Prettier 1.15.3**
> [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKB6DACADgJzhhgEs58BaEgcygkPQwCon1snsBhaAZxgENYPbBABm2fIIDWJKNTZMM6OAA9c9GNkhQ+2AErTZ1bjoFDsAXmzA22ANIBRAJoB9ACIBBAJIAZV3o8AOTsvQIBxbGwkbAByT19-IJDwmIAaSOwsezgATxFxABN+EgAbPMkoGTlbR1cAdQcHOz8XAODQiOiYhqaWtuSwtMisu1z87AB3ODgpMolDaqhI2pcAWQB5QIAVAAk+pI6uje29xPaU9JGxsWwAW2gYAAs5iqr5JewfL1WvLZd1gBiLgACh4wg4MhlogBWAAM6UhiKRWR8JFuJE0N1w-GocFsqw8AA0QWCIUjIdEAIyw+HkulZVb8FR4HF4qAAXwA3OgQKkQBBcKReMhQPx8PgIBNgWKEDxkCB+AA3CAkAq8kAAI0kYCkRAAytiwEZkDB8ABXOB8x4wW4lOqPDFwHiGuB62UYkiKjE5eVgHhyvmyHjkGDAyTUW78ZCifglYN8gBWPBUACFtbqYHr+Lc4KioHBo7H4yAkyo9UYSnAAIpmiDwQtxy0gbH4YP4eUa-ganIlaDqgiyGB1VVPZAADnhzYlwbqklw8oITvIioLfMIAEczSRCGGcZGG8Xg+iTeamzwK9Xa-WkDHG3yBBrhwVR0gAEz3ySlIzcW77lB0fN1TNYMti7OUbyLOB2XZIA)
> ```sh
> --parser babylon
> ```
> 
> **Input:**
> ```jsx
> 
> // prettier-ignore
> /**
>  * Constants of ranking
>  */
> export const RankingConstants = {
>   KEY_DAILY_RANKING  : 'DAILY_RANKING',   // Key of daily ranking
>   KEY_WEEKLY_RANKING : 'WEEKLY_RANKING',  // Key of weekly ranking
>   KEY_MONTHLY_RANKING: 'MONTHLY_RANKING', // Key of monthly ranking
>   LIMIT_OF_PAGE      : 50,                // Limit of page
>   MAX_PAGE           : 100,               // Max page
> };
> 
> ```
> 
> **Output:**
> ```jsx
> // prettier-ignore
> /**
>  * Constants of ranking
>  */
> export const RankingConstants = {
>   KEY_DAILY_RANKING  : 'DAILY_RANKING',   // Key of daily ranking
>   KEY_WEEKLY_RANKING : 'WEEKLY_RANKING',  // Key of weekly ranking
>   KEY_MONTHLY_RANKING: 'MONTHLY_RANKING', // Key of monthly ranking
>   LIMIT_OF_PAGE      : 50,                // Limit of page
>   MAX_PAGE           : 100,               // Max page
> };
> 
> ```

**Comment by nmussy** [comment]
Agreed, this is a much cleaner and simpler solution. This also removes the performance concern I had of having to go through all the comments contents to look for a `@prettier-ignore`.

**Comment by thorn0** [comment]
Closing as per https://github.com/prettier/prettier/pull/5748#pullrequestreview-191924898
