### ISSUE TITLE
[bug] Prettier formats contents of template string

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#5279]
**Prettier 1.14.3**

[playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDEAbdAIQjTwF48SBPSgEwDo2BLANwAMAOlEEweRDOQCGzJHgBmlNAG5hoqeW4BzKAFpu8ALZE5YBPGyqRMAFYBXEt3nNdheLFPm4ltTEXpdAHdsKQw5YNCrUX80XR5sODAYbmg5ABJgDAYAPjwMLm4EpJSoAF8o6wys+lz8kikwAGsAeSgAWQgAI25KPAB+PCFrUQzDOB4pAAoAcgAeNjgiRpgIDGmASlK8YF9RaKU4wsTk1IIIcjtDKCiYUVLffjw5aen74etcgCpt3ZhA7jYMAAFulMjk8JN8kCIIE2lIoMwAAreABKMP6gwyAEYAAw4vAAejyHGhsPhSNRMNKAFJHs8pHYVhtyr43kMQAAaECrE7EZCgKTYbAwxGChBEZAgKS8CAAzkgTohJpwGAAZQwDW4UC0yBg2DscC5WqI3hgiJCWkMUmQ8g0Jq5NiIaCoSsaKtVUjGABktXAbXbDSANdgTdhJZ0pJ1WNB5RhsFqYAB1AHA5AADhxXLjEBNiZCGElccW3l4fq5CQAjnYjuapJbrUhbeR7SATYZuLr9YGiFqtJQAIp2CDwf3NwMwSPJwFA5AAJi5eqkPV7AGEIIYrZKoNAyyAHHAACqRiWNgNcqQkUcttgQMBXwMQRkYRmz++lUpAA)

**Input:**

```js
export const FlexBox = styled.div`
	display: flex;
	align-items: center;
	justify-content: center;
	flex-wrap: wrap;
	flex-direction: ${p => p.direction};

	${p => p.stackOnMobile ? `
		${media('<desktop')} {
			flex-direction: column;
		}
	` : ''}
	
	> * {
		width: ${p => (p.howManyPerRow ? `${100 / p.howManyPerRow}%` : 'auto')};
	}
`
```

**output:**

```js
export const FlexBox = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  flex-direction: ${p => p.direction};

  ${p =>
    p.stackOnMobile
      ? `
		${media("<desktop")} {
			flex-direction: column;
		}
	`
      : ""} > * {
    width: ${p => (p.howManyPerRow ? `${100 / p.howManyPerRow}%` : "auto")};
  }
`;
```

**Expected behavior:**

Prettier should never format any part of a template string (at least not without some in-code option like some sort of comment).

**Comment by trusktr** [comment]
It Prettier should in fact format a template string, it should be explicit. For example, using a comment:

```js
/* prettier format-template */
export const FlexBox = styled.div`
   ...
`
```

**Comment by trusktr** [comment]
`styled.div` should not be an indicator that prettier should format the template.

**Comment by trusktr** [comment]
IMO the output is ugly compared to the input. I'd much prefer to tell Prettier when to format templates; it'd just conceptually pure that way because string literals are string literals, not code.

**Comment by trusktr** [comment]
Maybe it isn't a bug, but I thought it was because the output looks so bad.

**Comment by lydell** [comment]
I don't understand what specifically what the issue is? Could you please clarify?

**Comment by SimenB** [comment]
If you add a semicolon after your `${p =>` part, it looks alright

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDEAbdAIQjTwF48SBPSgEwDo2BLANwAMAOlEEweRDOQCGzJHgBmlNAG5hoqeW4BzKAFpu8ALZE5YBPGyqRMAFYBXEt3nNdheLFPm4ltTEXpdAHdsKQw5YNCrUX80XR5sODAYbmg5ABJgDAYAPjwMLm4EpJSoAF8o6wys+lz8kikwAGsAeSgAWQgAI25KPAB+PCFrUQzDOB4pAAoAcgAeNjgiRpgIDGmASlK8YF9RaKU4wsTk1IIIcjtDKCiYUVLffjw5aeny3etcgCpt3ZhA7jYMAAFulMjk8JN8kCIIE2lIoMwAAreABKMP6gwyAEYAAw4vAAejyHGhsPhSNRMNKAFJHs8pHYVhs3tZ7lAhiAADQgVYnYjIUBSbDYGGIoUIIjIEBSXgQAFckCdEJNOAwADKGAa3CgWmQMGwdjg3O1RG8MERIS0hikyHkGlN3JsRDQVGVjVVaqkYwAMtq4Lb7UaQJrsKbsFLOlJOqxoAqMNhtTAAOoA4HIAAcOO58YgpqTIQwUvji28vH93ISAEc7EcLVIrTakHbyA6QKbDNw9Qag0RtVpKABFOwQeABltBmBRlOAoHIABM3P1Uh6fYAwhBDNapVBoOWQA44AAVKOSpuB7lSEhj1tsCBga9BiCMjCMucP0qlIA)
```sh
--parser babylon
```

**Input:**
```jsx
export const FlexBox = styled.div`
	display: flex;
	align-items: center;
	justify-content: center;
	flex-wrap: wrap;
	flex-direction: ${p => p.direction};

	${p => p.stackOnMobile ? `
		${media('<desktop')} {
			flex-direction: column;
		}
	` : ''};
	
	> * {
		width: ${p => (p.howManyPerRow ? `${100 / p.howManyPerRow}%` : 'auto')};
	}
`

```

**Output:**
```jsx
export const FlexBox = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  flex-direction: ${p => p.direction};

  ${p =>
    p.stackOnMobile
      ? `
		${media("<desktop")} {
			flex-direction: column;
		}
	`
      : ""};

  > * {
    width: ${p => (p.howManyPerRow ? `${100 / p.howManyPerRow}%` : "auto")};
  }
`;

```

And that won't be necessary after #5240

**Comment by trusktr** [comment]
@lydell I already provided the above example showing ugly output formatting.

@SimenB's semi tip doesn't work in all the cases.

Honestly I just want to disable this template string formatting, and have a way to opt-in only when I want to.

**Comment by trusktr** [comment]
Arguably Prettier is trying to do too much, and should thus make some things opt-in (or opt-out). The line between formatting code and formatting template strings isn't fully clear.

**Comment by lydell** [comment]
> Is the output formatting in the OP example not ugly to you?

There's a lot of symbols, so my brain quickly zones out and I'm not sure what I'm looking at. Is there a specific part of it you don't like?

> Honestly I just want to disable this template string formatting, and have a way to opt-in only when I want to.

Could you say _why_ you want this? Is it breaking your code? Or is it "just" a bit ugly? Wouldn't you be more interested in fixing thins rather than diabling things?

**Comment by evilebottnawi** [comment]
IMHO, output looks good

@SimenB Looks we ahve good PR to fix it https://github.com/prettier/prettier/pull/5240 [playground](https://deploy-preview-5240--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDEAbdAIQjTwF48SBPSgEwDo2BLANwAMAOlEEweRDOQCGzJHgBmlNAG5hoqeW4BzKAFpu8ALZE5YBPGyqRMAFYBXEt3nNdheLFPm4ltTEXpdAHdsKQw5YNCrUX80XR5sODAYbmg5ABJgDAYAPjwMLm4EpJSoAF8o6wys+lz8kikwAGsAeSgAWQgAI25KPAB+PCFrUQzDOB4pAAoAcgAeNjgiRpgIDGmASlK8YF9RaKU4wsTk1IIIcjtDKCiYUVLffjw5aen7kWtcgCpt3ZhA7jYMAAFulMjk8JN8kCIIE2lIoMwAAreABKMP6gwyAEYAAw4vAAejyHGhsPhSNRMNKAFJHs8pHYVhtyr43vwQAAaECrE7EZCgKTYbAwxGChBEZAgKS8CAAzkgTohJpwGAAZQwDW4UC0yBg2DscC5WqI3hgiJCWkMUmQ8g0Jq5NiIaCoSsaKtVUjGABktXAbXbDSANdgTdhJZ0pJ1WNB5RhsFqYAB1AHA5AADhxXLjEBNiZCGElccW3l4fq5CQAjnYjuapJbrUhbeR7SATYZuLr9YGiFqtJQAIp2CDwf3NwMwSPJwFA5AAJi5eqkPV7AGEIIYrZKoNAyyAHHAACqRiWNgOlUpAA)

**Comment by evilebottnawi** [comment]
Original problem was solved, disable autoformat literal in roadmap for `2.0`
