### ISSUE TITLE
Prettier lint error isn't fixable

### ISSUE THREAD

**Issue by jackiehluo** [prettier/prettier#5281]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAznDABQDWcAngDT4BuAhgDbpwCU+wAOlPvgHoB+ACIBRAGr4AcgHkAKmKT4A6nHzpi+RoUI4A5nwAWcAE7qYEfGHON42-FDgB3fBABGAKzjYiVmEZ2+GIAtu5m1oxQvPxC+Ob6OITwptpQACbxEMzM7oxg5PgB6mCBUPpwhEVWjEw4zIzuzHAAEhDopoQx1tDJRTgh6gC8+LJePjAAdDp6hqTAAL50AUmTFWQA5LiDG+zsANzdkFB9xM3YcOkACmZ4mSMrhGskpBtnE5c3pne7h3z9g0mRnaqRGpGk6DCZlITFYHHwAFJ8ABGABMnAA1PhSO8LtdbhB7iMNlcALIbfAAfhRqPwygADAduo9JsRNts4BtlgMOH9+OYYB0+LC2H8FiAaCAIAAHXC9ZCgRimUwQZxXJUIQjIEC1CA4dISkDuUz5SgwADK0vyOHKyBgpjYkptxFMMCuJv0IUYyFQLGIks8hAAHgAhE0FEjmxiDAAyNrgPr9cElVs6Zm1eXcVGY0EN0u+sBU+oCyAAHPSUyriCoTdLtfnKmZ6AnJeYAI7oHDmd2MT3epC+5j+kDEEI4O0O5Mjm36ZoARXQEHgE8dIBgjSL6RLSFRkvtjHqM4AwhAQl7tZUAKyGzRweSNLUDpMLBZAA)
```sh
--parser babylon
--single-quote
--trailing-comma es5
```

**Input:**
```jsx
function set(key, value) {
  // DEV NOTE: We use assign here to create a new object so that Ember can
  // register and rollback the changes to availableHours
  const time = Object.assign({}, this.get('time'));
  const selectedPeriod = this.get('selectedPeriod');
  time.hour = (Number(value) % 12) + (selectedPeriod == 'PM' ? 12 : 0);
  this.set('time', time);
  return value;
}
```

**Output:**
```jsx
function set(key, value) {
  // DEV NOTE: We use assign here to create a new object so that Ember can
  // register and rollback the changes to availableHours
  const time = Object.assign({}, this.get('time'));
  const selectedPeriod = this.get('selectedPeriod');
  time.hour = (Number(value) % 12) + (selectedPeriod == 'PM' ? 12 : 0);
  this.set('time', time);
  return value;
}

```

**Expected behavior:**

I've been running into a pretty frustrating issue where I keep getting a Prettier error, running the autoformatter doesn't fit it, and then when I fix it manually, I get another error that the original formatting is correct.

Here's the error:

```
30:19  error  Replace `(Number(value)·%·12)` with `Number(value)·%·12`  prettier/prettier
69:19  error  Replace `(time.hour·%·12)` with `time.hour·%·12`          prettier/prettier
```

But when I fix it manually, it shows this error:
```
30:19  error  Replace `Number(value)·%·12` with `(Number(value)·%·12)`  prettier/prettier
69:19  error  Replace `time.hour·%·12` with `(time.hour·%·12)`          prettier/prettier
```

And the autoformatter doesn't notice it at all.

Any thoughts on what I can do? I'm not sure if this issue is in Prettier's domain or if it's an issue with the ESLint plugin.

**Comment by lydell** [comment]
What is the "autoformatter"?

Am I understanding you right that you are both running Prettier some way (which way?) and then ESLint and the two disagreeing with each other? If so, could you show us the exact commands you are using?

**Comment by lydell** [comment]
Or maybe you have an ESLint rule that conflicts with Prettier? See [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)

**Comment by jackiehluo** [comment]
The "autoformatter" just refers to:

```
prettier --write --single-quote --trailing-comma es5 'addon/**/*.js' 'app/**/*.js' 'config/**/*.js' 'tests/**/*.js'
```

I'm using Ember, so ESLint gets run as a part of `ember test`, and ESLint is both disagreeing with Prettier and disagreeing with itself. Running the above Prettier command never shows any formatting issues. Running ESLint shows a Prettier error, and then if I _fix_ the error, it says that my original code was correct and throws a new lint error that contradicts the prior one.

We're already using `eslint-config-prettier`!

**Comment by lydell** [comment]
Ok, thanks!

What you need to do now is to reduce your config. Keep removing stuff until the error goes away, or you're left with the minimal setup to reproduce the problem. Then post all of the files and steps to reproduce here. The easiest way is to make a new repo and put everything there. Let me know if you need any help with any of that!

**Comment by j-f1** [comment]
I think this formatting was changed in a Prettier update. Perhaps you have multiple versions installed somehow?

**Comment by adong** [comment]
@jackiehluo I have a similar issue like yours.

The errors that gave by `ember s` and `ember test` are disagreeing with each other on `prettier`'s config.
