### ISSUE TITLE
Code parses with Flow before formatting, gives Flow syntax error after formatting.

### ISSUE THREAD

**Issue by cristianoc** [prettier/prettier#5283]
See https://github.com/cristianoc/genType/issues/66#issuecomment-431500178.

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ33hIDEBXKMGAS2gHkpGN7oiBBL7Ac0oC2CGEjwAeACoBGADQBDAHwAKAPxyZeJarkBKPAF4FeaTr2HjUg3gBm1Wgyh4A+ks59ZeN7wBMe4AQ58bDgiSgAbfH1jAE8MEIAhAGUAOjIYKhp2FhY2By4efiFYLS9LfSiocLC8FTxqABM4azooOHq8UVKdDS9fAG48YJhKbEdg0Ii8AF8+gB0oEBkQCFyOZFA5bGwIAHcABU2EImQQOQA3CDp6xZAAI2w5MABrOBhEjEeW3mQYbEo4JYtIhwXB7B68ARyZDWORhYFLABWRDQ8Qez1eiTkQgAMi04NDYfCQB9sMDsCdbnJbtEwtAbhhsC0YAB1K4wAAWyAAHAAGJYMiDA5kPDAnBkhEFnfFLYIAR0odGCYLkEKhSBhcIBIGBAjoPz+WqIXzCcAAipQIPACZqljAqaz6hzkN5bQ86GEvgBhCACSEnKDQaUgSjAiRU47qwlwKZTIA)
```sh
--parser babylon
```

**Input:**
```jsx
export const testFunctionOnOptionsAsArgument: <T1,a>(?a, ((?a) => T1)) => T1 = function _(Arg1, Arg2) { const result = TypesBS.testFunctionOnOptionsAsArgument((Arg1 == null ? undefined : Arg1), Arg2); return result };

```

**Output:**
```jsx
export const testFunctionOnOptionsAsArgument: <T1, a>(
  ?a,
  (?a) => T1
) => T1 = function _(Arg1, Arg2) {
  const result = TypesBS.testFunctionOnOptionsAsArgument(
    Arg1 == null ? undefined : Arg1,
    Arg2
  );
  return result;
};

```

**Expected behavior:**
`[flow] Unexpected token (`
on Flow version 0.83.0.

**Comment by cristianoc** [comment]
This is at the Flow/Prettier interface, not sure which one is to blame.

**Comment by lydell** [comment]
Babylon fails to parse the output too:

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ33hIDEBXKMGAS2gHkpGN7oiBBL7Ac0oC2CGEjwAeACoBGADQBDAHwAKAPxyZeJarkBKPAF4FeaTr2HjUg3gBm1Wgyh4A+ks59ZeN7wBMe4AQ58bDgiSgAbfH1jAE8MEIAhAGUAOjIYKhp2FhY2By4efiFYLS9LfSiocLC8FTxqABM4azooOHq8UVKdDS9fAG48YJhKbEdg0Ii8AF8+gB0oEBkQCFyOZFA5bGwIAHcABU2EImQQOQA3CDp6xZAAI2w5MABrOBhEjEeW3mQYbEo4JYtIhwXB7B68ARyZDWORhYFLABWRDQ8Qez1eiTkQgAMi04NDYfCQB9sMDsCdbnJbtEwtAbhhsC0YAB1K4wAAWyAAHAAGJYMiDA5kPDAnBkhEFnfFLYIAR0odGCYLkEKhSBhcIBIGBAjoPz+WqIXzCcAAipQIPACZqljAqaz6hzkN5bQ86GEvgBhCACSEnKDQaUgSjAiRU47qwlwKZTIA)
```sh
--parser babylon
```

**Input:**
```jsx
export const testFunctionOnOptionsAsArgument: <T1,a>(?a, ((?a) => T1)) => T1 = function _(Arg1, Arg2) { const result = TypesBS.testFunctionOnOptionsAsArgument((Arg1 == null ? undefined : Arg1), Arg2); return result };

```

**Output:**
```jsx
export const testFunctionOnOptionsAsArgument: <T1, a>(
  ?a,
  (?a) => T1
) => T1 = function _(Arg1, Arg2) {
  const result = TypesBS.testFunctionOnOptionsAsArgument(
    Arg1 == null ? undefined : Arg1,
    Arg2
  );
  return result;
};

```

**Second Output:**
```jsx
SyntaxError: Unexpected token (3:3)
  1 | export const testFunctionOnOptionsAsArgument: <T1, a>(
  2 |   ?a,
> 3 |   (?a) => T1
    |   ^
  4 | ) => T1 = function _(Arg1, Arg2) {
  5 |   const result = TypesBS.testFunctionOnOptionsAsArgument(
  6 |     Arg1 == null ? undefined : Arg1,
```

**Comment by thorn0** [comment]
A minimal repro.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAzJmA8AggHwAUmppA-IQJSYC8xmAQvfU6wNwgA0IEAA4wAltADOyUAEMATrIgB3AApyEklNIBuEEQBM+IAEazpYANYYAyoLMioAc2QxZAVzj8AFjAC2qAOqeIvDitmBwVurBIlrBAJ7I4OKS-PbicLIwyqYOPtLI2NKo6fwAVuIAHiymFtbSPnAAMvZwBUUlIOUVVvYO6ACKrhDwbcUeILay6bKJ2KhKhoKy9jD++jCeyAAcAAz8SxDp-qaCiUtw01qt-ACOQ-DZQhog0uIAtFBwcHrfhrJwdxE-2y0ly+SQhTG-HSPhEzjc43EvQG91aEPa4xg0iMaz0G2QACZ+C5pCJUL0AMIQHx5RJQaDXECudIAFWxGkhHS07gAklAfrArGBlsJCPyrDA4uhRukAL6yoA)
```sh
--arrow-parens avoid
--parser flow
--trailing-comma none
```

**Input:**
```jsx
let f: <A>( ((?A) => B) ) => B;
```

**Output:**
```jsx
let f: <A>((?A) => B) => B;

```

**Second Output:**
```jsx
SyntaxError: Unexpected token `(`, expected an identifier (1:12)
> 1 | let f: <A>((?A) => B) => B;
    |            ^
  2 | 
```
