### ISSUE TITLE
Prettier throws on MDX files with fenced code blocks

### ISSUE THREAD

**Issue by pmrcunha** [prettier/prettier#5284]
**Environments:**
- Prettier Version: dev
- Running Prettier via: CLI
- Runtime:  Node.js v10.6
- Operating System: Windows

**Steps to reproduce:**
1. Use a fenced code block in an MDX file, with JSX in it
      
```  
```js
<Component>Hello</Component>
` ``
 ```

2. Run prettier with `-l` or `--write`

**Expected behavior:**
I'm not sure if fenced code blocks are supposed to be supported by MDX (since it is extended syntax), but they usually work. 
If supported, Prettier should be able to format the JS/JSX inside the fenced code block.
If not, it should output a meaningful error message.

**Actual behavior:**
Running one time, Prettier throws when parsing the MDX file:
```
> prettier "**/*.+(js|ts|json|yml|yaml|md|mdx)" "-l"

[error] src\components\Alert\README.mdx: TypeError: Cannot read property '0' of null
[error]     at getFencedCodeBlockValue (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\language-markdown\utils.js:156:45)
[error]     at Object.genericPrint [as print] (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\language-markdown\printer-markdown.js:231:11)
[error]     at genericPrint (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\main\ast-to-doc.js:103:18)
[error]     at comments.printComments.p (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\main\ast-to-doc.js:40:14)
[error]     at Object.printComments (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\main\comments.js:480:19)
[error]     at printGenerically (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\main\ast-to-doc.js:38:22)
[error]     at FastPath.call (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\common\fast-path.js:68:18)
[error]     at processor (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\language-markdown\printer-markdown.js:676:24)
[error]     at path.map (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\language-markdown\printer-markdown.js:695:20)
[error]     at FastPath.map (C:\Users\paulo\Documents\reps\pmrcunha-components\node_modules\prettier\src\common\fast-path.js:122:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```
If I save the file and run Prettier again, it won't error, but it will duplicate the formatting transformations, i.e. where Prettier introduced one line break, there will now be 2 line breaks. In the next run it errors, then it introduces 3 line breaks and so on.

I get the same result with ` ```js`, ` ```jsx`, and ` ``` ` code blocks.

Thank you for building Prettier! 😃

**Comment by ikatyang** [comment]
Hi, I'm not able to reproduce the issue. Here's how I tried:

```sh
mkdir prettier-5284
cd prettier-5284
yarn init -y
yarn add prettier/prettier#d1d1f1715748cecb13a59e3fe1a659ad8ebc00d2
echo "\`\`\`js
<Component>Hello</Component>
\` \`\`" | node_modules/prettier/bin/prettier.js --parser mdx
```

````md
```js
<Component>Hello</Component>
` ``
```
````

**Comment by pmrcunha** [comment]
Ok, it looks like the issue was on my side.
VSCode switched the end of line sequence from LF to CRLF in this particular file, which led to the error above. Switching it back to LF solved the problem.

Thank you for your time!
