### ISSUE TITLE
Preserve quoted access (for Closure Compiler)

### ISSUE THREAD

**Issue by pauldraper** [prettier/prettier#5289]
The Closure Compiler is the [most](https://www.peterbe.com/plog/advanced-closure-compiler-vs-uglifyjs2) [effective](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/) JS minifier, and one of the oldest (developed in 2009 for Gmail, Google Docs, etc.). It is also a [point of focus](https://medium.com/@Jakeherringbone/what-angular-is-doing-with-bazel-and-closure-21f526f64a34) for the Angular team.

It would be great if prettier was compatible with Closure Compiler.

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB3AllAJhVA6MAQwBtiAjQsAawApgByAWwE8q5n6kACANxIFc4AXwCUAbgA6UEABoQEAA4x00AM7JQhAE5bcABW0J1KQjwjosskGS2U2MAMoLKmAObIYWwXMyq4WmD1bV0ZCZAAzEj85ACtVAA8AIVtqOEdCRjgAGUw4CKi4OWctPy1ka0IyZmJoKwUtTBgAdQsYAAtkAA4ABiLdPybbBXL6uFKePLktOABHfnRpoMIQsKRI4miQP0Z0Dy9CrbdiOABFfgh4fI2DmEqWrHbkACY5T0J0YjcAYQhGUPKoNBJiB+H4ACqVYzrPxCIRAA)
```sh
--parser babylon
```

**Input:**
```jsx
window.callback({'mykey': value});

```

**Output:**
```jsx
window.callback({ mykey: value });

```

**Expected behavior:**

I want to maintain the quotes around key.

The [Closure Compiler](https://github.com/google/closure-compiler) is a minifier that uses quoted vs unquoted access to determine which properties to rename.

The former input results in a compiled result of

```js
myfunction({mykey:value});

// Closure preserves value of mykey
```

while the later results in

```js
myfunction({a:value});

// Closure renames all instances of mykey properties to a
```

[Example](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Amyfunction(%257B%2520mykey%253A%2520value%2520%257D)%253B%250A)

[Documentation](https://developers.google.com/closure/compiler/docs/limitations#implications-of-global-variable-function-and-property-renaming)

The difference can break things; e.g. if myfunction sent the value as JSON to a server which expect mykey.

A `preserveQuoted` flag to preserve quoted properties would fix this.

Note that this is not a matter of preference, but a matter of interoperability with one of the longest-lived and most popular JS tools.

**Comment by pauldraper** [comment]
Hm, apparently, there is a similar issue #1103 #4327

> Closure Compiler with Advanced Mode is barely used in practice. 

It would appear not. :/

**Comment by j-f1** [comment]
In #4327, it was suggested to wrap the quotes in brackets:

```js
window.callback({['mykey']: value});
```

Closing since this is a duplicate, but feel free to discuss.
