### ISSUE TITLE
idea: "preferIndentation" option.

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#5293]
When this option is `true`, Prettier will _not_ try to fit as much as it can on a line, and always make indent blocks. The only except is function arguments. If they fit on the same line, it puts them on the same line, but it will otherwise always indent if, while, for, etc so that they never fit the whole statement on the same line.

**Comment by trusktr** [comment]
Maybe it could be called `alwaysIndent`. Would it be a good option?

If it was added, would it then be fine to make the line length configurable (f.e. more than 80)?

**Comment by lydell** [comment]
Can you post some real-world code where you'd like to use this formatting?
