### ISSUE TITLE
Bug: text-align is not working in markdown table with chinese

### ISSUE THREAD

**Issue by imcuttle** [prettier/prettier#5298]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABIIeVAOpuv6NAX6MDgzfM8iyq6m2u+hxjQbx9Bo9UY4IB0oMBaAYL4F0QseImSp0mbLnyF4kYpUDuvdAAMANgEsoAa014MgejNAZCqAKdUCn0YHVtQK3WgKDlAfGaAuT0D+8oApXQKGxgP5TApcaAEP-oAMIAtgAm6ADU6IBnuoB0qeiAz7GANvGAz4HoumAAhgBmcOiAkP8ANOiAyvqAviqAJ3KAMhGAvdqAZXqA5JqAcXLoAIwALAAM6IBvpoAw-9aA+UqAvwGAskaAAPqA9CqA2P+A8Dqt-YCYCoCQ5oDhpoA05oBGxrXoAEYArgDmIpoHEBDacDlQxpzUqDwYmgDuD-gYdvaAIW6AAObNJrNBaDbyAL8VPOgAOQAOnh0PQgGW-QB8OoNAEGaWgAzD0AKTGQBoRoBQAK0HR6PU+jyp1POUCOYQOcAATqgAM4wJn6E6UzjPDSaHJ6E73EQ-X6AFhtAM56gE-tQAK+YARyMAmEo0lWqtW0V7Qm55GDQ4wAeQASlpoZyTgALXUG42aaFgBDwJl6gggEogCAABxgumgrOQoByTKZEDeAAVAwg-SgcgA3CC6CKukAHJk5MAGOAwADKHrTXOQHKOcDd+lZzJgodTJzCOWQeUFZbdACtWQAPABCqfTmazOTCcAAMvo4HWG8WQLmmWWmcgQDWmQYIiGoEmPZzYAB1BMwc3IAAcPTda4gZY3qY9s7XcGnMZHbqZcAAjkddA-Kzlq7WkPXtI2QGWwl0AsmSLN1WS5G4AEUjggeBR1-ccYByA4twiHdkAAJjdDkcl0PQoBOEIIDCGtZygaA7xAI4ywAFWQqMfzLABfJigA)
```sh
--parser markdown
```

**Input:**
```markdown
| 参数    | 说明                                                                                                                     | 类型                                |
| ------- | ------------------------------------------------------------------------------------------------------------------------ | ----------------------------------- |
| `link`  | 是否在该字段上显示使用超链接（ Cmd + 左键 跳转至 icafe ）, 当命令行宽度大于 140 时，该功能才开启；小于时候有文本换行 bug | `boolean`                           |
| `w`     | 该字段的最大宽度大小，超出用 '...' 结尾，如 `30%` 或者 `100`                                                             | `number|string`                     |
| `align` | 该字段的水平对齐规则                                                                                                     | `'left'` OR `'right'` OR `'center'` |
```

**Output:**
```markdown
| 参数    | 说明                                                                                                                     | 类型                                |
| ------- | ------------------------------------------------------------------------------------------------------------------------ | ----------------------------------- |
| `link`  | 是否在该字段上显示使用超链接（ Cmd + 左键 跳转至 icafe ）, 当命令行宽度大于 140 时，该功能才开启；小于时候有文本换行 bug | `boolean`                           |
| `w`     | 该字段的最大宽度大小，超出用 '...' 结尾，如 `30%` 或者 `100`                                                             | `number|string`                     |
| `align` | 该字段的水平对齐规则                                                                                                     | `'left'` OR `'right'` OR `'center'` |

```

**Expected behavior:**

**Comment by imcuttle** [comment]
I have changed font to monospaced on ide (WebStorm), but not works.
![image](https://user-images.githubusercontent.com/13509258/47500512-9537f800-d895-11e8-86f3-770ab5f23795.png)


@ikatyang  Are you tried in browser?

**Comment by ikatyang** [comment]
It only works if you manually specify the Chinese monospaced font:

![image](https://user-images.githubusercontent.com/8341033/47500638-e6e08280-d895-11e8-9f21-b9a8a8641e1f.png)

**Comment by imcuttle** [comment]
Does it only works for Chinese monospaced font now?

**Comment by imcuttle** [comment]
I got it, Thanks @ikatyang  👍
