### ISSUE TITLE
Bug running Prettier Playground locally: Web Workers Fail to Import lib Scripts

### ISSUE THREAD

**Issue by beausmith** [prettier/prettier#5302]
## Environments
- Prettier Version: n/a (or 1234ceb) 
- Running Prettier Playground via: `yarn start`
- Runtime: Node.js v9.11.2, Chrome v69.0.3497.100
- Operating System: macOS

## Steps to reproduce:
To get Prettier Playground running locally, I followed the [docs](https://github.com/prettier/prettier/blob/master/website/README.md) and in the prettier/website dir I ran:

    yarn
    yarn start

## Expected behavior:

Playground works without any errors. Web worker imports defined scripts.

## Actual behavior:

The server starts and the site opens in my browser and I navigated to the playground, but there was something wrong with the web workers not being able to download the "lib" files. 

![prettier-playground-worker-error](https://user-images.githubusercontent.com/28444/47523372-b9231b80-d84c-11e8-8871-ae1ccd650b50.png)

The issues seem to be with `importScripts()` in the worker files:

- https://github.com/prettier/prettier/blob/master/website/static/worker.js
- https://github.com/prettier/prettier/blob/master/website/static/service-worker.js

To get it to run, I hacked by manually downloading and adding these files:

    prettier/website/static/lib/parser-babylon.js
    prettier/website/static/lib/standalone.js

**Can you help me understand what is going wrong so that this error can be fixed?** I'd love to be able to get this all worked out.

**Comment by j-f1** [comment]
Does `yarn build` fix the issue?

**Comment by ikatyang** [comment]
Actually, `yarn build` is for bundling, `yarn build-docs` should be what you're looking for. (Set `PULL_REQUEST=true` if you'd like to build the master one.)

**Comment by beausmith** [comment]
Thanks @ikatyang. I've created a PR containing your tip so that others can benefit!
