### ISSUE TITLE
Consider support asterisks as markdown unordered list style, again? 

### ISSUE THREAD

**Issue by linesh-simplicity** [prettier/prettier#5308]
I'm wondering if it's still possible to get asterisks back as markdown unordered list style, like origin text inferring and leaving an option of this(I suggest this not the prettier way)? Would love to have it back, cause using asterisk basically saves the distance to move when typing(or perhaps it's just me).

I've read these two issues happened and locked now about how we would like to format Markdown unordered list, asterisk or hyphen. I feel like asterisk fits me as it feels easier to type, but leaving those personal preferences and opinions behind, I was wondering if Prettier would also be opinionated on this style for a markdown file? Is it still under consideration to get it back and make a room to leave for both? 

* https://github.com/prettier/prettier/issues/4251
* https://github.com/prettier/prettier/issues/3025

**Comment by j-f1** [comment]
> I'm wondering if it's still possible to get asterisks back as markdown unordered list style, like origin text inferring and leaving an option of this(I suggest this not the prettier way)? Would love to have it back, cause using asterisk basically saves the distance to move when typing(or perhaps it's just me).

IMO `-` is easier since you don’t have to hold down shift.

> I've read these two issues happened and locked now about how we would like to format Markdown unordered list, asterisk or hyphen. I feel like asterisk fits me as it feels easier to type, but leaving those personal preferences and opinions behind, I was wondering if Prettier would also be opinionated on this style for a markdown file? Is it still under consideration to get it back and make a room to leave for both?

Prettier is opinionated for all languages. This doesn’t seem like a big problem since you can still create lists with any delimiter and Prettier will switch them to `-`. Most editors should have a plugin that extends the list’s delimiter when you hit enter.

**Comment by linesh-simplicity** [comment]
Well, I need to move my wrist up and stretch the little finger to get to `-` and then get back, which I feel uncomfortable, but with `*` your wrist doesn't need to move. But yeah that's personal.

About the auto-switching, I utilise WebStorm as my markdown editor and prettier is run for every save. Unfortunately as far as I know WebStorm(nor any plugins) doesn't extend the list's delimiter when I hit enter. I installed a global prettier 1.12 version(the last version that hyphen style has not been introduced as default) for markdown formatting as an alternative for now. 

Would be good if this can be solved in prettier end with respect to my list styles, but I guess that also makes other people unhappy. Prettier's been working quite good across all projects I've been through for code, but this one breaks my writing experience a little.

**Comment by ikatyang** [comment]
[I'm not going to be non-normal, again.](https://twitter.com/wangcheng678/status/1004311521948680192)

**Comment by linesh-simplicity** [comment]
这个地图炮开得好啊。

Well if a twit can make you change your mind ...
