### ISSUE TITLE
Arrow Function Parentheses option is incompatible with ESLint

### ISSUE THREAD

**Issue by miraage** [prettier/prettier#5309]
We use both ESLint and Prettier. 
ESLint is configured as `[2, "as-needed", { "requireForBlockBody": true }]`.

There are tons of developers who follows Airbnb JS codestyle, which recommends exactly this configuration.

How can we configure Prettier to avoid mangling our codebase? Is there any chance to provide an option to either disable this behavior or make it compatible with ESLint?

**Comment by j-f1** [comment]
We don’t have such an option and we likely won’t be providing it: https://prettier.io/docs/en/option-philosophy.html

However, you can use `eslint-plugin-prettier` to override AirBnB’s style guide.

**Comment by miraage** [comment]
@j-f1 I believe it's possible just not to run this transformation by providing smth like "disabled" option.

**Comment by lydell** [comment]
https://prettier.io/docs/en/eslint.html

**Comment by ivanguimam** [comment]
Sad the prettier not be compatible with Airbnb

**Comment by aboyton** [comment]
Actually I believe that Airbnb are planning on changing to always require parens. https://github.com/airbnb/javascript/pull/1863
