### ISSUE TITLE
NodeJS API: Changes to .js config not being picked up due to NodeJS module caching

### ISSUE THREAD

**Issue by undeadcat** [prettier/prettier#5311]
**Environments:**
- Prettier Version: **1.14.1 and above**
- Running Prettier via: Node.js API 
- Runtime: Any Node.js version
- Operating System: Any OS

**Steps to reproduce:**
This is reproducible via any Prettier editor integration, e.g. [prettier-vscode](https://github.com/prettier/prettier-vscode) or [Intellij prettier plugin](https://plugins.jetbrains.com/plugin/10456-prettier):

* Create a .prettierrc.js config file with, for example, a specified tab size:
```
module.exports = {
  tabWidth: 7
}
```
* Invoke 'Reformat Code' from the editor. File is reformatted according to .prettierrc correctly
* Modify .prettierrc.js, for example, changing `tabWidth` to 2
* Make sure the editor persists changes to the config file to disk
* Invoke 'Reformat Code' again

**Expected behavior:**
File is reformatted with the new tabWidth (2).
**Actual behavior:**
File is reformatted with the previous tabWidth (7), until the editor is restarted. After that the file is reformatted with new settings.

With `prettier` version **1.13.7** the changes to the file are picked up correctly.
Same with .json or .yaml config files - changes are picked up immediately after changing the config file.

This seems to be caused by the fact that Node.js `require` [caches the loaded modules](https://nodejs.org/api/modules.html#modules_caching) for the duration of the process. Editor integrations usually create a long-running process that then invokes 'reformat' multiple times, so if the config is read via `require`, subsequent attempts to read it will return the same result.
Prettier updated `cosmiconfig` to version 5 [here, in 1.14.1](https://github.com/prettier/prettier/commit/440ab4f60b7e7c4fe80565b65929a1a9534de86d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). 
Cosmiconfig replaced `require-from-string` with plain `require` [here](https://github.com/davidtheclark/cosmiconfig/commit/0143e84934d0f425af81327c12ebd1fb2eaad6c7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). 
`require-from-string` [had the side effect of not caching the loaded modules](https://github.com/floatdrop/require-from-string/issues/13#issuecomment-360775277).
ESLint had a similar issue in the past: https://github.com/eslint/eslint/issues/5067 and addressed it by using `require-uncached`. 

Even though this mostly affects editor integrations, I believe this should be addressed in `prettier` itself (or possibly in `cosmiconfig`), and *not in editor integrations* because:
* `prettier` picks up changes correctly for *.json or *.yaml files
* every editor integration would have to work around this issue, instead of only once.

**Comment by undeadcat** [comment]
Just in case, a repro using only the Node.js API, without an editor integration.

.prettierrc.js:
```
module.exports = {
  tabWidth: 7
}
```
package.json:
```
{
  "version": "1.0.0",
  "devDependencies": {
    "prettier": "1.14.1"
  }
}
```
test.js:
```js
var fs = require('fs');
var path = require('path');
var prettier = require('prettier');

var configFilePath = path.join(__dirname, '.prettierrc.js');
console.log('Before: ' + prettier.resolveConfig.sync(__filename, {useCache: false}).tabWidth); //expect 7

var fileOptions = {encoding: 'utf8'};
let previousContent = fs.readFileSync(configFilePath, fileOptions);

try {
  fs.writeFileSync(configFilePath, "module.exports = {tabWidth:2}", fileOptions);
  prettier.clearConfigCache();
  //expect 2
  console.log('After: ' + prettier.resolveConfig.sync(__filename, {useCache: false}).tabWidth);


} finally {
  //restore previous content just to make this script repeatable locally.
  fs.writeFileSync(configFilePath, previousContent, fileOptions);
}
```
With 1.14.1 this prints: 
```
Before: 7
After: 7
```
With 1.13.7:
```
Before: 7
After: 2
```

**Comment by ikatyang** [comment]
I believe the fix should be in [`cosmiconfig/src/loaders#L7-L10`](https://github.com/davidtheclark/cosmiconfig/blob/5.0.6/src/loaders.js#L7-L10). Could you open an issue there?

**Comment by ikatyang** [comment]
The fix is available in [`cosmiconfig@5.0.7`](https://github.com/davidtheclark/cosmiconfig/blob/master/CHANGELOG.md#507), we just needs to update and add some tests. PRs welcome.

**Comment by wuweiweiwu** [comment]
I can pick this up!

**Comment by ikatyang** [comment]
👍 Go ahead!

**Comment by ikatyang** [comment]
I guess we could:

1. use [`tempy`](https://github.com/sindresorhus/tempy) to create a js config file.
2. `prettier.resolveConfig(filename, { config: configFilename })`
3. override some configs
4. `prettier.clearConfigCache()`
5. `prettier.resolveConfig(filename, { config: configFilename })` again and see if the result changed

The test should be added to https://github.com/prettier/prettier/blob/master/tests_integration/__tests__/config-resolution.js.

**Comment by wuweiweiwu** [comment]
@ikatyang sounds good! thanks ill have a PR out tonight

**Comment by wuweiweiwu** [comment]
Created the PR. but the test that I created seem to fail still. Seems cosmic config 5.0.7 update doesn't work for us
