### ISSUE TITLE
-l option fails in less files with regular comments in them

### ISSUE THREAD

**Issue by alexw10** [prettier/prettier#5313]
**Environments:**
- Prettier Version: 1.14.3
- Running Prettier via: CLI
- Runtime: Node 10.9.0
- Operating System: macOS

**Steps to reproduce:**
prettier -l src/**/*.less

If you have a less file with regular comments in it such as:
```
@import 'theme-variables';

// body

body {
  background-color: @body-background-color;
  font-family: @base-font-family;
  color: @body-text-color;
}
```
This will fail the -l option but if you run -fix it does not do anything with it.

**Expected behavior:**
It should either fix something with the `// comment` line or it should not fail the -l option in this scenario

**Actual behavior:**
Fails the -l option even though it can't fix anything.
Does not seem to always happen but this scenario I have above it does it with it so not sure what the reasoning is.

**Comment by lydell** [comment]
Hi!

>  you run -fix it does not do anything with it.

Prettier does not have a `-fix` flag. Did you mean `--write`?

I tried to reproduce your problem, but failed:

```
~/stuff/prettier-less master 
❯ prettier --version
1.14.3

~/stuff/prettier-less master 
❯ prettier -l 'src/**/*.less'
src/test.less

~/stuff/prettier-less master 
❯ prettier --write 'src/**/*.less'
src/test.less 71ms

~/stuff/prettier-less master * 
❯ prettier -l 'src/**/*.less'

~/stuff/prettier-less master * 
❯ git diff
diff --git a/src/test.less b/src/test.less
index eaed485..9b4d2a1 100644
--- a/src/test.less
+++ b/src/test.less
@@ -1,4 +1,4 @@
-@import 'theme-variables';
+@import "theme-variables";
 
 // body
 
@@ -6,4 +6,4 @@ body {
   background-color: @body-background-color;
   font-family: @base-font-family;
   color: @body-text-color;
-}
\ No newline at end of file
+}

```

**Comment by alexw10** [comment]
Going to close this, not sure what was going on but I can't reproduce it now either.
