### ISSUE TITLE
1.15.0-dev LESS formatting bug

### ISSUE THREAD

**Issue by alexw10** [prettier/prettier#5315]
I think I found a bug in 1.15 with LESS formatting, this does not happen in 1.14.3
```
npm install -g ikatyang/prettier#feat/html/todos
```
```
➜  ~/projects/ClinicianSite prettier -v
1.15.0-dev
```

Less file is this:
```
@import 'theme-variables';

// body

body {
  background-color: @body-background-color;
  font-family: @base-font-family;
  color: @body-text-color;
}
```

Run --write on less file:
```
➜  ~/projects/ClinicianSite prettier --write ~/projects/ClinicianSite/src/styles/theme.less
src/styles/theme.less 169ms
```

Should now pass the -l option but does not:
```
➜  ~/projects/ClinicianSite prettier -l ~/projects/ClinicianSite/src/styles/theme.less
src/styles/theme.less
```

Also, something I observed is everytime I run the --write it adds a new line under the comment `// body`. If I remove the comment `// body` it then passes. So it seems to have something to do with comments in less files that it is not handling this properly right now.

**Comment by lydell** [comment]
Hi! I tried to reproduce this, and failed :(

https://github.com/lydell/prettier-less-issue

Am I missing something? @j-f1 Were you able to reproduce since you added the lables?

**Comment by alexw10** [comment]
I will clone your project quick and see if I can get it to in my environment, I like triple confirmed this before making the issue so I am going to be sad if it doesn't occur again for some reason ha.

**Comment by alexw10** [comment]
Ah I see! it happens if the file line endings are CRLF in VSC if you make sure your line endings in the bottom right are CRLF you will see this occurring.
![image](https://user-images.githubusercontent.com/9453636/47745947-e9a2f500-dc52-11e8-891e-cb6b090aac85.png)

**Comment by lydell** [comment]
Thanks! Confirmed, it happens with CRLF. And not on 1.14.3.
