### ISSUE TITLE
Adds Space Before and After Angle Brackets of Tags in JSX only

### ISSUE THREAD

**Issue by Behseini** [prettier/prettier#5319]
I am trying to prettify a jsx file after save but Preetie adding space between `<>`. for example the `<p>` changes to `< p >`  and this is raising issue on jsx

```
const elem = <h1> Hello React </h1>;
    console.log(elem);
```

```
const elem = < h1 > Hello React < /h1>;
console.log(elem);
```

can you please let me know how to fix this

**Comment by lydell** [comment]
My guess: You're using VSCode and it does something?

**Comment by ikatyang** [comment]
https://github.com/prettier/prettier-vscode#installation

> ⚠ A word of warning-if you have any other code formatting extensions installed such as for example hugely popular `HookyQR.beautify` or `taichi.react-beautify` they might take precedence and format your code instead of Prettier leading to unexpected results.

**Comment by Behseini** [comment]
Thank you all for reply and you are right I am using the Prettier with VS Code. The point is when ever I uninstall the prettier everything works fine but with this this error happening.

**Comment by lydell** [comment]
I think you'll get better help asking in some VS Code community. This repo is for Prettier core. I hope you'll figure it out!
