### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by chavab1** [prettier/prettier#5325]
I'm trying to use in conjunction with JSPrettier. I installed Prettier and then JSPrettier, per the instructions. When I run the prettify command I get the following error:

`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`

`SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Process finished with exit code 1`

I'm running it on Windows. I installed Prettier globally using NPM. And I'm running Node V 8.9.4

**Comment by lydell** [comment]
Hi! The first step to debug this kind of issues is to see if Prettier works outside your editor. What happens if you try prettier from the command line?

**Comment by chavab1** [comment]
Thanx for the reply @lydell.

I tried running it on the command line but nothing happens. I ran it without any arguments, just to see the options, but nothing comes back. No error message or anything.

Is there somewhere I can see the logs??

**Comment by lydell** [comment]
You could start with telling us what you do.

**Comment by chavab1** [comment]
As far as running it through the JSPrettier plugin, I just ran the default command (`right click->JSPrettier`) with the console open.

On the command line I just typed `prettier`, with no arguments, to view the options available. As I said, nothing happens. I don't get any feedback at all.

I haven't done anything else. I haven't changed any default settings or files.

**Comment by lydell** [comment]
To be able to type just `prettier` on the command line, `prettier` needs to be in you `$PATH`. It's really weird that you got no feedback at all when doing that. Your shell should at least have complained that `prettier` does not exist.

If `prettier` is in your path depends on your OS, how you've configured it, how you installed Prettier (global vs local), which directory you're in, which shell you use, etc. This isn't Prettier specific. I'd advise you to read up on that. `npx prettier` is a pretty safe bet, though.

Once you've been able to run Prettier, or any npm package with a CLI, from the command line – let us know and we'll continue the debugging!

**Comment by chavab1** [comment]
Yeah, I checked the `$PATH` when I initially discovered the problem using it through Sublime. I added the path manually in the JSPrettier configuration file.

I don't think that's the issue. I use Grunt (a node task manager) almost every day and it was installed the exact same way (globally). Besides, wouldn't I get a message stating that the `prettier` command was not found?

**Comment by lydell** [comment]
Ok, thanks for the extra info. Can you provide:

- Operating system
- Node version
- npm version
- The exact command you used to install Prettier

Then we can try to reproduce!

**Comment by lydell** [comment]
Cool! Unfortunately, I don't have a Windows machine to test on, so we'll have to wait for somebody else to help. Adding the "awaiting response" label for that reason.
