### ISSUE TITLE
Negating an if clause, requires it to be wrapped in additional parentheses.

### ISSUE THREAD

**Issue by smeijer** [prettier/prettier#5326]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAbgIYA2OAJsfABTEBO9AlPsADpT746r4CENAIKNiATwB0OAM7D6YuoxYAyJfgX1xpBAHMYAC3wBeY-gDM+AD4X8DDVqi6Dxw-gCsTFu05d89ODHR6TlQyKTgAbg4uAF8OKN9-QM4YenQIjlioDhJyKloAbQAGABp8AEZSgCYAXSZIqBBikAgAB1xoKWRQWwgAdwAFBgROlGJCCEpGkAAjOTAAa38AZRbiMBwHZBS0po2w+hh+uW0AW2JkENIwpoArKQAPACE5xZgl4hO4ABkNuAvQuBNVb0fbIGbEaaiUjQKYtegbGAAdUo+mQAA4SiA4RAwoi5C0wXC4PtCH8mn4AI7oHB+I7EU7nJCXa4gMInHBbVKA1kbbRaACK6Ag8H+V25MAhyIoqKQlSaKWIOHIDgAwhATmcwVBoGSQOgwgAVCEjZlwaLRIA)
```sh
--parser babylon
```

**Input:**
```jsx
function validate(arr) {
  if !(Array.isArray(arr) && (arr.length === 3 || arr.length === 5)) {
    return false;
  }

  return true;
}

validate([0, 1, 2]);
```

**Output:**
```jsx
SyntaxError: Unexpected token, expected "(" (2:6)
  1 | function validate(arr) {
> 2 |   if !(Array.isArray(arr) && (arr.length === 3 || arr.length === 5)) {
    |      ^
  3 |     return false;
  4 |   }
  5 | 
```

**Expected behavior:**
I would say the input is much more readable than the suggested output:

```jsx
function validate(arr) {
  if (!(Array.isArray(arr) && (arr.length === 3 || arr.length === 5))) {
    return false;
  }

  return true;
}

validate([0, 1, 2]);
```

This gets emphasized when the if clause gets longer:
```jsx
function validate(arr) {
  if !(
    Array.isArray(arr) &&
    (arr.length === 3 || arr.length === 5 || arr.length === 7)
  ) {
    return false;
  }

  return true;
}
```

vs prettified

```jsx
function validate(arr) {
  if (
    !(
      Array.isArray(arr) &&
      (arr.length === 3 || arr.length === 5 || arr.length === 7)
    )
  ) {
    return false;
  }

  return true;
}
```

**Suggestion**

Prettify 
```js
if (!(Array.isArray(arr) && (arr.length === 3 || arr.length === 5))) {
```

to 

```js
if !(Array.isArray(arr) && (arr.length === 3 || arr.length === 5)) {
```

Remove the wrapping parens. `!( ... )` vs `(!( ... ))`.

**Comment by lydell** [comment]
Hi! I agree the following looks pretty nice, but unfortunately it is not valid JavaScript.

```
if !(foo) {
  return false;
}
```

Prettier only deals with valid JavaScript, so there’s nothing we can do here!

**Comment by j-f1** [comment]
@lydell Feel free to use the `invalid` label however you want, but I created it to label invalid Hacktoberfest PRs so they wouldn’t count for the T-shirt.

**Comment by smeijer** [comment]
**OMG**, you have no idea how stupid this makes me feel. 

Well, let's migrate the issue to the [tc39](https://github.com/tc39) then. 😇
