### ISSUE TITLE
presence / absence of parens

### ISSUE THREAD

**Issue by lazex** [prettier/prettier#5329]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEYCGa4CMmAvJjpgGQWYBGmAPvdpdQCYA6UkUG2ecAJhKYA7pgD8mAB6YkmABQBPFpgBeASk4gANCAgAHGAEt0yUDgBOFiCIAKlhGmQgcANwhHWOkDQs4wANZwMADK+v5GUADmyDAWAK5wupH4FjC2flEAtjjIAGY4ADb4ugBWaFIAQn6BwSE4WXAAMpFw+UUlIOEWqc40ODSKhdDe+haRMADqnjAAFsgAHAAMumMQ+JN++s5jcKmubboWcACO8UbHGTjZuUgFxUkg+FlGsQmPaJFRhXAAivEQeDtB66GADaasObIASgvxGQpfADCECyOWcUGghxA8XwABUBk47h04ABfElAA)

**Input:**
```js
const case1 = a && b || c && d
const case2 = w ? x : (y && z)
```

**Output:**
```js
const case1 = (a && b) || (c && d);
const case2 = w ? x : y && z;
```

**Expected behavior:**

In case1, parens are added.
In case2, parens are removed.

I think prettier should unify behavior or keep presence / absence of parens.

**Comment by evilebottnawi** [comment]
@lazex prettier search way how better format for readability, it is not tool for `unify` behaviour, in second case parens is unnecessary and we do not want to add parens just for `unify`
