### ISSUE TITLE
Regression: trailing char is moved to the next line as leading char

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#5336]
**Prettier pr-5006**
[Playground link](https://deploy-preview-5006--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAbOMAEBbAngEQEsA3TAXkwCU4BDMGAFTgGcYBVGQ1ZgOgCcEAEzh8AkrAj4IYAK7YEMABQAdKJkwAeQSQB8q9eq0lMAazi4yykDAAWcKQHMrmMKhrNmAORrzLIQRBOIJgA9DoANPoGRqRmFla2cABChHyCzq7uXj5wfgBGqenBYVEaIdrEelAAlADcqiDhIBAADpzQzMigNHx8EADuAAo9CJ0oNMQQhIKNIHl8dGYwAMotdIRQDsgwfDJwTRvMIjCDCw7YNMgAZjTc+yAAVswAHkkLYEvLOQAyG3DXtyOTTWfCOfGQcxoeVwqGgsxafA2MAA6tNbMgABwABmBfSOyIWLQhCJYImI-yaAgAjjJUnBTjRzpckDc7k0jthCNtdvdmBsHOgAIoyCDwAFs6xQ1GCdFIABMTR2NC4-IAwhBsBcIVBoBSQDIjgwoWNWUcAL5moA)
```sh
--parser babylon
```

**Input:**
```jsx
let myDiv = ReactTestUtils.renderIntoDocument(
  <div>
    <div key="theDog" className="dog" />,
    <div key="theBird" className="bird" />
  </div>
);

```

**Output:**
```jsx
let myDiv = ReactTestUtils.renderIntoDocument(
  <div>
    <div key="theDog" className="dog" />
    ,<div key="theBird" className="bird" />
  </div>
);

```

**Expected behavior:**
Same as input.

Regression from #5006, cc @yuliaHope @lydell.

(Similar to #5047 but this one is fine in 1.14.)

**Comment by j-f1** [comment]
It’s also unstable:

**Second Output:**
```jsx
let myDiv = ReactTestUtils.renderIntoDocument(
  <div>
    <div key="theDog" className="dog" />,
    <div key="theBird" className="bird" />
  </div>
);

```
