### ISSUE TITLE
Regression: contents of TypeScript object types are not indented

### ISSUE THREAD

**Issue by Kovensky** [prettier/prettier#5342]
This works with **Prettier 1.14.3**, here is the [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEMCeAHOAFTgFs8AbAQ3gFlK8lNgBtKCGASwDMOxqPoAQTwdC+OIwwAnDlADmAXUYAJSlAAm5OACNKUtMTJV4AETha51OAF9MAXiaYScNGkpy4mayAA0ICHic6MigelIQAO4ACnoIaMgglABuEBzqviDaUpRgANZwMADKeDmycsgwUgCucH6yaHBSMFHZciSUyFyU5A1+AFZoAB4AQtl5BYWUzgAysnCd3b0gJfqNCbraOOTQGXgysADqaTAAFsgAHAAMfnsQDQfZeAl7Lo1J835ScACOVRxfLXc7QWPVqIAaJA4FWqYLQZS0AEUqux5kguqC-DBKNojupTsgAEyY7IcchlADCEBIwJQbCgHxAVQahGx8TRixs1iAA); but it is broken on `master`:

**Input:**
```ts
const typeTemplateMap: {[notificationApiType: string]: HandlebarsTemplateDelegate} = { message }
```

**Output:**
```ts
const typeTemplateMap: {
[notificationApiType: string]: HandlebarsTemplateDelegate
} = {
  message
}
```

**Expected behavior:**
```ts
const typeTemplateMap: {
  [notificationApiType: string]: HandlebarsTemplateDelegate
} = {
  message
}
```

**Comment by ikatyang** [comment]
I cannot reproduce the issue on master (2136fdc858c25b80ade232856a1d489a7c135628). Here's how I tried:

```sh
mkdir prettier-5342
cd prettier-5342
yarn init -y
yarn add prettier/prettier#2136fdc
echo "const typeTemplateMap: {[notificationApiType: string]: HandlebarsTemplateDelegate} = { message }" | yarn prettier --parser typescript
```

```ts
const typeTemplateMap: {
  [notificationApiType: string]: HandlebarsTemplateDelegate;
} = { message };
```

**Comment by Kovensky** [comment]
You are correct, this was caused by the `tslint` and `prettier` formatters fighting amongst themselves in `vscode`. This also explains some crazy formatting issues I was getting with JSX fragments:

```jsx
<>
  <Foo {...complexProps}/>
  <Bar {...complexProps}/>
</>
```

```jsx
<>'  '<Foo
  {...complexProps}
/>'  '<Bar
  {...complexProps}
/></>
```

Disabling the tslint auto format seems to have fixed this.
