### ISSUE TITLE
Problem with Docker*.json file

### ISSUE THREAD

**Issue by edahlseng** [prettier/prettier#5351]
**Environments:**
- Prettier Version: 1.14.3
- Running Prettier via: CLI
- Runtime: Node.js v10.13.0
- Operating System: macOS 10.14.1

**Steps to reproduce:**
* Create a file at the root level of a project named `Docker.json` (contents: `{}`)
* Run `npx prettier --list-different '**/*.json' --loglevel debug`

**Expected behavior:**
For Prettier to run properly.

**Actual behavior:**
Prettier returns an error with the following logs:
```
[debug] resolve config from 'Docker.json'
[debug] loaded options `{"useTabs":false,"tabWidth":"unset"}`
[error] Unable to expand glob patterns: **/*.json !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
[error] Invalid `"tabWidth"` value. Expected an integer, but received `null`.
```

What's odd is that the following files work: `docker.json`, `Docke.json`, `Doccer.json`. It appears somehow related to the `Docker` prefix. As far as I can tell, anything after `Docker` still causes an issue (I first noticed this on a `Dockerrun.aws.json` file).

**Comment by lydell** [comment]
Here's what happens for me on Ubuntu 18.04:

```
~/stuff/prettier-docker  
❯ ls
Docker.json

~/stuff/prettier-docker  
❯ cat Docker.json 
{}

~/stuff/prettier-docker  
❯ npx prettier --version
1.14.3

~/stuff/prettier-docker  
❯ npx prettier --list-different '**/*.json' --loglevel debug
[debug] normalized argv: {"color":true,"editorconfig":true,"list-different":true,"loglevel":"debug","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override","_":["**/*.json"]}
[debug] resolve config from 'Docker.json'
[debug] loaded options `null`
[debug] applied config-precedence (cli-override): {}
```

Idea: Do you have a .prettierignore somewhere, potentially outside the project?

Can anyone else reproduce this?

**Comment by ikatyang** [comment]
I guess there's an `.editorconfig` with content `indent_size  = unset`.

**Comment by lydell** [comment]
Yep, then I can reproduce. Is it a bug in https://github.com/josephfrazier/editorconfig-to-prettier?

**Comment by duailibe** [comment]
Opened https://github.com/josephfrazier/editorconfig-to-prettier/pull/5
