### ISSUE TITLE
@decorators on class are still being placed on separate line

### ISSUE THREAD

**Issue by desbrowne** [prettier/prettier#5360]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEMwZVoAafCAIwGc4cA3Y2gGznwF98AzHBHT4A5OjoAPEQG4AOlAzY8hGgybMmPfoOFjJAWhxxSMGfMW4CAKhL18AJWNltQ0UZNmFWSyvsQArvAAwkLYUAgwAAqCmHa8Aq4i7mSGAfA4nuawTHykXCH+sAASxFAAJpw40RCx+HAS8OV2foFwId7hsNWxADzA3AB8KtzyAAJ0jCya9UoEYOzE9HYFxaUV0w0IZc1OMAB07WERPSswJeWV3fRDwPKyMONqLGyc+JCFBAC8+AAMclD3IzlJgACgAlIR5PhoTDIFB6AQiGViDBiFpvjAABaoej-GEwowwfw4KD4EFQ-EwnplVDMAYUykw05IQhYnF7d6wEakxlU2iBGDQGhQILsVBgADWn2AbPoe0xa04AEkoGB3IxReKJYMVWrjIwegB6fkwQVQek83n4Homs3CzWS6UKi5wRyMGAO7UDN1wGBG23QC2M+5Gml0hkwsH-e7c+6jEwUUnO9a69VtMWS-DfcFZoayjkBWAAaiL0YeCaFyc4Po9GYlWbJEM+Nwj0PznK+vzxMO53BAlBANXI0HoyFAxBwggA7pEJwhRyhiMwIKgyv2QLQcKQJb6AMqYUioKAAc2QMBw-jgA8xMHQ7AA6tj4PQD2A4Lv56hyMwvwBPZDgEs65HpMURbse6DEMguTsIwA4AFb0BIABCW6SnuxDoHAAAyR5wNBxCwVeICIRIu5HsenAAIr+BA8AEURA4HjgkwATAv6YHA9BqqgmAwOumA4EeMD3quWLIAAHD8TGCIw95bpgAGCVx6j4QORgAI7+KgRjRMQEFQUgMFwSAjDoKgZ4XsR9AUdRtH0UZhEmaitCiWU4lIAATAO57EKgYonu0kEAVA0BqSA-iMAAKmwC7GXA3DcEAA)
```sh
--parser typescript
```

**Input:**
```tsx
import { action, observable } from 'mobx';
import { observer } from 'mobx-react';
import * as React from 'react';
import { RouteComponentProps } from 'react-router';

interface CountHandlerProps extends RouteComponentProps<{}> { }
@observer export class CountHandler extends React.Component<CountHandlerProps> {
	@observable count = 0;
	render() {
      const { data } = this;
      return (
        <div>
          Count: {this.count}
          <button onClick={this.handleIncreaseClick}>Increase</button>
          <button onClick={handleResetClick}>Reset</button>
      	</div>
      );
	}
	@action handleIncreaseClick = () => this.count++;
	@action handleResetClick = () => {
      this.count = 0;
    }
}
```

**Output:**
```tsx
import { action, observable } from "mobx";
import { observer } from "mobx-react";
import * as React from "react";
import { RouteComponentProps } from "react-router";

interface CountHandlerProps extends RouteComponentProps<{}> {}
@observer
export class CountHandler extends React.Component<CountHandlerProps> {
  @observable count = 0;
  render() {
    const { data } = this;
    return (
      <div>
        Count: {this.count}
        <button onClick={this.handleIncreaseClick}>Increase</button>
        <button onClick={handleResetClick}>Reset</button>
      </div>
    );
  }
  @action handleIncreaseClick = () => this.count++;
  @action
  handleResetClick = () => {
    this.count = 0;
  };
}

```

**Expected behavior:**
I would expect the `@observer` decorator and ~~the second `@action` decorator~~(fixed in 1.15.2) to stay inline as discussed in #4924.

**Comment by desbrowne** [comment]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEMwZVoAafCAIwGc4cA3Y2gGznwF98AzHBHT4A5OjoAPEQG4AOlAzY8hGgybMmPfoOFjJAWhxxSMGfMW4CAJWNltQ0UZNmFWSyqsQArvADCQ7CgEGAAFQUx6LQEHEScyQ294HBd5OAklAgABOkYWTTB2YnpI-y9YAAliKAATThx8NPgayJsTADp-NyDYQnlZGGy1FjZOfEgyggBefAAGOSh+oxqmAAoASl6ofG2dyCh6AiJq4hhiLWmYAAtUenmdnaMYLxwtlfl7+4AeatRmAD53h97qVYEhCFcbm1xrBuICgdtPrQfDBoDQoL52KgwABrSbACH0NqXKq1OAASSgYCcjAxWOx3D+FKpxkYnwA9EiYCioACtvCEZzuWjaTi8cSapwbIwYCL6X8pXAYOzBdBeUD+uyfv84Ts1vN+rCFgMTBQtuLSUzqXBZfhputbX98ASod5YABqN3641kU34c2SuDSm12jaTR3AHXbZ3QqazO47Q3cECUEAQTDkaD0ZCgYg4QQAdxCuYQWZQxGYEFQ1WTIFoOFI2MVAGVMKRUFAAObIGA4LxwFOXGDodgAdWu8HorbAcCbJdQ5GY84AnshwMUa+3cqF6x30MRkHxiOxGCmAFb0CQAIXrOObxHQcAAMu24AejyeQOeJE32x3OABFLwIHgN9j37EBWxwXJV1oNgl3YaAa0wHB2xgEcqyuZAAA4ZhTZCIEYEd60wVdkMDdRXxTIwAEcvFQIwwmIXd9yQQ8wJTRh0FQbte3A+hfwAoCQNY99wNOWh0OqTCkAAJhTHtiFQTFO06PdVygaBKJALxGAAFTYUs2MYbhuCAA)
```sh
--parser babylon
```

**Input:**
```jsx
import { action, observable } from 'mobx';
import { observer } from 'mobx-react';
import React from 'react';
import { RouteComponentProps } from 'react-router';

export @observer class CountHandler extends React.Component {
	@observable count = 0;
	render() {
      const { data } = this;
      return (
        <div>
          Count: {this.count}
          <button onClick={this.handleIncreaseClick}>Increase</button>
          <button onClick={handleResetClick}>Reset</button>
      	</div>
      );
	}
	@action handleIncreaseClick = () => this.count++;
	@action handleResetClick = () => {
      this.count = 0;
    }
}
```

**Output:**
```jsx
import { action, observable } from "mobx";
import { observer } from "mobx-react";
import React from "react";
import { RouteComponentProps } from "react-router";

export
@observer
class CountHandler extends React.Component {
  @observable count = 0;
  render() {
    const { data } = this;
    return (
      <div>
        Count: {this.count}
        <button onClick={this.handleIncreaseClick}>Increase</button>
        <button onClick={handleResetClick}>Reset</button>
      </div>
    );
  }
  @action handleIncreaseClick = () => this.count++;
  @action
  handleResetClick = () => {
    this.count = 0;
  };
}

```

**Expected behavior:**
Tried this with babylon parser to double check, seeing the same result.

**Comment by ikatyang** [comment]
cc @lydell @duailibe `@action` looks like a bug to me but I'm not sure where should `@observer` go.

**Comment by suchipi** [comment]
According to the [rationale doc](https://prettier.io/docs/en/rationale.html#decorators), we decided to always multiline decorators on classes, so that'd be why `@observer` is where it is.

**Comment by desbrowne** [comment]
Thanks, @suchipi, at over 3000 components in our web app that would be a problem for us as it's inconsistent. This is also not consistent with the mobx community.

I see the statement "We don't think it ever makes sense to inline the decorators" but no explanation on why it doesn't make sense. Given the large mobx community (> 17k stars) this statement seem at odds?

**Comment by desbrowne** [comment]
After speaking with the rest of my team I think we'd be happy to migrate to the multi-line decorator for classes as it seems that there is no real consensus with out mobx users (even the official docs has cases of multi-line `@observer`). 

Keen to get the second `@action` fixed so we can enable prettier for our team. Not sure where to start or if @duailibe you may be more familiar with the code?

**Comment by desbrowne** [comment]
Have added a couple of extra cases:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEMwZVoAafCAIwGc4cA3Y2gGznwF98AzHBHT4A5OjoAPEQG4AOlAzY8hGgybMmPfoOFjJAWhxxSMGfMW4CAKhL18AJWNltQ0UZNmFWSyvsQArvAAwkLYUAgwAAqCmHa8Aq4i7mSGAfA4nuawTHykXCH+sAASxFAAJpw40RCx+HAS8OV2foFwId7hsNWxADzA3AB8KtzyAAJ0jCya9UoEYOzE9HYFxaUV0w0IZc1OMAB07WERPSswJeWV3fRDwPKyMONqLGyc+JCFBAC8+AAMclD3IzlJgACgAlIR5PhoTDIFB6AQiGViDBiFpvjAABaoej-GEwowwfw4KD4EFQ-EwnplVDMAYUykw05IQhYnF7MoBDhtAKwEakxlU2iBGDQGhQILsVBgADWn2AbPoe0xa04AEkoGB3IxJdKZYMNVrjIwegB6YUwUVQekCwX4HoWq3i3Wy+WK5WquAAETgRsWcEGPr9JvNIugNrt0IdYdJ0BdcuAKoucEcjBg8cGqbgMDNjvDDJh9zNNLpBehYP+93591GJgopKT60N2raUtl+G+4I7Q3d71gAGp+3iYabTfgAOoBdhlfCYIx8TSKpAF0f4Wtkev4RucIMtjtkuAaWAsxwmA5JgDmcAAokec0UACoAWQAMhrMIFr5x0BEBhDPhGI5jviva8jA+j6MO0Krg+ED4EuFI1nWYrbt6vp7p2h4RCeuznqUV63scj6vu+n7fr+-49tiSp9uBkF3A8yENp6Wbpm2Mr7l2AGQraMKgR8+5-AW1YPJAWCtDOV4EJy-jcqcXa3Lx0KEsSpL8bA+A2AATJWMD8twICUCANTkNA9DIKAxA4IIADukRWQg5koMQzAQKgZSGSAtA4KQMrZgAypgpCoFAF7IDAOD+HARmYjA6DsOO2LwPQQVgHA-mOag5DMFlACeyDgEsnkhZMUQ+Re6DEMguTsIwRkAFb0BIABCPmygFxA-i+IVwNVxC1dFICNRI-khRenAAIr+BA8B9QNRlBTgkwFTAuWYHA9BaqgmAwJ5c4hTA47uViyAABw-AtgiMOOPmYAVc4beovVGUYACO-ioEY0TEBVVVIDVdUgIw6CoOFkWDfQY2TdNs3-f1gOorQR1lCdSBaUZEXEKgUqhe0lUFVA0DPSA-iMA+bBOQDAbcEAA

It seems that when a line is long the `@decorator` on line #25 in linked example is wrapped to the next line, not the expression body

**Comment by lydell** [comment]
Thanks, it's unfortunate we didn't know about it being common to inline decorators for classes in mobx. Coming from Python, that looked foreign to me. I guess we can simply remove that special case in a patch release.

**Comment by desbrowne** [comment]
Obviously the other cases should work but I'd suggest it's left as is for classes unless others chime in to say they would like it changed.

Our backend is .NET Core so like Python attributes are on a different line. We simply assumed this was the ES way as we only started using decorators when we picked up mobx (~3 years ago). Much of the mobx docs and examples I've seen are inline but again I may be wrong in making that inference that this is common with others who have a broader exposure to decorators.

**Comment by desbrowne** [comment]
Thanks @ikatyang your changes look much better! What did you think about [these last two scenarios in this example](https://deploy-preview-5364--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEMwZVoAafCAIwGc4cA3Y2gGznwF98AzHBHT4A5OjoAPEQG4AOlAzY8hGgybMmPfoOFjJAWhxxSMGfMW4CAKhL18AJWNltQ0UZNmFWSyvsQArvAAwkLYUAgwAAqCmHa8Aq4i7mSGAfA4nuawTHykXCH+sAASxFAAJpw40RCx+HAS8OV2foFwId7hsNWxADzA3AB8KtzyAAJ0jCya9UoEYOzE9HYFxaUV0w0IZc1OMAB07WERPSswJeWV3fRDwPKyMONqLGyc+JCFBAC8+AAMclD3IzlJgACgAlIR5PhoTDIFB6AQiGViDBiFpvjAABaoej-GEwowwfw4KD4EFQ-EwnplVDMAYUykw05IQhYnF7MoBDhtAKwEakxlU2iBGDQGhQILsVBgADWn2AbPoe0xa04AEkoGB3IxJdKZYMNVrjIwegB6YUwUVQekCwX4HoWq3i3Wy+WK5WquAAETgRsWcEGPr9JvNIugNrt0IdYdJ0BdcuAKoucEcjBg8cGqbgMDNjvDDJh9zNNLpBehYP+93591GJgopKT60N2raUtl+G+4I7Q3d71gAGp+5WHnWxY3OFn022ZR2yRDPjcy-he7yvr88TDqw9IFhWmV8ABzbP4Tn+bmnLu3W0E7PE0krj74GwAJmH-PxptN+AA6gF2PvMCMPhNEVJAC0-fBazIet8HHb1fRbWcQTgDRYBZRwTAOJMjwAUVQnMigAFQAWQAGQ1TBAhwzh0AiAZ5wjGEIPxB9YH0fQN2hCDCIgZdsXoMCBRrUcG09INEM7FCInQ3YsNKXD8J6IiyIoqiaLohi+PZPsYHYzj8Ag39-H-fBALgYCcC0gTwK-KDyDHT0AGUhGzbEoAPJCpLQhxZKCbC4Dw45lPIqBKJgai4Fo2B6O7GzKU5ZzaLZdzwX07jeNAilhOghzk0S1zUHczz8JkzC-PkgLFOC1TwvU6LNISlzkoPVL5G4EBKBAGp7PhZBQGIHBBAAd0iAaEHoZAQGIZgIFQMoOpAWgcFIGVs0czBSEKg9kBgHB-DgTrMRgdB2G-bF4HoDawDgRzxtQchmHugBPSawCWBbCsmKJloPdBiGQXJ2EYTqACt6AkAAhZbZTW4haNIwq4AB4ggYOkAwYkRyts4ABFfwIHgZHUc6jacEmSbaDYJ72GgBbAMKmBvzmrFkAADh+EnBEYb9lswSazMmDQFqMABHfxUCMaJiF+-6kEB4GQEYdBUB2va0fobG4DxgmkbllGFdRWgmbKFmkGfTrduIVApXc9o-smqBoCRzr-EYQi2AmvXUe4bggA)?

**Comment by svipben** [comment]
@ikatyang Thank you very much for the fix. Maybe you know when it will be released?

**Comment by ikatyang** [comment]
@desbrowne --> #5423

@svipben We plan to release a patch tomorrow.

**Comment by svipben** [comment]
@ikatyang They are still placed in the new line if width is > 60, if it's <= 60 decorator will be in the same line. I think it should respect the `printWidth` setting

**Comment by ikatyang** [comment]
@svipben Can you share an example?

**Comment by svipben** [comment]
@ikatyang https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEMwZVoAafCAIwGc4cA3Y2gGznwF98AzHBHT4A5OjoAPEQG4AOlAzY8hGgybMmPfoOFjJAWhxxSMGfMW4CAKhL18AJWNltQ0UZNmFWSyvsQArvAAwkLYUAgwAAqCmHa8Aq4i7mSGAfA4nuawTHykXCH+sAASxFAAJpw40RCx+HAS8OV2foFwId7hsNWxADzA3AB8KtzyAAJ0jCya9UoEYOzE9HYFxaUV0w0IZc1OMAB07WERPSswJeWV3fRDwPKyMONqLGyc+JCFBAC8+AAMclD3IzlJgACgAlIR5PhoTDIFB6AQiGViDBiFpvjAABaoej-GEwowwfw4KD4EFQ-EwnplVDMAYUykw05IQhYnF7MoBDhtAKwEakxlU2iBGDQGhQILsVBgADWn2AbPoe0xa04AEkoGB3IxJdKZYMNVrjIwegB6YUwUVQekCwX4HoWq3i3Wy+WK5WquAAETgRsWcEGPr9JvNIugNrt0IdYdJ0BdcuAKoucEcjBg8cGqbgMDNjvDDJh9zNNLpBehYP+93591GJgopKT60N2raUtl+G+4I7Q3d71gAGp+3iYabTfgAOoBdhlfCYIx8TSKpAF0f4Wtkev4RucIMtjtkuAaWAsxwmA5JgDmcAAokec0UACoAWQAMhrMIFr5x0BEBhDPhGI5jviva8jA+j6MO0Krg+ED4EuFI1nWYrbt6vp7p2h4RCeuznqUV63scj6vu+n7fr+-49tiSp9uBkF3A8yENp6Wbpm2Mr7l2AGQraMKgR8+5-AW1YPJAWCtDOV4EJy-jcqcXa3Lx0KEsSpL8bA+A2AATJWMD8twICUCANTkNA9DIKAxA4IIADukRWQg5koMQzAQKgZSGSAtA4KQMrZgAypgpCoFAF7IDAOD+HARmYjA6DsOO2LwPQQVgHA-mOag5DMFlACeyDgEsnkhZMUQ+Re6DEMguTsIwRkAFb0BIABCPmygFxA-i+IVwNVxC1dFICNRI-khRenAAIr+BA8B9QNRlBTgkwFTAuWYHA9BaqgmAwJ5c4hTA47uViyAABw-AtgiMOOPmYAVc4beovVGUYACO-ioEY0TEBVVVIDVdUgIw6CoOFkWDfQY2TdNs3-f1gOorQR1lCdSBaUZEXEKgUqhe0lUFVA0DPSA-iMA+bBOQDAbcEAA check the computed (the last one method)

**Comment by thorn0** [comment]
> MobX before version 6 encouraged the use of ES.next decorators to mark things as observable, computed and action. However, [...] In the interest of compatibility we have chosen to move away from them in MobX 6

-- [MobX docs](https://mobx.js.org/enabling-decorators.html#enabling-decorators-)

Also, I found [some docs](https://www.mobxjs.com/refguide/observer-component.html) for an older version, and it has class decorators on separate lines.

So things have changed, and what used to be common is the MobX community, isn't common anymore, which means that moving forward, even fewer users will want this formatting. I'm closing the issue.
