### ISSUE TITLE
Conflict with eslint-plugin-vue recommended rules

### ISSUE THREAD

**Issue by CinKon** [prettier/prettier#5363]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmp4BOMAlmDnGY3gM5sC8xIcAtGACSULAFcYPEuQqUAFnDwATONRb4O3XgOFiYAfT3ylKyaRkzUsgMxr2XHvyEjxB+jCaTgwMgBIYACjcmAEoyAF8w1AB6aylzClRFOgA3Ww0HbWd9PTwwemg2U2l4yiTU1nStJ10DXPzyRx0XHLy6aD4+NjgYeigAc0KQOJKLOBw+RWoILEUIAHcoMxHzGGo6Pr6VTUYGAGseJeWKAAFIDAw8KEVNWUvFJgBhCHO7g+KR4aPKACNxGGhDl8yDAAJ5YOCaX49AEgQHLT5A1BsZJ9MhIZJ0OBzABCEAAHpoGAUAHRdHp0fpsYkYrG4vFFIHxVCiLpovE4Cm7JCyahwABmmgABgBiHzAIlQKlk3oDYl0RRhQU8MhRBFfaLIvpqkbRKH-KDakqoMYTKYzeZQPgYBCiMhsHAQGCaSbTWYLBmMygml3mhZ8OiYFjPC5XZ1jbpwTzePz+ADkyiY8FjoQi0W9ZrdloDcAwhqZUXTrotVpteYSBfGPszeeiZRrZQoyX9Ap4AEI6GwAGJ0ahsCQgNL2KpNbJ1NoNTI1Fr1DoYCDJSOw97mMs-P4AxbLkag8GQ9eLJeM04csC7TQ+HMBuNzhd8URYZNvL6rhKatE0nH4wmQSXEmhTOYAFUsGpTFP3pIY4SOZlWSQdlOW5XkWxAEUxQlKl-3mYC5QVJUB1VKCjSiTVV11fcayiOtCNKFJqMbZtNHbNgABl2H7OjB00RoslqVpoDIbipzHdorXnRdqNIvUN0ZHcIR4KSDw4k4dlPc9LwCWMb34TNH0PI4X0oN90TAulvxJTC5gAEQtUDaXxD1GRg5g4I5KAuR5fkhVFcUfww6gAOshYcMVZUCK3IiSI4sjoQNajaxSbV4uSBFoiMZRqBShsKiHQTmh-eBYAcix7UdFUUsohKlmiGh6EYOApGiTBcAIerSBAAAaEBpnqNhkFACyAAUaAQXqUDwZIIHlDqQG+ahcl2boAGUsFyCk+mQVZRDgTrZBgDAcAAdVkbM2BWsA4EWkaAxSAMQWQEB1igCBeWmikuloAa5r6C5kD5PAcC6TqACs2DxbE5tPJa8GtZiKTgX7-sBkAQbxRa1qYABFURHXhpA-oB7aQBW3sVHu5ItumrA1lgA75RgWRkAADgABk6qmIC6A65qwe6qbgd6F2m3kAEdRB7OBPrwb68ARgnOq6DA6A26gtvl9G4CxnHldVkAYDwb5acUenkAAJk61Y8DoVy+ieF57qeqB4c6lk4AAFX10b8a6CIgA)
```sh
--html-whitespace-sensitivity ignore
--parser vue
--single-quote
```

**Input:**
```vue
<template>
  <article class="e-cInput">
    <header class="e-cInput__header">
      <h3 class="e-cInput__title">{{ $t(title) }}</h3>
      <div class="e-cInput__actions">
        <div class="e-cInput__action e-cInput__action--settings">
          <el-dropdown
            trigger="click"
            @command="handleCommand"
          >
            <button
              type="button"
            >
              <svg :viewBox="icons.settings.viewBox">
                <use :xlink:href="`#${icons.settings.id}`" />
              </svg>
            </button>
            <el-dropdown-menu slot="dropdown">
              <el-dropdown-item command="delete">{{ $t('delete') }}</el-dropdown-item>
            </el-dropdown-menu>
          </el-dropdown>
        </div>
        <div  v-if="!isFirst" class="e-cInput__action e-cInput__action--move"
        >
          <button

            type="button"
            @click="$emit('move-up')"
          >
            <svg :viewBox="icons.arrowUp.viewBox">
              <use :xlink:href="`#${icons.arrowUp.id}`" />
            </svg>
          </button>
        </div>
        <div
          v-if="!isLast"
          class="e-cInput__action e-cInput__action--move"
        >
          <button
            type="button"
            @click="$emit('move-down')"
          >
            <svg :viewBox="icons.arrowDown.viewBox">
              <use :xlink:href="`#${icons.arrowDown.id}`" />
            </svg>
          </button>
        </div>
      </div>
    </header>
    <div class="e-cInput__content">
      <slot />
    </div>
  </article>
</template>

```

**Output:**
```vue
<template>
  <article class="e-cInput">
    <header class="e-cInput__header">
      <h3 class="e-cInput__title">{{ $t(title) }}</h3>
      <div class="e-cInput__actions">
        <div class="e-cInput__action e-cInput__action--settings">
          <el-dropdown trigger="click" @command="handleCommand">
            <button type="button">
              <svg :viewBox="icons.settings.viewBox">
                <use :xlink:href="`#${icons.settings.id}`" />
              </svg>
            </button>
            <el-dropdown-menu slot="dropdown">
              <el-dropdown-item command="delete">
                {{ $t('delete') }}
              </el-dropdown-item>
            </el-dropdown-menu>
          </el-dropdown>
        </div>
        <div v-if="!isFirst" class="e-cInput__action e-cInput__action--move">
          <button type="button" @click="$emit('move-up');">
            <svg :viewBox="icons.arrowUp.viewBox">
              <use :xlink:href="`#${icons.arrowUp.id}`" />
            </svg>
          </button>
        </div>
        <div v-if="!isLast" class="e-cInput__action e-cInput__action--move">
          <button type="button" @click="$emit('move-down');">
            <svg :viewBox="icons.arrowDown.viewBox">
              <use :xlink:href="`#${icons.arrowDown.id}`" />
            </svg>
          </button>
        </div>
      </div>
    </header>
    <div class="e-cInput__content"><slot /></div>
  </article>
</template>
```

**Expected behavior:**
```vue
<template>
  <article class="e-cInput">
    <header class="e-cInput__header">
      <h3 class="e-cInput__title">{{ $t(title) }}</h3>
      <div class="e-cInput__actions">
        <div class="e-cInput__action e-cInput__action--settings">
          <el-dropdown 
            trigger="click" 
            @command="handleCommand"
          >
            <button type="button">
              <svg :viewBox="icons.settings.viewBox">
                <use :xlink:href="`#${icons.settings.id}`" />
              </svg>
            </button>
            <el-dropdown-menu slot="dropdown">
              <el-dropdown-item command="delete">
                {{ $t('delete') }}
              </el-dropdown-item>
            </el-dropdown-menu>
          </el-dropdown>
        </div>
        <div 
          v-if="!isFirst" 
          class="e-cInput__action e-cInput__action--move"
        >
          <button 
            type="button" 
            @click="$emit('move-up');"
          >
            <svg :viewBox="icons.arrowUp.viewBox">
              <use :xlink:href="`#${icons.arrowUp.id}`" />
            </svg>
          </button>
        </div>
        <div 
          v-if="!isLast" 
          class="e-cInput__action e-cInput__action--move"
        >
          <button 
            type="button" 
            @click="$emit('move-down');"
          >
            <svg :viewBox="icons.arrowDown.viewBox">
              <use :xlink:href="`#${icons.arrowDown.id}`" />
            </svg>
          </button>
        </div>
      </div>
    </header>
    <div class="e-cInput__content"><slot /></div>
  </article>
</template>
```

eslint-plugin-vue with recommended settings requires html-attributes on seperate lines if an element has more than one attribute: https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/max-attributes-per-line.md

is there a prettier-option to prevent errors by prettier?

```bash
  ✘  https://google.com/#q=prettier%2Fprettier  Replace `⏎··········v-if="!isLast"⏎··········class="e-cInput__action·e-cInput__action--move"⏎········` with `·v-if="!isLast"·class="e-cInput__action·e-cInput__action--move"`
```

**Comment by evilebottnawi** [comment]
You should disable all stylistics rules when you use prettier

**Comment by azdanov** [comment]
Wouldn't it be better to adjust prettier to follow the official style-guide?
https://vuejs.org/v2/style-guide/#Multi-attribute-elements-strongly-recommended

**Comment by evilebottnawi** [comment]
@azdanov it is prettier, it is not linter with a lot of options/configurations/settings, what exactly ugly?

**Comment by evilebottnawi** [comment]
@CinKon In right way use AND `prettier` AND `linter`, they have difference scope, first code formatter, second static analyzer

**Comment by lydell** [comment]
We should probably add support for eslint-plugin-vue in [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier). @CinKon Would you like to take a stab at it?

**Comment by azdanov** [comment]
@evilebottnawi Personally I see no problems here. There is a slight difference between the official vue style guide and the way prettier formatted the code right now.

🤷‍♂️ Sooner or later someone will mention the differences.

**Comment by aldarund** [comment]
I updated to pretteir 15 and now i have either prettier or eslint valid. The funny thing that when i disable eslint rule that is conflict prettier produce this formatting.

https://i.imgur.com/twOxC1z.png
https://i.imgur.com/IbDmobR.png
Really? Is it how its supposed to be? Never saw such formatting before and its horrible.

**Comment by j-f1** [comment]
That’s intentional @aldarund. We’d like to insert whitespace outside the tags, but that could change the displayed output.

**Comment by CinKon** [comment]
@lydell Thanks, but I'm not sure if I'm capable of this 🙈

**Comment by lydell** [comment]
@CinKon Ok, that's fine! I might get around to it this weekend.

**Comment by CinKon** [comment]
Is there a way to tell prettier to ignore the template-part in vue-files, so we still can use the latest prettier-versions?

**Comment by michaeljota** [comment]
I just open #5408 to request for this. I don't think Prettier have such thing. I think is because it was not needed before the support for HTML landed, as the most common scenario for want this is having multiple languages in one file, that I think it was not supported before.

**Comment by lydell** [comment]
I’ve released eslint-config-prettier 3.2.0 with support for eslint-plugin-vue! :tada:

**Comment by CinKon** [comment]
Wow, that was fast! I'll check it on Monday 😅

**Comment by phamhongphuc** [comment]
Unfortunately, It turns off all rules that are unnecessary or might conflict with Prettier.
It is not what I expected...

https://github.com/prettier/eslint-config-prettier/blob/master/vue.js
```
{
    "vue/html-closing-bracket-newline": "off",
    "vue/html-closing-bracket-spacing": "off",
    "vue/html-end-tags": "off",
    "vue/html-indent": "off",
    "vue/html-quotes": "off",
    "vue/max-attributes-per-line": "off",
    "vue/multiline-html-element-content-newline": "off",
    "vue/mustache-interpolation-spacing": "off",
    "vue/no-multi-spaces": "off",
    "vue/no-spaces-around-equal-signs-in-attribute": "off",
    "vue/script-indent": "off",
    "vue/singleline-html-element-content-newline": "off"
}
```

**Comment by lydell** [comment]
@phamhongphuc What do you expect?

**Comment by phamhongphuc** [comment]
I expected exactly what @CinKon said in the first comment.
Besides, when you said "add support for `eslint-plugin-vue`", I thought Prettier will somehow follow the official style guide. But after the release of `eslint-config-prettier`, I realize that I can't get what I expected with the current version of Prettier.
I will find another way #5440 or request for ignoring based on languages #5408
Thanks.

**Comment by michaeljota** [comment]
Formatting style guides are not strictly followed by Prettier though.

**Comment by lydell** [comment]
> I expected exactly what @CinKon said in the first comment.

As far as I can tell, that comment says "is there a prettier-option to prevent errors by prettier?" which I interpret as "is there a way to prevent errors by prettier?". Now there is!

> Besides, when you said "add support for eslint-plugin-vue", I thought Prettier will somehow follow the official style guide.

Ah, sorry for the confusion!

The way Prettier works is that it tries to pick a popular and non-controversial code style (while still taking all other trade-offs into account). Then we recommend turning off all lint rules that conflict. Linters do nothing without rules so they are easy to make Prettier-friendly, while Prettier always blows away the entire file so changing Prettier to follow linters is much harder.

> But after the release of eslint-config-prettier, I realize that I can't get what I expected with the current version of Prettier.

And what is it that you expect? Sorry for not understanding :(

**Comment by phamhongphuc** [comment]
Eh! I missed the line.

> is there a prettier-option to prevent errors by prettier?

Sorry about that! 🤣
I'm finding a way to use Prettier without turning off any lint rules, which follows the official vue style guide.

Or at least, could you please support `vue/max-attributes-per-line` (prettier/eslint-plugin-prettier#94)? It will be ok if there are 2~3 attributes each component. But when I have more, it's harder to read the code.
Thanks.

P/s: I love both `Linter` and `Prettier`. If it is against the prettier philosophy, I will try to figure out a way to love `Prettier` more than I did with `Linter`. 🤣

**Comment by lydell** [comment]
> Or at least, could you please support `vue/max-attributes-per-line`

This has been discussed before for JSX, but it might be worth opening a new issue now that we support Vue and HTML.



> P/s: I love both `Linter` and `Prettier`.

You mean ESLint?

**Comment by phamhongphuc** [comment]
> You mean ESLint?

Linter is ESLint or Stylelint.

> #3101 

Thank you!
