### ISSUE TITLE
Implicit arrow return of test function and timeout is hard to read

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#5365]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVBLGAKAOlddAcgGcBXMMOOAExMwDNUYALOZuEmVBjKDEm3p9mGALZwiAGnyFU2AJSoAvAD5UUOAHdUABQBOEMQLjZ9nCABsAbuzWoScGABVxcCGRzmSV21NQAjAAMCgoyBIQATACsQbKoCgDcIFIgEAAOMBjQJMigAIb6hlq6hQi5KPnWEBg0KSAARvr5YADWTgDK6S18AObIMPpkcKksMGKWAOosWJzdVB3lWBjWWACeyOAkual8jvowBvm9YvnIDPmWjqkAViQAHgBCzW2d+RIAMnxw55fXIHd7h0+pY4ABFMgQeC-K4jEDdfT7TYNfINNaWaD1dL6PgwSa1VjIAAcQVS2IgjkmzXSm2xnDg+ls9XMAEcyBhzEcTmckBdYalHMYBkM4SQQeDIdDeX84TBUfiaISkJFUoN8hhLH0AMJGU6bKDQH6pMiOZyoip8xwAXytQA)
```sh
--parser babylon
```

**Input:**
```jsx
  it(
    'succeeds if the test finishes in time',
    () => new Promise(resolve => setTimeout(resolve, 10)),
    250
  );
```

**Output:**
```jsx
it("succeeds if the test finishes in time", () =>
  new Promise(resolve => setTimeout(resolve, 10)), 250);

```

**Expected behavior:**
Not sure, actually. But I find it pretty hard to read at first glance that `250` is an argument to `it` and not part of the statement in the body of the callback function.

Related to #5085 (FWIW, I'm highly supportive of that change, I just think the arrow return case is hard to read)

**Comment by ikatyang** [comment]
The fix is available in [`1.15.2`](https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1152).
