### ISSUE TITLE
New generics printing causes very long lines

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#5370]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATArgJwEMAjASwBtSYBPAWThn1LDQGU5y4wYTOlMAkgFshuHsU4A6APL5scfHGzsYAHgA6UTJlYQhcAEpwADhHwxSUAOb1GzADSaAfJgC8mIdQCiAD2MLSBDA4dk5uXjhJSCgwQhgACggYAAsFABECEgoqOgYmFlCucU4ASgBuEHsQCGMLdGRQQnx8CAB3AAUmhDRkEEIANwhSbEqQYiIwAGsGVmNCMEsrZEZcOCrkmCFyAHVkqjg0OeD2KDQqUn6c3pYeqss0BRh2oishQmQAM0JyB6qAKzQPgAQhNpjBWIR9AAZSxwT7fX4gAE+ViLTgARVwSThSC+PzWIDm+Ae+F6xBI1HI0FGxiYsG2wxSyAAHAAGKq0iAPbZEYy9WkHBT9OFVRQAR1wpEUz0Ir3euIRBIeQlIy3wqyqZ2sGKx8Hh+Kq4gZ2CZSAATIaiNlrABhPRvXpQaAikC4B4AFRIPQV+IAvr6gA)
```sh
--parser babylon
```

**Input:**
```jsx
const durabilityMetricsSelectable: Immutable.OrderedSet<
  SomeReportingMetric,
> = myExperienceSelectable.concat(otherDurabilityMetricsSelectable);
```

**Output:**
```jsx
const durabilityMetricsSelectable: Immutable.OrderedSet<SomeReportingMetric> = myExperienceSelectable.concat(
  otherDurabilityMetricsSelectable
);

```

**Expected behavior:**
Ideally, we should make it work like this:
```jsx
const durabilityMetricsSelectable: Immutable.OrderedSet<SomeReportingMetric> =
  myExperienceSelectable.concat(otherDurabilityMetricsSelectable);
```
This is hard, I know prettier hasn't been doing breaking after equals because it's hard to know what's on its left side, but maybe there's a heuristic here? (same one as the one causing the generic to be one line?).

**Comment by lydell** [comment]
Related: #2482

**Comment by xixixao** [comment]
Notice that this is not just about breaking equal sign. The new implementation is very strict, and isn't even breaking this:
```
const SomePlatformsSelectOboOrSkipSubmitButtonContainer: React.ComponentType<{||}> = someCreateSimpleSelectorSomething(
```
The equal sign is on character 84, yet prettier is not breaking the line at all.
