### ISSUE TITLE
Pug inside .vue file is treated as html and mis-formatted

### ISSUE THREAD

**Issue by homerjam** [prettier/prettier#5371]
The welcome PR #5259 has introduced an issue whereby a `.vue` file containing pug in the template (specified like so: `<template lang="pug">`) is treated as html and therefore mis-formatted.

This can be resolved using the `<!-- prettier-ignore -->` flag but ideally pug would be ignored by default (until full support could be added at later date).

**Comment by ikatyang** [comment]
The fix is available in [`1.15.2`](https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1152).
