### ISSUE TITLE
CLRF line endings with HTML causes new line in multi line comments

### ISSUE THREAD

**Issue by alexw10** [prettier/prettier#5373]
**Prettier 1.15.1**
Very similar to this issue but with HTML now instead:
https://github.com/prettier/prettier/issues/5315

Line Endings have to be CRLF for this to occur.
This is utilizing Angular parser as well if that matters.

**Input:**
```html
<!--
  test
  test
-->
```

**Output**
```html
<!--
  test

  test
-->
```
**Second Output**
```html
<!--
  test


  test
-->

```

This causes prettier lint to fail.

**Comment by ikatyang** [comment]
The fix is available in [`1.15.2`](https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1152).
