### ISSUE TITLE
Formatting: inline function with multiple arguments

### ISSUE THREAD

**Issue by oskarrough** [prettier/prettier#5376]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAFnADYkQDqEATiQCYAUAlPsADpRszoDOcAoqlRxsDZvgC8APlYcuXAPQL8dCPh4QAtnBiEcUAOZyYAXwA0+ANoAHahGs8AdADcAhiXRwAukw4mOIGYg9rjQPMigrtR2AO4AClEI4SiuzhA4dIEgAEbUrmAA1joAytb5+gbIMNSeQYQwmiQUevA8ZWBwxUk4uM49AJ7I4DzhQfp81DBxeQaarsio7nxBAFY8AB4AQnmFJa7aADL6cAtLcKsbxRUkcACK6BDwpyTLIGXUE0PZrtn95FBZWz6GAUDK6ZAADgADEFbBA+BQ8tYhrY4BNnCcgtQ4ABHdA4bHTVyzeZIRYvc4gPiaHBVGqUnjXO4PJ5ks5BGA-UF0cFIABMHLyOBIFQAwlo5kMoNBMSBeHAACo-ZLkvgmExAA)
```sh
--parser babylon
```

**Input:**
```jsx
function helloWorld() {
  useEffect(() => {
    // do something
  }, [props.value])
}

```

**Output:**
```jsx
function helloWorld() {
  useEffect(
    () => {
      // do something
    },
    [props.value]
  );
}

```

**Expected behavior:**

Like input. Output seems a bit excessive.

If this is intended, please close. Thanks!

**Comment by duailibe** [comment]
This is intended, but we can change it.

I remember @vjeux, @jlongster and others have said something in Twitter; we might want to revisit this.

**Comment by vjeux** [comment]
The inline version looks prettier to me

**Comment by lukepighetti** [comment]
Input is prettier! :)

**Comment by ljharb** [comment]
Will the change apply to all function calls, or just apparent react hooks?

**Comment by j-f1** [comment]
All function calls with two parameters where the first parameter is an arrow function with a block body and the second is an array @ljharb.

**Comment by ljharb** [comment]
Any reason to restrict the second argument to being an array, rather than “any one-line thing”?

**Comment by j-f1** [comment]
Arrays are the only case I’ve heard of so far, and it’s difficult to handle the second parameter breaking (it’s easier for arrays since only the `[` stays on the first line when it breaks).

**Comment by j-f1** [comment]
Object literals could be done. Number and string literals, as well as identifiers, would be more difficult because they wouldn’t be able to break if they exceeded the print width.

**Comment by ljharb** [comment]
Functions as well?

**Comment by j-f1** [comment]
Feel free to open an issue or PR if this is important to you @lhharb.

**Comment by ljharb** [comment]
Seems like answering open questions should be important to all of us before merging and closing things.

**Comment by felixfbecker** [comment]
Another API that would benefit from this is Puppeteer `page.evaluate(func, ...args)`
