### ISSUE TITLE
Wrong example of whitespace handling in changelog

### ISSUE THREAD

**Issue by StarpTech** [prettier/prettier#5382]
The whitespace inline examples in the new changelog https://prettier.io/blog/2018/11/07/1.15.0.html are wrong. Leading and trailing whitespaces are irrelevant in the example. It depends on the inline formatting context. Did you consider it?

https://medium.com/@patrickbrosset/when-does-white-space-matter-in-html-b90e8a7cdd33

**Comment by lydell** [comment]
Thanks, that article is really good. Could you copy in some examples here for quick reference?
