### ISSUE TITLE
[Angular] '>' getting put to a new line when it shouldn't be?

### ISSUE THREAD

**Issue by alexw10** [prettier/prettier#5383]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8BbAhjAWgCdcATASwgICMBXGGaAHSgwzABtcBnbgXiYhcAB2EEIwmJSi4OBGCSjds5XtIIA3cnADu3YmUo16jKIJZt0G2bTgCQARnOtLAPgDyk6ageYA9HiEJBRUdAzQriAANCASUtDcyKC4REQQOgAKKQiJKLgaEOSk0SDUJGAA1nAwAMrCuGDkUADmyAq2MQAWMNgcAOqd5PDc9WBwNTlD5FowAJ7I4LwlTdxwRDAZJM14yABmsqsxAFbcAB4AQuVVtbjYcAAyTXB7B3DHZzVNzRxwAIq0EHgLw4hxA9SIqyIC1wLVoXChMWERCaMD6RRgnWQAA4AAyItKrPokYQLJFwSEaZ4xIhwACOtHINM2uG2uGBoNWKjaRA6IG4Xx+-0BzyQ+xBbxAMFw1DRpAxyAATDEFLhyBwvgBhCDYHYoKDQKkgWirAAq0tyYtWAF8rUA)
```sh
--parser angular
```

**Input:**
```html
<mat-radio-button class="app-optional-transmission-views-radio-button" value="1">Option 1</mat-radio-button>
```

**Output:**
```html
<mat-radio-button class="app-optional-transmission-views-radio-button" value="1"
  >Option 1</mat-radio-button
>

```

**Expected behavior:**
I am wondering do we think this is right?
To me the > should stay on the ending `mat-radio-button`

**Comment by michaeljota** [comment]
Can you try changing the default settings for html whitespace sensitivity? I'm almost sure that Angular takes care about it, so I've set it to ignore. So far my snapshot tests have came out fine, but if you can set a couple more just to make sure, that would be great.

**Comment by alexw10** [comment]
gotcha guess that makes sense, probably best to keep whitespace as it is, well at least it is safer I think. Will just accept the weird look :D
