### ISSUE TITLE
Prettier cannot format styled-components createGlobalStyle tag

### ISSUE THREAD

**Issue by sevenryze** [prettier/prettier#5386]
**Input:**
```jsx
// code snippet
import { createGlobalStyle } from "styled-components";

const GlobalStyle = createGlobalStyle`
  * {
    			box-sizing: border-box;
    



    margin: 0;
`;
```

**Output:**
```jsx
// code snippet
import { createGlobalStyle } from "styled-components";

const GlobalStyle = createGlobalStyle`
  * {
    			box-sizing: border-box;
    



    margin: 0;
`;
```

**Expected behavior:**
Prettier should format the styled-components' createGlobalStyle tag.

**Comment by ikatyang** [comment]
See https://github.com/prettier/prettier/pull/5264#issuecomment-429606676:

> Hi!
>
> It appears as if Prettier used to support more tags, but removed them:
>
> - https://github.com/prettier/prettier/pull/2337#issuecomment-311801382
> - #2342
> - #2970
> - #4937

**Comment by ikatyang** [comment]
Duplicate of #2970
