### ISSUE TITLE
[Angular] Removing parenthesis when it should not be

### ISSUE THREAD

**Issue by alexw10** [prettier/prettier#5389]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgAIAUALAlgEzgBlcoBHABQEMo4AbdAfnQB0QAlOABwgCcYAyvThgYuaADoAEgTgDsEAO5EqAI3oB9eUokCYvUgHM26JKw7c+g4aPFRps7crWaZhXfqNsAlOgA+6HQQYFR0uABecEiYQSFh4VRi0EK20L4AvukgADQgEFxJUADOyKBUvLxK1LwIJShUAG4QBDkgqrxUYADWcIJcnUbI+gCucLnYMAC2dADqePBF-WBytbhiDWsAnsjgRSW5pEVw-BQdhpNUyABmoUe5AFZFAB4AQh3dvQJUk8SkcNe3MYgR5PARGOhwACKwwg8ABdDuIH6vCOvB2NEMwzo5VaXAMsBmBBg2GQAA4AAy5PEQI4zDpcHZ4uCohr-XI1MjDXA1U5Uc6XJA3BFAo6TXBDXijXJFcFQmFwwWA3IwNSE-DE5AAJmVHVwYSghgAwhBJhcdlBoGyQMMjgAVNR1IVHTJAA)
```sh
--parser angular
```

**Input:**
```html
{{ (hideLinqPanel ? "ReportSelection.HideShowLabel_Show.String" : "ReportSelection.HideShowLabel_Hide.String") | localize:(localizationSection) }}
```

**Output:**
```html
{{
  hideLinqPanel
    ? "ReportSelection.HideShowLabel_Show.String"
    : "ReportSelection.HideShowLabel_Hide.String"
    | localize: localizationSection
}}

```

**Expected behavior:**
It should keep the ( ) around the main ternary operator cause this is piping after that evaluates, the output it provides makes it not localize.

**Comment by ikatyang** [comment]
The fix is available in [`1.15.2`](https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1152).
