### ISSUE TITLE
Ugly formatting for component declared using React.memo

### ISSUE THREAD

**Issue by Jessidhia** [prettier/prettier#5392]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEA5CA3OAGwGEALAQwCdyx5LiIBXWTAXkwCU4aYA6AWzj8IACgA6UTJgBmzWgEtoOfETJUecek1gjgmSMywBfJJj0HYpqI34AjTZiMBKMxKliYlODEaVJ4ySkggB4APmAAegAqfQh+AAdoBCxIWGS0TCiIo2CI0LdMDycCowknEAAaEAh4mEUoNGRQKkoIAHcABSoERpRyPAh5ABNKkFtqMABrbwBleJp5KABzZE9GOCrSGH5CAHVSeXg0ebA4GZ7D+TxDgE9kcDRGqsW0TRgO6iX+cmRpckJXlUAFZoAAeACEJtMYDNyIIADKLOC-f6AkAg0EzRZLQhwACKjAg8FWlHWVXmlFelHuMBu8TgaDAlHktVG8WZsF2wxgpGQAA4AAzk1qvXbUeL3dkMzQEUZeACOjHkXg+5C+PyQfwBGxAr348hR2qqaGxuIJRORSDWOpg5FsXKGPOQACYqp5yPJCNiGPxvvcoElRoxXgAVO29LWvIxGIA)
```sh
--jsx-single-quote
--parser typescript
--no-semi
--single-quote
```

**Input:**
```tsx
const NovelCharacterCount = React.memo(
  function NovelCharacterCount({ count }: { count: number }) {
  	return (
      <>{/* component contents */}</>
  	)
  }
)
```

**Output:**
```tsx
const NovelCharacterCount = React.memo(function NovelCharacterCount({
  count
}: {
  count: number
}) {
  return <>{/* component contents */}</>
})

```

**Expected behavior:**

Preferably same as the input; but primarily that the `function` expression starts on the _next_ line.

Using an arrow function for this is not ideal as it will lose the name of the wrapped component; even then, it still has the same issue of the function expression hugging the opening parens.

---

This probably also affects `forwardRef` and countless HOC factories so I guess a good heuristic would be, add the newline if the function expression is named? 🤔

**Comment by kachkaev** [comment]
Prettier's output looks pretty to me and it matches component wrappings into HOCs. The problem with formatting things as you suggest would mean that wrapping a component into `React.memo` would create a diff for all its content due to changes in spacing.

**Comment by evilebottnawi** [comment]
Answer above, thanks fro the issue, feel free to feedback
