### ISSUE TITLE
vue templates - pre tags single quotes dont get changed to double quotes

### ISSUE THREAD

**Issue by trainiac** [prettier/prettier#5398]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlKlgE5wAEY+AzvQLwDkA7hBDCyVNdcGDV6MAK4AzcdQC+00v1QB6SnF5LMuAqpAAaEBCwwAltHrJQeChQhsACpYRmUeAG4QjAE10gARhTxgANZwMADKWAFGUADmyDAUonB6ABYwGDgA6slG8PQRYHChjjlGLjkAnsjgjN5R9HAUMLb+0Rh4yOJ4OPV6AFb0AB4AQv5BIaF4GHAAMlFwHV09IP0DoVHROHAAiqJc80id3UkgERT1FFUuid6UUTAZnjDJyAAcAAx6lBD1Gf5YVSpzi55noqABHURGKjNPCtdoHRbHeoYIxxBJI9abHZ7BZHPQwPA+B4eJ7IABM+P8Rhw6wAwhAMG0qlBoCCQKJ6gAVQlOQ71WRAA)
```sh
--parser vue
```

**Input:**
```vue
<template>
<pre class='woot'>
  {{ stuff }}
  </pre>
</template>
```

**Output:**
```vue
<template>
  <pre class='woot'>
  {{ stuff }}
  </pre>
</template>

```

**Expected behavior:**
```vue
<template>
  <pre class="woot">
  {{ stuff }}
  </pre>
</template>

```

**Comment by ikatyang** [comment]
The fix is available in [`1.15.2`](https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1152).
