### ISSUE TITLE
HTML: Weird format for label

### ISSUE THREAD

**Issue by maxime1992** [prettier/prettier#5401]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeANgQwEZ3QAgDMIAnAXgB0QSIZMYBLaADSoD4AFTEmfAJVr0mUfAAoAHgEok+VAHosudG1QMoABwCuvBgBNK1QYxZV8MAJ7q4BqJoC2uEqYDO8dQYAMAOg8BGU+pYYHAAFhDounDkVAJ0xiISkqbEJHYAwtAwNOgAcph21lQ0ccKsIGwgADQgEOrxzsig3DQA7lwkCA0omABuEHpVINgkmGAA1nAwAMrqo2oA5shZmnDVITB26ADqIQzwzrPBU517DD175sjgzg3Vas5RMBwj83aYyISY6A-VAFbO4gAQiNxpMpvk4AAZNRwD5fH4gf7iKYLdBwACKmlosKQn2+qxAsxIDxIV3Wm0G6hIahgWz0MBCyF8ACYPNUqRAHlsRuorlS4CSerDqh0AI6aBgdZ6YV7vXHwgkPOwMJYkFbVZyojFY+Bw-HVOjYOm6BnIZkGkYMdALDJ2N5XKDQYUgTQPAAqOC6eIeAF8fUA)
```sh
--parser html
--print-width 120
```

**Input:**
```html
<label for="rotationX">Part Rotation (x): </label><input id="rotationX" type="number" step="0.01" placeholder="Rotation (x)" formControlName="rotationX">
```

**Output:**
```html
<label for="rotationX">Part Rotation (x): </label
><input id="rotationX" type="number" step="0.01" placeholder="Rotation (x)" formControlName="rotationX" />

```
**Expected behavior:**

Either:

```html
<label for="rotationX">Part Rotation (x): </label><input id="rotationX" type="number" step="0.01" placeholder="Rotation (x)" formControlName="rotationX">
```

or:
```html
<label for="rotationX">Part Rotation (x): </label>
<input id="rotationX" type="number" step="0.01" placeholder="Rotation (x)" formControlName="rotationX">
```

**Comment by lydell** [comment]
Looks like you want [`--whitespace-sensitivity ignore`](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) – but read about [whitespace sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) first.

**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeANgQwEZ3QAgDMIAnAXgB0QSIZMYBLaADSoD4AFTEmfAJVr0mUfAAoAHgEok+VAHosudG1QMoABwCuvBgBNK1QYxZV8MAJ7q4BqJoC2uEqYDO8dQYAMAOg8BGU+pYYHAAFhDounDkVAJ0xiISkqbEJHYAwtAwNOgAcph21lQ0ccKsIGwgADQgEOrxzsig3DQA7lwkCA0omABuEHpVINgkmGAA1nAwAMrqo2oA5shZmnDVITB26ADqIQzwzrPBU517DD175sggDPNQpHCDas5RMBwj83aYyISY6M-VACtnOIAEIjcaTKb5OAAGTUDyQPz+qxAQPEUwW6DgAEVNLQEUj-iBZiRniQrutNoN1CQ1DAtnoYCFkL4AEweao0iDPLYjdRXGlwMk9B7VDoAR00DA6b0wHy+iN+ROedgYSxIK2qzkxOLx8G+SpRdGwDN0TOQrOqWUwDHQCwydk+VzuUFFIE0zwAKjguoS4ABff1AA)
```sh
--html-whitespace-sensitivity ignore
--parser html
--print-width 120
```

**Input:**
```html
<label for="rotationX">Part Rotation (x): </label><input id="rotationX" type="number" step="0.01" placeholder="Rotation (x)" formControlName="rotationX">
```

**Output:**
```html
<label for="rotationX">Part Rotation (x):</label>
<input id="rotationX" type="number" step="0.01" placeholder="Rotation (x)" formControlName="rotationX" />

```

**Comment by maxime1992** [comment]
Oh I see closing for now and reopening later if needed thanks for explaining!
