### ISSUE TITLE
Flow comments in function arguments moved to body

### ISSUE THREAD

**Issue by zaygraveyard** [prettier/prettier#5403]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPIjAEwEN4BlGHOAMWwgFsBVAJQAyACgA6UPHgDOrbHDwB6AFRI8LNkoUAacZOBS49bGAAWWvCfpSTAX0Uq8+w8ZOqZ2clADm5y9bcwHt42muIAlI424iBaIBAYFNBSyKBGXADuAApGCMko9ABuEOS0MSAARtj0YADWcDBMGNWeXsiBRHCxJjDcADYA6ibk8FJNYHBMucPkBcMAnsjgUsmxnga4mVVe3PTIBPS9BrEAVlJoAEJVtfVM9Nxwgp5wewdHIKdoTC29cACKRBB4C9Dp0QE1sOtFuV6OU5r1oGUMEEYP0SjATMgABwABliSIgBn6VQwiyRcHWBWesTkAEciOQ5Jt6Ntdkh9iDYgZuOQ2tgOpzvn8AUC2a9QTAYajaOjkAAmWKBejkXotADCPB2iyg0CpICIBgAKjC8uyDDYbEA)
```sh
--parser babylon
```

**Input:**
```jsx
export function updateStoreFromURL(
  store /*: Store*/,
  {search, hash} /*: {search: string, hash: string}*/
) {}

```

**Output:**
```jsx
export function updateStoreFromURL(store /*: Store*/, { search, hash }) {
  /*: {search: string, hash: string}*/
}

```

**Expected behavior:**

Input is unchanged, more specifically the flow type comment should not move into the body of the function

**Comment by ikatyang** [comment]
The fix is available in [`1.15.2`](https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1152).
