### ISSUE TITLE
Allow to ignore based on languages

### ISSUE THREAD

**Issue by michaeljota** [prettier/prettier#5408]
**Environments:**
- Prettier Version: 1.15.1

**Steps to reproduce:**

As a user I want to ignore certain languages that are part of a larger file that I do want to format.

* `App.vue`
```vue
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <HelloWorld/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld'
export default {
  name: 'App',
  components: {
    HelloWorld
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

I don't want to format the HTML template
* `.prettierignore`
```json
{
  "languages": ["html"]
}
```

**Expected behavior:**

Prettier format the file, but the HTML template.

```vue
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <HelloWorld/>
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld";
export default {
  name: "App",
  components: {
    HelloWorld
  }
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

```

**Actual behavior:**

There is no way to ignore a part of a file based on the language. 

**Related:**

#5378

**Comment by lydell** [comment]
Hi! I think it helps the dicussion to know _why_ you want to ignore certain languages of a larger file. Could you please share that?

**Comment by michaeljota** [comment]
See [this comment](https://github.com/prettier/prettier/issues/5363#issuecomment-436889494). Also, I may no want to prettier to format certain languages, but others. This can be an issue in Angular files, and Vue files mostly. I may want Prettier to format the JS/TS code, but not the HTML nor the (S)CSS. But if everything is in the same file, how can I ignore those parts?

**Comment by Coder-256** [comment]
@lydell I'm not sure about the author's reason, but this is actually a feature that [I had already asked about](https://github.com/prettier/prettier/pull/5259#issuecomment-435264958) in order to enable the use of multiple formatters (such as TSLint) for parts of Vue files. It seems that this feature didn't make it, but I believe that it could be useful. +1

**Comment by lydell** [comment]
>  may want Prettier to format the JS/TS code, but not the HTML nor the (S)CSS

Yes, but _why?_ Just trying to understand the problem space fully before thinking about solutions.

**Comment by michaeljota** [comment]
See @Coder-256 comments please. I don't really have a problem so far. But I really think there should be an option for people who doesn't want to format HTML with Prettier, and it seems legit to me.

**Comment by lydell** [comment]
So … you (@michaeljota) don't need this and @Coder-256 _hypothetically_ needs it? I feel really dumb now, but am I missing something?

**Comment by Coder-256** [comment]
Haha well what I mean is that I don't currently need it for any current project, but I would like to be *able* to use other linters along with Prettier, especially for script/style blocks in Vue files.

**Comment by lydell** [comment]
Well, let's close this until somebody needs it then!

**Comment by blowsie** [comment]
Personally I prefer the eslint vue rules to the prettier html ones, especially since they provide useful messages to rules that are broken. How can I use prettier on my entire `.vue` file except for the `<template>` section?

**Comment by michaeljota** [comment]
This is a request to be able to do such thing. In the mean time you can add a comment above all the templates in your files. :/.

**Comment by blowsie** [comment]
@michaeljota thanks. Its a shame to have to disable one or the other since in the past my prettier rules and eslint rules have worked in perfect harmony. Anything else would be a lesser user experience and a headache for the teams involved when it comes to new issues etc I'm sure.

**Comment by blowsie** [comment]
Without this option;
Vue developers have a choice;
 - No longer follow the vue style guide. Using [`eslint-pretter-config`](https://github.com/prettier/eslint-config-prettier/blob/e47f4acd0746d1e2af875cb9ee2fc6dd1af12593/vue.js#L4-L19)
- No longer use prettier at all
- Disable prettier in each file / section using [prettier-ignore](https://github.com/prettier/eslint-config-prettier/blob/e47f4acd0746d1e2af875cb9ee2fc6dd1af12593/vue.js#L4-L19)

**Comment by lydell** [comment]
Why isn’t option 1 (use eslint-config-prettier) a good choice for you?

**Comment by blowsie** [comment]
> Why isn’t option 1 (use eslint-config-prettier) a good choice for you?

Because using this means no longer following the style guide.

**Comment by blowsie** [comment]
Because if I'm not following a predefined style guide, I would have to manage / define my own for other team members to use. 

Best practice would be to use the standards defined by the framework.

**Comment by lydell** [comment]
The thing with Prettier is that you don’t need a style guide anymore – the code style you use is whatever Prettier spits out.

**Comment by michaeljota** [comment]
@blowsie Correct me if I'm wrong, but I've see that most of the Style Guide request are about the number of properties in a single component. If that's a concern to you, you may request elements to be treated as object literal and respect if the first attribute is in a new line and format the rest of the element with multiline attributes in #3101. It was once a request for doing it in JSX, but now that Prettier have support for HTML/Angular/Vue, its for all of them. 

If there is anything else you would want to be added, please, consider posting explanations about the expected behavior and the rationale behind it.

**Comment by blowsie** [comment]
@michaeljota #3101 would certainly help to keep the appearance closer to the vue styleguide, and in my opinion makes things a lot more readable. But for me its still not enough to start using prettier in the HTML sections since eslint vue has some extra smarts like knowing which order the attributes should be in.

I will have to opt for the following option for now, but would still love to see "Allow to ignore based on languages" implemented.
> 3. No longer use prettier in a given file / section using prettier-ignore

**Comment by lydell** [comment]
> But for me its still not enough to start using prettier in the HTML sections since eslint vue has some extra smarts like knowing which order the attributes should be in.

It’s possible to use only the parts of eslint-plugin-vue that don’t conflict with Prettier.

**Comment by bengry** [comment]
@lydell Sorry for coming in late, but there is a need for it in the Angular community, at least. I haven't seen it brought up in the thread above, just Vue.

With Angular you usually use tslint, which doesn't support anything in the template/style part of the component, just plain TypeScript.

To add to that, in Angular, and especially with short-ish templates and styles, you want to keep everything in the same file (`foo.component.ts`), this means that you have 2/3 languages in the same file, all of them dealt with the same way by Prettier (as far as configuration goes), and can't run another pass like with `eslint-plugin-vue` (to my understanding) to fix things up.

With the current Prettier behavior, some things are unwanted (e.g. #3101, #5378).
Allowing at least ignoring based on languages would at least keep the formatting of the template/style untouched by Prettier, at least until #5378 gets in, which would probably make this obsolete (?).
