### ISSUE TITLE
Support `.html.tpl` as HTML files

### ISSUE THREAD

**Issue by astorije** [prettier/prettier#5428]
**Environments:**
- Prettier Version: 1.15.1
- Running Prettier via: CLI (in my case, but this affects all)
- Runtime: N/A
- Operating System: N/A

It is common to see `.html.tpl` files being installed/used by build tools, and in most cases these are valid HTML files. Would it be reasonable to support this specific extension with the `html` parser?

We are using the following configuration at the moment:

```js
  overrides: [
    {
      files: '*.html.tpl',
      options: { parser: 'html' },
    },
  ],
```

but it would be nice if Prettier was opinionatedly considering these as HTML by default.
Thoughts?

**Comment by ikatyang** [comment]
Ref: https://stackoverflow.com/questions/1808294/what-is-tpl-files-php-web-design

I googled it and it seems it's used for PHP templates?

**Comment by astorije** [comment]
Not necessarily, more often than not I have seen `.xxx.tpl` as "this is a templated file for format XXX". Historically Smarty yes, but for a while I've only seen it used as a generic way to say, this file is meant to be this format but needs some transformation. For example, you'll often see that in Ansible that offers templating support for any file with Jinja2.

Granted, this means `.html.tpl` may not be valid HTML pre-templating, but more often than not it is as the content itself is being templated.
It's definitely an opinionated suggestion, but I think it would make sense to consider `.html.tpl` HTML files unless opted-out, rather than opting-in (through a parser override). Of course I am biased since all the projects I work on in at least 2 organizations have such files, but this is just my 2c 😊
Thanks for your tremendous work @ikatyang, very highly appreciated!

**Comment by astorije** [comment]
If you're curious about an example of what I'm talking about, this is one (doctored because private) file that we use:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

Another one, public this time: [The Lounge's `index.html.tpl`](https://github.com/thelounge/thelounge/blob/master/client/index.html.tpl).

**Comment by michaeljota** [comment]
Through I does work with that example, it doesn't mean this would work in all scenarios. Template languages are not supported yet by Prettier, but Angular's and Vue's. 

If you are sure your files are HTML compatible, then use the workaround you proposed, but I don't think is a good idea for this be the default behavior, as it could lead to unintended formatting.

**Comment by ikatyang** [comment]
Thanks. But if I remember correctly, I did not enable the parsing for unknown directive (e.g., `<%`), which means they're all treated as normal text and we'll normalize their whitespaces, wouldn't they cause issues?

And also I tried to format the example you mentioned above, and I found that it's not compatible with HTML, for example:

```
<body class="signed-out<%- public ? " public" : "" %>" data-transports="<%- JSON.stringify(transports) %>">
```

`class="signed-out<%- public ? " public" : "" %>"` will be parsed as `class="signed-out<%- public ? "` and produce parsing errors for the rest parts.

**Comment by astorije** [comment]
All very good points.
The first example I have should always be valid HTML so my workaround will work, and the second project is being rewritten in Vue so it's not worth the effort until the rewrite is finished.
I'm going to close this because it makes sense and I have a workaround. If someone is looking for something similar, this issue / arguments will now show up in the search results.

Thanks!
