### ISSUE TITLE
close tag of A span multi lines

### ISSUE THREAD

**Issue by hisland** [prettier/prettier#5433]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AJPoC8AOiHAE7kTkD6AzgIYC2ADgDZykB8qDuAFuTgAzEiAD0kCCwB0-GEzbcGKlanEMefQSLGSI0uQqUguTAJ64wbCHTi4YDAOa46LBlFxMArmxiZcNkwoOHVNXgEhUVJ9Q3lFZVUGMJ5xLGwuYigMHHwiUggAa3pmdk5TCJ1oiSlZeJMuJOSNLlxKqL1aowTTfgY6XAB3fkx4RhYwewYqbyh0LzgAGnwAcmZcIpS27Q6YrvrE1RT1dMyoLPbdPYM6424YEYHMAb4bKBc3j+gv98Dvv9+nwBPxBwMCwVCLQu6SsbH6dDEfRs90e+BeYKBmP+WMB2LxuIJHwhJxwXBAixA0n80DoyFA0yogwACtMELSUAxsBACOSQAAjcgMMCFOAwADK7jAwScyBg5G8SxA9QA6iMxpK4GK2aMcKNzMhwHRaRTgnZyDAmYKnEwGMhhAw2HYKQArOgADwAQoLhaKxcw4AAZCF2h1OkCut1i6UcACK3gg8BDjsV7nIZoN9V5LHIwRgyoID2QAA4AAwU7O2ODKwUsA3ZuBm7BwXlCACO3kwQktzhtSbDdiYmFl8sVdGjcDjCebSHtyYpjj5+fQhaQACZ54LMEF3gBhCBMXsoKDQZsU7x2AAqDD57NndgAvvegA)
```sh
--parser html
```

**Input:**
```html
<div id="error_sample"><a href="/coop.html">aaaaa</a><a href="/coop.html">my close tag span multi line</a><a href="/coop.html">aaaaa</a></div>
<div id="ok_sample"><a href="/coop.html">aaaaa</a> <a href="/coop.html">has whitesapce around me, i'am ok</a> <a href="/coop.html">aaaaa</a></div>

<a href="/coop.html">this is a long long long long long long long long long long long line</a>
<div class="halo">this is a long long long long long long long long long long long line</div>
```

**Output:**
```html
<div id="error_sample">
  <a href="/coop.html">aaaaa</a
  ><a href="/coop.html">my close tag span multi line</a
  ><a href="/coop.html">aaaaa</a>
</div>
<div id="ok_sample">
  <a href="/coop.html">aaaaa</a>
  <a href="/coop.html">has whitesapce around me, i'am ok</a>
  <a href="/coop.html">aaaaa</a>
</div>

<a href="/coop.html"
  >this is a long long long long long long long long long long long line</a
>
<div class="halo">
  this is a long long long long long long long long long long long line
</div>

```

**Expected behavior:**
see the output above, '#ok_sample'

**Comment by ikatyang** [comment]
@paolovanini It sounds like the same concept as #5377, can you move your comment there?

**Comment by paolovanini** [comment]
@ikatyang : I don't think it's the same issue. It's not a problem with the alignment of a tag and its corresponding closing tag but that the single closing a tag (</a>) it's divided in 2 different lines.

**Comment by hisland** [comment]
through the spec, I know that end-tag can contain white-space, so
`</a>`  or  
`</a >` or 
`</a`
`>`  are valid end-tag!
my editor syntax highlighting take me wrong, 


![image](https://user-images.githubusercontent.com/417448/48354563-00266300-e6cd-11e8-9d38-c9282c7476e3.png)
![image](https://user-images.githubusercontent.com/417448/48355634-6a400780-e6cf-11e8-801c-2807335b57ed.png)

**Comment by ikatyang** [comment]
@hisland Sounds like this issue can be closed?

@paolovanini #5377 is about using [`--jsx-bracket-same-line`](https://prettier.io/docs/en/options.html#jsx-brackets) in html-like parser, they look like the same concept to me (do not put `>` alone on the next line). Did I miss something?

**Comment by ikatyang** [comment]
I'm confused. What's the difference between

- "_do not put `>` alone on the next line_"

and

- "_the single closing `a` tag (`</a>`) it's divided in 2 different lines_", or
- "_the end-tag span two lines_"

?

**Comment by ikatyang** [comment]
> why only `</a>` tag should be formatted like that by Prettier but `</p>`, `</div>` and other closing tags should behave differently?

Oh, I should understand your issue now. As mentioned by @hawkrives, it's because `<a>` is an inline element and we don't want to break your code, see [Whitespace-sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) for more info. And if you don't care about those whitespaces, just use `--html-whitespace-sensitivity ignore`:

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgOToE4CWsAtAO4EAmMAFtgAToCGejAtnPHnQQM508c6MCHQAcABlQB6LAB0oGTAQBmdADZE46hAHNqMKeSrVufAK5QKcLqICMdMNWaMwnHkgdqIPIjrrZGehhGP146ZU1pOQVGOmo8OGUAXlkQAA8MzKzsnNy8nNTMDSgtMIB2AE4HJxZXax5pRkx5VFj4xJT0-O6e3sLi0r4Jauc6vAapJpa2hOTU3oXF7P7NUzF7R1G3RuaFLBV1VbVdfUNKGjWIADdrdZHatw8wLx8oPwCgkLWAIzwIAGsEHRrrcAEyHEruKK7VpxWadJaIxYrEprUTgzYPeo7EAAGhAEHQMAI0B4yFAzD+pAACswEGSUIwrhBKHiQL8XICYABlJhgXzIGB4MxwfH6VhqADq1AI8B4fLg3PpsoIV1lAE9kCACDooBAEmyiAI8DBqSwdKxGMhlIw1AJ8QArHhpABCtS53LYcAAMpprbb7SAnWlub5jgBFMwQeD+u2ikBMcbWLXitRs-BEGCS87UZASfH4bxwSUsdBa-BwY03NkJACOZgICTNIUtscDAlYBEFwvjrx0EajMaQNrj+OC32zxmQoLHLAIxR0AGEIKxWyg9SU2WYBAAVRjfBkjgQAX2PQA)
```sh
--html-whitespace-sensitivity ignore
--parser html
```

**Input:**
```html
<p>'print-width' parameter is set to 80</p>
<p>if line lenght/width is under 81 characters: closing 'a' tag is fine</p>
<a href="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">line is 79 characters</a>
<a href="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">line is 80 characters</a>
<a href="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">line is 81 characters</a>
<p>if line lenght/width is over 81 characters: closing 'a' tag is broken over 2 lines:</p>
<a href="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">line is 82 characters</a>
```

**Output:**
```html
<p>'print-width' parameter is set to 80</p>
<p>if line lenght/width is under 81 characters: closing 'a' tag is fine</p>
<a href="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">line is 79 characters</a>
<a href="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">line is 80 characters</a>
<a href="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">line is 81 characters</a>
<p>
  if line lenght/width is over 81 characters: closing 'a' tag is broken over 2
  lines:
</p>
<a href="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
  line is 82 characters
</a>

```

**Comment by hisland** [comment]
Yeah ! That's what I need, because I style tag-a as a block-element, which don't care the whitespace around it. Thank You Very Much!

**Comment by paolovanini** [comment]
@ikatyang : the option you suggested seems to resolve my problems with the closing tags:.
--html-whitespace-sensitivity ignore
(and I learned a lot about the spec of a closing 'a' tag and white-spacing too ;-))
Thanks for your help! :-)
