### ISSUE TITLE
angular.js templates problem-custom components are converted to self-closing tags

### ISSUE THREAD

**Issue by capaj** [prettier/prettier#5436]
So I guess my question is-is this intentional? Prettier doesn't support angular.js?
Because only way to write a custom component in an Angular.js template is to use both opening and closing tag.

**Comment by j-f1** [comment]
From https://github.com/prettier/prettier/issues/1882#issuecomment-437603539:

> I just updated to prettier 1.15.2 and I get this when I format our angular.js templates:
> ![image](https://user-images.githubusercontent.com/1305378/48304509-b269f900-e51a-11e8-81b6-518cf13bbb93.png)
> 
> this totally breaks our angular.js app.
> Guess it's back to the old 1.14.x version for us. 
> Can't you make the conversion to self-closing tags configurable?

**Comment by capaj** [comment]
BTW I don't mind if prettier says-hey let's not support that archaic framework. I can't wait until we can refactor it all to react in our app. 
If this is the case for prettier-it would be nice to document this incompatibility in the readme or somewhere. Especially given the fact that angular.js doesn't give you any errors or warnings when it's compiling your templates. It's just chugging along ignoring the rest of your html happily. So it's really easy to miss the breakage when developing.

**Comment by ikatyang** [comment]
It seems you're using `--parser babylon`, which treats it as JSX:

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhldAbAnjASzAGcBaGCAB1ICc5iIBXGsegHSgAJOoBzUggDMAvGxCYc+IsQB0BYgBV0AIwDKcbHDDwAJgApOAcjoNmrYoc4BKMRwB8qAPQS8hEuSq16TFvTsgAGhAqQmhiZFB0GhoIAHcABSiEcJR0ADcIAh1AkGUadDAAazgYVUoCgj5kGBpGOCCACxgAW2wAdQaCeGJy1nUoYi6CNK7cZHBicKDK4jgaGHj83mb0ZEEcWaCAK2IADwAhfKKS1XRmuAAZSrg1jfqQHd3VSt5NAEVGCHhb7E2Qcposxo42UKlw2GgOUoNEqMDaWRgDWQAA4AAxBaEQWZtfKUcbQ+hzNI3IJ0ACOjAIdEW6GWqyQ61+91mzQI1VqzJe70+3wZdyCMBU8J0iOQACYBfkCNgXgBhCDNFbjKDQEkgRizJTKFKM2YAXz1QA)
```sh
--parser babylon
```

**Input:**
```jsx
<analytics-top-resources
  ng-if="analytics.isTabSelected( 'resources' )"
></analytics-top-resources>
```

**Output:**
```jsx
<analytics-top-resources ng-if="analytics.isTabSelected( 'resources' )" />;
```

Though we did not support angular.js (e.g., format `ng-if`), but at least it won't break your code with `--parser html` or `--parser angular`:

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhldAbAnjASzAGcBaGCAB1ICc5iIBXGsegHSgAJOoBzUggDMAvGxCYc+IsQB0BYgBV0AIwDKcbHDDwAJgApOAcjoNmrYoc4BKMRwB8qAPQS8hEuSq16TFvTsgAGhAqQmhiZFB0GhoIAHcABSiEcJR0ADcIAh1AkGUadDAAazgYVUoCgj5kGBpGOCCACxgAW2wAdQaCeGJy1nUoYi6CNK7cZHBicKDK4jgaGHj83mb0ZEEcWaCAK2IADwAhfKKS1XRmuAAZSrg1jfqQHd3VSt5NAEVGCHhb7E2Qcposxo40wvEY2CiOUoNEqMDaWRgDWQAA4AAxBaEQWZtfKUcbQ+hzNI3IJ0ACOjAIdEW6GWqyQ61+91mzQI1VqzJe70+3wZdyCMBU8J0iOQACYBfkCNgXgBhCDNFbjKDQEkgRizJTKFKM2YAXz1QA)
```sh
--parser angular
```

**Input:**
```html
<analytics-top-resources
  ng-if="analytics.isTabSelected( 'resources' )"
></analytics-top-resources>
```

**Output:**
```html
<analytics-top-resources
  ng-if="analytics.isTabSelected( 'resources' )"
></analytics-top-resources>

```

(Please provide text example next time.)

**Comment by capaj** [comment]
@ikatyang oh my I am so sorry! I ran the command using my global installation of prettier and didn't notice it until today. 1.15.x works beautifully and it even uncovered cases where we currently have templates with a bad syntax:
![image](https://user-images.githubusercontent.com/1305378/48312611-beed6080-e5b1-11e8-85bb-0a9ee7384f25.png)


Accept my humble apologies. I am gonna go and uninstall it now. Global installs are a pain. 

Maybe come tho think of it-wouldn't it be nice to show a warning(with a current version printed out) when running prettier from a global install instead of a local one?
