### ISSUE TITLE
Issue Vue Formatting

### ISSUE THREAD

**Issue by aaaguirrep** [prettier/prettier#5441]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkVkDKArmGHAM7ekWoA9LQakhmXATiMx3MACcaWGIzgAPLBHkwyVOADM8bHDuD8y+AJ4Q2MJGQDkRmAAsHAGnMYaVKjjgA7njycPYA2g4htCFgMA4AuqQAvmKCcorKjCDuIBDKNNDcyKDB8hABAArBCEUoeHQQPtkgAEbyeGAA1nAwLFgdNFAA5sgw8mxwOS4wGDgA6i408Nz9XCw1S-RLlsjgvM2D3HDaFe1DGHjIhjhHOQBW3GoAQu1dPSx4GHAAMoNwV3gbpMQA81CxBkN-ABFNgQeAAoE5fryI7yXZ0CbNLCKWBzHyuZAADgADEiykc5u0sLtsTxjnR-jkQgBHNg0EKnPDnS5Ia63EBHbyjcbA7gQ6Gw+G8wH8mB4Fp4qgEpAAJhyYzwNBwEIAwhAMBddlBoIyQGwjgAVeW1PlwJJJIA)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <div>
    Success
  </div>
</template>

<script>
export default {
  layout: 'auth',
  middleware: ['redirect']
}
</script>

```

**Output:**
```vue
<template>
  <div>Success</div>
</template>

<script>
export default {
  layout: "auth",
  middleware: ["redirect"]
};
</script>

```

**Expected behavior:**
I am new developing but I think that if it is working now the update shouldnt generate errors. I think that the current input is the expected output. Otherwise, i need to change and fix all "error" in the compilation process.

**Comment by hawkrives** [comment]
@aaaguirrep Could you fill out the "Expected behavior" section, too, please? It's not immediately obvious what your problem is, or why it's a problem.

**Comment by aaaguirrep** [comment]
Expected behavior:
I am new developing but I think that if it is working now the update shouldnt generate errors. I think that the current input is the expected output. Otherwise, i need to change and fix all "error" in the compilation process.

**Comment by lydell** [comment]
> fix all "error" in the compilation process.

I'm not super familiar with Vue development – what compilation errors are you talking about?

**Comment by aaaguirrep** [comment]
The next component shows the next errors that in the version 1.14.3 it was working:

<template>
  <div>
    Success
  </div>
</template>

<script>
export default {
  layout: 'auth',
  middleware: ['redirect']
}
</script>


C:\Users\ARSENIO\Desktop\Development\applicationdev\frontend\pages\index.vue
   1:11  error  Delete `␍`                                               prettier/prettier
   2:8   error  Replace `␍⏎····Success␍⏎··</div>␍` with `Success</div>`  prettier/prettier
   5:12  error  Delete `␍`                                               prettier/prettier
   6:1   error  Delete `␍`                                               prettier/prettier
   7:9   error  Delete `␍`                                               prettier/prettier
   8:17  error  Delete `␍`                                               prettier/prettier
   9:18  error  Delete `␍`                                               prettier/prettier
  10:27  error  Delete `␍`                                               prettier/prettier
  11:2   error  Delete `␍`                                               prettier/prettier
  12:10  error  Delete `␍`                                               prettier/prettier

✖ 10 problems (10 errors, 0 warnings)
  10 errors and 0 warnings potentially fixable with the `--fix` option.

**Comment by hawkrives** [comment]
Those look like lint errors to me; if this was eslint, I'd say "install eslint-config-prettier and disable all stylistic rules". However, I don't know the first thing about how Vue works, so I don't know what to recommend.

**Comment by aaaguirrep** [comment]
I have installed the following modules and it works but when i install the last version of prettier it shows the errors.

    "babel-eslint": "^10.0.1",
    "eslint": "^5.9.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-prettier": "^3.0.0",
    "eslint-plugin-vue": "^4.0.0",
    "nodemon": "^1.18.6",
    "prettier": "^1.14.3"

**Comment by lydell** [comment]
@aaaguirrep I think you have to add eslint-config-prettier to some config file as well?

**Comment by aaaguirrep** [comment]
I don't know, i have installed eslint-config-prettier and ir shows the same error.

**Comment by lydell** [comment]
@aaaguirrep The best way of debugging this kind of issues is to make a new repo. Make a small test file, then install stuff one by one until you hit the issue. Then share the repo here and we'll take a look!
