### ISSUE TITLE
Auto-closed JSX tags are really annoying during development. I would like to propose a one-way option that could provide "development" and "commit" stages

### ISSUE THREAD

**Issue by ndbroadbent** [prettier/prettier#5442]
**Prettier 1.15.2**

I started getting annoyed by this issue, and I found [this discussion on Twitter](https://twitter.com/wesbos/status/983717331699490818): 

> [@wesbos](https://twitter.com/wesbos/status/983717331699490818): Is there a prettier setting that will stop it from self-closing HTML elements? I’m too trigger happy with my saves and it converts \<div\>\</div> to \<div/> before I put anything inside of it

> [@tvanantwerp](https://twitter.com/tvanantwerp/status/983721724024934400): I hope someone knows. How many minutes (hours?) have I lost changing \<div/> back to \<div>\</div>...

> [@kiran_abburi](https://twitter.com/kiran_abburi/status/983721533330702337): I need this one.

> [@vigzmv](https://twitter.com/vigzmv/status/983786848114765825): Yes...! it's super annoying. I have to save to see the changes but then I got to add children inside it.

> [@AndyWynyard](https://twitter.com/AndyWynyard/status/983733360831926273): Omg this sooooo much this!!! I’ve started slowing down with the Cmd + S consciously now because of...

> [@NicklausRoach](https://twitter.com/NicklausRoach/status/983720970367193088): This would be a wonderful thing to have. I hate having to go back and “reopen” tags. Let us know if you find a solution!

### Scenario

1. Add a new `div` and get ready to add some content:

```
<div>
</div>
```
2. Switch to the browser to check something

3. Come back to VS Code and see that the div is now closed:

```
<div />
```

This happens because I use `formatOnSave`, and Auto Save with `onFocusChange`. (I know I can press ⌘+Z to undo the format, but it's still really annoying.) 

I've experimented with turning off `formatOnSave` and just using a keyboard shortcut and precommit hook. But now I really miss the auto-formatted code.

> [@wesbos](https://twitter.com/wesbos/status/983718155498508288): I love having it on every save - it saves me tons of time reformatting and indenting code. I don’t have to think about style anymore with it enabled

I would like to propose a new one-way boolean option called `closeEmptyJsxElements`. The default value would be `true`, which is the current behavior. Setting this to `false` would prevent any new empty JSX tags from being closed, but it would *not* re-open any self-closing tags. There are a lot of React components and HTML elements that *should* be self-closing, so re-opening these would also be annoying.

The idea is that a developer could set `"closeEmptyJsxElements": false` in their `.prettierrc`, which they use during development. Then they could pass a command-line argument in their git precommit hook: `--close-empty-jsx-elements true`. This would close any of the empty JSX tags where they don't need to add any more content. (They could also set up a new keyboard shortcut to run prettier with this option. It might also be known as "commit mode", versus "development mode".)

I can think of a few other options that share a similar philosophy:

* `trailingComma`
  * It's easier to add a new argument or property when you have trailing commas.
* `arrowParens`
  * It's easier to add a new argument if the parentheses are already there.
* `jsxBracketSameLine`
  * It's easier to add a new prop when the bracket is on a new line.

It might be interesting to have one-way versions of these options these during development, and then tidy up the code before you commit your changes. I'm actually not too excited about those, and I just wanted to come up with some more examples.  But the self-closing JSX tags have been really annoying, so I think this could be a good solution.

Thanks!

**Comment by lydell** [comment]
Hi! What I usually do is typing TODO inside JSX elements (or if I'm really lazy, just a single letter). I do the same for if/for/while-blocks. Have you tried that?

**Comment by ndbroadbent** [comment]
Hi @lydell, oh yeah I forgot to mention that I've started doing that with single letters (usually "s", because it's right before I press ⌘+S.) But I don't know, that felt like an ugly workaround as well. And then I have to highlight the character or press backspace to delete it.

**Comment by ndbroadbent** [comment]
Whoa, it was actually really easy to get this working! I don't really understand how the AST works, but commenting out [these lines](https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L5305-L5308) will preserve the existing tags:`<div></div>` doesn't change, and neither does `<div />`. So I wrapped it with an option, and it works perfectly:

```bash
/tmp $ cat test.jsx
const a =         123

const b = (
  <div>
    <p></p>
    <span />
    <p />
        <i class="icon"></i>

  <div class="new-content"></div>
  </div>
     )
/tmp $ prettier --close-empty-jsx-tags false test.jsx
const a = 123;

const b = (
  <div>
    <p></p>
    <span />
    <p />
    <i class="icon"></i>

    <div class="new-content"></div>
  </div>
);
/tmp $ prettier test.jsx
const a = 123;

const b = (
  <div>
    <p />
    <span />
    <p />
    <i class="icon" />

    <div class="new-content" />
  </div>
);
```


Here's my branch with the change: https://github.com/ndbroadbent/prettier/tree/add_close_empty_jsx_tags_option

Try it out with:

```
cd /tmp
git clone https://github.com/ndbroadbent/prettier.git prettier-ndbroadbent
cd prettier-ndbroadbent
git checkout add_close_empty_jsx_tags_option
yarn
npm install -g .
```

Now you should see:

```
$ prettier --help | grep jsx-tags
  --close-empty-jsx-tags   Make empty JSX tags self-closing. (Note: This is a one-way operation.)
```

Not going to send a PR because I think it might be a bit controversial. But I'm definitely going to start using it in all of my projects.

**Comment by ndbroadbent** [comment]
Quick update: It's working really well. I installed it into my project with `yarn add https://github.com/ndbroadbent/prettier.git#add_close_empty_jsx_tags_option`. Then I added `"closeEmptyJsxElements": false` to my `.prettierrc`. I had to restart VS Code, and after that everything works great.

Then I set up a pre-commit hook with `husky`, in my `package.json`:

```
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx,json,css,md}": [
      "prettier --close-empty-jsx-elements true --write",
      "git add"
    ]
  }
```

> See the [Prettier Pre-Commit Docs](https://prettier.io/docs/en/precommit.html)

Now Prettier leaves my empty JSX elements alone during development, but converts them into self-closing elements before I can commit any changes.

**Comment by duailibe** [comment]
Can we just stop changing this at all, i.e. if you write `<foo></foo>` don't change to `<foo/>`? Or maybe apply this to lower case tags?

**Comment by ikatyang** [comment]
I think we should only touch whitespaces, quotes, etc. but not something like changing open-closing tags to self-closing tags.

**Comment by duailibe** [comment]
```jsx
<Foo
  prop={val}
  prop={val}
></Foo>

// or

<Foo
  prop={val}
  prop={val}
>
</Foo>
```
?

**Comment by ikatyang** [comment]
I'm not familiar with JSX whitespace but 

```jsx
<Foo
  prop={val}
  prop={val}
></Foo>
```

looks the safest to me.

**Comment by duailibe** [comment]
They're equivalent

**Comment by j-f1** [comment]
👍 for option 1, ❤️ for option 2 ⤵️

**Comment by axe-z** [comment]
any news on this as an option ? without having to resort to a prettier config in vscode ?

**Comment by shamilovtim** [comment]
Is this released yet? I'm still having this issue!

**Comment by duailibe** [comment]
@shamilovtim No

**Comment by vkyplr** [comment]
> yarn add https://github.com/ndbroadbent/prettier.git#add_close_empty_jsx_tags_option

Thanks, It worked 👍
