### ISSUE TITLE
[TypeScript] inline method decorators should stay inlined

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#5443]
Originally reported by @svipben in https://github.com/prettier/prettier/issues/5360#issuecomment-437759115

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgBo7AA6UOOAAgCZyQ4AeAFAJSEllkBOcMArh6TAAWAS0wA6SD1g4AVDgBMAbjY4Aviqo0IOAObd6zVqXZde-HENESIUmLIXLj6qM5AAaEBAAOMYdEzIoOgcHBAA7gAKwQgBKOgAbhDClO4gAEYc6GAA1twAyl5ZwlA6yDAcPHAegjAAtqgA6iLwmIVgcHkxwr7x3QCeyODYqcWYcBwwEZk6tejIAGboqGMeAFaYdABCmTn56LVwADLFcAtLKyDrdHnFOqhwAIo8EPBny1UghRxjHIMwfV44JgwBxhD5Ul5QbAGskhMgABwABg8kIgYwamS8g0hQPG8VOHi4AEceMIuFN0DM5khFu8PGNasIyhUPphbvcni9TjTzh8YOg0jDKHCkPIPOV0MJULcAMIQWqzQZQaAEkA8MYAFQFsVpY1UqiAA)
```sh
--parser typescript
```

**Input:**
```tsx
class X {
  @deco x() {
    return this.count * 2;
  }
  @deco get x() {
    return this.count * 2;
  }
}

```

**Output:**
```tsx
class X {
  @deco
  x() {
    return this.count * 2;
  }
  @deco
  get x() {
    return this.count * 2;
  }
}

```

**Expected behavior:**
Same as input.

**Comment by svipben** [comment]
@ikatyang I created an issue https://github.com/prettier/prettier/issues/5445 so I'm closing it and I will add a reference to this issue.

**Comment by ikatyang** [comment]
Ah, sorry! I thought you're away from the computer.

**Comment by svipben** [comment]
@ikatyang No problem, your examples are way shorter and better. Also, you're very fast, you opened an issue and already fixed it 😄 Thank you very much, I'm very happy 😄
