### ISSUE TITLE
Comment types of Flow makes Prettier confused

### ISSUE THREAD

**Issue by jinmayamashita** [prettier/prettier#5446]
**Prettier 1.15.1**

Sorry, I could not reproduce it on v1.15.2 playground. :bow: (solved at 1.15.2 ? :eyes:)
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACACgJwgwGdsBebYAHwB0ptsA6ZgEgFEAPAQzBgB4CRYgHUAljAAWAFQBiUAHwAaOg2aN23XnxYBhLgBt9fdFggAzbAFsuGAMowu8KREElF2AFTuP8pSqasnDz8ugZGJnDmVjYAIqLEGI5gEt7evsr0AepBWgDu4hIASnAJ0MRwjGKSAIoArnD4aK7EfIUQEDB1DWjpdFQAvgDcIIogRDCiZcigXPiEubizCMTIIFwAbhCiACYjIABG+DwA1nAwtolgolAA5sgw+PWjEjCW+sIS4iWXcLbL4qJ1uI0KswMQVqNruV8DACFwbtZkGYDOVRgArYgcABCRzAp3OXEscAAMtc4PdHnB0ZjbNcbvo4HUOuSkMj9KiQIl8NDVmZ9BBcnsMPhrjAxNtJMgABwABlGwog5WERwwq2FJQa63Jo3wcAAjrVRLq4QiuEiUVSQOVLKIKU8rXSGUz4Ob2ZaHPtxZKkAAmUYPLiifR0nQQSyIlBhPa1cpSLj7Fasi39fpAA)

In flow, I can typecast with the following, not type-assertion.

**Input:**
```js
type Props = {|
  ...$Exact<PropsWithTFn>,
  ...$Exact<$Call<typeof mapStateToProps, *, *>>,
  ...$Exact<$Call<typeof mapDispatch, *, *>>,
  ...$Exact<withResponse.WithQueryProps<RootQuery>>,
|};
```

However, this gets error message below in prettier 1.15.1

```sh
Replace `<$Call<typeof·mapDispatch,·*,·*>>` with `/*::·<$Call/*::·<typeof·mapDispatch,·*,·*>·*/>·*/`
```

**Output:**
```js
type Props = {|
  ...$Exact<PropsWithTFn>,
  ...$Exact/*:: <$Call/*:: <typeof·mapStateToProps, *, *>*/> */
  ...$Exact/*:: <$Call/*:: <typeof mapDispatch, *, *>*/> */,
  ...$Exact/*:: <withResponse.WithQueryProps<RootQuery>*/> */,
|};
```

**Expected behavior:**
```js
type Props = {|
  ...$Exact<PropsWithTFn>,
  ...$Exact<$Call<typeof mapStateToProps, *, *>>,
  ...$Exact<$Call<typeof mapDispatch, *, *>>,
  ...$Exact<withResponse.WithQueryProps<RootQuery>>,
|};
```

**Comment by j-f1** [comment]
Does upgrading to Prettier 1.15.2 fix the issue for you?

**Comment by jinmayamashita** [comment]
@j-f1 Thanks for your comment! 
I checked Prettier 1.15.2, but same the message is displayed.

Also, I can reproduce it on v1.15.2 playground. :pray:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwDYQDuAOlKZFAM4wYC2AhgA4AiAlpY-TGABZIYBZJmw5deAHgBUAPgwBeDAAoAJu07ceAGgyMAThEaUAlPNmLgpDBgB0tvQcqbLGaAEkorGP3MYArpThdDABffmA-AN1+AGUIWjgAfX9AkJM5WQsoKytWHCVk3RNM7OyKagxwqHp4kPkIwIBuZxLKQk9eJTB6XRgE+wA3VmVAhICYGFYoAHNrBISYAE9GBGq4IuaSjC6AjGIQAEE9sI3NjFVRDUUC6zcPGAAhBYBFX0CFxT3DkCMjJqzT7IAI10cHoAGs-gCQidSvQdnt7kcYSVzupeFdIjcoO5PI8Xm8PiBEd9fsigSDwZCAds4LsQABhJH-KGosQ8DGBLE4h7PV66d57RkkqlQ4GgiFk4Y4ei+PBeMlWVCSDBIbzXOaLZZVeL8OC0RiLX4YSSYdAYOCUPCTGAAWnO9EBeDgNqtUDgCowYspMOCMNZlzJ11uuN5BOKUPqUQqGBwrF01AAcqt+LH471tXBtHg4TAkzqMNnqAkMyEnMzNsEjGXTqTy77-sEy5W-qRNbSAAr6Qx1YAAH2ctmsABIAKIAD3oYBg4k7DgA6p4eAAVABiUGk1ZstlHE6n4iH9PoeDw4jbEDyDEY0RgXDgS4gs8M2kkz+kG4H2-Hk+nB6PJ7PF7CGobLPq+77-IOO7fuIbQwDwABKFqMNAATWAucH4vyj6UOI8EQBAMCYQsb5lr2wQNCAmggAYEwocgoDdPohDtt0CCUMgID0P0EBDJRIDApOYJwDA0ScGAkxTMgMC6K8VE8DAtB4HOPCeEhk5wNEbGeKwgyLBxYCUOxVGTJEMCdvQUwMMg0p4AEVEAFaUGO9y6IJwnRKsAAykxwFJMmZiAjljtEElOi8BG+UgNl2SAnDxoEHH4EQfF6NaC7KHByAABwAAxUfYARzq5jAcXoFqBP0vlUSCACOvhxnA5mWfQ1lHjFAS0KwfmySAlChXA4XwK1tkBTegLpZlSAAExUdJ9CsK6Uz0nEVkoH+fHJEuDrsVFbVwMEwRAA)

Maybe `/* :: (user.__typename: empty); */ // eslint-disable-line` Is related? :eyes:

**Comment by ikatyang** [comment]
@j-f1 There're two bugs in the example:

- `/* :: (user.__typename: empty); */` -> `(user.__typename: empty);`
  - this is the long-standing one
- `...$Exact<PropsWithTFn>,` -> `...$Exact/*:: <PropsWithTFn> */,`
  - this one is somehow caused by `/* :: (user.__typename: empty); */`, it works fine if there's no `/* :: (user.__typename: empty); */`

**Comment by kogai** [comment]
Still occurred at `1.16.4`.
As @ikatyang said, I think this issue treat a confusable situation of prettier when using comment types of Flow.

FYI, I attempt to present smallest reproduction codes [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAiUzAKAawEsoATXOAWwAcYBPASgG51UAdKOAD2ogCcYmSFADOggIK4AKgB4AagD5MAXkwAGJhxAAaEBFpFoI5KACGfPhADuABXMJjKUwDcIRUjpAAjPqbAE4GABlaj8SAHNkGD4AVzhdAAsYSgAbAHUEongRULA4IIcsomcsumRwEWNdEhE4ARtfcMpTZAAzUxTa3QArES4AIV9-QKDTSjgAGRI4KNj4kF6uIIiUuABFGIh4No6ukFC+Wr5y1pTrT2o+Ehg09xgE5AAONV1LiFq032pyy7gj5xmuj4cAAjjEiMCGqYmi0kO1OvNapQiLM4roRCt1pttnDdvMYKYvLdSPdkAAmXTRUxEFIRADCEEozXKHRSnhitSkhMc8NqAF8+UA)

It's just from

```js
/* :: (kind: empty);*/
export const A: T<V> = 0;
```

to 

```js
(kind: empty);
export const A: T/*:: <V> */ = 0;
```

I wonder although the issue labeld as a high-priority bug, but it still not fixed.
Is fixing the issue a hard problem or need to change something external libraries?
Or, if it not so, but not exists enough time of contributers, would you allow me to attempt fixing the issue?

**Comment by j-f1** [comment]
> would you allow me to attempt fixing the issue?

Please go ahead! We appreciate PRs.

**Comment by thorn0** [comment]
Not an issue anymore because support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687

**Comment by fisker** [comment]
Sorry, must hit the wrong button.
