### ISSUE TITLE
Suggested improvement for Vim+ALE integration

### ISSUE THREAD

**Issue by vrde** [prettier/prettier#5447]
**Environments:**
- Prettier Version: 1.15.2
- Running Prettier via: neovim+ALE
- Runtime: Node 10.12.0
- Operating System: GNU/Linux

**Steps to reproduce:**
:wave: hello there, I'm a neovim+ALE user, and after following the steps in [the documentation](https://prettier.io/docs/en/vim.html#ale-https-githubcom-w0rp-ale) I was unable to make *prettier* working for my setup.

TL;DR, I've added those lines to my `$MYVIMRC`:

```
Plug 'w0rp/ale'

let g:ale_fixers = {
\   'javascript': ['prettier'],
\   'css': ['prettier'],
\}

let g:ale_fix_on_save = 1
```

**Expected behavior:**
The expected behavior was to have ALE running prettier, and format the file on save.

**Actual behavior:**
[Standard](https://github.com/standard/standard) was running instead :confused:.

**Possible solution:**
After digging a bit, I found this in the [ALE FAQ](https://github.com/w0rp/ale#5i-how-do-i-disable-particular-linters):

> By default, all available tools for all supported languages will be run. If you want to only select a subset of the tools, you can define `b:ale_linters` for a single buffer, or `g:ale_linters globally`.
[...]
If you don't want ALE to run anything other than what you've explicitly asked for, you can set `g:ale_linters_explicit` to 1.

By adding `let g:ale_linters_explicit = 1` to my `$MYVIMRC` I was finally able to use *prettier* :tada:.

If that's the correct approach, I can make a PR to update the documentation, what do you think?

**Comment by lydell** [comment]
A PR would be great!

**Comment by vrde** [comment]
@lydell here we go! Check #5454 :)
