### ISSUE TITLE
Angular template <textarea> wrong formatting

### ISSUE THREAD

**Issue by yuriykuzin** [prettier/prettier#5450]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeAPGBDATnbAAhgE8AHOAXgB0RMZbDqpCmGZXcIB3AZxpABGAAy1mrCZMJgANtl79aAMwi4AtgFpIsLjMIATAJa9IAV1haI+uAH0b9DXgJiWUyUd7YARjLj7mAHzAwIQA5ghwuNjw+gAixmawAMJWcLyEAL4ZqAD09E7YASAANCAQZDCG0LzIoHhc3AAKTlA1KNgAbhCG+iUgXlFgANZwMADKZNhghlChyDC4pnClABYwajIA6iuG8LyTYHBjCLy7hh27JMjgCn0zvJEwjVGhatjIStgyD6UAVrwYABCgxG42wajgABkZnAPl8fiB-hgxjNQr4AIqmCDwOHfZYgSa4B64a7YWamOQk0pkXAzGCbHowFbIAAcwmpXAemyiZGuNLSkQ6sNK+AAjqZDPhnthXu8kJ88aUHmpDPNFvjTrMMVicfL4ficF4GfomcgAEylBbYQwyVEpNRva5QaDCkCmB4AFW8bQVDyyQA)
```sh
--parser angular
```

**Input:**
```html
<textarea type="text"
          rows="10"
          class="form-control discount-code__text-area"
          disabled
>{{ generatedDiscountCodes }}</textarea>
```

**Output:**
```html
<textarea
  type="text"
  rows="10"
  class="form-control discount-code__text-area"
  disabled
>
  {{ generatedDiscountCodes }}</textarea
>

```

**Expected behavior:**
The text should not be formatted in this case

**Comment by ikatyang** [comment]
According to the spec, the first LF in `<textarea>` can be ignored, but we should not add whitespace in this case since interpolation can be anything.
