### ISSUE TITLE
Add a maximum allowed value for printWidth

### ISSUE THREAD

**Issue by ndbroadbent** [prettier/prettier#5453]
I've just sent a PR to an open source project that uses Prettier, and here is their `.prettierrc`:

```javascript
module.exports = {
    printWidth: 5000,
    tabWidth: 4
};
```

I feel like this should not be allowed. I had a really long multi-line string with linebreaks. I had split it up into different strings using `+`, and it looked fine. But then Prettier crammed it all onto one line that was over 300 characters long.

It would be nice if there was a sane hard-coded maximum for `printWidth`. Maybe something like 130 characters for large high-resolution screens. I saw [the issue about long "it" calls](https://github.com/prettier/prettier/issues/159), and the limit shouldn't apply for those cases.

I guess it's true that if you give people an option, they're going to do something crazy with it.

EDIT: I realized that some developers might turn on word-wrapping in their editor, so they have all the code on one line, but their editor breaks it up into multiple lines. IMO that's the wrong way to do it, because Prettier was designed specifically for code-aware word wrapping. Why would you want to use your editor's terrible word-wrapping, when you can have Prettier's nicer formatting that indents everything properly?

And the other possibility is that there are some developers who prefer to scroll horizontally and view really long lines of code. That makes zero sense to me, but if you're one of those developers, I'd love to hear from you!

**Comment by ndbroadbent** [comment]
@lipis This wouldn't be an error if the lines are longer, and Prettier doesn't stick to this limit for many cases. I'm not sure about JSON, but long strings won't be affected. If you have lots of data in a JSON file then you probably don't want Prettier to format that. And if you do care about the formatting because you want the data to be readable, then really long lines are a problem.

**Comment by lipis** [comment]
Plus I really don't see why we should limit that number.

**Comment by ndbroadbent** [comment]
When people set it to a really high number, it makes it impossible to format long multi-line strings. Example: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACd6YAsBOEDuqUchAojnjgBQAGAJMALZwDOLAhgOZwC+AOnygCoqACIBLACaoAnhACuqeQAdJ7eKjA446uAFpt7MDD3tly1BByacRiKm1gEMADYyA-KhqoA1KkEYgUHBGDTCAAouOixwqDDsANax7KguEBAJqOqoLBDMDnBOsKjibPKsJSJadllQ0lo68AY6xqbmXr4BId1BNDD2MbHiAGY5eXDQsVjsLKjDCnVZYy7yMOLQSP6Cwt5+XT0HNABUqAyc4jAAEvIARgCSZXAAqjguVHwgLNPanLoA9NVIB8ADSoACO5RwMgAlPxBLt9gdusdTsBzldbg8WOUXm8PsMjHAbukEgDDE1DK0zMoQeDITC4VAaNCANyoEDAkAQZRraAsZCgdgUAjhIUIfkodgANwgUg5IButjASRgAGVlEZxFBOMgYDhypysDBGC4AOpYC6sDVOVXii7iKUXGTIcBseVamI4GDhWycRjsZAElwxTkAKxYAA8AEJKlWq9jMAAyWrggfYwbgYcjqq1nCiAEV5BB4GmM5yNThPS6buwbjI0lB5cocFqYKapNhkABWAAMffLeBiptsyhdzdYcBwUtTnO0EPE2h9XH9pZDnzgjHEuv1mc+uYLRZLSCDa-iN3bkk7SAATJy9exxC5cwBhPIrlBQSby+QxAAqtYlE9eB4IA

**Comment by ndbroadbent** [comment]
But really I just want to understand why people feel the need to set this option to a really large number for their JS projects. I'm probably missing something about their IDE, or what kind of code they're writing.

**Comment by lydell** [comment]
Can't you ask the project maintainers to change their config to a more sane value? Or am I missing something?

**Comment by ndbroadbent** [comment]
@lydell Yes I did that, but I also wanted to see why this value was allowed, and if it might be a good idea to prevent other people from doing that.

No problem if not, but I'm really curious to know why some people want to set it to extremely high values. It just doesn't seem necessary.

**Comment by ndbroadbent** [comment]
@lydell Sure I [just asked them](https://github.com/sharegate/craco/issues/8), and I've opened [a PR to change the setting](https://github.com/sharegate/craco/pull/19). I also wasn't the [first person to talk about the prettier settings.](https://github.com/sharegate/craco/pull/4#issuecomment-436534833). 

I think whoever wrote the `.prettierrc` might not be familiar with Prettier, and thought it was similar to an `.eslintrc`, so that setting a very high value would just disable some warnings. But Prettier doesn't work like that, it actually formats your code based on this setting, and can lead to weird situations like multi-line strings being forced into one huge line.

That's another reason for setting some sane limits for the options. It will prevent this kind of misunderstanding.

**Comment by lydell** [comment]
> That's another reason for setting some sane limits for the options, because it will prevent this kind of misunderstanding.

Only if the person sets it to something above the limit we choose. And finding that limit will be really hard. So it doesn't feel like this will work out in practice. Let's see what responses we get over at https://github.com/sharegate/craco/issues/8 and re-open this if needed.

**Comment by ndbroadbent** [comment]
Ok sure, sounds good! FWIW, I'd suggest 150 as the limit. That would give you really long lines for large high-resolution displays, and I can't think of any reason to set it much higher than that.

**Comment by kachkaev** [comment]
@ndbroadbent my personal rule is: _when in doubt, just stick with Prettier's default and don't crowd `.prettierrc` with options_. Paying attention to what the code does than _how exactly_ it is formatted pays for itself in my view 😉

**Comment by ndbroadbent** [comment]
@kachkaev I totally agree! This definitely wouldn't be an extra option - My suggestion is to actually limit the existing option even further and set a maximum allowed value.

**Comment by kachkaev** [comment]
I agree with the rest that this is not necessary. There's no objectively optimal value that we could use for that and there's no research we theoretically conduct that would let us pick it. Limiting the `printWidth` to, say, 10000 is no better than to 500. Or 200. Or is 200 worse than 500? Or not? Maybe 142? Or 1000?

Any picked limit will cause a new issue in this repo sooner or later as there will be a valid reason for someone to just slightly exceed the number we've defined. No limit also means no additional rule to read in the docs and so one less thing to remember.
