### ISSUE TITLE
Prettier adds extra closing bracket when a pre tag contains elements with angular template reference variables

### ISSUE THREAD

**Issue by mister-walter** [prettier/prettier#5457]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgJzgPlZAEzgAIBiAMwgjwHpDdUatcQAaECdGAS2gGdkoAIaZMEAO4AFEQgEohANwjcCbEACNMQsAGs4MAMrpt3KAHNkMTAFc47ABYwAtgBsA6ve7w+xsHAOyXtwKXgCeyOB8AuymfHCYMJJaZk5CyORCLnHsAFZ8AB4AQlq6+gZCTnAAMqZw6ZnZIHn5BqZmLnAAitYQ8PVZdiDGmHGYEULm1i4ialimMG4qMPbIABwADOxYEHFuWugRzKMKdezYAI7W3NhJQilpSBkD7HFO3JY2g3xtHd29dY8GoMYEJ1IsCMtkAAmdhWITcFxtADCECcqQiUGgpxA1jiABVQXInnEAL4koA)
```sh
--parser angular
```

**Input:**
```html
<pre><code #foo></code></pre>
```

**Output:**
```html
<pre><code #foo></code>></pre>

```

**Expected behavior:**
Prettier should not add an extra closing angle bracket after `</code>`

EDIT: changed example to use `<code>` instead of `<p>`. This is how I originally found the bug, not sure why I thought it would be better to replace `<code>` with `<p>`...

**Comment by thanhcng** [comment]
Can I try this one pls?

**Comment by ikatyang** [comment]
Sure. We currently do not support non-text/interpolation node in a `<pre>` tag so we just preserve the content, but it seems the location that we used for slicing text from source is somehow wrong:

https://github.com/prettier/prettier/blob/81a72cc2d640b050bb31ea163cc1fbf8ae0f2f48/src/language-html/printer-html.js#L472-L496

**Comment by mister-walter** [comment]
Just a heads up, I updated the issue to use `<code>` instead of `<p>` in the example, since `<p>` is not allowed inside of a `<pre>`. I originally found this bug using a `<code>` inside `<pre>`, so I'm not sure why I changed it to `<p>` when submitting this issue.

This shouldn't change anything, but wanted to update it to reduce confusion.

**Comment by michaeljota** [comment]
As a workaround you can span the `code` block to a new line.

**Comment by thanhcng** [comment]
How do I test the result after fixing the code?

**Comment by mister-walter** [comment]
Create a file `foo.html` containing the code ```<pre><code #foo></code></pre>```, and then run prettier on it (`prettier foo.html`). If the output does not contain the extra closing angle bracket, you should be good!

**Comment by ikatyang** [comment]
We use snapshot testing to verify the result, see [CONTRIBUTING.md](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md#contributing-to-prettier) for more info. 

In short, you could create a temporary test file just like what @mister-walter said, and run `bin/prettier.js foo.html` to see if it works. If it works, put it in the `tests` folder and run `AST_COMPARE=1 yarn test -u`, it should be good to send the PR if everything worked as expected.
