### ISSUE TITLE
unexpected formating in special IE conditional comment

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#5459]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UGAtGwNoCWAZuXRjkAkhQCcAXQapq9cmDoBDAM7KAvExB04Ac0VgAnm25xN09JwQATPhI7NW6Dj3474I8VPZtpsxt4xLKBteOx8WcnIZOEUraQB6Shi4iKiAIwgrAwSMrIdURNpGEAAaEAgABxhuaGVkUEUAJ0aIAHdiJoQ6lEUANwhuK1KQNMb9AGs4GABlCv1uKB1kGEaAVzgyvwB1Sm54ZTmwOGmuve5evYNkcFVhheU4RphiMZ0aRWReRToHsoArZQADwAQmMwJMZooaHAADILOCfb6-EAAwHTBY6bQARVWEHgiJ+GxAc0aD0a1z8wwqjQWMC2gxglGQAA4AAxlakQB5bMYVa7UuBk3oIsqNOAAR1W3DFL0Ubw+SC+hLKDxo3GWayJygx2Nx+MVSKJMEUaXpVkZyAATGUVopuHQMbgIDR3tcoNARSBVg98CbukqHgBfQNAA)

**Input:**
```html
<!DOCTYPE html>
<!--[if lt IE 9]><html class="legacy-ie"><![endif]-->
<!--[if gte IE 9]><!--><html><!--<![endif]-->
  <head></head>
  <body></body>
</html>
```

**Output:**
```html
<!DOCTYPE html>
<!--[if lt IE 9]><html class="legacy-ie"><![endif]-->
<!-- [if gte IE 9]><! -->
<html>
  <!-- <![endif] -->
  <head></head>
  <body></body>
</html>
```

**Expected behavior:**
```html
<!DOCTYPE html>
<!--[if lt IE 9]><html class="legacy-ie"><![endif]-->
<!--[if gte IE 9]><!--><html><!--<![endif]-->
  <head></head>
  <body></body>
</html>
```

I understand that in morden browser, 3rd line is considered as two normal comment, but it's still a IE  conditional comment

**Comment by ikatyang** [comment]
It looks like we should treat `<!--[if ...]><!-->` and `<!--<![endif]-->` as IE conditional start/end comment, and add a special case for a single opening tag surrounded by IE conditional start/end comment.

**Comment by ikatyang** [comment]
@fisker Can you open another issue for it? It does not look easy enough to be implemented here. (It's simple for a single opening tag, but I guess you want something more advanced?) It probably needs to traverse the whole tree to find the corresponding start/end comments since it does not follow the normal structure, and we have to think how to print it if it's in inline element or other situations.
