### ISSUE TITLE
Flow call expression generic with union type is parsed incorrectly with babylon parser

### ISSUE THREAD

**Issue by FezVrasta** [prettier/prettier#5460]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVAFnAWzkwF5MAlOAQzBgDowAna+AYWngA8YAeAHRAAbAJYBzXDAGYAPpgEATKowDWAgHwAKASPGSQASgDcfKCAA0ICAAcYw9MlBLGEAO4AFJQjTIQVAG4QwvLmIABGjDTKcDAAylY0wlCiyDCMAK5wFhIEggDquMLwaPFgcDFehcJ+hQCePmBo3haJaHCMMG4RogRUyABmVIKtFgBWaJwAQhFgUbFURAAyiXD9g8MgY5wxiaKCcACKaRDwq0OZIPGMrYw+oVShNYLQIVaMiTC5QTC4yAAcAAwWV4QVq5CJWHyvODXPwrCzMACOaWEzE6VG6vSQAzOFlaBGEKXS5zQOz2h2OKyxa3OMHun3k32QACYLKkqMIREl2AQej4oNA4SA0q1sPdvFSzgBfSVAA)

**Input:**
```jsx
const Theme = React.createContext<"light" | "dark">("light");
```

**Output:**
```jsx
const Theme = (React.createContext < "light") | ("dark" > "light");

```

**Expected behavior:**
```jsx
const Theme = React.createContext<"light" | "dark">("light");
```

This seems pretty bad.

**Comment by ikatyang** [comment]
This looks like an edge case in babylon. As a workaround you could use `--parser flow` for now:

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVAFnAWzkwF5MAlOAQzBgDowAna+AYWngA8YAeAHRAAbAJYBzXDAGYAPpgEATKowDWAgHwAKASPGSQASgDcfKCAA0ICAAcYw9MlBLGEAO4AFJQjTIQVAG4QwvLmIABGjDTKcDAAylY0wlCiyDCMAK5wFhIEggDquMLwaPFgcDFehcJ+hQCePmBo3haJaHCMMG4RogRUyABmVIKtFgBWaJwAQhFgUbFURAAyiXD9g8MgY5wxiaKCcACKaRDwq0OZIPGMrYw+fYKuIVaMiTC5QTC4yAAcAAwWTxBWrkIlYfE84Nc-CsLMwAI5pYTMTpUbq9JADM4WVoEYQpdLnNA7PaHY4rdFrc4wKihN7yD7IABMFlSVGEIiS7AIPR8UGg0JAaVa2Gp3nJZwAvuKgA)
```sh
--parser flow
```

**Input:**
```jsx
const Theme = React.createContext<"light" | "dark">("light");

```

**Output:**
```jsx
const Theme = React.createContext<"light" | "dark">("light");

```

cc @existentialism

**Comment by j-f1** [comment]
You can also use `// prettier-ignore` to work around the issue in the meantime.

**Comment by ikatyang** [comment]
Tracked in babel/babel#9070.

**Comment by existentialism** [comment]
Since https://github.com/babel/babel/pull/7934, the @babel/parser will only attempt to parse this if `@flow` pragma is present in the file or `all` option is passed to the flow plugin in its options (`["flow", { all: true }]`)

**Comment by j-f1** [comment]
Should Prettier add an option to enable `all: true` for the Babylon parser?

**Comment by ikatyang** [comment]
How about adding a `babylon-flow` parser (and `babylon-typescript` for TS)?
