### ISSUE TITLE
Don't add space adjacent to html tags in some situations, even when ingonring whitespace sensitivity

### ISSUE THREAD

**Issue by karptonite** [prettier/prettier#5462]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdAeAzgBwIZSoBmEEAvADogBGeATlarQF6UjMedfc+9-9cqAPhIQMAelwEhAOgqF0IADQgIOGAEtoWZKHp0IAdwAK9BDpR4AbhA0ATZTTp4wAazgwAyvjAaoAc2QYOgBXOBUACxgAWwAbAHUIjXgpMDhPc2SNK2SAT2QQDX8oCDo4Rz8sODoYY2d-aLxkIjxYqpUAKywADwAhZzcPTzxouAAZP3KkFrbwkC7uzz9-WLgARRCIeGbW9pB8Oiq6AoJ-ENj6Rxw6Pxh4+xgI5AAOAAYVa4gq+OccAuu4EcrOUVGUAI4hDRlOp4BpNaa7OZVaIaIKhJHLVYbLZTGZ7GB4aj3OyPZAAJhUwTwGliywAwhBoo0CiUoCCQCEqgAVQkWPFwAC+AqAA)
```sh
# Options (if any):
--html-whitespace-sensitivity ignore
```

**Input:**
```html
<span foo="bar" baz="zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz">foo</span>.
 ```

**Output:**
```html
<span foo="bar" baz="zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz">
  foo
</span>
.
```

**Expected behavior:**
```html
<span foo="bar" baz="zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz">
  foo
</span>.
```

This may be related to #5449 and #5439, but I think it may be distinct. The basic issue here is that even when "ignoring" whitespace, I believe prettier shouldn't be adding whitespace to the outer "edges" of elements. That means that adding whitespace on the inside "edge" of an element, say after `<span>` or before  `</span>`, is OK, but adding whitespace just outside of an element can be an issue. As it is now, there is now way to both ignore whitespace on the inside edge of an element, but keep it on the outside.

I'd argue that adding the space before the period in this example is essentially equivalent to adding a space in the middle of a word--this is whitespace that will always be important.

This is particularly relevant for Angular users, which by default strips whitespace from code in most cases.

**Comment by thorn0** [comment]
>  means that adding whitespace on the inside "edge" of an element, say after <span> or before </span>, is OK, but adding whitespace just outside of an element can be an issue.

How exactly this `<span>foo </span>.` is more OK for you than this `<span>foo</span> .`? Can you elaborate?

> this is whitespace that will always be important

It is not really clear why you think it is more special than the white space before `</span>`. It is important in inline context only and only if the preceding inline element doesn't end in another whitespace. E.g. if `display: block` is specified for that span, this white space will be ignored by browsers. By default (`--html-whitespace-sensitivity css`), Prettier hopes that there is no such tricky CSS, but if there is, `--html-whitespace-sensitivity strict` should be used.

I'm not sure what the use case for `--html-whitespace-sensitivity ignore` even is, but using this mode you're basically saying to Prettier that you don't care about white spaces. If you do care, why use this mode?

> This is particularly relevant for Angular users, which by default strips whitespace from code in most cases.

Interesting. How exactly Angular Compiler decides which white spaces can be removed?

**Comment by thorn0** [comment]
So, Angular by default simply removes white-space-only text nodes: [demo](https://stackblitz.com/edit/angular-kyiwx1?file=src%2Fapp%2Fapp.component.html), [src](https://github.com/angular/angular/blob/cf0968f98e844043a0f6c2548201f3c0dfd329a7/packages/compiler/src/ml_parser/html_whitespaces.ts#L71)

This behavior can be changed by setting `preserveWhitespaces` to true:
1. globally (app-wide), [separately for JIT and AOT at that](https://stackoverflow.com/a/46619232/76173)
2. component-wide: pass `preserveWhitespaces: true` to the `Component` decorator
3. element-wide: in the template: use the `ngPreserveWhitespaces` attribute

Now I see why Angular developers can have different expectations regarding white space formatting than the rest of those who write HTML.

**Comment by karptonite** [comment]
Wow, I wast totally wrong, actually. it turns out that 
```html
<span foo="bar" baz="zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz">
  foo
</span>.
```
also inserts a space after foo with Angular set to not preserve whitespaces.
Under the circumstances, that means that my original point is wrong. There may be some better setting in prettier for Angular, but I'm not sure what it would be.

**Comment by thorn0** [comment]
Why don't the default settings work for you?

**Comment by karptonite** [comment]
@thorn0 only that it ends up looking kind of ugly in some cases. I can open another issue with a concrete example of where I think it ends up looking ugly.

**Comment by thorn0** [comment]
Why not? Go ahead.
