### ISSUE TITLE
css-in-js: extra space in var(...)

### ISSUE THREAD

**Issue by maraisr** [prettier/prettier#5465]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEA5nDAGoCGATuTrAPIBucllOAJnAM4AUADpRF6ck+AJIAFAUICU+YAB0o8mJwDuOGGAAW+PlM4A6BlRwIYshUpjKw5TnHwBRCqzMGAMrQDWSRcv8wlCTolFD4YJycAAZ+1nE2EAA2EJQixpTcALSZhMkARuSJ2ZDJlNmE1ACemQCcAAx10gDcsQHKBWBeFRCYbJklKSKB5FCcvFRmLUpWbTAAZEhaEEyUcq3xcR1dAr39SYP46Vk5+YXF+2U5VZkATA3N67MDqYdUx7kQBUV7pdmJ3g8ZhsAL6PGBRKYBDiocjoRIwXzWIHKIIwEJhCLRMHtcidbq7Z5pN7lU7fZ7ZAAkwH4gkM6VMsGBgOx80Wy2Ya2RGy2+KgfUJrwyJM+Zx+KUp1P0RhMZmBAH05dA4MyNspQdNZsoFrjcExOZrNrjtj0+WKXkdhV9zr9MlSaUJpa5GQqYKoICrZurZhDYurgSAADQgQS4aCcZCgKgCVTiCajZAgcgMCDsQMgPLUTokADK4zAtEIyEC6DgQa0MAAtokAOpaDRcPNwbMITgaHAMDSVBOYtO0eyUGCSciECvkZAwxL2IMAK04AA8AEKZrw58gVuCeKBwceFKcgWdz7MFxJwACK6Ag8B3k9LIHGlH7CZglV4XDArF4MDT-FoMGr7BgLRkAADjqIMaXsatqF4BN+C4ZgmDTIIAEd0BwIIhxHMckAnPd7ArHAi0oEsg1bKBcjPC8ryQYtbxgcg8n-NhAOQABWINhhwf5yIAYQgCtRwTKAlTTdB7AAFQY8MaOIuBgWBIA)
```sh
--parser typescript
--single-quote
--tab-width 5
--use-tabs
```

**Input:**
```tsx
function getVaraintOverrides(props: IProps) {
	switch (props.varient) {
		case EVarient.Link:
			return css`
				color: var(--global--color--gray-900);
				background-color: transparent;

				&:hover {
					background-color: var(--global--color--gray-200);
					color: var(--global--color--link);
				}
			`;
		default:	
			return css`
				background-color: var(--global--color--${props.varient});

				&:hover {
					background-color: var(--global--color--${props.varient}__one);
				}

				&:active {
					background-color: var(--global--color--${props.varient}__two);
				}
			`;
	}
}
```

**Output:**
```tsx
function getVaraintOverrides(props: IProps) {
	switch (props.varient) {
		case EVarient.Link:
			return css`
				color: var(--global--color--gray-900);
				background-color: transparent;

				&:hover {
					background-color: var(--global--color--gray-200);
					color: var(--global--color--link);
				}
			`;
		default:
			return css`
				background-color: var(--global--color-- ${props.varient});

				&:hover {
					background-color: var(
						--global--color-- ${props.varient}__one
					);
				}

				&:active {
					background-color: var(
						--global--color-- ${props.varient}__two
					);
				}
			`;
	}
}

```

**Expected behavior:**
```diff
function getVaraintOverrides(props: IProps) {
	switch (props.varient) {
		case EVarient.Link:
			return css`
				color: var(--global--color--gray-900);
				background-color: transparent;

				&:hover {
					background-color: var(--global--color--gray-200);
					color: var(--global--color--link);
				}
			`;
		default:
			return css`
-				background-color: var(--global--color-- ${props.varient});
+				background-color: var(--global--color--${props.varient});

				&:hover {
					background-color: var(
-						--global--color-- ${props.varient}__one
+						--global--color--${props.varient}__one
					);
				}

				&:active {
					background-color: var(
-						--global--color-- ${props.varient}__two
+						--global--color--${props.varient}__two
					);
				}
			`;
	}
}

```

**Comment by maraisr** [comment]
current solution `// prettier-ignore`

**Comment by lydell** [comment]
Another workaround is to use "double" interpolation:

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEA5nDAGoCGATuTrAPIBucllOAJnAM4AUADpRF6ck+AJIAFAUICU+YAB0o8mJwDuOGGAAW+PlM4A6BlRwIYshUpjKw5TnHwBRCqzMGAMrQDWSRcv8wlCTolFD4YJycAAZ+1nE2EAA2EJQixpTcALSZhMkARuSJ2ZDJlNmE1ACemQCcAAx10gDcsQHKBWBeFRCYbJklKSKB5FCcvFRmLUpWbTAAZEhaEEyUcq3xcR1dAr39SYP46Vk5+YXF+2U5VZkATA3N67MDqYdUx7kQBUV7pdmJ3g8ZhsAL6PGBRKYBDiocjoRIwXzWIHKIIwEJhCLRMHtcidbq7Z5pN4AEmAUXKp2+z2ypP4gkM6VMsGBUWBgOx80Wy2Ya2RGy2+KgfUJrwypPJJ0+Zx+KRpwDpQiMJjMwIA+qroHBWeyNspQdNZsoFrjcExeYbNrjtj0hTKXkdxRSpVSLnKFQzlcz1TBVBBtZDdTB9bMIbF9cCQAAaECCXDQTjIUBUASqcQTUbIEDkBgQdhRkB5aidEgAZXGYFohGQgXQcGjWhgAFtEgB1LQaLjluAlhCcDQ4BgaSqZzH52j2SgwSTkQiN8jIGGJezRgBWnAAHgAhIteUvkRtwTxQOALwrLkBr9clyuJOAARXQEHgp6XdZA40oE8zMEqvC4YFYXgYHzfhaBgFt2BgLRkAADjqaM6XsFtqF4TN+C4ZgmHzIIAEd0BwIJp1neckEXc97EbHBq0oWtoz7KBcnvR9nyQGs3xgcg8ggtgoOQABWaNhhwf4GIAYQgRs50zKBNXzdB7AAFU4hNWJouBgWBIA)
```sh
--parser typescript
--single-quote
--tab-width 5
--use-tabs
```

**Input:**
```tsx
function getVaraintOverrides(props: IProps) {
	switch (props.varient) {
		case EVarient.Link:
			return css`
				color: var(--global--color--gray-900);
				background-color: transparent;

				&:hover {
					background-color: var(--global--color--gray-200);
					color: var(--global--color--link);
				}
			`;
		default:	
			return css`
				background-color: var(${`--global--color--${props.varient}`});

				&:hover {
					background-color: var(${`--global--color--${props.varient}__one`});
				}

				&:active {
					background-color: var(${`--global--color--${props.varient}__two`});
				}
			`;
	}
}
```

**Output:**
```tsx
function getVaraintOverrides(props: IProps) {
	switch (props.varient) {
		case EVarient.Link:
			return css`
				color: var(--global--color--gray-900);
				background-color: transparent;

				&:hover {
					background-color: var(--global--color--gray-200);
					color: var(--global--color--link);
				}
			`;
		default:
			return css`
				background-color: var(
					${`--global--color--${props.varient}`}
				);

				&:hover {
					background-color: var(
						${`--global--color--${props.varient}__one`}
					);
				}

				&:active {
					background-color: var(
						${`--global--color--${props.varient}__two`}
					);
				}
			`;
	}
}

```

**Comment by fisker** [comment]
minimum reproduction

https://prettier.io/playground/#N4Igxg9gdgLgprEAucBnVADAOlADgJwlyQAIA3AQ3wAoBaWgcwBsIAjCp+yF-egEmAEiqAHSV8ASwQwAvgEoA3DgwgANCCIwJ0VMlBVCAdwAKVBLpQUyECQBM1IVvgpgA1nBgBlXC4lQGyDD4AK5w6gAWMAC2TADq4RLwqD5gcJ7miRJkiQCeyGi66n6ocPgwxs4MURTIAGYcJeoAVqgAHgBCzm4enhRRcAAyfnB1DWEgLa2efsxwAIrBEPCjTI0gPvgl+PkwObhwqGCSuDAOBH4wsXYw4cgAHAAM6kIlsc64+QQHpWQj6gCOi3gFWE+QoqFoUDgcFsMIc+DggIkCIqFCqNSQ9VW4xKUQkgRCOJmTHmQJGSCCoXUMAorCuthuyAArNTnBImDMAMIQKLVfJQaB-EDBEoAFVpFkpcBkMiAA
