### ISSUE TITLE
Feature Request: Add MJML Formatting

### ISSUE THREAD

**Issue by iamclaytonray** [prettier/prettier#5471]
Can we add support for formatting MJML templates?

[Official Website](https://mjml.io/)

Shouldn't be too hard to add support, since it's essentially HTML. I'm willing to contribute to a PR for this but also wouldn't mind some guidance/advice. Thanks!

**Comment by j-f1** [comment]
Are there any syntactic differences from HTML?

**Comment by j-f1** [comment]
Feel free to open PRs adding support for this. It seems like there wouldn’t need to be a custom `mjml` parser, since the HTML parser could be expanded to support MJML. It seems like you just need to add support for those tags to the parser, then update it in Prettier.

**Comment by ikatyang** [comment]
Self-closing tags are allowed in the `vue` parser, I guess you could use it directly if there's no syntax conflict with vue?

**Comment by n1ru4l** [comment]
@ikatyang AFAIK there should be no conflict, it is just custom html-tags. I tried fiddeling around with setting the `canSelfClose` for html to true and it worked quite fine.

Will try to do some more testing when I got more time and eventually send a pull request for a MJML formatter!

**Comment by iamclaytonray** [comment]
Sorry, just woke up.

I agree that Vue would probably be the best option to base off of for MJML. I have to finish up a couple of work items but afterwards, I'm going to spend a bit of time playing around with this. Thanks guys!

**Comment by blowsie** [comment]
Should i expect to see this working in VSCode?
I have prettier `^1.16.4` in my project, prettier menus and actions are showing and working fine on `.html `files but not `.mjml` files

Of course, running from the CLI works fine.
