### ISSUE TITLE
Preserve line-breaks on multiline HTML content

### ISSUE THREAD

**Issue by cormojs** [prettier/prettier#5472]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABMagEYQAmAnoSaWVQJYBuxzVAvASPAM4xe9RowCGYoqNQB6FqxFkZlWvVmZceEABoQEAA4xm0fslBiAThYgB3AAqWEplGNYROOkOQtiwAazgYAGV9X2YoAHNkGAsAVzhdDRwAdXRmAVCwOCCndLZ0mmRwflNdcP44Cxg7HwisMWQAMzEcCt0AK34ADwAhH39AoLEsOAAZcLgmlraQTq6g8IicOABFWIh4KdaEkFCLCosipM99C3CYZM4YdGQADgAGXVOICuSffSLTuAPWSd0LOAAR1izABNTEdQaSGa210FSwzGicR2-EWyzWG0m0OmOxgYnIlyo12QACZdDExMwcIsAMIQLD1IpQaB-ECxCoAFXxzhhFQAvnygA)

**Input:**
```html
<html>
  <body>
    <div id="test">
      aa
    </div>
  </body>
</html>
```

**Output:**
```html
<html>
  <body>
    <div id="test">aa</div>
  </body>
</html>
```

**Expected behavior:**
Preserve line-break before and after "aa".
```html
<html>
  <body>
    <div id="test">
      aa
    </div>
  </body>
</html>
```
This situation is similar to preserve multiline array notation of JavaScript.

**Comment by thorn0** [comment]
Why do you want those line breaks? How exactly is it similar to arrays?

**Comment by cormojs** [comment]
Because in the case of ignoring the white sensitivity of the CSS, I want to insert a line feed for readability.

It's exactly the same reason as aligning arrays

**Comment by thorn0** [comment]
But Prettier doesn't do this with arrays if they fit within `printWidth`. [See?](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAbQB0pNMByba7C0gXQG4QAaECABxgEt1lRsAJ0EQA7gAUhCNMhDYAbhG4ATViABGg7GADWcGAGUO27lADmyGIICucNgAsYAWwA2AdXvd4aY2DgHpL255LwBPWTA0GTZTNDhBGHEtMydsZAAzbBc4tgArNAAPACEtXX0DbCc4ABlTOAysnJB8goNTMxc4AEVrCHgG7LsQY0E4wVl1bHVQl2g1DkFTGDcVGHtkAA4ABjYFiDi3LQ5ZBbgx+Xq2QTgAR2tua6TsFLSkTMG2OKduSxshtHanR6fXqb0aQxgUxWyjWyAATGwrNhuC52gBhCBOVKyKDQS4gaxxAAqUxkYMGAF8KUA)

**Comment by cormojs** [comment]
Sorry I had made a mistake arrays for objects. I have a similar motivation to multi-line object. See this [example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBXNcBOmAvJsADpSaZQCGAtnEpmSAFIQAWlAIhHCwBoKVGgHNGmAMwAGCgF8A3CAEgIABxgBLdMlA18+CAHcACvoRpkIGgDcImgCbKQAI3w0wAazgwAymo9NKFFkGHxsOBUOGDoAGwB1Dk14NACwOF8LZM0bZIBPKzA0SxUgvHwYE3dROhpkADMaWLwVACs0AA8AIXcvH196OAAZILgGppaQdo7fINFYuABFbAh4cebIkAD8cqsXGhc82OhnNXwgmHjHGA5kAA5pFTOIPHj3NSszuHKbMZV8OAAR2wmgBVTEtXWkzwdE0oXCmzQcwWy1WYyQjQ2KhgByuDhuyAATNj3JpYnMAMIQOiQlBQaB-EC4OAAFQOlgxEzgcjkQA).

**Comment by thorn0** [comment]
So are you proposing to always add such line breaks to all block elements regardless of `printWidth` or to preserve existing line breaks?

**Comment by cormojs** [comment]
I am proposing to preserve existing line breaks.

**Comment by AndreasGassmann** [comment]
It would be nice if something like this could be added. There is not really a technical reason, but after including prettier into our project, I got a lot of reports from people complaining about the "weird" HTML formatting. Our `printWidth` is quite high, which works fine for code, but the formatted HTML does indeed not look that nice.

Eg.

Input:
```
<ion-header transparent no-border><ion-navbar hideBackButton transparent><ion-title>A long title of the page</ion-title></ion-navbar></ion-header>
```
Output:
```
<ion-header transparent no-border>
  <ion-navbar hideBackButton transparent><ion-title>A long title of the page</ion-title></ion-navbar>
</ion-header>
```
Expected:
```
<ion-header transparent no-border>
  <ion-navbar hideBackButton transparent>
    <ion-title>
      A long title of the page
    </ion-title> 
  </ion-navbar>
</ion-header>
```

The expected output is just more readable in my opiniton.

Empty elements like `<div style="..."></div>` should still be put on one line.

Now I guess the big question is what you do with tags that only wrap a couple of words, like this:

Input:
```
<h1>
  This is some text with that is <strong ion-text color="primary">correctly</strong> <b>formatted</b>.
</h1>
```
Output and expected (should stay like that):
```
<h1>
  This is some text with that is
  <strong ion-text color="primary">correctly</strong>
  <b>formatted</b>
  .
</h1>
```
Wrong (might happen if the changes proposed in this issue are added):
```
<h1>
  This is some text with that is
  <strong ion-text color="primary">
    correctly
  </strong>
  <b>
    formatted
  </b>
  .
</h1>
```

I don't know how this can be handled. Maybe make it dependent on the length of the child node? If that's not possible, then I prefer the latter "wrong" one where every tag is split across multiple lines to the current formatting.

Any thoughts?

**Comment by j-f1** [comment]
You could use try overriding the `printWidth` for HTML files only @AndreasGassmann.

**Comment by yanni4night** [comment]
Line-breaks are required sometimes.

See this vue file input:

```html
<template>
    <div>
        <div name="f">
            <p>sd</p>
        </div>
        <ul name="f">
            <li>sd</li>
        </ul>
    </div>
</template>
```

output:

```html
<template>
    <div>
        <div name="f"><p>sd</p></div>
        <ul name="f">
            <li>sd</li>
        </ul>
    </div>
</template>
```

This really makes me confused. Overriding *printWidth* does not work properly.

We may shutdown formatting html, is there any option to do it?

**Comment by hawkrives** [comment]
When you say "required", are you saying that the lack of newlines there breaks your app, or that you prefer the formatting with them?

**Comment by yanni4night** [comment]
@hawkrives Line-breaks may not break my app, but break the visual format, e.g.

```html
<div class="list">
    <div class="item">Jan</div>
</div>
```

We may add another "item" next time,

```html
<div class="list">
    <div class="item">Jan</div>
    <div class="item">Feb</div>
</div>
```

We prefer the line-breaks being preserved, so the number of lines which changed/added is only one, instead of three even more.

The most important is, the dom tree is clear enough for reading.

That's only my own understanding. Now I have to add a html comment to prevent from being collapsed.

```html
<div class="list">
     <!-- prevent-collapsed -->
    <div class="item">Jan</div>
    <!-- prevent-collapsed -->
    <div class="item">Feb</div>
</div>
```
