### ISSUE TITLE
BUG: formatting ejs creates wrong code

### ISSUE THREAD

**Issue by MohGanji** [prettier/prettier#5474]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UBMqAllAA4CuMABKgKR1kBmAFAISs4CGA5gEpgdRnjoATMgGdeAIxxwJDRgF8xdAPSEoqTZlx4QAGhARKMMtGnJQvAE72IAdwAKDhDZS8AbhDISJiBy9rxgANZwMADKlGEU-Mgw9tRwpgY4AOroZPDScWBw0Z65ZD65AJ7I4NI2phTScPYwrqH8WLzIrLw4jaYAVtIAHgBCoRFR0bxYcAAyFHBdPX0gg0PRCYoAitQQ8Eu9aSBx9o321RlBlPYUMJkBMOjIABwADKbXEI2ZoZTV13Azj5FqZ7HAAI7UMhg1oCDoHFaNLBkJIpI7STZwHZ7RZIbqHUwweT3CSPZAAJkJoTIOASAGEIFh4SgoNAQSBqI0ACryLz4la8aQwBFHCQQMAi0wQWg0GDkkWqVRAA)
```sh
--parser html
```

**Input:**
```html
<html>
	<input <% if(!flag){ %> disabled <%}%> />
</html>
```

**Output:**
```html
<html>
  <input <% if(!flag){ % />
  disabled <%}%> />
</html>

```

**Expected behavior:**
when using prettier before it did not put any `/` at the end of any `>` symbol, but now it separates '%' and '>' (they together make ejs closing tag) puts slash before the `>` symbol, so the ejs file fails to compile!

expected output should be something like this:
```html
<html>
  <input <% if(!flag){ %>
  disabled <%}%> />
</html>
```

**Comment by ikatyang** [comment]
We do not support ejs, and its syntax is conflict with HTML (the first `>` after `<input` will be recognized as `input`'s opening tag end marker in HTML). I have a similar explanation that can also be applied here, see https://github.com/prettier/prettier/issues/5428#issuecomment-437412183.

**Comment by MohGanji** [comment]
@ikatyang I know that you don't support ejs, but I was writing ejs files using prettier html language and I did n't have this kind of problem, I mean I had this same piece of code, and it worked right until recently, but when I updated the code and tried to save the file, prettier made a big change to the file and also made a bug in this part of code, thats why I added this issue here. I hope there is an explanation

**Comment by ikatyang** [comment]
@MohGanji The HTML support was added in 1.15. I guess you probably wrote ejs in a `.html` file and updated the prettier editor extension recently, so it started to format your ejs on save? If it's not the case and it's reproducible using Prettier CLI, can you share the filename and its content?

**Comment by MohGanji** [comment]
@ikatyang 
Okay, here is the scenario I'm in: I had an `.ejs` file, that was working with prettier (not working well, just working) prettier formatted the html code and I was happy with it, but when I tried changing the file recently(none of the configs changed, I only changed some other unrelated part of the code) but after saving the document, prettier changed the formatting and also changed that `if` code that I created a [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UBMqAllAA4CuMABKgKR1kBmAFAISs4CGA5gEpgdRnjoATMgGdeAIxxwJDRgF8xdAPSEoqTZlx4QAGhARKMMtGnJQvAE72IAdwAKDhDZS8AbhDISJiBy9rxgANZwMADKlGEU-Mgw9tRwpgY4AOroZPDScWBw0Z65ZD65AJ7I4NI2phTScPYwrqH8WLzIrLw4jaYAVtIAHgBCoRFR0bxYcAAyFHBdPX0gg0PRCYoAitQQ8Eu9aSBx9o321RlBlPYUMJkBMOjIABwADKbXEI2ZoZTV13Azj5FqZ7HAAI7UMhg1oCDoHFaNLBkJIpI7STZwHZ7RZIbqHUwweT3CSPZAAJkJoTIOASAGEIFh4SgoNAQSBqI0ACryLz4la8aQwBFHCQQMAi0wQWg0GDkkWqVRAA) for.

I know that you don't support .ejs at the moment, but you did not change the ejs code either, but now it seems like I cannot code .ejs with prettier at all.

**Comment by ikatyang** [comment]
Weird. We didn't treat `.ejs` as HTML file so it should not be touched. @MohGanji How did you run Prettier? via CLI or editor integration?

**Comment by MohGanji** [comment]
@ikatyang I use VSCode, so editor integration

**Comment by ikatyang** [comment]
I think this is probably an VSCode issue since it's not reproducible via CLI. Can you open an issue in [`prettier-vscode`](https://github.com/prettier/prettier-vscode)?
