### ISSUE TITLE
Nested ternary indentation changes

### ISSUE THREAD

**Issue by vincentwoo** [prettier/prettier#5476]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucALAhlA5nAdDCXAGwEso4ACAHgoAcIBnYsuAHSgooH47HcxU7TkgoDMOfHAAeMYgiwxU1ALwUAjEIqsYPekwEUAtBQAUY7HgL8lx8xIBmAJwgBbawEoKAagoMAri4AMvKKDGYYFpIy7prCvPo2ohESVgY+ROgMMOHiltIw7nLYiiAANCAQtDAk0AzIoOiOzgDuAAqNCHUo6ABuECQAJmUgAEaO6GAA1nAwAMq0E2RYyDCOfnDlqDAuRADqqCTwDAtgcLOdhyQ9hwCeyOAMdeVkDHCOMK3jWC7oyPboRFe5QAVgwpAAhcZTGazdAuOCBFh-AFAkCgqSzJZEOAART8EHgyMBGxAC0cr0c9xG6BGNyI0GGtEcZBgu0GJSQAA4AAzlJmMOC7ca0e5MuAUnpwYaOOAARz8JBln3Q31+SH+xPKrxcJBWaxJDCxuPxhPVKJJMBpbIGHIATOVVugSKRsABhVw-e5QaBS8p+V4AFRpXQ1rwAvmGgA)
```sh
--parser babylon
```

**Input:**
```jsx
change.to.line < pos.line
  ? pos.ch
  : change.text.length <= 1
    ? pos.ch - (change.to.ch - change.from.ch) + sumLengths(change.text)
    : pos.ch - change.to.ch + last(change.text).length
```

**Output:**
```jsx
change.to.line < pos.line
  ? pos.ch
  : change.text.length <= 1
  ? pos.ch - (change.to.ch - change.from.ch) + sumLengths(change.text)
  : pos.ch - change.to.ch + last(change.text).length;

```

**Expected behavior:**
Hi, I'm not sure when this prettier change was made, but it used to be the case that such ternary expressions were indented like the input text. Recently it seems that we get the shown output instead. I think the former is certainly superior for communicating intent. Was this an intended indentation (hah) change?

**Comment by lydell** [comment]
Hi! Thanks for the well written issue.

Yes, it was an intentional change:

- https://prettier.io/blog/2018/11/07/1.15.0.html#flatten-else-branch-for-nested-ternaries-5039-by-suchipi-5272-by-duailibe-5333-by-ikatyang
- #5039
- #737

I think you’re one of the first to express that they preferred the old way.

**Comment by j-f1** [comment]
For posterity, two GitHub Desktop team members also expressed reservations (https://github.com/desktop/desktop/pull/6092#discussion_r231509335):

> @shiftkey:
> I think this is the only real formatting change that bothers me, and maybe this is a chance to avoid the crutch of nested ternary statements.
> @say25:
> I think its also easier to read with nesting. Maybe we can turn that off/back?

**Comment by jeffmath** [comment]
In my opinion, this change makes nested ternaries more difficult to read and understand.
