### ISSUE TITLE
[Angular] Respect --no-bracket-spacing for interpolations

### ISSUE THREAD

**Issue by nunocastromartins** [prettier/prettier#5478]
Some might disagree that this should be added, but (possibly unfortunately) the option `--no-bracket-spacing` already exists. Respecting it would, in my opinion, make a code base more consistent.

JSX also seems to ignore this option, although in its case no spaces are added (an issue was opened and closed regarding this: #1097). Why no spaces for JSX but spaces in Angular? I suppose that people don't really use Angular together with JSX so there shouldn't be any inconsistency there, but still, why the inconsistency in terms of decisions (space vs. no space)?

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4AEww+JAHvgNT4BMAvrSfqgPRZ4gA0IEADjJtADOyUAEMATuIgB3AAoSEwlKOwRM6TiABG40WADWcGAGUeezFADmyAGaiANoLhcAFjAC29gOovM8QWZgcMaKfjh+AJ7I4ILCXBZO4jCyupbuorYOTlwAVoKkAEK6BkbGou5wADIWcJmOziB5pMYWlvZwAIoArhDwddkgZuKJ0aJWXfYSmjziFjBe6jAuyAAcAAxcMxBOXro80TNwidi1XOJwAI5dmOcpomkZSHb1XE7umMgw4l0Ngq3t3V6tSeWQaMFEWgW6CWyGoXC+okw9laAGEIO50tEoNBTiAuk4ACoQpTPJz0IA)
```sh
--parser angular
--no-bracket-spacing
```

**Input:**
```html
<div> {{   x + 2}}   </div>
```

**Output:**
```html
<div>{{ x + 2 }}</div>
```

**Expected behavior:**
```html
<div>{{x + 2}}</div>
```

**Comment by ikatyang** [comment]
There was no whitespace in the initial implementation, but people complained that it didn't follow the [Angular](http://codelyzer.com/rules/angular-whitespace/)/[Vue](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/mustache-interpolation-spacing.md) style guide and `{{input}}` is indeed more verbose than `{input}`, so it's changed to print whitespaces there.

Discussions happened in #5259.

**Comment by lydell** [comment]
Same request but for JSX: #2651

**Comment by voithos** [comment]
This would also be useful for me, as we have lots of Angular templates already using the other style - but not a deal breaker.

**Comment by maartentibau** [comment]
Any news on this? 

Would be nice if an extra option could be provided to actually allow/disallow the spacing for interpolation brackets

**Comment by lydell** [comment]
Yes, there are some news: This issue has been open for over a year and has (at the time of writing this comment) 0 :+1:s.

**Comment by lydell** [comment]
It’s been 2 years with just 1 :+1:. Time to close.
