### ISSUE TITLE
[Markdown] Space removed before dollar sign

### ISSUE THREAD

**Issue by BPScott** [prettier/prettier#5483]
In markdown a dollar sign seems to swallow all spaces before it when there is another one on the same line.

I think this is related to mathjax stuff and I *think* the solution is I need to escape all dollar signs but I wonder if there is some way that prettier can be smarter about how it treats these dollar signs pairings

//cc @ikatyang 

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAjABgAQFpuoBMmAOlBpgHSY4CGUAJgQCxU0gA0IEADjAJbQAzslC0ATuIgB3AAoSEIlLQBuEfg04gARuNpgA1nBgBlHvv5QA5shjiArnC4ALGAFsANgHVn-eEPMwOBNFP34VPwBPZHAhES5LIThxGFk9KzdaZAAzWg8krgArIQAPACE9Q2MTWjc4ABlLOBy8gpBikpNLKw84AEV7CHgW-KcQc3Ek8RjM8QMGGSgtHnFLGC8NGGdkAA5MLhWIJK89HhiVuCmVZq5xOABHe347tNoMrKRc0a4kt35bBxjITdXoDIbNT6tMYwWjaDYMLbIQhcOy0fgeboAYQgbkyMSg0BuIHsSQAKrClF8kgBfalAA)

**Input:**
```md
$10 - $20
$10.00 and $40.00
```

**Output:**

```md
$10 -$20
$10.00 and$40.00

```

**Expected behavior:**

As input

OR 

```md
\$10 - \$20
\$10.00 and \$40.00

```

**Comment by alexandernanberg** [comment]
Is Prettier meant to escape all `$` from now on or just the ones in "math-syntax"?

For an example

**Input**
```markdown
$5/month
```

**Output**
```markdown
\$5/month
```

This still occurs on the preview of the  #5485 PR

**Comment by ikatyang** [comment]
The math syntax is quite easy to be triggered, for example:

```md
<!-- input -->
hello world $something __hi__ foo bar $baz
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is parsed as math, which means
                                        its content will be preserved.
                                        `__hi__` is not considered a strong here.

<!-- output -->
hello world $something __hi__ foo bar $baz
```

So we escape all non-math dollar signs to reduce false positives (this rule is also applied to `*` and `_`):

```md
<!-- input -->
hello world \$something __hi__ foo bar $baz
                        ^^^^^^ this is be parsed as strong

<!-- output -->
hello world \$something **hi** foo bar \$baz
```

If you saw a dollar sign that is not escaped, it's probably recognized as math syntax.

**Comment by alexandernanberg** [comment]
Ah I get it, thanks!
