### ISSUE TITLE
Setup dependency dashboard

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#5486]
I just tried the master issue from renovate in tslint-plugin-prettier yesterday, and it looks good to me. What do you think about adding it to this repo? (only enable the dashboard to browse dependency updates.)

(prettier/tslint-plugin-prettier#282)

![image](https://user-images.githubusercontent.com/8341033/48528587-9e334c80-e8ca-11e8-8e93-9741dcd39260.png)

The title can be customized via configs so we could get something like:

- Parser: update dependency XXX to vXXX
- Dependency: update dependency XXX to vXXX
- Build: update dependency XXX to vXXX
- Linter: update dependency XXX to vXXX

**Comment by fisker** [comment]
Tht dependabot already taking care dependencies.
