### ISSUE TITLE
Trimming semicolon when defining TypeScript type on single line.

### ISSUE THREAD

**Issue by zelein** [prettier/prettier#5488]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPAWQE8BJYsy64AHSjz1IIBs4GcjAAWSPAGcY2IgHMA3J24EJAUTTTyAfnEAjCBAHkoiqAF8leTuiy48MOhmr0AKo7gATJvBZU8AXjwOLh5+QWExSWk5U2U1DWxtPQMjE04LEO5rTBx8BydaOgAhbAgAawQ3Jy9mCj9A4FCBIVFxKRkoBUJ4zR08fUM4Y3k8MxAAGhAIDBgCaAlkUHJsUoB3AAVlhAWUcgA3CAIPCZBdRLAKmABlITA5ZGkAVzhJkRgAWz4AdRECeAlbnArts-gQ9n86MhwBIFpMiBISDB1olZO9yMgKHwEZMAFYSNAlSiXK7kd5wAAyRDgGPIWJeIDxaCucgEAEVHhB4DS6ZMhNgEdgofk4BIwDIZicMB0YF8jqJkAAWAAMSt5pQRX0SGChUpFJD21Mm2DgAEdHgRjcjyKj0UhMdiQAj3gQHthnpMJCy4OzOdS7bSHTByLpZR55UgFZNNPw5ABhCDvNFQqDQQ0gR4IlzBnb2uBmMxAA)
```sh
--parser typescript
--print-width 400
--tab-width 4
```

**Input:**
```ts
export interface MyInterface {
  filepath: string;
  isExtra?: boolean;
}
  
export type MyTypedInterface = {
  filepath: string;
  isExtra?: boolean;
}
    
export type MyBrokenTypedInterface = { filepath: string; isExtra?: boolean; }
```

**Output:**
```ts
export interface MyInterface {
    filepath: string;
    isExtra?: boolean;
}

export type MyTypedInterface = {
    filepath: string;
    isExtra?: boolean;
};

export type MyBrokenTypedInterface = { filepath: string; isExtra?: boolean };

```

**Expected behavior:**
```ts
export type MyBrokenTypedInterface = { filepath: string; isExtra?: boolean; }
```
The semicolon after the `isExtra?: boolean;` should not be trimmed off. It only seems to do so when defined on a single line.

**Comment by j-f1** [comment]
This is intentional behavior. We only add a trailing punctuation character when the expression is on multiple lines, since that’s the only case where the trailing comma/semicolon is useful for diffability.

**Comment by zelein** [comment]
Thanks for the explanation. TSLint also does not complain, so I don't really have anything further to argue.
I typically don't run into this situation anyways. I just happen to see it because I was inlining an interface and picking from another.

`type Foo = { foo1: string} & Pick<AnotherInterface, "foo2">;`
