### ISSUE TITLE
Eclipse support

### ISSUE THREAD

**Issue by AIMMOTH** [prettier/prettier#5496]
Add support for Eclipse IDE.

**Comment by kachkaev** [comment]
Hi @AIMMOTH! This repo is only for Prettier core (a command-line tool). If you want to integrate Prettier to Eclipse, it might be worth speaking to someone in their community. Or you can also implement the plugin yourself 😉

I can suggest looking at [`prettier-atom`](https://github.com/prettier/prettier-atom) for reference as its design supports external Prettier plugins, which are not yet available in all editor integrations.

**Comment by j-f1** [comment]
We typically don’t add support for editors directly; however, feel free to create a plugin for Eclipse yourself and we’ll be happy to list it on the website!
