### ISSUE TITLE
[JS/HTML] Each save indents the code further.

### ISSUE THREAD

**Issue by 8483** [prettier/prettier#5499]
The following code:  
```javascript
function foo() {
    return `
        <div>
            <p>Text</p>
        </div>
    `;
}
```

When I save, becomes this...
```javascript
function foo() {
    return `
            <div>
                <p>Text</p>
            </div>
        `;
}
```
Saving again does this...
```javascript
function foo() {
    return `
                <div>
                    <p>Text</p>
                </div>
            `;
}
```
Why is this happening? It wasn't an issue a day ago.

**Comment by j-f1** [comment]
I can’t reproduce this in the online playground. Can you make a playground example that demonstrates the issue please?

**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U+d+ATnDOg7QAY33f4A8AJjgBuAPi48JvAA4iAKnAAeMXgHoZ4ySsGiN+dgG4aAXxAAaEBCm5oAZ2SgAhgwYQA7gAUnCOygdCIOPxmIABGDA5gANbMAMpSEThQAObIMAzocOYAFjAAtgA2AOpZOPA28WBwMd6lwqUAnsjgNnbmiTZwDDDu4Um5DsioDvkd5gBWNgoAQuFRsQ65cAAyiXCDw6MgEwoxiUn5cACK6BDw6yOZIPEMHQxNIQ4h9fnQwVIMiTCFgTBZyAAcAAZzO8IB1CuEpE13nBbkI1uYmABHdA4Jg9Bx9AZIIYXcwdXI4VLpS42PYHY6nNY4jaXGCPb78X7IABM5jSDhw+T2AGEILl+k0oNAESB0B1ZI8fLiOkYjEA)
```sh
--parser babylon
```

**Input:**
```jsx
function foo() {
    return `
        <div>
            <p>Text</p>
        </div>
    `;
}
```

**Output:**
```jsx
function foo() {
  return `
        <div>
            <p>Text</p>
        </div>
    `;
}

```

**Comment by 8483** [comment]
I did some testing and it doesn't seem like a JS problem, but rather an HTML one.  

If the code is in a **bug.js** file, it doesn't happen.

```javascript
function foo() {
  return `
        <div>
            <p>Text</p>
        </div>
    `;
}
```

However, this bug happens when the code is inside a `<script></script>` tag in a **bug.html** file.

```html
<!DOCTYPE html>
<html lang="en">
    <head>
    </head>
    <body>
        <script>
            function foo() {
                return `
                    <div>
                        <p>Text</p>
                    </div>
                `;
            }
        </script>
    </body>
</html>
```
Saving this file does this...

```html
<!DOCTYPE html>
<html lang="en">
    <head>
    </head>
    <body>
        <script>
            function foo() {
                return `
                                <div>
                                    <p>Text</p>
                                </div>
                            `;
            }
        </script>
    </body>
</html>
```

**Comment by j-f1** [comment]
I can repro now:

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAiHMo5CeTZwuAEzGSpAekoz5LRagBGEWQE8FiyagDOYAE4BLAA4xDRowDMArlDAxL0co4gQAFACU5MAaDmES5nAwzubiAAah4UlSspYAbvbJWajWDPhwAB4wqEq5iVkOJakZ5RVxANy1YQC+TRIlZla2mSU6+mIl7IwgADQgELaeUCbIoFzm5hAA7sTzCDMoXGkQlrKjIFrmXGAA1lEAytbHlnzIMObOcGNDAOqUlvAmV2Bw5+sf6Q+emQ4BMMzGNxMcHMMGIR14NC4yEcXDoULGACsTAUAEJHU4XLg0OAAGRucGRqPRICxBXON14dDgAEVnBB4JS0U8QFdzFDzCChvtrFZYC9djBKMgABwABjGIogUJeR2sIJFcH5aQpY0iAEdnJZInCuAikUgUVyxlCaJY7g9uSYGUzWeyKRaqdyYFwtOLZJLkAAmMb3LiWOgM3AQGiIkFQaA6kDOKH4H0bS1Q5rNIA)
```sh
--parser html
```

**Input:**
```html
<!DOCTYPE html>
<html lang="en">
    <head>
    </head>
    <body>
        <script>
            function foo() {
                return `
                    <div>
                        <p>Text</p>
                    </div>
                `;
            }
        </script>
    </body>
</html>
```

**Output:**
```html
<!DOCTYPE html>
<html lang="en">
  <head> </head>
  <body>
    <script>
      function foo() {
        return `
                          <div>
                              <p>Text</p>
                          </div>
                      `;
      }
    </script>
  </body>
</html>

```

**Second Output:**
```html
<!DOCTYPE html>
<html lang="en">
  <head> </head>
  <body>
    <script>
      function foo() {
        return `
                                <div>
                                    <p>Text</p>
                                </div>
                            `;
      }
    </script>
  </body>
</html>

```
