### ISSUE TITLE
Is there a way to specify different printWidth for .html file type ?

### ISSUE THREAD

**Issue by isotope3** [prettier/prettier#5503]
In .prettierrc we can specify printWidth as 
```
{
"printWidth":80
}
```

This applies to all file types eg. .js, .ts, .html etc. 

Is there a way to specify a different printWidth for each file type? 
More specifically,  I want .html files to have printWidth: 120 and leave it to 80 for other file types.

**Comment by kachkaev** [comment]
According to the [docs](https://prettier.io/docs/en/configuration.html#configuration-overrides):
```
{
  "printWidth": 80,
  "overrides": [
    {
      "files": "*.html",
      "options": {
        "printWidth": 120
      }
    }
  ]
}
```

**Comment by isotope3** [comment]
Perfect. That is exactly what I was looking for. Thanks
