### ISSUE TITLE
loose jsx format

### ISSUE THREAD

**Issue by acrazing** [prettier/prettier#5504]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAggA7EA2OYAhrtABQCU+wAOlPvgE5wzqft02HDgB4AJjgBuAPiHCOrdvOHFOEYgGcAdOg1xO2gLZVidOrv1MAvNPyCly4eKmyHjpxuJUo04Bc5aOGIAviIA9J7eru7KIpE+fnoBUFSGcKERXj5yMeESMjnKDAyFHMGFeS5yJVDBIAA0IOq0UBrIoFScagDuAAqdCG0oVJIQQQ0gAEacVGAA1jwAyl5gOFAA5sgwnOhwjQAWMIZkAOr7OPCRYHCLgxdSFwCeyOAabY1rSTC9M+vGyKgqGQ9I0AFYaAAeACEZvMlqk4AAZNZwAFAkEgcEQxZrdZkOAARXQEHgaOBexAXgM+hekyok0eZGgE1UaxgJyCMH2yAAHAAGRqqCB6E4zYgvVRwJKSVGNbgAR3QOG4PyofyoZIxekMOC2OwpGlx+KJJNRSEB5MaMHpHLEXOQACYrTMcBQNgBhCCGf4oKDQWUgCwAFXpQwtemCwSAA)

**Input:**
```jsx
// code snippet
function Application() {
  return (
    <div>
      {
        props.users.map((user) => (
          <div>
            <span>{user.id}</span>
            <span>{user.name}</span>
          </div>
        ))
      }
    </div>
  )
}
```

**Output:**
```jsx
// code snippet
function Application() {
  return (
    <div>
      {props.users.map(user => (
        <div>
          <span>{user.id}</span>
          <span>{user.name}</span>
        </div>
      ))}
    </div>
  );
}

```

**Expected behavior:**

Output original code rather than put `props.users.map...` and `{` to same line.

**Comment by kachkaev** [comment]
Why do you find the original code better? The output looks prettier to me as it uses fewer lines and results into smaller indents. Hence, more characters will fit without added line breaks.

**Comment by acrazing** [comment]
It is better to read.
