### ISSUE TITLE
Support AsciiDoc files

### ISSUE THREAD

**Issue by samerbuna** [prettier/prettier#5506]
It would be great if prettier could format AsciiDoc (.adoc) files. 

_I am a big fan of Markdown but AsciiDoc is the choice of some book publishers as it seems to have a lot more features than Markdown._

**Comment by kachkaev** [comment]
@samerbuna AsciiDoc does not look like a commonly used language in web projects these days. However, feel free to create a [third-party Prettier plugin](https://prettier.io/docs/en/plugins.html) for it if you wish 😉 This might be a great opportunity to start a new open-source project!

**Comment by ptandler** [comment]
I also would vote for AsciiDoc. I agree that MarkDown is more commonly used, However, IMO AsciiDoc has a clearer syntax.

**Comment by evilebottnawi** [comment]
Yes, better implement own plugin for this, it is not commonly used language in web projects, anyway thanks for issue, maybe we will reconsider this in the future
