### ISSUE TITLE
Configuration via pragma

### ISSUE THREAD

**Issue by taylorgoolsby** [prettier/prettier#5507]
This is a request for a feature.
It would be nice to be able to define prettier configuration per file via a comment at the top of the file.
This is similar to how you can override global `.eslintrc` settings using a comment at the top of the file.

I see that prettier already has a pragma feature to only allow running prettier on files with the pragma.
Can we also put prettier settings next to the pragma?

**Comment by kachkaev** [comment]
Hi @taylorgoolsby! What problem can this feature solve?

**Comment by taylorgoolsby** [comment]
Hi, @kachkaev, most files in my project enjoy the 80 width rule. However, there is one file that has abnormally long lines, and for this file I would like it to have a different width rule because formatting actually looks better that way.

For now I've just disabled prettier on that file using `.prettierignore`, but this feature request was the solution I was hoping for.

**Comment by lydell** [comment]
@taylorgoolsby Can you use [configuration overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides)?

**Comment by taylorgoolsby** [comment]
@lydell Oh yes! that will be just fine! I didn't realize that was a feature, thank you!
