### ISSUE TITLE
Long strings exceed maximum line length

### ISSUE THREAD

**Issue by hollandThomas** [prettier/prettier#551]
The output of [this file](https://github.com/graphql/swapi-graphql/blob/master/src/schema/connections.js) contains lines that are longer than the maximum line length of 80.  In the output file, the lines in question are 40 and 48.

As a sidenote: The way these particular long strings are displayed in said file seems more pleasing to my eye than letting them start right after _description:_. I can see that this is a matter of taste though.

**Comment by vjeux** [comment]
Thanks for filing an issue. Here's a reduced test case so it's easier to talk about :)

```js
    ({
      totalCount: {
        type: GraphQLInt,
        resolve: conn => conn.totalCount,
        description:
`A count of the total number of objects in this connection, ignoring pagination.
This allows a client to fetch the first five objects by passing "5" as the
argument to "first", then fetch the total count so it could display "5 of 83",
for example.`
      }
    });
```

turns into

```js
({
  totalCount: {
    type: GraphQLInt,
    resolve: conn => conn.totalCount,
    description: (
      `A count of the total number of objects in this connection, ignoring pagination.
This allows a client to fetch the first five objects by passing "5" as the
argument to "first", then fetch the total count so it could display "5 of 83",
for example.`
    )
  }
});
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20(%7B%5Cn%20%20%20%20%20%20totalCount%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20GraphQLInt%2C%5Cn%20%20%20%20%20%20%20%20resolve%3A%20conn%20%3D%3E%20conn.totalCount%2C%5Cn%20%20%20%20%20%20%20%20description%3A%5Cn%60A%20count%20of%20the%20total%20number%20of%20objects%20in%20this%20connection%2C%20ignoring%20pagination.%5CnThis%20allows%20a%20client%20to%20fetch%20the%20first%20five%20objects%20by%20passing%20%5C%225%5C%22%20as%20the%5Cnargument%20to%20%5C%22first%5C%22%2C%20then%20fetch%20the%20total%20count%20so%20it%20could%20display%20%5C%225%20of%2083%5C%22%2C%5Cnfor%20example.%60%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by lydell** [comment]
What is the expected output here? :)

**Comment by vjeux** [comment]
We are unlikely going to try to try and accommodate long strings. I'm closing this issue in order to keep the issue list actionable.
