### ISSUE TITLE
[Vue] do not remove necessary semicolon in event bindings with --no-semi

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#5510]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG5kACYONYA1gLzEhUQDKEDHBgALGlADmAbh6FUAelp0SURZlwE4hEABoQELDBrQAzslB4ATlYgB3AArWE5lHjoQaVPSABGVvA4RfixAiUlkGCsAVzh9URgMHAB1cXhTULA4fhcaYzo8gE9kcFNzfQlTOCsYBwDJDDxkADM8HCr9ACtTAA8AIQCgmH48YQAZCTgWto6Qbp7+cJw4AEVoiHhp9riQUKsqqxK6WJ8sKwkYZK8xZAAOAAZ9M4gq5ICsErO4A7op-Ss4ABHaI0AF1PANJpIVrbfRVDA0LazUxLVbrTbQmY7GB4XxXKg3JAAJn0UTwNFYUgAwkJGiUoNA-iBolUACq41wwqoAX25QA)
```sh
--parser vue
--no-semi
```

**Input:**
```vue
<template>
  <div @click="doSomething;"></div>
</template>
```

**Output:**
```vue
<template>
  <div @click="doSomething"></div>
</template>

```

**Expected behavior:**
Same as input. `doSomething` and `doSomething;` behave [differently](https://template-explorer.vuejs.org/#%3Cdiv%0A%20%20%40a%3D%22doSomething%22%0A%20%20%40b%3D%22doSomething%3B%22%0A%3E%3C%2Fdiv%3E%0A).

**Comment by j-f1** [comment]
Note that this only applies to simple expressions, such as identifiers and member expressions, not call expressions, which always create the wrapper function.
