### ISSUE TITLE
Support HTMLx

### ISSUE THREAD

**Issue by Rich-Harris** [prettier/prettier#5511]
(I removed the issue boilerplate because it doesn't seem to pertain to feature requests — hope that's okay.)

@vjeux [sent me here!](https://mobile.twitter.com/Vjeux/status/1064910649229107200) On the [Svelte](https://svelte.technology) project, we're often asked if it it's possible to use Prettier to format single-file components. At present the answer is 'no, not reliably', because we typically write those components in `.html` files, and components are written in a superset of HTML called [HTMLx](https://github.com/htmlx-org/HTMLx).

Since Prettier supports Angular and Vue flavours of HTML already, I wondered what it would take to support HTMLx in addition? (We're considering adopting and promoting an `.htmlx` extension similar to `.vue`, if that's necessary.) We'd obviously be happy to do the work, I'm just raising this issue to see if a PR adding support would be likely to be accepted.

(Note that HTMLx will change slightly for Svelte 3, out soon.)

**Comment by Rich-Harris** [comment]
If you can give us a nudge in the right direction, we'd be very happy to submit a PR

**Comment by suchipi** [comment]
Assuming our HTML/Vue/Angular parser can already parse everything you need, add an entry for htmlx [here](https://github.com/prettier/prettier/blob/master/src/language-html/parser-html.js#L268) and then adjust the printing to support htmlx-specific semantics in [this file](https://github.com/prettier/prettier/blob/master/src/language-html/printer-html.js). The way the printer works is it returns an intermediate representation of the text called a "document" that is comprised of various nodes which are informally documented [here](https://github.com/prettier/prettier/blob/master/commands.md). The logic [here](https://github.com/prettier/prettier/blob/master/src/language-html/printer-html.js#L898) where we handle vue's `v-for` attribute may be a good place to start.

**Comment by Rich-Harris** [comment]
Perfect, thank you! We'll take a look at this soon

**Comment by suchipi** [comment]
If our parser can't parse what you need, you will need @ikatyang to advise, I'm not sure what to do in that situation

**Comment by ikatyang** [comment]
- We use HTML parser to parse HTML/Angular/Vue but we cannot use it to parse Svelte since there're [block expressions](https://svelte.technology/guide#if-blocks) (e.g., `{#if ...}<b>element</b>{/if}`), we need a Svelte parser and transform its AST to the format we used.
- There's no `if..elseif..else`-like element in the current implementation so we need to figure out how to print it without introducing unexpected whitespaces.

**Comment by Immortalin** [comment]
Any plans for Jinja template support?

**Comment by duailibe** [comment]
@Immortalin no plans right now

**Comment by UnwrittenFun** [comment]
I've made [prettier-plugin-svelte](https://github.com/UnwrittenFun/prettier-plugin-svelte). Is it preferred that things are built in to prettier, or provided as plugins? I don't know how hard it would be to integrate what I've done into prettier but willing to give it a go if I find some time

**Comment by azz** [comment]
Hey @UnwrittenFun, that's awesome, feel free to add it to this list: https://prettier.io/docs/en/plugins.html#community-plugins

**Comment by thorn0** [comment]
Closing this as we have the Svelte plugin now.
