### ISSUE TITLE
getFileInfo does not resolve ignores correctly when filePath is absolute

### ISSUE THREAD

**Issue by BPScott** [prettier/prettier#5513]
I received the following issue on eslint-plugin-prettier: https://github.com/prettier/eslint-plugin-prettier/issues/126

When passing an absolute path into `getFileInfo()` (or in my case `getFileInfo.sync()`) the line `src/not_pretty.js` within a `.prettierignore` is not honored. This results in a file being parsed by prettier when it should be ignored.

This seems to occur for any ignore line that contains a path instead of a single segment.

**Environments:**
- Prettier Version: 1.15.2
- Running Prettier via: vis eslint-plugin-prettier
- Runtime:Node 10
- Operating System: macOS

**Steps to reproduce:**

`git clone https://github.com/edmorley/testcase-eslint-plugin-prettier-ignore` and cd into the folder

Add the following file to the repository as `check-getfileinfo.js` and run it using `node check-getfileinfo.js`:

```js
const path = require("path");
const prettier = require("prettier");

filePath = "src/not_pretty.js";
options = { ignorePath: ".prettierignore" };

const relativeInfo = prettier.getFileInfo.sync(filePath, options);
const relativeWithDotInfo = prettier.getFileInfo.sync(`./${filePath}`, options);
const absoluteInfo = prettier.getFileInfo.sync(path.resolve(filePath), options);

console.log("relativePath is Ignored:", relativeInfo.ignored);
console.log("relativeWithDot is Ignored:", relativeWithDotInfo.ignored);
console.log("absolutePath is Ignored:", absoluteInfo.ignored);
```

**Expected behavior:**

All console logs should return true

**Actual behavior:**

- When using a relative path the ignored value is `true`
- When using a relative path with a leading . the ignored value is `false`
- When using an absolute path the ignored value is `false`

---

This behaviour does not occur when using the prettier CLI as all paths get resolved to be relative due to #2969. I think the solution is ensure the paths are relative when using getFileInfo() too.

**Comment by ikatyang** [comment]
We should `path.relative(ignorePath, filePath)` before passing into `ignorer.ignores(filePath)` if it's an absolute path.

**Comment by BPScott** [comment]
One other test case to consider: the filePath`./src/not_pretty.js` should also be ignored. I've edited my above test script to cover that.

I think if we only test for absolute paths then that case won't be covered.
