### ISSUE TITLE
TypeScript: SyntaxError: this is a reserved word (2:3)

### ISSUE THREAD

**Issue by balupton** [prettier/prettier#5514]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgEl5NcYJMBhXAGzoCN8BrAHgGUBXRgKzjAwANIQDScAJ4iAavS5wAfIWAAdKCpgAKGAAtUAZySFufAcMIA3OXCOy68kS0lHxUwvp79BRk15gBKIwsIVAATQgAfQjw6fTg1AF81ECEQCAAHGFRofWRQXExMCAB3AAUChFyUXGCwlJBGcjAnGA50-HQAc2QYTAcQHRgAWzoAdT14fXaCDkrULIt5iWRwfVzU9DjMGFLyTqHcZBi41N59AA8AISaWjlwhuAAZdDgj+hOQM-OOLro4AEUuBB4G9YnBUu1MFsVsxGBI6NB6ulMOgYKMwrpkAAOAAMEKKcVG5HSK2RcC2FleqUwcAAjlxUDTdrh9ockMdwSA4kNUD0+pz9L8AUCQez3pyYLhGOjQpikAAmVK9XCoOhdagQIYHFZQaBUkBcOIAFSlVQ5CQSQA)
```sh
--parser babylon
```

**Input:**
```jsx
interface IteratorCallback<Subject, Key, Value> {
	(this: Subject, value: Value, key: Key, subject: Subject): void | false
}

```

**Output:**
```jsx
SyntaxError: this is a reserved word (2:3)
  1 | interface IteratorCallback<Subject, Key, Value> {
> 2 | 	(this: Subject, value: Value, key: Key, subject: Subject): void | false
    | 	 ^
  3 | }
  4 | 
```

**Expected behavior:**

No error, as it is valid typescript syntax:
https://www.typescriptlang.org/docs/handbook/functions.html

**Comment by ikatyang** [comment]
You need to specify `--parser typescript` on the playground. (Click <kbd>Show options</kbd> on the left bottom.)

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgEl5NcYJMBhXAGzoCN8BrAHgGUBXRgKzjAwANIQDScAJ4iAavS5wAfIWAAdKCpgAKGAAtUAZySFufAcMIA3OXCOy68kS0lHxUwvp79BRk15gBKIwsIVAATQgAfQjw6fTg1AF81ECEQCAAHGFRofWRQXExMCAB3AAUChFyUXGCwlJBGcjAnGA50-HQAc2QYTAcQHRgAWzoAdT14fXaCDkrULIt5iWRwfVzU9DjMGFLyTqHcZBi41N59AA8AISaWjlwhuAAZdDgj+hOQM-OOLro4AEUuBB4G9YnBUu1MFsVjAJOk4PowJhUJl6ulkbBRmFdMgABwABghRTio3I6RW6IRWAsr1SmDgAEcuKh6btcPtDkhjuCQHEhqgen0efpfgCgSCue8eTBcIwsaEcUgAEypXq4VB0LrUCBDA4rKDQWkgLhxAAqsqq3ISCSAA)
```sh
--parser typescript
```

**Input:**
```tsx
interface IteratorCallback<Subject, Key, Value> {
	(this: Subject, value: Value, key: Key, subject: Subject): void | false
}

```

**Output:**
```tsx
interface IteratorCallback<Subject, Key, Value> {
  (this: Subject, value: Value, key: Key, subject: Subject): void | false;
}

```
