### ISSUE TITLE
SCSS map formatting incorrectly

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#5516]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgQwA5IAQAUAOlHngPTl6TroIwA0JZmTURMARt2x2WQEchbMpWoRa9NmBlg2AEwZwGAMzUqSASgDcIBiAjYYAS2gBnZKEwAnaxADuABRsILKTADcIx+XpCdrTDAAazgYAGVsIOMoAHNkGGsAV2UQAAsYdAAbAHU043gzKLA4cNcC4w8CgE9kcDMLfRizOGsYR0DYrGQVTCyW-QArMwAPACFAkLDwzDoAGRi4Hr6BkGGR8JjYrLgARSSIeGX+1KjrFus6szAGv2xrGJgcnxg05AAOAAZ9e4gWnMC2Dq9zgFw8S301jgAiSxihHUwXUwx1WLXQxgSyVSZi2O32hyWSF6J30MEwnGe8leyAATKTAsYslsAMISbooKDQCEgJItAAq5LcxJaAF8RUA.)

**Input:**
```scss
$map: (
  // comment,
  a,
	bbb,
	    qqq,
  // comment,
cccc,
d,e,ffff
);
```

**Output:**
```scss
$map: (
  // comment,
    a,
  bbb,
  qqq,
  // comment,
    cccc,
  d,
  e,
  ffff
);
```

**Expected behavior:**
```
$map: (
  // comment,
  a,
  bbb,
  qqq,
  // comment,
  cccc,
  d,
  e,
  ffff
);
```

it seems the map item after comment indentation level is a little high

**Comment by lydell** [comment]
Duplicate of #4878
