### ISSUE TITLE
Update next and beta tags on NPM

### ISSUE THREAD

**Issue by zeorin** [prettier/prettier#5518]
![2018-11-21-172856_3840x2106_scrot](https://user-images.githubusercontent.com/1187078/48851203-232ed200-edb3-11e8-9fdc-963aca275286.png)

The `next` and `beta` tags are very out-of-date. Perhaps update or remove them.

**Comment by j-f1** [comment]
Should we deprecate those specific versions and use the deprecation message to tell users to install `prettier/prettier` instead?

**Comment by ikatyang** [comment]
Removing them should be fine I think, since tags are meant that their target may be changed and we did not document it anywhere.

@prettier/core what do you think?

**Comment by lipis** [comment]
Burn them with fire!

**Comment by ikatyang** [comment]
Removed.
