### ISSUE TITLE
[HTML] Support SSI (Server Side Includes)

### ISSUE THREAD

**Issue by yuma84** [prettier/prettier#5522]
(example by using `#include` command)

### Input:

```
<!--#INCLUDE VIRTUAL="common/header.html" -->
<!--#include virtual="common/footer.html" -->
```

### Output:

```
<!-- #INCLUDE VIRTUAL="common/header.html" -->
<!-- #include virtual="common/footer.html" -->
```

### Expected behavior:

```
<!--#INCLUDE VIRTUAL="common/header.html" -->
<!--#include virtual="common/footer.html" -->
```

There is *no space* until after the command

**Comment by lydell** [comment]
I guess we shouldn't touch the contents of comments at all?

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwYgJIByAwgDICqAIgKIAEAangEoAqZAgiQLwA64EAtv2gB6ABZwAhgBM4AJwB0omPwA2vGtgB83KBmw4AllDAqArjJoA3A7JimJKnn0EiAZhAjwFS1eq069bExtXSxMCX9Q7BoYmglYmgAjBK0QABoQCAAHGANoAGdkUAlZWQgAdwAFEoRClAlLCAMpdJBE2QkwAGs4GABlLM6jAHNkGFlTOAyfFQB1UQN4fMGwOD7axYNrGABPZHB8woyjfLkYSo7h-glkVwdTjIArfIAPACEO7t6+iX44EiMcFu9ymIGeLz6IxUcAAiqZPECkHcVA8QINZKdZPsZq0srIjDBZs0YKJkAAOAAMGTxEFOsw6WX2eLgmMsQIysjgAEdTDY4BcJFcbkiQRlTvwDGMJqD8lDYfD4MCUaCYBJEkSpCTkAAmDLjCQGFQjIgCa77KDQdkgUynZhqurI04AXydQA)
```sh
--parser html
```

**Input:**
```html
<!--#INCLUDE VIRTUAL="common/header.html" -->
<!--#include virtual="common/footer.html" -->
<!---->
<!--a-->
<!--    a    b    -->
```

**Output:**
```html
<!-- #INCLUDE VIRTUAL="common/header.html" -->
<!-- #include virtual="common/footer.html" -->
<!---->
<!-- a -->
<!-- a    b -->

```

**Comment by ikatyang** [comment]
It looks like @yuma84 was asking for SSI formatting so I'm going to move the _do not touch comments_ part to #5523 and track the SSI formatting here.

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/5525
