### ISSUE TITLE
Feature request: operating system specific line endings

### ISSUE THREAD

**Issue by mhinterreither** [prettier/prettier#5528]
Hi,

In the current version of prettier there is an option to force line endings to "crlf" or "lf" (default is "auto" which means to detect the type of the first line ending):

`endOfLine: "<auto|lf|crlf|cr>"`

I think it would be a good idea to add a new setting for this option, which works like "crlf" on windows and like "lf" on linux so that line endings are changed to what is usual for the os used (similar to git, which uses "lf" on linux when checking out and "crlf" on windows per default).

What do you think about this feature request?

**Comment by lydell** [comment]
What's your use case?

**Comment by mhinterreither** [comment]
We use a git repository where developers can work unter linux using "lf" line endings or under windows using "crlf" line endings (git setting core.autocrlf=true).

A lot of source files are generated with angular command "ng generate" and angular always emits files with line endings "lf" (like many other code generators do). We run prettier on this files to format them according to our code style standards (currently with setting endOfLine=auto, which leaves the "lf" line endings on all operating systems).

When we add those files to the git repository, windows developers now get a warning because of "lf" line endings. We could set up prettier to always change line endings to "crlf" to get rid of this warning but this setting would lead to a similar warning for linux developers when adding the prettified files to git repository with the non-linux line endings "crlf" (leading to "crlf" line endings in the repository, what we don't want).

This new setting would allow windows developers and linux developers to use their native line endings immediately after generating and prettifying without warnings during check in of new files into git repository (like they are used to for files which are checked out of git).

We wouldn't have to care about what line endings a code generator uses and developers don't get warnings during check in anymore.

**Comment by lydell** [comment]
@kachkaev What do you think?

**Comment by kachkaev** [comment]
Looks like technically it's quite easy to extend `endOfLine` values to  `<auto|lf|crlf|cr|os>`. However, I'm not sure that using `os` in practice is better than having `lf` with `* text=auto eol=lf` in `.gitattributes`.

My experience with git's `core.autocrlf=true` on Windows machines has been pretty poor and this is the reason why I [proposed `endOfLine` option](https://github.com/prettier/prettier/issues/5320) in the first place. For some reasons I don't fully understand, CRLF line endings still occasionally get into the central repo despite that git is supposed to convert all cases of CRLF to LF during the commits. One possible source of this unwanted outcome can be the Windows Ubuntu Bash terminal, which some folks mix up with `cmd.exe` / `PowerShell` or Git Bash. E.g. someone checks out things via `cmd.exe` with CRLF and then commits from Ubuntu bash with no CRLF→LF transformation (that's a totally different copy of git if I understand correctly).

My intuition suggests that not adding `os` value to the `endOfLine` option is a better way to go as it helps avoid the 'magic' scenario lots of people will struggle in. Adding `* text=auto eol=lf` to the repo's `.gitignore` and configuring Prettier with `endOfLine: lf` seems like a way more robust thing than relying on a global git config a contributor may or may not have.

What if someone sets `core.autocrlf=false`, check outs the repo, runs Prettier with `endOfLine: os` and commits? That gives us CRLF 100%. 🤔

@mhinterreither see the [docs for the `endOfLine` option] and let us know if there are factors I miss.

**Comment by mhinterreither** [comment]
Thanks for your feedback. I'll try your suggested setup. To be able to share repository folders between different operating systems without caring about lf/crlf is a good argument against using crlf under windows.

**Comment by kachkaev** [comment]
@mhinterreither Windows folks who switch from CRLF to LF might need to re-check out all files after you’ve set `* text=auto eol=lf`. This is to ensure that there are no CRLF files in the working directory.

You may also want to search for `\r` in the repo a few times during the transition period to ensure that no CRLFs slip through. As an extra precaution, feel free to create `.editorconfig` file and `.vscode/settings.json` to help editors pick LF when creating new files.
