### ISSUE TITLE
Babylon and typescript parser inconsistency

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#5532]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAFArgJwAcI04BlQuMASwDMBPASQBtncN8BDGa6JTAEpxOYGADoAYriijeUAMIQAtsSgIYAHhZsO3OdnwRCaAHyYAvJkKHjFs8AC+AHSggANCCM90yUJ3yGAO7Y-ghoyCCcAG4Q1AAm7iAARlxgANZwMBQi1FAA5sgw+LhwHgAWMErMAOpl1PBohCLkYfXUUfX0EWBo4R65pPgwBpx5SpzItJzMpB4AVmgAHgBCqRlZnEpwADK5cJPTsyALi2S5ecxwAIq4EPAHM6UgTfiDEUmcSfTM0InWuTBqvEYGVkAAOAAMHmsJDg1S4hAi1jggyi+w8+DgAEdcNRMSMxhMkFNHh5SEpqIVik80OdLjc7vtiYcnjBPkC4iDkAAmDxFTjUZjnRRKcYRKDQdEgdhwAAqn3CzMeDgcQA)
```sh
--parser babylon
```

**Input:**
```jsx
const PurposeSpecifyIllustration: React.FunctionComponent<IllustrationProps> = props => {}

```

**Output:**
```jsx
const PurposeSpecifyIllustration: React.FunctionComponent<IllustrationProps> = props => {};

```

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAFArgJwAcI04BlQuMASwDMBPASQBtncN8BDGa6JTAEpxOYGADoAYriijeUAMIQAtsSgIYAHhZsO3OdnwRCaAHyYAvJkKHjFs8AC+AHSggANCCM90yUJ3yGAO7Y-ghoyCCcAG4Q1AAm7iAARlxgANZwMBQi1FAA5sgw+LhwHgAWMErMAOpl1PBohCLkYfXUUfX0EWBo4R65pPgwBpx5SpzItJzMpB4AVmgAHgBCqRlZnEpwADK5cJPTsyALi2S5ecxwAIq4EPAHM6UgTfiDETD0lGhg+NSEMIlrLkYNV4jAysgABwABg81hIcGqXEIEWscEGUX2HnwcAAjrhqDiRmMJkgpo8PKQlNRCsUnmhzpcbnd9mTDk8YJwkqC4uDkAAmDxFTjUZjnRRKcYRKDQLEgdhwAAqXPCbMeDgcQA)
```sh
--parser typescript
```

**Input:**
```tsx
const PurposeSpecifyIllustration: React.FunctionComponent<IllustrationProps> = props => {}

```

**Output:**
```tsx
const PurposeSpecifyIllustration: React.FunctionComponent<
  IllustrationProps
> = props => {};

```

**Expected behavior:**
For both parsers to agree on the output.

**Comment by thorn0** [comment]
Fixed in version 1.19.1.
