### ISSUE TITLE
[TS] do not change `module` into `namespace` and break/hug them correctly

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#5533]
_Originally reported by @xcatliu in prettier/tslint-config-prettier#234_

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgAgA19gBfAHSkvWzyJMv30igGcZ8APfAXnwEYA3JQpUoNXAWLBG+CXWmjR1TJPoyoTeVIaamzaOy68BwvUsqUoAQ1RxWAB2tgdZS1Bt3Hz17JZHuPiERd097Jxd1WTDvSMUQsRiI3z0knyi9Jn8OQNNZCygQABoQCAcYAEtDZFBrACc6iAB3AAV6hFZkEGsANwgKjGKQACM65wBrOBgAZQiKqABzZBg6rDgSgAsYVBwAdQ2K+Fi4aY7Dip7DgE8usFZOkvnWODqYFrGF1GtkADNrHGeJQAVqxOAAhMZgSYzWxwAAy8zgv3+gJAIM403mCzwAEUsBB4MiAesQE46s86l0YFcHPYwHUKuUhg4GbBdgMYBtkAAOAAMJRZEGeuzGDi6LPsLx6SJKdTgAEcsBU5e9rJ9vkg-sSSs9UBVlqsSawsbj8YTNSiSTBrMN2RhOcgAEwlFbWCo4LEAYQgqC+XSg0BlICwzwAKjbOhbiaRSEA)
```sh
--parser typescript
```

**Input:**
```tsx
module X {}

module X {
  const x = 1;
}

module X {
  module X {}
}

module X {
  module X {
    const x = 1;
  }
}

namespace X {}

namespace X {
  const x = 1;
}

namespace X {
  namespace X {}
}

namespace X {
  namespace X {
    const x = 1;
  }
}

```

**Output:**
```tsx
namespace X {

}

namespace X {
  const x = 1;
}

namespace X {
  namespace X {  }
}

namespace X {
  namespace X { const x = 1; }
}

namespace X {

}

namespace X {
  const x = 1;
}

namespace X {
  namespace X {  }
}

namespace X {
  namespace X { const x = 1; }
}

```

**Expected behavior:**
Same as input.

**Comment by azz** [comment]
@ikatyang  I don't understand why this change was made. We've just upgraded prettier in a repo that heavily uses `module` -> `namespace` and this has caused countless changes.

Why was it wrong for Prettier to convert the deprecated `module` keyword to `namespace` (which has exactly the same semantics in this case)?

**Comment by ikatyang** [comment]
> We've just upgraded prettier in a repo that heavily uses `module` -> `namespace` and this has caused countless changes.

These keywords should remain the same after this PR, it must be a bug if it caused countless changes.

> Why was it wrong for Prettier to convert the deprecated module keyword to namespace (which has exactly the same semantics in this case)?

Isn't it something should be done in a linter (e.g., [`no-internal-module`](https://palantir.github.io/tslint/rules/no-internal-module/)) instead of a formatter?

**Comment by azz** [comment]
We have a code generator that pipes through prettier, so it stopped converting `module` to `namespace`. We had to fix that we the source. 

I don't see an issue with both tools supporting it. Not everyone uses tslint.
