### ISSUE TITLE
Html Angular formatting removes necessary parentheses

### ISSUE THREAD

**Issue by runeabrahams1** [prettier/prettier#5535]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVxioDongZxl1QB9UYAnAQynwBsr4kGoBzJDVADw4Ao6AloVJlBhAEwBKAPwA6OglYwAFqgC+6tdiggANCAgAHGAOj5koKhQoQA7gAUrCcyioA3CAIAmekACNqMABrOBgAZUMqMAE2ZEoAVzh9ZRgAWzoAdWUBAkiwODDnHIE3HIBPZHB8c30Y-DgKGHtqVlSqZAAzKjp6-QArfC4AIUCQ8KpUuAAZGLhO7t6QAa4wmNYFAEV4iHh5nqSQSIp6ikqaVniGU-1DChiYDO8VZAAOAAYbm3qM6kNK27gJzcc30FDgAEd4gIwc0qK12kguvt9PVUgI4hREii1pttrtEQsDpQqAJBGwAMIQVJtSpQaAgkDxeoAFSofhcSMWMDZjy8zyQ4jUaiAA)
```sh
--parser angular
```

**Input:**
```html
  {{ "test" | translate:lang: { x: (list || list2)?.length } }}

```

**Output:**
```html
{{ "test" | translate: lang:{ x: list || list2?.length } }}

```

**Expected behavior:**
Input should be equal output, but the **()** is removed around **list or list2**.

**Comment by ikatyang** [comment]
Looks like a general JS issue.

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKANgSwM4wAQA+BeWuATAJQD8AdOggOYwAWIANCBAA4ybTbJQAQwBOIiAHcACqIQCUQgG4RMAE3YgARiKFgA1nBgBlLrsxQGyGCICucDsxgBbdAHVmmeNlNg4RuZ6Yip4Ansjg2AIc5thwIjBSOgxOQsgAZkLosRwAVtgAHgBCOvqGRkJOcAAy5nDpmdkgeflG5gz0AIo2EPD1WfYgpiKxIuGaQpoh6NAaXCLmMK5qLMgAHAAMHHMQsa46XOFzcCOKdRwicACONpgXiULJqUgZ-RyxTphWtgPYbZ3dvWeDQGMAmS1UKyQZA41iEmCwFgAwhAnClwlBoGcQDZYgAVCbyF6xAC+xKAA)
```sh
--parser babylon
```

**Input:**
```jsx
(list || list2)?.length
```

**Output:**
```jsx
list || list2?.length;

```
