### ISSUE TITLE
Using prettier for .jsp files

### ISSUE THREAD

**Issue by Waltari10** [prettier/prettier#5536]
We are using .jsp files for our project. It's pretty much pure .html apart from a few occasional jsp tags. Does prettier support .jsp files or will I have to find another way to format our .jsp files?

**Comment by evilebottnawi** [comment]
@Waltari10 you need create plugin for `jsp`, prettier doesn't support `jsp` files out of box and it is not generic format for `web` projects

**Comment by Waltari10** [comment]
How does one make such plugin?

**Comment by j-f1** [comment]
https://prettier.io/docs/en/plugins.html

**Comment by Waltari10** [comment]
Any idea when the new plugins update is coming? I'm very much interested in making this plugin, but I wonder if I should wait for next version to be released.

**Comment by kachkaev** [comment]
@Waltari10 what do you mean by _plugins update_?

**Comment by evilebottnawi** [comment]
@Waltari10 plugins develop community, feel free to start develop plugin

**Comment by Waltari10** [comment]
I mean are any API changes coming? It states in the plugins doc 

> The plugin API is in a beta state as of Prettier 1.10 and the API may change in the next release!

**Comment by evilebottnawi** [comment]
@Waltari10 just notice, but no big changes a long of time

**Comment by kachkaev** [comment]
If there are slight changes in the API in future, they won't be so dramatic that waiting until they happen is worth it. [Quite a few plugins](https://prettier.io/docs/en/plugins.html#official-plugins) already use the existing API and the core team is aware that making breaking changes in Prettier is not desired. So feel free to give your jsp plugin a go now and share it on the plugins page once it's working 😉

**Comment by ikatyang** [comment]
Some hints for building plugins for various HTML template languages: https://github.com/prettier/prettier/issues/5286#issuecomment-442061386

**Comment by thorn0** [comment]
Prettier isn't going to add more languages to the core. This should be implemented as a plugin.
