### ISSUE TITLE
Angular HTML ngif - else issue

### ISSUE THREAD

**Issue by fredericouimet** [prettier/prettier#5539]
**Prettier 1.15.1**
When using the 'angular' formatter, this code:

<ng-container *ngIf="data?.title; **else** defaultTitle">{{ data.title | translate }}</ng-container>

gets reformatted this way: (notice the ":" after the "else")
<ng-container *ngIf="data?.title; **else:** defaultTitle">{{ data.title | translate }}</ng-container>

When forcing the "html" parser for *.component.html files, this does not happen.

**Expected behavior:**
no ":" gets added after the "else", as this is not a valid angular template syntax.

Thank you!
Frederic

**Comment by hawkrives** [comment]
See this thread: https://mobile.twitter.com/juristr/status/1065637494006472704

Namely https://mobile.twitter.com/ikatyang_/status/1065659926272368640 by @ikatyang:

> It's the same syntax as `trackBy: trackById`, we just didn't add a special case for it. Currently there's only one special case for `let hero of heroes` (it's same as `let hero; of: heroes`). We use the official Angular parser so it shouldn't break in the future.

---

Is it breaking your build? I'm very curious, since it didn't wind up breaking the build in the above thread.

**Comment by fredericouimet** [comment]
No, it's not breaking the build, it works fine. My IDE complains though so it's annoying; for now I'm using prettier-ignore on that line.
Tks for the quick answer!

**Comment by ikatyang** [comment]
After second thought, it should be common enough to add a special case for it.
