### ISSUE TITLE
TypeScript bigint support

### ISSUE THREAD

**Issue by vekexasia** [prettier/prettier#5545]
Hey Typescript 3.2 has bigint support but prettier marks the following with an error:

```typescript
let n = 1n;
```

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXmwEYoBuEAGhAgAcYBLaAZ2VC0wgHcAFLBFlOlQR6AE0ogARpnRgA1nBgBlGrPpQA5shiYArnCoALGAFsANgHVD9eE1Vg4S-jfqobAT2TgmLKuqZwmDDcMhom6MgAZuhmAVQAVkwAHgBCMvKKSugmcAAy6nBRMXEgiUlK6hpmcACKuhDwRbEGIKqYAZheMO40cExgmPR0EjSDsBZiMIbIABwADFSjEAEWMjReo32BqIVUmHAAjrr0+yHoYRFI0c1UASb02notTJXVdQ2FV8UtMOiSE6IpsgAExUHToehmSoAYQgJnCXig0F2IF0AQAKn8BNcAgBfXFAA)

**Comment by ikatyang** [comment]
Tracked in JamesHenry/typescript-estree#35.

**Comment by vekexasia** [comment]
Hello @ikatyang thanks for your work. I guess this will land in 1.15.3 right?
