### ISSUE TITLE
when i use parser ,it is wrong

### ISSUE THREAD

**Issue by Jason-story** [prettier/prettier#5548]
"prettier": "1.15.2",

this is package.json code

> 
    "prettier": {
        "printWidth": 120,
        "tabWidth": 4,
        "parser": "babylon",
        "trailingComma": "none",
        "jsxBracketSameLine": true,
        "semi": true,
        "singleQuote": true,
        "overrides": [{
            "files": "*.json",
            "options": {
                "tabWidth": 2
            }
        }]
    },
    "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "lint-staged": {
        "src/**/*.{js,jsx,mjs,css,scss,less,json,ts}": [
            "prettier --write",
            "git add"
        ]
    }

and this is the error message

```
> Can't find node in PATH, trying to find a node binary on your system
husky > pre-commit (node v8.11.1)
Stashing changes... [started]
Stashing changes... [completed]
Running linters... [started]
Running tasks for src/**/*.{js,jsx,mjs,css,scss,less,json,ts} [started]
prettier --write [started]
prettier --write [failed]
→ 
Running tasks for src/**/*.{js,jsx,mjs,css,scss,less,json,ts} [failed]
→ 
Running linters... [failed]
Updating stash... [started]
Updating stash... [skipped]
→ Skipping stash update since some tasks exited with errors
Restoring local changes... [started]
Restoring local changes... [completed]



✖ prettier --write found some errors. Please fix them and try committing again.

src/views/console/console.view.jsx 100ms

[error] src/views/console/console.view.less: SyntaxError: Unexpected token (1:1)
[error] > 1 | .component {
[error]     | ^
[error]   2 |     height: 100vh;
[error]   3 |     width: 100%;
[error]   4 |     display: flex;
husky > pre-commit hook failed (add --no-verify to bypass)
```

this is the less code 

```less
.component {
    height: 100vh;
    width: 100%;
    display: flex;
    flex-direction: row;
    overflow: hidden;
    .content-inner {
        padding: 16px;
        flex: 1;
        overflow-y: auto;
    }
}
```

**Comment by j-f1** [comment]
Thanks for opening an issue! The problem here is that the options include `"parser": "babylon"`, which forces Prettier to use the JavaScript parser for all files. Since Prettier is pretty good at determining which parser to use for a given file, you should be able to just remove that option and everything should work ✨

I’m closing this for now, but feel free to ask any additional questions you might have here.

**Comment by Jason-story** [comment]
thanks
