### ISSUE TITLE
Flow suppress_comments are moved when used inside parentheses

### ISSUE THREAD

**Issue by GordyD** [prettier/prettier#555]
With Flow you can use `$FlowFixMe`, or your own annotation, to suppress any linting errors that you will fix at a later time. The comment needs to on the line proceeding the line you wish to suppress. Following running prettier any of these comments inside parentheses are moved outside of the parentheses, resulting the underlying lint error no longer being suppressed.

See [Flow Docs - Advanced Configuration](https://flowtype.org/docs/advanced-configuration.html) (search for 'suppress_comment').

before:

```js
const aDiv = (
  /* $FlowFixMe */
  <div className="foo">
    Foo bar
  </div>
);
```

after:

```js
const aDiv = /* $FlowFixMe */
(
  <div className="foo">
    Foo bar
  </div>
);
```

[Prettier example](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20aDiv%20%3D%20(%5Cn%20%20%2F*%20%24FlowFixMe%20*%2F%5Cn%20%20%3Cdiv%20className%3D%5C%22foo%5C%22%3E%5Cn%20%20%20%20Foo%20bar%5Cn%20%20%3C%2Fdiv%3E%5Cn)%3B%5Cn%5Cn%2F*%20%24FlowFixMe%20*%2F%5Cnconst%20anotherDiv%20%3D%20%3Cdiv%20className%3D%5C%22foo%5C%22%3E%5Cn%20%20Foo%20bar%5Cn%3C%2Fdiv%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
This is likely going to be hard to fix because parenthesis are part of the expression and this is a leading comment, so it is printed as intended. It is not a goal to be able to make sure that all the flow/eslint disables keep working.

**Comment by vjeux** [comment]
@rattrayalex Do you know if there's an easy way to put the comment inside of the parenthesis. This triggers on quite a few files inside of Facebook and there doesn't seem to be a good workaround

```js
const aDiv =
  /* $FlowFixMe */
  (
    <div className="foo">
      Foo bar
    </div>
  );
```

**Comment by rattrayalex** [comment]
I don't know much about how comments in `prettier` work... is there a primer or high-level overview anywhere? PR discussion or a block of code would be fine. 

It's a topic I'm interested in
