### ISSUE TITLE
Generic type breaks line in none expected way

### ISSUE THREAD

**Issue by BernhardFuchs** [prettier/prettier#5554]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzOMwAsAKBDATwFsEYBnAJTjIFcAbGAEgAIBeZgChiwEsyA6PGBg9oZRvwioAKgQAOcDgDEAotIDCACQD6OAIIBNALIqActO0B5AGoqK1gJIqA6gEpmeMs0sAjMnAAnADc8Hzo4AB49YVEoAD5XfjIAdx5MLCM8OQ4Od1Y4gB0oZhLmbj5+OUISWDIAZUCgnjA4ItLS-nR03LbmVwBuEAAaEAg5ETFkUDwAgIhk-ACEMmQQPCCIHgATYZAfAKEAaww6qrAeKABzZBgAmjgRrBgiOmdeeDIzuAaoMjSeJowAirMBkFYjC7+AIwHAHS5EPDIVB4Oj+EYAKzIAA8AEIHMDHGB1PAkAAyFzgSJRaJAmKxdQul3CAEUaBB4FTUQ8QFUAlDVkCFGQwAEeONdnJRbBnNtuMgAIwABkVI0lEH8zgOclWkuojUpIyWAEcaDwlrC8PDEUhkVyRv4iDwbnduX8riy2RykLd7iMYKEZVs5UgAEx+g48OiM9QQIgI1ZQaAGkA0fzSUIrb0ugC+2aAA)
```sh
--parser typescript
--print-width 100
--single-quote
--use-tabs
```

**Input:**
```tsx
fetchPaymentsResult$ = (this.actions$.ofType(FETCH_PAYMENT_OVERVIEW) as Observable<Action>).switchMap(() =>
    this.paymentsService
      .fetch()
  );
```

**Output:**
```tsx
fetchPaymentsResult$ = (this.actions$.ofType(FETCH_PAYMENT_OVERVIEW) as Observable<
	Action
>).switchMap(() => this.paymentsService.fetch());

```

**Expected behavior:**
This ```Observable<Action>``` should not be broken apart.
An acceptable output would be 
```
fetchPaymentsResult$ = (this.actions$.ofType(FETCH_PAYMENT_OVERVIEW) as 
  Observable<Action>).switchMap(() => this.paymentsService.fetch());
```

**Comment by j-f1** [comment]
Is this a duplicate of #5399?

**Comment by BernhardFuchs** [comment]
Not sure. #5399 happens when chaining, this one is when assigning a type.

**Comment by octogonz** [comment]
I encountered a generic wrapping issue like this:

**Input:**
```ts
class MapItem { }

export class MyClass {
  public readonly const shortMap: Map<string, MapItem> = new Map<string, MapItem>();
  public readonly mapWithAlongerName: Map<string, MapItem> = new Map<string, MapItem>();
}
```

**Actual Output: (not pretty)**
```ts
class MapItem {}

export class MyClass {
  public readonly shortMap: Map<string, MapItem> = new Map<string, MapItem>();
  public readonly mapWithAlongerName: Map<string, MapItem> = new Map<
    string,
    MapItem
  >();
}
```

A better result might be like this:
**Expected output: (pretty)**
```ts
class MapItem {}

export class MyClass {
  public readonly shortMap: Map<string, MapItem> = new Map<string, MapItem>();
  public readonly mapWithAlongerName: Map<string, MapItem> 
    = new Map<string, MapItem>();
}
```

Prettier's approach might make sense if the generic arguments were complex expressions.  But in most cases they are simple names, which is not a good place to break out onto multiple lines.

If someone created a PR to fix this, would you accept it?

**Comment by j-f1** [comment]
> If someone created a PR to fix this, would you accept it?

Probably, as long as it includes tests and doesn't add an option :)

**Comment by TheNickmaster21** [comment]
I am experiencing the same or a similar issue:
```        
        return (((player: Player, ...args: unknown[]) =>
            (remoteFunction as RemoteFunction).InvokeClient(player, ...args)) as unknown) as ServerSideRemoteFunction<
            T
        >;
```

I would expect the formatter to not break in the middle of the <>s...

**Comment by thorn0** [comment]
Seems to have been fixed long ago. Prettier never breaks simple single-parameter generic types like `Observable<Action>` now.
