### ISSUE TITLE
Prettier changes the way HTML renders in JSX by adding newlines where spaces did not exist

### ISSUE THREAD

**Issue by jamietre** [prettier/prettier#5555]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhoB4qSBDKAPhgAsBLW-jVY0c0AOYjeUODQgAzGvCIxF3VitYkScVuVowINORTAyS5ODBi845RYZY5eMRsO4W5dADohjEHxzCFjjqvABucDgAniLiklAA1jQA7nxg3DTOcFSRCsm8ODg0UBAqcs68Kc58UKoyTtKSqM6MAPSsgbEq6BaKxCo86kJaOnpCcvB2PPVSSam86UYmcBg05pbWtvY0js6ZGmKsUm0s7BwgADQgECTW0FTIoLrkEMkACroIDyisYRC8GEuIAARuRWGAEpYAMpsMBSMTIGDkLBwK7cGCoHAAdT48FOpihXwqYWcUWQ4CoDyuUhylDeYLEqFYyDkrBwOSuACsqEQAEJgiHQ1ioOAAGSkcBZbI5IG5RCh8LwAEUsKVJUhWezUSA2HpbOTgaxgVFRFAgeYpDAsQCeMgABwABiu5ggOSxYJI5PWtIiQIsAEcsLwLPTWIzmRrpdqcs1Ecjo4q4Cq1VKtVcYEbrRhbUgAEzpsEFeEAYQgqCZ5JK0iBWByABUjd9NTkAL4toA)
```sh
--parser babylon
```

**Input:**
```jsx
module.exports = <span>this is a long line of text that appears to force prettier to split<a href="foo">a relatively long link which iteself will not fiti within the line limit</a>a lot more text that appears after the link which forced prettier to split it again</span>
```

**Output:**
```jsx
module.exports = (
  <span>
    this is a long line of text that appears to force prettier to split
    <a href="foo">
      a relatively long link which iteself will not fiti within the line limit
    </a>
    a lot more text that appears after the link which forced prettier to split
    it again
  </span>
);

```

**Expected behavior:**

It should not add a newline before and after the link.

To see how they render differently: https://codepen.io/jamietre/pen/OawNOE

**Comment by duailibe** [comment]
Hi @jamietre 

The way JSX is rendered is not the same as HTML. 

See how they render exactly the same: https://codesandbox.io/s/l2l4mnzzm9

**Comment by jamietre** [comment]
Ah.... ok. I saw a bunch of jest snapshot test differences after converting a large codebase to Prettier format. Since the snapshots are formatted themselves (e.g. don't depend on the input format) I incorrectly assumed this was a material change. There are some other differences w.r.t. trailing spaces, e.g. after Prettifying there are double-newlines in the snapshots, but this also should not matter.
