### ISSUE TITLE
Format PHP + HTML + JS + CSS at once? (Wordpress)

### ISSUE THREAD

**Issue by kkmuffme** [prettier/prettier#5556]
Will it be/is it possible when using prettier + the coming PHP plugin, to prettify a .php file that contains php + html + inline js (<script>) + inline css (<style>)?

Atm I am using phpcs + eslint at the moment, which struggle and output a complete chaos of indentation unless it was already correct (& even then they sometimes mess it up, if its a mixed file, like it's often encountered in WP core & plugins)

**Comment by kachkaev** [comment]
This is probably a question to https://github.com/prettier/plugin-php. If they figure out how to mark certain parts of a .php file as html, css and js, formatting this mix of four languages should be possible. The approach would be similar to the one used to format code blocks in markdown files.
