### ISSUE TITLE
Disable/Enable prettier for a line, the next line or until I activate it again

### ISSUE THREAD

**Issue by muuvmuuv** [prettier/prettier#5559]
**Environments:**
- Prettier Version: 1.15.2
- Running Prettier via: VS Code plugin [Unibeautify](https://github.com/unibeautify/unibeautify)
- Runtime: Node.js
- Operating System: macOS 10.14.1

**Expected behavior:**

Using a flag to disable prettier for a line, the next line or until I activate it again (ESLint like syntax).

```ts
// prettier-disable
  border: {
    sep: "║",
    topLeft: "╔", topMid: "╦", top: "═", topRight: "╗",
    midLeft: "╠", midMid: "╬", mid: "═", midRight: "╣",
    botLeft: "╚", botMid: "╩", bot: "═", botRight: "╝"
  },
// prettier-enable
```

**Actual behavior:**

```ts
border: {
    sep: '║',
    topLeft: '╔',
    topMid: '╦',
    top: '═',
    topRight: '╗',
    midLeft: '╠',
    midMid: '╬',
    mid: '═',
    midRight: '╣',
    botLeft: '╚',
    botMid: '╩',
    bot: '═',
    botRight: '╝'
  },
```

**Comment by j-f1** [comment]
You can use `// prettier-ignore` for this case, though.

**Comment by muuvmuuv** [comment]
@j-f1 no, this would tell prettier to ignore the whole file.
