### ISSUE TITLE
Latest version make HTML code and vue templates unreadable

### ISSUE THREAD

**Issue by events-jonas-chrisw** [prettier/prettier#5564]
I have just updated prettier in VScode and now if makes  aright old mess of html and vue.js template code.

Fort example it turns:

```html
           <div class="columns report-title" id="report-title">
                <page-title title="Pre-Event Report" width="is-three-fifths" subtitle="View your pre-event attendance report."></page-title>
                <event-selector class="column has-text-right-tablet" v-if="eventListLoaded" />
            </div>
```

into

```html
        <div
          class="columns report-title"
          id="report-title"
        >
          <page-title
            title="Pre-Event Report"
            width="is-three-fifths"
            subtitle="View your pre-event attendance report."
          ></page-title>
          <event-selector
            class="column has-text-right-tablet"
            v-if="eventListLoaded"
          />
        </div>
```

and one line of code like this:

```html
<grid-item class="dash-panel" v-for="(item,index) in layout" :x="item.x" :y="item.y" :w="item.w" :h="item.h" :i="item.i" :minH="griditem.minH" :minW="griditem.minW" :maxH="griditem.maxH" :maxW="griditem.maxW" :key="index" :drag-allow-from="griditem.dragAllow">
```

into

```html
          <grid-item
            class="dash-panel"
            v-for="(item,index) in layout"
            :x="item.x"
            :y="item.y"
            :w="item.w"
            :h="item.h"
            :i="item.i"
            :minH="griditem.minH"
            :minW="griditem.minW"
            :maxH="griditem.maxH"
            :maxW="griditem.maxW"
            :key="index"
            :drag-allow-from="griditem.dragAllow"
          >
```

Makes the code look a right old mess, makes it unreadable and doubles the length of my source files. 

Not exactly progress. Is there any way to go back to an older version, as I have had to disable prettier from my vscode setup?

**Comment by lydell** [comment]
> Is there any way to go back to an older version

Yes! You can install any npm package at a specific version using the `package-name@version` syntax. For example, you can run `npm install prettier@1.14`.

**Comment by events-jonas-chrisw** [comment]
how do you do that as a vscode extension??

**Comment by j-f1** [comment]
You should also be able to create a `.prettierignore` file that acts like a gitignore, but stops Prettier from formatting matched files.

**Comment by CinKon** [comment]
Could you share your prettier- and eslint-settings? I really want to force the code style that is unreadable for you, since it is the style the vue-recommended eslint-settings wants.

**Comment by danielgolden** [comment]
@events-jonas-chrisw Isn't that formatting what's recommended in the [vue style guide](https://vuejs.org/v2/style-guide/#Multi-attribute-elements-strongly-recommended)?

**Comment by events-jonas-chrisw** [comment]
> @events-jonas-chrisw Isn't that formatting what's recommended in the [vue style guide](https://vuejs.org/v2/style-guide/#Multi-attribute-elements-strongly-recommended)?

yep, still doesn't make it easy to read...

**Comment by phifa** [comment]
`"vetur.format.defaultFormatter.html": "prettyhtml"`

This made it work for me.
