### ISSUE TITLE
Update to prettier marks line endings as issues on windows

### ISSUE THREAD

**Issue by ImreC** [prettier/prettier#5567]
I am on a windows machine and after updating prettier my line endings are marked as a problem. This means that every file in my entire project is marked red. I personally have cared very little about line endings and am not ready to start doing this today. How do I switch this behavior off? I have added an ignore rule to my eslintrc, but this doesn't stop prettier from busting my balls. 

Updated from:
```
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "eslint": "^5.0.1",
    "eslint-config-prettier": "^3.1.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-prettier": "2.6.2",
    "eslint-plugin-vue": "^4.0.0",
    "node-sass": "^4.9.4",
    "nodemon": "^1.11.0",
    "nuxt-imagemin": "^1.0.0",
    "prettier": "1.14.3",
    "sass-loader": "^7.1.0"
  }
```
Updated to:
```
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.9.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-prettier": "3.0.0",
    "eslint-plugin-vue": "^4.7.1",
    "node-sass": "^4.10.0",
    "nodemon": "^1.18.7",
    "nuxt-imagemin": "^1.0.0",
    "prettier": "1.15.2",
    "sass-loader": "^7.1.0"
  }
}
```

**Comment by evilebottnawi** [comment]
@ImreC do you have `.editorconfig`?

**Comment by lydell** [comment]
It’s starting to feel like reading .editorconfig creates more issues than it solves…

**Comment by evilebottnawi** [comment]
@lydell it is expected, for me it is invalid and misleading use `.editroconfig` with `LF` option and use `CRLF` in source code.
