### ISSUE TITLE
Any use case of "filepath" in .prettierrc?

### ISSUE THREAD

**Issue by alanyinjs** [prettier/prettier#5571]
I am not quite sure how to use `filepath` in .prettierrc. The doc suggests `Specify the input filepath. This will be used to do parser inference.` My understanding is that this can potentially be used to override the default parser.

![screen shot 2018-11-29 at 1 16 25 am](https://user-images.githubusercontent.com/25688258/49157729-99fc3a00-f374-11e8-8aa9-b77e8dc7689d.png)

However I am not sure if there is a use case for this as it is suggested across the whole doc that we use `files`, e.g. 

```
{
  "overrides": [
    {
      "files": "src/**/*.js",
      "options": {
        // some options here
      }
    }
  ]
}
```

I am also assuming that it is a deliberate choice to only target files in the CLI command, as suggested in the following issue: #3042

**Comment by j-f1** [comment]
This option is only really useful in the CLI or Node API if you’re passing code instead of a file path.

**Comment by j-f1** [comment]
Actually, we should clarify this in the docs.
