### ISSUE TITLE
Issue parsing arrow functions in union type when not wrapped in parentheses

### ISSUE THREAD

**Issue by SnailCoil** [prettier/prettier#5580]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAWQE8BhCAWyygX2AB0o88ABASSgYArjAAUASjzCARoQCWYPA2oDhMJHgl4AvAD48AQWzZi1ADw0A8tIBWcMDH0AfQ8dMXq1uw90BuTgC+nCAANCAQGDBy0KTIoMTGEADuAAoJCLEoxABuEHIAJqEg0iZgANZwMADKGMRgclAA5sgw2EJwYQAWMAyEAOqdcvCktWBwVRlDctlD1Mjg5EUNpHC4KSaNDMTIAGbEhCthNqRoAEKlFdXEDHAAMg1wu-uHIMdoVQ2NhHAAikIQ8CeBw6IFq2BW2HmMGoGDgpDA2DkkSKGERsD6BRgnWQAFYAAxhVEQFZ9EwYeaouGrbKPMLYOAARyEcnp62Im22SD2wLCKwYchabRBpE+3z+AMeXOeIJgxGkGPyWOQACYwq1iHJ5E16AwtvMoNBaSAhCsACpyzLcl5kGBAl75CBgO0giAiNTK50BAJAA)
```sh
--parser typescript
--print-width 50
```

**Input:**
```tsx
export class MyComponent {
  @Input() public myInput: () => Array<MyObject> | Array<MyObject>;
}

```

**Output:**
```tsx
export class MyComponent {
  @Input() public myInput: () =>
    | Array<MyObject>
    | Array<MyObject>;
}

```

**Expected behavior:**
```tsx
export class MyComponent {
  @Input() public myInput:
    | (() => Array<MyObject>)
    | Array<MyObject>;
}

```

It seems like there's an issue parsing the first arrow function in the union type, because this probably isn't a widely used syntax (in order for this syntax to be valid without parentheses, it has to be the first type in the union type). I looked at the generated AST, and it seemed like it was treating the two sides of the union type identically. 

The easy workaround is to insert parentheses around the arrow function manually, at which point it's interpreted correctly:

**Input:**
```tsx
export class MyComponent {
  @Input() public myInput: (() => Array<MyObject>) | Array<MyObject>;
}

```
**Output:**
```tsx
export class MyComponent {
  @Input() public myInput:
    | (() => Array<MyObject>)
    | Array<MyObject>;
}

```

**Comment by j-f1** [comment]
The parser we use (which uses the official TypeScript parser internally) interprets this as we print it. You can check this by enabling the AST checkbox on the playground in the debug section.
