### ISSUE TITLE
html: Closing > put on newline

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#5582]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAJgJYBuzU557br379BPFiJFjhkqZ3F9Zk6RKWyVitbIBKcAM4AHaHrjkARhDYBPVVuXwAHjACGAJzjPbdyVGc04ALxMIO7OnFD6esSuEGZwAHTuhsYJFtbBXt4MwMDkoeGR0bEJSUZQJvFpVuQAvjWoAPSOLqEy3o3ybWodQplSDZ19PQrKA72Kw7yTLCAANCAQBjAcxsigbjEA7sRuCHrIIM5cEBxscyBmrs5gANZwMADKBtccUADmyDCuAK5w89T0ADqlA48EM1zgDz2oO4oKsBzAen281eJlcMGizjeNGcyAAZs46CZ5gArPQOABCV1u9wefjgABlXnB8YTiSAyQ4Hq83nQ4ABFb4QeCsol-EDPVxog4AujnAyuV4wQGnGCUZAADgADPMFRATICrgYDgr9HBXFwWfN3ABHb4cdyY7G4pAEsXzEw0DifH7ivQ8vmC4Us11s8UuMwqthq5AAJnmX2cHDoPNwEBoOIOUGgVpA3xM+GcZn2obFdSAA)
```sh
--parser html
```

**Input:**
```html
<!DOCTYPE html>
<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              Response body
              <textarea
                name="readinessProbe.response.body"
              >{{ readinessProbe.response.body }}</textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

```

**Output:**
```html
<!DOCTYPE html>
<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              Response body
              <textarea name="readinessProbe.response.body">
{{ readinessProbe.response.body }}</textarea
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

```

**Expected behavior:**
Not to change the input. The input comes from 1.15.2.

```html
</textarea
>
```

That part is the thing I'm reporting, if the amount if divs were confusing 😅 

`html-whitespace-sensitivity` doesn't matter, btw

**Comment by ikatyang** [comment]
Partially related to #5377, but it seems you forgot to use the angular/vue parser? which should trigger the formatting for interpolations:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAJgJYBuzU557br379BPFiJFjhkqZ3F9Zk6RKWyVitbIBKcAM4AHaHrjkARhDYBPVVuXwAHjACGAJzjPbdyVGc04ALxMIO7OnFD6esSuEGZwAHTuhsYJFtbBXt4MwMDkoeGR0bEJSUZQJvFpVuQAvjWoAPSOLqEy3o3ybWodQplSDZ19PQrKA72Kw7yTLCAANCAQBjAcxsigbjEA7sRuCHrIIM5cEBxscyBmrs5gANZwMADKBtccUADmyDCuAK5w89T0ADqlA48EM1zgDz2oO4oKsBzAen281eJlcMGizjeNGcyAAZs46CZ5gArPQOABCV1u9wefjgABlXnB8YTiSAyQ4Hq83nQ4ABFb4QeCsol-EDPVxog7Od7fOhuc4GVyvGCA04wSjIAAcAAZ5sqICZAVcDAdlfo4K4uCz5u4AI7fDjuTHY3FIAli+YmGgcT4-cV6Hl8wXClketnilxmdVsTXIABM8y+zg4dB5uAgNBxByg0FtIG+JnwzjM+wjYrqQA)
```sh
--parser angular
```

**Input:**
```html
<!DOCTYPE html>
<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              Response body
              <textarea
                name="readinessProbe.response.body"
              >{{ readinessProbe.response.body }}</textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

```

**Output:**
```html
<!DOCTYPE html>
<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              Response body
              <textarea name="readinessProbe.response.body">{{
                readinessProbe.response.body
              }}</textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

```

**Comment by SimenB** [comment]
Is it related to that? This is closing `>` on the closing tag, not the opening tag.

That said, we should probably use another parser, even though I'd expect the content of a `textarea` to just be treated as plain text in the `html` parser

**Comment by SimenB** [comment]
Feel free to close however, as changing the parser works fine 🙂

**Comment by ikatyang** [comment]
> Is it related to that? This is closing `>` on the closing tag, not the opening tag.

Since `--jsx-bracket-same-line` is defined as _"do not put `>` alone on the next line"_, #5377 should track it for both opening and closing tags.

> That said, we should probably use another parser, even though I'd expect the content of a `textarea` to just be treated as plain text in the `html` parser

If you intend to use it as an interpolation, you should use one of the parser that supports interpolation since there's a special rule for `<textarea>` in the HTML spec that the first LF will be ignored in `<textarea>`. That said, the following formatting can be unsafe based on the value of the interpolation:

```html
<!-- before -->
<textarea>{{something}}

<!-- after -->
<textarea>
{{something}}
```

It'll break the output if `{{something}}` is interpolated as something starts with LF since there will be two LF and only the first one will be ignored, causes an extra LF.

And also, continuous whitespaces in `<textarea>` can not be collapsed but it's not the case for interpolations.
