### ISSUE TITLE
Typescript Ignores Quote Style Rules

### ISSUE THREAD

**Issue by domske** [prettier/prettier#5583]
I just installed Prettier `1.7.2` in VS Code `1.29.1`. Working in an Angular 7.1 (TypeScript).
Formatting a ts-file replaces all single quotes to double quotes. 
It's against tslint settings and / or editorconfig. What does the setting `auto` mean?
How does the Prettier recognize the quote style? What does `auto` mean?
Prettier should initially work with the optimal settings. ...

**Comment by ikatyang** [comment]
What did you mean `auto`? `auto` is only allowed to be used in [`--end-of-line`](https://prettier.io/docs/en/options.html#end-of-line), which seems unrelated to quotes. Can you share a [playground](https://prettier.io/playground/) link that can reproduce the issue?

**Comment by domske** [comment]
Sorry, that's right. There is no `auto` option. Do I understand this correctly? Prettier does not detect this automatically. It's a fix option to use single or double quotes.
I just expected that it detects from project settings. There are several methods to do this.
e.g. The file (js/ts) it self, the .editorconfig file or tslint settings. etc. 
Ok for a workaround I could add a settings json for vscode to the vscode workspace folder to overwrite this. But I you want, you can add this as feature request or close this. - Thanks for your time.

**Comment by j-f1** [comment]
We do support editorconfig, but we don’t read linter settings.

**Comment by domske** [comment]
Ok and how to setup editorconfig for this option?
```text
[*.ts, *.js]
quote_type = single
```
(?)

**Comment by j-f1** [comment]
That should be working, since the editorconfig parser supports it. Does only specifying one glob in the header help Prettier parse the config?

**Comment by domske** [comment]
Yes it works. Anyway `.prettierrc` is also a way to do this.
