### ISSUE TITLE
Flow comment syntax gets doubled in output

### ISSUE THREAD

**Issue by wincent** [prettier/prettier#5584]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEU4HcAEAxCED0AVEkpgDwDOMATgJZQDmAfIfgBQCUA3CADQgQADjFrQKyUAENq1COgAK0hOJSSAbhFoATPiABG1SWADWcGAGVBR+g2Q0ArnH4ALGAFsANgHVnteBSswOHNlP1o1PwBPZHAKcX56CjhqGHlDBjdJZAAzSQ8k-gArCgAPACFDEzNzSTc4ABl6OBy8gpBikvMbDzgARXsIeBb8pxAraiTqGL1JPUiPaF1BOlgvbRhnZAAOAAZ+ZYgkr0NBGOW4SbVm-mo4AEd7Wlu0yQyspFyR-iS3WjtqRzfbp9AZDD6tUYwWZrLQbZAAJn4NEktA8NgAwhA3JkYlBoNcQPYkgAVWYqT5JAC+lKAA)
```sh
--parser babylon
```

**Input:**
```jsx
new Foo/*:: <string>*/();
```

**Output:**
```jsx
new Foo /*:: <string>*//*:: <string> */();

```

**Expected behavior:**

I'd expect the `/*:: */` comment to be passed through untouched.

Doesn't happen with `/*: */` or `/* */` comments, only with `/*:: */` comments.

**Comment by j-f1** [comment]
You can work around this by placing `// prettier-ignore` on the line before this code.

**Comment by thorn0** [comment]
Not an issue anymore because support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687
