### ISSUE TITLE
vue: Issue Vue Template Formatting

### ISSUE THREAD

**Issue by pavons** [prettier/prettier#5585]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDOcYMAltGWPlVQLzHjQx71RwATlxLkKlACb0AbqPHjUAGQgBzCGQD0c+ZQAWARmasOXBjBxwRWQRABWtGKg0Ht81LoBMRvG04gqAK4ARmYWVjb2dE6ergpS0t6+XDj8ANZUIqQ6CnhkuoJwAGZ+ujAwWFRIGhpQAQAeMLZUAHQQgioaXGS87XAwfgD6QfhQqV0sPiYgQQFl0AC08yoFCCIAIhBgVE54sW5UWHjk+UUlZRVVGir0MLrBzZAYNfUwzw3NTV09Kn2Dw0djECJKYzOZQRbLOAATxEAHEbgAJYJOA5HPaUDTxWJOLFZDE0OiMKCiJyYXAEOCiUjUMCCehYGCiejYNowMjKNRkQo2DBkADkAD8NI8sNAEDAqBoORBmtIAnA+QBuUikOB1UWCNkSIp4AI4NnAPEisWwSpkQ1iCjSgA0eIAvraxBICHgABQASnNeIoBRgAUE5At2VCcCQ-IAonU8NgLHzHfI7cqxA68bo4HgJB6vZayL7-YHveIQ2HbvQWiH4zoMH08GGANqF+TAPL0CRhvnaqi0+kMaBxshQaOh-md7sMon9yCwcXtgCSUG1dTIAAU8D8+WQUzmKABdSsURP2x2HqAoseMlWnqgwKEWMgjFR+LtsLpdiBYOASUQPHh8ASCbMKAwfh5jTegVFKMN9AABmg6RdCTCgpAOfAoTDQoLDqRCyFsAJr3oQooXmKd4FgMMwHFIRsLwFIVHBG44AwM0KOnQRsPgBp5ho8CoHIyi2NIO1L2aENAK5Hh5kKaN6BwND+QARQCegwHSI4JH7PkAGUIH9CiyE0o4qBXGx+y4rBcDgeYqCha9GOtMgACEUlGABZPAwE0mzMAAMR4fd+U0uA1DgMgAFVZ37AAlCAgggGAIHsvkETgHBpD6ZTcgAOTgeV+wAQTpGj7KoQyrKEAjsOQ8k5OGTZUmwwoJIAdzgcDILIABmWCGokqh6AAL2HGDoKwLCjQgHA2jDABiDqAFYABYAE45rgbCLDKIQrMOMB+BUKDRqTISoFIZpAhCG47yDcTYHmFq2pgMMuugnrbr6wawwWjxDvGybBBmuaPAANgWgAOUHsKatoJG29y9rDOafrEQ4JCkKAVHmWK5gwKDEbGqBjtO5z0jElG0Yx+KsFxpHjpRG8LFEEBrRAd9eygKhkFAPBBBsJrVwKdnkBAPBpAgVsmemQR3NSPpNJ2vbkBgQR5WZ0oMBwAB1XQGNRCjAvZm4ZBuKEha2Dnmf4GhNWXKWVAwPBkCknAaGZpo6gcqWVNlodFH4OBHZol2QDdzS9osRS4v9pAnaDw5BCtoW5X95nrH4GANdbW5kFB6CU5sGgNalrAhesOArbSiWCgARyUgobbXe2A+duBmZoYDFeVlv-DDuAI-gJug94IIM4kLOkA8Zmlb4ZyVAAYQgDBG5QKAxQlvC4AAFTwIIOejwO4DtO0gA)
```sh
# Options (if any):
--parser vue
```

**Input:**
```vue
<template>
  <section class="container">
    <div>
      <Logo />
      <h1 class="title">project</h1>
      <h2 class="subtitle">project</h2>
      <div class="links">
        <a href="https://nuxtjs.org/" target="_blank" class="button--green">Docs</a>
        <span href="https://github.com/nuxt/nuxt.js" target="_blank" class="button--grey">GitHub</span>
      </div>
    </div>
  </section>
</template>

```

**Output:**
```vue
<template>
  <section class="container">
    <div>
      <Logo />
      <h1 class="title">project</h1>
      <h2 class="subtitle">project</h2>
      <div class="links">
        <a href="https://nuxtjs.org/" target="_blank" class="button--green"
          >Docs</a
        >
        <span
          href="https://github.com/nuxt/nuxt.js"
          target="_blank"
          class="button--grey"
          >GitHub</span
        >
      </div>
    </div>
  </section>
</template>

```

**Expected behavior:**
```vue
<template>
  <section class="container">
    <div>
      <Logo />
      <h1 class="title">project</h1>
      <h2 class="subtitle">project</h2>
      <div class="links">
        <a href="https://nuxtjs.org/" target="_blank" class="button--green">
          Docs
        </a>
        <span
          href="https://github.com/nuxt/nuxt.js"
          target="_blank"
          class="button--grey"
        >
          GitHub
        </span>
      </div>
    </div>
  </section>
</template>

```

**Comment by j-f1** [comment]
This is by design; see https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting for details.
