### ISSUE TITLE
Prettier adds parentheses around condition assignment inside other parentheses

### ISSUE THREAD

**Issue by SilencerWeb** [prettier/prettier#5591]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQA9MC8mADAJSbAA6UmmAbgIYBOmARoZgIwDc1AvtUFR0AVyhgYqaJgDOcGAAk4qAOYALGNhkQAtnAByEACZxyVGpiMQK1WrW17DJgHRrl6mBwDknYsQAOuF68FnyYAO5qqAA2cDgOBsZxRAlOcM7+zAgwaaQhfCAANCAQ-pLQMsigzEwQ4QAKWVCVKAx0EKhGRSCsTAxgANbyAMqZYKhQKsgwTCJwxRo60QDqUfAyY3DDCDKoknR7AJ7I4DKVxRNyTDD1fSo6DMjoDNFyxQBWMrgAQn2DIww9AAZCZwJ4vN4gT64YYTFSxACKIgg8HBr3mIEyTCuJ1YDFYh2i0G6-iYExgy06MDUyAAHMRiqSIHJln1-CdSXArnQwcUmHAAI4iVD824Me6PJDPdHFOQ6VDTWYY3aTRHI1FSiEYmD4ylGanIABMxRmDBicIAwroHicoNBeSARHIACr4lrSuR8PhAA)

**Input:**
```jsx
if (x = 0) {
  var b = 1;
}


function setHeight(someNode) {
  do {
    someNode.height = '100px';
  } while (someNode = someNode.parentNode);
}
```

**Output:**
```jsx
if ((x = 0)) {
  var b = 1;
}

function setHeight(someNode) {
  do {
    someNode.height = "100px";
  } while ((someNode = someNode.parentNode));
}
```

**Expected behavior:**
No parentheses should be added around `x = 0` and `someNode = someNode.parentNode`.

**Comment by lydell** [comment]
Hi! This is actually intentional, since it is a common convention to wrap assignments in conditions in extra parens to show that you actually meant to use assignment (`=`) instead of comparision (`===`) (which is an easy mistake to make). For example, the [no-cond-assign](https://eslint.org/docs/rules/no-cond-assign) ESLint rule has an `except-parens` option for this case.

**Comment by lydell** [comment]
If Prettier _didn't_ add those parens, people who do want them would feel as if  Prettier removed them. We can't make everyone happy! Luckily, this kind of code is rare, so you should be able to stand a couple of extrea parens there, right?

There won't be an option for this – see our [option philosophy](https://prettier.io/docs/en/option-philosophy.html).
