### ISSUE TITLE
[Angular] Spaces for pipe and its arguments

### ISSUE THREAD

**Issue by superamadeus** [prettier/prettier#5601]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAwhAtgB2gmACmAB0oACc+XAGwEN4lyADMkmYYcrATwDU6NAK5xyAH248ACgEsccJL1nyAggCcA5uQC+2spVZRtASjJh6AZwvkAsj0y58scqQqTlcdRqZ0oPANxk2iAANCAQODAy0BbIoHRqahAA7lIJCLEodABuEDIAJqEgAEZqdGAA1nAwAMo45TJQGsgwaiJhABYwWDQA6h0y8Bb1YHA1GYMy2YM8yOBWRY0WcGowUmUaWHTIAGaCy2EAVhYAHgBCZZXVNXRYcAAyjXC7+3BHpzWNGjRwAIpCEHgLxoBxA9TUyzUcxgPHkFjAajkMCKOERsF6BRgHWQAA4AAxhVEQZa9Mo4OaouCQ7LPMJqOAARyEMnp6zom22SD2ILeIGWWBkLTavIsXx+-0Bzy5rzCMDoxQx+SxyAATLKyjIaF8HFs5lB8EUhMsACryzLc5a6IA)
```sh
--parser typescript
```

**Input:**
```tsx
@Component({
  template: `
	{{ myValue | myPipe:myPipeArg }}
  `
})
class MyComponent {
  myPipeArg: any;
}
```

**Output:**
```tsx
@Component({
  template: `
    {{ myValue | myPipe: myPipeArg }}
  `
})
class MyComponent {
  myPipeArg: any;
}

```

**Expected behavior:**

Prettier should not add a space between `myPipe` and `myPipeArg`. This causes a runtime error in angular because it's invalid syntax. Only way to make it so prettier only format the typescript and not the html in my inline template is to use `// prettier-ignore`, which I hate doing, so this is pretty infuriating. 

EDIT: Updated playground link to the latest version in `prettier.io`.

**Comment by j-f1** [comment]
cc @ikatyang

**Comment by aboyton** [comment]
I've not had any problems with having spaces here in my code, nor when playing around with StackBlitz. What version of Angular are you using?

You can test putting spaces in here and everything still works.

https://stackblitz.com/edit/angular-pipes?file=app%2Fapp.component.html

**Comment by superamadeus** [comment]
Okay, inexplicably, I can no longer repeat the error which was occurring before. I got rid of the offending code since I made this issue.

I can't explain it with any more detail because I don't remember, but I was literally adding the space, getting the error, removing it, not getting the error. Every time. 

Now I don't.

So I guess it's not a syntax error. Either way, would anyone agree that the correct formatting for pipes is `myPipe:myArg1:myArg2` and not `myPipe: myArg1:myArg2` a la:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAwhAtgB2gmACmAB0oACc+XAGwEN4lyADMkmYYcrATwDU6NAK5xyAH248ACgEsccJL1nyAggCcA5ouly46jQCZyAX2NlKrKMYCUZMPQDOD8gFkemXPljlSFScr1NJjooHgBuMmMQABoQCBwYGWgHZFA6NTUIAHcpdIQUlDoANwgZABMYkAAjNTowAGs4GABlHDqZKA1kGDURWIALGCwaAHV+mXgHNrA4ZvyJmSKJnmRwJ0qOhzg1GClajSw6ZAAzQS3YgCsHAA8AIVqGpua6LDgAGQ64E7O4S5vmjoaGhwACKQgg8G+NHOIDaai2alWMB48gcYDUchglRwGNgI3KMH6yAAHAAGWI4iBbEa1HCrHFwBFFL6xNRwACOQhkbL2dAORyQp2hvxAWywMm6vRFDkBwLBEK+gp+sRgdCq+LKhOQBhVtRkNEBHkOqyg+EqQi2ABU1QUhVtTEA)
```sh
--parser typescript
```

**Input:**
```tsx
@Component({
  template: `
	{{ myValue | myPipe:myPipeArg:myPipeArg2 }}
  `
})
class MyComponent {
  myPipeArg: any;
}
```

**Output:**
```tsx
@Component({
  template: `
    {{ myValue | myPipe: myPipeArg:myPipeArg2 }}
  `
})
class MyComponent {
  myPipeArg: any;
}

```

**Comment by superamadeus** [comment]
Thanks for the context. After thinking about it, I accept that formatting decision. I feel silly for having created this issue. I still can't seem to repeat the error I encountered in the first place but I suppose it must have been a bug in Angular.
