### ISSUE TITLE
Why doesn't prettier format this expression on single line?

### ISSUE THREAD

**Issue by 1MikeMakuch** [prettier/prettier#5609]
I believe prettier should be making this push expression into a single line, well within the 120 print-width I'm using here.

Here is a short js file:

    $ cat test.js
    var promises = [];
    promises.push(
      refunds.rebuildUserProducts(orderData.order.UserId, {
        transaction: t
      })
    );
    promises.push(refunds.rebuildUserProducts(originalUserId, {transaction: t}));

Now I prettier it and it doesn't change anything, I expect it to put the 1st push on 1 line but it doesn't.

    $ prettier --print-width 120 test.js
    var promises = [];
    promises.push(
        refunds.rebuildUserProducts(orderData.order.UserId, {
            transaction: t,
        }),
    );
    promises.push(refunds.rebuildUserProducts(originalUserId, { transaction: t }));

Prettier claims to put as much as possible (or reasonable) on one line, but it didn't! (That line is only 85 chars in width)

But if I modify that push to be a single line prettier correctly leaves it alone:

    $ cat test.js
    var promises = [];
    promises.push(refunds.rebuildUserProducts(orderData.order.UserId, {transaction: t}));
    promises.push(refunds.rebuildUserProducts(originalUserId, {transaction: t}));

    $ prettier --print-width 120 test.js
    var promises = [];
    promises.push(refunds.rebuildUserProducts(orderData.order.UserId, { transaction: t }));
    promises.push(refunds.rebuildUserProducts(originalUserId, { transaction: t }));

I expect prettier to deterministically format the file but in this case it is not. It leaves it either way.  What is going on here? Am I missing something?

Thanks
Mike

    $ prettier --version
    1.15.3

**Comment by j-f1** [comment]
Hello!

This is an [intentional behavior](https://prettier.io/docs/en/rationale.html#multi-line-objects):

> By default, Prettier’s printing algorithm prints expressions on a single line if they fit. Objects are used for a lot of different things in JavaScript, though, and sometimes it really helps readability if they stay multiline. See [object lists], [nested configs], [stylesheets] and [keyed methods], for example. We haven't been able to find a good rule for all those cases, so Prettier instead keeps objects multiline if there's a newline between the `{` and the first key in the original source code. A consequence of this is that long singleline objects are automatically expanded, but short multiline objects are never collapsed.

[object lists]: https://github.com/prettier/prettier/issues/74#issue-199965534
[nested configs]: https://github.com/prettier/prettier/issues/88#issuecomment-275448346
[stylesheets]: https://github.com/prettier/prettier/issues/74#issuecomment-275262094
[keyed methods]: https://github.com/prettier/prettier/pull/495#issuecomment-275745434

As of a recent Prettier version, you can just delete the newline after the `{` to make the object format back onto a single line.

**Comment by 1MikeMakuch** [comment]
I guess at some point I should RTFM. Thanks.

**Comment by mark-os** [comment]
@j-f1 I was also surprised by this behavior. Perhaps you can mention somewhere in the docs that Prettier is not attempting to be fully deterministic, and that if people want that, they will have to look for something like [escodegen](http://estools.github.io/escodegen/demo/index.html) (implemented in CyberChef).

**Comment by lydell** [comment]
That already is mentioned in it. @j-f1 linked to it. Do you have any other suggestions?

**Comment by mark-os** [comment]
My point is that while the docs mention behavior w.r.t. newlines after braces, they don't say "this is not deterministic and it's not trying to be". Some people are expecting that.

So under "what prettier is not concerned about" put "being deterministic". In some situations that's exactly what people are looking for. Comparing two files for instance, and not just a single commit but two versions of the same JS across multiple commits. I expected that I could run prettier on both files and then compare, but what I needed was a different tool.
