### ISSUE TITLE
Styled-components and custom css properties

### ISSUE THREAD

**Issue by fcaldera** [prettier/prettier#5614]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwHIdTy6BuAHSg2z3wGcYAngBs4AE3xUa9fsLEBaSFmgIYvVhy64CAYRI5xk2nQB0Ael371UDpCj98AZUEjRABQCuOMAAsSvOBbiALx8zmIAFIEAlAAGHPj46KhQcgDuqKIw3kj4AEwADPmYAB7sUAkARmQA1gDm1O5QogoQQrg5AG564XJyACTAmNSYvPhBAHz4QxAjxpBtOAC+UWUJ8+34AMQUO2UxZSAANCAzMKjQvMigetSprnoIlygkHRAZRyAVODVwMA6YZGStWQMBw7jgx28MHQQgA6t5UPBeACwHAHI9EagOoiBMhwLxLsdkv48K5vrV0CRkBQSEJ-McAFa8YoAIW+YGqvwcJHQcAAMsk4NTafSQEzig4gSIAIruCDwYV0iEgAE4El4qoVYTQD5DZIwWEZLLIAAc+WO038sO+mDxQzgJI6QuOjAAju5UIwySQKVSkDSlcd-EkQWDlbwpXBZfKhUhQeDjjASBVDZlvMhconvqghEDtDRKXiHQBWD7ufwAFWTTwD-kWiyAA)
```sh
--parser babylon
--single-quote
--trailing-comma es5
```

**Input:**
```jsx
import React from 'react';
import styled from 'styled-components';
import Card from './Card';

const StyledPurchaseCard = styled(Card)`
  min-width: 200px;
  background-color: var(--${props => props.color});
  color: #fff;
`;

```

**Output:**
```jsx
import React from 'react';
import styled from 'styled-components';
import Card from './Card';

const StyledPurchaseCard = styled(Card)`
  min-width: 200px;
  background-color: var(-- ${props => props.color});
  color: #fff;
`;

```

**Expected behavior:**
Prettier should not add a space between the custom property name prefix `--` and the template literal placeholder `${props => props.color}`. It causes an invalid property value and the style is not applied.

```jsx
import React from 'react';
import styled from 'styled-components';
import Card from './Card';

const StyledPurchaseCard = styled(Card)`
  min-width: 200px;
  background-color: var(--${props => props.color});
  color: #fff;
`;

```

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/7883
