### ISSUE TITLE
[JS/TS] [Suggestion] Enforce empty line between ModuleDeclarations and Statements

### ISSUE THREAD

**Issue by jeysal** [prettier/prettier#5615]
In files with long import lists, it can be hard to spot at a glance where the "actual code" (as in statements) begins. This gets a lot harder if there is no empty line separating the import declarations from the statements, in particular if there are empty lines between groups of imports and then suddenly the first statement is placed below an import without an empty line in between.

I've also seen some tools perform auto imports by inserting import declarations into the empty line that comes right after the other imports and right before the statements, requiring manual user intervention to re-add the empty line, if its absence is noticed at all.
On the other hand, I've never seen the empty line between imports and statements intentionally being left out, so I suggest Prettier enforcing the presence of an empty line between import declarations and statements.

I realize this might be controversial, especially because to my knowledge there is no case where Prettier by itself inserts an empty line yet, but I couldn't find an issue where something like this has been discussed before, so perhaps it's worth considering.

As far as I know, ES allows module declarations (imports / exports) interleaved with statements in any arbitrary order, so this would have to be implemented for the general case, e.g. by placing an empty line between any two program children if one is a module declaration and the other a statement.

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgA98AzHCdfAcgDoB6QqgbgB0o2Ns98BPU8yrTo9mbQgAoAlExAAaEBEwxU0AM7JQAQxzkA7gAVtCdSk0A3CKgAmckACMcmsAGs4MAMqYnqKAHNkMDgArnDyABYw6AA2AOphqPCqXmBw7sYJqGYJPMjgquryPqpwePqOvuiayCSaUcXyAFaqhABCji5u7procAAyPnDVtfUgTYTuPr5RcACKQRDwQ3WhIF44xTi5dpp2PFHQtpg4PjAx1jBhyAAcAAzyRxDFMY6YuUdwG2aD8jhwAI5BVC-MqaCpVJA1ZbyYroVABYIrVSTaZzBaDCHDFYwHZnKwXZAAJnkgU0qCikwAwhRKrkoNBviAgsUACo7EyQ4oAX05QA)
```sh
--parser babylon
```

**Input:**
```jsx
import x from './x';

import y from './y';
x();
```

**Output:**
```jsx
import x from "./x";

import y from "./y";

x();

```

**Comment by lydell** [comment]
Thanks for the well-written issue! Should this be part of #3597?

**Comment by jeysal** [comment]
You're right! I must have missed that one because I searched for "empty line", not "blank line"

**Comment by lydell** [comment]
Ok, let's keep the discussion in #3597 then.
