### ISSUE TITLE
Angular parser strips single quotes from ngClass

### ISSUE THREAD

**Issue by artemzakharov** [prettier/prettier#5618]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIDaUA5gMIA2AhgM5UC6AvADojC4DkAHm0rgJ64BfZgD5UAeizZhIADQgIABxiZoVZKAoAnTRADuABS0I1KCtgiZ0skACNNFMAGs4MAMoKHmYshiaArnByABYwALZkAOpBmPBUHmBwrsYxODG8yOA01l5UcJow+vZEoRTIAGYUZLlyAFZUHABC9k4urhShcAAyXnDlldUgdRyuXkRkcACKfhDwfVWBIB6auZoZFMR+lKtyCppeMBGWMEHIABwADDs6uRH2Chm7cCvYvXKacACOfpjvhRTFpSQFXmclyoUwPn8Cyoo3GUxmvSB-QWMAoNkO6GOyAATHJfBRMGRRiQIKEShkoNBXiA-LkACpokzA3ICARAA)
```sh
--parser angular
```

**Input:**
```html
<div [ngClass]="{ 'x': y }"></div>
```

**Output:**
```html
<div [ngClass]="{ x: y }"></div>

```

**Expected behavior:**
The single quotations around the `x` should not be stripped out.

**Comment by hawkrives** [comment]
Does this break your app? Or is it just a formatting preference?

**Comment by artemzakharov** [comment]
It actually surprisingly doesn't, but this seems to be undocumented behavior - every example on Angular's official page that follows the `[ngClass]="{ ... }"` format uses the single quotations:

```
<some-element [ngClass]="'first second'">...</some-element>

<some-element [ngClass]="['first', 'second']">...</some-element>

<some-element [ngClass]="{'first': true, 'second': true, 'third': false}">...</some-element>

<some-element [ngClass]="stringExp|arrayExp|objExp">...</some-element>

<some-element [ngClass]="{'class1 class2 class3' : true}">...</some-element>
```

My playground code follows example 3, which you can see is supposed to have quotation marks around the class name. 

I did some more experimentation, and it seems like the formatter only strips the quotations when the class name is a single word - code like `[ngClass]="{ 'a-b-c': x }"`, for example, does _not_ lose the quotations, which I'm not sure is intentional or not since in that case stripping the quotations DOES break the app. Even if it is intentional, however, I think it creates confusing code - I imagine that this is the reason why the examples use quotes for ALL classes, not just ones that include two or more words separated by dashes.

**Comment by artemzakharov** [comment]
Good catch! That would explain the otherwise odd behavior - why something like `'abc'` would lose the single quotes, while `'a-b-c'` or `'a b c'` or something similar would not. That also explains why I couldn't find a case where it actually DID break the app, as I guess it is explicitly a JS expression. 

With that said, I still think it should leave quotations alone - since the keys being passed are supposed to be CSS classes, where the convention is kebab-case (which DOES require quotations), I think it would make sense for it to naturally assume that the key requires quotations, and don't check for whether they could be removed. I'm not sure how much work this would take to implement, but I know for a fact that Prettier only very recently started doing this, so perhaps it wouldn't take that much to see where the change happened?

**Comment by j-f1** [comment]
The change happened because we started formatting Angular files only recently.

**Comment by duailibe** [comment]
> I still think it should leave quotations alone - since the keys being passed are supposed to be CSS classes, where the convention is kebab-case (which DOES require quotations when there are multiple words, which happens very very often with CSS classes), I think it would make sense for it to naturally assume that the key requires quotations, and don't check for whether they could be removed

@artemzakharov I don't understand.. are you worried that Prettier might break the code or is it just stylistic preference?

**Comment by brodybits** [comment]
> > since the keys being passed are supposed to be CSS classes, where the convention is kebab-case (which DOES require quotations when there are multiple words, which happens very very often with CSS classes), I think it would make sense for it to naturally assume that the key requires quotations, and don't check for whether they could be removed
> 
> @artemzakharov I don't understand.. are you worried that Prettier might break the code or is it just stylistic preference?

I think @artemzakharov wanted to bring up a point of consistency, which could be considered a styling preference. He did say the following in the same comment (<https://github.com/prettier/prettier/issues/5618#issuecomment-455207536>) to imply that he didn't see Prettier breaking behavior of code in this case:

> That also explains why I couldn't find a case where it actually DID break the app, as I guess it is explicitly a JS expression.

"That" refers to <https://github.com/prettier/prettier/issues/5618#issuecomment-445692066>:

> Honestly, it looks like [ngClass] just takes a JS expression, in which case it follows the same rules as normal JS for when to quote object keys [...]

**Comment by artemzakharov** [comment]
@duailibe No, I am not worried that it will break the app - I am worried that it will lead to what some (including myself) would consider inconsistent styling, where someone who isn't familiar with the otherwise somewhat obscure rules regarding multiple, dash separated word variable names in JS would be confused at why some ngClass examples get stripped of quotes, and others don't. This is further amplified by the fact that while the parser strips quotes when they aren't needed, it doesn't add them where they *are* needed, creating further confusion for someone who might modify a single word class into a multi word one, and suddenly run into a compilation error. 

At the end of the day, I'm just worried that newbies are going to get confused, but its possible that I'm worrying too much, so it would help if any other Angular devs could give their thoughts.

**Comment by duailibe** [comment]
Thanks for explaining.

Seems reasonable to me to always add quotes there.

**Comment by bojanbass** [comment]
It looks like this bug is present only when template file has `.component.html` suffix. In all other cases single quotes are NOT stripped.

**Comment by sander1095** [comment]
Any updates? This causes our app to start working since we depend on the `' '`  to be there.

**Comment by thorn0** [comment]
The `--quote-props preserve` option can be used since Prettier 1.17.0 to preserve quotes in expressions.
