### ISSUE TITLE
[Conditional Operator] How to wrap only when some situations?

### ISSUE THREAD

**Issue by NE-SmallTown** [prettier/prettier#5619]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCb4AUAlPsADpTsyRQDOMfLzo5c0AIz4AvPnEBuTvnzdeAodBFioAJmn5tCqEpXQ1w0XigBmPVcPGjynqcHU4fdCRiSZ5rZIB+fBskfAByVAgIMPsnVVd3TxhdXw0LCXwgxj9LXQAyPPUoTUsbAuDWUIiomM4AXxAAGhAIAActPmRQAENqaggAdwAFXoROlG6ANwgcOiaQACNqbrAAazgYAGVWlZwoAHNkGGp0OGaACxgAWxIKc9F3HbA4TbGLSdEAT2RwPk7mvZ8ODUGBDZb7K7dZCobokIHNABWfAAHgAhZZrDabbpXOAAGT2cGhsPhICRyM2e32JDgAEV0BB4MS4WcQDtqEDqD8Ft0Fp9yFB5q1qHsYBRZjBzsgABwABmawogQIoy1aP2F7mBkyJzTcAEd0Dg3GDuhCoUgYSzmkCrjgjidWXwqTT6YyiRaSayYLzxXRJchtM1jt0cCQqQBhCBXSE-KDQHUgdBAgAqvPGlqBdTqQA)
```sh
--parser babylon
```

**Input:**
```jsx
function HelloWorld () {
  const condition1 = 1;
  const condition2 = 2;
  const condition3 = 3;
  
  const result1 = condition1 ? 3 : 'foo';
  const result2 = condition1 ? (condition2 && condition3 && 3) : 'foo';
}
```

**Output:**
```jsx
function HelloWorld() {
  const condition1 = 1;
  const condition2 = 2;
  const condition3 = 3;

  const result1 = condition1 ? 3 : "foo";
  const result2 = condition1 ? condition2 && condition3 && 3 : "foo";
}

```

**Expected behavior:**
```js
function HelloWorld() {
  const condition1 = 1;
  const condition2 = 2;
  const condition3 = 3;

  const result1 = condition1 ? 3 : "foo";
  const result2 = condition1 
                  ? condition2 && condition3 && 3 
                  : "foo";
}
```

I want the Conditional Operator **only** wrap when the condition is complex(i.e. not just a primitive value), is there any option could do this? Thanks.

**Comment by lydell** [comment]
Here's a way to do it:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCb4AUAlPsADpT76RQDOMHtDo5c0AIz4AvPnEBuTt14ChUEWKgAmafk0Kuqlb3V4oAZh1n93RfgD0d-AAdqcGLjjUAtDgDmUGjhbZUFXPnQSGEkZY1FTSQB+fAskfAByAEN8ADdPAE98cihffAFqHGL8GAALDMEwDPQ+OCrqlvhqKAzqApgIfAB3agynNOtDULhwyO0Y4TiJfATbblX7R0gAW02EQRq6-FQaMCn8LKGRlbWmWI1tADJ71RNoC0fk1lS0o4gxzgBfEAAGhAECcGj4yFA3WoEAGAAVughISgMtkIDg6MCQAAjYZgADWbgAyk4MmAKr5kDBqOg4CDqjBNiQKNVRFMySdici4tlRHlkOA+JCQRVmtQYPDhr5NhlkKgMiRmiCAFZ8AAeACF8USYMSMjsADIVODyxXKkBq9XEykkOAARXQEHgZqV9JAZOo4sFOIyOLyRWxLgqMAomJqyAAHAAGEEuCDNCjDJyClxTTy5bGuACO6BwrilGRlcqQCrdIOamxw1Np7r4todTpdpfN7pgfrDdAjSE0IJpGRwJEpAGEINsSyAAlBTSCmnAACp+lFl5r-f5AA)
```sh
--parser babylon
```

**Input:**
```jsx
function HelloWorld () {
  const condition1 = 1;
  const condition2 = 2;
  const condition3 = 3;
  
  // prettier-ignore
  const result1 = condition1 ? 3 : 'a very long string that cause the ternary to wrap';
  const result2 = condition1 ?
        // comment that forces a wrap
        (condition2 && condition3 && 3) : 'foo';
}
```

**Output:**
```jsx
function HelloWorld() {
  const condition1 = 1;
  const condition2 = 2;
  const condition3 = 3;

  // prettier-ignore
  const result1 = condition1 ? 3 : 'a very long string that cause the ternary to wrap';
  const result2 = condition1
    ? // comment that forces a wrap
      condition2 && condition3 && 3
    : "foo";
}

```

But the real answer is that if you think about how you want your lines to be wrapped, you're not really using Prettier like it's supposed to be used. The idea with Prettier is that you free your mind of all code formatting, and only focus on the program logic, leaving formatting to Prettier.

**Comment by NE-SmallTown** [comment]
Yea, add a comment or just write the condition on a new line and then the formatting works like I want, but that's seems a little redundant. But thanks for your clarification, I know the idea of prettier now
