### ISSUE TITLE
markdown: plain object in js code block causing a throw error

### ISSUE THREAD

**Issue by revelt** [prettier/prettier#5621]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB1AlgG0wAgEYBOcAhgNY7Q4DOckUAJjpulHEgDpScAGvAVlU7BOOHAHcAFunjMqMJDgDaAXQA0OAPQacAMwgEccAB7EAtgAdMcdYvYgAdGEzEqVALQBGO+rsBidPSe3jh29qYQ9ACuVm4AVHbKIvjEYKQI9Aoq6lq6+oYmFlY2wDgSJPRUCnbAwiDqMMRYlSEgAL6tdjit6iVlxBVVIMAApMENTYPDHSBdiVCikQDmzDoAngo6xJg0qklE4QBucAASACoAsgAyAMIQpqYIMM0wBJHWSfQQAHIQMABKcEOJwuNzuD1gVFQEggNAA8uYECxFqdiItbrBGlBmrYQIp0DpgnZFOl8QlOB0oLxuJw6iAIOYYOhoFRkKBiAQCBAxAAFdkIFkoYgHCABWmEFJpGAAZXMKSRyBeb1UIAkMFMmCh0jgVFlYDgUv50nQB2kq2Q4FctJYNAIMG5BFRpmIyE222sIAERgAQg7UnBpWY4JcWHAXVsdh6qEYpUirABFSK-UNIV0R2UEG3mp0EUifMRQWnmAgsGAYegwCTIAAcAAZlUWYXBUA7zOai9q4AQjrSiABHSLoIj2x3OlPh900UzoBWvCexuAJpNht3Khp4MsV5AAJlXDqwSNu91HICg0FDysiNBReAFqbg7SAA)
```sh
--parser markdown
```

**Input:**
````markdown
Will break on second line:

```js
{
  whitelist: [], // for example, [".class-1", "#id-1", ".module-*"]
  backend: [], // for example, [{ heads: "{{", tails: "}}" }, { heads: "{%", tails: "%}" }]
  uglify: false,
  removeHTMLComments: true,
  doNotRemoveHTMLCommentsWhoseOpeningTagContains: ["[if", "[endif"]
}
```

````

In real life, it's [markdown file](https://bitbucket.org/codsen/email-remove-unused-css/src/master/README.md) with code block set to "js", and minimal sample is:

```js
{
  a: [], // for example, [".a"]
  b: []
}
```

**Output:**
```markdown
SyntaxError: Unexpected token, expected ";" (3:10)
  1 | {
  2 |   whitelist: [], // for example, [".class-1", "#id-1", ".module-*"]
> 3 |   backend: [], // for example, [{ heads: "{{", tails: "}}" }, { heads: "{%", tails: "%}" }]
    |          ^
  4 |   uglify: false,
  5 |   removeHTMLComments: true,
  6 |   doNotRemoveHTMLCommentsWhoseOpeningTagContains: ["[if", "[endif"]
```

**Expected behavior:**
Playground above is showing a different error message from the real life because in real life it's a markdown file with JS code block, but code is coming from the same place:

<img width="1279" alt="error_in_use" src="https://user-images.githubusercontent.com/8344688/49730745-3a096b80-fc71-11e8-8d40-de6b43186e54.png">

OK, this is technically not valid JavaScript piece, a plain object is not assigned to anything, but I was trying to describe am options' plain object in my readme. It is still not acceptable that markdown parser should throw an error. Instead, it should gracefully skip the code block, for example:

```js
{
  a: [], // for example, [".a"]
  b: []
}
```

I did some research and the error:

```
readme.md: SyntaxError: Invalid regular expression: /^\s{0,3}**/: Nothing to repeat
```

is coming from https://github.com/prettier/prettier/blob/952bc0cc039c034c5fe651864db528dcd9800e9e/src/language-markdown/utils.js#L149

where new regex is created in `new RegExp(`^\\s{0,${leadingSpaceCount}}`);`

Now, maybe we can do something to validate the `leadingSpaceCount` before using it in the regex? @ikatyang what do you think?

**Comment by j-f1** [comment]
Here’s a solution for you:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB1AlgG0wAgEYBOcAhgNY7Q4DOckUAJjpulHEgDpScAGvAVlWgBWTsE44cAdwAW6eMyowkOANoBdADQ4A9NpwAzCARxwAHsQC2AB0xwtK9iAB0YTMSpUAtAEZHWxwDE6PQ+fjiOThYQ9ACutp4AVI5q4vjEYKQI9MrqWroGRibm1rb2wDjSJPRUyo7AYiBaMMRYNeEgAL4djjgdWuWVxNW1IMAApGHNrSNj3SC9KVASMQDmzPoAnsr6xJg0GqlEUQBucAASACoAsgAyAMIQFhYIMG0wBDF2qfQQAHIQMAASnATudrvdHs9YFRUNIIDQAPJWBAsFYXYgrB6wFpQNoOEAqdD6MKOFRZInJTjdKC8bicRogCBWGDoaBUZCgYgEAgQSQABS5CHZKGIxwgwQZhHSmRgAGUrOlUch3p8NCBpDALJhYXI4FQFWA4LKhXJ0Mc5BtkOAPAyWDQCDA+QQMRZiMgdns7CABKYAELOjJwOWWOA3Fhwd27fbeqimWWo2wARRiAIjSA90YVBHtVtdBFIP0kUAZVgILBgGHoMGkyAAHAAGNWl+FwVDOqxW0t6uAEU4MogARxi6CITpdbvTUa9NAs6GVH2nCbgydTkc9auaeEr1eQACYN86sKiHk8JyAoNAI2qYjR0XhhRm4F0gA)
```sh
--parser markdown
```

**Input:**
````markdown
Will break on second line:

```json5
{
  whitelist: [], // for example, [".class-1", "#id-1", ".module-*"]
  backend: [], // for example, [{ heads: "{{", tails: "}}" }, { heads: "{%", tails: "%}" }]
  uglify: false,
  removeHTMLComments: true,
  doNotRemoveHTMLCommentsWhoseOpeningTagContains: ["[if", "[endif"]
}
```

````

**Output:**
````markdown
Will break on second line:

```json5
{
  whitelist: [], // for example, [".class-1", "#id-1", ".module-*"]
  backend: [], // for example, [{ heads: "{{", tails: "}}" }, { heads: "{%", tails: "%}" }]
  uglify: false,
  removeHTMLComments: true,
  doNotRemoveHTMLCommentsWhoseOpeningTagContains: ["[if", "[endif"]
}
```

````

**Comment by revelt** [comment]
Nice! Thank you for fix and quick reply.

Jed, do you think https://github.com/prettier/prettier/blob/952bc0cc039c034c5fe651864db528dcd9800e9e/src/language-markdown/utils.js#L149 is worth improving for posterity or this can be closed?

**Comment by ikatyang** [comment]
I guess it probably comes from here:

https://github.com/prettier/prettier/blob/952bc0cc039c034c5fe651864db528dcd9800e9e/src/language-markdown/utils.js#L160

The `marker` is supposed to be `` ` `` or `~` but I'm not sure where does the `**` come from, and I cannot reproduce the issue locally. Can you share more info?

**Comment by j-f1** [comment]
Would it be possible to share the entire `readme.md`?

**Comment by revelt** [comment]
hi guys!

Definitely. So, readme in question is this:
https://bitbucket.org/codsen/email-remove-unused-css/src/master/README.md

right now, you can recreate the bug by cloning and:

```
npx prettier readme.md --write
```

**Comment by j-f1** [comment]
What does `npx prettier --version` output for you?

**Comment by ikatyang** [comment]
I'm still not able to reproduce the issue, here's how I tried:

```sh
mkdir prettier-5621
cd prettier-5621
yarn init -y
yarn add prettier
curl -O https://bitbucket.org/codsen/email-remove-unused-css/raw/525d7a7dc47d94a5db829a502cf1211d2d5d1bd7/README.md
yarn prettier README.md
```

**Comment by revelt** [comment]
@j-f1 `1.15.3`
@ikatyang oh, I used npm, not yarn!

**Comment by revelt** [comment]
basically, you don't need to have a global `prettier`, the `npx` will fetch the latest and run it. Although it's proprietary `npm` command.

**Comment by ikatyang** [comment]
It's still not reproducible using `npx`:

```sh
curl https://bitbucket.org/codsen/email-remove-unused-css/raw/525d7a7dc47d94a5db829a502cf1211d2d5d1bd7/README.md | npx prettier --parser markdown
```

(There's actually no difference between yarn and npm in this case, prettier has 0 dependency.)

And also I tried to clone it and run `npx prettier readme.md --write` but there's no error thrown.

**Comment by ikatyang** [comment]
> The second also excludes file type clashing.

I thought it could reproduce the issue https://github.com/prettier/prettier/issues/5621#issuecomment-445819558.

> Here's package.json npm script "format"...

I modified the `format` script in `package.json` and run `npm run format`, but still:

![image](https://user-images.githubusercontent.com/8341033/49787673-44eff900-fd62-11e8-90c8-e7d773513bf7.png)

Can you share a shell script (something like https://github.com/prettier/prettier/issues/5621#issuecomment-445822994) that I can simply copy-paste and reproduce the issue?

**Comment by revelt** [comment]
If you can't recreate it it must be something with my machine then, at least we looked at it. Thank you for all your help, I'll close.
