### ISSUE TITLE
Using a ternary symbol will format  error when the parameter being evaluated is an html structure

### ISSUE THREAD

**Issue by khukeke** [prettier/prettier#5622]
input：

````javascript
const EditableCell = ({editable, value, isDefault, onChange}) => {
    return <div>
        {editable
            ? <Select defaultValue={value + ''} onChange={onChange}>
                <Option value='0'>ok</Option>
                <Option value='1'>false</Option>
            </Select>
            : <span className={isDefault ? '' : 'colorYellow'}>{value ? 'ok' : 'false'}</span>
        }
    </div>;
};
````

output： 

````javascript
const EditableCell = ({editable, value, isDefault, onChange}) => {
    return (
        <div>
            {editable ? (
                <Select defaultValue={value + ''} onChange={onChange}>
                    <Option value='0'>ok</Option>
                    <Option value='1'>false</Option>
                </Select>
            ) : (
                <span className={isDefault ? '' : 'colorYellow'}>
                    {value ? 'ok' : 'false'}
                </span>
            )}
        </div>
    );
};
````

expect input.
ps: I can't change config to output type,because when i push my code , my comany has it's own Code verification rule .so i can't push my code to git successfully.
i found ternary symbol formatter sometimes is good.but when  parameter is html structure it will be wrong.

[demo here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBRAJgSxgEMAjAGzgGU4KwYBhGszAXkwApg4Djy4AaTADciZAK4DM+NABE4AMyJiyMQdHoALIlADmcAL4BKVgD5MwADpRMNzACc4MMXesAeAkJNXbP890KkFN6+IQD8mK7UtFi4CkoqAGqiEizAIuJwmADUmADkufqY6lq6cKnF2nr6XtYhdTauAPIADjD40MLJZbkADLkmgLBygOZGgDIRrgD0LW3QNfX1Ta3t1ukpuQCM-aMTU0uzcw3jUXB0e-tIEWjN2phgZERoaAByRAC2ZcDScorKWOH5mOdcpAyBA7ABNJgQADuBRMaS6mD+o1yALywxGBQml20p18+mCBw8JgA3FZ9MSQPwQBBFuhkKAiHY7NCAAqMhBoZAgIhCCD4XCUkAkOxEMAAa0clCuYHwumQMDsEipGhgLzIAHUNIQ4NiwFQOYR8EJCABPLlgB6C2VoOB2GAskU6F5EZCKMg2qkAKzQAA8AEIi8WS15wAAysrgrtEHpA3p9lFlOgoAEUxBB4FH3QIQFc7Da7FySKQTSCoILmnZZTB1fyYBpkAAOHpUisQG3qkXNLkVnW2oSRqkOACOYnwDgdRCdLqQbpjNpe+HliuzaETKbTGZn0ezvBruDryAALFSFUR8GRE-QIC9nVyoNAByAxDaACqkTlbrP6fRAA)

**Comment by j-f1** [comment]
Quoting @lydell:

> The "extra" parens were requested in #2208 and added in #2398 (and has since then received a couple of tweaks as well). There's also this similar issue: #3001
> 
> The formatting for this has already been decided, and is not going to change at this point. I also thought it looked weird at first, but quickly got used to it. These days I even prefer it!

I’d suggest talking to your company to see if they’d be willing to use Prettier to verify code formatting.
