### ISSUE TITLE
`html` in `.ts/.tsx` is not formatted

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#5623]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALGBbAG0wF5MB6AKkwAkAVAWQBlMKzMADAHgEIARAeQDCtAJoAFAKI58BAHwAdKJzpNMgxgEEAyluLyQUCAFoAVmkx4RRwQQ1ot+hVEyZlEjbycuXnehNoaatQaAEpa-nogAK4wAGZGAByOit6utACStIwSsvQAnpgwmQQSnGQZWTkp3r7+gQByGn6RACZwaGAATgCWAA4w3dD6mJCwCDCR+WoQ9TASULTJzq5k1O6e1ZwARhAteV41YrLUcAQEEJgA7hCdBC3cnABCIbKYtNjd5p80DIwArJhHhBugQ4J1egQAIbwAB0ZSO1R8WkEIXSYloB1Sl26UBaEEuMIA5pCSJhYlEoGABtBMAAKACUmGAmGJMIAjjDelE0NhaZDOoSonhxmhGQBfADcLMh7NJAG0ALpS1lEUgAaigcEumF40LgEsR3mJtIA5F04HqTQAaTAmgCqGiMAA0XS6jCJrbbITEICb6crIaa0AgWp6Tb1IYS4AA3bpav2GsodHr9TGuZGo9GYNCdMCRXAwXpoJBkMiXctEiAQQmgoyQqCQgh5AZgNAwyB4Mj1xvN7qtmFmYbaET1QQ6iQAMQkLyTXT6MAOZR2eycZRUjFk7BAVpAEH6gygaGQoH5nXxYn5CCPKEh0eBLW3IC2nUhYAA1nAYFoI2AcYTkDAnRRHAO64IQADqHzwGgP5wFoV7dAMsYwHkyDgGgR47jiwadDAYgvoSeCQsgsSNsGO5mAAHo8L7vp+WiQsKjA4nAJFkSBIBUVof6ggAilEEDwGxBDkSAEadDhaEob07Rzv0j69D0sDgd0LQwNgyAJAADDuikQMG4Evr0aGKe0YLRqxO6dHAbJRN01n4ZGRHCaJwZ4N0AFARxaA8XA-GCaxSCkSJHEwJCWwqWpGlIAATDugGQiCf6CBAeDOSghiao+3JwLQ4XXsFwZimKQA)
```sh
--parser typescript
```

**Input:**
```tsx
const html = /* HTML */ `<!DOCTYPE html>
<HTML CLASS="no-js mY-ClAsS">
  <HEAD>
    <META CHARSET="utf-8">
    <TITLE>My tITlE</TITLE>
    <META NAME="description" content="My CoNtEnT">
  </HEAD>
  <body>
    <P>Hello world!<BR> This is HTML5 Boilerplate.</P>
    <SCRIPT>
      window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
      ga('create', 'UA-XXXXX-Y', 'auto'); ga('send', 'pageview')
    </script>
    <SCRIPT src="https://www.google-analytics.com/analytics.js" ASYNC DEFER></script>
  </body>
</HTML>`
```

**Output:**
```tsx
const html = /* HTML */ `<!DOCTYPE html>
<HTML CLASS="no-js mY-ClAsS">
  <HEAD>
    <META CHARSET="utf-8">
    <TITLE>My tITlE</TITLE>
    <META NAME="description" content="My CoNtEnT">
  </HEAD>
  <body>
    <P>Hello world!<BR> This is HTML5 Boilerplate.</P>
    <SCRIPT>
      window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
      ga('create', 'UA-XXXXX-Y', 'auto'); ga('send', 'pageview')
    </script>
    <SCRIPT src="https://www.google-analytics.com/analytics.js" ASYNC DEFER></script>
  </body>
</HTML>`;

```

**Expected behavior:**
format html correctly like [JavaScript](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALGBbAG0wF5MB6AKkwAkAVAWQBlMKzMADAHgEIARAeQDCtAJoAFAKI58BAHwAdKJzpNMgxgEEAyluLyQUCAFoAVmkx4RRwQQ1ot+hVEyZlEjbycuXnehNoaatQaAEpa-nogAK4wAGZGAByOit6utACStIwSsvQAnpgwmQQSnGQZWTkp3r7+gQByGn6RACZwaGAATgCWAA4w3dD6mJCwCDCR+WoQ9TASULTJzq5k1O6e1ZwARhAteV41YrLUcAQEEJgA7hCdBC3cnABCIbKYtNjd5p80DIwArJhHhBugQ4J1egQAIbwAB0ZSO1R8WkEIXSYloB1Sl26UBaEEuMIA5pCSJhYlEoGABtBMAAKACUmGAmGJMIAjjDelE0NhaZDOoSonhxmhGQBfADcLMh7NJAG0ALpS1lEUgAaigcEumF40LgEsR3mJtIA5F04HqTQAaTAmgCqGiMAA0XS6jCJrbbITEICb6crIaa0AgWp6Tb1IYS4AA3bpav2GsodHr9TGuZGo9GYNCdMCRXAwXpoJBkMiXctEiAQQmgoyQqCQgh5AZgNAwyB4Mj1xvN7qtmFmYbaET1QQ6iQAMQkLyTXT6MAOZR2eycZRUjFk7BAVpAEH6gygaGQoH5nXxYn5CCPKEh0eBLW3IC2nUhYAA1nAYFoI2AcYTkDAnRRHAO64IQADqHzwGgP5wFoV7dAMsYwHkyDgGgR47jiwadDAYgvoSeCQsgsSNsGO5mAAHo8L7vp+WiQsKjA4nAJFkSBIBUVof6ggAilEEDwGxBDkSAEadDhaFbJCWx5OcUCPr0PSwOB3QtDA2DIAkAAMO5KRAwbgS+vRoUp7RgtGrE7p0cBslE3Q2fhkZEcJonBng3QAUBHFoDxcD8YJrFIKRIkcTAMmqepmlIAATDugGQiCf6CBAeAuSghiao+3JwLQMnXiFwZimKQA)

**Comment by ikatyang** [comment]
The issue here is that the `/* HTML */` comment is somehow not attached to the template literal.

**Comment by Coder-256** [comment]
This seems to be related to #5588, relevant code: https://github.com/prettier/prettier/blob/6a45924379d919a17b072e38114745053ab808ef/src/language-js/embed.js#L555

**Comment by duailibe** [comment]
Also happens with Flow, i.e. only works with babylon.
