### ISSUE TITLE
Bracket and Brace Together and Keep Multiline

### ISSUE THREAD

**Issue by Domvel** [prettier/prettier#5624]
Hi, 
in my case, prettier formats a typescript code from:

**Input** (wanted)

```ts
this.messageService
  .prompt(this.name, [{
      name: 'value',
      type: 'number'
    }])
```

**Output** (formatted)

```ts
this.messageService
  .prompt(this.name, [
    {
      name: 'value',
      type: 'number'
    }
  ])
```

I expected keep bracket and braces together. (the first one) `[{ ...` not `[\n\t{ ...`
Is there a option for e.g. `.prettierrc`

"prettier": "^1.15.3",

**Comment by Domvel** [comment]
Also another issue. 

**Input**

```ts
constructor(
  protected one: One,
  protected two: Two
) {}
```

**Output**

```ts
constructor(protected one: One, two: Two) {}
```

**Expceted**

Keep multilines. This happend on other places too. Not only contructor.
e.g. arguments in a method. Or multiple operator. like `one && two && three` (the line break after `&&` is removed.)

Is there already a option? If not, this is a feature request.

**Comment by Domvel** [comment]
@hawkrives Why downrate? Do you want arguments in a single line? Especially if you set it as multiline. Prettier should have an option and / or should detect the format single or multiline.

currently: 

```ts
constructor(private one: One, private two: Two, private three: Three, private four: Four, private five: Five ) {}
```

vs wanted:

```ts
constructor(
  private one: One,
  private two: Two,
  private three Three,
  private four: Four,
  private five: Five
) {}
```

**Comment by Domvel** [comment]
@evilebottnawi Ok, this means format style requests are futile. I can not understand this decision. Are there no options? Because both formats are justified. "The community already have chosen the format?" Is this a final decision? Especially with a tight decision, an option makes sense. And in some cases it also makes sense that the formatter recognizes the style. (single / multiline)

Is there a documentation about how Prettier works? e.g. why does Prettier format multiline arguments to a single line and are options available? etc. Or is this only in the source code? Is there a link to the community chosen styles?

Anyway ... my request is only a suggestion. It's completely ok if this is rejected. I just wanted to know the reason in this case. :)

**Comment by evilebottnawi** [comment]
> Are there no options?

https://prettier.io/docs/en/option-philosophy.html

> Because both formats are justified. "The community already have chosen the format?"

Yes

> Is this a final decision?

Maybe, good ideas gets a lot of :+1: 

> Especially with a tight decision, an option makes sense.

https://prettier.io/docs/en/option-philosophy.html and https://prettier.io/docs/en/comparison.html

> Is there a documentation about how Prettier works? e.g. why does Prettier format multiline arguments to a single line and are options available? etc. Or is this only in the source code? Is there a link to the community chosen styles?

https://prettier.io/docs/en/technical-details.html

**Comment by Domvel** [comment]
I understand. I do agree the option philosophy. Not with all formats. But this is Prettier.

Conclusion:
Options are generally forbidden. Prettier format style should be unified but the community can vote for changes.

In my case: 

This (I prefer, compact)

```js
[{
  one: 1
}, {
  two: 2
}, {
  three: 3
}]
```

vs Prettier (More flexible, easier to add / remove objects.)

```js
[
  {
    one: 1
  },
  {
    two: 2
  }, 
  {
    three: 3
  }
]
```

Right? It's ok. I can live this that. 😄

**Comment by evilebottnawi** [comment]
@Domvel right, no options - no problems :smile:
