### ISSUE TITLE
Typescript: no-inferrable-types

### ISSUE THREAD

**Issue by Domvel** [prettier/prettier#5625]
Is there a option to handle `no-inferrable-types` (tslint.json). I know the formatter does not read linter settings. But I wondering if this is already possible. Otherwise maybe a good new feature? 

Example `no-inferrable-types`:

```ts
let foo: string = 'bar';
```

to

```ts
let foo = 'bar';
```

btw. what you think about a option to read linter files? It's very complex, isn't?

"prettier": "^1.15.3"

**Comment by j-f1** [comment]
I don’t think we should do this. Prettier tries to format whatever you give it without changing your code’s meaning. Please use a linter instead to make code changes like this.
