### ISSUE TITLE
Is it possible to disable bracketSpacing option somehow?

### ISSUE THREAD

**Issue by alexicum** [prettier/prettier#5634]
If set bracketSpacing to true (or not set it at all) prettier insert spaces,
but if set to false, then it removes existing brackets.

Is it possible to switch it off completely: so it will do nothing in this case?

**Comment by j-f1** [comment]
This isn’t possible. Prettier has to re-print your entire file so it has to make a decision for every case. Leaving this aliene by checking your source code would make Prettier’s output inconsistent. Do you have a specific reason you need this functionality?

**Comment by alexicum** [comment]
```
[debug] normalized argv: {"_":["api/**/*.ts*"],"color":true,"editorconfig":false,"write":true,"config":"./scripts/autoformat/set-indent/prettier.config.js","loglevel":"debug","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] load config file from './scripts/autoformat/set-indent/prettier.config.js'
[debug] loaded options `{"tabWidth":2,"useTabs":false,"proseWrap":"preserve"}`
[debug] applied config-precedence (cli-override): {"proseWrap":"preserve","tabWidth":2,"useTabs":false}
api/BaseRequest.ts 238ms
```

There is no 
"bracketSpacing":false
or
"bracketSpacing":true

but it is still working like when = true

**Comment by j-f1** [comment]
That’s because we have a default value for that option. Do you have a reason you want the input format preserved?

**Comment by alexicum** [comment]
The reason: I need to convert huge code base from four spaces indent to two spaces.
And it whould be greate to avoid other format changes.

Git clients has a feature to not show the difference when only leading or trailing spaces changed.

At second step I will configure other formatting rules and my team could test and decide what to use.

**Comment by j-f1** [comment]
I’d recommend using a different tool than Prettier for that first change. Perhaps try ESLint’s `indent` rule instead?

**Comment by alexicum** [comment]
I'm using TypeScript and after some research found, that for now neither tslint no eslint (with *typescript-eslint-parser*) could --fix simple indent rule, here is discussion:

https://github.com/palantir/tslint/issues/2814

tslint **ter-indent** rule works with hack.

**Test case**: convert indentation from 4 to 2 spaces.

**tslint.js**
```
const path = require("path");
module.exports = {
  rulesDirectory: [path.join(path.dirname(require.resolve("tslint-eslint-rules")), "dist/rules")],
  rules: {
    "ter-indent": [true, 2, { SwitchCase: 1 }]
  }
}; 
```

**test.ts**
```
interface MyInterface {
    foo(): string;
    bar: Array<number>;
}

export abstract class Foo implements MyInterface {
    foo() {
        // TODO: return an actual value here
        return "hello";
    }
    get bar() {
        return [1, 2, 3];
    }
}
```
Сommand to run tslint:
"node_modules/.bin/tslint" --config ./scripts/autoformat/set-indent/tslint.js --fix "src/test.ts"

Result: 
1st attempt: Fixed 6 error(s) in src/test.ts
2nd attempt: Fixed 4 error(s) in src/test.ts
3rd attempt: (no output)

So tslint with ter-indent rule should be executed several times to get result, but take into account that comments are not aligned correctly

Here is final result:

```
interface MyInterface {
  foo(): string;
  bar: Array<number>;
}

export abstract class Foo implements MyInterface {
  foo() {
        // TODO: return an actual value here
    return "hello";
  }
  get bar() {
    return [1, 2, 3];
  }
}
```

Prettier doing same job well, but it has some predefined options and there is no ability to disable them.

@j-f1 If you could update some options to have "preserve" mode - it would be great, as soon as eslint (tslint) still could not indent well.

**Comment by j-f1** [comment]
@alexicum I don’t think we’re going to add a preserve mode. I just thought of an alternative: what if you enabled Prettier and set `tabWidth` to 4 first, then changed the `tabWidth` setting later?

**Comment by alexicum** [comment]
@j-f1 unfortunatly It is not possible to enable Prettier now, because:
`import { foo } from 'bar';`
whould be converted to:
`import {foo} from 'bar';`

even if I will not include "bracketSpacing" rule.
