### ISSUE TITLE
Extra Backticks and 4 backticks getting added

### ISSUE THREAD

**Issue by anishmittal2020** [prettier/prettier#5640]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAOQgdwDTpgBOcAhvOqegGYCWANnIafYwCboAGAtgJ4DO9Wmzj8AdNzad0OWjAAW6XhACuRQtHiwx6AJIx03Ur3QQADjFrQW9E7Shh6KkZXQBNAIIBZADI0imobk8OrUEOqWMIwEpCoK4TFQHGzkcEgAOlCZ6FycPKREANZsuFlQOaiV2ZRx8uFI6ABSEPLlACIQcNWRjA1tcNwQ6ADKQiLVKfANjSpQTABMAIwE8wAMiwDs1ZWomdUAxOgAYhAQe+U5uZxmvPFll+hmRPYwABTpIPJwrEM44fRsD4ASmqOTynHOOUOACECpD0Bh4PwYNt0EiURdwSA8CBzJZoPxkKACgEcAAFAoIQkoUgANwgwmxIAARkRSGBCnAYMMzOz7ABzZAwIgqOA4+Qwbj0ADq8jkol5YDgwypclotLkvGQ4H4hJx9n4cCIMDJbP5RmQ1BYhpxACt+AAPaFsjlc4akbhwHz2OCW61ikD2h3DAWMACKKgg8D99BtIF5RENRG1RiKJRwUCZTxe0uECmQAA5VjinhBDdK2WZtU9REbab6cSQAI4qWgkU2kc2kGNxw3cWhCkUB-ihuARqO+pBW2MBmCkZm5tj5pDzHHC0gMAUAYQg3AtKCg0AbIBUhoAKvPqdPDQBfG9AA)
```sh
--parser markdown
```

**Input:**
````markdown
- Now, create a file called `myslides.md` with your content. It may optionally include a YAML front matter for title, author, and date:

  ```markdown
  ---
  author: John Doe
  title: Demo Slide
  date: June 21, 2017
  ---

  # Foo

    ```python
    print("hello world")
    ```

  # Bar

  - test
  - test
  ```
````

**Output:**
`````markdown
- Now, create a file called `myslides.md` with your content. It may optionally include a YAML front matter for title, author, and date:

  ````markdown
  ---
  author: John Doe
  title: Demo Slide
  date: June 21, 2017
  ---

  # Foo

  ```python
  print("hello world")
  ```
  ````

  # Bar

  - test
  - test

  ```

  ```

`````

**Expected behavior:** See input

**Comment by ikatyang** [comment]
The [current behavior matches how CommonMark works](https://spec.commonmark.org/dingus/?text=-%20Now%2C%20create%20a%20file%20called%20%60myslides.md%60%20with%20your%20content.%20It%20may%20optionally%20include%20a%20YAML%20front%20matter%20for%20title%2C%20author%2C%20and%20date%3A%0A%0A%20%20%60%60%60markdown%0A%20%20---%0A%20%20author%3A%20John%20Doe%0A%20%20title%3A%20Demo%20Slide%0A%20%20date%3A%20June%2021%2C%202017%0A%20%20---%0A%0A%20%20%23%20Foo%0A%0A%20%20%20%20%60%60%60python%0A%20%20%20%20print(%22hello%20world%22)%0A%20%20%20%20%60%60%60%0A%0A%20%20%23%20Bar%0A%0A%20%20-%20test%0A%20%20-%20test%0A%20%20%60%60%60), you should use 4 backticks if there're backtick fenced code blocks in it:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAOQgdwDTpgBOcAhvOqegGYCWANnIafYwCboAGAtgJ4DO9Wmzj8AdNzad0OWjAAW6XhACuRQtHiwx6AJIx03Ur3QQADjFrQW9E7Shh6KkZXQBNAIIBZADI0imobk8OrUEOqWMIwEpCoK4TFQHGzkcEgAOlCZ6FyceUZEANZsuFlQOaiV2ZRx8uFI6ABSEPLlACIQcNWRjA1tcNwQ6ADKQiLVKfANjSpQTABMAIwE8wAMiwDs1ZWomdUAxOgAYhAQe+U5uZxmvPFll+hmRPYwABTpIPJwrEM44fRsD4ASmqOTynHOOUOACFSERIegMPB+DBtuhkaiLuDOCA8CBzJZoPxkKA4QEcAAFOEIYkoUgANwgwlxIAARkRSGBCnAYMMzJz7ABzZAwIgqOB4+Qwbj0ADq8jkon5YDgwxpclo9LkvGQ4H4xLx9n4cCIMApHMFRmQ1BYxrxACt+AAPaEcrk84akbhwHz2ODW20SkCOp3DIWMACKKgg8AD9DtIH5RGNRF1BWKpRZTxesuECmQAA5VninhBjbKOWZdU9RCb6f68SQAI4qWgkc2kS2kOMJ43cWgisVB-jhuBRmP+pA2+NBmCkVm5tj5pDzPGi0gMIUAYQg3CtKCg0AbIBUxoAKvPadPjQBfG9AA)
```sh
--parser markdown
```

**Input:**
`````markdown
- Now, create a file called `myslides.md` with your content. It may optionally include a YAML front matter for title, author, and date:

  ````markdown
  ---
  author: John Doe
  title: Demo Slide
  date: June 21, 2017
  ---

  # Foo

    ```python
    print("hello world")
    ```

  # Bar

  - test
  - test
  ````
`````

**Output:**
`````markdown
- Now, create a file called `myslides.md` with your content. It may optionally include a YAML front matter for title, author, and date:

  ````markdown
  ---
  author: John Doe
  title: Demo Slide
  date: June 21, 2017
  ---

  # Foo

  ```python
  print("hello world")
  ```

  # Bar

  - test
  - test
  ````

`````
