### ISSUE TITLE
add dependable collaborators on other repos

### ISSUE THREAD

**Issue by markgoho** [prettier/prettier#5644]
there's been a [PR open for 3 weeks](https://github.com/prettier/prettier-vscode/pull/658) on the prettier/vs-code extension repo 

In the short term is it possible for an owner to approve and merge that?

In the long term, could we add collaborators to that repo so that this doesn't happen again?

**Comment by j-f1** [comment]
Merged, but I’m not sure what the release process is.

**Comment by j-f1** [comment]
Do you know of anyone who’s willing to help maintain that package?

**Comment by markgoho** [comment]
Thank you so much for merging! Yes, the release process would be the next step. Unfortunately it looks like there isn't any documentation on how that works. I'm happy to do some research over the next week on how VS Code extensions are published and try to figure out if there's anything currently in the repo that lines up with what that process looks like.
