### ISSUE TITLE
HTML Angular parser removes necessary parentheses causing early block closing

### ISSUE THREAD

**Issue by nmussy** [prettier/prettier#5648]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpQAQF7DC6Fl4DkAJnADZzwWnksA+eMATgIZQDOtbvCREA7gAshIgBQUEMAJaK4fCnnZdeAoXBHBIAV1gjunHgE8AdPSgBzGOIC+ASkfMCjt1FQB6LCAAaEAh0RWg+ZFBTTghRAAVTBAiUbgA3CAUqQJAAIx4wAGsGAGV0bjAFO2QAM25aPjgg8RgAW1oAdXElFTKwOGKkpQVUpXNkcD4IoMqGzhg4nlsW7hq6hqCAKz4ADwAhfKKYYu4WuAAZSrhV+saQLe3iytt6AEUDCHhr9ZAyzlnx3i2AyCTjZdCcSowdqZBzIAAcAAYguCIA12jx0ONwSo4JxUlcgpw4ABHAwKIkLbhLFZIWo3IINFoKZBcAy3PhPV7vT60ta3GDcHLQqiwpAAJiCmgUtCeAGEIC1luMoNACSADA0ACqC5J0hqeIA)
```sh
--no-bracket-spacing
--parser angular
```

**Input:**
```html
<p>
    {{
        'delete'
            | translate: {what: ('entities' | translate: {count: array.length})}
    }}
</p>
```

**Output:**
```html
<p>
  {{
    "delete" | translate: {what: "entities" | translate: {count: array.length}}
  }}
</p>

```

**Expected behavior:**
The parentheses should be kept to prevent angular from parsing the two closing curly brackets as the end of the block

**Comment by thorn0** [comment]
Angular doesn't parse `} }` as `}}`. There is a white space in between.

**Comment by nmussy** [comment]
Yes, my bad, I forgot to add the --no-bracket-spacing option. I've updated the original comment and the playground link accordingly.

**Comment by ikatyang** [comment]
It looks like we need to force `bracketSpacing: true` for interpolations.
