### ISSUE TITLE
support for wrapping attributes in HTML

### ISSUE THREAD

**Issue by jfoo1984** [prettier/prettier#5652]
This was mentioned in #3540, but it doesn't seem like there was any work or update on it, but is support for wrapping HTML attributes ([similar to how VSCode does it with html.format.wrapAttributes](https://code.visualstudio.com/docs/languages/html#_formatting)) under consideration?  I'd be happy to help look into this as well if someone can get me started.

EDIT: also, may be worth noting that VSCode [derives those settings from js-beautify](https://github.com/beautify-web/js-beautify#css--html)

**Comment by ikatyang** [comment]
Hi, it looks like you're looking for #3101 or #5501.
