### ISSUE TITLE
--write option conflicts with package.json scripts chaining (namely stylelint)

### ISSUE THREAD

**Issue by avrelaun** [prettier/prettier#5656]
**Environments:**
- Prettier Version: 1.15.3
- Running Prettier via: package.json scripts (Node.JS)
- Runtime: Node v10.14.2
- Operating System: Linux

**Steps to reproduce:**

We have a package.json script at work called "fix" which runs prettier write && eslint --fix && stylelint --fix. Works pretty well, but the stylelint --fix output varies based on whether or not prettier as the --write option. Cannot seem to figure out why.

Here's a repo containing minimal code to test: 

https://github.com/avrelaun/prettier-stylelint-conflict

**Expected behavior:**

When running "yarn run fix" in the repo, the files should be edited like when running "yarn run fix2" (where prettier does not --write)

**Actual behavior:**

Some stylelint --fix does not pass (although some does, you can check by adding some other css/scss stylelint rule error)

**Comment by avrelaun** [comment]
Related duplicate on stylelint: https://github.com/stylelint/stylelint/issues/3856

**Comment by ikatyang** [comment]
The formatted code is printed to the stdout if there's no `--write`, which means it does nothing to your files. It looks like you forgot to use [`stylelint-config-prettier`](https://github.com/prettier/stylelint-config-prettier) to disable conflict stylelint rules.

**Comment by avrelaun** [comment]
I know pretty well prettier print to stdout without ```--write```, and it does nothing to our files. If you prefer,  we can remove prettier --write from the fix2 script, but the stylelint --fix shouldn't have a different output if run right after prettier by chaining it, or running it standalone.

After running prettier --write, the files are written and standing still, and the output of stylelint --fix shouldn't differ based on whether it's called after prettier like this: ```prettier --write && stylelint --fix``` or with two separate commands runned one after another.

stylelint-config-prettier are prettier rules applied to stylelint, which is not what we would like to achieve I think. Prettier is used for formatting with defaults, then overridden by our own defined rules, like we do on eslint.

**Comment by ikatyang** [comment]
Ah, sorry. I misunderstood.

It's caused by `yarn stylint --fix` which needs to be run two times after `yarn prettierfix` to get the stable output. You can observe the diff between these commands to see the unstable issue:

```sh
yarn prettierfix
yarn stylint --fix
yarn stylint --fix
```
