### ISSUE TITLE
Support private class methods

### ISSUE THREAD

**Issue by geotrev** [prettier/prettier#5660]
Prettier Version: 1.15.3
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgIwIY4CeANtADpQVjF4DOtGA4gE5xwwCWUA5hsBRgyQotGMwCuYGBGYAKAJR8BGMjBgALDrQB0AYgAOzDgDc88ALLt1EACYLlAX2XKDR0xau2FSqINWsYcWZfMhAACThiUgwNOFYAQlDHCicoEAAaEAh9TmhaZFA8ZmYIAHcABSKEfJQ8YwgOGwyQHGY8MABrdgBlfXaubmQxcThM9RgAW2IAdU14Wj6wOG7qjk5jNcJkcHpmrlo4mHK27gm8ZAAzPGIDzIArWgAPACE2zp68CbgAGS44S+utxAD0e3QGxDgAEVxBB4ACbqMQH1mAdmNt8ERSGlMoYuDBpo0NMgABwABhxJQO0za+m2hjgqOM-0yrAAjuIOKxjnhTuckFcEZkDhMOEMJIjaOCoTC4fzAYiYAQCTYiUgAEyZMR4DjEAYAYQgEzO2yg0GZIHEBwAKgQagKDg4HEA)
Parser: Babylon + Flow

**Pre-face:** this is a pretty new feature to Babel, so not entirely surprised if it's not accounted for yet. :)
**Steps to reproduce:**
Using **babel@7.2.x**+ and **@babel/plugin-proposal-private-methods**, try using a private method and formatting with prettier (I used CLI, but it happens in other cases as well).

Simple example:
```js
class Greeting {
  constructor() {
    this.#privateMethod()
  }
  
  #privateMethod() {
    return "Hello there!"
  }
}
```

**Expected behavior:**
The code is formatted.

**Actual behavior:**
Parser error.

```shell
SyntaxError: This experimental syntax requires enabling the parser plugin: 'classPrivateMethods' (8:3)
   6 |   }
   7 |   
>  8 |   #privateMethod() {
     |   ^
   9 |     return "Hello there!"
  10 |   }
  11 | }
```

**Comment by lydell** [comment]
This was added a couple of days ago (#5637) and is coming in the next release (~January)!

**Comment by geotrev** [comment]
Awesome, thanks @lydell!
