### ISSUE TITLE
Prettier not working with `require('node-window-polyfill').register(false)`

### ISSUE THREAD

**Issue by vinayk406** [prettier/prettier#5662]
Getting the below error when trying to use prettier with node-window-polyfill

```js
const nodePolyfill = require('node-window-polyfill').register(false);
const prettier = require('prettier');

console.log(prettier);
```

```
D:\lab\nodejs\codegen\node_modules\prettier\index.js:1957
    throw new TypeError("Super expression must either be null or a function");
    ^

TypeError: Super expression must either be null or a function
    at _inherits (D:\lab\nodejs\codegen\node_modules\prettier\index.js:1957:11)
    at D:\lab\nodejs\codegen\node_modules\prettier\index.js:39936:5
    at D:\lab\nodejs\codegen\node_modules\prettier\index.js:39956:4
    at createCommonjsModule (D:\lab\nodejs\codegen\node_modules\prettier\index.js:19
3:35)
    at Object.<anonymous> (D:\lab\nodejs\codegen\node_modules\prettier\index.js:3992
8:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Comment by evilebottnawi** [comment]
@vinayk406 please use issue template

**Comment by SimenB** [comment]
(might consider getting prettier into CITGM, https://github.com/nodejs/citgm/)

**Comment by lydell** [comment]
Hi! I tried to reproduce this, but failed. Am I missing something?

```
$ node -v
v10.14.2

$ npm -v
6.4.1

$ npm i prettier
npm notice created a lockfile as package-lock.json. You should commit this file.
+ prettier@1.15.3
added 1 package from 1 contributor and audited 1 package in 0.692s
found 0 vulnerabilities

$ which prettier
./node_modules/.bin/prettier

$ echo a > test.js

$ prettier test.js
a;
```

**Comment by vinayk406** [comment]
It failed on windows 10 machine.

**Comment by lydell** [comment]
It works for me, though.

```
$ node -p 'require("prettier")'
{ formatWithCursor: [Function],
  format: [Function: format],
  check: [Function: check],
  doc:
   { builders:
...
```

- Can you try with Node.js 10.4.2?
- What operating system do you use?

**Comment by j-f1** [comment]
Will do @SimenB.

**Comment by vinayk406** [comment]
I'm using windows 10. 

const nodePolyfill = require('node-window-polyfill').register(false);
const prettier = require('prettier');

console.log(prettier);

Its failing when I tried to import 'prettier' after 'node-window-polyfill'

**Comment by lydell** [comment]
Thanks, now I can reproduce. Happens on Node.js 8 as well.

**Comment by vinayk406** [comment]
Working fine with node 11 and node 6 versions.

**Comment by lydell** [comment]
Doesn't work in Node.js 6 for me.

**Comment by lydell** [comment]
Pinging @tgorka, the author of node-window-polyfill, in case you're interested. Not sure whose "fault" this si.

**Comment by vinayk406** [comment]
Loading 'prettier' before 'node-window-polyfill' solved the problem for me.
This issue can be de-prioritized/closed.

**Comment by lydell** [comment]
Alright, let's close it for now then!

**Comment by duailibe** [comment]
This is the same issue of #5018.

Our TOML parser (used by cosmiconfig) tries to subclass `global.Date`, and because of how Rollup works, `global` resolves to `window` when it's defined. `node-window-polyfill` defines a `window` variable, but not  `window.Date`, which makes Prettier work when required before the polyfill, but fails when required after.

Since we have the `standalone.js` build, we could consider ignoring `window` altogether in the `index.js` build.

@lydell @ikatyang WDYT?
