### ISSUE TITLE
webstorm bracket-same-line problem

### ISSUE THREAD

**Issue by 2071534594** [prettier/prettier#5663]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAJgJYBuzU557br379BPFiJFjhkqZ3F9Zk6RKWyVitbIBKcAM4AHaHrjkARhDYBPVVuXwAHjACGAJzjPbdyVGc04ALxMIO7OnFD6esSuEGZwAHTuhsYJFtbBXt4MwMDkoeGR0bEJSUZQJvFpVuQAvjWoAPSOLqEy3o3ybWodQplSDZ19PQrKA72Kw7yTLCAANCAQBjAcxsigbjEA7sRuCHrIIM5cEBxscyBmrs5gANZwMADKBtccUADmyDCuAK5w89T0ADqlA48EM1zgDz2oO4oKsBzAen281eJlcMGizjeNGcyAAZs46CZ5gArPQOABCV1u9wefjgABlXnB8YTiSAyQ4Hq83nQ4ABFb4QeCsol-EDPVxog5cX7nAyuV4wQGnGCUZAADgADPMFRATICrgYDgr9HBXFwWfN3ABHb4cdyY7G4pAEsXzEw0DifH7ivQ8vmC4Us11s8UuMwqthq5AAJnmX2cHDoPNwEBoOIOUGgVpA3xM+GcZn2obFdSAA)
```sh
--parser vue
```

**Input:**
```vue
<!DOCTYPE html>
<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              Response body
              <textarea
                name="readinessProbe.response.body"
              >{{ readinessProbe.response.body }}</textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

```

**Output:**
```vue
<!DOCTYPE html>
<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              Response body
              <textarea
                name="readinessProbe.response.body"
              >{{ readinessProbe.response.body }}</textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

```

**Expected behavior:**
```
<!DOCTYPE html>
<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              Response body
              <textarea name="readinessProbe.response.body">
               {{ readinessProbe.response.body }}
              </textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by lydell** [comment]
Hi! That would include a bunch of spaces at the start of the first line of your textarea – try it! So doing what you suggest wouldn’t be good. Or am I missing something?

**Comment by ikatyang** [comment]
- Top-level elements that's not something like `<template>` or `<html>` are considered custom blocks in Vue, which is not safe to be formatted as HTML so we just preserve it, see #5448 for more info.
- It's not safe to add whitespaces there, see https://github.com/prettier/prettier/issues/5582#issuecomment-443493157.

Here's how we format it if it's in `<html>`:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zrAJgJYBuncuVS8BLIUJH9BEyaJmy508YtlSxUVavUKtsgEpwAzgAdoRuOQBGELgE8VetfAAeMAIYAnOO8dPZUO40cAC8TCDe7rxQxkbEnhBWcAB03qbmKTb24X7+DMDA5JHRsfGJKWlmUBbJWXbkAL4NqAD0rh6Runqt8rmKPcqaWgMa2i29Q5Ljg1MTI5yt7IwgADQgECYwPObIoF4JAO7EXghGyCDufBA8XKsgVp7uYADWcDAAyiZPPFAA5sgwTwAVzgayWAHVKDx4KYnnB3qdofxoXZzmAjGc1j8LJ4YPF3L8aO5kAAzdx0CxrABWRhcACFHi83u8gnAADI-OCk8mUkA0lzvH6-OhwACKQIg8G5FNBIC+nhx5z4ILuJk8Pxg4JuMEoyAAHAAGNZqiAWcGPEznNXGOCePhctbeACOQJ43nxhOJSDJMrWFhoPABwNlRiFIvFkq53p5so8Vi1XB1yAATGtAe4eHQhbgIDQiecoNAHSAgRZ8O4rGdozKmkA)
```sh
--parser vue
```

**Input:**
```vue
<!DOCTYPE html>
<html>
<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              Response body
              <textarea
                name="readinessProbe.response.body"
              >{{ readinessProbe.response.body }}</textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</html>
```

**Output:**
```vue
<!DOCTYPE html>
<html>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              <div>
                Response body
                <textarea name="readinessProbe.response.body">{{
                  readinessProbe.response.body
                }}</textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</html>

```
