### ISSUE TITLE
Ugly array key format 

### ISSUE THREAD

**Issue by ph55** [prettier/prettier#5664]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaCuAjGAJwEMwYARHEmAS2kwF5MBbCZhGAOgBMrjboACgA6UTNnxFSMALLEADgG0asOIQBuxADYBdRQAYdAGkyjxuAiTJylK+Bu16AjDszE0mHFBowA8gDMAFRp2TkpqOigAYXQiHDIIQlEASgBuECMQCHkBKDRkUGJCQggAdwAFIoR8lGJ1CBpuDJA8KwBrOBgAZXlSFQBzZDi4TIALGGYtAHVRnzg0XrA4LuqfGnUfAE9kcDR8zJU0NRhykn7mYmR-bSPMgCs0AA8AIXbOruJ2ABkVOCubkYgB6PLoDLRwACKOAg8H+WluIF6hCOhB2ME28nmYEINByzXkJSOUxI8h2BPmanUf0yhDgAEccDRaadiOdLkhrvDAUdmDQhoQcNywZDobCkMNMjBiHgpo0YKNkAAmSUkGhaAYxZgXHZQaDUkA4I6BaU1TkIgl2WXceXIJz6fQAXwdQA)
```sh
--parser typescript
--print-width 100
--single-quote
```

**Input:**
```tsx
const subtractDuration = moment.duration(
  subtractMap[interval][0], 
  subtractMap[interval][1] as unitOfTime.DurationConstructor
);
```

**Output:**
```tsx
const subtractDuration = moment.duration(subtractMap[interval][0], subtractMap[
  interval
][1] as unitOfTime.DurationConstructor);

```

**Expected behavior:**

`interval` key should be force sticked to array container.

**Comment by sasurau4** [comment]
This issue is fixed?
The playground link seems same as expected behavior.

**Comment by evilebottnawi** [comment]
Yes, need add to test to ensure we can't do regression in future
