### ISSUE TITLE
TypeScript constructor assignment improvement.

### ISSUE THREAD

**Issue by ph55** [prettier/prettier#5666]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAFTlJgGETy9gAdKPA6W7AVzBhwAKNhw4ZsASwBuxeHmIYJSPAEFFAZTjYpEsHAA0I0eOmy4nKADMJAc2V1o1m5u264RgJTMAvm28h9EAgMGAkuZFBibGwIAHcABSiEUmQQYikICQATAJAAI2xiMABrOBh1DCKJKBtkGF4DEAALGABbQgB1Jol4Ukq9TShSHukegE9UsHJc6tItGHjCm1biZEtiQjnAgCtSNAAhQpKy9WJWuAAZarg1ja2QXbR1aptCOABFHgh4W83Gyuwc2wqRgYwwNDAkhCuRMsA62RgTWQAA4AAyBcQQOYdQoYVLiGhaKQ3QLYOAARx4EjJi2Iy1WSHWf0Cc1aEjqDRZLzen2+N0Zd0aMGIeXhWURyAATIF6sQJIQXg5WitUlBoCSQDw5pQRSkBX9vN4gA)
```sh
--parser typescript
```

**Input:**
```tsx
export class TestClass {
  constructor(
    private api: ApiService,
    private config: ConfigService
  ) {}
}
```

**Output:**
```tsx
export class TestClass {
  constructor(private api: ApiService, private config: ConfigService) {}
}

```

**Expected behavior:**

Consider breaking line despite `printWidth` value (as input).
Since it visually should be close to:

```tsx
export class TestClass {
  private api: ApiService;
  private config: ConfigService;
}
```

and not:

```tsx
export class TestClass {
  private api: ApiService; private config: ConfigService;
}
```

**Comment by duailibe** [comment]
Is there any relation between "class properties" and "constructor arguments" in TypeScript? I don't use TypeScript so I really don't know. 

If there is, then sure let's discuss.

If this works like JS where there's no relation between class properties and arguments in constructor, then I don't see why we should special case the `constructor` method. It's just like any other method in the class

**Comment by ikatyang** [comment]
It's a TypeScript-specific feature called [parameter property](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties). I think we should not treat it differently since it can be used with normal parameter simultaneously:

```ts
export class TestClass {
  constructor(
    private api: ApiService,
    something: any,
    private config: ConfigService
  ) {}
}
```

**Comment by duailibe** [comment]
Oh cool I didn't know.. in that case, we can discuss if it makes sense to add this, but I agree with @ikatyang we should not treat it differently.

**Comment by ph55** [comment]
> I think we should not treat it differently since it can be used with normal parameter simultaneously

Good point.

**Comment by eamodio** [comment]
I would love to see this added -- anytime a parameter property is used multi-line the whole ctor. This makes features like reference code lens in vscode better:
![image](https://user-images.githubusercontent.com/641685/52997435-82ba6f00-33ee-11e9-8faf-e88cd92b0245.png)

Any way this could be re-opened?

**Comment by lydell** [comment]
@eamodio Can you provide a screenshot showing the vscode lens thing not working?

**Comment by eamodio** [comment]
![image](https://user-images.githubusercontent.com/641685/53004012-3d9e3900-33fe-11e9-8400-b7f2225a7885.png)

They still work, but it is much clearer if they are each on their own line.

**Comment by eamodio** [comment]
@lydell is this something that can be reconsidered and re-opened?

**Comment by brainkim** [comment]
I’m familiar with the code that would have to change to do this and could work on this issue this weekend, but I’m not sure if there’s consensus to implement this yet? Personally, as an avid typescript user I think putting parameter properties on their own lines (even if there are non-property parameters in between) is a good idea.

**Comment by nevcos** [comment]
I would love to have this introduced, this would make the code much easier to read.

This format that Prettier is applying now is making it very hard to understand that there are multiple class properties defined there, making this Typescript feature much less apealing:

``` 
export class TestClass {
  constructor(private api: ApiService, private config: ConfigService, autoConnect: boolean) {}
}

// vs

export class TestClass {
  constructor(
    private api: ApiService,
    private config: ConfigService,
    autoConnect: boolean
  ) {}
}
```

I suggest introducing this feature as a new option.
```
--typescript-parameter-prop-multi-line <never|allways|preserve>
> never (default) - working as today
> allways - apply multi line format every time there's at least one parameter property
> preserve - keep existing format decision
```

Thanks!

**Comment by nseni** [comment]
That's why prettier should have more options in configuration. This formatting rule is a deal-breaker to me, as an Angular developer.

Having this in one file
```ts
  constructor(private form: NgForm, private ngbModal: NgbModal, private commonDialogsService: CommonDialogsService) {}
```
but this in another file
```
  constructor(
    private title: Title,
    private form: NgForm,
    private ngbModal: NgbModal,
    private commonDialogsService: CommonDialogsService,
  ) {}
```
is just not acceptable. It's inconsistent, it's hard to scan, it makes the code harder to understand.

**Comment by stringham** [comment]
I think that putting each constructor parameter on their own line if there are any parameter properties helps a lot with code readability.

In addition to helping with code readability, it helps avoid merge conflicts and reduce diff sizes in line-based version control.

I think it would be an improvement to Prettier to change this without adding an additional configuration option.

```typescript
    constructor(foo: string, private bar: number) {}
```

would change to

```typescript
    constructor(
        foo: string,
        private bar: number,
    ) {}
```

An alternative approach to a unilateral change or a new configuration variable is to honor whether someone has entered a trailing comma in their constructor parameter list, then people could opt-in to multi-line constructor parameters by writing

```typescript
    constructor(foo: string, private bar: number,) {}
```

**Comment by anewtonlevey** [comment]
I think that this should be a configuration option for typescript. We've decided internally to currently force it by putting in a trailing comment after the first parameter as below but preference would be just to have config we can turn on that would do this for us.

`
constructor(
        public foo: string, //
        private bar: number,
    ) {}
`

**Comment by MrGrigri** [comment]
The most elegant solution to this, until there is a specific rule in place, is to add the `// prettier-ignore` trigger before the constructor. The empty comment, `//`, solution doesn't let other developers know what it's doing.

I believe that there should be a constructor specific rule. In Angular and because of dependency injection, the constructor tends to have more than normal amounts of parameters.

**Comment by marcuswestin** [comment]
Bump - would love this to be resolved! It's definitely annoying as is.

**Comment by thorn0** [comment]
Let's do this when at least one parameter is a parameter property.

**Comment by Samuel-B-D** [comment]
Bumping this. It's not just annoying, it's a deal-breaker for working in any serious Angular project.
Not only is it unclear to read, but it also create tons of avoidable merge conflicts.

**Comment by varthc** [comment]
Any update on this? Or solution that it's not a patch like `//`? Thanks!

**Comment by gtteamamxx** [comment]
For me it's unbelievable that this issue is 4yrs old and no one did it.

**Comment by TovahParnes** [comment]
Hi! Me and two classmates was gonna work on this issue for our masters class at Uni. 
We have tried to replicate the problem and found that prettier puts the parameters on different lines based on characters per line and not the amount of parameters. If you have any helpful input or advice we are all ears, thanks!

**Comment by danriedl** [comment]
I introduced prettier in our project to have common code formatting and now my colleagues are mad, because we have that weird constructor formatting 🚶‍♂️

**Comment by fisker** [comment]
Fixed by #14402

**Comment by klutzer** [comment]
Is there a way to disable this new behavior?

**Comment by carlosmoliv** [comment]
> 

Hey, did you manage to solve that?

**Comment by klutzer** [comment]
> @klutzer  Hey, did you manage to solve that?

No, I didn't find any way to disable it, so I stuck with the previous version

**Comment by seiyab** [comment]
Hi, I'm a contributor who have implemented this behavior.
This new behavior can't be disabled as of V3 except [prettier-ignore](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOkUmMATgK5gwTUAUADtQJYBu68O6AGhztuvODgBGASkIBfEvKgkwGbDgBChEmQD0O4dTgwYHONQC0HAOZQmcbeWhU6DJm048+gg6L7S5CiACIBCsJk7IoOjU1BAA7gAK0QiYyCDoqHHoAJ6pwRLU6GAA1kYAyugAtnAAMhxQcMgAZhmYcPmFJeWsRfVWyDS07SBtlRwDdMOYfahwAIq0EPDNrcMAVpgAHmUz84vLSC2obcEAjvtwCbGsqShY5g1wACbPQSA06ByofQDCEJWVdBpDKoN7TKBWWZ4YycCS0eAJMx1BorY7DAAWMEqqAA6uiOPBMD0wHAyikCdwCdk0mBsG8uEMAJJQF6wMpgThhPAssowbKzVEnEDsCBtHGFVhpdhwNrULiNYL1WUwK7oKyAwXDHrUWVpPmsGUcjhhN4iWA4jhPGDo5AADgADMFDOcOIZVeqgYdVsEYOgJBarTakAAmYK0NoAFT9tyOQrglQkzxeTxq6AhtDVcAAYkxAcY+sD4RAQLJZEA).
If you really need older behavior, I recommend create an issue and **describe why you need it** there.
I think improving heuristics should be better approach if it is inconvenient under some practical cases.
Just adding an option is likely to be rejected because [Prettier is **opinionated**](https://prettier.io/docs/en/option-philosophy.html).
And this behavior is not likely to be reverted because they described why it is desired like https://github.com/prettier/prettier/issues/5666#issuecomment-465054210 .
