### ISSUE TITLE
Issues with multiple YAML header

### ISSUE THREAD

**Issue by anishmittal2020** [prettier/prettier#5669]
In the following examples, the 2nd yaml header has added blank line and in the second example, it completely goes out of the line!

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdWBLGAbOJAAgEEAHMgSQFsBDAczi3VS2cygHdsATGAC2IBOAGwAGLPzjZ6-GMQDsYiVBZsoAYiKVYAJwg8ArmBjZo61EQscQAGhAQyp6AGdkoWrv2cACp4RuKLQAbhC8diAARrq0YADWcDAAymSx2FD0yDC6hnD2ctR4AOr8uHAuqWBwSQG42MG4AJ7I4C5u9ukucLowPjH0dMgAZrR4XfYAVi4AHgBCMfGJSbTUcAAy6XDDo+MgU9NJ6fQEAIqGEPDbY3kgqbpdui10unE8EJxQEWS66TBFvAJkAAOMT2b4QLpFGJkFrfcrdYJbey6OAAR0M2BRfQYgyQI2u9i61GwWRyNxcR1O50ueJ2NxgtEi-z4-GQACZ7NlaNg8EcAMIQai4kBQaBIkCGLoAFUZgXxXQAvgqgA)
```sh
--parser markdown
```

**Input:**
```markdown
---
title: AppImage
---

---
width: 960
height: 700
---

# Introduction

- 

---

```

**Output:**
```markdown
---
title: AppImage
---

---

width: 960
height: 700

---

# Introduction

-

---

```

**Expected behavior:** See Input.

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdWBLGAbOJAAgEEAHMgSQFsBDAczi3VS2cygHdsATGAC2IBOAGwAGdqyhYAxEUqwAThB4BXMDGzQ2UVER0ssIADQgIZTdADOyULUXLOABXsIbKWgDcIvEyABGirRgANZwMADKZMHYUPTIMIqqcKb8MNR4AOr8uHBW0WBwEW642J64AJ7I4FY2prFWcIowTkH0dMgAZrR4jaYAVlYAHgBCQaHhEbTUcAAysXBdPX0gg0MRsfQEAIqqEPBLvSkg0YqNitV0iiE8EJxQfmSKsTCZvALIABxipk8QjZkgmRqk88k1PItTIo4ABHVTYaGtBgdJDdI6mRrUbAJJLHKybHZ7A6o5bHGC0fxvPj8ZAAJlMiVo2DwmwAwhBqCiQFBoJCQKpGgAVCnuNGNAC+4qAA)
```sh
--parser markdown
```

**Input:**
```markdown
---
title: AppImage
---

---
width: 960
---

# Introduction

- 

---

```

**Output:**
```markdown
---
title: AppImage
---

---

## width: 960

# Introduction

-

---

```

**Expected behavior:** See Input

**Comment by ikatyang** [comment]
Front matter (YAML) must be the first thing in the file, the rest "YAML" (`---`s) are considered thematic breaks.

**Comment by anishmittal2020** [comment]
Ok, so prettier supports only 1 block of YAML Header?

**Comment by ikatyang** [comment]
Prettier only supports [front matter](https://jekyllrb.com/docs/front-matter/):

> The front matter must be the first thing in the file and must take the form of valid YAML set between triple-dashed lines.
