### ISSUE TITLE
js in html tagged template literals too verbose?

### ISSUE THREAD

**Issue by daKmoR** [prettier/prettier#5672]
hey,

so when using prettier for tagged template literals it becomes kind of very verbose. e.g. it puts every `${` and `function()` on its own line. I would like to get easily readable and "short" js/html code - and that in this case unneeded verbosity sort of defeats the purpose.

Don't get me wrong for javascript it completely makes sense... but the js in a html tagged template literal is usually pretty limited. e.g. you will not define full functions there.

So this is basically a discussion to see if we can get a more "suitable" default for js in html tagged template literals. It does not need to be completely the same as `Expected behavior` but not putting each `${` followed by a `function` onto a seprate line would already help tremendously. 

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjAhgJzUwF5MBtAcgQBNMIAzTGACzkzgJYoBpMLr8AVygBrBJjS4AlgBsIhCgF0A3AB0o6+sLAwp0TAAk4MuQHV5M6gAoAlJmDrMmfHBiD8UTMxgBbGQANHJ0wAHmYAZgA+ACECTAAZKQwQgHoIyKCnABJgPEIAOh9cAAcrPJJIr18AzODQ4sicvIBfVIba-xtmoP81KG6oEG4QCGLddGRQAnwIAHcABQIENGQQXAA3CClqIZBsfFwwMRgAZWLDqSgAc2QYIThh7z9TZil4NHOwOBPlt6l1t4AT1WYDQK2GlzQcHwMHmByuRWQ9FwMihwwAVmgAB7RA5HVwnXA+OCJKBwJEotEgTFYk6XK4yOAARUEEHgFNRDxA50I0NWeGwgLkg2GxXwlxgpm2LGQAA4AAyimZQ0wHYqrMVwKH4dbk4YuACOgikLjhuARuA5VKhPikt3uwzQ9MZLLZ5KQyM5wxguGwUuoMqQACZvQdZPSAMIQHyIlBQaB6kCCKEAFV9Kw9lLgzWaQA)
```sh
--parser babylon
```

**Input:**
```jsx
const bars = ['end of the earth', 'drunken sailors'];

function HelloWorld() {
  return html`
    <h3>Bar List</h3>
    ${bars.map(bar => html`
       <p>${bar}</p>
    `)}
  `;
}
```

**Output:**
```jsx
const bars = ["end of the earth", "drunken sailors"];

function HelloWorld() {
  return html`
    <h3>Bar List</h3>
    ${
      bars.map(
        bar => html`
          <p>${bar}</p>
        `
      )
    }
  `;
}
```

**Expected behavior:**
```jsx
const bars = ["end of the earth", "drunken sailors"];

function HelloWorld() {
  return html`
    <h3>Bar List</h3>
    ${bars.map(bar => html`
       <p>${bar}</p>
    `)}
  `;
}
```

**An alternative possible outcome (okish):**
```jsx
const bars = ["end of the earth", "drunken sailors"];

function HelloWorld() {
  return html`
    <h3>Bar List</h3>
    ${bars.map(
       bar => html`
         <p>${bar}</p>
       `
    )}
  `;
}
```

**Comment by daKmoR** [comment]
> We could format these like JSXExpressionContainers.

how would that output look like?

**Comment by j-f1** [comment]
Like so:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjAhgJzUwF5MBtAcgQBNMIAzTGACzkzgJYoBpMLr8AVygBrBJjS4AlgBsIhCgF0A3AB0o6+sLAwp0TAAk4MuQHV5M6gAoAlJmDrMmfHBiD8UTFYA8APkdOmN7MAMy+AEIEmAAyUhjeAPSh-p6BwHiEAHQAtrgADlYZJL5eAYFO3nm+6QQAvolVZZg2NrUBib42alBtUCDcIBB5uujIoAT4EADuAAoECGjIILgAbhBS1P0g2Pi4YGIwAMp5e1JQAObIMEJwA8ww2TKmzFLwaCdgcIcLr1IrrwBPJZgNCLAZnNBwfAwGa7c65ZD0XAySEDABWaAAHuFdvtXIdcNk4LEoHBEcjUSAMZjDmdzjI4ABFQQQeDklG3EAnQhQpZ4bAAuR9AZ5fBnGCmDYsZAADgADCLJpDTLs8ktRXBIfgVmSBi4AI6CKQuWG4eG4dmUyHZKRXG4DNB0hnM1lkpBIjkDGC4bCS6jSpAAJi9u1kdIAwhBsgiUFBoLqQIJIQAVH2Ld0UuC1WpAA)
```sh
--parser babylon
```

**Input:**
```jsx
const bars = ['end of the earth', 'drunken sailors'];

function HelloWorld() {
  return (<>
    <h3>Bar List</h3>
    {bars.map(bar => (
       <p>{bar}</p>
    ))}
  </>);
}

```

**Output:**
```jsx
const bars = ["end of the earth", "drunken sailors"];

function HelloWorld() {
  return (
    <>
      <h3>Bar List</h3>
      {bars.map(bar => (
        <p>{bar}</p>
      ))}
    </>
  );
}

```

**Comment by LarsDenBakker** [comment]
Yes that looks great, definite improvement!

**Comment by LarsDenBakker** [comment]
What would be needed to get this moving forward?

**Comment by daKmoR** [comment]
it's a new year 🎉

maybe some hints on how this could be archived? I'm not afraid to do some code digging myself - would just need a starting point :)

**Comment by duailibe** [comment]
I don't understand why this only happens with `html` tag:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjAhgJzUwF5MBtAcgQBNMIAzTGACzkzgJYoBpMLr8AVygBrBJjS4AlgBsIhCgF0A3AB0o6+sLAwp0TAAk4MuQHV5M6gAoAlJmDrMmfHBiD8UTPQgQABo6dMAB5mAGYAPgAhAkwAGSkMIIB6MPCApwASYDxCADoAW1wAByscknDMZhh8mX9PQMCgovCsnIBfZOb0zF8bNoDfNSh+qBBuEAgi3XRkUAJ8CAB3AAUCBDRkEFwANwgpajGQbHxcMDEYAGUi06koAHNkGCE4caqa02YpeDRrsDgL9ZfKTbL4AT02YDQG3GtzQcHwMGWJzuhWQ9FwMjh4wAVmgAB6RE5nVwXXD5ODxKBwNEYrEgXF4i63O4yOAARUEEHgNMxLxA10I8M2eGwoLko3GRXwtxgpn2LGQAA4AAyShZw0wnIqbKVwOH4bbU8YuACOgikLiRuBRuB5dLh+Skj2e4zQzNZHK51KQ6N54xguGwcuoCqQACZ-SdZMyAMIQfKolBQaBGkCCOEAFUDGx9tLgbTaQA)
```sh
--parser babylon
```

**Input:**
```jsx
const bars = ['end of the earth', 'drunken sailors'];

function HelloWorld() {
  return foo`
    <h3>Bar List</h3>
    ${bars.map(bar => html`
       <p>${bar}</p>
    `)}
  `;
}

```

**Output:**
```jsx
const bars = ["end of the earth", "drunken sailors"];

function HelloWorld() {
  return foo`
    <h3>Bar List</h3>
    ${bars.map(
      bar => html`
        <p>${bar}</p>
      `
    )}
  `;
}

```

**Comment by daKmoR** [comment]
a friendly reminder to see if there is anything we can do to help? 🤗

**Comment by ikatyang** [comment]
@daKmoR Sorry for the late response, I just opened #5771 to address this issue.

**Comment by ikatyang** [comment]
> is there a specific reason it's now like the 2nd one?

That's how normal templates work (https://github.com/prettier/prettier/issues/5672#issuecomment-453173558) now.

> could also happen in a separate PR if needed?

I'm not sure why we only add special cases for JSX (https://github.com/prettier/prettier/issues/5672#issuecomment-449385480), it's worth investigating.

**Comment by daKmoR** [comment]
ah I see... so that would be another special case that needs to be handled...

what do you think is the best way forward?
maybe merge this as is (as it's already a big improvement) and open another issue with just this particular question?
