### ISSUE TITLE
The behavior is different for different kinds of OS.

### ISSUE THREAD

**Issue by maxpopovitch** [prettier/prettier#5675]
My IDE (JetBrain WebStorm, macOS) consider the code snippet at the screenshot below as a wrong formatted one:

```
const DBFieldInfoBlock = ({
  rowClassName,
  cellLabelClassName,
  cellValueClassName,
  id,
  value,
  currency,
}) => (
  <div className={rowClassName}>
    <span className={cellLabelClassName}>
      <InfoLabel id={id} />:
    </span>
    {value !== undefined && value !== null && (
      <span className={cellValueClassName}>
        <InfoValue value={value} id={id} currency={currency} />
      </span>
    )}
  </div>
);
```

https://i.stack.imgur.com/gA8aH.png

But my teammate has JetBrains IntelliJ IDEA on Windows, and the same code is OK for the same linter!

We use the same environment for linters (.eslintrc, .prettierrc, .editorconfig, etc.). In the same time, my IDE does not refer to the rule it's trying to use, it just shows me this hint:
`ESLint: Insert⏎·····(prettier/prettier)`

Who knows what can it be?

**Comment by kachkaev** [comment]
Hi @maxdonetsk! Can this be related to how CRLF / LF is configured in your repo and operating systems? See https://prettier.io/docs/en/options.html#end-of-line

**Comment by maxdonetsk** [comment]
Resolved.
Guys, perhaps it will be helpful for someone.
I proceeded following steps:

1. Configure .gitconfig file with `autocrlf = true` instead of `autocrlf = input` as it was before.
2. Delete the repo.
3. Clone the repo again.

That's it!
