### ISSUE TITLE
Preserve Liquid control flow tags on dedicated lines

### ISSUE THREAD

**Issue by infotexture** [prettier/prettier#5680]
The _contents_ of Liquid tags are now preserved since #4484, but [control flow tags](https://shopify.github.io/liquid/tags/control-flow/) that are used to define programming logic are treated as any other content and subjected to Prettier's line fitting rules.

This makes it much more difficult to understand the template logic, as the logical blocks are rendered as inline content.

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeARhAJgTwHwA6UABMcAKTECWUYANgK5ZzEAWcAhswE4B0rMALZ1i5AL5FSqLFQBu1LAF4C4aPFgri9DgGcdykDoiC4MVjQDmKwiVLFpcrXV36V3CAHdrku6QrUAM2IABw4LOF4GbhFIWA4aHWIAcgB6ZlkUpNEJW18-Shp6JhZ0DigoOD4BYWyfX38EGSDxOrtgYC01BBhiMRzfVDS5Gykh2RH7GXltPQMjEzNLAFo4Oh04b1yyAqDQ8N5oFhat0gAxKm4dHtkObioymFaGtapdsIiYDwhak+IAZTgsSwxBudweT0oq3WPzyxAAKuZuMDQfcNFsGlAmjD7GMJv5CoxmMR1rcwKx+EIRMd8tRaISWOw6MEKTVjoNMLgbCAADQgCDBGBUaA6ZCgW7uDwABVuCBFKA4sggVCwPJA6G4HDAAGtTH9QmBLMgYNwGHBedU6AB1czwHT6uAAqA6KiC2QunDIcB6VUJSowSUaiyCDjIAIcNZmkAAKx0AA8AEIa7W6jgmAAyNDgofD615Mdjf0sdDgAEUGBB4NmI7zQpdKp6LargndYJblWZkAAOAAMNfc60tGuCnubcHW3FkWd53DgAEcGBc4AGwsGq7nDHBBFQjSbI86oBZi2WK1mkGHqyAYBx0G2sB2kAAmXnG+J0SwAYWMq5QUEOqoY6xwtecrnusfRAA)
```sh
--parser html
```

**Input:**
```html
<body>
  {% include header.html %}
  <div id="content" class="something">
    <div class="row">
      {% if page.url contains '/dev/' %}
        {% include banner.html %}
      {% endif %}
      {{ content }}
    </div>
  </div>
  <div class="something-else">
    {% if page.one %}
      First variant
    {% elsif page.two %}
      Second variant
    {% else %}
      Third variant
    {% endif %}
  </div>
  {% include search.html %}
  {% include help.html %}
</body>
```

**Output:**
```html
<body>
  {% include header.html %}
  <div id="content" class="something">
    <div class="row">
      {% if page.url contains '/dev/' %} {% include banner.html %} {% endif %}
      {{ content }}
    </div>
  </div>
  <div class="something-else">
    {% if page.one %} First variant {% elsif page.two %} Second variant {% else
    %} Third variant {% endif %}
  </div>
  {% include search.html %} {% include help.html %}
</body>
```

**Expected behavior:**

Control flow tags and include statements that appear on separate lines in the source file should remain on separate lines.

From https://github.com/prettier/prettier/issues/3695#issuecomment-380230600, it sounds like the original idea was to preserve them:

> We should be able to fix this by detecting paragraphs whose first and last words are the word
> `{%` and `%}` and printing those entire paragraphs as they appear in the source.

**Comment by infotexture** [comment]
Now that #5596 has landed with v1.16, perhaps the same logic could be applied here, since this is essentially another case of the `if-else`-like logic that @ikatyang handled there.

**Comment by ikatyang** [comment]
The issue here is that there's no reliable way to identify those liquid tags without using a liquid parser since contents in liquid tags should be parsed as their children, not siblings.

And also we currently do not support nodes with multi-branch:

```
{% if cond %}
  First variant
{% else %}
  Second variant
{% endif %}
```

We need to figure out a way to handle it without introducing unexpected whitespaces.

**Comment by PatrickNausha** [comment]
Not sure if this belongs in a separate issue, but the HTML parser  seems to actually break liquid templates in the case that it interprets liquid tags as HTML attributes.

Input:
```
<div class="js-new-section new-section" data-section="{{ section_name }}" {% if section_id != nil %}data-section-id="{{ section_id }}"{% endif %} data-above-section="{{ above_section }}">
	...
</div>
```

Output:
```
<div
	class="js-new-section new-section"
	data-section="{{ section_name }}"
	{%
	if
	section_id
	!="nil"
	%}data-section-id="{{ section_id }}"
	{%
	endif
	%}
	data-above-section="{{ above_section }}"
>
	...
</div>
```

Note `section_id != nil ` becomes `section_id !="nil"` which are not equivalent.

**Comment by lydell** [comment]
@PatrickNausha Yeah, Prettier's HTML formatter mostly supports plain HTML currently.

**Comment by PatrickNausha** [comment]
👍 I should've clarified that my comment was more an affirmation of @ikatyang's suggestion that a separate liquid parser would be necessary for Liquid-Prettier integration.

**Comment by tbsvttr** [comment]
A Liquid integration for Prettier would be _very_ useful!

**Comment by thorn0** [comment]
Prettier isn't going to add more languages to the core. This should be implemented as a plugin.
