### ISSUE TITLE
TSX parser incorrectly removes parentheses around inline React elements being accessed

### ISSUE THREAD

**Issue by jleclanche** [prettier/prettier#5683]
Reproduce with this code:

```ts
import React from "react"

const Example  = () => {
    const foo = (<a/>).toString()
    return <a/>
}
```

This removes the parentheses, creating the invalid syntax `foo = <a/>.toString()`.

**Comment by lydell** [comment]
Babel compiles both to the same thing: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DwQw9AfAdALg9gZRgJwJYDsDmAKAlAKCA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=

I tried all parsers on https://astexplorer.net/, and they all parse it.

What makes you say the syntax is invalid?

**Comment by jleclanche** [comment]
Prettier can't reparse the same file afterwards. Vscode also complains.
I'll have to check when I get home if it's actually valid in any situation.

**Comment by jleclanche** [comment]
Maybe it's only an issue in typescript?

**Comment by lydell** [comment]
Ah, yes, you're right. It's a Typescript issue.

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwB0QdTyG6o3IoBnAgUQA8SWADZx8+ALz4AFAEpJAPnzA248Zx74KECJJkAeEgHoFsgHQwIAZRg5UUAOZzVapjACuOKPkMm2AXxAAGhAITBhUaC5kUBIcagB3AAU4hGiUEgA3CFQAE2CQACMcMgBrOBgrTDJ7B2RbdzgQgAsYdGEAdWbUeC5qsDgrNJ7UTJ6AT2RwLmiQ+y44PCSSh3QSZAoSYQWQgCsufgAhErByyqE4ABl7OA2tnZB9-ita0QBFdwh4O+2mkGqcAscFMYONMHAuGA7OECpg7LAOnkYM1kAAOAAMIThEAWHRKmCmcIhi0ytxCTAAju5UExliRVuskJtfiEFuhUPUcI1Wa84B8vrcmfc-jASIVEblkcgAEwhWwkVDCWoAYRoaymUGgZJA7gWABUxelmQt-P4gA)
```sh
--parser typescript
```

**Input:**
```tsx
import React from "react"

const Example  = () => {
    const foo = (<a/>).toString()
    return <a/>
}
```

**Output:**
```tsx
import React from "react";

const Example = () => {
  const foo = <a />.toString();
  return <a />;
};

```

**Second Output:**
```tsx
SyntaxError: ',' expected. (4:20)
  2 | 
  3 | const Example = () => {
> 4 |   const foo = <a />.toString();
    |                    ^
  5 |   return <a />;
  6 | };
  7 | 
```

We probably need to report an issue to https://github.com/JamesHenry/typescript-estree

**Comment by JamesHenry** [comment]
@lydell You mentioned testing all parsers on https://astexplorer.net/ but if you choose the actual TypeScript parser on there, it does produce `parseDiagnostics`, which is how it reports errors.

This is ultimately what is being forwarded on by `typescript-estree`. This is a tricky one... :/

**Comment by lydell** [comment]
Yes, sorry, I was mistaken about typescript on astexplorer. Maybe Prettier should keep the parens in this case anyway since I think that looks better.

**Comment by jleclanche** [comment]
I'm of the general opinion that if it's a syntax error in TSX, prettier should probably go as far as adding parentheses even if the file is in JSX (which may save the author of the code pain down the line).

**Comment by jleclanche** [comment]
Either way IMO the behaviour should be consistent between TSX and JSX.

**Comment by lydell** [comment]
Let's always put parens around JSX when using `.foo` or `[foo]` access on it.

**Comment by j-f1** [comment]
How about wrapping JSX in parens if it’s used in any way besides passing it to functions, assigning it to variables, or returning it?

**Comment by lydell** [comment]
> How about wrapping JSX in parens if it’s used in any way besides passing it to functions, assigning it to variables, or returning it?

Yeah, maybe there's a better rule. Worth exploring.
