### ISSUE TITLE
[Typescript] Regression: wrong formatting on type assertion

### ISSUE THREAD

**Issue by yuriykuzin** [prettier/prettier#5684]
I guess it was resolved, but now come back.
Similar issue marked as resolved: https://github.com/prettier/prettier/issues/4171

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBLNBBKATwGUBXMMONNAM1IBs8Z4BbABxgBIlMB5AIzRwATgDcAhv3pwAPPwgRp4qAD5MAXkwwAFrgB0AfQCOpbAC9iI0dkp7cBEuUrU6jZnHZcAFAEo9bbDY4LwAdKEwtcTYvL3siMgoqWgYmVg4eeUU4ZR8NNWAwiIidfTjHRJcU908NHHx4pyTXVI8OAG5CzABfHwAaMJ8OqBBekAgObHRkUHFhYQgAdwAFWYQ0ZBBxUQhsABMRkH5hcTAAazgYYjYT7CgAc2QYYVI4Ue0YFnoAdV14NGvKJYoGhsDBsNYYIQNmBqAdbkJhDAlsc7ixxMgaOJ6EJRgArNAADwAQsczhdiOIWHAADK3OAYrE4kD4gnEW53aQARVIEHgDOxrxA12ECI2kKCaDAwkCMAObHmQi+xzYG3lVCs9NGwjgJmw2uR4lR6KQmIFoyELGwj2egpB9y5PL5JsZgpgki+ex0yAATKMnuJsPR2QBhCAsNEbKDQTUgUhCAAqknWzrNQulsA9uy9SAAHAAGLpdIA)
```sh
--parser typescript
```

**Input:**
```tsx
const isAnySuccessfulAttempt$: Observable<boolean> = this._quizService.isAnySuccessfulAttempt$().pipe(
  tap((isAnySuccessfulAttempt: boolean) => {
    this.isAnySuccessfulAttempt = isAnySuccessfulAttempt;
  }),
);

```

**Output:**
```tsx
const isAnySuccessfulAttempt$: Observable<
  boolean
> = this._quizService.isAnySuccessfulAttempt$().pipe(
  tap((isAnySuccessfulAttempt: boolean) => {
    this.isAnySuccessfulAttempt = isAnySuccessfulAttempt;
  })
);

```

**Expected behavior:**
```tsx
const isAnySuccessfulAttempt$: Observable<boolean> = 
  this._quizService.isAnySuccessfulAttempt$().pipe(
    tap((isAnySuccessfulAttempt: boolean) => {
      this.isAnySuccessfulAttempt = isAnySuccessfulAttempt;
    })
  );

```

**Comment by thorn0** [comment]
While it does indeed look bad, superfluous type annotations are bad style because those who write them are missing the point of TypeScript (type inference). So, from a practical standpoint, why fix it?

**Comment by yuriykuzin** [comment]
Thanks @thorn0 , I understand your point. Still, in our current project we prefer to use type annotations for sake of better readability. It's much faster to get the meaning of the code seeing type annotation, which is quite sufficient in case of big team/project.

Basically, I can agree with this comment - https://www.quora.com/In-TypeScript-when-is-it-good-practice-to-include-omit-type-information/answer/Dylan-Cutler

**Comment by j-f1** [comment]
I usually find that I can get the needed information by hovering over the appropriate symbol in my editor.

**Comment by thorn0** [comment]
@yuriykuzin Even in that comment that you linked, its author doesn't say 'write type annotations for your local variables'. That is simply a mistake and not how TS is supposed to be used. Function signatures (except for inline callbacks) are a different matter. A variable might need a type annotation only in one rare case: when you're sure that the inferred type is not what you need.

**Comment by yuriykuzin** [comment]
@thorn0 Good point. I have to give it a try.

**Comment by yuriykuzin** [comment]
@evilebottnawi Yes, you can see it in a playground:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBLNBBKATwGUBXMMONNAM1IBs8Z4BbABxgBIlMB5AIzRwATgDcAhv3pwAPPwgRp4qAD5MAXkwwAFrgB0AfTQQWcALJwdEACYB1bDoAy0AOYA5caYAUASgDcADpQIAA0IBAc2OjIoOLCwhAA7gAKcQhoyCDiohDY1qEg-MLiYADWlsRsJdhQLsgwwqRwYdowLPS2uvBoVZTE6Q7Yog6EmWDUBTVCwjDJxS4s4sg04vRCYQBWaAAeAELFZRWecI41cMur6yBb28Q1LtIAiqQQ8BdrzSBVwtOZMIRsKhgYTYDgFNgg2D2aw6ZAADgADGEIRAhLZimxMhCqCJROcwgBHF7wOYRDIocRoAC0UDgcGs9IKwjgROwzLm4gWSyQKw+YSELGw9UanzQ9yexPOPMunxgkmhsKQACYwg1xNh6PcAMImRaZKDQfEgUhCAAqknJvKEAF9rUA
