### ISSUE TITLE
[Typescript] [Javascript] Inserting {" "} when breaking TSX/JSX into new lines.

### ISSUE THREAD

**Issue by jared-w** [prettier/prettier#5693]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwHIdTy6BuAHSg8igGcCBBTJiREmMAHQAxAK5RyqaAGEa2KAhgAeYAF8AfPgC8+ABQBKQ-o0ATVADd8YADYkePAHIl0cA2xCDMvpYAFqRWcDgOzq4eXj5+QgC0ISRhOIH4ACpwAB4EGgD0yamW+Ta2uuycatnYePhhFCTSjgJClSAANCAQmDAKvMigJDjUAO4ACsMIPMggJLYQqFadIABGOGQA1nAwAMqYZKhQAObIMDjScF1BMOiOAOpBqPA8B2Bwu9PPds8AnrNgVwrI48cIwcYbY7oEjIRqOUFdABWPGyACENmBtntPHAADJHOCwkjwq4gZHZXZHY6OOAARWkEHgRJJXQOOFBOFmMF+mDgPDAOFQvRWmEFsHuSxgQWQAA4AAys6ig+4bTCzUV88K2QldRgAR2kqEYEJIUJhSDhCJAoPQqDOF1JPCpNPpjMJFuJVpgJFWEqsUuQACYuucSKhHFTlOhobMoNAdSBpKCMj6Zh6SdptEA)
```sh
--parser typescript
```

or

```sh
--parser babylon
```

**Input:**
```tsx
import React from 'react';

const App: React.FunctionComponent<{}> = () => <div className="App"> <header className="App-header"> Text </header> </div>;

export default App;

```

**Output:**
```tsx
import React from "react";

const App: React.FunctionComponent<{}> = () => (
  <div className="App">
    {" "}
    <header className="App-header"> Text </header>{" "}
  </div>
);

export default App;

```

**Expected behavior:**

```tsx
import React from 'react';

const App: React.FunctionComponent<{}> = () => (
    <div className="App">
        <header className="App-header">Text</header>
    </div>
);

export default App;
```

---

Note: You can observe the same behavior with the equivalent JSX program (same input just no type annotation).

Note 2: The issue will disappear if you wrote the jsx with no spaces, eg `<div><header>...` or if it's already on multiple lines somehow, so it's a bit of an edge case to be sure.

**Comment by jared-w** [comment]
Issue [#201](https://github.com/prettier/prettier/issues/201) appears related but in the opposite direction. However, it involves jsx inside of text, not text inside of jsx.

**Comment by SimenB** [comment]
That's the correct transformation. See how Babel transpiles your input: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAggBwQLhgJQKYENhQHQBiArmLgJbgDCIAtguBmFADwDeAvgHwwC8MAFAEpe3ZgBMyANxjAANlggQAclhoYeAIkQINogBbYxGAE4z5ilWs3aAtAaxHjumABUMAD1jMA9PcejvCUlOAG4AKCA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=react%2Cflow&prettier=true&targets=Node-6&version=7.0.0-beta.55&envVersion=7.0.0

**Comment by jared-w** [comment]
Huh, good to know then; it's certainly a bit surprising although, thinking of the transformation in general, it's basically the only sane thing you can do.
