### ISSUE TITLE
brackets config to be in te same line

### ISSUE THREAD

**Issue by onorax** [prettier/prettier#5695]
I'm trying to config Prettier, but i can't find where i can specified that i want brackets in te same line

**EX:**

**INPUT:**
![image](https://user-images.githubusercontent.com/15808062/50538797-750a0b00-0b5c-11e9-8dd6-3da55c6da916.png)

  
**OUTPUT:**
![image](https://user-images.githubusercontent.com/15808062/50538799-84895400-0b5c-11e9-8543-0b6459d41203.png)

**As i want:**
![image](https://user-images.githubusercontent.com/15808062/50538800-8d7a2580-0b5c-11e9-9090-b19a697aae98.png)

Where can i find this configuration?

Thanks!

**Comment by j-f1** [comment]
Prettier’s style is to put the `{` on the same line, as in your input. Are you sure you don’t have another formatter running in your editor?

**Comment by aboyton** [comment]
Looks like PHP to me. See https://github.com/prettier/plugin-php/issues/107 and  https://github.com/prettier/plugin-php/issues/120

This behaviour is reason enough for me to not use Prettier for PHP. Last I checked the option isn’t available yet despite many people wanting it.
