### ISSUE TITLE
standalone formatAST errors with "Cannot read property 'charAt' of undefined"

### ISSUE THREAD

**Issue by Gregoor** [prettier/prettier#5696]
**Environments:**
- Prettier Version: 1.15.3
- Running Prettier via: API

**Steps to reproduce:**
1. use babel/standalone with babylon and a valid AST
2. call __debug.formatAST

https://codesandbox.io/s/j7jr8q3025

**Expected behavior:**
Code is generated without error.

**Actual behavior:**
`Cannot read property 'charAt' of undefined` is thrown

(I guess I shouldn't use __debug functionality, but I'd really like to use this one. I'd gladly help to make this work but tbh I'm a bit lost in the codebase and don't know where to start.)

**Comment by ikatyang** [comment]
As you noticed, it's not part of the public API so it's not recommended to use it and it may be changed in the future without further notice. But if you'd still like to use it, you need to pass `originalText` to get it work.

```js
const code = 'var n = 23;';
prettier.__debug.formatAST(parse(code), {
  parser: 'babylon',
  plugins: [babylon],
  originalText: code,
});
```

**Comment by Gregoor** [comment]
Thanks! That's helpful. For my use-case I only have the AST (and there would be some nodes without locs). Do you think it's reasonable for me to look at making formatAST work without the originalText or would that require major rearchitecting?

**Comment by j-f1** [comment]
It works if you pass `""` as `originalText`: https://codesandbox.io/s/vv46x943m5

**Comment by ikatyang** [comment]
It could be dangerous since we sometimes need the `originalText` to get some informations that does not exist in the AST, [multiline objects](https://prettier.io/docs/en/rationale.html#multi-line-objects) for example. You may be interested in #4685.

**Comment by Gregoor** [comment]
Oh neat! That's good enough for my use case. Thanks for the help (and for prettier ❤️ 💐 )
