### ISSUE TITLE
[TS] Should add some whitespacing to make it easier to read the code

### ISSUE THREAD

**Issue by justindra** [prettier/prettier#5706]
It would be great for prettier to add some whitespace to make it easier to read the code and make it look pretty for interfaces and classes in TypeScript

**Prettier 1.15.3**

**Input:**
```ts
export interface IEntityBase {
  readonly id: string;
  readonly createdAt: number;
  permitted: TOperation[];
  [otherProps: string]: any;
}

export class Management {
  public Account: Account;
  public AccountApproval: BaseEntity<IAccountApproval>;
}
```

**Output:**
```ts
export interface IEntityBase {
  readonly id: string;
  readonly createdAt: number;
  permitted: TOperation[];
  [otherProps: string]: any;
}

export class Management {
  public Account: Account;
  public AccountApproval: BaseEntity<IAccountApproval>;
}
```

**Expected behavior:**
```ts
export interface IEntityBase {
  readonly id:          string;
  readonly createdAt:   number;
  permitted:            TOperation[];
  [otherProps: string]: any;
}

export class Management {
  public Account:         Account;
  public AccountApproval: BaseEntity<IAccountApproval>;
}
```

**Comment by kachkaev** [comment]
Hi @justindra! This approach may have more cons than pros. Imagine you want to add  
`public f42: string;` to:

```ts
export class Something {
  public a: string;
  public b: string;
  public c: string;
  public d: string;
  public e: string;
}
```
This will result quite a massive diff, which is unwanted:

```diff
export class Something {
-  public a: string;
-  public b: string;
-  public c: string;
-  public d: string;
-  public e: string;
+  public a:   string;
+  public b:   string;
+  public c:   string;
+  public d:   string;
+  public e:   string;
+  public f42: string;
}
```

I see your point, however I don't believe that what you're suggesting will work well for the real code.

Despite that misaligned types are a bit harder too read compared to the aligned ones, code highlighting that editors provide by default make common cognitive tasks not so painful.

**Comment by justindra** [comment]
Good point on the big diff @kachkaev. I guess it depends on your preference. I personally would prefer to have the aligned types with the occasional bigger diffs, so it's easier to read in general with or without an editor.

I guess another option would be too manually do it with a bunch of `// prettier-ignore` everywhere. Or once prettier supports a block-ignore similar to it does in markdown.

**Comment by lydell** [comment]
Hi! There have been several requests for this kind of alignment in the past, but we've decided not to do it, mostly because of the big diffs. Thanks for the suggestion!
