### ISSUE TITLE
Typescript formatting forces an empty case for discriminated unions

### ISSUE THREAD

**Issue by alextreppass** [prettier/prettier#5709]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPAEwgGUIBbOGAC3KgHMAKCDGAM5I8wADpQ8hCBGEAxaQBpxAXzwAyPNzES8jCNTjCA5AEMjSqKoA+I8ZL0HjAI3N28Tk9mEAhTxeUAlAG2EgD0oXgCMEQEBHgq4iAKIHwU0ALIoJ7YEADuAAqeCBkoJgBuEOTUSSBO2CZgANYsdBgNHJzIMNhEcMmsMIwANgDq7PACbWBwdMXkFGXzAJ7I4AIZyRwCcLj59ZyMJsgEJkPbyQBWAmje9U0tJswAMhxwx6fnIFdodB1DcABFIgQeDvM59EBtbDbbCrGBLDBwARgbDkfg1DCo2AjKpsZAADgADMlMRBtiN6hhVpikTsym9ktg4ABHIjkJl7EwHI5IE7g5LbRjkLo9CECP6A4Gg3kfCEwExOHHUPFIABMyW6JnIQw6AGEmIdVlBoAyQERtgAVBUlPnbZTKIA)

```sh
# Options:
--parser=typescript
```

**Input:**
```ts
export function doSomething(opts: {
  foo: Foo,
} & ({
  mode: 'a',
} | {
  mode: 'b',
  bar: Bar,
})) {
 // stuff 
}
```

**Output:**
```ts
export function doSomething(
  opts: {
    foo: Foo;
  } & (
    | {
        mode: "a";
      }
    | {
        mode: "b";
        bar: Bar;
      })
) {
  // stuff
}
```

**Expected behavior:**
```ts
export function doSomething(
  opts: {
    foo: Foo;
  } & ({
        mode: "a";
      }
    | {
        mode: "b";
        bar: Bar;
      })
) {
  // stuff
}
```

Is starting with an `| {` intentional?

Thanks

**Comment by j-f1** [comment]
Yes — TypeScript will ignore it.

**Comment by alextreppass** [comment]
Thanks
