### ISSUE TITLE
Drop support for old Node.js versions

### ISSUE THREAD

**Issue by brodybits** [prettier/prettier#5711]
* Node.js 4 (#3919)
* Node.js 6 maintenance will end in April (see <https://github.com/nodejs/Release#release-schedule>)
* Node.js 8 maintenance will end in December (ibid)

This would need to be done in one or more major releases, such as 2.0 (#3503).

**Comment by evilebottnawi** [comment]
@brodybits let's close this in favor https://github.com/prettier/prettier/issues/3919? include drop node@6
