### ISSUE TITLE
Installing the newest version on the master branch in VSCode

### ISSUE THREAD

**Issue by mortenmoulder** [prettier/prettier#5712]
So I tried searching, but I honestly couldn't find a related "issue". One of my issues was fixed here: #5596 which honestly is a dealbreaker for me. I want that fix now, instead of waiting for it to be released in the Visual Studio Code extension "store".

How do I go about doing that? I'm not even getting the newest master branch updates, if I install Prettier using npm or yarn.

**Comment by j-f1** [comment]
Does installing `prettier/prettier` with npm or yarn fix the issue?

**Comment by mortenmoulder** [comment]
Unfortunately not, @j-f1. When I simply do `prettier file.html` it won't output the desired HTML. Example of my HTML:

```
<header>
    <p>Test</p>
</header>
```

My output:

```
<header><p>Test</p></header>
```

and if I do the output as the input, the output is the same. However, if you check out the [Playground link](https://deploy-preview-5596--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAFnAhgEzgJwD4AdKAAjNQAdCAVOAZxlQHobTXNcDCQAaEBCowAltAbJQWfPggB3AArSEElFgBuEETn4gARvixgA1nBgBlKkZFQA5shj4ArnAHoYAWwA2AdXQj4BiswOHMVAJF1AIBPZHAGCQEbBgIYBUNbDyxkADMsLxSBACsGAA8AIUMTM3MsDzgAGRs4XPzCkBLS8xtbLzgARScIeFaC1xArfBT8OPdvXSp8GxgfbRh0ZAAOAAYBRYgUn0MqOMXGAnUWgXw4AEcnERv0rEzspDyxgRSPEQdncYYPT6g2GLXebXGMCwelWOHWyAALAJHFgRF4egBhCAeLJxKDQK4gJwpWjQ1QfFIAX0pQA) you can see it works in that `deploy-preview-5596` version (the PR I linked in the post).

I assume that the PR was merged into the master branch, as that is what it says here on GitHub:

![image](https://user-images.githubusercontent.com/1304665/50665312-6a160700-0fb0-11e9-8b14-ab3bbbfa5dba.png)

**Comment by lydell** [comment]
@mortenmoulder Are you sure that `prettier file.html` runs the prettier you installed?

**Comment by mortenmoulder** [comment]
@lydell I can't really see why it shouldn't.

```
$ npm install -g prettier
$ prettier file.html (wrong output)
$ npm uninstall -g prettier
$ prettier file.html (not recognized as a command)
$ npm install -g prettier/prettier
$ prettier file.html (wrong output)
```

**Comment by ikatyang** [comment]
I guess you're running into some cache issues? I just tried it on master and it did work.
