### ISSUE TITLE
Preserve indentation (blank space) on empty lines

### ISSUE THREAD

**Issue by anishmittal2020** [prettier/prettier#5713]
In the following example Line number 2 is indented with 2 blank space (just before block code). But Prettier removes those blank space. These spaces are important, as latter if we wish to decrease the indentation its easier to do.

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAKkwUQB4CGAtgA4A2c2SAOlOurfQAYtEEDWcj6e6SAvOgBmECNwCefQQBIAFHgCU6AEYEATt14D0ZAvA110LJrRAAaEBBIwAltADOyUOrUQA7gAV1CRygIA3CBsAE3MQZTUCME4YAGUSKJsoAHNkGDUAVzgLAAsYIjIAdRybeHsEsDhYn1Kbf1LxZHB7Rwsk+zg1GA9I5LZkIQIyDosAK3s8ACFI6Lg44jgAGSS4AaGRkHG8WKTkigBFDIh4NeHskAS1DrUmtjV2YPcoMJI1JJhCkJgc5AAOAAYLK8IB1CpESE1XnBrv5VhY1HAAI4ZGwInoEPoEU4bDpEGxpTLney7A5HE5IQZnCwwAjKT7Bb7IABM1MiNjIuwAwhAiP0UFBoHCQBkOgAVWm+SkdAC+0qAA)
```sh
--parser markdown
```

**Input:**
````markdown
- **Example**:
  
  ```make
  x := foo
  y := $(x) bar
  x := later
  ```

````

**Output:**
````markdown
- **Example**:

  ```make
  x := foo
  y := $(x) bar
  x := later
  ```

````

**Expected behavior:** See Input

These spaces are important, as latter if we wish to decrease the indentation its easier to do.

For example: If we have 

````markdown
- A
  - B

    ```python
    CODE
    ```
````

and if we want to decrease the indentation to get the following

````markdown
- A
- B

  ```python 
  CODE 
  ```
````

We can select multiple lines by having multiple cursors and decrease the indentation in a single go. If in between we have empty lines , we can't do it in a single step.

**Comment by lydell** [comment]
In the input there's two spaces on line 2 (which is otherwise empty), but they're not present in the output – is that what you mean? Why are those spaces important to you?

**Comment by anishmittal2020** [comment]
> In the input there's two spaces on line 2 (which is otherwise empty), but they're not present in the output – is that what you mean? Why are those spaces important to you?

These spaces are important, as latter if we wish to decrease the indentation its easier to do.

For example:

````markdown
- A
  - B

  ```python
  CODE
  ```
````

**Comment by lydell** [comment]
1. Select all the lines you want to dedent.
2. Press the dedent keyboard shortcut in your editor.

Does that not work for you?

**Comment by anishmittal2020** [comment]
Thank you I wasn't aware of this!
