### ISSUE TITLE
Is it possible to preserve asterisk for italics?

### ISSUE THREAD

**Issue by anishmittal2020** [prettier/prettier#5715]
Is it possible to preserve asterisk `*` for italics (rather than getting converted to `_`)?

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqAEnANliqQA0IEADjAJbQDOyoAhgE4MQDuACowjSnQG4TkAJoRAAjBnTABrODADKJSeSgBzZDAYBXOEQAWMALZYA6rvLwqisHDldz5XuYCeycFRpFlVOAxhsJKgZ0yABmdFjeRABWVAAeAEIS0rJydAZwADLKcKHhkSAxsXLKKlhwAIqaEPC5ETogigzeDK5BDFKCrFAiJAzKMMZCMLrIABwADES9EN7GEiSuvXDNvDlEDHAAjprkG-50gcFIYXVE3gbk6lr1VCVlldU5x3n1MHSig4LDyABMRBp0chYEoAYQgBiCrig0DWIE03gAKu9uCdvABfNFAA)
```sh
--parser markdown
```

**Input:**
```markdown
*Hello*
```

**Output:**
```markdown
_Hello_

```

**Expected behavior:**
See Input

**Comment by lipis** [comment]
No there is no option for that.. we went with the most popular one if I remember it correctly
