### ISSUE TITLE
Not sure why this lib is included in my gatsby project, but is not transpiling the arrow function to proper functions

### ISSUE THREAD

**Issue by hackhat** [prettier/prettier#5716]
Hi!

I was wondering why when I use this lib with babel is not transpiled to normal es5 functions?  If is similar to this issue, do you have any solutions? https://github.com/sindresorhus/query-string/pull/148

Thanks

**Comment by hackhat** [comment]
Somehow gatsby with typescript includes all node_modules, but that's not the problem. 

So basically this library has some `=>` arrow functions and when I transpile to es5 it keeps the arrow function. Not sure why.

**Comment by duailibe** [comment]
Without a repo to reproduce there's nothing we can do. And even with one, this sounds like it's not a problem with Prettier itself.

**Comment by hackhat** [comment]
I will close, but basically, the other library that has this issue is because the author decided to disable transpilation of the code of his library.
