### ISSUE TITLE
Chained methods indented for logical readability are being un-indented

### ISSUE THREAD

**Issue by nas5w** [prettier/prettier#5722]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAFAcgMQEt4C2AzpgJQA6UABFQHQBmuUAJlrUXADZxjzNmUaNWgAtcAcxGcJImOgrUhtBKwXDGLNhAAOCAYuEBXbcwCG8AMIRDseQG5BQkABoQOmLmhFkoUwCc-CAB3AAV-BG8UUwA3CFxmFxAAIz9TMABrOBgAZW00pnFkGD9DOFdZAk4AdTF4IjywOGyI-Fxo-ABPZHAib1cmDj8YENTxAlNkelNODlcAKyIADwAhVIys7NMCOAAZJjhJ6dmQBcXsgu4ARUMIeEOZspA8v0HupNMkjs5oRO0-JhgVXiMBEyAAHAAGVx-CAcKqpbTdP5wQbRA6uPxwACOhlwmJGpjGEyQUwerg4BFwRRKjyIFzg11uBxJR0eMA+QOYIOQACZXMVTLhpFBxFYCONulBoOiQIYOAAVD6RUkcAC+qqAA)
```sh
--parser babylon
```

**Input:**
```javascript
$('#items')
  .find('.selected')
    .highlight()
    .end()
  .find('.open')
    .updateCount();
    
```

**Output:**
```javascript
$("#items")
  .find(".selected")
  .highlight()
  .end()
  .find(".open")
  .updateCount();

```

**Expected behavior:**
This example is taken from [Airbnb's style guide](https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v15.1.0/README.md#whitespace--chains). Essentially, since the `highlight` and `end` methods are related to the `find` method, they should be indented for readability. Same goes for the `updateCount` method. This is obviously challenging to automate since Prettier has no way of knowing these logical relationships, so I'm wondering if there should be an option to turn off chained method indentation formatting using configuration.

Thanks!

**Comment by lydell** [comment]
I'd say airbnb should encourage writing such code in a more obvious way instead:

```js
const $items = $('#items');
$items.find('.selected').highlight();
$items.find('.open').updateCount();
```

**Comment by nas5w** [comment]
I'd like to withdraw this issue.

After your comment I did some more researching, and found [this comment](https://github.com/airbnb/javascript/issues/1566#issuecomment-331355223) in which an airbnb developer appears to walk back the recommendation for the nested-style indents in favor of more readable code (much like you recommended). I'm surprised they never updated their style guide accordingly. Thank you for the discussion!
