### ISSUE TITLE
Docs: broken relative links

### ISSUE THREAD

**Issue by nmussy** [prettier/prettier#5740]
There are currently several broken links in a few different pages. They all reference other pages relatively (e.g. `[api](./api.md)`.

Here are a few examples:
* https://github.com/prettier/prettier/blame/master/docs/cli.md#L133
* https://github.com/prettier/prettier/blame/master/docs/options.md#L313

Links without the redundant `./` work fine:
* https://github.com/prettier/prettier/blame/master/docs/cli.md#L133

I can make a quick PR removing them if needed.

**Comment by j-f1** [comment]
Awesome, please do!
