### ISSUE TITLE
spaced-comments not working.

### ISSUE THREAD

**Issue by austonpramodh** [prettier/prettier#5755]
**Prettier 1.15.3**

**Options:**
"trailingComma": "all"

```
**Input:**
//comments
```
```

**Output:**
//comments
```
```
**Expected behavior:**
// comments
```

I need to have a space between "//" and "comment". How do I get spaced-comment?

**Comment by lydell** [comment]
Prettier does not touch the contents of your comments, because it does not know what's in there (it could be anything). Instead, you can use the [spaced-comment](https://eslint.org/docs/rules/spaced-comment) ESLint rule.
