### ISSUE TITLE
preserve line breaks for multiline Imports, functions

### ISSUE THREAD

**Issue by keslavi** [prettier/prettier#5756]
can prettier respect line formatting on import statements or multiline statements?  I'm using VS Code as IDE

**Input:**

import {
  mercury, 
  venus,
  mars, 
  earth
}

  export const actions = 
    act1
    | act2
    | act3;

**Output:**
  //creates a line length issue and merge problems in git
  import {mercury, venus, mars, earth} 
  export const actions = act1 | act2 | act3;

**Expected behavior:**

import {
  mercury, 
  venus,
  mars, 
  earth
}

  export const actions = 
    act1
    | act2
    | act3;

**Comment by evilebottnawi** [comment]
Issue is not readable, please open new issue
