### ISSUE TITLE
Array as function argument is kept on one line

### ISSUE THREAD

**Issue by AaronGillBraun** [prettier/prettier#5758]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBzArgGwA4DoYCGAzgNYAUA5AEboCWmAJkgZphQDQAEGOu2BAJxaY4mMgG0AOlE6zO1OoyTQ4HTtLnya9JjADuENRrkKdSGAAsBcVe2OzTSgGYR0AjsYC6ASmneA3CDsIBDYMLTQRMigggIQegAKgghRKAQAbhC0DEEgVEJgJHAwAMr8YLRQqMgwAuhwwRYwALaYAOoWtPBE5XAlKV206V0AnsjgRFHBlURwAjAJQqjNBMhOLLPBAFZEAB4AQgVFpQTNcAAylXBrGw0gO7sllagiAIroEPA3mJsg-AKzATjKgEKgjTDQXLYASVGBtbKWZAADgADMFoRBZm0hNhxtC4ID0tdgtYAI50ayLAjLVZIdY-O6zZq0Gp1RnPN4fL5027BQhUeEMRFIABMfKE9GeAGEIM0VuMoCpcuhZgAVUGpemzAC+2qAA)
```sh
--parser babylon
```

**Input:**
```jsx
gulp.task('build:all', gulp.parallel([
    'build:one', 
    'build:two', 
    'build:three',
    'build:four',
  ])
);
```

**Output:**
```jsx
gulp.task(
  "build:all",
  gulp.parallel(["build:one", "build:two", "build:three", "build:four"])
);

```

**Expected behavior:**

In cases like this, it makes much more sense just to split at each array element. The above formatting looks alright if there's only one argument inside the array, but anything above that doesn't look good. Prettier does a pretty great job at making balanced and readable code, however the above formatting is far from balanced. I can get prettier to do what I want by setting `--print-width` to `60`, but for obvious reasons, this is not a solution.

*Ideal formatting*
```jsx
gulp.task(
  'build:all',
  gulp.parallel([
    'build:one',
    'build:two',
    'build:three',
    'build:four',
  ])
);
```

**Comment by lydell** [comment]
To be honest, I think the Output is very readable. ¯\\\_(ツ)\_/¯
