### ISSUE TITLE
Endless loop on HTML parsing

### ISSUE THREAD

**Issue by prettydiff** [prettier/prettier#5759]
Prettier HTML parser is producing an endless loop on current version.  All environment data and a stack trace is available on issue opened with the integration project:

https://github.com/Glavin001/atom-beautify/issues/2296#issuecomment-454413898

---
Also, I don't know if this will be helpful to the project down the line but the parser I have been working on is reaching maturity.  I will start working the next major version tonight and hopefully have it wrapped up before end of month.  With the next major version the demo page will be something like https://sparser.io/demo/ but for now the current demo page is https://prettydiff.com/parse-framework/runtimes/browsertest.xhtml?wrap=50

**Comment by ikatyang** [comment]
I'm not sure what did you mean the _endless loop_, can you fill in the issue template?

**Comment by duailibe** [comment]
From https://github.com/Glavin001/atom-beautify/issues/2296 it's not a endless loop, Prettier just threw an exception. Please share the code that's causing this error.
