### ISSUE TITLE
plugins options support plugin instance too

### ISSUE THREAD

**Issue by Kingwl** [prettier/prettier#5760]
**Environments:**
- Prettier Version: 1.15.3
- Running Prettier via: 
- Runtime: 
- Operating System: 

**Steps to reproduce:**

I wanna to build a app target web(by standalone and external modules) and node,
I tried to donot explicit set plugin by explicit behavior in my code, 
but the plugins option of standalone accept plugin instance, the otherwise accept a path,
Could we accept the plugin instacne too in the normal version? that maybe only a typeof pred statement but very helpful to me!

**Expected behavior:**

**Actual behavior:**

**Comment by ikatyang** [comment]
Plugin instance should be supported but it seems we forgot to handle it.

https://github.com/prettier/prettier/blob/8ac0a731a42c9e7aeb13c5550ded0a1ddf60adee/src/common/load-plugins.js#L27-L40
