### ISSUE TITLE
parens incorrectly stripped from typecasts in function argument array destructuring, causing syntax error

### ISSUE THREAD

**Issue by rattrayalex-stripe** [prettier/prettier#5764]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTACgG0BDAGiICMlMAxCCASgF0n8A+TYAHSk0wAnODACug-qUwBqTFT4BfPn0hQMmAJ74iZSoUI1MpKBqa0GzNp258BwsRKMy5ikORAQADjACW6ZKCkgoIQAO4ACkEIaMggpABuED4AJm4gVIKkYADWIgDKnlk+UADmyDCConDuABYwALYANgDqNT7waIVgcHnR7T7x7RqxYGgx7sVocIIw4Zkl9aTIAGakjVPuAFZo2ABCmTn5pPVwADLFcCtrGyDb2HnFJY1wAIqiEPBX69UghYJTgliVFIVA0jWgaU8gmKMGaKRgNWQAA4AAzuKEQKbNTKeWJQuAA+KXdzCACOoh8wjmpAWSyQq2+7im9R85UqPzQj2ebw+l3p1x+MBBcOSCOQACZ3BVSD5Go8AMIQeqLWJQaDEkCiKYAFRBMX53wUCiAA)
```sh
--parser babylon
```

**Input:**
```jsx
const x = ([a, (b: Foo)]) => {
  return a + b
}

const y = ([a, ((b: any): Foo)]) => {
  return a + b
}
```

**Output:**
```jsx
const x = ([a, b: Foo]) => {
  return a + b;
};

const y = ([a, (b: Foo: Foo)]) => {
  return a + b;
};

```

This causes syntax errors in Flow: 

https://flow.org/try/#0MYewdgzgLgBAHjAvDAFAbQIYBoYCMBcMAYiCALoCUSAfDAN4BQMMATgKZQCuLYMGMAajwBuBgF9RDUJFgBPJKkw4UBYqUIkQFSjXpNWHbr35DcoiQyA

**Expected behavior:**

same as input:

```jsx
const x = ([a, (b: Foo)]) => {
  return a + b
}

const y = ([a, ((b: any): Foo)]) => {
  return a + b
}
```

**Workaround:**

cast in function body:

```jsx
const y = ([a, b]) => {
  b = ((b: any): Foo);

  return a + b
}
```

**Comment by thorn0** [comment]
Flow 0.124.0 can't parse this: https://flow.org/try/#0MYewdgzgLgBAHjAvDAFAbQIYBpUCMBcMAYiCAJQC6ZSAfDAN4BQMMATgKZQCurYMGMANQxcjAL6MgA
