### ISSUE TITLE
Support for Hive HQL, Spark SQL, and Presto SQL

### ISSUE THREAD

**Issue by ericsun2** [prettier/prettier#5765]
#2425
> There are countless ways to format SQL, and there are also countless dialects of SQL. I'm going to say this is out of scope for prettier.

Since the above 3 dialects are fully opensourced, the ANTLR grammars are available. And Hive and Spark's syntax are pretty much the same.

It will be a great feature for Prettier to add.

Thanks

**Comment by duailibe** [comment]
Hi! We only include languages if they are related to the realm of Prettier somehow (mostly web development).

I do think a formatter is useful so this would make a great Prettier plugin.

I'm closing this since we won't do anything, but feel free to continue to comment.
