### ISSUE TITLE
Pug support.

### ISSUE THREAD

**Issue by ispyhumanfly** [prettier/prettier#5767]
We use pug alot in our application. And yes, it's been around 2 years since pug-lint, pug-beautifier and pug-lint-vue have been updated. But they still work. I'm considering attempting to take over pug in general since it's such an awesome syntax for authoring application markup. We use prettier as the principle validator on most all of our code. I'd be willing to create this integration if someone would explain to me how...

**Comment by j-f1** [comment]
Check out our [docs on making plugins](https://prettier.io/docs/en/plugins.html). You can also check out [an example plugin](https://github.com/prettier/plugin-python) for some ideas. Best of luck and please keep us updated!

**Comment by rdhar** [comment]
Would be absolutely delightful to have a Pug plug-in for Prettier to allow complete formatting validation. Looking forward to this!

**Comment by ispyhumanfly** [comment]
Hi all, I have created https://github.com/flypapertech/prettier-puglint and https://github.com/flypapertech/puglint-config-puglint
