### ISSUE TITLE
Prettier formats a sensible one-liner into seven lines

### ISSUE THREAD

**Issue by mattrussell-sonocent** [prettier/prettier#5769]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcBuCYGUYQE5wB0ArgA4AmAhvABQCW5ANAAQD6hAZgDYQDuNZKvDws6UMAQC2mAGpw8AZzrQAlCoA6UEIxARSMZVAXJQlPHj4AFMwmMpKaCA20gARnkpgA1nGylPYgDmyDB4xHA6ABYwklwA6pF08Ar+YHBYtkl0aEkAnsjgCsY6YgryMJYegZKUyByUXGU6AFYKAB4AQh7evliU0gAyYnB1DU0grW1YQVxwAIrEEPCjjREg-oryBa6Urrk8WjqkeGIwcQwwkcgAHAAMRxZlcR6kBcdwZXgYLgQAjsR0AiVSjVWpIeqrHRlSR0EJhNZKKCBWYLJYjcFjNYwXbnciXZAAJh0oUodC4QQAwhBJDUClBoCMdMQygAVXZ2CFlAC+XKAA)
```sh
--parser babylon
```

**Input:**
```jsx
eventStore.update(id, _.flow(updater, incrementVersion))

```

**Output:**
```jsx
eventStore.update(
  id,
  _.flow(
    updater,
    incrementVersion
  )
);

```

**Expected behavior:**
Unchanged:
```jsx
eventStore.update(id, _.flow(updater, incrementVersion))

```

**Comment by duailibe** [comment]
Hi! This is because of #4172, after several requests, functions like `flow()` are in multiple lines now.

I personally prefer your input better than Prettier's output.

**Comment by duailibe** [comment]
I think we maybe should revisit this heuristic.

**Comment by sam3d** [comment]
Could this not default to being one-line (as long as it's within the character limit), but in the same way that an object can _always_ be made to be on multiple lines if a newline is added after `{`, could this be made so that it's possible with function parameters?

This would have the benefit of not affecting existing prettier code that has already been split over multiple lines.

---

**Input**

```javascript
eventStore.update(id, _.flow(updater, incrementVersion))
```

**Output:**

```javascript
eventStore.update(id, _.flow(updater, incrementVersion));
```

---

**Input**

```javascript
eventStore.update(
id, _.flow(updater, incrementVersion))
```

**Output:**

```javascript
eventStore.update(
  id,
  _.flow(
    updater,
    incrementVersion
  )
);
```

---

**Input**

```javascript
eventStore.update(id, _.flow(updater, incrementVersion), aReallyLongArgumentThatGoesPast80Characters)
```

**Output:**

```javascript
eventStore.update(
  id,
  _.flow(
    updater,
    incrementVersion
  ),
  aReallyLongArgumentThatGoesPast80Characters
);

```

**Comment by mpro7** [comment]
It looks weird also when in HTML files there are some pieces of Typescript code:

**input:**
```
<div class="valid" *ngIf="form.get('pieces').get([i]).get('weight').valid && form.get('pieces').get([i]).get('weight').touched">
  <img alt="Validity icon - valid" src="assets/common/images/icons/ValidIcon.svg">
</div>
```

**output:**
```
<div
  class="valid"
  *ngIf="
	form
	  .get('pieces')
	  .get([i])
	  .get('weight').valid &&
	form
	  .get('pieces')
	  .get([i])
	  .get('weight').touched
  "
>
  <img alt="Validity icon - valid" src="assets/common/images/icons/ValidIcon.svg" />
</div>
```

But this is just small example - it looks really weird when because of this file double or triple it's number of lines. Btw, is there any possibility to disable line wrapping by prettier?

**Comment by duailibe** [comment]
> is there any possibility to disable line wrapping by prettier

No, it's a core functionality of prettier and can't be disabled.
