### ISSUE TITLE
Use of nested decorators breaks

### ISSUE THREAD

**Issue by lougreenwood** [prettier/prettier#5777]
**Prettier 1.16.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgBo7AA6UOOAAgBSQC2ADgK7wAmlAlAHQBuEGMAlqjjs2JMgA8SAXxIgANCAh0B0TMlDoATpogB3AApaEalOh79m8kACNN6MAGs4MAMp17-KAHNkMTQzgFAAsYGlQAdSD+eEx3MDgXY2j+LmiAT2RwbCtPTDhNGH07Lxp0ZAAzdFQ8hQArTHEAITtHZxd0GjgAGU84CqqakHrxF08vIQBFBgh4furAkHdNPM1M63RrOFQrOk1PGHCLGCDkAA4ABgVdiDzwuzpM3bgVrj6FTTgARwZ+D6L0EplJCVeYKPI0fi+fwLTBjSbTWbAgYLGAbQ7MY7IABMCj86EEYwAwhAaKVMlBoG8QAw8gAVDYmEF5KRSIA)
```sh
--parser babel
```

**Input:**
```jsx
class X {
  @(computed().volatile())
  x
}

```

**Output:**
```jsx
class X {
  @computed().volatile()
  x;
}

```

Which is wrong and results in a JS exception in the application :(

**Comment by ikatyang** [comment]
The input is valid for both `decorators` and `decorators-legacy` but the output is only valid for `decorators-legacy`.
