### ISSUE TITLE
Map constructor entries being collapsed when they fit looks bad

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#5780]
**Prettier 1.16.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAZgSxgZwwFcoATOAJwwAcKdYMB3HUmACwB0oo5GMBZAIbUAFAG0uGDGICCAGgwAhALpzJ0gMIKAIqvViAogoBieqFLEBxBQAkzFgJIKAUvekBpBQBk3Y-goA5ZS5lAEoAbi4udAxSCDh8KAByGGw8YjJKGjoGZlZObl4BYXF9eSVfLQxdNXNpIwxTWotrDDtm6ScMVw6xTwwfXv8MIN6AeQUABV8ARQUAJWCoMMioEDkQCGoYHGh8ZFBBCgoIRkmjhH2UQQA3CBZ1kAAjCkEwAGs4GABlajf6ADmyBgFCIcA29HwlBgk1eAIAtoJkFhBAAbKEbABW+AAHopXh8vt9BPC4F56HBkWiMSA-hQoRRkM9BE8AJ6o6CPWj0GAAdRY7GQAA4AAwbWgQKG817UJm0BKUG6UjYUOAARyIOFVsMECKRSBR6PBICh8JwwNBxvwgNRcBmRAg8CpRo2MBZ-PyyAATK7XjhUYCNBB4YimVBoMqQEQoQAVFlXQ1QgC+SaAA)
```sh
--parser babylon
```

**Input:**
```jsx
// fits under print width
new Map([
  [A, B],
  [C, D],
  [E, F],
  [G, H],
  [I, J],
  [K, L],
  [M, N]
]);

// doesn't fit under print width
new Map([
  [A, B],
  [C, D],
  [E, F],
  [G, H],
  [I, J],
  [K, L],
  [M, N],
  [O, P],
  [Q, R]
]);

```

**Output:**
```jsx
// fits under print width
new Map([[A, B], [C, D], [E, F], [G, H], [I, J], [K, L], [M, N]]);

// doesn't fit under print width
new Map([
  [A, B],
  [C, D],
  [E, F],
  [G, H],
  [I, J],
  [K, L],
  [M, N],
  [O, P],
  [Q, R]
]);

```

**Expected behavior:**

Same as input

---

I'm thinking let's always break Map constructor entries like this across multiple lines as long as there's more than 1 entry. Any opinions against?

**Comment by lydell** [comment]
Fixed by #6694.
