### ISSUE TITLE
MDX parser cannot incorrectly parses React components used within markdown syntax in paragraphs

### ISSUE THREAD

**Issue by manovotny** [prettier/prettier#5781]
This isn't a regression in `1.16.0`. I was doing this before today's release.

**Prettier 1.16.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wCEIAbAEzirwF48AKASgYD4AdKTmAHhLZoAc3YAjSjTrw0-APSCRXHlAAqACwCWRPNrwBDKHnT6Athgpw8EAGYGCEc9AT4A+mLiaowvAFcitLpGRI5WmjD6FJpgeKb62ADWVBAA7kYp4ep4IaZWfOTUgXLsADR43IZ0+joAnhC+BIbZcHCu1lBgVnUNYBQQAXgw6mERUWBEZeF4GRQUeGLYcPoJQZDYi2AwFDXTw0YYizAwmnDYeDY4cTA64QB0ICUgEBjH0ETIoPFCKQAK8QjvFD6ABuEE0VAeIAW+jACTgMAAyhgYV5hMgYNhfHBHuoYKYKAB1LTwIjIzoIgHhTTA8I1ZDgIjvR5eAK4H7YfTCOLIGyRAKPABWRDQpA5sPhCLMcAAMl44Dy+diQEK0AjUZYAIq+CDwBUUfkgZHYVn00xUNCQg5eGAE8FDZAADgADI8Dv04ASORh6Qc4KzgfLHosAI6+TSLdmc7lIXn6pUBUyaPUGojquBanXypAYrGPCJiW1Ue1IABMeY5mii3gAwo5oyAoM5If44Kp9GJAbGAgBfbtAA)
```sh
--parser mdx
--no-semi
--single-quote
```

**Input:**
```mdx
export const Bolded = () =>
	<strong>bolded text</strong>

This is an example of a component _being used in some italic markdown with some <Bolded />, 
and as you can see_ once you close the italics, it will break incorrectly when prettier formats it.
```

**Output:**
```mdx
export const Bolded = () => <strong>bolded text</strong>

This is an example of a component _being used in some italic markdown with some

<Bolded />,
and as you can see_ once you close the italics, it will break incorrectly when prettier formats it.

```

**Rendered:**

As you can see, when it adds a completely blank line before the component, it will cause the italics to break and format the markdown / MDX incorrectly.

<img width="667" alt="screen shot 2019-01-20 at 4 25 17 pm" src="https://user-images.githubusercontent.com/446260/51445902-0f7aeb80-1cd0-11e9-9bb7-5216f4b5c720.png">

**Expected behavior:**

The completely blank line should not be there and the paragraph should read correctly and unbroken.

<img width="696" alt="screen shot 2019-01-20 at 4 26 59 pm" src="https://user-images.githubusercontent.com/446260/51445919-3df8c680-1cd0-11e9-9b5b-d49d6a0d81ce.png">

**Comment by ikatyang** [comment]
👉 https://github.com/prettier/prettier/releases/tag/1.16.1
