### ISSUE TITLE
MDX parser cannot parse HTML and React components in table cells when surrounded by markdown syntax

### ISSUE THREAD

**Issue by manovotny** [prettier/prettier#5782]
This isn't a regression in `1.16.0`. I was doing this before today's release.

I thought this might have been resolved with #5702, but it must go another level deeper.

This may also be related to the other issue I opened, #5781.

**Prettier 1.16.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wEkoAbASyjgGEIATOPAXjwApgwALKixtgQBfAJRsAfAB0oUmAB5IzCdz6MKQqMPkB6JXGmyoAHzwMKAVwC2UPAEY8p89dsAmRzNMBaL47w+PEzwAKmCAAwAlCAB3ezMmODDQvwBlCCsWeDQYADpA01DFBIko2PcGZl19CWTTNIy8LNz8kOD5cmpaCoNSvHKE3Q6aemLavHrM9GbjEAAaEAgMGCpoImRQAENsbBiABS2ENZQNgDcIKkY5kAAjbA2wAGs4GBSMe5oAc2QYbAs4eZ4MCsFAA6nx4EQ3mA4ClDlRlid4QBPZDgIhreY0IhwXC7O4fKwbZAAMw2FGx8wAVkQ0AAhO6PZ4pDYZAAywxJZIpIGpaBSnwocAAihYIPBOeT-iA3thsdhUVZGGgrhhsDQYCCLjAeMgABwABnmqog2JBdwwqNVcDlJzgVyEAEcLFQhHiNgSiUhSZL5tirFQJdyiALhaLxUgfn95jANtdNYxtchXNG7vxPgwrITUVBoHb5hZsQAVWNHb3Y4TCIA)
```sh
--parser mdx
--no-semi
--single-quote
```

**Input:**
```mdx
export const InlineCode = ({children}) =>
	<code>{chidlren}</code>

| Column 1 | Column 2 |
| -- | -- |
| **`Row 1 Code`** | Some text. |
| **<code>Row 2 Code</code>** | Some text. |
| **<InlineCode>Row 2 Code</InlineCode>** | Some text. |
```

**Output:**
```mdx
SyntaxError: Unexpected token (1:7)
> 1 | <code>
    |       ^
```

**Expected behavior:**

HTML and React components should be able to be used intermingled with markdown syntax in tables.

**Comment by ikatyang** [comment]
👉 https://github.com/prettier/prettier/releases/tag/1.16.1

**Comment by manovotny** [comment]
@ikatyang thanks for all your work on quickly addressing these MDX issues! ❤️
