### ISSUE TITLE
How to terminate STDIN on Windows

### ISSUE THREAD

**Issue by codenesium** [prettier/prettier#5787]
This is on Windows. Latest prettier release. 
I'm using a .NET process to send input to prettier with STDIN and also just from the cmd line using 

prettier --stdin function test(){}

but it doesn't write anything to the console and the process never exits. I've tried writing to the process with .NET but I don't know what the terminating character is supposed to be. I've tried Ctrl +Z and Ctrl + D. Am I missing something here?

**Comment by j-f1** [comment]
Does `echo 'function test(){}' | prettier --stdin --stdin-filepath foo.js` work?

**Comment by lydell** [comment]
It wouldn't surprise me if we have to manually add support for this on Windows somehow.

**Comment by lydell** [comment]
Just to be sure, is this what you're trying to do, @codenesium?

```
$ prettier --parser babel --stdin
test
^D
test;
```

**Comment by codenesium** [comment]
Does echo 'function test(){}' | prettier --stdin --stdin-filepath foo.js work?
This does work as expected @j-f1 and I will see if I can make this work in my project. 

Just to be sure, is this what you're trying to do, codenesium?
$ prettier --parser babel --stdin
test
^D
test;

@lydell Yes that's essentially I want to do. Pass code to be formatted via STDIN because I'm generating code in memory and I want to format it before I write it to disk because it's inefficient to write it to disk and then format it for my use case. I just want to pass the code without piping it.

**Comment by j-f1** [comment]
I don’t think we support code passed as command line arguments.

**Comment by lydell** [comment]
I don't get it – I thought the thing I showed with the `^D` and all only had to do with _manually typing in stdin_ (not sure if/why people do this, but I know it's possible). But you're talking about generating code in memory? And you _don't_ want to pipe it?

To me, it sounds like you're looking for this:

```
somehow-generate-some-js | prettier --parser babel
```

> I don’t think we support code passed as command line arguments.

Correct, since that's not very useful.

**Comment by codenesium** [comment]
@lydell I'm ok with piping it but it's not obvious on windows how to do that but I can research how to do it from my .NET app. this is what I've got so far. Just have to figure out how to echo a multi line statement without newlines and it should work.

```CMD /C echo import * as Api from '../api/models';
import BadgeViewModel from  '../viewmodels/badgeViewModel';

export default class BadgeMapper {
    
	mapApiResponseToViewModel(dto: Api.BadgeClientResponseModel) : BadgeViewModel 
	{
		let response = new BadgeViewModel();
		response.setProperties(dto.date,dto.id,dto.name,dto.userId);
		return response;
	}

	mapViewModelToApiRequest(model: BadgeViewModel) : Api.BadgeClientRequestModel
	{
		let response = new Api.BadgeClientRequestModel();
		response.setProperties(model.date,model.id,model.name,model.userId);
		return response;
	}
}; | C:\Users\Administrator\AppData\Roaming\npm\prettier.cmd es5 --stdin
```

**Comment by j-f1** [comment]
If you’re able to spawn Prettier, you might be able to stream the text to the running process.
