### ISSUE TITLE
CSS tag name lowercasing

### ISSUE THREAD

**Issue by chevallard** [prettier/prettier#5788]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZAhgIzgGwATAA6UhMAZtDALQDOAlgF5xJ4BMALANzEC+IANCAgAHGHWg1kodACcZEAO4AFWQkkp0ANwh0AJgJCYZ6MAGs4MAMrCTdKAHNkMGQFc4guzTgyYS4-YBbdGQydBwvQQArGgAPACFjMwtLdAC4VDs4ELCIkBsZLxlkEBowGklBYRk7GAB1PRgAC2QADgAGSvkvWuNhYqq4Qs0swRk4AEcXOjG-dEDgpFDw9xK4ALonVxX6Bxw4AEUXCHhs5cEYLHrdJuRWc+M6HDt7AGEIAKDiqGgRkBcvAAqWHUSy8PB4QA)
```sh
--parser scss
```

**Input:**
```scss
Label {
	font-size: 24;
}
```

**Output:**
```scss
label {
  font-size: 24;
}

```

**Expected behavior:**
```scss
Label {
  font-size: 24;
}
```

I am using prettier on a NativeScript project, which uses an Xml markup with some tag names similar to html but with uppercase names (like Label and Button). CSS is largely case-insensitive, so the styles still apply properly even with the incorrect lowercase tag names output by prettier, but it sure looks inconsistent when looking at the markup and the styles together.

**Comment by lydell** [comment]
@j-f1 Since you labeled this a bug, do you have an idea for how we could fix it?

**Comment by j-f1** [comment]
We could respect the input’s capitalization.

**Comment by 13k** [comment]
I have the same issue working with [Valve's Panorama UI](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Panorama), which also uses XML markup + (modified) CSS with custom elements named like `Label` and `Image`. Unfortunately, in Panorama's case, case sensitivity is relevant, so a stylesheet containing a rule `#element image` throws an error by the game engine.

Using prettier to format stylesheets in an editor with format-on-save becomes impractical. Right now I'm using VSCode and every time I'm editing a CSS file that contains element tags in rules, I have to run "save without formatting".

Another workaround is to add classes to elements that I write myself, so the stylesheet doesn't refer to the element tag.

There's a case where I don't have any control, though, which is styling built-in elements provided by the game. For example, `ToggleButton` elements will internally render a `Label` element with no class, so it's only possible to style the `Label` element by explicitly referring to the element tag, which prettier will reformat as `label` and cause an error.

I don't know exactly how prettier would deal with this situation. I strongly agree with the "less configuration as possible" philosophy (or even zero configuration, like `gofmt`) and I also agree with lower case formatting of element tags for platforms where case sensitivity is not relevant.

I guess the only way is to add configuration for this? I'm not sure.

**Comment by evilebottnawi** [comment]
`Label` === `label`, i don't think it is bug

**Comment by 13k** [comment]
Like I said, there are platforms where `Label !== label`. Panorama is one of them:

```css
label {
  font-size: 14px;
}
```

![20190905-163703-dota2](https://user-images.githubusercontent.com/4762/64361120-56f58400-cfe2-11e9-8244-3ce2d225f499.png)

**Comment by evilebottnawi** [comment]
It is violate CSS spec, better open issue in `Panorama`

**Comment by lydell** [comment]
I'm not sure it is necessarily violating the CSS spec, actually. See: #3317

Lowercasing of HTML names was added in: #3954

**Comment by evilebottnawi** [comment]
According spec `label` === `Label` === `LABEL` === `lAbEl`

**Comment by 13k** [comment]
> The case sensitivity of document language element names, attribute names, and attribute values in selectors **depends on the document language**.

(emphasis mine)

That's interesting. Sounds like a bug in the spec (I'm half-joking).

Anyway, the spec explicitly states that casing is dependent on the document language. Isn't this important enough to consider having a configuration for? Prettier can't know the document language. Right now it's assuming it's either HTML or SVG.

**Comment by evilebottnawi** [comment]
We support officially CSS/Less/Sass, you should not use prettier on other languages because we doesn't support them, you can create custom plugin for this. We can't support all subsets of the language of which there are hundreds, also pretter can potentially break the code

**Comment by chevallard** [comment]
According to the CSS spec, the document that the CSS is being applied to determines case sensitivity. The CSS file has no indication of which type of document it is being applied to. This is an issue when we are using the supported CSS/Less/Sass.

**Comment by lydell** [comment]
> The CSS file has no indication of which type of document it is being applied to.

I know there's some namespace stuff in CSS which could potentially be relevant here, but I don't know.

**Comment by evilebottnawi** [comment]
@chevallard can you provide link on this

**Comment by chevallard** [comment]
https://www.w3.org/TR/selectors-3/#casesens

The relevant quote:

> The case sensitivity of document language element names, attribute names, and attribute values in selectors depends on the document language. For example, in HTML, element names are case-insensitive, but in XML, they are case-sensitive

**Comment by Stephen2** [comment]
I think this might be causing prettier to break some styled components in react-native for this project I'm looking at:
```
import styled from "styled-components/native";

export const Foo = styled.Image`
  borderWidth: 4px;
`
```
comes out as `borderwidth` and throws an error

Playground: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcYBPAGzgBN8AzHCdfAHRGPKoFpItoEZCA9FACGMVADc4LANxMocuAA9sefJCjF8AMQgR8AXiKkKlAHQBJdMIDmcAAZz8+AEa5KcHAHVUlGAAskfAAWTEVZKAcoEAAaEAhMMWhCZFBhHHoAdwAFNIRklGFxCB8YkGccYTAAazgYAGVMStQoa2QYHABXOFi-GHQyTz9UeEJGsDg6vOGJYZJkcEJk2ObCDxgsiusrZBphMlXYgCtCRQAhCurauuF0OAAZZrgdvYOQY8U65usKAEUOiHgz323RAjRwqxw82cwmc5GgpUwOGaMG8vj8yAAHAAGWKIiCrTwVTDzRFwCGSUoAR3+8A28XyIGEhA4UDgVCopRwcGpqC5Gxs2yQu2BsVW6FQbU6IMIX1+NKeQpeIJgMNR-mQACZYu1hKgyF8AMIMQUgKC8UodVYAFRh+WFqwAvg6gA

**Comment by Stephen2** [comment]
actually, I'm gonna raise separate ticket for this, sorry for the noise

**Comment by evilebottnawi** [comment]
@chevallard maybe we can detect what you use css for html or for xml, do you use some declaration for this?

**Comment by ark120202** [comment]
@evilebottnawi Unfortunately, in all of the non-web CSS hosts I've seen there was nothing that can be used to detect that. One way to solve that could be adding a new parser, similarly to `json-stringify`, but there's nothing specific in the file name as well, so that would be effectively the same as an option.

IMO that falls under AST-changing formatting and it's better to leave it to linters (stylelint has a [selector-type-case](https://stylelint.io/user-guide/rules/selector-type-case) rule for that).

Related: https://github.com/prettier/prettier/issues/3304#issuecomment-346906000.

**Comment by evilebottnawi** [comment]
@ark120202 feel free to send a PR
