### ISSUE TITLE
Bug with type annotation, keep removing and adding parentheses

### ISSUE THREAD

**Issue by VincentLanglet** [prettier/prettier#5789]
Following https://github.com/prettier/prettier/issues/5247
I think, introduced in https://github.com/prettier/prettier/commit/30979ed10471731f293da3f254f2267dd760c060

**Prettier 1.16.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAFAJRIlmEB8mAbhAJYAmpNJ59Tz7UArgBsBAbgA6UcZCgZMAIwCGAJ0IcKVArQYt2ZClp4bM-IcJAAaEBAAOMRumSgliiAHcACkoRpkIefvMgsoryYADWcDAAylYhjFAA5sgwinxwFgAWMAC2AgDq6YzwaDFgcJFehYx0hQCePmBo3hZxaHCKMG7B8VnyyNjyAq0WAFZoAB4AQsFhEZHyWXAAMnFwfQNDIKNjkXHxAnAAinwQ8GuDaSAxiq2KPjA1VnBoYIqMNgFWr7C5LDDpyAAOAAMFk+EFauWCVh8nyebToqwsijgAEc+IxkZ15N1ekh+ucLK0sowkikLmhdvsjidVnj1hcYPJZD9mH9kAAmCzJeSMAS7ADCECyPR8UGgiJAfFaABUmd46ecAL6KoA)
```sh
--parser typescript
```

**Input:**
```jsx
const foo = (): (() => void) => (): void => null;
const bar = (): () => void => (): void => null;
```

**Output:**
```jsx
const foo = (): () => void => (): void => null;
const bar = (): (() => void) => (): void => null;
```

**Expected behavior:**
A choice between `(): () => void => (): void => null;` and `(): (() => void) => (): void => null;`.
I think the second one is better.

**Comment by Jessidhia** [comment]
That is a regression in the sense that 1.15 had a clear preference for `(): () => void`, which is better. Unless there is an ambiguity in the type expression you should not need parens, and there is never an ambiguity with a function type unless you need to `|` or `&` the function type itself with another type.

To be honest, your type is confusing and redundant, and took me a while to understand what was going on 😵

```ts
type OuterReturnType = () => void
type InnerReturnType = void
const foo = (): OuterReturnType => (): InnerReturnType => null;
```

**Comment by ikatyang** [comment]
@Jessidhia I guess you meant `(): (() => void)`, which is the output from 1.15.

**Comment by ikatyang** [comment]
👉 https://github.com/prettier/prettier/releases/tag/1.16.1
