### ISSUE TITLE
Way to ignore specific file paths in a glob?

### ISSUE THREAD

**Issue by pdehaan** [prettier/prettier#579]
I have one file in my data/ folder (data/bundle.js) which is generated by Webpack and I don't want formatted (since it essentially unminimizes the file). But I do want to format the other files in the data/ folder formatted. Is there a way to ignore certain files/paths using a glob?

It doesn't look like a glob of "data/*.js" and "!data/bundle.js" works.

I did find https://github.com/isaacs/node-glob#comments-and-negation which almost looks like the negation pattern (`!data/bundle.js`) was removed in **glob@6** and replaced with the `ignore` option in the `glob` constructor.

```
> prettier --parser flow --single-quote --write 'data/*.js' '!data/bundle.js' 'tools/**/*.js' 'test/*.js' 'src/**/*.js'

data/message-bridge.js
data/set-installed-flag.js
data/bundle.js
test/test-addonlistener.js
...
```

**Comment by vjeux** [comment]
If you want you can use `find` and `grep` to solve this

```
find data src tools test src -name '*.js' | grep -v data/bundle.js | xargs prettier --parser flow --single-quote --write
```

**Comment by lydell** [comment]
This should do the trick:

```
prettier --parser flow --single-quote --write 'data/!(bundle).js' 'tools/**/*.js' 'test/*.js' 'src/**/*.js'
```

https://github.com/isaacs/node-glob#glob-primer

Also, if you're unsing ESLint, you can run prettier through `eslint --fix` and get all of ESLint's ignore options for free: https://github.com/not-an-aardvark/eslint-plugin-prettier
