### ISSUE TITLE
 list-different (and check) log every file in CI, instead of just changed files

### ISSUE THREAD

**Issue by DSchau** [prettier/prettier#5801]
**Environments:**
- Prettier Version: 1.16.1
- Running Prettier via: CLI
- Runtime: Node.js 10 (and probably every version)
- Operating System: Linux

**Steps to reproduce:**

- Use [this reproduction repo](https://github.com/DSchau/prettier-check-repro) and specifically [this PR](https://github.com/DSchau/prettier-check-repro/pull/1) for an illustration of the issue

**Expected behavior:**

`prettier --list-different` (and `prettier --check`) should _only_ log the different files in CI

**Actual behavior:**

`prettier --list-different` logs _every_ file in a CI server, tested with TravisCI and CircleCI.

**More information**

Prettier v1.16.1 tweaked the behavior of `--list-different` (and additionally `--check`). It appears to now log all files that are being checked, rather than just the files that differ. In a local, non-CI environment this works well because the shell is wiped with each new file, and the end result ends up being _just_ the files that are changed. In CI, this behavior is **not** present, and so the output becomes incredibly challenging to read and it's not clear which files are different and should be updated.

It appears that [this PR](https://github.com/prettier/prettier/pull/5629) may have been the cause of the regression, specifically with relying on only `process.stdout.isTTY` which seems to log _every_ file being accessed in CI.

**Comment by j-f1** [comment]
I noticed this issue with another project too. It seems like CI providers pretend to be a TTY even though they’re not. I ended up explicitly checking for the `CI` environment variable

**Comment by kachkaev** [comment]
Should the check look like `if (process.stdout.isTTY && !process.env.CI) {...}` then?

**Comment by ikatyang** [comment]
As far as I can tell, there's no `CI` environment variable in Azure Pipelines. I think we should use the original logic (i.e., `process.stdout.isTTY && argv['write']` , the one used before #5629) since it should the safest solution.

**Comment by kachkaev** [comment]
Thanks for the link @SimenB! I'll submit a PR shortly.

**Comment by kachkaev** [comment]
Interestingly, `process.stdout.isTTY` is reported correctly in Azure pipelines (at least on Linux VMs). Just checked the logs for 1.16.1 at work this morning and they were all adequate.

**Comment by kachkaev** [comment]
@DSchau is the problem solved for you now? Just want to double-check.

**Comment by DSchau** [comment]
It has been! Working great for us on Gatsby!
