### ISSUE TITLE
Why isn't the output consistent?

### ISSUE THREAD

**Issue by rickthepick** [prettier/prettier#5803]
**Environments:**
- Prettier Version: 1.16.1
- Running Prettier via: CLI
- Runtime: Node.js v8.11.3
- Operating System: macOS 10.13.6

1) run prettier with the following .prettierrc
printWidth: 120

```javascript
      lesson_colors: {
        lesson_color: [
          { response_type: "success", unit: 0, color: 11730944, lesson: 0, id: 1625, language_level_id: 1 },
          { response_type: "success", unit: 1, color: 16737280, lesson: 0, id: 1630, language_level_id: 1 },
```

2) then run prettier with no .prettierrc:
```javascript
      lesson_colors: {
        lesson_color: [
          {
            response_type: "success",
            unit: 0,
            color: 11730944,
            lesson: 0,
            id: 1625,
            language_level_id: 1
          },
```

3) then run prettier with the same .prettierrc as step 1:
```javascript
       lesson_colors: {
        lesson_color: [
          {
            response_type: "success",
            unit: 0,
            color: 11730944,
            lesson: 0,
            id: 1625,
            language_level_id: 1
          },
```
result: no change!

Why doesn't the output of step 3 bring you back to the same output of step 1?  For any particular file isn't there a single canonical prettier output?

**Comment by lydell** [comment]
This is because we had to make a compromise for objects – see https://prettier.io/docs/en/rationale.html#multi-line-objects

You might be interested in #2068/#4685.

Hope this answers your question!
