### ISSUE TITLE
Tag function (lit-html) breaks arrow function in multiple lines

### ISSUE THREAD

**Issue by odahcam** [prettier/prettier#5806]
I have an oneliner arrow func smaller than printWidth that keeps being breaked in various lines just because of a html lit-html call inside of it.

**Prettier 1.16.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCpyYw7AA6UOO5lkURATgK5gwT0AUAlCdZTjAAsAlpgB0AWwCeABXoQADjgC8OANoBdXgF9evTBHFwAsnEEQAJlx4U+OWkRz1CjVMRWCREmXPkT089iFlAD4cARhxVAADAB5UIWCAEmAPMSkTM0shTi0YgHp44KjObXItEAAaEAUYIWhMZFB0ejkAd2lmhAaUdAA3CCFzSpAAI3p0MABrUwBleQmhKABzZBgmOCrwyIB1YXhMebA4Ga6hWt6zyWRwbGHFzDh6GFl0JfF0ZAAzdFQHqoArTAADwAQuMprN0IYADKLOBfH5-ECAoEzRZLVBwACKjAg8ARvw2IHm9Ae9GuI3QI0kqGgw3k9EWMG2g0EyAAHAAGKoMiAPbbjeTXBmER69eFVJwAR0YQicLzeHyQ30JVQe4iEq3WavRmJxePhysRRJgVJZ5jZSAATFU1ughPFlgBhAzva5QaASkCMB54KndFUPLRaIA)

**Input:**
```jsx
    const result = this.myProp.map(i => html`<li>${this.myMethod(i)}</li>`)
```

**Output:**
```jsx
    const result = this.myProp.map(
      i =>
        html`
          <li>${this.myMethod(i)}</li>
        `
    )
```

**Expected behavior:**
```jsx
    const result = this.myProp.map(i => html`<li>${this.myMethod(i)}</li>`)
```

**Comment by j-f1** [comment]
Minimal repro:

**Prettier 1.16.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALGBbANgAwGYQQ4gA0IEADjAJbQDOyoAhgE4sQDuACqwgykwBuEagBNSIAEYsmYANZwYAZQqzqUAObIYLAK5wy6bAHVU1eHVVg4SvueqDzAT2Tg6DMurpwWMLjI0MJmQ8JixvMgArOgAPACEZeUUlJgw4ABl1OBCwiJBomKV1DSw4AEVdCHgc8IMQVRZvFldJJkk4LAkKFnUYYzEYVGQADgAGMm6Ib2MZClduuCbBbLIWOABHXWo1-yZA4KRQ2rJvDGoavLpi0oqq7MPcupg2-tFB5AAmMh0maixigDCEAwQVcUGgKxAum8ABU2vwjt4AL5IoA)
```sh
--parser babel
--no-semi
```

**Input:**
```jsx
html`foo`
```

**Output:**
```jsx
html`
  foo
`

```

**Comment by odahcam** [comment]
[Playground for this minimal example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALGBbANgAwGYQQ4gA0IEADjAJbQDOyoAhgE4sQDuACqwgykwBuEagBNSIAEYsmYANZwYAZQqzqUAObIYLAK5wy6bAHVU1eHVVg4SvueqDzAT2Tg6DMurpwWMLjI0MJmQ8JixvMgArOgAPACEZeUUlJgw4ABl1OBCwiJBomKV1DSw4AEVdCHgc8IMQVRZvFldJJkknLGgJChZ1GGMxGFRkAA4ABjIeiG9jGQpXHrgmwWyyFjgAR11qdf8mQOCkUNqybwxqbT06umLSiqrso9y6mDaB0SHkACYyHSZqLDFADCEAwQVcUGgqxAum8ABU2vxjt4AL4ooA).

**Comment by jridgewell** [comment]
Hitting this as part of AMP HTML's transition to prettier. Formatting of embedded languages in JS files should be disable-able at a minimum.

This should be given a much higher priority, as this formatting **changes the runtime evaluation** of the code. This probably means it should be disabled by default.

```js
function html(strings) {
  console.assert(
    strings.join("") === "<div></div>",
    "this will throw because of prettier!"
  );
}

html`<div></div>`;
```

**Comment by lydell** [comment]
@jridgewell Here's the issue you're looking for: #5588. We're planning on adding an option for all the simple tags: `md`, `html`, `gql`. They might be off by default in 2.0.

**Comment by jridgewell** [comment]
Thanks!

**Comment by thorn0** [comment]
Fixed by https://github.com/prettier/prettier/pull/7208
