### ISSUE TITLE
IE11 Support for PrettierJS: Suggestion to Implement Polyfills

### ISSUE THREAD

**Issue by jonnyhork** [prettier/prettier#5812]
**Environments:**
- Prettier Version: 1.15.3
- Running Prettier via:  Browser API
- Runtime: IE11
- Operating System: Windows

**Steps to reproduce:**
Using Prettier JS via the standalone.js and HTML,CSS,JS parser files.

**Actual Behavior**
When loading the application that had prettier as a dependency, IE11 does not support methods used in standalone.js such as String.prototype.startsWith and Symbol. 

**1.** Is there official support for using Prettier in IE11?
**2.** Is there an official recommendation on how to polyfill methods in standalone.js that are not supported in IE?

Thank you for your help!

**Comment by lydell** [comment]
> Is there official support for using Prettier in IE11?

I don't think there's been any discussion around that before. I'd say no.

> Is there an official recommendation on how to polyfill methods in standalone.js that are not supported in IE?

`String` is a global object – if you make sure that `String.prototype.startsWith` exists, it should be available when standalone.js tries to use it?

**Comment by lydell** [comment]
No, I don't think we have a recommendation. There are lots of ways of dealing with polyfills. I'd read up a bit on it and use whatever gets you going.

**Comment by j-f1** [comment]
This isn’t an official recommendation of the Prettier team, but I’ve found https://polyfill.io to be useful.
