### ISSUE TITLE
getSupportInfo misinform about babel/babylon

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#5822]
Since 1.16 and the name change babylon -> babel, getSupportInfo returns "babel" as a valid parser for JS, Flow, JSX language. Of course, babel is not a valid parser with prettier < 1.16.
This appeared in prettier-vscode.
We have a current workaround, sadly it doesn't work with prettier < 1.8 (where getSupportInfo doesn't exist)
Changing `prettier.getSupportInfo(otherPrettier.version)` to `otherPrettier.getSupportInfo()`

context: 
prettier/prettier-vscode#705
prettier/prettier-vscode#706

**Environments:**
- Prettier Version: 1.16.3
- Running Prettier via: API
- Runtime: Node 8+ 
- Operating System: ALL

**Steps to reproduce:**

```js
require("prettier").getSupportInfo("0.0.0").languages.find(l=>l.name === "JavaScript").parsers
```

**Expected behavior:**
`[ 'babylon', 'flow' ]`

**Actual behavior:**
`[ 'babel', 'flow' ]`

**Comment by ikatyang** [comment]
👉 https://github.com/prettier/prettier/releases/tag/1.16.4
