### ISSUE TITLE
"trailingComma": "none"    =>  Not working

### ISSUE THREAD

**Issue by pactera-admindev-remy** [prettier/prettier#5825]
Hello, 
    Even after disabled trailingComma in the .prettierrc file, I keep having syntax error message.
 ```Line 1:  Insert `;`  prettier/prettier```.

Fyi: The config file is operational as singleQuote rule is working correctly.

**Input:**
```
   import en from './en'
   import fr from './fr'
   import jp from './jp'
```

***config:***
```.prettierrc
{
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "none"
}
```
```.eslintrc.js
 'plugins': [
   'prettier'
 ],
'extends':[
   'prettier
],
'rules':[
   'prettier/prettier': 2,
   'comma-dangle': 0,
]
```
``` package.json
"dependencies": {
    "prettier": "^1.16.3"
    },
"devDependencies": {
    "eslint-config-prettier": "^2.10.0",
    "eslint-plugin-prettier": "^2.6.2"
}
```

**Output:**
``` console
Failed to compile.

./src/i18n/index.js
  Line 1:  Insert `;`  prettier/prettier
  Line 2:  Insert `;`  prettier/prettier
  Line 3:  Insert `;`  prettier/prettier
  Line 9:   Insert `;`  prettier/prettier

```

**Expected behavior:**

=> Those error message above shouldn't appear.

Could someone tell me where am I doing wrong?

Thank you for your support.

**Comment by lydell** [comment]
Hi!

This is a comma: `,`
This is a semicolon: `;`

Are you looking for the [semi](https://prettier.io/docs/en/options.html#semicolons) option?

**Comment by pactera-admindev-remy** [comment]
Shame on me, I indeed reversed meaning of "comma" and "semicolon".
Than just have to add  ```  semi: false```  in the .prettierrc file
Thank you very much.
