### ISSUE TITLE
parenthesis around nested lambda functions removed incorrectly

### ISSUE THREAD

**Issue by finnigantime** [prettier/prettier#5831]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAsgQwGs4BVDAE33gCdsBebACgEtyBnJbNma5qAcwDaAXQCU9AHxNGGahAAeaTvihoANNmpw2GaGzjLV4ulJVpRAbhBqQEDDGZ7kofNTkB3AAquEbZCHwANwhWaxAAI2p8MGIYAGUMaL5+ZB4AVzgbAAsYAFsAGwB1LOZ4HWi4ON9S5kDStH8wNj8bPn1qGE8o-lz8ZAAzfHz9GwArNnkAISiYuHj8XLgAGT44AaGRkHH5OOT8uABFNIh4deHMkETqdv9w-HC0fOgw2T4YQtYYLOQADgAGGyyCD6QpRDD+WTaODUQJrGxaACOaWYWi6+B6fSQg3ONn0uWYqWoGVxe0Ox1OWI2Fxg9w+5C+yAATDYePhmPlkgBhCC5Xr+KDQOEgNL6AAq9z8lPOAF9pUA)
```sh
# Options (if any):
```

**Input:**
```tsx
type MakeUpdater = (ids: string[]) => ((proxy: any, response: any) => any);
```

**Output:**
```tsx
type MakeUpdater = (ids: string[]) => (proxy: any, response: any) => any;
```

**Expected behavior:**
input is not modified; parentheses are preserved around second lambda function to improve readability

**Comment by hawkrives** [comment]
Isn't that the same result type, though? Does this break code or is it a stylistic request?

**Comment by zpao** [comment]
[Here's another case](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEcAeBDAWwAcAbOTAXkwAoAdKTTAEzxjyUwwCcBLKAcwA09AJQdgAbW59+AXXFSYvAfMzAmcNGF5EYPaB2kDBmAG54SPFvA7Uj-SgD5OSmSIC+np2vqNIUDEwCAE8AfQAzAFcGKmpzEkNXATEXZQcKZ2BfRkwuOBhIrgYAcgALOBISCGKAbmz3OqhsvIKitXCICHEAIzwucQ0tHT0DTGLukjxSzAmp4pN4q1Y4DhCI6M8G+gaQQRAIXX0A5FA+rggAdwAFPoQ0ZBA8UwgrXZBurjwwAGt8gGUiF8ZMglJE4HtSjACCQAOqlHjwNCAsBwP53BE8UwI4IPMBoe57PhoOBcGBXT78Ah4ZDhCzEvYAKzQOAAQp8fv9CHAADJ8OA0ungkBMnB-GRkACKkQg8AFJHpIEBXGJXAe4SqFzeRGUMBhVhgpWQAA4AAx7bUQYkwz5EB7azQk0z8vZ5ACOkR4eXJeEp1KQtPlQuJBB4IK4YL2aHFcClMv5-sFezY3T1TANyAATEnPjxLAIAMIQAhUh5QaDOkCRYkAFTw3XuCcDniAA), where the resulting code actually breaks and cannot be parsed by Flow nor Babel.

**Comment by j-f1** [comment]
That’s a very weird bug @zpao and I’m guessing it’s a problem with the parsers.

**Comment by finnigantime** [comment]
This is a stylistic request, not a bug in terms of breaking code. The prettier output here is worse for human readability than the input. So to me, that's a bug in terms of prettier producing less readable code.

**Comment by j-f1** [comment]
IMO the input is perfectly readable. It describes a function that returns a function that returns a value.

**Comment by zpao** [comment]
Somebody on the Flow team helpfully simplified the broken case:

```js
var example = (): {p: (string => string)} => (0: any);
```

> I’m guessing it’s a problem with the parsers.

If prettier is generating code that cannot be handled by parsers, it doesn't really matter if parsers are ultimately at fault. From talking briefly with the Flow folks, it seems like this may be intentional because there is ambiguity otherwise.

> This is a stylistic request, not a bug in terms of breaking code.

It looks like we have 2 slightly different cases. For lambdas as a value, it seems to be fine (perhaps even because your original test case as multiple arguments). But when the lambda is a property value, that's where the resulting code doesn't parse.

So at least for my cases, this isn't a stylistic request. Code breaks.
