### ISSUE TITLE
Errors with HTML parsing nested tags in <p>

### ISSUE THREAD

**Issue by sbreatnach** [prettier/prettier#5833]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAgC0AcQBCQ5q0pwuAExmoYASxh04DfHADOMVAHo1GrSyNzFygEYQFATxnlyqBaoBuT5y4AOX7y5uniwBzkZB-i6GfiHeqDFQoS66PjyRYYYpabEZCRkR5oa2DsqG7IwgADQgED5q0LrIoFwATi0QAO7ErQiNKFzuEKoKVSDWLVxgANZwMADKqWCqfMgwLQCucNXlAOqU6nqLcHO96h7q9sjguo3Vy7pwLTDEE7w0XMgAZlx0D9UAVroAB4SCbTWZzLg0OAAGWWcC+Pz+IEBQLmy14mgAiusIPBEb8tiBUi0Hi0rjxeOtuOTqj4WssYDthjBKMgABwABjp7QeOwmPiu9L0j3cCOqLTgAEd1qpJS8uG8PkhvoTqg8aKpVhsiboMdjcfiVUiiTAuNZmQpWcgAEzVNZcVR0DG4CA0d5XKDQcUgdYPfDmvqqh4AXxDQA)
```sh
--parser angular
```

**Input:**
```html
<!DOCTYPE html>
<html lang="en-GB">
<head>
<title>Test</title>
</head>
<body>
  <div>
    <p>
      <div>
      </div>
    </p>
    <p>
      <span>
      </span>
    </p>
  </div>
</body>
</html>
```

**Output:**
```html
SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (11:5)
   9 |       <div>
  10 |       </div>
> 11 |     </p>
     |     ^
  12 |     <p>
  13 |       <span>
  14 |       </span>
```

**Expected behavior:**
Nested divs in a p tag should be parsable.

There are a few issues around nested block tags I came across while trying this out. If you replace the div with a span, it works as expected. If you replace the div with another block tag (e.g. another p), the error reoccurs. If you delete the offending ending p tag, it moves the div outside the p tag altogether.

Also, the original is actually invalid HTML according to the W3C validator, because the p tag does indeed have implied end tags. But prettier ingests it just fine, as long as there's no block tag nested. The W3C validator is being very strict though, because the original HTML appears as expected in Chrome et al.

Finally, this happens whether the parser is angular or html.

**Comment by lydell** [comment]
Let's say Prettier did this. What would it gain you? The browser still parses the file like so:

![screenshot from 2019-02-05 17-37-35](https://user-images.githubusercontent.com/2142817/52288638-e2376a00-296c-11e9-9bc3-65c1a514127b.png)

- There's no nested div.
- An extra p tag has appeared.

So you'd have to change your code anyway. I'd say Prettier throwing an error on this is a _good_ thing since it helps you catch the mistake earlier.

**Comment by sbreatnach** [comment]
Ah, that makes more sense. It wasn't clear from the error message that this was the issue. I read it as meaning that the second p tag had closed the first, whereas the div had closed it. The HTML spec link was no help there for me either, because it made no explicit mention of what closes the tags implicitly.

The prettier behaviour isn't entirely consistent with the browser though. If you remove the trailing p end tag, it auto-generates the empty p tag as per what happens in the browser. Whereas if the p end tag is there, it fails completely instead of generating the second empty p tag. This also confused me because I was seeing two behaviours for what I thought was the same incorrect HTML layout.

Ideally, prettier would either do what the browser does and auto-generate the p tags in both cases, or fail hard in both cases. A clearer error message would have helped also, but that may be more of an issue with the inscrutable HTML spec than prettier. But I understand why you've done it this way, so I'll close.
