### ISSUE TITLE
Prettier is still breaking HTML in 2019

### ISSUE THREAD

**Issue by tysun** [prettier/prettier#5834]
VSCode, macOS

`"printWidth": 80`

```
<h1 [ngStyle]="{
  'color': h1Style ? 'gray' : 'black',
  'font-size': !h1Style ? '1em' : '4em'
}">Home</h1>
```

save result = broken html

```
<h1
  [ngStyle]="{
    color: h1Style ? 'gray' : 'black',
    'font-size': !h1Style ? '1em' : '4em'
  }"
>
  Home
</h1>
```

if edit line length < 80

```
<h1 [ngStyle]="{color: h1Style ? 'gray' : 'black',
'font-size': !h1Style ? '1em' : '4em'}">Home</h1>
```
save result = still broken html

```
<h1
  [ngStyle]="{
    color: h1Style ? 'gray' : 'black',
    'font-size': !h1Style ? '1em' : '4em'
  }"
>
  Home
</h1>
```

**Comment by azz** [comment]
Not sure what specifically is broken there? Maybe you're after [`html-whitespace-sensitivity=strict`](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity)?


**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFgRgAQG0oDmAyjAJ4A2cAugLwA6IwdU22A5JORAE5tLZYSFONgD87AtwCGpNtn5sARuSlgA1mwA0zVmwBm0GAFoAzgEsAXnD7YAhILKUx7THAC2chQBZ3bZgF8GAD4ACQg3OFQAeiwgkE0QCAAHGDNoE2RQKW5uCAB3AAVshAyUKQA3CDMAE3iQRWl1OBgiJNUzQmQYbgBXOAT0GDdyAHV0M3gTNrA4IhKJs3KJ0mQQE26zMBg6jpM4bhgC6QI3KWQ9KXI9hIArEwAPACFGtWaiKQiAGQ64c8vrkB3e5EDoESgARR6EHgfyu-RAbW4e24q0GwzqSW4HRgIxqMHQyAAHAAGBKYiB7EbSJKrTFwZHlX4JbhwACOPTMLKOUhOZyQFzhCT2bjMXV68PMhAhUJh-P+8JgUkUuOq+OQACYEt0pGZyKCAMLhU6rKDQJkgHp7AAqStKAr2-n8QA)
```sh
--html-whitespace-sensitivity strict
--parser html
```

**Input:**
```html
<h1 [ngStyle]="{
  'color': h1Style ? 'gray' : 'black',
  'font-size': !h1Style ? '1em' : '4em'
}">Home</h1>
```

**Output:**
```html
<h1
  [ngStyle]="{
  'color': h1Style ? 'gray' : 'black',
  'font-size': !h1Style ? '1em' : '4em'
}"
  >Home</h1
>

```

**Comment by j-f1** [comment]
Note that the input should be fine since leading and trailing whitespace is stripped from block elements.

**Comment by tysun** [comment]
I used sensitivity strict in VSCode and .eslint but it still comes out with those solo closing brackets. So I guess my white space wasn't a problem as you mentioned. There is no way to get `}">Home</h1>` closing?

**Comment by duailibe** [comment]
So it doesn't break HTML, it's just not printing how you'd prefer.

**Comment by lydell** [comment]
@tysun Can you clarify what you're asking for, please?

**Comment by tysun** [comment]
Hi. Yes I only meant the formatting broke. I'm not used to characters dangling by themselves like that. I guess that's normal in markup and style languages.

**Comment by azz** [comment]
Yeah that's the expected behaviour.
