### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by kddeisz** [prettier/prettier#5838]
Hi there - I've written a plugin for the ruby programming language (https://github.com/kddeisz/prettier-ruby). I'm pretty happy with the state it's in (supporting Ruby 2.5 through trunk). I'm opening this issue to see what would be involved in getting it added as an official plugin. Please let me know what I can do!

**Comment by evilebottnawi** [comment]
Here also https://github.com/iamsolankiamit/prettier-ruby ruby, maybe we can union?

**Comment by kddeisz** [comment]
That one hasn't been updated in about a year and has a pretty fundamentally different approach, not sure how easy it would be to union them.

**Comment by j-f1** [comment]
I’m all for moving this one over. In the meantime, can you open a PR to update the website to list your plugin instead @kddeisz?

**Comment by kddeisz** [comment]
Yeah definitely - https://github.com/prettier/prettier/pull/5841

**Comment by evilebottnawi** [comment]
We get :+1: from @vjeux 

/cc @kddeisz let's start to move this in prettier repo

**Comment by kddeisz** [comment]
Cool! How?

**Comment by j-f1** [comment]
I’ve invited you to the org, so you should be able to transfer the repo to the Ruby team.

**Comment by kddeisz** [comment]
Done and done! Would it be alright to publish it on npm under the `@prettier` namespace?

**Comment by evilebottnawi** [comment]
@kddeisz yep, let's close issue here and continue discussion here https://github.com/prettier/prettier-ruby/issues/51
