### ISSUE TITLE
typescript: empty typeParameters and typeArguments

### ISSUE THREAD

**Issue by armano2** [prettier/prettier#5839]
**Prettier 1.16.4**

Due to inconsistency in reported ast by typescript parser, there is issue with some of typeParameters and typeArguments, in some cases parser outputs `TSTypeParameterInstantiation` and `TSTypeParameterDeclaration` with empty array of `params`

in PR https://github.com/typescript-eslint/typescript-eslint/pull/223i proposed change to make all occurrences of this consistent across all nodes. It means that all occurrences of `<>` are going to lead to crash in this package, as opposed to only sometimes.

`TSTypeParameterInstantiation` and `TSTypeParameterDeclaration` with empty array of `params` should be supported

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAmwgkOAB0pCbjSAeAPgAoBKAbioF8qQAaEBAAOMVNADOyULkyYIAdwAKMhJJS4AbhFQATfiABGmfAGs4MAMpD86AObIYmAK5wBACxgBbADYB1N6jw4tYEFqqBqBqBAJ7I4OKSAujiWDCKxraeuMh43ikCAFbiAB4AQsZgZpa4nnAAMuhwObh5riBFxRZ23nAAik4Q8M2tAtaYKZhxMNFCcOJgmKgi+kKLsL66MG7IABwADKNyKb7GQnGrc1gaTQKYcACOTqh36biZ2Ui5+SApnqgOzja4m6fQGQ0+LW+MFwBg2Oi2yAATAJHLhUN47ABhCCeLJxKDQG4gJwpAAqMLUXzgXC4QA)
[AST Structure](https://astexplorer.net/#/gist/e4cecffa1a43eb0d6889926c7008df7e/fb9f74643829cec99626c7432a050ca905ff5f36)

**Input:**
```ts
interface foo {
    foo<>();
}
```

**Output:**
```jsx
TypeError: Cannot read property 'pos' of undefined
    at https://prettier.io/lib/parser-typescript.js:1:2122250
    at T (https://prettier.io/lib/parser-typescript.js:1:2123933)
    at t (https://prettier.io/lib/parser-typescript.js:1:2122204)
    at Object.h [as findNextToken] (https://prettier.io/lib/parser-typescript.js:1:2122387)
    at b (https://prettier.io/lib/parser-typescript.js:1:2128676)
    at e (https://prettier.io/lib/parser-typescript.js:1:2155613)
    at d (https://prettier.io/lib/parser-typescript.js:1:2127555)
    at m (https://prettier.io/lib/parser-typescript.js:1:2127698)
    at https://prettier.io/lib/parser-typescript.js:1:2157681
    at Array.map (<anonymous>)
```

**Reference:**
- https://github.com/typescript-eslint/typescript-eslint/issues/220
- https://github.com/typescript-eslint/typescript-eslint/pull/223
- https://github.com/typescript-eslint/typescript-eslint/pull/219

**Comment by armano2** [comment]
i did some testing, and looks like its issue with old version of parser and it will be fixed after upgrade

**Comment by azz** [comment]
(me just catching up on ts changes) what does the empty type argument list mean semantically?

**Comment by armano2** [comment]
its invalid code and ts reports:
```
      case 1098: // ts 3.3 "Type parameter list cannot be empty."
      case 1099: // ts 3.3 "Type argument list cannot be empty."
```

right now parser is not reporting errors for semantic issues in sourceCode (due to performance concerns for prettier) and we are generating AST even when there are errors.

as far as i know prettier should not change output code, just format it.

-----------

i did some digging and looks like this issue was present in old version of parser, i'm unsure if this is not a case for version used in here see [ast explored: old parser](https://astexplorer.net/#/gist/0d7b2e18920812a36d62557cba05d1f8/4ad914d6aa37fa958e1afe23e97d7774550b453e)

**Comment by thorn0** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/223 was merged long time ago, so Prettier supports empty type argument lists now. The only thing we need to close this issue is a test.
