### ISSUE TITLE
Flow Maybe syntax makes TypeScript parser throw

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#5840]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAThALYBiANhAO4AUAhkQOZL4D8AsgwJ4BGcAJT5gAXxAAaEBAAOuaAGdkoJiRoAFJgiUoGANwg4AJpJB8iDMAGs4MAMozLOKM2Qwi6OFIAWMUpQB1bxx4BUcwODttEJw9EJ5kcAUlKWcFOCIYdQtmUgZkVAZKdKkAKwUADwAhC2tbOwZSOAAZZzgCopKQcoq7Z2ZKOABFdAh4DuKvEEcidKJEmB4ZOAUwIhw5Uxl12ADjGG9kAA4ABiltiHSAixlE7ZWMvXapIjgAR3QcV+yGXPykQqTKTpUg4NweKYKfqDEZjdoAzpTGAMPh7IwHZAAJik7gYOEo-QAwmQ8okoNBniB0OkACoonSA9KiURAA)
```sh
--parser typescript
```

**Input:**
```tsx
function fromFlow(arg: ?Maybe) {}
```

**Output:**
```tsx
Error: unknown type: "TSJSDocNullableType"
    at printPathNoParens (https://prettier.io/lib/standalone.js:26012:13)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:23541:28)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15912:18)
    at https://prettier.io/lib/standalone.js:15863:16
    at Object.printComments (https://prettier.io/lib/standalone.js:15586:17)
    at printGenerically (https://prettier.io/lib/standalone.js:15862:22)
    at FastPath.call (https://prettier.io/lib/standalone.js:15700:16)
    at printPathNoParens (https://prettier.io/lib/standalone.js:25203:21)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:23541:28)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15912:18)
```

**Expected behavior:**
Show a synatx error, I guess? AFAIK, it's not valid TS.

The reason this shows up is that I'm currently converting a Flow code base to TypeScript. Just renaming the files makes `prettier` throw in my IDE due to this error.

Link to Flow docs, if it matters: https://flow.org/en/docs/types/maybe/

**Comment by armano2** [comment]
note:

this is a case also for 
```
function fromFlow(arg: Maybe?) {}
```

**Comment by j-f1** [comment]
This is because that syntax is valid in JSDoc comments, and TypeScript throws most parsing errors after doing the parse. There’s an option available in our TS parser, but IIRC it makes things slower (we’re working on fixing that).

**Comment by thorn0** [comment]
What is the best way to improve this situation I wonder?

1. Print it as is even though it's not valid TS.
2. Convert it to valid TS: `?T` will become `T | null | undefined`. It already works like this for some other JSDoc type syntaxes: Prettier turns `Array.<Foo>` into `Array<Foo>`.
3. Just make the error more human friendly. Unify it with usual `SyntaxError`s.

**Comment by evilebottnawi** [comment]
> 3. Just make the error more human friendly. Unify it with usual SyntaxErrors.

:+1:

**Comment by thorn0** [comment]
The approach # 2 can be super useful for people who migrate from Flow to TS though.

**Comment by evilebottnawi** [comment]
@thorn0 i don't think we should do this, because we are beautifier, it is out of our scope, I think other utilities must exist for this

**Comment by thorn0** [comment]
The option #1 then. Error recovery is a good thing for a beautifier. And if the parser give us this opportunity for free, why not use it?

**Comment by evilebottnawi** [comment]
Yes, #1 is good also.
