### ISSUE TITLE
printWidth not respecting line width

### ISSUE THREAD

**Issue by MythlinMasterdo** [prettier/prettier#5842]
When executing `prettier --config ./.prettierrc.json --write src/filename` `printWidth` is consistently not working as expected.

Example line not being formatted:
`export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR = "Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters";`

`prettierrc.json`
```
{
  "singleQuote": true,
  "bracketSpacing": false,
  "printWidth": 100
}
```

**Expected behavior:**
Format `"Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters";` to a new line.

**Comment by lydell** [comment]
I tried to reproduce this in the playground, but couldn't.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFEANABVICUBJAWVIDkAVAfQGEbSBBVugHlm7ZrybsAMiwDirABLtaNQTTwBePAB0QDAIZo8AGwQBzGAAs8EAGZ5SmONgCWAWwT5me9wT1QoEPjoYHBwACZ4ACTAAMqCEpLCMuwAarw07DKCpDHs8rSkAL4EFnrYemDw2EQ6ANwgADQgEBgwztBEyKBl2BAA7pRlCJ0oegBuEM5hjSAARuVgANZwMDEYFc5Qpsgw2ACucE0WMK5GAOoWzvBE6yExw1fOY1cAnsjgRJ1Nm0ROMJTlUyuPTIGx6Iy-JoAKyIaAAQgtlqtvHBJJs4KDwZCQDC0DFNqYTABFPaBDFIMEQw4gdbVJzvWZ6WZwIwzDAuWBnKaWZAADgADE12RBfmdyhh3uy4L9sGMMU1sHAAI57ZyKgF6IEgilY6m-VzOHb7PUE4mk+CYqlNGBMrlhHlIABM1vKziMBM4EFcwPeASg8pAe1+rCZI0pv0KhSAA)
```sh
--parser babel
```

**Input:**
```jsx
export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR = "Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters";
```

**Output:**
```jsx
export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR =
  "Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters";

```

Maybe you're running an old version of Prettier or have some other tool involved as well?

**Comment by MythlinMasterdo** [comment]
> I tried to reproduce this in the playground, but couldn't.
> 
> **Prettier 1.16.4**
> [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFEANABVICUBJAWVIDkAVAfQGEbSBBVugHlm7ZrybsAMiwDirABLtaNQTTwBePAB0QDAIZo8AGwQBzGAAs8EAGZ5SmONgCWAWwT5me9wT1QoEPjoYHBwACZ4ACTAAMqCEpLCMuwAarw07DKCpDHs8rSkAL4EFnrYemDw2EQ6ANwgADQgEBgwztBEyKBl2BAA7pRlCJ0oegBuEM5hjSAARuVgANZwMDEYFc5Qpsg2ekZEcE0WMK5GAOoWzvBE6yExw1fOY1cAnsjgRJ1Nmwe4lOWmVx6HZ7A5NABWRDQACEFstVt44JJNnAQftDiBIWgYptTCYAIoAV0CqKQu3RTXW1Sc71melmcCMMwwLlgZymlmQAEYAAw8ym9A5ncoYd4suC-MaoprYOAAR0Jzll-z0gOBZNBGIOrmcyBg2EJWtxBOJ8D1BoxMHp7LCnKQACYmvq9M4jLjOBBXED3gEoNKQISDqx6SNyQdCoUgA)
> 
> ```shell
> --no-bracket-spacing
> --parser babel
> --print-width 100
> --single-quote
> ```
> 
> **Input:**
> 
> ```js-jsx
> export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR = "Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters";
> ```
> 
> **Output:**
> 
> ```js-jsx
> export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR =
>   'Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters';
> ```
> 
> Maybe you're running an old version of Prettier or have some other tool involved as well?

I am running prettier `1.16.1`, and don't have any other tools involved as I just execute the command from my terminal.

**Comment by lydell** [comment]
Then try 1.16.4! If you still experience problems, please provide steps to reproduce and we'll take a look at it.

**Comment by MythlinMasterdo** [comment]
@lydell I just bumped to version `1.16.4` created a file locally called `test.js` added one line to it `export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR = "Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters";` then executed `prettier --config ./.prettierrc.json --write "test.js"` with the same `prettierrc.json` that I posted initially and the formatting is still not occurring even though the line is 141 columns wide.

**Comment by hawkrives** [comment]
@MythlinMasterdo Are you able to replicate this on the playground at all?

**Comment by lydell** [comment]
@MythlinMasterdo Sorry, I tried to follow your steps, but still no success.

```
~/stuff  
❯ mkdir prettier-test

~/stuff  
❯ cd prettier-test/

~/stuff/prettier-test  
❯ echo '{"private": true}' > package.json

~/stuff/prettier-test  
❯ npm i prettier
npm notice created a lockfile as package-lock.json. You should commit this file.
+ prettier@1.16.4
added 1 package from 1 contributor and audited 1 package in 1.476s
found 0 vulnerabilities


~/stuff/prettier-test  
❯ echo 'export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR = "Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters";' > test.js

~/stuff/prettier-test  
❯ echo '{
    "singleQuote": true,
    "bracketSpacing": false,
    "printWidth": 100
  }' > .prettierrc.json

~/stuff/prettier-test  
❯ 
~/stuff/prettier-test  
❯ prettier --config ./.prettierrc.json --write "test.js"
test.js 44ms

~/stuff/prettier-test  
❯ cat test.js 
export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR =
  'Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters';

~/stuff/prettier-test  
❯ which prettier
./node_modules/.bin/prettier

```

**Comment by MythlinMasterdo** [comment]
@hawkrives I am not able to replicate on the playground, but I am able to replicate on other machines near me.

**Comment by MythlinMasterdo** [comment]
@lydell Any idea what the issue would be? I already nuked prettier and re-installed it.

**Comment by lydell** [comment]
There could be prettier config files or editorconfig files laying around somewhere up the file tree that you don't realize are read.

If you share _exactly_ how you reproduce the issue (and on which OS) we could help you figure it out.

**Comment by MythlinMasterdo** [comment]
@lydell I think that I have found the problem. I can't get prettier to wrap when using template literals in JS. I tried in 2 playgrounds but can't seem to share the link(it gives a forbidden). Enter the same string that we have been using prior in this issue and replace the double quotes with back-ticks.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by lydell** [comment]
Thanks.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFEANABVICUBJAWVIDkAVAfQGEbSBBVugHlm7ZrybsAMiwDirABLtaNQTTwBePAAMGAQzR4ANggDmMABZ4IAMzylMcbAEsAtgnzNdbgrqhQI+OhgcHAAJngAJMAAyoISksIy7ABqvDTsMoKk0ezytKQAvgTmuti6YPDYRFoA3CAANCAQGDBO0ETIoKXYEADulKUIHSi6AG4QTqENIABGZWAA1nAw0RjlTlAmyNa6hkRwjeYwLoYA6uZO8ERrwdFDl06jlwCeyOBEHY0b+7iUZSYuXTbXb7RoAKyIaAAQvMlisvHBJBs4MC9gcQBC0NENiZjABFACuARRSB2aMaayqjjeM10MzghmmGGcsFOkwsyAAjAAGbkUnr7U5lDBvZlwH6jFGNbBwACOBKcMr+ugBQNJIPR+xcTmQMGwBM1OPxRPguv16JgdLZoQ5SAATI09bonIYcZwIC5AW9-FApSACftWHThmT9gUCkA)
```sh
--no-bracket-spacing
--parser babel
--print-width 100
--single-quote
```

**Input:**
```jsx
export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR = `Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters`;
```

**Output:**
```jsx
export const EXPERIMENT_CREATION_NAME_LENGTH_ERROR = `Max length of Experiment Name cannot exceed ${SOME_LONG_VAR_GOES_HERE} characters`;

```

Then this looks like a duplicate of #2889.

**Comment by lydell** [comment]
Duplicate of #2889
