### ISSUE TITLE
[TypeScript] Trailing commas from type exports removed

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#5846]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwBUBXDAGzjONIF48BtAHSjzygoFsAjONgA0eAPRi86AJYxIAEzgcAuiGEgIGGNOgBnZKACG2bBADuABWMJ9KQwDcI0+WpD9shsAGs4MAMoYntJQAObIMNgUcOoAFjC81ADqMbJwuoFgcH42stL2soTI4Lr66sG6QjAWHiG8hsgAZobUFeoAVrpoAEIe3r5+hrxwADLBcI3NrSAdaH7BIbQAihQQ8BMt0SCB2BXYRUQkumDY0lquGCewic4wMcgAHAAM6hcQFYkeGEUXaUL24+psHAAI4UaRA6qGWr1JBNDbqCq8aThSKbXTzJYrNawyabGCGfjXeS3ZAAJnUEUM0mo8wAwhBeHUis1qK4KBUyATbHCKgBfXlAA)
```sh
--parser typescript
--trailing-comma all
```

**Input:**
```tsx
export type TupleType = [
  number, // exitcode
]
```

**Output:**
```tsx
export type TupleType = [
  number // exitcode
];

```

**Expected behavior:**
Keep input as-is

Note that using `babel`, `babel-flow` or `flow` parser keeps the trailing comma

**Comment by Ruffeng** [comment]
Same to me. Every time I run prettier all the types that I've been working results as without commas. Therefore it's an error

**Comment by duailibe** [comment]
@Ruffeng what do you mean "it's an error" ?

**Comment by Ruffeng** [comment]
That my TS complains about that

**Comment by lydell** [comment]
It doesn't in the TypeScript playground: http://www.typescriptlang.org/play/#src=export%20type%20TupleType%20%3D%20%5B%0A%20%20number%20%2F%2F%20exitcode%0A%5D%3B

**Comment by Ruffeng** [comment]
Try to add a function in the interface and then another. Prettier  will remove it and will show it( at least in my project it does)

**Comment by hawkrives** [comment]
@ruffeng Can you give us an example on the TS playground that gives the error you're seeing?

**Comment by armano2** [comment]
before TypeScript 3.3 trailing comma on tuple types was not allowed
semantically as far as i know there there is no difference if you put it there or not

https://github.com/Microsoft/TypeScript/pull/28919

there is only one issue here, option: `--trailing-comma all` is not working for tuple types, but i think its better if its not going to (at least till most of people not upgrade to 3.3)

**Comment by arvinsim** [comment]
Yup, having the same issue as @Ruffeng. The issue only came out know because `react-intl-cra` throw the error when it tried to extract a `<FormattedMessage>` from a `.tsx` file.

**Comment by bitttttten** [comment]
I am also getting this error. I have prettier in my lint staged files and when it runs, it will strip the comma from

```ts
interface ItemProps {
    itemWidth: number,
    isTba: boolean
}
```

and then my create-react-app setup will complain in the terminal:

```sh
Failed to compile.

./src/organisms/Timetable/index.tsx
  Line 354:  Parsing error: Unexpected token

  352 | interface ItemProps {
  353 |     itemWidth: number
> 354 |     isTba: boolean
      |     ^
  355 | }
  356 | 
  357 | const Item = styled(GridItem)<ItemProps>(props =>
```

**Comment by rista404** [comment]
Anyone managed to fix this? Eslint is complaining about the missing comma that prettier removes.

**Comment by lydell** [comment]
@rista404 This has been fixed. Try updating Prettier.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwBUBXDAGzjONIF48BtAHSjzygoFsAjONgA0eAPRi86AJYxIAEzgcAuiGEgIGGNOgBnZKACG2bBADuABWMJ9KQwDcI0+WpD9shsAGs4MAMoYntJQAObIMNgUcOoAFjC81ADqMbJwuoFgcH42stL2soTI4Lr66sG6QjAWHiG8hsgAZobUFeoAVrpoAEIe3r5+hrxwADLBcI3NrSAdaH7BIbQAihQQ8BMt0SCB2BXYRUQkumDY0lquGCewic4wMcgAHAAM6hcQFYkeGEUXaUL24+psHAAI4UaRA6qGWr1JBNDbqCq8aThSKbXTzJYrNawyabGCGfjXeS3ZAAJnUEUM0mo8wAwhBeHUis1qK4KBUyATbHCKgBfXlAA)
```sh
--parser typescript
--trailing-comma all
```

**Input:**
```tsx
export type TupleType = [
  number, // exitcode
]
```

**Output:**
```tsx
export type TupleType = [
  number, // exitcode
];

```

**Comment by rista404** [comment]
@lydell I was using `1.18.2` and it didn't work, but looks like all of a sudden formatting works. Sorry for the false alarm and thanks for the response!

**Comment by Eksapsy** [comment]
@rista404 Any info on how you actually fixed that? :) I'm still struggling with this and tslint is complaining about the missing trailing commas.

**Before prettier**
```tsx
const [contextMenuOrigin, setContextMenuOrigin] = useState<{
    left: number,
    top: number,
  }>({ left: 0, top: 0 })
```

**After prettier**
```tsx
const [contextMenuOrigin, setContextMenuOrigin] = useState<{
    left: number
    top: number
  }>({ left: 0, top: 0 })
```

**Comment by rista404** [comment]
@Eksapsy I'm not sure, it just somehow stopped adding commas without me changing configuration and versions. For what it's worth, I'm using eslint, and I can share my `.eslintrc` file :)

**Comment by Eksapsy** [comment]
Oh thank you very much @rista404 . I use tslint though and I find it hard to believe that it would fix the problem itself :P I very much appreciate the effort though! :D 

I short of "fixed" it by just using an interface instead of having a type declaration right away. Like this:

**Before**
```tsx
const [contextMenuOrigin, setContextMenuOrigin] = useState<{
    left: number
    top: number
  }>({ left: 0, top: 0 })
```

**After**
```tsx
interface IOrigin {
    left: number,
    top: number,
}
const [contextMenuOrigin, setContextMenuOrigin] = useState<IOrigin>({ left: 0, top: 0 })
```

The problem is potentially that prettier thinks that type declaration inside a generic shouldn't have commas at all. So, it's not "fully compatible" with Typescript in some way probably, but I wont jump to conclusions.
