### ISSUE TITLE
[Typescript] Improvment for arrowParens rule

### ISSUE THREAD

**Issue by lhrolim** [prettier/prettier#5847]
I'm opening this issue here as I believe it makes the most sense.

Basically I got a situation where I cannot get a combination to suit simultaneously both prettier and tslint rules.

**Environments:**
- Prettier Version: 1.16.4
- Running Prettier via: vscode
- Runtime:  node 10.13.0
- Operating System: ubuntu

**Steps to reproduce:**

On a typescript based project, define a method such as:

`const MockedRollbar = {
  error: err => {
    console.log('mocked rollbar error call', err)
  },
  warn: err => {
    console.log('mocked rollbar warn call', err)
  },
}`

the tslint.json has the following options:

`"arrow-parens": false,`
or
`"arrow-parens": true,`
or
"arrow-parens": [true, "ban-single-arg-parens"]

Latter would be ideal as it would check for parentheses except for single argument parameters

However at  .prettierrc I got just two options

"arrowParens": "avoid | always",

I cannot figure a way to use both plugins in a way that auto-formatting keep the tslint rules valid.

**Expected behavior:**

Provide more granular options to prettier so that one is not forced to wrap every single function with parentheses whilst keeping tslint rules valid

**Actual behavior:**

Upon formatting I get:

`Expected parentheses around arrow function argument having a body with curly braces`

**Comment by lydell** [comment]
We recommend turning all lint rules that conflict with Prettier off. They don't gain you anything. See https://github.com/prettier/tslint-config-prettier

Does this answer your question?

**Comment by lhrolim** [comment]
Hi @lydell sorry for the late reply.

Actually it turned out I had it already configured, so unfortunately I have to say no :)

I apologize for not describing the issue very well. For an "outsider" it´s a bit rough to even tell whether this is a prettier issue, a tslint one, or a plugin.

However from a prettier-product perspective I feel like it would be nice if it would provide 2 extra options:

`ignore` --> this would completely ignore the parenthesis syntax on arrow-functions, letting the users decide (not that useful I believe, but for some might)
`ban-single-arg-parens` --> or something alike... similar to the tslint setup where it would be possible to prevent it just for single argument functions

Right now, I had to disable prettier by appending `// prettier-ignore` which is not cool since some folks in our team do not even use it.

**Comment by lydell** [comment]
> since some folks in our team do not even use it [Prettier]

There we have it. If your whole team isn’t onboard with using Prettier, you’re unfortunately going to have a bad time using Prettier. You’ll always bump into some incompatibility with your team’s style guide (so far you’ve only had trouble with arrow-parens, it seems), and you’ll accidentally commit unnecessarily large diffs by reformatting other part of the file.

[tslint-prettier](https://github.com/azz/prettier-tslint) might help, though.

**Comment by j-f1** [comment]
> `ban-single-arg-parens`

I’m pretty sure that’s what `arrowParens: avoid` does.
