### ISSUE TITLE
Prettier misplaces JSDoc of paren-wrapped Function Expressions!

### ISSUE THREAD

**Issue by SMotaal** [prettier/prettier#5850]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAhAThA1gpACYAHSjzwHoy8BtADQF08B1dAQwAc8BJTgMQFE8AMwCuUMDACW0PHAAebdHADOSqSQkk2LRVCV5ipCtTwMA0nDgcAUgGUAIhDB4A7hJgALIaPFqZ8xSq+GnhaOkoG+iTkAFTReAACMACebHAEABJwADap6EoAvnjRZBGQujB47tm5egC8eAAUEYQwZLEJoSwAtgQACtqSLFkAPJk5cHkAfIVV43lFJVEtDbM1ePXA+QCU65OV1RPhUVsNWwDcxPnExOksYFgAjPhEUUa0DACqUM6sHCJikmkcgUylU0mCoQQeg0qgAJmkshIlDAjoZKO88OZLHhIF0uggKgAjLKOLDQ3QSeF4RHI1GRQztRIpNLAMY1QrFUrQZH7OZ1RoRUgANwglLwAHJxQAaQXkSgAFQA8nZFfgWM4WG4QooYJIJkIJLJZU0oqQWm04vFOj1gP10IMRmzDtNeWtOab9DAVgd5httrtXYdZVsIidzpdrlBbvcAEzPCJveiYiwcXH42B4Ymk8lwhFIlHNV6M5KpDI+goLLnlQO+6iyoxKlVqjVakG6iT6wSG+uM619AYSIajcsu1aHSse7189YEf21PZjvIROhUAAMdFOFygVygIClIAgbEBumQoG0mGcdqhyBALBFlL3IEJrHucBgNi0YA0AHNkIIhkocD7u4MBdFkjDuG4yifnANhQm4EhCm4SQ3mAKiPjCEwwL0rDfl0LB-gBQEgAAVkosgYHcODvt0cAADIaHAyAwOgwjEWRsg2D+WRwAAisIEDwIRWSAfuoSAegN4lsoYDoBIR6PgoECAcw7A3iCElCkx+6KAAjsIEiKDhLB4QRSD-iJxGAV0EjMaxVncXxAlCUgLFsfuMAsISjCUh4yAxh5rASIiUDfgAwhAeJmbeWRZI+wiAfKXlKHZ7kgAoGgwD5sJ+UgDwxqu+T5EAA)
```sh
--no-bracket-spacing
--jsx-bracket-same-line
--parser typescript
--print-width 120
--single-quote
--trailing-comma all
--use-tabs
```

**Input:**
```tsx
Broken: {
  // [X] Wrap IIFE function expression in parens 
  // [ ] Keep JSDoc with function expression in parens
  
  /** @type {Helpers} */
  const helpers = (
  	/** @param {Partial<Helpers>} helpers */
  	(helpers = {}) => helpers
  )();
}

Hack1: {
  // [X] Unwrap function expression in parens inside lists
  // [X] Keep comment blocks inside lists
  
  /** @type {Helpers} */
  const helpers = (
    void '',
    // TODO: await prettier fix
    (
    	/** @param {Partial<Helpers>} helpers */
    	(helpers = {}) => helpers
    )
  )();
}

Hack2: {
  // [X] Keep comment blocks inside lists
  
  /** @type {Helpers} */
  const helpers = [
    // TODO: await prettier fix
    /** @param {Partial<Helpers>} helpers */
    (helpers = {}) => helpers
  ][0]();
}

```

**Output:**
```tsx
Broken: {
	// [X] Wrap IIFE function expression in parens
	// [ ] Keep JSDoc with function expression in parens

	/** @type {Helpers} */
	const helpers = /** @param {Partial<Helpers>} helpers */
	((helpers = {}) => helpers)();
}

Hack1: {
	// [X] Unwrap function expression in parens inside lists
	// [X] Keep comment blocks inside lists

	/** @type {Helpers} */
	const helpers = (void '',
	// TODO: await prettier fix
	/** @param {Partial<Helpers>} helpers */
	(helpers = {}) => helpers)();
}

Hack2: {
	// [X] Keep comment blocks inside lists

	/** @type {Helpers} */
	const helpers = [
		// TODO: await prettier fix
		/** @param {Partial<Helpers>} helpers */
		(helpers = {}) => helpers,
	][0]();
}

```

**Expected behavior:**

- [X] Wrap IIFE function expression in parens:

      `const ƒ = () => {}()` -> `const ƒ = (() => {})()`

- [ ] Keep JSDoc with function expression in parens:

      `const ƒ = /** … */() => {}()` -> `const ƒ = (/** … */() => {})()`

**Comment by SMotaal** [comment]
If prettier will move JSDocs, it has to distinguish between outer `@type` blocks versus inner `@param` and `@returns` blocks.

**Comment by SMotaal** [comment]
Hello 👋 — any updates would be greatly appreciated!

**Comment by thorn0** [comment]
Isolated issue:

**Prettier pr-6773 (next, 2.0.0-dev)**
[Playground link](https://deploy-preview-6773--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTACgB0pNMB6AKiswAEAHbAJ2wFtNgqBfTAI0xUKpcoT4BKfAD5O3UuMLjSIADQgIDGAEt0yUC2YQA7gAUWCNMhDYANkewBPS2r6swAazgwAykzBaoAHNkGGYAVzg1AAsYNhsAdSiteDQ-OG8LZK0AN2SHKzA0ZxAAtDhmGBNWQLZsZAAzWzK1ACs0AA8AITdPH3Y4ABkAuAamyJA29u8AwJs4AEUwiHhRm2aQJmYy5is+bD44G1UN5gCYeK0AExgo5AAOAAY1BkMy+NYGKxe4beyRtQAjkt4FUNJYUNg0ABaKBwOCXeHHZhwIFaZFVbA1OpIRprcZlNhaELhfEzOaLZYjHFjNQwfYXa63JAAJlprC0NhmAGEIGxalYfgBWY5hMoAFX24Nx62yEQAklAEbBvGBTpoAIKK7wwBxzVZlbjcIA)
```sh
--parser babel
```

**Input:**
```jsx
const a = (
  /** @param {*} b */
  (b) => {}
)()

```

**Output:**
```jsx
const a = /** @param {*} b */
((b) => {})();

```
