### ISSUE TITLE
Feature Request: toml support

### ISSUE THREAD

**Issue by Airkro** [prettier/prettier#5852]
TOML is an obvious and minimal format for config files. It is used by many developers, Like yaml.

**Comment by lydell** [comment]
See https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml

It was added to the website a couple of days ago (#5829), but as of this writing I could not see it on https://prettier.io/docs/en/plugins.html.

**Comment by bd82** [comment]
I've created:
- https://github.com/prettier/prettier/pull/5869
- https://github.com/prettier/prettier/pull/5866

I think after those are merged the links in the website will be updated...
