### ISSUE TITLE
Setting trailingComma to "all" or "es5" breaks SCSS comment formatting.

### ISSUE THREAD

**Issue by mgol** [prettier/prettier#5855]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgTwLToIYAOSABABQA6UxxA1nJiRVdcQCYCWAzgQDZ4PEARjwhgaAGkotiAehnFI6dAhhTiASklR1AbkohxICARjtonZKDwAnaxADuABRsILKPADcI7VgZCDrPDE4GABlAiD2KABzZBhrAFc4QwALGHQeAHUU9nhuILhQ11z2D1zMZHBOC0MozjhrGEdA6PxkADM8HnrDACtOAA8AIUDgsLxlABkouA6unpB+gdCo6J44AEUEiHg57uSQCOt660rOMGq-AmsomEyfGBTkAEYABlfDa4h6zMCCSuucBOHlmhmscAAjgl2ODmnhWng9gt6uh2HFEgdOKt1lsdrMkJ19oYYHhBPdWI9kAAmYmBdg8VYAYQgSkR7h4PD8CXqABVSW5CfUAL5CoA)
```sh
# Options (if any):
--trailing-comma=all
```

**Input:**
```scss
$my-map: (
  key: (
    display: block,
    // comment
  ),
);
```

**Output:**
```scss
$my-map: (
  key: (
    display: block,
    // comment,
  ),
);
```

**Expected behavior:**
There should be no comma added at the end of a comment. What's even worse, though, is the fact that running Prettier n times will add n commas... It doesn't stabilize, preventing me from formatting this file properly.

**EDIT:** I've just noticed the same happens with `--traling-comma=es5`.

**Comment by mgol** [comment]
I've just noticed the same happens with `--traling-comma=es5`.

**Comment by evilebottnawi** [comment]
@mgol because `scss`/`sass` support `trailingComma`, but it is bug with comment

**Comment by martinbroos** [comment]
I'm having the same problem

**Comment by lohfu** [comment]
@evilebottnawi setting `trailingComma: 'all'` turns

```scss
  @include container($max-width: $content-max-width + 2 * ($arrow-width + $arrow-margin));
```

into

```scss
  @include container(
    $max-width: $content-max-width + 2 *
      (
        $arrow-width + $arrow-margin,
      )
  );
```

which is not valid scss

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by tylim88** [comment]
any update on this? the issue still persist

**Comment by sosukesuzuki** [comment]
This was fixed in #6918. But, https://github.com/prettier/prettier/issues/5855#issuecomment-523088809 still persist, i'll open new issue.

**Comment by sosukesuzuki** [comment]
/cc @lohfu @evilebottnawi 
Sorry, I'm not familiar with scss syntax. The code shown in https://github.com/prettier/prettier/issues/5855#issuecomment-523088809 can be formatted with Prettier([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAllMAbArgEzgAJJYBDTOAJwAoAdKIogEgFsyAPAWgHd18YACyQtS8WF3bc+AwUQDURAExEAVAyZN6jTU2ZkqVCD178hClgaMn2VAOaYANBs0BKBq4DcDEI5AQABxh0aABnZFArYwAFAwRwlDIANwh+XxAAIyoyMABrOBgAZQCczDtkGCpcOD9BGFZsAHVBdHhQkrA4QvjW9CTWgE9kcFDwv0xQ6hho7Lt2ZAAzMmxJvwArUI4AIWy8gsKyVjgAGUpF5dWQDY5Csuw4AEVcCHhzlZqQEqpJqmHQsFG6QCVEwMEaZkEyAAjAAGGF+YEQSaNbIBYbAuA-JJwdIAR2e8BmgQSIDIoS4UDgcEI+HSVDg+PQ9JmZDmZDel0mrHQFSqH1Cd0eBJxSCW7z8MDIGXBsmQSgl2XQ2DKAGEIKx5olsNh0rhJgAVKUJMWXJLVACSUEIsEKYBBQQAglbCjABvcOXAAL6eoA)). Is it invalid scss code?

**Input**
```scss
@include container(
  $max-width: $content-max-width + 2 *
    (
      $arrow-width + $arrow-margin,
    )
);
```

**output**
```scss
@include container(
  $max-width: $content-max-width + 2 *
    (
      $arrow-width + $arrow-margin,
    )
);
```

**Comment by lohfu** [comment]
@sosukesuzuki your input is the same as your output... both are invalid.

i created a very simple example at codepen, https://codepen.io/lohfu/pen/ZEYmmKo. if you add a comma after `2px + 4px` the SCSS becomes invalid.

**Comment by sosukesuzuki** [comment]
@lohfu Thank you! I got it. I'll create new issue.
