### ISSUE TITLE
Spread operator's expression not wrapped in parentheses in JSXAttribute

### ISSUE THREAD

**Issue by Andarist** [prettier/prettier#5856]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AJgB0RAFAGYQS4A+V+AvgJR24D0AfADpQDcxhR5SjXqMuXEABoQEAA4xM0AM7JQAQwBO6iAHcAChoTKUq7BEzpJIAEbrVYANZwYAZRl3MUAObIY6gK5wUgAWMAC2ADYA6kGY8IpuYHDOhrE4sQCeyOCKylIeinDqMLq2nqGqyKSq4QVSAFaKAB4AQrYOTs6qoXAAMh5wldW1IA2Nzh6e4XAAin4Q8IM1gSBu6gXqWVaqVunh0JYy6h4wkeYwQcgAHAAMUocQBZG2MlmHcOvYA1LqcACOfpgfiVVGUKkgqkspAVQpgfP5looJlNZvMBuChssYNtTuhzsgAExSXyqTDhCYAYQgoXKWSg0C+ID8BQAKtsjBCCnQ6EA)
```sh
--parser babylon
```

**Input:**
```jsx
<div {...(foo || {})} />
;({...foo || {}})


```

**Output:**
```jsx
<div {...foo || {}} />;
({ ...(foo || {}) });

```

**Expected behavior:**
```jsx
<div {...(foo || {})} />;
({ ...(foo || {}) });

```

**Comment by duailibe** [comment]
Both aren't necessary, but for the sake of consistency, let's do this
