### ISSUE TITLE
[CSS] Leading 0

### ISSUE THREAD

**Issue by ju1i3nm** [prettier/prettier#5859]
This has already been discussed in https://github.com/prettier/prettier/issues/2705, but forcing leading 0s in CSS code goes against @mdo's code guide (http://codeguide.co/#css-syntax) and the Google CSS style guide (https://google.github.io/styleguide/htmlcssguide.html#Leading_0s).

It also goes against the default settings of scss-lint (https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/leading_zero.rb) and sass-lint (https://github.com/sasstools/sass-lint/blob/develop/lib/rules/leading-zero.js).

This is preventing Google projects from using prettier to format CSS/SCSS. Could we revisit introducing an option for leading 0s? Thank you!

**Comment by lydell** [comment]
Do you work at Google?

**Comment by ju1i3nm** [comment]
Yes! Don't consider this a "Google" request though -- this is just something my team members and I have been discussing today, so that's just me talking, not the company :)

As mentioned on other threads, Google uses clang-format. But some of us use prettier for languages that clang-format doesn't support (HTML, CSS/SASS, JSON...), mainly through IDE plugins. The "leading zero" issue was brought to my attention today, and led us to disable prettier for CSS/SCSS files. I was thinking of simply sending a PR to add a flag, but some research taught me more about prettier's philosophy (and the existing https://github.com/prettier/prettier/issues/2705), so I figured I'd ask first :)

**Comment by lydell** [comment]
Have you considered trying to change the style guide? Because leading zeroes is a perfect candidate for bike shedding – exactly the type of unproductive discussions Prettier is trying to get rid of.

**Comment by evilebottnawi** [comment]
I agree leading zero is great and readable. I don't think we need option for this or change default behavior too

**Comment by kachkaev** [comment]
I guess that the rationale for not having a leading zero is to save one byte in a network request. Given that the majority of CSS written today is post-processed, there is no more benefit in this. Having zeros makes the CSS more human-friendly, so it’s great that they are there by default.

**Comment by ju1i3nm** [comment]
> Have you considered trying to change the style guide? Because leading zeroes is a perfect candidate for bike shedding – exactly the type of unproductive discussions Prettier is trying to get rid of.

I have! I actually started a thread internally to try that angle in parallel. Will let you know how it goes.

**Comment by lydell** [comment]
Nice!

Meanwhile, I think you should be able to use Prettier via [stylelint-prettier](https://github.com/prettier/stylelint-prettier) and [number-leading-zero](https://stylelint.io/user-guide/rules/number-leading-zero/). Does that work for you?

**Comment by webdevnerdstuff** [comment]
I don't understand why the authors are so against adding the option to remove the leading zero, and to be honest some of the collaborators are being awfully rude about it. 

Nobody is asking to change it completely, just to give the option to let the user decide. Considering a lot of style guides and linters are for removing the zero, it only makes sense to add it as an option. 

Telling people to change their style guide is an awful answer as well. It's not that simple when you work with many developers or a large corporation. Some companies have a style guide set, and to try to change that is not as simple as "just change your style guide".

If you have the choice to make your users happy and improve your product, why not just do it?

**Comment by j-f1** [comment]
See https://prettier.io/docs/en/option-philosophy.html @webdevnerdstuff.

**Comment by webdevnerdstuff** [comment]
@j-f1 I have read that and understand that. I'm giving my feedback and thoughts. I do love Prettier and think they have done a great job, but I do think there's room for improvement, and that's why user feedback is important for a developer. I personally have multiple formatters as none are a perfect fit for all languages I code in. So it's not skin off my back if they refuse to change. 

I just think being more open to options is only going to make a good product even better. With that everybody wins in the end. This also helps solidify the product, as when the industry does change, they will already be ahead of the game because all people need to do is change the options. Look at linters like ESLint. Fully configurable, and as coding changes, it's as easy as changing the option. No additional development needed, and everybody is happy. :)

Just my two cents, with over 20 years of developing/programming/managing experience behind me.

**Comment by gigamesh** [comment]
I love prettier and have become completely addicted to it, but recently I'm working on google projects and this leading zero issue has become a source of headaches. 

I appreciate not adding more options than necessary, but why add an option that can't be disabled? 

In any case, if someone can point me to where this rule is implemented in the code base, I'd love to try to just make a fork for my team. I haven't been able to find it in the code. :)

**Comment by thorn0** [comment]
@gigamesh Google is famous for [being an alternative universe](http://neugierig.org/software/blog/2018/09/typescript-at-google.html) when it comes to conventions. I think the `printCssNumber` in `src/language-css/printer-postcss.js` is what you need.
