### ISSUE TITLE
Prettier breaks JSON

### ISSUE THREAD

**Issue by gazedash** [prettier/prettier#5861]
**Prettier 1.16.4**

**Input:**
```jsx
[
    {
      "time": 0,
      "end": 5,
      "content": "Some event 1",
      "img": "https://comps.canstockphoto.com/closeup-image-of-small-dog-yorkshire-stock-photograph_csp2414009.jpg",
      "id": 1
    },
    {
      "time": 10,
      "end": 15,
        "content": "Some event 2",
      "img": "https://comps.canstockphoto.com/womans-hand-gesturing-a-small-amount-stock-image_csp4354356.jpg",
      "id": 2
    },
    {
      "time": 15,
      "content": "Some event 3",
      "img": "https://images.pexels.com/photos/1267244/pexels-photo-1267244.jpeg?cs=srgb&dl=adult-bar-beer-1267244.jpg&fm=jpg",
      "id": 3
    }
]
```

**Output:**
```jsx
;[
  {
    time: 0,
    end: 5,
    content: 'Some event 1',
    img:
      'https://comps.canstockphoto.com/closeup-image-of-small-dog-yorkshire-stock-photograph_csp2414009.jpg',
    id: 1,
  },
  {
    time: 10,
    end: 15,
    content: 'Some event 2',
    img:
      'https://comps.canstockphoto.com/womans-hand-gesturing-a-small-amount-stock-image_csp4354356.jpg',
    id: 2,
  },
  {
    time: 15,
    content: 'Some event 3',
    img:
      'https://images.pexels.com/photos/1267244/pexels-photo-1267244.jpeg?cs=srgb&dl=adult-bar-beer-1267244.jpg&fm=jpg',
    id: 3,
  },
]
```

**Expected behavior:**

It should format json and don't break it (See the semicolon and missing double quotes in output, which isn't JSON)

**Comment by kachkaev** [comment]
I copy-pasted your input into the Playground and could not reproduce it.

* [input as is (no trailing `]`)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAOlABDrxO67ogwCWAtnMUlgAwA0BhWxCAJtVgKyPbPGRYCGJ2IBlCJSxwAbsKwBGYr2YsQFAOaiQACxgwADgGckAelORyxgHRgAhlCMwIYANYGdEZ7ckWANhBGcACuBgC0FHYacGEQAGZhRuR2fn5hbBAaYQCeEABOrkY6pHkxTi6uYR5emXl2HgD6YEYGAEwALArttLQAnNYAVgZaICr86hzIikw4AL5jOPh8hMRklJwKDDNEIOwbPNsr4NDwsNoSUrLyrcqHapraeoYm5pY29o7ObtXelqYA7pIHEYwjoHGwwtEnME8qQoFk7IlkqkwnZyBBgrBEl9KpFok0Wu0AMxcYlcABsg2Gt2WO1IkxoN1p822S1UqwoVCmCgOtJwAhOwnOkjg0jksCwRJp7PU5BGNGIT2MZlMeLgRmsBjgAA84H4NX8foFTApWuSAOwddqmLW6-VVTzOMKmi1WqlwDQAfmaAF4jHkNAAjABkbD8PrsbGCfhgYUDdjycbgcETLst7XaVI0wbi5B9QxGCzpDMl21moxAEAMZGgRmQoATeQg-wACgmEHWUHYZBB6RXA3U3HAYGIDHYwHCNMgYHlgnB6LoYOQ-AB1YrwFrjuBiDukMgyPfZZDgIx1hdwoJ5GAtuoaZLIOIpIILgZGbUAIUHrmHYjRcAAMnCcAPk+84gK+2piJOfhwAAisEXjAUgj76mBY55Jex6vtAFYGLCsArvSMA6MgAAcDAgHhgRwCudQGMeeHqimcgVqUACOwQlHAN5RPeyGgQuQTkKQ06zmBRjQXBCHwCBqELjAdiBoRbDEcgrTyXUpB+JOADCkh8SAUDQMBC7BEEAAqimdihQSzLMQA)

* [input with fixed syntax](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAOlABDrxO67ogwCWAtnMUlgAwA0BhWxCAJtVgKyPbPGRYCGJ2IBlCJSxwAbsKwBGYr2YsQFAOaiQACxgwADgGckAelORyxgHRgAhlCMwIYANYGdEZ7ckWANhBGcACuBgC0FHYacGEQAGZhRuR2fn5hbBAaYQCeEABOrkY6pHkxTi6uYR5emXl2HgD6YEYGAEwALArttLQAnNYAVgZaICr86hzIikw4AL5jOPh8hMRklJwKDDNEIOwbPNsr4NDwsNoSUrLyrcqHapraeoYm5pY29o7ObtXelqYA7pIHEYwjoHGwwtEnME8qQoFk7IlkqkwnZyBBgrBEl9KpFok0Wu0AMxcYlcABsg2Gt2WO1IkxoN1p822S1UqwoVCmCgOtJwAhOwnOkjg0jksCwRJp7PU5BGNGIT2MZlMeLgRmsBjgAA84H4NX8foFTApWuSAOwddqmLW6-VVTzOMKmi1WqlwDQAfmaAF4jHkNAAjABkbD8PrsbGCfhgYUDdjycbgcETLst7XaVI0wbi5B9QxGCzpDMl21mmAAuqMQBADGRoEZkKAE3kIP8AAoJhCNlB2GQQenVwN1NxwGBiAx2MBwjTIGB5YJwei6GDkPwAdWK8BaU7gYm7pDIMkP2WQ4CMjeXcKCeRg7bqGmSyDiKSCy4GRm1ACER64x2I0TgAAZOE4GfV8lxAD9tTEGc-DgABFYIvDApAX31SDJzyG8zw-aBqwMWFYHXekYB0ZAAA4GBAQjAjgdc6gMM9CPVFM5GrUoAEdghKOB7yiJ80Ig5cgnIUg5wXSCjDgxDkPgcCMOXGA7EDEi2DI5BWiUupSD8GcAGFJEEkAoGgMDl2CIIABUVJ7dCglmWYgA)

2 maintainers: this is a follow-up fro https://github.com/prettier/prettier-vscode/issues/724

**Comment by ikatyang** [comment]
This looks like an issue for misusing top-level `parser`, see [Setting the parser option](https://prettier.io/docs/en/configuration.html#setting-the-parser-docs-en-optionshtml-parser-option):

> **Note:** Never put the `parser` option at the top level of your configuration. Only use it inside `overrides`. Otherwise you effectively disable Prettier's automatic file extension based parser inference. This forces Prettier to use the parser you specified for _all_ types of files – **even when it doesn't make sense, such as trying to parse a CSS file as JavaScript**.

**Comment by gazedash** [comment]
So it seems it's a problem with vs code extension, not with prettier, so I am closing this issue.
Also, seems like the problem went away when I changed parser from "babylon" to "babel"
