### ISSUE TITLE
Option to indent wrapped lines by 2 * indent (e.g. +4)

### ISSUE THREAD

**Issue by mprobst** [prettier/prettier#5865]
prettier wraps lines and indents by the regular indentation level, i.e. +2 whitespace by default:

```js
if (this.line.is.very.long()
  && moreCodeHere) {
  bodyOfBlock();
}
const similarilyAssumingLongVariableNames =
  someValue;
```

Many style guides (see citations below) request a 2 * indent for wrapped lines (also known as continuation indent), to make them stand out more from the body of the block:

```js
if (this.line.is.very.long()
    && moreCodeHere) { // note: +4 indent here, not +2
  bodyOfBlock();
}
const similarilyAssumingLongVariableNames =
    someValue;
```

The reasoning is that it's otherwise easy to mix up statements of the body with expressions from the wrapped line, and indent from control structures/blocks (such as `if` statements) is more easily distinguished from wrapped lines.

This isn't universal, e.g. AirBnB's style guide is not explicit on the issue, but examples use a +2 continuation indent.

Would this be a valid option for prettier?

[0] https://contribute.jquery.org/style-guide/js/#multi-line-statements
[1] https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/styleguide.md#indent-style
[2] https://google.github.io/styleguide/javaguide.html#s4.5.2-line-wrapping-indent
[3] https://google.github.io/styleguide/jsguide.html#formatting-indent
[4] https://www.oracle.com/technetwork/java/codeconventions-150003.pdf
[5] counter example: https://github.com/airbnb/javascript

**Comment by lydell** [comment]
It's already clearly separated:

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwBaoDOAdADapRzFHEBucATgJ5nQDm2AlADpSaYAyAZgC2EBlUgATKnkZxsDAK5QoFNpgDUmCEpgAaHegCSMgIaFDAdwZmADgEFSEs1KadOmYL34AjCG4A8ugAQqQQYADWXADcvAC+vJBQhDCYhKgiqKRmDNlMDoSESllQbAAy7ABquahmvqRwAHJmInCEmAC8PukQbTWkSnAxIPogEHYwqNCEyKC5DBBWAAq5CLMoZrQQqFKjIL62UXAwAMp2ZmDqyDDKcGN4MCKkAOoE8IQXYHCn66hTtH+TGQ4CK+wohEYMGWtjYIjMyHQZlIkLGACtCAAPEJHSInU6tODlChwRHI1EgDGY07qRoARSUEHgZJR9xAFwYkIYIN89SY4Sg+zseVgL12+GQAA4AAxjYUQSEvWx2EHC9qMej7CQARyUqAkMLMcIRSCRrLGkKyNzuFtpcAZTNJpvJbJg9TFUglSAATGNbmZsuoAMJ9eEgqDQUljJSQgAq9Q2Zsh8XiQA)
```sh
--parser babylon
```

**Input:**
```jsx
if (this.line.is.very.long()
  && more.code.here(running + out, ofIdeas, wrapAlready)) {
  bodyOfBlock();
}
const similarilyAssumingLongVariableNames =
  someValue;
```

**Output:**
```jsx
if (
  this.line.is.very.long() &&
  more.code.here(running + out, ofIdeas, wrapAlready)
) {
  bodyOfBlock();
}
const similarilyAssumingLongVariableNames = someValue;

```

**Comment by voithos** [comment]
Prettier seems to do something analogous to this with template languages, as well (at least, I've seen this on Angular template formatting). If the opening tag is wrapped (e.g. because it has many attributes), the indent is +2 by default.

```
<really-long-tag
  withLotsOf="attributes"
  [and]="bindings"
  ...
>
  <inner-code>...</inner-code>
</really-long-tag>
<other-tag
  *ngIf="long.condition"
  ...
>
  ...
</other-tag>
```

This seems to create a bit of a visual imbalance (perhaps more so than the JS examples), since the opening tag name is attached to the first `<`, instead of going on the next line. Compare to the +4 continuation indent example, which seems to more clearly differentiate between inner HTML vs continuation lines:

```
<really-long-tag
    withLotsOf="attributes"
    [and]="bindings"
    ...
>
  <inner-code>...</inner-code>
</really-long-tag>
<other-tag
    *ngIf="long.condition"
    ...
>
  ...
</other-tag>
```

**Comment by vincent-olivert-riera** [comment]
@lydell can this issue be reopened? I'm interested on that feature (double-indent for wrapped lines).

**Comment by lydell** [comment]
@vincent-olivert-riera Feel free to open a new issue! It is not clear what this one is about anymore.

**Comment by mprobst** [comment]
@vincent-olivert-riera please CC me on any new issue.
