### ISSUE TITLE
Ability to disable/override a single rule with js comment

### ISSUE THREAD

**Issue by slorber** [prettier/prettier#5867]
I know this has been discussed in the past and other issues are already talking about this feature.

My usecase is:
- I have prettier rules for my whole js codebase, which is singlequote
- I'd like to have specific double quote rule for "translation files", yet keep prettier format them

I want double quote in translation files by default, because when I need to put a single quote in a translation, it's very annoying to have to transform the single quoted text to double quoted or to do escaping. It makes more sense to always double quote on translation files.

I'm integrating prettier with eslint

Currently, the workaround I use is to put this on top of my translation files:

```
/* eslint quotes: ["error", "double"] */
// prettier-ignore
```

This works, but this totally disable prettier for that file. I still want prettier to prettify my translation file :)

I'd like to be able to:
- disable a single prettier rule for the file
- or being able to override the prettier rule setting for the file, like eslint allows to do

I'm fine with both solutions, but I think supporting both would be nice for other usecases.

**Comment by j-f1** [comment]
Prettier supports an `overrides` setting similar to ESLint’s. You could also consider using curly quotes for better typography and to avoid issues with escapes (`“‘’”`).

**Comment by lydell** [comment]
You could also use backticks (`` ` ``) for your translations.

**Comment by slorber** [comment]
Thanks, didn't know about this override option here https://github.com/prettier/prettier/blob/master/docs/configuration.md#configuration-overrides
That will do the job.
