### ISSUE TITLE
Support ICU translation formatting

### ISSUE THREAD

**Issue by slorber** [prettier/prettier#5868]
Many of us use ICU string format for translations, this is common notably when using FormatJS / react-intl

Sometimes that ICU syntax can become quite complex and having proper formatting would help readability. 

Here's a guide regarding the message syntax: https://formatjs.io/guides/message-syntax/

Here's an example ICU message with correct/readable formatting:

![image](https://user-images.githubusercontent.com/749374/52852846-07209f80-311a-11e9-8e28-e47df5c87be3.png)

These strings can be in separate translation files, but can also be put anywhere in source, melted with other js code like react components or whatever. Afaik there is no easy way to detect currently a string is an ICU related string except introspecting the string content itself.

I'd like to discuss how we could add support for ICU in Prettier. I'm also interested to contribute this feature and have already some research work to find tooling around ICU: https://github.com/slorber/awesome-icu
Would someone from Prettier team help me build this feature?

@vanwagonet has done a great job for parsing ICU to AST and pretty printing the AST, which could be used for a prettier integration.

https://github.com/format-message/format-message/tree/master/packages/format-message-print

**Comment by j-f1** [comment]
You could implement this as a plugin that supports external files. However, I don’t think we’ve provided a way to hook into JS files yet. You

**Comment by slorber** [comment]
Thanks, will take a look at prettier plugins when I have time

Would having an extension like .icu.js make things easier?
Or creating a function that does nothing (return identity) to wrap ICU-related objects? Like the graphql fragments can be identified thanks to the gql template literal string...

**Comment by j-f1** [comment]
Unfortunately we don’t have a way to hook into our processing of JS files to add support for things like that at this time. The main issue tracking that is #4424.

**Comment by evilebottnawi** [comment]
Answer https://github.com/prettier/prettier/issues/5868#issuecomment-464013789 and https://github.com/prettier/prettier/issues/4424, feel free to feedback
