### ISSUE TITLE
[Angular] Void elements are needlessly self-closed

### ISSUE THREAD

**Issue by voithos** [prettier/prettier#5872]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAeAhgJzlgPgB0p10MAjLAZzmNLPIp3scY0gBtW32ALFiV68MASwC2Acx7C2YqAAcArjBmy5nUVADWa9XPFwYhEABoQEBTFHRqyULhwQA7gAVcCOyiwA3CKIATMxBmLDBtIwBlBTCtSWQYHCU4cz4YcU4AdT5ReGoYsDhIz1zRH1yAT2RwajtzLVocGFccLElxLGQAMyxOWnMAK2oADwAhVvCorEMAGS04bt7+kCHhyLjOOABFJQh4Rb6UkBicRuqsKEklTlxghRwtGEzAmD5kAA4ABnN7iFpM1oKar3OCNHwLcx4ACOSlEeBabQ6B2WtHEogSSSO1A2212+yQPUO5mMFGeAVeyAATMTWqJNJcAMIQcRIlBQaAQkBKWgAFSwFC8hNoAF9hUA)
```sh
--parser angular
```

**Input:**
```html
  <area>
    <base>
      <br>
        <col>
          <hr>
            <img>
              <input>
                <link>
                  <meta>
```

**Output:**
```html
<area />
<base />
<br />
<col />
<hr />
<img />
<input />
<link />
<meta />

```

**Expected behavior:**
Intuitively, I expect Angular templates to be treated similar to HTML5, and in HTML5 void elements cannot have full closing tags (e.g. `<input></input>` is invalid). Although HTML5 does ignore the self-closing `/`, it's unnecessary and leads to more visual noise.

Compare, for example, with the ember-template-lint rule, which prohibits the self-closing `/` on void elements (and justifies it): https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/self-closing-void-elements.md

This may be tangentially related to #5862, but explicitly just covers Angular template formatting.

**Comment by lydell** [comment]
As far as I can tell, this is a duplicate of #5246?

**Comment by voithos** [comment]
Ah, thank you - yes, this is a dupe.

**Comment by j-f1** [comment]
Duplicate of #5246
