### ISSUE TITLE
Python is dead

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#5877]
Looks like the python effort https://github.com/prettier/plugin-python is dead? Should Prettier (website etc) stop claiming support for it?

**Comment by lydell** [comment]
I agree. There’s no need for a Python plugin when there’s [black](https://github.com/ambv/black).

**Comment by evilebottnawi** [comment]
Just idea: we can run `black` under `prettier` plugin to allow using one tool for many languages

**Comment by j-f1** [comment]
The [Elm plugin](https://github.com/gicentre/prettier-plugin-elm) does something similar.

Should we archive the Python plugin repo?

**Comment by evilebottnawi** [comment]
Maybe somebody from our team works with python and take care about this.

**Comment by lipis** [comment]
Yes, I think it's a good idea to archive it and remove any references to it in the docs. 

/cc @patrick91

**Comment by brodybits** [comment]
> Yes, I think it's a good idea to archive it and remove any references to it in the docs.

with a reference to [`ambv/black`](https://github.com/ambv/black) would be nice:)

**Comment by lydell** [comment]
> Just idea: we can run `black` under `prettier` plugin to allow using one tool for many languages

I like the idea, but let's wait until somebody needs that.

**Comment by j-f1** [comment]
https://github.com/prettier/plugin-python/pull/117
