### ISSUE TITLE
[Typescript] Indentation of nested ? : (ternary operator) inconsistent - first part indented, second part not

### ISSUE THREAD

**Issue by mihilion** [prettier/prettier#5881]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEA3AhgJwEtcAjdTAXk0igBNCZDoBGAHSk0wH5rp7HoAJnadOPViFy4JI0UkwSSJGR0zya-JlGGqxC8GBWi1+2rQkBuEABoQEAA4CoAZ2SgC+CAHcACgQSuKLjYEIS0NiAk+LhgANYYAMr2MYRQAObIMPgArnC2ABYwALaoAOr5DHDOyWBwCQEMhNgMAJ7I4M6utqnOcPgwPtFpRbjIAGa4qL22AFbOAB4AQtFxibhFcAAyqXDjk9Mgc-MJqWnoAIrZEPB7U3kgyfi9+O0kpC2o0BH2RLClYTB8sgABwABlsPwgvVK0Xs7R+VT62F2tnwcAAjtlCGjBrhhqMkBM7rZekVCJkcvdnKcLlcboT9vcYKR-rRAchBLYsrhCKhTgBhCBFEbtKDQFEgbK9AAqpECRN6AF9FUA)

**Input:**
```ts
let variable = condition1
  ? condition2
    ? "aa"
    : "bb"
  : condition2
    ? "cc"
    : "dd";
```

**Output:**
```ts
let variable = condition1
  ? condition2
    ? "aa"
    : "bb"
  : condition2
  ? "cc"
  : "dd";
```

**Expected behavior:**
```ts
let variable = condition1
  ? condition2
    ? "aa"
    : "bb"
  : condition2
    ? "cc"
    : "dd";
```

**Comment by duailibe** [comment]
Hi!

This is the expected behavior, see #5039 for more context.
