### ISSUE TITLE
Use dot notation for property access

### ISSUE THREAD

**Issue by julien-f** [prettier/prettier#5882]
I think it would be nice to always use dot notation for property access when possible instead of keeping the original formatting.

Note: I did not find any issues related to this.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEEB0AzCEDcAdKCAbTxCwlIF0cQAaVABxgEtoBnZUAQwCceIA7gAVeCDii4A3CMwAmdEACMeXMAGs4MAMoNVzKAHNkMHgFc49ABYwAtgBsA6pebw2usHC1iXzSS4CeyOBsHPT6bHA8MEIqBjZcyBhcdhH0AFZsAB4AQirqmlpcNnAAMvpwicmpIBmZWvoGdnAAiqYQ8JUpFiC6PBE8QYpciv520AoMPPowDnIwlsgAHAAM9JMQEQ4qDEGTcP2SFfQ8cACOpswnMVxxCUhJXfQRNszGZt1sDU2t7RX3Vd0YMNZrJ5sgAEz0ExcZh2BoAYQgNniQUIUCOIFMEQAKsNxA8IgBfQlAA)

**Input:**
```jsx
o.foo;
o["foo"];
o["foo bar"];
```

**Output:**
```jsx
o.foo;
o["foo"];
o["foo bar"];
```

**Expected behavior:**

```jsx
o.foo;
o.foo;
o["foo bar"];
```

**Comment by lydell** [comment]
Hi! Prettier generally does not do this type transformations – see https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about

> Prettier only prints code. It does not transform it. This is to limit the scope of Prettier. Let's focus on the printing and do it really well!

You can use the [dot-notation](https://eslint.org/docs/rules/dot-notation) ESLint rule to achieve this (it has autofix!).

**Comment by julien-f** [comment]
I know it does only formatting but I did not think such a trivial change would fall into transformation :slightly_smiling_face: 

I believe semicolons are a much major change (and risky due to ASI quirks) but Prettier does this anyway :thinking:

**Comment by duailibe** [comment]
Adding/removing semicolons aren't transformations. What exactly do you mean by that? Do you have an example where it's risky?

**Comment by kachkaev** [comment]
@julien-f you may find this eslint rule useful: https://eslint.org/docs/rules/dot-notation. I agree with @lydell that this kind of transformation is out of Prettier's scope.

**Comment by julien-f** [comment]
@duailibe just a quick Google search gave me [this article](http://lucumr.pocoo.org/2011/2/6/automatic-semicolon-insertion/). It's hard dealing with semicolon insertions, for instance Prettier fixed a few things regarding the binding operator `::` some time ago.

@kachkaev No problem if you guys think it's not in the scope of Prettier, just wanted to give my opinion on this.

I will not use the ESLint plugin with autofix, I only want to use a single tool (Prettier) to format my code, I may use it for checking though, but IMHO, the less tools (and plugins) the better :slightly_smiling_face:

**Comment by evilebottnawi** [comment]
@julien-f seriously? prettier (printer) and eslint (linter) doing very difference things

**Comment by julien-f** [comment]
@evilebottnawi I do use ESLint, just not with autofix.

**Comment by lydell** [comment]
Then I recommend using autofix! It's great!

**Comment by julien-f** [comment]
ESLint is quite slow and I've had a couple of issues with autofix (I don't remember what exactly), I've decided to only use Prettier for formatting (which takes care of most of the issues anyway) and use ESLint for reporting, and I think its better for the devs to see what's wrong, to understand why and fix it themselves).

**Comment by lydell** [comment]
Fair enough!
