### ISSUE TITLE
Which version of Angular Prettier supports in 1.15.0?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#5884]
https://prettier.io/blog/2018/11/07/1.15.0.html#html-vue-angular

We use Angular 1.5.8 https://libraries.io/npm/angular/1.5.8

https://gorrion.io/blog/angularjs-vs-angular

Should I use 

`*.html: --parser html `
or
`*.component.html: --parser angular`

**Comment by ikatyang** [comment]
_Angular_ (v2+) is officially supported (`--parser angular`), while angular.js (v1) is not but using `--parser angular` for it should be fine for most of the cases (excluding #5586).
