### ISSUE TITLE
Contributing docs unclear about how to debug locally

### ISSUE THREAD

**Issue by voithos** [prettier/prettier#5887]
The [contributing docs](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md) have a bullet point that says the following:

> If you would like to debug prettier locally, you can either debug it in node or the browser. The easiest way to debug it in the browser is to run the interactive `docs` REPL locally. The easiest way to debug it in node, is to create a local test file and run it in an editor like VS Code.

It unfortunately wasn't clear to me what the "interactive `docs` REPL" was, nor how to run a test file in an editor like VS Code. I feel like some more specific guidelines (a command to run, or something) would be pretty helpful for new contributors.

**Comment by voithos** [comment]
And to be clear, I still don't know how to effectively debug locally. :D Any tips would be appreciated (even before updating docs).

**Comment by lydell** [comment]
I usually run `./bin/prettier.js test.js` and `./bin/prettier.js --debug-print-doc test.js` (where `test.js` is a file I just made with the syntax I’m trying to print) to play around with things. Then I move over to making Jest test cases. I don’t use any debugger or so. There might be better ways of doing things, but that’s one way at least.

**Comment by FabHof** [comment]
If anyone is still interested: I make a test file like @lydell and then use the VS Code to debug prettier. Here is the configuration for the VS Code `launch.json`:

```JSON
        {
            "type": "node",
            "request": "launch",
            "name": "Launch test.js",
            "program": "${workspaceFolder}\\bin\\prettier.js",
            "args": [
                "test.js"
            ]
        }
```
