### ISSUE TITLE
prettier complain about html doctype in vscode

### ISSUE THREAD

**Issue by krave1986** [prettier/prettier#5892]
I am new to prettier and thought this is already fixed but can not find a solution to this.
So if close this issue, please point me to the correct solution.

I use eslint and prettier as a plugin in vscode.
If I use html template to auto generate html for me, which is really simple and popullar at all.
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Page Title</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" media="screen" href="main.css">
	<script src="main.js"></script>
</head>
<body>
	
</body>
</html>
```
vscode complains that at first line:

> Parsing error: Unexpected tokeneslint(prettier/prettier)

Please let me if I missed any. Thanks.

**Comment by lydell** [comment]
Maybe the `prettier/prettier` rule in your ESLint tries to parse the code as JavaScript, not Vue?

The easiest way to debug this kind of issues is to first get everything working on the command line, then in your editor. You often get more detailed error messages on the command line, and it makes it easier for others to reproduce your issue and help out.

To get you started: Try running `eslint your-file.vue` and keep going from there.

**Comment by krave1986** [comment]
@lydell 
Hi, I just tried your suggestion and here is the output from cli:

> C:\Learn\Vue\create\hello-world> .\node_modules\.bin\eslint .\public\index.html
> { parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
> 
> C:\Learn\Vue\create\hello-world\public\index.html
>   1:2  error  Parsing error: Unexpected token  prettier/prettier
> 
> ✖ 1 problem (1 error, 0 warnings)

How did you know I am working on a vue project? 👍 
But the file throwing problems is index.html and the project is generated from vue-cli.

Maybe package.json would help so I paste it here:
```
{
	"name": "hello-world",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"serve": "vue-cli-service serve",
		"build": "vue-cli-service build",
		"lint": "vue-cli-service lint"
	},
	"dependencies": {
		"vue": "^2.5.22"
	},
	"devDependencies": {
		"@vue/cli-plugin-babel": "^3.4.0",
		"@vue/cli-plugin-eslint": "^3.4.0",
		"@vue/cli-service": "^3.4.0",
		"babel-eslint": "^10.0.1",
		"eslint": "^5.8.0",
		"eslint-config-prettier": "^4.0.0",
		"eslint-plugin-prettier": "^3.0.1",
		"eslint-plugin-vue": "^5.0.0",
		"prettier": "^1.16.4",
		"vue-template-compiler": "^2.5.21"
	},
	"eslintConfig": {
		"root": true,
		"env": {
			"node": true
		},
		"extends": [
			"plugin:vue/essential",
			"eslint:recommended",
			"prettier"
		],
		"plugins": [
			"prettier"
		],
		"rules": {
			"prettier/prettier": "error"
		},
		"parserOptions": {
			"parser": "babel-eslint"
		}
	},
	"postcss": {
		"plugins": {
			"autoprefixer": {}
		}
	},
	"browserslist": [
		"> 1%",
		"last 2 versions",
		"not ie <= 8"
	],
	"prettier": {
		"tabWidth": 4,
		"useTabs": true,
		"htmlWhitespaceSensitivity": "ignore",
		"jsxBracketSameLine": true,
		"printWidth": 128
	}
}
```

**Comment by lydell** [comment]
> How did you know I am working on a vue project?

I thought I read you were, then I was lucky :)

> { parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.

> Maybe package.json would help so I paste it here:

Thanks. Now I can reproduce the issue.

Note that running `./node_modules/.bin/prettier public/index.html` works, so it's something about the ESLint config that is wrong.

As far as I know, ESLint only works on .js files by default – or rather, it treats _any_ files you give it as JS. I think you need to install https://github.com/BenoitZugmeyer/eslint-plugin-html to be able to run `eslint some-file.html`. After that, the `prettier/prettier` rule hopefully tells Prettier to use the HTML parser. But I've never done this myself so I'm a little unsure about the details. Let me know of any progress!

**Comment by lydell** [comment]
No wait – I'm confused.

ESLint is a tool that works with JavaScript (and near identical languages like TypeScript through plugins) ("ES" stands for "ECMAScript", the JavaScript standard.) It can also work with `<script>` tags inside HTML and Vue, through "processor" plugins.

Running `eslint file.html` means "I want to run ESLint on the JS inside this HTML file". But you're trying to work with the _HTML_ of the file. That's (as far as I know) nothing that ESLint can do.

So when you want to run Prettier on other files than .js, you can't do it through ESLint. You need to run it directly. There's a Prettier plugin for vscode, too.

Hope this helps!

**Comment by krave1986** [comment]
It turns out that prettier can not infer the correct parser for html file or maybe default parser not able to deal with html file correctly.
According to prettier official doc, I told which parser to use when it meet *.html files like this:
```
"prettier": {
		"tabWidth": 4,
		"useTabs": true,
		"htmlWhitespaceSensitivity": "ignore",
		"jsxBracketSameLine": true,
		"printWidth": 128,
		"overrides": [
			{
				"files": "*.html",
				"options": {
					"parser":"html"
				}
			},
			{
				"files": "*.vue",
				"options": {
					"parser":"vue"
				}
			}
		]
	}
```
Everything in index.html works fine. Prettier even works for <script> tag inlined in html file.

**Comment by lydell** [comment]
> It turns out that prettier can not infer the correct parser for html file

Yes it can. I tried it and it works. If you share what you did maybe we can find out what happened.
