### ISSUE TITLE
Add option for redundant parens around JSX expressions

### ISSUE THREAD

**Issue by asos-richardgibson** [prettier/prettier#5893]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTAHSk0wB4ATASwDcA+Y0wmMgQ0wAsAnOAMz0IgA9EIDmECKIA2cAHSQAtoKEMS5IdXogANCAgAHGFXTJQrLlwgB3AArmEaZCFY0IVCjpAAjLqzABrOBgAZX0-KihRZBguAFc4XQ4YBSkAdQ4qeDQwsDhgh0zaTIBPJzA0R10ItDguGBtfUQVWZF5WKRrdACs0bAAhXwCg4NYFOAAZCLhW9s6QHuxgiOk4AEVYiHgZjoSQMK4aricvVi9iqWhPfS4ImFT3GA5kAA4ABl1riBrU330na7ghxo010PAAjrEqDwGqwmi0kG0droagoqNE4rs0MsZOtNtMEbNdjBTvcKI9kAAmXQxVhUKTLADCEAUzScUGgIJAsRqABVTo4CUjnBhtnMKBAwKLdhBYjB9LKKVKAL5KoA)

**Input:**
```jsx
const x = 
  <div>
  	<a href="//google.com"/>
  </div>
```

**Output:**
```jsx
const x = (
  <div>
    <a href="//google.com" />
  </div>
);

```

**Expected output:**
```jsx
const x = 
  <div>
  	<a href="//google.com"/>
  </div>
```

---

Prettier currently (for reasons that I just cannot fathom) wraps parens around multiline JSX expressions. Why? JSX already has a _very_ clear open and close syntax; the parens are completely redundant and do literally nothing except add noise. (I am, however, aware of the `return` situation in which they're actually necessary.)

I've been using Prettier on various projects for around a year now, although I'm currently on my first React project and I can see from GitHub that Prettier has flip-flopped on this issue a couple of times.

I know that part of Prettier's philosophy is that it should be opinionated and should not add options unless absolutely necessary, but if there was ever a case of needing an option I think this is it.

**Comment by lydell** [comment]
Hi! You are completely correct that those parentheses are unnecessary. Here's why Prettier adds them anyway:

- https://github.com/prettier/prettier/issues/1291#issuecomment-294367708
- https://github.com/prettier/prettier/issues/3993#issuecomment-366508901

> I can see from GitHub that Prettier has flip-flopped on this issue a couple of times.

Really, have we?

In summary – this has been discussed before and is not going to change. It's easy to get used to though. Hope this answers your question!
