### ISSUE TITLE
trailingComma setting ignored when scss parser is used

### ISSUE THREAD

**Issue by krishnagopinath** [prettier/prettier#5895]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAllMAbArgEzgAIBnAQwDM4BaMgJzjIAoWAHM-fTAc2oCMIMGBAC2RAIwA2VgA8iAoaICUAGiVKA3CBUgIrGOmglkoenQgB3AAr0ExlGQBuEdPm0g+dMmADWcGADK7GA8yDB0uHA6ABYwItgA6tHo8CTBcAF2KeiOKQCeyOAkxjqYJHB0MFZe3CJkyBRk2OU6AFYkMgBCXr7+AWQicAAymHANTS0g7TIBPNhwAIq4gmNIjc1RIOx05XSFJGDF7qx0mDAJrjDRyAAcAAw6JxDlCV6shSdwu45jOgwAjrh0AxqmRavU1hNNuUROgwhFoXNFst4OMNjoYGQ+Bd8FdkAAmDFedDYHgAYVEdUKTWw7lw5QAKlj7OtJmQSDA0ZN8BAwFzNhBcDBWEL8fyAL7ioA)
```sh
--parser scss
--trailing-comma all
```

**Input:**
```scss
@include safe-area(((padding-bottom 16px bottom),));
```

**Output:**
```scss
@include safe-area(((padding-bottom 16px bottom)));

```

**Expected behavior:**

It should ideally not strip the trailing comma. I saw that this was reported earlier in #4076 and was apparently fixed in PR #4317. But when I try it now, the formatter removes the trailing comma.

Any help looking into this would be great! 🙏

**Comment by lydell** [comment]
In JS (which the option originally comes from), we _don't_ put trailing commas in single-line things (even with the option turned on):

```js
// We don't do this:
[1, 2,];
{ a: 1, b: 2, };
f(1, 2,);
```

Only in multi-line cases:


```js
[
  1,
  2,
];
{
  a: 1,
  b: 2,
}
f(
  1,
  2,
);
```

So the comma being removed in your case sounds expected to me.

**Comment by damienwebdev** [comment]
This should not be closed. This actually matters in `SASS` given the nuance of list vs. single-value typing.

For example:

```scss
type-of(("a")) //[string] a
type-of(("a",)) //[comma-list] ("a",)
```

**Comment by damienwebdev** [comment]
Removing the comma during a format actually changes the type of the value, which can be extremely detrimental if you're not careful. While this is mostly just silliness within SASS's typing system, prettier should still handle it.

**Comment by evilebottnawi** [comment]
@damienwebdev stop writing in old issue, open new issue with example
