### ISSUE TITLE
CLI exit status not documented

### ISSUE THREAD

**Issue by Eeemil** [prettier/prettier#5896]
Apparently, prettier can terminate with exit status 0, 1 and 2. However, I found no documentation specifying what differs between exit status 1 and 2.

**Comment by j-f1** [comment]
I believe it’s:

0. Everything formatted properly 🎉
1. Something wasn’t formatted properly 😢
2. Something’s wrong with Prettier 🤯

**Comment by jamesgeorge007** [comment]
@j-f1 I would take this up :+1: It would be great if you could right files to work with as I'm not that aware of the code-base :clap:

**Comment by jamesgeorge007** [comment]
@j-f1 I would take this up :+1: It would be great if you could point me to the right files to work with as I'm not that aware of the code-base :clap:

**Comment by jamesgeorge007** [comment]
@j-f1 Kindly have a look at #6049 and let me know your thoughts :smiley:
