### ISSUE TITLE
Allow two blank spaces and enable block padding

### ISSUE THREAD

**Issue by ackvf** [prettier/prettier#5897]
Related closed https://github.com/prettier/prettier/issues/1613

I would like to open this suggestion once more as the (1) inability to keep two blank lines (or at least disable line-collapsing completely) is a major setback for me. _Imagine the two blank lines as a heading of a code block._
Moreover, (2) forcing _no blank line at blocks end_ makes actually the code harder to read as it forces the Container's children to stick to it. It is exactly the opposite of what you do with object literals and arrays where you pad the children from sides. `const obj = { a: 1, b: 2, c: 3 }` so why suddenly make:

```
    // bad
    <Parent>
      <Children1/>

      <Children2/>

      <Children3/>
    </Parent>
```

```
    // good
    <Parent>

      <Children1/>
      <Children2/>
      <Children3/>

    </Parent>
```

Now hear my reasoning behind this:

_1)_ Allowing two blank lines provides better visual clues and actually makes the code looking better and easier to scan with eyes. It is also almost mandatory for workspaces that use 2 spaces isntead of 4, allowing to transform the horizontal clues into vertical.

Normally you would use **one** blank line to separate variable instantiation, function calls, control flows, etc. However, **two** blank lines turn out to be useful at distinguishing between large bodies of self-contained functionality. This practice is actually **very** common.

### contextual scoping heading 1
> _Now imagine if I haven't put a contextual delimiter here, such as the heading. The text would melt together and create one block of unstructured text. Same applies to code, but obviously we don't have headings, paragraphs, horizontal rules, etc. except for comments and white spaces._

Here, in the picture below, you can see some grouping. At first you notice a _"superblock"_ called **S**.
The superblock groups related content and provides a layout for inner form items that are semantically grouped by a `name`. However, you will only notice three distinguish groups **1, 2 & 3** even though there are **~6**.

_2)_ Highlighted in blue is my second point. It is quite hard to tell where does the container start really.

![image](https://user-images.githubusercontent.com/2313018/53246616-80d40280-36b1-11e9-9a58-d1f44773b5ca.png)

Now compare with the second picture. Spacing has been reduced from 4 to 2, which actually makes the code **harder to follow**, however, it works great with column width. And since we lost some visual clues, we have to provide additional ones.

### I don't have anything else to say, the code is just better to orient in.

![image](https://user-images.githubusercontent.com/2313018/53246713-b842af00-36b1-11e9-9779-ecd20c9a55ca.png)

# note
> I am very sorry! Due to prettier **bad** formatting, I have mistakenly compared slightly different code without even noticing. _I have also misplaced the comment there because of this :) ._
> ![image](https://user-images.githubusercontent.com/2313018/53247133-dc52c000-36b2-11e9-9a64-eaf79a2f8cff.png)

Here are the original code snippets, without annotations:

https://user-images.githubusercontent.com/2313018/53247343-6864e780-36b3-11e9-94bd-f170b003235d.png
https://user-images.githubusercontent.com/2313018/53247384-7e72a800-36b3-11e9-89ec-a74c12db3402.png

**Comment by lydell** [comment]
This is most likely not going to happen, but we could just as well leave the issue open to see if it attracts other people.

**Comment by lyziane** [comment]
This is what is stopping me from using prettier. All the formatted code is stuck together and hard to read. At least a way to disable line-collapsing would be nice...

**Comment by lydell** [comment]
More than 1.5 years later this has only received 6 👍s. See the [option philosophy](https://prettier.io/docs/en/option-philosophy.html).
