### ISSUE TITLE
Inconsitent formatting for one specific line (always the same line)

### ISSUE THREAD

**Issue by jisuo** [prettier/prettier#5898]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ33hIGEIBbLKBfAXj2AB0o894aAbAQ3gA0bDoRjYI3bnGxICfIkTwAVOBWq16zYRwLQS2AK5gYOABQASKAHMASnAAmBtAEot7HRwDk1gJJQAVnDGngDcbNoeMAAWAJZEAHQGxAYARkRg2DEpcHhMlrYOTvGEdMam0XHxVLwYAMow-HACzAC+zuWxRM5h7hwtEXgD1XUN8KYkja6svTrYcDAG2OzTHpGqMLIT8PFkMEIzfT0e-e4nLSACIBAYMDF6yKC82OIA7gAKTwhEyCC8AG4QGL2C4gFLYXhgADW81qGAhMWsyDEBiaICiMCo3AA6rEyHCwHBal8Yrc-iSAJ4-MAKEEIojSGBvcFWarIABmvG49Mu-iIaAAQuCoTDeFQ4AAZBFwdmc7kgXloWoIqxSACKBgg8BlXNRcOw9OwPxSvBS5O40BBGEysCxQOiyAAHAAGS5WiD0rHgjA-K2qaR-aWXOYARwMMTmTN4LN42rl9KoMSRhlRRGVao1WqQyNRDRStvs9qQACZLmJeDFuMrKFRWShVABWEEGelKE3fJAcnUtFpAA)
```sh
# Options (if any):
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "parser": "babylon",
  "printWidth": 80,
  "proseWrap": "preserve",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false
}
```

**Input:**
```jsx
export const testComponent = {
  template,
  controller: class TestComponent {
    constructor($ngRedux) {
      'ngInject';

      this.unsubscribe = $ngRedux.connect(this.mapState, {})(this);
    }
    
    mapState(state) {
      return {
        test: state.test,
      };
    }
  }
}
```

**Output:**
```jsx
export const testComponent = {
  template,
  controller: class TestComponent {
    constructor($ngRedux) {
      'ngInject';

      this.unsubscribe = $ngRedux.connect(this.mapState, {})(this);
    }
    
    mapState(state) {
      return {
        test: state.test,
      };
    }
  }
}
```

**Expected behavior:**

Using VS Code and using `prettier-vscode` extension 1.8.1 I get inconsistent results

sometimes this line:

`this.unsubscribe = $ngRedux.connect(this.mapState, {})(this);` is formatted exactly like that

sometimes it is formatted like this instead:

```
this.unsubscribe = $ngRedux.connect(
  this.mapState,
  {}
)(this);
```

The lines always has the same width and same indentation.

**Comment by lydell** [comment]
Hi! How can we reproduce this?

**Comment by jisuo** [comment]
Hey @lydell I've experienced this in VS Code 1.31.1 with prettier-vscode 1.8.1 extension.

**Comment by lydell** [comment]
Thanks! Can you provide steps to reproduce? Using the CLI only (no VS Code) if possible.
