### ISSUE TITLE
Markdown: HTML formatting broken if the beginning tag starts after a list item

### ISSUE THREAD

**Issue by mgol** [prettier/prettier#5907]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAQXQGwJYDOM6e8AtgHQA6UAPACZwwCGeOBAfLQQK5lnMATgE8OAZT4CRtAPS9+Q0TVoAHDjRoZs+IiXLUoymWqOMWbTjRAAaEBBUw80AslBDBEAO4AFIQhcozABuEHj0NiAARoLMYADWTGIqsXhQAObIMII8cLYAFjBkOADqeaRwBMlgcGL+pHhBpMLI4AQutqkEcIIw3jFpAsgAZszsuSAAVgQAHgBCMfGJzGRwADKpcMOjXbZT02KpaThwAIo8EPBbY7bJgl2CLVJx9F5QESqCqTDFYTB5yAAOAAMNw8XWKMRULQ+FW6QU2tkEcAAjjw8Ei+swBswrjsQF0yHhMtlxgRDsczhdNkgRtcQCxIj96H9kAAmWxZVj4dIAYQgChaUGgCJAPC6ABVmJEArSugBfOVAA)
```sh
# Options (if any):
None
```

**Input:**
```md
- A list item.
<details><summary>Summary</summary>
<p>

- A list item.

</p>
</details>
```

**Output:**
```md
- A list item.

  <details><summary>Summary</summary>
  <p>

- A list item.

</p>
</details>
```

**Expected behavior:**
I'd expect output like:
```md
- A list item.

<details><summary>Summary</summary>
<p>

- A list item.

</p>
</details>
```
If I enter such Markdown manually, Prettier doesn't touch it.

The output Prettier produces for the initial input is broken; the original file defines proper HTML with list items inside of the `details`; the output Prettier produces takes the list item outside of the `details` element. Compare on GitHub:

Before:

-----

- A list item.
<details><summary>Summary</summary>
<p>

- A list item.

</p>
</details>

-----

After:

-----

- A list item.

  <details><summary>Summary</summary>
  <p>

- A list item.

</p>
</details>

-----

**Comment by evilebottnawi** [comment]
Thanks for the issue, bug
