### ISSUE TITLE
Inconsistent string concatenation between variable assignments & function calls

### ISSUE THREAD

**Issue by mgol** [prettier/prettier#5912]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTAcgEFMA3OAJwE8Aacquhm+imzAG2gHNMNKAllG6FMAaiKk2Taa0Zz2XYXxiDhhANwAdKADMAFCWYz5xhdU48VakeMlmHs45eX8hIgJTaoIWiAgADjAC6MigAIaUlBAA7gAKkQhoyCDhZBACACa+IABGlOFgANZwMADKAYXuyKoArnB+ABYwALYcAOqNAvBolWBwZUndAmTd1ClgaMl+QmhUMHEF3C3hyLrhHHN+AFZo2ABCBcWlZeEtcAAyQnBrG1sgu9hl7hxwAIq1EPC3mw0glZQ5pQUrlwrk4BwcgE1DB2lkYI1kAAOAAMfmhEDm7QKARS0LgQIoOUocAAjrUBCTFuFlqskOtfn45i0BDVKPUmS93p9vvS7n8YGC4ZkEcgAEx+VThAQcdwAYQgLRWKSg0BuflqcwAKmDknzfgBfA1AA)
```sh
# Options (if any):
None
```

**Input:**
```js
const x = 'A very, very, very, very long string' + 'A very, very, very, very long string';
f('A very, very, very, very long string' + 'A very, very, very, very long string');

```

**Output:**
```js
const x =
  "A very, very, very, very long string" +
  "A very, very, very, very long string";
f(
  "A very, very, very, very long string" +
    "A very, very, very, very long string"
);
```

**Expected behavior:**

I'd expect the following output:
```js
const x =
  "A very, very, very, very long string" +
    "A very, very, very, very long string";
f(
  "A very, very, very, very long string" +
    "A very, very, very, very long string"
);
```

Both cases feature the same string concatenation but the first one doesn't indent subsequent lines. One could argue another option would be to remove indentation altogether but that'd make it much harder to read function calls with more than one parameter which now looks nice, e.g. currently Prettier prints:
```js
f(
  "A very, very, very, very long string" +
    "A very, very, very, very long string",
  "A very, very, very, very long string" +
    "A very, very, very, very long string"
);
```
if you duplicate the `f` parameter from my original example.

**Comment by lydell** [comment]
I'm pretty sure this is on purpose, but I can't find the issue(s) I think I'm remembering right now.

**Comment by evilebottnawi** [comment]
i am :-1: on this too

/cc @mgol it is expected,

look
```js
f(
  "A very, very, very, very long string" +
    "A very, very, very, very long string"
);

f(
  "A very, very, very, very long string" +
  "A very, very, very, very long string",
  "A very, very, very, very long string" +
  "A very, very, very, very long string",
  "A very, very, very, very long string",
  "A very, very, very, very long string",
  "A very, very, very, very long string" +
  "A very, very, very, very long string",
);
```

It is very hard to read, but output for variable look good

**Comment by mgol** [comment]
It just feels inconsistent when sometimes the line after `+` is indented and sometimes it's not.

**Comment by evilebottnawi** [comment]
@mgol prettier search better way to format and improve readability, in some cases it is impossible to be consistent because readability more important to us, also changing this create a precedent where people want to return to previous behavior, sorry we don't want change current output right now, maybe we revisit this in future
