### ISSUE TITLE
ES6 string template misaligns closing brackets with html tags containing dash

### ISSUE THREAD

**Issue by Kisfejes** [prettier/prettier#5913]
I have experienced an issue with formatting custom elements (using lit-html). I think that the closing `>` symbols are misaligned. It works well if you remove the `custom-` prefix from the element. It's even looks worse, if you have nested custom elements.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALGBbANgAwDxgCuAzjBBgLQAmAlgG4AEW0A5hQIYwwBONARoXgBeADohmUNnXZZCcCgEYxTVhy68B8CgCZR41dNnztyiW049+guHrMVDcxWIB8AFTgAPGAwDC0eLB4APREpOTU9M44ANwiUCAANCAQAA4wNNDEyKDs3NwQAO4ACrkIWSjsdBA0VIkgfNzsYADWcDAAyilNNJLIPHJJ6NgA6qg08MRdYHDtZeP04wCeyODEWUk9xHDcMEWNLBjsyABmMltJAFbEHgBCjS1t7ewYcAAyPXAnZ3CX1+09LCwcAAioQIPAvlhziAutwttwVsdmAU6ileLBhjUYKhkAAOAAMSTREC2w0aKRWaLg8LonyS3DgAEdCDQGXt2AcjkhTlCfiAthgaH1uAN+QCgaDwZ9ud8kjB2HxMVRschtHLGjQsAC-BhDisoNA6SASHBXAryjytgBfK1AA)
```sh
--parser babylon
```

**Input:**
```jsx
html`<custom-div long-attribute="long-value-1" long-attribute-2="long-value-2" long-attribute-3="long-value-1">Text Content</custom-div>`;
```

**Output:**
```jsx
html`
  <custom-div
    long-attribute="long-value-1"
    long-attribute-2="long-value-2"
    long-attribute-3="long-value-1"
    >Text Content</custom-div
  >
`;
```

**Expected behavior:**
```jsx
html`
  <custom-div 
    long-attribute="long-value-1" 
    long-attribute-2="long-value-2"
    long-attribute-3="long-value-1"
  >
    Text Content
  </custom-div>
`;
```

**Comment by lydell** [comment]
I don't think this has to do with template literals. It's just the way HTML is printed.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeMBXAzjCBbAWgBMBLANwAIAbaAcwIEMYYAnEgIw3gF4AdEGlHpkGVDHAIBGftTqNmbTvAIAmPgLkixElTMH0mrDlwkBmdfoJbxU-gD4AKnAAeMCgGFo8WKgD0mHHxicjsQABoQCAAHGBJoLGRQBhYWCAB3AAVkhASUBjIIEiJwkHYWBjAAazgYAGUoipIhZFZxCIALGDwqAHV2kngsBrA4WpyB8gGAT2RwLASIpqw4FhgM8to8BmQAM1FliIArLGcAIXKqmtqGPDgAGSa4Xf24I5PaptoqOABFDAh4M8qAcQA0WMsWLNOt0SlE2LAekUYO1kAAOAAMEThEGWPXKUVmcLgELITwiLDgAEcMCQKesGJttkg9sDXiBlngSC0WG12Z9vn8AU9mS8IjAGOxEURkcgVGLyiQqJ9PHgtrMoNAySBsHAHBLcizlgBfI1AA)
```sh
--parser html
```

**Input:**
```html
<custom-div long-attribute="long-value-1" long-attribute-2="long-value-2" long-attribute-3="long-value-1">Text Content</custom-div>
```

**Output:**
```html
<custom-div
  long-attribute="long-value-1"
  long-attribute-2="long-value-2"
  long-attribute-3="long-value-1"
  >Text Content</custom-div
>

```

You can use [--html-whitespace-sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) to achieve what you want, but read [whitespace-sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) first.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeMBXAzjCBbAWgBMBLANwAIAbaAcwIEMYYAnEgIw3gF4AdEGlHpkGVDHAIBGftTqNmbTvAIAmPgLkixElTMH0mrDlwkBmdfoJbxU-gD4AKnAAeMCgGFo8WKgD0mHHxicjsQABoQCAAHGBJoLGRQBhYWCAB3AAVkhASUBjIIEiJwkHYWBjAAazgYAGUoipIhZFZxCIALGDwqAHV2kngsBrA4WpyB8gGAT2QQElooCBY4EqasOBYYDPLaPAZkADNRdYiAKyxnACFyqprahjw4ABkmlaQjqhOQc+daptoqHAAIoYCDwQ7HOARBosdYsWadbolKJsWA9IowdrIAAcAAZoal1j1ylFZii4HCyCsIssAI4YEjLbYMXb7d6QiLrPAkFosNogLD-QEgsFvD5fGAMdjooiY5AqCKsBgkKj-Tx4PazRZQakgbBwBxS3LiuAAX1NQA)
```sh
--html-whitespace-sensitivity ignore
--parser html
```

**Input:**
```html
<custom-div long-attribute="long-value-1" long-attribute-2="long-value-2" long-attribute-3="long-value-1">Text Content</custom-div>
```

**Output:**
```html
<custom-div
  long-attribute="long-value-1"
  long-attribute-2="long-value-2"
  long-attribute-3="long-value-1"
>
  Text Content
</custom-div>

```

**Comment by Kisfejes** [comment]
Thank you for your answer, it makes sense now!
