### ISSUE TITLE
Mapped type removed incorrectly

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#5914]
**Prettier 1.16.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgDEIJDgAdKQwgbQCNdMlCBnGTdAcwF1WmALwDc1AL7VqMAJ4AHIqXIBeCtVqNmrDlyh8BuEeOEgANCAiyYqaG2ShmmCAHcACswS2UuAG4RUAE1MQBkx8AGs4GABlWXweZE4AVzgzAAsYAFsAGwB1VNR4NliCKI8C1G8C6WRwNlszdDYsGBdQ7gzcZDwsprMAKzYADwAhULAI6NwMuAAZdDgu3B6UkAHBqJ4suABFRIh4ReWzWMwmzBqZeTYwLksg2R0YHICYVOQADgAGY8cmnNDZDUHnAzt4FmZMHAAI6JVCQ1q4dqdJDdXogJoZVAJTDJMxsTY7PYHFFLNEwXAMZ7+V7IABMZk4uFQWR4AGEIBkOjUoNBwSBEk0ACoUzyouBiMRAA)
```sh
--parser typescript
```

**Input:**
```tsx
interface Foo {
  [bar: string]: baz;
}

type Foo = {
  [bar: string]: baz;
};
```

**Output:**
```tsx
interface Foo {
  []: baz;
}

type Foo = {
  []: baz;
};

```

**Expected behavior:**

Same as input

**Comment by kachkaev** [comment]
🤔 seems like all works in the playground (1.16.4). I just followed your link.

<img width="1224" alt="screenshot 2019-02-26 at 20 05 31" src="https://user-images.githubusercontent.com/608862/53442770-edc50080-3a01-11e9-8e42-05c8721c1b2e.png">

**Comment by j-f1** [comment]
Caaaching 🤦‍♂️
