### ISSUE TITLE
Add priority to use 'const'

### ISSUE THREAD

**Issue by cn-src** [prettier/prettier#5916]
Add priority to use 'const', If the variable is not assigned again.

It makes the code more rigorous. Off by default.

Like this:
**Input:**
```js
let a = 'demo'
export default a
```

**Output:**
```js
const a = 'demo'
export default a
```

**Expected behavior:**

**Comment by lydell** [comment]
Hi! This type of transformation is out of scope for Prettier. See https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about

Use the [prefer-const](https://eslint.org/docs/rules/prefer-const) ESLint rule instead – it has autofix!
