### ISSUE TITLE
How to format code based on eslint config in browser ?

### ISSUE THREAD

**Issue by DevinCarl** [prettier/prettier#5917]
**Environments:**
- Prettier Version: 1.16.4
- Running Prettier via: Browser API,
- Runtime: Chrome Safari...
- Operating System: Windows, macOS

**Expected behavior:**
Now I'm using prettier standalone.js and parser-babylon.js in browser to format my react code in browser. 

and I want to import eslint config to prettier format options, so I can get code just like using prettier-eslint with eslint config running by node.

how can I do this?

**Comment by lydell** [comment]
Prettier has an online version: https://prettier.io/playground/

So has ESLint: https://eslint.org/demo/

So it feels like you should be able to make both of them work together on the web. However, this is not the right place to ask. Learn about webpack and running Node.js packages on the web, start experimenting and ask on StackOverflow or similar when you get stuck.
