### ISSUE TITLE
Rule: Add trailing indentation to all empty padded lines

### ISSUE THREAD

**Issue by Yzrsah** [prettier/prettier#5923]
I'm looking for a code formatter that is friendly to a convention that I standardize on:
```
const f = x => {
	// something
	g(x)
👉
	// something else
	h(x)
}
```
The **👉** indentation is required to match the block scope.

# Rule

If there's an empty padded line, it is required to be indented to the same level as the block scope.

# Why?

- Editors don't allow you to click on the empty space and get a cursor at the indent level.
- You typically have to move to the empty line at column 0, then press tab to re-tabulate,
*or*
- You typically have to move to the end of the previous line, then press enter. *Just to invoke smart behavior to try to repair the missing indentation on the next line*
- Every IDE has a different behavior for adjusted automatic indentation on empty lines to deal with this problem.

# Much, much better:

- Adding trailing indentation to empty padding lines resolves all issues.
- It does not behave differently in IDE's and does not require special behavior. You don't have to think about how the IDE works.
- Your cursor is always at the right indent level.
- Your cursor is always "ready" at the location you will begin typing the code.
- It doesn't break any code or cause any problems with anything.
- You don't have to re-indent, or move your cursor to the previous line and press enter, or do anything.
- You can paste on the empty line without being at the wrong indent level.

**Comment by kachkaev** [comment]
Hi @Yzrsah 👋

I understand your issue and often struggle with it myself too. However, I believe it could be better solved in the text editor rather than by adding lots of spaces to billions of files that are covered by Prettier. Just think of those endless git diffs that need to be committed and also about those extra terabytes of data this change would generate worldwide.

**Comment by j-f1** [comment]
Also, if you were to put a line of code there, Prettier would automatically indent it for you.

**Comment by Yzrsah** [comment]
I'm worried about it being *Prettier* for the programmer, but not *Minnier* for the server. I use other minifiers for that.

I don't consider Prettier to be a minifier: **It's not possible to be logically consistent without banning those pesky people who are consuming N's of terabytes with the usage of `useTabs: false` + `tabWidth: 4`**

They actually need to be banned from using that option in Prettier, or they need to use StandardJS because they are harming the planet.

Because the StandardJS **enforces** halving the number of bytes spent on whitespaces:
- Which we established is a priority that is actually important enough in order to enforce not allowing a programmer, or team, or someone who is paying for their own storage for their own uses, to have any option in a choice *that is measured in bytes*

# But the argument is irrelevant:

I just tested on a source tree and my source is **smaller** with (Tabs + Trailing-Indent-on-all-empty-padded-lines) than it is after running with (Prettier + `useTabs: false` + `tabWidth: 4`).

**Comment by lydell** [comment]
I understand the arguments in favor of adding the spaces, but this is not going to happen. Thanks for the suggestion, though!

**Comment by Yzrsah** [comment]
Referenced here: https://github.com/xojs/xo/issues/379
