### ISSUE TITLE
Formatting while typing

### ISSUE THREAD

**Issue by thejameskyle** [prettier/prettier#593]
This is gonna be a fun issue...

So a lot of editors try to do code formatting while you are typing, and to varying degrees they all kinda suck at it.

While it's an okay experience to format on save or after the fact, it would be nice if things were auto-formatting while typing.

There's a couple messages in the language-server-protocol for "formatting requests":

- [Document Formatting Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-formatting-request)
- [Document Range Formatting Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-range-formatting-request)
- [Document on Type Formatting Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-on-type-formatting-request)

Each of this represents a different opportunity for prettier to fix the formatting of code.

One of the important pieces here will be that it will be possible to have an invalid program which Babylon will currently reject because the user hasn't finished making it valid. Will have to talk to Babylon folks about implementing a "loose" parser which can recover from mistakes (cc @hzoo @danez).

While the language-server-protocol doesn't work everywhere. If more tools like prettier embraced it, it would push more editors to formally implement it, which would be a nice effect.

**Comment by vjeux** [comment]
Fwiw, this is the API that Visual Studio implements and is known to have extremely good formatting while typing facilities.

**Comment by thejameskyle** [comment]
Actually... It's probably better to do this even before Babel does any error-recovery. If you tried to format an invalid program, you'd end up formatting it incorrectly in a lot of scenarios.

Example:

```js
far (var i = 0; i < 10; i++) {
  // ...
}
```

This would be parsed as:

```
- ExpressionStatement
  - CallExpression(far, [], {})
- VariableDeclaration
  - VariableDeclarator(i, 0)
- ExpressionStatement
  - BinaryExpression(i, "<", 10)
- ExpressionStatement
  - UpdateExpression("++", i)
- BlockStatement []
```

Which would be printed something like this:

```js
far();
var i = 0;
i < 10;
i++;
{

}
```

That would be really really annoying.

But there are other scenarios where you could get away with it:

```js
try {
  // ...
}

function foo() {
 // ...
}
```

Here you get a TryStatement that is simply missing it's handler or finalizer. Invalid, but you could probably print it without any issues.

I actually made an exhaustive list of "raised" errors in the parser (this is not every possible error) the other day here: https://github.com/babel/babylon/issues/343. That list would probably also represent errors that prettier could print regardless of. They fall into these two categories:

> - Errors caused by syntax that needs to be wrapped in other syntax (i.e. `return;` – can be put inside function)
>   - Not syntax which is invalid due to being wrapped in other syntax (i.e. `({a}) = 2;` – would have to be unwrapped)
> - Errors caused by syntax that is missing a child node (i.e. `try {} – catch {}` can be added programmatically)
>   - Not when missing a parent node, isn't useful/possible (i.e. `class { @foo }` – you can't attach the decorator to a method afterwards)

**Comment by vjeux** [comment]
This is something that we should explore at some point but it is not very actionable right now so I'm going to close this issue. If someone is interested in building this, that would be awesome!
