### ISSUE TITLE
forceBreakContent on <template> tag

### ISSUE THREAD

**Issue by rndmerle** [prettier/prettier#5933]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALGBbAG0wF4d8CADAHSipgB548AHAgQ3gD4AVOADwYB6Jqw5xONCiAA0ICMxgBLdMlBsATuogB3AAoaEaZCDYA3CIoAmMkACN1bMAGs4MAMrNHiqAHNkMdQBXOFlcQgB1bEV4NE8wODdDaMVTaIBPYzA0I1lvNDh1GF0HHzw2ZAAzNgJ82QArND4AIQdnVzc2PDgAGW84SurakAa+N28fAjgARUCIeAGakJBPdXz1Y1s2WzSCaBtmdW8YcKsYbGQADgAGWQOIfPCHZmMDuDXTftl1OABHQMVvsU2KVykgqotZPk8Ip-EElmhxpMZnN+mDBksYFsTpYzsgAEyyAJsRQEcYAYQgeDKxig0E+IEC+W4WyMaMWAF92UA)
```sh
--parser babylon
```

**Input:**
```jsx
const html = html`
	<template>Text</template>
`
```

**Output:**
```jsx
const html = html`
  <template
    >Text</template
  >
`;

```

**Expected behavior:**
```jsx
const html = html`
	<template>Text</template>
`
```

I guess it's because of the <template> portion of Vuejs SFC files. But when using <template> for slots for instance you really don't want to break it down before print-width is reached.
```
<Component>
  <template #slot1>{{ text }}</template>
  <template #slot2><SubComponent /></template>
</Component>
```

Thanks :D

**Comment by thorn0** [comment]
fixed by #6284
