### ISSUE TITLE
Opt out inserting spaces between Japanese and Latin

### ISSUE THREAD

**Issue by takenspc** [prettier/prettier#5938]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEhlBkHYMhw00B9mh7BkDD-AwgMrH7EBqA4oFIMgEQyDODABrEAyAtAGIDygVgyCWDOkABRoGUIwOYMgfO1Af86AZBkBCNoECGQJEMgGIZA0QyAAOUA0QYBC3XoFPTQDTmgPKjAIr6AJJ3SBAyMBvcoCSGQBhRgB-jA6gyB9BkBBDOjGBNBkBw-yAANCAQAA4wAJbQAM7IoACGAE6JEADuAApJCLEo8QBuEBEAJkEgAEaJ8WAA1nAwxKFVEVAA5sgwiQCucMEAFjAAtgA2AOq9EfDRjWBwxNkTEXkTAJ7I4NGxwc3RcIkw6ZUtA-HIAGbxQzvBAFbRAB4AQpU1dcTxA3CszXBnF1cgtzuxGaLSGcAAip0IPBfpceiBGokdok1sdEtUimkoKVQolmjARsUYL1kAAOAAMwVxEB2I0qoTWuLgyLyP2CiTgAEdOhEOQd4kcTkhznDgjsBhF2l14dEQWDIdCfsK-vCYPEyoSisTkAAmYIdeIRIYgwgQAbHNZQaBskCdHYAFXVORFOwAvq6gA)
```sh
# Options (if any):
--parser markdown
```

**Input:**
```markdown
この文書は，CSS，SVGおよびXSL-FOなどの技術で実現が求められる一般的な日本語組版の要件を記述したものです．
```

**Output:**
```makdown
この文書は，CSS，SVG および XSL-FO などの技術で実現が求められる一般的な日本語組版の要件を記述したものです．
```

**Expected behavior:**
Output and input are identical.

# Opt out inserting spaces between Japanese and Latin

Though Prettier inserts spaces between Japanese and Latin by default, inserting spaces is not widely adopted in Japan. Because adding spaces are considered as part of visual aesthetics and not as inserting physical characters.

## Examples:

Requirements for Japanese Text Layout doesn’t insert spaces
https://www.w3.org/TR/2012/NOTE-jlreq-20120403/ja/
> この文書は，CSS，SVGおよびXSL-FOなどの技術で実現が求められる一般的な日本語組版の要件を記述したものです．

Japanese ministry of education (Ministry of Education, Culture, Sports, Science and Technology) doesn't insert spaces.
http://www.mext.go.jp/b_menu/activity/detail/2019/20190219_2.htm
> 2月19日、柴山大臣は、東洋大学赤羽台キャンパスを訪れ、INIADの教育環境を視察するとともに、安齋隆 理事長、坂村健 学部長と意見交換しました。

Japanese Wikipedia doesn't insert spaces
https://ja.wikipedia.org/wiki/%E3%82%A6%E3%82%A3%E3%82%AD%E3%83%9A%E3%83%87%E3%82%A3%E3%82%A2
> 専門家によるオンライン百科事典プロジェクトNupedia（ヌーペディア）を前身として

Adobe doesn’t insert spaces
https://blogs.adobe.com/japan/cc-web-xd-february-2019-update-integrations-language-support-narration/
> すでにXDはPhotoshop、Illustrator、After Effectsとの連携ワークフローがこれまでになく容易になっています。

## Note

Please note that [Requirements for Japanese Text Layout](https://www.w3.org/TR/jlreq/#handling_of_western_text_in_japanese_text_using_proportional_western_fonts) doesn't recommend inserting physical space (U+0020)s between Japanese and Latin. Instead it recommends software should render text as if it adds quarter em space (Microsoft Word do this).

**Comment by sosukesuzuki** [comment]
I want to know whether Chinese and Korean are similar.

**Comment by chibicode** [comment]
+1 on this. Related PR: https://github.com/prettier/prettier/issues/5028

**Comment by thorn0** [comment]
Closing in favor of #6385
