### ISSUE TITLE
brackets alignment issue between prettier.io/playground and similar config with prettier standalone 

### ISSUE THREAD

**Issue by paulbrie** [prettier/prettier#5943]
Hi, 

there's a difference in the output of the following snippet in the playground VS the same options with prettier/standalone. A live version can be seen here: https://codesandbox.io/s/zk6q26226x
I can't get the brackets and the inner string to be indented and aligned.

![image](https://user-images.githubusercontent.com/3997538/53826206-cb426280-3f80-11e9-9ddd-a00404ed6d83.png)

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwB0QdTyGBuDbPfABWswBUAnpjgBnfFRr0QmPgFoYwsWzpRIUUQQDCJHABN8AXnyyImcYYB8+YKvz4mMAK44o+ADx7UAN3xgANiSiogByJOhwhgxgunoMlsCm5gB0qPDoAL7umoL+cPgAVqIAHgkABnb2VdXJMfo2qui6AOaoUEj4AIwADJjFrKoARrh6cDgdnX34ohD+qAaDgWAA1gNQmCR6XlDNE739ldXVGZVlJ25V7gD0OXmW117elmsZazr6yUlCIhYNFwxpODoBgdXhmb5iZKaHBtZqqV6qd56ZKjCgkJz+GBg8xGP72AHpEHSTBLOAAC1moxwDHhazgxU4BFR6Mx+CRrBAABoQGYYKhoKJkKBdNQAO7cXQIQUoEjeCDzLkgQY4MjLOAwADKGzAsOQMBwTjg3LJMHQ-gA6mTAaJtXANVK0j40oJkOBgoq2qIxliVc0msg0f4vdyisUAEIqlbqjXhOAAGTacADJCDRpAoY1sLyAEUnBB4MnU9yNjgvThXYMSINctBFbI2jBzfMYGTkAAObrF6he80qzCu2RiMbeJPcpgARycqCYvBIfpIheDIC96FQeoNadEWbgufzSaQgaXMCrTb0LeQACZufqSKg5jstDR-SgoNBRyAnF7+FXpYe4BkMiAA)
```sh
--parser babylon
```

**Input:**
```jsx
import React from "react";import PropTypes from "prop-types";
const Card = props => {
  return <div className="card">{props.item}<style jsx>{`
          .card {
margin: 10px;
border: 1px solid black;
padding: 10px;
          }
  `}
    </style></div>;
};
Card.propTypes = {
  "item": PropTypes.string
};
Card.defaultProps = {
  "item": "placeholder"
};
export default Card;
```

**Output:**
```jsx
import React from "react";
import PropTypes from "prop-types";
const Card = props => {
  return (
    <div className="card">
      {props.item}
      <style jsx>
        {`
          .card {
            margin: 10px;
            border: 1px solid black;
            padding: 10px;
          }
        `}
      </style>
    </div>
  );
};
Card.propTypes = {
  item: PropTypes.string
};
Card.defaultProps = {
  item: "placeholder"
};
export default Card;

```

**Expected behavior:**
The playground behaves correctly. It's the standalone version who returns a different output.

**Comment by j-f1** [comment]
Did you include the `css` parser? It’s required to format CSS-in-JS.

**Comment by paulbrie** [comment]
No, that was it. Thanks for your quick answer!

Live demo: https://codesandbox.io/s/zk6q26226x

The working code: 

```javascript
var { format } = require('prettier/standalone')
var babylon = require('prettier/parser-babylon')
var postcss = require('prettier/parser-postcss')
var http = require('http')

var unformattedCode = require('./unformattedCode')
var formattedCode = format(unformattedCode, {
  arrowParens: 'avoid',
  bracketSpacing: true,
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: 'preserve',
  requirePragma: false,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: 'none',
  useTabs: false,
  plugins: [babylon, postcss],
  parser: 'babylon'
})
```
