### ISSUE TITLE
Preserve line breaks before comment

### ISSUE THREAD

**Issue by radarsu** [prettier/prettier#5950]
**Before formatting**

![2019-03-08 00_08_59-gray layout vue - widgets - visual studio code](https://user-images.githubusercontent.com/7216948/53995979-1e5e1600-4137-11e9-9a55-08ac8dc5b458.png)

**After formatting**

![2019-03-08 00_09_06- gray layout vue - widgets - visual studio code](https://user-images.githubusercontent.com/7216948/53995982-20c07000-4137-11e9-864a-aa34b03c3bb0.png)

**Comment**

Prettier is opinionated - and so I think the default behavior (in html formatting) should be: **not removing single-line breaks before comments**. I guess most people will agree that first image is much prettier formatting.

**Comment by lydell** [comment]
Hi!

> I guess most people will agree that first image is much prettier formatting.

Heh – I would have guessed the opposite! I guess this means this is something people don't agree on :)

Prettier uses the same empty line rules for all languages it formats. We've had those rules for a long time, and they work good enough so we're not interested in changing them at this point. See https://prettier.io/docs/en/rationale.html#empty-lines

**Comment by radarsu** [comment]
1. Majority of coding best practices advice line breaks between blocks of certain objects, functionalities etc.
2. Majority of ux best practices say human eyes like free space between items too.

If your goal is to make people's code `prettier`, maybe you should reconsider this issue based on statistics/surveys.

`Empty lines at the start and end of blocks (and whole files) are removed. (Files always end with a single newline, though.)`
3. Actually removing line breaks in html is an exception from the general rule you apply, so it's counter-intuitive too.
