### ISSUE TITLE
Passing a class expression as the only argument of a function

### ISSUE THREAD

**Issue by aleclarson** [prettier/prettier#5951]
I'm doing something that I'm sure is rare, which is the following:

```js
const MyClass = wrap(class {
  foo = true
  bar = []
})
```

Prettier formats it like so:

```js
const MyClass = wrap(
  class {
    foo = true
    bar = []
  }
)
```

..which IMO is not only ugly, but also unnecessary, since the class expression is the only argument.

Would you consider changing this? 😬

**Comment by lydell** [comment]
Maybe. We have 500 other issue open, and this is, as you say, a rare case so don't expect much attention to this issue. Personally I like Prettier's version better. ¯\\\_(ツ)\_/¯

**Comment by phaux** [comment]
Prettier's formatting **is** better because it allows adding a JSDoc to the anonymous class

**Comment by evilebottnawi** [comment]
Yes, it is rare use case, we don't want modify output, anyway thanks for the issue, maybe we will revisit this in future
