### ISSUE TITLE
(JS) Quotes not converted correctly

### ISSUE THREAD

**Issue by muuvmuuv** [prettier/prettier#5952]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhuAB0oaaScsBzASyiqQ0A2izZsABlwCG1AEYBPALQdufRTHkk4VMOR4kY4gDSixTENLlKVvKIvJwpYGIoAWcHKjgxzJ1mIBySyoFZU5bRTh0GB5oAL8xGgBdFgBfECMQCANY-mRQKXJyCAB3AAVChCpkECkANwgeDAyQWXInAGtvAGUSJz4uZBhyLDhM1xhUHAB1Vx54Kj6wOG6q+Z46+fkasCpqzL4qOEoy9q5UKWQAMykcI8yAKyoiACF2sC6YbqkvABk+ODXW73EBPIjdAZ4ACKWAg8CBdzGID65CO5BqsikChw0BaJD0sGmTRgrmQAA4AAyZfEQI7TdokGr47THOqAzIOACOWB4DlOUnOlyQN0RmSOqB4QxGSKokLgMLhgOFwKRMCxRIwJOQACZMsMpDwcAMAMIQVAXGpQaDskBYI4AFSx1WViNSqSAA)
```sh
--parser babylon
```

**Input:**
```jsx
module.exports = {
  plugins: [
    `gatsby-plugin-typescript`,
    "gatsby-plugin-react-helmet",
    'gatsby-plugin-emotion',
    ]
}
```

**Output:**
```jsx
module.exports = {
  plugins: [
    `gatsby-plugin-typescript`,
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-emotion"
  ]
};

```

**Expected behavior:**
```jsx
module.exports = {
  plugins: [
    "gatsby-plugin-typescript",
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-emotion"
  ]
};

```

Is it somehow possible to tell prettier to always prefer a style of quotes? I prefer to use single quotes but sometimes when I copy code from Gatsby it has this backtick quotes and it would be nice if prettier can convert them to my choice too if there is no variable set inside. OR I tell prettier which quote I want to use instead of just `--single-quote`.

**Comment by lydell** [comment]
Hi!

These are _strings:_

```js
"one"
'two'
```

This is a _template literal:_

```js
`three`
```

Prettier does not convert between the two, as mentioned here: https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about

You can use the [quotes](https://eslint.org/docs/rules/quotes) ESLint rule if you want this behavior – it’s autofixable! See https://github.com/prettier/eslint-config-prettier#quotes for more information.

Hope this helps!

**Comment by muuvmuuv** [comment]
@lydell nice, thank you! I'm using TSLint in my project right now, will have a look if they do have the same as ESLint.

**Comment by muuvmuuv** [comment]
Perfect: https://palantir.github.io/tslint/rules/quotemark/

```json
{
  "rulesDirectory": ["tslint-plugin-prettier"],
  "extends": ["tslint-config-blvd/react", "tslint-config-prettier"],
  "rules": {
    "prettier": true,
    "radix": false,
    "quotemark": [true, "single", "jsx-double"]
  }
}
```
