### ISSUE TITLE
RFC: Option to ignore long "throw new Error" statements

### ISSUE THREAD

**Issue by aleclarson** [prettier/prettier#5954]
I've seen codebases that always use `// prettier-ignore` at the end of any long error message.
```js
if (something == null) throw new Error("Some very long error message that goes past the printWidth option") // prettier-ignore
```

Would you consider adding something like a `breakErrorMessages` option? When `false`, Prettier would never break a line that has a long `throw new Error` statement.

**Comment by lydell** [comment]
Hi!

This is way too specific to add an option for, I’m afraid.

**Comment by aleclarson** [comment]
@lydell To better prepare me for future requests, can you explain the rule of thumb for "too specific"?

**Comment by lydell** [comment]
https://prettier.io/docs/en/option-philosophy.html
