### ISSUE TITLE
.prettierrc is not ignored inside ignored directories

### ISSUE THREAD

**Issue by amikheychik** [prettier/prettier#5955]
**Environments:**
- Prettier Version: `1.16.4`
- Running Prettier via: `CLI`
- Runtime: `Node.js v10.15.0`
- Operating System: macOS (`10.14.3 (18D109)`)

**Steps to reproduce:**

Setup:
```
mkdir prettier
cd prettier
mkdir dist
echo '{"test":"dist"}' > ./dist/test.json
echo '{"test":"dist"}' > ./test.json
echo '{"devDependencies": {"prettier": "1.16.4"}}' > package.json
echo 'dist' > .prettierignore
echo '.prettierignore' >> .prettierignore
echo 'Broken' > ./dist/.prettierrc
npm install
```

Run:
```
npx prettier --check "./**"
```

**Expected behavior:**

```
Checking formatting...
test.json
Code style issues found in the above file(s). Forgot to run Prettier?
```

**Actual behavior:**

```
Checking formatting...
[error] Invalid configuration file: Config is only allowed to be an object, but received string in "/Users/amikheychik/Code/prettier/dist/.prettierrc"
```

*Note*: the only case it's working correctly: `node_modules` in the root. But if `node_modules` are in subdirectories, then it fails.

*Note*: problem is mitigated by using `--config` parameter to specify exact `.prettierrc` to use.

**Comment by lydell** [comment]
As far as I know, Prettier resolves config individually for every file. From every file it walks up the directory tree looking for config files. `"./**"` matches `dist/test.json`. When looking for config files from `dist/test.json` Prettier finds `dist/.prettierrc`. And that file is invalid. Does this make sense?

**Comment by amikheychik** [comment]
@lydell no, because the whole `dist` is in the `.prettierignore`. So directory should be skipped.

**Comment by lydell** [comment]
I see. That sounds like a bug.

**Comment by jamesreggio** [comment]
Can confirm that Prettier will still resolve and attempt to validate configuration for files in `.prettierignore`.

**Comment by jamesreggio** [comment]
This was easy to fix. Will open a PR in a couple minutes.

**Comment by jamesreggio** [comment]
@lydell, PR is here: #6233.
