### ISSUE TITLE
\ characters in string are removed

### ISSUE THREAD

**Issue by craigblagg** [prettier/prettier#5956]
**Prettier 1.16.4**
(https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKkoGcYAIAOAhjPAE5S4C8uA5KqgPQBmEENA3CADQgT4wBLaFmShCpUhADuABXEIRKQgDcIAgCbcQAI1KEwAazgwAykTACoAc2QxSAVzg8AFjAC2AGwDqzgfCzmcCYKfgLKfgCeyOBYIjyWWHCkMDJ6Vm6EyEyEHok8AFZYAB4AQnqGxiaEbnAAMpZwWTl5IIVFJpZWHnAAivYQ8E25TiBEpImk0dqE2hEe0Fr4pJYwXhowzsgAHAAMPEsQiV56+NFLcBPKjTykcACO9gK3qYTpmUjZwzyJbgK2DiMsJ1un0Bo0Ps0RjAZmt1BtkAAmHh2QgCDydADCEDcGWiUGg1xA9kSABUZopPokAL5UoA)
```sh
--parser babylon
```

**Input:**
```jsx

const pattern = '\/foo';
```

**Output:**
```jsx
const pattern = "/foo"

```

**Expected behavior:**
- `\` characters are not expected to be stripped in the output 
- The input and output in this case are expected to be equal

**Comment by craigblagg** [comment]
The AST contains:

```
"init": {
  "type": "StringLiteral",
  "start": 17,
  "end": 24,
  "loc": {
    "start": { "line": 2, "column": 16 },
    "end": { "line": 2, "column": 23 }
  },
  "extra": { "rawValue": "/foo", "raw": "'\\/foo'" },
  "value": "/foo"
}
```

So presume that `rawValue` or `value` are being used when outputting the prettier code

**Comment by lydell** [comment]
Prettier simplifies unnecessary escapes on purpose. Is this causing problems for you?

**Comment by craigblagg** [comment]
It caused unexpected output in an implementation we have - whereby we have a number of config objects that declare patterns - which are used in RegExp within various components.

One example in our case it changed a segment of one of those:

```
Input: 
'[^\s]'

Output:
'[^s]'
```

Changing the meaning from matching any whitespace character to any "s" character.

We've sidestepped it using a prettier ignore comment - so isn't causing any immediate issues anymore - but wanted to share incase it wasn't expected.

**Comment by lydell** [comment]
`'[^\s]'` is a mistake. It's exactly the same as '[^s]'. What you really want is `'[^\\s]'`.

**Comment by craigblagg** [comment]
Ahh yes, that's my bad. And thank you.

**Comment by gregolai** [comment]
> It's exactly the same as '[^s]'. What you really want is '[^\\s]'.

I'd like to clarify that prettier's actually re-writing **strings** and not **RegExp** types, so they are **NOT** the same. Prettier is assuming too much. See:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAngQQCcAjASxkIENDcBlC0qAcwHVyALCAVxnylwBKcJnAAeAWTiUojJpgC8mADogA2gD0lStAF0VAbhAAaEBAAOMUumShqhCAHcACtQRpkISgDcIpACbGIMRUYADWcDC0ZpRgssgUXHAm7DDYADYs7ORwaNFgcLRu5KRe5LgeYGjuJoxocIQwTlRM2JTIAGaUaXUmAFZoogBCIeGRlNhwADKMcB1dPSD9orSyaXAAilwQ8HPdSSDRhHWEHsSUxLhp0IFmhIwwbH4w7MgAHAAMJrcQdSxUZh5bjl6l5ZiZCHAAI5cUgQpqUFptJCdPYmOrYUjxQiJNGrDZbHbI+b7GDnR7PZAAJhMFEopDSsgAwhBsK0PFBoGCQFw6gAVc7uIl7AC+wqAA

**Comment by lydell** [comment]
@gregolai What do you mean by "Prettier is assuming too much"?

**Comment by kachkaev** [comment]
@gregolai if you want to have `\s` in your string, you should add an extra slash:

```js
const myArbitraryStringWithoutAnyRegexMeaning = "[^\s]";
// ↓
const myArbitraryStringWithoutAnyRegexMeaning = "[^\\s]";
```

Try running this in the Chrome's console or Node.js REPL to see the difference:


```js
const myArbitraryStringWithoutAnyRegexMeaning = "[^\s]";
console.log(myArbitraryStringWithoutAnyRegexMeaning)
// [^s]
```

**Comment by gregolai** [comment]
@kachkaev Ah, ok. I was getting a little confused, thinking it would affect the string length, but you're right. `\` in a string doesn't count against it, because it's just indicating that it should escape the next character. Sorry about the confusion.
