### ISSUE TITLE
In VS Code, Unexpectedly Modifies Content of Attrs Whose Names Start with "on-"

### ISSUE THREAD

**Issue by stevemuench** [prettier/prettier#5957]
**Prettier 1.8.1**
Issue does not reproduce in the playground. I disabled all other extensions except Prettier and the problem reproduces in VS Code 1.32.1. After disabling also Prettier extension, the problem no longer reproduces.

**Input:**
```jsx
<div class="oj-flex">
  <oj-toolbar id="a">
    <oj-button id="b" on-oj-action="[[$page.listeners.backButtonClicked]]">Cancel</oj-button>
    <oj-button id="c" on-oj-action="[[$page.listeners.saveButtonClicked]]">Save</oj-button>
  </oj-toolbar>
</div>
```

**Output:**
```jsx
<div class="oj-flex">
  <oj-toolbar id="a">
    <oj-button id="b" on-oj-action="([[$page.listeners.backButtonClicked]])"
      >Cancel</oj-button
    >
    <oj-button id="c" on-oj-action="([[$page.listeners.saveButtonClicked]])"
      >Save</oj-button
    >
  </oj-toolbar>
</div
```

**Expected behavior:**
I never expect reformatting my HTML to change the attribute contents of my HTML attributes, but in this case it has inserted surrounding parenthesis around the value of my two on-oj-action attributes. The problem seems related to attributes whose names start with "on-" because if I change the name of the attribute from "on-oj-action" to "on-xx" it still occurs, but if I change it to "xx-oj-action" the problem no longer reproduces.

**Comment by lydell** [comment]
Hi! Prettier 1.8.1 is very old. The latest version as of this writing is 1.16.4. Try upgrading.

**Comment by stevemuench** [comment]
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

Latest version on the extension marketplace is 1.8.1

**Comment by lydell** [comment]
I see – you’re referring to the Prettier VSCode extension. Its repo is over here: https://github.com/prettier/prettier-vscode/
