### ISSUE TITLE
Ignore Prettier for VSCode Settings.json

### ISSUE THREAD

**Issue by jhanstra** [prettier/prettier#5962]
Sorry for the question, but I can't find an answer anywhere. I'm wondering how I would turn Prettier off only for my VSCode settings.json and keybindings.json files. I edit these files frequently and don't want them to be prettier-ified. But they are also not in any 'project' where I could put a .prettierignore file. I tried putting a file at the root of the folder they are in and that didn't work. I don't want to turn off 'formatOnSave' for all json files - just certain ones like settings.json. 

What's the best way to do this? Is there any way to do it? I've also tried adding `/* eslint-disable prettier */` at the top of the file with no luck. Thanks.

**Comment by lydell** [comment]
Hi! I think you'll get better answers if you ask in the https://github.com/prettier/prettier-vscode repo. My only idea is that you might be anle to put a .prettierignore file somewhere that includes patterns for those files.
