### ISSUE TITLE
Parens added to class instantiation

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#5964]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhuAB0oaaAzCCJGqOAdxpgcAQyq0AYl0YBfFjIDcIADQgIJGAEtoVZKBHlyEfgAUDCXShEA3CJowqQAI3IiwAazgwAyiTeaoAHNkGHIsOFUACxhUHAB1SM14Kj8wOG8LJM1rJIBPZHBxRwCqOEoTV0DUEWR2ERxS1QArKiIAIVcPL28RVDgAGQC4WvrGkBaibwDAvABFLAh4EYaIkD9yUvIC9hxjRxJyAJg4+xhI5AAOAAZVA4hSuNcSAoO4Teth1XI4AEcsTW+FREVRqSDqK1UpVQmhCYVWVGmcwWSzBo1WMBEThOGDOyAATKpQiJNDhpgBhCCoaoFKDQT4gLClAAqmMs4NKMhkQA)
```sh
--parser flow
```

**Input:**
```jsx
module.exports = {
  foo: new class Foo {}
};
```

**Output:**
```jsx
module.exports = {
  foo: new class Foo {}()
};

```

**Expected behavior:**
Unchanged input?

It might very well be on purpose, it just looked odd that it adds parens

**Comment by lydell** [comment]
Well, `new Foo` becomes `new Foo()` on purpose, but I guess nobody though about inlining the entire class definition when writing that rule :)

**Comment by SimenB** [comment]
Right, it's on purpose. Thanks for clarifying!

**Comment by j-f1** [comment]
I think this should be `new (class Foo {})()`.

**Comment by SimenB** [comment]
Fair point, I can reopen

**Comment by SimenB** [comment]
I agree adding parens around the class declaration would be good

**Comment by mackness** [comment]
This may or may not be related to this issue:

#### Input:
```js
module.exports = {
  asyncFoo: async function asyncFoo(a, b) {
  	const result = await a * b;
    return result;
  }
};
```

#### Output:
```js
module.exports = {
  asyncFoo: async function asyncFoo(a, b) {
    const result = (await a) * b;
    return result;
  }
};
```

#### Expected behavior:
Input should not have changed?

**Comment by lydell** [comment]
@mackness That's not related. If you wonder why the parens are added in your case, it's because they make it clear what is `await`ed.

**Comment by mackness** [comment]
@lydell gotcha thanks for the clarification.

**Comment by duailibe** [comment]
So this is a case of an IICE ? 😄
