### ISSUE TITLE
In flow comment syntaxt function type parameter is moved producing invalid syntax

### ISSUE THREAD

**Issue by Gozala** [prettier/prettier#5968]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wUgBM48BePAQyIE8ow8B6AKiSQB46A+DmzwAKcnRh1OSOkICU0gArYIAWwCWRODwCq62AA4Agtmx1Gg4dX55gAHSh482ODACu2R1DgB3PHsMTM0YROQcAXxAAGhAIDBh1aCJkUDpTCB9FNIRklDoANwh1cmiQACMzMABrVwBlDDowfQBzZBhsNzgYgAsYVQAbAHVu9XgiBrA4WpzR9XzRxmRwImSY-S1cZTpm1TpkADM6fq0YgCsiNAAhSpqYWrpVOAAZfTgDo5OQc7Ralv64ACKbgg8Hexy6IAa2A2SzKdDKcH6AFp9v0MqUMNh9DBBsUYN1kAYAAwxTEQLSDMwYJaYuAbfJvGIuACObnULi2Oz2SEO4JiWg0YM+RD+gOBoJ5HwhkjKuPI+OQACYYu06Op+i0AMJqXZLKDQRkgNxaAAq8NyvK04XCQA)
```sh
--parser babel-flow
--no-semi
```

**Input:**
```babel-flow
export const encode = async /*::<a>*/ (data/*:a*/)/*:Promise<Uint8Array>*/ => {
  return new Uint8Array()
}
```

**Output:**
```babel-flow
export const encode = async (
  /*::<a>*/ data /*:a*/
) /*:Promise<Uint8Array>*/ => {
  return new Uint8Array()
}

```

**Expected behavior:**

**Comment by j-f1** [comment]
As a workaround, you can use the `flow` parser.

**Comment by thorn0** [comment]
Not an issue anymore because support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687
