### ISSUE TITLE
Calls to functions or methods named “compose” are always split into multiple lines.

### ISSUE THREAD

**Issue by brainkim** [prettier/prettier#5969]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucEC2AHCBnOAKAQwBoACAI1LAEoBuAHSgHpGS7VMc5yCwBrAdwIAnACbY2DONggY0EMIVIUS1elCwyAdJA65F5SrQYaMmqTLkLiBlbRBEQMmAEto2ZKGFCI-AArCEdxQCADcIZxF7EDIhHl44GABlDB5nKABzZBghAFc4BwALGDQAGwB1Aud4bBSwOETAqucQqoBPZHBsdwc03CEYX1j0tAJkADMCEtwHACtsAA8AIVi+BMSCNDgAGTS4ccnpkDn5xLT0krgARRyIeH2p-JAUoT6OsZKfKIwhNJgyiJgBWQAA4AAwOb6cMqxDAdb5SOBCEJ7BxCOAARxyzjRgwIw1GSAmDwcuDQziyuUe2DOF2utz2hIOjxgBDI-xEgOQACYHNkCM4SmcAMLoEYdKDQFEgHK4AAqrKCRNwAF9lUA)
```sh
--parser flow
```

**Input:**
```jsx
compose(a, b, c);
// "compose backwards"
esopmoc(a, b, c);
poop.compose(a, b, c);
poop.esopmoc(a, b, c);
```

**Output:**
```jsx
compose(
  a,
  b,
  c
);
// "compose backwards"
esopmoc(a, b, c);
poop.compose(
  a,
  b,
  c
);
poop.esopmoc(a, b, c);

```

**Expected behavior:**
```jsx
compose(a, b, c);
// "compose backwards"
esopmoc(a, b, c);
poop.compose(a, b, c);
poop.esopmoc(a, b, c);
```
🤔🧐🤪

**Comment by kachkaev** [comment]
This behaviour is intentional and there is a reason for it. See [source](https://github.com/prettier/prettier/blob/f526c47b1ee929c677240420ff6124e2571701df/src/language-js/printer-estree.js#L3867-L3879). First introduced in https://github.com/prettier/prettier/pull/4431.

**Comment by kachkaev** [comment]
Would it be reasonable to treat `blah.compose()` as `blah.connect()` since https://github.com/prettier/prettier/issues/4935?

**Comment by brainkim** [comment]
@kachkaev Thanks for the additional info!

What recourse do I have as an end-user? Am I supposed to not define functions/methods named `compose` because the fp crowd have gotten it hard-coded in prettier as a call that is split up on multiple lines?

Feel free to close this as a #wontfix but I’m unconvinced that this decision to treat a hard-coded set of names differently was the right one in the first place.

**Comment by duailibe** [comment]
@brainkim 

Thanks for the feedback. I'm sorry you feel this way, we're open to suggestions on how to improve, but keep in mind this wasn't an arbitrary decision (it never is), see #4172 for the long discussion around this topic.

**Comment by brainkim** [comment]
@duailibe

I didn’t mean to parachute in and give my opinion on settled decisions, but here we are. I was sincerely surprised when, while coding, I defined a function named `compose` as in `compose` two `patches` together and found that prettier was splitting it up, within a short ternary expression to wit. Here’s the actual code prettier produced:

```js
export class PatchBuilder {
  replace(start: number, end: number, inserted: string): void {
    /* ... */
    this.patch =
      this.patch == null
        ? patch
        : compose(
            this.patch,
            patch,
          );
    /* ... */
  }
}
```
This doesn’t look prettier to me 😛, and I spent some time figuring out that it was not the ternary operator which caused the split.

If I had to give a suggestion, it would be for prettier to treat call expressions the same way it treats object literals, where it respects the author’s decision based on the first line (i.e. it doesn’t join multiple lines and splits the expression onto multiple lines only if it extends past the line limit). This wouldn’t change existing prettiered code and wouldn’t require a new option flag. Maybe the prettier team has reasons why they don’t seem to use this solution for anything besides object literals but I think the examples in #4172 underscore the fact that call expressions, like object literals, should not be messed with if authors feel the need to break them up.

Anyways, I’m thinking of renaming the `compose` function to `meld` or `merge`, but I’m going to leave this open because y’all got a bot that locks issues which are closed. Again, feel free to close as a wontfix.

**Comment by duailibe** [comment]
@brainkim 

I agree with you that doesn't look pretty and thanks for the suggestion. The problem with the comments in general is because people never post real world code samples of things that doesn't look pretty. So now that you posted an example, I've just realized that it might make sense to restrict when to apply the function name heuristics. For example, I think we should never force breaking `compose` if we're inside a ternary.

As for the suggestion, we don't want to add more of those respecting new lines because the point of Prettier is not having to think about formatting and that goes against the general value. But this is always subject to change and comments like yours with real world code examples help us make better decisions

**Comment by brainkim** [comment]
In the code I’m working on I changed the function name to “meld” so this is mostly just bikeshedding for me now, but here’s some more thoughts on a better heuristic.

> I've just realized that it might make sense to restrict when to apply the function name heuristics. For example, I think we should never force breaking compose if we're inside a ternary.

If we’re trying to reduce the number of false positives that the “name” heuristic produces, the best limiting heuristic might be to check for nested call expressions. This would fix the examples in #4935 without having to create an additional special case for ”connect,” and it would correctly format all the examples in #4172.

Again though, and I don’t really have skin in the game any more, my larger point is that, more likely than not, if you ask the average end-user about this particular behavior of prettier, they would be surprised that call splitting works based on hard-coded strings.

Some more ideas on name-independent heuristics:

Recursively check arguments for nested call expressions with function literals for arguments. In other words, if there’s a nested call expression with a function literal as an argument to the call, it’s most likely some sort of composing/piping function so we should split it. It seems like all the examples above would correctly format based on this criteria, and the non-splits wouldn’t look bad.

Another more aggressive heuristic might be to check for and split on calls with function literals in any argument besides the last. This would also correctly format, for instance, the new `useCallback` hook in react. Taken verbatim from [react docs](https://reactjs.org/docs/hooks-reference.html#usecallback):

```js
const memoizedCallback = useCallback(
  () => {
    doSomething(a, b);
  },
  [a, b],
);
```
whereas currently prettier does this:

```js
const memoizedCallback = useCallback(() => {
  doSomething(a, b);
}, [a, b]);
```

This is more aggressive because it would change how a lot of `setTimeout` and `setInterval` calls are currently formatted, but I would argue that it’s prettier. [From the mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Passing_string_literals):

```js
window.setTimeout(function() {
  alert('Hello World!');
}, 500);
```

```js
window.setTimeout(
  function() {
   alert('Hello World!');
  },
  500,
);
```

That might be too radical for prettier, and it would have additional repercussions when nesting function calls, but I think the larger point is that the most interesting and flexible heuristics which solve this problem posed in #4172 are ones which use the presence of function literals to figure out splits.

**Comment by j-f1** [comment]
The formatting of React hooks is an intentional override, see #5608.

**Comment by brainkim** [comment]
@j-f1 ahh so you’re already doing something to function calls based on argument types 🧐 ignore my last suggestion then.

**Comment by evilebottnawi** [comment]
I think we need search way how improve this , because it is real looks very ugly on simple cases. Maybe we can looks on `require`/`import` to determinate.

**Comment by brainkim** [comment]
I dislike the current string-specific behavior but I dislike the idea of dependency-specific behavior even more.

To rephrase my ideal solution in pseudocode:

```
for each function call:
    let literals = 0
    for each argument passed to function call:
        if argument or any of the argument’s descendants are a function literal:
            literals += 1
    if literals > 1:
        split function onto multiple lines
```

I would argue this solve ALL functional composition cases.

**Comment by evilebottnawi** [comment]
@brainkim you can send a PR, it is better to catch regressions or other problems

**Comment by brainkim** [comment]
@evilebottnawi Done. I was waiting for consensus but honestly I can’t even.
https://github.com/prettier/prettier/pull/6033
