### ISSUE TITLE
[TypeScript] Long assignment line w/ type variable doesn't look pretty to me

### ISSUE THREAD

**Issue by spiltcoffee** [prettier/prettier#5970]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VAbOAzGACASwGc8B3ACwEN8BJPOADwAc4wYAaPAJwIHNz8xMlVrdWcAgDc4AEwA6ULPggBrSgE8AjEjwBlCAFs4AFXUs8AXjwxyxAHS84MAOoi40rgB59RmwSi8AHwAFACUDk4AglAQNnBcxrYBAHIQpMEKeHqGcJFcvACuRrAKoQDcCgpgGJREJACipADCNXV4wJn0pABiBVBgYe1ZWZ1ZSniqGgBMOj4mZnCW1rZEES5uHt45fgEh4Y4w0bHk8Yn+vKnpo8NzeYXFMNfllVDDeOh0jCxssstCMBA8AAjLhwSgqPCUXDxZaLAAGwTheAwBBUi0oQIg0k4QIKgnwILBKhIUPgXDwcM8SP8RHglHkr2G4zgpFmOVM5isflWB1c1Hc8S2viSQTCayOcQSIsuACE8QAZaCOLgZRlvW75IoIR5qvDPRkAXwURqgIHYIAgTBgBGgRGQoEoXC4aQACo6EHaUJRJBACDIzSAQZQwGiYLomMHzsgYFwCnBzQIDBhXAR4EQI2A4LoPampKn1MhwHUAzT4jAXVxKLwDJRkNhKBgiPGQAArIgMGWVkNOXSUIzy-xwOsNpvmtsMXTnLAARQKsSHSHrjebEa4Ta4hZgCyIYB4VoDTB4sGcfpsyAAHAAGc2HiBN5yVpiFw9wdfSAOggCOBQIoIrVZrYdl3NJsDAIaNY2bIgpzgWd5yA0cQBgDETxkM8kCmc0Y0oAgUQCJpDEAlAYigIdzQKJtjAxT0lybA0DSAA)
```sh
--parser typescript
```

**Input:**
```tsx
//left is what I expect, right is what I received
let okay1: SomeType = this.getWhatever<Something>().getAnotherThingNow(
  SomeArgument
);

class EwClass {
  ewFunc() {    
    let okay2: SomeType = this.getWhatever<Something>().getAnotherThingNow(
      SomeArgument
    );

    //I expected this to break after the `(` like above, but it breaks after `<` instead
    let ew: SomeType = this.getWhatever<Something>().getAnotherThingNowButLonger(
      SomeArgument
    );
  }
}

```

**Output:**
```tsx
//left is what I expect, right is what I received
let okay1: SomeType = this.getWhatever<Something>().getAnotherThingNow(
  SomeArgument
);

class EwClass {
  ewFunc() {
    let okay2: SomeType = this.getWhatever<Something>().getAnotherThingNow(
      SomeArgument
    );

    //I expected this to break after the `(` like above, but it breaks after `<` instead
    let ew: SomeType = this.getWhatever<
      Something
    >().getAnotherThingNowButLonger(SomeArgument);
  }
}

```

**Expected behavior:**
I expected the `let ew` line to break after the `(`, but it broke after the `<` instead.

Not sure if this is desired by Prettier, but my eyes hate it 😛.

Having trouble identifying if there's an issue already raised about this or not, so sorry if this is a duplicate.

**Comment by dotku** [comment]
Yeah, it seems weird to me

**Comment by evilebottnawi** [comment]
Thanks for issue duplicate https://github.com/prettier/prettier/issues/4238
