### ISSUE TITLE
Address spacing/padding among blocks, statements

### ISSUE THREAD

**Issue by rdsedmundo** [prettier/prettier#5972]
I'm not sure if this is not on the scope of Prettier by intention, but I'd like to suggest it to start addressing spacing among blocks of code.

Today it seems that no corrections are made unless you're doing padding blocks or adding multiple empty lines among blocks, for instance. Code below is valid from Prettier perspective and won't lead to any corrections. I personally find it too much harder to follow compared to the second version.

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcJ04BRAD3hygEMAbS7PfAMxxPwHJaBaKTOl7oIAEwCu9OFwDcAHSgZmBWlAgwAFnByVqdRhWVsO6bqvVac-QcLGTp8xVlwFgC-ERLkq2-UxcAggA07p6kur4M-ngAQiFQHsThPjRRhi4AwvEAvsacXJqohNZCIhJSsgpKLvjA+DhwMDiocABucBnQ8FT4uez5tABGxPTi8LzVeAD0Y6j0hJVORnUA5o0AIoOdUFBwYDCo0L15plwAdGdTF1Oig4uTrvVwhNhQogDqqJoAyuJgYM9CMd+qchiMxnAJs5prN5lNCH8AYQFo4HrVQnAKHsxrh4h5MLQcIQ4DkTtxrhTLuhaKgoLxMdiYLh7tDHg0XtAPl8NAAxGmjBrAkxmYYQUbjB4zA5w1j88QNRYKWiEACeUDAbHE6oOR3ghBgAAo2ggYABKdEJfCQKD6q1dTEEAC8TyaLXa226htCchgmA4SMIZwQrTOGQA8gA5AAqZAAGlGAPoAcQAMmGYgEUwnwxGeQBJJMAVQASgEo3nI3iPPhjbAq6bHB4pARrbt9ocoI38E0VRbq3adnsdQlna2hx3A+gVYQAI70M5rGCbbZt4cGuoNV3G0Qeh08kxkdqwJADz29BuhDzW20EolwUSHk34Z234lGo9mrtX6C2uq0IL4IMAFgABogAXAxzOrWMBfgOtrsq8xLPvgtAAO40gQDJgDiODrpe1Z0KQJ5cNB9JYthTI4FwVb9q0hKECebiWv2Hj-vh-ZAex1YgVxHhgbxNY0dW2RCd+g7ttAQnZBezH4KgrD4AaCE-nAZwaMq6xwFIKy0JR5pMSxTwrEU1C-P8gKsJI9AAAr+oC96PrAeZQBktBgFoeGyf21qeqJ1bQX5HjKTaJJcdJsFBY08oJMFxJnKIWlwDplEGjJ-bZPhm7RU8HJvJ8PyIoCnmGT5Dp+QFXGxaFsnhaEuRgLp7mKdoHA4PpmVRTQOWvFymh8nM8pwMVLGlVQ5Ufn5VVSWlwK0gw9C9gZ+A+teYqqQlgziCsBqjTAAFcJ89D0Fa9AQEhY4SQkundloNZvHJCm0HRcxDBUwHQKuHYzR48mKRdw7tV5KHoV8A6fdAQZvKlsEZZasPZCAQQgBAmDDoQyCgISHCodZhIIOjKBPRAqCiIjICDDgbkANaNN8BJgLSKzIE04gkiAGgwOg9DvBoXzPPTcDfPjXyoK0Xwqsg4DImTtLEngtm0Cs1LILK8xswAVoQFAxJTYA0zA3y0KQKa0nAKsMMSSOaxQ3yM1IACK4jqGbSCq5bICvtokuDEMKqnVAZN+rSMCfKImjIAAHAADEjfpnXA7yU5gkt+s82jtGTDQzuIqANArSu0ObatI8S6CoMzOCsyXdtwI7ztF+7MBDKH4dIAATEjTT8oznToMrKBqLsZPiMSUZgg3cDZNkQA)
```js
import someExternalExport from 'a-npm-module';
import anotherExternalExport from 'another-npm-module';
import {
  someExternalExportA,
  someExternalExportB,
  someExternalExportC,
} from 'this-npm-module';
import { retrieveContext } from 'absolute-import/utils';
import { getDbConnection } from '../../db';
import { respondWithSuccess } from 'absolute-import/utils/success';
import {
  executor,
  parse,
} from '../../../main-executor';
import { respondWithFailure } from 'absolute-import/utils/failure';

async function test(event) {
  const context = retrieveContext(
    process.env.CONTEXT_GLOBAL_CONFIGURATION,
    event,
  );
  let connection;
  try {
    connection = connections.mysql.getDbConnection({ retrievedContextFromEvent: context });
    const parsedEvent = parse(event);
    const { a, b, c, d, e } = event;
    const response = await executor({
      name: 'event-executor',
      vars: {
        a,
        b,
        c,
        d,
        e,
      },
      connection,
    });
    if (response.hasDelegator) {
      registerSuccessfullProcessedEventInCache({
        context,
        event,
        response,
      });
      return response.delegator();
    }
    return respondWithSuccess({
      context,
      event,
      response,
    });
  } catch (error) {
    return respondWithFailure({
      context,
      event,
      response,
    });
  } finally {
    console.debug(context, 'Will close connection at the end if available', connection);
    if (connection) {
      await connection.end();
    }
  }
}
```

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcJ04BRAD3hygEMAbS7PfAMxxPwHJaBaKTOl7oIAEwCu9OFwDcAHSgZmBWlAgwAFnByVqdRhWVsO6bqvVac-QcLGTp8xVlwFgC-ERLkq2-UxcAggA07p6kur4M-ngAQiFQHsThPjRRhi4AwvEAvsacXJqohNZCIhJSsgoKSi74wPg4cDA4qHAAbnAZ0PBU+Lns+bQARsT04vC8NXgA9OOo9ISVTkb1jYTYUKIA6qiaAMriYGBwhIR9eaY8IxBjE1MwszDzhNOEh8enS-d1DScb27sNAAxWjzcSNc4DS7DUbjOCTZwzOYLaasUFjRpLaqI1z4ADmTQAIkMulAoHAwE9oJCTNwAHR06YM6aiIZfHF1UJwCgU8a4eIeTC0HCEOA5C70xnM5noUFQXjc3kwXBYuiEACeUDAbHEWqpCXghBgAAp2ggYABKTkJfCQKBG23dbkEAC8v2arQ6pJ6JtCchgmA4H0IdIQbTpGQA8gA5AAqZAAGrGAPoAcQAMpGYgF08mo9GgQBJVMAVQASgFY4WYwKPPgzbBaxbHB5QlICHbyZTUNAW-hQs11da646yRT9fg3Z3xz37XT0OrCABHeh0gkwYmkrv642rJotM2ib3OoEmMgdWBIUc+vrN0Ktm0eO0OoUiuCic-myf4V+i00Xy0+yfaAHXqWggnwIYILACDRAguBzjdBsYCA-tH1HB01g2UVv1oAB3UECEVMA+RwXd7zrOhSCvLhkIVHkSOVHAuFrEc2mFQgrzcdCR3AiiRyg-i6xgoSPDg0T61Yutsik4Cx27aApOyO90Io1BWHwY0sJAuA6Q0WhCEJOApDxWgmKtbiRw8Ro8SKagDiOE5CFYSR6AABSDJz30-WBCygDJaDALRyJ44SnSoWS62QyLrL+HTIuU1CHys91wQSbT7V00RjLgUymONFSR2yCiKMaGA0t+dZoABfZ3ickKUrtH1IuioSMtFJTCvOMAzKCzTtA4HALNKpoKoymrgXRcE4AaqymudFqAMi9qxQoxLQn6VB9HoIdLP7GBnxuLK4CGcQ8WNeaIu4HZ6HoW16AgHDpwUhIzPwTQEIQUR8HU-BaHY+ZhgqaDoG3WcuuSutfou0GZ2gYbQvwwjRzB6BQ02ArUOKm1seyEAghACBMH1QhkFAYUODwtzhQQUmUH+iBUFEfGQCGHBAoAayaPYhTALa8WQZpxDFEANBgdB6C2DRdj+QK4D2WndlQNpdnVZBwFOFmttFPAPNoPFZWQNEFhFgArQgKBidmwC5mA9loUh0y2uAjYYDqQHNig9n5qQAEVxHUF2kGN93f20dWhmGdUHqgFnAy2mAdlETRkAADgABgJwNHrgLZ2cwdXAxObQOhZxol3EVBGj1g3aFdk2CdFdBUEFnBhcbn24H9wP6-dmBhiTlOkAAJgJ5p0X5rp0ENlA1HJFnxFFWMYV7uBsmyIA)
```js
import someExternalExport from 'a-npm-module';
import anotherExternalExport from 'another-npm-module';
import {
  someExternalExportA,
  someExternalExportB,
  someExternalExportC,
} from 'this-npm-module';

import { retrieveContext } from 'absolute-import/utils';
import { respondWithSuccess } from 'absolute-import/utils/success';
import { respondWithFailure } from 'absolute-import/utils/failure';

import { getDbConnection } from '../../db';
import {
  executor,
  parse,
} from '../../../main-executor';

async function test(event) {
  const context = retrieveContext(
    process.env.CONTEXT_GLOBAL_CONFIGURATION,
    event,
  );
  
  let connection;
  
  try {
    connection = connections.mysql.getDbConnection({ retrievedContextFromEvent: context });
    
    const parsedEvent = parse(event);
    const { a, b, c, d, e } = event;
    
    const response = await executor({
      name: 'event-executor',
      vars: {
        a,
        b,
        c,
        d,
        e,
      },
      connection,
    });
    
    if (response.hasDelegator) {
      registerSuccessfullProcessedEventInCache({
        context,
        event,
        response,
      });
      
      return response.delegator();
    }
    
    return respondWithSuccess({
      context,
      event,
      response,
    });
  } catch (error) {
    return respondWithFailure({
      context,
      event,
      response,
    });
  } finally {
    console.debug(context, 'Will close connection at the end if available', connection);
    
    if (connection) {
      await connection.end();
    }
  }
}
```

The "rule" that I usually apply on my mind is simply:
- if something is multiline, it should be separated by spaces from other blocks;
- if something is from a different "group", it should be separated by spaces from other blocks;

By group I mean: variable assignments, or function calls. i.e this all are valid:

```
// same group, no multiline
const a = true;
const b = true;
const c = true;

// same group, but there's a multiline
const a = true;
const b = true

const c = {
  a,
  b,
  executor: function() {
    return this.a + this.b;
  },
};

// same group, no multiline
a();
b();
c();

// same group, but there are multiline
a();

b({
  someLongParameterName: someLongVariableName,
  variableData: {
    a,
    exec: () => window.exec || noop;
  },
});

c({
  initiatorCallback: a,
  parserCallback: b,
});

// different blocks
const a = true;
const b = true;

c();

const d = true;

e();
f();

const g = true;

h();
```

And all the control flow expressions or statements are also separated:

```
  ...
  const something = test;
  const another = something || providedAnother;

  if (something) {
    return another;
  }

  for (let i =  0; i < someArray.length; i++) {
    someArray[i] = exec(i-1, something, another);
  } 

  return theDefaultOne;
```

It's very annoying to see a lot of different spacing strategies being used among developers and simply not being able to say to someone to use X or Y, because there are no rules available. So it ends up which everyone doing on the manner they prefer. Even if I try to establish a guideline for that, agree with everyone on how we want the spacing to be, it's difficult and annoying to go on every LOC on a Pull Request and say: hey, you forgot a space here.

I'm not suggesting this rule I created on my mind per se, what I want is to start a discussion about Prettier starting to address this problem -- the rules can be discussed and even be part of a configuration.

**Comment by SimenB** [comment]
Related: #3597

**Comment by lydell** [comment]
The idea is that the `--pure` option is going to do this: #4685

**Comment by rdsedmundo** [comment]
Yes, this one definitely seems to be related, @SimenB, although my issue including it (spacing among imports), but even more.

And @lydell, I'm glad to hear that there's something WIP aiming to achieve that. I'll give it a shot.

**Comment by evilebottnawi** [comment]
@rdsedmundo Can we close issue in favor https://github.com/prettier/prettier/issues/2068?
