### ISSUE TITLE
1.17 Release

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#5975]
- **Prepare**
  - [ ] Complete [1.17 milestone items](https://github.com/prettier/prettier/milestone/27)
  - [ ] Run on other projects to check for regressions
  - [ ] Write release notes (#6052)
    - add a Markdown file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)
    - [prs-merged-since](https://npm.im/prs-merged-since) may be useful
- **Publish**
  - [ ] Run [release script](https://github.com/prettier/prettier/tree/master/scripts/release)
- **Postpublish**
  - [ ] Merge release notes
  - [ ] Wait for release notes to deploy
  - [ ] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [ ] Close milestone
  - [ ] Send schema PR generated by `scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
  - [ ] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😅

**Comment by ntotten** [comment]
Any chance we can remove #3888 from this release? It seems like that is holding things up as it is very controversial. There are a number of fixes and a new parser (LWC) in this release that would be great to go out soon.

**Comment by lydell** [comment]
Sounds reasonable!

**Comment by ntotten** [comment]
@ikatyang Any chance this release could go out. It looks like all the PRs are closed and all issues are resolved except #3888 which doesn't seem to have a conclusion. We would love to get the LWC parser into a release ASAP. :)

**Comment by duailibe** [comment]
@ntotten I'm already working on it

**Comment by brodybits** [comment]
I was hoping the dependency updates I proposed in approved PRs #5985 & #5987 would be included.

**Comment by brodybits** [comment]
S.o.r.r.y to be a pain here ... I forgot to mention that I think that the test in #5989 should be included if possible. It is needed to ensure that issue #5817 which was solved by TypeScript 3.4 update (#6027) does not reappear and can be closed.

Kudos to @ntotten and @duailibe for pushing this to go out the door.

**Comment by ntotten** [comment]
Awesome. Thanks everyone for getting this out!
