### ISSUE TITLE
AutoHotKey support

### ISSUE THREAD

**Issue by jaydeepkarena** [prettier/prettier#5978]
add support for .ahk file, which is Auto Hot Key files in VSCode

**Comment by evilebottnawi** [comment]
Out of scope prettier (core), you can create plugin for this

**Comment by kachkaev** [comment]
@jaydeepkarena see https://prettier.io/docs/en/plugins.html and feel free to create your own plugins.

**Comment by lydell** [comment]
Yeah, this language is a little too niche to include in core. But if you do make a plugin we’d be happy to link to it!
