### ISSUE TITLE
[Request] Separate printWidth for code blocks in markdown

### ISSUE THREAD

**Issue by alexkrolick** [prettier/prettier#5980]
Sometimes it is nice to wrap prose in Markdown around 80 chars, while wrapping example code that has to look good on mobile around 60.

The React docs do this by storing example code in a separate JS file and including it via plugins, but it would be nice to be able to support it natively as a Prettier option.

**Comment by thorn0** [comment]
closing in favor of https://github.com/prettier/prettier/issues/5378
