### ISSUE TITLE
Disable newline after opening parenthesis

### ISSUE THREAD

**Issue by Parthchokshi** [prettier/prettier#5981]
**Environments:**
- Prettier Version: 1.16.4
- Running Prettier via: CLI
- Runtime: Node.js
- Operating System: macOS

**Steps to reproduce:**

See code below

**Expected behavior:**
```
export default withContext(withStyles(styles)(class extends React.Component {
...
}
```

**Actual behavior:**

```
export default withContext(
    withStyles(styles)(
        class extends React.Component {
...
}
```
  
How can I tell prettier to not put new line after open parenthesis and let the declaration live on single line?

**Comment by lydell** [comment]
Hi! I tried to make look at your case in the playground. I hope I got it right!

```js
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt8B3ASxgAsBhaeNGACnqYGUYAnpTgBnTiMHCRASk5hKpESLzp4UAsoBKcUmBgA6VgFssUBPmAAdKHjzYERbJ2l4rN23bgxy2G1CqUANzWtgC+1qHS0sFQIAA0IBAYMHTQIsigpNjYEDQAClkI6SikAG4QdATxIABG2LoA1l68GLp0UADmyDDY5HAJjDBGlADqjAyirWBwvEUMdKUMAsjgStXtInC4efUdRqTIZJSbCQBWImgAQvVgTTC8pEZwADLtcIekx-0g52i87R1hABFcgQeAfL4JVrYTbYFY1Ug1ITQaoYbDtGAjSpMZAADgADFCcpsRvUMCs0aItqV3gl7ABHch0ew7Uh7A5II4nECbIx0bq9b4iAHA0HgzmfbkwRFYgg4pAAJgSPVIdEoAOM+xWUGgtJA5E2ABVEcUuXBQqEgA)
```sh
--parser babylon
```

**Input:**
```jsx
export default withContext(withStyles(styles)(class extends React.Component {
  render() {
    return null;
  }
}));

```

**Output:**
```jsx
export default withContext(
  withStyles(styles)(
    class extends React.Component {
      render() {
        return null;
      }
    }
  )
);

```

Now, assuming I understand you correctly, on to your question – no, there's no way to make Prettier print your code like in your input. IMO Prettier's version is easier for me to understand. Sometimes we get issues where everyone agrees instantly that Prettier's output is worse, but as seen that's not the case for this issue.

I'd recommend letting go of thinking hard about how to format your code. Let Prettier have its way, and if the result isn't terrible then let it be. That's part of using Prettier, and I must say it's pretty liberating!

In your case I'd write your code this way instead:

```js
class MyComponent extends React.Component {
  render() {
    return null;
  }
}

export default withContext(withStyles(styles)(MyComponent));
```

IMO that's easier to understand and much cleaner. As a bonus your component is now named as well!

I hope this answers your question!
