### ISSUE TITLE
Default endOfLine to "auto"

### ISSUE THREAD

**Issue by infinnie** [prettier/prettier#5984]
By default, EOLs should be automatically handled by text editors like Visual Studio Code and VCSs like Git. It is confusing for a formatter to handle that.

**Prettier 1.15.2**

**Expected behavior:**

**Comment by lydell** [comment]
"auto" already is the default. You probably have a Prettier config file or an .editorconfig file somewhere. Or VSCode is doing something.

**Comment by infinnie** [comment]
Did not know that configurations in .editorconfig are also respected.
