### ISSUE TITLE
Img Tags are closed with />

### ISSUE THREAD

**Issue by Christian24** [prettier/prettier#5992]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAy5u3AQQDKQgLxMQUCAFoAVgGdyNQtNx0B8oROZRy5dqQGYdevak6l8AvmwEAlIZfEgArjABm0gBzaWp-fgAkvjcpAycAJ7kMMF0pKgA9EEhYX6m5pbWAHICFs4AJnDyYABOAJYADjBl0BLkkLAIMM6RfBBZMKRQ+L66+glshsZpqABGEPkRJunEDGxwdHQQ5ADuECV0+eioAEJ2DOT4lGWKJ+QcPACs5DsQZXRwJRV0AIbwAHSJs2nkP+llNAA5uR5CUwM5qDAKvIkAkEhUSnAYNVHu8agkyg13hUoIDer8+olxpMdIkLtwGCAADQgCBVGpQeTIUAvEolCArYishBMlAvABud3y1JAoxKLzAAGskUIKhKyrjkDASi44DTqPQAOrHeDyOVgOBCHllar8k0RZDgeRMmkK+SPGDEcWAmgvZDuF50e00hQADx24qlMpeNDg3AVcHdnu9ID9QgVgIeAEUXBB4FGvWqQHKSvaSpaNXQRQiFTBNWV8jBKMgvAAGGkIiD2zXiiqWhFFR78yM0xEARxcZURTpeLrdSA9mZp9poZSVKqz8gTydT6Yn0azMBeo3LlerSAATDTlS97gncBAaK7LVIoD3XPb8NveZP7QBfN9AA)
```sh
--parser html
```

**Input:**
```html
<!DOCTYPE html>
<HTML CLASS="no-js mY-ClAsS">
  <HEAD>
    <META CHARSET="utf-8">
    <TITLE>My tITlE</TITLE>
    <META NAME="description" content="My CoNtEnT">
  </HEAD>
  <body>
    <P>Hello world!<BR> This is HTML5 Boilerplate.</P>
   
      <img src="https://prettier.io/icon.png">
 
  </body>
</HTML>
```

**Output:**
```html
<!DOCTYPE html>
<html class="no-js mY-ClAsS">
  <head>
    <meta charset="utf-8" />
    <title>My tITlE</title>
    <meta name="description" content="My CoNtEnT" />
  </head>
  <body>
    <p>
      Hello world!<br />
      This is HTML5 Boilerplate.
    </p>

    <img src="https://prettier.io/icon.png" />
  </body>
</html>

```

**Expected behavior:**
```html
<!DOCTYPE html>
<html class="no-js mY-ClAsS">
  <head>
    <meta charset="utf-8" />
    <title>My tITlE</title>
    <meta name="description" content="My CoNtEnT" />
  </head>
  <body>
    <p>
      Hello world!<br />
      This is HTML5 Boilerplate.
    </p>

    <img src="https://prettier.io/icon.png" >
  </body>
</html>

```
img tags are closed with `/>` which is not valid HTML5. Img tags are special tags that do not have an end tag according to https://www.w3schools.com/tags/tag_img.asp 

As far as I am aware `/>` is not valid HTML5 anyway.

**Comment by lydell** [comment]
It’s the opposite – HTML5 made `/>` valid!

Browsers have ignored a `/` before the `>` of void elements for a long time, but technically it wasn’t valid HTML (in HTML4 and earlier). But HTML5 now allows `/>` – but only for _void_ elements such as `img` and `link`, not for an empty `div` for example (`<div />` is invalid).

Prettier chose to print with the slash. There’s an open issue about that here: #5246

**Comment by Christian24** [comment]
Sorry, I was unaware of this detail. Thank you.
