### ISSUE TITLE
Query: Can prettier create a js file from an AST

### ISSUE THREAD

**Issue by jaitaiwan** [prettier/prettier#5998]
Hi, I've gone through and tried to find similar issues one of which is #1059.

I'm looking at creating some sort of visual scripting interface for JavaScript as a personal project. I'm very much on board with Prettier's goal, so I feel that code generated by the Visual Scripting tool should result in the same code as prettier would output. So I have a similar question to what the person in 1059 has:

Is there an exposed api that would allow me to input a programatically created AST into prettier and output a Javascript file?

**Comment by bakkot** [comment]
#2068 would presumably provide this, but to my knowledge there's nothing currently. Your best bet at the moment is probably using something like [@babel/generator](https://github.com/babel/babel/tree/master/packages/babel-generator) or [escodegen](https://github.com/estools/escodegen) or [shift-codegen](https://github.com/shapesecurity/shift-codegen-js) to turn your AST into an unformatted string, then pass that to Prettier. It adds a bit of overhead (though less than you might expect), but it works.

**Comment by thorn0** [comment]
It's possible to do this using the [Custom Parser API](https://prettier.io/docs/en/api.html#custom-parser-api):

```js
// suppose you have your AST in the yourAst variable
const formatted = prettier.format(
  ".", // any non-empty, non-whitespace string 
  { parser: () => yourAst }
);
```

**Comment by benatkin** [comment]
Worth reading about `gofmt`'s substitution command https://golang.org/cmd/gofmt/

**Comment by thorn0** [comment]
Closing in favor of #9114
