### ISSUE TITLE
Break jest-each array elements by lines

### ISSUE THREAD

**Issue by ark120202** [prettier/prettier#6000]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMB0cCGYAWAFANoA6UABBcBTkhaSAIyMA0FARvUxQL6vkqNOgxAAmNp3pi+AytVr1GAZklcKy2eQC6ASkKN0MSYWHsOfXRQC8APmqCKcAB4AHOGBiEAcgFcAthxwAE6EOLq6mDAQAEJwhBy6ANzkvMnkIKwgEK4wAJbQaMigOMHBEADuAAqlCEUoOABuEHkAJpkgHMF4ANZwMADKrnh5UADmyDDBvnBZ+DD+ADYA6vh56MNgcAN163mN6wCeyOBoRVmjaCEwVd1j-jjIAGY4i1dZAFZozjHdYH2DHD+OAAGVGcGer3eIC+zgGozGizgAEVfBB4JC3rMQMNgldgicODgOIdFtAOq5gqMYMs2jB8MgABwABiylIgV2W3VcJ0pcHxjQhWWCcAAjr48iLbjh7o8kC8sVkrv48pNpti0Aikaj0RD5VDsTBibTWvTkGIslMcHlFgiAMIQfwPE5QaBCkC+K4AFWJ9QVV14vCAA)

**Input:**
```jsx
test.each([
  { a: "1", b: 1 },
  { a: "2", b: 2 },
  { a: "3", b: 3 },
])("test", ({ a, b }) => {
  expect(Number(a)).toBe(b);
});
```

**Output:**
```jsx
test.each([{ a: "1", b: 1 }, { a: "2", b: 2 }, { a: "3", b: 3 }])(
  "test",
  ({ a, b }) => {
    expect(Number(a)).toBe(b);
  }
);

```

**Expected behavior:**

Same as input. I think it should be handled as a special case, like with composition functions.

Related issues: #2716, #5780.

**Comment by lydell** [comment]
This makes sense I think, since we already have special support for the `` test.each`` `` syntax.
