### ISSUE TITLE
The "trailingComma": "all" option does not work

### ISSUE THREAD

**Issue by haasz** [prettier/prettier#6006]
**Environments:**
- Prettier Versions(!): 1.16.4, 1.13.7, 1.17.0-dev
- Running Prettier via: CLI, Quasar-CLI, prettier-atom 0.56.4 (Atom), Prettier-Code formatter 1.8.1 (VS Code)
- Runtime: Node.js v8, Node.js v10
- Operating System: Linux Mint 18.3 Cinnamon 64-bit, Ubuntu 18(.04 or .10 unknown)

**Description:**

The `"trailingComma": "all"` option does not work properly, behaving like the `"trailingComma": "es5"` option.

**Steps to reproduce:**

Option in configuration
`"trailingComma": "all"`

**Expected behavior:**

From
```
function test1(a, b) {
	// ...
}

function test2(
	c,
	d
) {
	// ...
}

// Originally good:
function test3(
	e,
	f,
) {
	// ...
}

test1('A', 'B');

test2(
	'C',
	'D'
);

// Originally good:
test3(
	'E',
	'F',
);
```

to
```
function test1(
	a,
	b,
) {
	// ...
}

function test2(
	c,
	d,
) {
	// ...
}

// Originally good:
function test3(
	e,
	f,
) {
	// ...
}

test1(
	'A',
	'B',
);

test2(
	'C',
	'D',
);

// Originally good:
test3(
	'E',
	'F',
);
```

**Actual behavior:**

to
```
function test1(a, b) {
	// ...
}

function test2(c, d) {
	// ...
}

// Originally good:
function test3(e, f) {
	// ...
}

test1('A', 'B');

test2('C', 'D');

// Originally good:
test3('E', 'F');
```

**Comment by lydell** [comment]
Hi! This is how your input is printed:

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjAIwAUAhgDT4BGAlPsADpQswD0n+AdP2wC+bNhiy4CxGACZyImGGryAJmyat2XHv15CRUbvgDyAJxwBzHFEoAbGwE985iBGVJRmbHiiE4JAMxymnBKmqih6vKGOnrssH5k5ADkAIJJtEkAQkkMANz6UrLySQDC6cUAIklq+XGGphZWtg5OLm5sUoHFAKLlmkkAYn15INQgEAAOElBEyKCUJiYQAO4ACgsIsyiUAG4QOMqjIHQmlGAA1nAwAMoTZ1bmyDAm6CEgABYwALY2AOrvOGIdzAcGum0BOB2gPsyHARFmYysRDgJhgq1O5i+lGQqFsyLGACsiAAPTKnC5Xa6UL5wAAyVjgOLxbyJxOuDxscAAiugIPAmTZ8SA7iZkSZYXRKHR7DZoEcJmZYL8DjB3sgABwABjGCogyN+pwmsIVfhRO0ZYxMcAAjugcFb0ZRMdikLjBW9kV8cE8Xh6OdzefzXcyxjApcrlKrkNJQ6ccDYHiUIF8sbDmkd0MiACpSrZu5GCQRAA)
```sh
--parser babylon
--trailing-comma all
```

**Input:**
```jsx
function test1(a, b) {
	// ...
}

function test2(
	c,
	d
) {
	// ...
}

// Originally good:
function test3(
	e,
	f,
) {
	// ...
}

test1('A', 'B');

test2(
	'C',
	'D'
);

// Originally good:
test3(
	'E',
	'F',
);
```

**Output:**
```jsx
function test1(a, b) {
  // ...
}

function test2(c, d) {
  // ...
}

// Originally good:
function test3(e, f) {
  // ...
}

test1("A", "B");

test2("C", "D");

// Originally good:
test3("E", "F");

```

In the output, there are no multiline things with commas. Prettier only uses trailing commas for multiline stuff.

I don't think I understand your issue. Could you clarify, please?

**Comment by haasz** [comment]
However it doesn't work for multi-line, for example:

```
test2(
	'C',
	'D'
);
```
Note: multi-line array also does not work, but multi-line object does:

From
```
var a = [
  b,
  c,
  d
];

var x = {
  y: 1,
  z: 2,
  v: 3
};
```

To
```
var a = [b, c, d];

var x = {
  y: 1,
  z: 2,
  v: 3,
};
```

This operation is not consistent.

If the documentation means the break of the long lines as multi-line, then it is misleading and no good.

I suggest some additional options for trailingComma:
- "always-es5"
- "always-all"
- "off" (if I don't want it to work)

**Comment by lydell** [comment]
This:

```js
test2(
	'C',
	'D'
);
```

Formats to:

```js
test2('C', 'D');
```

While this:

```js
this.updateWorkerStateAfterHintActivation(
  tabId,
  hintElements,
  preventOverTyping
);
```

formats as (note the trailing comma):

```js
this.updateWorkerStateAfterHintActivation(
  tabId,
  hintElements,
  preventOverTyping,
);
```

I'm not sure what you're trying to say here?

> This operation [arrays vs objects] is not consistent.

Yes, it unfortunately is: https://prettier.io/docs/en/rationale.html#multi-line-objects

> If the documentation means the break of the long lines as multi-line, then it is misleading and no good.

Which piece of documentation are you referring to?

> I suggest some additional options for trailingComma:

https://prettier.io/docs/en/option-philosophy.html

> "off"

We already have `--trailing-comma none`.

**Comment by haasz** [comment]
It is consistent if handles arrays, objects, and signatures of functions on the same way.

For example, based on [https://prettier.io/docs/en/rationale.html#multi-line-objects](https://prettier.io/docs/en/rationale.html#multi-line-objects), this would be consistent:

From:
```
var a = [b,
	c, d];

var x = {y: 1,
	z: 2, v: 3};

function test(e,
	f, g) {
	// ...
}

test('E',
	'F', 'G');
```

To:
```
var a = [b, c, d];

var x = {y: 1, z: 2, v: 3};

function test(e, f, g) {
	// ...
}

test('E', 'F', 'G');
```

BUT

From:
```
var a = [
	b, c, d];

var x = {
	y: 1, z: 2, v: 3};

function test(
	e, f, g) {
	// ...
}

test(
	'E', 'F', 'G');
```

To:
```
var a = [
	b,
	c,
	d,
];

var x = {
	y: 1,
	z: 2,
	v: 3,
};

function test(
	e,
	f,
	g,
) {
	// ...
}

test(
	'E',
	'F',
	'G',
);
```

**Comment by lydell** [comment]
We're not really happy with our solution for object literals, where we let the user decide by placing a newline. Ideally, Prettier would format everything automatically, without input from the user. This frees the user from thinking about formatting completely, is more consistent and helps avoid code style discussions in more situations. So we're not looking to expand that behavior to other things.

I think we've gone through all your questions now, so I'm closing. Feel free to add more comments here if I missed something!
