### ISSUE TITLE
prettier produces broken code for quoted object properties: latest Chrome browser b0rks on Unicode accents/intricacies (March 2019)

### ISSUE THREAD

**Issue by GerHobbelt** [prettier/prettier#6007]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACeBnGGBmAlgDZwEQBOGADhXDDIXBQDpRv4CuUYj0BACgCUGYGwwSMANwCGVCACMAVhgC8o8ZInoM2KIWrV62LDIDWCAhQgBbDAFkZMABYApGQA8MkACZkBNjbEqEqeAHRK2EIANBgA7s6EYM4YCnTmJgmW+HA+WM7WnADmKbT0jMxImlrUELhEHkgaUFpaAOQsLJwATADsAKIAnG1N9gDyYQDCADJjAMr9sZI6Nk7OcKuMYDLEGBSEJXgyUEWkqRQyYBYw1a0dXX39AGIjDhMz84taK2sbTkk7PYHZx4fDEJzwKC5GhyBAuODYQjYW7tTqcAAM3UmADZXuMwgB1ACSABF+gBBSaTfoAOQAKrEVhAfIQiMwMKQGOywIQKGBODYwXAvJcwHCUZJ7hisb08RNiWTKdT6YzMNtrOwWq0JFLMZNhqN5aSKVTaQyMEyWWyqJz4FRVmANRKdWi9eS5WElWalhbMDZmaymDbyuzLpx4BhReKtdrdViAEIer0q5Z+gPWjkhqhFC5SMhR2DOjBxkkADiTppT2kwaTgeaLJYNb09lfN1YwPggRwUEHrMckAF9ohLCFAGk0xP3UZ0WB6xgAlEk+7W+vZ15jYMjYCDEQg+TjIqeSgB6c8XAEZz8vWjoeXyBUKRWAxYWjzqAPpnkmX6-fTDECA4g5Uc4AbAAfV4AG1umiGC6X6AANGZyTmOYwgXJdgByHg4CaGAKE4OBYlwOgYGSABPPCCKI3RyMCeh9jAKjCIHABdVVpGYLZAV3KEGwAYi-X8b0wfiGwAEiElc-wwcS2B0FddUxfooPRaIAGZongpDphQtCAAUAFUaUmBlgE3ag5CcShmLgNiOM6YhOxgagtAAWjcjtOCMDA4QocjyCoNowjaNoAEIG1dbp4ybfEMN-HRaEIGxQLfYtXXU9F0QrZU21XTocxkPtpN1TLzxy71UwwTow3gNhIoeTFysNMJ4yJGlNJE6qWB8HwZCKIpmAanp0RJWUWuTPKdE6PMwGG7pL2a5t4u1aaWCJGx5svdSpK6zo4GIYgtvPcsWpWvaWDiahjsmXaZM6edUpKtFum6dEAFY7qq-abGoGByM3G40qlV7zxUs7FwSzBOlHfB-olIdbgHABuW5SM4CgWkUJRUagAcQGiEAID+whoGwZBQDkaw4n02EoHJlAiogPcCZANJLmuOZLJ5E5kHwwjCZBIICUSHBubgOYEERRgpEIf7kHAbBycJ0dNwoGB9IuIpVmQfAdk3QnIg8eMLiueg5hkFLphA3X9aIkAjbmUdTjgABFTguzgW3iANkBLIoNWFYUGQFHIgCoFZpLYAJPcXGQUs1L96xNwJC5qAVso1bzVm6AAR04Xk4E1-qdaQPWfftzcbEIPnqMJxETlId3Pe932YBDmOfDjpAYJAfCZBIZ3JlsUuQCgaAvcJg84DpEOGfLzcBwHIA)
```sh
# Options (if any):
(none)
```

**Input:**
```js
// code snippet
function f() {
    var obj = {
      // snippets taken from MathJax code (mml/jax.js), which breaks when fed through prettier:
      postfix: {
        '\u27E9': MO.CLOSE,    // mathematical right angle bracket
        '\u27EF': MO.CLOSE,    // mathematical right flattened parenthesis
        // *** prettier will unquote the keys for the next 4 lines, causing trouble: ***
        '\u02C6': MO.WIDEACCENT, // modifier letter circumflex accent
        '\u02C7': MO.WIDEACCENT, // caron
        '\u02C9': MO.WIDEACCENT, // modifier letter macron
        '\u02CA': MO.ACCENT,   // modifier letter acute accent
        '\u02CB': MO.ACCENT,   // modifier letter grave accent
        ...
        // see complete code sample in the playground link above.
```

**Output:**
```jsx
// code snippet
function f() {
  var obj = {
    // snippets taken from MathJax code (mml/jax.js), which breaks when fed through prettier:
    postfix: {
      "\u27E9": MO.CLOSE, // mathematical right angle bracket
      "\u27EF": MO.CLOSE, // mathematical right flattened parenthesis
        // *** prettier has unquoted the keys for the next 4 lines, causing trouble: ***
      ˆ: MO.WIDEACCENT, // modifier letter circumflex accent
      ˇ: MO.WIDEACCENT, // caron
      ˉ: MO.WIDEACCENT, // modifier letter macron
      ˊ: MO.ACCENT, // modifier letter acute accent
      ˋ: MO.ACCENT, // modifier letter grave accent
      ...
```

**Expected behavior:**

These keys should not have been unquoted as their unicode content may possibly be part of an unquoted object property identifier name, but these may not start such an attribute identifier AFAICT.

Anyway, latest Chrome b0rks and aborts on this file with a report like this:

```
x.js:9 Uncaught SyntaxError: Invalid or unexpected token
```

## Related issues

* #5052
* #5934
* #4327
* #4639

(I got to the latter two via google search, which led to the rest of it and ultimately those got me here, filing a new one after further testing and evaluating what was written in the above items.)

Also relevant: the related option: https://eslint.org/docs/rules/quote-props

However, even without this option, prettier SHOULD NOT produce syntax errors.
(Haven't tested the various flavours of that option yet, BTW)

**Comment by GerHobbelt** [comment]
Forgot to say: you take the prettied output (as seen in the playground, for example), dump it in a file, e.g. `x.js` and then load that onto the browser using a simple HTML file/page, such as this:

```
<html>
    <head>
    <title>MathJax Simple Test Page</title>
    <script type="text/javascript" async src="../../x.js"></script>
    </head>
    <body>

    <h1>MathJax Test</h1> 
    </body>
</html>
```

Hit [F12] and look at the Console log of the browser to observe the SyntaxError in `x.js`. 

**Funnily enough, running the same `x.js` via node (`node x.js`) does NOT cause a SyntaxError. (node v8.11.1)**

**Comment by lydell** [comment]
I tried this in Node.js 10, Firefox 67 and Chromium 73 and none of them gave me syntax errors.

**Comment by GerHobbelt** [comment]
Checked Chrome version here: Windows 10/64, Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by GerHobbelt** [comment]
Updated Chrome; is now reported as:
> Google Chrome is up to date
> Version 73.0.3683.86 (Official Build) (64-bit)

Same SyntaxError.

**Comment by GerHobbelt** [comment]
![prettier-1](https://user-images.githubusercontent.com/402462/54882609-0cc97d80-4e5c-11e9-95ee-f6c28e3070a1.png)
![prettier-2](https://user-images.githubusercontent.com/402462/54882610-0d621400-4e5c-11e9-97f9-59964138144d.png)

**Comment by GerHobbelt** [comment]
... and while working on the screenshots it dawned on me: it's another incantation of bloody Windows-is-not-UTF8-by-default: see the screenshot of the Chrome debugger panel where the Unicode characters have been mangled as this is a load from local (dev) drive, rather than through a (test) server which adds UTF8 encoding headers.

The fix to this issue is to enforce the utf8 encoding for the JS script like this:

```
    <script type="text/javascript" async src="../../x.js" charset="utf-8"></script>
```

and the SyntaxError disappears.

Not a prettier issue, but a local dev platform issue. :blush: 😩 

😞 I have been looking at this and it didn't drop until now.

**Comment by GerHobbelt** [comment]
Issue fixed; case closed.
