### ISSUE TITLE
prettier-cli not error in terminal

### ISSUE THREAD

**Issue by isoftninja** [prettier/prettier#6010]
Why does this code display an error in the playlground, but not in the terminal?
[not valid code example playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdMCeAHOBnMAJwEtsYAdWHOAAgBVqAeOgPhoF4bhKaaBtANI1iUGgGs4mCADN6AXST1BcgNw8a2RVACuAWwBGcQmqgBfSulQgANCAhli0PMlABDQoQgB3AAruEziiuAG4QxAAmNiD6hK5gEjAAythxIgDmyDCE2nC2ABYwugA2AOp5xPB4KWBwiQEVxMEVmMjgeM62InhGMD6xabquyNKuRd22AFZ4AB4AQrHxcEmuunAAMiJww6PjIFPTielFcACK2hDw22O5ICmE3YStg4Ri4d5QUdgksCURMHnIAAcAAZbF8IN0SrFsK0vvgjMEtrZCHAAI7aYgovquAZDJAja62bq6YiZbI3PBHU7nS74nY3GCufS-cL-ZAAJlsWVcxCK6QAwhBdINWlBoEiQNpunQmYECd1TKYgA)

**Comment by thorn0** [comment]
It's [a known bug in the playground](https://github.com/prettier/prettier/issues/5466#issuecomment-438726689). It doesn't seem to have its own issue though.

**Comment by isoftninja** [comment]
@thorn0 this is not bug! It should be! Question is, why is there no error in the terminal?
```
> ./node_modules/.bin/prettier ./demo.md
```
...not error

**Comment by thorn0** [comment]
Any kind of mess inside a code block isn't a Markdown syntax error, the file is still a valid Markdown document, which Prettier is happy to format. Formatting the content of code blocks is just an extra feature: if Prettier can parse the code block, it formats it too, but if it can't, it doesn't mean the whole document shouldn't be formatted. You seem to want to use Prettier as a generic syntax checker to catch such errors, but that's not what it is.

**Comment by isoftninja** [comment]
@thorn0 That is, prettier does not and does not provide any solutions for current problem?

**Comment by lydell** [comment]
Currently, Prettier ignores errors in embedded languages. Except in the playground for whatever reason.

Personally, I wouldn't mind if Prettier threw errors for invalid code in embedded languages. This is maybe something we could do in Prettier 2.0.

**Comment by j-f1** [comment]
👍 as long as a `prettier-ignore` before the embed will suppress the error.

**Comment by evilebottnawi** [comment]
Answers above
