### ISSUE TITLE
Prettier format is geting overriden

### ISSUE THREAD

**Issue by ShadabFaiz** [prettier/prettier#6011]
I'm working on an angular project. I have installed prettier (as extension on vscode and through npm also). I have created a .prettierrc.json and inclused these following options:

``` json
{
    "trailingComma": "es5",
    "tabWidth": 2,
    "semi": true,
    "printWidth": 75,
    "bracketSpacing": true,
    "endOfLine": "auto",
    "htmlWhitespaceSensitivity": "css",
    "insertPragma": false,
    "useTabs": false,
    "singleQuote": true,
    "parser": "typescript"
}
```
I have enabled vscode **formatOnSave** and **Require .prettierrc**, but i seems the once prettier is applied, vscode quickly reset the line to original format.

![PrettierError](https://user-images.githubusercontent.com/8160121/55059462-0a059d00-5095-11e9-9e03-47dff233fd47.png)

The above image is before formatting.

![AfterManualFormat](https://user-images.githubusercontent.com/8160121/55059637-76809c00-5095-11e9-9a4a-2df731c0f8b7.png)
This is the result if i run prettier through script. But when i save my code by pressing **Ctrl+S**, 
code is getting reformatted to image 1.

**Comment by lydell** [comment]
A difference I see between your two images is the imports. That sounds like #5995

As a side not, it's generally an anti-pattern to include "parser" in your .prettierrc.json. See https://prettier.io/docs/en/configuration.html#setting-the-parser-docs-en-optionshtml-parser-option

Does this answer your questions?
