### ISSUE TITLE
Removes comment following TypeScript generic JSX opening element

### ISSUE THREAD

**Issue by matt-tingen** [prettier/prettier#6012]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEkC2AHTAXkwAoAdKTTAHgDEIJqoBXHAIzgCcA+CqqgPQDMAFQAWASzTYIOHAiwBzCHGk4paCVEV9+ANwCGAG2ZxCwACwBfXb0r8RqmLuoD6EOwEoA3CAA0IBB4MBLoyKAGnJwQAO4ACpEIaMggBnoQEgAm-iBsnAZgANZwMADKeAVaisgwnKYBYjA4RgDqkvBoFWBwpUkSIXr9AJ4pYGjJAVpoXDBx+Yo4BsgAZsbTAQBWaAAeAEL5RSWlBvIAMlpwK2twmzulVUZwAIrMEPBXRusgFZzTnCkwIZ4VRgTgSYI5PBg2AtLIwMTIAAcAAYAlCINMWvk8CkoaouHpLgFOHAAI7MCQkuYGBZLJCrT43EDTdQ1OpMzTaR4vN6XenXAIwAxsWGZeHIABMgvyEiMVQAwrJFikoNAiSBmNMRMLkvzGVYrEA)
```sh
--parser typescript
```

**Input:**
```tsx
const comp = (
  <Foo<number>
    // This comment goes missing
    value={4}
  >
    Test
  </Foo>
);
```

**Output:**
```tsx
const comp = <Foo<number> value={4}>Test</Foo>;

```

**Expected behavior:**
```tsx
const comp = (
  <Foo<number>
    // This comment goes missing
    value={4}
  >
    Test
  </Foo>
);
```

Note:
- The comment is preserved if the element is not generic or if it is self-closing.
- Using `//` vs `/* */` does not appear to change the outcome.

**Comment by sbusch** [comment]
I can confirm this bug. I reproduced it on the [playground (link)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEB3CAnAazUwF5MAKAHgGEIBbAB2gRkoBUA+AHSkz8wD0AzLTp0WPARwCUAbh49IUDJgZ4IAIwA2cOqQo16TKC3bde-ISPrjYmLRAw8OlAaOMsZ8qCAA0ICAYYAEt0ZFAAQzx1bAAFKIQ0ZBAIgDcIYIATPxANPAiwAjgYAGUGAuCoAHNkGDwAVzh-AAsYOi0AdWbg+DRysDgSxJ7g1J6AT2SwNCT-SrQ4PBhY-Kq6COQAMwitBf8AKzQADwAhfMLikojxABlKuC2dvZBDo5LKqp0ARXqIeEfdk0QOU8As8MkYOMGHA0GA8MEgjk1JUYB0sjBmsgABwABn8akccA6+QYyTUMMWqQe-gAjr94CtAkkUBE0ABaExwTJcnJ4OB04J8lYRNYbJDbQH+BZ0YK1BpAtAfb70h7ip5AmARDRozIY5AAJn8dQiwS0H1E62SUGYOXqCzYWuZEoWAF8XUA) before I found this bug report.

**Comment by duailibe** [comment]
I just confirmed the problem is the AST doesn't include this comment, just opened https://github.com/typescript-eslint/typescript-eslint/issues/583
