### ISSUE TITLE
object-curly-newline conflicts with max-len

### ISSUE THREAD

**Issue by fandy** [prettier/prettier#6023]
With the Prettier settings:

```
"max-len": ["error", { "code": 80, "ignoreComments": true }],
"object-curly-newline": ["error", { "multiline": true }],
```

Problem is that when formatting this code:

```
  @autobind
  private handleResize() {
    this.setState({
      showControls: window.innerWidth >= LARGEST_MOBILE_BREAKPOINT,
    })
  }
```

The two rules conflict because this is longer than 80 chars:

```
  @autobind
  private handleResize() {
    this.setState({showControls: window.innerWidth >= LARGEST_MOBILE_BREAKPOINT,})
  }
```

What can one do here to remove the conflict without disabling the rule?

**Comment by lydell** [comment]
Hi!

> ```
> "max-len": ["error", { "code": 80, "ignoreComments": true }],
> "object-curly-newline": ["error", { "multiline": true }],
> ```

These are _ESLint_ rules, not something from Prettier.

Here's how Prettier formats your code:

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCpyYw7AA6UOOAAugK4wQBGAllACbmUAOATswG7p4OABbp2qOACVCzAF5wAFAEoSnSjhgjmmAHSY4MAMowhSshQ2VMIiAHcAwtBg8IqTEhx3Wbe7tZQcDwA6sxsWjgAfAC8OAAyAIJSAOIAokZ4APoAsgDyAEIAknGpmflSqQkA0gAKuYUAcngANOqUAL7K6u3k7SDNIBBcMMzQmMig6DyudjVTCOMo6PwQYf0gjDzoYADWhkZc26wA5sgutHADIjAAtqjB2vCYh2BwRgvMI-yfAJ7I4Nh1qwDDwYDUtscbuhkAAzdDuS4gABWmAAHvktrt9ugbnA4qw4LD4QYBijUUYTpIAIq0CDwIkIgaHHgg-4wH5cQhgPjDda8VgwULhETIAAcAAYma4DMEtlx-rxCEF+ISBjw4ABHWjMdXg9CQ6FIOGMkAGG7MM48C4DTCUuA0umEo3ExGmRhCrTIABMAxc6GYqBOThuUP+UGgqpAtAMeHQjEWxoM7XaQA)
```sh
--parser typescript
```

**Input:**
```tsx
class Test {
  @autobind
  private handleResize() {
    this.setState({
      showControls: window.innerWidth >= LARGEST_MOBILE_BREAKPOINT,
    })
  }
}
```

**Output:**
```tsx
class Test {
  @autobind
  private handleResize() {
    this.setState({
      showControls: window.innerWidth >= LARGEST_MOBILE_BREAKPOINT
    });
  }
}

```

As seen above, the output does not look like the output you provided. It must be other tools you use that cause your output. Maybe ESLint? Maybe VSCode?

Finally, we recommend turning all linting rules that conflict with Prettier off. The easiest way to do this is using [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier). See also: https://prettier.io/docs/en/eslint.html

I'd recommend running Prettier and ESLint from the command line a little, to learn which tool does what. Then it's easier to understand where a certain piece of formatting comes from.

**Comment by gkatsanos** [comment]
Same issue. So airbnb linting likes a newline after `{` but prettier reformats this after the ESLINT autofix back to oneline. I like the prettier max length line but I'd like to keep the object-curly-newline rule. Somehow I need both.. makes sense?

**Comment by lydell** [comment]
@gkatsanos If you _really_ want that rule you need [prettier-eslint](github.com/prettier/prettier-eslint).

**Comment by gkatsanos** [comment]
You mean https://github.com/prettier/prettier-eslint?
I was almost about to drop prettier because I realized there was no way to disable printWidth which resulted in very intrusive code styling (either very in-line or very new line) without the chance to adjust on a case by case basis (unless you ignore which adds a lot of overhead...) 

Is prettier-eslint fixing that? (sounds like it actually)

**Comment by lydell** [comment]
Yes, that's the tool I meant. (I've edited the link in my comment now.)

There's no way to disable printWidth, not even with ESLint or prettier-eslint. If you don't like printWidth, then Prettier is not the tool you're looking for. printWidth is at the core of Prettier and can't be taken out. The whole printing algorithm is based on it.
