### ISSUE TITLE
Add a way to disable functional composition rule

### ISSUE THREAD

**Issue by leonidasv** [prettier/prettier#6030]
The change introduced by #4431 isn't disableable. Since we upgraded to 1.13+, lots of our files are being changed by this rule (mostly Redux related) but this goes against the previous stilying rule (same line for Redux `connect` invocations).

As this rule isn't disableable in configs (afaik), we had to downgrade to 1.12 in order to avoid the warnings on those files and breaking the previously stablished rule.

Could this rule be made an option like `singleQuote`, `bracketSpacing` and others?

**Comment by evilebottnawi** [comment]
Please provide examples

**Comment by leonidasv** [comment]
@evilebottnawi 
```
export default connect(mapStateToProps, mapDispatchToProps)(Component);
```
Was a valid code until 1.13. Now, this line is turned into:
```
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Component);
```

Since this is common line code in a lot of React files, enabling this rule changes a lot of files (for example, in our codebase, it changed 200+ files in just one react project).

**Comment by evilebottnawi** [comment]
Yep, looks ugly, it is only in `export`? Or you can have other examples?

**Comment by brainkim** [comment]
related: #5969 :trollface:

**Comment by leonidasv** [comment]
@evilebottnawi 
#5969 #4935 #4751 https://github.com/prettier/prettier/issues/4935#issuecomment-422843356

**Comment by evilebottnawi** [comment]
@leonidasv let's close this in favor https://github.com/prettier/prettier/issues/5969 (feel free to feedback)
