### ISSUE TITLE
Support golang template/html

### ISSUE THREAD

**Issue by lucacasonato** [prettier/prettier#6034]
We should consider supporting golang's template/html syntax. This syntax is gaining popularity and is being used by many people, especially because of static site generators like [Hugo](https://gohugo.io/). Prettier works fine for certain things already but breaks on others). In some cases prettier formats as expected but sometimes it completely breaks the code. A good implementation should fix this. I am including some examples below.

### Correct
Basic if statement: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zU55qARhABMAnp27dUAgJYA3TkxjzgwcpIBm5OAEdyAOigBDGnHJMQAGQCuYfafIBfOyzFj58gBJw6dCOUvWnziYwSggCDgHiAPRSsgGokfzCnPHsjCAANCAQAA4wktAAzsig+gBOpRAA7sRlCEUo+tIQkgIZILyl+mAA1nAwAMrZXZJQAObIMKUWcJmpAOqUkvAFQ2Bw-XVLMktCyOAFRZkjBXClMMSdozT6yKr6dCeZAFYFAB4AQp09ff2GcGYjOC3e6PEAvV79EajOhwACKFgg8GBDxmICGpROpT2qTa2VKIxgcxaMEoyAAHAAGTJ4iAnOadbJ7PFwTHSIGZUpaCySTkXfRXG5IO4ozInGiSCZTVEFKEw+GIoFCkGomD6XhEgQk5AAJkyk30kjoUNwEBo1z2UGg7JAFhO+DV9WFJwcQA)
Basic ranging: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8AbAlgPgB0oMNhhUAnAQygHM5UA6ABzghe0YF9vj1CMQZgCu2IiVJSActQC2cJKnLMo8nn0mDhAejESpyiggAmqXvwyYdefCAA0IDjFzQAzslDVKlCAHcABW8EDxRqADcIXBMHEAAjGjAAazgYAGUWajBcemQYShE4RwALGDlsAHVi3Hg3TLA4NJCa3HCagE9kcDcPRxy3OEoYAJo6OWpkADNqbAHHACs3AA8AIUSU9PUAGRy4KZm5kEWltJy6LgBFEQh4fdmikEzKAcou0vLYlkocmAromGKyAAHAAGRxfCADCo0FhdL5wF7hPaOShwACOIlwqJG1DGEyQ03ujgGclweQKDzcZ0u11uBIODxg1DifxMAOQACZHPlqLg8PQAMIQOTjLpQaDIkAiAYAFWZoUJA14QA)

### Not correct
Basic template: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgAIAmcBmBLKOdAHRAAcBDAczlPQF97ioAVACzwGd0v0Ko+AJxh4wAGzgA6dAB4ARoPQB6AHzM06aY3UYEmBkyggANCAhkR0TslAVBgiAHcACnYTWUFAG4Q8mEyAKFGAA1nAwAMqUYARUyDCCAK5wpmwwALZiAOoc8JzRcBHueCJeJQCeyOCc1qYEnHDCzoLU6RTIOBRiDaYAVpwAHgBCLaHhERTpcAAyBHAdXT0g-QMRsRIAiokQ8AvdKeR2DYJVaZkBZIIEMFl+MGzIABwADKaXEA1ZLWRVl3DHXnmpkEcAAjok8CDmq12khOvtTA10nh4kkDpx1nAtjt5nDFgcYBQ5LdMPdkAAmUwJCh4MSxADCEHSbSqUGgQJAiQaLCJHnhDUYQA)
Another basic template: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgAIAmcBmBLKOdAHRAAcBDAczlPQF97ioAVACzwGd0v0Ko+AJxh4wAGzgA6dADkKAWzhJ0adJIrDREyVAVFGzVQkwN6IADQgIZEdE7JQGwRADuABQ0J7KCgDcIeJgWIABGghRgANZwMADKlGAEVMgwggCucJZsMPJiAOoc8JwJcLFeeCK+FQCeyOCc9pYEnHDCbuFU8hTIOBRiLZYAVpwAHgBC4VExsXoAMgRwPX0DIMMjsUkSAIppEPBL-ZnkGi2Cddm5wWSCBDB5gTBsyAAcAAyW1xAteeFkdddwU6+RaWQRwACOaTwYPa1C6BxWLXkeBS6SOnE2cB2e0WSF6h0sMAoIXumEeyAATITwngxEkAMIQeTwlBQaAgkBpFosYnefEtRhAA)

### Weird edge cases
Works online but not offline: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgBM4DMCWU4AEAOiABYwC2ANiQL61FRoAk6EMBSAvAQHT2MAPAEIAIgHkAwgBUAmgAUAogXLUAfENVUCVAIZQA5lxIISGqIwIFBpOLvTmrVwRTgxdBMKV0AnAM5uxiAAqtIAYgC0ABwkBAD0jk4ubh5Quq5BAG44cADuAA4QPjCxkLAIMEG5OOgwpFyY2WBwEdW1pAA0BHg4MDi6VBF+YANwXACMvAAMsQmWSa7uKjAw+RFwAI4ArjiZQQAaEcEAghGSEBT5un0ARlRwpdDwsEE5XHDoBg8g8YnOfTB7mppHA-DBBHEAUDGPNnFQ8ABrAg+OBUIJggCe9z8tjcsVIKKwQXIqz8SDicTBujACKudV4Nwg7DBPl0+TA6CgvEgFDijOZMFZ+TiABZeJMAMxxMB+Px8pkwFls3gUPDc2UkWFOPDwAw+XoY9HeCVREURACyklyAE4onEAMphKAAcUUUSwAClpBLnftcopxIY-AA1ADsAC0YAAmUMAOX2YQguggx3yFFkFCi4xwW32EHkCLC4g9uQ9UUUACV0AioAAZeTm8SlHwQWVFHAGPBBfTQDEUCBbPyzP7WeFQJEotEkTHY3ElH4E7DElb5MkUwdwXhYJ66XKgi6bnlxSd2AJyzIAVl4EvF0tlcQGVHVQ5AWqsOrgeoNRt0JrNFAALx8ChFAvDZoCoAArYIUQoMI-A2MApnGe0ACERQANg9TIK3Ee1QxucM-AlABJcQo0UCgsHg9BxgvLYAAlMhImAAGpZCiTJFCwONQywAB1Y5gmbVs-HbTsoG7KBe37Qdhy1QQxwnVF0RgLFQTnfFCWXUlyWlTleFZXJOxgbkLgfLBUXQeUBSFCIYAgMA4kySYpmmOJ0BwMEbMVQU2XsxyVTVGUX1+BSlORFTpzU2c4DxBdtJICkOSgSC-G5KgB3QLA9BRMzeV0SDdAADzieEbjlUgO1IeEDHIXg0ria1xSvDDKRi0EPOwXQtioUzVS5EKzAU4Z9XyDg-B8MAgmSzk0oyrKct8Q9zMKkqypwCq4iquravqxrmro3g2p2mrqv6tU0rMCFRpwcaR0EW77pq+aehgBjqr2vpDEDWsk3QAAKABKABuG6wDGmBEghWx7HMeZBEZdAMQIdBrl0IZ8kNacIYgKgaB+NH3Hs3wvkqEgAGIHLAYaoCcaw0kyTw9FlIJGZuXwCHZ3x1mKq4oHQCIqAMLndEyDmfCF86CBuAwpbq+cR2cTymbAFm-CCMp3DwOAfFp+n6cEDw1d0VmSG5yWblZAWtKXJLYhnMYSCudBPMMAL8iQAgonyYqQeunAKAMN8DasSbppIElVz0lLeH0Posfyh9ZTcOVMoMVsyogDOAH0sF6qgc+knO-HT-ReHyQx8Tgc6gijDDNTp0ODZNs2QEFvAxxaO5HKRAYOygD2HY6oJt1gIYcAAuAvfGKZxvkpvm4IEEwQhXQlaSG4thWaBmdNjXzbFiWAoMAx7j1n41PyJ2QC3neLEJ9GT7Pm-IHxtkAliImMfcHwyaCCmFt7RbHyIUYoHxzjlFgI3JeVhfD9AiFrFsVAD4gCASAsB8B0CQOePOAg8CMZwD5voTA6BR4DE-j8AhQtdA3CiiAaQ2cX6i2yAYa4OBoD61gY9fme824W2fufCIOAyjXUpPzDezg+TbwclAeGi8DaCBVnw1Bb89CrkIAItRH9vjdDIYfcWvhgGgKKFgnBFQuFL0EL1FRbMj480ZgQCgkseoOUsbAtAyJ9BfD4HoDEA5TJXC+H4AgAgFFWPhLYgxwj4AUGICASRzcjZRLQWLKW44CBoBwFgAgmwCCsHYCqFIvAah8BqPQfBYA+iZEIJ4hA6BQkMASnbVAwBeCly2AYAQCTPG8DSK4RpIdYGZOANk3JGx8lsH6sU0pJT0D0B4foFJk0IgQQxGYAGYAtg+BRLAIGN0JF1IFoM8J3CHyJMNhtC5TgjkNLCcMiEvVEkQhVhvF5uwHpxEZvIw2FBdB4GRHjG+fy8DuKsGgWJ+Q9DwHiUE3R-AGAKIhCCuRMIkVPQmlNHS0dkoQEwA1bYusMRJ0goSnwGIIg3hvJMUugcgpciuq+U5H4vxqR-H+CIGwog4DiPsVi1oMIXlEABcQUwfDSFDLQgA0iKcYHp7QwAAIokWOBsYMBgKzBgAvkG4AEIAXj8BQfYUr8gilkFgCsmQGKsSiLQmA0hFDjHkDgDCkFJ4QBgS3FsbZ9QSSkjJAcL41Dg0hg9DFBBw7YrXPpVK6U1aLVyitAqRVSrlTlIUUBusGpykmOMMUUotgUGshm6+Ph6XZs9fTFl+o2XTmNKaCI4ZzTyFDD4YMEAJQUBIhiBEwZWJRn5R6CUwQPSYUgqhBEUx+K1l0CcTkGEojWl0FaCAGwbioQ9Dge0qVjhSrKlEfimRJD8XkCReQFARTWkrU4XGPqOxdhID2KAfZA1iIxWGiGd1MURzICuaNVIaR0lIAyBUSp2QGSPPyXyQpRTimvHERqUGwPlsZSHat3462-gbZIUgWANgbGKlscMwRJBQHlVKiUrFzT7AoPIWM3bFAYXDDcfipAowkXNBsRQUZZU+FkDgDYHpioYnNDgcMGFxD8TiB6Cg4ZFUGpgP6YItZpDrKZaHW9YlfUPpAE+l9ckEkhq-R+yGEasWRz-THAyRkTJJ10JZKg1kkN+TWNTZyrl3KeW8s5uy1MUNBqM-dBG8pkbyJhpQKg5hbmNJAB0EAEBxocKgH4ZAoBfAtlyPIZayXkC6cyBAGosXb6shpG4e0VwwB4AMMgQUWw4Bxa0Kx3ooIKtwHtAgPwvRdgGlyyFIreAAjFHkKyAwfzkBYAofVkAaViqoRKwiMr6Q4C1h1uNybcWZv2iq-cRVWx2BwDWygqbVx-C61y1oIr+R9SwH4jUOoyAohTDi1d1scB+JCly1d0EusalFZRNsHAKJhu6FG7oQ7AQ4sBFVDVnwdXIfbbgLt-b4OpvuBY3d0gyAoxxb8jgMcBhzgUDGygaS+AisbmkLQlLSAJtHfoEAA)

The syntax has some similarities to Handlebars (#5340).

**Comment by lydell** [comment]
Related: https://github.com/prettier/prettier/issues/5581#issuecomment-459417515

**Comment by zacharymorel** [comment]
Following this issue for golang template support.

**Comment by MarkRosemaker** [comment]
Seconded. This would be a great feature.

**Comment by brudnak** [comment]
This would be great 🙏

**Comment by akellbl4** [comment]
I tried to run Prettier on my Hugo project and found [case](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wAEAJnAGZxaHpZgC8AOiMMITlKQB6EB0Ayjng8AIgEMYongFtRUHBXREmM9jwBW6JgF8tTAHyoA9JlwE9IADQgIBHNHTJQorFggB3AArOEDlKIBuEDjEliAARliiYADWcDB8eFHsAObIMFgArnBWABYwUgA2AOo5gnDoiWBwfD6COP6CAJ7I4OgOVuzolDAekckyyGSiBV1WGpwAQpExcXyiUnAAMuxwg8OjIOMCUMkFcACKGRDwayPZIIlYXVgteYWheLiwRcEwOcgAHAAMVo8QXUVIngWo9ypR-KsrABHI7wXo2XwgUToAC0UDgcFIISsWDgMJwuN6on6olOGy6UhwaUy53QKT2h2OqyQQzOVgkYRexDeyAATOzIjgCikAMIQKQDFBQaCQkAZLoAFVEYV8rI2-iyAEkOAh4th8DAAIIcPgwRp7MlwHRAA) which can cause "SyntaxError"

**Comment by flexbox** [comment]
Same here, coming from the JavaScript world it's a frustrating experience when the go templates are not formated automatically.

I fixed by disabling the format on save
![image](https://user-images.githubusercontent.com/360936/76950964-2c7a7100-690b-11ea-94b9-cc69d66d5777.png)



@akellbl4 the syntax error could come from the mix of with `"` and `'` 
For example, for links, I am using this
```
        <a href='{{urlBrandReportPath $navLang .Brand "brandReport" }}'>
          {{.Name}}
        </a>
```

**Comment by bernardbaker** [comment]
`<!--  -->` worked for me! Use it to split the code blocks that would otherwise be split by the Prettier formatting.

**Comment by seanburlington** [comment]
> `<!-- -->` worked for me! Use it to split the code blocks that would otherwise be split by the Prettier formatting.

That doesn't work if the code block is a conditional and you end up with only half the comment rendering

**Comment by NiklasPor** [comment]
I wrote a small plugin for prettier which will stop prettier from breaking your go templates:

[prettier-plugin-go-template](https://github.com/NiklasPor/prettier-plugin-go-template)

Only supports: `.gohtml`, `.gotmpl`, `.go.tmpl`, `.tmpl`, `.tpl`, `.html.tmpl` extension to not break other html files in the same repository. 

Hope I could help a bit 🚀

**Comment by thorn0** [comment]
Prettier isn't going to add more languages to the core. This should be implemented as a plugin.
