### ISSUE TITLE
Preserves multi-line statements

### ISSUE THREAD

**Issue by pauldraper** [prettier/prettier#6036]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTYAHSkxyUwEYSBfAbhJMig0wCN9D2KAmTekiAA0ICAAcYAS3TJQ2AE7yIAdwAKChGmQhsANwiSAJsJBt52MAGs4MAMpiLkqAHNkMeQFc4IgBYwAtgA2AOo+kvBoDmBwtprhkrrhAJ7aYGhaIk5ocPIwqubO-tjIAGbYgdkiAFZoAB4AQuZWNrbY-nAAMk5wpeWVIDW1tk7OgXAAih4Q8L0V3iAO8tny2mzYbHCBJmLyTjDBRjA+yAAcAAwiOxDZweZi2jtwy7o9IvJwAI4eku-52IXFJBlOYibL+SRuTzzNAjMaTaY9IF9eYwdYHQxHZA8ETubCSQIjADCEH8RW0UGgrxAHmyABV1lokXMaDQgA)

**Input:**
```js
const a = {
  a: 1
};

const b = { b: 2 };
```

**Output:**
```js
const a = {
  a: 1
};

const b = { b: 2 };
```

**Expected behavior:**

I expect consistency: both statements should be either be single-line or multi-line.

Instead, Prettier is giving my team choices and arguments (gasp) about the format of the exact same AST. The reason I'm trying to use Prettier is to prevent that.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/pull/4685?

**Comment by pauldraper** [comment]
That's a PR, but that would solve this (and have other effects).

**Comment by lydell** [comment]
Hi!

See here why Prettier does this: https://prettier.io/docs/en/rationale.html#multi-line-objects

The solution for those who don't like this (like myself) is the proposed `--pure` flag that @evilebottnawi linked to.
