### ISSUE TITLE
All prettier errors are labeled `eslint (prettier/prettier)` instead of displaying underlying rule being violated

### ISSUE THREAD

**Issue by dandonahoe** [prettier/prettier#6037]
Seems that every linting violation related to prettier is given a generic `eslint (prettier/prettier)` without specifying which eslint rule is being violated under the hood. This is making it near impossible to set up rule overrides because I don't know which rule to override.

Example of one error:

![Screen Shot 2019-04-05 at 9 33 39 AM](https://user-images.githubusercontent.com/1390068/55632356-1fab4e80-5788-11e9-98fb-671f293ff9af.png)

I could violate 10 different rules on 10 different lines, but they all just display `eslint (prettier/prettier)`

I'm going nuts trying to figure out what eslint rules I should be telling prettier to ignore to have this ignored globally.

I'm seeing this happen both when running prettier by command line and via plugins that report prettier errors in my IDE.

Am I going about this wrong or is there a better way to dig deeper into the actual violation occurring?

Thanks.

**Environments:**
- Prettier Version: 1.16.4
- Running Prettier via: Node.js 10.15.3
- Runtime: Node.js 10.15.3
- Operating System: macOS

**Comment by lydell** [comment]
Hi!

First off, Prettier is not a linter. A linter analyzes your codes and points at places it wants you to change. Prettier is a formatter that takes a piece of code and outputs another piece of code.

Some people like to use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) to be able to use Prettier via their already existing `eslint --fix` workflow, without having to set up more tools. eslint-plugin-prettier is supposed to be used with autofix, but it of course still has to report errors too. So the plugin diffs the input and output code to let ESLint editor plugins know which parts of the code to highlight in red.

When using both Prettier and ESLint, we recommend turning off all rules that are unnecessary or might conflict with Prettier. The easiest way to do this is by using [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier/).

See also https://prettier.io/docs/en/eslint.html

Does this answer your questions?

**Comment by dandonahoe** [comment]
@lydell Ooooook, thanks. I have it integrated with eslint-plugin-prettier like you mentioned and even have airbnb rules along with a bunch of custom eslint rules (based on this boilerplate https://github.com/react-boilerplate/react-boilerplate/blob/master/.eslintrc.js)

I always thought that prettier and airbnb were just pre-configured ESLint rules packaged together to be more convenient.

Feel free to close this issue unless I've said anything incorrectly above. I seem to have had the wrong impression for several years at this point. Durr.
