### ISSUE TITLE
writing on symlinked files

### ISSUE THREAD

**Issue by localhostdotdev** [prettier/prettier#6039]
**Environments:**
- Prettier Version: 1.16.4
- Running Prettier via: cli
- Runtime: node v11.11.0
- Operating System: macOS

**Steps to reproduce:**

- `echo 'a = { "a": 1, }' > original.js`
- `ln -s original.js link.js`
- `prettier --write link.js`

**Expected behavior:** doesn't modify the original

**Actual behavior:** modifies the original

I got this because I symlink `prettier` itself to `./../node_modules/.bin/prettier` and it formatted the prettier file.

Also happens because I'm doing something like `ls | xargs prettier --write` basically to format all files.

fun fact: it takes ~5s, and then I get and error when executing the new prettier file: `env: node\r: No such file or directory`.

**Comment by lydell** [comment]
Hi! Can you provide a full example of what you're actually trying to do? It's not entirely clear to me.

**Comment by localhostdotdev** [comment]
I have a medium-sized repo of all sorts of files, mostly ruby. I'm using @prettier/plugin-ruby as well as prettier (for css/js).

I don't format on save, I just like to periodically format all code so I have a `bin/prettier-all` script:

```
#!/usr/bin/env bash

# https://github.com/prettier/prettier/issues/6039
# https://github.com/prettier/prettier/issues/6040
git ls-tree -r master --name-only | grep -v bin/prettier | grep -v .prettierrc | xargs ./bin/prettier --write
```

Works pretty well, it just ignores all the files it can't format, and formats everything else.

Running `prettier` doesn't pick up `@prettier/plugin-ruby` for some reason so I have it in my `./node_modules`. But I don't like to type `./node_modules/.bin/prettier`, I prefer `./bin/prettier`, so I made a symlink (nothing crazy right? I guess I could just make a bash script that calls the original prettier but I prefer the symlink).

Anyway, when running `./bin/prettier-all`, it hits to `bin/prettier` path and formats the original `./node_modules/.bin/prettier`.

**Comment by lydell** [comment]
Thanks!

I tried out what `sed -i` does, and it turned a symlink into a regular file with the updated content and did not change the original file.

So maybe Prettier should treat symlinks this way too.

Are there other examples of tools that we can compare with?

**Comment by localhostdotdev** [comment]
ok, seems to be be the way `rubocop` does it too (most popular ruby linter that has some auto-correct/formatting)

actually, looking closely, both rubocop and prettier replace the symlink with the updated file, so it seems to be the expected behavior, I'm going to switch to a bash script that calls the ./node_modules bin
