### ISSUE TITLE
.prettierrc parsed as js/json by prettier

### ISSUE THREAD

**Issue by localhostdotdev** [prettier/prettier#6040]
**Environments:**
- Prettier Version: 1.16.4
- Running Prettier via: cli
- Runtime: node v11.11.0
- Operating System: macOS

**Steps to reproduce:**

- `echo 'printWidth: 100' > .prettierrc`
- `prettier .prettierrc`

**Expected behavior:** either parses as yaml, or ignores as not parseable

**Actual behavior:** error:

```
.prettierrc[error] .prettierrc: SyntaxError: Unexpected token (1:11)
[error] > 1 | printWidth: 100
[error]     |           ^
[error]   2 |
```

(hitting this because I'm doing `ls | xargs prettier --write` basically)

**Comment by duailibe** [comment]
I never thought this could be YAML. What should we do here?

**Comment by davidmurdoch** [comment]
Prettier's docs state this file is YAML: https://prettier.io/docs/en/configuration.html

Could someone update the docs to omit the YAML part until the PR is merged?
