### ISSUE TITLE
Subsets of HTML

### ISSUE THREAD

**Issue by dlferro** [prettier/prettier#6041]
I've dug through a few issues in regards to individuals wanting to leverage Prettier for markup languages like EJS. Is there a route to go down to potentially implement support for other languages like EJS?

**Comment by lydell** [comment]
There are a bunch of open issues regarding support for various templating languages.

**Comment by thorn0** [comment]
Prettier now has the plugin API for this: https://prettier.io/docs/en/plugins.html

See also [issues with the "scope:plugin" label](https://github.com/prettier/prettier/issues?q=is%3Aissue+is%3Aopen+label%3Ascope%3Aplugin).
