### ISSUE TITLE
Preserve explicit line breaks in JSX

### ISSUE THREAD

**Issue by rhysforyou** [prettier/prettier#6042]
Prettier is currently very aggressive in how it formats JSX. If a multiline fragment of JSX can be compressed to fit on a single line, Prettier will compress it without hesitation. However, in certain cases this is undesirable, such as when you have multiple elements whose children vary in length, with some able to fit on a single line, and others needing to be split over multiple.

In these cases, it'd be desirable to have JSX behave the same ways object literals do, where newlines are preserved such that the following:

```js
const obj = {
  a: 1,
  b: 2
}
```

isn't forcibly reformatted into the following:

```jsx
const obj = { a: 1, b: 2 }
```

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAsgJ4DCEAtgA7QIwAUAlPsADpT74BOcM6XHADzoANgD52nToJE4JHKZwAyEHhXw4qAZ3TqAJhBGr8WnDHwBDCr0lTBAelnzFMubcUq1G7bvwGjXCZmltYwADT4kFBacNi8-JZ6mjimYDhQAOb4cLLhJnB6fhDZOOhaFBB67vgOTrYOovIAviBhIBBUuNBayKAWXFwQAO4ACv0IPSgWAG4QOHqtIABGXBZgANa8AMpUa+kZyDBc6HBtABYwFCIA6mdmcFq7YHBbE2Y402bEyOBaPW3pGJcGAjVYZCgWZCoCwiGJtABWWgAHgAhVYbbZWOBKdJwKEwuEgRFIrb7ERwACK6Ag8HxsNOIF2XCBPyWFiWxCMUEWVC46Rg13mMDOyAAHAAGNq8iAxa6rKg-XkPOBcaZ4to8ACO6BwPFBFnBkKQ0PpbRiFBwh2ODNMmXJVJpeONBIZMHZgr0wuQACY2kcLDhZJlyBQIT8oLRFmU4AAVdmTE0xJpNIA)

**Input:**
```jsx
function MyComponent() {
  return <ul>
    <li>
      Lorem ipsum dolor sit amet
    </li>
    <li>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    </li>
  </ul>
}
```

**Output:**
```jsx
function MyComponent() {
  return (
    <ul>
      <li>Lorem ipsum dolor sit amet</li>
      <li>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      </li>
    </ul>
  );
}

```

**Expected behavior:**

The line breaks from the input, which put each `li` tag's content on a new line, would be preserved in the output

**Comment by lydell** [comment]
Hi!

Prettier isn't more "aggressive" when it comes to JSX than anything else. At its core, Prettier tries to always give the same output for a given program (AST), regardless of how the author chose to write it. That's part of the power of Prettier – it leaves no (little) room for human style choices and thereby no room for unproductive code style discussions.

We're not happy about our workaround for object literals (where we _do_ look at how the object was originally written), but it's the best solution we've come up with so far. https://prettier.io/docs/en/rationale.html#multi-line-objects

When it comes to your JSX example – I totatlly see your point about the `<li>`s being inconsistent. When I first started using Prettier for JSX it bothered me too. But after I while I realized it doesn't matter much. It's far more worth not having to manually format JSX.

Keeping the original newlines would go against the goals of Prettier. It opens up for unproductive PR comments ("please add a newline here"/"please put this on one line"). And another really nice thing about Prettier is that it frees your mind from even _thinking_ about code formatting (after using Prettier for a while), but now you'd be on the lookout for newlines to insert/remove all the time while writing JSX.

The JSX formatting is a very stable part of Prettier, that we're happy with, so it is not likely to change. So I'm going to close the issue.
