### ISSUE TITLE
Silent CLI output if `--check` passes

### ISSUE THREAD

**Issue by borekb** [prettier/prettier#6048]
A standard behavior of many CLIs is to display error messages if there are any but be silent if everything succeeded. For example, in a CI build, I don't want to see this:

> Checking formatting...
> All matched files use Prettier code style!

We run a few tools like `tsc --noEmit` or `eslint` on the CI and `prettier --check` is the only tool that produces output even if everything is OK.

Some options I looked at:

- `--loglevel silent`: it does return a non-zero exit code but doesn't list files with formatting violations.
- `--list-different`: produces a raw list (I'd like to see a human-friendly message _if_ things fail).

I think that `prettier --check` should just produce an empty output by default, though I understand that it would be a "breaking change" in terms of UX for the current users.

**Comment by lydell** [comment]
Hi! Thanks for issue. Can you elaborate on _why_ you want this?

**Comment by borekb** [comment]
@lydell Just for consistency. For example, TypeScript doesn't output "Type-checking your project... All is good!", same for ESLint. It's just common to have an empty stdout when everything is fine.

I know it's a small thing :)

**Comment by lydell** [comment]
I would rather have it the other way around – ESLint and TypeScript printing friendly messages when they succeed. Like Flow does:

```
$ flow check
Found 0 errors
```

So it's not obvious that Prettier is the outlier here.

I don't think your argument is compelling enough to keep this issue open. We've got enough issues anyway. Thanks for the discussion, though!
