### ISSUE TITLE
Not working in webstorm

### ISSUE THREAD

**Issue by MatteoGioioso** [prettier/prettier#6055]
**Environments:**
- Prettier Version: 1.17.0
- Running Prettier via: Webstorm 2019.1
- Operating System: Windows 10 professional

**Steps to reproduce:**
https://prettier.io/docs/en/webstorm.html

this is my config, I am trying to run it from the global installation, same result with the local one
![webstorm_prettier](https://user-images.githubusercontent.com/43592430/56090802-4f1d3200-5ed1-11e9-8d49-70d14501012e.png)

Pressing `atl+shit+f` (I have binded my keyboard with this keys sequence) nothing in happening

**Expected behavior:**
It should work

**Actual behavior:**
Not working

**Comment by Jokerwin** [comment]
Hey, why did you close the issue? Were you able to find a solution?
