### ISSUE TITLE
Broken link. Documentation page "Integrating With Linters" doesn't exists

### ISSUE THREAD

**Issue by Haugen** [prettier/prettier#6056]
Reading the documentation, I came across a broken link.

While on the page [Watching For Changes](https://prettier.io/docs/en/watching-files.html), the link to the next page, [Integrating With Linters](https://prettier.io/docs/en/integrating-with-linters.html), leads to a 404. The same is true when trying to use the previous page link on [Ignoring Code](https://prettier.io/docs/en/ignore.html).

**Comment by lydell** [comment]
@prettier/core Anyone knows why this happens?

**Comment by duailibe** [comment]
It's a new doc, looks like I forgot to commit it after I ran the "update docs", to save the versioned docs

Thanks for the report @Haugen
