### ISSUE TITLE
Variable Alignment

### ISSUE THREAD

**Issue by properCase** [prettier/prettier#6058]
I get that Prettier is opinionated.  It makes sense.  However I've always been confused about one of the choices and was wondering if there is a way to configure for it or not.
I like my "continuation variables" to be nicely aligned with their declarator, I find it much easier to read.

However, prettier seems hell-bent on aligning them back to a two-space.
1. Is there a config option I'm missing?
2. If as I suspect option one isn't an option, what is the rational behind _not_ allowing at least an option for the "prettier" format of the variable declarations?

**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
--no-semi
 --jsx-single-quote
 --jsx-bracket-same-line
```

**Input:**
```js
// code snippet
function helloWorld() {
	let varOne = 1,
        varTwo = 2
    
  const immutableOne = "One",
        immutableTwo = 'Two'
  
  if (varOne === 1) { console.info(`${varOne}-${varTwo} :: ${immutableOne}${immutableTwo}`)}
}
helloWorld()
```

**Output:**
```jsx
// code snippet
function helloWorld() {
  let varOne = 1,
    varTwo = 2

  const immutableOne = 'One',
    immutableTwo = 'Two'

  if (varOne === 1) {
    console.info(`${varOne}-${varTwo} :: ${immutableOne}${immutableTwo}`)
  }
}
helloWorld()
```

**Expected behavior:**
```js
function helloWorld() {
  let varOne = 1,
      varTwo = 2

  const immutableOne = 'One',
        immutableTwo = 'Two'

  if (varOne === 1) {
    console.info(`${varOne}-${varTwo} :: ${immutableOne}${immutableTwo}`)
  }
}
helloWorld()
```

**Comment by lydell** [comment]
1. No, there's no option.
2. Why not options? See this slightly out-of-date docs page: https://prettier.io/docs/en/option-philosophy.html

**Comment by mpopv** [comment]
If you want aligned declarations with prettier your only option is put a new `const`/`let` on each line.
