### ISSUE TITLE
JSON without comment should print as `json-stringify`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#6059]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm0gGYQS5I76G4A0G221NtIARgIYBOxpL7IVW9NuFgC8Og5iJAYAvjxAQADjACW0AM7JQbVhADuABTYJ1KZgDcISgCazGrZmADWcGAGV59pVADmyGKwCucBQgABYwALYANgDqIUrwqu5gcC5G8Uqm8QCeyOCq6sGeqnCsMHp2XuHMyHjMkcXBAFaqAB4AQnaOzi7M4XAAMp5wNXUNIM0tLp5ekXAAiv4Q8CP1QSDurMWsuc3QsvKsnjDRVjAhyAAcAAzBBxDF0XbyuQdwW6bDwQCOi-DlCsYQMxVABaKBwOCWSGyVhwH5KWHlZiVapIWqrYLFcJKXwBNaqaazBZLYZo0ZrGDMRgnSxnZAAJmCfmYSki0wAwhBwlVclBoJ8QP5igAVKnGdHFKRSIA)
```sh
--parser json
```

**Input:**
```jsonc
{
  "foo": "foo",
    
      "bar": "bar",
        "baz": "baz"
}
```

**Output:**
```jsonc
{
  "foo": "foo",

  "bar": "bar",
  "baz": "baz"
}

```

**Expected behavior:**
```json
{
  "foo": "foo",
  "bar": "bar",
  "baz": "baz"
}

```

I understand there is `json-stringify` parser, and `json` is designed to parse `jsonc` (I think), but when a JSON file without any comment should tread as a standard JSON file, and remove empty lines.

I don't think this is a bug, but if we do this, the option `json` will be more flexible.

**Comment by lydell** [comment]
Prettier uses the same rules for blank lines in JSON as in all other languages.

**Comment by fisker** [comment]
Should I use `json-stringify` for standard JSON file?  And is this by design?

**Comment by lydell** [comment]
I think so.

**Comment by j-f1** [comment]
The `json-stringify` parser is used for files that are automatically altered, like `package-lock.json`. Why do you want the newlines removed?

**Comment by fisker** [comment]
I accidentally put  a new line in  my  `package.json`, I throught prettier will  remove  it  for me, but it didn't.

so  I  look around to figure why

**Comment by fisker** [comment]
@evilebottnawi I don't want newline, I want prettier remove it for me. not only `package.json`, I want every `.json` file.  I've used `json-stringify`  for a few month,  this works as I expected. But I still hope `json` parser can remove newline for files without comments, so I can use `json` as default parser, not `json-stringify` for `.json`, and `json` for `.jsonc`

**Comment by evilebottnawi** [comment]
@fisker looks you solve problem, can we close issue?

**Comment by fisker** [comment]
I still think we can remove blank lines for standard JSON file

**Comment by evilebottnawi** [comment]
@fisker why? you can switch parser if you need this, default behavior should keep newlines due our philosophy

**Comment by fisker** [comment]
make sense, should document this?

**Comment by evilebottnawi** [comment]
@fisker we already have documentation about changing parser, but i think extra docs is not bad idea

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by lydell** [comment]
@fisker Sorry, I don’t understand what we should document?

**Comment by fisker** [comment]
I mean, we should document how `json` prints, clarify it's not like `json-stringify`, for standrand `JSON` file maybe `json-stringify` is better.

When I first use `json`, I thought, this would print as `json-stringify` does, until I put some blank lines in the file
