### ISSUE TITLE
[html/vue]Weird line break position for custom element / component tag

### ISSUE THREAD

**Issue by Astray-git** [prettier/prettier#6061]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG5lJj4DOLAvMSACQswCeOOADoA7gCc8WLHHFcS5CpQCy-AEIBXGDGiMBMziHh8ujFjQBecQywx4cOUwAFmNMAGtDxmAHkoAYRw3dwAJPCgcKll5bzJ4AA8YVAB6VU1taAUKFNo6BRTMXAI4QhAAGhAILBgaaBZkUDxxcQhRAAUmhHqUPDoIGipykAAjSQ84GABlLDwwGigAc2QYcQ04CoALGAwcAHUNmmMZsDhJrsP6Q-5kcDYh+ZZZGDbJBbtkADN7R4qAKxZ4moxu4JpM8Bg4AAZeZwT7fdYgf7xSbzBZCACKGgg8DhOB+IBm4ke4hudDWQyw4nmMF2AxgG2QAA4AAwVSkQR67SRYG6UuDEuiwioARyx8BeVW6IDwLAAtFA4HAooMKuI4KKaGqXng3nhcfjHhgaMtVgjzIsMWLYUgvniETA8MNaVR6cgAEwVFZ4GhBRb+CAYd4oKDQIUgDSPAAqju6tseAF940A)

[Playground link for normal html element](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG5lj4DOzAvMSACTMwCeOOADoA7gCc8WLHDGcS5CpQBGAVxgxoZftI4gsYmhjxi+nMsxoAvOLuZGcOMwAEmNMAGtd8XgHkoAYRw3dwAJPCgcKhk5bxgtOAAPGFQAelV1aHkKVNo6eVTMXAI4QhAAGhAILBgaaGZkUGMxCBEABWMEepQ8OggaKnKQJQkPOBgAZSw8MBooAHNkGDEVOAqACxgMHAB1NZpvKbA4cc79+n2+ZHBWQdnmGRhWiTmjZAAzPBx7ioArZgSAEIjdxjcZ4DBwAAyszg70+3xAfwS41mc0EAEUVBB4HCvqs9MZ7mIrnQVoN9LMYNt+jA1sgABwABgq+gg922EiwV30cCJdFhFQAjlj4E8ql0QHhmABaKBwOBRAYVMRwYU0FVPPAvPC4hH3DA0RbLfEWeYYkWwpAfPEVGB4JTUqi05AAJltEhoQXm-ggGFeKCg0AFIBU9wAKvautb7gBfGNAA)

```sh
--parser vue
```

**Input:**
```vue
<template>
  <div :class="$style.wrapper">
    <MyButton :type="test" :size="small" @click="testOnClickHanlder">test text</MyButton>
  </div>
</template>
```

**Output:**
```vue
<template>
  <div :class="$style.wrapper">
    <MyButton :type="test" :size="small" @click="testOnClickHanlder"
      >test text</MyButton
    >
  </div>
</template>

```

**Expected behavior:**
```vue
<template>
  <div :class="$style.wrapper">
    <MyButton :type="test" :size="small" @click="testOnClickHanlder">
      test text
    </MyButton>
  </div>
</template>

```

**Comment by lydell** [comment]
Hi! It sounds like you're looking for the [html-whitespace-sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option.

**Comment by Astray-git** [comment]
Thanks! Is it possible providing additional options to the parser to somehow "register" custom block element? So I don't have to use magic comments every time.

**Comment by rndmerle** [comment]
Any particular reason that this form has been chosen:
```
<MyButton :type="test" :size="small" @click="testOnClickHanlder"
  >test text</MyButton
>
```
over this one ?
```
<MyButton :type="test" :size="small" @click="testOnClickHanlder"
>test text</MyButton>
```
------
or likewise this:
```
<MyButton :type="test" :size="small" @click="testOnClickHanlder"
  >test text</MyButton
>
```
over this one ?
```
<MyButton
  :type="test"
  :size="small"
  @click="testOnClickHanlder"
  >test text</MyButton
>
```
over this one:
```
<MyButton
  :type="test"
  :size="small"
  @click="testOnClickHanlder"
>test text</MyButton>
```

**Comment by meteorlxy** [comment]
[eslint-plugin-prettier-vue](https://github.com/meteorlxy/eslint-plugin-prettier-vue) could be a possible solution :wink:

![eslint-plugin-prettier-vue](https://user-images.githubusercontent.com/18205362/62407420-f80bac00-b5ea-11e9-8cd9-77e2e55cb16c.gif)

**Comment by thorn0** [comment]
The original question has been answered (`--html-whitespace-sensitivity` is the answer).

@Astray-git If you still have questions, please open a new issue.

@rndmerle see https://github.com/prettier/prettier/issues/7153
