### ISSUE TITLE
1.17.0 release formats scss in a breaking manner

### ISSUE THREAD

**Issue by vidarc** [prettier/prettier#6062]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
```scss
div {
  font-weight: #{someFunction('light')};
}
```

**Output:**
```jsx
div {
  font-weight: #{somefunction('light')};
}
```

**Expected behavior:**
```scss
div {
  font-weight: #{someFunction('light')};
}
```

this works as expected with version 1.16.4

**Comment by evilebottnawi** [comment]
Can't reproduce https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATAlgNwATADpTbYBm0MAtAO5zoDmAFjEtgMTADOEAtnAGICuUMDHTQAFAHIANnUYSAlAF8A3AUUgANCAgAHEdHbJQAQwBOpiJQAKZhIZTHMEdKk0gARqeNgA1nBgAyjre6FC0yDCm-HBajFxSAOr06PDswWBwAXYpWCkAnsjg7IZaoexwpjBWXrRcxsjExlLlWgBW7AAeAEJevv4BxjwAMqFwDU0tIO0dAaG0UnAAivwQ8OPNMSDBpuWmhexgxW46pqEwCS4w9MgAHAAMWicQ5QleOoUncLuYY1qmcABHfjof7VYy1epIRobLTlLjoCJRTbsOYLZarMZQiabGDGdwXVBXZAAJi0kWM6BkYQAwtw6oUoNBfiB+OUACp4+zQ8qKRRAA

**Comment by evilebottnawi** [comment]
Can you provide minimum reproducible test repo? thanks

**Comment by vidarc** [comment]
seems to actually be due to prettier-stylelint. unchecking the `use prettier-stylelint instead of prettier` option in vscode fixes the issue for me. 

these are my stylelint rules:
```json
{
  "extends": [
    "stylelint-config-prettier"
  ],
  "rules": {
    "number-leading-zero": null,
    "rule-empty-line-before": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-block-no-shorthand-property-overrides": null,
    "selector-type-no-unknown": [
      true,
      {
        ignoreTypes: ["/^ods-/", "/^cx-/"]
      }
    ]
  }
}
```

**Comment by evilebottnawi** [comment]
@vidarc looks somethign wrong on stylelint side, somebody can create minimum reproducible test repo?
