### ISSUE TITLE
YAML support for shared configurations

### ISSUE THREAD

**Issue by astorije** [prettier/prettier#6066]
**Environments:**
- Prettier Version: 1.17.0
- Running Prettier via: CLI
- Runtime: N/A
- Operating System: N/A

**Steps to reproduce:**

Have a Prettier configuration file in YAML in a shared package (say `@company/prettier-config`. In its `package.json`, expose it with:

```json
"main": "my-shared-config.yml",
```

**Expected behavior:**

Context: Shared configurations have been introduced by https://github.com/prettier/prettier/pull/5963 and explained at https://prettier.io/blog/2019/04/12/1.17.0.html#config.

Ideally, exporting a shared configuration would support all of the config formats Prettier supports: JSON, JS, YAML.

**Actual behavior:**

When extending the config in a consuming project through a `.prettierrc.yml` file that just contains `'@company/prettier-config'`, and running Prettier, I get the following:

```
[error] Invalid configuration file: Invalid or unexpected token
```

Exporting that same shared configuration in JSON or JS does work fine however.

**Comment by j-f1** [comment]
Why not use JS instead?

**Comment by astorije** [comment]
That's what we're doing at the moment (JS), but we would prefer to use YAML for all our Prettier configurations (shared and overrides at consumer level) as it's our preferred configuration format.
Since YAML is a supported config format, it would be really neat if that applied to shared configs as well!

**Comment by azz** [comment]
You could have an `index.js` that just loads `prettier.yml` with [`js-yaml`](https://github.com/nodeca/js-yaml). I've done that before.

**Comment by j-f1** [comment]
Sounds like a good workaround.
