### ISSUE TITLE
Prettier does not infer the right parser for Angular HTML files

### ISSUE THREAD

**Issue by imaka** [prettier/prettier#6071]
Prettier Version: 1.17

When running:
```zsh
> prettier *.component.html
```
it returns an error related to Angular specifics, such as *ngIf, but works fine when running:
```zsh
> prettier *.component.html --parser angular
```

**Expected behavior**
According to the [1.15 release notes](https://prettier.io/blog/2018/11/07/1.15.0.html), it should infer the right parser for *.component.hml files

**Comment by Gimly** [comment]
I have the same issue with Prettier 1.19.1

**Comment by thorn0** [comment]
Tested this and it worked even with 1.17.  Sounds like the OP had `"parser": "babel"` in his Prettier config.

**Comment by imaka** [comment]
@thorn0 parser is set to typescript:
<img width="675" alt="Screenshot 2020-03-05 at 09 51 10" src="https://user-images.githubusercontent.com/6725573/75969546-01cdf880-5ec7-11ea-931e-3ebadd511117.png">

**Comment by imaka** [comment]
`~/Workspace/Personal/Textual-Studio/src/app/pages/page master*
❯ prettier -v
1.17.0

~/Workspace/Personal/Textual-Studio/src/app/pages/page master*
❯ prettier page.component.html
page.component.html[error] page.component.html: SyntaxError: Identifier expected. (1:15)
[error] > 1 | <ng-container *ngIf="page">
[error]     |               ^
[error]   2 |   <ng-container *ngIf="page.showBanner">
[error]   3 |     <section class="hero is-medium" [ngStyle]="setBackground()">
[error]   4 |       <div class="hero-body">

~/Workspace/Personal/Textual-Studio/src/app/pages/page master*
❯ cat ../../../../prettier.config.js
module.exports = {
  printWidth: 140,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  trailingComma: "none", // other options `es5` or `all`
  bracketSpacing: true,
  arrowParens: "avoid", // other option 'always'
  parser: "typescript"
};`

**Comment by thorn0** [comment]
`parser` in the config overrides the inference.

**Comment by imaka** [comment]
Thanks @thorn0 !
