### ISSUE TITLE
don't break object literals with long strings

### ISSUE THREAD

**Issue by ianstormtaylor** [prettier/prettier#6072]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBRASrgeVwH0CA1PXASQBFsBlTAXk2AB0pNMBDAVxgAWCGAEsw3UdGIAnOAEdeI2QBMkmAOQAFADZxuaOJmFxpmAJ4RepuAFtuI7TyjLMAB31oA7hGnKAdOoANBxcfILCYhIiUiJQAG7c2iKqGgAqQjz8QrCRkpwWvG7SEHHJcC4iaJixCUn+QSGYkNq6YHnEUNw2cDLyiipqWrr6hsam3E0QLXBt0Zyd3QHBnJPTs1Jo2rwA5r0KSuWDOnoGTQIQEKcTza15mJs7S43wXcS29trENYnJR8OnYx4mFqySMdgcPGUylkaDQTxWLxsb3Bn1k+wGGmOIyMsBMQMRYI+kOhcFh8K4iI6XR6aP6h0x-0MYHOl0MEwJCzg5MwlIeu2+dUGAE1LKYCbwDNJOU1uJxoNozJNYPZOIlXAJZbxutIxGduNJuG0TFVZS5lPohHCGgi9Ei+Xs6SkhicmSyrjzbZgJSZOdzvdJkR8vvEfk6sQDceNgaHCRDuFCYVbllx-YGHG8AB6VGBoQYAQS9kswnhEgh5Gqw7zjCdJJu0snjirgWYwaEC5ksmBsIm2AiwnllWBgEEw2gg22qnFiGD09WThZMadRfQOYcZOPgpgK1hRxMTfslVO6DtXfxdG7x28wvutKcPUAgMGIADNLM5BgB1JmWbQuB9YZ9YhcCZ-WLUsBHLCRY0ceMSTJTB6B7TheFcScZ3jAB+W8FwDdxYW8Xxg0gaRZDaQZ0igvCvB8FwByqWJiNImAD0XKiCOUYMQSdEUrDcDx2K7CUsAAI0MMcoG2PFBFlTAAA49QNI1pCTRpUzYmiTwxZ1sWZC53XU3wWIDe0BV+DQeNMf1pXEOUoAVJUYBVHhtHVTVtV1Zl9UNTcTWcTBzTQS0jOIe1m2zXMNALUCSzLaSsCs6lnIbZQmxbHN2wKLsez7YtBx5EcxwnWI0JeOdVMPe1aVPBlz101kgQSxZrQAXxAQIQAgVw8jQZBQH1YpPE0fUEB6lBuDiCBkjakBhMUgBrOAYHodwwFibZkBgaReDgdq+xsbQPwEUtSRWuB6BG0sRFKGAzGQcBYWm6cTBgTQDW2OxkGfRIDHagArNAMwAIXmxb6GpAAZWI4E+76dpAf6M0QiTdAARV4R9oaQL7tB+kB3GUkw7uE7hhLMcTptcHVYA-ZJBGQWSAAZ2sp1kPwNVw7sp0kTDiaH2oUDHXs60aQH0ABaKA4HKcppqq2RXu4d7uBhnG4YMbsNq2tW1tR9H4BV3HHOEmnlDppAACZ2s2j41oAYQgGwPpQB9Jem71UhJ0bsYMZrmqAA)
```sh
--parser babylon
```

**Input:**
```jsx
const ERRORS = {
  team_email_invalid: 'Please enter a valid email address.',
  team_email_required: 'Please enter a team email address.',
  team_name_required: 'Please choose a team name.',
  team_slug_invalid: 'Your team username can only contain alphanumeric characters and dashes.',
  team_slug_required: 'Please choose a team username.',
  user_email_invalid: 'Please enter a valid email address.',
  user_email_exists: 'A user with that email address already exists, you might want to log in instead.',
  user_email_required: 'Please enter your email address.',
  user_name_required: 'Please enter your name.',
  user_not_found: 'We could not find a user with that email address. Sign up instead?',
  user_password_incorrect: 'That password was incorrect.',
  user_password_invalid: 'Your password must be longer than 8 characters.',
  user_password_required: 'Please choose a password.',
  user_slug_invalid: 'Your username can only contain alphanumeric characters and dashes.',
  user_slug_exists: 'A user with that username already exists, you might want to log in instead.',
  user_slug_required: 'Please choose a username.',
}
```

**Output:**
```jsx
const ERRORS = {
  team_email_invalid: "Please enter a valid email address.",
  team_email_required: "Please enter a team email address.",
  team_name_required: "Please choose a team name.",
  team_slug_invalid:
    "Your team username can only contain alphanumeric characters and dashes.",
  team_slug_required: "Please choose a team username.",
  user_email_invalid: "Please enter a valid email address.",
  user_email_exists:
    "A user with that email address already exists, you might want to log in instead.",
  user_email_required: "Please enter your email address.",
  user_name_required: "Please enter your name.",
  user_not_found:
    "We could not find a user with that email address. Sign up instead?",
  user_password_incorrect: "That password was incorrect.",
  user_password_invalid: "Your password must be longer than 8 characters.",
  user_password_required: "Please choose a password.",
  user_slug_invalid:
    "Your username can only contain alphanumeric characters and dashes.",
  user_slug_exists:
    "A user with that username already exists, you might want to log in instead.",
  user_slug_required: "Please choose a username."
};

```

**Expected behavior:**

Don't break the object literals keys and values up into separate lines when it's only an object full of longer strings. This was previously brought up in https://github.com/prettier/prettier/issues/2079, but the example given didn't make the failure case clear. (cc @kentcdodds)

As you can see, when you're creating mappings of keys to longer strings, some of the strings happen to be less than 80 columns, and some of them don't. By wrapping only the longer ones, Prettier makes is **much, much** harder to actually read through the keys of the objects. because you can't just scan down the list anymore.

The benefits of the wrapping are marginal, and ugly regardless. But the downsides for cases like this are big because legibility goes out the window.

**Comment by kentcdodds** [comment]
Personally, I'd just stick a `// prettier-ignore` above that and not worry about it 🤷‍♂️

**Comment by kentcdodds** [comment]
[Like so](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSkigGcYMBRAJQ4HkOB9bgDVOHAJIARNgGUMAXgzB6GDAEMArjAAWCImBVFofPAEc1hPABMkGAOQAFADZwVTOBh0kMATwhqc7gFsVQgdVKAtsFyYAdxoLADobABolVQ1tWEI9Ayg+QigANxUHQitbABVtNK0dLP1CaG9fbBwIAtK4CMImDHyikoTk1MgHJzAcvigVALgjOFNzTut7Jxc3D38VDBGxnIwpmcSUqGUduHGG3KYHNQo5hctlx2dXbc0ICFets4vG69ujql4NM+HAgiE8oViqUnqtXhtVBh+qVAsFQioLBY8EwmICThhgQFQeCHPczI9bM81u5YJ4toTUSFVJjsbihvjCZNprMTOSlpS4W4wO9Pm56c4AvtuXjlJz-nc+tCyjYAJq+fwMtSuHAHIUqE7QBxebbQGDBE7FLCafVqGY4LJvFQ4FTjEg9fURCwubRs46yiV8eVkxbKqmvYUfL4EiUYLUkXUy2Pa4loyHI0OCmnwTZIpWM9EsuA4xNxnApiFwAAe3RgTGWAEEk55ooQtATrawwWjmVii+6HHgMcaqzWmEkmmoMAFKJpWNF9awYBAMA4IBReid8ixnIM-U2y12IbyQ7CXutaf4fH58z3WSXk7rgxSVmes54r-4E+zlKXJhAYHwABmvjhMsADqQq+A4ETUKwgH5BEWylhgLZtlo+g3hivbFhgUiUCcahYBu24YgA-N++58FgUSxDgFiQpAOB4OMyyVBh1E4rRETzj0+SMcxMD3iQVE0XEaZKssarXhxMRxFOWqsAARm4q5QBQnjoScAAcjrOq6OC+qkv4yVxT78i+1IRqKiImXEQllkGioDJJ6r7rq2z6hghrGowZr5KoDhWjadoOsKToutm7rhBgXpMD69mBjcdwjiwda2I2yGoZo7YYaW7nFIOFjDtWqXjleU4znOC4Esuq7rv5W7AruRnJkGx7PmGQoilGeXSuyAC+IBJCAEBYDkTDIKATqtNEdhOggE0oCoBQQKUQ0gIpekANb4FI1FgPkFDIDAOBqHAw2zgEDhgZorZFvtcBSAtraEO0MBeMg4A4utW4kDAdjOhQQTIIBxSuMNABWTCVgAQttu3cgAMvkcAg2D50gFDlZ4WpTgAIpqP+qNIKDDjgyA1EGSQn2KSoileKp624PkMBgaUWjIFpAAMw24KKYHOlgn24EWJAFKjw2mETAOjYtIAuKQUBwJ0nTre1cAAyoQMqGjZMY6407Had+uHfjhPwLr5NmopbMWBzSAAEzDSdaKHQAwhAATAyg1BK+tcblHTi2k64-X9UAA)

**Comment by ianstormtaylor** [comment]
@kentcdodds I did not know that was even possible, thanks!
