### ISSUE TITLE
Support for custom babel plugin 'jsx-dom-expressions'

### ISSUE THREAD

**Issue by r0skar** [prettier/prettier#6073]
I know this probably way too specific, but I figured why not ask. I am using [babel-plugin-jsx-dom-expressions](https://github.com/ryansolid/babel-plugin-jsx-dom-expressions). The plugin enables the usage of dynamic expressions inside JSX when they are **wrapped in parentheses**. Unfortunately, prettier is removing them as "unneeded".

**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D5gAU6AhjMQHQDOATmAJQC+qA9FniADQgQAOMm0SslDFq1CAHcACqIRCUxbBEzpOIAEbViYANZwYAZR7bMUAObIY1AK5wuACxgBbADYB1e5niVjYOAbkvHC8AT2RwSiEuU0o4ahgpLTMnYmQAM2IXWK4AK0oADwAhLV19A2InOAAZUzh0zOyQPPyDUzMXOABFawh4eqy7EGNqWOpw9WJ1OBc1HmpTGDcVGHtkAA4ABi45iFi3LR5wubhR7DquAEce+ETeeRBiSgBaKDg4dHe1ajgrzG-E4jJVJIDIDLixJyYSw2QaUNodbq9OoghqDMjqJboFbIABMXCsxEwLjaAGEIE4UuEoNBziBrLEACqTeSg2IMBhAA)
```sh
--parser babel
```

**Input:**
```jsx
<div>{(data.src)}</div>
```

**Output:**
```jsx
<div>{data.src}</div>;

```

**Expected behavior:**
```jsx
<div>{(data.src)}</div>;
```

**Comment by JounQin** [comment]
+1 for custom babel config/plugins.

I'm using a custom babel preset [babel-preset-proposal-typescript](https://github.com/JounQin/babel-preset-proposal-typescript) which transforms proposals which are current in stage 0-2, it works fine with eslint.

But `prettier` doesn't support custom babel config, so it will emit parsing error from `@babel/parser` if any TypeScript feature is used.

@j-f1 Should I add another issue for discussion?

**Comment by thorn0** [comment]
That convention with parens was abandoned:
https://github.com/ryansolid/babel-plugin-jsx-dom-expressions/issues/35
