### ISSUE TITLE
Add space after GraphQL objects/enums/etc (eol)

### ISSUE THREAD

**Issue by iamclaytonray** [prettier/prettier#6075]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAyhAWzhgAsBLKAc22AB0ptsyATJbASQBEBCegX2wBibAGcMAQzA4RJCAFcANs2wAnYnJUNxAM3grspMiProseQsXJUAogpE46DJqw49+IADQgIGGGWgiyKDiKioQAO4ACiEIgSjiAG4QLJ4gAEYqkgDWxLgSYBSUyDAqcnBeJDAECgDq5PBiknC4sWR+CW1oyOAigV4U9iowkZmUBOLI2uJ25SAAViIAHgBCmWA5MLjiRAAyFHCT0-ZeC4u4hQpwAIpyEPCHM14SKoPdlJkYJACOCqkYKhQYDUWKRkAAOAAMTzC9hqH26-zggwSBy8ai+cjIahG4jGEyQU0eIHsBDIxVKsxEF2ut3uBKOsxg4jSwOYoKQACYvCVxGQFIUAMKEcbdKDQVEgOT2AAqzLihPsfD4QA)
```sh
--parser graphql
```

**Input:**
```graphql
type Something {
  id: ID!
}
type SomethingElse {
  id: ID!
}
```

**Output:**
```graphql
type Something {
  id: ID!
}
type SomethingElse {
  id: ID!
}

```

**Expected behavior:**
A space should be added right after the end of the first object type in this example, but would be applicable to any GraphQL construct (enum, input, etc).

```graphql
type Something {
  id: ID!
}

type SomethingElse {
  id: ID!
}
```

**Comment by lydell** [comment]
So far, we're using the same blank line rules for all languages: https://prettier.io/docs/en/rationale.html#empty-lines

This would probably be part of the proposed `--pure` flag: #2068 / #4685

**Comment by iamclaytonray** [comment]
Ahh, okay. Should I go ahead and close this issue then?

**Comment by evilebottnawi** [comment]
@iamclaytonray yes, it is expected
