### ISSUE TITLE
TypeScript: parentheses around function invocation with non-null assertion removed incorrectly

### ISSUE THREAD

**Issue by vkrol** [prettier/prettier#6076]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEU4HcAEAKA5nGAYRggCcB5UgOQFcAbO7ASgEInmBuEAGhAgAcYAS2gBnZKACGpUhHQAFaQnEpJANwhCAJjxAAjUpLABrAgGV+RoVFzIYpGnF4ALGAFs6AdWdD4oy2BwZsq+Qmq+AJ7I4KLivNaicKQw8oa4bpLIAGaSdIm8AFaiAB4AQoYm5pJucAAy1nDZufkgRcVm1rh0cACKNBDwTXlOIJakiaTRMBH8cKJgpEKCuvyLsJ7aMM7IAJwADLyrEImehvzRq3NJao28pHAAjjRC96mS6ZlIOcO8iW5CdgcI1EnW6fQGjS+zRGMEkeg2Wi2yAATLx7JIhHROoQIG4MtEoNBbiAaIkACpwlTfRIAXxpQA)
```sh
# Options (if any):
--parser typescript
```

**Input:**
```ts
declare function getCtorOrNull(): { new (): any } | null;

new (getCtorOrNull()!)();
```

**Output:**
```ts
declare function getCtorOrNull(): { new (): any } | null;

new getCtorOrNull()!();
```

The output is the invalid TS code. Proof: https://www.typescriptlang.org/play/index.html#src=declare%20function%20getCtorOrNull()%3A%20%7B%20new%20()%3A%20any%20%7D%20%7C%20null%3B%0D%0A%0D%0Anew%20getCtorOrNull()!()%3B%0D%0A%0D%0Anew%20(getCtorOrNull()!)()%3B%0D%0A

**Expected behavior:**
```ts
declare function getCtorOrNull(): { new (): any } | null;

new (getCtorOrNull()!)();
```

**Comment by evilebottnawi** [comment]
Thank for issue, looks like a bug
