### ISSUE TITLE
[Glimmer] Self-closing void elements

### ISSUE THREAD

**Issue by patocallaghan** [prettier/prettier#6079]
This is more a discussion rather than a bug.

Am I wrong in thinking that the glimmer parser will be primarily used in Ember  apps? If so, the behaviour of self-closing void elements is currently at odds with the [Ember community template styleguide](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/self-closing-void-elements.md)

> ### self-closing-void-elements
> HTML has no self-closing tags. The HTML5 parser will ignore self-closing tag in the case of void elements (tags that shouldn't have a "closing tag"). Although the parser will ignore it, it's unnecessary and can lead to confusion with SVG/XML code.

> This rule forbids the following:

> `<img src="http://emberjs.com/images/ember-logo.svg" alt="ember" />`
> `<hr/>`

> This rule allows the following:

> `<img src="http://emberjs.com/images/ember-logo.svg" alt="ember">`
> `<hr>`

I know the behaviour in the HTML parser is to opt for self-closing void elements (see long discussion in https://github.com/prettier/prettier/issues/5246) but as the audience of this parser is narrower in scope, i.e. Ember users, should we not do that here to mirror the community styleguide?

I came across this issue as we're currently trying to migrate our app to use Ember's new Angle Bracket syntax using [ember-angle-brackets-codemod](https://github.com/rajasegar/ember-angle-brackets-codemod) and this uses the Prettier formatter under the hood.

**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAllADgVxgAgDcBDAGxzgF5hh4APGAX0YD4QAaECLGdaAZ2ShiAJxEQA7gAVRCQSmKEI6ACYcQAIxHEwAazgwAylh2YA5shgiKnABYwAtqQDqt9PH4mwcQ3PfpCdwBPZHB+QU5MfjgRGCltMwdiZAAzMmjOACt+OgAhbT0DQ2IHOAAZTDhU9LgsnMNzUjgARRwIeGrSDJATEWiRULNSdAdSgc4sEUwYZ1UYW2QADgAGCfFo520sUMm4fsIqzgBHNvh47nkQYn4AWig4OBVH9RE4E-RX+OJE5KQ0rtqIGiDnQlmsgP4jRapyqfxqnBgxA0sxU82QACYEdp0MMoGYAMIQUa-EBQaCHEA4aIAFSR8n+0WYQA)
```sh
--parser glimmer
```

**Input:**
```hbs
<input value={{text}}>
```

**Output:**
```hbs
<input value={{text}} />
```

**Expected behavior:**
```hbs
<input value={{text}}>
```

**Comment by duailibe** [comment]
Hi! Sorry that this took a while to get a response.

It's really unfortunate that the Ember community took this decision, we really think it's better to just use self-closing tags, than having to think if it needs a self-closing tag or not; and I personally think there's a benefit for Prettier to print similarly both Ember, JSX, Angular and HTML (when possible).

> it's unnecessary and can lead to confusion with SVG/XML code.

Yes, it's unnecessary but I don't see the confusion it can lead.

FTR we don't necessarily cater to guidelines or lint rules, but we'd like to welcome everyone to use Prettier. So I don't oppose to this, but I'd like to see if we have other options without changing this.

**Comment by GavinJoyce** [comment]
@duailibe I added a comment to https://github.com/ember-template-lint/ember-template-lint/issues/691#issuecomment-499120663, it would be good if we could find consensus between `ember-template-lint` and `prettier`

**Comment by GavinJoyce** [comment]
@duailibe thinking about this a little more, I think we should accept the differences between Ember, JSX and others on this rule. `ember-template-lint`'s default rules are Ember's defaults and I think we should align prettier's rules for hbs templates to Ember's defaults. If we don't, it'll make adoption difficult as adopting prettier for hbs will mean straying from ember's conventions.

I'm keen to work on making prettier's hbs formatting high quality and have complete support, having alignment will make that challenge much easier.

What do you think?

**Comment by duailibe** [comment]
@GavinJoyce I think I'd like to understand better if that's really a convention or just a coincidence that this rule is on by default on the linter. I think that's more the latter.

**Comment by GavinJoyce** [comment]
👍 since my last comment, rwjblue has indicated that he'd be open to [modifying the default rule](https://github.com/ember-template-lint/ember-template-lint/issues/691#issuecomment-499248336) to simply assert that no end tag or children exist. That would mean that the default would support `<br />`. 

I'm going to close https://github.com/prettier/prettier/pull/6179 and I'll see if I can land the changes in `ember-template-lint` so that it and `prettier` are in sync

**Comment by thorn0** [comment]
The `self-closing-void-elements` rule has been removed from `ember-template-lint` (https://github.com/ember-template-lint/ember-template-lint/pull/899).
