### ISSUE TITLE
support dot pattern for CLI

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#6085]
**Environments:**
- Prettier Version: 1.17.0
- Running Prettier via: CLI
- Runtime: Node.js
- Operating System: no matter

**Steps to reproduce:**

```shell
node_modules/.bin/prettier . --write
```

**Expected behavior:**

Format all supported files.

**Actual behavior:**

output:
```
[error] No matching files. Patterns tried: . !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```

**Additional info:**

All popular linters (like `stylelint` and `eslint`) support `.` pattern. I think we should do same. I don't want have list of globs. It is good for DX and 0CJS configuration.

/cc @prettier/core What do you think? I can take care about this and send a PR.

**Comment by lydell** [comment]
Sounds reasonable. I think we have an (open?) issue (or PR?) about this (or something similar) as well

**Comment by evilebottnawi** [comment]
WIP

**Comment by evilebottnawi** [comment]
Looks globby already support this behavior by default, we need update globby

**Comment by lydell** [comment]
Here's some interesting PRs/issues:

- #5053
- #4715
- #5813
- #1844

**Comment by evilebottnawi** [comment]
Okey, we can update globby to `7.1.1`. Features:
- expend directories (`prettier src --write`)
- dot rule (`prettier . --write`)

**Comment by fregante** [comment]
Is this supported or not? The site mentions it:

https://prettier.io/docs/en/install.html

```sh
npx prettier@2.0.4 . --write
``

https://prettier.io/docs/en/cli.html

```sh
prettier --write .
```

But I get this

```sh
❯ npx prettier .
[error] No matching files. Patterns tried: . !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```

**Comment by evilebottnawi** [comment]
@fregante update prettier to latest version, it is supported only for `2` version
