### ISSUE TITLE
prettier-eslint in vscode remove newline of EOF when auto formating after saving a file

### ISSUE THREAD

**Issue by aflext** [prettier/prettier#6090]
So, how do i disable prettier for adding newline at EOF when vscode auto formats after saving a file?
I hope like this:
```js
"prettier.tabWidth": 4,
"prettier.singleQuote": true,
"prettier.arrowParens": "always"
// this is my hope
"prettier.disableNewLineEOF": "always"
```

**Comment by lydell** [comment]
Hi! Prettier ends all files with a newline, and there's no option for it. It might be that the vscode plugin has something for this, but then you're better off asking in the https://github.com/prettier/prettier-vscode repo.
