### ISSUE TITLE
Export `doc.utils.findInDoc`

### ISSUE THREAD

**Issue by rattrayalex-stripe** [prettier/prettier#6095]
https://github.com/prettier/prettier/blob/master/src/doc/doc-utils.js#L75 
is not exported: 
https://github.com/prettier/prettier/blob/master/src/doc/doc-utils.js#L208-L217

I would like to use it. Any hesitations about exporting? Happy to put up a PR if not.

**Comment by evilebottnawi** [comment]
PR welcome :+1:
