### ISSUE TITLE
Weird Formatting in HTML code

### ISSUE THREAD

**Issue by HaoyangFan** [prettier/prettier#6096]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zU535bcAhgBNOPUbxpwY-cmEr8ATgGdJAXiYgAqvgBiAWgAc68gHoRY7qglSqMGAAddcAI4BXAJYA3NSAAaujQCCurgQNHb8MG4ARnRwRpCwCDDeAJKkKnCCAOZwADSy8qFwKgCMRqYs5hZW0lD8Et4ebnAA7nYQ8jDx0PCw3i1ugjCUKoJwTWBwugNDlLluUG6R-HS6imArxWUgJmbmqJEwsQyHsajGp3B7YpaStfXF6vwuwx3diX3qdRLl16K31m+jxAY3W8jcdki0HevWS6lBYHBkLc0CocHkcR2FS4VQB9wa6gA1nAAJ4tDqCRQwpLeYlkimKXKUdGY3aVHjnZlCTjsixRCCCEl-Dl2YXmfCUNyKGz0cjEuB2cgweT8MCE6UQABm5EUMBcgvIWt5VQs0koGM13mo9kUSGMxjGHjgdAgdnRADoaBAAF5uOh0fjujpZYwIfwAZQdEDAimMABkBPIoMYABL4ACyceMKVghUELjAUKgAH0YBBi2nM8YJXBi1zBMWaoIIvxiwsKxm40YpPIcnCQMWYvwoIT1AwUwJBORSLEJLBzvwxWIFuRK12cftjKLjed+YLOJzaIwWCBciBXUXFMhQApCi1iAoEFeUPwPBBBqeQFEVWrJOHwmACxZMgyouHkIDsHQADqkrwIoAFwOGT5LJ4Swksg4CKFeZ4LMonTECqWQ0PwyCaisyhngAVooAAeABCP7EjA4YPHGCxwKR5HgdRNHhkBsQAIouBA8CcXQFEgOESjohhkGfnY4KwFBgzDMg+gAAxngpEDKFBKp2BhClwHhTqfq4IlwARrrPiA-CKLoUBwJkmSfhirhuBiBH8ERJFIGR4ngcoNBuCB8hgWeij8XAQkWWJElSFEymzMgABMZ7KvwfpASENDERhUDQBxZ4uMo+D8FEz7+coAC+1VAA)

**Input:**
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>title</title>
        <meta name="author" content="name" />
        <meta name="description" content="description here" />
        <meta name="keywords" content="keywords,here" />
    </head>

    <body>
        <p>
            This html keep tracks of study of
            <a href="https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML" target="_blank">Head Element</a>
            in HTML
        </p>
    </body>
</html>
```

**Output:**
```jsx
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>title</title>
    <meta name="author" content="name" />
    <meta name="description" content="description here" />
    <meta name="keywords" content="keywords,here" />
  </head>

  <body>
    <p>
      This html keep tracks of study of
      <a
        href="https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML"
        target="_blank"
        >Head Element</a
      >
      in HTML
    </p>
  </body>
</html>

```

**Expected behavior:**
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>title</title>
        <meta name="author" content="name" />
        <meta name="description" content="description here" />
        <meta name="keywords" content="keywords,here" />
    </head>

    <body>
        <p>
            This html keep tracks of study of
            <a href="https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML" target="_blank">Head Element</a>
            in HTML
        </p>
    </body>
</html>
```

Hi, the formatting of anchor looks super weird. I don't understand why anchor is formatted in this way (looks ugly to me)
```html
      <a
        href="https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML"
        target="_blank"
        >Head Element</a
      >
```

Any help? Thanks

**Comment by lydell** [comment]
Hi! You’re looking for the [HTML whitespace sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option. See also [whitespace-sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting).

**Comment by HaoyangFan** [comment]
Hi @lydell Thanks for your prompt response. I am using VSCode's prettier plugin and after setting the option `prettier.htmlWhitespaceSensitivity` to be `ignore`, the above HTML code now becomes
```html
<a
      href="https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML"
      target="_blank"
>
      Head Element
</a>
```
Is this the intended behavior for ignoring whitespaces (aka. consider them as insensitive)?

**Comment by lydell** [comment]
Yes, that looks correct to me. Isn’t that what you were looking for?

**Comment by HaoyangFan** [comment]
Yes, that's exactly what I'm looking for 🎉. Thanks for the help ❤️
