### ISSUE TITLE
Adding return type annotation to callback suddenly breaks call into multiple lines

### ISSUE THREAD

**Issue by Tetraib** [prettier/prettier#6099]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDADugdAczjACgB0QB6EgGgAICAnOAR2voGcBKJKgNwgEsATKgF4AfFWBEoVKqywsE-YiAAScADZqIVAOoRaa-gEISbANySAvmckgKICOhi9oLZKFS1aEAO4AFDwiuKKg8ArYgAEa0qGAA1vgAyugxvFA4yDC0AK5wdgAWMAC2atp5vPAsyWBwCYHlvFzlAJ7I4CyudqnytDC+0TiFqMgAZqhq8nYAViwAHgBC0XGJqIVwADKpcCNjEyDTMwmpOGpwAIpZEPDb47kgybTdrTBN6HAsYLS8juHon7DaAhgeWQAA4AAx2X4QeTaaLoVq-N5wWhcLZ2BgXeB9BxBNAsAC0UDgcH4JPC9AxvHofVQAyGSFGNzs8kKvAy2VuLCOJ3Oly2DJ2txgqAiAP4QOQACY7JlULw1EcAMIQQqDVpQaBokBZeQAFRFQUZ8gsFiAA)
```sh
--parser typescript
```

**Input:**
```tsx
app.get("/", (req, res): void => {
  res.send("Hello World!");
});

```

**Output:**
```tsx
app.get(
  "/",
  (req, res): void => {
    res.send("Hello World!");
  }
);

```

**Expected behavior:**
```tsx
app.get("/", (req, res): void => {
  res.send("Hello World!");
});

```
As soon as you try to type the returned value for the function with ": void" it incorrectly breaks the function in multiple lines.

**Comment by brainkim** [comment]
@Tetraib @lydell I have a quickfix PR here: #6106. This issue is caused by a change introduced with this PR: #4228.
