### ISSUE TITLE
Prettier still fails for unsupported files

### ISSUE THREAD

**Issue by commscheck** [prettier/prettier#6101]
When I run `prettier --write "./**/*"` I get errors for unsupported files:
```
[error] No parser could be inferred for file: static/placeholder.txt
```

I assumed from the conversation in https://github.com/prettier/prettier/issues/2884 that this is no longer the expected behaviour, and that unsupported filetypes would be skipped.

Is there a way I can achieve this behaviour without explicitly listing the filetypes I want pretty-fied, or explicitly excluding unsupported filetypes in `.prettierignore`?

**Environments:**
- Prettier Version: 1.17.0
- Running Prettier via: Node.js API
- Runtime: Node.js v12.1.0, npm v6.9.0
- Operating System: macOS

**Full output:**
```
-> % npm run prettier:all

> cash-tracker@1.0.0 prettier:all /Users/ben/src/cash-tracker/backend
> prettier --write "./**/*"

[error] No parser could be inferred for file: .prettierignore
.vscode/settings.json 25ms
package.json 9ms
README.md 21ms
src/main.ts 134ms
src/models/account.model.ts 13ms
src/models/category.model.ts 8ms
src/models/transaction.model.ts 12ms
src/models/user.model.ts 9ms
src/routes/index.ts 7ms
src/routes/transactions.ts 9ms
[error] No parser could be inferred for file: static/placeholder.txt
swagger.yaml 47ms
tsconfig.json 9ms
tslint.commit.json 5ms
tslint.json 5ms
webpack.config.js 12ms
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cash-tracker@1.0.0 prettier:all: `prettier --write "./**/*"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cash-tracker@1.0.0 prettier:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ben/.npm/_logs/2019-05-05T03_11_13_873Z-debug.log
```

**Comment by evilebottnawi** [comment]
It is expected behavior, `eslint` do same, but we want implement dot as argument https://github.com/prettier/prettier/issues/6085, i.e. you can use `prettier .` and prettier fix only supported files (`eslint` supports same pattern), closing, anyway thanks for issue
