### ISSUE TITLE
playground captures Cmd+L

### ISSUE THREAD

**Issue by jasonkarns** [prettier/prettier#6105]
The playground is intercepting Cmd+L and breaking the browser shortcut to address bar.

**Comment by duailibe** [comment]
It's probably [CodeMirror](https://codemirror.net/)'s fault.

**Comment by jasonkarns** [comment]
Looks like it's being caught by the sublime text keymap: https://github.com/codemirror/CodeMirror/blob/master/keymap/sublime.js#L578
