### ISSUE TITLE
Removes required semis in typescript with --no-semi flag

### ISSUE THREAD

**Issue by mrchief** [prettier/prettier#6108]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACGBnANgS1iQBN9sBDAI1ziUPgCcAzcsOAWinIFs4AdKMThhc5BnAzcIxAK40MfEONYx2xBhAAOxCAHco7GOI7Y4NMDEUZgAjBnzdNEBjAwAqDOWwYASnBUYTBrcCkr+FooA3AK2GHAAHk4uWACemhIAKsYAIuQw5BgAvBgA8pQAVsKuAD4YWXBwAHLScAAKGprYANoAutFQsQlJrvRwzKwS2R06+vVwAMpmVfP58NaxdtgAFnpTWjNQSBiUEBA05FD9dpv+DGBbALItJYfHp+eXG564uM1C2AAJfDEISvE5nfyfKDXLDGI5zP5wXpXa75ADm2HhxkRyNiAF8YlACVAQAAaEBaGD4aDYZCgMQaXStMQIWkocgANwgwLJIEoDFYAGs4DB5ppWIQ0cgjDI4OStjBuLgAOpbfDwbDitiLKDYdX4DnqlLIcDYWnkwimFztcho7jkZAsXCmcnlbDxABCArAwtFPDgABlCHBHeRnXKQG74vNJTQAIoyCDwUPh8nihhWk0wNJwbBgBj4TQwXmaAuwZXAmBbZAARgArAAGNMaUzKgWaE2l3NjDkh8kAR0T8HaWjZIC8nAaQmIvPEg-w4htdodSCdLpApm4+BT671UDR8aHIdXYfX+UoFeIVeQACZyUZyPgCPuAMIQbj2k1QaB9kAyUwZFQbJrnAeJ4kAA)
```sh
--parser typescript
--print-width 150
--no-semi
```

**Input:**
```tsx
// tslint:disable:interface-name
declare module "react-dropdown-tree-select" {
  import * as React from "react";

  export type TreeData = Object | TreeNodeProps[];

  export interface DropdownTreeSelectState {
    showDropdown: boolean;
    searchModeOn: boolean;
    allNodesHidden: boolean;
    tree: TreeNode[];
    tags: TreeNode[];
  }

}

```

**Output:**
```tsx
// tslint:disable:interface-name
declare module "react-dropdown-tree-select" {
  import * as React from "react"

  export type TreeData = Object | TreeNodeProps[]

  export interface DropdownTreeSelectState {
    showDropdown: boolean
    searchModeOn: boolean
    allNodesHidden: boolean
    tree: TreeNode[]
    tags: TreeNode[]
  }
}

```

**Comment by hawkrives** [comment]
Hi! Thanks for filing your issue!

I'm not entirely familiar with Typescript, personally; could you explain a little about the issue you're seeing? 

Is the removal of the semicolons a syntax error, or something else? Could we try with a somewhat smaller file, since this one's a bit long, and it's difficult to see which semicolon removals matter, especially with the multi-line comments mixed in.

**Comment by mrchief** [comment]
> I'm not entirely familiar with Typescript, personally; could you explain a little about the issue you're seeing?

Neither am I but apparently, TS needs comma or semis as a separator in their type definitions. 

I've got a type definition [file](https://github.com/dowjones/react-dropdown-tree-select/blob/develop/types/react-dropdown-tree-select.d.ts) in a JS + React project. When I save it, prettier removes the semis. My first thought was that prettier is simply treating them as JS files and not paying attention to `.ts` extension; or that since my parser is babylon and my code is 99% JS, prettier is treating everything as such.

However, I chose the TS parser in the playground and the problem is still there. 

Looking at old issues, I see that it has been brought up a couple of times and all of those issues are closed/fixed. So this looks like a regression or something else that I can't put my finger on.

> Could we try with a somewhat smaller file, 

Yes, I updated the original post with a simpler and shorter snippet.

**Comment by lydell** [comment]
There does not appear to be any syntax errors in the Typescript playground: https://www.typescriptlang.org/play/#src=%2F%2F%20tslint%3Adisable%3Ainterface-name%0D%0Adeclare%20module%20%22react-dropdown-tree-select%22%20%7B%0D%0A%20%20import%20*%20as%20React%20from%20%22react%22%0D%0A%0D%0A%20%20export%20type%20TreeData%20%3D%20Object%20%7C%20TreeNodeProps%5B%5D%0D%0A%0D%0A%20%20export%20interface%20DropdownTreeSelectState%20%7B%0D%0A%20%20%20%20showDropdown%3A%20boolean%0D%0A%20%20%20%20searchModeOn%3A%20boolean%0D%0A%20%20%20%20allNodesHidden%3A%20boolean%0D%0A%20%20%20%20tree%3A%20TreeNode%5B%5D%0D%0A%20%20%20%20tags%3A%20TreeNode%5B%5D%0D%0A%20%20%7D%0D%0A%7D%0D%0A

**Comment by mrchief** [comment]
That's interesting. I found [this](https://github.com/Microsoft/TypeScript/issues/10730) which also seems to indicate the semis are optional. 

Let me run some tests to make sure everything checks out and we can close this.
