### ISSUE TITLE
JSDoc typedef parentheses are removed if a typedef ends with `**/` instead of `*/`

### ISSUE THREAD

**Issue by rsimha** [prettier/prettier#6121]
**Prettier 1.17.1**

**Before:**
```
foo = /** @type {!Foo} **/(bar);
```

**After:**
```
foo = /** @type {!Foo} **/ bar;
```

Playground link [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAIhArgIwBs4MAqDASyjNNQB0p0MB1AJ2gHMGAzCCDALwZUpcgAEYATwAOJYAEIAYnwC+NVAAp8AQ1YBKANwMmAYQitWcMDB59Bw0Rgky5S1WU079RqCAA0IBDSMBTQAM7IoLrsAO4ACroIESjaAG4QFAAm-iD4rNpgANZwMADK0gVUHMgwrLhwAQAWMAC2hMyNFPBhFWBwpUldFKldksjgYREBVGFwrDBx+Rwt2sjc2oSzAQBWYQAeAEL5RSWl2i1wADJUcGsbWyC7e6VVxACKuBDwd5sNIBWsWascY6fCSQjQHLSVhUGDMLIwRrIAAcAAYAtCILM2NppONoXAgalbgEAI6feCLILJEDaMIAWigcDgmRZOUs5IolkW2mWqyQ61+AVmLQoNTqfzCrzgHy+twF9z+MG0+HhmURyAATAFatoKIQqmYWitxlBoCSQLhZgAVFXJQWzFQqIA)

Related to #4799

**Comment by thorn0** [comment]
Is this valid jsdoc syntax? Do other tools understand it?

**Comment by jridgewell** [comment]
I don't know about other tools, but it's valid in Closure. JSDoc itself only requires the explicit `/**` opening string, and it'll eat everything until the closing `*/`.

**Comment by ExE-Boss** [comment]
This is valid, albeit ugly, syntax.
