### ISSUE TITLE
JSDoc typedef parentheses are removed if member access is done on a typedef'd object variable

### ISSUE THREAD

**Issue by rsimha** [prettier/prettier#6122]
**Prettier 1.17.1**

**Before:**
```
foo = /** @type {!Foo} */ (/** @type {!Baz} */ (baz).bar );
```

**After:**
```
foo = /** @type {!Foo} */ /** @type {!Baz} */ (baz.bar);
```

Playground link [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA8gIwFZxgwYCGYYcAzpRtBjAJ4AOcAJnAGYA6U6GA6gCdoAcx4cIEDAF4MqAFTyMAAUYsMwAIQAxSQF8M8zAAoFS1czgbNAIRIAvA0YzGcDgJQA6N4IzuA3Dx8AMIQgoKEMOKSMnKKKmpWWroQTiam8RbqWnaOhiZu9u5ePn6BUDw8IAA0IBBMMACW0JTIoCThEADuAAodCK0oJABuEI2sNSA4gmQA1nAwAMpMZI1QIsgwggCucLUAFjAAtgA2-PuN8JQrFIsDl43DlwzI4NSTa5RwgjA9MyJHEjIDgkE5fWp4SgADxsMzA8yWJCOcAAMms4MDQeCQJCoYs1iITnAAIrbCDwTFgvYgFaCL6CV5uHAME7QSZMQRrGD8cYwfbIAAcAAZahyIF8hCQmK8OVRvsMMbUAI5k+B-eqDEAkSgAWigcDYbEmERVjQifxIAKBSBBVNqXyOjU2O2plAJRNJ5IxNqx1JgJBwPNYfOQACZalsSI0TgTQkdAa8oNBFSBtl8ACoBwa2r56PRAA)

Related to #4799

**Comment by thorn0** [comment]
A more isolated bug report:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAEBeTAKAegCojMABGATwAc5NgBCAIQEMAvAX0yIPwCN2ASgB0AgE6CA3AB0oIADQgI1GAEtoAZ2SgWYsRADuABV0ItKFgDcIqgCYKQfMSzABrODADK1F6qgBzZBgxAFc4RQALGABbABsAdQjVeA0fMDhPM2TVS2TKZHANLUU-DTgxGCNnf2iWZFQWWLLFACsNAA8mZzcPTxZouAAZPzh6xuaQNvbPP39YuABFEIh4MabwkB8xMrECgT44WIdqMT8YeLsYCOQADgAGRROIMvjnagKTuB3LUcUAR2W8CqynMIBYGgAtFA4HBbLCHGI4ADVIiqiwanUkA11ooytFVEFQhsNLN5ksVqMseMNjAWHwLrYrsgAEyKYIsVSxWYAYQg0VqBSg0F+IBCZQAKnTzNiJpYwgBJKBw2CeMCnFQAQSVnio8zWZQ4HCAA)
```sh
--parser babel
```

**Input:**
```jsx
foo = (/** @type {!Baz} */ (baz).bar);

```

**Output:**
```jsx
foo = /** @type {!Baz} */ (baz.bar);

```

**Comment by evilebottnawi** [comment]
WIP

**Comment by thorn0** [comment]
Should we probably convert such type assertions into full-fledged AST nodes to really fix all the issues with them?

**Comment by evilebottnawi** [comment]
@thorn0 to be honest I don’t even know, I will start working on this in the near future and leave feedback if something goes wrong

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/7791
