### ISSUE TITLE
Line breaks for functional-style switch-case

### ISSUE THREAD

**Issue by texastoland** [prettier/prettier#6123]
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzAlgI0wF5MAKKAGkwFs5qJjMBtAXQEpiA+TYAHSkyY0Ad1wwwACzJQOfAYMxgAhmjiYADEkwAnODACu2gev4LFKtQEYtug0cyXTC5asxQbewwNr0mUFpgAPoFOZqQ+EH4BJHj45JgAtA5UERwA1DgE8UkATCl0EGxsTgC+-GVQIBQgEAAOMLjoyKBK2toQwgAKrQhoyCBKAG4QuAAmVSD42kpgANZ6AMq1M7hQAObIMNr6cNUSMNQANgDqEmJwaMtgcAu9YriDYgCe-WBofdWrqtowndNr1CUyGwSkOqmqACs0AAPABC0zmiyUtAAMqs4MDQeCQFDoQtVmtDnAAIr6CDwTFg3YgZbab79fBKfBPQ7QCa1bSrGDHMYwCTIAAc6mqHIgqmO01q-Q5Fzg2kGGOqAEcyfA-nU+igVAkoHA4KN9RNdCrcLo-koAUCkCCqdVVNRcJTsWgCUTSeSMdasdSYEyeaM+cg8iAtkpcIcCQBhCDUQH9UGHCb6VQAFSZmptqhKJSAA)
```sh
# Options (if any):
--no-semi
```

**Input:**
```jsx
const fib = (n, memo = []) => {
  switch (n) {
    case 0: return 0
    case 1: return 1
    case n: return memo[n] ||
      (memo[n] = fib(n - 1, memo) + fib(n - 2, memo))
  }
}
```

**Output:**
```jsx
const fib = (n, memo = []) => {
  switch (n) {
    case 0:
      return 0
    case 1:
      return 1
    case n:
      return memo[n] || (memo[n] = fib(n - 1, memo) + fib(n - 2, memo))
  }
}
```

**Expected behavior:**

Not move `case` body to its own line when it's a single `return` statement. It's the only thing that bugs me about formatting. The reason is that I use `switch` to simulate pattern matching. I tweeted a [gist comparing](https://gist.github.com/texastoland/64c65935f1f5deb31072826f1be5a78c) the exact same logic between JavaScript and Reason to illustrate my point. I'd be willing to tackle it if there isn't much opposition.

**Comment by bakkot** [comment]
Some other cases to consider:

```js
switch (x) {
  case 0:
  case 1:
    return a;
  case 2:
    return b;
}
```

```js
switch (x) {
  case 0:
    foo();
    return a;
  case 1:
    return b;
}
```

```js
switch (x) {
  case 0:
    break outerLoop;
  case 1:
    return b;
}
```

```js
switch (x) {
  case 0:
    throw a;
  case 1:
    return b;
}
```

Prettier's current style is nicely consistent across all of these. I don't know if it could be modified in the way you suggest while still retaining this consistency.

**Comment by texastoland** [comment]
I agree. With the exception of the first, the rule could be if _all_ lines consist of a single `return`. In the first case, I'd prefer `case 1: return a` on the same line.

**Comment by bakkot** [comment]
> the rule could be if _all_ lines consist of a single `return`

It could, though personally I like style rules to be local to the extent possible - if I have

```js
switch (x) {
  case 0:
    return a;
  case 1:
    return b;
  [etc]
  case 42:
    console.log('this should not happen');
    return null;
}
```

I would be pretty surprised if removing the `console.log` from `case 42` also changed the formatting of `case 0`.

> In the first case, I'd prefer `case 1: return a` on the same line.

Huh. I definitely don't share that preference. To me that would look like the `return a` is associated with `case 1` in particular, not both it and `case 0`.

**Comment by texastoland** [comment]
> I would be pretty surprised if removing the `console.log` from `case 42` also changed the formatting of `case 0`.

I don't think that would be surprising from the perspective of FP. Think of arrow functions. If you want to add a statement then you have to wrap the original line in braces with a `return`. We tend to use tricks like `case 42: return console.log('this should not happen'), null` or `case 42: logIdentity(null, 'this should not happen')`.

> To me that would look like the `return a` is associated with `case 1` in particular, not both it and `case 0`.

It kind of looks like that already.

> Huh. I definitely don't share that preference

Is it common in an imperative style to write `switch`es where all `case`s are a single `return` statement? My hunch is `switch` is considered a code smell outside of pattern matching. It's a bit of a corner case. We could reuse my original example for practical purposes.

```
const fib = (n, memo = []) => {
  switch (n) {
    case 0:
    case 1: return n
    case n: return memo[n] ||
      (memo[n] = fib(n - 1, memo) + fib(n - 2, memo))
  }
}
```

Arguably, FP in JS is niche, and pigeon-holing `switch` to do pattern matching moreso. In that limited context, it doesn't make sense to treat `return` like a block-level statement.

**Comment by bakkot** [comment]
> I don't think that would be surprising from the perspective of FP.

I mean, I mostly write functional code, and it would be surprising to me. Specifically, the fact that changing one `case` affects other unrelated `case`s is weird to me, regardless of what paradigm the code is reflecting.

> It kind of looks like that already.

Hm, maybe, but I'm a lot more accustomed to seeing the style I wrote than the style you're suggesting, so I already know how to interpret it at a glance. I think there's a lot of value in sticking to more common styles, for this reason. Of course, I could be wrong that the style prettier currently uses is more common, but I'd be pretty surprised to learn this is the case outside of particular subcommunities.

> Is it common in an imperative style to write switches where all cases are a single return statement? 

I don't know about common, but it's [not especially rare](https://github.com/prettier/prettier/blob/b3adb46ba985e043fda079f56cb263305c082108/src/language-js/needs-parens.js#L257-L285). (And note how [a subsequent `switch`](https://github.com/prettier/prettier/blob/b3adb46ba985e043fda079f56cb263305c082108/src/language-js/needs-parens.js#L314-L392) has only _almost_ all `case`s as a single return - it'd be weird for these two samples not to match.)

----

By the way, you'd probably be interested in [this JavaScript proposal](https://github.com/tc39/proposal-pattern-matching/) if you haven't come across it yet.

**Comment by texastoland** [comment]
> I mean, I mostly write functional code, and it would be surprising to me.

That's exactly the kind of perspective I was looking for.

> And note how [a subsequent `switch`](https://github.com/prettier/prettier/blob/b3adb46ba985e043fda079f56cb263305c082108/src/language-js/needs-parens.js#L314-L392) has only _almost_ all `case`s as a single return

This is a super contextual example.

> By the way, you'd probably be interested in [this JavaScript proposal](https://github.com/tc39/proposal-pattern-matching/)

That and partial application both look compelling 🤙

---

Even more writing TypeScript, FP style feels like an uphill battle. I write more and more ReasonML. I appreciate the goals of Prettier and love the balance it strikes. The solution for my use case may be to accept ternary when writing JS.

```js
const fib = (n, memo = []) =>
  n === 0 || n === 1
    ? n
    : memo[n] || (memo[n] = fib(n - 1, memo) + fib(n - 2, memo))
```
