### ISSUE TITLE
html parser gets confused by <script type=text/javascript>

### ISSUE THREAD

**Issue by felix9** [prettier/prettier#6134]
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEwmGBPABzgAIALGAWwBsA+AHSlXOvqmONQGcwAnASwIxi+IgF54ADxgB6AFYBDAG7zu-Qa3bs6IUnCpUI2hu1TTVAmK1PNaIADQgIgvtE7JQ8njwgB3AAqeCG4oShB8mPYgAEY88mAA1nAwAMoEcXxQAObIMDwArnAONgDqpHzwnGlgcMlB5XyK5XjI4JxuDhmccDwwfrGZFPLIAGbyVF0OspwSAEKxCUnJ8hRwADIZcCNjEyBTEskZmVRwAIp5EPBb44UgaTxdPC02kQT8sMXhMKTIABwADA5XhAusVYgQWq84A9FJsHABHc7wPpOYIgFQAWigcDgmBxkR4cARfAJfXkAyGSFG1wcXQofBy+RunEOxzOF02lO2Nxg8iiH0wX2QACYHLl5HwqIcAMIQCiDFpQaCwkB5LoAFV5wSpXQAvjqgA)
```sh
--parser html
```

**Input:**
```html
<!doctype html>
<html>
  <script type=text/javascript>
    "hello"
  </script>
</html>
```

**Output:**
```html
SyntaxError: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:3)
  3 |   <script type=text/javascript>
  4 |     "hello"
> 5 |   </script>
    |   ^
  6 | </html>
```

**Expected behavior:**
This is legal html, and it should be formatted without error.

Prettier seems to be confused by the unquoted '/' in the script tag. Quoting it like `type="text/javascript"` will work.

I ran into this problem by trying to use Prettier to examine some random page saved from the web.

**Comment by ExE-Boss** [comment]
Yeah, an&nbsp;unquoted `/`&nbsp;character shouldn’t be&nbsp;treated as&nbsp;self&#x2011;closing if&nbsp;it’s&nbsp;not immediately followed by&nbsp;`>`.

**Comment by jcroll** [comment]
Try properly quoting:
```
<script type="text/javascript">
    "hello"
 </script>

**Comment by ExE-Boss** [comment]
Actually, this seems to be a bug within [angular&#x2011;html&#x2011;parser](https://www.npmjs.com/package/angular-html-parser), which is what Prettier uses internally to parse HTML: https://github.com/prettier/prettier/blob/6fae09b67ec6f7b27259a5c133a6961d05a4161b/src/language-html/parser-html.js#L20

**Comment by ikatyang** [comment]
I forked it since it should be easier to maintain, the fork could be updated from upstream easily. What did you mean confusing?

**Comment by evilebottnawi** [comment]
@ikatyang a lot of code not related to parser, i can be confused for other developers, but it is not high priority, just ask about this

**Comment by thorn0** [comment]
Closing in favor of #8210
