### ISSUE TITLE
recursive globs don't work as expected

### ISSUE THREAD

**Issue by samthomson** [prettier/prettier#6135]
Ubuntu, terminator term, yarn 1.12.3, prettier ^1.17.1.

in my package scripts I have:
```
"lint": "prettier --config=\".prettierrc\" --write src/**/*.ts src/**/*.tsx test/**/*.spec.ts",
```
When I run `yarn run lint` I expect the following files to be formatted:
- src/declarations.d.ts
- src/renderer/GPXApp.tsx
- src/renderer/components/MapViewPage.tsx

but only src/renderer/GPXApp.tsx is formatted.

![image](https://user-images.githubusercontent.com/6588340/57966689-eea46900-7944-11e9-961e-e95d5582c47c.png)

(it doesn't throw any errors, it just overlooks files I expect it to match).

I've tested my glob at http://www.globtester.com
I've also trawled through countless similar issues and tried wrapping the glob pattern in different variations of escaped quotes.

If I change it to `"lint": "prettier --config=\".prettierrc\" --write \"src/**/*.ts src/**/*.tsx test/**/*.spec.ts\""`

then I get:

![image](https://user-images.githubusercontent.com/6588340/57966660-8fdeef80-7944-11e9-8c45-b4147acbf8a9.png)

The same is true for single quotes.

Note: If I add `src/**/**/*.tsx` then it will also match the file `src/renderer/components/MapViewPage.tsx`. I don't want to add a different rule for every level of directories I might have, that seems silly. How can I do these with a pattern, or is it a bug with prettier glob matching ?

My actual config is pretty pedestrian, but here it is in case it helps:
```
{
  "trailingComma": "all",
  "tabWidth": 4,
  "semi": false,
  "singleQuote": true,
  "useTabs": true
}
```

**Comment by lydell** [comment]
```
"lint": "prettier --config=\".prettierrc\" --write src/**/*.ts src/**/*.tsx test/**/*.spec.ts",
```

Since the globs are not quoted, it means that the shell that npm/yarn spawns will expand the globs. You can see what they are expanded to (= what Prettier receives) by adding this script to package.json:

```
"debug": "echo src/**/*.ts src/**/*.tsx test/**/*.spec.ts",
```

and running `yarn run debug`. What is the output?

---

```
"lint": "prettier --config=\".prettierrc\" --write \"src/**/*.ts src/**/*.tsx test/**/*.spec.ts\""
```

In this case, the globs are within quotes so the shell won't expand anything. However, you must quote each glob separately:

```
"lint": "prettier --config=\".prettierrc\" --write \"src/**/*.ts\" \"src/**/*.tsx test/**/*.spec.ts\""
```

Does that work for you?

Maybe we can provide better error messages for this.

**Comment by samthomson** [comment]
Hi @lydell Thanks for trying to help.
After adding `"debug": "echo src/**/*.ts src/**/*.tsx test/**/*.spec.ts", to check how prettier receives my glob pattern I get:

![image](https://user-images.githubusercontent.com/6588340/57967847-3205d400-7953-11e9-8d1d-64c9cd95599a.png)

So the first two are replaced with a single file for each, and the third is left as expected.

After changing to wrap each glob in quotes: i.e. 
```
"lint": "prettier --config=\".prettierrc\" --write \"src/**/*.ts\" \"src/**/*.tsx\" \"test/**/*.spec.ts\"",
```
I get the expected results:
![image](https://user-images.githubusercontent.com/6588340/57967910-bb1d0b00-7953-11e9-9054-3372f4d14209.png)

I guess in my case I didn't realise each glob must be quoted. A really simple fix in the end. Thanks a lot.
