### ISSUE TITLE
Keep parens for multi-line logical expressions

### ISSUE THREAD

**Issue by polarathene** [prettier/prettier#6137]
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALAhmgOVxgEsA3OAGVwC8BPSiXAEwGUBXAB04gCcsAvJgAUAHSiZMMOpzgQAZpgASAFQCylAJIBbXAHM4AUQA2cbQiwBCAUIAG7KMzjySUOM1uYAZF-GTbxkzMrnqersrqWroGJmYWAHScvBAwKTJw4gCU4uKQUBiYJGgAQskA7mhwvJhC0rIKmGWuzBBlmNZ2Dk4ubh656Fh4aJoA8hzcfIIifoUl5ZXVPjNNjq3xmrBVlWCk0CMARgsUvFk5UHkF7JWj4zz8NdMS7UNEpBTU9Iwst5Pevk9DG5cO5YHztJIQThoeJgXgkUhgXDGP7tSoIYrOPgZKDZKD9fJYIoANSKJH2pgeYieEKhMLhCKRmAAPkyZkVSq0FijhC9iOQqLQGEEfvcWe0rnAgRN+LjMiAADQgSG7fLIUC4XjlAAKGoQaGQIFwZAgJGYCpA+14uDAAGs4DBWJxrSFkDBeOw4IrsDBtMYAOrYeFwNBOsBwVh6+HkeF0A1gND6xWuBYwLVWvS6ZDyJGVRUAKzQAA9Sta7Q7cOZKK44Fmc56QAXC6wQqYAIrsFI1pDZ4y5kBO3gLA37XD7OiBKDmpKuGB+00wbDIAAcAAZFRDKn6rZwDUlg1UKOaAI4d+BpyH6lD4AC0bnc7nNvDgJ5IT7T+kz3brisq2hIrvdes0BbOB207Wte3rGBRznZgF2QAAmRU3VwEhjBCABhCBtE-EAoGgGtFQlFRR0vHtKgAXwooA)
```sh
--parser babylon
```

**Input:**
```jsx
const hasNativeLazyLoadSupport = (
  typeof HTMLImageElement !== `undefined` &&
  `loading` in HTMLImageElement.prototype
)

const isBrowser = typeof window !== `undefined`
const hasIOSupport = (
  isBrowser &&
  window.IntersectionObserver
)

const useIOSupport = (
  !hasNativeLazyLoadSupport &&
  hasIOSupport && !props.critical && !seenBefore
)

const isVisible = (
  props.critical ||
  isBrowser && (hasNativeLazyLoadSupport || !useIOSupport)
)
```

**Output:**
```jsx
const hasNativeLazyLoadSupport =
  typeof HTMLImageElement !== `undefined` &&
  `loading` in HTMLImageElement.prototype;

const isBrowser = typeof window !== `undefined`;
const hasIOSupport = isBrowser && window.IntersectionObserver;

const useIOSupport =
  !hasNativeLazyLoadSupport && hasIOSupport && !props.critical && !seenBefore;

const isVisible =
  props.critical || (isBrowser && (hasNativeLazyLoadSupport || !useIOSupport));

```

**Expected behavior:**

`hasIOSupport` is fine, but as `hasNativeLazyLoadSupport` is too long, it just removes the parens but this seems to reduce clarity. Ideally the parens would be left alone for both in this situation, more so with `hasNativeLazyLoadSupport`.

`useIOSupport` and `isVisible` are too long and get treated similar to `hasNativeLazyLoadSupport`, however compressed to a single line(well `isVisible` added some paren). The line separation was intentional for better grokking. I understand prettier's take on this though.

Doesn't seem like there is any config/option for handling this. I did see a related PR for similar regarding [math expressions](https://github.com/prettier/prettier/pull/4407), [released in 1.13](https://prettier.io/blog/2018/05/27/1.13.0.html).

[A related issue #2065](https://github.com/prettier/prettier/issues/2065), ended up being more focused on arrow function parens, specifically for JSX, that issue is now locked. I think this is a case where keeping parens can be valid. [Another issue](https://github.com/prettier/prettier/issues/3546) points out:

> Which personally reminds me if of an unbraced if statement and, rightly or wrongly, sets off alarm bells.

[airbnb guide](https://github.com/airbnb/javascript#arrows--paren-wrap) states:

> In case the expression spans over multiple lines, wrap it in parentheses for better readability.

**Comment by evilebottnawi** [comment]
Sorry we do not want modify current output, you can use `prettier-eslint` and enable rule for this, maybe we revisit this in future, anyway feel free to feedback

**Comment by polarathene** [comment]
@evilebottnawi  `prettier-eslint` would have to be run after `prettier` no? I don't think it would know how to preserve what I had originally(which was more formatted for context purposes). Especially since `prettier` messes with parens which is destructive.
