### ISSUE TITLE
Vue-cli3 error: Parsing error: Unexpected token = 

### ISSUE THREAD

**Issue by MoonCheung** [prettier/prettier#6141]
**Environments:**
- Prettier Version: 1.17.1
My project development environment used the Prettier version 1.17.1 plugin before
- Running Prettier via: 
I was able to run the node v10.15.3 project with the vue-cli3 project and report an error
- Runtime: 
node v10.15.3
- Operating System: 
My computer system is Windows 10 pro
**Steps to reproduce:**

```javascript
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 2017,
    sourceType: 'module',
  },
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  // extends: ['plugin:vue/essential', 'eslint:recommended'],
  extends: [
    'plugin:vue/essential',
    'eslint:recommended',
    'plugin:prettier/recommended',
    // 'plugin:vue/base',
    '@vue/standard',
    // "plugin:vue/recommended",
  ],
  "plugins": [
    "flowtype",
    "html",
    "vue"
  ],
  // add your custom rules here
  //it is base on https://github.com/vuejs/eslint-config-vue
  rules: {
    // 关闭冲突规则
    'prettier/prettier': [
      'error',
      {
        //使用单引号而不是双引号。
        singleQuote: true,
        //多行时尽可能打印尾随逗号。
        trailingComma: 'none',
        // 在对象文字中打印括号之间的空格。
        bracketSpacing: true,
        // 将>多行JSX元素放在最后一行的末尾，而不是单独放在下一行（不适用于自闭元素）。
        jsxBracketSameLine: true,
        parser: 'flow'
      },
    ],
   //以下规则忽略
  }
}
```
![image](https://user-images.githubusercontent.com/19801190/58107314-24cf3a80-7c1c-11e9-866f-925b03ea13eb.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/19801190/58106365-98704800-7c1a-11e9-9e82-4c2ea8d4a316.png)

If the above screenshot don't use ` ESlint ` can run, but ready to use ` ESlint + prettier ` run to appear error screenshot below, how to solve, specific issues?

**Actual behavior:**
![image](https://user-images.githubusercontent.com/19801190/58106325-8a222c00-7c1a-11e9-8bde-337ad7eda171.png)

**Comment by duailibe** [comment]
Can't reproduce it:

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQVmpw4C0kOZSAzlnlALzEgBMALN0IAzCBFQB6GvQg4SUCZlwE4hEABoQELDACW0ZslB4ATsYgB3AAomEBlHgBuEHQBN1IAEbG8YANZwYAGU2MB0oAHNkGGMAVzgNAAsYDBwAdQSdeFYfOEDbTJ0HTIBPZHBmAw0w5jhjGEtvcIw8ZCE8HBqNACtmAA8AIW8-AMC8DDgAGTC4VvbOkB7ewLDwnDgARRiIeFmO+JA2YxrjMoc49yxjMJhU1xgE5AAOAAYNS4ga1O8sMsu4Y4cMw0AEctvAGlo7CA8MxaFA4HAXIj3MY4KCdKiGngmi0kG09hoahgdFFYvtmCs1pttjM8XN9jA8B5bi57sgeBpongdDgVgBhCAYZplKDQIEgGI1AAqTLs+JqAF8FUA)
```sh
--parser vue
```

**Input:**
```vue
<template>
    <el-col :span="24">foo</el-col>
</template>
```

**Output:**
```vue
<template>
  <el-col :span="24">foo</el-col>
</template>

```

So it seems there's a problem with the ESLint integration. Did you try opening an issue in https://github.com/prettier/eslint-plugin-prettier ?

**Comment by MoonCheung** [comment]
I didn't develop a problem for `eslint-plugin-prettier`, but as a newbie, I used `eslint +prettier` for the first time before An error occurred while the project was running.

Another question`--parser vue`, what does that mean

**Comment by duailibe** [comment]
Okay, I read your issue again and I think I see what the problem is. In your ESLint config, you can just remove this line:

```js
module.exports = {
  // ...
  rules: {
    // 关闭冲突规则
    'prettier/prettier': [
      'error',
      {
        //使用单引号而不是双引号。
        singleQuote: true,
        //多行时尽可能打印尾随逗号。
        trailingComma: 'none',
        // 在对象文字中打印括号之间的空格。
        bracketSpacing: true,
        // 将>多行JSX元素放在最后一行的末尾，而不是单独放在下一行（不适用于自闭元素）。
        jsxBracketSameLine: true,
        parser: 'flow' // <----- REMOVE THIS LINE
      },
    ],
   //以下规则忽略
  }
}
```

Prettier will try to guess which parser it should use to parse your file based on the filename (i.e. `foo.js` will use Babylon parser, `foo.vue` will use Vue parser, etc.), but if you included that on your config, it will force using that parser.

Let me know if removing that line works

**Comment by duailibe** [comment]
And what I meant was: the problem you're having is from a Prettier + ESLint integration, but this repository is specifically about problems that only happen when you use Prettier directly.

**Comment by MoonCheung** [comment]
```javascript
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 2017,
    sourceType: 'module',
  },
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  // extends: ['plugin:vue/essential', 'eslint:recommended'],
  extends: [
    'plugin:vue/essential',
    // 'eslint:recommended',
    'plugin:prettier/recommended',
    'plugin:vue/base',
    '@vue/standard',
    // "plugin:vue/recommended",
  ],
  "plugins": [
    "prettier"
    "flowtype",
    "html",
    "vue"
  ],
  // add your custom rules here
  //it is base on https://github.com/vuejs/eslint-config-vue
  rules: {
    // 关闭冲突规则
    'prettier/prettier': [
      'error',
      {
        //使用单引号而不是双引号。
        singleQuote: true,
        //多行时尽可能打印尾随逗号。
        trailingComma: 'none',
        // 在对象文字中打印括号之间的空格。
        bracketSpacing: true,
        // 将>多行JSX元素放在最后一行的末尾，而不是单独放在下一行（不适用于自闭元素）。
        jsxBracketSameLine: true,
        // parser: 'flow'
      },
    ],
   //以下规则忽略
  }
}
```

I according to your problems trying to do, the parser: 'flow' comment out, not to delete, and then to a single vue files use `npm run dev` run to complain a lot of error, such as command line appear a lot of error: `Insert `;` prettier/prettier`, `error: Delete ` · ` (prettier/prettier)`, etc., similar to the error * (prettier/prettier)

Another question I'm not going to use ` npm run lint - fix ` will automatically repair project all the files inside,Take a look at the screenshot below:
![image](https://user-images.githubusercontent.com/19801190/58261604-35fa8180-7dab-11e9-8593-3e4434028338.png)

**Comment by MoonCheung** [comment]
@duailibe From the vue-cli3 project, I gave up the configuration of ESlint+prettier, and only chose what can make the ESlint configuration work, without causing parsing error ，thank you!
