### ISSUE TITLE
Unstable template literals marked with /* HTML */ and /* GraphQL */

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#6150]
Happens if the template literal initially doesn't contain line breaks.

Another issue about unstable template literals: #5885

### HTML in JS ###

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUB6AVAAgAkAVAWQBl9dt8ADAHgEIBaZ-AIwEMAnARn1YA+Dj3xNWI7gCYBzQbQCUAbhAAaEBAAOMAJbQAzslA9uEAO4AFHgkMpOANwg6AJmpDtunMAGs4MAMqaXjpQAObIMNwArnDqABYwALYANgDqcTrw+kFgcP42mTr2mQCeyOD6huoh+nDcMBaeoYmcyKicybXqAFb6AB4AQp4+fv6ciXDkIXBtHV0gvX3+IaHJcACKURDws52xIEHctdzlXOwlydBumtwhMKkuMHHIABwADOo3ELWpnprlNzgx3sM3UAEctvBGlpbCBOPpmFA4HBnCi3Nw4BCdBjGpxmq0kO09upaokdBFovt9Cs1pttjNCXN9jBOOwHs4nsgpOpIpwdMkVgBhCCJFrlKDQUEgKK1Yis2xE2oAXyVQA)
```sh
--parser babylon
```

**Input:**
```jsx
foo(/* HTML */ `<!-- bar1 --> bar <!-- bar2 -->`);
```

**Output:**
```jsx
foo(
  /* HTML */ `
    <!-- bar1 -->
    bar
    <!-- bar2 -->
  `
);

```

**Second Output:**
```jsx
foo(/* HTML */ `
  <!-- bar1 -->
  bar
  <!-- bar2 -->
`);

```

### GraphQL in JS ###

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUB6AVAAgHEAnAQwAcALARQBl9dt8ADARwFc5iBPfYfdBD74ARqWL4AvlOYBKANwgANCAjkYAS2gBnZKHHEIAdwAK4hLpSkAbhA0ATZSBFkwAazgwAyuVJgNUADmyDDEnCqUMAC2ADYA6pQa8Nq+YHBeFkka1kncyODauioB2lwwJmSBUaTIqKQxpSoAVtoAHgBCrh7epFFwtAFwtfWNIC2tXgGBMXDU7BDwww1wKr7EpcT5YiLcMdBO5MQBMHEOMJTIABwADKuGpXFk5PmHcBvWQyocC3AVapYgUjaAC0UDgcHsEKcxDgHA0MIqpCqNSQdWWKlKUQ0ITCKxA2imMzmPyWoxgpBEp3s52QACYVKFSBoYlMAMIQKLVfJQaCfEDsUoAFQpljRpUkkiAA)
```sh
--parser babylon
```

**Input:**
```jsx
foo(/* GraphQL */ `query { foo { bar } }`);
```

**Output:**
```jsx
foo(
  /* GraphQL */ `
    query {
      foo {
        bar
      }
    }
  `
);

```

**Second Output:**
```jsx
foo(/* GraphQL */ `
  query {
    foo {
      bar
    }
  }
`);

```

**Comment by thorn0** [comment]
@jwbay Can this be caused by #5979?

**Comment by jwbay** [comment]
No, those changes are not in 1.17, or released at all, as far as I know.

**Comment by thorn0** [comment]
_Originally posted by @fisker in https://github.com/prettier/prettier/issues/7928_

**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAFAJSEB8mA9AFSYASAKgLIAymt1mABgDwBCALRDMAQ0wiqgkZgBGkoRR4BuADpQxxOo1YcuvGaIlTMR+YuWkVIADQgIABxgBLdMlBiATl4gB3AAVvBDRkEDEAGz8xAE9Q+zkvMTAAazgYAGVHZJcoAHNkGC8AVzh7AAsYAFsIgHVyl3g0bLA4DJDGlwA3RpiwsDR4kFy0OC8YAKS8qrFkbEjR+wArNAAPACEk1PSMsSq4Nly4OYWykBXVjNy8iLgARWKIeBOIxZBsr1GvMLkxOTgInZ3l5cjBai4ACYwcrIAAcAAZ7I5fKNaklHGFkXAvl1jvYAI6PeCTJyhFBiNBCKBwOAQ2lArxwQkuRmTMTTWZIeavM6jKouQolXnXW4PJ7HLmnewwP7gqEwpAAJmlSRcEWuAGEIFUZmFsQBWIHFUZMP5k7lvLqlACSUDpsAyYBBzgAgnaMjAYrcXqMAL6+oA)
```sh
--parser babel
```

**Input:**
```jsx
const foo = () => /* HTML */ `<!-- a --> <!-- b -->`;
a(/* HTML */ `<!-- a --> <!-- b -->`);
```

**Output:**
```jsx
const foo = () =>
  /* HTML */ `<!-- a -->
    <!-- b -->`;
a(
  /* HTML */ `<!-- a -->
    <!-- b -->`
);

```

**Second Output:**
```jsx
const foo = () => /* HTML */ `<!-- a -->
  <!-- b -->`;
a(/* HTML */ `<!-- a -->
  <!-- b -->`);

```

**Expected behavior:**

Stable output.

----

I found this when trying to fix [this file](https://github.com/prettier/prettier/blob/70da4fa630bbe21e1e7baa21984dd050cf1b3934/tests_config/run_spec.js#L41) second format, and have located the problem, here

https://github.com/prettier/prettier/blob/70da4fa630bbe21e1e7baa21984dd050cf1b3934/src/language-js/printer-estree.js#L1177-L1181 and https://github.com/prettier/prettier/blob/70da4fa630bbe21e1e7baa21984dd050cf1b3934/src/language-js/printer-estree.js#L875 , we detect if the `TemplateLiteral` is inline, but this `TemplateLiteral` will format by another parser, hard to know if it will break, seems we even can't know if it will parse by another parser. I was not able to fix it.

**Comment by fisker** [comment]
Any idea how to fix this? I tried to remove those `isTemplateOnItsOwnLine`, too many breaking changes.

**Comment by thorn0** [comment]
Let's decide first what output is expected in these cases.

**Comment by fisker** [comment]
I guess the second format is expect in all these cases.

**Comment by thorn0** [comment]
In that case, we can add another check to `isTemplateOnItsOwnLine` (BTW, the name is misleading, it's better to rename this function) or next to it. Namely, a check that the template will be formatted as embedded code. For that we could probably just call `embed(path, ...) !== undefined`, but that would be too much overhead. Instead we need to refactor `embed.js` to decouple the check from the printing.

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/13532
