### ISSUE TITLE
Allow plugin to add option with string type

### ISSUE THREAD

**Issue by dangmai** [prettier/prettier#6151]
**Environments:**
- Prettier Version: 1.17.1
- Running Prettier via:  CLI
- Runtime:  Node.js v10
- Operating System:  Linux

**Steps to reproduce:**

The `options` parameter that a plug in provides only accept the following types: `int`, `choice`, `boolean`, `flag`, `path`. I'd like the user to be able to provide a generic `string` type, which is not possible at the moment, see this check [here](https://github.com/prettier/prettier/blob/a9fd8e2cf42cd696aa1fb489ea7a374beb45b338/src/main/options-normalizer.js#L152).

Some background information: I'm developing a Prettier plugin for the [Apex language](https://github.com/dangmai/prettier-plugin-apex), and I'd to use a standalone server that does the parsing. Right now, I have to default making calls to `localhost` for the server, but I'd like to give the user the ability to specify this in case they have that server listening on a different interface or on a different network altogether.

**Expected behavior:**

Prettier allows me to specify a `string` type for option.

**Actual behavior:**

Prettier exits with error: `Unexpected type string`.

**Comment by shellscape** [comment]
Just ran into this today while working on https://github.com/shellscape/prettier-plugin-package. My use case is that I'm allowing users to enforce particular values for properties in package.json. This will come in particularly handy in monorepos.

**Comment by shellscape** [comment]
And just ran into this again trying to setup options for the same plugin. I need to allow an `object` to be passed for custom sorting rules. This is a pretty severe limitation for plugin authors.

**Comment by lydell** [comment]
I agree that it’s weird that we allow `path` – which is essentially a string – but not a string itself.
