### ISSUE TITLE
Update Rollup

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#6154]
We need to update it because the version we use doesn't parse some expressions like `...` which causes an error when bundling some of our dependencies.

This update isn't simple, I've tried a few times and gave up.

Opening this issue for me to keep track.

**Comment by revelt** [comment]
yeah current `0.47.6` is old

**Comment by fisker** [comment]
still working on it?

**Comment by duailibe** [comment]
@fisker Haven't started yet

**Comment by fisker** [comment]
I tried to do this, looks like the build script is working, but some tests failed, I will try to fix.

and another problem is I can't exclude `third-party.js` from `index.js`

My fork: https://github.com/fisker/prettier/commits/rollup-update
