### ISSUE TITLE
Unit test functions exceeding printWidth – document?

### ISSUE THREAD

**Issue by the-vampiire** [prettier/prettier#6156]
**Expected behavior:**
- expected it to break across new lines to respect the 80 width rule
- using vscode prettier and eslint extensions (vscode settings and package.json below)

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEMCeAHOAJTjQgBsA3OAJzUwF5Nq4BHAVwEtmAKAHRAB0AgPS4CafgEoA3LyhyAJiTDUOAIzh8QAYQhtacTABV8h5qUo0JIADSZukhgD5MwOZkyQoGV5l360QwBfBmxTYgsqWll5KA8lNBV1TX5-AwEFAEN4fjsHZ1d3D0xhYSY4AFsIKgVMADMIakw1ZgoOXDkij3gMLUzqAHM0ATJMqAG2TIHDRjxGmDYJkjgkcoXqb0w56gWlwMws+CYx6frGiuzc+0d6Fzc44o80wIzszUgAuDtgTFHxyemq34212bGW-EwQTsXngAA8YDIusU4LCCGAYNwPgYACJvQgnOCSAQwCAACUyVAAQnAENpMmQyHAFAB1doACz4D0eHixLww-RguPgNiRj15cAECAUQq+ouKwPmizBgX4csRXMh6o8QXVOpithAEDwMA46GQoH61AgAHcAAr9BBoZAgCkQDgKA0tTJgADWcBgAGU8N6OONkDBqGCbCA2TAKmRmWz2iRg2A4AHHe0OG1cM6wGgndHQ4EdrbqFMLsg6vTAtGAFZoWGU8u+-0BzIVOAAGVDcCrNa+IAbsIDoYGjIAimwIPB+2RayBgwZqM61Jk1DgyNADXhVLBWQoYGzkAAOAAM0d3EECzPLeGdu+W1CoBvYM7gZaNTpQmTQAFooBpJQPWjZh2C4D9ywGSskGredB0CCoOHDSMELHSdp1nWCB2jGB1wPI9kAAJlw8sODIMddAqGCQCgaA+2jNhAiMddvzgwIgiCIA)
```sh
--parser babylon
```

**Input:**
```jsx
const typeResolvers = require("../types");

describe("Course Type resolvers", () => {
  const { Course } = typeResolvers;

  describe("Course.date", () => {
    // removed for brevity

    test("args.language = portuguese: returns portuguese date range format", () => {
      Course.date(course, { language: "portuguese" }, context);
      expect(courseDateRange).toHaveBeenCalledWith(
        course.startDate,
        course.endDate,
        "portuguese"
      );
    });
  });
});

```

**Output:**
```jsx
const typeResolvers = require("../types");

describe("Course Type resolvers", () => {
  const { Course } = typeResolvers;

  describe("Course.date", () => {
    // removed for brevity

    test("args.language = portuguese: returns portuguese date range format", () => {
      Course.date(course, { language: "portuguese" }, context);
      expect(courseDateRange).toHaveBeenCalledWith(
        course.startDate,
        course.endDate,
        "portuguese"
      );
    });
  });
});

```

**Screenshot showing characters extending (85) over 80 limit**
<img width="1372" alt="Screen Shot 2019-05-25 at 10 24 31 PM" src="https://user-images.githubusercontent.com/25523682/58376603-5148c680-7f3c-11e9-84a0-e4dbd80da011.png">

**vscode prettier settings (default printWidth: 80)**
```json
{
  "files.autoSave": "onFocusChange",
  "prettier.tabWidth": 2,
  "prettier.proseWrap": "never",
  "prettier.eslintIntegration": true,
  "eslint.alwaysShowStatus": true,
  "eslint.run": "onSave",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[markdown]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

**package.json**
```json
{
  "devDependencies": {
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-jest": "^22.6.4",
    "eslint-plugin-prettier": "^3.1.0"
  },
  "eslintConfig": {
    "env": {
      "es6": true,
      "commonjs": true,
      "jest/globals": true
    },
    "extends": [
      "airbnb-base",
      "prettier",
      "plugin:jest/recommended"
    ],
    "plugins": [
      "jest"
    ],
    "globals": {
      "Atomics": "readonly",
      "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
      "ecmaVersion": 2018
    },
    "rules": {
      "quotes": [
        "error",
        "double"
      ],
      "max-len": [
        "error",
        80
      ],
      "prettier/prettier": "error"
    }
  }
}
``

**Comment by lydell** [comment]
Hi!

A thing to know about Prettier’s printWidth is that it is a guideline on how long lines can/should be, but Prettier can make both shorter and longer lines – sometimes because there’s no other way (deeply nested code for example), and sometimes on purpose.

Prettier makes an exception for testing functions. It was requested that these never break. See #842.

There is no way to change this. If you insist, there’s a workaround of putting `const tst = test;` at the top of your file and then using `tst(...)` instead of `test(...)`.

If you want to use ESLint’s max-len rule together with Prettier, that is generally possible, but also kind of annoying. I would recommend re-thinking if that rule actually gains you anything and maybe turn it off. See also https://github.com/prettier/eslint-config-prettier#max-len

You are not the first to ask about this, so maybe we should document this.

**Comment by the-vampiire** [comment]
ah damn thanks. i was losing my mind last night trying to figure this out. uninstalled everything, reinstalled one by one, tried all sorts of different settings. 

how / where can i add this to the documentation? i would hate to see someone else burn as much time as i did

**Comment by lydell** [comment]
Hmm, looks like we already have some documentation on it after all: https://prettier.io/docs/en/rationale.html#testing-functions

**Comment by the-vampiire** [comment]
good catch. i should have looked up prettier + testing. thanks for the info!

**Comment by the-vampiire** [comment]
@lydell hey man so im experiencing a column width issue again (this time outside of tests)

this is after removing this rule (as suggested) from my eslintConfig in package.json

```json
 "max-len": [
        "error",
        80
      ],
```

```js
module.exports = {
  Mutation: {
    registerForCourse: async (_, args, context) => {
      const { mailingList, ...registrationData } = args;
      const {
        logger,
        models: { Course },
        // TODO: implement
        emailService: { addToMailingList },
      } = context;

      if (mailingList) {
        addToMailingList(registrationData.email).catch(error => logger.error("Failed subscribing to mailing list from registerForCourse mutation", error));
      }

      return Course.registerStudent(registrationData);
    },
  },
};
```

now if i add the rule back in then it formats it correctly. however eslint now complains that the test files are beyond the max-len 👀 

```js
module.exports = {
  Mutation: {
    registerForCourse: async (_, args, context) => {
      const { mailingList, ...registrationData } = args;
      const {
        logger,
        models: { Course },
        // TODO: implement
        emailService: { addToMailingList },
      } = context;

      if (mailingList) {
        addToMailingList(registrationData.email).catch(error => logger.error(
          "Failed subscribing to mailing list from registerForCourse mutation",
          error,
        ));
      }

      return Course.registerStudent(registrationData);
    },
  },
};
```

i am working around this by setting the rule to `0 / "off"` but wondering if you had any insight into what the cause may be. id like to leave `max-len` out of my eslint rules completely but retain the expected prettier formatting (`printWidth: 80`, default)

**Comment by lydell** [comment]
Here's how Prettier formats your example:

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhuBpoB0pmBZLGAQxgEtoSRm2bNycAOb8q8cgDEKAYQhZyVOMJ5UAnlDA0AFAH0ANDR7lJVc5FjEYASnoA+EezHM7sxjVQ9+HH4oSQAZGRhzfGiJaVlyPkEoABE+HhoAX3oLKyoAblFPGm8YdyKxHAhJSThyU0Ly9Aw4HCphJhU1DUz6j3KAen6aABUAeWTR4X5UEjxUBBgGorh-QIBlWoA3fjBNXx4MDGGIDgCgkPCfDN7yrIY7eCIYAqgl5n4AMyNV87CI52AbzEByOJzOwT+skMsQiCQE0FSvEIP0c+DAfDAAAtDLVyBRXDRKtVaoRyHjyIYWCB5Gc4BgaFQsAAjKhgcj8JkQmgwCB+cEhQkRGgfPGoGgw2S1RTkTrqOB+biJaBU8y4iiORwvW5sIESGBqdiyjT4CVyNb65qwaFSWFKlJpTVLa6FZ1QDJ5ECmEAQEjwqBUZCgSx4gDuAAVLAgAygeJsIPwMJ6QEyEmAANZwGBrEg8MAQ5AwchYOBezEwVA4ADqmP48CoOd2G39tf42xgOmQ4CoAa9wQ0lDDCUk-mQHx4rRLIAAVlQiAAhVMZrM8ebhKBwUfjjRemdENYQvAARSwEHgm4nXpzcvInaZPCZOkqUCTJHZsErCZgmOQAA4AAyXniGiVgkJCdq+cD9psG5egAjie8CDj60YgNoAC0650nSSYSPB-ASIOPDDjw57biAGioPwBZFpOVAHnAx6nhuSBjheIC8EyH4YF+yAAExeoW-KSCoqAjigUDQDBIBYBowz3tGrEaBkGRAA)
```sh
--parser babylon
```

**Input:**
```jsx
module.exports = {  
  Mutation: {
    registerForCourse: async (_, args, context) => {
      const { mailingList, ...registrationData } = args;
      const {
        logger,
        models: { Course },
        // TODO: implement
        emailService: { addToMailingList },
      } = context;

      if (mailingList) {
        addToMailingList(registrationData.email).catch(error => logger.error("Failed subscribing to mailing list from registerForCourse mutation", error));
      }

      return Course.registerStudent(registrationData);
    },
  },
};
```

**Output:**
```jsx
module.exports = {
  Mutation: {
    registerForCourse: async (_, args, context) => {
      const { mailingList, ...registrationData } = args;
      const {
        logger,
        models: { Course },
        // TODO: implement
        emailService: { addToMailingList }
      } = context;

      if (mailingList) {
        addToMailingList(registrationData.email).catch(error =>
          logger.error(
            "Failed subscribing to mailing list from registerForCourse mutation",
            error
          )
        );
      }

      return Course.registerStudent(registrationData);
    }
  }
};

```

I don't think I understood what your problem was, exactly?

**Comment by the-vampiire** [comment]
hmm then there must be some conflict with eslint. when i remove the rule for `max-len` prettier does not format it (leaving it extending on one long line). when i add the rule back then prettier formats it the same as the playground output
