### ISSUE TITLE
Pipeline operator: support Smart & F# proposals

### ISSUE THREAD

**Issue by Sceat** [prettier/prettier#6162]
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBWABAHwHzoMToBU6ATCADQgQAOMAltAM7KgCGATuxAO4AKHCZilYA3CHQAmFEACN2rMAGs4MAMrUFdKAHNkMdgFc4lABYwAtgBsA6ibrxGGsHFWD7dEfYCeycI2aUWoxw7DC88trmrMgAZqyWwZQAVowAHgBC8koqqqzmcAAyWnCx8YkgKamqWtqWcACKBhDwpQnGIBrswey+MqwyXpbQ0tTsWjDWkjAmyAAcAAyUoxDB1vLUvqNw3SIllACOTfDhNEIgrIwAtFBwcBJ30uxwh3RP4ayR0UhxbZTB5nQ9IZ2owanVGs0St8yu0YP1JhJpsgSJR9Kw6JYagBhCDmKK+KDQPYgAzBAAq-SEP2CAF8aUA)
```sh
--parser babylon
```

**Input:**
```jsx
5 |> # * 2
```

**Output:**
```jsx
SyntaxError: Unexpected character '#' (1:6)
> 1 | 5 |> # * 2
    |      ^
```

**Expected behavior:**
The minimal proposal is supported, not the smart one (which is far more convenient)

![image](https://user-images.githubusercontent.com/11330271/58445504-92d89d80-8105-11e9-8931-557ec55e78b5.png)

**Comment by sosukesuzuki** [comment]
I would ask that if the feature will be implemented, Prettier will stop to support minimum pipeline? or optional?

**Comment by Sceat** [comment]
i don't see why both can't be supported as the only problem here is that `#` is unknown

**Comment by sosukesuzuki** [comment]
I see, thanks

**Comment by avetisk** [comment]
I have a similar issue but using `fsharp` proposal. 
```
SyntaxError: Unexpected "await" after pipeline body; await must have parentheses in minimal proposal
```

Seems that `.babelrc.js` is not taken into account.

**Comment by willin** [comment]
> `SyntaxError: Unexpected "await" after pipeline body; await must have parentheses in minimal proposal`

same in `smart`

**Comment by willin** [comment]
https://github.com/fanyonglong/DxFrameworks/blob/a6e8fefe218f8c676024dcc5c5884074bcd68f31/reference/babel-parser/src/parser/expression.js#L367-L376

perhaps it's sth related to eslint config

**Comment by willin** [comment]
use `babel-eslint@11` to resolve this problem.
