### ISSUE TITLE
Likelihood of configuration defaults changing

### ISSUE THREAD

**Issue by brlewis** [prettier/prettier#6163]
It was mentioned in issue #1105 that maintainers are considering changing the double-quote default to single quotes.

Suppose an organization decides to bypass all style discussion by standardizing on prettier with no configuration, taking all the defaults. What's the likelihood that the double-quote default will actually change at some point? Are there other defaults where there's a chance of a future change?

**Comment by lydell** [comment]
In my opinion, we should change only `--trailing-comma` to `es5` and nothing else. Switching to single quotes now after having had double quotes for so long would be pointless.

**Comment by evilebottnawi** [comment]
@lydell i think we should get statistics from github who use prettier before changing, i have very many projects which switch on single quotes, sometimes i think what it did most of repos

**Comment by brlewis** [comment]
Here's my assessment based on these answers:

There are at least two and probably not more than five options where at least one collaborator is inclined to change the default, so if one takes all the defaults it can't be ruled out that some might change at some point.

However, the inclination to change defaults is probably not strong enough to get any collaborators to push through all the non-coding things that would be involved. So although one should keep in mind the possibility that defaults could change, one shouldn't worry about it much.

Is this a fair assessment?

**Comment by j-f1** [comment]
That seems like a reasonable assessment.
