### ISSUE TITLE
Prettier hangs on Socket.IO

### ISSUE THREAD

**Issue by eadsjr** [prettier/prettier#6166]
When running Prettier from Sublime Text 3 on a copy of Socket.IO it consumes >%300 cpu continuously and doesn't appear to resolve for several minutes on OSX. I terminated it, as it normally completes on much larger files within seconds. It repeated the behavior on a second attempt.

From package.json:
    "socket.io": "2.2.0",

./node_modules/socket.io-client/dist/socket.io.js

**Comment by lydell** [comment]
Hi! How can we reproduce this?

```
~/stuff/socket  
❯ npm i prettier socket.io@2.2.0
+ socket.io@2.2.0
+ prettier@1.17.1
updated 2 packages and audited 78 packages in 0.973s
found 0 vulnerabilities

~/stuff/socket  
❯ ./node_modules/.bin/prettier ./node_modules/socket.io-client/dist/socket.io.js --with-node-modules --write
node_modules/socket.io-client/dist/socket.io.js 441ms
```
