### ISSUE TITLE
Markdown remark API for printer

### ISSUE THREAD

**Issue by mems** [prettier/prettier#6169]
There is any particular reason why prettier use the remark API only for parsing markdown, but not for printing?

https://github.com/prettier/prettier/blob/1061be070263f72653bdd69d41bfefc97699ec67/src/language-markdown/parser-markdown.js#L27-L43

It's could be better (for maintenance) to use [remark-stringify](https://github.com/wooorm/remark/tree/master/packages/remark-stringify) directly, instead of a custom one?

```js
const unified = require('unified');
const stringify = require('remark-stringify');

function genericPrint(path, options, print) {
	const node = path.getValue();

	return unified()
		.use(stringify)
		/*.use(... custom plugins)*/
		.stringify(node);
}
```

**Comment by lydell** [comment]
The point of Prettier is to be a custom Printer. remark-stringify doesn’t reflow text to fit 80 chars (`printWidth`), does it?
