### ISSUE TITLE
Uglify formatting in vue template.

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#6171]
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDOEGcAtJNtAjGUjAJ5ZwC8xIAGYQIAIzwAnYWMnTxEgWTD4qVfkJH159aVsmKAAsoCWYANbq5skfIAU0gEKSnEgJQDCwYGStSb1mT9AsgBfENQAeho6RlosFlgSKEjMXAI4QhAAGhAILBhjaCpkUEkJCAB3AAVJBGKUPAA3CGMAE2yQUQk8czgYAGUsHuMoAHNkGAkAVzgcgAsYDBwAdTnjeCohsDh+uvXjRvXOZHBVDpGqOAkYKu7RjDxkQTwcS5yAKyoADwdu3oG8HQADIjOBPF5vECfL79EajHBwACKUwg8HBr1mICGEkuEhOjRmHSw5Uuy26WBOxLguMaYJyAEcUfBbnl6iA8FR6FA4HBWryOhI4IzjILbnh7o8kM8MTlLhhjBNppiqHCEcjUWCpRDMTA8KJlm0YHNkAAmHKTPDGHBwgDCtAeJygLA6U0uABU9fVpZDiSMYAbWkbkAAOAAMYSAA)
```sh
# Options
--parser vue
--print-width 80
--tab-width 2
```

**Input:**
```vue
<template>
  <some-component :type="foobarfoobarfoobar" class="foo-bar-foo-bar" @click="foobarfoobar(fooBarBar)">{{ foobarfoobarfoobarfoobar }}</some-component>
</template>
```

**Output:**
```vue
<template>
  <some-component
    :type="foobarfoobarfoobar"
    class="foo-bar-foo-bar"
    @click="foobarfoobar(fooBarBar)"
    >{{ foobarfoobarfoobarfoobar }}</some-component
  >
</template>
```

**Expected behavior:**

```vue
<template>
  <some-component
    :type="foobarfoobarfoobar"
    class="foo-bar-foo-bar"
    @click="foobarfoobar(fooBarBar)"
  >
    {{ foobarfoobarfoobarfoobar }}
  </some-component>
</template>

```

**Comment by Airkro** [comment]
https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting

**Comment by sosukesuzuki** [comment]
@Airkro Thanks
