### ISSUE TITLE
Ignored unknown option { editorconfig: true }

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#6176]
**Environments:**
- Prettier Version: 1.17.1
- Running Prettier via: CLI
- Runtime: 11.14.0
- Operating System: macOS Mojave

**Steps to reproduce:**

I put `editorconfig: true` in my `.prettierrc.js`

```js
module.exports = {
	tabWidth: 4,
	useTabs: true,
	semi: false,
	singleQuote: true,
	trailingComma: 'es5',
	bracketSpacing: false,
	printWidth: 120,
	editorconfig: true, // <-------------- here
	arrowParens: 'avoid',
}
```

**Expected behavior:**

Should it work?

The docs mention an editorconfig option here: https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options

Is that only for the API usage? Does it make sense to support that in prettierrc?

**Actual behavior:**

Says it is an unknown option.

**Comment by lydell** [comment]
When using the CLI, Prettier always reads .editorconfig if it exists. There is no option. The API function `prettier.resolveConfig` has an `editorconfig: boolean` option, yes.
