### ISSUE TITLE
Hash sign stripped in markdown titles

### ISSUE THREAD

**Issue by mderazon** [prettier/prettier#6177]
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABABQE4QObYCGAtsQJZR7oA2hlAroXnAM4A6UHqGAwqh1wwApQgDdCLMNjIAHGCAA0ICHLLQWyUIWy4A7pm0INKMRDIATRSABGRMAGs4MAMozCYCnmQxs9OEoALGGJqAHUAsngWNzA4ZyNIslFIgE9kcBYNJQoWOGwYHCZiQmQAM0JqXKUAKxYADwAhO0cXEjgAGQo4MoqqkFq6509qOABFegh4Hsr-EDdsXOx04ux7cwhdKCsZaVhQixgA5AAOAAYlHYhc0KIZdJ3WPNFupQBHCfgcFWMQCQBaKBwODmYFWbBwd5kcGFPDFaZ9XLkby+WYsYZjD7dJDlGZKGCEaz7cyHZAAJjxRDI1E8PAgpBKKCg0BeIHouQAKgTjDjcgBfXlAA)
```sh
--parser markdown
```

**Input:**
```markdown
# Programming languages

## C#

## Javascript
```

**Output:**
```markdown
# Programming languages

## C

## Javascript

```

Markdown parser strips the hash sign (#) when it comes in a title.

**Comment by j-f1** [comment]
I think this could be because markdown allows hashes placed at the end of a header to “close” the header without being shown, and it doesn’t require the number to match the magnitude of the header.
