### ISSUE TITLE
Update remark: print lists

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#6180]
`remark-parse@6` includes a lot of fixes, like the fix for #6177 

But there was a significant change in lists, they don't include the `loose` property anymore, and include now a `spread`, which have different semantics.

See: https://github.com/remarkjs/remark/commit/aab3c3e705aafef79d9237ea3f2355e8fae9fbaa

For example, remark prints like this:

```markdown
<!-- input -->
- a

  - a
  - a
- b
  - b

  - b

- c
  - c

    c
  - c

<!-- output -->
-   a

    -   a
    -   a

-   b

    -   b

    -   b

-   c

    -   c

        c
    -   c
```

WDYT?

cc @ikatyang

**Comment by ikatyang** [comment]
Context: remarkjs/remark#364

We probably have to think of a way to get the `loose` property back. Here's what we'll probably get if there is only `loose`/`spread` information available, and the output from `loose` looks better to me.

- input
  ```md
  - a
  
    - a
    - a
  - b
    - b
  
    - b
  
  - c
    - c
  
      c
    - c
  ```
- output (with `loose` information available)
  ```md
  - a
  
    - a
    - a
  
  - b
  
    - b
  
    - b
  
  - c
  
    - c
  
      c
  
    - c
  ```
- output (with `spread` information available)
  ```md
  - a
  
    - a
    - a
  - b
    - b
  
    - b
  
  - c
    - c
  
      c
    - c
  ```

**Comment by duailibe** [comment]
@ikatyang Thanks for your input.. I didn't know exactly what `loose` meant, now I think I can get it to work then :-)

**Comment by duailibe** [comment]
@ikatyang Do you think this is too hackish? Do you have a better idea on how to solve this?

```js
function looseItems() {
  const self = this;
  const proto = this.Parser.prototype;
  const originalList = proto.blockTokenizers.list;

  function fixListNodes(value, node, parent) {
    if (node.type === "listItem") {
      node.loose = node.spread || value.charAt(value.length - 1) === "\n";
      if (node.loose) {
        parent.loose = true;
      }
    }
    return node;
  }

  proto.blockTokenizers.list = function list(realEat, value, silent) {
    function eat(subvalue) {
      const realAdd = realEat(subvalue);

      function add(node, parent) {
        return realAdd(fixListNodes(subvalue, node, parent), parent);
      }
      add.reset = function(node, parent) {
        return realAdd.reset(fixListNodes(subvalue, node, parent), parent);
      };

      return add;
    }
    eat.now = realEat.now;
    return originalList.call(this, eat, value, silent);
  };
}
```

**Comment by duailibe** [comment]
@ikatyang Also, what do you think we should do about spec updates? We should probably the tests in `markdown_spec`, some of them are "deprecated", e.g.:

```md
-   foo

    notcode

-   foo


    code
```

None of those are `code`, this is the updated version:

```md
-   foo

    notcode

-   foo

<!-- -->

    code
```

**Comment by ikatyang** [comment]
> Do you think this is too hacky? It works, but I'm not sure it's the best way to solve this. Do you have a better idea?

As long as it works and it does not look too complex, it should be fine. I don't have a better idea but maybe @wooorm could provide some suggestions.

@wooorm https://github.com/prettier/prettier/issues/6180#issuecomment-499498432 is a potential solution for https://github.com/remarkjs/remark/pull/364#issuecomment-428307268, do you have any suggestion for the implementation?

---

> What do you think we should do about spec updates?

I think we should always use the example from the latest spec as spec tests, but we could move those deprecated spec tests to normal tests to track their changes (or we could simply remove them.)

**Comment by duailibe** [comment]
@ikatyang Thanks!

**Comment by wooorm** [comment]
This issue does not include what you’d want to print: the expected output. Maybe it’s a good idea to not focus on getting exact previous behaviour back, but rather focus on a what style makes sense (which could be previous behaviour, but could also be something different?)

**Comment by duailibe** [comment]
@wooorm we're open to suggestions!

**Comment by wooorm** [comment]
Well I kinda like remark’s current behaviour 😉🤷‍♂ It made more sense.

**Comment by saramarcondes** [comment]
Is there any effort being put behind updating remark-parse right now? Prettier is currently pinned to `5.0.0`, however they've have released several versions of `remark-parse` since. [There](https://github.com/prettier/prettier/issues/4369) are [several](https://github.com/prettier/prettier/issues/7695) [tickets](https://github.com/prettier/prettier/issues/6177) that could be potentially closed due to fixes in remark that issues in Prettier were blocked on.

**Comment by fisker** [comment]
I have tried to update the parser before, failed.

**Comment by saramarcondes** [comment]
@fisker Do you have any comments about what was left over with that PR? It seems like there were still some big changes in how lists were being reprinted...

**Comment by thorn0** [comment]
@saramarcondes The Markdown support overall has been on the back burner for some time now. The current contributors focus on other areas, and Markdown waits for someone to adopt it.

**Comment by fisker** [comment]
@saramarcondes Right, list print is the tricky part, and seems I was on the wrong direction. You can try this https://github.com/prettier/prettier/issues/6180#issuecomment-499498432 . Good luck.

**Comment by thorn0** [comment]
A related question about Markdown lists. Do I understand correct that the behavior reported in #8004 is intended and not a bug? Do we want to keep it?
