### ISSUE TITLE
[Glimmer] Unwanted line breaks inserted between TextNodes and MustacheStatements

### ISSUE THREAD

**Issue by GavinJoyce** [prettier/prettier#6184]
**Prettier pr-6178** (I'm using this as https://prettier.io/playground doesn't seem to include glimmer)
[Playground link](https://deploy-preview-6178--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeADgPgJoQK4AEeAznAE5QCGAtnAQJbEEACwwVtAvp6gPRYAdKBkwAJegTYAzemWIwAcjTjdJwADaV5Srj36YQAGhAR0MetGLJQlMmQgB3AAq2EVlJQBuEegBMjIABGZJRgANZwMADK6KH0UADmyDBkeHDGABYw1OoA6hn08MSxYHBRboX0noUAnsjgxFbG8aRkME4hCdSUyFKU6qTGAFbEAB4AQiHhkVHKADLxcL39gyAjo1HxCepwAIp4EPDLA+kgsXLk9dv01LRkAehk8TC5fjAZyAAcAAzGjxCkXIhdD1R5wVqeJbGACOB3gHVM7hAWgAtFA4HBfJiAmQ4LDZHAOpQuj0kH0TsZSNR6MlUqdiFsdvtDksyStTjBKIFXr53sgAEzGFKUejqLYAYQgt1JICg0ChIBIcAAKlz3OTSNwgA)
```sh
--parser glimmer
```

**Input:**
```hbs
<p>Your username is @{{name}}</p>
<p>Hi {{firstName}} {{lastName}}</p>
```

**Output:**
```hbs
<p>
  Your username is @
  {{name}}
</p>
<p>
  Hi
  {{firstName}}
  {{lastName}}
</p>
```

**Expected behavior:**

I think this is the desired output:

```hbs
<p>
  Your username is @{{name}}
</p>
<p>
  Hi {{firstName}} {{lastName}}
</p>
```

**Comment by GavinJoyce** [comment]
We seem to be dropping `TextNode`s at some point.

`<p>Hi {{firstName}} {{lastName}}</p>` 

[AST Explorer](https://astexplorer.net/#/gist/b128d5545d7ccc52400b922f3b5010b4/3b78df0ed1ee6d72113a1fe2b10aa080a18dc6cc) gives 4 nodes:

<img width="1434" alt="Screen Shot 2019-06-06 at 11 20 58" src="https://user-images.githubusercontent.com/2526/59025948-3a17ac00-884d-11e9-9481-cfe8b7c764d0.png">

[Prettier seems to only have three](https://deploy-preview-6178--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeADgPgBIEsAEwwAZrgE4DOMAcgIYC2cAvk4cADa1V2MuoD0WEABoQEdDFzQKyULTJkIAdwAK8hDJS0AbhFwATESABGZWmADWcGAGV053FADmyGGQCucUQAsY9dgDq3rjwFPZgcDYaIbjaIQCeyOAUMqKOFHBkMCpmTvS0yMS07BmiAFYUAB4AQmaW1jYMcAAyjnCFxaUgFZU2jk7scACK7hDwHSVeIPaUmUkDuPSMZEboZI4wAQYw3sgAHAAMomsQGQFm6ElrcBlk2u2iAI6j8DnimiBcALRQcHD6-yMZDgz3IcBytDyBSQRUmogy9Fwrg8Uwo-UGIzG7RhnSmMFoxi2+h2yAATKI3LRcOx+gBhCBLaEgKDQB4gdwZAAqBM0sIyLCAA):

```
"children": [
        {
          "type": "TextNode",
          "chars": "Hi ",
          "loc": {
            "source": null,
            "start": { "line": 1, "column": 3 },
            "end": { "line": 1, "column": 6 }
          }
        },
        {
          "type": "MustacheStatement",
          "path": {
            "type": "PathExpression",
            "original": "firstName",
            "this": false,
            "parts": ["firstName"],
            "data": false,
            "loc": {
              "start": { "line": 1, "column": 8 },
              "end": { "line": 1, "column": 17 }
            }
          },
          "params": [],
          "hash": {
            "type": "Hash",
            "pairs": [],
            "loc": {
              "source": "(synthetic)",
              "start": { "line": 1, "column": 0 },
              "end": { "line": 1, "column": 0 }
            }
          },
          "escaped": true,
          "loc": {
            "source": null,
            "start": { "line": 1, "column": 6 },
            "end": { "line": 1, "column": 19 }
          }
        },
        {
          "type": "MustacheStatement",
          "path": {
            "type": "PathExpression",
            "original": "lastName",
            "this": false,
            "parts": ["lastName"],
            "data": false,
            "loc": {
              "start": { "line": 1, "column": 22 },
              "end": { "line": 1, "column": 30 }
            }
          },
          "params": [],
          "hash": {
            "type": "Hash",
            "pairs": [],
            "loc": {
              "source": "(synthetic)",
              "start": { "line": 1, "column": 0 },
              "end": { "line": 1, "column": 0 }
            }
          },
          "escaped": true,
          "loc": {
            "source": null,
            "start": { "line": 1, "column": 20 },
            "end": { "line": 1, "column": 32 }
          }
        }
      ],
```

**Comment by GavinJoyce** [comment]
We should probably upgrade `@glimmer/syntax`. We're on `0.30.3`, the current version is `0.41.0`

**Comment by GavinJoyce** [comment]
oh, it seems that we're currently removing white space nodes in the parser:

https://github.com/prettier/prettier/blob/3c5553cc8e7cf1dcff33f0b2796ee0ad141dd2f6/src/language-handlebars/parser-glimmer.js#L4-L22

**Comment by duailibe** [comment]
@GavinJoyce (re: playground) the Glimmer printer is not officially released yet because it still has lots of bugs, so it's not complete.

Re: space nodes, looks like here's the context for this: https://github.com/prettier/prettier/pull/3534#issuecomment-353781985

**Comment by GavinJoyce** [comment]
Thanks for the info @duailibe.

I'm still finding my bearings in prettier, I believe the solution to this issue is to stop stripping whitespace nodes and to replace this:

https://github.com/prettier/prettier/blob/3270ebf6f04be6cdc0b10aa18d0ffb3113d8acb8/src/language-handlebars/printer-glimmer.js#L86

With something similar to this which is more aware of sibling nodes and is more sophisticated:

https://github.com/prettier/prettier/blob/3270ebf6f04be6cdc0b10aa18d0ffb3113d8acb8/src/language-css/printer-postcss.js#L845-L901

**Comment by duailibe** [comment]
@GavinJoyce 

Feel free to do any changes you wish. What we do is to get a good set of code samples as test suite, and work on it until it prints everything right.

I'm not familiar with Glimmer/Ember/Handlebars, but I'm happy to try and help with anything you need. I believe it's smart to take advantage of the work done in HTML printer.

**Comment by GavinJoyce** [comment]
Thanks for the offer of help @duailibe, I'm working on a fix here: https://github.com/prettier/prettier/pull/6186

**Comment by GavinJoyce** [comment]
https://github.com/prettier/prettier/pull/6186 is ready for review
