### ISSUE TITLE
Airbnb Eslint and prettier conflict 

### ISSUE THREAD

**Issue by tajpouria** [prettier/prettier#6187]
Here's a simple User model as you know "this" keyword cannot be used in arrow function but  Airbnb "prefer-arrow-function" force prettier to turn es5 function to arrow function and it will cause a serious bug in the application:

BEFORE USING PRRETIER
```javascript 
const mongoose = require('mongoose');
const bcrypt = require('bcrypt');

const userSchema = new mongoose.Schema({
  email: String,
  password: String,
});
// here is conflict 
userSchema.pre('save', function (next) {
  const user = this;
  return bcrypt.genSalt(10, (saltErr, salt) => {
    if (saltErr) return next(saltErr);
    return bcrypt.hash(user.password, salt, (hashErr, encrypted) => {
      if (hashErr) return next(hashErr);

      user.password = encrypted;
      return next();
    });
  });
});

module.exports = mongoose.model('User', userSchema);
```
AFTER USING PRRETIER
```javascript
userSchema.pre('save', next => bcrypt.genSalt(10, (saltErr, salt) => {
  if (saltErr) return next(saltErr);
  return bcrypt.hash(user.password, salt, (hashErr, encrypted) => {
    if (hashErr) return next(hashErr);

    user.password = encrypted;
    return next();
  });
}));
```

```json
 "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.13.0",
    "html-webpack-plugin": "^3.2.0",
```

**Comment by duailibe** [comment]
Hi @tajpouria 

It seems there's some confusion, Prettier will never modify your code to change function expressions to arrow functions.

Here's what Prettier does to your code:

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbaBzCCNOTAXkwCc4BHAVwEsqAKAclygKLhYEoBuADpRIUDJgBGYCgE8ADlnJU6jOK0kz5vQVCEixtYhQDKYABZxsAQzKYocAO458hYgDoT5q02BDMmC5b0ADZImEYwFPQcADS+mLKWaGj2EBQAJqHhkTFCAL78QgD0hZjmVJj0aJgiAGZB9GBYQgZwxmYBrrLMLGiWAG7c0Zg1tMIw9NCYTHYAHjA8mD5QfnpYLRQ2MKaV2n5UMLQUy+pyMK54CEaWQTBMAIwADENMvTcAohQUQ6-zZAB8izifnoNSmPw+FAW+0Oy1mt3BnwKyz8lDgByOEikp1cpkSpiY606iWSqTS32uMGeuLQpghQwQWPkcDSC1IAKWKJRIKm1NpiNR6NhcDmTF5EKRQJRhISSRS6RsDI08DSu05AphtmFtyRnPyqr1eQlUFwaVoQTgrmFslSMCq5HYnDcJrgQVYAFVDCwhusPAF+CBoiAIPIJqJkKBLJ8IPYAAqRhBoZAgfoQehpAMgcQUSxgADWaKMCTAUTwyAitDggdMMGwQQA6tt4Ggi3AjAn6OM+h3pEmwEkM1FDDAY9m8FZkDVrsRAwArNAzABC2bzBcs2DgABkonAJ1PKyA5zMjCXzQBFWgQeC7oLTkAJCiGJPiSziaRBaAZrpRGB1tNbZAABxPHeFBcHW2ayEmXRwIYAwZnQl5wCOwaJigiQALR2MyzIZkoDBUCOlhjpY163sQ2D0GWFAVoGaAnnA56IaR+4wC+v5pP+SAAEyBhEgT1BwADCEDYOOKBQNAO6Bi0AAqL6oZON5wLkuRAA)
```sh
--parser babylon
```

**Input:**
```jsx
const mongoose = require('mongoose');
const bcrypt = require('bcrypt');

const userSchema = new mongoose.Schema({
  email: String,
  password: String,
});
// here is conflict 
userSchema.pre('save', function (next) {
  const user = this;
  return bcrypt.genSalt(10, (saltErr, salt) => {
    if (saltErr) return next(saltErr);
    return bcrypt.hash(user.password, salt, (hashErr, encrypted) => {
      if (hashErr) return next(hashErr);

      user.password = encrypted;
      return next();
    });
  });
});

module.exports = mongoose.model('User', userSchema);
```

**Output:**
```jsx
const mongoose = require("mongoose");
const bcrypt = require("bcrypt");

const userSchema = new mongoose.Schema({
  email: String,
  password: String
});
// here is conflict
userSchema.pre("save", function(next) {
  const user = this;
  return bcrypt.genSalt(10, (saltErr, salt) => {
    if (saltErr) return next(saltErr);
    return bcrypt.hash(user.password, salt, (hashErr, encrypted) => {
      if (hashErr) return next(hashErr);

      user.password = encrypted;
      return next();
    });
  });
});

module.exports = mongoose.model("User", userSchema);

```

It's something else that is turning your functions into arrow functions.

**Comment by tajpouria** [comment]
thank you for the response, as I mentioned I used Airbnb eslint rules but playground link you sent me not  using eslint-prettier setup also I'm using the following option on my VSCode :
```json
"[jsonc]": {
    "editor.defaultFormatter": "eslint.prettier-vscode"
  },
```
```javascript
userSchema.pre('save', function (next) {
// I 'm used "const user = this" as quick fix cuz prettier turn it to arrow function when I remove this line.
  return bcrypt.genSalt(10, (saltErr, salt) => {
    if (saltErr) return next(saltErr);
    return bcrypt.hash(user.password, salt, (hashErr, encrypted) => {
      if (hashErr) return next(hashErr);

      user.password = encrypted;
      return next();
    });
  });
});
}));
```

**Comment by duailibe** [comment]
@tajpouria 

> I used Airbnb eslint rules but playground link you sent me not using eslint-prettier setup

I understand, I just showed you that's __not__ Prettier who's changing your code, so there's not much we can do. I suggest disabling the lint rules that are breaking your code.
