### ISSUE TITLE
Overrides not applied to dotfiles

### ISSUE THREAD

**Issue by felixfbecker** [prettier/prettier#6193]
**Environments:**
- Prettier Version: 1.18.0
- Running Prettier via: CLI 
- Runtime: 
- Operating System: macOS 

**Steps to reproduce:**

.prettierrc.json
```json
{
    "tabWidth": 4,
    "printWidth": 120,
    "semi": false,
    "trailingComma": "es5",
    "singleQuote": true,
    "overrides": [
        {
            "files": "*.json",
            "options": {
                "tabWidth": 2
            }
        }
    ]
}
```

I also tried with `**/*.json`, `**.json`, `**/*.*.json`, `*.*.json`.

**Expected behavior:**
`prettier .prettierrc.json --write` should format the file with 2 spaces. 

**Actual behavior:**
It formats the filee with 4 spaces.

Logs:
```
> npx prettier ./.prettierrc.json --write --config ./.prettierrc.json --loglevel=debug
[debug] normalized argv: {"_":["./.prettierrc.json"],"color":true,"editorconfig":true,"write":true,"config":"./.prettierrc.json","loglevel":"debug","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] load config file from './.prettierrc.json'
[debug] loaded options `{"tabWidth":4,"printWidth":120,"semi":false,"trailingComma":"es5","singleQuote":true}`
[debug] applied config-precedence (cli-override): {"printWidth":120,"semi":false,"singleQuote":true,"tabWidth":4,"trailingComma":"es5"}
.prettierrc.json 25ms
```

Note how `tabWidth: 4` is used.

**Comment by duailibe** [comment]
Fixed in 1.18.1

**Comment by duailibe** [comment]
This is actually a breaking change. I'll have to revert this change and I'll release it again in 2.0

See #5813

**Comment by felixfbecker** [comment]
@duailibe but it used to behave like this I'm pretty sure because I had all my JSON dot files formatted before.

Also, isn't Prettier's versioning policy to not consider files being formatted differently (or more files being formatted, when a new file type is being supported for example) as a non-breaking change?

**Comment by duailibe** [comment]
> Also, isn't Prettier's versioning policy to not consider files being formatted differently (or more files being formatted, when a new file type is being supported for example) as a non-breaking change?

Yes, but this is not the case here. This is a change in the configuration contract.

**Comment by felixfbecker** [comment]
So a) I still believe it used to behave this way - but b), how is adding a new parser then not a breaking change? Because the only observable difference for both is that the set of files being formatted for a given glob increased.

**Comment by duailibe** [comment]
It's really strange that it used to behave this way, if you check the blame, you'll see that the commit before mine affecting this line was the commit the introduced this feature https://github.com/prettier/prettier/blame/master/src/config/resolve-config.js#L161.

As for b), because of the way our CLI was built, everyone needs to run Prettier with the "exact" match `prettier --write foo/**/*.{js,json,jsx,graphql}`, so we haven't been too strict about that (even though it is technically a breaking change). When we introduce the ability for walking recursively in folders (i.e. `prettier --write .`) we need to mark new extensions as breaking changes as well.

**Comment by felixfbecker** [comment]
But before, it was possible to explicitly include dotfiles, with e.g. `*.*.prettierrc` (see the issue). No glob works anymore to include them anymore, it's like they're invisible to Prettier? It's likely not related to the `dotfiles` option

**Comment by felixfbecker** [comment]
Another idea, can we maybe have a `dotfiles` option? Then in 2.0 it can be made the default
