### ISSUE TITLE
Epic: Trailing commas in TS/Flow

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#6198]
This is an old problem and I thought I had an issue open to discuss this topic, but we should make a decision on this matter:

How do we handle trailing commas in different versions of Flow/TS?
Should we add `flowXXX` and `tsX.X` options?
Should we always support new trailing commas in `"all"` and treat `"es5"` as `"none"`?

cc @prettier/core

**Comment by duailibe** [comment]
Issues raised on this topic: #6197 #3722

**Comment by evilebottnawi** [comment]
> Should we add flowXXX and tsX.X options?

I think yes, we planned same for php plugin, sometimes languages change syntax

> Should we always support new trailing commas in "all" and treat "es5" as "none"?

To avoid breaking code we should considered:
- `all` and `tsX.X`/`flowXXX` together. 
- with `none` no problems
- `es5` was bad idea, id on't know here solution, maybe apply trailing comma for lower level (i.e. apply commas only for lower ts/flow version)

**Comment by ikatyang** [comment]
- https://github.com/prettier/plugin-php/issues/964#issuecomment-465558448
> - Personally, I think we should replace `--trailing-comma <none|es5|all>` with `--[no-]trailing-comma`/`--js-trailing-comma es5`, but unfortunately there's no backward-compatible way to do it in the CLI since string flags would suddenly become part of filenames.
> - PHP plugin: any option that wants to extend the existing one should have their own name, `--php-trailing-comma` for example. (Since we do support sub-language formatting (`embed`), it's not possible to use the same name with different option.)

- https://github.com/prettier/plugin-php/issues/964#issuecomment-465563804
> I meant the php-specific value (`php5`, `php7.2`) should have their own name (`--php-trailing-comma`) but the general value (`all`, `none`) can still be used as before (`--trailing-comma`). The `--php-trailing-comma` should take precedence over `--trailing-comma` in this plugin, something like:
> 
> ```ts
> function getPhpTrailingCommaValue(options): "all" | "php5" | "php7.2" | "none" {
>   if (options.phpTrailingComma) return options.phpTrailingComma;
>   if (options.trailingComma === "es5") return "none";
>   return options.trailingComma;
> }
> ```

Same thing can be applied to TS/Flow as well.

**Comment by duailibe** [comment]
@ikatyang your solution sounds reasonable. I'll investigate that for 2.0

**Comment by kachkaev** [comment]
We can probably close this issue in favor of https://github.com/prettier/prettier/issues/11465

**Comment by nickmccurdy** [comment]
I just noticed #3722 is still open. Should that be included with Prettier 3?

**Comment by fisker** [comment]
Fixed by #14085
