### ISSUE TITLE
Unstable comments in import

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#620]
```js
import { a //comment1
//comment2
//comment3
as b} from "";
```

becomes ([online demo](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%20a%20%2F%2Fcomment1%5Cn%2F%2Fcomment2%5Cn%2F%2Fcomment3%5Cnas%20b%7D%20from%20%5C%22%5C%22%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D))

```js
import {
  a as //comment1
  //comment2
  //comment3
  b
} from "";
```

becomes ([online demo](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%5Cn%20%20a%20as%20%2F%2Fcomment1%5Cn%20%20%2F%2Fcomment2%5Cn%20%20%2F%2Fcomment3%5Cn%20%20b%5Cn%7D%20from%20%5C%22%5C%22%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D))

```js
import {
  a as //comment2 //comment1
  //comment3
  b
} from "";
```

becomes ([online demo](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%5Cn%20%20a%20as%20%2F%2Fcomment2%20%2F%2Fcomment1%5Cn%20%20%2F%2Fcomment3%5Cn%20%20b%5Cn%7D%20from%20%5C%22%5C%22%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D))

```js
import {
  a as //comment3 //comment2 //comment1
  b
} from "";
```

**Comment by rattrayalex** [comment]
how amusing

**Comment by vjeux** [comment]
2 -> 3 is a bug, we shouldn't have comment2 be attached as a trailing comment on the previous line, but as a leading comment on the next line
