### ISSUE TITLE
[Markdown] Some reference-style links are broken with proseWrap=always

### ISSUE THREAD

**Issue by Pavek** [prettier/prettier#6212]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdK6DaBGAukgAgHoAjAGwgHMiAmABmwHYBaOgTlZbAEMAnZgBbcwAawCWUSswBuY7jIhiwcZpAC2a7lAAmWGvgICYMAA4BnJESJq42uQDoAZhF7b76opFgIYRZ65s7bj8oYIBXMyIEIig4AHdI+iYiBhSAFiJuMjgAD3kefn9tZm5NAC9oZjMBCBMquD4wAUEIG3sjNTIsAFYDIjMYbhglIjFNSjhI8ioiAEFy6ABhPnsAKxNKAlRwMm4zC0cKIeZsxxgAbgIsmCRZ7LyCCQIYATgCAu30EAAaEFrh6BmZCgPi8CBxAAKfAQQJQ3Gkim0PxAJF4whEcBgAGUTMIJJRkDBeGE4L8OmQAOoCMTwMy45RYmE0sSyGAAT2Q4H2yIkZjgvBgELRlE0yEcWT5v1WZhyACE0aJMVjSnAADISOBiiWkkDSnJY-HZACKYQg8C1ZElIFxvD5vE5ml4Im04KgyJMvAkMApYm0L2Q2DodF+HogfIpaJMnKycW4bKBvwAjqb4ELarCQHtmLFbLZkbw4MmxAWhdwRdwLVa+WoxITiTqzIa4CazZqkOLLTqidwxGR8YtWqKUFBoJrfhE4AAVbgkWEdvkAXwXQA)
```sh
--parser markdown
--print-width 100
--prose-wrap always
```

**Input:**
```markdown


[1]: /blog/2017-09-07-car-hacking-via-voice-command
[2]: https://media.ford.com/content/fordmedia/fna/us/en/news/2017/01/04/alexa-car-ford-amazon-shop-search-home.html
[5]: /static/images/blog/AmazonCar.jpg "class:float-left; alt:Alexa in the car"

```

**Output:**
```markdown
[1]: /blog/2017-09-07-car-hacking-via-voice-command
[2]:
  https://media.ford.com/content/fordmedia/fna/us/en/news/2017/01/04/alexa-car-ford-amazon-shop-search-home.html
[5]: /static/images/blog/AmazonCar.jpg "class:float-left; alt:Alexa in the car"

```

**Expected behavior:**
```markdown
[1]: /blog/2017-09-07-car-hacking-via-voice-command
[2]: https://media.ford.com/content/fordmedia/fna/us/en/news/2017/01/04/alexa-car-ford-amazon-shop-search-home.html
[5]: /static/images/blog/AmazonCar.jpg "class:float-left; alt:Alexa in the car"

```

There should be no line-break after `[2]: `. This breaks that link formatting in my case.

**Comment by lydell** [comment]
This was added on purpose in #3531.

> This breaks that link formatting in my case.

It does? What markdown tooling do you use?

---

Personally, I'd prefer never breaking these references. It doesn't help in any way IMO. And it makes sorting them easier.

**Comment by duailibe** [comment]
FTR this is correct per CommonMark spec

**Comment by Pavek** [comment]
I understand that per spec it is correct. Regarding implementation that still cannot parse it, here's the info:
 - marked/0.3.12 - [broken](https://marked.js.org/demo/?text=%5BLink%5D%5B1%5D%0A%0A%5B1%5D%3A%0A%20%20http%3A%2F%2Fdaringfireball.net%2Fprojects%2Fmarkdown%2F%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.3.12)
- marked/0.3.13 - [fixed](https://marked.js.org/demo/?text=%5BLink%5D%5B1%5D%0A%0A%5B1%5D%3A%0A%20%20http%3A%2F%2Fdaringfireball.net%2Fprojects%2Fmarkdown%2F%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.3.13)

**Comment by evilebottnawi** [comment]
@Pavek looks it was fixed in future `marked` release, so prettier don't break code, i think we can close issue
