### ISSUE TITLE
Valid TS not parsed: `this` param `Unexpected keyword` in typescript

### ISSUE THREAD

**Issue by ktilcu** [prettier/prettier#6214]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEEAtgOb4AUMAFjgM5K0wBOOUJANPqhBA86yQCUfFm3zAAOlHz4mcGOibTqdfAGouPANxSAviHYgIAB1zRayUAEMmTCAHcACjYQWUVgG4QcAEwMgAIyYrMABreQBlYxCBZGZ0OEMqGCIAGwB1GnhaaLA4CNccXA8igE9kcFoLQ1ZaOCYYR2CSIitkVCtUusMAK1oADwAhYLDIqyI4ABlWOHbO7pA+-oiBVLgARXQIeDmuxJBopjqmCoCrANLU6H9jURh032pkAA4ABkNbiDr04OMK27gxw8s0MAEctvAmiY3CArLQALRQOBwHwo-xycE4ORNKwtNpIDp7Qx1Ig4OJMBLE1YbCGzAnzfYwc4PHxPJAAJkMzCsOFSAgAwsRWhUoNAQSB0HUACrnNyEuq6XRAA)
```sh
--parser babylon
```

**Input:**
```tsx
function omg (this:string, foo:string):string {
  return this + foo;
}
```

**Output:**
```tsx
SyntaxError: Unexpected token (1:10)
> 1 | function (this:string, foo:string):string {
    |          ^
  2 |   return this + foo;
  3 | }
```

**Expected behavior:**
Should format valid typescript.

https://www.typescriptlang.org/play/#src=function%20omg%20(this%3Astring%2C%20foo%3Astring)%3Astring%20%7B%0A%20%20return%20this%20%2B%20foo%3B%0A%7D

**Comment by lydell** [comment]
Is this a relatively new TypeScript feature?

**Comment by sosukesuzuki** [comment]
You should probably set `--parser typescript`.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEEAtgOb4AUMAFjgM5K0wBOOUJANPqhBA86yQCUfFm3zAAOlHz4mcGOibTqdfAGouPANxSAviHYgIAB1zRayUAEMmTCAHcACjYQWUVgG4QcAEwMgAIyYrMABreQBlYxCBZGZ0OEMqGCIAGwB1GnhaaLA4CNccXA8igE9kcFoLQ1ZaOCYYR2CSIitkVCtUusMAK1oADwAhYLDIqyI4ABlWOHbO7pA+-oiBVLgARXQIeDmuxJBopjqmCphS4zhaMBZTf2NRGHTfamQADgAGQ3uIOvTg4wq90u9Q8s0MAEctvAmiY3CArLQALRQOBwHxo-xySE4ORNKwtNpIDp7Qx1Ig4OJMBKk1YbKGzInzfYwKwBJ4+F5IABMhmYVhwqQEAGFiK0KlBoGCQOg6gAVVluYl1XS6IA)

**Comment by lydell** [comment]
@sosukesuzuki Thanks, I missed that.

@ktilcu Do you have `"parser": "babylon"` in your .prettierrc by any chance? If so remove that: https://prettier.io/docs/en/configuration.html#setting-the-parser-docs-en-optionshtml-parser-option

**Comment by ktilcu** [comment]
@lydell @sosukesuzuki Thanks! I had 2 things working against me. Our repo had a really old version of prettier installed. I also didn't know the parser selecting bit didn't really happen on the web playground.  Everything looks good now!
