### ISSUE TITLE
Idea "Non Breaking Line Builder"

### ISSUE THREAD

**Issue by Janther** [prettier/prettier#6216]
My scenario is that I have a body that should be followed by a **hardline** if it fit's in a **single line** and should be enclosed in brackets and keep the next document in the same line if the body breaks into **multiple lines**. 

At the moment I have the following code.
```Javascript
group(
  concat([
    ifBreak('{', ''),
    indent(concat([line, path.call(print, 'body')])),
    ifBreak(concat([line, '}  ']), hardline)
  ])
)
```
so if the group doesn't break, the last `ifBreak` will print a hardline which will force a break in the parent group which will reevaluate each `ifBreak`.

I tried printing `'\n'` but I lose the indentation.

I propose a new line builder that won't force a break in the parent group while keeping the indentation.
```Javascript
group(
  concat([
    ifBreak('{', ''),
    indent(concat([line, path.call(print, 'body')])),
    ifBreak(concat([line, '}  ']), nonbreakingline)
  ])
)
```

**Comment by j-f1** [comment]
Assuming the contents of the block always break onto multiple lines, this should work:

```js
group(
  concat([
    ifBreak('{', ''),
    hardline,
    indent(concat([hardline, path.call(print, 'body')])),
    hardline,
    ifBreak(concat(['}  ']), '')
  ])
)
```

**Comment by duailibe** [comment]
> Assuming the contents of the block always break onto multiple lines

I don’t think that’s the case

**Comment by Janther** [comment]
Not the case.

Here is the case:
I'm contributing to [prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity) and the style guide has the following sugestion regarding single line statements:

For control structures whose body contains a single statement, omitting the braces is ok if the statement is contained on a single line.

Yes:
```Solidity
if (x < 10)
    x += 1;
```

No:
```Solidity
if (x < 10)
    someArray.push(Coin({
        name: 'spam',
        value: 42
    }));
```

So my solution was to track if the statement breaks and just in that case adding the brackets.
```Solidity
if (x < 10)
    x += 1;

if (x < 10) {
    someArray.push(Coin({
        name: 'spam',
        value: 42
    }));
}
```

**Comment by Janther** [comment]
in the previous example, I need the hardline for the `else`:
```Solidity
if (x < 10) x += 1;
else return false;

if (x < 10) {
    someArray.push(Coin({
        name: 'spam',
        value: 42
    }));
} else return false;
```

so when it breaks, it needs to stay in the same line, if it doesn't break it needs a new line.

**Comment by thorn0** [comment]
`ifBreak`with `groupId` placed after the group [does this](https://deploy-preview-10183--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBtAOlABF9ICSAYlgBSRQAmAljFdAJR4A0mOA5gE4QCuADiaioAzAEIc4AQwDWJPFmDNcIPPSZYqlBDAEAbDXDV4ARhAoBPLCfOXTFq3ds3zAbjwBdem7ULsOdRSQlAEVmViwAX1Uw4TFJGVQACwkOCj0oAyVw9zVuTSF9Cm8sTh5efADguUiWXySUtINMNxAmEAheWmgAZ2RQZK4AdwAFZIQelAkdAYkzHtajDgkwKTgYAGVeJY02ZBgObgMQOABbIzgKCnOAGQkoNm4JNjhCCA5jiRhaO+QQCW4YCAtEAJGDHHQAdQSNDgXU2YDgazGNCoADcaGYfmAunMQBounAODAhos2O9kEJJvjWgArLoADzESxW6wkxzgV305Mph1pdLW2x0cCC3Ag8C5OipIE2HHxHB+FAgYAAtHA6bwdK8CUDeBwNDBwVQKDAEsgACwABlaOog+PBi14Px1MIJKLgQIAjiL4MT2uNfl0lelzucgeJPVRxMTHmSkBSJYd8ccqLt9gmBUKvW7Y9zWjAJEYDUaTUgAEy5xZUNJsADCEGOMaOXQArEDuPiACr58ZxyUog74TSwNZgXUdACClDWMDMgvF+PC4SAA).

BTW, we've recently updated [commands.md](https://github.com/prettier/prettier/blob/main/commands.md). It was somewhat incomplete. Have a look.
