### ISSUE TITLE
Less: detached rulesets collapse into one line

### ISSUE THREAD

**Issue by incompletude** [prettier/prettier#6218]
I have a  less mixin, and prettier formats it perfectly:

```
.on-tablet-landscape(@rules) {
  @media @media-tablet-landscape {
    @rules();
  }
}
```

Then I use this mixin inside my less files, and prettier messes it up badly.

```
html {
  font-size: 55%;

  .on-tablet-landscape({
    font-size: 62.5%;
    background: red;
  });
}
```

Ends up being:

```
html {
  font-size: 55%;

  .on-tablet-landscape({font-size: 62.5%; background: red;});
}
```

Any sugestions?

**Comment by evilebottnawi** [comment]
Please use issue template

**Comment by andre-lima** [comment]
@evilebottnawi I have this same issue with my media query mixin.

On shorter mixin uses, i get everything inlined:
```
.mq(desktop-up, {display: block;});
```
Where I'd prefer to have something like this:
```
.mq(desktop-up, {
    display: block;
});
```

On longer mixin uses, i get this:
```
  .mq(
    desktop-only,
    {--carousel-arrows-spacing: var(--space-xs) ; background-color: red; font-size:
      111px;},
    other_param
  );
```
Where something like this would look better:
```
  .mq(desktop-only, {
       --carousel-arrows-spacing: var(--space-xs) ; 
       background-color: red; 
       font-size: 111px;
    }, 
    other_param);
```

Please let me know if you have some more information about this.
Thanks.

**Comment by thorn0** [comment]
Duplicate of #4524
