### ISSUE TITLE
Newline after assignment operator `=` on long line formatted to break print width rule

### ISSUE THREAD

**Issue by andrewlott** [prettier/prettier#6223]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOgIYBqcATgJ5FkXknWU1UAy0A5gGICuUYMG0AcngC2cAAQBeEemz4qs+vLqLSTKG07deUAcJwAjDFAAmACilYAlAG4AOlFtmZC2s7lKVarj35DRE2yMlMXEInVxcndw5PTW04PQMTMysQABoQCAAHLygsZFA8YmIIAHcABQKEXJQ8ADcIDENUkF1iPDAAazgYAGUMtoNmZBhidjg0tBhBABsAdUx4LD6wOG7KjB4a9dJkcCxctIMsEhhS1uZBPGQAMzwpo7SAKywADwAhVo6u7p8GAzhr273EBPZ7dAZTOAARXYEHgALuYxAfWIR2IO10eF0cCmTQyxAMMBmDXQyAAjAAGclpPEQI4zVoZHZ4uComr-NIARxh8FOmSqIDwWAAtFA4HBDOKmsQ4FyMNLTnhzpckDcEWkjoIMEMRoisOCodz-irAYiYJiiYYSUgAExpYZ4DBTAYAYQggguOyg0HZIHYRwAKpiqqqjgBfUNAA)
```sh
--parser babel
--print-width 100
```

**Input:**
```jsx
this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName = this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName.bind(this);

this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName = 
  this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName.bind(this);
```

**Output:**
```jsx
this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName = this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName.bind(
  this
);

this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName = this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName.bind(
  this
);

```

**Expected behavior:**
That the line would be broken up such that it does not break the `print-width` rule. Or at least doesn't change the style of lines that do obey the rule.

```jsx
this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName = 
  this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName.bind(this);

this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName = 
  this.aVeryVeryVeryVeryVeryVeryVeryLongFunctionName.bind(this);
```

**Comment by bakkot** [comment]
This is a duplicate of #2482, which no one has yet had a good idea how to fix.

**Comment by lydell** [comment]
Duplicate of #2482
