### ISSUE TITLE
End of line comment in template literal turns into invalid

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#623]
```js
`
${// $FlowFixMe found when converting React.createClass to ES6
ExampleStory.getFragment('story')}
`
```

turns into

```js
`
${ExampleStory.getFragment('story')} // $FlowFixMe found when converting React.createClass to ES6
`;
```

which changes the meaning since the comment is now part of the text of the template literal.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%60%5Cn%24%7B%2F%2F%20%24FlowFixMe%20found%20when%20converting%20React.createClass%20to%20ES6%5CnExampleStory.getFragment('story')%7D%5Cn%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by yamafaktory** [comment]
@vjeux How do you want the comment to be inserted then? As a leading one, completely before the template literal, or still inside the`${...}`?

**Comment by vjeux** [comment]
I don't really know, the way it was initially printed seems fine.

**Comment by yamafaktory** [comment]
This looks ok to me too. I pushed a minor commit in order to deal with trailing comments inside the template literal.
