### ISSUE TITLE
Incorrect behavior with Flow .map<type>

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#6230]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlPvfgE5wzqN0wAWORAdAA6MI-PqhxwANgBM+AWwCG-ADwBhSRIB8pUmMlSk+AGLjplALwaqtBg2at2VujYY59+XdN6uANNef1cGAk4Aw8pXkDg3yd-ADd5CXQQ-FIhAHdvKlQIMHQiAF9zSy4eXikWOEZZHCg4AH1IRNkoOsk4WQQyMMz0zOzconI-G3yAbmH8QvGofJBvEGFcaCJkUHlGdIAFdYQVlHlYiFc5kAAjRnkwAGsWAGV+S5qAc2QYRiT5zhhZCQB1bmIDzAcFuuxwuFi4IAnshwEQVvMakRKjBNhcngpkKgEsj5gArIgADwAQhdrnd5B0ADI1OBYnFwfFE27PYIARXQEHg9IkuJAD0YyMYsNO8lOkhOghqMF+ri4yAAHAAGeaCCDI34XfiwwRwIWxOnzACOnPgaOEexA8iIAFpanBylITswTThmGj5Bj5Dy+cjqq93oyQERWXAOVy6UhsbygzAxbKpPKkAAmeZveQ4CTPFQQWSYlBQaCGkB5OAAFTFe2jyPy+SAA)
```sh
--parser babel
```

**Input:**
```jsx
function test() {
    return this.props.fields.map<Cell>((field: Field) => {
      return {
        id: field.id,
        title: field.title,
        value: (row, {focus}) => this.determine_column_element(field, row, focus)
      };
    });
}
```

**Output:**
```jsx
function test() {
  return (
    this.props.fields.map <
    Cell >
    ((field: Field) => {
      return {
        id: field.id,
        title: field.title,
        value: (row, { focus }) =>
          this.determine_column_element(field, row, focus)
      };
    })
  );
}

```

**Comment by lydell** [comment]
Hi!

https://prettier.io/blog/2019/01/20/1.16.0.html#add-babel-flow-parser-5685-by-ikatyang

> Both the `babel` and `flow` parsers support Flow syntax by default, but there are a few
> edge cases where Flow syntax is ambiguous. By default, Babel’s Flow parser will parse the
> ambiguous code as regular JS, while the native Flow parser will parse it as Flow syntax.
> To address this issue, we added the `babel-flow` parser option, which uses Babel’s parser,
> but prefers Flow syntax when ambiguities arise.


You need to use either the `babel-flow` or `flow` parser for this case.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlPvfgE5wzqN0wAWORAdAA6MI-PqhxwANgBM+AWwCG-ADwBhSRIB8pUmMlSk+AGLjplALwaqtBg2at2VujYY59+XdN6uANNef1cGAk4Aw8pXkDg3yd-ADd5CXQQ-FIhAHdvKlQIMHQiAF9zSy4eXikWOEZZHCg4AH1IRNkoOsk4WQQyMMz0zOzconI-G3yAbmH8QvGofJBvEGFcaCJkUHlGdIAFdYQVlHlYiFc5kAAjRnkwAGsWAGV+S5qAc2QYRiT5zhhZCQB1bmIDzAcFuuxwuFi4IAnshwEQVvMakRKjBNhcngpkKgEsj5gArIgADwAQhdrnd5B0ADI1OBYnFwfFE27PYIARXQEHg9IkuJAD0YyMYsNO8lOkgAtKgJBA0idBDUYL9XFxkAAOAAM80EEGRvwu-FhgjgQtidPmAEdOfA0cI9iB5EQJbU4OUpCdmFacMw0fIMfIeXzkdVXu9GSAiKy4ByuXSkNjeeGYGLlVJVUgAEzzN7yHASZ4qCCyTEoKDQc0gPJwAAqYr2CeR+XyQA)
```sh
--parser babel-flow
```

**Input:**
```babel-flow
function test() {
    return this.props.fields.map<Cell>((field: Field) => {
      return {
        id: field.id,
        title: field.title,
        value: (row, {focus}) => this.determine_column_element(field, row, focus)
      };
    });
}
```

**Output:**
```babel-flow
function test() {
  return this.props.fields.map<Cell>((field: Field) => {
    return {
      id: field.id,
      title: field.title,
      value: (row, { focus }) =>
        this.determine_column_element(field, row, focus)
    };
  });
}

```

**Comment by thorn0** [comment]
Another option is to add the directive `// @flow` ([playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwDYQDuAOlDgK5RgwCW0G8AzjABQCUGwpGPGATnBjk+UBgAsajAHQAHPhBnScNOHgAm0gLYBDGQB4AwqrwA+Fi2Wq1SDADEV6jgF4Tnbrx4ChIt6I+8aawxLdSlAgBp3fwYaGDw4GxC1KVo4uEi-aIA3bTxyBIwWeUJwzhwIMHJGAF9nVxgJaTVBOD5NGig4AH1IPM0oLtU4TQRWJNLi0vLKxjYo3mqAbnna5ahqkHCQBVpoRmRQbT5igAUjhH2UbSyIQM2QACM+bTAAa0EAZRkXjoBzZBgfHyWzEME0eAA6hImN8wHAPhdYjQsrEAJ7IcCMfZbDqMVowE7PX46ZA4XJ4rYAK0YAA8AELPN6fbQjAAyHTgpPJ6RA1JpHz+8QAiuQIPAuXgKSBvnw8XwMQ9tA9VPc5B0YBDAg1kAAOAAMWzkEDxEOeMgxcjgcqynK2AEdRfBCQpLiBtIwALSdODNNT3AQOmgCQnaYnaCVSvHtAFAnmMQVwEVizlIMmSnkwJWatTapAAJi2gO0NDwfwMEE0JJQUGgtpAVTgABUlZc03jqtUgA)).

**Comment by lydell** [comment]
@thorn0 Cool, I didn't know that!

**Comment by avalanche1** [comment]
Strangely enough, I have `//@flow strict` in that file, and Prettier still makes incorrect formatting.
Setting `parser: babel-flow` in `.prettierrc.yaml` alleviated the issue though. Thanks!
