### ISSUE TITLE
\u2139 is converted to 'i'

### ISSUE THREAD

**Issue by sharpart555** [prettier/prettier#6235]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoIaoC8qwAOlOugOSmkCuATAIwDMAnFUqlQO4AWAT1SkQtWo1ZsRGaADc4AJ3gATVDAjCQASxEB+KgBpy6AL4BuEAZAQADjC3QsyUHgUKIPAAquETlHgAbHjwBJysAIwU8MABrOBgAZRtorSgAc2QYBTo4Kz4YAFsAgHU+LXgsZLA4BN9yrVlygWRwLDDtbEUYTyi0grxkADNArFyQACssAA8AISjY+IS8ArgAGVS4TOyxyamE1LSAuABFOgh4IZGx5IVRhRbwvHC4AMsQGwVUmGKtZRg+ZAMAAMQKsHwgo2KURsLQ+cDu8jeAEczvAerY-CA8FgALRQOBwZSEt4KOAorSknp4PoDJDDAKjKyjApaLY5JkHI6nc6bJBZdkgGBPH5-AFIBhWLJ4LQBA4AYQgBX6LXhAFY3nRRgAVJ5+emjEwmIA)
```sh
--arrow-parens always
--jsx-bracket-same-line
--parser babel
--print-width 200
--single-quote
--trailing-comma es5
```

**Input:**
```jsx
  const a = {
    '\u2139': 'why "\\u2139" is converted to "i"?',
  };
```

**Output:**
```jsx
const a = {
  ℹ: 'why "\\u2139" is converted to "i"?',
};

```

**Expected behavior:**
```jsx
  const a = {
    '\u2139': 'why "\\u2139" is converted to "i"?',
  };
```

**Comment by bakkot** [comment]
For the same reason it [converts](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQB1cCuATAIwDMAnNgLzYAMA3CADQgQAOMAltAM7KgsmCAHcAClgT8U6VBC4ATFiABGmdGADWcGAGV2GrlADmyGJgJxWACxgBbADYB1a13i8DYOLqluuqNwBPZHBeflYjXjhMGDF1Yzt0ZAAzdAco1gArXgAPACF1LR1ddDs4ABkjOBS0jJBsnN0jYwc4AEUCCHga9KsQA0wozBCVdBVAh2hldkwjGCdFGGtkAA46VhmIKKd1dhCZuCHUatYAR074OI5pEHReAFooODgFF+VMOHOuD7j0BKSkKleqwonYuGYLH1eM1Wh0utVAbU+jAxgsFEtkERWOZ0FwHM0AMIQOyJEJQaAnEAEKIAFTG0iBUQAvkygA)

```js
var \u2139 = 0;
```
to
```
var ℹ = 0;
```

They're the same thing. See earlier discussion in #5052.

It's possible prettier should avoid replacing escape sequences in variable and property names just as it does in string literals. I don't know if that's been discussed much.

There's an additional workaround option now, which is [to use `--quote-props=preserve`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoIaoC8qwAOlOugOSmkCuATAIwDMAnFUqlQO4AWAT1SkQtWo1ZsRqAJZYM0AG5wATvAAmqGBGEgZIgPxUANOXQBfANzkQxkBAAOMGdCzJQeFSog8ACp4Q3FDxFCBl1WxAAIxU8MABrOBgAZQc4mSgAc2QYFTo4Oz4YAFsAGwB1Phl4LDSwOGTA6plFaoFkcCw3OwysVRhfWMzivGQAMzxSvrsAKywADwAhWISk5LxiuAAZDLhxyemQOfnkjMzSuABFOgh4famCkDSVPpUOqLwogVLoSIcVDIwcrhGB8ZAADgADHZ-hA+uVYg4Ov84K9lJEAI43eCDRxBJ4qVGqdF2QlYmSEwZ4YajJATB52PrFGQ5PKPLBnC7XW57OkHR4wT7A9Sg5AMOy5PAyUpnADCEGKIw6UGgezsdD6ABVPkF6X1zOYgA).

**Comment by sharpart555** [comment]
Thanks. I'll try `--quote-props=preserve` for now.
