### ISSUE TITLE
[Glimmer] improve curly/text spacing

### ISSUE THREAD

**Issue by GavinJoyce** [prettier/prettier#6237]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgJoQK4BOABHgM5wFQCGAtnEQJalEACww1dAvl6gPRYAOlAyYAEgyLsAZgwKkYAOVpweU4ABsqC5d14DMw1ABMGAN0ztOqro2YBPfMWv9TFo1nZUNcAB5qAIQR1Ugh0AAsGG34sEAAaEDCYBmhSZFAqAgIIAHcABUyENJQqMwgGY3iQACMCKjAAazgYAGV0eoYoAHNkGAI8OATwmBoNAHVI+FJ2sDgWooZks0X7ZHBSNITO8gIYPLqumipkaW9yBIArUl8AusbmlpUAGU64E7PBkCvfFs6unwAingIPB3hpziB2vIKGt-gwaHQCFV0AROjAxhUYOFkAAOAAMCRREHIYzq6DWKLgOzMbwSAEdgfB9mFiiBtABaKBwODGHlVAhwBlyOD7KiHY5IU7gz7kGgMXr9GV-QGMt6Sj4JGBUaoY4xY5AAJk1dQYGj+AGEIAiJSAoNBaSAyHAACra4pS8g8IA)
```sh
--parser glimmer
```

**Input:**
```hbs
<p>Your username is @{{name}}</p>
<p>Hi {{firstName}} {{lastName}}</p>
<div>{{name}} is your name</div>
<p>{{alex}} Ben {{sophie}}</p>
```

**Output:**
```hbs
<p>
  Your username is @
  {{name}}
</p>
<p>
  Hi
  {{firstName}}
  {{lastName}}
</p>
<div>
  {{name}}
  is your name
</div>
<p>
  {{alex}}
  Ben
  {{sophie}}
</p>
```

**Expected behavior:**

```hbs
<p>
  Your username is @{{name}}
</p>
<p>
  Hi {{firstName}} {{lastName}}
</p>
<div>
  {{name}} is your name
</div>
<p>
  {{alex}} Ben {{sophie}}
</p>
```

**Comment by evilebottnawi** [comment]
Thanks for issue, PR welcome
