### ISSUE TITLE
JavaScript: Breaking indentation with a tagged template literal.

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#6242]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U+hxABjQwNw0C+IANCBAA65oAZ2SgAhgCcJEAO4AFSQhEoxANwg4AJtxAAjCWLABrODADKfQzigBzZDAno4PABYwAtgBsA6i5zwhSzA4MyV-HFV-AE9kcCERHmshOAkYOQMbdzFkVDFPZJ4AKyEADwAhA2NTMzF3OAAZazgcvIKQYpKzaxtPOABFdAh4FvznEEsJZIlY3TFdOE8dPglrGG8tGBdkAA4ABh5liGTvAz5Y5bgp1WaeAEdB+HT+ZRAxIQBaKDg4TR+dCTg9xwAPSYky2SQuVGPGS7hw9kcYyE3V6AyGzUhrTGMDm600m2QACYeA4xDhPN0AMIQdxZWJQaA3EDoZIAFTmyihyXY7CAA)
```sh
--parser=babel
```

**Input:**
```js
function foo() {
  foo`
`;
}
```

**Output:**
```js
function foo() {
  foo`
`;
}
```

**Expected behavior:**

```js
function foo() {
  foo`
  `;
}
```

**Comment by sosukesuzuki** [comment]
If the text before formatting has right indentation,  it after formatting has right indentation.

[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U+hxABjXQwNw0C+NIANCBAAdc0AM7JQAQwBOUiAHcACtIRiUEgG4QcAE14gARlIlgA1nBgBlAcZxQA5shhT0cPgAsYAWwA2AdTc48CLWYHAWKoE46oEAnsjgImJ8tiJwUjAKRnaeEsioEt6pfABWIgAeAEJGpuYWEp5wADK2cHkFRSClZRa2dt5wAIroEPBtha4g1lKpUvH6Evpw3noCUrYwvjowbsgAHAAMfKsQqb5GAvGrcDPqrXwAjsPwmYKqIBIiALRQcHDaf3opHBHjggZkJNlckh8uM+KlPDhHM4JiJev0hiNWtD2hMYAtNtptsgAEx8JwSHDeXoAYQgnhy8Sg0DuIHQqQAKgtVDDUhwOEA)

```js
// Input
function foo() {
  foo`
  `;
}

// Output
function foo() {
  foo`
  `;
}
```

Also, if the tag is a member of `styled` and the template literal has some styles, the text after formatting has right indentation. (If the template literal doesn't have any styles, line breaks is removed)

[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U++AzjAJ4A2cAJgHREQAGNdOgAcAhuxxQA5knwAGANw1eiqAF8aNDFlwEe5SgIbM2XHvyjKaqkABoQEITqj1koEQCd3EAO4AFDwguKCIAbhA47LYgAEbuImAA1nAwAMqiYBKSyDDu6HB2ABYwALYsAOoFOPD06XApgVU4IVVMyOD0LnYS9HDuML5xksUiyKgiLD12AFb0AB4AQnGJySkixXAAMhJwo+OTIDOzKZlsAIroEPC7E-kgou497m3RItFwLFFC7hIwZREwBWQAA5ZHYvhAemU4kI2l84I8Qjs7ABHC7wAYOIIgET0AC0UDgHA4UXccFROFJAxEQxGSDGNzsPWKOGyuVu9BOcHOlx2dL2txgrz+7AByAATHYciIcCxMgBhCDFYZtKDQJEgdA9AAqryC9J6qlUQA)

```js
// Input
function foo() {
  styled.foo`
    padding: 0;
`;
}

// Output
function foo() {
  styled.foo`
    padding: 0;
  `;
}
```

**Comment by j-f1** [comment]
This is intentional. Indenting the closing `` ` `` will add spaces to the string, which changes the meaning of the code.

**Comment by sosukesuzuki** [comment]
thanks
