### ISSUE TITLE
[TypeScript] Breaking pipe character when union types wrap

### ISSUE THREAD

**Issue by ArgonAlex** [prettier/prettier#6244]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgDEIIAjXTQ4AHSkMIApdXclCBnGTdAcwA0hciPIduvKIMJhZYcT34BKBZL6EAPoSgBXALbksm7ToA2p4zqgATONnRxrAbnoBfevRgBPAA5FSFFSEALxcilLGugZGWuRkpnC4DFrEVmAwqNCRZhZaVrb2UI6WNnYOziACIBA+GdCcyKBUmBAA7gAKVAgNKLgAbhCo1pUg5Jj4ANZwMADKPvj8yDw6cFUAFjB6pgDqa6jwnPMEM937qH37XsjgnA1V6JxYMO3jfHq4yHimj1UAVpwADwAQuMwFNZrg9HAADIOT64b6rED-AEzfgJACKOgg8HhiKq80wj0w128fk4YF4tRGPkkMG2Qxga2QAA4AAwElqPbbjHzXWlwYl9OAjACO2PgLxqPRAuE4AFoio5HCNMHBxag1S9cG8Pkgvj8QI89KglpgVlVOOi4FicSL9QjDTBcOQGdYmcgAExVHi4VCmfgAYQgene1yg0BFVR0jwAKi6ega4K5XEA)

**Input:**
```ts
interface Foobar {
  (aaaa: string, bbbb: string, cccc: string): string | number | null | undefined;
}

type Foobar = string | number | boolean | Function | null | undefined | undefined;
```

**Output:**
```ts
interface Foobar {
  (aaaa: string, bbbb: string, cccc: string):
    | string
    | number
    | null
    | undefined;
}

type Foobar =
  | string
  | number
  | boolean
  | Function
  | null
  | undefined
  | undefined;
```

**Expected behavior:**
No pipe character at the beginning of the union type.

The function interface should probably also wrap the same as a function declaration, where the arguments wrap first, but that's a separate non-breaking issue.

**Comment by ArgonAlex** [comment]
Interestingly, intersection types don't have the same problem:

**Input:**
```ts
type Foobar = string & number & boolean & Function & null & undefined & undefined;
```

**Output:**
```ts
type Foobar = string &
  number &
  boolean &
  Function &
  null &
  undefined &
  undefined;
```

**Comment by j-f1** [comment]
This behavior is intentional — people are much more likely to have a union type with lots of member types than an intersection type with lots of member types.

**Comment by ArgonAlex** [comment]
Oh nevermind, I see now that the pipe at the beginning is in fact valid. My types were breaking for an unrelated reason.
