### ISSUE TITLE
Introducing Plugin for Pug

### ISSUE THREAD

**Issue by Shinigami92** [prettier/prettier#6245]
referencing issues #5767 and #4686

@ispyhumanfly, @j-f1, @rdhar, @danielpza, @lydell
Hello at all 😃 
I'm happy to introduce the plugin for prettier to support pug! 🎉 
https://github.com/Shinigami92/prettier-plugin-pug

I'm currently in heavily development phase and I am not completely finished with the base yet.
But I would like to let you know that I would like to publish a first alpha in the next few days.
In addition, I am currently developing so that no options can be passed. I'll do that later if the base is _stable_.

If you want to test something, you're welcome to help me.

**Comment by rdhar** [comment]
Brilliant, that's great to hear! 🎉

Do keep us in the loop with how you're getting along and we'd be more than happy to test/help out wherever possible.

And a huge thanks for taking on this challenge in the first place!

**Comment by evilebottnawi** [comment]
Feel free to send a PR in docs :+1:

**Comment by Shinigami92** [comment]
I'm happy to announce the first alpha :D

Please create issues for any bugs

https://github.com/Shinigami92/prettier-plugin-pug/releases/tag/1.0.0-alpha.1

https://www.npmjs.com/package/prettier-plugin-pug

**Comment by Shinigami92** [comment]
I have published an [alpha.2](https://www.npmjs.com/package/prettier-plugin-pug/v/1.0.0-alpha.2)
I used `npm publish --tag aplha` and I think the `--tag` was wrong, so it's not seen as the _latest_ version 🤔 
Nevermind, [Changelog](https://github.com/Shinigami92/prettier-plugin-pug/blob/master/CHANGELOG.md#100-alpha2)

Thanks to @rdhar, I used your [repo](https://github.com/rdhar/template-pug) for some internal testing 😄

**Comment by rdhar** [comment]
It's great to hear that some use came of that repo! I'd meant to keep it updated as a standard baseline for my smaller web projects in the future. But, would you believe it, due to an issue with [Parcel's CSS-loader](https://github.com/parcel-bundler/parcel/issues/2936), template-pug was left behind and forgotten(!)

Will be sure to pick this up shortly. Is there any additional steps on getting up and running with it on VS Code?

**Comment by Shinigami92** [comment]
Yes, follow this PR: https://github.com/prettier/prettier-vscode/pull/757

**Comment by lipis** [comment]
As already mentioned.. please add it to the this list: https://prettier.io/docs/en/plugins.html#community-plugins

**Comment by Shinigami92** [comment]
@lipis #6246 is already merged :thinking:

**Comment by lipis** [comment]
So I guess we can close it now! https://twitter.com/PrettierCode/status/1144718891349938177?s=19

**Comment by lipis** [comment]
we can also move it under prettier to make it official since it's v1

**Comment by Shinigami92** [comment]
[1.0.0-alpha.7](https://www.npmjs.com/package/prettier-plugin-pug) is released and supports wrapping of attributes 🎉 
Road to rc.1? 👀

**Comment by Shinigami92** [comment]
I just released [1.0.0](https://github.com/prettier/plugin-pug/releases/tag/1.0.0) 🎉
