### ISSUE TITLE
Typescript: unexpected semicolon at the beginning of a line

### ISSUE THREAD

**Issue by thomasnordquist** [prettier/prettier#6247]
Behavior triggered by `--no-semi`

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOADgK4BGqAlmDpALaXQIwDqDqqAVSisI1WAAoAlMTIUK4gO4MoAEwgKcWTVACekgHRh0UMHFQBJFajgBhdP1rowAa3EwAFg0z7HAJ0myOAC+ZIE09Ew4flLEIVBBIAA0IBCUMAzQmMig6L6+6gAKuQhZKOgAbhAMKkkgtL5OznAwAMqUTsoA5sgwvtRwye4wrKjcnvCY7aYtJQzp5XM6yODYtcqYcL4wBQ2drOjIAGb2G8kAVpgAHgBCDS7NLeiscAAyynBHJwMgF5ctXdYAIrUCDwT6oU4gdq+Da+ZYwHSUOCYMC+BhpWqUNGwXgqDzIAAcAAZkliIBtuA1KMsscjNuUPskAI4g+A7VKlEBYAC0UDgcBUAtqvjgLIYIp26D2ByQxwh3w2rAY4MhmABcGBoI+sq+yRg6FouPxSAATHqGnwujYIKx9stkQBWWrUDYAFQNpTlGyCQSAA)
```sh
--parser typescript
--no-semi
--trailing-comma es5
```

**Input:**
```tsx
class Foo {
  public componentWillUnmount() {
    (window as any).cancelIdleCallback(this.bar)
  }

  public bar() {}
}
```

**Output:**
```tsx
class Foo {
  public componentWillUnmount() {
    ;(window as any).cancelIdleCallback(this.bar)
  }

  public bar() {}
}

```

**Expected behavior:**
The semicolon in line 3 should not be there, it is however syntactically correct

Similar to https://github.com/prettier/prettier/issues/5837 but without a preceeding comment.

**Comment by j-f1** [comment]
This is correct behavior. If you were to add another line of code above the `(window as any)` line, it would behave unexpectedly:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOADgK4BGqAlmDpALaXQIwDqDqqAVSisI1WAAoAlMTIUKAN3QAnHADNCOALw5ay2XPEB3BlAAmEQzixWoAT0kA6MOihg4qAJKnUcAMLp+XTAAa3EYAAsGTAddJUl9AF8yfRp6Jh1lKWIkqByyMAxsfA1Scio6RmY2DiguXn4hETEYLNK5HEUVdSJtWP0KAG4jE3NLaxd7Jxc3T28-ANQg0IiomOV4sryy1MqMpVachJAAGhAIShgGaExkUGUlCwAFZQQblHR5CAZTE5BaJXQITgMAAypRASYAObIGBKahwU7hGCsVDcSLwTDgtwg14MS7yPG2ZDgbC-EyYOBKGCPAGQ1joZCqAIU04AK0wAA8AEIAoGg9CsOAAGRMcEZzIRIHZHJBUJ8AEVqBB4OLUCyQOClBSlMSYLZKHBMGAlAwLr9KCbYLxTBFkAAOAAMpwtEAp3ABlGJFsNlPkYtOAEclfAaec3iAsABaWpwUyx35KOBBhiJmnoOkMpBMtWSimsBiq9WYOVwRXKsVZiWnGDoWjW21IABM1YBfChvggrHpxMNAFZftQKQAVWtvbMUhIJIA)
```sh
--parser typescript
--no-semi
--trailing-comma es5
```

**Input:**
```tsx
class Foo {
  public componentWillUnmount() {
    var foo = bar
    (window as any).cancelIdleCallback(this.bar)
  }

  public bar() {}
}

class Foo {
  public componentWillUnmount() {
    var foo = bar
    ;(window as any).cancelIdleCallback(this.bar)
  }

  public bar() {}
}
```

**Output:**
```tsx
class Foo {
  public componentWillUnmount() {
    var foo = bar(window as any).cancelIdleCallback(this.bar)
  }

  public bar() {}
}

class Foo {
  public componentWillUnmount() {
    var foo = bar
    ;(window as any).cancelIdleCallback(this.bar)
  }

  public bar() {}
}

```

**Comment by thomasnordquist** [comment]
So you are saying that this rogue semicolon is a workaround for a different issue (in your example)?


The output should not be like this in the first place:
```javascript
var foo = bar(window as any).cancelIdleCallback(this.bar)
```
and should therefore not be a reason for weird workarounds?!

**Comment by lydell** [comment]
> The output should not be like this in the first place:

I totally agree! But sadly that's not how JavaScript works (any by extension, TypeScript). See also https://prettier.io/docs/en/rationale.html#semicolons
