### ISSUE TITLE
Markdown front matter is not parsed if the last value is omitted

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#6248]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBDJACAvAFgCYsAjfQrdVLLSWBGEAGhAgAcYBLaAZ2ShsAJxEQA7gAVRCQSmwA3CDwAmbEORHYwAazgwAypx08oAc2QwRAVzjsAFjAC2AGwDqDnvH4mwcQzlvHkVvAE9kcH5BdjN+OBEYKW1zZ2xkADNsV3j2ACt+AA8AIW09A0NsZzgAGTM4TOzckALCwzNzVzgARRsIeEac+xATEXiRSLSRXVVJKA1OETMYdzUYB2QADgAGdkWIePdtTkjFuHHFBvYARz74ZK55EGx+VCg4OFVPjRE4W55fslsKl0kgskN2PFnDwrLZhvwOl1ev0GmCmsMYNhyKtVOtkCR2NZsDxXB0AMIQZxpSJQaBXEA2eIAFSx8nB8QAvhygA)
```sh
--parser markdown
```

**Input:**
_a few spaces after `b`_
```markdown
---
a:    42
b:    
---

content
```

**Output:**
_no spaces after `b`_
```markdown
---
a: 42
b:
---

content

```

**Second Output:**
```markdown
SyntaxError: Implicit map keys need to be followed by map values (2:1)
  1 | a: 42
> 2 | b:
    | ^^
```

**Expected behavior:**

`b:\n---` is parsed just as `b:    \n---` or `b: ~\n---`

[Swapping a and b](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKAjJACAvLAQ30IBYAmLdVLLSWBGEAGhAgAcYBLaAZ2ShiAJxEQA7gAVRCQSmIA3CDwAmbENhHEwAazgwAypx08oAc2QwRAVzjsAFjAC2AGwDqDnvH4mwcQzlvHkVvAE9kcH5BdjN+OBEYKW1zZ2JkADNiV3j2ACt+AA8AIW09A0NiZzgAGTM4TOzckALCwzNzVzgARRsIeEac+xATEXiRSLSRXVVJKA1OETMYdzUYB2QADgAGdkWIePdtTkjFuHHFBvYARz74ZK55EGJ+VCg4OFVPjRE4W55fsliKl0kgskN2PFnDwrLZhvwOl1ev0GmCmsMYMRsKtVOtkJR2NZiDxXB0AMIQZxpSJQaBXEA2eIAFSx8nB8QAvhygA) (i.e. making so that the last line in YAML  has value) helps avoid the exception. Also [the same yaml in a separate file](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDJACLGAsAmAHSgCNNsiQAaECABxgEtoBnZUVAJw4gHcAFTglYpUANwgMAJlRDEOqMAGs4MAMq0FDKAHNkMDgFc41ABYwAtgBsA6iYbxmGsHFVD7DUfYCeycM1bUWsxwHDB88trmqMgAZqiWwdQAVswAHgBC8koqqqjmcAAyWnCx8YkgKamqWtqWcACKBhDwpQnGIBocwRy+XnmWMrQcWjDWUjAmyAAcAAzUQxDB1vK0vkNw3aIl1ACOTfDhdMJozAC0UHBwklcyHHB7DHfhqJHRSHFt1MHmDHqG7cwanVGs0Su8yu0YKhiGNJBNkHhqPpUAxLDUAMIQcxRXxQaDbEAGYIAFWhwg+wQAvpSgA) is formatted without problems.

**Comment by yech1990** [comment]
Also format in the wrong way when there is a empty line in the block.

input
```markdown
---
a:  42
b:  43
 
---

# test
```

**Output**:

```markdown

---
a: 42
b: 43

---#test
```

**Comment by thorn0** [comment]
The original issue seems to be gone.

@yech1990 please use [the playground](https://prettier.io/playground/) to reproduce your issue. I can't reproduce it.

**Comment by yech1990** [comment]
@thorn0  sorry about that. 
I got this error when using version 1.19. After upgrading prettier into version 2.0, it works properly now.

**Comment by thorn0** [comment]
Glad to hear that.
