### ISSUE TITLE
Typescript (x as y) syntax is broken with --no-semi flag

### ISSUE THREAD

**Issue by xorik** [prettier/prettier#6253]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAHgBQCGS+pUAngJT7AA6U++ZlAzvgBIAqAsgBkAklAAO6GAFEANnAC2CGLQB0qHHK4BefFHQyZzAL7MQAGhAQxuaB2ShSAJ0cQA7gAUnCOylIA3CBwAE3MQACNHUjAAazgYAGUxKJwoAHNkGEd0OAsACxh5GQB1XJx4DiSwOHjvMpw-MupkcA47CxSOOEcYd0jU+VJkVFIZTosAKw5CACFImLj40kVBFLghkbGQScJ4lNS5AEV0CHh10ZyQJMdOx2aYajE4DjBHHGtQsVfYIuCYXOQABwABgsnwgnSKkTEzU+Ty6fjWFgAjsd4L0rD4QKQOABaKBwOBBQmhRxwFE4Um9Uj9QZIYbnCydeQ4M6bDh7Q6otZ0jYXGCkMI-IJ-ZAAJgsmVIGj2AGEIPIBs0oNBESB0J1eAKfPTOkYjEA)
```sh
# Options (if any):
--no-semi
```

**Input:**
```typescript
function x(a: any) {
  (a as HTMLInputElement).files = null
}
```

**Output:**
```typescript
function x(a: any) {
  ;(a as HTMLInputElement).files = null
}

```

**Expected behavior:**
Don't add a semicolon before the `(x as y)` syntax

P.S. if you have anything before, then the result is even worse, e.g. try this:
```
function x(a: any) {
  const x = 1
  (a as HTMLInputElement).files = null
}
```
It breaks my code :(

**Comment by evilebottnawi** [comment]
https://prettier.io/docs/en/rationale.html#semicolons

How it is break your code?

**Comment by xorik** [comment]
@evcohen check the second example, it brokes the code:
```
function x(a: any) {
  const x = (1(a as HTMLInputElement).files = null)
}
```
Second issue is that I have a tslint rule, that checks that there's no semicolons in the code, and I can see warnings after prettier

**Comment by evilebottnawi** [comment]
@xorik Do you read link above?

```
function x(a: any) {
  const x = 1
  (a as HTMLInputElement).files = null
}
```
!==
```
function x(a: any) {
  const x = 1
  ;(a as HTMLInputElement).files = null
}
```

It is difference code do difference things and you need here semicolon

**Comment by xorik** [comment]
@evilebottnawi please check the [link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAHgBQCGS+pUAngJT7AA6U++kUAzjEfgLz4BGZqzKUO+ABIAVALIAZAJJQADuhgBRADZwAtghi0AdKhzbx-KOk2bmAXxAAaEBGW5oHZKFIAnbxADuAAo+CB4opABuEDgAJo4gAEbepGAA1nAwAMrKKThQAObIMN7ocE4AFjA6mgDq5TjwHDlgcJmhDTgRDdTI4BweTnkccN4wgcn5OqTIqKSaw04AVhyEAELJaRmZpHpyeXAzcwsgy4SZefnaAIroEPCH82UgOd7D3r0w1MpwHGDeOK54sp-rAarEYOVkAAOAAMTmBEGGNWSyl6wJ+IwiBycAEdbvBxi4wiBSBwALRQOBwGLU+LeOB4nD08akSbTJCzR5OYY6HAPY4cC7XfEHDlHJ4wUgJMExCHIABMTmKpFMFwAwhAdFNelBoNiQOhhlIpWFOcNbLYgA).
The output is not equials
```
function x(a: any) {
  const x = 1
  ;(a as HTMLInputElement).files = null
}
```
it's
```
function x(a: any) {
  const x = (1(a as HTMLInputElement).files = null)
}
```
which is totally wrong
```
I agree that my first example is not correct, because I didn't know about adding semicolon by prettier, but second example changes code completely

**Comment by evilebottnawi** [comment]
@xorik works fine https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAHgBQCGS+pUAngJT7AA6U++kUAzjEfgLz4BGZqwDcZSh3wAJACoBZADIBJKAAd0MAKIAbOAFsEMWgDpUOXZP5R027cwC+IADQgIq3NA7JQpAE6+IAHcABT8ELxRSADcIHAATZxAAI19SMABrOBgAZVU0nCgAc2QYX3Q4FwALGD1tAHVKnHgOPLA4bPCmnCim6mRwDi8XAo44Xxhg1MK9UmRUUm1RlwArDkIAIVSMrOzSAwUCuDmFpZBVwmyCwt0ARXQIeGPFipA831HffphqVTgOMF8OHciVUgNgdXiMEqyAAHAAGFygiCjOqpVT9UF-MZRI4uACO93gkzcERApA4AFooHA4HFaYlfHACThGZNSNNZkh5s8XKM9DgnqcOFdboSjlyTi8YKQkhC4lDkAAmFylUjmK4AYQgehm-Sg0FxIHQoxkMoi3NG9nsQA

you link still contains invalid code (missed semicolon)

**Comment by xorik** [comment]
hmmm, okay probably you're right. I didn't know that semi is required before the parentheses.
Thanks!
