### ISSUE TITLE
[HTML] Differences between formatting span and div

### ISSUE THREAD

**Issue by liamross** [prettier/prettier#6256]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAiHMo5cmzhcAJmIkTUNODC7kwlLgCcAzisEgAqvgBiAWgAcQ8gHp5CpSrVQuygwDcAlnADuABwgtGGtIWAQYAx9PGRhKfhk4LzA4MyiYygAack8oTxhPLjozHTBCuH4ARgA6AAZrOxYFSWVVKhgYPzM4AEcAV093AwANM0MAQTNcCBo-LnyAIzo4EOh4WANvfjgZXmWQW3tFfJglhmItFXy4LXIAM0CaOfy+bJ0dXrhUG2PTxskbSjSOR-VDzCAyACeh0k6DMZnIAGViGMAHLkAASYwR5Hw6IoxAAStgAEIAGVIAFlyHDoagdLMoAx8JRPDpXlQID5sjBOBAIABrNk+QHiR4JXkvBAQXq8SjkGAQci8RWzHQ8iw1cjCiHc8gyCAAfi+9J4Yj+ihNjOZrPZlE5urofMFWpF5DFcAlvHIUplcoVSpVXDV5A15DU8zynuuxoZZvEDlh8MwAEkAGrkHCkbEo7D4almWkyAZMllsm12rmRx0CoWu92e71QaWy+WK5XkVXqzXa3X6o02IvuONNVCDks28v2qtO2sIN2yD2OyVN32tgMdoNdsPkCM8pe7LRfMcgmxgyFiL7sRgsEAZEAQPz5aA6ZCgbRaTnEbQIF8oLjuCBolvEB5i0LgwH5FQEVmMAcl4ZAYC0D47yvAB1Fl4BNZIER-PIBjyCFkHAN5gJyPQgnOLheEeZBbkKPQ7wAKx0AAPYkwIgqDXDgUkcjgWj6LgJjWIROClgARV6CB4AEugGJAWZdGuIir2AvwtByGBUOiWJkA1O91IgPRULAvwiPUuByPcfi7z6aS4HOB9fxAIMzCgOBtm2YCLj6TwLko6iuFk+S9BoTwEKQoSQB0MS4Ek+zgqi1R5m09JkAAJjvRCuE8Og4KmGgaJQJt3OA3o9HwLh5l-Oi5LgABfeqgA)
```sh
# Options (if any):
# (all default)
```

**Input:**
```html
<span>This is how it looks when made long enough to go past 80 and with a span</span>
```

**Output:**
```html
<span
  >This is how it looks when made long enough to go past 80 and with a
  span</span
>
```

**Expected behavior:**

- Should format the same way `<div></div>` does:

```html
<span>
  This is how it looks when made long enough to go past 80 and with a span
</span>

```

**Comment by lydell** [comment]
Hi!

It sounds like you might be looking for the [html-whitespace-sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option.

**Comment by liamross** [comment]
Ah perfect, yep looks like it's not a bug, thanks @lydell
