### ISSUE TITLE
Solution: optimize/sort imports

### ISSUE THREAD

**Issue by pauldraper** [prettier/prettier#6260]
Workaround for popularly requested won't-fix issue:

* #767
* #949
* #3104
* #4654

This sorts imports and removes unused imports for JS/TS.

**myplugin.js**

```js
const { parsers: typescriptParsers } = require('prettier/parser-typescript');
const ts = require('typescript');

class SingleLanguageServiceHost {
  constructor(name, content) {
    this.name = name;
    this.content = content;
    this.getCompilationSettings = ts.getDefaultCompilerOptions;
    this.getDefaultLibFileName = ts.getDefaultLibFilePath;
  }
  getScriptFileNames() {
    return [this.name];
  }
  getScriptVersion() {
    return ts.version;
  }
  getScriptSnapshot() {
    return ts.ScriptSnapshot.fromString(this.content);
  }
  getCurrentDirectory() {
    return '';
  }
}

function applyChanges(text, changes) {
  return changes.reduceRight((text, change) => {
    const head = text.slice(0, change.span.start);
    const tail = text.slice(change.span.start + change.span.length);
    return `${head}${change.newText}${tail}`;
  }, text);
}

function organizeImports(text) {
  const fileName = 'file.ts';
  const host = new SingleLanguageServiceHost(fileName, text);
  const languageService = ts.createLanguageService(host);
  const formatOptions = ts.getDefaultFormatCodeSettings();
  const fileChanges = languageService.organizeImports(
    { type: 'file', fileName },
    formatOptions,
    {}
  );
  const textChanges = [...fileChanges.map(change => change.textChanges)];
  return applyChanges(text, textChanges);
}

export const parsers = {
  typescript: Object.assign({}, typescriptParsers.typescript, {
    preprocess(text) {
      text = organizeImports(text);
      return text;
    }
  })
};
```

**.prettierrc.yml** (or equivalent)

```yaml
plugins:
  - ./myplugin.js
```

As noted elsewhere, changing the import order can produce altered behavior in case of side-effects.

**Comment by ggascoigne** [comment]
Seeing your example here convinced me to write https://www.npmjs.com/package/prettier-plugin-import-sort.  This uses import-sort to sort imports for typescript and javascript before passing the text on to prettier.  Thanks for the hint.

**Comment by chrisstoy** [comment]
> Seeing your example here convinced me to write https://www.npmjs.com/package/prettier-plugin-import-sort. This uses import-sort to sort imports for typescript and javascript before passing the text on to prettier. Thanks for the hint.

I tried using this but doesn't seem to work.  Installed the npm module.  Added the plugin to my .prettierrc file.  It complains if it can't find the plugin,but doesn't seem to actually sort imports when I format my document.

```
{
  "plugins": [
    "./node_modules/prettier-plugin-import-sort/src"
  ],
  "arrowParens": "always",
  "bracketSpacing": true,
  "printWidth": 120,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false
}

```

**Comment by ggascoigne** [comment]
you should probably open an issue over at https://github.com/ggascoigne/prettier-plugin-import-sort, but I'll just take an action to improve the docs.

That said:  Prettier automatically imports any installed module called prettier-plugin and treats it as a plugin so you don't need an explicit plugin line.  What's likely missing is the configuration for import-sorts.

You still need something like this in you pacakge.json file:

https://github.com/ggascoigne/prettier-plugin-import-sort/blob/master/package.json#L38-L41

```json
"importSort": {
    ".js, .jsx, .ts, .tsx": {
      "style": "module"
    }
  }
```

**Comment by chrisstoy** [comment]
Thanks!  That worked for me.
