### ISSUE TITLE
[formatting] Support for template-strings (ES6).

### ISSUE THREAD

**Issue by Domvel** [prettier/prettier#6262]
**Prettier 1.18.2**

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOgEYA2AhoUfsQBQA6UABLQAam3Ok4vEdFK0AkwNevXTZyJYmNJspEmUQoBKQbQC+XZv2XDMuOZOLSDRsnMXKV7OV2vMADAA9NdIXrYwIAZRgAnDFADmFACMAGxKzmpWDk5C6rLGOO5evgHBYeYMNAoA3DQgADQgEAAOMBjQWMigRN7eEADuAAo1CJUoRABuEBgAJgUgeN5EYADWcDAexcN+-sg+AK5whWgwALYEAOqY8FhTYHAerRhlHccAnsjgWJWFflhw3jCNQ-6rRMgAZkQE94UAVlh7AAhIajcYeIirOAAGT8cE+31+IAB9g8MwIcAAivMIPAET8liApt57t5LngSGcCNB+sUUjANr10MgABy2Qp0iD3DZDYqXOlwUkdeGFACOOPgzxKbRARCwAFooHA4D0Vf1vHBxRgNc8iK93kgvgTCvdVhg5t5Fib0ViJfDDYjCTASIyesykAAmQo+IgYAgzADCEFWb0uUGgIpA83uABUSG0jfcVCogA)

**Input:**
(Already formatted in expected code after prettier format.)

```js
this.blabla.bla(
  `bla bla bla. bla bla: ${
    this.blabla.blablabla.blabla.blabla()
  } blabla ${
    this.blabla.blablabla.blablabla.blabla()
  }. blabla bla bla bla 0x${
    blabla.bla.toString(16)
  } blabla 0x${
    blabla.blabla.toString(16)
  }`
);
```
(Maybe also break before a dot.)

**Output:**
```js
this.blabla.bla(
  `bla bla bla. bla bla: ${this.blabla.blablabla.blabla.blabla()} blabla ${this.blabla.blablabla.blablabla.blabla()}. blabla bla bla bla 0x${blabla.bla.toString(
    16
  )} blabla 0x${blabla.blabla.toString(16)}`
);
```

**Expected behavior:**

See Input code.

- Prettier does not respect the print width (line character limit).
- Prettier formats it in an unreadable code.

**Suggestion for a solution:**
If the print width is reached, break on every template variable. See input code.
It seems to be Prettier is not template-string ready. Is this a planned feature?

Here is a screenshot, a proof of the current behavior and the print width line.
![image](https://user-images.githubusercontent.com/35452565/60427395-efdcdd00-9bf6-11e9-9740-79d306e72be4.png)

Additional infos:
VS Code version: 1.35.1
TypeScript
Windows_NT x64 10.0.18362

**Comment by lydell** [comment]
Prettier kind of used to work like you describe, but it was changed in: #5979

If there’s one thing we’ve learned during the years, it’s that no matter what we do, people always “complain” about template literals.

**Comment by Domvel** [comment]
Wait, Prettier is formatting depending on print width. 

[See example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAbAlhgZQAsIAnLAXkwG1hNo4lMBGAGkxgHcImAmdmEVJxGmAMwBfdnQZM2HbnwFCRTSQF0A3AB0ouyFAw58MADLQA5piq16UUfK49M-DitGTpdhwMUvlwh5SmDL2cr7OroKBasGhPgqRAariElq6IKwgEAAOMLjoyKAAhqSkEJwACqUIaMggxQBuELgAJpkgAEakxWAA1nAwBDm9uFAWyDCkAK5wWUQwALbYAOpEuPBoI2BwBLUbuI0bAJ71YGh1WWNocOSVPRaLxcgAZsXYN1kAVmgAHgBCPX6gwIxUWcFMYzgr3enxAP1+BDGFmwcAAitMIPAYR85iARqQbqR6p1ip1jthoB0cqQxjAVm1BMgABwABiyNIgNxWPRy9RpcCJjWhWQAjpj4PdcnUUMU0ABaexwVrKjrCcW4YT3YqPZ5IN64rI3Ra4SYzPFoZGojFY6H62F4mBkhmtJlIfggKbFXB4cYAYQgiye9SgDA60xuABUyTKDTcJBIgA)

It confirms with
> Don't break simple template literals

If I understood correctly, then Prettier is formatting by print width. See the playground example.
The current behvior for template-strings is more a bug / unexpected behavior and against Prettier's rules.
Or did I miss something? I do not understand the change. Because this is Prettie's behavior. It's more like a prettier-ignore solution. And in my example in the first post. The string breaks at toString() method. 

But ok, if some people want this ugly format. We could implement an option for this. I know Prettier does not like options. But There are already options for quote style, etc. 
We could start a poll. If the result is 50% / 50% it's a reason for an option. If the current (new) behavior wins, then I'll not understand why. But maybe I will, if you explain it. But for now, in my opinion it's wrong. And against clean code.

**Comment by Domvel** [comment]
Can I change the Prettier playground version? Because I think Prettier never had formatted my example code as I expecting.

In the change of #5979 it is descriped as: 

**A**
```js
console.log(
  chalk.white(
    `Covered Lines below threshold: ${coverageSettings.lines}%. Actual: ${
      coverageSummary.total.lines.pct
    }%`
  )
);
```
But I do expect: 

**B**
```js
console.log(
  chalk.white(
    `Covered Lines below threshold: ${
      coverageSettings.lines
    }%. Actual: ${
      coverageSummary.total.lines.pct
    }%`
  )
);
```

My expectation is exactly the same as Prettier works. See my second post example. If the print width is reached, it formats the node (e.g. array with objects) is a pretty styled code. This means not just a simple break at the print width. It breaks the along the objects syntax. (Not like **A**, like **B**!)

**Comment by lydell** [comment]
I think I misunderstood you slightly before posting my last comment. But what I wanted to get across was that we recently changed stuff regarding template strings.

Are you saying that you _always_ want a newline after `${` and before `}`? Like this:


```js
x = `A parent and ${
  numChildren
} children`;
```

Also note that print-width is just a general guideline for Prettier. It can produce both longer and shorter lines.

**Comment by Domvel** [comment]
If the code fits the line print width, do not break. If it will overflow, break it. Like in this [example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAbAlhgZQAsIAnLAXkwG1hNo4lMBGAGkxgHcImAmdmEVJxGmAMwBfdnQZM2HbnwFCRTSQF0A3AB0ouyFAw58MADLQA5piq16UUfK49M-DitGTpdhwMUvlwh5SmDL2cr7OroKBasGhPgqRAariElq6IKwgEAAOMLjoyKAAhqSkEJwACqUIaMggxQBuELgAJpkgAEakxWAA1nAwBDm9uFAWyDCkAK5wWUQwALbYAOpEuPBoI2BwBLUbuI0bAJ71YGh1WWNocOSVPRaLxcgAZsXYN1kAVmgAHgBCPX6gwIxUWcFMYzgr3enxAP1+BDGFmwcAAitMIPAYR85iARqQbqR6p1ip1jthoB0cqQxjAVm1BMgABwABiyNIgNxWPRy9RpcCJjWhWQAjpj4PdcnUUMU0ABaexwVrKjrCcW4YT3YqPZ5IN64rI3Ra4SYzPFoZGojFY6H62F4mBkhmtJlIfggKbFXB4cYAYQgiye9SgDA60xuABUyTKDTcJBIgA) like general Prettier behavior. So, do not break always. But if it breaks because the line character limit, it should break on all code sections. (`${\n...\n}`) And the code itself between `${` and `}`, should handled as normal code. Nothing special here. A string ends at `${` and continue at `}`. In short: Yes, break it if it exceeds the line limit.

Why? Because:

- Respect the maximal line length. (print width)
- Keep it simple and clean.

But maybe not trivial, because there a several cases which want one or the other rule. 
Could we say: If a line reaches the limit, try to break as much you can.
For sure, Prettier will not break your string. It's impossible. Otherwise it's a manipulation of your code.
So, there will be lines which overflows the line limit. But in this case, break it on the code sections to keep your code pretty formatted. Also your short literals like a variable is available at the beginning of a line. Not at the end. You do not need to scroll vertically.

**A**
```js
//                                                    This is the line limit -> |
console.log(`This is a demo of a long one-liner string with "simple" literals. ${
  14 * 3
} ${
  12 * 4 - 6
}`);
```

**B**
```js
//                                                    This is the line limit -> |
console.log(`This is a demo of a long one-liner string with "simple" literals. ${14 * 3} ${12 * 4 - 6}`);
```
Maybe not the best example. But it shows what I mean. 
So which is better? Scrolling to the end of the line to edit your code? Or keep it at the beginning?

**Comment by lydell** [comment]
Well, if you have a really long string without interpolations you’d have to scroll sideways anyway ¯\\\_(ツ)\_/¯

**Comment by Domvel** [comment]
It's a bit different to scroll for a string or for code. It's harder to edit code at the end. Note: Prettier will always format it at the end, also if you insert a line break in your code. 
Also we should only expect a string behind the scroll view. Not code.

**Comment by vityas-off** [comment]
Can i restore old behavior through .prettierrc or somehow else?

**Comment by lydell** [comment]
@vityas-off Currently there's no way to configure it.

**Comment by evilebottnawi** [comment]
Answer above, issue about improving output here https://github.com/prettier/prettier/issues/6192
