### ISSUE TITLE
Vue/HTML Parser: Incorrect format in tag <template>

### ISSUE THREAD

**Issue by gabrielwillemann** [prettier/prettier#6263]
When I use the tag "template", Vue Parser is formatting wrong.

The tag "template" is very popular in Vue Ecosystem. You can see examples in oficial documentation: [Iterations](https://vuejs.org/v2/guide/list.html#v-for-on-a-lt-template-gt) and [Conditions](https://vuejs.org/v2/guide/conditional.html#Conditional-Groups-with-v-if-on-lt-template-gt)

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWWa4Fxl0C0AZhAE4BeYiBpka5ANoBGADRkATPIDMAXRGEACvwgAjHHAziAzmQAWcfhy5lgwcWQC+j1AHpW+IqQpvaDUm4e7IwBxmD8NFgwjHAAHlgCMGRUcDx4AK44ScDeZFB4GHBIZCLwxjAisqSOANwBrmERUYwgsiAQUTTQxsigePw6AO6a-Qg9KHh0EDRUrSC6-HhgANZwMADKWEsSAObIMPzpcG1mMBg4AOpmNGVbYHDrYzf0NwCeyODGPW0SxpYw2jwOwweGQaRwfzaACtjLEAEKLFZrdYFOAAGQkcDBeAhxxAMNi612BgAiukIPBsbi2lt+H9+B86Ec5lgIrALjMYGZkAAOAAMNJ0fwuiywH1ZcHpdCxbQAjuT4NoOuMQHhjFwoHA4ClZm0rPKaFZAcDQUhwZCQH8MDR9oc8cZiXAyRSsWacRaYHhdByqFzkEoQAc8DQcLsAMIQDAgj5QaAykDpP4AFS943NcGcQA)

**Input:**
```vue
<template>
  <div>
    <template v-for="i in [1, 2, 3]">Problem is here - {{ i }}</template>
  </div>
</template>

<script>
export default {
  name: "test",
};
</script>
```

**Output:**
```vue
<template>
  <div>
    <template v-for="i in [1, 2, 3]"
      >Problem is here - {{ i }}</template
    >
  </div>
</template>

<script>
export default {
  name: "test"
};
</script>
```

**Expected behavior:**

```vue
<template>
  <div>
    <template v-for="i in [1, 2, 3]">Problem is here - {{ i }}</template>
  </div>
</template>

<script>
export default {
  name: "test",
};
</script>
```
or
```vue
<template>
  <div>
    <template v-for="i in [1, 2, 3]">
      Problem is here - {{ i }}
    </template>
  </div>
</template>

<script>
export default {
  name: "test",
};
</script>
```

**Comment by lydell** [comment]
Hi!

Are you aware of the [html-whitespace-sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option?

You get the same formatting with `<span>`:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWUDOWe5dAtAGYQBOAXmIgaZGuQDaARgA0ZAEzyAzAF0RhAAr8IAIxxwM4lmQAWcfnDLs8tu-dtUyXMsGDiyAX0+oA9Gw5GCj9aBlI-TFwCOEZwljB+GiwYRjgADywBGDIqOB48AFccbOBSCig8DDgkMhF4FhgRWVJPAG5w-wSklNIQWRAIZJpoFmRQPH4dAHdNCYRRlDw6CBoqPpBdfjwwAGs4GABldjAJAHNkGH4CuH7TGAwcAHVTGnrjuAP51-pXgE9kcAsUb9CQsCwwbR4U4YPDIfI4MH9ABWLDSACEtrt9gdKnAADISOBwvAIm4gFFpA5nAwARQKEHgxNJ-XY-DB-ABdGu6ywiVgj1WMFMyAAHAAGFk6MGPLZYAG8uDsuhE-oAR3p8G0gwWIDwLC4UDgcFya36lnVNEskOhsKQ8MRIDBGBoFyuZJY1LgdIZRLtJIdMDwugFVCFyCUIEueBoODOAGEIBgYQCoNAVSACmCACpBhb2uDeIA)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <div>
    <span v-for="i in [1, 2, 3]">Problem is here paaaaaaaaaaaaad - {{ i }}</span>
  </div>
</template>

<script>
export default {
  name: "test",
};
</script>

```

**Output:**
```vue
<template>
  <div>
    <span v-for="i in [1, 2, 3]"
      >Problem is here paaaaaaaaaaaaad - {{ i }}</span
    >
  </div>
</template>

<script>
export default {
  name: "test"
};
</script>

```

Unless I'm missing something, this is simply how Prettier works.

But it could be that `<template>` should be treated like a block element, like `<div>`.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWW11l0C0AZhAE4C8xEDTI1yAbQCMAGjIAmWQGYAukMIAFXhABGOOBlEBnMgAs4vOGSx4btu-apkOZYMFFkAvh9QB6Vowpff1JfTFwCOEYQwzBeGiwYRjgADyw+GDIqOC48AFccDOBSCig8DDgkMiF4QxghaVIPAG4Qnxi4hMYQaRAIBJpoQ2RQPF4tAHd1UYQhlDw6CBoqbpBtXjwwAGs4GABlazAxAHNkGF5cuB6TGAwcAHUTGhqDuF2Zp-ongE9kcEMhnpiQzmGCaPBHDB4ZA5HDAnoAK0MyQAQustjtdmU4AAZMRwaF4WGXECI5K7Y56ACKuQg8AJRJ61l4wN4vzoFxWWDisDuSxgJmQAA4AAyMrTAu7rLC-LlwFl0fE9ACONPgmj6sxAeEMHCgcDgWWWPQsKpoFjBEKhSBhcJAwIwNFO52JhgpcGptPx1sJtpgeG0vKo-OQChAZzwNBwxwAwhAMJDflBoIqQLlgQAVf2zG1wLxAA)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <div>
    <div v-for="i in [1, 2, 3]">Problem is here paaaaaaaaaaaaaaad - {{ i }}</div>
  </div>
</template>

<script>
export default {
  name: "test",
};
</script>

```

**Output:**
```vue
<template>
  <div>
    <div v-for="i in [1, 2, 3]">
      Problem is here paaaaaaaaaaaaaaad - {{ i }}
    </div>
  </div>
</template>

<script>
export default {
  name: "test"
};
</script>

```

But we'll have to look that up.

**Comment by gabrielwillemann** [comment]
About replace this tag for others tags, it's not nice. Because there are many situations this tag could not be replaced. In vue documentation you can see some examples: [Iterations](https://vuejs.org/v2/guide/list.html#v-for-on-a-lt-template-gt) and [Conditions](https://vuejs.org/v2/guide/conditional.html#Conditional-Groups-with-v-if-on-lt-template-gt)

I didn't know this documentation about html-whitespace-sensitivity, only now I read this.

But the template tag always wrap line, though his line not extrapolate 80 columns. I think that is bug. You can see this example:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWUDOWeUhAchDGVgCcIAIxxwMqAPRsOjZpVoMefQSLETJiuc3TjcBOIQAKQ0eLI0WZABZwBcKZn1FSFKVtKO9+F1E8swARosGEY4AA8sCAE+KjgAMzwAVxw+YFcyKDwMOCQyYhB4FhgCgBpSAF8Abk9pQODQ0hBSkAgQmmgWZFA8ASEAdyNehC6UPDoIGipmkGEBPDAAazgYAGV2MBooAHNkGAEkuBbrGAwcAHVrGiKNuFWR6-prgE9kcBYulq2WOxgTPG2GDwyESOB+LQAVixwgAheZLFarbJwAAyWzgILwYKOICh4VWW22YgAikleBikKDwSB2AIfgI3nRDjNVD9zvMsG9BHB6XQMS0AI5k+AmNqjEB4FgAWigcDgcWmLXsQpo9n+gOBlKx1J+GBoewOOJYhJJwopVJxMDwwnOUxg1mQACYWvs8DQcISAMIQDBAt5QaD8kBJH4AFWtowtLUEWxgtqo9uQAA4AAwVCpAA

**Comment by lydell** [comment]
I didn't mean that you should replace `<template>` with other tags. I just tried to demonstrate how the default value of html-whitespace-sensitivity works.

Now I see what you mean – the `<template>` tag seems to wrap to early (and maybe with the wrong inline/block semantics as I mentioned before). Sounds like a bug to me.

**Comment by gabrielwillemann** [comment]
> I didn't mean that you should replace template with other tags. I just tried to demonstrate how the default value of html-whitespace-sensitivity works.

That's ok.


> Now I see what you mean – the template tag seems to wrap to early (and maybe with the wrong inline/block semantics as I mentioned before). Sounds like a bug to me.

Thanks.

**Comment by rndmerle** [comment]
I can confirm that the `<template>` tag is wrapping way too soon.
Like [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDCE20CMJ5FlmuBcZAxABZx4ATOACdC8AB4xUAejb4ipCjJp0oDJjLkdCIADQgIWGAEtoAZ2Sg8w4RADuABWsILKPADcIxgXpAAjYTwwAGs4GABlLCDjKABzZBhhAFc4fR4YDBwAdR5jeDMosDhwlzzjdzyAT2RwMwt9GLMRGAdA2Iw8ZAAzPBwm-QArM3EAIUCQsPC8DDgAGRi4bt7+kCHxcJjYnDgARSSIeCW+1JAo4SbhGvcU3yxhGJgs7xgeZAAOAAZ9O4gmrMCsDU7nALu5FvoAI77eCtQyuEB4MwAWjUcCEPn0wjgUOMWNaeHanSQPWO+iaGGMCWSJzMm22ewOiyQiRS+hgeD8TwEL2QACY2YFjDhNioOjUQQBWXxJJoAFQ5rhJTQAvsqgA)

**Comment by magpiedigital** [comment]
Is there a workaround for this in the meantime?

**Comment by magpiedigital** [comment]
managed to get rid of error with option `"htmlWhitespaceSensitivity": "ignore"` for the time being

**Comment by meteorlxy** [comment]
[eslint-plugin-prettier-vue](https://github.com/meteorlxy/eslint-plugin-prettier-vue) could a possible solution :wink:

![eslint-plugin-prettier-vue](https://user-images.githubusercontent.com/18205362/62407420-f80bac00-b5ea-11e9-8cd9-77e2e55cb16c.gif)
