### ISSUE TITLE
has problem with typescript

### ISSUE THREAD

**Issue by martijintro** [prettier/prettier#6271]
https://prettier.io

-> that code:

```
export class AppComponent {
    private response: any;
  
    constructor(private configService: ConfigService)
    {
		// Argument used for DI
    }
```

causes that error:

```
SyntaxError: Unexpected token (18:13)
  16 | 
  17 | export class AppComponent {
> 18 |     private response: any;
     |             ^
  19 |   
  20 |     constructor(private configService: ConfigService)
  21 |     {
```

**Comment by lydell** [comment]
Hi!

You need to enable the Typescript parser on the playground:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAQQwwGEIBbLKBfYAHSj27w2wEsAbsXh5scUs1JwkeYlACeAbk7dVPSFFIxsAVzAwcACj5CRcAtABm-AOYBlONkH8wMvPSg2HTl24CU6twcUOwwYQD0EVTYtroMrHi60gAmeFY4eAAiAJJBeAC+nAUgADQgEBgw-NCkyKDE2NgQAO4ACo0IdSjEghD8KWUgAEbYxGAA1nAw9hjj-FC2yDq6cOUAFjAMhADq6-zwkuNwjloHQgcKyODkQwvSuG1jtgzEyFbEhNLlAFakaAAhMaTab2YgJAAyCzg70+3xAfzQ9gWtkIcAAiroIPBYV81iA5tgHtcYAoMBIwAIqkNTLAdgMYOtkAAOAAM5T4EGkOzGGGufAkvhh5QAjlj4E9Kt0QGQALQsOApRVDcRi-jiJ7EF5vJAfPHlaQMfjLPT40gotGY7Ew3Vw-EwYjDekpRnIABM5R0xH4hBR9AYr2uUGgwpAyTgABVHd09dICgUgA)
```sh
--parser typescript
```

**Input:**
```tsx
export class AppComponent {
    private response: any;
  
    constructor(private configService: ConfigService)
    {
		// Argument used for DI
    }
}
```

**Output:**
```tsx
export class AppComponent {
  private response: any;

  constructor(private configService: ConfigService) {
    // Argument used for DI
  }
}

```

Normally, Prettier figures out on its own which parser to use based on the file extension. Make sure that you have **not** set `parser` in your .prettierrc: https://prettier.io/docs/en/configuration.html#setting-the-parser-docs-en-optionshtml-parser-option
