### ISSUE TITLE
Adding typing to a react hook creates incorrect code

### ISSUE THREAD

**Issue by robvk** [prettier/prettier#6272]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtSBXWAGkzThgGEICYBdTAXkz1IGUYBDeAHijwFsARnABOAPgAUABgCUAbgA6USFAw58REmUrU6jZnDac4PfkOGYAPpl4AbGxNs25IQiAgAHGAEt0yUO2FhCAB3AAUAhDRkEHYANwgvABMXEAFhdjAAazIWdwyvKABzZBhhPDhXAAsYPhsAdUqveDQ8sANIpq9YpoBPaLA0KNcC0mEYUPTCvnZkADN2G1JXACs0AA8AIXSsnPY+OAAZArg5haWQVbWWAsKbOABFPAh4U8WKkDzhUeiBdgEemzQFLuYQFGB1JIwSrIAAcklcIIgpDq6Xc0RBcFGsROrgAjk94BMPFEUOw0ABaKBwOCJGkpYRwfFeBkTdhTGZIeZvVykPheEpld5oG53R7PE6cs7vDgCCGJKHIABMrlK7C8NhulD402iUGgOJA+gAKn8SVzSABfC1AA)
```sh
--parser babylon
```

**Input:**
```jsx
const [count, setCount] = useState<number>(0);
const [count, setCount] = useState<number | null>(null);
```

**Output:**
```jsx
const [count, setCount] = useState < number > 0;
const [count, setCount] = (useState < number) | (null > null);

```

**Expected behavior:**
As far as I can see the Input is actually the correct way of typing hooks: https://github.com/facebook/flow/pull/7149/files#diff-5ca8a047db3f6ee8d65a46bba4471236R283.

**Comment by kachkaev** [comment]
Changing parser to typescript fixes the problem: https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtSBXWAGkzThgGEICYBdTAXkz1IGUYBDeAHijwFsARnABOAPgAUABgCUAbgA6USFAw58REmUrU6jZnDac4PfkOGYAPpl4AbGxNs25IQiAgAHGAEt0yUO2FhCAB3AAUAhDRkEHYANwgvABMXEAFhdjAAazIWdwyvKABzZBhhPDhXAAsYPhsAdUqveDQ8sANIpq9YpoBPaLA0KNcC0mEYUPTCvnZkADN2G1JXACs0AA8AIXSsnPY+OAAZArg5haWQVbWWAsKbOABFPAh4U8WKkDzhUeiYHvc4NBgYReTwpdzA2B1JIwSrIAAcklc4IgpDq6Xc0XBAJEsROrgAjk94BMPFEUOw0ABaKBwOCJOkpYRwQleJkTdhTGZIeZvVykPheEpld5oG53R7PE7cs7vDgCKGJGHIABMrlK7C8NhulD402iUGgeJA+gAKuwBGSeaQAL7WoA

When using Prettier in CLI or an editor, the right parser gets picked up quite reliably based on the file path.

**Comment by lydell** [comment]
Using the babel-flow parser also works:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtSBXWAGkzThgGEICYBdTAXkz1IGUYBDeAHijwFsARnABOAPgAUABgCUAbgA6USFAw58REmUrU6jZnDac4PfkOGYAPpl4AbGxNs25IQiAgAHGAEt0yUO2FhCAB3AAUAhDRkEHYANwgvABMXEAFhdjAAazIWdwyvKABzZBhhPDhXAAsYPhsAdUqveDQ8sANIpq9YpoBPaLA0KNcC0mEYUPTCvnZkADN2G1JXACs0AA8AIXSsnPY+OAAZArg5haWQVbWWAsKbOABFPAh4U8WKkDzhUeiBdiEbAC0sxsIRS7mEBRgdSSMEqyAAHJJXOCIKQ6ul3NFwXBRrETq4AI5PeATDxRFDsNAAqBwOCJOkpYRwIleJkTdhTGZIeZvVykPheEpld5oG53R7PE7cs7vDgCaGJWHIABMrlK7C8NhulD402iUGg+JA+gAKn9yTzSABfK1AA)
```sh
--parser babel-flow
```

**Input:**
```jsx
const [count, setCount] = useState<number>(0);
const [count, setCount] = useState<number | null>(null);
```

**Output:**
```jsx
const [count, setCount] = useState<number>(0);
const [count, setCount] = useState<number | null>(null);

```

Or adding a Flow comment:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwDYQDuAOlJFAM4wYDakArrADQYVwwDCEjMAuhgF4M9NgGUYAQ3gAeKPQC2AIzgAnAHwAKAAwBKANylyVWg2at2XHvyEi44qXFkLlKjAB8McvHk1e8+kCYQCAAHGABLaApkUAkVFSIABTiEaJQJADcIcIATQJBFFQkwAGt2URDi8KgAc2QYFXo4IIALGHk8AHUW8PgKSrA7VN7wjN6AT2RwCmig6rYVGESimvkJZBwJPDYggCsKAA8AISLS8ol5OAAZargNrZ2QfYPRapq8OABFegh4e+3miBKioFlNFBJlHh8iEVNUYJ1cjAWsgABxaIIwiBsTpFEJTGFwBYZO5BACOP3gy1CaRAEgoAFooHA4DkWfkVHByeEOcsJKt1khNgCgmx5OF6o1ARQ3h9vr87oKHoDJIoETkkcgAExBBoScJ4N5ceRrKZQaAkkC2AAqELSQrYAF8HUA)
```sh
--parser babel
```

**Input:**
```jsx
// @flow
const [count, setCount] = useState<number>(0);
const [count, setCount] = useState<number | null>(null);
```

**Output:**
```jsx
// @flow
const [count, setCount] = useState<number>(0);
const [count, setCount] = useState<number | null>(null);

```

**Comment by lydell** [comment]
See also: #6230

**Comment by robvk** [comment]
That does it yeah. Thanks! Hadn't thought of the parser option.
