### ISSUE TITLE
Error parsing package.json with prettier on husky pre-commit hook

### ISSUE THREAD

**Issue by jsmiith** [prettier/prettier#6273]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: Husky
- Runtime: Node v10.15.0
- Operating System: Windows

**Steps to reproduce:**
1. Install `prettier@1.18.2`, `pretty-quick@1.11.1` and `husky@3.0.0`.

2. Make a `.prettierrc` file containing the following:

```json
{
    "trailingComma": "es5",
    "tabWidth": 4,
    "semi": true,
    "singleQuote": true,
    "bracketSpacing": true,
    "arrowParens": "always",
    "parser": "typescript"
  }
```

3. Add the following to the bottom of your `package.json`

```json
"husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
}
```

4. Make some edits to a TypeScript file, stage the changes on git, and commit them.

**Expected behavior:**
Husky should've prettified all of the files before committing.

**Actual behavior:**
Husky throws this error referencing prettier's TypeScript parser.
![image](https://user-images.githubusercontent.com/19301186/60687045-ffcd1900-9ea3-11e9-945b-69bc89a9b5df.png)

**Comment by lydell** [comment]
Hi!

I think you might be able to solve the problem by removing `"parser": "typescript"` from your .prettierrc. https://prettier.io/docs/en/configuration.html#setting-the-parser-docs-en-optionshtml-parser-option

**Comment by jsmiith** [comment]
That did indeed fix my issue. Thank you.
