### ISSUE TITLE
Doesn't work on sublimetext

### ISSUE THREAD

**Issue by seven-deuce** [prettier/prettier#6276]
I have gone through instruction in :
https://packagecontrol.io/packages/JsPrettier
I have done all.. nothing happens when I use command  **JsPrettier Format Code**
has someone tried this package recently? 
It seems I have done all steps one by one, I got all files and folders at the correct path... but nothing happens

**Comment by lydell** [comment]
Hi!

I think you’ll get better help over at the repo for the Sublime Text plugin: https://github.com/jonlabelle/SublimeJsPrettier
