### ISSUE TITLE
Multiline comments are formatted into single-line comments

### ISSUE THREAD

**Issue by huangkunsong** [prettier/prettier#6277]
While writing vue code in vscode, I encountered an annotation format problem using prettier.Please help me to solve it. Thank.

**Prettier - Code formatter 1.9.0**

**Input:**
```vue
/**
 * This is the comments
 * This is the comments
 * @author Rookie
 * @since 2019-07-07
 * 
 */
```

**Output:**
```vue
/** * This is the comments * This is the comments * @author Rookie * @since
2019-07-07 * */
```

**Expected behavior:**
I expect no formatting of comments

The attached includes the problem screenshot and vscode settings
### Before formatting
![before_format](https://user-images.githubusercontent.com/17569485/60768966-ccd19200-a0fc-11e9-9112-24926611a628.png)
### autoFixOnSave after
![after_format](https://user-images.githubusercontent.com/17569485/60768967-d1964600-a0fc-11e9-852c-586e5ae8bccc.png)
### This is my vsCode setting
![vscode_settings](https://user-images.githubusercontent.com/17569485/60768958-ba575880-a0fc-11e9-8c48-f0f63af52b16.png)

**Comment by lydell** [comment]
Hi!

Do you use a .vue file? 

You know how VSCode usually shows comments in a different color (green)? In your screenshot it is white. Because as far as I know, .vue files are essentially HTML so JS-style `/**/` comments are treated as _plain text._

You need to change your comment to this (HTML comment):

```vue
<!--
 * This is the comments
 * This is the comments
 * @author Rookie
 * @since 2019-07-07
 * 
-->
```

Or (JS comment inside script):

```vue
<script>
/**
 * This is the comments
 * This is the comments
 * @author Rookie
 * @since 2019-07-07
 * 
 */
</script>
```

Does this make sense?

**Comment by huangkunsong** [comment]
@lydell I seem to have made a stupid mistake,Use your solution to solve my problem,Thank you for your reply. 👍
