### ISSUE TITLE
Request: Add config flag for JSX ternaries

### ISSUE THREAD

**Issue by denieler** [prettier/prettier#6279]
Hey! I was searching for the answer why my JSX ternaries look so weird and ugly and found this issue https://github.com/prettier/prettier/issues/4139, which is closed. Please guys, can you make a configuration flag to be able to opt out from this decision.

Thank you in advance!

**Comment by lydell** [comment]
Hi!

The reason for closing #4139 still stands: https://github.com/prettier/prettier/issues/4139#issuecomment-386096028

Have you used Prettier for a while, or are just getting started? It might be helpful to know that we've had several issues closed by the people opening them a couple of months later. After using Prettier for a while they realized that the formatting the were initially bothered by was no longer an issue.

When it comes to JSX formatting, that is something that we've gone through several phases of improvements of and are quite happy with! So it is not something that we're going to change. Sorry! As you can see we have over 600 other issues to work on.

So in this case I'm going to close your issue, but thanks for using Prettier! :bowing_man:

**Comment by denieler** [comment]
hi @lydell , no actually I've been using it for years, it's a great tool, but customization in some places can make it magnificent. You have a configuration `singleQuote`, I don't see the big difference between the decision for having such configuration and having another for ternaries for JSX.

I know you probably will not do anything with this issue but just wanted to show that there are some people in the community, which are not extremely happy with the decision.

Also, it's quite strange that ternary operators are working as expected in JS, for example [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEA3AhgJwEtcAjdTAXk0igBNCZDoBGAHSk0wH5rp7HoAJnadOPViFy4JI0UkwSSJGR0zya-JlGGqxC8GBWi1+2rQkBuEABoQEAA4CoAZ2SgC+CAHcACgQSuKLjYEIS0NiAk+LhgANYYAMr2MYRQAObIMPgArnC2ABYwALaoAOr5DHDOyWBwCQEMhNgMAJ7I4M6utqnOcPgwPtFpRbjIAGa4qL22AFbOAB4AQtFxibhFcAAyqXDjk9Mgc-MJqWnoAIrZEPB7U3kgyfi9+O0kpC2o0BH2RLClYTB8sgABwABlsPwgvVK0Xs7R+VT62F2tnwcAAjtlCGjBrhhqMkBM7rZekVCJkcvdnKcLlcboT9vcYKR-rRAchBLYsrhCKhTgBhCBFEbtKDQFEgbK9AAqpECRN6AF9FUA) from https://github.com/prettier/prettier/issues/5881
And it's not really clear for me why it was made another decision for JSX.

**Comment by kachkaev** [comment]
@denieler see https://prettier.io/docs/en/option-philosophy.html and also check out the number of 👍 in https://github.com/prettier/prettier/issues/40 🙂

**Comment by denieler** [comment]
@kachkaev I think if https://github.com/prettier/prettier/issues/4139 would not be limited to collaborators it would also take numbers and number of 👍
