### ISSUE TITLE
How do I use the CLI to fix all files?

### ISSUE THREAD

**Issue by octogonz** [prettier/prettier#6280]
I apologize if this is a stupid question.

We have a large monorepo containing lots of projects.  We need to specify the exact set of paths to be processed by Prettier.  It's not okay for Prettier to go trawling through random folders, rewriting files with no idea whether they are inputs or outputs.

The **.prettierignore** config file seems like the right way to do this.  Well, actually we want to specify what DOES get processed, rather than what doesn't.  But I can solve that by inverting the logic, something like this:

**/.prettierignore**
```sh
# Exclude everything by default
/**/*

# But don't exclude folders (i.e. only exclude files)
!/**/*/

# Exclude node_modules folders at every level
node_modules/

# Also exclude the common folder at the top level
/common/

# Include specific file extensions if they appear in a project folder,
# which is always two levels deep
!/*/*/src/**/*.ts
!/*/*/src/**/*.tsx
!/*/*/src/**/*.js
!/*/*/config/**/*.json
```

But now, how do I get Prettier to rewrite these files?  The [CLI docs](https://prettier.io/docs/en/cli.html) show an example like this:

```
prettier --single-quote --trailing-comma es5 --write "{app,__{tests,mocks}__}/**/*.js"
```

The `"{app,__{tests,mocks}__}/**/*.js"` glob is redundant, because my **.prettierignore** file is already communicating this information.

If I try `prettier --check "*"` or `prettier --check NOTHING` then Prettier seems to completely ignore the **.prettierignore** file.

The option `--config-precedence=file-override` looks like a solution.  It supposedly makes the config file take precedence over the CLI.  

But when I try `prettier --check --config-precedence=file-override NOTHING`, it fails with this error:

```
[error] No matching files. Patterns tried: NOTHING !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```

What am I doing wrong here?  This seems like the most basic first step for adopting Prettier...

**Comment by kachkaev** [comment]
Here is what we commonly have in our projects:

Inside `.prettierignore`:

```ini
## Please check .eslintignore and .gitignore when changing this file

## file extensions
*.*
!*.css
!*.js
!*.json
!*.jsx
!*.less
!*.md
!*.mdx
!*.ts
!*.tsx
!*.yml


## copied from .gitignore
[a few paths]


## shared between eslint and prettier
[a few more paths]
```

`.eslintignore` is almost symmetrical to `.prettierignore`, it just whitelists fewer extensions. In `package.json` we have:

```json
{
  "scripts": {
    "fix": "yarn fix:eslint && yarn fix:prettier",
    "fix:eslint": "eslint --fix \"**/*.*\"",
    "fix:prettier": "prettier --write \"**/*.*\"",
    "lint": "yarn lint:eslint && yarn lint:prettier",
    "lint:eslint": "eslint \"**/*.*\"",
    "lint:prettier": "prettier --check \"**/*.*\"",
    "...": "..."
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "**/*.*": [
      "eslint",
      "prettier --write",
      "git add"
    ]
  },
  "...": "..."
}
```

**Caveat:** If there exist files without extensions, which need to be skipped, it is necessary to explicitly list them in `.prettierignore`:

```diff
 ## file extensions
 *.*
+LICENSE
 !*.css
 !*.js
```

**Comment by evilebottnawi** [comment]
In next major release we will support expand directories, so using `prettier .` will fix all files

**Comment by octogonz** [comment]
So `prettier --check "**/*.*"` /does/ honor **.prettierignore**? The problem was that I used `"*" ` as the glob?

BTW I saw that it is possible to invoke Prettier via the ESLint front-end. If I do that, is **.prettierignore** used at all? Or in that case is **.eslintrc.json** used instead to select the file paths? (And in that case should we be using the ESLint plugin for VSCode instead of the Prettier plugin?)

**Comment by kachkaev** [comment]
@octogonz we use both Prettier and ESlint plugins in VSCode. When a file is saved, ESlint autofixes what it can first and then Prettier cleans things up. Similarly, the tools run on their own in a pre-commit hook and in CI.

I used Prettier+ESlint integration a couple of years back and found it better to keep the tools separate. Tracking issues in Atom and VSCode Prettier extensions with my side vision I can say that people still git bitten time and again when the tools are merged.

**Comment by octogonz** [comment]
Thanks very much! I'll try this.

**Comment by kachkaev** [comment]
🙌 Feel free to close this issue if you think there is no need for changing anything in Prettier itself 🙂

**Comment by octogonz** [comment]
I will test it today and report back before closing the issue.

**Comment by octogonz** [comment]
> ```
> ## file extensions
> *.*
> !*.css
> ```

@kachkaev This `*.*` pattern excludes things that don't have periods in them.  It seems to have a couple downsides:
- If a folder name contains a `.`, then it will ignore that folder *and all child folders and their contents*, regardless of subsequent expressions
- If a file name does not contain a period (e.g. `LICENSE`) then it will NOT be ignored (although perhaps Prettier's file type detector will skip it)

The pattern I used seems more correct:
```
# Exclude everything by default
/**/*

# But don't exclude folders (i.e. only exclude files)
!/**/*/
```

**Comment by octogonz** [comment]
The simplest wildcard ended up being `**`, like this:
```bash
prettier --check "**"
```

I confirmed that it honors **.prettierignore** (whereas `*` did not).

Thanks again for the help!  I opened a PR #6285 to explain this in the docs.

**Comment by kachkaev** [comment]
@octogonz did "`**`" work both on Windows and Linux/MacOS?

**Comment by octogonz** [comment]
> did "`**`" work both on Windows and Linux/MacOS?

I tried Windows and MacOS, and it produced the same results.  I didn't try Linux.

**Comment by octogonz** [comment]
From the comments for PR https://github.com/prettier/prettier/pull/6285:
> IMHO suggesting people to use `**` without explaining what should go into `.prettierignore` nearby will cause some confusion and result lots of extra issues in this repo. It took me a while to establish a [sustainable structure for `.prettierignore`](https://github.com/prettier/prettier/issues/6280#issuecomment-509568953) – this task was not trivial. All this glob stuff (`**/*` vs `*.*` vs `*` vs `!*.blah`) is pretty hard-core.

I'm reopening this issue.  This experience was pretty confusing, so we definitely need to improve the docs somehow.  But now I'm unclear what the docs should say.

Naively, I imagined that the typical usage scenario for Prettier should be:
1. Specify which files in our repo should get prettified
2. Run a command that bulk-fixes everything, commit, and merge
3. Enable Git hooks that ensure Prettier gets run for files touched by future commits

The current documentation implies that:

Step 1 is specified using `.prettierignore`
Step 2 is performed using the CLI
Step 3 is not Prettier's responsibility; instead, it always gets handled by a front-end like **lint-staged** or somesuch

The docs are vague about how Step 1 and 2 are supposed to happen.  They are so vague that @kachkaev was concerned about advising people to use `"**"` to perform Step 2.

Thinking about this, I realize that **lint-staged** (or equivalent) implicitly filters out any files that are untracked by Git.  In other words, **lint-staged** implicitly computes the union of `.gitignore` and `.prettierignore`, whereas the CLI only uses `.prettierignore`.  This works because for simplistic repos, it's probably mostly true that: _"If it's tracked by Git, and if Prettier supports the file type, then we want to prettify it."_  (This is not true in a complex repo, though.)  Perhaps most people rely on Step 3 for everything.

Maybe one of the maintainers could help clarify the intended usage?

At the very least, the docs should explain exactly how Prettier selects files.  From what I can tell, it goes like this:
1. It applies an undocumented set of filters: `!**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**`
2. Then it adds in whatever it finds in `.prettierignore`
3. Then it adds the mandatory pattern from the command-line
Is that right?

Also, I wonder if the CLI design could be improved:
- Is it a design flaw that the CLI disregards `.gitignore` (and/or the Git index)?
- Should Prettier include a standard default `.prettierignore` with some example patterns and comments? Specifying the files you DO want seems to require "hard-core" skills to make the inverse pattern.

**Comment by octogonz** [comment]
I should also mention that the `.prettierignore` calculation seems to be pretty inefficient.  When running `prettier --write "**"`, the printed millisecond timings add up to 9.7 seconds.  Whereas the actual operation (starting from the first printed file path) takes ~33 seconds.  In other words, 70% of the CPU time was spent figuring out which file paths to process. (!)

**Comment by lydell** [comment]
I have just skimmed this thread, but it looks like bringing @kachkaev's comment into the docs would be a good idea: https://github.com/prettier/prettier/issues/6280#issuecomment-509568953

**Comment by octogonz** [comment]
Another idea might be to advise people to `cp .gitignore .prettierignore` as a starting point. And then we could give a second example, for the more advanced case if you want to  use inverted logic to "opt in" specific paths.

**Comment by evilebottnawi** [comment]
@octogonz i think we can close this in favor https://github.com/prettier/prettier/issues/6085, just use `prettier .` and create `.prettierignore` or use `prettier . --ignore-path=.gitignore`

**Comment by murashki** [comment]
It's difficult to understand how cli commands work. May be some examples will help us...

**Comment by lydell** [comment]
@murashki I agree, the CLI is not good. You might be interested in #7073
