### ISSUE TITLE
Add an option to set PX not to convert to px

### ISSUE THREAD

**Issue by lext-7** [prettier/prettier#6282]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AhgAmAHSpzAW3QCcBzASyiUwEYAmABQA0BuPAXxABoQIAHGBWgBnZKFIkIAd0akEYlOgBuECgBMeIAEYl0YANZwYAZX76qZZDBIBXOLwAWMQgBsA6o4rwR5sHBMFbwplbwBPZHARMV4qETgSGEY9MmJkADN0V3jeACsRAA8AIT1DYxN0QjgAGSo4DKyckHyCk0tXOABFWwh4BuyHEHMSeJJIjuitfhIqGHcNGEdkAA4ABl5piHj3PX5I6bhR5XreAEce+GSBRRB0EQBaKDg4dRetEjhzig-k9FT0fpNeKECjWOyDETtLoXepITIDXgwdDaebqRbIeiIvQUVyWADCEEIaRQUGgJxAtniABVkYp4fEOBwgA)
```sh
```

**Input:**
```less
.a {
  margin: 12PX;
}
```

**Output:**
```less
.a {
  margin: 12px;
}
```

**Expected behavior:**

```less
.a {
  margin: 12PX;
}
```

I have seen [How to set PX not to convert to px ？](https://github.com/prettier/prettier/issues/3077), but I still hope there will be an option to disable unit uppercase or lowercase transformation. 

It would be dangerous to use prettier in an existed project using `postcss2rem`. It's easy to add this option, why not add option for those projects using `postcss2rem`. We can contribute for it.

**Comment by evilebottnawi** [comment]
It is CSS so all dimensions are case insensitivity (PX === px), we don't accept new options, what code is break? Please provide use case/example, thanks

**Comment by lext-7** [comment]
See [here](https://github.com/cuth/postcss-pxtorem#a-message-about-ignoring-properties).  `postcss-pxtorem` plugin will convert `px` to `rem`, keep `Px` or `PX`.

**Comment by lext-7** [comment]
In my project, both of `px` and `PX` is required. `postcss-pxtorem` is widely used in mobile project.

**Comment by evilebottnawi** [comment]
better open issue in `postcss-pxtorem`, because it is invalid logic (px === PX, so PX should be converted too), also it is bad practice using difference case for dimensions , according spec dimensions are case insensitivity and it is bad idea provide option to violate spec

**Comment by lext-7** [comment]
It seems no one will resolve this problem as there are issues in `prettier` and `postcss-pxtorem` for years. Without extra option support, we need to make big changes to use prettier and it will be dangerous if there is anyone who doesn't the rule has changed.

**Comment by evilebottnawi** [comment]
@lext-7 prettier doing it in right way, `postcss-pxtorem` is not, as i said above it should be solved on `postcss-pxtorem` side or you can disable prettier for css. Postcss provide ability to do many unsafe thing in css, unfortunately we can handle all cases in prettier and can't implement over 9000 options for any case, good idea and good practice avoid do unsafe thing using postcss

**Comment by evilebottnawi** [comment]
As workaround you can use `// prettier-ignore` for unsafe things

**Comment by lext-7** [comment]
Yes, it works. But it will be big changes for our projects. And it will be dangerous if someone forgets to add this comment.

**Comment by evilebottnawi** [comment]
@lext-7 you can use `stylelint` to catch all problems or output error for other developers, it is very non standard thing what better handle on project side than prettier, tomorrow other plugins do other unsafe thing and we need implement new option, so prettier will have many options only for css what is violate our police about new options and our philosophy. Also you can see what plugin use old version of postcss (https://github.com/cuth/postcss-pxtorem/blob/master/package.json#L29) and abandoned around 2-3 years, not sure good idea implement option for abandoned, nonstandard, spec violation stuff

**Comment by lext-7** [comment]
Ok, thanks.
