### ISSUE TITLE
Prettier crashes on some Flow comment types

### ISSUE THREAD

**Issue by mrm007** [prettier/prettier#6288]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAlOBDMMB0AzCAJwHcNCATdPAegCokkAeABUIgAcBnAGgygE8AfLWoAKUezZduAAkJw8AShkBeQTMYAZAJZQA1jN1Q4hKiuDy8AXxnAc9yR043qgxQG4AOlBDcQHGG1oTmRQMjZiZjIEEJQMADcIbXJfEAAjQiw9OBgAZXYsXQBzZBhCAFc4PwALGABbABsAdWrteE4CsDhcmLbteLb+ZHBOEL9dThMYVgwiuoxkPAwGyb8AK04ADwAhTLBsvIw6uB1jReXVkA3N3OKGuABFcoh4c5WqkALCScJhtIw0vwGtBUpJdDAmskYNVkAAOAAMfkckyamXYw0kcB+8TgqQAjs94KwnMMMJwALTGODkampeQE7TyGZzBZIJbvPyTOraUoVD6cO6PQm4tkXD4wAGQ8jQ5AAJj8ZQw2gaxQAwhA6vNhlBoLi-OVJgAVAGxdmTKxWIA)
```sh
--parser babylon
```

**Input:**
```jsx
React.forwardRef/*::<Props,any>*/((props, ref) => <Link innerRef={ref} {...props} />);

```

**Output:**
```jsx
ensureAllCommentsPrinted/<@https://prettier.io/lib/standalone.js:16187:13
ensureAllCommentsPrinted@https://prettier.io/lib/standalone.js:16185:15
coreFormat@https://prettier.io/lib/standalone.js:16236:3
format@https://prettier.io/lib/standalone.js:16476:73
formatWithCursor@https://prettier.io/lib/standalone.js:16492:12
withPlugins/<@https://prettier.io/lib/standalone.js:30992:15
format@https://prettier.io/lib/standalone.js:31000:12
formatCode@https://prettier.io/worker.js:234:21
handleMessage@https://prettier.io/worker.js:185:18
self.onmessage@https://prettier.io/worker.js:155:14

```

**Expected behavior:**
Prettier should not crash.

**Comment by gautamsi** [comment]
ref: #4295

**Comment by thorn0** [comment]
Not an issue anymore because support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687
