### ISSUE TITLE
html: text after anchor: prettier inserts additional whitespace 

### ISSUE THREAD

**Issue by dmoebius** [prettier/prettier#6290]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpQAR4AKANnAIYDOceArlbgamXgBYBOcAZgLzYgswY6CkgD0o9B0EBLOGwB00iBOJkAngHM2EGlAAmovnhhk2GuDF4gA+gCNVUANZ8c+AkSkxZbADTGW1BQ6bGDUkHrUnBBsALZkgnIMeKiiZJjyqLZseKKuBACSMADkFHha5DDyuClYID4gEOhe0BTIoKbaAO6EpgitKGQAbhDSenUgWWRgjhYAyuhT0lAayDBsNHD1AjHEAOos0vAUC6GzfYfSg4dqyOAUrfVLVGwwhGxkGnHInGTEVPUAKwoAA8AELvaZzMgxOAAGSWcG+v3+ICBwNmSw0pAAijQIPAkX9NiAFmxnrdbGRbGpiNBxpIljBdqMYCxkAAOAAM9UkECou3e6Fukjgz0GiPqAEc8fA3o1+iBKABaKBwOARMb1DjS6QcN4fL5IH5E+pUGLSVbrYkUTE4mWIo3I4kmWzMvSs5AAJnqazI0mImIAwhAYoaQFBoBKQHQ4AAVKn9Y1UAC+yaAA)
```sh
--parser babylon
```

**Input:**
```jsx
<p>
  Please use
  <a href="https://prettier.io/playground/" target="_blank">
    Prettier, the source code formatter
  </a>.<br />
  It's great.
</p>
```

**Output:**
```jsx
<p>
  Please use
  <a href="https://prettier.io/playground/" target="_blank">
    Prettier, the source code formatter
  </a>
  .<br />
  It's great.
</p>;

```

**Expected behavior:**
Prettier inserts an additional newline before the dot after the closing `</a>`. That's wrong. The dot should stay right behind the `</a>`.

**Comment by evilebottnawi** [comment]
Why it is wrong?

**Comment by dmoebius** [comment]
Because the newline causes browsers to render an additional whitespace. Instead of 
`Please use Prettier, the source code formatter.`
the browser now renders:
`Please use Prettier, the source code formatter .`

It should get clearer if I'd used `[` and `]` around the link.

Also: why is there an `;` at the end of the output?!?

**Comment by dmoebius** [comment]
> Also: why is there an ; at the end of the output?!?

Because I used the wrong parser, "babel" instead of "html", sorry. Here's an updated playground:

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpQAR4AKANnAIYDOceArlbgamXgBYBOcAZgLzYgswY6CkgD0o9B0EBLOGwB00iBOJkAngHM2EGlAAmovnhhk2GuDF4gA+gCNVUANZ8c+AkSkxZbADTGW1BQ6bGDUkHrUnBBsALZkgnIMeKiiZJjyqLZseKKuBACSMADkFHha5DDyuClYID4gEOhe0BTIoKbaAO6EpgitKGQAbhDSenUgWWRgjhYAyuhT0lAayDBsNHD1AjHEAOos0vAUC6GzfYfSg4dqyOAUrfVLVGwwhGxkGnHInGTEVPUAKwoAA8AELvaZzMgxOAAGSWcG+v3+ICBwNmSw0pAAijQIPAkX9NiAFmxnrdtsRxpIljBdqMYCxkAAOAAM9UkECou3e6Fukjgz0GiPqAEc8fA3o1+iBKABaKBwOARMb1Dji6QcN4fL5IH5E+pUGLSVbrYkUTE4iWIvXI4kmWz0vSM5AAJnqazI0mImIAwhAYrqQFBoCKQHQ4AAVMi2fr6qgAXwTQA)

With the right parser I gets even weirder:

```
<p>
  Please use
  <a href="https://prettier.io/playground/" target="_blank">
    Prettier, the source code formatter </a
  >.<br />
  It's great.
</p>
```

Why is there a newline after `</a` ?

**Comment by evilebottnawi** [comment]
You have invalid `parser`, just change `parse` on `html` and check `--html-whitespace-sensitivity` on `css` or `strict` value https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpQAR4AKANnAIYDOceArlbgamXgBYBOcAZgLzYgswY6CkgD0o9B0EBLOGwB00iBOJkAngHM2EGlAAmovnhhk2GuDF4gA+gCNVUANZ8c+AkSkxZbADTGW1BQ6bGDUkHrUnBBsALZkgnIMeKiiZJjyqLZseKKuBACSMADkFHha5DDyuClYID4gEOhe0BTIoKbaAO6EpgitKGQAbhDSenUgWWRgjhYAyuhT0lAayDBsNHD1AjHEAOos0vAUC6GzfYfSg4dqyCAUa9JgMONLVGwwhGxkGnHInGTEKj1ABWFAAHgAhL7TOZkGJwAAySzgfwBQJAoLBsyWGlIAEUaBB4KjAZsQAs2G9bttiONJEsYLtRjAWMgABwABnqkggVF2X3Qt0kcDegxR9QAjoT4J9Gv0QJQALRQOBwCJjeocKXSDifb6-JD-Un1KgxaSrdZkig4-HSlGGtFkky2Jl6FnIABM9TWZGkxBxAGEIDEDSAoNBxSA6HAACpkWz9I1UAC+yaAA

**Comment by evilebottnawi** [comment]
Because you source has newline,without newline it can be collapse in one line what is wrong

**Comment by dmoebius** [comment]
I inserted a newline in the source, because the inner anchor text might be longer:

```
<p>
  Please use
  <a href="https://prettier.io/playground/" target="_blank">
    Prettier, the source code formatter which is really really really really cool</a>.<br />
  It's great.
</p>
```

Outputs:
```
<p>
  Please use
  <a href="https://prettier.io/playground/" target="_blank">
    Prettier, the source code formatter which is really really really really
    cool</a
  >.<br />
  It's great.
</p>
```

Same problem. The closing `</a` is just wrong.

**Comment by evilebottnawi** [comment]
It is not problem, it is expected, please read https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting

**Comment by dmoebius** [comment]
At least the whitespace is preserved correctly.

**Comment by evilebottnawi** [comment]
What output you expected?

**Comment by dmoebius** [comment]
```
<p>
  Please use
  <a href="https://prettier.io/playground/" target="_blank">
    Prettier, the source code formatter which is really really really really
    cool</a>.<br />
  It's great.
</p>
```

**Comment by dmoebius** [comment]
So we're down from an error (which was a misconfiguration on my part) to an annoyance. Prettier preserves the whitespace correctly, but the result is not "prettier".

The original description of this issue is misleading now. Please tell me if I should close this issue and add another one for the annoying formatting of `</a`.

**Comment by lydell** [comment]
@dmoebius Have you tried the different choices of [html-whitespace-sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity)?

**Comment by dmoebius** [comment]
Yes. "css" and "strict" break the `</a>` into `</a` and `>`. Only "ignore" keeps the `</a>`, but inserts additional whitespace after it which would show up in the browser:
```
<p>
  Please use
  <a href="https://prettier.io/playground/" target="_blank">
    Prettier, the source code formatter which is really really really really
    cool
  </a>
  .
  <br />
  It's great.
</p>
```

**Comment by lydell** [comment]
Yes, Prettier adds a newline between `</a` and `>` sometimes (not specific to `<a>`). Feel free to open a new issue about changing that if you want.
