### ISSUE TITLE
Error: Prettier service not started

### ISSUE THREAD

**Issue by denyskotsur** [prettier/prettier#6291]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: WebStorm
- Runtime: NodeJS v9.10
- Operating System: MacOS

**Steps to reproduce:**
Cmd+Shift+Option+P (can be any shortcut).

**Expected behavior:**
Files should be formatted after calling reformat command.

**Actual behavior:**
Unable to format any file. 

The error code is: 
> Prettier service not started
> Process finished with exit code -1.

Paths for Node interpreter and Prettier package are set in the settings.

**Comment by evilebottnawi** [comment]
Please open issue in `WebStorm` repo, maybe you use outdated/cracked version if `WebStorm`
