### ISSUE TITLE
Splitting a class name across multiple lines

### ISSUE THREAD

**Issue by 43081j** [prettier/prettier#6292]
Example: [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCoAWAlpgJKYCCAanAE4CeAMtAOYBy6AtnAGIS0UAwhmw44AD3hQAJrkIlyFKBBgE6NBsyjsuvfkJG5gAHSg4ckKJhi0ArmBj8AFAEocwHAF9TnkABoQCAAHGCJoTGRQdFpaCAB3AAVohAiUdAA3CCJpfxAAI1p0MABrOBgAZSCiom1kG1s4AIIYTlQAdWJ4TCqwOHKUolD0wfpkcGxcmsw6GATClk50ZAAzdFRpgIArTHEAIUKSsvLdRhq4FbWNkG3xcpqWVDgARVsVc6RV9caQKtpp2jGeXQeXoqGguSCsWmbUKQTGkLg-3S5wCAEdXvA5sFUiAsABaKBwODSYm5WhwdFEclzdALJYfS7faacIh1OxM+6PF5vC5fAIwYFtbKqZAAJn5hSIqHugggnEWY2UhNytmmeGBqU+V0hNRgQukIqQAHYAAyeTxAA).

We are considering a move from clang-format to prettier.

In this case:

```ts
class AVeryLongClassName extends AnotherVeryLongClassName {
```

clang-format produces:

```ts
class AVeryLongClassName extends
  AnotherVeryLongClassName {
```

prettier leaves it untouched, breaking the column limit (assuming its shorter than the example here).

is this expected? would you rather exceed the defined column limit than separate a class across multiple lines like this? if so, that's ok, i'll just stick with clang-format.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/issues/5156

**Comment by 43081j** [comment]
speedy.

i did try search but couldn't find the issue, my mistake.
