### ISSUE TITLE
Arrow fn as function parameter with newline

### ISSUE THREAD

**Issue by samdenty** [prettier/prettier#6294]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKBDAFF4GA066ARgL4CUABALwB8lwF6I+IEADjAJbQDOyoDACchEAO4AFYQn4oMANwhcAJixDEhGMAGs4MAMrstXKAHNkMIQFc4rABYwAtgBsA6na7xeRsHH0zPLnlPAE9kcF5+VhNeOCEYCU1TRwxkADMMZ1jWACteAA8AIU0dPX0MRzgAGRM4dMzskDz8-RNTZzgARSsIeHqs2xAjIVihcOIMYhDnaDV2IRMYVxUYO2QADgAGVnmIWNdNdnD5uFH5OtYARx74RI5ZEAxeAFooODhlD7UhOGuuH8SGGSqSQGQGrFiji4Fmsg14bQ63V6dVBDUGMEmy2Uq2QACZWJYMFxnG0AMIQRwpcJQaAXEBWWIAFUmsjBsVIpCAA)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx

a(({a,

b}) => {})

```

**Output:**
```jsx
a(({ a,
  b }) => {});
```

**Expected behavior:**

```jsx
a(({ a, b }) => {});
```

or

```jsx
const a = ({
  a,

  b
}) => {};
```

**Comment by sosukesuzuki** [comment]
FWIW, It look like breaking idempotency 
**Second Output:**
```js
a(({ a, b }) => {});
```

[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAFO4ACVAaAHSm2wCNsBfASmwF4A+bYagbiJDxAgAcYBLaAGdkoVACcxEAO4AFcQmEpUANwh8AJhxCkxqMAGs4MAMrc9fKAHNkMMQFc4nABYwAtgBsA6k77xBZsDhjBV8+ZV8AT2RwQWFOC0E4MRgZXUtXVGQAM1R3RM4AK0EADwAhXQMjY1RXOAAZCzhs3PyQIuLjC0t3OABFOwh4ZrzHEDMxRLForPdpLW4xCxhPDRgnZAAOAAZOBYhEz11uaIW4SeUmzgBHAfhUnkU0QQBaKDg4dQ+tMTgbvh-Uqh0pkkDkRpxEq4+DZ7KNBF0ev1Bk1QS1RjBUKQVuo1sgAEycWyoPjuLoAYQgrgy0Sg0EuIDsiQAKpjFGDEhQKEA)
