### ISSUE TITLE
Doest work for Django files

### ISSUE THREAD

**Issue by saileshkush95** [prettier/prettier#6296]
Before this is used, beautify for formatting Django file but, it doesn't work properly with jsx I decided to switch from beautify to prettier, but here is also a problem , that it doesn't work with Django file, is there any way to solve this issue for Django files.

**Comment by evilebottnawi** [comment]
Please clarify, what is not working, how you run prettier, what is content of file, what is configuration used

**Comment by saileshkush95** [comment]
I just installed prettier and try to format Django files. But it doesn't work. I didn't configure  any things.
Do I need to do any things to make this work if, please let me know

**Comment by saileshkush95** [comment]
Does prettier works for templating languages like jina

**Comment by evilebottnawi** [comment]
no, prettier doesn't support `jinja`

**Comment by mh-firouzjaah** [comment]
hi everyone, this may help, but they have to approve it first!
 "indentationRules": {
    "increaseIndentPattern": "((\\<)(body|address|blockquote|dd|div|dl|dt|tr|tbody|thead|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|a|menu|pre|table|button|a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var))|(\\{\\%)\\s*(autoescape|block|blocktrans|blocktranslate|plural|comment|debug|for|empty|if|elif|else|ifchanged|ifequal|ifnotequal|from|spaceless|with|verbatim|thumbnail)",
    "decreaseIndentPattern": "((\\<\\/)(.*)*(\\>))|((\\{\\%)\\s*(empty|elif|else|end(autoescape|block|blocktrans|blocktranslate|comment|for|if|ifchanged|ifequal|ifnotequal|spaceless|with|verbatim|thumbnail)))"
  }
