### ISSUE TITLE
Playground tooltips appear below scrollbars (and “Report issue” button causes a 414 in Playground)

### ISSUE THREAD

**Issue by dnicolson** [prettier/prettier#6297]
Edit: The 414 issue has been fixed. See the next comment for the remaining problem.

Using the “Report issue” button can result in a `414 Request-URI Too Large` response from GitHub. This was discovered attempting to report a [small issue](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzOMwAWAKgIYA2A1gMoEQDuamAvJgBRq0MA0mJADgEsA0nACePMiQwAJCAFcATmgCUzAHyZgAHSiZMCvIt0AFBRAC2AtHAB05Mu05ob5-q0IkoUOGXWadepBQGJiKviwABgQwMHxoSAD0CXQpNgDmEBBpZHD8VjaQ5gmi8jByAEZwCQBuAMwJ1iQKhAD8FGJMACTAeSKiAL4AZB5ePgCSACZdwCPeZEN8TTBMaFACfHx4XAITgxAKE3AKTBMk8IOuAB4ASnBocmQwaEwATAAMEQDcOgH6hgq6XD4AisMLKX56PQ2GAEBCsAxoPjoOB+BFI4K2ABWaGgrGU4N0kKhMLh2Ogfm0hKJRIMZQBmDJUBsAng5jQEOpnJs2AEjyOrBZcHMFI5nLFmCCISg9GYmG8dEwABEznA8d8qeKxZKsCTdCx5UqVQLWTZVutNjAbHwKmQrLCJgBBGDKdWazXazAwATmOCKgTYbBjKCyRSMFiLJRwIMwVisaUKgC0nthUFUCUwAEY3tm05gAGxvTDpguut1i2lGT3e33+wPB+RKTAAHkwkhkDbQpbLmH6BO7UNcfGNQpFGv7fzpukp4-FOyQmEF5mZExs1R2cAgky4opnei9MBy88XprWGzw0JZOW3Y93mEOaDACnWXugR5NZrPlvvj+fAmg19valTngN8hRPc1z2tcpbQ4OBHRgADAMhb0SDSOBQKXD8LWhAg5HMcooBIXlnAIAQ0gIGwwkQ3d+i7Mtex3cU6L0Xt1V7ZQcLhDh6DDDRuIYblJBjfE2M+EAuBACA+BfYJkFAJozDoYwmgQNBkBAEhqggHZxJAcoFBIMB2hgKhFjAAQoDSZAYAUOQ4Ak6JzDIAB1Uj4ERQy4CoVSWQENcYFEdSwDQNSJIs6wFBgUxUNcZBsHIawJOxS4ACEDKMvAqBIH0ABkLLgOKEvskBkqoCzsjgABFOQIHgQqyESkAIwi9TsDIehdL4J9YGcnYYWQDMJK6iBrGcgy+HUrq7iOaoCokgBHGr4FMKS1JQKQE28OC4N0gxFoEAxorSWKkHihriusSxrNsi7ypyaraoKpAbLsiSYBIcpeomfqkBeN6DN5cqAGELBOkBpW8XS5GsUhyjWs7rH6fogA) (which seems to be resolved) where the print width was hidden and defaulting to 1.

**Comment by dnicolson** [comment]
The popup labels of the buttons next to the “Report issue” are also obstructed by the scrollbar.

<img width="275" alt="Screen Shot 2019-07-13 at 18 54 38" src="https://user-images.githubusercontent.com/2276355/61174450-6d61ff00-a5a0-11e9-80d1-4b9c15bad632.png">

**Comment by lydell** [comment]
414: Maybe we can add a length check and show a message if the URL gets too long.

Tooltips: Confirmed.

**Comment by Drapegnik** [comment]
Hi! Could I take it?

**Comment by Drapegnik** [comment]
I found that Github accepts maximum urls of [8195 characters length](https://github.com/prettier/prettier/issues/new?body=111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111)

**Comment by lydell** [comment]
@Drapegnik Sure, go ahead! :+1:

**Comment by lydell** [comment]
The 414 issue has been fixed, but the tooltip issue remains.

**Comment by mrseanbaines** [comment]
I can take a look at the tooltip issue here
