### ISSUE TITLE
Pug plugin doesn't work for the .vue files

### ISSUE THREAD

**Issue by xorik** [prettier/prettier#6298]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI
- Runtime: node.js v8.15.0
- Operating System: MacOS

**Steps to reproduce:**
- clone https://github.com/xorik/prettier-pug-vue
- run `prettier --write *.vue`

**Expected behavior:**
Template inside the `pug.vue` should be prettified

**Actual behavior:**
template inside the `pug.vue` isn't touched by prettier

If you run `prettier --write *.pug`, you can see that the plugin itself works perfectly.
The plugin developers suggested to write here: (https://github.com/prettier/plugin-pug/issues/5)

**Comment by Shinigami92** [comment]
We think that it is not a problem of my plugin since the embedded pug in markdown works well.

**Comment by evilebottnawi** [comment]
Looks problem what vue printer should looks in plugins and run them for content inside (if plugin exists), i think it is feature

**Comment by xavxyz** [comment]
👋, @prettier/core team!

I may have found a hint for people wanting to use `@prettier/plugin-pug` and Vue templates (originally raised in https://github.com/prettier/plugin-pug/issues/5)

https://github.com/prettier/prettier/issues/5371 references a time where there were troubles with Vue templates written with Pug, Prettier formatting Pug templates as HTML templates. 

As far as I understand, it got fixed by ignoring `template` tags with a `lang` attribute different to `html` thanks to a `shouldPreserveElementContent` function: https://github.com/prettier/prettier/pull/5388/files#diff-0558c7e4048f9cad5b9156aecca77883R40-R47 

Should a modification be done directly to `shouldPreserveElementContent` in `prettier/language-html/utils` to check for other kind of templating engines depending on the plugin installed?

Or in `prettier/language-html/syntax-vue` ?

@Shinigami92 (maintainer of `@prettier/plugin-pug`) also suggested in https://github.com/prettier/plugin-pug/issues/5#issuecomment-536993369: 
> In my opinion I would suggest to create something like `prettier/language-pug/utils`.

I would be happy to help for this issue, but I don't know where to start (yet)! 💯

**Comment by gotexis** [comment]
@xavxyz are you still planning to work on the issue~

**Comment by xavxyz** [comment]
As soon as I have some hints on what's the recommended way to add something like this to Prettier, yes 🙂

**Comment by MentalGear** [comment]
Would be awesome, any news yet please? :)

**Comment by kissu** [comment]
> Would be awesome, any news yet please? :)

I really recommend ditching pug and use regular HTML. My team gave up but it's for the good. :+1:

**Comment by Shinigami92** [comment]
@kissu Sorry mate, but your comment doesn't help.  
If you choose not to use `pug` anymore, do not use it. But for all other users who use `pug`, this fix would be very welcome.  
I don't want to let my 2k weekly download users down.

**Comment by kissu** [comment]
@Shinigami92 I didn't want to be mean.
I'm just saying that `pug` will take a long time to be supported, if ever. My team converted it with a simple package and it's since, more readable and totally supported. It's not that big of a pain to convert and it's even better in plain HTML IMHO.

**Comment by MentalGear** [comment]
Well, I just set up vue with pug, and it makes writing code just much easier and it's great not having to constantly adding redundancies like closing tags etc. As a coder you want to keep it DRY, and what better way to reduce repetition (plus clutter) that than using pug.
And thanks for your work on prettier pug @Shinigami92 !

**Comment by fisker** [comment]
@Shinigami92 We already [improve the Vue SFC](https://github.com/prettier/prettier/pull/8153), now the `template[lang="pug"]` is correctly parsed as raw, do we need do something else to support this feature?

**Comment by Shinigami92** [comment]
Good to know!
Lastly tested with v2.0.5 and it didn't worked.
Is there another version yet?

**Comment by fisker** [comment]
It's not released yet, `yarn add prettier/prettier`.

**Comment by Shinigami92** [comment]
Sorry but seems to doesn't work for my repo:

<img src="https://user-images.githubusercontent.com/7195563/82784087-1be0fc80-9e60-11ea-9469-125bd4a09d08.png" width="500px">

When I use `yarn add prettier/prettier` I get the master branch into my `node_modules` and this is an incompatible folder structure to what e.g. `import { format, ParserOptions, RequiredOptions } from 'prettier';` is looking for

So have to wait on release

**Comment by fisker** [comment]
I tried myself, it's not working now. You can clone `prettier/prettier` and install `@prettier/plugin-pug` to play with it.

**Comment by Shinigami92** [comment]
Will come back to this in around 8h, have to work now

**Comment by Shinigami92** [comment]
Tried some things, but no luck for now
I think I will wait on released prettier version
May you publish a beta or rc version?
Then I could test with this

**Comment by fisker** [comment]
```bash
git clone https://github.com/prettier/prettier.git
cd prettier
yarn add @prettier/plugin-pug
code 1.vue
node bin/prettier 1.vue
```

**Comment by Shinigami92** [comment]
Test with markdown:

![image](https://user-images.githubusercontent.com/7195563/82830294-9b4ceb00-9eb5-11ea-8dda-887d408127f7.png)

The first embedded block was formatted

---

Test with vue:

![image](https://user-images.githubusercontent.com/7195563/82830325-b0297e80-9eb5-11ea-8b33-cca2964d9499.png)

---

No logging, no notification, no anything 😔

**Comment by fisker** [comment]
> I tried myself, it's not working now.

> I think the problem is on prettier side. Need investigate

**Comment by fisker** [comment]
I'm debugging

```console
$ cat 1.vue
<template lang="pug">
p= "This code is"+ ' <escaped>!'
</template>

$ node bin/prettier 1.vue
<template lang="pug">
  p= 'This code is' + ' <escaped>!'

</template>
```

I made it work, but very dirty way.

**Comment by Shinigami92** [comment]
Tell me you dirty secret 😏 (do you have a PR? pls link it)

The last empty line, could be something I can fix on my plugin side.

**Comment by fisker** [comment]
I'm trying to clean it up, but seem not easy.

**Comment by fisker** [comment]
@Shinigami92 check #8465

**Comment by Shinigami92** [comment]
> @Shinigami92 check #8465

I will do, but please give me some time
I'm pretty tired today
