### ISSUE TITLE
Typescript Union Types Formatting Issue

### ISSUE THREAD

**Issue by Domvel** [prettier/prettier#6299]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPAFQE8M4AhcgZ2uAB0o9CATJHlYxsRAOYBubryjkAtnEHDRUSdwC+3buiy5CxMpWr1GAeSjV08KH1a0GzNh2l5ygqAFc5AIxJSomlDamDj4RPCGVPaMNADuEHhWCLbRjux4XDx43u5evtj+gcG6YQYUUSZwNAAW2HCWaNYplSzpmbxguT5+GloWIXrhJOXGDgBiEB7YiY3Jdi1OGS4CeJ7dBb1B-SX6ESOpYwQAbg1N8w6tzlmKq3k9AX06obvDRqkAygRoM2epl0tZUhdfKFR4DfAwBx4ACCABtYZU7ABePAuSrmagAH1RWUqcQSmLRDhqdSxON4lQmUzw2KJjEOJxp5I+X38IAANCAIBgYARoKxkKByNhsBBYgAFYUIAUochHCAEPgckDebCUADWcBg7wwlHEyBEHjgnOqMDksIA6tUCPBWLqqO9pTbjja6MhwKwBZyiOxcOK1WI5ORkBRYexOQArVhoJhqsCa7XyOAAGSIcBD5DDxpAUbQn1UsLgAEUPBB4Bms5zddhfe7vORvHRYdBlRgVDALYqYNVkAAOAAMVdF7Ataow7rbcF9J2VAEdS-B-dyZSA2ABaCxwPhb5V1ecEOr+8iB4NIUPhkDsOQEA3YI2c1jiQslsvps+Zi8wBudvjd5AAJk5ERyAIWFxAAYQgOQg3dKBoHTTkPHYGgGxlc84HUdQgA)

**Input:**
```ts
export type AllTypes = 
  TypeOne | 
  TypeTwo |
  TypeThree | 
  TypeFour | 
  TypeFive | 
  TypeSix;
```

**Output:**
```ts
export type AllTypes =
  | TypeOne
  | TypeTwo
  | TypeThree
  | TypeFour
  | TypeFive
  | TypeSix;
```

**Expected behavior:**
The Prettier's output is weird. Because the first element of code is `undefined`. But when I hover my mouse over the variable it shows: `type AllTypes = TypeOne | TypeTwo | TypeThree | TypeFour | TypeFive | TypeSix` (correct). 

When I take the output of prettier and remove all linebreaks, you will get this:

```ts
export type AllTypes = | TypeOne | TypeTwo | TypeThree | TypeFour | TypeFive | TypeSix;
```

No TypeScript or Linter errors. I just wondering, is this allowed? Can I use pipes before OR after?
I expected the same as my input. 

```ts
export type AllTypes = TypeOne | TypeTwo | TypeThree | TypeFour | TypeFive | TypeSix;
```

Maybe this is a tolerated format of TypeScript. Because it ignores the empty expression before the first pipe. - I'm confused. Maybe this is a unwanted behavior?

Maybe it should be: 

```ts
export type AllTypes =
  TypeOne
  | TypeTwo
  | TypeThree
  | TypeFour
  | TypeFive
  | TypeSix;
```
I think the current output of prettier looks "prettier". But it's maybe not correct. I though the first element is undefined. Like declaring an array `[, 1, 2, 3, 4, 5]`. The first is empty / undefined. 
Do you know what I mean?

**Comment by hawkrives** [comment]
This is valid Typescript syntax (and Flow, fwiw). Both | (union) and & (difference) operators are allowed at the front and end of the line, and the location makes no difference to the generated type.

**Comment by Shinigami92** [comment]
If you want `undefined`, use 
```ts
export type AllTypes = undefined | TypeOne | TypeTwo | TypeThree | TypeFour | TypeFive | TypeSix;

// or better
export type AllTypes = TypeOne | TypeTwo | TypeThree | TypeFour | TypeFive | TypeSix | undefined;

// or even better
export type AllTypes = TypeOne | TypeTwo | TypeThree | TypeFour | TypeFive | TypeSix;
const type: AllTypes | undefined;
```

I think this is working as intended -> can be closed

**Comment by brainkim** [comment]
This is a feature of the typescript grammar.

Related typescript issue: https://github.com/Microsoft/TypeScript/issues/12071

**Comment by Domvel** [comment]
Ok, thanks for the informations. Leading pipes are ignored for formatting reasons. But maybe this should be an option.
