### ISSUE TITLE
union type array breaks after opening parenthesis, but not before closing

### ISSUE THREAD

**Issue by jeysal** [prettier/prettier#6303]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDATrzAXkwG1sAjMAGkwBM4AzGgcwAsBLGgKwGsAbGgFsoEGgAcAjrhoYArjQBuAdwAeNAJ4AvALo40mABQZc7KM0wAfTLKj0GpuLQCUJbQG4QVEBDEx26ZFA8XAglAAU8BDRkEGwFCHZaTxByXGwwHjgYAGUxdNNmZBhcWTgvVhhBPgB1Dng0PLA4bKj2PwU29RiwNGivUzQ4XBgwtOZBbGQGbD5Bry40FQAhNIys7OxBOAAZBymZuZAFlWyCvjgARVkIeH3ZspA83EHcGJh1MTg0MBNfZLETLBqokYKxkAAOAAMXgBEEG1TSYhiAK+QwUcGSEmu8FGPmiKGwaAAtFA4I5HMlcHAsewqaNsONJkhpvcvINBOwiiUHmgzpdsRjmQcHjAKMDaKDkAAmLzFbDsPgFADCEEEExiIlJyVkgwAKhR8SzBgBfY1AA)
```sh
--parser typescript
```

**Input:**
```tsx
const arr = [abc, def, ghi, jkl, mno, pqr, stu, vwx, yz] as (string | undefined)[];
```

**Output:**
```tsx
const arr = [abc, def, ghi, jkl, mno, pqr, stu, vwx, yz] as (
  | string
  | undefined)[];

```

**Expected behavior:**
Up for debate, maybe simply
```tsx
const arr = [abc, def, ghi, jkl, mno, pqr, stu, vwx, yz] as (
  | string
  | undefined
)[];

```
Also not sure if it's the best place to break first.

*somewhat* similar to https://github.com/prettier/prettier/issues/3403

**Comment by sosukesuzuki** [comment]
FWIW
- this happens with not only array type, for example happens too with `keyof`.
- this happens with not only `as`, for example happens too with the type for normal variables.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCEmYDWcAnhNpgBQYBOAllAOaYA+mArlACZzYNxcAlJgC8mANoBdANwgANCAgAHGHXTJQAQxo0IAdwAK2hGmQhNANwh0u8kACMamsMRgBlJc4aNkMGuzgFAAsYAFsAGwB1ILp4NE8wODcTWLoLWJIzMDRTBQY0OBoYAydGUM1kbE1wgoUAKzQADwAhJxc4d01QuAAZfkrq2pAGxrdvcLgARXYIeAGawJBPGgKaMxgSJTg0MHoVOyVdAsinJTND7cKLODsARxn4EuVTFE00AFooOAEBOxo4e50f4lTRlCpIKoLBQFUJ0Xz+RZocZTB43CGDRYwTT2SI2GBBZAAJgUfk0dHC3gAwhBQuUzFBoDcFOwCgAVbEvSFDQ4MGC4rj45AARgADABfMVAA)
