### ISSUE TITLE
Yet another template literal issue

### ISSUE THREAD

**Issue by shamilovtim** [prettier/prettier#6318]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAeAIhMMIBOAggG4CGMZBAOlOvQ6gM4QCuBYcAvMMLYwNTsAlklQAHAhHFMAdABNc+YuUoEAqgCUAkv0ECA-KgAGACxgwZSAPTWAtnEoBacacKzId62XHDrkiBJheTgCAH0AgDNhABs4MOE7MgBzOCZrABJgAJkFJUJtLABfa0UAdygYiDJ5TOypXMU8QlIKKi1tIuM9fQYxIiYmR1lIqTsAWQh5VjiACgI4AEdWYQXZgHJZWW9Bx3TElLTrODtxGABPJzJVKllxKGT1gEon2REewSKij4ZrAD4QAAaEDSGDCaBMZCgKhSMoABSoCEhKGuEGCQJAACMCGQwABrRwAZXEuOED2QMAIrDgwPMdhiAHVTMJ4EwSZxCUiWcIghdkOBBhiyUMCDA4TjkklkJEyDEhsCAFZMAAeACEcfiiWQHAAZMlwaWy+UgJXKwlk5JxACKrAg8ENcppIBJBBF-MxZEx5yqUAxASGDJx4n5kjSoRIBuByztcHF0mRIDITCcUDgcBC8gxC2Wq1jEqlSBljuBQzswgpVKdTAt1tt9sLRqdlExDOCMFMyAATMDKWRYhaAMIQOwFkBQaCRkCsIYAFU9yKLxskZJgrfk7eQAEYAAzbr5AA)
```sh
--parser babylon
--print-width 100
```

**Input:**
```jsx
  <DoctorAvatar
          source={{
            uri: props.doctorAvatarURI
              ? `https://asdf-asdf.com/api/abcabcab_profile_images/${props.abcdefID}/download/${props.abcdefAvatarURI}`
              : Asset.fromModule(require('../assets/images/empty-avatar.png')).uri
          }}
        />
```

**Output:**
```jsx
<DoctorAvatar
  source={{
    uri: props.doctorAvatarURI
      ? `https://asdf-asdf.com/api/abcabcab_profile_images/${props.abcdefID}/download/${
        props.abcdefAvatarURI
      }`
      : Asset.fromModule(require("../assets/images/empty-avatar.png")).uri
  }}
/>;

```

Using the VSC plugin. When the template literal starts before the print width limit, and ends during or after the print width limit, the template literal is treated like the curly brackets are just some indentable code. This is not correct and does not follow the spirit of a template literal.

**Expected behavior:**
Expected the string literal to stay intact, not have its curly brackets treated as indentable, line-broken code. When there's a template literal, continue as far past the print width as necessary and do not wrap and indent.

![https://i.imgur.com/eh35lPw.gif](https://i.imgur.com/eh35lPw.gif)

Now watch me fix it by adjusting print width to 120:
![https://i.imgur.com/Gigjj3F.gif](https://i.imgur.com/Gigjj3F.gif)

**Comment by lydell** [comment]
Hi!

> This is not correct

I'm not sure I'm following here – why is it not correct?

**Comment by shamilovtim** [comment]
because this: 

```
let abc = 1;
console.log('my number is ${abc}');
```

is many times cleaner than this:

```
let abc = 1;
console.log('my number is ${
  abc
}');

```

1.  in the spirit of what a template literal is, it's usually just an inline variable inside of a string. there's no reason to split it like this. it doesn't make the code more readable, it doesn't really do much of anything other than obfuscate for no good reason.

2. prettier knows before the print width limit is hit that template literals should not be split and indented. so it's surprising that once prettier hits the print width limit it suddenly changes syntax flavor. that's not consistent and doesn't logically make sense. either the syntax flavor is undesirable or it's not and the print width shouldn't affect it.

3. I can't find any evidence that template literals were ever intended to be treated like this syntactically and that anyone/or anything treats them like this beside Prettier after it hits the print width limit.

**Comment by thorn0** [comment]
@shamilovtim The playground link you provided doesn't produce the output you provided. Prettier already does what you want. You must be using an old version.

**Comment by shamilovtim** [comment]
Thank you @thorn0. Could it be that https://github.com/prettier/prettier-vscode is on an extremely old version of Prettier?

**Comment by shamilovtim** [comment]
Hi guys, I visited the vscode extension repo and indeed their version is old. Sorry for wasting your time.

**Comment by thorn0** [comment]
If you install a newer version locally in your project, the extension will use it.
