### ISSUE TITLE
there is should not provide this comma

### ISSUE THREAD

**Issue by zhangenming** [prettier/prettier#6322]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQAdMQC2AlgM5zYC82ACgSeQHSZykQA2qcAFAJQDcAHSj4iZOIxgALBNwCOVAHzY5AGmwB3Ldp269upZv3GTGgcNEMJ02cOwrDau0dOudht562rh5qCFUQCFwYYmhSZFAsAg0aLAQIlHRUCGIAEwCQACNMdDAAazgYAGVcPOIoAHNkGEwAVzhAqRhCdgB1KWJ4UjKwOGKEruJULoBPZHBSCMCK8kwYOnRKwnRkADN0dnJAgCtSAA8AIVyCouL0QjgAGQq4dc3tkD394orK9jgARTqIeHutxogMqYOYTLLoLKjdjQTL4CowNrpaTIAAcAAZAqJyG1crgJvhWHBMFxMnIfvA6MFEiB0KQALRQOBwNLMzIsMnEFiLZarJAbAGBcgkGr1QGkN4fb6-O58h6AmAQxFpZFIABMgVq6GI7DeAGEiCsJpt2Jk6uQACoQxL88gAX1tQA)
```sh
--parser babylon
--trailing-comma all
```

**Input:**
```jsx
var promise = Promise.resolve();
promise.then(
  q => q,
  wwwwwwwwwwwwwwwwwwwwwwwwwww => wwwwwwwwwwwwwwwwwwwwwwwwwww,
);

```

**Output:**
```jsx
var promise = Promise.resolve();
promise.then(
  q => q,
  wwwwwwwwwwwwwwwwwwwwwwwwwww => wwwwwwwwwwwwwwwwwwwwwwwwwww,
);

```

**Expected behavior:**
```jsx
var promise = Promise.resolve();
promise.then(
  q => q,
  wwwwwwwwwwwwwwwwwwwwwwwwwww => wwwwwwwwwwwwwwwwwwwwwwwwwww// because promise.then are at most two parameters,  now, it's already have 2, so there is should not provide this comma
);

```

**Comment by evilebottnawi** [comment]
No, we add trialing commas for all method, it is good practice, also we can't detect all Promises because you can do like this
```js
const something = Promise.resolve();

something.then( 
  q => q,
  wwwwwwwwwwwwwwwwwwwwwwwwwww => wwwwwwwwwwwwwwwwwwwwwwwwwww,
)
``` 

We can't known this is promise or just api with `then` method. This logic for any methods.
