### ISSUE TITLE
[markdown] no space in heading

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#6324]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiVACAKgSxgGzg3QB0oz1cCj0QAaECABxh2gGdlQBDAJ14gB3AAp8EnFNwBuEHABN6IAEa9uYANZwYAZSZqcUAObIYvAK5wGACxgBbfAHUreOOz1g428XhxS8AT2Rwdk4GA3Y4XhhhVUNbbmQAM258CIYAK3YADwAhVQ0tbW5bOAAZAzgklLSQTKztA0NCAEUzCHgq1MsQPV4I3iD43nU5IShFJl4DGAd5GCtkAA4ABgZJiAiHVSYgyddIqUqGAEc2+BjmCRBudgBaKDg4OSfFXjhTnDeY7jiEpGSugwIrYcCZzN12I0WmdKv9qt0YNwlLM5PNkAAmBimbg4fCNADCEFs8SCUGgRxAZgiWCREgBEQAvgygA)

**Input:**
```md
## Title ##

##Title ##
```

**Output:**
```md
## Title

##Title ##
```

**Expected behavior:**

```md
## Title

## Title
```

/cc @ikatyang something wrong with parse or we doesn't handle this case?

**Comment by kachkaev** [comment]
This looks like an expected behaviour.

GitHub Flavored Markdown Spec: https://github.github.com/gfm/#atx-headings (see example 34)
> ### ATX headings  
> ...  
> At least one space is required between the # characters and the heading’s contents, unless the heading is empty.

Same for CommonMark: https://spec.commonmark.org/0.29/#atx-headings (see example 34 too)

**Comment by evilebottnawi** [comment]
@kachkaev thanks for link, i found this lines in our legacy project :smile: 

Fast github test:

## test-with-spaces ##

## test-without-right-space##

##test-without-left-space ##

##test-without-spaces##

Expected, false alarm :smile:
