### ISSUE TITLE
Incorrectly parsing vue custom block as HTML

### ISSUE THREAD

**Issue by kirschre** [prettier/prettier#6325]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJhMBnAfAHSgBUALAS2wAJIBbAB2gRkpgEMBrOK1qSgAzLwa2PpToAnCHUoAKPgEFx41gE9UAeQBGAKzhgYuPgEoAdIUqUI4wqQrUI9RrEqa4YgDaswcdJTJRsMnQ3Vn5UGhUAWloGKCZDMyhUAHpMHAIoQlRsMHEyOgNzSmTkyjgYMCzknLyC3BAAGhApGDJobGRQViUIAHcABW6EDpRWADcIIMaQTWUwThgAZTovfwBzZBhxAFc4JpIYGncAdXJ4bBXvReHBMjHBFWRwbA6m-2w4cRh+5TWaVmQADNWO4Pk1tNgAB4AITmC0WrBocAAMv44ECQWCQBDIYt1u44ABFbYQeAY0F7EArcQfcRPMa7aYSfwwY5BGAkZAADgADE0JBAPsdlHQnhIuJ8xuimgBHEnwH5SEYgVjYSJxHw+abiOBysg6n6sP4ApDAilND40MibHaUwJQNYE4mk9GmzGUtiaNnoDnIABMTS2rDI7nWAGEHP8nlBGNNth8iKxNCMzR8AL5poA)
```sh
--parser vue
```

**Input:**
```vue
<docs>
This component takes an `items` prop (`Array<Object>`).
  or
This component should be placed inside a `<my-component>`.
</docs>

<script>
  // etc
</script>
```

**Output:**
```vue
SyntaxError: Unexpected closing tag "docs". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:1)
  3 |   or
  4 | This component should be placed inside a `<my-component>`.
> 5 | </docs>
    | ^
  6 | 
  7 | <script>
  8 |   // etc
```

**Expected behavior:**

My team has written a custom vue SFC webpack plugin that generates documentation via a `<docs>` tag. This tag contains markdown comments. Prettier tries to parse this block as HTML, which fails due to unclosed "element tags". Some examples of the syntax that cause problems are shown above. Prettier should not be running an HTML parser over these custom blocks, as there are no guarantees what type of content they will contain.

I'd expect that prettier would just ignore custom blocks it doesn't understand. Per #5448 prettier won't _format_ custom blocks. But if we're not gonna format them, why parse them at all?

**Comment by meteorlxy** [comment]
[eslint-plugin-prettier-vue](https://github.com/meteorlxy/eslint-plugin-prettier-vue) could a possible solution :wink:

![eslint-plugin-prettier-vue](https://user-images.githubusercontent.com/18205362/62407420-f80bac00-b5ea-11e9-8cd9-77e2e55cb16c.gif)

**Comment by kirschre** [comment]
Hi @meteorlxy - thanks for the suggestion, I'll take a look at that plugin. Does it support ignoring custom blocks entirely? I'm not sure we'd want to even use markdown formatting, as we have custom docs syntax.

That's kind of my point with this issue though. We're using a custom block built to work for our needs. Given that we can't know what custom blocks are being used for, and there aren't really conventions for them, I think tooling should ignore them by default. Opting into additional formatting via a plugin/config seems like a better solution.

**Comment by meteorlxy** [comment]
@kirschre Since v1.1.0, That plugin will ignore custom blocks by default if you don't specify the language of the custom block in the settings.

Thanks for your advice~
