### ISSUE TITLE
Syntax Error for Flow type parameter defaults in function declarations

### ISSUE THREAD

**Issue by taylorgoolsby** [prettier/prettier#6326]
Recently flowtype released https://github.com/facebook/flow/releases/tag/v0.103.0

This includes https://github.com/facebook/flow/commit/c18ee0d8ee7999ef65ee21d0113b7351c5dc1e15
which is a fix for https://github.com/facebook/flow/issues/6875.

This new syntax is not supported by prettier.

**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI
- Runtime: Node.js v10.15.0
- Operating System: macOS

**Steps to reproduce:**
```
function foo<T: any = number>(): any {}
```

**Expected behavior:**
```
src/foo.js 20ms
```

**Actual behavior:**
```
src/foo.js
[error] src/foo.js: SyntaxError: Unexpected token
[error] > 1 | function foo<T: any = number>(
[error]     |                     ^
```

**Comment by EnoahNetzach** [comment]
as a workaround, using the [comment types](https://flow.org/en/docs/types/comments/) works.

```
function foo<T: any /*:: = number*/>(): any {}
```

**Comment by EnoahNetzach** [comment]
as a note, this issue seems to have been solved

**Comment by thorn0** [comment]
Works with `--parser flow` too. We need tests for this.
