### ISSUE TITLE
error Delete `·` prettier/prettier in a fresh Nuxt.js app with Prettier and Eslint

### ISSUE THREAD

**Issue by jedrekdomanski** [prettier/prettier#6329]
Fresh Nuxt.js application with Eslint and Prettier.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9jyowYBLaPACmDwBJS1mBnADR5scAoxEM8AXwCUeYAB0oeLj34A6aACU4AR3Jw+MVq0hRijAOZyAvAD55spVKUgBICBibQ+yUKWxsCAB3AAUAhF8UUgA3CEYCNxAAI2xSMABrOBgAZQx0xihLZBhsA3cACxgAW0oAdQrGeD58sDgcyKbGGKaAT2RwPl93Qr44XFC0y2rSZDJKMfcAKz40ACE0zOyc0mq4ABlCuDnSBbhl1ZzCy0o4AEVyCHgTs-d87DHsAeTSZLhKJIYbCFGB1BIwCrIAAcAAY3kExnU0hgBkDDOMYsd3PonnBJp4oiBSHwALRQOCiURJET6cR4qYzF6LEBjaqMEplc4s663B64plcmC-MEECHIABM7lKpEYlGuAGEINVGSgoNAsSByGMACq-KLzMZSKRAA)
```sh
# Options (if any):
{
  "semi": false,
  "singleQuote": true
}
```

**Input:**
```jsx
export default function ({ $axios, redirect }) {
  $axios.onRequest(config => {})
}
```
![image](https://user-images.githubusercontent.com/5911945/61787267-bd965800-ae0f-11e9-894f-7c7855025351.png)

**Expected behavior:**
No error.

**Comment by evilebottnawi** [comment]
@jedrekdomanski do you see problem on playground? We don't output this error, also you use https://github.com/prettier/eslint-plugin-prettier

**Comment by jedrekdomanski** [comment]
No, I don't @evilebottnawi but I get this error on my page and can't continue development...unless I remove this package...

**Comment by evilebottnawi** [comment]
@jedrekdomanski do you look on error? You use `eslint-loader` with https://github.com/prettier/eslint-plugin-prettier, provide no additional information what is wrong, and ask to solve this :confused: How we should solve this?

**Comment by jedrekdomanski** [comment]
I don't know. I am quite new to this. It says `prettier/prettier` so I
raised it here.

śr., 24 lip 2019 o 12:48 Evilebot Tnawi <notifications@github.com>
napisał(a):

**Comment by evilebottnawi** [comment]
@jedrekdomanski sorry, but we can't solve this issue

**Comment by lightstream** [comment]
Google brought me to this page, so I'm commenting for future newbie prettiers confounded by this error. The thing to realise is that prettier uses the '·' character to denote a space - in this case it's unhappy about the space between `function` and the opening bracket.
