### ISSUE TITLE
inconsistent output between `html`(htmlWhitespaceSensitivity: "ignore") and `jsx`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#6336]
**Prettier 1.18.2**
[Babel Parser Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAEnANliA+AHSgAJj4BnGU61AdQgCcsATa6gejze4piNXaYc+EABoQEAA4wAltHLJQAQwYMIAdwAKKhApRKAbhBnMxIAEYMlYANZwYAZUnWZUAObIYDAK5xxACxgAWyxafxkKZzA4B10ImQMIgE9kEBk3KEY4M1dyOAYYTSs3IKVkADMlLDzxACtyAA8AIStbewclILgAGVdspErqvxB6hodXNyw4AEVvCHgKqpqQZwY8hlTzJXNsM0kGVxhaExh-ZAAOAAZxfYg82itJVP24dYNs8QBHOfgiqT0QEpyABaKBwODMCFmBhwb4yGFFJQlMoDJbDPJBGSeHzoiZTWbzfqDZYwbbHZinZAAJnEXiUMiwEwAwhAgqVUpkwWZvHkACrbPTEuAAX2FQA)

[HTML Parser Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAEnANliA+AHSgAJj4BnGU61AdQgCcsATa6gejze4piNXaYc+EABoQEAA4wAltHLJQAQwYMIAdwAKKhApRKAbhBnMxIAEYMlYANZwYAZUnWZUAObIYDAK5xxACxgAWyxafxkKZzA4B10ImQMIgE9kEBk3KEY4M1dyOAYYTSs3IKVkADMlLDzxACtyAA8AIStbewclILgAGVdspErqvxB6hodXNyw4AEVvCHgKqpqQZwY8hlTAkLNJBlcYWhMYf2QADgAGcV2IPNorSVTduHWDbPEARzn4Iqk9ECVyABaKBwODMMFmBhwT4yKFFJQlMoDJbDPJBGSeHyoiZTWbzfqDZYwJTmQ7MY7IABM4i8ShkWAmAGEIEFSqlMiCzN48gAVEl6QlwAC+QqAA)

```sh
# Options (if any):
--html-whitespace-sensitivity ignore
```

**Input:**
```html
<Hello>
  test     <World      />         test
</Hello>
```

**Output:**
```jsx
// babel
<Hello>
  test <World /> test
</Hello>;

// html
<Hello>
  test
  <World />
  test
</Hello>
```

**Expected behavior:**
Should output same content(ignore the last `semi`).

**Comment by evilebottnawi** [comment]
I think because jsx and html is not same even with `htmlWhitespaceSensitivity` option

**Comment by thorn0** [comment]
`--html-whitespace-sensitivity` doesn't and shouldn't affect JSX.
