### ISSUE TITLE
[Angular] Putting space in mustaches in a class attribute does different behavior

### ISSUE THREAD

**Issue by origin-master** [prettier/prettier#6337]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiMMAGYQQBGRATgL7vUB8qA9FmzcQAGhAQADjEzQSyUG1YQA7gAU2COSiLYImdKJBNWRMAGs4MAMoTTmKAHNkMVgFc4YgBYwAtgQDqnpjwJLZgcFaawTjBAJ7I4GSG9iRwrDCqJg4+RMh0RASpYgBWJAAeAEIm5pZWRD5wADL2cHkFRSClZVb2DgRwAIquEPBthR4gtqyprAlEjq7Es2ISrPYw-vownsgAHAAMK0qp-iYSCatwM9itYgCOw-CZklogpAC0UHBw6D+GrHAHpgAZkiNlckh8uMxKkfJhnG4JiRev0hiNWpD2hMYEQmJt0NtkAAmMQuIiYAi9ADCEB8OQSUGgtxArlSABVcVooalOEA)
```sh
--parser angular
```

**Input:**
```html
<div class="{{foobar}}"></div>
```

**Output:**
```html
<div class="{{ foobar }}"></div>

```

**Expected behavior:**
```html
<div class="{{foobar}}"></div>
```

Angular parses `{{` as a class name if it's spaced. I'm not sure whether it's Angular's compiler bug or Prettier's bug, but it does different behavior in comparison with unformatted code, I write the issue here.

**Comment by thorn0** [comment]
> Angular parses {{ as a class name if it's spaced.

Could you possibly create a project on StackBlitz or CodeSandbox to demonstrate this alleged behavior of Angular? I can't reproduce it. See https://stackblitz.com/edit/angular-gvxv2e

**Comment by origin-master** [comment]
Sorry, I found that HTML minifier attached in my project sorts class names before Angular reads it, that caused the issue.
