### ISSUE TITLE
[Feature] Move types to this repo

### ISSUE THREAD

**Issue by gengjiawen** [prettier/prettier#6346]
This will make it more easy to change and integrate.

Currently it's located in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prettier/index.d.ts.

**Comment by thorn0** [comment]
See http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

> There are two main ways you can publish your declaration files to npm:
> 1. bundling with your npm package, or
> 2. publishing to the `@types` organization on npm.
>
> If your package is written in TypeScript then the first approach is favored. [...]
> **If your package is not written in TypeScript then the second is the preferred approach.**

**Comment by evilebottnawi** [comment]
agree with @thorn0 , i think we can close this issue

**Comment by gengjiawen** [comment]
Unlike axios, mostly we use it in script.
