### ISSUE TITLE
Emoji in contents of file strips blank lines

### ISSUE THREAD

**Issue by bitcrumb** [prettier/prettier#6349]
It seems that having an emoji in the content of your file strips out any blank line that appears on the file after it.

This seems to be a regression, since this was previously reported to be fixed in this issue: https://github.com/prettier/prettier/issues/1427

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20a%20%3D%201%3B%5Cn%5Cnconst%20b%20%3D%20'two'%3B%5Cn%5Cnconst%20c%20%3D%20'%F0%9F%92%A9'%3B%5Cn%5Cnconst%20d%20%3D%20%5B%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)
```sh
--no-bracket-spacing
--parser flow
--single-quote
```

**Input:**
```jsx
const a = 1;

const b = 'two';

const c = '💩';

const d = [];
```

**Output:**
```jsx
const a = 1;

const b = 'two';

const c = '💩';
const d = [];

```

**Expected behavior:**

```jsx
const a = 1;

const b = 'two';

const c = '💩';

const d = [];
```

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by evilebottnawi** [comment]
Bug only for `flow`, problem in parser https://github.com/facebook/flow/issues/4219

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/issues/2091, sorry for delay

**Comment by bitcrumb** [comment]
Ah weird, sorry for the duplicate. I "re"opened this issue since in #1427 I noticed a referenced commit that claim it should resolve all unicode issues (by upgrading the flow parser).

See: https://github.com/prettier/prettier/commit/3161bd0787cd7ae0e96c8cdc0c1ae509a9b3aabb

But apparently this is not the case then. Sorry about that :)

**Comment by evilebottnawi** [comment]
@bitcrumb i will try to update flow parser, bug bug still exists in parser :disappointed:
