### ISSUE TITLE
special yaml rules

### ISSUE THREAD

**Issue by nickguo** [prettier/prettier#6350]
Hello!

My project uses yaml files for declaratively making templates.  I've written custom code that ingests yaml files to support nice-to-haves like imports and if-statements.

I'd still like to use prettier for my formatting project, but the existing rules are too restrictive and I have too many files to add # prettier-ignore to. (e.g. I get a bunch of `SyntaxError: Aliased anchor not found`. I realize this relates more to https://github.com/eemeli/yaml)

Any ideas on how to proceed? Is there any way I could still use prettier?  Perhaps I need a more traditional linter because I can't see a way of building the AST given my custom keywords.

Thank you

**Comment by evilebottnawi** [comment]
@nickguo can you provide examples, maybe you can create plugin for this purpose

**Comment by nickguo** [comment]
Example:

```
imports:
  - defaults.yml

key:
  - *YML_FROM_DEFAULTS
```

**Comment by nickguo** [comment]
Will need to build something inhouse. Thanks for your time!
