### ISSUE TITLE
Docs: Prettier plugins for JS

### ISSUE THREAD

**Issue by tocttou** [prettier/prettier#6351]
Hello!

I want to make a plugin for prettier that can sort the keys in destructuring assigment in JS/TS, but the official docs for plugins only list cases for implementing plugins for new languages. I went through the repo but it seems that `printer-estree.js` cannot be extended via plugins currently.

Can we have an example for such a case in the repo?

I will be very happy to add an example if someone can point me in the right direction.

**Comment by thorn0** [comment]
In your case, you can use the [custom parser API](https://prettier.io/docs/en/api.html#custom-parser-api).

**Comment by tocttou** [comment]
I tried the custom parser API but for some reason the changes to AST are not applied.

Input:

```
var { b, d, c } = {
    b: 1,
    d: 2,
    c: 3
};
```

Expected output:

```
var { b, c, d } = {
    b: 1,
    d: 2,
    c: 3
};
```

Parser:

```
var walk = require("estree-walker").walk;

module.exports = function(text, parser) {
  var ast = parser.babel(text);
  walk(ast, {
    enter: function(node) {
      if (
        node.type === "VariableDeclarator" &&
        node.id.type === "ObjectPattern"
      ) {
        var properties = node.id.properties;
        node.id.properties = properties.sort(function(a, b) {
          return a.key.name.localeCompare(b.key.name);
        });
      }
    }
  });
  return ast;
};
```

Run as:

```
node_modules/.bin/prettier --parser parser.js input.js
```

I tried the same code snippet in the `preprocess` stage for babel parser and that seems to work (given below) but it doesn't seem to be the right approach.

```
module.exports = {
  parsers: {
    babel: Object.assign({}, parser, {
      preprocess: function(text) {
        var ast = acorn.parse(text, { ecmaVersion: 6 });
        // process
        return toText(ast);
      }
    })
  }
};
```

**Comment by thorn0** [comment]
Deleting the location data helps:
```js
var walk = require("estree-walker").walk;

module.exports = function(text, parser) {
  var ast = parser.babel(text);
  walk(ast, {
    enter: function(node) {
      if (
        node.type === "VariableDeclarator" &&
        node.id.type === "ObjectPattern"
      ) {
        node.id.properties.sort(function(a, b) {
          return a.key.name.localeCompare(b.key.name);
        });
        for (const prop of node.id.properties) {
          delete prop.start;
          delete prop.end;
        }
      }
    }
  });
  return ast;
};
```

**Comment by tocttou** [comment]
That works! Thanks.

Here is the parser: https://github.com/tocttou/prettier-sort-destructure

Is it possible to load it through `.prettierrc` overrides? Currently this has to be pased in the CLI with `--parser`.

**Comment by thorn0** [comment]
It should be possible. See https://prettier.io/docs/en/configuration.html#setting-the-parser-docs-en-optionshtml-parser-option

**Comment by tocttou** [comment]
The schema says that it has to be one of: 

```
["flow", "babel", "babel-flow", "typescript", "css", "less", "scss", "json", "json5", "json-stringify", "graphql", "markdown", "mdx", "vue", "yaml", "html", "angular", "lwc"]
```

I tried setting it as (after installing the parser from npm), but that doesn't seem to work:

```
  "overrides": [
    {
      "files": "*.js",
      "options": {
        "parser": "prettier-sort-destructure"
      }
    }
  ]
```

**Comment by thorn0** [comment]
[It expects a local path.](https://github.com/prettier/prettier/blob/master/src/main/parser.js#L54)

**Comment by tocttou** [comment]
That helps! Thanks.
