### ISSUE TITLE
Solve JSX bracket same line

### ISSUE THREAD

**Issue by Faraz1995** [prettier/prettier#6355]
# Options (if any): JSX bracket Same line
![1](https://user-images.githubusercontent.com/53772471/62466960-e0c5ed80-b7a7-11e9-9320-fb5f07833ce3.JPG)

**Input:**
![2](https://user-images.githubusercontent.com/53772471/62466962-e15e8400-b7a7-11e9-94de-2ec81a3e3602.JPG)

**Output:**
![2](https://user-images.githubusercontent.com/53772471/62466962-e15e8400-b7a7-11e9-94de-2ec81a3e3602.JPG)

**Expected behavior:**
<input
        type='checkbox'
        checked={props.item.completed}
        onChange={() => props.change(props.item.id)} />

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue was closed

**Comment by Faraz1995** [comment]
> Please use issue template otherwise issue was closed

how should i do it?

**Comment by evilebottnawi** [comment]
https://github.com/prettier/prettier/blob/master/.github/ISSUE_TEMPLATE/formatting.md

**Comment by Faraz1995** [comment]
> Please use issue template otherwise issue was closed

is that ok now?
could you please answer me now?

**Comment by evilebottnawi** [comment]
Still can't understand what you want

**Comment by Faraz1995** [comment]
> Still can't understand what you want

look at the last line in my output, i want that closing tag be on the prev. line

**Comment by evilebottnawi** [comment]
@Faraz1995 prettier doesn't support this output and we are not going to change it at the moment, sorry

**Comment by Faraz1995** [comment]
> @Faraz1995 prettier doesn't support this output and we are not going to change it at the moment, sorry

ok thanks for your help :(
