### ISSUE TITLE
arguments with newline in arrow function

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#6374]
Still happens if the pattern is nested:
**Prettier pr-6301**
[Playground link](https://deploy-preview-6301--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEB6VACAklADgVxgB0oAzCCAChIw0uAEMlgbaMGAaE12gI1YC+AgJQYAvAD4MwASWEBuEiA4gIuGAEtoAZ2SgGAJwMQA7gAVDCXSgYA3CBoAmykLwMMwAazgwAyrg8NKABzZBgDfDgVAAsYAFsAGwB1aI14bQCwOF8rNI1bNIBPZHBtXRUg7TgDGDN3YLiGZFIGBKqVACttAA8AIXcvH18GOLgAGSC4Ztb2kC7u3yDghLgARXwIeGm2qJAAgyqDEt4GXkKE6BdcAyCYJKcYaOQADgAGFWuIKqT3XBLruCHWxTFQARw28DqamsIAY2gAtFA4HBHCiXAY4OCNBi6gwGk0kC0dioqnENGEIrttEsVutNlNCTNdjBTvdHI9kAAmFThBgaBJLADCEDijRKUGgIJA+CqABVTtYibNbJEcKjYL4wDd1ABBKCOXwwc4MpVwIRAA)
```sh
--parser babylon
```

**Input:**
```jsx
// Input
foo(
  ({a:{
    a,

    b
  }}) => {}
);

```

**Output:**
```jsx
// Input
foo(({ a: { a,
    b } }) => {});

```

_Originally posted by @thorn0 in https://github.com/prettier/prettier/pull/6301#issuecomment-519668330_

**Comment by sosukesuzuki** [comment]
**Expected behavior**
```js
foo(
  ({
    a: {
      a,

      b
    }
  }) => {}
);
```
