### ISSUE TITLE
Handlebars: quotes option not respected on html attributes

### ISSUE THREAD

**Issue by dcyriller** [prettier/prettier#6376]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
```hbs
<div class="a-class-name"></div>
```

**Output:**
```hbs
<div class="a-class-name"></div>
```

**Expected output:**
```hbs
<div class='a-class-name'></div>
```

**Comment by evilebottnawi** [comment]
Thanks for issue, duplicate https://github.com/prettier/prettier/issues/5828

**Comment by dcyriller** [comment]
Actually not 😞. It is the same bug in two different printers.

It makes me sad that we're not able to preprocess hbs files with html.

**Comment by evilebottnawi** [comment]
@dcyriller it should be not hard to implement, feel free to send a PR :+1:

**Comment by dcyriller** [comment]
Sure, I have it almost ready :)

**Comment by dcyriller** [comment]
It's ready there ^
