### ISSUE TITLE
Do not insert whitespaces between latin and cj letters

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#6385]
**Environments:**
- Prettier Version: 1.18.2

**Steps to reproduce:**

```md
// Input
私はJavaScriptが好きです
```

**Expected behavior:**
```md
私はJavaScriptが好きです
```

**Actual behavior:**
```md
私は JavaScript が好きです
```

***

For now, Prettier inserts whitespace between latin and Japanese/Chinese on formatting Markdown.

As mentioned in [#5938](https://github.com/prettier/prettier/issues/5938), this is not good behavior for Japanese, but correct for Chinese.

I tried to avoid this problem in [the same way as handling Korean language](https://github.com/prettier/prettier/pull/5040), but it was impossible because Japanese and Chinese uses same Kanji letter, with same char code.

From above reason, I think we should add new option like `add-whitespace-between-latin-and-cj` to determine whether whitespace is inserted between latin and cj.

Of cource it's the best if there is the way to distinguish Japanese and Chinese.

**Comment by ikatyang** [comment]
I still think those whitespaces could improve their readability, but since inserting physical whitespaces did affect the AST, which violates our correctness goal, we should probably do something for it.

**Comment by sosukesuzuki** [comment]
@ikatyang How do you think about add a option for this problem?

**Comment by ikatyang** [comment]
These whitespaces are very subtle, they could be considered visual aesthetics since markdown is a language for documentation, adding whitespaces does not change their meaning in general, but technically it did change their AST.

Personally, I won't object to add an option for it. But according to our [option philosophy](https://prettier.io/docs/en/option-philosophy.html), we should avoid adding options if possible so I'll let other maintainers decide if we should add it.

**Comment by Monchi** [comment]
I think Prettiter should do nothing for whitespaces, because whether whitespace should be inserted between Japanese letter and non-cjk letter is depending on the case.

In general, Japanese word in English sentence should be surrounded with whitespace and English word in Japanese sentence shouldn't be surrounded.
Those two sentence below is both valid.
```
JavaScriptはプログラミング言語です。
作る means MAKE in English.
```

**Comment by sosukesuzuki** [comment]
/cc @ikatyang 

I'll try implement to don't insert whitespace between latin and any cjk letters, NOT to add option. From below 2 reasons:

1. Prettier should not break AST.
2. It is so difficult to determine whitespace be inserted.

**Comment by ikatyang** [comment]
While not adding option is good but removing a feature is not a good idea IMO. From what I saw on Twitter, some people did enjoy using this feature. I'm not sure how uncommon it is for Japanese but it's [the recommended format for Chinese \[Chinese docs\]](https://github.com/ruanyf/document-style-guide/blob/master/docs/text.md) at least. If we're going to remove this feature, I'd say we should provide some alternative tools (or plugins) at the same time so that we won't bother people too much.

**Comment by shuata** [comment]
> While not adding option is good but removing a feature is not a good idea IMO. From what I saw on Twitter, some people did enjoy using this feature. I'm not sure how uncommon it is for Japanese but it's [the recommended format for Chinese [Chinese docs]](https://github.com/ruanyf/document-style-guide/blob/master/docs/text.md) at least. If we're going to remove this feature, I'd say we should provide some alternative tools (or plugins) at the same time so that we won't bother people too much.

No. Your reference is just a personal guide in chinese world. Check this official  [text layout guide](https://www.w3.org/TR/clreq/#mixed_text_composition_in_horizontal_writing_mode).

In a word, the space between cjk characters and latin characters is a **polution**. This work should be done by the layout engine instead of changing the text directly. So i think at least there should be an option to close these feature while removing the "feature" is a more wise action.

**Comment by gentksb** [comment]
I'm facing this issue too.
In Japanese, space character is uncommon to seperate cjk and latin. In general, never use space characters in Japanese.  The same applies when including English words in sentences.

If prettier can't detect Chinese or Japanese, it better way to adding "space cjk between latin" option.

**Comment by thorn0** [comment]
Why can't Prettier simply leave this whitespace (or lack of it) the way it was written in the input? In English, periods and commas should be followed by whitespace. Does Prettier care about that? [Nope](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE04BoYHcInagBxgEtoBnZUAQwCcaIsAFWhClKgNwmIBM8QARjSpgA1nBgBlAiOJQA5shg0ArhhAALGAFsANgHUNxeGRlg4k1seIdjAT2TgyFfHLJwaMRsPnaqyADMqXXd8ACsyAA8AIWExCUkqbTgAGTk4QODQkAjIyTl5XTgARRUIeEyQ9RkadxpHPxpRHgYofgIaORh9XhgNZAAOAAZ8Doh3fWECRw64Oo4M-ABHMvhvCAI2ECoyAFooODgeI-4aOBXiM+8qX38kIKr8d21iJVV1MgKi0vKM+6z1DAqAIejw+sgAEz4ZRUYi6AoAYQg2j8jigaH4KncABVgWwHtkOGoAJJQY6wSRgTpEACCZMkMDsRUq7gAvqygA). How is this situation different?

**Comment by uptonking** [comment]
@ikatyang   
An important use case for me is to copy and paste api docs from `.docx`/`.md` files to `.md`/`.docx`.   
Prettier made me sick if I update docs in markdown.   
When I copy updated and formatted docs from `.md` back to `.docx`, I have to remove the auto-added whitespaces one by one. I can't remove all whitespaces at once because some are necessary. It's really unnecessary for prettier to add whitespaces.   
Please provide an option for us. unchanged or auto-adding-space-for-cjk

**Comment by tats-u** [comment]
Official text style guide lines say:

Japanese:

> Note that Western word space (cl-26) is a one third em space, in principle, except at line head, line head of warichu, line end and line end of warichu.

> “one third em” means one third of the full-width size. (JIS Z 8125)
> “one third em space” means amount of space that is one third size of em space.

Chinese:

> In principle, there is tracking or spacing between an adjacent Han character and a Western character of up to one quarter of a Han character width, except at the line start or end.
> Another approach is to use a Western word space (U+0020 SPACE), in which case the width depends on the font in use.

https://www.w3.org/TR/jlreq/#mixed_text_composition_in_horizontal_writing_mode
https://www.w3.org/TR/jlreq/#term.one-third-em
https://www.w3.org/TR/jlreq/#term.one-third-em-space

https://www.w3.org/TR/clreq/#mixed_text_composition_in_horizontal_writing_mode

Anyway, the length of spaces between different types of characters is based on Han characters (or Hiragana / Katakana).
The image below shows that the spacing between hiragana or kanji and alphabets is 1/3 of the length of the former and that it is different from the spacing between English words.

![image](https://user-images.githubusercontent.com/12870451/92094047-f8d6c900-ee0e-11ea-8164-2fc7d54cdeb7.png)

**Even in Chinese, the act of inserting U+0020 is not the only standard, and takes away the option of document viewers and converters to insert spaces a quarter of the width of Han characters, which is unacceptable.  The spacing between Han characters and the alphabet should be left to them.**

**Comment by thorn0** [comment]
see also the discussion in https://github.com/prettier/prettier/pull/8526

**Comment by tats-u** [comment]
@thorn0 My comment is mainly for @ikatyang, who is the source of all this and who sticks to rule that is not the only standard even in Chinese, and prevents the abhorrent behavior from being controlled.
And we
need a quick fix anyway, even if it's a makeshift.
It's important to mitigate the problem by adding an option to temporarily disable it before spending too much time trying to solve the underlying problem.

taiwan.gov, gov.cn, and Chisese Wikipedia don't insert U+0020 between han characters and alphabets or numbers.

**Comment by tats-u** [comment]
Shall I create a PR based on now-defunct #8526?

```
--insert-cj-space {yes,no} Insert space between Chinese and Japanese letters and other letters.
Defaults to yes.
```

I really wanted to set the default value to no, but I did it in consideration of some Chinese.

**Comment by thorn0** [comment]
@tats-u Please read the discussion. This behavior simply should be disabled for `--prose-wrap preserve` (which is the default value, BTW). Whitespace should be kept as is in that case because it's processed with the sole purpose of rewrapping lines. If wrapping is disabled, why change whitespace?

**Comment by tats-u** [comment]
@thorn0 
> This behavior simply should be disabled
> If wrapping is disabled, why change whitespace?

Is it true that `this behavior` and `change whitespace` mean the currently problematic behavior (adding extra spaces around Chinese and Japanese letters)?  If true, it is for backward compatibility (It is preferable to go through a phase of outputting warnings and then discontinue it).  I feel like abolishing the current behavior of inserting a space suddenly has too much impact.  

BTW, some Markdown viewer used in Japan (e.g. https://github.com/weseek/growi (as an option) and https://qiita.com/) treats single line breaks as `<br />`.  (same as trailing double spaces; double line breaks are treated as `</p><p>`, as usual)

**Comment by thorn0** [comment]
> Is it true that this behavior and change whitespace mean the currently problematic behavior (adding extra spaces around Chinese and Japanese letters)?

Right. By "this behavior" I mean splitting the text into words. In the first place, it's needed for wrapping. With `--prose-wrap preserve`, it's useful only for replacing multiple spaces with one.

So the fix would be the following: if `--prose-wrap` is set to `preserve`, Prettier still should simplify multiple spaces, but it shouldn't add or completely remove whitespace between Latin and CJK.

Such a fix wouldn't close this issue completely because the other two `--prose-wrap` modes still would need fixing. But it'd be a good first step.

> it is for backward compatibility (It is preferable to go through a phase of outputting warnings and then discontinue it). I feel like abolishing the current behavior of inserting a space suddenly has too much impact.

Don't worry about that. It's a bug fix.
Also the maintainers are thinking of doing a new major (3.0) release, which would contain breaking changes. Drastic formatting changes would look better in a major release than in minor. But I really don't think this change is drastic.

> Is discussion the following?

I mean the entire discussion (also [on Twitter](https://mobile.twitter.com/thorn0/status/1271384214726901761)), not individual messages. The consensus we've come to is that the issue can be fully solved without adding an option. With such a conclusion and given Prettier's [option philosophy](https://prettier.io/docs/en/option-philosophy.html), a PR that adds an option has no chance to be merged.

> BTW, some Markdown viewer used in Japan ... treats single line breaks as `<br />`

Supporting other `--prose-wrap` modes for CJK (which could help for compatibility with those viewers) is a tricky task, but we plan eventually to tackle that too.

**Comment by tats-u** [comment]
> It's a bug fix.
> Also the maintainers are thinking of doing a new major (3.0) release, which would contain breaking changes. 

> The consensus we've come to is that the issue can be fully solved without adding an option. With such a conclusion and given Prettier's option philosophy, a PR that adds an option has no chance to be merged.

I got it.  Is the `master` branch for the next major release 3.0 or just a bugfix 2.1.2 as now?
If the latter, it may be hard for people other than maintainers to submit drastic (with breaking changes) PRs to mitigate this issue.
From the discussion, it seems to be necessary to introduce 2-pass to .  That is, we may have to pre-process all of given document beforehand and change the API of `src/printer-*.js`.  (Add functions for pre-processing to exported objects)
I'm concerned  that so far there doesn't appear to be any PR submitted to confront this issue.  I wonder what is troublesome (for maintainers and other than them).

> Such a fix wouldn't close this issue completely because the other two --prose-wrap modes still would need fixing. But it'd be a good first step.
> Supporting other --prose-wrap modes for CJK (which could help for compatibility with those viewers) is a tricky task, but we plan eventually to tackle that too.

Fix for them has lower priorities than that for `preserve` and it'd be good to fix in `preserve` first.

**Comment by tats-u** [comment]
You can now use my plugin to mitigate this issue:
<https://github.com/tats-u/prettier-plugin-md-nocjsp>
<https://www.npmjs.com/package/prettier-plugin-md-nocjsp>

Too late to stop me from spending time on the development of such a plugin.

**Comment by hirachan** [comment]
+1

**Comment by onlyid** [comment]
@sosukesuzuki @ikatyang 
Please can anyone fix this annoying bug?
I'm chinese and our product is OnlyID (an IDaaS solution in China similar to Auth0).
Only is 唯 in chinese, so our brand name is 唯ID, no space should be inserted because it is a brand name.

**Comment by tclzcja** [comment]
> While not adding option is good but removing a feature is not a good idea IMO. From what I saw on Twitter, some people did enjoy using this feature. I'm not sure how uncommon it is for Japanese but it's [the recommended format for Chinese [Chinese docs]](https://github.com/ruanyf/document-style-guide/blob/master/docs/text.md) at least. If we're going to remove this feature, I'd say we should provide some alternative tools (or plugins) at the same time so that we won't bother people too much.

While I definitely enjoy the readability improvement bringing by the empty spaces, this is still an issue that should and will be solved by render engine, see here [https://www.w3.org/International/articles/css3-text/](https://www.w3.org/International/articles/css3-text/). 

Plus I think iOS Safari has already been adding virtual half-space between CJK and Latin characters while displaying them.

I agree with you on providing some alternative tools just in case some people need it when the feature get removed.

**Comment by DarkGhost7** [comment]
Has this been fixed yet?

**Comment by fisker** [comment]
Not yet, I think we agree to merge this in v3.

**Comment by DarkGhost7** [comment]
Ok thanks for the update is there an eta on when v3 will be out?

**Comment by tats-u** [comment]
@fisker Do you have a plan to push patch commits for this issue to the `next` branch https://github.com/prettier/prettier/pull/9583 (for the time being)? There seems to be no commits for this issue yet. Also, do we have to create a PR to the `next` branch on behalf of you (to accelerate the release of the version 3.0)?

**Comment by tclzcja** [comment]
Quick question about this change. After this change be applied, no more space will be ADDED between Latin and CJK letters, but will the existing space between Latin and CJK be REMOVED? 

Maybe simply add an option like:

"spaceBetweenLatinAndCJK": "remove"|"add"|"keep"

**Comment by tclzcja** [comment]
Plus, it seems like characters like "%" or "&" is not considered as a Latin letter (it isn't I agree). So when we have text like:

> 有15%的人喜欢吃苹果

It will be changed into:

> 有 15%的人喜欢吃苹果

While for the best readability it should be :

> 有 15% 的人喜欢吃苹果

Any idea on this?

**Comment by fisker** [comment]
> Ok thanks for the update is there an eta on when v3 will be out?

Not yet.

> Also, do we have to create a PR to the next branch 

Yes, the PR should target `next` branch. (I thought this is a PR...)

> Quick question about this change. After this change be applied, no more space will be ADDED between Latin and CJK letters, but will the existing space between Latin and CJK be REMOVED?

I think we'll not ADDED/REMOVED any space, just keep it as it is.

---

@sosukesuzuki I thought there was a PR fix this?

**Comment by tclzcja** [comment]
> I think we'll not ADDED/REMOVED any space, just keep it as it is.
Ok thank you. I think that answers my 2nd question too.

**Comment by sosukesuzuki** [comment]
> I thought there was a PR fix this?

Maybe no. A PR that adds new options for this was created, but it has been closed already (#8526).

**Comment by arielyang** [comment]
> > While not adding option is good but removing a feature is not a good idea IMO. From what I saw on Twitter, some people did enjoy using this feature. I'm not sure how uncommon it is for Japanese but it's [the recommended format for Chinese [Chinese docs]](https://github.com/ruanyf/document-style-guide/blob/master/docs/text.md) at least. If we're going to remove this feature, I'd say we should provide some alternative tools (or plugins) at the same time so that we won't bother people too much.
> 
> No. Your reference is just a personal guide in chinese world. Check this official [text layout guide](https://www.w3.org/TR/clreq/#mixed_text_composition_in_horizontal_writing_mode).
> 
> In a word, the space between cjk characters and latin characters is a **pollution**. This work should be done by the layout engine instead of changing the text directly. So i think at least there should be an option to close this "feature" while removing it is a more wise action.

Hey guys, the top 3 biggest company in the world use whitespaces between half-width and Chinese character. Check yourself:

https://www.apple.com.cn
https://www.microsoft.com/zh-cn/
https://aws.amazon.com/cn/

**Comment by tats-u** [comment]
@arielyang 
I suppose that you should refer to websites of governments.

https://www.gov.cn/
https://www.kantei.go.jp/

This affects also on Japanese.

https://www.apple.com/jp/ -> **Does not insert ones**
https://aws.amazon.com/jp/ -> Insert ones
https://www.microsoft.com/ja-jp -> Insert ones

You are required to note that using U+0020 **is just optional and not mandatory** (https://www.w3.org/TR/clreq/#mixed_text_composition_in_horizontal_writing_mode) even in Chinese and **not defined** in Japanese (https://www.w3.org/TR/jlreq/#mixed_text_composition_in_horizontal_writing_mode).

**Comment by vfilter** [comment]
I was just writing our Japanese documentation in markdown and can confirm that this is completely unnatural in Japanese and means that we will have to write everything, turn off prettier and remove the spaces manually, which is a huge pain. Having an option for this would be really good.

**Comment by kissge** [comment]
Is there any hope for this to be fixed as early as in v2? Would it be accepted if a PR is submitted?
This behaviour is definitely unreasonable default for Japanese writings. It's basically severing what I write and it's even unrecoverable. It's not "code formatting that won’t affect the AST" which prettier claims to do.

**Comment by tats-u** [comment]
@kissge I have sent a PR (https://github.com/prettier/prettier/pull/11597) to fix this in the next major version, but will not be merged as now. Maintainers says that it takes long time to release it.

Honestly speaking, I believe that Prettier should not wait all changes planning in the next release and fix this issue as soon as possible.
C++11 initially planned to be released before 2010 and tried to wait all features to be implemented, Ultimately, that plan fell through and the release was delayed to 2011.  In response to this, newer C++ standards are always released every three years. (features are delayed to later standards.)
I would not like Prettier to make the same mistake as C++11.

**Comment by DarkGhost7** [comment]
I too would like to see this fixed asap. Please fix it soon.

**Comment by DarkGhost7** [comment]
> Quick question about this change. After this change be applied, no more space will be ADDED between Latin and CJK letters, but will the existing space between Latin and CJK be REMOVED?
> 
> Maybe simply add an option like:
> 
> `"spaceBetweenLatinAndCJK": "remove"|"add"|"keep"`

Pretty sad to see how long it has taken and probably will take to see this added if it ever gets added...

**Comment by fisker** [comment]
The alpha release is for plugin developers, I only mentioned changes for the plugin system.

**Comment by tats-u** [comment]
@fisker I got your policy. I'll look forward to the release note of the first beta version.
