### ISSUE TITLE
@import url in html, space being added after comma

### ISSUE THREAD

**Issue by duhseekoh** [prettier/prettier#6389]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UGcAhgCaHEDOMAnjnAAT0AOcAvASPAB4wB6MNWrcqTCUwACASyysIAJxhMAropwAKTDFbUkAgQDNoMagDoA5hAiXGpVjIuQsQkQH4jpLDJx0OAEoQAEYQMBBIACwADNEANADssQCUANxEEqgCtAxwVFnoZJREBdj4IHEgEKwwMtDUyKCkiooQAO4ACs0IDSikAG4QMuQVIMGKpGAA1nAwAMqskzJQlsgwiqpwlZi4AOroMvDUi2Bwcz2HMv2HdMjgIqPL1HDKHROWWKTIXjjPlQBW1F4ACEJtNZnNvHAADLLODfUi-LYgQG8ObLOxwACKqjC8KQPz+IEWimeijuOxwo1YimWMF2wxg6GQAA54sTWs9dhNWHcaXAyf14ZUAI64+Bvaq9ECkagAWigcDg5GVo0UcDFMnVb1IHy+BMRROePjWG2R1AxjBxeIRSMqMFIwQZ5CZyAATPaJr4MQBhCBYT53KDQYUgVTPAAqjt6hORspgtqJ5AgYETyIgql0mbdaYAvrmgA)
```sh
--parser html
```

**Input:**
```html
<html>
<head>
<style type="text/css">
    @import url(https://fonts.googleapis.com/css?family=Roboto:400,700);
  </style>
</head>
</html>
```

**Output:**
```html
<html>
  <head>
    <style type="text/css">
      @import url(https://fonts.googleapis.com/css?family=Roboto:400, 700);
    </style>
  </head>
</html>

```

**Expected behavior:**

The space should not exist after the comma: `400, 700`.

There's a similar issue (https://github.com/prettier/prettier/issues/5014) for when the parser is css and the suggested workaround of adding quotes does not work because those quotes get encoded when using the html parser.

**Comment by evilebottnawi** [comment]
Yes, it is duplicate https://github.com/prettier/prettier/issues/5014, html parser should not remove quotes

**Comment by evilebottnawi** [comment]
Duplicate if #5014
