### ISSUE TITLE
Access to Prettier Azure Pipeline

### ISSUE THREAD

**Issue by ntotten** [prettier/prettier#6390]
I am the new maintainer of https://github.com/prettier/prettier-vscode and I switched to use azure pipelines for builds so I can test on windows. Right now I have my own account, but it probably makes sense to use the same Azure pipeline account as this project. Could somebody provide me access? My email is nathan@ntotten.com

**Comment by brodybits** [comment]
Just an off-topic FYI that the new GitHub CI seems to be just like Azure Pipelines. I wonder if the new GitHub CI would make it easier for external contributors to have their own CI builds?

**Comment by ikatyang** [comment]
@ntotten I've [added prettier-vscode to our Azure Pipelines](https://dev.azure.com/prettier/prettier-vscode/_build) and you should receive the invitation email. Let me know if it works.

**Comment by ntotten** [comment]
@ikatyang I see the pipeline is working, but the github integration seems to be disconnected now. I think only org admins can set it up. Would you mind reinstalling the Azure Pipeline integration into the repo and linking it. https://github.com/prettier/prettier-vscode/settings/installations

Thanks!

**Comment by ikatyang** [comment]
I've reinstalled it but it seems [the build is still not triggered by commits](https://github.com/prettier/prettier-vscode/commits/ikatyang/test-azure-pipeline), not quite sure how to solve this problem. I've made you the prettier-vscode project admin on the Azure Pipelines so you should be able to do what you want.

**Comment by ikatyang** [comment]
The Travis CI is installed on all the repo under the Prettier org so I guess you could just ignore that.

**Comment by ikatyang** [comment]
I probably found the problem:

> The repository prettier/prettier-vscode is in use with the Azure Pipelines GitHub App in another Azure DevOps organization. [Learn more](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github#create-pipelines-in-multiple-azure-devops-organizations-and-projects)
>
>> #### Create pipelines in multiple Azure DevOps organizations and projects
>> Once the GitHub App is installed, pipelines can be created for the organization's repositories in different Azure DevOps organizations and projects. However, if you create pipelines for a single repository in multiple Azure DevOps organizations, **only the first organization's pipelines can be automatically triggered by GitHub commits or pull requests**. Manual or scheduled builds are still possible in secondary Azure DevOps organizations.

It seems you have to disconnect it in the previous Azure Pipeline project.

**Comment by ntotten** [comment]
@ikatyang I think I have successfully disconnected the repos from the old project. Would you mind trying the link again? Thanks!

**Comment by ikatyang** [comment]
I'm not quite sure why but I still got this message after reinstalling.

![image](https://user-images.githubusercontent.com/8341033/63180335-a3ebd780-c080-11e9-8f74-e5454c2e297f.png)

**Comment by ntotten** [comment]
Hmm. I reached out to MSFT to see what is going on. Hopefully, they can resolve it. :/

**Comment by ntmonson** [comment]
@evilebottnawi I believe you intended to cc @ntotten
