### ISSUE TITLE
CSS/SCSS config options (empty line beetwen, etc.)

### ISSUE THREAD

**Issue by kanlukasz** [prettier/prettier#6391]
Hello,
I miss options to config CSS formatting. Is any chance to add this?

For example:
- i would like to automatically remove empty lines between CSS properties
	```
	span {
		border: 1px solid red;
		<!-------- REMOVE THIS EMPTY LINE -------->
		background-attachment: fixed;
	}
	```
- I would like to add empty lines between the opening and closing parenthesis of @media
	```
	@media only screen and (min-width: 768px) {
		<!-------- KEEP or ADD THIS LINE -------->
		.entry .entry-content .block-audio.alignright audio {
			max-width: 384px;
		}

		.entry .entry-content .block-video video {
			width: 100%;
		}
		<!-------- KEEP or ADD THIS LINE -------->
	}
	```
What do you think about it?

**Comment by evilebottnawi** [comment]
No option(s) for this, currently output is good we don’t want to change it, also please use issue template in future, you can use stylelint to format expected output

**Comment by kanlukasz** [comment]
Thank you for the information and sorry for the ticket without a template
