### ISSUE TITLE
Unexpected formatting for script tag

### ISSUE THREAD

**Issue by pikeas** [prettier/prettier#6393]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABMagEYQAmAnoSaWQM5gBOAlgA4xGOMCGTGlDABeAiAm8+xdlXGTJDPk1ZiJAegD6UOAA8YGpjH4x2YDVTgA3ODgicsCQ534BzOE239OnAHQAVkwA-DBMogCMAKwAbFEA7ADMAEwRAJxRaTEAHFLKxHioRmxcMIUsHNyFxZVl0kWUtPRFmLj0RCAANCAOZtBMyKD8rKwQAO4ACsMIAyj81hByXSDkrPxgANZwMADKrmDsUG7IMKwArnDdrTgA6ujs8Ez7cDszD+zWDzTIIMYcYDBlocmHBWDAJms3Fh+MgAGb8HAg7pBPQAITWm22O34TgAMoc4HCEUiQCidoc3Dg4ABFM4QeBExGXECuVgg1g-a7LTgcWA3OQwdDIbIABm6PIgIJua04Px5nlBtmWAEc6fAIQ5ZiBBABaXRwKxUZasOCq9gmiHuaGMkkgrDsE7nZlMClU2n0wlIeFM7omcj8qiC5DJX1rdg4CkAYQgWGtKCg0EJ3TOIIAKvxyLNvSCAL45oA)
```sh
--html-whitespace-sensitivity strict
--parser html
```

**Input:**
```html
<html>
  <body>
    <script
      async=""
      id=""
      src="/_next/static/development/pages/_app.js?ts=1565732195968"
    ></script><script></script>
  </body>
</html>
```

**Output:**
```html
<html>
  <body>
    <script
      async=""
      id=""
      src="/_next/static/development/pages/_app.js?ts=1565732195968"
    ></script
    ><script></script>
  </body>
</html>
```

**Expected behavior:**

There are several previous GH issues about HTML whitespacing sensitivity, which seem to be related to this but not quite the same. There's also https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting.

For the above input, the output for `css` and `strict` are the same. For this case, prettier adds an extra newline for `</script><script></script>`, and borrows the closing `>` while doing so. 

This looks like an incorrect result. I expected either `<script></script>` on a newline (without the borrowed `>`), or for the input HTML to remain unmodified (when using `strict`).

This output is also problematic for syntax highlighters. You can see this happening in Github's highlighting for the text above.

**Comment by evilebottnawi** [comment]
Thanks for issue
