### ISSUE TITLE
Prettier breaks lines when arg has decorator and is destructured

### ISSUE THREAD

**Issue by MichalLytek** [prettier/prettier#6394]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCpyYwBiEATgLbowwCWUA5jsADpQ44ACAsgK4zVa0ABRk4MXmSi4AvAD4cAZQEAzFQEo2HLAE8oYHOgoIAJsvRrhWjlwCCZBlZD0ADvxYhN7G8By0TADQ4AHShRqbmagAi1Og4AL5IOLbGUGaqKgCSUG4w1upJAApkEBS0mHAAPJEqCqzeHGISUjhEFioA3NbxbD1QbGAY2PiEJORUNPRM9Rw8-IIiTZLSOPJKGV7amHoG4Wk1Vg12Dk6u7p7W2qiYEAAy0AwAcuHc6DoARnAAanBkOveMADyZAAogA3BAAhi-JIpCIZbK5fJFEplCrVDJ1S44JYtNpqLrePrxEABEAQFx0aCYZCgdBkEoAd0K9IQNJQ6DBEH8pJA7zI6DAAGtxIoXIKpsgYGReHAyQALGAUVAAdXltHgmHFYDgijZGtoYI1OmQ4GwvPoFTIMGK6AYVGQKnQ1zlIAAVpgAB4AIQFwtF4Vu9DgjudFTJHs9iimqDgAEVeBB4KGXWTxWQrab3uh3jpUNBeS4yPQYCr-DB5cgABwABjTJQqKoFLlNRcIvwhvIAjon4MUKeyQFgALRQOBwEwT3liHu0MS2+3oFPhkAVMpSmWuzAx+O9kNIJ2pkACd5lkwV5AAJjJ0vQtFQUwAwqUHSgoNAQ2TeBU8Dn2YeKnieIgA)

**Input:**
```ts
class TestFormatting {
  @Mutation(returns => Staff)
  async amendStaff(
    @Arg("input")
    { id, ...amendStaffData }: AmendStaffInput
  ): Promise<Staff> {
    return staff;
  }
}
```

**Output:**
```ts
class TestFormatting {
  @Mutation(returns => Staff)
  async amendStaff(@Arg("input")
  {
    id,
    ...amendStaffData
  }: AmendStaffInput): Promise<Staff> {
    return staff;
  }
}
```

**Expected behavior:**
Keep the destructured variables in one line (keep original formatting).
```ts
class TestFormatting {
  @Mutation(returns => Staff)
  async amendStaff(
    @Arg("input")
    { id, ...amendStaffData }: AmendStaffInput
  ): Promise<Staff> {
    return staff;
  }
}
```

This is the behavior for normal parameters that are not destructured:

```ts
class TestFormatting {
  @Mutation(returns => Staff)
  async amendStaff(
    @Arg("input")
    alsoLongNameMaybeVeryLongOrEvenLonger: AmendStaffInput
  ): Promise<Staff> {
    return staff;
  }
}
```

**Comment by evilebottnawi** [comment]
Expected is not same as input and output

**Comment by 19majkel94** [comment]
@evilebottnawi updated

**Comment by evilebottnawi** [comment]
i think it is bug, decorator here on ugly place
