### ISSUE TITLE
Potential bug: Ugly code example when breaking line

### ISSUE THREAD

**Issue by fab1o** [prettier/prettier#6396]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6URMAtnDABYQAmAFBAA4wCW0mAlISTvwIGQomGIRxwAHszhh4dHAF4cUAK6pUAGhyY2UAObr0AJyUr1WnM1Srj6VGbUbtbTHmN2AnmYBm9zHDaosZ6+mw+3spODgC+ZizsnDgAPsmEMQDcfAIxJLlQ-CRgGNg4AEK8pBRUtIwJHCI8xAWCgsKi4lIycnAKURZBoUam-c5WNnYOo5au7l6+-oE6MCEG4ZHmGjhxyvWcWS38+TEgmiB7IsigJsYQAO4ACiYImMgg6ABuEGx0pyAARnYwABrKgAZWY6DAoWQK1UgRA1AoqAA6tQ2PBMJCwHAwS8MWwPhjPG8wNg-noAsYYA87PpyOhkH5UAEzgArTCSMpA0EwMHoSgAGT0cCZi3ZnLBoVQcAAiqoIPAxSyEZDjFS3v90P84Kg-sxVjAUT8aMgAIwABgtZwNEACKLszDeBrgVI+orOAEcFfBaSxXigsABaKBwXq9P7GODethR2noemMpDM1kgALkNiw4zws66Awy+WK0XJ8UgGDa410U1IABMZxW6DYqFCAGEIOQGW8oNAPSBVAEACragMpuAxGJAA)
```sh
--parser babel
--print-width 100
```

**Input:**
```jsx
class A {
	method(options) {
         const { expected = null, singular = null, plural = null, isArray = false, stringify = null } = options || {};
    }
}
  
class B {
	method(options) {
         const { expected = null, singular = null, plural = null, isArray = false, stringify = null } = options;
    }
}
```

**Output:**
```jsx
class A {
  method(options) {
    const { expected = null, singular = null, plural = null, isArray = false, stringify = null } =
      options || {};
  }
}

class B {
  method(options) {
    const {
      expected = null,
      singular = null,
      plural = null,
      isArray = false,
      stringify = null
    } = options;
  }
}

```

**Expected behavior:**
```js
class A {
  method(options) {
    const {
      expected = null,
      singular = null,
      plural = null,
      isArray = false,
      stringify = null
    } = options || {};
  }
}

class B {
  method(options) {
    const {
      expected = null,
      singular = null,
      plural = null,
      isArray = false,
      stringify = null
    } = options;
  }
}

```

**Comment by lydell** [comment]
It's certainly unexpected that adding `|| options` completely changes how the line is broken.

**Comment by sosukesuzuki** [comment]
Playground Link looks like broken. We should probably replace it like this [Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6URMAtnDABYQAmAFBAA4wCW0mAlISTvwIGQomGIRxwAHszhh4dHAF4cUAK6pUAGhyY2UAObr0AJyUr1WnM1Srj6VGbUbtbTHmN2AnmYBm9zHDaosZ6+mw+3spODgC+ZizsnDgAPsmEMQDcfAIxJLlQ-CRgGNg4AEK8pBRUtIwJHCI8xAWCgsKi4lIycnAKURZBoUam-c5WNnYOo5au7l6+-oE6MCEG4ZHmGjhxyvWcWS38+TEgmiB7IsigJsYQAO4ACiYImMgg6ABuEGx0pyAARnYwABrKgAZWY6DAoWQK1UgRA1AoqAA6tQ2PBMJCwHAwS8MWwPhjPG8wNg-noAsYYA87PpyOhkH5UAEzgArTCSMpA0EwMHoSgAGT0cCZi3ZnLBoVQcAAiqoIPAxSyEZDjFS3v90P84Kg-sxVjAUT8aMgAIwABgtZwNEACKLszDeBrgVI+orOAEcFfBaSxXigsABaKBwXq9P7GODethR2noemMpDM1kgALkNiw4zws66Awy+WK0XJ8UgGDa410U1IABMZxW6DYqFCAGEIOQGW8oNAPSBVAEACragMpuAxGJAA).

**Comment by lydell** [comment]
@sosukesuzuki Thanks, updated.

**Comment by seiyab** [comment]
Looks to work fine as of 3.0.0

**Comment by kachkaev** [comment]
Thanks @seiyab! You are right:

**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6URMAtnDABYQAmAFBAA4wCW0mAlISTvwIGQomGIRxwAHszhh4dHAF4cUAK6pUAGhyY2UAObr0AJyUr1WnM1Srj6VGbUbtbTHmN2AnmYBm9zHDaosZ6+mw+3spODgC+ZizsnDgAPsmEMQDcfAIxJLlQ-CRgGNg4AEK8pBRUtIwJHCI8xAWCgsKi4lIycnAKURZBoUam-c5WNnYOo5au7l6+-oE6MCEG4ZHmGjhxyvWcWS38+TEgmiB7IsigJsYQAO4ACiYImMgg6ABuEGx0pyAARnYwABrKgAZWY6DAoWQK1UgRA1AoqAA6tQ2PBMJCwHAwS8MWwPhjPG8wNg-noAsYYA87PpyOhkH5UAEzgArTCSMpA0EwMHoSgAGT0cCZi3ZnLBoVQcAAiqoIPAxSyEZDjFS3v90P84Kg-sxVjAUT8aMgAIwABgtZwNEACKLszDeBrgVI+orOAEcFfBaSxXigsABaKBwXq9P7GODethR2noemMpDM1kgALkNiw4zws66Awy+WK0XJ8UgGDa410U1IABMZxW6DYqFCAGEIOQGW8oNAPSBVAEACragMpuAxGJAA)

```sh
--parser babel
--print-width 100
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```jsx
class A {
	method(options) {
         const { expected = null, singular = null, plural = null, isArray = false, stringify = null } = options || {};
    }
}
  
class B {
	method(options) {
         const { expected = null, singular = null, plural = null, isArray = false, stringify = null } = options;
    }
}
```

**Output:**

```jsx
class A {
  method(options) {
    const {
      expected = null,
      singular = null,
      plural = null,
      isArray = false,
      stringify = null
    } = options || {};
  }
}

class B {
  method(options) {
    const {
      expected = null,
      singular = null,
      plural = null,
      isArray = false,
      stringify = null
    } = options;
  }
}

```

Let’s close this issue 🎉
