### ISSUE TITLE
[Plugin] Prettier plugin defaultOptions not working

### ISSUE THREAD

**Issue by gengjiawen** [prettier/prettier#6399]
## Repro
https://github.com/gengjiawen/prettier-plugin-test
```bash
yarn
yarn test
```
I set the `semi: false` in https://github.com/gengjiawen/prettier-plugin-test/blob/917d4d9d9d8d2aff6bcbb62b04afedbd100e4632/index.js#L25.
But looks like it's not working.

I am new to https://prettier.io/docs/en/plugins.html, do I miss something or it's a bug ?

**Comment by gengjiawen** [comment]
@evilebottnawi @lydell Can you help on this issue ? Thanks.

**Comment by thorn0** [comment]
You should've filled the issue template. A proper report should include: 1) reproduction steps, **2) expected behavior, 3) actual behavior**. Please add the latter two.

**Comment by gengjiawen** [comment]
> You should've filled the issue template. A proper report should include: 1) reproduction steps, **2) expected behavior, 3) actual behavior**. Please add the latter two.

2) expected behavior

Semi will disappear after prettier plugin processed.

3) actual behavior.

Currently semi still exist.

**Comment by thorn0** [comment]
"Semi will disappear after prettier plugin processed"

What does it mean?

**Comment by gengjiawen** [comment]
> "Semi will disappear after prettier plugin processed"
> 
> What does it mean?

As I stated in Readme

> I set the semi: false in gengjiawen/prettier-plugin-test:index.js@917d4d9#L25.

It's not take effect.

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/6348

**Comment by gengjiawen** [comment]
> fixed by #6348

Thanks :)
