### ISSUE TITLE
HTML Adds Newlines Before Closing Angle Bracket

### ISSUE THREAD

**Issue by karlhorky** [prettier/prettier#6401]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeANgQwEZ3QAgDMIAnAXgB0QATTeKgPlQGcAHTKfMLZ5ymunAC0WXOkYAZaAHN88AB4w5EfHHlg4cavlYkAlrADqe6jAAWAOnxSoshUpgq1GrTv1GT5i6gD0bDkw+ongMIAA0IBCsMHrQzMigmCQkEADuAApJCPEomABuECbhINgkmGAA1nAwAMrsYAbSyDAkAK5wEWYwALbohmZ68P4aNdmDenmDAJ7I4LzFBsxwJDDpZdLdmMiEmOhLEQBWzPIAQmWV1TWY3XASBnDbu-sgR-I1jehwAIqtEPCPew6IHYJCWJFmXV6xV0BhgxlMZmQAA4AAwRXQQJaGMqsWa6OBgvIPCIAR1+8DWURyIEwzCEUE01C0xRIcDJelZa0wGy2SB2gIiS26emabSBzA+33JDz5TyBMBw8PMyAATBEWpg9OhGgBhCDdTazKDQYkgVpLAAqOBy-KWAF87UA)
```sh
--parser html
```

**Input:**

```html
<label for="date"><span class="date-label">Long text to exceed printWidth. Long text to exceed printWidth.</span></label>
```

**Output:**

```html
<label for="date"
  ><span class="date-label"
    >Long text to exceed printWidth. Long text to exceed printWidth.</span
  ></label
>

```

**Expected behavior:**

```html
<label for="date">
  <span class="date-label">
    Long text to exceed printWidth. Long text to exceed printWidth.
  </span>
</label>
```

---

Potentially related to the `angular` parser bug here: https://github.com/prettier/prettier/issues/6241

**Comment by lydell** [comment]
Hi! It sounds like you might be looking for the [html-whitespace-sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option?

**Comment by karlhorky** [comment]
Aha, this is by design. From the [Whitespace-sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) note on the `1.15.0` release:

> As you may notice during daily HTML works, the following two cases won't produce the same output:
> 
> `1<b> 2 </b>3` results in 1<b> 2 </b>3
>
> `1<b>2</b>3` results in 1<b>2</b>3
>
> This is because whitespaces are sensitive in inline elements.
> 
> For this reason, we cannot safely format
>
> ```html
> <a href="https://prettier.io/">Prettier is an opinionated code formatter.</a>
> ```
> 
> into
>
> ```html
> <a href="https://prettier.io/">
>  Prettier is an opinionated code formatter.
> </a>
> ```
>
>
> since it may modify the displayed output in the browser.


I've been working with JSX for so long I forgot about this. 😮 Sorry about that, closing!
