### ISSUE TITLE
Parentheses around nullish coalescing operator (??) within logical expressions

### ISSUE THREAD

**Issue by mroch** [prettier/prettier#6403]
in the latest stage 3 draft, nullish coalescing can no longer immediately contain, or be contained within, `&&` and `||`: https://tc39.es/proposal-nullish-coalescing/

so, `foo ?? bar || baz` is illegal, but you can write `(foo ?? bar) || baz`.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKVAzCEAEB+PHAIwEMAnAShwB9riSAvCkAGhAgAcYBLaAZ2ShyZCAHcACuQQCUJAG4RuAE1YgiZEmADWcGAGUOm7lADmyGGQCucNgAsYAWwA2AdVvd4fQ2Dh7pH7jkPAE9kcD4BNmM+ODIYcQ0TBxJkDBInGLYAKz4ADwAhDW1dPRIHOAAZYzhU9MyQHNy9YxMnOABFSwh4WoybEEMyGLIw0iJgp2hVDjJjGBdlGFtkAA4ABjYZiBiXDQ4wmbhhuRq2AEcu+ATOGRASPgBaKDg4JVfVMjgL7k+EkiSUkg0n02DEHNxzFZ+nwWm1Ot0akC6v0YCQiAslEtkAAmNgWEjcJwtADCEAcyTCUGgpxAlhiABU0TJgTEAL6soA)

**Input:**
```jsx
(foo ?? bar) || baz
```

**Output:**
```jsx
foo ?? bar || baz
```

**Expected behavior:**
```jsx
(foo ?? bar) || baz
```

Flow v0.106.0 implements the change to the spec, making this a parse error. So, prettier will turn valid code into invalid code by removing the parens.

**Comment by vjeux** [comment]
This code path doesn't go through the generic needsParen unfortunately, probably because of the special handling of chains of boolean expressions. I'm going to a meeting but I want to get to the bottom of it afterwards.
