### ISSUE TITLE
Typescript array containing a long union type

### ISSUE THREAD

**Issue by pfgithub** [prettier/prettier#6405]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAhgJ31zWwF5sBtAZxnwEsoBzAGmwB0QA3OfEgG2iNsdeAFts0HAAseOGBGwAzCPjA5c2KHADufBnA7YAPuy49+g4WOwAmQyY7de2AUytxxAZg4BdEMxAIDBg6aCpkUAJ8CG0ABQIEcJRcTgg6ABN-EAAjIjAAazgYAGUMXDAGRmRaAFc4AKkYUT4AdSkROCoytWLEkTpOETRkcCpwgIYqHhhYokZRXGRFXD4pgIArKgAPACE8wpLcUTgAGX0llbWQTa3iyr44AEUaiHgL1fqQMvwp-BH0LBUMD0YJZDD0WAtDIwKTIAAcAAYAuCIFMWkQMCNwZ0eNwsgBHF7wWZBJIgXBUAC0Wjg6VpWXwcEJdEZs1w80WSGWHwCU1EdGq+DqvPuTyJcHeVxguGyUPSMOQNgCtFwdD0TAAwhBRAsRlBJFkalMACoypLcqYAX0tQA)
```sh
--parser typescript
```

**Input:**
```ts
type array = [string, "very long item one here to force a newline" | "very long item 2" | "very long item 3"]
```

**Output:**
```ts
type array = [
  string,

    | "very long item one here to force a newline"
    | "very long item 2"
    | "very long item 3"
];
```

Running the output code through prettier again adds another extra newline

[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAhgJ31zWwF5sBtAHSm2wGcZ8BLKAcwBoaa66AfbFRAA3OPhIAbaG2zN4AW2zQcACzE4YEbADMI+MDlzYocAO4TWcIT14Cho8dintZC7ACZrtW4JFjJ0q5wigDMXgC6ANw0IBwgEBgwzND0yKAE+BCmAAoECKkouMIQzAAmsSAARkRgANZwMADKGLhgrGzITACucHEqMPISAOoqcnD0LQaN+XLMwnJoyOD0qXGs9GIw2URs8rjI2rgSG3EAVvQAHgBCNfVNuPJwADKWB0cnIOcXje0ScACKXQg8Dex16IBa+A2+CW6Cw9DALESFQwLFgQzKMBUyAAHAAGOKoiAbIZEDBLVHjMSiCoARyB8G2CQKIFw9AAtCY4KVuRV8HB6cx+dtcLt9khDmC4ht5MxOvgetLfgCGXBQR8YLhKhjSljkO44kxcMwLOwAMIQeR7JZQZQVLobAAqWoKko2AF93UA)

```ts
type array = [
  string,


    | "very long item one here to force a newline"
    | "very long item 2"
    | "very long item 3"
];

```

**Expected behavior:**

Not having a blank line and then extra indented unions

```ts
type array = [
  string,
  | "very long item one here to force a newline"
  | "very long item 2"
  | "very long item 3"
];
```

or

```ts
type array = [
  string,
  (
    | "very long item one here to force a newline"
    | "very long item 2"
    | "very long item 3"
  )
];
```

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by thorn0** [comment]
duplicate of #4794, PR #6381

**Comment by pfgithub** [comment]
Oh, missed that

**Comment by j-f1** [comment]
Duplicate of #4794
