### ISSUE TITLE
Refer to shared configuration package just by scope name

### ISSUE THREAD

**Issue by rdmurphy** [prettier/prettier#6413]
More feature request than issue — and apologies if I didn't see that someone suggested this already — but has there been any thought given to allowing the declaration of a shared configuration just by scoped package name if it follows (what has loosely been suggested to be the standard) a naming pattern?

For example, instead of:

```json
{
  "prettier": "@mynpmscope/prettier-config"
}
```

You could just do:

```json
{
  "prettier": "@mynpmscope"
}
```

Obviously not a massively necessary change. 😅  But I know a few other configuration systems out there support this kind of thing (I believe ESLint and Babel does?) and it could be a nice quality of life addition. Of course, maybe y'all don't wanna declare that `@scope/prettier-config` is the official pattern.

Thank you!

**Comment by lydell** [comment]
Hi!

I think it makes sense to have this shortcut in ESLint, so you can have this:


```js
module.exports = {
  plugins: ["import", "jest", "react", "react-hooks", "prettier", "css-modules"]
};
```

instead of this:

```js
module.exports = {
  plugins: [
    "eslint-plugin-import",
    "eslint-plugin-jest",
    "eslint-plugin-react",
    "eslint-plugin-react-hooks",
    "eslint-plugin-prettier",
    "eslint-plugin-css-modules"
  ]
};
```

Same things for ESLint's `extends` array.

But in Prettier's case there's _one_ package to specify. So the win of shortcuts is much smaller.

Personally, I think it's better _not_ to have a shortcut in Prettier's case. It makes things much more obvious. One thing less to learn.

Could you elaborate on how this would improve quality of life for you?

**Comment by fsmaia** [comment]
IMHO it would represent a canonical way of publishing the package, leveraging the correct way. It would also point that an organization/scope may have its default/standard preset.

I can see it becoming a must-have pattern, just like [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) to support different configuration files in a given pattern.

Commitlint uses the same ESLint pattern, and both tools name it Shareable Configs.

Examples:
- ESLint: https://eslint.org/docs/developer-guide/shareable-configs
- Commitlint: https://commitlint.js.org/#/concepts-shareable-config
