### ISSUE TITLE
`parser-glimmer` not compatible with Webpack

### ISSUE THREAD

**Issue by waynevanson** [prettier/prettier#6414]
Hi Guys,

Thanks for making everything `P R E T T I E R` !

This is in version 1.16.4 as the dependency of the package prisma. I will check if this is still broken in newer prettier versions.

So I've created an [issue](https://github.com/facebook/create-react-app/issues/7593) in the create-react-app repository for this, but I figure that it might be worth fixing at the source, if an issue at all. Please check out that issue before reading on.

If you check out the screen shot in the issue, a module is being required during the `eval` function call. From my brief research, [`eval`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Do_not_ever_use_eval!) should not be used and is the devil.

On further investigation, the code at the end of this issue may be part of this. Below it says it should change `eval('require('util').inspect')` to be `'require('util').inspect'`.

I found the following lines in the source. Are they supposed to be in there?
``` js
  var utilInspect = eval(`require('util').inspect`);
  /* istanbul ignore next */

  var _inspect = utilInspect && utilInspect.custom || 'inspect';
```

https://github.com/prettier/prettier/blob/3805034bdfe45722e31a1abf019d4368dfb8ae11/scripts/build/config.js#L107-L117

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by waynevanson** [comment]
It looks like prettier works with my issue when updating to the latest version.

It looks like everyone is looking to take out eval as it must be causing issues. I found many patch updates describing the removal of evals.
