### ISSUE TITLE
[Question] How to setup config based on file extension

### ISSUE THREAD

**Issue by ardimaunahan** [prettier/prettier#6415]
I wonder if it's possible to do it in `.prettierrc.js`. Please let me fill in the TODO part in this code:
```
var path = require('path');

let fileExtension = '';

// TODO: determine current file's extension (.js or .html). Will it work in both WebStorm's Prettier plugin and if run via CLI?

let options = {
    tabWidth: 4,
    printWidth: 100,
    bracketSpacing: false,
    singleQuote: true,
    endOfLine: 'lf'
};

switch (fileExtension) {
    case 'html':
        options.tabWidth = 2;
        break;
}

module.exports = options;
```
Or is there a much better approach?

**Comment by lydell** [comment]
Hi!

It’s called [overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides).

Does this work for you?

```js
module.exports = {
    tabWidth: 4,
    printWidth: 100,
    bracketSpacing: false,
    singleQuote: true,
    endOfLine: 'lf',
    overrides: [
        {
            files: "*.html",
            options: {
                tabWidth: 2
            }
        }
    ]
};
```

Can we make this easier to find the documentation?

**Comment by ardimaunahan** [comment]
Awesome, it works! I guess this statement can be improved to something like this:

> **_Use overrides to setup rules for multiple file extensions._** Prettier borrows eslint's override format. This allows you to apply configuration to specific files.
