### ISSUE TITLE
prettier needs to be run twice on a typescript piece of code

### ISSUE THREAD

**Issue by Janpot** [prettier/prettier#6417]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACACgJwgFsBLAZxIDM0BZOGACwgBMyAeAFQD5sBebYNgDaubCSjYA1nDQRK2DgF0kCkYuxwAHvCitsdRi2wB+PIVIVqBps05qeKjmuwBfEABoQEDDBLQyyKAAhviEAO64IQgBKEEAbhAkzB4gAEb4QWDSMADKGJniAObIMPgArnCeDDBEADYA6gwk8GT5YHA50c0kcc1oyOBkAZ7iZHD4MARBhURByJRBtWOeAFZkmgBCGVn0OUFEcAAy4nDzi8sga5o5RbVwAIplEPBnS5Ug+fhj+APoWGRgfAkHwpDBA2D1JKMZAADgADJ4wRAxvUMhgBmC4N84qdPABHJ7wAjeGIgIJkAC0UDgcGYtJS+DgBJIjKmMzmSAWb08Y1IJXK7woUEKd0ez1OnPO7xgQVSkOY0KQACZPKUgiRakUAMLEWYDKDQXEgMpjDiymJcsYuFxAA)
```sh
--parser typescript
```

**Input:**
```tsx
type PromisifyMethods<T> = { [P in keyof T]: T[P] extends Method ? PromisifyMethod<T[P]> : T[P] }
```

**Output:**
```tsx
type PromisifyMethods<T> = {
  [P in keyof T]: T[P] extends Method ? PromisifyMethod<T[P]> : T[P]
};

```

**Second Output:**
```tsx
type PromisifyMethods<T> = {
  [P in keyof T]: T[P] extends Method ? PromisifyMethod<T[P]> : T[P];
};

```

**Expected behavior:**
Only needing to run it once

**Comment by evilebottnawi** [comment]
I can't see any difference between first and second result

**Comment by SimenB** [comment]
(semicolon added)

**Comment by evilebottnawi** [comment]
Something unstable :disappointed:
