### ISSUE TITLE
Extra semicolon in TypeScript/Jest output

### ISSUE THREAD

**Issue by someguynamedmatt** [prettier/prettier#6422]
I've noticed in a few projects I've worked on that an unnecessary semicolon (`;`) is added within `it` blocks (Jest tests, specifically) immediately preceding TypeScript casting calls. I'm not sure if this is expected, but I thought I'd submit it as an issue to be sure it's not a bug. I've looked for the issue in the Issues backlog and the closest I could come up with is [#5022](https://github.com/prettier/prettier/issues/5022).

```sh
{
  "jsxSingleQuote": true,
  "printWidth": 100,
  "quoteProps": "consistent",
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5"
  "trailingComma": "es5",
  "bracketSpacing": true
}
```

**Input:**
```jsx
    it('should display Login when there is no user', async () => {
        (SessionContainer.useContainer as jest.Mock).mockImplementation(() => {
            return {user: undefined, endSession: jest.fn()}
        })
     })
```

**Output:**
```jsx
    it('should display Login when there is no user', async () => {
        ;(SessionContainer.useContainer as jest.Mock).mockImplementation(() => {
            return {user: undefined, endSession: jest.fn()}
        })
     })
```

**Expected behavior:**
No additional semicolon before the `(SessionContainer.useContainer..)` cast line

**Comment by lydell** [comment]
Hi! That semicolon is there on purpose – see the [semicolon rationale](https://prettier.io/docs/en/rationale.html#semicolons).

If it _wasn’t_ added, you could easily end up with this frustrating experience:

```diff
 it("should display Login when there is no user", async () => {
+  console.log("Does this test even run?!")
   (SessionContainer.useContainer as jest.Mock).mockImplementation(() => {
     return { user: undefined, endSession: jest.fn() }
   })
 })
```

Which actually means:

```ts
it("should display Login when there is no user", async () => {
  console
    .log("Does this test even run?!")(
      SessionContainer.useContainer as jest.Mock
    )
    .mockImplementation(() => {
      return { user: undefined, endSession: jest.fn() }
    })
})
```

Ouch! That's why Prettier adds a semicolon at the beginning of lines sometimes – to make future edits easier.
