### ISSUE TITLE
JSON format is not unique

### ISSUE THREAD

**Issue by ofk** [prettier/prettier#6424]
Formatting of the same data but with different line breaks is different.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm0gIYCMuSmA2httrkSADQWXpaVUgBGNJMATgK5wNsAXwYBdes1x4ATMTK5ZdTMBztFXPnExDRGEVDogIABxgBLaAGdkoPN24QA7gAU7CayjwA3CGYAmhmzceGAA1nAwAMrGIWZQAObIPPy0IAAWMAC2ADYA6mlm8JYxYHCR7oVmXoUAnsjgltapcZZw3DDOwfGZeMgAZnjZrakAVpYAHgBCwWERkXiZcAAycXD9g8MgY+ORcfHZcACKvBDw60NwqTHcrdz1Y9CGxtxxMLn+MGnIABwADFcOVq5YLGerPOC3LxrVIARxO8E6Jg8+EsAFooHA4H4sYZuHA4WY8Z08N1ekgBhdUq1MmYkpoqXsDsdTmtyRtLiAYHg2O8-J9kNJUjw8GZsnsAMIQTI9epQaDQkC8VoAFW5HgprSEQiAA)

```sh
# Options (if any):
--parser json
```

**Input:**
```json
{
  "a1": [
    "1",
    {
      "b1": true
    }
  ],
  "a2": ["2", { "b2": true }]
}
```

**Output:**
```json
{
  "a1": [
    "1",
    {
      "b1": true
    }
  ],
  "a2": ["2", { "b2": true }]
}
```

**Expected behavior:**
```json
{
  "a1": ["1", { "b1": true }],
  "a2": ["2", { "b2": true }]
}
```

OR

```json
{
  "a1": [
    "1",
    {
      "b1": true
    }
  ],
  "a2": [
    "2",
    {
      "b2": true
    }
  ]
}
```

**Comment by evilebottnawi** [comment]
We respect user input so you got this code, you need this https://github.com/prettier/prettier/issues/2068 to ignore user input, as workaround you can remove newlines from first and you will get same formating
