### ISSUE TITLE
Wrong version table?

### ISSUE THREAD

**Issue by hongbo-miao** [prettier/prettier#6426]
Is the version table at https://prettier.io/versions.html currently wrong?

Version | Install with | Documentation
-- | -- | --
1.18.1 | npm install prettier | stable (latest)
  | npm install prettier/prettier | next (master)

Should it be like this?

Version | Install with | Documentation
-- | -- | --
1.18.1 | npm install prettier | stable (master)
  | npm install prettier/prettier | next (next)

**Comment by lydell** [comment]
I think the names can be explained like this:

- `stable`: The name of the folder that the current stable documentation lives in in the git repo.
- `latest`: The npm tag of the latest release.
- `next`: Part of the URL of the documentation for the upcoming release.
- `master`: The name of the branch that will become the next release.

So I don't think there's anything _wrong_ with the table, but it is kind of confusing.

**Comment by lydell** [comment]
What would you like to be added/changed?

**Comment by lydell** [comment]
I see. The page is probably auto-generated by the docs framework, then.
