### ISSUE TITLE
Compact CSS format option

### ISSUE THREAD

**Issue by ajlonsdale** [prettier/prettier#6427]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option within settings to format css into a compact state rather than expanded e.g .

**this:**
```
ul { color:red; }
  ul > li { color: blue; }
```

**instead of this:**
```
ul {
  color: red;
}
ul > li {
  color: blue;
}
```

**Describe alternatives you've considered**
There is no real alternative to this at the moment, no one has managed to create a formatter that does the above including the indentations (that i can find)

**Comment by evilebottnawi** [comment]
Please read https://prettier.io/docs/en/option-philosophy.html, we don't want to modify current output right now, sorry

**Comment by ajlonsdale** [comment]
No problem, thank you

I did read that document and saw this: 

Feel free to open issues! Prettier isn’t perfect. Many times things can be improved without adding options. But if the issue does seem to need a new option, we’ll generally keep it open, to let people 👍 it and add comments.

Thought if enough people wanted the same thing then it might happen

**Comment by lydell** [comment]
Duplicate of #5948
