### ISSUE TITLE
Invalid trailing comma insertion for empty destructured argument

### ISSUE THREAD

**Issue by joel-duolingo** [prettier/prettier#6435]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzTBeTACmAF8lMBZATwDc4AnKgG2gHMYqAHOauxlqOy49aDZmw7deYgUO4BKfAD5MpANwAdKCAA0ICJxgBLdMlABDevQgB3AAqWEaZCHM0IRgCa6QAI3rmYADWcDAAypyBRoLIMPQArnB6ABYwALZMAOrJRvBokWBwYU65RjS5VC5gaM560WgMMHYBrGnmyNjmTA16AFZoAB4AQgHBoWHmaXAAMtFwHV09IP0DYdGsTHAAivEQ8AvdSSCR9A30Lr7mvuLaepz00TCZXjDJyAAcAAx31g2ZAZwXPc4Gc6D4AI67eDNAzOFDmNAAWigcDgnjRPnocEhRixzXMrXaSE6hz0DTSRliCSOaHWmx2e3mxMWRxgV2enleyAATHo4uYjEx1gBhCBpNouEEAVh88QaABUrnCSQ0SCQgA)
```sh
--parser babylon
--trailing-comma es5
```

**Input:**
```jsx
const f = ({}: MyverylongtypeMyverylongtypeMyverylongtypeMyverylongtype) => {};

```

**Output:**
```jsx
const f = ({
  ,
}: MyverylongtypeMyverylongtypeMyverylongtypeMyverylongtype) => {};

```
Note that the above is invalid JavaScript/TypeScript!

**Second Output:**
```jsx
SyntaxError: Unexpected token (2:3)
  1 | const f = ({
> 2 |   ,
    |   ^
  3 | }: MyverylongtypeMyverylongtypeMyverylongtypeMyverylongtype) => {};
  4 | 
```

**Expected behavior:**
Either
```tsx
const f = ({
}: MyverylongtypeMyverylongtypeMyverylongtypeMyverylongtype) => {};

```
or maybe
```tsx
const f = (
  {}: MyverylongtypeMyverylongtypeMyverylongtypeMyverylongtype,
) => {};

```

**Comment by thorn0** [comment]
Must be related. Such empty patterns are formatted differently when type annotations are added:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFMAL4CU+ZAOlBlrgcWUvgGIQSVkgA0IEAA6MoAZ2SgAhgCdpEAO4AFGQnEpJANwg4AJnxAAjaZLABrODADKgkzigBzZDGno4-ABYwAtgBsA6u448KI2YHCWqkE4GkEAnsjgouL8dqJw0jCKxvZeksiokj5p-ABWogAeAELGZhaWkl5wADJ2cPmFxSBl5ZZ29j5wAIroEPDtRW4gNtJp0gmoPgr6gtJ2MH66MO7IABwADPwrEGl+xoIJK3CzGm38AI4j8FlCaiCSogC0UHBwOr-60jgDxwgKykhyeSQBQm-DSXhwThck1EfQGw1GbShHUmMEkBg2Oi2yAATPxnJIcD4+gBhCBeXIJKDQW4gdBpAAqeLU0LSpFIQA)
```sh
--parser flow
```

**Input:**
```jsx
function f({}) {}
function f({}: Foo) {}
```

**Output:**
```jsx
function f({}) {}
function f({  }: Foo) {}

```
