### ISSUE TITLE
Bad formatting for multiple concatenated shorthand if

### ISSUE THREAD

**Issue by lppedd** [prettier/prettier#6436]
This happens also in **Prettier 1.18**.  
I would expect the second shorthand-if options to be indented.

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOg5KAOQEMBbOAAgF4AdKChxh9bHMAVwCdOEYBleAAdqVKhRa4YEGMQA2AuIKx0mqigH4KAcjBo4YANZaVaxknGZcAEww8wMDNBFitgngDdH7LMfqmGmlpWEOwARrJwALQRAGYwvv4M5kEh4VGcGADmaPEA3CAANCAQgg7QWMigxNwQAO4ACtUIFSjE7hAYVoUgoZzEhnD8gv0YUJnIMJzscEU5pLIA6pjwWMNgcHzNGA6eMACeyOBYFUWjWHCcMPV9maTEyDFy50UAVlgAHgBCfQP8ZHAAGVGcAeTxmIDe7z4o0yEQAiuxpCCkI9ZM8QMNOOdOIdQsRQntZNBum5RjAFp10MgABwABiKbgg5wWfUEhzccGx7hBRR4AEd2LY4NdiLd7iiwUVzqQMBMpuCsDD4Yj4KC0eCZKEKVYqUgAExFSbEDCyGEAYQgpDuhyg0B5IG8cAAKviWqjzgBfD1AA)
```sh
--parser babylon
```

**Input:**
```javascript
this.iconName =
        this.currentStep === this.totalSteps
          ? 'check'
          : this.direction === 'previous'
          ? 'double-left'
          : 'double-right';
```

**Output:**
```javascript
this.iconName =
  this.currentStep === this.totalSteps
    ? "check"
    : this.direction === "previous"
    ? "double-left"
    : "double-right";

```

**Expected behavior:**
```javascript
this.iconName =
  this.currentStep === this.totalSteps
    ? "check"
    : this.direction === "previous"
      ? "double-left"
      : "double-right";
```
Or
```javascript
this.iconName =
  this.currentStep === this.totalSteps
    ? "check"
    : this.direction === "previous"
        ? "double-left"
        : "double-right";
```

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/issues/5814

**Comment by j-f1** [comment]
Duplicate of #5814
