### ISSUE TITLE
Loading configuration file from user's home if none found in project root ?

### ISSUE THREAD

**Issue by playahater** [prettier/prettier#6440]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI, vim-prettier
- Runtime: Node v12.9.1
- Operating System: Archlinux

**Steps to reproduce:**
- Remove local prettier configuration file from the project document root
- Place the configuration options in ~/.prettierrc [ user's home directory ]
- go to project document root
- run either of these:
prettier --config-precedence 'prefer-file' --write path/to/file
prettier --config-precedence 'file-override' --write path/to/file
prettier --write path/to/file

**Expected behavior:**
The configuration options should be loaded from the user's home directory and written to a file.

**Actual behavior:**
The configuration options are not loaded. Prettier default ones are used instead.

So i tried using vim-prettier [ which actually uses prettier config resolver ] and using cli outside of vim and got the same results.

Am I i doing something wrong or this feature is not supported anymore ? Or it never was ?
If i copy the configuration from user's home to a project root, everything works as expected.

Any feedback is more than appreciated in advance.

**Comment by keyboard-clacker** [comment]
I'm also getting this issue and would love to be able to have a global config that applies as the base default. @playahater did you ever find a solution to this?

**Comment by playahater** [comment]
@keyboard-clacker unfortunately not. Doing manual copy of the rc file in the project root.

**Comment by thorn0** [comment]
Prettier isn't going to support any kind of global configuration. See https://github.com/prettier/prettier/issues/8094#issuecomment-616444163
