### ISSUE TITLE
JavaScript: There is extra indentation on binary expression within call expression 

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#6442]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUAdKACPAIwEMAnPAMgtwJNNwEoBuEAGhAgAcYBLaAZ2SgypCAHcACmQSCUxAG4QeAEzYhCpYmADWcGAGVOWnlADmyGKQCucdgAsYAWwA2AdTs94-I2Dj6ZnjzyngCeyOD8guwm-HCkMBKapo7EyKjEzrHsAFb8AB4AQpo6evrEjnAAMiZwaRlZILl5+iamznAAilYQ8HWZtiBGpLGk4SSEcM5qnKKxrpqc4TNwI-K17ACO3fCJXLIgxPwAtFBwcMrnaqRwWzzXicTJqUjp-eyxjjwW1gP8re1dHq1F71AYwYiEVwqGB2ZAAJnYlmIPGcrQAwhBHClwlBoOsQFZYgAVCGyV4NGYmGBQ5Qw5AARgADABfZlAA.)
```sh
# Options (if any):
--print-witdh=10
```

**Input:**
```js
foo(
  bar &&
  bar
);
```

**Output:**
```js
foo(
  bar &&
    bar
);
```

**Expected behavior:**
```js
foo(
  bar &&
  bar
);
```

**Comment by thorn0** [comment]
It's not a bug. That indentation is added to make it clearly visible how many arguments the call has.

**Comment by sosukesuzuki** [comment]
@thorn0 Thanks, I'll close
