### ISSUE TITLE
Prettier for Clojure

### ISSUE THREAD

**Issue by gunar** [prettier/prettier#6448]
Would it be possible we get a version of prettier for Clojure files? i.e. `file.clj`

I LOVE Prettier. Thank you so much for this tool. I'm never again styling code manually.

**Comment by evilebottnawi** [comment]
Please use plugin for this purpose, thanks

**Comment by lydell** [comment]
Don’t we all want formatters for all languages these days? :)

This won’t be added in Prettier core, but it would be a good fit for a [plugin](https://prettier.io/docs/en/plugins.html)! Feel free to start working on one and ask for help as needed, or convince someone in the Clojure community to start working on one!
