### ISSUE TITLE
How to enable convert empty JSX elements to self-closing elements

### ISSUE THREAD

**Issue by dhmacs** [prettier/prettier#6452]
After version `1.18` Prettier does not merge empty tags anymore (https://github.com/prettier/prettier/pull/6127)

Is there an option to turn this back on? This option is cluttering the code and it's very annoying to manually merge empty tags.

**Comment by evilebottnawi** [comment]
It is expected and no options for this and we don't plan to add option

**Comment by macs91** [comment]
So there's no solution for this? Everybody is just merging empty tags manually? 🤔

**Comment by evilebottnawi** [comment]
You can setup linter for this case

**Comment by macs91** [comment]
I think I'll stick with `1.17` an hope you'll change your mind along the way 😅

**Comment by evilebottnawi** [comment]
I don't recommend stick because we fix a lot of bugs, use linter for this case

**Comment by lydell** [comment]
@macs91 You can use the [react/self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/97a9f397d2a8a3ce3b2af893bdbb86bb2c1d4480/docs/rules/self-closing-comp.md) ESLint rule. It has autofix! Have you tried it? Does that work for you?

**Comment by macs91** [comment]
Thanks for the suggestion @lydell ! 
When we migrated to typescript we found eslint didn't bring value to our development process so we removed it from our toolchain. Adding it back just to fulfill this single purpose does not seem to be worth it (and if I'm not mistaken eslint generates warnings with fix suggestions that need to be manually applied to take effect and since we generally have lot of empty tags that would be an annoying process). 
We've been working happily with `v1.17` so we decided that for now we'll stick to this version.

**Comment by thorn0** [comment]
> we generally have lot of empty tags

Lot? Where do you get them from, I wonder? Are you converting HTML to JSX using Prettier?

**Comment by icyJoseph** [comment]
So users of create react app will have to wait for self-closing-comp to be implemented upstream?

**Comment by evilebottnawi** [comment]
> we found eslint didn't bring value to our development process so we removed it from our toolchain

:confused:

**Comment by thorn0** [comment]
@icyJoseph if I get what you mean, you've missed the fact that now CRA [allows to extend the ESLint config](https://create-react-app.dev/docs/setting-up-your-editor#experimental-extending-the-eslint-config).

**Comment by icyJoseph** [comment]
Aha! I tend to leave things labelled experimental out of my sight. Thanks! Good stuff @thorn0.

**Comment by macs91** [comment]
@thorn0 
> Lot? Where do you get them from, I wonder? 
I'm building dashboards.. Many JSX components are just empty tags (e.g. icons, form controls, components which abstracts parts of the UI like resource lists and stuff like that)

> Are you converting HTML to JSX using Prettier?
What do you mean?

**Comment by thorn0** [comment]
I mean why do you type them as empty tags in the first place?

**Comment by macs91** [comment]
I use emmet.. If you type `ResourceList` and hit tab you get
```jsx
<ResourceList></ResourceList>
```
In vscode usually I just type a few letters (e.g. `Res`), take the first autocompletion and create the tag with emmet

**Comment by thorn0** [comment]
~~What's the point in using Emmet in this case? Adding the closing tag, which you don't need anyway and which VS Code adds anyway when you type `>` (not `/>`)?~~

Okay, never mind. Clearly it's just a habit, and you feel really strongly about it. (But somehow not strongly enough to use ESLint...) I had this habit too, but it was outweighed by the annoyance of #5442, and now I think changing the behavior of Prettier was the right thing to do.

**Comment by macs91** [comment]
I proposed to my team to use prettier and not discuss formatting anymore ("whatever prettier does") so clearly I don't have strong opinions on this.
It's just a matter of time. We've spent too much time on configuring tools and fix conflicts between them that we think twice before adding more tools to our development process 🤷‍♂

>  it was outweighed by the annoyance of #5442

Yep, I totally see why you changed this, and I don't object it.. I just think both ways have pros and cons and we're used to the old behavior. After a few days using `v1.18` we're really missing the auto merge 😅 

Anyway I don't want to waste to much of your time, thank you for the suggestions 👍

**Comment by dannycarrera** [comment]
For @macs91 and anyone else looking to keep the old behaviour and to expand on the answers of @lydell  and @thorn0.

Simply create a .`eslintrc.json` file in the root of your project.
Add the following code:
```
{
  "extends": ["react-app"],
  "rules": {
    "react/self-closing-comp": [
      "error",
      {
        "component": true,
        "html": true
      }
    ]
  }
}
```

This worked for me with VSCode, Prettier and CRA 3.0.0 .

**Comment by amanolar94** [comment]
@dannycarrera Does it autofix for you? Because the docs say that this issue is auto-fixable but when using it, it says that it is not autofixable

**Comment by dannycarrera** [comment]
@amanolar94 Autofix works for me.

**Comment by gargrave** [comment]
I have to agree with @macs91's frustration here. If you change default behavior like this, at least give us an option to continue using the previous behavior, so we can maintain consistency in an existing codebase.

Yes, I know ESLint can do this for us as well, but the reason we are using Prettier in the first place is so we don't have to rely on _other_ formatting tools. (ESLint's auto-fix behavior can be pretty flaky at times anyway.)

**Comment by ScottAgirs** [comment]
I too think, it's quite simple: **There should be an option to choose from.**

Some may dislike it, however, clearly there are those who like it just as much, myself included. 
For a while I thought something's just broken, but didn't have time to investigate - and I'm sure I'm not alone in this boat either.
Quite surprised that a package of this popularity is changing such fundamental things so abruptly 🙂

**Comment by macs91** [comment]
@ScottAgirs Agreed. I had the same feeling that something was broken... Right now we're sticking to `v1.17`

**Comment by jonlambert** [comment]
I too thought this was a broken part of my configuration. It's a bit worrying that this functionality was removed so quickly and without any way to configure it. FWIW I will be sticking to `v1.17` until either this decision is reverted or our team find a better tool for the job. Unfortunately abrupt changes like this are a quick way to lose faith in a tool.

**Comment by jeanfortheweb** [comment]
Same here, sticking with 1.17 until it's configurable or whatever. I really loved that feature

**Comment by nanxiaobei** [comment]
Need an option 😭

**Comment by PenguenUmut** [comment]
People usually doesn't use autofix for linter rules but use autofix for formater rules when file saving.

Needs this option.

**Comment by yanivfranco** [comment]
Here to keep up this issue! 
Option in the prettier settings which will determine "auto-self-close-empty-tags " : true/false

**Comment by armano2** [comment]
as for emmet you should read: https://github.com/emmetio/emmet/issues/413

> Upcoming v2 support elem/ syntax to output self-closing elements

**Comment by jscul** [comment]
So this is why this feature stopped working... ugh. It was so nice to have auto-closing tags. I spent the last couple months wondering what happened. Please allow us to opt-in to auto-closing tags!!!

**Comment by mix4242** [comment]
Strongly support adding an option to enable/disable this feature. Clearly people are missing this functionality!

**Comment by good3n** [comment]
This is an absurd response by the Prettier team.

**Comment by thorn0** [comment]
This is a job for ESLint.

**Comment by DrianHillman** [comment]
This was driving me nuts too, and the eslint rule alone didn't help. 

My only workaround & suggestion is to turn on **AutoFixOnSave** in your editor and it'll fix this for you as prettier once did.

As mentioned in ESLint's VSCode extension—

vscode settings.json:
```json
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": true
},
```
