### ISSUE TITLE
CSS tag name lowercasing breaking styled components in Expo app

### ISSUE THREAD

**Issue by Stephen2** [prettier/prettier#6454]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcYBPAGzgBN8AzHCdfAHRGPKoFpItoEZCA9FACGMVADc4LANxMocuAA9sefJCjF8AMQgR8AXiKkKlAHQBJdMIDmcAAZz8+AEa5KcHAHVUlGAAskfAAWTEVZKAcoEAAaEAhMMWhCZFBhHHoAdwAFNIRklGFxCB8YkGccYTAAazgYAGVMStQoa2QYHABXOFi-GHQyTz9UeEJGsDg6vOGJYZJkcEJk2ObCDxgsiusrZBphMlXYgCtCRQAhCurauuF0OAAZZrgdvYOQY8U65usKAEUOiHgz323RAjRwqxw82cwmc5GgpUwOGaMG8vj8yAAHAAGWKIiCrTwVTDzRFwCGSUoAR3+8A28XyIGEhA4UDgVCopRwcGpqC5Gxs2yQu2BsVW6FQbU6IMIX1+NKeQpeIJgMNR-mQACZYu1hKgyF8AMIMQUgKC8UodVYAFRh+WFqwAvg6gA)
```sh
--parser babylon
```

**Input:**
```jsx
import styled from "styled-components/native";

export const Foo = styled.Image`
  borderWidth: 4px;
`

```

**Output:**
```jsx
import styled from "styled-components/native";

export const Foo = styled.Image`
  borderwidth: 4px;
`;

```

**Expected behavior:**
It shouldn't touch this string, error reads `Invariant violation: "borderwidth" is not a valid style property.`

**Comment by Stephen2** [comment]
CANCEL... I inherited bad code and didn't understand that styled components uses `kebab-case` for everything 🤦‍♂

**Comment by jsunwoo** [comment]
I have a same issue, how could you solve it?

**Comment by jsunwoo** [comment]
Thank you!
