### ISSUE TITLE
Custom yaml parser

### ISSUE THREAD

**Issue by mquandalle** [prettier/prettier#6458]
I'm trying to modify the AST of the `yaml` compiler, but the API documented [here](https://prettier.io/docs/en/api.html#custom-parser-api) isn't working even if I keep the AST untouched.

**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: Node.js API
- Runtime: Node.js 12.10
- Operating System: Windows 10

**Steps to reproduce:**

```js
const prettier = require('prettier')

const input = `
- hello
- world
`

const output = prettier.format(input, {
	parser(text, { yaml }) {
		const ast = yaml(text)
		return ast
	}
})

console.log(output)
```

**Expected behavior:**
It should return the input unchanged:
```yaml
- hello
- world
```

**Actual behavior:**
```
      throw new Error("unknown type: " + JSON.stringify(n.type));
      ^

Error: unknown type: "root"
```

**Comment by evilebottnawi** [comment]
What is parser you are use? We can't have compatibility with other yarn parsers

**Comment by mquandalle** [comment]
@evilebottnawi I'm following https://prettier.io/docs/en/api.html#custom-parser-api. Currently my code above doesn't do anything it just import the `yaml` parser from `prettier` and re-export it untouched. This code is working if you use any other base parser such as `babel`, but not with `yaml`.

**Comment by evilebottnawi** [comment]
@mquandalle yes, but you need modify printer too if you parser provide other nodes

**Comment by mquandalle** [comment]
Here is a code sandbox https://codesandbox.io/s/optimistic-dan-c1wpn

**Comment by mquandalle** [comment]
How can I tell `prettier.format()` to use the standard `yaml` printer?

**Comment by mquandalle** [comment]
@evilebottnawi Yes the problem still exists, the minimal reproduction in the codesandbox : https://codesandbox.io/s/optimistic-dan-c1wpn

**Comment by mquandalle** [comment]
The issue is here : https://github.com/prettier/prettier/blob/32dd447271db23b6d51f28f7053c7f9ebae46e56/src/main/parser.js#L31-L38

**Comment by thorn0** [comment]
@mquandalle [This workaround](https://github.com/prettier/prettier/issues/3150#issuecomment-394150810) might help you.

**Comment by thorn0** [comment]
duplicate of #3150
