### ISSUE TITLE
Webstorm watcher - file missing from workspace after first write

### ISSUE THREAD

**Issue by mrt123** [prettier/prettier#6459]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI
- Runtime: Node v12.10.0
- Operating System: macOS

**Steps to reproduce:**
Define watcher in Wbestorm 1.0.5 ( I realize this is an old version, however it's the latest supported on my license :
<img width="738" alt="Screen Shot 2019-09-09 at 16 37 09" src="https://user-images.githubusercontent.com/7832490/64548290-a1eb0080-d32e-11e9-82af-4343f9da3527.png">

**Expected behavior:**
Each file change in src/App.js triggers prettify
**Actual behavior:**
First file change in src/App.js triggers prettify, subsequent changes do not. Also App.js disappears from project Pane, while physically file stays in the same location. 

In order to restore file into project pane, invalidating cache and restart of Webstorm is required. Most likely the way the file is written the first time removes it from the index. 

Running from CLI : ```npx prettier  --write src/App.js``` does not suffer same issue, however running ```npx prettier  --write src/*.js``` reproduces the issue.

**Comment by mrt123** [comment]
I was able to fix it by changing to this:
<img width="316" alt="Screen Shot 2019-09-09 at 19 00 20" src="https://user-images.githubusercontent.com/7832490/64550908-34da6980-d334-11e9-8de5-1bc687fa27ed.png">
However this is against docs: https://prettier.io/docs/en/webstorm.html
It does specifically mention ```For older IDE versions, please follow the instructions below.```

**Comment by evilebottnawi** [comment]
Some version of `File Watcher` is very buggy, maybe it can be fixed on old versions
