### ISSUE TITLE
Prettier adding newline before closing bracket, only on certain elements (e.g. Label)

### ISSUE THREAD

**Issue by toddhd** [prettier/prettier#6460]
Standard HTML (not embedded in JSX for example, just a regular *.html file) is adding a line before the closing brackets only on certain elements. In this case, my <label> elements. All other elements on the page are formatted correctly.  I am using HTML and Angular code, NOT React. In the Prettier options (in VS Code) I have "Prettier: Jsx Bracket Same Line" checked. I do not see any bracket options for non-jsx code.  

```
<div class="col-sm-4">...</div>
<label
    >Enter the distance in feet below, rounding to the nearest whole
    number.<span style="color: red">*</span></label
  >
```

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue will be closed, thanks

**Comment by toddhd** [comment]
**Prettier 1.18.2**

**Environment**
IDE: VS Code v1.38.0
Mac OSX: v10.14.6 Mojave

**Issue Description **
Standard HTML (not embedded in JSX for example, just a regular *.html file) is adding a line before the closing brackets only on certain elements. In this case, my elements. All other elements on the page are formatted correctly. I am using HTML and Angular code, NOT React. In the Prettier options (in VS Code) I have "Prettier: Jsx Bracket Same Line" checked. I do not see any bracket options for non-jsx code.

**Input:**
```
<div class="col-sm-4">...</div>
<label>Enter the distance in feet below, rounding to the nearest whole
    number.<span style="color: red">*</span></label>
```

**Output:**
```<div class="col-sm-4">...</div>
<label
    >Enter the distance in feet below, rounding to the nearest whole
    number.<span style="color: red">*</span></label
  >
```

**Expected behavior:**
<div class="col-sm-4">...</div>
<label>Enter the distance in feet below, rounding to the nearest whole
    number.
  <span style="color: red">*</span>
</label>

**Comment by lydell** [comment]
That's how Prettier formats HTML by default. See https://github.com/prettier/prettier/issues/5377#issuecomment-524172346

You might also find the [html-whitespace-sensitivit](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option interesting.

**Comment by toddhd** [comment]
lydell,

I don't think that's correct. Here is the HTML I just formatted using Prettier. The bracket spacing is NOT consistent. Most of the brackets are on the same line, but the SPAN tag is not. If that's how Prettier formats HTML then I would think it would be all one way or the other, not a mixed bag of bracket breaks. 
```

<div class="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h2>Disclaimer</h2>
    </div>
    <div class="col-sm-4">
      <ngb-progressbar type="success" [value]="25"></ngb-progressbar>
    </div>
  </div>
</div>
<div class="content">
  <h3>
    Please read and acknowledge the disclaimer below.<span style="color: red;"
      >*</span
    >
  </h3>
</div>
<div class="page-nav">
  <div class="row">
    <div class="col-sm-6" style="text-align: left">
      &lt; <a [routerLink]="['/project-status']">Back</a>
    </div>
    <div class="col-sm-6" style="text-align: right">
      <button class="btn btn-primary" [routerLink]="['/outdoor-nga']">
        Next
      </button>
    </div>
  </div>
</div>

```

**Comment by toddhd** [comment]
Also, thank you for the info on the whitespace. I don't think this is the issue at hand, because I code on a Mac, and more importantly, I am the only person coding right now. The SPAN tag in question above was actually just added by me by hand before formatting. In other words, it wasn't a "cut and paste" that might have had a different line-ending in it. They should all be standard.

What confuses me is that I haven't seen this problem with Prettier before. It has always formatted perfectly for me.

**Comment by lydell** [comment]
- Can you post what your expected output of the code in your previous comment?
- Why are you talking about Mac and line breaks? As far as I know that has nothing to do with HTML formatting.
- You haven't seen this before? Before what? I don't think we've ever made major changes to the HTML formatting.

**Comment by thorn0** [comment]
I reproduced what @toddhd wrote, but there is nothing wrong with it. If a whitespace between the dot and the star is needed, it should be added manually. If Prettier added it unsolicitedly, it would affect how the page is rendered.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOuBAQLQkC2dALNQHwB03qA9FtnaUoqYgCM4BdgFFYcAE64YACzi4sJGEShg1mKLgBmcODFwSCEAO4AaXPIgBXKFigBzJRCWrcUOEXk4TVwrZVo4YVwo30dGCXlOVBIAB21cTQBPAjgqGkt5JHs4dA4AKj4U7XY+cUl2EBsQCGSYTGgSZFAAhysABQCEDpQibAhMdAaQMXkiMABrUwBlVLB9N2QYeUc4RuUYRgIAdWVMeErdRcHTnFOM5HAySf0SBRhembdGImRDIgIXxoAKxIAA8AEIzeZLIiMOAAGX0cB+fwBIGBIMWa2yAEVHBB4Mj-jsQKl5C95Pc9gdJsl5PoYIdxipkAB2AAMjVpEBehxmyXutKCCmwSMaAEc8fB3s0hiBSHQ-MVipNAhLMIF3kRPt8kL8iY0XoxMBstsSSFi4Lj8UjdSjiVoxIz0MykAAmRqbIiYAhrADCEEYX3uUGgopAjheABUiGIhnqXgBfBNAA)
```sh
--parser html
--print-width 70
```

**Input:**
```html
<div class="col-sm-4">...</div>
<label>Enter the distance in feet below, rounding to the nearest whole
    number.<span style="color: red">*</span></label>
```

**Output:**
```html
<div class="col-sm-4">...</div>
<label
  >Enter the distance in feet below, rounding to the nearest whole
  number.<span style="color: red">*</span></label
>

```

**Comment by rooby** [comment]
I'm seeing this too.
There are a couple of examples at this [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAy5u3AQQDKQgLxMQUCAFoAVgGdyNQtNx0B8oROZRy5dqQGYdevak6l8AvmwEAlIZfEgArjABm0gBzaWp-fgAkvjcpAycAJ7kMMF0pKgA9EEhYX6m5pbWAHICFs4AJnDyYABOAJYADjBl0BLkkLAIMM6RfBBZMKRQ+L66+glshsZpqABGEPkRJunEDGxwdHQQ5ADuECV0+eioAEJ2DOT4lGWKJ+QcPACs5DsQZXRwJRV0AIbwAHSJs2lmQrh2gWI+Gm-hWZSg+QgK3eAHMXuRROR3C4oGBqtByAAKACU5GA5Dh7wAju8Ki55JRMS8SjCXDQmvJcQBfADcBJexIR5AA2gBdNmEuhcgDUUDgK3ImDecBZP1McMxAHJSnBpYqADTkRUAVQE0gAGobDdJCBqtS83BBFdiBS8lfIEPkzYqKi8YXAAG5lcXWuWJP4AoEg-QBwH4cjyEpgZzUGAVeRIBIJFYp2EQCAwh7SF5QF50CLVMDyd6QGgJHN5gtlIvvBR1YSELK4SWkABipH2-v+YeDcrMFWD-lQ8ldUAY8Hk1SgMOHo-HRSnMOiC+Xk9XMHXm4nG+36-BM4SI5zDESR7Hff6A4vF9QV76-jMZ8HD9nx+HMBK0Bhc0ecHIZ3kCB6WXAAPHdKDef9FCWadyAQCAXBhShomWGgXgAaz-GBKD-OhwT-Ec8I3CAPUeJQXDoapnlw-D5FPD8vxPUYSnIBIT0POcLwfcghCAv8aHWLC4DArj+ifG8EjvMwEnGSYdESC5uAYEB1RACAqhqKB5GQUBqU-FZiGpBBtJQF4PTufIVJAZiXjATCYCEV0wH3ZAPxcOBVOoegAHVjgnJy4CEYyymqL0YAiZBwHkbTVPBB0ShgYgSjdNDkHcPMHVUhQQJ2ZK7LgByXnpbh8LSjKPJAbKhH3B4AEUXAgeAyroTKQFdEp4siry6CsipylgbyynybDkC8AAGVS+ogB1vOSipIr6opHlIqyiQa+AkvUkyQBeeRpDFOBCks1SSjgNaylOpKUpeZrWodGgylckp3NU+QargerGrgW6KpgF5RkG4bKGQAAmVSPxee591wIDUpQKQxSs8k4Hwf6TPSlq4CZJkgA). If lines are short it's fine but when it has to start splitting long lines up it starts breaking elements at strange places.

For example:

I would expect 
```
      <p>
        <span>
          <span><strong>Here is some text that is long enough to make the line split over multiple lines</strong><br /></span>
            Some more text
        </span>
      </p>
```
to be something more like 

```
      <p>
        <span><span><strong>Here is some text that is long enough to make the line split over multiple lines</strong><br />
        </span>Some more text</span>
      </p>
```

instead of

```
    <p>
      <span
        ><span
          ><strong
            >Here is some text that is long enough to make the line split over
            multiple lines</strong
          ><br /></span
        >Some more text</span
      >
    </p>
```
Also, (I'll open a separate issue for this), it shouldn't be adding line breaks around inline tags like span and strong because that can change the content the user sees, which is more serious.

**Comment by rooby** [comment]
Ah, this is mentioned in #6401 as intended behaviour to work around the issue I mentioned at the end of my last comment, about unintentionally adding whitespace to inline elements.

So it is by design, but IMO it's extremely unpleasant on the eye and looks like broken code at a glance.

**Comment by lydell** [comment]
Yes, HTML (the language) is broken IMO :)

**Comment by rooby** [comment]
Yeah it makes things tricky.
Seems I didn't read the previous comments thoroughly enough haha. The info [here ](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting)explains it well.

**Comment by rooby** [comment]
@toddhd have you recently updated your version of prettier? If you were previously using an older version it might explain the sudden change of behaviour.

**Comment by radiantone** [comment]
Is there a workaround or way to "unset" this "by design" terrible formatting? Having a single ">" floating by itself on a new line is probably the worst intentional design decision I've seen.

**Comment by Timmmm** [comment]
I agree. Prettier seems to love putting single angle brackets on their own. I can see how it might make sense in cases like this:

**Comment by Timmmm** [comment]
Hmm seems like [someone is working on a fix](https://github.com/prettier/prettier/issues/5377#issuecomment-678644985).

**Comment by radiantone** [comment]
This behavior of putting carriage return before end brackets > in HTML is the dumbest looking thing I ever seen.

**Comment by vkorsakov** [comment]
so no solution for this issue in 2021 huh?

**Comment by DARTzz** [comment]
I still could not make out why such orientation of angular bracket is needed. Can anyone refer a resource or explain since the topic is up :)

**Comment by Timmmm** [comment]
The reason is because in general whitespace in elements is significant, so Prettier does the safe thing and preserves it. That help text should say "significant" where it says "sensitive".

The CSS option tries to figure out cases where it actually isn't significant, but it can't really do it 100% reliably - that would be impossible.

**Comment by radiantone** [comment]
> The reason is because in general whitespace in elements is significant, so Prettier does the safe thing and preserves it. That help text should say "significant" where it says "sensitive".
> 
> The CSS option tries to figure out cases where it actually isn't significant, but it can't really do it 100% reliably - that would be impossible.

That's not a good reason really. Having a bracket on a line by itself extends the libes of a file, breaks convention and reduces human readability. All around a bad programming decision.

**Comment by Timmmm** [comment]
> That's not a good reason really.

It's an extremely good reason. An auto-formatter should not change the behaviour of code by default. That would be insane.

You can opt in to the risky but pretty behaviour if you prefer it.

**Comment by HDaghash** [comment]
Using the new option `bracketSameLine:true` 

solve the issue, just make sure to update the latest version of prettier.
