### ISSUE TITLE
[JS] named import with one import violates printWidth

### ISSUE THREAD

**Issue by zieka** [prettier/prettier#6462]
### Background

When adding a line that has a named import with one import that exceeds the printWidth (140 in the case below) prettier will not break the import statement into multiple lines.  Only when a second named import is added will prettier break the statement into multiple lines.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwGcJ04YALVKAc3wF98AzHM-AcgDouB6AQ0yZekLNAQxivUuQC0ANzg4AnrIA20WrKj9yAE1lUaWqvxizaEOMVnNccRTmlk4Cpao11tuuAaNfTc0trW3tHLlFsKAkOAG4AHShExIxsPEISF39aABpM8my4NWI4RhY2dE4eASERMiiJKRlXRw9Nb31DagDKMwsrGzscByVnOVb1dp1O7K6+4MGwpQj68Vg4kByQCEwYVGhiZFB+HDYAdwAFE4RDlH55CFQ9TZAAIxx+MABrCgBlTE+xmQMBwAFc4FtKDB0GoAOrUeDEAFgOC-G6oPbyDHKZDgYiHLY0Ep4C4fWjofjIZj8YoQkAAK2IAA8AEIfb5-HwAGRocCpNJKW0ZTN+xjUcAAiqCIPB+bStgCcMTca9+K9lJ4XpgcDQYLCnlRkABGAAsAAYFWwSrCPphcdrrEpFC8AI7S+Ckna3ED8GzRXy+F7DN2oYak-jkylIanykAldCoYFgunEMWS9186MCukwNX6vSGpAAJi2IP4qDUxgAwmQKbioOIXqCSgAVNW3GMlBgMIA)
```sh
--parser babylon
--print-width 140
```

**Input:**
```jsx
import { something } from '../app/components/some-very-long-named-thing-that-goes-forever/some-very-long-named-thing-that-goes-forever.component';


import { something, somethingelse } from '../app/components/some-very-long-named-thing-that-goes-forever/some-very-long-named-thing-that-goes-forever.component';
```

**Output:**
```jsx
import { something } from "../app/components/some-very-long-named-thing-that-goes-forever/some-very-long-named-thing-that-goes-forever.component";

import {
  something,
  somethingelse
} from "../app/components/some-very-long-named-thing-that-goes-forever/some-very-long-named-thing-that-goes-forever.component";

```

**Expected behavior:**
```jsx
import {
  something
} from "../app/components/some-very-long-named-thing-that-goes-forever/some-very-long-named-thing-that-goes-forever.component";

import {
  something,
  somethingelse
} from "../app/components/some-very-long-named-thing-that-goes-forever/some-very-long-named-thing-that-goes-forever.component";
```

**Comment by evilebottnawi** [comment]
It is expected (https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L1009), but only for one import for better readability

**Comment by lydell** [comment]
Hi! As, @evilebottnawi mentioned this is intended. printWidth is not a hard rule in Prettier, but a general guidance for its algorithm. Prettier can produce both shorter and longer lines. Please se #1954 and the issues that link to it.
