### ISSUE TITLE
Large names in certain cases cause ridiculous indentation

### ISSUE THREAD

**Issue by DMon19** [prettier/prettier#6466]
I can't describe exactly what happening here, but it looks like it's trying to align the start of the last parameter with the opening parenthesis of the function (this is more obvious in VSCode),
leaving a really quite excessive spacing between the comma and the last property.

I've found this specific layout of code useful when referencing denounce functions.
As this problem is difficult to put into words, I've not been able to find anyone else having this exact problem.
Is this intended behaviour, or just an unfortunate edge case?

~~Prettier v2.2.2~~ VSCode Prettier plugin version 2.2.0 (Prettier version 1.18+ assumed)
Issue is NOT happening in the playground as it does in my VSCode:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB3AFggKuglgZwEl8AZaAcwE0IBXAUSgBMBVABwHVcZ0cCACALx98cGFlwBbOLRgAKWQEpBAPj7AAOlD7a+Ael19e+PmACGNEcdYAnUTFxxrfGBD4TTAazh9TfAGamuNYANgCefLaMuGA0wbTGuLAIjKb20AB0mZoAvgA0fADMAAxFCgDcILkgEKxpUPjIoKbW1hCoAArNCA0opgBuELiMlSAARtamYF4wAMqsk4nkyDDWNHBV6DASwex48PjzYHAz3Vy4fVyhyOD4DVWJItYw7RPk7sgBwSJVAFb4AB4AIQmU1EM1MUhIiTgH1MX3WID+-xmi2CcAAijQIPBYfCqvNrI9rqNTKNQnEoCMbIkYJxGNxkAAOIr41oidgTVjXGxwR59GFVACOWPgLxqPRApnwAFooHA4IwFSNbMKgnAXqY3qZcd8QCIJLhlqsEfhURiRTCkJ9dTBSXSGUgAExVFaBYKLADCEAk7xQUGgApAFjgWFJPWtcGy2SAA

**Input:**
```jsx
  whenThisIsLongYouEndUpWithThis = setTimeout(() => {
    // This causes prettier to make a fairly rediculous intendation...
  }, 300);
```

**Output:**
```jsx
  whenThisIsLongYouEndUpWithThis = setTimeout(() => {
    // This causes prettier to make a fairly rediculous intendation...
  },                                                  300);
```

**Expected behavior:**
Not adding a huge indentation between 300 and the comma preceding it.

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue will be close

**Comment by DMon19** [comment]
> Please use issue template otherwise issue will be close

Woops, updated

**Comment by evilebottnawi** [comment]
Prettier v2.2.2? We don't have this version.

Maybe bug in VSCode plugin.

**Comment by DMon19** [comment]
> Prettier v2.2.2? We don't have this version.
> 
> Maybe bug in VSCode plugin.

Ok I see, so the plugin version doesn't match the Prettier version.
VSCode "Prettier - Code formatter" plugin version 2.2.0.
The last changelog (in VSCode Plugin version 1.10.0) mentions the update to Prettier v1.18.

**Comment by evilebottnawi** [comment]
Do you use latest plugin? Can you provide more information? Maybe screencast or something else, looks like bug in VSCode. not in prettier, because i can't reproduce

**Comment by DMon19** [comment]
Disabling prettier removes this behaviour, so it's definitely a behaviour
introduced by prettier. Im also using the tslint option, might this be
related?

**Comment by evilebottnawi** [comment]
I can't reproduce using pure prettier, so problem not in prettier
