### ISSUE TITLE
trailing comma not working for import function

### ISSUE THREAD

**Issue by mrksbnch** [prettier/prettier#6478]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEUIBUBOAhgJYA2xUA5gMIQC2dhmAvJgBQCULAfADpSZMxOgAcI+GG36DBAegBUmAO5wARiMJgA1tQAWAVyhaAcoTpwkmXiBwES5KrQaFrmebMwByAHTfZGmF1ZGAhZADMyOFldOHwoqDM4bwArNE9pTA4Abn5+SCgMTBgiMgoaekYWdi5mPgFMCEDYgDFDMBhiaCl6uUUVdU0dAyNTc0trYvsyp0ZXdy9ff0JA4NCI0iiYuNkE8xS0jOyQABoQCBEO9GRQQnx8CCUABVuENGQQQgA3CGIAExOQKoiNo4DAAMoaMBlZDFfRwU66GB0UgAdV0xHgaEhcDBrwxxE+GIAnu8wGg3qcKGhYjBHkRKIxkGFCKRqadUgAPABCwK0oLBiQAMhQ4EyWWyQJywWUNgBFfSNUVIZms+EgDT4an4d6qQiqImkaAAkT4CgwFF-QLIAAcAAZTiaINSUUQRO8TXAtZ9RacAI4K+B085vFCENAAWigcDgvxjALi-uIcTphAZhDFqtO1LoxBh+DhWZlcHlirzBZAMD1Ft+VqQACZTpNSo4KunQ6RSAD9NTcHqQyrqQBfQdAA)
```sh
# Options (if any):
--trailing-comma all
```

**Input:**
```jsx
const noTrailingComma = () =>
  import(
    /* webpackChunkName: "noTrailingComma" */ '../path/to/file/here/name.js'
  );

const trailingComma = () =>
  otherFunction(
    /* webpackChunkName: "trailingComma" */ '../path/to/file/here/name.js'
  );
```

**Output:**
```jsx
const noTrailingComma = () =>
  import(
    /* webpackChunkName: "noTrailingComma" */ '../path/to/file/here/name.js'
  );

const trailingComma = () =>
  otherFunction(
    /* webpackChunkName: "trailingComma" */ '../path/to/file/here/name.js',
  );
```

**Expected behavior:**

A trailing comma is added to both functions. 

**Actual behavior:**

A trailing comma is not added to the `import` function.

**Comment by sosukesuzuki** [comment]
latest babel parser disallow trailing comma for dynamic import.  (by https://github.com/babel/babel/pull/9313 )

[Babel Try it Out](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgFAIgHQHoBmEJIFYGcEA0AlEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-3&prettier=false&targets=&version=7.6.0&externalPlugins=)

```js
import("./foo.js",)
```
```
/repl: Trailing comma is disallowed inside import(...) arguments (1:18)
> 1 | import("./foo.js",)
    |                   ^
```

**Comment by bakkot** [comment]
Yeah, trailing commas are [not legal in `import()` expressions](https://tc39.es/ecma262/#prod-ImportCall), so Prettier can't put one there.
