### ISSUE TITLE
Re-indent comments

### ISSUE THREAD

**Issue by fingermark** [prettier/prettier#648]
As requested in #639, I'm opening up a separate ticket for [comments incorrectly being indented]

```js
function theFunction2(action$, store) {
    /*
     * comments
     */
	return true;
    /*
     * comments
     */
}
```

turns into

```js
function theFunction2(action$, store) {
  /*
     * comments
     */
  return true;
  /*
     * comments
     */
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20theFunction2(action%24%2C%20store)%20%7B%5Cn%20%20%20%20%2F*%5Cn%20%20%20%20%20*%20comments%5Cn%20%20%20%20%20*%2F%5Cn%5Ctreturn%20true%3B%5Cn%20%20%20%20%2F*%5Cn%20%20%20%20%20*%20comments%5Cn%20%20%20%20%20*%2F%5Cn%7D%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by ls-guillaume-lambert** [comment]
Haven't looked at the code but is this something fairly easy to fix? I'd be willing to give it a try but never worked with AST before 😉

**Comment by darahak** [comment]
Is there a simple way to get the new start location for a comment block after a print?
It could be used to re-align all the comment lines.

**Comment by jlongster** [comment]
@darahak No, you don't want to rely on the output of the printer.

It seems like it's printing each line of the comment with the current indentation, but I looked at the code and it shouldn't be doing that. That's weird. You should start [here](https://github.com/prettier/prettier/blob/master/src/comments.js#L685) which is where we print block comments. See how we just print the raw value? Try to figure out why it has extra indentation; see `node.value` and make sure it's correct. Then look around [here](https://github.com/prettier/prettier/blob/master/src/comments.js#L734) which is where it prints the first comment.

Thanks for the bug!

**Comment by darahak** [comment]
@jlongster Thanks for the pointers! I started working on it.

**Comment by darahak** [comment]
Update: I'm having good results on regular use cases, but I broke several tests.
I just need to converge on that.

**Comment by starwed** [comment]
Not sure if it's useful, but when I tried out prettier, [this file](https://github.com/craftyjs/Crafty/blob/f26e5dab29a2dd72cf1b2a0b4ba7b725d9b89df6/src/spatial/spatial-grid.js) resulted in especially bad indentation.  (Perhaps because the initial version is indented in an unusual/incorrect way?)

The result looks like this:
```
HashMap.prototype = {
  /**@
         * #Crafty.map.insert
         * @comp Crafty.map
         * @kind Method
```

**Comment by DanielMSchmidt** [comment]
@darahak Hey, Thanks for your great work on this! I was wondering if you might consider adding a test case for comments that end in the same line as another expression (e.g. functions) start? When generating code with Babel this is actually the case and it would help me a lot (see #2340) thank you so much 👍

**Comment by darahak** [comment]
I'm sorry, I didn't work on this since my last message.
I don't have a lot of free time these days, so if someone else wants to give it a try, go ahead.

**Comment by DanielMSchmidt** [comment]
Thanks for answering. Is there an open PR I could extend?

**Comment by darahak** [comment]
No, I didn't get to that point.
All I did was split comment blocks and print each line separately while trying to take care of alignments.

It worked with simple cases similar to OP, but many tests were broken and I didn't get to look into that.
I guess there are many cases I didn't take into account.

**Comment by maxdeviant** [comment]
@DanielMSchmidt I've started looking at this in #2470.

Still trying to get a feel for where things are happening.

I've tried a couple of things to remove the unnecessary indentation as @jlongster suggested, but that usually ends up in a bunch of other comment tests breaking :sweat_smile:

**Comment by maxdeviant** [comment]
Okay, got it down to just one failing test now :+1:

**Comment by DanielMSchmidt** [comment]
@maxdeviant do you have a link to the branch, would love to take a look. Tried it on my own, but failed :(

**Comment by maxdeviant** [comment]
@DanielMSchmidt The branch is [here](https://github.com/maxdeviant/prettier/tree/typescript-multiline-comments).

What I ended up doing was re-indenting the comment based on the parent node if the comment looks like a JSDoc comment. That works well unless the parent node's indentation is wrong, because the indent information is calculated before the parent node gets printed.

**Comment by vjeux** [comment]
This one shouldn't be too hard to implement if someone wants to give it a try. Whenever we print a multiline comment, look at the previous indentation and the current one and add/remove indentation based on the difference between the two.

**Comment by maxdeviant** [comment]
@vjeux Yep! It's mostly working. I described the issue I ran into [here](https://github.com/prettier/prettier/pull/2470#discussion_r127123588). If we can figure out how to deal with that then I think this issue should be resolved.

**Comment by bcherny** [comment]
Thanks for the hard work everyone. Are there any updates? This is blocking https://github.com/bcherny/json-schema-to-typescript/issues/45

**Comment by maxdeviant** [comment]
@bcherny I have a PR that is close to completion. I'll see if I can get it finished up this weekend.
