### ISSUE TITLE
Question: "never" vs "preserve" in --prose-wrap

### ISSUE THREAD

**Issue by infokiller** [prettier/prettier#6488]
Hey,

I couldn't figure out from the docs what's the difference between the `never` and `preserve` values for the `--prose-wrap`/`proseWrap` setting. Can you please give me an example markdown file for which the results that are produced are different?

Thanks!

**Comment by lydell** [comment]
### always

Wrap at printWidth.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCAnOBbABASwAcBnAVzwBMIAbTXY-GXAQ2zhgBpdIpi4x4MUhhYUi+YmHxQA5rjjVGAOgA6UAMLDmAI0bDu0PgPb7szAB75spYrgwSbXPhVxnL12-GrUbuGNKkKUlh5GCUQDhAIQn9DZFBmDAwIAHcABUSEYmQQZgA3CHwKCJBtDGYwAGt2AGVCCukZZBgMUjhIgAsYbGoAdQ7GOGJ6sDgarMZ8PMYATxywYmzI6T4MGDTymTNkADNmaj5IgCticwAhcqra1jhUaThd-cOQE-Maxuo4AEVSCHhHg7tED1DCrHJmDCVKgpKAlQj2WC9IowDrIAAcAAZIvCIHxeuVCDl9ilmDMliAAI6-eAbaLZFDMYgAWigcDgFHZJSwVPwWA2zC2zABzz42HwzVaQIYsk+Pz+DyQe0BkRgOiRFBRyAATCryvhFLJ1BBsNsUFBoA9IjY4AAVHT0pV8AC+TqAA)
```sh
--parser markdown
--prose-wrap always
```

**Input:**
```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Curabitur consectetur maximus risus, sed maximus tellus tincidunt et.
```

**Output:**
```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur consectetur
maximus risus, sed maximus tellus tincidunt et.

```


### never

Put text in one single long line.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCAnOBbABASwAcBnAVzwBMIAbTXY-GXAQ2zhgBpdIpi4x4MUhhYUi+YmHxQA5rjjVGAOgA6UAMLDmAI0bDu0PgPb7szAB75spYrgwSbXPhVxnL12-GrUbuGNKkKUlh5GCUQDhAIQn9DZFBmDAwIAHcABUSEYmQQZgA3CHwKCJBtDGYwAGt2AGVCCukZZBgMUjhIgAsYbGoAdQ7GOGJ6sDgarMZ8PMYATxywYmzI6T4MGDTymTNkADNmaj5IgCticwAhcqra1jhUaThd-cOQE-Maxuo4AEVSCHhHg7tED1DCrHJmDCVKgpKAlQj2WC9IowDrIAAcAAZIvCIHxeuVCDkoHA8nAMCUAI6-eAbaLZFDMYgAWmJcAobJKWCp+CwG2YW2YAOefGw+GarSBDFknx+fweSD2gMiMB0SIoKOQACZleV8IpZOoINhtigoNAHpEbHAACo6emKvgAX0dQA)
```sh
--parser markdown
--prose-wrap never
```

**Input:**
```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Curabitur consectetur maximus risus, sed maximus tellus tincidunt et.
```

**Output:**
```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur consectetur maximus risus, sed maximus tellus tincidunt et.

```

### preserve

Respect linebreaks in the input.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCAnOBbABASwAcBnAVzwBMIAbTXY-GXAQ2zhgBpdIpi4x4MUhhYUi+YmHxQA5rjjVGAOgA6UAMLDmAI0bDu0PgPb7szAB75spYrgwSbXPhVxnL12-GrUbuGNKkKUlh5GCUQDhAIQn9DZFBmDAwIAHcABUSEYmQQZgA3CHwKCJBtDGYwAGt2AGVCCukZZBgMUjhIgAsYbGoAdQ7GOGJ6sDgarMZ8PMYATxywYmzI6T4MGDTymTNkADNmaj5IgCticwAhcqra1jhUaThd-cOQE-Maxuo4AEVSCHhHg7tED1DCrHJmDCVKgpKAlQj2WC9IowDrIAAcAAZIvCIHxeuVCDl4UM4Bg8g9IgBHX7wDbRbIoZjEAC0UDgcAoHJKWGp+CwG2YW2YAOefGw+GarSBDFknx+fweSD2gMiMB0SIoKOQACZVeV8IpZOoINhtigoNAKSAbHAACo6BnKvgAX2dQA)
```sh
--parser markdown
```

**Input:**
```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Curabitur consectetur maximus risus, sed maximus tellus tincidunt et.
```

**Output:**
```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Curabitur consectetur maximus risus, sed maximus tellus tincidunt et.

```

**Comment by infokiller** [comment]
Thanks a lot, this really clarified it for me!
