### ISSUE TITLE
[Question] No line break after a header in markdown?

### ISSUE THREAD

**Issue by keita-makino** [prettier/prettier#6491]
With some option, is it possible not to automatically insert a line break after a header?

```
# Hogehoge
                            <-- not insert this line
This is the first body.
                            <-- insert this line
## Fugafuga
                            <-- not insert this line
This is the second body.
```

**Comment by lydell** [comment]
Hi!

There’s no option for this. Prettier has supported markdown for soon two years, and I can’t remember anyone asking for this before.

Are we going to add an option? See our [option philosophy](https://prettier.io/docs/en/option-philosophy.html). Many times we keep issues like this open, but given the history in this case, I think it makes sense to close it.

Hope this helps!

**Comment by keita-makino** [comment]
@lydell Understood, thank you for your explanation :)
