### ISSUE TITLE
Published package is outdated, please publish 1.18.3

### ISSUE THREAD

**Issue by rasenplanscher** [prettier/prettier#6494]
The documentation at https://prettier.io/ lists `--only-changed` as an extension to `--write` but using the latest npm package, that flag is unavailable. Looking into this, I see that the last publish has been 3 months ago while the docs are more recent and probably up to date with `master`. Consequently, there is jarring mismatch between docs and the package. The best course of action seems to be to just release the current state.

Additionally, `master` lists the version as `1.18.1`. You may want to look into whether this indicates a problem or not.

**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI
- Runtime: Node.js v10.16.3
- Operating System: Windows 10

**Steps to reproduce:**
```
npx prettier --only-changed some-file.js
```

**Expected behavior:**
```
Cannot use --only-changed without --write.
```

**Actual behavior:**
```
[warn] Ignored unknown option --only-changed
```

**Comment by lydell** [comment]
We have started work on releasing 1.19: https://github.com/prettier/prettier/pull/6486

It's sad that documentation for the new stuff as sneaked out. It's not supposed to until we release.
