### ISSUE TITLE
pre-commit hook and a script for running Prettier for this repository

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#6497]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: 
- Runtime: 
- Operating System: 

**Steps to reproduce:**

This is not bug report.

**Expected behavior:**

- I think this repo should have pre-commit hook to run Prettier.
- I think this repo should have a npm script for running Prettier in the source code.

**Actual behavior:**

- Prettier mentions the pre-commit hook on [its website](https://prettier.io/docs/en/precommit.html), but this repo doesn't have that setting.
  - I sometimes see a pull request with CI falling due to linter error.
- It is also strange that there is no npm scripts for running Prettier in the source code.

**Comment by lydell** [comment]
Prettier is run via `eslint --fix`, isn't it? So no need for a separate command for running only Prettier?

**Comment by sosukesuzuki** [comment]
@lydell 
Oh Sorry, thank, I was missing it...
How do you think about pre-commit hook?

**Comment by pranshuchittora** [comment]
@sosukesuzuki great idea.. :+1:

**Comment by duailibe** [comment]
I personally don't like pre-commit hooks, I run lots of commits and run the linter before opening a PR

**Comment by lydell** [comment]
Me too. The pre-commit hook gotta be _really_ fast or I'd be annoyed very quickly. On the other hand, I don't do much coding on this repo these days so maybe I shouldn't have a say. :shrug:

**Comment by sosukesuzuki** [comment]
Okay, I'll close this issue because the maintainers don't need it.:+1:
