### ISSUE TITLE
Support for terraform

### ISSUE THREAD

**Issue by tp199314** [prettier/prettier#6499]
Hi folks,
is it possible to add support for terraform?
https://www.terraform.io/docs/configuration/style.html

Kind regards,
tp199314

**Comment by SimenB** [comment]
Why not use https://www.terraform.io/docs/commands/fmt.html?

**Comment by brodybits** [comment]
or make a custom plugin: https://prettier.io/docs/en/plugins.html

**Comment by evilebottnawi** [comment]
Out of scope prettier, you can create plugin, please read https://prettier.io/docs/en/plugins.html
