### ISSUE TITLE
Bad format for multi-line optional chaining with comment

### ISSUE THREAD

**Issue by clundie** [prettier/prettier#6500]
The output from a multi-line optional chain (using the `?.` operator) may be unexpected if you have a comment on one of the lines.

It behaves differently from a normal chain that uses the `.` but not `.?` operator.

If you feed prettier's output back into itself, the output is different again. So, prettier has to run two times before the output is stable.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAchATgWwEMAbDMAC0IEsoA6AHSkdzhgFdcoNDGMNaARgAoAlL35hR49BgDCEfPgQxxtACZSmUGQHkADjCrQSZSjQZaW7Tt1XCxXCZr4z5i5eID86zYxkAxODg1DAAFK0M4XAwINhgBQjAAawwE5IwaGAgMmABnOGIAMwtmVg4uHkdBZycHPm9XBSVYcQ0RAG5GEAAaEAgDIyhc5FBCXFwIAHdQsYRhlEIANwgqNR6QAVxEpNYAZT1EmgBzZBhcNjhe8hh8YgB1cip4XIOwOF25p6pFp4BPZHAuWGvRo+VwMHChCORGQhRI+V6ACtcgAPABCW2Se0ISgAMjQ4LD4ZcQMiUbtjsQ4ABFNgQeBE4gIkAHXBggEJAS-YjQdZ6XCZO6rGDkZAADgADL1+RB8nctnoAfy4GDFoTegBHOnwcL9eYgQi5AC0UCCamC6xYWqoLEh0MIjOZ+XwVFO5xJuUpNO1hKQcKZJJghAEQrUIuQACZemdqMRjm4YSgoNB1SA2PkACrB+b+-IAXzzQA)
```sh
--parser babylon
```

**Input:**
```jsx
// Normal chain.

return a
  .b()
  .c()
  // Comment
  .d()

// Optional chain.

return a
  .b()
  .c()
  // Comment
  ?.d()

// Feed Prettier outback back into itself.

return a
  .b()
  .c()
  ?.// Comment
  d();
```

**Output:**
```jsx
// Normal chain.

return (
  a
    .b()
    .c()
    // Comment
    .d()
);

// Optional chain.

return a
  .b()
  .c()
  ?.// Comment
  d();

// Feed Prettier outback back into itself.

return a
  .b()
  .c() // Comment
  ?.d();
```

**Expected behavior:**

I would expect that the output with the `?.` operator is the same as with the `.` operator, and that Prettier would not change the formatting if fed its own output.

```jsx
return (
  a
    .b()
    .c()
    // Comment
    .d()
);

return (
  a
    .b()
    .c()
    // Comment
    ?.d()
);

```

**Comment by lydell** [comment]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAchATgWwEMAbDMAC0IEsoA6AHSkdzhgFdcoNDGMNaARgAoAlL35hR49BgDCEfPgQxxtACZSmUGQHkADjCrQSZSjQZaW7Tt1XCxXCZr4z5i5eID860SAA0IBAGRlAAzsighLi4EADuAApRCOEohABuEFRq-iACuIRgANasAMp6BTQA5sgwuGxwAeQw+MQA6uRU8KHlYHAlyZ1UaZ0AnsjgoeEBNKFwuDDx+ZVEyABmJLMBAFahAB4AQvlFpYRKADI0cGsbDSA7uyVVxHAAimwQ8NfEmyDluLO4cYCQgCEbEaA5PS4GgwVpZGDkZAADgADAEoRBZq18npxlC4AC0lcAgBHd7wRZBFIgQihAC0UDgcDUzJyLDJVBYi0Iy0IXx+s3wVBqdVuoSer3JVyQ62+txgILhagRyAATAFatRiFU3CsUFBoMSQGxZgAVEEpWWzAC+1qAA)
```sh
--parser babylon
```

**Input:**
```jsx
// Normal chain.

return a
  .b()
  .c()
  // Comment
  .d()

// Optional chain.

return a
  .b()
  .c()
  // Comment
  ?.d()
```

**Output:**
```jsx
// Normal chain.

return (
  a
    .b()
    .c()
    // Comment
    .d()
);

// Optional chain.

return a
  .b()
  .c()
  ?.// Comment
  d();

```

**Second Output:**
```jsx
// Normal chain.

return (
  a
    .b()
    .c()
    // Comment
    .d()
);

// Optional chain.

return a
  .b()
  .c() // Comment
  ?.d();

```

**Comment by sosukesuzuki** [comment]
Probably, we should put the label `lang:javascript`
