### ISSUE TITLE
CRLF: CR is removed in multiline comments and strings

### ISSUE THREAD

**Issue by xarety** [prettier/prettier#6501]
```
type IAmIncredibleLongParameterType = {};
const IAmAnotherFunctionName = (_0: IAmIncredibleLongParameterType) => {};
export const IAmIncredibleLongFunctionName = IAmAnotherFunctionName(
    (_0: IAmIncredibleLongParameterType) => {
        setTimeout(() => {
            /*
                Multiline comment
                Multiline comment
                Multiline comment
            */
            console.log(
                'Multiline string\
                 Multiline string\
                 Multiline string'
            );
        });
    }
);
```
**Before running `lint --fix`:**

![before](https://user-images.githubusercontent.com/17852627/65254692-5b06c300-db05-11e9-829c-8ad8cae4369b.PNG)

Errors:
```
   6:15  error  Delete `␍`  prettier/prettier
   7:34  error  Delete `␍`  prettier/prettier
   8:34  error  Delete `␍`  prettier/prettier
   9:34  error  Delete `␍`  prettier/prettier
  12:35  error  Delete `␍`  prettier/prettier
  13:35  error  Delete `␍`  prettier/prettier
```
**After running `lint --fix`:**

![after](https://user-images.githubusercontent.com/17852627/65254717-66f28500-db05-11e9-8c53-487086edc148.PNG)

**What version of `eslint` are you using?**
6.0.1

**What version of `prettier` are you using?**
1.18.2

**What version of `eslint-plugin-prettier` are you using?**
3.1.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```
{
  "printWidth": 100,
  "tabWidth": 4,
  "singleQuote": true,
  "quoteProps": "consistent"
}
```
```
module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 6,
        sourceType: 'module'
    },
    plugins: ['import', 'folder-schema', 'processors-stub', 'react-hooks'],
    extends: ['plugin:import/typescript', 'plugin:prettier/recommended'],
    rules: {
        'react-hooks/rules-of-hooks': 'error',
        'react-hooks/exhaustive-deps': 'warn'
    }
};
```

**What source code are you linting?**
*.tsx

**What did you expect to happen?**
Equal line endings for the whole file.

**What actually happened?**
The plugin is requiring and replacing CRLF with LF in multiline strings and comments

**Comment by lydell** [comment]
Confirmed – Prettier removes the CRs inside the comment and the string. I also tried with `--end-of-line crlf`, but it made no difference.

**Comment by xarety** [comment]
Hello guys, any updates?

**Comment by lydell** [comment]
@xarety I think this is a good first issue for new contributors! Do you want to give it a shot?
