### ISSUE TITLE
Print <!doctype html> lowercase rather than uppercase

### ISSUE THREAD

**Issue by k-yle** [prettier/prettier#6502]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEwmGBPABzgAIALGAWwBsA+AHSlXOvqmOPgA8YHUB6ZrRAAaEBAIwAltADOyUAEMATkogB3AArKEclAoBuESZhEgARkoVgA1nBgBlAlclQA5shhKArnFGCA6qSS8DJOYHD2OsGS+sF4yOAycqIuMnBKMBqWrhQKyABmClRpogBWMpwAQpY2dvYKFHAAMi5wBUUlIOWc9i6uVHAAil4Q8O3FviBOSmlKCYKmBEouMP7GMKTIABwADKJLEGn+lgQJS3Cz+m2iAI4j8FniuiAKMgC0UHBwmN+mSnB3ST-LIKHJ5JCFCaiNIUSQebyTGR9AbDUZtCEdSYwBRmNaYDbIABMok8CkkVD6AGEIBRcgkoNBriAvGkACo43SQtIAX25QA)
```sh
--parser html
```

**Input:**
```html
<!doctype html>
<html>
  text
</html>
```

**Output:**
```html
<!DOCTYPE html>
<html>
  text
</html>

```

**Expected behavior:**
It'd be great if there were an option to disable transforming the html doctype tag into uppercase. Per [the spec](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype), the doctype is case insensitive - even [google.com](https://google.com) has its doctype declaration in lowercase. For normal HTML tags, prettier accepts all uppercase, e.g. `<DIV>` or all lowercase, e.g. `<div>`, however the doctype tag must be uppercase.

I would expect prettier not to treat the doctype differently from other HTML tags.

**Comment by lydell** [comment]
Hi!

I’m not sure what you mean. Prettier normalizes the case of case insensitive stuff in HTML:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQgYQCoCeADgKIAEAEjALIAyAfADpSoV4C2tZtAhlAOIBeRiAQimUMmRw8AznADKCWQEsYKgG5xmqAPQALGgxAAaEBCLros5KB4AnexADuABQfLkIHhogqAJqYgAEb2PGAA1nAwCkThKlAA5sgw9gCucGaG7AA2AOr6anCycWCKymqaagReYLI2Zgny9jCuYYnsPMgAZjw58mYAVrIAHgBCYZHRCjzscLQJcD19AyDDIwoJiTlwAIppEPDL-ZkgcfbNXtk5QUT2CTB5ATD6yAAcAAxmdxDyeWFELx3YpwexaIIARwO8DaFhsKDkAFooHA4P40UF7HAoSosW0eB0ukheiczPJ2CoUulTqokjt9oclsSVqcYDxgk9-C9kAAmMypHgqHJbHAQdidLxQaBLMxpeR4dnwknyAC+KqAA)
```sh
--parser html
```

**Input:**
```html
<!DoCTypE HtML>
<HTmL LanG="en">
  CaseSensitive
</htML>
```

**Output:**
```html
<!DOCTYPE html>
<html lang="en">
  CaseSensitive
</html>

```

Generally, case insensitive things are lowercased. The word `DOCTYPE` seems to be uppercased, which isn’t an uncommon style.

**Comment by k-yle** [comment]
Hey, as your example shows, everything is lowercased except for the doctype, which is uppercased. It just seems a bit inconsistent to me

**Comment by lydell** [comment]
I see. Yes, it’s a little inconsistent.

Let’s keep this issue open and see if it gets any :+1:s. So far, I think you’ve been the first to suggest changing the case of doctype. I doubt this will be changed.

**Comment by fisker** [comment]
This not really bothers me, but lowercase might be a better choice

Bootstrap used to use uppercase one until 2 years ago https://github.com/twbs/bootstrap/pull/24217

and reject uppercase few days ago 
https://github.com/twbs/bootstrap/pull/29363

h5bp also use lowercase , discuss https://github.com/h5bp/html5-boilerplate/issues/1522

this also stackoverflow discuss 
https://stackoverflow.com/questions/7020961/uppercase-or-lowercase-doctype

**Comment by lydell** [comment]
Yeah, I read a few of those yesterday and was amazed at how much such a small detail like this can be discussed :)

If we make this change it will affect a lot of HTML files, so we have to wait and see how popular this is.

**Comment by kydesnic** [comment]
Please, don't uppercase doctype! It is so annoying!

> If we make this change it will affect a lot of HTML files, so we have to wait and see how popular this is.

Anyway, why everybody is talking about compulsory case changing, and about reformatting of "a lot of HTML files"?
Why cannot this be a *setting* in the rc file? It even can hold the *default value*, which follows the current behaviour! No reformatting of the existing files in this case. And those who want to change it, will be able to change it.

**Comment by k-yle** [comment]
I don't think this even needs a setting - prettier accepts completely-lowercase and completely-uppercase for normal HTML elements (e.g. `<div>` and `<DIV>` are both okay).



> If we make this change it will affect a lot of HTML files

As above, if the `<!doctype html>` tag matched the behvaiour of all other HTML elments, no files will be reformatted and it wouldn't even be a breaking change - prettier would just accept a lowercase _and_ uppercase doctype tag.

**Comment by thorn0** [comment]
@kydesnic Prettier is an opinionated code formatter. "Opinionated" means "not configurable". Settings are added only as a last resort.

**Comment by callumlocke** [comment]
What constitutes a last resort? As far as I can tell there is no way to prevent the `doctype` from being upper-cased, except to give up on using Prettier for HTML files, which isn't really a solution.

**Comment by ExE-Boss** [comment]
Note that in **XML**, the `<!DOCTYPE` portion must be in upper case[^1], so doing this would cause issues with **XHTML** compatibility.

[^1]: https://www.w3.org/TR/xml/#dtd

**Comment by fisker** [comment]
@ExE-Boss See https://github.com/prettier/prettier/pull/7391#issuecomment-577099818

**Comment by HolgerJeromin** [comment]
I think this issue should be closed (github bug because of the added colon?)

**Comment by fisker** [comment]
Thank you!


Fixed in
 #7391
