### ISSUE TITLE
[Vue] Unexpected closing tag "template" – support same HTML parsing strategy as the Vue compiler

### ISSUE THREAD

**Issue by gluons** [prettier/prettier#6503]
My Vue code file uses Pug in `<template>`.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdQHyVSGEDEkseAllHACcWbSjADOEDHAC0kbNAQwAFDDwUA5KglTpq0o3UBKFqgD0mXATiMQAGhAQsMHtDHJQeAQIgB3AAqeCG4oeABuEDwAJnYgAEYCeGAA1nAwAMpYiXykyDACtHD2ABYwGDgA6kU88GKZYHBpQdU8odUAnsjgYm72fGKCMH4JpBh4yABmeDj99gBWYgAeAEIJyalpeFIAMnxwE1MzIPMLadk4cACKtBDw+9OFNJ79Ap2hBTFYAnww5VEwRcgABwABnsnwg-XKCSwnU+cGeoT29gAjtd4ENHMEQHgxNJ+HBIgSYgI4KieCShmpRndDv0MDxcvkHmIzpc0XskJN7vZVLFfpF-sgAEw8hI8HDZADCkmpKCgChitH6ABU8LFglz+gBfLVAA)
```sh
# Options (if any):
--parser vue
```

**Input:**
```vue
<template lang="pug">
  #container
  	some-component(tag='<some-tag>')
</template>
```

**Output:**
```vue
SyntaxError: Unexpected closing tag "template". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (4:1)
  2 |   #container
  3 |   	some-component(tag='<some-tag>')
> 4 | </template>
    | ^
```

**Expected behavior:**

Get formatted Vue file (with Pug template) without error.

**Comment by lydell** [comment]
Maybe related:  #6298

Workaround: Write `'<some-tag>'` some way that does not look like an HTML tag so that the outer HTML parser doesn’t choke on it. I’m not sure what the correct parsing here is.

**Comment by gluons** [comment]
I haven't used [Pug plugins](https://github.com/prettier/plugin-pug). Is this related to Pug plugin?

I guess Prettier may try to parse & format content in `<template>` even it's `<template>` with unsupported `lang`.

**Comment by gluons** [comment]
Your workaround works. Maybe it's related to parser problem with something like HTML in `<template>`

**Comment by lydell** [comment]
`<template>` tags are parsed as defined in the HTML spec.

Try pasting this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Test</title>
</head>
<body>

<template lang="pug">
  #container
  	some-component(tag='<some-tag>')
</template>

</body>
</html>
```

Into this HTML validator: https://validator.w3.org/nu/#textarea

And you’ll get this result:


    Error: End tag template seen, but there were open elements.
    From line 11, column 1; to line 11, column 11
    me-tag>')↩</template>↩↩</bo

    Error: Unclosed element some-tag.
    From line 10, column 24; to line 10, column 33
    nent(tag='<some-tag>')↩</t

Does your code work with the Vue compiler? If so, Vue must be using some custom parsing logic that does not follow the HTML spec the same way as Prettier currently does.

**Comment by gluons** [comment]
Yes. Code likes that work in Vue.  
I currently use it. Passing some tag as `String` into Vue component prop.

![ภาพ](https://user-images.githubusercontent.com/4688092/65372613-9f789700-dc9c-11e9-9993-af0d39a1f085.png)
