### ISSUE TITLE
Feature Request: ignore code constructs

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#6504]
I would like Prettier to have an option to allow me to ignore certain code constructs.
Eg, I use lots of ternaries and I format them differently from Prettier way.
I cannot insert `// prettier-ignore` everywhere.
I would like a setting that instructs Prettier to omit ternaries.

**Comment by lydell** [comment]
Hi!

If you want to use a different format than Prettier – then I think it’s actually best not to use Prettier at all. Or fork it.

**Comment by avalanche1** [comment]
You are too too categorical. Ability to opt out os some parts of the functionality - is a good sign, not the other way around.

**Comment by lydell** [comment]
Hehe, yeah maybe ;)

But see our [Option philosophy](https://prettier.io/docs/en/options.html).

**Comment by JounQin** [comment]
I personally love prettier's strange very much, if it does provide an option, you can custom it as you like, if not, just accept it until it's a bug or very uncommon usage.

We should never complain about formatting.

**Comment by evilebottnawi** [comment]
Sorry we don't want to change currently output and don't want implement new option(s), you can setup eslint rule(s) for own code style (for example you can use https://github.com/prettier/prettier-eslint), thanks for feedback
