### ISSUE TITLE
Multi-line  template literal is configured, and becomes a line when it is automatically saved.

### ISSUE THREAD

**Issue by xiaomuzizier** [prettier/prettier#6507]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
   
In my project, in the configuration file as follows：

`printWidth: 100, // 每行最多字符数`
  
In the code file，I am pulling the code from the git repository，as follows：
```jsx
   <div
        className={`honour-partner-relationship ${
                    RELATIONSHIP_CLASS[relation]
        } ${className}`}
    >

```

**Output:**
Depending on the configuration file, the code should wrap if it exceeds the maximum width. But every time I automatically save it, it always becomes a line.
I found that the configuration file did not take effect.But the same code, my colleague's machine is no problem.

```jsx

<div className={`honour-partner-relationship ${RELATIONSHIP_CLASS[relation]} ${className}`} >

```

**Expected behavior:**
```jsx
   <div
        className={`honour-partner-relationship ${
                    RELATIONSHIP_CLASS[relation]
        } ${className}`}
    >

**Comment by lydell** [comment]
Hi!

It sounds like you and your colleague are running different versions of Prettier. Printing of template literals was recently changed. I’d highly suggest making sure that everyone on the team is using the exact same version of Prettier to avoid conflicts.

Here’s the change to template literals in 1.18: https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay

The `printWidth` option is a general guideline, but Prettier can generate both shorter and longer lines. Template literals is one of the cases where Prettier sometimes allows longer lines. See for example #3368.

**Comment by xiaomuzizier** [comment]
> Hi!
> 
> It sounds like you and your colleague are running different versions of Prettier. Printing of template literals was recently changed. I’d highly suggest making sure that everyone on the team is using the exact same version of Prettier to avoid conflicts.
> 
> Here’s the change to template literals in 1.18: https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay
> 
> The `printWidth` option is a general guideline, but Prettier can generate both shorter and longer lines. Template literals is one of the cases where Prettier sometimes allows longer lines. See for example #3368.

but

**Comment by xiaomuzizier** [comment]
> Hi!
> 
> It sounds like you and your colleague are running different versions of Prettier. Printing of template literals was recently changed. I’d highly suggest making sure that everyone on the team is using the exact same version of Prettier to avoid conflicts.
> 
> Here’s the change to template literals in 1.18: https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay
> 
> The `printWidth` option is a general guideline, but Prettier can generate both shorter and longer lines. Template literals is one of the cases where Prettier sometimes allows longer lines. See for example #3368.

but But the problem is that we use the same version of Prettier，the version is 1.15.2.

**Comment by xiaomuzizier** [comment]
Hi，
   Thanks for your reply.
    But the problem is that we use the same version of Prettier，the version is 1.15.2.
    It is sad.




| |
李倩倩
|
|
邮箱：13051391963@163.com
|

签名由 网易邮箱大师 定制

On 09/22/2019 15:11, Simon Lydell wrote:

Hi!

It sounds like you and your colleague are running different versions of Prettier. Printing of template literals was recently changed. I’d highly suggest making sure that everyone on the team is using the exact same version of Prettier to avoid conflicts.

Here’s the change to template literals in 1.18: https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay

The printWidth option is a general guideline, but Prettier can generate both shorter and longer lines. Template literals is one of the cases where Prettier sometimes allows longer lines. See for example #3368.

**Comment by lydell** [comment]
Thanks. We don’t support old versions of Prettier. Please try the latest version. If you still can reproduce the issue with the latest version, please post steps to reproduce and we’ll take a look at it.

**Comment by xiaomuzizier** [comment]
Hi,
    After updating to the latest version, multiple lines will become one line. This situation is consistent with the features of the latest version. But what if I still need more than one line? Because of the old version used by colleagues, it will still maintain multiple lines. Is it because the prettier plugin in vscode is upgraded to 2.2.2, will it cause detection of multiple lines into a line?

**Comment by lydell** [comment]
[prettier-vscode](https://github.com/prettier/prettier-vscode/) is supposed to use your local installation of Prettier, regardless of the version of prettier-eslint. Things can go wrong, though.

I’m not sure what you mean? Can you provide an example?

**Comment by xiaomuzizier** [comment]
First, I cloned the project code from the git repository, at which point the prettier version of the project was 1.15.2. Some template strings are limited by the width and are multi-line, which meets the requirements of version 1.15.2. But when I run the project in the vscode local environment (when the prettier version is version 1.15.2), these template strings will change from multiple lines to one line without any changes, regardless of the width limit. What is the source of my thinking about the problem?

**Comment by xiaomuzizier** [comment]
The example is the question I asked. I am thinking because although the old version of prettier is used in the project, since the prettier plugin of vscode is the latest version(2.2.2), is this multi-line change caused by the prettier plugin of vscode ?

**Comment by lydell** [comment]
https://github.com/prettier/prettier-vscode/#prettier-resolution

> This extension will use prettier from your project's local dependencies. Should prettier not be installed locally with your project's dependencies, a copy will be bundled with the extension.

Sounds like prettier-vscode is not able to find your local installation for some reason, and is using a newer version that is bundled with the extension.
