### ISSUE TITLE
Proposal: multiple variable declaration

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#6510]
I'd be happy to see
```js
const label = field.text,
      fieldName = field.id,
      foo = 'bar';
```
or better yet
```js
const label     = field.text,
      fieldName = field.id,
      foo       = 'bar';
```
instead of current
```js
const label = field.text,
 fieldName = field.id,
 foo = 'bar';
```

**Comment by evilebottnawi** [comment]
The current output is expected and we do not want to change it, you can use `eslint` to change this logic

**Comment by lydell** [comment]
See also #6058, #850 and other issues about alignment.

**Comment by avalanche1** [comment]
@evilebottnawi what does `eslint` have to do with this?

**Comment by evilebottnawi** [comment]
@avalanche1 you can setup rule to enforce own code style
