### ISSUE TITLE
Inconsistent line spreading in `switch` expression

### ISSUE THREAD

**Issue by loilo** [prettier/prettier#6512]
Spreading the expression of a `switch` statement behaves differently than in `if`/`else`/`while` structures in a slightly weird way.

Originally caught over at prettier/plugin-php#1176.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAogDwIYC2ADgDZwYCCAOlDQJYBmGAFACQBucATgJ4Ay0AOYUoAEwBq3HpK4AjCAGc44vFzp5ZZAHKFyAMj0ZWeKBBgALbjP5CREqTPlKVajdt0BKDMBoBfGjQA7uZ0ZCwcUgJQwmLWjorKquqacDoE+obGphZWkbaxDtxOia4paXBePlD+tFAKgXQwYObhnLxRMfa88c5Jbqm6GAZGJmaWXNYddnFFCS7J7umVfgG16Nj4xGEAQquM4SRC2wCuMADKJHSC5jAkPGfmEFzwE31lg8NZY9wXVzd3DyeL3m-XKy2qq2CoXIbEO0RO50u11u90ezysb0WGRG2XGv2RALRwMxAyW3hWtXqjWaByOp3x-1RQIxpSxQ0yoxyXAZKMB6NerNJFXJ1RAABoQBAiDA6NAFMhQKouBBAgAFVQIeUoPDsCB0UTikCyLh4MAAazg5yIpro0WQMC4xzgEpuBBIAHUQvAFNawHAzprGnR2I0eMhwAp5RLbUpnqqTYICHhkAw8CQlBKAFYKHDbE3my1nXR8W1wFNpjMgbM4M62wRkACKxzMZaQqfTzpA1q4sfDsg0cBIhqIalg7v1FmQAA4AAwSkcJd0mojhkdwWOcQ0AR2b8HjUq1IDwCgAtFA4HBRJfDVw4Du6Lf43hE8m2xXO0oCHR7Y6P3XG7urbtpWMAaOOoiTkgABMEoOngoR1gAwhABBJuGpjnoaxxKAAKhoWrAXAvi+EAA)
```sh
--parser babel
```

**Input:**
```jsx
// Example A

if ($veryLongAndVeryVerboseVariableName && $anotherVeryLongAndVeryVerboseVariableName) {
}

while ($veryLongAndVeryVerboseVariableName && $anotherVeryLongAndVeryVerboseVariableName) {
}

switch ($veryLongAndVeryVerboseVariableName && $anotherVeryLongAndVeryVerboseVariableName) {
}


// Example B

if ($longButSlightlyShorterVariableName && $anotherSlightlyShorterVariableName) {
}

while ($longButSlightlyShorterVariableName && $anotherSlightlyShorterVariableName) {
}

switch ($longButSlightlyShorterVariableName && $anotherSlightlyShorterVariableName) {
}
```

**Output:**
```jsx
// Example A

if (
  $veryLongAndVeryVerboseVariableName &&
  $anotherVeryLongAndVeryVerboseVariableName
) {
}

while (
  $veryLongAndVeryVerboseVariableName &&
  $anotherVeryLongAndVeryVerboseVariableName
) {}

switch (
  $veryLongAndVeryVerboseVariableName &&
    $anotherVeryLongAndVeryVerboseVariableName
) {
}

// Example B

if (
  $longButSlightlyShorterVariableName &&
  $anotherSlightlyShorterVariableName
) {
}

while (
  $longButSlightlyShorterVariableName &&
  $anotherSlightlyShorterVariableName
) {}

switch (
  $longButSlightlyShorterVariableName && $anotherSlightlyShorterVariableName
) {
}

```

**Expected behavior:**
Lines of the `switch` expression should be spread in the same way as `if` or `while` expressions.

**Comment by evilebottnawi** [comment]
Thanks for issue, should be easy to fix
