### ISSUE TITLE
Refactor proposal: Move functions unrelated to print to `utils.js` from `printer-estree.js`.

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#6513]
(Sorry, this is not bug report, so I didn't follow to an issue template)

I noticed to there are functions unrelated to printing, when I was reading `language-js/printer-estree.js`. I think that these functions should be defined in `language-js/utils.js`. For example, `isBinaryish`, `isMemberish`, `isNumricLiteral`, `isStringLiteral`, and more..

How do you think about it?

If it is needed, I'll do it.

**Comment by evilebottnawi** [comment]
Yep, PR welcome :+1:
