### ISSUE TITLE
Object destructuring in method shorthand syntax always breaks into multiple lines

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier#6515]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2AB0pNMAzAVyjAApzLKBLAEwBpmWyKXKOADYQA5khKYYrGELiYAvt36UFPAJQkelAE5wYNHRQ6YA1FJlyA3DyXkFNqCE4gIAB2npkoAIY6dEADuAAp+CGjIID4AbhAcziA4Oj5gANb6AMpuKaxQosgwOjRwLgAWMAC2QgDqpTJwaNlgcBnhMqzRMgCekWBoES65aHA6MMHJohU+yFQ+QsMueGgAHgBCyWmZPhVwADK5cDNzCyBLyxm5onIAijQQ8EfzJSDZOsM6kTg+OF0iTi5uHS5GDVDgwUrIAAcAAYAQFhtVkm5IoCGiNoocXABHO7wcbuCIoHxoAC0UDgcHYlISehxrD04x8k2mSFmTxcwwqrAKRWeaEuN1xhyQhWKLhg31B7HByAATOLkqwhJcAMIQCpTSJQaCYkA0YYAFW+hLZwwUCiAA)
```sh
--parser babylon
--single-quote
```

**Input:**
```jsx
const obj = {
  func(
    id,
    {
      blog: { title },
    }
  ) {
    return id + title;
  },
};

```

**Output:**
```jsx
const obj = {
  func(
    id,
    {
      blog: { title }
    }
  ) {
    return id + title;
  }
};

```

**Expected behavior:**
The result should like the es5 function property of the object.
```javascript
const obj = {
  func: function(id, { blog: { title } }) {
    return id + title;
  },
};
```

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by bakkot** [comment]
Prettier [intentionally keep linebreaks in object literals when they are present in the original program](https://github.com/prettier/prettier/blob/24ffeba8f6324ee74c5439c649b03fa2b0aec441/docs/rationale.md#multi-line-objects), so I don't think this a bug. There is an open issue (https://github.com/prettier/prettier/issues/2068) about adding an option to ignore the input formatting entirely; if that's what you are looking for, you should consider upvoting it.

**Comment by lydell** [comment]
@bakkot But in this case it seems to be impossible to force a non-wrapping input. Something seems to be wrong with the method shortcut syntax for object literals.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2AB0pNMAzAVyjAAoBLAEwBoTMcAbCAcyScYTGNziYAvpICUJcpUoAnODBqKKrTAGpMw0XADc8yW2O16AJkHN2nHv0HBdIsZJlEAfHIoLlq9ZiaOnpiRj4SplASYeQgbCAQAA7C6MigAIaKihAA7gAKmQhoyCDpAG4QrHEgOIrpYADWKgDKifVMUHzIMIo0cPEAFjAAttwA6gMicGhtYHDNRSJMZSIAniVgaMXxHWhwijB5dXzD6chU6dx78XhoAB4AQnWNLenDcAAyHXDnl9cgtzuzQ6fDEAEUaBB4L8rv0QG1FHtFCUcOkcKteFBqolFB0YGNWDABsgABwABniOIgezGdUSJRx032ZR+8QAjpD4EcksUUOk0ABaKBwOAsUXVZQcpjKI7pE5nJAXWHxPbDJjdXpwtAg8Gcn5IHp9eIwNEElhE5AWY11JjcEEAYQgw1OJSg0FZIBoewAKmjeUq9hIJEA)
```sh
--parser babylon
--single-quote
```

**Input:**
```jsx
const obj = {
  func(id, { blog: { title } }) {
    return id + title;
  },
  func2: (id, { blog: { title } }) => {
    return id + title;
  },
};


```

**Output:**
```jsx
const obj = {
  func(
    id,
    {
      blog: { title }
    }
  ) {
    return id + title;
  },
  func2: (id, { blog: { title } }) => {
    return id + title;
  }
};

```

**Comment by ericsakmar** [comment]
Hi! I just added a PR that treats `ObjectMethod`s like `ArrowFunctionExpression`s in this circumstance.
