### ISSUE TITLE
Format If statement based on line-length

### ISSUE THREAD

**Issue by ro-savage** [prettier/prettier#6520]
I searched for this topic but couldn't find any issues opened/closed.

Why does the `if` formatter always format to multi line instead of respecting the line length?

`if (good) { return GoodThing() }`

Will always be reformatted to multi line.

Why not respect line length and only format if the statement is over the line length?

**Comment by evilebottnawi** [comment]
Thanks for issue, it is preferable style for many developers, we don't want to change this, maybe we revisit this in future, but most probably not
