### ISSUE TITLE
Linebreak issue in JS Code after (.)

### ISSUE THREAD

**Issue by SumitSFDC1506** [prettier/prettier#6521]
Hi All,

I am using Prettier in my JS code. 
The original Code is as below:
let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

and after passing it through prettier
let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

i don't want this to happen. Please suggest which configuration of prettier in VS Code would help me here

**Comment by evilebottnawi** [comment]
Please use stackoverflow for questions, it is bug tacker, also you ignore issue template. It is expected behavior right now, maybe we change this in future, we already have same issue (can't find sorry)
