### ISSUE TITLE
Wrapping of small arrow functions

### ISSUE THREAD

**Issue by gc** [prettier/prettier#6524]
Playground: https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaCuBbPAQwCcBPTAXk0IHdCBLLAMzhjAAsAKAA3ZhgAOaJAHoRxNACMcAExmkAdJDwi4ADw6EoAczgjcBEooBWaaNwCUAHShWYdh-acKY7BJ2Jw0lAHyZPaAqm0JwWFgDcIAA0IBACMPToyKAkxBA0AAokCGjIIIQAbhD0MtEgksSEYADWrADKAlX0OsgwxDhwMXx4ADYA6uyMXo1gcHU5jPQFjKR5YGi5Mc1ocMQwGZXaRMhMhD0rMaZqAEKVNfWEeHAAMs1wO3sHIEd1zdo9cACKOBDwD-udECNCSrPKSQiSUg9aBlATEZowPolVzIAAcAAYYnCICs+pUBHk4V5VgV7jEAI4-eAbOK5FCENAAWigcDgMjZZU8lPong2hC2hH+TxWeHorXagLQbw+31+9yQuwBMRgEKRMhRSAATMrKvQem8AMIQQx5KDQMkgHArAAqELpipWAF9HUA

Is it possible for it to behave more like the left option? (e.g. keep then `.then()` on 1 line) I find it pointless and harder to read when the `.then(` is separated like it is.

Also applies in longer cases, like this: https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaCuBbPAQwCcBPTAXk0IHdCBLLAMzhjAAsAKAA3ZhgAOaJAHoRxNACMcAExmkAdJDwi4ADw6EoAczgjcBEooBWaaNwCUAHShWYdh-acKY7BJ2Jw0lAHyZgNphBwSGhYcF2TBDEmJwANqyY9JSYAAwA3EmYADyYAIypGUkA1MUW-oHhVdWhMhAAyjA4TEycFumVNV2hAL6d3V30TLFmeKzs9DrldfUQY66T2m0dUANdPe0gADQgEAIw9OjIoCTEEDQACiQIaMgghABuEPQy2yCSxIRgANas9QJfRbIGDEHBwHZ8PBxADqE3gaABYDg9RujHoD0YpDuYDQtx2kzQcGIMAun20RGQTEIcUJO1MagAQp8fn9CGMADKTOCU6m0kD0+qLBIARRwEHgPJp4JAAIkRLukkIklIcWgbwExEmMGhL1cyAAHKkdhqIIToZ8BHcNV4iQ9uTsAI5i+Ckva3FCENAAWigcDgMn9b08TvonlJhHJhElfMJeHowNB0rQQrgovF3KQVKlOxgSp1Mj1SAATDnPvQ4osAMJzCkoKDQe0gHCEgAqSvdWcJPR6QA

**Comment by evilebottnawi** [comment]
Please use issue template in future.

Duplicate https://github.com/prettier/prettier/issues/1401
