### ISSUE TITLE
[Vue] HTML tag in comment outside of template throws error

### ISSUE THREAD

**Issue by jamescostian** [prettier/prettier#6525]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qAJgJYBuxA9OVatZrgXIQDpSoDOYATmVhiE4ADywReMAAQk4AMzwBXHNOBSAvgx79B7KNWpTUeAEZg93GAE8crLdduEQAGhARBZaF2Sg8vXhAA7gAKfgjeKHgUEGQkLiAmvHhgANZwMADKWMlkUADmyDC8inCuABYwGDgA6mVk8FzZYHAZ4fWU9VbI4FzerrlccJLBSXkYeMgKOIOuAFZcIgBCSanpGXgYcAAyuXCTeNOlIPMiGbl5tgCKihDw+4eu2byDvN0UJfFY-LDVsTBlyAAHAAGR4BQbVJJYbpfOAvCh7VwARxu8BG7giIDwXAAtFA4HBZHFXLw4CiyKSRngxhMkFMZiBBhgyIVikcuOcrqi9nSDgyYKZfiR-sgAEyuIp4Mg4c4AYQgGHG3Sg0ERIEUgwAKqYIvS4Op1EA)
```sh
--parser vue
```

**Input:**
```vue
<template><div></div></template>
<script>export default { }</script>
// <abc>
<style></style>
```

**Output:**
```vue
printChild@https://prettier.io/lib/standalone.js:20926:291
printChildren/<@https://prettier.io/lib/standalone.js:20913:102
map@https://prettier.io/lib/standalone.js:15801:21
printChildren@https://prettier.io/lib/standalone.js:20857:24
genericPrint$2@https://prettier.io/lib/standalone.js:20741:39
callPluginPrintFunction@https://prettier.io/lib/standalone.js:15948:18
printGenerically/res<@https://prettier.io/lib/standalone.js:15899:16
printComments@https://prettier.io/lib/standalone.js:15621:22
printGenerically@https://prettier.io/lib/standalone.js:15898:22
printAstToDoc@https://prettier.io/lib/standalone.js:15910:32
coreFormat@https://prettier.io/lib/standalone.js:16229:24
format@https://prettier.io/lib/standalone.js:16476:73
formatWithCursor@https://prettier.io/lib/standalone.js:16492:12
withPlugins/<@https://prettier.io/lib/standalone.js:30992:15
format@https://prettier.io/lib/standalone.js:31000:12
formatCode@https://prettier.io/worker.js:234:21
handleMessage@https://prettier.io/worker.js:185:18
self.onmessage@https://prettier.io/worker.js:155:14

```

**Expected behavior:**

```vue
<template>
  <div></div>
</template>
<script>
export default {};
</script>
// <abc>
<style></style>
```

**Comment by evilebottnawi** [comment]
`//` is valid?

**Comment by lydell** [comment]
(Just to clarify: Prettier should either print a syntax error here, or format the code somehow if it is valid (is it?). But it should not crash.)

**Comment by jamescostian** [comment]
This code is valid, it is not a syntax error, and is compiled by vue just fine. As an example, check out [this code](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qAJgJYBuxA9OVatZrgXIQDpSoDOYATmVhiE4ADywReMAAQk4AMzwBXHNOBSAvgx79B7KNWpS8XElNRS5AcwAWUvdxgBPHKy1OXhEABoQEQWWguZFA8Xl4IAHcABVCEIJQ8CggyEm8QACNePDAAazgYAGUsbLIoS2QYXkU4H2sYDBwAdWsyeC5isDgCuNbKVsdkcC4gn1KuOEkorMsMPGQFHHGfACsuEQAhLNz8grwMOAAZUrh5vEWakFWRAtLLFwBFRQh4U-OfYt5x3kGKarSsfiwRopGDWZAADgADO9wuNGlksIMAXAvhQTj4AI5PeBTPzxEDGAC0UDgcFkqR8vDgWLIVKmeBmcyQCyWIHGGDIFSqFy4twe2JOzLOrJgeHSwJIoOQACYfJU8GQcLcAMIQDCzQZQaDokCKcYAFTF8RZcHU6iAA) that prettier handles just fine.

**Comment by evilebottnawi** [comment]
@jamescostian thanks for issue, it is bug, feel free to send a PR

**Comment by fisker** [comment]
` @vue/compiler-core` can't parse this code, we should close this

check https://astexplorer.net/
