### ISSUE TITLE
[TS] Prettier strips trailing commas from generic arguments

### ISSUE THREAD

**Issue by half0wl** [prettier/prettier#6527]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBhCBbAB2gRiUwCU4BDMGAOgDFsAeYAHSk0wICcICAjGQw8AllADmAGg5de-AEzCYYyTKgBfAHyYAvJgAUASj072UNirgwArj07MtzAPRaOGkFJD8Yo9MlAqHj4AdwAFIIQ0ZBAqADcIUQATTxAAIx4aAGtrAGUCGnEJZBUbOC8ACxg8ABsAdQrReDQCsDhcqKbROKaATxiwNGivcTQ4HhgwzIk8KmQAMyoasa8AKzQADwAhTLAcmFyqPDgAGXE4BaWVkHWN3KKauABFGwh4S+XykAKeMZ4YmC9AhwNBgMQEGCpXjiGB1ZIwCrIAAcAAYvPIxnVMgQYrwQeM4hcvABHV7wKb8aIoKhoAC0UDgcCSTNSPDgpNEbKmVBmcyQi0+XjGeFEH2uaAezzJF35Vy+MCoaThSQRyAUXhUVFENSKuDwsxiSxqqRsYwAKoqqQKxhoNEA)

```sh
{
  "parser": "typescript",
  "trailingComma": "all"
}
```

**Input:**
```typescript
const Component: React.FC<{
  prop1: string,
  prop2: string,
}> = () => {
  return <></>
}
```

**Output:**
```typescript
const Component: React.FC<{
  prop1: string
  prop2: string
}> = () => {
  return <></>
}
```

**Expected behavior:**

With the `{ "trailingComma": "all" }` config, the properties should have a trailing comma behind them, i.e.:

```diff
const Component: React.FC<{
-  prop1: string
-  prop2: string
+  prop1: string,
+  prop2: string,
}> = () => {
  return <></>
}
```

**Comment by Skalman** [comment]
I don't think this is a bug. That's a type argument, so the properties should use a semicolon - unless `--no-semi` is enabled.

**Input:**

```js
type A = {
  prop1: string,
  prop2: string,
};

const Component: React.FC<{
  prop1: string,
  prop2: string,
}> = () => {
	return <></>
}
```

**Output:** ([`--no-semi` disabled - playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXm2AB0ptsMAnCDARiWwGcYqBLKAcwBoyLraAJkYt2XXlAC+AbjJlIUFtgDCEALYZoCGIwBKcAIZgYAOgBiygDylylGvRGsOPPnaGOxLqQD5C2ABQAlIS+NiSscDAArlTklt6WAPTeZJIg3CC0MGzQTMigBlQ0AO4ACoUIeSgGAG4QbAAm6SAARlRGANaRAMoYRs7IrFFwGQAWMGoANgDqo2zwTH1gcN2V82w182jI4Ex5GRxMcFQwpe2cagbIAGYGk0cZAFZMAB4AQu1gXTDdBmpwABkOHAbncHiBni9us5JnAAIpRCDwUH3EYgPpUI5UHboLBMMDsDAwZrUDgwaaNGCjZAADgADBkBEdpu0MDtqHAsTUQRkAI6I+BnWhVEAGJgAWigcDgDRlzSocH5bAVZwMFyuSFuqIyRzUbEGVGGOph8IFIM1YLRMAMLQpDSpyEEGVYBjYk2cqjUlx2d0mzSiRwAKjaqlqjpJJEA))

```js
type A = {
  prop1: string;
  prop2: string;
};

const Component: React.FC<{
  prop1: string;
  prop2: string;
}> = () => {
  return <></>;
};
```

**Output:** ([`--no-semi` enabled - playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXm2AB0ptsMAnCDARiWwGcYqBLKAcwBoyLraAJkYt2XXlAC+AbjJlIUFtgDCEALYZoCGIwBKcAIZgYAOgBiygDylylGvRGsOPPnaGOxLqQD5C2ABQAlIS+NiSscDAArlTklt6WAPTeZJIg3CC0MGzQTMigBlQ0AO4ACoUIeSgGAG4QbAAm6SAARlRGANaRAMoYRs7IrFFwGQAWMGoANgDqo2zwTH1gcN2V82w182jI4Ex5GRxMcFQwpe2cagbIAGYGk0cZAFZMAB4AQu1gXTDdBmpwABkOHAbncHiBni9us5JnAAIpRCDwUH3EYgPpUI5UHboLBMMDsDAwZrUDgwaaNGCjZAADgADBkBEdpu0MDtqHAsTUQRkAI6I+BnWhVEAGJgAWigcDgDRlzSocH5bAVZwMFyuSFuqIyRzUbBR4KYMPhApBmrBaJgBhaFIaVOQggyrAMbEmzlUakuOzuk2aUSOABVrVUtUdJJIgA))

```js
type A = {
  prop1: string
  prop2: string
}

const Component: React.FC<{
  prop1: string
  prop2: string
}> = () => {
  return <></>
}
```

**Comment by half0wl** [comment]
@Skalman is absolutely right, I don't know how I missed that. Thanks for the response! I'm closing this.
