### ISSUE TITLE
[TypeScript 3.7] add support for `asserts` keyword

### ISSUE THREAD

**Issue by niedzielski** [prettier/prettier#6574]
**Prettier 1.18.2**

TypeScript is developing support for [assertions in control flow analysis](https://github.com/microsoft/TypeScript/pull/32695). The functionality is now available in development builds such as [v3.7.0-dev.20190928](https://www.npmjs.com/package/typescript/v/3.7.0-dev.20190928). This ticket requests enabling Prettier support of the new `asserts` keyword.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgM7FwBOMAFAG6EA26cS+mA1lBAO5QCULJMpWL46jOPmAAdKPnwwAFuW74ocLvgCi5ZeSq8ZAXxkgANCAgAHXNGLJQhHdwAKjhHZSEaEHABMzIABG5IRgbHAwAMqWoThQAObIMORM5gowALb0AOoKOPDEMWBwke75ODT5AJ7I4KQBcUIwziHxGYTIqAxk5gBWxAAeAEIhYRGRhBlwADJxcJ3dcH2DkXHx9HAAiugQ8Av0PSAx5EK1MFWWcMRg5DjWAZa3sNl+isgAHAAM5o8QZNkhSy1R5XCg0ebmACOO3gLSsHhAJAAtGo4L40QFyHBoTgsS1CG0OkgugcliAyBkcEkUmTiGsNttdvNiYtzDBCIEXr43kgAExskI4ehrADCEAy7VqnDUAXQZAAKhyPCSyIZDEA)
```sh
--parser typescript
```

**Input:**
```tsx
function assert(value: unknown): asserts value {
  throw new Error()
}
```

**Output:**
```tsx
SyntaxError: '{' or ';' expected. (1:42)
> 1 | function assert(value: unknown): asserts value {
    |                                          ^
  2 |   throw new Error()
  3 | }
  4 | 
```

**Expected behavior:**
```tsx
function assert(value: unknown): asserts value {
  throw new Error()
}
```

**Comment by evilebottnawi** [comment]
It is still in dev, feel free to send a PR when it was supported officially

**Comment by niedzielski** [comment]
In the interest of keeping this ticket up to date: [assertions are now in beta](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/).

**Comment by lppedd** [comment]
Also `foo?.bar` syntax isn't supported.
