### ISSUE TITLE
--only-changed need review again

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#6577]
PR: https://github.com/prettier/prettier/pull/5910

I think we should remove revert this PR and finish the PR late, as this could potentially create problems:
1. Argument name - `eslint`/`stylelint` (maybe other linters) use `--cache` option, so currently name is not too good
2. We should allow to setup cache directory, it can be potential problem for running prettier on difference system and CI
3. This options should be implement on API side, not on CLI (like `eslint`/`stylelint` do), it is allow to use cache for node API users (plugins for IDE, custom CLI runner, etc)
4. It should be work with `--check` argument too. I don't want to recheck files what are not changed
5. More tests, i find we don't have enough tests (i find couple edge cases with cache invalidation).
6. Use https://github.com/royriojas/file-entry-cache (there are a lot of abilities, fixes and other features, also easy maintenance)
7. Future implementation `--cache` (check and format only changed files, as in eslint and stylelint) can be difficult and added an additional cache layer what can be misleading and consume a lot of disk space  

It is very important because changing CLI argumentx and logic potentially can be breaking change and we need to do good design for CLI/API to avoid unnecessary/painful problems in future and avoid unnecessary breaking change.

I can to refactor and improve it, but it is require time, and we already prepare `1.19` so better solution is revert this commit for `1.19` and release in `1.20`.

/cc @prettier/core @g-harel @duailibe

**Comment by g-harel** [comment]
I think you make some great points, especially about using `file-entry-cache`.
I would be happy to help out with these changes.

**Comment by lydell** [comment]
Makes sense. I'm :+1: on delaying it for 1.20.

**Comment by evilebottnawi** [comment]
@g-harel sounds great, let's revert this for `1.19` and shipped in `1.20`, no need rush

**Comment by evilebottnawi** [comment]
@g-harel friendly ping, we can start implement this again

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/prettier/prettier/issues/5853

**Comment by g-harel** [comment]
Gotcha, I will get started with that this weekend

**Comment by evilebottnawi** [comment]
:+1:

**Comment by g-harel** [comment]
I started looking into how this could be implemented in core and I noticed there might be some important info missing to implement correct cache busting.

My assumption in the initial implementation was that a combination of `getSupportInfo` and `options` would be enough to guarantee that version changes of prettier core or any external plugins would generate a different hash. Looking through the code, this looks like it might not be the case.

I'm thinking it would be useful to make available all plugin names/versions (either internally or in `getSupportInfo`). For the built-in ones, I think reading prettier's version seems like it could work. For external plugins, I've been able to read the versions from inside [`findPluginsInNodeModules`](https://github.com/prettier/prettier/blob/3805034bdfe45722e31a1abf019d4368dfb8ae11/src/common/load-plugins.js#L72). However, I am not sure how [`externalPluginInstances`](https://github.com/prettier/prettier/blob/3805034bdfe45722e31a1abf019d4368dfb8ae11/src/common/load-plugins.js#L28) work and I'd like some background as to how they would get there, are these plugins passed at runtime as objects?

I'm not sure this is the right place for this discussion, but please point me there if it isn't!

**Comment by evilebottnawi** [comment]
@g-harel let's doing all step by step, send a PR again and i commented all weird places :+1:
