### ISSUE TITLE
How to get same formatting result

### ISSUE THREAD

**Issue by denvash** [prettier/prettier#6596]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAfAHSgAh6gMQgCcBbASXlJwBsBDAIzhoF5gBVAJQBkA6epjQC+WXHhzAA5nBgEAlswAmAETiRidGCQAUXPgDMFNRQBoJ2ceOIBXGnADOSHAG1gOYnACO1uR9M5SB3s6aSc9XkD7YOkcIQBdC3EhAEptRMtUcigAB2sYAEFFRWgcJn0SODYyiqEcOn14YjZ6xtrs+jA4AAsIYzgmjh5edrpOnr7iWoB6UUtkoUTUKaIySjhSUUWViipaRmY2cIFmEXSJaVkjFTUSTR1wwyUzYDO8GztHF1fxF7FLSw83l8cFM30skWicDCQwhITgYNi3wSf1iqW+mRyeUKxVw1Q8VTg5Q8tRa-WaDX6bQ63V6ijJgz4IzGtMpOBmZ3mi2WJB261ES3QIBMIAg2Rgcmg9mQoDoxGIEAA7gAFWUIKUoOgANwgckUQpADA0YAA1jIAMrZUZyKCSZAwGxwYVdGCkGgAdS6cng9ktnTNaq9ck1XoAnshwFF9db7P0YEqNJJSHRkPo6DQY8KAFb2AAeACEjaaYGa6IFuNa4Cm0xmQNmc2brZI7ABFawQeBV9OOkCW4gx4jhhiMEM0aD67LEa0wN26mBdZAADgADMKJxAY26NNlwxOHP1NZXhd523B46L1SA6PYALRQOAgkH6wE+DzxkJJzs1mOkOR2h3C+xGxbNsOyQe1rG7GBGBnRQ52QAAmYV7ToOQaEbABhCBSA-FAoGgQ8QGsGMABVGHVVMuyEIQgA)
```sh
--parser babylon
--single-quote
```

**Input:**
```jsx
<>
  <FormItem label={URL.label}>
    {getFieldDecorator(URL.field, {
      rules: [{ required, message: URL.message }]
    })(
      <InputAddon before={before} after={after} placeholder={URL.placeholder} />
    )}
  </FormItem>

  <FormItem label={URL.label}>
    {getFieldDecorator(URL.field, {
      rules: [
        {
          required,
          message: URL.message
        }
      ]
    })(
      <InputAddon before={before} after={after} placeholder={URL.placeholder} />
    )}
  </FormItem>
</>
```

**Output:**
```jsx
<>
  <FormItem label={URL.label}>
    {getFieldDecorator(URL.field, {
      rules: [{ required, message: URL.message }]
    })(
      <InputAddon before={before} after={after} placeholder={URL.placeholder} />
    )}
  </FormItem>

  <FormItem label={URL.label}>
    {getFieldDecorator(URL.field, {
      rules: [
        {
          required,
          message: URL.message
        }
      ]
    })(
      <InputAddon before={before} after={after} placeholder={URL.placeholder} />
    )}
  </FormItem>
</>;
```

**Expected behavior:**
Note for the same expression `rules: [{ required, message: URL.message }]` which doesn't format as the its first appearance.
I would expect the same result on formatting, for example:

```
<>
  <FormItem label={URL.label}>
    {getFieldDecorator(URL.field, {
      rules: [{ required, message: URL.message }]
    })(
      <InputAddon before={before} after={after} placeholder={URL.placeholder} />
    )}
  </FormItem>

  <FormItem label={URL.label}>
    {getFieldDecorator(URL.field, {
      rules: [{ required, message: URL.message }]
    })(
      <InputAddon before={before} after={after} placeholder={URL.placeholder} />
    )}
  </FormItem>
</>;
```

**Comment by evilebottnawi** [comment]
Remove newline from and run prettier again:
```
{ required,
          message: URL.message
}
```

We respect user input in some cases (if you have newline in object we format each property on new line and if no we try to put all properties in one line respecting print width), we already have issue about ignoring user code https://github.com/prettier/prettier/issues/2068
