### ISSUE TITLE
Unstable behaviours when using comments around variables

### ISSUE THREAD

**Issue by timjacobi** [prettier/prettier#660]
Hi, thank you for the great tool!

I have seen that @vjeux reported some unstable behaviours and thought we shouldn't rely on finding them by coincidence so I have written a tool that runs _prettier_ on a file and then runs it again on the prettified output. If the two passes are not the same it displays a diff.
The tool is here: https://github.com/timjacobi/prettier-unstable-finder

I ran the tool against the entire AngularJS code base and the good news is that it only found one unstable behaviour that hasn't been reported yet. Most other findings were related to comments in combination with the ternary operator as reported in https://github.com/jlongster/prettier/issues/617

Original source:
```js
var fnString =
      // The build and minification steps remove the string "use strict" from the code, but this is done using a regex.
      // This is a workaround for this until we do a better job at only removing the prefix only when we should.
      '"' + this.USE + ' ' + this.STRICT + '";\n' +
      this.filterPrefix() +
      'var fn=' + this.generateFunction('fn', 's,l,a,i') +
      extra +
      this.watchFns() +
      'return fn;';
```

Pass 1:
```js
var fnString = // The build and minification steps remove the string "use strict" from the code, but this is done using a regex.
// This is a workaround for this until we do a better job at only removing the prefix only when we should.
'"' +
  this.USE +
  ' ' +
  this.STRICT +
  '";\n' +
  this.filterPrefix() +
  'var fn=' +
  this.generateFunction('fn', 's,l,a,i') +
  extra +
  this.watchFns() +
  'return fn;';
```

Pass 2:
```js
var fnString = // This is a workaround for this until we do a better job at only removing the prefix only when we should. // The build and minification steps remove the string "use strict" from the code, but this is done using a regex.
'"' +
  this.USE +
  ' ' +
  this.STRICT +
  '";\n' +
  this.filterPrefix() +
  'var fn=' +
  this.generateFunction('fn', 's,l,a,i') +
  extra +
  this.watchFns() +
  'return fn;';
```

Pass 3
```js
var fnString = '"' + // This is a workaround for this until we do a better job at only removing the prefix only when we should. // The build and minification steps remove the string "use strict" from the code, but this is done using a regex.
  this.USE +
  ' ' +
  this.STRICT +
  '";\n' +
  this.filterPrefix() +
  'var fn=' +
  this.generateFunction('fn', 's,l,a,i') +
  extra +
  this.watchFns() +
  'return fn;';
```

**Comment by vjeux** [comment]
FYI, you can now do `prettier --check-debug file` in order to do that since 3 days ago :) https://github.com/jlongster/prettier/commit/4df5250f74953d88fd800464aaa1c861364c252e

**Comment by timjacobi** [comment]
Grand, thank you :)

**Comment by vjeux** [comment]
This is great news for the angular codebase! Hopefully by the end of next week we'll have most of them fixed :)

**Comment by vjeux** [comment]
Note: this only affects comments that are on the first line, comments in the middle are working fine.

**Comment by vjeux** [comment]
Sorry it took a while, just sent #830 to fix this problem!
