### ISSUE TITLE
Prettier removed  parentheses which broke typescript compiling

### ISSUE THREAD

**Issue by AlexanderKositsyn** [prettier/prettier#6602]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAhtgXmwAoBKQgPhIGcYAnASygHNsAfbANwgYBNSA3CAA0ICBhgNo1ZKFx06EAO4AFeQhkpc3PiJAAjOrjABrODADKGY02bJ6AVziiAFjAC2AGwDqLhvGprMDgLDX8GTn80ZHBqGVEmajg6GBUjZndcZAAzXE8k0QAragAPACEjU3MLXHc4ABkmOBy8gpBikotbTzgARQcIeBb85xBrOiS6GOzPZT0MRlhvPhgXZAAOAAZRBYgk7yMMGIW4Sc5m0QBHAfg08U0QXGoAWig4OF4PvTo4a4YftK4DJZJC5EaiJLuBj2OhOCHdPo3Zqg1qjGC4fTLXirZAAJlE9FwDE8tgAwhB3JkYlBoBcQA4kgAVDGaMFJAC+7KAA)
```sh
{
    "tabWidth": 4,
    "useTabs": false,
    "printWidth": 140,
    "semi": true,
    "singleQuote": true,
    "quoteProps": "as-needed",
    "jsxSingleQuote": false,
    "trailingComma": "es5",
    "bracketSpacing": false,
    "jsxBracketSameLine": false,
    "arrowParens": "always",
    "endOfLine": "lf"
}
```

**Input:**
```jsx
type a = () => (string | void);
```

**Output:**
```jsx
type a = () => string | void;
```

**Expected behavior:**
Not expected any changed in code. It change type of 'a'. In input it has one type Function which can returns string or void, but in output it has two types Function | void

**Comment by lydell** [comment]
Hi!

Are you sure about this? As far as I can tell, the parentheses make no difference in this case. See this [TypeScript playground](http://www.typescriptlang.org/play/#code/C4TwDgpgBAhlC8UAUBKBA+ZBnYAnAlgHYDmUAPlAG4D2+AJigNwBQokUARgsmvJjgRLkqtOi2YBjaoRywAjAC5Y3AK6E6EAGZEIYqAHp9UAKK5c1XFlhWIAD0gTgugHSTpsmACYlcRKgxQAESBLFIywLAAzD7c-nxQahrahLqh7hEwACwxfryYcowGRqbmltZQdg5OdK5u4ZyKnKrqWjp6hiZmFlYwNvYQji51shzeTbkBwWn1HNHjPAGJrSliwxEc2fNx+YUdJd3llQPVzkA).

**Comment by AlexanderKositsyn** [comment]
@lydell  thank you. my mistake. close issue. bug in another place in my project
