### ISSUE TITLE
prettier-ignore file pragma

### ISSUE THREAD

**Issue by jasonkuhrt** [prettier/prettier#6606]
I would like the ability to, at the top of my file, add this pragma:

```
// prettier-ignore
```

and the effect be that the file is not modified by prettier.

A pragma of this name already exists, for disabling prettier on single expressions.

Reusing the name is ok because the heuristics to differentiate are clear both from a human and machine perspective: first line, first column.

I know there is `.prettierignore`. But this file may not exist in my project and I am have ad-hoc cases where I want to control things.

Also, from a code gen perspective, from a lib/framework perspective, I may want to employ this pragma.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/issues/3634#issuecomment-364308981, anyway PR welcome
