### ISSUE TITLE
Typescript: Weird formatting with "as" expression in call expression where the left-hand-side starts with "this"

### ISSUE THREAD

**Issue by brainkim** [prettier/prettier#6623]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U++kUAzjPjvAE4CM+AvPe3ACG8AJIdhEdiRgALHIwB0DGOwgAbNXHYAaenLUATXbPkKYggOb5BjfAGUAnlgBimbHigBhCAFsADtAIMGQA3DR0DMz4jHBqqLz4JoxhtPTQUWxaAEwJYALCcGJaElIxcUrQKuqaOno4hrplqGaW1raOLm640N7+gbChNAC+INogEH7dTMigguyqAO4ACnMIjMggggBuEDgGoyAARuyCYADWcDB2fqc4UBbIKuhwYzIwPmoA6nLwjDdgcDsazYOC2bAcGzAjHWYzuMXYMCWJwsPkEyFQgjUMTGACtGAAPABCJ3Olzsgh8cAAMnc4OjMdiQHj8XY7hZNABFdAQeD0rEvEA3djwjYwBx+OCMPI4SYHPzsO4wT57WTIAAcAAYxvKIDFPic-Bt5ZKtFs6WMAI7c+BIibrFA2AC0UDgcAMboOAitOAESMsqL5jJiPhwj3YzzGjDZnOtdKQGP5Y3Mh2VBlVSCySZO9TZvQDKCggQO6BiABVBId7QmYkMhkA)

```sh
# Options (if any):
--parser typescript
```

**Input:**
```ts
function foo() {
  const iter1 = createIterator(this.controller, child, this.tag as SyncFunctionComponent);
  const self = this;
  const iter2 = createIterator(self.controller, child, self.tag as SyncFunctionComponent);
}
```

**Output:**
```ts
function foo() {
  const iter1 = createIterator(this.controller, child, this
    .tag as SyncFunctionComponent);
  const self = this;
  const iter2 = createIterator(
    self.controller,
    child,
    self.tag as SyncFunctionComponent
  );
}
// code snippet
```

**Expected behavior:**

```ts
function foo() {
  const iter1 = createIterator(
    this.controller,
    child,
    this.tag as SyncFunctionComponent
  );
  const self = this;
  const iter2 = createIterator(
    self.controller,
    child,
    self.tag as SyncFunctionComponent
  );
}
```

**Comment by thorn0** [comment]
It's a manifestation of #6450.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/prettier/prettier/issues/6443, thanks for issue

**Comment by evilebottnawi** [comment]
@brainkim feel free to add more examples in original issue

**Comment by brainkim** [comment]
Thanks! I was sure I saw this issue before but couldn’t find it via search. Also thought the difference when using `this` was interesting.
