### ISSUE TITLE
How to resolve the root editorconfig

### ISSUE THREAD

**Issue by CandySunPlus** [prettier/prettier#6630]
The editorconfig find path has been limit in https://github.com/prettier/prettier/blob/master/src/config/resolve-config-editorconfig.js#L12, but my editorconfig is localed on home root, how to resolve it?

in editorconfig https://github.com/editorconfig/editorconfig-core-js/blob/master//src/index.ts#L58, if not set the root options, it will find config file until system root  path like prettier, shoud we remove the root props in options?

**Comment by CandySunPlus** [comment]
how about add a parameter to control it

**Comment by thorn0** [comment]
[We don't add parameters](https://prettier.io/docs/en/option-philosophy.html). 😆

**Comment by thorn0** [comment]
I'd say it'd be great to remove this behavior and encourage people to use `root = true` in their `editorconfig` files and/or the `--no-editorconfig` option that Prettier already has (if you don't like how editorconfig works, simply don't use it).

**Comment by CandySunPlus** [comment]
ok, I'll add .editorconfg to my project root now

**Comment by evilebottnawi** [comment]
@CandySunPlus can we close issue or other problems still exits?
