### ISSUE TITLE
Markdown - Preserve escape sign in code field without prettier-ignore

### ISSUE THREAD

**Issue by P1X3L0V4** [prettier/prettier#6636]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAmhArhsAQyg1wGc4M4yiAHSsgSwHMTGTCMyYAnd5jABtGAa0rsMxKgA9CAW1qDKAIziCIAdwA6USFG4ZGcgQF4MWkAB4AJowBuBQYTJkTW9yDVw5CGO4sY1oQwhAC08NIwbh7w3P4gAHwWANw6egYwkRhmAOQAkn5aOWSSGMosGACecIQ8OckgADQgELQwjNBkyKC1PJoACrUIXSiEdhCM1k0gyjyEYGIwAMq08-zIvLhwzQAWMHKCAOo7jLGrYHBLw6f2p5XI4C7T7BQ8MP1zzHKEyABmhIIKM0AFZkaQAITmCzgy3kcAAMuw4H8AUCQKDpEt+EoAIq4CDwFGA7YgVY8V4PZSEZSVdRQaa0PiwQ6TGA7ZAADgADM1GRAKIc5rQHozqHAeHZkc0AI74+AfVojEDOUJQOBwawa6Y8OCyxg6j6EL4-JD-YnNChyRgbHhbC3YuB4gnI02okkhZQs6xs5AAJmavEIjGEUGYAGEIHJvg8oNApSByHAACrUkZmigAXwzQA)
```sh
# Options (if any):
--single-quote
```

**Input:**
```javascript
// You can use escape sign in a string like that:
const img = "<div class=\"element\" data-text=\"test\">";
const txt = 'It\'s a big year';
```

**Output:**
```javascript
// You can use escape sign in a string like that:
const img = '<div class="element" data-text="test">';
const txt = "It's a big year";
```

**Expected behavior:**
There should be an option to preserve escape sign in markdown file code block without using `// prettier-ignore`. Case above shows an instructory markdown file where JavaScript rules are beeing explained and use of `// prettier-ignore` distorts the appearance of the file and force to use another file formatter for `.md` files. Another good option would be to make `// prettier-ignore` comment somehow not visible for the user.

**Comment by evilebottnawi** [comment]
> There should be an option to preserve escape sign in markdown file code block without using // prettier-ignore

https://prettier.io/docs/en/option-philosophy.html

> Another good option would be to make // prettier-ignore comment somehow not visible for the user.

What? It is code, you can handle markdown files before public (using remark)

I don't see markdown in your examples

**Comment by kachkaev** [comment]
Hey @P1X3L0V4 👋

Does this example solve your issue? [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOAnOACAlgZ2wFsBPbAVyjAAsBDKAczgBNtJmd8pcAHHuGEgA6UEQB4AhAFop2HlhgxcmKbgZQIWbDIB8IgAaGAVvhEB6M9gCaEcm3oV8OOPjC1+2fGqh4ftTzAYuIzYADa4ANY4wdgOcAAetEQ8oTgARnChEADuIpBQ+DB4RAzYALzYQiBizLgAbmyhtPj4ZULtIJlwRAgw7VXYzLQwtFLw8TBtHfCF-SB6IADcedCF2DAT5dgA5ACSfULbhP5patgkcLQY28tQhvoiIgCCUKzUmNHHbHSMLNjQcGEd2MpigFmstnsPnITmwLjcHi86l8sQCQRC4SiKLiiWSqWwGSyuSoqyKuBKWyqNXqjWarTmXR6sDmg2Go3GkzmMwOVQWt3yaw2RQqewOR1Rp1KFyuNwMhhAABoQBAeEpVshQFcMDkAApXBD4ZAgWh1CC4ZiKkBpDC0MBRGAAZR4tuCDGQgXIcCV1BgRFCAHVqLgZs6wHAHQbg-VgyQjWAWpbgk4MDAdTaGERaMgAGa0UJOJUmeIAIRtdoEDqScAAMsE4Dm8wWQEWHa7UgBFcgQeAN-NekDOjDJo2ZjARZg5KCW+TBGD+80wajIAAcAAYlfIIE5-TaeEb5C5MHV60qAI5d+BplWGlDNKRQOAsFiWrDn3BYNO0DNZpC5vtKpwiFwd0ME9AC2zgTtu3rX9G37EY0nnZhF2QAAmJVAloXBwkYABhCAiEzI0NAfS0YTgAAVWg0hvP8nAAX3ooA)

**Comment by thorn0** [comment]
@P1X3L0V4 `<!-- prettier-ignore -->` is not a JS comment. It's a markdown comment that you put in front of the whole code block. The reader doesn't see it.

**Comment by evilebottnawi** [comment]
@P1X3L0V4 problem solved?

**Comment by P1X3L0V4** [comment]
Solved! Thank You @kachkaev and @thorn0 
Putting `<!-- prettier-ignore -->` before entire code block works perfectly.
For some reason I belived that I have to put js `// prettier-ignore` before single code line inside code blocks. I guess I misunderstood the documentation.
Thank You for your patience and clarification 💪
