### ISSUE TITLE
[TS] Separate type alias entries using commas instead of semicolons

### ISSUE THREAD

**Issue by mgtitimoli** [prettier/prettier#6655]
Hi there,

Time has passed and new conventions (luckily) have arisen, @calebmer opened an [issue](https://github.com/prettier/prettier/issues/1944) some time ago asking for this and @vjeux [replied](https://github.com/prettier/prettier/issues/1944#issuecomment-306000469) that it was done and then it was rolled back.

A couple of comments later @mafredi said semicolon was used in official docs, and here is when I jump to say this is no longer true.

As you can see in the [new handbook](https://microsoft.github.io/TypeScript-New-Handbook/chapters/everyday-types/#type-aliases), type aliases are written using commas (thankfully), so it could make sense to open this debate again to collect opinions.

I will use the same technique @azz used in [this comment](https://github.com/prettier/prettier/issues/1944#issuecomment-306039315)

Vote here!

:+1: Use commas
:-1: Continue using semicolons

**Comment by bakkot** [comment]
(I am pretty sure this is about [_object types_](https://microsoft.github.io/TypeScript-New-Handbook/chapters/everyday-types/#object-types), not type aliases.)

As a data point, it looks like [`tslint` still enforces semicolons](https://palantir.github.io/tslint/rules/type-literal-delimiter/). `tslint` is theoretically being deprecated, but at [2 million downloads per week](https://www.npmjs.com/package/tslint) it's obviously still in pretty wide use.

**Comment by mgtitimoli** [comment]
I would suggest don't ever take tslint into account, it's already deprecated and it hasn't been updated with the latest standards.

One example of this, is the fact that it recommends the use of an interface over an object type alias.

![image](https://user-images.githubusercontent.com/4404683/66964126-0c890d80-f04c-11e9-8771-31b22b926852.png)

**Comment by c32hedge** [comment]
Can this be made a configuration option? If I'm not mistaken this would be analogous to the [@typescript-eslint/member-delimiter-style](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-delimiter-style.md) rule available in typescript-eslint, which is more relevant than tslint now that the latter is deprecated.

**Comment by sosukesuzuki** [comment]
If you don't know https://prettier.io/docs/en/option-philosophy.html, please see.
I personally prefer using commas as member delimiter. But, I disagree adding configuration options for this.
However, according to the voting on this PR, using commas seem to be more popular. I think we should consider make member delimiter commas.

**Comment by c32hedge** [comment]
@sosukesuzuki Thanks, hadn't seen that page. Fair enough. The semicolons instead of commas seemed to be the main thing that jumped out as jarring when I just started trying Prettier, so this change would make me a lot happier if not 100% satisfied.

My main point above was that since Prettier's decision on this topic has already gone back and forth at least once, I just want to be able to "lock in" on one style.

**Comment by evilebottnawi** [comment]
`ts` uses semicolons in official guides https://www.typescriptlang.org/docs/handbook/interfaces.html, so we don't need change something or introduce the option for that, you can setup eslint rule and use prettier-eslint if you want change something

**Comment by mgtitimoli** [comment]
I'm back to TS again on a Project and I still believe it would be better to go with commas and limit the usage of semicolons to separate statements, if this is really controversial we could explore the possibility of going with this approach only for type aliases (using commas), and keep interfaces the way they are now (with semicolons).

What do you thing?

**Comment by thorn0** [comment]
@mgtitimoli This isn't going to change. See the reasoning here: https://github.com/prettier/prettier/issues/7719#issuecomment-595497709 and https://github.com/prettier/prettier/issues/7719#issuecomment-595654979.
