### ISSUE TITLE
Browser build causes webpack warning by using require.extensions

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier#6656]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: Browser API 
- Runtime: Node.js 12.11.1 (via webpack) 
- Operating System: macOS 

**Steps to reproduce:**

https://github.com/nickmccurdy/prettier-chrome-extension/tree/bundle-with-webpack

**Expected behavior:**

No warnings

**Actual behavior:**

```
WARNING in ./node_modules/prettier/parser-glimmer.js 1:127549-127567
require.extensions is not supported by webpack. Use a loader instead.
 @ ./ext/src/content/content.js 4:0-52 18:4-17

WARNING in ./node_modules/prettier/parser-glimmer.js 1:127570-127588
require.extensions is not supported by webpack. Use a loader instead.
 @ ./ext/src/content/content.js 4:0-52 18:4-17

WARNING in ./node_modules/prettier/parser-glimmer.js 1:127607-127625
require.extensions is not supported by webpack. Use a loader instead.
 @ ./ext/src/content/content.js 4:0-52 18:4-17
```

**Comment by fisker** [comment]
This is a issue of `handlebars` https://github.com/wycats/handlebars.js/search?q=require.extensions+is%3Aissue&type=Issues

But, seems other builds in `handlebars/dist` don't use `require.extensions` https://github.com/wycats/handlebars.js/issues/1174#issuecomment-179546676

I'll try find other format js that works

**Comment by fisker** [comment]
Hello @nickmccurdy , can you help me test if https://deploy-preview-6658--prettier.netlify.com/lib/parser-glimmer.js works?

**Comment by fisker** [comment]
test on https://github.com/nickmccurdy/prettier-chrome-extension/tree/bundle-with-webpack 

confirmed works


previous build

```text
yarn run v1.19.1
$ webpack
Hash: 5b1ea4c837d35d845165
Version: webpack 4.41.1
Time: 10898ms
Built at: 2019-10-15 6:27:37 PM
  Asset      Size  Chunks                    Chunk Names
main.js  6.22 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = main.js
 [0] (webpack)/buildin/global.js 472 bytes {0} [built]
[16] ./ext/src/content/content.js 12.2 KiB {0} [built]
    + 22 hidden modules

WARNING in ./node_modules/prettier/parser-glimmer.js 1:127549-127567
require.extensions is not supported by webpack. Use a loader instead.
 @ ./ext/src/content/content.js 4:0-52 18:4-17

WARNING in ./node_modules/prettier/parser-glimmer.js 1:127570-127588
require.extensions is not supported by webpack. Use a loader instead.
 @ ./ext/src/content/content.js 4:0-52 18:4-17

WARNING in ./node_modules/prettier/parser-glimmer.js 1:127607-127625
require.extensions is not supported by webpack. Use a loader instead.
 @ ./ext/src/content/content.js 4:0-52 18:4-17
Done in 13.91s.
```

new file

```text
-rw-r--r-- 1 fisker 197121  138523 Oct 15 18:28 parser-glimmer.js
-rw-r--r-- 1 fisker 197121  137717 Oct 10 15:44 parser-glimmer.js-old
```

```text
yarn run v1.19.1
$ webpack
Hash: e22a1b3beec5a295f98a
Version: webpack 4.41.1
Time: 3879ms
Built at: 2019-10-15 6:28:43 PM
  Asset      Size  Chunks                    Chunk Names
main.js  6.22 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = main.js
 [0] (webpack)/buildin/global.js 472 bytes {0} [built]
[16] ./ext/src/content/content.js 12.2 KiB {0} [built]
    + 22 hidden modules
Done in 5.08s.
```

**Comment by fisker** [comment]
I don't think we need test for this, what do you think @ydell @nickmccurdy

**Comment by lydell** [comment]
I don’t think a test is needed either.

**Comment by nickmccurdy** [comment]
@fisker @lipis Thanks for the quick fix! Is there going to be a release soon? I'd like to use this for https://github.com/prettier/prettier-chrome-extension/pull/23.

**Comment by lipis** [comment]
We are working hard on the [1.19](https://github.com/prettier/prettier/milestone/32)! As soon as possible :)

**Comment by mochen666** [comment]
> We are working hard on the [1.19](https://github.com/prettier/prettier/milestone/32)! As soon as possible :)

When do you plan to release v1.19?

**Comment by lydell** [comment]
Maybe today.
