### ISSUE TITLE
[TypeScript 3.7] declare modifier on class fields

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#6661]
see https://github.com/microsoft/TypeScript/pull/33509

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMI5wAe8UAJrgEI7AA6UOOZcYGATnDgA5I4BMAVnoBfeiAA0ICFxgBLaJmSh0bNhADuABRUJFKdADcIsshJAAjNujABrODADKXa7KgBzZDDYBXOJIAWMAC2qADq-rLwmM5gcA66kbIGkQCeyODYZq6YcGwwmlZuQejIAGboqDmSAFaYRJRWtvYO6EFwADKucGUVVSC1RA6ubqhwAIreEPA9lX4gzmw5bOkwKVxwmGBssjJmXNuwoSYw-sgAHAAMkvsQOaFWXOn7G7kG3ZIAjpPwBdJ6IFgALRQOBwZimSQcL6yDgFdBFEpIcqzSQ5IKyTw+OaYYajCZTbpI3pzGDocxHMgnZB8SRedCyVDDPAQILFdJQaDvEDeHIAFTJemROWEwiAA)
```sh
--parser typescript
```

**Input:**
```tsx
class C extends B {
  declare p: 25
}

```

**Output:**
```tsx
class C extends B {
  p: 25;
}

```

**Expected behavior:**

same as the input

**Comment by Cryrivers** [comment]
As discussed in #6657, we are waiting for typescript-eslint/typescript-eslint#1086.
