### ISSUE TITLE
Prevent Prettier from breaking lines before comments for .scss

### ISSUE THREAD

**Issue by Simpleqode** [prettier/prettier#6664]
I am using the default Prettier config and have an SCSS map that looks like this: 

```
$spacers: map-merge(
  (
    0: 0,
    1: ($spacer * 0.25), // 4px
    2: ($spacer * 0.5), // 8px
  ),
  $spacers
);
```

Prettier makes it look like: 

```
$spacers: map-merge(
  (
    0: 0,
    1: (
      $spacer * 0.25
    ),
    // 4px
      2:
      (
        $spacer * 0.5
      ),
    // 8px
  ),
  $spacers
);
```
I understand one may want to keep brackets on a new line, so I tried to get rid of them at all and got this: 

```
$spacers: map-merge(
  (
    0: 0,
    1: $spacer * 0.25,
    // 4px
      2: $spacer * 0.5,
    // 8px
  ),
  $spacers
);
```
So it moves the comments on the new line anyway and does something wrong with indentation. Any way this can be fixed with a config? Thanks in advance.

**Comment by lydell** [comment]
Hi!

This cannot be fixed with config – it’s just plain broken :)

I think this is already covered by #4878 and #4659. If so – feel free to add your example to one of those issues!

**Comment by Simpleqode** [comment]
Oh, sorry I missed those. Prettier is so good formatting JS / JSX. If not the issue above and a bit less opinionated HTML formatting (I need more control over line breaks), I'd be happy to use it as a default formatter.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/issues/4659, 

@Simpleqode PR welcome
