### ISSUE TITLE
Should prerrier when arrow function as function param

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#6668]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMAUAdKACPbEAQQAUBJPAczhgDEBLAGznKgDMI8B3BmACzxQuAQwBOVNEQA0hfHkwBKPAF4AfHjgAPAA5wwWHWNowGcMQDoa9Zqw4Qlii8YBW+mGgswIAFX5iIbkwoOG48HwBPPQBRMQCxHBBtPQM8AAN2W1IRATS8bzwAIzg8ETwMMQYoKlkqCBh0gFcoABM4TJCWtKJFRVxFAG4QaRAIHVNoNGRQcQDubOMoKZQRADcIBhbhkEKxETAAa1oAZR19qqpkGDFGuBH+GABbJgB1fj44NDOwOGOEND4DFWfAiyHAaCmIyqaHMMFIeyojxEyHYIiYMJGLjQWgAQntDicRI84AAZKpwFFojEgLFaY4XFgARUa9QpSFR6LuIDOYhhYjBhRExSY2yMVRgL02AmQAA4AAwjIwQGEvPY6MFGT7mVYUkYARxZ8HhY2WIBEaAAtCE4G0tiNjAaGMZ4SJEcj2VSuTDHgwrjcvQy4MzWZTOSMYELJS1pUgAEzhvbMC4AYQgjyRYOEIW2jRhPiFyw5MIAvsWgA)
```sh
--parser babel
```

**Input:**
```jsx
test(
  "API getFileInfo with no args", 
  () => expect(prettier.getFileInfo()).rejects.toThrow(new TypeError("expect `filePath` to be a string, got `undefined`"))
);
```

**Output:**
```jsx
test("API getFileInfo with no args", () =>
  expect(prettier.getFileInfo()).rejects.toThrow(
    new TypeError("expect `filePath` to be a string, got `undefined`")
  ));

```

**Expected behavior:**

maybe

```js
test(
  "API getFileInfo with no args", 
  () => expect(prettier.getFileInfo()).rejects.toThrow(
    new TypeError("expect `filePath` to be a string, got `undefined`")
  )
);
```

or

```js
test(
  "API getFileInfo with no args", 
  () => expect(prettier.getFileInfo())
      .rejects
      .toThrow(new TypeError("expect `filePath` to be a string, got `undefined`"))
);
```

this code is from my commit https://github.com/prettier/prettier/pull/6665/commits/5c2c2ac518be5d819b7ec9cecf8c2b329220f46e

**Comment by evilebottnawi** [comment]
It is expected, we already discussion about this in past, but maybe we should improve this, need dicussion

**Comment by fisker** [comment]
I didn't found any related, is its already discussed. you can close it

**Comment by evilebottnawi** [comment]
@fisker here logic https://github.com/prettier/prettier/blob/master/src/language-js/utils.js#L330

**Comment by fisker** [comment]
I've tried to add this to https://github.com/prettier/prettier/blob/master/src/language-js/utils.js#L330

```js
      if (
        n.arguments.length >= 2 &&
        n.arguments.some(
          argument =>
            isFunctionOrArrowExpression(argument) ||
            isFunctionOrArrowExpressionWithBody(argument)
        )
      ) {
        return false;
      }
```

some diff

```diff
-   test(`{pass: false} expect(${small}).toBeGreaterThanOrEqual(${big})`, () => {});
+   test(
+     `{pass: false} expect(${small}).toBeGreaterThanOrEqual(${big})`,
+     () => {}
+   );

- it("does something really long and complicated so I have to write a very long name for the test", () => {
-   console.log("hello!");
- });
+ it(
+   "does something really long and complicated so I have to write a very long name for the test",
+   () => {
+     console.log("hello!");
+   }
+ );


- it("does something really long and complicated so I have to write a very long name for the test", function myAssertions(done) {
-   console.log("hello!");
- });
+ it(
+   "does something really long and complicated so I have to write a very long name for the test",
+   function myAssertions(done) {
+     console.log("hello!");
+   }
+ );

- it("does something quick", () => {
-   console.log("hello!");
- }, 1000000000);
+ it(
+   "does something quick",
+   () => {
+     console.log("hello!");
+   },
+   1000000000
+ );

- it("succeeds if the test finishes in time", () =>
-   new Promise(resolve => setTimeout(resolve, 10)));
+ it(
+   "succeeds if the test finishes in time",
+   () => new Promise(resolve => setTimeout(resolve, 10))
+ );
```

what you guys think? I like the new one, more readable

**Comment by lydell** [comment]
Here’s the original PR that disabled breaking for test functions: #842

**Comment by fisker** [comment]
read the linked pr and issue, we should keep them as it is, closing this
