### ISSUE TITLE
Spaces are not being used to align variables in Javascript var statement

### ISSUE THREAD

**Issue by skerit** [prettier/prettier#6669]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlNTAG4CGATvgEYA2TANLffkH4AXnAZw2AXnwBGANy0AviB4gIAB1zQiyUKxYQA7gAVWCHSiYMIOACYqQ7FkzABrODADK6lzigBzZBgWdDhVAAsYAFtOAHVwnGIfMDhPc0ScBkSAT2RwIh1VPyIJGGNnfyimZFQmThLVACsiAA8AIWc3D08mKLgAGT84GrqGkGaWzz9-TjgARXQIeBH6sJAfFhKWPPYmdmzOaAd1Fj8YWLsYcOQADgAGVROIEtjndTyTuC3xBwBHRfg5Q0FhATCIAFooHA4LYYQ4WHB-jgEeUmJVqkhaqtVCUojggiE1kRprMFkthkhgqFVDA9hdbFdkAAWGnOHCcaYAYQgUSqeSg0GGqnQJQAKnsLFS4IpFEA)
```sh
--parser babylon
--single-quote
--tab-width 4
--use-tabs
```

**Input:**
```jsx
function test() {
	var bla,
	    zever = 1;
}
```

**Output:**
```jsx
function test() {
	var bla,
		zever = 1;
}

```

**Expected behavior:**

The original tab whitespace directly in front of `zever` is used for positioning, not for indenting.
Prettier should NOT replace that with a tab because it breaks the positioning (as you can see on this page, where tabs are 8 characters wide)

**Comment by evilebottnawi** [comment]
I think you have mistake in example, do you mean [this](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlNTAG4CGATvgEYA2TANLffkH4AXnAZw2AXnwBGANy0AviB4gIAB1zQiyUKxYQA7gAVWCHSiYMIOACYqQ7FkzABrODADK6lzigBzZBgWdDhVAAsYAFtOAHVwnGIfMDhPc0ScBkSAT2RwIh1VPyIJGGNnfyimZFQmThLVACsiAA8AIWc3D08mKLgAGT84GrqGkGaWzz9-TjgARXQIeBH6sJAfFhKWPPYmdmzOaAd1Fj8YWLsYcOQADgAGVROIEtjndTyTuC3xBwBHRfg5Q0FhATCIAFooHA4LYYQ4WHB-jgEeUmJVqkhaqtVCUojggiE1kRprMFkthkhgqFVDA9hdbFdbjTnDhONMAMIQKJVPJQaDDVToEoAFT2FixJUUiiAA)?

**Comment by skerit** [comment]
@evilebottnawi  No, it's correct :) I want to indent with tabs, but position with spaces. (Which the documentation says it should be doing, anyway)

**Comment by lydell** [comment]
Hi, @skerit!

Prettier doesn’t do alignment in general, because it causes unnecessary git diff.

Let’s say we _did_ do alignment, and you had this:

```js
var one = 1,
    two = 2,
    three = 3;
```

And now you change to `const`:

```js
const one = 1,
      two = 2,
      three = 3;
```

_All_ of the lines suddenly changed, even though you really only updated one!

So instead, Prettier _indents_ each item one level in var/let/const statements.

> Which the documentation says it should be doing, anyway

What part of the documentation are you referring to?

**Comment by skerit** [comment]
Sorry for the very late reply!

Someone on my team keeps on using prettier, while the rest of us don't.
Whenever he commits something, ALL the spaces get turned into tabs, which pollutes the diff a lot more :)

Also, the `var`/`const` example isn't really complete, because when you use tabs it would actually look like this...

When using `var`:

```js
var one = 1,
    two = 2,
    three = 3;
```
When using `const`:
```js
const one = 1,
    two = 2,
    three = 3;
```

And that's exactly the reason why spaces are used for positioning the text.
Using spaces for positioning allows everyone to use their preferred tab width without breaking the actual flow of the file. When you use tabs for positioning, things just break.

Is someone would switch to a tab width of 8, suddenly this would look like this:

```js
const one = 1,
        two = 2,
        three = 3;
```

These are subtle examples, of course.

Anyway, indentations aren't the only place where positioning is broken. Object literals get mangled, too.
Take this for example:

```js
{
	str           : 'string',
	number        : 1,
	function_call : hello()
}
```

Prettier turns this into:

```js
{
	str: 'string',
	number: 1,
	function_call: hello()
}
```

Which I do not consider to be prettier at all, but that's subjective anyway :)

I understand these are **hard** things to get to work for a language like JavaScript. So I tried to add a `.prettierignore` file in order to forcibly disable it for everyone, but it somehow still happens :/

Regarding the part of the documentation:
I interpreted this line:

> (Tabs will be used for indentation but Prettier uses spaces to align things, such as in ternaries.)

on https://prettier.io/docs/en/options.html#tabs as it to actually use spaces for positioning.

**Comment by lydell** [comment]
> Someone on my team keeps on using prettier, while the rest of us don't.
Whenever he commits something, ALL the spaces get turned into tabs, which pollutes the diff a lot more

Then you have a very simple solution to your problem: Ask this person to stop using Prettier! Tell them that it causes unnecessary diff which makes PRs harder to review and increases the risk of merge conflicts.
