### ISSUE TITLE
PyYaml support 

### ISSUE THREAD

**Issue by rickstaa** [prettier/prettier#6674]
I was wondering if there is a way to stop the formatter from formatting custom tags? I currently use the [PyYaml](https://pypi.org/project/PyYAML/) `!include` in my .yaml file but the formatter keeps removing the linebreak (See gif below). I tried to add the tags I used to the custom tags settings variable.

```
"yaml.customTags": [
	"!secret scalar",
	"!include scalar",
	"!include_dir_merge_named scalar"
],
```

![formatting error](https://user-images.githubusercontent.com/17570430/66955592-f6d31280-f062-11e9-989e-b6ccc685e87d.gif)

**Prettier 1.18.2**

**Input:**
```yaml
parameters:
  !include ./_cfg/gqcnn_parms.yaml
```

**Output:**
```yaml
parameters: !include ./_cfg/gqcnn_parms.yaml
```

**Expected behaviour:**

```
parameters:
  !include ./_cfg/gqcnn_parms.yaml
```

**Downstream issue:**
I filed a formatting [issue](https://github.com/redhat-developer/vscode-yaml/issues/234) at the `vscode-yaml` extension yesterday. They, however, stated that they use the prettier formatting for their code formatting.

**Comment by lydell** [comment]
Hi!

I think this answers your question: https://github.com/prettier/prettier/issues/5581#issuecomment-459417515

**Comment by rickstaa** [comment]
@Iydel. Thanks for your answer. So if I understand it correctly the `!include` tag, which is a template tag of the `PyYaml` module is not yet supported and thus recognised by prettier formatter. What I am wondering if there is a way to set a `prettier.do_not_format` dictionary argument such that a line containing a `!include!` tag or any other template tags gets ignored by the prettier formatter?

**Comment by rickstaa** [comment]
> Hi!
> 
> I think this answers your question: [#5581 (comment)](https://github.com/prettier/prettier/issues/5581#issuecomment-459417515)

@Iydel . Thanks for your answer. So if I understand it correctly the `!include` tag, which is a template tag of the `PyYaml` module is not yet supported and thus recognised by prettier formatter. What I am wondering if there is a way to set a `prettier.do_not_format` dictionary argument such that a line containing a `!include!` tag or any other template tags gets ignored by the prettier formatter?

**Comment by evilebottnawi** [comment]
@rickstaa unfortunately no, i think better create plugin for non standard syntaxes or we should implement this https://github.com/prettier/prettier/issues/4424

**Comment by rickstaa** [comment]
@evilebottnawi Thanks for the response! As I currently only use the `!include` syntax of the `pyyaml` templates I will manually re-editing my files after each format. If in the future I start to use more `pyyaml` templates I will create a plugin.
