### ISSUE TITLE
TypeScript: incorrectly removing a question mark when the key is member expression in a optional computed method

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#6678]
This is mentioned on https://github.com/prettier/prettier/pull/6601#issuecomment-541992951, and also we can't fix this without fixing https://github.com/typescript-eslint/typescript-eslint/issues/1097.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOA2gEboBOAdLXQLoD8AFAJTEC+ZvEABoQEAA4wAltEzJQ9OhADuABXoJZKdADcIkgCbCQ1OujABrODADKYs5KgBzZDDoBXOCIAWMALaoAdS9JeEw7MDhrDRDJbRCAT2RwbCMHTDg6GBVTR190ZAAzdFR0kQArTAAPACFTCytrdF84ABkHOELi0pAKyusHR1Q4AEU3CHhOks8QOzp0uiSYeLE4TDA6SQkjMQ3YAIMYL2QADgAGER2IdIDTMSSd1YztDpEARzH4bPFNECwAWigcDg+mBRjocHeknB2XQuXySCKUxE6V8khc7mmmAGQ1G4w6CK60xg6Go+30h2QACYRK50JJUAMAMIQXx5JJQaAvEBudIAFRJmkR6V4vCAA)
```sh
# Options (if any):
--single-quote
```

**Input:**
```ts
class Foo {
  [bar.bar]?() {}
}
```

**Output:**
```ts
class Foo {
  [bar.bar]() {}
}
```

**Expected behavior:**
(Same as input)
```ts
class Foo {
  [bar.bar]?() {}
}
```

**Comment by polRk** [comment]
And this
<img width="433" alt="Снимок экрана 2019-11-08 в 8 11 09 PM" src="https://user-images.githubusercontent.com/39828645/68496744-13c6c400-0264-11ea-8d84-0b17b854a85e.png">
typescript 3.7.2

**Comment by thorn0** [comment]
Fixed in the parser. Needs tests.
