### ISSUE TITLE
[HTML] Some types of tags get wrapped incorrectly

### ISSUE THREAD

**Issue by zposten** [prettier/prettier#6698]
Prettier wraps some kinds of html tags incorrectly, putting their closing delimiter on a different line than the rest of the tag.  You can make prettier not do this by formatting it yourself, but it's time consuming to do so when prettier has already awkwardly formatted the tag. 

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zU55qARhABMAnp27dUAgJYA3cmDoBDAM5KAvExCTyAd0l065BQIHkaCqELmKVcJVTgAnOORgRTCgNbOADk5gxJRx0HBW8XSmc4OjgaBBgNBgEQgDMYJVQAeilpUTFUJQBXXitlNQ0tXX1DY3cLEps7CKcXNzMvcl84f0CHYNDwyOjY2ASkhVT0jMLeXPEFerLNHT0DIxMzOvlS23tm13d2zu6g7RCwmAjyKJi40ZS0zIVZ8hYxHnmtlXUlytWajcsnyUOyazn2bR8fgCJzOAyuQ1uIGe3DGE1eeQyT3RmX4wk4mXYjBYIAANCAIN4AtAlMhQAoHA4INpiPSEDSUAppBBJAJSSBeCEwF4YABlbwKMCSKAAc2QMAcBTgZMJAHVKJJ4EpxWA4CK2RqZBqhMhwCo+VLgQ4YMQQtKzMhkgo6MCyQArJQADwAQoLhSKFLEADJSuAOp0ukDuj0iqXS6IARQKEHgYedSpA4oclpNhL5vilMBVPIuyAAHAAGMm+CDAlVnE2dS3SUNkgCOSfgNop7JAygAtFA4HABMO+U525InDaFHaFKmI8CaJI5Qr00pYwmO6GkI602SYApeEWBCWkAAmfchPSx3AQGj2lBQaAtkAFYH4Q-s3fAgC+P6AA)
```sh
--parser html
```

**Input:**
```html
<!DOCTYPE html>
<html>
  <body>
    <div class="i will add many classes here to make prettier wrap the element">drafts</div>
    <sub class="i will add many classes here to make prettier wrap the element">drafts</sub>
    <a class="i will add many classes here to make prettier wrap the element">drafts</a>
    
    <a class="i will add many classes here to make prettier wrap the element">
      drafts
    </a>
  </body>
</html>

```

**Output:**
```html
<!DOCTYPE html>
<html>
  <body>
    <div class="i will add many classes here to make prettier wrap the element">
      drafts
    </div>
    <sub class="i will add many classes here to make prettier wrap the element"
      >drafts</sub
    >
    <a class="i will add many classes here to make prettier wrap the element"
      >drafts</a
    >

    <a class="i will add many classes here to make prettier wrap the element">
      drafts
    </a>
  </body>
</html>

```

**Expected behavior:**

I expect all three tags to be wrapped in the way that the `div` tag gets wrapped, without having to format the tag myself.

**Comment by thorn0** [comment]
This happens for a reason and can be controlled with the option `--html-whitespace-sensitivity`. Please read more [here](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting).

**Comment by AFu-1993** [comment]
in `.prettierrrc.json`
``` json
{
"htmlWhitespaceSensitivity": "css"
}
```
in `xxx.vue`
``` html
<!-- display: inline -->
<div class="detail-content-box">{{
                data_content.subscribe && data_content.subscribe.msg_content
 }}</div>
```
