### ISSUE TITLE
Prettier typescript inserts extraneous semicolons in if/else condition

### ISSUE THREAD

**Issue by webcoderkz** [prettier/prettier#6714]
file.ts:

```
  private validateField(fieldStateType: string, e: string) {
    if (fieldStateType === 'msisdnState') {
      ;(this as any)[fieldStateType] = e.length == 9
    } else {
      ;(this as any)[fieldStateType] = e.length > 0
    }
  }
```

Why does it inserts semicolons before `(this as any)`?

PS Already seen these topics:

1) https://github.com/prettier/prettier/issues/1244
2) https://github.com/prettier/prettier/issues/4193

There's no actual answer on this issue.

**Comment by thorn0** [comment]
The actual answer has been given multiple times in those exact issues you linked to and in the ones that are linked from there:
- https://github.com/prettier/prettier/issues/4193#issuecomment-375486578
- https://github.com/prettier/prettier/issues/736#issuecomment-291934981

**Comment by webcoderkz** [comment]
@thorn0:

> This is intentional behavior, because if you put another line before the destructuring (maybe a function > call, for example), the [ will be interpreted as the beginning of a property access expression instead of a > destructuring assignment. Adding the ; prevents this from happening.

Well, you think it's correct even for my case? It's working well without these semi-colons.

**Comment by thorn0** [comment]
Yes, I do think so. Let's take your code without semicolons and try adding a statement in the beginning of the `if`:
```ts
  private validateField(fieldStateType: string, e: string) {
    if (fieldStateType === 'msisdnState') {
      console.log('foo')
      (this as any)[fieldStateType] = e.length == 9
    } else {
      (this as any)[fieldStateType] = e.length > 0
    }
  }
```
Guess what's going to happen when you run this code or [format it with Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOADgE4CWAbuvDo6rQCZNx61yrsAKAGa9+AZRhcAKgE9KcJDkww6UAOYAaHAqUra6gJTEyFCrSE5ho9hOly4OALzOcAcgC2mWpnZRb8VyNSclMKSChMCFQ4ADpUCDUBVyFCQJNQyxgAC28cLDyoGQMAbRE+G0l4WXkAXSdtOIQ1bKdHHABOdIoAX21UTAdgjMyc3Hz0QpKy8Uq4arg6ttjo9RaAPhwABi6cbvS9qG6QDRAIShhaaExkUHRqaggAdwAFO4RrlHR6CA5jkAAjajoMAAazgMDElGB+jUyBUAFc4CcsjB3KgAOo5eCYKFgOBid60C70IkyZDgbB-fQDagwZ5AtTudDIITofpIkAAK0wAA8AEJA0HgsTodxwAAy+jgLLZAxO3J5Yhh0QAivCIPAZeyTlDqDTyTB7JgwHRzn8aPoYOiONlkAAOTY6h4DdFAyjkmhwGn0aUnACO6vg9LOHxAWAAtFA4HB2DG-tQ4AHaAn6ehGcykKztSABu5aFq5TnlXA1RrpZnZRzJP9rexbUgAEwnFToWhsdQAYQg7iZ5Kg0F9IHhAyk6H+HyzA263SAA).

**Comment by webcoderkz** [comment]
Ok, got your point, thanks.

**Comment by thorn0** [comment]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOADgE4CWAbuvDo6rQCZNx61yrsAKAGa9+AZRhcAKgE9KcJDkww6UAOYAaHAqUra6gJTEyFCrSE5ho9hOly4OALzOcAcgC2mWpnZRb8VyNSclMKSChMCFQ4ADpUCDUBVyFCQJNQyxgAC28cLDyoGQMAbRE+G0l4WXkAXSdtOIQ1bKdHHABOdIoAX21UTAdgjMyc3Hz0QpKy8Uq4arg6ttjo9RaAPhwABi6cbvS9qG6QDRAIShhaaExkUHRqaggAdwAFO4RrlHR6CA5jkAAjajoMAAazgMDElGB+jUyBUAFc4CcsjB3KgAOo5eCYKFgOBid60C70IkyZDgbB-fQDagwZ5AtTudDIITofpIkAAK0wAA8AEJA0HgsTodxwAAy+jgLLZAxO3J5Yhh0QAivCIPAZeyTlDqDTyTB7JgwHRzn8aPoYOiONlkAAOTY6h4DdFAyjkmhwGn0aUnACO6vg9LOHxAWAAtFA4HB2DG-tQ4AHaAn6ehGcykKztSABu5aFq5TnlXA1RrpZnZRzJP9rexbUgAEwnFToWhsdQAYQg7iZ5Kg0F9IHhAyk6H+HyzA263SAA)
```sh
--parser typescript
--no-semi
```

**Input:**
```tsx
class Foo {
  private validateField(fieldStateType: string, e: string) {
    if (fieldStateType === 'msisdnState') {
      console.log('foo')
      (this as any)[fieldStateType] = e.length == 9
    } else {
      (this as any)[fieldStateType] = e.length > 0
    }
  }
}
```

**Output:**
```tsx
class Foo {
  private validateField(fieldStateType: string, e: string) {
    if (fieldStateType === "msisdnState") {
      console.log("foo")(this as any)[fieldStateType] = e.length == 9
    } else {
      ;(this as any)[fieldStateType] = e.length > 0
    }
  }
}

```

**Comment by webcoderkz** [comment]
Why it doesn't put semicolon `console.log("foo")(this as any)[fieldStateType] = e.length == 9` after console?

**Comment by thorn0** [comment]
Because that's how JS works. Please google "automatic semicolon insertion".
