### ISSUE TITLE
Break line when arguments are in functions are too long

### ISSUE THREAD

**Issue by algomaster99** [prettier/prettier#6716]
**Prettier 1.18.2**
[Playground Link](N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoByAZV3XwENsBZBAVwHoALOAGwAc5sSAaAAREAlIIC8APkHAAOlEGD0WPIVLoAZtUYcYA4WKkz5ixbhhETpxbJAAVVtggB3DIN5Psg3Bu)

**Input:**
```jsx
    it(
      "Throws error if item has source: false and doesn't have children",
      () => {
...
```

**Output:**
```jsx
    it("Throws error if item has source: false and doesn't have children", () => {
...
```

**Expected behavior:**
Prettier should have an option to leave it as it is since the string is too long.

The current workaround is using `// prettier-ignore`. What is suggested?

**Comment by lydell** [comment]
Hi!

Prettier ignores line length when printing test function since it was a commonly requested behavior. See:

- https://prettier.io/docs/en/rationale.html#testing-functions
- #159
- #953
- #1369
- #4293
- #5081

**Comment by shcheklein** [comment]
@lydell thanks for the quick response! Do you know by chance how do people integrate this behavior with `eslint` for example? Does it mean that we have to write some meta `//eslint-ignore-next-line`?

Also, is there a guide to decide which setting can be exposed as an option and which is not? Just trying to understand the decision making process and general philosophy behind the project. Thanks, again!

**Comment by lydell** [comment]
We recommend turning off all ESLint rules that conflict with Prettier: https://prettier.io/docs/en/integrating-with-linters.html

Option philosophy: https://prettier.io/docs/en/option-philosophy.html
