### ISSUE TITLE
Operators in control statements should behave similar to ternary expressions

### ISSUE THREAD

**Issue by kripod** [prettier/prettier#6720]
As suggested [in the Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript#control-statements), the logical operator should begin the line in control statements, similar to how ternary expressions with long values behave:

```js
const something = someVeryLongVariableName === 'condition'
  ? anotherLongVariable
  : justToKeepTheExpressionLongEnoughToWrap
```

> Why? Requiring operators at the beginning of the line keeps the operators aligned and follows a pattern similar to method chaining. This also improves readability by making it easier to visually follow complex logic.

A simple example (see the guide linked above for more):

```js
// bad
if (
  foo === 123 &&
  bar === 'abc'
) {
  thing1();
}

// good
if (
  foo === 123
  && bar === 'abc'
) {
  thing1();
}
```

**Comment by thorn0** [comment]
Duplicate of #3806?

**Comment by kripod** [comment]
@thorn0 Possibly, sorry for missing it during search.
