### ISSUE TITLE
Is our dependabot setting correctly?

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#6742]
some deps should be taking care by bot.

eg: `rollup` `rollup-plugin-alias` `@babel/core`

**Comment by lydell** [comment]
> some deps should be taking care by bot

Sorry, I don’t understand what this means?

**Comment by fisker** [comment]
dependabot should already send PRs to update `rollup` etc

**Comment by brodybits** [comment]
I recall reading somewhere that dependabot is limited to 5 PRs at first, by default. Unfortunately I don't understand it so well.

**Comment by fisker** [comment]
There was a message says that https://github.com/prettier/prettier/pull/6618 but I think this can be configured

**Comment by thorn0** [comment]
We need to close the PRs we aren't going to merge, probably using commands like `@dependabot ignore this dependency`.

**Comment by fisker** [comment]
No, we don't need to do that, on dependabot site  there should be settings. Was it on @lipis account?

**Comment by fisker** [comment]
I always use config file https://github.com/fisker/promisify-file-reader/tree/master/.dependabot

**Comment by thorn0** [comment]
I have access to its dashboard. Its update schedule is set to "Weekly update". I guess this is the reason.

**Comment by lipis** [comment]
I changed it to daily.. if we'll have bunch of noise we'll revert it to Weekly.

**Comment by lipis** [comment]
Let's reopen it if we'll have issues in the next few days
