### ISSUE TITLE
matching none-js (and .js files inside `templates` dir) files outside of node_modules

### ISSUE THREAD

**Issue by xxyyzz2050** [prettier/prettier#6743]
I want to match all none-js files, and all files inside `templates` folder including .js files
and totally exclude node_modules

please don't suggest extended patterns
i.e:  {!(node_modules/**), !(*.ts), templates/**}
because it will run the glob multiple times, causing to include node_modules in the other extended patterns

also !(node_modules/**) not works
and !(node_modules)/** cannot be used with files, i.e: !(node_modules | *.ts)/**

examples:
node_modules/some-module/file.js (not matches: inside node_modules)
dir/subdir/file.ts (not matches: .ts)
dir/subdir/files/file.ts (matches: .ts file, but inside files/ dir)

**Comment by lydell** [comment]
Hi!

I’m afraid I don’t understand what you mean. Could you please:

1. Show what your file and folder structure looks like.
2. What Prettier commands / config you tried.
3. What happened and what you want to happen.
