### ISSUE TITLE
bug(*.ts): print-width 80 not being respected

### ISSUE THREAD

**Issue by jLouzado** [prettier/prettier#6746]
**Prettier 1.18.2**
```sh
--no-bracket-spacing
--parser typescript
--no-semi
--single-quote
```

**Input:**
```tsx
const style = css.sheet({
  headerContainer: {
    background: `linear-gradient(104deg, ${
      config.theme.jssVariablesNewTheme.headerGradientFrom
    } 50%, ${config.theme.jssVariablesNewTheme.headerGradientTo} 50%)`,
    display: 'flex',
    flexDirection: 'column',
    zIndex: `${ZIndex.TOOLBAR}`
  }})
```

**Output:**
```tsx
const style = css.sheet({
  headerContainer: {
    background: `linear-gradient(104deg, ${config.theme.jssVariablesNewTheme.headerGradientFrom} 50%, ${config.theme.jssVariablesNewTheme.headerGradientTo} 50%)`,
    display: 'flex',
    flexDirection: 'column',
    zIndex: `${ZIndex.TOOLBAR}`
  }
})
```

**Expected behavior:**
Works fine in v1.17.0, as seen in the [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEGCeAbOTAXkzDTQDo0ALOOGACmAB0pNNaBDAEzgCcAwtBicAllH5JMLNu0wAjTmADWAcz4QArlG5SABnnFxOfALTqeohIwCMABgAsvVQBpMAEhly5kKADNRVQoYWgBbOAoAK3IANRNRTnkCNAA5OAB3ABUwiK5ePgBxPktrADENUNZvAF9MAFY7AFI3T18AoJC4cKjY+MTktKycijz+IpLYTIhahsaASj0XKrluUTQABzxOHCkAcj8CAA9dpdl2A7hDgBFRPjgwGFFoPcg8TVCoE+X2AC8ASR0l30ngAWgDeIcKJkAPLQgAyACEAIIAJWqemW1WqcxALhAEHWj3QyFAJg06QACiYEGhkCBOAA3CCibi4kDyYoqegAZXWSnEqmQfk4eDQcDx1BgoTwAHVqKJ4BslHBuTSFaIGQqcHSyLS8eIxXwYBTiqpQpwhSKxXjoocEZzlDzOOE4UZLaLxSBbdyBQQAIqaCDwd3WkB8viGukwHDrOBoMB8USEtnrROwGUskLIAAcdjxqYgYplxXWdNTcf4DLgbIAjoH4CaCbSUJw0KYJHBeKy8Xc67c4CbOGaLUhhR68WLQqIQ560L64AGg9WkDA+JpPSJ5BnuFmkAAmPGrsSGKCqIShc10qDQat4zRizKJZtjsVYoA)
```tsx
const style = css.sheet({
  headerContainer: {
    background: `linear-gradient(104deg, ${
      config.theme.jssVariablesNewTheme.headerGradientFrom
    } 50%, ${config.theme.jssVariablesNewTheme.headerGradientTo} 50%)`,
    display: 'flex',
    flexDirection: 'column',
    zIndex: `${ZIndex.TOOLBAR}`
  }
})

```

**Comment by lydell** [comment]
Hi!

This was changed in 1.18: https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay

See #5979 and all the issues that link to it.
