### ISSUE TITLE
Can't use &excl; HTML entity: unknown entity "excl"

### ISSUE THREAD

**Issue by humphd** [prettier/prettier#6749]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zrlcAhgCadUMAJYw6cBqQAauADLlSsUQE9y+OAGcYqAPQixElru79BAIwh9lggA4N8lYRvJPyPKOTgAPMHR40eEWhPJRhlJHIAMm9fAG5dOyMdCytBHXZGEAAaEAgbIKgNZFAeACdSiAB3YjKEIpQeADcIYT5skDNSnjAAazgYAGUbbuEoAHNkGFKAVzgcjIB1R3gNYbA4AbrRYUaVZHANIpzRjThSmGIusYDkADMeOlOcgCsNLwAhLt7+gf84WVGcDuDyeIFeXgGozG4gAitMIPBgY85iBhqVTqV9hl2jZSqMYAtWjBKMgABwABhyuIgpwWXRs+1xmjOjSBOVKcAAjtNhBzLjxrjwkaDTjRhJMZiiNFDYfDEUh7sicjAeGZCXxicgAEzKrrCOhQ3AQGg3FBQaBskDTU74VX1RWnAC+jqAA)
```sh
--parser html
```

**Input:**
```html
<!DOCTYPE html>
<html>
<head>
<title>EXCL Entity Test</title>
</head>
<body>
<p>This is an exclamation entity: &excl;</p>
</body>
</html>
```

**Output:**
```html
SyntaxError: Unknown entity "excl" - use the "&#<decimal>;" or  "&#x<hex>;" syntax (7:35)
  5 | </head>
  6 | <body>
> 7 | <p>This is an exclamation entity: &excl;</p>
    |                                   ^
  8 | </body>
  9 | </html>
```

**Expected behavior:**

If I change to use `&#33;` it will work, but I would have thought named entities like this would work.  Maybe supporting them all is beyond the scope of what you want to do?  In case not, I've filed this.

**Comment by lydell** [comment]
Hi!

It seems our HTML parser has intentionally left out a bunch of valid named entities to “keep the compiler footprint low”:

https://github.com/ikatyang/angular-html-parser/blob/3f8475f5244365364b3ea454e2ecd7a5c7989f92/packages/compiler/src/ml_parser/tags.ts#L69-L74

It includes 252 out of 2231 entities listed in https://html.spec.whatwg.org/entities.json as of 2019-10-30.

**Comment by ikatyang** [comment]
Full named entities support is added in [`angular-html-parser`@1.3.0](https://github.com/ikatyang/angular-html-parser/blob/master/packages/angular-html-parser/CHANGELOG.md#130-2019-11-02), updating the parser should fix the issue.
