### ISSUE TITLE
设置了"proseWrap": "never"，为什么还是会换行

### ISSUE THREAD

**Issue by 007GitHu** [prettier/prettier#6763]
我设置了proseWrap属性为never，但是代码还是会换行，给我的感觉还是按照这个属性printWidth: 80来实现的效果

**Comment by y912765390** [comment]
Hello, I don't know why this library is introduced into the Vue project. With this API, the project will not run. Can't find the third party, can you help me? Thank you very much.

**Comment by thorn0** [comment]
Please use the issue template.
