### ISSUE TITLE
代码超过printWidth设定的值，代码是依据什么机制换行的呢

### ISSUE THREAD

**Issue by 007GitHu** [prettier/prettier#6768]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--printWidth 80
```

**Input:**
```jsx
 <hy-text title="测试名称" placeholder="placeholder" model="modle"></hy-text>

$hyapi.model.setGtData(this.modelService, "gt_时间选择框", {numberT: "100"});
```

**Output:**
```jsx
      <hy-text
          title="测试名称"
          placeholder="placeholder"
          model="modle"
        ></hy-text>

  $hyapi.model.setGtData(this.modelService, "gt_时间选择框", {
      numberT: "100"
    });
```

**Expected behavior:**
字符超过80会换行，但是依据什么条件换行呢，是依据标点符号么，比如引号、逗号

**Comment by lipis** [comment]
Can you or someone else translate that to English?

**Comment by 007GitHu** [comment]
What is the mechanism by which the code breaks lines，When a line of code exceeds a fixed width

**Comment by thorn0** [comment]
The mechanism is described here: http://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf
