### ISSUE TITLE
Formatting .mongo files

### ISSUE THREAD

**Issue by aymericbouzy** [prettier/prettier#6769]
I'm trying to format .mongo files in VS Code using prettier/prettier-vscode extension as explained in my PR https://github.com/prettier/prettier-vscode/pull/1009

Here is an example of a .mongo file (it is valid javascript) : 

```js
db.users.find({ someField: { $exists: true } });
```

These files are created by Azure Cosmos DB, an extension for VS Code. Renaming them to .js files doesn't work for me, because then I cannot run the query to the DB, it only works for files with the extension .mongo.

VS Code seems to treat mongo as a different language from javascript or typescript. I would love to open a PR to add support for .mongo files in Prettier : can someone give me a general direction? I'm new to the Prettier codebase.

**Comment by thorn0** [comment]
I guess you need to change [this line](https://github.com/prettier/prettier/blob/56a2cd8a1b809e5f1b9f0f08b0d5bad4bbfd61d1/src/language-js/index.js#L13).

**Comment by thorn0** [comment]
@aymericbouzy Do you have further questions?

**Comment by aymericbouzy** [comment]
Perfect! I'm opening a PR right away. Thank you so much!
