### ISSUE TITLE
Invalid expanding of long arrays in function arguments

### ISSUE THREAD

**Issue by umidbekkarimov** [prettier/prettier#677]
In
```javascript
fn([every, time, see, you, In, the, world, you, always, step, to, my, girl], [back, back, way, back, I, used, to, front, like, Angkor, Wat])
```

Out
```javascript
fn([every, time, see, you, In, the, world, you, always, step, to, my, girl], [
  back,
  back,
  way,
  back,
  I,
  used,
  to,
  front,
  like,
  Angkor,
  Wat
]);
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22fn(%5Bevery%2C%20time%2C%20see%2C%20you%2C%20In%2C%20the%2C%20world%2C%20you%2C%20always%2C%20step%2C%20to%2C%20my%2C%20girl%5D%2C%20%5Bback%2C%20back%2C%20way%2C%20back%2C%20I%2C%20used%2C%20to%2C%20front%2C%20like%2C%20Angkor%2C%20Wat%5D)%5Cn%5Cnfn(%5Bevery%2C%20time%2C%20see%2C%20you%2C%20In%2C%20the%2C%20world%5D%2C%20%5Byou%2C%20always%2C%20step%2C%20to%2C%20my%2C%20girl%5D%2C%20%5Bback%2C%20back%2C%20way%2C%20back%5D%2C%20%5BI%2C%20used%2C%20to%2C%20front%2C%20like%2C%20Angkor%2C%20Wat%5D)%22%2C%22options%22%3A%7B%22printWidth%22%3A87%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by umidbekkarimov** [comment]
I guess this is related:

In
```javascript
const mapChargeItems = fp.flow(
  l => l < 10 ? l: 1, 
  l => Immutable.Range(l).toMap()
);
```

Out
```javascript
const mapChargeItems = fp.flow(l => l < 10 ? l : 1, l =>
  Immutable.Range(l).toMap());
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20mapChargeItems%20%3D%20fp.flow(%5Cn%20%20l%20%3D%3E%20l%20%3C%2010%20%3F%20l%3A%201%2C%20%5Cn%20%20l%20%3D%3E%20Immutable.Range(l).toMap()%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
For your first issue, https://github.com/jlongster/prettier/issues/253 is related.

One idea I had is to not do the array expansion is the previous argument as also an array. It seems like a rule like this to not do the expansion of the function is the previous argument was a function too would work out.

**Comment by umidbekkarimov** [comment]
> For your first issue, #253 is related.

Oh, my bad 😱, I was to lazy to look for 20+ days old issues, thought it's new one.

> One idea I had is to not do the array expansion is the previous argument as also an array. It seems like a rule like this to not do the expansion of the function is the previous argument was a function too would work out.

I don't really understand how AST transformations works in prettier, but, what i understood from second example - it expands from inside, e.g.

```javascript
const mapChargeItems = fp.flow(l => l < 10 ? l : 1, l =>
  Immutable.Range(l).toMap());
```
1st argument fits to width
2nd argument doest fit - so it's get expanded

But what if it go back, expand function, and go in again to check every argument?

Maybe it makes no sense at all 😅 but this what idea came to me when i was playing with `printWidth ` option.

**Comment by vjeux** [comment]
For the second one, in JavaScript you often have a function as last argument and the custom is to inline it. For example

```js
return items.map(function(elem) {
  return elem.key;
});
```

instead of writing

```js
return items.map(
  function(elem) {
    return elem.key;
  }
);
```

So in prettier we first check if the last argument is a function and can be "inlined", if that's not the case, then we put everything on their own line.

**Comment by yamafaktory** [comment]
With #809 this now output:

```js
fn(
  [every, time, see, you, In, the, world, you, always, step, to, my, girl],
  [back, back, way, back, I, used, to, front, like, Angkor, Wat]
);
```

Should we close it @vjeux?
