### ISSUE TITLE
[Typescript] Access modifiers apparently not supported

### ISSUE THREAD

**Issue by jorge-cbqa** [prettier/prettier#6772]
Created a very simple class to demonstrate this issue.
![image](https://user-images.githubusercontent.com/35709525/67988523-e475de80-fbf5-11e9-8209-758d4796bc7a.png)

When I do lint I get this output:
![image](https://user-images.githubusercontent.com/35709525/67988580-0cfdd880-fbf6-11e9-8cf7-802856de8ee9.png)

**NOTICE: 2:12  error    Parsing error: Unexpected token   prettier/prettier**

Here's my .eslintrc.json
`{
  "extends": [
    "airbnb-base",
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint", "prettier"],
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".jsx", ".ts", ".tsx"]
      }
    }
  },
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "parser": "babel"
      }
    ],
    "no-console": 0,
    "@typescript-eslint/no-explicit-any": 0
  },
  "env": {
    "browser": true,
    "node": true,
    "mocha": true
  }
}`

**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI
- Runtime: Node.js 10.17.0
- Operating System: Ubuntu 18.04

**Comment by lydell** [comment]
Hi! This seems to work to me?

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCpyYw7AA6UOOADgE4CWAbuvDgB5I5QCuAtgEZwaAbnIBfEABoQEKjDrRMyUOho0IAdwAKKhIpToGEOgBNJIPjXRgA1nBgBlKlbpQA5shg0ucKQAsYPKgA6r508JhOYHD2umGMYQCeyODYZi6YgjCalq486MgAZuioGVIAVpisAEKWNnb26DxwADIucIXFpSAVrPYurqhwAIpcEPAdJT4gTjQZNMkwCVSEYPSyZrQuMEEmML7IABwADFK0EBlBllTJtISCDO1SAI6j8NkyeiBYALRQcHDGAFmGhwF50EHZdC5fJIIqTKQZHh0DxeKaYfqDEZjdqwzpTGDoPg7Yx7ZAAJiknnQdFQ-QAwhAeHlklBoI8QFwMnhCXo4RlRKIgA)
```sh
--parser typescript
```

**Input:**
```tsx
class Test {
  private x: number;
}
```

**Output:**
```tsx
class Test {
  private x: number;
}

```

**Comment by thorn0** [comment]
@jorge-cbqa Don't add `"parser": "babel"` to the config. With such a config entry, Prettier parses all files as JS. May I ask why did you add it?

**Comment by jorge-cbqa** [comment]
Thanks guys. The problem was indeed the parser. The reason why I missed changing that property is because I created my boilerplate code using the configuration of a JS express project using flow. I'll close the issue.

**Comment by thorn0** [comment]
We'd really like to understand why people end up with such erroneous configuration as we want to improve the configuration story in future releases. In particular, for some reason, people tend to add `parser` to their config. What was your motivation to add it when you wrote that boilerplate?
