### ISSUE TITLE
we need to avoid `CHANGELOG.unreleased.md` conflicts

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#6786]
The workaround is required after the 1.19 release. (ref: https://github.com/prettier/prettier/pull/6354#issuecomment-540074567)

**Comment by lydell** [comment]
I can set that up at the same time as I empty `CHANGELOG.unreleased.md` into the 1.19 blog post.

**Comment by sosukesuzuki** [comment]
thank you:+1:

**Comment by sosukesuzuki** [comment]
This is fixed via #6787
