### ISSUE TITLE
.editorconfig overrides unset default values from prettier config file

### ISSUE THREAD

**Issue by aryzing** [prettier/prettier#6795]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI
- Runtime: v11.10.1
- Operating System: Ubuntu 18.04

**Steps to reproduce:**
As long as there's a `.editorconfig` somewhere in file hierarchy, unset defaults in `prettier.config.js` will be set to whatever is specified in `.editorconfig`. See [reproduction repo](https://github.com/aryzing/repro-prettier-editorconfig).

**Expected behavior:**
When a `prettier.config.js` file is found, the search for prettier's configuration settings stops.

**Actual behavior:**
The search for prettier's final configuration continues to include values from `.editorconfig` anywhere in the filesystem hierarchy.

**Call to action**
Despite the actual behavior being unexpected to me personally, I would suggest to think about whether this is what we actually want and then document it. I'm not so much concerned about the chosen actual behavior, as I am about documenting the behavior to avoid surprises in the future for other users.

**Comment by thorn0** [comment]
This is expected. That's the whole idea of editorconfig. The docs could benefit from an improvement though.

> The search for prettier's final configuration continues to include values from .editorconfig anywhere in the filesystem hierarchy.

I wish it were like this, so that it were consistent with other editorconfig-aware tools. But Prettier actually doesn't climb all the way up the file system. It finds a '[project root](https://www.npmjs.com/package/find-project-root)' and stops there. This part seems to be missing from the docs.

**Comment by aryzing** [comment]
> Prettier actually doesn't climb all the way up the file system

You are right, I must have botched up my trials while reproducing the expected behavior, thanks for clarifying. And yes, an update to the docs much appreciated.

**Comment by thorn0** [comment]
Totally appreciated. Which page of the docs do you think needs updating? Feel free to make a PR.

**Comment by thorn0** [comment]
Closing in favor of https://github.com/prettier/prettier/issues/8044
