### ISSUE TITLE
No matching files. Patterns tried: F:\project\testproject!**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**

### ISSUE THREAD

**Issue by 007GitHu** [prettier/prettier#6798]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: v12.6.0
- Runtime: v12.6.0
- Operating System: Windows

**Steps to reproduce:**
java

**Expected behavior:**
In idea , the ability to format code
**Actual behavior:**
Error in formatting：No matching files. Patterns tried: F:\project\testproject!**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**

**Comment by lydell** [comment]
Hi!

I drank a cup of coffee, but encountered no errors. Maybe it wasn’t warm enough?

Please add steps to reproduce if you’d like us to take a look at your problem.
