### ISSUE TITLE
Vue named slots shorthand value is not formatted

### ISSUE THREAD

**Issue by wenfangdu** [prettier/prettier#6800]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDCArgM4wQYCSUWNMZAxACZwBmeGjhgBeYiGD8IEAL4SyAehJRUizLgJwVIADQgIWGAEtodZKDwAnKxADuABWsJzKPADcIxnnpAAjKzwwAGs4GABlLCDjKABzZBgrGjh9AAsYDBwAdVTjeDoosDhwlzzjdzyAT2RwOnN9GLo4KxgHQNiMPGRBHCb9ACs6AA8AIUCQsPC8DDgAGRi4brxelJBBofCY2Jw4AEUaCHgllf0oqyarGvdk3ywrGJgs7xhU5AAOAAZT2yaswKwanc4Bd3It9ABHA7wNqGVwgPB0AC0UDgcD4Pn0VjgkOMWLaeA6XSQPT6ICaGGMCSSqzoWx2+0Oi2Jy1JMDwfiePBeyAATPpEnhjDgtlQmJ0alBoGCQPQ4AAVdmuElwWSyIA)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <CustomInput #default="{foo}" />
</template>

```

**Output:**
```vue
<template>
  <CustomInput #default="{foo}" />
</template>

```

**Expected behavior:**
**Output:**
```vue
<template>
  <CustomInput #default="{ foo }" />
</template>

```

**Comment by fisker** [comment]
`#` is new?

**Comment by lydell** [comment]
Hi! Could you provide a link to documentation about this syntax, please?

**Comment by thinkerdu** [comment]
[Named Slots Shorthand](https://vuejs.org/v2/guide/components-slots.html#Named-Slots-Shorthand)

**Comment by fisker** [comment]
never used this :(

**Comment by wenfangdu** [comment]
I think this change could do the job.
![image](https://user-images.githubusercontent.com/28700378/88458656-323c2080-cec2-11ea-9d3f-23878ec4bd10.png)

**Comment by fisker** [comment]
PR welcome
