### ISSUE TITLE
[Markdown] Parsing 2 ULs after each other is broken

### ISSUE THREAD

**Issue by MichaelDeBoey** [prettier/prettier#6814]
As provided by @alexandrtovmach in https://github.com/gatsbyjs/gatsby/pull/18942#issuecomment-549761497, having two ULs after each other, the second one isn't parsed correctly (using `-` instead of `*`).
When putting some text in between, it works as expected.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiVACAKgdwhgVQBkBnDAQwDN4AnDOcsACwwhibhoB0oeBaDEQCWJGP0EixUAcNE8eAKglyoS2VLWT5UdNjyFSFap3qMWbDnRxD2GEhAC2cDPAAeMDEKgYARnBg4cAjaMlrSylKhKjzw0aoRignx6jwgADQgEAAOMELQJMig5DQ0EDgACsUIBSjkAG4QQgAm6SA+NIwA1v4AylmMXgDmyDA0AK5wGUwwDgA2AOpMNnAk-WBwPdU2QnU2AJ7I4CQFGV4knDDlHYMO5MiU5LPnGQBWJK4AQh1g3TA95E5hFA4PdHs8QG9XD0hrM4ABFMZsEFIB5PSYgfo0c40Q63GidJplKCtLI0LwwebNdjIAAcAAYMqSIOd5h0sodHjhyHsTiAAI6I+BXbI1EDkEh8YFwJrS1o0OACoTyq7kG53FFg9HnBxCEbjLUw+GC5Go8Ewcg+SlNalIABMGVG5CEsyGAGFHLdDlBoCCMmNzlgLTVTXAAL6hoA)
```sh
--parser markdown
```

**Input:**
```md
## Two ULs after each other

- List
- List
- List

* List
* List
* List

## Two ULs after each other with some text in between

- List
- List
- List

test

* List
* List
* List
```

**Output:**
```md
## Two ULs after each other

- List
- List
- List

* List
* List
* List

## Two ULs after each other with some text in between

- List
- List
- List

test

- List
- List
- List

```

**Expected behavior:**
```md
## Two ULs after each other

- List
- List
- List

- List
- List
- List

## Two ULs after each other with some text in between

- List
- List
- List

test

- List
- List
- List

```

**Comment by evilebottnawi** [comment]
We avoid this because some developers prefer use `-`, some `*` so i recommend use remark lint to enforce one style

**Comment by MichaelDeBoey** [comment]
All list sings are replaced by `-`.
- [`*` is replaced by `-`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABAGQJYGcYA6UGO+RJeMIANCBAA4zbS7KgCGATpxAO4AKXBKxTsAbhGwATGiABGndmADWcGAGV6S7FADmyGJwCucWgAsYAWwA2AdTPZ4uLWDjrhj7GMcBPZOFxWWh1cOE4YfkVdS3ZkADN2a1DaACtcAA8AIUUVNXV2SzgcKDh4xOSQNPT1HV1rOABFIwh4MqTTEC1OUM5-GM5lKT4oWXpOHRhbaRgzZAAOAAZaMYhQ20V6fzG4HrFS2gBHZvhIhhEQdlwAWhK4KTvZTjgj7CfI9mjYpAT22lDLbAGYwdXC1epNFqlb7lDowdhyKZSGbIABMtEM7Gw1lqAGEIJYYv4oNB9iAjKEACrwkQ-UIAXzpQA)
- [`+` is replaced by `-`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBqABAGQJYGcYA6UGO+RJeMIANCBAA4zbS7KgCGATpxAO4AKXBKxTsAbhGwATGiABGndmADWcGAGV6S7FADmyGJwCucWgAsYAWwA2AdTPZ4uLWDjrhj7GMcBPZOFxWWh1cOE4YfkVdS3ZkADN2a1DaACtcAA8AIUUVNXV2SzgcKDh4xOSQNPT1HV1rOABFIwh4MqTTEC1OUM5-GM5lKT4oWXpOHRhbaRgzZAAOAAZaMYhQ20V6fzG4HrFS2gBHZvhIhhEQdlwAWhK4KTvZTjgj7CfI9mjYpAT22lDLbAGYwdXC1epNFqlb7lDowdhyKZSGbIABMtEM7Gw1lqAGEIJYYv4oNB9iAjKEACrwkQ-UIAXzpQA)

But when having a combined list (using 2 or more signs from `-`, `*` or `+`), this breaks.

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by lydell** [comment]
@ikatyang Is this something you remember thinking about when implementing markdown?

**Comment by evilebottnawi** [comment]
@lydell looks like it is expected https://github.com/prettier/prettier/blob/master/src/language-markdown/printer-markdown.js#L249, I think this is done so as not to be confused with two and more lists, but for me it is weird :confused:

**Comment by MichaelDeBoey** [comment]
I think this should be relooked at if it's an intentional thing.

For me it's weird too that having lists with multiple list styles and/or 2 lists after each other with a blank line in between them won't parse these lists to all be `-`.

**Comment by lydell** [comment]
It wouldn’t surprise me if there is some subtle markdown rule we’re overlooking here. @ikatyang would probably know.

**Comment by lydell** [comment]
It wouldn’t surprise me if there is some subtle markdown rule we’re overlooking here. @ikatyang would probably know.

**Comment by lydell** [comment]
I think the current output is correct. According to the spec, changing bullet marker creates a new list. So if Prettier was to change both lists to the same marker, the two lists would suddenly be merged into one list. https://spec.commonmark.org/0.29/#example-271

**Comment by MichaelDeBoey** [comment]
But according to the spec, having 2 of the same list styles with an empty line in between, is just one and the same list

https://spec.commonmark.org/dingus/?text=-%20bar%0A-%20baz%0A%0A-%20foo%0A

**Comment by lydell** [comment]
Yes – that proves that your expected output would change the meaning of the document?

**Comment by MichaelDeBoey** [comment]
It proves that the empty line in between can be deleted, no? 🤔

**Comment by lydell** [comment]
No, empty lines are significant in lists. They decide if list items will have `<p>` tags inside of them.

But now I’m completely confused. You’ve proved yourself wrong, so the issue should be closed? Or am I missing something. Sorry if this sounds harsh or anything, I’m just tired.

**Comment by MichaelDeBoey** [comment]
Hmmm I don't know what I just proved 😂

**Comment by MichaelDeBoey** [comment]
I'm just like "you _always_ change whatever sign we use to be `-`, so it's weird to have other signs in there"

**Comment by lydell** [comment]
List with three items:

```md
- one
- two
- three
```

List with three items, where every item is wrapped in `<p>`:

```md
- one

- two

- three
```

List with three items, where every item is wrapped in `<p>` (“if **any** of its constituent list items are separated by blank lines”):

```md
- one
- two

- three
```

What if you want a `<ul>` after another `<ul>`? It’s possible in HTML, so it should be possible in HTML, right? Naive attempt:

```md
- one
- two

- new list?
```

Wait – that’s the same as the previous example! So that’s really just one `<ul>`. So CommonMark says that if you switch list marker, a new `<ul>` is started.

```md
- one
- two

* new list!
```

Another way to do it is to add a comment:

```md
- one
- two

<!-- -->

- new list!
```

Makes sense?

**Comment by MichaelDeBoey** [comment]
Kinda makes sense indeed, but still a bit weird to have.

Why change all other signs to `-` then if there are cases you "can't" change it? 🤔

**Comment by lydell** [comment]
Prettier _always_ normalizes list markers:


**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAGQJYGcYA6UGO+RJehURA1FpbfWVHaTCADQgQAOM20XMlABDAE5iIAdwAK4hEJQiAbhGwATTiABGYkWADWcGAGUe+7FADmyGGICucLgAsYAWwA2AdWfZ4uczA4EwU-bGU-AE9kcFwhLktcODEYGT0rNxFkADMRDySuACtcAA8AIT1DYxMRNzgcKDgcvIKQYpKTSysPOABFewh4ZvynEHMxJLEYzLEDdWkoLR4xSxgvDRhnZAAOAAYuZYgkrz0eGOW4SeUmrgBHAfg03kUQEVxURrh1L60xOHvsH80iIMlkkLkRlwkm5sLYHKNcF0ev1Bk1wS1RjARNp1upNsgAExcOwibAeLoAYQgbkyMSg0BuIHsSQAKtjFBCkgBfLlAA)
```sh
--parser markdown
```

**Input:**
```markdown
- List
- List
- List

+ List
+ List
+ List
```

**Output:**
```markdown
- List
- List
- List

* List
* List
* List

```
