### ISSUE TITLE
[question]format `import {x,y,z} from 'xxx'`

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [prettier/prettier#6834]
**Input:**
```jsx
// code snippet
import {x,y,z} from 'xxx'
```

**Output:**
```jsx
// code snippet
import {
  x,
  y,
  z,
} from 'xxx'
```
## How to set up to convert `Input` into `Output` after formatting?

**Comment by lydell** [comment]
It already works that way.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACSATOGDOUAlgA4lwwA6xAtiRAE4wbAAeANAJ7sBeAvhgBmDCDQwByVlPEh2ICCRhFo+ZKACGDEQHcACpoSqU6gG4Qi2WSABGDdWADWFAMol7RKAHNkMBgFc4OQALGBoAGwB1IKJ4fDcwOGdDGKITGM5kcHxVOQ98OCZdO08adWRBdTD8uQArfFYAITtHF3UaOAAZDzhyyuqQOtZnD08wuABFPwh4XqrAkDcGfIZM63VrODCrEgYPGAiLGCDkAA4ABjkdiHyIuxJMnbhlkx65AEcp+CKFIxB1fAAtFA4HBcJY5Aw4B8iJCiuoSmUkBU5nJ8jQiD5-PN8CMxpNpj0kX15jB1gdsEdkAAmOS+dREMIjADColKmSg0FeID8+QAKusjMj8nw+EA)
```sh
--parser babel
```

**Input:**
```jsx
// code snippet
import {x,y,z} from 'xxx'
```

**Output:**
```jsx
// code snippet
import { x, y, z } from "xxx";

```

**Comment by Mr-jiangzhiguo** [comment]
> It already works that way.
> 
> **Prettier 1.18.2**
> [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACSATOGDOUAlgA4lwwA6xAtiRAE4wbAAeANAJ7sBeAvhgBmDCDQwByVlPEh2ICCRhFo+ZKACGDEQHcACpoSqU6gG4Qi2WSABGDdWADWFAMol7RKAHNkMBgFc4OQALGBoAGwB1IKJ4fDcwOGdDGKITGM5kcHxVOQ98OCZdO08adWRBdTD8uQArfFYAITtHF3UaOAAZDzhyyuqQOtZnD08wuABFPwh4XqrAkDcGfIZM63VrODCrEgYPGAiLGCDkAA4ABjkdiHyIuxJMnbhlkx65AEcp+CKFIxB1fAAtFA4HBcJY5Aw4B8iJCiuoSmUkBU5nJ8jQiD5-PN8CMxpNpj0kX15jB1gdsEdkAAmOS+dREMIjADColKmSg0FeID8+QAKusjMj8nw+EA)
> 
> ```shell
> --parser babel
> ```
> 
> **Input:**
> 
> ```js-jsx
> // code snippet
> import {x,y,z} from 'xxx'
> ```
> 
> **Output:**
> 
> ```js-jsx
> // code snippet
> import { x, y, z } from "xxx";
> ```

No, this is not my expected, I hope it can newline behind `x`,`y`and `z`,
it likes:
```js
import {
  x,
  y,
  z,
} from 'xxx'
```
not only one line,likes `import { x, y, z } from "xxx";`

**Comment by lydell** [comment]
Ah, sorry, I misunderstood. That’s not possible. But there are workarounds:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSkIFssaYNh6MMAPAGk4wBPflC4AvEQF8MAMxwRGGAOTdVS+vSYscbDqIzoBfAcIET60uQuWruSkLxAQsRaAGdkoAIY55AdwAFHwQPFC8ANwhCABMHEAAjHC8wAGt8AGUsZMIoCmQYHABXOEcACxhGABsAdVLCeDcssDh0kPrCcPrBZHA3D0cctxIYAKSKRi9kGS9KoccAKzduACEk1IyvRjgAGRy4KZm5kEXudJyKSrgARUKIeAPZkpAsnCGcHviveLhKuNwcmDVGIwUrIAAcAAZHLgIENqkksD1cHA3uF9o4AI63eCjZyhEBeNykKBwODRMlxPBYwh4UZecaTJDTR6OIaMQj5IpPNznS43O77JmHJ4wL5A6Ig5AAJkcBS8hEq5wAwgoJj1qCS4oUhgAVL6hZlDSSSIA)
```sh
--parser babel
```

**Input:**
```jsx
// prettier-ignore
import {
  x,
  y,
  z,
} from 'xxx'

import {
  //
  x,
  y,
  z,
} from 'xxx'
```

**Output:**
```jsx
// prettier-ignore
import {
  x,
  y,
  z,
} from 'xxx'

import {
  //
  x,
  y,
  z
} from "xxx";

```

**Comment by Mr-jiangzhiguo** [comment]
@lydell 
in the future, it is able to support it?

**Comment by lydell** [comment]
No, this is not planned, and not a common request either.
