### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by todorone** [prettier/prettier#6849]
I know that these kinda questions may be annoying, but new shiny TS3.7 just out and the only thing is stopping from using it for a lot of folks around is the absence of Prettier's support. Is there any ETA? 😊

**Comment by evilebottnawi** [comment]
Please don't create issues for release, we are working on new version (duplicate of #6469) , thanks

**Comment by todorone** [comment]
@evilebottnawi Sorry, missed it. If You pin release issue for better visibility, probably there will be less such stupid topics...😸

**Comment by evilebottnawi** [comment]
@todorone done :+1:

**Comment by kirillgroshkov** [comment]
Can't wait:)
