### ISSUE TITLE
Problem with comment within ternary

### ISSUE THREAD

**Issue by kjbekkelund** [prettier/prettier#685]
Comment support is way better now! The only comment failure I could see in my current code base was this:

```diff
 const { configureStore } = process.env.NODE_ENV === "production"
-  ? require("./configureProdStore") // eslint-disable-line import/no-commonjs
-  : require("./configureDevStore"); // eslint-disable-line import/no-commonjs
+  ? require("./configureProdStore")
+  : // eslint-disable-line import/no-commonjs
+    require("./configureDevStore"); // eslint-disable-line import/no-commonjs
```

So:

```js
const { configureStore } = process.env.NODE_ENV === "production"
  ? require("./configureProdStore") // eslint-disable-line import/no-commonjs
  : require("./configureDevStore"); // eslint-disable-line import/no-commonjs
```

turns into:

```js
const { configureStore } = process.env.NODE_ENV === "production"
  ? require("./configureProdStore")
  : // eslint-disable-line import/no-commonjs
    require("./configureDevStore"); // eslint-disable-line import/no-commonjs
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20%7B%20configureStore%20%7D%20%3D%20process.env.NODE_ENV%20%3D%3D%3D%20%5C%22production%5C%22%5Cn%20%20%3F%20require(%5C%22.%2FconfigureProdStore%5C%22)%20%2F%2F%20eslint-disable-line%20import%2Fno-commonjs%5Cn%20%20%3A%20require(%5C%22.%2FconfigureDevStore%5C%22)%3B%20%2F%2F%20eslint-disable-line%20import%2Fno-commonjs%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks, just submitted #754 to fix it!
