### ISSUE TITLE
[TS / JS] line break before Array methods for inline await

### ISSUE THREAD

**Issue by felixmosh** [prettier/prettier#6851]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaXACTgBsaIB1CAJxoBMAKYAc2bjjJRuuALy4AOiAAWtepIA0uXv3htRuAOSSmrNpI2L0pGghjr8qGujiLoAWQiFrAeQBucZvIC+ASlzBxKEDcXEgodDNUNgBbUnD1DlQAd1RSGA42ACMAOmsTMHSNACoNH2z8Zghojg0o2PDS7JN8GAApCDiazJpURqSZPhrSNgNNONGAbQBGeQAmeQBmeQAWAF0fDezo1AAHDi5hxShUaLhfEQA+A7Yjk7ONwMCvEHkQCB2yaHRkUFRmSqSAAU-ghvihUK4OmwXiBMsxUGAANYCADKOwRcW4yBgzEINmkMGiNAYUjScHQ6LAcBRoLSpFcaUwyHA6G+rzi1mYMEB8O422QFis+IAVugAB4AIXhSNRdwAMnE4ALLNZXqKxSjMSYAIqECDwZVC17o5ic5mZVCZWgwnbMOIwBjDGBSZAADgADMbKtYGPCdszbeSPO4YQBHPXwHnvMFodAAWig-DYcGhrz44dIfB5qD5qENqpA1li2Nx+KMQh1EaVSEFBZglsdbGdyHmIBxqRomIAwlV+SgoNAla8nHAACqWsG1s5eIA)
```sh
--parser babel
```

**Input:**
```jsx
async function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  const admins = (await(db.select('*').from('admins').leftJoin('bla').where('id', 'in', [1,2,3,4]))).map(({id, name})=>({id, name}))

}
```

**Output:**
```jsx
async function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  const admins = (await db
    .select("*")
    .from("admins")
    .leftJoin("bla")
    .where("id", "in", [1, 2, 3, 4])).map(({ id, name }) => ({ id, name }));
}

```

**Expected behavior:**
As you can see the `map` method is on the same line at the end, and it looks weird.
I think that this looks much better:

```jsx
async function HelloWorld() {
  const admins = (await db
        .select("*")
        .from("admins")
        .leftJoin("bla")
        .where("id", "in", [1, 2, 3, 4])
     )
     .map(({ id, name }) => ({ id, name }));
}
```

**Comment by thorn0** [comment]
How about:
```js
async function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  const admins = (
    await db
      .select("*")
      .from("admins")
      .leftJoin("bla")
      .where("id", "in", [1, 2, 3, 4])
  ).map(({ id, name }) => ({ id, name }));
}
```
?

**Comment by felixmosh** [comment]
> How about:
> 
> ```js
> async function HelloWorld({
>   greeting = "hello",
>   greeted = '"World"',
>   silent = false,
>   onMouseOver
> }) {
>   const admins = (
>     await db
>       .select("*")
>       .from("admins")
>       .leftJoin("bla")
>       .where("id", "in", [1, 2, 3, 4])
>   ).map(({ id, name }) => ({ id, name }));
> }
> ```
> 
> ?

Looks good as well.

I can contribute, I just need a small guidance.

**Comment by thorn0** [comment]
Too late. See https://github.com/prettier/prettier/pull/6856
