### ISSUE TITLE
Issue finding/writing files with brackets ([]).

### ISSUE THREAD

**Issue by zjr** [prettier/prettier#6854]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI, CLI via Editor Tool (WebStorm File Watcher)
- Runtime: Node v12.13.0
- Operating System: macOS

**Steps to reproduce:**
```fish
prettier --write src/pages/posts/[id].jsx
```

**Expected behavior:**
It's expected to find, parse, update & write the file, as a prettier does.

**Actual behavior:**
```fish
[error] No matching files. Patterns tried: src/pages/posts/[id].jsx !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```

There is another issue previously opened about this (#6344), I am opening this one because the other is closed & locked so can't be commented on.

It was said in the above referenced issue that this was probably an issue for `lint-staged` instead of `prettier` but I feel a bit differently about that given that this—at least to my imagination—affects tooling of many kinds. I could escape the file path like this: `"src/pages/posts/\[id\].jsx"` to get prettier to work, but that isn't really possible for any tools that insert an arbitrary file path into the CLI command. In my case I'm using a File Watcher in WebStorm… this is really just using the CLI with whatever the current file path is.

**Comment by evilebottnawi** [comment]
Same problem here https://github.com/prettier/prettier/pull/6492

Potential solution - https://github.com/prettier/prettier/pull/6492#issuecomment-536523483

**Comment by lydell** [comment]
@evilebottnawi :+1: I agree

**Comment by lydell** [comment]
Just to clarify: We would like to first try to read each CLI argument as a file. If there is no such file, we treat it as a glob.

**Comment by evilebottnawi** [comment]
@lydell yep, just take the logic from eslint :smile:

**Comment by evilebottnawi** [comment]
WIP

**Comment by fisker** [comment]
@evilebottnawi Have you seen 
 https://github.com/prettier/prettier/pull/6776#issuecomment-581389188

> Actually, might some other problem, we relay on `isFile()`, what if this file is program generated file.
> 
> ```
> git clone some/repo
> prettier repo/example**.js
> ```
> 
> it should format `repo/example**.js`, but that repo delete this file some day, we will format all his `exampleXXXX.js` file


Do we need consider this?

**Comment by evilebottnawi** [comment]
Ideally - yes, because many glob characters can be used in filename (especial on Linux/MacOS)

**Comment by fisker** [comment]
So are we still stick to the original plan?

**Comment by evilebottnawi** [comment]
Yes, I think we can get the logic for eslint and simplify that

**Comment by fisker** [comment]
Okay, you can assign this to me.

**Comment by evilebottnawi** [comment]
Big thanks!

**Comment by evilebottnawi** [comment]
Fixed https://github.com/prettier/prettier/pull/7587
