### ISSUE TITLE
TypeScript: option to use comma as interface/type member delimiter

### ISSUE THREAD

**Issue by kalbert312** [prettier/prettier#6859]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKgRmwF5thsBDJbAZxgCcBLKAcwBpsAjK2xl7AXwDcAHViYcuAEzFSo7NjBUoAVwC2HOHVZzsAEyocIEADZxyUbVH6jRTeHQBm5MBIDMsqPLjd6TNjoclNQ0tUWsoUUgoWmwIfCoCGTJKbGEQcg4wNPYuVJBdOAc0gREoKJiISQTpEjIdRWwAVkt5fWx6ZTgw0pBWEAgMGAZoamRQcjo6CAB3AAUJhFGUcgA3CAZdXpAOOmcAazgYAGUMZz9kDrg+gAsYVWMAdWuGeGpTlyPFl4YVl7RkcDUUZ9JjUTQwWa7ZiqcjIJzGMF9ABW1AAHgAhXZgA7HciqOAAGSYcDh5ARVxAKNRRz8pgAisoIPBSeS+qc6GC6AD0FhqGBGIMthheDAHhsYNdkAAOAAMbKmYIeuwwAOFcE5KxJfQAjoz4JCBkt0tQALRQOBwAqbPp0OC6hi2yHkaGwpDwxEgMGqBgXOidPrUWlwBlMkluskemAZMW6CXISR9ejkBjGPwAYQgqhhALJxi2yjBuAyS3dcH4-CAA)
```sh
# Options (if any):
--trailing-comma=all
```

**Input:**
```typescript
type T1 = { a: string, b: string };
type T2 = {
  c: number,
  d: boolean,
}

interface T3 {
  e: string,
  f: number,
}

const o1: T1 = { a: "abc", b: "def" };
const o2: T2 = { 
  c: 5,
  d: true
};
```

**Output:**
```typescript
type T1 = { a: string; b: string };
type T2 = {
  c: number;
  d: boolean;
};

interface T3 {
  e: string;
  f: number;
}

const o1: T1 = { a: "abc", b: "def" };
const o2: T2 = {
  c: 5,
  d: true,
};
```

**Expected behavior:**
I'd like to be able to write objects and types the same way so I don't need to think about which delimiter to use. When I write a TS interface/type, I habitually use `,` because that's the only delimiter allowed for objects. I understand they are two different concepts that just happen to share similar syntax and that prettier will automatically adjust these via a pre-commit hook. However, in reality, I find that I just naturally type commas and then usually end up with a mix of semi-colons and commas in between prettier runs. I think such a distinction is a waste of time when commas can work just as well and lessens the difference between interface and object syntax.

**Comment by lydell** [comment]
Hi!

So your argument is that you’d like to be able to always type `,` in order not to have to think about which delimiter to use? Good news – you already can. Always type commas and let Prettier do whatever it does on save.

**Comment by kalbert312** [comment]
Is it possible to turn this particular thing off and delegate it to a linter or is it all-or-nothing?

**Comment by lydell** [comment]
Like most things in Prettier, it’s all-or-nothing. If you _really_ care about this, there’s [prettier-eslint](https://github.com/prettier/prettier-eslint).

**Comment by kalbert312** [comment]
Alright. For the record I do like 97% of prettier's decisions. Cool stuff.

**Comment by thorn0** [comment]
Nobody likes 100%. Software is tradeoffs.
