### ISSUE TITLE
Making a release with new options / 1.19.0 “post mortem”

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#6887]
All options in Prettier have a `since: "x.y.z"` field.

The new option in 1.19, `vueIndentScriptAndStyle`, had `since: "1.19.0"`.

`prettier --support-info` apparently does not print stuff with a higher `since` version than is specified in package.json.

The release script bumps the version in package.json and then runs the tests. The tests for `prettier --support-info` then fail, because now it returns the new option added in 1.19.0 which isn’t in the snapshots.

I worked around this issue by first making a commit where I bumped the version in package.json to `1.19.0-beta.1` and updated the snapshots:

https://github.com/prettier/prettier/commit/057e15d50d92a3af3de97b908905ed7ec13318de

However, we now have this in our code:

```
vueIndentScriptAndStyle: {
    since: "1.19.0-beta.1",
```

The questions of this issue are:

- ~~Is `since: "1.19.0-beta.1"` a problem?~~ EDIT: Changed to `since: "1.19.0"` in 1.19.1.
- Does the release script need updating to handle new options?
- Should the PR adding the new `vueIndentScriptAndStyle` have done something differently?

@duailibe do you have any insight?

**Comment by duailibe** [comment]
@lydell If I understand correctly, what's missing in the release script is to change `package.json` version back to "NEXTVERSION-dev". Does that make sense?

**Comment by lydell** [comment]
Another way would be to default `version` in `getSupportInfo(version, opts)` to `"999.9.9"` rather than `require("../../package.json").version.split("-", 1)[0]` I guess. Or something like that – not passing a version should mean “give me _everything_”. One should ideally not have to update the snapshots when bumping the version.

**Comment by fisker** [comment]
Is this still a problem? There will be a [new option](https://github.com/prettier/prettier/blob/0f3967b5ab66f68b9b3c6a29eae5735140174ef3/src/main/core-options.js#L250) in `v2.1`

**Comment by thorn0** [comment]
No longer a problem. The version in `package.json` is already set to `2.1.0-dev`, so the snapshots don't change after changing it to `2.1.0`. The problem with `1.19.0` was that the version in `package.json` wasn't set to `1.19.0-dev` after releasing 1.18.2. No idea why. The release script should have done that.
