### ISSUE TITLE
Prettier 2.0 – 2.0 2020

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#6888]
We already have a Prettier 2.0 issue – #3503 – but tell you what: Time’s up for that one. As of this writing, Node.js 8 is scheduled to expire early on December 31, 2019. And we still support Node.js 4. In two months we will be 6 versions behind!

Supporting Node.js 4 and Node.js 6 has been a real hassle lately as our dependencies (rightfully!) has stopped supporting them. We have spent a lot of unnecessary time getting tests to pass in Node.js 4.

So here’s my suggestion for a 2.0 of a Prettier 2.0 issue:

**The main focus should be dropping support for unsupported Node.js versions.** Let’s aim for releasing Prettier 2.0 early in January 2020 with support for only Node.js 10+.

Apart from that we could do some easy breaking changes:

- Change the default for `trailingComma` to `es5`, as discussed in the original Prettier 2.0 thread.
- Remove deprecated stuff.

When that is done – if we have time, we could do more things. We’ll see. For example, it would be really nice addressing #5588 (making all unsafe template literal formatting **opt-in**). I also have a suggestion for lots of improvements for Prettier’s CLI and API, but I’ll open a separate issue for that.

/cc @prettier/core @brodybits @fisker

**Comment by azz** [comment]
Sounds good to me! Let's get this shipped.

**Comment by fisker** [comment]
@lydell you fogot Change the default for `singleQuote` to `true`

**Comment by lydell** [comment]
@fisker No, I didn’t. I don’t think we should do that. As far as I can tell, there’s been no consensus on that change. Let’s not discuss `singleQuote` for this release so that we can stay focused on the important parts.

**Comment by brodybits** [comment]
I hope we can drop use of a bundled `typescript` dependency in favor of babel-ts as proposed in PR #6400. I think this would be much less bulky, also reduced variety of bundled dependency licenses (I think TypeScript is Apache 2.0.).

**Comment by lydell** [comment]
That would be nice. Maybe we can change to `babel-ts` as the default TypeScript parser in 2.0 and remove the `typescript` parser in 3.0 if it all works out.

**Comment by thorn0** [comment]
On the other hand, we might want to go the other way round and use TypeScript to parse JS. If Prettier is going to format JSDoc, TypeScript already parses it for us.

![image](https://user-images.githubusercontent.com/94334/68574765-4e527b80-0473-11ea-8137-6cae8912e5c9.png)

**Comment by manuelbieh** [comment]
Is this ticket the right place to propose changes of default values? If so, I would like to put `arrowParens` up for discussion. This should imo be changed to `always` to provide maximum consistency. See my tweet from a few weeks ago for why I think `avoid` is a mistake:
https://twitter.com/ManuelBieh/status/1181880524954050560

**Comment by Shinigami92** [comment]
IMO, it is not the right place 😕
We should discuss any suggestion to change a default value in a separate issue
Then we could refer to the issue in this issue

Otherwise it could be very messy in this issue

**Comment by thorn0** [comment]
@manuelbieh It's out of scope for this release.

**Comment by evilebottnawi** [comment]
@thorn0 I think we should consider `arrowParens: always`. I have worked with many projects, both large and small, and most of them use `always` for the `arrowParens` option. Also it will not change many lines in code

/cc @prettier/core what do you think?

**Comment by thorn0** [comment]
This release is supposed to be focused only on the things a consensus has been already reached about.

**Comment by evilebottnawi** [comment]
@thorn0 we have time to discussion about other things is not it so? I see no reason to delay things that can be solved quickly and without pain

**Comment by Shinigami92** [comment]
> @thorn0 we have time to discussion about other things is not it so? I see no reason to delay things that can be solved quickly and without pain

You are free to open several issues for your proposals

**Comment by kachkaev** [comment]
Two more potential changes in default values to discuss folks: #6931 #6932. Please give your 👍or 👎 !

**Comment by j-f1** [comment]
It might be valuable to provide a command-line tool that upgrades JSON, YAML, and TOML configurations to Prettier 2.0, by removing any option values that have become the default, and adding entries to the config file for any options that are no longer the default. What do you think?

**Comment by lydell** [comment]
Sounds great. If we can make it in time. It won’t block the release.

**Comment by suchipi** [comment]
In regard to removing `typescript` in favor of `babel-ts`: I am hesitant to do so, because when new TypeScript features are added, they might be added to the TypeScript parser before Babel. However if it works out, it works out. Just want to make sure we are careful.

**Comment by thorn0** [comment]
Also TypeScript's parser is less restrictive than Babel, even with error recovery, which is important for Prettier. E.g. now Prettier simply silently corrects this invalid code whereas Babel (with the TS plugin enabled) can't parse it:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOADgK4BGqAlmDurZjAE7pgw4BmhABQBKANxkKrdlx5U6jZrXQcR4qAF8QAGhARKMBtEzJQyjhADuABWUJjKdADcIDACbaQtGQGs4MAMqU3AxQAObInNRwOgAWMAC2qADqMQzwmEFgcP52aQyOaQCeyODYHiGYcBwwVlyh8ejIfOiolToAVpgAHgBCPn7+6PFwADIhcE0tbSCdXf4hoahwAIrUEPCTrdEgQRyVHCUwhZRwmGAcDPoelBewSW4wMcgAHAAMOjcQlUlclCU3pyqjgmOgAjmt4LU9PYQFgALRQOBwVzIjwcODghjo2roeqNJDNLY6SrxBgRDhRYkLJardYTAlTbYwVj3VyPZAAJh0nHQDEYYQAwhB4g0SlBoCCQNRKgAVKSbaaOKIASSgKNg-nOlxgAEE1f4jksFXB1OogA)
```sh
--parser typescript
```

**Input:**
```tsx
class Foo {
  public abstract foo();
  abstract public bar();
}
```

**Output:**
```tsx
class Foo {
  public abstract foo();
  public abstract bar();
}

```

**Comment by lydell** [comment]
Yeah, we might need to keep all of TypeScript, Flow and Babel to stay cutting-edge. But it sure would have been nice to just have one.

**Comment by Shinigami92** [comment]
Should we use https://github.com/prettier/prettier/tree/next for some PRs?

**Comment by lydell** [comment]
Yes. For breaking changes.

**Comment by brodybits** [comment]
Sorry to be a bother but I think there are a couple of major issues with bundled TypeScript implementation from the `typescript` package:

- additional complexity of the published bundle, even if it is limited by tree shaking
- Since TypeScript is under the longer Apache 2.0 license statement, I think any package that bundles the implementation should technically fall under the same license statement

I would *personally* favor moving use of the TypeScript parser into an external Prettier plugin, and use something like babel-ts to parse TypeScript by default.

**Comment by ljharb** [comment]
Why parse it by default at all, when it could be done properly via a plugin?

**Comment by j-f1** [comment]
> Why parse it by default at all, when it could be done properly via a plugin?

Which do you mean @ljharb:

- TypeScript altogether? Our goal is to enable most projects to get up and running by simply installing `prettier` with no additional plugins. For those running Prettier in a webpage (where bundle size is more significant than it is for the CLI version), we don’t bundle any parsers by default and you must manually load and include any plugins you want to use.
- technically-invalid TS which the error correction handles properly? I agree with you there, although our current plugin infrastructure wouldn’t allow you to use a different TS parser.

**Comment by ljharb** [comment]
Yes, that's what I mean, TypeScript altogether.

tsc and babel both parse typescript slightly differently, and different versions of TypeScript will work very differently. It seems like the user *should* be forced to explicitly indicate which version of TS, and which flavor of it, they're using.

**Comment by thorn0** [comment]
> It seems like the user should be forced to explicitly indicate

@ljharb What makes you think that? I helped add support for TS 3.7 in Prettier and have a pretty clear sense of the AST format discrepancies between the parsers used by Prettier, but I have no idea what you mean.

**Comment by ljharb** [comment]
@thorn0 i mean which TS minor they're using matters a lot, and i'd be very surprised if all the discrepancies between babel and tsc were resolved.

**Comment by thorn0** [comment]
@ljharb Matters a lot for what exactly? A TS project that uses say TS 2.0 (or even is compiled by Babel) can be without any trouble parsed and reformatted by the current version of Prettier that uses TS 3.7 internally.

**Comment by ljharb** [comment]
There are countless bugs that make that not tenable; TS still isn't (and has never been) a true superset of JS. I'm sure many code samples will work "fine", but that's not the same thing as the level of determinism that prettier usually strives to attain.

**Comment by thorn0** [comment]
@ljharb Please write something specific. We're talking about nothing.

**Comment by ljharb** [comment]
I'm sorry, are you implying that TypeScript parsing has always, in every version, been identically forwards-compatible? That implication is the one that has the burden of proof imo.

**Comment by lydell** [comment]
Can we move the TypeScript discussion to another issue?

**Comment by lydell** [comment]
After three years of going through Prettier github notifications almost daily, I’ve decided to take a break. I’ll be around if you ping me, and I’m subscribed to a ton of issues and PRs, but I won’t be looking at new stuff for the forseable future.

@thorn0 @sosukesuzuki @evilebottnawi and more, are you up for finishing up on 2.0?

**Comment by VincentLanglet** [comment]
Is there any timeline for the next major version ? :)

**Comment by thorn0** [comment]
@lydell 

> are you up for finishing up on 2.0?

I'd give it a try if we stick to the original plan (because time's up):

>> **The main focus should be dropping support for unsupported Node.js versions.** Let’s aim for releasing Prettier 2.0 early in January 2020 with support for only Node.js 10+.
>>
>> Apart from that we could do some easy breaking changes:
>>
>> - Change the default for `trailingComma` to `es5`, as discussed in the original Prettier 2.0 thread.
>> - Remove deprecated stuff.

What do I need to proceed?

**Comment by kachkaev** [comment]
> Apart from that we could do some easy breaking changes
> * Change the default for trailingComma to es5, as discussed in the original Prettier 2.0 thread.

🚀 https://github.com/prettier/prettier/pull/6963 (merged already)

Voting results for other breaking changes in defaults:

✅ https://github.com/prettier/prettier/issues/6929: **Change `arrowParens` to `always` by default for 2.0**
✅ https://github.com/prettier/prettier/issues/6932: **Change `endOfLine` to `lf` by default for 2.0**
❌ https://github.com/prettier/prettier/issues/6931: **Change `quoteProps` to `consistent` by default for 2.0**

Did I forget anything?

**Comment by VincentLanglet** [comment]
> Voting results for other breaking changes in config defaults:
> 
> ✅ #6929: **Change `arrowParens` to `always` by default for 2.0**
> ✅ #6932: **Change `endOfLine` to `lf` by default for 2.0**
> ❌ #6931: **Change `quoteProps` to `consistent` by default for 2.0**
> 
> Did I forget anything?

What about [this](https://github.com/prettier/prettier/pull/7111) breaking change since an option was refused.

**Comment by thorn0** [comment]
@VincentLanglet It's clearly out of scope for 2.0.

**Comment by VincentLanglet** [comment]
Ok, I thought this could be merged since I saw a PR and this comment https://github.com/prettier/prettier/issues/3806#issuecomment-562603324

I'll wait for 3.0 then.

**Comment by lydell** [comment]
@thorn0 There’s the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) and the [release readme](https://github.com/prettier/prettier/blob/master/scripts/release/README.md). The release script is really nice and a bit interactive, telling you what to do. I’ve only done one or two release before so I’m not super familiar with this, though. Most time is needed for the changelog/blog post. You should now have npm publish access.

**Comment by fyeeme** [comment]
can [bracketSameLine](https://github.com/prettier/prettier/issues/5377) (support for vue)be considered?

**Comment by karlhorky** [comment]
If 2.0 is still open, just like @kachkaev's list above, here's also another issue where the votes clearly show a favor towards changing the default:

✅ #4102: Change the default value for singleQuote to true

**Comment by janaagaard75** [comment]
It's really hard to use the number of votes in #4102 without having something to compare them to. 
It could just be people searching for "how to set up Prettier to using single quotes", ending up on that thread, and then obviously giving it a thumbs up. We would need an alternate timeline where Prettier was defaulting to single quotes, and an issue about switching to double quotes.

**Comment by 0az** [comment]
What about #3806 (implemented in #7111)?

Unlike `singleQuote`, it's uncontroversial. I don't recall any significant opposition, or any opposition at all to that change. Reading through the comments, [this comment suggesting a variant](https://github.com/prettier/prettier/issues/3806#issuecomment-360075440) and [this comment in opposition](https://github.com/prettier/prettier/issues/3806#issuecomment-442638892) are the only ones with significant amounts of downvotes.

**Comment by miyaokamarina** [comment]
What about #3986? For the last few years I’ve avoided using intersections in any way, even in places where I can’t do without them, because Prettier is turning them into complete nonsense.

**Comment by 0az** [comment]
#3988, the PR for #3986, was closed as "inconclusive". I do think that it should get revisited, if only for consistency with the proposed binary operator change.

And given that the latter's consensus is more or less settled, in my opinion it's safe to conclude that the intersection change will see similar support, or at least lack of significant opposition.

I'm willing to try my hand at a PR for the lot this weekend, if I end up having spare time. Does anyone know of any similar issues with consensus?

**Comment by karlhorky** [comment]
Congratulations on the 2.0 release! 🎉
