### ISSUE TITLE
`yarn build` doesn't make `dist/bin-prettier.js` executable anymore

### ISSUE THREAD

**Issue by maximbaz** [prettier/prettier#6900]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: N/A
- Runtime: N/A
- Operating System: Arch Linux

**Steps to reproduce:**

```
yarn
yarn build
ls -al dist/
```

**Expected behavior:**

```
.rwxr-xr-x bin-prettier.js
```

**Actual behavior:**

```
.rw-r--r-- bin-prettier.js
```

**Notes:**

If this helps, I ran `git bisect`:

```
99d4b86c18cae7e1cfa9e7da075677fa7233fea3 is the first bad commit
commit 99d4b86c18cae7e1cfa9e7da075677fa7233fea3
Author: fisker Cheung <lionkay@gmail.com>
Date:   Sat Jun 8 03:58:05 2019 +0800

    Rollup update (#6200)
```

**Comment by lydell** [comment]
Hi!

What problem does this cause you?

**Comment by fisker** [comment]
Not sure if this line has problem

https://github.com/prettier/prettier/blob/b56f95c97522e2099d46f02af5139a9dd178b6c5/scripts/build/rollup-plugins/executable.js#L43

**Comment by maximbaz** [comment]
I discovered this during packaging `prettier` for Arch Linux, it is trivial to fix the permissions on my end, but I thought you would be interested to fix it on your end, in case you also expect users to run `yarn build` and then use the resulting files.

**Comment by fisker** [comment]
It's suppose to be excutable

**Comment by fisker** [comment]
found the problem `writeBundle` is not excuted

**Comment by fisker** [comment]
done.  @lydell
