### ISSUE TITLE
TypeScript browser bundle has webpack warning

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier#6903]
**Environments:**
- Prettier Version: 1.19.0 and 1.19.1
- Running Prettier via: Browser API
- Runtime: webpack 4.41.2
- Operating System: macOS

**Steps to reproduce:**

```js
import "prettier/parser-typescript";
```

**Expected behavior:**
Bundle continues to compile without warnings.

**Actual behavior:**
```
WARNING in ./node_modules/prettier/parser-typescript.js
Module not found: Error: Can't resolve '@microsoft/typescript-etw' in '/Users/nick/Repos/prettier-chrome-extension/node_modules/prettier'
 @ ./node_modules/prettier/parser-typescript.js
 @ ./src/content/parsers.js
 @ ./src/content/github.js
 @ ./src/content/extension.js
 @ ./src/content/index.js
```
Oddly enough, the parser continues to work properly. However the error is confusing and may cause potential issues as `typescript-etw` only supports running on Windows natively, and this version of the parser only supports running in web browsers.

**Comment by fisker** [comment]
I think you should exclude it yourself, like we did

https://github.com/prettier/prettier/blob/master/scripts/build/config.js#L46-L47

**Comment by fisker** [comment]
> Oddly enough, the parser continues to work properly. 

because this require is in a try/catch block

**Comment by nickmccurdy** [comment]
I don't really understand how this build script works, but it seems like it's causing webpack to exclude this package when used with CJS modules. Should this also be added for ES modules? I can confirm that this isn't an issue when using Node or using a browser without webpack.

**Comment by fisker** [comment]
Our config script is for `rollup`, you need to find the equation to exclude a module in webpack, this is not bug. It's expected, so people installed `typescript-etw` can work with it

**Comment by nickmccurdy** [comment]
Thanks, I understand that there should be a way for me to ignore this warning in webpack.

However, it seems add to me that `typescript-etw` is referenced in the browser bundle when this module will not work in the browser. Is there a way for us to adjust the build script or feature flags of Prettier to exclude this in the browser bundle completely? I'm also curious what changed to cause this warning in 1.19.

**Comment by fisker** [comment]
`parser-typescript.js` is universal, works in both `nodejs` and `browser`. I don't understand what's the problem

**Comment by nickmccurdy** [comment]
Oh, I thought everything was bundled into `main` for Node.

**Comment by fisker** [comment]
this should be the one https://webpack.js.org/configuration/module/#modulenoparse, I'm not sure, but if not, go to webpack community to find a solution

**Comment by nickmccurdy** [comment]
I've fixed the warning already, I was just wondering if there was a way to fix it at build time. My last idea is to try to prevent the import conditionally in the browser using dynamic imports. If that's not possible I'll close this.

**Comment by thorn0** [comment]
> so people installed typescript-etw can work with it

Do we really need to support this use case?

**Comment by j-f1** [comment]
Here’s where it’s imported:

https://github.com/microsoft/TypeScript/blob/0fc388893ef2e76c93d35195cc59c69ed5e8ac05/src/compiler/perfLogger.ts#L27-L37

I don’t think there would be an easy way for us to remove this code.

**Comment by fisker** [comment]
@thorn0 I thought people can somehow benefits

@j-f1 In fact , we can remove it, just replace it with a `throw `

**Comment by j-f1** [comment]
ah, you’re correct. The build script could replace it using this option:

https://github.com/prettier/prettier/blob/1d1a90144f80d042d504c3356a2e8331d3f7589f/scripts/build/config.js#L153-L156

```js
replace: {
  "require("@microsoft/typescript-etw")": "undefined"
}
```

**Comment by thorn0** [comment]
> I thought people can somehow benefits

It's extremely doubtful. If by any chance someone needs this, they can use Prettier unbundled or build a custom bundle.

**Comment by nickmccurdy** [comment]
Would typescript-etw be useful for Prettier users on Windows?

**Comment by j-f1** [comment]
I don’t think so. It’s just a performance logger, which isn’t something Prettier really needs.
