### ISSUE TITLE
Ugly linebreak caused by type assertion

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#6904]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaAiCACgEpdgAdHadGXMACwCcIBbOAGUYEbqgDmcAGqoANoThJcAcQRxupMAHkARgCs4YdgF5cqAO6pS7al14CAdG1ES4D2RDByz6XMJeSAILccKi0DpIw1AJQhACS8HxxACa0ANzMAL4gADQgEAAOZKzIoKjcvOYACuUI6MhoAG4QpMm5IDpiYADWcDCCBahgpFDiyDDcCnmcMHyyAOqc1nDog2BCddakjdaYDWDo9Xkj6OowVWLifKjI+HKneXroAB4AQl29-agCADIjcLd7nBHi9BCNxLI4ABFQgQeCA2QPECDbinbgNGCYAorMAaIrtAoaWDzVowTjIACcAAY8oSIKd5mICg1CSt1I0AXkAI6w+AXQr1FAYAC0UDgcGSEvaIR5pBCFwk1wRSNOfFI40mwJA6HBkJhcIBSDuiK1MFQOhJyTJyAATHkJlZZOCAML8JUoKDQTkgQinAAq5sFxqRjQUcSgktgglxpCKgQjwkwkOVcEymSAA)
```sh
# Options (if any):
--typescipt
--print-width: 90
```

**Input:**
```typescipt
async function foo() {
const chromeStorageValue: GenericObject = await (chrome.storage.local as StorageArea).get(menuItemId);
}
```

**Output:**
```typescipt
async function foo() {
  const chromeStorageValue: GenericObject = await (chrome.storage
    .local as StorageArea).get(menuItemId);
}

```

**Expected behavior:**
Smth like
```typescipt
async function foo() {
  const chromeStorageValue: GenericObject = await (
    chrome.storage.local as StorageArea
  ).get(menuItemId);
}

```

**Comment by thorn0** [comment]
It has nothing to do with `await`, it's the same without it:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaAiCACgEpdgAdHadGXMACwCcIBbOAGUYEbqgDmcAGqoANoThJcAcQRxupMAHkARgCs4YdgF5cuajt58AdFytxrbURIeyIYObgy5hzyQEFuOFRaa0kYagEoQgBJeD4YgBNaAG5mAF8QABoQCAAHMlZkUFRuXgB3AAVShHRkNAA3CFJE7JBLVDAAazgYQTzO0ihxZBhuBRzOGD5ZAHVOUnh0AbAhWsXSBsXMerB0Opyh9HUYSrFxPlRkfDljnL10AA8AITFu3sFUAQAZIbhr25we5PQRDcSyOAARUIEHgANkdxAA24x249RgmDycHQYA0BTaeQ0sFmLRgnGQAE4AAw5QkQY6zMR5eqE7HqBr-HIARxh8DO+TqKAwAFooHA4IkJW0gjzSEEzhJLvDEcc+KRRuMgSB0GCIdDYf8kDcEVqYKgdCTEmTkAAmHJjVCkWRggDC-CVKCg0E5IEIxwAKubBcbEQ0FDEoJLYIJcaQCv5I8JMBDlXB0ukgA)
```sh
--parser typescript
--print-width 90
```

**Input:**
```tsx
async function foo() {
const chromeStorageValue: GenericObject =  (brom.chrome.storage.local as StorageArea).get(menuItemId);
}
```

**Output:**
```tsx
async function foo() {
  const chromeStorageValue: GenericObject = (brom.chrome.storage
    .local as StorageArea).get(menuItemId);
}

```

**Comment by thorn0** [comment]
I would say it's a manifestation of https://github.com/prettier/prettier/issues/6443. If you replace `as` with a binary operator, it formats fine:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaAiCACgEpdgAdHadGXMACwCcIBbOAGUYEbqgDmcAGqoANoThJcAcQRxupMAHkARgCs4YdgF5cuajt58AdFytxrbURIeyIYObgBUX3MOeSAILccKi01pIw1AJQhACS8HxxACa0ANzMAL4gADQgEAAOZKzIoKjcvADuAArlCOjIaABuEKTJuSCWqGAA1nAwggXdpFDiyDDcCnmcMHyyAOqcpPDoQ2BC9cukTcuYjWDoDXkj6Oow1WLifKjI+HKneXroAB4AQmK9-YKoAgAyI3Bbvc4I8XoIRuJZHAAIqECDwIGyB4gIbcU7cRowTAFODoMAaIodAoaWDzNowTjIACcAAY8sSIKd5mICo1ibj1E1AXkAI5w+AXQoNFAYAC0UDgcGSUo6IT5pBCFwk10RyNOfFI40mIJA6AhUNh8MBSDuSJ1MFQOjJyQpyAATHkJqhSLIIQBhfgqlBQaDckCEU4AFUtwtNyKaCjiUGlsEE+NIRUC0eEmChqrgmUyQA)
```sh
--parser typescript
--print-width 90
```

**Input:**
```tsx
async function foo() {
const chromeStorageValue: GenericObject =  (brom.chrome.storage.local ** StorageArea).get(menuItemId);
}
```

**Output:**
```tsx
async function foo() {
  const chromeStorageValue: GenericObject = (
    brom.chrome.storage.local ** StorageArea
  ).get(menuItemId);
}

```

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/10341
