### ISSUE TITLE
Feature request: Range ignore in CSS

### ISSUE THREAD

**Issue by Walther** [prettier/prettier#6906]
Originally submitted as https://github.com/prettier/prettier-vscode/issues/1023

Related:
- https://github.com/prettier/prettier/issues/5557
- https://github.com/prettier/prettier/issues/5508
- https://github.com/prettier/prettier/issues/5008

(Wonder if there should be a master tracking issue for adding the ranged ignore to all supported file formats?)

### Summary

Prettier has a feature for ranged ignores  <https://prettier.io/docs/en/ignore.html#range-ignore> since v1.12.0+. This does not work in CSS (and any other format than Markdown, for that matter).

[Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgA4Cc4wwCWcuAtEQOZQT5kDOMAhrjJuqgDpQaYBmuCAFscTKABMIYTPQCesJgA9MACyoqANuuJRKmdlyiRxcGdjEA6JhszBMkDbSSYAxHz4AGLx4DcmAL6YvACCGqRsHNzGpvTmUFZQtvYQjrjOLgBsHkweAEa+AUFYwVA0zMTQBlEQJmaWTGx2Dk6uAOziAJweAEwdfoEhhLhEuQCu8FVGNTFxFrmJTSktLgAs2R6tBQNYAEJM9HAAcpPRdfFjSduYO6NEGjAAkomRU7WxlmB8Sc1prl6b3S2RUwAGFoDBBBoAGKOADuJ2mZwsYBU3yWv1WG3W-WBIJULARb1mYAWyVS6QAHBTvEDeGCoIwxBFDKd3vFIGjya4sjl8ji6cIhAhmdUiR8AG6c5Y8vK0rBgoRC2AANQJL1Zs0kUoxuSY3QAjAb+VgACJSUZK8pESrqxFsiziRpk5ZdQFeY2YE0NJgAFVk2FMtrF8XEksWXMxOU2HpNcDAqpsQZmllI2vS7hpHoAorhBLhCcn4nBlHYrlnFPAGdbniy7bM+DZw8s1lG5ZgYRAGgWkXxRmm-hluhTWnAPVDRkYKjXRYWLEQRKXgQ8hNhaCLXrOiKSfukZXzCrwnnxaEIGtXu-aANbwpsY-49NsAaTgslhtHEF9mEGw-cyGX--4egA8gGuANLQn6WBATo7n8WKAsBMAqKmSZItgP63ukuRgK0ORtgACvgeBSHA9D0BBqH2vQ0iYa4aybDkHoAMoBmARDWHiaq1sGFhkb+uS5P+VLMax7EaExEJbnolGzIwv70diB5YBJwy6JB8Tikwv76h0+qtK0YAeqqwxMLkYTqRY4r0PJWKMUpmDKqQurEEIKlSRZsJabRmTrPuVwAOosFA7kvLweAEMQpAUNQtBwGQCAfhwIAADQgN+U70MgoAsIIsL4SwCCZSgTDihARDiClIC5GBYCXgQLFMGxujIBCoxwKlKgwEIGj+Wo8DvGAcBMYVRDEOKo2yMg4BkZVW4HKwhFMJQp7IHw1gHKlABW9CKDsNV1TATFMEKAAyW5wKt63tSA22KExUlhAAiqM0EXUga0aBtIDmLg81TWAM2pXgW4wP55VIcg1JA4IBz+WB2BTeF83ihdqUAI4vfAhHfkVID7GQUBwHAJgVal+AY0Q+CLctTCXZ910HEIRAtbgbWpfQD1wM9r1019zC5GDjoqMg3SpRCTB3FJCorSgNCE5VowHD6plFR9X3im1TwmLATFgMM2AwCU4gSbIYS83A-j+EAA)

### Expected result

prettier does not reformat the section defined with `prettier-ignore-start` and `prettier-ignore-end`

### Actual result

prettier reformats all the lines.

### Additional information

```
prettier --version
1.19.1
```

prettier-vscode 2.3.0

![prettier-vscode](https://user-images.githubusercontent.com/2943750/68535687-fa4e7680-034e-11ea-8e8e-91ba0d1fcf56.gif)

**Comment by thorn0** [comment]
Closing in favor of #5287
