### ISSUE TITLE
Support for codeblocks inside RST (restructured text)

### ISSUE THREAD

**Issue by edi9999** [prettier/prettier#6913]
RST (restructured text) is a format that is quite used in the open-source community. The sphinx documentation software uses this restructured text format to generate HTML sites for documentation. Sphinx is used by the Linux Kernel, Python for example.

Currently prettier supports the markdown format and indents code inside js snippets.

In RST, code snippets are used like this : 

```
.. code-block:: javascript

    var myApp = {};
    myApp.foo = "bar"
```

Is this something that could be done in prettier, or in an extension maybe ?

**Comment by thorn0** [comment]
Sounds like a use case for Prettier's [plugin API](https://prettier.io/docs/en/plugins.html).
