### ISSUE TITLE
How can I maintain new lines on Prettier?

### ISSUE THREAD

**Issue by Unknow-del** [prettier/prettier#6914]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbm9fAXjMvwzcrLyc-KLCv1KAejL8ABVbABFbJHxa6AV9Gzh8akMoOggAW394th6nDN19RIG+C0MYIQA6VHIafAYZufmunv6GDwAqfABGAFEAagB2N3mYCABlGGpw5l3NuAAHEkMwOAYy-n55v86KcyjhmJJBII3OkstFYvEADx0HD2fBgT6aTQAOUMfTgPAUxDIlBo9AU+FwMF0PGAAAMAJrWfCGNj4ew4bQ3agJdB9ABGTnwABJgDyBi5aS58JZrHZHNQaTL2g4nC4AHww0r4BGaB7QZhq0WhTjMeaaEg4b4MfAABkkh3wVxuAFU3m8nABhQymXb4U5SNhhLhmi1Ww5OiAAGQgAHdPd6fh4XAiyrrqPqNVk-CxAyb5gg6JoKDg5gwJFD8AB+AQgGv4Ro6t7dfC6gCe1OAwEg5GojSU-GkrYULnVEhrKc0TagavwLgyfgRcD6mf4MCNubgcjnPhgKaXma1ooY2l0sGhWdK1cEgJA89KjUEQUE27vKeR9jVaR8UBcIHEIAgN5cGgTRkFAFl0xjAAFFkEFAlBDHsCAcDoP8QD5LowAAaw4W4mzAJ5kAedAzGEGA+hICghBLOBJy+OBbjgksURLVtkHATE0PCUxqBgKCumYPpDGQIwTFIgArTQAA8ACFMJwmBblxOBI3COAROMUx-0kqTbieXQAEV0AgeANLE-8m2oHj2L5QwBRINC3keWBizoOZkAADjtEAnIgUwKC6N52Kc2inEcNCAEdjPgfjAPgkBvQAWigdg6E3NC2CinA2H4wxBOEpBRK0kBTD6HAiOoEj-20LhDOi9TCs00iYDs1z3KQAAmf8HkMHQng9fohPYqBoHU-92iqOz4KK0j7BIgBJEZYFuMBHiAgBBHp7nbBqZpHIA)
```sh
--parser babel
```

**Input:**
```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

  
  
  
  
  
  
  
  
  
  
  
     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>;

}
```

**Output:**
```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}

```

**Expected behavior:**
Hi guys,
I have a question about a Prettier.
I have a file .css where I want to preserve the newlines that I add.
But every time I run Prettier the empty lines were compressed always in one.

How can I maintain this newlines?

Thank you for reading

**Comment by lydell** [comment]
See the answer in #6916

**Comment by j-f1** [comment]
Duplicate of #6916
