### ISSUE TITLE
How can I maintain new lines on Prettier?

### ISSUE THREAD

**Issue by Unknow-del** [prettier/prettier#6916]
Hi guys,
I have a question about a Prettier.
I have a file .css where I want to preserve the newlines that I add.
But every time I run Prettier the empty lines were compressed always in one.

How can I maintain this newlines?

Thank you for reading

**Comment by j-f1** [comment]
Prettier only allows one consecutive blank line. There is no way to prevent Prettier from collapsing multiple blank lines into one.

**Comment by lydell** [comment]
https://prettier.io/docs/en/rationale.html#empty-lines

**Comment by zphhhhh** [comment]
but 
```js
export default {

    /**
     * aaa
     */
    aaa,

    /**
     * bbb
     */
    bbb
}
```
will be processed to
```js
export default {
    /**
     * aaa
     */
    aaa,

    /**
     * bbb
     */
    bbb
}
```
and I want to preserve the empty line before the first param.
