### ISSUE TITLE
SCSS: extra comma added to map, before last comment

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#6920]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKASAtgTwLRYCGADkgAQAU6ZZA5AGYQS3kCMANGQPRdkDCELFgQxqdAEaEATizIAmTj36DhsdAEoA3CHYgIxGAEtoAZ2ShpUiAHcACtIRmUhAG4RDAEx0hxUwmABrOBgAZWJ-QygAc2QYKQBXOF0ACxgsABsAdWTDeBNwsDgQx1zDF1ycZHATM11IkzgpGFs-KKJkekJ0ht0AKxMADwAhP0DgkMJhABlIuA6unpB+gZDIqPS4AEV4iHh57qSQcKkGqSqTMBrvYilImEzPGGTkAA4ABl0biAbMv2Iqm5wU4uOa6ACOO3gLX0ThAhBMeCgcDgHhR3ikcAhhgxLUIbUI+0WDSwhliCUOJjWG22uzmSE6B10MEI4geHieyAUIDihEM6TWAiEBJQUGgoJA8QaABUWU4GYsXIkAJJQVGwEJgW4GACCqpCMBwG0JcAAviagA)
```sh
--parser scss
```

**Input:**
```scss

$my-map: (
  'foo': 1, // Comment
  'bar': 2, // Comment
);
```

**Output:**
```scss
$my-map: (
  "foo": 1,
  // Comment
    "bar": 2,
  //        ^ <----- trailingComma should not printed
  // Comment
);

```

**Expected behavior:**

```scss
$my-map: (
  "foo": 1,
  // Comment
    "bar": 2
  // Comment
);
```

should not print trailingComma

**Comment by evilebottnawi** [comment]
Yes, it is bug, feel free to send a PR
