### ISSUE TITLE
Change `arrowParens` to `always` by default for 2.0

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#6929]
Why i think we need to change that?

- code consistency when an argument more than one
- if we look through our issues a lot of developers use `always`
- it does not require large code changes in our code
- honestly I don't even know why we once created this option and whether we need it in the future

Maybe we should create poll on twitter and here

@prettier/core I would like to hear your opinions on this

Ref: https://github.com/prettier/prettier/issues/6888

**Comment by manuelbieh** [comment]
I already posted it in the main 2.0 issue and for the sake of completeness I think I should post it again. Why I think `avoid` is a mistake. A mistake in the ES6 spec to make it at all possible to omit parens in exactly one very specific case, namely when you have exactly one argument without default, without typing or anything. And a mistake to make it the default value for arrowParens in Prettier. TL;DR, here:
https://twitter.com/ManuelBieh/status/1181880524954050560

**Comment by Shinigami92** [comment]
We should not remove the option completely, because options are always better then forcing the JavaScript community to use braces in arrowParents

**Comment by thorn0** [comment]
> honestly I don't even know why we once created this option and whether we need it in the future

For reference: [original issue (#812)](https://github.com/prettier/prettier/issues/812), [PR where it was added (#3324)](https://github.com/prettier/prettier/pull/3324).

**Comment by lydell** [comment]
If an option value results in code that is easier to edit and produces less `git diff`, I’m all for changing the default. People upgrading can always change those options back in their configs if they want to.

`trailingComma` and `arrowParens` are great candidates for this. (While `singleQuote`, for example, is just bike shedding.)

**Comment by MichaelDeBoey** [comment]
I agree with @lydell: I'm too all in for everything that produces a smaller `git diff`.

**Comment by kachkaev** [comment]
@MichaelDeBoey I was thinking the same actually. Is it worth creating separate issues for [`quoteProps: "consistent"`](https://prettier.io/docs/en/options.html#quote-props) and [`endOfLine: "lf"`](https://prettier.io/docs/en/options.html#end-of-line)? 🤔

**Comment by lydell** [comment]
@kachkaev Sure, why not.

**Comment by kachkaev** [comment]
@lydell here we go: #6931 & #6932 😉

**Comment by Skalman** [comment]
`always` is clearly more consistent, and might be easier for beginners to learn. That said, I _really_ like the cleanliness of having fewer parentheses, since I frequently write long chains of arrow functions.

```js
// `avoid`
categories
  .filter(x => x.name === category)
  .flatMap(x => x.pages)
  .filter(x => x.name.includes(search))
  .forEach(x => (x.highlight = true));

// `always`
categories
  .filter((x) => x.name === category)
  .flatMap((x) => x.pages)
  .filter((x) => x.name.includes(search))
  .forEach((x) => (x.highlight = true));
```

In this short example, the difference isn't that big, but when inside of complicated functions, having less visual noise helps.

**Comment by kachkaev** [comment]
@Skalman when looking at your example in isolation, the first statement with `arrowParens: "avoid"` looks cleaner indeed. However, what we're trying to optimise is the overall consistency across codebases, which are often very large and are worked on by many people.

IMHO what makes the second case better is the conciseness of the rule I need to keep in my head and communicate to other developer. It is as short as _always use parens in arguments_. Easy to remember, is not it? To produce your ‘cleaner example’ it would be like _always use parens in arguments unless there is exactly one argument, which does not have a default value, a type definition and is not a object destructed on fly_. Not as short as it could ideally be.

I use idea of _rule shortness_ as a general principle when making code styling or more general engineering decisions. An option that produces a shorter rule, implies a smaller cognitive load and reduces exchange of redundant information between contributors. In my personal experience, the resulting short rule is usually more robust and easier to follow.

**Comment by suchipi** [comment]
I always set `arrowParens` to "always" in my personal projects, because otherwise the parens get removed by prettier and I have to re-add them when I want to destructure something or add a type annotation. I'm all for changing the default.

I also think it's important to keep the option though, because a lot of FP fans like to use `avoid` (which is why it ended up as the default iirc).

**Comment by Skalman** [comment]
@kachkaev, I really do understand - I tried to make that clear in my first sentence. My suggestion for default value would be whatever is more common in the JS world. If that is `always`, I'll switch my projects.

**Comment by j-f1** [comment]
> My suggestion for default value would be whatever is more common in the JS world.

The problem with this suggestion is that Prettier is becoming more and more popular, so whatever Prettier does may start to dominate “whatever is more common in the JS world.”

**Comment by ExE-Boss** [comment]
FWIW, I&nbsp;always use&nbsp;`arrowParens: "avoid"`, because&nbsp;it&nbsp;looks&nbsp;cleaner, and&nbsp;doesn’t&nbsp;really&nbsp;affect&nbsp;`diff`.

**Comment by davidfregoli** [comment]
Personally I don't really care about the default, but I would really like to have a third option: avoid only on single-argument single-statement (no curly braces) functions.

so these are valid:
`x => x + 1`

```
(x) => {
  const y = x + 1;
  return y;
}
```

**Comment by kachkaev** [comment]
👀 ➡️ https://github.com/prettier/prettier/pull/7430

**Comment by evilebottnawi** [comment]
Done for next
