### ISSUE TITLE
Unstable comments after `extends`

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#693]
```js
class A extends B // comment1
// comment2
// comment3
{}
```

[turns into](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22class%20A%E2%80%84extends%20B%20%2F%2F%20comment1%5Cn%2F%2F%20comment2%5Cn%2F%2F%20comment3%5Cn%7B%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

```js
class A
  extends B // comment2 // comment1
// comment3
{
}
```

[turns into](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22class%20A%5Cn%20%20extends%20B%20%2F%2F%20comment2%20%2F%2F%20comment1%5Cn%2F%2F%20comment3%5Cn%7B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

```js
class A
  extends B // comment3 // comment2 // comment1
{
}
```

[turns into](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22class%20A%5Cn%20%20extends%20B%20%2F%2F%20comment3%20%2F%2F%20comment2%20%2F%2F%20comment1%5Cn%7B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

```js
class A
  extends B {} // comment3 // comment2 // comment1
```

[turns into](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22class%20A%5Cn%20%20extends%20B%20%7B%7D%20%2F%2F%20comment3%20%2F%2F%20comment2%20%2F%2F%20comment1%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

```js
class A extends B {} // comment3 // comment2 // comment1
```

**Comment by vjeux** [comment]
We need to find a generic solution for those.
