### ISSUE TITLE
Change `quoteProps` to `consistent` by default for 2.0

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#6931]
Refs: #6888 (about Prettier 2.0), #6929 (about changing `arrowParens` to `always`)

[`Quote Props option`](https://prettier.io/docs/en/options.html#quote-props) was added in https://github.com/prettier/prettier/pull/5934 and is available since Prettier 1.17. Given that @azz [did not mind](https://github.com/prettier/prettier/pull/5934#issuecomment-468912380) changing the default value from `as-needed` to `consistent` in V2, I decided to open this issue to bring the topic to a broader discussion.

I understand that changing defaults can cause large git diffs in some projects. However for the benefit of newly created projects, I suggest that the problem can be addressed by changing `prettier.config.js` in existing codebases. V2.0 is a great opportunity for breaking changes like this.

WDYT folks?

**Comment by Shinigami92** [comment]
I vote for `as-needed` as default value

**Comment by lydell** [comment]
What are the benefits of changing the default here?

**Comment by Skalman** [comment]
I'm not a fan, since Git diffs would be unnecessarily large. Adding or removing a single property/method might change many rows.

I prefer the first of the following diffs:

```diff
 const headers = {
   Host: "example.com",
   Accept: "text/html",
+  "Accept-Language": "en-US",
 };
 ```

```diff
 const headers = {
-  Host: "example.com",
+  "Host": "example.com",
-  Accept: "text/html",
+  "Accept": "text/html",
+  "Accept-Language": "en-US",
 };
 ```

I suppose the following is just my preference, but to me it doesn't read well at all:

```js
const headers = {
  "Host": "example.com",
  "Accept": "text/html",
  "Accept-Language": "en-US",

  // I'd prefer `toString()`
  "toString"() {
    return Object.entries(this)
      .map(
        ([header, value]) => typeof value === "string" && `${header}: ${value}`
      )
      .filter(x => x)
      .join("\n");
  }
};

```

**Comment by j-f1** [comment]
I don’t think we should change the default from `as-needed` to `consistent` since Prettier generally tries to avoid changing the formatting for a whole block of code due to a change in one line. It would also inflate the size of diffs, which goes against what @lydell said in https://github.com/prettier/prettier/issues/6929#issuecomment-552521966:

> If an option value results in code that is easier to edit and produces less `git diff`, I’m all for changing the default. People upgrading can always change those options back in their configs if they want to.

**Comment by kachkaev** [comment]
I'm buying the above arguments and am now leaning towards keeping things as they are (`quoteProps: "as-needed"`). We can keep the issue open to let others still jump in and throw a spanner in the works 😁

**Comment by wmorrell** [comment]
I would say `"as-needed"` makes the most sense as a default. I am using `"preserve"`, and letting eslint do `"quote-props": [1, "always"]` for clarity.

**Comment by kachkaev** [comment]
At the time of writing this comment, the issue got **3** 👍 and **14** 👎

Many thanks to those who voted and expressed their opinion in the comments! The points made against changing the default were quite solid and they were not successfully challenged by someone with an opposite opinion.

Two and a half months after starting the topic, I believe it would be fair to say that changing `quoteProps` to `consistent` should not happen 😉
