### ISSUE TITLE
Change `endOfLine` to `lf` by default for 2.0

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#6932]
Refs: #6888 (about Prettier 2.0), #6929 (about changing `arrowParens` to `always`)

[`End of Line option`](https://prettier.io/docs/en/options.html#end-of-line) was added in https://github.com/prettier/prettier/pull/5327 and is available since Prettier 1.15. Given that using LF (Linux line endings) is a default choice in the software dev world, I decided to open this issue to bring the topic to a broader discussion.

I understand that changing defaults can cause large git diffs in some projects. However for the benefit of newly created projects, I suggest that the problem can be addressed by changing `prettier.config.js` in existing codebases. V2.0 is a great opportunity for breaking changes like this.

WDYT folks?

**Comment by lydell** [comment]
What are the benefits of changing the default here?

**Comment by Shinigami92** [comment]
Want to let you know that I'm using `.editorconfig` with `end_of_line = lf`

**Comment by kachkaev** [comment]
@Shinigami92 we also have `endOfLine: "lf"` configured, the suggestion is to avoid a need to do this 🙂

@lydell see https://github.com/prettier/prettier/issues/5320 and linked issues for context. My motivation for adding `endOfLine` to Prettier was a lot of pain we had to experience in our company. Because developers were contributing to repos from both *nix and Windows machines, end of lines ended up being different in neighbouring files and even jumped from one style to another in one file between commits. In addition to a discomfort and unnecessary diffs coming out of this inconsistency, it was also a source of real bugs. If a javascript file starts with 

```
#!/usr/bin/env node
```

and someone manages to save it with  `CRLF`, the above shebang directive no longer works. With the release of Prettier 1.15, we configured `endOfLine: "lf"` and had no CRLF problems ever since.

The reason we have `endOfLine: "auto"` by default is https://github.com/prettier/prettier/issues/92, which got more 👎 than 👍 in the end. It was closed in https://github.com/prettier/prettier/pull/472, which was nearly three years ago. I'm not suggesting to remove the option completely, to cover the case of someone still using Nodepad on Windows 8. This is the least old text editor I know of that requires `CR` characters in order to see multiple lines. Going further, I would suggest removing this option completely given that `LF` works in any modern editor these days.

**Comment by kachkaev** [comment]
Examples of mixed `CRLF` / `LF` line endings in popular repos (before `endOfLine: "lf"` was introduced): https://github.com/prettier/prettier/issues/5320#issuecomment-435159024

**Comment by kachkaev** [comment]
👀 ➡ ️#7435

**Comment by kachkaev** [comment]
Closed in #7435 🚀 Thanks to @thorn0 for merging! 🙌

**Comment by snebjorn** [comment]
I see that I'm a bit late to the party. But I'm having a hard time understanding this change. Forcing LF on windows is not ideal, sure modern editors don't care. But it's still not optimal.

I much perfer using git to handle this.

```
// .gitattributes
# Set default behavior to automatically normalize line endings. (checkout fixes line endings to system default. Commits are always LF)
* text=auto

# Force bash scripts to always use LF line endings so that if a repo is accessed
# in Unix via a file share from Windows, the scripts will work.
*.sh text eol=lf
```

Should I open an issue for this discussion?

**Comment by lydell** [comment]
@snebjorn Can you elaborate on _why_ it’s not optimal and why you prefer git to handle things?

**Comment by snebjorn** [comment]
@lydell seems I was a bit set in my ways. It appears windows now understands and works well with LF.

Only thing I found that didn't was wordpad, but who uses that 😄?

So disregard my comment.
