### ISSUE TITLE
Add CLI option to update / migrate existing config to new version

### ISSUE THREAD

**Issue by Shinigami92** [prettier/prettier#6933]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: CLI
- Runtime: Node.js
- Operating System: all

**Steps to reproduce:**

```shell
prettier --migrate-config
```

**Expected behavior:**

Update existing config (if there is one)
- e.g. remove default configs

**Actual behavior:**
Help is printed

ref https://github.com/prettier/prettier/issues/6888#issuecomment-552587370

**Comment by Shinigami92** [comment]
I could try to implement this in the next few days

**Comment by kachkaev** [comment]
Cases to keep in mind (based on https://prettier.io/docs/en/configuration.html):

1.  **Shared configuration**. Project configuration file may refer to a shared config:

    ```js
    // .prettierrc.json
    "@company/prettier-config"
    ```

    ```js
    // .prettierrc.js
    module.exports = {
      ...require("@company/prettier-config"),
      something: "z",
    }
    ```

    Quite a lot of things can happen here.
    
    For example, imagine that today's Prettier default is `something: "x"`, `"@company/prettier-config"` sets it to `"y"` and `.prettierrc.js` sets it to `"z"`. If Prettier 2.0 sets `something: "z"`, we still cannot remove this line from `.prettierrc.js`. The migration tool should have the notion of config extension and should be able to account for the contents of `"@company/prettier-config"`. This can include jumping back and forth from `.prettierrc.json` and `.prettierrc.js` if options cancel out.

1.  **Overrides**. It might be necessary to not only remove or add options at the top level, but also in structures like:

    ```js
    {
      "something": "x",
      "overrides": [
        {
          "files": "*.y",
          "options": {
            "something": "y"
          }
        },
        {
          "files": ["*.z"],
          "options": {
            "something": "z"
          }
        }
      ]
    }
    ```

1. **Multiple config formats**. We have `json`, `js`, `yaml/yml` and `toml` as well as the ability to define the config in `package.json` 🤯

**Comment by Shinigami92** [comment]
Thank you @kachkaev 
IMO we should first concentrate on the basic migration
We can work it out later in other PRs

Therefore, we should not touch `overrides` or special cases as mentioned in your 1st point

**Comment by bakkot** [comment]
I don't think this should be an option in this project, since most people will use it exactly once (or at least once per project). Rather, it should be a standalone tool, like [`babel-upgrade`](https://github.com/babel/babel-upgrade).

**Comment by Shinigami92** [comment]
It *must* be in the organization `@prettier` and therefore be an official package
Otherwise, developers will not see it and it will not get enough love / attention and will not be used enough

One step further... What do you think about `@prettier/cli`?
Like `@vue/cli`, `@angular/cli`, `@babel/cli`, `webpack-cli`, `eslint-cli`, ...
These are all independent repos/mono-sub-repos (... not sub `src/cli`)

**Comment by evilebottnawi** [comment]
I don't think option for migrate configuration is high priority for us, we don't have a lot of options, also it is has a lot of limitation like external configurations, `js` templates where you can use variables/expressions and i don't see many benefits, better focus on fixing bugs

**Comment by thorn0** [comment]
After the 2.0 release, where 3 options at once unprecedentedly changed their defaults, there was no demand at all for such a tool. Should some default value change ever again, it'll be easy enough for users to follow a super short migration guide. Prettier's configuration is too minimalistic for such tools to be needed. I'm closing the issue. Thanks for trying to help @Shinigami92
