### ISSUE TITLE
External configuration file not working

### ISSUE THREAD

**Issue by nikhilbisht21** [prettier/prettier#6938]
External configuration file is not working with prettier new version i.e. 3.2.1 in vscode. Downgraded to previous version to resolve this problem.

VS Code version : 1.40.0
Prettier version: 3.2.1

**Comment by evilebottnawi** [comment]
Please provide steps, prettier do not have `3.2.1` version

**Comment by kachkaev** [comment]
Possible duplicate of https://github.com/prettier/prettier-vscode/issues/1037

**Comment by Reaverart** [comment]
Thats might be related, we have number of prettier errors from 1.19 and had to bump 1.18.2 for now

**Comment by evilebottnawi** [comment]
@Reaverart what is errors?

**Comment by nikhilbisht21** [comment]
Configuration file settings are not being applied by the prettier extension in new version. In previous version the settings for prettier were saved with vscode settings, but in new version we have to provide an external settings file named as .prettierrc as mentioned here: https://prettier.io/docs/en/configuration.html

I migrated settings to the external file as suggested by extension, but It  stopped worked for me.
I had following settings for prettier:
`{
  "printWidth": 120,
  "singleQuote": true
}
`

I am not able to format my code according to settings in new version.

**Comment by evilebottnawi** [comment]
i think you should open issue in vscode :confused: we don't change in our resolution logic in `1.19`

**Comment by Reaverart** [comment]
@evilebottnawi something like following:
```
  186:1   error  Replace `··········` with `········`                                                                                                                                                                                                      prettier/prettier
  187:1   error  Delete `··`                                                                                                                                                                                                                               prettier/prettier
  188:1   error  Replace `······` with `····`                                                                                                                                                                                                              prettier/prettier
  189:1   error  Delete `··`                                                                                                                                                                                                                               prettier/prettier
  190:1   error  Replace `····}⏎··` with `··}`                                                                                                                                       
```
where with 1.18.2 we dont have it, so my guess it looses config somewhere
I cant say exactly whats going on, I'm not really familiar with our eslint/prettier configuration at this point.

**Comment by evilebottnawi** [comment]
@Reaverart we always improve some things in prettier, so it is expected what something change after update prettier

**Comment by Reaverart** [comment]
Thank you, I think I need to figure out is there misconfiguration or updates formatting rules.

**Comment by nikhilbisht21** [comment]
I updated to new version of prettier i.e. 3.3.5 and Its working fine now with external settings file. Just provided the path of prettier's external settings file like before in VS Code settings and It worked this time. 
I guess this issue is resolved now in new version. Thanks!
