### ISSUE TITLE
thx for migrating and 3.0v idiots, now i can't work in vscode anymore, because your config files broken

### ISSUE THREAD

**Issue by TicTak21** [prettier/prettier#6940]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: 
- Runtime: 
- Operating System: 

**Steps to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by kachkaev** [comment]
Unrelated to Prettier core. Please politely join discussions in https://github.com/prettier/prettier-vscode/issues

**Comment by evilebottnawi** [comment]
and ban
