### ISSUE TITLE
MDX with "html" tag in JSX fails

### ISSUE THREAD

**Issue by Tigge** [prettier/prettier#6943]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAkMOCMIDEIIAaQgIQEMd8BffAMxwnVPwHIA6APRlUADxgBXHHF4AdKPIDE+ABJwANuuqkA7rnUATAITz5AHgoR8AIwDmAXl7SDvAHzyiZg6gBu+AM4wAJ7qcPbAJITe-pjq9EFIRLzWWmAA1ryshMzuUDz4ZgxMRK4AFqikZoJFufkFgt4+uVWWuSBUIBCYMKjQ-sigjJw6AAqMCP0o9D4QqAbtINY49OlwMADKmCuoULbIMDgScB2lMOjqAOrl8DErcOsTqD0+T0HI4P79HTv+cHgjy1s6HoyDY9HUvw6ACt-KJaMtVht6Og4AAZHZwUHgyEgGGidY7WyhACKEgg8CxEOOIC2OF+OHe6AMogWmBwOxgFzmMFKyAAHAAGDpsiC-C7LTDvNlwek+TEdACOZPgAK6kxA9H8AFooHA4AZ9QtpErUNIAfQgSCkGCqR1fuhUPtDtT-ISScrMdbsdSYPRrFyDDzkAAmDoHeiodSEgDCXGB7yg0HlIAkvwAKn7JjacT4jgBJKAG2DrMDs7oAQUL62CoUpv2YzCAA)
```sh
--parser mdx
```

**Input:**
```mdx
import     {     Foo,  Bar } from     './Fixture'

# Hello,    world!

<Foo bg='red'>
   <div style={{   display:   'block'}   }>
      <Bar    >hi    </Bar>
       </div>
</Foo>

```

**Output:**
```mdx
SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (4:8)
  2 | 
  3 | # Hello,    world!
> 4 | 
    | ^
  5 | <Foo bg='red'>
  6 |    <div style={{   display:   'block'}   }>
  7 |       <Bar    >hi    </Bar>
```

**Expected behavior:**

In prettier 1.18.2 this worked fine, but now it seems that the div tag is parsed as html (judging from the stack trace) and fails. The example above also renders correctly in the MDX playground at <https://mdxjs.com/playground>. Result JSX is:

```jsx
    <h1>{`Hello,    world!`}</h1>
    <Foo bg='red' mdxType="Foo">
   <div style={{
        display: 'block'
      }}>
      <Bar mdxType="Bar">hi    </Bar>
       </div>
    </Foo>
```

**Comment by Tigge** [comment]
Git bisect puts 998f98aaded4c3b2b627578098c7f0c92cda7385 `fix: Adjacent JSX elements should be allowed in mdx (#6332)` as first non-working commit for this test (since 1.18.2 tag).

**Comment by Tigge** [comment]
MDX specification say that "In MDX, all embedded markup is interpreted as JSX", so there is something wrong here.

**Comment by evilebottnawi** [comment]
Thanks for issue, feel free to send a PR

**Comment by Tigge** [comment]
@evilebottnawi thanks. It's a bit complex, with mdx allowing adjacent jsx elements while the babel parser prohibits this. So I think either split it before and send in the elements one by one, or wrap it in a container before parsing, and remove that later. 

I'm not too familiar with the code base, but if you have some idea how to solve that I can probably create a PR.

If a fix doesn't happen it is also possible to revert the commit that introduced this. Not formatting certain blocks is probably better than throwing errors on valid MDX.

**Comment by evilebottnawi** [comment]
@Tigge sorry, i am not familiar with mdx and can't advise anything

**Comment by thorn0** [comment]
@Tigge Please see [these comments](https://github.com/prettier/prettier/pull/6398#discussion_r315160044)  re how this can be fixed. Yeah, we should have reviewed that PR #6332 more thoroughly...

**Comment by Tigge** [comment]
@thorn0 I've created a draft merge request with the method you mentioned. Looks promising, but there is one issue which changes the formatting for adjacent text. I'm not sure if something else should be done with regards to formatting for that to work.

**Comment by JounQin** [comment]
@Tigge I think you can continue the work based on https://github.com/prettier/prettier/pull/6398 which should have fixed this issue.
