### ISSUE TITLE
Browser format API integration with Community Plugins

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [prettier/prettier#6946]
Hi, I am trying to use the community plugin `prettier-plugin-svelte` whcih was mentioned here --> https://prettier.io/docs/en/plugins.html

It's working fine with the CLI, but i am trying to achive the same with API. But it keeps throwing 

```
Error: Couldn't resolve parser "babel". Parsers must be explicitly added to the standalone bundle.
```

I tried configuring the parser, like this 

```js
import * as svelte from "svelte/compiler";
import { format } from "prettier/standalone";
import * as prettierPluginSvelte from "prettier-plugin-svelte";

const result = format(code, {
  parser: svelte.parse,
  plugin: [prettierPluginSvelte]
});
```

The official plugins are working fine, am i configuring the plugins wrong or am i missing something. Thank you for the help 😄 

**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via:  CLI, Node.js API
- Runtime: Node.js v10.10.0
- Operating System:  macOS, etc.

**Comment by evilebottnawi** [comment]
@JayaKrishnaNamburu Can you provide steps?

**Comment by thorn0** [comment]
You need to import `parser-babylon` like it's done with `parser-graphql` in the example in the [docs](https://prettier.io/docs/en/browser.html). However, if your runtime is Node and not the browser, why are you using `prettier/standalone` instead of `prettier`?

**Comment by JayaKrishnaNamburu** [comment]
Yeah sure, 

1. Using format from the `prettier/standalone`
2. Need to use [prettier-plugin-svelte](https://github.com/UnwrittenFun/prettier-plugin-svelte)
3. Then it throws we need to explicitly specify a parser in standalone
4. Passing the parser for `svelte` and then it thorws the above mentioned error

**Comment by JayaKrishnaNamburu** [comment]
> You need to import `parser-babylon` like it's done with `parser-graphql` in the example in the [docs](https://prettier.io/docs/en/browser.html).
> 
> However, if your runtime is Node and not the browser, why are you using `prettier/standalone` instead of `prettier`?

Yeah but i don't think there is a official `parser-svelte` available. And i wanted to use the same in browser as well. Currently following the same for other languages and its working fine with them 👍

**Comment by JayaKrishnaNamburu** [comment]
I have a sandbox link for the same --> https://codesandbox.io/s/kind-robinson-itoqt

**Comment by thorn0** [comment]
You need to import parser-babylon like it's done with parser-graphql in the example in the docs.

**Comment by JayaKrishnaNamburu** [comment]
Yeah, but babylon parser is breaking since these are svelte scripts 😅 That's where a little confusion, since these are svelte script we should be passing a parser that can pass svelte right ?

**Comment by thorn0** [comment]
That Svelte plugin uses many other parsers shipped with Prettier. Also at the very beginning of its [bundle](https://unpkg.com/browse/prettier-plugin-svelte@0.7.0/plugin.js) I can see `require('prettier')`. It's not supposed to work standalone.

**Comment by JayaKrishnaNamburu** [comment]
Thanks for your time @thorn0 i will check this and update here if i can make it work 😃👍
