### ISSUE TITLE
Unprinted comment in try-catch

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#695]
```js
try
/* missing comment */
{;}
finally {}
```

```
Error: Comment "missing comment" was not printed. Please report this error!
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22try%5Cn%2F*%20missing%20comment%20*%2F%5Cn%7B%3B%7D%5Cnfinally%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
The issue is that the comment is attached to the `;` which is an EmptyExpression and not printed. This is strange because there's a check in place to make sure that we don't consider them when attaching comments https://github.com/prettier/prettier/blob/master/src/comments.js#L32
