### ISSUE TITLE
Wifi-pumpkin AP

### ISSUE THREAD

**Issue by CharlieBrown805** [prettier/prettier#6964]
Hello all, I'm new here so sorry if this is in the wrong section to add this in. I have started classes on networking and security as well as learning python and kali linux.  I have came upon wifi-pumpkin. I have installed Kali linux on my laptop I have had laying around.  Installed wifi-pumpkin. From the specs of my network card it supports AP. When I go run it it says "your card doesnt doesn't support AP (wlan0)" I take it I have to configure something with the drive? Or run it on another internet network where the ip isn't private?

**Comment by evilebottnawi** [comment]
Please use stackoverflow for these questions
