### ISSUE TITLE
Logical operators & nullish coalescing break strangely in template string expressions

### ISSUE THREAD

**Issue by theneva** [prettier/prettier#6965]
Hi! :wave:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACKBXANrgSwGcALDSAQ1ziLAKgHMAaDXCBgsKjCABzgBOFGBAFEWFKABMMAIwgRqknvyEixcuCQoA3OBhgl9RCgFs4AHSgADAIz2HDjACZXbtxgDM3nz4wAWQKCgjABWcIiIjAA2WLi4jAB2ZJSUjAASYFsMAH4clwBfawBuKztHRxd3dy9fXwDg4LDIyJj4+KTU1IysjAAyPsKSsorK6pq6+samltb2jq7uzOyAHxWh0ptRp3GPSb9pkNmo+YTFtOWMdecizat0A0EoCgEATwxebFIaAyMMAHcSIp9HAAB68AQ0IgEaAGCAYChYOD-Vj0SxbbbZXauWr7BqHZrHNqnTrnHrZfLZJAbKwgJggPgwGFQIjIUAvAQQf4ABReCFZKF0EAIUjpIFkQjAAGs4DAAMq8Ch0RjIGACbBwekkGCmXAAdRIBHgREVYDgcv5RoIOiNr2Q4CIrPp9CIghg3KEDFMFGQADMqK76QArIiggBCkpl8rMcAAMmi-QHNSAQ6C5fQGNQAIrYCDwRO4QMgRViQT22QUWRwXBiiH0GB6kWGZAADgADPSIRBXXqhLx7RCaII9GKAI65+AevgCkAUIgAWigcDgUhXYsh44IkI9FC9PqQ-sLyddpgIqvVx4z2YncALRZglcbUmbSGc9LVFAIhEYAGEIKZvXtKBoFvekvjgAAVSsBUPIsdA1ABJaQEHlMABAIXgYAAQWkOUYFeag7zgAoCiAA)

This happens with both the Babel and TypeScript parsers.

**Input:**
```jsx
// nullish coalescing, logical operators, and boolean operators behave the same
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 ?? 2}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 && 2}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 || 2}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 | 2}`;

// ternary pushes the whole expression to a new line
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 ? 1 : 2}`;
```

**Output:**
```jsx
// nullish coalescing, logical operators, and boolean operators behave the same
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 ??
  2}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 &&
  2}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 ||
  2}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${1 |
  2}`;

// ternary pushes the whole expression to a new line
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${
  1 ? 1 : 2
}`;
```

**Expected behavior:**

I think the non-ternary cases look pretty ugly. I would expect all of these statements to mimic the behaviour of the ternary expression case, yielding this output:

```jsx
// nullish coalescing, logical operators, and boolean operators behave the same
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${
  1 ?? 2
}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${
  1 && 2
}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${
  1 || 2
}`;
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${
  1 | 2
}`;

// ternary pushes the whole expression to a new line
`111111111 222222222 333333333 444444444 555555555 666666666 777777777 ${
  1 ? 1 : 2
}`;
```

**Comment by evilebottnawi** [comment]
i think it makes sense

**Comment by lydell** [comment]
Sometimes breaking like this:

```js
`abc ${...
  ...}`
```

…and sometimes like this:

```js
`abc ${
  ...
}`
```

…sounds like a bug to me. We should always print like the second example.

**Comment by evilebottnawi** [comment]
@lydell :+1: Let's mark as bug

**Comment by evilebottnawi** [comment]
Feel free to send a PR with fix

**Comment by theneva** [comment]
Cool! I have no idea how to fix this, I'm afraid :sweat_smile:
