### ISSUE TITLE
Redundant parens inserted around JSX inside NewExpressions

### ISSUE THREAD

**Issue by rtsao** [prettier/prettier#6969]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEU4HcAEAxCEAUAPAMIQC2ADtAjJgPQB8AlANwgA0IEFMAltAGdkoAIYAnMRHQAFcQiEoRANwi8AJhxAAjMSLABrODADKFPbygBzZDDEBXOJwAWMMgBsA6k97wBZsHDG8j68Sj4AnsjgAkKcFgJwYjDSupZkIsgAZiJuCZwAVgIAHgBCugZGxiJkcAAyFnBZOXkghUXGFpZucACKdhDwTbmOIGZiCWJRWiJacG6aFGIWMB7qME7IABwADJyLEAkeuhRRi3ATSo2cAI798CncCiAiAgC0aHBqn5picLe8vxSIjSGSQ2WGnASZF4NnsIwEnW6fQGjTBzRGMBmqzU62QACZOLYRLw3J1SGR0lEoNRNHYEgAVGYKcEtJQOACSUC+sGMYCWPAAglzjDBwt0hgkAL6SoA)
```sh
--parser babel
```

**Input:**
```jsx
new Foo(<Component />);
```

**Output:**
```jsx
new Foo((<Component />));

```

**Expected behavior:**

```jsx
new Foo(<Component />);
```

No parens should be inserted (like is the case when the `new` keyword is omitted)

**Comment by thorn0** [comment]
Thanks for the issue. Would you like to submit a PR with a fix for it? It looks simple enough to be a good first contribution.
