### ISSUE TITLE
Word in TSX is forced onto the previous line with an added space literal after it

### ISSUE THREAD

**Issue by PachowStudios** [prettier/prettier#6970]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwHIdTy6BuAHSg2z32H0agATODgAqEAMowSMVGACyJHAGsArpnwBffFRr1GZGAFpBNAPQBnEQDcRrDhzgAPbpVVRyqaPjAH48uAsLEgBzOAAKTGpMCyR8EigATwBKXg58fjgYVRwoNLyM-AtVACMAKzhyOIADUUCYaoAadMLIWAQYOIFhMUlpWQUlNUxwlsL8AB4APjHxycwZgrnC0QALVAt8Dfj8YXRoCxgcGS88iAodilx0GVkoEK2g1TgAOnxZ5YBhABs5ZUmSPhVowKABeYDVGDre5mAAkwCiEBiL1Qgk01U0U1WIjgEzMJCmOlwuyyJFQ3wsLw+hTxC2peKmzSW+GSTIymnYUE0HBAjRASNkB2QoCU1AA7gAFJQICzIEAkawQVG8kAlY5gZRZCSYMioe7II7PPmrGDob4AdXW8AsOrAcAkMtQsmsTsScrAQRVeqseAlxxCN2QFBIFLgfLKFicACF1ZqYBISOg4AAZPVwIMhqzhyMSPUhb5wACKqgg8Azob5OpwPrlMESmECvlQmBgKqiepg5tRUOQAEYAAz9yvUKzm46YOVRQI2dN8gCOJfgfqRspQJAsRigcDgwkEKsYC9QjD9oUDSGDFZAVnQqANOCNV7zBeLpfTSENYZA0hKXcEPaQABMfJHGSvz3J8NBniAUDQLOICqFYogkCUq4XlmIDWM8ACSQgdBITYtgAgkIUiJAW5ZWJomhAA)
```sh
--parser typescript
--print-width 100
--single-quote
--trailing-comma all
```

**Input:**
```tsx
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

export function createMessage(props: any) {
  return {
    subject: `Test`,
    content: renderToStaticMarkup(
      <>
        <p>
          This is a demonstration of a formatting issue. 
          Click <a href={`thing/${props.id}`}>here</a> for details.
        </p>
      </>,
    ),
  };
}
```

**Output:**
```tsx
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

export function createMessage(props: any) {
  return {
    subject: `Test`,
    content: renderToStaticMarkup(
      <>
        <p>
          This is a demonstration of a formatting issue. Click{' '}
          <a href={`thing/${props.id}`}>here</a> for details.
        </p>
      </>
    )
  };
}
```

**Expected behavior:**
*Unchanged*
```tsx
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

export function createMessage(props: any) {
  return {
    subject: `Test`,
    content: renderToStaticMarkup(
      <>
        <p>
          This is a demonstration of a formatting issue. 
          Click <a href={`thing/${props.id}`}>here</a> for details.
        </p>
      </>,
    ),
  };
}
```

**Comment by lydell** [comment]
Hi!

Yes, this is how Prettier works. It takes care of where to put line breaks in your JSX text so that you don’t have to. See  #4223 for more discussion.
