### ISSUE TITLE
Incorrect handling comments in labeled statements

### ISSUE THREAD

**Issue by clement26695** [prettier/prettier#6983]
Reformatting of labeled statements with comments is not stable. Here is one example:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbCEAOBGJACAHSgHpj4BnGIyKSvASzwF48BmAbiJABoQsZ60cslABDAE7iIAdwAKEhMJSiAbhHoATHiABG40WADWcGAGVMB+lADmyGOICucXgAsYAW1QB1F-QoWwOFNFP3oVPwBPZHByYV4rcjhxGFl9a3dRZAAzUVRE3gArcgAPACF9IxNTUXc4ABkrOGzc-JAi4tMra1Q4AEUHCHhmvOcQC3FE8WidUR04VG1McSsYL00YF2QADgAGXiWIRK99TGiluEmVJt4ARwH4VKwlEFFyAFooODgNb+1xODu9H+qVE6UySByI14iXc9DsjlG5C6PX6gyaEJaoxgszWGg2yAATLx7KJ6KgugBhCDuDLRKDQa4gByJAAqsyUkNaKicAEkoD9YKYwMtMDAAIL80wwCI9YaJAC+8qAA)
```sh
--parser babel
```

**Input:**
```jsx
loop1: 
//test
const i = 3;

```

**Output:**
```jsx
loop1: //test
const i = 3;

```

**Second Output:**
```jsx
//test
loop1: const i = 3;

```

**Expected behavior:**
It should be consistent. I think putting the comments above the labeled statement is the expected behavior. I have a PR incoming to fix this

**Comment by bakkot** [comment]
Nitpick: you can't label `let` or `const` declarations in JS, so for the changelog it might be better to choose an example program which has a different kind of label, like

```js
label: 
//test
foo();
```
