### ISSUE TITLE
Comments starting with `:` are duplicated after JSX

### ISSUE THREAD

**Issue by Flcwl** [prettier/prettier#6995]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjGUCCYYEtoDOA2gIwC6ABALwUAUAlNQHx0A6UFFAPKgK4wxoLeARjcA9HwFD2nceIpIRMAMLt6IADQgIABzyFkoAIYAnUxADuABTMICyEMYBuEXABMtaU8bABrOBgAZV1fXCgAc2QYU144bQALGABbABsAdQTcEVCwOCD7bNxnbIBPRzACB21wgjhTGGsfCOTjZAAzY1S67QArAgAPACEff0Cg42S4ABlwuA6unpB+gaDwiNS4AEVeCHgF7viQUNM600dUY1Q4VK9dU3CYdI8YBOQADgAGbXuIOvSfLpHPc4GdnPNtABHXbwJp6BwoYwEAC0UDgcHcGK8pjg0NwOKaxhabSQnUO2jqyVw0ViRwI602Oz281JiyOMCuz3cr2QACZtDFjLhUusVBBkq1HFBoBCQLw6gAVK4IslLZxxACSUExsCCYAe+kw2qCMFKmwOdQAvpagA)
```sh
--parser babel
```
Doesn't happen with `flow` and `typescript`.

**Input:**
```jsx
btnActions[1] = () => (
  <button> test </button>
  // :testC
)
```

**Output:**
```jsx
btnActions[1] = () => (
  <button> test </button>
  // :testC
 /*:testC*/);

```

**Second Output:**
```jsx
btnActions[1] = () => (
  <button> test </button>
  // :testC
  /*:testC*/
 /*:testC*/);

```

<details>
<summary>Original report</summary>

**Prettier 1.18.2**

# Options (if any):
```
{
  "singleQuote": true,
  "printWidth": 100,
  "semi": false,
  "useTabs": false,
  "trailingComma": "es5",
  "arrowParens": "always",
  "bracketSpacing": true,
  "jsxSingleQuote": false,
  "jsxBracketSameLine": false,
  "overrides": [
    {
      "files": ".prettierrc",
      "options": { "parser": "json" }
    }
  ]
}

```

**file: **
**.js|x

**Input:**
As the gif, formatting maybe incorrect when adding a comment such as `//:testC`.

**Output:**
![prettier-bug](https://user-images.githubusercontent.com/26050644/69043995-175e0600-0a2f-11ea-8d8a-b9546b0b180c.gif)
notes: formatting with `prettier` by clicking [format document].

**Expected behavior:**
I think that it shouldn't inset a comment (such as `/*: testC */`) when format the code.
</details>

**Comment by evilebottnawi** [comment]
Please format your issue according to the template, otherwise it will be closed, thanks

**Comment by Flcwl** [comment]
Can‘t reproduce it when using Playground link.

**Comment by thorn0** [comment]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjGUCCYYEtoDOA2gIwC6ABALwUAUAlNQHx0A6UFFAPKgK4wxoLeARjcA9HwFD2nceIpIRMAMLt6IADQgIABzyFkoAIYAnUxADuABTMICyEMYBuEXABMtaU8bABrOBgAZV1fXCgAc2QYU144bQALGABbABsAdQTcEVCwOCD7bNxnbIBPRzACB21wgjhTGGsfCOTjZAAzY1S67QArAgAPACEff0Cg42S4ABlwuA6unpB+gaDwiNS4AEVeCHgF7viQUNM600dUY1Q4VK9dU3CYdI8YBOQADgAGbXuIOvSfLpHPc4GdnPNtABHXbwJp6BwoYwEAC0UDgcHcGK8pjg0NwOKaxhabSQnUO2jqyVw0ViRwI602Oz281JiyOMCuz3cr2QACZtDFjLhUusVBBkq1HFBoBCQLw6gAVK4IslLZxxACSUExsCCYAe+kw2qCMFKmwOdQAvpagA)
```sh
--parser babel
```

**Input:**
```jsx
btnActions[1] = () => (
  <button> test </button>
  // :testC
)
```

**Output:**
```jsx
btnActions[1] = () => (
  <button> test </button>
  // :testC
 /*:testC*/);

```

**Second Output:**
```jsx
btnActions[1] = () => (
  <button> test </button>
  // :testC
  /*:testC*/
 /*:testC*/);

```

**Comment by thorn0** [comment]
Another example from #13685:

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAjgO5wBOMAngBQCU+wAOlPvmXDOmS9c66wHoAVDgDOAYQA2AQwC2ABzgATasHwA3aZPRwk+HLHKbJAGnyzpADz2iY0iqICCMfAF96AfnxCBffgB4AZThsPBYwGVFRADk5OABeYFtKSThRADpRENxoV3wAI2kwAGsAczIITCUAPj9+fH9ReWkoWpZ6-mB4SxhXPWAlOEk7PNUlaXh3OoCBJpa2joYcSBYAMlWGnFlS-FEyMETl3PwtGHjGEABJFYv8COko2NkEpKpUjKOoPIFq12n-ATBULQar4YT4PRQdCSSQ+Py0ADczFcIBMIAg8hyUFEyFA9gqxAACvYEDiUFpiNJKDi0fkyEVihxAnEADIGODIVBaLK0+klJnNMAGUrIGBkHRouCyfLKQZKFktUroaSlOAAMQgZAsMFwUBF5PQMAgqJAAAsYLJJAB1U04eBzMBwYLYu04dR2yjIcBRE0GLIUQn00oWTncuBogBWoksgWFqQAiugIPBQ5IeSBmmR-V7CjLJCb5GQDDArTglDBTcgABwABjRhYgWSt9PkXsLaSMHLRhCT8EDGLJIAeAFooHBlMoTewezh2IGVSGkFy0+GQFlZDhReLV6I43BE8mOUuw2i7PlS+XK0gAEyn+k4STC8QQWSLkBpACsJvQWQAKtJ8jJZd03UHRLigQZYECMAi0xRwIMCN4j2AuBXFcIA)

```sh
--parser babel
```

**Input:**

```jsx
function qwerty() {
  return (
    /*isClamped({ value: interval, max: startsAt }) ? */
    <Section className={styles.section} background>
      <span>
        {text}: {delta} ({date})
      </span>
      {icon && <img src={icon} alt="Icon" className={styles.icon} />}
    </Section> /* : null*/
  );
}
```

**Output:**

```jsx
function qwerty() {
  return (
    /*isClamped({ value: interval, max: startsAt }) ? */
    <Section className={styles.section} background>
      <span>
        {text}: {delta} ({date})
      </span>
      {icon && <img src={icon} alt="Icon" className={styles.icon} />}
    </Section> /* : null*/
   /*: null*/);
}

```

**Comment by thorn0** [comment]
Fixed by https://github.com/prettier/prettier/pull/13687
