### ISSUE TITLE
Extra parentheses and spaces added to TypeScript

### ISSUE THREAD

**Issue by David-Else** [prettier/prettier#6997]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgOLoC2cA8gEYBWcYMOwAOlDjpFJjAE4CuNEHAFAybMcABwiYAljEnQANIxE4AbnFQQw0gJ4LhzAAoALLVLCZdSvB3SjDksxZEBJKKK4xHAXyR1FI8VIy0D4AatQwfABMANx+zKrqmjBaoeFRsXo4Rib2mD5CSsxQcADuOPwAlD7ZppgAwhCE4sWwGUqebSJWNnZm+XEixWWVPt22uQ1N0AgwncwdAy5uMP2ZRaXlVThL7pPNM3M4C8KeFb6ZMHaYAHQB0rJMALxiEvfyA5eSNwka2jjPPySOg+V2uklc7n+OCG2whMEqh0+N1sOTMUJhNVyCJBX2uAHNrOM0c8YWNephsSdGJ5GCA5CAIKIgmxkKB0BwOBASvp2QhMMgQOhlBBJAATOkgMjWMAAazgMAAyqJ0JooHjkJwuHB6YYYIRUAB1OzwTDKsBwBV8+7KbQCsz8+ngzBwDgwfTWPGEdDIABm6FQzvpFEwAA8AELSuWKohwAAy4Lgvv9gZAwZDCvBeNQcAAilwIPAkwHtSBlRxnRwBWR0GQ1BLRBxwTADWLLsgABwABnpDYkcANhIFDbgFdUEoAjvn4O7GfyUFgALTFOCilcSjhwSeSDfu9Ce71IP3F+nOwiSDXcEtSNXZvMFxOH5MlmA1luittISL0zjoSSoTOTF6ApQNMEpcM6AAqNZzkeKbKFqLirrACpgI2TIAIJQKKCrJNmRbOp4nhAA)
```sh
--parser babel
```

**Input:**
```jsx
class GameObject {
  constructor({
    position,
    velocity,
    Physics,
    Graphics,
    Input,
  }: {
    position: Vector2;
    velocity: Vector2;
    Physics: {
      new (): PhysicsComponent;
    };
    Graphics: {
      new (): GraphicsComponent;
    };
    Input: {
      new (): InputComponent;
    };
  }) {
    this.position = position,
    this.velocity = velocity,
    this.input = new Input();
    this.physics = new Physics();
    this.graphics = new Graphics();
  }
}

```

**Output:**
```jsx
class GameObject {
  constructor({
    position,
    velocity,
    Physics,
    Graphics,
    Input
  }: {
    position: Vector2,
    velocity: Vector2,
    Physics: {
      new(): PhysicsComponent
    },
    Graphics: {
      new(): GraphicsComponent
    },
    Input: {
      new(): InputComponent
    }
  }) {
    (this.position = position),
      (this.velocity = velocity),
      (this.input = new Input());
    this.physics = new Physics();
    this.graphics = new Graphics();
  }
}

```

**Expected behavior:**
```
    this.position = position,
    this.velocity = velocity,
    this.input = new Input();
    this.physics = new Physics();
    this.graphics = new Graphics();
```

**Comment by thorn0** [comment]
Works as intended. That's how Prettier formats [the comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator). I think you used this operator instead of semicolons by mistake.

**Comment by David-Else** [comment]
@thorn0 You are right! Thanks :)
