### ISSUE TITLE
"export default async function" wraps function in parenthesis

### ISSUE THREAD

**Issue by stewartulm** [prettier/prettier#700]
`"export default async function"` adds an unnecessary parenthesis around the entire function:

```
export default async function foo() {
  console.log('Hello, World');
}
```

turns into:

```
export default (async function foo() {
  console.log("Hello, World!");
});
```

If I remove either the `"default"` or `"async"` modifiers, this issue is no longer triggered.

**Comment by existentialism** [comment]
It's due to an upstream issue in Babylon (fixed: https://github.com/babel/babylon/issues/257), and should be resolved once we ship the next Babylon release (soon!)

**Comment by vjeux** [comment]
This is also an issue with flow parser btw.

**Comment by vjeux** [comment]
@existentialism any idea if a new version of babylon has been released with the fix?

**Comment by existentialism** [comment]
The fix is currently in `babylon@7.0.0-beta.4`, not sure if/when it'll get back ported to 6.x as we'd also need to backport a fix in babel proper.

**Comment by vjeux** [comment]
@existentialism okay perfect! No need to backport it to 6.x, we'll just upgrade to 7 when it is released :)

**Comment by vjeux** [comment]
Looks like updating to the latest beta just works and doesn't require any changes nor breaks anything else :) https://github.com/prettier/prettier/pull/1047
