### ISSUE TITLE
[RFC] remove option `vueIndentScriptAndStyle` or rename it to treat all html style files consistently

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#7000]
First of all, we have https://prettier.io/docs/en/option-philosophy.html

Secondly, 

> Besides, I even don't like option vueIndentScriptAndStyle personally, why it's related to vue only? Svelte has .html/.svelte as SFC also. We should treat them as html without distinction, and we should have only one style for html like files: indented or non-indented everywhere. Why should we care about that. Just accept the default formats, you will be happy all the time someday.
>
> No more options please until it breaks your codes like #5588 or #6626.

See my comments at https://github.com/prettier/prettier/pull/3903#issuecomment-554695922

`.vue` is should not be treated specially. 

My personal idea approach:

1. Remove the option, treat `.vue` not specially, `indented or non-indented everywhere even for head and body tag`
2. Rename the option to affect all html like files

---

Besides, shall we have a separate repository for RFCs?

**Comment by lydell** [comment]
Hi!

Unfortunately, you’re too late to the game. This has already been discussed to death in #3888, where even the creator of Vue pitched in. I don’t want the option either, but now we have it.

We also explored having it general for all HTML like files, but it didn’t work out. Read through #3888 and the PRs that link to it for the full history.

**Comment by JounQin** [comment]
@lydell 

Now we will have 2.0 to include BREAKING CHANGES, don't we? I recommend to retalk about it again. Of course, I'm free to be rejected.
