### ISSUE TITLE
Prettier creates Eslint warnings in some situations

### ISSUE THREAD

**Issue by fab1o** [prettier/prettier#7012]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLGAKA5AYgIZgyoBue8AogB7wBOUeANgCoQDWCABAM4AWEArgwAmHGnBj86HAkVIVqcOoxbsoAOhkkycKrXrM2nAO49OXGGX5cOkIXA6prAJgAMTrABppXAJ5QwHBgAlBwAvAB8HMAcAPQxHHBcDKiwALRCjngARgxwqclQ9gC2eJT5CAA6UBw1sTFqDVUAvkEA3CAeIBAADkTQXMigeDQ0EEYACsMIAyh4xBCoQh0gWTQE7DAAyt0EKQDmyDA0-HCdPDBFDADqPOiJO2Bwm9PoJOg+yOBcA50pXIowcZrPYlZAAM0Y-06ACsuJQAEJrMAbTZ4IpwAAyKTg4MhpxAsMom32uQAivwIPBDsd8TsaP8aJ8stk4Axlt0aCkYFdFjAeMgABwuTociD-K5rbqfRhGPA+H4gACOFPgQJ6MxAeC4qUKcDsS06YmVqDEQLwILwuIYUJA-yKqGpJ06XBJcHJlJxSCOTpAFiyPKEfOQABZOkc8KgCnsAMIQIqglBQaA4zpWOBMbIzCHWuBNJpAA)
```sh
# Options (if any):
--single-quote
--print-width 80
```

**Input:**

There's an Eslint disable comment at the end of the line

```jsx
it('#activateExternalToken should return activateExternalToken.activateExternalToken when status code is 202', async () => { // eslint-disable-line max-len
  //...
});
```

**Output:**

it drops the comment to the next line causing it to create an Eslint warning

```jsx
it('#activateExternalToken should return activateExternalToken.activateExternalToken when status code is 202', async () => {
  // eslint-disable-line max-len
  //...
});
```

**Expected behavior:**

Should remain the same with the Eslint disable comment on the same line

```js
it('#activateExternalToken should return activateExternalToken.activateExternalToken when status code is 202', async () => { // eslint-disable-line max-len
  //...
});
```

**Comment by lydell** [comment]
Hi! This is a known issue of a difficult problem.

We suggest using `eslint-disable-next-line` instead – it generally works better. See https://prettier.io/docs/en/rationale.html#comments for more information.

Hope this helps!
