### ISSUE TITLE
Question/Output for Prettier results

### ISSUE THREAD

**Issue by ffahri** [prettier/prettier#7022]
Hey does Prettier supports output file for results such as junit or json ?

**Comment by lydell** [comment]
Hi! No, I don’t think so. What would you expect to find in such a file?

**Comment by ffahri** [comment]
Junit formatted results to show users
Such as eslint --formatter functionality

**Comment by lydell** [comment]
I’m not familiar with Junit and `eslint --formatter`. Could you provide an example?

Prettier doesn’t have much more to say than “I formatted this file (and it took this long)”, “This file is already up-to-date” and “I encountered an error for this file”. What are you going to use the Junit output for?

**Comment by ffahri** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<testsuites duration="50.5">
    <testsuite failures="0" name="Untitled suite in /Users/niko/Sites/casperjs/tests/suites/casper/agent.js" package="tests/suites/casper/agent" tests="3" time="0.256">
        <testcase classname="tests/suites/casper/agent" name="Default user agent matches /CasperJS/" time="0.103"/>
        <testcase classname="tests/suites/casper/agent" name="Default user agent matches /plop/" time="0.146"/>
        <testcase classname="tests/suites/casper/agent" name="Default user agent matches /plop/" time="0.007"/>
    </testsuite>
    <testsuite failures="0" name="Untitled suite in /Users/niko/Sites/casperjs/tests/suites/casper/alert.js" package="tests/suites/casper/alert" tests="1" time="0.449">
        <testcase classname="tests/suites/casper/alert" name="alert event has been intercepted" time="0.449"/>
    </testsuite>
    <testsuite failures="0" name="Untitled suite in /Users/niko/Sites/casperjs/tests/suites/casper/auth.js" package="tests/suites/casper/auth" tests="8" time="0.101">
        <testcase classname="tests/suites/casper/auth" name="Subject equals the expected value" time="0.1"/>
        <testcase classname="tests/suites/casper/auth" name="Subject equals the expected value" time="0"/>
        <testcase classname="tests/suites/casper/auth" name="Subject equals the expected value" time="0"/>
        <testcase classname="tests/suites/casper/auth" name="Subject equals the expected value" time="0.001"/>
        <testcase classname="tests/suites/casper/auth" name="Subject equals the expected value" time="0"/>
        <testcase classname="tests/suites/casper/auth" name="Subject equals the expected value" time="0"/>
        <testcase classname="tests/suites/casper/auth" name="Subject equals the expected value" time="0"/>
        <testcase classname="tests/suites/casper/auth" name="Subject equals the expected value" time="0"/>
    </testsuite>
</testsuites>`

this format (junit xml) will integrated with most of the ci tools etc. 
This would be useful if user can be see their error from prettier

**Comment by lydell** [comment]
How would you imagine the XML looking for Prettier’s output? The above example mentions `testsuite` and `testcase` but Prettier has no such things.

**Comment by ffahri** [comment]
Yes thats the generated. Such as other tools has formatting output flags. 
Its also can be used json or html formats etc not only for junit.
Is there any plan to make output file and formats for Prettier in future

**Comment by thorn0** [comment]
@ffahri You didn't answer the question.

**Comment by viceice** [comment]
I would like to have an output format like checkstyle or junit (or any other compatible format), so i can track issues with jenkins  [Warnings Next Generation](https://plugins.jenkins.io/warnings-ng/) plugin.

**Comment by thorn0** [comment]
@viceice [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) + `eslint --formatter` is probably what you need.

**Comment by viceice** [comment]
I know that, but what about other file types, like `html`, `xml` ...

**Comment by thorn0** [comment]
A standalone tool inspired by `eslint-plugin-prettier` can be built for them, but it's out of scope of the core Prettier library / CLI. At least for now.

**Comment by adidahiya** [comment]
I'm still interested in this feature in the core prettier library, it would be nice to have. I'd like to avoid running eslint-plugin-prettier on my TypeScript codebase because it requires every file to be parsed a second time ([see typescript-eslint FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#eslint-plugin-prettier)). So I run the `prettier` CLI separately in a CI task. I'd like to see formatting errors reported as junit results in that CircleCI task.
