### ISSUE TITLE
Formatting in markdown cannot be ignored in all cases

### ISSUE THREAD

**Issue by domoritz** [prettier/prettier#7027]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRGYDOMAhgTDtgHwA6UAxPxwARCGACuAWwSsy0HAHkAbhSXkA7n2BIAdHQD6MMQF8+fXABUFAYS1IjYU1AzZ8REuUo06DBABNOTC4QABoQCDw5KEZkUDYCCHUABTYEGJQWJQhSP1CQACMCFjAAa2IAZTxi0ihqZBgCcTgwgAsYSQAbAHUW0nhGKrA4crS+0jUYAE9kcEYYsJrGChgkoupJFmQAMxYOpbCAK0YADwAhItKKlmkAGRq4bd39kCPj8prqDrgARXEIeEee2aICqBCWBBmGwIJT8iSgeUINRgXRyMBayAAHAAGMKECBLLpFPAzQhwcEqPIARz+8FWEXSIBYjEwUDgcD87LyRGppCIqxY602SB2QLCS0kpHqjWBjA+X1+-wewqewNY+RRfjRyAATGEGixSB0PtYIJINjM6Ky8uIlhYWPl0iLnkomgBJKAc2DlMAEUiRACCHvKUy+gKWxmMQA)

**Input:**
```md
## Documentation Overview
{:.no_toc}

- TOC
{:toc}
```

**Output:**
```md
## Documentation Overview

{:.no_toc}

- TOC
  {:toc}

```

**Expected behavior:**

**Output:**
```md
## Documentation Overview
{:.no_toc}

- TOC
{:toc}
```

The formatter currently changes the behavior. The prettified version doesn't render the same. 

Ignoring ranges also does not work because of https://github.com/prettier/prettier/issues/5557

**Comment by evilebottnawi** [comment]
It is expected for markdown parsers `{:toc}` is part of list, try to put this:

```markdown
- TOC
{:toc}
```

in github issue text field and look how github render this. Due it is not standard syntax you can't use markdown printer in your case, you need own plugin for this case or changed something in you build process

**Comment by domoritz** [comment]
I can set prettier to ignore the 

```md
- TOC
{:toc}
```

I have not found a way to ask prettier to ignore the missing newline after the header. I believe it's a bug/missing feature that formatting cannot be ignored.

**Comment by thorn0** [comment]
Works if you add an empty line after `{:toc}` to close this list. Does this help?

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwBwE5wwwCWcemxA5lBAZgM4wCGeM2AfADpQDEPABABEIYAK4BbBMxLR+-APIA3MotIB3bsCQA6GgH0YIgL7dumfgBV5AYU1JDYE1G4Zs+QiTIVqtOJgQAJhwgADQgEDgyUPTIoCx4EGoACiwIMShMihDEAaEgAEZ4TGAA1oQAyjjFxFCUyDB4onBhABYw4gA2AOotxPD0VWBw5Wl9xKowAJ7I4PQxYTX0ZDBJRZTiTMgAZkwdS2EAVvQAHgBCRaUVTJIAMjVw27v7IEfH5TWUHXAAiqIQ8I89s0QFU8Es8DMNngSgFElA8vgajAujkYC1kAAOAAMYXwECWXSKOBm7nByjyAEc-vBVhF0iAmPRMFA4HAAmy8gQqcQCKsmOtNkgdkCwktxMR6o1gfQPl9fv8HkKnsDmPkUQE0cgAExhBpMYgdD7WCDiDYzGgsvKiJYWJj5dLC56KJoASSg7Ng5TAeGIkQAgu7ylMvoClkYjEA)
```sh
--parser markdown
```

**Input:**
```markdown
<!--prettier-ignore-start-->
## Documentation  Overview
{:.no_toc}

- TOC
{:toc}

<!--prettier-ignore-end-->
```

**Output:**
```markdown
<!--prettier-ignore-start-->
## Documentation  Overview
{:.no_toc}

- TOC
{:toc}

<!--prettier-ignore-end-->

```

**Comment by domoritz** [comment]
Wooow, that fixed it. Thank you @thorn0!

What's the rule here? Do you want to update the docs at https://prettier.io/docs/en/ignore.html#range-ignore?

**Comment by thorn0** [comment]
That's how markdown works. You tried to put the closing comment inside the list.

It'd be easy to understand if we draw an analogy with HTML:
```html
<!--prettier-ignore-start-->
<ul>
  <li>
    TOC
    {:toc}
    <!--prettier-ignore-end-->
  </li>
</ul>
```

If you know how to describe this in the docs to avoid confusion in the future I'd be happy to review a PR.

**Comment by domoritz** [comment]
I see. I've been writing HTML and Markdown for years and didn't realize the issue since markdown doesn't have closing tags. I can't think of a good way to phrase this for the docs but will send a PR if I come up with something.
