### ISSUE TITLE
Could not load existing sourcemap of "../node_modules/prettier/parser-typescript.js" when including the Prettier library

### ISSUE THREAD

**Issue by acobster** [prettier/prettier#7037]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: API
- Runtime: Node.js v10.5.0
- Operating System: Linux (Ubuntu 18.04)

**Steps to reproduce:**

Repro steps in README here: https://github.com/acobster/prettier-bug

**Expected behavior:**

When I install prettier via `yarn add prettier`, `import` it normally within my app code, and build with `yarn parcel build src/index.html` I expect it not to throw any errors. :)

**Actual behavior:**

When running the build step, it hangs, spits out a bunch of compressed JS code, and then says:

> ⚠️  Could not load existing sourcemap of "../node_modules/prettier/parser-postcss.js".

Full output of the `yarn parcel build src/index.html` command in [`parcel.out`](https://raw.githubusercontent.com/acobster/prettier-bug/master/parcel.out).

**Comment by thorn0** [comment]
No idea what exactly is going on here, but in the browser `prettier/standalone` is supposed to be used, not `prettier`. See https://prettier.io/docs/en/browser.html

Does this help?

**Comment by acobster** [comment]
Yes, sorry I didn't understand the distinction between API and Browser. :smile:
