### ISSUE TITLE
CLI: add a `recursive` option

### ISSUE THREAD

**Issue by fberrez** [prettier/prettier#7048]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: CLI
- Runtime: Node.js v12.5.0
- Operating System: macOS Cataline 10.15.1

**Steps to reproduce:**

My request is about a `recursive` option.

`$ prettier --write *` only fixes the first-level files and does not read any other files that are in sub-directories.

**Expected behavior:**

```sh
# Reads all sub-directories and first-level files and fixes them.
$ prettier --write --recursive *
```

**Actual behavior:**

```sh
$ prettier --write *
index.js 84ms

$ tree
.
├── index.js
├── app
│   ├── controllers
│   │   ├── authentication.js
│   │   ├── healthcheck.js
│   │   ├── index.js
```

**Comment by evilebottnawi** [comment]
It is expected because glob resolve `*` as top level files, we don't need `recursive` option, you can use `{**/*,*}.{js,json,md,yml,css}` for all files right now, also we have issue https://github.com/prettier/prettier/issues/6085 for using `.` and all nested supported files for more 0CJS, thanks for issue

**Comment by fberrez** [comment]
Your command only works for top- and second- level files (files located in a sub directory).

**Comment by sregg** [comment]
I have the same issue as @fberrez, `npx prettier --write src/**/*.{js,jsx,ts,tsx,json}` only runs the command for the first 2 levels inside `src`

**Comment by thorn0** [comment]
@sregg I guess your shell expands the glob, not Prettier. Try adding quotes around the glob.

**Comment by sregg** [comment]
oh wow that worked. Thanks @thorn0 !
