### ISSUE TITLE
Idempotence testing: prettier(code) == prettier(prettier(code))

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#7055]
The tests don't contain such a check as of now. Let's add it.

Previous discussions: https://github.com/prettier/prettier/issues/2803#issuecomment-329671900, https://github.com/prettier/prettier/issues/3512#issuecomment-352622275

**Comment by SMotaal** [comment]
Since this **Presented** in #7050, I am interested to keep track and know when it lands to retest in vs code.

<details>

## Presentation

1. Given the following code fragment in `Untitled-1` <kbd>js</kbd>:

   ```js
   typeof /** @type {typeof Matcher} */ (matcher.constructor).clone !== 'function'
   ```

2. Executing **Format Document** once, rewrites it as:

   ```js
   typeof (/** @type {typeof Matcher} */ (matcher.constructor).clone) !==
     "function";
   ```

3. Executing **Format Document** again, as:

   ```js
   typeof (/** @type {typeof Matcher} */ (matcher.constructor.clone)) !==
     "function";
   ```

</details>

Thanks!

**Comment by evilebottnawi** [comment]
It was discussed before, we can't do it, because in some cases can't be easy fixed and maybe even not fixable

**Comment by thorn0** [comment]
Doesn't sound like a good reason for not doing it. We can explicitly disable those specific failing tests (with an explanation comment). This way we at least will notice when something new breaks.

**Comment by SMotaal** [comment]
Thanks @evilebottnawi and @thorn0, I now fully appreciate the fine balance necessary between complicated testing on your end and regressions on the end-user side that are very hard to figure out when filing bugs. My hope from this is that end-users who don't understand all this do not end up with unpredictable linting when they merely updated a comment in some file one day and did not register there being linting side-effects.

**Comment by thorn0** [comment]
closed by https://github.com/prettier/prettier/pull/7565
