### ISSUE TITLE
Formatting functions composed from other functions - different behaviour 1.18.2 => 1.19.1

### ISSUE THREAD

**Issue by AdrianSkierniewski** [prettier/prettier#7060]
Hi,

After a minor upgrade of `prettier-eslint` from `9.0.0` to `9.0.1` I started observing different formatting behavior. After digging deeper I discovered that it was caused by `prettier` upgrade `1.18.2` => `1.19.1`. I scanned all open issues and I couldn't find anything that matches observer behavior, that's why I decided to create a separate issue.

I'd like to confirm that the formatting behavior observer bellow is a bug. 
Before `prettier` upgrade all functional code was formated in new lines so it was easy to read. After the upgrade, code that is short enough (most of the code) everything lads into single line which is harder to read, because you'd need to focus on brackets there to understand how the function works.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEYCGAHASxhwBsCAvOTAXmwgFs8I04AKAHSkzqgDc4ATgHM2kKLhisAlABpMAbU7dukRszZLl3GBACqePIJmatACzg4AJsa7LZJzMQIkb3ALr3bOgDIQA7kacUgDcIDIgEHgwBOjIoDgCAv4ACgkIaMggOLwQBJZhIABGAjhgANZwMADKeKUEUELIMAIArnDhpjD0JADqpkRwaLVgcFXpRAS8RACemWBoGeH1LAIwySVC9DjIAGakLOEAVmgAHgBCJeWVVTj0cN71cLv77SDHJ1X1QiRwAIotEHgzxIBxAtQEK0yhRwhTgJAKeAE9RgPTyMFMyAAjAAGbHhRHqHolPCZRGDQT8AoARwB8HWkQyKBwaAAtFA4HBLJyCgI4DSCLz1jhNtskHsQa8WPQCE1WpKvj9-oCnmKXuFiIVUZZ0cgAEzqkrOL4AYQYW0yUGgT3CLRYABUYYzxaDeG0AJJQLmwKpgJFRACCnqqMGmP2BLAAvhGgA)
```sh
--parser babel
--print-width 100
```

**Input:**
```jsx
const capitalize = compose(
  converge(concat(), [
    compose(
      toUpper,
      head,
    ),
    tail,
  ]),
  toLower,
);
```

**Output:**
```jsx
const capitalize = compose(converge(concat(), [compose(toUpper, head), tail]), toLower);

```

**Expected behavior:**
The `1.18.2` returned 
```jsx
const capitalize = compose(
  converge(concat(), [
    compose(
      toUpper,
      head,
    ),
    tail,
  ]),
  toLower,
);
``` 
which was easier to read

**Comment by lydell** [comment]
Hi!

It’s in the changelog/blog post: https://prettier.io/blog/2019/11/09/1.19.0.html#use-function-literals-in-arguments-to-detect-function-composition-6033-by-brainkim

Is this a duplicate of #6921?

**Comment by AdrianSkierniewski** [comment]
@lydell yes it looks like it. Thank you!

**Comment by lydell** [comment]
duplicate of #6921

**Comment by lydell** [comment]
Duplicate of #6921
