### ISSUE TITLE
Rehashed: Spaces inside JSX curly braces are removed

### ISSUE THREAD

**Issue by Hummel-Mors** [prettier/prettier#7067]
Copied from issue # 95

I would like to start the discussion again. It would be great, if the spaces were not removed.

I use to write my JSX like this

```javascript
<div className={ className }>
  Bla bla bla
</div>
```

Note the spaces inside the className curly braces.

But it's formatted like this

```javascript
<div className={className}>
  Bla bla bla
</div>
```

**Comment by lydell** [comment]
Duplicate of #2651
