### ISSUE TITLE
Verbose formatting for nested objects

### ISSUE THREAD

**Issue by Webbrother** [prettier/prettier#7068]
I found that prettier make code very very verbose. I use default config.

**Output:**
```ts
    this.form = this.fb.group({
      title: [
        '',
        {
          validators: [Validators.required, Validators.maxLength(40)]
        }
      ],
      description: [
        '',
        {
          validators: [Validators.required]
        }
      ],
      category: [
        '',
        {
          validators: [Validators.required]
        }
      ],
      tags: [
        [],
        {
          validators: [Validators.required]
        }
      ],
      dueDate: [this.minDueDate, { validators: [Validators.required] }],
      reward: [
        '',
        {
          validators: [Validators.required, Validators.maxLength(50)]
        }
      ],
      rewardLink: [''],
      owner: [
        '',
        {
          validators: [Validators.required]
        }
      ]
    });
```

Is there any way to make it less verbose?
For example:
```
    this.form = this.fb.group({
      title: ['',{
        validators: [Validators.required, Validators.maxLength(40)]
      }],
      description: ['', {
        validators: [Validators.required]
      }],
  ...
```

**Comment by evilebottnawi** [comment]
It is edge case because you have empty `string`, don't think we should change current output in that case, for me current output is more readable

**Comment by thorn0** [comment]
If you manually remove the line breaks after `{` in the object literals, the output will be [more compact](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACGALAlgZwHQBmEATgLaoC862+BARngObEQCuADgBTAA6UqAwTCwwANnCSoA2n0FzUAcgUAaWfIHB1cgG4BDUVgAmumCRySpANX1GTZvMTgBHVlkeHlqaweOni+Ul0ADwAZBEZMTgAWAAYASgBdNXUAX2TBBNV+eUM4HDBiLHZhaAt0uSUsrVRNatQ9Hzt-C29bP3xHFzc4QyTs1PLUTMGwEzhGEgBPMv75SsGNOvqbXzMWlaaO51d3Puq02YFhw-RdRnNpBelj6trqhra16VbV-wdt7t6rg-UbnNY4AARMYWTC4PCkLBQQEA4HwTyaB6vC5WDbtd5dXaoFJ-OSOADuumIhhm1XmJ0WdSRm3WjXRnR2PU8L02EOCYSgEQwnAArPE9lofvJcYICUTDCEoQBrCxKEUCCD4qBwYikrTk25LantWmPN4Mz4CgYnI3YuIAbhAyhAEGKWGgOGQoCJLHxAAUiQhHShdNoIEYrSA6MRdGApXAYABldihqGMZAwYgA60YGCkUQAdWw8BwMbAcEjXpEWG0IkmyHAOEd1qhOBVMDdIcYgWQBH0detACscEEAEIhsMRyO6UhwSXK1vtuBdnuRuPiACKrAg8Enog7IBj-hVFboujocFEgfYhVgGaMmGQAA4YtaTxA6xmQ+wKye8irtHBAy4V3BG7bvRAXQcAAWmVHoekDA1HEbM4WyQNt12nEA60hBMk2QnB5zgJdfzXDcYH3c9DEvJAACZrUTXQsAMTkAGEIFIeCQCgaAv2tVg6wAFX3b1EI3bQAQASSgXJYEjAoihgABBUTIxgSZxHwuAUhSIA). See https://prettier.io/docs/en/rationale.html#multi-line-objects
