### ISSUE TITLE
Unquoted numeric keys in JSON output

### ISSUE THREAD

**Issue by idler8** [prettier/prettier#7080]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwCMSA6ICG2C+IANCBAA4wCW0AzsqDgE6MQDuACkwnSjgG4RKAE2IgARoxxgA1nBgBlMlMpQA5shiMArnBIALGAFsANgHU9leDSVg487pcp9LAT2TgadEippxGMdklVQxxkADMcY18SACsaAA8AIUkZOXkcQzgAGRU4cMjokDj4+RVVYzgARS0IeHyo3RAlRl9GdzjoUTJGFRhTYRg9ZAAOAAYSbohfU0kyd264Vr48kgBHGvhA8h5cGgBaKDg4IWPRRjh1ynPAnGDQpAiGkl9DSg1tRpoyiuravIeCo0YDgxP0hINkAAmEiaHCUYxlADCEEMIXcUGgKxAWl8ABUQTxHoU+DoAJJQE6weRgHoUACCFPkMBcFXqvnw+CAA)
```sh
--parser json
```

**Input:**
```jsonc
{1:"a"}
```

**Output:**
```jsonc
{ 1: "a" }

```

**Expected:**
```jsonc
{ "1": "a" }

```

**Comment by evilebottnawi** [comment]
@thorn0 i don't think it is bug because json allow **only** double quotes  properties, we don't linter or fixer to fix problems in files, so we print this as is

**Comment by thorn0** [comment]
Strictly speaking, it's not a bug, right, but Prettier adds quotes around unquoted string keys in JSON, so it's reasonable to expect that it would do so for numeric keys too.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwCOSA6ICG2C+IANCBAA4wCW0AzsqDgE6MQDuACkwnSjgG4RKAE2IgARoxxgA1nBgBlMlMpQA5shiMArnBIALGAFsANgHU9leDSVg487pcp9LAT2TgadEippxGMdklVQxxkADMcY18SACsaAA8AIUkZOXkcQzgAGRU4cMjokDj4+RVVYzgARS0IeHyo3RAlRl9GdzjoUTJGFRhTYRg9ZAAOAAYSbohfU0kyd264Vr48kjQa+EDyHlwaAFooODghI9FGODXKM8CcYNCkCIaSX0NKDW1GmjKK6tq8+4LGjAcGJ+kJBsgAEwkTQ4SjGMoAYQghhC7ig0BWIC0vgAKsCeA9CnwdABJKDHWDyMA9CgAQXJ8hgLgq9V8+HwQA)
```sh
--parser json
```

**Input:**
```jsonc
{q:"a"}
```

**Output:**
```jsonc
{ "q": "a" }

```

**Comment by evilebottnawi** [comment]
@thorn0 i still think it is bug, i think we done this bug when have integrated json5 so i think we should avoid adding quotes for pure `json`

**Comment by thorn0** [comment]
I find this behavior, as well as replacing single quotes with double, pretty useful, e.g. for copy-pasting from JS (or Dev Tools, or elsewhere) to JSON.

**Comment by lydell** [comment]
Sorry, I have no input on this. But I did think of #6132. Not sure if it is related.

**Comment by thorn0** [comment]
It surely is related. I forgot that adding those quotes isn't as simple as it looks.

**Comment by idler8** [comment]
It is json not json5.
`{1:'something'}` is the wrong result
@thorn0

**Comment by idler8** [comment]
I don't care about formatting big numbers
Just need to resolve the current error
@lydell

**Comment by idler8** [comment]
Supplementary note
```
JSON.parse(`{
  1: 1
}`)
```
result
```
{}
```
Not what I expected, no error

**Comment by thorn0** [comment]
@idler8 As it's been written, Prettier is a code formatter. Fixing such errors is not a goal of this project.

**Comment by idler8** [comment]
My words may be overdone or unclear
I am not solving the error with Prettier
But Prettier returned me a wrong result
I need a standard JSON formatted content`{"1":"a"}`
But it gives me a non-JSON standard content`{1:"a"}`

**Comment by thorn0** [comment]
@idler8 You gave invalid input to Prettier, you got invalid output. That's expected. If Prettier made valid code invalid, that would be a bug, but it's not your case, is it?

**Comment by idler8** [comment]
But this is also an invalid input
`{b:"a"}`
It can be processed like this
`{"b":"a"}`
Is it different from this?
`{1:"a"}`
@thorn0
