### ISSUE TITLE
How use prettier in Webstorm with eslint integrations?

### ISSUE THREAD

**Issue by claudioviola** [prettier/prettier#7081]
How can I make Prettier format the code according to the rules specified in ESlint?

I want to use Prettier and ESlint. without using .prettierrc.js -> singleQuote: true,. 

In order for Prettier to format the file according to the ESlint rules, before saving, Prettier takes the rules specified in eslintrc.js and formats the code

How can i do this?

I know in VSCode there is a param named `eslintIntegration `
https://github.com/prettier/prettier-vscode#vscode-specific-settings

Any similar solution or workaround for web storm?

**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: Webstorm 2019.2.4
- Runtime: Node v8.16.0
- Operating System: ,macOS

I'd like to integrate prettier with the eslint configuration

My configuration is

`
{
  "env": {
    "browser": true,
    "node": false
  },
  "extends": [
    "react-app",
    "airbnb",
    "plugin:jsx-a11y/recommended",
    "prettier",
    "prettier/react"
  ],
  "plugins": ["jsx-a11y", "prettier", "react", "react-hooks"],
  "settings": {
    "import/resolver": {
      "node": {
        "paths": ["src"]
      }
    }
  },
  "rules": {
    "no-shadow": 0,
    "no-console": 0,
    "no-param-reassign": 0,
    "no-plusplus": 0,
    "react-hooks/exhaustive-deps": "off",
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
    "prettier/prettier": [
      "error",
      {
        "bracketSpacing": true,
        "jsxBracketSameLine": false,
        "printWidth": 100,
        "semi": true,
        "singleQuote": true,
        "tabWidth": 4,
        "trailingComma": "es5",
        "useTabs": true,
        "overrides": [
          {
            "files": "{.prettierrc,.watchmanconfig,.ember-cli}",
            "options": { "parser": "json" }
          }
        ]
      }
    ]
  }
}
`
Thank you

**Comment by evilebottnawi** [comment]
Please use stackoverflow for questions, or open issue in webstrom bug tracker

**Comment by lydell** [comment]
prettier-vscode is a bit confusing. "eslintIntegration" basically means that it’ll use [prettier-eslint](https://github.com/prettier/prettier-eslint) instead of `prettier`.

So you should be able to install `prettier-eslint` and follow the [Webstorm docs](https://prettier.io/docs/en/webstorm.html) but enter `prettier-eslint` instead of `prettier`.

Hope it works out for you! I don’t think we’ll be able to help you more than that in this repo.
