### ISSUE TITLE
How to configure format like this

### ISSUE THREAD

**Issue by EthianWong** [prettier/prettier#7085]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmp5kAWATnAGYC8xINMMWAzkgPR8wOAJYA6AG4BXOACtuoiHQDmbMjDzK4MViAD6AI3xQA1qoY4dUCBCwI4dNoSlwAtEOFkAJhDCSMCdRhhaFQ+PEJRUlDMXAI4QhAAGhAbIOhuZFANOggAdwAFDQQMlDxxCGFPJJB9OjwwYy0AZSx64SglZBg6aWSODBwAdRpheG5WsDgm4tHhcVGAT2Rwbgzk9u57GHy6pQw8ZEY8HE3kuQAPACE6hua8fwAZdrhD49OQC6b2pRw4AEVJBB4K8TnBkq06Js6MtnNUsHR2jBBpUYDRkAA2AAM4Jym0GdSwy3hcCh4heyQAjoD4DsbCUQHhuC4oHA4J42dUGFThAwdng9gckEdQclNhhhF0emCQNxvr8AUCXkK3tL1PpkZ5UcgAEzJbp4YQiDoAYQgGH2yysLOqkk2ABU8PoSsL3s4AJJQdmwJpgBFYGAAQU9TRgC1+IM2AF9I0A)
```sh
--parser vue --print-width 60
```

**Input:**
```vue
<template>
  <a href="https://cli.vuejs.org" target="_blank" rel="noopener">vue-cli documentation</a>.
</template>
```

**Output:**
```jsx
<template>
  <a
    href="https://cli.vuejs.org"
    target="_blank"
    rel="noopener"
    >vue-cli documentation</a
  >.
</template>
```

**Expected behavior:**
```jsx
<template>
  <a
    href="https://cli.vuejs.org"
    target="_blank"
    rel="noopener">vue-cli documentation</a>.
</template>
```

**Comment by lydell** [comment]
Hi!

There is no way to get that output, as far as I know. This is how Prettier formats HTML.

**Comment by PandaTsui** [comment]
I understand, will all vue files be formatted as html?so, the prettier is not very suitable for formatting vue files.

**Comment by lydell** [comment]
Vue _is_ HTML, isn’t it?

**Comment by armano2** [comment]
vue is not html its html like if html parser is used. Vue as template code allows to use html like syntax or pug
