### ISSUE TITLE
Optional chaining does not work with typescript parser

### ISSUE THREAD

**Issue by just-boris** [prettier/prettier#7088]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgGwK5wHQQAOMAltFgPx6YIDmMAFgNwA6UIANCEadAM7JQ6AE7CIAdwAKIhAJTpUEEgBNOIAEbD0YANZwYAZULaSUWshjDcXBjAC2mAOoMS8PsbBwDs1yVSuAT2RwPgEuUz44YRhJLVo7dGQAMyxIrgArPgAPACEtXX0DdDs4ABlTOGTUuAzsg1NaGgBFbAh4Ksw0kGNhSOFgmADCOD4wYRJiNUJx2EcVRmQADgAGLmmISMctQmDpkajUSq4AR1b4WKI5EHQ+AFooODhlJ7VhOFOSN9j0eMSkFM6NRAkTsJAsViBfAazTOlX+1S4MHQ6jmygWSAATIitCRMA0AMIQOwJYJQaBHEDYSIAFWRcgBXVQuAAklBnrADGMJjAAIJsgyDGgdSIAXxFQA)
```sh
# Options (if any):
--parser=typescript
```

**Input:**
```jsx
value.optional?.length;
```

**Output:**
```jsx
SyntaxError: Expression expected. (1:16)
> 1 | value.optional?.length;
    |                ^
  2 | 
```

**Expected behavior:**
The code is parsed without error.

When I switch to `--parser=babel`, it works, the problem is only with `typescript` parser

**Comment by evilebottnawi** [comment]
Can't reproduce, double check prettier version

**Comment by just-boris** [comment]
It worked on the playground

<img width="1280" alt="Screen Shot 2019-12-03 at 1 32 19 PM" src="https://user-images.githubusercontent.com/812240/70051450-5cf30500-15d1-11ea-98a3-6a1722c1c760.png">

But can't reproduce this anymore, caching issues, apparently.

I have the same problem locally, I am preparing the minimal repro example

**Comment by evilebottnawi** [comment]
@just-boris try `CTRL + F5`, playground works fine

**Comment by just-boris** [comment]
Resolved the local problem too. Apparently, there was an issue with package-lock.

Sorry for the disturbance!

**Comment by OzzieOrca** [comment]
I'm having this same issue too.

Copied first code example from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

[Playground with `typescript` parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDAJgNwRgFcAnOUzAXk2AB0pNMpsBbOJTAcgEEAbAJZg4XADQMmYbDE71GTZmw7cAIgJYALLhMwBfBroDcDBpCgZMuCAHMAckuo4CRMhQB0V6wH43LdsagzNAg+ODc+GwAKT3t2AEoAgHpEzDgADwAHODB4XEwIYhgMws5iKFw4ADN1OFwTQPQQsIjrSLxCWFdSN2D2W2gAUTSBDCIAWTgYDQhcH0i4uIZk1Mzs3PzC4plMMorqqFqQURAIDJgBdGRQbFJSCAB3AAUbhDRkEGx8CAFcI5AAI1I2DAAGtJgBlDLA9TWZAwUjEODHDQwVh8ADqGgE8DQUOE4Ne2IE+GxAE93mA0G9juo0BQYI8gdZWNhkJVsHw6ccAFZoNIAISBoIhSgAMjU2RyuSBeWlwTDQgBFYgQeCSzlIkBQ0h00jvGCkrJoMCkARnP4ZU2wdE-KbIAAcAAZjpaIHT0UCMu9LXBdYQ-gBHFXwRmnN4obBoAC0B1qh2O5CDAnIjOwzNZSHZGuOdNYAjhCM1aAVcGVqrg6ulMGw-xtuDtSAATMd4dgBIIoNYAMIQVgs95QaAV47EOkAFRr4az0vwiIAkuUiOCTWaYDxyuCDaFK3BdLogA) throws 
```ts
SyntaxError: Expression expected. (8:32)
   6 | };
   7 | 
>  8 | const dogName = adventurer.dog?.name;
     |                                ^
   9 | console.log(dogName);
  10 | // expected output: undefined
  11 | 
```
[Playground with `babel` parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDAJgNwRgFcAnOUzAXk2AB0pNMpsBbOJTAcgEEAbAJZg4XADQMmYbDE71GTZmw7cAIgJYALLhMwBfBroDcDBpCgZMuCAHMAckuo4CRMhQB0V6wH43LdsagzNAg+ODc+GwAKT3t2AEoAgHpEzDgADwAHODB4XEwIYhgMws5iKFw4ADN1OFwTQPQQsIjrSLxCWFdSN2D2W2gAUTSBDCIAWTgYDQhcH0i4uIZk1Mzs3PzC4plMMorqqFqQURAIDJgBdGRQbFJSCAB3AAUbhDRkEGx8CAFcI5AAI1I2DAAGtJgBlDLA9TWZAwUjEODHDQwVh8ADqGgE8DQUOE4Ne2IE+GxAE93mA0G9juo0BQYI8gdZWNhkJVsHw6ccAFZoNIAISBoIhSgAMjU2RyuSBeWlwTDQgBFYgQeCSzlIkBQ0h00jvf7Yf5wPh-DKkdQwdE-KbIAAcAAZjmaIHT0UCMu8zXBdYQ-gBHFXwRmnN4obBoAC0B1qh2O5ADAnIjOwzNZSHZGuOdNYAjhCM1aAVcGVqrg6ulMENVtwNqQACZjvDsAJBFBrABhCCsFnvKDQMvHYh0gAqhtDGel+ERAElykRwWBzWceOVwTBSaFy3BdLogA) works.

I'm having this issue with prettier-vscode 3.20.0 which runs prettier 1.19.1.

Guess I can make a new issue if that's better or I don't get a response.

**Comment by OzzieOrca** [comment]
And all my problems seem to have gone away both on playground and after restarting VS Code... Just like the OP. Idk what's going on...

**Comment by Spaxe** [comment]
Can confirm that updating prettier to the latest works

**Comment by cothman** [comment]
Still having the issue, I'm using prettier-vscode-4.4.0

**Comment by LordParsley** [comment]
In my case, if you are using another IDE like SublimeText, check the JsPrettier `prettier_cli_path` and make sure it is correct. If you're pointing to a global version which is out of date, you might run into this too.
