### ISSUE TITLE
Stylelint integration doesn't work, only Prettier rules applied

### ISSUE THREAD

**Issue by SharakPL** [prettier/prettier#7090]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: Prettier extension v. 3.11.0 in VSCode 1.40.2
- Runtime: 
- Operating System: Windows 10 Pro

**Steps to reproduce:**
I have been using [stylelint-config-twbs-bootstrap](https://github.com/twbs/stylelint-config-twbs-bootstrap) which depends on _stylelint-order_ and added _stylelint-prettier_ to allow fixing on save. Everything worked just fine, most errors and (s)css properties' order was being fixed, but it required `"prettier.stylelintIntegration": true` in vscode settings, even though it was already depreciated:

![obraz](https://user-images.githubusercontent.com/5007456/70103208-c2c7a700-163a-11ea-9e42-6d5984ad8b1d.png)

**Wouldn't autofix stylelint rules (properties order included) withouth it !!!**

In `.stylelintrc.json` I used:
````
"extends": ["stylelint-config-twbs-bootstrap/scss"],
"plugins": [
    "stylelint-prettier",
],
````
But last update of prettier extension broke it. Nothing is fixed anymore and vscode force me to delete depreciated setting 😞 

![obraz](https://user-images.githubusercontent.com/5007456/70103605-e0494080-163b-11ea-9777-d96dc33651d2.png)

Doing so allows to autofix on save again, but only prettier rules are being considered. Linting by stylelint rules still works (some collide with prettier rules), but no autofix on save.

Tried settings recommended [in Prettier docs](https://prettier.io/docs/en/integrating-with-linters.html#use-stylelint-to-run-prettier) but it still has impact only on linting. Autofix on save applies only Prettier rules, so required order is completely ignored.

**Expected behavior:**

Stylelint configuration should be considered

**Actual behavior:**

**Comment by lydell** [comment]
Hi! I think you should post this in the https://github.com/prettier/prettier-vscode repo. Unfortunately we can’t help you here.

**Comment by SharakPL** [comment]
Right, sorry.
