### ISSUE TITLE
return with ??

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#7093]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAnOMCuGqoBmEOUAJgDICGARnADaoD8TmcYeAzgJYBucAfULdyA+rQYCcAByEYIAWwEjpOGAAoAOgXSoVagKL0ANNt16oqmEdM70ARlvnpETjxr041OvQAqVAHNOJ10XN24PLwl6AGFxNzhOM1QASgBubRBjEAhpGG5oTmRQKgx5AHcABVKEIpQqXghuMiyQGgwqMABrbABlaU6RAOQYDBw4bIALGAV6AHVJ7nhOAbA4XtqlviWAT2RwN1aRTjgMGEqOgIUqZEIqehPsgCtOAA8AIQ7uvqoFLxE4Ld7o8QC9Xr0hp4AIo4CDwIEPCYgAYYE4YfY0aKtaQYEQwObNGCTZAADgADNkca44HMOtJ9jjEqd+K0AI6w+AXXJ1EBUTgAWigcDgZBFrSw7O4WAugWuCJBJwU3BGYyRPCgAWhHMBSDuiOyMFoBLIROQACYDR1uPQhjFFHKUFBoIDsjgTv4aHU9SDeOMAJLkBAwXpgXF5ACC5F6MB2nnlcAAvgmgA)
```sh
--parser babel
```

**Input:**
```jsx
  return foundLabel ?? recursive_find_label_up_from_input(
    inputEl,
    inputEl,
    1,
    possibleLabelTags,
    possibleLabelClasses
  );

```

**Output:**
```jsx
return (
  foundLabel ??
  recursive_find_label_up_from_input(
    inputEl,
    inputEl,
    1,
    possibleLabelTags,
    possibleLabelClasses
  )
);

```

**Expected behavior:**
Don't know if it's buy design, but IMO looks ugly.

**Comment by evilebottnawi** [comment]
Output is better and readable, sorry we don't want to change currently output
