### ISSUE TITLE
Comments and strings are not wrapped correctly

### ISSUE THREAD

**Issue by helmbold** [prettier/prettier#7097]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVBLGAKAOiAJzgEMAbUgT1VOgHNV4BnGVAEzkbAIwAcYNoqAO5YAFqmLUILCADM2cGMQylGEqK1QBbYlCpCIBVo3wAaVLOIBrOAEFGFKGGzYAlKgC8APlTBcUdHRIKEYIUjgAOhpaPBB8V390AF9XVxBTEAg+ARDkUGICAgghAAUChEZkEGIANwgMVnSQACMCYjAbGABlHnaMKFpkGAIAVzgM0RgtUgB1USwOXrA4LoqsDBqsCiqwRkqM-sY4AhgSttodZEtVcZAAK0YADwAhNo7FLuItOAAZfrgrmQjhkHo8uv1aOEAIojaQApDXYEgXoEI4EKrNYjNOCkJo8biwGYNGCiZAADgADBl8RAjjM2jwqviOMcagCMgBHWHwM5ZSooYiMAC0UDgcHYjQyRC5GCIZ2IF2IgJuGSOWgwQ1Gt0YEOh3PhiNuSmaRNYJOQACYMsNlKQIQBhCBaS4oKDQdkgEZHAAqWP5hoyNTGAEkNAhulxeDBbBoujAKOFlUckkkgA)

```sh
--parser babel
```

**Input:**
```typescript
  it("really long test description with a lot of details and many words", fakeAsync(() => {
    console.log("")
  }))
```

**Output:**
```typesctipt
it("really long test description with a lot of details and many words", fakeAsync(() => {
  console.log("");
}));
```

Same applies for some [comments](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVB6AVFgOldVLVAJTgEMAbSgT1UugHNUATOAZzACcBLABxg9oqAO48YAC1Tl6EGKggAzVnBjkeldtKgtUAW3JQaAGn2G6IiFxZaYEVFwotT7e5PLzJcB07hdUYIb0FFwEMgwwAHT4hFgYMQGGACIUYIIAbh5wABSQenzQCDBIqADKEHpwAMIVBVBFAJQlAPIARux+ma2UcAA8rRAQPYYAfKjACQC+IMYgEAJCUOzIoORcXBAiAAprCMso5OkQPCwzIK1c5GAA1qqlfFc8UIzIMFwArnCzEjB6lADqEnEHAeYDgpT24h46XENGQ4HYy1mTw6XBgW0ujAMyEUVA6swAVuwAB4AIUuNzu5EqABknnAcXiviAicTSk9GD0AIrvOQMpC4zTMh5cVHw1rkVpwShnPi8WD-E6SZAADgADLM5RAOv9Lnx4XKOJ0GbMAI68+AY+b7EDkdgAWnqcDYp1mjnNPEcGPIWPIjKFsw6eh4rw+zPYHO5Fv5gvxIDUrUVLGVSAATLM3upKByanpsSgoIUzu8OgAVSX7WPM9KfACSOiKpW4-BgAEEdKUYDQev6OpNJkA):

```typescript
  /**
   * Really long description with a lot of details and many, many words to read, so that the reader can learn a lot.
   */
  canDeactivate(component: SomeComponent): Observable<boolean> {
  }
```

**Expected behavior:**

Since the line is too long, it should be wrapped.

```typesctipt
it(
  "really long test description with a lot of details and many words", 
  fakeAsync(() => {
    console.log("");
  }
));
```

```typescript
  /**
   * Really long description with a lot of details and many, many words to 
   * read, so that the reader can learn a lot.
   */
  canDeactivate(component: SomeComponent): Observable<boolean> {
  }
```

**Comment by evilebottnawi** [comment]
Please fix issue template

**Comment by thorn0** [comment]
1. It's intentional. Prettier doesn't wrap `it`, `describe` and co. See https://prettier.io/docs/en/rationale.html#testing-functions
2. Prettier doesn't wrap comments. See #6926.
3. Please make sure only to include one issue per report in the future.
