### ISSUE TITLE
U+2005 etc. is (sometimes) stripped from html

### ISSUE THREAD

**Issue by pkra** [prettier/prettier#7103]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPlQZ3QQykwA1UB6PQzAAkFACWiAJ3utwKIE1zKjysAdKBhJ0GzWtS5kBUEABoQEdDACW0HMlD5GjCAHcACtoQaU+AG4QVAE3kgARo3xgA1nBgBlAmBVQA5sgwjACucAoAFjAAtgA2AOrhKvCUYHAeJkkq5kkAnsjgOBoKvjhwjDAGTn5R+MgAZvgxpQoAVjgAHgBCTq7uHvhRcAAyvnD1jc0gbe0evn4xcACKwRDw401hIASMpYz5kbF26Iy+MHE2MOHIABwADArHEKVxTuj5x3C75mMKAI4r8EqSlMIHwOAAtFA4HBrDC7Iw4P8VAjKvhqrUkA0NgpSlEVIEQpscHMFstVmNMRNNjB8PZztZLsgAEwKIL4FQxOYAYQgURq+Sg0B+IGCpQAKrTTFjJuZQgBJKCw2AeMAnZQAQUVHhgOQW61KAF8DUA)
```sh
# Options (if any):
--single-quote
```

**Input:**
```html
<p><span>X</span>   or   <span>Y</span></p>
<p>X   or   Y</p>
```

**Output:**
```html
<p><span>X</span> or <span>Y</span></p>
<p>X   or   Y</p>
```

**Expected behavior:**

U+2005 should not be turned into a regular space.

From a quick test, this also happens for similar characters in the [Unicode General Punctuation block](https://en.wikipedia.org/wiki/General_Punctuation).

**Comment by fisker** [comment]
I can't see any bug here, all formated as expected.

**Comment by fisker** [comment]
@pkra Can you point me which character is wrong formatted?

**Comment by pkra** [comment]
Thanks for looking into this!

> Can you point me which character is wrong formatted?

The input has 

> <p><span>X</span>   or   <span>Y</span></p>
 
Before and after the "or" there's a string: \u0020\u2005\u0020

The output has 

> <p><span>X</span> or <span>Y</span></p>

which only has \u0020 around the "or".

This renders visually quite differently.

Now the second line in the example has 

> <p>X   or   Y</p>

again with  \u0020\u2005\u0020 around "or" -- but this time the output contains \u0020\u2005\u0020 as well.

To me, the second behavior (preserving such Unicode spacing and punctuation) seems correct. 
In any case, the two different behaviors seem inconsistent.

**Comment by fisker** [comment]
```console
$ node -p "require('prettier').format('X\u0020\u2005\u0020Y', {parser:'html'}).split('').map(c => c.charCodeAt(0).toString(16))"
[ '58', '20', '2005', '20', '59', 'a' ]
```

There is no difference.

**Comment by pkra** [comment]
@fisker right -- it seems to depend on the HTML markup. Did you see the [link to the playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPlQZ3QQykwA1UB6PQzAAkFACWiAJ3utwKIE1zKjysAdKBhJ0GzWtS5kBUEABoQEdDACW0HMlD5GjCAHcACtoQaU+AG4QVAE3kgARo3xgA1nBgBlAmBVQA5sgwjACucAoAFjAAtgA2AOrhKvCUYHAeJkkq5kkAnsjgOBoKvjhwjDAGTn5R+MgAZvgxpQoAVjgAHgBCTq7uHvhRcAAyvnD1jc0gbe0evn4xcACKwRDw401hIASMpYz5kbF26Iy+MHE2MOHIABwADArHEKVxTuj5x3C75mMKAI4r8EqSlMIHwOAAtFA4HBrDC7Iw4P8VAjKvhqrUkA0NgpSlEVIEQpscHMFstVmNMRNNjB8PZztZLsgAEwKIL4FQxOYAYQgURq+Sg0B+IGCpQAKrTTFjJuZQgBJKCw2AeMAnZQAQUVHhgOQW61KAF8DUA)?

**Comment by pkra** [comment]
For completeness:

```
$ node -p "require('prettier').format('<p><span>X</span>   or   <span>Y</span></p>', {parser:'html'}).split('').map(c => c.charCodeAt(0).toString(16))"
[
  '3c', '70', '3e', '3c', '73', '70',
  '61', '6e', '3e', '58', '3c', '2f',
  '73', '70', '61', '6e', '3e', '20',
  '6f', '72', '20', '3c', '73', '70',
  '61', '6e', '3e', '59', '3c', '2f',
  '73', '70', '61', '6e', '3e', '3c',
  '2f', '70', '3e', 'a'
]
$ node -p "require('prettier').format('<p>X   or   Y</p>', {parser:'html'}).split('').map(c => c.charCodeAt(0).toString(16))"
[
  '3c',   '70',   '3e',
  '58',   '20',   '2005',
  '2005', '6f',   '72',
  '2005', '2005', '20',
  '59',   '3c',   '2f',
  '70',   '3e',   'a'
]
```

**Comment by pkra** [comment]
Note how the second one preserves u+2005.

**Comment by thorn0** [comment]
Note that u+2005 is matched by `\s` and is trimmed by `.trim()` in JS whereas HTML uses the notion of "[ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace)".

**Comment by fisker** [comment]
Found the problem, thank you.

```console
$ node -p "require('prettier').format('<i>X</i>\u0020\u2005\u0020<i>X</i>', {parser:'html'}) === '<i>X</i>\u0020\u2005\u0020<i>X</i>\n'"
false
```

**Comment by pkra** [comment]
Thanks again, @fisker!

**Comment by fisker** [comment]
Thanks for helping me out too. ❤️

**Comment by thorn0** [comment]
@pkra What are your thought on this proposal: https://github.com/prettier/prettier/issues/8146?

**Comment by pkra** [comment]
@thorn0 thanks for the pointer. I don't have a strong opinion on #8146 - I don't wouldn't do such a replacement myself but it wouldn't bother me either. And I can understand if an opionated formatter like prettier would want to do this kind of thing.
