### ISSUE TITLE
Typo in docs 

### ISSUE THREAD

**Issue by nelsonomuto** [prettier/prettier#7105]
Typo https://github.com/prettier/prettier/blob/master/docs/precommit.md#option-2-pretty-quick 

line 38 instead of pre-commit it should read precommit 

**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: 
- Runtime: 
- Operating System: 

**Steps to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by evilebottnawi** [comment]
No, it is not bug, please read https://github.com/typicode/husky#install
