### ISSUE TITLE
Wrong formatting of minus in variable name

### ISSUE THREAD

**Issue by garyee** [prettier/prettier#7115]
Hi,

I'am using Prettier in Vs-Code with React and Styled Components.
I now have the problem, that I have to access a html data attribute (that I've set) and the variable name gets formatted so that it does not work anmore.
As DOM data attribues must be name "data-something" I have to have a minus in between but prettier allwas adds spaces around the minus.

`export const Styled = {
    Panel: styled(Panel)`
        .panel-body {
            ${props => (props.data-withBodyWrapper == true ? 'padding: 0' : 'padding: 15px')};
		}    
`,
};`
is formatted to  `props.data - withBodyWrapper` which does not work.
I looked for what option to change but found none.

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue will be closed

**Comment by garyee** [comment]
Sorry my fault. Dashes are not allowed in property names I honestly did not know that.
