### ISSUE TITLE
JSON range formatting throws syntax error

### ISSUE THREAD

**Issue by trevorah** [prettier/prettier#7116]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwAEAdEAjLS0BMaAviADQgQAOMAltAM7KgCGATmxAO4AK7CTFCwBuEWgBNyONizABrODADKVWbSgBzZDDYBXOBQAWMALYAbAOqHa8BqrBwlAm7WE2AnsnAMmFdQzg2GB4ZDRMWZAAzFjMAigArBgAPACEZeUUlFhM4ABl1OCiYuJBEpKV1DTM4AEVdCHgi2IMQVTYAti9E6CkqNnUYCwkYQ2QADgAGCj6IAIsZKi8+uA7hQooAR3r4EOpBEBYGAFooODhxc6k2OC3aa5CWMIikaOaKAJNabT0WhkrquoNQovYotGAsbBDcQjZAECg6Fi0MyVADCEBM4S8UGg6xAugCABUIYJXiVhPoAJJQC6wJRgfo0ACC1KUMHc1SaJRkmkc4KCyAArBRuRo4ABRanIACcxGIQA)
```sh
--parser json
--range-end 9
--range-start 5
```

**Input:**
```jsonc
{ "b": 2 }
```

**Output:**
```jsonc
SyntaxError: Unexpected token (1:4)
> 1 | "b": 2
    |    ^
```

**Expected behavior:**
```jsonc
{ "b": 2 }
```

This is the smallest example I could make that causes the parser to fail. It seems like if the range starts with a `:` but doesn't end with a `,` or `}` after the object value, then the parser throws a syntax error.

**Comment by athyuttamre** [comment]
Also ran into the same issue. Not a blocker since I can format the whole file for my use case, but was hoping to get a performance boost by only formatting part of the file that changed.
