### ISSUE TITLE
Remove support for `semi: false`

### ISSUE THREAD

**Issue by ExE-Boss** [prettier/prettier#7117]
@TC39&nbsp;agrees that&nbsp;**Automatic&nbsp;Semicolon&nbsp;Insertion** is&nbsp;a&nbsp;hazard and&nbsp;legacy&nbsp;mistake in&nbsp;<https://github.com/tc39/ecma262/pull/1062>.

I&nbsp;can’t&nbsp;think of&nbsp;a&nbsp;good&nbsp;justification to&nbsp;keep it&nbsp;either, so&nbsp;I&nbsp;feel&nbsp;like it&nbsp;should be&nbsp;considered for&nbsp;removal in&nbsp;a&nbsp;major&nbsp;**Prettier**&nbsp;release.

**Comment by evilebottnawi** [comment]
I don't think we should do this because it is not standardized right now

**Comment by ericbf** [comment]
This would be super lame.

**Comment by evilebottnawi** [comment]
Yes, we don't want to remove this option right now, maybe we revisit it late

**Comment by ExE-Boss** [comment]
<https://github.com/tc39/ecma262/pull/1062> has&nbsp;now&nbsp;been&nbsp;merged in&nbsp;<https://github.com/tc39/ecma262/commit/f5436bfed9b1bd01ec35a074d8369d4a330e85ec>.
