### ISSUE TITLE
Markdown: Link key converted to lower-case

### ISSUE THREAD

**Issue by schallm** [prettier/prettier#7118]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAZznA2gGQEsoBrdGCdAMQggF1cBbAQ03gCdUjSAVCG+gB0owpqw5diJPgLpJ0ACxgwADkgD06gGa0AdJEYgANCAgqYhaJmShm7dhADuABTsJrKZgDcIhACbGIABG7MxgJHAwAMoqYcQA5sgw7ACucCZKjAA2AOoKhPCYsWBwUe4FhF4FAJ7I4JjWJsTY7DDOofEsyFrMWdgmAFaYAB4AQqHhkVHMjHDccN29-SBDw1EJWXAAiikQ8It96SCx7C11LOwkfk5QgSrsxDA5-jAKyAAcAAwm9xDYOaEVHV7nAWl4FiYAI67eDtMweECsVBQHB+OABEzsODQwhY9rMTrMA7LbCMQhJVJHTAbbYwhZIHqHEwwZhBZ5+V7IABMzNChCyCQAwhBGF0UFBoBCQClsDxWR5GcsvGkAJJQNGwKJgB7mACC6qiMGqm2JcAAvmagA)
```sh
--parser markdown
```

**Input:**
```markdown
- see[Link to Foo][master-LinkToFoo]

[master-LinkToFoo]: http://foo.com
```

**Output:**
```markdown
- see[Link to Foo][master-linktofoo]

[master-linktofoo]: http://foo.com

```

**Expected behavior:**
```markdown
- see[Link to Foo][master-LinkToFoo]

[master-LinkToFoo]: http://foo.com

```

Making the key lower case reduces the readability of Camel or Pascal cased keys.  This seems to have changed recently?  Was the change intentional?  Can you share the justification?

**Comment by lydell** [comment]
I think Prettier has always lowercased them. Why? Because we lowercase case insensitive things in other languages, I guess. Such as hex numbers in JS.

In your case, you could use `master-link-to-foo` or `master-foo` or just `foo` for better readability.

**Comment by schallm** [comment]
Thanks for the quick response!  Your suggestions are valid in many cases, but many times we have class names or database table names or stored procedure names (Camel or Pascal cased) in our link names to source control and adding dashes "changes" the name.

We were surprised by the current behavior.  Feel free to close if this is intentional.

**Comment by evilebottnawi** [comment]
You can use `prettier-ignore` in that case

**Comment by schallm** [comment]
Thanks for the suggestion, but we want to use prettier as-is.  I'll close as this seems to be intentional.

**Comment by DerekNonGeneric** [comment]
@vjeux, thanks for getting this unlocked! We have a lint rule that forbids inline links in the form of:

```md
Bla bla [PascalCase](./PascalCase.md) bla.
```

&hellip; and requires them to be at the end of the document like so:

```md
Bla bla [PascalCase][] bla.

[PascalCase]: ./PascalCase.md
```

This is problematic when documenting APIs because oftentimes we want the capitalization of the link text to remain intact as it provides meaningful clues about whether or not this is a class or a function/variable. However, Prettier doesn't care about this and makes these all lowercase.

**Comment by jacobbuck** [comment]
I've just come across this issue with `CHANGELOG.md` files following the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format:

**Input:**

```md
## [Unreleased]
…
[Unreleased]: https://github.com/username/project/compare/v1.0.0...HEAD
```

**Output**

```md
## [Unreleased]
…
[unreleased]: https://github.com/username/project/compare/v1.0.0...HEAD
```

**Expected behaviour:**

No change from input.

**Comment by AndrewKvalheim** [comment]
Just seconding that this cuts against readability and correctness. Often link reference definitions read as a glossary, e.g.:

```markdown
[darktable]: https://www.darktable.org/
[js;dr]: https://indieweb.org/js;dr
[LinuxFest Northwest]: https://www.linuxfestnorthwest.org/
[OpenStreetMap]: https://www.openstreetmap.org/about
[SeaGL]: https://seagl.org/
[uBlock Origin]: https://github.com/gorhill/uBlock
```

and it would be a spelling error to change a label’s capitalization.
