### ISSUE TITLE
Incorrect react multiline comments formatting

### ISSUE THREAD

**Issue by arvigeus** [prettier/prettier#712]
Input:
```js
<div>{/*<div>Some very very very very long line to break line width limit </div>*/}</div>
```

Result:
```js
<div>
  {/*<div>Some very very very very long line to break line width limit </div>*/
  }
</div>
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%7B%2F*%3Cdiv%3ESome%20very%20very%20very%20very%20long%20line%20to%20break%20line%20width%20limit.%20%3C%2Fdiv%3E*%2F%7D%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Repro link:

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%7B%2F*%3Cdiv%3ESome%20very%20very%20very%20very%20long%20line%20to%20break%20line%20width%20limit.%20%3C%2Fdiv%3E*%2F%7D%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
