### ISSUE TITLE
ESLint (Airbnb) + Prettier - Incorrect removal of parentheses around multiline JSX

### ISSUE THREAD

**Issue by jamesopti** [prettier/prettier#7130]
The error I'm encountering only manifests when ESLint (Airbnb) is integrated (done per [the Prettier recommendation](https://prettier.io/docs/en/integrating-with-linters.html#use-eslint-to-run-prettier)). The playground below shows Prettier by itself formatting correctly (ESLint by itself also fixes correctly). When integrated, the error below happens.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAggA7EAUAlPsADpT74BOcM6j9ZdDDAPACY4Abl24MwAGwCGAZ2kA5SQFs4AXhppxcAB7qRoydiGSYERiuD5O9Ud35CAfHpsNFATyZxJ48e-HQA5vgCgiGhYeHhTs480sSSUPbSEMr4YAAWOOJ8PAD0sfGO1tE5wYXOVAC+ZTYAsu6SpE65pSIUANx0FXQgADQgEMS40NLIoJKMjBAA7gAK4wgjKJKCEDh8vSAARowGANYsAMpxYDhQ-sgwjOhwfWkwiuIA6hnw+WBwBws4uILfrsjgWQbU7SOCMGAzHb+RSSZCoLygvoAK2kWgAQjswPsYAclHAADKnOAXK43EAorQHU7+TQARXQEHgcIRZLijFBjABm0kmzg4g2xEYpxgjzWMDSyAAHAAGPqCiCgx47YgAwVwDmCYl9ZgAR3QOGYkMk0NhSHh4kRIFBihwJOufWk1LpDKZZpZfRgPNFfHFyAATB6dplqQBhZIwgFQaBakDoUEAFR5i3NoIqFSAA)
```sh
--jsx-bracket-same-line
--parser babel
```

➡️ **Input:**
```jsx
function App() {
  return (
    <div
      className="flex"
      activator={ (
        <div>
          my really long divvvvvvvvvvvvvvvvvvvv
          <span>some child</span>
        </div>
      ) }>
      My app
    </div>
  );
}

```

❌ **Output (_with ESLint integration_):** Opening paren remains, causing compile error
```jsx
function App() {
  return (
    <div
      className="flex"
      activator={(
        <div>
          my really long divvvvvvvvvvvvvvvvvvvv
          <span>some child</span>
        </div>
      }
    >
      My app
    </div>
  );
}

```

✅ **Output (_without ESLint integration_):**
```jsx
function App() {
  return (
    <div
      className="flex"
      activator={
        <div>
          my really long divvvvvvvvvvvvvvvvvvvv
          <span>some child</span>
        </div>
      }>
      My app
    </div>
  );
}

```

**Expected behavior:**

With the ESLint (Airbnb) + Prettier integration, the parentheses should be removed correctly, as seen in the 2nd ✅ output example.

Here is a GIF to show this as well:

![eslint-error](https://user-images.githubusercontent.com/3718812/70644315-9d690900-1bf7-11ea-9059-a1d8e18995be.gif)

<details>
  <summary>ESLint Config</summary>

```js
module.exports = {
  env: {
    browser: true,
    es6: true,
  },
  extends: [
    'plugin:react/recommended',
    'airbnb',
    'plugin:prettier/recommended'
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly'

  },
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: [
    'react',
    'prettier'
  ],
  rules: {
    'react/jsx-filename-extension': ['warn', { extensions: ['.js'] }], // changed to warn and change to allow .js to contain JSX syntax
    'prettier/prettier': 'error'
  },
};
```  

</details>

**Comment by lydell** [comment]
Hi!

First I’d try to find the smallest possible ESLint config that triggers the bug. Try to find the exact rules that are the culprits and specify them directly instead of using `extends`.

If this only happens in VSCode, try asking for help at [prettier-vscode](https://github.com/prettier/prettier-vscode).

If this happens using `eslint --fix`, try asking for help at [eslint-plugin-prettier](http://github.com/prettier/eslint-plugin-prettier.)

Unfortunately we’re not able to help you more here since Prettier itself is working.

**Comment by jamesopti** [comment]
@lydell Thank you for the tip! I did confirm through trial and error that this single rule causes the conflict:

`'react/jsx-curly-spacing': ['error', 'never', { allowMultiline: true }],`

I've updated this issue to reflect that.

Would you still recommend filing the issue with the `eslint-plugin-prettier` folks?

**Comment by thorn0** [comment]
@jamesopti Rules like that aren't compatible with Prettier. See https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules

**Comment by jamesopti** [comment]
> @jamesopti Rules like that aren't compatible with Prettier. See https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules

I understand that, but then that means that the recommended configuration is not properly disabling this rule:

```
extends: [
    'plugin:react/recommended',
    <a config that has a rule conflicting with prettier, such as Airbnb>, 
    'plugin:prettier/recommended'
  ],
```

**Comment by jamesopti** [comment]
UPDATE: IMO this is not clear in the docs at all, but a second prettier extends was needed:

```js
extends: [
    'airbnb',
    'plugin:fetch/recommended',
    'plugin:prettier/recommended',
    'prettier/react',  // THIS OVERRIDES SPECIFIC REACT RULES THAT CONFLICT WITH PRETTIER
  ],
```

**Comment by brodybits** [comment]
I think someone should raise a PR to clarify this (docs page has an edit button).

**Comment by lydell** [comment]
@jamesopti configs from `extends` can’t override what you put in `rules`. That’s just how ESLint works. The [eslint-config-prettier CLI tool](https://github.com/prettier/eslint-config-prettier#cli-helper-tool) exists to find such mistakes.

**Comment by jamesopti** [comment]
> @jamesopti configs from `extends` can’t override what you put in `rules`. That’s just how ESLint works. The [eslint-config-prettier CLI tool](https://github.com/prettier/eslint-config-prettier#cli-helper-tool) exists to find such mistakes.

Yup! Thanks for helping clarify this and showing me the tool. I agree with @brodybits that the docs should clarify this, as I think many people would expect the `plugin:prettier/recommended` config to have accounted for this.
