### ISSUE TITLE
Provide option to preserve multiple blank lines 

### ISSUE THREAD

**Issue by power-f-GOD** [prettier/prettier#7131]
Currently, there is no option to preserve multiple blank lines. Can you, please, add an option to preserve multiple blank lines (especially after function/major definitions)? They are basically for to section code blocks and (easily) distinguish them from regular statements.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT74lwz4AWpcvgC8+AOTiA3By6z8qGvgY8+YfBFQTiZCABp8Adxr1xAOgDOABxI4YzJvK6Dd+ANRiwMzvnnVe6NScLuTeAL4ckVAcGFi4BDrkAAr+MLhw1Mys8qoCQhCiEtLy8orUyrnqmtr5Bim86dTm1rb2TI4+zvnunt5yPqmBwfnhHCB6IBBW8VAWyKAAhtTUEIZJSwhzKAsAbhA4dOMgAEbUC2AA1rwAylbnOFAA5sgw1OhwE-wwALYkFPx2ODWc5wa6bOw4HZ2ACeyHAFjmEweFgyMBSC0e3wWyFQCxIKImACsLAAPABCZ0uNwW3zgABkHnAcXiCSBiSTrg9HjwAIroCDwZn4j4gO7UFHUOHHBbHUhHKzUB4wCgHGD8ZAADgADBMFRAURQzlY4QqgRkdkyJgBHfnwFJTLYgBYWAC0UDgcDonqO-htOH86Mx2KQuOFExR3xwLzeIosXN5tqZIZZIpgMpVdDVyAATBNXgscLYngBhCDfLFwqDQS0gdAogAqMq2odZO3eAEkoF7YNcwIrpgBBLvXGDQnhClFhMJAA)
```sh
--parser babel
```

**Input:**
```jsx
function HelloWorld() {
  let hello = '';
  
  for (let c of 'Hello, world'.split())
    hello += c;
  
  return hello;
}



function HelloPrettier() {
  let hello = '';
  
  for (let c of 'Hello, Prettier'.split())
    hello += c;
  
  return hello;
}

```

**Output:**
```jsx
function HelloWorld() {
  let hello = "";

  for (let c of "Hello, world".split()) hello += c;

  return hello;
}

function HelloPrettier() {
  let hello = "";

  for (let c of "Hello, Prettier".split()) hello += c;

  return hello;
}

```

**Expected behavior:**
```jsx
function HelloWorld() {
  let hello = "";

  for (let c of "Hello, world".split()) hello += c;

  return hello;
}



function HelloPrettier() {
  let hello = "";

  for (let c of "Hello, Prettier".split()) hello += c;

  return hello;
}

```

**Comment by lydell** [comment]
This has been discussed before: https://github.com/prettier/prettier/issues/554

Personally, I really like the at-most-1-blank-line rule so I never have to think about how many blank lines I should make.

**Comment by lydell** [comment]
Duplicate of #554

**Comment by power-f-GOD** [comment]
You say "Personally", that's to you. Not everyone would like what you like. If you made Prettier for the community (and not for you or your 'personal' use alone), then you should consider some of this suggestions.

You've done a great work with Prettier. Thanks for creating it. But I'd love if you considered this comment: https://github.com/prettier/prettier/issues/554#issuecomment-439482518

Thank you.

**Comment by lydell** [comment]
I added the “Personally …“ sentence to offer a different perspective; not to motivate why things are the way they are.

**Comment by power-f-GOD** [comment]
No prob'm. But from the thread created in #554, you saw that other Developers wanted it (according to preference), so why not just do as requested? Make it default to a line; add an option to turn it off (according to preference).
