### ISSUE TITLE
Conditional Rules?

### ISSUE THREAD

**Issue by BrianD91** [prettier/prettier#7135]
I'm using emotion css in a project, and it requires a pragma to be added at the top of any file that uses it.

Is there any way to configure prettier so that _only_ files that have certain content (in this case, an import statement from that library) will have the pragma inserted at the top?

**Comment by kachkaev** [comment]
This looks like a job for eslint, for instance. Prettier aims to not change the structure of your code to avoid unexpected bugs, doing so is outside the scope.

If a rule you are seeking does not exist in eslint yet, I guess you can try implementing a custom one. Perhaps, emotion community is the best place to discuss this.

**Comment by BrianD91** [comment]
@kachkaev upon further inspection it seems you're right I should be able to resolve this issue with some eslint customizations.
