### ISSUE TITLE
eslint object-curly-newline conflicts prettier multi-line rationale

### ISSUE THREAD

**Issue by DylanJu** [prettier/prettier#7136]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcauAHSnXTAEsBHAGkONQBMAnAQwHdSoBzAWQQFcANakWKNW7bnwCaQ2ljgAbOGHh0AIszacZqAL6oAvKhwQGcAHRgAFkwYwAyjBNwA3CEogIABxiloWZKA2DBAsAAo2CP4oTABuEKR0biAARsxgANZw9p5MZJzIMAy8cO6WMAC28gDqlqTwWDlgcHaRdaQxdQCeyOBY-u7scrahzBzlTMgAZkzycu4AVlgAHgBCaZn2TOVwADLscFMzcyCLS3biigCKvBDwh7MlIDkMQz3JTMkKSZ4M7DBVCRglmQAA4AAzuH4QORVZieHo-OBDGIHdzkG7wEZeKIgJhYAC0UDgcDoJKSpnRpFMIyYYwmSGmD3ccnKpAKRUeWAucGutwODKOjxgHwBdCByAATO5CkxSPJxABhCDlcY9KDQVEgXhyAAqHyijOOMWKAEkoKTYHYwL9vABBc0OTqKe5yHQ6IA)

**Input:**
```jsx
const {
  ciq,
  drawingMenuX,
  drawingMenuY,
  selectedDrawing,
} = store.chartStore;
```

**Output:**
```jsx
const { ciq, drawingMenuX, drawingMenuY, selectedDrawing } = store.chartStore;
```

**Expected behavior:**
```jsx
const {
  ciq,
  drawingMenuX,
  drawingMenuY,
  selectedDrawing,
} = store.chartStore;
```

I wanna keep a multiline format in destructure object like the rationale (https://prettier.io/docs/en/rationale.html#multi-line-objects)

It works well in a normal object but it's not in destructure object

How can I fix this problem?
Do I just have to fix each line?

**package.json**
```json
"@typescript-eslint/eslint-plugin": "^2.11.0",
"@typescript-eslint/parser": "^2.11.0",
"eslint": "^6.7.2",
"eslint-config-airbnb": "^18.0.1",
"eslint-config-prettier": "^6.7.0",
"eslint-plugin-import": "^2.19.1",
"eslint-plugin-jsx-a11y": "^6.2.3",
"eslint-plugin-prettier": "^3.1.1",
"eslint-plugin-react": "^7.17.0",
"eslint-plugin-react-hooks": "^1.7.0",
"prettier": "^1.19.1",
```

**.eslintrc.js**
```js
module.exports = {
  env: {
    browser: true,
    es6: true,
  },
  extends: ['plugin:react/recommended', 'plugin:prettier/recommended', 'airbnb'],
  plugins: ['react', '@typescript-eslint'],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
  },
  rules: {
    'react/jsx-filename-extension': [
      1,
      {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    ],

    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],

    'no-confusing-arrow': [0],
  },

  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      rules: {
        '@typescript-eslint/no-unused-vars': [2, { args: 'none' }],
      },
    },
  ],
};
```

**Comment by lydell** [comment]
Hi!

Yes, object-curly-newline conflicts with Prettier and as such cannot be used with Prettier (which is why eslint-config-prettier turns it off).

If you want to use it anyway, see [prettier-eslint](https://github.com/prettier/prettier-eslint).

See also #2550

**Comment by DylanJu** [comment]
@lydell 
Thank you for your quick response.

Do you mean if I use prettier without prettier-eslint, there is no chance to keep multi-line in destructure object?

**Comment by lydell** [comment]
Yes.
