### ISSUE TITLE
Clarification of bracketSpacing option

### ISSUE THREAD

**Issue by benjaminapetersen** [prettier/prettier#715]
I'm not 100% sure what the bracketSpacing config does.

These explanations:
- `// Controls the printing of spaces inside object literals` from the README.md
- `// Controls the printing of spaces inside arrays and objects` from the atom package settings page

When using, the following code:

```javascript
// source:
let list = [{
    name: "foo",
    value: "bar"
  },{
    name: "bar",
    value: "baz"
  }];
```
The output is always the same, wether `bracketSpacing` is used or not (cli or atom plugin):
```JavaScript
// output:
let list = [
  {
    name: "foo",
    value: "bar"
  },
  {
    name: "bar",
    value: "baz"
  }
];
```
I'm assuming I'm just expecting something its not designed to do.  With `bracketSpacing` disabled, I would have expected it to stay more dense.  Any clarification would be great. Thanks!

**Comment by rhengles** [comment]
That config only makes a difference when the object fits on a single line:

```javascript
const obj1 = { a: 1, b: 2, c: 3 }; // bracketSpacing: true
const obj1 = {a: 1, b: 2, c: 3}; // bracketSpacing: false
```

**Comment by benjaminapetersen** [comment]
Ahh... ok great.  Perhaps is just a README/doc update then.  I'd be happy to PR the README change if it would be helpful.

**Comment by vjeux** [comment]
@benjaminapetersen would be awesome to give examples of what each options look like in the readme!

**Comment by benjaminapetersen** [comment]
Cool.  So I'm curious, there are very few options (implying opinion is good), why even have `bracketSpacing` as an option at all?  Seems like this one & `trailingComma` (suppress) are just worth enforcing.  However, `printWidth`, `tabWidth`, and `singleQuote` seem like basic essential settings.

**Comment by vjeux** [comment]
Making trailing commas the default seems like a good idea! @jlongster we could use that option for the es7 trailing commas. I don't think that trailing commas are very controversial

**Comment by lydell** [comment]
I'm also curious about why the `bracketSpacing` options exists at all. `printWidth`, `tabWidth` and `singleQuote` are things I could easily see people starting flame wars over, but `bracketSpacing`?

**Comment by jlongster** [comment]
People are pretty opinionated about trailing commas, and I think it's worth having it as an option. However, I am open to removing the `bracketSpacing` option. I haven't seen many people talk about it or use it. I think it's mainly there because recast had that option.

**Comment by vjeux** [comment]
The new docs have it clarified
