### ISSUE TITLE
Template literals not honoring printWidth

### ISSUE THREAD

**Issue by dipamchang** [prettier/prettier#7162]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZA8gcQHRwE54R4AUAOlAARXV5wCOArnAM4wDC08AHjADTnVqAAwBiAQwCWAGzgATCjAgUAZnBhgAFhVZ4JUAOYUAbmKlMVRCgGs4ATyQUAJMGYQAtmo179AX14UAdwkYLTguMDgABxgJaAoPZmYxfTgHZwFBalcPEO84KWY4bGy4CAAjACs4MBgAbQAGAF0MwR8hFooASgBuEF4QCGjYqGZkUDECCACABQmEUZQxIwgJWT6QMrwxMBsYAGVI7e9kGDwmfo0YNykAdS94ZkOIvfngiSNg22RwRPW9QrwMGmW30bjEyGUpkK-QqzC4ACEtjs1HsxB5UHo4BCoXAYXC9t4ZABFBgQeDYgq4kCHPAA75lMRlfLrSK6WA3VYhZAADnq-VZEEKNy2kW+rJY+CMWP6jDJcGBgwWIDEzAAtFA4HI5OtaIwJLRgckwRToSBCm4JCczlTmIS4CS5SaqTBGRzZFykAAmfqnSRSbwcNzGlBQaDSkAMQoAFUZC0hlP6RiYAEkoLIEPswLpogBBNN7GC2GROnw+IA)
```sh
--parser babel
```

**Input:**
```jsx
LOG.error(
      requestContext,
      `Failed to fetch string value for key: ${something}, with exception message: ${
        somethingelse.someobject[0]
      }`
    );
```

**Output:**
```jsx
LOG.error(
  requestContext,
  `Failed to fetch string value for key: ${something}, with exception message: ${somethingelse.someobject[0]}`
);

```

**Expected behavior:**

The code line should wrap after 80 characters.
The Input text above is formatted by Prettier 1.14.x
And the Output is from Prettier 1.19.x

Prettier 1.14.x does a better job at honoring printWidth. 
Prettier 1.19.x does NOT honor printWidth in Template literals
Expectation is that it should.

[My printWidth setting is 80 characters]

**Comment by evilebottnawi** [comment]
It is expected for readability, we don't want modify current output, same issue for template literal https://github.com/prettier/prettier/issues/3368
