### ISSUE TITLE
Feature: Multiple prettier configurations

### ISSUE THREAD

**Issue by iamclaytonray** [prettier/prettier#7163]
**Current Behavior:**
Single, shared prettier config forces formatting styles that may conflict with dev's efficiency/flow.

**Desired Behavior:**
Multi-config support, allowing a git remote (and hooks) to fallback to a default prettier config but each developer can define their own local config. For example, some members on my team like 120 printWidth but I like 80. This would be a win-win for everyone, and I imagine the use-case is very high

**Comment by evilebottnawi** [comment]
Out of scope prettier, you can create custom script if you need something complex
