### ISSUE TITLE
Comments can cause inconsistent output

### ISSUE THREAD

**Issue by benjaminapetersen** [prettier/prettier#717]
In a project I work on, there is a common stanza at the top of most files that has been implemented inconsistently.  If there are comments, the prettier output is also inconsistent:

```JavaScript
angular.module('foo').directive('bar', function() {});

angular
  .module('foo').directive('bar', function() {});

angular
  .module('foo')
  .directive('bar', function() {});

angular
  .module('foo')
  // the directive
  .directive('bar', function() {});


angular
  // the mod
  .module('foo')
  // the directive
  .directive('bar', function() {});
```

Output:
```JavaScript
angular.module('foo').directive('bar', function() {});

angular.module('foo').directive('bar', function() {});

angular.module('foo').directive('bar', function() {});

angular.module('foo')// the directive
.directive('bar', function() {});

angular
  // the mod
  .module('foo')
  // the directive
  .directive('bar', function() {});
```

I probably would have expected consistently either of these:
```JavaScript
angular.module('foo').directive('bar', function() {});
// or
angular
  .module('foo')
  .directive('bar', function() {});
```

**Comment by alekhurst** [comment]
I have a project where prettier consistently produces inconsistent output...

code looks like:
```
  ...
  /*eslint-enable */
}
```

and every time I run prettier, the format changes (adds and removes newline)

**Comment by vjeux** [comment]
> I probably would have expected consistently either of these:

Where do you put the comments? for the first version?

**Comment by vjeux** [comment]
@alekhurst Could you try to find a minimal repro case and open a different issue? That would be great thanks!

**Comment by vjeux** [comment]
@alekhurst I just opened https://github.com/jlongster/prettier/issues/723 for your issue.

**Comment by benjaminapetersen** [comment]
@vjeux the first and second versions are just there for reference, the 3rd and 4th illustrate how the comments alter the output.
