### ISSUE TITLE
Prettier not formatting vue sfcs containing JSX script

### ISSUE THREAD

**Issue by tanisha-keshri** [prettier/prettier#7170]
**Prettier 1.19.1**
Prettier is not formatting the file with <script lang="jsx"> but working for <script lang="tsx"> don't know what's going wrong with my configuration. I am not able to reproduce this in Playground but here is a link to my [demo reproducer repo](https://github.com/tanisha-keshri/vue-jsx-lint-demo).
**Input:**
```jsx
<script lang="jsx">
export default {
  data: () => ({
    message: 'hello with jsx'
  }),
  render(h) {



    return <div>{this.message}</div>
  }
}
</script>

```

**Output:**
```jsx
<script lang="jsx">
export default {
  data: () => ({
    message: 'hello with jsx'
  }),
  render(h) {



    return <div>{this.message}</div>
  }
}
</script>

```

**Expected behavior:**
Should remove the extra newline characters.

**Comment by thorn0** [comment]
Reproduced on the Playground:
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wAEANgIZQDmAvADogBW6AHnQHw1RxN4RZEAmcAGakArsSLAOhQv1IxSSQgAoAlISqsVUqDJkBbOOnSkKcJQHIAFnGLEIhAO44YVwoyYXphAL6qANN5YCIJYylbqOhzRunrBMKJYuqj8OABurMCuOOgAdIbGpnA+qAD0qRnePhzVUGWYuASsIP4gEAQ40OjIoKRYWBCOAAp9CN0opGkQOPwtIABGWKRgANZwMADKeMs4lMgwWKJwrVYw+sQA6lYuRttgcBtjLukuAJ7I4MZzu+hwfENLCj6UjIETEX6tDwAISWq3WG1IhgAMrs4KDSODjgxmBtdhRiHAAIqiCDwdGY1rbLC-LAfNJHOZ4XCwC4zVzIAAcAAZKQNfhclngPkyjH80mjWgBHEnwAHtcYgUjoAC0nDgglmrWC0pwwQBpmB5IhIF++hw+0OWPQeIJxNJaKQYONCnmrP47KQACZWgdSDhiHiAMIQfSGlBQaASkCiX4AFVI83GTqx9LgAEkoIJYBtsPgYABBTMbGCvAlG4o+IA)
```sh
--parser vue
```

**Input:**
```vue
<script lang="jsx">
export default {
  data: () => ({
    message: 'hello with jsx'
  }),
  render(h) {



    return <div>{this.message}</div>
  }
}
</script>
```

**Output:**
```vue
TypeError: Cannot read property 'endsWith' of undefined
    at inferScriptParser (https://prettier.io/lib/standalone.js:19735:29)
    at Object.embed$2 [as embed] (https://prettier.io/lib/standalone.js:20964:26)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15170:30)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15288:31)
    at https://prettier.io/lib/standalone.js:15253:18
    at Object.printComments (https://prettier.io/lib/standalone.js:14974:19)
    at printGenerically (https://prettier.io/lib/standalone.js:15252:24)
    at printChild (https://prettier.io/lib/standalone.js:21227:14)
    at https://prettier.io/lib/standalone.js:21171:16
    at FastPath.map (https://prettier.io/lib/standalone.js:15155:23)
```
