### ISSUE TITLE
Format error syntax with language typescript

### ISSUE THREAD

**Issue by playlistduong** [prettier/prettier#7174]
BEFORE RUN FORMAT
`type A = { readonly [key in keyof B] };`
AFTER RUN FORMAT
`type A = { readonly [key in keyof B]:  };`

**Comment by armano2** [comment]
https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L3336

```diff
-              ": ",
+              n.typeAnnotation ? ": " : "",
```
