### ISSUE TITLE
Idea: Format/sort .gitignore .prettierignore etc

### ISSUE THREAD

**Issue by JerryGreen** [prettier/prettier#7179]
## What

I would like to see `prettier` to sort lines of `.gitignore`, `.prettierignore` and other `.*ignore` files. In ascending order, case sensitively. At the same time, - allowing me to separate lines into meaningful chunks by empty lines.

So my mess like this:

```ignore
# Logs
yarn-error.log

# Ignore-files
.gitignore
.prettierignore
.nowignore
.ignore

# Other
.DS_Store
public
static
.nvmrc
.env
.env.default
.env.production
Dockerfile
.idea
.next
.yarnrc
docker-entrypoint.sh
readport.sh
yarn.lock
CODEOWNERS
```

Will become this (everything sorted alphabetically):

```ignore
# Logs
yarn-error.log

# Ignore-files
.gitignore
.ignore
.nowignore
.prettierignore

# Other
.DS_Store
.env
.env.default
.env.production
.idea
.next
.nvmrc
.yarnrc
CODEOWNERS
Dockerfile
docker-entrypoint.sh
public
readport.sh
static
yarn.lock
```

## Why

First of all, - these "ignore"-files are turning into mess pretty easily. I already have to use simple tools to sort them out alphabetically. But it's semi-manually. I would be happy prettier to do it for me.

In addition, the example isn't `.gitignore` but `.prettierignore`, so since I won't longer need to ignore this "ignore"-files, I will cut out a whole chunk so it will become this:

```ignore
# Logs
yarn-error.log

# Other
.DS_Store
.env
.env.default
.env.production
.idea
.next
.nvmrc
.yarnrc
CODEOWNERS
Dockerfile
docker-entrypoint.sh
public
readport.sh
static
yarn.lock
```

**Comment by lydell** [comment]
Hi!

I think this can be covered by #4547. See also #7073.

**Comment by JerryGreen** [comment]
@lydell sorry, maybe the title wasn't explicit enough. This issue is (mainly) about SORTING. Those issues have nothing to do with sorting.

**Comment by lydell** [comment]
I, sorry, I see.

**Comment by thorn0** [comment]
While there is no plans for adding builtin support for more languages to Prettier, the requested enhancement can be implemented as a plugin. Please see https://prettier.io/docs/en/plugins.html
