### ISSUE TITLE
Dependency Buffer() deprecated due to security

### ISSUE THREAD

**Issue by wilsonmar** [prettier/prettier#7212]
**Steps to reproduce:**
In the response to CLI command  running VS Code command:
```
code --install-extension esbenp.prettier-vscode
```
**Expected behavior:**
No error messages.
**Actual behavior:**
This message:
```
Installing extensions...
Installing extension 'esbenp.prettier-vscode' v3.18.0...
(node:30736) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:30736) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'esbenp.prettier-vscode' v3.18.0 was successfully installed.
```
**Environments:**
- Prettier Version: v1.21.1
- Running Prettier via: CLI 
- Runtime: Node.js v6, Chrome v67, etc.
- Operating System: macOS Mojave

**Comment by lydell** [comment]
Hi! Did you mean to post this in the [prettier-vscode](https://github.com/prettier/prettier-vscode) repo?
