### ISSUE TITLE
Question: How to prevent from to enter next line after +

### ISSUE THREAD

**Issue by fakhamatia** [prettier/prettier#7219]
I want this:
![71624698-240e7600-2bf9-11ea-9a5b-688db9d49eaa](https://user-images.githubusercontent.com/20030910/71760889-7097d100-2ed9-11ea-8237-056688bcee65.png)

Not this:
![71624702-2a045700-2bf9-11ea-9131-2db0743932dc](https://user-images.githubusercontent.com/20030910/71760890-72619480-2ed9-11ea-8647-cf49a52d37dc.png)

**Comment by aboyton** [comment]
Any reason to not putting the variables in the template literal with `${foo}`?

**Comment by fakhamatia** [comment]
> Any reason to not putting the variables in the template literal with `${foo}`?

Sorry, I don't get it, Can you explain by example?

**Comment by thorn0** [comment]
Please see https://prettier.io/docs/en/ignore.html#javascript

**Comment by fakhamatia** [comment]
> Please see https://prettier.io/docs/en/ignore.html#javascript

@thorn0 
Helped, but adding comments it is the only way?

**Comment by thorn0** [comment]
@fakhamatia yes
