### ISSUE TITLE
Disable appveyor on prettier/plugin-php

### ISSUE THREAD

**Issue by czosel** [prettier/prettier#7223]
Over at the PHP plugin for prettier we recently switched to GitHub actions, replacing both Travis and AppVeyor. Unfortunately, AppVeyor still runs on every PR (example: https://github.com/prettier/plugin-php/pull/1281), even though we removed the webhook and the config file. In https://github.com/prettier/prettier/pull/5410#issuecomment-438893526 it was mentioned that the GitHub app needs to be disabled, which I don't seem to have permission for. Can someone help out? Maybe @ikatyang?

Thanks in advance :blush:

**Comment by ikatyang** [comment]
👉 https://github.com/prettier/plugin-php/pull/1277#issuecomment-573014803
