### ISSUE TITLE
GraphQL: Support `repeatable` DirectiveDefinitions

### ISSUE THREAD

**Issue by timkendall** [prettier/prettier#7226]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATAlgJzmG6BucABAAIBmEEAFAEYCGmSRAyjJulAOYCUR2ADnDow6NADbFoRAGIBJAKIAZACIB9ZfLkA5WQBVZAeS0gANCAj880AM7JQDTBADuABQYJbKOvgjpUpkBpMOjAAazgYZn4Qjk5kNgBXODMACxgAWzEAdRT0eGtosDhmDzyCPIBPZHBrWzMOazhMGBdgznS6ZDI6MUazACtrAA8AIWCwiOY6dLhFDjgunr6QQaHmWIkARQSIeEXe5JBozEbMas5g-hSARzEA-nZYLL8YFOQADgAGMweIRqzLtUHnBToQAtcdvBWhZPCA6NYALRQOBwVCogLYCFYOCtOjtTpIboHMyNdLoeKYJIkjZwba7BaEpaHEQ0Z6oV7IABMZjYdHQYliAGEIOkOtUoNAFmYEo1dKJPETlvgkrIoGjYMwwOxLABBNWsCoSfaNAC+JqAA)
```sh
--parser graphql
```

**Input:**
```graphql
directive @foo(bar: String) repeatable on FIELD_DEFINITION
```

**Output:**
```graphql
directive @foo(bar: String) on FIELD_DEFINITION

```

**Expected behavior:**
`repeatable` should be printed in the formatted output.

**Comment by sosukesuzuki** [comment]
Closed via #7227
