### ISSUE TITLE
single line ternary expressions don't need parens and newlines, they just don't

### ISSUE THREAD

**Issue by iratner** [prettier/prettier#7230]
I know that this was the result of #2208, but I think it makes ternary operators with single line expressions after the condition very hard to read, and unecessary.  I've seen that you won't work on this again, but is there really no way to change it for the single line expression case?  Or add an option? This feels especially true because Prettier doesn't format the single line expression, so why add all the extra bits?

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8BOUCGAnpgLyYAUwAthAEYCWANnABL0AmcAKnAB4wAabHxgBhCFQAO0BDAC+ASlIA+CgB0omTAB40k-FGUatJzNTpNWHbiNIkyMHAFc4mY6Y8B+HV3y1mMADyOABC9ADm4XA4ysDw-OJSMrBy2gD0vv5wQaERUTHuHiZIwgkS0lCyhSZypoXpegZGUAogAiAQkjD06Mig+Dg4EADuAAoDCGjIIPgAbhAcbSC0OPhgANbZAMr6YPRQ4ciOLu0AFjBUjADqp-TwjWBwW5N39LN3hNNgaFPt+2jRGCjVbhKj4ZAAM3wjAB7QAVmheCFVhttvgqHAADL7OCQ6GwkAI3hbfbhZgARScEHgeJhcHa+hwAJw01ofjgjCWkhw+xgVw4MFOyAAHAAGBlDAFXVaSabcuDM2a49oARyp8GBnSmKHwaAAtJU4Jx2EscHA1fQzcD8KDwUgoXT2gCqPQjs56SA0KSKercfb8R6YH5+exBcgAEztRz4JikxJg6ZQGRLJwAzLah0E2YuACSUE4sC2YB5XQAgvmtjBCMxaQC5HIgA)
```sh
--parser babel
```

**Input:**
```jsx
const ternay = ({mobileHideText, textComponent}) => (
  <span>
      {mobileHideText === true 
          ? <TabletOrBigger>{textComponent}</TabletOrBigger>
          : textComponent
      }    
   </span>
)
```

**Output:**
```jsx
const ternay = ({ mobileHideText, textComponent }) => (
  <span>
    {mobileHideText === true ? (
      <TabletOrBigger>{textComponent}</TabletOrBigger>
    ) : (
      textComponent
    )}
  </span>
);

```

**Expected behavior:**
```jsx
const ternay = ({mobileHideText, textComponent}) => (
  <span>
      {mobileHideText === true 
          ? <TabletOrBigger>{textComponent}</TabletOrBigger>
          : textComponent
      }    
   </span>
)
```

**Comment by thorn0** [comment]
This way to format conditional operators inside JSX is idiomatic and is not going to change, sorry.

BTW, if the whole expression fits on one line, Prettier doesn't fomat it this way:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8BOUCGAnpgLyYAUwAthAEYCWANnABL0AmcAKnAB4wAabHxgBhCFQAO0BDAC+ASlIA+CgB0omTAB40k-FGUatJzNTpNWHbiOOn7Afh1d8tZjADyOAEL0A5n5wOAD0Rpr2pkjC-OJSMrB2pnKmidrBegZhCiACIBCSMPToyKD4ODgQAO4ACmUIaMgg+ABuEBw5ILQ4+GAA1nAwAMr6YPRQfsgwOACucLkAFjBUjADq8-TwGWBwg-Ub9M0bhI1gaA25Y2hBMNXdflT4yABm+IxXuQBWaLze3X0Dg3wVDgABkxnBnq93iAvrxBmM-MwAIrTCDwSFvOYgfQ4K44Rq0VxwRgdSQ4MYwFYcGDzZAADgADLkyRAritupJGmS4HjmhDcgBHVHwW75BoofBoAC0UDgcE47A6ODgQvoytu+HujyQL0xuSuVHokxmWLQCORwohOqhWJgrip7BpyAATLkpvgmAjYg9GlAZB1plcXLRxbroc1ZgBJKCcWCDMDkgoAQRjgxghGYGKucjkQA)

```jsx
const ternay = ({ mobileHideText, textComponent }) => (
  <span>{mobileHideText ? <TabletOrBigger /> : textComponent}</span>
);

```
