### ISSUE TITLE
end of newline

### ISSUE THREAD

**Issue by tang412** [prettier/prettier#7232]
How to remove the end of newline，I think it's ugly

**Comment by kachkaev** [comment]
@tang412 could you please elaborate? Please follow the [issue template](https://raw.githubusercontent.com/prettier/prettier/master/.github/ISSUE_TEMPLATE/formatting.md) and include a Playground example.

**Comment by tang412** [comment]
> @tang412 could you please elaborate? Please follow the [issue template](https://raw.githubusercontent.com/prettier/prettier/master/.github/ISSUE_TEMPLATE/formatting.md) and include a Playground example.


### like this.
![before](https://user-images.githubusercontent.com/30660709/72036160-ea163180-32d4-11ea-9fe3-7d1798187661.png)
![after](https://user-images.githubusercontent.com/30660709/72036234-221d7480-32d5-11ea-9a56-8cf62920f93a.png)

### new line 4

Beautify has the same function and can be set

**Comment by kachkaev** [comment]
There is a good engineering reason why prettier always adds new lines to the end of files. This helps get less noisy diffs, see https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file for an explanation. I don't think the behaviour will ever change.

**Comment by tang412** [comment]
Although I dont understand, I still think it’s better to be configurable

> There is a good engineering reason why prettier always adds new lines to the end of files. This helps get less noisy diffs, see https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file for an explanation. I don't think the behaviour will ever change.

**Comment by evilebottnawi** [comment]
We don't want to do it configurable, sorry, you can use prettier-eslint and setup eslint rule to achieve that

**Comment by armano2** [comment]
Shouldn't we pick this value from editorconfig?

**Comment by thorn0** [comment]
@armano2 This has been discussed in https://github.com/prettier/prettier/issues/6360
