### ISSUE TITLE
HTML tag with colon breaks formatting

### ISSUE THREAD

**Issue by louis-bompart** [prettier/prettier#7236]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBnGA+AOlVAdwEsYALCAVxgFpIAbaPAgE2IDdtUyBGbAGQgAnOAFsABMQAOGShJYRGQ8RlLiAhqLgwANOMhQMcMPBiVl6tlOIYwxKAHNxceqQB04gCKUb4yvRghYjs4DBV1B1IYXyl-dnt1IQ8ANVDogCN-OQ1YOEkZbKkg0V97cQAzdUo7TLDhO3F6arMw7T8AoLBQ8SkIWTgRfUp04ld1cQBhc3U4AG5J6ZGzZX96TUghKQH9aHZ1elcwhSVxKGMVLvoBmwBHSjgPADlNCqDHUbXxY+FT6HEyBAsERBGCNCDpYTRDAeACywhG4juvigNmIOXgKTSxEyTQkGEUrjsZjYUFO52ksgk6jA4nYCAQ6ihTxe5Xs2MoYVEiixeW+yjaLjgxHKgI8AEF6epSYznD4MFyWKcbPQPAB5IQNPZBDmnRkQO55LZQRns1qg0QRFFHGKJZbEBDm6CYPTG2zacziIJsMBZTkcjwABTI6iMBx1q3Wwi2Fg1lEkpMFwsBtKxOLkmKw7Nx-0BwLUUjWXSEMtc6QGED0dPo4miUDsLEosHEFvMvn2xANoOExpEHk80HOgq0sDkej5iLlKg5dmsoJGZagDdEelL5ZrkJ+6TWi7UZwNeiMiqqJh+LjUy2sYWIiqgjbAHgAyhyjWwMEYVBAWPtuq4HP5xlWzbcpmeS1vWjYwG4qAAPS8Fw0FsJw+CoLYQRSDg+AGFgFR3uIAC8OF1tE0AABQAJTiMAOyGNybiMA4JEAOQABIuIwejkAMcCMWRswAL7IdBqHSBhBDQSQ5BULQDBMMhElkEgMlQMwqCIVwcGCCIEgUtk46qKCmjaHoWHGKYHqWNINh2I4ziuJBXiTv4gTBPaYQYBEUQxHECRJOIqSZmmVK5PklI9MUpSkpU1SmuI9Rok0Jg6m0TmdN0vT9IMPojGMCzFnMuXqEsHoRqIGzRtRewHL445nDSbpXEEGAGsyEjlG8kQHOMNV-ACi55qCjAQkITLiHCQgIkiYRWmiUoYn5qZZHiBIucSZS1SF2TUimZzGiNzytWytRAVcIFfIop6gomIqLuKkrSpdcoKkqGAquI6qaokxA6rt+r3D0DIZEl5qWtVNrDa2DpAbkGAuiGXTLJ617BL6zb+uIQYhmx4adaVUbbIkPrxrZQrXYqdIBYtGaA9mvVAtcoIFtSAwlti5aVi4Nb2OBTYto1GiuJ2sVCD2DxeAONJDg6o5nSck1TrYllzqzi7S6uQgQOuw2btubCgnu9wHnAR7NKedk1uYl6SDed6Ps+gI2O++JfidjTEH+nyAVyJ3RKBXPXhBUGwXwMFqchwnocwWGguUuEETHRHEKRFFUVhtH0UxrEHBWNYAiIPH8YJ4eiTB8mKedylyaQClKTQUosDQX4YGQKlqdwfCaWIG3yOdyj6RoWi6NRRgmO6FhWFZ9hOGe9neL4KUud07mRDAUI9N5PZU1mm3BTpEhFMQJRXpFx4xXFjTNED7TOV0YTpfcmXDKMxDjFMeXzK-hWkMVONldsBiVYcGWPx1r1WuE1e4LVXiTw+F1HuvxSS036mCIaI0xoTUnNNdEot-LU2yPiKqRJKAkjJDSXeGgaR0h2iaaE4h9oVEOjqL2PIgH8kulcJMN1xASjOFKDQD0bBPStK9d6aItRfSmnqA0-1doxTaBaBwVovhgztJDLk0NYZugRl6ZGTQ-Q0IxqGXR7Q1i402PjWMRMrrJnJrg0Qm9Ao5j6vTHohZmYDVZurdm1YwL+x5lUPm7ZBbdkSKLfs61JYjmXCwicvhZAK1nOIecgJVYeI1jADcygtx113HAfcKgjYaBNvyM2F5SjWzrLbDAL4HZ5Cdt+MIv5-wpmrEw06PiGywEDnBEOHAVJF0jtAbC8caRxzvMRKA5FKJDzThABiLE2LZ04nnXiAkxL9MEqXGudcG4hmbshRuZAaCbPLi3XpbcBDCE7mQvSahDKDxMiPBGFlLzWSnnZPsjkOgLzch5FeXl6DxA3vNCm2ZZp5DIfvQ+RMoo1B1GfBKLRnCgnnjfHofR755Cyk-F+0x8ofyKisH+eNlD-32IAmq5xQGNWarQlk7UYHRKgD1XMzjBqQhsLCeEaI5aYLBfYxaH4CFf2IetMhW1KEAw5bSg6KIjqtJ9tEgU7DSa3R4fdWUAjPzPWERqURn1vqSL+kaE0R05Eg2tLfW0EMeZOlCBo+GHptE+iMaINGBisZhBKr-GMhMyhWMXCmEF6ZgW2McXTEELimbFncWWTxzTOZ1l8cDVsYRAn3C7MLEJfZxbE2HGYKJ445ZxJnGoJJKsolqzSRkxJOscl5MPIUk8xTzwWzKacG24gnxVPtm+Wpn56mu3dgBDm8r7QJu5pBGC3SEK9LDmANCoko6ERGcu8ZkyU6DJmXMzO7Ec5cXzqsmC6yxIHKOVXMujAK6sF2We8gF7oC10XDspupzODnI7tpAo3cTh9zucZQZplR4aHHgrGy08Plzy+SEH5y9V6xABT5floKd5frCgfCKFQT5HXhRfM0V9Uq33RVxIY2Vn4FTxYsL+hKTHeoqmS6qcCQGXDATSuhbVoGdUZcypxEa2XDSlWg7lGDURYKQ3g5ahCRXklQ+K+kMiaFsYYZyYCCrxxKpJqKLhd0+EavlFqoRapdW0n1RI9JUjjWAzw-IxRr4ehWqCKo21MNdSaMdUjZ1jC3XBkMdjGjxKNAWL9cq6xC1cRiYkIg5xjMiws1jdnQC7SILNn8W2AW6ahYi2zeEq4ebpaFsnMWxWiTlZLhXKkzW6TMm1r1rkg2+TjZNtsi2zYbbbwVM7XbHcvaPzOx-G7JpnsVNjsS50qdwcZ1IQIMepdwz8KrsThM5O0yrh0VmRnBZHFc7cRWYXedIkVIIRvccy9j764HIO5gHAIAdAgAgOhBbGBkCgESOrQgAYQmGGQCAdQ7AIDXmuyAdIxYwAAGttAPikNSSeyBAgGxAGQGAoh6AAHUyCkFCJDroD4ED6Q4KQAAnl9sAb4Af2CMMNAMxYHAWmQJUegRgbsACsMAAA8ABCwOwcwAfIZfg9g4C0-2AzkAzOWcPknlcAAipQCA8BBf07gDdyHQhydfYR0jgH+9YDI+vOQZAAAOAADEr9WRhkfFikF9oooQBh0gB3cWXcBKd3ceygEMNAzhGyNgDkQSIRCU4iDTpAdPhdGBKDDoQcPVCOClzLuXweheK5ADAQqOuWB66QAAJhu4EdQT9HATAgKIIPIAmVnABxyOAAAVQqruQ9J-YPcAAkouB0D49voTFIuB8MB8dXHl0YPifEgA.)
No special options.

**Input:**
```html
<with:colon>
<div><h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultricies sagittis pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ullamcorper convallis dolor nec scelerisque. Nam fringilla dolor non hendrerit lobortis. Morbi quis nisi ante. Vestibulum sollicitudin nec ipsum ac venenatis. Nam finibus molestie dolor et eleifend. Aenean at euismod nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus ullamcorper arcu in eleifend vestibulum. Vestibulum hendrerit placerat libero, vel tincidunt mauris aliquet ornare. Donec elementum, dolor quis suscipit bibendum, libero tortor blandit neque, sed auctor elit turpis id nunc. Suspendisse sodales ligula vel molestie tincidunt.</h1></div>
<script>
const func = function() { console.log('Hello, there');}
</script>
</with:colon>
```

**Output:**
```html
<with:colon>
  <div
    ><h1
      >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultricies
      sagittis pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et
      ultrices posuere cubilia Curae; Curabitur ullamcorper convallis dolor nec
      scelerisque. Nam fringilla dolor non hendrerit lobortis. Morbi quis nisi
      ante. Vestibulum sollicitudin nec ipsum ac venenatis. Nam finibus molestie
      dolor et eleifend. Aenean at euismod nisl. Orci varius natoque penatibus
      et magnis dis parturient montes, nascetur ridiculus mus. Phasellus
      ullamcorper arcu in eleifend vestibulum. Vestibulum hendrerit placerat
      libero, vel tincidunt mauris aliquet ornare. Donec elementum, dolor quis
      suscipit bibendum, libero tortor blandit neque, sed auctor elit turpis id
      nunc. Suspendisse sodales ligula vel molestie tincidunt.</h1
    ></div
  >
  <script>
    const func = function() { console.log('Hello, there');}
  </script>
</with:colon>
```

**Expected behavior:**

```html
<with:colon>
  <div>
    <h1>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultricies
      sagittis pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et
      ultrices posuere cubilia Curae; Curabitur ullamcorper convallis dolor nec
      scelerisque. Nam fringilla dolor non hendrerit lobortis. Morbi quis nisi
      ante. Vestibulum sollicitudin nec ipsum ac venenatis. Nam finibus molestie
      dolor et eleifend. Aenean at euismod nisl. Orci varius natoque penatibus
      et magnis dis parturient montes, nascetur ridiculus mus. Phasellus
      ullamcorper arcu in eleifend vestibulum. Vestibulum hendrerit placerat
      libero, vel tincidunt mauris aliquet ornare. Donec elementum, dolor quis
      suscipit bibendum, libero tortor blandit neque, sed auctor elit turpis id
      nunc. Suspendisse sodales ligula vel molestie tincidunt.
    </h1>
  </div>
  <script>
    const func = function() {
      console.log("Hello, there");
    };
  </script>
</with:colon>
```

I think that either the parser should accommodate colons as shown ☝️ , either throw an error/warning when this kind of invalid tag occurs.

**Comment by louis-bompart** [comment]
Hi, from what I checked, the issue is still present. By that I mean that the expected behavior is not equal to the output yet: The content of the script tag is not formatted properly even with 2.0.2.

You can see it in the original playground of this issue.

**Comment by thorn0** [comment]
> The content of the script tag is not formatted properly

Oh, right. Thanks for noticing that.

**Comment by fisker** [comment]
I'll fix it.
