### ISSUE TITLE
Allow node_modules directory

### ISSUE THREAD

**Issue by lloydbanks** [prettier/prettier#7240]
My current project structure looks like this:
- app
	- node_modules
	- public
	- src
		- **node_modules** // no npm modules here, just my source files
			- pages
				- globalFeed
					- index.js
		- App.js
		- index.js	
	- .gitignore
	- .prettierignore
	- package.json

As far as I can see, prettier ignores `node_modules` by default.
**But I also have `node_modules` inside `src` directory and I don't want it to be excluded.**

I've created `.prettierignore` as an empty file and also tried this entry `!./node_modules`, but it didn't help to rewrite the default patterns.
Still getting error:
```
cmd.exe /D /C call C:\Users\admin\AppData\Roaming\npm\prettier.cmd --write src\node_modules\pages\globalFeed\index.js
[error] No matching files. Patterns tried: src\node_modules\pages\globalFeed\index.js !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**

Process finished with exit code 2
```
So my question is **how to ignore `node_modules` folder only on the top level?**

---

**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: WebStorm
- Runtime: WebStorm
- Operating System: Windows

**Steps to reproduce:**
Create `.prettierignore` in the project root
Leave the file empty or add `!./node_modules` rule to rewrite default ignore patterns

**Expected behavior:**
`node_modules` should be ignored on the top level only 

**Actual behavior:**
`node_modules` inside `src` directory is still being ignored

**Comment by evilebottnawi** [comment]
What is use case to prettify `node_modules` on any level? Don't use `node_modules` name because it is special folder, also in theory it can break resolution algorithm

**Comment by lloydbanks** [comment]
@evilebottnawi, well... such folder structure helps me to resolve module paths inside my imports. e.g this ugly string
`import Pagination from '../../../components/pagination'` 
turns into 
`import Pagination from 'components/pagination'` 

I know it can be done with webpack aliases but since I'm using `create-react-app`, eject is not the case.

**Comment by evilebottnawi** [comment]
It is bad practice and i do not recommend to use it
