### ISSUE TITLE
Placeholders in Template Literals may split w/ new-lines

### ISSUE THREAD

**Issue by CNSKnight** [prettier/prettier#7244]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKkoGcYAIBmcMYAFgJLwC2uAvLgIZYCeGuAFMLpJZQJYwAaXABNeWAA71iJIQHMi8AE5YhOKXFwBfIfziUAlLQB8uYOlxdoOXIrgTaDAO71+DAB68IWDuYu4ArooANki4AOQkMDDiWEgA9HFYEJRwALSK9FDCyamBQQB0UERhvpr6+WBSpGxwiorGpr4WQUS4tYoAIuoA3E24vPjs7fm2ElZwhmZQfn4DQ3UjduLj+Wow-li0NHQALAAMO5N9M6ISVSRsEZnCLQCidRCKYUJTM2+4WLUAbrxgcKFhWxgXjif5BCD0YTPY5vT5fWr8JgArD+MB-LBYaHTd5+dqPUIAA3yxIARkF6CRcGSKcT8gSYRYyr1se9uHwYJc1PJnrgAPIkgBWcDAMHyjCwvFkUDYYHBRQ6cDg4jYukoABU9OJyfB9DoqPp9Mz3po2kFPo0WW92l14A4io5cDa4GxDQyRGJJNJLiRrncHk8Xm6LJ9FD8-gDCNIkKqsTi-HCETAkeE8QGg7gErgAArkv4kCBBYS1Ta8aYayha9S4AAyugyQVwJFqGko9CYHy1rnw-igAGswrwgkEmOnUwBBQn3RSPXAAEmAw1Gy2wcFWMCkG00oXni6WKzWGw1bhgJp3dSd+Xwj1bHLCAG0AKRjoQPshIB8AWXyD4AyrgH+IAC6YT6JoBICOmmYAOqPL29DTj2wj9JsMAQLg4i2KkWBBK4rZQP49BDu2o7+gAQpO-pzguCxLvu67rFgW7mGeiiLGMK5rhuWBHieVHWuol7XlIlyPs+-5vp+35-gBwGgfSlozEyMKaH0JpwGaGivDi-G2nQ9qOuoLpGm8mYwCQYi4I4g4NnAsj9IMZkaAgwjLKWeD4C4ZowqcnrVFcWR+tOAYWnGIZhv84SRqQ0ZULGOIJooiIRlIhFxe8qahO0ymupaKnYkpUCaN0IACCAEDiDAnjYMgoDwdOjhZvBCBYMgID0F8EC8MIJUgCSGRgL2RA-pIwJQLIyAwIo-hwKVkSUEEUHmfAZx-D+zX8LwPxJq1YAYj1pYhjAWYZLIrbIB5GmlQKWBuKR-WDTAP70CktZFOdhGfFdN0-qWsgtAAiv4EDwO9l0gJIyi1K1JL0CS6k9RhblQV1ZnIAAHHspUYV4cBQRk4itRhdjfHAPUAI5A-Ax3lS1KCMKkRRwEW3WlbYFO8LYx30Kd9Cg59ICfHwE1TTNAu-QDlOk0gF38+uJLI8IqNIAATKVk2eb9ADCyRnSgUDQKTpUbHAaqw7TMui1801kFkCCPWAiUVWOWQ-kmLR83AmiaEAA)
```sh
--parser babel
```

**Input:**
```jsx

const fetchItem = async ({ commit, dispatch, getters, state }, item) => {
  const resp = await axios({
    url: 'https://some-random-url.net'
  }).catch(err => {
    let errDate;
    if (err.response) {
      if (err.response.status === 404) {
        dispatch('handleError', {
          service: 'recipe:load',
          severity: 'success',
          error: `...blah blah...`
        });
        commit('stage', Object.assign(cloneDeep(itemTemplate), item));
      } else {
        errDate = new Date();
        dispatch('handleError', {
          service: 'fetch:item',
          severity: 'error',
          // Placeholders in Template Literal here may split funk'illy
          errorA: `Error ${err.response.status}: ${err.response.statusText} ${errDate.format('[%A, %I:%M.%S %p]')}`,
          // Workaround is to pre-slit manually 
          errorB: `Error ${err.response.status}:
 ${err.response.statusText} ${errDate.format('[%A, %I:%M.%S %p]')}`
        });
      }
    } else {
        errDate = new Date();
      // this will eg if the endpoint fails
      dispatch('handleError', {
        service: 'fetch:item',
        severity: 'fatal',
        error: err
      });
    }
  });
};
```

**Output:**
```jsx
const fetchItem = async ({ commit, dispatch, getters, state }, item) => {
  const resp = await axios({
    url: "https://some-random-url.net"
  }).catch(err => {
    let errDate;
    if (err.response) {
      if (err.response.status === 404) {
        dispatch("handleError", {
          service: "recipe:load",
          severity: "success",
          error: `...blah blah...`
        });
        commit("stage", Object.assign(cloneDeep(itemTemplate), item));
      } else {
        errDate = new Date();
        dispatch("handleError", {
          service: "fetch:item",
          severity: "error",
          // Placeholders in Template Literal here may split funk'illy
          errorA: `Error ${err.response.status}: ${
            err.response.statusText
          } ${errDate.format("[%A, %I:%M.%S %p]")}`,
          // Workaround is to pre-slit manually
          errorB: `Error ${err.response.status}:
 ${err.response.statusText} ${errDate.format("[%A, %I:%M.%S %p]")}`
        });
      }
    } else {
      errDate = new Date();
      // this will eg if the endpoint fails
      dispatch("handleError", {
        service: "fetch:item",
        severity: "fatal",
        error: err
      });
    }
  });
};

```

**Expected behavior:**

**Comment by evilebottnawi** [comment]
It is expected, we don't want change current output, you can look at https://github.com/prettier/prettier/issues/3368

**Comment by thorn0** [comment]
I'd say this issue is a duplicate of https://github.com/prettier/prettier/issues/3368 and it doesn't really look expected:
```js
          errorA: `Error ${err.response.status}: ${
            err.response.statusText
          } ${errDate.format("[%A, %I:%M.%S %p]")}`,
```
I'd expect the function call (the 3rd expression) to break instead:
```js
          errorA: `Error ${err.response.status}: ${err.response.statusText} ${
            errDate.format("[%A, %I:%M.%S %p]")
          }`,
```
Simple member expressions like `err.response.statusText` should not break in template literals.
