### ISSUE TITLE
Comments in function declaration parameters are moved outside parens

### ISSUE THREAD

**Issue by rtsao** [prettier/prettier#727]
This seems related to https://github.com/jlongster/prettier/issues/719

Before:
```js
function foo(/* unused1, unused2 */) {}
```
After:
```js
function foo /* unused1, unused2 */() {}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20foo(%2F*%20unused1%2C%20unused2%20*%2F)%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

This seems like unexpected behavior, but feel free to close this if it is.

**Comment by vjeux** [comment]
It would be nice indeed to keep the comment inside.

**Comment by yamafaktory** [comment]
I pick that one!
