### ISSUE TITLE
Typescript: Unreadable formatting

### ISSUE THREAD

**Issue by armano2** [prettier/prettier#7274]
**Prettier 1.19.1**

This is not ticket about code being reformatted, prettier produces really "unreadable" pice of code for this specific use case, i'm unsure how it can be improved but as is is not readable and its taking to much time to actually understand the code.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/experimental-utils/src/eslint-utils/RuleCreator.ts

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmAB0p98AlAVwBs4BZOGAQwBEnmAaEsq2h5tgIhgAzl1IUacADKoR8KHBzieUgMLR4ADxgrJfCABMp4gL74AZjgjp8AcgB0DgPQwRAWjgjqqWM95wdgDcJBjYeIT4TJiY1ACeLHAWTDQE5lY29i7RsQlJKdQwwSQkzs74AO6B1NRRlDA27KhgTDVxUYaG+DAAFnD4lDi1ANTd3r4Ehl5gOKiYMKjQlrj4mHAQsXAOJDBxa-hqOHDscAH8rMIi+AC8+ADy6KgwADxnjKzsF6Ic9oPUdgA+EKwPb9Q7HeBvZjPAAqDBEIiYAHM4ABJQxXOA6BAY-DyWZQJEAm6Ebj4QyXJAHI4nKFfETA8wAMnujxedMETFh8MRKPRIgBPzsFNEgOBJCx4QIFkoUDACyWAXB7FwAAo-sqGjgqaqcFIAHJMdBwKn43xIgCUN2JZsJVuIEjK+BhPTklll8sWpAqqBq+BRBHQlDAPXwxxEqCU3Qg+BafoqfVIvTdbuNOBRXR6MBgmBESDKSKePUoACMHJB0M46M1rCIIBYYM4YaCAMozOaNzA0ajOABMADYAMwAFgAnGSnTC7iw7vh3JVE90+lESxAAG79AAK5Hw1CYUAxQQ6XV2+xDcDAAGtzcscEv+pBYFiYA4jlL8AADQyfD+raxrPA4jJI4YEGUgZTlBVSBmCFTikZ4yTIKd5i9TFsQPK5ZUvKAIAqKAAG0AF09CQnlkTRXFnxxK5bSREjnQCWR5AQKMqIw-QZDkBQo1uRiuJYnAyQBVUHTIMgoCNOB6ONThEPJfJUjuFDoDEOSYJOPRTCpUSxIk41TRgAkkWBMT8BkpgqU1OC+HebkvF5CiBRMsSpmSRTlKgPNnSUqCGTUml4B1OSyEfbQYCpJVNGfOyEXI-kfmQ3zBWC-ANl8gB1ItEjcwoqUS1D6Kta5iRhPjmMUHBnNMC0IqkOgjHguF7LijEEp8gqGKkJjuJwYkdLIECwNJCRTPM7SUrIJwHHM+jTJFLz+tMsSpvMhx5tmpa-ipDUArVPS4AtDayFMDaTpS9T4FVULnxqzraG6gThqWsTH3kVKPJETLemygoCFuHJ4h+1JVQmlyFMKdqVKOl6op0Bw0oK0GLWc57BpwaCArgK7Yd0d6Mqy8GYGRlKzpG-BTCqxkQA4EAEZU5BQCYHBrAqTcmYQERkBAJg1wgVBDGpkASxwJgr0YFtMFF81kEMygpJALN0GodLXXgERJbAOAWw5p5UDXJ44i50ROZp3wRCUGBNxFpF0CYZBkmoc2aYAKxELQACERbFmAW0k2RFHt1onZAV2tBbc1aAARUoCB4EDx35clnBzZwLnT2mWZ5kFzACRgTLDF6ZAAA4AAYaZziBzfSkXMC5nOvCUDdBYARxj+ArY2TmUCYDxFDgKYBZpo5W9QI4reRW34+D83HhlvV5YjQko7buAp-l5gS3zwukF7GnDKYX1zQ0dBJ5QHCA5pyhzZhJgSy7h3g7XOXUQPBAffbeYAEEDxbXZaDX0wpggA)
```sh
--parser typescript
```

**Input:** / **Output:**
```tsx
import {
  RuleMetaData,
  RuleMetaDataDocs,
  RuleListener,
  RuleContext,
  RuleModule,
} from '../ts-eslint/Rule';
import { applyDefault } from './applyDefault';

// we'll automatically add the url + tslint description for people.
type CreateRuleMetaDocs = Omit<RuleMetaDataDocs, 'url'>;
type CreateRuleMeta<TMessageIds extends string> = {
  docs: CreateRuleMetaDocs;
} & Omit<RuleMetaData<TMessageIds>, 'docs'>;

export function RuleCreator(urlCreator: (ruleName: string) => string) {
  // This function will get much easier to call when this is merged https://github.com/Microsoft/TypeScript/pull/26349
  // TODO - when the above PR lands; add type checking for the context.report `data` property
  return function createRule<
    TOptions extends unknown[],
    TMessageIds extends string,
    TRuleListener extends RuleListener = RuleListener
  >({
    name,
    meta,
    defaultOptions,
    create,
  }: {
    name: string;
    meta: CreateRuleMeta<TMessageIds>;
    defaultOptions: TOptions;
    create: (
      context: RuleContext<TMessageIds, TOptions>,
      optionsWithDefault: TOptions,
    ) => TRuleListener;
  }): RuleModule<TMessageIds, TOptions, TRuleListener> {
    return {
      meta: {
        ...meta,
        docs: {
          ...meta.docs,
          url: urlCreator(name),
        },
      },
      create(context): TRuleListener {
        const optionsWithDefault = applyDefault(
          defaultOptions,
          context.options,
        );
        return create(context, optionsWithDefault);
      },
    };
  };
}
```

**Comment by thorn0** [comment]
How would you reformat this code manually to make it more readable?
