### ISSUE TITLE
Exit status 1

### ISSUE THREAD

**Issue by Legends** [prettier/prettier#7288]
Can someone tell me what this error means:

> [lint:prettier] npm ERR! code ELIFECYCLE
> [lint:prettier] npm ERR! errno 1
> [lint:prettier] npm ERR! crap@1.0.0 lint:prettier: `prettier "{**/*,*}.{js,json,md,yml,css,ts}" --list-different`
> [lint:prettier] npm ERR! Exit status 1
> [lint:prettier] npm ERR!
> [lint:prettier] npm ERR! Failed at the crap@1.0.0 lint:prettier script.
> [lint:prettier] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [lint:prettier] 
> [lint:prettier] npm ERR! A complete log of this run can be found in:
> [lint:prettier] npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-01-12T14_10_42_633Z-debug.log
> ERROR: "lint:prettier" exited with 1.

The error messages suck also the log file. Where and what is problem?

**Comment by evilebottnawi** [comment]
How we can reproducible that error?

**Comment by Legends** [comment]
Actually, the error here is not important, but I would like to get a concrete error msg which points me to the issue.
The error message above tells me nothing, obviously.

I would re-review the exception management of the package, because the error got swallowed somewhere along the way.

I currently don't have time to dig deeper into this. Close it, if it doesn't matter to you.

**Comment by evilebottnawi** [comment]
We want to improve error messages, but it hard to say what is happens in your case so we don't know what we should improve :smile:

**Comment by Legends** [comment]
I can't tell either :D I don't have a repo for reproduction right now. Will open it again, when i find time.
