### ISSUE TITLE
Netlify: configure deploy previews for `next` branch

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#7292]
Currently, PRs against the `next` branch aren't deployed to Netlify, so their Playground links don't work. Can we enable previews for `next`? Who has access to the settings? @duailibe @j-f1 ?

docs: https://docs.netlify.com/site-deploys/overview/#branch-deploy-controls

**Comment by azz** [comment]
I have enabled deploys for `next`. Could you test?

**Comment by thorn0** [comment]
It worked in #7403. Thanks.
