### ISSUE TITLE
Feature request: format Template literals without expressions as string

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7301]
Format

```js
const foo = `bar`;
```

to

```js
const foo = "bar";
```

`---single-quote`

```js
const foo = 'bar';
```

**Comment by thorn0** [comment]
It's ESLint's job. See https://github.com/prettier/eslint-config-prettier#forbid-unnecessary-backticks

**Comment by evilebottnawi** [comment]
@thorn0 i think we should setup that rule in prettier repo to avoid using "`" without expressions

**Comment by fisker** [comment]
@evilebottnawi already did #7304

**Comment by fisker** [comment]
@thorn0 @evilebottnawi 

I still think we should do this, 2 reasons

1. Not everyone use `ESLint`
2. `eslint-config-prettier` disable `quote` rule by default, so people have to override rules,  and it's hard to know what quote style is used in prettier config.

**Comment by fisker** [comment]
?

**Comment by evilebottnawi** [comment]
https://github.com/prettier/eslint-config-prettier#forbid-unnecessary-backticks

**Comment by evilebottnawi** [comment]
Out of scope prettier
