### ISSUE TITLE
Export the logger for plugins

### ISSUE THREAD

**Issue by Shinigami92** [prettier/prettier#7370]
# Export the logger for plugins

## Environments
- Prettier Version: 1.19.1
- Running Prettier via: CLI
- Runtime: Node.js v10+
- Operating System: Windows, Linux, macOS

## Steps to reproduce
- Just write a plugin ^^ (like `@prettier/plugin-pug`)
- Try to access the logger so that the CLI option `--loglevel` can take effect and can be used for the plugin
- Also benefit from chalk cli coloring

## Expected behavior

The logger can be used/accessed in a plugin

## Actual behavior

I had to write a logger by myself
And this could not be managed by `--loglevel` 🙁 

## Old Issue

#3585 that was `locked-due-to-inactivity` 👎

**Comment by Shinigami92** [comment]
@taion does this make you also happy?

**Comment by thorn0** [comment]
But what is the use case? As it was written in #3585 and hasn't been changed since then, the logger is part of the CLI. Prettier is used not only via the CLI. Plugins are just parsers and printers, pure functions that shouldn't have side effects.

**Comment by Shinigami92** [comment]
As said: I have written my own logger https://github.com/prettier/plugin-pug/blob/master/src/index.ts#L15

And I want to make it obsolete and use prettier's logger
Also (currently not resolved by the PR) I want to profit from the `--loglevel` cli option

So when running `prettier --write 'src/**/*.pug' --loglevel debug`, debug logs can be seen from the user to debug the plugin

**Comment by taion** [comment]
I’m not working on any Prettier plug ins at the moment.

**Comment by thorn0** [comment]
> and use prettier's loggers

The thing is Prettier itself doesn't have loggers. Its CLI does, but the CLI is a kind of separate thing. Think of it as of a separate package, which it (or a [completely new CLI](7073)) should eventually become. It's a Node program that uses Prettier API, whereas Prettier proper is an environment-independent library.

So even if we decide to support this use case, we can't do it the way you did in your PR. The plugin helpers (`util-shared`) can't use things like `chalk` or `process.stdout`. Pieces of the CLI code can't leave the `/cli` directory and can't be used in other directories.

**Comment by Shinigami92** [comment]
Ok that's a point I understand 😕
