### ISSUE TITLE
Stop Prettier from removing break after function open bracket?

### ISSUE THREAD

**Issue by KShivum** [prettier/prettier#7374]
Sorry if this isn't the right place to put this, but is it possible to turn off prettier from removing the break after a bracket after a Javascript function bracket?

**Comment by sosukesuzuki** [comment]
@KShivum Hi, please give a specific example according to the Issue template!

**Comment by KShivum** [comment]
Sorry, I mean stopping prettier from correcting:
``function()
{
code
}
``
to this:
`
function(){
code
}
`

**Comment by evilebottnawi** [comment]
Please provide example(s) with link on the playground with what you have and what you expected

**Comment by KShivum** [comment]
Not sure what you mean by playground but here's a pastebin:
https://pastebin.com/QC5hthBA
I want prettier to keep the formatting to the first block of code not removing the break after the open bracket

**Comment by sosukesuzuki** [comment]
@KShivum "the playground" means https://prettier.io/playground.
Is the below example what you expect?
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFAJQA6UwF++ZIAzhALZwwAWOUA5nRQL4gANCAgAHXNHrJQAQwBOciAHcACvIRSUMgG4QcAEyEgARnJlgA1qwDKo85y7IYc9HGFsYTADYB1DvHo7MDhrDRxcbXCAT2RweilhTno4ORgVMy4mGWRUGS9k4QAregAPACEzSxsZFgAZTjgcvIKQYpLrBy84AEV0CHgm-LcQOzlkuVjjGWM4LyNROU4YHwN2ZAAOAAZhBYhknzNRWIW4ce1G4QBHPvh0sU0QGXoAWig4OH0Pozk4a5wf9IyTLZJC5IbCZJMHBOFzDeidHo3Rqg5rDGDTFb6NZIABMwmcMhwXgcAGFmFlYlBoBcQOhkgAVaaaMEtbSuACSUE+sGsYEW4gAglzrDAol1Bsk+HwgA)
```js
// Input
function f()
{
  something();
}

// Output
function f() {
  something();
}

// Expected
function f()
{
  something();
}
```
Sorry, Prettier won't support the style.

**Comment by thorn0** [comment]
This has been answere
