### ISSUE TITLE
Dev releases

### ISSUE THREAD

**Issue by steve8708** [prettier/prettier#7376]
I see prettier doesn't use any dist tags, but I wanted to suggest a `dev` tag or similar (`npm publish --tag dev`) like other projects do to test updates on real users who are willing. 

I would be more than happy to use a dev/alpha/beta version of prettier (`npm install prettier@dev`) with features like TS optional chaining and happily send pull requests for fixes, and I would guess others feel the same

This could help resolve things like this long thread over here #6595 about asking for a release and waiting for things to be safe/stable

**Comment by thorn0** [comment]
This is already possible. [You can install Prettier directly from GitHub](https://github.com/prettier/prettier/issues/7176#issuecomment-572540357).

**Comment by steve8708** [comment]
Fair point, and thanks @thorn0
