### ISSUE TITLE
Breaks markdown segment links

### ISSUE THREAD

**Issue by tajpouria** [prettier/prettier#7390]
**Prettier 1.19.1**

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVBaVBtVBLKPGVAXQAoBiAogMigCMBnABwG4B2upt6mPAQwA2eAF5wuLVgBN+MfvX6NxDSfyhSJbCPQBWcMDE2tGMCACc4jAJQgANCAjM+0RslD8zZiAHcACh4RXFH4ANwg8KTsQejN+MABrOBgAZWY4ggBzZBgzAFc4ewALGABbQQB1QqJLNLA4ZMCiPBCiAE9kcEZXewIlMxhfWIyS-mQAMyElex1GAA8AIViEpOT+ErgAGQI4ccmCkBnZ5MzBOABFXIh4XcEpkDSzPo6Rs3ipHygo5jMCGHKImCFZAADgADPZvhAlOVYswOt9LHAzCEdvYAI6XeCDRxBECKDBQOBwKTEqIWDF4CyDfjDUZICa3fZKEp4bJ5Jknc6Ynb0vb2OT0f5SQHIABM-NieGEUAyAGEICURh0oNBUSBckoACryIIMu4hfIASXUCBSYB+TgAgupkjBWqcbkoAL5OoA)

```shell
["INFO" - 10:26:30 AM] Formatting c:\Users\p.tajdivand\.pro\fun\idborm\README.md
["INFO" - 10:26:30 AM] Loaded module 'prettier@1.19.1' from 'c:\Users\p.tajdivand\.pro\fun\idborm\node_modules\prettier\index.js'
["INFO" - 10:26:30 AM] Using ignore file (if present) at c:\Users\p.tajdivand\.pro\fun\idborm\.prettierignore
["INFO" - 10:26:30 AM] File Info:
{
  "ignored": false,
  "inferredParser": "markdown"
}
["INFO" - 10:26:30 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:26:30 AM] Prettier Options:
{
  "filepath": "c:\\Users\\p.tajdivand\\.pro\\fun\\idborm\\README.md",
  "parser": "markdown",
  "printWidth": 120,
  "trailingComma": "all",
  "singleQuote": false,
  "tabWidth": 2
}
["INFO" - 10:26:30 AM] Formatting completed in 130.5972ms.
```
Input:
```md
  - [ init ](#init&nbsp;·&nbsp;initialize&nbsp;database&nbsp;and&nbsp;object&nbsp;stores)
```

output
```md
- [ init ](#init · initialize database and object stores)
```

**Expected behavior:**
In this case, I wanna use a link as a reference to the current markdown specific segment and as you see the segment title contains space _&nbsp;_, but prettier totally break the link, I suggest that prettier not prettify links and segment links by default.

**Comment by thorn0** [comment]
Are the input and the output converted to different HTML? What tools do you use to convert Markdown to HTML?

**Comment by tajpouria** [comment]
Yes, you right, it highly depends on HTML converter I use for example:

**Github MD preview: _breaks_**
- [ init ](#init · initialize database and object stores)

- [ init ](#init&nbsp;·&nbsp;initialize&nbsp;database&nbsp;and&nbsp;object&nbsp;stores)

**VSCode _1.41_ MD preview: _breaks_**

![VSCodeSegmentLink](https://user-images.githubusercontent.com/46822325/72702254-4562e200-3b67-11ea-8878-79f27670b6cc.PNG)

**A Random converter like https://markdowntohtml.com/ _Pass_**

<ul>
<li><a href="#init&nbsp;·&nbsp;initialize&nbsp;database&nbsp;and&nbsp;object&nbsp;stores"> init </a></li>
</ul>
<ul>
<li><a href="#init · initialize database and object stores"> init </a></li>
</ul>

But at the end of the day, I believe prettier should avoid formatting markdown links by default

**Comment by thorn0** [comment]
You're not using Prettier's actual output though. You've replaced non-breaking spaces with usual ones.

**Comment by tajpouria** [comment]
In following example prettier turn **1 into 2** and as you can see it break the link, that's all I want say:
```md
1. [ init ](#init&nbsp;·&nbsp;initialize&nbsp;database&nbsp;and&nbsp;object&nbsp;stores)

2. [ init ](#init · initialize database and object stores)
```
Preview:
![pretteirLinkProblem](https://user-images.githubusercontent.com/46822325/72720387-0f395880-3b8f-11ea-99aa-a52f46832cd4.PNG)

**Comment by thorn0** [comment]
Prettier doesn't turn 1 into 2. Prettier outputs non-breaking spaces, but you have usual spaces in your messages here. Are you writing that "output" by hand?

**Comment by tajpouria** [comment]
[Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVBaVBtVBLKPGVAXQAoBiAogMigCMBnABwG4B2upt6mPAQwA2eAF5wuLVgBN+MfvX6NxDSfyhSJbCPQBWcMDE2tGMCACc4jAJQgANCAjM+0RslD8zZiAHcACh4RXFH4ANwg8KTsQejN+MABrOBgAZWY4ggBzZBgzAFc4ewALGABbQQB1QqJLNLA4ZMCiPBCiAE9kcEZXewIlMxhfWIyS-mQAMyElex1GAA8AIViEpOT+ErgAGQI4ccmCkBnZ5MzBOABFXIh4XcEpkDSzPo6Rs3ipHygo5jMCGHKImCFZAADgADPZvhAlOVYswOt9LHAzCEdvYAI6XeCDRxBECKDBQOBwKTEqIWDF4CyDfjDUZICa3fZKEp4bJ5Jknc6Ynb0vb2OT0f5SQHIABM-NieGEUAyAGEICURh0oNBUSBckoACryIIMu4hfIASXUCBSYB+TgAgupkjBWqcbkoAL5OoA)

**Comment by thorn0** [comment]
And that's how GitHub renders the output of your playground link:

- [ init ](#init · initialize database and object stores)

**Comment by tajpouria** [comment]
Yeah you right, and I'm totally confused how it works ?
input:
```md
- [ init ](#init · initialize database and object stores)
- [ init ](#init · initialize database and object stores)
```
output:

- [ init ](#init · initialize database and object stores)
- [ init ](#init · initialize database and object stores)

!!!

**Comment by thorn0** [comment]
See https://en.wikipedia.org/wiki/Non-breaking_space
