### ISSUE TITLE
do not  add blank before my <?php   header

### ISSUE THREAD

**Issue by dvaknheo** [prettier/prettier#7394]
**Prettier 1.19.1**
**Input:**
```php
<table>
<?php 
foreach($recordset as $line){
?>
    <tr>
<?php
    foreach($line as $v){
?>
        <td><?=$v?><td>
<?php
    }
?>
    </tr>
<?php
}
?>
</table>
```

**Output:**
```php
<table>
	<?php 
foreach($recordset as $line){
?>
	<tr>
		<?php
    foreach($line as $v){
?>
		<td>
			<?=$v?>
			<td>
				<?php
    }
?>
	</tr>
	<?php
}
?>
</table>
```

**Expected behavior:**

I want to keep the output as the same to  input

is any option to keep my php code  output ?

**Comment by thorn0** [comment]
Prettier doesn't support PHP directly, but there exists a plugin: https://github.com/prettier/plugin-php
You may want to reopen this issue in that repo.
