### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by kissu** [prettier/prettier#7396]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlMTKgJYYDmABEgM4BOYAvMSAAYB0PA9H0EChokeOp4acfgBJgANzzNKeAEY44AXx5YoNLp34koqfplwE4hEABoQELDErRGyUMuYQA7gAVlCG4oeAoQlAAmdiBqzHhgANZwMADKWHGU+sgwzACucPYAFjAYOADqBZTwjGlgcMmBlZQKlQCeyOCMbvYZjHDMML6xNBh4yABmeDi99gBWjAAeAEKxCUnJeBhwADIZcOOT0yBz88kZNJoAijkQ8PtT+SBpzL3M7Qp5UVhevaWxWO1fOAvBR7ewAR2u8EGjiCIDwjAAtFA4HBwqiosw4BDKJjBlIRndDr0MJQsrkHowzpdIXskBN7vYYOpShEYAVkAAmRmxSg4M4AYQgGAJKCg0FBIByvQAKuogvTDu84ABJKBo2DJMAqJwAQTVyRgLU0hIeXwyMBZ4TZyAALAAGLRaIA)
```sh
--parser vue
--print-width 40
```

**Input:**
```vue
<template>
	<img :src="`../../../../../../../..image/${variable}.png`"/>
</template>
```

**Output:**
```vue
<template>
  <img
    :src="
      `../../../../../../../..image/${variable}.png`
    "
  />
</template>

```

**Expected behavior:**
```vue
<template>
  <img
    :src=
      "`../../../../../../../..image/${variable}.png`"
  />
</template>
```
or anything alike, but do not put the double quote alone on a single line.

Not sure if there is some kind of flag to set to prevent that. :sweat_smile:

**Comment by fisker** [comment]
Actually, it's not bug. 

We print all long expression on new line

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlMTKgJYYDmABEgM4BOYAvMSIxBnHQD786OaPUF04ADyzM4jRjErQBQmAAsCKumDxQtUCDC0AzSjE4B6ElFQXMuAnEIgANCAhZF0RslB5mzBAA7gAK-gg+KHgAbhCUACauIABGzHhgANZwMADKWOmUUDTIMMwArnBuajAYOADqamZy+WBwORFmlNFmAJ7I4PJJhYxwzDAhaTQYeMjGeDgjbgBWjJIAQmmZ2Tl4vAAyhXCz84sgK5I5hTQ4cACKZYZHSHMLlSD5zCPM-dEVSTKFGB1BLqZAAFgADG4ZBARnU0lh+jI5KNokc3ABHB7wCYeSIgPCMAC0UDgcHi5KSsixlFkEzwUxmzxObxGGEoJXKrKuN3uj2OrzcMDwyWB8VBSAATEK0pQcFcAMI8ab9AykpJlEYAFRFkRep1+cAAklAKbAcmBmJRPABBU05GA9G4CkYAX1dQA)
```sh
--parser vue
--print-width 40
```

**Input:**
```vue
<template>
	<img :src="some || long || expresstion || that || can || not || fit"/>
</template>
```

**Output:**
```vue
<template>
  <img
    :src="
      some ||
        long ||
        expresstion ||
        that ||
        can ||
        not ||
        fit
    "
  />
</template>

```

**Comment by fisker** [comment]
But I think put single `TemplateLiteral` and `StringLiteral` on the same line with attribute more readable.

**Comment by fisker** [comment]
@kissu What do you think fix yor case in this way?

**Prettier pr-7479**
[Playground link](https://deploy-preview-7479--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlMTKgJYYDmABEgM4BOYAvMSAAYB0PA9H0EChokeOp4acfgBJgANzzNKeAEY44AXx5YoNLp34koqfplwE4hEABoQELDErRGyUMuYQA7gAVlCG4oeDjeeACebvZqzHhgANZwMADKWHGU+sgwzACucPYAFjAYOADqBZTwjGlgcMmBlZQKleHI4IxRIBmMcMwwvrE0GHjIAGYhPfYAVowAHgBCsQlJyXgYcAAyGXBjE-kgM7PJGTSaAIo5EPC7OJMgacw9zG0KeXb3KrCllAAmMAXIAAsAAZ7FgvD1SrEsG1wXAngodvYAI6XeADRxBEB4RgAWigcDgPyJ72YcFRlDJAykwxudx6GEoWVy+0YJ3OaJ2SHGt32MHU3z+AKQACZ7Nk8JQcCcAMIQDC0lDwgCs7xyPQAKuogjy7q84ABJKDE2DJMAqJwAQWNyRg4U0dO0WiAA)
```sh
--parser vue
--print-width 40
```

**Input:**
```vue
<template>
	<img :src="`../../../../../../../..image/${variable}.png`"/>
</template>
```

**Output:**
```vue
<template>
  <img
    :src="`../../../../../../../..image/${variable}.png`"
  />
</template>

```

**Comment by kissu** [comment]
> But I think put single `TemplateLiteral` and `StringLiteral` on the same line with attribute more readable.

Not sure of what those actually are. 😅

> **Output:**
> 
> ```
> <template>
>   <img
>     :src="`../../../../../../../..image/${variable}.png`"
>   />
> </template>
> ```

This one is actually great tho because it keeps the double quotes on the same line and splits the beginning and ending of the tags on a new line, yes! 😁
And it's super readable IMO. 👌🏻

**Comment by thorn0** [comment]
closed by https://github.com/prettier/prettier/pull/7479
