### ISSUE TITLE
Let's use GitHub actions / workflows for linting tests instead of Azure

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#7401]
Suppose to be faster and it's without using 3rd party software. WDYT?

**Comment by BPScott** [comment]
Yo @lipis, getting stuff consistent across the org would be handy - shall we say GH Actions is the preferred CI flow for all stuff? If so I'll switch eslint-plugin-prettier / stylelint-prettier over to GH Actions too.

**Comment by thorn0** [comment]
We've done this, however the action `codecov-action` is [flaky](https://github.com/codecov/codecov-action/issues/68). If it stays like this, we should consider using Azure again for coverage-enabled testing as it was stable there.

**Comment by lipis** [comment]
@fisker can you check what is going on?

**Comment by fisker** [comment]
I really don't know why, people has this error too https://community.codecov.io/t/error-the-coverage-upload-was-rejected-because-the-workflow-run-is-either-not-in-progress-or-finished-a-while-ago/1116 , I suggest we can try upload with token.

**Comment by thorn0** [comment]
@fisker "Keep in mind that secrets are not available to forks of repositories." It means that won't work for pull requests.

**Comment by fisker** [comment]
babel use token https://github.com/babel/babel/blob/548cb3ee89552ffc08ee5625b084bd33f8107530/.github/workflows/coverage.yml#L29

**Comment by lipis** [comment]
Let's do this!

**Comment by fisker** [comment]
@lipis Can you setup `CODECOV_TOKEN` on https://github.com/prettier/prettier/settings/secrets?

**Comment by lipis** [comment]
@fisker  I sent you an invite.. you should get access now.

**Comment by fisker** [comment]
I don't have access to that page.

**Comment by fisker** [comment]
Just click `Add a new secret` 

Name: CODECOV_TOKEN
Value: [token from this page](https://codecov.io/gh/prettier/prettier/settings)

**Comment by lipis** [comment]
Added
