### ISSUE TITLE
 throw the error when there is flow shorthand annotation comment with other comments

### ISSUE THREAD

**Issue by strager** [prettier/prettier#7429]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAFAHSgAhwenx0gFsSEZs90AGAgKiRygFcSAjOAJx3vwEps-ANwgANCAgAHGAEtoAZ2SgAhly4QA7gAU1CJShUA3CLIAm4kOy4qwAazgwAylNuyoAc2QwuLOBIALGBIAGwB1ANl4BVcwOCd9KNkjKIBPZHAFJQl3BW4YbRsPEhVkVBUQvIkAKwUADwAhG3tHJxVyABl3ODKKqpBauqd3DxC4AEUWCHheyv8QVy48rgz2FU4Qyykudxgw8xgA5AAOGgltiDywmykM7bhlox6JAEcp+ELpAxAVBQBaKBwOBmYGWLhwN6ycGFFTFUpIcpzCR5Eiyby+eYKEZjSbTHoIvrzGDrfZmQ7IABMEh8KlkIRGAGEIGR4SAoNBniAWHkACrrAyI-pGPwASSgINgTjAOxkAEFxU4YKkxrM8gBfNVAA)
```sh
--parser babel
```

**Input:**
```babel
f(
  // comment
  (0 /*: number */)
);
```

**Output:**
```babel
ensureAllCommentsPrinted/<@https://prettier.io/lib/standalone.js:15543:15
ensureAllCommentsPrinted@https://prettier.io/lib/standalone.js:15541:17
coreFormat@https://prettier.io/lib/standalone.js:15592:29
format@https://prettier.io/lib/standalone.js:15832:75
formatWithCursor@https://prettier.io/lib/standalone.js:15848:14
withPlugins/<@https://prettier.io/lib/standalone.js:31794:17
format@https://prettier.io/lib/standalone.js:31802:14
formatCode@https://prettier.io/worker.js:234:21
handleMessage@https://prettier.io/worker.js:185:18
self.onmessage@https://prettier.io/worker.js:155:14

```

**Expected behavior:**
Prettier exits successfully. Prettier does not change the formatting of this code.

**Observations:**
The following changes to the input make the crash disappear:

* Remove the : in the comment on line 3
* Remove the ( and ) on line 3
* Remove the comment on line 2

**Comment by sosukesuzuki** [comment]
Thanks for reporting! Prettier seems to throw the error when there is flow shorthand annotation comment with other comments.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKADAAgPQComZQCuAtgEZwBOmu2OumkJJCMN2AlCADQgQAOMAJbQAzslABDSpQgB3AArSE4lJIBuEIQBMeIMpUlgA1nBgBlfkaFQA5shiUicXgAsYJADYB1V0PiiVmBw5ir+Qur+AJ7I4KLivDaiVDAKhrYkksgAZpKeybwAVqIAHgBChiZm5pIsADI2cDl5BSDFJeY2tp5wAIpEEPDN+S4gVpTJlLFkkhSeevyUNjDeOjCuyAAc6LyLEMnehvyxi3CT6k28AI4D8GkCqiCSogC0UHBw2p96lHA3Qr80pIMlkkLkRrxkiQhA4nKNRF0ev1Bk0wS1RjBZqttOtkAAmXiOSRCTxdADCEGYoJAUGglxARGSABVZqpwa11M4AJJQL6wcxgJaCACCvPMMCiPWGyQAvjKgA)

```js
// Input
(0 /*: number */ /* comment */)
```

```
Error: Comment "comment" was not printed. Please report this error!
    at https://prettier.io/lib/standalone.js:15543:15
    at Array.forEach (<anonymous>)
    at ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:15541:17)
    at coreFormat (https://prettier.io/lib/standalone.js:15592:5)
    at format (https://prettier.io/lib/standalone.js:15832:75)
    at formatWithCursor (https://prettier.io/lib/standalone.js:15848:14)
    at https://prettier.io/lib/standalone.js:31794:17
    at Object.format (https://prettier.io/lib/standalone.js:31802:14)
    at formatCode (https://prettier.io/worker.js:234:21)
    at handleMessage (https://prettier.io/worker.js:185:18)
```

**Comment by strager** [comment]
If a Flow shorthand annotation comment is detected, Prettier disables the [default comment handling][] and implements [custom handling for Flow comments][]. (This custom handling was implemented in pull request #5280.) The problem is that the custom handling only prints one comment (the first trailing comment), and forgets about all other comments. Prettier's sanity checks detect the fact that some comments were not printed, and reports an error.

This issue does not reproduce when using Flow's parser (`--parser flow`).

I see three solutions:

1. Extend the [custom handling for Flow comments][] to print all other comments too.
2. In Prettier, transform the AST given by Babel to make it look like the AST given by Flow. In particular, wrap each commented node in a TypeCastExpression node. (See the AST comparisons below.) Then, remove the [custom handling for Flow comments][].
2. In Babel, add an option to parse Flow shorthand annotation comments into TypeCastExpression nodes, mimicking Flow's parser. (See the AST comparisons below.) Then, enable this feature in Prettier's use of Babel, and remove Prettier's [custom handling for Flow comments][].

Which of the above solutions sounds best? Does anyone have any other ideas on how to fix this crash?

cc @swac, @j-f1, @lydell

# AST comparison

## Input program

    f(
      // comment
      (0 /*: number */)
    );

## `--parser babel` AST (abridged)

    Node {
      type: 'File',
      program:
       Node {
         type: 'Program',
         sourceType: 'module',
         interpreter: null,
         body:
          [ Node {
              type: 'ExpressionStatement',
              expression:
               Node {
                 type: 'CallExpression',
                 callee:
                  Node {
                    type: 'Identifier',
                    name: 'f' },
                 arguments:
                  [ Node {
                      type: 'NumericLiteral',
                      extra:
                       { rawValue: 0, raw: '0', parenthesized: true, parenStart: 18 },
                      value: 0,
                      leadingComments:
                       [ { type: 'CommentLine',
                           value: ' comment' } ],
                      trailingComments:
                       [ { type: 'CommentBlock',
                           value: ': number ' } ] } ] } } ],
         directives: [] },
      comments:
       [ { type: 'CommentLine',
           value: ' comment' },
         { type: 'CommentBlock',
           value: ': number ' } ] }


## `--parser flow` AST (abridged)

    { type: 'Program',
      body:
       [ { type: 'ExpressionStatement',
           expression:
            { type: 'CallExpression',
              callee:
               { type: 'Identifier',
                 name: 'f',
                 typeAnnotation: null,
                 optional: false },
              typeArguments: null,
              arguments:
               [ { type: 'TypeCastExpression',
                   expression:
                    { type: 'Literal',
                      value: 0,
                      raw: '0' },
                   typeAnnotation:
                    { type: 'TypeAnnotation',
                      typeAnnotation:
                       { type: 'NumberTypeAnnotation' } } } ] },
           directive: null } ],
      comments:
       [ { type: 'Line',
           value: ' comment' } ] }

[default comment handling]: https://github.com/prettier/prettier/blob/a858a315e926c21bd1ebfcde70a08419c9472a8c/src/language-js/printer-estree.js#L6009
[custom handling for Flow comments]: https://github.com/prettier/prettier/blob/a858a315e926c21bd1ebfcde70a08419c9472a8c/src/language-js/printer-estree.js#L241-L246

**Comment by fisker** [comment]
I was trying to fix this, before I saw commnet by @strager , spend a lot of time figure how it works... I tried a solution similar to solution1. Finnally make it work for `babel` but `typescript` parser still fail. will look into it later

**Comment by fisker** [comment]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAFAHSugjAAmwHoj9IBbchGbfIgKiXygFdyAjOAJ33qOPpkIlan2wBKCQG4QAGhAQADjACW0AM7JQAQy5cIAdwAKuhJpTaAbhBUATOSHZdtYANZwYAZUUuVUAObIMFwscPIAFjDkADYA6uEq8Oo+YHCeZokqlokAnsjg6pryfurcMEbO-uTayKja0aXyAFbqAB4AQs5uHp7aVAAyfnC19Y0gLa2efv7RcACKLBDwIw1hID5cpVz5qNGGDopcfjCxdjDhyAAcAAzyhxClsc6K+YdwW5bD8gCOi-AVSnMIG06gAtFA4HBbFCHFw4L8VHCKtoqjUkHVVvJSuQVEEQmt1NNZgslsN0aM1jBtOxTrZzsgAEzyYLaFTRaYAYWE1XyUGgXxALFKABVqeYMWNLKEAJJQaGwTxgI7KACCcs8MBysxWpQAvrqgA)
```sh
--parser flow
```

**Input:**
```jsx
f(
(1 
// comment
 /*: number */
/* comment*/
)
);
```

**Output:**
```jsx
f(
  (1 /*: // comment
  number */)
  /* comment*/
);

```

Is this valid code?

**Comment by thorn0** [comment]
Seems to be valid. Use Flow's [playground](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swoAKAQwEoBvAX3QtTDHIEYxQAuL4MXHAC2QgKbZ8LMNkxCARqIBOyYNSmgBwsRJSpqAbiA).

**Comment by fisker** [comment]
Opened a [new issue](https://github.com/prettier/prettier/issues/7510), maybe we should fix this first

**Comment by thorn0** [comment]
Not an issue anymore because support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687
