### ISSUE TITLE
YAML trailing comma optional

### ISSUE THREAD

**Issue by phifa** [prettier/prettier#7452]
**Prettier 1.19.1**

**Input:**
```jsx
`[update_vars, ]`
```

**Output:**
```jsx
`[update_vars]`
```

**Expected behavior:**

So instead of: `[update_vars]` we would get tags: `[update_vars, ]`. Right now trailing commas are removed by the formatter. An option to disable the removal would already be helpful, then I could set them manually. I like trailing commas everywhere, as they remind me of the type I am dealing with.

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue as closed

**Comment by phifa** [comment]
done

**Comment by j-f1** [comment]
No repro:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADA2gVwA4BMCG8A+gG74BOAzgDQAEAuqiNSBNjAJbSXKgXkQA7gAUKCHinwkIHXMxAAjcvjABrODADK2FRygBzZDHKY4LABYwAtgBsA6uY7xKOsHE3inHEk4CeycEoeFj1KOHIYYWV9K3xkADN8GzCWACtKAA8AIWU1DU18KzgAGT04BKSUkHSMzT19GzgARUwIeArksxAdKnCA30KbeWxyPRg7WRhzZAAOAAYWEYgwu2VsAJG4MPIScpYAR1b4KLYJEHxKAFooODhcO-lyOEOOJ6j8GLikRM6WMKsOEYTF1KPVGi02uVvpUujB8AoJrgpsgAEwsYz4Dg2eoAYQgVliASg0D2IEwYQAKvCJD8qiRTABJKD3WCaMCjdgAQWZmhgvkaHTCAF8hUA)
```sh
--parser yaml
```

**Input:**
```yaml
`[update_vars, ]`
```

**Output:**
```yaml
`[update_vars, ]`

```

**Comment by gkim795** [comment]
I would like to reopen question that @phifa has brought up. Has a solution been found to this yet?

**Comment by Rich-Farmbrough** [comment]
> I would like to reopen question that @phifa has brought up. Has a solution been found to this yet?

If you look at Jed Fox's response above, a reproduction case is wanted.  He gives a simple example where trailing commas are not removed.

**Comment by Rich-Farmbrough** [comment]
> No repro:
The playground link you give currently errors.
[This](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtArgBwCYEN4D6AbrgE4DOANAAQC6IlIEmMAltOcqGaRAO4AFMgk4pcRCK2wMQAI1K4wAazgwAypkWsoAc2QxS6OIzgBbWXGzZLAGVy70uHXABiEUqfxtdyELnQwEDIAFjCmADYA6sGs8OSaYHBqIrGsRLEAnr5g5JyM2uRwpDACCjqeyABmuOGFjABW5AAeAEIKyqpquKZwNtpwVTV1II1Nato64XAAiugQ8IO1xiCaFEW+Gd3hMpik2jCRUjDByAAcAAyMuxCFkQqYvrtwhaREA4wAjnPwpcyifuQALRQOCWSwyUhwL6sSGlJwVJDVJaMQqmVj6QzLcgTKazeYDRFDZYwXCyQ7YY7IABMjAMuFY4QmAGEIKYESAoNB3iB0IUACqk0RI4ZEIwASSg1lgajAexYAEFJWoYBkpotCgBfDVAA) link however does seem to be a repro case.  (Not that I like trailing commas.)

**Comment by Rich-Farmbrough** [comment]
> No repro:
> 
> **Prettier 1.19.1**
> [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADA2gVwA4BMCG8A+gG74BOAzgDQAEAuqiNSBNjAJbSXKgXkQA7gAUKCHinwkIHXMxAAjcvjABrODADK2FRygBzZDHKY4LABYwAtgBsA6uY7xKOsHE3inHEk4CeycEoeFj1KOHIYYWV9K3xkADN8GzCWACtKAA8AIWU1DU18KzgAGT04BKSUkHSMzT19GzgARUwIeArksxAdKnCA30KbeWxyPRg7WRhzZAAOAAYWEYgwu2VsAJG4MPIScpYAR1b4KLYJEHxKAFooODhcO-lyOEOOJ6j8GLikRM6WMKsOEYTF1KPVGi02uVvpUujB8AoJrgpsgAEwsYz4Dg2eoAYQgVliASg0D2IEwYQAKvCJD8qiRTABJKD3WCaMCjdgAQWZmhgvkaHTCAF8hUA)
> 
> ```shell
> --parser yaml
> ```
> 
> **Input:**
> 
> ```yaml
> `[update_vars, ]`
> ```
> 
> **Output:**
> 
> ```yaml
> `[update_vars, ]`
> ```

> No repro:
The playground link you give currently errors.
[This](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtArgBwCYEN4D6AbrgE4DOANAAQC6IlIEmMAltOcqGaRAO4AFMgk4pcRCK2wMQAI1K4wAazgwAypkWsoAc2QxS6OIzgBbWXGzZLAGVy70uHXABiEUqfxtdyELnQwEDIAFjCmADYA6sGs8OSaYHBqIrGsRLEAnr5g5JyM2uRwpDACCjqeyABmuOGFjABW5AAeAEIKyqpquKZwNtpwVTV1II1Nato64XAAiugQ8IO1xiCaFEW+Gd3hMpik2jCRUjDByAAcAAyMuxCFkQqYvrtwhaREA4wAjnPwpcyifuQALRQOCWSwyUhwL6sSGlJwVJDVJaMQqmVj6QzLcgTKazeYDRFDZYwXCyQ7YY7IABMjAMuFY4QmAGEIKYESAoNB3iB0IUACqk0RI4ZEIwASSg1lgajAexYAEFJWoYBkpotCgBfDVAA) link however does seem to be a repro case.  (Not that I like trailing commas.)
