### ISSUE TITLE
Unstable formatting of multi-line expression

### ISSUE THREAD

**Issue by robx** [prettier/prettier#7486]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VAdK6AEhFhkC6GQa4ZAvtUEhzQToZB6hkCuGQdYZAJhkAuEnQDwZBnBkBEGQQwZAVBkAknHAAs4AIwCWAOgBWAZyzosACgBmAVyhgY46EoAO4gCYAbcbJgAaHGGMBDWbNH24ASmBYcnr5-EqlMAE89OAgVHABbCEM1YzgAXgSAcghRaTgtRJwAMiyIqJi4STgADz0IACcYWTdI6Nii0oqqnDicAG0DEzNLazsHJ1k4AF0AbgBfD28vOGNB4Bw9AC89cskbe1lwgHNV8NsAazgAYTVzCHD9I1NzK3X+5xdxrDGlLDbEkQlEoat3bFQALRA4Eg0Fg8EQyFQoEKVA4QDcroB5hUAFhGALk9AN8+WAA4uVbHohOIwEg-lMvATDHAABK2eBQWw4JA4GDlNRwCxYSaknZGSDGCoAfUCwQZOAwIAAMgBJLGUgAqYvZUE5UxUWzAM2MvIF6k0IrFAEcoGpwgrld4VNAYABlIS2Cla8p6kAAdwJ8FNUFJniN4VEcHKDv5OrATpU4mKcEM-Nktophg9Zq8WzgMAAQhUKeUjhA+Y7GcHtLpRBn-W5E16vL4lABCGAE2SSPRqRaLerJmDZqBhrZKRKyOmHUSGRIuNw4coptTlT0qWyzOBPJWeitegButkd6uMxgAjC0cMXypnJLIjOkNW0AAw-awagBM+8Px9P9ovO9G5ZXVerW93kjMRrbtkuQ-ve-79jExjAZ+K6eEov47pIhrGgkcQAnuOS3tud5IT6qHoS40HLrBXrwRqiG2D61YJOhOAAD50Vhxg4ZRxrUWhO6ETkMGwUoOBKGR24UXhNGcexgnMZIrHhPhnGEQx-EALI0kIUmiLIEnCcaAK-ixPouOxck4C4PGkiSJEWROMBTp6Ak1ghkjMuIc45A50nsQRDH2WBTkuVkulSVRomjjgAD8TL1khlGyA6Ip1mYjnlM5mo5hUjymVMEzERZ46TtOOCAcYIyfllpWjsVUAgBYIAQHohZQLIyCgBu5QQM6AAKG4II1KC2KuEBGFVICiLiYCHNaei2GA4hQFsyDMqy1VCDA4TGAA6m6cCyJN6pWt14jaKuB0BMg4AOENM2DJU7W4lsezILO87VXIxSpqN41WrY4RwOKM1wA9c6DM9sjFFaM1bLEACKagQPAANPSAk3lFdp1OH6xhDSsM0wGtRh1sgAAcl7VSsECDGtuJ6KdKxbf6q7-dV+ow-AN21T1ID2ACUBwJGkZDROTPiBON22Hdtjw0DICDOE4jzSybJS+DUPM-9SCPZLMC2KIuOGPjSB3tVzK2OIpizdm4T3SgUDQAzICnHAspaz1C0K6urKSlAFKwFaYBJXVACCntWoEsQS3AYxjEAA)
```sh
--parser babel
--use-tabs
```

**Input:**
```jsx
//
// パズル固有スクリプト部 へびいちご版 hebi.js
//
(function(pidlist, classbase){
        if(typeof module==='object' && module.exports){module.exports = [pidlist, classbase];}
        else{ pzpr.classmgr.makeCustom(pidlist, classbase);}
}(
['hebi'], {
//---------------------------------------------------------
// 画像表示系
Graphic:{
        hideHatena : true,

        gridcolor_type : "LIGHT",

        fgcellcolor_func : "qnum",
        fontShadecolor : "white",
        numbercolor_func : "fixed_shaded",

        getBorderColor : function(border){
                if(!this.puzzle.getConfig('snakebd')){ return false;}

                var cell1 = border.sidecell[0], cell2 = border.sidecell[1];
                if(!cell1.isnull && !cell2.isnull &&
                   (cell1.qnum===-1 && cell2.qnum===-1) &&
                   (cell1.anum!==-1 || cell2.anum!==-1) &&
                   ( ((cell1.anum===-1)!==(cell2.anum===-1)) || (Math.abs(cell1.anum-cell2.anum)!==1)) )
                {
                        return (((!cell1.trial&&cell1.anum!==-1)||(!cell2.trial&&cell2.anum!==-1)) ? this.qanscolor : this.trialcolor);
                }
                return null;
        }
}
}));

```

**Output:**
```jsx
//
// パズル固有スクリプト部 へびいちご版 hebi.js
//
(function(pidlist, classbase) {
	if (typeof module === "object" && module.exports) {
		module.exports = [pidlist, classbase];
	} else {
		pzpr.classmgr.makeCustom(pidlist, classbase);
	}
})(["hebi"], {
	//---------------------------------------------------------
	// 画像表示系
	Graphic: {
		hideHatena: true,

		gridcolor_type: "LIGHT",

		fgcellcolor_func: "qnum",
		fontShadecolor: "white",
		numbercolor_func: "fixed_shaded",

		getBorderColor: function(border) {
			if (!this.puzzle.getConfig("snakebd")) {
				return false;
			}

			var cell1 = border.sidecell[0],
				cell2 = border.sidecell[1];
			if (
				!cell1.isnull &&
				!cell2.isnull &&
				cell1.qnum === -1 && cell2.qnum === -1 &&
				(cell1.anum !== -1 || cell2.anum !== -1) &&
				((cell1.anum === -1) !== (cell2.anum === -1) ||
					Math.abs(cell1.anum - cell2.anum) !== 1)
			) {
				return (!cell1.trial && cell1.anum !== -1) ||
					(!cell2.trial && cell2.anum !== -1)
					? this.qanscolor
					: this.trialcolor;
			}
			return null;
		}
	}
});

```

**Iterated output:** (extra line-break in long condition)
```jsx
//
// パズル固有スクリプト部 へびいちご版 hebi.js
//
(function(pidlist, classbase) {
	if (typeof module === "object" && module.exports) {
		module.exports = [pidlist, classbase];
	} else {
		pzpr.classmgr.makeCustom(pidlist, classbase);
	}
})(["hebi"], {
	//---------------------------------------------------------
	// 画像表示系
	Graphic: {
		hideHatena: true,

		gridcolor_type: "LIGHT",

		fgcellcolor_func: "qnum",
		fontShadecolor: "white",
		numbercolor_func: "fixed_shaded",

		getBorderColor: function(border) {
			if (!this.puzzle.getConfig("snakebd")) {
				return false;
			}

			var cell1 = border.sidecell[0],
				cell2 = border.sidecell[1];
			if (
				!cell1.isnull &&
				!cell2.isnull &&
				cell1.qnum === -1 &&
				cell2.qnum === -1 &&
				(cell1.anum !== -1 || cell2.anum !== -1) &&
				((cell1.anum === -1) !== (cell2.anum === -1) ||
					Math.abs(cell1.anum - cell2.anum) !== 1)
			) {
				return (!cell1.trial && cell1.anum !== -1) ||
					(!cell2.trial && cell2.anum !== -1)
					? this.qanscolor
					: this.trialcolor;
			}
			return null;
		}
	}
});

```

**Expected behavior:**
No change between first and second run.

**Comment by evilebottnawi** [comment]
Thanks for the issue

**Comment by thorn0** [comment]
This has been fixed by https://github.com/prettier/prettier/pull/7026, but not yet released. Try it on the [playground for the upcoming release](https://deploy-preview-6773--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAFgBQBGEATgCZwUCUwAOlPq2+x-jqsQIRhwANoICMAOhwBnKOmH4AZPPz8hggEwTpswQvnNOBzsQHDxARxkBbALy2AtCN34T6sRfQ37Iurv2H-+Maq4gCGVrxe+AA+Uc6qGmEeEdYOPop+AQbEgUGmYomeKd7Jua4FtkV0PjGBALIhMIT5pJKloVZ2LglWdMnePnQZmaxMLMOZFHAw6BQsxPMqeTAUOCGCii7tSV50MXxdYsur6-IHBcmpPgD8+I1SbmGSkIKU+Ei3hPdHa8+UdADcQ2GAF8gRMpjMWDJhICxpxQVBmCAADQgCAAB1w0EkyFAIQoFAgAHcAAr4hA4lBrIkhACeONRpAoITAAGspgBldEsnBQADmyGW6DgqMIMEsggA6p94JJuQIORScLgAG7K2nIcCSBkgXmSWgwEnMvmWELIVBrfWogBWkgAHgAhZlszkhSxwAAyvLg5stIpAtrtHN5fMEcAAiugIPBfYIrSBuRR9RRNaQQqQhCiEytYJKcFRGsgABwABlR6MJ+slzPRmorcGTKp9qLMUfgRoxlJAIUkdigcDgNCoWcmrZwkyNIRNZqQFrj-v1lhwgoowtRkhDYcj0Z9s79qJg6bzBcIyDUB+ZOEEIYAwhBLKbNQ2AKxZ9D6gAq6cpc-jKuFACSUA0LAHJgCsmIAILARyMC0mGsb6sCwJAA).

**Comment by robx** [comment]
Oh, great! Apologies for not checking the development version. Looking forward to the new release then.
