### ISSUE TITLE
Remove parentheses of sequence expressions breaks code

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7490]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt8AKARgBo8AmASgG4QGQIMYBLaAGdkoUtmwQA7gAVxCESlIA3CPwJcQAI2ykwAazgwAyhj38oAc2Qxs5ONwAWMALaUA6o-7whZsHGMFb35lbwBPZHAhEW4LIThcGV1LF1JkMkp47gArITQAIV0DI2NSFzgAGQs4dNJMhxBctGMLS0o4AEVyCHha+u4zbHjsSK1SLThKTQxsCxh3dRhHZAAOAAYByXj3XQxImbhh5RruAEdu+CTeRRBSIQBaKDg4Ig1ubDhz-g+k0hS0pAZLIgeIufg2OwNIStdpdHo1QF1YEwcYLAhLZDMbi2Uj8SitADCEBcqUiUGgJxA5HiABVxoogQ1lPYAJJQIiwYxgWZ8ACC7OMMDC7T68QAvmKgA)
```sh
--parser babel
```

**Input:**
```jsx
export default (1, 2);
```

**Output:**
```jsx
export default 1, 2;

```

**Second Output:**
```jsx
SyntaxError: Unexpected token, expected ";" (1:17)
> 1 | export default 1, 2;
    |                 ^
  2 | 
```

**Expected behavior:**

A case found in #7470

**Comment by armano2** [comment]
note: this issue is present in jest and typescript, and its related to https://github.com/estree/estree/issues/193

**Comment by evilebottnawi** [comment]
Fixed in next

**Comment by thorn0** [comment]
Are issues not closed automatically because PRs target `next`, not `master`, or is GitHub broken?

**Comment by evilebottnawi** [comment]
Honestly, I do not know, maybe this really only works for the master, need to write in support

**Comment by thorn0** [comment]
I wrote yesterday, No answer so far.
