### ISSUE TITLE
Add a redirect from jlongster.github.io/prettier

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#751]
I used this html to do so https://github.com/vjeux/prettier-browser/blob/master/index.html

**Comment by jlongster** [comment]
How do I do this while keeping the redirect from the jlongster/prettier project to here?

**Comment by vjeux** [comment]
Hmmm, good question, I have no idea :(

**Comment by jlongster** [comment]
Let me think about this a little bit. I might be able to create a page for my profile but have a `prettier` subfolder that does the redirect. I run into this problem all the time when moving repos...

**Comment by jlongster** [comment]
Unfortunately it doesn't work :( I create a user page for my profile and then put a `prettier` folder underneath it: https://github.com/jlongster/jlongster.github.io/tree/master/prettier. Going to `https://jlongster.github.io/` works, but `https://jlongster.github.io/prettier` doesn't. I'm guessing this is a problem with github's routing mechanism and it sees some sort of "redirect" repo there.

I don't think we can solve this, unfortunately. I think it's going to be easiest to update the links in the issues as we find broken links and tell people to manually redirect. It's unfortunate but I view most of that content as transient.

**Comment by vjeux** [comment]
cc @tberman. Do you have any if it is possible to put a redirect on the old github page now that the repo has been moved? If not, not a big deal but there may be a way :)

**Comment by jlongster** [comment]
Oh wait, it just started working. The top-level page had updated so I assumed it was up-to-date. I guess for some reason it took a while for the prettier folder to update.

So yay, it's working I think!

**Comment by vjeux** [comment]
Yay, thanks!
