### ISSUE TITLE
Wrong formatting on flow shorthand annotation comment with other comments

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7510]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKADAAgPQCpOQC2hCMmu2OuSmUAroQEZwBO52AlCADQgQAOMAJbQAzslABDFiwgB3AArSE4lJIBuEIQBMeIRi0lgA1nBgBlfkaFQA5shgs6cXgAsYhADYB1V0PiiVmBw5ir+Qur+AJ7I4KLivDairDAKhraEksgAZpKeybwAVqIAHgBChiZm5pIkADI2cDl5BSDFJeY2tp5wAIp0EPDN+S4gVizJLLHZnvJ6-Cw2MN46MK7IABzovAsQyd6G-LELcJPqTbwAjgPwaQKqIJKiALRQcHDaH3oscNdCP2lJBkskhciNeMlCEIHE5RqIuj1+oMmqCWqMYJJGCttGtkAAmXiOSRCTxdADCEGIIJAUGgFxAdGSABVMaowa11M4AJJQT6wcxgRaCACCvPMMCiPWGyQAvjKgA)
```sh
--parser flow
```

**Input:**
```jsx
(0 /* comment */ /*: number */)
```

**Output:**
```jsx
(0 /*: /* comment */ number */);

```

**Second Output:**
```jsx
SyntaxError: Unexpected token `*/`. Did you mean `*-/`? (1:19)
> 1 | (0 /*: /* comment */ number */);
    |                   ^^
  2 | 
```

Flow's [playground](https://flow.org/try/#0BQBgBA9AVGDGD2BbRBTAdgFzFCkoC4w0BXRAIxQCdsIBKIA)

**Comment by thorn0** [comment]
Fixed by #13687
