### ISSUE TITLE
How to disable added leading/trailing spaces in HTML inline "interpolation" blocks.

### ISSUE THREAD

**Issue by chasemaier** [prettier/prettier#7513]
I'm using Meteor's Blaze/SpaceBars within HTML files.

The Prettier formatting within VSCode seems to be adding white space to the inline interpolation blocks and I can't seem to find a relevant setting to remove this behavior.

`<p>You've pressed the button {{counter}} times.</p>`

becomes

`<p>You've pressed the button {{ counter }} times.</p>`

I'd prefer the inverse, if possible.

I tried to track down where it is getting added starting from https://github.com/prettier/prettier/blob/master/src/language-html/printer-html.js#L292-L297 but I couldn't pin down where the spaces were added to see if there was some relevant setting.

**Comment by kachkaev** [comment]
👋 @chasemaier, please provide a [Playground](https://prettier.io/playground/) example and use an [issue template](https://github.com/prettier/prettier/tree/master/.github/ISSUE_TEMPLATE). Also this might be worth a read: https://prettier.io/docs/en/option-philosophy.html
