### ISSUE TITLE
Unstable single-line comments in destructured function argument

### ISSUE THREAD

**Issue by smably** [prettier/prettier#7518]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAhAThAawUwF5MAlOAQzBgDoAzCXAdytwBNKGAKH4ADpQBMMAAsAlgBsOuBABohIgPTLMARiUxVmAExaYEmFLiLhMSRw4KtOgMxCAvvMxyGASlIA+TDy0AeDgkAN1c4BhJgN0cvLRFgcWlZBEcA5SDg2Kh3dxB5EAgAB0N0ZFB2fBYABXYENGQQKmCICQ48kAAjXBoiGABlQpoJKABzZBhcAFdTEDEYAFspAHVJeDRBsDg+uqMQowBPBrA0evzhtDhcGCrukfmqZAYqKQv8gCs0AA88Hrh+qnmcAAMsM4I9nq8QB9Pn1hiMTABFSYQeDgl4zQa4C64BodKgdfZSaDtQq4YYwJatCzIAAcAAZ8qSIBclt1Cg1SXBscEwfkAI7I+A3Ir1FBUNAAWigcDg1ja+TkAokchuVDuDyQT3R+Qu8wk4ymMzQcMRgrBmohMxg+MpHGpSF0+QmVGkcIAwhB5vcGlBoLyQJMLgAVfGirWQ4LTACSUGssD6YDJxQAgrG+jBCebw3BHI4gA)
```sh
--parser babylon
```

**Input:**
```jsx
const Broken = React.forwardRef(({
	children,
	// 1
	// 2
	title,
	hidden,
	// 3
}, ref) => (
	<div ref={ref}>
		{children}
	</div>
))
```

**Output:**
```jsx
const Broken = React.forwardRef(({ children, // 1
  // 2
  title, hidden }, ref) => <div ref={ref
  // 3
    }>{children}</div>);

```

**Second output:**
```jsx
const Broken = React.forwardRef(({ children, // 2 // 1
  title, hidden }, ref) => (
  <div
    ref={
      ref
      // 3
    }
  >
    {children}
  </div>
));
```

**Third output:**
```jsx
const Broken = React.forwardRef(({ children, title, hidden }, ref) => ( // 2 // 1
  <div
    ref={
      ref
      // 3
    }
  >
    {children}
  </div>
));
```

**Fourth output:**
```jsx
const Broken = React.forwardRef((
  { children, title, hidden },
  ref // 2 // 1
) => (
  <div
    ref={
      ref
      // 3
    }
  >
    {children}
  </div>
));
```

**Expected behavior:**
```jsx
const Broken = React.forwardRef(({
  children,
  // 1
  // 2
  title,
  hidden
  // 3
}, ref) => (
  <div ref={ref}>{children}</div>
));
```

**Comment by armano2** [comment]
note: flow and typescript parsers are affected to

**Comment by sosukesuzuki** [comment]
a minimal example to reproduce:
[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUngB0oAEBARgIYBe+RA9NQQEz4C+AlAQLwB8BAPACYBLAG7VOLfCAA0ICAAcYA6AGdkoUgCd1EAO4AFDQhUpSQiAL5SQxdaTABrODADKs2wKgBzZDHUBXONIAFjAAtgA2AOqBAvBKrmBwToYxwjEAnsjgSirS7kpw6jC6Nh4hpMiopGH50gBWSgAeAEI29o5OpCFwADLucBVVNSD1DU7uHmFwAIq+EPAD1QEgrur56plkxHBhlrLq7jAR5jCByAAcAAzSexD5ETaymXtwa0L90gCOs-DFckYgpCUAFooHA4HxwZZ1HAvgJocVSKVykhKotpPkQgJvH4lkpxpMZnN+ijBksYKRiEc+CdkPRpD5SAIwuMAMIQEJlTJQaDvEC+fIAFQpRlRQyE-gAklAIbAnGB9vIAILSpwwNKTBb5JhMIA)
**Input**
```js
foo(({
  baz
  // 2
}) => <div/>)
```
**Output**
```js
foo(({ baz }) => <div />);
  // 2
```
This bug happens with only returns JSX.

**Comment by armano2** [comment]
@sosukesuzuki it can be reproduced with other array and object.

Input
```js
foo(({
  baz
  // 2
}) => [])
```
```js
foo(({
  baz
  // 2
}) => ({}))
```

**Output**
```js
foo(({ baz }) => []);
  // 2
```
```js
foo(({ baz }) => ({}));
  // 2
```

**Comment by sosukesuzuki** [comment]
@armano2 I missed it, thanks!
