### ISSUE TITLE
Surprising prettier --check behaviour 

### ISSUE THREAD

**Issue by AngusMorton** [prettier/prettier#7519]
`prettier --check` passes even though code changes will be made by `prettier --write`.

The following code passes prettier --check, even though it's modified when prettier --write is run next.
```jsx
       {request ? (
            <DynamicSchedules
              scheduleList={
                schedulesResponse
                  ? createScheduleList(schedulesResponse)
                  : undefined}/>
          ) : (
            <StaticSchedules cells={viewModel.timelineCells} />
          )}
```

When --write is run, the code changes to the following, even though --check passed.
```jsx
          {request ? (
            <DynamicSchedules
              scheduleList={
                schedulesResponse
                  ? createScheduleList(schedulesResponse)
                  : undefined
              }
            />
          ) : (
            <StaticSchedules cells={viewModel.timelineCells} />
          )}
```

I expect `prettier --check` to fail if code changes will occur.

**Environment**
Prettier 1.19.1
```sh
prettier src/**/*.{ts,tsx,json,js} --check
```
prettier.rc
```json
{
  "trailingComma": "es5",
  "semi": false,
  "singleQuote": true,
  "endOfLine": "lf",
  "arrowParens": "always",
  "useTabs": false,
  "bracketSpacing": true,
  "printWidth": 80
}
```

**Comment by fisker** [comment]
It can't be true, we should the same command on our codebase

https://github.com/prettier/prettier/blob/e2e534df30f09985151718267d84cb6c18306606/package.json#L126

**Comment by AngusMorton** [comment]
Thanks! That helped identify the issue. 

We were missing quotes in our script. e.g.  `"format:check": "prettier src/**/*.{ts,tsx,json,js} --check"`
It turns out this was only checking files in the first directory under `src`!

Then we changed it to: `"format:check": "prettier \"src/**/*.{ts,tsx,json,js}\" --check"`, now it finds all files correctly.

We didn't notice that it wasn't checking all of the components.

**Comment by thorn0** [comment]
If you don't use quotes, then your shell expands the patterns, not Prettier. And not every shell understands `**`,
