### ISSUE TITLE
Don't limit the length of require lines.

### ISSUE THREAD

**Issue by conartist6** [prettier/prettier#752]
lines such as

`const MyReallyExtrememlyLongModuleName = require('MyReallyExtrememlyLongModuleName');`

should not be split apart. Once split, module system parsers will fail to understand the dependency.

**Comment by vjeux** [comment]
> module system parsers will fail to understand the dependency

Can you tell us which require system you are working with? The ones I know have pretty permissive regarding to whitespace and should cover this case.

**Comment by conartist6** [comment]
Facebook's...

**Comment by vjeux** [comment]
I opened an internal task about it, we need to fix our stuff rather than hardcoding something inside of prettier :)
