### ISSUE TITLE
Long strings as function arguments sometimes produce output that violates printWidth

### ISSUE THREAD

**Issue by kaiyoma** [prettier/prettier#7532]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoByAMwghIBoACIgSloF4A+W4AHSlttxlIALONjh8MtAIa0ANtADms3FDEQyteAA8YGwZJ24JAKwCuGHTGG088wTpkJ5ljRA035IqbXwnFy2gAOojAwuCI09ExsHNy8vAD08bSorhgQALZwlsrysbQAvgwA3NyFJVAg1CAQAaHQGMigktjYEADuAArNCA0okgBuELiolSD42JJgANZZAMoBkznIMNgmcFV26TIA6oL8mAtgcLM9-Lj9-ACeyOAYDVXKGCIwHRPy6ZLIZJIyT1VGGE0ACEJtM5pJMgAZZRwL4-P4gAGaWY5BwARRMEHgcN+6xAC2wT2wN3wkkIMlGQWUMG2w0syAAjAAGJlVIIQJ7bCYBG5BTAifqwqoAR0x8FeNV6IEkGAAtCo4OgRlVRKLcKJXpJ3p8kN9cVUnulcMtVniMKi4BisbDdfC8TAybTUPSkAAmKorSS4GQ5ADCGQ+Nyg0CFIDMcAAKmTenqEf01gBJKDoWCzHC4WoAQWTsxglwcOKe+XyQA)
```sh
--parser babel
--print-width 100
```

**Input:**
```jsx
describe('foo', () => {
  it('here is a long line of text that is just the right length to trigger a bug in prettier', () => {
    // do something
  });
});

```

**Output:**
```jsx
describe("foo", () => {
  it("here is a long line of text that is just the right length to trigger a bug in prettier", () => {
    // do something
  });
});

```

**Expected behavior:**
I would expect the two arguments of the `it(...)` call to be moved to separate lines, which would satisfy the `printWidth` requirement:

```jsx
describe("foo", () => {
  it(
    "here is a long line of text that is just the right length to trigger a bug in prettier",
    () => {
      // do something
    },
  ),
});

```

**Comment by evilebottnawi** [comment]
It is expected for better readability, because it is test functions (https://github.com/prettier/prettier/blob/master/src/language-js/utils.js#L306), sorry, we don't want to change current output

**Comment by kaiyoma** [comment]
@evilebottnawi I have seen this problem with non-test code as well.

**Comment by thorn0** [comment]
@kaiyoma Open issues about those. But this specific behavior with `it`, `describe`, etc is a feature, not a problem. See https://prettier.io/docs/en/rationale.html#testing-functions
