### ISSUE TITLE
Unnecessary new lines injected by typescript parser.

### ISSUE THREAD

**Issue by whitneyit** [prettier/prettier#7542]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDEII8BePAMxwHcBDbAEwCU5aAKbjbCBiJI85CAAUBQgDR5sXEZ1oAeABIAVALIAZAKIAbOAFsEMAHwBKEQCkAygA0AdAeOnqZvMAA6UPHLgwAK7YvsqsAJYAbngA9GYA3D4AvhaJUD7oWLgE0CR4AEIs1HSMLBxcvPyCwgUsktWy8rSKXGpaeoYmsJY2Ds6dbgA+eFCB+vrunj5+8kEheGFRsQnJqT4+gURw2ESORkwYvJvbIgCqW9hWeOfbk96+-nO+x9hpKSDSIIIw4bnIoCwBAxxCwEERkCAmJEIOFWB8QAAjbBMMAAawCtgwKPCUAA5sgYNhAnBPgALGBGfQAdVJ4XgRCxYDgtjBdKidIAnhCwERwZ8cRcYJImLj9shaEx9FtPgArIhofLItEYpgmbQ4uDiyXSkBytC2HG4wwARUCEHgWqlJJAWJ22whMA5GDgRDA2HCGBg8P4OJgVNhMFJyAAjAAmAAMnyqWypyIwEP4Lu2kU1nwAjmb4PUhBCmEQALRQOBwVgl+HyDPheTC0VMS06rZGcIEonWoiGk2ZzVICVWz4wJgI-2sQPIUP95HhfSGgDCECMYpQUGgqZAx3Ug-BPe11sixIAklBS7BbG6PTAAIJH2yOwz1uBJJJAA)
```sh
--parser typescript
--print-width 120
```

**Input:**
```tsx
export const Foo = forwardRef((props: FooProps, ref: Ref<HTMLElement>): JSX.Element => {
  return <div />;
});

export const Bar = forwardRef((props: BarProps, ref: Ref<HTMLElement>): JSX.Element | null => {
  return <div />;
});

users.map((user: User): User => {
  return user;
})
```

**Output:**
```tsx
export const Foo = forwardRef(
  (props: FooProps, ref: Ref<HTMLElement>): JSX.Element => {
    return <div />;
  }
);

export const Bar = forwardRef((props: BarProps, ref: Ref<HTMLElement>): JSX.Element | null => {
  return <div />;
});

users.map(
  (user: User): User => {
    return user;
  }
);

```

**Expected behavior:**
Prettier leaves the code as is.

This formatting issue only occurs when using the [typescript](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDEII8BePAMxwHcBDbAEwCU5aAKbjbCBiJI85CAAUBQgDR5sXEZ1oAeABIAVALIAZAKIAbOAFsEMAHwBKEQCkAygA0AdAeOnqZvMAA6UPHLgwAK7YvsqsAJYAbngA9GYA3D4AvhaJUD7oWLgE0CR4AEIs1HSMLBxcvPyCwgUsktWy8rSKXGpaeoYmsJY2Ds6dbgA+eFCB+vrunj5+8kEheGFRsQnJqT4+gURw2ESORkwYvJvbIgCqW9hWeOfbk96+-nO+x9hpKSDSIIIw4bnIoCwBAxxCwEERkCAmJEIOFWB8QAAjbBMMAAawCtgwKPCUAA5sgYNhAnBPgALGBGfQAdVJ4XgRCxYDgtjBdKidIAnhCwERwZ8cRcYJImLj9shaEx9FtPgArIhofLItEYpgmbQ4uDiyXSkBytC2HG4wwARUCEHgWqlJJAWJ22whMA5GDgRDA2HCGBg8P4OJgVNhMFJyAAjAAmAAMnyqWypyIwEP4Lu2kU1nwAjmb4PUhBCmEQALRQOBwVgl+HyDPheTC0VMS06rZGcIEonWoiGk2ZzVICVWz4wJgI-2sQPIUP95HhfSGgDCECMYpQUGgqZAx3Ug-BPe11sixIAklBS7BbG6PTAAIJH2yOwz1uBJJJAA) parser. If you switch over to the [babel](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDEII8BePAMxwHcBDbAEwCU5aAKbjbCBiJI85CAAUBQgDR5sXEZ1oAeABIAVALIAZAKIAbOAFsEMAHwBKEQCkAygA0AdAeOnqZvMAA6UPHLgwAK7YvsqsAJYAbngA9GYA3D4AvhaJUD7oWLgE0CR4AEIs1HSMLBxcvPyCwgUsktWy8rSKXGpaeoYmsJY2Ds6dbgA+eFCB+vrunj5+8kEheGFRsQnJqT4+gURw2ESORkwYvJvbIgCqW9hWeOfbk96+-nO+x9hpKSDSIIIw4bnIoCwBAxxCwEERkCAmJEIOFWB8QAAjbBMMAAawCtgwKPCUAA5sgYNhAnBPgALGBGfQAdVJ4XgRCxYDgtjBdKidIAnhCwERwZ8cRcYJImLj9shaEx9FtPgArIhofLItEYpgmbQ4uDiyXSkBytC2HG4wwARUCEHgWqlJJAWJ22whCKYCLg+nh-BxMCpsJgpOQAEYAEwABk+VS2VORGAh-DgF0ims+AEczfB6kIIUwiABaKBwOCsfPw+TJ8LyYWipiWnVbIzhAlE61EQ0mlOapASq2fGBOr2sH3IANd5HhfSGgDCECMYpQUGgCZAx3UTvB7e11sixIAklAC7BbGBsOEMDAAII72wwDmGKtwJJJIA) parser, the code remains untouched.

The extra lines that prettier injects seem overkill, especially for the `users.map` example.

It's interesting though how that functions that have a union return type, don't get rewritten to a new line.

**Comment by sosukesuzuki** [comment]
I'm not sure if this is a bug. But, it is strange that there is difference between normal return type and union return type.

**Comment by whitneyit** [comment]
If this is considered a bug, I would be happy to work on a fix

**Comment by armano2** [comment]
@whitneyit are you still interested in picking this one up, if no i can take it as its annoying me in my codebase

**Comment by whitneyit** [comment]
I'm keen to work on it as well. I'm not sure if it is deemed a bug or not :man_shrugging:

**Comment by whitneyit** [comment]
@armano2, if you want to take a look at as well, I'm not going to say no lol
