### ISSUE TITLE
Anyone working on a prettier extension for nova?

### ISSUE THREAD

**Issue by zolon4** [prettier/prettier#7569]
I don't want to build it if anyone is already working on it.

**Comment by kachkaev** [comment]
Hi @zolon4, please see https://github.com/prettier/prettier/issues/7531. This repo is about Prettier Core, all new issues are expected follow one of the [templates](https://github.com/prettier/prettier/tree/master/.github/ISSUE_TEMPLATE).

**Comment by zolon4** [comment]
@kachkaev Thank you!

**Comment by evilebottnawi** [comment]
Please do not use prettier bug tracker for questions not related to core, you can use reddit/stackoverflow/many other services for that, thank you
