### ISSUE TITLE
Prettier ignores --print-width for object literals with long name and value

### ISSUE THREAD

**Issue by tejohans** [prettier/prettier#7572]
**Prettier 1.19.1**

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEWC8ngA6UmmBIAFnADZURlKYDuEATlQCYAUAlADREkA5DHIBLNAFpxEgIYSAbnBYBPCbSgBzCQGs4qmVHYSRcWWjSiNUALYIYEtOQgBXDhIBGpgA7P70Y5QSUHAAHvZUosGCDKwAsjLKngCSAILWseLOhkoYBuyRGimGSQASMooAynAwFRC2IgUA6izQGklQscoAwtAAZpY8-MSk4AYOdXDQpqFeVDKR9NhiaDxEAL4A3CC8IBBeMKLoyKAyLC2MAAqnCGjIIOUQouzbIO4sMmC6NV4fBcgwLGccB25Bg1iojTE8DQPzAcCqUAsB3kohgyjuYHML0iaCUMAu7w01hkyF6MiouJ2ACs0CEAELvT7VCoyWwAGUicFJ5MpIBpIQqBSocAAis4IPB-oDgSAfixcSw7mivHA0GAWKJ9i8vBrYI0niJkABGABMAAYdjqILjmjIvHcdaqlIoXgBHcXwAl7W4oGSSYJwdiBl4sODu0ShgkyIkkpBkiky3HWURSoE7CyaYViiVcpAAtMgGAydz69iGpAmnYA+YRTQ9azEu5QKYvZy4gAqxZ98d58iB7SDsAq6s1MCK7AqaOF3ITO3emjgAFFDMbzXODBp4UWWDBkGa1msgA)

`--parser typescript`

**Input:**
```
const t = {
  "hello": world(),
  'this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line': 
  	orMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig(),
  "can-someone-explain": this()
};
```

**Output**
```
const t = {
  hello: world(),
  'this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line': orMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig(),
  'can-someone-explain': this()
};
```

**Expected behaviour:**
```
const t = {
  hello: world(),
  'this-is-a-very-long-key-and-the-assignment-should-be-put-on-the-next-line':
    orMaybeIAmMisunderstandingAndIHaveSetSomethingWrongInMyConfig(),
  'can-someone-explain': this()
};
```

With the --print-width set to 120 characters, I am expecting the name and value to be split into separate lines, given that neither name nor value exceeds the limit of 120 characters.

**Comment by evilebottnawi** [comment]
It is expected, and we don't split it the name and value for readability purpose, sorry we don't want change the current behavior, you can set `20` width and see what we still keep them on one line

**Comment by j-f1** [comment]
@evilebottnawi What’s the context for this? I thought it used to behave the way OP expected?

**Comment by thorn0** [comment]
It never behaved that way. It's a manifestation of #2482.
