### ISSUE TITLE
add prettier-eslint to prettier org

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier#758]
@jlongster and I talked about this on twitter and he said it's something y'all would consider. The use case for [prettier-eslint](https://github.com/kentcdodds/prettier-eslint) is for people who want to benefit from the advanced formatting capabilities in addition to the configuration/formatting of eslint. This is not 100% stylistic, but most of the time it is. Situations for that include preference differences and/or challenge convincing a team of developers to adopt prettier wholesale. Also, ESlint is capable of auto-formatting/fixing more than prettier, so even if you have the same style as prettier (or disable style roles altogether) this puts the two automatic fix/formatting together in a single workflow.

I think it'd be valuable to include this (and potentially the associated CLI and Atom plugin) in the org.

**Comment by vjeux** [comment]
I think that it's actually going to be the main way people integrate prettier into their stack, so it makes sense to me to include inside of the prettier org if you want to!

**Comment by jlongster** [comment]
I'm fine with it too! My only concern is the naming of all these projects. We have prettier-eslint, eslint-config-prettier, and eslint-plugin-prettier, in addition to any editor-specific integrations (prettier-eslint-atom, prettier-atom). Maybe this is just part of this kind of work and combining all the tooling is going to make a lot of similar names.

It would be good at least to have a list of all these projects and a short explanation of what each does.

But yeah, let's get it in here. How do we do that? Do we need to create teams and such and add @kentcdodds to one of them so he can move it here?

**Comment by kentcdodds** [comment]
I agree the use cases should be spelled out well. A list of them all together with short use case explications would be good. Then each project should do a good job describing its use case in its own documentation, and probably reference the other packages too

**Comment by lydell** [comment]
(Note that ESLint requires a certain naming convention for its shareable configs and plugins: `eslint-config-foo` and `eslint-plugin-foo`.)

**Comment by kentcdodds** [comment]
@lydell, I'm aware of that. `prettier-eslint` is neither a config nor a plugin.

**Comment by lydell** [comment]
@kentcdodds My comment was more directed at @jlongster :)

**Comment by jlongster** [comment]
Thanks!

Just gotta figure out all the logistics. Sorry I haven't had a block of time to figure this out yet. I may be able to research that later today (if any of you have recommendations for how to setup teams, etc, I'm all ears!)

**Comment by not-an-aardvark** [comment]
By the way, I can also transfer `eslint-plugin-prettier` to the `prettier` org -- just let me know when all the logistics are figured out.

**Comment by kentcdodds** [comment]
I think teams can be challenging to manage and you can simply as contributors on specific repositories within and organization. So once I transfer prettier-eslint over, I believe you just need to add me as a contributor with admin access and I can continue to manage contributors as in doing now. Sound good?

**Comment by jlongster** [comment]
We can try that, I will make sure this happens today. I thought there were some things that admin contributors can't do, and I'd like to give you full control over the repo. But I guess I we can try it and see if that works.

@kentcdodds Want to go ahead and start the transfer? I know you're merging with prettier-atom, which repo are you all merging on?

**Comment by kentcdodds** [comment]
Here's what I got when I tried. Looks like I need to be on the org first.

<img width="419" alt="screen shot 2017-02-27 at 10 07 37 am" src="https://cloud.githubusercontent.com/assets/1500684/23371215/953e2962-fcd4-11e6-8489-d70373dde937.png">

> I know you're merging with prettier-atom, which repo are you all merging on?

@robwise can speak to that more. He's going to be taking over the atom plugin. I'm thinking it'd be best for us to just converge on `prettier-atom` and I'll deprecate my old package as soon as it supports `prettier-eslint`.

**Comment by robwise** [comment]
@jlongster @kentcdodds 

Just to be clear, there are two things, `prettier-eslint` and `prettier-eslint-atom`. I'm thinking we should merge `prettier-eslint-atom` into the `prettier-atom` repo, which I'm currently helping maintain. Once we've done that, we can deprecate `prettier-eslint-atom` and have all users migrate over to `prettier-atom`. This way, if you're an atom user, there's one package to worry about regardless if you use eslint or not and it's simple both for the users and the maintainers.

I've gone ahead and already merged the `prettier-eslint-atom` code into the `prettier-atom` repo in a local branch and am most of the way done—I just need to implement some Jest testing. Then I was hoping @jlongster could transfer ownership of that repo so that I could manage things like CI and other integrations and I would be held responsible for maintaining it (fixing bugs, reviewing PRs, organizing and answering issues).

**Comment by jlongster** [comment]
@kentcdodds @robwise Just added both of you to the org. You should be able to create repos, which I assume means you can transfer repos in as well. Let me know if it doesn't work!

**Comment by kentcdodds** [comment]
Moved. I'll move the CLI too, thanks!

**Comment by jlongster** [comment]
Awesome, closing!

**Comment by kentcdodds** [comment]
Any chance I could get admin rights on those two repos? There's still not a lot of activity from the perspective of people reviewing PRs and I'm unable to push to `master` (it's protected) or merge PRs without another reviewer. I'd like to be able to have more control until there's more contribution activity.

**Comment by kentcdodds** [comment]
For example, I couldn't push this to master and I can't merge this: https://github.com/prettier/prettier-eslint-cli/pull/33

**Comment by jlongster** [comment]
@kentcdodds done, let me know if there's anything else blocking you. I'm happy to add you to anything.

**Comment by lydell** [comment]
@jlongster If you do the same things you did to @kentcdodds to me I could transfer eslint-config-prettier :)

**Comment by jlongster** [comment]
@lydell of course! I'll add you now

**Comment by robwise** [comment]
@jlongster I have a PR open with the integration (just need to do some manual acceptance testing). Any word on doing the same stuff for that repo so that I can add CI/DependenciesAutomation/CodeCoverage etc.?

**Comment by not-an-aardvark** [comment]
Would it be useful if I transferred `eslint-plugin-prettier` to the `prettier` organization?

**Comment by lydell** [comment]
@not-an-aardvark I think so, at least! 👍
