### ISSUE TITLE
`--ignore-path` not respected when prettier executes in a subdirectory

### ISSUE THREAD

**Issue by heylookltsme** [prettier/prettier#7586]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: CLI
- Runtime: Node.js v13.8.0
- Operating System: macOS, etc.

**Steps to reproduce:**
Repo for reproducing: https://github.com/heylookltsme/prettier-bug

1. `.prettierignore` file at the root of a project
2. `.prettierrc` in subdirectories of the project
3. Run prettier in a subdirectory, passing the `--ignore-path`
4. The `.prettierignore` file is not respected

Correct behavior when run from the root:
<img width="794" alt="corinne_hoener_vimeo____projects_prettier-bug-2" src="https://user-images.githubusercontent.com/1299305/74543467-6ecb1f80-4f13-11ea-969f-0a056abbc1c5.png">

Bad behavior when run from a subdirectory:
<img width="782" alt="corinne_hoener_vimeo____projects_prettier-bug_web1" src="https://user-images.githubusercontent.com/1299305/74543521-81ddef80-4f13-11ea-8427-3b3b887c99d3.png">

**Expected behavior:**
The `.prettierignore` file is respected when prettier is run in a subdirectory. 

**Actual behavior:**
Prettier fails to ignore files when it's run in a subdirectory. 

It seems like the issue is that `.prettierignore` must be at the root of the repo, but if prettier is executing in a subdirectory,  then the ignored patterns aren’t matching because it’s comparing the file path relative to the _current working directory_, not to the root where the .prettierignore file lives. 

I _think_ I have a fix. [This fixes](https://github.com/prettier/prettier/compare/master...heylookltsme:fix-prettierignore-bug) the issue for me locally. I'll submit a PR for feedback. 

Thanks!

**Comment by thorn0** [comment]
`--ignore-path` seems to have been inspired by ESLint. How does ESLint behave in this situation?

**Comment by heylookltsme** [comment]
Good question! 

ESLint behaves as I would expect. `.eslintignore` is not respected when eslint is run from a subdirectory, _unless_ `--ignore-path` is passed, in which case it _is_ respected. 

<img width="957" alt="corinne_hoener_vimeo____projects_prettier-bug_web1" src="https://user-images.githubusercontent.com/1299305/74657169-a9c09380-515d-11ea-8222-6845c3611a65.png">

**Comment by thorn0** [comment]
Fixed by #7588

**Comment by heylookltsme** [comment]
Thanks very much for the prompt attention and review @thorn0! Do you know if there are plans to cut a new release soon? We're hoping to start using a `.prettierignore` in one of our repos at work but we were blocked by this bug, so I'm just curious about the timeline.

**Comment by thorn0** [comment]
The release should happen very soon. Stay tuned. Thanks for the contribution.

**Comment by heylookltsme** [comment]
Awesome, thank you! 🎉

**Comment by j-f1** [comment]
In the meantime, you can do `npm install prettier/prettier` to install the very latest version from GitHub.

**Comment by thorn0** [comment]
> In the meantime, you can do npm install prettier/prettier to install the very latest version from GitHub.

`npm install prettier/prettier#next` is the latest.
