### ISSUE TITLE
Doesn't understand decorators

### ISSUE THREAD

**Issue by ffxsam** [prettier/prettier#759]
I just got this error from the Atom package:

```
SyntaxError: Unexpected token @ (9:0)
   7 | import formousOptions from './theme-form-fields';
   8 | 
>  9 | @Formous(formousOptions)
     | ^
  10 | @Radium
  11 | class ThemeForm extends Component {
  12 |   constructor(props) {
```

**Comment by vramana** [comment]
Please paste the rest of the error. Prettier understands decorators. May be it's specific to atom prettier.

**Comment by ffxsam** [comment]
```

SyntaxError: Unexpected token @ (9:0)
   7 | import formousOptions from './theme-form-fields';
   8 | 
>  9 | @Formous(formousOptions)
     | ^
  10 | @Radium
  11 | class ThemeForm extends Component {
  12 |   constructor(props) {
  at parseWithFlow (/Users/samh/.atom/packages/prettier-atom/node_modules/prettier/src/parser.js:25:19)
  at parse (/Users/samh/.atom/packages/prettier-atom/node_modules/prettier/index.js:26:12)
  at format (/Users/samh/.atom/packages/prettier-atom/node_modules/prettier/index.js:66:15)
  at formatWithShebang (/Users/samh/.atom/packages/prettier-atom/node_modules/prettier/index.js:76:12)
  at Object.format (/Users/samh/.atom/packages/prettier-atom/node_modules/prettier/index.js:90:12)
  at executePrettier (/Users/samh/.atom/packages/prettier-atom/lib/helpers.js:27:21)
  at transformRange (/Users/samh/.atom/packages/prettier-atom/lib/helpers.js:44:23)
  at Object.format (/Users/samh/.atom/packages/prettier-atom/lib/helpers.js:77:7)
  at atom-workspace.format (/Users/samh/.atom/packages/prettier-atom/lib/prettier.js:15:39)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by yamafaktory** [comment]
I can reproduce your issue with the Flow parser using this code, extracted from your error:

```js
import formousOptions from './theme-form-fields';

@Formous(formousOptions)
```

With Babylon I get your error: `../test.js: SyntaxError: Unexpected token @ (3:0)`.

But with Flow, everything is clear then as the error is more helpful: `../test.js: SyntaxError: Leading decorators must be attached to a class declaration (4:0)`

**Comment by ffxsam** [comment]
Got it. So this is indeed a bug in Prettier, then?

**Comment by yamafaktory** [comment]
The error is self-explanatory, if you attach it to a class then Babylon doesn't complain anymore (but not Flow):

```js
import formousOptions from "./theme-form-fields";

@Formous(formousOptions)
class test {}
```

**Comment by ffxsam** [comment]
How is the error self-explanatory? This is valid JavaScript code. If you're saying it's a bug with Flow, the only Flow message I get with regards to using decorators is this (if I run `flow check`):

```
 11: @Formous(formousOptions)
      ^ Experimental decorator usage. Decorators are an early stage proposal that may change. Additionally, Flow does not account for the type implications of decorators at this time.
```

But certainly not an error about not attaching it to a class.

**Comment by yamafaktory** [comment]
When I said it was self-explanatory, I was just saying that the message was leading us in the right direction as this is not thrown by Prettier itself. And I totally agree on the fact that this is valid JavaScript. Any idea @vjeux?

**Comment by ffxsam** [comment]
Ah gotcha. Sorry for the misunderstanding!

**Comment by yamafaktory** [comment]
Ok, I found something. Maybe we should add `esproposal_decorators: true` as another option in https://github.com/prettier/prettier/blob/master/src/parser.js#L10.

Then your code doesn't throw any error. Sadly the *@* are removed with Flow:

```js
Formous(formousOptions)
Radium
class ThemeForm extends Component {
  constructor(props) {
    super(props);
    this.state = {
      file: undefined
    };
  }

  // ...
}
```

**Comment by yamafaktory** [comment]
@vjeux the thing is that there are no nodes of type **Decorator** in Flow, we have to check them as attached props in **ClassDeclaration**.

**Comment by vjeux** [comment]
I tried to make decorators work in flow but the support for them is completely broken. If you want to get decorators, you need to use babylon parser.

**Comment by yamafaktory** [comment]
As per https://github.com/facebook/flow/issues/2741, nothing new regarding supporting that in Flow I guess. But can't we use a workaround, as I mentioned in my previous post (I know it's hacky...)?

**Comment by vjeux** [comment]
If there was only this problem we could have worked around it, but if you try the decorator tests with the flow parser, it syntax error on some of them, don't render some of them and has a widely different way of encoding them in the ast. And the flow team is likely not going to spend any effort on them. You can use babylon parser which works fine if you want decorators.

**Comment by yamafaktory** [comment]
Thanks 👍.

**Comment by bakkot** [comment]
Side note, @ffxsam & @yamafaktory:

> This is valid JavaScript code.

No, it's not! Decorators are not yet part of the language, and their syntax and semantics are going to change (have already changed) between what Babel implements and what, if anything, eventually becomes part of JavaScript.

**Comment by ffxsam** [comment]
@bakkot Fair point! 😄

**Comment by yamafaktory** [comment]
@bakkot Ok, I should have said valid ECMAScript proposal 😄 but anyway Prettier already supports some other stage-2 features (e.g. https://github.com/tc39/proposal-class-public-fields).

**Comment by vjeux** [comment]
Closing as we're not going to support this in the flow parser. You should use babylon parser if you want to use decorators.

**Comment by datwheat** [comment]
@vjeux can i use flow with the babylon parser to get the best of type checking and decorators formatted with prettier?

**Comment by hawkrives** [comment]
@datwheat Babylon also understands flow types, so you should be fine to use it.

**Comment by vjpr** [comment]
@vjeux From https://github.com/prettier/prettier#parser:

> Both the babylon and flow parsers support the same set of JavaScript features (including Flow). Prettier automatically infers the parser from the input file path, so you shouldn't have to change this setting.

1. This should be updated to indicate `flow` parser doesn't support decorators.
2. Does Prettier ever automatically infer a `flow` parser?

**Comment by bakkot** [comment]
Yeah, the "same set of JavaScript features" bit is very wrong. Babylon has support for a great many things Flow lacks and will probably continue to lack for a long time.
