### ISSUE TITLE
Don't force arrow function body on same line

### ISSUE THREAD

**Issue by Hilzu** [prettier/prettier#760]
I created a function like this:

```js
const promiseFromCallback = fn => 
  new Promise((resolve, reject) => 
    fn((err, result) => {
      if (err) return reject(err);
      return resolve(result);
    })
  );
```

This seems pretty clear to me with all the arrow function bodies moved to a new line. Prettier formats that function to this:

```js
const promiseFromCallback = fn => new Promise((resolve, reject) => fn((
  err,
  result
) => {
  if (err) return reject(err);
  return resolve(result);
}));
```
At least to me that is a lot less readable than the first one. This formatting seems to be related to always moving the body of an arrow function to the same line as the arrow. I'm not sure this creates well formatted code.

I also added that code to [prettier.github.io](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20promiseFromCallback%20%3D%20fn%20%3D%3E%20%5Cn%20%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%5Cn%20%20%20%20fn((err%2C%20result)%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20if%20(err)%20return%20reject(err)%3B%5Cn%20%20%20%20%20%20return%20resolve(result)%3B%5Cn%20%20%20%20%7D)%5Cn%20%20)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
Thanks for the report! This is not intended to be printed like this. #674 and #680 are attempts at fixing the problem but we're not 100% sure what the root cause is.

**Comment by jlongster** [comment]
Oh, those are related? I really need to look at those ;)

**Comment by vjeux** [comment]
One thing I want to do at some point is to disallow last argument expansion if the params don't fit in a single line.

```js
/* ... */ fn((
  err,
  result
) => {
  // ...
});
```

should be formatted as

```js
/* ... */ fn(
  (err, result) => {
    // ...
  }
);
```

**Comment by vjeux** [comment]
#847 makes it look:

```js
const promiseFromCallback = fn =>
  new Promise((resolve, reject) => fn((err, result) => {
    if (err) return reject(err);
    return resolve(result);
  }));
```

instead. It's not the original one but looks way less broken than what is currently in prettier.

**Comment by Hilzu** [comment]
That new style looks much better. 👌🏻 The original function is formatted according to my personal preference but anything non-broken looking is good with prettier.

**Comment by jasonkuhrt** [comment]
@vjeux as @Hilzu had in his original, I too think it is more readable to to see function bodies nested more or less regardless of how small they are. For example I think this more readable:
```js
const imageParams = src =>
  src.replace("__IMAGE_PARAMS__", "b_white")

```
than:
```js
const imageParams = src => src.replace("__IMAGE_PARAMS__", "b_white")
```

I realize not everyone may agree so maybe this feature would be best as an opt-in flag. Is there an issue already tracking this described refinement or should I create a new one?

Thanks!

**Comment by spencerfdavis** [comment]
I'd like to add a +1 to @jasonkuhrt as well.  I much prefer the body in a separate line.  This option exist anywhere and maybe I'm just missing it?

**Comment by evilsoft** [comment]
I would like to also second @jasonkuhrt and then on top of that third @spencerfdavis second of @jasonkuhrt comment.
(one step closer to elm 😉)
