### ISSUE TITLE
Remove the version parameter from prettier.getSupportInfo()

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#7615]
This [parameter](https://prettier.io/docs/en/api.html#prettiergetsupportinfoversion) adds a significant maintenance burden (see #4097, #6887), but its value is dubious. What's the use case? I found only that it was used by prettier-vscode (see #5822), but then they understood that it didn't make much sense and stopped using it. I have also checked all the other editor integrations listed on the main page of Prettier's site. They don't use it. So let's get rid of this parameter, shall we?

`getSupportInfo` was added in https://github.com/prettier/prettier/pull/3033.

**Comment by evilebottnawi** [comment]
Previously many plugins recommend to install prettier globally, so developers don't know what is support what is not, and this function allow to them know about supported features based on versions, I don't have strong opinion on that, so if most of core developers vote :+1: I voting :+1: too

**Comment by thorn0** [comment]
I don't really understand. If there is a global instance of Prettier and a local one, you just call `getSupportInfo()` (without arguments) on each of them to see what they support. Why use the parameter?

**Comment by evilebottnawi** [comment]
@thorn0 I tried to find an example of use, but could not, let's remove it

**Comment by lydell** [comment]
This was done in #7620.
