### ISSUE TITLE
Singleton has IIFE parens?

### ISSUE THREAD

**Issue by zbuttram** [prettier/prettier#764]
So, this doesn't seem to break anything, but I do find it a bit weird that singletons that are created right from the class definition get a set of parens after them like an IIFE. Not something I've seen before and I could be fine with them, just want to make sure it's intentional I suppose. Here's an example: https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20MyClass%20%7B%5Cn%20%20%5Cn%7D%5Cn%5Cnnew%20class%20MySingleton%20%7B%5Cn%20%20%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by bakkot** [comment]
See #50.

**Comment by zbuttram** [comment]
Ah, so it's the result of all uses of 'new' doing that. Works for me!
