### ISSUE TITLE
With pre-commit integration, does not format paths containing square brackets

### ISSUE THREAD

**Issue by Conduitry** [prettier/prettier#7641]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: pre-commit
- Runtime: Node.js 13
- Operating System: WSL

**Steps to reproduce:**
1. Set up `pre-commit` in a project pointing to this repo's `.pre-commit-hooks.yaml`
1. Stage a file containing square brackets in its path
1. Run `pre-commit`

**Expected behavior:**

The file whose path contains brackets should be formatted by Prettier.

**Actual behavior:**

The file is not formatted.

I believe this is because of the globbing (beyond the OS shell's globbing) that Prettier is doing. The Prettier CLI gives special meaning to square brackets (and maybe to other characters?) and so they need to be escaped. The hook defined in `.pre-commit-hooks.yaml` simply passes the file paths as-is to the main `prettier` bin, which is a problem. There either needs to be a separate entry point that accepts literal path names, or there needs to be a wrapper entry point that escapes the appropriate characters and passes the args along to the main one.

**Comment by evilebottnawi** [comment]
Fixed in next
