### ISSUE TITLE
Don't wrap arrays in `test.each` template strings 

### ISSUE THREAD

**Issue by offnertho** [prettier/prettier#7653]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdr4GcYDo4CGYAFgAYA6UGGA5gJYBuCAkrHDXAE6oA+q9TKAHkARgCs4YGAEFOnAgE9qyvgIQBlOgFsADgBs4s+QsrLUAEmABGAL5m+lgNrBUOApxhJUAVgA0qBAATLytvVBsAXTsHYEcrXwAmXwBmXwAWXz8ANl8Adl8ADijTZUtbGOdXGHdPH38gkLDI6ItY8hBsGHb-dpxOOigabtR2gDMITmH2nU44GBg6LnbiqlLgZLsVVsq3Dy8-AKhg1FDwqN5tlbNLNJanF13a+MPj5PDfB+q9k4OG1ASAAzvc4VK4YUgACnacAAHgRdAZMHAcMMIcA1FBWPAOJx-BjRBIpEZFHjGBptPpDHJFDYAJSoAC8AD5UMA6ZQOat0J18EQyCVqBiAMIQBGwgmSGTUpR8AUYe6oAghfwiLxvGwfVBgRr+Y6As42WVc+WxT41ZUvNXvM3fUL1I5efUa1lVc0-e16oEaqJG6iQ6FwsVIlEgfxojFY9hcUmCCVE6Ux8li4kKOmMlls2mhkAQHQLaBYZCgdycCAAdwACu4EIWUAQGBA6IFsyJ5GAANZzdQ6IgDGjIGCcACucF8IGIMC0egA6sQ6Nge2A4Ooa-PGPOFMhwFhC2OBlguDAK-IaFoCMhRgQ9Aex2IsDCAEJtzswdTwuAAGQGcAvV5vIDvGFNEGAwAEUhwgeBf2vUcQB7TgD04LcRAIEQ4D0bMZgGGBpybGBiGQAoATHGYIAPad5B0LcZmRLgmGzABHCD4GPXNaxAAgsAAWigOA4ECfjs1mJi6FmY8CFPc8kEvGCxwPLQ6AHYdYKwPswOYn9pL-WDqhEXDAnw5Akg6eQ6D0PsRS0M8tygaAfzHIcDwAFVQ2sZP-BgR1YATYHUMB+jzaQjnUGAFAMaCDxsGwgA)

**Input:**
```jsx
    test.each`
      givenInteger | givenObjectArray         | givenSimpleArray
      ${1}      | ${[{ start: 5, end: 15 }]} | ${[1,2,3,4,5,6,7,8]}
      ${1}| ${[{ start: 5, end: 15 }]} | ${["test", "string", "for", "prettier"]}
      ${3}      | ${[{ start: 5, end: 15 }]} | ${6}
      ${4} | ${[{ start: 1, end: 3 },{ start: 15, end: 20 },]} | ${15.01}
    `("example test", ({givenInteger, givenObjectArray, givenSimpleArray}) => {})
```

**Output:**
```jsx
test.each`
  givenInteger | givenObjectArray           | givenSimpleArray
  ${1}         | ${[{ start: 5, end: 15 }]} | ${[1, 2, 3, 4, 5, 6, 7, 8]}
  ${1}         | ${[{ start: 5, end: 15 }]} | ${["test", "string", "for", "prettier"]}
  ${3}         | ${[{ start: 5, end: 15 }]} | ${6}
  ${4} | ${[
  { start: 1, end: 3 },
  { start: 15, end: 20 }
]} | ${15.01}
`("example test", ({ givenInteger, givenObjectArray, givenSimpleArray }) => {});

```

**Expected behavior:**

I would expect that the `givenObjectArray` containing multiple objects does not get wrapped and stays in one line and that the alignment is working as expected. This example has been taken from an `jest` test.

**Comment by thorn0** [comment]
Suppose there is 20 elements in that array or it contains complex expressions with functions. Does it still have to stay on one long line? If not, how can we tell these two situations apart?

**Comment by offnertho** [comment]
@thorn0 Good point. But currently, the line length is also not respected. As you see in the attached Playground link the second line is exceeding the line length, but the 4th line would not. 

Apart from that I'd say if there are multiline template strings the should not be wrapped. If you use 20 elements it is your own fault I would say.

**Comment by offnertho** [comment]
Adjusted the playground link with a second example that shows that arrays are always wrapped no matter if they would respect the line length.

**Comment by thorn0** [comment]
Yes, they wrap because of [this heuristic](https://prettier.io/blog/2019/11/09/1.19.0.html#break-arrays-of-arraysobjects-if-each-element-has-more-than-one-elementproperty-6694-by-sosukesuzuki). It seems to make sense to adjust the heuristic for arrays not to wrap in `test.each` templates.

**Comment by yogmel** [comment]
Hi everyone,
I'm looking for good-first-bugs to get started contributing to Prettier. May I solve this one if available?

Thanks!

**Comment by thorn0** [comment]
@yogmel Hi and welcome. Of course you may, go ahead. Let me know if you have questions.

**Comment by yogmel** [comment]
Thanks :) I'll look it over the weekend and will let you know.

**Comment by yogmel** [comment]
Hi @thorn0, sorry for the late reply.

I've seen what sosukesuzuki did and started from there, in the `printer-estree.js` file.
Apparently, when the path enters the "TemplateLiteral" case, and then it still runs to the "ArrayPattern" case.

I thought of verifying inside the "ArrayPattern" case if it is a jest template with `isJestEachTemplateLiteral` function, but I'm not sure **what parameters I should pass**. Using the same ones in the "TemplateLiteral" doesn't work:

```javascript
let expressions = path.map(print, "expressions");
const parentNode = path.getParentNode();

if (isJestEachTemplateLiteral(n, parentNode)) {
        // ...
}
```

Could you give me a hand here, please? Thanks!

**Comment by thorn0** [comment]
The goal is to determine if there is a Jest `each` template literal among the ancestors of the current AST (abstract syntax tree) node. Note that it can be any ancestor, not necessarily the direct parent, so you'll need to iterate through the ancestors and check their `type` property. If it equals `TaggedTemplateExpression`, then apply a more specific check, namely `isJestEachTemplateLiteral`. The arguments are the ancestor whose type you checked and its direct parent. To access the ancestors, use the `path` object. It's an instance of the `FastPath` class (`common/fast-path.js`). It holds the coordinates of the current node within the AST, literally the path from the root of the AST to the current node, hence it contains pointers to all the ancestors. Explore its source to learn about its methods.

Hope this helps. If you have more questions, ask here or feel free to DM [me on Twitter](https://mobile.twitter.com/thorn0).
