### ISSUE TITLE
Means to undo formatting applied?

### ISSUE THREAD

**Issue by davidhorner** [prettier/prettier#7656]
Is there a way to have prettier save a delta of the changes it applied to the code and have it undo those transformations?  I'd like to use prettier locally while editing, then before commit have prettier undo the whitespace and other formatting changes so that the lines of change are only those lines which are added or those changes which are functionally different?

that way original authors continue to keep their preference of format within the repo; but those with a taste for prettier formatting could view their code locally pretty and not have to back out formatting changes to keep line ownership/blame working.

thoughts?  wondering the feasibility; would be happy to help create a patch for this ability if it doesn't exist already.

sorry if this is not the place for this discussion;
I looked for a discussion group/email list and didn't find one.
Thanks.

**Comment by thorn0** [comment]
Prettier doesn't have such functionality. This sounds like an idea for a separate tool, not like something that could be part of Prettier itself.

BTW, there was the [`precise-commits`][pc] project. Its idea was similar but not exactly the same. I'm not sure why its development has stopped. Might have something to do with Prettier's bugs related to formatting code ranges, e.g. #4926.

[pc]: https://github.com/nrwl/precise-commits
