### ISSUE TITLE
Prettier requires multiple runs to settle on a final output

### ISSUE THREAD

**Issue by NickHeiner** [prettier/prettier#7657]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBzTBeTAQ3zwICNMAfSzAelswEspGZHCAbTAMzhjAAWAHSiYxmABRhMAQlKYAJlRpxZ87gEoRI+pgBKcNAFcOWCNx6MAThkwAHQmjQjIUW7jwixxUuWV0GZlZ2Ll5+YVFMaTkCJWpMVRieAG4QABoQCDs2dGRQQisrCAB3AAUChDRkEEIANwhGBXSQMitCMABrPgBlBzBmbGQYKyM4DIEYAFsOAHUBVkM+uG7K4NrWAE9qsCdm5jQ4KxhStuxJwmRuTgOMgCs0AA8AITbOnsJJuAAZZjhL67GIHuD26Aw4cAAikYIPB-hwbiAHDZDtUyIQyHAOM07FZmDAZo0YAJkAAOAAMGRxEAOMzadmqOMMh1qfwyAEdofATlkqihHABaKBwOAKEXNKxwDnWOAnQhnC5IK7wwEHSaMIYjFVgyGcv6KgEZGDogkKInIABMhrajA4AwAwhBJudqlBoKyQEYDgAVdG8pUI2qjACSUFFsG6YFx2QAgqHujANuC4QcAL4poA)

When I run `prettier`, it produces a result that is still unformatted. I have to run `prettier` multiple times to ensure that the code is properly formatted.

For example:

**sample.js**
```js
const g = a === b || // initial fetch
    (c !== d || e !== f)

```

```
$ prettier sample.js --no-config --write
```

**sample.js** (after the first pass)
```js
const g =
  a === b || // initial fetch
  c !== d || e !== f;
```

Then I run again, using the same command shown above. Now I get:

**sample.js** (after the second pass)
```js
// Result of first pass
const g =
  a === b || // initial fetch
  c !== d ||
  e !== f;
```

Ideally, running `prettier` once would be enough to output correctly-formatted code.

ESLint has had similar work in this area, where a `fix` for one rule can create code that another rule considers invalid.

**Comment by thorn0** [comment]
already fixed by #7026, but not yet released
