### ISSUE TITLE
Add an option to enforce curly brackets

### ISSUE THREAD

**Issue by titoBouzout** [prettier/prettier#7659]
I find myself constantly adding curly brackets for one liners....

I find this a lot harder to read 
https://s.draw.uy/565a16c498.png

than this
https://s.draw.uy/1c8c25a6dc.png

Can we have an option to enforce curly brackets? 

Reasoning is simple: curly brackets can only be avoided in a "one-liner", so people that like them they just can enable force it and thats it

Well, thats my try :P

**Comment by kachkaev** [comment]
Please do not delete the [issue template](https://raw.githubusercontent.com/prettier/prettier/master/.github/ISSUE_TEMPLATE/formatting.md) when submitting a new issue. Avoiding this simple rule makes it harder to respond.

---

This is a duplicate of #14.

To enforce the rule you want, please use ESLint with its [`curly`](https://eslint.org/docs/rules/curly) rule.

**Comment by titoBouzout** [comment]
Hi kachkaev, 

issue template is irrelevant, I would just skip what I think about it, open a new issue if you want to discuss the issue template.

> This feature request is a duplicate of #4262. To enforce the behaviour you describe, please use ESLint with its curly rule.

What do you mean with "use ESLint with its curly rule", do you mean that editor will show me a red thing on my code so I can add the curly brackets? That's useless, I already know that is complicated to read what I just wrote and Im seeing..... I dont see how adding red stuff on my editor helps me.

What Im asking is very explicit, add an option so prettier while "formatting the code" adds the curly brackets.....

**Comment by kachkaev** [comment]
The feature you are asking for is not about formatting, but the modification of the syntax tree. Such changes in code are outside Prettier’s scope, see: https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about

> What do you mean with "use ESLint with its curly rule", do you mean that editor will show me a red thing on my code so I can add the curly brackets?

Some ESLint rules, including [`curly`](https://eslint.org/docs/rules/curly) are autofixable, which means that you can configure your editor to apply them on file save. This is what we do at our company for the rules that are outside Prettier’s scope. Works quite well!

**Comment by titoBouzout** [comment]
I see, alright, thanks! That will work :)
