### ISSUE TITLE
Prettier formatting destroys Public Suffix List by randomly removing quotes

### ISSUE THREAD

**Issue by kekkc** [prettier/prettier#7661]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgM7E4DmUACugEYA2OYAyuqqjgB5zEAUAlPmAAdKMJgAHOoxZsO3YvgC8Q0ePEByWgBMNSfACYANGpiaAXumIALHADoA1oSiFyhAO6E7AKwl78AIymAL4A3KLBoiBGIBASuNDEyKCEAE6pEO5UaQhJKIQAbhA42tEgtKmEYA5wMMwSVThQ5MgwqehwMdYwALb0AOq28MQNYHDMuTi4BVMAnsjgpGVNxHCpMFSV5D2EyKiE9Ksx3sScAEKV1bXMhD1wADJNcHsHRyAnnMxN5PRwAIroCDwF6HTogBqpVapBa0Qi0OD0MoSVJNGD9EowazIAAcAAYYsiIKt+pUJAtkTw1gVnjEAI6A+CbOJ5EAkAC0UDgcG03LKqTg9Jw-M2rh2ILeqx6OFa7TBZGavwBQOeSH2oJiMDh6O0mOQxhAbUIOEYzQAwhAemKUFBoDSQFY4AAVOF5NVvAodACSUB5sGYYBR8QAgj7mDBZr9xXBgsEgA)

**Input:**
```jsx
function assignPublicSuffixes() {
	publicSuffixes = {
		'bd': 2,
		'zushi.kanagawa.jp': 1
	};
}
```

**Output:**
```jsx
function assignPublicSuffixes() {
  publicSuffixes = {
    bd: 2,
    "zushi.kanagawa.jp": 1
  };
}

```

**Expected behavior:**
It should read "bd", but Prettier removed the quotes and destroyed the PSL.

**Comment by sosukesuzuki** [comment]
Please use [quote-props option](https://prettier.io/docs/en/options.html#quote-props).
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgM7E4DmUACugEYA2OYAyuqqjgB5zEAUAlPmAAdKMJgAHOoxZsO3YvgC8Q0ePEByWgBMNSfACYANGpiaAXumIALHADoA1oSiFyhAO6E7AKwl78AIymAL4A3KLBIEYgEBK40MTIoIQATikQ7lSpCIkohABuEDjaUSC0KYRgDnAwzBKVOFDkyDAp6HDR1jAAtvQA6rbwxPVgcMw5OLj5kwCeyOCkpY3EcCkwVBXk3YTIqIT0K9HexJwAQhVVNcyE3XAAMo1wu-uHIMeczI3k9HAAiugQeDPA4dED1FIrFLzWiEWhweilCQpRowPrFGDWZAADgADNEkRAVn0KhJ5kieKt8k9ogBHAHwDaxXJglIUlJU0qsuk4VkbVzbYGvFbdHAtNqgshNH7-QFPJB7EHRGCwtHaDHIYwgVqEHCMJoAYQg3QFKCg0GpICscAAKrDcgrXvl2gBJKDaBC1MDIuIAQTdzBgMx+grgwWCQA).
```js
// Input
function assignPublicSuffixes() {
	publicSuffixes = {
		'bd': 2,
		'zushi.kanagawa.jp': 1
	};
}

// Output
function assignPublicSuffixes() {
  publicSuffixes = {
    "bd": 2,
    "zushi.kanagawa.jp": 1
  };
}
```
