### ISSUE TITLE
Angular interpolation code not indented correctly

### ISSUE THREAD

**Issue by DarkLite1** [prettier/prettier#7665]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAtgQxgWk2SAJwBMBLaAAnQFcAbGUgXgB0QZDq5WKAqKAcwCSAMxYgADhADOMKQDpaCfjAAWFAHwUADK3XMoFChmw44AD3GYoU8lByWocWrwEAxCITGKYFSTIoQwr7Ssrr6hobGuOYONtD2Vk44KnCYxHCEegYRhsDAwTJyDDCKFAC+ZeERqAD0WNEWVnF2DkkpaRlZOXkFMHKQsAg+FVWR9XhgDPGEEADuXTlGAEbUMDCU4ytrlJC0HmLihKRYhACeugCiACKCACq1W+tQCzmojxsm7wa7+6yzmIQoLorhcADIXW4XB6rJ4vIx1Ez4KZ2GbzKq1cYxJq2BKOWhZDGIggeMjQLL6VAAQhwOAoKjW4ikSBqCPgR0wtDkVn4dABcnINR5pHSNRgp0k-EImHEKlOFBpBPEFDAtEwUikYlIUGEEBw8DMPk2EGIpxwAEZuHwhKJWH5ZAolKojIxtLoAHIQXpSChpdLECinOAwWriLIgAA0IAg4mRUmQoABqIACgCEHGUJgAG4QYURkBLKVgADWQYAypYwFr+Mh2JxI-T0LQAOoqUjwKQVuCltNt0iZtunZDgdV5rVSDIwJNS-hYZDCDnjyMAKykZgAQoWSzBS5h0HBQVq4HOF3Bl6vS1XFABFagQeDH2iLiQA8eEIdLTBLJx5w5amBN4VVGQAAOLRI0OaQ4CbKVxCHQ44FfTMj0jABHW94CnaN0xANUcEcOA-TzQg4DQ0hiKnTAZ0wB8n3HdBSBrDhTxAGwBGvdCjyQedH2YmBPwA4ggKQAAmSN2EwUhaCrABhCB0FnFAoGgZCQGocdbk-dNuKfTNOEEKB0lgUswCOGMAEEDNLMVFBouAKiAA)
```sh
--parser babel
```

**Input:**
```jsx
<mat-accordion multi="true" *ngIf="posts.length > 0">
  <mat-expansion-panel *ngFor="let post of posts">
    <mat-expansion-panel-header>
      {{ post.title }}
    </mat-expansion-panel-header>
    {{ post.content }}
    <mat-action-row>
      <button mat-button color="primary">EDIT</button>
      <button mat-button color="warn">DELETE</button>
    </mat-action-row>
  </mat-expansion-panel>
</mat-accordion>

<!-- https://material.angular.io/guide/typography -->
<p class="info-text mat-body-1" *ngIf="posts.length <= 0">No posts added yet</p>

```

**Output:**
```jsx
SyntaxError: Unexpected token (1:29)
> 1 | <mat-accordion multi="true" *ngIf="posts.length > 0">
    |                             ^
  2 |   <mat-expansion-panel *ngFor="let post of posts">
  3 |     <mat-expansion-panel-header>
  4 |       {{ post.title }}
```

**Expected behavior:**
```javascript
<mat-accordion multi="true" *ngIf="posts.length > 0">
  <mat-expansion-panel *ngFor="let post of posts">
    <mat-expansion-panel-header>
      {{ post.title }}
    </mat-expansion-panel-header>
      {{ post.content }}
    <mat-action-row>
      <button mat-button color="primary">EDIT</button>
      <button mat-button color="warn">DELETE</button>
    </mat-action-row>
  </mat-expansion-panel>
</mat-accordion>

<!-- https://material.angular.io/guide/typography -->
<p class="info-text mat-body-1" *ngIf="posts.length <= 0">No posts added yet</p>

```

**Comment by thorn0** [comment]
This code is formatted fine with `--parser angular`.

Prettier automatically detects that the Angular parser should be used if the file has the extension `.component.html`, which is the naming convention in Angular. If you want to name your template files differently, you'll have to let Prettier know that the Angular parser should be used for them.

For examplem, here's what you need to add your Prettier [config file](https://prettier.io/docs/en/configuration.html) (`.prettierrc`) to format `*.tpl.html` as Angular markup:
```json
{
  "overrides": [
    {
      "files": "*.tpl.html",
      "options": { "parser": "angular" }
    }
  ]
}
```

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAtgQxgWk2SAJwBMBLaAAnQFcAbGUgXgB0QZDq5WKAqKAcwCSAMxYgADhADOMKQDpaCfjAAWFAHwUADK3XMoFChmw44AD3GYoU8lByWocWrwEAxCITGKYFSTIoQwr7Ssrr6hobGuOYONtD2Vk44KnCYxHCEegYRhsDAwTJyDDCKFAC+ZeERqAD0WNEWVnF2DkkpaRlZOXkFMHKQsAg+FVWR9XhgDPGEEADuXTlGAEbUMDCU4ytrlJC0HmLihKRYhACeugCiACKCACq1W+tQCzmojxsm7wa7+6yzmIQoLorhcADIXW4XB6rJ4vIx1Ez4KZ2GbzKq1cYxJq2BKOWhZDGIggeMjQLL6VAAQhwOAoKjW4ikSBqCPgR0wtDkVn4dABcnINR5pHSNRgp0k-EImHEKlOFBpBPEFDAtEwUikYlIUGEEBw8DMPk2EGIpxwAEZuHwhKJWH5ZAolKojIxtLoAHIQXpSChpdLECinOAwWriLIgAA0IAg4mRUmQoABqIACgCEHGUJgAG4QYURkBLKVgADWQYAypYwFr+Mh2JxI-T0LQAOoqUjwKQVuCltNt0iZtunZDgdV5rVSDIwJNS-hYZDCDnjyMAKykZgAQoWSzBS5h0HBQVq4HOF3Bl6vS1XFABFagQeDH2iLiQA8eEIfc3lvyOHLUwJvC1RkAADi0b8ZnHJspXEIdDjgV9MyPSMAEdb3gKdo3TEA1RwRw4D9PNCDgFDSEIqdMBnTAHyfcd0FIGsOFPEAbAEa9UKPJB50fRiYEwJZ-2IQCkAAJkjdhMFIWgqwAYQgdBZxQKBoEQkBqHHW5ePTTin0zThBCgdJYFLMAjhjABBfTSzFRQqLgCogA)
```sh
--parser angular
```

**Input:**
```html
<mat-accordion multi="true" *ngIf="posts.length > 0">
  <mat-expansion-panel *ngFor="let post of posts">
    <mat-expansion-panel-header>
      {{ post.title }}
    </mat-expansion-panel-header>
    {{ post.content }}
    <mat-action-row>
      <button mat-button color="primary">EDIT</button>
      <button mat-button color="warn">DELETE</button>
    </mat-action-row>
  </mat-expansion-panel>
</mat-accordion>

<!-- https://material.angular.io/guide/typography -->
<p class="info-text mat-body-1" *ngIf="posts.length <= 0">No posts added yet</p>

```

**Output:**
```html
<mat-accordion multi="true" *ngIf="posts.length > 0">
  <mat-expansion-panel *ngFor="let post of posts">
    <mat-expansion-panel-header>
      {{ post.title }}
    </mat-expansion-panel-header>
    {{ post.content }}
    <mat-action-row>
      <button mat-button color="primary">EDIT</button>
      <button mat-button color="warn">DELETE</button>
    </mat-action-row>
  </mat-expansion-panel>
</mat-accordion>

<!-- https://material.angular.io/guide/typography -->
<p class="info-text mat-body-1" *ngIf="posts.length <= 0">No posts added yet</p>

```

**Comment by DarkLite1** [comment]
@thorn0  thank you for the feedback. 

The file is called `post-list.component.html` so I guess the naming is correct but Prettier is not using the correct angular formatting. Should this not be a bug then? As all files ending with `component.html` should be formatted for Angular by default?
