### ISSUE TITLE
Import sorting

### ISSUE THREAD

**Issue by philipp-spiess** [prettier/prettier#767]
In order to avoid unnecessary git changes, we sort our import statements using the default sort feature of Atom or VSCode. We do this by selecting all import lines and running the sort action.

This works okayish but breaks complelty when we break multiple imports into multiple lines, e.g:

```js
import {
  Foo,
  Bar,
  Baz
} from 'foobarbaz';
```

Since this will (obviously) be sorted to:

```js
  Bar,
  Baz
  Foo,
} from 'foobarbaz';
import {
```

Are there any plans to support sorting of import blocks using prettier?

The idea would be to detect blocks that consists of import lines like:

```js
import Bar from 'foo';
import Foo from 'foo';
import foo from 'foo';
import bar from 'foo';
import { 
  Foo,
  Bar
} from 'foo';
import * from 'foo';
import { Bar } from 'foo';
import {
  foo,
  bar
} from 'foo';
import { Foo } from 'foo';
import type Foo from 'foo';
import type Bar from 'foo';
import { bar } from 'foo';
import { foo } from 'foo';

```

and turn it to something like:

```js
import { bar } from 'foo';
import { Bar } from 'foo';
import { foo } from 'foo';
import { Foo } from 'foo';
import { 
  foo,
  bar
} from 'foo';
import {
  Foo,
  Bar
} from 'foo';
import * from 'foo';
import Bar from 'foo';
import bar from 'foo';
import foo from 'foo';
import Foo from 'foo';
import type Bar from 'foo';
import type Foo from 'foo';
```

**Comment by demoneaux** [comment]
Prettier is just a code formatter and avoids actual changes to the code which modifies the AST and hence might affect execution. You should try to create a plugin to do that.

**Comment by lydell** [comment]
Unfortunately, importing modules can have side effects so changing the order of imports is not safe. So I guess this one has to be closed for the same reasons as #323 and #766. You could use the [sort-imports](http://eslint.org/docs/rules/sort-imports) ESLint rule, though.

**Comment by philipp-spiess** [comment]
Right, side effects, I kinda forgot about that. Thank you for your quick reply :) Consider this closed.

**Comment by dolanmiu** [comment]
But could this be a feature, but then have an option to turn it off in `.prettierignore` or inline in the file?

I have noticed that I have to sort imports more often than not.

There is only a few files in projects with side effects from ordering. But 99% of the time, I have to sort...

**Comment by j-f1** [comment]
@dolanmiu https://prettier.io/docs/en/option-philosophy.html

**Comment by suchipi** [comment]
FYI/for future readers, `eslint-plugin-import`'s [`import/order` rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) can enforce an import order based on module location (but not alphabetization). However, the rule is not fixable.

**Comment by lydell** [comment]
Here are two ESLint plugins I'm watching that might be good for import sorting:

- https://github.com/asn007/eslint-plugin-codebox
- https://github.com/marudor/eslint-plugin-sort-imports-es6-autofix
