### ISSUE TITLE
Ugly React Hooks 

### ISSUE THREAD

**Issue by DScheglov** [prettier/prettier#7671]
[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMGAGn2HwFcBnOAZRhPiobgFk50J8AvvgBmOCOnwAdEDlLlpAbklRlkKPQKYSORgDFaAGwMA5Eujj4AvCMMmzFywD5qy-PjUb8Ad1wATelY2RqbmAHQwOBgAFACUofSYBqgwUQD0kpL0ANSpccKoBvA4UQBCEBAGpFAxSlBuHgT5OjAhDt5+9PEAFqjCKTWu7tCeBiQarYE+OP6hAFYQqFBR0lIgA3X4sjC0OHU0TeP2VKOH5oK1AsrKwrRQ5KjQ+ACCmJixLhsN+ADaN8FH+EYMH0-3MAF1ApwWGw4MsQNJ1vVhgR9qhmq1jmMWvZBJDGDw+MsNm53k58FodHAQXZzFE-jS4DEKIM3L9bK0wcyNoipBstjs6kS3G4ADyOFlSGAixaYWgwCXC-AANxIBlocEswHprUuxMV+GgAGEuiQoABzDXAOBKhAEMlA6mtKLW23hbQWmChFVqxm6-X4VLivWiro4ANB-0iwwR-34EVJRy6NGeVpIOMaMTmxxa5PY8wCEWpDPQM2OQsJhXC+OoRwAGSx+FT6YiJezJzzcALRZbWfLNcrhejEsLMfWuuUcAAHtg8PhfHBhCRDAQXpgFCAKCAIJgYA91MhQNoxF4AAraBD0ZAgEhKha+DcgABGODIAGs4DAmFowIszcgIuqm5dDA6AGAA6j08AJGQzAXskqBKskACeV5gPQl6bosjB4CeL5mugJDIIuBiMJusz0JOJQvmA76fvYtaLHARGqqRIDkZOTC-pUACKtAQPAzEkXAm4UthV6PiQj5IQY0APpgkSwGBqC+DAXTIAAHAADCJYiMGBL6YFe8lwNhNoPgAjnx8C4dul4oGMAC0UBwHA873pusiWWicC4SQ+GEUgxGsYw6CoP+OCASA9BcXAvH8UxgUscJICsI+SkqWpSAAEybhEJAFL+hriARV5QNATGbpwAAqkl2UFyVKuqACSUDzrATBgJEO5PK1LDSQl9UCAIQA)

**Input:**
```jsx
  const { firstName, lastName } = useMemo(
    () => parseFullName(fullName),
    [fullName],
  );
```

**Output:**
```jsx
  const { firstName, lastName } = useMemo(() => parseFullName(fullName), [
    fullName
  ]);
```

**Expected behavior:**
Input should be kept unchanged.

```jsx
  const { firstName, lastName } = useMemo(
    () => parseFullName(fullName),
    [fullName],
  );
```

**Comment by DScheglov** [comment]
There is workaround for this bug: To add comment after dependency list (or after factory or callback).

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMGAGn2HwFcBnOAZRhPiobgFk50J8AvvgBmOCOnwAdEDlLlpAbklRlkKPQKYSORgDFaAGwMA5Eujj4AvCMMmzFywD5qy-PjUb8Ad1wATelY2RqbmAHQwOBgAFACUofSYBqgwUQD0kpL0ANSpccKoBvA4UQBCEBAGpFAxSlBuHgT5OjAhDt5+9PEAFqjCKTWu7tCeBiQarYE+OP6hAFYQqFBR0lIgA3X4sjC0OHU0TeP2VKOH5oK1AsrKwrRQ5KjQ+ACCmJixLhsN+ADaN8FH+EYMH0-3MAF1ApwWGw4MsQNJ1vVhgR9qhmq1jmMWvZBJDGDw+MsNm53k58FodHAQXZzFE-jS4DEKIM3L9bK0wVRUql8L44JgEHy7qg4PRBoipBstjs6kS3G4ADyOFlSGAKxaYWgwFXy-AANxIBlocEswHprUuxN1+GgAGEuiQoABzE3AOB6hAEMlA6mtKLuz3hbQumChA1GxmW634VLKq2Kro4GNx6MKwwp6P4BVJRy6NGeVpILMaMTOxxm-PY8wCBWpEvQJ2OWs5nXy7OoRwAGSx+ELxYiDfLJyrcBrdYHZebHdbtfTKtrGfWluUcAAHtg8Ly4MISIYCC9MAoQBQQBBMDAHupkKBtGIvAAFbQIejIEAkPULXzHkAAIxwZAAazgGAmC0MBFidZAImNE8uhgdADAAdR6eAEjIZhn2SVA9WSABPV8wHoF8T0WRg8Hvf8nXQEhkB3AxGBPWZ6FXEp-zAICQPsTtFjgWjDQYkAmNXJgIMqABFWgIHgPj6LgE8KTI18fxIH84AMb9MEiWBENQXwYC6ZAAA4AAZ5LERhEP-TBX000U4BwD1vwAR0k+AKLPF8UDGABaKA4DgPkvxPWQXLROAKJIKiaKQOiBMYdBUCgnAYJAehRLgCSpN4mL+LkkBWB-HS9IMpAACYTwiEgCgg21xGo18oGgXiT04AAVFTPNivK9WNABJKAhRAsBInPJ4BpYXDKhkxgBAEIA)

**Input**:
```js
  const { firstName, lastName } = useMemo(
    () => parseFullName(fullName),
    [fullName], // dependencies
  );
```

**Output**:
```js
  const { firstName, lastName } = useMemo(
    () => parseFullName(fullName),
    [fullName] // dependencies
  );
```

The workaround works but there is a significant con for that: it noises code with unnecessary comments, so it could be, but not should, be used.

**Comment by mayeths** [comment]
The [inline version of react hooks](https://github.com/prettier/prettier/issues/5376) looks great. Is that issue solved?
**Inline:**
```javascript
function helloWorld() {
  useEffect(() => {
    // do something
  }, [props.value])
}
```
**Actual:**
```javascript
function helloWorld() {
  useEffect(
    () => {
      // do something
    },
    [props.value]
  );
}
```

**Comment by kuzkokov** [comment]
@mayeths nope, those are different cases.

using something like `useMemo` we can return value right away, and this is when format gets ugly:
```
const something = useMemo(() => getSomething(props.foo), [
  props.foo,
]);
```

to get your version of formatting we should do something like this:
```
const something = useMemo(() => {
    return getSomething(props.foo);
}, [props.foo]);
```

**Comment by unix** [comment]
Additional information.
If the `width` is set low, it looks normal. [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMGAGn2HwFcBnOAZRhPiobgFk50J8AvvgBmOCOnwAdEDlLlpAbklRly4bSjlU0fAEFMmABQBKasvz5IUegQDaUEujhVGMAHKO4AXXwBeOowsbHCG0tLGSlAWVjb49p4ATD7+nEHwoSDhkdHQsfFOAMzJAcys6WEgEeaWuXYOTgAsxallIRVVUTXWdZ4ArM2BrRlZ1TE9TgBsA6XBw5XZXbE0wqg4Nh5OVAA2JOuegn4lPHyhnRYmfgB8+Jgka3AAYrRbWxsh6i9vxhTVFvnO+HqcASVCBBVBniaP06HQs1VkMFoOCipwsFgAPJdflIYNiMQALHD4AD0WLOaPRACNaDAYDpoABhfEkKAAczgvmAF1811cb0MAHIAIwC4wCS5gZlsuDo4nU2nQLG48myskWDoCVRQOAAD2weHwABM4MISM8CPpMAoQBQQBBMDBtNZkKA7mIAO4ABTuCHoyBAJC27pIAE8-bbKTgyABrOAwJi3MCoNnIGA4WjOED4mDoLYAdXxqHg9ETzF9RdQADciyH-WB6OG0NY4HhPVHWegSMhTVtGLaAFb0HUAISjYFj8c8ABlk3Bu4G+yBBzqmMnWVs4ABFWgQeDz3uZ273HD+ykkSlwLY2kCYHDJmB51CGmD45ATAAMttvEEYeajmH9W84EYHBKznW0AEcd3gNt7T9FBdgAWm1OBjUNa9ZCg1Y4DbEgOy7JAe0XRh0FQVN00zeg1w3bddznQiF0zVhKUfZ9XyQEEQDTEhUC2NcGXETt-WA3pr04AAVc94KIzNKwzABJKBjVgJgwDvB1dCUlgQw3fdGAEAQgA).

**Input(`print-width: 60`):**
```jsx
const { firstName, lastName } = useMemo(
    () => parseFullName(fullName),
    [name, name2, name3, name4],
);
```
**Output:**
```jsx
const { firstName, lastName } = useMemo(
    () => parseFullName(fullName),
    [name, name2, name3, name4]
);
```
