### ISSUE TITLE
Feature: consider using confinode

### ISSUE THREAD

**Issue by sveyret** [prettier/prettier#7674]
Hi,

Please consider using [confinode](https://www.npmjs.com/package/confinode) for your configuration file. This would allow _Prettier_ to:

- offer a great variety of file types, e.g. _TypeScript_ users could write the configuration in _TypeScript_;
- extend configuration file (inheritance).

This would also automatically manage some points which seem to be currently managed in _Prettier_ code:
- configuration indirection (returning a string indicate the real place of the configuration file);
- configuration analysis to check there are no errors in configuration file.

Do not hesitate and ask me if questions or help needed…

(whether you take it or not, I'd really appreciate if you tell me why…)

**Comment by evilebottnawi** [comment]
We use `cosmiconfig` https://github.com/davidtheclark/cosmiconfig and do not want to migrate on other (a lot of packages use this package), maybe we revisit it in the future

Anyway thanks for the issue
