### ISSUE TITLE
Prettier 1.20 - Last 1.x release?

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#7675]
The latest release (1.19) was in November of last year. We have a few bugfixes that we could be released already before the 2.0 release.

I'll work on this today

**Comment by evilebottnawi** [comment]
@duailibe Which PRs we want to port for `1.20`?

**Comment by duailibe** [comment]
@evilebottnawi I would just do a release from master, but if there are PRs that can be ported easy enough, I'm happy to do it

**Comment by thorn0** [comment]
I'd say #6949 and #7026. Users complain the most about these two.

**Comment by duailibe** [comment]
Yes, #6949 is the main reason, which is why a release from master would suffice

**Comment by evilebottnawi** [comment]
@duailibe master contains breaking changes, we can't release this as `1.20`, we do have a lot of work for `2`, so I would probably rather not do release `1.20`, but if all votes for `1.20`, I am ok

**Comment by duailibe** [comment]
@evilebottnawi what breaking changes?

**Comment by graemeworthy** [comment]
#7654 on other items in the 2.0 branch, and can be easily ported, it is not in master.

I have rebased on master:
https://github.com/prettier/prettier/compare/master...graemeworthy:prettier-ignore-should-also-ignore-text-nodes

**Comment by thorn0** [comment]
Let's merge #7660 (as is, without addressing this [issue](https://github.com/prettier/prettier/pull/7660#discussion_r383698135)) and #7668 and release 2.0 instead.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/6981

**Comment by duailibe** [comment]
@thorn0 IMO you shouldn't rush a 2.0 release, but it's your call. I wanted to get those fixes out by today or tomorrow. Do you think 2.0 will be ready by then?

**Comment by FabHof** [comment]
#6464 would make glimmer almost usable.

**Comment by krilllind** [comment]
Would it be possible to release a 1.19.2 patch including issues related to 1.19(.1) and then just wait with 2.0?

I'm for example waiting for [this](https://github.com/prettier/prettier/issues/5875#issuecomment-576152782) fix to be released.

**Comment by heylookltsme** [comment]
I'd love to have [this](https://github.com/prettier/prettier/pull/7588) included in a minor release, if possible! 🙏

**Comment by mvlabat** [comment]
I would also love to see this: #6953

**Comment by eps1lon** [comment]
#7631 would be nice as well. Generally any change that deals with new syntax would be nice to backport. Otherwise you might get stuck in this weird limbo where you can't upgrade syntax because you can't ugrade prettier.
