### ISSUE TITLE
Prettier on the Jest repo

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#768]
Not sure if this issue is valid by itself, but I tried out prettier on the Jest repo and there are a number of issues that I found. Feel free to close this issue if it isn't detailed enough or you aren't planning on fixing any of these.

I ran:

```
node_modules/.bin/prettier --write "packages/*/src/**.js" --single-quote --trailing-comma --bracket-spacing=false --parser=flow
```

on the jest repo and got a bunch of lines that are longer than 80 characters. Examples:

```
    return chalk.bold('No tests found') +
      '\n' +
      (data.total
        ? `  ${pluralize('file', data.total || 0, 's')} checked.\n` +
            statsMessage
        : `No files found in ${config.rootDir}.\n` +
            `Make sure Jest's configuration does not exclude this directory.\n` +
            `To set up Jest, make sure a package.json file exists.\n` +
            `Jest Documentation: facebook.github.io/jest/docs/configuration.html`);
```
or:

```
const JASMINE_IGNORE = /^\s+at(?:(?:.*?vendor\/|jasmine\-)|\s+jasmine\.buildExpectationResult)/;
const STACK_TRACE_IGNORE = /^\s+at.*?jest(-.*?)?(\/|\\)(vendor|build|node_modules|packages)(\/|\\)/;
```

**Comment by cpojer** [comment]
Seems like an empty try-catch gets split into two lines:

```
try {
  …
} catch (e) {}
```
becomes
```
try {
  …
} catch (e) {
}
```

**Comment by cpojer** [comment]
Long requires get split up into multiple lines. At FB we have a rule to ignore "require" or "imports" from the max-width restriction:

```
const Module = require('long/path/to/foo/does/not/get/split/up/over/multiple/lines');
```

**Comment by yamafaktory** [comment]
Really interesting to see Prettier running against such a huge and nice codebase 👍.

**Comment by cpojer** [comment]
One thing I really don't like about prettier is:

```
return a &&
  b;
```

the code style I've been using mostly is

```
return (
  a &&
  b
);
```

which allows to line up the operations nicely. I understand I'm now going into bikeshed territory but I'm unclear which parts of the standard are still being iterated on and which one @jlongster considers final.

**Comment by cpojer** [comment]
Another thing is that right now, it introduces flow errors because of a `// $FlowFixMe` declaration. I'm unsure if there is anything you can do about this in prettier, though, and we may 

```
      // $FlowFixMe
      Object.freeze(
        Object.assign(
          {
            testNamePattern: argv.testNamePattern,
            testPathPattern: argv.testPathPattern,
          },
          config,
          overrideConfig,
        ),
      ),
```

previously, `Object.freeze(Object.assign(…` was in one line, so it would suppress the error properly. Afterwards, I have to figure something else out to work around flow errors.

cc @vjeux this one may block you massively if you attempt to roll out prettier at FB.

**Comment by cpojer** [comment]
Happy to start using it on parts of the codebase, though: https://github.com/facebook/jest/pull/2975

**Comment by cpojer** [comment]
For years I've been using this style (cc @thymikee):

```
array.forEach(
  item => doSomethingWith(item),
);
```

but prettier prefers:
```
array.forEach(item =>
  doSomethingWith(item),
);
```

which seems less readable in the common case.

**Comment by cpojer** [comment]
Another one in the readability category and is very subjective is grouping for && and || operators. I used to prefer this style all my life:

```
const a = (b && c) || y;
```

the parenthesis are unnecessary because of how operator precedence works, however I always thought it helps greatly with readability. Prettier prints this:

```
const a = b && c || y;
```

It really comes down to whether you optimize for readability or the least amount of code here. I'd always choose readability but I know a lot of people would disagree with me that what prettier produces here is harder to read than using parenthesis.

**Comment by cpojer** [comment]
This also looks quite a bit more confusing than before, although I will accept this as being subjective: https://github.com/facebook/jest/pull/2975/commits/0724d877565f489561f52b1535de8b7496bd702b#diff-01c39670fbe12c47eaa0c31e8bdcbc22R250

**Comment by cpojer** [comment]
Unexpected parenthesis here: https://github.com/facebook/jest/pull/2975/files/79aae746592b53a76ca372b85f7965b9062acdd7#diff-97e858f36d62364c13d1ae642c703e04

**Comment by cpojer** [comment]
The previous code style was more readable:


```
chalk => added
  ? chalk.bgRed
  : (removed ? chalk.bgGreen : chalk.dim);
```

vs

```
chalk => added ? chalk.bgRed : removed ? chalk.bgGreen : chalk.dim;
```

https://github.com/facebook/jest/pull/2975/files/79aae746592b53a76ca372b85f7965b9062acdd7#diff-2f8c2bdb6c4e6ba4cb808277d3d41fcc

**Comment by cpojer** [comment]
This one is pretty odd: https://github.com/facebook/jest/pull/2975#discussion_r102500336

```
.split(EOL)
[0].trim()
```

even though it is fine on the code right below it.

**Comment by cpojer** [comment]
Another one that is very confusing: https://github.com/facebook/jest/pull/2975#discussion_r102509941

```
this._mockMetaDataCache[modulePath] = (this._moduleMocker.getMetadata({
}): any);
```

this should stay in one line.

**Comment by vjeux** [comment]
Thanks for trying it out and reporting all those! I'm pretty excited that overall those aren't big issues.

I have to go for a while but I replied to comments in the jest PR and created a bunch of issues with what you reported (not all yet). All the ones marked as bugs I'm going to fix and I'd like to get some more discussion on the ones labelled as "Needs discussion".

![image](https://cloud.githubusercontent.com/assets/197597/23224046/b09554ca-f8e1-11e6-8c24-2b234730631c.png)

I hope that with some more work we'll be able to make it work well for your codebase :)

**Comment by cpojer** [comment]
Sounds awesome, feel free to close this issue if it doesn't serve any purpose any more. We'll hold off on adopting prettier until the bugs are fixed and you have made a decision on the style, but do get back to me when most of this is tagged and ready. I wanna start using prettier asap.

**Comment by vjeux** [comment]
Let's close it and talk about them on the individual issues. Feel free to open issues for things I missed.

**Comment by jlongster** [comment]
Woha, thanks @cpojer!

**Comment by vjeux** [comment]
@cpojer @thymikee I just pushed 0.19.0 with a bunch of fixes. Would be great if you could run prettier on jest again and do another round of suggestions on things to fix :)

**Comment by cpojer** [comment]
Can you let me know which things were fixed?

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/pulls?q=is%3Apr+is%3Aclosed
