### ISSUE TITLE
Preserve indentation on empty lines

### ISSUE THREAD

**Issue by BlueskyFR** [prettier/prettier#7681]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlPvpFERADZwB0LEA5qdSEQAOEHGwBOSQgAs4+KHAAeMfCxzz8OInIjLuIqN0IR8AI1lqAJghgBCfuQDctes4bRmbTjz4gA7gEMcZRgZDSgrWHwCENlBMTgANzx0LVV1TW1lAGs4QVt7JygAXxAAGhAIPLwmZFB-MTEIXwAFeoQiZBB-BJELMpATMX8wHJgAZUFhtW5kGDF0OHKpGABbFgB1KSC4IWG4MfagnCSYAE9OsCIO8rUiODEYZqHuFf9kVH8WO-KAKyIFABCQxGcHG-hWcAAMmo4O9Pt8QH8FGNpmwAIroHSwpAfL6LECTMR3MSdEz+MwsfpxNQwdY4CwhZAADgADOU4hA7ushoJOnEdvcErDygBHTHwJ6VDoofxEAC08jgVj65XiYpw8Se-hebxx8PxdxWOFm8wNqLgGKxcLx5Rg5LpDKkyAATLahqJpgBhCArV6dKDQYUgFJwAAq5OluIRCQWAElwtYxmAxDg8gBBcJjM5sa13IpFIA)

**Input:**
```js
function test() {
  console.log("spoiler: the next line is not going to be indent!");
  
  console.log("wait the indent on the previous line is not kept!");
}
```

**Output:**
```jsx
function test() {
  console.log("spoiler: the next line is not going to be indent!");

  console.log("wait the indent on the previous line is not kept!");
}
```

**Expected behavior:**
How can I have the line between the two console.log indented after Prettifying my file?
Is there an option for that?

Thanks in advance!

**Comment by evilebottnawi** [comment]
No options, it is default behavior and we do not want to modify that, please read https://prettier.io/docs/en/rationale.html#empty-lines

**Comment by BlueskyFR** [comment]
@evilebottnawi "The approach that Prettier takes is to preserve empty lines the way they were in the original source code."
Here the line is not **preserved**.

**Comment by GrayStrider** [comment]
Hello? Any comments in the comment above? I just noticed that prettier removes indentation from empty lines; I suppose this behavior is not configurable? That would seriously pollute my git history
