### ISSUE TITLE
Consider separating CLI.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [prettier/prettier#769]
This would reduce the number of dependencies when `prettier` is used as a library (i.e. `prettier-eslint`).
Would you be interested in a PR for this?

**Comment by jlongster** [comment]
I don't know. I know there are some specific advantages but I think it makes the overall experience feel a lot more bloated. We are thinking through a server architecture right now though and we'll probably have a better idea after that's finished.

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for your consideration.
It does take a bit more work, but `lerna` takes a lot of the hassle out of it.

**Comment by jlongster** [comment]
`lerna` is a whole new tool and more stuff to manage. :) Not saying it's not a good project, but I'm hesitant to add a lot of boilerplate. I think I'd like to focus on core bugs right now before refactoring the infrastructure of the project.

**Comment by vjeux** [comment]
I have another proposal for solving this problem: https://github.com/prettier/prettier/issues/1640. I'm going to close this one in favor of the other one. Thanks for the suggestion!
