### ISSUE TITLE
how set specific syntax Prettier ?

### ISSUE THREAD

**Issue by MedinaGitHub** [prettier/prettier#7698]
for example i have this sintaxis Hello.Loader.define('Cart', ['Util'], function(util) { })

and i want the same rules that "define"

so, pretti should read  Hello.Loader.define like define('Cart', ['Util'], function(util) { })

other example:

i need to this reading of "define" for this sintaxys Some.some.some.define({})

![image](https://user-images.githubusercontent.com/16387514/75694564-7b77a380-5c87-11ea-850d-b5344d127d76.png)

**Comment by sosukesuzuki** [comment]
Please follow issue template.
