### ISSUE TITLE
Flow parser outputs incorrect location with unicode characters

### ISSUE THREAD

**Issue by thymikee** [prettier/prettier#770]
It seems that using en-dash `–` and em-dash `—` in comments confuses flow parser and it removes newlines between 

Examples:

1.
```js
// @flow

// codes: 0 : ABC, 1 — DDD

const localFn = () => {};

export const fn = (state: Object) => state;

```
2.
```js
// @flow

/*
 * codes: 0 : ABC, 1 — DDD
 */

const localFn = () => {};

export const fn = (state: Object) => state;
```

Results of running `prettier --parser=flow` on these files:

1.
```js
// @flow

// codes: 0 : ABC, 1 — DDD
const localFn = () => {};
export const fn = (state: Object) => state;
```
2.
```js
// @flow

/*
 * codes: 0 : ABC, 1 — DDD
 */ const localFn = () => {};
export const fn = (state: Object) => state;

```

Tested on prettier v0.18

**Comment by vjeux** [comment]
This is a known issue, flow parser doesn't correctly deal with unicode characters and reports incorrect ranges. Because we use those to determine if we should preserve newlines, then they get messed up.

@mroch has been prototyping with a different tokenizer that supports unicode but I'm not sure what the status is.

**Comment by vjeux** [comment]
In the meantime, you can use the babylon parser, it has no known issues.

**Comment by thymikee** [comment]
Thanks! Feel free to close it if you like.

**Comment by lydell** [comment]
Here's a case where unicode characters cause unstable formatting with the flow parser:

```js
"ííííí";
let {a} = {a: 1, b: 2, c: 2}
```

[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5C%22%C3%AD%C3%AD%C3%AD%C3%AD%C3%AD%5C%22%3B%5Cnlet%20%7Ba%7D%20%3D%20%7Ba%3A%201%2C%20b%3A%202%2C%20c%3A%202%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A24%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D):

```js
"ííííí";
let { a } = {
  a: 1,
  b: 2,
  c: 2
};
```

[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5C%22%C3%AD%C3%AD%C3%AD%C3%AD%C3%AD%5C%22%3B%5Cnlet%20%7B%20a%20%7D%20%3D%20%7B%5Cn%20%20a%3A%201%2C%5Cn%20%20b%3A%202%2C%5Cn%20%20c%3A%202%5Cn%7D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A24%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D):

```js
"ííííí";
let {
  a
} = {
  a: 1,
  b: 2,
  c: 2
};
```
