### ISSUE TITLE
Prettier doens't respect range ignore in aspx

### ISSUE THREAD

**Issue by Lokdei** [prettier/prettier#7702]
Situation: 
- I'm using esbenp.prettier-vscode version 3.20.0
- I'm editing AcessDenied.aspx which is an aspx file for SharePoint
- The aspx file contains <%@ .... %> tags
- I surrounded the tags with a range ignore, but it seems to not work

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRGYDOMAhgTDtgHwA6UqAUgACOAEpxqpZhRwAVFtUJwAZqQAeAXh4gA6nABGABTYxj1OI204AciwC2FvCzBwtIALKkwBCIwjKYADoAZQALNjhDCFJYQL0jEzMLKwBBRkY4O30AGwBPN09vX38gsIiomJgAGhwANQpGUmgNAEYAVkCABi6umoBhAFdsmAGiDSg4AZgCFmyawwGcrwBpOFzZCABrBA0Adha4AE59Fxazo4AWACZDsCsBLhw+QRE0jKy8m3tXbUKfPwCIXCRAqsRSeDw2S8LDI0CSjBq9QIjWa7R63U6-SGIzGEymMzmOAWSzAq3WWx2+yOJzgZwOh2ut20Dye-CwuCUJHIlBodAYCAAJpxMLwoM8WIw8Eg+tB4LAcDLYAhTNlnHAABIQbICigASQFbkMqpcmu1FCSslIMGycCsBAGUBhbgyBAAbhRtKKcDhUGUQdFYEgAKJQSA6gUAGStFFmfG93vtjpgzoo7oI2jj8fgamT2kEABJxH5Ri5GEgAO7pKrOUuMAAiCHIAoA+k5zGRrbS2g8M1B4zgQ2G4O5iKEIAbtOqYHZsoPx7aQJnvfq3FH4ASAEI+SvmhRwS2d3vegD0otQx4lUsVcpgXBAVRAEDwsKgjGQoDY2+MRFfyBALFdaIBXvEB9BmMBthgYInDAGJqGQaYBjgB9QmnbIdFCaNJTVYIEEaMhXStXI-zAdIQJiF1TBmag7BYZBlFmDIHwAK0YNQt2cSDgm+KMJnoxjkJAVi1GCOCbQARQGCB4H47ImJAJxkQoP9UJnEDCEqHRSAFGBQmQFpOkxBT-jgHQZjwP8lBdd0QIARyk+BDB8PA3xQCVMAmOBwxAoh7NIEFqNo2T5PeUgEPtQTGigagJIcuBgsE1h9C0nS9KQK4H2mFhSChaKZTsIKUDoPiHwGDJ5H0VyGLkwTXSQ3UoB1WBgm8UhnxSRrghgXIbQSgBfPqgA)
```sh
--parser html
--print-width 100
```

**Input:**
```html
<!-- prettier-ignore-start -->
<%@ Register Tagprefix="WebPartPages" Namespace="Microsoft.SharePoint.WebPartPages" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> 
<%@ Assembly Name="Microsoft.SharePoint.ApplicationPages, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c"%> 
<!-- prettier-ignore-end -->

<asp:Content ContentPlaceHolderId="PlaceHolderPageTitle" runat="server">
  <SharePoint:EncodedLiteral
    runat="server"
    text="<%$Resources:wss,accessDenied_pagetitle15%>"
    EncodeMethod="HtmlEncode"
    Id="LiteralBrowserPageTitle"
  />
</asp:Content>
```

**Output:**
```html
<!-- prettier-ignore-start -->
<%@ Register Tagprefix="WebPartPages" Namespace="Microsoft.SharePoint.WebPartPages"
Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c"
%> <%@ Assembly Name="Microsoft.SharePoint.ApplicationPages, Version=15.0.0.0, Culture=neutral,
PublicKeyToken=71e9bce111e9429c"%>
<!-- prettier-ignore-end -->

<asp:Content ContentPlaceHolderId="PlaceHolderPageTitle" runat="server">
  <SharePoint:EncodedLiteral
    runat="server"
    text="<%$Resources:wss,accessDenied_pagetitle15%>"
    EncodeMethod="HtmlEncode"
    Id="LiteralBrowserPageTitle"
  />
</asp:Content>

```

**Expected behavior:**
In this case I expected the input to match the output. Essentially not formatting anything within the range ignore. 

Is this not supported?

**Comment by evilebottnawi** [comment]
It is expected and doesn't supported, I recommend to create plugin (you need use ASP parser), because it is potential unsafe and can break code.

Also `prettier-ignore-start` and `prettier-ignore-end` comments doesn't work in HTML right now, please look at https://github.com/prettier/prettier/issues/5508, you can send a PR and help us

**Comment by Lokdei** [comment]
Thank you for your quick reply

As for the ASP Parser:
- I would have to do it in the weekend(s)
-  I don't know if I'm skilled enough to create one. Do you happen to know where I could get started ?

**Comment by evilebottnawi** [comment]
> I don't know if I'm skilled enough to create one. Do you happen to know where I could get started ?

Sorry, I am not familiar with ASP, you can ask that on stackoverflow
