### ISSUE TITLE
Importing parsers dynamically with import() in browsers

### ISSUE THREAD

**Issue by SebastiaanYN** [prettier/prettier#7704]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: Browser API

I'm trying to do something similar to the prettier playground, but I can't figure out how to import parsers dynamically using `import()`.

The prettier playground uses `importScripts` in a webworker, which requires the parsers synchronously when they're needed.
```js
var parsers = {
  // JS - Babel
  get babel() {
    importScriptOnce("lib/parser-babylon.js");
    return prettierPlugins.babylon.parsers.babel;
  },

...

var plugins = [{ parsers: parsers }];
options.plugins = plugins;
prettier.format(text, options);
```

I'm trying to do a similar thing, but because `import()` is async this approach won't work. I considered importing the dependencies of a parser manually, but this won't work well for languages like Markdown as they can depend on a lot, and they might not all be needed. Is there a proper way to asynchronously import the parsers when they're required?

**Comment by thorn0** [comment]
No, `prettier.format` is a synchronous function. Load all the parsers you need before calling it.
