### ISSUE TITLE
Option to insert empty line between adjacent JSX tags

### ISSUE THREAD

**Issue by flaviolivolsi** [prettier/prettier#7708]
I'd like to know whether there's an option that allows to format the code inserting an empty line between adjacent JSX tags in a similar fashion:

**Input:**
```jsx
<div>
  <h1>Foo</h1>
  <p>Bar</p>
</div>
```

**Output:**
```jsx
<div>
  <h1>Foo</h1>

  <p>Bar</p>
</div>
```

Thanks.

**Comment by evilebottnawi** [comment]
No option and we don't want new options, please read https://prettier.io/docs/en/option-philosophy.html

You can create eslint plugin for that, it is out of scope prettier.
