### ISSUE TITLE
Inconsistent ending for type

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#7719]
I believe that the one we should have is what flow is outputting. Does someone have more context around why there's a difference here?

**Flow**
```sh
--parser babel
```

```tsx
export type Block = {
  format: BlockFormat,
  lang: BlockLanguage
}
```

**Typescript**
```sh
--parser typescript
```

```tsx
type Block = {
  format: BlockFormat;
  lang: BlockLanguage;
};
```

**Comment by bolinfest** [comment]
@bradzacher I feel like I am going to lose this battle, but nevertheless, I favor the consistency of "objects looking like objects" over "objects looking like `interface`". In the case of `type Obj`, using `;` within the curlies makes it look like a statement, which it is not. So from my perspective, the status quo *is* the inconsistency!

**Comment by sosukesuzuki** [comment]
As mentioned in https://github.com/prettier/prettier/issues/6655#issuecomment-582929713, the official guide of TS uses semicolons.(The comment mentioned about only `interface`, but the guide also uses semicolon for Type Alias(https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-aliases))

**Comment by thorn0** [comment]
Object types in TS *are* anonymous interfaces. They can contain everything named interface can, e.g. method signatures, which look really strange with commas:
```ts
let a: {
    foo(): number,
    bar(baz: string): string,
    (): void,
};
```

**Comment by bradzacher** [comment]
interestingly, I just found out that prettier actually treats types and interfaces _in flow_ differently:

```ts
interface Test {
  semi: string;
  comma: string,
}

type Test = {
  semi: string;
  comma: string,
};
```

is formatted to the following with `babel`/`babel-flow`:
```ts
interface Test {
  semi: string;
  comma: string;
}

type Test = {
  semi: string,
  comma: string,
};
```

Whereas it's formatted to the following with `typescript`:
```ts
interface Test {
  semi: string;
  comma: string;
}

type Test = {
  semi: string;
  comma: string;
};
```

[repl](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgBU4BnGQ4AHSkMLLgFtUkGZN0BzAblvshMmuNhU5QuAGloBfWrRgBPAA5FSFQgF4q-Bs1btxvXYOGiO3aVBl8oISSAjKYqaGWShcmTBADuABS8EdxRcADcIVAATexAAI0x8AGs4GABlZXxuZA4AVzgHAAsYJgAbAHVC1HgyTII04OrUMOrFZHAydwd0RkwYf0SuYWQ8UsYHACsyAA8AIUSwFPTcJjgAGXQ4EdwxgpAp6bTuUrgARVyIeG3dh0zMXva43Di4UtjlcRhy6JhC5AAOAAMtx8jHKiWU7Q+5CwYS2DgAjhd4AMnCEQLgyABaKBwOBRfGxTBwJGoYkDXBDXDXcYgRgsHKYfIOMjHM7IrZIUa0mDPb5RX7IABMDg4uFQpW4AGEIEJqaFSm8HLlGMRniFuXswvkAJJQAmwNJgTjOACC+rSShONLgMhkQA)

**Comment by seahindeniz** [comment]
@thorn0  Please see this [@typescript-eslint/member-delimiter-style](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-delimiter-style.md) 

```json5
{
  "rules": {
    "@typescript-eslint/member-delimiter-style": [
      "error",
      {
        "multiline": {
          "delimiter": "comma",
          "requireLast": true
        },
        "singleline": {
          "delimiter": "comma",
          "requireLast": true
        }
      }
    ]
  }
}

```

Having this configuration allows eslint to use comma instead of semicolon

Eslint before the rule
![image](https://user-images.githubusercontent.com/5789670/80951842-4ca1b900-8e01-11ea-8332-e1bed8a1448c.png)

Eslint after adding the rule
![image](https://user-images.githubusercontent.com/5789670/80951870-5e835c00-8e01-11ea-8808-32f88c005649.png)

**Comment by thorn0** [comment]
@seahindeniz And that's what that page says: "Semicolon style (**default, preferred in TypeScript**)". To avoid conflicts with Prettier, such formatting-related rules should be disabled. See https://prettier.io/docs/en/integrating-with-linters.html#eslint

----

I'm closing this issue, see the justification above: https://github.com/prettier/prettier/issues/7719#issuecomment-595497709, https://github.com/prettier/prettier/issues/7719#issuecomment-595654979

**Comment by seahindeniz** [comment]
@thorn0 yes, I have seen that before but there is also no restriction on the Typescript that enforces to use semicolons. The comma support has added in Typescript 1.5 see [#1971](https://github.com/microsoft/TypeScript/pull/1971)
Can't we can agree semicolon usage shouldn't be also enforced by Prettier and should be an optional choice?
Like default as semicolon and user can change delimiter as comma?

This is kind of look like the argument between tab and 2 or 4 spaces usage, isn't it? :confused:

**Comment by thorn0** [comment]
@seahindeniz I guess you've seen the option philosophy page too, right? This isn't going to happen. Tab width is a much more divisive issue than this.

**Comment by seahindeniz** [comment]
I didn't read that before and now did.

> Everybody wants to add just a tiny piece of configuration to satisfy their use case. As a result we end up with inconsistently designed tools, with unexpected combinations that don’t work correctly, with bugs and regressions that, when fixed in one configuration, break something else with another configuration.

I can say and confirm that this isn't directly related to my use case. I'm simply referring is that Typescript has support for comma delimiter since 2015 and there is no enforcement that restricts us to use semicolon in type/interface definitions. 

Btw. the tab width example is just to show that you there is no restriction between both usages, therefore, there shouldn't be for delimiters.
