### ISSUE TITLE
Empty objects shouldn't be split out

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#772]
```js
this.__mockMetaDataCache[modulePath] = (this._moduleMocker.getMetadata({}): any);
```

outputs

```js
this.__mockMetaDataCache[modulePath] = (this._moduleMocker.getMetadata({
}): any);
```

but should

```js
this.__mockMetaDataCache[modulePath] = (this._moduleMocker.getMetadata(
  {}
): any);
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22this.__mockMetaDataCache%5BmodulePath%5D%20%3D%20(this._moduleMocker.getMetadata(%7B%7D)%3A%20any)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
@thymikee if I remove the break inside of `{}` it then breaks like this:

```js
this.__mockMetaDataCache[
  modulePath
] = (this._moduleMocker.getMetadata({}): any);
```

Do you think that it is an improvement?

I'm honestly not sure what is the best way to break this expression. The way prettier does it today doesn't seem crazy. This is one of those cases where it barely fits by one character and there's no ideal break placements.

**Comment by vjeux** [comment]
Here's the fix for what I mentioned above if you are curious and want to play with it.

```diff
diff --git a/src/printer.js b/src/printer.js
index be633e2..1df8ca1 100644
--- a/src/printer.js
+++ b/src/printer.js
@@ -685,6 +685,9 @@ function genericPrintNoParens(path, options, print) {
       );

       if (props.length === 0) {
+        if (!n.comments) {
+          return "{}";
+        }
         return group(
           concat([
             "{",
```

**Comment by thymikee** [comment]
I think this is ok, certainly better than it is now.
Just curious – would something like this be possible? I'll try to find some time tomorrow to play with it, hopefully!
```js
this.__mockMetaDataCache[modulePath] = (
  this._moduleMocker.getMetadata({}): any
);
```

**Comment by vjeux** [comment]
Oh yeah, we can do this!

https://github.com/prettier/prettier/blob/master/src/printer.js#L1662

Just add `indent(options.printWidth, ...)` and `softline` inside of this block and it should do what you suggest. I think it's a good solution.

**Comment by thymikee** [comment]
I've tried something like this (similar to what `printFunctionParams` does):

```js
    case "TypeCastExpression":
      return concat([
        "(",
        indent(
          options.tabWidth,
          concat([
            softline,
            path.call(print, "expression"),
            path.call(print, "typeAnnotation"),
          ])
        ),
        ifBreak(shouldPrintComma(options, "all") ? "," : ""),
        softline,
        ")",
      ])
```
But it always breaks lines. 
Example diff from snapshot:
```diff
-(42: Obj_Prop_x);
+(
+  42: Obj_Prop_x
+);
```
Thought `softline` will break the line only when needed, but I must miss something.
Appreaciate any help on this (btw, is there any documentation expalining how internals work?)

**Comment by vjeux** [comment]
Docs: https://github.com/prettier/prettier/blob/master/commands.md

You need to add a `group()` around where you want things to be able to break

**Comment by vjeux** [comment]
If you don't put a group inside, then the entire expression is not going to fit so all the softline are going to be part of the larger group and be printed.

**Comment by jlongster** [comment]
I ran into this code today which breaks similarly:

```js
      navigation = this._childNavigationProps[
        scene.key
      ] = addNavigationHelpers({
        ...this.props.navigation,
        state: scene.route
      });
```

whereas somethings like this looks better (although I'm not really sure of the best way to format it):

```js
      navigation = this._childNavigationProps[scene.key] =
        addNavigationHelpers({
          ...this.props.navigation,
          state: scene.route
        });
```

Not a huge deal, just though I'd bring up that we break on the brackets in these kinds of assignments expressions which feels a little weird.

**Comment by vjeux** [comment]
Breaking after the `=` is often requested but I'm not sure how it's going to play with the rest of the rules. I fear that it's going to be really inconsistent.

**Comment by vjeux** [comment]
They are not split out anymore.
