### ISSUE TITLE
Prettier adds an extra space to rendered Vue markup (when there's an <a> tag in parens)

### ISSUE THREAD

**Issue by dylnclrk** [prettier/prettier#7720]
Problem: When I have a link that's within parentheses, and it's re-formatted by Prettier, an extra space is added after the parens.

Am I missing something?

----------

⚠️ See [this comment](https://github.com/prettier/prettier/issues/7720#issuecomment-595506006), below, for clarification (this original example is misleading, as it makes the issue appear to be with JSX, instead of vue)

----------
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEADgE46wDqAFjvAM6ECGYcAFAJT7AA6U++xcGOmK8WPPhIkAeACY4AbgD5xk1VMoBmRQGEGvAJL4wlPQHM4+ALYBPfA0KEIZGJYQwA-FID0m5b1WSUoR+AQEAggBGtBAANujwMdYAhPhwlgw4MfjotPgsUgz4lAKoALxcIOmZMBBIlHAxhAACcAAeDJaEMXAAdJCWFYr1jS3tnd19EJbeDIpsPSqh+N7Bi2peckoqbDwAviAANCAQhLjQtMigDMTEEADuAArXCBcoDPJOMocgEcRMANaCADKjDAZFMyBgxHQcCOlBcMSoNDg9CYcCBLxoCho1mQ4FoFyOZFocGIMAef1M6WQqAYMRJRwAVrRWgAhP5gQEwIEdOAAGTIcBpdIZIGZrSB4O6AEV0BB4ML6bCQIxiCTiHiIgwIg1viRnOQcDIYJRkAAOAAMRxIEBJ5D+hDxJBRpPkQqOAEc5fAKSdXiAGLQALRQOBwGTh74CL04AQUhhUhiK0Ukyw4SHQ5W0KVwWXyoVIWlKo4wbWG42mpAAJhLf0y4O0U2pKCg0HdIBycAAKtrXkXRfIYfooBHYECwKRTmER0CYNZusm4LtdkA)
```sh
--parser babel
```

**Input:**
```jsx
function printWhitespace() {
  return (
        <div>
          <h3>Can I change my appointment?</h3>
          <p>
            Absolutely! email us (<a href="mailto:help@example.com">help@example.com</a>).
          </p>
        </div>
  )
}
```

**Output:**
```jsx
function printWhitespace() {
  return (
    <div>
      <h3>Can I change my appointment?</h3>
      <p>
        Absolutely! email us (
        <a href="mailto:help@example.com">help@example.com</a>).
      </p>
    </div>
  );
}

```

**Expected behavior:**

When this markup is rendered, I expect the paragraph to read 
`Absolutely! email us (help@example.com).` 

But I see an extra space: 
`Absolutely! email us ( help@example.com).` 

I.e.,
```diff
- Absolutely! email us (help@example.com).
+ Absolutely! email us ( help@example.com).
```

This could be accomplished with the Prettier output:

```
function printWhitespace() {
  return (
    <div>
      <h3>Can I change my appointment?</h3>
      <p>
        Absolutely! email us
        (<a href="mailto:help@example.com">help@example.com</a>).
      </p>
    </div>
  );
}
```

Or,
```
function printWhitespace() {
  return (
    <div>
      <h3>Can I change my appointment?</h3>
      <p>
        Absolutely! email us (<!--
        --><a href="mailto:help@example.com">help@example.com</a>).
      </p>
    </div>
  );
}
```

**Comment by dylnclrk** [comment]
@thorn0 Ah, I guess my example was misleading, I changed it in to JSX without thinking. 

In this case it's happening with a `.vue` file (just inherited a Vue codebase, and I don't have much/any experience with Vue)

Now I understand why I've never seen this before, hah..

**Comment by dylnclrk** [comment]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQWUWoAmAlgG4nlWuoAWAzIQMJ7kBJMmHb8A5nDIYAnmTxYsEOrAwIYAflQB6Ls1Zsse-awCCAIwDOEHAFd4OaQEIyADxeu3bjx8-fP-3wD3AApUPDJ2ACc4ADMAXmIQDDw6HBgIJHY4HCwAATgXPGwcOAA6SAxEwiyc-MLisortPEIASlLSY0ptQ07jbXomUm1MXAI4QhAAGhAILBg6aAtkUDxIyIgAdwAFNYRllDwGJRppkDNIvDAAazgYAGUsK+UxZBhImzgZ9hgMHAB1dh0eAWJ5gOD3fbAxjA6TIcAWZYzZQWOCRGDbS5iZLIGJ4HComYAKwsLgAQpcbnd7kU4AAZZRwXH4wkgEkue4vEoARRsEHgzIJXxAT0iqMi8LMeDM0hw0DOWEiyhg-zoNBg7GQAA4AAwzRUQVH-S5YeGKuDihhMmYARz58ExcwOIDwFgAtFA4HAaN6ztE7XRopi8Ni8ILWaiMHQ3h9hRYuXBefymUg8UKZjBpar1ZqkAAmDOXVIvHgQDA4lBQaDWkA2VEAFWlBzTrIYnwEUB9sHuYCV8xMnfuMFlKZbcAAvuOgA)
```sh
--parser babylon
```

**Input:**
```jsx
<template>
        <div>
          <h3>Can I change my appointment?</h3>
          <p>
            Absolutely! xx xxxxx xx xxxxx xx xxxxxxxxxx xxxxxx (<a href="mailto:help@example.com">help@example.com</a>).
          </p>
        </div>
</template>
```

**Output:**
```jsx
<template>
  <div>
    <h3>Can I change my appointment?</h3>
    <p>
      Absolutely! xx xxxxx xx xxxxx xx xxxxxxxxxx xxxxxx (
      <a href="mailto:help@example.com">help@example.com</a>).
    </p>
  </div>
</template>;

```

**Comment by sosukesuzuki** [comment]
Your output was formatted as flow. Below is what was formatted as a vue.
**Output:**
[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQWUWoAmAlgG4nlWuoAWAzIQMJ7kBJMmHb8A5nDIYAnmTxYsEOrAwIYAflQB6Ls1Zsse-awCCAIwDOEHAFd4OaQEIyADxeu3bjx8-fP-3wD3AApUPDJ2ACc4ADMAXmIQDDw6HBgIJHY4HCwAATgXPGwcOAA6SAxEwiyc-MLisortPEIASlLSY0ptQ07jbXomUm1MXAI4QhAAGhAILBg6aAtkUDxIyIgAdwAFNYRllDwGJRppkDNIvDAAazgYAGUsK+UxZBhImzgZ9hgMHAB1dh0eAWJ5gOD3fbAxjA6TIcAWZYzZQWOCRGDbS5iZLIGJ4HComYAKwsLgAQpcbnd7kU4AAZZRwXH4wkgEkue4vEoARRsEHgzIJXxAT0iqMi8IYnzOWEiyhg-zoNBg7GQAA4AAwzWUQVH-S5YeGyuDihhMmYARz58ExcwOIDwFgAtFA4HAaO6ztErXRopi8Ni8ILWaiMHQ3h9hRYuXBefymUg8UKZjA8GZFcrVUgAEwpy6pF48CAYHEoKDQc0gGyogAqaYOSdZUrgAigHtg9zAcvmJjb9xg0hKwbgAF8R0A)
```vue
<template>
  <div>
    <h3>Can I change my appointment?</h3>
    <p>
      Absolutely! xx xxxxx xx xxxxx xx xxxxxxxxxx xxxxxx (<a
        href="mailto:help@example.com"
        >help@example.com</a
      >).
    </p>
  </div>
</template>
```

**Comment by thorn0** [comment]
@dylnclrk Is the problem solved?
