### ISSUE TITLE
Broken nestled jsdoc comments for overloaded functions

### ISSUE THREAD

**Issue by grassator** [prettier/prettier#7724]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAOiAEICGATqQNzFQMD0AVCw5i5gALwC2ABwA2FeJgAqHLtwHUKfTMHEBPAXAC+mGKrhSesqvMXjNANwpCArrqiceVODEtVbwAGoXr6qU1btb0gZGSjqa2mp63A5OLooeVho+DNiWUGAwAJbQmOYJABThcAA0OZ5wAJSKHJgZ2Jh51ADmlnwIMGgAdEIIjTAAFoQERABMlcDVmJjRzrZQcADumADC0GDRcPHWBToludbl9LaYmnBCaHBVR5PTsXOLm3DbagfV3lBvIEUgEAKZ6MigahUCDzAAK1AQaGQIAopggGQAJp8QAAjQxgADWjgAyrIwBkoI1kDAqNYvn0YHwhAB1PoZeBoPFwbGQ+kZUz05TQsBoKFfAnnKgwUGGRp8CjIbAWc5fABWaAAHmR0ViYNj5HAADIEuCS6XFEDyhXYgmNboARUsEHgerOBoMguhKIoKNOyIEVAJMGpiP6yAAHAAGL4eiDnamGATQj1wQWmXVfACOVvgIp+UJQFDQAFo5nAEfnkQ5kxkHCKKGKJUgpXavuc+BliaSDWhTRaU7rq-qvjAXT6EX6kMMe4YMkJTSs+OLoVBoAmQJZzuIXRmazKQKZrABJKAF2DYtYZX4AQV32O03Vt53U6iAA)
```sh
--parser babel
```

**Input:**
```jsx
const foo = "Bar";

/**
 * @template T
 * @param {Type} type
 * @param {T} value
 * @return {Value}
 *//**
 * @param {Type} type
 * @return {Value}
 */
function value(type, value) {
  if (arguments.length === 2) {
    return new ConcreteValue(type, value);
  } else {
    return new Value(type);
  }
}

```

**Output:**
```jsx
const foo = "Bar";
/**
 * @param {Type} type
 * @return {Value}
 */

/**
 * @template T
 * @param {Type} type
 * @param {T} value
 * @return {Value}
 */ function value(type, value) {
  if (arguments.length === 2) {
    return new ConcreteValue(type, value);
  } else {
    return new Value(type);
  }
}

```

**Expected behavior:**
Output identical to input.

**Comment by evilebottnawi** [comment]
Thanks

**Comment by thorn0** [comment]
@grassator Is this syntax documented somewhere?

**Comment by grassator** [comment]
@thorn0 I have found the information is [this jsdoc issue](https://github.com/jsdoc/jsdoc/issues/1017). I didn't realize right away that these are just two comments going one after each other and if I add a line break, prettier leaves it alone. I'm not sure it works with JSDoc itself though (I don't have it setup):

```js
/**
 * @template T
 * @param {Type} type
 * @param {T} value
 * @return {Value}
 */
/**
 * @param {Type} type
 * @return {Value}
 */
function value(type, value) {
  if (arguments.length === 2) {
    return new ConcreteValue(type, value);
  } else {
    return new Value(type);
  }
}
```

I also though that TypesScript (which is my use case) would correctly parse it, but apparently not.

**Comment by thorn0** [comment]
Yes, TS doesn't support this syntax.

**Comment by thw0rted** [comment]
TS does not support it but [`tsd-jsdoc` does](https://github.com/englercj/tsd-jsdoc/issues/30), so this is breaking a live process today.  JSDoc does parse it correctly as demonstrated in their issue, linked above.
