### ISSUE TITLE
Typescript optional chaining opertator in prettier@1.15.3

### ISSUE THREAD

**Issue by yarinr** [prettier/prettier#7730]
My project is running on Typescript@3.7.5, and I'm using Prettier@1.15.3.

Prettier refuses to format .ts files if the optional chaining operator is present.

I prefer to not update the prettier version, since I wish to avoid another huge diff of formatting that'll ruin my source control history.

How should I go about it? Is there any way to let me use the optional chaining operator without having to update prettier in a way that will affect current formatting? or do I just HAVE TO update?

Would love to hear any form of input or advice, thanks in advance!

**Comment by j-f1** [comment]
I don’t think we currently support versions of Prettier other than the most recent one. Therefore, there is no way for you to use new language features with an old version of Prettier. Sorry we couldn’t be more helpful!

I’m curious, though: what changes to Prettier are causing a huge diff for you?
