### ISSUE TITLE
html wrapping

### ISSUE THREAD

**Issue by gkhndev** [prettier/prettier#7738]
Hi,

why when i save it happens like below? i just want to see in a row

    "<label className="test" htmlFor="name">{labelText}</label>"

       <label className="test" htmlFor="name">
        {labelText}
     </label>

{
  "workbench.colorTheme": "One Dark Pro",
  "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "workbench.iconTheme": "vscode-icons",
  "window.zoomLevel": 0.5,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "prettier.printWidth": 500  
}

**Comment by evilebottnawi** [comment]
Please format your issue using an issue template, thanks

**Comment by gkhndev** [comment]
"{labelText} "why this part goes down when saved code

**Comment by evilebottnawi** [comment]
Please use the issue template
