### ISSUE TITLE
!() indentation

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#774]
Right now

```js
const anyTestFailures = !(
  aggregatedResults.numFailedTests === 0 &&
  aggregatedResults.numRuntimeErrorTestSuites === 0
);
```

turns into

```js
const anyTestFailures = !(aggregatedResults.numFailedTests === 0 &&
  aggregatedResults.numRuntimeErrorTestSuites === 0);
```

but the original version looks better. We may want to tweak it.

**Comment by vjeux** [comment]
This one is tricky to implement because the parenthesis are added part of the boolean expression with needsParen and not controlled by the unary expression.

But we could remove the needsParen and handle it inside of the unary.

**Comment by vjeux** [comment]
We should fix this!

**Comment by lemon79** [comment]
i will look into this after i finish the static comment bug

**Comment by vjeux** [comment]
Awesome!

**Comment by lemon79** [comment]
@vjeux There is a flow test in test\flow\intersection\pred.js that expects the brackets to be with the arguments. I really want to separate them into different lines but then this test has to be changed. Singular arguments are in the same line as the brackets. 

function hasObjectMode_ok(options: DuplexStreamOptions): boolean {
  return !!(options.objectMode
    || options.readableObjectMode
    || options.writableObjectMode);
}

**Comment by vjeux** [comment]
Note that the inputs of the tests are not the "source of truth". They are just random pieces of code that were written. If it changes and the output looks better, then it is okay.

**Comment by lemon79** [comment]
@vjeux opening more pull requests soon
