### ISSUE TITLE
Problem with parameters in Svelte code

### ISSUE THREAD

**Issue by fkereki** [prettier/prettier#7762]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiEWJAK6zUB8lUuuGO+xZVNdCIxgxMMAnGq5W7DpwAOzAIKDhqAPSK2cuagAiATyhEAtpjAAVCBAKj5+aPFjlgAEhgAKE3DJEA5nAAlLgAPiG4AOQRAL4yOjqoAJKQ7ObQLsC4xt5IkZhQAGYQAPpC4vlwEbjR0bjqcfEahtnmVjZ2DRpY2DJdOHFsqCRgAE6Y8jAN6gBUuABSRNhEAMqj4zC4fhA+uAAWcCNwAHQnuNPqg+rDYxMyIAA0IBATmNAkyKBEIyMQAO4ACl8EO8UIsIJh0A8QAAjEa0ADWcBgy3ktHyfmQMBG9Dgj12MBMBAA6rsxD5UWA4MtgWIcGIDMhwGQofkSAcYP84X4TERkAUiAQ2Y8AFYkAAeACE4WBEcjTHAADIVPkCoUgUVi5boiQARXoEHgKsFuJAqJGbJGjJM6DFUPkY1gRIhMF2yAAHAAGR72iBsolw+SM+0+A7YOBQgCO+vgnOeIJoJAAtFA4HB0GmoYco5hDpz-DyjWq2WZMdiTSRtXA9Qbw0h+cbHjAiNCnegXcgAEyNuGYAjogDCEBMBZQUGg4ce9DZFmbIPrauwOMSUHTsFWNxgShXyxgBgkhbgNSAA)
```sh
--parser mdx
```

**Input:**
```mdx
<div class="account">
  <div class="accounttitle" >
    <p>Account</p>
      <DynamicTooltip content={$t(message) || ''}>
        <Icon icon={{ name: 'info_outline' }} />
      </DynamicTooltip>
  </div>
</div>
 
<script>
  /* JavaScript goes here... */
</script>

```

**Output:**
```mdx
SyntaxError: Unexpected closing tag "DynamicTooltip". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (6:7)
  4 |       <DynamicTooltip content={$t(message) || ''}>
  5 |         <Icon icon={{ name: 'info_outline' }} />
> 6 |       </DynamicTooltip>
    |       ^
  7 |   </div>
  8 | </div>
  9 |  
```

**Expected behavior:**
The code should be formatted. Incidentally, if we remove    `|| ''`   in line 4, the code is formatted.

**Comment by thorn0** [comment]
Prettier doesn't support Svelte OOTB, but there exists a plugin for it: https://github.com/UnwrittenFun/prettier-plugin-svelte

Also Svelte has nothing to do with MDX (as far as I know), so this issue is invalid.
