### ISSUE TITLE
Extending shared config in JSON

### ISSUE THREAD

**Issue by snebjorn** [prettier/prettier#7763]
Prettier already support [sharing-configurations](https://prettier.io/docs/en/configuration.html#sharing-configurations).
However it's lacking support for extending shared configurations.

I'm thinking it could work like this

```jsonc
// .prettierrc.json
{
  "$schema": "http://json.schemastore.org/prettierrc",
  "extends": "@myorg/prettier-config", // shared config
  "printWidth": 120 // override
}

```

**Comment by j-f1** [comment]
I think we decided not to implement this because Prettier has so few options it doesn’t really make sense to want to change one or two things about a config rather than just copy-pasting it.

**Comment by snebjorn** [comment]
Simplicity is always nice.

But I think there's value in the `extends` feature. As you can have an organization wide config, that can be changed, which then can be opt'ed out of on a per project. Possibly with a reason attached. Not sure if .prettierrc.json supports comments.

Example

```jsonc
// .prettierrc.json
{
  "$schema": "http://json.schemastore.org/prettierrc",
  "extends": "@myorg/prettier-config", // shared config
  "printWidth": 180 // @myorg default is simply to narrow when working with X
}
```

**Comment by thorn0** [comment]
As it's written in [the docs](https://prettier.io/docs/en/configuration.html#sharing-configurations), this can be done in a `.prettierrc.js` file:
```js
module.exports = {
  ...require("@company/prettier-config"),
  semi: false,
};
```

**Comment by snebjorn** [comment]
That does solve the issue. But we'll be losing the sweet IDE help coming from `"$schema": "http://json.schemastore.org/prettierrc",`

**Comment by yzStrive** [comment]
> As it's written in [the docs](https://prettier.io/docs/en/configuration.html#sharing-configurations), this can be done in a `.prettierrc.js` file:
> 
> ```js
> module.exports = {
>   ...require("@company/prettier-config"),
>   semi: false,
> };
> ```
> 
> @snebjorn Does this option not work for you for some reason?

But it is not supported in the vscode plug-in , now only can run shell  to format code
https://github.com/prettier/prettier-vscode/issues/1516

**Comment by fisker** [comment]
It works for me. There must be something wrong.

**Comment by yzStrive** [comment]
need reopen vscode ,and then it works
@fisker

**Comment by Zryru** [comment]
> I think we decided not to implement this because Prettier has so few options it doesn’t really make sense to want to change one or two things about a config rather than just copy-pasting it.

Copy and paste is not an option when you want to maintain a huge organisation, if we decide for a change, instead of a npm install update, it would be "copy-pasting" over so many repositories which may not even be possible to get someone to go over ALL projects.

**Comment by seahindeniz** [comment]
> That does solve the issue. But we'll be losing the sweet IDE help coming from `"$schema": "http://json.schemastore.org/prettierrc",`

I think you can use JSDoc over your config object to gain the IntelliSense power if you have Prettier as a NPM dependency on your project
![image](https://user-images.githubusercontent.com/5789670/119642046-fdbb2d00-be22-11eb-874c-69ccd8839ebd.png)

However, I'm also a fan of using a JSON file inside a Typescript project. I don't like to use JS file and I rather go with a TS config file too.
Extending a main JSON file that is located in the root directory of a monolith project across packages even sub packages is an example case for this issue.

**Comment by haotang-dayone** [comment]
This is how I extended Google's gts prettier config.

**prettier.config.js**
`module.exports = require('./node_modules/gts/.prettierrc.json');`

**Comment by haotangio** [comment]
This is how I extended Google's gts prettier config and make it work.

**prettier.config.js**
`module.exports = require('./node_modules/gts/.prettierrc.json');`

**Comment by marcoreni** [comment]
I think there may be some scenarios where the `require()` solution it's not ideal.
In our organization we have a basic, and shared, prettier configuration with a set of plugins. 
In some specific projects we'd like to be able to add a specific plugin.

The suggested way of sharing configurations:

```js
module.exports = {
  ...require('base-prettier-conf'),
  plugins: [
    require('custom-prettier-plugin'),
  ]
}
```

would overwrite the `plugins` object and remove the standard plugins.

A workaround may be:

```js
const baseConf = require('base-prettier-conf');
module.exports = {
  ...baseConf,
  plugins: [
    ...baseConf.plugins,
    require('custom-prettier-plugin'),
  ]
}
```
or some other sort of merging, but an end-user may forget to do this, so having this kind of behavior on prettier itself would definitely be better.

**Comment by maylortaylor** [comment]
> As it's written in [the docs](https://prettier.io/docs/en/configuration.html#sharing-configurations), this can be done in a `.prettierrc.js` file:
> 
> ```js
> module.exports = {
>   ...require("@company/prettier-config"),
>   semi: false,
> };
> ```
> 
> @snebjorn Does this option not work for you for some reason?

I like this option but I think having a way to do this in `.prettierrc.json` or even `.prettierrc.yaml` would be beneficial.

**Comment by maylortaylor** [comment]
> This is how I extended Google's gts prettier config and make it work.
> 
> **prettier.config.js** `module.exports = require('./node_modules/gts/.prettierrc.json');`

My company does this pattern. We event can override the `Google gts` prettier config which is nice. But we wish this was possible in the `prettierrc.json` format.

`
module.exports = {
  ...require('gts/.prettierrc.json'),

  printWidth: 100, // override
}
`

**Comment by sosukesuzuki** [comment]
@antongolub Let's discuss here.

Implementing a new dependency resolution mechanism such as `extends` increases maintenance costs excessively. If we use `.prettierrc.js`, we can use Node.js' module resolution mechanism as is. For a small team like ours, that's preferable.

**Comment by antongolub** [comment]
> increases maintenance costs excessively

That's true, I completely agree. And therefore, I propose not to expand the code base with this utility, but to use the existing solutions:
* [@yargs/helpers #applyExtends](https://github.com/yargs/yargs/blob/main/lib/utils/apply-extends.ts)
* @topoconfig/extends

<sup>And I was quite surprised when I saw that you [dropped cosmiconfig](https://github.com/prettier/prettier/issues/15506)</sup>

**Comment by sosukesuzuki** [comment]
Even if we use a library, if it's user-facing feature, we need to be concerned with its implementation.

If Prettier currently did not offer the ability to inherit settings at all, we might have considered adding `extends`. However, since it can be achieved with `.prettierrc.js`, I do not want to add new feature.

@fisker What do you think?

**Comment by antongolub** [comment]
> it can be achieved with .prettierrc.js
Definitelly yes, but we also have to partially transfer the business logic to the configuration layer.

```js
{
  ...baseConf,
  plugins: [
    ...baseConf.plugins,
    require('custom-prettier-plugin'),
  ],
  overrides: [
     ...baseConf,
     {
      "files": "*.test.js",
      "options": {
        "semi": true
      }
    }
  ]
}
```

vs

```json
{
  "extends": "'custom-prettier-plugin'",
  "overrides": [{
    "files": "*.test.js",
      "options": {
        "semi": true
      }
  }]
}
```

**Comment by fisker** [comment]
@sosukesuzuki I'm on the "NOT support extends" side, https://github.com/prettier/prettier/issues/7763#issuecomment-598893838 make sense to me.

**Comment by sosukesuzuki** [comment]
I understand the motivation behind the need for this feature. This is a trade-off issue. However, the two currently active maintainers, myself and fisker, do not support this feature. I am closing this issue for now.
