### ISSUE TITLE
Wrong indentation when using structured mocha describe

### ISSUE THREAD

**Issue by saarmae** [prettier/prettier#7771]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoByABzhgAIFUyJdYMSAaKogSioF4A+K4AB0ogmOix5CpVBADmNKHQZNW7LnwHDRo8TgLESAcQCiAFSoB6GbItJcqVdjgBHAK64npAHRW5GC7KUALTWXvAYMCQcHADcWjA6mHpSRmaW1sxsTm4eBj4ZAcEZYZiR0XEiMAC+HCzxupIGYACG1LT0jDCZajz8QpWJEvqkJuYWLTC29o4u7p4kPhP+gTBBEyURUbHaCQkDYkmNI2njrd3Zc3mnXYWrSxtl25U1dZUNw6ljALaUzTM58x8KyCPxgzQeWwqNQqIBYIAgZBguGgGGQoGa2GwEAA7gAFDEIVEoZoANwYqFhIHw2GaYAA1pQAMpkWmMWTIGDYVxwOEACxgXwANgB1Xm4cIssBwRmE8W4EnigCeyHAGFRcMYGDg2BguJpsi+zWQADNmoKtXCAFYYAAeACEafSmc0fgAZRhwE1mi0ga02xlswVwACKrgg8C95p5IBZ2C12BV+GahEFlLIeFgwvsMF5yAAjAAmAAMcPTEC1wppZBV6cw2pJnrhbnDcD1CKJIGaGCCUDgcHQFLhF1yeuaBqNSFNUbhWq+uA5XOjGEDIbDEcn3ujYPwWdQOeQABY4ZzmrhBWyAMIQL6GlVQaCNkCuLWmZNEzncuEk7kASUUCBgRk9ERABBRRGRgRUg0jLUqiqIA)

**Input:**
```jsx
describe('pet endpoints', () => {
	describe('dog endpoints', () => {
		describe('GET /dog/:id', require('./dogs/get-dog.test'));
		describe('GET /dogs', require('./dogs/get-dogs.test'));
	}),
	describe('cat endpoints', () => {
		describe('GET /cat/:id', require('./cats/get-cat.test'));			
		describe('GET /cats', require('./cats/get-cats.test'));
	}),
	describe('GET /meta', require('./get-meta.test'));
});

```

**Output:**
```jsx
describe("pet endpoints", () => {
	describe("dog endpoints", () => {
		describe("GET /dog/:id", require("./dogs/get-dog.test"));
		describe("GET /dogs", require("./dogs/get-dogs.test"));
	}),
		describe("cat endpoints", () => {
			describe("GET /cat/:id", require("./cats/get-cat.test"));
			describe("GET /cats", require("./cats/get-cats.test"));
		}),
		describe("GET /meta", require("./get-meta.test"));
});

```

**Expected behavior:**
Correct indentation

**Comment by evilebottnawi** [comment]
@j-f1 Not sure it is bug, here `,`, instead `;`

**Comment by j-f1** [comment]
Oh yep you’re right.
