### ISSUE TITLE
Svelte code is rejected because of adjacent elements

### ISSUE THREAD

**Issue by fkereki** [prettier/prettier#7772]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgNzgG3kgCzgEMATAPgB0oACOm1GASxhznIBUmwaPieOEOKgD0zVu2qisufETJUoUggEZO3Xv15DRqxVIBGAVxgxoNaEjA5uAawC8wKHADuAcWIBbOAF9yAOVcaD29RY1NofShgAGImADMab3R0YgBzX2p6BgIAJnJgZNSMn1186mARBJ9qKQAhCGIAJ1IaYDSvXxprOwBhXBxHAAoADwAaGgBPAEoae3IaIY7vOZpluAA6HrBbUYmZ6Z8aESiMGEm2RToRACoaAGVzmyg0taF0GiImuBobkSkROgnpJaDQpOgwE0mAAHGCKW40ABSxEwxHukJhMDecA+Xx+fwBEKhsKitSgIDGIAgsKY0HQyFAzSaEBcAAVmgh6SgURAmKQKSADE1+LY4DB7tD+EwXsgYE0jHBKQQYJ4cAB1AgsHGSsBwe6clhMTAsSbIcApAXS9BwJowVnCtKeYjIeLEHDWykAK3QIzqwp2YvunQAMtK4C63R6QN6RvdpWk2ABFIwQeAR92KkCSprWppmgzEAy4AXQqGwNV8mAEZAADgADJTSxBrWrhdCzaWcTbsAKAI4p+D26lckDEdAAWmccFI04F337TG+9vSTvTUetniYsvlmfQ8aTA-DSFdGcpMELFdIVeQuTPwqYzzSvQgnlXKCg0HDlKM1r4Bi5J5RpgCoAJJQDOsDosSMAAILgY8FxHoBvg+EAA)
```sh
--parser babel
```

**Input:**
```jsx
<svelte:head>
    <title>Tic Tac Toe</title>
</svelte:head>

<h1>Tic Tac Toe</h1>

<button on:click={newGame}>New Game</button>

{#if message}
    <h2>{message}</h2>
{/if}

<Board {game} clickCell={(x, y) => (game = game.click(x, y))} />

<style>
  /* Styling goes here */
</style>
  
<script>
/* JavaScript goes here */
</script>




```

**Output:**
```jsx
SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (5:1)
  3 | </svelte:head>
  4 | 
> 5 | <h1>Tic Tac Toe</h1>
    | ^
  6 | 
  7 | <button on:click={newGame}>New Game</button>
  8 | 
```

**Expected behavior:**
The Svelte file should not be considered JSX, and the code should be accepted and formatted correctly.

**Comment by j-f1** [comment]
What is the filename? How are you running Prettier?

**Comment by fkereki** [comment]
The current name of the file has extension **.html**. I'm running Prettier either with the Visual Studio Code extension or from the command line; results are the same.

**Comment by j-f1** [comment]
Weird. Does your config file have a `parser` property? If so, that’s your issue. It should infer the `html` parser, which at least parses.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgNzgG3kgCzgEMATAPgB0oACOm1GASxhznIBUmwaPieOEOKgD0zVu2qisufETJUoUggEZO3Xv15DRqxVIBGAVxgxoNaEjA5uAawC8wKHADuAcWIBbOAF9yAOVcaD29RY1NofShgAGImADMab3R0YgBzX2p6BgIAJnJgZNSMn1186mARBJ9qKQAhCGIAJ1IaYDSvXxprOwBhXBxHAAoADwAaGgBPAEoae3IaIY7vOZpluAA6HrBbUYmZ6Z8aESiMGEm2RToRACoaAGVzmyg0taF0GiImuBobkSkROgnpJaDQpOgwE0mAAHGCKW40ABSxEwxHukJhMDecA+Xx+fwBEKhsKitSgIDGIAgsKY0HQyFAzSaEBcAAVmgh6SgURAmKQKSADE1+LY4DB7tD+EwXsgYE0jHBKQQYJ4cAB1AgsHGSsBwe6clhMTAsSbIcApAXS9BwJowVnCtKeYjIeLEHDWykAK3QIzqwp2YvunQAMtK4C63R6QN6RvdpWk2ABFIwQeAR92KkCSprWppm5WqgXQqGwNV8mAEZAADgADJTixBrWrhdCzcWcTbsAKAI4p+D26lckDEdAAWmccFIk4F317TG+9vSTvTUetniYsvlmfQ8aTffDSFdGcpMGIBjLpAryFyJ+FTGeaV6EE8y5QUGg4cpRmtfAMXKPUaYAqACSUBTrA6LEjAACCYGPBcB4Ab4PhAA)
```sh
--parser html
```

**Input:**
```html
<svelte:head>
    <title>Tic Tac Toe</title>
</svelte:head>

<h1>Tic Tac Toe</h1>

<button on:click={newGame}>New Game</button>

{#if message}
    <h2>{message}</h2>
{/if}

<Board {game} clickCell={(x, y) => (game = game.click(x, y))} />

<style>
  /* Styling goes here */
</style>
  
<script>
/* JavaScript goes here */
</script>




```

**Output:**
```html
<svelte:head>
  <title>Tic Tac Toe</title>
</svelte:head>

<h1>Tic Tac Toe</h1>

<button on:click="{newGame}">New Game</button>

{#if message}
<h2>{message}</h2>
{/if} <Board {game} clickCell={(x, y) => (game = game.click(x, y))} />

<style>
  /* Styling goes here */
</style>

<script>
  /* JavaScript goes here */
</script>

```

**Comment by fkereki** [comment]
@j-f1: What will happen with JavaScript code, if the HTML parser is used? Is there any possibility of problems there? And if SASS code appears in the styling part?

**Comment by j-f1** [comment]
We support JS in `<script>` tags. I think we might support SCS in `<style>` if it’s marked as such.

**Comment by thorn0** [comment]
see https://github.com/prettier/prettier/issues/7762#issuecomment-599515317
