### ISSUE TITLE
Nested type assertions in JS code are broken

### ISSUE THREAD

**Issue by ExE-Boss** [prettier/prettier#7775]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAhAhgJwEkBbABwBtMBeTAegCp7MABGAT1Lk2D3wGF0MfAFcwMCPgC+merUwAKBk1YcuwYVADWUCAHco02QoBmGsQEtoOAvICU3TDAAW+PZihxdmAKL5X+eQAdEEJYOHwoXEpw-yRMQnJyOABzKMxIKAwRMQlg+0lbWwBuEAAaEAhSGEtM5FACV10ABQIENGQQXAA3CHMAEzKQACN8XDBNOBgAZVIx8yhk5CFhOHKnGGJyAHUnc3g0WbA4Kba98y69tg6wNHby+bRwmCbR5OJcZGMox-KAKzQAB7YUbjSZTXDEOAAGXmcE+31WIH+AKm82SSQAisIIPB4eQfiBZvhHvgOkNcEM4ORBqR8PMYFt+s5kAAOAAM5VpEEeW1GpA6tLgJK6cPKAEdsfAXpV2ihcGgALQeOB9FWDfBwCXmDUvXBvD5IL74xGPYjmJYiE1ozGSuGGhHlGAUxl9ZlIAAsjtG5nIaIExHeHR0HkGwkeABUKbLloiuitQqrYFMwHSqgBBKB9KbsJJ4x6SSRAA)

When using type assertions, **TypeScript** sometimes requires an intermediate cast to `unknown` due to a lack of significant overlap between types.

**Prettier’s** formatting currently breaks this intermediate JSDoc‑based type assertion.

## Input:
```js
const BarImpl = /** @type {BarConstructor} */ (
	/** @type {unknown} */
	(function Bar() {
		throw new Error("Internal error: Illegal constructor");
	})
);
```

**Note:** `BarImpl` is wrapped by a `Proxy` later in the code, which takes care of the actual `apply` and `construct` calls, but that’s irrelevant to this issue.

## Output:
```js
const BarImpl /** @type {BarConstructor} */ =
	/** @type {unknown} */
	(function Bar() {
		throw new Error("Internal error: Illegal constructor");
	});
```

## Expected behavior:
```js
const BarImpl = /** @type {BarConstructor} */ (
	/** @type {unknown} */
	(function Bar() {
		throw new Error("Internal error: Illegal constructor");
	})
);
```

**Comment by sosukesuzuki** [comment]
@evilebottnawi Unfortunately, no. This and the problem fixed by #7709 is different.
The below is the result of current `next`.

**Input:**
```js
// This issue
const BarImpl = /** @type {BarConstructor} */ (
	/** @type {unknown} */
	(function Bar() {
		throw new Error("Internal error: Illegal constructor");
	})
);

// Problem fixed by #7709
const foo = /* comments */
  bar;
```

**Output:**
```js
// This issue
const BarImpl /** @type {BarConstructor} */ =
  /** @type {unknown} */
  (function Bar() {
    throw new Error("Internal error: Illegal constructor");
  });

// Problem fixed by #7709
const foo = /* comments */ bar;
```

**Comment by thorn0** [comment]
I don't think it's possible to really fix this without adding `ParenthesizedExpression` nodes to the AST. Previously, I thought Babel's `extra.parenthesized` is enough information, but turns out sometimes we need to know how many nested parens there are and loc info for each parens.

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/7791
