### ISSUE TITLE
Wrong indention in vue `v-if`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7779]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoYCeAtJNtAjGQG60CWAZgLzEg5oAcwD6gqKPGThYmVNkSRkKABMOMDtDIAybWXkG5RxYcXK1Grbv3HpJ2wrujz6zeWumnj756XQLbjp6viEO8i6W7sFhMfZxzv6u0PyEqAD0NPQQjFDMJFDpmLgEcIQgADQgEFiRAM7IoHgATk0QAO4ACs0I9Sh4rBAcKhUgAEZNeGAA1nAwAMpYkxwSyDBNAK5wlQAWMBg4AOrb6nC1i2Bwcz2urOrUyOC19ZXLtXBNMB0TQhh4yFx4HBvSoAK1qAA8AEITaazOZ4DBwAAyyzg-0BwJAYPBc2WQhwcAAiusIPB0UCtiBFk03k0HqxNiMsE1ljADkMYNtkAAOAAMlWZEDeBwmWAezNO71YaMqAEcSfAvtVeiA8LVaLk4CotSMmnB5Rw9V88D8-kgARTKm8MBxVhtKbU8QTiaS0eaMZSYHhRuyVJzkAAmSprPAcHB4gDC2V+DygTBG6zeABVvb0LZiGXAAJKqZhzMAsmoAQVUcxg1AJ5LeAF9q0A)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <my-component v-if="long_long_long_long_long_long_long_condition && long_long_long_long_long_long_long_condition && long_long_long_long_long_long_long_condition && long_long_long_long_long_long_long_condition && long_long_long_long_long_long_long_condition && long_long_long_long_long_long_long_condition"></my-component>
</template>
```

**Output:**
```vue
<template>
  <my-component
    v-if="
      long_long_long_long_long_long_long_condition &&
        long_long_long_long_long_long_long_condition &&
        long_long_long_long_long_long_long_condition &&
        long_long_long_long_long_long_long_condition &&
        long_long_long_long_long_long_long_condition &&
        long_long_long_long_long_long_long_condition
    "
  ></my-component>
</template>

```

**Expected behavior:**
```vue
<template>
  <my-component
    v-if="
      long_long_long_long_long_long_long_condition &&
      long_long_long_long_long_long_long_condition &&
      long_long_long_long_long_long_long_condition &&
      long_long_long_long_long_long_long_condition &&
      long_long_long_long_long_long_long_condition &&
      long_long_long_long_long_long_long_condition
    "
  ></my-component>
</template>

```

**Comment by thorn0** [comment]
closed by https://github.com/prettier/prettier/pull/7781
