### ISSUE TITLE
Prettier fix breaks type casting

### ISSUE THREAD

**Issue by ernestostifano** [prettier/prettier#7784]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQGcIC2cAwoQA4A2cAHsQBZxgDWu2MdquAdLmAwQEMAlEMzAAOlEyYMOGAE8ycCFmwB6AFQbMAAQVKxAJwCuVACqK4AX0wa1cjt179hXACZx0ogLy-MAcmMoD3RUKDg3f1EJKWlMdk4uADcBClQ3ARhUaAAlOFxTGExvTHRU3DgAbklpK0krEAAaEAgyLOhcZFABQ0MIAHcABR6ETpQBJIh0ppAAI0MBZjgYAGUyRbCAc2QYEzhmuhgCCgB1DnhcdbA4FdHULKT7+WRwXE7msIrDGEGFzcFkGUKBVmgArXDUABCCyWqwERAAMmE4IDyvsQODqCstlQAIrGCDwVHA9HrQxfF6zASzOAUGZkQxhGAndLsZAADgADM0GRAKicFmQXgz8nBDEkUc0AI4E+C-VpjEACXAAWnCEQiM0McBlqG1vwE-wExJBIAqBFQOz2zVwOLg+MJKKQQNNMGpLLcbKQACZmrsBKg0lBNqQCACUFBoJKQMYKmZqWMXeiksY4ABJYIIVZgRltACCwRWCioJusViAA)
```sh
--parser babel
```

**Input:**
```jsx
if (someComplexChecks(this.schema)) {
  if (typeof (/** @type {ruleType} */ (this.schema).def) === 'undefined') {
    this.validationResult = false;
  }
}
```

**Output:**
```jsx
if (someComplexChecks(this.schema)) {
  if (typeof (/** @type {ruleType} */ (this.schema.def)) === "undefined") {
    this.validationResult = false;
  }
}

```

**Expected behavior:**
Parenthesis must remain in the input position `(this.schema).def` to allow correctly type-casting `this.schema` according to current TypeScript and Google Closure type-casting specifications.

**Comment by evilebottnawi** [comment]
I think we already have a similar problem somewhere, but I can't find

**Comment by ernestostifano** [comment]
@evilebottnawi there are various open/resolved issues regarding type casting, but I saw none of them covered the case of "partial" type casting while using property accessor like `/** @type {newType} */ (property.accessor.dot).notation.value`, which is sometimes inevitable (like in my example above, where a type change is deduced by a side effect check and not by property modification/re-assignment)

**Comment by thorn0** [comment]
Duplicate of https://github.com/prettier/prettier/issues/6122
