### ISSUE TITLE
printWidth always break line if method chains >= 3

### ISSUE THREAD

**Issue by wvq** [prettier/prettier#7803]
The printWidth option is not work, it's always break line.
**Input:**
```javascript
    a.b().c().d()
```

**Output:**
```javascript
    a.b()
      .c()
      .d()
```

**Expected behavior:**
```javascript
    a.b().c().d()
```

**Comment by thorn0** [comment]
This is fixed by https://github.com/prettier/prettier/pull/6685 , but not yet released.

**Comment by thorn0** [comment]
Duplicate of #3107
