### ISSUE TITLE
default values in 2.0 for trailingComma and arrowParens

### ISSUE THREAD

**Issue by simllll** [prettier/prettier#7806]
I updated to prettier#next to test our project with it and also look into the new ts3.8 support ;). Something I discovered that I thought could worth mentioning it, was that even though the docs for 2.x say that trailingComma "none" and arrowParens: "avoid" are the default values, they were not acting like this. I had to set this two parameters explicity in my prettierrc file.
Did the default values change and this is just wrongly documented or is it a bug?

Thanks for prettier!

Simon

**Comment by thorn0** [comment]
> trailingComma "none" and arrowParens: "avoid

In `next`, the defaults are changed to `"trailingComma": "es5", "arrowParens": "always"`. If you referred to the docs at https://prettier.io/docs/en/next, sorry for the confusion. Those docs are for `master`, not for `next`.

Apart from that, what are your impressions of `next`?

**Comment by simllll** [comment]
Ah okay, is there any summary of changes available? So far I cannot find any other issues :-) looks good to me! Looking forward to the release already

**Comment by thorn0** [comment]
Thanks for testing. See https://github.com/prettier/prettier/pull/7417
