### ISSUE TITLE
Migrate prettier-vscode to new prettier organization

### ISSUE THREAD

**Issue by ConAntonakos** [prettier/prettier#781]
Since both parties agree, let's migrate the Visual Studio Code plugin for Prettier under this new organization!

Thanks, @jlongster and @esbenp!

Original Twitter thread: https://twitter.com/ConAntonakos/status/834084544655527937

Relates to esbenp/prettier-vscode#41.

**Comment by vjeux** [comment]
We should probably do it! Is there any blocker?

**Comment by CiGit** [comment]
@vjeux none I'm aware of
Let's pull @esbenp in

**Comment by esbenp** [comment]
Well I am up for it. How do you want to do it?

**Comment by vjeux** [comment]
cc @jlongster

**Comment by vjeux** [comment]
@esbenp I just added you as a member of the organization, so you should be able to migrate the project over if you still want to do it :)

**Comment by vjeux** [comment]
Closing this as there's been no progress. If you want to move it, feel free to, if not, that's fine :)
