### ISSUE TITLE
CLI errors on "no files matching the pattern were found"

### ISSUE THREAD

**Issue by kirillgroshkov** [prettier/prettier#7822]
**Environments:**

- Prettier Version: 2.0.1
- Running Prettier via: Node 12.16.1
- Runtime: Node 12.16.1
- Operating System: MacOS

**Steps to reproduce:**

```
yarn prettier --write '*.{json,css},!CHANGELOG.md'

yarn run v1.22.4
$ /Users/kirill/Idea/dev-lib/node_modules/.bin/prettier --write '*.{json,css},!CHANGELOG.md'
[error] No files matching the pattern were found: "*.{json,css},!CHANGELOG.md".
error Command failed with exit code 2.
```

Prettier 1.x didn't return a non-0 exit status when 0 files were found. Now it does.

**Expected behavior:**

Print no error and return status 0.

**Actual behavior:**

Error is printed and status 2 is returned.

**Comment by kirillgroshkov** [comment]
UPD: I made it to work in my case like this (splitting 1 glob expression into 2 separate):

```
yarn prettier --write '*.{json,css}' '!CHANGELOG.md'
```

But it still can be breaking for some other people.

**Comment by lydell** [comment]
Can you provide some more context?

Is the _real_ issue that the following glob syntax isn’t supported anymore or something: `'*.{json,css},!CHANGELOG.md'`?

Because you do have more than 0 files that you want to run prettier on right?

Exiting with an error if no files were matched sounds reasonable to me. That helps you realize that your command did not do what you expected, rather than silently doing nothing.

**Comment by kirillgroshkov** [comment]
Actually, I think it's better I close this issue, since I found the workaround. Basically, I changed from:

```
yarn prettier --write '*.{json,css},!CHANGELOG.md'
```

to

```
yarn prettier --write '*.{json,css}' '!CHANGELOG.md'
```

The "error on no files" was not a root cause, my files are still there, just the globbing syntax wasn't recognized.

Thanks for looking into it anyway and thanks for amazing tool!

**Comment by evilebottnawi** [comment]
> `'*.{json,css},!CHANGELOG.md'` 

I didn’t even think that it is supported, I think we never officially supported it :smile:
