### ISSUE TITLE
New default EOL config causes format check to fail on Windows

### ISSUE THREAD

**Issue by imbsky** [prettier/prettier#7825]
**Environments:**

- Prettier Version: 2.0.1
- Running Prettier via: CLI
- Runtime: Node.js 12.x
- Operating System: Windows Server 2019

**Steps to reproduce:**

Format with the latest Prettier with default config and then run format check. 

**Expected behavior:**

It shouldn't fail.

**Actual behavior:**

It will fail.

**Information for users with similar problems:**

You can temporarily avoid this problem by changing the EOL configuration to auto.

**Comment by imbsky** [comment]
For reference: https://github.com/ocamllabs/vscode-ocaml-platform/pull/71

**Comment by imbsky** [comment]
I'm not familiar with the Prettier's code, so I don't know what causes this, but it shouldn't happen anyway.

**Comment by lydell** [comment]
Hi!

Was your problem that [your GitHub Actions workflow](https://github.com/ocamllabs/vscode-ocaml-platform/blob/3c69dad03b88ee66d5e9c47ae3ad86ce0cc4bd98/.github/workflows/workflow.yml) failed?

You should be able to fix that by either:

1. Do like mentioned in [the docs for the End of Line option](https://prettier.io/docs/en/options.html#end-of-line):

   > Add `* text=auto eol=lf` to the repo's .gitattributes file. You may need to ask Windows users to re-clone your repo after this change to ensure git has not converted LF to CRLF on checkout.

2. Set git to use LF in GitHub Actions: https://github.com/actions/checkout/issues/135

**Comment by imbsky** [comment]
Oh, I see, I could solve this by adding the `.gitattributes`. Thanks!
