### ISSUE TITLE
Prettier is inferring incorrect parser for markdown

### ISSUE THREAD

**Issue by lfilho** [prettier/prettier#7827]
**Environments:**

- Prettier Version: 2.0.1
- Running Prettier via: CLI (also via `coc-prettier`)
- Runtime: Node.js 13.7.0
- Operating System: macOS

## Reproduction steps

1. Markdown file `test.md`  with contents: `*TEST*`.
2. Run `prettier --write test.md`
3. Run `prettier --loglevel debug --check test.md` 

## Expected behavior

On step 2, file would be formatted to: `_TEST_`

## Actual behavior

- File is unchanged.
- Result from step 3 is:

```
Checking formatting...
[debug] normalized argv: {"_":["test.md"],"check":true,"color":true,"editorconfig":true,"loglevel":"debug","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
Checking formatting...
[debug] resolve config from 'test.md'
[debug] loaded options `{"useTabs":false,"tabWidth":2,"endOfLine":"lf","trailingComma":"es5","singleQuote":true,"parser":"babel"}`
[debug] applied config-precedence (cli-override): {"endOfLine":"lf","parser":"babel","singleQuote":true,"tabWidth":2,"trailingComma":"es5","useTabs":false}
test.md[error] test.md: SyntaxError: Unexpected token (1:1)
[error] > 1 | *TEST*
[error]     | ^
[error]   2 |
All matched files use Prettier code style!
```

Note two things:
1. Parser being `babel` instead of `markdown`
2. Last line reporting "all matched files use Prettier code style!" although there was a clear "SyntaxError" just above.

---

If I run steps 2 and 3 explicitly passing `--parser markdown`, then it works as expected.

**Comment by lfilho** [comment]
Nevermind. Realized I had a `parser: babel` in my config file. 

But still, shouldn't the commands have thrown an error as per my note 2 above?

Thanks

**Comment by thorn0** [comment]
> shouldn't the commands have thrown an error as per my note 2 above?

No, it shouldn't. [`--check`](https://prettier.io/docs/en/cli.html#--check) looks for files that would change if Prettier were run with `--write`.
