### ISSUE TITLE
Breaking change of 2.0.1 - if files not found it gives an error.

### ISSUE THREAD

**Issue by thebravoman** [prettier/prettier#7829]
**Environments:**

- Prettier Version: 2.0.1
- Running Prettier via: CLI
- Runtime: Node.js
- Operating System: Linux

**Steps to reproduce:**
With 1.19.1 run 
```
"npx prettier app/**/*.js test/dummy/spec/javascripts/**/*_spec.js vendor/assets/javascripts/gcc/externs/*.externs.js --write -c --config prettier_conf.json" 
```
it runs

With 2.0.1 run
```
"npx prettier app/**/*.js test/dummy/spec/javascripts/**/*_spec.js vendor/assets/javascripts/gcc/externs/*.externs.js --write -c --config prettier_conf.json" 
```

```
[error] No files matching the pattern were found: "test/dummy/spec/javascripts/**/*_spec.js".
[error] No files matching the pattern were found: "vendor/assets/javascripts/gcc/externs/*.externs.js".
```
**Expected behavior:**
I would expect that something that has worked with 1.19.1 would continue working with 2.0.1. Yes, there are no such files in the specific folder. But we were depending on this. It was a common procedure for us. We have hundreds of places and projects that got broken today.

Thank you for the terrific job with Prettier, but I would expect that things continue working on an upgrade. Should it give an error? I don't know. But were were depending on it not given an error. It's not a bug, it is a feature on which we've based our building infrastructure. 

And yes, we could fix it. But that is not the point. 

**Actual behavior:**

**Comment by j-f1** [comment]
This is a result of changes to our glob engine. Since version 2.0 was a new major version, we made several breaking changes. The fix for this should be pretty simple:

```
"npx prettier app/**.js test/dummy/spec/javascripts/**_spec.js vendor/assets/javascripts/gcc/externs/*.externs.js --write -c --config prettier_conf.json" 
```

Alternatively, you could change your code to do `npx prettier --check .` and set up a `.prettierignore` file that ignores any files you don’t want to format.

**Comment by thebravoman** [comment]
Thanks @j-f1 it really is a simple fix. It would have been also very simple to log
"Warning: Hey guys, we have deprecated this. Please have in mind that with version 2.0.1 it will be a breaking change. You don't have files in this project and this will break in 2.0.1. Repeat. This will break. Please guys, don't open an issue on our github. Read this message. We see that you are using a feature that will break. Please. Just be prepared and read this document of what to do"

I am not against breaking changes. I welcome them. But give us some warning and heads up

**Comment by thebravoman** [comment]
And no. The fix did not work
```
$ npx prettier app/**.js test/dummy/spec/javascripts/**_spec.js vendor/assets/javascripts/gcc/externs/*.externs.js --write -c --config /var/lib/jenkins/jobs/is-gcc_tools\ Build\ and\ Release/workspace/prettier_conf.json
npx: installed 1 in 1.867s
Checking formatting...
[error] No files matching the pattern were found: "app/**.js".
[error] No files matching the pattern were found: "test/dummy/spec/javascripts/**_spec.js".
[error] No files matching the pattern were found: "vendor/assets/javascripts/gcc/externs/*.externs.js".
```

**Comment by thebravoman** [comment]
I also can not prettierignore the files since I don't know what to ignore. I only know what to include

I have a common project that does the build on many other projects.

This common project knows which files from the other projects to compile test/dummy/*.js. And it does not know what to exclude. Since there could be many different other files in the different projects and it can not know about them. It knows nothing about them. It works - convention over configuration. I do not have to create hundreds of prettierignore now for all the projects. That would be overkill.

**Comment by thebravoman** [comment]
Looking here - https://prettier.io/blog/2020/03/21/2.0.0.html

I can not find information about this breaking change and what to do with it. 

Here is my solution if others visit this issue

```
npm install prettier@1.19.1 && npx prettier ...
```

Just install prettier@1.19.1 

I should probably open a different issue about the fact that running with a wildcard glob returns an error. What do you think @j-f1 ?

This is not just breaking. We cannot run with an empty glob.

**Comment by j-f1** [comment]
I think we should consider making it a warning instead, but some more-involved members of @prettier/core may have better understanding of why we made this change.

**Comment by thorn0** [comment]
The new behavior matches the behavior of the ESLint CLI. ESLint has `--no-error-on-unmatched-pattern` though. We might want to add it too.

**Comment by thebravoman** [comment]
@thorn0 you mean to add this option "--no-error-on-unmatched" to my npx prettier. I could try

**Comment by j-f1** [comment]
@thebravoman Not yet. I think @thorn0 was saying that’s a thing that works in ESLint, and Prettier should consider adding it.

**Comment by thorn0** [comment]
@thebravoman I'm trying to understand your use case. What is the point in combining `--write` and `--check`?

**Comment by thebravoman** [comment]
--write -c is returning
```
Checking formatting...
All matched files use Prettier code style!
```
--write is listing all the files 
```
is_protects_manifest.js 25ms
protects.js 22ms
protects/is_cc.js 35ms
protects/is_gc.js 18ms
protects/is_p.js 54ms
protects/server_load.js 21ms
```

Guess it was just prettier and it is a left over from when we build it.

**Comment by thorn0** [comment]
> I just want to specify
> $ npx prettier *.js 
> and if there are not js files than this is not an error.

This was an error in 1.19.

Anyways, looks like I found a workaround for you though. You can combine all your patterns into one big pattern using `{...}`:
```console
$  prettier '{app/**/*.js,test/dummy/spec/javascripts/**/*_spec.js,vendor/assets/javascripts/gcc/externs/*.externs.js}' --write -c --config prettier_conf.json
```

I agree that the release notes need a clarification about these errors.

**Comment by thebravoman** [comment]
Exactly.

**Comment by thorn0** [comment]
1.19.1 printed an error, if it couldn't match any file at all—for all the patterns together, not for an individual pattern. 2.0.1 now also prints errors for individual patterns.

**Comment by thebravoman** [comment]
@thorn0 @j-f1 if only it was that simple

2.0.1
```bash
$ mkdir pretti
$ cd pretti/
/pretti$ touch some.js
/pretti$ npx prettier --version
2.0.1
/pretti$ ls
some.js
/pretti$ npx prettier app/**/*.js *.js
[error] No files matching the pattern were found: "app/**/*.js".
/pretti$ echo $?
127
```

1.19.1
```bash
$ mkdir pretti
$ cd pretti/
/pretti$ touch some.js
/pretti$ npx prettier --version
1.19.1
/pretti$ ls
some.js
/pretti$ npx prettier app/**/*.js *.js
/pretti$ echo $?
0
```

The difference here is no **1.19.1 printed an error, ** and **2.0.1 now also prints errors for individual patterns.**

I don't actually care of what is printed. It is returning a different result. 2.0.1 is returning 127 and 1.19.1 is returning 0. So 2.0.1 is not successful and 1.19.1 is successful.

This breaks continuous integration.

**Comment by thorn0** [comment]
closed by https://github.com/prettier/prettier/commit/0d813b7d4ab8dc14dd551fdd9cf78bd3d403759c
