### ISSUE TITLE
"Always add a space..." is a breaking change and should be marked as such. It is not just Others.

### ISSUE THREAD

**Issue by thebravoman** [prettier/prettier#7831]
**Environments:**

- Prettier Version: 2.0.1
- Running Prettier via: cli
- Runtime: Node
- Operating System: Linux

**Steps to reproduce:**
Go to https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot

A new change is introduced. I would consider it a breaking change since in a scenario of a Continuous Integration this means that your code is not formatted correctly. 

So the build could not continue as Prettier returns that not all files are formatted.

**Expected behavior:**
Have an explanation of what is the option and with what value should this option be for the continuous integration checks to continue working as previously. The option is probably  "--space-before-function-paren" but it is not clear how to use it directly on the release note.

I think this should be marked as a braking change. It is breaking a couple of hundred projects on one client, that is true, but it is breaking them. 

**Actual behavior:**
There is no explanation on how to keep the old behavior and with what configuration.

**Comment by thorn0** [comment]
Prettier does not consider formatting changes breaking unless they actually break code (previously working code stops working). Let me quote [this comment](https://github.com/prettier/prettier/issues/6126#issuecomment-499814070):

> The contract of Prettier is that it takes a string as input (and a bunch of options), and gives a string as output. But what that output string looks like is not specified. Otherwise every release of Prettier would be a breaking change (even the smallest bug fixes).

As for the space after `function`, there is no option to keep the old behavior.

**Comment by thebravoman** [comment]
@thorn0 makes sense.
 
Why is this a breaking change then - https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-arrowparens-to-always-7430httpsgithubcomprettierprettierpull7430-by-kachkaevhttpsgithubcomkachkaev

Is it changing formatting and default behavior and is breaking, but the rest are not?

**Comment by thorn0** [comment]
> Why is this a breaking change then

We consider changes to the default values of options breaking as it's part of the API.

> Which is exactly what the "function ()" needs

Please see the [option philosophy](https://prettier.io/docs/en/option-philosophy.html) page.
