### ISSUE TITLE
Breaking CI change - new formatting for line (with old config) breaks CL and is not described as Breaking in release note

### ISSUE THREAD

**Issue by thebravoman** [prettier/prettier#7832]
**Environments:**

- Prettier Version: 2.0.1
- Running Prettier via: CLI
- Runtime: Node
- Operating System: Linus

**Steps to reproduce:**
1. Go to https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot and look at the breaking changes.

2. Update from 1.19.1 to 2.0.1. Use same configuration. 

3. Format files. The following is a difference in one of the files:

```javascript
-          it("'recievesWith'", function() {
-            expect(
-              this.result
-                .getEventsDef()
-                .getEventDef("stepsTreeLoaded")
-                .getReceivesWith()
-            ).toEqual(Object.assign);
+          it("'recievesWith'", function () {
+            expect(this.result.getEventsDef().getEventDef("stepsTreeLoaded").getReceivesWith()).toEqual(Object.assign);
           });
```

**Expected behavior:**

This should be marked as a breaking changed. I could not find it in the list of breaking changes. Forgive me if I am wrong.

**Actual behavior:**

No documentation that this is a breaking change

**Comment by thorn0** [comment]
https://github.com/prettier/prettier/issues/7831#issuecomment-602262006
