### ISSUE TITLE
Question: remove `bracketSpacing` option?

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7841]
I understand that we just released v2.0.0, but `bracketSpacing` seem not very useful, should we remove it some day?

**Comment by SimenB** [comment]
it was added for fb and afaik they still use it

**Comment by lydell** [comment]
Previous discussion:

- https://github.com/prettier/prettier/issues/3520
- https://github.com/prettier/prettier/issues/3503

**Comment by bakkot** [comment]
I am hopeful that there are not going to be enough breaking changes which are worth making to warrant a 3.0, ever, so this would not come up.

**Comment by thorn0** [comment]
This option is going to stay. See the previous discussions.
