### ISSUE TITLE
Question:How can I prevent prettier behavior

### ISSUE THREAD

**Issue by har17bar** [prettier/prettier#7843]
i want formating like this
Input:
```jsx
@Matches(
    /^[a-zA-Z0-9_.-]*$/, {
      message: 'Please try again'
    })
```
Prettier reformat to
Output:
```jsx
@Matches(
    /^[a-zA-Z0-9_.-]*$/,
    {
      message: 'Please try again'
    }
  )
```
dont want to disable prettier, i have .prettierrc file in root for configuration
Expected behavior:
```jsx
@Matches(
    /^[a-zA-Z0-9_.-]*$/, {
      message: 'Please try again'
    })
```

**Comment by sosukesuzuki** [comment]
It would be nice if you could follow the [issue template](https://github.com/prettier/prettier/blob/master/.github/ISSUE_TEMPLATE/formatting.md).
