### ISSUE TITLE
Spaces are removed from markdown lines followed by two spaces on a previous line

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#7846]
**Prettier 2.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFnATnABAQx1xgHcJcBnAB3zDgtwDMIAbFiEgSygHNc5a6XFg64uMIQAN8AOjkATSbgBGcdiSQAdKNoC0BA7m24TylSeMncYaxahX5uR0fv9+27QEYZJ-Ab8uVmbBdiY24aEmjtGRJnjxIAA0IBBUMJzQFMighCIkAAqECFko+Cwk+ACeWcnKWLQA1nAwAMo0YNw8yDBYAK5wyegwALYsAOronPDUtHAtxVOcAG5TlcjgFDUg3BTYMPn1PMP4yIxlu8kAVhQAHgBC9WBNrfjDcAAy3HCn5wMg1zcWp0WHAAIq9CDwH4sC4gGhYXZYdbHLANeQcKBJOFYbgwMaceQSZAADgADMkqCJdmN6lR1pT6Nglt9kgBHCHwA6pEogfAUXRQOBweTCrE4dmcHAHfBHE5IM4wv67Yacbp9JXAsEc77y37JGD4ZT4wnoZAAJn19U4LE6AGEIMNjut6ABWLG9XaoQ0lBWwpb9ACSUBFsBaYBxaQAgsGWjBKiDobsAL5JoA)
```sh
--parser markdown
```

Seems like this issue is caused by https://github.com/prettier/prettier/pull/7178, which fixes https://github.com/prettier/prettier/issues/6948

**Input:**
```markdown
There are two spaces following each row with `a...d` below:

- a a  
   b b  
    c c  
   d d  
  e e

1.  a a a  
   b b b  
  c c c  
   d d d  
    e e e
```

**Output:**
```markdown
There are two spaces following each row with `a...d` below:

- a a  
  bb  
  cc  
  dd  
  ee

1.  a a a  
    bbb  
    ccc  
    ddd  
    eee

```

**Expected behavior:**

```markdown
There are two spaces following each row with `a...d` below:

- a a  
  b b  
  c c  
  d d  
  e e

1.  a a a  
    b b b  
    c c c  
    d d d  
    e e e
```

Meanwhile, a workaround is to [use `<br>` instead of `··` for line breaks](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFnATnABAQx1xgHcJcBnAB3zDgtwDMIAbFiEgSygHNc5a6XFg64uMIQAN8kglAAmuSfNkAjOOxJIAOlF0BaAkdy7cZ1blUAeVVgB8ps7jDOb9x7kWKTUM3ji6ugCMAHRm+EYRPk4WsW4Ovs5JYPEeXp5mHvzZcCAANCAQVDCc0BTIoIQiJAAKhAjlKPgsJPgAnuUFtrQA1nAwAMo0YNw8yDBYAK5wBegwALYsAOronPDUtHADDWucAG5rbcjgFJ0g3BTYMDVY+Dzz+MiMzZcFAFYUAB4AQrdgfYN8PM4AAZbi5JDPFivEAfT4DUYsOAARUmEHgTxeMxANCwlywxweWB68g4UHyOKw3BgS048gkyAAHAAGApUESXJa3KjHdn0bB7XIFACOaPgNyKjRA+Ao+igcDg8kVFJwos4OBudwemOh2Mu8044ymesRKLFEKhMJg+FUtPp6GQACYChN8JwWKMAMIQebalD0ACsFMml1QNsaluxe2mAEkFAhBmAqcUAIIKAYwNpInWXAC+uaAA).

Seems like this issue only relates to lists. Not in lists though, there is the [same leading space issue](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFnATnABAQx1xgHcJcBnAB3zDgtwDMIAbFiEgSygHNc5a6XFg64uMIQAN8AOjkATSbgBGcdiSQAdKNvwFcubSuOGoBsLgunc8mwe1442o-r17ry459MXf9s7aB-gaO-CAANCAQVDCc0BTIoIQiJAAKhAgJKPgsJPgAngmRyli0ANZwMADKNGDcPMgwWACucJHoMAC2LADq6Jzw1LRwVZkDnABuA-nI4BRFINwU2DCppTyd+MiMOcuRAFYUAB4AQqVgFdX4nXAAMtxw27ttIIdHVfUscACKzRDwTxYexANCwyyws02WDK8g4UAiIKw3BgPU48gkyAAHAAGSJUETLHqlKizfH0bATR6RACOf3ga2iWRA+AoAFooHA4PIuQicLTODg1vgNlskDsgS9lp1OI0WpLPj86Y8xc9IjB8MpUej0MgAExq0qcFj1ADCEE6m1m9AArAjmstUBqsuLgRNWgBJKDc2BVMBImIAQS9VRg+S+gOWAF9I0A) as reported in #6948

**Comment by evilebottnawi** [comment]
Thanks

**Comment by thorn0** [comment]
Is this a regression in 2.0?

**Comment by kachkaev** [comment]
Yep, all was OK in 1.19 (before https://github.com/prettier/prettier/pull/7178)

**Comment by kachkaev** [comment]
@thorn0 if there is a planned 2.0.x release but we still don't have a proper fix, perhaps we could just revert https://github.com/prettier/prettier/pull/7178 for now and just remove a [corresponding section in the blog post](https://prettier.io/blog/2020/03/21/2.0.0.html#fix-redundant-leading-spaces-in-lists-7178httpsgithubcomprettierprettierpull7178-by-sasurau4httpsgithubcomsasurau4). That's minor compared to the impact this new bug has. For us, its a blocker from upgrading to v2, whil https://github.com/prettier/prettier/issues/6948 is just a small imperfection.

cc @sasurau4 (if you have time to look into fixing 🙏)
