### ISSUE TITLE
New line in tagged template literal is removed

### ISSUE THREAD

**Issue by mohsen1** [prettier/prettier#7849]
**Prettier 2.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALGBbANgAwDpR4wA8qAjAHwAScWWExA9ORQTiADQgQAOMAltADOyUAEMAThIgB3AAqSEIlGKwyxATxFcARhLFgA1nBgBlHgf5QA5shgSArnC7psAdVT94Qi2DimlL34ANy8NZHAhbRArITgJGDl9awwxZAAzVTiuACshAA8AIX0jE1MxDDgAGSs4DKznEDz80ytrLDgARQcIeHqsbJALCTiJCJ0xHVpOIYkrGDd+ABMYVGQADgAGLh5pOLd9HgjduFHguq4ARx74JN5lEDEhAFooODglj5mJOGv+H6SYhSaSQmQGjTiGH4dkcELaHW6vTqoIaXBgk0WKzWSAATGj9PwsG0AMIQDCpCKnACsMwccQAKpNlGDBsEnABJKCfWCmMBzPgAQS5phgGg6-TiAF9JUA)
```sh
--parser babel
```

**Input:**
```jsx
html`
	<h1>Hello</h1>
`
```

**Output:**
```jsx
html` <h1>Hello</h1> `;

```

**Expected behavior:**
Output must sustain new lines 
```jsx
html`
	<h1>Hello</h1>
`
```

**Comment by evilebottnawi** [comment]
newline === space in HTML, what is a problem?

**Comment by mohsen1** [comment]
That's correct. Didn't realize `html` tag is treating specially. Closing as expected behavior then.

**Comment by thorn0** [comment]
@mohsen1 Please see [this section](https://prettier.io/blog/2020/03/21/2.0.0.html#respect-whitespace-significance-in-html-template-literals-7208httpsgithubcomprettierprettierpull7208-by-saschanazhttpsgithubcomsaschanaz) ("Respect whitespace significance in HTML template literals") of the 2.0 blog post.
