### ISSUE TITLE
force to always use long ternary format?

### ISSUE THREAD

**Issue by chrisdrackett** [prettier/prettier#785]
I've always preferred the multi line format for ternaries for readability. I'm sure you guys don't want to add a billion options and I understand this project is suppose to be opinionated, but it would be awesome if there was a way for even short ternaries to use the following format:

```js
const obj0 = conditionIsTruthy 
    ? shortThing
    : otherShortThing;
```

**Comment by jlongster** [comment]
I think there are too many places where a short `isTrue? 0 : 1` would look really bad with this, and would make it way too verbose. I can think of many places where I've written code almost literally the my example so I think we need to keep it inline where we can.
