### ISSUE TITLE
Remove Extra Parenthesis around pure Conditional Expressions

### ISSUE THREAD

**Issue by lukeed** [prettier/prettier#7852]
**Prettier 2.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgDZwxYCWAvAAwA0WMAtgA4DcJWAPFgIYYYB0BUAcxgALZsQDU4gJRZgAHShYSqXHXpZSnbgG1iAXRmQoAZwgE+EATgDkATw63rUxgoC+ISiAj0YxaMeRQLgwIAHcABS4EAJQOPFCHAM8AIwwOMABrQgBlenTiQWQYDABXOE9hOjwAdWFieGM8sDhs6PriADd622RwYySQAuM4DBhwtIFaDmRUOOHPACtjAA8AITTMnI5aOAAZArgZufKQJeXsgoECAEUSiHgjvHmQPIxhjF7kjmS4PA8XjAFGDVYgAExEyAAjAAmKgAiDDappei9egYODvDqHTwARzu8HG3hiIA4xgAtFA4HBQdT-ui8cR0eMOJNpkhZk8TsNaMQiqUuZcbvjDkhimVPDBviDwcJkNCJWliHhLgBhCC0Ka9DEAVn+JWGABVvjExScOmUAJJQGmwbJgQE+ACC1uyMFsBEew1criAA)

```sh
# Options (if any):
# ... any
```

**Input:**

```js
for (let i=0, tmp; i < arr.length; i++) {
  if (tmp = arr[i]) console.log('yay');
}
```

**Output:**

```js
for (let i = 0, tmp; i < arr.length; i++) {
	if ((tmp = arr[i])) console.log('yay');
}
```

**Expected behavior:**

```js
for (let i = 0, tmp; i < arr.length; i++) {
	if (tmp = arr[i]) console.log('yay');
}
```

The `if`-block's parenthesis are sufficient. 
It's too much noise to wrap w/ any extra. Imagine with an expression that uses a function, too: [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgDZwxYCWAvAAwA0WMAtgA4DcJWAPFgIYYYB0BUAcxgALZsQDU4gJRZgAHShYSqXHXpZSWSAy5wcXDAG1iAXWroIAIy44pdrdADOEAnwgCcAcgCeHb56lGBQBfEEoQCHoYYidkUAMIAHcABV0oR2QQDjxEvwzwywwOMABrQgBlemLiQWQYDABXOHDhOjwAdWFieEcqsDhyhEdu4gA3bu9MsEd8kBrHOAwYZKKBWg5kVGyF8IArRwAPACEi0oqOWjgAGRq4Te3mkH2D8pqBAgBFBoh4e7wdkBVDALDCZayWOB4MKAjA1GDtYgAExEyAAjAAmKgwiALdpFeiZegYOAg0Z3cIAR2+8BWkQyKA4jgAtFA4HBEezocSqcRiSsOGsNkgtv9HgtaMQ6o0xW9PtS7kh6k1wjAOJYEcjhMh0SqisQ8G8AMIQWjrTIkgCs0IaCwAKmr6UrHqMmgBJKAc2DlMCwqIAQQ95Rg3gIfwWwWCQA):

```js
// input
for (let i=0, tmp; i < arr.length; i++) {
  if (tmp = compare(arr[i], foobar())) console.log('yay');
}

// output
for (let i = 0, tmp; i < arr.length; i++) {
	if ((tmp = compare(arr[i], foobar()))) console.log('yay');
}
```

These parenthesis are only necessary when comparing the assignment to something else:

```js
for (let i=0, max; i < arr.length; i++) {
  if ((max = Math.max(arr[i], max)) > 10) console.log('yay');
}
```

**Comment by sosukesuzuki** [comment]
This behavior is intentional! Quote from the https://github.com/prettier/prettier/issues/5591#issuecomment-444070697

**Comment by lukeed** [comment]
I know. I'm requesting it be reconsidered.

**Comment by j-f1** [comment]
I don’t think we plan on changing this. At least for me, I almost never see this kind of construct, and the extra `()` help show that something unusual is happening (`=` instead of `==` or `===`).
