### ISSUE TITLE
Windows `--check .` problem

### ISSUE THREAD

**Issue by christianbundy** [prettier/prettier#7853]
**Environments:**

- Prettier Version: 2.0.2
- Running Prettier via: CLI
- Runtime: Node.js v10, v12, v13
- Operating System: Windows

**Steps to reproduce:** `prettier --check .`

**Expected behavior:** Prettier is happy and exits 0.

**Actual behavior:** "Code style issues found in the above file(s). Forgot to run Prettier?" [see here for full log from Travis CI](https://api.travis-ci.com/v3/job/301435954/log.txt)

**Comment by thorn0** [comment]
Please clarify why you expect that "Prettier is happy and exits 0"? Are you sure those files are actually formatted? Why do you think the problem is specific to Windows?

**Comment by christianbundy** [comment]
I'm running these tests on all three Node.js version on both macOS and Linux and can confirm that they [succeed](https://travis-ci.com/github/fraction/oasis/builds/154702510). The problem is specific to Prettier 2 and Windows.

**Comment by christianbundy** [comment]
I've just added a `.gitattributes` to ensure that Windows is using LF line endings but it doesn't seem to solve the problem. Is there a way that I can get Prettier to tell me what the problem is?

**Comment by thorn0** [comment]
Let it reformat a file and compare the result with the source:
```
cat foo.js | prettier --parser babel | diff foo.js -
```

**Comment by christianbundy** [comment]
Workaround: `--end-of-line auto` 

It's unclear to me whether Travis has a bug where it isn't respecting `.gitattributes` or whether this is a bug in Prettier.

**Comment by thorn0** [comment]
Please see https://docs.travis-ci.com/user/customizing-the-build#git-end-of-line-conversion-control

**Comment by christianbundy** [comment]
That did the trick, thank you! I'm surprised nobody else has bumped into this yet.

```sh
cat << EOF >> .travis.yml

git:
  autocrlf: input

EOF
```

**Comment by thorn0** [comment]
documented this: https://github.com/prettier/prettier/commit/b4a52257709129882d789906b6842fc17217dd65

**Comment by christianbundy** [comment]
Beautiful, thanks again for all your help.

**Comment by axetroy** [comment]
I got same issue in Github Actions.

and add `.gitattributes` not works for me

```
text=auto
eol=lf
```

**Comment by christianbundy** [comment]
I think that's supposed to be one line:

```
* text=auto eol=lf
```

If *that* doesn't work, maybe GitHub actions has its own setting for auto-conversion of EOL characters.

**Comment by axetroy** [comment]
@christianbundy Thanks and works for me 👍
