### ISSUE TITLE
odd output for template literals

### ISSUE THREAD

**Issue by chrisdrackett** [prettier/prettier#786]
given the following code:

```js
insertRule(`*, *:before, *:after {
  box-sizing: inherit;
}`)
```

I get the following output:

```js
insertRule(
  `*, *:before, *:after {
  box-sizing: inherit;
}`,
)
```

The formatting of the last two lines seems odd to me. I'm not sure why a comma is added or why the line with the closing bracket is on the same indentation as the closing parenthesis.

**Comment by vjeux** [comment]
Template literals are tricky because the indentation is part of the string itself. If we change the indentation, this means that the string itself will change and this may (or may not, like in this case) change the program behavior, which we don't want to.

In this case, in the original version, `}` was indented by 0 spaces so we respect that. As for the comma, this is because you've got the trailing comma option enabled.

**Comment by jlongster** [comment]
That code should not be breaking in the first place though... it doesn't reach 80 chars so not sure why it breaks the function call. In cases where it does break though, yes, this is expected behavior and you'll have to tweak the literal to make it align correctly.

**Comment by vjeux** [comment]
```js
./bin/prettier.js test.js --debug-print-doc
[
  "insertRule",
  wrappedGroup([
    "(",
    indent(2, [
      softline,
      "`",
      "*, *:before, *:after {",
      hardline,
      breakParent,
      "  box-sizing: inherit;",
      hardline,
      breakParent,
      "}",
      "`"
    ]),
    ifBreak(""),
    softline,
    ")"
  ]),
  ";",
  hardline,
  breakParent
];
```

Looks like template literal \n force the parent to break.

**Comment by vjeux** [comment]
But even if I remove `breakParent` from `templateline`, it still triggers the parent to break.

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/issues/231 has more examples of template literal issues.

**Comment by vjeux** [comment]
Let's close this in favor of #231

**Comment by vjeux** [comment]
Another similar issue reported by @jonikorpi

[styled-jsx](https://github.com/zeit/styled-jsx) causes similar issues. No errors, but the resulting formatting is undesirable/ugly. 

```jsx
<style jsx>{`
      p {
        color: red;
      }
`}</style>
```
->
```jsx
<style jsx>
      {
        `
      p {
        color: red;
      }
    `
      }
</style>
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20default%20()%20%3D%3E%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%3Cp%3Eonly%20this%20paragraph%20will%20get%20the%20style%20%3A)%3C%2Fp%3E%5Cn%20%20%20%20%7B%20%2F*%20you%20can%20include%20%3CComponent%20%2F%3Es%20here%20that%20include%5Cn%20%20%20%20%20%20%20%20%20other%20%3Cp%3Es%20that%20don't%20get%20unexpected%20styles!%20*%2F%20%7D%5Cn%20%20%20%20%3Cstyle%20jsx%3E%7B%60%5Cn%20%20%20%20%20%20p%20%7B%5Cn%20%20%20%20%20%20%20%20color%3A%20red%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%60%7D%3C%2Fstyle%3E%5Cn%20%20%3C%2Fdiv%3E%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
For the first example, I found out that if you write it without parenthesis, then it prints the same way as the original.

```js
insertRule`*, *:before, *:after {
  box-sizing: inherit;
}`
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22insertRule%60*%2C%20*%3Abefore%2C%20*%3Aafter%20%7B%5Cn%20%20box-sizing%3A%20inherit%3B%5Cn%7D%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
I wonder if many people write it as 

```js
insertRule(
  `this is a long string
    that is very long`
);
```

if not, then we could special case single-argument calls that are templates to not indent.

**Comment by vjeux** [comment]
I just sent https://github.com/prettier/prettier/pull/873 which fixes the original issue but I'm not sure this is the right thing to do.

**Comment by techniq** [comment]
I thought the formatting for an optional `styled-component` rule was a little odd (although not terrible), but thought I'd throw another template literal example here to consider.  This one has nested template literals.

```js
const Wrapper = styled.div`
  padding-top: 64px;
  padding-left: 8px;
  padding-right: 8px;
  transition: margin .3s;

  ${({sidebar}) => sidebar.docked && sidebar.open && css`
    margin-left: ${sidebar.width}px
  `}
`;
```
formats to
```js
const Wrapper = styled.div`
  padding-top: 64px;
  padding-left: 8px;
  padding-right: 8px;
  transition: margin .3s;

  ${({ sidebar }) => sidebar.docked &&
  sidebar.open &&
  css`
    margin-left: ${sidebar.width}px
  `}
`;
```

**Comment by knowbody** [comment]
I've also seen that `styled-components` get weird formatting, probably all related to this issue:

```js
const Container = styled.div`
  margin: ${props => props.margin || 0};
  background: ${props => props.color || 'transparent'};
  margin-bottom: ${props => {
    if (props.hasStickyFooter) {
      return '5rem';
    } else if (!props.margin) {
      return '0rem';
    }
  }};
  cursor: ${props => props.pointer ? 'pointer' : 'auto'};
`;

export default Container;
```

formatted to: 

```js
import styled from 'styled-components';

const Container = styled.div`
  margin: ${props => props.margin || 0};
  background: ${props => props.color || 'transparent'};
  margin-bottom: ${props => {
  if (props.hasStickyFooter) {
    return '5rem';
  } else if (!props.margin) {
    return '0rem';
  }
}};
  cursor: ${props => props.pointer ? 'pointer' : 'auto'};
`;

export default Container;
```

**Comment by gustavnikolaj** [comment]
I have a similar case and , which is triggered by tabWidth. Notice how the second argument to the `this.query` call in `loadEntity` is indented incorrectly in the tabWidth 4 case.

1. [tabWidth 2](https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Api%20%7B%5Cn%20%20constructor%20(graphQlClient)%20%7B%5Cn%20%20%20%20this.query%20%3D%20(query%2C%20variables%20)%20%3D%3E%20graphQlClient.query(query%2C%20variables)%3B%5Cn%20%20%7D%5Cn%5Cn%20%20loadEntity(id)%20%7B%5Cn%20%20%20%20%20%20return%20this.query(gql%60%5Cn%20%20%20%20%20%20%20%20%20%20query%20LoadEntity(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%24id%3A%20ID!%5Cn%20%20%20%20%20%20%20%20%20%20)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20getEntity(id%3A%20%24id)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20error%20%7B%20type%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mail%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...Entity%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%24%7BApi.fragments.Entity%7D%5Cn%20%20%20%20%20%20%60%2C%20%7B%20id%20%7D).then(res%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20if%20(res.data.getEntity.error)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20throw%20new%20Error(res.data.getEntity.error.type)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20return%20res.data.getEntity.mail%3B%5Cn%20%20%20%20%20%20%7D)%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)
2. [tabWidth 4](https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Api%20%7B%5Cn%20%20constructor%20(graphQlClient)%20%7B%5Cn%20%20%20%20this.query%20%3D%20(query%2C%20variables%20)%20%3D%3E%20graphQlClient.query(query%2C%20variables)%3B%5Cn%20%20%7D%5Cn%5Cn%20%20loadEntity(id)%20%7B%5Cn%20%20%20%20%20%20return%20this.query(gql%60%5Cn%20%20%20%20%20%20%20%20%20%20query%20LoadEntity(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%24id%3A%20ID!%5Cn%20%20%20%20%20%20%20%20%20%20)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20getEntity(id%3A%20%24id)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20error%20%7B%20type%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mail%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...Entity%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%24%7BApi.fragments.Entity%7D%5Cn%20%20%20%20%20%20%60%2C%20%7B%20id%20%7D).then(res%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20if%20(res.data.getEntity.error)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20throw%20new%20Error(res.data.getEntity.error.type)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20return%20res.data.getEntity.mail%3B%5Cn%20%20%20%20%20%20%7D)%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

**Comment by hundsim** [comment]
As this was closed - was there eventually any solution to this or are we out of luck if we for example use `styled-components`?

**Comment by j-f1** [comment]
@hundsim This issue should be fixed. If you’re having formatting issues, please open a new issue and fill out the template so we can more easily track them.
