### ISSUE TITLE
Error thrown on no file matching glob in 2.0.x

### ISSUE THREAD

**Issue by pburkindine** [prettier/prettier#7861]
**Environments:**

- Prettier Version: 2.0.2
- Running Prettier via: CLI
- Runtime: Node 12
- Operating System: OSX Cataline

**Expected behavior:**

Non-matching glob does not throw any error as in 1.x

**Actual behavior:**

Non-matching glob throws an error

We use the same prettier-config and prettier cli invocation for all of our repos, regardless of whether they currently contain files of a particular type.  This worked fine in 1.x but in 2.x this causes an error when a glob matches no files.

A warning would be better.

```
npx prettier --write \"{apps,libs}/**/*.{js,ts,css,scss,html,json,yaml,yml,md}\"

...

[error] No files matching the pattern were found: "*.yaml".
[error] No files matching the pattern were found: "*.yml".
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ccxp-client@0.0.1 prettier-all: `npx prettier --write "{apps,libs}/**/*.{js,ts,css,scss,html,json,yaml,yml,md}" && npx prettier --write *.{json,js,md,yaml,yml}`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ccxp-client@0.0.1 prettier-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pete.burkindine/.npm/_logs/2020-03-24T16_22_15_545Z-debug.log
```

**Comment by thorn0** [comment]
You pass only one glob, but Prettier complains about multiple globs. This happens because your shell expands the curly braces in your glob, so Prettier gets `apps/**/*.js apps/**/*.ts ...`. Try removing the backslashes in front of double quotes and letting Prettier expand those braces,

Besides, Prettier shouldn't be called like this, without pinning the version. See https://prettier.io/docs/en/install.html

**Comment by pburkindine** [comment]
The \ is there because it's a script in a package.json file, so can't be removed and still be valid JSON

I tried also with no quotes and with single quotes and got the same result (pinning to 2.0.2 in the cli invocation)

```
"prettier-all": "npx prettier@2.0.2 --write '{apps,libs}/**/*.{js,ts,css,scss,html,json,yaml,yml,md}' && npx prettier@2.0.2 --write *.{json,js,md,yaml,yml}",
```

```
[error] No files matching the pattern were found: "*.yaml".
[error] No files matching the pattern were found: "*.yml".
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ccxp-client@0.0.1 prettier-all: `npx prettier@2.0.2 --write '{apps,libs}/**/*.{js,ts,css,scss,html,json,yaml,yml,md}' && npx prettier@2.0.2 --write *.{json,js,md,yaml,yml}`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ccxp-client@0.0.1 prettier-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pete.burkindine/.npm/_logs/2020-03-24T17_55_34_752Z-debug.log
```

**Comment by thorn0** [comment]
I'm not familiar with macOS's shell. There must be a way to prevent it from expanding the braces. If you find it, please let us know.

The new CLI behavior was modeled after ESLint. ESLint issues errors for individual patterns. We're considering either issuing warnings instead or adding a `--no-error-on-unmatched-pattern` CLI option ([ESLint has it](https://eslint.org/docs/user-guide/command-line-interface#no-error-on-unmatched-pattern)).

**Comment by pburkindine** [comment]
Ah! We're making this too hard :D

The issue is actually the second part of the invocation (`npx prettier@2.0.2 --write *.{json,js,md,yaml,yml}`); wrapping the glob there in quotes solved the problem

I think the flag is still a good idea, though

**Comment by thorn0** [comment]
Closing this in favor of https://github.com/prettier/prettier/issues/8233
