### ISSUE TITLE
Unexpected space after two dashes in a template literal

### ISSUE THREAD

**Issue by everdimension** [prettier/prettier#7864]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlCBbOGACwEsoBzTAXkwwE8AbOAEwDpmSA3AAwB0pMmAEYBDMAGtyAJwgBXKMySZOIqQAoAtBoAkwaHAC+ASgDcmAPQAqTPLgAPAA5ww8ZrQdi4mEQDN4UzC1MS3N+QSEIKWY4KSUARgc7WggGEjcVdS1dGAB3CGMzKxsoeycXFndPbz8YwI1g0KhuE35+SCgMTAB1IhEsGg4eMOExSRl5RWVVTR09EoKLazQ4ODw0TAhxEToG4YiomPjE5NT06azgXPzTRdoVtY2tnZD+Zv4QABoQCAcYEnRkKBVDIcgAFVQINDIEAiBg5bZQr5CKSjQjYDxgMjkZAwKSyOBfIgwPAMHokeBoDFwbCQ8lccl0aFgNCIkBkZZSGCglHkPAiZA+WHLL4AKzQdgAQiiJGiRAQADJkOACoUEkBiuzYLFMACKsgg8BVDGFIA8Ug50NEQjgDE+pqkZBgXTSxGQAA4AAxfBwyZZdFEOaE+uAczjKr4AR318G5PyhKBEaA0JRYLDtUjgUZIGe5Il5-KQguNauWeBIOLxJe1cD1BuVhdVXxgIiEzuYrqQACYmyiSKkKABhfB86EhgCsdtkywAKi340WTZx8QBJBQIGDYMAO34AQQU2BgjHrC8MBiAA)
```sh
--parser babel
```

**Input:**
```jsx
const Something = styled.div`
  background: var(--${one}); /* unexpected space after -- */
  border: 1px solid var(--${two}); /* unexpected space after -- */
`;

const What = div`
  background: var(--${one}); /* seems okay */
  border: 1px solid var(--${two}); /* seems okay */
`;

```

**Output:**
```jsx
const Something = styled.div`
  background: var(-- ${one}); /* unexpected space after -- */
  border: 1px solid var(-- ${two}); /* unexpected space after -- */
`;

const What = div`
  background: var(--${one}); /* seems okay */
  border: 1px solid var(--${two}); /* seems okay */
`;

```

**Expected behavior:**

There should be no spaces after `--` in the first output.
Is there some hardcoded behavior for styled components?

**Comment by thorn0** [comment]
It's not a 2.0 regression, so might be a duplicate.

**Comment by everdimension** [comment]
Thank you!
