### ISSUE TITLE
Suggested way to ignore webpack files?

### ISSUE THREAD

**Issue by ragmha** [prettier/prettier#787]
I ran into an issue today when prettier-atom formatted my webpack, Adding trailing commas to resolving path,  luckily I was able to fix it by seeing the git difference and disabling prettier-atom.

What is the suggested way to use prettier and is there something like ` /* prettier-disable */ `?

Thanks!

**Comment by vramana** [comment]
Prettier doesn't have any such thing. You can should run prettier on the files you care about. May be you can file an issue on prettier-atom to implement a black-list.

**Comment by vjeux** [comment]
If you are using eslint integration, you can do /* eslint-disable prettier */. We need to figure out a holistic way to tell which files should be printed and which shouldn't. I'm going to close this issue as there are other issues tracking the same idea listed by @vramana above.
