### ISSUE TITLE
Add braces when single-line ifs wrap

### ISSUE THREAD

**Issue by jakearchibald** [prettier/prettier#7888]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAJnALYQAUAlPsADpT746r7mRSE67TUwAWAJwgB3fAFEBQgeQDkAIwCGhGZQDc9Rs1ZwFAgDYBPAEpwY6AVGoDT5hjAHo46hkxbkFUCPzgCAwtE5uS3x+IVEJKXIAAwA5BT4QvhwAZyIIOGSoGRh8YQgBAGt8VHzEuGKIPT0RHCgAc3xrBWToZMAyAii1egBfenoQABoQCAAHIOTkUF0wgAVdBAmUBQA3CBxCQZA5AQUwAtMAZRHd2rrke0chvhgSPQB1JPhk47A4A4WuHGWuA2RwZImQ1qyR8MBmOzqJAUyFQCj0IKGACtkgAPABCOz2hwUJDgABlanAYXCESBkSiDqc9HAAIroLxEpCw+FwIbHAQggR-RRyAzVKCbEYCWowO7rfjIAAcAAY2UIQXcdiM-kKMj5lkShgBHenwcGjRYgZoAWigcDgxA2Q2sOpw1nBCkh0KZJNZIBBJBw5wcbuSVNpusZzNJMAUcjFhAlSAATEN7AocHpTv4SFC-p4zZt0CCACphxbBuDdbpAA)
```sh
--parser babylon
```

**Input:**
```jsx
function demo() {
  if (condition) throw Error('bad');
  if (earlyReturn) return true;
  if (anotherCondition) throw Error(`Nah this doesn't work for the following reasons…`);
}
```

**Output:**
```jsx
function demo() {
  if (condition) throw Error("bad");
  if (earlyReturn) return true;
  if (anotherCondition)
    throw Error(`Nah this doesn't work for the following reasons…`);
}
```

**Expected behavior:**

I like single-line if statements for early exits and early throws, and I'm really happy that Pretty doesn't try and prevent that.

However, once the line length is reached, the statement goes onto the next line. Although single-line ifs are somewhat controversial, folks seem very much against the statement being on the following line. I've seen this go wrong in the wild, where folks don't realise the braces are missing, and add an extra statement that they expect to be part of the if. Prettier's formatting would correct the indenting of course, but maybe it's better to add the braces?

```jsx
function demo() {
  if (condition) throw Error("bad");
  if (earlyReturn) return true;
  if (anotherCondition) {
    throw Error(`Nah this doesn't work for the following reasons…`);
  }
}
```

This has probably been discussed already, but I couldn't find an existing issue.

**Comment by j-f1** [comment]
Three reasons we don’t do this:

1. One of Prettier’s main goals is to avoid changing the structure of the code. Adding braces would [change the AST](https://astexplorer.net/#/gist/eeb03cebe6274a9e84c695e57656a231/579733f0cab9c718e26cf36445ea79e3e404fdfd).
2. Prettier will [make it obvious](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAJnALYQAUAlPsADpT746r7mRSE67TUwAWAJwgB3fAFEBQgeVogARgENCsygG56jZqzgKBAGwCeAJTgx0AqNQGnzDGAPRx1DJi3IKoEfnAEBhaJzclhqM+HoQAOYAKhAAygoKseR0LqH4JHAAzpkKEXBI+ADkPlIAhIUhjAC+lJX4-EKiElLkAAYAcgp89Xw4mUQQWVCFMPjCEAIA1vioEz1wMxB64cI4UBH41gqZ0JmAZAStavRV9CAANCAQAA5Bmciguo0ACroIdygKesIKBncXcgIFGBJqZYlcgWsIsh7I4LnwYCQ9AB1XrwTLgsBwWJvLg4ABuXAMyHA2XOIDWmR8MCegIiJAUyFQn0pFwAVpkAB4AIUBwNBCgyABk1nBGcy4GzObFIXo4ABFdBeUVIJl6FkgcECSkCYmKORwPRkq4CNYwJE4Qj8ZAADgADBdjRBKUjAVdicasj48aKLgBHRXwGnXd4gbYAWigcDgxEIZOs-pw1hpuXpYrVEpAlJIOGhDgzmRl8oDytV6pgCjk5stfGQACYLvYFDg9JD-CRUygsgBWMnoSlRCvvUsZvGOACSHAQMFiYBNNwAghxYjADLK05SqlUgA) when you add a second statement to a non-block if statement:

   ```jsx
   function demo() {
     if (condition) throw Error("bad");
     if (earlyReturn) return true;
     if (anotherCondition)
       logToSaaS({
         message: "error!",
       });
     throw Error(`Nah this doesn't work for the following reasons…`);
   }
   ```
3. This is the kind of thing you could write an ESLint rule to fix automatically — check if there’s a `\n` in the text of the `consequent`, and return a fixer that wraps the statement in braces.

**Comment by jakearchibald** [comment]
Makes sense. Thanks for the explanation! Appreciated.
