### ISSUE TITLE
Code coverage failing on PRs

### ISSUE THREAD

**Issue by sidharthv96** [prettier/prettier#7893]
The github workflow for coverage running on node 12 - ubuntu is consistently failing across PRs.

**Comment by sidharthv96** [comment]
@sosukesuzuki You are also facing the same issue right?

**Comment by sosukesuzuki** [comment]
@sidharthv96 yes, the action seems to fail if the test takes a long time to run. This is a problem, but unfortunately we will have to ignore it for now.

/cc @thorn0 @fisker Do you have a solution for this?

**Comment by sidharthv96** [comment]
![image](https://user-images.githubusercontent.com/10703445/77825514-d211b980-712f-11ea-8615-99cba1fee0f5.png)
Seems like coverage isn't generated at all.

**Comment by fisker** [comment]
Not sure how to fix it.

@sidharthv96 Is this from github actions job?

**Comment by sidharthv96** [comment]
@fisker No, that was from my local.

```
==> Detecting git/mercurial file structure
==> Reading reports
    - Skipping empty file ./coverage/lcov.info
--> No coverage data found.
    Please visit http://docs.codecov.io/docs/supported-languages
    search for your projects language to learn how to collect reports.
```

This is from actions.

**Comment by fisker** [comment]
Local test don't collect coverage by default, you can run `yarn test --collectCoverage`.

**Comment by fisker** [comment]
Seems it stopped collect coverage from jest upgrade commit.

**Comment by sidharthv96** [comment]
I used ENABLE_CODE_COVERAGE flag. 
Yeah, downgraded jest and running test now.

**Comment by sidharthv96** [comment]
@fisker Tried downgrading to `25.1.0` and ran tests with `yarn test --collectCoverage`. Still no coverage locally. 

https://github.com/prettier/prettier/pull/7894 will help test the CI

**Comment by sidharthv96** [comment]
Any chance there is a mock fs?

> When using mock-fs make sure to run mock.restore() when your tests are done running, or else the reports wont get generated on the CI.

**Comment by SimenB** [comment]
This is a bug in Jest, fix here: https://github.com/facebook/jest/pull/9724

**Comment by SimenB** [comment]
Patch out: https://github.com/facebook/jest/releases/tag/v25.2.4

**Comment by thorn0** [comment]
closed by https://github.com/prettier/prettier/pull/7901
