### ISSUE TITLE
Prevent adding of parenthesis around ternary

### ISSUE THREAD

**Issue by mathildebuenerd** [prettier/prettier#7898]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExJQCYEsZegAgF5j8YAnAVznwB0p98B+fAHmwDcA+AFQAssAzvnTZcBQaUpwAhCwD0HTnQZJWivhJE489CQDMAhgBsBcAHQX5iugF8QAGhAQADmKgDkoA2TIQA7gAK3ggeKMZ+BgCeHo4ARmQGYADWcDAAys6JWFAA5sjkVI68MAC2RgDq-PACmWBwaSHa7DiRyOACMSDZpmQwAQk5JQbIhiZwjgBWAgAeAEIJyalpBiVwADLZcCPGppMzadk5RnAAihQQ8NtjjplkPW2xBrFwRg4gzmTZMOVYGDC8yAAHAAGG6+UzlBLONofOA9dhbRwAR3O8H6LlCIAMAgAtFA4HAMIS3mQ4CisKT+gZBsMkKNdiBTCUsPkpI4BIdjmcLls6TtxiAYE8fn8AUgAEyOcgGLBGQ4AYQgJSGbThAFY3hRTNwnqF6QL2FQAJKYBDpMCfVwAQUwaRgkWOV1MNhsQA)
```sh
--parser babel
```

**Input:**
```jsx
{condition === true 
  ? <div>This condition is true!</div>
  : <div>This condition is false...</div>
}
```

**Output:**
```jsx
{
  condition === true ? (
    <div>This condition is true!</div>
  ) : (
    <div>This condition is false...</div>
  );
}

```

**Expected behavior:**
I expect the input to not to be changed. Can I configure Prettier in a way that it will not add these parenthesis around the content?

I saw this thread already https://github.com/prettier/prettier/issues/4714 but I don't understand what is the conclusion of it. Is there an option to configure this?

Thanks!

**Comment by sosukesuzuki** [comment]
No, Prettier has no option for this! See https://prettier.io/docs/en/options.html

**Comment by sosukesuzuki** [comment]
I think the expected output of this Issue makes sense. But, I don't know the status of this.

**Comment by thorn0** [comment]
This is intended, documented (see https://prettier.io/docs/en/rationale.html#jsx), and won't change.

**Comment by sosukesuzuki** [comment]
I didn't know it, thanks
