### ISSUE TITLE
 .prettierignore rule doesn't work on Windows if file name contains emoji

### ISSUE THREAD

**Issue by webanimate** [prettier/prettier#7899]
I have  [.prettierignore file](https://github.com/webanimate/animate.web/blob/master/.prettierignore) where dist folder is set to be ignored. 
However if in that folder there is a file whose name contains emoji it is not ignored. It happens only on Windows. On Linux and MacOS everything works properly.

[Windows build on Travis](https://travis-ci.org/github/webanimate/animate.web/builds/668326604#L370):
![image](https://user-images.githubusercontent.com/60752454/77849200-22d5f080-71ca-11ea-89ff-8805053a0f20.png)

[Linux build](https://travis-ci.org/github/webanimate/animate.web/jobs/668325504#L458):
![image](https://user-images.githubusercontent.com/60752454/77849216-4ac55400-71ca-11ea-9668-84ed4ecba236.png)

[OSX build](https://travis-ci.org/github/webanimate/animate.web/jobs/668331299#L396):
![image](https://user-images.githubusercontent.com/60752454/77849254-9d067500-71ca-11ea-9234-b0231bc618a2.png)

**Environments:**

- Prettier Version: 2.0.2
- Running Prettier via: CLI
- Runtime:  Node.js v13
- Operating System: Windows

**Steps to reproduce:**
```
git clone https://github.com/webanimate/animate.web.git
cd animate.web\
git reset --hard 65b13107d66964f16850cc8500553535f1954bf3
yarn
yarn test
```

**Expected behavior:**
Ignore all files in /dist folder

**Actual behavior:**
All files are ignored except dist\fla😁sh.js

**Comment by thorn0** [comment]
As a workaround, you can try replacing `dist` in your ignore file with `/dist` or `/dist/`.

**Comment by webanimate** [comment]
@thorn0 I tried what you suggested but it didn't work.

**Comment by webanimate** [comment]
It doesn't help:
`/dist` [Build](https://travis-ci.org/github/webanimate/animate.web/builds/668635460#L373) [diff](https://github.com/webanimate/animate.web/commit/6a00ff18ed0f)
`/dist/` [Build](https://travis-ci.org/github/webanimate/animate.web/builds/668636050#L373) [diff](https://github.com/webanimate/animate.web/compare/6a00ff18ed0f...7b880794b2ff)
