### ISSUE TITLE
Trailing semicolon in inline style tags

### ISSUE THREAD

**Issue by bschlenk** [prettier/prettier#7907]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zU55qARhABMAnp27dUAgJYA3cgGcYQunAC8TEAAcAhgKlQA5knIBWDQA91osdwAScOnQgtrqAPRTpVt-2FfX7RhAAGhAIDRhJaDlkUC0AJziIAHdieIRolC06JK0haJDeOK0wAGs4GABlbTBJA2QYOIBXOBCAgHVKSXg5argK9K6ZLqFkcDl8kFq5ODiYYiL9Gi1kADMs6ZCAKzkzACEi0vKKrRo4ABlauFX1lpBtswra-WUARUaIeGu6Dc146bjRgFgpo4rUYG1JAIYJRkAAOAAMIQ0iWmbSKGlGyLg-2kVxCAEd3vB5mEMiAtHIALRQOBwAR04FxOCEyRM+ZaRbLJBrb63aY0ST1Jp8p6vIlXbk3EIwLS8CFQmFIABM0qKkjoT1wEBoS1G2OMwMa03wsoyPJ+0maAEkoPTYBUwKDwgBBW0VRTKL7TAC+3qAA)
```sh
--parser html
```

**Input:**
```html
<!DOCTYPE html>
<html>
  <body>
    <div style="padding: 5px">
      Hello
    </div>
  </body>
  </html>
```

**Output:**
```html
<!DOCTYPE html>
<html>
  <body>
    <div style="padding: 5px;">
      Hello
    </div>
  </body>
</html>

```

**Expected behavior:**

I would expect a trailing semicolon *not* to be added to inline style tags that contain a single property.

**Comment by j-f1** [comment]
Although both syntaxes are valid, I agree with you that we shouldn’t put a trailing semicolon on single-line `style` attributes just like we don’t put trailing commas on single-line objects in JS, which is what these strings are most similar to.

**Comment by bschlenk** [comment]
I'm working on a pull request but could use some help. I figured out the change would be in [printer-postcss](https://github.com/prettier/prettier/blob/master/src/language-css/printer-postcss.js#L88) somewhere. How do I tell the printer to only print the semicolon if the line ends up breaking?

This should stay as is:

```html
<div style="margin: 0; padding: 20px"></div>
```

But this would end up with line breaks and thus should have a trailing semicolon:

```html
// in
<div style="padding: 20px; margin: 0; color: blue; display: inline-block; position: relative"></div>

// out
<div
  style="
    padding: 20px;
    margin: 0;
    color: blue;
    display: inline-block;
    position: relative;
  "
></div>

```

**Comment by thorn0** [comment]
see https://github.com/prettier/prettier/blob/master/commands.md#ifbreak

**Comment by bschlenk** [comment]
Aptly named, thanks 👍

**Comment by fisker** [comment]
@bschlenk Changes in #7556 might help

**Comment by fisker** [comment]
I like the trailing semicolon, I always put one when I write inline styles, even only one property.

**Comment by bschlenk** [comment]
I agree with j-f1’s reasoning that an inline style is similar to an inline object, and for consistency’s sake, the trailing semi (much like the trailing comma) should be dropped. I could be convinced either way though.

I was holding off on bumping prettier to 2.0 in my team’s project because we have a lot of these single line style attributes in our test harnesses. I didn’t see anything about adding trailing semicolons in the 2.0 changelog, so it seemed like a bug to me.

**Comment by fisker** [comment]
I guess most style guide don't have opinion about inline style , but [this one](https://codeguide.co/#css-single-declarations) suggest keep `;` for single declarations . Though it's about css not html, still I prefer keep `;`.

Also, please check source code of this PR page, search `style="` github keeps it too.

**Comment by bschlenk** [comment]
Css in a string is a fairly different beast. That guide is talking about regular css on a single line - something prettier doesn’t even do, it’ll always reformat single line css onto multiple lines. 

Looking at prior art is a good idea, I’ll see if I can pull a few other repos and see what the most common convention is. 

As far as which convention is *prettier*, I think omitting is much cleaner looking.

**Comment by evilebottnawi** [comment]
> As far as which convention is prettier, I think omitting is much cleaner looking.

Agree

**Comment by bschlenk** [comment]
For the fun of it I wrote a script that checks what the most common convention is using github's code-search api. ~65% of files prefer to omit the semicolon. This is probably wildly inaccurate though, since github limits you to the first 1000 results, many of which looked auto generated.

**Comment by fisker** [comment]
@bschlenk I  like  your  analyze tool , but  there 
should be  some compressed results by machine. I saw  you filter the filename, can  you  also filter the result by  checking at least 5 line breaks in code? And don't worry about your PR, seems most prettier member like to strip the semicolon, so I'm going to accept that, just curious.
