### ISSUE TITLE
How to disable markdown inserting blank line after headings

### ISSUE THREAD

**Issue by chinwobble** [prettier/prettier#7909]
Using Prettier 2.0.2.
All default config.
I want to disable the blank line inserting after headings.
This conflicts with `vimwiki` auto generate table of contents.
I also have limited screen real estimate.
I've read through the documentation and checked the source code but couldn't find out how to do this without disabling all linting for markdown.

**Input:**

```markdown
# Contents
- [Section1](#Section1)
- [Section2](#Section2)

## Section1
xx

## Section2
xx
```

**Output:**

```jsx
# Contents

- [Section1](#Section1)
- [Section2](#Section2)

## Section1

xx

## Section2

xx
```

**Expected behavior:**
Have some ability to not inserting the blank line after the heading.

**Comment by evilebottnawi** [comment]
It is default behavior and we don't want to change it, please open an issue in `vimwiki`, it is valid markdown and should work
