### ISSUE TITLE
Curly braces and `from` keyword stripped off of `import` statements

### ISSUE THREAD

**Issue by 3dos** [prettier/prettier#7912]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA7hATgawGcAdKASwFsAHPGDYAXwwDNcIKMByQ9uGACzJQA5p1Kl0GAEa44AQyKlKNXHWAZUAKgyQKFBHU2Ymrdlx76AtFTlh8c4XDFQJmGfKIYYECEuq16UgwNTABhdn1YUhM2Dm5eDAgBOAwbOwcnEAAaEAgqGDJoQmRQOVw2LAAFMoRilDkANwgyABNskBlbfD4AZTShYWQYXABXOBz+GAoAGwB1QXhCNLge2rIChvWAT2RwQmKcoUI4VUrcBwo5ZGY5aeOcgCtCAA8AIXO7Xrl9ABkhOGut3uICezx6A2mcAAiiMkgCkDc7uMQDZcMdcLspHIpHBpu0qLghDBZq0BMgABwABhyBIgx1m5youwJcHRDQBOQAjrD4Gc8nUQHJCJYoHA4C1xe1ZNyyLIzhcrgigcjjhQyICkTlCBDoTz4cMxjkYNiSS0yUgAExG85kaYDcJ6RUgKDQDkgEbHAAq2LqiOBDTGAEkoBLYD0wIT8gBBEM9GBbSEa44MBhAA)
```sh
--arrow-parens avoid
--parser babel
--no-semi
--single-quote
--trailing-comma none
```

You may wonder what would be the use case for this kind of behavior. It happened to me as I wrote a generator cli for a project creating several files based on user input data and automatically applying a prettier format when those are generated. One of the files provides the empty import statement with the comment in the middle of the curly braces to invite the developer to import what he should from a precise package.

I currently use the first version commented with `// works` in the example to work around the issue.

**Input:**
```jsx
// works
import {} from 'something'

// breaks
import { /* comment */ } from 'some-package'

// breaks too
import {
  // Comment
} from 'some other package'
```

**Output:**
```jsx
// works
import {} from 'something'

// breaks
import /* comment */ 'some-package'

// breaks too
import // Comment
'some other package'

```

**Expected behavior:**
```jsx
// works
import {} from 'something'

// breaks
import { /* comment */ } from 'some-package'

// breaks too
import {
  // Comment
} from 'some other package'

```

**Comment by thorn0** [comment]
Strictly speaking, this doesn't break code. Still, better to fix it.

**Comment by fisker** [comment]
@thorn0 I'm trying to fix this, do you know is there tokens info in those parser? I can't find anything. We have to use source code? https://github.com/prettier/prettier/blob/aeeb2ff7a8231e2f3a0b2474fd35b4419fe0d97a/src/language-js/printer-estree.js#L1083-L1087
