### ISSUE TITLE
How to make prettier correct for new endOfLines?

### ISSUE THREAD

**Issue by kuworking** [prettier/prettier#7931]
After updating to the new 2.0.2 prettier, it nows marks every line of code (Windows 10) as an error

```
{
	"resource": "/c:/CODING/kuworking/src/components/index.js",
	"owner": "eslint",
	"code": {
		"value": "prettier/prettier",
		"target": {
			"$mid": 1,
			"external": "https://github.com/prettier/eslint-plugin-prettier#options",
			"path": "/prettier/eslint-plugin-prettier",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "options"
		}
	},
	"severity": 8,
	"message": "Delete `␍`",
	"source": "eslint",
	"startLineNumber": 1,
	"startColumn": 62,
	"endLineNumber": 1,
	"endColumn": 63
}
```

I then try to correct it with my usual `Shift+Alt+F`

But this corrects any other error except these EOLs

How can I change them?

**Comment by kachkaev** [comment]
👋 @kuworking see Prettier 2.0 blog post on this matter: https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-endofline-to-lf-7435httpsgithubcomprettierprettierpull7435-by-kachkaevhttpsgithubcomkachkaev

There was just a change in default option value, which means that you can restore old behaviour by providing `{ "endOfLine": "crlf" }` to Prettier. The specifics of how you do it depend on your use case. Related docs:

* https://prettier.io/docs/en/options.html#end-of-line
* https://prettier.io/docs/en/configuration.html

Given that this is not a bug or a missing feature in Prettier, I think that this issue can be closed 😉

**Comment by kuworking** [comment]
Yes yes, I know there has been a change, the question is how to apply the new end of lines to my files

My assumption was that prettier would correct and substitute all CRLF for LF

Maybe the answer is that prettier will only warn about this, but won't (or can't) change it?

*I've tried configuring it in vscode directly but it neither works

**Comment by kachkaev** [comment]
I think you can find more help if you try discussing this issue on StackOverflow, addressing it to the `eslint-plugin-prettier` community. Prettier docs mainly focus on isolated usage of Prettier, but there's also a page on [integrating with linters](https://prettier.io/docs/en/integrating-with-linters.html). You might want to simplify your setup by switching to `eslint-config-prettier` and use ESLint separately.
