### ISSUE TITLE
Incorrect Formatting Arguments in nested funtion

### ISSUE THREAD

**Issue by vin-ni** [prettier/prettier#7939]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAzArlMMCW0qA5nDAMIQ4wAUAlKsADpTroBOZW7rUcA7qgAK7CAFt8AZzg0anSRAA2ANzgAaVJwBWcPAwC8APkYs2bDJIB0nAIYATAGL5FMmAAsplgA432NsVaQ1HDsQjbuGgDkWDAYAByRGti4BNA0IewaduE2DMysZmz4GKjp7OwM2rq0GXQA3KaF6C4wqEGwIaj6qNkwNg0FTZBQCi6WihDENL25A41NFpb87PjwTi40802o7p4+fgGW7fCh4W5qW00zF4PbyXiEUGUVJrfbqMWltZpwOnjP9Uu22Gozg40mNEikDEXhacEigLe23kSlUNGOIUR73QAF9LAAjfBQOw0XaSOhA9BYwo46m46k4kBqEAQLypEbIUC+UT8MKcDkoGyKfg2ACekiZIHxfjAAGsyABlHxgInEZAwdhYdQgNwwMSKADqHngkmVcAVCEkq3wylWouQ4EkEuZROk7BgIhsxDENmQGCF0mZWkkAA8AEIy+UwBX+OAAGSJcD9Ae1wZDCtVLgAilgIPB1Zrtfs3Q78TZ8XBFJKvCtYAb8HZ3MgAIwAJgADMyaxBpAa-F4HTW4G7VJKAI65+AiVkSwWSAC0fDgdmXks4E-wnE93t9SH9ikDIGkEgLWuZVqgxGzk6TSA1Z5AfXx9cbbmQreZGpszlVlDEPodYcAFZJSwaQABVy1nfdD2ULUAEliQQaMwBWNkAEFiQVGBRRcZMDzgHEcSAA)

```sh
# Options (if any):
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": true,
  "printWidth": 120,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false
}
```

**Input:**

```jsx
  function getCount() {
    return new Promise((resolve, reject) => {
      fs.readFile(this.params.counterPath, 'utf8', function(err, data) {
        if (err) reject(err);
        let counter = data;

        fs.writeFile( this.params.counterPath, data, function(err) {
            if (err) reject(err);
            resolve(counter);
          }.bind(this)
        );
      });
    });
  }
```

**Output:**

```jsx
function getCount() {
  return new Promise((resolve, reject) => {
    fs.readFile(this.params.counterPath, 'utf8', function (err, data) {
      if (err) reject(err);
      let counter = data;

      fs.writeFile(
        this.params.counterPath,
        data,
        function (err) {
          if (err) reject(err);
          resolve(counter);
        }.bind(this)
      );
    });
  });
}

```

**Expected behavior:**
Keep formatting as input -> the arguments in the nested function stay in one line.

**Comment by evilebottnawi** [comment]
For me the current output is better and readable

**Comment by vin-ni** [comment]
- fs.readFile(this.params.counterPath, 'utf8', function (err, data) {...}
- fs.writeFile(this.params.counterPath, data, function (err) {...}

should be formatted differently?

**Comment by thorn0** [comment]
They're formatted differently because of `.bind(this)`. The callback of `readFile` is formatted like that because it's a common expectation. On the other hand, `.bind(this)` isn't common. Everybody uses arrow functions instead, so we won't change the output for it.

**Comment by vin-ni** [comment]
Ok, thanks for the explanation!
I should use arrow functions anyway...
