### ISSUE TITLE
Ignores printwidth in JSX

### ISSUE THREAD

**Issue by jefflindholm** [prettier/prettier#7941]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflHz42MdGofBm9fXwAeHCgAB3R9GABPaLgeQSh0AFsAIydBfGgAYSFDLhTgOF4APk98UxgAERxmHBgGOAA6GENqZg52+2N0M3wABjcAbnwXF3wBkiGeYDomls0AbRGAXRmAekrQsLdvFxBxEAho3GhNZFBu6ggAdwAFboQblGNHwwSbs6zqIYwABrDgAZWiQKizGQMGoQzOQhgGRIFCELTgmkhYDgYPeLRw9haCWQ4E0fxAUVM1Bgz0BzAyhmQRhMZhAACtNAAPABCgJB4MMGTgABkonBmcZTGdOVywdDdABFdAQeCS1lnSHUamkrKGHIkU4gaLUKIwCg4OgwITIACMAA4RpqHqYKIDoqSTZinI4jQBHFXwOkXD4gQyaAC0UHYdDgdCNbADODYdMMDKZSBZ0pApgyOFh8LZ2i4SsDEszUrZXSyFqtNqQACYznDDDpoQUIBlGaTMQBWI02OAAFX1HyzbPsQwAklBY7AwWBTZcAIKzsGJXTq0zTIA)
```sh
--parser babel
--print-width 180
```

**Input:**
```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {
  return (
    <input type="number" onChange={e => { setDigit(e.target.value, 0); }} value={digits[0]} />
    )
}
```

**Output:**
```jsx
function HelloWorld({ greeting = "hello", greeted = '"World"', silent = false, onMouseOver }) {
  return (
    <input
      type="number"
      onChange={(e) => {
        setDigit(e.target.value, 0);
      }}
      value={digits[0]}
    />
  );
}

```

**Expected behavior:**
```jsx
function HelloWorld({ greeting = "hello", greeted = '"World"', silent = false, onMouseOver }) {
  return (
    <input type="number" onChange={e => { setDigit(e.target.value, 0); }} value={digits[0]} />
  );
}
```

 It is about 95 characters wide with indentation. I would expect JSX to work just like all my js code in the same file with the same settings. It SEEMS to wrap at the default of 80. I am fine if you actually want a different printWidth for JSX code, but at least let me set it.

**Comment by evilebottnawi** [comment]
Please use an issue template with link on playgound, otherwise issue was ignored, please respect the time other developers, thanks

**Comment by jefflindholm** [comment]
Updated

**Comment by j-f1** [comment]
This is because the `onChange` prop breaks — we always break block statements onto multiple lines, which the `{ ... }` in the arrow function is — and so we break the whole statement onto multiple lines.

**Comment by thorn0** [comment]
This works as expected and won't change.
