### ISSUE TITLE
Extra trailing commas in template literal.

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#795]
Run prettier on: https://github.com/cpojer/jest/blob/master/packages/jest-cli/src/TestNamePatternPrompt.js#L91

```js
         pipe.write(
            // eslint-disable-next-line max-len
            `\n  ${chalk.dim(`\u203A and ${more} more ${pluralizeTest(more)}`)}`,
          );
```

turns it into this:

```js
          pipe.write(
            // eslint-disable-next-line max-len
            `\n  ${chalk.dim(`\u203A and ${more} more ${pluralizeTest(more,)}`,)}`,
          );
```

**Comment by yamafaktory** [comment]
Are you using the latest version? This is what I get:

```js
pipe.write(
  // eslint-disable-next-line max-len
  `\n  ${chalk.dim(`\u203A and ${more} more ${pluralizeTest(more)}`)}`
);
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20%20%20%20%20%20pipe.write(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20eslint-disable-next-line%20max-len%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%60%5C%5Cn%20%20%24%7Bchalk.dim(%60%5C%5Cu203A%20and%20%24%7Bmore%7D%20more%20%24%7BpluralizeTest(more)%7D%60)%7D%60%2C%5Cn%20%20%20%20%20%20%20%20%20%20)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D.

**Comment by cpojer** [comment]
Yes I used 0.19 just a moment ago.

**Comment by yamafaktory** [comment]
I can't reproduce it with the latest version, even locally (Flow or Babylon). Any idea @vjeux?

**Comment by vjeux** [comment]
The issue is that the code that removes softline inside of template literals doesn't remove trailing commas.

repro case:

```js
./bin/prettier.js test.js --trailing-comma=all
`\n                               ${chalk.dim(`\u203A and ${more} more ${pluralizeTest(more,)}`,)}`;
```

cc @jlongster

**Comment by jlongster** [comment]
Shoot, that's a good point. I suppose we should try to eagerly evaluate `ifBreak`... I'll open a PR to see if it works.
