### ISSUE TITLE
Prettier 2.0 breaks on decorators wrapping functions

### ISSUE THREAD

**Issue by brokenalarms** [prettier/prettier#7950]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACGBDAzgawwEtdiBbABwgCd4ATDAM2ojIzjICM5qBaSKGACu1agjABPADpRGQwTCLQsefAAoAlBmABfGTLAAbPKQCiAD2yVDcbTIwOMAARwE1chUqgAqNQEchHgkMAF4MAHJwrWB7Rwd0FQIMTgg6aSgHHQ0AOjFcHFpsThtNWIB9GAkKOGwACxq6AGUa6jBagBVVWJkdEAAaEAgKRWhcZFBsUQgAdwAFSYQxlGxDaewJMYHOamwwfDgYRopdoigAc2QYakCB2pgyQwB1WqJ4XGOwOGaoXFeiADdXhJkOBcJsQKdcDwYLMdmcyNhkIwVlCBgArXDmABCOz2B0aVjgABlTnAkSi4OjMY1TmcbABFIQQeDkwyokDHahQ6ggzhFOCGfoc6inGCPIh0GC1ZAADgADAMKCwoY8dhQQUq4Nz-mSBgFmXBYUMliA8LwoHA4HQrUKxAEiGJYdh4YikMi2ZSQFCyERLtdPb9zgymSy3RSBjhOOLJdKkAAmCM7IiGWkAYVYCJBWoArEKhFDOpwlu72f9AgBJKDW2CNMAi4YAQSrjUqNlZUJ0OiAA)
```sh
--parser babel
```

**Input:**
```jsx
// task is imported from ember-concurrency
function task() {}

class Example {
    @task(function*(query = '') {
      // task body
  }).restartable()
  _typeaheadSearchTask
  
}
```

**Output:**
```jsx
SyntaxError: Unexpected token (7:5)
   5 |     @task(function*(query = '') {
   6 |       // task body
>  7 |   }).restartable()
     |     ^
   8 |   _typeaheadSearchTask
   9 |   
  10 | }
```

**Expected behavior:**
This code is already throughout our code base and works fine with existing Prettier ^1.19.1

**Comment by thorn0** [comment]
I'm actually reluctant to call this a bug. Decorators are a proposal whose syntax is in flux, and it's probably not realistic to expect from Prettier to support every prior draft.

As a workaround, try using the `typescript` parser if you can. TypeScript supports that syntax.

**Comment by brokenalarms** [comment]
Thanks for your answer! Hmm, we would be introducing 2.0 to take advantage of the new glimmer parser for our handlebar files. I guess we could auto format with the glimmer parser for hbs files and typescript for JS, though we don't use TS.

[Daniel - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=g9a7h)	[g9a7h]

On April 4, 2020 at 16:43 GMT, Georgii Dolzhykov <notifications@github.com> wrote:

I'm actually reluctant to call this a bug. Decorators are a proposal whose syntax is in flux, and it's probably not realistic to expect from Prettier to support every prior draft.

As a workaround, try using the typescript parser if you can. TypeScript supports that syntax.

**Comment by thorn0** [comment]
The `typescript` parser might not work for you if you use other proposals supported only by Babel, e.g. do-expressions or logical assignment operators. Also note that Prettier 2.0 with the `babel` parser will format your code if you add parens around the expression after `@`:
```js
class Example {
  @(task(function*(query = '') {
    // task body
  }).restartable())
  _typeaheadSearchTask 
}
```
By the way, that's how Prettier 1.19.1 formats it, so I don't understand why your code is without those parens if you're saying you're already using Prettier 1.19.1.

As for Glimmer support, please note that it's still in experimental stage. Its development is discussed in https://github.com/jgwhite/prettier/issues/1.

**Comment by thorn0** [comment]
Closing this issue and #4136 as the demand for this legacy syntax in JS seems to be really low.
