### ISSUE TITLE
Keep single valued JSON arrays on the same line

### ISSUE THREAD

**Issue by GrimLink** [prettier/prettier#7955]
With both the VSCode plugin and via the Cli, using v1.19.1 and v2.0.2.
The single array is wrapped to a new line.

**Input:**
```jsonc
{
  "sass": {
    "includePaths": ["node_modules"]
  }
}
```

**Output:**
```jsonc
{
  "sass": {
    "includePaths": [
      "node_modules"
    ]
  }
}
```

**Expected behavior:**
```jsonc
{
  "sass": {
    "includePaths": ["node_modules"]
  }
}
```

On the playground weirdly the Expected behavior is used.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm0gM4CGeeuSm6W2OIAllGADYCuAJnAAoEwAWJymAbVxQIbAPoBbUUwZw+AXQzYAvhmUgANCAgAHGDWh5koAgCdTEAO6dTCIygIA3CDRaaQAI1MEwAazgwAMo6PnQA5sgwpkxwWtwwEgwA6tw08HghYHCBdmk0jmkAnsjgxO50eHCmMOzeYRIEyABmBAyVWgBWeAAeAELefgGBBBJwADJ0cM2t7SBd3YHhsgCKTBDw022xICGmlaYlXdDuOqZ0MEmuPMgAHAAMWqcQlUneOiWnclWOU1oAjmt4LVdPYQEQALRQOBwNhuLS2AE0Wy1Aj1RpIFpbLSVCQ0SLRbZ4JZwVbrKYYmbbGAEDyXFjXJAAJi0UQINAY4QAwhAJA0SiIoe4mJUACo0+yY2aOGIASSgbFggTAZz0AEF5YEYIVZJtKsplEA)
```sh
--parser json
```

Also in JS files the Expected behavior also used.
I found this issue only to effect json files.

I know there is also currently a discussion open to alway wrapping json arrays -> https://github.com/prettier/prettier/issues/2716
But for single values it makes no sense to wrap it.

**Comment by thorn0** [comment]
`package.json` isn't formatted the same way as other JSON files. Please see https://prettier.io/blog/2018/05/27/1.13.0.html#added-json-stringify-parser-for-jsonstringify-style-formatting-4450-by-ikatyang

**Comment by GrimLink** [comment]
Ah that makes sense, closing ->
Thank you for the quick reply @thorn0
