### ISSUE TITLE
Regression with TypeScript "as const" object literal in 2.0.3

### ISSUE THREAD

**Issue by wincent** [prettier/prettier#7956]
Playground hasn't updated to 2.0.3 yet, so this link was generated on 2.0.2 playground:

**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVAmgBQFEB9AWQEF9MBeTYAHSk2cwHIwALAQwCcux4PTABM4ANwCWYOKyRs0ABzhgJXADasANIxZtOvfoMyLlqtZgBmEtTLmsTK9Vp0thEnspgQeATztuPAW8fZyYWVg8AcwBXNV5La1s2KxtQ3TQIMABrOBg7DOzctPC0HwBbACMINSlMGqgs2TZ6xu0oAF9MLjRMSCgMAG5GEE0QCAUYCXRkUF4eCAB3fF4ENGQQdQWuHzXRir5CmABlBX4JKEjkGB5ouFGOGDK1AHUOCXhFfjgj1feJSRgPnWYDQuxA5zQcB4MHwfEiZS4yAs6khowAVmgAB4AIQOOWOXDKcAAMuc4EiUXcQBjMUdzpEbABFaIQeAUtSokCnHiQnjrQFKNBgHgSCYjLki2DPCTCGAcZAADgADKMFPNIc8+Ap1mq4LyxOTRgBHFnwWHjNYoboAWigcDgomE4o8JvccFhXHhiKQyI5VMhZQkVxu-vpTNN5J9lNGMC4FWlsvlSAATDG+NZ6QBhCBlBHrPUAVnF0Uh2Djlt9nLEtwAklBRLAjsLRTByPWjoCbOzIe12kA)
```sh
--parser typescript
```

**Input:**
```tsx
const TYPE_MAP = {
    'character device': 'special',
    'character special file': 'special',
    directory: 'directory',
    'regular file': 'file',
    socket: 'socket',
    'symbolic link': 'link',
} as const;
```

**Output:**
```tsx
const TYPE_MAP = {
  "character device": "special",
  "character special file": "special",
  directory: "directory",
  "regular file": "file",
  socket: "socket",
  "symbolic link": "link",
} as const;

```

**Expected behavior:**

The 2.0.2 behavior (above) is expected, but with 2.0.3, I get:

```tsx
export const LOG_LEVEL =
    {
        EMERGENCY: 0,
        ALERT: 1,
        CRITICAL: 2,
        ERROR: 3,
        WARNING: 4,
        NOTICE: 5,
        INFO: 6,
        DEBUG: 7,
    } as const;
```

Only happens with `as const` qualifier. Without it, formatting continues to be like in 2.0.2:

```tsx
export const LOG_LEVEL = {
    EMERGENCY: 0,
    ALERT: 1,
    CRITICAL: 2,
    ERROR: 3,
    WARNING: 4,
    NOTICE: 5,
    INFO: 6,
    DEBUG: 7,
};
```

**Comment by sosukesuzuki** [comment]
This happens for not only `as const`.
[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVAmgBQFEB9AWQEF9MBeTYAHSk2cwHIwALAQwCcux4PTABM4ANwCWYOKyRs0ABzhgJXADasANIxZtOvfoMyLlqtZgBmEtTLmsTK9Vp0thEnspgQeATztuPAW8fZyYWVg8AcwBXNV5La1s2KxtQ3TQIMABrOBg7DOzctPC0HwBbACMINSlMGqgs2TZ6xu0oAF9MLjRMADEICABuEE0QCAUYCXRkUF4eCAB3fF4ENGQQdQWuHzXRir5CmABlBX4JKEjkGB5ouFGOGDK1AHUOCXhFfjgj1feJSRgPnWYDQuxA5zQcB4MHwfEiZS4yAs6khowAVmgAB4AIQOOWOXDKcAAMuc4EiUXcQBjMUdzpEbABFaIQeAUtSokCnHiQnjrQFKNBgHgSCYjLki2DPCTCGAcZAADgADKMFPNIc8+Ap1mq4LyxOTRgBHFnwWHjNYoboAWigcDgomE4o8JvccFhXHhiKQyI5VMhZQkVxu-vpTNN5J9lNGMC4FWlsvlSAATDG+NZ6QBhCBlBHrPUAVnF0Uh2Djlt9nLEtwAklBRLAjsLRTByPWjoCbOzIe12kA)
**Input:**
```ts
const TYPE_MAP = {
    'character device': 'special',
    'character special file': 'special',
    directory: 'directory',
    'regular file': 'file',
    socket: 'socket',
    'symbolic link': 'link',
} as Foo;
```
**Output:**
```ts
const TYPE_MAP =
  {
    "character device": "special",
    "character special file": "special",
    directory: "directory",
    "regular file": "file",
    socket: "socket",
    "symbolic link": "link",
  } as Foo;
```

**Comment by Shinigami92** [comment]
I don't know if it's the same problem, but I think it might fit here:

_Somewhere in our code (real world example), only one example of eleven_

`v2.0.2`:
```js
    this.previewPlayerHandle = (setInterval(async () => {
      if (this.previewIsPlaying) {
        await this.fetchNextPreviews();
        this.currentPreviewIndex++;
      }
    }, this.refreshDelay) as unknown) as number;
```

`v2.0.3`:
```js
    this.previewPlayerHandle =
      (setInterval(async () => {
        if (this.previewIsPlaying) {
          await this.fetchNextPreviews();
          this.currentPreviewIndex++;
        }
      }, this.refreshDelay) as
        unknown) as
      number;
```

v2.0.2 is MUCH more readable and less noisy

---

Another example

`v2.0.2`:
```js
    this.intervalID = (setInterval(() => {
      self.step();
    }, 30) as unknown) as number;
```

`v2.0.3`:
```js
    this.intervalID =
      (setInterval(() => {
        self.step();
      }, 30) as
        unknown) as
      number;
```

... I will skip v2.0.3 and wait for a patch in v2.0.4+
