### ISSUE TITLE
Difference in detection in Linux / macOS

### ISSUE THREAD

**Issue by moltar** [prettier/prettier#7963]
Seems like there is a difference in carriage return handling between macOS and Windows.

Here is a GitHub action that is failing to run in Windows: https://github.com/ScaleLeap/semantic-release-config/runs/564240533?check_suite_focus=true#step:6:11

Exactly the same code passes under Linux: https://github.com/ScaleLeap/semantic-release-config/runs/564240546?check_suite_focus=true#step:6:1

I also tested on macOS locally and it also passes.

Prettier version: 2.0.4

**Comment by thorn0** [comment]
Please see the [Prettier 2.0 blog post](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-endofline-to-lf-7435httpsgithubcomprettierprettierpull7435-by-kachkaevhttpsgithubcomkachkaev) and the [docs for the `endOfLine` option](https://prettier.io/docs/en/options.html).

**Comment by moltar** [comment]
Thanks for the hints!

Seems to be related to #7825.

And https://github.com/actions/checkout/issues/135
