### ISSUE TITLE
Reformatting indication after pasting multi-line code

### ISSUE THREAD

**Issue by JStyle21** [prettier/prettier#7965]
Hi,

I was just wondering if there is something to be done when copy pasting a multi-line string or 2 lines in fact, where the second line\part  doesn't have any indication at all.
Right now prettier seems to resolve this when i write things manually i.e. adjusting the indication levels, but if i paste a multi-line where it isn't so then it's not being fixed which is something i need to do manually later :(

Note: i used template strings here but it doesn't matter

**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAOlYn01wIwgBMBPJAAgAMc8YBDAZyMaJtxbZgGYA6cmAB4wAqgzgAnAJJFyAXnIBzODABKcAI4BXOAxgBlGOICWUBQAp0IAA6MGAdwjjWIAJQBuTIP0BFADJzySz0AUV9ggGEAFXIAKnIAMRUAeQBZcgAFW3IAdQAJYJVgjKzZSwBqGwYGDyhcXEoAGhoAXyaoAF03EAaQCCsYI2gGZFA6cXEIO0zxBGGUOgAbOzoSYZ78cTowAGtlPRswEwVkQ20egAsYAFsF7POjeAYDuD1Zh6MANweSZHAq7pAJjE4hg6U2CiudGQADNFmIegArBgCABCmx2ezoVzgvhMcBO4jOICRAj0RwWcG8mgg8BhcLgPRs4mBv3wdHwcAWAKsxlg2SMRBg52QAA4AAyMiZibKbKy-Hk6CQffE9LQ0uBgvpzECMAC0UDgcCIRoBMy0RhmYLoEKhSFhC3hIDEVyMBKJDHJlOptLt9J69Hw-MFwqQACZ-ZsjAsjuEIFdIb8dABWAGaMSRdlzU4MkAfbSSKDG2B6MDGfoAQULBhIFLpDrgzWaQA)

```sh
# Options (if any):
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": true,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": true,
  "vueIndentScriptAndStyle": false
}
```

**Input:**

```JSX
   txtUserId = getRequestString("password");
txtSQL = "SELECT * FROM Pass WHERE Pass ="+pass;
```

**Output:**

```JSX
		body: `
		asdasd
		asd
		txtUserId = getRequestString("password");
txtSQL = "SELECT * FROM Pass WHERE Pass ="+pass;
    		`,
```

**Expected behavior:**
```JSX
		body: `
		asdasd
		asd
		xtUserId = getRequestString("password");
		txtSQL = "SELECT * FROM Pass WHERE Pass ="+pass;
    		`,
```

Also while i'm asking, is there any way to make it output like:
```JSX
		body: `
			asdasd
			asd
			txtUserId = getRequestString("password");
    			txtSQL = "SELECT * FROM Pass WHERE Pass ="+pass;
    		`,
```

**Comment by evilebottnawi** [comment]
Please use an issue template with playground link, respect time other developers, thanks

**Comment by JStyle21** [comment]
Sorry!, Added
Please consider removing the word "Tip" from the new issue description it was confusing as i thought this was optional.

**Comment by evilebottnawi** [comment]
Output expected, it is unsafe to remove characters from template literal, for example you can have code:
```js
const code = `

   example

`;
// True
const hasSpacesBeforeWord = / example/.test(code);
```

If we remove `spaces` the `hasSpacesBeforeWord` variable will be false. 
There are more complex examples of why we can’t change content of template literal. 

You can implement eslint plugin if you really need it.

We don't want to implement an option which could potentially break the code.

**Comment by JStyle21** [comment]
I can understand, but since i also prefer to have this (linting doesn't help me)
I will ask this question, is it possible to format the copied text when pasting? or is this more in a vscode area than prettier? because before i copied and pasted that, it wasn't inside template literals.
