### ISSUE TITLE
Prettier adds semicolon to end of codeblock in otherwise empty markdown file

### ISSUE THREAD

**Issue by AndrewRayCode** [prettier/prettier#7966]
**Prettier 2.0.4**
I was unable to create a playground for this because the playground appears to be javascript only

Node version: 12
Prettier version: 2.0.4

```sh
$ nvm use 12
Now using node v12.16.1 (npm v6.13.4)

$ npx prettier --version
npx: installed 1 in 2.406s
2.0.4

$  echo '```json\nhi\n```' | npx prettier --no-config --parser=babel
npx: installed 1 in 2.042s
```json\nhi\n```;
```

**Input:**
```
```json\nhi\n```
```

**Output:**

```jsx
```json\nhi\n```;
```

**Expected behavior:**
You can see the output has a semicolon at the end of it, which is unexpected in markdown

**Comment by sosukesuzuki** [comment]
Please use `parser=markdown`.
