### ISSUE TITLE
Use `vue-eslint-parser` parse `.vue` file first?

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7975]
So the invalid html won't pass to html parser, maybe can fix #6525 #6503 #6325 ?

Update: we should also try [`vue-component-compiler`](https://github.com/vuejs/vue-component-compiler)/[`@vue/component-compiler-utils`](https://github.com/vuejs/component-compiler-utils).

**Comment by evilebottnawi** [comment]
Need to try
