### ISSUE TITLE
Less :extend() unwanted space

### ISSUE THREAD

**Issue by andreaswilli** [prettier/prettier#7977]
**Prettier 2.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA7hATgawGcMBDYuADwAc4x4ATAHSgDowAbM44ZjDAMiSV4UegAoWhCAFs4AWg5cMkmfIgwAFnFwLOhYitlyAbtoCec9hGs3btqAHNdSku3YBKANzMAvs2boGABmeNIkMDAAlo4Y0GBwpA4k0aT09MQkUBgArlBYmQwYhFQk8aRB8LgYkFZQzGx63LwCQhQi4s18hvKK+spSRupaOr0GA-KmuBZWdrPWjs59ruzNXr4gADQgEFRR0ITIoCS4uBBYAArHCAcorvlmB1sARril+HAwAMolYNEOyDBcNk4FsNDBpOwAOoaSLwYqlOCfa6wyLGWFmZDgfSbEDRQjaGDnV4OMLIIKufFbABWhAoACFXmB3l8SLIADLROBkikgkA0iifP7sOAARWy6i5SHJ7EpIBKuHxuExwuxWyouGiMEhkXommQAA4AAxq074yGvKiY9VwRWmHEAR3F8CJOxuIDIcigcDg9B9ONwcEdkQDRJIJJI3JlvPx0kiAKB0aFoqdkulspgJCe2t1GmQACYtoDkuw-gBhGSklA2gCsOOy+IAKpmbmnecZgQBJUQIL5gDW7ACCok+MDMwsj+J8PiAA)
```sh
--parser less
```

**Input:**
```less
// works as expected
.class {
  &:extend(.some-class .some-other-class .some-very-loooooooooooooong-class all);
}

// formatting once again adds an unwanted space after colon
.class {
  &:extend(
    .some-class .some-other-class .some-very-loooooooooooooong-class all
  );
}
```

**Output:**
```less
// works as expected
.class {
  &:extend(
    .some-class .some-other-class .some-very-loooooooooooooong-class all
  );
}

// formatting once again adds an unwanted space after colon
.class {
  &: extend(
    .some-class .some-other-class .some-very-loooooooooooooong-class all
  );
}

```
The additional space after the color causes this error: `Unrecognised input in file styles.less` similar to #1967.

**Expected behavior:**
```less
// works as expected
.class {
  &:extend(
    .some-class .some-other-class .some-very-loooooooooooooong-class all
  );
}

// no additional space after colon
.class {
  &:extend(
    .some-class .some-other-class .some-very-loooooooooooooong-class all
  );
}

```

**Comment by thorn0** [comment]
Yes, regression. Output of 1.19.1:
```less
// works as expected
.class {
  &:extend(.some-class
      .some-other-class
      .some-very-loooooooooooooong-class
      all);
}

// formatting once again adds an unwanted space after colon
.class {
  &:extend(.some-class
      .some-other-class
      .some-very-loooooooooooooong-class
      all);
}
```
