### ISSUE TITLE
bracketSpacing doesn't add spaces within JSX codeblocks

### ISSUE THREAD

**Issue by n1k0** [prettier/prettier#799]
Prettier v0.19.0 with `bracketSpacing` [enabled](https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20Foo()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%7B%20foo%20%26%26%5Cn%20%20%20%20%20%20%20%20%3Cp%3Esome%20very%20long%20text%20here%20so%20we%20can%20see%20it%20wrapped%2C%20lol%20lol%20lol.%3C%2Fp%3E%20%7D%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22doc%22%3Afalse%7D%7D):

```jsx
function Foo() {
  return (
    <div>
      {foo &&
        <p>some very long text here so we can see it wrapped, lol lol lol.</p>}
    </div>
  );
}
```

Call me picky but I'd expect something like this:

```jsx
function Foo() {
  return (
    <div>
      { foo &&
        <p>some very long text here so we can see it wrapped, lol lol lol.</p> }
    </div>
  );
}
```

**Comment by vjeux** [comment]
cc @jlongster 

It also doesn't do it on

```js
<div foo={ bar } />
```

**Comment by jlongster** [comment]
Do we want this? bracketSpacing was only intended to object/array literals mainly. It doesn't mean unconditional spaces. I've honestly never seen JSX written that way.

**Comment by n1k0** [comment]
It's totally matter of taste and perception of what JSX is (I can't help but read it as plain JavaScript), just my OCD suggested that consistency what probably something good to have here.

**Comment by vramana** [comment]
`{expression}` in JSX is similar to `(expresson)` in JS. Along this line of argument, there shouldn't be spaces around expression surrounded by {}.

**Comment by jlongster** [comment]
@n1k0 I know you would like it that way but we make decisions based on the majority of users, and most people expect JSX to not have spaces, sorry :( It's tough to balance all these decisions but we need to make a call, so I'm closing this.

**Comment by rhengles** [comment]
@n1k0 I tried implementing this option in the simplest way possible, but I got some results that got weird formatting:

```diff
 long_obj = (
   <div
-    style={{
+    style={ {
       i: "dont",
       use: "bootstrap",
       and: "instead",
       use: "massive",
       objects
-    }}
+    } }
   >
     hello world
   </div>
 );
```
```diff
 <div>
-  {ExampleStory.getFragment("story") // $FlowFixMe found when converting React.createClass to ES6
-  }
+  { ExampleStory.getFragment("story") // $FlowFixMe found when converting React.createClass to ES6
+   }
 </div>;
```

I'm willing to support such a option [in my fork](https://github.com/arijs/prettier-with-tabs), but I'd like to get these issues solved first...
