### ISSUE TITLE
Consider heuristic for aligning table-like objects in Javascript

### ISSUE THREAD

**Issue by ppershing** [prettier/prettier#7993]
I know that prettier is quite opinionated about formatting but sometimes this gets annoying for constructs which are table-like (see example below). In such case, it would be wonderfull if prettier aligned the columns to make the resulting text more readable.
Obviously, the right heuristic is quite tricky. The questions we should ask are
1) when to trigger "table-like" formatting
- if all sub-objects have keys in the same order, this looks table-like and we should apply the formatting heuristic
- if objects have keys in different order, this is definitely not "table-like" and a normal heuristic is preferred.
- but what to do with "deleted" keys? It would be nice if prettier could handle occasional missing key with just skipping. But then, how many keys can be deleted for this to still be "table-like" and not two completely unrelated objects? No clear answers here
2) are the columns roughly of similar width or are there some outliers which would cause excessive spacing. What would be a good threshold
3) how much we would be willing to violate text-width constraint? Let's say one of 10 "rows" would be slightly over threshold, should we turn it into separate-key:value-per line (as it is right now) or should we rather want to squeeze it back to the table format?

All in all, I think that this is probably not worth the cost to implement (the heuristic seems to be too involved and the use-cases are usually found more in configuration files than in real code) but I wanted to get this idea across

**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEMCGAjdAGQEsBrOTAXkwG0AdKTTYSVARiUwHIA3HdrgBpMrAEyde-UUJERUAZgl8FXAL6CGTFnI7ccMsRLwG5i7mDUMAuiEEgIABxjFoAZ2SgcAJy8QA7gAK3gjuKPx+OACe7nZ4Xjhg5DAAyg4JxFAA5sgwXgCucHYAFjAAtqgA6kXE8K5pYHDJITXEPDWRyOCuMSAZrnBeMAHxmaU4yABm-P12AFauAB4AQvGJGMk4pXAkUHCT04Ug8wvJGZnoAIp5EPD7qDMgaV79Xp14+HCoto9eGTAVxAAJjAisgABwABjsDl8-Qq8QcnRhcBePD2dgAjtd4MNHKEQDhXABaXZwQFk75eOBY4hU4Y4UbjJBTe6HfqlYg5fJss6XbF7ZkHOy4PAA4GgpCiYXxYioM4AYQgpTGnRRAFZvnl+gAVfChFkPHgFACSUHJsGSYF+TgAgmbkjBIug7v1VKogA)
```sh
--parser babel
```

**Input:**
```jsx
let tableLike = [
  {col1: 'val1', col2: 'val2', col3: 'val3'},
  {col1: 'a', col2: 'b', col3: 'c'}
]
```

**Output:**
```js
let tableLike = [
  { col1: "val1", col2: "val2", col3: "val3" },
  { col1: "a", col2: "b", col3: "c" },
];

```

**Expected behavior:**
```js
let tableLike = [
  { col1: "val1", col2: "val2", col3: "val3" },
  { col1: "a",    col2: "b",    col3: "c"    },
];

```

**Comment by evilebottnawi** [comment]
Sorry, we don't want it, you can create an eslint rule for it, or create a custom plugin, already discussed
