### ISSUE TITLE
Auto-close JSX tags

### ISSUE THREAD

**Issue by Ro4052** [prettier/prettier#7998]
Hi, this is really more a question than a request. I was wondering why the JSX auto-close feature wasn't working for me anymore and then found this issue: #5442.

Someone suggested using [this library](https://github.com/yannickcr/eslint-plugin-react/blob/97a9f397d2a8a3ce3b2af893bdbb86bb2c1d4480/docs/rules/self-closing-comp.md) to re-enable the feature. However, in my hobby projects, I don't bother with ESLint as it's just extra setup that I don't want/need and I would normally just use the Prettier plugin for VSCode. Would it be possible to bring this feature back as an option?

**Comment by evilebottnawi** [comment]
> Would it be possible to bring this feature back as an option?

No, please read https://prettier.io/docs/en/option-philosophy.html

> I don't bother with ESLint

It is good practice to using linter on code

Sorry, it is current behavior and we don't want to change it
