### ISSUE TITLE
Couldn't resolve parser "postcss" when updated to v2.0.4

### ISSUE THREAD

**Issue by etylsarin** [prettier/prettier#7999]
I use prettier-stylelint to let prettier formart my scss files using my stylelint rules.
I have a problem since I upgraded from v 1.19.1 to 2.0.4
I have found that there was a similar issue with prettier-atom while ago: https://github.com/prettier/prettier-atom/issues/388

**Environments:**

- Prettier Version: 2.0.4
- Running Prettier via: prettier-stylelint
- Runtime: Node.js v10.18
- Operating System: macOS Catalina
**Steps to reproduce:**

prettier-stylelint --write --quiet 'src/**/*.{css,scss}'"

**Expected behavior:**
to pass all the formatting without throwing an error

**Actual behavior:**
I got an error:
prettier-stylelint [ERROR]: There was an error formatting "src/index.scss"

Error: Couldn't resolve parser "postcss"
    at resolveParser (/Users/myname/repos/project/node_modules/prettier/index.js:11341:15)
    at normalize$1 (/Users/myname/repos/project/node_modules/prettier/index.js:11436:18)
    at formatWithCursor (/Users/myname/repos/project/node_modules/prettier/index.js:15032:12)
    at args (/Users/myname/repos/project/node_modules/prettier/index.js:50675:12)
    at Object.format (/Users/myname/repos/project/node_modules/prettier/index.js:50695:12)
    at resolveConfig.then/Users/myname/repos/project/node_modules/prettier-stylelint/src/index.js:129:30)

**Comment by fisker** [comment]
Parser `postcss` is renamed to `css` in `v1.7.1`, removed in `v2.0.0`. https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-arrowparens-to-always-7430httpsgithubcomprettierprettierpull7430-by-kachkaevhttpsgithubcomkachkaev

**Comment by etylsarin** [comment]
@fisker thanks for a quick response, could you please point me to a fix? because I'm not aware of any parser usage by myself. That's probably something what's happening under the hood.

**Comment by brodybits** [comment]
The stack trace shows that `prettier` is called by `prettier-stylelint`. So I would recommend raising an issue there.

I did take a quick look at `prettier-stylelint`, seems to be not maintained, but it does specify `"prettier": "^1.7.0"` in its dependencies so I wonder if something may be wrong with your installation?

**Comment by fisker** [comment]
I saw  you opened  an issue there , but  seems that project hasn't update for  a  long  time .

Personally, I use stylelint with `stylelint-prettier` plugin.

**Comment by etylsarin** [comment]
@brodybits I raised a ticket there, however the project seems to be dead for a while, which is pity. I also realised that in its dependencies it relies on that old version of prettier. But in reality it suddenly stopped working when I upgraded prettier in my app.
@fisker yes I might replace it, but this isn't ideal, as stylelint-prettier inverts the workflow. I liked the workflow of prettier-stylelint because passing the document through prettier first and then enforcing stylelint rules makes more sense imho. Prettier has less customization and so, if I pass the document through stylelint firsts and then Prettier, Prettier can undo some of the rules that I want to enforce in stylelint. I simply would like to prettify and then apply linting rules - the same way how your prettier-eslint works. It would be awesome if your squad can also provide this officialy.

**Comment by zmeyc** [comment]
@etylsarin A temporary workaround until prettier-stylelint is fixed:

1. In project root, create patches/prettier-stylelint+0.4.2.patch with contents:
```
diff --git a/node_modules/prettier-stylelint/src/index.js b/node_modules/prettier-stylelint/src/index.js
index 124c00d..a6f12ec 100644
--- a/node_modules/prettier-stylelint/src/index.js
+++ b/node_modules/prettier-stylelint/src/index.js
@@ -60,7 +60,7 @@ resolveConfig.resolve = (stylelintConfig, prettierOptions = {}) => {
             prettierOptions.tabWidth = indentation;
         }
     }
-    prettierOptions.parser = 'postcss';
+    prettierOptions.parser = 'css';
     debug('prettier %O', prettierOptions);
     debug('linter %O', stylelintConfig);
```

2. In package.json, add to scripts:

```
  "scripts": {
    "postinstall": "patch-package"
```

3. `yarn add --dev patch-package`

4. `yarn install` will now patch the package.

**Comment by frederikocmr** [comment]
If you just upgraded patch-package, you can try running:
  
    patch -p1 -i patches/prettier-stylelint+0.4.2.patch
    npx patch-package prettier-stylelint

In case it does not works, in reply to:
    

> @etylsarin A temporary workaround until prettier-stylelint is fixed:
> 
> 1. In project root, create patches/prettier-stylelint+0.4.2.patch with contents:
> 
> ```
> diff --git a/node_modules/prettier-stylelint/src/index.js b/node_modules/prettier-stylelint/src/index.js
> index 124c00d..a6f12ec 100644
> --- a/node_modules/prettier-stylelint/src/index.js
> +++ b/node_modules/prettier-stylelint/src/index.js
> @@ -60,7 +60,7 @@ resolveConfig.resolve = (stylelintConfig, prettierOptions = {}) => {
>              prettierOptions.tabWidth = indentation;
>          }
>      }
> -    prettierOptions.parser = 'postcss';
> +    prettierOptions.parser = 'css';
>      debug('prettier %O', prettierOptions);
>      debug('linter %O', stylelintConfig);
> ```
> 
> 1. In package.json, add to scripts:
> 
> ```
>   "scripts": {
>     "postinstall": "patch-package"
> ```
> 
> 1. `yarn add --dev patch-package`
> 2. `yarn install` will now patch the package.

**Comment by evilebottnawi** [comment]
Close here, because it is problem on `prettier-stylelint` side, workaround above, we can't fix it on our side, sorry
