### ISSUE TITLE
Add `{tokens: true}` to parsers

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8017]
Both `@typescript-eslint/typescript-estree` `@babel/parser` `flow-parser` supports `{tokens: true}`.

I think with token info we can make some improvements (maybe comments print).

Example:

https://github.com/prettier/prettier/blob/aeeb2ff7a8231e2f3a0b2474fd35b4419fe0d97a/src/language-js/printer-estree.js#L1083-L1087

I think we don't have to check source code, instead we can check tokens between.

**Comment by thorn0** [comment]
Yes, I'm going to use `tokens` in https://github.com/prettier/prettier/pull/7161 to improve handling of comments with `--no-semi`.

**Comment by fisker** [comment]
I tried a little bit, seems not easy, many tests broken.
