### ISSUE TITLE
Odd line breaking behaviour for some HTML

### ISSUE THREAD

**Issue by beauroberts** [prettier/prettier#8018]
Apologies if this has already been flagged by another issue - I wasn't able to find one.

I have come across some odd breaking behaviour with the `html` parser. Image and playground link below:

**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQARgA2266AvADogBOEhcVAfKgJZSYCuMeMAnpnErgAFnDABrAEYQAHlTwsAJkNr0A+sEiK4AX3lhREuIrXYYMakPmKW6bJPomzFqyALFSQ9AHM11OOhwMGpsnDDyAPTMxJJwhHgAZhCWVKpwGlq6+h7kVD5+AUFqMXFMNljEvGpQ2AC2cKgRJYTMEVi4jCAANCAQmDAs0OjIoNjUtADuAApjCMMo2IQT2LzDPZLU2EYwAMo4YGzeyBYccD3CMLWEAOrCLPDtYHA7c-csAG73vMjgpN0gbEC1BgU023lq2GQCUWgR6ACt0DIAEKbbY7OpwAAybDgUJhZxACJkO0O9AAihwIPA8YRYSAcNQgT8Lld-phqGwYNclDBhMgABwABh67IggWum0wP3ZhWo71xPQAjpT4KC+vMQCQALRQODGYz-fzKlj+UHYcGQpDQ2kEwK1FjHainHroUlwClU3FW-E9GD2bmKXnIABMvs2LEIhwAwhBahCfgEAKz-DiBAAq9nm1rp71OAEkoNpYDswBz+gBBQs7Pj0GmBHQ6IA)

**Input:**

```html
<span class="role"><input type="checkbox" id="role_{code}" checked_attr="" disabled_attr="" class="sg_reset_input" /><label for="role_{code}" class="sg_reset_label">display_name</label></span>
```

**Output:**

```html
<span class="role"
  ><input
    type="checkbox"
    id="role_{code}"
    checked_attr=""
    disabled_attr=""
    class="sg_reset_input"
  /><label for="role_{code}" class="sg_reset_label">display_name</label></span
>
```

**Expected behavior:**

```html
<span class="role">
  <input
    type="checkbox"
    id="role_{code}"
    checked_attr=""
    disabled_attr=""
    class="sg_reset_input"
  />
  <label for="role_{code}" class="sg_reset_label">display_name</label>
</span>
```

**Comment by fisker** [comment]
You might want check this 
[HTML Whitespace Sensitivity] (https://prettier.io/docs/en/options.html#html-whitespace-sensitivity)

**Comment by beauroberts** [comment]
@fisker thank you! sorry for not catching that. closing!
