### ISSUE TITLE
Output of comment before slash in JSX end tag fails to parse

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#8030]
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgPlQehwHShy0JABoQIAHGAS2gGdlR0AnViAdwAU2EmU6ADad0ATyYUARq3RgA1nBgBlKnNpQA5shisArnAoALGAFshAdSO14DNWDjL+N2gDcbY5OAaSQGhnCsMNyymqboyABmwgEUAFYMAB4AQrIKSsropnAAMhpwUTGGIAmJyhqaQnAAinoQ8IVCsSBqrAGsXlLoUnBC5C2sGjAWtAAmMEbIABwADBRUHAEWslReC3DtrgUUAI518CHUAiDoDAC0UHBwo9f9rHB7tPch6GERSNFNxQGmtDr63wqVVq9QKHyKFBg3RG40mSAATJDZLQhBUAMIQUzhLwbACs-T0AQAKt0BJ9mq4DABJKA3WDKMCDGgAQVpyhgYiqjQCAF8eUA)
```sh
--parser babel
```

**Input:**
```jsx
<a><//
/a>

```

**Output:**
```jsx
<a><///
a>;

```

**Second Output:**
```jsx
SyntaxError: Unterminated JSX contents (2:3)
  1 | <a><///
> 2 | a>;
    |   ^
  3 | 
```

**Expected behavior:**
Add a space before the comment, or move the comment somewhere. This parses:

```jsx
<a></ //
a>;
```

**Comment by lydell** [comment]
Also happens for `/**/` comment.

**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgPlQegFR44A6UOWJIANCBAA4wCW0AzsqOgE4cQDuACpwSsU6ADY90AT1bUARh3RgA1nBgBlWooZQA5shgcArnGoALGAFtRAdVMN4zTWDhqh9hgDd7k5OGYyQbWY4Dhg+BR0LdGQAMzFg6gArZgAPACEFZVU1dAs4ABltOFj4kxBklLVtHVE4AEVDCHgS0QSQTQ5gjl9ZdFk4USp2jm0YawYAExhTZAAOAAZqWm5g6wVaX2W4Lo9i6gBHRvhwumEQdGYAWig4OAm7oY44Q4Yn8PRI6KQ41rLgiwY+iMf2qtQaTWK31K1BgfXGUxmSAATDCFAxRNUAMIQCxRXzbACsQ0MwQAKn1hD82h5jABJKD3WBqMAjegAQQZahgklqLWCAF9+UA)
```sh
--parser babel
```

**Input:**
```jsx
<a></**/
/a>

```

**Output:**
```jsx
<a><//**/
a>;

```

**Second Output:**
```jsx
SyntaxError: Unterminated JSX contents (2:3)
  1 | <a><//**/
> 2 | a>;
    |   ^
  3 | 
```

**Comment by fisker** [comment]
This is how fragment is printed

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAfKg9FgOlLdAbnxABoQIAHGAS2gGdlQBDAJzYgHcAFdhJihYAbLiwCeTCgCM2LMAGs4MAMpV5tKAHNkMNgFc4FOAFtpcACYXLAGRbb9LLXABiENiZYw625CBb6MBDkIAAWMCbCAOqhtPAM6mBwKgJxtABuceJ+YAxSIJoMcGwwPHJansgAZiJFFABWDAAeAEJyisoqLCZwNppw1bVGII1NKppawnAAivoQ8IPCdSDqbEVsftIs5sIhVGyaMFG0FjChyAAcAAwU+xBFUXJUfvtw6+kDFACOc-Bl1IJ-AwALRQOCWSwhNhwH60aFlJyVJA1JbDIomWi6AxoiZTWbzAbIoYUGDbY6nc5IABMJLktGEEwAwhATEiQG8AKwhfRFAAq20EKOW6UMAEkoNZYCowAcaABBCUqGDiKaLIoAX3VQA)
```sh
--parser babel
```

**Input:**
```jsx
<><//
/>;

```

**Output:**
```jsx
<></
  //
>;

```
