### ISSUE TITLE
Use single keyword to declare variable

### ISSUE THREAD

**Issue by iamplex** [prettier/prettier#8032]
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMA6UAEPMwBmEESGATgJZQDmOAvDgOQCMTANNngQEYCG5JDgrU6jJgCYmIdiAgAHGJXTJQA8hADuABQEI0yEHwA2mvgE8DsnuT5gA1nBgBleXdHIY5AK5xZACxgAW2MAdX9KeDQ3MDhnfUjKADdI80MwNCsQajQ4chhtWxogvmRCE1zZACs0AA8AIVsHJ2c+ILgAGWo4Moq-EBra51FjOABFbwh4XuNKkDdyXPJDGHN5ODQwKkUZeapYUMoAExh-ZAAOAAZZeQ1c0Nt5Q1uNvKSe2QBHSfhChQMUC8lu9duQ4N9KGDCnxiqUkOVZv1ckFKDM5mgRuMfj0kF5fLIYHweIcTmckBICbZKMZRABhCBBEqGEzGXbeXIAFSJAIRcySvgAklAjggXFtKIoAILC5yrUZouAAX0VQA)

**Input:**

```ts
const
  foo:string = '1',
  bar: string = '2'
```

**Output:**

```ts
const foo: string = '1',
  bar: string = '2'
```
my question is: would add some option to support format style like this?
* the keyword on a line without other code
* all variable on a new/same line and auto indent(tab or space by config file or editor setting) 

**Expected behavior:**
```ts
const
  foo: string = '1',
  bar: string = '2'
```

**Comment by evilebottnawi** [comment]
Thanks for the issue, but we don't want to change current output, our output is preferred most of developers + more readable, look at:
```js
const
  fooVeryVeryVeryVeryVeryVeryLong: string = '1',
  bar                                                   : string = '2'
```
```js
const
  foo: VeryVeryVeryVeryVeryVeyLong = '1',
  bar: string                                          = '2'
```

It is ugly and unreadable
