### ISSUE TITLE
Wrapping is too greedy for function call with two object literal arguments

### ISSUE THREAD

**Issue by roryokane** [prettier/prettier#804]
Input source code:

```javascript
deepCopyAndAsyncMapLeaves(
  { source: sourceValue, destination: destination[sourceKey] },
  { valueMapper, overwriteExistingKeys }
);
```

The output is still well-formatted [when I specify `printWidth: 80`][correct]:

```javascript
deepCopyAndAsyncMapLeaves(
  { source: sourceValue, destination: destination[sourceKey] },
  { valueMapper, overwriteExistingKeys }
);
```

But [with `printWidth: 100`][bad-looking], the output is harder to read:

```javascript
deepCopyAndAsyncMapLeaves({ source: sourceValue, destination: destination[sourceKey] }, {
  valueMapper,
  overwriteExistingKeys,
});
```

This 100-width formatting loses the 80-width version's property of clearly showing that there are two object arguments, and it doesn't even take up fewer lines of space. I would prefer the 80-width output even when width 100 is specified.

I am guessing this happens because arguments are greedily put onto the same line as the function call as long as they will fit. Instead, Prettier should look ahead at later arguments to see whether the argument list will be better balanced if it breaks that first argument onto a new line.

[correct]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22deepCopyAndAsyncMapLeaves(%5Cn%20%20%7B%20source%3A%20sourceValue%2C%20destination%3A%20destination%5BsourceKey%5D%20%7D%2C%5Cn%20%20%7B%20valueMapper%2C%20overwriteExistingKeys%20%7D%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

[bad-looking]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22deepCopyAndAsyncMapLeaves(%5Cn%20%20%7B%20source%3A%20sourceValue%2C%20destination%3A%20destination%5BsourceKey%5D%20%7D%2C%5Cn%20%20%7B%20valueMapper%2C%20overwriteExistingKeys%20%7D%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A100%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
There's been multiple similar reports (with arrays, arrow functions and now objects) and I think I have found a good heuristic. If the last two arguments are of the same type, we shouldn't do last element expansion.

@yamafaktory are you interested in implementing it? This shouldn't be too hard.

**Comment by yamafaktory** [comment]
@vjeux I will be happy to fix it 👍. Feel free to assign me to this issue in order to avoid duplicate work by any other contributor (by the way should be cool to be able to assign myself to any issue I want to fix)!

**Comment by vjeux** [comment]
@yamafaktory github only let people that have admin access to the repo be assigned an issue unfortunately :( But consider yourself assigned!

**Comment by vramana** [comment]
@vjeux @yamafaktory Assigned 😂
