### ISSUE TITLE
Prettier does not format empty line

### ISSUE THREAD

**Issue by AliShehzad18** [prettier/prettier#8042]
In my React Native code below, I'm expecting prettier to remove the empty line but it doesn't. Is this a bug?

```
screenOptions={{
  headerTitleStyle: {
    color: "#a41034",

    fontWeight: "bold",
  },
```

**Comment by thorn0** [comment]
This is intended. Please see https://prettier.io/docs/en/rationale.html#empty-lines

**Comment by AliShehzad18** [comment]
> This is intended. Please see https://prettier.io/docs/en/rationale.html#empty-lines

I was guessing this might be the case. However, my doubt grew when it was formatting the code below and not the code in my question.

```
<Stack.Screen
  name="AddContact"

  component={AddContactScreen}
  options={{
    headerTitle: 'New Contact',
  }}
/>
```
Isn't this not a code block as well(like the code in the question)? **Prettier** does indeed remove the empty line here.

**Comment by thorn0** [comment]
see https://github.com/prettier/prettier/issues/6047
