### ISSUE TITLE
Prettier bizarrely defaulting to tabWidth 4

### ISSUE THREAD

**Issue by mramato** [prettier/prettier#8043]
1. I work on a large open source project, [CesiumJS](https://github.com/CesiumGS/cesium), and we are making the switch to prettier.

2. We plan on using the recommended defaults for everything so there is no `.prettierrc` file.

3. Running `prettier` on the code base is causing an indentation level of 4 instead of the default of 2.

4. Pasting any of the source files directly into https://prettier.io/playground seems to use the correct default indent of 2.

5. Moving a source file outside of our repository and running prettier directly on that file has a default of 2.

6. I've confirmed that is no `.prettierrc` anywhere in the directory structure. Some `node_modules` have it defined in their package.json so I remove `node_modules` and ran `prettier` as a global install and the problem still happened.

7. We're using Node `v10.20.1` and prettier `2.0.4`. I also tried Node 12.

So I'm out of ideas as to where it's picking up the setting from. You can check out the tiny PR here: https://github.com/CesiumGS/cesium/pull/8744

**Comment by thorn0** [comment]
Your `.editorconfig` contains `indent_size = 4`. Prettier respects it.

**Comment by thorn0** [comment]
I totally agree that this needs to be documented better. Opened https://github.com/prettier/prettier/issues/8044.

**Comment by mramato** [comment]
@thorn0 Thank you! That was driving me crazy. Would you recommend we simply get rid of our .editorconfig now that we are using prettier?

**Comment by thorn0** [comment]
I'd recommend to adjust the settings in it instead if you want to switch to `tabWidth=2`. EditorConfig is used by other tools (e.g. IDEs), not only by Prettier. Also it applies to files that Prettier can't format (e.g. GLSL).
