### ISSUE TITLE
EditorConfig support needs to be documented better

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#8044]
Prettier supports [EditorConfig](https://editorconfig.org/), but the docs are almost silent about this fact. In particular:

- the "[Options](https://prettier.io/docs/en/options.html)" page must specify which options and how can be set via EditorConfig,
- the "[Configuration File](https://prettier.io/docs/en/configuration.html)" page should mention EditorConfig somewhere.

See also https://github.com/prettier/prettier/issues/6795

**Comment by Friksel** [comment]
+1
Totally agree. I was looking everywhere for editorconfig support and couldn't find anything on it in the docs at first. Until I found this 'issue', so thanks for that. Why be so silent about such a standard that when supported by Prettier only makes Prettier better?

**Comment by lydell** [comment]
> Why be so silent about such a standard

It’s just an oversight.

**Comment by ceafive** [comment]
Can I pick this up and work on it? The configuration files needs to be updated to include what the order of precedence for the `.editorconfig` file will be. Also explain how the recursive search for a config file will be

**Comment by AGBrown** [comment]
[pull 2760] added some documentation for editorconfig support, but #3213 reverted it., however here was [a note] left by duailibe:

> We should remember to comment the docs when including it again for 1.9

[pull 2760]: ../pull/2760/files#diff-76e731333fb756df3bff5ddb3b731c46
[a note]: ../pull/3213#issuecomment-343009769

**Comment by mrmckeb** [comment]
I hit this today and was very confused. I feel like this should be opt-in. Maybe a good change for the next major?
