### ISSUE TITLE
Lines with a JSdoc typecast do not respect line length

### ISSUE THREAD

**Issue by sk-** [prettier/prettier#8045]
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACACgJzjGASzhwwBMI4BnDKCGDAQwFcYIBbRosRgG14CeGAO45GABwB0AHSiQoVBuwEAZaAHMAaoxyFGAI15wAco3ZwMAXgyoAVLYwABGAPEXgAFQAWhKgEkqAEFNElUND1c4by4AZS8IZl4yD111dRIVQig4AHUxcXEs9QBfDFtMAAoAMwgIACEdBoAvAEoAbllZKuY5ImgMACsqCjAAYUZFPygAJXxmHCgKloxgWQwMPBh5qBt7Jxc3Fe9fAODQtSh1CLdomDiEpJTCNIys3PzCy9LyjGrahpwzXasmKnSg6GwmyIJBE+Ro+lYTDIZCYtDgwl4bwANINmIoMPo4Dw8RYYF4SHAAOQ0RgYGBiQiYy4iHzwKjiRhgOAyOTQfHKC5aHR6QwmMwWax2BzOSJHHz+IIhHBhS7XKJeWLxRLJVLpHCZbJ5CSfEplTBrdaWv71RqMVodKBdHpgPo7IYjcaTGZzBZLFYWzbbX5S-ayzzy05KlVXSK3e7ap4vfVvI0FIrfc07K01G2Au0tYFQUGO8GYXD4aGkSA4PAuwQYGo4TgwGlQFGiCQ0MkWJnUHnyfnR7S6AxGUzmKy7aUHdzHBVnZWCtVxrWPXWvQ0fdNmi2W345gFAh1O3qEfruiBjCYwKazLa+5arLOBhbBvYyw7hk6K87hWMau5Vx1Z49QNd5jW3cpd33f5bVaQtihALEQAgcRXSoZBQB0HAIGELAdAQDCUD4YRGAEDDkP0MQwAAa3wGIOTAIpkHpZg4GQrwYHYXgclZahGLgGJCMIIgADcRIEZBwCoCiQCyKgSBgXBGHUThkCqPgFOQoYAA86moui7nFMD1M09iQF0mIiiMABFZh6DgUzeC0kAORwBScCk-QDDgXgkNc3RYByQgyDJZAAA4AAZkPEHCFNTKTYuoEhRMc5CAEd7PgXBUKIkAJgAWmyOAyBK-y8Eywg8GU1TGCclyFPYQgWJwNjkKoay4Dshz6vMmADGC0KvGQAAmZD6UYRkilGDg1JQagAFZ-JJDwDCIjTnPM0S2KmUrYBiMBdDQwI2xiFwjF64piiAA)
```sh
--parser babel
```

**Input:**
```jsx
// Prettier does not automatically wrap.
const myLongVariableName = /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */ (fooBarBaz);

function jsdocCastInReturn() {
  return /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */ (fooBarBaz);
}

// Prettier wraps but add a newline, just because there's a trailing whitespace.
const myLongVariableName = /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */ 
      (fooBarBaz);

function jsdocCastInReturn() {
  return (/** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */ 
    (fooBarBaz));
}

// Prettier correctly formats and wraps the lines.
const myLongVariableName = /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */
      (fooBarBaz);

function jsdocCastInReturn() {
  return (/** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */
    (fooBarBaz));
}
```

**Output:**
```jsx
// Prettier does not automatically wrap.
const myLongVariableName = /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */ (fooBarBaz);

function jsdocCastInReturn() {
  return /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */ (fooBarBaz);
}

// Prettier wraps but add a newline, just because there's a trailing whitespace.
const myLongVariableName =
  /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */

  (fooBarBaz);

function jsdocCastInReturn() {
  return (
    /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */

    (fooBarBaz)
  );
}

// Prettier correctly formats and wraps the lines.
const myLongVariableName =
  /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */
  (fooBarBaz);

function jsdocCastInReturn() {
  return (
    /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */
    (fooBarBaz)
  );
}

```

**Expected behavior:**
`prettier` should automatically add new lines to wrap long constructs when using JSdoc casts, rather than having to manually add a line break. Also note that if you keep a trailing whitespace, `prettier` adds an extra new line.

**Comment by evilebottnawi** [comment]
@thorn0 I think it is not bug, for me it is feature

**Comment by thorn0** [comment]
This issue needs decomposing because there are multiple code samples and they seem to be about different problems.

1)
```js
const myLongVariableName = /** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */ (fooBarBaz);
```
This stays on one line probably because of https://github.com/prettier/prettier/issues/2482

But I'm not sure why somebody would write code like that instead of
```js
/** @type {ThisIsAVeryLongTypeThatShouldTriggerLineWrapping} */
const myLongVariableName = fooBarBaz;;
```

2) There is indeed a bug where trailing whitespace after an end-of-line comment changes the output. This needs fixing.

3) Printing of type casts in `return` can be improved, but how often do they happen? Is there a good reason to use them instead of `/** @returns ... */`?

**Comment by sk-** [comment]
@thorn0 the code (both declaration and return) you posted is not equivalent. Typecasts are required to cast the resulting object of a generic call, or when working with mocks, to just name a few.

Note that there is dedicated support to this syntax, for example https://github.com/prettier/prettier/pull/7011.

@thorn0 @evilebottnawi The code samples all show different flavors of the same bug, which is that prettier format the codes in different ways depending on whitespace.

**Comment by thorn0** [comment]
> the code (both declaration and return) you posted is not equivalent. Typecasts are required to cast the resulting object of a generic call, or when working with mocks, to just name a few.

Please, could you expand on why type casts are necessary in those situations and the other syntax that I mentioned can't be used?

**Comment by sk-** [comment]
Mocks in jest need to be type casted. See https://stackoverflow.com/a/60416990/1413687.

Also, when working with generics from Firestore you need to typecast the results.

For example, the following works

```js
this.ref =
      /** @type {FirebaseFirestore.DocumentReference<AccountModel>} */
      (firestore.collection('animals').doc(animalId));
```
but the following fails with the error: 

```
Type 'DocumentReference<DocumentData>' is not assignable to type 'DocumentReference<AnimalModel>'.
  Type 'DocumentData' is missing the following properties from type 'AnimalModel': name,
```

```js
/** @type {FirebaseFirestore.DocumentReference<AnimalModel>} */
this.ref = firestore.collection('animals').doc(animalId);
```

Note that adding the parentheses to the assigned value, also performs the cast, but prettier will remove it.

```js
/** @type {FirebaseFirestore.DocumentReference<AnimalModel>} */
this.ref = (firestore.collection('animals').doc(animalId));
```

For the return case with Firestore I see no other workaround other than typecasting, due to the same error posted above.

**Comment by thorn0** [comment]
> Note that adding the parentheses to the assigned value, also performs the cast, but prettier will remove it.

Because it's a bug (https://github.com/microsoft/TypeScript/issues/26635).

Your original example and my question was about variable declarations and return values, not about assignments
