### ISSUE TITLE
Two blank lines are inserted between a `case` statement and a comment, except on Windows

### ISSUE THREAD

**Issue by roryokane** [prettier/prettier#805]
Input source code:

```javascript
switch (node && node.type) {
  case "Property":
  case "MethodDefinition":
    prop = node.key;
    break;

  case "MemberExpression":
    prop = node.property;
    break;

  // no default
}
```

When formatted, the single blank line before the final comment is turned into two blank lines:

```javascript
switch (node && node.type) {
  case "Property":
  case "MethodDefinition":
    prop = node.key;
    break;

  case "MemberExpression":
    prop = node.property;
    break;


  // no default
}
```

This is unexpected behavior to me. Prettier never uses multiple blank lines in a row anywhere else, and in fact it collapses multiple blank lines into one blank line in other situations.

The extra blank line is inserted in the web tool [prettier.github.io/prettier/][output] (no matter what OS it is viewed with), and is also inserted when I or my coworker on Ubuntu run the `prettier` command-line tool. However, for my coworkers who run Windows, `prettier` keeps only one blank line between the `break;` and the comment instead of inserting an extra one. It's probably related to `\n` vs. `\r\n` line endings.

Some more-minimal input code that [still reproduces the problem][minimal-output]:

```javascript
switch (foo) {
  case "bar":
    doThing()

  // no default
}
```

Deleting the single blank line or deleting the comment avoids this issue.

[output]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(node%20%26%26%20node.type)%20%7B%5Cn%20%20case%20%5C%22Property%5C%22%3A%5Cn%20%20case%20%5C%22MethodDefinition%5C%22%3A%5Cn%20%20%20%20prop%20%3D%20node.key%3B%5Cn%20%20%20%20break%3B%5Cn%5Cn%20%20case%20%5C%22MemberExpression%5C%22%3A%5Cn%20%20%20%20prop%20%3D%20node.property%3B%5Cn%20%20%20%20break%3B%5Cn%5Cn%20%20%2F%2F%20no%20default%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

[minimal-output]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(foo)%20%7B%5Cn%20%20case%20%5C%22bar%5C%22%3A%5Cn%20%20%20%20doThing()%5Cn%5Cn%20%20%2F%2F%20no%20default%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thank you, this is indeed a bug and we should fix it.
