### ISSUE TITLE
Prettier cannot run through ESLint when ecmaVersion is specified

### ISSUE THREAD

**Issue by mihaiborbea** [prettier/prettier#8054]
**Environments:**
- Prettier Version: 2.0.4
- Running Prettier via: CLI (through eslint-plugin-prettier) 
- Runtime: Node.js v10
- Operating System: Windows WSL

**Steps to reproduce:**
1. Set prettier to run through ESLint via _eslint-plugin-prettier_ and _eslint-config-prettier_ as shown in official documentation.
2. Write some code that do not comply with formatting rules set in .prettierrc config files
3. Set the {parserOptions: { ecmaVersion: 6 } } in .eslintrc file
4. Run linting (eg _eslint '.'_)

**Expected behavior:**
Formatting errors should still be reported as with ESLint without ecmaVersion specified.
Example:
 70:3   error  Replace `··startMessageListening` with `startMessageListening,`  prettier/prettier

**Actual behavior:**
No error for the "rule" prettier/prettier is reported anymore.

**Comment by evilebottnawi** [comment]
Please open a issue in `eslint-plugin-prettier` repo
