### ISSUE TITLE
[Bug?] Symlink'd plugins in `node_modules` are not auto detected.

### ISSUE THREAD

**Issue by benallfree** [prettier/prettier#8056]
**Environments:**

- Prettier Version: 2.0.4
- Running Prettier via: VSCode, CLI
- Runtime: Node 12.16.2
- Operating System: OS X

**Steps to reproduce:**

1. Use `npm` to install  [prettier-plugin-organize-imports](https://www.npmjs.com/package/prettier-plugin-organize-imports)
2. Run `prettier foo.txs`
3. Observe that imports are correctly organized

This time, use `pnpm` which uses symlinks instead of copying packages to `node_modules`:

1. Use `pnpm` to install [prettier-plugin-organize-imports](https://www.npmjs.com/package/prettier-plugin-organize-imports)
2. Run `prettier foo.tsx` from the command line
3. Observe that imports are *NOT* organized

Now, add the plugin explicitly to `package.json`:

```json
  "prettier": {
    "plugins": [
      "./node_modules/prettier-plugin-organize-imports"
    ]
  }
```

Repeat step 2 above and observe that plugins are now organized.

**Expected behavior:**

Symlink'd plugins in `node_modules` are auto detected.

**Actual behavior:**

Symlink'd plugins in `node_modules` are not auto detected.

**Comment by fisker** [comment]
I don't think we support `plugins` option. 

Can you try `node -p "require.resolve('prettier-plugin-organize-imports')"`?

**Comment by thorn0** [comment]
Prettier does support the `plugins` options. See https://prettier.io/docs/en/plugins.html

**Comment by aparajita** [comment]
@thorn0 It's true you don't support the `plugins` option, but the issue is still valid. Plugins installed via `pnpm` are not auto-detected because their entries in node_modules are symlinks, not directories.

**Comment by fisker** [comment]
I can reproduce on local, run `pnpm add prettier`, Prettier will be installed in `node_modules/.pnpm/prettier@2.1.1/node_modules/prettier`, then we use `findParentDir` to find `node_modules`, it will be `node_modules/.pnpm/prettier@2.1.1/node_modules` and nothing is in there.

**Comment by ZeroAurora** [comment]
Experiencing the same bug. But things are worse, because `plugins` in my `.prettierrc` won't be detected too.

**Comment by Shinigami92** [comment]
I was affected by exactly the same: https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/34

IMO it should work out of the box.
I prefer `.prettierrc.json` instead of `.prettierrc.js`, because then you have support from jsonschema.

**Comment by arimgibson** [comment]
@Shinigami92 posted an example of this workaround on another thread, thought I'd link here for those wanting a temporary solution. It's a little bit of manual configuration, but pretty minor IMO.

https://github.com/prettier/plugin-pug/blob/3c6dd7222b65fea5c2ba69ddbb00dbed56d70b86/.prettierrc.cjs#L8
