### ISSUE TITLE
Feat: Add curly brackets when breaking up long if statement

### ISSUE THREAD

**Issue by mesqueeb** [prettier/prettier#8059]
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQEIDOEAtnAMIAWcYA1gJSYzkBOEA7plHOwKJMtPYAOiACGmAG5wmAT0wAbaAHNMU-phL58IxXEyKIcfJkpNdjETExgRAV3yHMYzqzmpOw2oKggANCAgADjCo0PjIoCJ8bAAKkQhhKCJyrCLSYX4ARkwiNHAwAMoBOW6KyDBMNnB+5DBEcgDq5Kjw+EVgcPnxzajizdLI4Jq+aFD2TDDR2YpEIsjoSfZ+AFb4AB4AQtm5BSIkADJucHMLVSArq-klcnAAijYQ8MdyiyBFTGMDGSIZcHLDAUw3DB6qgACaMZAADgADH4ARB7PVsgEBgDDFJJMMAI73eCTQIJUT4AC0nDgoPJw1MONQpkm2hmTxe9iIqDKFVO+Cut1xRyQ82epxg3xB4PIyAATH5yiJUK4oIpSMRGShDABWYZ2OAAFW+CQFL3ElQAklAKbB8mBAUEAIJm-IwaTXJlwAC+rqAA)

**Input:**

```jsx
if (!someCheck) throw new Error("a very long error message goes here that causes a newline")
```

**Output:**

```jsx
if (!someCheck)
  throw new Error("a very long error message goes here that causes a newline");
```

**Expected behavior:**
```jsx
if (!someCheck) {
  throw new Error("a very long error message goes here that causes a newline");
}
```

I believe that only indentation is not safe enough and easily overlooked in a case like I describe above.

Is it possible to have prettier add curly brackets whenever it creates a new line to break up a long single-line if statement?

**Comment by thorn0** [comment]
This is out of scope for this project. See https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about
