### ISSUE TITLE
Blank lines are lost in files that contain only comments

### ISSUE THREAD

**Issue by roryokane** [prettier/prettier#806]
Input code:

```javascript
/**
 * @typedef {DataDrivenMapping|ConstantMapping} Mapping
 */
/**
 * @typedef {Object.<String, Mapping>} ConfigurationMapping
 */

/**
 * @typedef {Function} D3Scale - a D3 scale
 * @property {Function} ticks
 * @property {Function} tickFormat
 */
```

The blank line in the middle, which separates groups of related [JSDoc `@typedef`s](http://usejsdoc.org/tags-typedef.html), is lost [when Prettier reformats][output]:

```javascript
/**
 * @typedef {DataDrivenMapping|ConstantMapping} Mapping
 */
/**
 * @typedef {Object.<String, Mapping>} ConfigurationMapping
 */
/**
 * @typedef {Function} D3Scale - a D3 scale
 * @property {Function} ticks
 * @property {Function} tickFormat
 */
```

I would expect the blank line to be preserved, the same way Prettier preserves single blank lines between blocks of code. These JSDoc `/** */` comments basically *are* blocks of code that just happen to syntactically be comments.

### A more minimal example

Input:

```javascript
// a

// b
```

The blank line [is still lost][minimal-output]:

```javascript
// a
// b
```

But adding non-comment code anywhere in the file causes the blank line to be preserved:

```javascript
code();
// a

// b
```

The above [stays unchanged][minimal-working-output] after reformatting.

[output]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F**%5Cn%20*%20%40typedef%20%7BDataDrivenMapping%7CConstantMapping%7D%20Mapping%5Cn%20*%2F%5Cn%2F**%5Cn%20*%20%40typedef%20%7BObject.%3CString%2C%20Mapping%3E%7D%20ConfigurationMapping%5Cn%20*%2F%5Cn%5Cn%2F**%5Cn%20*%20%40typedef%20%7BFunction%7D%20D3Scale%20-%20a%20D3%20scale%5Cn%20*%20%40property%20%7BFunction%7D%20ticks%5Cn%20*%20%40property%20%7BFunction%7D%20tickFormat%5Cn%20*%2F%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

[minimal-output]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20a%5Cn%5Cn%2F%2F%20b%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

[minimal-working-output]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22code()%3B%5Cn%2F%2F%20a%5Cn%5Cn%2F%2F%20b%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thank you for those extremely well detailed issues, they are all valid points and we should fix them. Keep them coming!

**Comment by yamafaktory** [comment]
I will try to fix!
