### ISSUE TITLE
arrow function should not wrap when used as argument

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier#8066]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaCuAjAWwEssBeTHNOAWTgIgAoAdKTN9thgSk1ID4WHIewAmcPBBxQwcBgwBuAQwA2OOGiSZFUAJ49+mYIOEm2kKBkOYADorRoA7hABOIzAF9emJavUBuY1Nhc0siNAAxImVlOBEABTtHFzdyW3snV0wAMiybRIyRADoYZyICbkwAQlJyAHJagKhAoI4iADNMBjDI6NiE9OSeI1YWoKoYADUwojwYhhK1LkbRoU84ZSpDZpWOHGsRRXg45wg2qNkl7Z22AnU0RQBzOELcMBl7BlrAO-lATlNABCNAPlKgEB-2qXEbXdxXYTuAA0mAATAAGRFcGFQzAAbT2ByOJzOMQAumjwZgliAYSAINYYER0MhQIpnCcHAlnAg0MgQCoHIodByKXhnIowABrOAwADKtjARCgD2QCzgFIAFjACMoAOrKkjqaVwCXskhEeQkHScsD2ckgWVUZwwY6PAiKZBtFRUCkAKzQAA8AEJC0XiiWKW4AGVlcBdbqVIC93olsoeMQAijgIPAoxsY7ZnLbOXhFHh1lbrKVYBqiCIYMrkAAOREU0sQKgaoXWTml9RwZzySMUgCOadxVI5KDsAFooHBYrErWzB0Q2Q6Hk7M+6QFRiArnGoKWhEymh5GkK6sxSYIWK1Wa0h4eehVFEwBhCAEVcodQAVitlDgABVC1HU913kNQAEkoDEWAJTAUpqQAQUgiUYB0GI1zgdx3CAA)
```sh
--parser babel
```

**Input:**
```jsx
const submit = useMemo(
        () =>
            debounce((values: any) => {
                const { password } = values;
                const isFilledPassword = password && password.trim() !== '';

                if (isFilledPassword) {
                    setVisible(true);
                } else {
                    updateProfile();
                    message.success('修改成功！');
                }
            }, 200),
        [updateProfile],
    );
```

**Output:**
```jsx
const submit = useMemo(
  () =>
    debounce((values: any) => {
      const { password } = values;
      const isFilledPassword = password && password.trim() !== "";

      if (isFilledPassword) {
        setVisible(true);
      } else {
        updateProfile();
        message.success("修改成功！");
      }
    }, 200),
  [updateProfile]
);

```

**Expected behavior:**
```javascript
const submit = useMemo(
  () => debounce((values: any) => {
      const { password } = values;
      const isFilledPassword = password && password.trim() !== "";

      if (isFilledPassword) {
        setVisible(true);
      } else {
        updateProfile();
        message.success("修改成功！");
      }
    }, 200),
  [updateProfile]
);
```

**Comment by evilebottnawi** [comment]
Expected behavior is more readable (less indentation), we don't want to change current output, sorry
