### ISSUE TITLE
Bug on Glitch with CSS background shorthand

### ISSUE THREAD

**Issue by k-johnston** [prettier/prettier#8067]
This happens in [my CSS file in a Glitch editing environment](https://glitch.com/edit/#!/keinenbock?path=style.css:10:0) and was reported [here](https://support.glitch.com/t/bug-format-this-file-strips-spaces-in-background-declaration/22235).

I tried to reproduce in https://prettier.io/playground, but could not, so I didn't report the issue there as requested in your guidelines.

**Input:** - CSS file has a background shorthand syntax
```
html {
  background: url(
      https://cdn.glitch.com/b7643b5b-8aaa-4826-97c4-76f856ac2803%2Ffabrizio-conti-b5rPuIBFeME-unsplash.jpg?v=1569761318680
    ) no-repeat center center fixed;
  background-size: cover;
}
```
![before format button](https://user-images.githubusercontent.com/27199738/79498240-40f47b00-8029-11ea-9890-4e2723b4fab2.png)

I press the "Format this file" button. Then the background shorthand is formatted without spaces, as below.

**Output:**
```
html {
  background: url(
      https://cdn.glitch.com/b7643b5b-8aaa-4826-97c4-76f856ac2803%2Ffabrizio-conti-b5rPuIBFeME-unsplash.jpg?v=1569761318680
    )no-repeatcentercenterfixed;
  background-size: cover;
}
```
To correct this and have the picture appear, I have to add spacing back into the background syntax manually.

![after format button](https://user-images.githubusercontent.com/27199738/79498230-3d60f400-8029-11ea-8743-5b243637c700.png)

**Expected behavior:**
I except that formatting would not change the internal spacing in CSS properties. I attached two screenshots - and you can see that the font CSS property in line 6 of both screenshots has spacing intact before and after formatting.

I believe that this is an actual bug, because the output code will prevent the background image from being displayed. I don't think this is related to stylistic preference for whitespace.

Thanks for taking a look. I'm happy to help clarify any questions.

**Comment by thorn0** [comment]
What version of Prettier do they use? I've tested your code with different versions and haven't been able to reproduce the problem. Probably they should update Prettier.

**Comment by k-johnston** [comment]
I'm not sure either, but based on this comment thread, they had added the button UI in October 2019: https://support.glitch.com/t/make-your-code-prettier/14768.

Not sure where you want to take this from here, but I just wanted to let you all know. :)

**Comment by thorn0** [comment]
Also [answered on Glitch](https://support.glitch.com/t/bug-format-this-file-strips-spaces-in-background-declaration/22235/4?u=thorn0).
