### ISSUE TITLE
Problem with formatting array literals

### ISSUE THREAD

**Issue by RDIL** [prettier/prettier#8078]
Hi!

I use the latest prettier version, and I found an issue with its formatting.

My configuration is simply `{ "semi": false }`, and it seems to be putting a semicolon right before this array literal.  
![Screenshot 2020-04-17 at 3 03 21 PM](https://user-images.githubusercontent.com/34555510/79604913-f45a7f80-80bc-11ea-9443-26d595e4ab61.png)

This shouldn't happen because
1. I have semicolons disabled as mentioned above - I think that semicolons are disgusting so I don't use them wherever possible, and
2. why would it need to be there in the first place?!  There isn't any statement before it, so it just doesn't make sense.

Sadly, because this source code isn't something I can disclose, you will just need to try based off a snippet like this one.

Oh, and running prettier multiple times proves that the formatter thinks that this is correct.

**Comment by thorn0** [comment]
This works as intended. Please see https://prettier.io/docs/en/rationale.html#semicolons

**Comment by RDIL** [comment]
Fair enough.  Thanks.
