### ISSUE TITLE
Support formatting SQL files

### ISSUE THREAD

**Issue by xenoterracide** [prettier/prettier#8084]
I'd love to see support for formatting SQL files, as OMG is getting consistently formatted liquibase changesets that actually look good is a PAIN.

I think it'd be great if they could somehow be formatted in strings as well maybe through some sort of comment

```js
// prettier:format:sql
const sql = "SELECT * FROM foo;"
```

**Comment by thorn0** [comment]
Older issues: https://github.com/prettier/prettier/issues/2425, https://github.com/prettier/prettier/issues/5765

Someone is already working on a plugin for PostgreSQL-flavour SQL: https://github.com/benjie/prettier-plugin-pg

**Comment by xenoterracide** [comment]
maybe if we keep asking ;) (since we can't respond to previous issues)

**Comment by thorn0** [comment]
Do you really believe it works like that? :)
There is no plans for adding new parsers to Prettier core. That's what the plugin API is for.
