### ISSUE TITLE
Support JSON 5 as a configuration format

### ISSUE THREAD

**Issue by xenoterracide** [prettier/prettier#8085]
would be nice if we could have `.prettierrc.json5`
```json5
{
  singleQuote: true // some comment
}
```
I think comments are already possible in the json file (I'd argue they shouldn't be) but it'd also be nice not to have to quote everything.

**Comment by evilebottnawi** [comment]
@xenoterracide Why do not use `js` config file in this case?

**Comment by xenoterracide** [comment]
I have a great dislove of configuration files that can execute code. This probably comes from my system administrator days.

**Comment by fisker** [comment]
Want  try yaml? `.prettierrc` can  use yaml.

**Comment by xenoterracide** [comment]
so, on yaml, my experience with yaml is... maybe 20% of the time you mess up indentation, and then you pray that you had a good parser/validator that will tell you where, usually they're slightly wrong, for bad parsers, horribly wrong.

**Comment by fisker** [comment]
So, `.prettier.toml`?  :simle:

**Comment by fisker** [comment]
I'm not  sure the  team will accept this, but  very  easy  to  add  support,  you can  try to make a PR, update here  https://github.com/prettier/prettier/blob/299f2cad583cce07e6ba56893ef9c75670391cb5/src/config/resolve-config.js#L36-L41.

**Comment by fisker** [comment]
We are supportting new config format `.cjs`, do you think it's a  good chance to support json5?

/cc @prettier/core

**Comment by evilebottnawi** [comment]
Why not?
