### ISSUE TITLE
Ignore File Extension Globally

### ISSUE THREAD

**Issue by JStyle21** [prettier/prettier#8094]
Hi,

I'm looking for something like .prettierignore but on a global level, i don't want to copy that file to every new directory i make just to ignore 1 file extension which isn't supported anyway.

AFAIK this isn't supported right?

BTW the extension in this case is EJS which prettier thinks is JS and some other stuff so the best way really is to ignore .ejs as a whole.

**Comment by thorn0** [comment]
Sorry, but Prettier intentionally doesn't support any global settings at all. This is to make sure that when a project is copied to a new machine, Prettier's behavior stays the same. Otherwise we wouldn't be able to guarantee that everybody in a team gets the same consistent results.

**Comment by JStyle21** [comment]
Ok, thanks

**Comment by thorn0** [comment]
I guess we should clarify this point in the docs though.

**Comment by thorn0** [comment]
Also we should make it clear that it's recommended to install Prettier locally. Currently, https://prettier.io/docs/en/install.html makes an impression that global installation is an equally good alternative.

**Comment by fisker** [comment]
Why we never thought about this? With [`import-local`](https://github.com/sindresorhus/import-local) we can make the global installed Prettier try to run local one.

Example [ava](https://github.com/avajs/ava/blob/master/cli.js) project.

We should implement this logic.

**Comment by thorn0** [comment]
closing in favor of https://github.com/prettier/prettier/issues/8464
