### ISSUE TITLE
Allow "multiline JSDoc casts" for TS compiler with checkJS option

### ISSUE THREAD

**Issue by CombeeMike** [prettier/prettier#8096]
We're using the TS compiler with the `checkJs` option enabled to check JS code.

Right now, "JSDoc style casts" need to be in the same line as the "expression to cast" which oftentimes leads to very verbose & long lines and therefore to code which is very hard to read.

**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AFQAs5cAzCAGyogHcBLKAc1zogCcBrAZ1wEM+cAB4AHOGHgATAHQ58RUrgBGHfmC5wYffhwgBXKFNxYQw0wI5lNomLia5RVdXDl50qHJCg87AKx4AEQgwAGFBOwBeXAwCAAEYAE9xXGAAWUTCZLgAX3xUXAAKYQBKAG4cHFj5AhIyQgBlXEgAW1EGKjgOZs4rSSpE3D6IZigGAC84PhglMAj7PBmyQ1ErGBgGcgY4YwA3Lp4GaFwIchrcJYpqWkYWHqlXc-OACXo4fY4AGkc1ja6huAtCD7aZKVTqTTaSwGIwmMwWOjEBhgYhw1Rwfi8CyXOa+K4cc6XRo9NodLoyCk1TxQKqYXAJbKpDJZcR5DxeaB4gLBMIRNL6KgbKhMMjRYrlECfEAQWxHHzIUC6PR0AAKugQPGQIH4VDo-ESmql4I0WgaonUTGYyBgHH0cClxBgLSoAHUkfAeOawHAGhqGBtdv7ElqwDxDSAmDwujAVWpmC1+MhyDqo1KAsIAEJqE0wBr8FpwAAyIqTKftIHTDUtnQAivoIPBS1RUyBzRwoxwtcp+Mo4FRJa2OEwYC6GFIZsgABwABilqwgUZdalEWtWUy6+wHAEd6-BYzLNShBABaKBwHY7AdWHcMKyx-jxxNIZPN8tRloMa22t-VuB1htwE2LYwD2o7jsQyAAExSja-AdJaoQQC0CZalMACsA76FGhA9oeL4trsdoAJJGAguZgEOtgAIJGA0SSdEBuQ5EAA)
```sh
--parser babel
```

**Input:**
```jsx
/**
 * The following works as expected.
 * The brackets around "x" are kept in place.
 */
const jsDocCast = /** @type {MyType} */ (x);

/**
 * The TS compiler correctly recognizes the cast in the unprettified version of
 * the following code.
 * 
 * However, prettier removes the brackets around "x" which "breaks" the cast for
 * the TS compiler...
 */

/** @type {MyType} */
const jsDocCastMultiline = (x);
```

**Output:**
```jsx
/**
 * The following works as expected.
 * The brackets around "x" are kept in place.
 */
const jsDocCast = /** @type {MyType} */ (x);

/**
 * The TS compiler correctly recognizes the cast in the unprettified version of
 * the following code.
 *
 * However, prettier removes the brackets around "x" which "breaks" the cast for
 * the TS compiler...
 */

/** @type {MyType} */
const jsDocCastMultiline = x;

```

**Expected behavior:**

We'd love to see prettier "respect/keep" brackets around expressions in such situations as well.

**Comment by evilebottnawi** [comment]
@CombeeMike Why you need parentheses in that case:

```js
/** @type {MyType} */
const jsDocCastMultiline = x;
```

It works fine without them.

**Comment by thorn0** [comment]
@CombeeMike The behavior you're relying on is a bug in TypeScript: https://github.com/microsoft/TypeScript/issues/26635. Being a bug, it's going to be fixed, so I wouldn't recommend relying on it. See also https://github.com/prettier/prettier/issues/8045

**Comment by CombeeMike** [comment]
@thorn0 I wasn't aware of the fact that such "multiline casts" were not standard conform and only recognized by TS due to a bug. Thanks for pointing this out!

Obviously this make my request obsolete ;)
