### ISSUE TITLE
[Feature Request] Add option arrowParens: multiline

### ISSUE THREAD

**Issue by marcofugaro** [prettier/prettier#8104]
Since Prettier 2.0 changed its default `arrowParens` value, let me explain a good compromise that would make everyone happy. This is my take on what developers would have wanted from the start.

The situation is: a simple arrow function with **one argument** (e.g. `x => x`)

By setting the following option:
```sh
--arrow-parens multiline
```

The logic would looks like this.

- **If the arrow function has an implicit return --> arrowParens = false**
  `x => x`  --> `x => x`

- **If the arrow function has brackets instead --> arrowParens = true**
  `x => { return x }`  --> `(x) => { return x }`

From the docs:

> When Prettier removes parentheses, it becomes harder to add type annotations, extra arguments or default values as well as making other changes.

That is true only for callback functions, developers often don't need to add arguments or modify simple lambda functions. (e.g. `x => x + 1` or `s => s.trim()`)

**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDMY5poQBOmAvJgCbkB8VAdAB4DcAOlO5FBpmNgDb8ARrgDW5TAAo4-OAFsEMAJS1Mwdpl7oIs+vwgBzabIWwlbKAF8QAGhAQADjACW6ZKGzFiEAO4AFTwQ0ZBABH2wAT2C7IWIxOBgAZQdcZygDZBhiAFc4OwALGDl+AHV853g0FPxEoIrnADcKiJCwQlsQNLQ4Yhg-OIM5bGQAMwFuuwArNEYAITiwUQTE7AUAGTS4UfG8kGnGRLSDWQBFbIh4bf4JkBTibuIQkSEI-SgOh2I0mBLnShh8sgABwABjsnwg3RKcQcIU+BB6DS2dgAjud4P1HMEUNg0ABaKBwOCUYkdYhwNHOcn9bCDYZIMbXXbdOTOTI5ZlHU7orYMnZ2GDYIS-f6ApAAJgFcWc-COAGEIHIhiEoNBkSBst0ACpC7GM7qWSxAA)

**Input:**

```jsx
const accessor = d => d.x;

const callback = (element) => {
  console.log(element);
}
```

**Current output:**

```jsx
const accessor = (d) => d.x;

const callback = (element) => {
  console.log(element);
};
```

**Expected output:**

```jsx
const accessor = d => d.x;

const callback = (element) => {
  console.log(element);
};
```

**Comment by evilebottnawi** [comment]
:-1: on this, it was discussed a lot of time

**Comment by marcofugaro** [comment]
@evilebottnawi care to elaborate or link the old discussion issues?

**Comment by orinokai** [comment]
@marcofugaro there's been lots of discussion on https://github.com/prettier/prettier/issues/6929 although, for what it's worth, I think your idea is a wonderfully logical solution

**Comment by evilebottnawi** [comment]
Why? Minimizes diff churn when adding or removing arguments.

/cc @thorn0 I think we can close this issue.

**Comment by marcofugaro** [comment]
Because developers don't usually add arguments if the function is a simple functional one-liner with an implicit return.


In Prettier the opposite has been the default for the longest time, it makes sense to find a middle point between the two current options.

**Comment by evilebottnawi** [comment]
The presence of this option is generally under a huge question, we are not going to add more options or change the current output, sorry

> Because developers don't usually add arguments if the function is a simple functional one-liner with an implicit return.

They usually add to avoid git diff as I written above.

**Comment by thorn0** [comment]
The idea in itself is interesting, but it's too late to change this. This ship has sailed and we don't want to revisit these decisions as such discussions and changes generate too much bike-shedding and too little value.
