### ISSUE TITLE
Improve `.vue` parse with `angular-html-parser@1.5.0`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8108]
Details: https://github.com/ikatyang/angular-html-parser/pull/12#issuecomment-616167534

**Comment by brodybits** [comment]
Should this be linked to PR #8107?

Should we add any tests?

**Comment by fisker** [comment]
No, we need rewrite vue parser, that PR send to test if there broken changes.

**Comment by sosukesuzuki** [comment]
@fisker Can I work on this? Do you want to work on this?

**Comment by fisker** [comment]
@sosukesuzuki 

One note: 

I played a little bit with the new `angular-html-parser`, to parse as `RAW_TEXT`, I thought it should be


```js
getTagContentType() { return require("angular-html-parser").TagContentType.RAW_TEXT;}
```

turns out it should be

```js
getTagContentType() { return "RAW_TEXT";}
```
