### ISSUE TITLE
Does not support underscore

### ISSUE THREAD

**Issue by yisibl** [prettier/prettier#8109]
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeApAHSgehwAgCc4AHOAQxnwEt4BbAZ32wH0A6CsACwApa5GAGgBmAVyhgY1aH3qCA1nACeggDbUGMAJTBs+ffjz4wxSnHwA3coWrkARqrgM9Bq4XzD8AXhr02Ucjo4NgYSdRgeTBAorRCuamEI2JgIABkIAHc4QgBhcgY4Hi0Abmx0AD5sVBhCSqgDfFQAQgBaFvxRAstrWwcnfDa6huqAE3KMH0UlfArUHBgxl31R41V8hi8oiY8ZypAhhoNmto6u9HaUmigAKzhJDqgWhnIoWmoALzgR0+yrklEqDwCuYAOQAEQEEHwEE8AA0AMrw-BcchgeQgrQDFoHQ6NLgAZnG518An8gXMsxwBJxh1QJCJ7X4dDY1Fg2ScMCYlPpS0a80WUDmNTqGHwAF8SrsQIIQBASFJoAxkKBrIRMgAFawIJUociqDLkJRKmV2QioxQweEkVGsgDmyBqojgMq4MDoqgA6vF4KFUXB4dq3hZaEpkOAGMaQKyCoQYOqzba6ORkMI9QUZdcGAAPABCZrRcEt5NSrLgKbTzpAmaz8LtjgAiqIIPBy6p0yBrYQY2HXe7pR2bLAPdQRjAuMgABwABhlJDVBQ9ZpIYbnTmyFjLMoAjk34PG5TqQPkWlA4F8vv3iDvqMR4+RE8mkKm25WCnRqA7CE6ZQw63BG82ZZPhWMowPYw6juOSAAEygWa1DqFAto5BAdBJmGTgAKz9p0cAACr2Dqz7thYToAJJQCMCCWiY1DygAgpR8IwEojitgUYpikAA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```html
<%
// repeat items 
_.each(items,function(item,key,list){
    // create variables
    var f = item.name.split("").shift().toLowerCase();
%>
<tr>
    <!-- use variables -->
    <td><%= key %></td>
    <td class="<%= f %>">
        <!-- use %- to inject un-sanitized user input (see 'Demo of XSS hack') -->
        <h3><%- item.name %></h3>
        <p><%- item.interests %></p>
    </td>
</tr>
<% }); %>
```

**Output:**

```html
<% // repeat items _.each(items,function(item,key,list){ // create variables var f =
item.name.split("").shift().toLowerCase(); %>
<tr>
<!-- use variables -->
<td><%= key %></td>
<td class="<%= f %>">
    <!-- use %- to inject un-sanitized user input (see 'Demo of XSS hack') -->
    <h3><%- item.name %></h3>
    <p><%- item.interests %></p>
</td>
</tr>
<% }); %>
```

**Expected behavior:**
Like Input.

If it cannot be support, is there a way to ignore it?

**Comment by bakkot** [comment]
I don't think this about underscores; it's a bug with the comment printing. A simpler reproduction is

```html
<%
// comment 
foo()
%>
```
which prints

```js
<% // comment foo() %>
```

which seems wrong. ([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeApAHSgehwAkgFsiEZ9sAzCCACgEpt0A+bEAGhAgAcYBLaAGdkoAIYAncRADuABQkJhKUQBtpogJ7DOAI3GiwAazgwAytwN8oAc2QxxAVzicAFjCIqA6i77xBFsDhTRV8+ADdfDWRwQW0QK0E4cRhZfWsiUWRKVUTOACtBAA8AIX0jE1NRUgAZKzgsnOcQAsLTK2sVOABFBwh4BpVckAtxRPFotw8OYfErGE8+ABMYF2QADgAGTm4pRM99bmiduDGw+s4AR174VJ4lEFFBAFooODhF9+nxOCu+b9TROlMkhsoMmokiHw7I5we1Oj0+vUQY1ODBRDoFstVkgAEyo-R8FTtADCEBIwJAJwArNMHIkACropSgoZhJwASSgH1gpjAs14AEEuaYYBpOgNEgBfSVAA).)

I'm not actually sure what syntax this is. I'm guessing [EJS](https://ejs.co/#docs)?

**Comment by thorn0** [comment]
The Underscore library has such templates too: https://underscorejs.org/#template
Prettier never claimed it supported such syntax, so it's a feature request, not a bug.

**Comment by thorn0** [comment]
Closing in favor of #5537
