### ISSUE TITLE
[Less] Comment deleted for no reason

### ISSUE THREAD

**Issue by fjc0k** [prettier/prettier#8130]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wAEAOiAHRkD0UEAJnAPqZ0CuANnAM6UBmEElAEYBDPGQ6dOpANzEocypUIYo9AB4AKANoByKpBzQEMbgCpTlU+K6cdAGkI6AhFXOUG9ZpdM6Aug55CAF4APkIAAwxDAkcAEmAeMmxhGAALAF94xLg1GHSdaXCASjko3Bi9SgNcKGNuACEWGBhoSkbm6GtJAtKscqJK6qNYbgAxfExKcbxMLttZKDL8Af0IQ1qRygBJKGwm7d2muZ6oRWUEWnRVHLkQOxAIbBh0aE5kUFE8CAB3AAVRBBvFDCNjfYQATze90EeGEYAA1nAYABlZJgK4Ac2QMDwLDg91SMEwbAA6ql0PBOGi4MjART0AA3Cng5DgSR3EBXThwAi-WEYzDCZA8EHc+4AK04anqsIRSORwkwcAAMlc4MLRfiQJK1MjMRwAIosCDwDVsMUgZJ4bl4VkSKGWvBXGAk9C0NLIAAcAAZ7tgvtySbDsKz-VweQz1fcAI7G+B8x5AkDCTgAWlqcHotA5eDgsfQub5wgFQqQIvNWu5mHQ2Nxlf1cCNJvVZc19xgwkErvdqWQACZ27D0GxMQBhNaC1lcACsHJY3IAKp2geWLQy8Tt6LBkWAnU8AIKqZEwcEcM3c9LpIA)
```sh
--parser less
```

**Input:**
```less
@import "../node_modules/foo/bar.less";

// @index(['./components/**/*.less', '!./**/_demo/**'], f => `@import '${f.path}${f.ext}';`)
@import './components/Button/Button.less';
@import './components/Form/Form.less';
@import './components/Input/Input.less';
// @endindex

```

**Output:**
```less
@import "../node_modules/foo/bar.less";

// @index(['./components/**/*.less', '!./**/_demo/**'], f => `@import '${f.path}${f.ext}';`)
@import "./components/Button/Button.less";
@import "./components/Form/Form.less";
@import "./components/Input/Input.less";
@import './components/Form/Form.less';

```

**Expected behavior:**

Don't delete `// @endindex`.

**Comment by fisker** [comment]
I've tried `less` can parse it

<details>
<summary>AST</summary>
<pre><code> Ruleset {
  parent: null,
  visibilityBlocks: undefined,
  nodeVisible: undefined,
  rootNode: null,
  parsed: null,
  selectors: null,
  rules: [
    Import {
      parent: null,
      visibilityBlocks: undefined,
      nodeVisible: undefined,
      rootNode: null,
      parsed: null,
      options: {},
      _index: 0,
      _fileInfo: [Object],
      path: [Quoted],
      features: null,
      allowRoot: true,
      skip: [Function (anonymous)],
      root: [Ruleset],
      importedFilename: 'a.less'
    },
    Comment {
      parent: [Circular *1],
      visibilityBlocks: undefined,
      nodeVisible: undefined,
      rootNode: null,
      parsed: null,
      value: "// '/*' <-- this makes the parser parse next import as comment",
      isLineComment: true,
      _index: 14,
      _fileInfo: [Object],
      allowRoot: true
    },
    Import {
      parent: null,
      visibilityBlocks: undefined,
      nodeVisible: undefined,
      rootNode: null,
      parsed: null,
      options: {},
      _index: 78,
      _fileInfo: [Object],
      path: [Quoted],
      features: null,
      allowRoot: true,
      skip: [Function (anonymous)],
      root: [Ruleset],
      importedFilename: 'b.less'
    },
    Comment {
      parent: [Circular *1],
      visibilityBlocks: undefined,
      nodeVisible: undefined,
      rootNode: null,
      parsed: null,
      value: '// @endindex',
      isLineComment: true,
      _index: 91,
      _fileInfo: [Object],
      allowRoot: true
    }
  ],
  _lookups: {},
  _variables: null,
  _properties: null,
  strictImports: undefined,
  allowRoot: true,
  root: true,
  firstRoot: true,
  functionRegistry: {</code></pre>
</details>
