### ISSUE TITLE
Implement a new `--ignore-unknown` argument for CLI

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#8136]
Idea - do not throw an error on unknown extensions (when we don’t know which parser should be used)

Why? For tools like `lint-staged`. 

Main idea:

```js
{
  "*.*": "prettier --write --ignore-unknown"
}
```

This will avoid listing extensions. 

We already support `prettier --list-different .` and it improves 0CJS configuration, now we can do it more.

/cc @prettier/core your thoughts?

**Comment by alecmev** [comment]
As mentioned in #8454, another use case where this can be very useful:

```bash
onchange . -- prettier --write --ignore-unknown '{{changed}}'
```
