### ISSUE TITLE
Dependency `dedent` has bug

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8143]
`dedent` is in `package.json`, I just found it's buggy, I'll check how it effect our code.

```console
$ node -p "`\u0070\u0072\u0065\u0074\u0074\u0069\u0065\u0072`"
prettier

$ node -p "require('dedent')`\u0070\u0072\u0065\u0074\u0074\u0069\u0065\u0072`"
\u0070\u0072\u0065\u0074\u0074\u0069\u0065\u0072

$ node -p "require('outdent').outdent`\u0070\u0072\u0065\u0074\u0074\u0069\u0065\u0072`"
prettier
```

**Comment by brodybits** [comment]
dedent seems to be not actively maintained, last published 3 years ago, maybe just switch to outdent?

**Comment by fisker** [comment]
Yes, that's the idea, but we are using a lot. Including `dedent()` function call, not checked yet.

**Comment by fisker** [comment]
I'm switching to `outdent` in #8142, check [this](https://github.com/prettier/prettier/pull/8142/commits/51b5def1567326140da5f6af9767188c2ecbcb84) the old result is wrong.

**Comment by fisker** [comment]
I hate it, wasted hours.

**Comment by fisker** [comment]
I used `outdent` before, it's also did't release any new version for a long time, but seem they just release a new version a month ago
