### ISSUE TITLE
[Help wanted] use prettierignore to lint all the files in a project

### ISSUE THREAD

**Issue by Mister-Hope** [prettier/prettier#8144]
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: cli
- Runtime: node 12.16.2
- Operating System: Win 10 20H1

**Steps to reproduce:**

My `.prettierignore`:

```
dist/**
node_modules/**
```

My npm script:

```
"lint": "prettier --check --write ."
```

**Expected behavior:**

I expected that prettier is linting all the files in my project which it can lint, except those in `dist` and `node_modules` folder.

**Actual behavior:**
It is linting files in `dist` folder, and stay the same even if I use `prettier --check --write --ignore-path './.prettierignore' .`

**Comment by thorn0** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff).
