### ISSUE TITLE
HTML: URLs with commas are broken in srcset

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#8150]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAlgWwOYB0oDO6AXnAQLy4gAUmAhgB4C0A7ugCYwAWSABAIwAWAAzCADgwCUA0QDcWAGgEjxDKvgIAnMATgxKIfAH0ATMLPCR-I0ICsogJxGCxTVwBWAVyNhnYOgA2cAospqIAdO5i2LwWisZmFlY2gvbCTi5uXj5+gcGhAMwA7A6R0bzFDvFQYUnC1naOzq4e3r4E-kEhRrb8tmUxvbbVtaLJjenNWW25XaEAbAXCA7yLwiOJY-UpaRkt2e2d+UZFBfwrp-wb5lsNqU2ZrTkded0AHCZvKx9v13V3uymT0Or1CDhM5yiMXBVwUCRulm2Ez202eR26Dgc-ShvExwzhNU2iIBD32MxecxswiKJhW-GpJj+tx2pNRIMp-DsdLsTOJLMmjwOs2O-Ah8zpYt543uArJaNBNk+gglb0EUqRMpRwOF3X4BXsdP16wJoz5yKBQopIoKDi+OL1tvVJNlbJ1oSEEXtKhY6kI2gMpulgMF5PR7pUA19gX06hAAD4QAoQBAxDB0NACMhQHRNJoICwAAo5hCZlCBFh0ACemaTACNNHQwABrPQAZTEjfQUGwyBgmk8wRAXBgmACAHUuOh4AQO2A4K2S1P0LIp5XkOACDWQF3dJoYAWG9h6MgAGaBXRJ9wEBgAIQbzbbdEwcAAMl24Kfz4OrwxW13sEEACKngQPAn4BBeIAdpou7rsOo6JlBmhdjAY4cNwyBvMISZiHmuhjg2YjrrhZBwJosgfkmACOIHwAeKaliAdAEEwUBwHA7AcYhmhwDR6A8QedBHnQ4GQbomDoL2-aDkQ3ZAbRH5IGeEGDjAdC1mhnBcMgJhJn2dDoAE-4AMIQJgx4oGQtiIZ4ugACrqaWymQbIA4AJJQJxsCtmAyGpgAgp5rYwJWQSiXAAC+EVAA)
```sh
--parser html
```

**Input:**
```html
<img
sizes="(max-width: 1400px) 100vw, 1400px"
srcset="
_20200401_145009_szrhju_c_scale,w_200.jpg 200w,
_20200401_145009_szrhju_c_scale,w_379.jpg 379w,
_20200401_145009_szrhju_c_scale,w_515.jpg 515w,
_20200401_145009_szrhju_c_scale,w_630.jpg 630w,
_20200401_145009_szrhju_c_scale,w_731.jpg 731w,
_20200401_145009_szrhju_c_scale,w_828.jpg 828w,
_20200401_145009_szrhju_c_scale,w_921.jpg 921w,
_20200401_145009_szrhju_c_scale,w_995.jpg 995w,
_20200401_145009_szrhju_c_scale,w_1072.jpg 1072w,
_20200401_145009_szrhju_c_scale,w_1145.jpg 1145w,
_20200401_145009_szrhju_c_scale,w_1216.jpg 1216w,
_20200401_145009_szrhju_c_scale,w_1284.jpg 1284w,
_20200401_145009_szrhju_c_scale,w_1350.jpg 1350w,
_20200401_145009_szrhju_c_scale,w_1398.jpg 1398w,
_20200401_145009_szrhju_c_scale,w_1400.jpg 1400w"
src="_20200401_145009_szrhju_c_scale,w_1400.jpg"
alt="">
```

**Output:**
```html
<img
  sizes="(max-width: 1400px) 100vw, 1400px"
  srcset="
    _20200401_145009_szrhju_c_scale,
    w_200.jpg                        200w,
    _20200401_145009_szrhju_c_scale,
    w_379.jpg                        379w,
    _20200401_145009_szrhju_c_scale,
    w_515.jpg                        515w,
    _20200401_145009_szrhju_c_scale,
    w_630.jpg                        630w,
    _20200401_145009_szrhju_c_scale,
    w_731.jpg                        731w,
    _20200401_145009_szrhju_c_scale,
    w_828.jpg                        828w,
    _20200401_145009_szrhju_c_scale,
    w_921.jpg                        921w,
    _20200401_145009_szrhju_c_scale,
    w_995.jpg                        995w,
    _20200401_145009_szrhju_c_scale,
    w_1072.jpg                      1072w,
    _20200401_145009_szrhju_c_scale,
    w_1145.jpg                      1145w,
    _20200401_145009_szrhju_c_scale,
    w_1216.jpg                      1216w,
    _20200401_145009_szrhju_c_scale,
    w_1284.jpg                      1284w,
    _20200401_145009_szrhju_c_scale,
    w_1350.jpg                      1350w,
    _20200401_145009_szrhju_c_scale,
    w_1398.jpg                      1398w,
    _20200401_145009_szrhju_c_scale,
    w_1400.jpg                      1400w
  "
  src="_20200401_145009_szrhju_c_scale,w_1400.jpg"
  alt=""
/>

```

**Comment by fisker** [comment]
@thorn0 

I switched `parse-srcset` to `srcset` in https://github.com/prettier/prettier/pull/7381 , because I thought  `srcset` is more popular, should be better, and I was going to improve it by that time https://github.com/sindresorhus/srcset/issues/1#issuecomment-555285577 . 

Turns out I might made mistake, the `parse-srcset` follows the spec better. see https://github.com/sindresorhus/srcset/issues/1#issuecomment-591938086 

I suggest we switch it back or push `srcset` to fix it.

**Comment by evilebottnawi** [comment]
@fisker yep, we should switch back, maybe we can move parsing in our code base, this will make fixes much faster
