### ISSUE TITLE
Vue: ugly formatting for one line `template` in Vue SFC

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#8151]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qWhAZhBKgPSmoAmAlgG7mU1Os2a4FyEAdKCAA0ICFhiNoAZ2Sg8AJ0UQA7gAUlCOSjw5VeAJ5yxAI0V4wAazgwAylkuMoAc2QxFAVzhiAFjAwcAHVfRngZRzA4O20wljDDZHAZExBnGThFGHULFww8ZDI9DLEAKxkADwAhC2tbOzwMOAAZZzhC4p8Qcoq7ZxccOABFTwh4DpwSkEdFDMUk5m9RacVnGCDGehhfZAAOAAYxLBUMoIssJOO4OeZ2sQBHUfgciR0QPBkAWig4OHo-5aKOCPRhAnJ4PIFJBFSZdDIYRjuLxw-qDEZjdrQzpiGB4UwbLY7JAAJhxFkYOH6AGEIBh8klrgBWZaeDIAFTxOhhU0WcAAklB-rA7GBVpIAIKCuwwQyDCYZAC+CqAA)
```sh
--parser vue
```

**Input:**
```vue
<template><p>foo</p><div>foo</div></template>

```

**Output:**
```vue
<template
  ><p>foo</p>
  <div>foo</div></template
>

```

**Expected behavior:**

```vue
<template>
  <p>foo</p>
  <div>foo</div>
</template>
```

**Comment by fisker** [comment]
[A better example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qAJgJYBuxWhAZhBKgPQ2mWEBGeATs+VX3bNMuAnEIAdKCAA0ICFhhloAZ2Sge3CAHcACjwRqUeHNrwBPNXI7c8YANZwYAZSx2yUAObIY3AK5wcgAWMBg4AOpBZPAqbmBwzobRlNHmyOAqViAeKnDcMLq2nhh4yLQmuXIAVioAHgBCtg5OzngYcAAyHnBlFYEgNbXOHp44cACKfhDwvTiVIG7cudzpFAGyC9weMOFkJDBByAAcAAxyWFq54bZY6RdwyxQ9cgCOU-CFCkYgeCoAtFA4HASMCNtw4G8yODCnhiqUkOU5v1chgyD5-MiRmNJtMegi+nIYHgOLt9ockAAmQm2Mg4EYAYQgGBK6QeAFYNn5cgAVYlGRHzNZwACSUBBsGcYC2igAgmLnDBzGNZrkAL6qoA), vue SFC requires single root before `v3.0`

**Comment by cilice** [comment]
The formatting is way better when you set the `--html-whitespace-sensitivity` to `ignore`. 

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qWhAZhBKgPSmoAmAlgG7mU1Os2a4FyEAdKCAA0ICFhiNoAZ2Sg8AJ0UQA7gAUlCOSjw5VeAJ5yxAI0V4wAazgwAylkuMoAc2QxFAVzhiAFjAwcAHVfRngZRzA4O20wljDDZBBGFygIRThRZKgZOEUYdQsXDDxkMj1csQArGQAPACELa1s7PAw4ABlnTKRynEqQGtq7ZxccOABFTwh4MoqfEEdFXMUk5m8srEVnGCDGehhfZAAOAAYxLYhcoIssJK24FeZMsQBHafhCiR0QPBkAWigcDg9BBWQy70YGUKeGKpV68zEuQwjHcXgWMlG4ymMx6fQGMDwpj2ByOSAATGIPHhGDhRgBhCAYEpJR4AViynlyABUiTp8Qt1nAAJJQUGwOxgbaSACCYrsMEM4zm-TgAF81UA)

**Comment by fisker** [comment]
I think it format like this  is because `template` is considered `inline` https://github.com/prettier/prettier/blob/c0cd681af05404827e5cb9a399692d29ad5d2f06/src/language-html/constants.evaluate.js#L30 , after we merge https://github.com/prettier/prettier/pull/8153 we can override root `template` in vue SFC to be `block`, it will get fixed.
