### ISSUE TITLE
Default to ignoring .prettierignore

### ISSUE THREAD

**Issue by zbot473** [prettier/prettier#8157]
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: CLI
- Runtime: v13.12.0
- Operating System: macOS

**Steps to reproduce:**

Run prettier with a .prettierignore file

**Expected behavior:**
Prettier will ignore the .prettierignore file and not output any errors

**Actual behavior:**
Leaves an error: `[error] No parser could be inferred for file: .prettierignore`
And also exits with code 2.
You have to manually ignore .prettierignore to hide this error.

**Comment by fisker** [comment]
Make sense, but is there any plugin format `ignore` file?

**Comment by thorn0** [comment]
@zbot473 Please help us understand your use case. Why do you run prettier with a .prettierignore file?

**Comment by zbot473** [comment]
> Make sense, but is there any plugin format `ignore` file?

No plugins.

> @zbot473 Please help us understand your use case. Why do you run prettier with a .prettierignore file?

I have a project with a bunch of mp3 files in it which i need to ignore. Also i ignore the minified output of my webpack build process.

**Comment by thorn0** [comment]
Why do you pass `.prettierignore` to Prettier as a file to format?

**Comment by zbot473** [comment]
Oh, I wildcarded file names using "**/*.*".

**Comment by thorn0** [comment]
But why use wildcards (AKA globs)? They are a kind of last resort. Usually, it's enough to pass a directory name to Prettier or `.` for the current directory. See the [docs](https://prettier.io/docs/en/cli.html):

> If the path points to an existing directory, Prettier CLI recursively finds supported files in that directory. This resolution process is based on file extensions and well-known file names that Prettier and its plugins associate with supported languages.

Doesn't that work for you?

**Comment by zbot473** [comment]
Using "./\*.\*" only does top level **files**, but using "\*\*/\*.*does all top level files as well as folders.

**Comment by thorn0** [comment]
No, I mean you probably should call just `prettier .`, without any asterisks at all.

**Comment by zbot473** [comment]
That worked. Thanks!
