### ISSUE TITLE
May not work well in self-executing functions

### ISSUE THREAD

**Issue by kenve** [prettier/prettier#8159]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAZgSwE4DOMGARgDYRgDWAOlABRYCuUYMO09AlBsHRhkhQCEMnAB0FAOb0A5LkLFylKgEJZXANx0Avl25066DAThCAJqQrU6jFmw4MefKAKEixkiDNmmLVlXUtXX0tEAAaEAgAB3ZoAmRQAEM8PAgAdwAFFIQElCSydKSATwTIkjwk6jgYAGVoqpwoKWQYPCY4SIALGABbMgB1Lpx4AgawOFrckZwANxHi5HACMpAm0zwYTMqpXqTkLALTSIArAgAPACFK6rqk3rgAGSa4A6POkDPz2qapMQBFJgQeBvMjHEANQhwPBLEhJEhwMgRCF4JowAY4cwwLrIAAcAAZItE0qYBpVoktiXANrNXpEAI5A+DbGJ5EBJAgAWigcDg5j5yLwcEZ+Dg2ySu32SEOYI+pl6OFa7TlvwBTNe0vekRg8IxWJxSAATNrKjgyL8AMIQXp7JbUgCsyKYpgAKvC8jLwbMOgBJKD82C1MCo2IAQX9tRgxTEoNMOh0QA)
```sh
--parser babel
```

**Input:**
```jsx
// first block
(function() {
  console.log('first block!');
})()

// second block
(function() {
  console.log('second block!');
})();
```

**Output:**
```jsx
// first block
(function () {
  console.log("first block!");
})()(
  // second block
  function () {
    console.log("second block!");
  }
)();

```

**Expected behavior:**
```js
// first block
(function() {
  console.log('first block!');
})();

// second block
(function() {
  console.log('second block!');
})();
```

**Comment by fisker** [comment]
This is expected, [you forgot your semi](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAZgSwE4DOMGARgDYRgDWAOlABRYCuUYMO09AlBsHRhkhQCEMnAB0FAOb0A5LkLFylKgEJZXANx0Avl25066DAThCAJqQrU6mxizYcGPPlAFCRYyRBmzTFqxV1LV19LRAAGhAIAAd2aAJkUABDPDwIAHcABVSERJRksgzkgE9EqJI8ZOo4GABlGOqcKClkGDwmOCiACxgAWzIAdW6ceAJGsDg6vNGcADdRkuRwAnKQZtM8GCyqqT7k5CxC0yiAKwIADwAhKpr65L64ABlmuEPjrpBzi7rmqTEAIpMCDwd5kE4gRqEOB4ZYkZIkOBkSKQvDNGCDHDmGDdZAADgADFEYulTIMqjFliS4Js5m8ogBHYHwHaxfIgZIEAC0UDgcHM-JReDgTPwcB2yT2ByQR3Bn1MfRwbQ68r+gOZbxlHyiMARmOxuKQACYdVUcGQ-gBhCB9fbLGkAVhRTFMABUEflZRC5p0AJJQAWwOpgNFxACCAbqMBKYjBph0OiAA)

**Comment by kenve** [comment]
@fisker I know, does it support add it automatically when formatting?

**Comment by fisker** [comment]
Your code can't even run.

**Comment by kenve** [comment]
ok, thx
