### ISSUE TITLE
Vue/Angular: Break formatting with upper case HTML tag

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#8162]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHyoAS+AsgDIMA6U55qAEYQAJgE8effgJEBLAG7l5AWlkAzALzcQaiBHIbD08gHJdEE9sm9UAejnzJx1AGcwAJ1kAHGJKhwAd3IANQBXOAAKYDg6JFMAYgBDLy8TAF8ASl5nWzdPHycBW2FxSTtWTkkQABoQCB9ZaBdkUET3dwgA4jaEZpREugDEsWbawXdEsABrOBgAZS9J2SgAc2QYd3Da6noAdUpZeBdFsDg53sOFQ7FkcBdRkGWXOHcYYgmVmkTkNQHn2oAVi4AB4AIQm01mc0SNDgHGWcB+fzggJBc2WKzocAAiqEIPAkXR-iBFu5nu5bvJwjUSZ5YLtZCIYJRkAAOAAMtS8HWeuwmXlu3Lg5PkiNqAEc8fB3vU+iBEi5lP44CIVTT3HBJbINe9Ep9vkhfkSUSBnjRZOtNiaXBisbj8YjDcjajBEoIGUyWUgAEwuiayOgY3AQGhfW7CgCsNNCz3wbr6RuJVLgAEkoKrYHMPN4YABBdNzGBiLGE55pNJAA)
```sh
--parser vue
```

**Input:**
```vue
<!DOCTYPE html><HTML>
  <body>
    <div v-if="foo ===    'foo'">

</div>
    <script>
new Vue({el: '#app'})
    </script>
  </body>
</HTML>

```

**Output:**
```vue
<!DOCTYPE html
>><HTML>
  <body>
    <div v-if="foo ===    'foo'">

</div>
    <script>
new Vue({el: '#app'})
    </script>
  </body>
</HTML>

```

**Expected behavior:**
```vue
<!DOCTYPE html>
<html>
  <body>
    <div v-if="foo === 'foo'"></div>
    <script>
      new Vue({ el: "#app" });
    </script>
  </body>
</html>
```

**Comment by sosukesuzuki** [comment]
on Angular
[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHyoAS+AsgDIMA6U55qAEYQAJgE8efAQHph4yammtOkkABoQEAA4wAltADOyUAEMATmYgB3YuYRGUJulZNijGwWZNgA1nBgAylreulAA5sgwZgCucBrU9ADqlLrwBsFgcAH2qboAbqliyOAG7iChBnBmMMReYTQmyABmTpUaAFYGAB4AQl6+-gEmNHAcoXDNrXEgnV0BoWF0cACK0RDwk3RtIMFmlWbFebHqO2ahMIm6IjCUyAAcAAwaWpaViV5axS9w+3kTGgBHNbwWraBwgEwGAC0UDgcBE8JOZjgQN0yNqJnqjSQLS200qNF0kRi+IWS1W6wmOKmGhgJkEl2utyQACZaV5dHQFrgIDQGsUfgBWE7RSr4ekOXHbI5wACSUARsACYDOOgAggqAjAxEtNpUAL76oA)
```
--parser=angular
```
**Input:**
```html
<!DOCTYPE html><HTML>
  <body>
  </body>
</HTML>
```
**Output:**
```
<!DOCTYPE html
>><HTML>
  <body>
  </body>
</HTML>
```
**Expected:**
```
<!DOCTYPE html>
<html>
  <body>
  </body>
</html>
```

**Comment by fisker** [comment]
I think it's because https://github.com/prettier/prettier/blob/82676f6308322496d71d8ea43853190e710e678f/src/language-html/parser-html.js#L290

Make a exception? But, `html` only? or `html/head/body/script/style/meta...`? I don't known..

**Comment by fisker** [comment]
I don't know Angular, but for Vue, I think we can make `isTagNameCaseSensitive: false`, if it's not Vue SFC.
