### ISSUE TITLE
When copy/paste in VS Code can the cursor get on the left of the semicolon

### ISSUE THREAD

**Issue by Luxcium** [prettier/prettier#8172]
#### When copy/paste in VS Code can the cursor get on the left of the semicolon
I have been searching for the last 40 minutes (maybe you will find it right away but I did not)
I have removed the prettier plugin and it fixed my issue.

### Steps To Reproduce:

I am trying to past code i/e `symbolToInfosObject` but I get `symbolToInfosObject;|`

### Expected result

 could I get `symbolToInfosObject|;` 

### Actual result

instead of `symbolToInfosObject;|`

### Additional information

and then either I have to unset `"editor.formatOnPaste": true,` which I wan to keep for when I am pasting a bigger chunk of code ... 

I don't want to un-set the semi in prettier because then it removes the semi 

I have tried many different scenarios and none is working if I have Prettier installed or if I have `editor.formatOnPaste` set to `true` 

```jsonc
}
// [...]
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "typescript.format.semicolons": "insert",
    "javascript.format.semicolons": "insert"
// [...]
}
```

**OS and version**:
 Darwin x64 18.7.0

 

**VS Code Version**:
Version: |1.44.2
--- | --- 
Commit:| ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: |2020-04-16T17:07:18.473Z
Electron: |7.1.11
Chrome: |78.0.3904.130
Node.js: |12.8.1
V8: |7.8.279.23-electron.0
OS:| Darwin x64 18.7.0

**Prettier Extension Version**:
Publisher | Esben Petersen
--- | --- 
Version | 4.5.0 
Last updated | 22/04/2020 à 09:58:00
Released on | 10/01/2017 à 14:52:02 
Unique Identifier | esbenp.prettier-vscode

## Prettier Log Output

```
["INFO" - 21 h 28 min 59 s] Extension Name: esbenp.prettier-vscode.
["INFO" - 21 h 28 min 59 s] Extension Version: 4.5.0.
["INFO" - 21 h 28 min 59 s] Loaded module 'prettier@2.0.5' from '/Users/neb_401/Developer/LuxciumProject/luxcium.io/node_modules/prettier/index.js'
["INFO" - 21 h 28 min 59 s] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 21 h 28 min 59 s] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]

```
[duplicate of prettier/prettier-vscode/1358](https://github.com/prettier/prettier-vscode/issues/1358)

**Comment by thorn0** [comment]
> duplicate of prettier/prettier-vscode/1358

Indeed, it's an issue for prettier-vscode, not for the core Prettier library or CLI.
