### ISSUE TITLE
JSX unstable trailing spaces

### ISSUE THREAD

**Issue by escaton** [prettier/prettier#818]
Given
```jsx
<div>
	long text long text long text <link>url</link> long text long text
</div>
```
if i want to prettify it with for example [30 printWidth](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%5Ctlong%20text%20long%20text%20long%20text%20%3Clink%3Eurl%3C%2Flink%3E%20long%20text%20long%20text%5Cn%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A26%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

i got
```jsx
<div>
  long text long text long text{" "}
  <link>url</link>
  {" "}long text long text
</div>;
```
which is fine, but. [Next run](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%20%20long%20text%20long%20text%20long%20text%7B%5C%22%20%5C%22%7D%5Cn%20%20%3Clink%3Eurl%3C%2Flink%3E%5Cn%20%20%7B%5C%22%20%5C%22%7Dlong%20text%20long%20text%5Cn%3C%2Fdiv%3E%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A26%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) with same settings gives another result:
```jsx
<div>
  long text long text long text
  {" "}
  <link>url</link>
  {" "}long text long text
</div>;
```
and this is weird.

cc @tempname11

**Comment by vjeux** [comment]
cc @rattrayalex

**Comment by rattrayalex** [comment]
Thanks for the report! Have a few ideas what might be causing this, hope to fix this afternoon.
