### ISSUE TITLE
How to extend the estree printer for a new prettier plugin?

### ISSUE THREAD

**Issue by TaylorAbraham** [prettier/prettier#8195]
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: CLI
- Runtime: Node.js v12.16
- Operating System: Windows 10

**Issue**
I am currently writing an ESLint plugin for a language which is extremely similar to JS with some minor differences. As such, I am using the ESTree parser and using a preprocessing step to make any small changes necessary to format some slightly less JS looking code into parseable JS.

I would like to use the ESTree printer unless the AST node is of a certain type. So ideally I would like to make my own printer which extends the ESTree printer, calling the default print most of the time, and having my own custom printing logic for the few nodes unique to this language. It does not appear that the ESTree printer is exported anywhere, is there any way to achieve extension of the ESTree printer with some custom behaviour?

**Comment by thorn0** [comment]
The printer isn't exported and what you want is not possible at the moment, but we might add such extensibility in the future.

**Comment by TaylorAbraham** [comment]
@thorn0 Makes sense, that's what I thought. Would we be able to just add the estree default print as an export from the babel-parser? Or is there somewhere else appropriate we could add it in?

**Comment by thorn0** [comment]
Adding a proper extensibility point that plugins would be able to use sounds like a much better idea. PRs are welcome.

But actually, turns out I lied to you. You can access the printer because all the internal plugins are accessible via `options.plugins`:
```js
const result = prettier.format("a", {
  parser: "foo",
  plugins: [
    {
      parsers: {
        foo: {
          astFormat: "foo",
          parse(text, parsers, options) {
            return {};
          },
        },
      },
      printers: {
        foo: {
          print(path, options, print) {
            const jsPlugin = options.plugins.find(
              (plugin) => plugin.printers && plugin.printers.estree
            );
            console.log(jsPlugin.printer.estree);
            return {};
          },
        },
      },
    },
  ],
});
```

**Comment by TaylorAbraham** [comment]
@thorn0 Thank you very much! I can indeed verify access to the estree printer via the plugins under options. I'm noticing some odd behaviour with doing that though. When I set the astFormat to "estree" (aka just using the estree printer), it would all print fine. However, using the estree printer from my own printer has caused comments to not be printing. I noticed the estree printer also has a `printComments` method in addition to the `defaultPrint` method, so I'm suspecting that may need to be called somehow, but I couldn't find a method of doing that.

This is my code for using the estree printer in my own printer, am I missing something that would cause comments to be omitted?

```
const printers = {
  gmltree: {
    print: (path, options, print) => {
      const jsPlugin = options.plugins.find(
        (plugin) => plugin.printers && plugin.printers.estree
      );
      const { print: defaultPrint } = jsPlugin.printers.estree;

      return defaultPrint(path, options, print);
    },
  },
};
```

**Comment by thorn0** [comment]
The ESTree printer indeed has more than one method, so your printer needs to have (at least some of) those methods too to behave the same way. In your parser, you can access `option.plugins` to copy methods from the ESTree printer to yours.

**Comment by TaylorAbraham** [comment]
@thorn0 I can indeed access the estree plugin from the parse function. However, doing any form of assignment or modification of the printers object from the parse (or pre-process) method seems to be not doing anything.

```
      const jsPlugin = options.plugins.find(
        (plugin) => plugin.printers && plugin.printers.estree
      );

      printers.gmltree = {
        ...jsPlugin.printers.estree,
        print: printers.gmltree.print,
      };
```

This should be adding in the additional methods from the estree printer. But absolutely no difference appears in output. In fact, deleting the "print: printers.gmltree.print" line causes my own print method to still be run even though it should have been overridden completely by the estree printer. This indicates that trying to override or modify the printer at this stage appears to be too late, and has no effect on the printer that runs after the parsing.

**Comment by thorn0** [comment]
You're creating a new object, try modifying the existing one.

**Comment by thorn0** [comment]
closing in favor of #4424

**Comment by thorn0** [comment]
@TaylorAbraham Have you been able to build what you were building? If you have further questions, feel free to ask here. I'll get a notification.
