### ISSUE TITLE
Typescript parser error with '?. ' (questionmark and dot)

### ISSUE THREAD

**Issue by vkrenta** [prettier/prettier#8200]
**Environments:**

- Prettier Version: 4.1.0  - 4.5.0
- React Typescript
- NodeJS v14.0.0
- OS: Windows 10
- Editor: vs-code

Expression
```react
<Button
        title={props.children?.toString()}
        buttonStyle={$.buttonStyle}
        titleStyle={$.titleStyle}
      
      />
```
gives next error 
```
SyntaxError: Expression expected.
title={props.children?.toString()}
                      ^
```
When i downgrade to version 4.0.0 - prettier works, 4.0.1 or later - crashes

**Comment by evilebottnawi** [comment]
We don't have `4.1.0` version, wrong repo, please update prettier to latest version
