### ISSUE TITLE
API fails with "unknown type" for html / angular printing

### ISSUE THREAD

**Issue by LucaVazz** [prettier/prettier#8202]
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: node v14
- Runtime: none / node v14
- Operating System: all

**Steps to reproduce:**

Try to parse and print html / angular-html text via the prettier API.

Example provided here: https://runkit.com/lucavazz/runkit-npm-prettier-html-printer

short form:
```js
prettier.format('<div [foo]="bar">test</div>', {
    parser(text, { angular }) {
        const ast = angular(text)
        return ast
    }
})
```

**Expected behavior:**

Prints out the same as the input.

**Actual behavior:**

Throws an error `unknown type: "root"`

**Comment by thorn0** [comment]
The custom parser API that you're trying to use supports only JS. Here's how you can format Angular markup using Prettier API:
```js
prettier.format('<div [foo]="bar">test</div>', { parser: "angular" })
```
Does this help?

**Comment by LucaVazz** [comment]
Thanks for the quick answer.

So there is no way to hook into the parser for html / angular to adapt the AST before it gets printed out?

That's what I'm trying to do in the end, but left out of the examples for brevity.

**Comment by thorn0** [comment]
You can use [the plugin API](https://prettier.io/docs/en/plugins.html#developing-plugins) (see also https://github.com/prettier/prettier/issues/8195#issuecomment-622591656). Or this hack: https://github.com/prettier/prettier/issues/3150#issuecomment-394150810
