### ISSUE TITLE
Typescript: interface/type delimiter

### ISSUE THREAD

**Issue by connormanning** [prettier/prettier#8203]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKtgXm2AB0ptsBDJbARgBoyKAjGgJkfOzBoGYyAvmRD0QEDDACW0AM7JQlAE6KIAdwAKShHJSUANqspo5o5ospgA1nBgBlDBclQA5shiKArnFEALGAFs9AHUfSXgZBzA4W20wyQA3MLRkcBkTECcZOEUYdXNnf0pkADN9LNEAKxkADwAhcysbW0p-OAAZJzgSsu8QKurbJ2c9OABFDwh4br1ykAdFLMUU9CwZMEVJCRE5jdggyQATGB9kAA4ABlEMFSyg8wwU67hF+K7RAEcJ+DzxHRBKGQAWigcDgBzB20UcE+kiheUoBSKSFKM16WX8kmmsxkQxG40mXWRPVEMEozH2RxOSA4qHMkj0QwAwhB-IUUs8AKzbDxZXBknQo2bxLwASSg4NgtnWmxgAEFxbZ0CMsXABAIgA)
```sh
--parser typescript
--no-semi
```

**Input:**
```tsx
type T = {
  a: 1,
  b: 2,
  c: 3
}

```

**Output:**
```tsx
type T = {
  a: 1
  b: 2
  c: 3
}

```

**Expected behavior:** I expect some sort of delimiter between the lines in my `type`.  With default settings, there would be semicolons, but with `no-semi` set, there is no delimiter at all. 
 This isn't a stylistic complaint though - this lack of delimiter makes things more cumbersome to work with due to Prettier respecting a user's newline entry.  For example:

Say I have a `type` definition which does not fit within 80 characters so is forced to be separated into multiple lines:
```
type MySuperAwesomeType = {
  someNumber: number
  someOtherNumber: number
  yetAnotherNumber: number
  s: string
  b: boolean
}
```

Then maybe I refactor a bit to:
```
type Numbers = {
  someNumber: number
  someOtherNumber: number
  yetAnotherNumber: number
}
type MySuperAwesomeType = {
  n: Numbers
  s: string
  b: boolean
}
```

Now, `MySuperAwesomeType` fits within 80 characters and thus an equally valid format according to Prettier is:
```
type MySuperAwesomeType = { n: Numbers; s: string; b: boolean }
```

But because I currently have newlines here, Prettier will *not* collapse these into one line automatically even though the one-line version is acceptable.  That's fine, but now if I would like to join these lines into a one-line definition, I need to manually insert delimiters to keep my code valid and allow Prettier to format it.  This is a bit clunky, here is a comparison:
![prettier-delimiters](https://user-images.githubusercontent.com/5015470/80821458-60011a00-8b9e-11ea-9c27-5cc746c058ba.gif)

I wouldn't care what the delimiter is, but having *something* there would make things easier to work with.  I believe the same applies to the typescript `interface` keyword.

Related to #6859, although in opposition to that discussion, I'd not propose to make this an option but instead to change default behavior *always* insert a delimiter because of the usability advantage described here.

**Comment by thorn0** [comment]
> That's fine, but now if I would like to join these lines into a one-line definition, I need to manually insert delimiters to keep my code.

You don't really need to do that. Just remove the first line break after the opening curly brace and Prettier will do the rest. Please see https://prettier.io/docs/en/rationale.html#multi-line-objects

**Comment by connormanning** [comment]
Very good to know - it solves my issue perfectly.  I had thought that the "Rationale" section would consist more of *justification* for chosen formatting choices rather than behavioral notes, so I missed that section in the docs.  Thanks for the response!
