### ISSUE TITLE
There must not be a line break after flow type annotation colon.

### ISSUE THREAD

**Issue by ernestostifano** [prettier/prettier#8209]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAsmgFUxwF5tgAdKbG7DAJwgwEYlsB5AIwCs4wZsAH2xQArgFtOcekOwBnGPQCWUAOazOECABs4AQ2rCAFCoyiYbBcrUBKbCQB85PWzGTpAGmydLilaoBfKgCAbioqAHoIjgBVAgAFOOwAYXYAEQBRbAB1AEkAGXzsAgAlXIBxcoyS4oAJLIAxdkL2PIA5cuxqkvYSpEjojIBlfJULYoALaRxxUQURCAEpbD1sbRUcTnp9AGsVgDN4GQoQBiZmE+x0LBWoKEW9GCVobEhtaAA6I333gHdruAROQYPRgOAAWj0h2k4IB4Le0BsIA8ICYT2gcmQoD09EYv3iOIQmJQem0vz0aExKK2oJ2cBgQxBYH8yEUojgKImMHE2myEyU8GBoLgQyJAqUADcBWhkOA5FSQCo5NIYPF6HpVOI9Mh9qTlSjuHIAB4AIXVYDpDL04jgoygcB1eo5IENRqG-l0AEVRIsHUhddp9acccr6LLOHopNpkadrDBskoACYwCbIAAcAAYUWdldl1RhZQw4KGJQ6UQBHH3wNVMYkgPRycH2uCJlsx7aVpTbNUarWOwPO5XiJSs+jslFyD1wb2+-tBmCRhPJ1NIABMKMUeiU6zUyQg4j7KGLAFYY3M4ARI8SA0GJezclBW7AhmBlBgYABBR9DdC6OdwAIAiAA)
```sh
--parser babel
```

**Input:**
```jsx
type MyType = {
    prop1: Object | number | string | boolean | (input: string) => {a: number, b: string}
};

// OUTPUT CODE WILL TRIGGER THE FOLLOWING ERROR:
// ESLint: There must not be a line break after "prop1" type annotation colon.(flowtype/space-after-type-colon)
```

**Output:**
```jsx
type MyType = {
  prop1:
    | Object
    | number
    | string
    | boolean
    | ((input: string) => { a: number, b: string }),
};

// OUTPUT CODE WILL TRIGGER THE FOLLOWING ERROR:
// ESLint: There must not be a line break after "prop1" type annotation colon.(flowtype/space-after-type-colon)

```

**Expected behavior:**
Maybe in this case code wrapping? Should be avoided? Or must be done with a deeper indentation level like:

```jsx
type MyType = {
  prop1: Object
        | number
        | string
        | boolean
        | ((input: string) => { a: number, b: string }),
};

**Comment by thorn0** [comment]
For ESLint to not conflict with Prettier, all ESLint's formatting-related rules must be disabled. The easiest way to do that is to use [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).
