### ISSUE TITLE
Unstable object expansion within function call

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#821]
```js
f(`${{
  a: 4,
  b: 9,
}}`);
```

turns into

```js
f(
  `${{ a: 4, b: 9 }}`,
);
```

then

```js
f(`${{ a: 4, b: 9 }}`);
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22f(%60%24%7B%7B%5Cn%20%20a%3A%204%2C%5Cn%20%20b%3A%209%2C%5Cn%7D%7D%60)%3B%5Cn%5Cnf(%5Cn%20%20%60%24%7B%7Ba%3A%204%2C%20b%3A%209%2C%7D%7D%60%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by jlongster** [comment]
So it only happens within string templates?

**Comment by vjeux** [comment]
As far as I know, yes. I'm guessing it's due to the hackery we do with the removal of softlines and forcing objects to be expanded.

**Comment by jlongster** [comment]
Most likely, yeah.

**Comment by josephfrazier** [comment]
I didn't close this from the commit message of https://github.com/prettier/prettier/commit/374a68201c966ee9064a1173f5dfeb37980cfbe3, but I think it's actually fixed now:

```js
f(`${{
  a: 4,
  b: 9,
}}`);
```

becomes:

```js
f(
  `${{
    a: 4,
    b: 9
  }}`
);
```

which stays stable.

**Comment by vjeux** [comment]
Nice!
