### ISSUE TITLE
LICENSE file only contains MIT license but code in project contains BSD license in file headers

### ISSUE THREAD

**Issue by samccone** [prettier/prettier#8211]
LICENSE files should contain all of the projects licenses. Currently the license file only contains the MIT license however the project distributes the files:

v2_0_5/third-party.js
v2_0_5/standalone.js
v2_0_5/index.js
v2_0_5/bin-prettier.js

which contain the BSD-2-Clause license(s)

**Comment by thorn0** [comment]
closing in favor of #9980
