### ISSUE TITLE
Ignore Perl Toolkit Template code in embedded JS

### ISSUE THREAD

**Issue by ylavoie** [prettier/prettier#8212]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtApAHSgAjwYhwBUALASwGccS4AbABzgCccKSIBXWgExwCM4OMlDC0O3OL2E4AZmVpwqAd3JgSOJfNr9BFZgDdJOAIYVseHIRgR6AWgWHtTRfWh6qACjIA6ON5zcEGAcALYIMFTQODA0ZCwQSlAAlADc0eRUwqLiiuYEOACqAJIA9LQQAObC3iQwIbQANIWl5RWcMDV1jc0lIcbVtfUmULz6xkxknFTFJXowHPQlOPTGFbm4eLboALrYADwAhAAiAPIAwkQAmgAKAKLUXQB8+4PaAB71UBQAvJggtTB6EgSiUlGDvEoAMzeCBMColACMAE4USU3q8-s8oHsaMZuFiLIScHsYGQYApHhhomSFDgdnsSqTyXAsXkiTgqUUAGKyWEhbwUGAATwUbDgcBgdN2G3ZhL2tGEAGscM5aL8QIKRYoaBK-tRnDJ1WAKBQSlSZHyBcLRTrJTs9cLGOr4G8YCVjWYQDgSgTZVTbgAZADK3NY1u14rt0tlRPlSpVdHVmptkb1JANRpNZvQYa1YolUodQqdfxdbo9ep9bKJ-oAckdCzKazmuScAEq3ACCZwAEqwcN8hCIxBIAPrJiMF+1NmNxqDK1VJ8P5mBpjN-D3Z-v2r2OuDOuCu90myu+9l1hvT2cUMATeiSvcHo8AK2MYxvd9XIDPMZwYxYtAUCEfBnNAcgVAOODANWv4WJyPIFEGtxtt43DGPAFpMH0UYwbBeB-GhGF8uhfxIDgfxUohyGoehcCYdhhYgLhsEXo2eE4AAvikzHErMt5kPeP5yh+AkPsW+6loebqvu+-H3nqFBMGA6rPqa9CqhAeLMN4ql6mo4xzOqHAwDItgAByYgyImCfsJS4vitmvFiIANCANikm4yCgOMTAJNc4wIBQyAgG+EBkNwLkgHwTDGGAioSkGKxgMIFTIDATAcHArmvAA6uQ8AUElcBBoFZJkPoZJCsFHqRcIehMDA1wxRUfTIDIxiAVlICqW8ABCMVxQlxhhAGwhwG1HV6K5PVBilCgAIocBA8ATZ1rkrEw9XBa8kXqcIMA5eFMTIGZAAM62+XoOUxfQwXqYoBjja5ACOS3wE1NhBSgpi2FA4oSBFrnOK9cRwE1qytUg7VrRqcAhGQaUZV1FBzXAi3LeNUOTV1MDGHwh3cMdSAAEyuel-QKlAFSgSEkMgFA0BPSAHB6EQeNfdDU0gPomVFCM4RBnJMCdiMQbhqtegcRxQA)
```sh
--arrow-parens avoid
--parser html
--trailing-comma none
```

**Input:**
```html
[%
   # This helper should be included in files which will be served as
   # top-level responses (i.e. documents on their own); this includes
   # UI/login.html, UI/logout.html, UI/main.html and various UI/setup/ pages
   -%]
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
        <title>[% title %]</title>

        [% IF form.stylesheet %]
            <link rel="stylesheet" href="css/[% form.stylesheet %]" type="text/css" />
        [% ELSIF stylesheet %]
            <link rel="stylesheet" href="css/[% stylesheet %]" type="text/css" />
        [% END %]
        [% FOREACH s = include_stylesheet %]
            <link rel="stylesheet" href="css/[% s %]" type="text/css" />
        [% END %]
        <script type="text/javascript">
            var lsmbConfig = {
                [% IF USER.dateformat %]
                 "dateformat": "[% USER.dateformat %]"
                [% END %]
            };
        </script>
        <script type="text/javascript" src="js/preloader.js" charset="utf-8"></script>
</head>
</html>

```

**Output:**
```html
SyntaxError: Unexpected token (3:18)
  1 | 
  2 |             var lsmbConfig = {
> 3 |                 [% IF USER.dateformat %]
    |                  ^
  4 |                  "dateformat": "[% USER.dateformat %]"
  5 |                 [% END %]
  6 |             };
```

**Expected behavior:**

Perl Template Toolkit statements are within '[%' and '%] and are properly handled/ignored in the HTML part but they trigger an error in the embedded section. 

At minimum, everything within those introducers should be considered as correct and returned as is, within the introducers, in the prettyfied code.

At best, support Perl Toolkit Template.

**Comment by thorn0** [comment]
> At minimum, everything within those introducers should be considered as correct and returned as is,

That's how it already is. This error appears only on the playground. In production, Prettier just outputs the `script` tag as is. 

> At best, support Perl Toolkit Template

Prettier has a plugin API that can be used to implement that. There is no plans to add support for more HTML template languages to the core.

**Comment by ylavoie** [comment]
This appears in production too. The code shown in the playground was extracted from my prudoction code which fails to compile.
