### ISSUE TITLE
Error: Extension 'Prettier - Code formatter' cannot format 'src\sass\styles.scss'

### ISSUE THREAD

**Issue by TamerCrea** [prettier/prettier#8219]
Hi folks,
I'm using VSCode and prettier since a few weeks ago. I'm trying to format my SCSS file but I don't seem to achieve it. These are the details of my issue:

**Prettier 4.5.0 over VS Code 1.44.2 (Win10 64bit)** 

Prettier seems to work fine in the CSS Generated file, but when I try to format my SCSS document, the bottom bar throws this error:
```sh
Extension 'Prettier - Code formatter' cannot format 'src\sass\styles.scss'
```
I've also tried adding the SCSS Formatter but got the same error. On the other hand, Prettier is working fine with my HTML, TS and JS Files.
Thanks

**Comment by AshotN** [comment]
I also can't format SASS files using WebStorm and Prettier 2.0.5. If it is relevant the file is named `index.module.sass`

**Comment by thorn0** [comment]
This is an issue for another repository, namely VS Code extension for Prettier: https://github.com/prettier/prettier-vscode

When opening an issue there, please include what Prettier outputs to the Output pane when you try to format your file. 
![image](https://user-images.githubusercontent.com/94334/81126234-60edcf00-8f43-11ea-88e8-b775accb1259.png)

Also please check how your code is formatted in the playground (https://prettier.io/playground). If needed, use the <kbd>Copy markdown</kbd> button there to copy the result and paste it to your issue.

@AshotN The `.sass` syntax is not supported by Prettier, only `.scss`.

**Comment by AshotN** [comment]
Is there any issue regarding that? I couldn't find one.

**Comment by thorn0** [comment]
@AshotN There is no plans for adding new parsers to Prettier core. Prettier has a [plugin API](https://prettier.io/docs/en/plugins.html), which can be used to implement SASS support as a separate project.
