### ISSUE TITLE
Function args should either all be on 1 line or each split

### ISSUE THREAD

**Issue by AliRain** [prettier/prettier#8224]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnArgBzgJwDLQDmAYulGAHICGAtnABQBmAljqjAII6EA0ABKjiQoAEy68+MABasx3fsAA6UPqrXrVLNjGLM4AGxFI+AclQQ6fAG5V96OCZ7LVg4SN0Gjp85YjTc1rb2Js4a6gC+AJQA3CA8IBCYMMzQqMigVDg4EADuAAqZCGkotjlUAJ5p8QBGOFRgANZwMADKmPXMUITIMDj28VIwNPoA6jLwqO1gcC1FzMlW8+XI4KhVIJ2CODB5dYQ0VMiMtoLxAFaoAB4AQnWNzS20cHidcEcncOdXLZ2E+nAARXQfjeSGO+lOIHabFwK2qVGqBjiUJwnRgI2YImkyAAHAAGeKYbKCEZ1TArIlwLZWN7xACOwPgu0SxRAVFQAFooHA4CJecicHAGaw4LsqPtDmCPvFBDRmD0+p80L9-kCQe8IUqYAiMVipMgAEzxXpUZj6X4AYQsBxWVIArMj0IIACoI4rgyFWewASVECFaYFRSQ4ohaMHK-w1gnC4SAA)
```sh
--parser babel
```

**Input:**
```js
superLongFuncName(firstArg, secondArg, thirdArg, {
            firstField: 'some value',
  secondField: 'some other value'
          });
```

**Output:**
```js
superLongFuncName(firstArg, secondArg, thirdArg, {
  firstField: "some value",
  secondField: "some other value",
});

```

**Expected behavior:**
```js
superLongFuncName(
  firstArg,
  secondArg,
  thirdArg,
  {
    firstField: "some value",
    secondField: "some other value",
  },
);
```

**Comment by thorn0** [comment]
The output in your example is okay, but the current behavior indeed has some ugly manifestations. See https://github.com/prettier/prettier/issues/2239
I'm closing this issue in favor of that one.
