### ISSUE TITLE
Extra space after function keyword when exporting anonymous function

### ISSUE THREAD

**Issue by xeoneux** [prettier/prettier#8237]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGBnAOgFcMACAXlIDMiowYBLaUgCgGsp0BKU4AHSilS2ODCLZBHdATxgAFnAC2AQwJgRy+ABVlAIwA2cFgHIF+-RAD6Adxz6AJsYA01WvSaCWMPYZ79BQqQCQgC+XAIhAiBOIBAYjNB4yKDK2NgQ1gAKqQhJKMr61soAnkkxutjKYGyiAMoYVQxQAObIMNhEcDFyMIr6AOpyDPB4DWBwtbnDDABuw8XI4HhlIE14cLiZlc0qyFQF6zEAVnhoAEKV1XXKinAAMk1wewddICdotU3NhgCKRBDwZ76Q4gBrYdbYRa6PRwfTRUHYJowfoMewwOTIAAcAAYYhh0ut+pUMIt8XAITMnjEAI7-eBbOJ5EDKPAAWk4cHsnPhIlpDBEW2UO2UQJB60UDDaHVeeC+vzpTyQ+2Br28uhRaIxSAATDF2soGPovgBhCCKXYockAVnhRHWOl0eWVIJmnQAklAubBauoGPEAIKe2owYqGUVwEIhIA)
```sh
--parser babel
```

**Input:**
```jsx
exports.up = function (knex) {
  return knex.schema.createTable('hello_world', function (table) {
    
  })
}

```

**Output:**
```jsx
exports.up = function (knex) {
  return knex.schema.createTable("hello_world", function (table) {});
};

```

**Expected behavior:**
Output should be:
```jsx
exports.up = function(knex) {
  return knex.schema.createTable("hello_world", function (table) {});
};

```

There's an extra space after the function keyword

**Comment by thorn0** [comment]
See the [version 2.0 release notes](https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot).
This behavior is expected, it isn't configurable, and isn't going to change.
