### ISSUE TITLE
Swapping elements via array destructuring bad formatting

### ISSUE THREAD

**Issue by h0tw4t3r** [prettier/prettier#8238]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDATrzAXkwG0BGAGkwCYqBmKgFioFYqA2AXQB0oS9cJAAycqA8p05FS46qJz4SdSSAogIABxgBLdMlACIAdwAKeBGmQhsAGyPYAnpbUAjXNjABrODADKGj20oAHNkGFwAVzg1AAsYAFsbAHUY7Xg0ALA4Xws07QA3NIcrMDRnECC0OFwYE3dg+OxkADNbKrUAKzQADwAhdy8fX2x4uAAZILgWtuiQLu7fIOCbOABFCIh4aZt2kADcKtwrF2wXOBtVPdwgmCTtABMYGOQADiE1DVwIKqT3DStPnBDvkpmoAI4beB1TSWFDYNAAWigcDg91Rl1wcAh2kxdWwDSaSFaO1mVXi2jCkVJSxW602UyJMzUMFOd0ezyQtBA4Ww2hsSwAwhB4o0rECWJcIlUACqnWHE3b5KIASSgaNgvjA1y0AEE1b4YA4VtsqgBfU1AA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```js
const arr = [1, 2, 3, 4, 5, 6]
[arr[0], arr[1]] = [arr[2], arr[3]]
```

**Output:**

```js
const arr = ([1, 2, 3, 4, 5, 6][(arr[0], arr[1])] = [arr[2], arr[3]]);

```

**Expected behavior:**
```js
const arr = [1, 2, 3, 4, 5, 6]
[arr[0], arr[1]] = [arr[2], arr[3]]
```

**Comment by thorn0** [comment]
This behavior is expected. Please see https://prettier.io/docs/en/rationale.html#semicolons
