### ISSUE TITLE
Incorrect formatting with safe-navigation-operator and property access via bracket-notation in angular

### ISSUE THREAD

**Issue by Dassderdie** [prettier/prettier#8252]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgAICGB+AdAIwG0wBddAX3JABoQIAHGAS2gGdlRMAnLiAdwAK3BOxSYANn0wBPdrXxdMYANZwYAZXpKmUAObIYXAK5xaACxgBbcQHUzTeKy1g46kQ6YA3B9OThWciA6rHBcMAKKupaYyABmEiG0AFasAB4AQooqauqYlnAAMjpwcQmmICmp6jq64nAAikYQ8KXiiSBaXCFcfph6RuLcNB1cOjA2TAAmMGbIABwADLT0vCE2ivR+K3DdniW0AI5N8BEMoiCYrAC0UHBwk-fDXHBHTM8RmFExSPFt5SGWJgGYz-Gp1RrNEpIQwmWgwTD4CbTWZIAAscMUTHENQAwhBLNE-DsAKzDIwhAAqCNEv3anhMAEkoA9YOowKNGABBZnqGDSOqtEKUIA)
```sh
--parser angular
--single-quote
--tab-width 4
```

**Input:**
```html
{{ a?.b[c] }}
```

**Output:**
```html
{{ (a?.b)[c] }}

```

**Expected behavior:**
```html
{{ a?.b[c] }}
```

The current output from prettier is incorrect and will cause errors during compilation (at least in angular 9 with ivy and strict-mode turned on) and possible also in runtime (if `a` has no property `b`, it is going to throw `Cannot read property c of undefined`-error).
It is also inconsistent with the ts-formatting for such an expression.

**Comment by thorn0** [comment]
The AST can be explored here:

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA-AOgEYG0wC6IANCBAA4wCW0AzsqKgE5MQDuACswvSqgDZtUAT3qlsTVGADWcGAGVyUqlADmyGEwCucUgAsYAW34B1PVXi0lYOPJ4WqANwvDk4WmJAracJjA6SqoaoyABmAj6kAFa0AB4AQpIycvKohnAAMipwYRG6IDGx8iqq-HAAiloQ8Ln8kSBKTD5MbgD6rWqt2CoAJiUkDUwqMCZUPTB6yAAcAAyk5Kw+JpLkbgtwzY45pACOVfABFLxotAC0UHBwPVcDTHB7VHcBqEEhSOF1+T6GVBraXyUypVqjkkJodKQYKhsKNxpMkAAWSGSKj8EoAYQghmCbg2AFYBlofAAVaG8D71Rw6ACSUGusHkYCGlAAgnT5DBhGVaj4AL68oA)
```sh
--parser __ng_binding
--single-quote
--tab-width 4
```

**Input:**
```__ng_binding
a?.b[c]
```

**Output:**
```__ng_binding
(a?.b)[c]
```
