### ISSUE TITLE
Newline is inserted within template literal, breaking behavior

### ISSUE THREAD

**Issue by noelforte** [prettier/prettier#8279]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlAagcUwF5MADAHjQDcBzTADwFsAbKNIgHRAAsYYAHJAHohAd3EA6UQGYJEAE40hAJgAM6odRpdMGAJ7M4nEABMAlmn7MAhnqSYo0OAG4uAPgAkwNHsYAjCGY0CQArCDMoAAouLgBKAF9yTVo3UmcQABoQCH4YM3RkUGt5eQhRAAVihDRkEGtmUVsarL95azAAazgYbH52iJpkGHkAVzgs3hYAdW4zeEt2uGxqubMqOb1asDRmkAi0OHkYcraaRmtkADN6g6yQtHoAITbO7uxrRjgAGQi4K5vxiB7vRsANDABFEYQeD-IKAvryA7yWp+ax+ODMTIgfjyCIwKZmEwwbjIAAcqiyOIgBymbX4tRxcCRVD+WQAjlD4CccjUUNY0ABaKBwOAmUVY+RwDlmSUnaxnC5Ia5wrIHRhmIajQFoMFwSHQv5KgFZGBoglEklIZQmtpmZgDADCEEY51qTIArFiRgcACpo3nK24gKhjACSUDFsGwYFxuQAghHsDADIbA3B4vEgA)
```sh
--parser babel
```

**Input:**
```jsx
const SVG = `<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">${symbols.join("")}</svg>`;
```

**Output:**
```jsx
const SVG = `<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">${symbols.join(
  ""
)}</svg>`;

```

**Expected behavior:** Since template literals output exactly what's fed to them, it's important that their formatting not be impacted significantly, as this alters the output. Prettier moving the double quote to its own line and indenting it yields different results when the array elements are joined versus if this code were written on one line only.

**Comment by thorn0** [comment]
> Prettier moving the double quote to its own line and indenting it yields different results when the array elements are joined versus if this code were written on one line only.

That's not how JavaScript works. The formatting Prettier does in this case may not be pretty, but it's safe and doesn't change the output.

**Comment by noelforte** [comment]
Ah my bad, there were multiple copies of the same output file and I wasn't looking at the right one. 🤦‍♂️Was totally boggled as to why JS would be inserting weird lines and thought the formatting had something to do with it.
