### ISSUE TITLE
Whitespace is removed from between footnotes

### ISSUE THREAD

**Issue by Undistraction** [prettier/prettier#8301]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAegRgLpIAQCyAhmACbREA2pANHgBIB0BjdATAAyYDMjeAwtBgAnAJYAjAK4xR0AM54IAMzxzJUSqIDmACxh4iUUnlKi4+mBDwA3UTCIBbUVDwARVfZiS5fflTCiSnwAKqJyanB4AJKwrHgAnGwAFGwAlHQADhmMmABs3AC0mADsuYwAOlCVGGy4hETCMlBwRJJ0AIKMAEpxAFIQlJpKSnB0royddPQQEBlwwnQ9ADJxAOLCcAji81p0Kx2UEKJEdL2MAGJxAEI7DoZ0AApxrpLiUBDWBV1EAF50q3EAKJyDIQOR2CB0ADKa0MdxObjWzlIozwnU6BiMeFWM1IVEodEBjH4cU4JT4ADU7I5nG5VJIspQ4A4EJ5ZC5LHgMhtrKyDGBpJENiDRMIiJZhABPPAiEj6ZwjMAyeT4OSSuTwO4yMB4HlmADumOMLPsBUMVHVYUUKmRolspEkVC5DW1ogyhn0ePsfCuBF6dG4AFZcplGKJcoGABy8SrVdDcOpXBobGAwU5xJYkADWez4hmMBAgwjEcjoLDomHi8V4eGCOkiciZcAyBTg1ggWbgxhRYA2RDkkWUeHEEFI0s1czFXg2fChTYyFdyKXSXOy1YKVcYIBoIFmyqgcmQoGTEH1DwaCEPKCo+qI6u3IHEYrAnZgUPdASgWmQIkkoxAegOJQADqOh2HAIIkHAUKXnYdp2JKyDgOED7OAOjQPGKWh3MgShUAOO4AFZyAAHlcz6vlCjhwEszhwLh+H-sRJFQs4WhMgAipIEDwAxlAESA7rCOhSF3MIWbkPqUAPtyzgwMBoikDAOjIJGHA7tyYJwMBYoZEh3IQfMvIPgAjtx8CYbMV4gP2BTNF2XYPhsZminAmFENhRB8QJA5OD+wh-ju4Jfpx5n0UgeH8f+9jiApSkqUgbA7rKoiaF+ggODhKAQYGD7eHAwREOIV6RQJ1h-jEKKwFCvZujA7RGFCMCSky3lwAAvu1QA)
```sh
--parser markdown
```

**Input:**
```markdown
[^1]: Macdonald, H.M., 2013. Contributions of sunlight and diet to vitamin D status. Calcif. Tissue Int., 92(2), pp.163-176.

[^2]: Martineau, A.R., Jolliffe, D.A., Hooper, R.L., Greenberg, L., Aloia, J.F., Bergman, P., Dubnov-Raz, G., Esposito, S., Ganmaa, D., Ginde, A.A. and Goodall, E.C., 2017. Vitamin D supplementation to prevent acute respiratory tract infections: systematic review and meta-analysis of individual participant data. BMJ, 356, p.i6583.

[^3]: Barrett, J., Lack, L. and Morris, M., 1993. The sleep-evoked decrease of body temperature. Sleep, 16(2), pp.93-99.
```

**Output:**
```markdown
[^1]: Macdonald, H.M., 2013. Contributions of sunlight and diet to vitamin D status. Calcif. Tissue Int., 92(2), pp.163-176.
[^2]: Martineau, A.R., Jolliffe, D.A., Hooper, R.L., Greenberg, L., Aloia, J.F., Bergman, P., Dubnov-Raz, G., Esposito, S., Ganmaa, D., Ginde, A.A. and Goodall, E.C., 2017. Vitamin D supplementation to prevent acute respiratory tract infections: systematic review and meta-analysis of individual participant data. BMJ, 356, p.i6583.
[^3]: Barrett, J., Lack, L. and Morris, M., 1993. The sleep-evoked decrease of body temperature. Sleep, 16(2), pp.93-99.

```

**Expected behavior:**
Blocks should be respected.

**Comment by thorn0** [comment]
Indeed, seems to be a bug.

From https://pandoc.org/MANUAL.html#footnotes:

> Each footnote should be separated from surrounding content (including other footnotes) by blank lines.

**Comment by thorn0** [comment]
@Undistraction Work is currently underway to update the Markdown parser that Prettier uses. See #8140. Could you probably help with testing that PR against your Markdown documents? I'm particularly interested in testing footnotes-related issues.

**Comment by bitstein** [comment]
I still experience this bug.

**Comment by qaqland** [comment]
meet this bug when use mdbook
