### ISSUE TITLE
HTML Whitespace formatting in wrong behavior

### ISSUE THREAD

**Issue by maxiqboy** [prettier/prettier#8304]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#.....)

**Input:**

```html
    <div class="navigation-buttons">
      <div class="is-pulled-right">
        <router-link to="/products" class="button"><i class="fa fa-user-circle"></i><span>Shop</span></router-link>
        <routerlink to="/cart" class="button is-primary"><i class="fa fa-shopping-cart"></i><span>{{cartQuantity}}</span></routerlink>
      </div>
    </div>
```

 **Output: On Playground with Vue Parser  ( not working - don't know why )**
[on playground ](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8ATAlgN1TABsBDAZ3IF4AdEKU-XAc1Jl2gFoAjAVxhjRydAHw0oGDDgJEylWiFzlOAB17FicbJwBOLABYxR4yZMw6I-ODs7FcUANapBCgPQqL2XmBjC0JCmo6PgFoUUxcWUCFADNSVDjOXnJrTjBcHRI4cNdcEUxyFVIoEQBlfQgVTFdC4vzXCysbO0cxCVN0c0t4HRanFzpXMFIdI385IJAQwQklVT0AWxGAT3DIgPk6OITSTnIKlRV7ZjSRsfq8gqKS4GBh0YBFXmL2GGWAX3fq2pLqxp6+m0OtU8PggVJXKCRCAADQgSrsITIUAjCwAdwACiMEORkCBSMQ0aRlri4dwdKQwA44DBSkV0lBmMgYDpeHA4YYFsQAOr6XDwWpgOClHH8gj85Z4sCUWGKKApUYYinMJbIOLEFJwgBW5AAHgAhClUmmlUgLOAAGXscDVBM1IB1utKx00Twg8FtGvZICKOgVePwbNlHnsMG5uGwMH0yAAHAAGOEeCApbkUlR4jxwBX4G1wgCOvHdcCVlVxKAonCgcC0WllOjgBYyxeVqqQ6vtKQWuGZrO95BdcDdHrbdu9MFI3HDkejSAATHCWaRcC1mABhCALVsgLMAVllyTgABUJ2X297A3AAJJQbAIWlgPQqGAAQRvpTemk9KU+QA)

**Output: On Playground with html Parser and  `--html-whitespace-sensitivity` : `strict`**  
[on playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8ATAlgN1TABsBDAZ3IF4AdEKU-XAc1Jl2gFoAjAVxhjRydAHw0oGDDgJEylWiFzlOAB17FicbJwBOLABYxR4yZMw6I-ODs7FcUANapBCgPQqL2XmBjC0JCmo6PgFoUUxcWUCFADNSVDjOXnJrTjBcHRI4cNdcEUxyFVIoEQBlfQgVTFdC4vzXCysbO0cxCVN0c0t4HRanFzpXMFIdI385IJAQwQklVT0AWxGAT3DIgPk6OITSTnIKlRV7ZjSRsfq8gqKS4GBh0YBFXmL2GGWAX3fq2pLqxp6+m0OtU8PggVJXKCRCAADQgSrsITIUAjCwAdwACiMEORkCBSMQ0aRlri4dwdKQwA44DBSkV0lBmMgYDpeHA4YYFsQAOr6XDwWpgOClHH8gj85Z48gs3A+WGKKApUYYinMJbIOLEFJwgBW5AAHgAhClUmmlUgLOAAGXscA1BO1ID1+tKx00Twg8HtWvZICKOiVeM5xHlHnsMG5uGwMH0yAAHAAGOEeCApbkUlR4jxwJX4O1wgCOvE9cBVlVxKAonCgcC0WnlOjgRYypdV6qQmsdKQWuGZrN95DdcA9Xo7Dt9MFI3Ej0djSAATHCWaRcC1mABhCALdsgHMAVnlyTgABUpxXO778GyAJJQbAIWlgPQqGAAQTvpTemm9KU+QA)

As you can see in the result below, there is no white space on html text, but they still break in lines

```html
    <div class="navigation-buttons">
      <div class="is-pulled-right">
        <router-link to="/products" class="button"
          ><i class="fa fa-user-circle" /><span>Shop</span></router-link
        >
        <routerlink to="/cart" class="button is-primary"
          ><i class="fa fa-shopping-cart" /><span>{{
            cartQuantity
          }}</span></routerlink
        >
      </div>
    </div>
```

**Expected behavior:**

I got this behavior when choosing HTML parser with  `--html-whitespace-sensitivity` : `ignore`  [in playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8ATAlgN1TABsBDAZ3IF4AdEKU-XAc1Jl2gFoAjAVxhjRydAHw0oGDDgJEylWiFzlOAB17FicbJwBOLABYxR4yZMw6I-ODs7FcUANapBCgPQqL2XmBjC0JCmo6PgFoUUxcWUCFADNSVDjOXnJrTjBcHRI4cNdcEUxyFVIoEQBlfQgVTFdC4vzXCysbO0cxCVN0c0t4HRanFzpXMFIdI385IJAQwQklVT0AWxGAT3DIgPk6OITSTnIKlRV7ZjSRsfq8gqKS4GBh0YBFXmL2GGWAX3fq2pLqxp6+m0OtU8PggVJXKCRCAADQgSrsITIUAjCwAdwACiMEORkCBSMQ0aRlri4dwdKQwA44DBSkV0lBmMgYDpeHA4YYFsQAOr6XDwWpgOClHH8gj85Z4sCUWGKKApUYYinMJbIOLEFJwgBW5AAHgAhClUmmlUgLOAAGXscDVBM1IB1utKx00Twg8FtGvZICKOgVeO4pG4cGIso89hg3Nw2Bg+mQAA4AAxwjwQFLcikqPEeOAK-A2uEAR147rgSsquJQFE4UDgWi0sp0cGLGTLytVSHV9pSC1wzNZ3vILrgbo9nbt3pgQajMbjSAATHCWaRcC1mABhCALDsgXMAVllyTgABUg5Wu978GyAJJQbAIWlgPQqGAAQTvpTemk9KU+QA)

Also, in VS Code, I can edit manually and Prettier is ok with that ( not undo to that above format )

```html
<div class="navigation-buttons">
  <div class="is-pulled-right">
    <router-link to="/products" class="button">
      <i class="fa fa-user-circle"></i>
      <span>Shop</span>
    </router-link>
    <routerlink to="/cart" class="button is-primary">
      <i class="fa fa-shopping-cart"></i>
      <span>{{ cartQuantity }}</span>
    </routerlink>
  </div>
</div>;

```

**Comment by fisker** [comment]
You might wan check this option [--html-whitespace-sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity)

**Comment by maxiqboy** [comment]
> You might wan check this option [--html-whitespace-sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity)

thanks, but I see in my code, there is no html whitespace, and I can edit manually and Prettier is ok with that ( no reformatting )

**Comment by fisker** [comment]
Exactly, there is no whitespace, so we have to break in this way. [with --html-whitespace-sensitivity=ignore](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8ATAlgN1TABsBDAZ3IF4AdEKU-XAc1Jl2gFoAjAVxhjRydAHw0oGDDgJEylWiFzlOAB17FicbJwBOLABYxR4yZMw6I-ODs7FcUANapBCgPQqL2XmBjC0JCmo6PgFoUUxcWUCFADNSVDjOXnJrTjBcHRI4cNdcEUxyFVIoEQBlfQgVTFdC4vzXCysbO0cxCVN0c0t4HRanFzpXMFIdI385IJAQwQklVT0AWxGAT3DIgPk6OITSTnIKlRV7ZjSRsfq8gqKS4GBh0YBFXmL2GGWAX3fq2pLqxp6+m0OtU8PggVJXKCRCAADQgSrsITIUAjCwAdwACiMEORkCBSMQ0aRlri4dwdKQwA44DBSkV0lBmMgYDpeHA4YYFsQAOr6XDwWpgOClHH8gj85Z4sCUWGKKApUYYinMJbIOLEFJwgBW5AAHgAhClUmmlUgLOAAGXscDVBM1IB1utKx00Twg8FtGvZICKOgVeM5xFlHnsMG5uGwMH0yAAHAAGOEeCApbkUlR4jxwBX4G1wgCOvHdcCVlVxKAonCgcC0WllOjgBYyxeVqqQ6vtKQWuGZrO95BdcDdHrbdu9MFI3HDkejSAATHCWaRcC1mABhCALVsgLMAVllyTgABUJ2X2978GyAJJQbAIWlgPQqGAAQRvpTemk9KU+QA), this is what you want, but not safe, not there is extra space before `<i>`.

**Comment by maxiqboy** [comment]
> Exactly, there is no whitespace, so we have to break in this way. [with --html-whitespace-sensitivity=ignore](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8ATAlgN1TABsBDAZ3IF4AdEKU-XAc1Jl2gFoAjAVxhjRydAHw0oGDDgJEylWiFzlOAB17FicbJwBOLABYxR4yZMw6I-ODs7FcUANapBCgPQqL2XmBjC0JCmo6PgFoUUxcWUCFADNSVDjOXnJrTjBcHRI4cNdcEUxyFVIoEQBlfQgVTFdC4vzXCysbO0cxCVN0c0t4HRanFzpXMFIdI385IJAQwQklVT0AWxGAT3DIgPk6OITSTnIKlRV7ZjSRsfq8gqKS4GBh0YBFXmL2GGWAX3fq2pLqxp6+m0OtU8PggVJXKCRCAADQgSrsITIUAjCwAdwACiMEORkCBSMQ0aRlri4dwdKQwA44DBSkV0lBmMgYDpeHA4YYFsQAOr6XDwWpgOClHH8gj85Z4lhQCA6OCwxRQFKjDEU5hLZBxYgpOEAK3IAA8AEIUqk00qkBZwAAy9nlSC1OpA+oNpWOmieEHgmoJTqKOmVeM5xAVHnsMG5uGwMH0yAAHAAGOEeCApbkUlR4jxwZX4eVwgCOvC9cFVlVxKAonCgcC0WgVcqLGVLao1Dt97JAKQWuGZrM75HdcE93vb2s7MFI3Ej0djSAATHCWaRcC1mABhCALNsgHMAVgVyTgABUpxXHZ38GyAJJQbAIWlgPQqGAAQTvpTemh948+QA), this is what you want, but not safe, note there is extra space before `<i>`.

oh, I just see the space before `<i>` as you pointed.

I got the idea, thank for your help
