### ISSUE TITLE
Weird caret formatting in html template literal

### ISSUE THREAD

**Issue by skeggse** [prettier/prettier#8310]
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbOa0CGA5nJgLyYAWM2ANgAYA6UAPAA4B8zLabBUHAOpxatTAHcIAV1oATAFYFMtCBADWASywxKBLAFpMASRwa0+2gQBGIuLMw7SbAE4bYcZwEJMLDdiKYBLQwZIwggHwbgGS7YZhozmChIFIAjABmAJwATABsAHRsUEQxAPQcLMW8-FysxZzM9ADczCAANCAQbDAa6MigBM7OEOIACv0IaMggQeIEAJ4TbVbOBGBqcDAAynxgbkTIMM5ScG3UdIKUWnjbcBvjWhoAblqzk2D4rSBuaB4ww8tE2AIyFSQW+bXkaAAHgAhZardYbAi4AAybjgwNBxxAEMhG12tDgAEUpBB4BjaGCQHxnN9nJMrNYRB8XG4YIINLIdMhkgAGHltFwQb6CZZsSYuPAeB7otoARxJ8D+HQmKAI5igcDsdg+zjg8o0ur+xEB5Mp32wGn2hyxaHxRIV6KQIIpWJg1nZnMoyEybQOBA0tF2AGEINgTSg8ABWD5Sb4AFWsKudlIeRyMUFkCE2YFcnQAghmNjBZgTTXAAL7loA)
```sh
--parser babel
--print-width 100
```

**Input:**
```jsx
const message = html`
<p>
<span>Well wouldja lookit that - I mis-labeled the printer! <img alt="🤦" src="u1f926.png" /></span>
</p>
`;

```

**Output:**
```jsx
const message = html`
  <p>
    <span
      >Well wouldja lookit that - I mis-labeled the printer! <img alt="🤦" src="u1f926.png"
    /></span>
  </p>
`;

```

**Expected behavior:**
```jsx
const message = html`
  <p>
    <span>
      Well wouldja lookit that - I mis-labeled the printer!
      <img alt="🤦" src="u1f926.png" />
    </span>
  </p>
`;

```

**Comment by skeggse** [comment]
Dupe of #8302, oops!

**Comment by thorn0** [comment]
Not really a dupe. If you need whitespace after `img`, add it manually. Prettier won't do it because it's unsafe.

**Comment by thorn0** [comment]
After adding whitespace and setting `printWidth` to 80, we get the expected result:

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbOa0CGA5nJgLyYAWM2ANgAYA6UAPAA4B8zLabBUHTAHU4tWpgDuEAK60AJgCsCmWhAgBrAJZYYlAlgC0mAJI5NaA7QIAjUXDmZdpNgCdNsOC4CEmFpuxEmAS0MGSMIIB8G4Bku+GYaC5gYSDSAIwAZgCcAEwAbAB0bFBEsQD0giwlvPxcrCWczPQA3MwgADQgEGwwmujIoAQuLhASAAoDCGjIIMESBACek+3WLgRg6nAwAMp8YO5EyDAu0nDt1HRClNp4O3CbE9qaAG7ac1Ng+G0g7mieMCMrRGwBGQaWCP3aCjQAA8AEIrNYbTYEXAAGXccBBYJOIEhUM2e1ocAAitIIPBMbRwSA+C4fi4ptYbKJPq53DAhJo5LpkAAOAAM7VcEB+QhWbCmrjwnkeGPaAEdSfB-p1JigCBYoHB7PZPi44ArNHr-sQgRSqT9sJoDkdsWgCcTFRikKDKdiYDYOVzKMgsu1DgRNLQ9gBhCDYU0oPAAVk+0h+ABUbKqXVTHsdjFA5AgtmA3F0AIKZzYwOaEs1wAC+FaAA)
```sh
--parser babel
```

**Input:**
```jsx
const message = html`
<p>
<span> Well wouldja lookit that - I mis-labeled the printer! <img alt="🤦" src="u1f926.png" /> </span>
</p>
`;

```

**Output:**
```jsx
const message = html`
  <p>
    <span>
      Well wouldja lookit that - I mis-labeled the printer!
      <img alt="🤦" src="u1f926.png" />
    </span>
  </p>
`;

```
