### ISSUE TITLE
Comment in class is not formatted like other nodes

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8313]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgIIA6UA9MTpALYUIxHAC+RRAZgK5RgwCW0O6AFAEocRUuQhUadRlCJdmOfukGiylarGlMoAdwAWXVHCUqSaiRtpQGIADQgIAB27RMyUOgBOniDoAKXghuKOioOugAnm72AEae6GAA1nAwAMqOCVxQAObIMJ6scPZ6MBSoAOoG8JgZYHCpQVzcAG5NEcjg2HYgWZhwnjB+8dkU6MjMoX32AFaYAB4AQvFJKano1AAyWXDjk0Ugs3OpWdlGAIqsEPC7qFMgGZ59nh0x6DFwqN2Onlkw5VwAExgemQAA4AAz2b4QPrleKODrfOBPZo7ewAR0u8CGTmCICwAFooHA4ADSd1PHBMVxKUN0CMxkgJrd9n0KFw8gVWSdzlidky9vYYG9-kCQUgAExC+KGE4AYQsjJAyIArN1WH0ACpvYLMu7NQoASSgZNgqTAP2ceBNqRgESMNz69HoQA)
```sh
--parser babel
```

**Input:**
```jsx
class A
// comment
{}

function a() 
// comment
{}

if (a)
// comment
{}

while(a)
// comment
{}
```

**Output:**
```jsx
class A
// comment
{
}

function a() {
  // comment
}

if (a) {
  // comment
}

while (a) {
  // comment
}

```

**Expected behavior:**
```jsx
class A {
  // comment
}

function a() {
  // comment
}

if (a) {
  // comment
}

while (a) {
  // comment
}

```

**Comment by thorn0** [comment]
But is the current behavior in the non-class cases intended or accidental?

**Comment by fisker** [comment]
`Try/Import` similar, `For` is not

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBPAOlA9LyAW0IRh2AF8ccBLQgBwjRgAId8WiTY2pgBDCiwBmaCIRYByfpOpRhTABQBuZQEocLFvi6lNLYPq399VKCAA0ICPRg1oAZ2Sh+aMQHcACq4ROU-ABt3fgwnKwAjNH4wAGs4GABlemiaKABzZHQAVzgrAAsYQgCAdTyaeAdksDgE33KaADdyjGRwBzCQVIc4Zk8otMJ+ZGFA7qsAKwcADwAhKNj4hP4SABlUuGHR3JBJqYTUtIC4AEUsiHhNgLGQZLRutFbw-nC4AMsbtFSYYpoAExg8sgABwABis9DE3WKUXorQhcHuDQ2VgAjmd4H0bH4QPwHABaKBwOC-YnvNBwNE0cl9fgDIZIEZXbbdQg0TJoHJWBwHI6nc4bBlbKwwZ4-f6ApAAJmFURoAQOAGFxINWgiAKzvLLdAAqzz8jOuDRyAEkoCTYAkwJ9bABBM0JGAYI6XboUChAA)
```sh
--parser babel
```

**Input:**
```jsx
try
//comment
{}

import 
// comment 
{a} from 'a'

for(;;)
  //comment
  {
    a
  }

```

**Output:**
```jsx
try {
  //comment
}

import {
  // comment
  a,
} from "a";

for (;;) //comment
{
  a;
}

```
