### ISSUE TITLE
Removal of backslashes in json schema validation

### ISSUE THREAD

**Issue by foxMclion** [prettier/prettier#8317]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQCsDO02AvNsADpTbbkiZwDmcAHrUjSOeQEYDaXAdwB0AQgDEAEgCkAMkCYBACoA1FwD0xAPwA9AAbAAPgF8AfgFoAukoAC-cgItKAFBqRcht+5YCUCrt1qUhiAANCAQAA4wAJbQ+MigWJgQAgAKWAhxKOgANgLoAJ5xodyY6GAA1nAwAMrhZVFQDMgwmACucKEAFjAAttkA6p1R8Ph1YHDVGcNRqMP5yOD4RSAN+HCYMCmlDD3oyABmOWuhBMwAQqUVVdXoPXAAMg1wB0cdIKfVDQzZcACKrRB4C9sscQHVMGtMAtuOhuHBsiEwZgGjB+lEACYwTrIAAcAAZQuEkmt+qVwgsiXBIahnqEAI4A+BbCKZEDofCmKBwODonmI+gMqL0LboHZ7JCHEFvNY9KLNNrSr4-f6A54S16hGCwtGY7FIABMmtKUWyXwAwhAersFlSAKyI1prAAqsMyktBqHaAEkoLzYNUwMjIgBBX3VGD5H7AtaGQxAA)
```sh
--parser babel
```

**Input:**
```jsx
var json = {
  "regex": "\b[\w.!#$%&’*+\/=?^`{|}~-]+@[\w-]+(?:\.[\w-]+)*\b"
}
```

**Output:**
```jsx
var json = {
  regex: "\b[w.!#$%&’*+/=?^`{|}~-]+@[w-]+(?:.[w-]+)*\b",
};

```

**Expected behavior:**

I'm trying to use json-schema to define a validating object. I expect the `\w` to remain as-is. I've read the other issue where the offered solution is to use double backslashes, but if I do that it will result in a literal `\` and I don't want that. The tested pattern is compatible with an email format standard.

**Comment by thorn0** [comment]
Works as expected. In JS, `"\w"` and `"w"` are the same string (of length 1). Prettier just removes the unneeded backslash.

**Comment by fisker** [comment]
@thorn0 [Is this expected?](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAXnQAwDp4DuBAdPlBtgOQHF4lUgA0IEADjAJbQDOyoqAE6CIhAApCEfFKgA2hVAE8+LAEaDUYANZwYAZTabOUAObIYggK5wWACxgBbWQHVbneD0Ng4eqe84Abu6KyOA8KiDGPHCCMGIaJg6oyABmctEsAFY8AB4AQhraunqoDnAAMsZwqek2INk5esYmsnAAipYQ8DWyGSCGgtGCoaqoqnCyzP2CxjDOnAAmMLbIABwADCxsItHOGmyh23BDAdUsAI6d8PHs0mg8ALRQcHALr1OCcJecn-GoickkGlenVog5OOYrKDmq0Ol1qkDaiwYGN5ksVkgAEzIjScWTNADCEAcSVCxwArFNLNEACpjaTAvoBawASSgb1gejAMw4AEF2XoYIpWj1ogBfMVAA)

**Comment by thorn0** [comment]
yep

**Comment by foxMclion** [comment]
solved with

>  \\\b[\\\w.!#$%&’*+\\/=?^`{|}~-]+@[\\\w-]+(?:\\\\.[\\\w-]+)*\\\b

which turns into

> \\\b[\\\w.!#$%&’*+\/=?^`{|}~-]+@[\\\w-]+(?:\\\\.[\\\w-]+)*\\\b

**Comment by thorn0** [comment]
@fisker I'm not sure about template literals. Need to investigate.
