### ISSUE TITLE
Space added between function and parens

### ISSUE THREAD

**Issue by speed-e** [prettier/prettier#8318]
**Config:**
```js
module.exports = {
  extends: ['standard', 'prettier', 'plugin:security/recommended'],
  plugins: ['prettier'],
  rules: {
    'comma-dangle': ['error', 'never'],
    'guard-for-in': 'error',
    'no-var': 'error',
    semi: ['error', 'always'],
    'no-extra-semi': 'error',
    'no-unused-vars': 'error',
    'no-duplicate-imports': 'error',
    'space-before-function-paren': ['error', 'never'],
    'prettier/prettier': [
      'error',
      {
        singleQuote: true,
        trailingComma: 'none',
        parenthesisSpace: false
      }
    ],
    'standard/computed-property-even-spacing': 'off'
  },
  parser: 'babel-eslint',
  globals: {
    assert: false,
    browser: false,
    expect: false
  }
};
```
**Input:**

```jsx
window.setAnalyticsVariables = function() {}
```

**Output:**

```jsx
window.setAnalyticsVariables = function () {}
```

**Expected behavior:**
```jsx
window.setAnalyticsVariables = function() {}
```

Since upgrading to prettier v2.0.5 from v1.19.1 I have been getting a space added between function and parenthesis. I thought that adding this line `'space-before-function-paren': ['error', 'never']` or `parenthesisSpace: false` in to the config should disable this, but I still get an error: `error  Insert `·`  prettier/prettier`. Is there a way to diable this behaviour please?

**Comment by thorn0** [comment]
No, there is no way to disable it. Please use search when opening issues.

**Comment by speed-e** [comment]
Oh I apologise, I was looking at release notes but couldn't see this information. Thanks a lot!

**Comment by luzik** [comment]
I am in eslint<->prettier fixing loop
when I fix code for eslint it breaks for prettier
'space-before-function-paren': ['warn', 'never']

I just wanted to +1 for adding this as option, as an "great demand" issue of "Option Philosophy"

**Comment by thorn0** [comment]
@luzik If you want to use ESLint with Prettier, you have to disable all ESLint's formatting-related rules. Please read more here https://prettier.io/docs/en/integrating-with-linters.html
