### ISSUE TITLE
return outside of functions

### ISSUE THREAD

**Issue by ooflorent** [prettier/prettier#832]
Given:

```js
// https://github.com/observing/pre-commit/blob/master/install.js#27
if (!exists(git) || !fs.lstatSync(git).isDirectory()) return;
```

I got a parse error:

```
SyntaxError: 'return' outside of function (1:54)
> 1 | if (!exists(git) || !fs.lstatSync(git).isDirectory()) return;
    |                                                       ^
```

This is because `return` is allowed within node modules but the parser does not like it.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22return%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by escaton** [comment]
This is [babylon](https://github.com/babel/babylon) issue, not prettier.

**Comment by ooflorent** [comment]
@escaton  Actually no. It is a configuration issue (see [parser.js#L40](https://github.com/prettier/prettier/blob/4540f473e9e099ca61090c4fb1fc2bb4faad43d4/src/parser.js#L40)).

**Comment by escaton** [comment]
Oops, sorry.

**Comment by jlongster** [comment]
Pinging @hzoo for some JS spec advice. Is this a new feature of JS, and is allowed within ES6 modules? I had no idea.

**Comment by hzoo** [comment]
It's not a feature in JS (not ES module compliant); it only works in node because every module puts the whole file in a wrapper function as part of being a node module, thus you can use "return".

Example:

![screen shot 2017-02-28 at 10 52 33 am](https://cloud.githubusercontent.com/assets/588473/23412605/0e1adacc-fda4-11e6-92a6-24a822dc1bdf.png)

**Comment by jlongster** [comment]
It seems like we shouldn't allow then. We want to encourage only spec-compliant code and this is a very strange node feature.

**Comment by jlongster** [comment]
Thanks @hzoo!

**Comment by vjeux** [comment]
Since we're unlikely going to implement this, I'm going to close this issue.

**Comment by escaton** [comment]
@vjeux can you explain why `prettier` as consumer of `babylon` shouldn't support this explicitly exposed feature and thus limit `prettier` usage while it costs so few?

**Comment by vjeux** [comment]
I'll defer to @jlongster. Flow parser doesn't support this option fwiw.

**Comment by escaton** [comment]
this is another question, why need to support two parsers that give different output?
