### ISSUE TITLE
bool is rewritten to boolean 

### ISSUE THREAD

**Issue by preynal** [prettier/prettier#8320]
Prettier converts all my `bool` types to `boolean`, it doesn't seem configurable from the docs.
Is there any way to stop prettier from doing this ?

See a playground example here:
[https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDJmBGEEANpgLyYBm2xacIANCBAA4wCW6yo2ATrxADuABT4I0yEDUHYAnhKb5e2MAGs4MAMosV7KAHNkMXgFc4TABYwAtsQDqF9vDQ6wcTeKfsAbk9mSwNAUQPTpeGGFlfWtsZGpacxAAKzQADwAhZTUNTWxrOAAZPXokeLomFNTNPX1iOABFEwh4OJpykB1eMMl8bHw4YkYO3j0YO3YAExgLZAAOAAYmFgE6O2UWSWW4MO96JgBHJvhI1gkUbDQAWig4OAm7od44Q-YnyOxo2NK2xLprdiMpl+NTqjWaJTKiRgfXGUxmSAATExjNh2MQagBhCDWGKSbYAViGJjoABU+mdIUxvGYAJJQe6wTRgEZsACC9M0MFkdVaCQAvnygA](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDJmBGEEANpgLyYBm2xacIANCBAA4wCW6yo2ATrxADuABT4I0yEDUHYAnhKb5e2MAGs4MAMosV7KAHNkMXgFc4TABYwAtsQDqF9vDQ6wcTeKfsAbk9mSwNAUQPTpeGGFlfWtsZGpacxAAKzQADwAhZTUNTWxrOAAZPXokeLomFNTNPX1iOABFEwh4OJpykB1eMMl8bHw4YkYO3j0YO3YAExgLZAAOAAYmFgE6O2UWSWW4MO96JgBHJvhI1gkUbDQAWig4OAm7od44Q-YnyOxo2NK2xLprdiMpl+NTqjWaJTKiRgfXGUxmSAATExjNh2MQagBhCDWGKSbYAViGJjoABU+mdIUxvGYAJJQe6wTRgEZsACC9M0MFkdVaCQAvnygA)

**Comment by thorn0** [comment]
Why do you need that? `bool` is a legacy synonym for `boolean` in Flow, these keywords have the same meaning.
