### ISSUE TITLE
Missing newline after import

### ISSUE THREAD

**Issue by pikeas** [prettier/prettier#8321]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgDEIJ8AzHCdfAHRADoyS6ao4APbPfAEzjICGAVwA2BMkKhgYqaORIAKAJT5gAX1YgANCAiYZ0AM7JQAnJQDuABTMJjKASIsCAnsZ0AjHALABrODAAypg+qFAA5sgwOEJwOgAWMOgiAOrxqPCGIWBwgXYZqABuGS7I4IbuaFCGcHhW3uHoAsiCIjU6AFaG7ABC3n4BgQLocAAyYXAtju0gXeyBYeEicACKQhDwU21xICE4NThlHgIecCLauzhhMCmoPDDxyAAcAAw6mJQ1Kd6YZR9wB0Kkx0AEd1vB6np7CABIYALRsOB8HgXHBwMGoNH1ASNZpIVozGroVBRGI7QyLZZrDaTfHTHYwE63e6PJAAJh00QEqBEiwAwlQmmUAQBWC5CGoAFRO9gJO0KsQAklA+LBAmArvoAIIqwIwFzLLY1NRqIA)
```sh
--parser babel
```

**Input:**
```jsx
import Foo from "./foo"
export default function foo() {}

```

**Output:**
```jsx
import Foo from "./foo";
export default function foo() {}

```

**Expected behavior:**
```jsx
import Foo from "./foo";

export default function foo() {}

```

Output is as expected when you have too many newlines:

```jsx
import Foo from "./foo"



export default function foo() {}

```

```jsx
import Foo from "./foo";

export default function foo() {}

```

**Comment by thorn0** [comment]
This is expected. Prettier doesn't insert empty lines automatically. Please see https://prettier.io/docs/en/rationale.html#empty-lines
