### ISSUE TITLE
Constantly changing comments when formatting.

### ISSUE THREAD

**Issue by daidodo** [prettier/prettier#8323]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwFkBDTANVTgHcAFHCTAZ3wF98AzR9fAchxxSYGAFoopGKgBucUenLM+AbnwB6AFQAdKJHToEBAIwAWfDo1r1G-HoOwjOowAYLVzVbuH8RgMz5LHU0dWwh9bwBOEI0YwKgMbDwA-FJWGFZuMP4YAE9MOGYwHFRMGBUQABoQJiloZmRQUhxGeiaEepRSABsaUhz6qoAjHGEAazgYAGVMYVQoAHNkGBwAVzgqgAsYdC6AdQ3UeGYZsDhJ9sOZQ5zkcGYBtChmODwGUnmFZE5u56qAK2YAA8AEIjMDjKakAwAGTmcC+P3WIABgMmc3mXTgAEUVhB4Aiur8QDMcM8cLdBqRBnAupVicVYLtUAATGAbZAADmcVUwjGeuxGmFuvIKL1kdIAjrj4AwmB0QKlxHA4MyVXTBFLUII3h9SASic90Kglqskcx0ZicXj4UhvoSkTAqUzWeykAAmKrLUioLrogDCYU+KAKAFY6StngAVKkdO1E6RrACSUFVsEmRRKMAAginJrlMfq4Gw2EA)
```sh
--parser babel
```

**Input 1:**
```jsx
import { MapViewProps } from 'react-native-maps'; /*
comment 14 
*/ /* comment1
10
*/ /*/ comment 13 */
/*
 comment 9
 ****/
import * as ts from 'typescript';
```

**Output 1:**
```jsx
import { MapViewProps } from "react-native-maps"; /*/ comment 13 */ /*
comment 14 
*/ /* comment1
10
*/
/*
 comment 9
 ****/
import * as ts from "typescript";

```

**Input 2:**
```jsx
import { MapViewProps } from "react-native-maps"; /*/ comment 13 */ /*
comment 14 
*/ /* comment1
10
*/
/*
 comment 9
 ****/
import * as ts from "typescript";

```

**Output 2:**
```jsx
import { MapViewProps } from 'react-native-maps'; /*
comment 14 
*/ /* comment1
10
*/ /*/ comment 13 */
/*
 comment 9
 ****/
import * as ts from 'typescript';
```

**Expected behavior:**
The outputs should be the same as inputs.

**Comment by daidodo** [comment]
Originally reported in https://github.com/prettier/prettier-vscode/issues/1365.

**Comment by thorn0** [comment]
A simplified reproduce:

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPA3AAgPQCpMA6UAjJrtjvgExnZFECeIANCBAA4wCW0AzsqACGAJ2EQA7gAURCfikEAbcYIb9WAI2GCwAazgwAyu21coAc2QxhAVzisAFjAC2CgOr2u8XsbBwDszy4AN08mFDBeNRBTXjhhGEktMydBZAAzRVjWACteVAAhLV19A0EnOAAZUzh0zLsQXNQDUzMFOABFawh4WoUskGNhWOFkEHVBdTgFFgHhUxhXLgATGHtkAA4ABlZ2MVjXLXZR3bhhoJrWAEcu+ESOORBBXgBaKDg4JY+Z4Thrrh-EoJkqkkBk+vVYk4uJYbBCWm1Ot0aqC6qwYBNFis1kgqGitFwFC0AMIQJwpUanACsM2ssQAKhM5GD+kFbABJKCfWAGMBzTgAQU5BhgDDavViAF8JUA)
```sh
--parser babel
```

**Input:**
```jsx
x; /* 
1 */ /* 2 */

y
```

**Output:**
```jsx
x; /* 2 */ /* 
1 */

y;

```

**Second Output:**
```jsx
x; /* 
1 */ /* 2 */

y;

```

**Comment by boyenn** [comment]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPA3AAgPQCoCMu2eATEQDpQCe6IANCBAA4wCW0AzsqAIYBOfCAHcACvwRcUPADZCeVLgwBGfHmADWcGAGUma1lADmyGHwCucBgAsYAW2kB1K63gc9YONokvWANxdUyOAciiAGHHB8MCKqhrY8yABmMhEMAFYcqABCqhpa2jy2cAAyBnBJKZYgGajaBobScACKZhDwFdKpIHp8EXxBSjxKcNL03XwGMA6sACYwVsgAHAAMDEyCEQ6qTEHrcH2+5QwAjq3wMcySIDwcALRQcHAzT2N8cKesbzE8cQlIyZ0qhFbKwTOYgfVGi02uV-pUGDAhtM5gskCQEapWNJ6gBhCC2eJBfYAVjGZgiABUhpIAV1fBYAJJQZ6wbRgCYsACCzO0MCojQ6EQAvkKgA)
```sh
--parser babel
```

**Input:**
```jsx
x; /*1*//*2*/
y;
```

**Output:**
```jsx
x; /*2*/ /*1*/
y;

```

**Second Output:**
```jsx
x; /*1*/ /*2*/
y;

```

Even more simplified ^
