### ISSUE TITLE
Inconsistent JSON formatting

### ISSUE THREAD

**Issue by Quitch** [prettier/prettier#8324]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6IAOAbAhjCaAfXgFsd84BnDJdEAeQCcAjASxl2yIDE2BzABbwmRAIIxOYANa16AVygcayANoKlMEgE9M1WhmbtO2AAQAyU3yEiMAGgyk2UIpEUxaARgchSuAB6uEO60ALSeAL4AuhGxIHYgEJgwbNBUyKC4TEwQAO4AClkI6Shcubja6QksTLgycDAAyph1zvzIMEzycAnCpNgA6oIc1C1gcI3FHGwAbhzayOBUVSDOVHBMMPm1-H7IAGZc6wkAVlT+AEK19U24pHAAMs5wB0c9IGf+jW3YcACK8gg8Fe2GOWCy6yYizO0HiWCYzhgAzYABMYIJkAAOAAMCUwOXWA1qmEW+OoGxmLwSAEdAfBtkkSiBcFRQlA4HAUZy4Uw4LS2LztrhdrgQWD1k4Ol13lQfv86S8kIdQe9OCxkWiMUgAEwJTq4NjYNoAYQgpD2KGoAFY4fJ1gAVXAsErKsEzboASSgXNgjTACOSYm9jRg2l+YrgsSAA)
```sh
--parser json
```

**Input:**
```jsonc
{"platoon_templates":{"Orbital_Fighter_Attack":{"units":[{"unit_types":"Orbital & Fighter","min_count":1,"max_count":-1}]}}}
```

**Output:**
```jsonc
{
  "platoon_templates": {
    "Orbital_Fighter_Attack": {
      "units": [
        { "unit_types": "Orbital & Fighter", "min_count": 1, "max_count": -1 }
      ]
    }
  }
}

```

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm0gA4A2AhjBNAPrwC2hJcAzrkpultjiAPIBOARgJYwiBcgDF+AcwAW8buQCCMIWADWTFhnbtcAVyiDGyTAG1NW9q3Pnd+mJQCeeButw8BQgpgBkmcdNm4ADRmVti4VPxQ5JB6MOoAjMFsoRxURAAe0RCx6gC08SHmAL6F2AC6hSVsVUUggSAQeDD80PTIoETc3BAA7gAKnQhtKMI9RPZt9bzcRKpwMADKeLOREsgw3Dpw9TJUBADqUoIMy2BwC0OC-ABugvbI4PSTIJH0cNwwfTMSacgAZsI3vUAFb0dIAIRmc0WRCocAAMpE4P9AdsQKD0gtVgQ4ABFHQQeAoghA-CdN7cB6g6B1fDcSIwfb8AAmMCkyAAHAAGep4bpvfYzPAPPkMd7XZH1ACOBPgX0awxARHouSgcDgzI1tO4cBl-B1XyIPyIxNJbwi602aPo2LxsuRSABJLRQl4TNZ7KQACZ6hsiPwCKsAMIQKi-FAMACstJ0bwAKkReMMnaTrlsAJJQTWwBZgelNeRZhYwew401wIpFIA)
```sh
--parser json
```

**Input:**
```jsonc
{
  "platoon_templates": {
    "Orbital_Fighter_Attack": {
      "units": [
        {
          "unit_types": "Orbital & Fighter",
          "min_count": 1,
          "max_count": -1
        }
      ]
    }
  }
}
```

**Output:**
```jsonc
{
  "platoon_templates": {
    "Orbital_Fighter_Attack": {
      "units": [
        {
          "unit_types": "Orbital & Fighter",
          "min_count": 1,
          "max_count": -1
        }
      ]
    }
  }
}

```

**Expected behavior:**
Prettier should format the JSON the same way in both instances.

**Comment by thorn0** [comment]
This behavior is expected and documented.
Please see https://prettier.io/docs/en/rationale.html#multi-line-objects

However, for JSON you can use `--parser json-stringify` to get the results you want.
