### ISSUE TITLE
Cannot format files opened via ssh server

### ISSUE THREAD

**Issue by efreibe** [prettier/prettier#8328]
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: VS Code Latest Version
- Runtime: n/a
- Operating System: macOS

**Steps to reproduce:**
Download "[Remote Workspace](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-remote-workspace)" extension.
Connect to any ssh and edit a javascript file.
Go to "Format Document" and execute it.

**Expected behavior:**
Document is formatted.

**Actual behavior:**
There is no formatter for 'javascript' files installed.

---------

Hello, I'm using "Remote Workspace" extension for editing files via SSH. 

I can load, view, edit and save the file in vscode.

When I try to format any local file it works well and formats the document.
But if I edit the remote file and I click in "Format Document" the error shows.

I do not know about vscode internals, so I don't understand why these files aren't formatted, are plain javascript files and the only difference is that they were loaded from an ssh connection.

I'm referencing the issue in "Remote Workspace": https://github.com/mkloubert/vscode-remote-workspace/issues/2

**Comment by thorn0** [comment]
Hi, thanks for the report!

This repository is only concerned with the core formatting tool and not the editor integrations. Unfortunately, there's not much we can do to help you in this case. I suggest you open a report on the extension's issue tracker: https://github.com/prettier/prettier-vscode
