### ISSUE TITLE
Getting error "Cannot find module 'prettier/parser-babylon'" when executing through a pre commit hook in Prettier 2

### ISSUE THREAD

**Issue by arpit73** [prettier/prettier#8329]
I setup Prettier 1.9 to work as part of a pre commit hook via `husky` and `lint-staged` and that setup ran fine, after upgrading to Prettier 2

**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: Cli via pre commit hook
- Runtime:12.9.1
- Operating System: Linux

**Steps to reproduce:**
- Setup a pre commit hook in `package.json`
    setup - 
```json
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "./**/*.{ts,tsx,json}": [
      "prettier --write --config ./.prettierrc --ignore-path ./.gitignore"
    ]
  }
```

- Run git commit

**Expected behavior:**
Prettier formats after being called as a pre commit hook.

**Actual behavior:**
Gives this error - 

```sh
husky > pre-commit (node v12.9.1)
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for ./**/*.{ts,tsx,json}
    ✖ prettier --write --config ./.prettierrc --ignore-path ./.gitignore [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up... 

✖ prettier --write --config ./.prettierrc --ignore-path ./.gitignore:
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'prettier/parser-babylon'
Require stack:
- /home/arpit/Development/amoli-sessions/node_modules/prettier-plugin-import-sort/src/index.js
- /home/arpit/Development/amoli-sessions/node_modules/prettier/bin-prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/arpit/Development/amoli-sessions/node_modules/prettier-plugin-import-sort/src/index.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/arpit/Development/amoli-sessions/node_modules/prettier-plugin-import-sort/src/index.js',
    '/home/arpit/Development/amoli-sessions/node_modules/prettier/bin-prettier.js'
  ]
}
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by thorn0** [comment]
You didn't show your configuration file `.prettierrc`, but looks like you use the deprecated `babylon` option value in it. Please see the [version 2.0 release notes](https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot).

**Comment by arpit73** [comment]
Ohh here's my `.prettierrc` 
```json
{
    "semi": false,
    "tabWidth": 2,
    "printWidth": 99,
    "singleQuote": true,
    "arrowParens": "always",
    "trailingComma": "none",
    "jsxBracketSameLine": true
}
```

**Comment by arpit73** [comment]
I tried again by removing the `.prettierrc` file completely and just used the ``` "prettier --write"``` in my pre commit hook. But the issue persists.

**Comment by fisker** [comment]
I think  you need  upgrade `prettier-plugin-import-sort`

**Comment by arpit73** [comment]
Fixed!  that was the issue, `prettier-plugin-import-sort` does not support Prettier 2 it seems.
