### ISSUE TITLE
Prettier passed on Mac and Linux but fails on Windows

### ISSUE THREAD

**Issue by staticdev** [prettier/prettier#8330]
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: pre-commit hook
- Runtime: hook
- Operating System: Windows

**Steps to reproduce:**

My YAML and JSON files were created on Linux. I created a pipeline that runs on Linux, Windows and MacOS: https://github.com/staticdev/toml-validator/pull/37/checks?check_run_id=683256615

**Expected behavior:**: pass on all operating systems.

**Actual behavior:** fails on Windows.

**Comment by kachkaev** [comment]
👋 @staticdev, here is the likely cause: https://prettier.io/docs/en/options.html#end-of-line

Probably the issue is in your repo setup rather than in Prettier

**Comment by staticdev** [comment]
@kachkaev @thorn0 I didn't quite understand what more I need to change. I added the .gitattributes and nothing changed.

**Comment by staticdev** [comment]
Sorry, it worked!
