### ISSUE TITLE
Parenthesized non-null assertion in an optional chain

### ISSUE THREAD

**Issue by bradzacher** [prettier/prettier#8339]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAHgfgHQE8CUAhNgF4gA0IEADjAJbQDOyoAhgE7sQDuAChwmYpWAG26tczSgCN2rMAGs4MAMrV5dKAHNkMdgFc4lABYwAtiIDqxuvEbqwcFYNt0AbrdzJwjKSE2McOwwvHJaZqzIAGaigZQAVozoAEJyisoqrGZwADKacNGxRiCJ6CqaWiJwAIr6EPCFInEg6uyB7N4wuNRwjGDsdLQULQOwlnQAJjDGyAAcAAyU1FyBlnLU3su9QW4FlACOdfChNEIgrIwAtFBwcBN3w+xwh3RPoazhkUgxTcWBZnRdAY-hUqrV6gVvkVKDBWNJxlMZkgAEwwuR0EQVADCEDMEW8vQArMN9IEACpwoQ-ZpuQwASSg91gKn6gxgAEFGSoulVGoEAL78oA)

```sh
# Options (if any):
--parser=typescript
```

**Input:**

```jsx
(x?.y)!.z
```

**Output:**

```jsx
x?.y!.z;
```

**Expected behavior:**

```jsx
(x?.y)!.z
```

---

As of [TS 3.9](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#breaking-changes), `x?.y!.z` no longer means `(x?.y).z`.
Instead, the `!` is applied solely to the type of the property `y`, preserving the optionality of the chain (i.e. `x?.y!.z` is the same as `x?.y.z`, and `(x?.y)!.z` is the same as `(x?.y).z`).

This means that now automatically removing the parentheses in this case is wrong, and changes the meaning of the code.

**Comment by sosukesuzuki** [comment]
note: we should wait https://github.com/typescript-eslint/typescript-eslint/pull/2036

**Comment by sosukesuzuki** [comment]
We also need to wait https://github.com/typescript-eslint/typescript-eslint/pull/2057 to avoid warning.

**Comment by bradzacher** [comment]
typescript-eslint/typescript-eslint#2057 will be released on monday morning :)
