### ISSUE TITLE
A comment between 'if' and 'else' statement causes formatting error

### ISSUE THREAD

**Issue by daleroy** [prettier/prettier#834]
Input source code:

```js
if (true) {
  console.log("foo");
}
// Comment in between if and  else
else {
  console.log("bar");
}
```

Formatted code:
```js
if (true) {
  console.log("foo");
}
// Comment in between if and  else else {
  console.log("bar");
}
```

**Comment by vjeux** [comment]
Can you upgrade your version of prettier, we've fixed that issue a few weeks ago.

It now outputs

```js
if (true) {
  console.log("foo");
} else {
  // Comment in between if and  else
  console.log("bar");
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22if%20(true)%20%7B%5Cn%20%20console.log(%5C%22foo%5C%22)%3B%5Cn%7D%5Cn%2F%2F%20Comment%20in%20between%20if%20and%20%20else%5Cnelse%20%7B%5Cn%20%20console.log(%5C%22bar%5C%22)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by daleroy** [comment]
Yes, that fixed it. Thanks!
