### ISSUE TITLE
Wrapping extends/implement clauses for class make declaration ugly

### ISSUE THREAD

**Issue by DullReferenceException** [prettier/prettier#8340]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgOoQBOA1qhOgCYCKArnHQJIC2ADqgDwCyc26A5nAB8AHSg4ccAB7woFXAFEAbghjymASxjxCo8etao4TFbgIkylWvThcemfkJyjgu8ThaF1i9PBwAzCAgkHEwYTyg+AG5RAF9REAAaEAgWGHVoTGRQdEJCCAB3AAUchEyUdFR89ABPTKSAI0J0MGI4GABlFmb1COQwuiSACxgmVDxBzR4usDh20s0vTWrkcGxEkB7MOEIYQqa+JnRkPwqtpIArTEkAISaWtvb0YwAZHrhj07gLq-aevkNaBB4B9UGcQF1CFtCCsYNUWDwwJ5UusPD0YHh1BQYINkAAOAAMSQ8EC2eCaLBWHh422U6wAjjQgXA9ikyiAsABaKBwOAUXnrQhwBnqQV7fiHEFgrYaPqEAYgTB-AGM4FIE6gr4gGDoeoYrE4pAAJiSYXQ6lQfwAwhAmBKUDwAKzrGhbAAqOrK6rBikYshU7UR6lSAEFZO1YYZJXAYjEgA)

**Input:**

```ts
class WorkloadQueueImpl<Message>
  extends EventEmitter
  implements WorkloadQueue<Message>
{
  private foo: string;
}
```

**Output:**

```ts
class WorkloadQueueImpl<Message> extends EventEmitter
  implements WorkloadQueue<Message> {
  private foo: string;
}
```

**Expected behavior:**

The way things are currently formatted, the `implements` or `extends` clause is indented at the same level as class members. It might be cleaner if the opening brace appears on its own new line in the case where the "predicates" wrap to multiple lines. For if/for statements it's pretty straightforward:

```js
if (
  longconditiona &&
  longconditionb &&
  longconditionc &&
  longconditiond &&
  longconditione
) {
}
```

Perhaps for classes:

```ts
class WorkloadQueueImpl<Message>
  extends EventEmitter
  implements WorkloadQueue<Message>
{
  private foo: string;
}
```

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/issues/5156?

**Comment by sosukesuzuki** [comment]
I think this is not duplicated with #5156. This mentions about mixed `extends` and `implements` formatting.

**Comment by evilebottnawi** [comment]
@sosukesuzuki I think we should use same logic for `implements`

**Comment by sosukesuzuki** [comment]
@evilebottnawi I agree. But #5156 mentions only using `extends`.  I think this issue says how to format codes when class has both `extends` and `implements`.
