### ISSUE TITLE
Options for closing bracket position

### ISSUE THREAD

**Issue by calvindio** [prettier/prettier#8343]
For me, there are 3 logical possible places to put the closing bracket
# 1. The Most Common
```sql
create table A (
   id serial primary key,
   title varchar(50) not null
);
create table B (
   id serial primary key,
   title varchar(50) not null
);
create table C (
   id serial primary key,
   title varchar(50) not null
);
```
```js
const A = {
   name: "John Doe",
   age: 30,
};
const B = {
   name: "John Doe",
   age: 30,
};
const C = {
   name: "John Doe",
   age: 30,
};
```
pros
   - easy to read the last line in block
   - easy to add new line into the last line in block  

cons
   - more cluttered on the left side because of the > or nested like strucutre
     - ie, instead of seeing 3 start of lines, we see 6
# 2. The Condensed
```sql
create table A (
   id serial primary key,
   title varchar(50) not null);
create table B (
   id serial primary key,
   title varchar(50) not null);
create table C (
   id serial primary key,
   title varchar(50) not null);
```
```js
const A = {
   name: "John Doe",
   age: 30,};
const B = {
   name: "John Doe",
   age: 30,};
const C = {
   name: "John Doe",
   age: 30,};
```
pros
   - shorter
   - clearer on the left side (that there are 3 blocks: A, B, and C)  

cons
   - harder to read the last line of each block
   - harder to add new line to the last line of each block
# 3. My Personal Favorite (hybrid?)
```sql
create table A (
   id serial primary key,
   title varchar(50) not null
   );
create table B (
   id serial primary key,
   title varchar(50) not null
   );
create table C (
   id serial primary key,
   title varchar(50) not null
   );
```
```js
const A = {
   name: "John Doe",
   age: 30,
   };
const B = {
   name: "John Doe",
   age: 30,
   };
const C = {
   name: "John Doe",
   age: 30,
   };
```
pros
   - less clutter on the left side (that there are 3 blocks: A, B, and C)
   - easy to read the last line of each block
   - easy to add a new line to the end of each block  

cons
   - longer than the condensed style

I know this is adding an option and prettier is supposed to be opinionated. I'm okay with what option is the default or what other people use. Personally, I really prefer the style no. 3 (I hate clutter).  

Right now, I even turn off prettier for sql because I can't stand the clutter. I still use prettier on js, ts, etc. because the format-on-save feature is better than the pain of closing brackets cluttering the left side of the blocks.

If it is not possible to add the option because of the philosophy, do you know any other 'format on save' extension on vscode where I can use style no.3?

**Comment by kachkaev** [comment]
👋 @calvindio! Your guess about the [option philosophy](https://prettier.io/docs/en/option-philosophy.html) is right – it’s unlikely that what you are suggesting will become configurable in Prettier.

Try postponing your search for a solution for, say, 3-4 weeks and force yourself into using standard formatting as an experiment. You’ll be surprised that after a few days your frustration is gone away and you no longer mind the ‘wrong’ location of brackets 🙂 As a bonus, it will be easier for your to navigate someone else’s codebases and configure new projects for yourself.

**Comment by calvindio** [comment]
@kachkaev thank you for the quick response.

I am still itching for the solution tho. I may be in the minority here, but I am sure that in our diverse world, there are more than a few programmers who prefer this style too, however minor their percentage are. I hope I can find them and find the way the solve this itch.

I know and respect that it is the right of the project owner to decide which feature is good and which will only add confusion to its target user.

If you are part of that minority who's reading this from the future and have found the solution, please contact me. If I found the solution, I will post it in my github page.

@kachkaev do you want me to close this issue? (I'm a newbie and not very sure about the etiquettes here)

**Comment by thorn0** [comment]
Things like this are intentionally non-configurable in Prettier. That's what the word "opinionated" means in "an opinionated code formatter".

You might be able to run ESLint (with autofix enabled) after Prettier to accomplish what you want, but I'm not sure if a rule for what you want exists.
