### ISSUE TITLE
Vue: Support X-Template style DOM template

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#8344]
from https://github.com/prettier/prettier/pull/8153#issuecomment-628082830
ref: [stackoverflow](https://stackoverflow.com/questions/61742084/is-it-possible-to-configure-prettier-to-treat-text-within-a-script-tag-as-html), [Vue official document](https://vuejs.org/v2/guide/components-edge-cases.html#X-Templates)

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wAEMAnnnALwA6I8AHjAPR0C08AtngDYCG8NAPipRChVDnYBzQuixhqIAK5YuNYaNFIAZhAgKARjyyEKpjeY2GAXjUKMhUVI0y4CDkABoQEAjmjpkUCMsCAB3AAUjBACUHi5QnhIAr30sHjAAazgYAGU8dJwoSWQYLEU4LwALGHYuAHVKnHh0fLA4HOimnAA3JpJkcHRkkEL0OCwYcLTJdh5kLTixrwArdDoAITTM7JyedjgAGUK4ecWKkFW6HMLJLjgARUUIeFOuJZB8rDGsAe7yzw+uFgdRwABMYJVkAAOAAMXjwITGdTSeAGCLg326Jy8AEcnvApj4YiAeOgWFA4HBQVSAVg4HicHSpjwZnNtGcvGN2DgSmVzugbndHs8Tuy3ucYDx9CDwZCkAAmLylHg4Lg3ADCEHYswGGIArADFGMACpSmILcVeP5wACSUGpsBy2HwMAAgvacqQ7q8xgBfX1AA)
```sh
--parser vue
```

**Input:**
```vue
<script type="text/x-template">
  <img src="url"
    :foo="bar ===          baz" />
</script>

```

**Output:**
```vue
<script type="text/x-template">
<img src="url"
  :foo="bar ===          baz" />
</script>

```

**Expected behavior:**
```vue
<script type="text/x-template">
  <img src="url" :foo="bar === baz" />
</script>

```

**Comment by fisker** [comment]
I really don't think we can format it as html, check [this](https://codepen.io/lionkay/pen/OJymwwz). But if `script` has `lang="html"` or `type="text/html"`, I can accept formatting it.

**Comment by fisker** [comment]
It's just string, we can even concat two template innerHTML.

**Comment by sosukesuzuki** [comment]
@fisker
> I really don't think we can format it as html, check this. But if script has lang="html" or type="text/html", I can accept formatting it.

I got it... I'll create PR to support `lang="html"` and `type="text/html"`.

> It's just string, we can even concat two template innerHTML.

Sorry, I'm not sure. Could you explain what do you mean?

**Comment by fisker** [comment]
```vue
<script type="text/x-template" id="t1">
  <img src="url" 
</script>

<script type="text/x-template" id="t2">
  :foo="bar === baz" />
</script>

<script>

new Vue({
	template: document.getElementById(t1).innerHTML + document.getElementById(t2).innerHTML
})
</script>
```

**Comment by fisker** [comment]
> I got it... I'll create PR to support lang="html" and type="text/html".

This don't has to be `vue`, we can apply to `html` parser too, I also use `textarea` to create template too, but I'm not sure other people use or not.

**Comment by sosukesuzuki** [comment]
Thank you show me examples! I close this issue for now.
