### ISSUE TITLE
CSS selectors must not be lowercased in styled-components that reference other

### ISSUE THREAD

**Issue by lucasols** [prettier/prettier#8352]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlGBPAGzgBMBhCAWwAdoEsBeTDQkgOmIEsA3AAwB0omTBQCGAJwDmHKAFoxHCQAsYSTDIAsVAB4BuAQKEASYOVgjpcMQF9WHNAFEtVEVGIlMAMkzADQzDDEXNAAzCDEKVTEIGBF4AAoZAEYADgAGNwkASj1BTCsBHh0QABoQCCoYDnRkUHEogHcABXEENGQQEQJ6kTw20oAjQLAAazgYbGcwaQlkAIBXOFLlCgIAdUUOeDRJuGxWze5NvHawND6QaTRLGEbAiVFkYM6r0oArNC0AISHR8ZEKOAAGQsj2eixA7y02GmRAAinNonBQQQXiBnGIrmJ2v0RP04AQSmj5LBVhxiDBFMg0qUqFErqtAlR2rS4JiuEjSgBHBHwW7lNooERoGRQOAkEiEsRwbkcKW3ET3ETI1FXCgcWZiBalNAwuDwxHK8Exfqk8mUpAAJlKAXMBGm5AoDxQrIArIS5lcACq4gVPFHgrgLACSrjo2DA8gqAEFXLgWIarFYgA)
```sh
--parser babel
```

**Input:**
```jsx
const StyledComponent = styled.div`
  margin-right: -4px;

  ${Container}.isExpanded & {
    transform: rotate(-180deg);
  }
`;
```

**Output:**
```jsx
const StyledComponent = styled.div`
  margin-right: -4px;

  ${Container}.isexpanded & {
    transform: rotate(-180deg);
  }
`;

```

**Expected behavior:**

The input and output should be the same, keeping the selector `.isExpanded` case. The output breaks the style since HTML selectors are case-sensitive.

**Comment by jonathanstiansen** [comment]
This is the case with parser @typescript-eslint as well. Probably also with just eslint-prettier.

**Comment by nfour** [comment]
Can confirm with `typescript-eslint`, thought maybe I had the syntax wrong at first. 

Going to use `/* prettier-ignore */` for now.

**Comment by dontsave** [comment]
also, if it helps debug, the unwanted lowercasing only seems to happen on the first instance of a class name selector attached to an interpolation in the line. further class names are not lowercased: [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlGBPAGzgBMBhCAWwAdoEsBeTDQkgOmIEsA3AAwB0omTBQCGAJwDmHKAFoxHCQAsYSTDIAsVAB4BuAQKEASYCIBGYAL6swIinAKkRaOJgDUmY8TgAzKzbsOTi4AZJjABkKYMGIiUGjeEGIUqmIQMCLwABQyAIwAHAAMXhIAlHqCmBYCPDogADQgEFQwHOjIoOKpAO4ACuIIaMggIgRdIniDDaYxYADWcDDYVCJg0hLI0QCucA1wFKYkXsQAMrESmyIScABiiaIwLVDrKCKbMBD1IMoUBADqihx4GhlmA4NgBoDuIC8EMwGhJiBpM4xDAejEJKJkN4Rs4GgArNBaABCM3mi1scGO0jgWJxOxABK02DWRAAips0jSkNiCLiQMsxMihqYzPZPlR5LBfhxiDBFMhCg0JRBnL8YlQhhK4MiuDSGgBHDnwNFNQYvNAyKBwEgkT5iOCGjj2tGXTHcukNZwUDgbMTbT0suDszm03n09KmaWy+VIABMDWiIg4BDW5AobpA2oArJ9Ns4ACpmM08vlcbYASSgXlg2DA8maAEEq7gWKHnBYLEA)
