### ISSUE TITLE
Misformats array destructuring (variable swap) following object

### ISSUE THREAD

**Issue by janosh** [prettier/prettier#8361]
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAExMEMA0mARpgL6YC82eSmAjIUbQExkA6UHA2kYbgLqVMXAsX4h8ICAAcYAS2gBnZKFwAnNRADuABXUJlKXKi24AnsslE1uMAGsMAZWm25UAObIYagK5xJABYwALaoAOoBcvCKLmBwjgZRcgBuUWbI4IqWIG6KcGowOjbuwbjIAGbGeZIAVooAHgBCNvZOuMFwADJucBVV-iB19Y5u7ugAij4Q8H2o1SAuanlqGUS4RHCoEgtqbjBhcgAmMAHIABwADJLSmnlhNtIZN3DLyb2SAI5T8EUyhiC4RQAWigcDgh3B2zUcC+cmhRVwJTKSEqcwGeWCclm80Uowm316KP6khg6wOx1OSGYJJsclQowAwhBgqUMi8AKzbHx5AAq60MqPmyT8AEkoBDYI4wLtZABBcWOGBmdDYuCkUhAA)
```sh
--parser babel
--no-semi
```

**Input:**

```jsx
let { a, b } = { a: 1, b: 2 }

[b, a] = [a, b]
```

**Output:**

```jsx
let { a, b } = ({ a: 1, b: 2 }[(b, a)] = [a, b])

```

**Expected behavior:**
Nothing to format here. Should remain:

```js
let { a, b } = { a: 1, b: 2 }

[b, a] = [a, b]
```

**Comment by thorn0** [comment]
This behavior is expected. Please see https://prettier.io/docs/en/rationale.html#semicolons
