### ISSUE TITLE
Prettier breaks template literal in JSX className

### ISSUE THREAD

**Issue by wudoem** [prettier/prettier#8363]
Hello. Im using function as template literal to generate classnames and then convert them into CSSModules. Currently Prettier is breaking my template literal. This is my config:

```
{
  "semi": false,
  "printWidth": 180,
  "tabWidth": 2,
  "tabs": false,
  "endOfLine": "lf",
  "arrowParens": "always",
  "jsxBracketSameLine": true
}
```

What I want to achieve:
```<div className={css`md:mr-8 h-full`} />```

What am I getting as result:
```
<div className={css`
 md: mr-8 h-full
`} />
```

Please notice prettier adds space after `md:` . How can I solve it?

**Comment by wudoem** [comment]
Setting `parser: "babel"` solved isue

**Comment by evilebottnawi** [comment]
Please use the issue template otherwise we will close it

**Comment by thorn0** [comment]
@wudoem For now you need to choose a different name for your function because Prettier has a special logic for formatting CSS in JS triggered by a set of hard-coded template tag names (`css`, `styled.*`, etc.). Or you can wait. It'll be possible to disable this behavior in Prettier 2.1 (see #7875).

**Comment by jonathanstiansen** [comment]
re: [prettier 2.0](https://prettier.io/blog/2020/03/21/2.0.0.html#dont-lowercase-element-names-in-css-selectors-6947httpsgithubcomprettierprettierpull6947-by-ark120202httpsgithubcomark120202) notes @thorn0 I thought that this was fixed?

**Comment by thorn0** [comment]
@jonathanstiansen ???

**Comment by jonathanstiansen** [comment]
FYI - when prettier 2.1 comes out it should fix this. For now the dev branch should work.
