### ISSUE TITLE
Indented unordered lists formatted wrong if tab rather than spaces

### ISSUE THREAD

**Issue by trinkel** [prettier/prettier#8364]
I have searched for this and while I found other issues that may be related, this seems different.

If my editor (VS Code) uses tabs for indenting, indented unordered list items loose their line returns. If the editor is set to use spaces for indenting it seems to be ok.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABASXQQwLboBiAllHADpQYDqcANnQDTpQQzoBOcODAnpTRxQoOdAGtWAd3SSAFvyroAcm07c+lcjAwB5CAAcAzpu3oAKrLhd0AcwhxDuVjEsdOAVwBGnq+hhc4dH06IQA6ShBGEAMYYmhDZFAcDg4ISQAFZIQElB5JHF4EqM8OHDAxOBgAZX0y0htkf3c4KNkYPDpqWWJ4Q1qwOCrsnuIANx7eZHBDIpBSQysYdNKbPBxkADMeBaiAK0MADwAhUvLKqvw4ABlSOE3tlpB9g6r6ujgARXc2O6Qtuh2IFqHAWHCmaw4YgAJmkoJEgRxSDBqMQoS5kAAOAAMUX0qQW1FK+imeIcVlGdyiAEdvvBlgYciAcIZUGQ4FD2fCuDTiFxljhVus-g8ogs8MRGhxmqK3p9ab9-oCYDhPCi0bJkAAmKL+HDEOj1ADCEDwaymDgArPD3AszCqck1HqNmpgoBzYFUwIj9DAAIJuqowXjve4AuAAX3DQA)
```sh
--parser markdown
--use-tabs
```

**Input:**
```markdown
- I am Fine
- Well, not really
- Wanna know why
- Not really
	- Oops
	- There goes another rubber tree plan.

```

**Output:**
```markdown
- I am Fine
- Well, not really
- Wanna know why
- Not really - Oops - There goes another rubber tree plan.

```

**Expected behavior:**
- I am Fine
- Well, not really
- Wanna know why
- Not really
	- Oops
	- There goes another rubber tree plan.

**Comment by thorn0** [comment]
#8140 should fix this.
