### ISSUE TITLE
Playground: enable glimmer parser for handlebars?

### ISSUE THREAD

**Issue by dcyriller** [prettier/prettier#8372]
https://github.com/prettier/prettier/pull/4915 enabled glimmer parser on preview playground. Do you think it could be enabled for prettier.io/playground (perhaps with the "experimental" mention)? It would make reporting issues easier (thanks to the "Report issue" button).

EDIT: I'd be happy to help if you point me to the right files.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/blob/master/website/playground/markdown.js#L36

**Comment by dcyriller** [comment]
Just opened https://github.com/prettier/prettier/pull/8373

**Comment by thorn0** [comment]
closed by #8373
