### ISSUE TITLE
mixed arrow functions handling

### ISSUE THREAD

**Issue by shaharmor** [prettier/prettier#839]
Hi,

This:
```js
server
  .stop()
  .then(() => console.log('x'))
  .catch(() => {
    console.log('y');
  });
```

gets transformed in to this:
```js
server.stop().then(() => console.log('x')).catch(() => {
  console.log('y');
});
```

Shouldn't it be more like this?

```js
server
  .stop()
  .then(() => {
    console.log('x');
  })
  .catch(() => {
    console.log('y');
  });
```

Btw, if I wrap the `console.log('x')` method with `{}` myself it will keep it like it should and not mess it up.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22server%5Cn%20%20.stop()%5Cn%20%20.then(()%20%3D%3E%20%7B%5Cn%20%20%20%20console.log('x')%3B%5Cn%20%20%7D)%5Cn%20%20.catch(err%20%3D%3E%20%7B%5Cn%20%20%20%20console.log('y')%3B%5Cn%20%20%7D)%3B%5Cn%5Cn%5Cnserver%5Cn%20%20.stop()%5Cn%20%20.then(()%20%3D%3E%20console.log('x'))%5Cn%20%20.catch(()%20%3D%3E%20%7B%5Cn%20%20%20%20console.log('y')%3B%5Cn%20%20%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
If all the chain but the last call fit in one line, it's going to keep it that way. As a general rule, prettier tries to keeps things in one line when they fit.

If you want to make it be multi-line, you can add `{}` in the second arrow function as you did or make the expressions longer so that it doesn't fit 80 columns.

**Comment by vjeux** [comment]
I noticed that you put 120 columns in the example. I would recommend that you put it to something closer than 80 columns. The way prettier works is that it puts as many things as they fit in the limit of columns. So if you have a big window, then each line is going to be very dense.

**Comment by shaharmor** [comment]
and I guess there is no way to ask prettier to always add `{}`, is it?

**Comment by vjeux** [comment]
Prettier tries to only change the way code is formatted and not the AST. There are many legit use cases for both brackets and non-bracket and we don't see prettier as being the judge of that.

**Comment by shaharmor** [comment]
And adding `{}` changes the AST because its a block? Sorry, I'm not that familiar with how AST's are built

**Comment by yamafaktory** [comment]
Adding a block wrap it into a `BlockStatement`. You can play with your code in https://astexplorer.net/ in order to see it.

**Comment by vjeux** [comment]
Let's close this one as this is behaving as expected.
