### ISSUE TITLE
Handle new AST type `TSEmptyBodyFunctionExpression`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8416]
Ref: 

- `typescript-estree` PR https://github.com/typescript-eslint/typescript-eslint/pull/1289
- `@typescript-eslint/typescript-estree@v3.0.1` #84

**Comment by thorn0** [comment]
As far as I can tell, nothing needs to be done here. These nodes aren't passed to `print`.

**Comment by fisker** [comment]
Close?
