### ISSUE TITLE
How to prevent breaking lines for each statment

### ISSUE THREAD

**Issue by Ofer-Gal** [prettier/prettier#8417]
After formatting in VS code, I get:
`<GridColumn
            field="ProjJob"
            title="Project-Job"
            width={setWidth(50)}
            groupable={false}
            filter={"text"}
          />` 

But I want it to stay 
`<GridColumn field = "ProjJob" title = "Project-Job" width = {setWidth(50)} groupable = {false} filter = {"text"} />`

I change "Prettier: Print Width" to be 180 and Prettier: Prose Wrap to never 
but it still breaks the lines
also, where is the configuration file?
Thank you

**Comment by thorn0** [comment]
Please provide a reproduce of your situation using the [Prettier playground](https://prettier.io/playground/) and the <kbd>Copy markdown</kbd> button there.

However, overall, that's what Prettier does: breaks lines if they get too long. It doesn't make sense to use Prettier if you don't need its line-breaking behavior as this behavior and Prettier are one and the same.

> also, where is the configuration file?

See https://prettier.io/docs/en/configuration.html
