### ISSUE TITLE
paranthesis around jsx used in a prop

### ISSUE THREAD

**Issue by chrisdrackett** [prettier/prettier#843]
Prettier adds parans in the following:

```js
<ParentComponent prop={
  <Child>
    test
  </Child>
}/>
```

exporting as:

```js
<ParentComponent
  prop={
    (
      <Child>
        test
      </Child>
    )
  }
/>;
```

This seems to add a lot of extra lines to me, curious what others think.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3CParentComponent%20prop%3D%7B%5Cn%20%20%3CChild%3E%5Cn%5Cttest%5Cn%20%20%3C%2FChild%3E%5Cn%7D%2F%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Good catch, the parenthesis are a bug. cc @rattrayalex

**Comment by rattrayalex** [comment]
on it
