### ISSUE TITLE
2.0 Regression: Type casts before variable declarations are broken

### ISSUE THREAD

**Issue by ExE-Boss** [prettier/prettier#8434]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBzBcBOAhjBPpgLyYBmArlGDAJbQBUmAFAJSbAC+A3AB0oAehZsAAjACeABzg8A4niIl8AMToNmUAMLoY+Gg1K9MLEcMhQMOFcVKb6TaBQ64oBB2QD8dz6qkAHTWGEYmZEiYdAAmcFSMnjGcQlBWBpiEaNL06lBuWTlg1Fou+Vw8AsJikjLyPE7a0Po2hsZqZhbprZnZuaU6buyFufl+I2B5IQbhaphRsfGJcMmp3bYTyvmUEyXOOmwVfKk1mFJyCsAAgn1gW15qjWUtYe2m5pb0GZsIT4OUw1uW0w4yBCGmrVmpHm0SgcQSSRSIAANCAILIymhkKBCPh8BAAO4ABVxCCxKEIABsCYRpFjUQAjIhgADWcBgAGVZIQwIlsMg2nBUQALGAAW0pAHVhYx4GhuWA4ByybLGAA3WXSZDgND0kCJNAEGBEojYMWEZBUKmG1EAKzQAA8AELMtmcwhiuAAGWWlutQpA9odHL5lLgAEUaBB4H7KTaQNz8Ib8NqGYQGXBKSiE-hEjBJYwYjBhcgABwABlRsnxhslRFk2urcGTarg2YAjlH4Cb0eSQFkALSeFYrbP4OCdxjjk2EM0WpBWuMBw1ixgCozL0MRrtthf+1EwdMFoslpAAFgPREYlL5+jF5u1zYArNmaIaACrp8mC1FqmhwABJOEEE5MBcwxK44Q5GQw1jQ1eF4IA)

## Input:

```js
const generator = function* () {};
/** @type {GeneratorFunctionConstructor} */
const generatorFunction = (generator ? generator.constructor : undefined);

const asyncFn = async function () {};
/** @type {FunctionConstructor} */
const asyncFunction = (asyncFn ? asyncFn.constructor : undefined);

const asyncGen = async function* () {};
/** @type {AsyncGeneratorFunctionConstructor} */
const asyncGenFunction = (asyncGen ? asyncGen.constructor : undefined);
```

## Output:

```js
const generator = function* () {};
/** @type {GeneratorFunctionConstructor} */
const generatorFunction = generator ? generator.constructor : undefined;

const asyncFn = async function () {};
/** @type {FunctionConstructor} */
const asyncFunction = asyncFn ? asyncFn.constructor : undefined;

const asyncGen = async function* () {};
/** @type {AsyncGeneratorFunctionConstructor} */
const asyncGenFunction = asyncGen ? asyncGen.constructor : undefined;
```

## Expected behaviour:

```js
const generator = function* () {};
/** @type {GeneratorFunctionConstructor} */
const generatorFunction = (generator ? generator.constructor : undefined);

const asyncFn = async function () {};
/** @type {FunctionConstructor} */
const asyncFunction = (asyncFn ? asyncFn.constructor : undefined);

const asyncGen = async function* () {};
/** @type {AsyncGeneratorFunctionConstructor} */
const asyncGenFunction = (asyncGen ? asyncGen.constructor : undefined);
```

## Additional notes:

- This used to work before <https://github.com/prettier/prettier/pull/7791>.
- This is valid type cast syntax when using **TypeScript** to type check **JavaScript** files.

**Comment by thorn0** [comment]
The behavior you're relying on is a bug in TypeScript: https://github.com/microsoft/TypeScript/issues/26635. Being a bug, it's going to be fixed, so I wouldn't recommend relying on it. See also https://github.com/prettier/prettier/issues/8045 

The syntax of JSDoc type casts is simple: `@type` comment followed by a parenthesized expression. Anything else is not a type cast. Reference: [Closure Compiler](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#type-type), [TypeScript](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#casts).
