### ISSUE TITLE
Comment breaks pipeline and logic operator indention 

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8451]
**Prettier pr-8435**
[Playground link](https://deploy-preview-8435--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBDAOlABFgPgPi1S0xwKJwHpKtIBbOhGUvQjbVozTYgMl5IcANtADmAGTGSoEqXJnTZCsVn4sRyzUu2Ld80aoFZqtCAybr9erdZ0q1wq05vPR3KMVy5LL33b943o5+tqH6gVQ09IywPv7xYVqBcYkJriAANCAQAA4wAJbQAM7IoKgATuUQAO4AChUIJSioQtWoAJ4lWQBG5ahgANZwMADKOf35Msgw5QCucFlwdN1wACara+KoMrOoonAAYhDldKgwBVPNszAQmSAAFjB0QgDq9-nwReNgcCONH-kAG4fdrIcBFLogSZFODlGC1PqiU7IABmLRhWQAVkUAB4AIT6g2GI1QjHEkzgqPRCxA2JxI0moiEcAAirMIPAqUIMSBxuUYeUwd1UCshHccuVJjAXvlVjB7sgABwABiyEogMJefRyYIlcAFgMpWQAjuz4Ajck00EUALRQOBrNZ3cpwU35F0IvbIpBo7k0mF0fLTOb+xnMtkcyk+6lZGAimVyhVIABMsb6+SEjIAwmZvSB9QBWO6zGEAFRFTV9PMB8wAklANrARmBJXkAIINkYwdrMrkwgC+-aAA) (pipeline has not released yet, playground is from a PR)
```sh
--parser babel
```

**Input:**
```jsx
a
  |> a 
  |> a  // comment
  |> a
  |> a

a && 
  longLongLongLongLongLongLongLongLong &&
  longLongLongLongLongLongLongLongLong &&  // comment
  longLongLongLongLongLongLongLongLong &&
  longLongLongLongLongLongLongLongLong

a ||
  longLongLongLongLongLongLongLongLong ||
  longLongLongLongLongLongLongLongLong ||  // comment
  longLongLongLongLongLongLongLongLong ||
  longLongLongLongLongLongLongLongLong
```

**Output:**
```jsx
a
|> a
|> a  // comment
  |> a
  |> a;

a &&
longLongLongLongLongLongLongLongLong &&
longLongLongLongLongLongLongLongLong && // comment
  longLongLongLongLongLongLongLongLong &&
  longLongLongLongLongLongLongLongLong;

a ||
longLongLongLongLongLongLongLongLong ||
longLongLongLongLongLongLongLongLong || // comment
  longLongLongLongLongLongLongLongLong ||
  longLongLongLongLongLongLongLongLong;

```

**Expected behavior:**

Should aligned

<details>
<summary>Assign work as expected</summary>

**Prettier pr-8435**
[Playground link](https://deploy-preview-8435--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEZMF5MCGAOlJpgD4B8hmJZVNmA9E9hALbsIx0XXGk+hEiUhQM2PDQBk02oIA20AOYAZFeqhqNOrZu16VmWbyWHzBy-uu7lxuc1aRO3U7ZsWPVoycXv-ngHKIlBiEjj4BBTkboFx3vHRsQkpXl7RZCxsLrDJaUH5Wkl+8YWpKiAANCAQAA4wAJboyKAEAE5tEADuAArtCGjIIAQKXQQAnoPVAEZtBGAA1nAwAMq18w1ayDBtAK5w1XDs03AAJqdnqgRauwTKcABiEG3sBDCNWygEuzAQVSAACxg7AUAHUAQ14Gh1mA4CsBpCGgA3SHjIZgNBTECbNBwNowHpzZSvZAAMxGuOqACs0AAPABCc0WyxWBC4qk2cDJFIOIBptJWm2UCjgAEVdhB4NyFJSQOs2ri2kNpgQTgp-rU2psYKCGqcYADkAAOAAM1U1EFxoLmtSGmrgiqRXOqAEcJfBCXVBl80ABaKBwM5nf5tOBuhqhwl3ElIcky3m49gNbZ7BNCkXiyVc2M86owVW6-WGpAAJjzcwaCiFAGEODGQA6AKz-Xa4gAqqu9cdlSP2AEkoBdYCswFr6gBBQcrGDjEXS3EAXwXQA)
```sh
--parser babel
```

**Input:**
```jsx
const c = a
  |> a 
  |> a  // comment
  |> a
  |> a

const c = a && 
  longLongLongLongLongLongLongLongLong &&
  longLongLongLongLongLongLongLongLong &&  // comment
  longLongLongLongLongLongLongLongLong &&
  longLongLongLongLongLongLongLongLong

const c = a ||
  longLongLongLongLongLongLongLongLong ||
  longLongLongLongLongLongLongLongLong ||  // comment
  longLongLongLongLongLongLongLongLong ||
  longLongLongLongLongLongLongLongLong
```

**Output:**
```jsx
const c =
  a
  |> a
  |> a  // comment
  |> a
  |> a;

const c =
  a &&
  longLongLongLongLongLongLongLongLong &&
  longLongLongLongLongLongLongLongLong && // comment
  longLongLongLongLongLongLongLongLong &&
  longLongLongLongLongLongLongLongLong;

const c =
  a ||
  longLongLongLongLongLongLongLongLong ||
  longLongLongLongLongLongLongLongLong || // comment
  longLongLongLongLongLongLongLongLong ||
  longLongLongLongLongLongLongLongLong;

```
</details>

**Comment by thorn0** [comment]
Happens not only in expression statements:

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXmwA8AKdAIwEsAzCTKAYU0qgHM5MBZCAZwAs4AEwAKHAA4AbOEQDK6AO6COAHSgBqbAGsIYPhQYQIlOAHF0AWzgB5KFfIQpAVSjy46VHGwB6L9mqqNVglKcx5TCQBPMT4eAAl0AC8sQQA5QzEeABVjbLg1Klp6JhZ2Ll4BEXEpWQUlTABKAG4QABoQCDEYSmgeZFAsTAh5YSwEXpR0CXl0CN628kx0ME04GBkxJZLkGEwAVzg2vhhzCQB1Pkp4Hg2wOBkxy8pUS4jkcB45kBYwzBhhRdY5nQyGokzCbQAVjwiAAhRbLVZySwAGRYcBBYIOIChshKUgAirsIPAMRJwSANpgfm9yBQ4BJWhTmLBTpRBDA+MgABwABjaYkGYVOizEbwFcB+HkZAEcifB-h1xiB0DwALRQOBCISMzBwWWUXX-dCA4FIUFkrFhcyUbZ7S14uCE4nos2YtowCis9mcpAAJndi0owTYBnMQLeEoArIzdmFMhRxubyah9gBJKBKWAyMDMToAQQzMhgESkpLCAF9y0A)
```sh
--parser babel
```

**Input:**
```jsx
var a = x(abifornCringerMoshedPerplexSawder
+ kochabCooieGameOnOboleUnweave // f
+ glimseGlyphsHazardNoopsTieTie+bifornCringerMoshedPerplexSawder);
```

**Output:**
```jsx
var a = x(
  abifornCringerMoshedPerplexSawder +
  kochabCooieGameOnOboleUnweave + // f
    glimseGlyphsHazardNoopsTieTie +
    bifornCringerMoshedPerplexSawder
);

```
