### ISSUE TITLE
--supported-files-glob

### ISSUE THREAD

**Issue by alecmev** [prettier/prettier#8454]
I watch for changes from the command line and I use a copy-paste of this with `onchange`:

https://github.com/prettier/prettier/blob/5a0e33cc84fd59e20a0fcc1d055300a97b595689/src/cli/expand-patterns.js#L123-L136

Would be nice if this were baked-in as a CLI option, the code is already there. I'm sure I'm not the only one who's using Prettier like this, there's even [a page dedicated to this](https://prettier.io/docs/en/watching-files.html) in the docs.

**Comment by evilebottnawi** [comment]
What do you mean? It is a breaking change and we don't need `--supported-files-glob` flag for CLI

**Comment by alecmev** [comment]
I want `onchange` to pick up changes to all files supported by Prettier. So I have this script:

```ts
// getPrettierGlob.ts

import { flatten } from "lodash";
import prettier from "prettier";

const { languages } = prettier.getSupportInfo();
const extensions = flatten(languages.map((x) => x.extensions || []));
const filenames = flatten(languages.map((x) => x.filenames || []));

process.stdout.write(
  `**/{${extensions
    .map((x) => "*" + (x[0] === "." ? x : "." + x))
    .concat(filenames)}}`
);
```

And I run `onchange` like so:

```bash
yarn onchange `yarn ts-node getPrettierGlob` -- prettier --write '{{changed}}'
```

Instead, I'd like to have no `getPrettierGlob.ts` and run `onchange` like so:

```bash
yarn onchange `prettier --supported-files-glob` -- prettier --write '{{changed}}'
```

Or at least like so:

```bash
yarn onchange `yarn node -e "process.stdout.write(require('prettier').getSupportedFilesGlob())"` -- prettier --write '{{changed}}'
```

Perhaps this is feature bloat, but the code is already there, just need to expose it.

**Comment by fisker** [comment]
What do you think this solution https://github.com/prettier/prettier/issues/8136

**Comment by alecmev** [comment]
Thanks, @fisker, that would work! I can imagine a project where `onchange` might produce a lot of noise, e.g. triggered by log files, but that's nothing an `--exclude` can't fix.
