### ISSUE TITLE
Trim final newlines

### ISSUE THREAD

**Issue by Roger-WIN** [prettier/prettier#8457]
I use Prettier by its Visual Studio Code extension.
VS Code offers an option to trim final newlines, but Prettier overwrites it.
I wish Prettier to offer the same option either in VS Code settings (preferred personally!) or Prettier configuration file. Or at least, do not overwrite the option offered by VS Code.

**Comment by thorn0** [comment]
Please use the [playground](https://prettier.io/playground/) to reproduce your issue.

**Comment by Roger-WIN** [comment]
No bug, it's just a feature suggestion.

**Comment by thorn0** [comment]
The thing is Prettier doesn't do what you describe, or probably you don't understand what Prettier does (it doesn't work with lines, it reprints the syntax tree). That's why I'm asking for a reproduce, to understand what exactly you refer to. An example of input code, of Prettier's output, and what you expect it to be.

**Comment by Roger-WIN** [comment]
**Input:**

```javascript
const getList = async () =>
    (await getCases())
        .map(item => item.name);
```

**Output:**

```javascript
const getList = async () => (await getCases()).map(item => item.name);
 
```

**Expected behavior:**
The formatted code should occupy only 1 line. But Prettier adds a newline at the end, which makes the code occupies 2 lines.
I enable the option offered by VS Code to trim final newlines like that. But Prettier makes it invalid.

**Comment by thorn0** [comment]
Oh, I'm sorry. I misread you messages. For some reason I thought you meant trailing whitespace.
Final newlines were discussed before. See #2575
