### ISSUE TITLE
missing-parser warning when using prettier.resolveConfigFile() without parameters

### ISSUE THREAD

**Issue by JoernBerkefeld** [prettier/prettier#8458]
given that resolveConfigFile does come with an [OPTIONAL filePath parameter](https://prettier.io/docs/en/api.html#prettierresolveconfigfilefilepath) it should not throw an error if `parser` is not set in that config. After all, [the docs](https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option) state one should not set parser outside of overrides.

**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: Node.js API
- Runtime: Node.js v13.3
- Operating System: Windows

**Steps to reproduce:**

```javascript
const prettierConfigPath = await prettier.resolveConfigFile();
console.log('prettierConfigPath', prettierConfigPath);
```

**Expected behavior:**
filePath is returned for CWD and no actual parsing of config is done.

**Actual behavior:**
return value is `null` and an error is thrown:
`No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.`

**Comment by JoernBerkefeld** [comment]
fyi @DougMidgley

**Comment by fisker** [comment]
@JoernBerkefeld 

May I ask, why are you using this `prettierConfigPath`? 
Because I don't know what this file can do in #6873.

**Comment by fisker** [comment]
I can't reproduce this issue.
