### ISSUE TITLE
On formatting, Prettier converts all my single inverted commas to double inverted commas in javascript File!

### ISSUE THREAD

**Issue by Vaasu-Dhand** [prettier/prettier#8460]
## Converts all my double inverted commas to single inverted commas. Happens in a Javascript file

**Comment by kachkaev** [comment]
Please follow the issue template: https://github.com/prettier/prettier/blob/master/.github/ISSUE_TEMPLATE/formatting.md

**Comment by conartist6** [comment]
Bug: user can't discover the `singleQuote: true` option if they don't know the word for "quotation mark".

@Vaasu-Dhand Please consider closing this issue as it is not actionable.
