### ISSUE TITLE
Is there a way to detect/prevent having conflicting configs with ESlint? 

### ISSUE THREAD

**Issue by dwjohnston** [prettier/prettier#8466]
As an example, say you have an eslint config like this: 

```
module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  extends: ['eslint:recommended', 'plugin:prettier/recommended'],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 11,
    sourceType: 'module',
  },
  rules: {
    quotes: ['warn', 'single'],
  },
};
```

You have a conflict here where the eslint `quotes` rule conflicts with how prettier wants to do quotes. 

```
// eslint wants this
const str1 = 'hello I\'m david'; 
// prettier wants this
const str2 = "Hello I'm david"; 
```

Now, even though we've put prettier/recommended at the end of our extends array, because this comes from the rules section it takes precedence. 

Is there a tool, or alternative way of doing the eslint configuration, such that this is never a problem?

**Comment by thorn0** [comment]
Yes, there is a helper tool for this. See https://github.com/prettier/eslint-config-prettier#cli-helper-tool
