### ISSUE TITLE
Some comments in JSX break

### ISSUE THREAD

**Issue by ashtonsix** [prettier/prettier#848]
[Two examples at link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22var%20a%20%3D%20()%20%3D%3E%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%7B%2F%2F%5Cn%20%20%20%20%7D%5Cn%20%20%3C%2Fdiv%3E%5Cn)%5Cn%5Cnvar%20b%20%3D%20()%20%3D%3E%20(%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%7B%2F*%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20Content%20in%20nested%20div%20long%20enough%20to%20require%20wrapping%20because%20it%20is%20rather%20long.%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%20*%2F%7D%5Cn%20%20%3C%2Fdiv%3E%5Cn)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

Prettier introduces syntax errors to the first example.

There are no issues in the second example, however it is very disruptive for my particular workflow. Pressing `ctrl + /` in Atom when a block of JSX is selected creates a comment like in _example b_, formatting with Prettier then reveals a bug in `language-babel` (all text after the comment is syntax-highlighted like a comment).

Sometimes Prettier formats mutli-line comments in JSX like this (good):

```js
(() => (
  <div>
    {/* <span>
      text
    </span> */}
  </div>
));
```

But sometimes like this (bad):

```js
(() => (
  <div>
    {/* <span>
      text
    </span> */
    }
  </div>
));
```

Decreasing `printWidth` seems to help replicate the bad formatting.

**Comment by vjeux** [comment]
Thanks for the report! This is likely the same bug as https://github.com/prettier/prettier/issues/712 i'm going to fix it today
