### ISSUE TITLE
Unnecessary backslash removal from path string

### ISSUE THREAD

**Issue by Igsu-Bravo** [prettier/prettier#8483]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEB3AllAEwmzQAUBDGAC0wF5MByAUgFUBlAUQCVSuB5AGIBJADIcmAHQkAROGgDWMCAAcGAbglQQAGhAqYudMlDkATqeIVTCNMhDkANtnIBPW7oBGp8mHlwYbMo++ADmyDCmAK5wulQwALYOAOpUuPBoQWBwbDZpuABuaS52YGjuIPhocKYwpN4h8eTIAGaOVboAVmgAHgBC3r7+bOTxcCL4cC1tMSBd3WyhDnAAipEQ8FMO7SBBplWmdh7kHnAOOjum+DBJuATUyAAcAAy6yhZVSd7Kdm9y1fmTXQARzW8DqKlsKHIaAAtFA4HACIjztYQbhrHVyA0mkhWlsZlV4rhwlECYsVqDJrjproYMcbncqMgAEy07y4ByhADCEHijTscgArOdIlUACrHSF47b5aJCQgIAJgS7KGAAQUIbBgLiWmyqAF99UA)

Hi! And thanks for the awesome package 😸 

I stumbled upon this particular case where backlash is removed from a path string. Obviously we need to maintain the backslash for the path string to work.

**Input:**

```jsx
const windowsPath = '%USERPROFILE%\Desktop';
```

**Output:**

```jsx
const windowsPath = '%USERPROFILE%Desktop';
```

**Expected behavior:**

```jsx
const windowsPath = '%USERPROFILE%\Desktop';
```

As a workaround I used a template literal and the formatting was kept correctly

```jsx
const windowsPath = `%USERPROFILE%\Desktop`;
```

**Comment by thorn0** [comment]
Prettier works as expected. Open your browser console and enter `'%USERPROFILE%\Desktop'` to see what I mean.
