### ISSUE TITLE
Prettier doesn't send reports when there is an error in a MDX file

### ISSUE THREAD

**Issue by Ayc0** [prettier/prettier#8488]
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: VSCode's prettier-vscode 5.0.0 or prettier CLI
- Runtime: Node 14.3.0
- Operating System: macOS 10.15.2 

**Steps to reproduce:**

- Clone and install this repo locally: https://codesandbox.io/s/mdx-vsvode-prettier-p8oks
- Install the extension prettier-vscode

I made two typos on purpose in this repo:
- an extra comma in a JSON file – [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAE3NpAQzyVxACM8AaCjAXwxApAgAcYBLaAZ2VHwCc+EAO4AFfgm4p8ANwhsAJgzJ98YANZwYAZWaq2UAObIYfAK5xGACxgBbADYB1S23iddYOFoku20lwE9kcE5uRn1OOD4YERUDG3xkADN8OwjGACtOAA8AIRV1TS18GzgAGX04JJS0kEysrX0DOzgARVMIeCrUixBdPgi+IMzoJWY+fRgHBRhLZAAOAAZGMYgIhxVmILG4AelKxgBHdvgYlkkCTgBaKDg4eTulPjgjtieY-DiEpGTuxgibNjGMw9TiNZptDqVb7VHowfCkKbyGbIABMjBM+DYdkaAGEIDZ4kEoNB9iBTBEACrwyQ-GrScwASSg91gWjA41YAEFmVoYP5ml0IjQaEA)
- an extra curly bracket in a JSX block in a MDX file – [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAzgDwDpSRRYwAEAhqQLykAOAThLVgL7UB8pwBpp9cMAK70odRswIsC6VCAA0IJjACW0LMlDl6jAO4AFLQnUpyANwjKAJvJAAjeuTABrAQGVaj5VADmyGPUE4BQALGABbABsAdWDleCwPMDhXIzjlUziAT2RwLHUFLyw4ehg9B28w8mQAM3IIooVsHAAhB2c3cjC4ABkvOBq6hpAm1y9vCLgARUEIeAH6oJAPeiL6HLDLHBsGLxgoqxhg5AAOAAYFBggiqIdaHIY4VdN+hQBHGfgypmMQciwAWigcDglhBNn472U-DK5AqVSQtQWCiKYWUfgCiywYwm01m-QRg0WMHItn2lkOyAATAp-ORlBExgBhCBhSo5KDQF4gQRFAAqJOMiKGpkCAEkoKDYK4wPRlLQYABBCWuGCZCbzIosFhAA)

![image](https://user-images.githubusercontent.com/22725671/83629529-8d285a00-a59a-11ea-8f83-304089231c5e.png)

**Expected behavior:**

They should both send a report in VSCode / the CLI (they throw the right errors in the playground, see links above)

For the JSON file
![image](https://user-images.githubusercontent.com/22725671/83629675-d8db0380-a59a-11ea-9da8-11dd13a6f295.png)

**Actual behavior:**

I have no report when formatting the MDX file:
![image](https://user-images.githubusercontent.com/22725671/83630001-60c10d80-a59b-11ea-8f65-5e3d112dc053.png)

I opened an issue here instead of in VSCode's integration because I have the same result in the CLI:
![image](https://user-images.githubusercontent.com/22725671/83630420-142a0200-a59c-11ea-8f67-857ee6647739.png)

**Comment by thorn0** [comment]
This works as expected. Prettier is a formatter, not a syntax checker. If an embedded code block can't be parsed, it doesn't mean the whole document shouldn't be formatted as it's still valid Markdown. The Playground shows those errors for debugging purposes.

If you need them, you can set the `PRETTIER_DEBUG` environment to any non-empty value, but keep in mind that this is just a debugging aid. It may be changed or removed without notice in any release.

**Comment by thorn0** [comment]
Also the support for MDX in Prettier isn't mature enough for allowing such errors to propagate (even though, after a second thought, I agree that that might make sense). See https://github.com/prettier/prettier/issues/7041#issuecomment-557915941

**Comment by Ayc0** [comment]
@thorn0 in that case, why does the prettier sandbox throw an error with the same output?
![image](https://user-images.githubusercontent.com/22725671/84872585-5cf4b700-b082-11ea-9c4e-a22a7953f826.png)

I created this issue specially because you have a different behavior in your sandbox and in your CLI

**Comment by thorn0** [comment]
> The Playground shows those errors for debugging purposes.

**Comment by Ayc0** [comment]
Sorry, I haven't seen this line
Thanks 👍

**Comment by thorn0** [comment]
That's probably because I wrote two comments instead of one, so you missed the first one. I merged them now.
