### ISSUE TITLE
Force newline after if/else condition

### ISSUE THREAD

**Issue by gardhr** [prettier/prettier#8494]
How to get a newline printed after the closing parenthesis of conditionals and such?

Example:

```
if (condition) action();
```

What I want is this:

```
if (condition) 
 action();
```

**Comment by thorn0** [comment]
There is no way to do that. It's wrapped if the line is long enough. See also https://github.com/prettier/prettier/issues/3049

**Comment by gardhr** [comment]
Is there some technical reason for this? Because it obviously works in certain situations. (Eg: comments appearing on a line ensuing a conditional, for example.)

**Comment by thorn0** [comment]
It's intentional and isn't going to change.

**Comment by gardhr** [comment]
Well your software is garbage, and so is your attitude. I'm guessing neither is going to change any time soon either. Moving on...

**Comment by thorn0** [comment]
Well, we have a code of conduct and you just have been reported. Congrats.

**Comment by gardhr** [comment]
You doggedly refuse to consider adding a feature which users have repeatedly requested. (As can be seen in issue #3049.) Perhaps you should be questioning your own motivations before accusing others of bad conduct?
