### ISSUE TITLE
Intendation for const variables

### ISSUE THREAD

**Issue by rogovdm** [prettier/prettier#850]
It's likely that this issued has already raised in the repo, but I could not find it 😞 

My proposal is to change aligning of `const` variables declaration.

Current view:
````javascript
const locomotive = require('locomotive'),
  Controller = locomotive.Controller;
````

Desired:
````javascript
const locomotive = require('locomotive'),
      Controller = locomotive.Controller,
````

**Comment by vjeux** [comment]
You are the first to have raised it.

Some thoughts:
- Nowhere in prettier do we indent by an arbitrary amount of spaces to match the indentation of a keyword. So this would be an exception and may be seen as inconsistent.

- If you have series of `const` and `let`, it would look very odd having the indentation be off.
```js
const locomotive = require('locomotive'),
      Controller = locomotive.Controller;
let locomotive = require('locomotive'),
    Controller = locomotive.Controller;
```

My suggestion is for you to add a const before each line, this way they all look nicely aligned:

```js
const locomotive = require('locomotive');
const Controller = locomotive.Controller;
```

**Comment by rogovdm** [comment]
I'll get into discussion.

`Nowhere in prettier do we indent by an arbitrary amount of spaces to match the indentation of a keyword. So this would be an exception and may be seen as inconsistent.`
Can't respond anything because I, unfortunately, don't understand how much complexity this inconsistency will bring to the code. Can you give it some measure?

`If you have series of const and let, it would look very odd having the indentation be off.`
Before I used to put escape between series of declarations and perfectionist inside me said nothing 😄 

````javascript
const locomotive = require('locomotive'),
      Controller = locomotive.Controller;

let locomotive = require('locomotive'),
    Controller = locomotive.Controller;
````

`My suggestion is for you to add a const before each line, this way they all look nicely aligned:`
That is actually a 'workaround'. 😸  I will try to use it and see how it goes.

**Comment by vjeux** [comment]
> I don't understand how much complexity this inconsistency will bring to the code

The implementation would be trivial. The prettier codebase is pretty awesome to work on :)

**Comment by rogovdm** [comment]
So :)

Constant typing of «const» feels okaaay, but I would prefer automatic indentation. 

I'd like to see other peoples opinions. I'm the first one who raised this question but also I'm truly surprised that thus does bother anybody else :)

**Comment by lydell** [comment]
I use one `const` (or `let` or `var`) per variable. Makes it easier to move the declarations around.

**Comment by SimenB** [comment]
If Prettier were to enforce anything, I'd like it to force a `const`/`let`/`var` per declaration. If you wanna get fancy, mess about with just for initialisations: http://eslint.org/docs/rules/one-var-declaration-per-line#initializations, http://eslint.org/docs/rules/one-var#initialized-and-uninitialized.

But it might be best to just leave it alone. I'd definitely _not_ like indentation based on the length of the keyword used, then I'd probably start post-processing...

> Constant typing of «const» feels okaaay, but I would prefer automatic indentation.

You type it the way you want, then Prettier expands to one per line. No "constant typing" on your part 😀

**Comment by vjeux** [comment]
@simenb: yeah, one of the next step for prettier is to plug an ast-based transform in front. This way you can do those kind of expansion, merging else { if } into else if...

**Comment by rattrayalex** [comment]
Should this be closed?

**Comment by vjeux** [comment]
Let's keep it open for a while longer so that people can chime in. At some point we'll likely want to close it out.

**Comment by rogovdm** [comment]
> not like indentation based on the length of the keyword used

Can you, please, provide more details? Basically, why this is so bad for you as it seems.

**Comment by rogovdm** [comment]
Const per variable is completely fine
