### ISSUE TITLE
bug(handlebars): Idempotency issue

### ISSUE THREAD

**Issue by dcyriller** [prettier/prettier#8504]
## Description

```hbs
<Textarea />

{{#if true}}
  Test
{{/if}}
```
is formatted to 
```hbs
<Textarea />
{{#if true}}
  Test
{{/if}}
```

And 
```hbs
<Textarea />
{{#if true}}
  Test
{{/if}}
```
is formatted to
```hbs
<Textarea />

{{#if true}}
  Test
{{/if}}
```

## Report

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAKnAHjAhgJzlwAIB6APgB0phgBiASwDNiZ8BXOAXy+uOMwBnGNVqlmPPsWoZseQiQrVR9Zqw7deUfkJE1g4pjxAAaEBAAOMBtEHJQBfBADuABQII7KXABtnuAE87MwAjfFwwAGs4GABlCwiGKABzZDZOMwALGABbHwB1TIZ4QQSwOFjPYoYAN2KA5HBBYJAkwTh8GFdw5JzcZCZfdrMAK0EsACFwqJjY3By4ABkkuAGhuFHx2KTknzgARXYIeDWfYZAE-Hb8Rt2GHIWbswt8JJh8hgATGEzkABYAAzPJztfLhCyNF5wa41VZmACOR3g3UsXhAuEEAFooHA4J88aYQIREQxCN1cL1+khBmcNiB2jkGGkNGZBDs9odjqtqeszHgQh9vr8kAAmPnhBg+HYAYQgDypIGhAFZCex2uhcCEvDTzjVOABJKD42CxMCvKwAQSNsRgAT2p3aPCAA)
```sh
--parser glimmer
--print-width 40
```

**Input:**
```hbs
<Textarea />
{{#if true}}
  Test
{{/if}}
  
<Textarea />

{{#if true}}
  Test
{{/if}}
```

**Output:**
```hbs
<Textarea />

{{#if true}}
  Test
{{/if}}
<Textarea />
{{#if true}}
  Test
{{/if}}
```

**Expected behavior (maybe):**
```hbs
<Textarea />
{{#if true}}
  Test
{{/if}}
  
<Textarea />

{{#if true}}
  Test
{{/if}}
```

**Comment by Alonski** [comment]
Anyone want to pair with me on trying to fix this?

**Comment by Alonski** [comment]
The really weird thing is that this only seems to happen for `<Textarea>`
[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAKnAHjAggJzgEMACAegD4AdKYYAYgEsAzEmfAVzgF9uaSSmAM4wadMi178SNDNhhFCpSjTEMWbTjz5QBw0bWATmU3f1mYcBYsuqGmrdl1N64ItcZcyocnIpvkdmoOms46ru6GntwgADQgEAAOMIzQQsigivgQAO4ACv5Q6ShEADY5RACe6fEARvhEYADWcDAAyomNjFAA5shOcPEAFjAAtqUA6kOM8EKdYHBtCEIzjABuM5XI4EI1IN1CcPgweQ09o0TIzGWH8QBWQlgAQg3NrW1Eo3AAMt1wVzdBiAHlg2t0eqU4ABFDgQeAA0q3ECdfCHfDbCGMUZfdHxRL4bowCaMAAmMCGyAALAAGPHZQ4TBqJbb4txHNb-eIAR1h8FOSWKICIQgAtFA4HASZK4iBCDzGIRTkRzpckNdEUDDqNGP0tPEVr1ITC4f81YD4gpasSyRSkAAmC0NRilcEAYQg2NVIDcAFYZRxDugiLViuqkWsuABJKBS2BtMAE5K4GNtGCVSEIw68IA)

**Comment by fisker** [comment]
FYI: There is a `show second format` option on playground.

**Comment by Alonski** [comment]
@fisker Any idea what this means?

**Comment by Alonski** [comment]
Oh it just formats again :)

**Comment by Alonski** [comment]
@fisker Would you be up to pairing with me next week to try and figure this out?

**Comment by fisker** [comment]
I believe @dcyriller is more familiar with it. Don't worry, If you have problems, everyone will help.

**Comment by Alonski** [comment]
Ok :) This is the only thing blocking me from going all in on Prettier in the main app I work on.

**Comment by Alonski** [comment]
This seems to have been caused by this PR:
https://github.com/prettier/prettier/pull/6354

**Comment by dcyriller** [comment]
We chatted a bit over Discord. Might have a solution

**Comment by dcyriller** [comment]
The bug appears to be in glimmer 

In this AST, the TextNode chars attribute is "" instead of "/n" https://astexplorer.net/#/gist/bfd66c00d2b721d85d429f0fdecaff2c/45417f91610050f640cd57c409846742d4885b1b

**Comment by Alonski** [comment]
This PR is probably the "cause" for this issue: https://github.com/tildeio/simple-html-tokenizer/pull/59
Specifically this: https://github.com/tildeio/simple-html-tokenizer/blob/5a7739761ffc4358dd46399b5a2b62da9e0d7ba6/src/evented-tokenizer.ts#L137-L139

Looking at this code I found that `<Pre />` is also causing these issues.

**Comment by dcyriller** [comment]
Opened https://github.com/tildeio/simple-html-tokenizer/pull/84

**Comment by rwjblue** [comment]
@dcyriller - Updating to `@glimmer/syntax@0.62.3` should resolve this.

**Comment by dcyriller** [comment]
Awesome, thank you @rwjblue
