### ISSUE TITLE
Docs: Ellipsis is positioned oddly on mac / Better font stack?

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#8509]
In the docs, ellipsis (`…`) is positioned oddly (in the middle of the line) on mac:

<img width="832" alt="Screenshot 2020-06-06 at 22 42 43" src="https://user-images.githubusercontent.com/2142817/83954166-1663b900-a847-11ea-87c0-a059b1b4b7df.png">

It seems to be a problem with the font we are using (Apple SD Gothic Neo) according to https://discussions.apple.com/thread/7278554:

> That font is for the Korean language.  It's often a bad idea to use such fonts for English, because they are not designed for it and may well contain bugs like the one you are describing.  Better to use a font intended for the language you are writing in

Should we find a different font stack?

https://github.com/prettier/prettier/blob/a9fd99846a4b87d2590a74072d77fa241ccefd3f/website/static/overrides.css#L2-L3

**Comment by jeneser** [comment]
`Source Sans Pro` is a good choice. It is [licensed](https://fonts.google.com/specimen/Source+Sans+Pro#license) under the Open Font License. Lots of projects are using it. `ESLint`、`Vue.js`...

We can remove `Apple SD Gothic Neo` and `AppleSDGothicNeo`.  Like this:

```
font-family: "Source Sans Pro" -apple-system, 
   BlinkMacSystemFont, Helvetica, Arial, sans-serif; 
```
