### ISSUE TITLE
Feature request: -l option to list un-prettier-formatted files

### ISSUE THREAD

**Issue by llimllib** [prettier/prettier#851]
Similar to [gofmt](https://golang.org/cmd/gofmt/); helpful for writing tooling to verify that prettier has been run.

Ideally, `prettier -l [filename ...]` would print each file that would change on a new line.

**Comment by vjeux** [comment]
Really good idea!

**Comment by llimllib** [comment]
I wanted to have something like [gofmt's pre-commit hook](https://golang.org/misc/git/pre-commit). In the absence of `-l`, here's what I ended up with:

```
jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$')
[ -z "$jsfiles" ] && exit 0

# XXX note that this will not work on filenames with spaces
diffs=$(echo "$jsfiles" | xargs -I {} sh -c "prettier {} | diff {} -")
[ -z "$diffs" ] && exit 0

echo >&2 "Javascript files must be formatted with prettier. Please run:"
echo >&2 "prettier -w $(echo $jsfiles | tr '\n' ' ')"

exit 1
```

I'm not sure if there's a useful place to store this script?
