### ISSUE TITLE
Prettier automatically quotes vuetify property values (true, false, numbers)

### ISSUE THREAD

**Issue by Kenan7** [prettier/prettier#8514]
I want to pass contain as a true value;

![image](https://user-images.githubusercontent.com/11595462/83256862-4ca89500-a1c4-11ea-8ba7-64adde0bf7b5.png)

But when I save it automatically quotes the property value

![image](https://user-images.githubusercontent.com/11595462/83256841-3e5a7900-a1c4-11ea-9ec0-3a4e9db9b11c.png)

My default setting is "as-needed"

**Comment by fisker** [comment]
There is no difference, if you want `true`, you should use `:contain="true"`

**Comment by fisker** [comment]
See 

https://vuejs.org/v2/guide/components-props.html#Passing-a-Number

https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean
