### ISSUE TITLE
Configuration for opening brace/bracket on new line

### ISSUE THREAD

**Issue by marelynsaez** [prettier/prettier#8539]
Hi there! 

I would like to know please if it is possible to set up the opening brace/bracket after a function on a new line:

Current:

function foo() {
  //...
}

I would like to set it up like:

function foo()
{
  //...
}

Thank you in advance. :)

**Comment by evilebottnawi** [comment]
We don't want new options (https://prettier.io/docs/en/option-philosophy.html) and we don't want change current output

**Comment by marelynsaez** [comment]
Ok, thank you for the respond. I will try with Eslint and Prettier
