### ISSUE TITLE
Error Markdown files: transform **abc\_def\_cde**. Need to conserve escape \_

### ISSUE THREAD

**Issue by pacocom** [prettier/prettier#8549]
I use `"prettier": "2.0.5"`.
```
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "jsxSingleQuote": false,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "jsxBracketSameLine": true,
  "arrowParens": "always",
  "endOfLine": "lf"
}
```

Error md files: transform **abc\_def\_cde**. Need to conserve _ inside of **
I don't want (cursive)
  _a_
I want
  \_a\_

Example:
1- The good code;
`There is also a metric called **spark\_read\_valid** to check how many records were successfully processed and **spark\_records\_written** to know how many records were written to datasource.`
![image](https://user-images.githubusercontent.com/7735329/84485352-53430c00-ac9c-11ea-800b-e96c1d13ab84.png)

2- After prettier this file;
`There is also a metric called **spark_read_valid** to check how many records were successfully processed and **spark_records_written** to know how many records were written to datasource.`
![image](https://user-images.githubusercontent.com/7735329/84485399-62c25500-ac9c-11ea-8249-934f7ed7684e.png)

3- If I try to add more escapes:
`There is also a metric called **spark\\\_read\\\_valid** to check how many records were successfully processed and **spark\\\_records\\\_written** to know how many records were written to datasource.`
![image](https://user-images.githubusercontent.com/7735329/84485488-81285080-ac9c-11ea-995a-33c11a349069.png)

I want first case but appliying prettier.

Thanks.

**Comment by thorn0** [comment]
@pacocom Work is currently underway to update the Markdown parser that Prettier uses. See #8140. Could you please check if it fixes your issue?

**Comment by thorn0** [comment]
Also, what Markdown renderer do you use?

**Comment by pacocom** [comment]
@thorn0 thank for the quick response:

According to:

https://www.gatsbyjs.org/packages/gatsby-transformer-remark/ use http://remark.js.org/
```
    "gatsby": "2.23.3",
    "gatsby-remark-autolink-headers": "2.3.5",
    "gatsby-remark-copy-linked-files": "2.3.5",
    "gatsby-remark-external-links": "0.0.4",
    "gatsby-remark-images": "3.3.10",
    "gatsby-remark-link-rewrite": "0.2.1",
    "gatsby-remark-prismjs": "3.5.4",
    "gatsby-remark-relative-images": "0.3.0",
    "gatsby-remark-responsive-iframe": "2.4.5",
    "gatsby-remark-smartypants": "2.3.4",
    "gatsby-transformer-remark": "2.8.15",
```

Thanks!

**Comment by thorn0** [comment]
This seems to be a problem with your Markdown processing/rendering pipeline. Underscores shouldn't be interpreted as emphasis in this position. See https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis
