### ISSUE TITLE
Prettier markdown doesn't added blank space after # 

### ISSUE THREAD

**Issue by pacocom** [prettier/prettier#8550]
Prettier doesn't add blank space between # and title, example:

before prettier:
`#Title`

now: 
`#Title`

after prettier should be:
`# Title`

Thanks!

**Comment by evilebottnawi** [comment]
Please use the issue template, otherwise it will be closed

**Comment by thorn0** [comment]
[Works as intended](https://spec.commonmark.org/dingus/?text=%5Bfoo%5D%20%5Bbar%5D%0A%0A%5Bbar%5D%3A%20%2Furl%20%22title%22%0A)

Your Markdown renderer seems to be really non-standard.

If you're going to open new issues about it, _please_:

1. use the issue template and the playground to reproduce the issue;
2. specify as many details as possible about your Markdown renderer, including steps to reproduce the issue using that renderer (e.g. a sample repo).
