### ISSUE TITLE
CSS formatting breaks line too early (VS Code)

### ISSUE THREAD

**Issue by yossidagan** [prettier/prettier#8558]
I have an inline CSS line with a variable that looks like this :

`.popupSubmit {background: #{{ generic_color_10 }};color: #fff; border-color: #fff;}`

I'm formatting it with Prettier, but the result is broken

```
.popupSubmit {
    background: #{{ generic_color_10 }
}
;
color: #fff;
border-color: #fff;

}
```

When it should look like this 

```
.popupSubmit {
background: #{{ generic_color_10 }}; 
color: #fff;
border-color: #fff;

}
```
How can I edit the formatter settings to fix this?

**Comment by evilebottnawi** [comment]
Sorry, it is non standard syntax and we can't parse it, we support sass/less/css, what is this syntax?

**Comment by yossidagan** [comment]
Sorry for the delay. This is used in a legacy system in my current workplace 
so I thought maybe there is some solution using Prettier. 
Thanks anyways
