### ISSUE TITLE
Why isn't it possible to keep prettier from adding empty line to my files?!

### ISSUE THREAD

**Issue by SassNinja** [prettier/prettier#8559]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAHAThAIwBs4BbTAXkwB0QBJTAE2gHIsB3AQyk8zTjiZumMthgBPTEQCWUQZywwAFoISNMEAGaZSkzdJIBCWgG4QAGhAQx09MlCdc+dgAVHCNMhCciXcZ8sCXE4wAGs4GABlbBDZAHNkGFwAVzhLJRhSIgB1JWl4NBiwOEiPfOkAN3zxLzA0AJBZflwYF2C40k5kTR9+SwArNAAPACFgsIjIzlI4ABlZOG7etJBBocj4kgBFZIh4JaI+kBjcZq8CTgI4Igtj3FkYbOlGZWQADgAGSzwIfmzg7BePBwZoVRaWACOu3gbWsnhQnDQAFo5HBGGjbrg4FDpFi2pwOl0kD1Dit+KRpIkUmTNnAdntFsTlpYYJcni8lMgAEws4IGeIAYQgpE6XhBAFZbsl+AAVS7wklHCqpOhQdGwSJge5iACCasiEhIB34AF8TUA)

**Input:**

```jsx
const problem = "I don't wana see an empty line at the end of my file!";
```

**Output:**

```jsx
const problem = "I don't wana see an empty line at the end of my file!";\n
```

**Expected behavior:**

I expect prettier considers my `.editorconfig` file or at least provides an option to turn this behavior off.

I've already found an old issue about this problem:
https://github.com/prettier/prettier/issues/6360

However I can't understand why prettier is such arrogant, assuming its rules are the only valid ones.
I mean I can accept there are some requirements for a consistent logic and the  easy-to-use philosophy.

But I can't except a tool prohibits me to decide whether I wanna have an empty line at the end of each file or not. And I can't believe it's that much work to add some more options so people who are not happy with the default behavior may change it.

I've noticed there are some discussions about making prettier more extensible (via plugin system etc.) which I like
https://github.com/prettier/prettier/issues/8507#issuecomment-640628043
though that's much more that I expect.

I only want the existing prettier rules to be toggleable so I don't get an empty line in each file that's formatted by prettier.

May anyone (from the core team) tell me if that's gonna happen in near future?
Otherwise I'm forced to completely throw away prettier because it's more than annoying.

**Comment by j-f1** [comment]
As specified in our option philosophy, we don’t want to add more options: https://prettier.io/docs/en/option-philosophy.html

> However I can't understand why prettier is such arrogant, assuming its rules are the only valid ones.

I don’t think that’s our stance. It’s more that the rules Prettier follows result in readable code in most cases, and the benefits obtained by not having to think about code formatting at all outweigh the (temporary) readability costs of not following your particular preference.

**Comment by SassNinja** [comment]
@j-f1 thanks for the clear words!

Unfortunately this means we're not going to use prettier any longer in my company at least not this restricted version.

> the benefits obtained by not having to think about code formatting at all
or rather the benefits of getting infantilized...
(however I've realized it doesn't make sense to discus this any further)

**Comment by netlander** [comment]
**At least the utility should allow for this behaviour to be disabled even if 99% of devs want an extra line at the end of the file, there might be some good reasons for wanting to disable this default behaviour.**

**Comment by evilebottnawi** [comment]
https://prettier.io/docs/en/option-philosophy.html

We don't want to support an option(s). No problems with one empty line at the end of file
