### ISSUE TITLE
Support prettier-ignore comment for specific rule

### ISSUE THREAD

**Issue by nguyenxndaidev** [prettier/prettier#8572]
How can I set `// prettier-ignore` for a rule but not for others?

**Comment by evilebottnawi** [comment]
Thanks, we don't need it, also we don't have rules, please read https://github.com/prettier/prettier/issues/8432

**Comment by nguyenxndaidev** [comment]
I actually mean **options** (ex. singleQuote), so I updated the title and description. Could we open the issue again?

**Comment by fisker** [comment]
What do you mean option? A option called `prettierIgnore`?

**Comment by thorn0** [comment]
@nguyenxndaidev Did you read #8432? Is my explanation really there really that bad?

**Comment by nguyenxndaidev** [comment]
> What do you mean option?

@fisker: I mean all options in this page: https://prettier.io/docs/en/options.html
> Prettier ships with a handful of customizable format options, usable in both the CLI and API.

---

@thorn0: Sorry, I read your comment again, but I still wonder if the idea of `// prettier-ignore` could be stolen or improved somehow to adapt some special situations.

`// prettier-ignore` is mentioned in this page: https://prettier.io/docs/en/ignore.html#javascript
> A JavaScript comment of `// prettier-ignore` will exclude the next node in the abstract syntax tree from formatting.

```
matrix(
  1, 0, 0,
  0, 1, 0,
  0, 0, 1
);

// prettier-ignore
matrix(
  1, 0, 0,
  0, 1, 0,
  0, 0, 1
);
```
will be transformed to:
```
matrix(1, 0, 0, 0, 1, 0, 0, 0, 1);

// prettier-ignore
matrix(
  1, 0, 0,
  0, 1, 0,
  0, 0, 1
);
```

---

Let me take another example, where I would like to have an improvement.

I have a configuration file `.prettierrc.json`
```
{
  "printWidth": 100,
  "singleQuote": true
}
```

And my code
```
matrix1(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);

// prettier-ignore
matrix2(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);
```

will be formatted like this:
```
matrix1('aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff');

// prettier-ignore
matrix2(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);
```

But I would like to have something like this:
```
matrix1('aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff');

matrix2(
  'aaa', 'bbb', 'ccc',
  'ddd', 'eee', 'fff'
);
```

or even better, like this:
```
matrix1('aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff');

matrix2(
  'aaa',
  'bbb',
  'ccc',
  'ddd',
  'eee',
  'fff'
);
```

My original idea when create this issue was to improve the implemented feature `// prettier-ignore` to only ignore the `printWidth: 100` option.

But now, I think it won't work because even if the option is ignore, the default option `printWidth: 80` will be used.

So my next question is that, can we overwrite the current option `printWidth: 100` (or even overwrite multiple options) for a node or a range of nodes?

What do you think, if we have something like this?
```
// prettier-overwrite: {printWidth: 10}
matrix1(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);

// prettier-overwrite: {printWidth: 15}
matrix2(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);

// prettier-overwrite-start[anyname]: {printWidth: 25}
matrix3(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);

matrix4(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);
// prettier-overwrite-end[anyname]
```
is translated to:
```
// prettier-overwrite: {printWidth: 10}
matrix1(
  'aaa',
  'bbb',
  'ccc',
  'ddd',
  'eee',
  'fff'
);

// prettier-overwrite: {printWidth: 15}
matrix2(
  'aaa', 'bbb',
  'ccc', 'ddd',
  'eee', 'fff'
);

// prettier-overwrite-start[anyname]: {printWidth: 25}
matrix3(
  'aaa', 'bbb', 'ccc',
  'ddd', 'eee', 'fff'
);

matrix4(
  'aaa', 'bbb', 'ccc',
  'ddd', 'eee', 'fff'
);
// prettier-overwrite-end[anyname]
```

**Comment by fisker** [comment]
So, inline config? Nothing related to `prettier-ignore`.

**Comment by nguyenxndaidev** [comment]
> So, inline config? Nothing related to `prettier-ignore`.

@fisker thanks for your reply. As I mentioned, it was my original idea but after some thoughts it won't work.
I created https://github.com/prettier/prettier/issues/8589 for the inline config support.
