### ISSUE TITLE
`getFileInfo()` should try to resolve config by default

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8581]
[`getFileInfo()`](https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath--options) returns `ignored` and `inferredParser`, it accepts a `resolveConfig` option, it's default to `false`, I think it's more reasonable to set default to `true`, or even remove this option and always to `true`.

Ref: https://github.com/prettier/prettier/pull/8551#issuecomment-645225864

**Comment by ntotten** [comment]
Agreed. I set this to true always in the VS Code extension. https://github.com/prettier/prettier-vscode/blob/main/src/PrettierEditService.ts#L262

**Comment by fisker** [comment]
Should we consider this bugfix or breaking change?

**Comment by thorn0** [comment]
The current default value is in the [docs](https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath--options):

> When setting options.resolveConfig (boolean, default false),

So it's a breaking change.

**Comment by fisker** [comment]
Fixed by #14108
