### ISSUE TITLE
Move `final new line` insertion to core

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8582]
Currently, we insert the final new line on each printer, 3rd party plugins need insert it too.

For embed print, normally this new line is not kept, [1](https://github.com/prettier/prettier/blob/fbf0beb716fcab954cb03c43357cd5b34f072fc0/src/language-js/embed.js#L197) [2](https://github.com/prettier/prettier/blob/fbf0beb716fcab954cb03c43357cd5b34f072fc0/src/language-js/embed.js#L249) [3](https://github.com/prettier/prettier/blob/fbf0beb716fcab954cb03c43357cd5b34f072fc0/src/language-js/embed.js#L110) [4](https://github.com/prettier/prettier/blob/fbf0beb716fcab954cb03c43357cd5b34f072fc0/src/language-html/printer-html.js#L92).

If we move this to `core.format`, should make things easier.

To make this change none breaking, we can call `stripTrailingHardline` first in `core.format`.

Question: Is there language can't insert the final new line? If not, plugins should not be able to prevent this behavior, if there is, how to process?

[Movitation](https://github.com/prettier/prettier/pull/8465#issuecomment-645273859)

**Comment by evilebottnawi** [comment]
For example - newline in `PHP` can break code:
```php
<span><?php echo 'Hello world!'; ?></span>
```

This part can be included in any part of templates so `newline` can create unnecessary space in generated HTML, not sure it is really good idea, manually adding newline give more control.

**Comment by fisker** [comment]
In your case, is it `php-in-html` or `html-in-php`? Or just `php` plugin.

**Comment by evilebottnawi** [comment]
It is more `php-in-html` https://www.php.net/manual/en/faq.html.php, but it is possible to do `html-in-html`, it is not embedded, it is part of language

**Comment by fisker** [comment]
If it's `php-in-html`, shouldn't this easier for `php` plugin? `php` plugin don't need add `\n`.  

If `php` decide not to add `\n`, `html` can still add `\n`(html controls how to print it, but it won't).
If `php` decide to add `\n`, `html` will remove that `stripTrailingHardline`, so the `\n` will kept.

The `core.format` don't care about `embed`, only final doc, right?

If we add `php-in-html` support.

```html
<script>
var foo = '<?php echo $foo;?>';
</script>
```

We probably won't pass `<?php echo $foo;?>` to `php`, only `echo $foo;` right? If `php` returns `echo $foo;\n`, is still in `php` block, the `\n` won't print in html, right?


```html
<script>
var foo = '<?php echo $foo;
?>';
</script>
```

This valid?

**Comment by evilebottnawi** [comment]
it's not really `php-in-html` or `html-in-php`, it is mix of PHP, HTML, CSS, JS and any other stuff, adding any new characters potential unsafe

PHP have own parser for this cases, so when it is possible and safe we want to handle them as `embedded`, if it is not safe, we print them as is. All of this is very strange, but that’s how PHP works.

Also - don't forget about plugin developers, some of them potential can create plugin which avoid inserting newline (for preferred style or something else).

**Comment by fisker** [comment]
> Also - don't forget about plugin developers, some of them potential can create plugin which avoid inserting newline (for preferred style or something else).

I've considered this, need investigate, and @thorn0 [post](https://github.com/prettier/prettier/pull/8465#issuecomment-645289877)

> 3rd party plugins should behave the same way the builtin plugins do

**Comment by fisker** [comment]
> it's not really php-in-html or html-in-php, it is mix of PHP, HTML, CSS, JS and any other stuff, adding any new characters potential unsafe.
>
> PHP have own parser for this cases, so when it is possible and safe we want to handle them as embedded, if it is not safe, we print them as is. All of this is very strange, but that’s how PHP works.

I know how PHP works.

For example, you want use `embedded` for style

```php
<?php
// php code
?>
<style>
a {color: <?php echo $color;?>;
}
</style>
<?php
// php code
```

You will pass

```css
a {color: __PHP_PLACEHOLDER__;
}
```

to `css`, it will return 


```css
a {
  color: __PHP_PLACEHOLDER__;
}
<EOL>
```
back, you might want remove the `\n` too.

If we do this will make it easier, because the `css` printer won't add `\n`(because it will not call `core.format()`, correct if I'm wrong), the `php` plugin decided add `\n` or not.

**Comment by evilebottnawi** [comment]
@fisker Please read carefully, repeat:

**span.php**

```php
<span><?php echo 'Hello world!'; ?></span>
```

```php
<div><?php include './span.php'; ?></div>
<span><?php include './span.php'; ?>$</span>
```

Adding newline `span.php` output:
```
<div>Hello world!
</div>
<span>Hello world!
$</span>
```

You can see space between `Hello world! $`, but expected `Hello world!$`. We resolve `include` so can't analyze and can't control it.

**Comment by evilebottnawi** [comment]
As I said before PHP plugin can't handle HTML as embedded, it is part of language, it is not feature or something else. You can do even:
```php
<h<?php echo '1'; ?>>Header</h<?php echo '1'; ?>;
```

**Comment by fisker** [comment]
I get your  point now, so  this about the question I asked

> Question: Is there language can't insert the final new line? If not, plugins should not be able to prevent this behavior, if there is, how to process?

So  there it is, we  can't add `\n` in `php`. 

But, we can still do this if we decide to accept, maybe define some flag in printer or something, we can discuss.

---

Lucky, we don't auto insert BOM, that would be a error, calling `header()` will be a error, because content already sent.

BTW, personally, I always add `<?php` (no closing tag)to the end of file, no matter how short this php file is.

**Comment by thorn0** [comment]
@evilebottnawi Are you saying that, unlike what Prettier does for JS and other languages, the PHP plugin currently doesn't always insert the final new line and leaves it up to the user?

**Comment by evilebottnawi** [comment]
@thorn0 And yes and no, we adding newline when it is safe (no HTML at the end), like:

- With newline

```
<?php

class Foo {
  // Code
}

```

- Keep as is (no touch)

**without-newline.php**

```php
<h1><?php echo 'Hello world!'; ?></h1>
```

**with-newline.php**

```php
<h1><?php echo 'Hello world!'; ?></h1>

```

**Comment by thorn0** [comment]
I see. This issue is a no-go then, closing.

**Comment by fisker** [comment]
Do you think we should handle string in `stripTrailingHardline`?
