### ISSUE TITLE
Prettier formats handlebars components incorrectly inside html tag

### ISSUE THREAD

**Issue by Drakeoon** [prettier/prettier#8584]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UABEcMAM4AWAhgE5zoD0mUADgK4wC0kAtq9AQwiAG2oAjOCIC8+EABVKcIgGEI-QbDlFs1EeziyQ6OOTC1MrGJmjbM5cgen3HcAL5vCJL6Qo16TCwc3HwCUEJEvBD00qy0EKzkRHDYCNJR9KISUkaKymoa4VogOnpOciZmFlY2UHYOTi4GHoSojFh4IAA0IAnW0OTIoHTxAO4ACnQIgyjU2BCY6N0g4rTUYADWcDAAyqzrLADmyDC0Bj2UMLwiAOqUmPDk+2BwO9MPOA8AnsjgDssschwWgwcZrQ68ajIABmeiBPQAVuQAB4AITWm22O2ovDgABkWHAYXC4IiUTsjiI4ABFdgQeDEkTwkD7WhA2i-Q4iTC8XEcnpxFgwG6LGCUZAADgADAL4kCbmtWL84qZgallgBHOnwMEJGYgajkLjhBgMZb0LWYehg6gQqFIWFM0kgIG8TAnM7O8iUmnaokOkk9GASEXoMXIABMQbWmG5UEOBUhvyggmW7CB8gkM0dzOwBgAklATLAduZLDAAIJFnYwL5UxlAjxAA)
```sh
--arrow-parens avoid
--parser glimmer
--trailing-comma none
```

**Input:**
```hbs
<div>
  {{shared/input-component label="The Component" value="description" issue=issue}}
  
  {{shared/input-component more=props even=more label="The Component" value="description" issue=issue}}
</div>
```

**Output:**
```hbs
<div>
  {{
    shared/input-component label="The Component" value="description" issue=issue
  }}

  {{
    shared/input-component
    more=props
    even=more
    label="The Component"
    value="description"
    issue=issue
  }}
</div>
```

**Expected behavior:**
```hbs
<div>
  {{shared/input-component label="The Component" value="description" issue=issue}}

  {{shared/input-component
    more=props
    even=more
    label="The Component"
    value="description"
    issue=issue
  }}
</div>
```

The issue only appears to happen when having an html tag wrapping Ember components, [here's the example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgGcAWBDATnAEwHoBLKABwFcYBaSAW3OgRgAIAbbAIznYF4AOiAAqmOKwDCERs1hDWAN2ztKcQSAJx0YXCXIwS0eSXTpVfE2bgBfawKitW9tFjyFSFanWlMoLVvQQ+HzkuBDk6KxwCgh8gfgc3LzqouJSMn5yIIrK5kKa2rr6hlDGpuaWqrb2IAA0IOEG0OjIoHhhAO4ACm5QLSjYChAkBHUgXLjYYADWcDAAyuRTZADmyDC4qvWYMPTsAOqYJPDoS2Bw8wjoxyQKxwCeyOCmY2TocLgwXZMr9NjIADNlO96gArdAADwAQpMZnN5th6HAADJkOCA4FwMGQ+ardhwACKlAg8Ax7BBICWuHeuCeK3YJHoSNp9VCZBg+xGMEwyAAHAAGVlhd77SbkJ6hLQfGJjACOxPg33C-RA2HQND8hEIY3w8pI+G+2F+-yQQPJWJA73oJHWmwt1yg9MJCvRpsx9Rg3E5BG5yAATB7JiQGY70n8nlBmGNKO9hNx+maKQpVABJKCaWDzHR6GAAQXT8xg93xZPetiAA) of prettier working correctly after stripping `<div>` tag

**Comment by evilebottnawi** [comment]
For me current output is readable. Why do you think result in expected is better?

**Comment by 3runo** [comment]
> For me current output is readable. Why do you think result in expected is better?

This should not be based on personal information. The parser is breaking the **init** and **ending** of the components for no reason.

It would be the same of

`<ReactComponent prop1=1 prop2=2 prop3=3 />`

being formatted like

```
<
ReactComponent prop1=1 prop2=2 prop3=3
/>
```

**Comment by PoslinskiNet** [comment]
It's funny because if we don't wrap it as a first ancestor with HTML element, then it works as expected. With HTML element it behaves oddly. Funny thing - `vue` formatter works well in this case (for Handlebars).

**Comment by Drakeoon** [comment]
@evilebottnawi Well, to me the main reasons to follow the expected output would be:
1. VSCode does not recognize the current output as any form of component when using Handlebars language
![image](https://user-images.githubusercontent.com/24693481/85004566-ffcb3500-b157-11ea-9ded-7290921ab2da.png)

2. Ember guides [use the same formatting style](https://guides.emberjs.com/v3.4.0/components/passing-properties-to-a-component/), which leads to the majority of Ember projects following the expected output style
3. It looks more like a bug than an intention, because if the element is not wrapped in an html tag it behaves just fine

Although I understand you guys provide a limited support to the handlebars and it might be outside of the scope

**Comment by mikoscz** [comment]
https://github.com/jgwhite/prettier/issues/1#issuecomment-607273019
