### ISSUE TITLE
Support inline config to overwrite option(s) for a node or range of nodes

### ISSUE THREAD

**Issue by nguyenxndaidev** [prettier/prettier#8589]
I have a configuration file `.prettierrc.json`
```
{
  "printWidth": 100,
  "singleQuote": true
}
```

And my code
```
matrix1(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);

// prettier-ignore
matrix2(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);
```

will be formatted like this:
```
matrix1('aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff');

// prettier-ignore
matrix2(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);
```

But I would like to have something like this:
```
matrix1('aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff');

matrix2(
  'aaa', 'bbb', 'ccc',
  'ddd', 'eee', 'fff'
);
```

or even better, like this:
```
matrix1('aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff');

matrix2(
  'aaa',
  'bbb',
  'ccc',
  'ddd',
  'eee',
  'fff'
);
```

Can we overwrite the current option `printWidth: 100` (or even overwrite multiple options) for a node or a range of nodes?

What do you think, if we have something like this?
```
// prettier-overwrite: {printWidth: 10}
matrix1(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);

// prettier-overwrite: {printWidth: 15}
matrix2(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);

// prettier-overwrite-start[anyname]: {printWidth: 25}
matrix3(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);

matrix4(
  "aaa", "bbb", "ccc",
  "ddd", "eee", "fff"
);
// prettier-overwrite-end[anyname]
```
is translated to:
```
// prettier-overwrite: {printWidth: 10}
matrix1(
  'aaa',
  'bbb',
  'ccc',
  'ddd',
  'eee',
  'fff'
);

// prettier-overwrite: {printWidth: 15}
matrix2(
  'aaa', 'bbb',
  'ccc', 'ddd',
  'eee', 'fff'
);

// prettier-overwrite-start[anyname]: {printWidth: 25}
matrix3(
  'aaa', 'bbb', 'ccc',
  'ddd', 'eee', 'fff'
);

matrix4(
  'aaa', 'bbb', 'ccc',
  'ddd', 'eee', 'fff'
);
// prettier-overwrite-end[anyname]
```

**Comment by evilebottnawi** [comment]
:-1: 

/cc @prettier/core

**Comment by fisker** [comment]
`printWidth` seem impossible to be config during print, but maybe other options? 

Like I don't want `babel` to format my html `<script>`, but only script in html, even https://github.com/prettier/prettier/issues/5378 can't do this.

I can

```html
<!-- prettier {"parser": "meriyah"} -->
<script></script>
```

**Comment by boyenn** [comment]
I hate that it would allow  "Add `// prettier-overwrite: {someOption: someValue}` here to format this more along the way I like it" comments during review.

**Comment by fisker** [comment]
> I hate that it would allow "Add `// prettier-overwrite: {someOption: someValue}` here to format this more along the way I like it" comments during review.

That's a  good  one.

**Comment by thorn0** [comment]
:-1: Ignore comments are an escape hatch, not a feature we want to extend.

If you really want to format something with a different set of options, it's possible: extract it to a separate file and use `overrides` in the configuration file.

**Comment by evilebottnawi** [comment]
@nguyenxndaidev sorry, we don't want to have it in prettier, you can read solutions how to achieve it above
