### ISSUE TITLE
Add parenthesis around AssignmentExpression

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#861]
On the react codebase, parenthesis are added around `=` as expression in order to show that it is not a comparison:

```js
while ((rendered = component._renderedComponent)) {
```

I really like this idea.

**Comment by daltones** [comment]
Just to enforce this, I've always wrote code this way and I guess that's a very common trick. The good old JSHint already suggested people to do this [here](http://jshint.com/docs/options/#boss).

Good!

**Comment by vjeux** [comment]
I just sent #862 to implement it.
