### ISSUE TITLE
prettier breaks tsx

### ISSUE THREAD

**Issue by vedantroy** [prettier/prettier#8610]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAlOBDMMAiB5AWQDoAnBAEzhIAoAdKAAgYB50sYiBlGEgS2wIRKAPnpMmzAEIkIAdwDOVVBACu8EqMbiJAQQAOegPSbtzQ9LmKSytVRMtDbbFx78YgkQBoxDchDAqALYIHADmcDAAogA2cMGwkgCeAJLkdCAyEDC0IACU9LkA3CCeIBB6MLzQ8sigGCQysgAK9Qg1KBjRshiJNaUARiRYANYRnHpYvFChyDwqcKUAFjCB0QDqi7zw8hNgcJxtW7wAbluJyODyfSBTVjBNQ6GBGMgAZp2KpQBW8gAe0iMxhhggAZKZwN4fBYgH6-ThTUKxACKKiyEKQ72inxAExIVgu-Qw-Tg0RKOL4sDWvHIMEWyAAHAAGUp6GSKNZDPQXVlwKzHCGlACOqPgD3K7RAGHkAFooHA4JRyGSyMLeGQHhgni8MVDSopArxZiR5nqEciRejMdiYESqTS6UgAEylHgYXjRBEAYQggWeF15AFYySpFAAVIntK3Q47zZJQSiwThgPgVHTx7iJWKQrFwAC+uaAA)
```sh
--parser babel
```

**Input:**
```jsx
ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <App/>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById("root")
);
```

**Output:**
```jsx
ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById("root")
);

```

**Expected behavior:**
There should not be a space in `<App />`, this causes a syntax error in the tsx. Specifically, when using Create React App, I get the error: `"Parsing error: '>' expected` on the line with the `<App />` component.

**Comment by thorn0** [comment]
This is valid TSX. It's something else, not related to Prettier, that causes that error.
