### ISSUE TITLE
Feature request: vertical alignment

### ISSUE THREAD

**Issue by axetroy** [prettier/prettier#8611]
I know that this issue has been discussed many times. #350 #1622

But I think it is still worth considering

I hope the prettier team can listen more to the community

### Why Javascript/Typescript code is not so comfortable to read

Not align:

```ts
const bike: Record<string|number> = {
    wheelSize: 16, // The size of the wheel. Minimum value is 1
    topTubeLength: 24.5, // The length of top tube. Minimum value is 1
    manufacturer: 'Brompton' // The name of manufacturer. should not be null
};
```

Aligned:

```ts
const bike: Record<string|number> = {
    wheelSize:     16,			// The size of the wheel. Minimum value is 1
    topTubeLength: 24.5,       	// The length of top tube. Minimum value is 1
    manufacturer:  'Brompton'  	// The name of manufacturer. should not be null
};
```

After aligning them, it will become `real prettier`

It will be more comfortable to read

### Success Case

I have to admit that Golang's code is very easy to read and very comfortable

Because it implements a little bit of "code that is easy to read with developers"

```go
type Button struct {
	ID   string `json:"id"`             // The ID of the button
	Text string `json:"text"`           // The text of the button. length < 32 bit
	Icon string `json:"icon,omitempty"` // The Icon of the button
	Url  string `json:"url,omitempty"`  // The url link of the button when click and go
}
```

### Proposal

Is it possible to add an option for alignment

- Align property/value of the object

```ts
const man = {
  name: 	"nick",
  age: 		18,
  address: "your address"
}
```

- Align variable declaration

```ts
var name 	= "nick"
var age 	= 18
var address = "your address"
```

- Align comment of lines

```ts
const a = 123 	// comment 1
var b 	= 231 	// comment 2
let c 	= "abc" // comment 3
```

- Align interface declaration for Typescript

```ts
interface People {
  name: 	string
  age: 		number
  address: 	string
}
```

### Concern

After the alignment, the file size becomes larger, but this is not our concern

These spaces can be deleted during the build-ugly stage

I'm looking forward to this feature.

It makes me got a better mood to read `javascript/typescript` code

If agreed then 👍

**Comment by thorn0** [comment]
Sorry, we won't revisit our decision on this.
