### ISSUE TITLE
Work after updating markdown parser

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#8630]
To do after merging:

- [x] open a new issue for whitespace in inline code  - https://github.com/prettier/prettier/pull/8140#discussion_r421797658
  New issue #8655
- [x] go through [all the open Markdown-related issues](https://github.com/prettier/prettier/issues?q=is%3Aissue+is%3Aopen+label%3Alang%3Amarkdown) to check whether this PR fixed them and add tests
  - [x] #3223
- [x] open an issue about [these failed edge autolink cases](https://github.com/prettier/prettier/runs/730525149#step:6:3911) 
  New issue #8654
- [x] make sure that we have tests for the fixed issues:
  - [x] #3753
  - [x] #4122
  - [x] #4306
  - [x] #4369
  - [x] #5921
  - [x] #6177
  - [x] #6180
  - [x] #8226
  - [x] #8364

_Originally posted by @thorn0 in https://github.com/prettier/prettier/pull/8140#issuecomment-648058515_

[#8140 Playground](https://deploy-preview-8140--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQDZUkCeRGARmSWAGs4MAMpZ+uKAHNkMMgFc4GOAFtucACYbNAGRLT5JKXABiEMipIw805CBLyYEdCAAWMFcwDqr3PALiYHAiDH64AG5+7HZgBFwgkgRwZDA0fFKWyABmLEkYAFYEAB4AQnyCwiIkKnA6knDZuUoghUUiklLMcACK8hDwjcx5IOJkSWR2lmQCGtRQLlhkkjBeuBowrsgAHAAMGIsQSV58WHaLcOPhDRgAjn3wadiM9gQAtFBwmpouZHB3uL80kZMkgckNmkkVLhZAoIR0ur1+g1QU0MDASNxVutNkgAExovi4ZgdADCEBUIJAFwArC55EkACoYxhg4bhRQASSg2lgIjASxwAEFuSIYOwuoMkgBfKVAA)

**Comment by sosukesuzuki** [comment]
All todos has done. Can we close this?
