### ISSUE TITLE
`prettier .` shouldn't include `*.handlebars`

### ISSUE THREAD

**Issue by czerwinskilukasz1** [prettier/prettier#8631]
Running `prettier --check .` for a folder with an unsupported file type fails with errors saying `No parser could be inferred for file`, while `prettier --write .` finishes successfully in my project.

Please note that issue https://github.com/prettier/prettier/issues/2691 resolved the problem for `--write` option, but `prettier --check` still works the old way.

**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: CLI
- Operating System: macOS

**Steps to reproduce:**

Create a folder with a .handlebars file (or probably virtually any file extension which is not supported) and run `prettier --check .`

**Expected behavior:**
prettier finishes successfully

**Actual behavior:**
prettier finishes with an error:
`
src/playground/src/views/main.handlebars[error] No parser could be inferred for file: src/playground/src/views/main.handlebars
`

**Comment by thorn0** [comment]
Seems to be specific to the `handlebars` extension. I can't reproduce this with other extensions.

**Comment by thorn0** [comment]
The `glimmer` parser is experimental (alpha). It doesn't work with `.handlebars` files out of the box and needs to be specified explicitly. However, `.handlebars` files are still included in the big glob that Prettier uses to find supported files, which is a bug.
