### ISSUE TITLE
unnecessary parentheses around await with type assertion

### ISSUE THREAD

**Issue by mfulton26** [prettier/prettier#8632]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOBDAJgKQM7QDKAnlGABQBmAlgDZwAKGMAFgJQAEGeHAIsxgDcAHSgYA7hmowO6bPmhU6jZuy49+MIaJAAaEBAAOMatDzJQGVKgjim6KOZQZak4uf0AjVBjABrOBhCQ19qKABzZBhUAFc4fRYYAFtaAHUWaTg8ELA4QgQ8aWoAN2liZHA8DxAwvDhUGAYfcKSMZEoXOv0AKzwADwAhH39AwgwkuAAZMLh2zviQXr7CMPD6AEUYiHg52i6QENQ61ArPDE84WgBaGGrDVDCYVOosVmQADgAGfXuIOtSfIYKvcsvVirN9ABHLbwJpGJwgbhXKBwOBYNF6NBwaHUdBNDAtNpIDp7BZ1JLUKKxMmrDYw2bE+b6LSeZ6vFjIABMzJ8dFWAGEIElWhUsgBWTExOoAFXOThJ+2KcQAklB0bBCGAHsYAIJqwgwYj0XZ1AC+pqAA)
```sh
--parser babel-ts
```

**Input:**
```tsx
readJsonSync(filePath) as Data;
await readJson(filePath) as Data;

```

**Output:**
```tsx
readJsonSync(filePath) as Data;
(await readJson(filePath)) as Data;

```

**Expected behavior:**
```tsx
readJsonSync(filePath) as Data;
await readJson(filePath) as Data;

```

From what I can tell the parentheses around `await readJson(filePath)` are unnecessary. 

Furthermore doing a type assertion on `readJson(filePath)` requires additional parentheses thereby clarifying even more that the usage of the parentheses to assert the type of an awaited value is not necessary:

```tsx
await (readJson(filePath) as Promise<Data>);

```

also of note is that Prettier doesn't put parentheses around the alternative form of type assertions:

```tsx
<Data>await readJson(filePath);
```

I propose not adding parentheses to statements like `await readJson(filePath) as Data;`

**Comment by thorn0** [comment]
Various cases of parentheses around `await` are discussed in #3089. The output is unlikely to change as many people think these parentheses aid readability.
