### ISSUE TITLE
Handlebars: newline in an attribute incorrectly rendered as `[object Object]`

### ISSUE THREAD

**Issue by kangax** [prettier/prettier#8648]
As reported in https://github.com/jgwhite/prettier/issues/1#issuecomment-640699531

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAYhCACAAgQwCcBzAXgB0RypKB6APhABoQIAHGAS2gGdlQihCAHcACkQR8U+ADbD8ATz4sARoXxgA1nBgBlNhs5RiyGIQCucFgAsYAWxkB1a53g8DYOLsmvOAN1cFZHAeZRAjHjhCGFF1Yjt8ZAAzWUiWACseAA8AIXUtHV18OzgAGSM4ZNSrEEys3SNiGTgARXMIeCqZNJADQkjCYKbOOxLBljZCIxhHTgATGGtkAA4ABgmhSMd1NmDJuAG-SpYAR3b4WPYpEHweAFooODg55+YQQjgzzg-Y-HjEpApbo1SJ2TimCwgxrNNodSqA6osGD4FSzBZLJAAJiR6k4MkaAGEIKMASADgBWN7mSIAFRRUiBPT8lgAklAXrBdGAphwAILs3QwBTNLqRAC+YqAA)

**Input:**

```
<Foo arg="
"/>
```

**Output:**

```
<Foo arg="[object Object]" />
```

**Expected behavior:**

```
<Foo arg="
" />
```

**Comment by jelhan** [comment]
Seems to be fixed in Prettier 2.2.0. At least the Playground link is showing expected output for me.

**Comment by kangax** [comment]
Interesting, ok, closing. 

@fisker do you know why this doesn't happen anymore if my PR hasn't gone in yet?

**Comment by fisker** [comment]
I think this not resolved

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAYhCACMAbAQwGciBeAHRHKkoHoA+EAGhAgAcYBLaI5UAgE4CIAdwAKghLxQE8IggE9eLAEYCCYANZwYAZTYbOUAObIYAgK5wWcALYq4AE0dOAMgRMWCxuJgG2CGC4TZBACCxgIZhAACxhbPAB1GM54IgMwOF0pVM4AN1SFULASaKMiOAEYMXVjAOQAM1kKlgArIgAPACF1LR1dAls4VyM4RubrEHaO3SNjPDgARQsIeHG8FpADAQqBUPnOWyG9ljYBIxhEzkcYGOQADgAGU+EKxPU2ULO4XbyxlgAjit4DV2NIwkQALRQOBOJzRARwIGcRE1bz1JBNDaTCq2ThmSw4uYLZarMaYiYsGAEFRXG53JAAJip6k4eDmAGEIEcCKEfgBWaIWCoAFRp0ixmzyVgAklAXLBdGBzhwAILy3QwBQLdYVAC+eqAA)
```sh
--parser glimmer
```

**Input:**
```hbs
<Foo class="
"/>
```

**Output:**
```hbs
<Foo class="[object Object]," />
```
