### ISSUE TITLE
Style tag not supported in HTML?

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#8657]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABMRnAIYAmhJpZAzjAJ45zEsAOcAvASPAAeMAPRgGDfrXr1OxYERkzIOCACckxAMQAmAGwAjAOw6DAbkVKAvpdKoRTVnGlkR6SjUv3MuWiAA0IBCcMACW0AzIoBRqahAA7gAKMQiRKBQ48RTMkYEGahRgANZwMADKnIWhUADmyDBqAK5wgT44AOroofAMlWBwZandoQBu3czI4BIBINUMcGowiQU1WBTIAGYZ84EAVgyCAEIFxaVlFFhwADLVcJvbLSD7gmXVNWwAio0Q8Pc4OyBKmp5mpJgYKAY4DgZpw1NUYO1QlQYOhkAAOAAMgVhEHm7QKnEmsLgIJGd0CAEdvvBlsE0iAKAwALRQOBwKjsmZqOBU0Lc5YUVbrJBbf6PeZYUL1Jrit6fal3EUPQIwCGI5GopA6FUFUI4N4AYQgWDWkxJAFYZo15gAVCFpUUAkbNACSUA5sDKYDhIQAgu6yiw2H95lYrEA)
```sh
--parser babel
```

**Input:**
```jsx
<html>
  <head>
    <style>
      p {
        color: #26b72b;
      }
    </style>
  </head>
  </html>

```

**Output:**
```jsx
SyntaxError: Unexpected token, expected "}" (5:14)
  3 |     <style>
  4 |       p {
> 5 |         color: #26b72b;
    |              ^
  6 |       }
  7 |     </style>
  8 |   </head>
```

**Expected behavior:**
No error.

Reference for style tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style

I don't know what I'm missing... Seems obviously broken and I can't find a single mention of it anywhere?

**Comment by fisker** [comment]
You didn't select parser from left side.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABMRnAIYAmhJpZAzjAJ45zEsAOcAvASPAAeMAPRgGDfrXr1OxYERkzIOCACckxAMQAmAGwAjAOw6DAbkVKAvpdKoRTVnGlkR6SjUv3MuWiAA0IBCcMACW0AzIoBRqahAA7gAKMQiRKBQ48RTMkYEGahRgANZwMADKnIWhUADmyDBqAK5wgT44AOroofAMlWBwZandoQBu3czI4BIBINUMcGowiQU1WBTIAGYZ84EAVgyCAEIFxaVlFFhwADLVcJvbLSD7gmXVNWwAio0Q8Pc4OyBKmp5mpJm0Zpw1NUYO1QlQYOhkAAOAAMgUhEHm7QKnEmkLgIJGd0CAEdvvBlsE0iAKAwALRQOBwKjMmZqOBk0Ls5YUVbrJBbf6PeZYUL1JrCt6fcl3AUPQIwCgGWHwxFIHQKgqhHBvADCECwa0mBIArDNGvMACpKtKCgEjZoASSgLNgZTAUJCAEEXWUWGw-vMrFYgA)
```sh
--parser html
```

**Input:**
```html
<html>
  <head>
    <style type="text/css">
      p {
        color: #26b72b;
      }
    </style>
  </head>
  </html>

```

**Output:**
```html
<html>
  <head>
    <style type="text/css">
      p {
        color: #26b72b;
      }
    </style>
  </head>
</html>

```

**Comment by evilebottnawi** [comment]
@fisker And not required, `type` is optional, without `type` is should be pure CSS
```
<style>
  h1 {color:red;}
  p {color:blue;}
</style>
```

**Comment by evilebottnawi** [comment]
I was wrong, here `--parser babel`, it is invalid parser for `HTML`

**Comment by fisker** [comment]
Hmmm, sorry, I don't know where I got this type attribute...

**Comment by fisker** [comment]
Ah, his playground link has type in code

**Comment by xixixao** [comment]
Thanks! So I got confused by the playground, but I'm actually seeing the same error in VS Code for an `.html` file, so there's something wrong with the prettier extension there (or my config).

**Comment by xixixao** [comment]
Oh, I got it, so here is my actual issue (let me know if it's specific to prettier or the VS Code Prettier extension (by Esben Petersen):

I have "parser" set to "flow" in package.json "prettier" config, because "babel" fails on some of the syntax I have in my files (edge case). This should of course only be used for my js files, not for my html file. Any way to get around this (preferably without writing a custom parser)?

**Comment by fisker** [comment]
https://prettier.io/docs/en/configuration.html
