### ISSUE TITLE
Wrong formatting of EJS file

### ISSUE THREAD

**Issue by kunduarijit** [prettier/prettier#8676]
Without Prettier using EJS its working

![Annotation 2020-06-30 174156](https://user-images.githubusercontent.com/53327173/86124581-07e08880-baf9-11ea-8a78-894b2b7b6fb6.jpg)

But after formatting with ejs, its breaking like this

![Annotation 2020-06-30 174252](https://user-images.githubusercontent.com/53327173/86124680-25aded80-baf9-11ea-87b3-9e3355c17465.jpg)

**Comment by kunduarijit** [comment]
<div class="poster">
    <img src="<%" ="poster" % /> class="img-fluid1" alt="Responsive image">
  </div>

**Comment by fisker** [comment]
EJS is not valid html, Prettier isn't going to add more languages to the core. This should be implemented as a plugin.

**Comment by evilebottnawi** [comment]
We don't support EJS and never support it, you can create plugin for this format https://prettier.io/docs/en/plugins.html
