### ISSUE TITLE
Config through .editorconfig

### ISSUE THREAD

**Issue by blaggacao** [prettier/prettier#8680]
Shamelessly copy the way shfmt is configured:

https://github.com/mvdan/sh#shfmt

```ini
[*.sh]
# like -i=4
indent_style = space
indent_size = 4

shell_variant      = posix # like -ln=posix
binary_next_line   = true  # like -bn
switch_case_indent = true  # like -ci
space_redirects    = true  # like -sr
keep_padding       = true  # like -kp
function_next_line = true  # like -fn

# Ignore the entire "third_party" directory.
[third_party/**]
ignore = true
```

/cc @josephfrazier

Goal: reduce dotfile jungle

**Comment by evilebottnawi** [comment]
Currently, the following EditorConfig properties are supported:

- end_of_line
- indent_style
- indent_size/tab_width
- max_line_length

I think it is enough

**Comment by thorn0** [comment]
Prettier supports EditorConfig, but we need to document this fact better. #8044

**Comment by blaggacao** [comment]
> I think it is enough

That's arguable, but yeah. It might just have been an extreme thought to crush .prettierrc alltogether.
It's just that, tools claiming their own rc files are so much abundand that it eventually grows into a nuisance.

**Comment by evilebottnawi** [comment]
@blaggacao disagree, we can't "crush .prettierrc" because we have more options than .editorconfig

**Comment by blaggacao** [comment]
@evilebottnawi I tend to thing you are right this is not necesary, but technically -for the sake of the purity of the argument - this is how shfmt does it:
```ini
shell_variant      = posix # like -ln=posix
binary_next_line   = true  # like -bn
switch_case_indent = true  # like -ci
space_redirects    = true  # like -sr
keep_padding       = true  # like -kp
function_next_line = true  # like -fn

# Ignore the entire "third_party" directory.
[third_party/**]
ignore = true
```

These are shfmt's options.

**Comment by evilebottnawi** [comment]
We are not `shfmt`, sorry
