### ISSUE TITLE
Intentional align of comments in YAML within Markdown is not respected

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#8690]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdBPAtgGwDpSRYAO0CMSABAIYDuAzgLQCW1WjAThDnJZQMSUAFBzgBHAK7NRAEwCUlKG14QAZpRgALXkVJRyAOgJKscKlgyduvPrbt9BI8VNkKTK9RggSOlXWVhKZih6GGpCOCMoCA4Acyp6OA4ANySeenpgsHsHYQhiGGZoahwFRJS0uAzKGWp6TQAjCGoOGUoY2INKAnRUEAAaEHzC6HpkUBauWgAFFoQxlBLaagwxwYaOajAAazgYAGViLeDY5BgOCThBzRhcAHVNZnh6I7A4ffmn5mSnjGRwDIDEDBcowaabWJYajIVQlRKDABW9AAHgAhTY7Pb7ZQAGWCcBhcKuICRyP2Jx4AEUJBB4IScPCQEcOOV-lCONsZBBaFAgcQOMEYHdmDItMgABwABkG-IgiTum2I-35VSSqSBklpcHB+QWIDqjH0cBkxqBokk0m1EKh9MZiSwzDOF2JmSgsSpNLpSFhDOJYQawtFmmQACZBudqMwcCcAMIQLA2lBVACsQIkiQAKtQGgsfYzkpcAJJQE2wfZgAUFACCJf2MAwPFtcAAvs2gA)
```sh
--parser markdown
```

**Input:**
````markdown
```yml
component: aws-iam-role  # (required) name of the component.
name: my-role            # (required) name of your component instance.
org: serverlessinc       # (optional) serverless dashboard org. 
```
````

**Output:**
````markdown
```yml
component: aws-iam-role # (required) name of the component.
name: my-role # (required) name of your component instance.
org: serverlessinc # (optional) serverless dashboard org.
```

````

**Expected behavior:**

````markdown
```yml
component: aws-iam-role  # (required) name of the component.
name: my-role            # (required) name of your component instance.
org: serverlessinc       # (optional) serverless dashboard org. 
```
````

**Comment by evilebottnawi** [comment]
We don't align comments and value(s) for all languages, it was discussed a lot of time please use search for more information

**Comment by medikoo** [comment]
@evilebottnawi I've used search and didn't find corresponding issue. Can you provide a link to duplicate where it was discussed?
