### ISSUE TITLE
Less: Incorrect formatting of inline comment inside `selector()`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8704]
**Prettier pr-8545**
[Playground link](https://deploy-preview-8545--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEABAzgVwA7YgJxnQAJ04AbOMGAgCgB0pjikAzCMTdAWgDcBLdPwBGlYgHpxxAFT0QAQzmMAlMWCNGAX0YgANCAjYY-aOmSh5+fBADuABUsIzKeeRvyAnmf3D88sADWcDAAytj+-FAA5sgw+Jhw+nAAtsJwACbpGQAy8tGY8lFwAGIEyfIwxtHICpg0eiAAFjDJ5ADqjfzw6OFgcCFOXfwCMB41YOjeIJFkhHZ+UeXIrK5k+gBW6AAeAEJ+gcEh8slw2ZFwy6uJIJtbIZFRlACKmBDwl+RrIOH4szWUkwa2HwkRgbX46RgjWQAA4AAz6YEQMhtPzYGrAuCzXgXfQAR1e8HmhmcCh4UDgGQyDXwcAJ-Fp80KSzYV30ZGS-Fi8WuQmiz0JF1Zn2uMHkwnBkOhSAATPo4vJ+OQHgBhCDJFkgLEAVgaXDgABVxc4ViL9LwEgBJKBZWAhMAgowAQRtIVGlA+ZE0miAA)
```sh
--parser less
```

**Input:**
```less
@supports selector(
  :focus-visible // *"a"
) {

}

```

**Output:**
```less
@supports selector(:focus-visible //   a) {
}

```

**Expected behavior:**

Print the right comment

--- 

Post by @thorn0 https://github.com/prettier/prettier/pull/8545#pullrequestreview-441790582
Possible solution https://github.com/prettier/prettier/pull/8545#issuecomment-653079204

**Comment by boyenn** [comment]
I don't believe this is a bug.

In css, comments seem to not be allowed inside the selector(), see https://jsfiddle.net/5rtf16ak/12/
Less seems to also leave alone the statement when transpiling to css.

**Comment by thorn0** [comment]
@boyenn CSS doesn't support `//` comments, but turns out Less indeed doesn't strip them inside `selector(...)` ([demo](https://jsbin.com/hewizek/1/edit?html,js,console,output)). Might be a bug in Less.

**Comment by fisker** [comment]
Let's ignore the syntax, just try to bring `*` and quotes back?

**Comment by thorn0** [comment]
@fisker Of course, it's better to bring them back, but I think we can ignore this issue for now. Neither Less nor SCSS supports this syntax, so it shouldn't break anyone's code.

**Comment by fisker** [comment]
I'm sending a PR to fix missing characters.
