### ISSUE TITLE
Final newline disappeared

### ISSUE THREAD

**Issue by MortalHappiness** [prettier/prettier#8715]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTARgG4QAaECABxgEt1lRsAnZiAdwAUWE1kRsAG3bYAnnwoAjZtjABrODADKVWbSgBzZDGYBXOBQAWMALaCA6odrw0qsHCW9rtAG7XR-MGgkh1aOMwwnDIaJtjIAGZC-hQAVmgAHgBCMvKKStgmcAAy6nCR0QYg8QlK6hqCcACKuhDwBYIxIKrM-sz8ktiScILkzczqMOa0ACYwhsgAHAAMFFRs-uYyVPzzcG0u+RQAjrXwwdR8KNhoALRQcHAjV33McLu0d8HYoeFIUY1F-ia02npf5UqNTq+XehQoMC6wzGEyQACYITJaIJygBhCAmML8dYAVj6un8ABUukcPk0XPoAJJQa6wJRgAY0ACCNKUMFElQa-gAvtygA)
```sh
--parser babel
```

**Input:**
```jsx
const a = 1;
```

**Output:**
```jsx
const a = 1;
```

**Expected behavior:**
```jsx
const a = 1;
// newline here
```

In playground there will be a final newline in the result, however in my local machine the final newline disappears.
I do use prettier@2.0.5, my machine is arch linux and node version is v12.16.1

**Comment by kachkaev** [comment]
It is likely that your local setup involves a mix of tools and Prettier is not the last used one amongst them. It's impossible to investigate the problem without seeing clear reproduction steps.

**Comment by MortalHappiness** [comment]
I am sure that I do not use mix of tools. The following step can reproduce this behavior.
As root user, create a testuser to prevent use mix of tools
```sh
useradd testuser -m
su - testuser
```
As testuser, use nvm to download nodeJS
```sh
git clone https://github.com/nvm-sh/nvm.git .nvm
cd .nvm
git checkout v0.35.3
. nvm.sh
nvm install --lts=erbium
```
Ensure that I do not use mix of tools
```sh
node -v    # v12.18.2
npm list -g --depth=0    # only npm@6.14.5
```
Do the testing
```sh
echo "const a = 1;" > test.js
cp test.js test1.js
npx prettier@2.0.5 --write test.js    # Prettier should add final newline in test.js
diff test.js test1.js    # Expect they are different, but they are the same.
```

**Comment by bakkot** [comment]
> `echo "const a = 1;" > test.js`

`echo` adds a trailing newline by default. You'd need to use `echo -n` to explicitly omit it. And if you do that you'll see Prettier does in fact add the newline:

```
$ echo -n "const a = 1;" > test.js
$ cp test.js test1.js
$ npx prettier@2.0.5 --write test.j
$ diff test.js test1.js
1c1
< const a = 1;
---
> const a = 1;
\ No newline at end of file
```

**Comment by MortalHappiness** [comment]
Your comprehension of `echo` command is wrong, `echo` add a single line feed at default, so the string will look like
`const a = 1\n`, try this.
```sh
$ echo -n "1" && echo -n "2"      # output 12
```
In this case no line feed at the end of file and Prettier will add a line feed to it.

I provide another test to show that Prettier does not add final new line.
```sh
$ echo -e "const a = 1;\n" > test.js
```
This time the string in `test.js` will be `const a = 1;\n\n`
You can run `cat` command to verify.
```sh
$ cat -n test.js
# output
        1  const a = 1;
        2
```
And then copy the file, run Prettier
```sh
$ cp test.js test1.js
$ npx prettier@2.0.5 --write test.js
```
```sh
$ cat -n test.js
# output
        1  const a = 1;
```
You will see that Prettier remove the final newline.
```sh
$ diff test.js test1.js
1a2
>
```
However in Prettier playground the final newline will not be removed.

**Comment by fisker** [comment]
@MortalHappiness

Can you run this, and post the result?

```console
node -e "require('fs').writeFileSync('test.js', 'const a =2;\n')"
npx prettier@2.0.5 test.js --write
node -p "require('fs').readFileSync('test.js', 'utf8').split(';')"
```

**Comment by MortalHappiness** [comment]
Maybe I better use `final blank line` instead of `final newline`. Final blank line should have two "\n" instead of single "\n".

I have run the command 1 and 3 you provided(without prettier) and get single "\n". But if I run `echo -e "const a=1;\n` and then run the command 3 you provided, I get '\n\n'.
In prettier playground, the final blank line is reserved, which means there are two '\n'. You can try using two '\n' and run prettier again.

**Comment by fisker** [comment]
One `\n` is expected.

**Comment by MortalHappiness** [comment]
If only one '\n' is expected, I think that Prettier playground is a little bit misleading since it outputs a final blank line, which means it has two '\n'.

**Comment by fisker** [comment]
I think this is how editor renders.

One `\n`.

Any difference?

VSCODE

![image](https://user-images.githubusercontent.com/172584/86695866-84b2bb80-c03f-11ea-9900-f78840b9539b.png)

Playground

![image](https://user-images.githubusercontent.com/172584/86695940-95633180-c03f-11ea-9205-caee4f22d79d.png)

**Comment by MortalHappiness** [comment]
That's pretty wierd, single '\n' using `cat` command and in vim editor will only show one line.

**Comment by bakkot** [comment]
>  I think that Prettier playground is a little bit misleading since it outputs a final blank line, which means it has two '\n'.

It does not have two `\n`s. All text areas on the web which end in a single `\n` have a final blank; that blank line represents the `\n`. In my experience this is true of almost all text editors: notepad, sublime, etc all have this behavior. Vim is very much the the odd one out. (I think its behavior is because it assumes _all_ files end in a blank line, and in fact will put one there for you when you save whether you ask for it or not, which means it doesn't need to explicitly represent the blank line.)

**Comment by MortalHappiness** [comment]
> In my experience this is true of almost all text editors: notepad, sublime, etc all have this behavior. Vim is very much the the odd one out.

@bakkot thank you for your reply, I don't know this fun fact before. The behavior of vim and cat command are indeed different from other editors.
