### ISSUE TITLE
Unecessary parentheses around method chaining in return statement when one line is commented out

### ISSUE THREAD

**Issue by darsain** [prettier/prettier#8729]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEATnDOoVAMozECGAtgBQCU+wAOlG9SWVPgM6EwDAAoBBACoAJCgDpBYJhy5dZABxxq4DAG5xCATwAy0AOYiANulM4oAOXramSzjC4B6d-nWbtewyZQ5lY29o7MLiowPlq6+sZmlta2DnROkW7RGrEAJnD8MKKSMrIARug4FjnOANwcAL4gADQgEGq40PzIoDSEhBAA7iK9CF0oNBYDNAZdLaWENGAA1iQUaou2psjU6HAtABYwdBYA6vs48PzrYHAUoxc4OhcGyOD8syC2-PowIgumdBoyFQE2+LQAVvwAB4AIQWy1WjiMtjgwNBexAkKhFE2FjgAEV0BB4GiLGCQOtCN9CK9SjRSnALM0KYRbDATjgcjB9sgABwABhaan63xOCzUr2F+X0emZAEcifA-m0xiAaPwALRQOBwPI5ZnEBU4Yh-GgAoFIEFkjHfOg4baEXYtfi4gmK1GW9EtGD0jlcnlIABM3oWlU2AGEIHRAa98gBWZnob4SeljK3knS7ACSUDysAoYFZ7TEuaoBjxpO+9XqQA)

Prettier adds unnecessary parentheses around method chaining in return statement if one of the lines is commented out. Works fine without the commented line.

**Input:**

```jsx
function returnStream() {
  return src(PATHS.src)
    .pipe(veryLongPluginName())
    // .pipe(veryLongPluginName())
    .pipe(veryLongPluginName())
    .pipe(dest(PATHS.build));
}
```

**Output:**

```jsx
function returnStream() {
  return (
    src(PATHS.src)
      .pipe(veryLongPluginName())
      // .pipe(veryLongPluginName())
      .pipe(veryLongPluginName())
      .pipe(dest(PATHS.build))
  );
}

```

**Expected behavior:** Don't add the parentheses.

**Comment by evilebottnawi** [comment]
It is expected and discussed https://github.com/prettier/prettier/issues/2208
