### ISSUE TITLE
Adding prettier-ignore comment in JSX doubles the comment

### ISSUE THREAD

**Issue by etr2460** [prettier/prettier#8736]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT77VwzrWcGHLlwA8dHADdhIrsAB0i4AF98AegBU+GbLVr8AARgBnALQ4A5lBpx8G-ZvwAHHjFxxq5qzbtrlOkRwoSQBDEhw6AAVqCCcAXjYQYjJKGnpEgIA+AK54YxgA0TUJSWzOfCYAbg5-KBAAGhBY3GhjZFAQ6hiAd0jOhDaUMO6QgE82xoAjahCwAGteAGUnWaCLZBhqdDhGgAsYAFsSCl2cPJWwOEWBs6kz0eRwYwmQIOMPGGiQiwOQ5FQwu9GgArYwADwAQjN5ksQgc4AAZIJwf6AnYgUFgxZrEhwACK6Ag8FRJCBIBW1He1EekxCk1IDXJ1CCMAoERgu2QAA4AAyNFwQd4UGZOR4uOBUyQoxoAR0J8GisUGIBCZigcDgdE1jJ4cpwPC+Pz+SABpPR7wOOA2W3NOPx8pRJrRjRgdLZdA5yAATC6ZjhwlALABhCAHX6PCUAVkZ6HeABU6YNTWTJNsAJJQLWwRZgZlOGAAQUzixgo1xJPeymUQA)
```sh
--parser babel
```

**Input:**
```jsx
function HelloWorld() {
  return (
    <div
      {...{} /* 
      // @ts-ignore */ /* prettier-ignore */}
      invalidProp="HelloWorld"
    >
      test
    </div>
  );
}

```

**Output:**
```jsx
function HelloWorld() {
  return (
    <div
      {
        ...{} /* 
      // @ts-ignore */ /* prettier-ignore */ /* 
      // @ts-ignore */ /* prettier-ignore */
      }
      invalidProp="HelloWorld"
    >
      test
    </div>
  );
}

```

**Expected behavior:**
I would expect prettier to ignore this ugly block entirely. This is probably a pretty uncommon use case, but I was trying to get a `ts-ignore` comment to work in JSX by following instructions here (https://github.com/microsoft/TypeScript/issues/27552#issuecomment-550531540) and ended up in this state where every time I saved the file, prettier auto formatting would double the number of comments I had

**Comment by thorn0** [comment]
While, obviously, this is a bug, wouldn't the following work for your case @etr2460 ?

```ts
function HelloWorld() {
  return (
    <div
      // @ts-ignore
      invalidProp="HelloWorld"
    >
      test
    </div>
  );
}
```
