### ISSUE TITLE
npx prettier version is still v1?

### ISSUE THREAD

**Issue by bodazhao** [prettier/prettier#8737]
**Environments:**

- Running Prettier via: CLI
- Runtime: Node.js v12.18.2, NPM v6.14.5
- Operating System: macOS

**Steps to reproduce:**

The prettier version in my npx is still v1

```sh
npx prettier --version
# 1.19.1
```

It's a new repository and I don't have prettier installed locally

**Expected behavior:**

should be update to date with the latest v2 version?

**Comment by fisker** [comment]
can you try 

```bash
npm uninstall prettier
npm uninstall --global prettier
```

first, and run 

```bash
npx prettier --version
```
again?

**Comment by bodazhao** [comment]
Did so, still getting `1.19.1`

**Comment by evilebottnawi** [comment]
What is register?

**Comment by bodazhao** [comment]
Found the solution 

- I have Yarn v1 and NPM on my machine
- Tried `npm uninstall -g prettier` and `yarn global remove prettier`
- Nothing was removed as I don't have prettier installed globally in both
- So I manually went to each package manager's globally installed location
- Found under `~/.config/yarn/global/node_modules`, there was a `prettier` folder
- Manually removed that folder, and now `npx prettier --version` is `2.0.5`

Thanks for the response, should've done this before
