### ISSUE TITLE
Custom GraphQL template tag

### ISSUE THREAD

**Issue by jasonkuhrt** [prettier/prettier#8738]
This may be considered a dupe of #4260, because one of the solutions there would satisfy this issue too.

I work on a project called [Nexus](https://github.com/graphql-nexus/nexus) and we're considering integrating [ts-graphql-plugin](https://github.com/Quramy/ts-graphql-plugin). It allows for static analysis of GraphQL strings, e.g. queries. One of its features is to allow [customizing the template tag](https://github.com/Quramy/ts-graphql-plugin#tag) that it will analyze.

Relevant to Nexus because our desired API would not use `gql` as the tag name, but rather `ctx.client.send` (at least currently).

However, it appears that this path would lose us formatting from prettier.

So the feature request here is to allow local prettier configuration that would make it so a custom tag/path such as `ctx.client.send` could be treated as GraphQL source to format.

A solution taken from #4260 that could work for this, adapted:

```json
{
  "overrides": [
    {
      "tags": ["ctx.client.send"],
      "options": { "type": "graphql" }
    }
  ]
}
```

**Comment by jasonkuhrt** [comment]
Interested in providing a PR for this. Only place I found a reference to `gql` tag in codebase (non-test) was here https://github.com/prettier/prettier/blob/a0e2efca04a88e7b8b946d07982647abe8f09f50/src/language-js/clean.js#L172. Is this right?

**Comment by bakkot** [comment]
See also https://github.com/prettier/prettier/issues/4424, https://github.com/prettier/prettier/issues/7073, and https://github.com/prettier/prettier/pull/6626 (and possibly others).

I think most of the work to be done here is design, not implementation. If you want to try to pick up and discussion of the design, go for it.

**Comment by thorn0** [comment]
Closing in favor of #5588.
