### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by ryanmcdermott** [prettier/prettier#874]
I really love the work y'all have done on this! I was curious, is there a roadmap to 1.0? Any plan for new features, bug fixes, etc.?

**Comment by vjeux** [comment]
The goal right now is to fix the long tail of formatting things that pop up when people are actually using for real on big codebases. Every week, we're getting more of those edge cases sorted out and the changes become smaller and smaller. Also, as more people are adopting it, the cost of change is going to increase dramatically. So, we should expect to converge towards something stable pretty soon and we'll be able to call it 1.0.

The big amount of work once the actual formatter is stable enough is going to be integrations. We need to make sure that editor, lint, CI, hooks... are rock solid. Right now everything is pretty ad-hoc and not a great experience.

**Comment by vjeux** [comment]
I'm going to close this issue as it's not very actionable. If there are things you'd want to see, please create issues for them :)

**Comment by ryanmcdermott** [comment]
Thanks for the update, I appreciate it!
