### ISSUE TITLE
speced if-else and try-catch blocks

### ISSUE THREAD

**Issue by Fylls** [prettier/prettier#8754]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACOAPAhgWwAcAbODARgB0pqBLAMwwAoBnCfOGAC1qgHMAlBmDUMGSABM4ojNQC+WYizINmbDt158Agn1y8hIqGMnTjsqArhKyRkxCnyA3NWroseIqQwAmVzVgAJwBPYRlTGXlxXBgwLmY4QMDDcOg2UgA6Ygg+JkTk+RAAGhAIQhhaNORQXCSIAHcABVqEFmQQXGJ63GC2koAjQNwwAGtOAGVCYa1kGECAVzgSrhh8YgB1HngWKbA4cdbaCoA3I+D2sBY+kF5lQJhGob58XGR6TuUSgCsWbAAhIajCYEOAAGV4cDeHyWIB+2HGWlIAEV5hB4FCbCUpoE7u1+rh+tZiiBCIFeDB1rQJNxkAAOAAMWMCEGU6yGhHapLgd2OkJKAEdUfBHmU2ihcCwALRQOBwKQSYmBOCC2hKx64Z6vJDvTEgZT4WizBYwliIuAotGQ7XQkowAmU6lcZA+W1DWjELQAYXYL3a3IArMT5soACoEsU6z4gY6LACSUCksHGYDJ5W0CfGMGCpAxyjkciAA)

hey first of all thanks for creating prettier, it help keeping my code organized and readable!
By the way I was tinkering with prettier options and I noticed there were none relative to spacing with "if-else" and "try-catch".
I really think that spacing those in the way I showed could improve readability, especially if the code is long.

Maybe it shouldn't be active by default but we can easily implement in the config a line of code to turn it on and off at will.
something like this:

`"prettier.conditionalSpacing": true,`

the following are visual examples of what i mean

**Input:**
```jsx
// example 1

if (something) {
  code
  
} else if (somethingAgain) {
  code
  
} else {
  code
};

// example 2


try {
  code
  
} catch (err) {
  console.log(err)
}
```

**Output:**
```jsx
// example 1

if (something) {
  code;
} else if (somethingAgain) {
  code;
} else {
  code;
}

// example 2

try {
  code;
} catch (err) {
  console.log(err);
}

```

**Expected behavior:**

same as input

```jsx
// example 1

if (something) {
  code
  
} else if (somethingAgain) {
  code
  
} else {
  code
};

// example 2


try {
  code
  
} catch (err) {
  console.log(err)
}
```

**Comment by evilebottnawi** [comment]
Please read https://prettier.io/docs/en/option-philosophy.html, sorry we don't want to change current output and don't want new options
