### ISSUE TITLE
[typescript] allow collapsing space before type declarations

### ISSUE THREAD

**Issue by zanona** [prettier/prettier#8757]
I would like to being able to not having spaces automatically added before type declarations on typescript as it feels we are breaking the context where it seems disconnected from the variable or function itself:

```ts
const foo:string = '' // it feels foo is a `string`
const foo: string = '' //it feels `string` is an argument of sorts
```

As the separator is already `:` I fear it may be a bit unneeded also adding a space in there.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJRIDOMATjlAOb7AC+AOltNfgEYCGNKrXpMAvPgDkEgNwgANCAgAHXF2SgBNCAHcACgISVkIPgDcIOACbyQPGnzABrODADKShyOS10cBQAsYAFsAGwB1fxx4Sg8wOFdDKJxTKIBPYzBKIwV6SjgaGF17BiC+ZFQ+ELyFACtKAA8AIXsnF1c+ILgAGXo4csrqkDr61xEQuABFdAh4fqq-EA8aPJpjGFSlOEowOhUbJTpYMKsYf2QADgAGBQOIPLD7JWMDrfzTPoUAR2n4IuUjFB8SgAWigcDglghNhocG+OBhRT4JTKSAq8wUeSCOG8NF8GLGkx+fVRAwWMD4PGOllOyAATApaHwcCERABhCBBUrGSohGzoPIAFQpALRg1MvgAklBIbBXDscCoAILS1zrcZzPIsFhAA)
```sh
--arrow-parens avoid
--parser typescript
--trailing-comma all
```

**Input:**
```tsx
function foo():string {}
const bar:string = '';
```

**Output:**
```tsx
function foo(): string {}
const bar: string = "";

```

**Expected behavior:**
```tsx
function foo():string {}
const bar:string = '';
```

**Comment by kachkaev** [comment]
See https://prettier.io/docs/en/option-philosophy.html

The point of prettier is not to get a 'perfectly looking code' (it never would be), but to forget about formatting once and forever. No matter how odd the absence of space looks to you today, you won't notice it after a week of using Prettier. The same applies to all other cases.

**Comment by evilebottnawi** [comment]
Thanks for the issue, but we don't want to change current output and don't want new options
