### ISSUE TITLE
Overeager paren removal on flow array types

### ISSUE THREAD

**Issue by hawkrives** [prettier/prettier#877]
> here is a [prettier web example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20problem%3A%5Cnlet%20arr%3A%20(number%7Cstring)%5B%5D%20%3D%20%5B%5D%5Cn%5Cn%2F%2F%20this%20is%20a%20solution%2C%20I%20suppose%5Cnlet%20arr2%3A%20Array%3Cnumber%7Cstring%3E%20%3D%20%5B%5D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

In short:

```js
let arr: (number|string)[] = []
// becomes
let arr: number | string[] = []
```

Flow actually caught this one after I ran prettier on my codebase, so that's nice.

A workaround is to just use `Array<T | U>` instead of `(T | U)[]`.

**Comment by existentialism** [comment]
I have a fix for this incoming (happened to be looking at something similar, lol)
