### ISSUE TITLE
Prettier doesn't throw an error for not printed comments with `prettier-ignore` comment

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#8773]
If input includes `prettier-ignore` comment, Prettier doesn't throw an error for not printed comments. I'm not sure it depends on languages.
(The below example code uses #7126 bug.)

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSgDMIIMBqDDzpiAbnvsixCUAK5wM6DJAC20hDHp8oIADQgIWItADOyUAEMcOCAHcACoYS6U+gDYn9AT11qARjn1gA1vgDKWT2EKZBgcMTUACxhpWwB1CMJ4bQCwOF8rRMIAN0THZHBtFxBhbRIYMw8KaX1kBjtStQArbQAPACEPbz99OQAZYTha+rgm1t8g2zgARREIeCHbBpAAnFKcfJhHLDhtMBxCTVVl-dhYwgATGAjkAA4ABjVcCFLYjyx83B2SLMG1AEdZvAKhprCB9NpSFA4HBzjCjngAYQ8BV9FUakg6osRiBStJCCEwtjtBNpoDBhjhmoYPpXGdLtckAAmKkeQi2IIAYQgsnRIB2AFYjiJSgAVGnWTFLLJiACSUFhsF8ewOMAAgvLfJtJgtSgBfXVAA)
```sh
--parser typescript
```

**Input:**
```tsx
// prettier-ignore
foo +      foo;

continue // comment
;

```

**Output:**
```tsx
// prettier-ignore
foo +      foo;

continue;

```

**Expected behavior:**

```
Error: Comment "comment" was not printed. Please report this error!
```

**Comment by thorn0** [comment]
This is expected. `prettier-ignore` leads to outputting a portion of the input file instead of printing AST nodes, so the comments in the AST remain marked as not printed.

**Comment by sosukesuzuki** [comment]
I thought this is not expected because `prettier-ignore` comment affects to other than its target node. At least I think users will be confused.

**Comment by thorn0** [comment]
I mean it's expected because this check becomes impossible.

**Comment by fisker** [comment]
I'll take a shot.
