### ISSUE TITLE
Enforce consistent spacing around comments

### ISSUE THREAD

**Issue by remcohaszing** [prettier/prettier#8774]
I think it would be nice if prettier enforces consistent spacing around multiline comments.

- Multiline comments are always preceded by a blank line, unless:
  - They are at the start of a file
  - They are at the start of a block
- A blank line after a multiline comment is never allowed, unless it it followed by another multiline comment.

This behaviour is similar to ESLint rule [lines-around-comment](https://eslint.org/docs/rules/lines-around-comment) with the configuration below, except not all TypeScript features are supported, causing conflicts with Prettier:

```yaml
lines-around-comment:
  - error
  - allowBlockStart: true
    allowObjectStart: true
    allowArrayStart: true
    allowClassStart: true
```

Arguably the same could be applied to inline comments and comments in languages other than JavaScript / TypeScript.

**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AWwgBMBXAGzlwCsBnEiMHfVHDbPAgYQoEM6dWgyYt0bKGH6DcAMQgRcwFrg4r8uAEZ8ATsMbM8uViu16AvLgAMAbhVqjG7QC99ox+NN9XlgIx2oAF92TDFcAElYOB0AMz4wanoDMQkASyjY+Op5RWUjB2MnXTdDQs8jMyRcKDJCTWiA4wLjAhcS9XLjFyqauoacYKgCgghNGjgwGHauCUgoOimYhVxLPKbQjy1ipPcyiS7dKqsAGnsNsq3XHdKW-cuj06CQY5AIAAcYVOg6ZFBdHQgAHcAAq6BA-FB8CiAvgATx+L00OniAGs4DAAMpveLpADmyBgOjIcBeAAsYIQKAB1UmpeB0bEJDHgumpABudNhyHAgmeIHSdGiMGByNxhD4yDiFEFL3oAA8AELIsBozF8QhwAAy6TgkqhMpA8oxeKoAEUyBB4HrpSSQNidIKdNyYLC3nA6GAdKkPny3l7YFTUiQYKTkAAOE52gGCqnIt7cv3u6Js3UvACOFvgIveEJAAgAtFA4HASCW+To4BnUhWRXwxRKkFKDYLCKkCUTbXQTXBzZbdY39baYHxNIHg6GkAAmF6EvipCh47gQQji7nugCsfLIgoAKiOIU3bWziZFS7AMZ7vTAAIJQEgYl1Ua2CwKBIA)
```sh
--parser typescript
```

**Input:**
```tsx
/**
 * module jsdoc
 */
/**
 * Class jsdoc
 */
class Foo {
  /**
   * bar jsdoc
   */
  bar = 0;
  /**
   * baz jsdoc
   */
  baz = 1;
}
/**
 * Interface jsdoc
 */
interface Foo {
  /**
   * bar jsdoc
   */
  bar: number;
  /**
   * baz jsdoc
   */
  baz: number;
}
/**
 * object jsdoc
 */
const foo = {
  /**
   * bar jsdoc
   */
  bar: 0,
  /**
   * baz jsdoc
   */
  baz: 0,
}
```

**Output:**
```tsx
/**
 * module jsdoc
 */
/**
 * Class jsdoc
 */
class Foo {
  /**
   * bar jsdoc
   */
  bar = 0;
  /**
   * baz jsdoc
   */
  baz = 1;
}
/**
 * Interface jsdoc
 */
interface Foo {
  /**
   * bar jsdoc
   */
  bar: number;
  /**
   * baz jsdoc
   */
  baz: number;
}
/**
 * object jsdoc
 */
const foo = {
  /**
   * bar jsdoc
   */
  bar: 0,
  /**
   * baz jsdoc
   */
  baz: 0,
};

```

**Expected behavior:**

```tsx
/**
 * module jsdoc
 */

/**
 * Class jsdoc
 */
class Foo {
  /**
   * bar jsdoc
   */
  bar = 0;

  /**
   * baz jsdoc
   */
  baz = 1;
}

/**
 * Interface jsdoc
 */
interface Foo {
  /**
   * bar jsdoc
   */
  bar: number;

  /**
   * baz jsdoc
   */
  baz: number;
}

/**
 * object jsdoc
 */
const foo = {
  /**
   * bar jsdoc
   */
  bar: 0,

  /**
   * baz jsdoc
   */
  baz: 0,
};

```

**Comment by evilebottnawi** [comment]
Sorry, it is out of scope prettier, we don't want to insert extra new line, because some people don't like it, you should disable this rule if you want to use prettier
