### ISSUE TITLE
Incorrect link to remark-parse package in Options doc file

### ISSUE THREAD

**Issue by josephmarkus** [prettier/prettier#8781]
There's a link in your docs, here - https://github.com/prettier/prettier/blame/master/docs/options.md#L221

which takes to

https://github.com/remarkjs/remark/tree/master/packages/remark-parse

but it should take to

https://github.com/remarkjs/remark/tree/main/packages/remark-parse

I'd create a pull request, but in your docs (here - https://prettier.io/docs/en/options.html) 'Edit' button takes to your GitHub and says that I should fork the repo in order to propose changes

Hope, this helps 👍

**Comment by fisker** [comment]
Thank you, PR welcome.

**Comment by josephmarkus** [comment]
@fisker I'd happily contribute, but it doesn't seem so welcome:

<img width="722" alt="Screenshot 2020-07-17 at 16 35 06" src="https://user-images.githubusercontent.com/9258365/87804291-8eac9980-c84b-11ea-9113-1a90a4059bf0.png">

**Comment by fisker** [comment]
To make a PR, you need fork, if you don't want use git client, you can edit on github website and send it.
