### ISSUE TITLE
Prettier adds trailing commas inside Javascript Objects

### ISSUE THREAD

**Issue by Yash-Singh1** [prettier/prettier#8784]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#.....)

**Input:**

```jsx
// code snippet
var example = {
  something: "example"
}
```

**Output:**

```jsx
// code snippet
var example = {
  something: "example", // Why is there an extra trailing comma
};

```

**Expected behavior:**
The Prettier formatter will automatically add an extra trailing comma inside the Javascript object. On my understanding, it is not illegal but can cause problems if you are converting objects to JSON. There is an option inside the prettier configuration, but the default should be no trailing commas due to problems it could cause. My suggestion is to change the default trailing commas option from ES5 to none. You never know when a person spends the whole day getting syntax errors just because of that.

**Comment by fisker** [comment]
This was dicussed, we are not going to change it.

**Comment by Yash-Singh1** [comment]
Sure
