### ISSUE TITLE
MDX parser converts *** to --- which does not match the MDX spec

### ISSUE THREAD

**Issue by mshick** [prettier/prettier#8788]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOAbDEA6U8BUReeAPAIQC0lABAA4BOcMMAlnA5awOZQRM1qAPkLEoNGnhAAaEBDptoAZ2SgAhgwYQA7gAUNCFSjUZtagJ4rZAIwZqwAa2YBlOvdZRuyGAwCucWQALGABbDAB1QNZ4JTcwOGdDaNYAN2jzZHAlKxAPJQ4YXTtuELVkADMTfNkAKyUADwAhO0cXNRC4ABkPOAqqgJA6+ucPbgw4AEVfCHg+jGqQNwZ8hkyQgBN6mUWGDxhw1nWYQOQADgAGWUYIfPC7OkzGOBWU3tkAR2n4IvkjEDUlJQoHA4OtQdsmJ9WEwimoSmUkJV5gN8iFWN4-CjRuMpjNeoj+rIYGprAcjickAAmIl2VgYUYAYQgIVKmWeAFZtr58gAVElGJELFL+ACSUDBsGcYF2CgAguLnDBzOM5vkAL5qoA)
```sh
--parser mdx
```

**Input:**
```mdx
Hello

***

<!-- prettier-ignore -->
***
  

```

**Output:**
```mdx
Hello

---

<!-- prettier-ignore -->
***

```

**Expected behavior:**

The MDX parser should not change `***` to `---` since they have different meanings in the MDX spec. 

- [Thematic Break](https://github.com/syntax-tree/mdast#thematicbreak) uses `***` 
- `---` is solely mentioned as a [divider for frontmatter](https://github.com/syntax-tree/mdast#yaml) 
- The remark parser will also turn `---` in the body into `hr` tags, but it would be preferable to use that explicitly

**Comment by thorn0** [comment]
> since they have different meanings in the MDX spec

The page you linked to isn't the MDX spec, is it?

As per the [CommonMark spec](https://spec.commonmark.org/0.29/#thematic-breaks), 

> A line consisting of 0-3 spaces of indentation, followed by a sequence of three or more matching -, _, or * characters, each followed optionally by any number of spaces or tabs, forms a thematic break.

**Comment by mshick** [comment]
The MDAST/MDXAST specifications (their words, not mine) are linked to from the MDX specification page [here](https://github.com/mdx-js/specification) and it is the only place I've seen the markdown-to-unist syntax mappings documented. Given that the prettier mdx parser  [is derived from the same mdx-js library](https://github.com/prettier/prettier/blob/master/src/language-markdown/mdx.js#L4) and that prettier uses the remark parser for markdown, which follows the spec I linked to, it seems like prettier should have a behavior that follows the MDAST.

That said, are you suggesting that remark is not correctly implementing the CommonMark spec by having a different meaning for `---` and `***` in their AST?  I can raise an issue over there if that's the case, but I suspect it won't get much movement since it could cause issues with a lot of markdown in the wild. I'll also point out that CommonMark has nothing to say about front matter, which uses the same `---` sequence so perhaps the move to have different sequences was an attempt to deal with a common use case.

Seems like the easiest solution would be to prefer `***` in prettier since that's the direction the remark parser has gone, and it's certainly less ambiguous having a thematic break that is distinct from the `---` used to separate front matter.

**Comment by thorn0** [comment]
The MDX spec https://github.com/mdx-js/specification page says:

> MDX is superset of the CommonMark specification that adds embedded JSX and import/export syntax.

Both `---` and `***` are parsed as a thematic break by remark in full accordance with the CommonMark spec.

Here https://github.com/syntax-tree/mdast#thematicbreak `***` is just an *example* of a thematic break. That page defines the  format of AST structures, not the syntax of Markdown.

**Comment by mshick** [comment]
@thorn0 Thanks very much for looking into this. You're totally right, and after digging into the various internals on my project and the processor, `gatsby-plugin-mdx`, I realize what I was seeing was some idiosyncratic behavior there.
