### ISSUE TITLE
CSS incorrect whitespace after escaped semicolon

### ISSUE THREAD

**Issue by ialexi-bl** [prettier/prettier#8789]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6A5gJwJYBMAEwAOlPvpALYAOEAznLUvgBYQBucmRRSARugFoAjAAYR+AGaYIFfOgA2EXgEN5AbhIBfEiRAAaEBCoxs0WslDLM0gO4AFKwnMpVN5QE9zB3pmVgA1nAwAMpUfthQ6MgwmACucAbMMBTyAOrM2PC0YWBwwU6Z2GyZ7sjgtF4gEfSYMHa+6BTKyBKq9AYAVrQAHgBCvgFBwcoUcAAyEXAtbQkgXd3BEQpwAIqxEPDT8u0gYZg1ZWAV+rs4sKl4MMzIABwiBlTS9Km+VGWPDJwcJwCO6-D1IzOEDKWgCKBwOC4KEnTBwP7YOH1ZSNZpIVrbWb0CjYaJxLFLeSrf5TdEzAwwZS8C64K7IABMFN82HkSwAwjImmUGABWE6xegAFSpzgxOzY8QAklBobBgmAcMYAIIy4IwdxErb0TSaIA)

I'm using prettier in a project with css-modules and tailwind. Css-modules provide the `composes` rule to combine classnames in css files and tailwind uses classnames like `hover:bg-blue`, note the semicolon.

```sh
--parser css
```

**Input:**

```css
/* Non-escaped colon causes parsing error, so escaping it */
composes: hover\:bg-blue from global;
```

**Output:**

```css
composes: hover\: bg-blue from global;
```

**Expected behavior:**
```css
composes: hover\:bg-blue from global;
```

There was already #8512, but it didn't fix this problem. Are there any situations, when escaped colon needs a space after it? I don't see one, so is this possible to just disable putting space in this case?

**Comment by thorn0** [comment]
It has been fixed, but not released yet.
