### ISSUE TITLE
new line before and after function 

### ISSUE THREAD

**Issue by fabriziogiordano** [prettier/prettier#879]
Is it possible to wrap `function declarations` in new lines.

Raw:
```js
const a;function b(){/*something here*/}function c(){/*something here*/}
```

Proposed prettified code:
```js
const a; 

function b() {
  /*something here*/
} 

function c() {
  /*something here*/
}
```

Prettier 0.21 do not add lines and it feels too condensed:
```js
const a; 
function b() {
  /*something here*/
} 
function c() {
  /*something here*/
}
```

Thank you.

**Comment by vjeux** [comment]
```js
const a = 1;function b(){/*something here*/}function c(){/*something here*/}
```

outputs

```js
const a = 1;
function b() {
  /*something here*/
}
function c() {
  /*something here*/
}
```

with no empty lines.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20a%20%3D%201%3Bfunction%20b()%7B%2F*something%20here*%2F%7Dfunction%20c()%7B%2F*something%20here*%2F%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

But, if you add empty lines and reformat, then prettier will respect them.

```js
const a = 1;

function b() {
  /*something here*/
}

function c() {
  /*something here*/
}
```

outputs

```js
const a = 1;

function b() {
  /*something here*/
}

function c() {
  /*something here*/
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20a%20%3D%201%3B%5Cn%5Cnfunction%20b()%20%7B%5Cn%20%20%2F*something%20here*%2F%5Cn%7D%5Cn%5Cnfunction%20c()%20%7B%5Cn%20%20%2F*something%20here*%2F%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by SimenB** [comment]
+1 for defaulting to adding a single linebreak around functions.

(sorry if you want exclusively reactions on OP for this sort of thing)

**Comment by fabriziogiordano** [comment]
@vjeux correct. I'd like to avoid the "add empty lines and reformat" part and have prettier automatically add the new lines.

Do you think it is nicer to the eyes to have newlines between function declarations?

**Comment by vjeux** [comment]
So, we've tried this approach at the beginning but it's too error prone, there are times when you want them and times when you don't. Instead, we now preserve what the developer entered.

This is not ideal but we found that it was a good trade-off.

**Comment by noahdecoco** [comment]
How about adding lines just after the opening and just before the closing of a function. Like this:

`const a = 1;

function b() {

  /*something here*/

}

function c() {

  /*something here*/

}`

I would really like to have this as an option. Is it possible to configure this somewhere? Currently prettier removes these lines if present, would like to disable that.

**Comment by lydell** [comment]
@noahdecoco See #2352.

**Comment by xahon** [comment]
So what if i don't want to use eslint? I think should be an option to insert that newlines
