### ISSUE TITLE
Prettier adds an empty object with a space to my code: {' '} ?

### ISSUE THREAD

**Issue by BlakeBrown** [prettier/prettier#8790]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqA8AHAfAHSg2JOIAU4AnMBGAQwHM5VJLK4wYlVhDT+SACgCMABlGoAVKhgALAJYBnAHSL68VQFcAttrqUAnstbtOASlQB6PgNuC5S1erhbd+oyY4xUAahkKVNToNRR09Q2UAd0poBjMbWxIAXwBSBMSsSzwQABoQCGwYeWhFZFB9GMiyfQRSlDoAG0i6A1K8gCNKOjAAazgYAGVsbvkoBmQYSk04PNkYbQaAdQV4RWGaAdr5IoA3bYNkcEU2kFHFKhgyLoY9ZAAzRvO8gCtFAA8AIS7e-oG6bTgABlRnB7o8ZiBXm8BqMGA04ABFTQQeBghpPEDDSjnSiHdp0dpwBq5TGUUYwRbyAAmcmQAA5RHlsDFzosuthDsy4DidqC8gBHZHwK4FOogOiKAC0UDgcCpcpJ7EF8nYV0YtyQD3REPO2nkEymOth8KRKNBmvBeXo7UpNNkyAATFauvIGrCAMIQNyHbkAVhJmnOABUCXUtRidtMAJJQeWwAZgMmFACCsYGMAM8LR5ySSSAA)

```sh
# Options (if any):
semi: true
singleQuote: true
jsxSingleQuote: true
jsxBracketSameLine: true
htmlWhitespaceSensitivity: 'strict'
```

**Input:**

```jsx
              <p>
                Percentage correct: {
                  (100 * this.state.summary.correct) /
                  (this.state.summary.correct + this.state.summary.wrong)
                }%
              </p>

```

**Output:**

```jsx
              <p>
                Percentage correct:{' '}
                {(100 * this.state.summary.correct) /
                  (this.state.summary.correct + this.state.summary.wrong)}
                %
              </p>
```

**Expected behavior:**

Reformatting is fine, but why is prettier adding a random object with a single space? 🤔

**Comment by thorn0** [comment]
That's how whitespace works in JSX. Please see e.g. [this question on StackOverflow](https://stackoverflow.com/q/32686728/76173).

**Comment by BlakeBrown** [comment]
Thanks for the explanation! 🙏
