### ISSUE TITLE
[SCSS] Corrupted comments inside multi-line lists and maps

### ISSUE THREAD

**Issue by xpuu** [prettier/prettier#8807]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKASANgSwM4xIAE6A9KUQIwA06ATNSVOUQMyPoAstzFArDxYA2QRQDsPANzoZmHPAC2eYgAoyFAgEMAToSIAzLHAAeAWi26eRIggAmxQydN2rRMAnjbi72HG2iiACM4GAB3OARiPAAHTXdTYLCIqACdCABXKHsiGLi4UzTM2wC4ADcELABPKNj4sorKngBKSRBqEAhomBxoPGRQHW0IUIAFHQQ+lE0sUM1KvvbA7TiAaxCAZVqcKABzZBhtdLh2gAsYBSwAdRP5OFz3dYn5HFL5SuRwPAWQbbw-GBGyx2Ck0yH00z+7QAVnhjAAhZZgNYwdaaBRwAAy2zgYIhxxAMOM622OyMAEV0hB4LisJCQLFtH9tB88GAvm16dptjBLjhbDATsgABwABna0SGf0uy2iHwldz85Q5AEdKfBAZ1JiBNHhTFAIrY4LYOdo4KqcKbAZpgaCkODafi-gocPtDo6SeS1Ti7Xj2jBNIFefzBUgGCADpocLhdgBhCAKEEfO58DnpP4AFQDk3tdNKRwAklkPOswFyugBBLLrGCVIw0v4AXwbQA)

```sh
# Options (if any):
default
```

**Input:**

```scss
$list: 
// 1,
2, 
// 3, 
4,
// 5,
// 6,
// 7,
;

$items: (
// start: flex-start,
  end: flex-end,
  center: center,
// between: space-between,
// around: space-around,
// evenly: space-evenly,
);
```

**Output:**

```scss
// code snippet
$list: 
// 1, 2,
  // 3,
    4,
  // 5,
    // 6,
    // 7,;

$items: (
  // start: flex-start,
    end: flex-end,
  center: center,
  // between: space-between,
    // around: space-around,
    // evenly: space-evenly,
);
```

**Expected behavior:**
All the values are preserved and correctly indented

**Comment by thorn0** [comment]
Fixed by #7844. Not yet released.

**Comment by xpuu** [comment]
I will just leave it here and test it with the new release.

**Input:**

```scss
$items: (
  all,
  /*
  left,
  right,
  bottom,
  */
);
```

**Output:**

```scss
$items: (all, /*
  left,
  right,
  bottom,
  */);
```

**Expected behavior:**
Line spacing should be respected.

**Comment by evilebottnawi** [comment]
@xpuu Can you open a new issue?
