### ISSUE TITLE
htmlWhitespaceSensitivity: 'css' doesn't account for display properties other than 'inline'

### ISSUE THREAD

**Issue by me1230** [prettier/prettier#8808]
htmlWhitespaceSensitivity: 'css' doesn't take into account display property values that are whitespace senstive other than 'inline'
The default display property of \<li> is 'list-item' which is whitespace sensitive but prettier will format it as if it was display: 'block'

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeArgGwHwB0q4yqYCW2AkgAQDOAFhFgCaUBGclMATnAIbzOkA1u3IByALaUSUUlHaYIipcpWrFUAOaVG1AGbUejXTUO6e1I6gD0pPFGtZsIADQgIABxglo1ZKB6cnBAA7gAKAQi+KDyYwTwAnr6uLJw8YMIwAMruadIayFzocK60MOKYAOq0JPDUOWBwmZE1JABuNfHI4NRJINLUcJwwoaka4jzIZpgDrgBW1AAeAEKp6XBZPOJwADLScJMxMyDzC5l5mHAAiugQ8AfTxSA5nAOcXaXlLk+c0jAVJIwYLRkAAOAAMrncQQGFVS7i6ULgr1a+1cAEcbvARh4oiBzABaORwRjEr7cDEkbgjHhjCZIKZHAbiEgFThFVzUc5XTH7emHR4wHgsf6A4FIABMri4PBIsg0AGEIOJxl0kQBWL7oAYAFSFUQZj1aRXIUBJsEyYB+ngAgqbMjB4hd7gMAL4uoA)

```sh
# Options (if any):
```

**Input:**

```html
<ul>
	<li>I should be treated like I'm inline looooooooooooooooooooooong dsfsadf sadfasdf</li>
</ul>
```

**Output:**

```html
<ul>
  <li>
    I should be treated like I'm inline looooooooooooooooooooooong dsfsadf
    sadfasdf
  </li>
</ul>
```

**Expected behavior:**
Should be formatted as if the \ tag had been added above the \<li>
```html
<ul>
  <li
    >I should be treated like I'm inline looooooooooooooooooooooong dsfsadf
    sadfasdf</li
  >
</ul>
```

**Comment by thorn0** [comment]
> 'list-item' which is whitespace sensitive

@me1230 Would be great if you could back up this statement somehow.

**Comment by me1230** [comment]
@thorn0 Sorry I jumped to conclusions, should of tested before making an issue.
Turns out that adding a ::before pseudo element causes whitespace to have an effect no matter the display property.

Can't think of anything but it would be nice to have a solution other than setting htmlWhitespaceSensitivity to 'strict' or littering my templates in \

**Comment by thorn0** [comment]
Related: #5415.
