### ISSUE TITLE
JSON Error in .prettierrc.json: LinesAndColumns$1 is not a constructor

### ISSUE THREAD

**Issue by Jernik** [prettier/prettier#8815]
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: CLI and VsCode extension
- Runtime: Node.js v12.18.1
- Operating System:  Windows

**Steps to reproduce:**
Follow the installation instructions here: 
https://prettier.io/docs/en/install.html
and the configuration file documentation here: 
https://prettier.io/docs/en/configuration.html

I have the configuration file .prettierrc.json :
`{"tabWidth":4,"semi":true,"trailingComma":"es5"}`

run `npx prettier --write src/`

**Expected behavior:**
prettier runs and formats my code

**Actual behavior:**
The error message from the CLI is 
```npx prettier --write src/  
[error] Invalid configuration file `src\App.css`: JSON Error in C:\Users\mill0715\Code\Portal-Web\.prettierrc.json:
[error] LinesAndColumns$1 is not a constructor
```

I am getting the same error from the CLI, but I don't know how to get a stack trace/detailed logs from there, so here is the vscode "format on save" error logs that get spit out. 
```["INFO" - 12:01:41 PM] Formatting c:\Users\mill0715\Code\Portal-Web\node_modules\prettier\third-party.js
["ERROR" - 12:01:41 PM] Invalid prettier configuration file detected.
["ERROR" - 12:01:41 PM] JSON Error in c:\Users\mill0715\Code\Portal-Web\.prettierrc.json:
LinesAndColumns$1 is not a constructor
TypeError: JSON Error in c:\Users\mill0715\Code\Portal-Web\.prettierrc.json:
LinesAndColumns$1 is not a constructor
	at parseJson$1 (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:3200:21)
	at loadJson (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11009:22)
	at Explorer.loadFileContent (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11535:34)
	at Explorer.createCosmiconfigResult (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11540:38)
	at Explorer.loadSearchPlace (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11521:33)
	at async Explorer.searchDirectory (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11492:31)
	at async run (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11465:24)
	at async cacheWrapper (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11300:20)
	at async cacheWrapper (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11300:20)
	at async Explorer.search (c:\Users\mill0715\.vscode\extensions\esbenp.prettier-vscode-5.1.3\node_modules\prettier\third-party.js:11457:22)
	at async Promise.all (index 0)```

**Comment by evilebottnawi** [comment]
Looks like problem on `esbenp.prettier-vscode-5.1.3` extension side

**Comment by Jernik** [comment]
Since I'm running into the exact same error message from the CLI, I provided those error logs as a stack trace, I'm assuming the stack is pretty similar since the error is coming from the `node_modules\prettier`.

**Comment by evilebottnawi** [comment]
@Jernik Can you provide steps to reproduce?

**Comment by Jernik** [comment]
@evilebottnawi I can try to repro it in a small project on my machine.

**Comment by Jernik** [comment]
I was able to repro it and fix it. The problem is that the `.prettierrc.json` file was encoded in UTF-16LE, not UTF-8. A better error message or UTF-16 handling would be appreciated, but hopefully this issue will be enough for the next person who runs into this error.

**Comment by fisker** [comment]
This  error 

> [error] LinesAndColumns$1 is not a constructor

is not expected.

There should be something wrong.

**Comment by carpben** [comment]
I'm experiencing the same issue. It occurs also when the vscode pretttier plugin is not installed. 

This screenshot presents the error well: 
![image](https://user-images.githubusercontent.com/13496178/89750303-0e88f500-dad4-11ea-8909-490bfbe4109f.png)

I follow the documentation and create `.prettierrc.json` with the command `echo {}> .prettierrc.json`. But when running `npx prettier --write .` it doesn't recognize a prettier config file. 

Any ideas as to why this might be happening?

**Comment by Jernik** [comment]
@carpben is your file utf-16? As I mentioned in the comments above, that was the root cause of what triggered this error for me.

**Comment by fisker** [comment]
@carpben Can you run `node -p "require('fs').readFileSync('.prettierrc.json', 'utf8')"`, and post the output, I didn't see any content in your `.prettierrc.json` file.

**Comment by carpben** [comment]
@Jernik , Saving as utf-8 solved the problem. On my Windows machine `echo {}> .prettierrc.json` as recommended in the [documentation](https://prettier.io/docs/en/install.html) creates a utf-16 file. 

Possible solutions: 
1. echoing a utf-8 file
2. Handling a utf-16 file 
3. Changing documentation to manually create a utf-8 file instead. I'll be happy to help with this solution and submit a PR. 

@fisker, 
Not sure if this is still relevant, but I ran the command with a utf-16 version of prettierrc.json and a utf-8 version. Here is the output: 

```
PS C:\givingway\gw-ts> node -p "require('fs').readFileSync('.prettierrc16.json', 'utf8')"
 �{
         " p r i n t W i d t h " :   1 1 0 ,
         " t r a i l i n g C o m m a " :   " a l l " ,
         " t a b W i d t h " :   3 ,
         " u s e T a b s " :   t r u e ,
         " s e m i " :   f a l s e ,
         " s i n g l e Q u o t e " :   f a l s e
 }

PS C:\givingway\gw-ts> node -p "require('fs').readFileSync('.prettierrc8.json', 'utf8')" 
{
        "printWidth": 110,
        "trailingComma": "all",
        "tabWidth": 3,
        "useTabs": true,
        "semi": false,
        "singleQuote": false
}
```

**Comment by fisker** [comment]
I tried on window 10 with `cmd.exe`, ran `echo {}> .prettierrc.json`, and the ecoding is `utf8`.
What version of windows, and which command line program do you use?

**Comment by carpben** [comment]
I confirm that running `echo {}> .prettierrc.json` from the Commad Prompt (`cmd.exe`) creates a utf8 file. But when I create it from PowerShell it creates a utf-16 file. 

I'm using the Windows 10 with regular updates.

**Comment by tychenjiajun** [comment]
@carpben Use `echo {}> .prettierrc.json`  is Win 10 Powershell will create a UTF16LE file. I open it and save it in UTF8 fix this problem.
