### ISSUE TITLE
Unstable comment in function parameters

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#882]
```js
let f = (
  a =
  //comment
  b
) => {}
```

[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20f%20%3D%20(%5Cn%20%20a%20%3D%5Cn%20%20%2F%2Fcomment%5Cn%20%20b%5Cn)%20%3D%3E%20%7B%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A801%2C%22tabWidth%22%3A1%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D):

```js
let f = (
 a = //comment
 b,
) => {};
```

[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20f%20%3D%20(%5Cn%20a%20%3D%20%2F%2Fcomment%5Cn%20b%2C%5Cn)%20%3D%3E%20%7B%7D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A801%2C%22tabWidth%22%3A1%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D):

```js
let f = (
 a = b, //comment
) => {};
```

**Comment by umidbekkarimov** [comment]
Not sure if [this](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20f%20%3D%20(%2F*%20...%20*%2F)%20%3D%3E%20%7B%7D%5Cn(function%20(%2F*%20...%20*%2F)%20%7B%7D)(%2F*%20...%20*%2F)%5Cnfunction%20f(%2F*%20...%20*%2F)%20%7B%7D%5Cn%5Cnconst%20obj%20%3D%20%7B%5Cn%20%20f(%2F*%20...%20*%2F)%20%7B%7D%2C%5Cn%20%20f%3A%20(%2F*%20...%20*%2F)%20%3D%3E%20%7B%7D%2C%5Cn%20%20f%3A%20function(%2F*%20...%20*%2F)%20%7B%7D%2C%5Cn%20%20f%3A%20function%20f(%2F*%20...%20*%2F)%20%7B%7D%5Cn%7D%5Cn%5Cnclass%20Foo%20%7B%5Cn%20%20f(%2F*%20...%20*%2F)%20%7B%7D%5Cn%20%20f%20%3D%20(%2F*%20...%20*%2F)%20%3D%3E%20%7B%7D%5Cn%20%20static%20f(%2F*%20..%20*%2F)%20%7B%7D%5Cn%20%20static%20f%20%3D%20(%2F*%20...%20*%2F)%20%3D%3E%20%7B%7D%5Cn%20%20static%20f%20%3D%20function(%2F*%20...%20*%2F)%20%7B%7D%5Cn%20%20static%20f%20%3D%20function%20f(%2F*%20...%20*%2F)%20%7B%7D%5Cn%7D%5Cn%5Cnf(%2F*%20...%20*%2F)%3B%5Cnf(a%2C%20%2F*%20...%20*%2F)%3B%5Cnf(a%2C%20%2F*%20...%20*%2F%20b)%3B%5Cnf(%2F*%20...%20*%2F%20a%2C%20b)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A801%2C%22tabWidth%22%3A1%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D) related or not, but I'l keep it here.

**In:**

```javascript
let f = (/* ... */) => {}
(function (/* ... */) {})(/* ... */)
function f(/* ... */) {}

const obj = {
  f(/* ... */) {},
  f: (/* ... */) => {},
  f: function(/* ... */) {},
  f: function f(/* ... */) {}
}

class Foo {
  f(/* ... */) {}
  f = (/* ... */) => {}
  static f(/* .. */) {}
  static f = (/* ... */) => {}
  static f = function(/* ... */) {}
  static f = function f(/* ... */) {}
}

f(/* ... */);
f(a, /* ... */);
f(a, /* ... */ b);
f(/* ... */ a, b);
```

**Out:**

```javascript
let f = () => /* ... */ {
};
(function() /* ... */ {
}) /* ... */();
function f(/* ... */) {}

const obj = {
 f /* ... */() {},
 f: () => /* ... */ {
 },
 f: function() /* ... */ {
 },
 f: function f /* ... */() {},
};

class Foo {
 f /* ... */() {}
 f = () => /* ... */ {
 };
 static f /* .. */() {}
 static f = () => /* ... */ {
 };
 static f = function() /* ... */ {
 };
 static f = function f /* ... */() {};
}

f /* ... */();
f(a /* ... */);
f(a, /* ... */ b);
f(/* ... */ a, b);
````

**Comment by vjeux** [comment]
@yamafaktory if you are interested in fixing this issue, you should be able to use the move trick ;)

**Comment by yamafaktory** [comment]
@vjeux sure I can do it! Just need to figure out what you mean by the move trick :)

**Comment by vjeux** [comment]
I just mean doing `if (enclosing && enclosing.type === "XXX") addLeadingComment(enclosing)`

**Comment by yamafaktory** [comment]
No problem, will fix it this evening 👍.
