### ISSUE TITLE
(Addition|Subtraction|Multiplication|Division) Assignment Operator Parenthesis Order Of Operations BUG

### ISSUE THREAD

**Issue by tyler1205** [prettier/prettier#8823]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2ADcBDAGwFc4lMBWAXwB0pIoNMAHOAJzAIYAYQgBbbpTjwimAAwA6AOwM2bAPTrMASSwBLND34w9UIZhgALclitxMcAB6S9YPVm7k+CQ97HlTTFMYcjB9KGw+ABN+CwhsHBDAjS07TEg+bzDMCho4ABpMHGoPbxgTWIw+PW5DOzFMcgB3cgBPC0t+OBx2sGsoAHNTAZSO+who2IgAM2xePhs9dHUcOGtSJb44zDRxaUthzGozZzgwuCjGqEvj4IQYqIUntlw8BVzaTAAqYgAKAEZMABaIwCISiCRSeAAShA+RAEG4JnQyFAXj4ECaAAUvD5kCAqC1Wmg4SAcAswABraQAZU8bkGyBgfFo8MsMDElAA6gd4Gh6XAaT53HoNjBWviwGgSfDTGhjFiFgN-MhplR5fC8GhHAAhCnUmA08hiOAAGVMcFV6oKIC1jhpwykAEVqBB4FbKBqQJ4+PK+PicORVpRSdxqrAuXoolZkAAOOTwsMQeVchbcfFhuB+0iW+EAR1d8EViJJKHIaCBZguF1J3gLem8ivIyvIHq98rEeiZLJtaEdcBdbstSDVnptIRwkejlmQACZ4cyApRhhCVSgswxSdR5QAVIOl0de0i0bTXIQ0sDVJEAQWuNPFUjbcCYTCAA)
```sh
--parser babel
```

**Input:**
```jsx
const obj = {value: 5}
const percentComplete = 0.75

// It is pertinent that the explicit parens remain intact in order to obtain 
// the correct value, but prettier strips them away thereby changing
// the order of operations/behavior to something unexpected and unintended...
obj.value *= (1 - percentComplete)
```

**Output:**
```jsx
const obj = { value: 5 };
const percentComplete = 0.75;

// It is pertinent that the explicit parens remain intact in order to obtain
// the correct value, but prettier strips them away thereby changing
// the order of operations/behavior to something unexpected and unintended...
obj.value *= 1 - percentComplete;

```

Note: originally discovered in typescript

**Comment by thorn0** [comment]
Works as expected. `*=` has the same precedence as `=`. Please refer to the [precedence table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#Table).

**Comment by tyler1205** [comment]
> Works as expected. `*=` has the same precedence as `=`. Please refer to the [precedence table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#Table).

Oh you're right, my bad. When I was testing this out I was forgetting to reset obj.value back to 5 so I was getting different results and wrongly attributing it to the existence of the grouping operator.
