### ISSUE TITLE
Unstable comments when using rare newlines

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#883]
Note: This is not reproducible in the online demo, since it appears to normalize newlines.

First off, note how the comments are stable when using the widely used `\n` or `\r\n` newlines:

```js
$ node -p '"1;/*a*///b\n/*c*/2"' | prettier
1; /*a*/ //b
/*c*/ 2;

$ node -p '"1;/*a*///b\n/*c*/2"' | prettier | prettier
1; /*a*/ //b
/*c*/ 2;

$ node -p '"1;/*a*///b\r\n/*c*/2"' | prettier
1; /*a*/ //b
/*c*/ 2;

$ node -p '"1;/*a*///b\r\n/*c*/2"' | prettier | prettier
1; /*a*/ //b
/*c*/ 2;
```

But when using any of the other valid JavaScript newlines (`\r`, `\u2028`, `\u2029`) the comments become unstable:

```js
$ node -p '"1;/*a*///b\r/*c*/2"' | prettier
1;
/*a*/ //b
/*c*/ 2;

$ node -p '"1;/*a*///b\r/*c*/2"' | prettier | prettier
1; //b
/*a*/ /*c*/ 2;

$ node -p '"1;/*a*///b\u2028/*c*/2"' | prettier
1;
/*a*/ //b
/*c*/ 2;

$ node -p '"1;/*a*///b\u2028/*c*/2"' | prettier | prettier
1; //b
/*a*/ /*c*/ 2;

$ node -p '"1;/*a*///b\u2029/*c*/2"' | prettier
1;
/*a*/ //b
/*c*/ 2;

$ node -p '"1;/*a*///b\u2029/*c*/2"' | prettier | prettier 
1; //b
/*a*/ /*c*/ 2;
```

**Comment by vjeux** [comment]
Soooo, I fixed it but the snapshot tests don't pass because jest somehow normalizes the line endings in the snapshot :p

**Comment by vjeux** [comment]
Looks like only the one with `\r` doesn't work: https://github.com/prettier/prettier/pull/1050
