### ISSUE TITLE
Prefer keeping statement on line with `if`

### ISSUE THREAD

**Issue by jbmanning** [prettier/prettier#8836]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEkADgJ4AqEAwgDY5EBGEAhgE4AmAFAJT7AA6UfPhyp8HGAAscAZwB0YONWpzUOavBYcOYHgF4AfIVkA3JtXRx8AQl278mNnFVQ4bfADJ3R6RHQsF1rb4AILYeFAAsnCSEGyyAJJQOLhmAOJMALZwXDz8gkL4ZnAsMByUAPIACgCaAPoAQuXBAEoAIrUA6vFkABK1AGrBADIAqgCiAMqdLQBy8TOpXADcAkIAvgIbUCAANCAQRLjQ0sigrCwQAO6VrAgnKGaXTCQne-QsTGAA1tETRJ84KAAc2QMBYFj2EhgGWoHSk8Gk-wUEzuyRwxmSJGQ4GkrxAgOkxRglQ+QIyTGQqDMhL2ACtpAAPeofb6-TJwIaAuCU6lwOmMiaAoHUOAARXQEHgPOUfJA-xYhJY2PoTHoil2cpYgJgHRwbEkyAAHAAGPZEC6EjofIjY81wRXGbl7ACOEvgJIO9xATGkAFoXK5XBqWHBXTgQySmGSKUgqTK9oSMjhQeDZdIhSLxZLubHeXsYKrdfqJMgAEz5j5qIWUCAZcnY+0AVg16EJZFV9zjNJAxgsiUcsAmYC1h2CUDYExgJBF0sJazWQA)
```sh
--parser babel
```

**Input:**
```jsx
function copyToClipboard() {
  if (this.cells.filter((c) => c.value !== undefined && c.source !== ActionMethod.InitialGame)) {
    alert(COPY_BOARD_WITH_VALUES_WARNING);
  }
}

```

**Output:**
```jsx
function copyToClipboard() {
  if (
    this.cells.filter(
      (c) => c.value !== undefined && c.source !== ActionMethod.InitialGame
    )
  ) {
    alert(COPY_BOARD_WITH_VALUES_WARNING);
  }
}

```

**Expected behavior:**

```jsx
function copyToClipboard() {
  if (this.cells.filter((c) =>
    c.value !== undefined &&
    c.source !== ActionMethod.InitialGame
  )) {
    alert(COPY_BOARD_WITH_VALUES_WARNING);
  }
}
```
or
```jsx
function copyToClipboard() {
  if (this.cells.filter((c) =>
    c.value !== undefined && c.source !== ActionMethod.InitialGame
  )) {
    alert(COPY_BOARD_WITH_VALUES_WARNING);
  }
}
```

_(Ignore the bad filter statement 😅 )_

**Comment by evilebottnawi** [comment]
Current output is readable, we don't want to change it, sorry

**Comment by jbmanning** [comment]
No problem, thanks!
