### ISSUE TITLE
Keep generating backslashes

### ISSUE THREAD

**Issue by Clloz** [prettier/prettier#8838]
**Prettier 2.0.5**

**Input:**
```javascript
\\
```

**Output:**
```javascript
// the backslashes will keep generating，and vscode will crash
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ 
```

**Expected behavior:**
fix this problem. If I accidentally enter two backslashes and format this file, my vscode will crash.
ps: If the `\\` is in a regular expression `/\\/`, the above situation will not happen.

**Comment by kachkaev** [comment]
Please follow the issue template
