### ISSUE TITLE
Ugly formatting of ternary inside a TS as assertion

### ISSUE THREAD

**Issue by bradzacher** [prettier/prettier#8840]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEn1ezjffAemMwEkA5ABQFUAVQozJoyKAZxkwEsoAHAK4wAogA8AhgFt+AGziYAvJgAUYCbNmUIAEzgA6fhIBOCGAH59MAJ78Fih5gCCAZXoB9SgHkAIiPf0AJrUIi76AMIAFhJ84vymHBw80JjmmOqa2nqGJmY5prCYSOkaWroGRgUwAJSYEhyY9C6h9KYGAEJ8JtZxCUnQrPiD2KSYIgAaIeH0Ij7DLHhs0FyYcGJ2YPA6XsJCMACMSqrz2Bll2ZVmljZ2So6uHt5+AcGhEdGx633JUCf4aWcshVcrB8mY-thioDymDYPNavVGs03G19J0oN1enBEj95vN2Cs1hstjsYHsAExHNSlIGwixWWz2Bx-B6eXz+IIhMJRGJQLE4gaLZjYAE0mGXUESmAQoolTLikE1OoNJotVHozFfbH9X5C7DzUYTJwAWWoABkRJgAOrkegACS8DGcLmaACV6OQvJQ8Xr0stuGtpHI4IdFH9oRdFddGXdlKynhzXtyPnytQLdcKiKL5ZGqnSZVCxbnwUKAL5MctQSsgAA0IAg-BgPw4yFAJmMEAA7tQQS2UBpOxJrC26wAjYwSMAAazgMBcRjAfAA5sgYMZBHA65EYFJZFbIjx4BwF3AXAgkk2AG6H6zIcCJWsgPgcODGGDUCdLqQSZAAMw0L51gAVhwYjtBO06zi40hwGafBwH+AGbiAIFiC4y7yAAioIEDwIhsiASAlQvsYd43NiYDGDwjaPvEfAwFaPA6DAkTIAAHAADHW8QQC+VoTvwd7xNir6XghdYAI44fAH4Nn2ID1AAtFAcBwHoOiPqYUk8KYH4SF+P5IP+BHIS+Ug8Ku66mRhcDYbhCFGUhdYwBIo6McxrFIOSzkTjwsjLuEEBSN+d7YgArI+ggvvQrl9sZhGXhu5BQHosAuJR1EwE4KUuDY8j4S+palkAA)

```sh
# Options (if any):
--parser=typescript
```

**Input:**

```jsx
{ { {
const inputExample = (callNode.parent?.type === AST_NODE_TYPES.ChainExpression ? callNode.parent.parent : callNode.parent) as TSESTree.BinaryExpression
} } }
```

**Output:**

```jsx
{
  {
    {
      const inputExample = (callNode.parent?.type ===
      AST_NODE_TYPES.ChainExpression
        ? callNode.parent.parent
        : callNode.parent) as TSESTree.BinaryExpression;
    }
  }
}
```

**Expected behavior:**

```jsx
{
  {
    {      
      const expectedOutput1 = (
        callNode.parent?.type === AST_NODE_TYPES.ChainExpression
          ? callNode.parent.parent
          : callNode.parent
      ) as TSESTree.BinaryExpression;

      const expectedOutput2 = (callNode.parent?.type ===
        AST_NODE_TYPES.ChainExpression
          ? callNode.parent.parent
          : callNode.parent) as TSESTree.BinaryExpression;
    }
  }
}
```

**Comment by sosukesuzuki** [comment]
I personally prefer `expectedOutput1`

**Comment by evilebottnawi** [comment]
Agree, let's improve it
