### ISSUE TITLE
Unstable comments in for-in (and for-of) loop

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#886]
```js
for (x
/*a*/
in //b
y) //c
;
```

[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22for%20(x%5Cn%2F*a*%2F%5Cnin%20%2F%2Fb%5Cny)%20%2F%2Fc%5Cn%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A801%2C%22tabWidth%22%3A1%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D):

```js
for (x in /*a*/ //b
y); //c
```

[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22for%20(x%20in%20%2F*a*%2F%20%2F%2Fb%5Cny)%3B%20%2F%2Fc%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A801%2C%22tabWidth%22%3A1%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D):

```js
for (x /*a*/ in y); //b //c
```

**Comment by vjeux** [comment]
Good find, so this only happens if there's a \n before AND after `/* a */`

**Comment by vjeux** [comment]
```js
for (x
/*a*/
in y);
```

```js
for (x in
/*a*/
y);
```

are the minimal repro cases
