### ISSUE TITLE
Option to remove ALL empty lines?

### ISSUE THREAD

**Issue by hi2u** [prettier/prettier#8860]
The default behaviour of Prettier, is to reduce multiple empty lines in a row down to 1 empty line.

Instead of "1", is there some way to have prettier optionally instead make it "0"?  i.e. All empty lines are removed altogether.

If not, could it be added as an option?

It could be an option specifically for this.  Or alternatively, to cover more use cases... an option called something like `maxEmptyLines` where the user can set a number...

* The default would be: 1 - as is the current behaviour
* People like me who want no empty lines at all, could set it to: 0
* Others might like to allow 2 or more empty lines in a row (in places where they already inserted multiple lines to begin with - obviously prettier shouldn't ever increase lines).

I know that the policies around adding new options are pretty conservative.  But I think compared to most other types of more complicated formatting decisions, this one is pretty simple.

**Comment by evilebottnawi** [comment]
Sorry, we don't want to change our behavior for newlines and we don't want new options, please read https://prettier.io/docs/en/option-philosophy.html
