### ISSUE TITLE
Support of IntelliJ IDEA specific code reformatting rules by Prettier

### ISSUE THREAD

**Issue by pubmikeb** [prettier/prettier#8862]
Starting 2020.2 IDEA supports Prettier. Since IDEA supports much more wider set of code reformatting rules then Prettier, is it possible to apply the IntelliJ IDEA specific code style rules via Prettier?

E.g.:
```editorconfig
ij_css_enforce_quotes_on_format = true
ij_css_hex_color_long_format = true
ij_css_hex_color_lower_case = true
ij_css_hex_color_short_format = false
```

**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: IntelliJ IDEA/WebStorm
- Runtime: Node.js 14.6.0
- Operating System: Windows 10 2004

**Comment by evilebottnawi** [comment]
No, it is impossible and we don't want to support them
