### ISSUE TITLE
Wrong formatting of HTML

### ISSUE THREAD

**Issue by igodorogea** [prettier/prettier#8874]
### Case 1

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgAnQJwJboC0YAFnGANZwAmAvADogBm6ANgM5yOY4StwMQAIwCuMGNG4x0QvFGpwAHoIAM3MK3Tt2goTCiY9UQgAd8AW1wBPRgD4AMnIqoA9Olv0oIADQgIJmDxodmRQXF4AdwAFXAQQlDYI9CsQ3yEcdEo4GABlE0y5AHNkGBwROF8SGHNWAHUSPHh2fLA4HLjGvAA3RqtkcG0fEDlOHBgojMLLZBYOCpAAK3ZFACEMrNz0czhHKDgZtk5fJcUcov4ARREIeAO533ycUf70KEKRTRwhszkYWrxqDASMgABwqB68Ti1DImfpmOCjLr7XwAR2u8Am-niIC0hD2NBoQxwcDReGJE3QU3QdyOIE45jwJTK83Y5zgVxu+yQs1p0iE-0BwKQACZfKV0HhWEUAMIQczTFAIgCsQxEnAAKjJ4jz5l1ygBJeQIXJgfABACC8hyMCs-BpcAAvg6gA)
```sh
--parser angular
```

**Input:**
```html
<a aria-checked="false" role="button" tabindex="0" class="btn btn-primary">Link</a>
```

**Output:**
```html
<a aria-checked="false" role="button" tabindex="0" class="btn btn-primary"
  >Link</a
>
```

**Expected behavior:**
```html
<a
  aria-checked="false"
  role="button"
  tabindex="0"
  class="btn btn-primary"
>Link</a>
```

### Case 2

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgAnQJwJboC0YAFnGANZwAmAvADogBm6ANgM5yOY4StwMQAIwCuMGNG4x0QvFGpwAHoIAM3MK3Tt2goTCiY9UQgAd8AW1wBPQ-sJDWESowB8AGTkVUAenQv6UCAANCAQJjB40OzIoLi8AO4ACrgI0Shs8ehW0SFCOOiUcDAAyiYFcgDmyDA4InAhJDDmrADqJHjw7GVgcMWpHXgAbh1WyODawSBynDgwifkVlsgsHPUgAFbsigBC+YUl6OZwHlBwy2ycIZuKxZX8AIoiEPDnqyFlODNj6FAVIpo4SZmOQwFp4agwEjIAAcKnevE4LXyJjGZjgM0GZxCAEcnvB5mE0iAtIRTjQaJMcHBcXgqfN0It0K9LiBOOY8NVamt2Hc4I9nmckCsWdIhGCIVCkAAmEI1dB4ViVADCEHMSxQ6IArJMRJwACoyNLCtaDOoASXkCBKYHw4QAgvJijArPxmXAAL7uoA)
```sh
--parser angular
```

**Input:**
```html
<a aria-checked="false" role="button" tabindex="0" class="btn btn-primary btn-block">Link</a>
```

**Output:**
```html
<a
  aria-checked="false"
  role="button"
  tabindex="0"
  class="btn btn-primary btn-block"
  >Link</a
>
```

**Expected behavior:**
```html
<a
  aria-checked="false"
  role="button"
  tabindex="0"
  class="btn btn-primary btn-block"
>Link</a>
```

**Comment by evilebottnawi** [comment]
It is expected, because we try to write all attributes in one line if it is fit

**Comment by evilebottnawi** [comment]
Please use search before post issues, there are lot of same
