### ISSUE TITLE
YAML Inline Extend syntax cannot be parsed

### ISSUE THREAD

**Issue by Vampire** [prettier/prettier#8876]
The blog post https://blog.daemonl.com/2016/02/yaml.html shows that there is an "inline extend" syntax where this YAML

```yaml 
foo:
 <<: &anchor
   K1: "One"
 K2: "Two"

bar:
 <<: *anchor
 K3: "Three"
```

defines this JSON
```json
{
    "foo": {
        "K1": "One",
        "K2": "Two"
    }, 
    "bar": {
        "K1": "One",
        "K3": "Three"
    }
}
```

But If I give the mentioned YAML to prettier, I am greeted with this error:
```
[error] test.yml: SyntaxError: Merge nodes can only have Alias nodes as values (2:2)
[error]   1 | foo:
[error] > 2 |  <<: &anchor
[error]     |  ^^^^^^^^^^^
[error] > 3 |    K1: "One"
[error]     | ^^^^^^^^^^^^
[error] > 4 |  K2: "Two"
[error]     | ^^^^^^^^^^^^
[error] > 5 | 
[error]     | ^
[error]   6 | bar:
[error]   7 |  <<: *anchor
[error]   8 |  K3: "Three"
```

Sending given YAML through `js-yaml` produces the exact expected result.
It would be nice if prettier would support this syntax too.

**Comment by evilebottnawi** [comment]
We should improve it on parser side firstly https://github.com/ikatyang/yaml-unist-parser/issues/273

**Comment by evilebottnawi** [comment]
Can be implemented https://github.com/ikatyang/yaml-unist-parser/issues/273, PR welcome
