### ISSUE TITLE
Expand first argument if it is an inline function.

### ISSUE THREAD

**Issue by Royce** [prettier/prettier#888]
```javascript
setInterval(function() {
  thing();
}, 500);
```
[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22setTimeout(name%20%3D%3E%20%7B%5Cn%20%20alert(%5C%22Hello%20%5C%22%20%2B%20name)%3B%5Cn%7D%2C%20500%2C%20%5C%22Bob%5C%22)%3B%5Cn%5CnsetInterval(function()%20%7B%5Cn%20%20thing()%3B%5Cn%7D%2C%20500)%3B%5Cn%5Cn%2F%2F%20The%20actual%20example%20from%20the%20codebase%20I%20want%20to%20run%20this%20on.%5Cn%2F%2F%20%20%3A%2F%5Cn_showAddActionSheet%20%3D%20debounce(function%20(component%2C%20id)%20%7B%5Cn%20%20setTimeout(function()%20%7B%5Cn%20%20%20%20component.refManager%5B'actions_'%20%2B%20id%5D.show()%5Cn%20%20%7D%2C%200)%20%5Cn%7D%2C%20500%2C%20true)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D) a slightly sprawled
```javascript
setInterval(
  function() {
    thing();
  },
  500
);
```
but my colleagues prefers the original.

Also, arrow functions with statement blocks:
```js
setTimeout(name => {
  alert("Hello " + name);
}, 500, "Bob");
```

Would you accept a PR for a `shouldGroupFirstArg` sort of thing?

**Comment by vjeux** [comment]
It's been a complaint from people at Facebook too fwiw. If you want to experiment with it, a pull request would be welcome to see what impact it has on the rest of the system.

**Comment by Royce** [comment]
Closed. See #889
