### ISSUE TITLE
Small printWidth wraps every word from string to new line in JSX/TSX

### ISSUE THREAD

**Issue by chancegraff** [prettier/prettier#8881]
An ideal fix would be to apply `htmlWhitespaceSensitivity` to the HTML within a JSX/TSX file.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgFkBPASQx3yOAB0pDDsIIAKASiUIGcZN0AcwA0DAL4MGcAB4AHCJhiFcAIz6Z8SsABtcPHoQBirQqgC2s7XDMIYBspXjUCheo2atOrhk1+-McDAArpiMbD5+kQA8ACaoAG4AfBGRkXQwACoAFqgG6kKEAO6o2tqEKkQqmBAA1gimsBDKhFBwhYTa6ERw8VikhDDmcCmpvun0INm5vPwFxaUtPVjlldV1jOgwTbiL7Z2tdCAS7qOEUQD0cUkjfhwA3DeEx8cgwiAQsoPQPMiguJjVQoABX+CB+KFw2kKuFIPzeVXwdRgAGVZPghMh+EE4G8sjAzNoAOo5eA8NEEZFg1CDeLU0jIcD6V5oKA8LAwIEaQRmXDIPDaNlvABWPGkACENGAkcjcDYADJdPmQwUgEXSZFCKwARSCEHgSoFOJAaMwbMwDJgpFkcB4YAEn2ZsgEsEJqBiMCyyAAjAAGN5OiBswkaWQMp02rC9ZkAR118E5H3BID0AFpWnAYhnmQFY6gApzcNzeUh+Sq2WZUJjMNi3jxNXAdXq4AaVTBVK73Z6kAAmN78XAlIQAYQgZh5DJtAFZmUE2RlVODS0b4tjKJnYMi7ahPgBBKAxZGWqwtuBiMRAA)
```sh
--parser typescript
--print-width 10
```

**Input:**
```tsx
interface MyInterface {
  foo(): string,
}

export abstract class Foo implements MyInterface {
  foo() {
        return (
          <div>
            	This string will be broken into a new line every time
            	{"This string will never be broken into a new line"}
          </div>
        );
      }
}

```

**Output:**
```tsx
interface MyInterface {
  foo(): string;
}

export abstract class Foo
  implements
    MyInterface {
  foo() {
    return (
      <div>
        This
        string
        will
        be
        broken
        into
        a
        new
        line
        every
        time
        {
          "This string will never be broken into a new line"
        }
      </div>
    );
  }
}
```

**Expected behavior:**
```tsx
interface MyInterface {
  foo(): string;
}

export abstract class Foo
  implements
    MyInterface {
  foo() {
    return (
      <div>
        This string will be broken into a new line every time
        {
          "This string will never be broken into a new line"
        }
      </div>
    );
  }
}
```

**Comment by evilebottnawi** [comment]
`html` and `jsx` have difference in whitespaces, sorry it is expected output and we don't want to change it

**Comment by chancegraff** [comment]
I don't understand. Is it a scope issue? Would this be fixable via a plugin, then? There's no one on Earth that would look at the HTML above and say that's appropriate in anyway. What purpose would `printWidth` even serve, then, if you're not supposed to change it from 80?

**Comment by chancegraff** [comment]
At any rate, I'll close this issue to prevent more backlog buildup.

For anyone that stumbles across this in the future, I've written some custom ESLint rules to accomplish this: https://github.com/chancegraff/eslint-plugin-wrap-params
