### ISSUE TITLE
trailing comma for TS tuple types is not printed when `trailing-comma` is `es5`

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#8886]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKgVwwBs5c0cBebAbQB0ptsAzCCAGnsaNZ97-4GChwwVADmHKAF0A3PRBsQEDDACW0AM7JQAQwBOeiAHcACvoRaUOokZ1otigEZ6dYANZwYAZQyvV45Bg9fDhFAAsYAFsiAHUw1XgNXzA4LwsE1QA3BLRkcA0HEH8NOD0YExcxSJ1kJmsSxQArDQAPACEXd08vHUi4ABl-OFr60JBmlq9-MRIARXwIeBGiBpBfPRK9PPQsDTA9VRUFNYPYGNUAExgw5AAOAAZFDEMSmJcMPOe4TczhxQBHBbwCrKSwgHQaAC0UDgcAucOOejggNUSIqOiqNSQdRWYxKkVUgWCeOmcyBw2xo0UMB0jnOVxuSAATNSXKoiNMAMIQSLVPLfACsx3wJVwtMsONWmRCAEkoPDYF59ocYABBeVedAkZYlAC+uqAA)
```sh
--parser typescript
--trailing-comma es5
```

**Input:**
```tsx
type TupleTye = [
  foo,
  loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong,
];

```

**Output:**
```tsx
type TupleTye = [
  foo,
  loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong
];

```

**Expected behavior:**

```tsx
type TupleTye = [
  foo,
  loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong,
];

```

**Comment by thorn0** [comment]
This was intentionally done in #6199.
