### ISSUE TITLE
Comment not printed

### ISSUE THREAD

**Issue by warpr** [prettier/prettier#8894]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzAlgGzjUwF5MAKcgeQCMArOMGAOgDcBDfAVyPIAd2AczjM8hNAEoA9ACpMSTOygBPTDKkTMs+ZgCCAJ33tlAHgBiBOAFkIAEzj4AfGo0BuADpQQAGhAQ+MLjoyKDshhAA7gAKYQhoyCCcEcbxvjRGYADWcDAAygJguFCCyDD6PL4AFjAAtvgA6pW48GgFcLlxzbiszcoJYGipIEVocPowUUaCNezI2JyjvnRoAB4AQhnZeew1cAAyRXBzC3BLq7lFgoQAilwQ8Mf4iyAC+qP6CTTsNA4+L-pFGD1XC2GCVZAADgADL4+PoIKN6kY+Ak4UQxqwjr4AI53eCTfzxFDsNAAWigcDg9lsf30cFxuDpkyEM0ez1GNVwpXKpxAaEuNzxRyQ8yevJg32BoPBSAATL4yuwCJcAMIQGqslBEACsfy4owAKt8iaLnqweABJKD2WC5MAAgK6a25GDKQhsuAAX09QA)
```sh
--parser babel
```

**Input:**
```jsx
const files = ((Object.values(page.files)/*: any */) /*: Array<FileModel> */);

```

**Output:**
```jsx
ensureAllCommentsPrinted/<@https://prettier.io/lib/standalone.js:17105:15
ensureAllCommentsPrinted@https://prettier.io/lib/standalone.js:17103:17
coreFormat@https://prettier.io/lib/standalone.js:17151:29
format@https://prettier.io/lib/standalone.js:17369:77
formatWithCursor@https://prettier.io/lib/standalone.js:17385:14
withPlugins/<@https://prettier.io/lib/standalone.js:32887:14
format@https://prettier.io/lib/standalone.js:32896:14
formatCode@https://prettier.io/worker.js:117:21
handleMessage@https://prettier.io/worker.js:68:18
self.onmessage@https://prettier.io/worker.js:38:14

```

**Expected behavior:**

```js
const files = ((Object.values(page.files) /*: any */) /*: Array<FileModel> */);
```

**Comment by warpr** [comment]
These are flow comments, this issue may be a duplicate of https://github.com/prettier/prettier/issues/6102

**Comment by evilebottnawi** [comment]
@warpr Let's put this example to #6102 and close in favor #6102 (easy to search)?

**Comment by warpr** [comment]
Commented at https://github.com/prettier/prettier/issues/6102 , closing this one.  Thanks @evilebottnawi .
