### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by 3ASIMA-Limited** [prettier/prettier#8895]
Hi,
  I am a beginner in web design and I wanted to edit an html templtate I copied, unfortunatly it is filled with divs like this one:

<div class="
  sqs-gallery-container
  sqs-gallery-block-grid
  sqs-gallery-aspect-ratio-square
  sqs-gallery-thumbnails-per-row-3
  
  

  
    
    
  
  sqs-gallery-block-show-meta
  
  sqs-gallery-block-meta-only-title

  
  

  
  block-animation-none
  clear"
  
  
>

causing several prettier errors.

Is  ther a way to correct these tags in order to have one line tags ?

Thank you.

**Comment by evilebottnawi** [comment]
Please use the issue template, otherwise issue was closed
