### ISSUE TITLE
Perentheses to denote conditional expression are removed.

### ISSUE THREAD

**Issue by ryanhomer** [prettier/prettier#890]
I have the following code:

    while ( (request = this.requests.shift()) ) ...

Note the extra parentheses which is used to denote that `request = this.requests.shift()`, while an assignment, is to be evaluated by `while` as a conditional expression, and is used to inform eslint that this was a conscious choice and not by error.

The obvious solution would be:

    while ((request = this.requests.shift()) !== undefined) ...

Just wondering what thoughts are out there regarding this. Is this more of a C construct that should be avoided in JavaScript or is this something that prettier should be able to handle?

**Comment by vjeux** [comment]
I implemented this yesterday ( https://github.com/prettier/prettier/commit/fa9dca362e5c71d85dc88b8cb3d7f29bafa4c474 ). If you upgrade to 0.21.0 it's now there :)

https://prettier.github.io/prettier/#%7B%22content%22%3A%22while%20(%20(request%20%3D%20this.requests.shift())%20)%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by ryanhomer** [comment]
Oh, what timing! :)

Thanks for letting me know. It's not available yet through Atom's auto update but I'll wait for it to come through on its own.

Thanks again!

**Comment by vjeux** [comment]
cc @robwise for prettier-atom. We really need to find a way to decouple the editor extensions versions from the project versions.

**Comment by robwise** [comment]
@vjeux roger that, got an issue for it here: https://github.com/jlongster/prettier-atom/issues/59
