### ISSUE TITLE
Inconsistent indentation following multi-level object passed to chained method.

### ISSUE THREAD

**Issue by plastbox** [prettier/prettier#8902]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQEsoAmCM6Mu0A8gNbYC82wAOlNtgA7oCeANhOgUmwApCLgB0AW3QBzXGABiuAB5iIAIwBWcMDAAUTFq2wBXAM5xMUdBLiCR40zEz5pugJRjMcAI7HcXgncxIgAzdGNuPQByKI8iUzBnNjJoXSiAVXNLazhYgBpmI3Z0U1MAdwhMAWFRMUdnKFcPL19-OEC4uDCI6NjguASklKg0gAUS8sqCfMLsAF83WdVk8ituINDwyP0F5jmAbmZmDBx8IlhSVYAhTAgqBDoGWY4ePmr7VU1tPQMiswsrDY7LV6i4gi0-AENl0tr1OoNcCtUhksoDcm4CoZWBxShUqsCHE4wc0fJD2tDutsYvDEojhmMJnjphjZrtDMthuh1p1KT82QdmCA8iAIEioKZkKAsLcyuMvOLkCAuWUuBLhWpMOgwPcYABlDhgFzIJzGODCgAWMAk3AA6ubcPBTAa4LqEKYHbhUA7OIqwKUhSB8FkYKNNdIpMgwtxzMKNKYlDctTrdTkADL4OCRrkxkBxpS6lzcOAARWMEHgWejZpAHEwWUVanQajg3ADbAaMBtuAIMHNyAAjAAmAAMwvbEHMNs1bEV7YGFlQmeFvnLcFDoolKBKAFooHB2u0AxC2qGZBGkFGc+YJLhjZhTcL3Y0i6XV3eHyASGouz2+0hB8KTjoLg3AuAAwhAEjniAAwAKwBv8AAqTabpe1aoKaACShDELqtLJAAgoQuowDwmYXtm1YlDAlY5gQEBgLR1YQMYMBsKxg5MXMcxAA)
```sh
--parser babel
--print-width 120
--single-quote
```

**Input:**
```jsx
var indentationOk = {
  payload: Joi.magicFix.object({
    username: Joi.string().required().default('').description('Username'),
    password: Joi.string().required().default('').description('Password'),
  })
  .optional().default({})
};

var indentationBroken = {
  payload: Joi.object({
    username: Joi.string().required().default('').description('Username'),
    password: Joi.string().required().default('').description('Password'),
  })
  .optional().default({})
};
```

**Output:**
```jsx
var indentationOk = {
  payload: Joi.magicFix
    .object({
      username: Joi.string().required().default('').description('Username'),
      password: Joi.string().required().default('').description('Password'),
    })
    .optional()
    .default({}),
};

var indentationBroken = {
  payload: Joi.object({
    username: Joi.string().required().default('').description('Username'),
    password: Joi.string().required().default('').description('Password'),
  })
    .optional()
    .default({}),
};
```

**Expected behavior:**
```jsx
var indentationOk = {
  payload: Joi.magicFix
    .object({
      username: Joi.string().required().default('').description('Username'),
      password: Joi.string().required().default('').description('Password'),
    })
    .optional()
    .default({}),
};

var indentationBroken = {
  payload: Joi
    .object({
      username: Joi.string().required().default('').description('Username'),
      password: Joi.string().required().default('').description('Password'),
    })
    .optional()
    .default({}),
};
```

**Notes:**
Indentation is inconsistent following a chained method which takes an object as a parameter, if the object forces line-breaks (either through having multiple properties or one really long one).

Of the following four snippets, three are perfectly consistent.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzOMwAsAUwCuATgDZIAEA5FjDAA4DOSA9E7YRjAJZyEB0nEVsQCGATwDmhCPigATJhQA0ZehAC2cAApTa5CvSwRCMAGrDi+OBQC+ASgA6UMmV4wsCHO3q1o9OGQBeAD4yLx8oP1c4AA8YHFsHJxc3D3hYwJDgMkgIiGI4XmIIcRw0mFsAbjI7CsdHAHdOOQh63nRMXAISPWo6RhY2Dm4+ASExSWk5BWVVDW0IXUoDI1NzSxtE51d3KE84b19-YND98Miy+M3kndKYmAyyLJzVfMLi29jK6sq6qHbsPBEUiUXoMZisdg0Yb8QS0EQSKQyeRKFTqLQ6PSzOAAJTg5mIogAMtBxGYLFY7I4tildmFDg86REChcElTrqk7g8nr48gUiiUyl8ar9Gs1Wv9OkCejQwQNIVweDCxgjJsiZmj5ot9GjcfiiSSyetKUlth5GX4GadDlFYpdTbsylzsjzXvyPuUqsKoCBFCAFlxfMhQMJCFJ6poQwh6MgQOZ6mJo76AEaEYRgADWGAAyrQ001xMgYIRLL7qGpiAB1LCceDeNNwLNRmucABuNdEMbA9ETICafmM2mE4jUwmQqHMfl9ACt6NEAEKpjPZ4QaQlNOBjidwaezrP5-IARXwEHgm+Ik5AucI-ZjSeESbgxB9l8ITRgFc4sjcyAAHAAGX02AgPwK1TWgY0GfsWw3X0AEdj3gTVoxQYR6AAWigOA4FkbDn3YeDOHYQdh1HJBx3PbcQD8NROELYtKPofc4CPE8NzIrdfRge8Py-LBkAAJk41NOGIfMAGF1BHGN9gAVmffA-AAFXvZDyIvFtLAASTkBAYCzMBX1oGAAEE5CzGBRHyM8-GsawgA)
```jsx
// "Unchained" entry point, no line-break in options passed to fetch
fetch({ url: "https://prettier.io/playground/", someProp: "shortValue" })
  .then((response) => response.text())
  .then((text) => {
    console.log(text);
  });

// "Chained" entry point, no line-break in options passed to fetch
window
  .fetch({ url: "https://prettier.io/playground/", someProp: "shortValue" })
  .then((response) => response.text())
  .then((text) => {
    console.log(text);
  });

// "Unchained" entry point, line-break in options passed to fetch
fetch({
  url: "https://prettier.io/playground/",
  someProp: "someReallyLongValue",
})
  .then((response) => response.text())
  .then((text) => {
    console.log(text);
  });

// "Chained" entry point, no line-break in options passed to fetch
window
  .fetch({
    url: "https://prettier.io/playground/",
    someProp: "someReallyLongValue",
  })
  .then((response) => response.text())
  .then((text) => {
    console.log(text);
  });
```

**Expected behavior:**
```jsx
// "Unchained" entry point, line-break in options passed to fetch
fetch({
    url: "https://prettier.io/playground/",
    someProp: "someReallyLongValue",
  })
  .then((response) => response.text())
  .then((text) => {
    console.log(text);
  });
```

**Comment by evilebottnawi** [comment]
Same problem https://github.com/prettier/prettier/issues/6094, let's close in favor https://github.com/prettier/prettier/issues/5737, can you put example to issue?

**Comment by evilebottnawi** [comment]
It is expected, we can't add indentation because, it is require adding indentation to nested objects/functions/etc and it will be ugly, sorry we don't want change current output

**Comment by evilebottnawi** [comment]
If you want to break then on each line (indentation is not required in this case) look here https://github.com/prettier/prettier/issues/5737

**Comment by evilebottnawi** [comment]
Just note - I agree that this should be improved and we will try to improve it, closed because it duplicates the problem

**Comment by plastbox** [comment]
> Same problem #6094, let's close in favor #5737, can you put example to issue?
> 
> And yes and no

Sorry, not sure what you mean here. I've added several good examples.

This does indeed seem to be the same problem as #6094, but neither is related to #5737.

**Comment by evilebottnawi** [comment]
The problem is based on the same thing, so I ask to put examples in the linked issue

**Comment by plastbox** [comment]
> It is expected, we can't add indentation because, it is require adding indentation to nested objects/functions/etc and it will be ugly, sorry we don't want change current output
I agree that double indentations should probably be avoided. I have no issue with the below rewriting of my "Expected output", as this is not really relevant to the actual issue.
```jsx
// "Unchained" entry point, line-break in options passed to fetch
fetch({
  url: "https://prettier.io/playground/",
  someProp: "someReallyLongValue",
})
.then((response) => response.text())
.then((text) => {
  console.log(text);
});
```
> If you want to break it on each line (indentation is not required in this case) look here #5737

It's not about what I want. It's about the indentation below being:
- _objectively_ bad. Items don't line up correctly.
- _objectively_ inconsistent. Antithetical to the goal of establishing a standard everyone is reasonably content with.


```jsx
// This is objectively bad
var indentationBroken = {
  payload: Joi.object({
    username: Joi.string().required().default('').description('Username'),
    password: Joi.string().required().default('').description('Password'),
  })
    .optional()
    .default({}),
};

// Either of the following alternatives are better:

// Indentation follows the property the object is assigned to. No "double indentations", but readability suffers.
{
  payload: Joi.object({
    username: Joi.string().required().default('').description('Username'),
    password: Joi.string().required().default('').description('Password'),
  })
  .optional()
  .default({}),
};

// Objectively correct indentation, good readability. Fails for single "chained" methods, e.g. replacing "Joi.object(" for "fetch(".
{
  payload: Joi
    .object({
      username: Joi.string().required().default('').description('Username'),
      password: Joi.string().required().default('').description('Password'),
    })
    .optional()
    .default({}),
};

// Objectively correct indentation, good readability. "Double indentation".
{
  payload: Joi.object({
      username: Joi.string().required().default('').description('Username'),
      password: Joi.string().required().default('').description('Password'),
    })
    .optional()
    .default({}),
};

// Possible solution to maintain readability and correct indentation for "unchained" methods without your "double indents":
{
  payload: (
    fetch({
      url: "https://prettier.io/playground/",
      someProp: "someReallyLongValue",
    })
    .then((response) => response.text())
    .then((text) => {
      console.log(text);
    })
  )
};
```

**Comment by evilebottnawi** [comment]
I do not argue with you, I just ask you to put this information in the linked issue

> The problem is based on the same thing, so I ask to put examples in the linked issue

Both issues is called by the same code sections and must be reworked together, so let's union to avoid regressions
