### ISSUE TITLE
How to format files written in supported languages but with different extensions?

### ISSUE THREAD

**Issue by Sichen-Wang** [prettier/prettier#8918]
I have files with `.wpy` extension, but the code inside is written in Vue.

How can I configure Prettier to treate `.wpy` files as `.vue` files so I can format them.

Do I need to write a plugin to do it?

**Comment by fisker** [comment]
```json
{
	"overides": [
			{
				"files": "*.wpy",
				"options": {
					"parser": "vue"
				} 
			}
	]
}
```

https://prettier.io/docs/en/configuration.html

**Comment by Sichen-Wang** [comment]
```json
{
  "overrides": [
    {
      "files": "*.wpy",
      "options": { "parser": "vue" }
    }
  ]
}
```

**Comment by Sichen-Wang** [comment]
Why `yarn prettier --check .` doesn't check `.wpy` files, it only checks files with supported extensions.

**Comment by Sichen-Wang** [comment]
@fisker Most of my `.wpy` files are under `src/components/`. After config that overrides: 

It works when I run `yarn prettier --check src/components/*`,
but if I run `yarn prettier --check src/components/`, there's an error:

```
[error] No supported files were found in the directory: "src/components/".
```

Because of that, I cannot run `yarn prettier --check .` to format both `.wpy` and `.js`. Do I need to use some globs?

**Comment by fisker** [comment]
That's a known issue, but seems we don't have an open issue about it. Can you do it?

**Comment by fisker** [comment]
See this comment https://github.com/prettier/prettier/pull/7660#discussion_r383781236
