### ISSUE TITLE
Breaks long `it` and `then` calls if using template literals

### ISSUE THREAD

**Issue by kjbekkelund** [prettier/prettier#892]
Not sure if intended or not, but hit this with template literals when upgrading to 0.21 today.

(We'll probably get rid of the template literals, though, just thought I'd open it either way in case it's unintended.)

Input:

```js
test(`does something really long and complicated so I have to write a very long name for the test`, (done) => {
  console.log("hello!");
});

test("does something really long and complicated so I have to write a very long name for the test", (done) => {
  console.log("hello!");
});
```

Output:

```js
test(
  `does something really long and complicated so I have to write a very long name for the test`,
  done => {
    console.log("hello!");
  }
);

test("does something really long and complicated so I have to write a very long name for the test", done => {
  console.log("hello!");
});
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22test(%60does%20something%20really%20long%20and%20complicated%20so%20I%20have%20to%20write%20a%20very%20long%20name%20for%20the%20test%60%2C%20(done)%20%3D%3E%20%7B%5Cn%20%20console.log(%5C%22hello!%5C%22)%3B%5Cn%7D)%3B%5Cn%5Cntest(%5C%22does%20something%20really%20long%20and%20complicated%20so%20I%20have%20to%20write%20a%20very%20long%20name%20for%20the%20test%5C%22%2C%20(done)%20%3D%3E%20%7B%5Cn%20%20console.log(%5C%22hello!%5C%22)%3B%5Cn%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
We added a special case for tests so that they do not break and only do it for string literals.

We could do it for template literals but it's a bit tricky, we need to make sure they don't have any ${} inside and do not have new lines in them.

I don't think that we should support this use case personally and just push people to use normal string literals for those.

**Comment by lydell** [comment]
Regular string literals can have newlines in them too:

```js
"line one\
line two"
```

**Comment by vjeux** [comment]
Wow, TIL!
