### ISSUE TITLE
`yarn prettier --write .` cannot format files with unsupported extensions, even though the extension has been overridden

### ISSUE THREAD

**Issue by clpud** [prettier/prettier#8924]
`yarn prettier --write .` cannot format files with unsupported extensions, even though the extension has been overridden.

```json
{
  "overrides": [
    {
      "files": "*.wpy",
      "options": { "parser": "vue" }
    }
  ]
}
```

Current solution: `yarn prettier --write '**/*.wpy'`

How to write the glob so that prettier can format `.wpy` and all extensions supported by Prettier?

**Comment by fisker** [comment]
Temporary workaround `yarn prettier --write . "**/*.wpy"`

**Comment by thorn0** [comment]
Closing in favor of https://github.com/prettier/prettier/issues/11141
