### ISSUE TITLE
Can I config Prettier to format a certain portion of Vue file?

### ISSUE THREAD

**Issue by Sichen-Wang** [prettier/prettier#8929]
Such as only format `<script>`.

**Comment by fisker** [comment]
No you can't.

You can format only html, not `script`/`style` (use `embeddedLanguageFormatting`, but not released yet)

For your case, you can turn off vue format and use `<script src="foo.js">`

It doesn't make sense not formatting html when you use `vue` parser.

**Comment by Sichen-Wang** [comment]
@fisker. Because of [`.wpy`'s strangeness when parsing html](https://github.com/Tencent/wepy/issues/2677), I don't want to format html when using `vue` parser.

Do you have some suggestions?

My current solution: disable line breaks with `"printWidth": 10000`

**Comment by fisker** [comment]
我印象中小程序好像没有行内元素吧 你可以考虑用这个

https://prettier.io/docs/en/options.html#html-whitespace-sensitivity


但注意：不安全，空白可能不对。

**Comment by Sichen-Wang** [comment]
有行内元素，老哥，text 就是行内元素。所以要想好好的 format wepy 似乎没办法了？

**Comment by Sichen-Wang** [comment]
破案了，小程序关闭标签 `>` 前加空格没问题，WePY 里就有问题，看来是没办法了

**Comment by fisker** [comment]
如果你觉得空白很重要  那就没办法了。 实际上 我一直忽略空白  https://github.com/fisker/shared-configs/blob/84a8059670cbefd699064927a7436823cd42679a/packages/prettier-config/src/global.js#L3

**Comment by Sichen-Wang** [comment]
小程序的 text 标签里把换行解析成 `<br />` 而不是空格，这就没办法了

**Comment by fisker** [comment]
实际上我很少在乎空白， 极少数情况需要考虑空白的，会用 `<-- prrttier-ignore -->`
