### ISSUE TITLE
Typescript: Inline block comment in front of method definition causes incorrect indentation

### ISSUE THREAD

**Issue by dominic-simplan** [prettier/prettier#8930]
Adding an inline block comment in front of a method definition in Typescript leads to incorrect indentation of the following lines.

**Prettier 2.0.5**
```sh
# Options (if any):
tabWidth: 4,
printWidth: 120,
```

**Input:**
```ts
export class MyClass implements MyInterface {
    /** @override */ public transform(
        prop1: string,
        prop2: string,
        prop3: string
    ): string { }
}
```

**Output:**

```ts
export class MyClass implements MyInterface {
    /** @override */ public transform(
    prop1: string,
    prop2: string,
    prop3: string
): string { }
}
```

**Expected behavior:**
Lines should be indented correctly and not be in-line with the block comment

**Comment by evilebottnawi** [comment]
Can't reproduce [link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAWQE8BhE8vASwFsNC4WEYKaBJWHGwAzYmDh5gAHSh45eAPQAqJXgACEAG5DsTACYSlCvBgCuAI0JMweGNmJRSwnCwAUM+Z5PYIGAIxIeKR2TFAA5gA0Hl5yGD4YAEyBwbrhUbIx3r4AzMkh4dFyAJR5qWGSeAC+MpUgESC+MEzQpMigxNg+AO4ACh0IrSjEhF3E1K315vZgANZwMADKGGKhYch2pnD1ABYwLIQA6ttM8KTL4gsDJ0yaJ9TI4OR1IKGkQjA99mEsxMiihG96gArUhoABC0zmi2IXAAMqE4H9hoCQCC0AtVhwAIqmCDwJEArYgZbYN7YB7mYjmOCEAC0PGecVCMAO+hg22QAA4AAz1OIQN4HewYB5xOBk7TPACOuPgn18gxAZFpUDgcAMeme2DgMqY2s+xG+vyQ-xRbxYTHW2E29VImLgOLxiJNyKJMCprL07OQCXqdmITCs4VoEBYPwe4oArM9TG8ACpUwamomaTYCAywBZgXQYGAAQSgegWMGoHAJb0qlSAA)

**Comment by dominic-simplan** [comment]
@evilebottnawi thank you for the playground link. I wan't aware that you can choose TypeScript in the options.
Seems like the wrong formatter was setup in my VSCode, as I can confirm that everything is correctly indented.
Thanks again!
