### ISSUE TITLE
Improve number format?

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8939]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6ADOgOlAjB9Abh3V0JABoQIAHGAS2gGdlQBDAJw4gHcAFTghYo2AGx5sAniyoAjDmzABrODADKNRfSgBzZDA4BXOFQAWMALaiA6qfrwmmsHDVD79AG73JycExkg2kxwHDB8CjoWbMgAZmLBVABWTAAeAEIKyqpqbBZwADLacLHxJiDJKWraOqJwAIqGEPAlogkgmhzBHL6ybLJwopTtHNow1vQAJjCmyAAc6FQ03MHWCjS+S3BdHsVUAI6N8OG0wiBsTAC0UHBwE7dDHHAH9I-hbJHRSHGtZcEW9PojL9qrUGk1il9SlQYH1xlMZkgAEzQhT0UTVADCEAsUV8WwArENDMEACp9YTfNoeYwASSgd1gajAIzoAEF6WoYJJai1ggBfPlAA)
```sh
--parser babel
```

**Input:**
```jsx
.00
1.00;
01;
```

**Output:**
```jsx
0.0;
1.0;
01;

```

**Expected behavior:**
```jsx
0;
1;
1;
```

**Comment by evilebottnawi** [comment]
We already discussed about this, can't find, but keeping `.x` notation is best for developers

**Comment by evilebottnawi** [comment]
Just intresting case:
```
12.00.toString() -> 12
12.toString() -> Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by bakkot** [comment]
> 01;

Note that this is an octal literal: `011` is `9`, not `1`. Presumably if someone intentionally wrote an octal literal it was for a reason, the same as if they wrote `0x11` rather than `17`.

**Comment by lydell** [comment]
Previous discussion about removing `.0`: https://github.com/prettier/prettier/pull/1639

**Comment by fisker** [comment]
Thank you for the links, I'll close
