### ISSUE TITLE
Ugly formatting for class implements with long type parameters

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#8943]
This is regression on master. I found this when work on #8941.
**Prettier pr-8931(Current master)**
[Playground link](https://deploy-preview-8931--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgEpzqqoCeBRpAMtAOYBy6AtnAEwA8AOlDjgCokAHOAEEATjQCuzWHSkAjOKIDyUOABouPfkLGTpMWYwWjeAdwgbufQSPFSEB+Yt4ALUXDhcAfDgCWjAVQ4fVwAISw4AElYRQAzdDA4HGAAXy4QNRAIARhfaExkUHRRUQhTAAVihAKUIlN0EgLMuVEEgGs4GABlAQTfKBpkGFEJdRBghQATSbhJynQBiXQaOAAxCFFGdBhcgeQQdAkYCAyQFxhGVAB1F194TF7Eruq73wA3O5J9sGxT-sxFDByq0aFtkPFUADMgArTAAD1CrTAHW6TDglH6cHBRChIFhcK6-RoQQAihIIPBsZCxr1RADRPsYDZMGBRL4cqcBGzYFdfJMYC5kAAOAAMmS5EABV1aAn2XLg9LeWMyAEdyfBgdkagdMABaVSzWandxq3zuYHLMFICG4gGMXxDEZjTBE0nqrHWnFjGDoOS8-mCpAsTLDdC+VBEgDCEEYVvGmAArKcJADeL6ajaxm9RtEZrAuqz2TBhFBJl0mUEqQCUikgA)
```sh
--parser typescript
```

**Input:**
```tsx
class ReallyReallyLongName2<
  TypeArgumentNumberOne,
  TypeArgumentNumberTwo,
  TypeArgumentNumberThree
> implements BaseInterface {}

```

**Output:**
```tsx
class ReallyReallyLongName2<
    TypeArgumentNumberOne,
    TypeArgumentNumberTwo,
    TypeArgumentNumberThree
  >
  implements BaseInterface {}

```

**Expected behavior(2.0.5 output):**

```tsx
class ReallyReallyLongName2<
  TypeArgumentNumberOne,
  TypeArgumentNumberTwo,
  TypeArgumentNumberThree
> implements BaseInterface {}

```

**Comment by fisker** [comment]
Is this changed by #8312?

**Comment by fisker** [comment]
That's the one.

**Comment by sosukesuzuki** [comment]
this does not happen for extends. If this is not bug, I thnik we should unify behaviors.

**Comment by fisker** [comment]
Maybe because didn't check `superTypeParameters` here. https://github.com/prettier/prettier/pull/8312/files#diff-3abca41914b4b214a2507e33cc54c28bR4483
