### ISSUE TITLE
jsx inline functions wrapping

### ISSUE THREAD

**Issue by FinnFrotscher** [prettier/prettier#896]
Hi
i want to change the way this package wraps inline functions. 
this is what happens:
```
                <li onClick={e => {
                        browserHistory.push(link);
                    }} className='hoverable' key={index}>
                    <Icon />
                </li>
```
this is what i want:
```
                <li 
                     onClick={e => {browserHistory.push(link)}} 
                     className='hoverable' key={index}>
                    <Icon />
                </li>
```

how would i go about changing this?

**Comment by vjeux** [comment]
You should be getting

```js
<li
  onClick={e => {
    browserHistory.push(link);
  }}
  className="hoverable"
  key={index}>
  <Icon />
</li>;
```

Can you make sure you are running the latest version of prettier?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cli%20onClick%3D%7Be%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20browserHistory.push(link)%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%7D%20className%3D'hoverable'%20key%3D%7Bindex%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CIcon%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fli%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by FinnFrotscher** [comment]
Atom didnt update the package. works now. thank you 👍
