### ISSUE TITLE
The end of the style attribute on the VUE code tag is automatically semicolon； as： <div style="text-align: right; margin: 0;">  。How do I cancel it?

### ISSUE THREAD

**Issue by 499190982** [prettier/prettier#8964]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

**Comment by fisker** [comment]
This is fixed https://github.com/prettier/prettier/pull/8013, please wait for `v2.1.0` release.
