### ISSUE TITLE
HTML: Base64 Data URLs in srcset are Broken

### ISSUE THREAD

**Issue by ericleong** [prettier/prettier#8965]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAlgWwOYB0oAEBAzgE5gC8uIAJgIYx1JZ3ZwD0ADlNgNwBGdYnABsAFgA06AGoAhAPIAlAO4AGANIBxbBACC+3QDkAygFUAFgFFT2AwAU9+gMJRdARQCyB3U48xDABreugEmiqoAkrqkxGJgIm7eilBupgCMss4AHgBWygBuABwAmqneAFJgluYAWmDK+gAixF76AOyNumA0+QCOmokGjaaWWaaKAQCc7ABmAKyNWgCerfpgZoqyctg1bVVZ7gYeEdgA1CI0cE45k7bBuoWyigDqABL6AGKKlvxLQd6WAA2HwAKgBrYwAVzcmCcTmo+CIZDAwhgVBAiKIBHojGYmFYHG4fEEwnEUjkSjUWh03hMFmsd10DgMLncqx8fkCwVCxnCURicQSSRS6UyPlyBRKZQMlWqdQaumaqw6XR6-UGTRGYwm03mi00K2863GW1kOz2o0O+mOZwuVxujO8jxe710Xx+f2CQNBEOhsKcWMDQeDIdDYfDEcjUejMdjcfjwYATHNVMoJJiiDimCw2FweAIhKJJDIFCoNNpHPo6VYbPpZBqjNI2d4aJCwK91NywpForF4g3kqkMtk8kVSqYKlVavUmi0DCrun0Bt5hqNxmB0Ow5omAmk7GIxCzjZttrt9lbdDbzpcnKZbvcH4+n8+X6+3++P5+v9+f-pLI9NHKVpihBV5zEhVRgjMaQlHUOYnGKCIIgoAg0kTQpU0xBFCBIdAAC84GIdEAAp8SyABaZR0BoGBzCQAgMNUTgsgASgIABmVR8jTVD0KYrJsPYAA+EAJBACBOBgdBoGIZBQDoUhSAgZQ7AUhBZJQOhAWUOgllksT+FIOgwDBOAYGMThjPQHhkBgUhITgMTzBgTBAWecx0HgYhLLAOBjHUzz0HyTylmQcBiH0kBrOEUgYDsIzsHxZAZi04QxJyYgslkIyTLM4w6EwOAABlrLgZLUsckAMqyYxrOwQE4DcSEIHgcrATSkBLJiOBSDC5zXNEzrSGsmBnmo2jkAwsTOCU4RniMzgwpmwievyMqxN6Zr4HiiSNJAIRyKgOA4EuGhBtIOBNvQC74tYJKkBS9rKuETB0Fs+znrqhqmpasqHoqsTGH4MaaPMZBE0Boz0EBOqnAgTB7pAQi5kGyFhBBOh+A0x6OvyByIigS5YGMMBhsk3RCeMGAlgatrhAAX3poA)
```sh
--parser html
```

**Input:**
```html
<img
  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAACnAQMAAAACMtNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURX9/f5DKGyMAAAAcSURBVBgZ7cExAQAAAMIg+6deCj9gAAAAAAA8BRWHAAFREbyXAAAAAElFTkSuQmCC"
  srcset="
    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAACnAQMAAAACMtNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURX9/f5DKGyMAAAAcSURBVBgZ7cExAQAAAMIg+6deCj9gAAAAAAA8BRWHAAFREbyXAAAAAElFTkSuQmCC                                                                                                                                                                              250w,
    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABQAAAANVAQMAAAAducHKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURci/52X1P44AAACcSURBVBgZ7cExAQAAAMIg+6deCU9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE8BGJMAAYTHhu0AAAAASUVORK5CYII= 1280w
  "
  sizes="(max-width: 800px) 30vw, 1280px"
/>
```

**Output:**
```html
<img
  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAACnAQMAAAACMtNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURX9/f5DKGyMAAAAcSURBVBgZ7cExAQAAAMIg+6deCj9gAAAAAAA8BRWHAAFREbyXAAAAAElFTkSuQmCC"
  srcset="
    data:image/png;base64,
    iVBORw0KGgoAAAANSUhEUgAAAPoAAACnAQMAAAACMtNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURX9/f5DKGyMAAAAcSURBVBgZ7cExAQAAAMIg+6deCj9gAAAAAAA8BRWHAAFREbyXAAAAAElFTkSuQmCC                                                                                                                                                                              250w,
    data:image/png;base64,
    iVBORw0KGgoAAAANSUhEUgAABQAAAANVAQMAAAAducHKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURci/52X1P44AAACcSURBVBgZ7cExAQAAAMIg+6deCU9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE8BGJMAAYTHhu0AAAAASUVORK5CYII= 1280w
  "
  sizes="(max-width: 800px) 30vw, 1280px"
/>

```

**Expected behavior:**
Base64 encoded data URLs in image srcsets should not have line breaks inserted after the comma, which causes them to not be rendered correctly by browsers (tested in Firefox and Chrome). Data URLs without line breaks are rendered correctly.

Similar to #8150

**Comment by fisker** [comment]
This is fixed by #8359


**Prettier pr-8359**
[Playground link](https://deploy-preview-8359--prettier.netlify.app//playground/#N4Igxg9gdgLgprEAuEAeAlgWwOYB0oAEBAzgE5gC8uIAJgIYx1JZ3ZwD0ADlNgNwBGdYnABsAFgA06AGoAhAPIAlAO4AGANIBxbBACC+3QDkAygFUAFgFFT2AwAU9+gMJRdARQCyB3U48xDABreugEmiqoAkrqkxGJgIm7eilBupgCMss4AHgBWygBuABwAmqneAFJgluYAWmDK+gAixF76AOyNumA0+QCOmokGjaaWWaaKAQCc7ABmAKyNWgCerfpgZoqyctg1bVVZ7gYeEdgA1CI0cE45k7bBuoWyigDqABL6AGKKlvxLQd6WAA2HwAKgBrYwAVzcmCcTmo+CIZDAwhgVBAiKIBHojGYmFYHG4fEEwnEUjkSjUWh03hMFmsd10DgMLncqx8fkCwVCxnCURicQSSRS6UyPlyBRKZQMlWqdQaumaqw6XR6-UGTRGYwm03mi00K2863GW1kOz2o0O+mOZwuVxujO8jxe710Xx+f2CQNBEOhsKcWMDQeDIdDYfDEcjUejMdjcfjwYATHNVMoJJiiDimCw2FweAIhKJJDIFCoNNpHPo6VYbPpZBqjNI2d4aJCwK91NywpForF4g3kqkMtk8kVSqYKlVavUmi0DCrun0Bt5hqNxmB0Ow5omAmk7GIxCzjZttrt9lbdDbzpcnKZbvcH4+n8+X6+3++P5+v9+f-pLI9NHKVpihBV5zEhVRgjMaQlHUOYnGKCIIgoAg0kTQpU0xBFCBIdAAC84GIdEAAp8SyABaZR0BoGBzCQAgMNUTgsgASgIABmVR8jTVD0KYrJsPYAA+EAJBACBOBgdBoGIZBQDoUhSAgZQ7AUhBZJQOhAWUOgllksT+FIOgwDBOAYGMThjPQHhkBgUhITgMTzBgTBAWecx0HgYhLLAOBjHUzz0HyTylmQcBiH0kBrOEUgYDsIzsHxZAZi04QxJyYgslkIyTLM4w6EwOAABlrLgZLUsckAMqyYxrOwQE4DcSEIHgcrATSkBLJiOBSDC5zXNEzrSGsmBnmo2jkAwsTOCU4RniMzgwpmwievyMqxN6Zr4HiiSNJAIRyKgOA4EuGhBtIOBNvQC74tYJKkBS9rKuETB0Fs+znrqhqmpasqHoqsTGH4MaaPMZBE0Boz0EBOqnAgTB7pAQi5kGyFhBBOh+A0x6OvyByIigS5YGMMBhsk3RCeMGAlgatrhAAX3poA)
```sh
--parser html
```

**Input:**
```html
<img
  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAACnAQMAAAACMtNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURX9/f5DKGyMAAAAcSURBVBgZ7cExAQAAAMIg+6deCj9gAAAAAAA8BRWHAAFREbyXAAAAAElFTkSuQmCC"
  srcset="
    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAACnAQMAAAACMtNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURX9/f5DKGyMAAAAcSURBVBgZ7cExAQAAAMIg+6deCj9gAAAAAAA8BRWHAAFREbyXAAAAAElFTkSuQmCC                                                                                                                                                                              250w,
    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABQAAAANVAQMAAAAducHKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURci/52X1P44AAACcSURBVBgZ7cExAQAAAMIg+6deCU9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE8BGJMAAYTHhu0AAAAASUVORK5CYII= 1280w
  "
  sizes="(max-width: 800px) 30vw, 1280px"
/>
```

**Output:**
```html
<img
  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAACnAQMAAAACMtNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURX9/f5DKGyMAAAAcSURBVBgZ7cExAQAAAMIg+6deCj9gAAAAAAA8BRWHAAFREbyXAAAAAElFTkSuQmCC"
  srcset="
    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAACnAQMAAAACMtNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURX9/f5DKGyMAAAAcSURBVBgZ7cExAQAAAMIg+6deCj9gAAAAAAA8BRWHAAFREbyXAAAAAElFTkSuQmCC                                                                                                                                                                              250w,
    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABQAAAANVAQMAAAAducHKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAADUExURci/52X1P44AAACcSURBVBgZ7cExAQAAAMIg+6deCU9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE8BGJMAAYTHhu0AAAAASUVORK5CYII= 1280w
  "
  sizes="(max-width: 800px) 30vw, 1280px"
/>

```
