### ISSUE TITLE
Needs to have an installation.md file included

### ISSUE THREAD

**Issue by manula2004** [prettier/prettier#8973]
I noticed that this repository does not have an installation.md file included. I think it's better to have an installation guide in the repository itself rather than a link to the guide in the web page. If you think this needs to be resolved, I can create an installation.md file or include the installation guide in the readme.md file. Please respond to this quick; saying weather I need to do contribute on this or not

**Comment by fisker** [comment]
https://github.com/prettier/prettier/blob/master/docs/install.md
