### ISSUE TITLE
Improve `<textarea>` format

### ISSUE THREAD

**Issue by danrneal** [prettier/prettier#8980]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeARhAJgTwHyrwAeMAhgE5ykAEYANqQM6MC8A5AGYTkC2AtJFjkIdalAh8AbqToBLLKXhtq89qTAxujZVFI84ajVuXCA7qzYAWNnmDB1m8owC+z1AHpiZSqTwAdKBAAGhAIAAcYWWhGZFAKMwAFCgQYlBlTUhwYkPRydQBrOBgAZTD1WSgAc2QYcgBXOBCACxgeOgB1Jtl4RjKwOGKU7tlJbpxkEEZa2Q1gkArGOHIYBLzKnlJkDhlFkIArRiIAITywQpK9OAAZCrgtncaQA6Jiisq6OABFOoh4e7pdiAyk4lhMWm05mFyBUYO15DAmsgABwABhCUIgi3aeTCEyhcEW5EkdxCAEcfvBVuFUiAmHwoHA4FgmXNKOTZJRVqR1pskNsAY9FjxZDV6oK3h9vr87nyHiEyOg4VgEcgAEzyvKyORVADCEB4GwmBIArHM6osACqkdCpfmAyQNACSUGZsGKYGhEQAgi7ijAcB9-otXEA)
```sh
--html-whitespace-sensitivity strict
--parser html
```

**Input:**
```html
<body><textarea class='form-control no-validate' id='actors' name='actors' rows='4'>{{actors}}</textarea>

```

**Output:**
```html
<body>
  <textarea class="form-control no-validate" id="actors" name="actors" rows="4">
{{actors}}</textarea
  >
</body>

```

**Expected behavior:**
```html
<body>
  <textarea class="form-control no-validate" id="actors" name="actors" rows="4"
    >{{ actors }}</textarea
  >;
</body>
```

When html-whitespace-sensitivity is set to strict it should respect the whitespace for the textarea tag.  It should do it even if it is set to css but as can be seen it does not.  So when pre-filling a textarea field, it make a ugly whitespace at the beginning.

**Comment by fisker** [comment]
You didn't choose the right parser 

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeAPGBDATnbAAjABtsBncgXgHIAzCXAWwFpJZcITCoIWA3bCQCWAE2zwahMbWxgYjclKjYmcWfMVTOAd2o0ALDQB8wYHIW5yAX2uoA9Jhz5sxgDpQQAGhAQADjDC0OTIoHi6AAp4CCEoQjrYAJ4hPgBGuHIA1nAwAMp+csJQAObIMLgArnA+ABYwTCQA6jXC8OQFYHC5Ma3C-K2JyCDk5cLy3iBF5HC4MBEZxUzYyHRC0z4AVuQYAEIZYNl5qnAAMkVwK2vVIFsYuUXFJHAAihUQ8Jck6yAFVjNDdQaEz8uCKMEaYhgNWQAA4AAw+EEQaaNDJ+IYguDTXD8C4+ACOb3g838sRAFBYUDgcFENIm+EJwnw82wi2WSFWX2u0yYwjKlW5Dyer3eFw5Vx8OFSENEUOQACZJRlhCISgBhCBMJZDLEAVgmFWmABVsKlYpzvvwqgBJKC02C5MCggIAQTtuRgiSen2mtiAA)
```sh
--html-whitespace-sensitivity strict
--parser html
```

**Input:**
```html
<textarea class='form-control no-validate' id='actors' name='actors' rows='4'>{{actors}}</textarea>

```

**Output:**
```html
<textarea class="form-control no-validate" id="actors" name="actors" rows="4">
{{actors}}</textarea
>

```

**Comment by danrneal** [comment]
This still leaves an ugly whitespace at the beginning of the text area since the no-whitespace is not preserved between the opening tag and content.

In addition and it may be a separate cause, but inside of a handlebars template, this not the result I get.

**Comment by fisker** [comment]
What parser are you actually using? With different parser, they are different issue.

**Comment by danrneal** [comment]
I am using html parser.

When this bit of code is placed in the body of the output code I get the result you posted.  Which creates a whitespace in the beginning of the textarea

When this bit of code is placed between script tags in a handlebars template (`<script type="text/x-handlebars-template"></script>`) then I get output code I posted with whitespace at the beginning and end of the textarea.

**Comment by danrneal** [comment]
![Example of the whitespace at the beginning of the textarea](https://i.imgur.com/R5uWjgw.png)

**Comment by fisker** [comment]
1. `html-whitespace-sensitivity` don't work for `glimmer` parser (`<script type="text/x-handlebars-template"></script>` is embed, and use `glimmer` parser)
2. For `html` parser, I didn't see a broken case, but if you want it improved, that's a different issue

**Comment by danrneal** [comment]
The above screenshot doesn't constitute a broken case?  That is when the textarea is in the body of the html.

**Comment by fisker** [comment]
For `html`, No. 
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeARhAJgTwHyrwAeMAhgE5ykAEYANqQM6MC8A5AGYTkC2AtJFjkIdalAh8AbqToBLLKXhtq89qTAxujZVFI84ajVuXCA7qzYAWNnmDB1m8owC+z1AHpiZSqTwAdKBAAGhAIAAcYWWhGZFAKMwAFCgQYlBlTUhwYkPRydQBrOBgAZTD1WSgAc2QYcgBXOBCACxgeOgB1Jtl4RjKwOGKU7tlJbpxkEEZa2Q1gkArGOHIYBLzKnlJkDhlFkIArRiIAITywQpK9OAAZCrgtncaQA6Jiisq6OABFOoh4e7pdiAyk4lhMWm05mFyBUYO15DAmsgABwABhCUIgi3aeTCEyhcEW5EkdxCAEcfvBVuFUiAmHwoHA4FgmXNKOTZJRVqR1pskNsAY9FjxZDV6oK3h9vr87nyHiEyOg4VgEcgAEzyvKyORVADCEB4GwmBIArHM6osACqkdCpfmAyQNACSUGZsGKYGhEQAgi7ijAcB9-otXEA)
```sh
--html-whitespace-sensitivity strict
--parser html
```

**Input:**
```html
<body><textarea class='form-control no-validate' id='actors' name='actors' rows='4'>{{actors}}</textarea>

```

**Output:**
```html
<body>
  <textarea class="form-control no-validate" id="actors" name="actors" rows="4">
{{actors}}</textarea
  >
</body>

```

but for embed `glimmer`, yes.



Can you update the example?

**Comment by danrneal** [comment]
I updated my OP with the example.  The ">" should be dropped to line 3 in order to respect the whitespace at the beginning of the textarea

**Comment by fisker** [comment]
I updated the issue title.

**Comment by fisker** [comment]
@danrneal  What do you think, how should  we format this case?

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeARhAJgTwHwA6UABMavAB4wCGATnNcWADbUDObAvAOQBmEtALYBaSLFoRmxKBGEA3aswCWWavG7EVPamBgC2GqNUFxtu-RokB3LtwAs3PMqhxiARiLPXAJk9KXxADMfgF2Ia4ArKgA9JQ09NSEUCAANCAQAA4wStBsyKB01gAKdAh5KIpW1Dh5aei0OgDWcDAAyhk6-gDmyDC0AK5waQAWMILMAOrDSvBsHWBwrWUzSnIzOMjgHKkg-mxwtDBFDV2C1Mi8ivtpAFZsFABCDWDNbcZwADL+cBdXQyB3CitbrMOAARX6EHgv2Y1xAHVo+1om1G4x2GVo-hgExUMGGyAAHAAGNIYiD7CYNDKbDFwJFyH5pACOkPgx0y5RA7GELjgWD5O3oLKU9GO1FO5yQl1h-32giUvQGspB4NZPylfzSNHQOKweOQ3i1DSUzi6AGEIIIzps6REdv19gAVajocrSuFyQYASSg-NgrTAmKyAEFfa0YDhQTD9gBfGNAA)
```sh
--parser html
```

**Input:**
```html
<body>
  <textarea class='form-control no-validate' id='actors' name='actors' rows='4'>line 1
line 2
line 3
line 4
line 5</textarea>

```

**Output:**
```html
<body>
  <textarea class="form-control no-validate" id="actors" name="actors" rows="4">
line 1
line 2
line 3
line 4
line 5</textarea
  >
</body>

```

**Comment by danrneal** [comment]
To be consistent with the rest of Prettier I would think you would want it like this:

```html
<body>
  <textarea class="form-control no-validate" id="actors" name="actors" rows="4"
    >line 1
      line 2
      line 3
      line 4
      line 5</textarea
  >
</body>
```

**Comment by fisker** [comment]
No, this will change value of textarea 

![image](https://user-images.githubusercontent.com/172584/90308236-6f6b5f80-df10-11ea-8fa2-e61d39cc2d2b.png)

**Comment by danrneal** [comment]
I suppose then the next best alternative would be:

```html
<body>
  <textarea class="form-control no-validate" id="actors" name="actors" rows="4"
    >line 1
line 2
line 3
line 4
line 5</textarea
  >
</body>
```

While not particularly pretty, multiline textarea fields are by their nature ugly in html, and I thing this solves the whitespace issue and makes it less ugly.... or prettier if you will.

**Comment by fisker** [comment]
I guess the output from playground is not that bad.

**Comment by danrneal** [comment]
The main issue is the whitespace (newline) that it inserts between line 2 and line 3.  If the > is dropped down to the next line, the whitespace issue is solved

**Comment by fisker** [comment]
I already told you, there is no  "whitespace issue", go test yourself or read [the spec](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody]

> If the next token is a U+000A LINE FEED (LF) character token, then ignore that token and move on to the next one. (Newlines at the start of textarea elements are ignored as an authoring convenience.)

**Comment by danrneal** [comment]
Ah... So you right.  I could have sworn I tested and got whitespace.... but I guess I was wrong.  My mistake.  Then you are correct that the output from the playground is pretty much the best you can do.

**Comment by kingy86** [comment]
Not sure if anyone else is having this issue but on my end, it seems to self close the textarea.
