### ISSUE TITLE
Question: usage in GreaseMonkey/TamperMonkey script

### ISSUE THREAD

**Issue by DonaldTsang** [prettier/prettier#8985]
There has been a discussion regarding the usage of Prettier as a formatter for webpages. https://github.com/lelinhtinh/Userscript/issues/77
But according to the documention, the only way to use it is through the commandline. Is that correct?

**Comment by evilebottnawi** [comment]
You can use API https://prettier.io/docs/en/api.html

**Comment by DonaldTsang** [comment]
As a response https://github.com/lelinhtinh/Userscript/issues/77#issuecomment-674517541

**Comment by evilebottnawi** [comment]
@DonaldTsang Yes, what else can I help?

**Comment by DonaldTsang** [comment]
Not really, except I hope that there could be some way of explaining how code can be integrated into webpages vs GreaseMonkey scripts.

**Comment by evilebottnawi** [comment]
@DonaldTsang What do you want achieve please clarify

**Comment by DonaldTsang** [comment]
There has been no clarification regarding how GreaseMonkey scripts can integrate certain types of JS scripts, either directly or in the form of modules... it might be a good idea to document them.

**Comment by evilebottnawi** [comment]
@DonaldTsang I think it is out of scope prettier documentation, it should be part of `GreaseMonkey`

**Comment by DonaldTsang** [comment]
I know it is out of scope, this is more of a personal issue while we still have time to talk.

**Comment by evilebottnawi** [comment]
@DonaldTsang What do you want to hear from prettier team?

**Comment by DonaldTsang** [comment]
If someone imports a normal "raw" js file they can directly use the function, but if it is a module, how would one go about using it?
