### ISSUE TITLE
Escape non-printable characters

### ISSUE THREAD

**Issue by Skalman** [prettier/prettier#8995]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOEA2cB0mIDmAFADogAScm+g0AQAqAFnAE5xkCUA3CVCADQgIABxgBLdMlABDZswgB3AAoyEaZCCmZ5UgJ5qBAI2ZSwAazgwAykJOioBZDGYBXOAIYwAtpgDqDUfBoNmBwlqoBogBuATrqYGj6IHZoLDCKxgSeUsgAZpopAgBWaAAeAELGZhaWUp5wADJ2cLn5biDFJZZ2BNgAis4Q8C2YBSA2zCnM6gZSBlT8Y8x2MD6iACYwDMgAHAAMAkJyKT7GQuqHcJORzQIAjgPw6cJqKFJoALRQcHBrPwus91ErHSUky2SQeRGbRSnlEjhc0O6fQezQhrQEMFmqw2WyQACYMcZRJhugBhCCeLLqS4AVgWzhSdFmL0ho0irgAklBfrBLGAliIAILcywwHTYYYpAC+UqAA)

**Input:**

```jsx
console.log("Hello​World");
```

**Output:**
_not changed_

**Expected behavior:**
```jsx
console.log("Hello\u200bWorld");
```

There's a zero-width space between `Hello` and `World`. Usually, when these types of characters are added to the source code, it's a mistake, and depending on the editor it may well be invisible and therefore very hard/annoying to debug.

I'd suggest automatically reformatting some characters by using their escape sequences instead.

## Whitespace

I've personally had problems with `U+200B zero-width space` and `U+00A0 non-breaking space`.
But I think it's reasonable to escape all space characters except `U+000A newlines` (and probably carriage `U+000D returns`), `U+0020 spaces` and `U+0009 tabs`.

Here are other space chars: `U+1680 U+2000 U+2001 U+2002 U+2003 U+2004 U+2005 U+2006 U+2007 U+2008 U+2009 U+200A U+2028 U+2029 U+202F U+205F U+3000 U+000B U+000C U+0085 U+202F U+2007 U+2060`

## Text direction

I've personally had problems with the `U+200E left-to-right mark` showing up unexpectedly. I don't _think_ it would annoy anyone, but if you want to be conservative, it could be escaped only when the rest of the string is ASCII.
If you don't want to be conservative, we should also escape the `U+200F right-to-left mark`.

## Soft hyphens

`U+00AD Soft hyphens` also usually don't render at all. Escape them too.

## Other control characters

I don't think I've personally ever needed other control characters automatically escaped, but I don't see why not.
A conservative approach would be to skip these until someone has had a problem.
Here's a list: https://www.fileformat.info/info/unicode/char/200f/index.htm

**Comment by evilebottnawi** [comment]
Sorry, it is out of scope prettier, you can use linter for this purpose
