### ISSUE TITLE
Inline comment moves to next line when placed after single-line if statement

### ISSUE THREAD

**Issue by r0gi** [prettier/prettier#8996]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBSSgE1RlWgEpM8BnCAGzgDoaIBzbAHXGkOOkxgCcArnA6kA3JgD0kilyIkofISKhwalOLKjU6jFu04F5vdAEN1IkOKky83BZjMW2UEABoQEAA49tyUKb8-BAA7gAKgQiUyCDmIaYAntEeAEb8pmAA1nAwAMpeGahQzMgCwh4AFjAAtjQA6hVEcJQFYHC5UfIAbkQJMWCUyWjacPwwYenM1abIThoeAFaUAB4AQulZObmm1XAAMkVws+bzIEvLuUXMdACKghDwxxYeBfwa-DEppilq7iBe-CKMDqqHwMAqyAAHAAGF7BDR1dJeGIA5qjLpHDwAR3u8Am3miKFMlAAtKo4PgKX9+HAcagaRNTFMZkg5nAPBpqqhSsoOVdbrijqyTuyQDBviCwRCkAAmDwCUyoGhXADCEGq0xizQArH9BBoACrfQlsjxdYQASQICDyYEBPgAggRcjAEnQnhoAL6eoA)
```sh
--parser babel
```

**Input:**
```jsx
if (condition) console.log("condition true"); // condition true
else console.log("condition false"); // condition false

```

**Output:**
```jsx
if (condition) console.log("condition true");
// condition true
else console.log("condition false"); // condition false

```

**Expected behavior:**
```jsx
if (condition) console.log("condition true"); // condition true
else console.log("condition false"); // condition false

```

This makes it confusing to read the comment because generally comments that are on their own line refer to the code below them.
Ideally the comment should stay on the same line, but if it has to be moved for some reason, then the line above the `if` statement would make more sense.

This closed issue seems to be related: #3294.

**Comment by evilebottnawi** [comment]
Please read answer, it is not easy, but no need duplicate, we tracked issue here https://github.com/prettier/prettier/issues/807, just put your example there, anyway thanks for the issue
