### ISSUE TITLE
Add parens back for yielding jsx

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8999]
`Espree` throws error when yielding JSX without parenthesis.

Related issue 

- https://github.com/eslint/espree/issues/355
- https://github.com/acornjs/acorn-jsx/issues/82

It has been a long time since these issues, and it's still not fixed.

I suggest put parens back.

This will revert #7367 

//cc @cola119 @brainkim

**Comment by fisker** [comment]
```text
require('espree').parse('function * a() {yield (<JSX/>)}', {ecmaVersion: 2020, ecmaFeatures: {jsx: true}}).body[0].body.body[0]
Node {
  type: 'ExpressionStatement',
  start: 16,
  end: 30,
  expression: Node {
    type: 'YieldExpression',
    start: 16,
    end: 30,
    delegate: false,
    argument: Node {
      type: 'JSXElement',
      start: 23,
      end: 29,
      openingElement: [Node],
      closingElement: null,
      children: []
    }
  }
}
```


```text
require('espree').parse('function * a() {yield <JSX/>}', {ecmaVersion: 2020, ecmaFeatures: {jsx: true}}).body[0].body.body[0]
Uncaught [SyntaxError: Unexpected token <
] {
  index: 22,
  lineNumber: 1,
  column: 23
}
```

**Comment by brainkim** [comment]
Hm I’m usually using typescript parsers so I never noticed this. I’m okay with this I guess.

**Comment by cola119** [comment]
Sorry for the late reply. Well, thank you!

**Comment by brodybits** [comment]
I think the motivation was not clear enough in the description. I gave my understanding of the motivation in <https://github.com/prettier/prettier/issues/9173#issuecomment-689944586>, which is now down to the following:

> * Output would lead to syntax error if it is parsed by an old version of `eslint`. While I would rather see users upgrade to latest `eslint` version, this should be considered to be a breaking change.
