### ISSUE TITLE
why set `printWidth=120` will cause multiple line properties to one line?

### ISSUE THREAD

**Issue by llcat** [prettier/prettier#9005]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPAISJhmgAoBKPYAHSjz2zhiOxdGnbtwA8AIzoMoI0dzAAbAIYBnVQDllAWzgBeAOQZe9cnGwBaJWtUG588gBNDxvhXMWndrvLzQAworkYADWesAwABbkqgB0kcpQjopwgcEhAL72eAB82dxpoXgAEuZw2WIA9FL00Hk+zADcnBkgADQgEBgU0KrIoMrY2BAA7gAKgwh9KMqKI8oAnn0dEtjKoXwAyhjr5FAA5sgw2ERwHZEw2ooA6tHwqjtgcJtT5BQAbm8LyODq7SB7VTmGBjNb7bTKZAEWZAjoAK1UaGoaw2ME2OjgABk9nAoTCziAEWhNnt9ikAIpECDwPGKWEgHbYIHYH4SZQSOCKf7GPYwa5OKLIACMACYAAwdYwQIHXNYYH6uZnvXEdACOVPgoK60xAagsUDgcEcRv+vHV5F4oOU4MhSGhdIJQO05COJ0dpIpGtxdvxHRg7P5jkFSBFfrW5CCB38EG0EJ+cFUAFZ-kQgQAVdnTe3096nACSSQQaLA2HI3QAgklNjAFilaUCMhkgA)
```sh
--parser babel
--print-width 120
```

**Input:**
```jsx
export function Button() {
  return (
    <button
      className='prettier-class'
      id='prettier-id'
      onClick={this.handleClick}
    >
      Click Here
    </button>
  );
}
```

**Output:**
```jsx
export function Button() {
  return (
    <button className="prettier-class" id="prettier-id" onClick={this.handleClick}>
      Click Here
    </button>
  );
}

```

**Expected behavior:**
hope output as the input

**Comment by evilebottnawi** [comment]
Because line fits in 100 characters

**Comment by llcat** [comment]
> Because line fits in 100 characters

ok, that make me confused, set 80 will keep the mulitiple line, i think this fits in 80 characters too. i don't want turn my multiple line to one line

**Comment by evilebottnawi** [comment]
@llcat original code can't fit in 80 characters

**Comment by llcat** [comment]
@evilebottnawi thanks for your reply ! you're right, I have count it, it's not fit 80, I think I may not understand what `printWidth` mean, in my opinion, the single property `className='prettier-class'` is a new line, but prettier considerthe whole tag content as a line. 😄
