### ISSUE TITLE
Auto removing the parentheses causes unexpected result

### ISSUE THREAD

**Issue by Mert1980** [prettier/prettier#9018]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMGAGn2HwFcBnOAZRhPnwF98AzHCdfAB0QOUuWEBuQVAzY81fJChQ45Tjz4DhosjAC0ogCa0AHpOmzcBGuhIBrZjACeAGzj11vfkJAABW-A4qCQuerSoAPSQohH0zm705jJYVvgACiSYcDga3sL+bNnBoeFRuHARGVk4SZbyACokAEYeXlp+AUUhYZHRFY0ttSkNzbntBYHFPWUxA0NyBADCJDiGYz465HpNEBAwcTiZEcur86kAQrQwMNDr2mL6O3sHR5fX0GfywgB032UpKlg9AiAEFMJhvmB6IkQFIoNIlHE6IwWK53PgALz4WwOVEJAAUwGk+HwfD2SGoxJJPDcJgA4nwAO4UgCMFCpJMZqEMMAAFhThABWAAMAFJhOyoNTsSsAOaoKAAGTg3BgApAACZBeKQJKSRxJRwAJRw6TcWhQcioW4ARVo7hg1qgA3o+MwfEw9CNlKlimgSLALhI0PRWIYjjRrpNVMRBAA2gA3EL2qiMGAANWTcAAupjkY5CvjhdHfYiIG5vi4ILL8cIky57fgkBL8PX7SWSWWK1Wa8ISFdeXBDABVRg5Zu6-DuiCe779vlD0fZEsx-0EXkkKCGNyLDdQWVwPP4uAJhCUfAqRmZhtwb0YgB8Pulaev9vxl9ft7h+tNvoiET9KAkVQegQSAxlsiHI9wxwABJAARO9HxghDMQxLFp1nedBxHMdv3wf9AOA+hhygTd6AgoxoLHBCkPzOD4LQjCPXoOcB0XPCqVEGBaBwKVa19EkAB5DFQBNFCDaEADkSHQOAMWEABHe04idGF7w5akhKqbIJODegZLkjFgEDfT3G+MkYA4DTBOlfAhJdTS7NbLNjLbOAOCcuzoF3TcD2MvdtzgXz9w8rzpQVUSwDYXBFnLXAFJAd0MBWJxhHC6l4BMGA4qrHBEuS2wcDSkAMs7M9IMMDKbOc6UHNGIMmjgFxEtI8jKKHYQCJq2rhIGfBGuaxKwIoyquoiHrnKEiIXUmrTKkybI5uE0TxNM6TZPkpSVMdaA9Gi04QGW6lgAAeSaAArVQYG+dzXUw1jlIdNSjW+WxMHxfEntU6A6KJWznMI1BuHwL6dqdb4Z12qBTpUb4T2yJx8RAkaOsMb0AB8Mfwb7ochzBodhuB4dPYrkdA8DKqNf6yoIgDPIBuzuN4qV3KY-AWVpkkAH5QdxiGoadInbr2cyFUDWhDHcN0WLYhdcOXfAsa5uz+egfHofqRkIBF+BWPFhspfu2XsI45dvQAMgt0GVamk41gcJxjLVqBvm5Lg4jRYyaC5Hl+R8FkAA5RHQLqOGs23aqE+3vlg9BZUj3qkyCTcYESm5MHSxnet6+gcDAYyHu+GD6DjF25d5XBsznJNWBwYdCEVBmc5b7rE7s6OVkMb5zggQwnGO1uO5j+pUBgNx7wAdQgWgXDWABNGeiDYQccGmkex4n9u7a7756jgbL72AcvBegYWsqs9fd-3w-t+H6+D5ge9cEAMgIr9WPfH8HoetLeG5WZWMEWABUghFRKveVGuk7TPWgNNP+0Bv5D3ft3Xu-dEE52Qeg5yRoVYUjZuhLEwp8BW3bviAAhCfAmQs4YJlFvrS0htpZF1NgrHAlsLbtwoeDdWp9nTa11mLBhksmEm3Yqwo07CbbZ1bp3VY+BHbO24a7d2+BPZuG9vgX2fJ1RBxDmHCO0ikExzjgnQxP9k5ALTsIDOWcf45zzgXYARcS5lyURXKuNc2ArAbk3O+JIJp+PsjHVBA9AnCQ3uPOAU8Z5z3wIvWgy8Fxr2ONfTeUSwlBIfofY+bjeHn0fhwZBn9b5mKMVkp+r8ik3yfhkoS8CAEp2AcIQqqVhAQMpjkaBP0oBwKuP-LBGCUkfxCQMqaQzDCjOpB2Wqxpm4dwiKtOa01FlUhLAzM0ForS3HeiwQo9QIBpBYoSei9AqAu1OfgFhS4cjGifKSOAPE+J3JJCXPU1JzlvJJFcscbyOBwnWSoEwCx8BS24P2FwBAlAqHIPiHZrB4D7MOTOL0+Iuma2aF6OEuoQC8PoMgUAKwmQZFEEBZAIAQiMhIE4PFFAQBNEOGABwMAmCYDIAqWUyAYA4BTCAXkMB0AuEnryMe7hWVgGYAgegY8xJjycGSqENK0BAWyDAQ5JBZS2GQGClwjBaUXXoCYc4DKmVME2oqBUcAtUhF1SAfVJgmDsrcHaUWVqdVwFpaynAY4yVNGaM1bFyVYCT25HyZAgdhQer4IwSehxMBkvdO4bIp5sXKVFkiz0ZLgx6BUEOIc2LRDKVQKINVGqSCuptYwdAqBOXcvdSAKV+4nW0BdUgbVNrWBNGDX7ZAGpaVcpIKgFw7K4roE1SgdwgpsXhhdOWutCZ7SwS3GeJgYAggEzAoYPElrW3Wo8hwIAA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
return value === 1
            ? (question.optionOne.votes.includes(props.authedUser) ||
                question.optionTwo.votes.includes(props.authedUser)) && (
                  <Card key={question.id} style={{ width: "18rem" }}>
                    <Card.Img
                      variant="top"
                      src={props.users[question.author].avatarURL}
                    />
                    <Card.Body>
                      <Card.Title>Would You Rather</Card.Title>
                      <Card.Text>{question.optionOne.text}</Card.Text>
                      <Card.Text>or…</Card.Text>
                      <Button variant="primary">Answer Question</Button>
                    </Card.Body>
                  </Card>
                )
```

**Output:**

```jsx
return value === 1
            ? question.optionOne.votes.includes(props.authedUser) ||
                question.optionTwo.votes.includes(props.authedUser) && (
                  <Card key={question.id} style={{ width: "18rem" }}>
                    <Card.Img
                      variant="top"
                      src={props.users[question.author].avatarURL}
                    />
                    <Card.Body>
                      <Card.Title>Would You Rather</Card.Title>
                      <Card.Text>{question.optionOne.text}</Card.Text>
                      <Card.Text>or…</Card.Text>
                      <Button variant="primary">Answer Question</Button>
                    </Card.Body>
                  </Card>
                )
```

**Expected behavior:**
If I save the file, the parentheses surrounding the `array.includes` methods are auto removed and that causes an unexpected result. But, as seen from the snippet line 51-52 it works fine now. That makes me confused!

**Comment by evilebottnawi** [comment]
You can find what we don't remove your parentheses around [includes](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMGAGn2HwFcBnOAZRhPnwF98AzHCdfAB0QOUuWEBuQVAzY81fJChQ45Tjz4DhosjAC0ogCa0AHpOmzcBGuhIBrZjACeAGzj11vfkJAABW-A4qCQuerSoAPSQohH0zm705jJYVvgACiSYcDga3sL+bNnBoeFRuHARGVk4SZbyACokAEYeXlp+AUUhYZHRFY0ttSkNzbntBYHFPWUxA0NyBADCJDiGYz465HpNEBAwcTiZEcur86kAQrQwMNDr2mL6O3sHR5fX0GfywgB032UpKlg9AiAEFMJhvmB6IkQFIoNIlHE6IwWK53PgALz4WwOVEJAAUwGk+HwfD2SGoxJJPDcJgA4nwAO4UgCMFCpJMZqEMMAAFhThABWAAMAFJhOyoNTsSsAOaoKAAGTg3BgApAACZBeKQJKSRxJRwAJRw6TcWhQcioW4ARVo7hg1qgA3o+MwfEw9CNlKlimgSLALhI0PRWIYjjRrpNVMRBAA2gA3EL2qiMGAANWTcAAupjkY5CvjhdHfYiIG5vi4ILL8cIky57fgkBL8PX7SWSWWK1Wa8ISFdeXBDABVRg5Zu6-DuiCe779vlD0fZEsx-0EXkkKCGNyLDdQWVwPP4uAJhCUfAqRmZhtwb0YgB8Pulaev9vxl9ft7h+tNvoiET9KAkVQegQSAxlsiHI9wxwABJAARO9HxghDMQxLFp1nedBxHMdv3wf9AOA+hhygTd6AgoxoLHBCkPzOD4LQjCPXoOcB0XPCqVEGBaBwKVa19EkAB5DFQBNFCDaEADkSHQOAMWEABHe04idGF7w5akhKqbIJODegZLkjFgEDfT3G+MkYA4DTBOlfAhJdTS7NbLNjLbOAOCcuzoF3TcD2MvdtzgXz9w8rzpQVUSwDYXBFnLXAFJAd0MBWJxhHC6l4BMGA4qrHBEuS2wcDSkAMs7M9IMMDKbOc6UHNGIMmjgFxEtI8jKKHYQCJq2rhIGfBGuaxKwIoyquoiHrnKEiIXUmrTKkybI5uE0TxNM6TZPkpSVMdaA9Gi04QGW6lgAAeSaAArVQYG+dzXUw1jlIdNSjW+WxMHxfEntU6A6KJWznMI1BuHwL6dqdb4Z12qBTpUb4T2yJx8RAkaOsMb0AB8Mfwb7ochzBodhuB4dPYrkdA8DKqNf6yoIgDPIBuzuN4qV3KY-AWVpkkAH5QdxiGoadInbr2cyFUDWhDHcN0WLYhdcOXfAsa5uz+egfHofqRkIBF+BWPFhspfu2XsI45dvQAMgt0GVamk41gcJxjLVqBvm5Lg4jRYyaC5Hl+R8FkAA5RHQLqOGs23aqE+3vlg9BZUj3qkyCTcYESm5MHSxnet6+gcDAYyHu+GD6DjF25d5XBsznJNWBwYdCEVBmc5b7rE7s6OVkMb5zggQwnGO1uO5j+pUBgNx7wAdQgWgXDWABNGeiDYQccGmkex4n9u7a7756jgbL72AcvBegYWsqs9fd-3w-t+H6+D5ge9cEAMgIr9WPfH8HoetLeG5WZWMEWABUghFRKveVGuk7TPWgNNP+0Bv5D3ft3Xu-dEE52Qeg5yRoVYUjZuhLEwp8BW3bviAAhCfAmQs4YJlFvrS0htpZF1NgrHAlsLbtwoeDdWp9nTa11mLBhksmEm3Yqwo07CbbZ1bp3VY+BHbO24a7d2+BPZuG9vgX2fJ1RBxDmHCO0ikExzjgnQxP9k5ALTsIDOWcf45zzgXYARcS5lyURXKuNc2ArAbk3O+JIJp+PsjHVBA9AnCQ3uPOAU8Z5z3wIvWgy8Fxr2ONfTeUSwlBIfofY+bjeHn0fhwZBn9b5mKMVkp+r8ik3yfhkoS8CAEp2AcIQqqVhAQMpjkaBP0oBwKuP-LBGCUkfxCQMqaQzDCjOpB2Wqxpm4dwiKtOa01FlUhLAzM0ForS3HeiwQo9QIBpBYoSei9AqAu1OfgFhS4cjGifKSOAPE+J3JJCXPU1JzlvJJFcscbyOBwnWSoEwCx8BS24P2FwBAlAqHIPiHZrB4D7MOTOL0+Iuma2aF6OEuoQC8PoMgUAKwmQZFEEBZAIAQiMhIE4PFFAQBNEOGABwMAmCYDIAqWUyAYA4BTCAXkMB0AuEnryMe7hWVgGYAgegY8xJjycGSqENK0BAWyDAQ5JBZS2GQGClwjBaUXXoCYc4DKmVME2oqBUcAtUhF1SAfVJgmDsrcHaUWVqdVwFpaynAY4yVNGaM1bFyVYCT25HyZAgdhQer4IwSehxMBkvdO4bIp5sXKVFkiz0ZLgx6BUEOIc2LRDKVQKINVGqSCuptYwdAqBOXcvdSAKV+4nW0BdUgbVNrWBNGDX7ZAGpaVcpIKgFw7K4roE1SgdwgpsXhhdOWutCZ7SwS3GeJgYAggEzAoYPElrW3Wo8hwIAA)
