### ISSUE TITLE
2.1 removes quotes from numeric keys in flow types

### ISSUE THREAD

**Issue by TrySound** [prettier/prettier#9036]
**Prettier 2.1.0**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAhgE8AHQgYQkwlwIF4DgAfAHSgIIHIBWABi5ICAZxi4AllADmAGnacuARj4ChoidLkduAJhWCRYybPncAzPrVHNprgBZLhjSajMAviBkgIpGOOjCyKB4uBAA7gAKeAiBKNiYYdjEgV4ARrjYYADWcDAAyqSZxshiAK5wXnAAtqlwqOioADLY0qXYUnAAYrRV2DB+0sgg2KUwEJ4gABYwVZgA6pPi8MKFYHB5MUviAG5LxENgwikgksJwuDARGVK9yABm8WdeAFbCAB4AQhnZuXnYVXBGpI4PdHhUQK83nljJg4ABFUoQeCgzBPECFXBnXBDVLYWqYCakDQwObiVAwSbIAAcfC8RIgZzmGVIQyJcCx2xBXgAjoj4FcfLFhsIALRQOB1OoTfC88T4K7tW5IB6o8FnKriEq4cpeYQw+F8kHKsFeGB40nkylIHSmjLiTDGKhVJUgdk8CalM4AFTxsRVaO25QAklB0LA8mAJL4AIKhvIkWEos5uNxAA

```sh
# Options (if any):
--single-quote
```

Flow does not allow numeric keys without quotes in types. In objects it's not allowed as well though this is something I could deal with. With types it's a bug.

**Input:**

```jsx
declare type Color = {|
  '50': string,
  '100': string,
  '200': string,
  '300': string,
  '400': string,
|}
```

**Output:**

```jsx
declare type Color = {|
  50: string,
  100: string,
  200: string,
  300: string,
  400: string,
|};
```

**Expected behavior:**

```jsx
declare type Color = {|
  '50': string,
  '100': string,
  '200': string,
  '300': string,
  '400': string,
|}
```

**Comment by fisker** [comment]
`flow` or `babel-flow` parser is recommended, they don't remove quotes.

**Comment by TrySound** [comment]
This looks like a solution. Thanks.

**Comment by fisker** [comment]
@TrySound  A unrelated question, do you use flow with `@flow` comment? I proposed to drop flow support in `babel` parser in https://github.com/prettier/prettier/issues/8204, and  @thorn0 suggest that auto  switch to  `babel-flow` if  `@flow` found(or maybe  .flow.js in filename too), if  we  do  that you would be  able to use `babel` without breaking your  code.

**Comment by TrySound** [comment]
Yes, I always used flow annotation.

**Comment by fisker** [comment]
Thank  you!
