### ISSUE TITLE
[Bug since 2.1.0] Insert `⏎·`

### ISSUE THREAD

**Issue by C0ZEN** [prettier/prettier#9038]
Sorry, I am not able to create a reproduction.
I use prettier for a TypeScript project.
I have this error since the release `2.1.0`.

**Error:**
```
/home/runner/work/il-est-midi-discord/il-est-midi-discord/src/features/app/services/config/app-config-core.service.ts
##[error]  6:34  error  Insert `⏎·`  prettier/prettier
```

```typescript
export class AppConfigCoreService extends AbstractService
  implements IAppConfig {
}
```

I think that the error is related to the implements being on another line.
This is formatted like this due to prettier by the way.

Using `--fix` does not find the error but on the other hand it is not changing the files so there is nothing to commit.

**Input:**
See the error in this [PR GitHub action step](https://github.com/Sonia-corporation/il-est-midi-discord/pull/841/checks?check_run_id=1022486154).

**Expected behavior:**
No error.

Sorry for not being able to provide a reproduction - reminder nonetheless that the issue in inside an [open source repository](https://github.com/Sonia-corporation/il-est-midi-discord/pull/841) -. If you need more information I am available.

**Comment by fisker** [comment]
I think somehow you're  running a older version of Prettier(global eslint or prettier or something)


**Prettier 2.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAQQwwGFoAzASwHN7s4BlObANybBw86eFAAmFSgCNSMbMTAxufAXAA6UPHiYBbDITg6EMCgElqdRqzzANAXxAAaEBAwwm0UslDFs2CADuAAq+CF4oxIQBxACeXs5S8mAA1nBKGApMUCzIcgCucM6GUnBiYqUAMsTZecQscABiODrEMO7ZyCDEeTAQTiAAFjA6hADqA0zwpBmC3FCkk0z8MDGdYOT9WaQ8MEHyLC3IDJHbzgBWpGgAQkmpSsRGFVlwRyeFIBdonFksBgCKeQg8FehFOIAy2G22E6UmIJUI-Qw2CyMFGTDEMAGyAAHAAGZxIiDbUbyDCdJFwKG8F7OACOgPge1c4S6pAAtFA4KVSv0OPSmBw9nVDkhjqD3tsdExctgCs4Ftl-gyXqK3s4YHC0RisUgAEzq+RMQg-eg6EWoUgAVn6eW2ABU4eExWDeAVTOJjJwwMi3JRxJwVgYQds7HYgA)
```sh
--parser babel
```

**Input:**
```jsx
export class AppConfigCoreService extends AbstractService
  implements IAppConfig {
}
```

**Output:**
```jsx
export class AppConfigCoreService
  extends AbstractService
  implements IAppConfig {}

```

**Comment by brodybits** [comment]
I recommend you do `npx prettier --write` with the file name in you work area, for example:

```
npx prettier --write src/features/app/services/config/app-config-core.service.ts
```

**Comment by evilebottnawi** [comment]
What your expected? You need to fix style problems. It is improvement

**Comment by C0ZEN** [comment]
@fisker was right about running an old version.
Sorry for false alarm here; 
I use a VPN to work and somehow stopping it and running once again `npm i` fixed the issue after using the `--fix` flag.
