### ISSUE TITLE
[HTML‑in‑SVG‑in‑HTML] Cryptic SyntaxError thrown when using auto‑closing HTML tags

### ISSUE THREAD

**Issue by ExE-Boss** [prettier/prettier#9040]
**Prettier 2.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqNcMAhuWJZwE4BnDgF4mIAK4wAZgFoAHOOatBANwDm5AB70ogsSGowADoKQB6cwHcbAOisBmWxH7rzAJgAM382vVKWJhhUaRc4AEt1KGwAIwArODAYcitwgBMYSgN3AFYANnEqCPVqbPyAqCCg1DTw1W1dfXEjYwtrO0dnV3MARgBOAfMtanoKqphq4wZ8SnDBcgAyOhgAbmMF9VXyLk1OKQhZMDoIYUFbVBj+ZXHxpdXLja258m5VCHTtznVbQIm-1CmqHCNH8lT+40E-DAIgA5L8bn80pwuEhgV84L4NABqHR0Fa8ATCGAiKRyRRghFBAA0qAA-LjyKo4EJwtADD1bJ5CghILUoOoDKSFOJaddweLUH4GnQ9AYWm0bFZ7E4XG4vD4-IVUhksuIeu5FCAipFSnqDWNxQjUPxEsltZl2eajZRiqaQPrDeRpOE6HQDOobQhCuYxZTgpj1KHxXCKeKkVxZKEIAYYgJxPC-lHUOZaqoxdnQjbItF4rblNm-MoQFSQBBjDBWXpkKABPwIFZiAIEIJkCBOHQrJwAJ49muXThgADWHAAysYJ+F+cgYPwJHAa3AaDE4Gk0juADKcfkSdEAMRcNGRDaXKD2MAg1cMtDoAHVZvBBPOwHAZ93wg3VH-IdezAQRRxARdhH4GBiH4L5L2QaR+2EGs4kELQACE4KnWdOHYfdFzgRDkPXEA0K0GdF3UOg4AARQkCB4GIugUJAechGZXsRjoR9jH4RcYBfdJMmQeRPBrPiTjgF84OMXs+LgKCmUfABHBj4Fguse1vQRZCgOAdx3R8bTU8IbVg+DOGY1jhBocJl1XUjBComj6MYoikCQljSK4GIhJ1ZAABYaxXTgfSo3AIBoBCUEUnJHwkYR8E4GJtJXNca1UNcAEkoD3WAZzAfj6wAQTymcYCHGjrLgABfWqgA)
```sh
--parser html
--tab-width 4
--use-tabs
```

## Input:
```html
<!DOCTYPE html>
<meta charset="utf-8">
<svg xmlns="https://www.w3.org/2000/svg">
	<foreignObject width="256" height="256">
		<div xmlns="http://www.w3.org/1999/xhtml">
			<p>This &lt;p&gt; tag auto-closes.<br>
				&lt;br&gt; is a void tag.
			<p><img
				src='
					data:image/svg+xml;charset=utf-8
					,<?xml version="1.0" encoding="utf-8"?>
					<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">
						<rect width="128" height="128" fill="green" />
					</svg>
				'
				data-foo="bar"
			>
		</div>
	</foreignObject>
</svg>
```

## Output:
```
SyntaxError: Unexpected closing tag ":svg:div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (18:3)
  16 | 				data-foo="bar"
  17 | 			>
> 18 | 		</div>
     | 		^
  19 | 	</foreignObject>
  20 | </svg>
  21 | 
```

## Expected behavior:
```html
<!DOCTYPE html>
<meta charset="utf-8" />
<svg xmlns="https://www.w3.org/2000/svg">
	<foreignObject width="256" height="256">
		<div xmlns="http://www.w3.org/1999/xhtml">
			<p>
				This &lt;p&gt; tag auto-closes.<br />
				&lt;br&gt; is a void tag.
			</p>
			<p>
				<img
					src='
						data:image/svg+xml;charset=utf-8
						,<?xml version="1.0" encoding="utf-8"?>
						<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">
							<rect width="128" height="128" fill="green" />
						</svg>
					'
					data-foo="bar"
				/>
			</p>
		</div>
	</foreignObject>
</svg>
```

**Comment by thorn0** [comment]
Shouldn't the markup inside `foreignObject` be written in the XML syntax?

**Comment by ExE-Boss** [comment]
Web browsers parse and display it just fine.

**Comment by thorn0** [comment]
Browsers parse tag soup like `<b><i>foo</b></i>`, but that doesn't mean Prettier needs to support that. Overall, HTML parsing is extremely permissive in browsers. You'll never get an "Invalid HTML. Can't parse." error message from a browser.

SVG documents have to be well-formed XML, that's why the markup you provided isn't valid SVG. If you save it as a `.svg` file, you'll see that browsers can't parse it as SVG. E.g. it won't be displayed by an `img` element.

On the other hand, if this is a common practice to write HTML like this inside not well-formed SVG embedded in HTML, then it might make sense for Prettier to support this. Do people really do this? How often?

**Comment by ExE-Boss** [comment]
I have encountered several minified **SVG** files like this in the wild (most recently the output of <https://daniel2013.github.io/satisfactory/calculator>), and I tried using **Prettier** to pretty‑print them, which didn’t work because of this.

**Comment by thorn0** [comment]
Can you link to specific files, please?

**Comment by ExE-Boss** [comment]
Well, <https://daniel2013.github.io/satisfactory/calculator> generates dynamic output into an inline `<svg>` tag, so there’s no specific file to link to.

---

At the very least, the `SyntaxError` should point to the `<img>` void element, rather than the `</div>` closing tag.

**Comment by thorn0** [comment]
Why `img`? `p` should be closed first, then `br`, etc. The error looks okay. It says "Unexpected closing tag" and shows where it is.  Why would it point to a valid opening tag instead?

**Comment by thorn0** [comment]
Closing as non actionable.
