### ISSUE TITLE
Prettier 2.1.0 generates broken code with new `...infer T` syntax in TypeScript 4.0

### ISSUE THREAD

**Issue by papb** [prettier/prettier#9041]
**Prettier 2.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKgQwEsAbAHl2zgA94oATAZ23yjQG0BdAPmwF49KNBI2xtCUAGZwATtgCqAGmwA6VeKmyASh2wB+bJuxJsUOADcZAbhAKQEDDELQGyUPmnSIAdwAK7hC4o+MRe+GgutgBG0vhgANZwMADKGLHiAObIMNIArnC2cAC2kXB0dKUAMizpOfjpcABiENKF+DCOUJlBOTAQNiAAFjCFxADqA4TwDKlgcEkBk4Rmk2jI4AwRIOIMMjA+MemtyBLBO7YAVgxUAEIx8YlJ+IVwFeJwx6f5IJdUSRnEcAAijkIPAPsQziBUtIdtI1ugsAwwNJCA5+hgUbBRoQ6DABsgABwABlsGIgO1GMQwawxcFhFn6AEcQfB9vZAiB8AwALSmUqlfrSODMwhC-Z1I5IE4Qr47QqELK5WX-IEs95Sz62GD4SLY3H4pAAJi1MRIGQAwhBCpKQHSAKz9HI7AiRQLSyFmPIASXoCGSyNRMAAgvQkugAeCdgBfKNAA)
```sh
--parser typescript
```

**Input:**
```tsx
type Tail<T extends any[]> = T extends [infer U, ...infer R] ? R : never;
```

**Output:**
```tsx
type Tail<T extends any[]> = T extends [infer U, ...(infer R)] ? R : never;

```

**Expected behavior:**

Output should be identical to input. The output given by Prettier does not compile in TypeScript 4.0.

**Extra information:**

This [was mentioned](https://github.com/prettier/prettier/issues/8646#issuecomment-650476312) by @bradennapier in #8646 but was forgotten.

I am working around this with `// prettier-ignore` for now.

-------------

Thank you for this awesome code formatter!

**Comment by papb** [comment]
By the way I am very surprised that TypeScript can't handle these parentheses... I feel the urge to put these parentheses myself, even if Prettier wouldn't put them...

**Comment by bradennapier** [comment]
I am not sure the exact semantics atm.  It is actually quite possible that there are cases where `...(infer U)` would be used in a valid way, I would have to play with it some more.  There isn't actually any direct information there in the release notes.

**Comment by evilebottnawi** [comment]
@bradennapier feel free to open a new issue

**Comment by bradennapier** [comment]
> @bradennapier feel free to open a new issue

Just replying to the message previous.  

I'll have to play with the syntax when I can, I'm pretty sure what I said would work but on mobile atm.  

It seems likely that prettier shouldn't correct either use of it -- or if the () is literally only valid when used as an array then it could be smarter. 

If anyone else has time to test to confirm as well that'd be good. 

The `...infer` style is the new syntax though and worst case could be converted to the other style if needed in meantime easy enough :).

**Comment by thorn0** [comment]
@bradennapier You're overthinking it. `...(infer U)[]` looks similar to `...(infer U)`, but it doesn't have the same structure in the AST.

**Comment by brodybits** [comment]
I tried 2 more combos in `tests/typescript/rest-type/infer-type.ts`, don't know if they are relevant or not:

**Input:**

```ts
type Tail<T extends any[]> = T extends [infer U, ...infer R] ? R : never;
type Tail2<T extends any[]> = T extends [infer U, ...(infer R)] ? R : never;
type Tail3<T extends any[]> = T extends [infer U, ...(infer R)[]] ? R : never;
```

**Output:**

```ts
type Tail<T extends any[]> = T extends [infer U, ...infer R] ? R : never;
type Tail2<T extends any[]> = T extends [infer U, ...infer R] ? R : never;
type Tail3<T extends any[]> = T extends [infer U, ...(infer R)[]] ? R : never;
```

**Comment by ExE-Boss** [comment]
@brodybits The definition of `Tail2` results in:

```
:2:51 - error TS2574: A rest element type must be an array type. 

2 | type Tail2<T extends any[]> = T extends [unknown, ...(infer R)] ? R : never;
                                                      ~~~~~~~~~~~~
```
