### ISSUE TITLE
Vue template with src not well formatted when installed a plugin that transforms the template tag's content (since 2.1.0)

### ISSUE THREAD

**Issue by Shinigami92** [prettier/prettier#9049]
**Prettier 2.1.0**
[Playground link](https://prettier.io/playground/#.....)

No playground link, cause not up to date ⚠️ 

**Input:**

```vue
<template lang="pug" src="./somefile.pug"></template>
```

```vue
<template lang="pug" src="./somefile.pug" />
```

**Output:**

```vue
<template lang="pug" src="./somefile.pug">

</template>
```

```vue
<template lang="pug" src="./somefile.pug"

/>
```

**Expected behavior:**

```vue
<template lang="pug" src="./somefile.pug"></template>
```

_or_

```vue
<template lang="pug" src="./somefile.pug" />
```

**Comment by fisker** [comment]
Your example seems not right?


**Prettier 2.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdYQM4BOYVIAdAPRMQZwAZgEsccTnQYgAfKm6ZcBONMpR0cbPiIkK1SY1btqPPgJFiJ9Rt2kgANCAhYYw6E2Sg8LFhADuABS8EdxQ8HF88AE93BwAjFjwwAGs4GABlLEThMmQYFlo4Bw1YuAATUrKAGTwyWjxSOAAxCBYMAhcc0NoYCHsQAAsYDBwAdX7heCZMsDg04InhADcJyORwJhiQbKY4Fhh-BNI25EEwnYcAKyYADwAhBOTUtLwBSuy4E7PCkCvrtOzSGIAIq0CDwT44c40Lw7FhrRYFPpYFjZGAjYSlGD9ZAADgADA5kRAdiMElg1si4LDFh8HABHUHwA5OEIgPBMAC0UDgZTKfRYcAZwgFB3qxyQp0h3x2GGEuXy0oBwMZHwlXwcMDwsXRmOxSAATBqEqIAQBhfjikBUgCsfVoOwAKlqQpKoQi4ABJKAVWBpMAo5wAQW9aRgkTEEJ2AF8o0A)
```sh
--parser vue
```

**Input:**
```vue
<template lang="pug" src="./somefile.pug"></template>
<template lang="pug" src="./somefile.pug" />
```

**Output:**
```vue
<template lang="pug" src="./somefile.pug"></template>
<template lang="pug" src="./somefile.pug" />

```

**Comment by Shinigami92** [comment]
Ok I will investigate why it happens, maybe it's a _weird_ option 🤔

**Comment by fisker** [comment]
There was bug in v2.0, especially the second one. You must using the old version

https://prettier.io/blog/2020/08/24/2.1.0.html#fix-formatting-element-with-void-element-as-its-last-child-8643httpsgithubcomprettierprettierpull8643-by-ikatyanghttpsgithubcomikatyang

**Comment by Shinigami92** [comment]
Ok removed all options in .prettierrc.json
Problem not resolved on my side using 2.1.0 CLI
With 2.0.5 it's working fine 🤔 

I'm in some meetings now, hope I can find more info later 👋

**Comment by Shinigami92** [comment]
Ok... it must be something different, it's not prettier 2.1.0 itself!
Created an empty project with yarn and tried to recreate the problem, but everything is fine 🤔 

So it could be another dependency that conflicts with prettier or something else...

---

😬🙈 ... it's `@prettier/plugin-pug` 🥴
Damnd... so I will report the bug to the maintainer of this package... wait ... thats me... 🙈

**Comment by fisker** [comment]
Kill him!

**Comment by thorn0** [comment]
@Shinigami92 

> No playground link, cause not up to date

Try cleaning your browser cache.

**Comment by Shinigami92** [comment]
I need to reopen this 🙁

The problem occurs when my plugin was installed as `devDependency`, but I can't control it!
I'm returning an empty string and prettier itself uses this empty string and this results in one empty line

```vue
<template lang="pug" src="./index.pug">
    // <== this line is just an empty string ('')
</template>
```

---

But I don't understand the second case❓ 

```vue
<template lang="pug" src="./index.pug"

/>
```

My plugin doesn't even have access to the `template` tag, or does it?

**Comment by Shinigami92** [comment]
https://github.com/prettier/plugin-pug/commit/f7d553b442a8eb2264ad045b21f016ef5f06a404#diff-46bec2a2249807aa1515b246cc13ee93R143-R144

**Comment by fisker** [comment]
I guess, I forgot check src.

**Comment by fisker** [comment]
WIP

**Comment by fisker** [comment]
You are right, https://github.com/prettier/prettier/pull/9052/files#diff-af1611ccd22ac8f495a01338b0e09f01R286

**Comment by fisker** [comment]
Kill me please

**Comment by Shinigami92** [comment]
Thanks for the v2.1.1 release, everything is now working as expected 👍
