### ISSUE TITLE
`v2.1.1` patch release

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#9054]
## Bugs introduced in 2.1

- Prettier 2.1.0 generates broken code with new `...infer T` syntax in TypeScript 4.0 #9041 
  - [x] #9044 
- Breaking jest inline snapshot https://github.com/facebook/jest/issues/10444
  - [x] #9053
- Vue template with src not well formatted when installed a plugin that transforms the template tag's content (since 2.1.0) #9049 
  - [x] #9052
- Prettier 2.1.0 and Sass rules with single mixin inclusion #9050
  - [x] #9051
- Void custom element in vue https://github.com/prettier/prettier/pull/9052#issuecomment-680083242
  - [x] #9055

## Bugs before 2.1

- Cannot read property 'end' of undefined in html with front matter #9042 
  - [x] #9043

---

Anything else need to be done?

**Comment by fisker** [comment]
Will you @sosukesuzuki or @thorn0 do it?

**Comment by sosukesuzuki** [comment]
Okay, I'll do it when above tasks is done.

**Comment by fisker** [comment]
Please review #9051

**Comment by brodybits** [comment]
Add <https://github.com/prettier/prettier/pull/9052#issuecomment-680083242> to the list - ??

**Comment by fisker** [comment]
I did

**Comment by sosukesuzuki** [comment]
When master CI is passed, I'll start release.

**Comment by sosukesuzuki** [comment]
start

**Comment by sosukesuzuki** [comment]
done!
