### ISSUE TITLE
Mixing Flow comment will cause generic syntax to be wrapped with Flow comment

### ISSUE THREAD

**Issue by kenrick95** [prettier/prettier#9062]
**Prettier 2.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAhgE9M59h8B5KOAFRLIF98AzHCdfAcgDoB6aHABiqADZweAKwDOXADpQ+AKiRIFGbHkINy+ABJxRoiPVL5mbDt34QYACzg4R4qbIVK+ChcTMAFdpimcNL4ALzkAD4K+Pi0wTAAwhzYNLBI+ABKcACGYDA8AIIARtIwOLmJyYKwADzZUEQAfAA00fgORhDpBp1BrVARjADcIM0gEJgwqNDSyKDZOOwA7r4LCLMo2aJL2USzY0XlYADWcDAAypi5qFAA5shlAK5wY3DoRXAAJp9fADL1t0e2Vuwlw6GyMCmd2QIGyjxgEFGIDsMHQogA6nZUPBpFcwHBzutsagAG7YogwsDSfZoKDSRwwfzA8HIFhbeljGQADwAQkdThdsug4L8bnBWeyXiBuecbrdxABFR62cVINmiDkgK44ek4GFFbIfUQAWhYxiWSMwOBuMHRqE+9mQAA4AAxjK0Qeno8qYGFW4KOEnisYAR2V8H8Ew2sOkxpoXy+SJwcDDqGTTNuLLVkrG9PQqAeOGeublivDqqeUpghrtDrsyAATGMytkxHKkugsyBggBWJGPem0Q0bdWaknPACSUB+sHOYGtkwK0-OxHEEo1cEYjCAA)
```sh
--parser babel-flow
--single-quote
```

**Input:**
```jsx
import type { OneType } from './oneFile.js'
/*::
import type { HelloType } from './otherFile.js'
*/

type PropTypes = {|
  TestComponent: React.AbstractComponent<any>,
  hello: HelloType,
|};
```

**Output:**
```jsx
import type { OneType } from './oneFile.js';
/*::
import type { HelloType } from './otherFile.js'
*/

type PropTypes = {|
  TestComponent: React.AbstractComponent/*:: <any> */, // <--- unexpected!
  hello: HelloType,
|};

```

**Expected behavior:**

```jsx
import type { OneType } from './oneFile.js';
/*::
import type { HelloType } from './otherFile.js'
*/

type PropTypes = {|
  TestComponent: React.AbstractComponent<any>, // <--- This is the behavior of Prettier 2.0.5
  hello: HelloType,
|};

```

**Comment by sosukesuzuki** [comment]
I'll work on this

**Comment by sosukesuzuki** [comment]
Note: with `--parser=flow`
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAhgE9M59h8B5KOAFRLIF98AzHCdfAcgDoB6aHABiqADZweAKwDOXADpQ+AKiRIFGbHkINy+ABJxRoiPVL5mbDt34QYACzg4R4qbIVK+ChcTMAFdpimcNL4ALzkAD4K+Pi0wTAAwhzYNLBI+ABKcACGYDA8AIIARtIwOLmJyYKwADzZUEQAfAA00fgORhDpBp1BrVARjADcIM0gEJgwqNDSyKDZOOwA7r4LCLMo2aJL2USzY0XlYADWcDAAypi5qFAA5shlAK5wY3DoRXAAJp9fADL1t0e2Vuwlw6GyMCmd2QIGyjxgEFGIDsMHQogA6nZUPBpFcwHBzutsagAG7YogwsDSfZoKDSRwwfzA8HIFhbeljGQADwAQkdThdsug4L8bnBWeyXiBuecbrdxABFR62cVINmiDkgK44ek4GEsYxLJGYHA3GDo1CfezIAAcAAYxiaIPT0eVMDCTcFHCTxWMAI7K+D+CYbWHSAC0NC+XyRODgAdQcaZtxZaslY3p6FQDxwzwzcsVgdVTylMGyRQtVrsyAATGMytkxHKkuhUyBggBWJGPem0csbdWaknPACSUB+sHOYFNkwK4-OxHEEo1cEYjCAA)
```sh
--parser flow
--single-quote
```

**Input:**
```jsx
import type { OneType } from './oneFile.js'
/*::
import type { HelloType } from './otherFile.js'
*/

type PropTypes = {|
  TestComponent: React.AbstractComponent<any>,
  hello: HelloType,
|};
```

**Output:**
```jsx
import type { OneType } from './oneFile.js';
import type { HelloType } from './otherFile.js';
type PropTypes = {|
  TestComponent: React.AbstractComponent/*:: <any> */,
  hello: HelloType,
|};

```

**Comment by thorn0** [comment]
Flow comments are a huge mess. See https://github.com/facebook/flow/issues/8355#issuecomment-627442127

Also note that Babel has support for these comments in the parser now. https://babeljs.io/docs/en/babel-parser#language-extensions

**Comment by sosukesuzuki** [comment]
Probably caused by #8724

**Comment by fisker** [comment]
`range` are different from `location`?

**Comment by sosukesuzuki** [comment]
No, `ranges` has not problem. This regression was caused by [the change](https://github.com/prettier/prettier/pull/8724/files#diff-3abca41914b4b214a2507e33cc54c28bL2853-L2855). So I reverted the change, but the regression wasn't fixed. Upon investigation, the behavior in 2.0.5 depended on `ranges` not being enabled.
