### ISSUE TITLE
Omitted parentheses in ForStatement with `in` in initializer

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#907]
The grouping parentheses are necessary in all of the below, but prettier removes them:

```js
for (let a = (b in c);;);
```

```js
for (a && (b in c);;);
```

```js
for (a => (b in c);;);
```

```js
function* g() {
  for (yield (a in b);;);
}
```

```js
async function f() {
  for (await (a in b);;);
}
```

**Comment by vjeux** [comment]
Thanks! I think that we should just crawl up the tree and if `in` is inside the first element of a for, then parenthesis is.

**Comment by bakkot** [comment]
Always parenthesizing would be overkill. You don't need to bother with the parentheses in a lot of cases, e.g. if the `in` is within an object, array, template, or function literal (other than the body of an expression-bodied arrow function literal), or a parameter to a call, or a computed member access. Or if the initializer is going to be parenthesized anyway, e.g. in an assignment expression after #862, or in e.g. `!(a in b)`.

**Comment by vjeux** [comment]
We found this edge case during fuzz testing and it doesn't appear in any of our millions of lines of js at Facebook. So I think it is fine having a bit of over-parenthesing for such a rare edge case just to make sure that it doesn't output something invalid :)
