### ISSUE TITLE
async should be added when await is used

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier#9084]
Using `await` in a function that isn't `async` is illegal in JavaScript, so Prettier currently fails to format with a parser error. However, Prettier should be able to detect an `await` inside a function that doesn't have `async` and add it when formatting for convenience and to prevent confusion.

**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaXAEzgAcEExMAKASl2AF8AdKHok8lCq0E1WK3Y9cuVAHdUpGMLpQxjVjw4gANCAg0y0dMlCoATmYiyACuYTGUqADbzMx3QCMzqMAGs4MADKND6kUADmyDBmhHC6cAC2HnCU1JQAMqgRhKjhcABiEGYJqDBkEchohDAQOiAAFjAJTgDq9Ypw6CFgcIH2iqQAboqYlWDo7iBh6HBmMNbe4SXI+M4zugBW6AAeAELefgGBqAlw6WFwK2txIFvbgWHhTnAAioQQ8FdO6yAhZjNmSoeVDJJx1GhmMIwFqkSgwerIAAcAAZdBCIDMWt4aJUIZ1ZoNLroAI7veALfQONDoAC0UDgKRSdTMcFJpBZC1yyyQq2+NxmCVIURi-MezzeH0uPOuuhgIJhcIRSAATLLvKQnI8AMIQBLckCdACsdUIMwAKiCHLyfoNYgBJVQIIJgSEGACCqkCMEwzy+Mw4HCAA)

**Input:**

```js
async function depenency() {}

function dependent() {
  await dependency();
}
```

**Output:**

```js
SyntaxError: Unexpected token, expected ";" (4:9)
  2 | 
  3 | function dependent() {
> 4 |   await dependency()
    |         ^
  5 | }
```

**Expected behavior:**

```js
async function depenency() {}

async function dependent() {
  await dependency();
}
```

**Comment by kachkaev** [comment]
This is out of Prettier’s scope because adding await would mean a change in AST. See

https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about

**Comment by nickmccurdy** [comment]
Prettier already changes code from invalid syntax trees to valid syntax trees (such as removing trailing commas in JSON files where they are banned), so I think this would be more consistent.

**Comment by fisker** [comment]
Let's say even if we want do it, without ast, how do we know where to insert? Parser can't parse it, it's impossible to do it.

**Comment by thorn0** [comment]
Often functions have to stay non-async because their callers don't expect to get a promise. Silently adding `async` and thus hiding the error is just dangerous. Closing as such things are really out of scope for Prettier.

**Comment by nickmccurdy** [comment]
In that case can we improve the error message? In Node there's an easy to understand error about using `async` with `await`, but Prettier has a vague syntax error about an illegal `;`.

**Comment by fisker** [comment]
We don't have AST , when don't know what happened in parser

**Comment by thorn0** [comment]
That's not a job of a code formatter to tell what's wrong with the code. If Prettier is passed invalid code, it only outputs the error it gets from the parser, Babel in this case. So an issue can probably be opened in the Babel project.

**Comment by nickmccurdy** [comment]
I experimented with Babel and this code gives the helpful error message about `async` with the source type set to module or unambiguous, and the unhelpful error message about `;` with the source type set to script. Since the latter is the same as Prettier's error, it seems like Prettier may be incorrectly using the script source type. Is it intentional that Prettier parses modules as scripts, or can we change the internal Babel parser options to use script/unambiguous conditionally/unconditionally?

**Comment by brodybits** [comment]
> can we change the internal Babel parser type to `script` or `unambiguous` for the better error messages?

I think that kind of a change would be helpful if it does not affect the existing functionality.

**Comment by nickmccurdy** [comment]
If I'm understanding how Babel works properly, it should be okay to just set it to `module`. One of Prettier's goals is to not affect runtime behavior anyway, so guessing the wrong Babel parsing and Babel wanting to do something different at runtime wouldn't matter.
