### ISSUE TITLE
Inconsistent line wrapping with styled-components/template literal

### ISSUE THREAD

**Issue by tu4mo** [prettier/prettier#9096]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlGBPAGzgBMARASwDdMBeTDQkgOmKoAMAdKTTAEmAAOAJwgC0tAHyYA5nBjZyALzgAKYaLRNeaJXCYAPNAEoAvlx791YyTLkLlakWK07lTNAFsANJgDkn31NzPkEncRopWXldRw0XXSYPYh9fJMCzKDYQLxBRGHJ0ZFAAQyERAHcABVKENGQQYoJy4rw6nIAjIWKwAGs7AW7yKGlkGCEAVzgcuA92kmISABli4fHi2QAxCCEPYph84fri8ZgIbJAACxgPAgB1C-J4NAGwOGxax6pHvHqwNDaQEM0HAhDBKl1pLtkAAzRrAnIAKzQ+gAQl1enZih44IshnAYXCpiAkfoFMMiABFcYQeAEgjwkADITAoT1drFOYEAC0MABwiGMFu5GIMAuyAAHAAGHLqYG3LoCerCOAsyj4nIAR2p8HBGiOaC5UDgJBI5yEcC15HN4PWUKQsPpROBHnIdIZOnJcCpNPx9sJORgHKFIrFSAATAGuuQCENpABhCAeO0gFUAVnO42BABUOXU-Y6cpRJgBJKALWDYMBCcgCGAAQTLuEYbrgJhMQA)
```sh
--parser babel-ts
--no-semi
```

**Input:**
```tsx
const StyledDiv = styled.div`
  ${props => getSize(props.$size.xs)}
  ${props => getSize(props.$size.sm, 'sm')}
  ${props => getSize(props.$size.md, 'md')}
`
```

**Output:**
```tsx
const StyledDiv = styled.div`
  ${(props) => getSize(props.$size.xs)}
  ${(props) => getSize(props.$size.sm, "sm")}
  ${(props) =>
    getSize(props.$size.md, "md")}
`

```

**Expected behavior:**
Output should match the Input.

**Comment by thorn0** [comment]
Regression. Worked as expected in 2.0.5.
