### ISSUE TITLE
Typescript comma replaced with semi-colons

### ISSUE THREAD

**Issue by NorbertBodziony** [prettier/prettier#9097]
**Prettier 2.1.0**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--parser typescript
--no-semi
```

**Input:**

```jsx
 action: PayloadAction<{ asset: assets, value: BigNumber }>
```

**Output:**

```jsx
 action: PayloadAction<{ asset: assets; value: BigNumber }>
```

**Expected behavior:**
```jsx
 action: PayloadAction<{ asset: assets, value: BigNumber }>
```

**Comment by thorn0** [comment]
This is intended. See the reasoning here: https://github.com/prettier/prettier/issues/7719#issuecomment-595497709 and https://github.com/prettier/prettier/issues/7719#issuecomment-595654979.
