### ISSUE TITLE
Prettier CLI gets glob patterns wrong

### ISSUE THREAD

**Issue by michaelkolber** [prettier/prettier#9098]
**Environments:**

- Prettier Version: 2.1.1
- Running Prettier via: CLI
- Runtime:  Node.js v12.18.3
- Operating System: WSL (Ubuntu) on Windows

**Steps to reproduce:**

1. Have a directory with an unprettified TS file in it, and also directories in that directory with unprettified TS files.
1. Run `npx prettify --check foldername/**/*.ts`

**Expected behavior:**

Prettify finds the top-level unprettified file as well as the ones in subdirectories.

**Actual behavior:**

Prettify only finds the ones in subdirectories. Running `npx prettify --check foldername/*.ts` finds the file in the top-level directory.

**Image:**

![image](https://user-images.githubusercontent.com/20274958/91606114-81e98e00-e93f-11ea-9712-6187f9e93a9d.png)

Note how `src/server.ts` does not show up in the first command.

**Comment by thorn0** [comment]
> Don’t forget the quotes around the globs! The quotes make sure that Prettier CLI expands the globs rather than your shell...

from https://prettier.io/docs/en/cli.html

**Comment by michaelkolber** [comment]
Ah, yeah that's on me, sorry about that.
