### ISSUE TITLE
Spacing problem

### ISSUE THREAD

**Issue by b5414** [prettier/prettier#9100]
I used the blank form ⚠

**Describe the solution you'd like**
Several new options in prettier extension for Visual Studio Code
or post-processing (_for example:_ replace all: `} else {` to `}else{`, _crutch alert_)

**Describe alternatives**
I asked people and tried to configure the prettier vscode extension myself(too few settings), and unfortunately without success
+[stackoverflow question](https://stackoverflow.com/questions/63278148/prettier-spacing)
++[another issue](https://github.com/prettier/prettier-vscode/issues/1527#issue-687535394) from /prettier-vscode

**Additional context**
I hate spaces because they are everywhere - where I need and not

I very like the clean code, and every space is a symbol which useless for me and understanding the code. Also when you move the text-caret(it's more stable than mouse in most cases) you need to hit the button a few times more... multiply that by +-5 hours of development every day and it will sound like a waste of time

Hateful spaces:
- in arrow functions, `const a=()=>{};` from `const a = () => {};`
- in `} else {`, for example to the clear one: `}else{`
- same with `if ()` and `for ()`

So, all spaces before `(` and after `)`, and kill beside space around - `=>` (I understand about `a = ()`, it's variable designation, so I can skip it in my mind, but another spaces are really painful)

What is best solution for me - creating a special module(?) or what can you recommend?

**Comment by thorn0** [comment]
These restrictions in Prettier are totally intentional. Please see https://prettier.io/docs/en/option-philosophy.html
I'd recommend you to fork Prettier and customize its output to your liking.

**Comment by b5414** [comment]
Space = `_`

- [Space1](https://github.com/prettier/prettier/blob/c94d1bc014b146eb221af962a96115cb7cd38a05/src/language-js/printer-estree.js#L712) - `const a=()=>_{};` or `if()_{}` 
- [Space2](https://github.com/prettier/prettier/blob/c94d1bc014b146eb221af962a96115cb7cd38a05/src/language-js/printer-estree.js#L5004) - `if_(){}` or while\for\etc
- [Space3](https://github.com/prettier/prettier/blob/c94d1bc014b146eb221af962a96115cb7cd38a05/src/language-js/printer-estree.js#L696) - before arrow

As I thought, this [space4](https://github.com/prettier/prettier/blob/c94d1bc014b146eb221af962a96115cb7cd38a05/src/language-js/printer-estree.js#L1533) (`const a_=_()=>{};`) is used in all variable declarations

Have a problem to find `if()_a++;` (not `if()_{}`)
