### ISSUE TITLE
Prettier always fails Pipeline even with correct EOL

### ISSUE THREAD

**Issue by JonahKr** [prettier/prettier#9103]
Hey there 👋 

So i have a github repository setup wich is using action [here](https://github.com/JonahKr/e3dc-power-wheel-card/blob/master/.github/workflows/tests.yml).. And it all works except for the prettier part.

I am running Windows 10 on my PC and have tested it in Ubuntu WSL (`prettier --check "*.js" --end-of-line lf`) aswell and in both cases its successfull.
However in the Pipeline it always throws an error that it hasn't been formated correctly.
I tried multiple things like adding a `.gitattributes` file to the repository but nothing helped so far.

Thanks in advance

**Comment by thorn0** [comment]
> Install an exact version of Prettier locally in your project. This makes sure that everyone in the project gets the exact same version of Prettier. Even a patch release of Prettier can result in slightly different formatting, so you wouldn’t want different team members using different versions and formatting each other’s changes back and forth.

from https://prettier.io/docs/en/install.html
