### ISSUE TITLE
styled-components formatting

### ISSUE THREAD

**Issue by AlexeiMet** [prettier/prettier#9115]
Hi.
I encountered some difficulties using prettier, stylelint and styled-components together. It seems there is no way to disable prettier's formatting of styled-components or configure rules (for example color hex case, like in stylelint). So if stylelint's rule conflicts with prettier's rule (for example if we set color hex to upper case in stylelint) than errors will remain always. Maybe you could consider adding rule for disabling styled-components formatting.

Prettier version: 2.0.5

![image](https://user-images.githubusercontent.com/37084849/91777930-d324a680-ebf9-11ea-8de4-0409d6ab32a7.png)
![image](https://user-images.githubusercontent.com/37084849/91777952-df106880-ebf9-11ea-9842-e2a47f233a95.png)

**Comment by fisker** [comment]
You need turn off conflict rules https://github.com/prettier/stylelint-config-prettier

**Comment by evilebottnawi** [comment]
Answer above
