### ISSUE TITLE
Unexpectedly doubles a blank line before a YAML comment (2.1.0 regression)

### ISSUE THREAD

**Issue by andersk** [prettier/prettier#9130]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAMwhJ6AMAOlOugEYCGATngIzHGkDE5FAXngEzEYCOArvwAeeAMzEQAGhAQADjACW0AM7JQ1KhADuABWoJVKCgBstFAJ6rpZKhTABrODADKsuwqgBzZDCr840nAAtmRwACZh4QAyFF78FJ5wAGIQVEEUMIpeyCAU-DAQUiAAFjBBxgDqxQrwym5gcM4GNQoAbjXmOWDKViAeynBUMDq2nunImCYD0gBWykIAQrYOTs4UQXBRHnATUwEgc0LOHp7GcACK-BDwu8bTIG5UA1Q55uvGRbJUHjAVCmEwYrIAAc+GkXwgAwqtlkOS+cGerR20gE1zgIzkhlyylQUDg4XCRSocAECmJIwS4yQkzu+wGQQUPj8dJOZ0uaNu9xgFDIfwBQKQnGkvgoCmMJwAwhAglSQAiAKxFfgDAAqPMMNPurX8AEkoJFYM4wN95ABBfXOGDmM6cuAAXztQA)
```sh
--parser yaml
```

**Input:**
```yaml
- foo: 0
  bar: 1

  # baz: 2
- quux: 3

```

**Output:**
```yaml
- foo: 0
  bar: 1


  # baz: 2
- quux: 3

```

**Expected behavior:**

Prettier should preserve the single blank line, not add a second blank line.

I bisected this issue to commit ea84392af27720b4b3f99556042d1abf5bd8d419 YAML: Preserve blank lines in comments (#8356). Cc @fisker.

**Comment by KarenEfereyan** [comment]
@andersk this seems interesting. Can i take it up?

**Comment by evilebottnawi** [comment]
Yes, PR welcome

**Comment by fisker** [comment]
@sosukesuzuki already on it https://github.com/prettier/prettier/pull/9143

**Comment by KarenEfereyan** [comment]
Okay
