### ISSUE TITLE
Unnecessary line breaks in `return`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#9139]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJTAA6U1ATnDOrVPidfvgPSf4BKcAQwDOBIrXwAWAEztJMqGXwAqfAA58AanxSA3LNkBfEABoQEAA65oQ5KAG1aEAO4AFewhsoBANwg4AJiYgAEa0AmAA1gwAyubhOFAA5sgwtOhwpnAAtsFw-v55ADICSegCiXAAYhC0WQIwuEnIIALoMBBBABYwWQA2AOqdOPBCcWBw0R7DON7DAJ7NYEI2pglCcLQwLmGJdcioAr3rpgBWQgAeAEJhkTECWXCFCXD7h8cgZ+fRCYm9cACK6Ag8FeRwyIDitHWtGawQEuV6QXMtASMH6ARgnWQqgADKZkRB1v0wuZmsi4NDvC9TABHIHwbYWTwtIQAWigcDyeSC9DpOHo23KeyQBzBpnWWRwKTS4KEPz+gOBLxFb3BMHh6P8mOQUlMqQEOF6PwAwhAssKQFBoNSQOh1gAVeGeUXvbzpACSUAKsGiYBRlgAgl7ojA5n9QesDAYgA)
```sh
--arrow-parens avoid
--parser babel
--trailing-comma none
```

**Input:**
```jsx
function foo(){

return (
  // Reason for 42
  42
) * 8 + 2;
  
  }
```

**Output:**
```jsx
function foo() {
  return (
    // Reason for 42
    42 *
      8 +
    2
  );
}

```

**Expected behavior:**

```jsx
function foo() {
  return (
    // Reason for 42
    42 * 8 + 2
  );
}

**Comment by thorn0** [comment]
Are you sure it's not a duplicate of #7746? Also this all happens in binary expressions in any position, not only in return statements.

**Comment by fisker** [comment]
Ah, yes, sorry about it, found this during reviewing https://github.com/prettier/prettier/pull/9026, but forgot #7746
