### ISSUE TITLE
Empty arrays/object literals are split across lines

### ISSUE THREAD

**Issue by garth** [prettier/prettier#914]
After upgrading from 0.20 to 0.21

```diff
-        function contentTypesContentTypes(
-            tile,
-            searchString = '',
-            filteredContentTypes = [],
-            contentTypesArray = [],
-            selectedGroup,
-            singleSelection
-        ) {
+        function contentTypesContentTypes(tile, searchString = '', filteredContentTypes = [], contentTypesArray = [
+        ], selectedGroup, singleSelection) {
```
and
```diff
-export default compute(props`tile.id`, state`repository.items.status`, function conflictItem(
-    locator,
-    itemsStatus = {},
-    get
-) {
+export default compute(props`tile.id`, state`repository.items.status`, function conflictItem(locator, itemsStatus = {
+}, get) {
```
IMO it was clearer before?

**Comment by vjeux** [comment]
I cannot repro either of those.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22if%20(1)%20%7B%5Cn%20%20if%20(2)%20%7B%5Cn%20%20%20%20if%20(3)%20%7B%5Cn%20%20%20%20%20%20if%20(4)%20%7B%5Cn%20%20%20%20%20%20%20%20function%20contentTypesContentTypes(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20tile%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20searchString%20%3D%20''%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20filteredContentTypes%20%3D%20%5B%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20contentTypesArray%20%3D%20%5B%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20selectedGroup%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20singleSelection%5Cn%20%20%20%20%20%20%20%20)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%7D%7D%7D%5Cn%5Cnexport%20default%20compute(props%60tile.id%60%2C%20state%60repository.items.status%60%2C%20function%20conflictItem(locator%2C%20itemsStatus%20%3D%20%7B%7D%2C%20get)%20%7B%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

Do you mind tweaking your code such that it reproduces as a minimal example?

**Comment by garth** [comment]
It might not be minimal, but it's now has the full context.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20complete%20example%201%5Cnconst%20contentTypes%20%3D%20function(tile%2C%20singleSelection)%20%7B%5Cn%20%20%20%20return%20compute(%5Cn%20%20%20%20%20%20%20%20tile%2C%5Cn%20%20%20%20%20%20%20%20state%60contentTypes.viewState.searchString%60%2C%5Cn%20%20%20%20%20%20%20%20Fuse(ContentTypesArray()%2C%20state%60contentTypes.viewState.searchString%60%2C%20%7B%20keys%3A%20%5B'name'%5D%20%7D)%2C%5Cn%20%20%20%20%20%20%20%20ContentTypesArray()%2C%5Cn%20%20%20%20%20%20%20%20state%60contentTypes.viewState.selectedGroup%60%2C%5Cn%20%20%20%20%20%20%20%20singleSelection%2C%5Cn%20%20%20%20%20%20%20%20function%20contentTypesContentTypes(%5Cn%20%20%20%20%20%20%5Ct%5Cttile%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20searchString%20%3D%20''%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20filteredContentTypes%20%3D%20%5B%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20contentTypesArray%20%3D%20%5B%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20selectedGroup%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20singleSelection)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20selectedGroup%20%3D%20(tile.state%20%26%26%20tile.state.group)%20%7C%7C%20selectedGroup%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20return%20(searchString.length%20%3F%20filteredContentTypes%20%3A%20contentTypesArray).filter(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20contentType%20%3D%3E%20(!selectedGroup%20%26%26%20!isSingleSelection(%7B%20tile%20%7D))%20%7C%7C%20contentType.group%20%3D%3D%3D%20selectedGroup%5Cn%20%20%20%20%20%20%20%20%20%20%20%20)%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20)%3B%5Cn%7D%3B%5Cn%5Cn%2F%2F%20complete%20example%202%5Cnexport%20default%20compute(%5Cn%20%20props%60tile.id%60%2C%5Cn%20%20state%60repository.items.status%60%2C%5Cn%20%20function%20conflictItem(locator%2C%20itemsStatus%20%3D%20%7B%7D%2C%20get)%20%7B%5Cn%20%20%20%20if%20(!locator%20%7C%7C%20itemsStatus.state%20!%3D%3D%20'dirty')%20%7B%5Cn%20%20%20%20%20%20%20%20return%20%7B%7D%3B%5Cn%20%20%20%20%7D%5Cn%20%20%20%20const%20conflict%20%3D%20itemsStatus.conflicts.find(conflict%20%3D%3E%20conflict.locator%20%3D%3D%3D%20locator)%3B%5Cn%20%20%20%20const%20rawItem%20%3D%20conflict.theirs.object%3B%5Cn%20%20%20%20return%20get(ContentItem(rawItem))%3B%5Cn%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks! As I suspected, it's not an issue per-se of the object breaking but the whole list not breaking.

**Comment by vjeux** [comment]
Another similar issue:

```js
function f() {
  return new Promise((
    resolve: (event: any) => void,
    reject: (event: any) => void,
  ) => {
    const resolveReject = new Map();
    resolveReject.set('resolve', resolve);
    resolveReject.set('reject', reject);
  });
}
```

turns into

```js
function f() {
  return new Promise((resolve: (event: any) => void, reject: (
    event: any
  ) => void) => {
    const resolveReject = new Map();
    resolveReject.set("resolve", resolve);
    resolveReject.set("reject", reject);
  });
}
```

**Comment by vjeux** [comment]
This bug was introduced by #847

**Comment by vjeux** [comment]
This is the same root cause as #914, I'm going to close this one if favor of the other one. Fixing either is going to fix both.

**Comment by SimenB** [comment]
@vjeux #914 is this issue, which did you mean to link to?

**Comment by vjeux** [comment]
#997 sorry!

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/pull/1224 is a fix for this issue! Sorry it took so much time to track down!

**Comment by vjeux** [comment]
Note that #1224 doesn't fix

```js
function f() {
  return new Promise((
    resolve: (event: any) => void,
    reject: (event: any) => void,
  ) => {
    const resolveReject = new Map();
    resolveReject.set('resolve', resolve);
    resolveReject.set('reject', reject);
  });
}
```
