### ISSUE TITLE
Markdown inline code in table

### ISSUE THREAD

**Issue by sergeysova** [prettier/prettier#9146]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABAOQIYFs7qFHEYAqAngA4HG130ONMYAicAZtgK4A2MJ6NgGcwAJwCWlGOOhM589KgA6UDAFoNmrZsXpt+g4aPHDu42ZOWrBxSowADGFTj2GDpSHgAPGB90fKbCEhAHcIUQATPwwPOFxscR4PVwVGB28YFKIMAAlSAFkAGXQnanQIdhKACwJxKEoufmVVdHsoPBc3VqEYCSgAcyzU4dSMOQwcfHRsGF7xACNGgiFqMHF2cTghafR2qYrq2vrG2ygQABoQCCkZKCFkUGxRUQgQgAUnhHuUbB4Q7HI90u81E2DAAGs4DAAMqBNYDZC9LhwS5xeZwCIRDGFbADLjYfpwABi4Xiszq-WQIG4MAgFxAVRguB4AHUquJ4CswXBoV8OeIAG4c8hUsDBel1IRwUQwN6g-rxZCcHhSy4AKyEXgAQqCIVDoR1CnU4ErfqqQBqvNCKTw4ABFLgQeCmlUokCBURS0RU+KicERV5nS6UPowFniCIwKrIAAcAAZgy8pSzQZQqSGttKBSbLgBHR3wOXXb7UoRqKBwDEY+miOD58S1uUExVIZXmqW4cSI0TIy5CG32gsm1tmt0wbDzcOR6NIABMl16CR4FIAwhBcC2QFsAKz0rhS0gT75tt0C5EASSgWNg0LEkhgAEEr9CnLaXVKAL4foA)

```sh
# Options (if any):
--parser markdown
```

**Input:**

```md
| Name          | Type                                                  | Default    | Description                                  |
| ------------- | ----------------------------------------------------- | ---------- | -------------------------------------------- |
| `type`        | `"text" | "password" | "email"`                       | `text`     | HTML type of the input |
| `name`        | `string`                                              |            | Name attribute specifies a name of the input |

```

**Output:**

```md
| Name   | Type     | Default    | Description                                  |
| ------ | -------- | ---------- | -------------------------------------------- |
| `type` | `"text"  | "password" | "email"`                                     | `text` | HTML type of the input |
| `name` | `string` |            | Name attribute specifies a name of the input |
```

**Expected output:**

```md
| Name   | Type                            | Default | Description                                  |
| ------ | ------------------------------- | ------- | -------------------------------------------- |
| `type` | `"text" | "password" | "email"` | `text`  | HTML type of the input                       |
| `name` | `string`                        |         | Name attribute specifies a name of the input |
```

**Comment by evilebottnawi** [comment]
Thanks

**Comment by fisker** [comment]
I remember we have an issue on this, can't find it.

**Comment by thorn0** [comment]
@sergeysova What dialect of Markdown is this? Prettier tries to stick to [the GitHub Flavored Markdown spec](https://github.github.com/gfm/#tables-extension-). It doesn't support what you want. You can test it right here in comments on Github:

| Name          | Type                                                  | Default    | Description                                  |
| ------------- | ----------------------------------------------------- | ---------- | -------------------------------------------- |
| `type`        | `"text" | "password" | "email"`                       | `text`     | HTML type of the input |
| `name`        | `string`                                              |            | Name attribute specifies a name of the input |

**Comment by evilebottnawi** [comment]
Oh, yes, it is not supported by github

**Comment by sergeysova** [comment]
| Name   | Type                            | Default | Description                                  |
| ------ | ------------------------------- | ------- | -------------------------------------------- |
| `type` | `"text" \| "password" \| "email"` | `text`  | HTML type of the input                       |
| `name` | `string`                        |         | Name attribute specifies a name of the input |


Ok. Thanks. Solved with `\|`
