### ISSUE TITLE
Markdown: space normalisation between block langauge and the attributes does not work for spaceless curly brace

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#9155]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAzgAmAMwggF4AdEACzgBtqIcGcB3CAJ2oBNyBfUqAen6NAiYQ44ADwAOcMPA7UAnjmpx8MHAENcWnAEssfSFCwQVDAHQM6AcwAU5KrXot2XEAEo+6VHy+ZcjAwERGSUNHSBLpw8fIIiYlIycoo4rHAcAK5g6ThYkhpgulDWhtAmZjiWyhB2DuHObNEefj5QLdjBJHVOkY1uvAJCgcOBohlQEtKy6SlpmdkcufmFxaXGpnAWVjX2YT1Rbp5Q3r7H-sCBhF17EYwH5IwDcfHjk0kzSnNZOXkFRSVQIzlTaVba1G4NVzkI4nKAgAA0IAgkhgujKyFAGlYrAgTAACliEFhkCANNQmBoFMTEQAjVgFADWcBgAGVlv9kDBWBk4Ii4ABbGnpDjpAAyGmKGQ01jgADE2PyNDBUcUSRoMjAIAjKDB+dQAOoUXTwX7ZFlE426ABuxoUJLAWGpICKWDgrBgePp1kVyHwZNdiOw4gAQvSwEzWRp+XBRUU4L7-byQEGWf8VABFDIQeAJ6gBkD5Viu1gkxWsBkcXFwxGSVhFGD63QcGAUZAADgADDWca79fTJCTa3Bi1b44iAI5Z+Ce5HElBaAC0E3S6W1aUnujSnulPqQfrzSdd-N0nO5h7TcEz2fje8TiJgGhpjebraQACZ7-TdNR-gBhCD8ruIDDgArNqGSugAKo+c77vmVo8gAklAIqwCyYB1iiACCKEsjACgqLmrrcNwQA)
```sh
--parser markdown
```

**Input:**
````markdown
```js {foo="hello    world"}
//   ↑ expectedly left as as is
console  .  log("hello world")
```

```js      {foo="hello    world"}
//   ↑ expectedly reduced spacing
console  .  log("hello world")
```

```js{foo="hello    world"}
//              ↑ unexpectedly reduced spacing
console  .  log("hello world")
```

```js{    foo="hello    world"   }
//    ↑ unexpectedly reduced spacing
console  .  log("hello world")
```

````

**Output:**
````markdown
```js {foo="hello    world"}
//   ↑ expectedly left as as is
console.log("hello world");
```

```js {foo="hello    world"}
//   ↑ expectedly reduced spacing
console.log("hello world");
```

```js{foo="hello world"}
//              ↑ unexpectedly reduced spacing
console.log("hello world");
```

```js{ foo="hello    world"   }
//    ↑ unexpectedly reduced spacing
console.log("hello world");
```

````

**Expected behavior:**

````markdown
```js {foo="hello    world"}
//   ↑ expectedly left as as is (no change)
console.log("hello world");
```

```js {foo="hello    world"}
//   ↑ expectedly reduced spacing (no change)
console.log("hello world");
```

```js {foo="hello    world"}
//   ↑ added space after lang + no reduced spacing afterwards
console.log("hello world");
```

```js {    foo="hello    world"   }
//   ↑ added space after lang + no reduced spacing afterwards
console.log("hello world");
```

````

Background: 
 - Seems that the bug was accidentally introduced by #8140, which in turn was the result of https://github.com/remarkjs/remark/pull/345
- Upstream issue: https://github.com/remarkjs/remark/issues/528
- Pain point: https://github.com/gicentre/litvis/issues/50

I’m happy to tweak the [logic of embed.js](https://github.com/prettier/prettier/blob/370844cc4cbe3c43b8e699e3e4bcec215bd94e08/src/language-markdown/embed.js#L15-L17) and submit a bugfix. Doing so with synchronise language detection (which already works) and space normalisation. In the longer term, we might replace this with a proper fix in remark. WDYT?

**Comment by fisker** [comment]
How are we going to solve this? keep meta untouched, or check `{`? @kachkaev

**Comment by kachkaev** [comment]
After speaking to @wooorm in https://github.com/remarkjs/remark/issues/528 I'm no longer sure I can provide the fix I originally wanted. Because remark's AST does not contain the 'raw' value of lang before the extraction of meta, the number of spaces in the original document gets completely lost.

This issue boils down to the vagueness of the term 'word' in the markdown specs. When remark [introduced](https://github.com/remarkjs/remark/pull/345) the extraction of lang and meta from 'raw lang' in their parser, the separators they chose were just space and the tab symbol. Prettier, on the other hand, was treating any punctuation symbol as the end of the language 'word' since https://github.com/prettier/prettier/pull/4783. When it comes to syntax highlighting in editors, Atom seems to be aligned with the current Prettier's behaviour, while VSCode is in line with remark.

This vagueness creates a slightly poor DX. For example, a user might be seeing a code block that is not highlighted but is formatted by Prettier.

An easy solution would be to refer to the specs, but they can't help here unless we dig out what the term 'word' actually is. To fix this bug, we have two options:

1. Persuade @wooorm to change how the `lang` 'word' is being extracted in remark or at least include some raw value into the AST so that Prettier could handle it as it wants. That said, I understand that this is not an ideal solution and has cons.

2. Revert https://github.com/prettier/prettier/pull/4783, thus removing the [`langMatch` hack](https://github.com/prettier/prettier/blob/370844cc4cbe3c43b8e699e3e4bcec215bd94e08/src/language-markdown/embed.js#L15-L17) (it existed before remark started extracting `meta`). This will make lang matching aligned with remark VSCode, but will require users to update their block infos. ` ```js{stuff}` will no longer be a js block, only ` ```js {stuff}`) will.

Not sure what's the least evil here, so happy to hear some other thoughts.

**Comment by fisker** [comment]
Maybe we can try to get the raw value from originalText?

This case, 

````markdown
```js{foo="hello    world"}
```
````

We can try to find `"world\"}"`(meta) position and slice from `originalText`

**Comment by fisker** [comment]
Sorry, I misunderstood the problem, the `lang` from parser contains whole `js{foo="hello    world"}`? How about keep unknow lang as it is?

**Comment by kachkaev** [comment]
> the lang from parser contains whole js{foo="hello world"}? How

Nope since https://github.com/remarkjs/remark/pull/345 → https://github.com/prettier/prettier/pull/8140

We used to get `lang` equal to `js{foo="hello world"}` before then, from which we extracted the bit before `{`. Now in the remark AST we have `lang` = `js{foo="hello` and `meta` = `world"}` and no information about the space in between 🤔

**Comment by fisker** [comment]
But we can do this https://github.com/prettier/prettier/issues/9155#issuecomment-688302135, right?

**Comment by kachkaev** [comment]
Yeah I guess it's generally possible, although pretty hacky. Shall we go that route or wait till @wooorm shares his thoughts? Maybe we can get a patch version of remark pretty quick, IDK. Ideally, we'd get a raw block info value and then extract lang using the definition of the 'word' already established in Prettier (i.e. treating syntax chars as word terminators, not just spacing).

**Comment by wooorm** [comment]
To reiterate, for markdown, “language” is the stuff before a space or a tab, if there is one, or the whole thing. This is how GFM, CM, and remark have always worked. Although, remark used to do the splitting when going to HTML. That’s how it is on the language level for parsers.
And I’m not going to change that.

Now, if you’re Atom, or Code, or Prettier when figuring out how to format the text in code, what you do is up to you. Either take the language directly from markdown, or alternatively if a language is unknown (because there’s punctuation too) try to figure it out some other way (by ignoring punctuation an stuff after it)

**Comment by kachkaev** [comment]
After further chatting with @woorm in an upstream issue I’m now leaning towards dropping the support for non-whitespace language separator — see https://github.com/remarkjs/remark/issues/528#issuecomment-703297322

I was actually the one who added it in the first place two years ago: #4783

Back then, remark parse did not have its own logic for separating the language from the args, so we just implemented our own. Now that remark parse [has an opinion](https://github.com/remarkjs/remark/pull/345) on what characters to count  separators, the easiest path forward is to just follow.

Happy to submit a PR that removes this hack and updates the tests:

https://github.com/prettier/prettier/blob/fbb212ab59a5951f062caf01e94eba89759f24b0/src/language-markdown/embed.js#L15-L17

Formally, this is a breaking change, but given that it only concerns are rather unpopular edge case, we probably don't have to wait for Prettier@3.0.

WDYT?

**Comment by fisker** [comment]
I'm fine with this change.

**Comment by thorn0** [comment]
@kachkaev :+1:  https://prettier.io/docs/en/rationale.html#disclaimer-about-non-standard-syntax

**Comment by kachkaev** [comment]
👀 #9365
