### ISSUE TITLE
Comment in return expression cause un-wanted new line

### ISSUE THREAD

**Issue by gaelduplessix** [prettier/prettier#916]
```js
function f() {
  return (
    // Reason for 42
    42
  ) && 84
}
```

Gets transformed to this
```js
function f() {
  return // Reason for 42
  42 && 84;
}
```

The strangest thing here is that there's no semicolon after the `return`, so if I take this result and run it into `prettier` again, it actually adds the semicolon. So basically in my editor, hitting "CMD+S" multiple times gives me 2 different results.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%2F%2F%20Reason%20for%2042%5Cn%20%20%20%2042%5Cn%20%20)%20%26%26%2084%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Great catch, we need to fix this as it generates code that has a different meaning.

**Comment by gaelduplessix** [comment]
Yup, just added prettier formatting to a project and caught this one thanks to eslint reporting unreachable code after the return :)

**Comment by vjeux** [comment]
You can run `--debug-check` instead of `--write` as a sanity check while we're still ironing out all the bugs.

**Comment by vjeux** [comment]
Two examples from our codebase:

```js
function f() {
    return (
      // comment
      !obj.some_requested ||
      obj.some < obj.some_requested
    )
      ? obj.some
      : obj.some_requested;
}
```

```js
function f() {
  return // comment
  !obj.some_requested || obj.some < obj.some_requested
    ? obj.some
    : obj.some_requested;
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%2F%2F%20comment%5Cn%20%20%20%20%20%20!obj.some_requested%20%7C%7C%5Cn%20%20%20%20%20%20obj.some%20%3C%20obj.some_requested%5Cn%20%20%20%20)%5Cn%20%20%20%20%20%20%3F%20obj.some%5Cn%20%20%20%20%20%20%3A%20obj.some_requested%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

and

```js
function f() {
  return (
    // $FlowFixMe
    obj.some &&
    obj.some.thing[0]
  ) || undefined;
}
```

```js
function f() {
  return // $FlowFixMe
  (obj.some && obj.some.thing[0]) ||
    undefined;
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%2F%2F%20%24FlowFixMe%5Cn%20%20%20%20obj.some%20%26%26%5Cn%20%20%20%20obj.some.thing%5B0%5D%5Cn%20%20)%20%7C%7C%20undefined%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by rattrayalex** [comment]
I'm hoping to take a crack at this tomorrow... I'm new to the comments code but assuming a `handleReturnStatement` or similar function might be useful.
