### ISSUE TITLE
Statement-position expression whose LHS starts with '{' needs parens

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#917]
Prettier incorrectly drops the parentheses in e.g.
```js
({} && a, b);
```

Related: #912

**Comment by bakkot** [comment]
Among other cases. Here's a sort of mega-test:

```js
({}::b()``[''].c++ + 0 && 0 ? 0 : 0, 0);
```

**Comment by vjeux** [comment]
I'm curious, do you think that we're going to be able to use the same infrastructure for handling no-semi?

**Comment by bakkot** [comment]
Depends on how you go about it. You don't actually need to know the first token of a node in general to solve this particular problem; you just need to know if if the first token of *an expression* is `{`. Probably similar logic would allow you to figure out if the first token of an expression `` ` `` or `[`, and you can special-case the `get; x` and `x = 0; *y` cases in class bodies. I believe that covers most of what you need for no-semi, except parentheses.

Unfortunately, parentheses are much harder to figure out, since they're inserted by prettier itself.

**Comment by vjeux** [comment]
The hacky way would be to add a "semi" node inside of the IR and when you print it, replace it with "" if the next printed character is one of the banned one.

cc @jlongster

**Comment by bakkot** [comment]
@vjeux You might be able to get something like that to work, but, a few potential problems with that approach:

- Needs to be "next printed character except whitespace and comments"

- Will insert an unnecessary semicolon in many cases, like
```js
x = "";
(function(){}())
```
and
```js
export {};
(function(){}())
```
- Won't necessarily work class bodies, especially the corner cases:
```js
class A {
  get;
  x(){}
}
```
in which the semicolon is necessary but that approach omits it, or
```js
class A {
  x;
  ['']
}
```
in which the semicolon is unnecessary but that approach includes it.
