### ISSUE TITLE
Is there a way to ignore a specific rule? [Possible Feature]

### ISSUE THREAD

**Issue by ColdHandz** [prettier/prettier#9171]
## Problem

Right now prettier `check`s and `write`s for all rules that it has, but it does not have an option to ignore a rule.
For example i don't need to `check` if there is trailing comma or not in my code, but need to check for other things like semicolons and tabWidth.

There is also another problem: `check` finds if specific file has a problem, it doesnt specify what problem it is, or on what line it occurs, it just prints `[warn] mycode.ts`.

**Comment by evilebottnawi** [comment]
> Right now prettier checks and writes for all rules that it has, but it does not have an option to ignore a rule.

> There is also another problem: check finds if specific file has a problem, it doesnt specify what problem it is, or on what line it occurs, it just prints [warn] mycode.ts.

Prettier doesn't have rules.

and will never have

**Comment by ColdHandz** [comment]
> Prettier doesn't have rules and will never have

But it has `options`, there will never be an option ignore? And what about verbose check printing?

**Comment by evilebottnawi** [comment]
> But it has options, there will never be an option ignore?

Never

> And what about verbose check printing?

https://prettier.io/docs/en/cli.html#--list-different
