### ISSUE TITLE
No line break for type annotations in variable declarations exceeding 80 characters and initialized with function result

### ISSUE THREAD

**Issue by liolick** [prettier/prettier#9172]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzAlgJzgwkIAU581oBDAG1oE8BJAEwRlz2oCNa5TqMABZokmAIL581BgB4AwhHpwwHdADoAqmgpp1AUVi4YDAHyYAvJioBbONgCuUMAAoAlAG4QAGhAQADmpQaMig1FIQAO4ChMHIIHSRMiG+3NJgANZwMADK-tRguFAA5sgw+A5wvnA23HAsbCwAMtQlDtTFcABiJDaCHCXx1A4wED4gQjA2tADqQsZE+WBwOQhoxrgAbsYM8WBoKSBFOvgwpNLFfcjYdDq+AFZoAB4AQulZudR2TUVw17dVECPJ45IrFPgARQcEHg-1odxA+UoFHi3B4cFo438+CKMBmuBYwmQAA4AAy+bEQHQzaT+eLYogUTZ-XwAR2h8HOARCKGoaAAtFA4PV6uNCOyCPwLlckDd4YCdDZcGUKgqwZCOX9ZQDfDAePjCUJkAAmXXSXC0MGKGwykBEACs4wcOgAKjweXKEZtKkwoGxYDkwDjAuI-TkTHw4ToAL7RoA)
```sh
--parser babel
```

**Input:**
```jsx
const firestorePersonallyIdentifiablePaths: Array<Collections.Users.Entity> = somefunc();
```

**Output:**
```jsx
const firestorePersonallyIdentifiablePaths: Array<Collections.Users.Entity> = somefunc();

```

**Expected behavior:**
```jsx
const firestorePersonallyIdentifiablePaths: Array<Collections.Users.Entity> = 
    somefunc();

```

**Comment by liolick** [comment]
Very similar to https://github.com/prettier/prettier/issues/6899, but not fixed

**Comment by bakkot** [comment]
See also https://github.com/prettier/prettier/issues/2482
