### ISSUE TITLE
Prettier : Settings -Semicolon- Whether to add semicolon at end of every line - Turned OFF but still adding them.

### ISSUE THREAD

**Issue by marksteven** [prettier/prettier#9174]
Settings - Semicolon- Whether to add semicolon at end of every line - Turned OFF but still adding them.

**Input:**
Settings Box unchecked should not add semicolons at end of line , but still does even after reboot
disable Prettifier completely and problem goes away 
enable - comes back

**Output:**
Hitting save adds a semicolon in front of MyList even though there was not one there previously.
```
function App() {
  return
  ;<MyList />
}
export default App


**Expected behavior:**
function App() {
  return
  <MyList />
}

works ok if return and MyList is on same line eg
function App() {
  return <MyList />
}
export default App
```
But given this has been disabled in settings should not add semicolons at all so appears to be a bug that has only started doing this lately so assuming there has been a change to be aware of.

**Comment by fisker** [comment]
Please use playground to report format issue, https://prettier.io/playground/ there is a `report issue` button on bottom-right.

**Comment by marksteven** [comment]
ok will do

**Comment by evilebottnawi** [comment]
https://github.com/prettier/prettier/issues/9175#issuecomment-690127841
