### ISSUE TITLE
Settings - Semicolon- Whether to add semicolon at end of every line - Turned OFF but still adding them.

### ISSUE THREAD

**Issue by marksteven** [prettier/prettier#9175]
Settings - Semicolon- Whether to add semicolon at end of every line - Turned OFF but still adding them.

Input:
Settings Box unchecked should not add semicolons at end of line , but still does even after reboot
disable Prettifier completely and problem goes away
enable - comes back

Output:
Hitting save adds a semicolon in front of MyList even though there was not one there previously.
```
function App() {
  return
  ;<MyList />
}
export default App


**Expected behavior:**
function App() {
  return
  <MyList />
}

works ok if return and MyList is on same line eg
function App() {
  return <MyList />
}
export default App
```
But given this has been disabled in settings should not add semicolons at all so appears to be a bug that has only started doing this lately so assuming there has been a change to be aware of.

Also just noticed that the () brackets were being deleted as well hence why the code above does not have any.
Final product should look like 
```
function App() {
  return (
  <MyList />
)
}
```

**Comment by evilebottnawi** [comment]
Not related to prettier, please open an issue in IDE repo

**Comment by marksteven** [comment]
This is Prettier that has this bug so why is it not here?

**Comment by fisker** [comment]
Do you think these are equal?

```js
alert(function() {
  return 
   1
}())
```

```js
alert(function() {
  return 1
}())
```

**Comment by marksteven** [comment]
Issue is semicolons are disabled in prettifier yet it is still adding them even after reboots.

I was told to put this issue in IDE when as far as I can tell it is a prettifier issue.
Your code above depends as there is a carriage return in there.
For json this makes a difference but for normally for React it usually does not.
However what has been happening to me is prettifier has been adding a semicolon and this automatic semicolon has been breaking the code.
If I disable prettifier so a semicolon is not added it saves and works properly.
If I enable prettifier but untick the semicolon box in settings so it should NOT add a semicolon
it still adds one even with a. reboot.
This has only started recently so assumed there has been some changes to prettifier.
It also deleted brackets on occasion as well.
Now have to use VS code without prettifier as it keeps getting it wrong for some reason.
So yes do have to assume this is bug somewhere or am I missing something?

**Comment by fisker** [comment]
Please use playground to report format issue, https://prettier.io/playground/ there is a `report issue` button on bottom-right.
