### ISSUE TITLE
Properties object format are changed

### ISSUE THREAD

**Issue by massimiliamanto74** [prettier/prettier#9188]
When i configure "single Quote" the code format of object properties is changed though "Quote Props" is "Preserve".

Example.
`userResp["status"] === "OK"` 
is changed first time in 
`userResp['status'] === 'OK'`
and then 
`userResp.status === 'OK'`

Not always object are typed so this last change breaks the code!
Why "Quote Props": "Preserve" doesn't preserve the properties format?

**Comment by evilebottnawi** [comment]
Please use issue template and provide link on playground

**Comment by massimiliamanto74** [comment]
do you mean this?
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOiwVwCMswAnDABxg2iwG0AdEAGQgHMMoBlIk8qmlCYBdAAQBeUemw4AhvnQJqYWdWhc4pAG4YwcBlFFHjOADbtOACmm58WTQBopmXBQDuAEwCUB4yYLEZBiEcJa+fsaWpHBYFLRwSKKyUACeXhIAfKLA4RHGMKQp2bl5xpBQWDCiAFZY0BKiAFJcAPIAcjgUsqT2UTFxFXBeANwGJaWiGABmopa19QBkCzV1UIwglap2IhKSTC0A0kyiSyvQ61gA1iLpOYYTETZyCmhKuqqCGtq6cHhwMAAVCCXBBzVYXa4gYROKD4UymEZje4PYzTWbzNZMaIEUwwLAiMwINjoW7jFHOGTyRSwd5qbiaHR6P4wACq9lIABFVLIwecsTE4XiRHQAAzCRHI8kAXyR5PyLjwvCCAlojElcqYAGF8KRorA2ZoeIF+HSmGSJmJJE8qa8aSo6V9Gfp1eScGx-trdUoDaRLD4XSjFcbgqFLHZNAAlfqJZJpTLFAPktFh9lR2IXGBbfFQ3Z7ECHJikxNy60vN72z4Mn7Mn0pyP9HAebkS81yyYzawKm3lj7qKtM8xsd0eACSUCLbYeT1IEAUmhwUFkOjYqlC6xuo2L0tEcFM9gTk4mydL1OUvfp3yZcAAHhQMNEAPqmH6DCeHiZPG93x-PvSDBoFPgcCbu+eRSjue5wAeoF5E8bgzlAbCatEHhvLIe4AaQQEgTBxgyluKL4TBRGHlKEpyuBu77nck5wQhSEoWhGFWlhwGtn4JETOB9pgGgsxDNBKJ0dADFwKhNLoVgmHYexoicREUoOK2liaDOpDpOIWQ0Q85R1KYvyDipuoQOpOEfgq8EichYlMVJLEyYm8lGCMIAOCAEAqhUyCgN0M5uAACt0CBYMgIDoW4sgpCFbmEKQshgCCMBcF0YCcGwyCAXAblwAAtiEHioR4zDJGw+CyO6ABiJk5ao1CIaFVIQK5IBoDAOWmAA6pg8CxPFcAaBUGDUDoMApKFYBYNFICcOyMD+XFbA1cgUySVlIC1NeABCcUJf8XCyDlcDMJwcDLatbkbVwaX6QAivgEDwGdkFuV0PSaKFo0UDEyowM1FDkLAHUYB46DIAAHCKL0zvYHVxRQoX-TEDKnW5ACO93wPNHkhSgshYAAtFAcA2R4zXROj95wPN5VLUgK3PRsuUYBlrFuVg11wHdD2nXT52oLIhBAyDaDIAATG5BSyBgz6IZqEA5bTIAxAArM14YAgLOP0-YblaEBY7iUlP0AIJQB4XCjfpT32FKUpAA)

**Comment by massimiliamanto74** [comment]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOiwVwCMswAnDABxg2iwG0AdEAGQgHMMoBlIk8qmlCYBdAAQBeUemw4AhvnQJqYWdWhc4pAG4YwcBlFFHjOADbtOACmm58WTQBopmXBQDuAEwCUB4yYLEZBiEcJa+fsaWpHBYFLRwSKKyUACeXhIAfKLA4RHGMKQp2bl5xpBQWDCiAFZY0BKiAFJcAPIAcjgUsqT2UTFxFXBeANwGJaWiGABmopa19QBkCzV1UIwglap2IhKSTC0A0kyiSyvQ61gA1iLpOYYTETZyCmhKuqqCGtq6cHhwMAAVCCXBBzVYXa4gYROKD4UymEZje4PYzTWbzNZMaIEUwwLAiMwINjoW7jFHOGTyRSwd5qbiaHR6P4wACq9lIABFVLIwecsTE4XiRHQAAzCRHI8kAXyR5PyLjwvCCAlojElcqYAGF8KRorA2ZoeIF+HSmGSJmJJE8qa8aSo6V9Gfp1eScGx-trdUoDaRLD4XSjFcbgqFLHZNAAlfqJZJpTLFAPktFh9lR2IXGBbfFQ3Z7ECHJikxNy60vN72z4Mn7Mn0pyP9HAebkS81yyYzawKm3lj7qKtM8xsd0eACSUCLbYeT1IEAUmhwUFkOjYqlC6xuo2L0tEcFM9gTk4mydL1OUvfp3yZcAAHhQMNEAPqmH6DCeHiZPG93x-PvSDBoFPgcCbu+eRSjue5wAeoF5E8bgzlAbCatEHhvLIe4AaQQEgTBxgyluKL4TBRGHlKEpyuBu77nck5wQhSEoWhGFWlhwGtn4JETOB9pgGgsxDNBKJ0dADFwKhNLoVgmHYexoicREUoOK2liaDOpDpOIWQ0Q85R1KYvyDipuoQOpOEfgq8EichYlMVJLEyYm8lGCMIAOCAEAqhUyCgN0M5uAACt0CBYMgIDoW4sgpCFbmEKQshgCCMBcF0YCcGwyCAXAblwAAtiEHioR4zDJGw+CyO6ABiJk5ao1CIaFVIQK5IBoDAOWmAA6pg8CxPFcAaBUGDUDoMApKFYBYNFICcOyMD+XFbA1cgUySVlIC1NeABCcUJf8XCyDlcDMJwcDLatbkbVwaX6QAivgEDwGdkFuV0PSaKFo0UDEyowM1FDkLAHUYB46DIAAHCKL0zvYHVxRQoX-TEDKnW5ACO93wPNHkhSgshYAAtFAcA2R4zXROj95wPN5VLUgK3PRsuUYBlrFuVg11wHdD2nXT52oLIhBAyDaDIAATG5BSyBgz6IZqEA5bTIAxAArM14YAgLOP0-YblaEBY7iUlP0AIJQB4XCjfpT32FKUpAA)
```sh
--parser typescript
```

**Input:**
```tsx
this.subscriptions["LoginSubscription"] = this.authenticationService
      .login(this.user, this.pwd)
      .subscribe(
        (response: any) => {
          try {
            const json = JSON.parse(response);

            if (json && json["status"] == "OK" && json["sk"]) {
              this.authenticationService.setToken(json["sk"], null);

              if (json["results"].length) {
                this.authenticationService.setUserData(json["results"][0]);
              }

              this.subscriptions[
                "CurrentUserSubscription"
              ] = this.authenticationService
                .getCurrentUser()
                .subscribe((userResp: any) => {
                  if (userResp["status"] === "OK") {
                    this.authenticationService.setUser(userResp.data);

                    if (this.authenticationService.loggedIn) {
                      this.router.navigate([""]);
                    } else {
                      if (this.authenticationService.expire_license) {
                        this.expire_license = true;
                      } else {
                        this.wrongCredentials = true;
                      }
                    }
                  }
                });
            } else {
              this.wrongCredentials = true;
            }
          } catch (e) {
            this.wrongCredentials = true;
          }
        },
        (error) => {
          console.log(error);
          this.wrongCredentials = true;
        }
      );
```

**Output:**
```tsx
this.subscriptions["LoginSubscription"] = this.authenticationService
  .login(this.user, this.pwd)
  .subscribe(
    (response: any) => {
      try {
        const json = JSON.parse(response);

        if (json && json["status"] == "OK" && json["sk"]) {
          this.authenticationService.setToken(json["sk"], null);

          if (json["results"].length) {
            this.authenticationService.setUserData(json["results"][0]);
          }

          this.subscriptions[
            "CurrentUserSubscription"
          ] = this.authenticationService
            .getCurrentUser()
            .subscribe((userResp: any) => {
              if (userResp["status"] === "OK") {
                this.authenticationService.setUser(userResp.data);

                if (this.authenticationService.loggedIn) {
                  this.router.navigate([""]);
                } else {
                  if (this.authenticationService.expire_license) {
                    this.expire_license = true;
                  } else {
                    this.wrongCredentials = true;
                  }
                }
              }
            });
        } else {
          this.wrongCredentials = true;
        }
      } catch (e) {
        this.wrongCredentials = true;
      }
    },
    (error) => {
      console.log(error);
      this.wrongCredentials = true;
    }
  );

```

**Expected behavior:**

**Comment by massimiliamanto74** [comment]
[This is the link playground ](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOiwVwCMswAnDABxg2iwG0AdEAGQgHMMoBlIk8qmlCYBdAAQBeUemw4AhvnQJqYWdWhc4pAG4YwcBlFFHjOADbtOACmm58WTQBopmXBQDuAEwCUB4yYLEZBiEcJa+fsaWpHBYFLRwSKKyUACeXhIAfKLA4RHGMKQp2bl5xpBQWDCiAFZY0BKiAFJcAPIAcjgUsqT2UTFxFXBeANwGJaWiGABmopa19QBkCzV1UIwglap2IhKSTC0A0kyiSyvQ61gA1iLpOYYTETZyCmhKuqqCGtq6cHhwMAAVCCXBBzVYXa4gYROKD4UymEZje4PYzTWbzNZMaIEUwwLAiMwINjoW7jFHOGTyRSwd5qbiaHR6P4wACq9lIABFVLIwecsTE4XiRHQAAzCRHI8kAXyR5PyLjwvCCAlojElcqYAGF8KRorA2ZoeIF+HSmGSJmJJE8qa8aSo6V9Gfp1eScGx-trdUoDaRLD4XSjFcbgqFLHZNAAlfqJZJpTLFAPktFh9lR2IXGBbfFQ3Z7ECHJikxNy60vN72z4Mn7Mn0pyP9HAebkS81yyYzawKm3lj7qKtM8xsd0eACSUCLbYeT1IEAUmhwUFkOjYqlC6xuo2L0tEcFM9gTk4mydL1OUvfp3yZcAAHhQMNEAPqmH6DCeHiZPG93x-PvSDBoFPgcCbu+eRSjue5wAeoF5E8bgzlAbCatEHhvLIe4AaQQEgTBxgyluKL4TBRGHlKEpyuBu77nck5wQhSEoWhGFWlhwGtn4JETOB9pgGgsxDNBKJ0dADFwKhNLoVgmHYexoicREUoOK2liaDOpDpOIWQ0Q85R1KYvyDipuoQOpOEfgq8EichYlMVJLEyYm8lGCMIAOCAEAqhUyCgN0M5uAACt0CBYMgIDoW4sgpCFbmEKQshgCCMBcF0YCcGwyCAXAblwAAtiEHioR4zDJGw+CyO6ABiJk5ao1CIaFVIQK5IBoDAOWmAA6pg8CxPFcAaBUGDUDoMApKFYBYNFICcOyMD+XFbA1cgUySVlIC1NeABCcUJf8XCyDlcDMJwcDLatbkbVwaX6QAivgEDwGdkFuV0PSaKFo0UDEyowM1FDkLAHUYB46DIAAHCKL0zvYHVxRQoX-TEDKnW5ACO93wPNHkhSgiPsloKMgNE6P3nA83lUtSArc9Gy5RgGWsW5WDXXAd0PadSCZW5maEEDINoMgABM3NxRgz6IZqEA5ZTIAxAArM14YArIxBPfYblaEBY7iUlP0AIJQB4XCjfpatwFKUpAA)

but in my vscode it works differently.
At first save it format right like in playground but second time it remove `['']` from properties of object.

**Comment by massimiliamanto74** [comment]
I have removed others configuration in vstudio setting and it works correctly, sorry, it should be some conflicts
