### ISSUE TITLE
Question: how to define file type for parser

### ISSUE THREAD

**Issue by hosseinmd** [prettier/prettier#9190]
I developed a prettier plugin for formatting jsdoc [prettier-plugin-jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc)

Currently, in this plugin I used babel-ts parser. But this is troublesome because there is no way to use other parsers.

I try to format jsdoc of JS or TS files I want to use user defined parser like "babel", "babel-flow" or "typescript" in prettier.json

How can I parse with user defined parser?

- Prettier Version: 2.1.1
- Running Prettier via:  Node.js
- Runtime:  Node.js v12

**Comment by evilebottnawi** [comment]
Example - https://github.com/prettier/plugin-php/blob/master/src/parser.js#L4, you have `opts` to get default options

**Comment by hosseinmd** [comment]
@evilebottnawi How do I know what file type of file is parsed?

**Comment by evilebottnawi** [comment]
You need to use `linguist-languages`, example https://github.com/prettier/prettier/blob/master/src/language-js/index.js#L9

**Comment by hosseinmd** [comment]
> You need to use `linguist-languages`, example https://github.com/prettier/prettier/blob/master/src/language-js/index.js#L9

This solved.
