### ISSUE TITLE
prettier 2.1 has a breaking change?

### ISSUE THREAD

**Issue by marwahaha** [prettier/prettier#9194]
Sorry I'm not following the guide.

I maintain https://github.com/moment/moment and our builds are failing because prettier is now on 2.1.1 . I'm not sure why that's the case.

I will downgrade to 2.0.5 for now.

**Comment by evilebottnawi** [comment]
@marwahaha What do you mean - `our builds are failing`, please provide context or logs or something more

**Comment by marwahaha** [comment]
https://github.com/moment/moment/commits/develop

This build failed, for example.
https://travis-ci.org/github/moment/moment/jobs/726735603

This commit fixed it (pinning to 2.0.5)
https://github.com/moment/moment/commit/db9994d8f8dead38be72e9a8442a3884e78c60b3

Hope this is helpful for you. I'll keep it pinned to 2.0.5 for now

**Comment by fisker** [comment]
I'll look into it

**Comment by fisker** [comment]
In v2.1

> Prettier also removes quotes from object keys that are numbers

[Changelog](https://prettier.io/blog/2020/08/24/2.1.0.html#quote-and-unquote-number-keys-8508httpsgithubcomprettierprettierpull8508-by-lydellhttpsgithubcomlydell)

This line quote will be removed https://github.com/moment/moment/blob/a3824e36daca9b39dfcf1bcf4e2782b29f7eaafa/src/locale/ar.js#L10
