### ISSUE TITLE
Remove Unnecessary Parens changes logic of code.

### ISSUE THREAD

**Issue by Bow2Jesus** [prettier/prettier#9202]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

**Comment by Bow2Jesus** [comment]
Prettier removes parens that it deems unnecessary, but sometimes they are very necessary.  It would be better styling to make parens required in some cases than to remove "unnecessary" parens.   

There is probably no way to blanket determine in all cases what is necessary and what is not.  Let the developers decide what is necessary and what is not. 

For example,

Sometimes parenthesis are necessary to cause math operations to be done in the right order.  Parenthesis ensure that the operations will always be done in the order intended by the developer.  Removing the parenthesis causes the associativity rule to be used instead.  This can cause a different result in a math statement with multiple operations.  It also removes clarity of what was intended.

In other cases, the use of parenthesis help clarify the intention of the developer.  Intentionality is a foundation engineering principle that helps create defect free code.

So, either please remove this completely or make it an option so developers can turn it off completely.

**Comment by evilebottnawi** [comment]
No new options, please read https://prettier.io/docs/en/option-philosophy.html, we don't want to change current output, you don't provide code, so I can say why we remove/keep parens
