### ISSUE TITLE
A way to spore the tabs

### ISSUE THREAD

**Issue by vladgovor77771** [prettier/prettier#9205]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEApAygeQHIDoDOMATgJZQDmJAZgJ4AUAOlAATPBOuuECGMArviTMGIfBAC2cdDF4CRAGg7MAvopZslXCXBgALMuSEBGAEwBmNa2VMAlAG4Q8kBAAOMEtHzJQ3IkQgA7gAKvgheKNwANgHcNF5OAEZE3GAA1jroLikGyMR8cE5w4glwACalZQAy3BR83ORwAGIQROK87hTIINx8MBCOILow4pEA6vrw+FlgUmEk7gBu8zRdYPjxIGT4cEQwQcnkbchUUdtOAFb4AB4AQslpGdySlWRwx6cFIJdX6AaRcABFPgQeDvSJnEBZIjbIhdBLcEqRAYuUiwUYkUp6ZAADgADE4URBtqNki4uii4DCFm8nABHYHwfaucLdfAAWigcDKZQGRDg9JIfP29SOSBO4M+23EJFyRHyTnwf0BDLeYo+ThkCXRmN0yBMGuSJEiBgAwhJRSBKQBWAYCOAAFQR4XFEIW+QAklAKrB0GBSG4AIJe6Q0f5g7bKZRAA)
```sh
--parser babel
```

**Input:**
```jsx
JSON.stringify(
  {
    status: "someStatus",
  },
  {
    something: 123,
  }
);
```

**Output:**
```jsx
JSON.stringify(
  {
    status: "someStatus",
  },
  {
    something: 123,
  }
);

```

**Expected behavior:**

```jsx
JSON.stringify({
  status: "someStatus",
}, {
  something: 123
});

```

I would prefer to see more "compact" style where block height not big.

Is there a way to make it so?

**Comment by evilebottnawi** [comment]
You can do this:
```js
JSON.stringify(
  { status: "someStatus" },
  { something: 123 }
);
```

We don't want to change current output, sorry
