### ISSUE TITLE
Doesn't support TypeScript 4's labeled tuple syntax

### ISSUE THREAD

**Issue by cakoose** [prettier/prettier#9208]
Prettier v2.1.1 reports a syntax error in the following code.

```typescript
type X = [a: string, b: string];  // SyntaxError: Unexpected token, expected "," (1:12)
```

Prettier playground: [link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAGtgXmwG0BDJbAZxgCcBLKAcwBpsAjC6+pgXQG4QzEBAww60SslCkaNCAHcACjISSUpADbzSaSULY1SYANZwYAZQxGGjZLQCucIXAC2bOABMPngDKkm9qSMcABiEDQupDBiTMggpPYwEIIgABYwLhoA6ql08JRWYHDmqnl0AG55aHFglHogDJRwNDCKhoyRyABmmk1CAFaUAB4AQoYmZuakLnA+DHDdvU4gg0PmNhpwAIr2EPCLGn0gVjRNNHFspO4aKRjcMFl0HjCpyAAcAAxCdxBNWYYYOJ3OBncoLIQAR128DaIjU8UoAFooHBPJ4UjQ4FC6Ji2kFOkgeodlk0XHQ7DRHEJKBtttCFoSlkIYFdHs9XkgAEzMwx0DQ2ADCEBcBJAIIArCl7E0ACpXNREo7lRwASSg3lg5jA9FEAEF1eZ0JsDk0AL6moA)

TypeScript playground: [link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDaBDAXFAzsATgSwDsBzAGigCMNt9iBdAbiA)

TypeScript added this syntax in v4: ["labeled tuple elements" in the release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements)

There was an earlier bug and apparently also a fix: <https://github.com/prettier/prettier/issues/8646#issuecomment-668025265>.  Maybe I'm missing something?

**Comment by cakoose** [comment]
Oh hmm, looks like the original fix (https://github.com/prettier/prettier/pull/8885) had a caveat:

> Current typescript-estree cannot parse labeled tuple types. So we should put this in /tests/misc/typescript-babel-only for now.

That was on Aug 3.  A week later @typescript-eslint/typescript-estree 3.9 was released and claims to support labeled tuple types: [ChangeLog v3.9](https://github.com/typescript-eslint/typescript-eslint/blob/master/CHANGELOG.md#390-2020-08-10).  And Prettier's current @typescript-eslint/typescript-estree dependency is v3.10.1.

**Comment by sosukesuzuki** [comment]
You seem to be using a babel parser. please use the typescript parser or the babel-ts parser.

**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAGtgXmwG0BDJbAZxgCcBLKAcwBpsAjC6+pgXQG4QzEBAww60SslCkaNCAHcACjISSUpADbzSaSULY1SYANZwYAZQxGGjZLQCucIXAC2bOABMPngDKkm9qSMcABiEDQupDBiTMggpPYwEIIgABYwLhoA6ql08JRWYHDmqnl0AG55aHFglHogDJRwNDCKhoyRyABmmk1CAFaUAB4AQoYmZuakLnA+DHDdvU4gg0PmNhpwAIr2EPCLGn0gVjRNNHHoWJRg9KIpGNwwWXQeMKnIABwADEIPEE1ZQwYOIPOBncoLIQAR128DaIjU8UoAFooHBPJ4UjQ4DC6Ni2kFOkgeodlk0XHQ7DRHEJKBttrCFsSlkIYKQ2M9Xu8kAAmVmGOgaGwAYQgLiJIDBAFYUvYmgAVdlqElHcqOACSUG8sHMNzoogAglrzOhNgcmgBfC1AA)
```sh
--parser typescript
```

**Input:**
```tsx
type X = [a: string, b: string];
```

**Output:**
```tsx
type X = [a: string, b: string];

```

**Comment by cakoose** [comment]
Thanks!

The default parser seems to accept many TypeScript constructs, which I guess confused me a bit...
