### ISSUE TITLE
Standalone tests are slow

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#9217]
This is taking too long, https://github.com/prettier/prettier/runs/1121558091

But not sure how we can improve it.

Related file https://github.com/prettier/prettier/blob/master/tests_config/require_standalone.js

**Comment by thorn0** [comment]
How about running them only for commits to `main`, not for every PR?
Also, I wonder if it's possible to configure it in such a way that a PR author could somehow indicate that he wants these tests to run for the PR.

**Comment by thorn0** [comment]
I tried to cache the concatenated modules (`"standalone.js", "parser-*.js"`) and also to use the `cachedData` parameter of [`vm.Script`](https://nodejs.org/dist/latest-v15.x/docs/api/vm.html#vm_new_vm_script_code_options) but couldn't get any significant improvement.

**Comment by fisker** [comment]
It seems it's much faster on Node.js v16 

 Node.js v16  https://github.com/prettier/prettier/runs/2400699620
 Node.js v14 https://github.com/prettier/prettier/runs/2395999211

~10m vs ~33m

**Comment by fisker** [comment]
Closing since it no longer an issue.
