### ISSUE TITLE
SyntaxError: Unexpected token, expected "{"

### ISSUE THREAD

**Issue by edsel77** [prettier/prettier#9218]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlMTKgCYCWAbiVAATMtV2Nj4DOXAvMSFoAPALQAnCAHcBDFnNY1aHbnwHCRkHIy4YkkkQEYA9ACZG+gGYBXHFowAjESZml5bhe054e-EBOkgsu7BzKg6eLaEAMoweGIwjJQEcKhG4ZGuIXKpikFZoYrK3qp+UokEeBoqLkz5bmFYeFCEwMBWUNRCACoQMU1JYpQAIskAFFyx8QD6SfAAlAC+C6lcjc2ZdTl0ee5b9BusRrmk5HsMqZi4yYQgADQgEFgw1NBcyKBx-gAKcQhvKBFJHgAJ5ve72MR4MAAazgMCijTA1CgAHNkDAxFY4Pc4A44JRKPiADJNFFWPAouAAMQgYgwBGeqOQIDwVhgEDuIAAFjAMDgAOpc6jwVZQuBRP7CujC4HMsA8TnIrhweJfSEo+nICwRZX3ABWXCEACFITC4VE8Bg4ETkXAtTrsSADUIosiUTg4ABFKwQeD2nC6kCNMTKsTM+x4exwHCcrBiZEwfnUSgwLnIAAcAAZ7nGIMr+ZCsMy43BQ7Q7fcAI4++Bqx7-FlcERQOD4-GcsRwavUTtqimapDagOO5UYajozEjt0e72+u2Dh33WL2JMptNIExLyHUHBugDCEAwA5ApYArJyrMqupH-kPA7QsQBJKCE2BRMDxp4AQRfMWBHv9ZUliAA)
```sh
--parser babel
```

**Input:**
```jsx
<template>
	<div>
      <div class="vx-row">
          <div class="vx-col sm:w-1/2 w-full mb-2">
              <div class="row">
                  <small>Start date</small>
              </div>
              <div class="row data-class">
                  <span>{{unixToStandardDate(start_date)}}</span>
              </div>
          </div>
      </div>
	</div>
</template>
```

**Output:**
```jsx
SyntaxError: Unexpected token, expected "{" (9:57)
   7 |               </div>
   8 |               <div class="row data-class">
>  9 |                   <span>{{unixToStandardDate(start_date)}}</span>
     |                                                         ^
  10 |               </div>
  11 |           </div>
  12 |       </div>
```

**Expected behavior:**

**Comment by evilebottnawi** [comment]
Because you need to use `vue` parser
