### ISSUE TITLE
Odd indentation in expect call.

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#922]
See: https://github.com/cpojer/jest/blob/master/packages/jest-mock/src/__tests__/jest-mock-test.js#L166

before:
```js
    it('mocks regexp instances', () => {
      expect(
        () => moduleMocker.generateFromMetadata(moduleMocker.getMetadata(/a/)),
      ).not.toThrow();
    });
```

after:
```js
    it('mocks regexp instances', () => {
      expect(() =>
        moduleMocker.generateFromMetadata(
          moduleMocker.getMetadata(/a/),
        )).not.toThrow();
    });
```

I would at least expect:

```js
    it('mocks regexp instances', () => {
      expect(() =>
        moduleMocker.generateFromMetadata(
          moduleMocker.getMetadata(/a/),
        ),
      ).not.toThrow();
    });
```

but the current behavior seems wrong.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22it('mocks%20regexp%20instances'%2C%20()%20%3D%3E%20%7B%5Cn%20%20expect(%5Cn%20%20%20%20()%20%3D%3E%20moduleMocker.generateFromMetadata(moduleMocker.getMetadata(%2Fa%2F))%2C%5Cn%20%20).not.toThrow()%3B%5Cn%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Thanks! Likely the same issue as https://github.com/prettier/prettier/issues/797

**Comment by vjeux** [comment]
Going to close this as it's being tracked by #974
