### ISSUE TITLE
semi is not work in .ts files.

### ISSUE THREAD

**Issue by PolanZ** [prettier/prettier#9237]
The **Prettier - Code formatter** VS Code plugin. 
prettier cli is work.

typescript files is not work, javascript files is work

**Version**
2.1.2

**Options (if any):**
.prettierrc.js
```js
module.exports = {
  trailingComma: 'es5',
  semi: true,
  singleQuote: true,
};
```

**Input:**

_test.ts_
```jsx
const a=123
```

test.js
```js
const a=123
```

**Output:**

_test.ts_
```jsx
const a = 123
```

test.js
```js
const a = 123;
```

**Comment by andersonAlmeida** [comment]
Was it fixed? I am facing the same trouble.
