### ISSUE TITLE
Odd indentation for multi-line ternaries

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#924]
See https://github.com/cpojer/jest/blob/master/packages/pretty-format/src/__tests__/ImmutablePlugins-test.js#L35

before:
```js
const message = pass
      ? () =>
          this.utils.matcherHint('.not.toBe') +
          '\n\n' +
          `Expected value to not be:\n` +
          `  ${this.utils.printExpected(expected)}\n` +
          `Received:\n` +
          `  ${this.utils.printReceived(prettyPrintImmutable)}`
      : () => {
        const diffString = diff(expected, prettyPrintImmutable, {
          expand: this.expand,
        });
        return this.utils.matcherHint('.toBe') +
          '\n\n' +
          `Expected value to be:\n` +
          `  ${this.utils.printExpected(expected)}\n` +
          `Received:\n` +
          `  ${this.utils.printReceived(prettyPrintImmutable)}` +
          (diffString ? `\n\nDifference:\n\n${diffString}` : '');
      };
```

after:
```js
const message = pass
      ? () =>
          this.utils.matcherHint('.not.toBe') +
          '\n\n' +
          `Expected value to not be:\n` +
          `  ${this.utils.printExpected(expected)}\n` +
          `Received:\n` +
          `  ${this.utils.printReceived(prettyPrintImmutable)}`
      : () => {
          const diffString = diff(expected, prettyPrintImmutable, {
            expand: this.expand,
          });
          return this.utils.matcherHint('.toBe') +
            '\n\n' +
            `Expected value to be:\n` +
            `  ${this.utils.printExpected(expected)}\n` +
            `Received:\n` +
            `  ${this.utils.printReceived(prettyPrintImmutable)}` +
            (diffString ? `\n\nDifference:\n\n${diffString}` : '');
        };
```

See the indentation of the second function after the `:`. The function body is indented one level more than it should be.

**Comment by vjeux** [comment]
For ternary, we actually indent with the start of the expression

```js
a
  ? {
      // indent
    }
  : {
      // indent
    }
```

**Comment by marcusdarmstrong** [comment]
Just tried out Prettier on my own project and also found this formatting to be pretty strange—It's especially odd when you're using tabWidths that aren't 2, since that means anything inside the inner objects are indented by a non-tabWidth offset, and seems pretty inconsistent with the rest of Prettier's style principles.

**Comment by hawkrives** [comment]
Just to chime in: I appreciate this style of indentation, aligning the object with itself instead of with the ?:.

**Comment by darobin** [comment]
@cpojer Could you maybe be a bit clearer regarding your expectations? In your before you have the true branch of the ternary indented more than the false branch, and prettier handled that by providing both branches with the same indentation. It strikes me as sensible (to the extent that style ever is) that blocks at the same logical depth would be represented at the same indentation depth. Am I missing something?

**Comment by cpojer** [comment]
Oh, I actually didn't notice that. Yeah, the first one doesn't have curly braces. Hmmmm…

**Comment by jussi-kalliokoski** [comment]
I have some cases where ternaries are used as expression style `if`s, for example:

```javascript
const animation =
  targetState === IN_GAME && currentState === HIDDEN ?
    self._overlayAnimations.showInGameView()
  : targetState === IN_GAME ?
    self._overlayAnimations.hideOverlay()
  : targetState === OPEN ?
    self._overlayAnimations.showOverlay()
  : targetState === HIDDEN ?
    self._overlayAnimations.hideAll()
  : null;
```

and I personally find this style quite nice - prettier currently however seems to go a bit overboard with indentation on this:

```javascript
const animation = targetState === IN_GAME && currentState === HIDDEN
  ? self._overlayAnimations.showInGameView()
  : targetState === IN_GAME
      ? self._overlayAnimations.hideOverlay()
      : targetState === OPEN
          ? self._overlayAnimations.showOverlay()
          : targetState === HIDDEN ? self._overlayAnimations.hideAll() : null;
```

**Comment by rhengles** [comment]
@jussi-kalliokoski You're in luck - there is an option for an alternate rendering implemented in https://github.com/arijs/prettier-with-tabs/commit/290aee15e02de453909cdd8a7a91c3ecaf74bfad as `flattenTernaries` option (as commented on https://github.com/prettier/prettier/issues/737#issuecomment-283104970)

**Comment by jussi-kalliokoski** [comment]
@rhengles Ooh that's nice, thanks for the pointer!

**Comment by corydeppen** [comment]
I've been noticing the [language-babel package](https://atom.io/packages/language-babel) for Atom fights the Prettier formatting when auto-indenting JSX like the following. While the Prettier formatting is easier to read, the spacing doesn't appear consistent with code outside the ternary (as @marcusdarmstrong [mentions](#issuecomment-285262402)). I'm not clear which is the expected output and whether an issue needs to be filed for the Atom package or not. Would it be feasible/desirable to maintain the parens that wrap the multi-line expression like the third snippet below? The language-babel package doesn't have an issue with the snippet when wrapped in parens, the indentation is consistent, and it's easy to read, similar to the current Prettier formatting.

```jsx
// Prettier
{inputType === 'select'
  ? <Input id={id} type="select" {...input}>
      {placeholder && <option value="">{placeholder}</option>}
      {options}
    </Input>
  : <Input id={id} {...input} />}

// language-babel
{inputType === 'select'
  ? <Input id={id} type="select" {...input}>
    {placeholder && <option value="">{placeholder}</option>}
    {options}
  </Input>
  : <Input id={id} {...input} />}

// Alternative?
{inputType === 'select'
  ? (
    <Input id={id} type="select" {...input}>
      {placeholder && <option value="">{placeholder}</option>}
    	{options}
    </Input>
  ) : <Input id={id} {...input} />}
```

**Comment by jlongster** [comment]
@corydeppen fwiw it shouldn't really matter anymore if your editor doesn't indent some things correctly. Just bind prettier to a keystroke and run it when needed. I do this all the time! We can't play the cat-and-mouse game of produce code that works with all editor plugins.

For you case, I don't think the parens add much, so I think you should try to fix it in your editor. We should take a look at nested ternaries, however, and see if we should do something better.

**Comment by tlrobinson** [comment]
Something like `flattenTernaries` would be awesome, especially in JSX. This is a pretty common pattern:

```javascript
<div>
{
  conditionA ?
    <div>foo</div>
  : conditionB ?
    <div>bar</div>
  :
    <div>baz</div>
}
</div>
```

which currently gets formatted as:

```javascript
<div>
  {conditionA
    ? <div>foo</div>
    : conditionB ? <div>bar</div> : <div>baz</div>}
</div>
```

**Comment by vjeux** [comment]
I'm going to concentrate all the ternary discussions in https://github.com/prettier/prettier/issues/924

**Comment by tlrobinson** [comment]
@vjeux Which issue? You closed #924 (this one)

**Comment by k15a** [comment]
I think he meant this #1271? :D

**Comment by vjeux** [comment]
Sorry, I meant https://github.com/prettier/prettier/issues/737
