### ISSUE TITLE
Doc builder support for Playground

### ISSUE THREAD

**Issue by zweimach** [prettier/prettier#9245]
It would be very helpful for contributors and maintainers if we could directly edit the Doc Intermediate Representations in the Playground.

This will also attract more contributors because everyone can try their customizations and fixes before hacking and searching the source code.

**Comment by sosukesuzuki** [comment]
I think it would be helpful but I think it is hard to implementing...

By the way, I used to develop a Playground for such a doc builder. 
- site: https://prettier-doc-playground.netlify.app/
- repo: https://github.com/sosukesuzuki/prettier-doc-playground

This is still experimental, but if this is useful for contributors I start to maintain.

**Comment by thorn0** [comment]
I played with this too: [demo](https://prettier-doc.netlify.app/playground/#N4Igxg9gdgLgprEAuEBzAThArgBwBQCWUAJgjHpFGAIbkDaAOlAATMMgBGBAZhOlAGF0RVHHQBZCAGcAFnGIAFMTgA2cAB4BlagHdS6dgBomrFUTjGWbENSkBrACqYAbgmoAhOG4AicHAmIpACUIHWooKXYmAF0ASniQQxAIHBgCaClkUGp0TB0FHIRMlGoVMIBPTKSOdGowOzgYTRw6kWQYdCwLEDgAWw55UmIAGXDULGpRADE+Xto0qFRkGywYCESQGRhelQB1GQJ4KRawOE0iw4JnQ-LlsCkqkCIpMRgFWtQ55G5Sl6SAKyk6nctXqjW0vTgw3M31+3UBWhEagAilgIPBYSo-iAWugXuhljh0I00mIALTECBgDZEogwXYEYgwGTIACsAHYkkTpHBdrUcITifjXBsAI5o+DvFLFGxSMlQLxDDbE8UEYnvSZfJA-LHdF69AjtTp6pFwVHouCY7EwagcBlMllIABMSQ61AIZkWAggvS1PSkrI2WBeDltxR12OcXQAkiQyJowMJUgBBEiaGDlNRWuAAXxzQA), [branch](https://github.com/thorn0/prettier/tree/doc-explorer)

**Comment by sosukesuzuki** [comment]
Looks good.

**Comment by thorn0** [comment]
It uses a [`with` statement](https://github.com/thorn0/prettier/commit/e7b73d5814780150d00e7b6dec6db13e559e5303#diff-0ad053a501f4cae79d330ef51c23e1f8R9) 😱
