### ISSUE TITLE
Unnecessary new line in arrow function

### ISSUE THREAD

**Issue by mgmcdermott** [prettier/prettier#925]
Before:
```js
export const selectShapeData = (
  state : AppState,
  containerId : string,
  shapeId : string,
  entityName : string,
) => getPath(['shapeData', containerId, shapeId, entityName], state) || null;
```

After:
```js
export const selectShapeData = (
  state : AppState,
  containerId : string,
  shapeId : string,
  entityName : string,
) =>
  getPath(['shapeData', containerId, shapeId, entityName], state) || null;
```

Note that the "Before" satisfies my configured line length of 100 characters.

**Comment by vjeux** [comment]
Can you upgrade to the last version of prettier, I fixed this recently. It doesn't repro on 0.21 anymore

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20const%20selectShapeData%20%3D%20(%5Cn%20%20state%20%3A%20AppState%2C%5Cn%20%20containerId%20%3A%20string%2C%5Cn%20%20shapeId%20%3A%20string%2C%5Cn%20%20entityName%20%3A%20string%2C%5Cn)%20%3D%3E%20getPath(%5B'shapeData'%2C%20containerId%2C%20shapeId%2C%20entityName%5D%2C%20state)%20%7C%7C%20null%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by mgmcdermott** [comment]
Sorry if I wasn't clear enough, what kind of information do you need?

**Comment by vjeux** [comment]
Can you upgrade your version of prettier to 0.21 and see if that fixes your problem?

**Comment by mgmcdermott** [comment]
Happened through prettier-atom 0.22.0. Wasn't sure if I should make an issue here or there.

**Comment by vjeux** [comment]
Hmm, this is weird, this is up to date. I'm not sure what is going on. If you look at the web version, it does work and break correctly. Maybe restart atom so it makes sure to use the latest version?

**Comment by mgmcdermott** [comment]
I found it.
<img width="536" alt="screen shot 2017-03-07 at 2 24 59 pm" src="https://cloud.githubusercontent.com/assets/8161781/23673879/e4d0ab44-0341-11e7-9155-0234b5defae2.png">
prettier-eslint uses prettier 0.19.0. Enabling the eslint integration option in the plugin uses prettier-eslint which in turn uses the outdated prettier version.

**Comment by vjeux** [comment]
Good catch! We need to figure out how to get all the tools to use a canonical version. See https://github.com/prettier/prettier/issues/918 for discussions around it.

I'll close this issue for now.
