### ISSUE TITLE
Extra parenthesis around export default async function

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#926]
```js
export default async function() {};
```

turns into

```js
export default (async function() {});
```

cc @bakkot, this is what I was trying to fix in the other pr :)

**Comment by existentialism** [comment]
This is https://github.com/prettier/prettier/issues/700, which is fixed in latest Babylon. We had to revert the fix in 6.x due to some breaking changes, so the fix currently lives in the [7.x branch](https://github.com/babel/babylon/pull/377), currently `7.0.0-beta.4`
