### ISSUE TITLE
Formatting `mdx`, from v2.0.0 to v2.1.2 now a new line is introduced

### ISSUE THREAD

**Issue by kuworking** [prettier/prettier#9260]
After upgrading Prettier from some version higher than 2.0.0, I see now that the formatting for a particular code has changed in `mdx` files

This code 

```
# title

<Parenthesis>

CR: Carriage Return, \r
LF: Line Feed, \n

</Parenthesis>

```

was preserved by Prettier before (>2.0.0)

Now it gets an extra new line

```
# title

<Parenthesis>


CR: Carriage Return, \r
LF: Line Feed, \n

</Parenthesis>

```

My `.prettierrc` is this (prettier 2.1.2, eslint-config-prettier 6.11.0)

```json
{
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5",
  "printWidth": 120,
  "arrowParens": "avoid"
}
```

__How can I prevent this?__

*Didn't inserted the playground because this code (changing `<Parenthesis`> for `<div>`) gives an error, but it should not)

EDIT:

I'm trying to downgrade Prettier, but somehow I can't see a consistent behavior

Going one by one to 2.0.3 has reverted the issue, then going upwards at 2.1.0 I had the correct behavior, and at 2.1.1 I had again the new extra line

But now I've downgraded directly to `2.0.0` and I see the same new line (but upgraded to 2.0.1 and I don't see it)

So I don't know what is happening (I'm using yarn)

Now I'm at 2.1.0 and I don't see the new line, so my bet is from 2.1.0 to 2.1.1 (https://github.com/prettier/prettier/blob/master/CHANGELOG.md#211)

**Comment by fisker** [comment]
Maybe introduced by https://github.com/prettier/prettier/pull/9143

**Comment by fisker** [comment]
Introduced by #8825
