### ISSUE TITLE
Add --extension flag

### ISSUE THREAD

**Issue by fregante** [prettier/prettier#9271]
I just saw this config example:

```json
{
  "scripts": {
    "prettier": "prettier --single-quote --write \"src/**/*.{js,css}\" \"docs/**/*.md\""
  }
}
```

What if you could specify the file extensions explicitly?

```json
{
  "scripts": {
    "prettier": "prettier --single-quote --write --ext js,css,md src docs"
  }
}
```

The only reason why I'd want to use a glob in the first place would be to **limit** Prettier to _some_ extensions, so why not make this desire super clear with a dedicated flag? Globs can get ugly, difficult, and are error-prone.

**Globs can still exist for advanced usage**, but regular users should never need them.

More easily:
```sh
prettier --write "./src/**/*.{ts,tsx}"
# becomes
prettier --write src --ext ts,tsx
```

**Comment by lydell** [comment]
The recommended way is to use `prettier --write .` with a .prettierignore file: https://prettier.io/docs/en/install.html

Can you try ignoring _everything_ in .prettierignore and add `!` lines to it to unignore the things you actually want to format? Alternatively, could you provide more info on why you want to limit Prettier to some extensions? Examples and use cases are great.

**Comment by fregante** [comment]
Recommended way or not, if you’re going to support globs, that’s what people are using to specifically limit Prettier to some files, either because they don’t need/like Prettier on every file or because they don’t need it on every folder. 

For example personally I don’t like how it mangles HTML so I only run that extension manually occasionally and discard unwanted text. I treat Prettier as a useful formatting tool, not always as something I **must** install and configure in every project.

**Comment by evilebottnawi** [comment]
@fregante Why do not use `prettier --write . "!*.html"`?

**Comment by lydell** [comment]
@fregante It sounds like you want `*.html` in your .prettierignore?

You can use `npx prettier --write path/to/file.html --ignore-path nope` when you format stuff manually and want to bypass .prettierignore.

**Comment by fregante** [comment]
> @fregante Why do not use `prettier --write . "!*.html"`?

Glob strikes again, that doesn't work, even if it looks like it should. Example run:

<img width="254" alt="" src="https://user-images.githubusercontent.com/1402241/94291793-aaa27a80-ff21-11ea-9415-22236b174e60.png">


> You can use `npx prettier --write path/to/file.html --ignore-path nope` when you format stuff manually and want to bypass .prettierignore.

Globs are used because I don't have a single `file.html`, so how can I write that to cover all HTML files in a folder, for example?

**Comment by evilebottnawi** [comment]
Sorry, we don't want to implement `--extension`/`--no-extension` options, because it is unnecessary, also each `extension` associated with special parser/printer, so implement this will be misleading, if you write `--extension custom` we don't know what is parser/printer we should use, there are a lot of other ways to archive and solve your problem

**Comment by lydell** [comment]
> Globs are used because I don't have a single file.html, so how can I write that to cover all HTML files in a folder, for example?

That’s exactly what globs are for, I’d say! `npx prettier --write "your-folder/**/*.html"`. Stick it in a script if you run it semi-regularly – then you won’t need to remember any details.
