### ISSUE TITLE
[Feature Request] Formatting Rust source code

### ISSUE THREAD

**Issue by arnabanimesh** [prettier/prettier#9272]
I really like it when Prettier formats the documents automatically on save. However, since I code mostly in Rust I miss Prettier since it doesn't support Rust.

_**One possible really simple implementation:** Calling `rustfmt` from the rust compiler when saving a `.rs` file would suffice. A warning if the option is enabled without rust installed can warn the user._

**Comment by sosukesuzuki** [comment]
I'm not familiar with rust, but I think `rustfmt` is enough. If it is not enough for you, you can implement a Prettier plugin for formatting rust.:+1: (see https://prettier.io/docs/en/plugins.html)
