### ISSUE TITLE
Prettier thinks there is a comma and expects a semicolon but there is no comma. 

### ISSUE THREAD

**Issue by AlexanderProd** [prettier/prettier#9273]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzAllAEwAUBDNNAdwgCcDMBeTMgTyjEwAoSxIBXWAKIBbErgA2AGky80calBJC4ASgYA+TMAA6UTJmpwYveZihwKmItQhDcsjhwNoIYgG5wpBgFZwwMVfQa2rp6mDDUzJo6oaGQUBjSstRoDJgEAEYAdJBiYr4wuNAcAOQycmjFygDc0TGYAPT1mAAOBjAFcgC0uADmUDRwtTFxCU68YliMJBSiWGXJmXiEHMCYcCLiSEw8EPwwwqJimAC+ykOx6FirzWSUNHTHqWMTmfgYJD3UigCCO3toi3wBA45xi3D4sHU2whMEy8wUSgY9EY8MUgxCMWqoP0cGcbjgHBu5CotCxGJOmDAJBgYAAFpw5NZqKpgnUcT4-BxGTQyTFjrVTjUoMcqiAJCAIM0CuhkKASNRrBRSAZ4sgQCQxDNmGgxSB0l8wABrQwAZRuYHwPWQ4V4HhA63ScAIBCdABkSFAerwPnAAGI0ETtS1qki8GAQXW0mBCMQAdVpuHgaHNcBNCDQidwrkTzDVYHIurechgVg+ImQ2A1snFXjQAA8AEIG40wE1o134OAVqt22t1k2WvIARV4EHg3bE1ZAN2ScjV6RIjrEuta+BgsdwBBgtOQAA4AAzi1oQWSxr7NNWtXFydy6gCOo-gVklOpQZE6ZidTt1BgfuAMpY9OWSCVpOdqyLY1rULa4oZp6w6Pl2IE9uKMCLhuW47kgABMqFfOIloAMI2MB9poAArLqZQACqLq+oFTq4toAJKEAgrZgNQuBSt8hAmjAzB5BOsjHMcQA)
```sh
--parser babel
```

**Input:**
```jsx
const findPassword = async (accountEmail, username) => {
  return new Promise((resolve, reject) => {
    try {
      const users = db.collection('users');
      // prettier-ignore
      const result = await users.find({ email: accountEmail })
      const { password } = result.instagramAccounts.find(
        account => account.username === username
      );
      resolve(password);
    } catch (error) {
      reject(error);
    }
  });
};
```

**Output:**
```jsx
SyntaxError: Unexpected token, expected ";" (6:28)
  4 |       const users = db.collection('users');
  5 |       // prettier-ignore
> 6 |       const result = await users.find({ email: accountEmail })
    |                            ^
  7 |       const { password } = result.instagramAccounts.find(
  8 |         account => account.username === username
  9 |       );
```

**Expected behavior:**
Prettier thinks there is a comma and expects a semicolon but there is no comma.

**Comment by evilebottnawi** [comment]
> Cannot use keyword 'await' outside an async function (5:21)

Not prettier problem
