### ISSUE TITLE
Inlined skipped tests result in an inconsistent behavior

### ISSUE THREAD

**Issue by denis-sokolov** [prettier/prettier#9285]
In #2900 the formatting of skipped tests has been tailored to inline. All examples in the PR included tests with empty test bodies, but that is not at all always the case. If the test body contains code, the behavior of the formatter becomes erratic: as I add or remove the `skip` modified, the indentation of the entire test changes.

I think the heuristic that should have been used in #2900 was not that the tests are skipped, but that the callback parameter is an empty function.

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMB0aDWBLACgB0QBDAAgBtoBzcqUgWznIDMIAnci9GcgEzhowHPACM8UOmgjM2AVyhgYeaKUp4YAT3KduUCDAAWcDiQA0CpSugEYASmBEo5cgHo3AiOQzzWrZwBfe2dnXmx8AAdiMipaeiYWdi4eIT5BYVEJKR9ZJMVlVQYNbV0Ug2NTCytC2wcnF3dPfm9ffyCQqDC0iLxI6JIKahyGOWTucl4BIRFxSWk8mptizR09UgqTMxBLVgLlu0dnVw8vHxg-AKhgnZAISOW0ZFBSDg4IAHcABVeEJ5R1B9SFonuYQGIOKQwDg4DAAMqRKHzZAwDjyOBguCMMRwfiCfgAGQ2NHkpBocAAYpxGKQYCopMgyPIYBBbkYYIxKAB1IyaISIsBwOF-TR4ABuq0ZYDQoJAkjQphgX0hNBpyFY6gVYIAVmgAB4AIUh0NhcMSBMkcHVmoxIF1erh80ocAAivJDFakBrKFqQIiOAqOIyxKQcZRbpFRLAuXh+MZkAAOAAMYMjEAVXMhkUZkaEpjFVrBAEd3fBlfd-mQ0ABaKBwXG424cOAlvDN5VktVem1ghWMPAotG2tBO12lz3e30wUMxuNGZAAJjBqNIeA0UgAwrIuyAhABWW7yBUAFVD-0ntrF6IAklBBLA4bMHgBBO9w7TO60+uCBQJAA)
```sh
--parser babel
```

**Input:**
```jsx
test.ski("a long name for a test describing some functionality or another", function(t){
  // 20 lines
})

test.skip("a long name for a test describing some functionality or another", function(t){
  // 20 lines
})

test.skipp("a long name for a test describing some functionality or another", function(t){
  // 20 lines
})
```

**Output:**
```jsx
test.ski(
  "a long name for a test describing some functionality or another",
  function (t) {
    // 20 lines
  }
);

test.skip("a long name for a test describing some functionality or another", function (t) {
  // 20 lines
});

test.skipp(
  "a long name for a test describing some functionality or another",
  function (t) {
    // 20 lines
  }
);

```

**Expected behavior:**
All three cases above are consistently inlined or not inlined.

**Comment by thorn0** [comment]
This works as intended. See the docs: https://prettier.io/docs/en/rationale.html#testing-functions
`test.skip` is a well-known testing framework function. `test.skipp` isn't. See also #4424
