### ISSUE TITLE
/* */ in object literals

### ISSUE THREAD

**Issue by gaearon** [prettier/prettier#929]
This strikes me as odd:

```js
var x = {
  a: b, /* wow */
};
```

becomes

```js
var x = {
  a: b /* wow */,
};
```

with trailing commas.

Note how `/* */` is put before the comma.

I don't feel strongly about this since I could've used `//` which works correctly, but it was a bit surprising.

**Comment by vjeux** [comment]
The comment placement logic doesn't take into account `,` so both cases are the same right now and we normalize to the first one:

```js
var x = {
  a: b /* wow */,
  a: b, /* wow */
};
```

We may want to be more fine grained about it.

**Comment by vjeux** [comment]
If someone is interested in making the canonical placement for inline comment of an object key/value pair before the `,`, I would be happy to accept a PR. But this is very low pri and i'm going to close this issue in order to keep them actionable and high signal.
