### ISSUE TITLE
Testing with source code from other repositories

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#9290]
We run the latest Prettier on the other repositories' source code to check for regressions before we release.

like below:
- https://github.com/sosukesuzuki/eslint-plugin-vue/pull/1
- https://github.com/sosukesuzuki/excalidraw/pull/2
- https://github.com/sosukesuzuki/typescript-eslint/pull/1

This is hard to do manually, so I want to automate it.

**Comment by fisker** [comment]
Use a separate repo,

- add `prettier/prettier` and other repositories as submodule.
- add GithubActions, when open an issue with specific title, CI send a PR with formatted code.

**Comment by sosukesuzuki** [comment]
What do you think about adding to this repository as a normal test and checking with a CI for each PR?

**Comment by fisker** [comment]
Will this test fail, if format changed? Or are you thinking about snapshot the result?

**Comment by sosukesuzuki** [comment]
Sorry, I was mistaken. I'll try with your suggestion.

**Comment by sosukesuzuki** [comment]
I created a repository https://github.com/sosukesuzuki/prettier-regression-testing.
I don't know the way to see diffs of submodules on PR. So, I implemented an action using issue comments for checking diffs. See example issue: https://github.com/sosukesuzuki/prettier-regression-testing/issues/4.
This has only `typescript-eslint` as a submodule because work in progress.

**Comment by fisker** [comment]
Maybe no submodule, `git clone` -> `git commit ` -> `run format` -> `git commit`?

**Comment by sosukesuzuki** [comment]
Hmm, we want to see just diffs. So I think submodule and issue comments is enough. They are also relatively easy to manage.

**Comment by fisker** [comment]
I don't know how to see submodule diff either.

> git clone -> git commit -> run format -> git commit

We can check the second commit to see diff.

**Comment by sosukesuzuki** [comment]
> I don't know how to see submodule diff either. 

https://github.com/sosukesuzuki/prettier-regression-testing/issues/4#issuecomment-701849136

I'll use it to check regressions in the next release. If we are unhappy with it, you can improve it afterwards.
I close this issue for now.
