### ISSUE TITLE
Translate cursor position

### ISSUE THREAD

**Issue by glenjamin** [prettier/prettier#93]
I'm not quite sure what the API / CLI would look like for this, but it'd be cool
If you could pass in the current cursor position and be told where the equivalent position is in the output.

This would be for editor plugins so you can prettify without losing your spot.

**Comment by wmertens** [comment]
OTOH, not implementing this simply means that in some cases your cursor is on a very nearby position while doing incremental prettifying

**Comment by demoneaux** [comment]
I don't think this would be easy to do with Prettier, as it does not generate a sourcemap. With a sourcemap, the cursor position can be located at a specific AST node, and the sourcemap can be used to find the resulting node. However, without that, the only easy way would be to reparse the generated code to regenerate an identical AST with the new location properties, and map from the old node to the new node, but that would be bad performance-wise.

**Comment by jlongster** [comment]
Yeah, we would need something like sourcmaps to make this work. We don't support them now, but we might in the future to also allow prettier to be a frontend to other build tools that want to generate code from ASTs. It's probably going to be a lot of work though.

I'm worried that sourcemaps is going to decrease performance a lot, which makes it harder for the in-editor formatting use case. I'm not sure it's worth the perf hit to maintain cursor position, but I suppose it could be optional. Generating sourcemaps is typically very heavy so I'd expect to see a 20-30% perf decrease.

**Comment by ftlio** [comment]
Does anyone have a temporary solution for emacs?  It doesn't have to be exact, but in a class definition the cursor will jump to the top of the class.  The before-save-hook has some pretty frustrating quality of life repercussions.

**Comment by vjeux** [comment]
We've been thinking about this with @cpojer and we found a solution that should work.

1) After we have the AST, use the same binary-search technique as comments in order to find what AST node the cursor position is in.
2) In the generic print function, if we are about to print that node, then add a special cursor token with the offset the cursor was compared to the ast node.
3) When we are about to print that token, the new cursor should be at the token position + delta.

If anyone is interesting in trying it out, that would be great! cc @rattrayalex @jlongster

**Comment by EnoahNetzach** [comment]
If no one is around, I could take a try at this :3

**Comment by josephfrazier** [comment]
I decided to give this a shot at https://github.com/prettier/prettier/pull/1637. If you're interested in having this feature, I'd appreciate feedback :)

**Comment by vjeux** [comment]
It's been built :)
