### ISSUE TITLE
Cli different between `prettier .` and `prettier ./`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#9300]
I found this long time ago, but fogot to open an issue. 

I forgot what's the difference between them. I'm not near a desktop, will check later.

**Comment by lydell** [comment]
Did you find a difference in the end?

**Comment by fisker** [comment]
Sorry, I'm on vacation.

**Comment by fisker** [comment]
I'm sorry, didn't find anything. Must be a mistake.

**Comment by fisker** [comment]
Turns out there is

```console
$ ls
1.js  1.unknown

$ prettier .

$ prettier ./
[error] No supported files were found in the directory: "./".
```

**Comment by fisker** [comment]
Because 

```text
> require('fast-glob').sync('./**/*')
[ '1.js', '1.unknown' ]
> require('fast-glob').sync('.//**/*')
[]
```

**Comment by fisker** [comment]
Not sure if it's a bug, or do we need remove the trailing `/`, `node-glob` behave like this

```text
> require('glob').sync('./**/*')
[ './1.js', './1.unknown' ]
> require('glob').sync('.//**/*')
[ './1.js', './1.unknown' ]
```

@mrmlnc Can you help here?
