### ISSUE TITLE
Remove unnecessary curlies around JSX string attributes

### ISSUE THREAD

**Issue by jrr** [prettier/prettier#9302]
This was brought up and closed a few years ago ( https://github.com/prettier/prettier/issues/2211, https://github.com/prettier/prettier/issues/3303 ), but I thought I'd try again. Could Prettier remove unnecessary curlies around JSX string attributes?:

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAYhCACAFnAGwIgF5gAdEAd1wEMYByAZ2wFcAHSgX2wHoA+EABoQEdjACW0JslC0ATvIhUACgoQyUtAlVoBPGSIBG82mADWcGAGV2ZiVADmyGPNZwRcALZG4AEz9-ABlaJ1ZaRzhMeS96SSdkEFpWGAhhEFwYLwIAdVwJeCY7MDhrDQKJADcCvUSwJkMQByY4eRgVU0dY5AAzbRaRACsmAA8AIVMLK2taLzgghzhe-o8QYZHrB0cCOABFVgh4ZYIBkDt5FvlEo1pfAnT2eQcYHIk-GFxkAA4ABhFHiAtHKmdiJR5wS6VJYiACOB3gHTEmiSTAAtFA4P5-Ol5HA4RJcR0It0kH0TqsWl4JC43BStjt9oclqSViIYLdXu9PkgAExs0wSAhbADCEC8JJAEIArOlWC0ACq3TRk06VdwASSggVg1jAT3EAEEtdYYHodscWlwuEA)

```sh
--parser babel
```

**Input:**
```jsx
<Foo hello={"what's up"} />
```

**Output:**
```jsx
<Foo hello={"what's up"} />;

```

**Expected behavior:**
```jsx
<Foo hello="what's up" />;
```

For the record, eslint-plugin-react's `react/jsx-curly-brace-presence` [rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md) is able to do this (with rewriting).

I don't totally understand the context around why Prettier has decided not to, but as a casual user of both Prettier and ESLint it seems weird that only one of those tools is able to perform this fix, and unfortunately it's not the tool that is typically wired up to format-on-save.

**Comment by fisker** [comment]
Same thing, we don't change ``const foo = `bar` `` to `const foo = "bar"`.

**Comment by thorn0** [comment]
Please see #3303

**Comment by jrr** [comment]
So I guess the attitude on this hasn't changed in the last three years. For me and for future searchers, could you explain why Prettier doesn't want to do this?

What circumstances led to this decision, and could those circumstances foreseeably change in the future?

Is it _harder_ for Prettier than it is for ESLint?

My goal is for this transform to apply without me having to think about it, just like Prettier's others. As a workaround, does anyone know of a way to apply both Prettier's and ESLint's formatting in one format-on-save operation in VS Code?

**Comment by thorn0** [comment]
It's out of scope for Prettier.
See https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about
