### ISSUE TITLE
Markdown Should preserve internal spacing in inline code according to the CommonMark spec

### ISSUE THREAD

**Issue by DingoEatingFuzz** [prettier/prettier#9308]
See [CommonMark spec (example 337)](https://spec.commonmark.org/0.29/#example-337)

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADAygBwIZgJZQDmABMQM4AWEArgDYAmpxARnE8ZgE5xlycBuceqgA6UMQEkoxXJE71sUMGxgRiMCmwDaAYQgBbfdACy2TgGtymOGGIAKOAA9s+zLTYBmDwHYAlAF07ChgYTDIkAHoIsmswADpIQ2h9M3M4iE5CCIAGOIAmAE4IgGInFzc4AFovPxAAGhAITBg8aDJkUDNOCAB3AAUzBHaUbFoe7ABPdobmTlxzOBgsXAJCZBhOajgGuH1WenohABlFQmpsQjgAMQyUkNXkEGxqVXqQYP1aAHUKPHgY3BwdBDP54fh-CaPMBkaYgAi8TgwPpzQgpZAAM1GvAaACsyI4AEJzMALJYuOBHAhwDFY7YgPGOdCrdwARWoEHgNNo2JAOE4CMeKQs9F6UDeXAIMC+eHoGmQAA5sg0uBBeF85phHlweHxBG8AI7s+DIprDJ5kSpQOBCIRvbiGvDcZEXNFITHcum8fR4dabT3MuBsjnUt20howbDMaWyijIPLhuZ4WirPSGbCPHgAVje1F4ABVI8N3Tz+FspIdYOgwJw8M0AIJQejoGATdxc3gAXw7QA)
```sh
--parser markdown
```

**Input:**
```markdown
`Spacing  should   be    preserved`

In accordance to the [CommonMark spec (example 337)](https://spec.commonmark.org/0.29/#example-337)
```

**Output:**
```markdown
`Spacing should be preserved`

In accordance to the [CommonMark spec (example 337)](https://spec.commonmark.org/0.29/#example-337)

```

**Expected behavior:**
```markdown
`Spacing  should   be    preserved`

In accordance to the [CommonMark spec (example 337)](https://spec.commonmark.org/0.29/#example-337)
```

This also impacts Markdown derivatives such as MDX.

**Comment by thorn0** [comment]
Closing in favor of #13485 (even though this one is older, there is some discussion in that one)
