### ISSUE TITLE
Prettier removing backslashes unnecessarily.

### ISSUE THREAD

**Issue by giddyuptiger** [prettier/prettier#9312]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAHAThAVnMMDOAEgCoCyAMgAQDUAvADpSXMusDkAPAEYCuMM0SgEsAJgxBsajVjMoZsuGADkAhgFs4UprJZt6ISiJUwVAWjAAbIQhjjJ1aTuaXrsVRq1Pmeg5ZX58cXkcPHw4C0UuGCh8fUpoFzAAa3EwiLwABUwQmAAKGAALIXwAOlEAGkpC4pKAczgYAEF+dCFeeFz7Ryd9eno2IxNzKxs+n08vNgBKKYBufQA+Lu0nYMV3TQcVnX0OAHp2gSgFuK2vSk5DwVE7CdXsxQBpOABPEqTXu51xhKtk8RE4QacCyCjw+SKpVEU16IAWAA19ldjtx0Et5lA9nswDx0OgbJQAO4QdBJFSYHhQESVMD44yaABu5MYTPQhmMKgAwiNYJRaJR9AMOcNXDAfBj7mCCCQKDQGNtZJc+EdhGJBV9ZGs8BsNTJxoMzC4bLczl4jW51Jtut84n4AkEHqEgXgojE4r8hP99GlFKCchCahUqpC6g1mjBWu04J1dawDdzRbHdDN5nDluctcpLUnmLsDsroCcDKanEr+Nc1RIc3JHTBnm8Pi9qz8oIkUvpARF4H7FAGoSIYSBFoj8+WUVw0WwMViAMpCNRCCzkypQCDCAI8OAlRiZohkKh0RhllUe5IOEA+zK1vuhpr8Np8aO9foGkWjfr6FOCkDlEAQVAwEI0D4MgoDkpghIZOSCAgSgKgWISKgvCBv4TioyQNDOqDoUIUC1MgEabr+cBqFwcAiICIjkCoeE8Co9QAGIkmoxiAXhyAgCofAQD+IAFDAagWAA6kU8D4NhYBwDOMFCIBDKyS8HFgAEvG4WE6AwFk9EscgABm8FhL+WD4AAHgAQug6EfDAM6WuQuFwHpBlwEZplznhEQAIo8BA8BORYhloOS6kcVwKhkRYvEYLhMBCaIhTIAAHAADL+8hhEJlmoBxGBwOpDKOb+ACOPndpgqCwZx+CmFAcDkeRvH4iVQj4lptQ6Ug+kBS5F4kUIBHoERF64bUXmlY5nXOb+JhcHFIgJUgABM02WYuI2chAagdSAeUAKy8TwYTEOFsFdYFDKbgAklSNgzrSQgAY0VIzjALwRP5YQAL6fUAA)

**Input:**

```jsx
// code snippet
projectsHTML +=
          '<button id="' +
          projectName +
          '" data-client="' +
          clientName +
          '" class="projectselectbtns" onclick="selectProject(this.id, this.getAttribute(' +
          "\'data-client\'" +
          '));">' +
          projectName +
          "</button>" +
          '<button id="' +
          projectKey.key +
          '" onclick="deleteProject(this.id)"">X</button><br>';
//current workaround, create var
var dataClient = "'data-client'";
        projectsHTML +=
          '<button id="' +
          projectName +
          '" data-client="' +
          clientName +
          '" class="projectselectbtns" onclick="selectProject(this.id, this.getAttribute(' +
          dataClient +
          '));">' +
          projectName +
          "</button>" +
          '<button id="' +
          projectKey.key +
          '" onclick="deleteProject(this.id)"">X</button><br>';
//Similar, no issue.
projectsHTML +=
'<button onclick+"selectProject(this.getAttibute("\'data-client\'"));"'
```
**Output:**

```jsx
// projectsHTML +=
  '<button id="' +
  projectName +
  '" data-client="' +
  clientName +
  '" class="projectselectbtns" onclick="selectProject(this.id, this.getAttribute(' +
  "'data-client'" +
  '));">' +
  projectName +
  "</button>" +
  '<button id="' +
  projectKey.key +
  '" onclick="deleteProject(this.id)"">X</button><br>';
//current workaround, create var
var dataClient = "'data-client'";
projectsHTML +=
  '<button id="' +
  projectName +
  '" data-client="' +
  clientName +
  '" class="projectselectbtns" onclick="selectProject(this.id, this.getAttribute(' +
  dataClient +
  '));">' +
  projectName +
  "</button>" +
  '<button id="' +
  projectKey.key +
  '" onclick="deleteProject(this.id)"">X</button><br>';
//Similar, no issue.
projectsHTML +=
  '<button onclick+"selectProject(this.getAttibute("\'data-client\'"));"';

```

**Expected behavior:**
I want to escape the single quote (') around the second instance of "data-client" but it removes the backslashes from `"\'data-client\'" +`  and returns `"'data-client'" +`

**Comment by evilebottnawi** [comment]
Because it is unnecessary, what is the problem?

**Comment by kachkaev** [comment]
If your want backslashes in the string itself, it should be `"\\'data-client\\'"` instead of `"\'data-client\'"`.

Otherwise, the removal of backslashes is justified.

**Comment by giddyuptiger** [comment]
Thank you, I tried that and the code does not run. It does work when I run it the way that prettier is “correcting”. I am a new programmer so there could be something I’m missing, but it runs my way, and not prettier’s or your way.

**Comment by evilebottnawi** [comment]
@giddyuptiger Please provide more information

**Comment by giddyuptiger** [comment]
I get this error: "Uncaught SyntaxError: Unexpected identifier" for the line of code in question if I use `'\\'data-client\\''` and then prettier deletes it if I use only one like so: `'\'data-client\''`. So I have to create `var dataClient = "'data-client'"`.

**Comment by evilebottnawi** [comment]
@giddyuptiger Can you create reproducible example, prettier doesn't (should not) break code, we change quotes only when it is safe
