### ISSUE TITLE
TypeScript: `// prettier‑ignore` causes extraneous semicolons in object and interface types

### ISSUE THREAD

**Issue by ExE-Boss** [prettier/prettier#9313]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3xggFEoBzASyjgCYA2BgNQEMAbAVziT2AAdKIJgB6MXgzY4MGDTjYAtDSpQccYaIA8rAHwAKAG5de-VgBo8EDDCIB+fgGFoRxURrQA8rc-EAlEhaMKKseOjwUAAmRHgcPHB49nF4QSIhMGERCDF43NFwAGZ0cFFJeACqBcX0UfG8qcGh4WiRuVDcnJzlAHKdnPWJaaLN2dGxAEYQEJxw7FDlAELTs-ODunqN6aOtOZOqdPjJi6oAkrDr+lsjmS1tsR0AthOKvdzPipebwxlZu+N4EjYOhUcoAZRgwOoX2uvzue2sEwAVnAwEc8F5kajMqYhk0YPQ3NhghI8AAVAAWNFiRDgjxokE40DwVFksSi3AwnAZ7HgUR+AG5hABfPAAXjwxlx-HyAGt1AB3KCBPDzACe4s2QnSYgAVHgaI8uXhdWIRUKoCALCAbPJoERkKB2NhsBAFQAFZ0IB0oLgK9hqh3WibYdhgWWyMEYMMg5CQ3jWukvKJRUoAGXmVG47FZADEcI9efJqMgQOxuGQrSAKTBHpwAOpU+BEaNgOBg700eRGLtq0tgIhBkB0Wm4d2hqiF5CFLi061IohoRah8OR9iPOBpkrT2dweeLsEg2YARW4EHgO84c5A0ewo9LMDVGDgRDAwNsVekh3rNCiMApyAABwAAzWtIEC0vWoYYKW0gvoobhVgAjme8DjjYPplkQSj0KUpRVjIKE0DI445lOSAzlee4gLS9JxtgCY0UecCnuecCXteMDsBMP5-gBSAACzWpC7A0Ny1AuI85GoEQACsVbcLSZLcT68bUUYvDnKmsBgm+NC2AAgtEEJqrMHFwMKwpAA)
```sh
# Options:
--parser typescript
```

## Input:
```ts
export const toEngine262Value: {
	// prettier-ignore
	<V>(value: V, opts?: ConversionOptions):
		V extends Value ? V :
		V extends undefined ? UndefinedValue :
		V extends null ? NullValue :
		V extends boolean ? BooleanValue<V> :
		V extends bigint ? BigIntValue<V> :
		V extends number ? NumberValue<V> :
		V extends string ? StringValue<V> :
		V extends object ? ObjectValue :
		never
	// This semicolon gets duplicated:
	;
} = (value: unknown): any => {
	/* impl */
};
```

## Output:
```ts
export const toEngine262Value: {
	// prettier-ignore
	<V>(value: V, opts?: ConversionOptions):
		V extends Value ? V :
		V extends undefined ? UndefinedValue :
		V extends null ? NullValue :
		V extends boolean ? BooleanValue<V> :
		V extends bigint ? BigIntValue<V> :
		V extends number ? NumberValue<V> :
		V extends string ? StringValue<V> :
		V extends object ? ObjectValue :
		never
	// This semicolon gets duplicated:
	;;
} = (value: unknown): any => {
	/* impl */
};
```

## Expected behaviour:
```ts
export const toEngine262Value: {
	// prettier-ignore
	<V>(value: V, opts?: ConversionOptions):
		V extends Value ? V :
		V extends undefined ? UndefinedValue :
		V extends null ? NullValue :
		V extends boolean ? BooleanValue<V> :
		V extends bigint ? BigIntValue<V> :
		V extends number ? NumberValue<V> :
		V extends string ? StringValue<V> :
		V extends object ? ObjectValue :
		never
	// This semicolon gets duplicated:
	;
} = (value: unknown): any => {
	/* impl */
};
```

**Comment by thorn0** [comment]
A simplified example (note that the output can't be parsed by TypeScript!):

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDJngA6UmmA9KZgA4BOGMAlnNQLT0DmUEtRJARnmADcRAL7CoIADQgIlBtADOyUNmrUIAdwAKqhEpTZUG7AE8l03tWxgA1hgDKla-ShtkMagFc40uAFteOAATIOCAGWxXT2w2OAAxLj9sGAZXZBBsTxgIKRAACxg-VAB1PPp4BScwOHs9cvoAN3KTdLAFcxAXBSYYLSs2JOQAM0Nu6QArBQAPACErWwdsPzgwlzhh0Z8QSan7FzZ0AEVPCHgN1DGQJ2pu6nSYE0o4BTBqejlcmhcYYvogmDyyAAHAAGaQ0CDdYpWSjpGjPJgNdbSACOJ3gfVk+gyCmYUDgwWCuVoaPotD6MUGSBGFy23T89HcXjp+yO6PW1M20hg2F4v3+gKQACZuVZ6Kh9gBhCB+KkgZ4AVlynm6ABVefoaZcGt4AJJQUKweyvd4wACCBvsD3Q526IhEQA)
```sh
--parser typescript
```

**Input:**
```tsx
let a: {
  // prettier-ignore
  b: c;
};

```

**Output:**
```tsx
let a: {
  // prettier-ignore
  b: c;;
};

```
