### ISSUE TITLE
Prettier word-wrap's can break cross-reference links in Doxygen markdown

### ISSUE THREAD

**Issue by ssokolow** [prettier/prettier#9317]
Doxygen's syntax for internal cross-references is `\ref anchor` or `@ref anchor`. To specify custom link text in a markdown-format page, one valid form is `[text](@ref anchor)` or `[text](\ref anchor)`.

When `--prose-wrap always` is specified, Prettier doesn't understand that spaces inside the URL portion of Markdown link markup need to be an exception.

Doxygen has no problem with a bare `@ref anchor` or `@ref anchor "Custom Title"` being split across two lines in this way but, if it sees a line break within the URL portion of `[link](URL)`, it treats the whole thing as literal text, resulting in a means for Prettier to cause silent breakages.

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFgSwM4AIe4CGu2C8UYcuA7pjOkbgDaZRVMIDm9u9hMuALaEA1nDz0q6AJ4AHOACcWUEbgDa2GAsIATHRwC6ACgACCuADNcAI0IKAlAB1Y6dq3Zce1iAFcoOu2l8KFwAKx9NXlcaBWhOGkJpADoQABoQCFkYTGhsZFA7WOoABTsEPJRCJmpEvPTrbTAxGABlWUIwVk5kLR84dLhBazg9EYAZQihOH0JOOAAxCAVhGGyp5BBCHxgINJB0GEEmAHUseGx2yhbyukwANzppDbBsOpBWUgUYYu1OYWQLFVSOlQtgAB4AIUazRahEEcDG7gBQP6IFBYJaXQ4AEUfBB4MimMCQO0FJ8NsIFCIdBBqFA9rIFKwYMdMDp6MgABwABnSjIgpGO2lkGyqNWkbwAjnj4D9MhVNtgALRsEYjPbmaWYcw-Wb-JCAomo0iCTA9BR9dLYLFwXH4uCE4kwQjWVns9DIABM6S0hEwyk4AGEIIJ9SBxABWPYROCoF0VQ3Eu59ACS-jILTATKyAEF-C0YNIOI64ABfUtAA)
```sh
--parser markdown
--prose-wrap always
```

**Input:**
```markdown
This is a sentence with a line length that makes the hyperlink [straddle](@ref bar)
the line length boundary in just the wrong way.
```

**Output:**
```markdown
This is a sentence with a line length that makes the hyperlink [straddle](@ref
bar) the line length boundary in just the wrong way.

```

...which results in Doxygen-rendered output like this

> This is a sentence with a line length that makes the hyperlink [straddle](
> [Title of The Page With Anchor `bar`](#)) the line length boundary in just the wrong way.

**Expected behavior:**
```markdown
This is a sentence with a line length that makes the hyperlink
[straddle](@ref bar) the line length boundary in just the wrong way.
```

...resulting in Doxygen-rendered output like this

> This is a sentence with a line length that makes the hyperlink
> [straddle](#) the line length boundary in just the wrong way.

**Comment by evilebottnawi** [comment]
I want to close this issue in favor doxygen https://github.com/prettier/prettier/issues/9348#issuecomment-705470523, again, please open new issue for supporting oxygen, we don't want to implement new options
