### ISSUE TITLE
Unstable comment before array in assignement

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#932]
Likely going to have the same fix as https://github.com/prettier/prettier/issues/916

```js
const commands = // Commands
[
  {
    a: 1
  },
]
```

```js
const commands = [ // Commands
  {
    a: 1
  }
];
```

```js
const commands = [
  // Commands
  {
    a: 1
  }
];
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20commands%20%3D%20%2F%2F%20Commands%5Cn%5B%5Cn%20%20%7B%5Cn%20%20%20%20a%3A%201%5Cn%20%20%7D%2C%5Cn%5D%5Cn%5Cnconst%20commands%20%3D%20%5B%20%2F%2F%20Commands%5Cn%20%20%7B%5Cn%20%20%20%20a%3A%201%5Cn%20%20%7D%5Cn%5D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by duailibe** [comment]
Also happens with objects:

`let obj = // Comment
    {
  key: 'val'
}

let obj = { // Comment
  key: 'val'
}`

Looks like in the first case comment is added as trailing comment of the variable. In the second case, it is added as leading comment of the first element/property. I have no idea how to fix it though :-)
