### ISSUE TITLE
Prettier lacks an option to preserve the semantic distinction between single and double backticks in Doxygen Markdown

### ISSUE THREAD

**Issue by ssokolow** [prettier/prettier#9323]
Prettier currently normalizes code spans to single-backtick form.

However, [Doxygen](https://www.doxygen.nl/)'s markdown renderer interprets single-backtick markup in a less spec-compliant way for legacy compatibility.

Here are the relevant passages from the [Doxygen documentation](https://www.doxygen.nl/manual/markdown.html#md_codespan):

> ### code spans
> To show a literal backtick or single quote inside a code span use double backticks, i.e.
>
>     To assign the output of command `ls` to `var` use ``var=`ls```.
> 
>     To assign the text 'text' to `var` use ``var='text'``.
> 
> See section [Code Spans Limits](https://www.doxygen.nl/manual/markdown.html#mddox_code_spans) for more info how doxygen handles code spans slightly different than standard Markdown.

> ### Code Spans Limits
> Note that unlike standard Markdown, doxygen leaves the following untouched.
> 
>     A `cool' word in a `nice' sentence.
> 
> In other words; a single quote cancels the special treatment of a code span wrapped in a pair of backtick characters. This extra restriction was added for backward compatibility reasons.
> 
> In case you want to have single quotes inside a code span, don't use one backtick but two backticks around the code span.

The rules for where the single quote and space have to be in relation to each other to force the backticks to be interpreted literally are actually a bit fiddly, but this example snippet of C (one of the main languages Doxygen is used to document) elicits the problem:

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADVYAWBDATgAgGcAHbMOfAXnwHJaBudAHShABoQJiYBLaQ5KDy4IAdwAKeBAJTYANqOwBPARwBGuMgGs4MAMqkwPKAHNkMXAFc4HOAFs1cACZPnAGWynL2E3ABiELh22DC8psgg2JYwEOwgmDB2cgDqmDzwJGRwetLpPABu6UoRYISqIMaEcLgw4pomwcgAZvJVHABWhAAeAEKaYDr62HZwbsZwza02IJ1desYmcnAAipYQ8JNybSCkuFW4EcG4Wk5irBzEuMYwyTxOMJjIABwADBciVcmaxBGXcPv5CYcACOa3gdS4MkihAAtFA4M5nHFcHBQTwUXUfI0kC0ttMqnYeOYrPiFktVusJjiphwYNg1Ld7o8kAAmWmaHhyBYAYQgdmxIH+AFY4pYqgAVekyXHbfLWACSUFcsD0YCu3AAgkq9DAlEtNlUAL6GoA)
```sh
--parser markdown
```

**Input:**
```markdown
``char space = ' ';``

```

**Output:**
```markdown
`char space = ' ';`

```

**Expected behavior:**

To avoid making destructive modifications to Doxygen-rendered markdown, there needs to be an option to pass double-backtick code spans through without conversion to single-backtick form.

**Comment by evilebottnawi** [comment]
I want to close this issue in favor doxygen https://github.com/prettier/prettier/issues/9348#issuecomment-705470523, again, please open new issue for supporting oxygen, we don't want to implement new options
