### ISSUE TITLE
TypeScript: "comment not printed" between MethodDefinition and its semicolon

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#9324]
Same thing happens with `TSAbstractMethodDefinition`.

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGYQQCMOwAOlDjgEboBOAFAJQ4D0AVDejDu6wNwUAviAA0ICAAcYAS2iZkoenQgB3AAr0EClOlSr0ATwXjqddGADWcGAGVJFmVADmyGHQCuccXAC21OAATQKCAGXQXD3RnOAAxCDpfblkXZBB0DxgIMRAACxhfVAB1XJl4TAcwOFttMpkANzLDNLBsHKdMODoYdXNnJOQ8PU7xACtMAA8AIXMrG1t0XzhQpzhB4e8QcYnbJ2dUOABFDwh4ddQRkAc6Tro0mENJOEwwOhlpHMk32CKZQJhcsgABwABnEXwgnSK5kkaS+zy69TW4gAjid4L0pDp0pgALRQOBBII5OhwNEyUm9aIDJBDC6bTq+GRuTwMvYHY6nNa0jbiGDoai-f6ApAAJj55hkqD2AGEIL4aSBngBWHIeToAFQFOjpl3qXgAklAQrBbK93jAAILG2wPA7nTpCIRAA)
```sh
--parser typescript
```

**Input:**
```tsx
class foo1 {
  bar() /* bat */;
}
```

**Output:**
```tsx
Error: Comment "bat" was not printed. Please report this error!
    at https://prettier.io/lib/standalone.js:15:106002
    at Array.forEach (<anonymous>)
    at Object.ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:15:105970)
    at Xi (https://prettier.io/lib/standalone.js:15:111682)
    at Yi (https://prettier.io/lib/standalone.js:15:113795)
    at formatWithCursor (https://prettier.io/lib/standalone.js:15:113915)
    at https://prettier.io/lib/standalone.js:15:386874
    at Object.format (https://prettier.io/lib/standalone.js:15:386957)
    at formatCode (https://prettier.io/worker.js:115:21)
    at handleMessage (https://prettier.io/worker.js:66:18)
```

**Comment by sosukesuzuki** [comment]
Does not happen with `--parser=babel-ts`.

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGYQQCMOwAOlDjgEboBOAFAJQ4D0AVDejDu6wNwUAviAA0ICAAcYAS2iZkoenQgB3AAr0EClOlSr0ATwXjqddGADWcGAGVJFmVADmyGHQCuccXAC21OAATQKCAGXQXD3RnOAAxCDpfblkXZBB0DxgIMRAACxhfVAB1XJl4TAcwOFttMpkANzLDNLBsHKdMODoYdXNnJOQ8PU7xACtMAA8AIXMrG1t0XzhQpzhB4e8QcYnbJ2dUOABFDwh4ddQRkAc6Tro02gDUAFoYEyu6JxgimUCYXOQABwABnEkhUnSK5kkaTBcFu9TW4gAjid4L0pDp0pgnlA4EEgjk6HAUTIib1ogMkEMLptOr4ZG5PLS9gdjqc1lSNuIYOhqN9fv8kAAmbnmGSoPYAYQgvkpIDhAFYch5OgAVXk6amXepeACSUBCsFsYA+0gAggbbDBDAdzp0hEIgA)
```sh
--parser babel-ts
```

**Input:**
```tsx
class foo1 {
  bar() /* bat */;
}
```

**Output:**
```tsx
class foo1 {
  bar /* bat */();
}

```
