### ISSUE TITLE
Basic C++ code makes the parser think there's an expected ";" missing.

### ISSUE THREAD

**Issue by Vodkacannon** [prettier/prettier#9328]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiAllMAbArgEzgB50IBnGAJzgEMBbAPgB0pMYACOmzACgEpgLdu2oxclKOwAMAbhYBfEABoQEAA4xSUMslA1KlCAHcACvoQ6UNbEZoBPHSoBGlGmADWcGAGU1bzADmyFS4cCpwdE5w+IT4ADI0UAG4NAFwAGIQlFwwmknIIDS4MBDKIAAWMHTYAOrl6PBkfmBw3hYN6ABuDXYFYGSOIJhkcJQwJq4BXMgAZtYjKgBWZAAeAEKuHl7e9HBxmHCz82EgyyvegdhwAIq4EPBH2AsgfpQjlAVONFHYZWqUbBq6HwMHKyAAHFIVP9yHAaq41AV-nB3p1DioAI53eATdSWQpkAC0UDg0WiZWoWPQ1AmqWmSDmTxOIzo6GClFCKjIlxu2MODOOKhg3yBILBSAATELXOhsIEAMIQOj0kAogCsZVwIwAKt9LIznp1QgBJKCEWDeMAAjQAQTN3hgdiujxG8nkQA)
```sh
--parser babel
```

**Input:**
```jsx
#include<iostream>
int main(){
  return 0;
}
```

**Output:**
```jsx
SyntaxError: Unexpected token, expected ";" (2:5)
  1 | #include<iostream>
> 2 | int main(){
    |     ^
  3 |   return 0;
  4 | }
```

**Expected behavior:**
I expect the parser to find no errors with the syntax.

**Comment by sosukesuzuki** [comment]
We don't support C++. You can implement a plugin that supports C++. https://prettier.io/docs/en/plugins.html
