### ISSUE TITLE
Unstable comment with return function comment on its own line

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#933]
Note that if you put it on the same line, it works well.

```js
this.getAttribute(name, defaultValue, function(/*string*/ s)
  /*string*/ {
  console.log()
});
```

```js
this.getAttribute(name, defaultValue, function(/*string*/ s) {
/*string*/
  console.log();
});
```

```js
this.getAttribute(name, defaultValue, function(/*string*/ s) {
  /*string*/
  console.log();
});
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22this.getAttribute(name%2C%20defaultValue%2C%20function(%2F*string*%2F%20s)%5Cn%20%20%2F*string*%2F%20%7B%5Cn%20%20console.log()%5Cn%7D)%3B%5Cn%5Cnthis.getAttribute(name%2C%20defaultValue%2C%20function(%2F*string*%2F%20s)%20%7B%5Cn%2F*string*%2F%5Cn%20%20console.log()%3B%5Cn%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
and this one

**Comment by vinhlh** [comment]
@vjeux, so the desired output should be:
```js
this.getAttribute(name, defaultValue, function(/*string*/ s) /*string*/ {
  console.log();
});
```
right?

**Comment by vjeux** [comment]
Ideally yes, but I'm not really attached to a particular output. The main concern here is that when you print twice, it outputs two different versions.
