### ISSUE TITLE
JavaScript: Unstable formatting for prettier-ignore and class extends

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#9335]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGYQQ5wAe8UAJrgDpQ44D0DOADgE5wwwCWcbAtNwDmUCB1r08OYAF9aIADQgILHtEzJQ6NmwgB3AAraEGlOlR70ATw1KARm3RgA1pwDKLJ9yhDkMNgCucEpwALZ2cBQUkQAy6D4B6EJwAGJioehc3r5mATAQiiAAFjChqADqRdzwmJ5gcG4m1dwAbtVWyODYhd6YfDAGjkIZyHjmfUoAVpgkAEKOLu7ooXAx3nCj48Eg0yRu2ahwAIoBEPCbqBMgnmx9bJ126BGohezeMOXcFDBFyAAcAAYlOwIH1yo4WJ12HA7i0NkoAI6neCDFSmEBYfhQOCRSKFDhI7gcQZJEZIMaXbZ9ULcPyBKkHY7IjbkrZKGBPT7fX5IABM7Mc3FQ2QAwhBQmSQDCAKyFAJ9AAqT1MFKuLSCAElKAgYG4wGxuKoAIKUNwwKyHC59GQyIA)
```sh
--parser babel
```

**Input:**
```tsx
class foo extends 
  // prettier-ignore
  f {}

```

**Output:**
```tsx
class foo
  // prettier-ignore
  extends // prettier-ignore
  f {}

```

**Second Output:**
```tsx
class foo // prettier-ignore
  // prettier-ignore
  extends // prettier-ignore
  f {}

```

**Third Output...:**
```tsx
class foo // prettier-ignore // prettier-ignore
  // prettier-ignore
  extends // prettier-ignore
  f {}

```

**Expected behavior:**

Same as input

```tsx
class foo extends 
  // prettier-ignore
  f {}

```

**Comment by fisker** [comment]
Same as https://github.com/prettier/prettier/issues/9877#issuecomment-1441305062

This already fixed by https://github.com/prettier/prettier/pull/10666
I'm going to add test in https://github.com/prettier/prettier/pull/14406
