### ISSUE TITLE
Flow error: Required module not found

### ISSUE THREAD

**Issue by montogeek** [prettier/prettier#934]
Hi!

After install prettier on my project, some Flow errors appeared:
```bash
node_modules/prettier/node_modules/jest-validate/src/__tests__/fixtures/jestConfig.js:135
135: const format = (value: string) => require('pretty-format')(value, {min: true});
                                       ^^^^^^^^^^^^^^^^^^^^^^^^ pretty-format. Required module not found

node_modules/prettier/node_modules/jest-validate/src/errors.js:17
 17: const {getType} = require('jest-matcher-utils');
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ jest-matcher-utils. Required module not found

node_modules/prettier/node_modules/jest-validate/src/utils.js:22
 22:     : require('pretty-format')(value, {min: true});
           ^^^^^^^^^^^^^^^^^^^^^^^^ pretty-format. Required module not found
```

My .flowconfig file:
```yaml
[include]
src/*

[ignore]
.*/dist/.*
.*/build/.*

[options]
module.system=node

[libs]
decls/
```

I am using `prettier` like this:
```
"lint-staged": {
    "*.js": [
      "flow",
      "prettier --single-quote --print-width=90 --write '{src,test}/**/*.js'",
      "git add",
      "jest --bail --findRelatedTests"
    ]
  }
```

Flow version 0.41.0
Prettier version 0.21.0
Jest version 19.0.2

**Comment by vjeux** [comment]
Hey! Without looking at your codebase, it's hard to know what is happening. Could you try to investigate on your end what changed and what is causing those errors?

Then, if you find the root cause, we can address it inside of prettier.

**Comment by montogeek** [comment]
@vjeux It was probably a incorrect yarn installation or something else, couldn't reproduce it again

**Comment by vjeux** [comment]
Great, I'm glad that your problem has been solved!

**Comment by admmasters** [comment]
I'm now also getting this error - pretty much the same config as @montogeek blew away node_modules and installed. I'm not sure this isn't a flow issue but its complaining about required modules not being found but they are present within node_modules - although not explicitly in the root package.json.

The errors I'm getting are:
`node_modules/prettier/node_modules/jest-validate/src/__tests__/fixtures/jestConfig.js:135
135: const format = (value: string) => require('pretty-format')(value, {min: true});
                                       ^^^^^^^^^^^^^^^^^^^^^^^^ pretty-format. Required module not found

node_modules/prettier/node_modules/jest-validate/src/errors.js:17
 17: const {getType} = require('jest-matcher-utils');
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ jest-matcher-utils. Required module not found

node_modules/prettier/node_modules/jest-validate/src/utils.js:22
 22:     : require('pretty-format')(value, {min: true});
           ^^^^^^^^^^^^^^^^^^^^^^^^ pretty-format. Required module not found`

Happy to dig in further if needed.

**Comment by montogeek** [comment]
I forgot to comment, the error went away because I ignored prettier module

**Comment by montogeek** [comment]
It is also so weird, because I have Jest as well, Jest uses `jest-matcher-utils`, but Flow dont say anything about it

**Comment by athomann** [comment]
Coworker ran into this issue and solved it by upgrading his yarn version.
