### ISSUE TITLE
Add option to force explicitly numbered lists in Markdown

### ISSUE THREAD

**Issue by ssokolow** [prettier/prettier#9348]
I'd like to request an option to have Prettier normalize ordered/numbered lists in Markdown to explicitly numbered form (ie. 1234 rather than "1111, let the renderer figure it out")

Aside from this being nicer to read in source form when format-on-save is removing the drudgework of maintaining it, there *is* a semantic concern too:

One of Doxygen's legacy compatibility affordances is to [not support implicitly numbered lists](https://www.doxygen.nl/manual/markdown.html#mddox_lists).

Doxygen interprets this...

```md
1. Foo
2. Bar

1. Baz
1. Quux
```

...as this:

<blockquote>
<ol>
<li>Foo</li>
<li>Bar</li>
</ol>

<ol>
<li>Baz</li>
</ol>

<ol>
<li>Quux</li>
</ol>
</blockquote>

(That is, it requires numbers within any given list to be strictly ascending.)

**Comment by evilebottnawi** [comment]
Sorry, no, please read https://prettier.io/docs/en/option-philosophy.html, we don't support doxygen, especial legacy, if you need to support doxygen please open a new issue

**Comment by ssokolow** [comment]
I'm not asking for "doxygen support".

I'm asking for an option to make Prettier *more* opinionated in a direction which **happens** to also avoid a flaw in Doxygen.

**Whether it's Doxygen, GitHub Pages, or any other consumer of Markdown,** I want to be able to forcibly normalize numbered lists to "1, 2, 3" instead of "1, 1, 1".

**Comment by thorn0** [comment]
Prettier already almost does that. If the first two items have different numbers, Prettier will renumber the items. Isn't this enough for your use cases?

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgGIQgHSgGYsAhAQwCdCNMKAvGrARQFdWAPEAGhAgAcYAS2gBnZKCqUIAdwAKVBOJTkAbhCEATHiABGlcmADWcGAGV+hoVADmyGJVZxecALa64mzZ4Ay5W6zkNnC4lK7kMMK2yCDkrDAQOgAWMK4ANgDqSULwopZgcGZKOUKqOQCeMWCi4rzWonCUMHIGNuHIAGbkaQ28AFaiHKQGxqZm5K5wPtZwnd29IAMcZtY2aXBsEPBzPc4glpQNlDHhlEaaslA6-JTWMBlaMEnIABwADLw3EA0ZBvwxNzgR1Us14AEdWFs4C0BMpYqIALRQOCeTw6ShwCFCDEtILtJBdXa8BquIT2Rx7USrdabbYE+Z7GDkXQPTRPZAAJl4DnIQjSqwAwhBXPiQFBoKCQKwGgAVZnKQkLVROACSUG8sDMYFuggAguqzDByusdg0AL5moA)
```sh
--arrow-parens avoid
--parser markdown
--trailing-comma none
```

**Input:**
```markdown
1. Foo
3. Bar
1. Baz
1. Quux
```

**Output:**
```markdown
1. Foo
2. Bar
3. Baz
4. Quux

```

**Comment by ssokolow** [comment]
> Isn't this enough for your use cases?

No. I want this effect:

**Input:**

```md
1. Foo
1. Bar
1. Baz
1. Quux
```

Output:

```md
1. Foo
2. Bar
3. Baz
4. Quux
```

**Comment by evilebottnawi** [comment]
Change on

```
1. Foo
2. Bar
1. Baz
1. Quux
```

and run prettier, you can setup `remark-link` to linting this problem

**Comment by evilebottnawi** [comment]
We never support doxygen and don't want to implement new options for this, if you need to support doxygen, please open new issue and describe your problems

**Comment by kachkaev** [comment]
Both `1. 2. 3. 4.` and `1. 1. 1. 1.` are valid outputs for Prettier for a reason. Natural sequencing is beginner-friendly while a consistent `1.` is more efficient as it makes diffs smaller when editing lists.

If you need an opinion from a tooling on this, I'd suggest using [Markdownlint](https://github.com/DavidAnson/markdownlint) in addition to Prettier (just as we use ESLint with Prettier in JS). Example repo: https://github.com/kachkaev/njt (see package.json scripts and config files in the root dir).
