### ISSUE TITLE
Ugly line breaks for variable declarations with JSDoc type comment 

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#9358]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCeIBGAhgE6YC8mA9AFQ2YACMAngA5ybACCJJRzAOgA8uPAOK9xRaTIBeAPgC+mGlUwAKUYWklis2QEl4AWzSYAPuZx4AlAG4AOlEhQM1-BIrU6jFu048fIIi+FKSxDLSCsqqGloRukT6RnCmmADU7vZOLm5a2mSUtPRMbBzcvPzCWmEkUpFJSipqmh46eoYmZpZZmAD87phImBJ2IAA0IBCsMACW6MigpCQQAO4ACqQIaMggRAA2q-w7kwR8YADWcDAAyqxEYLNQAObIMCQArnCTqQRwACb-AEAGSILw+RGecAAYhASMYiDA5i9dkQPjAIBMQAALGDGfYAdWxs3gaHuYDgN22JNmADcScxdmA0CcQE80HASDB1nxngjkNgDhzJgArNAADwAQucrrciMY4MCnnABULviAxeKbk9nvs4ABFD4QeCq-bCkD3Egcki7Yh-fZY1gkJ4wAmzf4wbHIAAcAAZJk6IByCXxWLsnXBrbSVZMAI5G+A86Y7FBENAAWigcABAKxJDg8dm+Z5kP5SEFZvVHOMszenyrOr1huNKvLasmMCIBDdHq9SAATB2+LN9jqAMIQYxlkCRgCsWI+HIAKl2UxXzbSvgYoEDYDcwM6ZlwdzcWHrTRzFIogA)
```sh
--parser babel
```

**Input:**
```jsx
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems || foo);
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems + foo);
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems || foo) ? foo : bar;

```

**Output:**
```jsx
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems ||
  foo);
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems +
  foo);
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems ||
  foo)
  ? foo
  : bar;

```

***Expected:**

```jsx
const foooobar =
  /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems || foo);
const foooobar =
  /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems + foo);
const foooobar =
  /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems || foo)
    ? foo
    : bar;

```

**Comment by brodybits** [comment]
Wouldn't it be ideal to rework this kind of code in this manner:

```js
/** @type {Array.<fooo.barr.baaaaaaz>} */
const foooobar = this.foobarItems || [];
```

**Comment by sosukesuzuki** [comment]
I think that's overkill. For example in Google Closure Compiler, [typing to a variable](https://github.com/google/closure-compiler/wiki/Annotating-Types#variable-declarations) and [typecasting to a value](https://github.com/google/closure-compiler/wiki/Annotating-Types#type-casts) are two different things. Also, I don't think Prettier should format in a way that changes the AST.

**Comment by thorn0** [comment]
related: https://github.com/prettier/prettier/issues/8045
