### ISSUE TITLE
Option to disable printWidth on specific lines based on regex

### ISSUE THREAD

**Issue by stefaanMLB** [prettier/prettier#9362]
This feature has been requested and turned down before ([#3468](https://github.com/prettier/prettier/issues/3468)), but I want to insist.

I would like to be able to make a exceptions to the printWidth setting for certain lines based on a regex.

**The rationale is this**
I have a lot of logging instructions in my code.  Because I use Winston with json logging, these instuctions can be long depending on the length of the message and the amount of metadata.
Prettier will usually split the logging instructions up into 2 to 4 different lines.
Since I have lots of logging, this looks messy - the split up logging instructions can take up as much as 30% of the vertical space.

When I review the code, I want to know there is a logging instruction but I seldomly need to review it.  It would be great if the whole instruction is on one line.  For those lines I don't mind how long they are.

Inserting `//prettier-ignore` comments makes the code even more cluttered.

**Comment by evilebottnawi** [comment]
No options, sorry, please read https://prettier.io/docs/en/option-philosophy.html, you can increase `printWidth` for some files using `overrides` (https://prettier.io/docs/en/configuration.html)

**Comment by stefaanMLB** [comment]
This I stop using Prettier.
Also sorry

**Comment by thorn0** [comment]
> Inserting //prettier-ignore comments makes the code even more cluttered.

Add it to the end of the line where your logging instruction is. You wrote you don't look there.

**Comment by stefaanMLB** [comment]
That actually works.  Thanks !
