### ISSUE TITLE
stroustrup code style

### ISSUE THREAD

**Issue by cybermerlin** [prettier/prettier#9363]
I'm sorry, but I can't find how can I reconfigure this plugin with typescript and eslint to allow Stroustrup code style.
Can u help me with this situation?

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

**Comment by thorn0** [comment]
You can't, and this is by design as this style isn't common for JS/TS. See also https://prettier.io/docs/en/option-philosophy.html

**Comment by cybermerlin** [comment]
oh, very bad, this philosophy is wrong. For js and for ts exactly should use the Stroustrup code style first (with some modifications).
