### ISSUE TITLE
JSON Lines files cause parse error

### ISSUE THREAD

**Issue by aphedges** [prettier/prettier#9364]
**Environments:**

- Prettier Version: 2.1.2
- Running Prettier via: CLI
- Runtime: Installed via Homebrew, uses NodeJS 14.13.1
- Operating System: macOS 10.15.7

**Steps to reproduce:**

Run the following in an empty directory:

```bash
echo "Lorem ipsum" >good.txt
echo '{"type": "t/f", "head": "England", "relation": "invaded", "tail": "United States"}' >bad.jsonl
echo '{"type": "t/f", "head": "England", "relation": "attacked", "tail": "Baltimore"}' >>bad.jsonl
prettier --check .
```

**Expected behavior:**

Both `good.txt` and `bad.jsonl` should be ignored by Prettier because they are not supported formats.

**Actual behavior:**

`good.txt` is ignored as it is supposed to be, but `bad.jsonl` causes the following error:

```console
[error] bad.jsonl: SyntaxError: Unexpected token (2:1)
[error]   1 | {"type": "t/f", "head": "England", "relation": "invaded", "tail": "United States"}
[error] > 2 | {"type": "t/f", "head": "England", "relation": "attacked", "tail": "Baltimore"}
[error]     | ^
[error]   3 | 
```

I see two possible resolutions to this issue:

1. Ignore [JSON Lines](https://jsonlines.org/) files the same way Prettier ignores plaintext, Python, and other files. These files are not valid JSON, so they should not be parsed as JSON.
1. Support JSON Lines files, but I'm not going to ask Prettier to support an additional file format.

**Comment by fisker** [comment]
We need  exclude `.jsonl` from  https://github.com/prettier/prettier/blob/53008ffefb5f2d8a3de286cc123bca3ad6d6c57f/src/language-js/index.js#L55

**Comment by AlexKing2289** [comment]
> We need exclude `.jsonl` from
> 
> https://github.com/prettier/prettier/blob/53008ffefb5f2d8a3de286cc123bca3ad6d6c57f/src/language-js/index.js#L55-L60
