### ISSUE TITLE
A discussion on changing the default value for trailingComma in Prettier 3.0 and/or TypeScript

### ISSUE THREAD

**Issue by Zamiell** [prettier/prettier#9369]
Related to: #68 (Enforce Trailing Commas by Default)

Apologies if I missed any other previous discussion; I tried to go through and read any past threads on the topic.

In the [Prettier 2.0 release notes blog post](https://prettier.io/blog/2020/03/21/2.0.0.html), Georgii Dolzhykov explains how Prettier decided to change the default value for the `trailingComma` option from `none` to `es5`.

Georgii links [this excellent blog post from Nik Graf](https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8) as justification for this change. In short, trailing commas result in:
* cleaner diffs
* easier code-manipulations

Looking over the relevant issues (#6888, #6910, and #6963), this did not seem to be a controversial change. And indeed, I think it can be said that this was a sensible and a welcome change for Prettier.

While the `es5` default is a step in the right direction, it still results in missing commas for e.g. the final argument in a function call (and perhaps other some places, not 100% sure). Obviously, programmers are going to want commas after function arguments for the exact same reasons that they would want commas after array elements - all of the points that Nik Graf raises in his blog would equally apply to both situations.

In a previous issue on the topic (I can't remember exactly which one), lydell smartly mentions that IE11 does not support trailing commas in function args, and that IE11 is the final release of a major browser. Since IE11 still has some adoption, lydell argues that it would be inappropriate for Prettier code to not work with IE11 out of the box. That seems sensible and I don't think that most people would argue with that.

However, IE11 usage will fade over time. lydell mentions in issue #68 that the default value **will change** from `es5` to `all` "some day", which is fantastic news. One goal of starting this discussion is to try and narrow down "some day" to something more specific. 2 years? 4 years? Would changing the default in Prettier 3.0 be too early?

---

In the meantime, it strikes me that having to support IE11 is not something that should be applicable to TypeScript code, since any ".ts" file would obviously have to be transpiled by the TypeScript compiler before it would ever hit IE11.

At the risk of sounding heretical, I'll ask: what if Prettier had a trailingComma default value of `es5` specifically for JavaScript files, and a default value of `all` for all other languages? (Or, similarly, a trailingComma default value of `all` for TypeScript, and `es5` for all other languages, whichever is better.)

Cons:

* Admittedly, doing this would compilate the tool; are there any other settings that function like this? I suspect not.
* Similarly, it would make the documentation for the trailingComma section a bit wonky.
* Doing this goes against the spirit of the tool to be as simple as possible.

Pros:

* On the other hand, having trailing commas after function arguments would clearly provide value to the TypeScript users of Prettier, for all of the reasons described in Nik Graf's blog.
* Many users of Prettier are now getting comfortable with trailing commas (since the introduction of it in Prettier 2.0). However, it is a bit weird/annoying that some places have trailing commas and other places do not.
* Georgii Dolzhykov, Simon Lydell, and the other members of the Prettier team seem to already acknowledge and agree with the benefits of trailing commas.
* Another thing to note is that such a feature would only be a **short-term** aberration. In the long-term, when Prettier stops caring about IE11, the global default would change to `all` and all remnants of the split would be cleaned up and forgotten.

I acknowledge that any change in a default value would probably only belong in a major version bump (correct me if I am wrong). So consider this a proposal for Prettier 3.0 *if* the global default will not change to `all` at that time.

In closing, thanks for the excellent formatter.

**Comment by kachkaev** [comment]
The point about little value of `es5` in TypeScript is a valid. That said, varying default value based on the language can make things more complicated for end user, so I’m not sure we should do it.

[According to Microsoft](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666), they are already in the process of dropping IE11 support in their own apps, and according to https://death-to-ie11.com (unofficial source), the extended support will end in 2025.

I can imagine that there is still a small proportion of Prettier users, who simply install the tool as the editor extension and edit their IE11-compatible files without any transpilation. Not sure how big that community is and how painful it would be for them to configure Prettier so that it does not produce broken code.

If we have data to confirm that the volume of hand-written code for IE11 is marginally small, we can probably release v3 with `trailingComma: all` in the next few months. Otherwise, we can at least wait till August 2021, which is the planned mainstream support for IE11. Perhaps, that will have to be Prettier 4 if any [other breaking changes](https://github.com/prettier/prettier/milestone/14) are released earlier.

See also: #6198

**Comment by Zamiell** [comment]
@kachkaev August 2021 has come and gone, is there any news of a new Prettier release?

I am looking forward to removing the `.prettierrc.js` file in all of my repositories.

**Comment by kachkaev** [comment]
@Zamiell see https://github.com/prettier/prettier/issues/11465 🙂

**Comment by Zamiell** [comment]
@kachkaev That issue contains a PR from fisker on Sep 9, 2021, and it has still not yet been merged.
It has been almost 5 months now, and we are still waiting for the trailing comma update.
Can you shed any more light when this PR will be accepted and/or when a new version of Prettier will be released with this change?

**Comment by kachkaev** [comment]
You can track v3 progress here: https://github.com/prettier/prettier/milestone/14 I don’t think there is any ETA yet.

In the meantime, you can enable `"trailingComma": "all"` [via the configuration file](https://prettier.io/docs/en/configuration.html).

**Comment by nickmccurdy** [comment]
Can we close this in favor of #11465? I see no reason not to switch to `"trailingComma": "all"` by default now that Internet Explorer support has officially ended.

**Comment by Zamiell** [comment]
Sure, I'll close.
