### ISSUE TITLE
Function expressions in statement position need parentheses

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#937]
E.g. the parentheses are necessary in

```js
(function(){} && 0);
```

I'll work on this one. Looks like there's existing infrastructure (`firstInStatement`); it's just not consistently applied. (In fact it's not applied under any conditions at the moment.) @vjeux (or whoever), thoughts on doing it similarly to #921 v.s. using the existing `firstInStatement`?

**Comment by vjeux** [comment]
That looks like a good idea. firstInStatement is a leftover from recast fyi
