### ISSUE TITLE
How to prevent HTML closing tag's ">" character being placed on a new line? 

### ISSUE THREAD

**Issue by preeteshjain** [prettier/prettier#9381]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWW0OnPPX2McddtNenVjyG9UEHKLHicNaTPEAnCAFd4SgLRyoAazJh8AZyMBeYiAAeATwBemw3hNk8AIzAPjRi2RgRzIAD0ABYQGHAWhAASYXCogSrqcFo6ugqKlIFy6Yqo2ewZymoa2jR6Bl4BNvaOzm4etd4gvv4WgVgQRjBNhAAKnd3xiSWpOTLx+YK5gZJjnIEiBULxi1MUK9xLmavrC5tQ8Zi4BHCEIAA0IBBYMDTQRsigeEoqAO69zwgPKHg4r3jWB6XVxKPBgXRwGAAZSwYLKAHNkDAlKo4Jc4BhXHAqFRsQAZPBQeGqPDwuAAMQgSgwBFuROQIDw6ggFxAwRgGBwAHVgjR4EZYWA4FCvnz6HzrAywCZWWUjMkYL1QfCacgAGa-eWXABWRksACFQeDIVC8OE8WU4OrNWiQLrLFCETg4ABFVQQeDWnBakCwpTypQMuio1lYJRlGBcmhUGDBZAADgADJcw504FzQVgGWG4AG6FbLgBHd3wJXXb6MoyaKBwbHY1lKODFmiNpWk1VIDXe23yjA0JEontO10lq2dm2XGBuKMxuNIABMk9BNB08IAwmEOyBcwBWVmqeUAFTc3y7PuDcAAklBcbAoWBwzcAII3qEwazOr3ygC+36AA)

```sh
--parser vue
```

**Input:**

```vue
<template>
  <div>
    <div>
      <div>
        <div>
          <div>
            <ol>
              <li>
                <router-link class="xyz-class abc-class" to="/home">Home</router-link>
              </li>
              <li>
                <router-link class="xyz-class abc-class" to="/posts">Posts</router-link>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
```

**Output:**

```vue
<template>
  <div>
    <div>
      <div>
        <div>
          <div>
            <ol>
              <li>
                <router-link class="xyz-class abc-class" to="/home"
                  >Home</router-link
                >
              </li>
              <li>
                <router-link class="xyz-class abc-class" to="/posts"
                  >Posts</router-link
                >
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
```

**Expected behavior:**

Any of these would be fine and neater in my opinion.

```vue
<template>
  <div>
    <div>
      <div>
        <div>
          <div>
            <ol>
              <li>
                <router-link class="xyz-class abc-class" to="/home">
                  Home
                </router-link>
              </li>
              <li>
                <router-link class="xyz-class abc-class" to="/posts">
                  Posts
                </router-link>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
```

OR

```vue
<template>
  <div>
    <div>
      <div>
        <div>
          <div>
            <ol>
              <li>
                <router-link
                  class="xyz-class abc-class"
                  to="/home"
                >Home</router-link>
              </li>
              <li>
                <router-link
                  class="xyz-class abc-class"
                  to="/posts"
                >Posts</router-link>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
```

***

Am I missing some option here that I can disable/enable to prevent this? If so, please guide.

Apologies if this is a repost, I searched everywhere but couldn't find any solutions to this.

Thanks! 🙏

**Comment by thorn0** [comment]
This is by design. It's unsafe to add whitespace around "Home". If you don't care about whitespace safety, use `--html-whitespace-sensitivity ignore`. You can read more on that here: https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting

**Comment by preeteshjain** [comment]
@thorn0 Thanks a lot that solves the problem for now.

Although I'd add that if it is unsafe to add whitespace around "Home" why not format it like this:

```vue
<router-link
  class="xyz-class abc-class"
  to="/home"
>Home</router-link>
```

I mean it is certainly better than

```vue
<router-link class="xyz-class abc-class" to="/home"
  >Home</router-link
>
```

**Comment by thorn0** [comment]
Yes,  there is #7153 open about this. You have a point, the problem is this formatting is okay only in simple cases like in your example. With nested tags, it quickly gets unclear what is nested in what:
```html
<router-link
  class="xyz-class abc-class"
  to="/home"
><another-nested-element
  class="xyz-class abc-class"
  bla="foo"
>Home</another-nested-element></router-link>
```
Whereas currently Prettier uses indentation to show the hierarchy. And it's not the only problem, see #7153.

So what's needed is a conditional solution that would detect when it's okay to use the proposed formatting. It's not an easy problem though. If someone dares to tackle it, I'll be glad to review the PR.

Other related issues: #8302, #5464

**Comment by preeteshjain** [comment]
Got it. It is indeed a hard problem to solve, given that there can be so many edge cases for the HTML code.

**Comment by hanjc1993** [comment]
unfortunately，the example by @thorn0 is not in line with the actual situation. When i format it by VSCode prettier formatter. It goes a stange layout like this: 

```html
<router-link class="xyz-class abc-class" to="/home"
    ><another-nested-element class="xyz-class abc-class" bla="foo"
        >Home</another-nested-element
    ></router-link
>
```
It's obviously a same problem as above by @preeteshjain
