### ISSUE TITLE
No support for hard-private members?

### ISSUE THREAD

**Issue by matiu** [prettier/prettier#9382]
Hi, I am using Prettier v2.1.2, and I am getting:

```
[error] xxx.ts: SyntaxError: Invalid character. (32:3)
[error] > 32 |   #test: string;
```

This is a "hard" private TS member and should be allowed 

https://www.typescriptlang.org/docs/handbook/classes.html#ecmascript-private-fields

Is there planned support for this member types?

thanks

**Comment by kachkaev** [comment]
Hi @matiu! Could you please follow the issue template and produce a playground example as advised?

**Comment by matiu** [comment]
sure, thanks!
