### ISSUE TITLE
Chain functions not breaking into new lines

### ISSUE THREAD

**Issue by calvindio** [prettier/prettier#9388]
```js
// Before Format
Product.findById(prodId).then(product => req.user.addToCart(product)).then(resultA => resultA + 1).then((resultB) => console.log(resultB)).catch(err => console.log(err))

// Expected Behavior
Product
	.findById(prodId)
	.then(product => req.user.addToCart(product))
	.then(resultA => resultA + 1)
	.then((resultB) => console.log(resultB))
	.catch(err => console.log(err))

// Actual Behavior
Product.findById(prodId).then(product => req.user.addToCart(product)).then(resultA => resultA + 1).then((resultB) => console.log(resultB)).catch(err => console.log(err))
```
Previously, long chain functions will be broken up into new lines automatically.
Now it will not break up even though the line is well beyond the 80 (or even 120!) print width limit.
I have to manually press enter for every new chained functions, but the indentation formatting is working fine after manually indenting.
How to restore previous behavior (automatically break up chain functions)?

**Comment by fisker** [comment]
I can't reproduce on Prettier v2.1.2 [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAFAThAJgVzDAOgDMBLKLAIQE8BJLACgAdMs6BKAmACwSZbxgACALwA+QejgBHAjgDOcdAQCGWLABUIAYWXoYfbALYduvSXJwAbGAEER481duCA1IICMJnlHr1H1ijZ7QUgoOQhLOAJLCABzPzgLAOMCMGUYMC56RXRg0PDI6Ljs9HRjAB0oEAAaEAhGGBJoOWRQXUwAd1RdBBaUZUsO5SoW2oAjdGUwAGs4GABlRimyWOQYdBw4WrgAWzG4NQOAGWUoWJxlWLgAMQh0HfTGs+QQZRwYCBqQLhgdywB1LgkeByJZgODzXrAkgAN2BVBeYDkoxAZAUegwlweyCIAwUtQAVnIAB4USYzObzZQ7OBHMhwHF4rYgInE+YrSIARRwEHgjMs+JAS3Q6JeY2U+0sX2YZBg-xIWG4yAAHAAGWrMCAKf6TRgvZiJRQwhm1KQ8+AYep9V5yAC0UDgBwOX0kZpIkkxsWxSFxAuZCh2JDWG39HLg3N5DJ9TNqMAl8sVXGQACZY5MSJYVloIDtvSBEgBWL7yODqCV9X2CmGbGjkBALMDoEgNGzkeYwKiRfkKAC+PaAA)

**Comment by calvindio** [comment]
I don't know, maybe there's something wrong with my vs code. I've uninstalled and reinstalled Prettier extension and double checked the related settings. Maybe there's other extension that messed up with the behavior.
I assume it's not because of the update. I will go tinker with it some more.
Thank you!

**Comment by calvindio** [comment]
```js
// Before Format
const product = new    Product    ({
    title:    title,
    price: price,    description:     description, imageUrl:imageUrl
  })

// Expected Behavior
 const product = new Product({
    title: title,
    price: price,
    description: description,
    imageUrl: imageUrl
  })

// Actual Behavior
 const product = new Product({
    title: title,
    price: price, description: description, imageUrl: imageUrl
  })
```
Prettier formatted the code successfully, but only the inline and refused to modify existing line breaks.

**Comment by fisker** [comment]
It can't be the problem from Prettier, please check your editor settings or find the real problem.
