### ISSUE TITLE
Unstable trailing comment before { of class method

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#939]
```js
class x {
  focus() // do nothing
  {
    // do nothing
  }
}
```

```js
class x {
  focus() { // do nothing
    // do nothing
  }
}
```

```js
class x {
  focus() {
    // do nothing
    // do nothing
  }
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20x%20%7B%5Cn%20%20focus()%20%2F%2F%20do%20nothing%5Cn%20%20%7B%5Cn%20%20%20%20%2F%2F%20do%20nothing%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnclass%20x%20%7B%5Cn%20%20focus()%20%7B%20%2F%2F%20do%20nothing%5Cn%20%20%20%20%2F%2F%20do%20nothing%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
@yamafaktory this one should be easy too

**Comment by yamafaktory** [comment]
@vjeux Ok, I will take a look at it!
