### ISSUE TITLE
Unstable jsx expression

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#940]
```js
<td
onClick={() => {
  a
}}>{header}{showSort}</td>;
```

```js
<td
  onClick={() => {
    a;
  }}
>{header}
{showSort}</td>;
```

```js
<td
  onClick={() => {
    a;
  }}
>
  {header}
  {showSort}
</td>;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Ctd%5CnonClick%3D%7B()%20%3D%3E%20%7B%5Cn%20%20a%5Cn%7D%7D%3E%7Bheader%7D%7BshowSort%7D%3C%2Ftd%3E%3B%5Cn%5Cn%3Ctd%5Cn%20%20onClick%3D%7B()%20%3D%3E%20%7B%5Cn%20%20%20%20a%3B%5Cn%20%20%7D%7D%5Cn%3E%7Bheader%7D%5Cn%7BshowSort%7D%3C%2Ftd%3E%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by rattrayalex** [comment]
Cool; clearly the first should compile directly to the last. 
Happens when the opening element breaks, and the body contains softlines.
Should be breaking everything. 

This might be fairly hard to do without breaking other things..

**Comment by rattrayalex** [comment]
Ah, nope, it was a simple bug.

**Comment by vjeux** [comment]
Yay!
