### ISSUE TITLE
Prettier erasing typed catch

### ISSUE THREAD

**Issue by JeremyLoy** [prettier/prettier#9400]
Cannot reproduce in the playground. As you can see from the below link, everything seems fine.

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAYhBABQCUSAbhDgCb7AA6U++MAFgE4QDu+UOPwCiXHl1IByXhxIAHAM6TyLAL4sWMLgE9GLNsTIqoq-GACGMMB1JwkmANZQ+UcntZnoCiABs4AOjgxCAk4Y1UQABoQCDlcL2RQc2DeAAVkhAVkEHMfXnNtLOiAIy5zMAc4GABlOXKcKABzZC10OGi4AFtiuDo6XoAZcyb0c0a4Yi5Oy1wm7PN0GAgokA4YTp8AdQ4ceAU6sDhqzN2cKl3tbLAFIpAGhSCYVLLG6eRUXIfogCsFAA8AEJlCpVarmTpwAYNODvT7tEC-P7VBqNPwARXQEHgsJ8XxAdS4Dy42Rg2jkcAUYC4ODiKzk1Ngm3onGQAA4AAzRekQB6bMpybL0ilBKgw6IAR0x8GesSyKHMCgAtIJer0Vlw4JKcBrnmM3kgPrj4Q9OjgWlw2tEFCj0VKYQa4dEYOZiky6CykAAmJ1lHA+FEAYQgnX1IApAFYVugHgAVF1yw14qhtACSUH6sGqVJpMAAgunqqS-DiHqpVEA)

For my project however, every time I add `: unknown` to a `catch` clause, prettier erases it.

My prettier config is small

```
{
  "singleQuote": true,
  "bracketSpacing": true,
  "trailingComma": "es5"
}
```

One plausible cause is I am in a Lerna/yarn monorepo.

I execute prettier from the top directory as such.

```
yarn prettier --write .
```

The top level `package.json` has prettier as a dependency.

```
...
"prettier": "^2.1.2"
...
```

My nested project, the one having the issues, has typescript as a dependency, not the top level
```
...
"typescript": "^4.0.2"
...
```

**Comment by evilebottnawi** [comment]
How you run prettier?

**Comment by JeremyLoy** [comment]
yarn prettier --write .

**Comment by evilebottnawi** [comment]
@JeremyLoy I think you use old version of `prettier`, look at lock file try to write `yarn ls prettier`

**Comment by JeremyLoy** [comment]
No, the version is 2.1.2. Checking the version directly from the command line proves this

**Comment by evilebottnawi** [comment]
@JeremyLoy sorry, no magic, we don't remove types in catch, so something wrong with your env, please create reproducible test repo

**Comment by pixelbucket-dev** [comment]
I have the same issue. @JeremyLoy have you found a solution? 

The only way I can fix this is either switching of the `prettier-vscode` plugin or switching of prettier in my setup, e.g. husky pre-commit hook. Or I have to remove `"editor.formatOnSave": true` from the VSCode settings.

This is pretty annoying, since I want to enforce tighter linting rules using `@typescript-eslint/no-implicit-any-catch`.

**Comment by pixelbucket-dev** [comment]
This should have added the feature, but it does not seem to work:

https://prettier.io/blog/2020/08/24/2.1.0.html#type-annotations-on-catch-clauses-8805httpsgithubcomprettierprettierpull8805-by-fiskerhttpsgithubcomfisker

PS:

I think I got it to work by updating prettier to a newer version.
