### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by ajfarkas** [prettier/prettier#9401]
**Environments:**

- Prettier Version: all (running 1.19.1)
- Running Prettier via:Node.js API
- Runtime: Node.js v12.18.3
- Operating System: macOS

**Steps to reproduce:**
1. `npm i prettier@1.18.2`
2. fix errors reported by prettier
3. `npm i prettier@1.19.1`

**Expected behavior:**
Prettier does not report any new errors

**Actual behavior:**
Every file has errors reported.

The issue is that there are breaking changes between minor versions. Every other package I use keeps breaking changes to major versions, so I regularly run updates on all packages. But minor version changes for prettier mean that I have to commit hundreds of lines of changes every time. This means I need a separate PR for prettier updates because it's unfair to ask my collaborators to look at a PR that has that many changes that have nothing to do with the bug or feature I'm working on.

There are also not enough flags to keep these changes from affecting how prettier lints my code. (I can't set defaults and just not worry about changes you push.)

I like the idea of prettier, and you're certainly doing a lot of good work here, but I'm close to dropping it from all of my projects because of all these breaking changes.

**Comment by evilebottnawi** [comment]
Expected. it is formatter and can change output in any versions.
