### ISSUE TITLE
I wrote a pre-commit hook. Any good place to put it?

### ISSUE THREAD

**Issue by llimllib** [prettier/prettier#943]
I'd file a PR with my pre-commit hook to verify that all changed javascript files are formatted properly: https://gist.github.com/llimllib/acca10ef730384ee519631843e4c31b1 , but there doesn't seem to be a sensible place in the repository for it. Any ideas? I think it'd be useful to at least point people to?

Also, it can be MIT licensed, I just put something on there so it said something. I 100% do not care about the license.

**Comment by llimllib** [comment]
btw, thanks so much @vjeux for https://github.com/prettier/prettier/commit/205458a8d12ab39a8ad0bb0e815e017481108f2e

**Comment by vjeux** [comment]
Since it's super small, I think it would make sense to just put it as a blockquote in the README under a git hook section

**Comment by llimllib** [comment]
Oh, I just noticed you added the husky/lint-staged stuff to the README. I think this is simpler? I'll submit the PR but no shame if you close it, you already have a solution to this.

**Comment by vjeux** [comment]
We may want to add both options if people don't/can't use husky/lint-staged. It's nice to know that you can add 6 lines to your commit hook to get it instead of having to add a dependency.
