### ISSUE TITLE
Same configuration but different output format

### ISSUE THREAD

**Issue by lizhuang93** [prettier/prettier#9447]
### .prettierrc
printWidth:120

### input: 
```
location.href = `https://open.weixin.qq.com/connect/oauth2/authorize?appid=${store.state.appid}&redirect_uri=${redirect}&response_type=code&scope=snsapi_userinfo#wechat_redirect`
```
#### computer A: 
```
location.href = `https://open.weixin.qq.com/connect/oauth2/authorize?appid=${
            store.state.appid
          }&redirect_uri=${redirect}&response_type=code&scope=snsapi_userinfo#wechat_redirect`
```
#### computer B:
same as input,why???
```
location.href = `https://open.weixin.qq.com/connect/oauth2/authorize?appid=${store.state.appid}&redirect_uri=${redirect}&response_type=code&scope=snsapi_userinfo#wechat_redirect`
```

**Comment by fisker** [comment]
You must using different version of Prettier, [this behavior is changed in v1.19.0](https://prettier.io/blog/2019/11/09/1.19.0.html#dont-wrap-template-elements-on-lines-shorter-than-printwidth-6284-by-sosukesuzuki)

**Comment by lizhuang93** [comment]
> You must using different version of Prettier, [this behavior is changed in v1.18.0](https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay)
nice, thanks!
