### ISSUE TITLE
Unstable last trailing comment of a switch case

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#945]
```js
switch (token) {
  case TOKEN_TRUE:
    a; // Comment

  case TOKEN_FALSE:
    b;
}
```

```js
switch (token) {
  case TOKEN_TRUE:
    a;
     // Comment
  case TOKEN_FALSE:
    b;
}
```

```js
switch (token) {
  case TOKEN_TRUE:
    a;
  // Comment
  case TOKEN_FALSE:
    b;
}
```

Note that it works correctly if there's no empty line after the comment.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(token)%20%7B%5Cn%20%20case%20TOKEN_TRUE%3A%5Cn%20%20%20%20a%3B%20%2F%2F%20Comment%201%5Cn%5Cn%20%20case%20TOKEN_FALSE%3A%5Cn%20%20%20%20b%3B%5Cn%7D%5Cn%5Cnswitch%20(token)%20%7B%5Cn%20%20case%20TOKEN_TRUE%3A%5Cn%20%20%20%20a%3B%5Cn%20%20%20%20%20%2F%2F%20Comment%201%5Cn%20%20case%20TOKEN_FALSE%3A%5Cn%20%20%20%20b%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by duailibe** [comment]
Looks like I screwed up not writing "fixes" or "closes" in #1136. I think this can be closed :)
