### ISSUE TITLE
prettier JSON formatter does not catch U+200B : ZERO WIDTH SPACE [ZWSP]

### ISSUE THREAD

**Issue by dxc-jbeck** [prettier/prettier#9458]
**Prettier 2.1.2**

Create a JSON file that has this unicode key for "zero width space in it", like this:
```
{​
    "prop":true
}
```
Just after the first `{` character is a hidden character U+200B : ZERO WIDTH SPACE [ZWSP]
You can detect it if you try and move the cursor over the character with the arrow keys
The prettier formatter does not catch this, but the notepad++ plugin: JSON Viewer >> Format Json does

**Expected behavior:**
Prettier would notice that this is invalid JSON because of the ZWSP character

**Comment by thorn0** [comment]
I can't reproduce this. Please use the Playground to demonstrate the problem.
Also please note that Prettier isn't a validator. If it gets invalid code as input, it might still try to format it.
