### ISSUE TITLE
How to disable new line after if or else 

### ISSUE THREAD

**Issue by avatar-lavventura** [prettier/prettier#9460]
`prettier` converts:

```
if <condition>
   revert()
```

into 

```if <condition> revert()```

----------

example:

```
  if(!greeting)            |      if (!greeting) return null;
    return null;           |
```
----

Is it possible to disable this configuration ?

**Comment by thorn0** [comment]
No, it's not possible. Such things are intentionally non-configurable in Prettier.
Please see https://prettier.io/docs/en/option-philosophy.html
Also please use StackOverflow for questions like this. Issue trackers are for development.

**Comment by kachkaev** [comment]
To avoid one-liners, you can add curly braces:

```
if <condition> {
   revert()
}
```

If you are also using ESLint in parallel to Prettier, you can force curly braces via https://eslint.org/docs/rules/curly

**Comment by avatar-lavventura** [comment]
@kachkaev Is it possible to use `ESLint` in other languages that are using prettier as backbone such as [prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity)

**Comment by avatar-lavventura** [comment]
@thorn0 I respect your philosophy. I am just looking for a solution, that's what developers do.

**Comment by kachkaev** [comment]
@avatar-lavventura you can find my personal opinionated example in https://github.com/kachkaev/njt. The repo uses ESLint for JavaScript-y code and Prettier for all supported formats (JS/TS/JSON/Markdown/YAML)

**Comment by avatar-lavventura** [comment]
@thorn0 I am not asking related to configuration ; but I am asking related to change the default, which is not against the philosophy.
