### ISSUE TITLE
--embedded-language-formatting is inconsistent in its formatting

### ISSUE THREAD

**Issue by richiepreece** [prettier/prettier#9466]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAngFQIYHMDqAljABYDKMAToVLgDLFyXYA2ABnRJXKgASEAHAM4BXPgBMILLryHFe2VHBgAaXgBJgS0hHEAKIRCUA1bNWwAjFnACUAXwXjBhIWBq5ecFsQB0vAMIizBbEQZ4w-MJiCp5QhHzYImAwMpqGSj7StD4AbmaEltY+AtikDqW8OcTYcLyoidRCfgCqEYYs3m4wIk5QGlrKJLp69rIirs4wfsaEeajj-OK83rgiLNi8Alww2GpCPAJMnkIRaUOUMKbmVnB2agIkZsrMsjw+bCAqIBACMITQQmQoDMlAgAHcAApPKCAlCsMHYdCAr4WZhgADWyjIJTctGQVBEcC+PAscHE4jJdGwtBEeDgADEuPUYH88SgIAAzDmfEAkGCoFj4EiMIQ4uBkBByP5VGDoZDgITIkA0fYXCHMXD1ZAc1j7L4AKyEAA8AEJozEwMiKOAMKBwbW6okgQ1GsjuawARREEHgDpYepAJUoqvlFksXh5AmosCI4lIyAAHAAGL5RiD7fDMATyqNwVU5e1fACO3vg6p+sJA2CEAFo7WSyTzuCXCNx1XgtUgdf6nftUIR8ZRCV85LRPaX7V3HV8dhZY-GkAAmGfMQjeWj+IydkB5gCsPPGcBwFlh3YDOUJAEkoBTYGQwNRfgBBG8UdDWP37Ox2IA)
```sh
--embedded-language-formatting off
--parser babel
```

**Input:**
```jsx
myTagWithStringLiteral`Lorem ipsum dolor sit amet, ${method(someVariable)} adipiscing elit. Curabitur et ipsum a enim auctor ${some.long.variable.path} at vitae mauris. Ut sollicitudin ${method()} suscipit. Vivamus id ligula porta, semper est ${shortVariable}, pharetra sem.`
```

**Output:**
```jsx
myTagWithStringLiteral`Lorem ipsum dolor sit amet, ${method(
  someVariable
)} adipiscing elit. Curabitur et ipsum a enim auctor ${
  some.long.variable.path
} at vitae mauris. Ut sollicitudin ${method()} suscipit. Vivamus id ligula porta, semper est ${shortVariable}, pharetra sem.`;

```

**Expected behavior:**
Template literals should not be auto-formatted with --embedded-language-formatting is "off". Instead, we're seeing that the "auto" and "off" values have the exact same behavior.

**Comment by sosukesuzuki** [comment]
`--embedded-language-formatting` does not affect all tagged template literals.
It controls the formatting of embedded languages, such as styled-components and GraphQL and more.

```js
// Input
styled.div`a {}`;
gql`type Query {hero: Character}`;

// Output (embedded-language-formatting=auto)
styled.div`
  a {
  }
`;
gql`
  type Query {
    hero: Character
  }
`;

// Output (embedded-language-formatting=off)
styled.div`a {}`;
gql`type Query {hero: Character}`;
```

You might want to use prettier-ignore in your example. see https://prettier.io/docs/en/ignore.html
