### ISSUE TITLE
Ternary operators are not being placed on new line

### ISSUE THREAD

**Issue by g-chance** [prettier/prettier#9481]
I imagine that there may be something I don't understand about the behavior of this extension, but based the other threads I have seen on the topic of formatting ternaries, it appears that the expected behavior should be more in-line with what I posted below. Would appreciate any insight anyone is able to provide as to whether I'm doing something wrong, or if this is in fact unexpected behavior.

Thanks!

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDADrzAXkwAoBKIgPk2AB0pNMAnOGAVyYZPsd8wB4AJgEsAbpR58pwAISRYcAB4wAdGzRwmKgEZNsUQZKnHMAfgEjRmMABtsaNADlsAWziFaIACL2AFtohsJkMQSn5fACZKAHU4G0g3TBgITABVXATNNBkBAHpIiQYTYsZZeXhlNQ0tFgBHNjgMOEEAfV19QyKS7rMBXEoATQgOawgXXH0AT2Y4esasX3tMbTgETBE0PFwmCFFm5en0zKY0TABBQRdhKAAaTFwbOHs4UdhsMBgjHu-+bExfFgAMw8IBc2GENmSSGwl2uAAE2BkxlkVAlPJQYVcoAikW4TqixvxcthqICIExMC5yS9BKxwTY0Coif0vt9jEg+oNhhSEhMoNM6g0MJhhKdcAgRFAAOZpXFZc6wqAAclOZ3wO1E2BsdweTw0o0S2neAGtMHZ4EwcszCmypABfImWG1sjlCMRhXJO1m8WgwO3exiO93esj0O0gG4gCC4GDCdDIUBBHYAdwACkEEGhkCAtcnsJMs5H2mBjawAMoTMDXKXIGBMBqRuAuFaCWmCAAy+ilbGwUrgADFyWCYLHpdnsGxkhGQL4YC4bNFfMJ4GhK3Ay5nl2Jl5Ns2AHNPrtUYKm9FKwchAVqNJGAFZoRQAIT0JfLrjg7eucEv17gd4fZbVo8ACKbAQPAP4Mn+IATCcmjZkaKw2NO2zXDA0TCIIMC+MgAAcAAMkbbBAGjRHouDZtsjSaHs071OBcCntGWYoPYAC0UCrG206CsILCnr2F5IFeUGRhoVy1vW0FoEBcCgQxkE3iAMDYNoGFYThSARJGdb0tWADCYxCSAjQAKzTuocAACqqSxIlKaIDQAJIGAgMBlmATDCDGZwGGWMCTI8ilwHadpAA)
```sh
--parser babel
```

**Input:**
```jsx
const app = () => {
  return (
      <div>
          {!context.user.brand
              ? <div className="Dashboard"><h2>Welcome to Upcomers! </h2>
                  {!context.user.requested_brand
                      ? <p>Your company request has been disapproved by Upcomers Admin, please contact
                          <a href="mailto:admin@upcomers.com">email@email.com</a> for more details.</p>
                      : <p>Your company request is pending Upcomers Admin's Approval, please come back later! </p>
                  }</div>
              : <div></div>
        	}
        </div>
      )
}
```

**Output:**
```jsx
const app = () => {
  return (
    <div>
      {!context.user.brand ? (
        <div className="Dashboard">
          <h2>Welcome to Upcomers! </h2>
          {!context.user.requested_brand ? (
            <p>
              Your company request has been disapproved by Upcomers Admin,
              please contact
              <a href="mailto:admin@upcomers.com">email@email.com</a> for
              more details.
            </p>
          ) : (
            <p>
              Your company request is pending Upcomers Admin's Approval, please
              come back later!{" "}
            </p>
          )}
        </div>
      ) : (
        <div></div>
      )}
    </div>
  );
};

```

**Expected behavior:**
```jsx
const app = () => {
  return (
    <div>
      {!context.user.brand 
        ? (
        <div className="Dashboard">
          <h2>Welcome to Upcomers! </h2>
          {!context.user.requested_brand 
            ? (
            <p>
              Your company request has been disapproved by Upcomers Admin,
              please contact
              <a href="mailto:admin@upcomers.com">email@email.com</a> for
              more details.
            </p>
          ) 
            : (
            <p>
              Your company request is pending Upcomers Admin's Approval, please
              come back later!{" "}
            </p>
          )}
        </div>
      ) 
        : (
        <div></div>
      )}
    </div>
  );
};

**Comment by thorn0** [comment]
This is intentional. See https://prettier.io/docs/en/rationale.html#jsx and #2208.

**Comment by g-chance** [comment]
Thank you for that information thorn0. I was searching for ternary formatting and missed the specifics of formatting JSX.
