### ISSUE TITLE
Inconsistent output of `return assign` between `babel` and `ts`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#9483]
**Prettier 2.1.2**

[TS Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAhgBwBTYNoBOcAzhAK4FhwC6AlAAQC8AfPdsADpT31GkVUkbGAAsAlsQB0fcpThNeJWVVoAaLgF9atEKpARMMMdGLJQ6AgQgB3AAoWEplOgA219AE9TegEYF0YADWcDAAypgBYlAA5sgwBGRwenCoPnAAJukZADLoMWTo0XAAYhAEGDBGMcgg6GQwELogIjCoLgDq4vDEEVShjmJGAG6DHjVgxN4gUcRwBDC2-tEYyABmrrN6AFbEAB4AQv5BIaHoqHDZUXBrG0kgO7uhUdEucACKZBDwNy6bIBEEWYEGowDyYEhgAhiQxNTBQ2DtMTpUTIAAcAAY9HCILN2v5MDU4SQ5kNrnoAI6feCLAxOWrEAC0UDgGQyTSIlLEREWhRWSHWvzus1QYjiCSFz1eHy+135tz0MHQPkRyJEyAATAr-GIXM8AMIQVB8kAkACsTTIswAKkqnAK-kNEgBJKBZWChSHQmAAQVdoVBrx+sw0GiAA)

**Input:**

```ts
map(([resource]) => ({
  resource: (this.resource = resource),
}))
```

**Output:**

```ts
map(([resource]) => ({
  resource: this.resource = resource,
}));
```

**Expected behavior:**

```js
map(([resource]) => ({
  resource: (this.resource = resource),
}));
```

[Babel Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAhgBwBTYNoBOcAzhAK4FhwC6AlAAQC8AfPdsADpT31GkVUkbGAAsAlsQB0fcpThNeJWVVoAaLgF9atEKpARMMMdGLJQ6AgQgB3AAoWEplOgA219AE9TegEYF0YADWcDAAypgBYlAA5sgwBGRwenCoPnAAJukZADLoMWTo0XAAYhAEGDBGMcgg6GQwELogIjCoLgDq4vDEEVShjmJGAG6DHjVgxN4gUcRwBDC2-tEYyABmrrN6AFbEAB4AQv5BIaHoqHDZUXBrG0kgO7uhUdEucACKZBDwNy6bIBEEWYEGo+dBpFxNTAEKIwdpidKiZAADgADHooRBZu1-JgalCSHMhtc9ABHT7wRYGJy1YgAWigcAyGSaRDJYiIi0KKyQ61+d1mqDEcQS-Oerw+X2uPNuehgYLhCJEyAATLL-GIXM8AMIQVDckAkACsTTIswAKmCnLy-kNEgBJKBZWChMDQwwAQUdoRgHleP1mGg0QA)

**Comment by fisker** [comment]
Happens on the new `espree` parser too [playground](https://deploy-preview-9000--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBbAhgBwBTYNoBOcAzhAK4FhwC6AlAAQC8AfPdsADpT31GkVUkbGAAsAlsQB0fcpThNeJWVVoAaLgF9atEKpARMMMdGLJQ6AgQgB3AAoWEplOgA219AE9TegEYF0YADWcDAAypgBYlAA5sgwBGRwenCoPnAAJukZADLoMWTo0XAAYhAEGDBGMcgg6GQwELogIjCoLgDq4vDEEVShjmJGAG6DHjVgxN4gUcRwBDC2-tEYyABmrrN6AFbEAB4AQv5BIaHoqHDZUXBrG0kgO7uhUdEucACKZBDwNy6bIBEEWYEGokTBEa56MFRGDtMTpUTIAAcAAZIVZZu1-JgamCSHMhhCQABHT7wRYGJy1YgAWigcAyGSaRBJYiIi0KKyQ61+d1mqDEcQSvOerw+X2uXNuehg6B8sPhImQACZpf4xC5ngBhCCoTkgEgAViaZFmABVZU5uX8hokAJJQLKwUJgAhiQwAQQdoRgHleP1mGg0QA)
