### ISSUE TITLE
Optimize/Sort Imports

### ISSUE THREAD

**Issue by umidbekkarimov** [prettier/prettier#949]
## Optimize

Will join imports from similar source.
**From**:
```javascript
import {foo} from './tools'
import {bar} from './tools'
```

**To**:
```javascript
import { foo, bar } from './tools';
```

See: [no-duplicate-imports](http://eslint.org/docs/rules/no-duplicate-imports), [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md).

## Sort

Will sort imports by module or filename.

**From**:
```javascript
import _ from 'lodash'
import {bar} from './tools'
import fs from 'fs'
```

**To**:
```javascript
import fs from 'fs';
import _ from 'lodash';
import { bar } from './tools';
```

See: [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md).

Both rules are debateable, so I created one issue.

P.S. inspired by 
1. WebStorm [Optimizing Imports](https://www.jetbrains.com/help/webstorm/2016.3/optimizing-imports.html).
2. WebStorm [Sorting for Imports](https://www.jetbrains.com/webstorm/nextversion/#sorting-for-imports).

**Comment by yamafaktory** [comment]
Related to #767.

**Comment by vjeux** [comment]
With prettier, we do not want to change the AST and instead make it print well a given AST. The idea is to then be able to plugin ast transformers before prettier.

There's been many ideas for those kind of transformers:
- `} else { if () { } }` -> `} else if () { }`
- function -> arrow function
- string concatenation with template literals

This way, we can keep the complexity of pretty printing scoped to this project and people can write the ast transformers (which are orders of magnitude simpler to write) independently.

**Comment by umidbekkarimov** [comment]
@vjeux thanks for explanation! 

I agree that these changes can cause problems from unpredictable side effects that was described here #767 to glitches during "format-on-save" process.

Currently I'm using builtin ide tool, and totally happy with it. Personally, I think If reordering of imports can break your app, you should rewrite your app. But it's just my opinion.

Just wanted to know what prettier community thinks about it.

**Comment by n1ru4l** [comment]
IMHO this can break things that I do.
E.g if your are importing a module thats sets up things which affect the following modules that are loaded.

**Comment by spudly** [comment]
I've seen so many different strategies for sorting imports (alpha, by path, external/internal, etc.) and I think whatever strategy that would get adopted here would be highly controversial.

Seems like this is more of an `eslint --fix` thing than a `prettier` thing, since the rule in the eslint plugin supports tons of options, and because this would actually modify the AST, causing code to execute in a different order (or other issues?).

See benmosher/eslint-plugin-import#711.

**Comment by spudly** [comment]
Also, see https://github.com/AlexJuarez/eslint-plugin-import-order-autofix

**Comment by jlongster** [comment]
Agreed. Closing this as this it out of scope and more of an eslint issue.

**Comment by hlehmann** [comment]
As webstorm as implemented it, such optimisation is relevant/usefull in many case.

Could it be optional in order to avoid side effects issues ?
Also we can use a comment such as `/* no import optimisation */` on files that need to be protected.

**Comment by j-f1** [comment]
@hlehmann We try to avoid adding options for maintainability reasons, and the tools that currently exist to do this seem to work just fine.

**Comment by lydell** [comment]
> the tools that currently exist to do this seem to work just fine.

Which tools are you referring to?

**Comment by j-f1** [comment]
@lydell [`import/order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md).

**Comment by cozmy** [comment]
What about now, when this option is available as a [TypeScript language service](https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/#organize-imports)?

**Comment by j-f1** [comment]
>What about now, when this option is available as a [TypeScript language service](https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/#organize-imports)?

@cozmy I still don’t think we’ll do it, because it could change the code’s behavior.

**Comment by duailibe** [comment]
@cozmy I guess you can let TypeScript do that and just let Prettier format the code.

**Comment by pronebird** [comment]
I don't think it's out of scope. Other formatters for other languages do this and nothing blow up.

**Comment by j-f1** [comment]
Please check out [our option philosophy](https://prettier.io/docs/en/option-philosophy.html) — we don’t want to add too many options. Also, the ESLint rule mentioned above can do the job much more configuably than we can (we would probably pick an order and stick to it).

**Comment by duailibe** [comment]
@pronebird It is out of scope. We try not to change the AST (with some exceptions), otherwise we'd have to keep track of what may change the meaning of the code or not. We think other tools can do that in a much safer way.

I'm locking this since we're not gonna do it.
