### ISSUE TITLE
Unary expressions prevent line break

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [prettier/prettier#9490]
Although printWidth is set to `80` but some times Prettier don't break lines to shorter lines so my linter complains that `This line has a length of X. Maximum allowed is 81. eslint(max-len)` I have seen this issue in lines with long name variables. 

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwqNAtgM4AKJAhmHKwQwAynBi4oAcwA0AXwCU+YAB0o+fJCjsY+aCQCeAJQR041YwEd0OanDrD0AI1Y527PFvwBefAEIW1BzcfAJCouI4UgB0AIKcnADyAJIAcgAqALIAoukA+oZZAGpJWRQA3KrqAPRV+Bk0cPgkkXDsuqgaEKZRPaqyINIgEAAOuNDsyKA81NQQAO6c0wgTKDwkczz6E4OO1HwA1mLCw3yRksgw1OhwgwKOdqZ0ADI8Uug8knAAYmw8EVLIEA8dAwCADEAACxgrBIFAhOHg7BO-FEWgROAAbgj9ICwG5wZF2GYYJw9pJWDxkKg1kTBgArdgADwAQnswIcRDxBE8WlSaTcQAzGcIziQ4ABFdAQeB8ki0kAnahE6iAxw8e4kcHDaiRGAUHB0GAQ5AADgADINtRAiRQ9sNAdrWmYMXBwVZpXBSSMVkD2ABaKBwOx2cG2Kw2T1kimy+VElwXK4C9xSMWSj0xgUwdX6w3GpAAJkGlx4OGaUgAwhBWNGUK0AKzg9BEtLqlbUuUCjHXJJQUywYRgHWjGK94QwfRijOyWRAA)
```sh
--parser babel
```

**options:**
```json
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "embeddedLanguageFormatting": "auto",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false
}
```

**Input:**
```jsx
function HelloWorld({formsPlacementSetting,}) {
  const onlyRenderRequiredSubmissions = !formsPlacementSetting.APPOINTMENT_REVIEW;
  // More lines of code...
}
```

**Output:**
```jsx
function HelloWorld({ formsPlacementSetting }) {
  const onlyRenderRequiredSubmissions = !formsPlacementSetting.APPOINTMENT_REVIEW;
  // More lines of code...
}

```

**Expected behavior:**
```jsx
function HelloWorld({ formsPlacementSetting }) {
  const onlyRenderRequiredSubmissions = 
    !formsPlacementSetting.APPOINTMENT_REVIEW;
  // More lines of code...
}

```

**Comment by ImanMahmoudinasab** [comment]
I checked the same code without `!` character and Prettier formatted the code as expected. So it seems that `!` causes the issue.

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwqNAtgM4AKJAhmHKwQwAynBi4oAcwA0AXwCU+YAB0o+fJCjsY+aCQCeAJQR041YwEd0OanDrD0AI1Y527PFvwBefC2oduPgEhUXEcKQA6AEFOTgB5AEkAOQAVAFkAUVSAfUMMgDUEjIoAblV1AHoK-DSaOHwScLh2XVQNCFMIrtVZEGkQCAAHXGh2ZFAeamoIAHdOSYQxlB4SGZ59Mf7Haj4AazFhQb5wyWQYanQ4foFHO1M6ABkeKXQeSTgAMTYeMKlkEB46BgED6IAAFjBWCQKGCcPB2Ed+KItHCcAA3OH6f5gNyg8LsMwwTg7SSsHjIVArAn9ABW7AAHgAhHZgfYiHiCB5NClUq4gOn04QnEhwACK6Ag8B5JGpICO1AJ1H+jh4txIoMG1HCMAoODoMDByAAHAAGfqaiAEig7Qb-TXNMxouCgqySuDEoZLAHsAC0UDgdjsoNsVhs7pJZOlsoJLjOFz57ikIvFbqjfJgqt1+sNSAATP1zjwcI0pABhCCsSMoZoAVlB6AJKVVS0pMr5aMuCSgplgwjAWuGUW7whg+hFadksiAA)
**Input:**
```jsx
function HelloWorld({formsPlacementSetting,}) {
  const onlyRenderRequiredSubmissions = formsPlacementSetting.APPOINTMENT_REVIEW;
  // More lines of code...
}
```

**Output:**
```jsx
function HelloWorld({ formsPlacementSetting }) {
  const onlyRenderRequiredSubmissions =
    formsPlacementSetting.APPOINTMENT_REVIEW;
  // More lines of code...
}

```

**Comment by fisker** [comment]
It seems all [`UnaryExpression`](https://github.com/estree/estree/blob/master/es5.md#unaryexpression) is not allow to break, 

Add some logic here should be able to fix it. https://github.com/prettier/prettier/blob/de9ff6626fe1330d4c349f191bc70e68d1a935da/src/language-js/printer-estree.js#L5015

**Comment by brodybits** [comment]
This looks similar to the more general issue #2482.
