### ISSUE TITLE
Extra space in for loop parens

### ISSUE THREAD

**Issue by arnarthor** [prettier/prettier#950]
```js
for (let i = 0; i < rowWidth - seats.size;) {
  console.log('Hello');
}
```

turns into

```js
for (let i = 0; i < rowWidth - seats.size; ) {
  console.log("Hello");
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22for%20(let%20i%20%3D%200%3B%20i%20%3C%20rowWidth%20-%20seats.size%3B)%20%7B%5Cn%20%20console.log('Hello')%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

This seems to add an extra space before the closing paren in the for loop due too the semi colon at the back.

**Comment by vjeux** [comment]
Thanks for raising this. The reason it's there is because this is the default way we print things. But I'm not sure if it's a bad choice. It makes it clear that there is no last condition. Any thoughts?

**Comment by yamafaktory** [comment]
IMHO, keeping the extra space makes it clear that the final expression is omitted and as a consequence, this improves the readability.

**Comment by arnarthor** [comment]
Oh wow, sorry. This is code from the codebase at work, I just activated prettier and thought this was strange because ESLint complained. Didn't realise it was missing the third argument to `for`. 

I 100% agree that this is clear and a pretty nice indicator on the missing last argument.

I'll close this

**Comment by meyer** [comment]
@vjeux sorry to bring this issue back from the dead, but I just happened upon this discussion and wanted to give input. It seems like removing the trailing space from a `for` loop if the update portion is missing fits in with how prettier is already doing things (see #169).

Prettier didn’t remove the trailing space from a for loop I just wrote and I assumed it was a bug.
