### ISSUE TITLE
wrong indent and wrap in Vue template

### ISSUE THREAD

**Issue by hanjc1993** [prettier/prettier#9522]
### I have a Vue file like this
![1](https://user-images.githubusercontent.com/33806233/97437651-c228b500-195e-11eb-9f52-627943f1b3fd.png)

### When i format this file by VSCode Prettier Formatter，it goes to a strange layout
![2](https://user-images.githubusercontent.com/33806233/97437955-277ca600-195f-11eb-89c0-b4c77300cfaf.png)

### How can i keep code like the first case with prettier

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

I will reopen it when you fix it
