### ISSUE TITLE
Cannot npm install using npm@7

### ISSUE THREAD

**Issue by asottile** [prettier/prettier#9536]
**Environments:**

- Prettier Version: **1abfe91f27a386e351c7587ab9767546670df797 (current revision of default branch)**
- Running Prettier via: **N/A: can't get it installed**
- Runtime: **nodejs 15.0.1, npm 7.0.3**
- Operating System: **linux**

**Steps to reproduce:**

1. `npm i`

**Expected behavior:**

successfully install

**Actual behavior:**

```console
$ npm --version
7.0.3
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: prettier@2.2.0-dev
npm ERR! Found: remark-parse@8.0.3
npm ERR! node_modules/remark-parse
npm ERR!   remark-parse@"8.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer remark-parse@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from remark-math@1.0.6
npm ERR! node_modules/remark-math
npm ERR!   remark-math@"1.0.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/asottile/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asottile/.npm/_logs/2020-10-29T16_53_08_900Z-debug.log
```

**Comment by Poorva17** [comment]
I am using prettier version 2.1.2, npm version 7.0.3 and node version v15.0.1. 
`npm i` is working for me.

I am facing issue while running prettrier cli. `prettier --write` is failing with ERROR prettier not found. I have opened issue for this #9611 

Might be related to this one so commenting here
