### ISSUE TITLE
Inconsistent formatting of multiline template strings

### ISSUE THREAD

**Issue by isaacl** [prettier/prettier#9546]
In my typescript code I have some multiline template strings.  `getUpcomingClasses` looks correct to me, but in `getUnscheduled`, I don't understand why prettier is moving the starting `` ` `` to a new line, and forcing paren after the closing `` ` `` to a new line.

```ts
export function getUnscheduled(conf: MbConfig) {
  return async (dbClient: ClientBase): Promise<ClassInsert[]> => {
    const res = await dbClient.query<ClassInsert>(
      `
SELECT * FROM CLASSES WHERE
  start_ts > now() AND
  start_ts < now() + interval '${conf.meeting_delay_mins} minutes' AND
  NOT is_cancelled AND
  zoom_account >= 0 AND
  zoom_meeting_id IS NULL`,
    );
    return res.rows;
  };
}

export async function getUpcomingClasses(
  dbClient: ClientBase,
): Promise<ClassRow[]> {
  const res = await dbClient.query<ClassRow>(`
SELECT * FROM CLASSES
WHERE end_ts > now() - interval '15 minutes' AND
  start_ts < now() + interval '24 hours' AND
  NOT is_cancelled
ORDER BY start_ts`);
  return res.rows;
}
```

Prettier 2.1.2.  `.prettierrc`:
```js
{
  trailingComma: 'all',
  singleQuote: true,
}
```

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
