### ISSUE TITLE
Comment get lost

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#9564]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOA9AFRJIlkDUAlpgDIQQDW6AFnOgCZIcAI3ao+UANx0clcjIBm7ABQBKQgF8SWqCTAZs+QjKo05ileuA6NIADQgIABxiNomZKHQAnbxADuAAo+CB4o6Kj+6ACeHg7C3uhgHHAwAMpOSYxQAObIMN4ArnAOcAC2wnD8-FUs6LmF6DlwAGIQ3mXoMK65yCDohTAQ9iDcMGWoAOrcjPCYmWBwaaGzjABus9F9YNgj2Zhw3jCBiTmdyAoRBw4AVpgAHgBCicmpaehlcCzZcBdXJSA7vc0tkcuIAIqFCDwP6oa4gTLeA7ePoKVABEZObzZGCTRj8GDcZAADgADA4sRADpNEk4+li4Mi1r8HABHKHwE7OML9TAAWigcCqVRG3jg7MYYpOTXOSEucIBBzKjHyRUVoIhHN+cv+Dhg6GEeIJRKQACY9YlGKhQQBhCBlWUgRkAVhGhQOABUDWF5fC1sUAJJQGqwNJgbEuPDBtIwaLiWEHDQaIA)
```sh
--parser flow
```

**Input:**
```jsx
class A {
  /*::
  +isLookahead: boolean;
  */
  foo() {}
}

class A {
  /*::*/
  foo() {}
}
```

**Output:**
```jsx
class A {
  +isLookahead: boolean;
  foo() {}
}

class A {
  foo() {}
}

```

**Expected behavior:**

**Comment by thorn0** [comment]
Unfortunately, this isn't solvable in the general case. Flow comments work on the token level, not on the AST level. So we can easily find an infinite amount of bugs like this in Prettier.

<details><summary>Example</summary>

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVEpACAlgM23VWwAoAPASmwGpsBPAbhABoQIAHGXaAZ2VABDAE7CIAdwAKIhPxSCANuMH1+bAEbDBYANZwYAZQ7bcUAObIYwgK5w2cALbq4AExeuAMoPPXBZuABiEMIOgjDc5sgggtYwEKwgABYwDgoA6om48LzGYHAGslm4AG5Z9FFgvGogprxwwjCSWmahyPiKdWwAVrzkAEJauvoGgg5wHqZwbR12ID3kBqZmCnAAitYQ8NMKnSDGwnXCUfgKEgkcwqYwabguMInIABwADGwXEHVpWhxRF3CHxSmbAAjht4E1OHJorwALRQOCuVwJYRwUG4FFNPytJDtHazOoOXCWGz4pYrdabKY4mZsGCCdQ3O4PJAAJlpWlwCiWAGEIA5sSB-gBWBLWOoAFXpclxu2KtgAklB3LADGBLlwAIJKgwwegrbZ1AC+hqAA)
```sh
--parser flow
```

**Input:**
```jsx
/*:: if */ (x) + y;
```

**Output:**
```jsx
if (x) +y;

```

</details>

This requires a fundamentally different solution.

A possible solution:

Prettier doesn't try to preserve these comments at all and just lets the parser parse them like normal code, which happens already for the Flow parser and can be enabled for Babel (#9074). Then, an option (or probably an option value for the `parser` option) controls the printer: the code can be printed either in the "Flow mode", where all the Flow comments are printed uncommented, as normal code, or in the "JS compatibility mode", in which all non-JS constructions are printed as Flow comments. AFAIK there can't be a good reason to mix the two in the same file.

**Comment by thorn0** [comment]
Closing as support for Flow comments was removed in https://github.com/prettier/prettier/pull/13687
Now this output is intended.
