### ISSUE TITLE
Prettier CLI does not work with npm v7 (ERROR: prettier not found)

### ISSUE THREAD

**Issue by Poorva17** [prettier/prettier#9611]
**Environments:**

- Prettier Version: 2.1.2
- Running Prettier via: CLI
- Runtime: 
   Node.js v15: v15.0.1
   NPM v7: 7.0.3
- Operating System:  macOS

**Steps to reproduce:**

We have added following in the `Scripts` section of `package.json`:
```"fix:prettier": "prettier --write --config ./.prettierrc './**/*.{ts,tsx}' "```
1. `npm run fix:prettier`

**Expected behavior:**
Executes successfully 

**Actual behavior:**
```sh: 1: prettier: not found
npm ERR! code 127
npm ERR! path <path-for-project>
npm ERR! command failed
npm ERR! command sh -c prettier --write --config ./.prettierrc './**/*.{ts,tsx}' 
```

**NOTE** - **This flow is working as expected with npm version 6.14.8 and node version v14.14.0. We have started facing this issue with upgrade of npm version to 7.x**

**Comment by thorn0** [comment]
What happens if you run the command (`prettier --write --config ./.prettierrc './**/*.{ts,tsx}'`) directly, not via `npm run fix:prettier`?

**Comment by Waxolunist** [comment]
My current workaround is

```
"postinstall": "ln -sf ../prettier/bin-prettier.js `npm bin`/prettier"
```

The same happened to lit-analyzer. https://github.com/runem/lit-analyzer/issues/147

**Comment by thorn0** [comment]
Please provide steps to reproduce the issue. Everything works as expected for me on Linux, Node 15.2.0, npm 7.0.8.

**Comment by Waxolunist** [comment]
Mac OS, node 15, npm 7.08
Install prettier

```
npm install --save-dev prettier
```

```
ls -la `npm  bin` | grep prettier
```

No output

**Comment by Waxolunist** [comment]
Same happens for me on ubuntu 18

**Comment by Waxolunist** [comment]
I tested now on a new empty project and it worked. Seems, that there is another problem on my project with another package. It works on my project with node 14 and npm 6

Sorry, you can close this issue

**Comment by thorn0** [comment]
This sounds quite unusual. How exactly that other package can affect the installation of Prettier?

Also it'd be good to get an answer from @Poorva17 to compare your situations.

**Comment by Waxolunist** [comment]
When I remove node_modules and do a `npm i` the post install scripts are not executed.

This looks then as follows on ubuntu:
node 15 / npm 7

```
/opt/hostedtoolcache/node/15.2.0/x64/bin/npm install

added 1483 packages, and audited 1483 packages in 40s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Finishing: npm install
```

node 14 / npm 6

```

> pre-commit@1.2.2 install /home/vsts/work/1/s/node_modules/pre-commit
> node install.js


> core-js@2.6.11 postinstall /home/vsts/work/1/s/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-bundle@3.6.5 postinstall /home/vsts/work/1/s/node_modules/core-js-bundle
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /home/vsts/work/1/s/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> spawn-sync@1.0.15 postinstall /home/vsts/work/1/s/node_modules/spawn-sync
> node postinstall


> cypress@5.6.0 postinstall /home/vsts/work/1/s/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 5.6.0)

25l[09:44:46]  Downloading Cypress     [started]
[09:44:49]  Downloading Cypress     [completed]
[09:44:49]  Unzipping Cypress       [started]
[09:45:00]  Unzipping Cypress       [completed]
[09:45:00]  Finishing Installation  [started]
[09:45:00]  Finishing Installation  [completed]
25h
You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

25hadded 1482 packages from 1201 contributors and audited 1488 packages in 45.582s

59 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

Finishing: npm install
```

I suppressed first the output of npm install, because that usually works and found the issue in the check stage, which suddenly crashed with `command not found`.

**Comment by thorn0** [comment]
I still don't see why you didn't have `` `npm bin`/prettier``.

**Comment by Waxolunist** [comment]
Me neither. But I know now that this is definitely not a prettier bug. So sorry again for opening an issue here.
It's a npm 7 behavior I don't have figured out right now. I have read some other users complaining about issues with npm 7.
If you are still interested, it happens in my playground project https://github.com/Waxolunist/paint2
