### ISSUE TITLE
jsxBracketSameLine not working in prettier 2.1.2 version 

### ISSUE THREAD

**Issue by girishgalla** [prettier/prettier#9612]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAtgTwLSXQB2gRgAIwAbAQwGdqBeAHRAHcwATbAM3LgA9sAjCTYBLSuQgBzXNHixqJVh2pgAThHLlsANziqYIsOKYkA2pwgQAuoxAAjSqqYA+BlFQB6LDIJFYzkAAaEAh8A2hqZFBHdWYABUcESJRKbQgRNiD7VUowAGs4GABlfFyRKElkGFUAVzhguHQ7ODY2FoAZSgqaykk4ADEIVXRKGAMK5BBKGpgILIALGHRyAHV5kXhqUrA4IqSNkW0NzEmwWizy6j0YOJzJEeROcSvggCtqXgAhHPzCosp0HB2uU4I9nvUQO9eEVypIeABFGoQeBg8gvEClVRXVSTLqSGpUHHBfCqcowFYZGDzZAADgADMT1FcVjl8JMSXBsbosgBHJHwW6hZJTajYKBwFotLKqOB8kQy269B5IJ5oiFXdAiKq1dWwhH80Eq8HBGCUOwUthU5AAFhNORE5FhAGEIOhlSAoEQsjUrgAVM3JVXo7R1ACSUDasCKahEYQAghGijBMDxUVcAL7poA)
```sh
--arrow-parens avoid
--jsx-bracket-same-line
--parser angular
--tab-width 4
--trailing-comma none
```

**Input:**
```html
<my-component class="wcd-flex-1 dialog-contents wcd-scroll-vertical" [foo]="bar">
</my-component>
```

**Output:**
```html
<my-component
    class="wcd-flex-1 dialog-contents wcd-scroll-vertical"
    [foo]="bar"
>
</my-component>

```

**Expected behavior:**
```html
<my-component
    class="wcd-flex-1 dialog-contents wcd-scroll-vertical"
    [foo]="bar">
</my-component>

**Comment by lydell** [comment]
The jsxBracketSameLine is for JSX, but you seem to be formatting Angular templates?

**Comment by girishgalla** [comment]
sorry my default formating command is pointing to .ts files now i changed it to html then it is fixed
