### ISSUE TITLE
Support for literal file paths claimed but doesn't work

### ISSUE THREAD

**Issue by okonet** [prettier/prettier#9618]
This is a follow up issue for https://github.com/prettier/prettier/issues/6344 and https://github.com/okonet/lint-staged/issues/676

We've attempted to fix the issue several times in lint-staged, but we could not make it in a generalized way meaning every time we would fix this prettier behavior we would break other CLI tools on different platforms. 

We believe that this should be resolved in the Prettier repository. 

cc @iiroj

**Environments:**

- Prettier Version: 2.1.2
- Running Prettier via: Node.js API (lint-staged) and CLI (same result)
- Runtime: Node.js v14
- Operating System: macOS

**Steps to reproduce:**

```shell
➜ touch \[slug\].tsx
➜ prettier [slug].tsx                 
zsh: no matches found: [slug].tsx
```

**Expected behavior:**

As per https://prettier.io/docs/en/cli.html#file-patterns

> Given a list of paths/patterns, the Prettier CLI first treats every entry in it as a literal path.

so I'd expect it to treat the file as a literal path.

**Actual behavior:**

It's not treating it as a literal path.

**Comment by evilebottnawi** [comment]
Because it is glob, you should use `\[slug\].tsx`

**Comment by fisker** [comment]
Does `prettier "[slug].tsx"` work?

**Comment by okonet** [comment]
https://prettier.io/blog/2020/03/21/2.0.0.html#test-whether-passed-globs-are-names-of-existing-files-before-treating-them-as-globs-7587httpsgithubcomprettierprettierpull7587-by-fiskerhttpsgithubcomfisker says

> Since file names in Linux can contain almost any characters, strings like foo*.js and [bar].css are valid file names.
> Previously, if the user needed to format a file named [bar].css, a glob escaping syntax had to be used: prettier "\[bar].css" (this one doesn't work on Windows, where backslashes are treated as path separators)
> Now, when Prettier CLI gets a glob, it first tries to resolve it as a literal file name.

**Comment by fisker** [comment]
There are quotes in that changelog

**Comment by okonet** [comment]
Interestingly enough, it might have been fixed in v2 indeed as I cannot reproduce this with lint-staged anymore (but I just did so I'm re-testing).

**Comment by okonet** [comment]
Okay it might have been a mistake on my side (or cache?) but with v2 I can run `prettier --write` from lint-staged without any troubles anymore. Sorry for the noise! Closing.

**Comment by iiroj** [comment]
I have some tests in this repo using prettier 2.1.2 through [execa](https://github.com/sindresorhus/execa), and I can't get them to work: https://github.com/iiroj/path-escape-research/blob/master/execa.test.js

Please note that the jest tests expect failures, and failing jests mean that they failed differently than the snapshots.
