### ISSUE TITLE
Space lost when comment on preceding line

### ISSUE THREAD

**Issue by karl** [prettier/prettier#964]
Input:
```javascript
const foo = {
  /* Section A */
  a: 'a' /* comment for this line */,

  /* Section B */
  b: 'b',

  /* Section C */
  c: 'c',
};
```

Output:
```javascript
const foo = {
  /* Section A */
  a: "a" /* comment for this line */,
  /* Section B */
  b: "b",

  /* Section C */
  c: "c"
};
```

Expected:
```javascript
const foo = {
  /* Section A */
  a: "a" /* comment for this line */,

  /* Section B */
  b: "b",

  /* Section C */
  c: "c"
};
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20boo%20%3D%20%7B%5Cn%20%20%2F*%20Section%20A%20*%2F%5Cn%20%20a%3A%20'a'%20%2F*%20comment%20for%20this%20line%20*%2F%2C%5Cn%5Cn%20%20%2F*%20Section%20B%20*%2F%5Cn%20%20b%3A%20'b'%2C%5Cn%5Cn%20%20%2F*%20Section%20C%20*%2F%5Cn%20%20c%3A%20'c'%2C%5Cn%7D%3B%5Cn%5Cnconst%20yay%20%3D%20%7B%5Cn%20%20%2F*%20Section%20A%20*%2F%5Cn%20%20a%3A%20'a'%2C%5Cn%5Cn%20%20%2F*%20Section%20B%20*%2F%5Cn%20%20b%3A%20'b'%2C%5Cn%5Cn%20%20%2F*%20Section%20C%20*%2F%5Cn%20%20c%3A%20'c'%2C%5Cn%7D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Good catch!

**Comment by vjeux** [comment]
Interestingly, if you put the inline comment after the comma, the space is correctly preserved.

```js
const foo = {
  /* Section A */
  a: 'a', /* comment for this line */

  /* Section B */
  b: 'b',

  /* Section C */
  c: 'c',
};
```

outputs

```js
const foo = {
  /* Section A */
  a: "a" /* comment for this line */,

  /* Section B */
  b: "b",

  /* Section C */
  c: "c"
};
```
