### ISSUE TITLE
"prettier.singleQuote": true is broken on purpose

### ISSUE THREAD

**Issue by olamedia** [prettier/prettier#9644]
I totally dislike the idea of having array of string with mixed double and single quotes when few of them have escaped characters.

Expected behavior is to have additional option to disable "avoid-escape" rule or to have singleQuote: "strict" option.
I will not disable the eslint check by various reasons, I would better avoid using prettier in a future.

current option name should be singleQuoteMayBeYesOrMayBeNotYouDontDecideForUs

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
