### ISSUE TITLE
Import braces are removed when there is no specifiers

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#9645]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwHoAqfSddBA04-AX3wDMcJ18AdEZiCbgNwgANCAiYYqaAGdkoAIY42AdwAKihLJTyANsvkBPWaIBGOeWADWcGAGVMF1FADmyGDgCucUXHQm4ACYBgQAy8i4e8s5wAGK46PIwki7IIPIeMBAiIAAWMOg6AOo5qPDSDmBwtpqlqABupQapYNLGaFDScHiq5s4JyMy6naIAVtIAHgBC5lY2tvLUIU5wA0PeIGPjtk7OOnAAih4Q8Ks6wyAOOJ04qSby-jrZmDhOMIWoATA5yAAcAAyiZ4QTqFcyYVLPODXOorUQARyO8B64i0aWkAFooHBAoFsjg4AjUPielF+khBmd1p10Kg3J4qTs9odjityWtRDB7u9Pt8kAAmDnmVA6HYAYXYZJAUIArNkPJ0ACr3LQU851LwASSgwVgtjALwkAEFtbYYAY9qdOgwGEA)
```sh
--parser babel
```

**Input:**
```jsx
import { /* comment */ } from "foo";
```

**Output:**
```jsx
import /* comment */ "foo";

```

**Expected behavior:**
```jsx
import { /* comment */ } from "foo";
```

**Comment by fisker** [comment]
Known issue #7912 , and didn't finish pr https://github.com/prettier/prettier/pull/8016

**Comment by sosukesuzuki** [comment]
Oh, I didn't know. thank you.
