### ISSUE TITLE
semicolon added as first character to html files on save

### ISSUE THREAD

**Issue by brewster1134** [prettier/prettier#9652]
originally i posted this issue to the [prettier-vscode](https://github.com/prettier/prettier-vscode/issues/1629) repo issues page, but was directed to post it here

in visual studio code, each time i save an html file, prettier adds a semicolon to the left of my html tag `;<html>`. i remove it, save the file, and it is added back.

i have noticed a few things since the original post... the issue comes from the script tag... 

###### these script tags cause the semicolon to be added
```html
;<html>
  <head>
    <!-- both types of closing tags inside the head, cause the issue -->
    <script src=".dist/demo.js"></script>
    <script src=".dist/demo.js" />
  </head>
```

###### these script tags do not
```html
<html>
  <head>
    <!-- using both tag closing types, the semi-colon is not added -->
    <script src=".dist/demo.js" /></script>
  </head>
```

i went through disabling extensions until i found out prettier was causing it, but am unable to change/find any settings that fix the issue. its possible this has been an issue for awhile, but i am just noticing it. is this a known issue, and if so, is there a known fix for it?

**Comment by thorn0** [comment]
Your Prettier is misconfigured and uses the wrong parser for HTML (parses it as JSX).
Please see https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option

**Comment by brewster1134** [comment]
bingo! after tweaking some config, i was able to fix the problem... ty for setting me on the right path
