### ISSUE TITLE
"Comment "xyz" was not printed" error for `require` function call

### ISSUE THREAD

**Issue by gavinpc-mindgrub** [prettier/prettier#9668]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTAJzgEcBXAS2IAoB6AKkwDMIJN7aBKEAGhAgAOMCumSgAhoUIQA7gAVJCNMhDiANjPEBPZXwBGhcWADWcGAGUBRilADmyGITJw+cALZ64AEy-eAMuJ2ZOK2cABiEIRu4jDCdiriZDAQvCAAFjBuagDqaRTwaFZgcOZK+RQAbvlaKmBouiA2aHCEMHKGttHITOrNfABWaNgAQoYmZubibnB+NnDdvS4gg9jmNrZqcACKZBDwC2p9IFaEzYQqeuKeaqkChDYw2RReMGnIABwADHx3EM3ZhgEKjucDOFXmfHIezg7UEyhQ4jQAFooHBvN5UsRyFQYR0ukgeocls03BQHE5ietNjtoQcjjArk8Xm8kAAmPiOcQUNTrADCEDc+JAoIArKkyM0ACpXeGEo4VZwASSgvlg5jA9yEAEEVeYYFpNnS4ABfY1AA)
```sh
--parser babel
```

**Input:**
```js
const x = require(/* foo */)
```

**Output:**
```jsx
ensureAllCommentsPrinted/<@https://prettier.io/lib/standalone.js:15:106002
ensureAllCommentsPrinted@https://prettier.io/lib/standalone.js:15:105970
Xi@https://prettier.io/lib/standalone.js:15:111682
Yi@https://prettier.io/lib/standalone.js:15:113795
formatWithCursor@https://prettier.io/lib/standalone.js:15:113917
Px/<@https://prettier.io/lib/standalone.js:15:386874
format@https://prettier.io/lib/standalone.js:15:386959
formatCode@https://prettier.io/worker.js:124:21
handleMessage@https://prettier.io/worker.js:75:18
self.onmessage@https://prettier.io/worker.js:36:14

```

**Expected behavior:**
No crash, comment is left as-is.

This appears to be related to a special case for the `require` function (perhaps assuming that it will have an argument).  The error doesn't occur for other function names that I tried.

**Comment by fisker** [comment]
`define` the same

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTAEzgDMBLKOACgHoAqTEiCTOmgShABoQIAHGGXTJQAQwBO4iAHcAChIRpkIUQBtpogJ5KeAI3GiwAazgwAyn0MUA5shjiArnB5wAtrriFihADKio1g6i1nAAYhDirqIwggHKog4wENwgABYwrqoA6qlk8GiWYHBminlkAG55mspgaDogFGhw4jCyBtZRyCRqTTwAVmjYAEIGxqZmoq5wPhRwXT3OIAPYZjaqcACKDhDw86q9IJbiTeLKuqIeqil84hQwWWSEMKnIABwADDw3EE1ZBnzKG5wE7lOY8ACO23gbX4ShQojQAFpKJ5PClxHBIWQMW1gp0kN19osmq4yHZHMS1psoXMCQseDALg8ni8kAAmBkGMiqGwAYQgrnxIGBAFYUg4mgAVC5wwkHcpOACSUGIsDMYFuAgAgiqzDBNOs9k0AL7GoA)
```sh
--parser babel
```

**Input:**
```jsx
const x = define(/* foo */)
```

**Output:**
```jsx
Error: Comment "foo" was not printed. Please report this error!
    at https://prettier.io/lib/standalone.js:15:106002
    at Array.forEach (<anonymous>)
    at Object.ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:15:105970)
    at Xi (https://prettier.io/lib/standalone.js:15:111682)
    at Yi (https://prettier.io/lib/standalone.js:15:113795)
    at formatWithCursor (https://prettier.io/lib/standalone.js:15:113915)
    at https://prettier.io/lib/standalone.js:15:386874
    at Object.format (https://prettier.io/lib/standalone.js:15:386957)
    at formatCode (https://prettier.io/worker.js:124:21)
    at handleMessage (https://prettier.io/worker.js:75:18)
```

**Second Output:**
```jsx
SyntaxError: Unexpected token, expected ";" (1:16)
> 1 | Error: Comment "foo" was not printed. Please report this error!
    |                ^
  2 |     at https://prettier.io/lib/standalone.js:15:106002
  3 |     at Array.forEach (<anonymous>)
  4 |     at Object.ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:15:105970)
```
