### ISSUE TITLE
[Feature] license header

### ISSUE THREAD

**Issue by xenoterracide** [prettier/prettier#9676]
it would be useful to be abled to prepend a license header to any formatted file, this is inspired by [spotless](https://github.com/diffplug/spotless/)

in `prettierrc.json5`

```json5
{
   licenseHeaderFile: 'licenceHeader.txt'
}
```

and in the referenced file you could have

```
Copyright © $YEAR Caleb Cushing. All rights reserved
```

I'm suggesting a separate file so you can do multiline in any config without weird newline escapes for a multiline header

`$YEAR` in the output would be replaced by the actual current year.

A given language formatter would decide how to apply the header. Meaning in java it would probably add 

```java
/* Copyright © 2020 Caleb Cushing. All rights reserved */
```

but in html

```html
<!-- Copyright © 2020 Caleb Cushing. All rights reserved -->
```

The header would be updated if needed anytime prettier was run against the file.

**Comment by kachkaev** [comment]
Not sure if this feature is in scope of Prettier. See [What Prettier is _not_ concerned about](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about) in docs.

**Comment by xenoterracide** [comment]
I hear you, but seems like something prettier could easily integrate, and honestly there doesn't seem to be much in the way of choices, and if prettier doesn't do it you have to be concerned with ordering when running with prettier. Also have to give the idea.

**Comment by lipis** [comment]
I agree with @kachkaev: _Prettier only prints code. It does not transform it._ and this looks like it transforms it.
