### ISSUE TITLE
Feature Request: add option to ignore semicolons.

### ISSUE THREAD

**Issue by bassamanator** [prettier/prettier#9679]
It would be great if prettier would simply ignore semicolons in JS/JSX the way atom-beautify does.

- This option would not remove/add semicolons. Some lines of code might end with a semicolon while others might not.
- This option would ignore semicolons altogether. 

Thanks.

**Comment by thorn0** [comment]
What do you mean exactly? Please fill the issue template: input, current output, expected output.

**Comment by bassamanator** [comment]
Well I would like it if prettier would leave my semicolons alone. Meaning, prettier should not add any semicolons at the end of my lines nor should it remove them. I'm looking for a **"semi": ignore** option. 

Input:
```
let a = 2;
let b = 3
```
Current output with "semi": true

```
let a = 2;
let b = 3;
```

Current output with "semi": false

```
let a = 2
let b = 3
```
Expected output:
```
let a = 2;
let b = 3
```

**Comment by thorn0** [comment]
Sorry, but that would be totally against Prettier's [philosophy](https://prettier.io/docs/en/option-philosophy.html).

**Comment by bassamanator** [comment]
Alright.

**Comment by bassamanator** [comment]
I actually want to push back a bit against this if you don't mind. The thing is that prettier is not perfect. It might not often make mistakes but it makes mistakes on a regular basis. I've only been using prettier with JSX and sometimes ostensibly simple snippets of code get corrupted. It usually takes 3 cycles of undo-prettierify to get the code to look right when these corruptions happen. It's certainly not a big deal but I suspect (but what do I know) that the semicolon bit is throwing things off/complicating this process and I'd rather just turn this feature off so that the prettifying process can be simplified which might lead to less errors.

Really love this plugin by the way. Thanks!

**Comment by ricealexander** [comment]
Do you have specific examples of when it's advantageous to use semicolons inconsistently or where the formatting of semicolons causes errors?

**Comment by bassamanator** [comment]
I don't think it's advantageous to use semicolons inconsistently, in fact I prefer to use semicolons, consistently of coarse. I just think it's unwise to offload that work, that 'thinking' off to a plugin. 

And the next time prettier makes errors formatting my JSX I'll be sure to post a picture here. Again, I only suspect that semicolons are the culprit here, and I say that as a hobbyist, not a professional programmer.

**Comment by bassamanator** [comment]
Here's a small example of what I'm talking about. 

1. Before
![image](https://user-images.githubusercontent.com/61985779/103425635-9a81e300-4b81-11eb-80ee-912b8d17c79f.png)

2. Ran prettier

3. After
![image](https://user-images.githubusercontent.com/61985779/103425641-a8cfff00-4b81-11eb-810d-91b9209cf38a.png)

**Comment by brodybits** [comment]
@bassamanator something doesn't look right in your editor. I would highly recommend you use the [Prettier playground](https://prettier.io/playground/) to demonstrate your example. The Prettier playground even has buttons to copy the markdown or raise a new issue.
