### ISSUE TITLE
Prettier adds parens around a commented chained expression

### ISSUE THREAD

**Issue by hawkrives** [prettier/prettier#968]
In this example, I would expect to not have wrapping parentheses around the chain. (In fact, the original code here was formatted by prettier@0.21.)

Is this intended?

[prettier-web reproduction](https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20iosOpen(url%3A%20string)%20%7B%5Cn%20%20return%20SafariView.isAvailable()%5Cn%20%20%20%20%2F%2F%20if%20it's%20around%2C%20open%20in%20safari%5Cn%20%20%20%20.then(()%20%3D%3E%20SafariView.show(%7Burl%7D))%5Cn%20%20%20%20%2F%2F%20fall%20back%20to%20opening%20in%20default%20browser%5Cn%20%20%20%20.catch(()%20%3D%3E%20genericOpen(url))%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

```js
function iosOpen(url: string) {
  return SafariView.isAvailable()
    // if it's around, open in safari
    .then(() => SafariView.show({url}))
    // fall back to opening in default browser
    .catch(() => genericOpen(url))
}

// becomes

function iosOpen(url: string) {
  return (
    SafariView.isAvailable()
      // if it's around, open in safari
      .then(() => SafariView.show({ url }))
      // fall back to opening in default browser
      .catch(() => genericOpen(url))
  );
}
```

**Comment by vjeux** [comment]
cc @rattrayalex, probably due to your `return` diff

**Comment by rattrayalex** [comment]
Yup, definitely. I think I might have an idea how to fix... (Check for comments that are leading and not trailing, rather than just leading)

**Comment by rattrayalex** [comment]
Ah, that's not how it works. This may be quite hard. 

The trick is disambiguating between
```js
return (
  // comment
  a.b
    .c
)
``` 
where the comment is attached to the inner MemberExpression, not the leftmost Identifier, and
```js
return (
  a.b
    // comment
    .c.d
)
``` 
where a comment is also attached to a MemberExpression that is to the left of something. 

The line of the node here matters; if a comment is attached to a node whose `loc.start.line` is greater than the `loc.start.line` of the leftMost node, it should not be counted when deciding whether to wrap in parens. 

This doesn't actually sound too difficult to do, so I'll draw up an example, but it'll definitely hurt performance... not sure how significantly...

**Comment by vjeux** [comment]
By the way, if it is too complicated, I think we should just bail on it. While having a parenthesis there is not perfect, this is still acceptable.

**Comment by rattrayalex** [comment]
For posterity, this was my approach: 

```js
    let commentsByLine = {};
    let leftMostLine = null;
    let leftMost = argument;
    let newLeftMost;
    while (newLeftMost = getLeftSide(leftMost)) {
      leftMost = newLeftMost;
      const line = (leftMost.loc && leftMost.loc.start && leftMost.loc.start.line)
        ? leftMost.loc.start.line
        : null;
      leftMostLine = line;
      console.log({ line, leftMostLine, commentsByLine })

      if (hasLeadingOwnLineComment(options.originalText, leftMost)) {
        // bail if the node doesn't have line information, erring on the side of caution.
        if (line === null) {
          return true;
        }
        commentsByLine[line] = true;
      } else {
        if (line === null) {
          return false;
        }
        if (!commentsByLine[line]) {
          commentsByLine[line] = false;
        }
      }
    }

    return commentsByLine[leftMostLine];
```

it worked in all cases but this: 

```
function memberOutside() {
  return (
    // Reason for a
    a
  ).b.c
}
```
which I think had to do with the comment being attached in a strange place, perhaps due to special-case editing. 

So for now I don't think this is worth doing. I might think about a heuristic that uses the line of the ReturnStatement... but that's certainly feeling a little shaky...

**Comment by hawkrives** [comment]
FWIW, I've adjusted and I'm fine with having the parens there.

**Comment by vjeux** [comment]
I'm going to close this issue as while this would be great, it is very hard to do in practice and doesn't occur very often.
