### ISSUE TITLE
Remove parenthesis around flow shorthand

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#969]
Flow shorthand syntax with one arg prints with parenthesis. Let's drop it.

Before:
```js
type Banana = {
  eat: string => boolean,
};
```

After:
```js
type Banana = {
  eat: (string) => boolean,
};
```

**Comment by vjeux** [comment]
I looked at fixing it and this is in the same part of the codebase where the AST is completely crazy. I spent a week trying to get https://github.com/prettier/prettier/commit/91087e1e840cdd85a5a3a87ad05de615a621a906 to work.

I think that we should implement what you suggest but this is going to be tricky.

**Comment by yamafaktory** [comment]
@vjeux I've just seen you comment while trying to fix it. Now I guess my solution is not the way to go...

**Comment by yamafaktory** [comment]
In order to keep the issue discussion in sync too, my latest changes in #972 seems to solve it.
