### ISSUE TITLE
Format nested ternary operators in functional style

### ISSUE THREAD

**Issue by ansavchenco** [prettier/prettier#9690]
Currently nested ternary operators are formatted like this:
```javascript
const color =
  type === "success"
    ? SUCCESS_COLOR
    : type === "warning"
    ? WARNING_COLOR
    : type === "failure"
    ? FAILURE_COLOR
    : DEFAULT_COLOR;
```
It would be very nice to have a config option to make prettier format the above piece of code like this:
```javascript
const color =
  type === "success" ? SUCCESS_COLOR :
  type === "warning" ? WARNING_COLOR :
  type === "failure" ? FAILURE_COLOR :
  DEFAULT_COLOR;
```
I know that this is objective and all but in my opinion it looks much better and is easier to follow. It also takes almost twice less lines of code which can be considered a plus.

**Comment by kachkaev** [comment]
> It would be very nice to have a config option 

Please see https://prettier.io/docs/en/option-philosophy.html

**Comment by ansavchenco** [comment]
Well, sounds fair. Thank you!
