### ISSUE TITLE
Improve handling of non-typical whitespace characters like zero width space

### ISSUE THREAD

**Issue by silbinarywolf** [prettier/prettier#9697]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAngNQEMAbTAXkwB0R4NqBuQaAJKoQAaECABxgEt1koQgCdhEAO4AFEQjTIQJcYVxyOAI2GEwAazgwAyly28oAc2QxhAVzgc42NXAAmT5wBlCZq4VNwAYhDC2IQwfGbyhFYwEOwgABYw2MQA6nG8tEZgcPqy6bwAbum48mBoqiAmaHDCMJKapsHIAGYkVRwAVmgAHgBCmjp6+oTYcG4mcM2ttiCdXfompsRwAIpWEPCTxG0gRsJVwvJqhI7EsVzCJjDJvE4wccgAHAAMHOcQVcmaXPLncPv5Ew4AEc1vA6tw5ChCGgALRQODOZyxYRwEG8FF1HyNJAtLbTKrYXgWaz4hZLVbrCY4qYcGDHa63e5IABMtM0vGICwAwhBsNiQH8AKyxKxVAAqx0huO2+RsAEkoK5YPowBceABBRX6GC4JabKoAXwNQA)

**Input:**
```jsx
const myVal = "test";​
```

**Output:**
```jsx
SyntaxError: Unexpected character '​' (1:22)
> 1 | const myVal = "test";​
    |                      ^
  2 | 
```

**Expected behavior:**

- Prettier should when using `--write` strip out zero width characters
- When giving error messages, give pretty names for typically not used whitespace characters `Unexpected character '​'" (zero width space)`

**Why are you raising this issue?**
Somehow I copied a zero width space into my code (I actually have no idea how it got there). Prettier kept falling over on a particular line and I just couldn't figure out why, TypeScript/Parcel/Babel/Jest and other tooling worked fine.

**Comment by fisker** [comment]
It's not valid code, 

Node.js

```js
node test.js
test.js:1
console.log(1)​


SyntaxError: Invalid or unexpected token
[90m    at wrapSafe (internal/modules/cjs/loader.js:979:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1027:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m
```

https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUBGAlIaAIBQQ&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.3&externalPlugins=

We are not going to do this.
