### ISSUE TITLE
Plugin cannot print trailing comments without newline at end of file

### ISSUE THREAD

**Issue by dangmai** [prettier/prettier#9702]
**Environments:**

- Prettier Version: 2.1.2
- Running Prettier via: CLI
- Runtime: Node.js v14
- Operating System: Windows/Linux

**Steps to reproduce:**

I am the maintainer for [prettier-plugin-apex](https://github.com/dangmai/prettier-plugin-apex), which has an option to turn off the empty newline at the end of the formatted file (this is due to Salesforce's weird handling of empty lines). Recently a user [reports](https://github.com/dangmai/prettier-plugin-apex/issues/301) that when he uses that option, trailing comments are not being included in the formatted result.

I look into Prettier's core code and I've found that trailing comments are only flushed in the output if there is a new line somewhere after the comment, because a trailing comment uses `line-suffix`, and contents within line-suffix are only flushed after a new line, see [here](https://github.com/prettier/prettier/blob/31e7c1d04e00a5b1f9c20ba6244d3cd7d6f6506b/src/document/doc-printer.js#L505).

I know most Prettier languages do not support removing the trailing empty lines, but I do think some language plugins do need this depending on the language ecosystem they're supporting. Here are a couple of options that can address this issue:

- Prettier core can add a doc type that flushes line-suffix contents, similar to `line`, `softline` or `hardline`.
- Alternatively, Prettier can add a `postprocess` for plugin printers, which allows plugins to manipulate the formatted result. If this is an option, my plugin can always add a trailing empty line to the returned Doc, and remove it as part of post-processing phase based on options.

I know that in my plugin, I can implement `willPrintOwnComments` to work around this issue and make sure my comments are not in a `line-suffix`, however it's a very lengthy hack which IMO should be handled upstream. There may be other options that I haven't thought of as well, and I'm open to suggestions if anyone has any.

**Comment by thorn0** [comment]
You can try adding the [`lineSuffixBoundary`](https://github.com/prettier/prettier/blob/master/commands.md#linesuffixboundary) command to the end of your doc.

**Comment by dangmai** [comment]
Hey @thorn0 thanks for chiming in, it is actually one of the things I tried, but as you can see [here](https://github.com/prettier/prettier/blob/31e7c1d04e00a5b1f9c20ba6244d3cd7d6f6506b/src/document/doc-printer.js#L477), lineSuffixBoundary automatically adds a `hardline` to the end of the Doc, which ends up being the trailing empty line to the document (which is what I'm trying to avoid).

**Comment by thorn0** [comment]
I think what's needed is an extra check after the main loop in the doc printer that would flush the `lineSuffix` array if it's not empty. I'll happily review if you do a PR.

**Comment by dangmai** [comment]
That's a good point, I'll open a PR for it :)
