### ISSUE TITLE
Invalid code generated with jsx expression comment

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#971]
```js
<div>
  {
    // Comment
  }
</div>
```

outputs

```js
<div>
  {// Comment}
</div>;
```

This is a regression introduced by #675

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%20%20%7B%5Cn%20%20%20%20%2F%2F%20Comment%5Cn%20%20%7D%5Cn%3C%2Fdiv%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by hongymagic** [comment]
Extra test case:

```
<div>
  {
    // Comment 1
    // Comment 2
  }
</div>
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%20%20%7B%5Cn%20%20%20%20%2F%2F%20Comment%201%5Cn%20%20%20%20%2F%2F%20Comment%202%5Cn%20%20%7D%5Cn%3C%2Fdiv%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by hongymagic** [comment]
Thought I'd spend sometime looking through the codebase using this issue as a starting point, one implementation I've landed on is here: https://github.com/hongymagic/prettier/commit/90963639543b58050a1935fc8d649ad9c86ea458

**Comment by vjeux** [comment]
This is awesome! Could you send a PR?
