### ISSUE TITLE
Prefer escaping single quotes in strings rather than mixing quote styles.

### ISSUE THREAD

**Issue by maciejbembenista** [prettier/prettier#973]
Currently, this string (`'\'editing\' flag'`) is automatically converted to `"'editing' flag"` - is there a way to prefer escaped single quotes? The value of this preference is that it promotes a consistent code style.

In my opinion, there should be an option to leave the single quotes alone. What do you guys think?

Edit: I've encountered this issue in my Jest tests and I have the --single-quote option set.

**Comment by bakkot** [comment]
cf #390.

I agree that we should prefer consistent quotes over minimum number of escaped characters.

**Comment by SimenB** [comment]
I really like that it avoids escaping quotes, but if it's behind an option then that of course is fine

**Comment by lydell** [comment]
Don't you think that `"'editing' flag"` is easier to read than `'\'editing\' flag'`?

**Comment by macbem** [comment]
I think that consistency is more important than having to write/read another character. Mixing quote types makes you think if you're going to use a quote type same as the enclosing one inside the string or not. 

Escaping characters allows you to have that comfort of not having to think too much about your strings - you just get used to escaping all single quotes.

**Comment by lydell** [comment]
> mixing quote types isn't the industry standard and it won't be anytime soon

This is JavaScript – there are no industry standards at all :)

ESLint has a [`avoidEscape` option for the `quotes` rule](http://eslint.org/docs/rules/quotes#options), and [standard has it on by default](https://github.com/feross/eslint-config-standard/blob/df2400a95faf952b5b8469f509809942755a2342/eslintrc.json#L152), so mixing quotes is definitely not something new :)

> Escaping characters allows you to have that comfort of not having to think too much about your strings - you just get used to escaping all single quotes.

You could just escape _all_ quotes: prettier will remove unnecessary escapes. Since all projects don't use the same type of quote this makes you think even less :)

**Comment by bakkot** [comment]
FWIW, [AirBnB](https://github.com/airbnb/javascript#strings) and [Google](https://google.github.io/styleguide/javascriptguide.xml?showone=Strings#Strings) both recommend single quotes and don't even mention the possibility that you might want to mix quote styles. ESLint also has `avoidEscape` off by default. That's about as close to industry consensus as you'll find, I think.

It's just a style preference, of course. If we keep the current behavior it would prevent me from using prettier, though, and I'd be sad. If there's one thing I want from my code formatter, it's consistency.

**Comment by macbem** [comment]
My thougths exactly ;)

**Comment by SimenB** [comment]
@bakkot AirBnB might not mention it in the readme, but the implementation says that escapes are to be be avoided: https://github.com/airbnb/javascript/blob/772bbb5b7d2f6990e519c3d70539f807257492fe/packages/eslint-config-airbnb-base/rules/style.js#L332

Google does not have it though: https://github.com/google/eslint-config-google/blob/b8f993bf2a4149c436a5c52ff28314948d870cfd/index.js#L258

**Comment by bakkot** [comment]
@SimenB Ah, yup. Well that's horrifying. Should probably be mentioned in their readme.

**Comment by SimenB** [comment]
We can at least agree on that part 😄

I still think readability wins here, and as long as prettier enforces the consistency (which it does), I would really prefer it to remain as it is. Might be worth an option though, IDK how many of those are wanted?

**Comment by bakkot** [comment]
@SimenB, see, my perspective is that "use single quotes *except* [...]" is not consistent. Or at least is less consistent that "use single quotes." So I'd say that currently Prettier is enforcing *inconsistency*, which is why I'm strongly opposed to the current behavior.

**Comment by hongymagic** [comment]
Imagine a world escaping isn't even a thought process. Cognitively, I would think escaping techniques require more thought than mixed quotes. How is escaping any easier than writing quotes that make sense?

Never used mixed until prettier and <3 it

**Comment by bakkot** [comment]
@hongymagic 

> Is escaping any easier than writing quotes that make sense?

I think so, yes. Escaping happens at the point that I find myself writing the character which needs escaping, rather than at the start (and end) of the string. It's always easier for rules to be local.

And if I later need to add a quote mark to a string which doesn't already contain one, I don't need to go change the quotes the literal is using - or not, if it turns out there's already a quote mark of the *other* style in the string, in which case I'd need to just escape the character I'm adding anyway!

I certainly find it to be much lower cognitive overhead to have the rule be "always type `\'` inside of strings" than "figure out in advance which style of quote to use for every string you type".

**Comment by SimenB** [comment]
The thing is that you _don't_ have to figure it out ahead of time, just do whatever is easiest for you to write, and prettier will format it for you. That way, "always type `\'`" is still true :smile:

I spend way more time reading than writing code, and IMO it's easier to read without quotes.

**Comment by macbem** [comment]
You'll have lots of strings beginning with `'` and lots of them beginning with `"` - this is an example of **_inconsistent behaviour_** and this is something that code formatters were created to help us **avoid**, not promote.

**Comment by bakkot** [comment]
@vjeux Any word on this? This is one of the blockers for using prettier for a lot of my projects & those of people I've talked to about prettier.

**Comment by labithiotis** [comment]
How about using template literals instead, very little difference in performance overhead and just as readable and not mutated by prettier.

```
(`'editing' flag`)
```

 [https://jsperf.com/es-string-vs-template](https://jsperf.com/es-string-vs-template)

**Comment by macbem** [comment]
@labithiotis this is beyond the idea of code formatters like Prettier - they are supposed to format the code, not refactor it. Besides, template literals have only existed since ES6 and there surely are some people that would not like to be forced to use the new standard.

**Comment by vjeux** [comment]
We are now past 1.0 and are not going to do any big formatting changes like the one proposed here. There are pros and cons for both approaches and I don't think that we're going to get everyone happy, so it's best to keep with the status quo.

As for prettier being a code formatter and not a refactoring tool, this is true. But single/double quotes is more often than not lumped inside of the formatting category, so prettier has to make a decision around those.

**Comment by j-f1** [comment]
@jextrevor You could always change the style guide.

**Comment by jextrevor** [comment]
@j-f1 I'm not in a position to change the style guide, nor would I want to, nor would it be beneficial to our team to change the style guide in the middle of a large project.

**Comment by bakkot** [comment]
@jextrevor, I'm also not a fan of prettier's behavior here, but generally speaking "this conflicts with the style guide at my workplace" has not been held to be a sufficiently convincing reason for prettier to change its behavior or [add an option](https://prettier.io/docs/en/option-philosophy.html) (which I think is a good decision).

If the problem is just that you don't want to have to format it and then check it against the style guide, a lot of people use [prettier-eslint](https://github.com/prettier/prettier-eslint) to apply prettier's style and then use eslint to make small tweaks of exactly this sort in a single pass.

**Comment by jextrevor** [comment]
@bakkot By itself, it may not be convincing, but I think it adds value to the conversation here: Prettier is used in all sorts of situations, and though sometimes mixed quotes may be "easier to read" or ideal in an "imagined world", it's important to remember that code formatters are used in real life situations where there's a style guide that isn't going to change for reasons like these.

Thanks for the tip about prettier-eslint.

**Comment by lydell** [comment]
If you have style guides that can't change – don't use Prettier. It would be a constant uphill battle.

**Comment by dougal83** [comment]
> If you have style guides that can't change...

@lydell Same can be said for Prettier's rules.

There is a clear conflict here with the application of the ``"prettier.singleQuote: true"`` rule.  I'd personally like to see a rule regarding escaped character behaviour in this instance.  Littering code with ``// prettier-ignore`` seems unnecessary.

+1 for prettier following its own rules.

**Comment by j-f1** [comment]
We do follow our own rules. The `singleQuote` option specifies the *preferred* quote style, but we will switch to the other quote style so the strings are easier to read.

**Comment by j-f1** [comment]
We do follow our own rules. The `singleQuote` option specifies the *preferred* quote style, but we will switch to the other quote style so the strings are easier to read.

> Littering code with `// prettier-ignore` seems unnecessary.

It is in most cases. Just remove the comments :)

Alternatively, you could use `prettier-eslint` so you can have whatever quote rules you want.

**Comment by dougal83** [comment]
@j-f1 Hi Jed, thank you for pointing me toward prettier-eslint, that is very helpful.  Much appreciated.

This is all subjective, I'm one of those people that find switching quotes extremely difficult to read on account of how I handle reading as a dyslexic.  On the whole, prettier is a massive boon.  The string escape in this instance is extremely easy for someone with my disability to scan visually... especially when most programming environments alter the font colours on top.  Switching the quotes is jarring to read for me and it is disappointing to not have an option in this case to allow escapes to keep quotes consistent, but you've given me a good alternative so I'm grateful.

Perhaps the [documents](https://prettier.io/docs/en/options.html#quotes) could emphasis initially the _prefered_ nature you've highlighted.

**Comment by u84six** [comment]
I came here for the same reason. I like using single quotes and escapes and my linter throws errors on double quotes. But rather than having a long discussion around which one wins: simplicity vs consistency, I think what wins is the ability to turn off something that automatically changes your code. Again, ignoreEscape when formatting would be very useful.

**Comment by fractalawareness** [comment]
I don't see any downsides of making it configurable with default behavior that equals to the current implementation. Everybody would be happy with it.

**Comment by lydell** [comment]
@fractalawareness For the downside of configuration, see the [option philosophy](https://prettier.io/docs/en/option-philosophy.html).

**Comment by fractalawareness** [comment]
> @fractalawareness For the downside of configuration, see the [option philosophy](https://prettier.io/docs/en/option-philosophy.html).

Thank you for response!

So it seems like this philosophy was partly introduced to avoid adding options that can be temporary. But this issue is few years old already so there is constant flow of people dealing with this inconsistency issue:
https://github.com/prettier/prettier/issues/2338
https://github.com/prettier/prettier/issues/2516
https://github.com/prettier/prettier/issues/838
https://github.com/prettier/prettier/issues/2031
https://github.com/prettier/prettier/issues/2338

And the last sentence of option philosophy is: 
> But if the issue does seem to need a new option, we’ll generally keep it open, to let people 👍 it and add comments.

So we have like ~70 overall 👍 on this issue (with duplicates).

Seems like enough reasons for adding this option.

**Comment by jextrevor** [comment]
If there's hesitancy to add the option based on other higher priorities, I'd love to work on and get a PR opened.

**Comment by lydell** [comment]
@jextrevor Thanks for the offer! But code is the easy part.

**Comment by bakkot** [comment]
> So we have like ~70 overall 👍 on this issue (with duplicates). Seems like enough reasons for adding this option.

FWIW I would want the bar for adding an option to be _much_ higher than this.

**Comment by cpboyd** [comment]
Just to add: This also happens to Markdown. YAML frontmatter treats single quotes and double quotes differently.

Single quotes are effectively eliminate the need to escape anything (aside from the quote itself), and I'd prefer a single `'Don''t replace me'` over inconsistencies in files.

**Comment by leonardorb** [comment]
I'm having to do something like:
```js
console.log(`Can${'`'}t add more players to the game.`)
```
Looks ugly, but it "solves" the issue. I'm assuming no further development is going to be made towards this since the issue was closed? Glad to help if any.

**Comment by lydell** [comment]
@leonardorb I don’t think I understand your issue? I’d write your code like this:

```js
console.log(`Can\`t add more players to the game.`)
```

Or, to avoid the escape:

```js
console.log("Can`t add more players to the game.")
```

But, really, one should use an apostrophe:

```js
console.log("Can't add more players to the game.")
```

Even better – a typographic one:

```js
console.log("Can’t add more players to the game.")
```

Also works with single quotes if you prefer:

```js
console.log('Can’t add more players to the game.')
```

Or backticks if you like always being ready for adding interpolations:

```js
console.log(`Can’t add more players to the game.`)
```

But this issue isn’t about template literals though. It’s about some people preferring escapes over mixed quote styles.

**Comment by leonardorb** [comment]
@lydell yeah, let me add more context to it. I'm using `ESLint` + `Prettier`, with VSCode. The core of my setup is:

#### under my `settings.json` I have (VSCode)
```json
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
 }
```

#### my `.prettierrc` config file:
```json
{
  "printWidth": 120,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all",
  "tabWidth": 2
}
```

#### my `.eslintrc.js` file:
```js
module.exports = {
  env: {
    es6: true,
    node: true,
  },
  extends: 'eslint:recommended',
  globals: {
    Atomics: 'readonly',
    describe: true,
    expect: true,
    test: true,
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: ['prettier'],
  rules: {
    indent: ['error', 2],
    'linebreak-style': ['error', 'unix'],
    quotes: ['error', 'single'],
    semi: ['error', 'never'],
  },
}
```

If I have:
```js
console.log('Can\'t add more players to the game.')
```
after saving, this will get converted to:
```js
console.log("Can't add more players to the game.")
```
like @macbem mentioned on the first post of this thread. And `ESLint` will complain:
![](https://leo.d.pr/2WdMql+)

What am I doing wrong here?

**Comment by fisker** [comment]
see https://github.com/prettier/eslint-config-prettier/blob/master/README.md#quotes

**Comment by leonardorb** [comment]
@fisker thanks! I missed that. `quotes: ['error', 'single', { avoidEscape: true }]` works like a charm.

**Comment by matthew-manuel** [comment]
Yeah Prettier is fighting with my other formatters and linters by forcing double quotes in lots of places where we (and our other tools) want single quotes.  This was a deal breaker unfortunately, not worth the effort to fight with it, so we are moving away from Prettier.

**Comment by lydell** [comment]
@matthew-manuel Yeah, using tools that conflict with each other is not recommended. Removing (or re-configuring) one of the is the correct solution :+1:

**Comment by jpike88** [comment]
I get the concept of having a strongly opinionated formatter, but it has made some decisions which are completely arbitrary and in my opinion poorly conceived. 

Mixing double quote and single quote strings makes zero sense, so what if you escape the rare single quote, it'd rather that than trying to locate where strings are via two different pairs of characters.

There should be SOME ability to override settings which are controversial. This one is the best example of that.

**Comment by dougal83** [comment]
I can see both sides of the argument here but ultimately the decision lies with the project lead.

The project has to push back against configuring every little option or it will balloon and not be opinionated (considered good practice).

I'm actually dyslexic and the mixing quotes irks me as I scan code.  To compensate, when reading I scan visually for images of words(recognise) and I have to stop and actually read words that are irregular to me... the mixing quotes throws me every time.  Like all things, I'll carry on compensating.

**Comment by dsaw** [comment]
I also had the single quote option enabled for jsx and js too - but prettier is converting html attribute values to `"`. Most of the attribute values are double quoted, yes but its the opposite behaviour in js. Plus the documentation isn't crystal clear on what behavior is expected [()](https://prettier.io/docs/en/next/rationale.html#strings).

**Comment by lydell** [comment]
@dsaw Do you have a suggestion on how we can make the documentation better? Or point out something specific that isn’t clear?

**Comment by dsaw** [comment]
@lydell.  From the documentation, I take that for html/jsx the default format is double strings if you say set `singleQuote` to true (which is for js files). However, when I set `jsxSingleQuote` to true even then the single quote attribute values in the html turn to double quotes, though I was expecting the opposite, from the docs atleast. 
Double quotes is considered standard for HTML I see. Could it be clarified what should be the default behaviour in this case?

**Comment by lydell** [comment]
Oh, I didn’t even know HTML doesn’t obey the singleQuote option 🤯

**Comment by nsisodiya** [comment]
Eslint setting will fix this.
```
quotes: ['error', 'single', { avoidEscape: true }]
```
PS: I just copy pasted this solution from this thread itself. easy for those who are in hurry.

**Comment by serabariq** [comment]
> avoidEscape

This is the correct answer

**Comment by serabariq** [comment]
> @fisker thanks! I missed that. `quotes: ['error', 'single', { avoidEscape: true }]` works like a charm.

This is the correct answer
