### ISSUE TITLE
Edge-cases with `expect` + callback as first param

### ISSUE THREAD

**Issue by kjbekkelund** [prettier/prettier#974]
I found some "edge cases" when playing around with the results I got when running Prettier on my tests.

```js
expect(() => asyncRequest({ url: "/test-endpoint" }))
  .toThrowError(/Required parameter/);

expect(() => asyncRequest({ url: "/test-endpoint-but-with-a-long-url" }))
  .toThrowError(/Required parameter/);

expect(() => asyncRequest({ url: "/test-endpoint-but-with-a-suuuuuuuuper-long-url" }))
  .toThrowError(/Required parameter/);

expect(() => asyncRequest({ type: "foo", url: "/test-endpoint" }))
  .not.toThrowError();

expect(() => asyncRequest({ type: "foo", url: "/test-endpoint-but-with-a-long-url" }))
  .not.toThrowError();
```

transforms into:

```js
expect(() => asyncRequest({ url: "/test-endpoint" })).toThrowError(
  /Required parameter/
);

expect(() =>
  asyncRequest({ url: "/test-endpoint-but-with-a-long-url" })).toThrowError(
  /Required parameter/
);

expect(() =>
  asyncRequest({
    url: "/test-endpoint-but-with-a-suuuuuuuuper-long-url"
  })).toThrowError(/Required parameter/);

expect(() =>
  asyncRequest({ type: "foo", url: "/test-endpoint" })).not.toThrowError();

expect(() =>
  asyncRequest({
    type: "foo",
    url: "/test-endpoint-but-with-a-long-url"
  })).not.toThrowError();
```

Number 2 feels like a bug to me, the others might be "as intended" (just different from what I expected).

For me, in the last three it kinda feels like the assertions are _within_ the callback (as we're not putting the `)` on its own line it's "difficult" to see we're doing something to the result). I'm not sure what result I think would be best here (and it might just be "it's different so it's just about getting used to it"), but to have some examples for discussion these seem easier to read:

```js
expect(() => asyncRequest({ url: "/test-endpoint" }))
  .toThrowError(/Required parameter/);

expect(() => asyncRequest({ url: "/test-endpoint-but-with-a-long-url" }))
  .toThrowError(/Required parameter/);

expect(() =>
  asyncRequest({ url: "/test-endpoint-but-with-a-suuuuuuuuper-long-url" })
).toThrowError(/Required parameter/);

expect(() => asyncRequest({ type: "foo", url: "/test-endpoint" }))
  .not.toThrowError();

expect(() =>
  asyncRequest({
    type: "foo",
    url: "/test-endpoint-but-with-a-long-url"
  })
).not.toThrowError();
```

Or maybe:

```js
expect(() =>
  asyncRequest({ url: "/test-endpoint-but-with-a-suuuuuuuuper-long-url " })
)
  .toThrowError(/Required parameter/);

expect(() =>
  asyncRequest({
    type: "foo",
    url: "/test-endpoint-but-with-a-long-url"
  })
)
  .not.toThrowError();
```

But this doesn't look good:

```
expect(() =>
  asyncRequest({ url: "/test-endpoint-but-with-a-suuuuuuuuper-long-url " }))
  .toThrowError(/Required parameter/);
```

So all in all: not sure, just thought I'd open this to hear your thoughts

https://prettier.github.io/prettier/#%7B%22content%22%3A%22expect(()%20%3D%3E%20asyncRequest(%7B%20url%3A%20%60%2Ftest-endpoint%60%20%7D))%5Cn%20%20.toThrowError(%2FRequired%20parameter%2F)%3B%5Cn%5Cnexpect(()%20%3D%3E%20asyncRequest(%7B%20url%3A%20%60%2Ftest-endpoint-but-with-a-long-url%60%20%7D))%5Cn%20%20.toThrowError(%2FRequired%20parameter%2F)%3B%5Cn%5Cnexpect(()%20%3D%3E%20asyncRequest(%7B%20url%3A%20%60%2Ftest-endpoint-but-with-a-suuuuuuuuper-long-url%60%20%7D))%5Cn%20%20.toThrowError(%2FRequired%20parameter%2F)%3B%5Cn%5Cnexpect(()%20%3D%3E%20asyncRequest(%7B%20type%3A%20%60foo%60%2C%20url%3A%20%60%2Ftest-endpoint%60%20%7D))%5Cn%20%20.not.toThrowError()%3B%5Cn%5Cnexpect(()%20%3D%3E%20asyncRequest(%7B%20type%3A%20%60foo%60%2C%20url%3A%20%60%2Ftest-endpoint-but-with-a-long-url%60%20%7D))%5Cn%20%20.not.toThrowError()%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/pull/927 changes the way this is behaving. I'm not at a computer right now but you may want to see how it behave with it.

**Comment by kjbekkelund** [comment]
@vjeux :tada: The result:

```js
expect(() => asyncRequest({ url: "/test-endpoint" })).toThrowError(
  /Required parameter/
);

expect(() =>
  asyncRequest({ url: "/test-endpoint-but-with-a-long-url" })
).toThrowError(/Required parameter/);

expect(() =>
  asyncRequest({ url: "/test-endpoint-but-with-a-suuuuuuuuper-long-url" })
).toThrowError(/Required parameter/);

expect(() =>
  asyncRequest({ type: "foo", url: "/test-endpoint" })
).not.toThrowError();

expect(() =>
  asyncRequest({
    type: "foo",
    url: "/test-endpoint-but-with-a-suuuuuuuuper-long-url"
  })
).not.toThrowError();
```

I ❤️ it!

(The only nit I can think of is having the first split on `toThrowError`, but as this is generally way better that master I'll close this issue)

**Comment by vjeux** [comment]
Let's reopen until it actually lands :)

**Comment by kjbekkelund** [comment]
(These could be potential extra tests for that PR too)

**Comment by vjeux** [comment]
Added the tests to the PR as well, thanks!
