### ISSUE TITLE
2.2.1 patch release

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#9744]
Anything else?

## TODO

- [x] #9740 (#9741)

**Comment by sosukesuzuki** [comment]
@fisker Do you know other issues that should be included in 2.2.1? If no, I'll release today.

**Comment by fisker** [comment]
I guess there is no other issue introduced in v2.2.0.

#9734 is broken since v2.1.0, and the PR is not approved, I'm not sure if we want include this one.

**Comment by sosukesuzuki** [comment]
@fisker Okay, I'll release without #9736 for now. When #9736 is merged, we'll release next patch version (2.2.2).

**Comment by sosukesuzuki** [comment]
[2.2.1](https://github.com/prettier/prettier/releases/tag/2.2.1) has been published!
