### ISSUE TITLE
Invalid code format

### ISSUE THREAD

**Issue by montogeek** [prettier/prettier#977]
Hi!

I couldn't find a similar issue, if it is a duplicate, sorry.

prettier 0.22.0 is formatting this code:
```js
var inherits = function (subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
    throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
  }

  subClass.prototype = Object.create(superClass && superClass.prototype, {
    constructor: {
      value: subClass,
      enumerable: false,
      writable: true,
      configurable: true
    }
  });
  if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;
};
```

to
```js
var inherits = function(subClass, superClass) {
    if (typeof superClass !== 'function' && superClass !== null) {
      throw new TypeError(
        'Super expression must either be null or a function, not ' + typeof superClass,
      );
    }

    subClass.prototype = Object.create(superClass && superClass.prototype, {
      constructor: {
        value: subClass,
        enumerable: false,
        writable: true,
        configurable: true,
      },
    });
    if (superClass)
      Object.setPrototypeOf
        ? Object.setPrototypeOf(subClass, superClass)
        : (subClass.__proto__ = superClass);
  };
```
```js
 throw new TypeError(
        'Super expression must either be null or a function, not ' + typeof superClass,
      );
```

These lines are incorrect, causing a `Uncaught SyntaxError: Unexpected token )` error, that comma is not expected

**Comment by yamafaktory** [comment]
This is indeed a bug, thanks! Minimal repro case https://prettier.github.io/prettier/#%7B%22content%22%3A%22a(%5C%22longgggggggggggggggggggggggggggggggggggggggffffffffefwefwefwefwefwefwefweff%5C%22)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by yamafaktory** [comment]
Oh wait, are you using the `--trailing-comma all` flag? If so, then this is intended as stated in the doc https://github.com/prettier/prettier#api.

**Comment by montogeek** [comment]
Yes, I am "prettier --single-quote --print-width=90 --trailing-comma=all --write '{src,test}/**/*.js'"

**Comment by existentialism** [comment]
@montogeek you need to either switch it to `--trailing-comma=es5`, or use `babel-plugin-syntax-trailing-function-commas` in your project

**Comment by montogeek** [comment]
Actually I got this bug by mistakenly running prettier on bundle, I already make a change to only _prettierify_ src code

**Comment by yamafaktory** [comment]
If you're unfamiliar with this you can check https://github.com/tc39/proposal-trailing-function-commas.

**Comment by montogeek** [comment]
Thanks for the help!

**Comment by montogeek** [comment]
Thanks @yamafaktory
