### ISSUE TITLE
Embed Function in browser returns Error: Couldn't find plugin for AST format 

### ISSUE THREAD

**Issue by thebells1111** [prettier/prettier#9770]
**Environments:**

- Prettier Version: 2.2.0
- Running Prettier via: Browser
- Runtime:  Chrome v83,
- Operating System: Windows

**Steps to reproduce:**

```js
function embed(path, print, textToDoc, options) {
  const node = path.getNode();

  if ((node.type = "style")) {
    const content = "div{color:red}";

    try {
      const body = textToDoc(content, {
        parser: "css",
        plugins: [parserPostcss],
      });

      let result = prettier.doc.group(
        prettier.doc.concat(["<", "style", ">", body, "</", "style", ">"])
      );

      return result;
    } catch (error) {
      console.log("err: " + error);
      return "err: " + error;
    }
  }
  return null;
}
```
**Expected behavior:**

`textToDoc` to return the formatted code. 

**Actual behavior:**

I'm working on a browser based plugin, and want to use `embed` to use a different parser for a portion of the code. I understand the browser needs me to explicitly set the plugin to be used. I thought I was doing that by passing `plugins` to the `textToDoc` options. If I remove the `plugins` option, I get this error. `Error: Couldn't resolve parser "css". Parsers must be explicitly added to the standalone bundle.`. When I add the plugin, I get this error. `Error: Couldn't find plugin for AST format "postcss"`. What do I need to do so the plugin for AST format can be found? What else needs to be done in order to get `textToDoc` to work in the browser?

**Comment by thorn0** [comment]
Plugins probably aren't supposed to be added at this stage. They should be passed in the top-level `prettier.format` call.

**Comment by thebells1111** [comment]
I have a custom plugin being added at the top-level `prettier.format` call. I thought `embed` was to call a different plugin to parse a different language when it's encountered by the original parser. For example, if my plug-in was `Babel` for Javascript, and I wanted to parse some CSS-in-JS, wouldn't I need to have some sort of CSS parser to take care of that. Where would I pass in the second parser?

**Comment by thorn0** [comment]
> Where would I pass in the second parser?

In the same place where you pass the first one. When you call `format`, you need to pass all the plugins that are supposed to be used by that format run. Does that answer your question?

**Comment by thebells1111** [comment]
It does answer my question. Thank you.
