### ISSUE TITLE
Chain calls, the code will all wrap

### ISSUE THREAD

**Issue by jahnli** [prettier/prettier#9773]
![image](https://user-images.githubusercontent.com/20943608/100178546-0633b900-2f0f-11eb-93fa-963c42343c77.png)
![image](https://user-images.githubusercontent.com/20943608/100178643-42671980-2f0f-11eb-8723-99c600944fe8.png)

**Comment by thorn0** [comment]
Please fill the issue template: input, current output, expected output. Use the playground to generate reproducible examples. Please [don't post code as images](https://meta.stackoverflow.com/questions/285551/why-not-upload-images-of-code-errors-when-asking-a-question).
