### ISSUE TITLE
Semicolon being added at the beginning of expression

### ISSUE THREAD

**Issue by roddds** [prettier/prettier#9776]
**Prettier 2.2.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAglMALCAnAAmzzgDMBeAHRACsBDANzoGcw8BLABxiQYnYAmACgAMASmoA+AMLY4YANYEIAVxgEY2dswLN2iggBt2UBagD0mHPkkgANCAjd20ZslB08eCAHcACp4Ibih0hj50AJ5uDgBGeHSKcDAAypwJJgDmyDB4KnAOcAC2MXACAqUAMnRQGSp0GXAAYviFdDAwmcggdGoQ9iDYMIWGAOpa8MxpYHDJQewdDPMRXWDM0SAmzHB4MH7xGa3IpKFbDjTMAB4AQvGJKXSFcBUmcEcn+bSXyZmGcACKKgg8DehlOIDSeC2eC6pEMvn6nA4sBGgk0yAAHCIHIiIFsRvFOF1EXAoQxXg4AI6A+B7JzBbrMAC0UDgpVK-RIVPYJD29UOSGOoI+W0K7BBYL0NV+AKBrwF7wcMDoMRRAjRSAATIr4uxjDVpBBCvyQCSAKz9FRbAAqyuCgrBDDyAEkoOVYMk2FwYJgBMkYBFfuK4ABfYNAA)
```sh
--parser flow
--no-semi
```

**Input:**
```jsx
<Anchor href="javascript:void(0)">Check out this sick link</Anchor>
```

**Output:**
```jsx
;<Anchor href="javascript:void(0)">Check out this sick link</Anchor>

```

(notice the semicolon at the beginning of the line)

**Expected behavior:**

```jsx
<Anchor href="javascript:void(0)">Check out this sick link</Anchor>

```

I can't tell whether this is a duplicate of #1510, so if it is feel free to close.

**Comment by thorn0** [comment]
This works as expected. These leading semicolons are explained [here in the docs](https://prettier.io/docs/en/rationale.html#semicolons). Specifically JSX has been discussed in https://github.com/prettier/prettier/issues/1433.
