### ISSUE TITLE
Empty YAML front matter breaks horizontal rules in markdown when formatting 

### ISSUE THREAD

**Issue by taoky** [prettier/prettier#9788]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdK7VawYgAIAVASxgBs5CBGPKACTgoogBpCB3CAJwoBN6OevAAeMEGxAQADjFLQAzslABDHjwicACuoTKUqip1UBPZVIBGPVWADWcGAGUZt0lADmyGDwCucKTgAW0s4fn4wgBlVT19VDzgAMV4g1Rh5T2QQVV8YCEkQAAsYIIoAdULyOEVXMDgnfXJSADdyUyywRQsQd0U4HhhtGw9U5AAzIz6pACtFUQAhG3tHJ1UguEj3OHHJgJBZ0Sd3DyoARV8IeB2KKZBXHj6eLNSeO34tKAKZHncYMtJ+DBCsgABwABik3wgfTKNhkWW+1X6zW2UgAjhd4ENZAZsopUFA4GEwgUeHAMaQyUN4qMkBMbns+kFSN4-IzjmdMds6bspDBVJZ-oDgUgAEx8mykCjHADCECCtJA1QArAVfH1iAKDPTbs1-ABJKARWBOMA-OQAQSNThgpio1z6AF9HUA)
```sh
--parser markdown
```

**Input:**
```markdown
---
---

# Title 1

Hello, world

---

text
```

**Output:**
```markdown
---
---
# Title 1

Hello, world
---

text

```

**Expected behavior:**

The same as input (No converting `Hello, world` from `<p>` to `<h2>`)

When `--embedded-language-formatting` is off, this problem is gone.

**Comment by fisker** [comment]
Empty frontMatter can't work in  css too

**Prettier 2.2.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdK7UgDQgQAOMAltAM7KgCGATnRAO4AK9CVKNANkzQJ5UCAIzo0wAazgwAykXGkoAc2Qw6AVzgE4AW2FwAJgcMAZGsvU0lcAGIQ6OmjDLLkIGupgR8IABYwdbgB1X1J4CnkwOBkOMNIANzD+NzAKIRBFCjg6GBYxJUdkADMeLIIAKwoADwAhMUlpGRodOBNFOGLSrRBKqplFJW44AEV1CHhO7jKQeTosuhS0nyI6RRgg0gMYX2QADgAGAhWILKCxIjcVuHn4joIARzH4POJOdwpUKDhDQx86OEepH+eSshSQJSm3SyOlIqg0UIGQ1G4w64K6BBgNGEGy2OyQACYMWJSNwBgBhCA6MEga4AVh86iyABUsZwIdN4poAJJQYywGRgVYkACCvJkMH4Q0mWQAvjKgA)
```sh
--parser css
```

**Input:**
```css
---
---
```

**Output:**
```css
TypeError: Cannot read property 'trim' of undefined
    at print (https://prettier.io/lib/standalone.js:15:292310)
    at Object.sb [as embed] (https://prettier.io/lib/standalone.js:15:292554)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15:113406)
    at _a (https://prettier.io/lib/standalone.js:15:114825)
    at https://prettier.io/lib/standalone.js:15:114370
    at Object.printComments (https://prettier.io/lib/standalone.js:15:110811)
    at e (https://prettier.io/lib/standalone.js:15:114350)
    at wa.call (https://prettier.io/lib/standalone.js:15:112603)
    at https://prettier.io/lib/standalone.js:15:303123
    at wa.each (https://prettier.io/lib/standalone.js:15:112878)
```

**Comment by fisker** [comment]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdK7VawHgBMBLANwD4scCB6EikAGhAgAcZjoBnZUAQwBOAiAHcACoIQ8UfADYi+ATx7MARgL5gA1nBgBlVpuJQA5shgCArnGZwAtqriFCTgDJ9TlvibgAxCAJ2fDAcpsggfJYwEEwgABYwdrIA6nHE8FyGYHB6Uulk6YrhYFwqIMZccAIwYhomQcgAZnKVzABWXAAeAEIa2rp6fHZwrsZwTS02IB2desYmsnAAipYQ8BOyrSCGApUC4QlJsawCxjDJxIQwccgAHAAMzCcQlckarOEncHuk48wAjqt4LU2NIIlxUFA4E4nLEBHBAcR4bVvA0kM1NlNKnZiOYrFj5osVmtxujJswYHxVBcrjckAAmCkaYiyeYAYQgdjRIG+AFZYpZKgAVKnSDFbUjWACSUBcsD0YFO7AAgrK9DBFIsNpUAL46oA)
```sh
--parser html
```

**Input:**
```html
---
---

<div>
---
</div>
```

**Output:**
```html
SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (6:1)
  4 | <div>
  5 | ---
> 6 | </div>
    | ^^^^^^
```
