### ISSUE TITLE
Not ideal flow type formatting for `null | {}`

### ISSUE THREAD

**Issue by stas-vilchik** [prettier/prettier#979]
[This snippet](https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Props%20%3D%20%7B%5Cn%20%20field%3A%20null%20%7C%20%7B%20%5Cn%5Ctkey%3A%20string%5Cn%20%20%7D%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D) generates wrong and invalid output.

```js
type Props = {
  field: null | { 
	key: string
  }
};
```

outputs

```js
type Props = {
  field:
    | null
    | {
        key: string
      }
};
```

However [this one](https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Props%20%3D%20%7B%5Cn%20%20field%3A%20null%20%7C%20%7B%20key%3A%20string%20%7D%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D) is correct.

```js
type Props = {
  field: null | { key: string }
};
```
outputs

```js
type Props = {
  field: null | { key: string }
};
```

**Comment by vjeux** [comment]
Hey, thanks for the bug report. Both are actually correct and valid flow, but indeed the first one is not ideal.
Related to #864 and #981

**Comment by vjeux** [comment]
I've been looking into it a bit and I don't see any easy way to fix this unfortunately, so I'm going to close the issue as it's not actionable. If someone is interested in fixing this, a fix would be welcome.
