### ISSUE TITLE
Allow compacting single-line void functions

### ISSUE THREAD

**Issue by kripod** [prettier/prettier#9790]
Event callbacks mostly have no return type, so it may be misleading to write code like:

```jsx
// The callback given to `onClick` returns a number instead of nothing
<button onClick={(e) => setTimeout(() => console.log(e), 3000)}>
  I'll print my click event to the console in 3 seconds
</button>
```

To encourage correct return types for callbacks, the code below should be formatted as-is:

```tsx
// Notice the curly brackets encapsulating the outer function's body
<button onClick={(e) => { setTimeout(() => console.log(e), 3000)} }>
  I'll print my click event to the console in 3 seconds
</button>
```

The current behavior is to [force formatting void-returning functions as multi-line](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAchGBLMODGACyLAFcAnAGwE8MAjKgQzAGs4YBnDBMFgAduFGi3xQA5sTIYIFeFQwAzClDD5oAcl6MIAEzoAdKAB5GCmNDlQAwjQLsAvMAAUcAJQYnAPgzAMbi4AFTwAWzh5GFdXL18MSChuCBo4ADoaCEl3DwAaDABmAAYSjwBfDDKfEwwMAEktGhoMQSo8WAwwhjAHDj4ANwQYYggZcmhk1Ix2wsC4RP1uE1NUCxgrKB8QXJAIQU0k5FAWKioIAHcABROEbmQQFhpzljo7neY2ThgAZUE2dskyBgVAocB2cDCjDg+n00IAMiwpBQWJI4AAxCBUMLiCSAlAsBQQbYgEgwMI0ADqJDw8G4f0I31uNLw-RpdHuYG4bxA7SCVBgl1YkmxyGUjyCOwAVtwAB4AIVYHC43xYETh7TgovFYJA0pl3wBqQAihRcJqkGKaBKQH8qHz7owWFCaMTWu0YBS8PpSMgABxFHatCBBCmsQT3VpwPmDYkAR1N8EFezu+O4AFooHBodDiVQ4PG8HnBSiRRbtTsgmE8ECQTruIa4CazVqrTqYE7Pd6SMgAEw7YEsPAOKS2CBhUsgKMAVmJFCCwSdKct1v6oLqUFhsG+YDa+wAghvvjA6KkW0EymUgA), even if the body contains only a single expression:

```tsx
// Notice the curly brackets encapsulating the outer function's body
<button
  onClick={(e) => {
    setTimeout(() => console.log(e), 3000);
  }}
>
  I'll print my click event to the console in 3 seconds
</button>;
```

**Comment by thorn0** [comment]
This was brought up earlier. E.g. in #3684. Works as intended.

**Comment by kripod** [comment]
I’m suggesting that the behavior should be overridable. Multi-line by default, but single-line when desired, just like with small objects.

**Comment by thorn0** [comment]
Please see the last paragraph here https://prettier.io/docs/en/option-philosophy.html

**Comment by kripod** [comment]
I apologize for pushing it. Understanding that the project takes a lot of effort to be maintained, I’m thankful for all the work and governance put into it.

**Comment by thorn0** [comment]
Thanks. See also this related comment: https://github.com/prettier/prettier/issues/9391#issuecomment-707975158
