### ISSUE TITLE
Prettier writes empty files when used with npm-watch

### ISSUE THREAD

**Issue by olpeh** [prettier/prettier#980]
Steps to reproduce:
- `npm install -g create-react-app`
- `create-react-app prettier-empty-files`
- `cd prettier-empty-files`
- `yarn add prettier`
- `yarn add npm-watch` https://www.npmjs.com/package/npm-watch
- modify package.json as follows:

```
"watch": {
    "format": "src/*.js"
  },
  "scripts": {
    "start": "npm run watch && react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "watch": "npm-watch",
    "format": "prettier --trailing-comma es5 --single-quote --write 'src/**/*.js*' 'src/*.js*'"
  }
```
- `yarn start`
- Change something in a .js file and hit save (see attached gif)

I'm unable to reproduce the bug 100% with this setup, but it happens quite often, I have been able to reproduce it at least 8 times in a couple of minutes.

![peek 2017-03-10 18-35](https://cloud.githubusercontent.com/assets/6113341/23803823/6d7d25fa-05c0-11e7-8d59-2fd0f2edf9d8.gif)

**Comment by vjeux** [comment]
@M-Zuber @grncdr, you may have an idea of what could be happening here?

**Comment by olpeh** [comment]
I am just thinking out loud:

Could this happen because of the watcher triggering a new prettier run when prettier writes, and if that is triggered before prettier manages to write the file, so in between the file would be empty and prettier result for an empty file is of course an empty file?

I am thinking this because as I stated here https://github.com/prettier/prettier/issues/575 I managed to run prettier like this using https://github.com/mikeal/watch instead of npm-watch.
I later realized it triggers the prettier formatting twice, once when I hit save, second time when prettier writes back to the files.

Surely there must be a better solution...

**Comment by M-Zuber** [comment]
I apologize for never getting back to you, was this closed due to lack of response, or did the mentioned PR fix the issue?

**Comment by vjeux** [comment]
Oops sorry for closing without replying. I think that the merged issue is going to fix that problem. If you can try to reproduce on master that would be great. If it still reproduces, we can re-open and try to come up with another fix.

**Comment by M-Zuber** [comment]
Great,
Due to a combination of factors I may not get to checking it out for ~2 weeks, but if I find an issue I will report back here

**Comment by M-Zuber** [comment]
Thankfully I was not able to reproduce the issue, so this can stay closed
