### ISSUE TITLE
API Prettier.Format throws an error

### ISSUE THREAD

**Issue by BigBin96** [prettier/prettier#9801]
This is the first time I have used Prettier，Is there something wrong with my operation

**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: API
- Runtime: Node.js v14.15.0 Chrome v87
- Operating System: Windows

**Steps to reproduce:**
The install
`
npm install --save-dev --save-exact prettier
`

The runtime is as follows
`
const prettier = require("prettier");
let res = prettier.format("foo ( );", { semi: false, parser: "babel" });
`

**Expected behavior:**
res -> "foo()"

**Actual behavior:**
Console throws an error -> "Uncaught Error: Couldn't resolve parser "babel". Parsers must be explicitly added to the standalone bundle."

**Comment by fisker** [comment]
In browser, you need import the parsers yourself, see https://prettier.io/docs/en/browser.html

**Comment by BigBin96** [comment]
I tried to introduce a parser. But the browser throws another error
`Uncaught TypeError: Cannot read property 'languages' of undefined`

My version of the package
`
"devDependencies": {
    "@babel/parser": "^7.12.7",
    "prettier": "^2.2.1"
  }
`

The running code is as follows
```
import prettier from 'prettier';
import babelParser from '@babel/parser';

prettier.format("let a = 6  ;", {
   parser: "babel",
   plugins: [babelParser],
})
```

**Comment by BigBin96** [comment]
> 在浏览器中，您需要自己导入解析器，请参阅https://prettier.io/docs/en/browser.html

I tried to introduce the parser, but threw other errors
`Uncaught TypeError: Cannot read property 'languages' of undefined`

My NPM package version
```
"devDependencies": {
    "@babel/parser": "^7.12.7",
    "prettier": "^2.2.1"
  }
```

The code that I execute
```
import prettier from 'prettier';
import babelParser from '@babel/parser';

prettier.format("let a = 6  ;", {
    parser: "babel",
    plugins: [babelParser]
})
```

**Comment by fisker** [comment]
This is a prettier parser(also called plugin)

`https://unpkg.com/prettier@2.2.1/parser-babel.js`
`https://unpkg.com/prettier@2.2.1/esm/parser-babel.mjs`


```js
import prettier from 'prettier/standalone';
import parserBabel from 'prettier/parser-babel';

prettier.format("let a = 6  ;", {
    parser: "babel",
    plugins: [parserBabel]
})
```

**Comment by fisker** [comment]
I'm going to close this issue, if you have any further qustions, feel free to ask.

**Comment by BigBin96** [comment]
> I'm going to close this issue, if you have any further qustions, feel free to ask.

No problem, thanks

**Comment by vjeux** [comment]
Would be really nice to improve the error message ("Couldn't resolve parser "babel". Parsers must be explicitly added to the standalone bundle.") and [documentation](https://prettier.io/docs/en/api.html). It's very unclear how to do so within an npm module.

**Comment by fisker** [comment]
> Would be really nice to improve the error message

Already did https://github.com/prettier/prettier/blob/9f5135f62b83db424643058fd6bba15540c50cb0/src/main/parser-and-printer.js#L25-L28

> and [documentation](https://prettier.io/docs/en/api.html)

https://github.com/prettier/prettier/pull/14365
