### ISSUE TITLE
HTML/Vue: How to wrap attributes without 'print-width'?

### ISSUE THREAD

**Issue by jianhee** [prettier/prettier#9828]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDOAbgOYUVj5VUC8xIAlpFALS06nRmTwAnLnj4ALLgBM5CDiBhiArnGFlCqAPSCS5SoJHM8rZT2gD6NunYeDHtp4K0VxkmfMVRlqjS0dfXpDPUxcAjhCEAAaEAgsGC5oKmRQcTEIAHcABXEENJQ8HGy8AE80+IAjMTwwAGs4GABlLHquKDpkALh4uAxquAVhgBk8LrU8OjgAMQgxDAJkruQQPDUYCDiQaRgMHAB1WXgqdrA4FsKuZJob8rWwVh3OqjgxGFy6uiXkADMSm94gArKgADwAQnVGs0WngMHBRp04P9AX0QKCwS1OnQcHAAIpqCDwVE4IEgdpiN5iNbVPBDHA7LASWCHeQwaTIAAcAAZ4syIG9DnUsGtmXBqTQUfEAI5E+BfRJFdZUPhQODDYY7MRwOVcHVfaa-JAAsnot4YLg9dTmnF4wnElEmtHxGD0tlyDnIABMrrqXBwOIAwhAMMaQBKAKw7NRvAAq9KKpvJNA0AEkoL5WmAJEkAIKZlowcp40lvAC+5aAA)
```sh
--parser babel
```

**Input:**
```jsx
<template>
  <svg    class="icon-svg"    aria-hidden="true"  ></svg>
  <svg    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg"    aria-hidden="true"  ></svg>
</template>
```

**Output:**
```jsx
<template>
  <svg class="icon-svg" aria-hidden="true"></svg>
  <svg
    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg"
    aria-hidden="true"
  ></svg>
</template>;

```

**Expected behavior:**
```jsx
<template>
  <svg
    class="icon-svg"
    aria-hidden="true"
  ></svg>
  <svg
    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg"
    aria-hidden="true"
  ></svg>
</template>;

```

**Comment by thorn0** [comment]
You can't tweak that since configurability is a non-goal for Prettier.
