### ISSUE TITLE
comma after destructuring

### ISSUE THREAD

**Issue by mvolkmann** [prettier/prettier#983]
Should prettier be adding the comma at the end of line 2 below?
````
const DataInput = (
  {autoFocus, className = '', label, name, onChange, onKeyPress, value},
) => (
````

**Comment by vjeux** [comment]
Yes, you may want to add a second argument to the arrow function that would add this `,`

**Comment by mvolkmann** [comment]
I don't understand. I only have one parameter which is the object I am destructuring. The comma at the end isn't needed. Is that a style choice that prettier has made?

**Comment by vjeux** [comment]
Prettier only add it if you use the option `--trailing-comma`

**Comment by yamafaktory** [comment]
@mvolkmann adding the option righteously mentioned by @vjeux is in fact not a style choice but a  way to support the following upcoming ECMAScript feature https://github.com/tc39/proposal-trailing-function-commas (currently in stage 4). [Babel supports it for example](https://babeljs.io/docs/plugins/syntax-trailing-function-commas/).
