### ISSUE TITLE
Markdown custom blocks ::: content indentations

### ISSUE THREAD

**Issue by revelt** [prettier/prettier#9839]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZSkAICGAHAlgHSgBMI4BnAZQgFs4YALXKAcwAoBKdYQ9dJ7AK4wAjABoefKIJgAmQgF9CaFKJARsMXNDLJQmAE76IAdwAKBhDpSYANscwBPHaoBG+zGADWdCtg9NmZBh9AThVOGoXOCIiaIAZTBYBTGY4ADEIfWpMGE0WZBBMIQgQVXoYahsAdUZ4Mj8wOApLXE0AN1aHArAyZxAmMjh9GFN3ZmzkADNbQdUAKzIADwAhdy8fTFo4pjgpmbCQBcWKAJs4AEUBCHg9m1mQP31B-QLs-U8SYyhSh-0mGCquCIDGQAA4AAyqbBGQZVdzYArQ8hDNq7VQARyu8FG6ishTIAFooHBotEfvo4JjcBTRikJkhpncDoNqLggiFmacLljdgz9qoYJgXIDgfRkDIBe5cDYAgBhGj0kDkACsPwEgwAKkKrIz7m1QgBJYgIGAUMB-DQAQWIFBgDjOt0G8nkQA)

**Input:**

```markdown
::: api
doesSomething() {
  input1,
  input2
}
:::
```

**Output:**

```markdown
::: api
doesSomething() {
input1,
input2
}
:::
```

**Expected behavior:**

Indentations to be kept intact,

```markdown
::: api
doesSomething() {
  input1,
  input2
}
:::
```

## Background

As you know, markdown's [custom blocks](https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html) can be used to customize the appearance of content blocks. In my case, I use custom blocks `:::` to style the code snippets alternatively from the usual <code>&#x60;&#x60;&#x60;</code> blocks, to generate alternative `<pre><code>` wrappers:

![custom-blocks](https://user-images.githubusercontent.com/8344688/101319870-969cc280-385a-11eb-9627-f3592a240909.png)

(That's [eleventy](https://www.11ty.dev/) + [markdown-it-fence](https://github.com/geekplux/markdown-it-fence)).

When sources are processed with Prettier, indentations are removed:

![no-indentations](https://user-images.githubusercontent.com/8344688/101322124-6ce59a80-385e-11eb-94e5-15c92a40edcd.png)

I understand, custom code blocks can be used for anything, and for non-`pre` code generation, indentations are not needed. That's a really edge-case, Prettier deals with markdown really well.

**Comment by thorn0** [comment]
Is it the same syntax support for which is requested in #8640 or is it a different thing?

> I understand, custom code blocks can be used for anything, and for non-pre code generation, indentations are not needed.

Right... So how can Prettier decide whether the indentation should be kept?

**Comment by revelt** [comment]
#8640 is different angle, inner whitespace within custom blocks. This is for indentations specifically which #8640 doesn't address.

> So how can Prettier decide whether the indentation should be kept?
It's impossible.

I'd say it would be best if there was an option to disable processing of markdown custom blocks. Like in #8640, there's too much unknowns of what's inside them...

Also, another argument in favor of not processing contents of custom blocks is they are quite rare side of the markdown spec; if anybody is using them they are more likely to format intentionally that way...

**Comment by thorn0** [comment]
> custom blocks is they are quite rare side of the markdown spec

What spec do you refer to here? Does there exist a spec for this syntax?

**Comment by revelt** [comment]
> What spec do you refer to here? Does there exist a spec for this syntax?

I meant implicit spec, not explicit. The https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html is the best written spec I can find. 

Generally, backwards-engineering the [markdown-it-fence](https://github.com/geekplux/markdown-it-fence), I can see that there can be at least [three consecutive colons](https://github.com/geekplux/markdown-it-fence/blob/master/test/index.test.js#L27) followed by zero or more whitespace and optionally, on the same line, a string (also that's seen in #8640 examples, separator space is optional) is the opening. The amount of closing colons seem to be mirrored to the opening-ones.

That's the best specification I can extract. 

Georgii, thank you for looking deeply into this.

**Comment by thorn0** [comment]
In R Markdown, Pandoc, and Docusaurus, this syntax is used as a container for Markdown content whereas using it as an alternative syntax for code blocks doesn't seem to be widespread at all. Unfortunately, I see no convincing reason to preserve the indentation and not to parse the content as Markdown. If you really need to use that syntax this way, you can use `<!-- prettier-ignore-start -->`/`<!-- prettier-ignore-end -->` to exclude it from formatting, but probably if you should just use the standard syntax for code blocks with an extra marker in the [info string](https://spec.commonmark.org/0.29/#example-113) that would trigger the alternative rendering, Prettier [has not problems](https://prettier.io/blog/2020/11/20/2.2.0.html#align-code-block-language-detection-with-other-popular-tools-9365httpsgithubcomprettierprettierpull9365-by-kachkaevhttpsgithubcomkachkaev) with that. I'm closing the issue in favor of #8640.
