### ISSUE TITLE
Closing paren in chain should be same indentation as invoked metod

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#984]
Might be a misleading title, sorry about that...

Going from 0.21.0 to 0.22.0 gives the following diff:

```diff
diff --git i/check.js w/check.js
index 144fe80..e3aa3de 100644
--- i/check.js
+++ w/check.js
@@ -29,11 +29,12 @@ function checkContent(contentPromise, savePatchToDisk, directory) {
       });
     })
     .filter(({ hash, es3Hash }) => hash !== es3Hash)
-    .map(({ filename, content, es3Content }) => Promise.props({
-      filename,
-      patch: createPatch(filename, content, es3Content),
-      textDiff: diffChars(content, es3Content),
-    }))
+    .map(({ filename, content, es3Content }) =>
+      Promise.props({
+        filename,
+        patch: createPatch(filename, content, es3Content),
+        textDiff: diffChars(content, es3Content),
+      }))
     .tap(arr => {
       if (savePatchToDisk) {
         return Promise.all(
@@ -61,10 +62,11 @@ export default function(files = [], { savePatchToDisk, directory } = {}) {
     return filename;
   });
 
   return checkContent(readFilesAsPromise, savePatchToDisk, directory);
 }
```

I would want it to become

```diff
diff --git i/check.js w/check.js
index 144fe80..e3aa3de 100644
--- i/check.js
+++ w/check.js
@@ -29,11 +29,12 @@ function checkContent(contentPromise, savePatchToDisk, directory) {
       });
     })
     .filter(({ hash, es3Hash }) => hash !== es3Hash)
-    .map(({ filename, content, es3Content }) => Promise.props({
-      filename,
-      patch: createPatch(filename, content, es3Content),
-      textDiff: diffChars(content, es3Content),
-    }))
+    .map(({ filename, content, es3Content }) =>
+      Promise.props({
+        filename,
+        patch: createPatch(filename, content, es3Content),
+        textDiff: diffChars(content, es3Content),
+      })
+    )
     .tap(arr => {
       if (savePatchToDisk) {
         return Promise.all(
@@ -61,10 +62,11 @@ export default function(files = [], { savePatchToDisk, directory } = {}) {
     return filename;
   });
 
   return checkContent(readFilesAsPromise, savePatchToDisk, directory);
 }
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22function%20checkContent(contentPromise%2C%20savePatchToDisk%2C%20directory)%20%7B%5Cn%20%20return%20contentPromise%5Cn%20%20%20%20.map((%7B%20content%2C%20filename%20%7D)%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20const%20hash%20%3D%20hashString(content)%3B%5Cn%20%20%20%20%20%20const%20es3Content%20%3D%20transform(content)%3B%5Cn%20%20%20%20%20%20const%20es3Hash%20%3D%20hashString(es3Content)%3B%5Cn%5Cn%20%20%20%20%20%20return%20Promise.props(%7B%5Cn%20%20%20%20%20%20%20%20filename%2C%5Cn%20%20%20%20%20%20%20%20content%2C%5Cn%20%20%20%20%20%20%20%20hash%2C%5Cn%20%20%20%20%20%20%20%20es3Content%2C%5Cn%20%20%20%20%20%20%20%20es3Hash%2C%5Cn%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20%7D)%5Cn%20%20%20%20.filter((%7B%20hash%2C%20es3Hash%20%7D)%20%3D%3E%20hash%20!%3D%3D%20es3Hash)%5Cn%20%20%20%20.map((%7B%20filename%2C%20content%2C%20es3Content%20%7D)%20%3D%3E%20Promise.props(%7B%5Cn%20%20%20%20%20%20filename%2C%5Cn%20%20%20%20%20%20patch%3A%20createPatch(filename%2C%20content%2C%20es3Content)%2C%5Cn%20%20%20%20%20%20textDiff%3A%20diffChars(content%2C%20es3Content)%2C%5Cn%20%20%20%20%7D))%5Cn%20%20%20%20.tap(arr%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20if%20(savePatchToDisk)%20%7B%5Cn%20%20%20%20%20%20%20%20return%20Promise.all(%5Cn%20%20%20%20%20%20%20%20%20%20arr.map(res%20%3D%3E%20writeFile(path.join(directory%2C%20%60%24%7Bpath.basename(res.filename)%7D.patch%60)%2C%20res.patch))%5Cn%20%20%20%20%20%20%20%20)%3B%5Cn%20%20%20%20%20%20%7D%5Cn%5Cn%20%20%20%20%20%20return%20Promise.resolve()%3B%5Cn%20%20%20%20%7D)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Agreed, https://github.com/prettier/prettier/pull/927 intends to apply your suggestion. I can't test right now but I think it would.

**Comment by SimenB** [comment]
Yeah, the changed test there looks like the fix I want :smile:

**Comment by jlongster** [comment]
That PR has been merged

**Comment by SimenB** [comment]
Having installed from master, I can confirm it's fixed 😄
