### ISSUE TITLE
Broken Link (to babeljs.io) in docs

### ISSUE THREAD

**Issue by maxprehl** [prettier/prettier#9855]
Found a dead link while browsing the docs at https://prettier.io/docs/en/options.html#trailing-commas

There's a link on the word "transform" to: https://babeljs.io/docs/plugins/syntax-trailing-function-commas/

It ends in a 404 on their site.

Not sure if the link should just be removed or if there could be a content update here to explain what a "transform" is.

In your repo the page in question is at https://github.com/prettier/prettier/blob/master/docs/options.md#trailing-commas

**Comment by fisker** [comment]
Thanks, I'll fix
