### ISSUE TITLE
Module not found: 'typescript-eslint-parser'

### ISSUE THREAD

**Issue by jimmyhmiller** [prettier/prettier#986]
I am trying to import prettier in a create-react-app to format some code snippets, (not trying to using it **on** the project but *in* the project) but I am getting the following error:

```javascript
Error in ./~/prettier/src/parser.js
Module not found: 'typescript-eslint-parser' in /Users/jimmyhmiller/Documents/Code/PlayGround/debug-prettier/node_modules/prettier/src

 @ ./~/prettier/src/parser.js 58:19-54
```

I've put up an [example project](https://github.com/jimmyhmiller/PlayGround/tree/master/debug-prettier). The only change is to `yarn add prettier` and to import it.

I'm guessing that this is because of [the decision](https://github.com/prettier/prettier/pull/915#issuecomment-285168443) to move `typescript-eslint-parser` to devDependencies.

**Comment by vjeux** [comment]
Thanks, we need to make it not directly call require so that static module loaders do not see it yet. It also broke all our release generation.

```js
require('typescript-eslint-parser');
```

to

```js
var r = require;
r('typescript-eslint-parser');
```

**Comment by go1t** [comment]
I'm using prettier to format code snippet in create-react-app as well and got this error today :(

**Comment by CompuIves** [comment]
I believe this issue still exists. I have an example project here: https://github.com/CompuIves/prettier-import-test

When you run `yarn start` you get this message:
![screen shot 2017-04-23 at 18 47 10](https://cloud.githubusercontent.com/assets/587016/25315455/55097a3e-2855-11e7-83c6-f3cb0eb91b08.png)

I encountered the same when doing this with CodeSandbox, the project can still compile, but HMR, for example, ceases to work and I get console errors.

When I surround the contents of the function in a try...catch block it turns into a warning instead of an error.

**Comment by emi600** [comment]
REACT_APP_SECRET_CODE=abcdef,CodeSandbox, the project can still compile, but HMR, for example, ceases to work and I get console errors.

**Comment by longsangstan** [comment]
Same problem for me. In my case the project cannot even compile (using npm start).
I am using create-react-app and "prettier": "^1.3.1".

**Comment by varenya** [comment]
Is there a fix or workaround for this? the issue seems to be closed but few people including me are still facing the issue.

**Comment by vjeux** [comment]
Someone needs to find a better workaround for it. But, the good news is that thanks to @azz, typescript support is getting real close to becoming usable so we'll add proper typescript dependency to prettier real soon and this issue will disappear on its own.

**Comment by pascalduez** [comment]
Same issue while trying to import `prettier` in a Webpack context (storybook).

**Comment by vjeux** [comment]
If someone wants to improve the require hack for typescript that would be great.

**Comment by azz** [comment]
This shouldn't be an issue anymore.
