### ISSUE TITLE
Don't add space after parens and before string literal

### ISSUE THREAD

**Issue by brunolemos** [prettier/prettier#987]
#  styled.View
**Correct: no changes**
```js
export const StyledView = styled.View``;
```

# styled(MyComponent)
**Wrong, added weird space)**
```diff
-export const MyStyledComponent = styled(MyComponent)``;
+export const MyStyledComponent = styled(MyComponent) ``;
```

**Comment by vjeux** [comment]
Could you update to the latest version of prettier, it doesn't seem to repro on 0.22

https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20const%20MyStyledComponent%20%3D%20styled(MyComponent)%20%60%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by brunolemos** [comment]
@vjeux oh it would be interesting to have a version picker in this live parser!

I'll wait this to test again: https://github.com/esbenp/prettier-vscode/issues/49

**Comment by vjeux** [comment]
It would be nice indeed. But hopefully won't be necessary for long. The goal is to converge quickly to a stable version. In a month or two we should arrive at it if things keep going as well as they've been so far.
