### ISSUE TITLE
Typescript types with generics does not respect printWidth

### ISSUE THREAD

**Issue by olegshilov** [prettier/prettier#9874]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwCU4BHAVzgGcYA5dGAETgEMAbAQTBgCW0PAF48AIQ504fQdAA87bnVlCoAFWL0AdGQCiARQCqegMrqA+oz0ANS6z08AMgD4A3CAA0ICBjlQ6ZFAObGwIAHcABRCEQJRucI5CQO8AI2wOMABrOBhTDEyBKABzZBhsWm84AFtUuAATeoanDhLqDmK4ADEcao4YQRLkEA5qGAgvEAALGGquAHUpgXg6ArA4U1jlgQA3ZcJhsDoUkCLpXEiM4r7kADNlOG8AKzo0cQzs3NMOargnIrgdwez1epiKxS4cAM1Ag8CBXGk3gK2HOwyIJDoYGwAj8kww2Ng8wE9RgU2QAA4AAxIsLSeYZDDDfH0ODYHaA7w0WFwS6+OIjOgAWigcAaDUm2Co1AEksuHRuSHuCMeIGk1QEZQqKro4Mh0O58MRIBgHFSRJJZKQACZvOUOAIuOCAMIQaoK1B0ACsk2o0nUpriSqNO1oAEkoE1YKYsTiYDwI6YiJDDXAAL6poA)
```sh
--parser typescript
--print-width 80
```

**Input:**
```tsx
export type RequestNextDealAction = BaseAction<DealsActionTypes.REQUEST_NEXT_DEAL>;
```

**Output:**
```tsx
export type RequestNextDealAction = BaseAction<DealsActionTypes.REQUEST_NEXT_DEAL>;

```

**Expected behavior:**
```tsx
export type RequestNextDealAction = BaseAction<
  DealsActionTypes.REQUEST_NEXT_DEAL
>;

```

**Comment by maojj** [comment]
same problem

**Comment by attilacsanyi** [comment]
Not sure how, but [official prettier still having issues ](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwCU4BHAVzgGcYA5dGAETgEMAbAQTBgCW0PAF48AIQ504fQdAA87bnVlCoAFWL0AdGQCiARQCqegMrqA+oz0ANS6z08AMgD4A3CAA0ICBjlQ6ZFAObGwIAHcABRCEQJRucI5CQO8AI2wOMABrOBhTDEyBKABzZBhsWm84AFtUuAATeoanDhLqDmK4ADEcao4YQRLkEA5qGAgvEAALGGquAHUpgXg6ArA4U1jlgQA3ZcJhsDoUkCLpXEiM4r7kADNlOG8AKzo0cQzs3NMOargnIrgdwez1epiKxS4cAM1Ag8CBXGk3gK2HOwyIJDoYGwAj8kww2Ng8wE9RgU2QAA4AAxIsLSeYZDDDfH0ODYHaA7w0WFwS6+OIjOgAWigcAaDUm2Co1AEksuHRuSHuCMeIGk1QEZQqKro4Mh0O58MRIBgHFSRJJZKQACZvOUOAIuOCAMIQaoK1B0ACsk2o0nUpriSqNO1oAEkoE1YKYsTiYDwI6YiJDDXAAL6poA)with the generic example above.

Thanks for the feedback how to achieve the expected format within 80 columns.
