### ISSUE TITLE
A // prettier-ignore comment after an object key is increasingly added before the object key on each run

### ISSUE THREAD

**Issue by dmnsgn** [prettier/prettier#9877]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9jyowYBLaPeAZxgAoBKPYAHSh482ODHLYhAocLwBbUjGyM0SPAHp1eDKJhM42ALSMA5lBxxBs2VDgB3PADFKERQGYATAEFs2UgE9OAG0razwABgAaCMjQ6wBGaKi42US8RJThKPSUgF1uWJkAXwBuQSLBEEiQCAwmaDZkUFJfCDsABRaERpRSSjsAxuqAIz8wAGsxAGUMUjBGKBNkJXI4arg5YbgCIgIAGVJF8lITOEccBT0Fpd7yGAgqkAALGDlKAHUnxnZZsDgp7rfRgAN2+-mQ4DYQxACzYBhg7T8JgUyDIlDh1QAVmw0AAhMaTGBTUhyOB7BZwVF9DEgbFoKbXShwACK5Ag8Cp6LWIFm2Dh2Ahw1IW0ojx0Cxg70YBBgT2QAA4ojzsBA4e8-BgITo4PzgZTqgBHNnwRG1HogUhsQy2bbbR6iI2MUSIk4opBomlwuSMZbYVbVNiMlnGynu6ncmDCqUyuVIDzVJSkRiUa4AYQgcjdqDYAFZHuQ4QAVYU9D3c4GrACSUCIsCmYGUdS8NamMH8TM5cKKRSAA)
```sh
--parser babel
```

**Input:**
```jsx
export default function test() {
  return {
    matrix: // prettier-ignore
      new Float32Array([
      0, 0,
      1, 0,
      1, 1,
      0, 1
    ]),
  };
}

```

**Output:**
```jsx
export default function test() {
  return {
    // prettier-ignore
    matrix: // prettier-ignore
      new Float32Array([
      0, 0,
      1, 0,
      1, 1,
      0, 1
    ]),
  };
}

```

**Second Output:**
```jsx
export default function test() {
  return {
    // prettier-ignore
    // prettier-ignore
    matrix: // prettier-ignore
      new Float32Array([
      0, 0,
      1, 0,
      1, 1,
      0, 1
    ]),
  };
}

```

`// prettier-ignore` not to be prepended before `matrix` key.

**Comment by fisker** [comment]
This already fixed by https://github.com/prettier/prettier/pull/10666
I'm going to add test in #14406

**Comment by fisker** [comment]
Tests added in #14406
