### ISSUE TITLE
Inline decorator support

### ISSUE THREAD

**Issue by arackaf** [prettier/prettier#988]
Hi, regarding decorators, 

it looks like

```javascript
class C { 
    @observable a = 12;
    @computed get a1(){ return this.a + 1; };
    @action inc = () => this.a++;
}
```

is turned into

```javascript
class C {
  @observable
  a = 12;
  @computed
  get a1() {
    return this.a + 1;
  }

  @action
  inc = () => this.a++;
}
```

ie the decorator is split apart from the declaration.  I know decorators are pretty new (stage 2) but I think declarations like that are commonly kept on the same line.  And the normal, great rule of 60 chars is being ignored for the simple getter body.

Regardless of the defaults you guys decide on, do you think this should be configurable?

**Comment by bakkot** [comment]
As I understand it, Babylon at least is considering deprecating their current decorators plugin and eventually replacing it with one which better matches the current proposal's grammar. For a project like Prettier, it might not be worth trying to nail down stuff like this until the upstream parsers (and proposal) are more settled. (As an example of the problems with the current implementation, try using a decorator with a computed property.)

**Comment by arackaf** [comment]
Ha!  I actually report the computed, decorated name bug to the Babel folks :)

And yeah, the proposal for decorators definitely changed, but that seems orthogonal for prettier. The syntax for *using* a decorator is the same in either, so I wouldn't really see why this project would need to wait to decide how best to format such code.

**Comment by vjeux** [comment]
Can you update your version of prettier, we are now inlining those

**Comment by arackaf** [comment]
@vjeux - outstanding!  Truth be told I was only trying out your online demo - I assumed it would be latest.  Will definitely take a closer look now.

**Comment by vjeux** [comment]
The online demo IS the latest published version and those decorators are inline. I'm not sure what you are looking at?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5Cnclass%20C%20%7B%20%5Cn%20%20%20%20%40observable%20a%20%3D%2012%3B%5Cn%20%20%20%20%40computed%20get%20a1()%7B%20return%20this.a%20%2B%201%3B%20%7D%3B%5Cn%20%20%20%20%40action%20inc%20%3D%20()%20%3D%3E%20this.a%2B%2B%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by arackaf** [comment]
@vjeux was looking here :)

![image](https://cloud.githubusercontent.com/assets/11261266/23828463/dc07154e-0697-11e7-82fb-cd7ab1682725.png)

**Comment by vjeux** [comment]
Oh wow, this is ancient :p @jlongster would be nice to update it :)

**Comment by arackaf** [comment]
Indeed - glad I brought this up then - @jlongster this project looks tremendous! Great work
