### ISSUE TITLE
Introduce `htmlWhitespaceSensitivity` option for Handlebars

### ISSUE THREAD

**Issue by dcyriller** [prettier/prettier#9881]
I open an issue to discuss / track the progress on the following feature.

## Introduce the [HTML Whitespace Sensitivity](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) option for Handlebars

In the Handlebars printer, whitespaces are currently considered insentitive. The goal of this feature is to introduce a mode to treat whitespaces as _sensitive_. It will use html plugin's option: `htmlWhitespaceSensitivity`.

The following commands would then be supported:
```sh
yarn prettier --html-whitespace-sensitivity=ignore template.hbs
yarn prettier --html-whitespace-sensitivity=strict template.hbs
yarn prettier template.hbs # currently defaults to `ignore`
```

## Progress

I slice the feature this way to ease the review:

1. [Add snapshots for `htmlWhitespaceSensitivity=ignore` and  `htmlWhitespaceSensitivity=strict`](https://github.com/prettier/prettier/pull/9883). It might be pure duplication at this point. But it will be useful when a/ we will implement the `strict` mode, b/ we will switch the default to `strict`.
2. [Do a first implementation of `htmlWhitespaceSensitivity=strict` option](https://github.com/prettier/prettier/pull/9885).
3. Update the documentation for the option to take into account how it behaves for Handlebars.
4. [optional] Switch the default to `strict`. (note: this is not urgent, and we will have to go through a beta phase before merging that)

## Out of scope

html also has the possible `css` value (its default). It could be implemented later.

**Comment by thorn0** [comment]
@dcyriller Oops, we forgot to add a changelog entry in #9885. Could you submit a PR adding it?

**Comment by dcyriller** [comment]
Done ✅ in https://github.com/prettier/prettier/pull/10133 (I initially didn't add it because this mode was not user facing).
