### ISSUE TITLE
Weird linebreaks in arrow functions.

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#990]
prettier 0.21 would print this:

```js
jest.mock(
  '../SearchSource',
  () => class {
    findMatchingTests(pattern) {
      return {paths: []};
    }
  },
);
```

prettier 0.22 prints this:

```js
jest.mock(
  '../SearchSource',
  () =>
    class {
      findMatchingTests(pattern) {
        return {paths: []};
      }
    },
);
```

See https://github.com/cpojer/jest/blob/master/packages/jest-cli/src/__tests__/watch-test-name-pattern-mode-test.js#L30

**Comment by cpojer** [comment]
@vjeux informed me of PR https://github.com/prettier/prettier/pull/966

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/pull/1023 fixes it
