### ISSUE TITLE
Weird printing of type definition

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#991]
https://github.com/cpojer/jest/blob/master/types/HasteMap.js#L48

before:
```
export type FileMetaData = [
  /* id */ string,
  /* mtime */ number,
  /* visited */ 0|1,
  /* dependencies */ Array<string>,
];
```

after:
```
export type FileMetaData = [/* id */ string, /* mtime */ number, /* visited */
  | 0
  | 1, /* dependencies */ Array<string>];
```
@vjeux back to flow printing for you!

**Comment by vjeux** [comment]
Looks like for some reason we didn't implement flow type arrays breaks, so it has to break the "or". Should be easy to fix, thanks for reporting!
