### ISSUE TITLE
Remove superfluous prettier-ignore comments

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#992]
I'm adding a few `// prettier-ignore` comments for printing mistakes that I expect to be fixed in future versions of prettier. When a block is ignored, prettier should pretty-print it anyway and remove the comment if the nodes end up resulting in the same output. This way superfluous ignore comments won't stick around forever.

**Comment by vjeux** [comment]
Really good idea

**Comment by demoneaux** [comment]
Might not always be a good idea though. There might be some cases where people do want to stick to a certain format.

**Comment by cpojer** [comment]
I think you are misinterpreting the issue. It's about removing the comment
if the node is printing the same string with or without the annotation,
therefore indicating the comment is unnecessary.

**Comment by vjeux** [comment]
I'm doing some spring cleaning and while this would be useful, it's low pri and I'm not going to implement this so closing this issue. If someone is interested in building this, that would be a welcome addition.
