### ISSUE TITLE
Too many files open error with prettier cli

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#994]
I accidentally passed 10000 files to prettier which makes it crash on my Mac because it opens too many files in parallel.

See https://github.com/prettier/prettier/blob/master/bin/prettier.js#L214

Here are two solutions:

* Turn this into `fs.readFileSync`. All of prettiers code is CPU bound. The overhead of reading all files asynchronously actually makes prettier slower here.
* Throttle the FS operations or use graceful-fs.

Alternatively: add a way to actually exclude node_modules from the glob pattern. I couldn't make it work so I had to do my own filtering before calling prettier.

**Comment by vjeux** [comment]
To ignore files: https://github.com/prettier/prettier/issues/579

We need to put it in the Readme.

Also need to fix that error!
