### ISSUE TITLE
JSX: Turn attr={`hello`} into attr="hello" and attr={true} into attr

### ISSUE THREAD

**Issue by blixt** [prettier/prettier#9952]
Doing the above would help clean up JSX over time, since it's not uncommon for a property to use a template string, then simplify to just the string literal. But if the developer doesn't convert the template string format back to a literal string, it will look unnecessarily complex. The same is true for setting attributes to `true`. The code that's executed will still be the same.

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT77VwzrWcAPHRwA3fLhgk4AXmAADABaly+AO4168gL7461AIYBzIwYBG0uTGro4ugPQA+DtpAAaEBAAOuaAGdkUANqagg1AAVghACUAxI1AwBPAI8zQzAAa14AZS8DMBwoI2RrWw84AFszODo6GoAZAyL0YzgAMRoKgxhcIuQQA3QYCHcQRRgKkgpFHHg-PLA4bOjZsVnE-rA-FJBCvzhqGHDDIy7kVDj9jwArPwAPACF0rJhsgwq4esK4c8u4G-u2UKRmkAEV0BB4L8SFcQHlqPtqP0zOZSKMvNRCjAKDg6DBFMgABwABg8GIg+wohi8-QxcERoh+HgAjhD4MdvDEBn4ALRQOA1GqjHisnA8Y7GM5IC4w-4gfYVHAlGxyvzAsFsn7Sv4eGDmHF4glIABMusMOBIwIAwhAKlKQPSAKyjdD7AAq5hiMtholsAEkoHVYNkwJifABBQPZGCJaTQ-babRAA)
```sh
--parser babel
```

**Input:**
```jsx
function HelloWorld() {
  return <div title={`hello world`} draggable={true} />
}
```

**Output:**
```jsx
function HelloWorld() {
  return <div title={`hello world`} draggable={true} />;
}
```

**Expected output:**
```jsx
function HelloWorld() {
  return <div title="hello world" draggable />;
}
```

**Comment by sosukesuzuki** [comment]
Thank you for your reporting.

This is a not Prettier's job. Prettier should just format. You can use ESLint rules such as https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md and https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md.
