### ISSUE TITLE
Line breaks that were kept in prettier 1.19.1 are now flattened into one line in prettier 2.2

### ISSUE THREAD

**Issue by Roaders** [prettier/prettier#9958]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdWALAlgZwHQD6kUAZlgOYAEAvJTNvjBBADYBGAhgE4DC0Z5AK5cOTLukqTKeMFzii4ACgCUEqXgC2cLuSVNWnXvwo5VUKdLaCsLACYqA3CAA0ICAAcYWaDmShuXBAA7gAK3Ai+KBwsQRwAnr6ubCJgANZwMADK7hxgWFDkyDBcgnCucBpscLa21QAyHAWCHLoAYhBcGqJeBcggHIJMLiAYMBosAOrY8Dg5YHCZEVheAG7LcX1gOIkg+TjaMCEi5F3IJNH7rgBWOAAeAEIp6VkcWnX5cGcXZSA3t5n5cgsOAARUEEHgXxYlxAOS4+y4fRgcXccBwsiwnmG7i4+RgEywtnoyAAjAAmAAMrhxEH2ExE7j6OLR2hWn1cAEdwfAjh5Iv0cABaKBwarVYZyLlYORHFqnJDnaE-fYaLBFErKwHAsEQz4K76uGAcNgEokYZAAFkNIhsgL4GnlIDRAFZhoJ9gAVY2RRUwlalACSUFqsEyGM8AEFg5lkcCofsAL4JoA)
```sh
--parser typescript
--print-width 120
--tab-width 4
```

**Input:**
```ts

this._config = this.toolbarConfigurator
    .create()
    .merge(toolbarConfigs)
    .build();
```

**Output:**
```ts
this._config = this.toolbarConfigurator.create().merge(toolbarConfigs).build();

```

**Expected behavior:**

This code used to remain split over several lines in prettier 1.19.1 but now it is flattened to a single line. Can I change the config to allow it to remain split over multiple lines?

**Comment by alexander-akait** [comment]
Change print width to 80

**Comment by kachkaev** [comment]
You can also force new lines by adding a `//` comment in the middle of the chain:

```ts
this._config = this.toolbarConfigurator //
    .create()
    .merge(toolbarConfigs)
    .build();
```

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOgPqRQBmGA5gAQC8562OMEEANgEYCGATgMLQmkCuHNgw7kA9GIA6UcrPI4wHOMLgAKAJTS58gLZwOpNQ2btuvMlk0y5OFvwxMAJhoDcIADQgIABxgZoWMignBwQAO4ACpwIgShsTGFsAJ6BnixCYADWcDAAyt5sYBhQpMgwHPxwnnA6LHCOjvUAMmwl-GyGAGIQHDrCfiXIIGz8DB4gaDA6TADqmPBYBWBwuTEYfgBu60lDYFipIMVY+jARQqR9yETxx54AVlgAHgBCGdl5bHpNxXBXN1UgB6PXLFUhMOAARX4EHgfyYtxABQ4xw4QxgSW8cCwigwvnG3g4xRgMwwjnQyAAjAAmAAMngJEGOMyE3iGBKx+g2v08AEdofAzj5YsMsABaKBwer1cZKPkYJRnDqXJDXeEA446DBlCrq0HgqEw34q-6eGBsFgksloZAAFlNQgcoJ4OmVICxAFZxvxjgAVc2xVUIjaVACSUEasFyON8AEFw7l0eC4ccAL4poA)

**Comment by Roaders** [comment]
So there are no configuration options to revert to behaviour in 1.19? 

Guess I'll have to just roll back to 1.19...

**Comment by sosukesuzuki** [comment]
Yes, we have no option for this. Please see https://prettier.io/docs/en/option-philosophy.html and https://prettier.io/docs/en/options.html.

Btw we'll never add options for your problem, but the formatting for member chaining may be improved in future.
