### ISSUE TITLE
Weird line breaks for boolean expression inside JSX expression

### ISSUE THREAD

**Issue by jonathanewerner** [prettier/prettier#996]
Prettier reformats boolean expressions inside JSX expressions in a weird way:
```diff
-        {services && services.length > 0 && (
-          <List>
-            {services.map(this._renderServiceListItem)}
-          </List>
-        )}
+        {services &&
+          services.length > 0 &&
+          <List>
+            {services.map(this._renderServiceListItem)}
+          </List>}
```
Is this intentional? I would think that the original is much clearer in this case.

**Comment by vjeux** [comment]
We break on every single && when it doesn't fit in a single line. We are unlikely going to change this so I'm closing this task. Thanks for reporting it.
