### ISSUE TITLE
Is there a way to format the ts code into the following style?

### ISSUE THREAD

**Issue by rxliuli** [prettier/prettier#9961]
https://twitter.com/buildsghost/status/1301976526603206657

![EhGMhuAUcAANKba](https://user-images.githubusercontent.com/24560368/103182131-99457300-486e-11eb-827d-4137e6aa7b56.jpeg)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by rxliuli** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.

Well, I re-used the playground to create the problem, but the core is almost the same. . .

https://github.com/prettier/prettier/issues/9965
