### ISSUE TITLE
function params not being split even when exceeding max line length

### ISSUE THREAD

**Issue by tikotzky** [prettier/prettier#997]
input
```js
foo(
  (
    one, 
    two, 
    three, 
    four, 
    five, 
    six, 
    seven, 
    eight, 
    nine, 
    ten,
    eleven,
    twelve,
    thirteen,
    fourteen,
  ) => {},
);
```
output
```js
foo(
  (one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen) => {},
);
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22foo(%5Cn%20%20(%5Cn%20%20%20%20one%2C%20%5Cn%20%20%20%20two%2C%20%5Cn%20%20%20%20three%2C%20%5Cn%20%20%20%20four%2C%20%5Cn%20%20%20%20five%2C%20%5Cn%20%20%20%20six%2C%20%5Cn%20%20%20%20seven%2C%20%5Cn%20%20%20%20eight%2C%20%5Cn%20%20%20%20nine%2C%20%5Cn%20%20%20%20ten%2C%5Cn%20%20%20%20eleven%2C%5Cn%20%20%20%20twelve%2C%5Cn%20%20%20%20thirteen%2C%5Cn%20%20%20%20fourteen%2C%5Cn%20%20)%20%3D%3E%20%7B%7D%2C%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by tikotzky** [comment]
just tested a little more...
it looks like if you add a comment before the param then it formats it as expected...

input
```js
foo(
  // a comment
  (one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen) => {},
);
```

output 
```js
foo(
  // a comment
  (
    one,
    two,
    three,
    four,
    five,
    six,
    seven,
    eight,
    nine,
    ten,
    eleven,
    twelve,
    thirteen,
    fourteen,
  ) => {},
);
```
https://prettier.github.io/prettier/#%7B%22content%22%3A%22foo(%5Cn%20%20%2F%2F%20a%20comment%5Cn%20%20(one%2C%20two%2C%20three%2C%20four%2C%20five%2C%20six%2C%20seven%2C%20eight%2C%20nine%2C%20ten%2C%20eleven%2C%20twelve%2C%20thirteen%2C%20fourteen)%20%3D%3E%20%7B%7D%2C%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
This is a side-effect of https://github.com/prettier/prettier/pull/847
