### ISSUE TITLE
Only wrap the excess part.

### ISSUE THREAD

**Issue by gonnavis** [prettier/prettier#9977]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDOAbgOYUVj5VUC8xIAlpFALS06nRmTwAnLnj4ALLgBM5CDiBhiArnGFlCqAPSCS5SoJHM8rZT2gD6NunYeDHtp4K3zlGAJ5uQFcZIy8opQyqoaWjr69IYU1PSmLOycVvyuLhn26VmZdu5ynj70AExaAVKyCkqc4Zp+VDBeOHDKAEZ4YADWdGIQalBySGJwcgDckXoGpHqYuARwhCAANCAQWDBc0FTIoOK9AO4ACuII2yh4OPt4PssgrWIdnXAwAMpYHVxQdMi1K3AYrRGijkABk8F81Hg6HAAGIQMQYAgbL7IEB4NQwCC3aQwDA4ADqsngVHeYDgL1OXA2NCpXlRYFYt0+VDgYhghwedERyAAZhcWSsAFZUAAeACEHl1ni88Bg4CDPnBefy4ELRS9PnRmgBFNQQeDKnACkDvMQssSo9qAnC3LASWD4+QwaTIAAcAAYVnaICz8Q8sKi7XBzTQlSsAI56+ActZnNFUPhQOAjEa3YaRrjDDlQ7lIPlG1UgFkYLg-dSFqianVRpV5lUrGB4VqOuTO5DFBsPLg4TUAYQgGFzIGDAFZbmoWQAVJtnfPGmgaACSAwQrzAEnWAEEBi9Gs1DSyAL6HoA)

```shell
--parser babel
```

**Input:**

```js-jsx
<template>
  <svg    class="icon-svg"    aria-hidden="true"  ></svg>
  <svg    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg"  id="mysvg"  aria-hidden="true"  ></svg>
  <svg    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg"  id="mysvg2"  aria-hidden="true" style="background:red;"  ></svg>
</template>
```

**Output:**

```js-jsx
<template>
  <svg class="icon-svg" aria-hidden="true"></svg>
  <svg
    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg"
    id="mysvg"
    aria-hidden="true"
  ></svg>
  <svg
    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg"
    id="mysvg2"
    aria-hidden="true"
    style="background:red;"
  ></svg>
</template>;

```

**Expected behavior:**

```js-jsx
<template>
  <svg class="icon-svg" aria-hidden="true"></svg>
  <svg
    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg" id="mysvg"
    aria-hidden="true"
  ></svg>
  <svg
    class="icon-svg-svg-svg-svg-svg-svg-svg-svg-svg" id="mysvg2"
    aria-hidden="true" style="background:red;"
  ></svg>
</template>;

```

**Comment by sosukesuzuki** [comment]
I'm not familiar with HTML formatting but probably we cannot accept this suggestion.
/cc @fisker

**Comment by thorn0** [comment]
It's not clear what this issue is: a question or a proposal. If a question, then the answer is this isn't and won't be configurable, because configurability of formatting [goes against the project's goals](https://prettier.io/docs/en/option-philosophy.html). If a proposal, the current formatting is clearly more readable and thus won't be changed.
