### ISSUE TITLE
Publishing bundled dependencies and licencing

### ISSUE THREAD

**Issue by bradzacher** [prettier/prettier#9980]
To preface this issue: (a) I am not a lawyer, (b) I have *zero* knowledge or idea about how licencing 
works in any context (c) I am 100% okay with prettier bundling @typescript-eslint.

I am just seeking to understand how this all works legally - as I do not see any prior discussions about it, nor do I fully understand how licencing works myself.

Prettier's build bundles all of its dependencies together as part of its NPM package deployment.
However as part of this build - it does not include a dependency's LICENCE (unless that LICENCE is expressly included as a docblock).

A few examples of prettier's dependency's Licences:
- [typescript-estree](https://github.com/typescript-eslint/typescript-eslint/blob/85c27205713943be5e43937edb90d804b7959199/packages/typescript-estree/LICENSE) has a licence similar to MIT
- [babel](https://github.com/babel/babel/blob/2d35f5a8f7f575d87a350b6a0f14efd96091c35f/LICENSE) uses MIT licence
- [flow](https://github.com/facebook/flow/blob/96e2ae6e50401594a2fbffcce883cf7349a5a15a/LICENSE) uses MIT licence

Which all state some version of "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

Does this mean that prettier is violating dependency's licences by publishing a dependency's code without also publishing its licence?

In the general NPM world, I guess everyone "gets around this" because the package is a self-contained thing, and it's up to the original publisher to include the licence file (which most do).

Should prettier be doing something similar to [what typescript does](https://unpkg.com/browse/typescript@4.1.3/ThirdPartyNoticeText.txt) - where it includes a separate text file with its published package that lists the licences?

Or am I completely wrong about how the copyright licences work? (I seriously have no idea)

**Comment by brodybits** [comment]
I have also been concerned about the bundling of the parser code from TypeScript, which is under the Apache 2.0 license. The `prettierx` fork that I maintain does not do the bundling, uses Babel by default for TypeScript, and keeps TypeScript as an optional dependency.

**Comment by thorn0** [comment]
Thanks for bringing this up. Yes, this is something that has to be fixed.
Prettier should do the same thing Rollup does:
https://unpkg.com/browse/rollup@2.11.2/LICENSE.md
See "Licenses of bundled dependencies" in that file.

**Comment by fisker** [comment]
Don't know why this issue not close...

**Comment by fisker** [comment]
@bradzacher We'll include licenses in v3, but no promise when will it be released 😄

**Comment by fisker** [comment]
Licenses included in v2.6.0 https://unpkg.com/browse/prettier@2.6.0/LICENSE
