### ISSUE TITLE
Glimmer Handlebars incorrectly reformats use of array indexes

### ISSUE THREAD

**Issue by haveaguess** [prettier/prettier#9984]
Using PyCharm prettier integration : 

![image](https://user-images.githubusercontent.com/85821/103414796-512c9600-4b77-11eb-8283-597aa00253b6.png)

```sh
# Options:
--parser=glimmer
```

Here you can see the input and output in a git diff:

![image](https://user-images.githubusercontent.com/85821/103414730-0dd22780-4b77-11eb-90e1-7b33fa4572f4.png)

**Expected behavior:**

It should maintain the use of array indexes or error imho

**Comment by sosukesuzuki** [comment]
Please use the issue template.

**Comment by boris-petrov** [comment]
@haveaguess - this is actually unsupported syntax. Check from [this comment on](https://github.com/prettier/prettier/issues/4908#issuecomment-681618661).
