### ISSUE TITLE
prettier.io Homepage markdown not converted -> HTML

### ISSUE THREAD

**Issue by Yash-Singh1** [prettier/prettier#9986]
# Steps

- Go to prettier.io
- See the:
```markdown
# What is Prettier?
* An opinionated code formatter
* Supports many languages
* Integrates with most editors
* Has few options

# Why?
* You press save and code is formatted
* No need to discuss style in code review
* Saves you time and energy
* And more
```
That is not rendered in HTML.

# Screenshot

![Screenshot from 2020-12-31 17-01-46](https://user-images.githubusercontent.com/53054099/103431729-e3d63080-4b89-11eb-98db-136fccd58d35.png)

**Comment by sosukesuzuki** [comment]
It is intentional:
- https://github.com/prettier/prettier/blob/master/website/static/overrides.css#L146-L148
- https://github.com/prettier/prettier/blob/master/website/static/overrides.css#L160-L163
