### ISSUE TITLE
CLI - npm script failing due to single quote

### ISSUE THREAD

**Issue by wenfangdu** [prettier/prettier#9987]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI
- Runtime: Node v14.15.1
- Operating System: Windows 10

**Steps to reproduce:**
npm script
```json
{
  "scripts": {
    "test": "prettier --check --write '**/*.{ts,flow,json,css,scss,less,html,gql,graphql,md,yml,yaml}'"
  }
}
```

**Expected behavior:**
```bash
$ prettier --check --write '**/*.{ts,flow,json,css,scss,less,html,gql,graphql,md,yml,yaml}'
Checking formatting...
All matched files use Prettier code style!
Done in 0.67s.
```

**Actual behavior:**
```bash
$ prettier --check --write '**/*.{ts,flow,json,css,scss,less,html,gql,graphql,md,yml,yaml}'
Checking formatting...
[error] No files matching the pattern were found: "'**/*.{ts,flow,json,css,scss,less,html,gql,graphql,md,yml,yaml}'".
All matched files use Prettier code style!
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fisker** [comment]
You already know the problem, use `""`

**Comment by wenfangdu** [comment]
@fisker Yes, but I wonder why single quote is not allowed, could it be supported? So we could get rid of the `\` in npm scripts.

**Comment by fisker** [comment]
This is how `cmd.exe` works.

**Comment by wenfangdu** [comment]
@fisker I'm using git bash to run the script though, run `prettier --check --write '**/*.{ts,flow,json,css,scss,less,html,gql,graphql,md,yml,yaml}'` directly in git bash will work, but fails when used as a npm script, strange 😕.

**Comment by wenfangdu** [comment]
Does anyone know 🙏 ?
