### ISSUE TITLE
Require an easier way to use the lib in the browser.

### ISSUE THREAD

**Issue by AkiraVoid** [prettier/prettier#9991]
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: Chrome
- Runtime: Chrome V87
- Operating System: Windows

**Steps to reproduce:**

None

**Expected behavior:**

I'm using TypeScript to build a page. This page will display some not-formatted codes and I want to use Prettier to format them. There's nothing but the Prettier lib and its parser are TOO LARGE to deployment which made me cannot use webpack directly. I want to use cdn to solve this problem but the parser always not work if I use this way(I just use parser-babel plugin and parser `json`). The problem is, there's no function named "parserBabel", "parser-babel", "babel" or "json", and if I use 

```json
externals: {
    "prettier/parser-babel":"parserBabel"
}
```
the browser will throw an exception: `'parserBabel' is not defined`, because webpack seems always output `module.exports = parserBabel` to avoid this problem but there's function named `parserBabel` in `parser-babel.js`, and the name is suggested by your [docs](https://prettier.io/docs/en/browser.html). I think there should be an easier way to use the lib in browser.

(And by the way, the cdn `unpkg` was blocked by China, although `jsdelivr` can be an insteed, this is still a reason to my problem.)

**Actual behavior:**

None

**Comment by fisker** [comment]
I think  you are using `index.js` instead of `prettier/standalone.js`?

**Comment by AkiraVoid** [comment]
> I think you are using `index.js` instead of `prettier/standalone.js`?

No, I am using standalone.js:

```html
<script src="https://cdn.jsdelivr.net/npm/prettier@latest/standalone.js"></script>
```

**Comment by AkiraVoid** [comment]
> I think you are using `index.js` instead of `prettier/standalone.js`?

Here is the format code:
```typescript
prettier.format(JSON.stringify(error), {
    parser: "json",
    plugins: [parserBabel],
})
```
I replaced 'json' and 'parserBabel' with all possible words I know

**Comment by fisker** [comment]
Then the docs didn't say `parserBabel`, you should use global variable `prettierPlugins`, 

```html
<script>
  prettier.format("type Query { hello: String }", {
    parser: "graphql",
    plugins: prettierPlugins,
  });
</script>
```

**Comment by AkiraVoid** [comment]
> Then the docs didn't say `parserBabel`, you should use global variable `prettierPlugins`,
> 
> ```
> <script>
>   prettier.format("type Query { hello: String }", {
>     parser: "graphql",
>     plugins: prettierPlugins,
>   });
> </script>
> ```

TypeScript need an import statement and `prettierPlugins` should be an array, so I cannot use:
```typescript
import prettierPlugin from "prettier/parser-babel";
```
If I define a variable named 'prettierPlugin', it will be renamed by webpack

**Comment by fisker** [comment]
Will this work?

```js
externals: {
    "prettier/parser-babel":"prettierPlugins[0]"
}
```

**Comment by fisker** [comment]
Sorry, bad idea, won't work.

**Comment by fisker** [comment]
I think this should work, can you try it?

```js
prettier.format(JSON.stringify(error), {
    parser: "json",
    plugins: {
		json: parserBabel.json
	},
})
```


```js
externals: {
    "prettier/parser-babel":"prettierPlugins"
}
```

**Comment by AkiraVoid** [comment]
> I think this should work, can you try it?
> 
> ```js
> prettier.format(JSON.stringify(error), {
>     parser: "json",
>     plugins: {
> 		json: prettierPlugins.parsers.json
> 	},
> })
> ```
> 
> ```js
> externals: {
>     "prettier/parser-babel": "prettierPlugins"
> }
> ```

No...`plugins` can only be string[] or Plugin[]

**Comment by fisker** [comment]
> No...plugins can only be string[] or Plugin[]

No. Actually it's not, it can accept object.

**Comment by AkiraVoid** [comment]
> > No...plugins can only be string[] or Plugin[]
> 
> No. Actually it's not, it can accept object.

But the type definations is string[] or Plugin[]... Maybe you can fix the type definitions files?

**Comment by AkiraVoid** [comment]
```typescript
plugins: Array<string | Plugin>;
```

**Comment by fisker** [comment]
Can you try my solution first? Note, I updated my comment.

**Comment by AkiraVoid** [comment]
> I think this should work, can you try it?
> 
> ```js
> prettier.format(JSON.stringify(error), {
>     parser: "json",
>     plugins: {
> 		babel: prettierPlugins
> 	},
> })
> ```
> 
> ```js
> externals: {
>     "prettier/parser-babel": "prettierPlugins"
> }
> ```

I tried this and got a Complier Error

**Comment by AkiraVoid** [comment]
I found this comment in type definations:
```typescript
/**
* The plugin API is in a beta state.
*/
```

**Comment by fisker** [comment]
Can you ignore type checking?

**Comment by fisker** [comment]
The type info is not maintained in this repo, https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prettier

**Comment by AkiraVoid** [comment]
Now I got `Uncaught TypeError: Cannot read property 'json' of undefined` without type checking

**Comment by fisker** [comment]
> Now I got `Uncaught TypeError: Cannot read property 'json' of undefined` without type checking

Did you use the updated code? It should work, if still not working, can you post complied code?


```console
$ require('prettier/standalone').format('{}', {parser:'json', plugins: {babel: require('prettier/parser-babel')}})
'{}\n'
```

**Comment by AkiraVoid** [comment]
Not work. Compiled code:
```json
{ parser: "json", plugins: { babel: h.a } }
```

**Comment by fisker** [comment]
Can you figure a way to make it `{ parser: "json", plugins: { babel: prettierPlugins.babel } }`?


Maybe


```js
import parserBabel from 'prettier/parser-babel'

prettier.format(JSON.stringify(error), {
    parser: "json",
    plugins: {
		babel: parserBabel
	},
})
```


```js
externals: {
    "prettier/parser-babel": "prettierPlugins.babel"
}
```

?

**Comment by AkiraVoid** [comment]
Hi, I've just solved this problem. As you say, I should use `prettierPlugins`, but I cannot use type checking. That should be a type definations problem. Thanks for your help.

**Comment by fisker** [comment]
Can you share your solution and open an issue in [this repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prettier)?
